Initial upload of Vulnerateca Post-Exploitation Framework (VPEF)
rapid7/metasploit-framework pull request #10119
Opened 2018-05-31 16:43 UTC by AlbertoCoding

## Description

Vulnerateca Post-Exploitation Framework (VPEF), is a framework that will ease the process of post-exploitation. It will use only simple Linux commands (as `echo`) in the most standard way possible and unifying all this in a shell console emulating native Linux commands (as `ls`, `cat`, etc).

## Verification

List of steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] Get a valid remote shell session
- [ ] Load one of the following vpef post-exploitation modules:

1. `use post/linux/vpef/vpef_cat`
2. `use post/linux/vpef/vpef_ls`
3. `use post/linux/vpef/vpef_fingerprinting`

- [ ] Set session id (`set SESSION 1`)
- [ ] Review and set module options and run
- [ ] **Verify** the thing does what it should

## Example

`msfconsole`
`use auxiliary/scanner/ssh/ssh_login`
`set RHOST 192.168.1.1`
`set USERNAME admin`
`set PASSWORD admin`
`run`
`use post/linux/vpef/vpef_cat`
`set SESSION 1`
`set FILENAME /etc/passwd`
`run`

2018-05-31 18:13 UTC, wvu-r7 commented
Can we name this something other than "Vulnerateca Post-Exploitation Framework (VPEF)?" That name is too obscure, already trademarked, turned into an acronym, and exists within a greater framework already.

2018-05-31 18:15 UTC, wvu-r7 commented
Unless I guess Vulnerateca is your company. But this is really a contribution toward Metasploit Framework's post exploitation capabilities, so a generic name will suffice!

2018-05-31 18:28 UTC, jmartin-r7 commented
Please note: "Metasploit requires spaces instead of hard tabs"

See https://github.com/rapid7/metasploit-framework/wiki/Style-Tips

Travis tests are failing early due to `\t`.

2018-05-31 20:55 UTC, AlbertoCoding commented
Ok, thank you very much for the feedback!
I agree with you so I'm going to work on changing these things now.
By the way, do I need to create a new PR once I have all changes done on my repository, or if I just push to my branch [ AlbertoCoding: vpef ], changes will be shown here automatically?

2018-05-31 21:18 UTC, wvu-r7 commented
You can push to your branch. The PR will be updated accordingly.

2018-06-02 07:33 UTC, sempervictus requested changes
Cool stuff, thank you. We need to ween off specific binaries for more generic and quiet functionality.
The lib code might be better off integrated to the current library calls for access mechanisms so its used by all consumers - the framework is neat that way, you can shim in functionality for tons of existing code underneath.
Far as the modules go, they're not really collecting anything so much as displaying it... Storing loot, creds, notes, and any relevant named model properties is paramount for other modules to use this information down the line.
Agree with others that the naming piece is a bit much. Leave the company name in the email, and keep the code as close to existing standards as possible. There's free marketing enough from building cool things people use, branding doesn't belong in code outside a copyright header.

2018-06-02 07:36 UTC, bcoles commented
+1 for removing `pepa` from namespace
+1 for integrating this functionality into existing post libs

2018-06-04 18:58 UTC, wvu-r7 commented
Yep, agree with @sempervictus and @bcoles about working within the `Post` API.

That's the point I was trying to make in previous conversations. The API was designed to be portable, but then the code diverged from that. Make it right again. :)

Also, yeah, modules shouldn't be written for primitives, IMHO. You should add or enhance primitives in the library code, then write modules to use them. In your case, you'll be writing an interface.

2018-06-19 10:51 UTC, bcoles commented on lib/msf/core/post/linux/priv.rb
> +    if line[1] = 0
Is this meant to be `== 0` ? Also, the indentation is messed up.

2018-06-19 12:32 UTC, AlbertoCoding commented
Thank you everyone for all the suggestions and comments.
All the suggested fixes and changes have been already applied.

2018-06-19 19:54 UTC, wvu-r7 commented on modules/post/linux/manage/pseudo_shell.rb
> +$vhostname = ""
I think you'd want instance variables, not globals.

2018-06-25 14:45 UTC, bcoles commented
Has this PR been rebased with master? It looks like it nukes the changes made to [lib/msf/core/post/common.rb](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/post/common.rb) in 9eb5700fcbbed01dd210032cb801b133db5c217d.

2018-06-25 15:08 UTC, bcoles commented on lib/msf/core/post/file.rb
>    def read_file(file_name)
Same here.

Refactored, would look like this.

```ruby
  def read_file(file_name)
    if session.type == 'meterpreter'
      return _read_file_meterpreter(file_name)
    end

    return nil unless session.type == 'shell'

    if session.platform == 'windows'
      return session.shell_command_token("type \"#{file_name}\"")
    end

    if command_exists?('cat')
      return session.shell_command_token("cat \"#{file_name}\"")
    end

    # Result on systems without cat command
    session.shell_command_token("while read line; do echo $line; done <#{file_name}")
  end
```

2018-06-25 15:08 UTC, bcoles commented on lib/msf/core/post/linux/system.rb
> +      read_file("/proc/sys/kernel/hostname").chomp.to_s
Probably best to call `to_s` before `chomp`

2018-06-25 15:08 UTC, bcoles commented on lib/msf/core/post/linux/system.rb
> +    raise 'Unable to gather shell name'
Looks like this was changed in error?

2018-06-25 15:08 UTC, bcoles commented on lib/msf/core/post/linux/system.rb
> +    return str_pid
The method could be refactored:

```ruby
  def get_shell_pid
    cmd_exec("echo $$").to_s
  end
```

2018-06-25 15:08 UTC, bcoles commented on lib/msf/core/post/linux/system.rb
> +  def pid_uid(pid)
May as well use string interpolations, as you're using double quotes, calling `to_s` on `pid` then using string concatenation.

Also, the `return` is redundant.

Refactored:

```ruby
  def pid_uid(pid)
    read_file("/proc/#{pid}/status").to_s
  end
```

2018-06-25 15:08 UTC, bcoles commented on lib/msf/core/post/linux/system.rb
> +  def ips()
Style. No need to use brackets `()` in method definitions when the method takes no arguments.

2018-06-25 15:08 UTC, bcoles commented on lib/msf/core/post/linux/system.rb
> +  def interfaces()
Style. No need to use brackets `()` in method definitions when the method takes no arguments.

2018-06-25 15:08 UTC, bcoles commented on lib/msf/core/post/linux/system.rb
> +  def macs()
Style. No need to use brackets `()` in method definitions when the method takes no arguments.

2018-06-25 15:08 UTC, bcoles commented on lib/msf/core/post/linux/system.rb
> +  def listen_tcp_ports()
Style. No need to use brackets `()` in method definitions when the method takes no arguments.

2018-06-25 15:08 UTC, bcoles commented on lib/msf/core/post/linux/system.rb
> +  def listen_udp_ports()
Style. No need to use brackets `()` in method definitions when the method takes no arguments.

2018-06-25 15:08 UTC, bcoles commented on lib/msf/core/post/unix.rb
> +  def whoami()
Style. No need to use brackets `()` in method definitions when the method takes no arguments.

2018-06-25 15:08 UTC, bcoles commented on modules/post/linux/manage/pseudo_shell.rb
> +      message = error + ": " + cmd + ": Command not exist\n"
String interpolation.

```ruby
"#{error}: #{cmd}: Command does not exist\n"
```

2018-06-25 15:33 UTC, bcoles commented on lib/msf/core/post/linux/priv.rb
>    def is_root?
Refactored:

```ruby
  #
  # Returns true if running as root, false if not.
  # @return [Boolean]
  #
  def is_root?
    if command_exists?('id')
      user_id = cmd_exec('id -u')
      clean_user_id = user_id.to_s.gsub(/[^\d]/, '')
      if clean_user_id.empty?
        raise "Could not determine UID: #{user_id.inspect}"
      end
      return clean_user_id.match(/^0$/) ? true : false
    end

    user = whoami
    data = cmd_exec('while read line; do echo $line; done </etc/passwd')
    data.each_line do |line|
      line = line.split(':')
      return true if line[0] == user && line[3].to_i == 0
    end

    false
  end
```

2018-06-25 15:46 UTC, bcoles commented on modules/post/linux/manage/pseudo_shell.rb
> +  def parse_cmd(cmd)
Refactored, but could likely be cleaned up some more.

```ruby
  def parse_cmd(cmd)
    parts = cmd.split(' ')
    return '' unless parts.length >= 1    # I left this as an empty string as per the original code,
                                          # but I'm not sure if nil might be a better return value,
                                          # or raising an error instead

    cmd = parts[0]
    nargs = parts.length - 1
    HELP_COMMANDS.each do |linea|
      next unless linea[0] == cmd

      func = linea[1]
      if nargs >= 1
        if linea[2] == 1
          args = parts[1]
        else
          nargs = 0
        end
      else
        args = ''
      end

      return func, cmd, args, nargs
    end

    error = get_shell_name
    message = "#{error}: #{cmd}: Command does not exist\n"
    print message
    message
  end
```

2018-07-12 12:22 UTC, bcoles commented on modules/post/linux/manage/iptables_removal.rb
> +    cmd_exec("iptables -P INPUT ACCEPT")
It might be worth checking `command_exists? 'iptables'` first.

2018-07-12 12:22 UTC, bcoles commented on modules/post/linux/manage/iptables_removal.rb
> +    cmd_exec("ip6tables -P INPUT ACCEPT")
It might be worth checking `command_exists? 'ip6tables'` first.

2018-07-12 12:22 UTC, bcoles commented on modules/post/linux/manage/iptables_removal.rb
> +    cmd_exec("iptable -t mangle -F")
`iptables`

2018-11-11 05:49 UTC, bcoles commented
Bump @asoto-r7 @sempervictus @wvu-r7

2019-01-15 20:50 UTC, sempervictus reviewed
I'll check if this works under grsec, but if not, we may wanna check perms before we try a read, or we will be logged.

2019-01-18 16:54 UTC, wvu-r7 commented
Merging `master` again to pass the build.

2019-01-24 17:01 UTC, wvu-r7 commented
`whoami` and missing username in prompt fixed.

2019-01-24 17:23 UTC, wvu-r7 commented
Privilege-specific prompt character added. `SessionTypes` updated to include Meterpreter.

2019-01-24 17:28 UTC, merged

2019-01-24 17:34 UTC, wvu-r7 commented
# Release Notes

This adds a metashell (pseudoshell) focused on post-exploitation against Linux targets. Users can run the `post/linux/manage/pseudo_shell` module to enable this feature against a session.