Add new module: apacheflex_xxe
rapid7/metasploit-framework pull request #10116
Opened 2018-05-30 17:45 UTC by zamaralves

XXE vulnerability in Apache Flex BlazeDS/Adobe . The vulnerable code can be found in the BlazeDS Remoting/AMF protocol implementation. This module exploit this vulnerability. 

## Verification

- [ ] Start `msfconsole`
- [ ] `use auxiliaryscanner/http/apacheflex_xxe`
- [ ] ...
- [ ] **set rhost* <RHOST>
- [ ] **set rport ** <RPORT>
- [ ] **set file** </etc/passwd>

2018-05-30 19:11 UTC, acammack-r7 requested changes
Typos?

2018-05-30 19:11 UTC, acammack-r7 commented on modules/auxiliary/scanner/http/apacheflex_xxe.rb
> +    payload_post << "<!ENTITY xxe SYSTEM '#{datastore}' >]><foo>&xxe;</foo>"
Should this be `datastore['FILE']`?

2018-05-30 19:11 UTC, acammack-r7 commented on modules/auxiliary/scanner/http/apacheflex_xxe.rb
> +        OptString.new('FILE', [ true,  "File Acess", '/etc/passwd']),
Should be `File Access`.

2018-05-30 19:34 UTC, zamaralves commented on modules/auxiliary/scanner/http/apacheflex_xxe.rb
> +        OptString.new('FILE', [ true,  "File Acess", '/etc/passwd']),
I changed, thank you.

2018-05-30 19:36 UTC, acammack-r7 approved these changes

2018-05-30 20:00 UTC, zamaralves commented
@acammack-r7 , hi man.. I need write documentation ? 
Thanks.

2018-05-30 20:52 UTC, acammack-r7 commented
@zamaralves Yes, we encourage everyone to include include documentation when submitting a module, you can look at [this recent PR](https://github.com/rapid7/metasploit-framework/pull/10027/files#diff-27aa4316895002df2a1d852c1233fd7f) for an example. Even if it is just a longer description and some expected output it still helps a lot.

We also need PRs to come from individual topic branches so the PR history works correctly (see https://github.com/rapid7/metasploit-framework/blob/master/CONTRIBUTING.md#code-contributions). I will close this PR so you can reopen from a different branch.

2018-05-30 20:52 UTC, closed without merging

2018-05-30 20:56 UTC, zamaralves commented
Ok, @acammack-r7 . I'll changue and reopen this pull. 
Thanks.

2018-06-05 03:44 UTC, zamaralves commented
Hi @acammack-r7, i open https://github.com/rapid7/metasploit-framework/pull/10140 . . . I send documentation and PR individual.