Speedup general refactors
rapid7/metasploit-framework pull request #10659
Opened 2018-09-17 14:32 UTC by picatz

A bunch of tiny refactors, driven with `rubocop --only Performance`, aimed at improving performance and a smidgen of readability.

## Verification
- [ ] Start `msfconsole`
- [ ] ... Stuff **_should_** work normally. 😹

2018-09-17 15:27 UTC, acammack-r7 requested changes
Can't wait to get rid of all these extra `#sort`s! I think a couple need to become `#max_by`s, though.

2018-09-17 15:27 UTC, acammack-r7 commented on lib/msf/core/auxiliary/web.rb
> +        }.max
Pretty sure this will need to be `max_by &:size`, since we don't specify `<=>` for payloads IIRC.

2018-09-17 15:27 UTC, acammack-r7 commented on lib/msf/core/auxiliary/web/analysis/timing.rb
> +      payload = fuzzer.payloads.select{ |pl| seed.include?( pl ) }.max
Same as above

2018-09-19 15:06 UTC, picatz commented
@acammack-r7 I changed those two spots to use `max_by`, as you suggested 👍

2018-09-19 15:19 UTC, acammack-r7 approved these changes

2018-09-19 19:57 UTC, merged