add sip options_tcp docs
rapid7/metasploit-framework pull request #10797
Opened 2018-10-11 20:19 UTC by h00die

Adds docs for `auxiliary/scanner/sip/options_tcp`

## Verification

- [ ] Start `msfconsole`
- [ ] `use auxiliary/scanner/sip/options_tcp`
- [ ] `info -d`
- [ ] **Verify** parsing/spelling/formatting

2018-10-12 07:26 UTC, bcoles requested changes

2018-10-12 20:09 UTC, h00die commented
#8296

2018-10-13 12:49 UTC, h00die commented
nice finds, all fixed!

2018-10-14 08:32 UTC, bcoles approved these changes

2018-10-15 07:02 UTC, merged

2018-10-15 07:02 UTC, bcoles commented
Added `rn-no-release-notes` label. Not sure if there's a more appropriate label?