cisco aux scanner snmp docs
rapid7/metasploit-framework pull request #10800
Opened 2018-10-12 03:15 UTC by h00die

Adds documentation for `auxiliary/scanner/snmp/cisco_config_tftp` and `auxiliary/scanner/snmp/cisco_upload_file`

## Verification

- [ ] Start `msfconsole`
- [ ] `use auxiliary/scanner/snmp/cisco_config_tftp` or `auxiliary/scanner/snmp/cisco_upload_file`
- [ ] `info -d`
- [ ] **Verify** formatting/spelling/etc

2018-10-12 07:32 UTC, bcoles requested changes

2018-10-12 07:32 UTC, bcoles commented on documentation/modules/auxiliary/scanner/snmp/cisco_config_tftp.md
> +3. At this point the config is transfering, we need to wait a few seconds.  Lastly, we'll remove `666` from the system.
`transferring`

2018-10-12 07:32 UTC, bcoles commented on documentation/modules/auxiliary/scanner/snmp/cisco_config_tftp.md
> +Cisco's (documentation)[https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/15217-copy-configs-snmp.html#copying_startup]
Malformed markdown.

Should be:

```
[documentation](https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/15217-copy-configs-snmp.html#copying_startup)
```

2018-10-12 20:09 UTC, h00die commented
#8296

2018-10-13 12:53 UTC, h00die commented
all fixed, thanks for checking

2018-10-14 08:34 UTC, bcoles approved these changes

2018-10-15 07:05 UTC, merged