Bypassuac computerdefault
rapid7/metasploit-framework pull request #10886
Opened 2018-10-30 05:53 UTC by St0rn

Bypass UAC via computerdefault for metasploit.
Bypassuac_computerDefault.rb.

2018-10-30 15:10 UTC, bwatters-r7 commented
From the Travis testing:
```
[*] Running msftidy.rb in ./.git/hooks/post-merge mode
--- Checking new and changed module syntax with tools/dev/msftidy.rb ---
modules/exploits/windows/local/bypassuac_computerDefault.rb - [INFO] No CVE references found. Please check before you land!
modules/exploits/windows/local/bypassuac_computerDefault.rb - [ERROR] Incorrect disclosure date format
modules/exploits/windows/local/bypassuac_computerDefault.rb - [WARNING] Filenames must be lowercase alphanumeric snake case.
------------------------------------------------------------------------
------------------------------------------------------------------------
[*] This merge contains modules failing msftidy.rb
[*] Please fix this if you intend to publish these
[*] modules to a popular metasploit-framework repo
------------------------------------------------------------------------
```

2018-10-30 15:18 UTC, bwatters-r7 commented
Some strangeness going on with sanity tests.... the session is there, but it seems... _angry_
```
[-] WARNING! The following modules could not be loaded!
[-] 	/home/msfuser/rapid7/metasploit-framework/modules/exploits/windows/local/bypassuac_computerDefault.rb: Msf::Modules::MetasploitClassCompatibilityError Failed to load module (windows/local/bypassuac_computerDefault from /home/msfuser/rapid7/metasploit-framework/modules/exploits/windows/local/bypassuac_computerDefault.rb) due to Missing compatible Metasploit<major_version> class constant
...
> sessions -C sysinfo

Active sessions
===============

  Id  Type                   Information                      Connection
  --  ----                   -----------                      ----------
  1   meterpreter x64/win64  WIN2016X64\vagrant @ WIN2016X64  192.168.15.31:35942 -> 192.168.16.182:30001 (192.168.16.182)
...
> use post/test/railgun
[-] Failed to load module: post/test/railgun

```

2018-10-30 16:00 UTC, St0rn commented
Hi, Ok.
I chec kthis tomorrow.

2018-11-05 19:16 UTC, bwatters-r7 requested changes
Hi there, @St0rn!  Thanks for the PR, but I have a few suggestions.  The specifics are listed in the code review, but for some general things:
(1) You have used the existing fodhelper module as a base, and that's exactly what I would do, but you have not changed any of the fodhelper comments, so future devs working on this would be confused.  Please update the comments to this module.  
(2) You based this on an old branch, so testing is a bit off, because whoever tests it must merge it into master to be able to test it.  There's no need to rebase or merge yourself, as I will do that while landing, but in the future, please try to use the current master branch as the base.
(3) Right now, you are failing msftidy, so please run: `tools/msftidy.rb modules/exploits/windows/local/bypassuac_computerDefault.rb` to see the warnings/errors.
(4) For some more 'Ruby'-centric suggestions, please run rubocop on this module (https://github.com/rapid7/metasploit-framework/wiki/Using-Rubocop)
(5) Please add a documentation markdown file.  You can find a guide here: https://github.com/rapid7/metasploit-framework/wiki/Writing-Module-Documentation

2018-11-05 19:16 UTC, bwatters-r7 commented on modules/exploits/windows/local/bypassuac_computerDefault.rb
> +
Might as well align these '='

2018-11-05 19:16 UTC, bwatters-r7 commented on modules/exploits/windows/local/bypassuac_computerDefault.rb
> +        'DisclosureDate' => 'October 22 2018'
Oct 22 2018

2018-11-06 15:12 UTC, St0rn commented on modules/exploits/windows/local/bypassuac_computerDefault.rb
> +        # fodhelper.exe is x64 only exe
Yes, I have use a base exploit for computerDefault, sorry...

2018-11-06 15:15 UTC, St0rn commented
Thx bwatters-r7,
I check for modify the code this week.

2018-11-27 22:40 UTC, bwatters-r7 commented
This does not appear to work; I verified that the registry entries are created and launched the exe as required, and nothing fires off.

2018-11-27 23:15 UTC, wchen-r7 commented
Hmm so the module is looking for a `ComputerDefault.exe`, but my Windows 10 only has a `ComputerDefaults.exe` (notice the s).... could it be why it's not working?

2018-11-28 00:10 UTC, bwatters-r7 commented
@wchen-r7 nope.  You can play with my updated version of this here: https://github.com/bwatters-r7/metasploit-framework/tree/land-10886-updated

2018-11-29 21:57 UTC, bwatters-r7 commented
@wchen-r7 makes sense to me.  I am going to close it for mow, but I am happy to reopen it if @St0rn gets a chance to update it.

2018-11-29 21:57 UTC, closed without merging

2018-12-13 21:38 UTC, jmartin-r7 commented
Tagged `re-no-release-notes` for now due to inadvertent merge that has been reverted.