Add module to discover Ubiquiti devices
rapid7/metasploit-framework pull request #11338
Opened 2019-01-31 19:25 UTC by jhart-r7

This adds a scanner module to facilitate discovering devices made by Ubiquiti using a simple UDP protocol that operates on 10001.  This service can be disabled and can include metadata about the device in question including name, model, version, MACs and IPs.

## Verification

- [ ] Locate a network known or suspected to house Ubiquiti devices
- [ ] Start msfconsole
- [ ] Do: `use auxiliary/scanner/ubiquiti_discovery`
- [ ] Do: `set RHOSTS <some_targets>`
- [ ] Do: `run`

```
[+] a.b.c.d:10001 Ubiquiti Discovery metadata: {"ips"=>["a.b.c.d"], "macs"=>["f0:9f:c2:4c:aa:bb"], "name"=>"mFi4c5051", "model_short"=>"P8U", "firmware"=>"MF.ar933x.v2.0.25.1238.140624.1356"}
```

2019-01-31 20:22 UTC, bwatters-r7 commented
Cool; I scanned a quick selection of Ubuquiti stuff I have and got replies from an AP, a camera, and a powerstrip (all unmanaged).
```
msf5 auxiliary(scanner/ubiquiti/ubiquiti_discover) > show options

Module options (auxiliary/scanner/ubiquiti/ubiquiti_discover):

   Name       Current Setting   Required  Description
   ----       ---------------   --------  -----------
   BATCHSIZE  256               yes       The number of hosts to probe in each set
   RHOSTS     192.168.132.0/24  yes       The target address range or CIDR identifier
   RPORT      10001             yes       The target port (UDP)
   THREADS    1                 yes       The number of concurrent threads

msf5 auxiliary(scanner/ubiquiti/ubiquiti_discover) > run

[+] 192.168.132.191:10001 Ubiquiti Discovery metadata: {"ips"=>["192.168.132.191"], "macs"=>["f0:9f:c2:XX:XX:XX"], "name"=>"UVC G3", "model_short"=>"UVC G3", "firmware"=>"UVC.S2L.v4.2.59.67.ddb1280.180405.2139"}
[+] 192.168.132.193:10001 Ubiquiti Discovery metadata: {"ips"=>["192.168.132.193"], "macs"=>["80:2a:a8:XX:XX:XX"], "name"=>"UBNT", "model_short"=>"U7PG2", "firmware"=>"BZ.qca956x.v3.9.27.8537.180317.1235", "model_long"=>"UAP-AC-Pro-Gen2"}
[+] 192.168.132.224:10001 Ubiquiti Discovery metadata: {"ips"=>["192.168.132.224"], "macs"=>["f0:9f:c2:XX:XX:XX"], "name"=>"mFixxxxxx", "model_short"=>"P8U", "firmware"=>"MF.ar933x.v2.1.11.1309.150406.1423"}
[*] Scanned 256 of 256 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/ubiquiti/ubiquiti_discover) > 
```

2019-01-31 21:34 UTC, wvu requested changes

2019-01-31 21:34 UTC, wvu-r7 commented on modules/auxiliary/scanner/ubiquiti/ubiquiti_discover.rb
> +        return
```suggestion
      return
```

2019-01-31 21:34 UTC, wvu-r7 commented on modules/auxiliary/scanner/ubiquiti/ubiquiti_discover.rb
> +        return
```suggestion
      return
```

2019-01-31 21:34 UTC, wvu-r7 commented on modules/auxiliary/scanner/ubiquiti/ubiquiti_discover.rb
> +      if type == 0x0b
This can be a `case` statement.

2019-01-31 21:36 UTC, wvu-r7 commented on modules/auxiliary/scanner/ubiquiti/ubiquiti_discover.rb
> +      else
?

2019-01-31 22:12 UTC, wvu reviewed
Did you want to use the `Msf::Auxiliary::DRDoS` mixin you wrote?

2019-02-01 02:47 UTC, wvu-r7 commented on modules/auxiliary/scanner/ubiquiti/ubiquiti_discover.rb
> +      else
Just asking about the empty `else`. If you're not using it, you can remove it.

2019-02-01 02:48 UTC, wvu-r7 commented on modules/auxiliary/scanner/ubiquiti/ubiquiti_discover.rb
> +      else
Well, it's not empty anymore!

2019-02-01 16:57 UTC, jhart-r7 commented on modules/auxiliary/scanner/ubiquiti/ubiquiti_discover.rb
> +      if type == 0x0b
Indeed it could be ;)

2019-02-01 17:06 UTC, bcoles commented on documentation/modules/auxiliary/scanner/ubiquiti/ubiquiti_discover.md
> +  3. Do: `set RHOSTS <some_targets>`
https://www.youtube.com/watch?v=VOaZbaPzdsk

2019-02-01 17:44 UTC, merged

2019-02-01 17:45 UTC, bwatters-r7 commented
# Release notes
This PR adds a module to enumerate some ubiquiti devices.

2019-02-01 19:08 UTC, jhart-r7 commented
Excellent thank you all for the help!