Add metasm format of code for Super small Shell Bind TCP Random Port
rapid7/metasploit-framework pull request #11374
Opened 2019-02-09 12:59 UTC by Ekzorcist

The shellcode is going to upgrade/complement the old one https://github.com/rapid7/metasploit-framework/blob/master/modules/payloads/singles/linux/x86/shell_bind_tcp_random_port.rb which size is 57. The functionality is virtually the same but the size if SIGNIFICANTLY (44 against 57!) smaller which makes it unique in its kind.

This payload is really tiny since it uses nc by opening a random port.
Use nmap to discover the open port: 'nmap -sS -p- target'.
More details can be found here https://www.exploit-db.com/exploits/41631

Tested on Linux 4.9.0-7-amd64 #1 SMP Debian 4.9.110-1 (2018-07-05) x86_64 GNU/Linux

Please review it.
Thanks in advance!

2019-02-09 13:12 UTC, bcoles commented on modules/payloads/singles/linux/x86/shell_bind_tcp_super_small_random_port.rb
> +# This module requires Metasploit: http://metasploit.com/download
```suggestion
# This module requires Metasploit: https://metasploit.com/download
```

2019-02-09 13:13 UTC, bcoles commented on modules/payloads/singles/linux/x86/shell_bind_tcp_super_small_random_port.rb
> +      'References'    => ['URL', 'https://www.exploit-db.com/exploits/41631'],
```suggestion
      'References'    => ['EDB', '41631'],
```

2019-02-14 08:38 UTC, Ekzorcist commented
Hello, guys!
Please reopen https://github.com/rapid7/metasploit-framework/pull/11370
to advance with the current task!

2019-02-20 14:33 UTC, busterb commented
Reopening #11370 really isn't required for this. Taking a look now.

2019-02-20 14:39 UTC, Ekzorcist commented
ok! Glad to hear that)!

2019-02-22 14:13 UTC, phra requested changes

2019-02-22 14:13 UTC, phra commented on modules/payloads/singles/linux/x86/shell_bind_tcp_super_small_random_port.rb
> +        Use nmap to discover the open port: 'nmap -sS -p- target'.
```suggestion
        Use nmap to discover unfiltered closed port: 'nmap -sS -p- target'.
```

with BIND TCP, you need an available, not filtered, closed port, not an open one.

2019-02-22 19:22 UTC, Ekzorcist commented on modules/payloads/singles/linux/x86/shell_bind_tcp_super_small_random_port.rb
> +        Use nmap to discover the open port: 'nmap -sS -p- target'.
phra, yes, we need not filtered and not used (closed) port when it comes to bind tcp.

But, once shellcode triggers - it opens a port, so we need to scan a target to find that opened port in order to connect to it.

2019-02-23 13:25 UTC, phra commented on modules/payloads/singles/linux/x86/shell_bind_tcp_super_small_random_port.rb
> +        Use nmap to discover the open port: 'nmap -sS -p- target'.
got it. :+1:

2019-02-23 13:42 UTC, phra commented
> This payload is really tiny since it uses nc by opening a random port.

the command passed to the `execve()` is `nc -le /bin/sh` so it requires `nc.traditional` installed on the target machine making the shellcode dependent on the machine configuration.

2019-02-23 15:28 UTC, Ekzorcist commented
> > This payload is really tiny since it uses nc by opening a random port.
> 
> the command passed to the `execve()` is `nc -le /bin/sh` so it requires `nc.traditional` installed on the target machine making the shellcode dependent on the machine configuration.

yes, I am aware of it. And this is a deliberate approach to make it the tiniest one!
Regardless of the used technique to open a port your attempt to do this can also be limited with other factors such as iptables INPUT configuration, SELINUX etc..
Nothing is universal for every case.

2019-03-08 18:30 UTC, Ekzorcist commented
Hello, @busterb !
Is there any news on reviewing and merging the shellcode?
Appreciate your help on this a lot!!!

2019-03-08 21:08 UTC, busterb commented
Hi @Ekzorcist yeah I started reviewing this, noticed that our payload size checker automation was actually broken!, and didn't finish. Plan to get back on this soon to fix that as well.

2019-03-09 06:44 UTC, Ekzorcist commented
Thank you!!

2019-04-05 20:01 UTC, Ekzorcist commented
Hello, Brent!
How is it going with payload size checker automation?
May be I could help in fixing it ?

2019-05-17 09:37 UTC, busterb commented
All fixed, there was a bug in msfvenom's size checker that got merged in #11821. I have some changes I'm going to include with the merge here too.

2019-05-17 10:14 UTC, merged

2019-05-17 10:18 UTC, busterb commented
I added 9ae01c98c9 which merged this payload into the existing bind payload. This makes it automatically invoked as needed rather than having to evaluate a different payload entirely (this pattern is in many other payloads as well.) If you pass `-s 56` or smaller to msfvenom, it will choose the tinier version, e.g. `./msfvenom -p linux/x86/shell_bind_tcp_random_port -s 57`

Note also that I had to rename `generate_bind_tcp_shell` to `generate`, since the original payload in this PR never generated anything unless it overrode the base class method for the payload class. Keep that in mind for any future efforts.

Thanks!

2019-05-24 15:47 UTC, acammack-r7 commented
# Release Notes

Adds a small version of `linux/x86/shell_bind_tcp_random_port` that uses the `nc` command on the target to reduce the amount of shellcode needed. The new payload will automatically be used when the old one is too large.

2019-05-26 20:25 UTC, Ekzorcist commented
Super cool!