Add support for splunk 7.2.4 to 'Splunk Custom App Remote Code Execution'
rapid7/metasploit-framework pull request #11577
Opened 2019-03-17 16:46 UTC by avanzo

Hi
I have been working on integrating some changes to the 'Splunk Custom App Remote Code Execution' and including support for splunk 7.2.4 (it might even work on the whole 7 train up to 7.2.4)

## Verification steps

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/multi/http/splunk_upload_app_exec`
- [ ] set required variables (you will need admin credentials)

`
SET TARGET 1
SET RHOST 192.168.1.1
 SET USERNAME admin
 SET PASSWORD changeme
`
- [ ] 'run' or 'exploit' and you should expect reverse shell connection on port 4444

It has been tested successfully on both linux,macos (windows does not support python reverse shell but all the other available commands are working as expected)

2019-03-17 18:44 UTC, h00die requested changes
it looks like we don't have any docs for this module.  Excellent opportunity to make some!

Would you mind adding?  Template is here: https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/module_doc_template.md

2019-03-17 18:44 UTC, h00die commented on modules/exploits/multi/http/splunk_upload_app_exec.rb
> +    file_data = ::File.open(file_name, "rb") { |f| f.read }
as @bcoles excellently pointed out 7 days ago: https://github.com/rapid7/metasploit-framework/pull/11548#discussion_r264058072
```
file_data = ::File.read(file_name)
```

2019-03-17 18:44 UTC, h00die commented on modules/exploits/multi/http/splunk_upload_app_exec.rb
> +    if target.name.include? "7.2.4"
I assume you set this since you didn't test <7.2.4, but maybe this should include more than just that version?

2019-03-17 20:47 UTC, avanzo commented on modules/exploits/multi/http/splunk_upload_app_exec.rb
> +    file_data = ::File.open(file_name, "rb") { |f| f.read }
awesome, I  have updated it on both functions

2019-03-17 20:48 UTC, avanzo commented on modules/exploits/multi/http/splunk_upload_app_exec.rb
> +    if target.name.include? "7.2.4"
it would probably work on the whole 7.2 (or even 7 train) but I would stick to the tested version so far (I can include this comment in the documentation though)

2019-03-17 21:27 UTC, avanzo commented
I have also included the documentation section as well

2019-03-18 02:47 UTC, Green-m commented
It is required that code in your fork be merged from a unique branch in your repository to master in Rapid7's. Please create a new branch in your fork of framework and resubmit this from that branch.
```
git checkout -b <BRANCH_NAME>
git push <your_fork_remote> <BRANCH_NAME>
```
This helps protect the process, ensure users are aware of commits on the branch being considered for merge, allows for a location for more commits to be offered without mingling with other contributor changes and allows contributors to make progress while a PR is still being reviewed.

Closing based on the this requirement, please do resubmit from a unique branch.

2019-03-18 02:47 UTC, closed without merging

2019-03-18 08:23 UTC, bcoles commented
#11579