es file explorer open port CVE-2019-6447
rapid7/metasploit-framework pull request #11625
Opened 2019-03-24 12:07 UTC by h00die

This module exploits CVE-2019-6447, where Android app ES File Explorer before version 4.1.9.7.5 ran an HTTP server while the app was open, which accepted commands commands to do things like get device info, download files, list apps/files.

## Verification

- [ ] Install vulnerable app
- [ ] Start `msfconsole`
- [ ] `use modules/auxiliary/scanner/http/es_file_explorer_open_port`
- [ ] `set rhost`
- [ ] `run`
- [ ] **Verify** the action completes as expected (see docs)
- [ ] **Document** no spelling/grammar/syntax bugs

2019-03-26 18:18 UTC, busterb commented
Nice work! With features like these, who needs bugs!

2019-03-26 18:22 UTC, wvu requested changes
Please add a `DisclosureDate`.

2019-03-26 21:08 UTC, wvu approved these changes

2019-03-26 21:09 UTC, wvu-r7 commented
Btw, when we discussed this in work chat in January, I found this: https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fwww.ms509.com%2F2016%2F03%2F01%2Fes-explorer-vul%2F.

> Mar 1, 2016

Independent discovery?

2019-03-26 21:29 UTC, h00die commented
Interesting, 3yr timespan. I'll update references, credit should be given as it references all the same things

2019-03-26 21:32 UTC, fs0c131y commented
Hi,

Yes I found this issue 2 months ago. The PoC I made is available here: https://github.com/fs0c131y/ESFileExplorerOpenPortVuln

Regards

2019-03-26 21:41 UTC, wvu-r7 commented
Yes, credit all discoverers, please. Thanks!

2019-03-29 20:47 UTC, busterb commented
Verified locally yesterday, LGTM.

2019-03-29 20:47 UTC, merged

2019-03-29 20:48 UTC, busterb commented
## Release Notes

This module exploits CVE-2019-6447. Android app ES File Explorer before version 4.1.9.7.5 runs an HTTP server while the app is open, which accepts commands commands to perform operations such as getting device info, downloading files, and listing apps and files.