Microsoft windows contact remote code execution exploit
rapid7/metasploit-framework pull request #11638
Opened 2019-03-26 23:41 UTC by BrennerLittle

This module allows remote attackers to execute arbitrary code on vulnerable installations of Microsoft Windows.
User interaction is required to exploit this vulnerability in that the target must visit a malicious page or open a malicious file.

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/fileformat/microsoft_windows_contact_remote_code_execution`
- [ ] 'exploit'
- [ ] file written to home directory.

2019-03-27 19:18 UTC, busterb commented
Hi, can you please run the 'rubocop' and 'msftidy' tool with this module? There are style issues you will need to cleanup.

2019-03-28 19:29 UTC, cbrnrd requested changes
I would definitely do what @busterb said about rubocop and msftidy. There are some other ways you could improve UX and consistency between other similar modules (in terms of writing the file to disk).

2019-03-28 19:29 UTC, cbrnrd commented on modules/exploits/windows/fileformat/microsoft_windows_contact_remote_code_execution.rb
> +      'Name'        => 'Microsoft Windows CONTACT - Remote Code Execution Execution',
`Microsoft Windows Contact File Remote Code Execution`

2019-03-28 19:29 UTC, cbrnrd commented on modules/exploits/windows/fileformat/microsoft_windows_contact_remote_code_execution.rb
> +    require 'fileutils'
This should be required at the beginning of the file.

2019-03-28 19:29 UTC, cbrnrd commented on modules/exploits/windows/fileformat/microsoft_windows_contact_remote_code_execution.rb
> +        User interaction is required to exploit this vulnerability in that the target must visit a malicious page or open a malicious file.
This is very broad. Add some more specifics like what the user has to click and where the vulnerability lies. You can probably just copy/paste stuff from the vulnerability.

2019-03-28 19:29 UTC, cbrnrd commented on modules/exploits/windows/fileformat/microsoft_windows_contact_remote_code_execution.rb
> +    test = contactname
Why not just use `contactname`?

2019-03-28 19:29 UTC, cbrnrd commented on modules/exploits/windows/fileformat/microsoft_windows_contact_remote_code_execution.rb
> +    xml = | << ? xml version = "1.0"
This could be a bit prettier. Try using `%q{xmldata}` format.

2019-03-28 19:29 UTC, cbrnrd commented on modules/exploits/windows/fileformat/microsoft_windows_contact_remote_code_execution.rb
> +    FileUtils.mkdir_p test
The file should not be written to the home directory by default. It should be written to `datastore['FILENAME']`.

2019-03-28 19:29 UTC, cbrnrd commented on modules/exploits/windows/fileformat/microsoft_windows_contact_remote_code_execution.rb
> +    file.write(xml)
```suggestion
File.open(test + "/http/www." + exename, "wb") do |f|
  f.write(exe)
  print_status("Creating '#{datastore['FILENAME']}' file in directory " + test)
  File.open(test + "/" + contactname + ".contact", "wb") do |file|
    print_status("Creating '#{datastore['ContactName']}' file in directory " + test)
    file.write(xml)
  end
end
```
This should all be indented.

2019-03-28 19:29 UTC, cbrnrd commented on modules/exploits/windows/fileformat/microsoft_windows_contact_remote_code_execution.rb
> +      'DefaultOptions' => {
```suggestion
      'DefaultOptions' => {
        'DisablePayloadHandler' => true
      }
```

2019-03-28 19:29 UTC, cbrnrd commented on modules/exploits/windows/fileformat/microsoft_windows_contact_remote_code_execution.rb
> +        OptString.new('FILENAME', [false, 'The name of the malicious payload to execute', 'msf.com']),
```suggestion
        OptString.new('FILENAME', [false, 'The name of the contact file.', 'msf.com']),
```

Also, isn't the proper file extension for a contact `.contact`?

2019-03-28 19:29 UTC, cbrnrd commented on modules/exploits/windows/fileformat/microsoft_windows_contact_remote_code_execution.rb
> +        OptString.new('ContactName', [false, 'The name of the Contact File', 'John Smith'])
This should probably be `FULL_NAME` or you split it up into `FIRST_NAME` and `LAST_NAME` options.

2019-03-28 19:29 UTC, cbrnrd commented on modules/exploits/windows/fileformat/microsoft_windows_contact_remote_code_execution.rb
> +    contactname = "#{datastore['Contactname']}"
```suggestion
    contactname = "#{datastore['ContactName']}"
```

2019-03-28 22:59 UTC, bcoles commented on modules/exploits/windows/fileformat/microsoft_windows_contact_remote_code_execution.rb
> +    xml = | << ? xml version = "1.0"
The XML is malformed. It was correctly formed in 16874b00d38582fb5f0ae67dbf863b291ecb0f4a; but seems to have been corrupted in the following commits.

2019-03-28 23:14 UTC, bcoles commented on modules/exploits/windows/fileformat/microsoft_windows_contact_remote_code_execution.rb
> +        User interaction is required to exploit this vulnerability in that the target must visit a malicious page or open a malicious file.
What is the use case ?

> the target must visit a malicious page

This seems unlikely. Maybe with WebDAV? Or maybe via drive-by download? In which case the user still needs to open the file.

> or open a malicious file

This module generates two files - a contact file and a payload exe.

Exploitation will fail unless both files are located in the same directory. This needs to be documented in the module description or module documentation.

The vulnerability write-up suggests compressing the files into a zip file. This can be achieved with Metasploit's `Rex::Archive` library. However, exploitation will only be successful if the user extracts the contents before opening the contact file; or, when the contact file is opened directly from the within the zip file, and the compression utility automatically extracts both the exe and contact file to a temporary directory.

Effectively, you're distributing two files to the target. If the victim opens the payload, you get a shell. If the victim opens the contact file, you may or may not get a shell, as per the above.

2019-03-30 21:54 UTC, cbrnrd commented
@BrennerLittle You seem pretty interested in contributing to Metasploit, so here’s some tips to make this PR (and hopefully future ones) go a bit smoother. 

1. Use a Text Editor/IDE

Tools like [Visual Studio Code](https://code.visualstudio.com/) and [Atom](https://atom.io) are great for assisting in formatting, code completion, and make the whole coding process a bit easier. 

2. Use msftidy

The `msftidy` script is Metasoit’s all-in-one module checking tool. Run this on your module often so you can catch seemingly hidden errors early on. 

3. Look at other modules

This has saved me more times than I can count. Looking at other modules for ways to do something the “metasploit way” is by far the easiest way to improve module quality and stability. You can either search on github or using grep. 

4. Read the Wiki

The [Metasploit wiki](https://github.com/rapid7/metasploit-framework/wiki) has tips, tutorials, and helpful git stuff go speed up and simplify module development. This and the API docs should be your go-to place for development questions. 

5. Use the git CLI, not GitHub’s editor

GitHub’s editor... works, but is definitely not ideal. You should be using git from the command line for all but super minor edits. [This](https://github.com/rapid7/metasploit-framework/wiki/Using-Git) wiki page is a good read for getting started with git. [This](https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment) page is good read for contributing to metasploit in general. 

Since your PR is coming from your `master` branch, it will likely not be landed until it’s from a separate branch on your msf fork. My advice to you right now is to close this PR and follow the tips and instructions from the wiki when improving/fixing your module. If you do all that and open a new PR, your module should be landed in no time. 

Thanks, and best of luck! 👍🏻

2019-03-30 22:00 UTC, closed without merging