Update CVE reference and datastore options for WebLogic exploit
rapid7/metasploit-framework pull request #11861
Opened 2019-05-20 18:14 UTC by wchen-r7

This updates the weblogic_deserialize_asyncresponseservice exploit for the following:

* CVE reference: Instead of CVE-2019-2725, it should be CVE-2017-10271.
* Registering the right datastore option with the standard TARGET_URI. Please note: for NAT scenarios, you can use the VHOST option, which is always built-in.

2019-05-21 00:45 UTC, wvu-r7 commented on documentation/modules/exploit/multi/misc/weblogic_deserialize_asyncresponseservice.md
> +## Option
Since this is a header, I would keep this consistently plural, even if there is only one option.

2019-05-21 00:46 UTC, wvu-r7 commented on documentation/modules/exploit/multi/misc/weblogic_deserialize_asyncresponseservice.md
>  `URIPATH` is the URI (eg. `http://192.168.192.132`) used for the HTTP request.  In most cases, this value can be left blank and will be substituted with the IP address from RHOSTS.  Potential uses of
I think this paragraph can be removed.

2019-05-21 00:46 UTC, wvu-r7 commented on documentation/modules/exploit/multi/misc/weblogic_deserialize_asyncresponseservice.md
>  `URIPATH` is the URI (eg. `http://192.168.192.132`) used for the HTTP request.  In most cases, this value can be left blank and will be substituted with the IP address from RHOSTS.  Potential uses of
The option is still listed in the console output, too.

2019-05-21 00:46 UTC, wvu requested changes
Code looks good.

2019-05-22 19:20 UTC, wvu approved these changes

2019-05-22 19:24 UTC, merged

2019-05-22 19:25 UTC, wvu-r7 commented
# Release Notes

This updates `exploit/multi/misc/weblogic_deserialize_asyncresponseservice` to reference the correct CVE and consolidates on the `TARGETURI` option.