Add exploit module for wp-database-backup Wordpress plugin
rapid7/metasploit-framework pull request #12010
Opened 2019-06-25 16:38 UTC by space-r7

This adds a module that exploits a command injection vulnerability in `wp-database-backup` versions < `v5.2`. In the creation of a database backup, this software generates a `mysqldump` command. The user can opt to exclude certain tables via the plugin settings. The `wp_db_exclude_table` parameters in the POST request for choosing tables to exclude is unsanitized, which allows for code execution when the `ignore-table` option is later used in the `mysqldump` command that creates the database backup. Authentication is required to successfully exploit this vulnerability.

## Verification

 - [ ] Install the application
 - [ ] Start msfconsole
 - [ ] Do: ```use exploit/multi/http/wp_db_backup_rce```
 - [ ] Do: ```set RHOSTS <ip>```
 - [ ] Do: ```set USERNAME <user>```
 - [ ] Do: ```set PASSWORD <password>```
 - [ ] Do: ```run```
 - [ ] You should get a shell.

2019-06-25 17:06 UTC, jrobles-r7 commented
The `Exploit::CmdStager` mixin is included but the `execute_cmdstager`/`execute_command` syntax from https://github.com/rapid7/metasploit-framework/wiki/How-to-use-command-stagers isn't used.

Should the mixin be removed or is the mixin used in some other way?

2019-06-25 17:42 UTC, space-r7 commented
> The `Exploit::CmdStager` mixin is included but the `execute_cmdstager`/`execute_command` syntax from https://github.com/rapid7/metasploit-framework/wiki/How-to-use-command-stagers isn't used.
> 
> Should the mixin be removed or is the mixin used in some other way?

I'm using the mixin just for the `generate_cmdstager` function, but that can be changed, of course.

2019-06-26 01:49 UTC, wvu-r7 commented
I think your usage is fine, but bear in mind that command stagers are meant to be iterated over until completion, so if you're using `generate_cmdstager`, you should `join` instead of `first`.

If you don't have a line length requirement, it doesn't matter much, but it's good practice to follow the API. I would use `execute_cmdstager` if at all possible.

2019-06-26 01:50 UTC, wvu-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +      comm_payload = generate_cmdstager.first.gsub(';', '&&')
I will make this a configurable option, plus with the ability to background the payload.

2019-06-26 01:52 UTC, wvu-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +      comm_payload = comm_payload.gsub('/tmp/', './')
Are you able to use `:temp` in an options hash to `generate_cmdstager`?

https://github.com/rapid7/rex-exploitation/blob/master/lib/rex/exploitation/cmdstager/printf.rb#L22-L25

2019-06-26 02:00 UTC, wvu-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +    fail_with(Failure::BadConfig, 'Unable to log into Wordpress') unless cookie
`Failure::NoAccess` would be more specific.

2019-06-26 02:03 UTC, wvu-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +    fail_with(Failure::BadConfig, 'Failed to get a proper response') unless response
I would probably make this `Failure::UnexpectedReply` like above.

2019-06-26 02:06 UTC, wvu-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +  Rank = NormalRanking
This could probably be `ExcellentRanking` because of the command injection and reliable vector. I would add module traits to granularize.

2019-06-26 02:09 UTC, wvu-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +      'Arch'           => [ ARCH_X86, ARCH_X64 ],
Until someone fixes this, please add a top-level `Platform` that lists all your supported platforms.

```
msf5 exploit(multi/http/wp_db_backup_rce) > info

       Name: WP Database Backup RCE
     Module: exploit/multi/http/wp_db_backup_rce
   Platform:
       Arch: x86, x64
 Privileged: No
    License: Metasploit Framework License (BSD)
       Rank: Normal
  Disclosed: 2019-04-24
[snip]
```

2019-06-26 02:10 UTC, wvu-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +  include Exploit::CmdStager
This is a nitpick, but I would prefer to include the `Msf::` prefix. You could probably drop `Exploit::` altogether... but no.

2019-06-26 02:11 UTC, wvu-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +      comm_payload = generate_cmdstager.first.gsub(';', '&&')
I really need to make this stuff `BadChars`-aware!!

2019-06-26 02:13 UTC, wvu-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +  def exploit
Another nitpick, and feel free to disregard. Scrolling to the bottom to find a primary method like `exploit` is a little distracting. If you could move this after `check` like we usually do, it would read more easily.

2019-06-26 02:15 UTC, wvu-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +      'Targets'        =>
If you're ambitious, you can support `ARCH_CMD`, too. It would behoove us to try to combine with `CmdStager`... in the future.

2019-06-26 02:15 UTC, wvu-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +              'CmdStagerFlavor' =>  'printf'
Is this limited to `printf` because of badchars?

2019-06-26 02:16 UTC, wvu requested changes
Some comments. Excellent contribution as usual. The rigorous error checking is thoughtful to the user.

2019-06-26 13:36 UTC, space-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +      comm_payload = generate_cmdstager.first.gsub(';', '&&')
Wasn't aware of that one. Thank you!

2019-06-26 15:38 UTC, wvu-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +      comm_payload = generate_cmdstager.first.gsub(';', '&&')
The API is quite obscure and sequestered away in the `rex-exploitation` gem now. Sigh. :)

2019-06-26 16:56 UTC, space-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +      comm_payload = generate_cmdstager.first.gsub(';', '&&')
That's true. I just found the `:noarg` option for the echo command stager flavor. I had originally thought that there was no way to remove the `-ne` option with the api.

2019-06-26 16:58 UTC, space-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +              'CmdStagerFlavor' =>  'printf'
No, I wasn't aware of the `noarg` option to remove `-ne` from the command line generated by the `echo` command stager flavor. I'll add that in and test it out.

2019-06-26 17:10 UTC, wvu-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +      comm_payload = generate_cmdstager.first.gsub(';', '&&')
That's so hacky! Let's rewrite it. :)

2019-06-26 17:10 UTC, wvu-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +              'CmdStagerFlavor' =>  'printf'
Gotcha. No problem!

2019-06-27 15:40 UTC, wvu-r7 commented
Hey, if you resolved these things, can you mark the comments resolved? GitHub isn't doing that for some reason. I would like to mark this approved. :)

2019-06-27 15:52 UTC, space-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +              'CmdStagerFlavor' =>  'printf'
Tested with the `echo` command stager flavor, but couldn't get it to work properly.

2019-06-27 16:04 UTC, wvu-r7 commented on modules/exploits/multi/http/wp_db_backup_rce.rb
> +              'CmdStagerFlavor' =>  'printf'
All good. `printf` is more predictable/portable, anyway.

2019-06-27 16:04 UTC, wvu approved these changes

2019-07-23 17:21 UTC, merged

2019-07-23 17:22 UTC, wchen-r7 commented
# Release Notes

This adds a module that exploits a command injection vulnerability in wp-database-backup versions < v5.2.