Add exploit for CVE-2019-1621, Cisco Data Center Network Manager arbitrary file upload.
rapid7/metasploit-framework pull request #12059
Opened 2019-07-06 15:00 UTC by pedrib

DCNM exposes a servlet to download files on /fm/downloadServlet.
      An authenticated user can abuse this servlet to download arbitrary files as root by specifying
      the full path of the file.
      This module was tested on the DCNM Linux virtual appliance 10.4(2), 11.0(1) and 11.1(1), and should
      work on a few versions below 10.4(2). Only version 11.0(1) requires authentication to exploit
      (see References to understand why).

See also:
https://tools.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-20190626-dcnm-bypass
https://tools.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-20190626-dcnm-file-dwnld

I will also put a full disclosure post up soon that contains more details, and will add the link here.

2019-07-09 22:28 UTC, wvu-r7 commented
Thanks, @pedrib!

2019-07-10 00:03 UTC, pedrib commented
@wvu-r7 you're welcome, full disclosure link added!

2019-07-10 18:16 UTC, pedrib commented
Corrected the title, this is actually the auxiliary arb download module; the file upload leading to RCE is PR  #12058

2019-07-10 19:25 UTC, acammack-r7 commented on modules/auxiliary/admin/cisco/cisco_dcnm_download.rb
> +      if res.body =~ /\"version\":\"11\.1\(1\)/
See https://github.com/rapid7/metasploit-framework/pull/12058/files#r302228456 about using regex here.

2019-07-13 11:51 UTC, pedrib commented
@acammack-r7 @wvu-r7 give me some time to address your points, I'm currently busy with other work! I don't like to make changes without testing locally with all the versions I have here (10.4.2, 11.0.1, 11.1.1), so need to downtime to address them. Please be patient!

2019-08-02 22:01 UTC, pedrib commented
@acammack-r7 @wvu-r7 all done, good to go!

2019-08-14 05:37 UTC, pedrib commented
ping!

2019-08-22 08:57 UTC, pedrib commented
yo guys!

2019-08-22 15:31 UTC, wvu-r7 commented
And this one!

2019-08-24 10:40 UTC, pedrib commented
@wvu-r7 please do, these are ready to go!

2019-08-24 10:43 UTC, pedrib commented
The build failure is unrelated to the module I believe.

2019-08-28 04:34 UTC, pedrib commented
Do you want a pcap to accelerate this?

2019-08-29 03:19 UTC, wvu-r7 commented
I might have to transfer these PRs to someone else. This might be my busiest week of the year. :(

2019-08-29 03:20 UTC, wvu-r7 commented
A pcap would help, yes, but is there a virtual appliance we can test? This could benefit from [module documentation](https://github.com/rapid7/metasploit-framework/wiki/Writing-Module-Documentation).

2019-08-29 03:24 UTC, wvu-r7 commented
Note to committers: please handle #12058 as well.

2019-08-29 03:30 UTC, pedrib commented
> A pcap would help, yes, but is there a virtual appliance we can test? This could benefit from [module documentation](https://github.com/rapid7/metasploit-framework/wiki/Writing-Module-Documentation).

There is a virtual appliance, but you need a Cisco contract to access it. I'll send a pcap soon.

2019-08-29 03:35 UTC, wvu-r7 commented
Let me review this right quick, and if the pcap checks out, let's ship it.

2019-08-29 03:51 UTC, wvu requested changes
Quick-pass review. Should be clean enough to merge after.

2019-08-29 03:54 UTC, pedrib commented
[dcnm_download.pcap.zip](https://github.com/rapid7/metasploit-framework/files/3553753/dcnm_download.pcap.zip)

Pcap attached

2019-08-29 04:07 UTC, pedrib commented on modules/auxiliary/admin/cisco/cisco_dcnm_download.rb
> +    if res && res.code == 200
Honestly I prefer to leave it as is, guard clauses make the code unreadable IMO.

2019-08-29 04:07 UTC, pedrib commented on modules/auxiliary/admin/cisco/cisco_dcnm_download.rb
> +      if res.body.include?('version":"11.1(1)')
Perhaps, but it's just 3 cases, and it's well tested this way, I prefer to keep it as is.

2019-08-29 04:08 UTC, pedrib commented
Fixed most of your changes, except the ones where I provide a justification

2019-08-29 04:47 UTC, wvu-r7 commented
Cool, I can accept your justifications. Thanks for the quick changes!

2019-08-29 05:17 UTC, pedrib commented
Done!

2019-08-29 05:47 UTC, wvu-r7 commented
Once https://github.com/rapid7/metasploit-framework/pull/12058#issuecomment-526033371 is addressed, I plan to review the pcaps and land both PRs.

2019-08-29 15:49 UTC, pedrib commented
ok that's it!

2019-08-30 17:13 UTC, wvu-r7 commented
@pedrib: This one has an f-d reference. Okay to land?

2019-08-30 17:21 UTC, pedrib commented
@wvu-r7 all good for all modules!

2019-08-30 18:37 UTC, merged

2019-08-30 18:37 UTC, wvu approved these changes

2019-08-30 18:39 UTC, wvu-r7 commented
# Release Notes

This adds a Cisco Data Center Network Manager arbitrary file download auxiliary module.