Add exploit for Cisco Data Center Network Manager file upload
rapid7/metasploit-framework pull request #12058
Opened 2019-07-06 14:54 UTC by pedrib

DCNM exposes a file upload servlet (FileUploadServlet) at /fm/fileUpload.
      An authenticated user can abuse this servlet to upload a WAR to the Apache Tomcat webapps
      directory and achieve remote code execution as root.
      This module exploits two other vulnerabilities, CVE-2019-1619 for authentication bypass on
      versions 10.4(2) and below, and CVE-2019-1622 (information disclosure) to obtain the correct
      directory for the WAR file upload.
      This module was tested on the DCNM Linux virtual appliance 10.4(2), 11.0(1) and 11.1(1), and should
      work on a few versions below 10.4(2). Only version 11.0(1) requires authentication to exploit
      (see References to understand why).

Tested and working on 10.4(2) up to 11.1(1). 
See 
https://tools.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-20190626-dcnm-bypass
https://tools.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-20190626-dcnm-codex
https://tools.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-20190626-dcnm-infodiscl

I will also have a full disclosure post soon with more details about the vulns, and will add the link here.

2019-07-10 19:10 UTC, jrobles-r7 commented on cisco_dcnm_upload_2019.rb
> +        return Exploit::CheckCode::Detected
```suggestion
        return CheckCode::Detected
```

2019-07-10 19:10 UTC, jrobles-r7 commented on cisco_dcnm_upload_2019.rb
> +    return Exploit::CheckCode::Unknown
```suggestion
    CheckCode::Unknown
```

2019-07-10 19:12 UTC, acammack-r7 commented on cisco_dcnm_upload_2019.rb
> +        if res.body =~ /\"version\":\"11\.1\(1\)/
Since you are matching plain strings, instead of using a regular expression these matches would be more clear using `String#include?` like:
```ruby
if res.body.include? %q{"version":"11.1(1)}
....
elsif res.body.include? %q{"version":"11.0(1)}
...
elsif res.body.include? %q{"version":"10.4(2)}
...
```

2019-07-10 19:18 UTC, acammack-r7 commented on cisco_dcnm_upload_2019.rb
> +      tmp = Tempfile.new
We will want to make sure this file gets cleaned up after we are through with it. If it is helpful to keep around you could add an advanced option to move the file to loot.

2019-07-10 19:23 UTC, acammack-r7 commented
Looks cool @pedrib! I think this module would be more at home in `modules/exploits/multi/http/` than in the root Metasploit directory.

2019-07-11 11:13 UTC, pedrib commented
@acammack-r7 sorry mate, I must have been half asleep when I submitted the module, it deifnitely should be in modules/exploits/multi/http

2019-07-13 01:48 UTC, wvu-r7 commented on cisco_dcnm_upload_2019.rb
> +        if res.body =~ /\"version\":\"11\.1\(1\)/
And perhaps a `case` statement.

2019-07-13 11:51 UTC, pedrib commented
@acammack-r7 @wvu-r7 give me some time to address your points, I'm currently busy with other work! I don't like to make changes without testing locally with all the versions I have here (10.4.2, 11.0.1, 11.1.1), so need to downtime to address them. Please be patient!

2019-08-02 22:01 UTC, pedrib commented
@acammack-r7 @wvu-r7 all done, good to go!

2019-08-14 05:37 UTC, pedrib commented
ping!

2019-08-22 08:57 UTC, pedrib commented
yo guys!

2019-08-22 15:31 UTC, wvu-r7 commented
Hey, why don't I handle this!

2019-08-29 03:24 UTC, wvu-r7 commented
Note to commiters: please handle #12059 as well.

2019-08-29 03:54 UTC, pedrib commented
[dcnm_uploadp.pcap.zip](https://github.com/rapid7/metasploit-framework/files/3553757/dcnm_uploadp.pcap.zip)

Pcap attached

2019-08-29 03:56 UTC, wvu requested changes
Would appreciate it if you applied the review from #12059, too.

2019-08-29 04:13 UTC, pedrib commented on modules/exploits/multi/http/cisco_dcnm_upload_2019.rb
> +      Zip::File.open(tmp) do |zis|
Doesn't seem to work when I tested several methods, this was the only one that worked

2019-08-29 04:14 UTC, pedrib commented
done! should be good to go!

2019-08-29 04:21 UTC, pedrib commented on modules/exploits/multi/http/cisco_dcnm_upload_2019.rb
> +      # step 5: call Shelly
Shelly brings shells

2019-08-29 05:17 UTC, pedrib commented
all good!

2019-08-29 05:42 UTC, pedrib commented
all good?

2019-08-29 05:45 UTC, wvu-r7 commented
I'm fine with the code, but we do require a module doc per module now. If you are unable to provide, I can handle it.

You can at least copy the module description, setup notes, and example output into a Markdown file. Usually takes me five minutes.

2019-08-29 05:50 UTC, wvu-r7 commented
Here's the last one I wrote for reference: https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/exploit/unix/webapp/webmin_backdoor.md.

2019-08-29 07:01 UTC, wvu-r7 commented
I'm going to sleep, but I'll check in on this and the other PR tomorrow.

2019-08-30 17:14 UTC, wvu-r7 commented
@pedrib: This one has an f-d reference. Okay to land?

2019-08-30 18:37 UTC, merged

2019-08-30 18:37 UTC, wvu approved these changes

2019-08-30 18:39 UTC, wvu-r7 commented
# Release Notes

This adds a Cisco Data Center Network Manager file upload exploit.