add. exploit module vbulletin 5.x unauth RCE
rapid7/metasploit-framework pull request #12364
Opened 2019-09-25 21:22 UTC by mekhalleh

https://seclists.org/fulldisclosure/2019/Sep/31

vBulletin 5.x 0day pre-auth RCE exploit
This should work on all versions from 5.0.0 till 5.5.4

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `set exploit/multi/http/vbulletin_5x_unauth_rce`
- [ ] `set RHOSTS 192.168.1.11`
- [ ] `set LHOST 192.168.1.10`
- [ ] `run`

TODO : docs, try to dropper binary elf/pe for better experience.

2019-09-26 08:54 UTC, mekhalleh commented
Actually tested on Windows system host and vBulletin v5.4.5.

![mod1_win](https://user-images.githubusercontent.com/5225129/65673878-b6ccd100-e05c-11e9-9be7-2da30f4d16d4.png)

![mod2_win](https://user-images.githubusercontent.com/5225129/65673889-bdf3df00-e05c-11e9-8f9a-ac7abe2f0194.png)

2019-09-26 12:31 UTC, mekhalleh commented
Tested on Linux system host and vBulletin v5.5.1.

![mod3_lnx](https://user-images.githubusercontent.com/5225129/65687777-f86c7480-e07a-11e9-8c4a-77d7c7e0f042.png)

![mod4_lnx](https://user-images.githubusercontent.com/5225129/65687806-01f5dc80-e07b-11e9-9aeb-de90cb98dd35.png)

2019-10-12 02:25 UTC, h00die requested changes
First look over, this is pretty good. Untested, some style things to change, will test once they get fixed up

2019-10-12 02:25 UTC, h00die commented on modules/exploits/multi/http/vbulletin_5x_unauth_rce.rb
> +    if (received) && (received.body.include?(rand_str))
In general there are lots of not needed parenthesis in this code.
This for example could be
```
    if received && received.body.include?(rand_str)
      return Exploit::CheckCode::Vulnerable
    end
```

Which cuts out 2, saving 4 characters.  I would recommend going back over the code and seeing where you could drop them.

2019-10-14 19:03 UTC, space-r7 commented on modules/exploits/multi/http/vbulletin_5x_unauth_rce.rb
> +          'Type' => :php_dropper,
Since the code is executed within the context of `eval()`, is it possible to get a shell without dropping a file on the system?

2019-11-06 20:16 UTC, space-r7 commented on modules/exploits/multi/http/vbulletin_widgetconfig_rce.rb
> +        # discovered by an unknown sender.
```suggestion
        'unknown',  # discovered by an unknown sender.
```

2019-11-06 20:21 UTC, space-r7 commented
> First look over, this is pretty good. Untested, some style things to change, will test once they get fixed up

Hi @h00die! Would you happen to have a test environment and if so, would you be willing to test this if you have the time? If not, I can verify with a pcap. Thanks!

2019-11-10 14:27 UTC, h00die commented
@space-r7 I wanted to get around to this, but realistically I'm not going to be able to in a reasonable amount of time

2019-11-11 14:08 UTC, space-r7 commented
> @space-r7 I wanted to get around to this, but realistically I'm not going to be able to in a reasonable amount of time

Alrighty, no worries! Thank you!

Hey @mekhalleh, when you have time, could you please send a pcap of exploiting Vbulletin with your module to msfdev[at]metasploit.com? Thanks!

2019-11-12 13:54 UTC, mekhalleh commented
> > @space-r7 I wanted to get around to this, but realistically I'm not going to be able to in a reasonable amount of time
> 
> Alrighty, no worries! Thank you!
> 
> Hey @mekhalleh, when you have time, could you please send a pcap of exploiting Vbulletin with your module to msfdev[at]metasploit.com? Thanks!

it's sended.

2019-11-22 14:02 UTC, mekhalleh commented on modules/exploits/multi/http/vbulletin_widgetconfig_rce.rb
> +        # discovered by an unknown sender.
Just modified.

I also fix DisablePayloadHandler to false in target 0.

2019-11-22 14:06 UTC, bcoles commented on modules/exploits/multi/http/vbulletin_widgetconfig_rce.rb
> +        # discovered by an unknown sender.
`DisablePayloadHandler` should default to `false`, so it should be safe to remove it.

2019-11-22 15:48 UTC, mekhalleh commented on modules/exploits/multi/http/vbulletin_widgetconfig_rce.rb
> +        # discovered by an unknown sender.
Yes @bcoles , thanks for your reply, I add this because the others targets dont need and I have desactivate that.

But for exemple when I switch from target 2 to target 0 I do reactivate the handler for exploitation needs.

I you have other tricks for that?

2019-11-22 16:02 UTC, bcoles commented on documentation/modules/exploit/multi/http/vbulletin_widgetconfig_rce.md
> +3. Do: `use exploit/multi/http/vbullnetin_widgetconfig_rce`
```suggestion
3. Do: `use exploit/multi/http/vbulletin_widgetconfig_rce`
```

2019-11-22 16:03 UTC, bcoles commented on modules/exploits/multi/http/vbulletin_widgetconfig_rce.rb
> +        # discovered by an unknown sender.
> I add this because the others targets dont need and I have desactivate that.

In that case it makes sense to set `DisablePayloadHandler` to `false`.

2019-11-22 16:15 UTC, mekhalleh commented on documentation/modules/exploit/multi/http/vbulletin_widgetconfig_rce.md
> +3. Do: `use exploit/multi/http/vbullnetin_widgetconfig_rce`
Modified.

2019-12-10 17:55 UTC, space-r7 commented
Verified the pcap, will go ahead and land.

2019-12-10 18:13 UTC, merged

2019-12-10 18:16 UTC, space-r7 commented
## Release Notes

This adds an exploit module for vBulletin `v5.0.0` through `v5.5.4` that gains unauthenticated remote code execution by leveraging a flaw in the widget creation functionality. RCE can be leveraged by sending a POST request to `ajax/render/widget_php` with arbitrary data located in the `widgetConfig[code]` parameter.