Extend check codes with custom messages
rapid7/metasploit-framework pull request #12428
Opened 2019-10-08 15:31 UTC by acammack-r7

Check codes now take an optional message to allow a rationale to be more directly tied to the check code result. While this does help modules some (see the bluekeep scanner changes in this PR), the big win will be when combined with a few tweaks to the RPC API, this will allow remote clients to get some check context without having to troll through the printed output of a module run.

Verification
========
- [ ] `msfconsole`
- [ ] `use auxiliary/scanner/rdp/cve_2019_0708_bluekeep`
- [ ] `set RHOSTS 127.0.0.1`
- [ ] `set VERBOSE true`
- [ ] `run`
- [ ] Verify the custom safe message prints out with an error
- [ ] Vulnerable targets should now output a slightly more technical vulnerable message

2019-10-11 18:26 UTC, busterb approved these changes

2019-10-11 19:36 UTC, bwatters-r7 commented
This seems off; I tested it with a vulnerable machine:
# upstream/master
```
msf5 exploit(multi/handler) > use exploit/windows/rdp/cve_2019_0708_bluekeep_rce 
msf5 exploit(windows/rdp/cve_2019_0708_bluekeep_rce) > set rhosts 192.168.134.120
rhosts => 192.168.134.120
msf5 exploit(windows/rdp/cve_2019_0708_bluekeep_rce) > set verbose true
verbose => true
msf5 exploit(windows/rdp/cve_2019_0708_bluekeep_rce) > check

[*] 192.168.134.120:3389  - Verifying RDP protocol...
[*] 192.168.134.120:3389  - Attempting to connect using TLS security
[*] 192.168.134.120:3389  - Verifying RDP protocol...
[*] 192.168.134.120:3389  - Attempting to connect using TLS security
[*] 192.168.134.120:3389  - Detected RDP on 192.168.134.120:3389  (Windows version: 6.1.7601) (Requires NLA: No)
[*] 192.168.134.120:3389  - Sending erect domain request
[*] 192.168.134.120:3389  - Sending client info PDU
[*] 192.168.134.120:3389  - Received License packet (34 bytes)
[*] 192.168.134.120:3389  - Got license packet type 0xff (LICENSE_ERROR_ALERT)
[*] 192.168.134.120:3389  - License error/alert code 0x7 (LICENSE_ISSUED)
[*] 192.168.134.120:3389  - Waiting for Server Demand packet
[*] 192.168.134.120:3389  - Received Server Demand packet
[*] 192.168.134.120:3389  - Sending client confirm active PDU
[*] 192.168.134.120:3389  - Sending client synchronize PDU
[*] 192.168.134.120:3389  - Sending client control cooperate PDU
[*] 192.168.134.120:3389  - Sending client control request control PDU
[*] 192.168.134.120:3389  - Sending client input sychronize PDU
[*] 192.168.134.120:3389  - Sending client font list PDU
[*] 192.168.134.120:3389  - Sending patch check payloads
[+] 192.168.134.120:3389  - The target is vulnerable.
[+] 192.168.134.120:3389 - The target is vulnerable.

```

# This PR
```
msf5 exploit(multi/handler) > use exploit/windows/rdp/cve_2019_0708_bluekeep_rce 
msf5 exploit(windows/rdp/cve_2019_0708_bluekeep_rce) > set rhosts 192.168.134.120
rhosts => 192.168.134.120
msf5 exploit(windows/rdp/cve_2019_0708_bluekeep_rce) > set verbose true
verbose => true
msf5 exploit(windows/rdp/cve_2019_0708_bluekeep_rce) > check

[*] 192.168.134.120:3389  - Verifying RDP protocol...
[*] 192.168.134.120:3389  - Attempting to connect using TLS security
[*] 192.168.134.120:3389  - Verifying RDP protocol...
[*] 192.168.134.120:3389  - Attempting to connect using TLS security
[*] 192.168.134.120:3389  - Detected RDP on 192.168.134.120:3389  (Windows version: 6.1.7601) (Requires NLA: No)
[*] 192.168.134.120:3389  - Sending erect domain request
[*] 192.168.134.120:3389  - Sending client info PDU
[*] 192.168.134.120:3389  - Received License packet (34 bytes)
[*] 192.168.134.120:3389  - Got license packet type 0xff (LICENSE_ERROR_ALERT)
[*] 192.168.134.120:3389  - License error/alert code 0x7 (LICENSE_ISSUED)
[*] 192.168.134.120:3389  - Waiting for Server Demand packet
[*] 192.168.134.120:3389  - Received Server Demand packet
[*] 192.168.134.120:3389  - Sending client confirm active PDU
[*] 192.168.134.120:3389  - Sending client synchronize PDU
[*] 192.168.134.120:3389  - Sending client control cooperate PDU
[*] 192.168.134.120:3389  - Sending client control request control PDU
[*] 192.168.134.120:3389  - Sending client input sychronize PDU
[*] 192.168.134.120:3389  - Sending client font list PDU
[*] 192.168.134.120:3389  - Sending patch check payloads
[+] 192.168.134.120:3389  - The target attempted cleanup of the incorrectly-bound MS_T120 channel.
[+] 192.168.134.120:3389 - The target attempted cleanup of the incorrectly-bound MS_T120 channel.
msf5 exploit(windows/rdp/cve_2019_0708_bluekeep_rce) >

```

I'm a fan of extra output, but shouldn't that come in _addition_ to the original?  It quit saying "vulnerable"?

2019-10-11 21:18 UTC, busterb commented on lib/msf/core/exploit.rb
> +      def Detected(msg = 'The garget service is running, but could not be validated.')
the 'garget' service?

2019-10-11 21:20 UTC, busterb commented on lib/msf/core/exploit.rb
> +    class << self
Rather than replacing the existing message, these should clarify them:

If you say Unknown("The host was not listening")

The stringified output should be something like:

"Cannot reliably check exploitability: The host was not listening."

2019-10-11 21:22 UTC, busterb requested changes
Agree with Brendan's sentiment, would be ideal if these augmented the existing messages rather than just replaced them.

2019-10-14 14:57 UTC, busterb commented
@bwatters-r7 I fixed a couple of typos above and extended this to still display the original checkcode messages as well. Checked with other API consumers and this makes sense in that context as well. Look better?

2019-10-14 14:57 UTC, busterb approved these changes

2019-10-14 15:18 UTC, acammack-r7 commented
Sorry, I didn't get a chance to look at this over the weekend. I think that keeping the the original message in console prints makes sense, but in other consumers/formats the technical reason by itself is desirable (e.g. a table of vulnerable hosts). I think I have a way to accommodate both these use cases that I'll try to have up today.

2019-10-15 16:05 UTC, bwatters-r7 commented
I like it, and per instructions from above, landing this as-is for now.  We can tweak it in a future PR.
```
msf5 auxiliary(scanner/rdp/cve_2019_0708_bluekeep) > run

[-] 127.0.0.1:3389        - The target is not exploitable: The target service is not running or refused our connection.
[*] 127.0.0.1:3389        - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/rdp/cve_2019_0708_bluekeep) > set rhosts 192.168.134.142
rhosts => 192.168.134.142
msf5 auxiliary(scanner/rdp/cve_2019_0708_bluekeep) > run

[*] 192.168.134.142:3389  - Verifying RDP protocol...
[*] 192.168.134.142:3389  - Attempting to connect using TLS security
[*] 192.168.134.142:3389  - Verifying RDP protocol...
[*] 192.168.134.142:3389  - Attempting to connect using TLS security
[*] 192.168.134.142:3389  - Detected RDP on 192.168.134.142:3389  (Windows version: 6.1.7600) (Requires NLA: No)
[*] 192.168.134.142:3389  - Sending erect domain request
[*] 192.168.134.142:3389  - Sending client info PDU
[*] 192.168.134.142:3389  - Received License packet (34 bytes)
[*] 192.168.134.142:3389  - Got license packet type 0xff (LICENSE_ERROR_ALERT)
[*] 192.168.134.142:3389  - License error/alert code 0x7 (LICENSE_ISSUED)
[*] 192.168.134.142:3389  - Waiting for Server Demand packet
[*] 192.168.134.142:3389  - Received Server Demand packet
[*] 192.168.134.142:3389  - Sending client confirm active PDU
[*] 192.168.134.142:3389  - Sending client synchronize PDU
[*] 192.168.134.142:3389  - Sending client control cooperate PDU
[*] 192.168.134.142:3389  - Sending client control request control PDU
[*] 192.168.134.142:3389  - Sending client input sychronize PDU
[*] 192.168.134.142:3389  - Sending client font list PDU
[*] 192.168.134.142:3389  - Sending patch check payloads
[+] 192.168.134.142:3389  - The target is vulnerable: The target attempted cleanup of the incorrectly-bound MS_T120 channel.
[*] 192.168.134.142:3389  - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/rdp/cve_2019_0708_bluekeep) > 
```

2019-10-15 16:07 UTC, merged

2019-10-15 16:10 UTC, bwatters-r7 commented
# Release Notes
This PR adds the ability to add custom messages to default error and success messages so that a specific module can give tailored feedback when a predicted condition occurs.