Fix undefined port (RPORT option ) in SAP brute module
rapid7/metasploit-framework pull request #12479
Opened 2019-10-22 18:02 UTC by trolldbois

Define lcoal var port, to reflect the value of RPORT, 
otherwise, L172 fails, as port (RPORT) is not defined

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use scanner/sap/sap_mgmt_con_brute_login`
- [ ] set RHOSTS <target>
- [ ] set PASSWORD a_password
- [ ] ... find credentials that work

## previous error
[-] Auxiliary failed: NameError undefined local variable or method `port' for #<Msf::Modules::Auxiliary__Scanner__Sap__Sap_mgmt_con_brute_login::MetasploitModule:0x000055dad69f4f78>
Did you mean?  rport
[-] Call stack:
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/sap/sap_mgmt_con_brute_login.rb:170:in `enum_user'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/sap/sap_mgmt_con_brute_login.rb:58:in `block in run_host'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/auth_brute.rb:211:in `block in each_user_pass'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/auth_brute.rb:179:in `each'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/auth_brute.rb:179:in `each_user_pass'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/sap/sap_mgmt_con_brute_login.rb:57:in `run_host'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:111:in `block (2 levels) in run'
[-]   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:106:in `block in spawn'

2019-10-22 19:41 UTC, h00die commented
I believe this bug is from just 1 line of [code calling port instead of rport](https://github.com/rapid7/metasploit-framework/blob/f39a7f2a33567b25c944a5d11b6effb5f8dc061e/modules/auxiliary/scanner/sap/sap_mgmt_con_brute_login.rb#L172).  However instead of fixing the one call, you added another line of code just to alias the variable. Wouldn't it not be easier to just change `port` to `datastore['RPORT']`?  I may be missing other things, just asking.

2019-10-23 19:29 UTC, acammack-r7 requested changes

2019-10-23 19:29 UTC, acammack-r7 commented on modules/auxiliary/scanner/sap/sap_mgmt_con_brute_login.rb
> +        port: datastore['RPORT'],
```suggestion
        port: rport,
```
I think this is what @h00die was going for. Remote exploits have some nice convenience methods methods for accessing normalized datastore values including `rport` and `rhost` used above.

2019-11-07 22:54 UTC, acammack-r7 approved these changes

2019-11-08 06:41 UTC, bcoles approved these changes

2019-11-18 23:10 UTC, busterb commented
2 approved, let's land it!

2019-11-18 23:13 UTC, merged

2019-11-18 23:15 UTC, busterb commented
## Release Notes

This fixes a error when running the sap_mgmt_con_brute_login aux module.