Refactor CheckScanner to CheckModule to support most aux modules
rapid7/metasploit-framework pull request #12517
Opened 2019-10-31 03:31 UTC by wvu-r7

This is an enhancement to #11873 that will be used in #12515. Related to #12428.

```
msf5 > git grep CheckScanner
[*] exec: git grep CheckScanner

msf5 > git grep -l CheckModule
[*] exec: git grep -l CheckModule

lib/msf/core/exploit/check_module.rb
modules/exploits/windows/rdp/cve_2019_0708_bluekeep_rce.rb
modules/exploits/windows/smb/ms17_010_eternalblue.rb
modules/exploits/windows/smb/ms17_010_psexec.rb
msf5 > setg rhosts 192.168.56.117
rhosts => 192.168.56.117
msf5 > use modules/exploits/windows/rdp/cve_2019_0708_bluekeep_rce.rb
msf5 exploit(windows/rdp/cve_2019_0708_bluekeep_rce) > check

[*] 192.168.56.117:3389   - Verifying RDP protocol...
[*] 192.168.56.117:3389   - Attempting to connect using TLS security
[*] 192.168.56.117:3389   - Verifying RDP protocol...
[*] 192.168.56.117:3389   - Attempting to connect using TLS security
[*] 192.168.56.117:3389   - Detected RDP on 192.168.56.117:3389   (Windows version: 6.1.7601) (Requires NLA: No)
[*] 192.168.56.117:3389   - Sending erect domain request
[*] 192.168.56.117:3389   - Sending client info PDU
[*] 192.168.56.117:3389   - Received License packet (34 bytes)
[*] 192.168.56.117:3389   - Got license packet type 0xff (LICENSE_ERROR_ALERT)
[*] 192.168.56.117:3389   - License error/alert code 0x7 (LICENSE_ISSUED)
[*] 192.168.56.117:3389   - Waiting for Server Demand packet
[*] 192.168.56.117:3389   - Received Server Demand packet
[*] 192.168.56.117:3389   - Sending client confirm active PDU
[*] 192.168.56.117:3389   - Sending client synchronize PDU
[*] 192.168.56.117:3389   - Sending client control cooperate PDU
[*] 192.168.56.117:3389   - Sending client control request control PDU
[*] 192.168.56.117:3389   - Sending client input sychronize PDU
[*] 192.168.56.117:3389   - Sending client font list PDU
[*] 192.168.56.117:3389   - Sending patch check payloads
[+] 192.168.56.117:3389   - The target is vulnerable. The target attempted cleanup of the incorrectly-bound MS_T120 channel.
[+] 192.168.56.117:3389 - The target is vulnerable. The target attempted cleanup of the incorrectly-bound MS_T120 channel.
msf5 exploit(windows/rdp/cve_2019_0708_bluekeep_rce) > use modules/exploits/windows/smb/ms17_010_eternalblue.rb
msf5 exploit(windows/smb/ms17_010_eternalblue) > check

[*] 192.168.56.117:445    - Connected to \\192.168.56.117\IPC$ with TID = 2048
[*] 192.168.56.117:445    - Received STATUS_INSUFF_SERVER_RESOURCES with FID = 0
[+] 192.168.56.117:445    - Host is likely VULNERABLE to MS17-010! - Windows 7 Professional 7601 Service Pack 1 x64 (64-bit)
[+] 192.168.56.117:445 - The target is vulnerable.
msf5 exploit(windows/smb/ms17_010_eternalblue) > use modules/exploits/windows/smb/ms17_010_psexec.rb
msf5 exploit(windows/smb/ms17_010_psexec) > check

[*] 192.168.56.117:445    - Connected to \\192.168.56.117\IPC$ with TID = 2048
[*] 192.168.56.117:445    - Received STATUS_INSUFF_SERVER_RESOURCES with FID = 0
[+] 192.168.56.117:445    - Host is likely VULNERABLE to MS17-010! - Windows 7 Professional 7601 Service Pack 1 x64 (64-bit)
[+] 192.168.56.117:445 - The target is vulnerable.
msf5 exploit(windows/smb/ms17_010_psexec) >
```

2019-10-31 18:01 UTC, wvu-r7 commented
Would appreciate your eyes on this, too, @acammack-r7. This was another quick PR, so it may be just as rough. :)

2019-11-05 08:03 UTC, acammack-r7 commented on lib/msf/core/exploit/check_module.rb
> +    mod.datastore.merge!(datastore)
This seems dangerous:
```
irb(main):001:0> a = {}
=> {}
irb(main):002:0> b = {a: "a"}
=> {:a=>"a"}
irb(main):003:0> a.merge! b
=> {:a=>"a"}
irb(main):004:0> b[:a] << "sdf"
=> "asdf"
irb(main):005:0> a[:a]
=> "asdf"
```
Also, I reckon we should kick off the validation process here as well, since I don't think we can necessarily assume datastore parity.

2019-11-05 08:04 UTC, acammack-r7 commented on lib/msf/core/exploit/check_module.rb
> +    checkcode =
In the case of running in general, I think the code assumes a measure of exception handling not present here distilled in: https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/base/simple/auxiliary.rb#L62

2019-11-05 16:08 UTC, wvu-r7 commented on lib/msf/core/exploit/check_module.rb
> +    mod.datastore.merge!(datastore)
It is dangerous indeed. I didn't have a better idea at the time. Note that this very obviously will clobber the newly created module's datastore, too. I've been thinking I should limit it to the options required for targeting, such as `RHOSTS` and `RPORT`.

2019-11-05 16:15 UTC, wvu-r7 commented on lib/msf/core/exploit/check_module.rb
> +    mod.datastore.merge!(datastore)
If we do `RHOSTS`, it'll have to be labeled `msf5`, methinks.

2019-11-05 16:22 UTC, wvu-r7 commented on lib/msf/core/exploit/check_module.rb
> +    checkcode =
Good catch. I missed that, since I must have been pre-validating the exploit's datastore with `set` or `run`, and those options would be correct for the check module.

2019-11-06 04:34 UTC, acammack-r7 commented on lib/msf/core/exploit/check_module.rb
> +    mod.datastore.merge!(datastore)
`#dup` should be good enough for this purpose, I imagine. Since we are creating a new module (and not passing one around like we assume in most places), I'm fine with clobbering this module's datastore and not using the `#replicant` hax.

`RHOSTS` is tricky, even in msf5 a lot of how that is handled is in the command dispatcher and not in framework or the modules themselves.

2019-11-07 17:13 UTC, wvu-r7 commented on lib/msf/core/exploit/check_module.rb
> +    mod.options.validate(mod.datastore)
This will `raise`, but note that the command dispatcher will catch `RHOST(S)` and `RPORT` validation errors before getting to this point.

2019-11-07 17:21 UTC, wvu-r7 commented on lib/msf/core/exploit/check_module.rb
> +    options.validate(datastore)
Again, the command dispatcher will catch errors before getting to this point.

2019-11-07 18:25 UTC, wvu-r7 commented
@acammack-r7: I'm still iffy on the current code, but it should be a little better. Please review when you're able. Thank you. :)

2019-12-03 16:41 UTC, wvu-r7 commented
Rebased to retrieve and use in #12515.

2019-12-13 16:26 UTC, wvu-r7 commented
Hi, @acammack-r7. Sorry to bother. Can I get eyes on this? If an overhaul of this system isn't expected soon, I'd like to get this in, since it improves (arguably fixes) existing behavior of the feature with proper validation.

Converting from `CheckScanner` to `CheckModule` is only a small part of this PR. We already have a few modules that are actively using `CheckScanner` and could benefit from the additional validation. It's an easy win to use an aux module as an exploit's `check` method, edge cases notwithstanding.

2019-12-16 18:18 UTC, acammack-r7 requested changes
This is better about module isolation now, but it needs to reuse more code. Additionally, this should probably implement `#has_check?` in anticipation of #12702.

2019-12-16 18:18 UTC, acammack-r7 commented on lib/msf/core/exploit/check_module.rb
> +      meth = :run_host
`Msf::Auxiliary::Scanner#run` now returns results, so a separate check for `run_host` isn't needed.

2019-12-16 18:18 UTC, acammack-r7 commented on lib/msf/core/exploit/check_module.rb
> +      end
This _should_ boil down to something like:
```ruby
checkcode = mod.run_simple({'LocalInput' => user_input, 'LocalOutput' => user_output, 'Options' => datastore.slice('RHOSTS', 'RHOST', 'RPORT')}
```

The biggest reason is that the aux-specific error class are not handled properly by the things that run exploits and exploit checks.

2019-12-16 18:18 UTC, acammack-r7 commented on lib/msf/core/exploit/check_module.rb
> +      return Exploit::CheckCode::Unsupported
These should be combined as well.

2019-12-16 18:18 UTC, acammack-r7 commented on lib/msf/core/exploit/check_module.rb
> +    unless checkcode.kind_of?(Exploit::CheckCode)
If using `Msf::Auxiliary::Scanner#run`, you will get a hash of `{'ip_address' => check_code}` back to deal with here.

2019-12-16 19:17 UTC, wvu-r7 commented on lib/msf/core/exploit/check_module.rb
> +    end
[This is awesome.](https://dev.to/jeremy/ruby-method-spotlight-slice-1f3j) I should track Ruby changes more attentively. Thanks!

2019-12-16 19:38 UTC, wvu-r7 commented on lib/msf/core/exploit/check_module.rb
> +      meth = :run_host
Good point. `run` is the entry point for `run_host`, anyway. This check is unnecessary.

2019-12-16 19:47 UTC, wvu-r7 commented on lib/msf/core/exploit/check_module.rb
> +      end
Yes, this should use `run_simple` if possible.

2019-12-16 19:56 UTC, wvu-r7 commented on lib/msf/core/exploit/check_module.rb
> +    unless checkcode.kind_of?(Exploit::CheckCode)
Noted, thanks. I care about the visual output of a check and logging any results to the DB. This was intended to be strict about `CheckCode` as a return value, but I don't think it's entirely necessary to the end goal, specifically not here.

2019-12-16 20:17 UTC, wvu-r7 commented on lib/msf/core/exploit/check_module.rb
> +    end
FWIW, this requires `datastore.to_h.slice('RHOSTS', 'RHOST', 'RPORT')`.

2019-12-16 20:17 UTC, wvu-r7 commented on lib/msf/core/exploit/check_module.rb
> +      end
https://github.com/rapid7/metasploit-framework/pull/12517#discussion_r358442959

2019-12-16 20:25 UTC, wvu-r7 commented on lib/msf/core/exploit/check_module.rb
> +      meth = :run_host
(As of #12509.)

2019-12-16 20:25 UTC, wvu-r7 commented on lib/msf/core/exploit/check_module.rb
> +    unless checkcode.kind_of?(Exploit::CheckCode)
https://github.com/rapid7/metasploit-framework/pull/12517#discussion_r358446135

2019-12-16 20:39 UTC, wvu-r7 commented
Hey, I'm adding a check to ensure the instantiated module is an aux module.

2019-12-16 23:41 UTC, merged

2019-12-16 23:47 UTC, busterb commented
## Release Notes

This renames the CheckScanner mixin to CheckModule, allowing any aux module to be used as a check for an exploit module.

2019-12-17 00:02 UTC, busterb commented
I might have missed a few more changes that y'all wanted to make, feel free to follow up with more enhancement PRs. Thanks!

2019-12-17 00:06 UTC, wvu-r7 commented
Oof, yeah, wasn't done. No worries, I'll push what I have soon.