Convert all python code to python3. Fixes #12506.
rapid7/metasploit-framework pull request #12524
Opened 2019-10-31 21:32 UTC by xmunoz

This is a breaking change that removes support for python2. Not every file in the change has been fully tested because of limited access to the exploit target environments, but running with `python3 $FILE` produced no syntax errors when the needed dependencies were available. These changes were made with the following command:

    2to3-2.7 -f all -f ws_comma -w -n $FILE

[2to3](https://docs.python.org/3/library/2to3.html) is the recommended utility for auto translation for python 2 -> 3. I also manually edited some files where 2to3 performed unexpectedly.

Related: https://gitlab.com/kalilinux/packages/metasploit-framework/issues/1

2019-11-01 00:42 UTC, wvu-r7 commented
Wow, thanks!

2019-11-01 22:59 UTC, acammack-r7 requested changes
Thanks for your work on this! I think we will want a somewhat different approach from this, though. First, the output of 2to3 is a bit quirky and there are some things, like extra calls to `list()`, that we do not need or want. Next, a couple of these files are intended to run on older systems that definitely have Python 2 but may not have Python 3, or if the user has installed it, it may not be where we expect (also, the module that runs this privilege escalation scripts would need to be updated to look for Python 3). Finally, Python 2 is still around for a bit yet, and since dual-compatibility is not a huge lift for us I am reluctant to wholesale drop support for it in modules or external module libraries that do not explicitly need Python 3 features (like the async stuff). Tools and build scripts I think are fine to move to 3, since they are intended to be run by developers.

On the shebangs, files that can run under 2 and 3 should be allowed to do so. Also, as I understand it, the encoding can now taken from the operating system's `LOCALE` as well, which means we still have to specify the encoding to ensure the files are read properly.

Thanks again for submitting this, there are definitely a couple places you caught that I wouldn't have thought to check!

2019-11-01 22:59 UTC, acammack-r7 commented on data/exploits/cve-2015-5287/sosreport-rhel7.py
> +os.chmod(sosreport,0o777)
This is an old exploit that runs only on targets that have Python 2 installed as the default and does not need to be updated.

2019-11-02 01:38 UTC, xmunoz commented
Thanks for the comprehensive review! I'll clean this up shortly.

2019-11-02 01:45 UTC, xmunoz commented on data/exploits/cve-2015-5287/sosreport-rhel7.py
> +os.chmod(sosreport,0o777)
Ok, I'll revert all the changes to this file.

2019-11-05 07:52 UTC, acammack-r7 approved these changes

2019-11-05 07:54 UTC, acammack-r7 commented
Thanks for the cleanup, the changes look good! I haven't had a chance to test all the moving parts yet, but I have added some verification steps to the OP for anyone who wants to help out verifying these changes.

2019-11-08 19:14 UTC, xmunoz commented
When I was testing the windows shellcode builders, I encountered 2 errors on master.

1) On `external/source/shellcode/windows/x64/build.py`:

    $ python build.py all
    ...
    ./src/block/block_reverse_https.asm:148: warning: `ptr' is not a NASM keyword [-w+ptr]
    ./src/block/block_reverse_https.asm:148: error: comma, colon, decorator or end of line expected after operand
    [-]  [Errno 2] No such file or directory: 'bin/stager_reverse_https.bin'

According to [this](https://stackoverflow.com/a/13791007/1299373), you can just remove the `ptr` keyword. When I did that, the script ran to completion. I ran it on master and this branch, and compared the output. The results were identical.
```
$ diff result-master.txt result-python3.txt
1c1
< # Built on Fri Nov  8 10:47:56 2019
---
> # Built on Fri Nov  8 10:51:53 2019
```
Should I add this change to this PR?

```
$ git diff external/source/shellcode/windows/x64/src/block/block_reverse_https.asm
diff --git a/external/source/shellcode/windows/x64/src/block/block_reverse_https.asm b/external/source/shellcode/windows/x64/src/block/block_reverse_https.asm
index 7578b590c1..604d47c8ad 100644
--- a/external/source/shellcode/windows/x64/src/block/block_reverse_https.asm
+++ b/external/source/shellcode/windows/x64/src/block/block_reverse_https.asm
@@ -145,7 +145,7 @@ download_more:
   test eax,eax           ; download failed? (optional?)
   jz failure

-  mov ax, word ptr [edi]
+  mov ax, word [edi]
   add rbx, rax           ; buffer += bytes_received

   test rax,rax           ; optional?
```

2) On `external/source/shellcode/windows/x86/src/build.py`:

```
$ python build.py all
...
src/stager/stager_reverse_winhttp.asm:17: fatal: unable to open include file `./src/block/block_reverse_winhttp_http.asm'
[-]  [Errno 2] No such file or directory: 'bin/stager_reverse_winhttp.bin'
```

Here is the change required to make this run:
```
$ git diff external/source/shellcode/windows/x86/src/stager/stager_reverse_winhttp.asm
diff --git a/external/source/shellcode/windows/x86/src/stager/stager_reverse_winhttp.asm b/external/source/shellcode/windows/x86/src/stager/stager_reverse_winhttp.asm
index 7e32a9b3b8..bb8af3e470 100644
--- a/external/source/shellcode/windows/x86/src/stager/stager_reverse_winhttp.asm
+++ b/external/source/shellcode/windows/x86/src/stager/stager_reverse_winhttp.asm
@@ -14,6 +14,6 @@
 %include "./src/block/block_api.asm"
 start:                   ;
   pop ebp                ; pop off the address of 'api_call' for calling later.
-%include "./src/block/block_reverse_winhttp_http.asm"
+%include "./src/block/block_reverse_winhttp.asm"
   ; By here we will have performed the reverse_tcp connection and EDI will be our socket.
```

Should I add that change to this PR? Similar to above, I diff-ed the results from master and this branch after the edit was made, and the results were identical.

I think the first checkbox can be checked.

If you could give me some pointers for testing the other ones that would be great.

2019-11-11 22:42 UTC, xmunoz commented
ping @acammack-r7

2019-11-12 17:14 UTC, acammack-r7 commented
1. This is a NASM/MASM issue, and since it's Windows shellcode I'm inclined to leave it in the MASM style (IIRC MASM does require `ptr` in this case).
1. That does look like a bug in the assembly. This PR is works great, thanks!

In Metasploit the verification steps are mostly for the person landing the PR to verify all the proposed changes have their expected result. Verifying the rest of the changes will require a [Metasploit development environment](https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment) and a working knowledge of how to use `msfconsole` (the [SANS cheat sheet](https://www.sans.org/security-resources/sec560/misc_tools_sheet_v1.pdf) is a little out of date, but has the basics). Each of those PRs has a list of verification steps like this list the software that needs to be installed to test the module and how the modules are expected to run. If you want to go through all that, that's great and will definitely help us get this landed sooner! Even if you do, though, someone else will still need to verify the changes you have pushed do the right thing (a sad result of us not having good automated testing around modules).

I'll try to set aside some time to look at this since I have most of this software set up already, but the code looks good and any the team members that want to take this on can.

2019-12-19 14:44 UTC, busterb commented
Noting that a few of these don't work after the upgrade, will push fixes to the scripts.

2019-12-19 15:37 UTC, acammack-r7 commented
@busterb Did you the discussion the NASM/MASM difference?

> This is a NASM/MASM issue, and since it's Windows shellcode I'm inclined to leave it in the MASM style (IIRC MASM does require ptr in this case).

2019-12-19 15:54 UTC, busterb commented
Ah, thanks, maybe can make them both happy. I'm suspect the last time this was built and updated statically in framework though, it wasn't with masm.

2019-12-19 16:10 UTC, acammack-r7 commented
That is a good point, looking again at it now it calls`nasm` explicitly. Removing `ptr` should be fine, then.

2019-12-19 16:29 UTC, busterb commented
It might be possible to rewrite the asm on the fly so we filter keywords to make it happy in the build process, but I think just preferring nasm is the best case, since this is an area somewhat rarely visited by most users and developers.

2019-12-20 15:27 UTC, busterb commented on tools/hardware/killerbee_msfrelay.py
> -#!/usr/bin/env python
there is no python3 release of killerbee, making this conversion not really possible at this time.

2019-12-23 20:50 UTC, merged

2019-12-23 20:51 UTC, busterb commented
## Release Notes

This updates most Python code in Metasploit Framework to be compatible with Python 3.