Add Wordpress Plainview Activity Monitor RCE
rapid7/metasploit-framework pull request #12555
Opened 2019-11-10 07:29 UTC by leo-lb

Description:

```
Plainview Activity Monitor Wordpress plugin is vulnerable to OS
command injection which allows an attacker to remotely execute
commands on underlying system. Application passes unsafe user supplied
data to ip parameter into activities_overview.php.
Privileges are required in order to exploit this vulnerability, but
this plugin version is also vulnerable to CSRF attack and Reflected
XSS. Combined, these three vulnerabilities can lead to Remote Command
Execution just with an admin click on a malicious link.
```

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

Please ensure you are submitting **from a unique branch** in your [repository](https://github.com/rapid7/metasploit-framework/pull/11086#issuecomment-445506416) to master in Rapid7's.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/smb/ms08_067_netapi`
- [ ] ...
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not
- [ ] **Document** the thing and how it works ([Example](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/multi/gather/aws_keys.md))

2019-11-10 07:34 UTC, leo-lb commented
@bcoles The code is partially inspired from exploits/unix/webapp/wp_total_cache_exec and I took your documentation as a template from https://github.com/rapid7/metasploit-framework/pull/12532 -- I hope that's OK.

2019-11-10 07:38 UTC, bcoles commented
> 
> 
> @bcoles The code is partially inspired from **exploits/unix/webapp/wp_total_cache_exec** and I took your documentation as a template from #12532 -- I hope that's OK.

No worries. The code is pretty standard - mostly boiler plate.

2019-11-27 12:48 UTC, cdelafuente-r7 requested changes
Thanks for this great contribution! I just have some comments before it lands.

2019-11-27 19:20 UTC, leo-lb commented on modules/exploits/unix/webapp/wp_plainview_activity_monitor_rce.rb
> +          Execution just with an admin click on a malicious link.
I copy pasted the description from the exploit-db post, so I do not know what these references are.

2019-11-27 19:34 UTC, leo-lb commented on modules/exploits/unix/webapp/wp_plainview_activity_monitor_rce.rb
> +  Rank = NormalRanking
I thought that was determined through testing rather and I didnt want to assume anything before hand, but indeed, there isnt much unknown in the success of that exploit.

2019-11-27 20:40 UTC, leo-lb commented on modules/exploits/unix/webapp/wp_plainview_activity_monitor_rce.rb
> +    end
Hmm, cool function, but how can I express "that version and below"?

2019-11-27 20:40 UTC, leo-lb commented on modules/exploits/unix/webapp/wp_plainview_activity_monitor_rce.rb
> +    @password = datastore['PASSWORD']
Yes, I will.

2019-11-28 10:39 UTC, cdelafuente-r7 commented on modules/exploits/unix/webapp/wp_plainview_activity_monitor_rce.rb
> +          Execution just with an admin click on a malicious link.
Sure, no worry. Maybe adding the vulnerable versions and/or fixed version to the description would be enough.

2019-11-28 10:40 UTC, cdelafuente-r7 commented on modules/exploits/unix/webapp/wp_plainview_activity_monitor_rce.rb
> +  Rank = NormalRanking
Awesome! Thanks!

2019-11-28 10:40 UTC, cdelafuente-r7 commented on modules/exploits/unix/webapp/wp_plainview_activity_monitor_rce.rb
> +    end
The `check_plugin_version_from_readme` method accepts 3 arguments (see https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/exploit/http/wordpress/version.rb#L43-L52):
```ruby
  # Checks a readme for a vulnerable version
  #
  # @param [String] plugin_name The name of the plugin
  # @param [String] fixed_version Optional, the version the vulnerability was fixed in
  # @param [String] vuln_introduced_version Optional, the version the vulnerability was introduced
  #
  # @return [ Msf::Exploit::CheckCode ]
  def check_plugin_version_from_readme(plugin_name, fixed_version = nil, vuln_introduced_version = nil)
...
```
So, you can express "below that version" (`fixed_version`) and "from that version" (`vuln_introduced_version`). Both are optional and you can use any combination of them. The helper method will automatically check if the plugin version is in the vulnerable range.

Using this will express "below version 20180826":
```ruby
check_plugin_version_from_readme('plainview-activity-monitor', '20180826')
```

2019-11-28 10:40 UTC, cdelafuente-r7 commented on modules/exploits/unix/webapp/wp_plainview_activity_monitor_rce.rb
> +    @password = datastore['PASSWORD']
Thanks!

2019-11-28 11:48 UTC, cdelafuente-r7 requested changes

2019-11-28 11:48 UTC, cdelafuente-r7 commented on modules/exploits/unix/webapp/wp_plainview_activity_monitor_rce.rb
> +    unless check == CheckCode::Detected
`check_plugin_version_from_readme` can return the following `Msf::Exploit::CheckCode`:
- `Unknown`
- `Detected`
- `Appears`
- `Safe`

Please, see the descriptions here: https://github.com/rapid7/metasploit-framework/wiki/How-to-write-a-check()-method#check-codes

So, you can decide to be restrictive and run the exploit only if we are certain this version is vulnerable (`Appears`). Or, be more flexible and also try to exploit if we detected it is a Wordpress but we're not able to get the version (add `Detected` and/or `Unknown` to the list). Or, simply bail out if we are `Safe`. It's up to you.

The way it behaves now is that only `Detected` allows to run the exploit. At least, `Appears` should be on the list.

2019-11-28 19:56 UTC, leo-lb commented on modules/exploits/unix/webapp/wp_plainview_activity_monitor_rce.rb
> +    unless check == CheckCode::Detected
Hopefully it's good now!

2019-11-28 19:56 UTC, leo-lb commented on modules/exploits/unix/webapp/wp_plainview_activity_monitor_rce.rb
> +          Execution just with an admin click on a malicious link.
Added!

2019-11-29 10:04 UTC, cdelafuente-r7 commented on modules/exploits/unix/webapp/wp_plainview_activity_monitor_rce.rb
> +          Execution just with an admin click on a malicious link.
Thanks!

2019-11-29 10:04 UTC, cdelafuente-r7 commented on modules/exploits/unix/webapp/wp_plainview_activity_monitor_rce.rb
> +    unless check == CheckCode::Detected
Awesome! Thanks!

2019-11-29 10:05 UTC, cdelafuente-r7 approved these changes

2019-11-29 10:12 UTC, cdelafuente-r7 commented
Thanks! Great job on this one!

2019-11-29 10:13 UTC, merged

2019-11-29 10:27 UTC, leo-lb commented
@cdelafuente-r7 my commits werent squashed, it just trashed master's commit history :/

2019-12-02 18:07 UTC, cdelafuente-r7 commented
No worry, I agree these last commits could have been squashed before it lands, but it's not a problem. Master's commit history is fine :)

2019-12-11 17:30 UTC, tdoan-r7 commented
# Release Notes
The wp_plainview_activity_monitor_rce module has been added to the framework. It targets the Plainview Activity Monitor Wordpress plugin, which is is vulnerable to OS command injection that allows an attacker to remotely execute commands on underlying system.