Create apple_accp_scanner and afp_login module documentation.
rapid7/metasploit-framework pull request #12607
Opened 2019-11-19 21:21 UTC by kenlacroix

Create documentation.

2019-11-21 16:19 UTC, wvu approved these changes
This is excellent. Thank you for doing this!

2019-11-21 18:52 UTC, h00die requested changes

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/acpp/apple_acpp_scanner.md
> +      ...show and set options...
this line can be removed

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/acpp/apple_acpp_scanner.md
> +  4. Do: `run`
add a line for ```set rhosts [ip]```

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/acpp/apple_acpp_scanner.md
> +
Add an L3 header for what type of device (version, os) if possible.  For example:
```
### Apple Airport v2 OS 2.9
```

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/afp/afp_login.md
> +[developer.apple.com](https://developer.apple.com/library/mac/documentation/Networking/Reference/AFP_Reference/Reference/reference.html)
I would rename this link to AFP_Reference

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/afp/afp_login.md
> +[developer.apple/com](https://developer.apple.com/library/mac/documentation/networking/conceptual/afp/AFPSecurity/AFPSecurity.html)
I woudl rename this link to AFP_Security

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/afp/afp_login.md
> +1. `sudo apt-get install netatalk`
Can you add an L3 header to say what OS you did this on?
Exmaple:
```
### Kali 2019.3
```

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/afp/afp_login.md
> +      ...show and set options...
remove

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/acpp/apple_acpp_scanner.md
> +  3. Do: `show options`
this can be removed

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/afp/afp_login.md
> +  3. Do: `show options`
add a line for ```set rhosts [ip]``` instead of options

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/afp/afp_login.md
> +
Can you add an L3 header saying what os/version of the software this is.
Example:
```
### netatalk v2.1 on Kali 2019.3
```

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/db2/db2_auth.md
> +More information can be found on the [Rapid7 Vulnerability & Exploit Database page](https://www.rapid7.com/db/modules/auxiliary/scanner/db2/db2_auth) and https://nvd.nist.gov/vuln/detail/CVE-1999-050
you can remove the CVE reference, it's just a 'weak password' one and not specific

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/db2/db2_auth.md
> +
same as before, add L3 with host details

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/db2/db2_auth.md
> +  3. Do: `show options`
same as before, remove options, add rhosts

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/db2/db2_version.md
> +  3. Do: `show options`
same as before, remove options, add rhosts

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/dcerpc/windows_deployment_services.md
> +More information can be found on the [Rapid7 Vulnerability & Exploit Database page](https://www.rapid7.com/db/modules/auxiliary/scanner/dcerpc/windows_deployment_services) and pull request #1420 (htt
```[#1420]```

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/dcerpc/windows_deployment_services.md
> +  3. Do: `show options`
same as before, remove options, add rhosts

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/dcerpc/windows_deployment_services.md
> +
same as before, add L3 header with what version of windows you tested this against

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/ftp/pcman_ftp_traversal.md
> +  3. Do: `show options`
same as before, remove options, add rhosts

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/ftp/pcman_ftp_traversal.md
> +A run on Windows 7 (x64) and PCMan FTP Server 2.0.7.
Change this to:
```
### PCMan FTP Server 2.0.7 on Windows 7 (X64)
```

2019-11-21 18:52 UTC, h00die commented on documentation/modules/auxiliary/scanner/ftp/pcman_ftp_traversal.md
> +## Client Software Log
I would change this to something like
```
### Manual Exploitation
```

2019-11-23 04:28 UTC, bcoles commented on documentation/modules/auxiliary/scanner/afp/afp_login.md
> +Apple Filing Protocol (AFP) is Apple's file sharing protocol similar to SMB, and NFS. This module attempts to bruteforce authentication credentials for AFP.
For consistency with `brute force` phrasing elsewhere.

```suggestion
Apple Filing Protocol (AFP) is Apple's file sharing protocol similar to SMB, and NFS. This module attempts to brute force authentication credentials for AFP.
```

2019-11-23 04:28 UTC, bcoles commented on documentation/modules/auxiliary/scanner/afp/afp_login.md
> +  4. set RHOSTS [ip]
```suggestion
  3. set RHOSTS [ip]
```

2019-11-23 04:28 UTC, bcoles commented on documentation/modules/auxiliary/scanner/afp/afp_login.md
> +  5. Do: `run`
```suggestion
  4. Do: `run`
```

2019-11-23 04:28 UTC, bcoles commented on documentation/modules/auxiliary/scanner/afp/afp_server_info.md
>  The following was done on Ubuntu 16.04, and is largely base on [missingreadme.wordpress.com](https://missingreadme.wordpress.com/2010/05/08/how-to-set-up-afp-filesharing-on-ubuntu/):
```suggestion
The following was done on Ubuntu 16.04, and is largely based on [missingreadme.wordpress.com](https://missingreadme.wordpress.com/2010/05/08/how-to-set-up-afp-filesharing-on-ubuntu/):
```

2019-11-23 04:28 UTC, bcoles commented on documentation/modules/auxiliary/scanner/afp/afp_server_info.md
>    4. Do: `run`
```suggestion
  5. Do: `run`
```

2019-11-23 04:28 UTC, bcoles commented on documentation/modules/auxiliary/scanner/db2/db2_auth.md
> +This module attempts to authenticate against a DB2 instance using username and password combinations indicated by the USER_FILE, PASS_FILE, and USERPASS_FILE options.
```suggestion
This module attempts to authenticate against a DB2 instance using username and password combinations indicated by the `USER_FILE`, `PASS_FILE`, and `USERPASS_FILE` options.
```

2019-11-23 04:28 UTC, bcoles commented on documentation/modules/auxiliary/scanner/db2/db2_version.md
> +  3. Do: `run`
```suggestion
  4. Do: `run`
```

2019-11-23 04:28 UTC, bcoles commented on documentation/modules/auxiliary/scanner/discovery/empty_udp.md
> +4. Do: `run`
```suggestion
5. Do: `run`
```

2019-11-23 18:02 UTC, merged

2019-11-23 18:03 UTC, h00die commented
Thanks for the first time submission @kenlacroix , tons of new docs which are always great!
I had a few touch-ups, nothing major. https://github.com/rapid7/metasploit-framework/commit/238bfa9b67e5787c5cb1417e1ae45f56d718997f

2019-11-23 18:03 UTC, h00die commented
# Release Notes
This PR adds 10 new module docs for varying auxiliary modules.