Documentation.
rapid7/metasploit-framework pull request #12632
Opened 2019-11-27 02:37 UTC by kenlacroix

Create documentation.

2019-11-28 16:29 UTC, h00die commented
@kenlacroix let us know when youre done.  I would suggest either waiting till theyre all ready to post the PR, or putting `WIP:` as the start of the title, then removing it when its ready.

2019-12-02 19:10 UTC, kenlacroix commented
@h00die Ready for review.

2019-12-02 19:37 UTC, h00die commented
one general note, usually when we get a shell open, i like to do a `sysinfo` and a `getuid`, just to show a little more info right from meterp.  No need to re-create these ones, but something that would be easy to add in the future.

2019-12-02 20:52 UTC, kenlacroix commented
> one general note, usually when we get a shell open, i like to do a `sysinfo` and a `getuid`, just to show a little more info right from meterp. No need to re-create these ones, but something that would be easy to add in the future.

Good idea, will do in the future, updated ms06_040_netapi.md as I had that one still open.

2019-12-02 21:41 UTC, h00die requested changes

2019-12-02 21:41 UTC, h00die commented on documentation/modules/exploit/windows/smb/ms04_007_killbill.md
> +This exploit has been successfully tested with the win32/[all]/reverse_tcp payloads, however a few problems were encountered when using the equivalent bind payloads. Your mileage may vary.
so this is an old reference i believe since everything now is `windows/`, reference https://github.com/rapid7/metasploit-framework/pull/12646#issuecomment-560132897

2019-12-02 21:41 UTC, h00die commented on documentation/modules/exploit/windows/smb/ms04_007_killbill.md
> +### A run on Windows 2000 (Build 2195, SP4) and Kali Linux 2019.3
not an issue, but did you have to do anything special to make the box exploitable? as per https://github.com/rapid7/metasploit-framework/pull/12646#issuecomment-560133023 i attempted this on an sp4 rollup1 box and it failed.

2019-12-02 21:41 UTC, h00die commented on documentation/modules/exploit/windows/smb/ms06_040_netapi.md
> +  6. Do: `set LPORT [IP]`
lport ip?

2019-12-02 21:41 UTC, h00die commented on documentation/modules/exploit/windows/smb/ms04_007_killbill.md
> +  5. Do: `set LPORT [IP]`
lport ip?

2019-12-02 22:27 UTC, kenlacroix commented on documentation/modules/exploit/windows/smb/ms04_007_killbill.md
> +### A run on Windows 2000 (Build 2195, SP4) and Kali Linux 2019.3
Nothing special, rollup 1 includes "823559: Security Update for Microsoft Windows" which might fix the issue. Test machine is only SP4. Retested, got shell.

2019-12-03 01:20 UTC, h00die commented on documentation/modules/exploit/windows/fileformat/ms15_100_mcl_exe.md
> +
can you add an options section (common on most docs) that outlines `filename` and `file_name`? Example: https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/exploit/freebsd/local/intel_sysret_priv_esc.md#options

2019-12-03 01:28 UTC, h00die commented on documentation/modules/exploit/windows/smb/ms04_007_killbill.md
> +### A run on Windows 2000 (Build 2195, SP4) and Kali Linux 2019.3
It looks pretty strange.
https://docs.microsoft.com/en-us/security-updates/securitybulletins/2004/ms04-007 is actually 828028, however in the Caveats section it says:
```
Windows NT 4.0 (Workstation, Server, and Terminal Server Edition) does not install the affected file by default. This file is installed as part of the MS03-041 Windows NT 4.0 security update and other possible non-security-related hotfixes. If the Windows NT 4.0 security update for MS03-041 is not installed, this may not be a required update. To verify if the affected file is installed, search for the file named Msasn1.dll. If this file is present, this security update is required. Windows Update, Software Update Services, and the Microsoft Security Baseline Analyzer will also correctly detect if this update is required.
```
How i'm reading this is that MS03-041 has to be installed to make MS04-007 be vulnerable?
If I can get a 2nd or 3rd on this (or someone who actually knows or can test, which is difficult since Win2k isn't supported AT ALL).
SP4 Rollup 1 replaces 823559 [ref](http://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=70abebd2-f515-4bd4-8683-0796f949792f), but no mention of 828028.

I'll see about uninstalling rollup 1 in the near future, then testing this.  I'd like to get this documented properly (even if it is 15yrs old...)

2019-12-03 01:43 UTC, h00die commented on documentation/modules/exploit/windows/smb/ms04_007_killbill.md
> +### A run on Windows 2000 (Build 2195, SP4) and Kali Linux 2019.3
rollup 1 was released in 2005, so you'd assume it would include an MS advisory from 2004... https://docs.microsoft.com/en-us/security-updates/securityadvisories/2005/891861

2019-12-03 02:04 UTC, h00die commented on documentation/modules/exploit/windows/smb/ms04_007_killbill.md
> +### A run on Windows 2000 (Build 2195, SP4) and Kali Linux 2019.3
confirmed, rollup 1 includes the patch.
Can you add in this, and the module description, that SP4 Rollup 1 (823559) includes the MS04-007 patch?

2019-12-03 02:17 UTC, h00die commented on documentation/modules/exploit/windows/smb/ms04_007_killbill.md
> +### A run on Windows 2000 (Build 2195, SP4) and Kali Linux 2019.3
I'm also noting that on an exploitable system you see `The server responded with error: STATUS_ACCESS_VIOLATION (Command=115 WordCount=0)`
however on a non-vulnerable Rollup1 system, you get `The server responded with error: STATUS_INVALID_PARAMETER(Command=115 WordCount=0)`
Both system respond that they are Build 2195, which is another interesting that that rollup1 didn't seem to increment the build number.


Also add in to the notes here about that difference in the error codes of vuln vs not vuln. these are good things to document

2019-12-04 01:26 UTC, h00die commented
let me know when everythings ready to be looked at again!

2019-12-04 01:39 UTC, kenlacroix commented on documentation/modules/auxiliary/scanner/voice/recorder.md
> +
This module uses generic PBX servers (like Asterisk) and thus is version independent. This module just connects to the server and once the IAX session is established, dials phone number(s) and then records the calls client-side.

2019-12-04 01:41 UTC, kenlacroix commented
> let me know when everythings ready to be looked at again!

Should be ready, let me know if any additional changes need to be made.

2019-12-05 20:01 UTC, merged

2019-12-05 20:03 UTC, h00die commented
@kenlacroix great adds as always, thanks! Glad we got more info on the kill bill stuff.

2019-12-05 20:03 UTC, h00die commented
# Release Notes
This PR adds several new doc modules, mostly for windows exploits and the aux voice scanner module.