Added Linux Bash profile persistence module
rapid7/metasploit-framework pull request #12641
Opened 2019-11-28 21:30 UTC by bluesentinelsec

This module establishes persistence via the Linux Bash profile method.
This module makes two changes to the target system.
First, the module writes a payload to a directory (`/var/temp/` by default).
Second, the module writes a payload execution trigger to the Bash profile (`~/.bashrc` by default).
The persistent payload is executed whenever the victim user opens a Bash terminal.

## Verification
  1. Start `msfconsole`
  2. Get a Linux Meterpreter session
  3. `use exploit/linux/local/bash_profile_persistence`
  4. `set SESSION [SESSION]`
  5. `run`
  6. On victim, open a new Bash terminal
  7. You should get a new session with the permissions of the exploited user account

2019-12-04 19:18 UTC, cbrnrd requested changes
Pretty good overall, just some stylistic changes. Thanks for writing this!

2019-12-04 19:18 UTC, cbrnrd commented on documentation/modules/exploit/linux/local/bash_profile_persistence.md
> +# Documentation
Remove this line

2019-12-04 19:18 UTC, cbrnrd commented on documentation/modules/exploit/linux/local/bash_profile_persistence.md
> +  **SESSION**
This option is assumed for the module type.

2019-12-04 19:18 UTC, cbrnrd commented on modules/exploits/linux/local/bash_profile_persistence.rb
> +        'Description'    => "
Please use `%Q{...}` for the description.

2019-12-04 19:18 UTC, cbrnrd commented on modules/exploits/linux/local/bash_profile_persistence.rb
> +        'SessionTypes'   => ['meterpreter'],
Any reason it's just meterpreter?

2019-12-04 19:18 UTC, cbrnrd commented on modules/exploits/linux/local/bash_profile_persistence.rb
> +
remove empty line

2019-12-04 19:18 UTC, cbrnrd commented on modules/exploits/linux/local/bash_profile_persistence.rb
> +    print_status("Bash profile is writable: #{profile_path}")
This should probably be `print_good`

2019-12-04 19:18 UTC, cbrnrd commented on modules/exploits/linux/local/bash_profile_persistence.rb
> +
remove empty line

2019-12-04 19:18 UTC, cbrnrd commented on modules/exploits/linux/local/bash_profile_persistence.rb
> +    if !writable?(profile_path)
```suggestion
    unless writable?(profile_path)
```

2019-12-04 19:18 UTC, cbrnrd commented on modules/exploits/linux/local/bash_profile_persistence.rb
> +    if !exist?(profile_path)
```suggestion
    unless exist?(profile_path)
```

2019-12-04 19:18 UTC, cbrnrd commented on modules/exploits/linux/local/bash_profile_persistence.rb
> +    print_status("Bash profile exists: #{profile_path}")
Should probably be `print_good`

2019-12-04 22:02 UTC, bluesentinelsec commented on modules/exploits/linux/local/bash_profile_persistence.rb
> +        'SessionTypes'   => ['meterpreter'],
Presently the module throws an error when executed in generic shells:
`[-] Exploit failed: NoMethodError undefined method `sys' for #<Session:shell 127.0.0.1:34166 (127.0.0.1) >`
I think its being caused by these lines:
```
home_directory = session.sys.config.getenv('$HOME')
...
hostname = session.sys.config.sysinfo["Computer"]
```

2019-12-04 22:11 UTC, bluesentinelsec commented
Thanks for the feedback and improvement @cbrnrd !

2019-12-04 22:26 UTC, cbrnrd commented on modules/exploits/linux/local/bash_profile_persistence.rb
> +        'SessionTypes'   => ['meterpreter'],
Yep that would be it. If you can find an alternative way to get the home directory (say by executing a shell command or something else) that should make it work on shell sessions as well.

2019-12-07 00:45 UTC, bluesentinelsec commented on modules/exploits/linux/local/bash_profile_persistence.rb
> +        'SessionTypes'   => ['meterpreter'],
I added support for standard shell sessions.
If the Meterpreter API method fails, the module runs shell commands to pull the user's home directory and host name.

2019-12-10 23:35 UTC, cdelafuente-r7 reviewed
Thanks for your feedback and suggestions @cbrnrd, much appreciated.

Great contribution @bluesentinelsec, thank you! I just have some comments before it lands.

2019-12-10 23:41 UTC, cdelafuente-r7 commented
It would be interesting to have this module more generic and compatible with other OS shell configuration files (e.g. zsh, korn shell, csh, etc.). I don't think this would require a lot of changes. Probably just its name, description and the home directory path expansion logic, as suggested in https://github.com/rapid7/metasploit-framework/pull/12641#discussion_r356230702.

2019-12-12 01:29 UTC, bluesentinelsec commented on modules/exploits/linux/local/bash_profile_persistence.rb
> +      end
Great feedback; your solution is much cleaner.

2019-12-12 01:30 UTC, bluesentinelsec commented on modules/exploits/linux/local/bash_profile_persistence.rb
> +    file_local_write(log_file_name, backup_profile)
Fixed

2019-12-13 21:33 UTC, cdelafuente-r7 commented
Thanks for updating the code.

I just noticed that you've submitted from your `master` branch and we cannot merge it this way (please see https://github.com/rapid7/metasploit-framework/wiki/So-Your-PR-was-closed#your-submitted-a-pr-from-your-master-branch).

Please, can you create a new branch and re-push?
```
git checkout -b <BRANCH_NAME>
git push <your_fork_remote> <BRANCH_NAME>
```

Also, we usually don't want "Merge" commits to appear in the commit history. Please, can you `git rebase -i` and drop all the merge commits?
Another option is to take a clean checkout of master and `git cherry-pick` every commit you want to keep.

2019-12-13 22:50 UTC, cdelafuente-r7 commented
I am closing this PR because it has been submitted from a fork master branch and Github does not let you change the source branch.

@bluesentinelsec, please, re-push and resubmit a new PR when you get a chance. I will approve it and land it. Thanks!

2019-12-13 22:50 UTC, closed without merging

2019-12-15 02:56 UTC, bluesentinelsec commented
@cdelafuente-r7 Thank you for the guidance and patience; I'm still learning how to Git.
I had issues cleaning up my commits with git rebase, so I opted to run a hard reset to make my fork match upstream/master. I apologize if this causes inconvenience.