WIP: Module Documentation
rapid7/metasploit-framework pull request #12661
Opened 2019-12-04 20:32 UTC by kenlacroix

Create Documentation.

2019-12-09 21:30 UTC, kenlacroix commented
@h00die et al, ready for review.

2019-12-10 14:39 UTC, h00die requested changes

2019-12-10 14:39 UTC, h00die commented on documentation/modules/exploit/windows/fileformat/adobe_embedded_pdf.md
> +   3. Do: `use exploit/windows/fileformat/adobe_pdf_embedded_exe`
`git mv documentation/modules/exploit/windows/fileformat/adobe_embedded_pdf.md documentation/modules/exploit/windows/fileformat/adobe_pdf_embedded_exe.md`

2019-12-10 14:39 UTC, h00die commented on documentation/modules/exploit/windows/fileformat/adobe_embedded_pdf.md
> +
Please add the options header for `infilename`, `exename`, `filename`, and `launch_message`

2019-12-10 14:39 UTC, h00die commented on documentation/modules/exploit/windows/fileformat/adobe_geticon.md
> +This module exploits a buffer overflow in Adobe Reader and Adobe Acrobat. Affected versions include < 7.1.1, < 8.1.3, and < 9.1. By creating a specially crafted pdf that a contains malformed Collab.g
wrap Collab.getIcon() in ticks so its `Collab.getIcon()`

2019-12-10 14:39 UTC, h00die commented on documentation/modules/exploit/windows/fileformat/adobe_geticon.md
> +
can you add in the list of targets that were tested: https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/windows/fileformat/adobe_geticon.rb#L50

2019-12-10 14:39 UTC, h00die commented on documentation/modules/exploit/windows/fileformat/adobe_geticon.md
> +
please add options heading with `filename`

2019-12-10 14:39 UTC, h00die commented on documentation/modules/exploit/windows/fileformat/adobe_geticon.md
> +  meterpreter > run post/windows/gather/enum_applications
+1 on this!

2019-12-10 14:39 UTC, h00die commented on documentation/modules/exploit/windows/fileformat/adobe_reader_u3d.md
> +
please add options heading with `filename` and `obfuscate`

2019-12-10 14:39 UTC, h00die commented on documentation/modules/exploit/windows/fileformat/adobe_utilprintf.md
> +
please add options heading with `filename`

2019-12-10 14:39 UTC, h00die commented on documentation/modules/exploit/windows/fileformat/adobe_utilprintf.md
> +   5. Do: `exploit`
since you did this in reverse of the others, the `exploit` command has changed over time and may or may not default to `-j`, so it may be a good idea to just add `-j` on it for safety

2019-12-10 14:39 UTC, h00die commented on documentation/modules/exploit/windows/smb/group_policy_startup.md
> +set FILE_NAME [string]
this can be just FILE_NAME

2019-12-10 14:39 UTC, h00die commented on documentation/modules/exploit/windows/smb/group_policy_startup.md
> +set FOLDER_NAME [string]
remove set, and string

2019-12-10 14:39 UTC, h00die commented on documentation/modules/exploit/windows/smb/group_policy_startup.md
> +set SHARE [string]
remove set, and string

2019-12-10 14:39 UTC, h00die commented on documentation/modules/exploit/windows/smb/group_policy_startup.md
> +set SRVHOST [integer]
this can be removed, id consider it a 'core' function of msf

2019-12-10 14:39 UTC, h00die commented on documentation/modules/exploit/windows/smb/group_policy_startup.md
> +set SRVPORT [integer]
this can be removed, id consider it a 'core' function of msf

2019-12-10 14:39 UTC, h00die commented on documentation/modules/exploit/windows/smb/group_policy_startup.md
> +A run on Windows 7 (x64, Build 7601, SP1) and Server 2016 (x64, Version 1607, OS Build 14393.970) using Group Policy applied from the Domain Controller.
Can you explain this a bit more.  So you are on Kali, you create this SMB share with a VBS, then you set the group policy on the server, and the windows 7 client gets the start up script?
Maybe an ascii art diagram would help here.

```
Kali (smb share w/ vbs payload) <-------------------\
                                                    |
Server 2016 (policy applied to pull vbs payload)    |
 |                                                  |
 |                                                  |
\/                                                  |
Windows 7 ------------------------------------------/
```

or list out the steps:
1. Start this module
2. get access to a computer with a local group policy, or the domain controller withe the domain group policy
3. add to the group policy (where exactly???) to load this as well
4. get shells

2019-12-10 14:39 UTC, h00die commented on documentation/modules/exploit/windows/smb/group_policy_startup.md
> +## Vulnerable Application
this module (not the docs) was written before the aka was invented.
Could you add an AKA for 'badsamba' since that's what they call it?
See https://github.com/rapid7/metasploit-framework/blob/6126a627cc8ea92494aa2ae0d1141ff510f298ac/modules/auxiliary/server/dhclient_bash_env.rb#L47 as an example

2019-12-10 19:39 UTC, kenlacroix commented on documentation/modules/exploit/windows/smb/group_policy_startup.md
> +A run on Windows 7 (x64, Build 7601, SP1) and Server 2016 (x64, Version 1607, OS Build 14393.970) using Group Policy applied from the Domain Controller.
Yeah, so, the module sets up the SMB share and VBScript file for you. I used GP in a very simple domain for the example. The GP is simply applied to the OU computer container. The Win 7 box grabs the payload, in this case the meterpreter reverse_tcp stager on boot, with SYSTEM privs because its executed as a start up script. So, theoretically, any computer in that OU would pop a shell each time it started up. As stated in the docs, you can do local GPO when not on a domain. Your ASCII diagram is right. Also, one could do DNS spoofing of the server hosting the script (thus not needing to create or edit an exisitng GPO), but neither the author or I do did this for the simplicity of the illustration.

2019-12-11 02:26 UTC, kenlacroix commented
Closed PR by accident

2019-12-11 11:47 UTC, h00die commented on modules/exploits/windows/smb/group_policy_startup.rb
>        'DisclosureDate' => 'Jan 26 2015'
need to add a comma at the end here

2019-12-13 22:43 UTC, merged

2019-12-13 22:43 UTC, h00die commented
Thanks for the docs ken!!!

2019-12-13 22:44 UTC, h00die commented
# Release Notes
This PR adds more module docs, mainly for windows fileformat adobe modules.