add PROTOCOL option for sunrpc_portmapper
rapid7/metasploit-framework pull request #12776
Opened 2020-01-02 15:58 UTC by busterb

This changes the sunrpc_portmapper aux module to work like the NIS modules, supporting 'tcp' and 'udp'. It also changes the default proto to 'tcp', since this tends to portforward / route better (and also makes it consistent with the NIS modules).

## Verification

- [ ] Start `msfconsole`
- [ ] `use sunrpc_portmapper`
- [ ] `set RHOSTS 127.0.0.1` or wherever a running portmapper is
- [ ] **Verify** the services are discovered with PROTO = tcp and udp (or just trust me :)

```
 (❁´◡`❁) auxiliary(scanner/misc/sunrpc_portmapper) > run

[+] 127.0.0.1:111         - SunRPC Programs for 127.0.0.1
=============================

 Name     Number  Version  Port  Protocol
 ----     ------  -------  ----  --------
 rpcbind  100000  2        111   tcp
 rpcbind  100000  2        111   udp
 ypbind   100007  2        612   udp
 ypbind   100007  2        686   tcp
 ypserv   100004  2        888   udp
 ypserv   100004  2        888   tcp

[*] 127.0.0.1:111         - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
 (❁´◡`❁) auxiliary(scanner/misc/sunrpc_portmapper) >
```

2020-01-02 16:04 UTC, bcoles commented
Should this be exposed as an option for the `Exploit::Remote::SunRPC` mixin in `lib/msf/core/exploit/sunrpc.rb` instead?

Also, the `Exploit::Remote::SunRPC` mixin only imports `Exploit::Remote::Tcp` - should it also be importing `Exploit::Remote::Udp` ?

2020-01-02 16:29 UTC, wvu-r7 commented
I would have liked the protocol option exposed in the `Msf::Exploit::Remote::SunRPC` mixin while writing the NIS modules. I didn't spend much time refactoring the mixin, only fixing bugs. Now's a good time to update it.

The mixin uses `Rex::Proto::SunRPC::Client`, which uses `Rex::Socket` directly, so I'm not even sure it needs the `Msf::Exploit::Remote::Tcp` mixin.

2020-01-02 16:31 UTC, wvu requested changes

2020-01-02 16:31 UTC, wvu-r7 commented on modules/auxiliary/scanner/misc/sunrpc_portmapper.rb
> +      OptEnum.new('PROTOCOL', [true, 'Protocol to use', 'tcp', %w{tcp udp}]),
I'd use the `%w[]` [syntax](https://github.com/rubocop-hq/ruby-style-guide#percent-literal-braces) here and in the NIS modules. I hadn't changed my style yet.

2020-01-16 20:15 UTC, wvu approved these changes
I'll fix it myself. And we can refactor the mixin later.

2020-01-16 20:23 UTC, merged

2020-01-16 20:23 UTC, wvu-r7 commented
https://github.com/rapid7/metasploit-framework/commit/bb583672bf153e6a9add0a9e833db0d3c118d112

2020-01-16 20:24 UTC, wvu-r7 commented
# Release Notes

This updates the `auxiliary/scanner/misc/sunrpc_portmapper` module with a `PROTOCOL` option to select between TCP or UDP.