Add documentation for auxiliary/scanner/oracle/oracle_login
rapid7/metasploit-framework pull request #12849
Opened 2020-01-17 06:18 UTC by fpr1m3

Adding documentation for auxiliary/scanner/oracle/oracle_login. First PR, so please let me know how I can improve!

2020-01-21 22:31 UTC, h00die requested changes
Pretty good for first time on docs!  A few things to address, but nothing major that will take a long period of time.

2020-01-21 22:31 UTC, h00die commented on documentation/modules/auxiliary/scanner/oracle/oracle_login.md
> +msf auxiliary(scanner/oracle/oracle_login) > run
Do you have an example run w/ successful output you could include here?

2020-01-21 22:31 UTC, h00die commented on documentation/modules/auxiliary/scanner/oracle/oracle_login.md
> +### Version of software and OS as applicable
This should reflect the version you are showing the module work against, not the more generic question/answer

2020-01-21 22:31 UTC, h00die commented on documentation/modules/auxiliary/scanner/oracle/oracle_login.md
> +Module can be used to perform a bruteforce attack on the Oracle server to discover a valid username/password combination.
this line can be removed, it was covered earlier

2020-01-21 22:31 UTC, h00die commented on documentation/modules/auxiliary/scanner/oracle/oracle_login.md
> +Default port for SQL*Net listener is 1521/tcp. If this port is open, try this module to login.
id move up to the vulnerable application heading

2020-01-21 22:31 UTC, h00die commented on documentation/modules/auxiliary/scanner/oracle/oracle_login.md
> +  **VERBOSE**
this item can be removed since its generic to all modules

2020-01-21 22:31 UTC, h00die commented on documentation/modules/auxiliary/scanner/oracle/oracle_login.md
> +  Instance (SID) to authenticate against. Default 'XE'
instead of single quotes wrap in tilda (``)

2020-01-30 19:53 UTC, h00die commented
@fpr1m3 Just wanted to check if you were able to get oracle setup to scan

2020-01-31 23:06 UTC, fpr1m3 commented
@h00die Sorry still working on it! Docker seems to be setup correctly with a password I put in the wordlist, but the scanner isn't returning it as a valid combination. Who knows maybe I'll do another PR to fix that too lol. Sorry for the delay!

2020-02-11 05:29 UTC, fpr1m3 commented
@h00die sorry man but I'm still not able to get this one working, even on our servers at work, so I may take a step back and redo the module and submit documentation when I get it working? Let me know, I'm in uncharted territory lol

2020-02-16 14:13 UTC, h00die commented
I'll see if i have my oracle VMs around, and I can always patch it in and submit it to your PR. I'll take a look in a little while

2020-02-17 01:21 UTC, h00die commented
My VMs aren't loading unfortunately, and the modules we'd previously worked on for oracle were hashdump, not login.  If I have time this week I'll spin up a new VM and get it re-built.

2020-02-18 02:18 UTC, h00die commented
I should have oracle 18c installed by tomorrow (4.4 gig download, yikes! 9gig extracted), and I'll generate some traffic then submit a PR!

2020-02-18 02:43 UTC, fpr1m3 commented
> I should have oracle 18c installed by tomorrow (4.4 gig download, yikes! 9gig extracted), and I'll generate some traffic then submit a PR!

Yeah man these things are way too big! I'm downloading the oracle VM templates, going to give that a whirl tonight as well. Sorry this has turned into quite the job for you, but next con we're at, drinks are on me!

2020-02-19 01:24 UTC, h00die commented
It isn't a big deal!  One of the reasons docs are crucial is it gives us a chance to look over old code to make sure these things are working.

For instance:
` -P0` is now deprecated. as of https://github.com/nmap/nmap/commit/a02a29c28fadf40e6a2229041e31e4d32cb5ab7b which is used 3 times: https://github.com/rapid7/metasploit-framework/search?q=-P0&unscoped_q=-P0

https://github.com/rapid7/metasploit-framework/blob/4c11711a44825d59b2255ead946695e14b06de2d/lib/msf/core/auxiliary/nmap.rb#L136 good ol msf3 reference :)

While I can see oracle is open, I'm having issues getting any creds to work.  I'll try more later.

2020-02-19 17:55 UTC, fpr1m3 commented
That was my issue too. I can connect and login normally just fine, but even having the creds put into the module didn't seem to return a positive result. ☹️

2020-02-19 18:13 UTC, h00die commented
What version did you try? I did 18c, and using the nmap scanner itself didnt do it either (could be an nmap problem)

2020-02-19 18:17 UTC, fpr1m3 commented
I did 19c, then 18c, and then totally didn't try it on the work server running 11g.

2020-02-19 20:12 UTC, h00die commented
https://github.com/nmap/nmap/issues/1475

Looks like its an issue with nmap.
I'm going to leave the rest of my comment below, it was my due diligence research.  With this in mind, I think the best solution would be to add a note that to the docs, and module saying there's a known bug and that it most likely only works with up to 6.5 of nmap.

I'll handle all that while landing this.  Will most likely tackle it in a few hours from now, but no further effort on your part.  Thanks for hanging with this one, it looked easy but turned into a nightmare real quick!









The nmap script hasn't been updated (in a meaningful way) since ~2012. https://github.com/nmap/nmap/commits/a0418c0b892faded3b57a4c301d6d741e3281aeb/scripts/oracle-brute.nse

looks like the commit on march 15 2012: https://github.com/nmap/nmap/commit/692a9cd8bec72a301d1f193e17f7a4673545c0b4#diff-e9ce72aec51013b17f0be82ae4eae124 was the last one to do non-global or inconsequential (spaces, formatting, comments) changes.  

I know the msf module has a patch for 10g.  And based on the 2012 timeframe and [release window](https://en.wikipedia.org/wiki/Oracle_Database#Releases_and_versions), I'm wondering if theres just an incompatibility that this is the first someone is to detect it.

(PS this is why I insist on version numbers and OSes in the docs).  Trying to find references to versions tested, I see:
 - https://subscription.packtpub.com/book/networking_and_servers/9781849517485/5/ch05lvl1sec68/brute-forcing-oracle-passwords was written in 2012, and doesn't list the oracle version.
 - https://pentestlab.blog/2013/03/10/discovering-oracle-accounts-with-nmap/ 2013, doesn't list the oracle version
 - https://yusufanilakduygu.wordpress.com/2016/07/02/oracle-security-checks-with-nmap/ shows 11g (at least we have SOMETHING to go off of)

2020-02-20 03:26 UTC, fpr1m3 commented
Ah man no thanks needed! Wanna get to the point where I can contribute code, but figure this would be a decent way to start out. Luckily this also gave me an awesome amount of information for other documentation PRs I hope to make! Let me know if you want me to pull an older version of nmap, and setup an 11g at least to get some output of it working! :smile:

2020-02-20 10:24 UTC, bcoles commented
Possibly related #11063

2020-02-21 13:59 UTC, merged

2020-02-21 13:59 UTC, h00die commented
A few minor changes/updates: https://github.com/rapid7/metasploit-framework/commit/f451041d4b6fac4b254b8034624d0fc8e5d6d4a3

2020-02-21 14:00 UTC, h00die commented
Thanks for the submission @fpr1m3 , again, thanks for hanging with this to figure out there was an external bug.

2020-02-21 14:00 UTC, h00die commented
# Release Notes
This PR adds module documentation for auxiliary/scanner/oracle/oracle_login