msftidy_docs
rapid7/metasploit-framework pull request #12878
Opened 2020-01-22 22:45 UTC by h00die

This PR adds a new tool: `msftidy_docs.rb`
It acts like `msftidy` but is for docs.
Part of the greater cleanup: #12853 and partially implements https://github.com/rapid7/metasploit-framework/pull/12831#issuecomment-577292896

Right now it checks for the following things:

1. Checks to make sure the doc has a corresponding rb/py/go module
2. checks ## Vulnerable Application is the first line
3. checks to make sure Vulnerable Application, Verification Steps, Scenarios, Options are all present.
4. Checks if Description or Intro/Introduction are present and recommends moving them under Vulnerable Application
5. Checks newline at end of file
6. Checks the H2s mentioned in 3 are in the right order (@tperry-r7 should it be OK to be missing a section, or all all required? Right now i have all required)
7. checks for spaces EOL
8. Checks that there are no H1s
9. Checks line length and suggests cutting it at 140 (arbitrary number I picked, up for debate)

2020-01-22 22:52 UTC, wvu requested changes

2020-01-22 22:52 UTC, wvu-r7 commented on tools/dev/msftidy_docs.rb
> +#!/usr/bin/env ruby
This file should be `+x`.

2020-01-22 22:55 UTC, wvu-r7 commented on tools/dev/msftidy_docs.rb
> +        warn("Line too long (#{ln.length}).  Consider a newline (which resolves to a space in markdown) to break it up around #{l} characters.", idx)
FYI, this doesn't take into account code blocks.

2020-01-22 23:00 UTC, wvu-r7 commented
```
wvu@kharak:/rapid7/metasploit-framework:feature/wordpress$ tools/dev/msftidy_docs.rb documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md
documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md - [WARNING] Missing Section: ## Verification Steps
documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md - [WARNING] Descriptions should be within Vulnerable Application, or an H3 sub-section of Vulnerable Application
documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md - [WARNING] Intro/Introduction should be within Vulnerable Application, or an H3 sub-section of Vulnerable Application
documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md - [WARNING] H2 headings in incorrect order. Should be: Vulnerable Application, Verification Steps, Options, Scenarios
documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md:57 - [WARNING] Line too long (1096). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
wvu@kharak:/rapid7/metasploit-framework:feature/wordpress$
```

https://github.com/rapid7/metasploit-framework/pull/12853#discussion_r369843771

2020-01-22 23:03 UTC, wvu-r7 commented
```
wvu@kharak:/rapid7/metasploit-framework:feature/wordpress$ tools/dev/msftidy_docs.rb documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md
documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md - [WARNING] Missing Section: ## Verification Steps
documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md - [WARNING] Descriptions should be within Vulnerable Application, or an H3 sub-section of Vulnerable Application
documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md - [WARNING] Intro/Introduction should be within Vulnerable Application, or an H3 sub-section of Vulnerable Application
documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md - [WARNING] H2 headings in incorrect order. Should be: Vulnerable Application, Verification Steps, Options, Scenarios
documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md:59 - [WARNING] Line too long (1096). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
wvu@kharak:/rapid7/metasploit-framework:feature/wordpress$ git diff
diff --git a/documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md b/documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md
index 7857c3bfe6..8e3143ffdd 100644
--- a/documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md
+++ b/documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md
@@ -1,5 +1,7 @@
 ## Vulnerable Application

+### Description
+
 This module exploits an authentication bypass in the WordPress
 InfiniteWP Client plugin to log in as an administrator and execute
 arbitrary PHP code by overwriting the file specified by `PLUGIN_FILE`.
wvu@kharak:/rapid7/metasploit-framework:feature/wordpress$
```

2020-01-22 23:05 UTC, wvu-r7 commented on tools/dev/msftidy_docs.rb
> +    unless has_bad_description
Your logic appears to be inverted.

2020-01-22 23:05 UTC, wvu-r7 commented on tools/dev/msftidy_docs.rb
> +    unless has_bad_intro
Your logic appears to be inverted.

2020-01-22 23:06 UTC, wvu-r7 commented on tools/dev/msftidy_docs.rb
> +      warn('H2 headings in incorrect order.  Should be: Vulnerable Application, Verification Steps, Options, Scenarios')
This is not aware of missing sections.

2020-01-22 23:07 UTC, wvu requested changes
At least `chmod +x` and fix the false positives.

2020-01-23 00:20 UTC, h00die commented on tools/dev/msftidy_docs.rb
> +    unless has_bad_description
:) good catch!

2020-01-23 00:23 UTC, h00die commented on tools/dev/msftidy_docs.rb
> +      warn('H2 headings in incorrect order.  Should be: Vulnerable Application, Verification Steps, Options, Scenarios')
correct.  #6 I asked for @tperry-r7  thoughts on if its OK to have a missing section.  I think Options is most likely the only section that is commonly missing, and I'm personally ok with it as most modules don't have an option that's outside of the 'ordinary'.

2020-01-23 00:23 UTC, h00die commented on tools/dev/msftidy_docs.rb
> +      warn('H2 headings in incorrect order.  Should be: Vulnerable Application, Verification Steps, Options, Scenarios')
the other issue is half the comments about things are in PRs the other half in slack,s o also getting lost on where items are getting mentioned or not.

2020-01-23 00:31 UTC, wvu-r7 commented on tools/dev/msftidy_docs.rb
> +      warn('H2 headings in incorrect order.  Should be: Vulnerable Application, Verification Steps, Options, Scenarios')
I took both warnings into account, so I think it's okay for now. I understood what was intended.

2020-01-23 00:32 UTC, wvu approved these changes
Major blockers fixed.

2020-01-23 02:09 UTC, h00die commented
Thanks to @wvu-r7 for some guidance on the long lines in code blocks.  I was thinking some complex regex, he said KISS w/ the flipping Boolean.

2020-01-28 22:36 UTC, h00die commented
Found an edge case where code blocks use 4 space, and space at EOL check was hitting on it.  We need to keep those spaces to ensure its one continuous block.

Also started cleaning up more spaces at EOL and other bugs... docs are a mess, it'll be a long road of cleanup.

2020-01-31 17:33 UTC, tperry-r7 commented
This is great! @h00die !!! Going to merge

2020-01-31 17:59 UTC, merged

2020-01-31 18:29 UTC, tperry-r7 commented
# Release Notes
This PR adds a new tool: <a href="https://github.com/rapid7/metasploit-framework/blob/master/tools/dev/msftidy_docs.rb">msftidy_docs.rb</a>. It acts like <a href="https://github.com/rapid7/metasploit-framework/blob/master/tools/dev/msftidy.rb">msftidy</a> but is for module documentation.
This is part of a larger effort to standardize the module documentation. See <a href="https://github.com/rapid7/metasploit-framework/pull/12831">#12831<a>. Some of the items it checks for are:
<ul>
<li>Checks to make sure the doc has a corresponding rb/py/go module</li>
<li>Checks ## Vulnerable Application is the first line</li>
<li>Checks to make sure Vulnerable Application, Verification Steps, Scenarios, Options are all present.</li>
</ul>

Thanks to <a href="https://github.com/h00die">@h00die</a>!

2020-01-31 18:30 UTC, tperry-r7 commented
@h00die 
> Checks the H2s mentioned in 3 are in the right order (@tperry-r7 should it be OK to be missing a section, or all all required? Right now i have all required)


I think we can leave it to look for all. In the future if it starts complaining too much we can allow for sections to be skipped.

2021-05-02 23:01 UTC, wvu-r7 commented on tools/dev/msftidy_docs.rb
> +      warn('H2 headings in incorrect order.  Should be: Vulnerable Application, Verification Steps, Options, Scenarios')
Fixed in #15140.