Allows `set PAYLOAD` parameters to begin with `\`, `payload\`, & `\payload\`
rapid7/metasploit-framework pull request #12946
Opened 2020-02-18 10:43 UTC by adamgalway-r7

When setting a module `PAYLOAD` value, you are currently unable to set a payload if it's path begins with `\`, `payload\`, & `\payload\`. This is a pain when copy pasting full paths into `set PAYLOAD` commands.

This PR adds a regex statement to catch and remove the above three path beginnings to the `command_dispatcher/core.rb`, allowing the underlying code to retrieve the payload correctly without the user having to change their input.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use crosschex`
- [ ] `set PAYLOAD /payload/windows/x64/vncinject/reverse_winhttps`
- [ ] `set PAYLOAD payload/windows/x64/vncinject/reverse_winhttps`
- [ ] `set PAYLOAD /windows/x64/vncinject/reverse_winhttps`
- [ ] `set PAYLOAD windows/x64/vncinject/reverse_winhttps`
- [ ] Verify all three of the above inputs return `PAYLOAD => windows/x64/vncinject/reverse_winhttps`

2020-02-18 15:27 UTC, wvu-r7 commented
Somewhat related tickets: #7734 and #8882.

2020-02-18 15:29 UTC, wvu requested changes
I don't think `rn-no-release-notes` is warranted here. This is a significant change to core code.

2020-02-18 15:36 UTC, wvu-r7 commented on lib/msf/ui/console/command_dispatcher/core.rb
> +      if value.match(/^(\/?payload\/)|^\//i)
Can we get some consistency with https://github.com/rapid7/metasploit-framework/pull/12946#issuecomment-587517929? There are cases that I would like shared between the two codes.

2020-02-18 15:37 UTC, wvu-r7 commented on lib/msf/ui/console/command_dispatcher/core.rb
> +      if value.match(/^(\/?payload\/)|^\//i)
Also, it may be preferable to [use %r](https://github.com/rubocop-hq/ruby-style-guide#r).

2020-02-18 15:48 UTC, wvu-r7 commented on lib/msf/ui/console/command_dispatcher/core.rb
> +      if value.match(/^(\/?payload\/)|^\//i)
The `start_with?` and `end_with?` checks can probably be ignored, but they were done for extra insurance against bad replacements and negligible performance improvement (this code isn't called during Framework load).

I'm mostly concerned with addressing the common cases consistently. I reverted accommodating typos in #8882, but if you'd like to support that, both implementations should!

2020-02-18 15:52 UTC, wvu requested changes
Perhaps using a single shared code between `cmd_set` and `cmd_use` in [lib/msf/ui/console/command_dispatcher/common.rb](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/ui/console/command_dispatcher/common.rb) is best.

2020-02-18 16:46 UTC, adamgalway-r7 commented on lib/msf/ui/console/command_dispatcher/core.rb
> +      if value.match(/^(\/?payload\/)|^\//i)
Changed code to be more consistent in style with https://github.com/rapid7/metasploit-framework/pull/12946#issuecomment-587517929.

2020-02-18 17:20 UTC, wvu-r7 commented on lib/msf/ui/console/command_dispatcher/core.rb
> +      if value.match(/^(\/?payload\/)|^\//i)
Did you push this change?

2020-02-19 10:17 UTC, adamgalway-r7 commented on lib/msf/ui/console/command_dispatcher/core.rb
> +      if value.match(/^(\/?payload\/)|^\//i)
Sorry, forgot to push it up before I went home for the day :/

2020-02-19 16:00 UTC, wvu-r7 commented on lib/msf/ui/console/command_dispatcher/core.rb
> +      if value.match(/^(\/?payload\/)|^\//i)
No worries!

2020-02-19 16:37 UTC, wvu-r7 commented on lib/msf/ui/console/command_dispatcher/core.rb
> +      if value.start_with?(%r{^(/?payload/)|^/}i)
Can this be simplified to something like [this](https://rubular.com/r/chlwPx6POhj4ci) without alternation? [Original](https://rubular.com/r/RCYVMfCyDM6DNs) for comparison. Non-capturing group is desired if you're not using the match.

2020-02-19 16:42 UTC, wvu-r7 commented
Existing behavior:

```
msf5 > use payload/windows/x64/meterpreter/reverse_tcp
msf5 payload(windows/x64/meterpreter/reverse_tcp) > use /payload/windows/x64/meterpreter/reverse_tcp
[-] No results from search
[-] Failed to load module: /payload/windows/x64/meterpreter/reverse_tcp
msf5 payload(windows/x64/meterpreter/reverse_tcp) > use /windows/x64/meterpreter/reverse_tcp

Matching Modules
================

   #  Name                                              Disclosure Date  Rank    Check  Description
   -  ----                                              ---------------  ----    -----  -----------
   0  payload/windows/x64/meterpreter/reverse_tcp                        normal  No     Windows Meterpreter (Reflective Injection x64), Windows x64 Reverse TCP Stager
   1  payload/windows/x64/meterpreter/reverse_tcp_rc4                    normal  No     Windows Meterpreter (Reflective Injection x64), Reverse TCP Stager (RC4 Stage Encryption, Metasm)
   2  payload/windows/x64/meterpreter/reverse_tcp_uuid                   normal  No     Windows Meterpreter (Reflective Injection x64), Reverse TCP Stager with UUID Support (Windows x64)


msf5 payload(windows/x64/meterpreter/reverse_tcp) >
```

This PR should handle the other two nicely. :-)

2020-02-19 16:51 UTC, wvu-r7 commented on lib/msf/ui/console/command_dispatcher/core.rb
> +      if value.start_with?(%r{^(/?payload/)|^/}i)
```ruby
if value.start_with?('/', 'payload/')
  value.sub!(%r{^/?(?:payload/)?}, '')
end
```

2020-02-19 16:52 UTC, wvu-r7 commented on lib/msf/ui/console/command_dispatcher/core.rb
> +      if value.start_with?(%r{^(/?payload/)|^/}i)
This won't run the `sub!` unless your preconditions are met by the slightly faster `start_with?` string check.

2020-02-19 16:57 UTC, wvu-r7 commented on lib/msf/ui/console/command_dispatcher/core.rb
> +      if value.start_with?(%r{^(/?payload/)|^/}i)
https://medium.com/@Bakku1505/ruby-start-with-end-with-vs-regular-expressions-59728be0859e

2020-02-19 16:59 UTC, wvu-r7 commented on lib/msf/ui/console/command_dispatcher/core.rb
> +      if value.start_with?(%r{^(/?payload/)|^/}i)
Apologies, my comment was directed at this entire block of code, not just this line.

2020-02-19 17:12 UTC, adamgalway-r7 commented on lib/msf/ui/console/command_dispatcher/core.rb
> +      if value.start_with?(%r{^(/?payload/)|^/}i)
Implemented 
```ruby
if value.start_with?('/', 'payload/')
  value.sub!(%r{^/?(?:payload/)?}, '')
end
```
for efficiency & readability sake

2020-02-19 17:18 UTC, wvu approved these changes

2020-02-19 17:23 UTC, wvu-r7 commented on lib/msf/ui/console/command_dispatcher/core.rb
> +      if value.match(/^(\/?payload\/)|^\//i)
Due to the different pathing for payloads, it does not make sense to check for `modules/`, so this looks great.

2020-02-19 17:23 UTC, wvu-r7 commented
```
msf5 exploit(windows/misc/crosschex_device_bof) > set PAYLOAD /payload/windows/x64/vncinject/reverse_winhttps
PAYLOAD => windows/x64/vncinject/reverse_winhttps
msf5 exploit(windows/misc/crosschex_device_bof) > set PAYLOAD payload/windows/x64/vncinject/reverse_winhttps
PAYLOAD => windows/x64/vncinject/reverse_winhttps
msf5 exploit(windows/misc/crosschex_device_bof) > set PAYLOAD /windows/x64/vncinject/reverse_winhttps
PAYLOAD => windows/x64/vncinject/reverse_winhttps
msf5 exploit(windows/misc/crosschex_device_bof) > set PAYLOAD windows/x64/vncinject/reverse_winhttps
PAYLOAD => windows/x64/vncinject/reverse_winhttps
msf5 exploit(windows/misc/crosschex_device_bof) >
```

Excellent enhancement.

2020-02-19 17:25 UTC, wvu-r7 commented
Btw, the verification steps use an x64 payload, which is not supported by the module, but setting it works fine.

2020-02-19 17:28 UTC, wvu-r7 commented
```
msf5 exploit(windows/misc/crosschex_device_bof) > show payloads

Compatible Payloads
===================

   #    Name                                                Disclosure Date  Rank    Check  Description
   -    ----                                                ---------------  ----    -----  -----------
[snip]
   166  windows/vncinject/reverse_winhttp                                    normal  No     VNC Server (Reflective Injection), Windows Reverse HTTP Stager (winhttp)

msf5 exploit(windows/misc/crosschex_device_bof) > set payload 166
payload => windows/vncinject/reverse_winhttp
msf5 exploit(windows/misc/crosschex_device_bof) >
```

Setting the payload by index still works. :+1:

2020-02-19 17:29 UTC, merged

2020-02-19 17:29 UTC, wvu-r7 commented
Thanks for this! Quotes cleaned up in https://github.com/rapid7/metasploit-framework/commit/c5917048fb4fbe2cbda2349578fbd81d5dcf4780.

2020-02-19 17:33 UTC, wvu-r7 commented
# Release Notes

This enhances the `set PAYLOAD` command to strip leading path prefixes from its value, allowing a user to copy and paste certain payload paths into the command.