Backport fixes to various modules committed between Nexus and Liferay PRs
rapid7/metasploit-framework pull request #13259
Opened 2020-04-15 21:00 UTC by wvu-r7

These commits were extracted from #13195 and were added in parallel with #13213.

Modules with significant changes have been retested successfully for a shell. Modules with trivial changes were tested for basic functionality. Don't feel the need to retest everything!

2020-04-16 02:50 UTC, gwillcox-r7 commented
@wvu-r7 Whoo, 24 modified files 😱 Better get to reviewing!

2020-04-16 02:56 UTC, wvu-r7 commented
Hey, it's okay to wait till another day. But I think @adfoster-r7's #13261 will destroy this PR...

2020-04-16 05:50 UTC, gwillcox-r7 requested changes
Think there might have been one or two changes needed. Other than that looks good to go! Sorry for tons of comments, most of them you can just review and mark as approved, they are included for logging purposes to show what my thoughts were when approving in case anyone asks later on.

2020-04-16 05:50 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_srv_parhand_rce.rb
> +      execute_cmdstager(flavor: :curl, nospace: true)
After talking with @wvu-r7 found out that this change makes it so that static strings are symbols, which is more efficient and is kind of what you should be doing given symbols are essentially static strings. Also our API that integrates with Metasploit uses symbols so this could help with better integration which is key for us. Approved.

2020-04-16 05:50 UTC, gwillcox-r7 commented on modules/exploits/linux/upnp/belkin_wemo_upnp_exec.rb
> +        flavor:   :wget,
After talking with @wvu-r7 found out that this change makes it so that static strings are symbols, which is more efficient and is kind of what you should be doing given symbols are essentially static strings. Also our API that integrates with Metasploit uses symbols so this could help with better integration which is key for us. Approved.

2020-04-16 05:50 UTC, gwillcox-r7 commented on modules/exploits/unix/webapp/wp_phpmailer_host_header.rb
> +      'CmdStagerFlavor'     => %i[wget curl]
After talking with @wvu-r7 found out that this change makes it so that static strings are symbols, which is more efficient and is kind of what you should be doing given symbols are essentially static strings. See https://medium.com/@lcriswell/ruby-symbols-vs-strings-248842529fd9 for more info. Also our API that integrates with Metasploit uses symbols so this could help with better integration which is key for us. Approved.

2020-04-16 05:50 UTC, gwillcox-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +      'Description'     => %q{
Alignment fixes, approved.

2020-04-16 05:50 UTC, gwillcox-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +        'SSL'           => true,
Removed default option set elsewhere, approved.

2020-04-16 05:50 UTC, gwillcox-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +      Opt::RPORT(8383),
Relocate default option, approved.

2020-04-16 05:50 UTC, gwillcox-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +      'Platform'        => 'win',
Huh, apparently this is a thing and I was not aware of it at all, but looks good. Approved.

2020-04-16 05:50 UTC, gwillcox-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +      return CheckCode::Unknown('Target did not respond to check request.')
Appreciate the English improvements here, approved!

2020-04-16 05:50 UTC, gwillcox-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +    unless (build = Integer(build) rescue nil)
Good job implementing better checks here and better output lines, appreciated :)

2020-04-16 05:50 UTC, gwillcox-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +    # Desktop Central build 100474 is equivalent to version 10.0.474
Extra comments appreciated, thanks for adding this in and setting the build check to be a bit more readable in the code.

2020-04-16 05:50 UTC, gwillcox-r7 commented on modules/exploits/multi/http/jenkins_metaprogramming.rb
> +        yv66vgAAADMAFQoABQAMCgANAA4HAA8HABAHABEBAAY8aW5pdD4BAAMoKVYBAARDb2RlAQAN
This appears to be realignment of listing to be less compact and to flow across less lines. Approved.

2020-04-16 05:50 UTC, gwillcox-r7 commented on modules/exploits/multi/http/jenkins_metaprogramming.rb
> +=begin javac Metasploit.java
Updates to comments for different classes, looks good, approved.

2020-04-16 05:50 UTC, gwillcox-r7 commented on modules/exploits/multi/http/jenkins_metaprogramming.rb
> +      EOF
Above lines appear to all just be alignment fixes, approved.

2020-04-16 05:54 UTC, wvu-r7 commented on documentation/modules/exploit/linux/http/nexus_repo_manager_el_injection.md
> +create an unprivileged user, that step is omitted for simplicity.
Totally fair and partly why I chose this CVE over the other. I'll make the change, thanks!

2020-04-16 05:57 UTC, wvu-r7 commented on lib/msf/core/exploit/auto_check.rb
> +                "#{checkcode.message} Disable AutoCheck to override.")
Because at some point, it changed, or I was wrong. When I added the period, it ended up being two periods. `checkcode.message` will always end with a period now.

2020-04-16 05:58 UTC, wvu-r7 commented on lib/msf/core/exploit/cmdstager/http.rb
> +    print_status("Client #{client} requested #{request.uri}")
And for historical context, I originally wrote `raw_uri` because I wanted to see exactly what the client was requesting, but that didn't prove to be as useful as what the stager would be seeing.

2020-04-16 06:03 UTC, wvu-r7 commented on modules/exploits/linux/http/axis_srv_parhand_rce.rb
> +      execute_cmdstager(flavor: :curl, nospace: true)
For the record, the `CmdStager` API will allow strings, but it normalizes them to symbols, as it uses symbols internally. I am doing what the API expects.

2020-04-16 06:05 UTC, wvu-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +      'Platform'        => 'win',
Either will work. Specifically, it is `win`, and I use that in other modules. I hate it. I might change it later, haha. But it's consistent now.

2020-04-16 06:05 UTC, wvu-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +      return CheckCode::Unknown('Target did not respond to check request.')
Aligned with newer modules!

2020-04-16 06:07 UTC, gwillcox-r7 commented on lib/msf/core/exploit/auto_check.rb
> +                "#{checkcode.message} Disable AutoCheck to override.")
Ah ok, thanks for clarifying. If this is to remove the case of two periods then feel free to mark this as resolved.

2020-04-16 06:07 UTC, wvu-r7 commented on modules/exploits/multi/http/jenkins_metaprogramming.rb
> +        yv66vgAAADMAFQoABQAMCgANAA4HAA8HABAHABEBAAY8aW5pdD4BAAMoKVYBAARDb2RlAQAN
I think I actually changed the Base64 so the class name would be `Metasploit`. But it works. This module has been tested throughout my committing spree.

2020-04-16 06:16 UTC, wvu-r7 commented on lib/msf/core/exploit/auto_check.rb
> +                "#{checkcode.message} Disable AutoCheck to override.")
Oops, I didn't explain that correctly.

```
[-] Exploit aborted due to failure: unknown: Cannot reliably check exploitability. Target is not responding to check. Disable AutoCheck to override.
```

`checkcode.message` _should_ end with a period to ensure appropriate punctuation. That comes from the module. The hardcoded messages in the library use a period, so I removed the *assumed* punctuation here.

2020-04-16 06:18 UTC, wvu-r7 commented on lib/msf/core/exploit/auto_check.rb
> +                "#{checkcode.message} Disable AutoCheck to override.")
But yes, this removes the assumed and consequently forced punctuation.

2020-04-16 06:29 UTC, wvu-r7 commented on documentation/modules/exploit/windows/http/desktopcentral_deserialization.md
> +### WfsDelay
Yeah, I went back only as far as ManageEngine. I'll want to do a sweep in a follow-up PR.

2020-04-16 06:34 UTC, wvu-r7 commented on lib/msf/core/exploit/expect.rb
> +module Msf::Exploit::Remote::Expect
Yeah, I originally intended for it to be used in all modules, but it'll only ever be used in remote modules. I don't even think the socket methods will apply outside this realm.

2020-04-17 02:45 UTC, gwillcox-r7 approved these changes
Looks good, will merge this in now :)

2020-04-17 03:20 UTC, merged