Rubocop recently landed modules
rapid7/metasploit-framework pull request #13261
Opened 2020-04-16 01:08 UTC by adfoster-r7

Let's run Rubocop on recently landed modules to ensure we're still happy with the output. This is a pre-requisite to enabling Rubocop as part of CI runs.

Command ran:

> rubocop -a modules/auxiliary/scanner/http/limesurvey_zip_traversals.rb  modules/exploits/linux/http/nexus_repo_manager_el_injection.rb  modules/exploits/linux/http/pandora_ping_cmd_exec.rb  modules/exploits/linux/http/vestacp_exec.rb  modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb  modules/exploits/multi/http/liferay_java_unmarshalling.rb  modules/exploits/multi/http/playsms_template_injection.rb  modules/exploits/osx/local/vmware_fusion_lpe.rb  modules/exploits/unix/webapp/thinkphp_rce.rb  modules/exploits/windows/local/cve_2020_0796_smbghost.rb  modules/post/windows/gather/credentials/teamviewer_passwords.rb  modules/post/windows/manage/execute_dotnet_assembly.rb modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.rb modules/exploits/linux/local/exim4_deliver_message_priv_esc.rb modules/exploits/unix/smtp/opensmtpd_mail_from_rce.rb modules/exploits/windows/http/file_sharing_wizard_seh.rb modules/exploits/windows/misc/ais_esel_server_rce.rb modules/exploits/windows/misc/crosschex_device_bof.rb modules/exploits/windows/smb/ms17_010_eternalblue.rb modules/exploits/windows/telnet/goodtech_telnet.rb modules/payloads/singles/windows/pingback_reverse_tcp.rb modules/post/windows/manage/sshkey_persistence.rb

2020-04-16 01:24 UTC, adfoster-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    unless version && (build = begin
This formats weirdly IMO. But I think the side effect in a conditional statement that impacts code later on is a bit of a gotcha, and probably lives in the above line to clearly show the side effect that's being made.

Or alternatively I think this can safely be written as `(build = build.to_i)` due to the above regex matching only 1 or more digits.

2020-04-16 01:35 UTC, wvu-r7 commented
This conflicts with #13259, which contains manual changes.

2020-04-16 01:37 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    unless version && (build = begin
I agree that `to_i` can safely be used here.

2020-04-16 01:38 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    #     Building the Liferay-Portal header:
Since we're not using block comments, the extra indentation here is even more unnecessary.

2020-04-16 01:38 UTC, wvu-r7 commented on modules/exploits/unix/webapp/thinkphp_rce.rb
> +  #   wvu@kharak:~$ curl -vs "http://127.0.0.1:8080/index.php?s=$((RANDOM))" | xmllint --html --xpath 'substring-after(//div[@class = "copyright"]/span[1]/text(), "V")' -
https://github.com/rapid7/metasploit-framework/pull/13261/files#r409230015

2020-04-16 01:39 UTC, wvu-r7 commented on modules/exploits/unix/webapp/thinkphp_rce.rb
> +  #   wvu@kharak:~$ curl -gvs "http://127.0.0.1:8080/index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=system&vars[1][]=id" | head -1
https://github.com/rapid7/metasploit-framework/pull/13261/files#r409230015

2020-04-16 01:39 UTC, wvu-r7 commented on modules/exploits/unix/webapp/thinkphp_rce.rb
> +  #   wvu@kharak:~$ curl -vsd "_method=__construct&filter[]=system&method=get&server[REQUEST_METHOD]=id" http://127.0.0.1:8081/index.php?s=captcha | head -1
https://github.com/rapid7/metasploit-framework/pull/13261/files#r409230015

2020-04-16 01:40 UTC, adfoster-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    #     Building the Liferay-Portal header:
Agreed; I think Rubocop was playing it safe here when automatically fixing this.

2020-04-16 01:42 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    #     Building the Liferay-Portal header:
I'm on the fence about block comments, but they're really useful for pasting in structured information.

2020-04-16 01:49 UTC, adfoster-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    #     Building the Liferay-Portal header:
Also agreed! The docs shed a bit of light on the decision:

- https://rubocop.readthedocs.io/en/stable/cops_style/#styleblockcomments
- https://rubystyle.guide/#no-block-comments

2020-04-16 14:24 UTC, acammack-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    unless version && (build = begin
I don't think so:
```
> nil.to_i
0
```

Which will return `Appears` even when the regex does not match.

2020-04-16 15:35 UTC, adfoster-r7 commented
> This conflicts with #13259, which contains manual changes. I would rather run RuboCop against my modules after that lands.

@wvu-r7 100% happy to do this, let me know which files you'd like reverted :+1: Or I can land this after your module ships :shipit:

2020-04-16 15:51 UTC, gwillcox-r7 requested changes
Overall looks good. A few changes I didn't think were right but majority looks good. Sorry for extra comments, most of them were pointing out examples of where I thought things were going right for reference in case anyone wanted to discuss them more.

2020-04-16 15:51 UTC, gwillcox-r7 commented on modules/exploits/linux/http/vestacp_exec.rb
> +      'Proc' => proc do |cli, req|
Originally wasn't so sure about this, but after testing this module again against its target it seems to be fine and the documentation at https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/Proc explains this change well.

2020-04-16 15:51 UTC, gwillcox-r7 commented on modules/exploits/osx/local/vmware_fusion_lpe.rb
> +    /=> "(?<version>\d{0,2}\.\d{0,2}\.\d{0,2})"/ =~ version_raw # supposed 11.x is also vulnerable, but everyone whos tested shows 11.5.1 or 11.5.2
Good spot on missing space after #

2020-04-16 15:51 UTC, gwillcox-r7 commented on modules/exploits/osx/local/vmware_fusion_lpe.rb
> +        },
Appears that RuboCop also picked up on the fact that `%q()` was being used rather than `%q{}`

2020-04-16 15:51 UTC, gwillcox-r7 commented on modules/post/windows/manage/execute_dotnet_assembly.rb
> +    if (datastore['PPID'] != 0) && !pid_exists(datastore['PPID'])
Nice spot and makes this line simpler :)

2020-04-16 15:51 UTC, gwillcox-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    unless version && (build = begin
Agree that `to_i` fix shown above would be better, this one just looks a bit too weird for me imho.

2020-04-16 15:56 UTC, adfoster-r7 commented on modules/auxiliary/scanner/http/limesurvey_zip_traversals.rb
> +    traversal = '../' * datastore['DEPTH']
The use of ' or " is something developers like to bike shed over at review time. It's worth noting that in Ruby they are semantically different.

Rubocop uses the following approach:

https://rubocop.readthedocs.io/en/latest/cops_style/#stylestringliterals

Full details:

https://rubystyle.guide/#consistent-string-literals

2020-04-16 16:00 UTC, adfoster-r7 commented on modules/auxiliary/scanner/http/limesurvey_zip_traversals.rb
> +
It's requiring an empty line after the above guard clause:

https://rubocop.readthedocs.io/en/latest/cops_layout/#layoutemptylineafterguardclause

2020-04-16 16:04 UTC, adfoster-r7 commented on modules/exploits/linux/http/pandora_ping_cmd_exec.rb
> +  def execute_command(cmd, _opts = {})
The specific rule is [Lint/UnusedMethodArgument](https://rubocop.readthedocs.io/en/latest/cops_lint/#lintunusedmethodargument).

It's a heads up to the Ruby interpreter and Rubocop that the variable is unused, full details:

https://rubystyle.guide/#underscore-unused-vars

2020-04-16 17:00 UTC, adfoster-r7 commented on modules/auxiliary/scanner/http/limesurvey_zip_traversals.rb
> +          This module exploits an authenticated path traversal vulnerability found in LimeSurvey
The alignment of `=>` is using the default configuration of [Layout/HashAlignment](https://rubocop.readthedocs.io/en/latest/cops_layout/#layouthashalignment), which forces the left align of keys, one space before hash rockets and values.

The other approaches to aligning rockets can produce noisey PR diffs when a simple change is made elsewhere to a hash, and all of rockets need to be realigned.

In a similar vein, another example of noisey diffs is alignment of `=` within assignments that you will sometimes see on some PRs:

```diff
-variable_one  = 1
-variable_two  = 2
+variable_one   = 1
+variable_two   = 2
+variable_three = 3
```

One final example of bikeshedding that comes up is the locality of alignment, i.e. I like all of my rockets to be aligned across the entire file, not just a single hash etc. Then the next developer to the file doesn't follow that rule, either intentionally or unintentionally.

All of those types of discussions can be avoided when following a consistent formatting approach 🎉

2020-04-16 18:50 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/limesurvey_zip_traversals.rb
> +
@adfoster-r7  Hmm I have not seen this before but after further review, it makes sense. Marking this as resolved.

2020-04-16 18:54 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/limesurvey_zip_traversals.rb
> +    traversal = '../' * datastore['DEPTH']
Makes sense, its 50/50 on which style but personally I'm in favor of the default behavior here.

2020-04-16 19:15 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    unless version && (build = begin
Yeah, I went back and looked at how I wrote this method, and I was grabbing the version and build, simultaneously validating them with the regex, and THEN checking for `nil` and any potentially invalid integers (despite regex), all while assigning the `build` variable.

My code is getting more dense these days, and I'm getting dumber.

2020-04-16 19:19 UTC, wvu-r7 commented on modules/auxiliary/scanner/http/limesurvey_zip_traversals.rb
> +          This module exploits an authenticated path traversal vulnerability found in LimeSurvey
You can skip whitespace changes in most diff programs. That said, this is one of the best arguments I've heard yet for eschewing _alignism_. I'm 90% with you now.

2020-04-16 20:07 UTC, wvu-r7 commented
@adfoster-r7: I usually try to maintain some level of consistency between my modules, which leads to situations like #13259. We otherwise don't see much backporting of fixes or changes to old modules. It's seen as risky.

If this PR lands, it'll cause a lot of conflicts with the manual work I did in #13259, which I may have to redo. You can either redo the RuboCop run on my modules after the other PR lands, or I can revert your commits to my modules, reapply my changes, and then RuboCop again.

I plan to do a RuboCop sweep on my modules, at least the more recent ones we can test, since this train is going to keep rolling. Maybe it'll give me some release. :)

2020-04-16 20:57 UTC, gwillcox-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    unless version && (build = begin
Woops didn't see @acammack-r7's feedback, before posting mine due to a bug with GitHub not updating whilst I was reviewing. Ignore my comment then.

2020-04-16 21:01 UTC, gwillcox-r7 commented
> @adfoster-r7: I usually try to maintain some level of consistency between my modules, which leads to situations like #13259. We otherwise don't see much backporting of fixes or changes to old modules. It's seen as risky.
> 
> If this PR lands, it'll cause a lot of conflicts with the manual work I did in #13259, which I may have to redo. You can either redo the RuboCop run on my modules after the other PR lands, or I can revert your commits to my modules, reapply my changes, and then RuboCop again.
> 
> I plan to do a RuboCop sweep on my modules, at least the more recent ones we can test, since this train is going to keep rolling. Maybe it'll give me some release. We get more consistency between modules, and I can burn some "foolish consistencies." :)

Personally I vote for landing the other one; we get another PR and exploit out, customers are happier, then can go back retrospectively and fix up stuff like this. That other PR has already got a lot of commits as it is so I'd rather land that before it turns into a larger mess than it already is, then apply RuboCop edits after we have finalized the last few sticking points on this PR.

2020-04-16 21:09 UTC, wvu-r7 commented
I will need to get it after #13253 is ready. Apologies.

2020-04-16 21:14 UTC, wvu-r7 commented on modules/auxiliary/scanner/http/limesurvey_zip_traversals.rb
> +          This module exploits an authenticated path traversal vulnerability found in LimeSurvey
FWIW, GitHub also supports ignoring whitespace changes: https://github.blog/2018-05-01-ignore-white-space-in-code-review/.

2020-04-16 21:14 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/limesurvey_zip_traversals.rb
> +          This module exploits an authenticated path traversal vulnerability found in LimeSurvey
@wvu-r7 Unless you have anything else to contribute I think we are both on board here, so going to mark this as resolved. Feel free to reopen if you feel there is anything else you want to clarify etc.

2020-04-16 21:15 UTC, gwillcox-r7 approved these changes

2020-04-16 21:22 UTC, gwillcox-r7 commented
Will wait for @wvu-r7 to finish his edits, I think he meant to quote #13259, which has one issue left.

2020-04-16 21:23 UTC, wvu-r7 commented
Thanks, corrected. :)

2020-04-17 03:28 UTC, wvu-r7 commented
We are ready for you, @adfoster-r7. #13259 has landed. :)

2020-04-17 05:09 UTC, gwillcox-r7 commented
@adfoster-r7  Once merge conflicts are resolved on your end and you've reuploaded, ping me and I'll get this merged into master.

2020-04-17 11:02 UTC, adfoster-r7 commented
I've rebased + Rubocop'd again :+1:

2020-04-17 14:04 UTC, gwillcox-r7 commented
@adfoster-r7 Thanks, I'll get this merged into master now :)

2020-04-17 14:38 UTC, merged

2020-04-17 15:10 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    #     Building the Liferay-Portal header:
This was not fixed.

2020-04-17 15:10 UTC, wvu-r7 commented on modules/exploits/multi/http/liferay_java_unmarshalling.rb
> +    unless version && (build = begin
I would have rather rewritten this section than included RuboCop's terrible formatting.

2020-04-17 15:14 UTC, wvu-r7 commented on modules/exploits/unix/webapp/thinkphp_rce.rb
> +  #   wvu@kharak:~$ curl -vs "http://127.0.0.1:8080/index.php?s=$((RANDOM))" | xmllint --html --xpath 'substring-after(//div[@class = "copyright"]/span[1]/text(), "V")' -
Not fixed.

2020-04-17 15:14 UTC, wvu-r7 commented on modules/exploits/unix/webapp/thinkphp_rce.rb
> +  #   wvu@kharak:~$ curl -gvs "http://127.0.0.1:8080/index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=system&vars[1][]=id" | head -1
Not fixed.

2020-04-17 15:14 UTC, wvu-r7 commented on modules/exploits/unix/webapp/thinkphp_rce.rb
> +  #   wvu@kharak:~$ curl -vsd "_method=__construct&filter[]=system&method=get&server[REQUEST_METHOD]=id" http://127.0.0.1:8081/index.php?s=captcha | head -1
Not fixed.

2020-04-17 15:26 UTC, wvu-r7 commented
So what was the decision on block comments? Yea or nay?

2020-04-17 15:31 UTC, wvu-r7 commented
I've fixed the outstanding RuboCop mistakes in #13274. Please review and land.

2020-04-17 15:44 UTC, adfoster-r7 commented
@wvu-r7 Let's go with nay for now, and if it ends up being a complete pain - we can revise :+1:

2020-04-17 15:47 UTC, wvu-r7 commented
It's actually less of a pain if RuboCop makes the change, haha. Woohoo, automation.