Shortened URL linking to the msfdb help page
rapid7/metasploit-framework pull request #13390
Opened 2020-05-04 15:05 UTC by adamgalway-r7

Shortens URL link to [msfdb Features and setup guide](https://github.com/rapid7/metasploit-framework/wiki/msfdb:-Database-Features-&-How-to-Set-up-a-Database-for-Metasploit) to make it more copy & paste friendly. 

Link is displayed in an Error message generated when users cannot connect to a database correctly. This error message is usually shown at startup but can also be displayed when running `db_connect`.

2020-05-04 15:33 UTC, jmartin-tech requested changes
I believe there is a project in progress to move the wiki pages into the repository proper.  Obfuscating locations for urls may hinder this usability in the future.

Also I feel that docs linking opens-source info for other segment of this product should not need to be managed outside this project.

2020-05-04 15:47 UTC, adfoster-r7 commented
> I believe there is a project in progress to move the wiki pages into the repository proper. Obfuscating locations for urls may hinder this usability in the future.

@jmartin-r7 That migration effort will have to migrate the existing `r-7.co` URLs:

https://github.com/rapid7/metasploit-framework/search?q=r-7.co&unscoped_q=r-7.co

As that work isn't complete yet, it feels like this PR doesn't need to be blocked by any potential wiki changes as we're not introducing additional complexity to that migration effort. That is to say, as part of the migration effort a plan will need to take in to consideration existing `r-7.co` urls that are referenced both within code and the wiki itself:

```
$ rg r-7.co metasploit-framework.wiki 
metasploit-framework.wiki/Keeping-in-sync-with-rapid7-master.md
3:In this quick HOWTO, we'll be referring to the `rapid7` fork of `metasploit-framework` as `upstream`. It's a pretty common local configuration, advocated by the [development environment setup](http://r-7.co/MSF-DEV). Your fork of `metasploit-framework` will be referred to as `origin`.

metasploit-framework.wiki/Meterpreter-Transport-Control.md
304:+ -- --=[ Free Metasploit Pro trial: http://r-7.co/trymsp ]

metasploit-framework.wiki/Unstable-Modules.md
18:This assumes you're set up for development a la http://r-7.co/MSF-DEV with Rapid7's branch being the "upstream" repo. 

metasploit-framework.wiki/Committer-Rights.md
48:  * [http://r-7.co/MSF-DEV](https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment) is pretty much required reading.

metasploit-framework.wiki/dev/Setting-Up-a-Metasploit-Development-Environment.md
1:<sup>*The shortlink to this wiki page is https://r-7.co/MSF-DEV*</sup>
```

> I feel that docs linking opens-source info for other segment of this product should not need to be managed outside this project.

Sorry, I'm not familiar with all of the Metasploit terminology just yet. What do you mean by segment in this context? This message links to an article about how to set up your local database with `msfdb init`, which is also open source under metasploit framework

2020-05-04 17:01 UTC, jmartin-r7 commented
Links for metasploit-framework project resources should not be hidden behind redirects that can only be managed thru a third party. While R7 happens to be in control of the third party, shortened links should still be considered outside the project and community's sphere of control.

The links in `README.md` & `browser_exploit_server.rb`, I would prefer to see expanded to clearly link to original sources and not be privately controlled shortenings. The others link in lib on two error messages is for a blog post from 2011 which, while static in nature, may be better to documented inside the project.

Looking at other examples in the search, module references are always third party controlled.

This is all simply my view, happy to hear other's thoughts @bcook-r7, @h00die?

@adfoster-r7 as to `segment` that was simply a poor word choice for context, the above may be a more clear statement.

2020-05-04 17:12 UTC, h00die commented
Lets say I, a new contributor, follow guidelines and use an arbitrary 3rd party redirector service (could even be one i made up myself!).
My code is accepted.
I can then (possibly?) change the redirector's destination to something else w/o triggering a PR.
This could also happen if my account is hacked because I used 'monkey' as my password.

There is some degree of trust already that R7 isn't implanting msf w/ malicious code.  Yes its reviewable, but lets be honest on how many people review every line of MSF to ensure it isn't bugged.  Utilizing R7's redirector would follow on that same trust that there isn't something shady.  If the redirector was hacked, hopefully R7's corporate breach disclosure policy would at least kick in, if such exists.

So I'd say either no short-url, or R7.

2020-05-06 12:22 UTC, adfoster-r7 commented
I have no strong opinions here, happy to close this. At the time of requesting the shortened `r-7.co` URL, I assumed this was the convention to follow within Metasploit framework.

If the wiki migration happens in the future, then the URL will have to be changed to `metasploit.com` or something else in the future.

@adamgalway-r7 Happy to close this? :+1:

2020-05-06 14:46 UTC, adamgalway-r7 commented
Closed due to security concerns of shortened URLs.

2020-05-06 14:46 UTC, closed without merging