Fix Python 3 syntax errors
rapid7/metasploit-framework pull request #13477
Opened 2020-05-18 15:03 UTC by sbrun

It fixes small Python 3 syntax errors

2020-05-21 13:47 UTC, acammack-r7 requested changes
Nice catch with the `except` block. The rest of these changes are not needed, though.

2020-05-21 13:47 UTC, acammack-r7 commented on data/exploits/cve-2015-5287/sosreport-rhel7.py
> -print "dump directory: ", dumpdir
This file targets RHEL 7, which ships with Python 2.

2020-05-21 13:47 UTC, acammack-r7 commented on lib/msf/core/modules/external/python/metasploit/cli.py
> -from __future__ import print_function
This line must stay in place to allow us to be 2/3 compatible.

2020-05-21 13:47 UTC, acammack-r7 commented on lib/msf/core/modules/external/python/metasploit/cli.py
> +    for opt, props in list(meta['options'].items()):
This `list` call is not required in a `for ... in` loop.

2020-05-25 07:36 UTC, sbrun commented
I removed the unneeded changes. Thanks!

2020-05-26 17:41 UTC, acammack-r7 approved these changes

2020-05-26 18:09 UTC, merged

2020-05-26 18:11 UTC, acammack-r7 commented
# Release Notes
The `auxiliary/scanner/smb/impacket/wmiexec` external module has had its syntax updated to be Python 3 compatible.

2020-05-26 18:12 UTC, acammack-r7 commented
Thanks for the fix @sbrun!