[GSoC] SQLi library with support to MySQL (and MariaDB)
rapid7/metasploit-framework pull request #13596
Opened 2020-06-11 16:24 UTC by red0xff

# What is it

This pull request adds an SQL injection library to the metasploit framework, to make it easier for module writers to exploit these vulnerabilities, supports the MySQL database management system for now (support for others will be added).

# Features

- Wrappers around the most common queries (version, current user, table names, column names of a given table, data from a table ...)
- Boolean-based and Time-based blind injections
- Support for cases when only a part of the query results is returned (truncated results)
- Encoders that are easy to use (predefined ones, base64 or hex for example), or define (an encoder is a Hash, the encoder part is a string like to_base64(^DATA^), where ^DATA^ will be replaced with the data to encode, and decoder is a Ruby proc, that will decode the data).
 - An option to automatically get strings replaced with hexadecimal constants (to get around character filtering in some cases)

(data is casted to Binary already, to make sure it works on other character sets, substr returns a one-byte character, but sometimes, the encoding on the web application is different, or some unprintable characters are filtered on the output, see the OpenEMR example).

## Test modules

I rewrote two metasploit modules to use the new library, they are working exactly as the original ones, except the changes:
- `auxiliary/sqli/openemr/openemr_sqli_dump.rb` : query result truncated to 31 bytes, can contain non-ascii characters:
  - Table enumeration is now done only in the openemr database only (` where table_schema=database()` added to the condition when enumerating table names), let me know if I should change that.
  - `lang_definitions` table added to `skiptables`, it's a large (>4mb) table that contains the strings in different languages.
  - `base64` encoder is now used (see (1) for the reason)
- `exploits/linux/http/eyesofnetwork_autodiscovery_rce.rb` : time-based SQL injection.
   - No changes

(1) : 
```ruby
sqli.run_sql('select 0x61c3') # no "\xc3" byte returned, only 'a'
sqli.run_sql("select '<abcdefghijklmnopqrstuvwxyz01234'") # &lt; returned for <, and 30 other characters, which means, decoding &lt; is necessary to get 31 characters
```
Results can also include a comma, using base64 (or dealing with these issues is necessary to get correct results).
## Feedback

Any feedback is much appreciated, I am working on implementing a similar interface to `sqlite`, but if there is a feature request, or something should be changed, I'll be more than happy to make changes that can make the library better / more useful for module writers.

2020-06-11 16:52 UTC, h00die commented
I think the wiki would be a good place to add examples of how to use this. However, i'm not sure you have permissions to add a page to the wiki.  Maybe a markdown in a comment or something for the time being?
maybe add an `example_webapp_sqli.rb` would be another good case?

2020-06-11 17:03 UTC, jmartin-r7 commented
I like the idea of a usage guide with walk thru on how an exploit might be developed.  For now adding that as a markdown file in `documentation` in separate branch might give a place to start on that. I can check with the team on where the longer term location for something like that should be.

2020-06-11 21:25 UTC, h00die commented
Other ideas, I think if you include/require *sqli, it should load in advanced options like `sleepdelay` with preset values.  I think this is a more fluid way for users so they can do `set sleepdelay 15`.  This gets it out of being something set by the developer and into the hands of the user to judge for themselves since its hard to predict timing of internal networks vs VPN+far flung servers over the internet.

2020-06-16 17:20 UTC, jmartin-tech requested changes
Thanks for the through refactor.  Still working thru some test runs to validate module changes here.

The calls to `puts` & `print` are a concern.  We had previously discussed that you wanted to use `print_status` and there were issues with access to `datastore['VERBOSE']`, I will test out some options and provide a suggestion on that shortly.

In the mean time please look into code reuse ideas I have suggested in comments.

2020-06-16 17:24 UTC, jmartin-r7 commented on lib/msf/core/exploit/sqli/mysqli.rb
> +require 'msf/core/exploit/sqli/mysqli/time_based_blind'
This applies to multiple files in this PR.

2020-06-16 17:25 UTC, jmartin-r7 commented on lib/msf/core/exploit/sqli/mysqli/time_based_blind.rb
> +  end
Look closely at any method that just calls super in the PR and remove any that will be property inherited from another module or class.

2020-06-16 17:59 UTC, red0xff commented on lib/msf/core/exploit/sqli/mysqli.rb
> +require 'msf/core/exploit/sqli/mysqli/time_based_blind'
The issue with requires at the top of the files is that the class `Msf::Exploit::SQLi::MySQLi` inherits from `Msf::Exploit::SQLi::SQLi`, and with a require at the top of the file `sqli.rb`, it would create the child class before creating the parent, error would happen because it would inherit from a nonexistent class, would need to create all the classes in `boolean_based_blind.rb` required to avoid errors, 
Not sure how it could be possible to refactor, the only way I could think of could think of is creating the parent classes as empty in `boolean_based_blind.rb` and `time_based_blind.rb`.

2020-06-16 20:32 UTC, jmartin-r7 commented on lib/msf/core/exploit/sqli/mysqli.rb
> +require 'msf/core/exploit/sqli/mysqli/time_based_blind'
The inclusion pattern in the `dns` mixin is similar to what I am looking for, the wrapper holds the responsibility for bringing all the requires in to the metasploit module in a usable order. 

Each end class can require any class it extends directly.

Consider restructuring as:
```
sqli
|- common.rb
|- mysqli.rb
\-mysqli
 |- common.rb (current Msf::Exploit::SQLi::MySQLi would shift here and require SQLi::Common)
 |- boolean_based_blind.rb ( may require common.rb )
 |- time_based_blind.rb ( may require common.rb )
```
mysqli.rb would then be:
```
require 'msf/core/exploit/sqli/mysqli/common'
require 'msf/core/exploit/sqli/mysqli/boolean_based_blind'
require 'msf/core/exploit/sqli/mysqli/time_based_blind'
```

Then classes could inherit from `Msf::Exploit::SQLi::MySQLi::Common`

In the current code objects are instantiated as `MySQLi::BooleanBasedBlind.new` and `MySQLi.new`. This would shift `MySQLi.new` => `MySQLi::Common.new`.

This does not completely remove having a `require` at the end of a file, however it is primarily in the wrapping module.

Others with more Ruby specific expertise may have other opinions on this.

2020-06-19 20:55 UTC, jmartin-tech reviewed
Minor adjustments.

2020-06-19 20:55 UTC, jmartin-r7 commented on modules/auxiliary/sqli/openemr/openemr_sqli_dump.rb
> +        'enc' => "1' and updatexml(1,concat(0x7e, (" + payload + ")),0) or '"
```suggestion
        'enc' => "1' and updatexml(1,concat(0x7e, (#{payload})),0) or '"
```

Revert to original format please.

2020-06-19 20:55 UTC, jmartin-r7 commented on lib/msf/core/exploit/sqli.rb
> +    super
This would be where @h00die had suggested registering the `sleepdelay`.

2020-06-19 20:55 UTC, jmartin-r7 commented on lib/msf/core/exploit/sqli/mysqli/common.rb
> +    end
No need to override if just calling `super`.

2020-06-19 20:55 UTC, jmartin-r7 commented on lib/msf/core/exploit/sqli/mysqli/boolean_based_blind.rb
> +  #   @param output_charset [Range] The range of characters to expect in the output, optional
I believe it was mentioned that can optimize calls and speed up execution.  Elaborating on the value here on when used in a module will help others understand when to take advantage of this.

2020-06-19 20:55 UTC, jmartin-r7 commented on lib/msf/core/exploit/sqli/mysqli/boolean_based_blind.rb
> +  def run_sql(query, output_charset = nil)
```suggestion
  def run_sql(query, output_charset: nil)
```

Prefer named optional arguments.

Also note that the `run_sql` has 2 signatures, can that be avoided?
```
def run_sql(query)
```

2020-06-19 21:33 UTC, red0xff commented on lib/msf/core/exploit/sqli.rb
> +    super
@jmartin-r7  I thought about it, it's okay if I register sleepdelay even if SQLi is included for a non time-based injection? I don't see a way to know if the injection is time-based or not just at the time the module is included.

2020-06-19 22:46 UTC, red0xff commented on lib/msf/core/exploit/sqli/mysqli/boolean_based_blind.rb
> +  def run_sql(query, output_charset = nil)
For the different signatures, having output_charset in non-blind injections is useless, they are primarly there to save time and requests, also, run_sql is not the method users should use to dump data from a table, `dump_table_fields` and other high-level enumeration methods are there for that, it's a lower-level method to be used when we need to run custom queries, or we only care about one thing, and want to retrieve it fast (session_id for example in eyesofnetwork).

I could rename it, make it `blind_run_sql`, and make `run_sql` call it with output_charset being `nil`, if that has advantages, please let me know (for me, different signatures with optional additional options are okay).

2020-06-19 23:12 UTC, jmartin-r7 commented on lib/msf/core/exploit/sqli.rb
> +    super
What do you think about making it an `advanced` option?

https://github.com/rapid7/metasploit-framework/blob/76954957c740525cff2db5a60bcf936b4ee06c42/modules/exploits/windows/local/powershell_remoting.rb#L51-L54

@h00die what do you think?

2020-06-23 21:58 UTC, jmartin-r7 commented on modules/exploits/linux/http/eyesofnetwork_autodiscovery_rce.rb
>      sqli_sleep = datastore['SQLI_SLEEP']
This is only used once, consider just passing in `sqli_opts` similar to `VERBOSE` instead of adding the variable here.

2020-06-23 21:58 UTC, jmartin-r7 commented on lib/msf/core/exploit/sqli.rb
> +          OptFloat.new('SQLI_SLEEP', [ false, 'The delay to sleep on time-based blind SQL injections', 1.0 ])
Advanced options are registered with SnakeCase
```suggestion
          OptFloat.new('SqliDelay', [ false, 'The delay to sleep on time-based blind SQL injections', 1.0 ])
```

2020-06-23 21:58 UTC, jmartin-r7 commented on modules/exploits/linux/http/eyesofnetwork_autodiscovery_rce.rb
> +      OptFloat.new('SQLI_SLEEP',  [false, 'SQL Sleep value', 1.0]),
This is already registered by `include Msf::Exploit::SQLi`.

2020-07-10 18:46 UTC, merged

2020-07-10 18:49 UTC, jmartin-r7 commented
## Release Notes
Adds an SQL injection library to the metasploit framework, to make it easier for module writers to exploit these vulnerabilities, supports the MySQL database management system for now.  This initial refactor enhances two existing modules `eyesofnetwork_autodiscovery_rce` & `openemr_sqli_dump` to take advantage of the new library capabilities.

2020-07-25 18:46 UTC, hastalamuerte commented
> 
> 
> I think the wiki would be a good place to add examples of how to use this. However, i'm not sure you have permissions to add a page to the wiki. Maybe a markdown in a comment or something for the time being?
> maybe add an `example_webapp_sqli.rb` would be another good case?
> 
> Edit: oh oh oh!!! Here's what would be cool... use `sqlmap` and show it's output, then how you'd code that into the `example_webapp_sqli`, that way you give a real world example (maybe a hackme type app has multiple sqli types that can be shown).
> 
> This would give an easy roadmap to devs on how to take the most popular sqli tool and use it in msf.

Expirience of sqlmap will be very helpfull! (maybe whole integrating in framework (hope in pro version too) 
Wait wor wiki page of that module.

Thank you Rapid7, your products are best!