New CRC32 Hash API Proposal
rapid7/metasploit-framework pull request #13762
Opened 2020-06-24 18:34 UTC by EgeBalci

Salutations !

I wasn't sure to post this PR because it probably needs lots of work due to subject code is a very core component for shellcodes, and also pros and cons of this enhancement creates a litte dilemma :/  

This PR proposes a new and better alternative for [x86 block_api.asm](https://github.com/rapid7/metasploit-framework/blob/master/external/source/shellcode/windows/x86/src/block/block_api.asm) and [x64 block_api.asm](https://github.com/rapid7/metasploit-framework/blob/master/external/source/shellcode/windows/x64/src/block/block_api.asm) files. By changing the Windows API name hashing method it is possible to trim 1 byte for every x86 Windows shellcode and 4 byte from all x64 Windows shellcode. Because most of the security products are searching for well known ROR13 hashes of Windows API function names, changing the Windows API name hashing method will decreases the detection rate of Metasploit Windows shellcodes. Also new method in this proposal have much less colision rate compared to ROR13. 

![image](https://user-images.githubusercontent.com/17179401/85612965-0e3ab480-b662-11ea-8ac5-94148127e932.png)

## Prior Work & References 
Following DEFCON 25 talk mentions about AV products detecting the metasploit shellcodes by searching for well known ROR13 hashes of Windows API function names.

* https://www.youtube.com/watch?v=jk1VAuPH4-w
* https://github.com/secretsquirrel/fido/blob/master/Defcon_25_2017.pdf 

## New Hashing Method
I have taken advantage of [CRC32](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf#page=327&zoom=100,61,88) instruction for calculating the  CRC32 (polynomial
11EDC6F41H) value of the Windows `[MODULE_NAME+NULL+FUNCTION_NAME]` (same as old block_api.asm). By simply changing the ROR13 hashes with CRC32 values crc32_api.asm will find the desired function address with exact same way that old `block_api.asm` uses. No additional registers are changed. I have tested both of the crc32_api.asm for all existing Windows shellcode inside Metasploit and it works without any error. [crc32_hash.py](https://github.com/EgeBalci/metasploit-framework/blob/crc32_api/external/source/shellcode/windows/x86/src/crc32_hash.py) file can be used to calculate a CRC32 value of given input same as [hash.py](https://github.com/rapid7/metasploit-framework/blob/master/external/source/shellcode/windows/x86/src/hash.py).

## BUT ! Here's the catch.
`CRC32` instruction is a fairly new instruction. It is added with [SSE4](https://en.wikipedia.org/wiki/SSE4) so it may cause problems in older CPUs. Any model manufactured after 2006 seems to be working fine but I don't know what happens when you run a unsupported instruction on a old CPU, simply couldn't find old enough hardware for testing ¯\_(ツ)_/¯

2020-06-24 18:34 UTC, owarz commented
yeeey...

2020-06-24 18:34 UTC, Aporlorxl23 commented
Hello Metasploit <3

2020-06-24 18:35 UTC, antlionguard commented
That's it!

2020-06-24 18:35 UTC, JrSamuray commented
Ccc MDIİSEC CcC

2020-06-24 18:36 UTC, omrfrkklk commented
Congratulations

2020-06-24 18:36 UTC, ahmetmertugrul commented
fifiuv fifiuv fifiuv

2020-06-25 14:33 UTC, acammack-r7 requested changes
Looks nifty! This Python tool will need Python 3 compatibility before it can be landed.

2020-06-25 14:33 UTC, acammack-r7 commented on external/source/shellcode/windows/x86/src/crc32_hash.py
> +#!/usr/bin/env python2.7
This looks good, but it will need to be compatible with Python 3 since it is a local tool.

2020-06-25 14:33 UTC, acammack-r7 commented on external/source/shellcode/windows/x86/src/crc32_hash.py
> +import os, time, sys, crcmod
```suggestion
import time, sys, crcmod
```

2020-06-25 14:38 UTC, acammack-r7 commented
I think this would be a nice option to have for our Windows payloads. Besides converting the `external/source/shellcode/windows` payloads to use the new block API (or making new variants that do), we will also need the CRC32 API ported to [our Ruby hash calculation method](https://github.com/rapid7/rex-text/blob/master/lib/rex/text/block_api.rb) and our [x86](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/payload/windows/block_api.rb) and [x64](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/payload/windows/x64/block_api.rb) inline assembly bits.

2020-06-25 15:59 UTC, EgeBalci commented
Looking for a way to properly calculate CRC32 (polynomial
11EDC6F41H) in ruby any help is appreciated :)  Other bits are done.

2020-07-09 22:26 UTC, zeroSteiner commented
If the intention here is to remove the ROR13 hashes of the API methods, then we should be able to obfuscate them relatively easily with an XOR key at generation time and then add an XOR instruction towards the top of the block API to recover the original value. This would retain the older compatibility by avoiding an SSE4 instruction while also not simply swapping one hash for another that would be easily matched by a signature.

2020-07-13 04:55 UTC, EgeBalci commented
> If the intention here is to remove the ROR13 hashes of the API methods, then we should be able to obfuscate them relatively easily with an XOR key at generation time and then add an XOR instruction towards the top of the block API to recover the original value. This would retain the older compatibility by avoiding an SSE4 instruction while also not simply swapping one hash for another that would be easily matched by a signature.

We can also randomize the CRC checksum by changing initial the `EDI` register value (seed) on each payload generation. But i totally get your concerns about the SSE4 instructions.

2020-07-13 21:54 UTC, zeroSteiner commented
Well if the hashes can be randomized using either the CRC or ROR13 checksum methods, then I just don't know if the loss of compatibility out weighs the benefits of slightly smaller sizes and theoretically lower collision rates.

Metasploit has actually been working on making it harder to write signatures for the static Block API as part of the upcoming v6 work. We recently made changes in PR #13832 that randomizes the whole stub each time it's generated. If the ROR13 hashes were being matched though, that will continue to be the case since only the body of the Block API was updated with randomizations. I'm wondering if you would mind closing this and migrating the proposal to a feature request to remove the Block API hashes since it would likely need to target the v6 version anyways and be compatible with the changes I mentioned?

2020-07-14 20:29 UTC, closed without merging