Add checks to msftidy_docs and update the template for them
rapid7/metasploit-framework pull request #13896
Opened 2020-07-24 00:56 UTC by zeroSteiner

This adds a few additional checks to the `msftidy_docs` utility and updates the docs template to be compliant with them.

Changes include:
1. Prefer single backquotes for one line literals instead of triple backquotes
1. Dedent triple backquote blocks, because indenting them causes their content to also be indented in the rendered output
1. Use markdowns automatic numbering for numeric lists, this makes updating the template easier
1. Remove trailing whitespace when checking the line length.
    * If the user wrote exactly 140 characters followed by a new line, that should be permitted as 140 characters. This basically allows them to use a guide line that alot of editors support like RubyMine, Geany and Atom.

## Verification

- [ ] Run msftidy on the docs template, see only errors for content that needs to be changed
- [ ] Make a new doc from the docs template, using the automatic numbering, and single back quotes for single line literals
- [ ] Load metasploit and generate the docs using `info -d` and see that they render cleanly

## Examples 

Tidy On Old Template:
```
documentation/modules/module_doc_template.md - [ERROR] Doc missing module. Check file name and path(s) are correct. Doc: documentation/modules/module_doc_template.md
documentation/modules/module_doc_template.md - [WARNING] Docs should start with ## Vulnerable Application
documentation/modules/module_doc_template.md - [WARNING] Scenario sub-sections should include the vulnerable application version and OS tested on in an H3, not just ### Version and OS
documentation/modules/module_doc_template.md:12 - [WARNING] Instructional text not removed
documentation/modules/module_doc_template.md:16 - [WARNING] Should use single backquotes (`) for single line literals instead of triple backquotes (```)
documentation/modules/module_doc_template.md:17 - [WARNING] Should use single backquotes (`) for single line literals instead of triple backquotes (```)
documentation/modules/module_doc_template.md:33 - [WARNING] Code blocks using triple backquotes (```) should not be indented
documentation/modules/module_doc_template.md:35 - [WARNING] Code blocks using triple backquotes (```) should not be indented
documentation/modules/module_doc_template.md:41 - [WARNING] Code blocks using triple backquotes (```) should not be indented
documentation/modules/module_doc_template.md:45 - [WARNING] Code blocks using triple backquotes (```) should not be indented
```

Tidy On New Template:
```
documentation/modules/module_doc_template.md - [ERROR] Doc missing module. Check file name and path(s) are correct. Doc: documentation/modules/module_doc_template.md
documentation/modules/module_doc_template.md - [WARNING] Docs should start with ## Vulnerable Application
documentation/modules/module_doc_template.md - [WARNING] Scenario sub-sections should include the vulnerable application version and OS tested on in an H3, not just ### Version and OS
documentation/modules/module_doc_template.md:12 - [WARNING] Instructional text not removed
```

*The remaining warnings are for sections that need to be filled in.*

2020-07-26 18:52 UTC, h00die commented
maybe it's time to start looking back at #9506 ?

2020-07-26 21:47 UTC, zeroSteiner commented
That looks like an alternative workflow for generating docs while this is more of an augmentation for the existing workflow. The msftidy changes I introduce here would still be applicable regardless of if the module doc is hand written from a template or generated from a script and then edited. The overview details would still be relevant unless that gets moved to manual generation which I don't think would be a good idea.

2020-07-27 16:09 UTC, h00die commented
Compared to the module doc template, the ERB:
1. gives the first header as the module title, instead of `## Vulnerable Application`
2. Includes the module name (seems extraneous since you did `info -d` to get here)
3. includes authors (seems extraneous to me)
4. Includes Platforms (I'm not sure ive ever used this information tbh)
5. Includes Module Ranking (I like having this, however @tperry-r7 's format suggestions were H3 https://github.com/rapid7/metasploit-framework/blame/master/documentation/modules/module_doc_template.md#L23)
6. Includes Module Traits (pull requests/references/available targets, none of which are in the doc template).  I like the references personally since they're links... but maybe `target=new` on them? Also, things like OSVDB (using ms01_026) links to nothing, maybe we can avoid that.
7. The Basic Usage section always bothered me.  I understand it's hard to make something automated, but its a lie as nothing ever works that way.  We know the required options, couldn't we add a "set <required option> fill_me_in".  I think this actually maps decently to verification steps (https://github.com/rapid7/metasploit-framework/blame/master/documentation/modules/module_doc_template.md#L11), maybe it should be converted?
8. Says "Required Options" instead of just "Options"

I think now would be a good time to more cleanly sync this all up.

2020-07-28 11:13 UTC, h00die commented
After much discussion with @zeroSteiner over `em-dash` being the correct usage, but ugly (very long), a switch to colons was decided on.

Also, many of the other docs in https://github.com/rapid7/metasploit-framework/tree/master/data/markdown_doc should have a look over.  An additional later PR will tackle that.

2020-07-28 11:24 UTC, h00die requested changes

2020-07-28 11:24 UTC, h00die commented on data/markdown_doc/default_template.erb
> +
add link to https://github.com/rapid7/metasploit-framework/wiki/Definition-of-Module-Reliability,-Side-Effects,-and-Stability for consistency with the one to exploit rank

2020-07-28 11:24 UTC, h00die commented on data/markdown_doc/default_template.erb
> +* **<%= side_effect %>** &mdash; <%= description %>
convert to :

2020-07-28 11:24 UTC, h00die commented on data/markdown_doc/default_template.erb
> +* **<%= reliability %>** &mdash; <%= description %>
convert to :

2020-07-28 11:24 UTC, h00die commented on data/markdown_doc/default_template.erb
> +* **<%= name %>** &mdash; <%= props.desc %>
convert to :

2020-07-28 11:24 UTC, h00die commented on data/markdown_doc/default_template.erb
> +* **<%= stability %>** &mdash; <%= description %>
convert to :

2020-07-28 19:41 UTC, merged

2020-07-28 19:44 UTC, h00die commented
# Release Notes
This PR adds a few updates to the `msftidy_docs` script, as well as expand on the ERB template which generates the Overview tab to include additional data points.