Add exploit for Rockwell FactoryTalk View SE (Pwn2Own Miami 2020)
rapid7/metasploit-framework pull request #13960
Opened 2020-08-07 15:32 UTC by pedrib

This adds an exploit for Rockwell FactoryTalk View SE 2020. 
The module chains 5 vulnerabilities to drop a file in the IIS server directory, resulting in command execution as SYSTEM.
CVE-2020-12027/8/9 have been attributed to these vulns.

Most likely you don't have access to this software - if that's the case, let us know and we will add a pcap here.

cc @rdomanski

2020-08-07 15:55 UTC, bcoles commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +    end
Would this also work with `WfsDelay` ("wait for shell delay") ? In theory, it should be effectively the same. That is, wait x number of seconds for a shell before giving up.

`WfsDelay` is user configurable, and can be defined in the module `info` Hash.

```ruby
'DefaultOptions'   => { 'WfsDelay' => 30 }
```

If so, that would remove the requirement for the `on_new_session` method and associated `@shell_recv` temporary state variable and `SLEEP_SHELL` option.

2020-08-07 15:57 UTC, pedrib commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +    end
I think we tried that, but good point - I'll double check and get back to you

2020-08-07 19:28 UTC, smcintyre-r7 requested changes
Just left a few minor comments things look great overall. After you've addressed the feedback and written the docs can you please send the PCap to the team? Feel free to CC me specifically (smcintyre@metasploit.com) and I can review it. Also if you wouldn't mind please include the console output in addition to the PCap.

2020-08-07 19:28 UTC, smcintyre-r7 commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +            [ 'URL', 'RADEK_BLOG'],
Are these place holders, because they're not URLs.

2020-08-07 19:28 UTC, smcintyre-r7 commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +          The attack relies on the chaining of five separate vulnerabilities. The first vulnerability is an unauthenticated project copy request,
> The attack relies on the chaining of five separate vulnerabilities.

Most impressive 🥇

2020-08-07 19:28 UTC, smcintyre-r7 commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +    fail_with(Failure::Unknown, 'Failed to obtain project list. Bailing') unless res && res.code == 200
This should probably be `Failure::UnexpectedReply` not `Failure::Unknown`.

2020-08-07 19:28 UTC, smcintyre-r7 commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +    print_good("#{peer} - Got a path to drop our shell: #{shell_path}")
Does this path need to be cleaned up on a new session?

2020-08-07 19:28 UTC, smcintyre-r7 commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +          'Pedro Ribeiro <pedrib[at]gmail.com>',         # Vulnerability discovery and Metasploit module
The spacing here is the only rubocop offense, would you mind changing it to the following please?

```suggestion
          'Pedro Ribeiro <pedrib[at]gmail.com>', # Vulnerability discovery and Metasploit module
```

2020-08-08 08:56 UTC, pedrib commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +    end
Confirmed, works with WfsDelay, thanks for spotting it!

2020-08-08 08:58 UTC, pedrib commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +            [ 'URL', 'RADEK_BLOG'],
Correct, give us a couple of days and we'll have the URL there

2020-08-08 08:58 UTC, pedrib commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +    print_good("#{peer} - Got a path to drop our shell: #{shell_path}")
Nope, the file gets automatically deleted due to the race condition!

2020-08-08 08:58 UTC, pedrib commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +          'Pedro Ribeiro <pedrib[at]gmail.com>',         # Vulnerability discovery and Metasploit module
done

2020-08-08 09:06 UTC, pedrib commented
@smcintyre-r7 I have sent the pcap and console output to you.

BTW - I just noticed I am pushing from my main branch. This is actually the first time I am doing this, I usually create a new branch, drop the modules there, then send a PR. Is this going to be a problem? Any ill side effects? (I'm a git noob)

2020-08-09 15:12 UTC, ccondon-r7 commented
General comment—thanks for all the great PRs you've been putting up, @pedrib. You're definitely in our top few contributors for really high-value exploits. We appreciate you!

2020-08-09 15:22 UTC, pedrib commented
@ccondon-r7 thanks for the kind words, much appreciated! It's my pleasure and always awesome to work with you all. 

Shame I didn't get to meet the team in the previous Metasploit meetups during BH / Defcon, I was actually planning to go to Vegas this year... let's do it in 2021 then, hope you'll have another meetup.

2020-08-09 18:48 UTC, ccondon-r7 commented
@pedrib Sold!

2020-08-11 19:47 UTC, smcintyre-r7 commented
> BTW - I just noticed I am pushing from my main branch. This is actually the first time I am doing this, I usually create a new branch, drop the modules there, then send a PR. Is this going to be a problem? Any ill side effects? (I'm a git noob)

Yeah I missed that as well. The bots response includes the steps to get the changes switched over. If you have any trouble with it just let me know.

You may be able to "edit" this PR and set the source branch to your new one instead of opening a new PR.

2020-08-11 19:51 UTC, smcintyre-r7 commented
Nevermind, I just tested it out with a PR of my own and you can't edit the source branch of a PR in GitHub once it's been opened so this will have it be closed and resubmitted. I'm really sorry for the trouble.

2020-08-11 19:51 UTC, closed without merging

2020-08-13 09:13 UTC, pedrib commented
@smcintyre-r7 will do, but I'm swamped atm, give me a couple of days and I'll get on this!