Fixes for bug #13956
rapid7/metasploit-framework pull request #13975
Opened 2020-08-10 15:38 UTC by digininja

Fixing bug #13956

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use auxiliary/gather/enum_dns.rb`
- [ ] `set DOMAIN github.com`
- [ ] `run`
- [ ] Check that it completes successfully
- [ ] Check against zonetransfer.me to ensure it still returns AXFR records and against digi.ninja which should return without any errors

I've left in the original rescue and added a second which duplicates it. It feels a bit wrong doing it, but the ones in there were picked for a reason so I figured that the error on those can be made more specific, or my new one more generic, if needs be. It feels wrong to duplicate code but a nagging bit says to leave it there, happy to remove it though.

I've also added a rescue in the module as that is where I fixed it first before going into the library so left it in just for extra protection.

2020-08-10 15:46 UTC, bcoles commented
> I've left in the original rescue and added a second which duplicates it.

Perhaps `::Errno::ECONNRESET` should also be added to the initial `rescue` ? This is the exception that is causing the encountered error messages. It also "fits" with the other exceptions being rescued (connection failure, timeout, etc).

2020-08-10 16:18 UTC, digininja commented
Ok, I'll do that. I'll leave the general exception in as well, just in case.

On Mon, 10 Aug 2020, 16:46 bcoles, <notifications@github.com> wrote:

> I've left in the original rescue and added a second which duplicates it.
>
> Perhaps ::Errno::ECONNRESET should also be added to the initial rescue ?
> This is the exception that is causing the encountered error messages. It
> also "fits" with the other exceptions being rescued (connection failure,
> timeout, etc).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rapid7/metasploit-framework/pull/13975#issuecomment-671434495>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA4SWPLLSPFWNVAN566L23SAAI55ANCNFSM4P2CWZSQ>
> .
>

2020-08-11 16:13 UTC, gwillcox-r7 requested changes
Code changes look good, just one issue on the text your using for one of the output lines which is a little odd to me. Otherwise should be good to merge if it passes tests.

2020-08-11 16:13 UTC, gwillcox-r7 commented on lib/msf/core/exploit/dns/enumeration.rb
> +        print_error("Query #{domain} DNS AXFR - exception: #{e}")
Considering this is essentially this output is the same as the line above, would it not make sense to reword this line a bit? Otherwise we could just replace the two lines above with these two lines here and there wouldn't be any difference.

2020-08-11 16:31 UTC, gwillcox-r7 commented
Did a quick update on this PR description to remove the `.rb` at the end of the module you were loading.

Also here is the output from my runs which seems to suggest this issue is now fixed.

Running with `github.com`:
```
msf6 > use auxiliary/gather/enum_dns
msf6 auxiliary(gather/enum_dns) > set DOMAIN github.com
DOMAIN => github.com
msf6 auxiliary(gather/enum_dns) > run

[!] dns wildcard is enable OR fake dns server
[*] Querying DNS NS records for github.com
[+] github.com NS: dns1.p08.nsone.net
[+] github.com NS: dns2.p08.nsone.net
[+] github.com NS: dns3.p08.nsone.net
[+] github.com NS: dns4.p08.nsone.net
[+] github.com NS: ns-1283.awsdns-32.org
[+] github.com NS: ns-1707.awsdns-21.co.uk
[+] github.com NS: ns-421.awsdns-52.com
[+] github.com NS: ns-520.awsdns-01.net
[*] Attempting DNS AXFR for github.com from dns1.p08.nsone.net
[*] Attempting DNS AXFR for github.com from dns2.p08.nsone.net
[*] Attempting DNS AXFR for github.com from dns3.p08.nsone.net
[*] Attempting DNS AXFR for github.com from dns4.p08.nsone.net
[*] Attempting DNS AXFR for github.com from ns-1283.awsdns-32.org
[-] Query github.com DNS AXFR - exception: NoResponseError
[*] Attempting DNS AXFR for github.com from ns-1707.awsdns-21.co.uk
[-] Query github.com DNS AXFR - exception: NoResponseError
[*] Attempting DNS AXFR for github.com from ns-421.awsdns-52.com
[-] Query github.com DNS AXFR - exception: NoResponseError
[*] Attempting DNS AXFR for github.com from ns-520.awsdns-01.net
[-] Query github.com DNS AXFR - exception: NoResponseError
[*] Querying DNS CNAME records for github.com
[*] Querying DNS NS records for github.com
[+] github.com NS: dns1.p08.nsone.net
[+] github.com NS: dns2.p08.nsone.net
[+] github.com NS: dns3.p08.nsone.net
[+] github.com NS: dns4.p08.nsone.net
[+] github.com NS: ns-1283.awsdns-32.org
[+] github.com NS: ns-1707.awsdns-21.co.uk
[+] github.com NS: ns-421.awsdns-52.com
[+] github.com NS: ns-520.awsdns-01.net
[*] Querying DNS MX records for github.com
[+] github.com MX: aspmx.l.google.com
[+] github.com MX: alt3.aspmx.l.google.com
[+] github.com MX: alt4.aspmx.l.google.com
[+] github.com MX: alt1.aspmx.l.google.com
[+] github.com MX: alt2.aspmx.l.google.com
[*] Querying DNS SOA records for github.com
[+] github.com SOA: ns-1707.awsdns-21.co.uk
[*] Querying DNS TXT records for github.com
[+] github.com TXT: MS=6BF03E6AF5CB689E315FB6199603BABF2C88D805
[+] github.com TXT: MS=ms44452932
[+] github.com TXT: MS=ms58704441
[+] github.com TXT: docusign=087098e3-3d46-47b7-9b4e-8a23028154cd
[+] github.com TXT: v=spf1 ip4:192.30.252.0/22 ip4:208.74.204.0/22 ip4:46.19.168.0/23 include:_spf.google.com include:esp.github.com include:_spf.createsend.com include:servers.mcsv.net ~all
[*] Querying DNS SRV records for github.com
[*] Auxiliary module execution completed
msf6 auxiliary(gather/enum_dns) >
```

Running with `zonetransfer.me` (seems to still return some warnings, but otherwise working fine):

```
msf6 auxiliary(gather/enum_dns) > set DOMAIN zonetransfer.me
DOMAIN => zonetransfer.me
msf6 auxiliary(gather/enum_dns) > run

[*] Querying DNS NS records for zonetransfer.me
[+] zonetransfer.me NS: nsztm1.digi.ninja
[+] zonetransfer.me NS: nsztm2.digi.ninja
[*] Attempting DNS AXFR for zonetransfer.me from nsztm1.digi.ninja
W, [2020-08-11T11:27:43.867111 #3681]  WARN -- : Failed to parse RR packet from offset: 601
W, [2020-08-11T11:27:43.868904 #3681]  WARN -- : Failed to parse RR packet from offset: 670
W, [2020-08-11T11:27:43.872097 #3681]  WARN -- : Failed to parse RR packet from offset: 962
W, [2020-08-11T11:27:43.873599 #3681]  WARN -- : Failed to parse RR packet from offset: 1017
W, [2020-08-11T11:27:43.877793 #3681]  WARN -- : Failed to parse RR packet from offset: 1533
W, [2020-08-11T11:27:43.878991 #3681]  WARN -- : Failed to parse RR packet from offset: 1598

W, [2020-08-11T11:28:14.118271 #3681]  WARN -- : Failed to parse RR packet from offset: 601
W, [2020-08-11T11:28:14.119689 #3681]  WARN -- : Failed to parse RR packet from offset: 670
W, [2020-08-11T11:28:14.120369 #3681]  WARN -- : Failed to parse RR packet from offset: 962
W, [2020-08-11T11:28:14.120761 #3681]  WARN -- : Failed to parse RR packet from offset: 1017
W, [2020-08-11T11:28:14.122118 #3681]  WARN -- : Failed to parse RR packet from offset: 1533
W, [2020-08-11T11:28:14.122449 #3681]  WARN -- : Failed to parse RR packet from offset: 1598
[+] zonetransfer.me Zone Transfer: [;; Answer received from 81.4.108.41:53 (1983 bytes)
;;
;; HEADER SECTION
;; id = 10415
;; qr = 1       opCode: QUERY   aa = 1  tc = 0  rd = 0
;; ra = 0       ad = 0  cd = 0  rcode = NoError
;; qdCount = 1  anCount = 50    nsCount = 0     arCount = 0

;; QUESTION SECTION (1 record):
;; zonetransfer.me.             IN      AXFR

;; ANSWER SECTION (50 records):
zonetransfer.me.        7200    IN      SOA     nsztm1.digi.ninja. robin.digi.ninja. 2019100801 172800 900 1209600 3600
zonetransfer.me.        300     IN      HINFO   Casio fx-700G
 Windows XP�
zonetransfer.me.        301     IN      TXT
zonetransfer.me.        7200    IN      MX      0 ASPMX.L.GOOGLE.COM.
zonetransfer.me.        7200    IN      MX      10 ALT1.ASPMX.L.GOOGLE.COM.
zonetransfer.me.        7200    IN      MX      10 ALT2.ASPMX.L.GOOGLE.COM.
zonetransfer.me.        7200    IN      MX      20 ASPMX2.GOOGLEMAIL.COM.
zonetransfer.me.        7200    IN      MX      20 ASPMX3.GOOGLEMAIL.COM.
zonetransfer.me.        7200    IN      MX      20 ASPMX4.GOOGLEMAIL.COM.
zonetransfer.me.        7200    IN      MX      20 ASPMX5.GOOGLEMAIL.COM.
zonetransfer.me.        7200    IN      A       5.196.105.14
zonetransfer.me.        7200    IN      NS      nsztm1.digi.ninja.
zonetransfer.me.        7200    IN      NS      nsztm2.digi.ninja.
_acme-challenge.zonetransfer.me.   301   IN   TXT
_sip._tcp.zonetransfer.me.   14000   IN   SRV
14.105.196.5.IN-ADDR.ARPA.zonetransfer.me.   7200   IN   PTR   www.zonetransfer.me.
asfdbbox.zonetransfer.me.   7200   IN   A   127.0.0.1
canberra-office.zonetransfer.me.   7200   IN   A   202.14.81.230
cmdexec.zonetransfer.me.   300   IN   TXT
contact.zonetransfer.me.   2592000   IN   TXT
dc-office.zonetransfer.me.   7200   IN   A   143.228.181.132
deadbeef.zonetransfer.me.   7201   IN   AAAA   dead:beaf::
DZC.zonetransfer.me.    7200    IN      TXT
email.zonetransfer.me.  7200    IN      A       74.125.206.26
Hello.zonetransfer.me.  7200    IN      TXT
home.zonetransfer.me.   7200    IN      A       127.0.0.1
Info.zonetransfer.me.   7200    IN      TXT
internal.zonetransfer.me.   300   IN   NS   intns1.zonetransfer.me.
internal.zonetransfer.me.   300   IN   NS   intns2.zonetransfer.me.
intns1.zonetransfer.me. 300     IN      A       81.4.108.41
intns2.zonetransfer.me. 300     IN      A       167.88.42.94
office.zonetransfer.me. 7200    IN      A       4.23.39.254
ipv6actnow.org.zonetransfer.me.   7200   IN   AAAA   2001:67c:2e8:11::c100:1332
owa.zonetransfer.me.    7200    IN      A       207.46.197.32
robinwood.zonetransfer.me.   302   IN   TXT
sqli.zonetransfer.me.   300     IN      TXT
sshock.zonetransfer.me. 7200    IN      TXT
staging.zonetransfer.me.   7200   IN   CNAME   www.sydneyoperahouse.com.
alltcpportsopen.firewall.test.zonetransfer.me.   301   IN   A   127.0.0.1
testing.zonetransfer.me.   301   IN   CNAME   www.zonetransfer.me.
vpn.zonetransfer.me.    4000    IN      A       174.36.59.154
www.zonetransfer.me.    7200    IN      A       5.196.105.14
xss.zonetransfer.me.    300     IN      TXT
zonetransfer.me.        7200    IN      SOA     nsztm1.digi.ninja. robin.digi.ninja. 2019100801 172800 900 1209600 3600
]
[*] Attempting DNS AXFR for zonetransfer.me from nsztm2.digi.ninja
W, [2020-08-11T11:28:14.539360 #3681]  WARN -- : Failed to parse RR packet from offset: 657
W, [2020-08-11T11:28:14.541109 #3681]  WARN -- : Failed to parse RR packet from offset: 726
W, [2020-08-11T11:28:14.544021 #3681]  WARN -- : Failed to parse RR packet from offset: 1018
W, [2020-08-11T11:28:14.545951 #3681]  WARN -- : Failed to parse RR packet from [...]

2020-08-11 16:57 UTC, gwillcox-r7 commented on lib/msf/core/exploit/dns/enumeration.rb
> +        print_error("Query #{domain} DNS AXFR - exception: #{e}")
Update next PR should fix this issue and the issue @bcoles mentioned with `Errno::ECONNRESET`. Just changed this to be "unknown exception" for the second line so we can visually mark it as being a slightly different error in the output (as technically this is an exception we are not aware that could be thrown vs one of the ones we list above that we know could be thrown, and it would good to visually mark it as such in case we need to fix this code more later on).

2020-08-11 17:29 UTC, gwillcox-r7 commented
@bcoles and @digininja question but considering the fixes here, shouldn't we also be applying the same fix on https://github.com/rapid7/metasploit-framework/blob/daf38ceb62e51e4a6c1d9be1ed57cb1c06406bdc/lib/msf/core/exploit/dns/enumeration.rb#L54

2020-08-11 17:31 UTC, gwillcox-r7 commented
@bcoles and @digininja Question but shouldn't we also be applying these fixes to https://github.com/rapid7/metasploit-framework/blob/8ccb93ef8c75a8698bcdde7732b984a15bff17d1/modules/auxiliary/gather/enum_dns.rb#L313

2020-08-11 17:54 UTC, bcoles commented
> 
> 
> @bcoles and @digininja Question but shouldn't we also be applying these fixes r.e `Errno::ECONNRESET` to
> 
> https://github.com/rapid7/metasploit-framework/blob/8ccb93ef8c75a8698bcdde7732b984a15bff17d1/modules/auxiliary/gather/enum_dns.rb#L313

The `axfr` method is dead code.

2020-08-11 18:41 UTC, gwillcox-r7 commented
Thanks @bcoles in that case ignore my comment as it seems its likely that function will be altered or removed with the other PR you mentioned, so no point in trying to adjust it here seeing as it isn't used by anything.

2020-08-11 18:42 UTC, gwillcox-r7 approved these changes

2020-08-11 18:43 UTC, gwillcox-r7 commented
Alright with everything else that was mentioned above I think we have resolved all the issues that I thought might affect this PR. Going to go ahead and merge this in so long. Thanks @bcoles for your help and @digininja for your contribution!

2020-08-11 18:49 UTC, merged

2020-08-11 18:53 UTC, gwillcox-r7 commented
# Release Notes
This patch applies fixes to the DNS enumeration library so that `auxiliary/gather/enum_dns` will not display a stack trace when it receives a connection reset message from a DNS server. It also adds additional checks in to the DNS enumeration module to handle errors in the event that the library does not handle them correctly.

2020-08-11 20:03 UTC, digininja commented
Thanks for applying it.