CVE-2020-16139
rapid7/metasploit-framework pull request #13984
Opened 2020-08-11 14:38 UTC by debifrank

This new python module targets vulnerability CVE-2020-16139 in the Cisco Unified IP Conference Station 7937G and causes a DoS Reset on the device by sending specially crafted packets repeatedly to the device.

## Verification

- [ ] Start `msfconsole`
- [ ] `use auxiliary/dos/cisco/CVE-2020-16139`
- [ ] `set RHOST 192.168.x.x`
- [ ] **Verify** `FIRING ZE MIZZLES!`
- [ ] **Verify** If device does not have Web Access enabled: `Device doesn't appear to be functioning or web access is not enabled.`
- [ ] **Verify** If device does have Web Access enabled: `DoS reset attack completed!`
- [ ] **Document** The vulnerability is explained on our blog [here](https://blacklanternsecurity.com/2020-08-07-Cisco-Unified-IP-Conference-Station-7937G/)

Our blog has video demonstrations of manual exploitation. If a demonstration of the module is necessary it can be provided.

2020-08-11 15:39 UTC, gwillcox-r7 commented
Took a quick look over the code and it looks like this is just making a HTTP request in Python. It would be advisable given these circumstances to just port this code over to Ruby instead. You can find a guide on how to do this at https://github.com/rapid7/metasploit-framework/wiki/How-to-Send-an-HTTP-Request-Using-HTTPClient.

2020-08-11 20:07 UTC, h00die commented
https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/example_webapp.rb as another example

2020-08-11 20:08 UTC, h00die commented
Also wondering if some of these could be combined.  Looks like 2 are DoS modules, maybe combine into 1 module and allow the `ACTION` to specify which DoS to perform.

2020-08-12 15:09 UTC, debifrank commented
@gwillcox-r7 I was hoping to provide these as examples for the recent Python support in place. If it is absolutely necessary I can convert them to Ruby.

@h00die They are testing two different routes of DoS, and each cause a different type of DoS (one resets the device, the other causes permanently DoS until the device is power cycled manually). If it is absolutely necessary to combine them with an ACTION switch I can do that.

2020-08-12 15:24 UTC, gwillcox-r7 commented
@debifrank Replying here as @h00die responded here already and I don't want to duplicate comments all over the place.

Spoke to @smcintyre-r7 about this a bit more and the conclusion was basically that right now our Ruby modules have a lot more features than our Python modules do. Whilst you could submit a module as a Python module, given that in this case your not doing anything that is really Python specific, it seems that you would be limiting the module where it isn't necessary. In particular our external modules don't support pivoting, so you can't run a Meterpreter session over them.

Another limitation is that Python is not shipped with Metasploit itself, so users may not even have the `requests` library that you use here installed, and our Windows Omnibus nightly installers don't install Python with the build either. If you were to submit this as a Python module you would need to rewrite things to use the `sockets` library instead seeing as that comes built in with Python.

So basically the reason we are recommending Ruby is purely to avoid these issues given that the module could remove a lot of these self imposed restrictions purely by using Ruby. If you still want to submit in Python feel free to do so, but just be aware that these will be the limitations that will be imposed as a result of framework requirements.

2020-08-12 15:32 UTC, debifrank commented
@gwillcox-r7 Understood, and thank you for the quick reply and explanation of the limitations of the Python support in place. With that in mind though, I would still like to provide these as Python modules and begin working on the documentation files requested.

2020-08-12 17:58 UTC, debifrank commented
As these modules are written in Python, I don't believe rubocop is a valid option here. Does msftidy.rb have Python support or should I use something else like Pylint?

2020-08-12 18:28 UTC, gwillcox-r7 commented
@debifrank Hmm thats a fair point. For the linting my main point was to run `tools/dev/msftidy_docs.rb` on all your documentation files, but you are correct in that we don't really have a linter for Python modules at the moment, at least not to the best of my knowledge. You can use Pylint if you want, and any attempts to lint your code using tools like Pylint would be much appreciated!

2020-08-13 13:57 UTC, debifrank commented
@gwillcox-r7 - Python scripts have been linted with autopep8 and the corresponding documentation linted with msftidy_docs.rb

2020-08-13 21:14 UTC, gwillcox-r7 commented
Alright so it looks like we either need PCAPs to be send to `msfdev [THE USUAL] metasploit [GUESSIT] com` or we will need to aquire one of these devices for testing. It seems the device itself is EOL which is probably why buying one brand new costs $300, but thankfully there are some second hand devices such as this one at https://www.atlasphones.com/products/cisco-7937g-unified-ip-conference-station-cp-7937g?variant=31324336029776 which are a little under $60 for a second hand device.

I'll commence reviewing the code of your documentation and module in the meantime for your PRs so that we can at least that cleaned up and ready.

2020-08-13 22:12 UTC, gwillcox-r7 requested changes

2020-08-13 22:12 UTC, gwillcox-r7 commented on modules/auxiliary/dos/cisco/CVE-2020-16139.py
> +        'rhost': {'type': 'address', 'description': 'Target address', 'required': True, 'default': 'None'}
This is very hard to read. Please put each element and its value on a separate line for easier readability.

2020-08-13 22:12 UTC, gwillcox-r7 commented on modules/auxiliary/dos/cisco/CVE-2020-16139.py
> +            'Module dependency (requests) is missing, cannot continue')
This should really all be on one line, not sure why it was split across two lines?

2020-08-13 22:12 UTC, gwillcox-r7 commented on modules/auxiliary/dos/cisco/CVE-2020-16139.py
> +                    "Device doesn't appear to be functioning or web access is not enabled.")
Again this should all really be on one line, not need to split this up.

2020-08-13 22:12 UTC, gwillcox-r7 commented on modules/auxiliary/dos/cisco/CVE-2020-16139.py
> +            return
There is a fatal flaw with the logic of this as it is programmed at the moment. First off `requests.exceptions.RequestException` can occur for any number of reasons, including SSL reasons or simply that that the request could not be decoded. See https://requests.readthedocs.io/en/master/_modules/requests/exceptions/ for more details. This results in you returning a message stating that the DoS attack succeeded even when it might not have. I believe what you want to capture here rather is `requests.exception.Timeout`, not `requests.exceptions.RequestException`

2020-08-13 22:12 UTC, gwillcox-r7 commented on modules/auxiliary/dos/cisco/CVE-2020-16139.py
> +    # Exploit
This comment doesn't really describe what is going on. I would either remove it, or better yet rewrite it to more accurately describe what is going on at this point in the code.

2020-08-14 13:44 UTC, debifrank commented
The firmware Cisco provides for this device is not the full OS. It is only a small patch that contains some certificates, HTML and XML. I do not believe you will be able to emulate it. I can provide PCAP files, or if someone is interested themselves they are rather cheap when refurbished but will require PoE (not included).

2020-08-14 13:45 UTC, debifrank commented on modules/auxiliary/dos/cisco/CVE-2020-16139.py
> +    # Exploit
While I have no problem changing this, I do want to mention it is taken directly from the example documentation [here](https://github.com/rapid7/metasploit-framework/wiki/Writing-External-Python-Modules)

2020-08-14 14:37 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/dos/cisco/CVE-2020-16139.md
> +
This is much better @debifrank, thanks for including this! Marking this as resolved.

2020-08-14 14:43 UTC, gwillcox-r7 requested changes

2020-08-14 14:43 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/dos/cisco/CVE-2020-16139.md
> +  This module has been tested successfully against SCCP-1-4-5-5 and SCCP-1-4-5-7.
Again you still haven't included the vulnerable firmware versions here. Please include this in your description. Also is SCCP-1-4-5-7 a firmware version, a product, or something else? I can't tell from the description here. Same applies to the `## Scenarios` section.

2020-08-14 14:43 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/dos/cisco/CVE-2020-16139.md
> +### Cisco 7937G SCCP-1-4-5-7
Is SCCP-1-4-5-7 a firmware version? Can you make this a little clearer? I thought the firmware versions were in a different format given your earlier descriptions.

2020-08-14 16:19 UTC, debifrank commented
Hopefully that resolves the issues mentioned and I didn't miss anything. I'll move on to correcting the other two in a similar fashion as the comments presented here if everything looks alright?

2020-08-14 18:13 UTC, gwillcox-r7 commented
`documentation/modules/auxiliary/dos/cisco/CVE-2020-16139.md` should become `documentation/modules/auxiliary/dos/cisco/cve_2020_16139.md`

2020-08-14 18:19 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/dos/cisco/CVE-2020-16139.md
> +to the device immediately afterward to verify device is offline/reseting.
This has been updated with a more accurate description by @debifrank which is now in the `Description` section as mentioned. Marking resolved

2020-08-14 18:21 UTC, gwillcox-r7 commented on modules/auxiliary/dos/cisco/CVE-2020-16139.py
> +    logging.info("FIRING ZE MIZZLES!")
I'm leaving this as open as I still think "Sending DoS packets" is a little vague of a description. In reality you should say something like "Making POST requests to trigger the PING functionality. Host should crash with a DoS shortly..." or something similar to this that more accurately describes what is being sent.

2020-08-14 18:22 UTC, gwillcox-r7 commented on modules/auxiliary/dos/cisco/CVE-2020-16139.py
> +    data = "A"*46
New option looks good, thanks for fixing this @debifrank!

2020-08-14 18:24 UTC, gwillcox-r7 commented on modules/auxiliary/dos/cisco/CVE-2020-16139.py
> +    data = "A"*46
New option was a little confusing at first (been a while since I used Python), but tested it and confirmed it works:

```
>>> ''.join(random.choice(string.ascii_letters) for i in range(46))
'ckshKNGDHKrHOkAbPBwjQsoVwGKPlLoxPQRZbRIXCconBM'
```

Thanks for fixing this @debifrank!

2020-08-14 18:27 UTC, gwillcox-r7 commented on modules/auxiliary/dos/cisco/CVE-2020-16139.py
> +        DoS reset attack
Only comment on this would be that right now this is one long long line. Please line wrap this line to 72 columns or less so people reading the source code can have an easier time reading your output.

2020-08-14 18:28 UTC, gwillcox-r7 commented on modules/auxiliary/dos/cisco/CVE-2020-16139.py
> +        'rhost': {'type': 'address', 'description': 'Target address', 'required': True, 'default': 'None'}
Your trailing `}` should be indented to match the indentation of the rest of your code for readability. Other than that this looks fine now.

2020-08-14 18:33 UTC, gwillcox-r7 commented on modules/auxiliary/dos/cisco/CVE-2020-16139.py
> +            return
Sorry so I should have clarified this a bit more. Ideally what you want to include now is a extra segment after your current code that handles all other exceptions with a generic message that states something like `Unexpected response recieved!`:

So something like the following:

```
except requests.exceptions.ReadTimeout as e:
            logging.info('DoS reset attack completed!')
            return
except requests.exception.RequestException as e:
           logging.info('An unexpected exception occurred: " + e)
           return
```

2020-08-14 18:52 UTC, debifrank commented
I've got the three PCAP files as well now. I'll go ahead and send them to the specified address.

2020-08-14 18:58 UTC, debifrank commented
It appears the PCAP files are too large for me to send over email. Do you have a suggested solution?

2020-08-14 20:22 UTC, debifrank commented on modules/auxiliary/dos/cisco/CVE-2020-16139.py
> +            return
Missed this comment. Should be resolved now. Tested and still functions properly as before.

2020-08-14 21:27 UTC, gwillcox-r7 commented
> I've got the three PCAP files as well now. I'll go ahead and send them to the specified address.

Thanks received 👍

2020-08-14 21:28 UTC, gwillcox-r7 commented on modules/auxiliary/dos/cisco/CVE-2020-16139.py
> +            return
Looks good 👍

2020-08-14 21:30 UTC, gwillcox-r7 commented
@debifrank Still got two open comments on the files FYI. GitHub does have a tendency to hide the list sometimes.

2020-08-14 21:44 UTC, debifrank commented
Thanks for the update. I think I found the remaining issues and have put in the necessary edits.

2020-08-14 21:55 UTC, gwillcox-r7 commented on modules/auxiliary/dos/cisco/CVE-2020-16139.py
> +        DoS reset attack
Very nice looks a lot neater now :) Thanks for fixing this!

2020-08-14 21:56 UTC, gwillcox-r7 commented on modules/auxiliary/dos/cisco/CVE-2020-16139.py
> +    logging.info("FIRING ZE MIZZLES!")
New changes look good and accurately describe what is going on 👍 Marking as resolved.

2020-08-14 21:56 UTC, gwillcox-r7 commented
New changes look good, marked the related issues as resolved :)

2020-08-14 21:56 UTC, debifrank commented
Huzzah!

2020-08-17 12:58 UTC, debifrank commented
Are there any other roadblocks I can help clear up for these three modules?

2020-08-17 13:57 UTC, gwillcox-r7 commented
Just a heads up I'm not on PR duty the next 2 weeks so it is likely that someone else will be doing the last review and touch ups on your PRs, however so far the only thing I can see that might need to be altered is that you mentioned you tested this on two firmware versions, however only one of them is listed under the `Scenarios` section. Please add in the results of testing the other firmware version so that we have evidence to back up your statement that it works on both of these firmware versions.

2020-08-21 14:22 UTC, merged