TeamViewer URI SMB exploit (CVE-2020-13699)
rapid7/metasploit-framework pull request #13989
Opened 2020-08-13 00:05 UTC by h00die

This adds an HTTP server which responds to Firefox (all other browsers aren't exploitable) with an iframe that will force TeamViewer to create an SMB connection to a server of our choice.  Exploits CVE-2020-13699.  This is an unbelievably simple exploit.
I can provide the Teamviewer 15.4.4445 installer binary if needed.

## Verification

- [ ]  Install the application
- [ ] Start msfconsole
- [ ] Do: `use auxiliary/server/teamviewer_uri_smb_redirect`
- [ ] Do: `set SMB_SERVER [IP]`
- [ ] Do: `run`
- [ ] Start an SMB Capture or Relay server (such as responder)
- [ ] Open the URL on the target
- [ ] The SMB Server should receive a connection.

@jeffssh FYI.

I also wanted to note I emailed @jeffssh about this exploit with a question.  They answered back immediately and were super nice answering my questions, so just wanted to say thanks and show appreciation!

2020-08-13 06:33 UTC, bcoles commented on documentation/modules/auxiliary/server/teamviewer_uri_smb_redirect.md
> +Start the SMB replay/capture
Why not use `modules/auxiliary/server/capture/smb.rb` ?

2020-08-13 06:33 UTC, bcoles commented on modules/auxiliary/server/teamviewer_uri_smb_redirect.rb
> +        ])
Is there a reason not to iterate through these creating an iframe for each? Concerned about popups?

2020-08-13 06:33 UTC, bcoles commented on modules/auxiliary/server/teamviewer_uri_smb_redirect.rb
> +  end
A `firefox?` method seems a bit redundant as a replacement for `include?`.

```suggestion
  def on_request_uri(cli, req)
    print_status("Request received for: #{req.uri}")

    ua = req.headers['User-Agent'].to_s

    unless ua.include?('Firefox')
      print_error('Target is not Firefox')
      return
    end

    print_status("Sending TeamViewer Link to #{ua}...")
    send_response_html(cli, html_content)
  end
```

2020-08-13 14:42 UTC, h00die commented on documentation/modules/auxiliary/server/teamviewer_uri_smb_redirect.md
> +Start the SMB replay/capture
SMB3 **server** doesn't exist for msf yet, and win10 1909 only connected through that.

2020-08-13 14:43 UTC, h00die commented on modules/auxiliary/server/teamviewer_uri_smb_redirect.rb
> +        ])
Yup, exactly.

2020-08-18 15:16 UTC, cdelafuente-r7 requested changes
Thanks @h00die for this module. I just left a couple of small comments related to typos in the documentation.

2020-08-18 15:19 UTC, cdelafuente-r7 commented
This has been tested against Teamviewer v8.0.16642 and v15.4.4445. Both versions connect to the controlled SMB server as expected.

2020-08-18 17:46 UTC, h00die commented
all done, added 8.0.16642 to the list of confirmed versions as well.

2020-08-19 09:03 UTC, cdelafuente-r7 commented
Thank you! I'll go ahead and land it shortly.

2020-08-19 09:03 UTC, cdelafuente-r7 approved these changes

2020-08-19 09:11 UTC, merged

2020-08-19 09:36 UTC, cdelafuente-r7 commented
#Release Notes
This adds an exploit targeting an unquoted parameter call within the Teamviewer URI handler to create an SMB connection to an attacker controlled IP. This vulnerability is identified as CVE-2020-13699. By successfully exploiting this, an attacker would be able to capture the NTLM authentication contained in the request to retrieve passwords (hash cracking) or relay it (using a tool like responder) for code execution.

2020-09-03 22:21 UTC, pbarry-r7 commented
# Release Notes

New module <code>auxiliary/server/teamviewer_uri_smb_redirect</code> targets remote desktop software TeamViewer Desktop for Windows, creating an SMB connection with a vulnerable target via an unquoted parameter call within the
TeamViewer URI handler (<a href="https://attackerkb.com/topics/OQVSrAOTEg/cve-2020-13699?referrer=msfReleaseNotes">CVE-2020-13699</a>).