CVE-2020-1571 Windows Setup EoP with Patch Bypass
rapid7/metasploit-framework pull request #14044
Opened 2020-08-24 22:57 UTC by gwillcox-r7

This module adds support for exploiting CVE-2020-1571 using Metasploit, and also incorporates the, as of yet unpatched bypass from @klinix5. Successful exploitation should grant an attacker a shell as the `NT AUTHORITY\NETWORK SERVICE` user, though once @smcintyre-r7's PR at #14030 lands it should be possible to easily elevate to `SYSTEM` using `getsystem`.

## Verification
- [ ] Gain a Meterpreter shell as a normal user on a Windows 10 machine running  v1909 or earlier.
- [ ] `use exploit/windows/local/cve_2020_1571_windows_setup_lpe`
- [ ] `set SESSION *ID of session*`
- [ ] `set LHOST *LOCAL IP*`
- [ ] `set LPORT *LOCAL PORT TO LISTEN ON*`
- [ ] **Verify** that the exploit runs and spawns a shell as `NT AUTHORITY\NETWORK SERVICE`. You may experience a timeout issue at the very end due to how we run the service that grants us the `NT AUTHORITY\NETWORK SERVICE` permissions.
- [ ] **Document** if there are any additional files that need cleanup, or if there is anything that isn't working or appears odd in the output.

2020-08-24 23:01 UTC, gwillcox-r7 commented
Note for pentesters - Right now this module will work successfully, however there are a few tidying up issues like code quality improvements, documentation, and some double checking on the removal of files we drop that I need to address. This is the only reason this has been marked as a WIP.

2020-08-25 18:56 UTC, gwillcox-r7 commented
Still to do: 

1. Remove the extra debug output lines from the DLL's code to prevent potential strings that AVs can match on.
1. Review the code to see if there are any files that we drop on disk that we don't clean up, and either clean these files up or make the user aware of them when we grant them a shell.
1. Write up documentation
1. Get the module ratings and info section updated with appropriate info.
1. Add in adjustments to this exploit related to changes that @smcintyre-r7 made to my other PR for CVE-2020-1170.

2020-08-27 21:47 UTC, smcintyre-r7 requested changes

2020-08-27 21:47 UTC, smcintyre-r7 commented on external/source/exploits/CVE-2020-1571/CVE-2020-1571/exploit.cpp
> +	}
If you run this in the context of your own meterpreter session (because you can't / don't inject it into another) this will kill your session. Need fail out some other way, would simply returning be insufficient? If this gets called multiple times, could you use a static var or something to signal success. It doesn't look like you have any call back parameters so that might be your best choice.

2020-08-27 21:47 UTC, smcintyre-r7 commented on external/source/exploits/CVE-2020-1571/CVE-2020-1571/exploit.cpp
> +		}
Is `once` actually referenced anywhere? It looks like you clear it here if it's set but I don't see where it's used.

2020-08-27 21:47 UTC, smcintyre-r7 commented on modules/exploits/windows/local/cve_2020_1571_windows_setup_lpe.rb
> +            writing, there is no way to trigger the functionality needed to exploit this bug on that version of the operating system. Its possible
Can you please rephrase this to be in the third person context and remove any hints of speculation.

2020-08-27 21:47 UTC, smcintyre-r7 commented on modules/exploits/windows/local/cve_2020_1571_windows_setup_lpe.rb
> +    # Without this sleep statement here, the payload that we drop will not be erased from the target system automatically.
This seems incredibly odd. Any idea why that is? Also have you tried setting the `WfsDelay`.

2020-08-27 23:21 UTC, space-r7 commented on external/source/exploits/CVE-2020-1571/CVE-2020-1571/FileOpLock.cpp
> +}
Is this needed? It looks like `FileOpLock::CreateLock()` that accepts a `HANDLE` is only used in the exploit.

2020-08-27 23:21 UTC, space-r7 commented on external/source/exploits/CVE-2020-1571/CVE-2020-1571/FileOpLock.cpp
> +}
Is this needed? It doesn't look like it gets called in this exploit.

2020-08-28 14:59 UTC, gwillcox-r7 commented on external/source/exploits/CVE-2020-1571/CVE-2020-1571/FileOpLock.cpp
> +}
This code was taken from the author's original code, which has a bunch of files like this which create classes and wrappers that can be reused across multiple projects. If you want to remove this here you can though; I just left it in as I didn't want to modify the original author's code.

2020-08-28 15:00 UTC, gwillcox-r7 commented on external/source/exploits/CVE-2020-1571/CVE-2020-1571/FileOpLock.cpp
> +}
This code was taken from the author's original code, which has a bunch of files like this which create classes and wrappers that can be reused across multiple projects. If you want to remove this here you can though; I just left it in as I didn't want to modify the original author's code.

And yes you are correct we could remove this if you want, its not used within the code but it is part of the class that was defined in this file so that the same techniques could be reused with multiple different inputs.

2020-08-28 15:01 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_1571_windows_setup_lpe.rb
> +    sleep(5)
Good catch, let me fix that 👍

2020-08-28 15:05 UTC, gwillcox-r7 commented on external/source/exploits/CVE-2020-1571/CVE-2020-1571/FileOpLock.cpp
> +	}
Probably, this isn't my code, this is taken from the original PoC code, though I agree this check doesn't make much sense given that nothing is done if it is triggered.

2020-08-28 15:05 UTC, gwillcox-r7 commented on external/source/exploits/CVE-2020-1571/CVE-2020-1571/FileOpLock.cpp
> +	}
Probably, this isn't my code, this is taken from the original PoC code, though I agree this check doesn't make much sense given that nothing is done if it is triggered.

2020-08-28 15:06 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/cve_2020_1571_windows_setup_lpe.md
> +With the ability to delete arbitrary folders as the `SYSTEM` user, attackers can then proceed to use the direction deletion technique described in
Woops good catch, thanks 👍

2020-08-28 15:07 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/cve_2020_1571_windows_setup_lpe.md
> +  this timer to too low of a value will result in the exploit failing so its recommended to set
Will be fixed with next commit

2020-08-28 15:07 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/cve_2020_1571_windows_setup_lpe.md
> +  7. Do: ```set WaitTime <minutes>``` to set the number of minutes you want to wait the exploit to wait for the DLL to complete its job before continuing.
Will be fixed with next commit

2020-08-28 15:09 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_1571_windows_setup_lpe.rb
> +            Windows 10 v2004 machines were also vulnerable to this bug when they wrote up the advisory for CVE-2020-1571.
Good catches, thanks! Will fix with next commit 👍

2020-08-28 15:24 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_1571_windows_setup_lpe.rb
> +    # Without this sleep statement here, the payload that we drop will not be erased from the target system automatically.
Nope, no idea, I just tried it and it worked. I think this occurs due to some conflict between when the service runs and when we try and clean stuff up. So by allowing a bit of time for the service to run first we avoid the issue of trying to clean up whilst files are in use.

2020-08-28 15:30 UTC, gwillcox-r7 commented on external/source/exploits/CVE-2020-1571/CVE-2020-1571/exploit.cpp
> +		}
Hmm this wasn't my code, it was copied from the author's code. That being said it appears to be a local variable as its being set to `true` on the line above. I think the idea was to check if the loop had only executed once or not but the logic as its coded right now doesn't really do that and I can't see a point for this variable existing.

Also looked at the other code and confirmed this isn't being used elsewhere. I'll remove this so long.

2020-08-28 15:41 UTC, gwillcox-r7 commented on external/source/exploits/CVE-2020-1571/CVE-2020-1571/exploit.cpp
> +		}
Will be removed with next commit.

2020-08-28 15:47 UTC, gwillcox-r7 commented on external/source/exploits/CVE-2020-1571/CVE-2020-1571/exploit.cpp
> +	}
Hmm we only inject this and run this once but you are correct this is within the context of the Meterpreter session so this would kill our session. Thanks for catching this! We don't check the return value of the DLL, but rather that the two directories we ask the DLL to delete are deleted, so I'll just change these into `return` statements instead.

2020-08-28 16:16 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_1571_windows_setup_lpe.rb
> +            writing, there is no way to trigger the functionality needed to exploit this bug on that version of the operating system. Its possible
Removed the speculation and turned it into a more factual statement addressing the fact that the module may not cover the same targets as the Microsoft advisory states and just left it at that. Let me know if that needs further editing.

2020-08-28 16:20 UTC, gwillcox-r7 commented on external/source/exploits/CVE-2020-1571/CVE-2020-1571/FileOpLock.cpp
> +	}
Will resolve this is the next commit. DLLs will need to be recompiled though.

2020-08-28 16:20 UTC, gwillcox-r7 commented on external/source/exploits/CVE-2020-1571/CVE-2020-1571/FileOpLock.cpp
> +	}
Resolved in next commit.

2020-08-28 16:34 UTC, gwillcox-r7 commented on external/source/exploits/CVE-2020-1571/CVE-2020-1571/FileOpLock.cpp
> +}
After further discussions with @space-r7, I'm marking this as resolved as to do all the edits required to make these changes consistent would take more effort than the potential benefits gained.

2020-08-28 16:34 UTC, gwillcox-r7 commented on external/source/exploits/CVE-2020-1571/CVE-2020-1571/FileOpLock.cpp
> +}
After further discussions with @space-r7, I'm marking this as resolved as to do all the edits required to make these changes consistent would take more effort than the potential benefits gained.

2020-09-02 20:39 UTC, smcintyre-r7 commented on modules/exploits/windows/local/cve_2020_1571_windows_setup_lpe.rb
> +    # Without this sleep statement here, the payload that we drop will not be erased from the target system automatically.
If it's an issue with cleaning up files that are in use can you try setting `FileDropperDelay` instead?

2020-09-02 21:20 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_1571_windows_setup_lpe.rb
> +    # Without this sleep statement here, the payload that we drop will not be erased from the target system automatically.
Sure let me check if that helps or not @smcintyre-r7, sounds like that would be a better solution than this

2020-11-09 19:54 UTC, gwillcox-r7 commented
@space-r7 This should be ready for testing again. The issue with the delay on this PR has since been resolved. DM me if you need more info.

2020-11-11 15:16 UTC, space-r7 commented
> @space-r7 This should be ready for testing again. The issue with the delay on this PR has since been resolved. DM me if you need more info.

Awesome! I'll try to get started on this today, thanks!

2020-12-08 20:34 UTC, space-r7 commented
I tried testing this module against Windows 10 versions 1803 and 1809. The feature update will be `Getting things ready` until it reaches ~90% complete, and then I'll get a `Download error - 0x80070005` status. If I simply retry downloading the feature update without running the exploit, the update will succeed.

I also tried the [PoC](https://github.com/klinix5/Windows-Setup-EoP/tree/master/CVE-2020-1571-Bypass(0day)) and got the same result. I'm not sure if this is getting patched before the feature update is ready or what.

Here's the output from the PoC:

![Screen Shot 2020-12-08 at 2 24 20 PM](https://user-images.githubusercontent.com/40177151/101537482-275dc600-3961-11eb-8b78-298cbc173990.png)

2020-12-08 21:10 UTC, gwillcox-r7 commented
@space-r7 The error is expected and is normal. It is also expected to occur around 90% to 95% done so this is all in line with what I expected. The interesting part though is that for some reason it looks like part of the exploit might have worked but the other part didn't. In particular the `C:\Program Files\Windows Media Player` folder seems to have been deleted but not `C:\ProgramData\Microsoft\Windows\WER`.

I'm curious if maybe there are some files within `C:\ProgramData\Microsoft\Windows\WER` that are preventing it from being deleted as I have had this issue in the past whilst testing this exploit.

2020-12-21 22:10 UTC, gwillcox-r7 commented
@space-r7 Going to attic this for now. Testing has been fiddly at best and exploitation of this exploit is either a success or you wind up with a patched system and you can never exploit the target again.

Furthermore, it seems Microsoft is pushing those users on 1903 to forcibly upgrade to 1909 according to https://www.computerworld.com/article/3597401/microsoft-deviates-from-the-norm-forcibly-upgrades-windows-10-1903-with-minor-1909-refresh.html so I imagine this process will also force users to install the latest updates as well. This means that the only PC's we could likely reasonably expect to target are 1909 machines that haven't applied updates for some reason.

All in all though this is a fiddly exploit at best and whilst I believe this was useful for an exploitability perspective (cause this bug certainly is exploitable), I do think that we have other bugs that have released recently that may prove to be better candidates for inclusion.

2020-12-21 22:11 UTC, closed without merging