Added option to skip execution
rapid7/metasploit-framework pull request #14172
Opened 2020-09-22 12:26 UTC by ingroxd

This change add an advanced option (`DisableExec`) which control the execution of the payload.

2020-09-22 15:42 UTC, gwillcox-r7 commented
@ingroxd Updated your description as before your description made it sound like this was a library related change that could affect a large portion of the code base. However upon further review it seems you just intended to change the functionality of `modules/post/windows/manage/persistence_exe.rb` to allow the user to drop a persistent EXE onto disk without immediately executing it.

2020-09-23 06:40 UTC, ingroxd commented
Yes @gwillcox-r7 , it is exactly what I wanted, thank you!

2020-09-23 08:31 UTC, timwr requested changes
I think you should name the option `RUN_NOW` for consistency with modules/exploits/osx/local/persistence.rb

You could also call it `EXECUTE` or `EXEC_AFTER`, but let's not create yet another name for it.
It should default to true, so the logic needs to be inverted. I don't think you need the warning either.

2020-09-23 11:41 UTC, ingroxd commented
@timwr I don't know if github notified you, I tried the edit you suggested, should be ok now

2020-09-25 05:20 UTC, merged

2020-09-25 05:22 UTC, timwr commented
Nice work @ingroxd !
I made some minor changes: https://github.com/rapid7/metasploit-framework/commit/bb04041c930b42f24374f8f8407e7ae6b2a59c2d (I made it a non-advanced option and fixed the service from starting unless the option is set).
Thanks for your help!

2020-09-25 05:24 UTC, timwr commented
## Release notes
Add a RUN_NOW option to modules/post/windows/manage/persistence_exe.rb that can be used to choose whether the exe is automatically executed when the module is run.