force res and expected encoding in smb tests
rapid7/metasploit-framework pull request #14197
Opened 2020-09-29 13:59 UTC by jmartin-r7

In preparation for Ruby 2.7 update force known encodings during test comparison and add 2.7.1 to Travis CI.

## Verification

List the steps needed to make sure this thing works

- [ ] Review Travis results for Ruby 2.6 and Ruby 2.7

2020-09-29 21:44 UTC, jmartin-r7 commented
This will require anyone using a git checkout that does not already have `bundler >= 2` available in the env to install a newer bundler.

```
gem install bundler
```

2020-09-30 15:49 UTC, acammack-r7 requested changes
Glad a lot of things don't have to change, but I think the encoding issues should be addressed further down the testing stack.

2020-09-30 15:49 UTC, acammack-r7 commented on spec/lib/msf/core/exploit/smb/server/share/command/negotiate_spec.rb
> +      expect(res.force_encoding("ASCII-8BIT")).to eq(default_response.force_encoding("ASCII-8BIT"))
This seems like a symptom of a deeper problem with how we handle encoding. For example, the request fixtures should be specified like `"\x00\x00\x00\x00".b` and `msf_io` should be put in `binmode` in the shared context to prevent this cropping up in other places.

2020-09-30 15:49 UTC, acammack-r7 commented on spec/lib/msf/core/exploit/smb/server/share/command/close_spec.rb
> +      expect(res.force_encoding("ASCII-8BIT")).to eq(valid_response.force_encoding("ASCII-8BIT"))
Same as above.

2020-09-30 17:55 UTC, jmartin-r7 commented on spec/lib/msf/core/exploit/smb/server/share/command/negotiate_spec.rb
> +      expect(res.force_encoding("ASCII-8BIT")).to eq(default_response.force_encoding("ASCII-8BIT"))
The need to force encoding on both sides for 2.6 vs only accounting for 2.7 set the encoding on `default_response` to `UTF-8` makes me suspect there may be more work to do.  This adjustment was the simplest compatibility only revision.  Seems reasonable to look further into the stack to see if this can be made consistent for 2.6 and 2.7 without forcing both sides to a set encoding.

2020-10-01 13:51 UTC, acammack-r7 commented on spec/lib/msf/core/exploit/smb/server/share/command/negotiate_spec.rb
> +      expect(res.force_encoding("ASCII-8BIT")).to eq(default_response.force_encoding("ASCII-8BIT"))
Since in <= 2.6 treats this StringIO as UTF-8 (mistakenly, I think), we can force it by setting `s.binmode` in https://github.com/rapid7/metasploit-framework/blob/4747b7c676e20c5d511a4a68e89573c45bc39a4d/spec/support/shared/contexts/msf/string_io.rb#L9-L18

2020-10-02 16:21 UTC, acammack-r7 approved these changes

2020-10-02 16:27 UTC, merged

2020-10-02 16:28 UTC, acammack-r7 commented
Went ahead and bumped to latest Ruby 2.7 release while landing: https://github.com/rapid7/metasploit-framework/commit/919e5212e72031aadfdbdd4a133995991c5395b3