Randomly generate hashes for hashlib and networking specs
rapid7/metasploit-framework pull request #14219
Opened 2020-10-04 16:57 UTC by h00die

https://github.com/rapid7/metasploit-framework/pull/14031#discussion_r474726358

The hashlib spec, and networking specs now randomly generate md5 and sha256 password hashes to test against.
Also fixed a bug in the Brocade hash checks where `.` wasn't a valid character.

2020-11-02 15:57 UTC, agalway-r7 requested changes
`seed.crypt` is throwing rspec errors, due to `crypt` [cipher types availability being dependent on what your platform natively supports](https://apidock.com/ruby/String/crypt#1075-String-crypt-uses-your-platform-s-native-implementation):

```
Failure/Error: expect(aux_brocade).to receive(:print_good).with("User brocade of type 8 found with password hash #{hash}.")

       (#<DummyBrocadeClass:0x00007fa869551b30>).print_good("User brocade of type 8 found with password hash $1lNbtAlR6ckA.")
           expected: 1 time with arguments: ("User brocade of type 8 found with password hash $1lNbtAlR6ckA.")
           received: 0 times
```

To add more detail, for the command `"password".crypt("$6$somesalt")`:
- This is the MAC OS X 10.15.7 output: `"$1d2n7Q0.r54s"`
- This is the Ubuntu 19.10 output: `"$1$somesalt$W.KCTbPSiFDGffAGOjcBc."` 

@h00die would you be able to replace `crypt` with a platform independent implementation?

2020-11-09 10:06 UTC, agalway-r7 commented
@h00die We could also just merge the first commit of this PR as a stop gap and leave the second commit to be built on so it works with all platforms?

2020-11-10 00:23 UTC, h00die commented
well, I'm not interested, nor have time to rewrite a platform agnostic crypt library.  So I guess we can land the first commit, and just abandon the 2nd.

2020-11-16 12:57 UTC, merged

2020-11-16 12:59 UTC, agalway-r7 commented
## Release Notes
Fixes bug in tests that meant Brocade hashes weren't checked for the `.` character