Update sharepoint_ssi_viewstate
rapid7/metasploit-framework pull request #14345
Opened 2020-11-04 15:53 UTC by chmod750

Add Cookie and User-Agent headers as exploit inputs.
This can be used when authentication is performed trough an HTTP form for example.

Verification
List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/http/sharepoint_ssi_viewstate`
- [ ] `set User-Agent ''`
- [ ] `set Cookie ''`
- [ ] **Verify** Configure other inputs function of the target and run the exploit. The exploit shall work properly using added inputs.

This has been successfully tested during an audit.

2020-11-04 20:24 UTC, smcintyre-r7 requested changes
So we actually already have the `UserAgent` datastore option. It's under the advanced options. Have you tried using that value? This shouldn't be confused with `HttpUserAgent` and `HttpCookie` which are payload options for the `reverse_http(s)` stager.

If `UserAgent` works, you should remove the definition here and update your `#user_agent` method to use it.

2020-11-04 22:56 UTC, smcintyre-r7 commented
Also do you by chance have documentation with steps on how to setup SharePoint to require these changes? It looks like from your steps the original environment I used would work so it doesn't really demonstrate your changes, just that nothing breaks (which is also important).

2020-11-05 11:01 UTC, chmod750 commented
> So we actually already have the `UserAgent` datastore option. It's under the advanced options. Have you tried using that value? This shouldn't be confused with `HttpUserAgent` and `HttpCookie` which are payload options for the `reverse_http(s)` stager.
> 
> If `UserAgent` works, you should remove the definition here and update your `#user_agent` method to use it.

Thanks. I just tried and it works through advanced options. So I just deleted the UserAgent option from this PR.

2020-11-05 11:06 UTC, chmod750 commented
> Also do you by chance have documentation with steps on how to setup SharePoint to require these changes? It looks like from your steps the original environment I used would work so it doesn't really demonstrate your changes, just that nothing breaks (which is also important).

Unfortunately I do not have this documentation. To test it, it would need a first additional web authentication method.

2020-11-06 02:37 UTC, wvu-r7 commented
Is the point of this PR just to add a cookie setting in case you already have a session? If so, I think that's fine.

2020-11-06 02:55 UTC, wvu-r7 requested changes
API-relevant changes suggested. The module doc will need to be updated with the new option, too. Lastly, this PR is coming from your `master` branch. cc @smcintyre-r7

2020-11-06 02:55 UTC, wvu-r7 commented on modules/exploits/windows/http/sharepoint_ssi_viewstate.rb
> +      },
The API provides something for this already. :)

```suggestion
      'cookie' => cookie
```

Trailing comma can be removed, too.

2020-11-06 02:55 UTC, wvu-r7 commented on modules/exploits/windows/http/sharepoint_ssi_viewstate.rb
>        'data' => ssi_page
```suggestion
      'method' => 'PUT',
      'uri' => ssi_path,
      'cookie' => cookie,
      'data' => ssi_page
```

This is the order I prefer as well. It's somewhat like the raw HTTP request.

2020-11-06 02:55 UTC, wvu-r7 commented on modules/exploits/windows/http/sharepoint_ssi_viewstate.rb
>        }
```suggestion
      'method' => 'GET',
      'uri' => ssi_path,
      'cookie' => cookie,
      'headers' => {
        ssi_header => '<form runat="server" /><!--#include virtual="/web.config"-->'
      }
```

2020-11-06 02:55 UTC, wvu-r7 commented on modules/exploits/windows/http/sharepoint_ssi_viewstate.rb
> +      },
```suggestion
      'cookie' => cookie,
```

2020-11-06 02:55 UTC, wvu-r7 commented on modules/exploits/windows/http/sharepoint_ssi_viewstate.rb
> +      },
```suggestion
      'cookie' => cookie,
```

2020-11-06 02:55 UTC, wvu-r7 commented on modules/exploits/windows/http/sharepoint_ssi_viewstate.rb
> +      OptString.new('Cookie', [false, 'Cookie'])
Just a little more descriptive.

```suggestion
      OptString.new('Cookie', [false, 'SharePoint cookie if you have one'])
```

If you can, please move this option above the comment about promoting advanced options. Make sure to remove the trailing comma. Thanks!

2020-11-06 03:04 UTC, wvu-r7 commented
FWIW, I don't foresee any conflicts between basic auth and cookie auth.

2020-11-06 09:03 UTC, chmod750 commented
> Is the point of this PR just to add a cookie setting in case you already have a session? If so, I think that's fine. I assume form auth is dependent on the target.

Yes, that's the case. Thanks.

2020-11-06 09:20 UTC, chmod750 commented
> API-relevant changes suggested. The module doc will need to be updated with the new option, too. Lastly, this PR is coming from your `master` branch. cc @smcintyre-r7

Than

> API-relevant changes suggested. The module doc will need to be updated with the new option, too. Lastly, this PR is coming from your `master` branch. cc @smcintyre-r7

Thanks for this review. I applied suggestions. Sorry for the master branch and thanks again.

2020-11-06 13:29 UTC, smcintyre-r7 commented
@wvu-r7 Good catch on the master branch. We do unfortunately have to close it because of that and it will need to be resubmitted.

2020-11-06 13:29 UTC, closed without merging

2020-11-06 13:30 UTC, smcintyre-r7 commented
If you have any questions on those steps to resubmit the changes from a unique branch just let me know. You can still comment on this PR even though it's closed. Thanks!

2020-11-06 19:18 UTC, wvu-r7 commented
Thanks for the updates, @chmod750! New PR is #14361.