Create shodan_host.rb
rapid7/metasploit-framework pull request #14429
Opened 2020-11-25 04:59 UTC by Natto97

```
Module options (auxiliary/scanner/http/shodan_host):

   Name           Current Setting  Required  Description
   ----           ---------------  --------  -----------
   Proxies                         no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                          yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT          80               yes       The target port (TCP)
   SHODAN_APIKEY                   yes       The SHODAN API key
   SSL            false            no        Negotiate SSL/TLS for outgoing connections
   VHOST                           no        HTTP server virtual host

msf6 auxiliary(scanner/http/shodan_host) > reload
[*] Reloading module...
msf6 auxiliary(scanner/http/shodan_host) > run
[-] Auxiliary failed: Msf::OptionValidateError One or more options failed to validate: RHOSTS, SHODAN_APIKEY.
msf6 auxiliary(scanner/http/shodan_host) > set RHOSTS 8.8.8.8
RHOSTS => 8.8.8.8
msf6 auxiliary(scanner/http/shodan_host) > set SHODAN_APIKEY xxxxxx
SHODAN_APIKEY => xxxxxx
msf6 auxiliary(scanner/http/shodan_host) > run
[*] Running module against 8.8.8.8

[+] 8.8.8.8:53
[*] Auxiliary module execution completed
```

2020-12-10 19:57 UTC, gwillcox-r7 commented
@Natto97 Any update on creating documentation for this PR and updating the module to fix the issues reported by Travis?

2020-12-14 09:59 UTC, Natto97 commented
@gwillcox-r7   Update file completed https://github.com/rapid7/metasploit-framework/pull/14511

2020-12-14 15:15 UTC, gwillcox-r7 commented
@Natto97 You do not need to create a separate PR for the documentation file. I have closed the other PR. Please apply your documentation updates from #14511 to your branch `patch-2` instead, and those changes will populate into this PR.

2020-12-15 06:56 UTC, Natto97 commented
> @Natto97 Any update on creating documentation for this PR and updating the module to fix the issues reported by Travis?

Has been updated, is it like this @gwillcox-r7

2020-12-21 15:20 UTC, gwillcox-r7 commented
Hello @Natto97. So I was just reviewing this module and I noticed that we already have a module in the framework right now that performs very similar functionality to your module, specifically https://github.com/rapid7/metasploit-framework/blob/c0b42ff7a2a1b677aaba6acd7ebeefddcffdf38e/modules/auxiliary/gather/shodan_search.rb.

That being said during my tests I did notice that the module I linked above will not work on free accounts as the `ip:` filter is a paid filter within shodan.io. Ironically though, the `host` filter is not, for reasons I don't fully understand. 

So with all this being said it seems the best option would be to update the module at https://github.com/rapid7/metasploit-framework/blob/c0b42ff7a2a1b677aaba6acd7ebeefddcffdf38e/modules/auxiliary/gather/shodan_search.rb so that it adds a new check to see if the user specified an IP as the search filter and if they did, then adjust the query format to specifically use the new API format to prevent users having to use the paid `ip:` filter. 

This will allow us to still gather the same information without having similar code spread across multiple modules, thereby reducing code duplication.

In essence we will just be expanding upon the existing module to add in some newer features.

2020-12-21 15:22 UTC, bcoles commented
> so that it adds a new check to see if the user specified an IP as the search filter and if they did, then adjust the query format to specifically use the new API format to prevent users having to use the paid ip: filter.

Is there a difference between the `host` and `ip` filters? If so, this check sounds like it will introduce unexpected behavior.

2020-12-21 15:33 UTC, gwillcox-r7 commented
> > so that it adds a new check to see if the user specified an IP as the search filter and if they did, then adjust the query format to specifically use the new API format to prevent users having to use the paid ip: filter.
> 
> Is there a difference between the `host` and `ip` filters? If so, this check sounds like it will introduce unexpected behavior.

I don't know

> > so that it adds a new check to see if the user specified an IP as the search filter and if they did, then adjust the query format to specifically use the new API format to prevent users having to use the paid ip: filter.
> 
> Is there a difference between the `host` and `ip` filters? If so, this check sounds like it will introduce unexpected behavior.

I'm actually not sure if the `host` filter is a valid filter upon further review. As for the `ip:` filter allowing hostnames, you are correct in that it does not allow hostnames.

2020-12-21 17:30 UTC, gwillcox-r7 commented
Alright sorry for the confusion. My original idea was to include this into https://github.com/rapid7/metasploit-framework/blob/c0b42ff7a2a1b677aaba6acd7ebeefddcffdf38e/modules/auxiliary/gather/shodan_search.rb. Here is the output from one such run of this module as it stands at the moment:

```
msf6 auxiliary(gather/shodan_search) > run

[*] Total: 2 on 1 pages. Showing: 1 page(s)
[*] Collecting data, please wait...

Search Results
==============

 IP:Port      City  Country        Hostname
 -------      ----  -------        --------
 8.8.8.8:443  N/A   United States  dns.google
 8.8.8.8:53   N/A   United States  dns.google

[*] Auxiliary module execution completed
msf6 auxiliary(gather/shodan_search) > show options

Module options (auxiliary/gather/shodan_search):

   Name           Current Setting                   Required  Description
   ----           ---------------                   --------  -----------
   DATABASE       false                             no        Add search results to the database
   MAXPAGE        1                                 yes       Max amount of pages to collect
   OUTFILE                                          no        A filename to store the list of IPs
   QUERY          ip:8.8.8.8                        yes       Keywords you want to search for
   REGEX          .*                                yes       Regex search for a specific IP/City/Country/Hostname
   SHODAN_APIKEY  *censored* yes       The SHODAN API key

msf6 auxiliary(gather/shodan_search) > 
```
Note that the output is nearly identical to this module, so us merging this module in would not add much net new value minus allowing people to query for the same information using a free Shodan account. 

My thought was to incorporate these changes into https://github.com/rapid7/metasploit-framework/blob/c0b42ff7a2a1b677aaba6acd7ebeefddcffdf38e/modules/auxiliary/gather/shodan_search.rb however it seems it that module was designed from the ground up to incorporate page result support for querying multiple hosts or large data sets at once. Therefore given that the API used within this module does not return any `page` number in its response it would be hard to properly incorporate it into the module.

In conclusion I am in favor of closing this PR out given that we already have similar functionality in the framework and the only thing this really adds in is the ability for free users to obtain the same data automatically.

2020-12-21 20:17 UTC, gwillcox-r7 requested changes
Okay very sorry for the confusion here. So what happened was that we were going to try and merge the changes into https://github.com/rapid7/metasploit-framework/blob/c0b42ff7a2a1b677aaba6acd7ebeefddcffdf38e/modules/auxiliary/gather/shodan_search.rb however after a lot of deliberation and analysis we discovered that module heavily relies on the concept of splitting results by pages, which is a pro feature, and the API this module uses doesn't support that feature. Additionally since that module's code is heavily based around the pages feature, its hard to refactor the code to support this new API.

Therefore I think it would be better to leave this module as is and if people have questions as to why some factors might be duplicated we can point them to this discussion. Again sorry for this confusion @Natto97.

Below are a few minor things that I found whilst reviewing the module. I'm going to go ahead and fix these up myself. I'm just leaving them here for your records, however don't worry I'll make sure these are fixed and the module will be landed today once all the changes have been applied and retested to make sure everything still works appropriately.

2020-12-21 21:28 UTC, gwillcox-r7 commented on modules/auxiliary/gather/shodan_host.rb
> +    end
Fixed in https://github.com/rapid7/metasploit-framework/pull/14429/commits/12277d3020f8e413b4396f140fe18435e1d6fbf0

2020-12-21 21:28 UTC, gwillcox-r7 commented on modules/auxiliary/gather/shodan_host.rb
> +      print_error('Shodan did not respond in an expected way. Check your api key')
Fixed in https://github.com/rapid7/metasploit-framework/pull/14429/commits/12277d3020f8e413b4396f140fe18435e1d6fbf0

2020-12-21 21:28 UTC, gwillcox-r7 commented on modules/auxiliary/gather/shodan_host.rb
> +      fail_with(Failure::Unknown, 'Unable to connect to shodan')
Fixed in https://github.com/rapid7/metasploit-framework/pull/14429/commits/12277d3020f8e413b4396f140fe18435e1d6fbf0

2020-12-21 21:28 UTC, gwillcox-r7 commented on modules/auxiliary/gather/shodan_host.rb
> +      return
Fixed in https://github.com/rapid7/metasploit-framework/pull/14429/commits/12277d3020f8e413b4396f140fe18435e1d6fbf0

2020-12-21 21:28 UTC, gwillcox-r7 commented on modules/auxiliary/gather/shodan_host.rb
> +    deregister_options("Proxies")
Fixed in https://github.com/rapid7/metasploit-framework/pull/14429/commits/12277d3020f8e413b4396f140fe18435e1d6fbf0

2020-12-21 21:28 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/gather/shodan_host.md
> +This module uses the shodan API to return all port information found on a given host IP.
Fixed in https://github.com/rapid7/metasploit-framework/pull/14429/commits/12277d3020f8e413b4396f140fe18435e1d6fbf0

2020-12-21 21:29 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/gather/shodan_host.md
> +  The target host whose port information needs to be obtained
Fixed in https://github.com/rapid7/metasploit-framework/pull/14429/commits/12277d3020f8e413b4396f140fe18435e1d6fbf0

2020-12-21 21:29 UTC, gwillcox-r7 approved these changes

2020-12-21 21:59 UTC, merged

2020-12-21 22:01 UTC, gwillcox-r7 commented
# Release Notes
A new module, `auxiliary/gather/shodan_host.rb` has been added which allows users with a Shodan account to enumerate which ports are publicly accessible on a host or set of hosts using Shodan's API.