Lazy load `HrrRbSsh` to stop `pty` from being required on windows
rapid7/metasploit-framework pull request #14514
Opened 2020-12-14 16:46 UTC by dwelch-r7

Resolves #14512 

Presumably broken by _something_ in #14202 

More work to be done to be nicer to the user, catching the actual problem of `pty` not being available on windows and logging out the reason

# Verification
Steps for reproducing the issue are mentioned in the issue

- [ ] Install latest framework on windows
- [ ] Verify that running msfconsole breaks
- [ ] Switch over to this PR
- [ ] msfconsole should now start up

2020-12-14 16:56 UTC, adfoster-r7 commented
@dwelch-r7 Should we add checking that the existing modules still work to the verification steps? 😄

2020-12-14 18:24 UTC, jmartin-r7 commented
@msjenkins-r7 test this please.

2020-12-14 19:18 UTC, jmartin-r7 requested changes
Sanity test shows this causes failures when generating payloads using `msfvenom`.

```
msfuser@vagrant:~/rapid7/metasploit-framework$ ./msfvenom -p linux/x64/meterpreter_reverse_https -f elf  -o linux-x64-meterpreter_reverse_https-192x168x16x137-30004.elf LHOST=192.168.15.71 LPORT=30004
Traceback (most recent call last):
	42: from ./msfvenom:463:in `<main>'
	41: from ./msfvenom:64:in `framework'
	40: from ./msfvenom:55:in `init_framework'
	39: from /home/msfuser/rapid7/metasploit-framework/lib/msf/base/simple/framework.rb:75:in `create'
	38: from /home/msfuser/rapid7/metasploit-framework/lib/msf/base/simple/framework.rb:127:in `simplify'
	37: from /home/msfuser/rapid7/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `init_module_paths'
	36: from /home/msfuser/rapid7/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `each'
	35: from /home/msfuser/rapid7/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:51:in `block in init_module_paths'
	34: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
	33: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
	32: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
	31: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/module_manager/loading.rb:130:in `load_modules'
	30: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/module_manager/loading.rb:130:in `each'
	29: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/module_manager/loading.rb:132:in `block in load_modules'
	28: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/modules/loader/base.rb:243:in `load_modules'
	27: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/modules/loader/directory.rb:27:in `each_module_reference_name'
	26: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/modules/loader/directory.rb:27:in `foreach'
	25: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/modules/loader/directory.rb:37:in `block in each_module_reference_name'
	24: from /home/msfuser/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rex-core-0.1.14/lib/rex/file.rb:132:in `find'
	23: from /home/msfuser/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rex-core-0.1.14/lib/rex/file.rb:132:in `catch'
	22: from /home/msfuser/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rex-core-0.1.14/lib/rex/file.rb:133:in `block in find'
	21: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/modules/loader/directory.rb:46:in `block (2 levels) in each_module_reference_name'
	20: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/modules/loader/base.rb:244:in `block in load_modules'
	19: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/modules/loader/base.rb:189:in `load_module'
	18: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/module_manager/loading.rb:70:in `on_module_load'
	17: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/payload_set.rb:208:in `add_module'
	16: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/payload_set.rb:208:in `new'
	15: from /home/msfuser/rapid7/metasploit-framework/modules/payloads/singles/cmd/unix/reverse_ssh.rb:27:in `initialize'
	14: from /home/msfuser/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	13: from /home/msfuser/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	12: from /home/msfuser/rapid7/metasploit-framework/lib/msf/core/handler/reverse_ssh.rb:2:in `<top (required)>'
	11: from /home/msfuser/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	10: from /home/msfuser/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	 9: from /home/msfuser/rapid7/metasploit-framework/lib/rex/proto/ssh.rb:4:in `<top (required)>'
	 8: from /home/msfuser/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	 7: from /home/msfuser/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	 6: from /home/msfuser/rapid7/metasploit-framework/lib/rex/proto/ssh/server.rb:2:in `<top (required)>'
	 5: from /home/msfuser/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	 4: from /home/msfuser/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	 3: from /home/msfuser/rapid7/metasploit-framework/lib/rex/proto/ssh/connection.rb:2:in `<top (required)>'
	 2: from /home/msfuser/rapid7/metasploit-framework/lib/rex/proto/ssh/connection.rb:3:in `<module:Rex>'
	 1: from /home/msfuser/rapid7/metasploit-framework/lib/rex/proto/ssh/connection.rb:4:in `<module:Proto>'
/home/msfuser/rapid7/metasploit-framework/lib/rex/proto/ssh/connection.rb:60:in `<module:Ssh>': uninitialized constant HrrRbSsh (NameError)
```

2020-12-15 15:07 UTC, jmartin-r7 approved these changes
Minor formatting item, testing validates `msfvenom` and `ssh_login` are working.

2020-12-15 15:29 UTC, jmartin-r7 requested changes
Confirmed windows console loads with this revision:
```
C:\Users\vagrant>msfconsole -q
C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
msf6 >
```

However `msfvenom` still fails on windows:
```
C:\Users\vagrant>msfvenom -l payloads
C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
Traceback (most recent call last):
        83: from C:/metasploit-framework/bin/../embedded/framework/msfvenom:409:in `<main>'
        82: from C:/metasploit-framework/bin/../embedded/framework/msfvenom:409:in `each'
        81: from C:/metasploit-framework/bin/../embedded/framework/msfvenom:412:in `block in <main>'
        80: from C:/metasploit-framework/bin/../embedded/framework/msfvenom:347:in `dump_payloads'
        79: from C:/metasploit-framework/embedded/framework/lib/msf/core/module_set.rb:92:in `each_module'
        78: from C:/metasploit-framework/embedded/framework/lib/msf/core/module_set.rb:245:in `each_module_list'
        77: from C:/metasploit-framework/embedded/framework/lib/msf/core/module_set.rb:245:in `each'
        76: from C:/metasploit-framework/embedded/framework/lib/msf/core/module_set.rb:272:in `block in each_module_list'
        75: from C:/metasploit-framework/bin/../embedded/framework/msfvenom:350:in `block in dump_payloads'
        74: from C:/metasploit-framework/bin/../embedded/framework/msfvenom:350:in `new'
        73: from C:/metasploit-framework/embedded/framework/modules/payloads/singles/cmd/unix/reverse_ssh.rb:17:in `initialize'
        72: from C:/metasploit-framework/embedded/framework/lib/msf/base/sessions/command_shell_options.rb:16:in `initialize'
        71: from C:/metasploit-framework/embedded/framework/lib/msf/core/handler/reverse_ssh.rb:44:in `initialize'
        70: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
        69: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
        68: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
        67: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        66: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        65: from C:/metasploit-framework/embedded/framework/lib/rex/proto/ssh/connection.rb:2:in `<top (required)>'
        64: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
        63: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
        62: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
        61: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        60: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        59: from C:/metasploit-framework/embedded/framework/lib/rex/proto/ssh/hrr_rb_ssh.rb:3:in `<top (required)>'
        58: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
        57: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
        56: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
        55: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        54: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        53: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/hrr_rb_ssh-0.3.0.pre2/lib/hrr_rb_ssh.rb:18:in `<top (required)>'
        52: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
        51: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
        50: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
        49: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        48: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        47: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/hrr_rb_ssh-0.3.0.pre2/lib/hrr_rb_ssh/connection.rb:7:in `<top (required)>'
        46: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
        45: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
        44: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
        43: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        42: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        41: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/hrr_rb_ssh-0.3.0.pre2/lib/hrr_rb_ssh/connection/channel.rb:6:in `<top (required)>'
        40: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
        39: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
        38: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
        37: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        36: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        35: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/hrr_rb_ssh-0.3.0.pre2/lib/hrr_rb_ssh/connection/channel/channel_type.rb:19:in `<top (required)>'
        34: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
        33: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
        32: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
        31: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        30: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        29: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/hrr_rb_ssh-0.3.0.pre2/lib/hrr_rb_ssh/connection/chann [...]

2020-12-15 16:50 UTC, dwelch-r7 commented
Nice spot @jmartin-r7 
It still works for generating payloads, but is failing when it comes to listing the problematic one I guess

2020-12-16 10:13 UTC, dwelch-r7 commented
Weird I got a completely different error on windows too I just realised:
```

C:\metasploit-framework\bin>msfvenom.bat -l payload
C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
Traceback (most recent call last):
        13: from C:/metasploit-framework/bin/../embedded/framework/msfvenom:409:in `<main>'
        12: from C:/metasploit-framework/bin/../embedded/framework/msfvenom:409:in `each'
        11: from C:/metasploit-framework/bin/../embedded/framework/msfvenom:412:in `block in <main>'
        10: from C:/metasploit-framework/bin/../embedded/framework/msfvenom:347:in `dump_payloads'
         9: from C:/metasploit-framework/embedded/framework/lib/msf/core/module_set.rb:92:in `each_module'
         8: from C:/metasploit-framework/embedded/framework/lib/msf/core/module_set.rb:245:in `each_module_list'
         7: from C:/metasploit-framework/embedded/framework/lib/msf/core/module_set.rb:245:in `each'
         6: from C:/metasploit-framework/embedded/framework/lib/msf/core/module_set.rb:272:in `block in each_module_list'
         5: from C:/metasploit-framework/bin/../embedded/framework/msfvenom:350:in `block in dump_payloads'
         4: from C:/metasploit-framework/bin/../embedded/framework/msfvenom:350:in `new'
         3: from C:/metasploit-framework/embedded/framework/modules/payloads/singles/cmd/unix/reverse_ssh.rb:17:in `initialize'
         2: from C:/metasploit-framework/embedded/framework/lib/msf/base/sessions/command_shell_options.rb:16:in `initialize'
         1: from C:/metasploit-framework/embedded/framework/lib/msf/core/handler/reverse_ssh.rb:44:in `initialize'
C:/metasploit-framework/embedded/framework/lib/rex/proto/ssh/connection.rb:63:in `default_options': uninitialized constant HrrRbSsh::Authentication (NameError)
```

2020-12-16 17:32 UTC, adfoster-r7 commented
Alternative PR to eagerly load the ssh dependencies, rather than defer execution:
https://github.com/rapid7/metasploit-framework/pull/14525

Long term we'll want a better solution as we continue to migrate to deferring the loading of dependencies, but hoping to get an initial fix in before the next release

2020-12-18 10:40 UTC, dwelch-r7 commented
Superseded by #14525

2020-12-18 10:40 UTC, closed without merging