Add exploit for Micro Focus UCMDB unauthenticated RCE
rapid7/metasploit-framework pull request #14654
Opened 2021-01-24 15:39 UTC by pedrib

This module adds a new exploit for CVE-2020-11853 and 11854. It is an unauthenticated remote code execution chain that affects Micro Focus UCMDB, which is embedded in many Micro Focus products.

It seems MF doesn't offer this version for download any more, so I should send a pcap to you?

## Verification

1. Install the application
2. Start msfconsole
3. `use exploit/multi/http/microfocus_ucmdb_unauth_deser`
4. `set rhost TARGET'
5. `set lhost YOUR_IP`
6. `set target 0|1`
7. `run`
8. You should get a shell.

**NOTE: as I have said before [in my previous PR](https://github.com/rapid7/metasploit-framework/pull/13604), Metasploit ysoserial Linux payloads are currently BROKEN! Only cmd/unix/generic works, none of the others work. This module ideally should run with cmd/unix/reverse_python**

2021-01-25 14:22 UTC, smcintyre-r7 requested changes
I just left a couple of comments based on my review. Everything looks pretty good. If the software can't be downloaded then you're right, we'll want to have a PCAP sent to use for review. If you wouldn't mind, can you send that to me at smcintyre [at] metasploit.com.

I'll take a look and see if I can figure out that YSoSerial issue this week. Thanks!

2021-01-25 14:22 UTC, smcintyre-r7 commented on modules/exploits/multi/http/microfocus_ucmdb_unauth_deser.rb
> +      return Exploit::CheckCode::Detected
When doing a version check we try to use `Exploit::CheckCode::Appears` while reserving `Exploit::CheckCode::Vulnerable` for cases in which we can safely trigger the vulnerability to validate its presence. This would be the case if you tried the default credentials here.

Also the case in which it returns Detected seems a little loose. As long as it's a 200 OK response to that GET request it'll get to this point if the version is missing. Is there some other kind of unique string you could check for in here that would serve as a more specific detection? Even `res.body.include?('ServerVersion=')` would probably be better in case the version is different. "ServerVersion" is a little generic though but without the application I can't make a better suggestion.

2021-01-25 14:22 UTC, smcintyre-r7 commented on modules/exploits/multi/http/microfocus_ucmdb_unauth_deser.rb
> +      'uri' => normalize_uri('ucmdb-api', 'connect'),
This doesn't use the `TARGETURI` datastore option while other usages of `send_request_(cgi|raw)` do. It looks like the `TARGETURI` should be updated to use a default value of simply `'/'`, and then this should be:

```suggestion
        'uri' => normalize_uri(target_uri.path, 'ucmdb-api', 'connect')
```

The other two instances on L115 and L179 will need to be updated too using `... normalize_uri(target_uri.path, 'ucmdb-ui', ....)`

2021-01-25 15:27 UTC, pedrib commented
@smcintyre-r7 all done, thanks for reviewing!
I added an additional check when authenticating - if the server doesn't return a LWSSO_COOKIE_KEY, we bail out. 
Decided against doing the authentication when using check() as that might be too noise for IPS purposes.

Sending the pcaps to your email now!

2021-01-27 15:00 UTC, merged

2021-01-27 15:01 UTC, smcintyre-r7 commented
Thanks for update the code! That check method looks much better now. I reran the unit tests and the only one that is failing right now is the "Verify / Docker Build" job which is unrelated to this PR.

I received and reviewed the PCaps you sent, thanks for that as well. The traffic is all encrypted, which I missed from the module info. Based on the size of the traffic and order of connections though it looks right.

I made a couple of tweaks to the markdown documentation in fc6957fbf689910c1d6e553cf60a194cb02b7ce5. Added a couple of new lines so the bullet points would render and wrapped some lines at 120 chars.

With that, this PR has been merged. Thanks a lot @pedrib!

2021-01-27 15:04 UTC, smcintyre-r7 commented
# Release Notes
This adds an exploit module that combines two vulnerabilities in the Micro Focus UCMDB application. The first vulnerability is a set of hardcoded credentials, which are used to authenticate and access the second vulnerability which is insecure deserialization of user-controlled data. These vulnerabilities are identified as CVE-2020-11853 and CVE-2020-11854.

2021-01-28 09:19 UTC, pedrib commented
Thank you!