payload/x86/exec.rb - refactoring, metasm, new NullFreeVersion option
rapid7/metasploit-framework pull request #14661
Opened 2021-01-26 18:06 UTC by geyslan

## Changes

As proposed in PR https://github.com/rapid7/metasploit-framework/pull/14636 comments.

`commit 34223874b657e02066e24cd9dfc96769e052d2ff`

Converts shellcode to metasm and adds new behaviour to CMD option.

Now if CMD is empty or unset, a 20 byte not null-free execve payload is build. The arbitrary command option continues the same when CMD is set.

`commit 4ed8bd80526f4741f853fdd9d61fedc206f342dd`

Adds the OptBool NullFreeVersion advanced option.

Its default value is false. When set as true, generate will output a self included null-free version of the payload without need of encoding.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use payload/linux/x86/exec`
- [ ] `options`
- [ ] `advanced`
- [ ] `unset CMD`
- [ ] Test it `generate -f elf -o exec32.elf`
- [ ] `set NullFreeVersion true`
- [ ] Test it `generate -f elf -o exec32.elf`
- [ ] `set NullFreeVersion false`
- [ ] `set CMD uname -a`
- [ ] Test it `generate -f elf -o exec32.elf`
- [ ] `set NullFreeVersion true`
- [ ] Test it `generate -f elf -o exec32.elf`

![image](https://user-images.githubusercontent.com/3372117/105885334-c741e280-5fe7-11eb-827c-662307778dd2.png)

2021-02-15 20:38 UTC, geyslan commented
Ping.
Is this in consideration? There's no label.

2021-02-23 01:28 UTC, gwillcox-r7 commented
@geyslan Sorry for the delay on this, I think the team had some considerations r.e this PR that needed to be discussed further. Let me check in with them r.e this and I'll get back to you by EOD tomorrow with an update.

2021-02-23 15:21 UTC, gwillcox-r7 commented
Alright so general quick opinion on this similar to what was discussed previously in the last PR, which is that the option to have an advanced option that module authors have to explicitly set to have a NULL free payload is not ideal as this requires more configuration on the module authors end and they may not be aware that only this payload has it and that its not across the board, which can lead to confusion due to differing standards.

The other point that I have from a quick inspection is the fact that you are adding `/bin/sh` before the command to be executed even though the command is entirely dependent on the module it is being used in, and really the user should be adding in things like `/bin/sh` or what not to their command to be executed, as they may not want to use this interpreter, the interpreter may not exist, or they may be using this in a restricted environment of some sort where `/bin/sh` doesn't exist on the system. By forcing them to this interpreter you are potentially breaking existing modules that we have here and also limiting the scope in which these payloads can be utilized.

I am also not sure given this module's history that adding in the option to generate a default payload that just spawns a command shell is helpful. Given that this would just spawn a command shell that the user couldn't interact with, and given the history of this shellcode requiring a `CMD` option, I don't think this change makes much sense in my eyes in terms of the usefulness in the broader framework.

2021-02-24 12:44 UTC, geyslan commented
> Alright so general quick opinion on this similar to what was discussed previously in the last PR, which is that the option to have an advanced option that module authors have to explicitly set to have a NULL free payload is not ideal as this requires more configuration on the module authors end and they may not be aware that only this payload has it and that its not across the board, which can lead to confusion due to differing standards.

I see. So no module extra options. I will let that topic rest in peace.

> 
> The other point that I have from a quick inspection is the fact that you are adding `/bin/sh` before the command to be executed even though the command is entirely dependent on the module it is being used in, and really the user should be adding in things like `/bin/sh` or what not to their command to be executed, as they may not want to use this interpreter, the interpreter may not exist, or they may be using this in a restricted environment of some sort where `/bin/sh` doesn't exist on the system. By forcing them to this interpreter you are potentially breaking existing modules that we have here and also limiting the scope in which these payloads can be utilized.

That is the original exec.rb functionality. It makes use of `/bin/sh` [\x68\x2f\x73\x68\x00\x68\x2f\x62\x69\x6e](https://github.com/rapid7/metasploit-framework/blob/master/modules/payloads/singles/linux/x86/exec.rb#L43)

So the potential break is already in the module. But that could be avoided building a fully dynamic payload. The downside of a fully dynamic execve shellcode is the need of parsing the args what demands an dynamic array of pointers that certainly would increase the payload size.

> 
> I am also not sure given this module's history that adding in the option to generate a default payload that just spawns a command shell is helpful. Given that this would just spawn a command shell that the user couldn't interact with, and given the history of this shellcode requiring a `CMD` option, I don't think this change makes much sense in my eyes in terms of the usefulness in the broader framework.

I see your point. What I thought adding this functionality was to make possible to get ready shellcodes from msf for external use. But if the CMD is truly dynamic as mentioned above, the payload could be built to `execve()` any CMD with or without arguments. Eg.

`set CMD /bin/sh`
would dynamically build a call to
`execve("/bin/sh", NULL, NULL)` **Smaller payload - easy to make**

`set CMD /bin/uname -v -m`
would dynamically build a call to
`execve("/bin/uname", ["/bin/uname", "-v", "m"], NULL)`

`set CMD /bin/bash -c uname -v -m`
would dynamically build a call to
`execve("/bin/bash", ["/bin/bash", "-c", "uname -v -m"], NULL)`

And again the complexity would increase, since we don't know when to break or not the args for different binaries.

2021-03-11 14:57 UTC, smcintyre-r7 requested changes
I still think that an ideal solution would include propagating the bad character information to the payload generation routine for a first attempt at avoiding back characters before the encoder is even invoked. Adding a `NullFreeVersion` option seems redundant with our integrated capability of specifying an array of bad characters. Since this isn't feasible right now though this seems like a reasonable change.

I just left a couple of comments regarding the code and once addressed, I'll get to testing this out. Thanks a lot for the improvements and porting it over to metasm!

2021-03-11 14:57 UTC, smcintyre-r7 commented on modules/payloads/singles/linux/x86/exec.rb
> +    if !cmd.empty?
Instead of using this pattern of *if not some condition ... else*, the blocks should really be inverted for readability to just be *if some condition ... else* where the contents of the blocks are swapped. This pattern is seen throughout this function where the `!cmd.empty?` and `!nullfreeversion` expressions are used.

2021-03-11 14:57 UTC, smcintyre-r7 commented on modules/payloads/singles/linux/x86/exec.rb
> +    nullfreeversion = datastore['NullFreeVersion'] || false
This shouldn't be necessary since `false` is defined as a default value in the module store. Since this is a boolean and you do need to know whether or not the NULL-free version should be used, it makes sense to change it to being a required option (`OptBool.new('NullFreeVersion', [ true, ...`) and keep the default of `false`.

2021-03-11 21:28 UTC, geyslan commented on modules/payloads/singles/linux/x86/exec.rb
> +    nullfreeversion = datastore['NullFreeVersion'] || false
`NullFreeVersion` as `required` wouldn't demand it as an `register_options` instead of `register_advanced_options`?

2021-03-11 22:20 UTC, geyslan commented
> I just left a couple of comments regarding the code and once addressed, I'll get to testing this out.

@smcintyre-r7 just done it. :heavy_check_mark: 

> Thanks a lot for the improvements and porting it over to metasm!

You're welcome. :100:

2021-03-12 17:02 UTC, smcintyre-r7 approved these changes

2021-03-12 17:02 UTC, smcintyre-r7 commented
Tested it all out and everything is working as expected. The NULL version generates and is smaller, the NULL-free version also generates and is larger but contains no NULL characters. Both payloads execute as expected.

On the topic of this using `/bin/sh`, I think the behavior is reasonable for a couple of reasons, it's the most common shell that will be available, executes the OS command in an environment that the user is most likely expecting and finally / most importantly it maintains compatibility with the original version.

<details>
<summary>Testing Output</summary>

```
msf6 exploit(windows/smb/psexec) > use payload/linux/x86/exec 
msf6 payload(linux/x86/exec) > show options 

Module options (payload/linux/x86/exec):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------
   CMD                    no        The command string to execute

msf6 payload(linux/x86/exec) > set CMD id
CMD => id
msf6 payload(linux/x86/exec) > generate -f ruby
# linux/x86/exec - 38 bytes
# https://metasploit.com/
# VERBOSE=false, PrependFork=false, PrependSetresuid=false, 
# PrependSetreuid=false, PrependSetuid=false, 
# PrependSetresgid=false, PrependSetregid=false, 
# PrependSetgid=false, PrependChrootBreak=false, 
# AppendExit=false, MeterpreterDebugLevel=0, 
# RemoteMeterpreterDebugFile=, CMD=id, NullFreeVersion=false
buf = 
"\x6a\x0b\x58\x99\x52\x66\x68\x2d\x63\x89\xe7\x68\x2f\x73" +
"\x68\x00\x68\x2f\x62\x69\x6e\x89\xe3\x52\xe8\x03\x00\x00" +
"\x00\x69\x64\x00\x57\x53\x89\xe1\xcd\x80"
msf6 payload(linux/x86/exec) > generate -f elf -o /tmp/payload.x86
[*] Writing 122 bytes to /tmp/payload.x86...
msf6 payload(linux/x86/exec) > set NullFreeVersion true
NullFreeVersion => true
msf6 payload(linux/x86/exec) > generate -f ruby
# linux/x86/exec - 49 bytes
# https://metasploit.com/
# VERBOSE=false, PrependFork=false, PrependSetresuid=false, 
# PrependSetreuid=false, PrependSetuid=false, 
# PrependSetresgid=false, PrependSetregid=false, 
# PrependSetgid=false, PrependChrootBreak=false, 
# AppendExit=false, MeterpreterDebugLevel=0, 
# RemoteMeterpreterDebugFile=, CMD=id, NullFreeVersion=true
buf = 
"\x31\xdb\xf7\xe3\xb0\x0b\x52\x66\x68\x2d\x63\x89\xe7\xeb" +
"\x1b\x5e\xb3\x02\x88\x14\x1e\x52\x68\x2f\x2f\x73\x68\x68" +
"\x2f\x62\x69\x6e\x89\xe3\x52\x56\x57\x53\x89\xe1\xcd\x80" +
"\xe8\xe0\xff\xff\xff\x69\x64"
msf6 payload(linux/x86/exec) > generate -f elf -o /tmp/payload.x86
[*] Writing 133 bytes to /tmp/payload.x86...
msf6 payload(linux/x86/exec) > set CMD uname -a
msf6 payload(linux/x86/exec) > generate -f elf -o /tmp/payload.x86
[*] Writing 139 bytes to /tmp/payload.x86...
msf6 payload(linux/x86/exec) > info

       Name: Linux Execute Command
     Module: payload/linux/x86/exec
   Platform: Linux
       Arch: x86
Needs Admin: No
 Total size: 55
       Rank: Normal

Provided by:
  vlad902 <vlad902@gmail.com>
  Geyslan G. Bem <geyslan@gmail.com>

Basic options:
Name  Current Setting  Required  Description
----  ---------------  --------  -----------
CMD   uname -a         no        The command string to execute

Description:
  Execute an arbitrary command or just a /bin/sh shell


msf6 payload(linux/x86/exec) >
```
</details>

I'll have this landed shortly. Thanks!

2021-03-12 17:03 UTC, merged

2021-03-12 17:04 UTC, smcintyre-r7 commented
# Release Notes
This updates the `linux/x86/exec` payload to now use metasm, making the source code more readable and adds a new, larger NULL byte free variant.