Require rubocop for new modules
rapid7/metasploit-framework pull request #14735
Opened 2021-02-10 00:40 UTC by adfoster-r7

Note that the rubocop file change is from https://github.com/rapid7/metasploit-framework/pull/14733 - once that is landed, this will be rebased and the commit will no longer appear in this PR

This PR require Rubocop to pass for new modules as part of our CI setup

**Note** - Once merged PR is merged it may cause issues for old pull requests that get landed after the fact. It could make sense to merge this when there are less pull requests in flight, or force all inflight pull requests to rebase.

## Verification

I will test these scenarios and attach screenshots:

- Ensure that a very old module doesn't require being rubocopped - to avoid noisey pull requests for bug fixes. In an ideal world contributors could put up a pre-requisite PR for purely running rubocop, then a separate PR for any bug fixes - or two commits. It's unlikely this would happen though.
- Ensure that a newly created module requires being rubocop
- Ensure that modifying a recently created module requires rubocop to pass
- Ensure that the previous msftidy semantics are enforced and honored

2021-02-10 00:54 UTC, adfoster-r7 commented on .github/workflows/verify.yml
> +        # in parallel.
Extracting msftidy to run in a separate job has the added benefit of running slightly faster overall, but we could in theory automagically write comments letting users know that their linting needs fixed:

```
  - name: Notify user of lint failure
    if: ${{ failure() }}
    uses: actions/github-script@v3
    with:
      github-token: ${{secrets.GITHUB_TOKEN}}
      script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-linting']
            })

  - name: Notify user of lint success
    if: ${{ failure() }}
    uses: actions/github-script@v3
    with:
      github-token: ${{secrets.GITHUB_TOKEN}}
      script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'needs-linting'
            })
```

If bots trigger bots that is, will investigate 👀

2021-02-10 01:50 UTC, adfoster-r7 commented on .github/workflows/verify.yml
> +        # in parallel.
Looks like actions can trigger bots on pull requests where the branch is from the same repo

![image](https://user-images.githubusercontent.com/60357436/107453146-54397f80-6b42-11eb-936c-163cef3eaea7.png)

Will have to investigate the permissions of third party pull requests.

2021-02-10 03:14 UTC, adfoster-r7 commented on .github/workflows/verify.yml
> +        # in parallel.
Looks like using the new `pull_request_target` event wouldn't quite work as we want to use the workflow from master, but the code from a branch - which would expose the github token with write access as an environment variable. Will investigate further

https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

2021-02-10 12:27 UTC, adfoster-r7 commented on .github/workflows/verify.yml
> +        # in parallel.
This is definitely possible, but will extract that effort from this PR for now:

<details>
<summary>WIP changes</summary>

```yaml
name: Lint

on:
  push:
    branches-ignore:
      - gh-pages
      - metakitty
  # Note this is 'pull_request_target' and _not_ 'pull_request' for security reasons of having write tokens:
  #   https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
  # This means that a pull request's workflow will not run, but rather the one that's been committed to master.
  pull_request_target:
    branches:
      - '*'
    types: [synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-16.04
    timeout-minutes: 40

    strategy:
      fail-fast: true
      matrix:
        ruby:
          - 2.5

    name: Lint ${{ matrix.ruby }}
    steps:
     # ...

      - name: Notify user of lint success
        if: ${{ success() }}
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-linting']
            })

      - name: Notify user of lint failure
        if: ${{ failure() }}
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-linting']
            })

```
</details>

2021-02-23 22:44 UTC, gwillcox-r7 requested changes
Couple of minor changes but this mostly looks good to land, nice work!

2021-02-23 22:44 UTC, gwillcox-r7 commented on tools/dev/msftidy.rb
> +  # @return [Integer] RubCop::CLI status code
I think this meant to be `RuboCop::CLI` here vs `RubCop::CLI`?
```suggestion
  # @return [Integer] RuboCop::CLI status code
```

2021-02-23 22:58 UTC, adfoster-r7 commented on .github/workflows/lint.yml
> +            ${{ runner.os }}-gems-
There's no strong technical reasons for this - really it's just to be consistent within the rest of the file when multiline commands are required, and the ease of which additional lines can be added in the future without creating a large diff in a PR :+1:

2021-02-23 22:59 UTC, adfoster-r7 commented on spec/tools/dev/rubocop_runner_spec.rb
> +      expect(@stdout).to match 'no offenses detected'
The `match` matcher also works with strings :+1:

2021-02-23 23:02 UTC, adfoster-r7 commented on spec/tools/dev/rubocop_runner_spec.rb
> +      expect(@stdout).to match 'no offenses detected'
Extra context, this ends up calling the Ruby's `match?` method:
> match?(*args) public
> Converts pattern to a Regexp (if it isn’t already one), then returns a true or false 

Resources:
https://apidock.com/ruby/v2_5_5/String/match%3F
https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/match-matcher

2021-02-23 23:02 UTC, adfoster-r7 commented on spec/tools/dev/rubocop_runner_spec.rb
> +      expect(@stdout).to match 'Rubocop failed'
https://github.com/rapid7/metasploit-framework/pull/14735/files#r581373056

2021-02-23 23:04 UTC, bcoles commented on spec/tools/dev/rubocop_runner_spec.rb
> +      expect(@stdout).to match 'Rubocop failed'
Looks like a static string which should be fine (?)

2021-02-23 23:07 UTC, adfoster-r7 commented on spec/tools/dev/msftidy_runner_spec.rb
> +      expect(@msftidy_stdout).to match(/ERROR.*Invalid super class for auxiliary module/)
This was existing msftidy test logic, but converted over! 🕵️

2021-02-24 03:04 UTC, gwillcox-r7 commented on spec/tools/dev/rubocop_runner_spec.rb
> +      expect(@stdout).to match 'no offenses detected'
Thought so just found it odd that earlier it was a regex pattern vs now when it was a string. Not major though and I was considering taking this out of the review comments anyway so going to mark this as resolved.

2021-02-24 03:05 UTC, gwillcox-r7 commented on spec/tools/dev/rubocop_runner_spec.rb
> +      expect(@stdout).to match 'Rubocop failed'
Yep see previous comment on the issue above, this is fine as mentioned. Marking resolved.

2021-02-24 03:08 UTC, gwillcox-r7 commented on .github/workflows/lint.yml
> +            ${{ runner.os }}-gems-
Sounds good, thought this was more of a stylistic thing than any major issue. Your point about a large diff is valid and something I didn't think of which makes me realize this styling makes more sense for long term maintainability. Marking as resolved.

2021-02-24 03:09 UTC, gwillcox-r7 commented on spec/tools/dev/msftidy_runner_spec.rb
> +      expect(@msftidy_stdout).to match(/ERROR.*Invalid super class for auxiliary module/)
Ah woops, well at least its fixed now 😄

2021-02-24 03:10 UTC, gwillcox-r7 approved these changes

2021-02-24 03:13 UTC, merged

2021-02-24 03:16 UTC, gwillcox-r7 commented
# Release Notes
Updates have been made to require all new modules to now pass RuboCop and msftidy.rb checks prior to being merged into the framework. These checks will now be run automatically on PRs to detect issues rather than users having to run these tools manually to detect code quality issues within their contributions.