Emby ssrf
rapid7/metasploit-framework pull request #14836
Opened 2021-03-01 20:46 UTC by btnz-k

## Verification

List the steps needed to make sure this thing works

Version Checker: 

- [ ] Start `msfconsole`
- [ ] `auxiliary/scanner/emby_version`
- [ ] Set the RHOST as the vulnerable server IP/Hostname and run (modify RPORT if needed).
- [ ] Module will output the version information gleaned or will return not vulnerable. Notes will be updated.
- [ ] Module does not take any further action.
- [ ] ([Documentation](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/auxiliary/scanner/emby_version.md))

SSRF Scanner: 

- [ ] Start `msfconsole`
- [ ] `use auxiliary/scanner/http/emby_scan`
- [ ] Set the EMBY_PORT and EMBY_SERVER as the vulnerable server IP/Hostname and port.
- [ ] Set the PORT field for ports to check internally.
- [ ] Set RHOSTS as the internal IP addresses to check for.
- [ ] Module will attempt to connect on each port that is listed for each IP address and will return the HTTP Title as a note.
- [ ] Module does not take any further action.
- [ ] ([Documentation](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/auxiliary/scanner/http/emby_scan.md))

2021-03-01 22:20 UTC, h00die commented
Looks like it still also needs a `rubocop -a` run to clean the module up and hopefully get the checks to pass.

2021-03-01 22:20 UTC, h00die commented
My infrastructure should be back up by weeks end, if this is still in need of a review by then, I'll take it

2021-03-01 23:14 UTC, btnz-k commented
Working on updating the required changes per rubocop and h00die's comments.

2021-03-01 23:49 UTC, btnz-k commented
Hey there, can you provide the version of rubocop you're using, or the ruleset? I'm getting a mismatch on how many errors when running it locally. 

Here's my version info, using default rules:

`apt info rubocop
Package: rubocop
Version: 0.89.1+dfsg-1
Priority: optional
Section: ruby
Maintainer: Debian Ruby Extras Maintainers <pkg-ruby-extras-maintainers@lists.alioth.debian.org>
Installed-Size: 2,447 kB
Depends: ruby, ruby-parallel (>= 1.10), ruby-whitequark-parser (>= 2.7.1.1), ruby-rainbow (>= 2.2.2), ruby-rainbow (<< 4.0), ruby-regexp-parser (>= 1.7), ruby-rubocop-ast (>= 0.3.0), ruby-rubocop-ast (<< 1.0), ruby-progressbar (>= 1.7), ruby-unicode-display-width (>= 1.4.0), ruby-unicode-display-width (<< 2.0)
Homepage: https://github.com/rubocop-hq/rubocop
Ruby-Versions: all
Download-Size: 441 kB
APT-Manual-Installed: yes
APT-Sources: http://http.kali.org/kali kali-rolling/main amd64 Packages`

2021-03-01 23:52 UTC, bcoles commented
> Hey there, can you provide the version of rubocop you're using, or the ruleset? I'm getting a mismatch on how many errors when running it locally.

The rubocop version is pinned in [Gemfile.lock](
https://github.com/rapid7/metasploit-framework/blob/053853a86c986705f12a8c0ad54f1b9947c1ce71/Gemfile.lock#L384):

https://github.com/rapid7/metasploit-framework/blob/053853a86c986705f12a8c0ad54f1b9947c1ce71/Gemfile.lock#L384

The rules are defined in [.rubocop.yml](https://github.com/rapid7/metasploit-framework/blob/master/.rubocop.yml).

2021-03-02 16:07 UTC, btnz-k commented
> 
> 
> Please update the documentation to show a successful exploitation (or output) of a vulnerable device. I didn't see any, so I'm not sure what success looks like

I've added successful execution examples in the scenarios portion of the documentation.

2021-03-07 17:55 UTC, h00die requested changes
Just a quick review without setting up the software or running the module..  You'll want to address the module stuff before the doc stuff as the docs will most likely need updates.


I'll also note this looks to be the first module of its type, using an SSRF as a scanner.  Looks like only 1 other module even mentions SSRF, so congrats on a first of its kind module!

2021-03-07 17:55 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version.rb
> +##
I would move this to `emby_version_ssrf` since its using SSRF to determine the version.

2021-03-07 17:55 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version.rb
> +# This module requires Metasploit: https://metasploit.com/download
see other module comments about this comment block

2021-03-07 17:55 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version.rb
> +# msf::aux class
see other module comments

2021-03-07 17:55 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version.rb
> +# frozen_string_literal: true
see other module comments

2021-03-07 17:55 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version.rb
> +      'Version' => '1.0.2021.03.01.01',
see other module comments

2021-03-07 17:55 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version.rb
> +    )
see other module comments about adding reference section, disclosure date, etc

2021-03-07 17:55 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version.rb
> +    deregister_options('VHOST', 'FILTER', 'INTERFACE', 'PCAPFILE', 'SNAPLEN', 'SSL')
why deregister ssl and vhost? the others aren't loaded because capture isnt incliuded.

2021-03-07 17:55 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version.rb
> +  def to
don't believe this is necessary

2021-03-07 17:55 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version.rb
> +    })
`}, datastore['TIMEOUT'])`
https://rapid7.github.io/metasploit-framework/api/Msf/Exploit/Remote/HttpClient.html#send_request_cgi-instance_method

2021-03-07 17:55 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version.rb
> +            Based on the vulnerability CVE-2020-26948.
This doesn't seem to use the CVE

2021-03-07 17:55 UTC, h00die commented on documentation/modules/auxiliary/scanner/emby_scan.md
> +## Vulnerable Application
suggest running `tools/dev/msftidy_docs` on this file

2021-03-07 17:55 UTC, h00die commented on documentation/modules/auxiliary/scanner/emby_scan.md
> +### Emby Scan Internal 192.168.1.0 Network
This should include the Emby version and OS in the H3 title

2021-03-07 17:55 UTC, h00die commented on documentation/modules/auxiliary/scanner/emby_scan.md
> +Example with found host with port 80 open, returned server version and title.
not needed

2021-03-07 17:55 UTC, h00die commented on documentation/modules/auxiliary/scanner/http/emby_version.md
> +Generates an API request to the provided ip addresses in order to ascertain the Emby server version, if possible. Returns the server version, URI, and internal IP address (if provided). This is usefu
first IP isn't capitalized, but 2nd is. suggest capitalizing.

2021-03-07 17:55 UTC, h00die commented on documentation/modules/auxiliary/scanner/http/emby_version.md
> +## Vulnerable Application
suggest running `tools/dev/msftidy_docs` on this file

2021-03-07 17:55 UTC, h00die commented on documentation/modules/auxiliary/scanner/http/emby_version.md
> +This shows a successful scan of an Emby server using the API, and returns the URI, version, and Internal IP information.
not needed

2021-03-07 17:55 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version.rb
> +    report_service(
why not throw in something like:
```
print_good("Vulnerable to SSRF module auxiliary/scanner/...") if Rex::Version.new(version) < Rex::Version.new('4.5.0')
```

2021-03-07 17:55 UTC, h00die commented on modules/auxiliary/scanner/emby_scan.rb
> +
by chance does non-vulnerable Emby give back a response which would let you know the version isn't vulnerable and therefore the module could bail out?
For instance:
vuln version port open: 200 response
vuln version port closed: 404 response
non-vulnerable version: 500 response

2021-03-08 23:26 UTC, btnz-k commented
I'll be working on these fixes over the next week or two. Thanks for the feedback, @h00die!

2021-03-08 23:32 UTC, h00die commented
No rush, all good!

2021-03-09 01:19 UTC, btnz-k commented on modules/auxiliary/scanner/emby_scan.rb
> +    deregister_options('VHOST', 'RPORT', 'FILTER', 'INTERFACE', 'PCAPFILE', 'SNAPLEN', 'SSL')
So the EMBY server uses httpclient as well, but hardcodes http and any and all https end up failing. Since that's on the EMBY server side, i opted to remove SSL to prevent issues user-side.

2021-03-26 19:33 UTC, btnz-k commented on modules/auxiliary/scanner/emby_scan.rb
> +  include Msf::Exploit::Capture
removed

2021-03-26 19:35 UTC, btnz-k commented on modules/auxiliary/scanner/emby_scan.rb
> +        OptString.new('EMBY_SERVER', [true, 'IP to scan (eg 10.10.10.18))', '']),
updated

2021-03-27 14:22 UTC, h00die commented
Just let me know when you're all done and ready for review!

2021-04-08 20:12 UTC, h00die commented
@btnz-k just wanted to check in on this

2021-04-08 20:19 UTC, btnz-k commented
@h00die - still working it between my day job and life. hoping to devote some time to cleanup this weekend.

2021-04-28 17:51 UTC, btnz-k commented on modules/auxiliary/scanner/http/emby_version.rb
> +    deregister_options('VHOST', 'FILTER', 'INTERFACE', 'PCAPFILE', 'SNAPLEN', 'SSL')
Due to httpclient on the server side (emby) not allowing for ssl based relays, i opted to remove the option from the module to prevent confusion or issues trying to hit ssl based webpages as it will error out.

2021-04-28 18:02 UTC, btnz-k commented on modules/auxiliary/scanner/http/emby_version.rb
> +            Based on the vulnerability CVE-2020-26948.
updated phrasing

2021-04-28 19:38 UTC, btnz-k commented on modules/auxiliary/scanner/emby_scan.rb
> +
Unfortunately, it does not. Emby will sit and attempt to load up the page, and end up resulting in a timeout.

2021-04-28 21:03 UTC, btnz-k commented
I believe all change requests have been fulfilled. Please let me know if there are any additional changes that need to be made!

2021-05-05 23:30 UTC, h00die commented
awesome, thanks for the update, I'll check it out in the coming days!

2021-05-10 02:45 UTC, h00die requested changes
`emby_version_ssrf` has 3 rubocop issues, run `tools/dev/msftidy.rb` on it after that.
`emby_ssrf_scanner` has 4 rubocop issues, run `tools/dev/msftidy.rb` on it after that.
`emby_ssrf_scanner` needs to be moved into the `http` folder

2021-05-10 02:52 UTC, h00die commented
### 4.4.3.0
Looks good
```
msf6 auxiliary(scanner/http/emby_version_ssrf) > run

[*] Identifying Media Server Version on 1.1.1.1:8096     
[+] [Media Server] URI: http://1.1.1.1:8096/
[+] [Media Server] Version: 4.4.3.0
[+] [Media Server] Internal IP: http://1.1.1.1:8096
[+] *** Vulnerable to SSRF module auxiliary/scanner/emby_ssrf_scanner! ***
[*] Saving host information.
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

### 4.5.0.50
Gets the version number.  However, I think `Internal IP` shouldn't be printed if it isn't detected.
```
msf6 auxiliary(scanner/http/emby_version_ssrf) > run

[*] Identifying Media Server Version on 1.1.1.1:8096     
[+] [Media Server] URI: http://1.1.1.1:8096/
[+] [Media Server] Version: 4.5.0.50
[+] [Media Server] Internal IP: 
[*] Saving host information.
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

2021-05-10 03:28 UTC, h00die requested changes
a few review comments.

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version_ssrf.rb
> +      'Name' => 'Emby Version Checker',
I believe the nomenclature is Scanner, not Checker

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version_ssrf.rb
> +      'Disclosure Date' => 'September 1 2020',
wrong format

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version_ssrf.rb
> +      'Description' => 'This module attempts to identify the version of an Emby Media Server running on a host. If you wish to see all the information available, set VERBOSE to true. Use in conjuncti
line too long

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version_ssrf.rb
> +        OptString.new('BASEPATH', [true, 'The base path, usually just /', '/']),
Should be `TARGETURI` for consistency.
https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/example_webapp.rb#L78

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/emby_ssrf_scanner.rb
> +      ]
Need to add in a `TARGETURI`.  While very unlikely to have one, better to add it now.
https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/example_webapp.rb#L78

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version_ssrf.rb
> +      vprint_error('[Emby Version] failed to connect')
I would change this to something along the lines of ```print_error('Failed to connect to an Emby Server')```

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version_ssrf.rb
> +    print_good("[Media Server] Internal IP: #{result['LocalAddress']}")
per notes, only print this line if `LocalAddress` has a value

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version_ssrf.rb
> +    print_good("[Media Server] URI: http://#{ip}:#{rport}#{datastore['BASEPATH']}")
you can use `#{peer}` instead of `#{ip}:#{rport}`

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version_ssrf.rb
> +    print_good("*** Vulnerable to SSRF module auxiliary/scanner/emby_ssrf_scanner! ***") if Gem::Version.new("#{result['Version']}") < Gem::Version.new('4.5.0')
Since this could be threaded, I would add peer to this printout.

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version_ssrf.rb
> +    print_status "All info: #{result}" if datastore['VERBOSE']
`vprint_status` is the equivalent of `print_status` with an `if` check

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/http/emby_version_ssrf.rb
> +    print_status('Saving host information.')
This is prob better as a `vprint_status`

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/emby_ssrf_scanner.rb
> +        OptBool.new('STORE_NOTES', [true, 'Store the information in notes. Use "notes -t http.title" to view', true]),
I think you can take out the "Use" part here, it would be better in the markdown docs

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/emby_ssrf_scanner.rb
> +        OptString.new('EMBY_SERVER', [true, 'Emby Web UI IP to use (e.g. 10.10.10.18))', '']),
no eg needed

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/emby_ssrf_scanner.rb
> +        OptInt.new('EMBY_PORT', [true, 'Web UI port for Emby Server (e.g. 8096)', '8096']),
no eg needed here

2021-05-10 03:28 UTC, h00die commented on documentation/modules/auxiliary/scanner/emby_ssrf_scanner.md
> +Select which ports to check for HTTP servers internal to the Emby server. Defaults to 80, 8080, 8081, 8888.
wrap the defaults in ticks (`). Also, remove the spaces in that list

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/emby_ssrf_scanner.rb
> +    # loop through the IPs
IPs or ports?

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/emby_ssrf_scanner.rb
> +      res = Net::HTTP.get_response(datastore['EMBY_SERVER'], uri, datastore['EMBY_PORT'])
I take it youre using this since `send_request_cgi` would use `rhosts` instead of `EMBY_SERVER`.
If so, add a comment in the code just saying that for future code readers.

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/emby_ssrf_scanner.rb
> +#      })
can be removed

2021-05-10 03:28 UTC, h00die commented on modules/auxiliary/scanner/emby_ssrf_scanner.rb
> +      end
I would slightly re-arrange this.
```
      if rx[:title].empty?
        vprint_error("#{target_host}:#{p} No webpage title")
        next
      end     

      rx_title = Rex::Text.html_decode(rx[:title])
      if datastore['SHOW_TITLES']
        print_good("#{target_host}:#{p} Title: #{rx_title}")
        print_good("#{target_host}:#{p}     HTTP Code: #{res.code}")
        print_good("#{target_host}:#{p}     Location Header: #{location_header}")
        print_good("#{target_host}:#{p}     Server Header: #{server_header}")
      end
      if datastore['STORE_NOTES']
        notedata = { code: res.code, port: p, server: server_header, title: rx_title, redirect: location_header }
        report_note(host: target_host, port: p, type: 'http.title', data: notedata, update: :unique_data)
      end
```

Bails early, unindents a block of code. Also avoids `if not empty` for `if empty` which is slightly less double negative.

2021-05-11 15:33 UTC, btnz-k commented
Thanks for the corrections, I'll be working them soon!

2021-05-12 19:35 UTC, h00die commented
Just wanted to say, don't get discouraged by the amount of changes.  Most of them will only take a minute or two each.

2021-05-12 19:36 UTC, btnz-k commented
Thanks! Appreciated :)

2021-06-03 20:16 UTC, btnz-k commented
I believe these issues have all been addressed!

2021-06-06 16:01 UTC, h00die commented
Thanks for the code push, I'll get to this when I have some time

2021-06-06 16:28 UTC, h00die commented
Please run `rubocop -a` on your code

2021-06-09 19:37 UTC, h00die requested changes
3 quick easy changes:
1. an optbool needs to be an optstring
2. update the docs since they show outdated runs of the code.  i think after that we should be good to land!

2021-06-09 19:37 UTC, h00die commented on modules/auxiliary/scanner/http/emby_ssrf_scanner.rb
> +        OptBool.new('TARGETURI', [false, 'The URI of the Emby Server', '/']),
`OptString` not `OptBool`

2021-06-09 19:37 UTC, h00die commented on documentation/modules/auxiliary/scanner/http/emby_version_ssrf.md
> +[*] Saving host information.
looks like this is out of date now: https://github.com/rapid7/metasploit-framework/pull/14836/files#diff-5e44d60c69422a628ac1df9e88d35498abde49896ad7dd9922695d9b17241824R53

2021-06-09 19:37 UTC, h00die commented on documentation/modules/auxiliary/scanner/http/emby_ssrf_scanner.md
> +[+] 10.10.10.43:80 [C:200] [R:] [S:UPnP/1.0 DLNADOC/1.50] HP Integrated Lights-Out 2
this looks outdated as well

2021-06-09 22:27 UTC, btnz-k commented
All done :)

2021-06-12 19:11 UTC, h00die commented
Final runs:
```
msf6 auxiliary(scanner/http/emby_version_ssrf) > run

[*] Identifying Media Server Version on 1.1.1.1:8096     
[+] [Media Server] URI: http://1.1.1.1:8096     /
[+] [Media Server] Version: 4.4.3.0
[+] [Media Server] Internal IP: http://1.1.1.1:8096
[+] *** Vulnerable to SSRF module auxiliary/scanner/emby_ssrf_scanner! ***
[*] All info: {"LocalAddress"=>"http://1.1.1.1:8096", "WanAddress"=>"http://2.2.2.2:8096", "ServerName"=>"ubuntu2004", "Version"=>"4.4.3.0", "Id"=>"6db994a6782913fd870adbf8b86ffaf6"}
[*] Saving host information.
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

```
msf6 auxiliary(scanner/http/emby_ssrf_scanner) > run

[*] Attempting SSRF with target 2.2.2.2:80
[+] 2.2.2.2:80 Title: ● 2.2.2.2
[+] 2.2.2.2:80     HTTP Code: 200
[+] 2.2.2.2:80     Location Header: 
[+] 2.2.2.2:80     Server Header: UPnP/1.0 DLNADOC/1.50
[*] Scanned 1 of 2 hosts (50% complete)
[*] Attempting SSRF with target 3.3.3.3:80
[+] 3.3.3.3:80 Title: ● 3.3.3.3
[+] 3.3.3.3:80     HTTP Code: 200
[+] 3.3.3.3:80     Location Header: 
[+] 3.3.3.3:80     Server Header: UPnP/1.0 DLNADOC/1.50
[*] Scanned 2 of 2 hosts (100% complete)
[*] Auxiliary module execution completed
```

2021-06-12 19:20 UTC, merged

2021-06-12 19:22 UTC, h00die commented
# Release Notes
This PR adds an aux scanner and module to exploit CVE-2020-26948, an SSRF against emby servers

2021-06-12 19:23 UTC, h00die commented
@btnz-k it was a long time coming, thanks for hanging with it to get this thing through.  First SSRF exploit (although other modules include SSRF functions) in the framework! Congrats on becoming a part of the module development community!