Fix method check for linux/ftp/proftp_telnet_iac module
rapid7/metasploit-framework pull request #14856
Opened 2021-03-05 08:04 UTC by capme

This change related to the bugfix issue https://github.com/rapid7/metasploit-framework/issues/14848

Please ensure you are submitting **from a unique branch** in your [repository](https://github.com/rapid7/metasploit-framework/pull/11086#issuecomment-445506416) to master in Rapid7's.

## Verification

List the steps needed to make sure this thing works

- [ ] Make a target (ProFTPD 1.3.3) in your local (see https://github.com/rapid7/metasploit-framework/issues/14848)
- [ ] Start `msfconsole`
- [ ] `use exploit/linux/ftp/proftp_telnet_iac`
- [ ] `set RHOSTS localhost`
- [ ] `set RPORT 2021`
- [ ] run `check`
- [ ] Verify that the target is **vulnerable**

## Scenarios

Target (ProFTPD 1.3.3)

```
$ sudo docker run -p 2021:2021 proftpd_vuln:latest
 - using TCP receive buffer size of 131072 bytes
 - using TCP send buffer size of 16384 bytes
 - <IfModule>: using 'mod_ident.c' section at line 32
 - <Directory />: adding section for resolved path '/'
172.17.0.12 - 
172.17.0.12 - Config for ProFTPD TEST Installation:
172.17.0.12 - /
172.17.0.12 -  AllowOverwrite
172.17.0.12 -  TransferLog
172.17.0.12 -  RequireValidShell
172.17.0.12 -  UseFtpUsers
172.17.0.12 -  WtmpLog
172.17.0.12 -  Umask
172.17.0.12 - DefaultServer
172.17.0.12 - UserID
172.17.0.12 - UserName
172.17.0.12 - GroupID
172.17.0.12 - GroupName
172.17.0.12 - AuthUserFile
172.17.0.12 - AuthGroupFile
172.17.0.12 - PidFile
172.17.0.12 - TransferLog
172.17.0.12 - RequireValidShell
172.17.0.12 - UseFtpUsers
172.17.0.12 - WtmpLog
172.17.0.12 - IdentLookups
172.17.0.12 - Umask
172.17.0.12 - ProFTPD 1.3.3 (stable) (built Tue Mar 2 2021 06:47:05 UTC) standalone mode STARTUP
172.17.0.12 (::ffff:172.17.0.1[::ffff:172.17.0.1]) - session requested from client in unknown class
172.17.0.12 (::ffff:172.17.0.1[::ffff:172.17.0.1]) - connected - local  : ::ffff:172.17.0.12:2021
172.17.0.12 (::ffff:172.17.0.1[::ffff:172.17.0.1]) - connected - remote : ::ffff:172.17.0.1:45910
172.17.0.12 (::ffff:172.17.0.1[::ffff:172.17.0.1]) - FTP session opened.
172.17.0.12 (::ffff:172.17.0.1[::ffff:172.17.0.1]) - FTP session closed.
```

Metasploit console

```
msf6 > use exploit/linux/ftp/proftp_telnet_iac
[*] No payload configured, defaulting to linux/x86/meterpreter/reverse_tcp
msf6 exploit(linux/ftp/proftp_telnet_iac) > set RHOSTS localhost
RHOSTS => localhost
msf6 exploit(linux/ftp/proftp_telnet_iac) > set RPORT 2021
RPORT => 2021
msf6 exploit(linux/ftp/proftp_telnet_iac) > check
[*] 127.0.0.1:2021 - The target appears to be vulnerable.
msf6 exploit(linux/ftp/proftp_telnet_iac) > 
```

2021-03-05 12:49 UTC, capme commented
this PR related with this issue https://github.com/rapid7/metasploit-framework/issues/14848

2021-03-10 02:36 UTC, gwillcox-r7 commented
Changed a few minor details here to use the `Fixes` keyword which will ensure that when this PR is landed, the associate issue will be marked as resolved. Also removed the checkmarks and made your items into clickable checkboxes. This allows maintainers to check items off as they are tested, therefore if we get stuck halfway, its easy to tell what items currently are working and which ones need more work to get this PR into a state where it can be landed.

2021-03-10 20:06 UTC, smcintyre-r7 requested changes
This being an older module means there's quite a few stylistic infractions that would be caught by rubocop. Since you didn't write it, we don't want to hold you accountable for updating everything else but we do want to make sure that new changes follow the current [Ruby Style Guidelines](https://github.com/rubocop/ruby-style-guide).

Some notable discrepancies within here:
* Variables should be `snake_case` not `camelCase` (so `banner_array` not `bannerArray`)
* Should prefer the binary logic operators `&&` and `||` vs the English words `and` and `or`
* Indentation should be exactly two spaces

2021-03-10 20:06 UTC, smcintyre-r7 commented on modules/exploits/linux/ftp/proftp_telnet_iac.rb
> +      if extra.length == 0 or extra =~ /[abrc]/i
It looks like the R in `extra =~ /[abrc]/i`should be committed since the only 1.3.3 versions that are vulnerable are 1.3.3 1.3.3a, 1.3.3b and 1.3.3c, anything 1.3.3d or later (including the RC ones) are patched. The regex is also a bit confusing to read, it looks like this could be a bit easier to read as an array like `if extra.length == 0 || [ '', 'a', 'b', 'c' ].include?(extra)` which would be more specific.

2021-03-14 23:38 UTC, capme commented on modules/exploits/linux/ftp/proftp_telnet_iac.rb
> +      if extra.length == 0 or extra =~ /[abrc]/i
thank you @smcintyre-r7. I've made these updates:
- fix indentation
- change logical operator into binary
- simplify check extra variable.

2021-03-14 23:40 UTC, capme commented on modules/exploits/linux/ftp/proftp_telnet_iac.rb
> +      if extra.length == 0 or extra =~ /[abrc]/i
and also change the variable into snake case

2021-03-15 06:38 UTC, gwillcox-r7 commented on modules/exploits/linux/ftp/proftp_telnet_iac.rb
> +        if [ '', 'a', 'b', 'c' ].include?(extra)
Is this not meant to include the character `r` here as well given the original code? Will leave this to Spencer to do the rest of his review on but thought I'd point this out as it seems the original code was also checking for the character `r`.

2021-03-15 13:00 UTC, smcintyre-r7 commented on modules/exploits/linux/ftp/proftp_telnet_iac.rb
> +        if [ '', 'a', 'b', 'c' ].include?(extra)
No, the rc versions aren't affected so they should return the status of "safe".

2021-03-15 13:21 UTC, smcintyre-r7 requested changes
Sorry for the second round of review, I just spotted a couple of things I missed on my first pass.

Another thing is that this code is duplicated in a second exploit in `exploit/freebsd/ftp/proftp_telnet_iac`. Would you be able to please update that one too so they're kept synchronized?

2021-03-16 23:14 UTC, capme commented
> Sorry for the second round of review, I just spotted a couple of things I missed on my first pass.
> 
> Another thing is that this code is duplicated in a second exploit in `exploit/freebsd/ftp/proftp_telnet_iac`. Would you be able to please update that one too so they're kept synchronized?

ok. implemented for freebsd also

2021-03-16 23:22 UTC, capme commented on modules/exploits/linux/ftp/proftp_telnet_iac.rb
> -    if banner =~ /ProFTPD (1\.3\.[23][^ ])/i
do you mean we should put this line back-in ?

2021-03-16 23:53 UTC, capme commented on modules/exploits/linux/ftp/proftp_telnet_iac.rb
> -    if banner =~ /ProFTPD (1\.3\.[23][^ ])/i
ok. 
i'm putting back this line `if banner =~ /ProFTPD (1\.3\.[23])/i`.
but I'm not using this part `[^ ]`, since it will make version `1.3.3` not vulnerable

2021-03-16 23:57 UTC, capme commented on modules/exploits/linux/ftp/proftp_telnet_iac.rb
> +        if [ '', 'a', 'b', 'c' ].include?(extra)
ok. implemented for freebsd also

2021-03-17 13:25 UTC, smcintyre-r7 approved these changes
Changes look good to me now. I was able to reproduce the original issue where version 1.3.3 was being misclassified as not vulnerable.

With these changes in place, version 1.3.3, 1.3.3b and 1.3.3c are all being classified correctly.

I'll have this landed shortly, thanks alot for fixing this issue!

<details>
<summary>Original Output</summary>

In this scenario, the original bug is reproduced where version 1.3.3 is incorrectly identified as not vulnerable.

```
msf6 exploit(linux/ftp/proftp_telnet_iac) > set RHOSTS 192.168.159.128
RHOSTS => 192.168.159.128
msf6 exploit(linux/ftp/proftp_telnet_iac) > set RPORT 2021
RPORT => 2021
msf6 exploit(linux/ftp/proftp_telnet_iac) > check
[*] 192.168.159.128:2021 - The target is not exploitable.
msf6 exploit(linux/ftp/proftp_telnet_iac) > 
```
</details>

<details>
<summary>Corrected Output</summary>

```
msf6 exploit(linux/ftp/proftp_telnet_iac) > set RHOSTS 192.168.159.128
RHOSTS => 192.168.159.128
msf6 exploit(linux/ftp/proftp_telnet_iac) > set RPORT 2021
RPORT => 2021
msf6 exploit(linux/ftp/proftp_telnet_iac) > check
msf6 exploit(linux/ftp/proftp_telnet_iac) > check
[*] 192.168.159.128:2021 - The target appears to be vulnerable.
msf6 exploit(linux/ftp/proftp_telnet_iac) >
```
</details>

2021-03-17 13:27 UTC, merged

2021-03-17 13:28 UTC, smcintyre-r7 commented
# Release Notes
This corrects an issue in the two modules targeting CVE-2010-4221 where the ProFTPD version number without a letter suffix was being incorrectly identified as not vulnerable.