Drop python 3.6 string formatting syntax in rdp_web_login
rapid7/metasploit-framework pull request #14953
Opened 2021-03-26 18:47 UTC by bwatters-r7

The module cache builder is using a slightly older python syntax, so it will error quietly and fail to add the `rdp_web_login` module to the module cache.  This PR removes the cool new string interpolation present in the module and reverts to old, stone-age string concatenation.

See the original module PR for testing strategies: https://github.com/rapid7/metasploit-framework/pull/14544, but also:
- [ ] run msfconsole
- [ ] type `use auxiliary/scanner/http/rdp_`
- [ ] hit <tab>
- [ ] verify autocomplete works

@jmartin-r7, @k0pak4

2021-03-26 20:31 UTC, smcintyre-r7 commented
For future reference, do we have a minimum version of Python that we should be supporting in our external modules moving forward? I know it's 3.x something but there are certainly starting to be some appealing features coming out in the later versions that would make it helpful to know what's the oldest we need to maintain compatibility with.

2021-03-26 21:53 UTC, jmartin-r7 commented
>  do we have a minimum version of Python that we should be supporting in our external modules moving forward?

I think this is up for grabs, as it stands current automation uses 3.5 and supports older platforms which may never update beyond 3.5 is official package repositories, if a consensus on a new version is reached tooling can be updated.  On that note I have a branch currently in development to add support for all current external modules into the docker environment provided by the Framework repository.  Once dev on that branch is complete we could use that environment as the litmus test for desired version support although compatibility various other distributions may not be well supported by using that as the bar.

2021-03-30 16:02 UTC, k0pak4 requested changes
The changes overall look fine to me, except for one string replace. I haven't tested it locally, but will try to do so in the coming days on my setup

2021-04-06 18:29 UTC, k0pak4 requested changes
@bwatters-r7 I pulled your PR down and had to make a few additional changes in order for the string formatting to work. The autocomplete works for me now, but the requested changes will be needed to keep the module functional

2021-04-06 18:29 UTC, k0pak4 commented on modules/auxiliary/scanner/http/rdp_web_login.py
> +    body = 'DomainUserName=' + 'domain' + '%5C' + username + '&UserPass=' + password
This should be domain instead of 'domain' so that it uses the variable not the string 'domain'

2021-04-06 18:29 UTC, k0pak4 commented on modules/auxiliary/scanner/http/rdp_web_login.py
> +        module.log('Login ' + domain + '\\' + username + ':' + password + ' is invalid! No response received in ' + timeout + ' milliseconds',
this timeout needs a str() wrapper to get the concatenation to work. So replace with str(timeout)

2021-04-23 20:43 UTC, merged

2021-04-23 20:50 UTC, timwr commented
I fixed this by using python string.format, which should be compatible with all python versions and avoids having to convert the arguments into a str.

2021-04-23 20:52 UTC, timwr commented
## Release notes

Fix the python 3.6 string formatting syntax in modules/auxiliary/scanner/http/rdp_web_login