WIP: post gather module for saltstack
rapid7/metasploit-framework pull request #15113
Opened 2021-04-28 20:32 UTC by h00die

This PR adds a post module to gather salt information, configs, etc.  I'm not a salt admin, so if anyone knows some other things that would be worth pulling, I'll be happy to add it.  Putting this in draft as I work with a new dev while they get the Windows portion working.

## Verification

- [ ] Start `msfconsole`
- [ ] Get a shell on a box that is either a salt master or salt minion, linux or windows
- [ ] `use post/multi/gather/saltstack.rb`
- [ ] **Verify** you get lots of juicy info
- [ ] **Document** looks pretty fly for a pentest guy

2021-04-28 22:32 UTC, wvu-r7 commented
Cool!

2021-04-30 22:18 UTC, wvu-r7 requested changes
I'd rename this `post/multi/gather/saltstack_salt`, since SaltStack is the vendor, and Salt is the product.

2021-04-30 22:23 UTC, h00die commented
> I'd rename this `post/multi/gather/saltstack_salt`, since SaltStack is the vendor, and Salt is the product.

Don't be salty

2021-05-02 21:10 UTC, wvu-r7 commented on modules/post/multi/gather/saltstack_salt.rb
> +        'Name' => 'SaltStack Information Gatherer',
```suggestion
        'Name' => 'SaltStack Salt Information Gatherer',
```

2021-05-02 21:10 UTC, wvu-r7 commented on modules/post/multi/gather/saltstack_salt.rb
> +          This module gathers information from SaltStack masters and minions.
```suggestion
          This module gathers information from SaltStack Salt masters and minions.
```

2021-05-02 21:15 UTC, wvu-r7 requested changes
Still a few places to be consistent in naming. See `store_loot` calls, too.

2021-05-03 23:44 UTC, c2Vlcgo commented
Runs without issue in my dev environment.  Output files match result expectations; granular breakdown of SLS trees, and a good overview of all available minion hosts.

Salt master: Ubuntu 16.04
Salt minion: Ubuntu 16.04
Salt Versions Tested: 3001 and 3002.6

Screenshow below shows execution output; IP addresses redacted.

![saltstack_salt_testing](https://user-images.githubusercontent.com/47341159/116945963-ea170f00-ac46-11eb-8ea6-c2659c4b4987.png)

2021-05-04 04:09 UTC, wvu-r7 approved these changes

2021-05-13 22:22 UTC, bwatters-r7 commented on modules/post/multi/gather/saltstack_salt.rb
> +      minions.each do |name, minion|
You may want to guard this with 
`unless minions.nil?`
I found that the value `minions` came back as `nil` if salt-ssh was not installed on the minion:
```
[+] 192.168.134.113:60682 - minion data gathering successfully retrieved and saved to /home/tmoose/.msf4/loot/20210513144840_default_192.168.134.113_saltstack_minion_361736.bin
[+] Found minion: ubuntu-20041 (192.168.134.113) - Linux version 5.8.0-53-generic (buildd@lcy01-amd64-012) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021
[*] Showing SLS
[+] 192.168.134.113:60682 - SLS output successfully retrieved and saved to /home/tmoose/.msf4/loot/20210513144857_default_192.168.134.113_saltstack_sls_626023.txt
[*] Loading roster
[-] Post failed: NoMethodError undefined method `each' for nil:NilClass
[-] Call stack:
[-]   /home/tmoose/rapid7/metasploit-framework/modules/post/multi/gather/saltstack_salt.rb:223:in `block in master'
[-]   /home/tmoose/rapid7/metasploit-framework/modules/post/multi/gather/saltstack_salt.rb:214:in `each'
[-]   /home/tmoose/rapid7/metasploit-framework/modules/post/multi/gather/saltstack_salt.rb:214:in `master'
[-]   /home/tmoose/rapid7/metasploit-framework/modules/post/multi/gather/saltstack_salt.rb:299:in `run'
[*] Post module execution completed
```

2021-05-13 22:24 UTC, bwatters-r7 commented
Looks great.  Just the one thought about catching `nil` if salt-ssh is not installed on the minions.
```
msf6 post(multi/gather/saltstack_salt) > run

[!] SESSION may not be compatible with this module.
[*] Looking for salt minion config files
[+] Minion master: 192.168.134.113
[+] 192.168.134.113:60682 - minion file successfully retrieved and saved to /home/tmoose/.msf4/loot/20210513165358_default_192.168.134.113_saltstack_minion_137779.bin
[*] Attempting to list minions
[*] minions:
- ubuntu-20041
- ubuntu-vm
minions_denied: []
minions_pre: []
minions_rejected: []
[+] 192.168.134.113:60682 - minion file successfully retrieved and saved to /home/tmoose/.msf4/loot/20210513165359_default_192.168.134.113_saltstack_minion_836560.bin
[+] Minions List
============

 Status    Minion Name
 ------    -----------
 Accepted  ubuntu-20041
 Accepted  ubuntu-vm

[*] Gathering data from minions (this can take some time)
[*] ubuntu-20041:
  network.get_hostname: ubuntu-20041
  network.interfaces:
    ens32:
      hwaddr: 00:0c:29:f9:61:ef
      inet:
      - address: 192.168.134.113
        broadcast: 192.168.134.255
        label: ens32
        netmask: 255.255.255.0
      inet6:
      - address: fd34:fe56:7891:2f3b:2c25:cced:3232:fcea
        prefixlen: '64'
        scope: global
      - address: fd34:fe56:7891:2f3b:ff34:7a5f:f785:29e5
        prefixlen: '64'
        scope: global
      - address: fe80::3c97:c033:acf:f037
        prefixlen: '64'
        scope: link
      up: true
    lo:
      hwaddr: 00:00:00:00:00:00
      inet:
      - address: 127.0.0.1
        broadcast: null
        label: lo
        netmask: 255.0.0.0
      inet6:
      - address: ::1
        prefixlen: '128'
        scope: host
      up: true
  status.version: 'Linux version 5.8.0-53-generic (buildd@lcy01-amd64-012) (gcc (Ubuntu
    9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #60~20.04.1-Ubuntu
    SMP Thu May 6 09:52:46 UTC 2021'
  system.get_system_info: "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/salt/minion.py\",
    line 2098, in _thread_multi_return\n    return_data = minion_instance._execute_job_function(\n
    \ File \"/usr/lib/python3/dist-packages/salt/minion.py\", line 1861, in _execute_job_function\n
    \   return_data = self.executors[fname](opts, data, func, args, kwargs)\n  File
    \"/usr/lib/python3/dist-packages/salt/loader.py\", line 1235, in __call__\n    return
    self.loader.run(run_func, *args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/salt/loader.py\",
    line 2268, in run\n    return self._last_context.run(self._run_as, _func_or_method,
    *args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/salt/loader.py\", line
    2283, in _run_as\n    return _func_or_method(*args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/salt/executors/direct_call.py\",
    line 12, in execute\n    return func(*args, **kwargs)\nTypeError: 'str' object
    is not callable\n"
ubuntu-vm:
  network.get_hostname: ubuntu-vm
  network.interfaces:
    ens32:
      hwaddr: 00:0c:29:a2:ff:7f
      inet:
      - address: 192.168.134.134
        broadcast: 192.168.134.255
        label: ens32
        netmask: 255.255.255.0
      inet6:
      - address: fd34:fe56:7891:2f3b:9d32:a7c9:ec6b:95a3
        prefixlen: '64'
        scope: global
      - address: fd34:fe56:7891:2f3b:606:98c1:b25f:68aa
        prefixlen: '64'
        scope: global
      - address: fe80::e3f3:5a95:9951:f06b
        prefixlen: '64'
        scope: link
      up: true
    lo:
      hwaddr: 00:00:00:00:00:00
      inet:
      - address: 127.0.0.1
        broadcast: null
        label: lo
        netmask: 255.0.0.0
      inet6:
      - address: ::1
        prefixlen: '128'
        scope: host
      up: true
  status.version: 'Linux version 5.8.0-53-generic (buildd@lcy01-amd64-012) (gcc (Ubuntu
    9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #60~20.04.1-Ubuntu
    SMP Thu May 6 09:52:46 UTC 2021'
  system.get_system_info: "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/salt/minion.py\",
    line 2098, in _thread_multi_return\n    return_data = minion_instance._execute_job_function(\n
    \ File \"/usr/lib/python3/dist-packages/salt/minion.py\", line 1861, in _execute_job_function\n
    \   return_data = self.executors[fname](opts, data, func, args, kwargs)\n  File
    \"/usr/lib/python3/dist-packages/salt/loader.py\", line 1235, in __call__\n    return
    self.loader.run(run_func, *args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/salt/loader.py\",
    line 2268, in run\n    return self._last_context.run(self._run_as, _func_or_method,
    *args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/salt/loader.py\", line
    2283, in _run_as\n    return _func_or_method(*args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/salt/executors/direct_call.py\",
    line 12, in execute\n    return func(*args, **kwargs)\nTypeError: 'str' object
    is not callable\n"
[+] 192.168.134.113:60682 - minion data gathering successfully retrieved and saved to /home/tmoose/.msf4/loot/20210513165401_default_192.168.134.113_saltstack_minion_033068.bin
[+] Found minion: ubuntu-20041 (192.168.134.113) - Linux version 5.8.0-53-generic (buildd@lcy01-amd64-012) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021
[+] Found minion: ubuntu-vm (192.168.134.134) - Linux version 5.8.0-53-generic (buildd@lcy01-amd64-012) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021
[*] Showing SLS
[+] 192.168.134.113:60682 - SLS output successfully retrieved and saved to /home/tmoose/.msf4/loot/20210513165402_default_192.168.134.113_saltstack_sls_171640.txt
[*] Loading roster
[*] Looking for salt minion config files
[+] Minion master: 192.168.134.113
[+] 192.168.134.113:60682 - minion file successfully retrieved and saved to /home/tmoose/.msf4/loot/20210513165402_default_192.168.134.113_saltstack_minion_183800.bin
[+] 192.168.134.113:60682 - roster file successfully retrieved and saved to /home/tmoose/.msf4/loot/20210513165402_default_192.168.134.113_saltstack_roster_690465.bin
[*] Gathering pillar data
[*] ubuntu-20041: {}
ubuntu-vm: {}
[+] 192.168.134.113:60682 - pillar data gathering successfully retrieved and saved to /home/tmoose/.msf4/loot/20210513165403_default_192.168.134.113_saltstack_pillar_410702.bin
[*] Post module execution completed
msf6 post(multi/gather/saltstack_salt) > 

```

2021-05-15 13:39 UTC, h00die commented
guarded!

2021-05-17 20:34 UTC, merged

2021-05-17 20:34 UTC, bwatters-r7 commented
# Release Notes
This PR adds a post module to gather salt information, configs, etc.

2021-05-17 21:08 UTC, wvu-r7 commented
Thanks for handling this, @bwatters-r7!