CVE-2021-31802 - R7000 v1.0.11.116 and Prior Unauthenticated RCE via Heap Overflow
rapid7/metasploit-framework pull request #15163
Opened 2021-05-07 00:56 UTC by gwillcox-r7

This adds in a exploit for CVE-2021-31802, a heap based overflow in the `genie.cgi?backup.cgi` page of NetGear Nighthawk R7000 routers up to and including the latest firmware (v1.0.11.116) that can be exploited by unauthenticated attackers on the same network as the affected router to gain RCE as the `root` user.

This module is based on the writeup by SSD at https://ssd-disclosure.com/ssd-advisory-netgear-nighthawk-r7000-httpd-preauth-rce/ which was discovered and disclosed by @colorlight2019 (https://twitter.com/colorlight2019), and copies heavily from the PCAP traffic generated from the PoC code that was released there.

Successful exploitation should result in the `telnet` service being enabled on the target R7000 device. Users can then connect via port 23 over TCP to the target R7000 router in order to gain RCE as the `root` user. 

Note that whilst this module does work in its current state, its being marked as a work in progress until some cleanup work can be done, as the current module is just a port of the original PoC from @colorlight2019, and there are further improvements that can be made to randomize the exploit a bit more in certain places, assuming this doesn't prevent the exploit from working (still need to figure out what works and what doesn't).

Documentation and more to come soon.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/linux/http/netgear_r7000_backup_cgi_heap_overflow_rce`
- [ ] `set RHOSTS *router ip*`
- [ ] `exploit`
- [ ] Wait for the exploit to complete, it should hang at the last stage.
- [ ] `telnet *router ip*`
- [ ] Verify via `id` that you are running as the `admin` user.

PCAPs are available upon request should anyone need them to confirm things.

2021-05-19 15:17 UTC, bwatters-r7 reviewed
This is our particular definition of `exploit` rearing its head again.... This is currently an exploit module, but it does not need a handler because it does not send up an interactive payload per se.  I don't know if we have things like this already in exploits, or if this is a new animal.  I'm interested in seeing people's perspectives and possible examples.

I've always erred on the side of a strict programmatic definition of exploit modules in Metasploit.  Is psexec an exploit?  Is a DLL hijack an exploit?  Is stealing a token an exploit?  In my mind the defining aspect of an exploit in Metasploit is needing a handler for a call-in or call-back. 
 
There's a lot of room to talk about what an "exploit" is according to each of us, and I don't want to see modules get bike-shedded and yak-shaved, so I've always liked the definition that if it needs a handler, it is an exploit.  This module is a prime example of where that definition is not entirely adequate.

2021-05-19 15:52 UTC, gwillcox-r7 commented on modules/exploits/linux/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
> +          This module exploits an heap buffer overflow in the genie.cgi?backup.cgi
Resolved with https://github.com/rapid7/metasploit-framework/pull/15163/commits/275b021cdd54ddb626582c83f6a4308db250d711 and suggested change implemented.

2021-05-19 15:52 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/netgear_r7000_backup_cgi_heap_overflow_rce.md
> +This module exploits an heap buffer overflow in the `genie.cgi?backup.cgi`
Resolved with https://github.com/rapid7/metasploit-framework/pull/15163/commits/275b021cdd54ddb626582c83f6a4308db250d711 and suggested change implemented.

2021-05-20 15:05 UTC, bwatters-r7 commented
Yeah; to keep with our naming convention, this should be an aux module.

2021-06-02 22:58 UTC, gwillcox-r7 commented
@bwatters-r7 Converted this over into an auxiliary module, should be ready for review now.

2021-06-16 20:04 UTC, smcintyre-r7 requested changes
Well I tested this with a R7000 running firmware version `1.0.9.64_10.2.64`. First, it failed to detect the firmware version. I left a comment about this in the PR with the HTTP trace output showing the response. After disabling `AutoCheck`, I ran the exploit multiple times on the WAN interface where it failed every time. I then switched to the LAN interface, running it with the default settings of RPORT 80 and SSL false where it again failed 10/10 times. I'm guessing it's possible that the heap setup isn't working because the version is so old. If that's the case, the module should probably determine that and then `fail_with(Failure::NoTarget...`.

2021-06-16 20:36 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
> +    firmware_version = data.match(%r{<b>Firmware Version</b><br>V(\d+\.\d+\.\d+\.\d+)})
Interesting on your Router is almost like it was commented out:

```
          <!--
          <td style="text-align:right;padding-right:25px"><b>Firmware Version</b><br></td>  
          -->
```
Its the same format just the version info isn't disclosed. Might have to find a way to handle that better or an alternative page.

2021-06-16 20:37 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
> +      fail_with(Failure::Unreachable, 'Connection timed out.')
Oh wow I ended up doing a `Failure` case in a `check` method. I thought the day would never come but here we are 😄 My bad, let me fix this up, your correct it should be `CheckCode::Unknown`.

2021-06-16 20:38 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
> +        if check_vuln_firmware
Good point, I'll fix this up 👍

2021-06-16 20:39 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
> +    end
Agreed, let me rework this.

2021-06-16 20:58 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.md
> +This module exploits an heap buffer overflow in the `genie.cgi?backup.cgi`
Fixed in https://github.com/rapid7/metasploit-framework/pull/15163/commits/457a84078ff7ba2f7c95aac082c91b0d150be863

2021-06-16 20:59 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
> +        if check_vuln_firmware
Fixed in https://github.com/rapid7/metasploit-framework/pull/15163/commits/457a84078ff7ba2f7c95aac082c91b0d150be863

2021-06-16 20:59 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
> +    end
Fixed in https://github.com/rapid7/metasploit-framework/pull/15163/commits/457a84078ff7ba2f7c95aac082c91b0d150be863, let me know if the solution looks odd at all.

2021-06-16 20:59 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
> +      fail_with(Failure::Unreachable, 'Connection timed out.')
Fixed in https://github.com/rapid7/metasploit-framework/pull/15163/commits/457a84078ff7ba2f7c95aac082c91b0d150be863

2021-06-24 20:58 UTC, gwillcox-r7 commented
> Well I tested this with a R7000 running firmware version `1.0.9.64_10.2.64`. First, it failed to detect the firmware version. I left a comment about this in the PR with the HTTP trace output showing the response. After disabling `AutoCheck`, I ran the exploit multiple times on the WAN interface where it failed every time. I then switched to the LAN interface, running it with the default settings of RPORT 80 and SSL false where it again failed 10/10 times. I'm guessing it's possible that the heap setup isn't working because the version is so old. If that's the case, the module should probably determine that and then `fail_with(Failure::NoTarget...`.
> 
> This was the output when testing the WAN interface:
> 
> ```
> msf6 auxiliary(admin/http/netgear_r7000_backup_cgi_heap_overflow_rce) > run
> [*] Running module against 192.168.250.126
> 
> [!] AutoCheck is disabled, proceeding with exploitation
> [-] Auxiliary aborted due to failure: unexpected-reply: The target R7000 router responded prematurely on the first packet, something wrong happened!
> [*] Auxiliary module execution completed
> msf6 auxiliary(admin/http/netgear_r7000_backup_cgi_heap_overflow_rce) >
> ```

Hmm yeah the heap layout is quite possibly different for different routers, though I would be curious if a version closer to this one is still exploitable, as its possible older versions had a different layout and then at some point it got changed and more recent ones are still exploitable with the same code. Aka find if there was some cut off point at which the exploit code will no longer work and update accordingly.

2021-06-24 21:00 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
> +      'uri' => normalize_uri('cgi-bin', "genie.cgi?backup.cgi\nContent-Length: 4156559"),
I believe it is necessary for exploitation but I'll do a check to verify. I know there were a lot of odd stuff going on with the headers that appeared to be needed for exploitation given how out of place things were but I haven't verified things fully.

2021-06-24 21:23 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
> +      'uri' => normalize_uri('cgi-bin', "genie.cgi?backup.cgi\nContent-Length: 4156559"),
Okay yeah just verified it needs to be like this for exploitation purposes so I'll add a comment into the code for these places to explain they are needed.

2021-06-24 21:28 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
> +      'headers' => { 'Content-Disposition' => "form-data\r\n#{Rex::Text.rand_text_alpha(512)}: #{Rex::Text.rand_text_alpha(9)}", 'Host' => "#{datastore['RHOST']}:#{datastore['RPORT']}" },
Hmm good eyes, I think this should work fine, let me try it out now.

2021-06-24 21:54 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
> +      'headers' => { 'Content-Disposition' => "form-data\r\n#{Rex::Text.rand_text_alpha(512)}: #{Rex::Text.rand_text_alpha(9)}", 'Host' => "#{datastore['RHOST']}:#{datastore['RPORT']}" },
Fixed with https://github.com/rapid7/metasploit-framework/pull/15163/commits/3f9c5809dbc7cd7f1e9f5063c8c43edaa44d8d9c

2021-07-22 01:12 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
> +    firmware_version = data.match(%r{<b>Firmware Version</b><br>V(\d+\.\d+\.\d+\.\d+)})
Alright so found that `/currentsetting.htm` will leak much more information and also is accessible to unauthenticated users on both this device and another Netgear device I tested it on, so this should be a more reliable method of determining the router firmware version as an unauthenticated user.

2021-07-27 17:50 UTC, smcintyre-r7 commented on modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
> +      return
This should be `fail_with(Failure::NoTarget, ...`.

2021-07-27 18:02 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
> +      return
Fixed with https://github.com/rapid7/metasploit-framework/pull/15163/commits/a13f6a35dceb3f4ef479701e1d8ca67a83ee9357

2021-07-27 18:41 UTC, gwillcox-r7 commented on modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
> +    firmware_version = data.match(%r{<b>Firmware Version</b><br>V(\d+\.\d+\.\d+\.\d+)})
Issue is now resolved, current code should use `/currentsetting.htm` instead which should be more reliable.

2021-07-29 13:26 UTC, smcintyre-r7 approved these changes
The code looks good to me at this point. I tested it on an older R7000 I had on hand and verified that it properly identifies the version and correctly determines that it is unsupported. Forcing the exploit on this older version didn't work when I tested that as well.

I reviewed the demo video and everything appears to be in order.

I pushed up one small change to fix a rubocop error so the unit tests pass and with that in place, I'll go ahead and land this. Thanks @gwillcox-r7 !

2021-07-29 13:27 UTC, merged

2021-07-29 13:28 UTC, smcintyre-r7 commented
# Release Notes
This adds an module that will leverage CVE-2021-31802 which is an unauthenticated RCE in Netgear R7000 routers. The vulnerability is leveraged to execute a shellcode stub that will enable telnet which can then be accessed for root privileges on the affected device.