initial commit
rapid7/metasploit-framework pull request #15305
Opened 2021-06-07 14:45 UTC by Hakyac

## Description

This module allows an attacker with knowledge of the admin password of NSClient++
to start a privilege reverse shell.
For this module to work, both web interface of NSClient++ and `ExternalScripts`feature
should be enabled.

## Installation

A vulnerable version of NSClient++ can be downloaded from [here]https://nsclient.org/download/). Then you can help yourself with this [installation guide](https://docs.nsclient.org/api/rest/) to complete the installation. Don't forget to enable the web interface and the `ExternalScripts` feature to allow the exploit to work.

## Verification Steps

List the steps needed to make sure this thing works

- 1. Start `msfconsole`
- 2. `use exploit/windows/http/nscp_authenticated_rce`
- 3. `set RHOST <target_host>`
- 4. `set PASSWORD <admin_password>` to set the admin password of NSClient++ web interface
- 5. `check` to check if the targeted NSClient++ is vulnerable
- 6. `set payload <choose_a_payload>` to set a specific payload to send
- 7. `run` the module to exploit the vulnerability and start a shell

## Options

**RHOSTS**

Set the target host.

**PASSWORD**

Set the PASSWORD of the admin account of NSClient++.

## Demonstration

![image](https://user-images.githubusercontent.com/84333864/121037430-bd0ecc80-c7af-11eb-9c11-c6d03155985b.png)

2021-06-08 11:37 UTC, agalway-r7 commented
Tested and got an exploit working as expected 👍 

Will look over the code now to see if there's any issues/improvements

2021-06-08 11:45 UTC, agalway-r7 commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +          print_status('Application failed to reload. Nice DoS exploit! /s')
I appreciate this

2021-06-08 12:07 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +          print_status('Application failed to reload. Nice DoS exploit! /s')
Fortunately in my case this has never happened to me :)

2021-06-08 12:07 UTC, agalway-r7 commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +      token = get_auth_token
```suggestion
```

Was able to remove this line and still get a shell, is it needed?

2021-06-08 12:13 UTC, agalway-r7 requested changes

2021-06-08 12:13 UTC, agalway-r7 commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +      rand_key = generate_random_name
```suggestion
      rand_key = rand_text_alpha_lower(10)
```
You can replace this hand rolled method with a call to one of our random `Rex::Text` methods, it's way easier to read. I think `rand_text_alpha_lower(10)` is what you're looking for?

2021-06-08 12:13 UTC, agalway-r7 commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +  prepend Msf::Exploit::Remote::AutoCheck
```suggestion
  include ::Msf::Exploit::Remote::HttpClient
  include ::Msf::Exploit::Remote::HttpServer
  include ::Msf::Exploit::CmdStager
  include ::Msf::Exploit::Powershell
  prepend ::Msf::Exploit::Remote::AutoCheck
  include ::Rex::Text
```

Includes the `Rex::Text` library and fills out the proper library paths

2021-06-08 12:13 UTC, agalway-r7 commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +  end
```suggestion
```
See Below

2021-06-08 12:13 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +      token = get_auth_token
Just in case the app reloading deletes the current auth token. I don't know if it happens often.

2021-06-08 12:15 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +      rand_key = generate_random_name
Yes this matches my needs ! Didn't know something like that was already existing in msf. Do you know where I can find some other built-in functions like this one ?

2021-06-08 12:18 UTC, agalway-r7 commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +      token = get_auth_token
Fair enough, we'll keep it in 👍  Could put a comment on that line saying why we're keeping it?

2021-06-08 12:25 UTC, agalway-r7 commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +      rand_key = generate_random_name
They can be hidden a bit I will admit it 😅  Best place to start looking for some msf specific needs (powershell scripts/NOP generation) is our various [Remote EXploitation (REX) libraries](https://github.com/rapid7?q=rex&type=&language=&sort=). 

Outside of that if you're looking for more generic stuff we usually have a good few libraries already in msf that you can make use of. You can check the [Gemfile](https://github.com/rapid7/metasploit-framework/blob/master/Gemfile.lock) for the complete list

2021-06-08 12:27 UTC, agalway-r7 approved these changes

2021-06-08 12:35 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +      rand_key = generate_random_name
Thanks ! I will have a look for sure 😉 You're right, I find it rather difficult to find information about how to develop msf scripts 😅

2021-06-08 12:38 UTC, agalway-r7 commented
Thanks for the quick turn around! I'll land this once the tests pass

2021-06-08 12:42 UTC, adfoster-r7 commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +        if count > 10
I assume we will want to break out of this loop?

2021-06-08 12:44 UTC, adfoster-r7 commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +        if count > 10
For context: With Metasploit Pro we run exploits in an automated fashion, so we definitely want exploits to eventually end running - and not loop endlessly :+1:

2021-06-08 12:48 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +        if count > 10
Yes, maybe a `failwith` could do the trick ? Could you remind me the exact syntax pls ? (I can't find any documentation about it)

2021-06-08 12:49 UTC, adfoster-r7 submitted a review, later dismissed

2021-06-08 12:52 UTC, adfoster-r7 commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +        'plugin_id' => '1234',
^ Question about randomizing 1234 here too

2021-06-08 12:54 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +    payload = [ { 'plugin_id' => '1234', 'control' => { 'command' => 'SAVE' } } ]
Done !

2021-06-08 12:56 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +      begin
I could also add some delay inside the loop, you are right. But sending the request and waiting for a timeout already takes some time.

2021-06-08 13:00 UTC, bcoles commented on documentation/modules/exploit/windows/http/nscp_authenticated_rce.md
> +
Default options such as RHOSTS should not be defined.

```suggestion
```

2021-06-08 13:02 UTC, bcoles commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +      begin
It is best to sleep inside the loop. Rather than hammer the server as fast as possible. You can do both: delay before the loop and delay for each iteration of the loop.

2021-06-08 13:06 UTC, bcoles commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +        if count > 10
> Yes, maybe a `failwith` could do the trick ? 

`fail_with` is appropriate.

> Could you remind me the exact syntax pls ? (I can't find any documentation about it)

```ruby
  fail_with(Failure::Unknown, 'Application failed to reload. Nice DoS exploit!')
```

Rather than `Unknown` you could also use `Unreachable`.

2021-06-08 13:07 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +        if count > 10
Done !

2021-06-08 13:08 UTC, bcoles commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +      print_error('Unable to get an authentification token, maybe the target is safe')
Authentification is not a cromulent word.

```suggestion
      print_error('Unable to get an authentication token, maybe the target is safe')
```

2021-06-08 13:10 UTC, bcoles commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +  def check
You can combine both `print_*` statements and `CheckCode` codes in the `check` method. For example:

```ruby
      return CheckCode::Unknown('Unable to get an authentication token, maybe the target is safe')
```

2021-06-08 13:11 UTC, bcoles commented on documentation/modules/exploit/windows/http/nscp_authenticated_rce.md
> +For this module to work, both web interface of NSClient++ and `ExternalScripts`feature
```suggestion
For this module to work, both web interface of NSClient++ and `ExternalScripts` feature
```

2021-06-08 13:14 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +    r.body.to_s.include? 'STATUS_OK'
Should be better with Ruby's safe navigation operator :)

2021-06-08 13:15 UTC, Hakyac commented on documentation/modules/exploit/windows/http/nscp_authenticated_rce.md
> +- 7. `run` the module to exploit the vulnerability and start a shell
Oops some bad copy/paste 😅

2021-06-08 13:17 UTC, Hakyac commented on documentation/modules/exploit/windows/http/nscp_authenticated_rce.md
> +
Okay didn't know that, I thought that the documentation file was a kind of "follow all the steps and this module will work for sure".

2021-06-08 13:18 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +      print_error('Unable to get an authentification token, maybe the target is safe')
misspelling spotted !

2021-06-08 13:20 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +  def check
Wow cool ! It seems there are a lot of tricks around in msf library but it's not easy to find them...

2021-06-08 13:27 UTC, bcoles commented on documentation/modules/exploit/windows/http/nscp_authenticated_rce.md
> +
> 
> 
> Okay didn't know that, I thought that the documentation file was a kind of "follow all the steps and this module will work for sure".

It is, but that's what the numbered list above is for.

Also `rhosts` is implied and we end up with the same text in every module document.

There are also lots of other options that a user might want to set which might be required in some instances, but we don't include in the documentation (`WfsDelay` for laggy connections, `SSL` if the host is behind a non-HTTPS reverse proxy for some reason, etc).

2021-06-08 13:28 UTC, bcoles commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +  def check
This is fairly "new" (a couple years old). The best way to find them is to look at existing modules. The newer modules use the latest and greatest features.

2021-06-08 13:28 UTC, bcoles commented on documentation/modules/exploit/windows/http/nscp_authenticated_rce.md
> +
Also, the `msfdocs_tidy` utility might be useful. It should warn you if your documentation file contains errors or bad practices.

https://github.com/rapid7/metasploit-framework/blob/master/tools/dev/msftidy_docs.rb

2021-06-08 13:31 UTC, Hakyac commented
All suggestions should be added, if something is missing, feel free to correct it.

2021-06-08 13:37 UTC, Hakyac commented on documentation/modules/exploit/windows/http/nscp_authenticated_rce.md
> +
> > Okay didn't know that, I thought that the documentation file was a kind of "follow all the steps and this module will work for sure".
> 
> It is, but that's what the numbered list above is for.
> 
> Also `rhosts` is implied and we end up with the same text in every module document.
> 
> There are also lots of other options that a user might want to set which might be required in some instances, but we don't include in the documentation (`WfsDelay` for laggy connections, `SSL` if the host is behind a non-HTTPS reverse proxy for some reason, etc).

Understood !

2021-06-08 13:39 UTC, Hakyac commented on documentation/modules/exploit/windows/http/nscp_authenticated_rce.md
> +
> Also, the `msfdocs_tidy` utility might be useful. It should warn you if your documentation file contains errors or bad practices.
> 
> https://github.com/rapid7/metasploit-framework/blob/master/tools/dev/msftidy_docs.rb

Okay I will add that to my good practice routine 😁 Shouldn't it be added to the list of auto-check on github ?

2021-06-08 13:43 UTC, bcoles commented on documentation/modules/exploit/windows/http/nscp_authenticated_rce.md
> +
> Okay I will add that to my good practice routine grin Shouldn't it be added to the list of auto-check on github ?

I thought it had been. Here's the relevant check anyway:

https://github.com/rapid7/metasploit-framework/blob/66de4deabf9a403b42cc70f0e94f7d586de3c4e7/tools/dev/msftidy_docs.rb#L247-L250

2021-06-08 13:44 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +  def check
Yeah I agree with you that learning by imitating is good practice to learn that kind of tricks. But a more complete documentation is definitely needed in my opinion 🙂 (although I know how much trouble/pain it is to keep it up to date).

2021-06-08 13:48 UTC, bcoles commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +  def check
There's plenty of documentation - but it's not up to date.

* https://github.com/rapid7/metasploit-framework/wiki#contributing
* https://github.com/rapid7/metasploit-framework/blob/master/CONTRIBUTING.md
* https://github.com/rapid7/metasploit-framework/wiki/Contributing-to-Metasploit
* https://github.com/rapid7/metasploit-framework/wiki/How-to-write-a-check%28%29-method

For those who can read Ruby, the source code is the best documentation and is always up to date.

2021-06-08 13:54 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +  def check
Yes I have already read those links 😀 and I was talking about them when I said "a more complete documentation" cause as you said it's not up to date.

2021-06-08 14:11 UTC, bcoles commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +  def check
I don't think it is possible to give write permissions to a user for only the wiki portion of a repository, but if you write some documentation and submit it as an issue perhaps a contributor will make the changes for you and credit you in the diff.

I've updated the `How to write a check() method` page.

* https://github.com/rapid7/metasploit-framework/wiki/How-to-write-a-check()-method/_compare/65fed5ee3fc21b3e4f01c4ada650e0ad5bc9054a

2021-06-08 14:22 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +  def check
Thanks for adding it to the documentation. Every time someone suggests me something new or I find a new feature, I write it down in a notepad. If all those notes grow to big I may consider writing a kind of documentation with it as it could help someone else.

2021-06-08 14:26 UTC, bcoles commented on documentation/modules/exploit/windows/http/nscp_authenticated_rce.md
> +Set the PASSWORD of the admin account of NSClient++.
The documentation should include a `Scenarios` section with example output from using the module.

Refer to the template.

* https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/module_doc_template.md

2021-06-08 14:26 UTC, bcoles commented on documentation/modules/exploit/windows/http/nscp_authenticated_rce.md
> +This module allows an attacker with knowledge of the admin password of NSClient++ 0.5.2.35 to start a privilege reverse shell.
```suggestion
This module allows an attacker with knowledge of the admin password of NSClient++ 0.5.2.35 to start a privileged reverse shell.
```

2021-06-08 14:26 UTC, bcoles commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +        'Privileged' => false,
The module documentation suggests that a privileged session is obtained. Does NSClient run as admin/system by default ? If so, this should be `true`. If not, then the module documentation is incorrect.

```suggestion
        'Privileged' => true,
```

2021-06-08 14:26 UTC, bcoles commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +      CheckCode::Unknown('Unable to get an authentification token, maybe the target is safe')
Authentification is not a cromulent word.

```suggestion
      CheckCode::Unknown('Unable to get an authentication token, maybe the target is safe')
```

2021-06-08 14:26 UTC, bcoles commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +        'Name' => 'NSClient++ 0.5.2.35 - Authenticated Remote Code Execution',
I presume the functionality exploited in this module is an intended feature? It looks like you're uploading a plugin, which presumably can execute arbitrary code by design. If so, the version number isn't relevant for the module title.

I haven't looked into the feature / "vulnerability" at all, but perhaps `NSClient++ ExternalScripts Authenticated Remote Code Execution` is a better title, as `ExternalScripts` is a necessary (and non-default?) component for exploitation.

2021-06-08 14:26 UTC, bcoles commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +    if !r.body.to_s.include? 'STATUS_OK'
`r` could be `nil` here if the connection fails.

2021-06-08 14:26 UTC, bcoles commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +    print_status('Timeout exceeded. Assuming your payload executed . . .')
This `rescue` branch can be reached for more reasons than a timeout. A connection failure for example. Assuming that the payload executed seems like an unsafe assumption.

2021-06-08 14:40 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +        'Name' => 'NSClient++ 0.5.2.35 - Authenticated Remote Code Execution',
Yes it is non-default, I added this to the name.

2021-06-08 14:49 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +    print_status('Timeout exceeded. Assuming your payload executed . . .')
How can I know for which reason this `rescue` branch was reached ?

2021-06-08 15:21 UTC, agalway-r7 commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +    print_status('Timeout exceeded. Assuming your payload executed . . .')
Best thing that jumps to mind is make the error message generic, something like:

```
print_error("Request could not be sent. #{e.class} error raised with message '#{e.message}'")
```

That'll let you know what error was thrown and aid in any future debugging needed

2021-06-08 15:56 UTC, Hakyac commented on modules/exploits/windows/http/nscp_authenticated_rce.rb
> +    print_status('Timeout exceeded. Assuming your payload executed . . .')
Seems to be a good idea. I will also use `fail_with(Failure::Unknown, ...)` to prevent the following lines from being executing.

2021-06-08 15:57 UTC, Hakyac commented on documentation/modules/exploit/windows/http/nscp_authenticated_rce.md
> +Set the PASSWORD of the admin account of NSClient++.
Done !

2021-06-09 07:10 UTC, Hakyac commented
All suggestions should have been added now 😉

2021-06-09 14:38 UTC, merged

2021-06-09 14:43 UTC, agalway-r7 commented
## Release Notes

This module allows an attacker with knowledge of the admin password of NSClient++ 0.5.2.35 to start a privilege reverse shell, so long as the attacker has the admin password, and the NSClient++has both the web interface and ExternalScriptsfeature enabled.

2021-06-09 15:38 UTC, Hakyac commented
Thanks !