added Sage X3 modules
rapid7/metasploit-framework pull request #15400
Opened 2021-07-07 16:24 UTC by deadjakk

This exploits a vulnerability in the Sage X3 administrative service which results in an unauthenticated remote command execution. This branch contains the following three files:
- modules/exploits/x3/x3_adxsrv_cmd.rb | the remote command execution exploit module
- modules/auxiliary/scanner/x3/x3_adxsrv_login.rb | a login scanner for the X3 service
- lib/metasploit/framework/login_scanner/x3.rb | a ruby port of the X3Crypt function used by the X3 service for x3_login

Reference: https://www.rapid7.com/blog/post/2021/07/07/cve-2020-7387-7390-multiple-sage-x3-vulnerabilities/
Tagging @wvu-r7 per request

## Verification

- [ ] Start `msfconsole`
- [ ] `use exploit/x3/x3_adxsrv_cmd`
- [ ] set the RHOSTS
- [ ] set the RPORT
- [ ] `run`
- [ ] Confirm you received the output `nt authority\system`

## Output Images

### Remote Command Exploit

![screenshot-show-info](https://user-images.githubusercontent.com/30613497/124795640-dbcec300-df15-11eb-914a-3a576c835a97.png)

![screenshot-all-targets-running](https://user-images.githubusercontent.com/30613497/124795630-da04ff80-df15-11eb-9595-2e6f9407c650.png)

### Login Scanner 

![screenshot-login-scanner](https://user-images.githubusercontent.com/30613497/124795590-cd80a700-df15-11eb-9bdf-2d6b07ead109.png)

2021-07-07 22:33 UTC, bcoles reviewed
A couple of these files are missing license headers.

Also, not that it really matters, but sometimes review can take a while, and modules can be merged faster if they're split into multiple PRs. ie, one PR for the login scanner library + module, and one for the exploit module. However, if the exploit module is going to be updated to use the scanner modules as a `CheckModule` then disregard this comment.

2021-07-07 22:33 UTC, bcoles commented on modules/exploits/x3/x3_adxsrv_cmd.rb
> +  end
`Msf::Exploit::` prefix is redundant in exploit context.

```suggestion
  def check
    adxdir ? CheckCode::Appears : CheckCode::Safe
  end
```

2021-07-07 22:33 UTC, bcoles commented on modules/exploits/x3/x3_adxsrv_cmd.rb
> +    end
`fail_with` is preferred over `print_error(..); return` code pattern. (here, and elsewhere in the module)

```suggestion
    if (target.name == 'Windows Command') && payload.blank?
      fail_with(Failure::BadConfig, 'Exploit target requires CMD to be set')
    end
```

2021-07-07 22:33 UTC, bcoles commented on modules/exploits/x3/x3_adxsrv_cmd.rb
> +        'Name' => 'Sage X3 Administration Service Command Execution',
It is possible that in the future there will be multiple command execution vulnerabilities in this service.

At a glance, it appears as though executing arbitrary commands is intended functionality.

In which case, a more suitable module name should reference the authentication bypass as the key component of the exploit, ie: `Sage X3 Administration Service Authentication Bypass Command Execution`. The filename should also roughly match the module name, ie: `x3_adxsrv_auth_byoass_cmd_exec.rb`.

Alternatively, optionally, if command execution is intended functionality, this module could by updated to support a username and password combination to gain code execution, and a separate option to override with auth bypass instead.

2021-07-07 22:33 UTC, bcoles commented on modules/exploits/x3/x3_adxsrv_cmd.rb
> +        'DisclosureDate' => '2020-07-07',
Presumably this should be `2021`.

```suggestion
        'DisclosureDate' => '2021-07-07',
```

2021-07-07 22:33 UTC, bcoles commented on modules/exploits/x3/x3_adxsrv_cmd.rb
> +    filenum = filenum.to_s
```suggestion
    filenum = rand(10_000_000..99_999_999).to_s
```

2021-07-07 22:33 UTC, bcoles commented on modules/exploits/x3/x3_adxsrv_cmd.rb
> +    sagedir = adxdir
This could use some error handling and feedback to the operator. `adxdir` can return `false`.

```
irb(main):001:0> false.gsub(/a/, 'b')
Traceback (most recent call last):
	19: from /usr/local/bin/irb:23:in `<main>'
	18: from /usr/local/bin/irb:23:in `load'
	17: from /var/lib/gems/2.7.0/gems/irb-1.3.6/exe/irb:11:in `<top (required)>'
(irb):1:in `<main>': undefined method `gsub' for false:FalseClass (NoMethodError)
irb(main):002:0> 
```

2021-07-07 22:33 UTC, bcoles commented on modules/exploits/x3/x3_adxsrv_cmd.rb
> +      payload = datastore['CMD']
`payload` has a special meaning. Generally `payload` should not be clobbered.

Perhaps @wvu-r7 has some additional commentary here.

2021-07-08 00:46 UTC, deadjakk commented on modules/exploits/x3/x3_adxsrv_cmd.rb
> +    end
Changed all instances in [this commit](https://github.com/deadjakk/metasploit-framework/commit/fa98e9a3a407d740d5e6346ed2d1f2a683d5788c)

2021-07-08 00:47 UTC, deadjakk commented on modules/exploits/x3/x3_adxsrv_cmd.rb
> +        'Name' => 'Sage X3 Administration Service Command Execution',
Renamed file and updated name in [this commit](https://github.com/deadjakk/metasploit-framework/commit/fa98e9a3a407d740d5e6346ed2d1f2a683d5788c)

2021-07-08 00:47 UTC, deadjakk commented on modules/exploits/x3/x3_adxsrv_cmd.rb
> +    filenum = filenum.to_s
Updated in [this commit](https://github.com/deadjakk/metasploit-framework/commit/fa98e9a3a407d740d5e6346ed2d1f2a683d5788c)

2021-07-08 00:47 UTC, deadjakk commented on modules/exploits/x3/x3_adxsrv_cmd.rb
> +    sagedir = adxdir
Added checking of returned value in [this commit](https://github.com/deadjakk/metasploit-framework/commit/fa98e9a3a407d740d5e6346ed2d1f2a683d5788c)

2021-07-08 00:48 UTC, deadjakk commented on modules/exploits/x3/x3_adxsrv_cmd.rb
> +      payload = datastore['CMD']
Updated from 'payload' to 'sage_payload' [here](https://github.com/deadjakk/metasploit-framework/commit/fa98e9a3a407d740d5e6346ed2d1f2a683d5788c)

2021-07-08 00:50 UTC, deadjakk commented on modules/exploits/x3/x3_adxsrv_cmd.rb
> +      payload = datastore['CMD']
License still needs to be added

2021-07-08 02:01 UTC, wvu-r7 commented on modules/exploits/x3/x3_adxsrv_cmd.rb
> +      payload = datastore['CMD']
@bcoles is correct.

2021-07-08 14:26 UTC, smcintyre-r7 requested changes, later dismissed

2021-07-08 14:26 UTC, smcintyre-r7 commented on lib/metasploit/framework/login_scanner/x3.rb
> +          charset_1 = 'cf2tln3yuVkDr7oPaQ8bsSd4x'.split('')
Instead of splitting on an empty string you can use the `String#chars` method.

```suggestion
          charset_0 = 'cromanwqxfzpgedkvstjhyilu'.chars
          xyz = 'zxWyZxzvwYzxZXxxZWWyWxYXz'.chars
          charset_1 = 'cf2tln3yuVkDr7oPaQ8bsSd4x'.chars
```

2021-07-08 14:26 UTC, smcintyre-r7 commented on lib/metasploit/framework/login_scanner/x3.rb
> +              ret += charset_1[off].ord.chr
When concatenating strings, the `<<` operator is preferred vs the `+=` operator.

2021-07-08 14:26 UTC, smcintyre-r7 commented on lib/metasploit/framework/login_scanner/x3.rb
> +            # add the password
Since all of this is data that is being locally processed, there shouldn't be any connection or timeout errors. That means that this should be able to be moved outside of the exception handling block so only the network related code is protected.

2021-07-08 14:26 UTC, smcintyre-r7 commented on lib/metasploit/framework/login_scanner/x3.rb
> +        DEFAULT_PORT = 50000
This looks like it may have been left over from the db2 login scanner. The module you provide in this PR uses TCP port 1818 as the default which aligns with the statement from the [disclosure](https://www.rapid7.com/blog/post/2021/07/07/cve-2020-7387-7390-multiple-sage-x3-vulnerabilities/) you reference (see the "CVE-2020-7388: Sage X3 Unauthenticated Remote Command Execution (RCE) as SYSTEM in AdxDSrv.exe component" section).

2021-07-08 14:26 UTC, smcintyre-r7 commented on modules/auxiliary/scanner/x3/x3_adxsrv_login.rb
> +  Rank = GreatRanking
Non-exploit modules don't need a `Rank` to be defined. That's used to imply the exploits stability but since this is a login scanner it's not necessary.

2021-07-08 14:26 UTC, smcintyre-r7 commented on modules/exploits/x3/x3_adxsrv_auth_bypass_cmd_exec.rb
> +    adxdir ? CheckCode::Appears : CheckCode::Safe
If the directory is nil, the `adxdir` method will raise a runtime exception via `fail_with` which won't be caught and turned into a proper `CheckCode` constant here. This should add a bit of error handling to catch that and some timeout / connection errors which would map to `CheckCode::Unknown`.

2021-07-08 14:26 UTC, smcintyre-r7 commented on modules/exploits/x3/x3_adxsrv_auth_bypass_cmd_exec.rb
> +          ],
The `Msf::Exploit::EXE` mixin you're using registers a `EXE::Custom` option already that can be used by the user to specify a custom executable of their choice instead of having Metasploit generate it for them. That option should be able to be used with the "Windows Executable" target to achieve the desired effect. That also means that the `FILENAME` option you're registering on L97 should be unnecessary.

If you think this is something that users are likely going to want to do with this module you could update the module docs to include a walk through explanation as a scenario.

2021-07-08 14:26 UTC, smcintyre-r7 commented on modules/exploits/x3/x3_adxsrv_auth_bypass_cmd_exec.rb
> +        OptPath.new('FILENAME', [false, 'File for \'Custom Executable\' target', '']),
See the comment above regarding `EXE::Custom`.

2021-07-08 14:26 UTC, smcintyre-r7 commented on modules/exploits/x3/x3_adxsrv_auth_bypass_cmd_exec.rb
> +      fail_with(Failure::BadConfig, 'Select a different target or set CMD option')
Windows command payloads have more options than just the generic one that allows the user to set their own command. You should be able to set `sage_payload` to `payload.encoded` when the target is 'Windows Command' to allow any of the Windows command payloads to work with this module including the default generic one.

2021-07-08 14:26 UTC, smcintyre-r7 commented on modules/exploits/x3/x3_adxsrv_auth_bypass_cmd_exec.rb
> +    end
This should all be handled for you automatically using the `EXE::Custom` option.

2021-07-08 14:26 UTC, smcintyre-r7 commented on modules/exploits/x3/x3_adxsrv_auth_bypass_cmd_exec.rb
> +    filenum = rand(10_000_000..99_999_999).to_s
To generate a number that's 8 characters wide, you can use `rand_text_numeric` method.

```suggestion
    filenum = rand_text_numeric(8)
```

2021-07-08 14:26 UTC, smcintyre-r7 commented on modules/exploits/x3/x3_adxsrv_auth_bypass_cmd_exec.rb
> +      sage_payload = "rundll32.exe #{sagedir}\\tmp\\cmd#{filenum}.dll,0"
Since you're running the payload with rundll32, the user probably should know that so they can ensure the proper exports are provided. You can just call that out in the module docs.

2021-07-08 23:15 UTC, deadjakk commented on lib/metasploit/framework/login_scanner/x3.rb
> +              ret += charset_1[off].ord.chr
Made this change in [dadc59e](https://github.com/deadjakk/metasploit-framework/commit/dadc59ebbe66e376f78da31c4236cee78841f841)

2021-07-08 23:16 UTC, deadjakk commented on lib/metasploit/framework/login_scanner/x3.rb
> +            # add the password
I moved the 'begin' line down to make this make more sense

[dadc59e](https://github.com/deadjakk/metasploit-framework/commit/dadc59ebbe66e376f78da31c4236cee78841f841)

2021-07-08 23:17 UTC, deadjakk commented on lib/metasploit/framework/login_scanner/x3.rb
> +        DEFAULT_PORT = 50000
Changed this to the appropriate value [here](https://github.com/deadjakk/metasploit-framework/commit/dadc59ebbe66e376f78da31c4236cee78841f841#diff-69e45fbe19c9e6a666ce90d7e348cc26797622eb8c5df60a26308905dc4d1270L17)

2021-07-08 23:19 UTC, deadjakk commented on modules/auxiliary/scanner/x3/x3_adxsrv_login.rb
> +  Rank = GreatRanking
Removed this line [dadc59e](https://github.com/deadjakk/metasploit-framework/commit/dadc59ebbe66e376f78da31c4236cee78841f841)

2021-07-08 23:21 UTC, deadjakk commented on modules/exploits/x3/x3_adxsrv_auth_bypass_cmd_exec.rb
> +    adxdir ? CheckCode::Appears : CheckCode::Safe
Basically copied the code from the adxdir function and changed the returned values, It wasn't the most elegant, but the adxdir function wasn't very long... [here](https://github.com/deadjakk/metasploit-framework/commit/dadc59ebbe66e376f78da31c4236cee78841f841)

2021-07-08 23:21 UTC, deadjakk commented on modules/exploits/x3/x3_adxsrv_auth_bypass_cmd_exec.rb
> +          ],
Removed in favor of the EXE::Custom solution

2021-07-08 23:22 UTC, deadjakk commented on modules/exploits/x3/x3_adxsrv_auth_bypass_cmd_exec.rb
> +        OptPath.new('FILENAME', [false, 'File for \'Custom Executable\' target', '']),
Removed in favor of the EXE::Custom solution

2021-07-08 23:23 UTC, deadjakk commented on modules/exploits/x3/x3_adxsrv_auth_bypass_cmd_exec.rb
> +      fail_with(Failure::BadConfig, 'Select a different target or set CMD option')
Changed it to payload.encoded, it worked for cmd/windows/powershell_reverse_tcp, though most of the others I tried failed

2021-07-08 23:24 UTC, deadjakk commented on modules/exploits/x3/x3_adxsrv_auth_bypass_cmd_exec.rb
> +    end
Removed these lines [here](https://github.com/deadjakk/metasploit-framework/commit/dadc59ebbe66e376f78da31c4236cee78841f841#diff-620785ce2f86678cedae6b1fdec734e80dda34135c29554f3f62440479097dc1L218)

2021-07-08 23:27 UTC, deadjakk commented on modules/exploits/x3/x3_adxsrv_auth_bypass_cmd_exec.rb
> +      sage_payload = "rundll32.exe #{sagedir}\\tmp\\cmd#{filenum}.dll,0"
The dll being pushed isn't loaded by an application or provided by the user, just run outright with rundll32 using the dll generated by MSF.

2021-07-09 03:21 UTC, wvu-r7 commented on modules/exploits/x3/x3_adxsrv_auth_bypass_cmd_exec.rb
> +            [ 'CVE', 'CVE-2020-7387']
```suggestion
            [ 'CVE', '2020-7388'],
            [ 'CVE', '2020-7387']
```

2021-07-21 01:37 UTC, merged

2021-07-21 01:42 UTC, wvu-r7 commented
# Release Notes

Added a Sage X3 login scanner and [CVE-2020-7387 + CVE-2020-7388](https://www.rapid7.com/blog/post/2021/07/07/cve-2020-7387-7390-multiple-sage-x3-vulnerabilities/) exploit.