Update local exploit suggester to handle nil targets
rapid7/metasploit-framework pull request #15465
Opened 2021-07-23 15:00 UTC by sjanusz-r7

This PR fixes an issue with local_exploit_suggester, where it would crash if i encountered a module with a nil target property.

### Before
When a module returns a nil target:
![image](https://user-images.githubusercontent.com/85949464/126800529-4f8b8aeb-35ac-4d6c-91c1-99ddf4b1a64d.png)

### After
![image](https://user-images.githubusercontent.com/85949464/126797938-39908ca8-7f6f-4980-8968-0473e6a455e1.png)

## Verification

List the steps needed to make sure this thing works

- [ ] Apply this patch
```diff
diff --git a/lib/msf/core/exploit.rb b/lib/msf/core/exploit.rb
index 8f7891cef2..94b8bbdd86 100644
--- a/lib/msf/core/exploit.rb
+++ b/lib/msf/core/exploit.rb
@@ -634,6 +634,10 @@ class Exploit < Msf::Module
   # default target, that one will be automatically used.
   #
   def target
+    if self.fullname == "exploit/windows/local/ms10_092_schelevator"
+      return nil
+    end
     if self.respond_to?(:auto_targeted_index)
       if auto_target?
         auto_idx = auto_targeted_index
```
- [ ] Start `msfconsole`
- [ ] Get a session
- [ ] Use local_exploit_suggester
- [ ] **Verify** the exploit suggester doesn't crash

2021-07-23 16:05 UTC, adfoster-r7 commented on modules/post/multi/recon/local_exploit_suggester.rb
> +          checkcode = m.check
We might need to have the original exception handling below higher up now, since it looks like it might have been relying on `Rex::Post::Meterpreter::RequestError` to be raised when the session is dead? 🤔

Probably worth double checking 🕵️

2021-07-23 19:49 UTC, jmartin-r7 commented on modules/post/multi/recon/local_exploit_suggester.rb
> +        rescue => e
I am not a super fan of global rescue here, is there some way to restrict what is caught here more?

2021-07-23 19:49 UTC, jmartin-r7 commented on modules/post/multi/recon/local_exploit_suggester.rb
> +          elog("#{m.shortname} failed to run", error: e)
Let's be consistent on providing verbose output and not just send the error to a log.
```suggestion
          elog("#{m.shortname} failed to run", error: e)
          vprint_error "#{e.class} #{m.shortname} failed to run: #{e.message}"
```

2021-07-23 20:16 UTC, adfoster-r7 commented on modules/post/multi/recon/local_exploit_suggester.rb
> +        rescue => e
I think the problem is a module's check method can fail for lots of reasons, including regression issues in core library files unfortunately, it would be impossible to catch them all accurately.

Examples:
- ArgumentError - https://github.com/rapid7/metasploit-framework/issues/15370
- NoMethodError - https://github.com/rapid7/metasploit-framework/issues/15372
- Constant NameError - https://github.com/rapid7/metasploit-framework/issues/14974
- local variable NameError - https://github.com/rapid7/metasploit-framework/issues/14649
- Explicit `fail_with` call - https://github.com/rapid7/metasploit-framework/issues/13850
- NoMethodError - https://github.com/rapid7/metasploit-framework/issues/12499

2021-07-23 20:18 UTC, adfoster-r7 commented on modules/post/multi/recon/local_exploit_suggester.rb
> +          elog("#{m.shortname} failed to run", error: e)
Logging happens later:
```
        if checkcode.nil?
          vprint_error "#{m.fullname}: Check failed"
          next
        end
```

But this could definitely be tweaked to be more clear to the user that something went more wrong than normal 😄

2021-07-26 11:26 UTC, adfoster-r7 requested changes

2021-07-26 11:26 UTC, adfoster-r7 commented on modules/post/multi/recon/local_exploit_suggester.rb
> +      rescue Rex::Post::Meterpreter::RequestError => e
Out of interest, what's the rationale behind special casing this exception in particular? 👀

2021-07-26 11:27 UTC, adfoster-r7 commented on modules/post/multi/recon/local_exploit_suggester.rb
> +      rescue Rex::Post::Meterpreter::RequestError => e
I know it was there previously, but was it investigated in more detail whether it's needed still? 🕵️

2021-07-26 11:32 UTC, agalway-r7 commented on modules/post/multi/recon/local_exploit_suggester.rb
> +      rescue Rex::Post::Meterpreter::RequestError => e
If I'm not confuddled, it's that this error indicates the session is borked and that you can't run any more checks, where as any other error indicates it was just the check that had an issue

2021-07-28 09:16 UTC, adfoster-r7 commented on modules/post/multi/recon/local_exploit_suggester.rb
> +      rescue Rex::Post::Meterpreter::RequestError => e
It's raised in other circumstances too:
```
meterpreter > run post/windows/manage/migrate

[*] Running module against HOME-F006222D6C
[*] Current server process: webappmon.exe (7064)
[*] Spawning notepad.exe process to migrate to
[-] Post failed: Rex::Post::Meterpreter::RequestError stdapi_sys_process_execute: Operation failed: Access is denied.
[-] Call stack:
[-]   /projects/exploiting/trunk/lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb:163:in `execute'
[-]   (eval):80:in `create_temp_proc'
[-]   (eval):49:in `run'
=end
```

2021-07-28 09:17 UTC, adfoster-r7 commented on modules/post/multi/recon/local_exploit_suggester.rb
> +        break
```suggestion
```

2021-07-28 10:37 UTC, adfoster-r7 approved these changes
Just waiting on jenkins 🐌

2021-07-28 11:07 UTC, adfoster-r7 commented
@msjenkins-r7 retest this please

2021-07-28 14:55 UTC, merged

2021-07-28 15:00 UTC, adfoster-r7 commented
## Release Notes

Updates the local exploit suggester to gracefully handle modules raising unintended exceptions and nil target information