CVE-2021-36934 HiveNightmare aka SeriousSam - SAM hashes leak
rapid7/metasploit-framework pull request #15462
Opened 2021-07-23 13:14 UTC by Hakyac

2021-07-23 19:01 UTC, smcintyre-r7 commented
I'm pretty sure the `auxiliary/gather/windows_secrets_dump` module has the ability to extract the information out of a SAM file. The code is inlined in the module though, we'd want to extract it and place it into a reusable location to void copy-and-pasting a large chunk of it.

As for the difficulties with reading the file, I'd strongly suggest you avoid it entirely and invoke the necessary `CreateFile` call directly via railgun. It would have the disadvantage of only working with a Meterpreter session, but it wouldn't spawn a subprocess or rely on Powershell being available.

Finally if that's the game plan, this should be a post module.

2021-07-23 19:28 UTC, smcintyre-r7 commented
It would also be worth checking if you could even just use the `read_file` method from the File mixin with a Meterpreter session. IIRC, under the hood that will call `CreateFile` and could be the easiest way to access the contents. If that doesn't work though, then you will probably need to use railgun.

2021-07-24 02:02 UTC, bcoles commented on modules/auxiliary/gather/hivenightmare_windows_sam_leak.rb
> +              ['URL', 'https://github.com/romarroca/SeriousSam']
PoC exploit:

* https://github.com/GossiTheDog/HiveNightmare

Associated writeup:

* https://doublepulsar.com/hivenightmare-aka-serioussam-anybody-can-read-the-registry-in-windows-10-7a871c465fa5

There are a bunch of other posts about the bug. ISC has one of the better writeups:

* https://isc.sans.edu/diary/Summer+of+SAM+-+incorrect+permissions+on+Windows+1011+hives/27652

2021-07-24 02:03 UTC, bcoles commented
> It would have the disadvantage of only working with a Meterpreter session

This post discusses some techniques (`certutil` and `esentutl.exe`) which may be useful for non-meterpreter sessions:

* https://spyx.github.io/CVE-2021-36934/

2021-07-24 02:04 UTC, bcoles commented on modules/auxiliary/gather/hivenightmare_windows_sam_leak.rb
> +            return
is there any value in retrieving additional hives rather than bailing out after the first one that is found?

2021-07-26 17:15 UTC, Hakyac commented
@smcintyre-r7 Thank you for you suggestions 😃 I tried to use `read_file` from Meterpreter but it didn't work, so I used `railgun` as you suggested and it worked ! I didn't know that powerful module so it took me some time to understand it. It is now possible to retrieve both SAM and SYSTEM files by bruteforcing all possible index until the max index given. The most recent one is now chosen as the one to be stored with `store_loot()` (and not anymore the first one found as @bcoles raised the question). It is also possible to specify an index instead of scanning files. Just in case someone wants to retrieve other files than the latest modified one.

@bcoles Thanks for your suggestions too, I added those links.

Current issues/questions : 
- @smcintyre-r7 you said it should be a Post module, but I thought Post module were only used when you already have a privileged access on the target. Moreover, I think it is worth to have a `check` method, but as I understand, Post modules can't have one. How could it be done ?
- For some reason I can't explain, the command `icacls c:\windows\system32\config\SAM` is not working with a meterpreter session (after using `shell` command). Even if I launch `powershell.exe` from that shell. However it does work if I use a powershell session, do you have any idea ?
- I don't understand why at the end of the retrieve files there is a `A`. It seems to come from the default value filling the reading buffer, but I don't understand why `res_reading['lpBuffer'][0..res_reading['lpNumberOfBytesRead']]` reads more than just the necessary bytes. Maybe the reading function counts the null byte ending the file and doesn't write it in the buffer ? That could explain why I should read until something like `res_reading['lpNumberOfBytesRead']-1` at the end ? Feel free to give me your explanations 😃
- For now, one can use `secretsdump.py` for instance to dump the hashes from SAM files. I think dumping those hashes directly from this module would be great. As you mentioned @smcintyre-r7, there seems to be all the needed code in the great `auxiliary/gather/windows_secrets_dump`. But it is rather long and I have not yet clearly indentified which parts of it I need to reuse. Is there some ongoing attempts to make this module more reusable ?

2021-07-27 17:14 UTC, smcintyre-r7 commented
It should be a post module because it requires a session and does not deliver a payload. The privilege level has nothing to do with whether it should be a post module or not. If you can write a `check` method, that's great if not that's fine too since it's not an exploit. If possible I'd strongly prefer to avoid using Powershell at all. If you're using railgun you're doing everything in memory without spawning any new processes, which is a very strong position to be in from a detection perspective. If you really want the check method, you may be able to find a Win32 API function that can fetch the access permissions as icacls does but again without spawning a new process.

For your buffer problem try using `res_reading['lpBuffer'][0...res_reading['lpNumberOfBytesRead']]` (note the 3 dots instead of 2). When you want the first X number of elements in an array you need to use 3 dots. 

```
2.7.2 :002 > "testing"[0..2]
 => "tes" 
2.7.2 :003 > "testing"[0...2]
 => "te" 
2.7.2 :004 >
```

Saving the file and requiring the user to run `secretsdump.py` is fine for now. If you wouldn't mind, it'd be great to call that out with the steps in the module docs. Once our secrets dump work is done, we're planning to refactor that functionality into a library method and we can then come back to this and populate the secrets into the database automatically.

2021-07-28 09:10 UTC, Hakyac commented
> It should be a post module because it requires a session and does not deliver a payload. The privilege level has nothing to do with whether it should be a post module or not. If you can write a `check` method, that's great if not that's fine too since it's not an exploit. If possible I'd strongly prefer to avoid using Powershell at all. If you're using railgun you're doing everything in memory without spawning any new processes, which is a very strong position to be in from a detection perspective. If you really want the check method, you may be able to find a Win32 API function that can fetch the access permissions as icacls does but again without spawning a new process.
> 
> For your buffer problem try using `res_reading['lpBuffer'][0...res_reading['lpNumberOfBytesRead']]` (note the 3 dots instead of 2). When you want the first X number of elements in an array you need to use 3 dots.
> 
> ```
> 2.7.2 :002 > "testing"[0..2]
>  => "tes" 
> 2.7.2 :003 > "testing"[0...2]
>  => "te" 
> 2.7.2 :004 >
> ```
> 
> Saving the file and requiring the user to run `secretsdump.py` is fine for now. If you wouldn't mind, it'd be great to call that out with the steps in the module docs. Once our secrets dump work is done, we're planning to refactor that functionality into a library method and we can then come back to this and populate the secrets into the database automatically.

Thanks for your full answer ! I made some minor changes such as changing this module from auxiliary to post or adding a documentation file, and I opened this PR.
Feel free to keep me posted when the dump hashes functionality will be available 🙂

2021-07-28 13:07 UTC, smcintyre-r7 requested changes
Great work, I left a few comments throughout the module.

One thing else I'd like to call out is that there shouldn't be a space before an exclamation point in any of the status messages. This shows up in multiple places and they should all be fixed, for example: ` SAM data found in HarddiskVolumeShadowCopy5 !` should be ` SAM data found in HarddiskVolumeShadowCopy5!`.

2021-07-28 13:07 UTC, smcintyre-r7 commented on documentation/modules/post/windows/gather/credentials/windows_sam_hivenightmare.md
> +See the following output :
Minor suggestion:

```suggestion
See the following output:
```

Also would you be able to please add a note about how secretsdump.py should be used and maybe even the syntax to then extract the goods out of the SAM file? That could really help folks that are looking to use this module.

2021-07-28 13:38 UTC, Hakyac commented
Thanks for your suggestions, and my apologises for the spaces before "!". That's a French habit I'm struggling to get rid of 😁
I've just seen that it seems I messed up with the git branches when I created my PR. That's why there are conflicts with files from "Wordpress plugin modern events calendar rce" which I published recently. I may have not properly rebased to the master branch before creating this new one. When everything is okay for you, I could create a new PR with just the two files that interest us here.

2021-07-29 13:46 UTC, jmartin-r7 commented on modules/post/windows/gather/credentials/windows_sam_hivenightmare.rb
> +      OptInt.new('NBRE_ITER', [true, 'Number of iterations on Shadow Copy file index', 10]),
```suggestion
      OptInt.new('ITERATIONS', [true, 'Number of iterations on Shadow Copy file index', 10]),
```

2021-07-29 13:46 UTC, jmartin-r7 commented on modules/post/windows/gather/credentials/windows_sam_hivenightmare.rb
> +      for i in 0..datastore['NBRE_ITER']
```suggestion
      for i in 0..datastore['ITERATIONS']
```

2021-07-29 13:46 UTC, jmartin-r7 commented on modules/post/windows/gather/credentials/windows_sam_hivenightmare.rb
> +      fail_with(Failure::BadConfig, 'Please specify an iteration number greater than 0!') unless datastore['NBRE_ITER'] > 0
```suggestion
      fail_with(Failure::BadConfig, 'Please specify an iteration number greater than 0!') unless datastore['ITERATIONS'] > 0
```

2021-07-29 13:46 UTC, jmartin-r7 commented on documentation/modules/post/windows/gather/credentials/windows_sam_hivenightmare.md
> +3. `set NBRE_ITER <number>` to specify the number of iterations on file index (default is 10)
```suggestion
3. `set ITERATIONS <number>` to specify the number of iterations on file index (default is 10)
```

2021-07-29 13:46 UTC, jmartin-r7 commented on documentation/modules/post/windows/gather/credentials/windows_sam_hivenightmare.md
> +### NBRE_ITER
```suggestion
### ITERATIONS
```

2021-07-29 13:46 UTC, jmartin-r7 commented on documentation/modules/post/windows/gather/credentials/windows_sam_hivenightmare.md
> +`python3 secretsdump.py -sam <SAM_FILE> -system <SYSTEM_FILE> LOCAL`
Not for future travelers, the project should consider refactor to enable usage of the secrets dump inside framework.

2021-07-29 13:47 UTC, adfoster-r7 commented on modules/post/windows/gather/credentials/windows_sam_hivenightmare.rb
> +        print_error('No Shadow Copy files were found! Maybe you can try again we a greater iteration number...')
```suggestion
        print_error('No Shadow Copy files were found! Maybe you can try again with a greater iteration number...')
```

2021-07-29 13:57 UTC, Hakyac commented on documentation/modules/post/windows/gather/credentials/windows_sam_hivenightmare.md
> +`python3 secretsdump.py -sam <SAM_FILE> -system <SYSTEM_FILE> LOCAL`
I'm not sure to understand your comment

2021-07-29 15:17 UTC, jmartin-r7 commented on documentation/modules/post/windows/gather/credentials/windows_sam_hivenightmare.md
> +`python3 secretsdump.py -sam <SAM_FILE> -system <SYSTEM_FILE> LOCAL`
This is just a note for the maintainers that we will want to revisit this documentation and module if/when native secrets dump is possible in framework for this module.

2021-07-29 15:48 UTC, smcintyre-r7 approved these changes
Just successfully tested this on a fresh Windows 10 v2004 host. I renamed the NBRE_ITER option to ITERATIONS and made some minor documentation changes to reflect what I had to do while testing in commit ed29212d48a288bf7bcefedaa7ce1617f7e462d7.

I'll handle squashing this down and once the unit tests pass, I'll get this landed. Thanks alot @Hakyac !

```
msf6 post(windows/gather/credentials/windows_sam_hivenightmare) > sessions -i -1
[*] Starting interaction with 3...

meterpreter > sysinfo
Computer        : DESKTOP-UN2GAI7
OS              : Windows 10 (10.0 Build 19041).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 1
Meterpreter     : x64/windows
meterpreter > getuid
Server username: DESKTOP-UN2GAI7\aliddle
meterpreter > getsystem
[-] priv_elevate_getsystem: Operation failed: Access is denied. The following was attempted:
[-] Named Pipe Impersonation (In Memory/Admin)
[-] Named Pipe Impersonation (Dropper/Admin)
[-] Token Duplication (In Memory/Admin)
[-] Named Pipe Impersonation (RPCSS variant)
meterpreter > background 
[*] Backgrounding session 3...
msf6 post(windows/gather/credentials/windows_sam_hivenightmare) > run

[+] SAM data found in HarddiskVolumeShadowCopy1!
[+] Retrieving files of index 1 as they are the most recently modified...
[+] SAM data saved at /home/smcintyre/.msf4/loot/20210729113916_default_192.168.159.15_windows.sam_763500.bin
[+] SYSTEM data saved at /home/smcintyre/.msf4/loot/20210729113926_default_192.168.159.15_windows.system_202176.bin
[+] SAM and SYSTEM data were leaked!
[*] Post module execution completed
msf6 post(windows/gather/credentials/windows_sam_hivenightmare) > file /home/smcintyre/.msf4/loot/20210729113916_default_192.168.159.15_windows.sam_763500.bin
[*] exec: file /home/smcintyre/.msf4/loot/20210729113916_default_192.168.159.15_windows.sam_763500.bin

/home/smcintyre/.msf4/loot/20210729113916_default_192.168.159.15_windows.sam_763500.bin: MS Windows registry file, NT/2000 or above
msf6 post(windows/gather/credentials/windows_sam_hivenightmare) >
```

2021-07-29 16:54 UTC, merged

2021-07-30 06:59 UTC, Hakyac commented on documentation/modules/post/windows/gather/credentials/windows_sam_hivenightmare.md
> +`python3 secretsdump.py -sam <SAM_FILE> -system <SYSTEM_FILE> LOCAL`
Okay thanks for clarifying, I was not sure whether or not you were expecting me to do something 😉

2021-07-30 12:51 UTC, cdelafuente-r7 commented
# Release Notes
This adds a new exploit module that exploits a configuration issue in Windows 10 (from version 1809) and 11, identified as CVE-2021-36934. Due to permission issues, any local user is able to read SAM and SYSTEM hives. This module abuses Windows Volume Shadow Copy Service (VSS) to access these files and save them locally.