Cookie jar fix for gitlab exploit module issues
rapid7/metasploit-framework pull request #15500
Opened 2021-07-30 14:12 UTC by agalway-r7

Fixes https://github.com/rapid7/metasploit-framework/issues/15456

This fixes two issues with the cookie jar and it's use by the http client, one big and one small:
1) I incorrectly authored the http_cookie_jar `parse` method to create cookies without considering set-cookie headers with no additional attributes.
2) Requests made to an IP address without knowledge of said IP address' domain name (say for example when making requests via a VPN like the one's used in TryHackMe & HackTheBox), would result in the creation of a cookie without a domain attribute, which would cause the `http-cookie` library our jar is built on top of to throw an error. The work around for this is to create an origin for each cookie, which would populate the domain field **if a domain attribute isn't already specified by the server**. 

This may break in the future if the domain is set to the target rhost of a module and if the target server begins to interpret said domain incorrectly and create an error, since a IP address isn't a valid domain. However, in the two modules this PR fixes (`gitlab_file_read_rce` and `cacti_filter_sqli_rce`), said invalid domain is simply ignored and the cookie is treated as a default value, which is the desired functionality.  

List the steps needed to make sure this thing works

- [ ] Create a [cacti testing environment](https://github.com/rapid7/metasploit-framework/pull/15122/files#diff-82d7f56d21b1de07989f59e63089807c87cc1bf37b904175a70d62adbf195dcbR18-R24)
- [ ] `use exploit/unix/http/cacti_filter_sqli_rce`
- [ ] ensure module executes successfully

- [ ] Create a [gitlab testing environment](https://github.com/rapid7/metasploit-framework/pull/14422/files#diff-6d4d4dde676983baa2fc614c666b022663112cc36716bae64c28777fa9e41eeaR24-R29)
- [ ] `use exploit/multi/http/gitlab_file_read_rce`
- [ ] ensure module executes successfully

2021-07-30 14:23 UTC, dwelch-r7 requested changes

2021-07-30 14:23 UTC, dwelch-r7 commented on lib/msf/core/exploit/remote/http/http_cookie_jar.rb
> +              elog("Cookie #{cookie.to_s} could not be added to jar. Error was thrown with following message:\n#{e.message}")
I think `elog` can have the error passed in as an argument like this
```suggestion
              elog("Cookie #{cookie.to_s} could not be added to jar. Error was thrown with following message:\n#{e.message}", error: e)
```

2021-07-30 14:23 UTC, dwelch-r7 commented on lib/msf/core/exploit/remote/http/http_cookie_jar.rb
> +              end
this seems a little off to me, someone passing in attrs that isn't a hash and it just gets ignored, can it be anything other than a hash? if not maybe a guard clause or at least a warning

2021-07-30 14:23 UTC, dwelch-r7 commented on lib/msf/core/exploit/remote/http_client.rb
> +        c.origin = "http#{ssl ? 's' : ''}://#{vhost}:#{rport}"
can the vhost ever be nil? I don't think it can I think it defaults to the ip if it's not set but just wanted to call it out to be sure

2021-07-30 14:55 UTC, adfoster-r7 commented on lib/msf/core/exploit/remote/http_client.rb
> +      cookies = cookie_jar.parse(res.headers['Set-Cookie'])
Would it be easier for parse to take the origin/path like it did before?

https://github.com/rapid7/metasploit-framework/pull/15225/files#diff-181d5970bce86f6a48bb550ed0dbade6ea0d946645995e0ff7884e85fe3fe91aR402

2021-07-30 15:03 UTC, agalway-r7 commented on lib/msf/core/exploit/remote/http_client.rb
> +        c.origin = "http#{ssl ? 's' : ''}://#{vhost}:#{rport}"
Aye VHOST can be nil, in which case it gets set to RHOST 👍 
https://github.com/rapid7/metasploit-framework/blob/569660b8904a7a34c75f2f9ea044cda75c64640f/lib/msf/core/exploit/remote/http_client.rb#L653

2021-07-30 15:05 UTC, agalway-r7 commented on lib/msf/core/exploit/remote/http_client.rb
> +      cookies = cookie_jar.parse(res.headers['Set-Cookie'])
IMO we'd want the cookie & cookie_jar classes to stay as generic as possible. If we set parse to take an origin that means we're forcing users to generate an origin when they don't know how/don't want to. 

Parse returns a cookie class with an origin setter, so they can set origin using that if they want to.

2021-07-30 15:08 UTC, adfoster-r7 commented on lib/msf/core/exploit/remote/http/http_cookie_jar.rb
> +            end
```suggestion
            begin
              @cookie_jar.add(cookie)
            rescue ArgumentError => e
              elog("Cookie #{cookie.to_s} could not be added to jar. Error was thrown with following message:\n#{e.message}", error: e)
            end
            self
```

2021-07-30 15:10 UTC, adfoster-r7 commented on lib/msf/core/exploit/remote/http_client.rb
> +      cookies = cookie_jar.parse(res.headers['Set-Cookie'])
From the original PR, it looks like the existing API already takes `origin` as a parameter, which  seems pretty single responsibility to me and something we could easily align on
```ruby
::HTTP::Cookie.parse(set_cookie_header, origin_url, options)
```

2021-07-30 15:18 UTC, adfoster-r7 commented on lib/msf/core/exploit/remote/http/http_cookie_jar.rb
> +              end
What else can `attrs` be? 👀 

```suggestion
              cookies << HttpCookie.new(name, value, **attrs)
```

2021-07-30 15:21 UTC, agalway-r7 commented on lib/msf/core/exploit/remote/http_client.rb
> +      cookies = cookie_jar.parse(res.headers['Set-Cookie'])
Yeah but the original way of doing it wasn't great either IMO. Thing is we can make a cookie without an origin via it's initializer and/or setters, so why should we make people pass an origin to parse the same cookie? Especially since the origin isn't actually essential, only a domain and path value _need_ to be set

2021-07-30 15:52 UTC, agalway-r7 commented on lib/msf/core/exploit/remote/http/http_cookie_jar.rb
> +              end
`scan_set_cookie` can return`nil` in place of a hash as `attrs`, which will cause a `wrong number of arguments (given 3, expected 1..2) (ArgumentError)` error.  

I could replace the `if attrs.is_a?(Hash)` with `if attrs`, but some non hash value could be passed in the future if `scan_set_cookie` is changed or if another method entirely is used, which would also cause the above error, so IMO `is_a?(Hash)` is clearier since it indicates what it is we're looking for to ensure no errors.

2021-07-30 15:52 UTC, agalway-r7 commented on lib/msf/core/exploit/remote/http/http_cookie_jar.rb
> +              end
See below

2021-07-30 15:58 UTC, adfoster-r7 commented on lib/msf/core/exploit/remote/http/http_cookie_jar.rb
> +              end
How about
```
attrs ||= {}
cookies << HttpCookie.new(name, value, **attrs)
```

2021-07-30 17:12 UTC, agalway-r7 commented on lib/msf/core/exploit/remote/http/http_cookie_jar.rb
> +              end
That still has the issue of attrs being a value that isn't nil but also isn't a hash

2021-07-30 21:31 UTC, adfoster-r7 commented on lib/msf/core/exploit/remote/http/http_cookie_jar.rb
> +              end
Just checking the underlying code, I don't think a non-hash is yielded? 👀 

https://github.com/sparklemotion/http-cookie/blob/2578ebb536c4617fd3b343fb2468d1a3c5b705b8/lib/http/cookie/scanner.rb#L171

2021-08-02 09:50 UTC, adfoster-r7 commented on lib/msf/core/exploit/remote/http/http_cookie_jar.rb
> +              end
```suggestion
              raise ArgumentError, 'Expected attrs to be a Hash' unless attrs.is_a?(Hash)
              cookies << HttpCookie.new(name, value, **attrs)
```

2021-08-02 09:50 UTC, adfoster-r7 commented on spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb
> +    describe 'String' do
I think these should be contexts?  https://www.betterspecs.org/

2021-08-02 09:50 UTC, adfoster-r7 commented on spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb
> +      it 'which is a kind of String representing a URI will be passed to origin successfully, and populate the domain & path fields correctly' do
```suggestion
      it 'which is a kind of String representing a URI will be passed to origin successfully, and populate the domain and path fields correctly' do
```

2021-08-02 09:51 UTC, adfoster-r7 commented on spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb
> +      it 'representing a URI will be passed to origin successfully, and populate the domain & path fields correctly' do
```suggestion
      it 'representing a URI will be passed to origin successfully, and populate the domain and path fields correctly' do
```

2021-08-02 09:55 UTC, adfoster-r7 commented on spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb
> +        expect(cookie.origin.class).to eql(protocol.end_with?('s') ? URI::HTTPS : URI::HTTP)
Let's add two separate tests for this, instead of introducing non-deterministic tests :+1:

2021-08-02 10:07 UTC, adfoster-r7 commented on lib/msf/core/exploit/remote/http/http_cookie_jar.rb
> +              end
We'll want tests for this scenario too then

```ruby
  describe '#parse' do
    it 'parses comma separated cookies' do
      input = "cross-site-cookie=bar; SameSite=Strict;, Cacti=qlf907tneuneajqbr00fge0ull; path=/cacti/; HttpOnly"
      expected = [
        # ...
      ]
      expect(subject.parse(input)).to eq(expected)
    end

    it 'validates that that the third party scan_set_cookie implementation always returns a hash' do
      allow_any_instance_of(::HTTP::Cookie::Scanner).to receive(:scan_set_cookie).and_yield "foo", "bar", nil
      input = "cross-site-cookie=bar; SameSite=Strict;, Cacti=qlf907tneuneajqbr00fge0ull; path=/cacti/; HttpOnly"
      expect { subject.parse(input) }.to raise_error /Expected attrs to be a Hash/
    end
  end
```

2021-08-02 10:30 UTC, adfoster-r7 commented on lib/msf/core/exploit/remote/http_client.rb
> +      cookies = cookie_jar.parse(res.headers['Set-Cookie'])
I think the current approach is a leak of concerns, that would be better to consolidate inside the cookiejar itself - which is also the pattern of python's cookiejar implementation

2021-08-02 10:35 UTC, adfoster-r7 commented on spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb
> +
```suggestion
```

2021-08-04 09:22 UTC, dwelch-r7 approved these changes

2021-08-04 09:22 UTC, dwelch-r7 commented on lib/msf/core/exploit/remote/http/http_cookie.rb
> +              if k == 'max-age'.to_sym
do you need to call `to_sym` on this? and if so why not just check if it's equal to `:max-age` instead?

2021-08-04 09:23 UTC, adfoster-r7 commented on lib/msf/core/exploit/remote/http/http_cookie.rb
> +              if k == 'max-age'.to_sym
That's a syntax error, you'd want `:'max-age'`

2021-08-04 09:31 UTC, dwelch-r7 commented on lib/msf/core/exploit/remote/http/http_cookie.rb
> +              if k == 'max-age'.to_sym
ohhh well that explains why it was done the way that it is :sweat_smile:

2021-08-04 10:50 UTC, merged

2021-08-04 10:54 UTC, adfoster-r7 commented
## Release Notes

Fixes a regression issue for `gitlab_file_read_rce` and `cacti_filter_sqli_rce`

2021-08-04 23:55 UTC, myusrn commented
As noted in [15456](https://github.com/rapid7/metasploit-framework/issues/15456) comment I updated to latest 6.0.56-dev [ using `sudo apt upgrade metasploit-framework` ] and this issue still repros?  Will the fix for this regression not show up until a later package release?  Is there a way to install the fix straight from github repo?

2021-08-05 00:33 UTC, adfoster-r7 commented
Cross-referencing the response: https://github.com/rapid7/metasploit-framework/issues/15456#issuecomment-893071171