Add CVE-2002-0422 Coverage to iis_internal_ip Auxiliary Module
rapid7/metasploit-framework pull request #15782
Opened 2021-10-19 16:16 UTC by k0pak4

This PR updates the iis_internal_ip module to include coverage for the PROPFIND internal IP address disclosure as described by CVE-2002-0422. It also updates the documentation to include the CVE and other references as well as rubocopping the module since I was already making edits.

## Verification

- [ ] Start `msfconsole`
- [ ] `use auxiliary/scanner/http/iis_internal_ip`
- [ ] `set RHOSTS YYY.YY.YYY.YYY`
- [ ] `set RPORT 443`
- [ ] `set SSL true`
- [ ] Verify the internal ip address is discovered

Software Version
- Tested on IIS 7.0

2021-10-21 14:36 UTC, jmartin-tech requested changes
Thanks for the update on this module.  The changes to metadata in the module initialization look to need some rollback and adjustment.

2021-10-22 21:41 UTC, jmartin-tech approved these changes

2021-11-02 13:31 UTC, merged

2021-11-02 13:31 UTC, adfoster-r7 commented
## Release Notes

Updates the iis_internal_ip module to include coverage for the PROPFIND internal IP address disclosure as described by CVE-2002-0422

2021-11-02 13:32 UTC, adfoster-r7 commented
We weren't able to verify this against a local environment, but the changes seem good to land :+1: