Update on phpmailer_arg_injection.rb
rapid7/metasploit-framework pull request #15810
Opened 2021-10-29 21:28 UTC by erikbomb

Added Advanced options to change the name of the fields for the name, email, and message objects.  Set the default to the previous hard coded value.

No changes to the functionality of the code just adding the ability for users to modify values

## Verification

- [ ] Start `msfconsole`
- [ ] `use exploits/multi/http/phpmailer_arg_injection`
- [ ] `set NAME_FIELD different_name`

2021-10-29 21:29 UTC, erikbomb commented
Functionality works.

2021-10-30 00:50 UTC, erikbomb commented on modules/exploits/multi/http/phpmailer_arg_injection.rb
> +        OptString.new('MESSAGE_FIELD', [true, 'Name of the element for the Message field', 'message'])
Added Advanced Options

2021-10-30 00:51 UTC, erikbomb commented on modules/exploits/multi/http/phpmailer_arg_injection.rb
> +    data.add_part("#{rand_text_alphanumeric(2 + rand(20))}", nil, nil, "form-data; name='#{message_field}'")
changed form-data variable names  from static to advanced options allowing for more flexability

2021-11-04 10:46 UTC, smcintyre-r7 requested changes

2021-11-04 10:46 UTC, smcintyre-r7 commented on modules/exploits/multi/http/phpmailer_arg_injection.rb
> +        OptString.new('MESSAGE_FIELD', [true, 'Name of the element for the Message field', 'message'])
So I know that `WAIT_TIMEOUT` is screaming snake case, but typically advanced options are camel case (e.g. `WaitTimeout`, `NameField`, etc.). Also would you mind adding these options to the [module docs](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/exploit/multi/http/phpmailer_arg_injection.md)?

There should be an options section like this after the Verification Steps and before the Scenarios section:

```
## Options

### NameField
*This is an advanced option.*

Name of the element for the Name field.

...

## Scenarios
```

2021-11-04 10:46 UTC, smcintyre-r7 commented on modules/exploits/multi/http/phpmailer_arg_injection.rb
> +    data.add_part("#{rand_text_alphanumeric(2 + rand(20))}", nil, nil, "form-data; name='#{message_field}'")
This makes it look like the values should either be escaped or validated to ensure they only consist of acceptable characters. One way to limit it to an acceptable set of characters could be to use the `regex:` keyword argument in the option definition. There's an example of that usage in [this exploit](https://github.com/rapid7/metasploit-framework/blob/1a2285e1b3a3952280e863aa6ecd666d87fb3086/modules/exploits/linux/local/sudo_baron_samedit.rb#L89).

2022-02-04 16:41 UTC, closed without merging