Add Meterpreter compatibility requirements to lib
rapid7/metasploit-framework pull request #15842
Opened 2021-11-08 12:41 UTC by adfoster-r7

Updating the Meterpreter compatibility requirements for mixins within the lib folder

2021-11-08 12:42 UTC, adfoster-r7 commented on lib/msf/core/post/common.rb
> -              stdapi_sys_process_close
Keeping track of `process.close` statically was hard, so the tooling assumes that a process execution generally means there is close support in the meterpreter

2021-11-08 12:43 UTC, adfoster-r7 commented on lib/msf/core/post/windows/extapi.rb
> -  end
modules now uses the more granular extapi_* metadata, rather than `extapi` requiring all commands to be implemented

2021-11-08 12:44 UTC, adfoster-r7 commented on lib/msf/core/post/windows/packrat.rb
> -
Separate PR to rubocop this file https://github.com/rapid7/metasploit-framework/pull/15841

2021-11-16 16:27 UTC, adfoster-r7 commented on lib/msf/core/post/file.rb
> +              stdapi_fs_chmod
This looks like it might be impacting some post modules:

![image](https://user-images.githubusercontent.com/60357436/142025187-05b3718a-1acd-4a6b-a84f-880ec9dd8610.png)

@sjanusz-r7 is just taking a quick look 👀

2021-11-16 23:44 UTC, gwillcox-r7 requested changes

2021-11-16 23:44 UTC, gwillcox-r7 commented on lib/msf/core/post/file.rb
> +              stdapi_fs_chmod
I will just chime in here and say this is required for a few areas of the code here so I would be against removing it and instead figuring out why some of our Meterpreter versions don't have this functionality.

2021-11-16 23:44 UTC, gwillcox-r7 commented on lib/msf/core/post/file.rb
> +              stdapi_fs_chmod
One side note but this code seems to use `protected` twice and its probably only needed at line 632 unless `get_drives` was intended to be public.

2021-11-16 23:44 UTC, gwillcox-r7 commented on lib/msf/core/post/file.rb
> +              core_channel_write
No `core_channel_close`?

2021-11-17 10:23 UTC, adfoster-r7 commented on lib/msf/core/post/file.rb
> +              stdapi_fs_chmod
> figuring out why some of our Meterpreter versions don't have this functionality.

Windows doesn't have it, as it doesn't seem necessary. The `chmod` functionality in our exploits is mostly used on unix systems to mark a binary as being executable for exploitation purposes, it's not really needed on a windows system.

> One side note but this code seems to use protected twice

Good spot, seems like something we can throw a different PR up for :+1:

2021-11-17 10:41 UTC, adfoster-r7 commented on lib/msf/core/post/file.rb
> +              stdapi_fs_chmod
Potential solutions:
- Add this to an ignore list for windows's session validation handling [here](https://github.com/rapid7/metasploit-framework/blob/c9af078de8eed504a37ec70c03a4efbada111f9a/lib/msf/core/post_mixin.rb#L260)
- Add the support for a chmod equivalent to windows Meterpreter, although this logically doesn't make a lot of sense
- Split the `chmod` functionality out of this file into two mixins, although this will impact a lot of modules:
```
  include Msf::Post::File
  include Msf::Post::Linux::File # Now has chmod and upload_and_chmodx
```
- Potentially move the chmod functionality into `Msf::Post::Linux::Priv` - will get numbers to see if this makes sense

2021-11-17 15:06 UTC, gwillcox-r7 commented on lib/msf/core/post/file.rb
> +              stdapi_fs_chmod
> * Split the `chmod` functionality out of this file into two mixins, although this will impact a lot of modules:

I think to me this makes the most sense if and only if we have both a clear difference between what should be general file functionality and what should be Linux/Windows/MacOS specific, and also enough functionality that is unique to a specific OS to warrant this.

Logically I think this makes the most sense as it provides a more uniform structure vs the former two solutions.

As for moving it into `Msf::Post::Linux::Priv` I would also find this appropriate if the mixin approach doesn't work; technically this is a bit more on the privilege side than the file side per say but one could argue it either way.

2021-12-12 23:41 UTC, gwillcox-r7 commented
Pinging @adfoster-r7, any updates on fixing these issues? Only asking as its been nearly a month since the last review. If no time that's fine just want to make sure we have a status update on this so people looking at this PR know what is going on.

2021-12-13 13:52 UTC, adfoster-r7 commented on lib/msf/core/post/windows/priv.rb
> +              stdapi_sys_config_sysinfo
> stdapi_sys_config_getenv for the getenv command?

That will be covered by the mixin that provides the `getenv` function:
https://github.com/rapid7/metasploit-framework/blob/950e976f7b288bc681e5c30cbb465dff1e0a5505/lib/msf/core/post/common.rb#L5-L12

> stdapi_sys_process_get_processes for the session.sys.process.processes.each() call in steal_token?

Good spot, will add :+1:

> However I am unsure if this means that we need to require stdapi_registry_query_value_direct as a result.

This is covered in the base included Registry mixin that provides the `registry_getvaldata ` functionality https://github.com/rapid7/metasploit-framework/blob/c9af078de8eed504a37ec70c03a4efbada111f9a/lib/msf/core/post/windows/registry.rb#L63

2021-12-13 13:52 UTC, adfoster-r7 commented on lib/msf/core/post/windows/process.rb
> +              stdapi_sys_process_thread_create
Will add :+1:

2021-12-13 13:52 UTC, adfoster-r7 commented on lib/msf/core/post/windows/ldap.rb
> +                extapi_adsi_domain_query
I think this is fine for now, something that could be iterated on :+1:

2021-12-13 13:52 UTC, adfoster-r7 commented on lib/msf/core/post/windows/mssql.rb
> +                    stdapi_sys_process_get_processes
> Given that each_service here calls session.extapi.service.enumerate.each(&block) if extapi is loaded as per

That will be covered by the mixin that provides the each_service function:
https://github.com/rapid7/metasploit-framework/blob/c9af078de8eed504a37ec70c03a4efbada111f9a/lib/msf/core/post/windows/services.rb#L51-L52

> core_channel_read and core_channel_close potentially required here due to the way run_cmd operates.

Will lump this in with the implicit nature of stdapi_sys_process_execute being associated with channel open/close/read/eof, can iterate on this in a future PR though :+1:

2021-12-13 17:55 UTC, gwillcox-r7 commented on lib/msf/core/post/file.rb
> +              stdapi_fs_chmod
Resolved in 4c02405ab520ca3232aeb359a14fd82ae29e23db

2021-12-13 17:57 UTC, gwillcox-r7 commented on lib/msf/core/post/windows/process.rb
> +              stdapi_sys_process_thread_create
Fixed in 48f40077ead2ddd0ccb9dfd1cc6eac6caf62cb0e

2021-12-13 18:01 UTC, gwillcox-r7 commented on lib/msf/core/post/windows/priv.rb
> +              stdapi_sys_config_sysinfo
Proposals look good and verified the one necessary change was made in 48f40077ead2ddd0ccb9dfd1cc6eac6caf62cb0e. Marking resolved.

2021-12-13 18:22 UTC, gwillcox-r7 commented on lib/msf/core/post/windows/packrat.rb
> +                    core_channel_read
Huh didn't know that, thanks for pointing that out, will mark this as resolved.

2021-12-13 18:36 UTC, adfoster-r7 commented on lib/msf/core/post/windows/powershell.rb
> +                    stdapi_sys_process_kill
Good spot, will need to add this in a separate PR :+1:

2021-12-13 18:43 UTC, adfoster-r7 commented
Cross-referencing https://github.com/rapid7/metasploit-framework/issues/15949 too

This PR should fix the issue which stopped modules running as part of the local exploit suggester, as `stdapi_sys_process_*` - inadvertently required the new `stdapi_sys_process_set_term_size` command which isn't supported by all meterpreters

2021-12-13 18:54 UTC, gwillcox-r7 commented
To clarify before landing there are a few features here that we still need to iterate on and improve. Namely they are:

Comments at https://github.com/rapid7/metasploit-framework/pull/15842#discussion_r767775868 and previous comments r.e `lib/msf/core/post/windows/mssql.rb` missing some potential requirements to further lock things down.

Comments at https://github.com/rapid7/metasploit-framework/pull/15842#discussion_r750653353 and https://github.com/rapid7/metasploit-framework/pull/15842#discussion_r750647539 r.e `lib/msf/core/post/windows/powershell.rb` not requiring certain features it likely needs to further lock things down.

Comment at https://github.com/rapid7/metasploit-framework/pull/15842#discussion_r750653780 r.e creating a centralized list of requirements and what each one is actually used for in some form of documentation. I'm happy to investigate this further in 2022 but will likely need some assistance as some feature have some edge cases that @adfoster-r7 or similar might have better insights into.

For now though this PR is fine and @adfoster-r7 and I both agree this is a good point to pause and land existing work, with the understanding that the automation needs to be improved and run again across the codebase, and that further iteration and improvements are needed on the above issue along with the documentation note as mentioned above.

2021-12-13 18:54 UTC, gwillcox-r7 approved these changes

2021-12-13 18:58 UTC, merged