wordpress Secure Copy Content Protection and Content Locking Unauthenticated sqli (CVE'-2021-24931)
rapid7/metasploit-framework pull request #16182
Opened 2022-02-13 20:08 UTC by h00die

This adds a very simple to install and exploit (unauth) sqli for wordpress plugin Secure Copy Content Protection and Content Locking <2.8.2.

- [ ] install module (linked in docs, active it, no further action required)
- [ ] start msf
- [ ] use module
- [ ] set rhosts
- [ ] check
- [ ] run
- [ ] get hashes
- [ ] check docs

2022-02-14 09:02 UTC, its0x08 approved these changes

2022-02-14 21:52 UTC, gwillcox-r7 requested changes

2022-02-14 21:52 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.md
> +The larger this list, the more time it will take.  Defaults to `3`.
Considering this is user specific, it might be better to name this `USER_COUNT` or something more explicit. Just a suggestion though.

2022-02-14 21:52 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.rb
> +          'sccp_id[]' parameter.
This description tells me nothing about what this module is trying to do, so a typical user will have no idea what this module is actually trying to achieve. Should update this to state what the module will do so that a user who types `info` will have an idea what is going to be done when they run this module.

2022-02-14 21:52 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.rb
> +          'Hacker5preme (Ron Jost)', # edb
He also wrote a blog post explaining his process of finding this and other bugs in https://kazet.cc/2022/02/03/fuzzing-wordpress-plugins.html. Blog also notes other bugs that may be good for future PRs

2022-02-14 21:52 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.rb
> +      OptInt.new('COUNT', [false, 'Number of users to enumerate', 3])
```suggestion
      OptInt.new('COUNT', [true, 'Number of users to enumerate', 3])
```
required option, not optional

2022-02-14 21:52 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.rb
> +    id = Rex::Text.rand_text_numeric(1)
Does this have to be a single digit number? Are we 100% sure this can't be a large number? Just checking.

2022-02-14 21:52 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.rb
> +          'sccp_id[]' => "#{id}) AND (SELECT #{Rex::Text.rand_text_numeric(4)} FROM (SELECT(#{payload}))#{Rex::Text.rand_text_alpha(4)})-- #{Rex::Text.rand_text_alpha(4)}",
Seems like some of these could be longer than 4 character long. We can do ranges with something like `Rex::Text.rand_text_alpha(4...8)` to make things even more random.

2022-02-14 21:52 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.rb
> +      fail_with Failure::Unreachable, 'Connection failed' unless res
```suggestion
      fail_with(Failure::Unreachable, 'Connection failed') unless res
```

2022-02-15 00:25 UTC, h00die commented on data/wordlists/wp-exploitable-plugins.txt
> +custom-registration-form-builder-with-submission-manager
yes and no.
Its actually from #16130 but was never included since I forgot to run the script to include it.  So just adding it in now.

2022-02-24 19:58 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.rb
> +      fail_with Failure::Unreachable, 'Connection failed' unless res
Resolved in https://github.com/rapid7/metasploit-framework/pull/16182/commits/8d080135bbbe276ceb09185ae8d6a1ac0e8dcaf0

2022-02-24 19:58 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.rb
> +    print_good('Vulnerable version of Secure Copy Content Protection and Content Locking detected')
Resolved in https://github.com/rapid7/metasploit-framework/pull/16182/commits/8d080135bbbe276ceb09185ae8d6a1ac0e8dcaf0 and documentation updated accordingly.

2022-02-24 19:58 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.rb
> +      OptInt.new('COUNT', [false, 'Number of users to enumerate', 3])
Fixed in https://github.com/rapid7/metasploit-framework/pull/16182/commits/8d080135bbbe276ceb09185ae8d6a1ac0e8dcaf0

2022-02-24 19:59 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.md
> +The larger this list, the more time it will take.  Defaults to `3`.
Fixed in https://github.com/rapid7/metasploit-framework/pull/16182/commits/8d080135bbbe276ceb09185ae8d6a1ac0e8dcaf0 and references updated across module and documentation.

2022-02-24 19:59 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.md
> +This action lists `COUNT` users and password hashes.
Fixed in https://github.com/rapid7/metasploit-framework/pull/16182/commits/8d080135bbbe276ceb09185ae8d6a1ac0e8dcaf0

2022-02-24 19:59 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.rb
> +          'sccp_id[]' parameter.
Fixed in https://github.com/rapid7/metasploit-framework/pull/16182/commits/8d080135bbbe276ceb09185ae8d6a1ac0e8dcaf0 with a description that we are dumping from the `wp_users` table.

2022-02-24 20:00 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.md
> +6. You should get the users and hashes returned.
Fixed in https://github.com/rapid7/metasploit-framework/pull/16182/commits/8d080135bbbe276ceb09185ae8d6a1ac0e8dcaf0 by adding more detail.

2022-02-24 20:00 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.md
> +This module slightly replicates sqlmap running as:
Suggested fixed implemented with https://github.com/rapid7/metasploit-framework/pull/16182/commits/8d080135bbbe276ceb09185ae8d6a1ac0e8dcaf0

2022-02-24 20:00 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.md
> +[here](https://downloads.wordpress.org/plugin/secure-copy-content-protection.2.8.1.zip)
Suggested fix implemented in https://github.com/rapid7/metasploit-framework/pull/16182/commits/8d080135bbbe276ceb09185ae8d6a1ac0e8dcaf0

2022-02-24 20:01 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.md
> +`sccp_id[]` parameter.
Fixed in https://github.com/rapid7/metasploit-framework/pull/16182/commits/8d080135bbbe276ceb09185ae8d6a1ac0e8dcaf0

2022-02-24 20:01 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.rb
> +          'Hacker5preme (Ron Jost)', # edb
Fixed in https://github.com/rapid7/metasploit-framework/pull/16182/commits/8d080135bbbe276ceb09185ae8d6a1ac0e8dcaf0 by adding proper attribution and adding in a link to the blog post where this was originally found and reported.

2022-02-24 20:07 UTC, gwillcox-r7 commented
Last two changes are going to require me to set up the target and do some live testing, so going to ahead and do that so long, just wanted to push up other changes so long.

2022-02-24 21:43 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.rb
> +          'sccp_id[]' => "#{id}) AND (SELECT #{Rex::Text.rand_text_numeric(4)} FROM (SELECT(#{payload}))#{Rex::Text.rand_text_alpha(4)})-- #{Rex::Text.rand_text_alpha(4)}",
Fixed in https://github.com/rapid7/metasploit-framework/pull/16182/commits/9b53ed5f5c6cae16b262d6effa8aa3a376b1b640

2022-02-24 21:44 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.rb
> +    id = Rex::Text.rand_text_numeric(1)
Fixed in https://github.com/rapid7/metasploit-framework/pull/16182/commits/9b53ed5f5c6cae16b262d6effa8aa3a376b1b640

2022-02-24 21:44 UTC, gwillcox-r7 commented
```
msf6 auxiliary(scanner/http/wp_secure_copy_content_protection_sqli) > show options

Module options (auxiliary/scanner/http/wp_secure_copy_content_protection_sqli):

   Name        Current Setting  Required  Description
   ----        ---------------  --------  -----------
   Proxies                      no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS      127.0.0.1        yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metas
                                          ploit
   RPORT       8000             yes       The target port (TCP)
   SSL         false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI   /                yes       The base path to the wordpress application
   THREADS     1                yes       The number of concurrent threads (max one per host)
   USER_COUNT  3                yes       Number of user credentials to enumerate
   VHOST                        no        HTTP server virtual host


Auxiliary action:

   Name        Description
   ----        -----------
   List Users  Queries username, password hash for USER_COUNT users


msf6 auxiliary(scanner/http/wp_secure_copy_content_protection_sqli) > run

[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable.
[*] Enumerating Usernames and Password Hashes
[!] Each user will take about 5-10 minutes to enumerate. Be patient.
[+] Dumped table contents:
wp_users
========

 user_login  user_pass
 ----------  ---------
 normal      $P$Bu9/XNK93oyUTKO.zJ9yGZfYAcbZg9.
 testAdmin   $P$BYWtZOfh8yqLCKA877hwBysqGdRtk/.

[*] Scanned 1 of 1 hosts (100% complete)
```

Working like a charm :) Will land after tests pass.

2022-02-24 21:44 UTC, gwillcox-r7 approved these changes

2022-02-24 21:56 UTC, merged

2022-02-24 21:59 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added to exploit CVE-2021-24931, an unauthenticated SQLi vulnerability in the `sccp_id` parameter of the `ays_sccp_results_export_file` AJAX action in Secure Copy Content Protection and Content Locking WordPress plugin versions before 2.8.2. Successful exploitation allows attackers to dump usernames and password hashes from the `wp_users` table which can then be cracked offline to gain valid login credentials for the affected WordPress installation.