Axis Camera App RCE (No CVE)
rapid7/metasploit-framework pull request #16190
Opened 2022-02-15 02:23 UTC by jbaines-r7

## Background

This is an issue I disclosed to Axis back in 2017 and [published](https://www.tenable.com/blog/tenable-research-advisory-axis-camera-app-malicious-package-distribution-weakness) in 2018. No CVE was assigned, and the vendor indicated a plan to address "in the next generation." I revisited this on the latest firmware (Dec. 2021) for a device I have on hand, and the issue persists.

Given that dome cameras are ubiquitous and Axis is a popular vendor (Shodan indexes some 30k likely vulnerable internet facing [doodads](https://www.shodan.io/search?query=html%3A%22Axis+Communications+AB%22)). I figured it would be a fun module to write (it actually was somewhat miserably but :shrug:).

## Description

This module exploits the "Apps" feature in Axis IP cameras. The feature allows third party developers to upload and execute  'eap' applications on the device. The system does not validate the application comes from a trusted source, so a malicious attacker can upload and execute arbitrary code. The issue has no CVE, although the technique was made public in 2018.

This module uploads and executes stageless meterpreter as `root` via the application upload feature. The module will also  uninstall the application upon completion. Uploading the application requires valid credentials. The default administrator credentials used to be `root:root` but newer firmware versions force users to provide a new password for the `root` user.

The module was tested on an Axis M3044-V using the latest firmware (9.80.3.8: December 2021). All devices that support the "App" feature are presumed to be vulnerable at this time.

## Development Quirks

Execution is first established via a bash "post installation" script. The script is executed as a systemd oneshot. That's not great for an exploit as all children will be reaped after the parent exits... executing from post installation also holds the HTTP connection open. All around not good.

My solution was to create a second service that will execute stageless Meterpreter. That seemed to work nicely, but obviously is an extra moving part.

I also elected not to implement a CMD_ARCH payload. The only one that technically works is `reverse_openssl` and it has to be fairly heavily modified. I fiddled around with the idea of adding a new `single` that uses openssl / mkfifo but ultimately decided I'd had enough of the camera, and that having meterpreter on system was better anyway.

The device actually supports both HTTP and HTTPs. Shodan has way more HTTP endpoints though, so I left HTTP as the default setting.

Finally, I want reiterate that the armle starger is unstable. Including on this platform. See #16107.

## Verification

Acquire an affected device:

- [ ] Start `msfconsole`
- [ ] `use exploit/linux/http/axis_app_install`
- [ ] `set RHOST <ip>`
- [ ]  `set PASSWORD <password>`
- [ ] `check`
- [ ] Verify the remote target is flagged as vulnerable
- [ ]  `set LHOST <ip>`
- [ ]  `exploit`
- [ ]  You should get a Meterpreter session.

## PCAP || GTFO

[axis_camera_meterpreter.zip](https://github.com/rapid7/metasploit-framework/files/8065204/axis_camera_meterpreter.zip)

## Video || GTFO

https://www.youtube.com/watch?v=q7OtSkwpeqY

2022-02-15 18:54 UTC, gwillcox-r7 commented
Rerunning checks but seems it was just some temp Docker issue due to Alpine servers acting up again so not too concerned.

2022-02-17 15:39 UTC, bwatters-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    fail_with(Failure::Disconnected, 'Connection failed') unless res
'fail_with' might not be the best thing here- it is possible we could have a session, fail to clean up, and generate a failure for the module on not cleaning up.  It might be better to use something like `print_bad` and uninstall instructions?
You could also look into moving this to a cleanup method within the module...

2022-02-24 14:54 UTC, jbaines-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    fail_with(Failure::Disconnected, 'Connection failed') unless res
Yeah, you're right. `fail_with` is bad here. I'll switch it over to `print_bad`.

I *think* `cleanup` is only called on success? I could very well be wrong.  I used `ensure` to clean up as it's a similar situation to the Nagios issue discussed in module hacking... three weeks ago? Part of that conversation manifested [here](https://github.com/rapid7/metasploit-framework/pull/16150/files#r804296811). Anyway, the idea being that the app could install and the meterpreter session might not appear, but we still want to uninstall the app regardless 🤷  If that belongs in cleanup, I'm happy to move it... but the documentation isn't [super clear](https://www.rubydoc.info/github/rapid7/metasploit-framework/Msf%2FExploit:cleanup) about when it runs :)

2022-02-24 15:51 UTC, jbaines-r7 commented
Updated to address @bwatters-r7's comment regarding `fail_with`. I also included information about manually uninstalling, although (hopefully) it never comes to that. Updated pcap attached.

[axis_camera_meterpreter_updated.zip](https://github.com/rapid7/metasploit-framework/files/8133855/axis_camera_meterpreter_updated.zip)

2022-02-25 00:23 UTC, gwillcox-r7 commented
Quick comment that I think is relevant but the camera you tested this on is now discontinued. https://www.axis.com/products/axis-m3064-v/support lists the newer supported camera however the firmware version is the same as noted on February 24th 2022 and can be found at https://www.axis.com/ftp/pub/axis/software/MPQT/M3064-V/9_80_3_8/M3064-V_9_80_3_8_release_notes.txt.

2022-02-25 00:31 UTC, gwillcox-r7 commented
On a related note to above, I think we need to narrow down affected versions more. I tried searching on the site for Axis IP camera's but they don't seem to call them that so finding affected versions is.....well its tricky to say the least 😅

2022-02-25 01:57 UTC, gwillcox-r7 requested changes
Overall looks pretty good though had a few questions r.e randomization and a few places where I found some typos and wording suggestions that might deserve a further look. Note that some comments are minor suggestions based on further analysis, I just left them there to give some food for thought.

Only two major suggestions. One was the `DefaultOptions` section where Spencer told me recently that we shouldn't be setting that unless we have a valid reason so I left some notes there, but I'll leave you to decide if we need that based on your experience. Perhaps play around with taking that out and see if the module still works.

Other one is r.e vulnerable versions. See comments for more but TLDR is I think the current wording makes it hard for people to find vulnerable devices unless they use the `check` method. Happy to talk about this further though.

Let me know if anything is confusing, most of this should be fairly quick fixes though randomization checks may require a bit more time.

2022-02-25 01:57 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/axis_app_install.md
> +All devices that support the "App" feature are presumed to be vulnerable at this time.
Also r.e the `App` feature, this is a good callout, though given other firmware also seems to support these sorts of features that might not be vulnerable, I'd want to just check this isn't inadvertently broadening the scope of affected devices too much.

2022-02-25 01:57 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/axis_app_install.md
> +msf6 exploit(linux/http/axis_app_install) > run
Might want to update this with a `show options` output to show that you are authenticating as `root`. Not a deal breaker but its nice to see the options that are being used for future debugging purposes in case something breaks or we change the code later on and need to refer back to what worked.

2022-02-25 01:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +        'Privileged' => false,
Would we not consider that to be privileged given this executes code as `root`? 
```suggestion
        'Privileged' => true,
```

2022-02-25 01:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +          Although all modules that support this feature are presumed to be vulnerable.
```suggestion
          Although all modules that support the "Apps" feature are presumed to be vulnerable.
```

Suggestion to be more explicit otherwise given you mention the "Apps" feature 2 paragraphs up its possible to think this might be related to some other unnamed feature.

2022-02-25 01:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +              }
Only mentioning this as Spencer did a similar change but do we need to specify a default payload? Speaking to him recently the consensus was that we should not be setting default payloads unless absolutely needed and this doesn't appear to be a case where we need to explicitly limit the default payload, however given your development difficulties I'd just like to double check on this.

2022-02-25 01:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    return CheckCode::Detected unless res
Nice checking for edge cases, appreciate the extra testing on this 👍

2022-02-25 01:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    check_comment = "The target reports itself to be a '#{body_json.dig('Brand', 'Brand')} #{body_json.dig('Brand', 'ProdNbr')}'"
Minor comment but `ProdShortName` field contains this info already combined. Might help reduce some combination efforts.

2022-02-25 01:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    return CheckCode::Safe(check_comment) unless res.body.include?('<reply result="ok">') != 200
Given the comment here we may want to consider doing some more testing if this might be a concern.

2022-02-25 01:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +  # create and execute a new service for the payload. We have to d this because the oneshot
```suggestion
  # create and execute a new service for the payload. We have to do this because the oneshot
```

2022-02-25 01:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +  # child processes will be reaped when the main binary exits. Executing the payload from
Some people might not get the term `will be reaped`. I get maybe that the term `kill` might not want to be used here (for various reasons) but perhaps saying `will all be terminated` would be more appropriate and easier to understand? Just a thought.

2022-02-25 01:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +      "APPMICROVERSION='#{Rex::Text.rand_text_numeric(1)}'\n" \
Know this is odd to ask but any possibility one can do ranges of say 1 to 3 numbers for something like the micro version? Or are these fields all strictly 1 byte long?

2022-02-25 01:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    script_name = "#{Rex::Text.rand_text_alpha_lower(2..4)}.sh"
Only comment is that 2-4 characters seems rather small range for a script name. I don't think this would be limited to that size but just want to double check as it stood out as a bit odd to me.

2022-02-25 01:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    appname = Rex::Text.rand_text_alpha_lower(3)
I think we can make this a range at the very least (1..3). Also not sure if limiting this to 3 characters when this could be longer?

2022-02-25 01:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +  end
```suggestion
  print_good("The application #{appname} was successfully removed from the target!")
  end
```
Might be good to alert the user when things do go right 😄

2022-02-25 02:02 UTC, jbaines-r7 commented on documentation/modules/exploit/linux/http/axis_app_install.md
> +All devices that support the "App" feature are presumed to be vulnerable at this time.
I'm not sure what you are saying, to be honest. What are you looking for in release notes and what about the firmware would we want to double?

2022-02-25 02:10 UTC, jbaines-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +              }
For this module, without inserting a default payload, the stageless version of meterpreter won't be used. Stageless is desirable here since you can just upload it to the device (plus armle stager is broken).

So, this is intentional and I don't think it make sense to ever exclude a default payload in the first place 🤷

2022-02-25 02:17 UTC, jbaines-r7 commented on documentation/modules/exploit/linux/http/axis_app_install.md
> +This module exploits the "Apps" feature in Axis IP cameras. The feature allows third party
The number of affected devices is far too long to list here. I see what you are saying though. The specific feature that allows exploitation is the Axis Camera Application Platform  - which is linked in the module (https://www.axis.com/support/developer-support/axis-camera-application-platform - this is 503ing atm, looks like their main website says they are suffering a cyber attack?).

Regardless, to my knowledge, *all their cameras* support this platform. And since this "feature" was never patched, it seems that all their devices should be affected. 🤷 I'm open to wording how you that should be described.

2022-02-25 02:21 UTC, jbaines-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    return CheckCode::Safe(check_comment) unless res.body.include?('<reply result="ok">') != 200
The tested camera is on LTS into 2025. It isn't a huge concern, but worth noting for future readers. I'm also not buying more cameras to test this edge case 🤣

2022-02-25 02:23 UTC, jbaines-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    appname = Rex::Text.rand_text_alpha_lower(3)
The official apps I looked at use 3 letters. I don't see a reason deviate 🤷

2022-02-25 02:52 UTC, jbaines-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +      "APPMICROVERSION='#{Rex::Text.rand_text_numeric(1)}'\n" \
I have my doubts that using more or less randomization in a module is actually important. But you asked, so I altered minor to 1..2 and micro to 1..3.

2022-02-25 02:52 UTC, jbaines-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    script_name = "#{Rex::Text.rand_text_alpha_lower(2..4)}.sh"
Altered for a wider range.

2022-02-25 05:27 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    appname = Rex::Text.rand_text_alpha_lower(3)
no problem that makes sense, marking resolved.

2022-02-25 05:28 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    return CheckCode::Safe(check_comment) unless res.body.include?('<reply result="ok">') != 200
Haha fair fair and yeah wasn't too concerned about it was more just seeing if you wanted to investigate it further or not. Marking resolved due to emulation difficulties n time constraints for now.

2022-02-25 05:33 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/axis_app_install.md
> +This module exploits the "Apps" feature in Axis IP cameras. The feature allows third party
Ah so the reason I ask is that some of their devices seem to be running Axis OS and but the devices like the one that you tested seem to be running a separate OS. I guess this and the lack of being able to find that page easily on their website led  to my confusion. I'll chat tomorrow about this some more though I think its a bit hard to describe specifically over GitHub.

2022-02-25 05:36 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +              }
Makes sense in that case and since we can't filter by staged/stageless support (at least not to my knowledge) this seems like an acceptable case for this. In an ideal world the ARMLE stager would work properly but I understand the point that fixing that may take a while and this is an optimal solution in the meantime. If the ARMLE stager working would solve this, might I suggest we add a comment so that future observers can make appropriate changes if and when this is fixed? Just might help with code maintainability.

2022-02-25 05:44 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +              }
As for excluding a default payload its more that if one doesn't set it then it defaults to a set default. Speak to Spencer if you want more details as I know he made a similar change to my Exchange Server exploit at https://github.com/rapid7/metasploit-framework/pull/16164/commits/6d325933a99281e26c7091ed52a19a346959d0a8. I believe he mentioned it was to help keep the framework more uniform vs every exploit having their own set default, but he would be able to explain it better than I can.

2022-02-25 05:48 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +      "APPMICROVERSION='#{Rex::Text.rand_text_numeric(1)}'\n" \
Its a fair point however I have seen reviews from coworkers mentioning it in the past so thought I'd bring it up. Ideally we want to make it as random as possible and this has always been a goal that our modules try to achieve, however to your credit I can also understand your point that in this particular scenario its not adding that much extra randomness.

2022-02-25 05:51 UTC, gwillcox-r7 approved these changes

2022-02-25 05:52 UTC, gwillcox-r7 commented
@jbaines-r7 New changes look good, can discuss remaining open issues over Slack but for the most part I should just be able to review your PCAP and get this landed, as rest are documentation related changes👍

2022-02-25 06:08 UTC, gwillcox-r7 requested changes
Some more things I noticed whilst examining the PCAPs, sorry for the extra review but thought these should be pointed out.

2022-02-25 06:08 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    multipart_form.add_part(eap, 'application/octet-stream', 'binary', 'form-data; name="fileData"; filename="exploit.eap"')
Naming the file `exploit.eap` is kind of a dead giveaway of exploitation. Along with the filename being `blob` is there any way we can randomize this? Very obvious indicator in the PCAP.

2022-02-25 06:08 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    })
Going to have to ask this but in the PCAP this and other requests where you set the username and password in this manner result in two requests being sent, one to check if authorization is needed for the request, and another to actually then send the request with the proper authentication. Given your request to upload the file is nearly 1MB in size, this may be a bit excessive.

I'd advise seeing if we need to adjust this to reduce double sending packets.

This comment applies to all instances where you are supplying the username and password to `send_request_cgi` in this manner. However in some cases it can be worse as we actually end up doing two requests, getting two 401 responses, and then authenticating properly.

2022-02-25 10:28 UTC, jbaines-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    })
What do you suggest as an alternative? This is literally how framework handles basic/digest authentication and, because the camera uses digest authentication there is no work around (other than changes to framework).

The size of the uploaded file doesn't matter. It's a single POST request.

2022-02-25 10:52 UTC, jbaines-r7 commented on documentation/modules/exploit/linux/http/axis_app_install.md
> +This module exploits the "Apps" feature in Axis IP cameras. The feature allows third party
I don't really follow the confusion. All their cameras run "Axis OS". It's just Linux. The M3044-V is no different. It uses the 9.80 LTS branch.

Why don't you just suggest wording that would make you happy?

2022-02-25 11:03 UTC, jbaines-r7 commented
Updated pcap
[axis_camera_again.zip](https://github.com/rapid7/metasploit-framework/files/8140619/axis_camera_again.zip)

2022-02-25 11:25 UTC, jbaines-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    multipart_form.add_part(eap, 'application/octet-stream', 'binary', 'form-data; name="fileData"; filename="exploit.eap"')
An oversight on my part. Fixed.

I would remind you though, that framework uses a multipart boundary that no one else uses and is therefore always a dead giveaway when multipart form is used.

2022-02-25 16:44 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/axis_app_install.md
> +All devices that support the "App" feature are presumed to be vulnerable at this time.
Yeah idk either. After reviewing this again with a fresh mind this should be fine as is. I was extending my concern r.e documentation and people not knowing what versions were affected too far. My apologies for all this.

2022-02-25 16:45 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/axis_app_install.md
> +This module exploits the "Apps" feature in Axis IP cameras. The feature allows third party
After reviewing this again with a fresh mind this should be fine as is. I was extending my concern r.e documentation and people not knowing what versions were affected too far. People can just run the `check` method if they need to find this out. My apologies for all this.

2022-02-25 16:46 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +    })
Sorry I was not aware this was how Digest Authentication worked so upon reviewing your explanation this makes perfect sense. Closing as this is working as intended.

2022-02-25 16:51 UTC, gwillcox-r7 commented on modules/exploits/linux/http/axis_app_install.rb
> +              }
Alright so I'm just going to land this with a comment mentioning the issue at https://github.com/rapid7/metasploit-framework/issues/16107 as being why this needs to be set so that we can track things in the code a little easier should we need to identify what needs to be  updated once that fix has landed.

2022-02-25 16:52 UTC, gwillcox-r7 approved these changes

2022-02-25 16:52 UTC, gwillcox-r7 commented
LGTM will land this now.

2022-02-25 17:35 UTC, merged

2022-02-25 17:40 UTC, gwillcox-r7 commented
# Release Notes

The "Apps" feature in Axis IP cameras allow allows third party developers to upload and execute 'eap' applications on the device, however no validation is performed to ensure the application comes from a trusted source. This module takes advantage of this vulnerability to allow authenticated attackers to upload and execute malicious applications and gain RCE.  Once the application has been installed and the shell has been obtained, the module will then automatically delete the malicious application. No CVE is assigned to this issue as a patch has not been released as of the time of writing.