enum_domain: Cleanup and support non-Meterpreter sessions
rapid7/metasploit-framework pull request #16953
Opened 2022-08-29 05:45 UTC by bcoles

Note: This requires #16952 to be merged first.

---

Resolves Rubocop violations.

Adds `Notes` module meta information.

Adds support for non-Meterpreter sessions.

2022-09-01 22:51 UTC, bcoles commented on documentation/modules/post/windows/gather/enum_domain.md
> +### Windows 2016 with Windows 2008 SP1 DC
I don't see why not.

2022-09-08 18:07 UTC, gwillcox-r7 requested changes

2022-09-08 18:18 UTC, gwillcox-r7 commented on modules/post/windows/gather/enum_domain.rb
> +    fail_with(Failure::Unknown, 'Could not retrieve domain name. Is the host part of a domain?') unless domain
Will be fixed in an upcoming commit.

2022-09-08 18:18 UTC, gwillcox-r7 commented on modules/post/windows/gather/enum_domain.rb
> +    fail_with(Failure::Unknown, 'Could not retrieve domain controller name') unless domain_controller
Will be fixed in an upcoming commit.

2022-09-08 18:31 UTC, gwillcox-r7 commented
With the changes listed above this should be good to go and works well in my tests. Will land now.

2022-09-08 18:40 UTC, closed without merging

2022-09-08 18:44 UTC, gwillcox-r7 commented
# Release Notes
The `enum_domain` script has been updated to support Powershell and Shell sessions and its documentation and code have been cleaned up.

2022-09-08 18:48 UTC, gwillcox-r7 commented on modules/post/windows/gather/enum_domain.rb
> +    fail_with(Failure::Unknown, 'Could not retrieve domain name. Is the host part of a domain?') unless domain
Fixed in https://github.com/rapid7/metasploit-framework/commit/7869e9229858e9e8de11aeea2685c50c812c01bd

2022-09-08 18:48 UTC, gwillcox-r7 commented on modules/post/windows/gather/enum_domain.rb
> +    fail_with(Failure::Unknown, 'Could not retrieve domain controller name') unless domain_controller
Fixed in https://github.com/rapid7/metasploit-framework/commit/7869e9229858e9e8de11aeea2685c50c812c01bd

2022-09-08 18:48 UTC, gwillcox-r7 commented
PR was merged in https://github.com/rapid7/metasploit-framework/commit/bf19b722b135035d5ac135306c8bc504654af915, sorry for the mess 😞