Apache CouchDB Erlang RCE module CVE-2022-24706
rapid7/metasploit-framework pull request #17142
Opened 2022-10-14 21:39 UTC by jheysel-r7

Almost finished this but got caught by the Friday evening hard stop.

Need to refactor `get_erlang_ports` /  `connect_to_erlang_server` to not throw `fail_with`'s so they can be used by the check method. Also need to configure targets with multiple erlang ports and test.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/smb/ms08_067_netapi`
- [ ] ...
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not
- [ ] **Document** the thing and how it works ([Example](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/multi/gather/aws_keys.md))

2022-10-19 17:45 UTC, gwillcox-r7 requested changes

2022-10-19 17:45 UTC, gwillcox-r7 commented on modules/exploits/multi/http/apache_couchdb_erlang_rce.rb
> +    return Exploit::CheckCode::Safe('This endpoint does not appear to expose any erlang ports') unless erlang_ports.instance_of?(Array)
Uh this is a bad check. You are checking that you return an array, but not if that array is empty. `erlang_ports` will always be some array since `get_erlang_ports` will always return an array, however that array will be empty if things fail.

Therefore in the current code this condition will never be hit.

2022-10-19 17:45 UTC, gwillcox-r7 commented on modules/exploits/multi/http/apache_couchdb_erlang_rce.rb
> +      fail_with(Failure::BadConfig, 'This endpoint does not appear to expose any erlang ports') unless erlang_ports.instance_of?(Array)
Same issue here as above, checking for an Array when in reality return value will always be an array and you should be checking if its empty.

2022-10-19 17:45 UTC, gwillcox-r7 commented on modules/exploits/multi/http/apache_couchdb_erlang_rce.rb
> +    msg << [cmd.length].pack('S>')
Should we be placing a command length limit slightly under 65,535 as a result of this size limit here due to 16 bit nature?

Also confused why this is 16 bit and the later length is 32 bit, so just want to make sure this is intentional.

2022-10-19 17:45 UTC, gwillcox-r7 commented on modules/exploits/multi/http/apache_couchdb_erlang_rce.rb
> +    print_status('sending payload... ')
```suggestion
    print_status('Sending payload... ')
```

2022-10-19 17:45 UTC, gwillcox-r7 commented on modules/exploits/multi/http/apache_couchdb_erlang_rce.rb
> +    print_status('Connection successful')
Should there not be error handling around this? Looking at https://github.com/jheysel-r7/metasploit-framework/blob/48af0887aa28f73511034563686b43ed2b567642/lib/msf/core/exploit/remote/tcp.rb#L90 it doesn't suggest that library does error handling on its own so I think it would fall on us to handle any connection failures.

Current code just seems to naturally assume that it will always be able to connect successfully from what I can tell.

2022-10-19 17:45 UTC, gwillcox-r7 commented on modules/exploits/multi/http/apache_couchdb_erlang_rce.rb
> +    challenge = challenge[9..12].unpack('N*')[0]
You haven't checked `challenge` at all before you hit this code. For all you know it could be empty, the length could be wrong, etc etc. There are a lot of ways you could crash this module as you are acting blindly on untrusted data without validating it.

2022-10-19 18:44 UTC, jheysel-r7 commented on documentation/modules/exploit/multi/http/apache_couchdb_erlang_rce.md
> +OS commands request.
Oops that should be `provides for the possibility of executing OS command requests`.

2022-10-19 18:44 UTC, jheysel-r7 commented on documentation/modules/exploit/multi/http/apache_couchdb_erlang_rce.md
> +cp
Oops, yea that got documented below, deleting this

2022-10-19 18:44 UTC, jheysel-r7 commented on documentation/modules/exploit/multi/http/apache_couchdb_erlang_rce.md
> +find /opt/couchdb -type d -exec chmod 0770 {} \;
Yea, i think it's necessary? If not it can be removed
https://stackoverflow.com/questions/19737525/find-type-f-exec-chmod-644

2022-10-19 18:57 UTC, jheysel-r7 commented on modules/exploits/multi/http/apache_couchdb_erlang_rce.rb
> +    return Exploit::CheckCode::Safe('This endpoint does not appear to expose any erlang ports') unless erlang_ports.instance_of?(Array)
I was hoping if the target didn't respond successfully the method would hit this early return:
https://github.com/rapid7/metasploit-framework/pull/17142/files#diff-2672fd8fc58afe47344534513003ff76611f140849d55201d290a6d5b41da8d2R150-R153

Though I can update this to be a bit more robust

2022-10-19 19:05 UTC, jheysel-r7 commented on documentation/modules/exploit/multi/http/apache_couchdb_erlang_rce.md
> +installer before version 3.2.1, by default, sets the cookie to "monster".
fixed

2022-10-20 01:34 UTC, jheysel-r7 commented on modules/exploits/multi/http/apache_couchdb_erlang_rce.rb
> +    challenge = challenge[9..12].unpack('N*')[0]
added a check for the response here

2022-10-20 01:34 UTC, jheysel-r7 commented on modules/exploits/multi/http/apache_couchdb_erlang_rce.rb
> +    print_status('Connection successful')
As discussed on call, the rescue statement below should take care of this

2022-10-20 01:34 UTC, jheysel-r7 commented on modules/exploits/multi/http/apache_couchdb_erlang_rce.rb
> +    msg << [cmd.length].pack('S>')
added payload MaxSize and yes i believe this is intentional as per the python poc

2022-10-20 13:38 UTC, dwelch-r7 commented on modules/exploits/multi/http/apache_couchdb_erlang_rce.rb
> +      sleep datastore['WfsDelay']
Replace the 'WfsDelay' with a separate option

2022-10-20 13:42 UTC, dwelch-r7 commented on modules/exploits/multi/http/apache_couchdb_erlang_rce.rb
> +    msg = "\x83h\x02gw\x0eAAAAAA@AAAAAAA\x00\x00\x00\x03\x00\x00\x00\x00\x00h\x05w\x04callw\x02osw\x03cmdl\x00\x00\x00\x01k"
Consider moving this up with the other constants + giving it a name describing what is is/means

2022-10-20 13:42 UTC, smcintyre-r7 commented on modules/exploits/multi/http/apache_couchdb_erlang_rce.rb
> +      sleep datastore['WfsDelay']
This could be a good use for https://github.com/rapid7/metasploit-framework/blob/8f5fd0949292f3a8d9aa208870a15319261d92e3/lib/msf/core/exploit/retry.rb#L8. That would allow the time to scale up without requiring the user to wait the full duration every time.

This would only work though if `sock.get_once` returns nil or any empty string when there's no data, that is to say that it's nonblocking.

2022-10-31 20:43 UTC, gwillcox-r7 commented
@msjenkins-r7 test this please.

2022-11-01 16:11 UTC, gwillcox-r7 commented on modules/exploits/multi/http/apache_couchdb_erlang_rce.rb
> +        'Privileged' => false,
After further discussion on Slack with the team this setting seems to be appropriate to leave as is.

2022-11-01 16:26 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/apache_couchdb_erlang_rce.md
> +Change the bind address of [chttpd] and [httpd] in `</path/to/couchdb/>etc/default.ini` from 127.0.0.1 to 0.0.0.0 or
```suggestion
Change the bind address of [chttpd] and [httpd] in `</path/to/couchdb/>/etc/default.ini` from 127.0.0.1 to 0.0.0.0 or
```

2022-11-01 16:33 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/apache_couchdb_erlang_rce.md
> +
Before this is done you need to restart the Apache CouchDB service so the new changes take effect

2022-11-01 17:25 UTC, gwillcox-r7 approved these changes

2022-11-01 17:27 UTC, merged

2022-11-01 17:31 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added to exploit CVE-2022-24706 an RCE within Apache CouchDB prior to 3.2.2 via the Erlang/OTP Distribution protocol, which used a default cookie of "monster" to allow users to connect and run OS commands.