scanner/smb/smb_login Kerberos Authentication Support
rapid7/metasploit-framework pull request #17175
Opened 2022-10-21 16:28 UTC by cdelafuente-r7

This updates `scanner/smb/smb_login` to support Kerberos authentication (close #17169).

This also adds two new attributes to the `Kerberos::ServiceAuthenticator::Base` class (`use_cached_credentials` and `store_credential_cache`) and the corresponding datastore options to the `Exploit::Remote::SMB::Client::Authenticated` mixin (`UseCachedCredentials` and `StoreCredentialCache` respectively). The former will enables/disables the use of cached Kerberos credentials from the database, which makes sense in a login scanner scenario since we usually want to check usernames and passwords and not using any credentials cached in the database. The latter enables/disables storing `.ccache` (Kerberos TGS MIT Credential Cache) to the loot. This option makes sense if we want to disable the use of cached credentials and avoid storing the new fresh ticket for the same principal. These options are both set to true by default, which keeps the original behavior (store credentials and use stored credentials).

**Note for reviewers**: There are a good number of changes due to Rubocop complaining. Those are all in the last commit. You should be able to see the actual interesting changes in the first commit.

## Verification

- [ ] Start `msfconsole`
- [ ] `use auxiliary/scanner/smb/smb_login`
- [ ] `set SMBAuth kerberos`
- [ ] `set RHOSTS <remote IP>`
- [ ] `set SmbRhostname <remote hostname>`
- [ ] `set DomainControllerRhost <domain controller IP>`
- [ ] `set SMBUser <username>`
- [ ] `set SMBPass <password>`
- [ ] `set SMBDomain <fully qualified domain name>`
- [ ] `exploit`
- [ ] **Verify** the initial Kerberos authentication to the KDC occurs
- [ ] **Verify** the TGS is stored in the loot
- [ ] **Verify** the SMB authentication succeeds
- [ ] `exploit`
- [ ] **Verify** the cached credential is used
- [ ] **Verify** the SMB authentication succeeds

Check the new datastore options:
- [ ] `set UseCachedCredentials false`
- [ ] `exploit`
- [ ] **Verify** the cached credential is **not** used
- [ ] **Verify** the SMB authentication succeeds
- [ ] **Verify** the new TGS is stored in the loot
- [ ] `set UseCachedCredentials true`
- [ ] `set StoreCredentialCache false`
- [ ] `exploit`
- [ ] **Verify** the cached credential is used
- [ ] **Verify** the SMB authentication succeeds
- [ ] **Verify** the new TGS is **not** stored in the loot
- [ ] `set UseCachedCredentials false`
- [ ] `exploit`
- [ ] **Verify** the cached credential is **not** used
- [ ] **Verify** the SMB authentication succeeds
- [ ] **Verify** the new TGS is **not** stored in the loot

### Scenarios
- NTLM authentication
```
msf6 auxiliary(scanner/smb/smb_login) > exploit verbose=true lhost=10.0.0.1 rhosts=10.0.0.24 SmbRhostname=dc01 DomainControllerRhost=10.0.0.24 smbuser=Administrator smbpass=123456 smbdomain=testlab.local

[*] 10.0.0.24:445   - 10.0.0.24:445 - Starting SMB login bruteforce
[+] 10.0.0.24:445   - 10.0.0.24:445 - Success: 'testlab.local\Administrator:123456' Administrator
[*] 10.0.0.24:445   - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/smb/smb_login) > creds
Credentials
===========

host       origin     service        public         private  realm  private_type  JtR Format
----       ------     -------        ------         -------  -----  ------------  ----------
10.0.0.24  10.0.0.24  445/tcp (smb)  Administrator  123456          Password
```

- Kerberos authentication
```
msf6 auxiliary(scanner/smb/smb_login) > exploit verbose=true SMBAuth=kerberos lhost=10.0.0.1 rhosts=10.0.0.24 SmbRhostname=dc01 DomainControllerRhost=10.0.0.24 smbuser=Administrator smbpass=123456 smbdomain=testlab.local

[*] 10.0.0.24:445   - 10.0.0.24:445 - Starting SMB login bruteforce
[*] 10.0.0.24:445   - 10.0.0.24:88 - Received a valid TGT-Response
[+] 10.0.0.24:445   - 10.0.0.24:88 - Received a valid TGS-Response
[*] 10.0.0.24:445   - 10.0.0.24:88 - TGS MIT Credential Cache saved to /home/msfuser/.msf4/loot/20221021165819_default_10.0.0.24_mit.kerberos.cca_545917.bin
[+] 10.0.0.24:445   - 10.0.0.24:88 - Received a valid delegation TGS-Response
[+] 10.0.0.24:445   - 10.0.0.24:445 - Success: 'testlab.local\Administrator:123456' Administrator
[*] 10.0.0.24:445   - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/smb/smb_login) > creds
Credentials
===========

host       origin     service        public         private  realm  private_type  JtR Format
----       ------     -------        ------         -------  -----  ------------  ----------
10.0.0.24  10.0.0.24  445/tcp (smb)  Administrator  123456          Password

msf6 auxiliary(scanner/smb/smb_login) > loot

Loot
====

host       service  type                 name  content                   info                                                                   path
----       -------  ----                 ----  -------                   ----                                                                   ----
10.0.0.24           mit.kerberos.ccache        application/octet-stream  realm: testlab.local, serviceName: cifs/dc01, username: administrator  /home/msfuser/.msf4/loot/20221021165819_default_10.0.0.24_mit.kerberos.cca_545917.bin
```

- Kerberos authentication - Using cached credential (default behavior)
```
msf6 auxiliary(scanner/smb/smb_login) > loot

Loot
====

host       service  type                 name  content                   info                                                                   path
----       -------  ----                 ----  -------                   ----                                                                   ----
10.0.0.24           mit.kerberos.ccache        application/octet-stream  realm: testlab.local, serviceName: cifs/dc01, username: administrator  /home/msfuser/.msf4/loot/20221021170140_default_10.0.0.24_mit.kerberos.cca_267956.bin

msf6 auxiliary(scanner/smb/smb_login) > exploit verbose=true SMBAuth=kerberos lhost=10.0.0.1 rhosts=10.0.0.24 SmbRhostname=dc01 DomainControllerRhost=10.0.0.24 smbuser=Administrator smbpass=123456 smbdomain=testlab.local

[*] 10.0.0.24:445   - 10.0.0.24:445 - Starting SMB login bruteforce
[*] 10.0.0.24:445   - 10.0.0.24:88 - Using cached credential for cifs/dc01 Administrator
[+] 10.0.0.24:445   - 10.0.0.24:445 - Success: 'testlab.local\Administrator:123456' Administrator
[*] 10.0.0.24:445   - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

- Kerberos authentication - Not storing ccache
```
msf6 auxiliary(scanner/smb/smb_login) > exploit verbose=true SMBAuth=kerberos lhost=10.0.0.1 rhosts=10.0.0.24 SmbRhostname=dc01 DomainControllerRhost=10.0.0.24 smbuser=Administrator smbpass=123456 smbdomain=testlab.local StoreCredentialCache=false

[*] 10.0.0.24:445   - 10.0.0.24:445 - Starting SMB login bruteforce
[*] 10.0.0.24:445   - 10.0.0.24:88 - Received a valid TGT-Response
[+] 10.0.0.24:445   - 10.0.0.24:88 - Received a valid TGS-Response
[+] 10.0.0.24:445   - 10.0.0.24:88 - Received a valid delegation TGS-Response
[+] 10.0.0.24:445   - 10.0.0.24:445 - Success: 'testlab.local\Administrator:123456' Administrator
[*] 10.0.0.24:445   - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/smb/smb_login) > loot

Loot
====

host  service  type  name  content  info  path
----  -------  ----  ----  -------  ----  ----
```

- Kerberos authentication - Not using cached credential, but storing ccache again (default behavior)
```
msf6 auxiliary(scanner/smb/smb_login) > loot

Loot
====

host       service  type                 name  content                   info                                                                   path
----       -------  ----                 ----  -------                   ----                                                                   ----
10.0.0.24           mit.kerberos.ccache        application/octet-stream  realm: testlab.local, serviceName: cifs/dc01, username:  [...]

2022-10-25 15:40 UTC, smcintyre-r7 requested changes
Everything looks good to me. I noticed only one issue that needs to be addressed.

When no credentials are cached and the password is incorrect, the status is reported as a normal status using `[*]` and not an error (with a red `[-]`). This is inconsistent with the WinRM login module that reports `KDC_ERR_PREAUTH_FAILED` as a proper login failure.

SMB Login Results:
```
msf6 auxiliary(scanner/smb/smb_login) > set UseCachedCredentials false
UseCachedCredentials => false
msf6 auxiliary(scanner/smb/smb_login) > run

[*] 192.168.159.115:445   - 192.168.159.115:445 - Starting SMB login bruteforce
[*] 192.168.159.115:445   - Error: 192.168.159.115: Rex::Proto::Kerberos::Model::Error::KerberosError Kerberos Error - KDC_ERR_PREAUTH_FAILED (24) - Pre-authentication information was invalid
[*] 192.168.159.115:445   - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/smb/smb_login) >
```

WinRM Login Results:
```
msf6 auxiliary(scanner/winrm/winrm_login) > run 

[-] 192.168.159.10: - LOGIN FAILED: MSFLAB.LOCAL\smcintyre:badpass (Incorrect: Kerberos Error - KDC_ERR_PREAUTH_FAILED (24) - Pre-authentication information was invalid)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/winrm/winrm_login) >
```

It's a different account, but you see the point.

2022-10-26 12:46 UTC, smcintyre-r7 commented on lib/msf/core/exploit/remote/smb/client/authenticated.rb
> +        OptBool.new('UseCachedCredentials', [false, 'Use credentials stored in the database for kerberos authentication', true], conditions: %w[ SMBAuth == kerberos ]),
Yeah I think for login scanners it would make the most sense to disable reading from the database cache by default. Writing should still probably be enabled though so successes can be reused.

FWIW though, if we flipped this to false by default then the behavior would be inconsistent with the WinRM and HTTP scanners which don't have this option. We may want to address that in a separate PR so they're all the same in that regard.

2022-10-27 14:04 UTC, bwatters-r7 commented on lib/metasploit/framework/login_scanner/smb.rb
> +          rescue RubySMB::Error::UnexpectedStatusCode
Maybe leave the variable for easier debugging? `_e`

2022-10-28 13:20 UTC, cdelafuente-r7 commented on lib/msf/core/exploit/remote/smb/client/authenticated.rb
> +        OptBool.new('UseCachedCredentials', [false, 'Use credentials stored in the database for kerberos authentication', true], conditions: %w[ SMBAuth == kerberos ]),
I agree and switched the default to `false` for the SMB login scanner. I left the Kerberos base service authenticator to true since it this option is not implemented in other modules yet.

2022-10-28 13:37 UTC, cdelafuente-r7 commented
Thanks for the review @smcintyre-r7 , @adfoster-r7 and @bwatters-r7 . I believe I fixed everything in the last commit.

Particularly, I added a Kerberos specific exception handler to better handle these errors in the login scanner context:
```
msf6 auxiliary(scanner/smb/smb_login) > exploit verbose=true SMBAuth=kerberos rhosts=10.0.0.24 SmbRhostname=dc01 DomainControllerRhost=10.0.0.24 smbuser=Administrator smbpass=1234567 smbdomain=testlab.local KrbStoreCredentialCache=false

[*] 10.0.0.24:445   - 10.0.0.24:445 - Starting SMB login bruteforce
[-] 10.0.0.24:445   - 10.0.0.24:445 - Failed: 'testlab.local\Administrator:1234567',
[*] 10.0.0.24:445   - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

2022-10-28 17:52 UTC, smcintyre-r7 commented on lib/metasploit/framework/login_scanner/smb.rb
> +            status = Metasploit::Framework::LoginScanner::Kerberos.login_status_for_kerberos_error(e)
```suggestion
          rescue Rex::Proto::Kerberos::Model::Error::KerberosError => e
            status = Metasploit::Framework::LoginScanner::Kerberos.login_status_for_kerberos_error(e)
            proof = e
```

2022-10-28 17:57 UTC, smcintyre-r7 approved these changes
Approved! Now the results log failures correctly. I made just one suggestion that I'll ninja commit myself which is to set `proof` to the exception. This imitates what [winrm](https://github.com/rapid7/metasploit-framework/blob/e2ce63170930a3954c525f40f2cbd2f5fe1b7e2e/lib/metasploit/framework/login_scanner/http.rb#L303) does.

```
msf6 auxiliary(scanner/smb/smb_login) > set SMBAuth 
SMBAuth => kerberos
msf6 auxiliary(scanner/smb/smb_login) > run

[*] 192.168.159.10:445    - 192.168.159.10:445 - Starting SMB login bruteforce
[-] 192.168.159.10:445    - 192.168.159.10:445 - Failed: '.\smcintyre:FOO', Kerberos Error - KDC_ERR_WRONG_REALM (68) - Wrong Realm / domain
[*] 192.168.159.10:445    - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/smb/smb_login) > set SMBDomain MSFLAB
SMBDomain => MSFLAB
msf6 auxiliary(scanner/smb/smb_login) > run

[*] 192.168.159.10:445    - 192.168.159.10:445 - Starting SMB login bruteforce
[-] 192.168.159.10:445    - 192.168.159.10:445 - Failed: 'MSFLAB\smcintyre:FOO', Kerberos Error - KDC_ERR_PREAUTH_FAILED (24) - Pre-authentication information was invalid
[*] 192.168.159.10:445    - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/smb/smb_login) > set SMBPASS Password1!
SMBPASS => Password1!
msf6 auxiliary(scanner/smb/smb_login) > run

[*] 192.168.159.10:445    - 192.168.159.10:445 - Starting SMB login bruteforce
[*] 192.168.159.10:445    - 192.168.159.10:88 - Received a valid TGT-Response
[-] 192.168.159.10:445    - 192.168.159.10:445 - Failed: 'MSFLAB\smcintyre:Password1!', Kerberos Error - KRB_AP_ERR_BADMATCH (36) - Ticket and authenticator don't match
[*] 192.168.159.10:445    - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/smb/smb_login) > show options 

Module options (auxiliary/scanner/smb/smb_login):

   Name               Current Setting  Required  Description
   ----               ---------------  --------  -----------
   ABORT_ON_LOCKOUT   false            yes       Abort the run when an account lockout is detected
   BLANK_PASSWORDS    false            no        Try blank passwords for all users
   BRUTEFORCE_SPEED   5                yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS       false            no        Try each user/password couple stored in the current database
   DB_ALL_PASS        false            no        Add all passwords in the current database to the list
   DB_ALL_USERS       false            no        Add all users in the current database to the list
   DB_SKIP_EXISTING   none             no        Skip existing credentials stored in the current database (Accepted: none, user, user&realm)
   DETECT_ANY_AUTH    false            no        Enable detection of systems accepting any authentication
   DETECT_ANY_DOMAIN  false            no        Detect if domain is required for the specified user
   PASS_FILE                           no        File containing passwords, one per line
   PRESERVE_DOMAINS   true             no        Respect a username that contains a domain name.
   Proxies                             no        A proxy chain of format type:host:port[,type:host:port][...]
   RECORD_GUEST       false            no        Record guest-privileged random logins to the database
   RHOSTS             192.168.159.10   yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT              445              yes       The SMB service port (TCP)
   SMBDomain          MSFLAB           no        The Windows domain to use for authentication
   SMBPass            Password1!       no        The password for the specified username
   SMBUser            smcintyre        no        The username to authenticate as
   STOP_ON_SUCCESS    false            yes       Stop guessing when a credential works for a host
   THREADS            1                yes       The number of concurrent threads (max one per host)
   USERPASS_FILE                       no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS       false            no        Try the username as the password for all users
   USER_FILE                           no        File containing usernames, one per line
   VERBOSE            true             yes       Whether to print output for all attempts

msf6 auxiliary(scanner/smb/smb_login) > set SMBRHOSTNAME DC.msflaInterrupt: use the 'exit' command to quit
msf6 auxiliary(scanner/smb/smb_login) > set SMBDomain msflab.local
SMBDomain => msflab.local
msf6 auxiliary(scanner/smb/smb_login) > run

[*] 192.168.159.10:445    - 192.168.159.10:445 - Starting SMB login bruteforce
[*] 192.168.159.10:445    - 192.168.159.10:88 - Received a valid TGT-Response
[+] 192.168.159.10:445    - 192.168.159.10:88 - Received a valid TGS-Response
[*] 192.168.159.10:445    - 192.168.159.10:88 - TGS MIT Credential Cache saved to /home/smcintyre/.msf4/loot/20221028135707_default_192.168.159.10_mit.kerberos.cca_845604.bin
[+] 192.168.159.10:445    - 192.168.159.10:88 - Received a valid delegation TGS-Response
[+] 192.168.159.10:445    - 192.168.159.10:445 - Success: 'msflab.local\smcintyre:Password1!' Administrator
[*] 192.168.159.10:445    - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/smb/smb_login) > 
```

Note how the error information is helpful.

2022-10-28 17:59 UTC, merged

2023-04-05 17:43 UTC, adfoster-r7 commented
## Release Notes

Updates the `scanner/smb/smb_login` module to support Kerberos authentication