Pre-Authenticated Remote Code Execution in Nortek Linear eMerge Access Controller [CVE-2019-7256]
rapid7/metasploit-framework pull request #17312
Opened 2022-11-29 10:42 UTC by h00die-gr3y

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

Please ensure you are submitting **from a unique branch** in your [repository](https://github.com/rapid7/metasploit-framework/pull/11086#issuecomment-445506416) to master in Rapid7's.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/smb/ms08_067_netapi`
- [ ] ...
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not
- [ ] **Document** the thing and how it works ([Example](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/multi/gather/aws_keys.md))

If you are opening a PR for a new module that exploits a **specific** piece of hardware or requires a **complex or hard-to-find** testing environment, we recommend that you send us a demo of your module executing correctly. Seeing your module in action will help us review your PR faster!

Specific Hardware Examples:
* Switches
* Routers
* IP Cameras
* IoT devices

Complex Software Examples:
* Expensive proprietary software
* Software with an extensive installation process
* Software that requires exploit testing across multiple significantly different versions
* Software without an English language UI

We will also accept demonstrations of successful module execution even if your module doesn't meet the above conditions. It's not a necessity, but it may help us land your module faster!

Demonstration of successful module execution can take the form of a packet capture (pcap) or a screen recording. You can send pcaps and recordings to [msfdev@metasploit.com](mailto:msfdev@metasploit.com). Please include a CVE number in the subject header (if applicable), and a link to your PR in the email body.
If you wish to sanitize your pcap, please see the [wiki](https://docs.metasploit.com/docs/development/get-started/sanitizing-pcaps.html).

2022-12-01 20:11 UTC, bwatters-r7 commented on documentation/modules/exploit/linux/http/linear_emerge_unauth_rce_cve_2019_7256.md
> +Installing a vulnerable test bed requires a Linear eMerge E3 access controller with the vulnerable software loaded.
I doubt we have one of these.  Can you provide us with a packet capture demonstrating the exploit?  Please be sure to remove any sensitive data from it and email msfdev[at]metasploit.com.
Thanks!

2022-12-02 16:38 UTC, h00die-gr3y commented on documentation/modules/exploit/linux/http/linear_emerge_unauth_rce_cve_2019_7256.md
> +Installing a vulnerable test bed requires a Linear eMerge E3 access controller with the vulnerable software loaded.
pcap files have been shared !

2022-12-08 14:42 UTC, bwatters-r7 commented on documentation/modules/exploit/linux/http/linear_emerge_unauth_rce_cve_2019_7256.md
> +Staged payloads like `linux/armle/meterpreter/reverse_tcp` or `linux/armle/shell/reverse_tcp` do not work.
```suggestion
```
This has been an issue we've been chasing. Unfortunately, this appears to be only an issue on a subset of armle devices, and I don't have any that display the behavior. See https://github.com/rapid7/metasploit-framework/issues/16107.  Having it in the documentation will be confusing when we fix this.

2022-12-08 15:40 UTC, h00die-gr3y commented on documentation/modules/exploit/linux/http/linear_emerge_unauth_rce_cve_2019_7256.md
> +Staged payloads like `linux/armle/meterpreter/reverse_tcp` or `linux/armle/shell/reverse_tcp` do not work.
ok, let me remove the first paragraph from the limitations section.

2022-12-15 16:33 UTC, h00die-gr3y commented
Gents are we still moving on this module?

2022-12-29 18:44 UTC, gwillcox-r7 commented
@h00die-gr3y Sorry for the delay most of the team has been out on holiday and we also had end of the year tasks that kept us from getting to this. Will take a look at this today once I've finished reviewing another PR.

2022-12-29 21:26 UTC, gwillcox-r7 requested changes

2022-12-29 21:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +          function allowing arbitrary command execution with root privileges.
Should mention the firmware version here just in case it does get patched? Also same point r.e E3 being a range of products and not a single product.

2022-12-29 21:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +          function allowing arbitrary command execution with root privileges.
Also no mention of the vulnerable page here, or the vulnerable parameters either which is something that should be mentioned here.

2022-12-29 21:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +          [ 'URL', 'https://www.nortekcontrol.com' ],
This redirects to https://na.niceforyou.com/. Is this the URL we want instead?

2022-12-29 21:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +          [ 'PACKETSTORM', '155256']
Missing EDB reference for https://www.exploit-db.com/exploits/47649

2022-12-29 21:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +        'Privileged' => false,
I would think this would be `true` given this gives `root` level access on the target device?

2022-12-29 21:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +          'door' => "`echo #{ROOT_PWD}|su -c \"#{cmd}\"`"
You are assuming here that the root password is never changed on the target device. What if it is and we know the password? The current module gives you no way to change this; your stuck with the `davestyle` root password or the entire module goes bust on this part of the code.

2022-12-29 21:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +    return send_request_cgi({
Not checking if the response is `Nil`, the status code, or if the response contains the expected data format here. Just returning it blindly, which may lead to issues. Code should be checking for this whenever using `send_request_cgi`.

2022-12-29 21:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +  rescue StandardError => e
Ideally you should avoid rescuing StandardError whenever possible as this can lead to cases of you capture exceptions that you were not trying to handle given the broad scope of StandardError. I'd look at perhaps trying to narrow the scope of this exception handling down.

2022-12-29 21:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +    sleep_time = rand(2..6)
This only gives 5 values, is there any way we can make the range a bit longer without compromising the exploit itself?

2022-12-29 21:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +    return CheckCode::Unknown('No response received from the target!') unless res
Should also be checking the response code and potentially the response body here as well otherwise any server that merely responds to  this request will be considered valid, even if it just responds with a 404 page not found response.

2023-01-01 08:27 UTC, h00die-gr3y commented on documentation/modules/exploit/linux/http/linear_emerge_unauth_rce_cve_2019_7256.md
> +that leverages card_scan_decoder.php.
Done. See https://github.com/rapid7/metasploit-framework/pull/17312/commits/008ba5334b2aeea230933567d1b7503232a016b5

2023-01-01 08:27 UTC, h00die-gr3y commented on documentation/modules/exploit/linux/http/linear_emerge_unauth_rce_cve_2019_7256.md
> +Building Automation and Access Control systems are at the heart of many critical infrastructures, and their security is vital.
Done. See https://github.com/rapid7/metasploit-framework/pull/17312/commits/008ba5334b2aeea230933567d1b7503232a016b5

2023-01-01 08:28 UTC, h00die-gr3y commented on documentation/modules/exploit/linux/http/linear_emerge_unauth_rce_cve_2019_7256.md
> +cameras, boilers, lights, safety alarm systems in an entire building.
Done. See https://github.com/rapid7/metasploit-framework/pull/17312/commits/008ba5334b2aeea230933567d1b7503232a016b5

2023-01-01 08:28 UTC, h00die-gr3y commented on documentation/modules/exploit/linux/http/linear_emerge_unauth_rce_cve_2019_7256.md
> +* Firmware < `v1.00-06`
Done. See https://github.com/rapid7/metasploit-framework/pull/17312/commits/008ba5334b2aeea230933567d1b7503232a016b5

2023-01-01 08:28 UTC, h00die-gr3y commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +          function allowing arbitrary command execution with root privileges.
Done. See https://github.com/rapid7/metasploit-framework/pull/17312/commits/008ba5334b2aeea230933567d1b7503232a016b5

2023-01-01 08:30 UTC, h00die-gr3y commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +          'door' => "`echo #{ROOT_PWD}|su -c \"#{cmd}\"`"
Good point. I added an option `ROOT_PASSWORD` with a preset value of `davestyle` which can be changed if needed. See https://github.com/rapid7/metasploit-framework/pull/17312/commits/008ba5334b2aeea230933567d1b7503232a016b5

2023-01-01 08:37 UTC, h00die-gr3y commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +    return send_request_cgi({
Let's discuss. I am returning the response from `send_request_cgi` as part of the `execute_command` function and use the return value to test it outside. I do not see an issue with this approach. Might be wrong here, but I did not see any issues applying this in my testing at the field.

2023-01-01 08:46 UTC, h00die-gr3y commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +  rescue StandardError => e
well I did this in very beginning using error handling like the example below, 

`rescue Rex::ConnectionRefused, Rex::HostUnreachable, Rex::ConnectionTimeout, Errno::ETIMEDOUT`

but during testing I ran occasionally in method errors where the exception handling did not work. Using `StandardError` seems to cover all of those.

2023-01-01 08:47 UTC, h00die-gr3y commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +    sleep_time = rand(2..6)
Done. See https://github.com/rapid7/metasploit-framework/pull/17312/commits/008ba5334b2aeea230933567d1b7503232a016b5

2023-01-01 08:57 UTC, h00die-gr3y commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +    return CheckCode::Unknown('No response received from the target!') unless res
In this case, I am only interested if I get a response back. I am not bothered about a 404 or a 200 at this stage, because the rest of the test that follows is about the timing of the `sleep` command injection response.
That determines if the target is vulnerable to command injection. There is unfortunately no other way to gather specific version information.

2023-01-01 09:06 UTC, h00die-gr3y commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +          [ 'URL', 'https://www.nortekcontrol.com' ],
Done. See https://github.com/rapid7/metasploit-framework/pull/17312/commits/008ba5334b2aeea230933567d1b7503232a016b5

2023-01-01 09:06 UTC, h00die-gr3y commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +          [ 'PACKETSTORM', '155256']
Done. See https://github.com/rapid7/metasploit-framework/pull/17312/commits/008ba5334b2aeea230933567d1b7503232a016b5

2023-01-01 09:06 UTC, h00die-gr3y commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +        'Privileged' => false,
Done. See https://github.com/rapid7/metasploit-framework/pull/17312/commits/008ba5334b2aeea230933567d1b7503232a016b5

2023-01-02 08:48 UTC, h00die-gr3y commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +    return CheckCode::Unknown('No response received from the target!') unless res
I could add a test on a 200 response before proceeding with the timing comparison.

2023-01-02 09:34 UTC, h00die-gr3y commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +    return CheckCode::Unknown('No response received from the target!') unless res
see https://github.com/rapid7/metasploit-framework/pull/17312/commits/ea70c5b7a0e50c7c3cceb9fc2687493f50c91ab9

2023-01-04 21:30 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/linear_emerge_unauth_rce_cve_2019_7256.md
> +that leverages card_scan_decoder.php.
Extra spacing on this but otherwise looks good, thanks for fixing this!

2023-01-04 21:32 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/linear_emerge_unauth_rce_cve_2019_7256.md
> +* Firmware < `v1.00-06`
Thanks this is much appreciated, looks good!

2023-01-04 21:38 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +          'door' => "`echo #{ROOT_PWD}|su -c \"#{cmd}\"`"
Looks good and this configurability is what I was after :) Only thing you forgot to do is add this into the `# Options` section of the documentation file, but I can go ahead and do that for ya 👍

2023-01-04 21:47 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +    return CheckCode::Unknown('No response received from the target!') unless res
So I guess the idea here was that in the PCAP the server responds with `card_format_default` inside of a JSON response as one of its keys. Similarly it also has `total_bit` as a key as well. Its a lot less likely a random server on the internet is going to have both of these JSON fields in a response to a `card_scan_decoder.php` page.

I do think the 200 OK response is a good idea though since this prevents this from being affected by something that takes a while to respond, such as a slow server that responds with a 404 page not found response to a request, but the JSON data check would add extra reassurance. Up to you though.

2023-01-04 22:14 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +    return send_request_cgi({
Yep your right your approach is fine, I misread how this code was operating. Marking resolved.

2023-01-04 22:18 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +      execute_command(payload.encoded)
The result of this call is not being checked at all. This should return a `res` object that should then be checked like you did above.

2023-01-04 22:20 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +      execute_command(payload.encoded)
Note for future travelers, whilst this may look like this return code needs to be validated, the reality is that the server will not respond so there is nothing to check here when the payload is successfully executed.

Going to add a comment into the file to this effect to avoid potential confusion down the line.

2023-01-04 22:21 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +  rescue StandardError => e
After discussing this further with the team, it seems we are fine to continue with the `StandardError` so should be all good.

2023-01-04 22:22 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +    return send_request_cgi({
Generally speaking I don't like this pattern since it means that you have to now duplicate checks in multiple places vs centralizing them at the caller, however I can see why you did this given that this will result in a response for the `check` code but not for the actual exploitation, so this is okay as is. 

Marking resolved.

2023-01-04 22:56 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +      execute_command(payload.encoded)
Fixed in bce867262c2535cb79d90ea2c70ab28527742494

2023-01-04 22:56 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +    return CheckCode::Unknown('No response received from the target!') unless res
Fixed in bce867262c2535cb79d90ea2c70ab28527742494

2023-01-04 22:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +          'door' => "`echo #{ROOT_PWD}|su -c \"#{cmd}\"`"
Fixed in https://github.com/rapid7/metasploit-framework/pull/17312/commits/bce867262c2535cb79d90ea2c70ab28527742494

2023-01-04 22:58 UTC, gwillcox-r7 approved these changes

2023-01-04 23:03 UTC, gwillcox-r7 commented
Alright looks like everything should be good now. Also rebased to make sure there were no merge conflicts and to squash 2 commits down. Will land once tests pass.

2023-01-05 00:07 UTC, gwillcox-r7 commented
Woot all tests passed, will land this now. Thanks for your help @h00die-gr3y!

2023-01-05 00:09 UTC, merged

2023-01-05 00:11 UTC, gwillcox-r7 commented
# Release Notes
An exploit has been added for CVE-2019-7256, an unauthenticated command injection vulnerability in Linear eMerge E3 versions `1.00-06` and below in the `No` and `door` parameters of `card_scan_decoder.php`. Successful exploitation results in RCE as the `root` user.

2023-01-05 15:30 UTC, gwillcox-r7 commented on modules/exploits/linux/http/linear_emerge_unauth_rce_cve_2019_7256.rb
> +  rescue StandardError => e
As a note on this for future travelers, the code at https://github.com/rapid7/metasploit-framework/blob/cb682973f7701a276476af7ced304bc9ce7c8fc8/lib/msf/core/exploit/remote/http_client.rb#L403-L412 should be handling all but `Errno::ETIMEDOUT` here from what I can tell.