Update .mailmap
rapid7/metasploit-framework pull request #17428
Opened 2022-12-30 23:06 UTC by wvu

Removing myself.

2022-12-30 23:09 UTC, h00die requested changes, later dismissed
Rejected, sinn3r was gone longer and still in here. You will love on forever!

2023-01-01 21:39 UTC, gwillcox-r7 commented
On a serious note, perhaps we should move you down to the section denoted by the header mentioning past employees? It seems that is the convention and we might also want to do it for some other past employees such as sinn3r etc so we can still keep the info here but denote that it refers to past employees of Rapid7?

Though happy to remove entirely if that would be preferred, provided no issues from others r.e any historical archive concerns that may be prevalent.

2023-01-04 14:49 UTC, smcintyre-r7 commented
Yeah, I'm also inclined to reject this in favor of moving the entries down to the appropriate section. Looking through this it looks like nmt.edu one was responsible for 4 commits, which after this change are not grouped together as wvu-r7@github.

2023-01-04 15:02 UTC, gwillcox-r7 commented
Going to grab this and try to make the appropriate changes to your branch @wvu to fix this up so that we can relocate things to the right location.

2023-01-04 15:42 UTC, gwillcox-r7 commented
Looks like I don't have permissions to push to your repo @wvu so here is the file with the changes I was going to make. This moves past employees to the appropriate section, but also adds in your email to the email list.

<details>
<summary>File Contents</summary>


```
adfoster-r7 <adfoster-r7@github>       <alandavid_foster@rapid7.com>
bwatters-r7 <bwatters-r7@github>       <bwatters@rapid7.com>
cdelafuente-r7 <cdelafuente-r7@github> Christophe De La Fuente <christophe_delafuente@rapid7.com>
cdoughty-r7 <cdoughty-r7@github>       <chris_doughty@rapid7.com>
cgranleese-r7 <cgranleese-r7@github>   <christopher_granleese@rapid7.com>
dheiland-r7 <dheiland-r7@github>       <dh@layereddefense.com>
dwelch-r7 <dwelch-r7@github>           <dean_welch@rapid7.com>
gwillcox-r7 <gwillcox-r7@github>       <Grant_Willcox@rapid7.com>
jmartin-r7 <jmartin-r7@github>         <Jeffrey_Martin@rapid7.com>
mkienow-r7 <mkienow-r7@github>         <matthew_kienow@rapid7.com>
pdeardorff-r7 <pdeardorff-r7@github>   <paul_deardorff@rapid7.com>
pdeardorff-r7 <pdeardorff-r7@github>   <Paul_Deardorff@rapid7.com>
smcintyre-r7 <smcintyre-r7@github>     <spencer_mcintyre@rapid7.com>
space-r7 <space-r7@github>             <shelby_pace@rapid7.com>
todb-r7 <todb-r7@github>               <tod_beardsley@rapid7.com>
todb-r7 <todb-r7@github>               <todb@metasploit.com>
todb-r7 <todb-r7@github>               <todb@packetfu.com>

# Above this line are current Rapid7 employees. Below this paragraph are
# volunteers, former employees, and potential Rapid7 employees who, at
# one time or another, had some largeish number of commits landed on
# rapid7/metasploit-framework master branch.  This should be refreshed
# periodically. If you're on this list and would like to not be, just
# let todb@metasploit.com know.

acammack-r7 <acammack-r7@github>       <acammack@aus-mbp-1099.aus.rapid7.com>
acammack-r7 <acammack-r7@github>       <adam_cammack@rapid7.com>
acammack-r7 <acammack-r7@github>       <Adam_Cammack@rapid7.com>
adamgalway-r7 <adamgalway-r7@github>   <adam_galway@rapid7.com>
asoto-r7 <asoto-r7@github>             <aaron_soto@rapid7.com>
bannedit <bannedit@github>             David Rude <bannedit0@gmail.com>
bcoles <bcoles@github>                 bcoles <bcoles@gmail.com>
bcook-r7 <bcook-r7@github>             <bcook@rapid7.com>
bcook-r7 <bcook-r7@github>             <busterb@gmail.com>
bokojan <bokojan@github>               parzamendi-r7 <peter_arzamendi@rapid7.com>
bpatterson-r7 <bpatterson-r7@github>   <bpatterson@rapid7.com>
bpatterson-r7 <bpatterson-r7@github>   <Brian_Patterson@rapid7.com>
brandonprry <brandonprry@github>       <bperry@brandons-mbp.attlocal.net>
brandonprry <brandonprry@github>       Brandon Perry <bperry@bperry-rapid7.(none)>
brandonprry <brandonprry@github>       Brandon Perry <bperry.volatile@gmail.com>
brandonprry <brandonprry@github>       Brandon Perry <brandon.perry@zenimaxonline.com>
bturner-r7 <bturner-r7@github>         <brandon_turner@rapid7.com>
bwall <bwall@github>                   Brian Wallace <bwall@openbwall.com>
bwall <bwall@github>                   (B)rian (Wall)ace <nightstrike9809@gmail.com>
ceballosm <ceballosm@github>           Mario Ceballos <mc@metasploit.com>
Chao-mu <Chao-Mu@github>               chao-mu <chao@confusion.(none)>
Chao-mu <Chao-Mu@github>               <chao.mu@minorcrash.com>
ChrisJohnRiley <ChrisJohnRiley@github> Chris John Riley <chris.riley@c22.cc>
ChrisJohnRiley <ChrisJohnRiley@github> Chris John Riley <reg@c22.cc>
claudijd <claudijd@github>             Jonathan Claudius <claudijd@yahoo.com>
claudijd <claudijd@github>             Jonathan Claudius <jclaudius@trustwave.com>
corelanc0d3r <corelanc0d3r@github>     corelanc0d3r <peter.ve@corelan.be>
corelanc0d3r <corelanc0d3r@github>     Peter Van Eeckhoutte (corelanc0d3r) <peter.ve@corelan.be>
crcatala <crcatala@github>             Christian Catalan <ccatalan@rapid7.com>
darkoperator <darkoperator@github>     Carlos Perez <carlos_perez@darkoperator.com>
DanielRTeixeira <DanielRTeixeira@github> Daniel Teixeira <danieljcrteixeira@gmail.com>
dmaloney-r7 <dmaloney-r7@github>       <David_Maloney@rapid7.com>
dmaloney-r7 <dmaloney-r7@github>       <DMaloney@rapid7.com>
dmohanty-r7 <dmohanty-r7@github>       <Dev_Mohanty@rapid7.com>
ecarey-r7 <ecarey-r7@github>           <e@ipwnstuff.com>
efraintorres <efraintorres@github>     efraintorres <etlownoise@gmail.com>
efraintorres <efraintorres@github>     et <>
egypt <egypt@github>                   <egypt@metasploit.com> # aka egypt
egypt <egypt@github>                   <james_lee@rapid7.com>
espreto <espreto@github>               <robertoespreto@gmail.com>
fab <fab@???>                          fab <> # fab at revhosts.net (Fabrice MOURRON)
farias-r7 <farias-r7@github>           <fernando_arias@rapid7.com>
FireFart <FireFart@github>             <firefart@gmail.com>
FireFart <FireFart@github>             <FireFart@users.noreply.github.com>
gmikeska-r7 <gmikeska-r7@github>       <greg_mikeska@rapid7.com>
gmikeska-r7 <gmikeska-r7@github>       greg.mikeska@rapid7.com <=>
gmikeska-r7 <gmikeska-r7@github>       greg.mikeska@rapid7.com <YOUR_USERNAME_FOR_EMAIL>
g0tmi1k <g0tmi1k@github>               <g0tmi1k@users.noreply.github.com>
g0tmi1k <g0tmi1k@github>               <have.you.g0tmi1k@gmail.com>
h00die <h00die@github>                 <h00die@users.noreply.github.com>
h00die <h00die@github>                 <mike@shorebreaksecurity.com>
h0ng10 <h0ng10@github>                 h0ng10 <hansmartin.muench@googlemail.com>
h0ng10 <h0ng10@github>                 Hans-Martin Münch <hansmartin.muench@googlemail.com>
hdm <hdm@github>                       HD Moore <hdm@digitaloffense.net>
hdm <hdm@github>                       HD Moore <hd_moore@rapid7.com>
hdm <hdm@github>                       HD Moore <x@hdm.io>
jabra <jabra@github>                   <jabra@spl0it.org>
jbarnett-r7 <jbarnett-r7@github>       <James_Barnett@rapid7.com>
jbarnett-r7 <jbarnett-r7@github>       <jbarnett@rapid7.com>
jcran <jcran@github>                   <jcran@0x0e.org>
jcran <jcran@github>                   <jcran@pentestify.com>
jcran <jcran@github>                   <jcran@pwnieexpress.com>
jcran <jcran@github>                   <jcran@rapid7.com>
jduck <jduck@github>                   <github.jdrake@qoop.org>
jduck <jduck@github>                   <jdrake@qoop.org>
jgor <jgor@github>                     jgor <jgor@indiecom.org>
jhart-r7 <jhart-r7@github>             <jon_hart@rapid7.com>
jinq102030 <jinq102030@github>         <Jin_Qian@rapid7.com>
jinq102030 <jinq102030@github>         <jqian@rapid7.com>
joevennix <joevennix@github>           Joe Vennix <joevennix@gmail.com>
joevennix <joevennix@github>           <Joe_Vennix@rapid7.com>
joevennix <joevennix@github>           <joev@metasploit.com>
joevennix <joevennix@github>           jvennix-r7 <Joe_Vennix@rapid7.com>
juanvazquez <juanvazquez@github>       jvazquez-r7 <juan.vazquez@metasploit.com>
juanvazquez <juanvazquez@github>       jvazquez-r7 <juan_vazquez@rapid7.com>
kernelsmith <kernelsmith@github>       Joshua Smith <kernelsmith@kernelsmith.com>
kernelsmith <kernelsmith@github>       Joshua Smith <kernelsmith@metasploit.com>
kernelsmith <kernelsmith@github>       kernelsmith <kernelsmith@kernelsmith>
kgray-r7 <kgray-r7@github>             <kyle_gray@rapid7.com>
kost <kost@github>                     Vlatko Kosturjak <kost@linux.hr>
kris <kris@???>                        kris <>
KronicDeth <KronicDeth@github>         Luke Imhoff <luke_imhoff@rapid7.com>
lsanchez-r7 <lsanchez-r7@github>       <lance@aus-mac-1041.aus.rapid7.com>
lsanchez-r7 <lsanchez-r7@github>       <lance@AUS-MAC-1041.local>
lsanchez-r7 <lsanchez-r7@github>       <lance.sanchez+github@gmail.com>
lsanchez-r7 <lsanchez-r7@github>       <lance.sanchez@gmail.com>
lsanchez-r7 <lsanchez-r7@github>       <lance.sanchez@rapid7.com>
lsato-r7 <lsato-r7@github>             <lsato@rapid7.com>
lvarela-r7 <lvarela-r7@github>         <“leonard [...]

2023-01-05 03:13 UTC, todb commented
Yes indeed. If you want to smoke bomb outta the consolidated credits, you're of course welcome to, @wvu

2023-01-05 05:10 UTC, wvu commented
Bbiab. Feel free to push whatever you need, @gwillcox-r7.

2023-01-05 15:15 UTC, gwillcox-r7 commented
Updated and removed your contact @wvu since I believe this matches what you originally intended to commit. This should be good to merge once the tests pass.

2023-01-05 15:39 UTC, merged

2023-01-05 18:44 UTC, wvu commented
> Yeah, I'm also inclined to reject this in favor of moving the entries down to the appropriate section. Looking through this it looks like nmt.edu one was responsible for 4 commits, which after this change are not grouped together as wvu-r7@github.

To be fair, these weren't `-r7` commits.

2023-01-05 18:49 UTC, wvu commented
> Updated and removed your contact @wvu since I believe this matches what you originally intended to commit. This should be good to merge once the tests pass.

Thanks, everyone. I'm just glad the list is updated. :)