update http options module
rapid7/metasploit-framework pull request #17481
Opened 2023-01-15 11:45 UTC by h00die

fix #12557

This PR fixes some of the issues with the http options module:
1. adds `targeturi` option as `/` isn't always the right answer
2. uses `send_request_cgi` because `raw` was just not needed
3. updated to http 1.1 instead of 1.0
4. lint
5. if a host doesn't give an `allow` header, print something so we have *some* feedback
6. attempt to handle the Tomcat error page

I was unable to find a host that had the Tomcat error page, but there are a bunch of internet references to it, so I did my best to code it in.

## Verification

- [ ] Start `msfconsole`
- [ ] `use auxiliary/scanner/http/options`
- [ ] `set rhosts`
- [ ] `set verbose true`
- [ ] `run`
- [ ] **Verify** if the host doesn't respond with `Allow` header, you get an error message
- [ ] **Verify** hosts with `Allow` headers still work

# old output

```
msf6 auxiliary(scanner/http/options) > run

[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

# new output

```
msf6 auxiliary(scanner/http/options) > run

[-] 1.1.1.1 missing Allow header
[*] Scanned 1 of 1 hosts (100% complete)
```

2023-01-15 23:13 UTC, adfoster-r7 commented on modules/auxiliary/scanner/http/options.rb
> +    }, 10)
```suggestion
    })
```

I know this was an existing value; but I'm not sure if the hard coded timeout was intentional here 👀

2023-01-30 23:06 UTC, gwillcox-r7 requested changes

2023-01-30 23:06 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/options.rb
> +    if res.body =~ %r{<h1>HTTP Status 405 - JSPs only permit ([^<]*)</h1>}
Not sure we necessarily need to match on these H1 tags since that might change, what are your feelings on removing them from the regex?

2023-01-30 23:06 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/options.rb
> +    print_good("#{target_host} allows #{allowed_methods} methods")
Is this not an array of items normally? Your edge case seems to be converting this into a string but I'm not sure this code will work in normal circumstances.

2023-02-01 19:45 UTC, h00die commented on modules/auxiliary/scanner/http/options.rb
> -  # Scanner mixin should be near last
they felt very generic and like things we'd put in an example file for people to learn with.  Just generally not needed.

2023-02-01 19:53 UTC, h00die commented on modules/auxiliary/scanner/http/options.rb
> +      vprint_error("#{target_host} missing Allow header")
when scanning a large address space (class C), I would by default think you'd only want to see alive valid things, and verbosely see things that aren't there

2023-02-01 19:54 UTC, h00die commented on modules/auxiliary/scanner/http/options.rb
> +    # patch so that tomcat which responds in HTTP will work as well
I've re-worded this to be more clear

2023-02-01 19:57 UTC, h00die commented on modules/auxiliary/scanner/http/options.rb
> +    if res.body =~ %r{<h1>HTTP Status 405 - JSPs only permit ([^<]*)</h1>}
It may change, but I think this is also an edge case for a likely outdated version as I couldn't find any in the wild to test it against, so I think its safe to keep at this point.

2023-02-01 20:19 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/options.rb
> -  # Scanner mixin should be near last
My concern was that these were added to prevent issues with people adding dependencies as includes and then breaking things as a result of bad ordering. Granted this is a module and not a library so perhaps this is less needed since its less likely to break a whole suite of things, but I still think its good practice to document cases where things might fail if something was to be changed in a way that would be expected to work but in reality won't work.

2023-02-01 20:23 UTC, h00die commented on modules/auxiliary/scanner/http/options.rb
> +    print_good("#{target_host} allows #{allowed_methods} methods")
during testing I also added `puts res.headers['Allow'].class` and received `String` in the output, so I believe everything is a string that I'm dealing with.

2023-02-01 20:32 UTC, h00die commented on modules/auxiliary/scanner/http/options.rb
> -  # Scanner mixin should be near last
i'll add them back, nbd

2023-02-01 20:39 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/options.rb
> +    print_good("#{target_host} allows #{allowed_methods} methods")
Thanks that is sufficient for me, will mark this as resolved, don't think this should be an issue.

2023-02-01 20:45 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/options.rb
> +      vprint_error("#{target_host} missing Allow header")
The caveat here is what if you are scanning just a single host? It will fail silently.

2023-02-01 20:50 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/options.rb
> +    return if res.nil?
These two lines are pretty much equivalent? I imagine we can skip the `.nil? case and keep the first line.

2023-02-01 20:50 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/options.rb
> +    return if !res
Updates look fine, marking as resolved.

2023-02-01 20:52 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/options.rb
> +    if res.body =~ %r{<h1>HTTP Status 405 - JSPs only permit ([^<]*)</h1>}
Hmm fair point, lets keep it in as is, and we can update it later if needed.

2023-02-01 20:56 UTC, h00die commented on modules/auxiliary/scanner/http/options.rb
> +      vprint_error("#{target_host} missing Allow header")
Being an aux scanner module, I assume its mostly used for large block scans.  Also per my original issue:
`Also, the module should say (in verbose) that none were detected if none were detected. Right now you just get no output at all.`
So the original module, no matter what, gave no output for a host w/o an Allow header.  This at least gives you an option to see it if need be

2023-02-01 21:09 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/options.rb
> +      vprint_error("#{target_host} missing Allow header")
Fair point and after reviewing this further I came to the same conclusion r.e the code in that a bigger change would be needed to incorporate what I was suggesting. I'll leave this as is, your fix is in line with existing behavior 👍

2023-02-01 21:10 UTC, gwillcox-r7 commented
Everything looks good, will fix up the one minor remaining comment and then test and land this 👍

2023-02-01 21:17 UTC, gwillcox-r7 commented
Looks like baseline still works, now to test a host that doesn't respond with an Allow header:

```
msf6 > use auxiliary/scanner/http/options 
msf6 auxiliary(scanner/http/options) > set RHOSTS www.google.com
RHOSTS => www.google.com
msf6 auxiliary(scanner/http/options) > set VERBOSE true
VERBOSE => true
msf6 auxiliary(scanner/http/options) > run

[+] 142.250.138.105 allows GET, HEAD methods
[*] Scanned 1 of 7 hosts (14% complete)
[+] 142.250.138.99 allows GET, HEAD methods
[*] Scanned 2 of 7 hosts (28% complete)
[+] 142.250.138.147 allows GET, HEAD methods
[*] Scanned 3 of 7 hosts (42% complete)
[+] 142.250.138.104 allows GET, HEAD methods
[*] Scanned 4 of 7 hosts (57% complete)
[+] 142.250.138.103 allows GET, HEAD methods
[*] Scanned 5 of 7 hosts (71% complete)
[+] 142.250.138.106 allows GET, HEAD methods
[*] Scanned 6 of 7 hosts (85% complete)
[-] The host ([2607:f8b0:4000:81b::2004]:80) was unreachable.
[*] Scanned 7 of 7 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/options) >
```

And on a host without the allow header things are working as expected:

```
msf6 auxiliary(scanner/http/options) > show options

Module options (auxiliary/scanner/http/options):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     www.rapid7.com   yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT      80               yes       The target port (TCP)
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  /                yes       URI to test
   THREADS    1                yes       The number of concurrent threads (max one per host)
   VHOST                       no        HTTP server virtual host


View the full module info with the info, or info -d command.

msf6 auxiliary(scanner/http/options) > set RPORT 443
RPORT => 443
msf6 auxiliary(scanner/http/options) > run

[-] 13.249.74.44 missing Allow header
[*] Scanned 1 of 4 hosts (25% complete)
[-] 13.249.74.39 missing Allow header
[*] Scanned 2 of 4 hosts (50% complete)
[-] 13.249.74.83 missing Allow header
[*] Scanned 3 of 4 hosts (75% complete)
[-] 13.249.74.60 missing Allow header
[*] Scanned 4 of 4 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/options) > set SSL true
[!] Changing the SSL option's value may require changing RPORT!
SSL => true
msf6 auxiliary(scanner/http/options) > run

[-] 13.249.74.83 missing Allow header
[*] Scanned 1 of 4 hosts (25% complete)
[-] 13.249.74.44 missing Allow header
[*] Scanned 2 of 4 hosts (50% complete)
[-] 13.249.74.60 missing Allow header
[*] Scanned 3 of 4 hosts (75% complete)
[-] 13.249.74.39 missing Allow header
[*] Scanned 4 of 4 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/options) > 
```

2023-02-01 21:18 UTC, gwillcox-r7 commented
LGTM will land this once tests pass!

2023-02-01 21:20 UTC, gwillcox-r7 commented
# Release Notes
An update has been made to the `modules/auxiliary/scanner/http/options.rb` module to modernize a few of its options, tidy up the code, and to handle an edge case when a target server might respond with a Tomcat error page.

2023-02-01 21:48 UTC, gwillcox-r7 approved these changes

2023-02-01 21:51 UTC, merged

2023-02-01 22:28 UTC, h00die commented
thanks for the cleanup!