Add additional reliability and stability notes to modules
rapid7/metasploit-framework pull request #17634
Opened 2023-02-13 10:18 UTC by adfoster-r7

Add additional reliability and stability notes to modules

## Verification

- Verify the notes are cromulent

2023-02-14 17:54 UTC, gwillcox-r7 reviewed
I've reviewed a few of these 6 files but already I'm seeing a worrying trend to use the same base template of CRASH_SAFE and REPEATABLE_SESSION for all of these files regardless of the nature of the vulnerability involved. I've noted a few cases here but ideally I think this point needs further consideration and will be pausing my review until we can come to some conclusion on this, as I'd prefer not to be giving people the false impression that these exploits are more reliable than they actually are.

2023-02-14 17:54 UTC, gwillcox-r7 commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +          'Reliability' => [ REPEATABLE_SESSION ]
Is this a good option given it this involves a race condition and two information leaks? Seems to me there is a small chance that the race condition might be lost here.

2023-02-14 17:54 UTC, gwillcox-r7 commented on modules/exploits/apple_ios/browser/safari_jit.rb
> +          'Stability' => [ CRASH_SAFE ],
I really doubt this is crash safe. This is JIT in Safari followed by a shellcode memory write and kernel exploit. Most of the time in my experience this is unstable at best and highly temperamental. Is there a reason that we believe this is crash safe that I'm not aware of?

Same comment also applies to the REPEATABLE_SESSION part here.

2023-03-03 18:14 UTC, gwillcox-r7 commented
@adfoster-r7 Do you have any updates on the above? Would love to get this landed but have some outstanding concerns.

2023-03-03 19:07 UTC, adfoster-r7 commented
Hoping to get this sorted next week-ish :+1:

2023-04-18 16:06 UTC, adfoster-r7 commented on modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
> +          'Reliability' => [ REPEATABLE_SESSION ]
The exploit runs in a loop; so it should be repeatable https://github.com/rapid7/metasploit-framework/blob/4cab6cd0dba37f011bfdc7153ddfc1a3b846d236/modules/exploits/windows/scada/rockwell_factorytalk_rce.rb#L205-L212

2023-05-11 20:49 UTC, gwillcox-r7 requested changes

2023-05-11 20:49 UTC, gwillcox-r7 commented on modules/exploits/unix/webapp/opensis_chain_exec.rb
> +          'SideEffects' => [ CONFIG_CHANGES, IOC_IN_LOGS ],
I'm not sure why CONFIG_CHANGES is included here. Is there a reason for this? The setting of the session variable isn't what I'd consider a config change. Otherwise looks good.

2023-05-11 20:49 UTC, gwillcox-r7 commented on modules/exploits/unix/fileformat/metasploit_libnotify_cmd_injection.rb
> +          'Reliability' => [ REPEATABLE_SESSION ]
According to the notes:

```
In order to trigger the vulnerable code path, the service reported must be unique. This means that when the exploit file is loaded, it will not trigger the vulnerability again unless the service is removed. The easiest way to remove the service is to delete all services from the database using the services -d command.
```

Therefore its possible the vulnerability may not trigger a second time unless the service is removed, which this code doesn't seem to do automatically.

I think `UNRELIABLE_SESSION` is better here given this limitation.

2023-05-23 21:33 UTC, gwillcox-r7 commented
Bump, any update on this?

2024-01-23 09:41 UTC, sjanusz-r7 approved these changes

2024-01-23 09:42 UTC, merged

2024-01-23 09:44 UTC, sjanusz-r7 commented
## Release Notes
Reliability and stability notes that have been previously missing have been added to some modules.