Add in SCHANNEL support for LDAP
rapid7/metasploit-framework pull request #17699
Opened 2023-02-24 20:00 UTC by gwillcox-r7

Its finally here 🥳 SCHANNEL support has now been added in for LDAP so you can now use certificates to authenticate to the server and retrieve sensitive information as the user the certificate is authorized to authenticate as (if the certificate allows certificate authentication).

This should start completing the diagram that Spencer put up at https://gist.github.com/zeroSteiner/47dc724da74e6bd3f7c9b1da319ccb4b by completing the link between `Certificate` and `LDAP` by adding in the SCHANNEL support.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] Follow the directions at https://docs.metasploit.com/docs/pentesting/active-directory/ad-certificates/icpr_cert.html#issue-a-generic-certificate to get a certificate as a given user. Just make sure the certificate template specified has permissions to perform certificate authentication (has the Client Authentication, PKINIT Client Authentication, Smart Card Logon, Any Purpose, or SubCA EKUs enabled and allows enrollment by the user you are enrolling as).
- [ ] `use auxiliary/gather/ldap_query`
- [ ] `set LDAP::Auth schannel`
- [ ] `set RHOST *target host, usually the DC which is running the LDAP server*`
- [ ] `set PFX_PATH *path to the loot file on disk where the PFX data was saved from earlier*`
- [ ] `set SSL true`
- [ ] `run` or `exploit`
- [ ] Verify that you get the expected data.
- [ ] Verify via WireShark that that the traffic is TLS encrypted.

Here is an example run for convenience sake:

```
msf6 > use auxiliary/gather/ldap_query
msf6 auxiliary(gather/ldap_query) > set RHOST 192.168.153.167
RHOST => 192.168.153.167
msf6 auxiliary(gather/ldap_query) > set LDAP::Auth schannel
LDAP::Auth => schannel
msf6 auxiliary(gather/ldap_query) > show options

Module options (auxiliary/gather/ldap_query):

   Name           Current Setting  Required  Description
   ----           ---------------  --------  -----------
   BASE_DN                         no        LDAP base DN if you already have it
   DOMAIN                          no        The domain to authenticate to
   OUTPUT_FORMAT  table            yes       The output format to use (Accepted: csv, table, json)
   PASSWORD                        no        The password to authenticate with
   PFX_PATH                        no        The path to the PFX file on disk to authenticate with
   RHOSTS         192.168.153.167  yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT          389              yes       The target port
   SSL            false            no        Enable SSL on the LDAP connection
   USERNAME                        no        The username to authenticate with

   When ACTION is RUN_SINGLE_QUERY:

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   QUERY_ATTRIBUTES                   no        Comma seperated list of attributes to retrieve from the server
   QUERY_FILTER                       no        Filter to send to the target LDAP server to perform the query

   When ACTION is RUN_QUERY_FILE:

   Name             Current Setting  Required  Description
   ----             ---------------  --------  -----------
   QUERY_FILE_PATH                   no        Path to the JSON or YAML file to load and run queries from

Auxiliary action:

   Name           Description
   ----           -----------
   ENUM_ACCOUNTS  Dump info about all known user accounts in the domain.

View the full module info with the info, or info -d command.

msf6 auxiliary(gather/ldap_query) > set PFX_PATH /home/gwillcox/.msf4/loot/20230222155929_default_192.168.153.150_windows.ad.cs_830521.pfx
PFX_PATH => /home/gwillcox/.msf4/loot/20230222155929_default_192.168.153.150_windows.ad.cs_830521.pfx
msf6 auxiliary(gather/ldap_query) > exploit
[*] Running module against 192.168.153.167

[*] Discovering base DN automatically
[+] 192.168.153.167:389 Discovered base DN: DC=daforest,DC=com
[+] 192.168.153.167:389 Discovered schema DN: DC=daforest,DC=com
CN=Administrator CN=Users DC=daforest DC=com
============================================

 Name                Attributes
 ----                ----------
 badpwdcount         0
 description         Built-in account for administering the computer/domain
 lastlogoff          1601-01-01 00:00:00 UTC
 lastlogon           2023-02-24 18:25:30 UTC
 logoncount          97
 memberof            CN=Group Policy Creator Owners,CN=Users,DC=daforest,DC=com || CN=Domain Admins,CN=Users,DC=daforest,DC=com || CN=Enterprise Admins,CN=Users,DC=daforest,DC=com || CN=Schema Admins,CN=Users,DC=daforest,DC=com || CN=Users,CN=Builtin,DC=daforest,DC=com || CN=Administrators,CN=Builtin,DC=daforest,DC=com
 name                Administrator
 objectsid           S-1-5-21-583768849-728913032-1533249101-500
 pwdlastset          133164016158726978
 samaccountname      Administrator
 useraccountcontrol  66048

CN=Guest CN=Users DC=daforest DC=com
====================================

 Name                Attributes
 ----                ----------
 badpwdcount         0
 description         Built-in account for guest access to the computer/domain
 lastlogoff          1601-01-01 00:00:00 UTC
 lastlogon           1601-01-01 00:00:00 UTC
 logoncount          0
 memberof            CN=Guests,CN=Builtin,DC=daforest,DC=com
 name                Guest
 objectsid           S-1-5-21-583768849-728913032-1533249101-501
 pwdlastset          0
 samaccountname      Guest
 useraccountcontrol  66082

CN=WIN-BRSHGJGIDFM OU=Domain Controllers DC=daforest DC=com
===========================================================

 Name                Attributes
 ----                ----------
 badpwdcount         0
 lastlogoff          1601-01-01 00:00:00 UTC
 lastlogon           2023-02-24 14:47:00 UTC
 logoncount          333
 memberof            CN=Pre-Windows 2000 Compatible Access,CN=Builtin,DC=daforest,DC=com || CN=Cert Publishers,CN=Users,DC=daforest,DC=com
 name                WIN-BRSHGJGIDFM
 objectsid           S-1-5-21-583768849-728913032-1533249101-1000
 pwdlastset          133191500547736948
 samaccountname      WIN-BRSHGJGIDFM$
 useraccountcontrol  532480

CN=krbtgt CN=Users DC=daforest DC=com
=====================================

 Name                Attributes
 ----                ----------
 badpwdcount         0
 description         Key Distribution Center Service Account
 lastlogoff          1601-01-01 00:00:00 UTC
 lastlogon           1601-01-01 00:00:00 UTC
 logoncount          0
 memberof            CN=Denied RODC Password Replication Group,CN=Users,DC=daforest,DC=com
 name                krbtgt
 objectsid           S-1-5-21-583768849-728913032-1533249101-502
 pwdlastset          133164161644084399
 samaccountname      krbtgt
 useraccountcontrol  514

CN=CHILD$ CN=Users DC=daforest DC=com
=====================================

 Name                Attributes
 ----                ----------
 badpwdcount         0
 lastlogoff          1601-01-01 00:00:00 UTC
 lastlogon           1601-01-01 00:00:00 UTC
 logoncount          0
 name                CHILD$
 objectsid           S-1-5-21-583768849-728913032-1533249101-1103
 pwdlastset          133189882446424612
 samaccountname      CHILD$
 useraccountcontrol  2080

CN=normal CN=Users DC=daforest DC=com
=====================================

 Name                Attributes
 ----                ----------
 badpwdcount         0
 displayname         normal
 lastlogoff          1601-01-01 00:00:00 UTC
 lastlogon           2023-01-25 20:36:46 UTC
 logoncount          2
 name                normal
 objectsid           S-1-5-21-583768849-728913032-1533249101-1107
 pwdlastset          133189972129176212
 samaccountname      normal
 useraccountcontrol  66048
 userprincipalname   normal@daforest.com

[*] Auxiliary module execution completed
msf6 auxiliary(gather/ldap_query) > 
```

2023-02-24 20:19 UTC, gwillcox-r7 commented
A quick note on why some of the other files changed: found a bug with `to_json` calls that were being called on `Net::LDAP` object. In essence the issue boiled down to the fact that sometimes, `to_json` would end up hanging. I'm not sure why this occurs but it does. To cut a long story short, if you use `get_operation_result` instead this hang doesn't occur and this is more or less the proper way we are meant to be accessing the objects we are after.

Therefore I went ahead and updated some of the library code and one module I found (the RBCD one) to switch over to this new mechanism as if we do hang, we unfortunately can't just CTRL+C to exit things. The entirety of Metasploit will freeze and unless you have a debugger to send the interrupt properly, will simply cease to respond.

2023-02-27 15:01 UTC, smcintyre-r7 requested changes

2023-02-27 17:07 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/ldap.rb
> +        Msf::OptString.new('PFX_PATH', [false, 'The path to the PFX file on disk to authenticate with', ''])
Fixed in https://github.com/rapid7/metasploit-framework/pull/17699/commits/4cd50b45508b16c8df058f7028b38e46af614328

2023-02-27 17:07 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/ldap.rb
> +        fail_with(Msf::Exploit::Remote::Failure::BadConfig, 'SCHANNEL authentication requires an SSL connection!') if datastore['SSL'] != true
Fixed in https://github.com/rapid7/metasploit-framework/pull/17699/commits/4cd50b45508b16c8df058f7028b38e46af614328

2023-02-27 18:52 UTC, smcintyre-r7 commented on lib/msf/core/exploit/remote/ldap.rb
> +        pkcs = OpenSSL::PKCS12.new(File.read(pfx_path), '')
We could do a little better here like this:

```suggestion
        unless ::File.file?(pfx_path) and ::File.readable?(pfx_path)
          fail_with(Msf::Exploit::Remote::Failure::BadConfig, "Failed to load the PFX file. The path is not a readable file.")
        end
        begin
          pkcs = OpenSSL::PKCS12.new(File.binread(pfx_path), '')
        rescue => e
          fail_with(Msf::Exploit::Remote::Failure::BadConfig, "Failed to load the PFX file (#{e})")
        end
```

This would specifically differentiate between an path that isn't a readable file and a file that is readable but can't be loaded because it's in the wrong format.

2023-02-27 20:13 UTC, gwillcox-r7 commented on lib/msf/core/exploit/remote/ldap.rb
> +        pkcs = OpenSSL::PKCS12.new(File.read(pfx_path), '')
Should be fixed now with https://github.com/rapid7/metasploit-framework/pull/17699/commits/524f5e4e633a5b6592438c0e9fc60475f7c03f94

2023-02-27 21:20 UTC, smcintyre-r7 approved these changes
Looks great to me. Once all the tests pass I'll get this landed. Here in the demo output you can see that the query requires authentication and then I use schannel authentication to run it.

```
msf6 auxiliary(gather/ldap_query) > run
[*] Running module against 192.168.159.10

[*] Discovering base DN automatically
[+] 192.168.159.10:389 Discovered base DN: DC=msflab,DC=local
[-] Auxiliary aborted due to failure: unknown: An LDAP operational error occurred on (objectClass=*). It is likely the client requires authorization! The error was: 000004DC: LdapErr: DSID-0C090A5C, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563
[*] Auxiliary module execution completed
msf6 auxiliary(gather/ldap_query) > run LDAP::Auth=schannel LDAP::CertFile=/home/smcintyre/.msf4/loot/20230227094434_default_192.168.159.10_windows.ad.cs_452383.pfx
[*] Running module against 192.168.159.10

[-] Auxiliary aborted due to failure: bad-config: The SSL option must be enabled when using SCHANNEL authentication.
[*] Auxiliary module execution completed
msf6 auxiliary(gather/ldap_query) > run LDAP::Auth=schannel LDAP::CertFile=/home/smcintyre/.msf4/loot/20230227094434_default_192.168.159.10_windows.ad.cs_452383.pfx SSL=true 
[*] Running module against 192.168.159.10

[*] Discovering base DN automatically
[+] 192.168.159.10:389 Discovered base DN: DC=msflab,DC=local
[+] 192.168.159.10:389 Discovered schema DN: DC=msflab,DC=local
DC=msflab DC=local
==================

 Name                       Attributes
 ----                       ----------
 lockoutduration            0:00:30:00
 lockoutthreshold           0
 maxpwdage                  42:00:00:00
 minpwdage                  1:00:00:00
 minpwdlength               7
 ms-ds-machineaccountquota  10
 name                       msflab
 objectsid                  S-1-5-21-3402587289-1488798532-3618296993

[*] Auxiliary module execution completed
msf6 auxiliary(gather/ldap_query) > run LDAP::Auth=schannel LDAP::CertFile=/home/smcintyre/ SSL=true
[*] Running module against 192.168.159.10

[-] Auxiliary aborted due to failure: bad-config: Failed to load the PFX certificate file. The path was not a readable file.
[*] Auxiliary module execution completed
msf6 auxiliary(gather/ldap_query) > run LDAP::Auth=schannel LDAP::CertFile=/etc/resolv.conf SSL=true
[*] Running module against 192.168.159.10

[-] Auxiliary aborted due to failure: bad-config: Failed to load the PFX file (PKCS12_parse: invalid null pkcs12 pointer)
[*] Auxiliary module execution completed
msf6 auxiliary(gather/ldap_query) > 
```

After running it I also double check the argument validation abit by passing it a directory, an invalid file, no SSL, etc.

:tada:

2023-02-27 21:36 UTC, merged

2023-02-27 21:36 UTC, smcintyre-r7 commented
# Release Notes
This adds SCHANNEL authentication support to LDAP modules.