Pentaho Business Server Auth Bypass and SSTI
rapid7/metasploit-framework pull request #17964
Opened 2023-05-03 19:42 UTC by jheysel-r7

This PR adds a module that exploits Pentaho Business server based on the [Pentah0wnage: Pre-Auth RCE in Pentaho Business Analytics Server](https://research.aurainfosec.io/pentest/pentah0wnage/#timeline) blog post by Harry Withington.

PoC: https://github.com/dwbzn/pentaho-exploits/blob/main/cve-2022-43769.py
## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] Start msfconsole  
- [ ] Do: `use multi/http/pentaho_business_server_authbypass_and_ssti`  
- [ ] Set the `RHOST` and `LHOST` options
- [ ] Ensure the `TARGET` option corresponds to the environment being targeted.  
- [ ] Run the module  
- [ ] Receive a session in the context of the user that's running the Pentaho Business Server.  

## Vulnerable Softare
https://www.hitachivantara.com/en-us/products/lumada-dataops/data-integration-analytics/download-pentaho.html

Note - The Linux installation wasn't working for me out of the box on Ubuntu. I would recommend testing on Windows 11.

2023-05-04 18:26 UTC, jheysel-r7 commented on modules/exploits/multi/http/pentaho_business_server_authbypass_and_ssti.rb
> +    java_payload.gsub!('\\', '%5C')
I originally tried using `Rex::Text.uri_encode` although it didn't replace the `\` with a `%5C` so I switched them out manually. 
```
3.0.5 :001 > require 'rex'
 => true
3.0.5 :002 > payload = 'AHAAAAM8Dr>>%TEMP%\VoDHz.b64'
 => "AHAAAAM8Dr>>%TEMP%\\VoDHz.b64"
3.0.5 :003 > Rex::Text.uri_encode(payload)
 => "AHAAAAM8Dr%3e%3e%25TEMP%25\\VoDHz.b64"
```
What do you think would be best to use to encode this payload?

2023-05-08 22:22 UTC, gwillcox-r7 commented
Gonna grab this so long and see if I can't push things along in time for the Thursday cut off. If not then, then hopefully should be able to get this landed by end of the week.

2023-05-09 19:19 UTC, gwillcox-r7 requested changes

2023-05-09 19:44 UTC, gwillcox-r7 commented on modules/exploits/multi/http/pentaho_business_server_authbypass_and_ssti.rb
> +    java_payload = <<~JAVA.gsub(/^\s+/, '').tr("\n", '')
Fixed in a154c16f87a77034f71eb7192e197bc6e703d2ad

2023-05-09 20:59 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/http/pentaho_business_server_authbypass_and_ssti.md
> +page.
Fixed with e8a57561c64babf34ad4adde9a374e6a5c17948e

2023-05-09 23:38 UTC, gwillcox-r7 commented
@jheysel-r7 Tried running this a few times but was unable to get a session. Its possible something I did with the code may have changed something so as to make this not work; will need to take a further look into this.

2023-05-10 14:56 UTC, gwillcox-r7 commented on modules/exploits/multi/http/pentaho_business_server_authbypass_and_ssti.rb
> +    java_payload.gsub!('\\', '%5C')
Turns out that was not the best suggestion since it ended up messing up a few things. I'll push up a fix that sets this manually for the `send_request_cgi` request so that we can avoid this.

2023-05-10 14:57 UTC, gwillcox-r7 commented on modules/exploits/multi/http/pentaho_business_server_authbypass_and_ssti.rb
> +        'pwd' => 'a'
Further investigation revealed that these can be randomized so I'll go ahead and apply changes to allow these to be randomized.

2023-05-10 15:17 UTC, gwillcox-r7 commented on modules/exploits/multi/http/pentaho_business_server_authbypass_and_ssti.rb
> +        'pwd' => 'a'
Fixed in https://github.com/rapid7/metasploit-framework/pull/17964/commits/1b8f1de7c8707b3108193b7399777497377c7fe1

2023-05-11 14:10 UTC, gwillcox-r7 approved these changes

2023-05-11 14:28 UTC, merged

2023-05-11 14:31 UTC, gwillcox-r7 commented
# Release Notes
A new module has been added which exploits Hitachi Vantara Pentaho Business Analytics Server versions before 9.4.0.1 and 9.3.0.2, including 8.3.x. To do this it first exploits CVE-2022-43939 to bypass authentication before then using CVE-2022-43769, a Server Side Template Injection (SSTI) vulnerability, to achieve unauthenticated code execution as the user running the Pentaho Business Analytics Server.