Remote::JndiInjection: handle LDAP UnbindRequest
rapid7/metasploit-framework pull request #18069
Opened 2023-06-06 04:59 UTC by sempervictus

@ErikWynter showed me this output during his effort to pwn APC servers:
![image](https://github.com/rapid7/metasploit-framework/assets/1331084/1ac5d899-8b79-42d2-8efc-50c50db91016)

The `unexpected request 2` bit is misleading - thats the LDAP component not handling the session termination in the catch-all. This takes developers down the wrong debug path, and is easy to remedy.
Resolve by explicitly adding a case for the `UnbindRequest` type.

Ping @smcintyre-r7 - requesting eyes-on in case i broke something (its kinda late). :smile:

2023-06-06 18:27 UTC, jvoisin approved these changes

2023-06-08 21:09 UTC, smcintyre-r7 requested changes
Would you mind also updating https://github.com/rapid7/metasploit-framework/blob/4b082b997b2758736af82fc2238c3a36174e2c0a/lib/rex/proto/ldap/server.rb#L185 to include these changes so they stay in sync?

2023-06-10 13:43 UTC, sempervictus commented
> Would you mind also updating
> 
> https://github.com/rapid7/metasploit-framework/blob/4b082b997b2758736af82fc2238c3a36174e2c0a/lib/rex/proto/ldap/server.rb#L185
> to include these changes so they stay in sync?

set

2023-06-12 13:53 UTC, smcintyre-r7 approved these changes
Changes look good to me. I tested this by using the `exploit/multi/http/log4shell_header_injection` module and setting WfsDelay to 300. While the module was waiting for a shell, I was able to use a client to perform bind and unbind requests to ensure things were functioning properly.

```
msf6 exploit(multi/http/log4shell_header_injection) > run

[+] mkfifo /tmp/lasod; (nc -l -p 4444 ||nc -l 4444)0</tmp/lasod | /bin/sh >/tmp/lasod 2>&1; rm /tmp/lasod
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Using auxiliary/scanner/http/log4shell_scanner as check
[*] Scanned 1 of 1 hosts (100% complete)
[*] Sleeping 300 seconds for any last LDAP connections
[*] Client sent unbind request
```

2023-06-12 13:54 UTC, merged

2023-06-12 14:02 UTC, smcintyre-r7 commented
# Release Notes
This updates the LDAP server library to handle unbind requests.