Note when SMBv1 is supported to the user
rapid7/metasploit-framework pull request #19131
Opened 2024-04-24 10:54 UTC by nrathaus

This improves the feedback listed here: https://github.com/rapid7/metasploit-framework/issues/17402

## Verification

List the steps needed to make sure this thing works

- [ ] Run using `docker-compose up`, SMBv1 supported server, and SMBv1 not supported and see difference in outcome
- [ ] Start `msfconsole`
- [ ] `use smb_version`
- [ ] `run 172.24.0.2`

docker-compose with SMBv1:
```
version: "3"

services:
  sambav1:
    image: dperson/samba:latest
    container_name: samba
    restart: unless-stopped
    command: '-g "ntlm auth = yes" -g "server min protocol = NT1" -S -s "Files;/mnt/files;yes;yes"'
    ports:
      - 139:139
      - 445:445
    environment:
      - TZ=PST8PDT
    volumes:
      - files:/mnt/files

volumes:
  files:
```

docker-compose without SMBv1:
```
version: "3"

services:
  sambav1:
    image: dperson/samba:latest
    container_name: samba
    restart: unless-stopped
    command: '-s "Files;/mnt/files;yes;yes"'
    ports:
      - 139:139
      - 445:445
    environment:
      - TZ=PST8PDT
    volumes:
      - files:/mnt/files

volumes:
  files:
```

2024-04-24 13:10 UTC, smcintyre-r7 commented on modules/auxiliary/scanner/smb/smb_version.rb
> +        end
Wouldn't this be covered on the previous line where `(version:` includes 1? This seems redundant. I would expect a server that supports SMBv1 to show `(versions:1)` or `(versions:1,2)`, etc.

2024-04-24 13:48 UTC, adfoster-r7 commented
> I think that issue was to say that the host operating system information isn't extracted from the NTLM challenge/response when SMBv1 isn't in use.

Yip; it looks like from the original ticket I was hoping that the host information was extracted from the NTLMSSP_CHALLENGE response:

> I would have expected the Windows 10.0 Build 14393 metadata to be present
> I think the information should be extractable from the STATUS_MORE_PROCESSING_REQUIRED, NTLMSSP_CHALLENGE response

Sorry for the confusion in the original ticket

2024-04-24 13:58 UTC, nrathaus commented
Can you clarify what are the requirements for completing the task? I will
try to work on it


On Wed, 24 Apr 2024 at 16:49, adfoster-r7 ***@***.***> wrote:

> I think that issue was to say that the host operating system information
> isn't extracted from the NTLM challenge/response when SMBv1 isn't in use.
>
> Yip; it looks like from the original ticket I was hoping that the host
> information was extracted from the NTLMSSP_CHALLENGE response:
>
> I would have expected the Windows 10.0 Build 14393 metadata to be present
> I think the information should be extractable from the
> STATUS_MORE_PROCESSING_REQUIRED, NTLMSSP_CHALLENGE response
>
> Sorry for the confusion in the original ticket
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rapid7/metasploit-framework/pull/19131#issuecomment-2074997707>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAPQE3URTLJWWV7ERT6Z4V3Y66Z6HAVCNFSM6AAAAABGWVHNA6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANZUHE4TONZQG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-04-25 09:53 UTC, nrathaus commented
I think what you are asking to add already exists:
```
msf6 auxiliary(scanner/smb/smb_version) > run 172.22.0.2

[*] 172.22.0.2:445        - SMB Detected (versions:1, 2, 3) (preferred dialect:SMB 3.1.1) (compression capabilities:) (encryption capabilities:AES-128-GCM) (signatures:optional) (guid:{63613736-3062-3034-6238-653700000000}) (authentication domain:67ACB040B8E7)
[*] 172.22.0.2:445        -   Host could not be identified: Windows 6.1 (Samba 4.12.2)
[*] 172.22.0.2:           - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

NOTE the part about **Windows 6.1 (Samba 4.12.2)**

2024-04-25 09:55 UTC, compliance-r7 submitted a review, later dismissed
Only pom.xml has changed, approved!

2024-04-25 10:09 UTC, adfoster-r7 commented
Running smb_version against a windows target with SMB v1,v2,v3 enabled outputs the target build information ✅ 

```
msf6 auxiliary(scanner/smb/smb_version) > rerun rhost=192.168.123.136 username=vagrant password=vagrant
[*] Reloading module...

[*] 192.168.123.136:445   - Force SMB1 since SMB fingerprint needs native_lm/native_os information
[*] 192.168.123.136:445   - SMB Detected (versions:1, 2, 3) (preferred dialect:SMB 3.1.1) (compression capabilities:) (encryption capabilities:AES-128-GCM) (signatures:optional) (uptime:3m 45s) (guid:{eafd6aa4-cdfe-41c7-a1c5-340d151af52a}) (authentication domain:WINDEV)Windows 2016 Standard (build:14393) (name:WINDEV)
[+] 192.168.123.136:445   -   Host is running SMB Detected (versions:1, 2, 3) (preferred dialect:SMB 3.1.1) (compression capabilities:) (encryption capabilities:AES-128-GCM) (signatures:optional) (uptime:3m 45s) (guid:{eafd6aa4-cdfe-41c7-a1c5-340d151af52a}) (authentication domain:WINDEV)Windows 2016 Standard (build:14393) (name:WINDEV)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[*] 192.168.123.136:      - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

Disabling SMB v1 on the windows target:

```
Set-SmbServerConfiguration -EnableSMB1Protocol $false
```

Running the same module against the target with SMB v1 disabled no longer shows the target build information ❌ 

```
msf6 auxiliary(scanner/smb/smb_version) > rerun rhost=192.168.123.136 username=vagrant password=vagrant 
[*] Reloading module...

[*] 192.168.123.136:445   - Force SMB1 since SMB fingerprint needs native_lm/native_os information
[*] 192.168.123.136:445   - SMB Detected (versions:2, 3) (preferred dialect:SMB 3.1.1) (compression capabilities:) (encryption capabilities:AES-128-GCM) (signatures:optional) (uptime:4m 52s) (guid:{eafd6aa4-cdfe-41c7-a1c5-340d151af52a}) (authentication domain:WINDEV)
[*] 192.168.123.136:445   -   Host could not be identified
[*] 192.168.123.136:      - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

We can see that that build information is missing on the re-scan; but from wireshark it looks like it should be available just fine in the NTLMSSP_CHALLENGE packet:

![image](https://github.com/rapid7/metasploit-framework/assets/60357436/e77d1731-ef77-436a-a0d6-157e7c16f624)

2024-04-25 10:22 UTC, nrathaus commented
This information is processed in these two lines of code:
```
        response = smb2_ntlmssp_negotiate
        challenge_packet = smb2_ntlmssp_challenge_packet(response)
```

2024-04-25 10:23 UTC, nrathaus commented
Specifically, the:
`packet = RubySMB::SMB2::Packet::SessionSetupResponse.read(raw_response)`

2024-04-25 10:26 UTC, nrathaus commented
There seems to be no parsing of the `GSS-API Generic Security Service Application Program Interface` section of the data

2024-04-25 10:28 UTC, nrathaus commented
There seems to be some thought placed into the code to support GSS?
```
        def set_type2_blob(type1_message)
          gss_blob = RubySMB::Gss.gss_type2(type1_message)
          self.security_buffer_length = gss_blob.length
          self.buffer = gss_blob
        end
```

But nothing calls this function

2024-04-25 10:35 UTC, nrathaus commented
Parsing this data while coding it in Ruby is at the moment beyond my technical skills

2024-04-25 10:40 UTC, nrathaus commented
BTW It seems to be in fact (the security blob) ASN.1 encoded content:
https://gchq.github.io/CyberChef/#recipe=Parse_ASN.1_hex_string(0,32)&input=ICAgYTEgODEgZDYgMzAgODEgZDMgYTAgMDMgMGEgMDEgMDEgYTEgMGMgMDYgMGEgMmIKICAgMDYgMDEgMDQgMDEgODIgMzcgMDIgMDIgMGEgYTIgODEgYmQgMDQgODEgYmEgNGUKICAgNTQgNGMgNGQgNTMgNTMgNTAgMDAgMDIgMDAgMDAgMDAgMTggMDAgMTggMDAgMzgKICAgMDAgMDAgMDAgMzUgODIgOGEgZTIgY2IgOGMgOWQgNTkgMjkgNTcgNzYgNTkgMDAKICAgMDAgMDAgMDAgMDAgMDAgMDAgMDAgNmEgMDAgNmEgMDAgNTAgMDAgMDAgMDAgMDYKICAgMDEgMDAgMDAgMDAgMDAgMDAgMGYgMzYgMDAgMzMgMDAgMzQgMDAgNDUgMDAgMzIKICAgMDAgNDQgMDAgNDQgMDAgMzkgMDAgNDYgMDAgMzggMDAgMzMgMDAgMzAgMDAgMDIKICAgMDAgMTggMDAgMzYgMDAgMzMgMDAgMzQgMDAgNDUgMDAgMzIgMDAgNDQgMDAgNDQKICAgMDAgMzkgMDAgNDYgMDAgMzggMDAgMzMgMDAgMzAgMDAgMDEgMDAgMTggMDAgMzYKICAgMDAgMzMgMDAgMzQgMDAgNDUgMDAgMzIgMDAgNDQgMDAgNDQgMDAgMzkgMDAgNDYKICAgMDAgMzggMDAgMzMgMDAgMzAgMDAgMDQgMDAgMDIgMDAgMDAgMDAgMDMgMDAgMTgKICAgMDAgMzYgMDAgMzMgMDAgMzQgMDAgNjUgMDAgMzIgMDAgNjQgMDAgNjQgMDAgMzkKICAgMDAgNjYgMDAgMzggMDAgMzMgMDAgMzAgMDAgMDcgMDAgMDggMDAgZTggNGQgMGEKICAgNzAgZmEgOTYgZGEgMDEgMDAgMDAgMDAgMDAK

2024-04-25 21:01 UTC, smcintyre-r7 commented
You should be able to parse it using [RubyNTLM](https://github.com/WinRb/rubyntlm) / `Net::NTLM`. It's possible the entire message isn't available outside of RubySMB and RubySMB would need to be updated to parse the message when it's available, extract and save the necessary fields.

2024-04-25 22:33 UTC, adfoster-r7 commented
iirc there's all of the required parsers over in the ruby_smb library for that octet string/buffer, i.e. these methods:

https://github.com/rapid7/ruby_smb/blob/681f67763491639365acd6c18b3d3ce4f70388ce/lib/ruby_smb/peer_info.rb

And the binary model:

https://github.com/rapid7/ruby_smb/blob/681f67763491639365acd6c18b3d3ce4f70388ce/lib/ruby_smb/ntlm.rb#L48

2024-04-26 06:53 UTC, nrathaus commented
Is RubyNTLM being shipped/used by metasploit atm? or do I need to copy-paste the code there into the smb.rb that comes with Metasploit?

2024-04-26 12:55 UTC, smcintyre-r7 commented
It's already included with Metasploit https://github.com/rapid7/metasploit-framework/blob/master/metasploit-framework.gemspec#L84

It's worth noting though, that for the actual authentication workflow we use our [own client](https://github.com/rapid7/ruby_smb/blob/master/lib/ruby_smb/ntlm/client.rb#L17) from RubySMB because it includes some changes we haven't been able to get merged into the upstream library. Most notably, it supports anonymous authentication which is required in certain contexts by Metasploit such as exploiting zerologon.

2024-04-29 15:52 UTC, compliance-r7 approved these changes
Only pom.xml has changed, approved!

2024-04-29 18:43 UTC, adfoster-r7 requested changes
Looks like there's some changes to make here to support the requirements :+1:

2024-08-06 13:32 UTC, closed without merging