Add MS-NRPC users enumeration module
rapid7/metasploit-framework pull request #19205
Opened 2024-05-27 19:47 UTC by sud0Ru

Adding a new module for enumerating domain users without authentication . The method leverages auth-level = 1 (No authentication) against the MS-NRPC (Netlogon) interface on domain controllers.

2024-05-29 14:08 UTC, smcintyre-r7 requested changes

2024-05-29 14:08 UTC, smcintyre-r7 commented on modules/auxiliary/gather/nrpc_enumusers.rb
Since this is really similar to the `auxiliary/scanner/smb/smb_enumusers` module, it would make sense to move this to `auxiliary/scanner/dcerpc/nrpc_enumusers` because they're both scanners and this is using the MS-NRPC interface directly over DCERPC.

2024-05-30 10:41 UTC, sud0Ru commented on modules/auxiliary/gather/nrpc_enumusers.rb
> +  class DsrGetDCNameEx2Request < BinData::Record
Thank you for the review. Indeed, you are right. I tried to approach it this way from the beginning (defining the call as you suggested), but I had problems with the data types. For example, inside the [call](https://github.com/rapid7/ruby_smb/blob/master/lib/ruby_smb/dcerpc/netlogon/netr_server_authenticate3_request.rb) that you suggested, according to Microsoft, the ```ComputerName``` should be ```wchar_t*```. When I checked the corresponding value in the Metasploit implementation, I found it defined as ```ndr_conf_var_wide_stringz```. When I tried this datatype with my call, it didn't work (the NDR level had a problem with pointing to the actual data). For this reason, I thought there was a problem defining the datatype itself in Metasploit. So, I decided to make the call work inside the module by passing most of the arguments as uint32 because they are NULL.

However, the datatype you mentioned, ```ndr_wide_stringz_ptr```, seems to work well.

I have some questions:

Where can I find some documentation about the data types you use for DCERPC? For example, I couldn't find anything related to ```NULL``` and ```GUID*```.
I believe if we implement the request, we should also implement the response, which requires some work because the return value will be this [struct](https://learn.microsoft.com/en-us/windows/win32/api/dsgetdc/ns-dsgetdc-domain_controller_infow). Is there a way to avoid that (because in my module I'm only getting the last four bytes that represent the flag)?

2024-05-30 10:51 UTC, sud0Ru commented on modules/auxiliary/gather/nrpc_enumusers.rb
> +  def bind_to_netlogon_service
Yes, I copied it from the Zerologon module. If I understood you correctly, you want me to use ```endpointmapper``` through named pipes as the RPC transport layer?

In my case, that's not possible because the whole idea behind this domain users enumeration is to avoid using ```IPC$``` for several reasons:

1- It can be monitored for null session activities.
2- In most systems nowadays, there is no null session (they have applied some policies), so I think the ``endpointmapper``` will not work over SMB named pipes.
By using TCP as the transport layer, we can bind without authentication and get the endpoint for the ```netlogon``` interface.

I hope I understand you correctly.

2024-05-30 12:36 UTC, smcintyre-r7 commented on modules/auxiliary/gather/nrpc_enumusers.rb
> +  class DsrGetDCNameEx2Request < BinData::Record
> Where can I find some documentation about the data types you use for DCERPC? For example, I couldn't find anything related to NULL and GUID*.

We document most things in YARD, but I'm sure there's many gaps. I don't think we have API docs published but you may be able to build them. I just look through the source when I need to find the types and check the names. Most of the primitives are going to be defined in [ndr.rb](https://github.com/rapid7/ruby_smb/blob/master/lib/ruby_smb/dcerpc/ndr.rb).

You're right about the types not lining up with the MSDN docs exactly as they're defined. This is a known limitation with the MSDN definitions that I don't know a way around. You'll see in RubySMB, that the requests and responses both refer to a single structure but all the fields labeled `[out]` are only present in the response. You kind of just have to try different NDR fields until they work.

> I believe if we implement the request, we should also implement the response, which requires some work because the return value will be this [struct](https://learn.microsoft.com/en-us/windows/win32/api/dsgetdc/ns-dsgetdc-domain_controller_infow). Is there a way to avoid that (because in my module I'm only getting the last four bytes that represent the flag)?

Having the response would be ideal but as you said because you're only checking the error status I think it's reasonable if you wanted to skip it. The important thing is you're not defining a `NetrServerAuthenticate3Response` structure that's incorrect or incomplete.

2024-06-06 09:55 UTC, sud0Ru commented on modules/auxiliary/gather/nrpc_enumusers.rb
> +  class DsrGetDCNameEx2Request < BinData::Record
According to our decision, I implemented the DCERPC request as we discussed and tried to implement the response, but encountered a problem. I have created a [PR ](https://github.com/rapid7/ruby_smb/pull/269) for this, aiming to merge the request and discuss the response. However, it has been almost a week, and there is still no feedback on the PR. I wanted to ask if this delay is normal or if there might be an issue.

2024-06-18 10:15 UTC, sud0Ru commented
@smcintyre-r7
I just noticed  that there is secret detection? what does that meaning and how can I pass this check?

2024-06-18 12:33 UTC, adfoster-r7 commented
That can be ignored :+1:

2024-06-18 13:06 UTC, smcintyre-r7 commented
> it would make sense to move this to `auxiliary/scanner/dcerpc/nrpc_enumusers`

I see it looks like you filled [this request](https://github.com/rapid7/metasploit-framework/pull/19205/files#r1618946260) but the old files are still present and should be removed.

It also looks like we bumped RubySMB already in e10d8e20f2243408016cd502ba3dbb82241181eb so [this comment](https://github.com/rapid7/metasploit-framework/pull/19205#issuecomment-2158383853) should no longer be necessary as long as it's not preventing you from testing your code.

So to get this finished up, I think we just need the extra files removed and the class variable [changed back](https://github.com/rapid7/metasploit-framework/pull/19205#pullrequestreview-2125458230) to an instance variable.

2024-06-18 15:00 UTC, sud0Ru commented on modules/auxiliary/scanner/dcerpc/nrpc_enumusers.rb
> +  @@dport = nil
Sorry some typo here while I was trying to replace some strings using some automation. Yeah you are totally right, it should be changed back.

2024-06-18 15:02 UTC, sud0Ru commented
@smcintyre-r7 
I delete that old files and changed back the variable, but I did it from the browser because don't have access to my machine at this period of time so hope everything is going okay

2024-06-24 22:20 UTC, smcintyre-r7 commented
@msjenkins-r7 test this please.

2024-06-24 22:51 UTC, smcintyre-r7 approved these changes
I pushed up two changes to finish this up. The first in commit [3794285](https://github.com/rapid7/metasploit-framework/pull/19205/commits/379428571551b316a1b04d7a0ff16002be22b0a4) bumps the version of RubySMB to pull in the changes with the new definition, and the second is 858a2f8 to fix the issues that Rubocop  had flaggged.

Thank you very much for your work on this, I know the DCERPC definitions aren't the easiest thing to write.

Testing output:
```
msf6 auxiliary(gather/ldap_query) > use nrpc_enumuser

Matching Modules
================

   #  Name                                     Disclosure Date  Rank    Check  Description
   -  ----                                     ---------------  ----    -----  -----------
   0  auxiliary/scanner/dcerpc/nrpc_enumusers  .                normal  No     MS-NRPC Domain Users Enumeration


Interact with a module by name or index. For example info 0, use 0 or use auxiliary/scanner/dcerpc/nrpc_enumusers

[*] Using auxiliary/scanner/dcerpc/nrpc_enumusers
msf6 auxiliary(scanner/dcerpc/nrpc_enumusers) > show options 

Module options (auxiliary/scanner/dcerpc/nrpc_enumusers):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   DB_ALL_USERS  false            no        Add all enumerated usernames to the database
   RHOSTS        3.22.14.197      yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT                          no        The netlogon RPC port (TCP)
   THREADS       1                yes       The number of concurrent threads (max one per host)
   USER_FILE     /tmp/users.txt   yes       Path to the file containing the list of usernames to enumerate


View the full module info with the info, or info -d command.

msf6 auxiliary(scanner/dcerpc/nrpc_enumusers) > run

[*] 3.22.14.197: - Connecting to the endpoint mapper service...
[*] 3.22.14.197: - Binding to 12345678-1234-abcd-ef00-01234567cffb:1.0@ncacn_ip_tcp:3.22.14.197[49664]...
[-] 3.22.14.197: - Jack does not exist
[-] 3.22.14.197: - Spencer does not exist
[+] 3.22.14.197: - aliddle exists -> DC: \\SRV-ADDS01.labs1collabu0.local
[+] 3.22.14.197: - Administrator exists -> DC: \\SRV-ADDS01.labs1collabu0.local
[-] 3.22.14.197: - Jackson does not exist
[-] 3.22.14.197: - Sophie does not exist
[-] 3.22.14.197: - Jake does not exist
[-] 3.22.14.197: - Murrey does not exist
[+] 3.22.14.197: - smcintyre exists -> DC: \\SRV-ADDS01.labs1collabu0.local
[-] 3.22.14.197: - Blythe does not exist
[*] 3.22.14.197: - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/dcerpc/nrpc_enumusers) > 
```

2024-06-24 22:53 UTC, merged

2024-06-24 23:06 UTC, smcintyre-r7 commented
# Release Notes

This adds a new module that can enumerate accounts on a target Active Directory Domain Controller without authenticating to it by issuing a DCERPC request and analyzing the returned error status.

2024-06-25 10:01 UTC, sud0Ru commented
Thank you for your help also :) it was pleasure to work with u

2024-06-25 10:23 UTC, adfoster-r7 commented
Nice work @sud0Ru ! 🎉