Corrected a mistaken CVE-ID in exploit references.
rapid7/metasploit-framework pull request #19253
Opened 2024-06-11 19:45 UTC by aaronjfeingold

This entry for exploit/unix/http/zivif_ipcheck_exec contained a mistaken reference to a CVE that does not exist.  The referenced CVE-ID is "CVE-2017-171069".  The corrected CVE is "CVE-2017-17105".

## Verification
- Note that the listed CVE does not exist: [https://nvd.nist.gov/vuln/detail/CVE-2017-171069](https://nvd.nist.gov/vuln/detail/CVE-2017-171069)
- Note that the corrected CVE does exist, and describes the vuln used by this exploit: [https://nvd.nist.gov/vuln/detail/CVE-2017-17105](https://nvd.nist.gov/vuln/detail/CVE-2017-17105)
- Observe that the correct CVE is mentioned in the exploit's description: "This module exploits a remote command execution vulnerability in Zivif webcams.  This is known to impact versions prior to and including v2.3.4.2103. Exploit was reported in CVE-2017-17105."

2024-06-11 21:12 UTC, smcintyre-r7 requested changes
Hey thanks for catching this discrepancy. The file you edited is generated automatically based on the module file. Would you mind please making your change here instead https://github.com/rapid7/metasploit-framework/blob/13fc954381594f6ca3879c9bd9866dad34810caa/modules/exploits/unix/http/zivif_ipcheck_exec.rb#L25?

If you don't, your change will be overwritten the next time the data is generated.

2024-06-11 21:36 UTC, aaronjfeingold commented
Thanks! I've made the same edit to the module file.

2024-06-11 21:41 UTC, aaronjfeingold commented
I can also remove the edit from the automatically generated file, if that's better.

2024-06-12 16:32 UTC, aaronjfeingold commented
@smcintyre-r7, I added the change to the file you mentioned.  Please let me know if there's anything else required here, or if it's good to go.

2024-06-18 19:18 UTC, aaronjfeingold commented
@smcintyre-r7 - Only the module file is being changed.  I removed my change to the auto-generated file.  Can we merge this now?  Thanks!

2024-06-18 19:53 UTC, merged

2024-06-18 19:57 UTC, smcintyre-r7 commented
# Release Notes
This fixes an incorrect CVE reference in the `exploit/unix/http/zivif_ipcheck_exec` module.