Add an `Auto` option to live_compile
rapid7/metasploit-framework pull request #19462
Opened 2024-09-14 18:49 UTC by jvoisin

Ass suggested by @zeroSteiner

2024-09-17 09:48 UTC, bcoles commented on lib/msf/core/post/linux/compile.rb
> +
Clobbering `datastore` values is generally frowned upon.

Can we do this with a `compiler` variable within this method instead?

I'm not aware of any existing scenario where the calling module (or anything else outside of `upload_and_compile`) will need to know what compiler was used.

2024-09-18 17:39 UTC, smcintyre-r7 requested changes
It looks like the `#live_compile?` method needs to be updated to check if the COMPILER option is Auto or one of the explicit options.

Right now, I'm getting this exception and the compiler isn't selected.


```
msf6 exploit(linux/local/af_packet_chocobo_root_priv_esc) > run

[*] Started reverse TCP handler on 192.168.250.134:4444 
[!] AutoCheck is disabled, proceeding with exploitation
[-] Exploit aborted due to failure: bad-config: Auto is not installed. Set COMPILE False to upload a pre-compiled executable.
[*] Exploit completed, but no session was created.
msf6 exploit(linux/local/af_packet_chocobo_root_priv_esc) > 
```

2024-09-18 20:02 UTC, smcintyre-r7 requested changes

2024-09-18 20:02 UTC, smcintyre-r7 commented on lib/msf/core/post/linux/compile.rb
> +      return true
Using the rails [`#present?`](https://apidock.com/rails/Object/present%3F) method will ensure that the value return from `#get_compiler` is a non empty string, it also accounts for nil.

```suggestion
    elsif datastore['COMPILER'] == 'Auto' && get_compiler.present?
      return true
```

2024-09-18 20:02 UTC, smcintyre-r7 commented on lib/msf/core/post/linux/compile.rb
> +    end
This is where we'd likely want to fail if `#get_compiler` can't return a compiler and the module ignored/didn't call `#live_compile?`.

2024-09-19 16:03 UTC, smcintyre-r7 approved these changes

2024-09-19 16:03 UTC, merged

2024-09-27 12:32 UTC, cdelafuente-r7 commented
# Release Notes

This adds an `Auto` option to the `Msf::Post::Linux::Compile` library. This enables automatic selection of the compiler according to what is available locally on the target system.