Allow setting the RPORT option for pipe_auditor
rapid7/metasploit-framework pull request #19475
Opened 2024-09-19 14:47 UTC by NtAlexio2

This PR adds the same pattern in #19163 to `pipe_auditor` and also fixes a bug in `smb_enumusers`, which causes invalid operation in case **Empty/Zero RPORT**.

2024-09-23 14:26 UTC, smcintyre-r7 requested changes
Changes look pretty good to me. I did notice however that the reporting block on lines 77-88 are not reporting the correct port now that we're handling multiple cases.

Also `@rport` will need to be set on L44 as well so it's populated in the reported note. Something like `@rport = datastore['RPORT'] = session.port` would work.

2024-09-24 20:37 UTC, NtAlexio2 commented on modules/auxiliary/scanner/smb/pipe_auditor.rb
>            break
applied ;)

2024-09-25 15:39 UTC, smcintyre-r7 requested changes
I found the following two issues:

1. The pipes aren't reported when using a session.
2. The `#report_pipes` function fails because `ip` isn't defined. It needs to be passed as a parameter.

2024-09-25 15:39 UTC, smcintyre-r7 commented on modules/auxiliary/scanner/smb/pipe_auditor.rb
>        pipes += check_pipes
```suggestion
      report_pipes(ip, check_pipes)
```

2024-09-25 15:39 UTC, smcintyre-r7 commented on modules/auxiliary/scanner/smb/pipe_auditor.rb
> +          report_pipes(pipes)
```suggestion
          report_pipes(ip, pipes)
```

2024-09-25 15:39 UTC, smcintyre-r7 commented on modules/auxiliary/scanner/smb/pipe_auditor.rb
> +  def report_pipes(pipes)
```suggestion
  def report_pipes(ip, pipes)
```

2024-09-25 22:28 UTC, NtAlexio2 commented
Thanks very much! updated

2024-09-26 13:19 UTC, smcintyre-r7 approved these changes
Changes look good to me now. I was able to test it with a session and without and everything is being reported properly. Thanks for updating this!

```
msf6 auxiliary(scanner/smb/pipe_auditor) > run SESSION=-1

[*] Using existing session 1
[+] Pipes: \netlogon, \lsarpc, \samr, \atsvc, \epmapper, \eventlog, \InitShutdown, \lsass, \LSM_API_service, \ntsvcs, \protected_storage, \router, \scerpc, \srvsvc, \W32TIME_ALT, \wkssvc
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/smb/pipe_auditor) > notes

Notes
=====

 Time                     Host            Service  Port  Protocol  Type         Data
 ----                     ----            -------  ----  --------  ----         ----
 2024-09-26 13:17:32 UTC  192.168.159.10  smb      445   tcp       Pipes Found  "Pipes: \\netlogon, \\lsarpc, \\samr, \\atsvc, \\epmapper, \\eventlog, \\InitShutdown, \\lsass, \\LSM_API_service, \\ntsvcs, \\protected_storage, \\router, \\scerpc, \\srvsvc, \\W32TIME_ALT, \\wkssvc"

msf6 auxiliary(scanner/smb/pipe_auditor) > notes -d

Notes
=====

 Time                     Host            Service  Port  Protocol  Type         Data
 ----                     ----            -------  ----  --------  ----         ----
 2024-09-26 13:17:32 UTC  192.168.159.10  smb      445   tcp       Pipes Found  "Pipes: \\netlogon, \\lsarpc, \\samr, \\atsvc, \\epmapper, \\eventlog, \\InitShutdown, \\lsass, \\LSM_API_service, \\ntsvcs, \\protected_storage, \\router, \\scerpc, \\srvsvc, \\W32TIME_ALT, \\wkssvc"

[*] Deleted 1 notes
msf6 auxiliary(scanner/smb/pipe_auditor) > run

[+] 192.168.159.10:445 - Pipes: \netlogon, \lsarpc, \samr
[*] 192.168.159.10: - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/smb/pipe_auditor) > notes

Notes
=====

 Time                     Host            Service  Port  Protocol  Type         Data
 ----                     ----            -------  ----  --------  ----         ----
 2024-09-26 13:18:33 UTC  192.168.159.10  smb      445   tcp       Pipes Found  "Pipes: \\netlogon, \\lsarpc, \\samr"

msf6 auxiliary(scanner/smb/pipe_auditor) > 
``

2024-09-26 13:19 UTC, merged

2024-09-26 13:20 UTC, smcintyre-r7 commented
# Release Notes
This refactors the `pipe_auditor` scanner module to allow an RPORT argument to be specified and refactors it to follow more recent patterns used by SMB modules.