Add Msf::Exploit::Remote::HTTP::Wordpress::SQLi
rapid7/metasploit-framework pull request #19497
Opened 2024-09-24 20:36 UTC by Chocapikk

Hello Metasploit Team,

This pull request introduces a new mixin, `Msf::Exploit::Remote::HTTP::Wordpress::SQLi`, which provides reusable SQL Injection (SQLi) helper functions specifically designed for WordPress modules in the Metasploit Framework. This idea was proposed by @jvoisin to simplify the development of exploit and auxiliary modules targeting WordPress vulnerabilities by avoiding code duplication and facilitating maintenance.

### Key Features:

- **Dynamic Table Prefix Detection**: The mixin includes a function `wordpress_sqli_identify_table_prefix` that dynamically identifies the WordPress database table prefix, whether it's the default `wp_` or a custom prefix. This ensures compatibility with WordPress installations using custom table prefixes.

- **Prefixed Function Names**: All functions in the mixin are prefixed with `wordpress_sqli_` to clearly indicate their association with the WordPress SQLi mixin and to prevent naming conflicts.

- **Helper Functions**:

  - **`wordpress_sqli_initialize(sqli)`**: Initializes the SQLi instance in the module, making it accessible within the mixin for executing SQL injection queries.

  - **`wordpress_sqli_create_user(username, password, email, table_prefix)`**: Creates a new WordPress user or updates an existing one in the `users` table. The function handles password hashing using MD5 for compatibility with older WordPress versions.

  - **`wordpress_sqli_grant_admin_privileges(username, table_prefix)`**: Grants administrator privileges to the specified user by creating or updating the appropriate entry in the `usermeta` table.

  - **`wordpress_sqli_get_users_credentials(table_prefix, count = 10)`**: Retrieves user login names and password hashes from the `users` table, using the detected table prefix. All functions are dynamic thanks to the prefix detection, allowing them to handle installations with custom prefixes seamlessly.

### Adapting Existing Modules:

I plan to adapt the modules (both exploit and auxiliary) I've created in the following pull requests to use this new mixin:

- https://github.com/rapid7/metasploit-framework/pull/19489
- https://github.com/rapid7/metasploit-framework/pull/19488
- https://github.com/rapid7/metasploit-framework/pull/19482
- https://github.com/rapid7/metasploit-framework/pull/19473

Integrating this mixin into these modules will prevent code duplication, facilitate maintenance, and improve consistency across modules exploiting WordPress vulnerabilities.

Thank you for your time, and please let me know if you have any questions or need further adjustments.

2024-09-24 22:22 UTC, jvoisin commented on lib/msf/core/exploit/remote/http/wordpress/sqli.rb
> +    end
I'm not super-duper convinced that it's better to have a `sqli` variable here, instead of passing it systematically to all functions. Why did you pick this design over a stateless one? Especially since the `table_prefix` is passed as argument.

2024-09-24 22:22 UTC, jvoisin commented on lib/msf/core/exploit/remote/http/wordpress/sqli.rb
> +      print_status("{WPSQLi} User '#{username}' created or updated successfully.")
I think this could be simplified via a [`REPLACE INTO`](https://dev.mysql.com/doc/refman/8.0/en/replace.html), or an `INSERT IGNORE INTO` if you want to keep the two steps separate. Since `DUAL` is an Oracle extension, and because WordPress is working on (finally) adding native sqlite support, it would be nice to keep the SQL as portable as possible.

See [this stackoverflow](https://stackoverflow.com/questions/1361340/how-can-i-do-insert-if-not-exists-in-mysql) question and [this blogost](https://sebhastian.com/mysql-insert-if-not-exists/) for inspiration.

2024-09-24 22:22 UTC, jvoisin commented on lib/msf/core/exploit/remote/http/wordpress/sqli.rb
> +      else
```suggestion
      if result == 0
        print_status("{WPSQLi} Retrieved default table prefix: 'wp_'")
        return 'wp_'
      end
```

so you can reduce nested indentation level

2024-09-24 22:22 UTC, jvoisin commented on lib/msf/core/exploit/remote/http/wordpress/sqli.rb
> +                  AND table_name LIKE '%\\_users'
Maybe use a more WordPress specific table name than `_users`, as I'm _sure_ various plugins might have something like `my_plugin_users` or whatnot.

2024-09-24 22:22 UTC, jvoisin commented on lib/msf/core/exploit/remote/http/wordpress/sqli.rb
> +        prefix << '_' unless prefix.end_with?('_')
Are those two lines needed?

2024-09-24 22:22 UTC, jvoisin commented on lib/msf/core/exploit/remote/http/wordpress/sqli.rb
> +    # @param ip [String] The target IP address
I think that the target ip can be obtained from `datastore[HOST]` or something like this, no?

2024-09-24 22:49 UTC, Chocapikk commented on lib/msf/core/exploit/remote/http/wordpress/sqli.rb
> +    end
I've decided to initialise `@sqli` in this way so that we don't need to use it as an argument when using each function, but yes, I can also initialise the prefix directly in initialize, which will make it easier to use the functions without having to pass table_prefix in each function.

2024-09-24 23:01 UTC, Chocapikk commented on lib/msf/core/exploit/remote/http/wordpress/sqli.rb
> +                  AND table_name LIKE '%\\_users'
I'll have a look, but in fact here I'm checking that the table contains the `user_login` and `user_pass` columns, so we're supposed to get the right table no matter what other tables other plugins may add.

2024-09-25 11:21 UTC, jvoisin commented on lib/msf/core/exploit/remote/http/wordpress/sqli.rb
> +      @sqli.raw_run_sql(query.strip.gsub(/\s+/, ' '))
```suggestion
      @sqli.raw_run_sql(query.strip.gsub(/\n/, ' ').gsub(/\s+/, ' '))
```

2024-09-25 11:21 UTC, jvoisin commented on lib/msf/core/exploit/remote/http/wordpress/sqli.rb
> +      if result == 0
```suggestion
      indicator = rand()
      default_prefix_check = "SELECT #{indicator} FROM information_schema.tables WHERE table_name = 'wp_users'"
      result = @sqli.run_sql(default_prefix_check)&.to_i

      if result == indicator
```

2024-09-25 14:57 UTC, Chocapikk commented on lib/msf/core/exploit/remote/http/wordpress/sqli.rb
> +      @sqli.raw_run_sql(query.strip.gsub(/\s+/, ' '))
`query.strip.gsub(/\s+/, ' ')` is already replacing `\n`

2024-09-25 19:37 UTC, jvoisin approved these changes

2024-10-03 13:50 UTC, cgranleese-r7 commented on lib/msf/core/exploit/remote/http/wordpress/sqli.rb
> +      @sqli.raw_run_sql(admin_query.strip.gsub(/\s+/, ' '))
Does there need to be a check here? From a quick glance at the `raw_run_sql` method I think we may want something here maybe.

2024-10-03 21:06 UTC, jvoisin approved these changes

2024-10-08 14:37 UTC, dledda-r7 requested changes
Hello @Chocapikk,
I'm leaving here couple of suggestions to make the mixin less verbose by default.

2024-10-09 15:12 UTC, dledda-r7 commented
I think you missed this https://github.com/rapid7/metasploit-framework/pull/19497#discussion_r1791773443

2024-10-09 15:23 UTC, Chocapikk commented
> I think you missed this [#19497 (comment)](https://github.com/rapid7/metasploit-framework/pull/19497#discussion_r1791773443)

Oh yes thank you I actually forgot

2024-10-09 15:28 UTC, dledda-r7 commented
> > I think you missed this [#19497 (comment)](https://github.com/rapid7/metasploit-framework/pull/19497#discussion_r1791773443)
> 
> Oh yes thank you I actually forgot

Nice, thank you, I saw the CI didn't passed but doesn't look like a module issue, I'll re-run it if there are further errors.

2024-10-14 11:13 UTC, merged

2024-10-14 12:59 UTC, dledda-r7 commented
# Release Notes
This adds an helper library for the development of Wordpress SQLi modules.