Reline behind a feature flag
rapid7/metasploit-framework pull request #19559
Opened 2024-10-15 14:58 UTC by sjanusz-r7

This PR is a continuation of https://github.com/rapid7/metasploit-framework/pull/19397

This PR adds in the usage of the Reline library behind a feature flag.

Reline currently has some bugs/issues/inconsistencies compared to Readline. These are tracked as issue reports on Reline's GitHub.
These include:
- Using IO's object encoding to not have to set the encoding globally
- Tab completion append character only being appended when no more completions exist
- Being able to change the completion append character in the completion proc (monkeypatched)
- being able to perform multiple tab completions in a row with different values

We are moving away from Readline in favor if a pure Ruby implementation.
We are having to remove Readline on newer Windows 11 hosts due to an issue that Reline also encountered (and fixed since), where the console output handle would sometimes be incorrect, likely after calling popen, thus calls to console APIs such as `SetConsoleCursorPosition` would fail. A workaround is to periodically refresh the handle variable by calling `handle = GetStdHandle.call(-11) // for STDOUT`.

## Verification

- WIP

2024-10-23 09:12 UTC, adfoster-r7 commented on tools/exploit/nasm_shell.rb
> +require 'reline'
I think these are redundant if it's handled by msfenv 👀

2024-11-20 13:59 UTC, sjanusz-r7 commented on lib/msf/base/sessions/command_shell.rb
> +      framework.history_manager.with_context(name: :irb, input_library: :reline) do
IRB always uses Reline, unless we specify `@CONF[:USE_SINGLELINE] = true` when setting up the IRB shell, which we don't currently do here: https://github.com/rapid7/metasploit-framework/blob/e6615d3a747ca07ef70873230f31f71465610392/lib/rex/ui/text/irb_shell.rb#L29 I'll add in a helper here to check for this flag and default to `:reline` if `!use_singleline` or `use_multiline` as they are xor'd.

2024-11-20 17:24 UTC, sjanusz-r7 commented on lib/rex/ui/text/irb_shell.rb
> +      IRB.conf[:USE_MULTILINE] = true
I am using this to make sure that IRB uses Reline, allowing us to set `input_library: :reline` in calls to `with_context` when interacting with the history manager.

2024-12-03 12:50 UTC, adfoster-r7 commented
```
Rex::Post::Meterpreter::Ui::Console::CommandDispatcher::Core ..........F.........

  4) Rex::Post::Meterpreter::Ui::Console::CommandDispatcher::Core behaves like session command dispatcher Core commands #cmd_irb runs an irb shell instance
     Failure/Error: raise NoMethodError, msg

     NoMethodError:
       Method 'autocompletion' not found in Module
     Shared Example Group: "session command dispatcher" called from ./spec/lib/rex/post/meterpreter/ui/console/command_dispatcher/core_spec.rb:24
     # ./lib/msf/ui/console/msf_readline.rb:26:in `method_missing'
     # ./lib/msf/ui/console/msf_readline.rb:34:in `cache_current_config'
     # ./lib/msf/ui/console/command_dispatcher/session.rb:99:in `cmd_irb'
     # ./spec/support/shared/examples/msf/ui/console/command_dispatcher/session.rb:56:in `block (4 levels) in <top (required)>'
Rex::Post::PostgreSQL::Ui::Console::CommandDispatcher::Core .....F..............

  5) Rex::Post::PostgreSQL::Ui::Console::CommandDispatcher::Core behaves like session command dispatcher Core commands #cmd_irb runs an irb shell instance
     Failure/Error: raise NoMethodError, msg

     NoMethodError:
       Method 'autocompletion' not found in Module
     Shared Example Group: "session command dispatcher" called from ./spec/lib/rex/post/postgresql/ui/console/command_dispatcher/core_spec.rb:32
     # ./lib/msf/ui/console/msf_readline.rb:26:in `method_missing'
     # ./lib/msf/ui/console/msf_readline.rb:34:in `cache_current_config'
     # ./lib/msf/ui/console/command_dispatcher/session.rb:99:in `cmd_irb'
     # ./spec/support/shared/examples/msf/ui/console/command_dispatcher/session.rb:56:in `block (4 levels) in <top (required)>'


```

2025-02-26 19:53 UTC, smcintyre-r7 requested changes
It looks like this is also an outstanding item: https://github.com/rapid7/metasploit-framework/pull/19559/files#r1850369059

Verification steps would also be helpful to post. If this isn't a priority anymore, we can go ahead and attic it.

2025-02-27 10:08 UTC, closed without merging