Renames LDAP datastore options
rapid7/metasploit-framework pull request #19606
Opened 2024-10-31 11:49 UTC by cgranleese-r7

> [!NOTE]
Currently working on fixing a failure in the acceptance tests for one module.
This PR is required for another PR with Pro - https://github.com/rapid7/pro/pull/3808

This PR renames the LDAP datastore options to facilitate some being made in Pro as part of the following [PR](https://github.com/rapid7/pro/pull/3808). 

The reason this was required was due to adding the previous LDAP datastore values into the configuration hash within Pro in the following file - `ui/app/models/scan_task.rb`, this would result in duplicate hash keys as previous LDAP used:
- USERNAME
- PASSWORD
- DOMAIN

So I decided to align with how SMB was handling its datastore by updating them to be:
- LDAPUsername
- LDAPPassword
- LDAPDomain

## Verification
- [ ] Run `auxiliary/scanner/ldap/ldap_login` against an ldap server to get a session (an example of running an ldap container can be found in the ldap acceptance tests here https://github.com/rapid7/metasploit-framework/blob/33ffc14e6b58de95fa90f28add871cbbb2bc7fd4/.github/workflows/ldap_acceptance.yml#L67-L71 
- [ ] Run `SPEC_OPTS='--tag acceptance' SPEC_HELPER_LOAD_METASPLOIT=false bundle exec rspec ./spec/acceptance/ldap_spec.rb` and ensure those pass locally.
- [ ] Start `msfconsole`
- [ ] Test `ldap_login` module
- [ ] Code changes are sane

2024-10-31 14:54 UTC, sjanusz-r7 commented on lib/msf/core/optional_session/ldap.rb
> +      REQUIRED_OPTIONS = %w[RHOSTS RPORT LDAPUsername LDAPPassword THREADS]
Following the convention from PR: https://github.com/rapid7/metasploit-framework/pull/19551
```suggestion
      REQUIRED_OPTIONS = %w[RHOSTS RPORT THREADS]
```

2025-02-26 20:24 UTC, smcintyre-r7 requested changes

2025-02-26 20:24 UTC, smcintyre-r7 commented on lib/msf/core/exploit/remote/ldap.rb
> +        Msf::OptString.new('LDAPPassword', [false, 'The password to authenticate with'], aliases: ['BIND_PW'])
I think to match the SMB pattern, we should be adding `fallbacks` for each:

```suggestion
        Msf::OptString.new('LDAPDomain', [false, 'The domain to authenticate to'], fallbacks: ['DOMAIN']),
        Msf::OptString.new('LDAPUsername', [false, 'The username to authenticate with'], aliases: ['BIND_DN'], fallbacks: ['USERNAME']),
        Msf::OptString.new('LDAPPassword', [false, 'The password to authenticate with'], aliases: ['BIND_PW'], fallbacks: ['PASSWORD'])
```

Reading through the docs here, I'm not 100% sure if it should be `fallbacks` or `aliases` because it seems like this case is both renaming an option but also a "specialized names such as {SMBUser}".

https://github.com/rapid7/metasploit-framework/blob/5bb99d120f96362cf58bac222870d0dd2711d404/lib/msf/core/opt_base.rb#L207-L226

Either way, we should ensure that `USERNAME` / `PASSWORD` / `DOMAIN` usage continues to work as intended.

This quick test implies that the `shadow_credentials` module is no longer working with the old datastore options as it used to. It's also crashing when the credentials are wrong, but that's out of scope for this.

```
metasploit-framework (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > set USERNAME smcintyre 
USERNAME => smcintyre
metasploit-framework (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > set PASSWORD Password1!
PASSWORD => Password1!
metasploit-framework (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > set DOMAIN msflab.local
DOMAIN => msflab.local
metasploit-framework (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > list
[*] Running module against 192.168.159.10

[+] Successfully bound to the LDAP server!
[*] Discovering base DN automatically
[*] 192.168.159.10:389 Discovered base DN: DC=msflab,DC=local
[-] Auxiliary failed: NoMethodError undefined method `first' for nil:NilClass
[-] Call stack:
[-]   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/admin/ldap/shadow_credentials.rb:82:in `ldap_get'
[-]   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/admin/ldap/shadow_credentials.rb:128:in `block in run'
[-]   /home/smcintyre/.rvm/gems/ruby-3.2.5@metasploit-framework/gems/net-ldap-0.19.0/lib/net/ldap.rb:646:in `block in open'
[-]   /home/smcintyre/.rvm/gems/ruby-3.2.5@metasploit-framework/gems/net-ldap-0.19.0/lib/net/ldap.rb:718:in `block in open'
[-]   /home/smcintyre/.rvm/gems/ruby-3.2.5@metasploit-framework/gems/net-ldap-0.19.0/lib/net/ldap/instrumentation.rb:19:in `instrument'
[-]   /home/smcintyre/.rvm/gems/ruby-3.2.5@metasploit-framework/gems/net-ldap-0.19.0/lib/net/ldap.rb:713:in `open'
[-]   /home/smcintyre/.rvm/gems/ruby-3.2.5@metasploit-framework/gems/net-ldap-0.19.0/lib/net/ldap.rb:646:in `open'
[-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/core/exploit/remote/ldap.rb:146:in `ldap_open'
[-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/core/optional_session/ldap.rb:53:in `ldap_connect'
[-]   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/admin/ldap/shadow_credentials.rb:110:in `run'
[*] Auxiliary module execution completed
metasploit-framework (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > set LDAPUsername smcintyre
LDAPUsername => smcintyre
metasploit-framework (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > set LDAPPassword Password1!
LDAPPassword => Password1!
metasploit-framework (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > set LDAPDomain msflab.local
LDAPDomain => msflab.local
metasploit-framework (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > run
[*] Running module against 192.168.159.10

[+] Successfully bound to the LDAP server!
[*] Discovering base DN automatically
[*] 192.168.159.10:389 Discovered base DN: DC=msflab,DC=local
[*] Existing credentials:
[*] DeviceID: 82727040-c13a-4ebe-a294-f97e32bcc740 - Created 2025-02-26 09:25:11 -0500
[*] DeviceID: d930e752-fdf1-366b-7581-e203c587cb1a - Created 2025-02-26 09:27:59 -0500
[*] DeviceID: 35028985-0805-aea1-278f-d05df9f9f4f6 - Created 2025-02-26 09:27:19 -0500
[*] Auxiliary module execution completed
metasploit-framework (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) >
```

2025-02-27 15:36 UTC, adfoster-r7 commented on lib/msf/core/exploit/remote/ldap.rb
> +        Msf::OptString.new('LDAPPassword', [false, 'The password to authenticate with'], aliases: ['BIND_PW'])
I think both need added; will have to double check 👀

2025-03-03 10:51 UTC, cgranleese-r7 commented on lib/msf/core/exploit/remote/ldap.rb
> +        Msf::OptString.new('LDAPPassword', [false, 'The password to authenticate with'], aliases: ['BIND_PW'])
Thanks for taking a look @smcintyre-r7. I went ahead and added both. If @adfoster-r7 comes back with something different I can reshuffling 👍

2025-03-04 18:34 UTC, smcintyre-r7 commented
With the fallbacks and aliases in place, I'm getting errors when running `show options` and `run` about the stack level being too deep. I think we need to remove the `alias`. With just the fallbacks in place things are working as I'd expect. The user can specify `USERNAME` and it's populated to `LDAPUsername`, and matches the pattern used by SMB.

It also looks like the LDAP acceptance tests need to be fixed. It's possible that fixing the stack level issue by removing the alias could do the trick though.

2025-03-05 09:49 UTC, cgranleese-r7 commented
Seems the LDAP tests are still failing, will need to take a look at this locally and see what the issue is.

2025-03-05 12:28 UTC, cgranleese-r7 commented
Strangely these are all passing for me locally 😕 

```
metasploit-framework on  rename-ldap-datastore-values [$] via  desktop-linux via 🐘 v8.3.13 via  v3.13.0 via  v3.1.5 via ⍱
❯ SPEC_OPTS='--tag acceptance' SPEC_HELPER_LOAD_METASPLOIT=false bundle exec rspec ./spec/acceptance/ldap_spec.rb
Run options: include {:focus=>true, :acceptance=>true}

Randomized with seed 2770
LDAP modules [read] Overriding user environment variable 'OPENSSL_CONF' to enable legacy functions.
...
[read] msf6 auxiliary(gather/ldap_hashdump) >
[write] jobs -K
[read]
[read] [*] Killing all sessions...
[read] [*] 127.0.0.1 - LDAP session 6 closed.
[read] msf6 auxiliary(gather/ldap_hashdump) >
E, [2025-03-05T12:28:06.088500 #43635] ERROR -- : Can't add attachment, no test, step or fixture is running
E, [2025-03-05T12:28:06.088570 #43635] ERROR -- : Can't add attachment, no test, step or fixture is running
E, [2025-03-05T12:28:06.088652 #43635] ERROR -- : Can't add attachment, no test, step or fixture is running
.[write] sessions -K
[read]
[read] Stopping all jobs...
[read] msf6 auxiliary(gather/ldap_hashdump) >
[write] jobs -K
[read]
[read] [*] Killing all sessions...
[read] msf6 auxiliary(gather/ldap_hashdump) >


Top 10 slowest examples (11.92 seconds, 55.2% of total time):
  LDAP modules osx/ldap auxiliary/gather/ldap_hashdump when targeting a session osx/ldap session opens and passes the "auxiliary/gather/ldap_hashdump" tests
    3.53 seconds ./spec/acceptance/ldap_spec.rb:356
  LDAP modules osx/ldap auxiliary/gather/ldap_hashdump when targeting an rhost osx/ldap rhost opens and passes the "auxiliary/gather/ldap_hashdump" tests
    3.52 seconds ./spec/acceptance/ldap_spec.rb:383
  LDAP modules osx/ldap auxiliary/gather/ldap_query when targeting a session osx/ldap session opens and passes the "auxiliary/gather/ldap_query" tests
    1.48 seconds ./spec/acceptance/ldap_spec.rb:356
  LDAP modules osx/ldap auxiliary/gather/ldap_query when targeting an rhost osx/ldap rhost opens and passes the "auxiliary/gather/ldap_query" tests
    0.96754 seconds ./spec/acceptance/ldap_spec.rb:383
  LDAP modules osx/ldap auxiliary/gather/ldap_query when targeting a session osx/ldap session opens and passes the "auxiliary/gather/ldap_query" tests
    0.70308 seconds ./spec/acceptance/ldap_spec.rb:356
  LDAP modules osx/ldap auxiliary/admin/ldap/shadow_credentials when targeting a session osx/ldap session opens and passes the "auxiliary/admin/ldap/shadow_credentials" tests
    0.47133 seconds ./spec/acceptance/ldap_spec.rb:356
  LDAP modules osx/ldap auxiliary/gather/ldap_esc_vulnerable_cert_finder when targeting a session osx/ldap session opens and passes the "auxiliary/gather/ldap_esc_vulnerable_cert_finder" tests
    0.44535 seconds ./spec/acceptance/ldap_spec.rb:356
  LDAP modules osx/ldap auxiliary/admin/ldap/rbcd when targeting a session osx/ldap session opens and passes the "auxiliary/admin/ldap/rbcd" tests
    0.43514 seconds ./spec/acceptance/ldap_spec.rb:356
  LDAP modules osx/ldap auxiliary/gather/ldap_query when targeting an rhost osx/ldap rhost opens and passes the "auxiliary/gather/ldap_query" tests
    0.3077 seconds ./spec/acceptance/ldap_spec.rb:383
  LDAP modules osx/ldap auxiliary/admin/ldap/rbcd when targeting an rhost osx/ldap rhost opens and passes the "auxiliary/admin/ldap/rbcd" tests
    0.06801 seconds ./spec/acceptance/ldap_spec.rb:383

Finished in 21.58 seconds (files took 3.32 seconds to load)
12 examples, 0 failures

Randomized with seed 2770

metasploit-framework on  rename-ldap-datastore-values [$] via  desktop-linux via 🐘 v8.3.13 via  v3.13.0 via  v3.1.5 via ⍱ took 26s
❯
```

2025-03-27 20:25 UTC, smcintyre-r7 approved these changes
Thanks for that last round of changes Christopher! Things are working as I'd expect them to now and I see you were also able to fix the tests. Thanks for your work on this, I'll go ahead and get it landed.

```
metasploit-framework.pr (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > show options 

Module options (auxiliary/admin/ldap/shadow_credentials):

   Name         Current Setting  Required  Description
   ----         ---------------  --------  -----------
   SSL          false            no        Enable SSL on the LDAP connection
   TARGET_USER                   yes       The target to write to


   When ACTION is REMOVE:

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   DEVICE_ID                   no        The specific certificate ID to operate on


   Used when connecting via an existing SESSION:

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SESSION                   no        The session to run this module on


   Used when making a new connection via RHOSTS:

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   LDAPDomain                     no        The domain to authenticate to
   LDAPPassword  Password1!       no        The password to authenticate with
   LDAPUsername  basic_user       no        The username to authenticate with
   RHOSTS                         no        The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT         389              no        The target port


Auxiliary action:

   Name  Description
   ----  -----------
   LIST  Read all credentials associated with the account



View the full module info with the info, or info -d command.

metasploit-framework.pr (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > set DOMAIN ad.pro.local
DOMAIN => ad.pro.local
metasploit-framework.pr (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > set RHOSTS 10.140.10.254
RHOSTS => 10.140.10.254
metasploit-framework.pr (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > set TARGET_USER basic_user
TARGET_USER => basic_user
metasploit-framework.pr (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > list
[*] Running module against 10.140.10.254
[-] Auxiliary aborted due to failure: no-access: Invalid credentials provided!
[*] Auxiliary module execution completed
metasploit-framework.pr (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > set PASSWORD vagrant
PASSWORD => vagrant
metasploit-framework.pr (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > list
[*] Running module against 10.140.10.254
[+] Successfully bound to the LDAP server!
[*] Discovering base DN automatically
[*] 10.140.10.254:389 Discovered base DN: DC=ad,DC=pro,DC=local
[*] The msDS-KeyCredentialLink field is empty.
[*] Auxiliary module execution completed
metasploit-framework.pr (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > set LDAPPassword ThisIsWrong
LDAPPassword => ThisIsWrong
metasploit-framework.pr (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > run
[*] Running module against 10.140.10.254
[-] Auxiliary aborted due to failure: no-access: Invalid credentials provided!
[*] Auxiliary module execution completed
metasploit-framework.pr (S:0 J:0) auxiliary(admin/ldap/shadow_credentials) > 
```

2025-03-27 20:26 UTC, merged

2025-03-27 21:02 UTC, smcintyre-r7 commented
# Release Notes
This updates the LDAP modules to use datastore options for authentication that are prefixed with `LDAP`, allowing them to be used as larger workflows that merge datastore options for multiple protocols.