WIP: Remove hardcoded blockapi hashes and ASM Blockapi
rapid7/metasploit-framework pull request #19609
Opened 2024-11-01 10:07 UTC by dledda-r7

Work in progress PR, removing hardcoded block-api hashes and asm block api.

2024-11-19 17:01 UTC, dledda-r7 commented on modules/payloads/singles/windows/dns_txt_query_exec.rb
Not able to do `generate` here

2024-11-21 18:55 UTC, dledda-r7 commented
Re-Drafting as I need to work on some more hard-coded thing which I hoped I would be able to bypass.

2024-11-27 21:04 UTC, smcintyre-r7 requested changes
I think you missed:

* https://github.com/rapid7/metasploit-framework/blob/07ce1aae7758e7aa5604c1c81ae4fd963d216b0d/lib/msf/core/payload/windows/reverse_tcp_dns.rb#L145
* https://github.com/rapid7/metasploit-framework/blob/07ce1aae7758e7aa5604c1c81ae4fd963d216b0d/modules/payloads/stagers/windows/reverse_https_proxy.rb#L137

Generally speaking in the future when you edit a line like the following, it would clean things up a bit to remove the comment since it's now redundant with the source code. I wouldn't bother going back and deleting all of these comments, but as you continue to make changes, and it's convenient, I'd drop them.

```
push #{Rex::Text.block_api_hash("kernel32.dll", "VirtualAllocEx")} ; hash( "kernel32.dll", "VirtualAllocEx" )
``

2024-11-28 11:56 UTC, dledda-r7 commented
> I think you missed:
> 
> * https://github.com/rapid7/metasploit-framework/blob/07ce1aae7758e7aa5604c1c81ae4fd963d216b0d/lib/msf/core/payload/windows/reverse_tcp_dns.rb#L145
> * https://github.com/rapid7/metasploit-framework/blob/07ce1aae7758e7aa5604c1c81ae4fd963d216b0d/modules/payloads/stagers/windows/reverse_https_proxy.rb#L137
> 
> Generally speaking in the future when you edit a line like the following, it would clean things up a bit to remove the comment since it's now redundant with the source code. I wouldn't bother going back and deleting all of these comments, but as you continue to make changes, and it's convenient, I'd drop them.
> 
> ```
> push #{Rex::Text.block_api_hash("kernel32.dll", "VirtualAllocEx")} ; hash( "kernel32.dll", "VirtualAllocEx" )
> ```
> 
> Also, would you mind making a list of modules that have had non-trivial changes that should be tested? Any module that was previously hard coding the block API should probably get a quick test to ensure that it's still working. Adding them as checklist items to the PR description would be great. I can get started going through those next week after the two I found that were missing updates are addressed as well.

Good catch with the `reverse_tcp_dns`, I think the `reverse_https_proxy` need to be rewritten. working on that.

2024-11-29 13:02 UTC, dledda-r7 commented
So I re-wrote the `reverse_https_proxy`. but something in framework changed and we are not getting the second stage anymore, we are getting HTML with *It Works* so the payload is allocating that and jumping into it. Probably something some changes in the `ReverseHttp` handler...

2024-12-04 10:07 UTC, dledda-r7 commented
> So I've had a hard time testing some of these:
> 
> * modules/payloads/singles/windows/dns_txt_query_exec.rb
> * modules/payloads/stagers/windows/reverse_hop_http.rb
> 
> For modules/payloads/stagers/windows/reverse_hop_http.rb, I've been following the steps in the demo from the description of #6227. I've gone back as far as using Metasploit v4.14 with the docker image `php:5.6.40-apache`. I see in the PHP logs that requests are coming in and that an HTTP 200 response is issued but no session is created. Trying to use Metasploit v4.13 is being problematic because the dependencies won't compile in the Ruby docker container.
> 
> My question is: have you tested these two payloads and confirmed they're working? It wouldn't surprise me if `reverse_hop_http` hasn't been working since the encryption added in Metasploit 6.0 which is why I tried going back in time to test but without luck.

These two I haven't tested them dynamically. since I simply replaced the block-api-asm to use the randomized one and replaced the hardcoded hashes. I generated the shellcode and opened with binja

2024-12-04 10:11 UTC, dledda-r7 commented
> > So I've had a hard time testing some of these:
> > 
> > * modules/payloads/singles/windows/dns_txt_query_exec.rb
> > * modules/payloads/stagers/windows/reverse_hop_http.rb
> > 
> > For modules/payloads/stagers/windows/reverse_hop_http.rb, I've been following the steps in the demo from the description of #6227. I've gone back as far as using Metasploit v4.14 with the docker image `php:5.6.40-apache`. I see in the PHP logs that requests are coming in and that an HTTP 200 response is issued but no session is created. Trying to use Metasploit v4.13 is being problematic because the dependencies won't compile in the Ruby docker container.
> > My question is: have you tested these two payloads and confirmed they're working? It wouldn't surprise me if `reverse_hop_http` hasn't been working since the encryption added in Metasploit 6.0 which is why I tried going back in time to test but without luck.
> 
> These two I haven't tested them dynamically. since I simply replaced the block-api-asm to use the randomized one and replaced the hardcoded hashes. I generated the shellcode and opened with binja.

I don't think the encryption is the issue here. the encryption is completely handled by the `metsrv` after it is reflectevly-loaded(TM) by the stager inside the process.

If the module was not working even before my modification, make sense to drop the support of it?

2024-12-05 21:30 UTC, smcintyre-r7 approved these changes

2024-12-05 21:31 UTC, smcintyre-r7 commented
`modules/payloads/singles/windows/dns_txt_query_exec.rb` is just fine, it wasn't working because I split my shellcode into 256 byte chunks instead of 255. That broke the parsing because there were multiple strings in the response so the shellcode crashed. Once I fixed that error, everything was working just fine.

2024-12-06 17:43 UTC, merged