zoomeye search
rapid7/metasploit-framework pull request #7460
Opened 2016-10-19 03:56 UTC by nixawk

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use auxiliary/gather/zoomeye_search`
- [ ] `set ZOOMEYE_APIKEY demo_zoomeye_api`
- [ ] `set MAXPAGE 3`
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not

```
msf auxiliary(zoomeye_search) > show options

Module options (auxiliary/gather/zoomeye_search):

   Name            Current Setting   Required  Description
   ----            ---------------   --------  -----------
   MAXPAGE         3                 yes       Max amount of pages to collect
   Proxies                           no        A proxy chain of format type:host:port[,type:host:port][...]
   RESOURCE        web               yes       ZoomEye Resource Type (Accepted: host, web)
   ZOOMEYE_APIKEY  demo_zoomeye_api  yes       The ZoomEye API Key
   ZOOMEYE_DORK    apache            yes       The ZoomEye Dock
```

## Host Search

```
msf auxiliary(zoomeye_search) > set RESOURCE host
RESOURCE => host
msf auxiliary(zoomeye_search) > set ZOOMEYE_DORK apache
ZOOMEYE_DORK => apache
msf auxiliary(zoomeye_search) > run

[*] ZoomEye host Search: apache - page: 1
[+] Host: 50.22.36.55 ,PORT: 21
[+] Host: 50.200.127.124 ,PORT: 21
[+] Host: 50.206.79.73 ,PORT: 22
[+] Host: 50.151.68.228 ,PORT: 22
[+] Host: 50.143.188.35 ,PORT: 22
[+] Host: 50.87.254.17 ,PORT: 25
[+] Host: 50.203.236.80 ,PORT: 25
[+] Host: 50.87.254.15 ,PORT: 25
[+] Host: 50.87.254.18 ,PORT: 25
[+] Host: 50.78.222.246 ,PORT: 25
[*] ZoomEye host Search: apache - page: 2
[+] Host: 50.22.22.126 ,PORT: 25
[+] Host: 50.87.254.19 ,PORT: 25
[+] Host: 50.62.127.163 ,PORT: 80
[+] Host: 50.87.154.60 ,PORT: 80
[+] Host: 50.87.174.171 ,PORT: 80
[+] Host: 50.115.239.44 ,PORT: 80
[+] Host: 50.87.148.171 ,PORT: 80
[+] Host: 50.150.77.186 ,PORT: 80
[+] Host: 50.56.241.72 ,PORT: 80
[+] Host: 50.244.61.226 ,PORT: 80
[*] ZoomEye host Search: apache - page: 3
[+] Host: 50.244.61.226 ,PORT: 80
[+] Host: 50.115.163.44 ,PORT: 80
[+] Host: 50.115.238.81 ,PORT: 80
[+] Host: 50.62.224.199 ,PORT: 80
[+] Host: 50.112.185.249 ,PORT: 80
[+] Host: 50.87.139.34 ,PORT: 80
[+] Host: 50.22.190.202 ,PORT: 80
[+] Host: 50.116.73.111 ,PORT: 80
[+] Host: 50.28.29.124 ,PORT: 80
[+] Host: 50.87.133.93 ,PORT: 80
[*] Auxiliary module execution completed
```

## Web Search

```
msf auxiliary(zoomeye_search) > set RESOURCE web
RESOURCE => web
msf auxiliary(zoomeye_search) > set ZOOMEYE_DORK apache
ZOOMEYE_DORK => apache
msf auxiliary(zoomeye_search) > run

[*] ZoomEye web Search: apache - page: 1
[+] Host: 81.91.92.95, Domains: ["www.hardened-php.net", "developers.slashdot.org", "wiki.phpmyadmin.net", "jigsaw.w3.org", "bugzilla.mozilla.org", "www.gnu.org", "www.fpdf.org", "php.net", "en.wikipedia.org", "www.wikipedia.org", "www.acko.net", "pecl.php.net", "www.phpmyadmin.net", "phpmyadmin.net", "pear.php.net", "www.ozerov.de", "www.php.net", "dd.cron.ru", "github.com", "sourceforge.net", "sf.net", "bugs.mysql.com", "bugs.php.net", "www.ietf.org", "httpd.apache.org", "validator.w3.org", "lists.sourceforge.net", "dev.mysql.com", "blobstreaming.org", "developer.mimer.com", "www.tcpdf.org", "l10n.cihar.com"]
[+] Host: 211.144.132.141, Domains: []
[+] Host: 103.224.212.247, Domains: []
[+] Host: 103.35.148.58, Domains: []
[+] Host: 106.187.99.174, Domains: []
[+] Host: 173.236.179.144, Domains: ["alistapart.com", "www.heydonworks.com", "medium.com", "twitter.com", "adamsilver.io", "maintainablecss.com", "xkcd.com"]
[+] Host: 106.187.99.174, Domains: []
[+] Host: 123.196.121.6, Domains: []
[+] Host: 219.234.85.223, Domains: []
[+] Host: 106.187.51.202, Domains: []
[*] ZoomEye web Search: apache - page: 2
[+] Host: 96.47.69.62, Domains: []
[+] Host: 96.47.69.62, Domains: []
[+] Host: 96.47.69.62, Domains: []
[+] Host: 96.47.69.62, Domains: []
[+] Host: 96.47.69.62, Domains: []
[+] Host: 122.10.96.62, Domains: ["wpa.qq.com"]
[+] Host: 96.47.69.62, Domains: []
[+] Host: 96.47.69.62, Domains: []
[+] Host: 96.47.69.62, Domains: []
[+] Host: 96.47.69.62, Domains: []
[*] ZoomEye web Search: apache - page: 3
[+] Host: 217.74.66.167, Domains: []
[+] Host: 125.209.214.79, Domains: []
[+] Host: 64.71.33.37, Domains: []
[+] Host: 78.138.120.119, Domains: []
[+] Host: 96.47.69.62, Domains: []
[+] Host: 96.47.69.62, Domains: []
[+] Host: 96.47.69.62, Domains: []
[+] Host: 72.52.4.121, Domains: []
[+] Host: 96.47.69.62, Domains: []
[+] Host: 72.52.4.121, Domains: []
[*] Auxiliary module execution completed
```

2016-10-19 06:30 UTC, mubix commented
I didn't know about this service until now. This is pretty awesome. Just did a `cidr:8.8.0.0/16`

2016-10-19 07:16 UTC, nixawk commented
- ZoomEye User Manual: https://www.zoomeye.org/help/manual

<img width="1373" alt="zoomeye" src="https://cloud.githubusercontent.com/assets/7352479/19508988/d1e85300-95a1-11e6-92fb-ee9195881f97.png">

2016-10-19 11:00 UTC, madmike33 commented
it would be great if u make for censys.io

2016-10-19 11:48 UTC, nixawk commented
@madmike33 This is a good idea. I'll try it later.

2016-10-19 16:53 UTC, thelightcosine requested changes
Everything looks pretty good here, just a few minor things to correct

2016-10-19 16:53 UTC, dmaloney-r7 commented on modules/auxiliary/gather/zoomeye_search.rb
> +    records && records.key?('matches') ? true : false
This ternary operator is completely extraneous: this can be re-written simply as:
```
def match_records?(records)
  records && records.key?('matches')
end
```

and it will do the right thing

2016-10-19 16:53 UTC, dmaloney-r7 commented on modules/auxiliary/gather/zoomeye_search.rb
> +      break if page > maxpage
this break statement should never be needed, the condition is checked at the beginning of each iteration. if this condition is ever hit something is very wrong

2016-10-19 16:53 UTC, dmaloney-r7 commented on modules/auxiliary/gather/zoomeye_search.rb
> +  include Msf::Exploit::Remote::HttpClient
You don't actually appear to be using either of these mixins. You're not reporting anything to the database, and you're using Net::HTTP and URI directly instead of using the Metasploit HTTP client. There's nothing really wrong with not using the HttpClient, but there's no reason to include it if you're not going to use it

2016-10-20 00:59 UTC, nixawk commented on modules/auxiliary/gather/zoomeye_search.rb
> +      break if page > maxpage
Thanks @dmaloney-r7 .

2016-10-20 01:01 UTC, nixawk commented on modules/auxiliary/gather/zoomeye_search.rb
> +  include Msf::Exploit::Remote::HttpClient
I'll try to replace Net::HTTP Metasploit HTTP client.

2016-10-20 01:56 UTC, nixawk commented
Thanks @dmaloney-r7.  The module is updated to use **Metasploit HTTP Client**, and it works.

```
msf auxiliary(zoomeye_search) > set RESOURCE host
RESOURCE => host
msf auxiliary(zoomeye_search) > set ZOOMEYE_DORK "apache country:us"
ZOOMEYE_DORK => apache country:us
msf auxiliary(zoomeye_search) > set MAXPAGE 2
MAXPAGE => 2
msf auxiliary(zoomeye_search) > run

[*] ZoomEye host Search: apache country:us - page: 1
[+] Host: 50.22.36.55 ,PORT: 21
[+] Host: 50.200.127.124 ,PORT: 21
[+] Host: 50.206.79.73 ,PORT: 22
[+] Host: 50.151.68.228 ,PORT: 22
[+] Host: 50.143.188.35 ,PORT: 22
[+] Host: 50.87.254.17 ,PORT: 25
[+] Host: 50.203.236.80 ,PORT: 25
[+] Host: 50.87.254.15 ,PORT: 25
[+] Host: 50.87.254.18 ,PORT: 25
[+] Host: 50.78.222.246 ,PORT: 25
[*] ZoomEye host Search: apache country:us - page: 2
[+] Host: 50.22.22.126 ,PORT: 25
[+] Host: 50.87.254.19 ,PORT: 25
[+] Host: 50.62.127.163 ,PORT: 80
[+] Host: 50.87.154.60 ,PORT: 80
[+] Host: 50.87.174.171 ,PORT: 80
[+] Host: 50.115.239.44 ,PORT: 80
[+] Host: 50.87.148.171 ,PORT: 80
[+] Host: 50.150.77.186 ,PORT: 80
[+] Host: 50.56.241.72 ,PORT: 80
[+] Host: 50.63.179.39 ,PORT: 80
[*] Auxiliary module execution completed
```

2016-10-21 03:57 UTC, nixawk commented
Please try to use **`USERNAME`** / **`PASSWORD`**, **ZOOMEYE_APIKEY** is removed because it has a limit lifecycle (serval hours,).

2016-10-21 14:27 UTC, thelightcosine approved these changes

2016-10-21 15:26 UTC, merged