Make php_cgi_arg_injection work in certain environnement
rapid7/metasploit-framework pull request #7929
Opened 2017-02-07 18:05 UTC by jvoisin

This commit sets two more options to `0` in the payload:

- [cgi.force_redirect](https://secure.php.net/manual/en/ini.core.php#ini.cgi.force-redirect)
- [cgi.redirect_status_env](https://secure.php.net/manual/en/ini.core.php#ini.cgi.redirect-status-env)

The configuration directive `cgi.force_redirect` prevents anyone from calling PHP
directly with a URL like http://my.host/cgi-bin/php/secretdir/script.php.
Instead, PHP will only parse in this mode if it has gone through a web server redirect rule.

The string set in the configuration directive `cgi.redirect_status_env`
is the one that PHP will look for to know it's ok to continue its
execution. This might be use together with the previous configuration
option as a security measure.

Setting those variables to `0` is (as stated in the documentation) a
security issue, but it also make the exploit work on some Apache2 setup.

## Verification

- [ ] Start `msfconsole`
- [ ] `use exploits/multi/http/php_cgi_arg_injection.rb`
- [ ] Setup your apache2 in a weird way
- [ ] **Verify** that you get  shell
- [ ] **Verify** that [other]( https://www.vulnerability-lab.com/get_content.php?id=1562 ) [exploits](https://www.praetorian.com/blog/php-cgi-remote-command-execution-vulnerability-exploitation) are using those parameters

2017-02-07 18:05 UTC, jvoisin commented
Is it worth adding `suhosin.simulation=1`? Or do we want to keep the payload as short as possible?

2017-02-08 08:08 UTC, wvu-r7 commented
cc @egypt

2017-02-08 17:39 UTC, egypt commented
I don't think payload size is really a big deal for this exploit. From a quick search it looks like real attackers are using `suhosin.simulation=1` in the wild. It seems reasonable to add it.

2017-02-08 17:59 UTC, egypt requested changes

2017-02-08 17:59 UTC, egypt commented on modules/exploits/multi/http/php_cgi_arg_injection.rb
> +        create_arg("-d", "cgi.force_redirect=0"),
For consistency and greater entropy, this `0` should probably be `#{rand_php_ini_false}`

2017-02-08 17:59 UTC, egypt commented on modules/exploits/multi/http/php_cgi_arg_injection.rb
> +        create_arg("-d", "cgi.redirect_status_env=0"),
Same here. For consistency and greater entropy, this `0` should probably be `#{rand_php_ini_false}`

2017-02-10 13:19 UTC, jvoisin commented
I'm not sure about using `rand_php_false` for the `cgi.redirect_status_env` variable, since it could likelybe interpreted as a string.

2017-02-10 13:19 UTC, jvoisin commented on modules/exploits/multi/http/php_cgi_arg_injection.rb
> +        create_arg("-d", "cgi.redirect_status_env=0"),
I'm not sure about using `rand_php_false` for the `cgi.redirect_status_env` variable, since it could likelybe interpreted as a string.

2017-02-10 13:19 UTC, jvoisin commented on modules/exploits/multi/http/php_cgi_arg_injection.rb
> +        create_arg("-d", "cgi.force_redirect=0"),
Sure.

2017-02-10 16:00 UTC, egypt approved these changes

2017-02-10 16:02 UTC, merged

2017-02-10 16:03 UTC, egypt commented
@jvoisin Thanks!

2017-02-10 19:08 UTC, wvu-r7 commented
Thanks for landing, @egypt. :3

2017-02-21 23:40 UTC, tdoan-r7 commented
# Release Notes

The cgi.force_redirect and cgi.redirect_status_env options are now set to 0 in the PHP CGI ARG injection exploit, which will allow it to work on some Apache2 setups.

2017-02-22 11:07 UTC, jvoisin commented
I also added a suhosin deactivation.