Add Satel SenNet Command Exec Module
rapid7/metasploit-framework pull request #8205
Opened 2017-04-06 21:22 UTC by juushya

This module exploits an OS Command Injection vulnerability in Satel SenNet Data Loggers to perform arbitrary command execution as 'root'.

## Verification Steps

1. Do: ```use auxiliary/scanner/telnet/satel_cmd_exec```
2. Do: ```set RHOSTS [IP]```
3. Do: ```set RPORT [PORT]```
4. Do: ```run```

## Checks run

  ```
rubocop
msftidy
  ```

## NOTE
Currently the module executes a single command. It should be able to chain and execute multiple commands - it does so when tested manually. I am using `socks.puts(cmd)` to send the commands. If this is not the correct way, or if there is a better way to do this, please let me know.

2017-04-06 21:46 UTC, mmetince commented on modules/auxiliary/scanner/telnet/satel_cmd_exec.rb
> +        inject = '$true; ' + "#{command}"
One unimportant thing. Wouldn't be better with `inject = "$true; #{command}"`  ?

2017-04-06 22:08 UTC, wvu-r7 commented
Is there a reason this isn't an exploit module?

2017-04-16 20:18 UTC, busterb commented
Hi. The original disclosure refers to an 'ARM' operating system, but the only thing close to that I could find was https://www.mbed.com/en/platform/mbed-os/, which seems like a probably but unlikely choice by the vendor. Is it safe to presume these devices are really running Linux?

I'd imagine these devices are found in massive numbers however, which would mean that enumerating them is almost as interesting as exploiting them, since they hand you a shell on port 5000 directly (there's not much to exploit here.) It would be neat to see an exploit module that could double as a scanner module, similar to the wish on #7614. Then one module could work either way, doing checks against multiple hosts, or exploits.

2017-04-17 02:40 UTC, wvu-r7 commented on modules/auxiliary/scanner/telnet/satel_cmd_exec.rb
> +        p = store_loot(loot_name, loot_type, datastore['RHOST'], data, loot_desc)
Seems like this should be more of a note than loot?

2017-04-17 17:22 UTC, busterb requested changes

2017-04-17 17:22 UTC, busterb commented on modules/auxiliary/scanner/telnet/satel_cmd_exec.rb
> +        ],
This needs refs, at least the CVE, links to web pages are good too.

2017-04-17 17:22 UTC, busterb commented on modules/auxiliary/scanner/telnet/satel_cmd_exec.rb
> +        This module exploits an OS Command Injection vulnerability in Satel SenNet Data Loggers to perform arbitrary command execution as 'root'.
please wrap this

2017-04-17 17:22 UTC, busterb commented on modules/auxiliary/scanner/telnet/satel_cmd_exec.rb
> +    create_credential_login(login_data)
this can be done with create_credential_and_login

2017-04-17 17:22 UTC, busterb commented on modules/auxiliary/scanner/telnet/satel_cmd_exec.rb
> +  def report_cred(opts)
if you're not calling report_cred, it does not need to exist

2017-04-17 17:22 UTC, busterb commented on modules/auxiliary/scanner/telnet/satel_cmd_exec.rb
> +  def report_cred(opts)
suggest just deleting this

2017-04-17 17:22 UTC, busterb commented on modules/auxiliary/scanner/telnet/satel_cmd_exec.rb
> +require 'msf/core'
this is not needed (note to @wvu-r7 - msftidy kill)

2017-04-21 19:17 UTC, juushya commented on modules/auxiliary/scanner/telnet/satel_cmd_exec.rb
> +        p = store_loot(loot_name, loot_type, datastore['RHOST'], data, loot_desc)
@wvu-r7 loot seems more useful here, when executing multiple commands on IP ranges so all info is saved..

2017-04-21 19:24 UTC, juushya commented
@wvu-r7 @busterb That is correct. These boxes are based on ARM - armv5tejl - based on my observations. I am not sure if existing armle payloads will work, hence keeping this as auxiliary for cmd exec.

The shell on TCP 5000 is a busybox shell, and the module basically breaks out of this restricted shell. There is no banner produced, thus no fingerprinting check. One noisy way, perhaps, could be to send the commands anyway, & look for errors or valid output.?

2017-04-21 19:25 UTC, juushya commented
@wvu-r7 @busterb That is correct. These boxes are based on ARM - armv5tejl - based on my observations. I am not sure if existing armle payloads will work, hence keeping this as auxiliary for cmd exec.

The shell on TCP 5000 is a busybox shell, and the module basically breaks out of this restricted shell. There is no banner produced, thus no fingerprinting check. One noisy way, perhaps, could be to send the commands anyway, & look for errors or valid output.?

2017-05-24 11:18 UTC, juushya commented
Currently, only the module handles executing one command at a time. In case of more than one command, for e.g `id; pwd;`, a second `sock.get_once` is needed followed by another `print_good`, & so on. I am not sure if there is a way to exec multiple commands without the need to do `sock.get_once` multiple times..

2017-05-30 22:53 UTC, juushya commented
@busterb @wvu-r7 @mmetince Sending the pcap now. Thanks.

2017-06-24 17:50 UTC, juushya commented
@busterb @wvu-r7 @mmetince Guys, is anything else needed on this..

2017-06-24 18:31 UTC, busterb approved these changes

2017-06-25 23:03 UTC, merged

2017-06-25 23:04 UTC, busterb commented
## Release Notes

This module exploits an OS Command Injection vulnerability in Satel SenNet Data Loggers to perform arbitrary command execution as 'root'. The results of commands are stored as loot by the module, so that the operator can collect information efficiently from an entire data logger network.

2017-06-26 04:51 UTC, wvu-r7 commented on modules/auxiliary/scanner/telnet/satel_cmd_exec.rb
> +        p = store_loot(loot_name, loot_type, datastore['RHOST'], data, loot_desc)
I suggested note over loot because you're storing text output, but you could actually store file output or something else. Loot is just fine. Might have been good to store the command as well, though.

2017-06-26 04:54 UTC, wvu-r7 commented
I have no right to complain about this being an `aux/scanner` taking a command. That's exactly what I did with the Shellshock module. Thanks for the submission, @juushya. Keep 'em coming!