New Module: RCE on IDA Pro debug server
rapid7/metasploit-framework pull request #8474
Opened 2017-05-28 12:27 UTC by PatrickHarsdorf

By default the server component of the HexRays IDA PRO debugger binds to all interfaces and has no password set.
This modules gives us RCE.

IDA PRO is not the most popular software, but this module could be fun at CTF competitions.

## Verification
Should work on all versions. 
Tested: 6.6, 6.8, 6.9, Linux & Windows.

./msfconsole
use auxiliary/admin/idapro/idapro_dbgsrv_exec
msf auxiliary(idapro_dbgsrv_exec) > set RHOST 192.168.148.140
msf auxiliary(idapro_dbgsrv_exec) > set CMD /usr/bin/touch pwned
msf auxiliary(idapro_dbgsrv_exec) > run

File "pwned" is created on remote system

2017-05-28 14:39 UTC, h00die commented
If this is an RCE, why not make it an exploit module and pop a shell?

2017-05-28 14:40 UTC, h00die commented
Please also add documentation see https://github.com/rapid7/metasploit-framework/wiki/Generating-Module-Documentation

2017-05-28 15:41 UTC, cbrnrd commented
@h00die I could work on making this use cmdstager and turn it into an exploit. @PatrickHarsdorf would this be okay with you?

2017-05-28 15:50 UTC, cbrnrd requested changes
Just a few minor things

2017-05-28 15:50 UTC, cbrnrd commented on modules/auxiliary/admin/idapro/idapro_dbgsrv_exec.rb
> +      print_status("Sending RPC code: #{rpc_code}, data: #{Rex::Text.hexify(data)}")
here as well

2017-05-28 15:50 UTC, cbrnrd commented on modules/auxiliary/admin/idapro/idapro_dbgsrv_exec.rb
> +      print_status("Received RPC code: #{rpc_code}, data: #{Rex::Text.hexify(data)}")
same as above

2017-05-28 15:50 UTC, cbrnrd commented on modules/auxiliary/admin/idapro/idapro_dbgsrv_exec.rb
> +      print_status("packet length: #{length}")
`vprint_status` and no check

2017-05-28 15:50 UTC, cbrnrd commented on modules/auxiliary/admin/idapro/idapro_dbgsrv_exec.rb
> +                          ],
if there are no references please remove the section

2017-05-28 15:50 UTC, cbrnrd commented on modules/auxiliary/admin/idapro/idapro_dbgsrv_exec.rb
> +                      'DisclosureDate' => ''))
if there isn't a disclosure date please remove it

2017-05-28 18:03 UTC, PatrickHarsdorf commented on modules/auxiliary/admin/idapro/idapro_dbgsrv_exec.rb
> +      print_status("Sending RPC code: #{rpc_code}, data: #{Rex::Text.hexify(data)}")
@cbrnrd Thanks, that would be great. I won´t be at my dev machine for a few days anyway.

2017-05-28 19:01 UTC, cbrnrd commented
@PatrickHarsdorf Whipped something up [here](https://gist.github.com/cbrnrd/c16fd8096cb072f80b7d0bb8bcb55edc). Mind testing it when you get a chance?

2017-06-01 06:33 UTC, PatrickHarsdorf commented
@cbrnrd: Thanks. I had to change a few things, but got it to work. Works on Linux, fails on Windows10 for reasons I have not full explored but seem unrelated to code of either of us (vbs file does not get created because %TEMP% does not get expanded?).

I would prefer to go back to the original RCE. It´s simpler and does not rely on other potentially brittle stuff. Also works it works OSX and other platforms not supported by cmdstager.

2017-06-19 17:24 UTC, wwebb-r7 commented
Thanks for the submission.  After review, we've decided that we can't see any real-world use case for this.  For one, I've personally never encountered anyone running the debug server on a machine or VM exposed on an outward facing interface.  Secondly, I've screwed up with the password parameter myself in the past.  When that happens, I immediately kill the server and start over.  I can't imagine why anyone else's workflow would be any different.  Finally, Hexrays is fully aware of this (as are most end users of any debugging server I'd assume) and have been since the product was branded by DataRescue.  The fact that they've done nothing to mitigate it would seem to echo the sentiment that it's not a security issue.  Personally, I can't see this as being fun for anyone at a CTF, be it module users spending untold time trying to get a shell with it, or any potential targets unlucky and naive enough to fall victim to it.

Closing.  If you feel this is in error, let us know.

2017-06-19 17:24 UTC, closed without merging