Add processmaker_exec documentation
rapid7/metasploit-framework pull request #8482
Opened 2017-05-30 08:29 UTC by bcoles

Add documentation for `exploit/multi/http/processmaker_exec` module.

2017-05-31 00:20 UTC, h00die requested changes
a few minor changes, looks good though!

2017-05-31 00:20 UTC, h00die commented on documentation/modules/exploit/multi/http/processmaker_exec.md
> +  This module has been tested successfully on ProcessMaker Open Source versions 2.5.1, 2.5.0, 2.0.23 on Windows XP SP3; and version 2.0.45 on Debian Linux.
Lets change this to a bullet or numbered list.

Successfully tested against:

- 2.5.1 on Windows XP SP3
- 2.5.0 on Windows XP SP3
- 2.0.45 on Debian
- 2.0.23 on Windows XP SP3

2017-05-31 00:20 UTC, h00die commented on documentation/modules/exploit/multi/http/processmaker_exec.md
> +  The relevant source code for the affected files is shown below.
I'd say lets remove this, i think its too much detail for these docs.  I'd either link to http://bugs.processmaker.com/view.php?id=13436 where you describe it or the git where they fixed it: https://github.com/colosa/processmaker/pull/2107/files

2017-05-31 00:20 UTC, h00die commented on documentation/modules/exploit/multi/http/processmaker_exec.md
> +
can you do a L3 heading (###) and put in what version of processmaker it is and the OS (debian) just like on the other markdown PR you submitted.

2017-05-31 01:23 UTC, bcoles commented on documentation/modules/exploit/multi/http/processmaker_exec.md
> +  The relevant source code for the affected files is shown below.
Are you sure? Too much detail for the documentation doesn't sound right...

2017-05-31 01:24 UTC, h00die commented on documentation/modules/exploit/multi/http/processmaker_exec.md
> +  The relevant source code for the affected files is shown below.
for **this** documentation.  This is more the how to use with examples, and setting up the environment and such.

I think that may be better in the PR, or having the link to it.

However, if you want to keep it, i wouldn't argue to the death

2017-05-31 01:49 UTC, bcoles commented on documentation/modules/exploit/multi/http/processmaker_exec.md
> +
That wouldn't be consistent with the rest of the documentation.

```bash
# grep -rn "Sample Output" documentation/modules/*
documentation/modules/auxiliary/admin/http/scadabr_credential_dump.md:30:## Sample Output
documentation/modules/auxiliary/admin/chromecast/chromecast_youtube.md:17:## Sample Output
documentation/modules/auxiliary/scanner/snmp/cambium_snmp_loot.md:19:## Sample Output
documentation/modules/auxiliary/scanner/ftp/anonymous.md:60:## Sample Output
documentation/modules/auxiliary/scanner/ftp/ftp_version.md:50:## Sample Output
documentation/modules/auxiliary/scanner/ftp/ftp_login.md:50:## Sample Output
documentation/modules/auxiliary/scanner/http/chromecast_wifi.md:9:## Sample Output
documentation/modules/auxiliary/scanner/http/crawler.md:37:## Sample Output
documentation/modules/auxiliary/scanner/http/epmp1000_dump_hashes.md:10:## Sample Output
documentation/modules/auxiliary/scanner/http/binom3_login_config_pass_dump.md:10:## Sample Output
documentation/modules/auxiliary/scanner/http/owa_ews_login.md:10:## Sample Output
documentation/modules/auxiliary/scanner/http/epmp1000_cmd_exec.md:10:## Sample Output
documentation/modules/auxiliary/scanner/http/robots_txt.md:28:## Sample Output
documentation/modules/auxiliary/scanner/http/chromecast_webserver.md:9:## Sample Output
documentation/modules/auxiliary/scanner/http/ms15_034_http_sys_memory_dump.md:14:## Sample Output
documentation/modules/auxiliary/scanner/http/epmp1000_web_login.md:10:## Sample Output
documentation/modules/auxiliary/scanner/http/meteocontrol_weblog_extractadmin.md:12:## Sample Output
documentation/modules/auxiliary/scanner/http/epmp1000_dump_config.md:10:## Sample Output
documentation/modules/auxiliary/scanner/http/gavazzi_em_login_loot.md:17:## Sample Output
documentation/modules/auxiliary/scanner/ike/cisco_ike_benigncertain.md:12:## Sample Output
documentation/modules/auxiliary/gather/censys_search.md:12:## Sample Output
documentation/modules/exploit/multi/browser/adobe_flash_hacking_team_uaf.md:20:## Sample Output
documentation/modules/exploit/multi/http/processmaker_exec.md:68:## Sample Output
documentation/modules/exploit/multi/http/rails_web_console_v2_code_exec.md:41:## Sample Output
documentation/modules/exploit/multi/http/glassfish_deployer.md:37:## Sample Output
documentation/modules/exploit/multi/http/axis2_deployer.md:20:## Sample Output
documentation/modules/exploit/multi/http/mediawiki_syntaxhighlight.md:50:## Sample Output
documentation/modules/exploit/unix/webapp/vicidial_user_authorization_unauth_cmd_exec.md:97:## Sample Output
documentation/modules/exploit/windows/iis/iis_webdav_upload_asp.md:24:## Sample Output
documentation/modules/exploit/windows/http/manageengine_connectionid_write.md:24:## Sample Output
documentation/modules/exploit/windows/http/serviio_checkstreamurl_cmd_exec.md:33:## Sample Output
```

2017-05-31 01:51 UTC, bcoles commented on documentation/modules/exploit/multi/http/processmaker_exec.md
> +  This module has been tested successfully on ProcessMaker Open Source versions 2.5.1, 2.5.0, 2.0.23 on Windows XP SP3; and version 2.0.45 on Debian Linux.
Fixed

2017-05-31 01:58 UTC, h00die commented on documentation/modules/exploit/multi/http/processmaker_exec.md
> +
Keep ```## Sample Output```, i mean on the next line down do the ```### bla bla bla```

You are correct on a consistence issue.  I think originally we were doing text blocks like on https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/auxiliary/admin/chromecast/chromecast_youtube.md#sample-output (Of note...) however its just cleaner/easier to do it like in https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/auxiliary/scanner/ftp/ftp_version.md#on-vsftpd-303-on-kali where you can send a direct link.  While many modules it wont matter since theres only one example, for bigger ones like https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/exploit/linux/local/service_persistence.md#scenarios it can make a bigger difference.

You bring up another point though Scenarios vs Sample Output.

2017-05-31 04:33 UTC, wvu-r7 commented on documentation/modules/exploit/multi/http/processmaker_exec.md
> +  The relevant source code for the affected files is shown below.
While I agree that a module doc might not be the right place for RCA, there's a chance the hard links may be gone in the future. The technical details here are in their own section and don't take up too much space. I see no harm in leaving them alone.

Honestly, we would put technical details in the module description itself, but code snippets would be going to far. Up to you how you want to handle this. I don't mind information overload in documentation so long as the sections are laid out cleanly. Maybe you can move this to an appendix of sorts.

2017-06-01 00:41 UTC, h00die approved these changes

2017-06-01 00:41 UTC, merged

2017-06-01 00:42 UTC, h00die commented
Landing this now, i'll do a sweep and fix up consistency issues on everything at once, no need to keep this waiting out by itself.

Thanks for the docs, and the discussion and keeping consistency in check!!!!

2017-06-01 00:42 UTC, h00die commented
# Release Notes
Adds docs for exploit/multi/http/processmaker_exec