Add snare_registry documentation
rapid7/metasploit-framework pull request #8485
Opened 2017-05-30 09:19 UTC by bcoles

Add documentation for `auxiliary/gather/snare_registry` module.

2017-05-31 00:06 UTC, h00die requested changes
Good doc, really good examples and nice explanation of the options.  few minor things to touch up

2017-05-31 00:06 UTC, h00die commented on documentation/modules/auxiliary/gather/snare_registry.md
> +  Installers for Snare Lite are no longer available and the product is unsupported.
I think this should be in BOLD as its important so people dont go looking all around (like i just did) before getting to this.

2017-05-31 00:06 UTC, h00die commented on documentation/modules/auxiliary/gather/snare_registry.md
> +
Lets add:
```
### Snare Lite for Windows version 4.0.2.0 on Windows XP SP3.
```

I like to put the versions down in the scenarios for clarity. You can keep or drop it from above in the vuln app section

2017-05-31 01:18 UTC, bcoles commented on documentation/modules/auxiliary/gather/snare_registry.md
> +  This module uses the Registry Dump feature of the [Snare Lite for Windows](https://sourceforge.net/projects/snare/) HTTP service on 6161/TCP to retrieve the Windows registry. The Dump Registry func
I'll fix this. The documentation and web interface refers to it as "Registry Dump". I'm not sure why I called it "Dump Registry."

2017-05-31 01:22 UTC, bcoles commented on documentation/modules/auxiliary/gather/snare_registry.md
> +  Installers for Snare Lite are no longer available and the product is unsupported.
I had a look for the software on Web Archive and Sourceforge. It's gone. However, the free trial is available here:

* https://drive.google.com/open?id=0B17PaDdG2x0BXzI3RzBLNFowSkU

I'll update the docs.

2017-05-31 01:37 UTC, bcoles commented on documentation/modules/auxiliary/gather/snare_registry.md
> +  Note: The Dump Registry functionality accepts only one connected client at a time. Requesting a large key/hive will cause the service to become unresponsive until the server completes the request.
Done

2017-05-31 01:37 UTC, bcoles commented on documentation/modules/auxiliary/gather/snare_registry.md
> +  Note: The Dump Registry functionality accepts only one connected client at a time. Requesting a large key/hive will cause the service to become unresponsive until the server completes the request.
Done

2017-05-31 01:37 UTC, bcoles commented on documentation/modules/auxiliary/gather/snare_registry.md
> +
Scenarios aren't specific to software version

2017-06-01 00:43 UTC, h00die approved these changes

2017-06-01 00:53 UTC, merged

2017-06-01 00:54 UTC, h00die commented
Landing this now, i'll do a sweep and fix up consistency issues on everything at once, no need to keep this waiting out by itself.

Thanks for the docs, and the discussion and keeping consistency in check!!!!

2017-06-01 00:55 UTC, h00die commented
Release Notes

Adds docs for auxiliary/gather/snare_registry