Clean up cmd_ps table output for Mettle
rapid7/metasploit-framework pull request #8545
Opened 2017-06-12 05:32 UTC by sempervictus

Mettle can run in all sorts of environments where some colums of a
process table will be nil. The existing implementation compacts
rows going into the table while providing filtering for the colum
contents only by checking the output of the first row in the proc
table.

Check column filters against all rows to ensure proper table init.
Check columns going into table for match against header.
Do not compact nil values in the table rows - some things, like
kthreads/workers dont have a path while other PIDs will.

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] Get a mettle session in current stable Linux system
- [ ] Run ps, get:
```
meterpreter > ps
[-] Error running command ps: Rex::RuntimeError Invalid number of columns
```
- [ ] Add this PR to framework
- [ ] **Verify** That under the above conditions, a nice table is printed
- [ ] **Verify** That other session types still work as intended

2017-06-12 18:51 UTC, egypt requested changes
You're not supposed to check your own boxes, @sempervictus  :stuck_out_tongue:

2017-06-12 18:51 UTC, egypt commented on lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb
>      # that processes might have different columns, but for now assume that the
This comment is now a lie. Please update it.

2017-06-12 18:51 UTC, egypt commented on lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb
> +      !(any? {|r| r.has_key?(c.downcase)}) or
`||` over `or`, per the style guide. Also, it's not in the style guide but I think I prefer `none?` over `!(any? ...)`.

2017-06-14 05:37 UTC, sempervictus commented on lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb
> +      !(any? {|r| r.has_key?(c.downcase)}) or
@egypt: thanks for the review boss, if i knew you were lookin i'd have added a ternary conditional assignment somewhere ;-).

Comments nixed and style changes implemented. I wasn't thrilled with the !(any?..) piece either, the entire block looks voodoo-ish to me, but its hidden deep enough in the guts that anyone digging in there deserves some head scratching.

2017-06-23 02:48 UTC, egypt approved these changes

2017-06-24 19:44 UTC, merged

2017-07-18 16:45 UTC, alrosenthal-r7 commented
@egypt could you please add release notes to this PR?

2017-07-18 17:58 UTC, egypt commented
# Release notes

Fixes a bug where partial information about processes would prevent showing the whole table when you run the `ps` command in Meterpreter.

2017-07-18 17:58 UTC, egypt commented
@alrosenthal-r7 sorry, thanks for the reminder.