Print_Status -> Print_Good
rapid7/metasploit-framework pull request #8716
Opened 2017-07-13 23:11 UTC by g0tmi1k

When there is success or something is added to `report_*`, use `print_good` to make it stand out.

2017-07-13 23:48 UTC, wvu-r7 commented
Welcome back, @g0tmi1k. :)

2017-07-14 00:39 UTC, sempervictus commented
That right there, is some serious code review.
Thanks as always @g0tmi1k, your tenacity in this matter is bordering on disturbing ;-)

2017-07-14 04:17 UTC, OJ reviewed
Thanks @g0tmi1k for this! Changes look fine, just a few little things we can adjust.

@bcook-r7 do we have any test suites that allow us to easily test all the modules that were modified?

2017-07-14 04:17 UTC, OJ commented on modules/post/windows/gather/enum_termserv.rb
> +# post/windows/gather/enum_termserv.rb
Given this is commented out, can it be removed?

2017-07-14 04:17 UTC, OJ commented on modules/post/windows/gather/credentials/vnc.rb
> +# post/windows/gather/enum_vnc_pw.rb
Given this is commented out, can it be removed?

2017-07-14 04:17 UTC, OJ commented on modules/exploits/multi/http/rails_dynamic_render_code_exec.rb
> +
Can remove a couple of these newlines?

2017-07-14 04:17 UTC, OJ commented on modules/exploits/multi/http/bassmaster_js_injection.rb
> +
Can remove a couple of these newlines?

2017-07-14 04:17 UTC, OJ commented on modules/exploits/mainframe/ftp/ftp_jcl_creds.rb
> +
Can remove a couple of these newlines?

2017-07-14 04:17 UTC, OJ commented on modules/exploits/linux/http/tr064_ntpserver_cmdinject.rb
> +
Can remove a couple of these newlines?

2017-07-14 04:17 UTC, OJ commented on modules/encoders/x86/service.rb
> +
Can remove a newline.

2017-07-14 04:17 UTC, OJ commented on modules/auxiliary/gather/avtech744_dvr_accounts.rb
> +
Can remove a couple of these newlines?

2017-07-14 07:51 UTC, g0tmi1k commented
Missed me @wvu-r7 ? ;)

Thanks @sempervictus :)

If there is anything I can do to help, just shout @OJ 
I've fixed up all the ones that you reported - as well as then apply it to all the other modules I could see.

2017-07-14 08:21 UTC, OJ commented
Looking good @g0tmi1k !

2017-07-14 08:22 UTC, OJ approved these changes
👍

2017-07-14 10:16 UTC, wvu requested changes
So, I disagree with this commit because it unbalances the whitespace on the other end of the `class` for a number of modules (my own included). Thoughts on how to make it more consistent?

2017-07-17 11:12 UTC, g0tmi1k commented
What can I do to help?

2017-07-17 15:21 UTC, wvu-r7 commented
Just make the whitespace consistent. Don't remove the extra newline after `class` if there is one before the last `end`. Please and thank you. :)

2017-07-18 09:25 UTC, g0tmi1k commented
What about removing the last newline after `class` if there is one?

2017-07-18 15:56 UTC, wvu-r7 commented
That would be more correct, but then I'd have to change my personal style. 1366 changed files is a lot. :-)

2017-07-19 10:24 UTC, g0tmi1k commented
How does it look now to you?

2017-07-24 12:28 UTC, busterb commented
I'm going to help move this along before it bit-rots. So far haven't seen anything controversial.

2017-07-24 13:53 UTC, merged

2017-07-24 13:55 UTC, busterb commented
I made a few additional changes based on the latest master. And as long as we were touching the splat everywhere and making msftidy run on everything, I updated the http://metasploit.com URLs to use https://metasploit.com.

6300758c46 - use https for metaploit.com links
80d18fae6a - update example modules to have zero rubocop violations
6e06d1a8b1 - update rubocop rules for common practice
1d290d2491 - resurrect one print_error/bad conversion for symmetry in eternalblue (print_bad was added recently by popular demand from the author)
8db3f74b81 - fix a broken link

2017-07-24 13:57 UTC, g0tmi1k commented
Thanking you @busterb! 🎉

2017-07-24 13:58 UTC, busterb commented
now where's that hash rocket guy when you need him...

2017-07-24 14:25 UTC, g0tmi1k commented
Where did you last leave him ;)

2017-07-24 21:07 UTC, wvu-r7 commented
🙇

2017-07-25 02:28 UTC, bcoles commented
```

       !
       !
       ^
      /#\
     /###\
    |=###=|
    |# H #|
    |# A #|
    |# S #|
    |# H #|
    |## ##|
    |# R #|
    |# K #|
    |# T #|
    |#####|
   /|##!##|\
  /#|##!##|#\
 /##/##!##\##\
|##/(     )\##|
|#/  #####  \#|
|/  #######  \|
    #######
     #####
      ###
      ###
       #
       #
       #
       #
```