syn.md
rapid7/metasploit-framework pull request #8942
Opened 2017-09-08 06:58 UTC by d78ui98

documentation for syn portscan

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/smb/ms08_067_netapi`
- [ ] ...
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not
- [ ] **Document** the thing and how it works ([Example](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/multi/gather/aws_keys.md))

2017-09-08 09:17 UTC, h00die commented
I cleaned up the title and submission info. i'll tackle this one in a few hours.

2017-09-08 20:29 UTC, wvu-r7 commented on documentation/modules/auxiliary/scanner/portscan/syn.md
> +This module will attempt to initiate a three-way handshake with every
Every...?

2017-09-08 20:36 UTC, h00die commented on documentation/modules/auxiliary/scanner/portscan/syn.md
> +This module will attempt to initiate a three-way handshake with every
Syn scanner three way handshake?!

2017-09-08 23:26 UTC, h00die requested changes

2017-09-08 23:26 UTC, h00die commented on documentation/modules/auxiliary/scanner/portscan/syn.md
> +  This is the list of ports to test for TCP Scan on each host.
This is the list of TCP ports to test on each host.

2017-09-08 23:26 UTC, h00die commented on documentation/modules/auxiliary/scanner/portscan/syn.md
> +  Formats like  `1-3`, `1,2,3`, `1,2-3`, etc. are all supported.Default
supported. Default (add a space)

2017-09-08 23:26 UTC, h00die commented on documentation/modules/auxiliary/scanner/portscan/syn.md
> +   Maximum time (seconds) to wait for a response. The default value is 500.
`500`

2017-09-08 23:26 UTC, h00die commented on documentation/modules/auxiliary/scanner/portscan/syn.md
> +  **ConnectTimeout**
this doesn't exist in syn scanner.

2017-09-08 23:26 UTC, h00die commented on documentation/modules/auxiliary/scanner/portscan/syn.md
> +  1. Do: `use auxiliary/scanner/portscan/tcp`
syn?

2017-09-08 23:26 UTC, h00die commented on documentation/modules/auxiliary/scanner/portscan/syn.md
> +  3. Do: `set RPORT [PORTS]`
PORTS

2017-09-08 23:26 UTC, h00die commented on documentation/modules/auxiliary/scanner/portscan/syn.md
> +  5. If any of the TCP ports were open they will be discovered, status will be printed indicated as such.
indicating

2017-09-09 08:00 UTC, d78ui98 commented
I have made the requested changes. Thanks @h00die  @wvu-r7

2017-09-10 14:04 UTC, merged

2017-09-10 14:05 UTC, h00die commented
# Release Notes
Docs for syn port scanner.

2017-09-10 14:06 UTC, h00die commented
@d78ui98 Thank you for the submission.  I had one minor correction https://github.com/rapid7/metasploit-framework/commit/ddfa1d722bb98f21992b6a151e856e24ce44fb06 but didn't want to push this back any further.