Update shell2session
rapid7/metasploit-framework pull request #8986
Opened 2017-09-21 13:17 UTC by bwatters-r7

This is a work-in-progress.  The reason I've pushed it early is because it is much easier to point the testing framework at a PR than a branch.  The intended goal is to fix up this module to support migration in many more cases and verify the behavior of the override attribute.

It is out early so I can use it to test some expected changes to mettle payloads, and this module allows us to perform automated testing on meterpreter sessions for devices that have ssh access.

- [ ] Start `msfconsole`
- [ ] Get a shell (example: `use auxiliary/scanner/ssh/ssh_login` and set username, password, and RHOSTS)
- [ ] `use post/multi/manage/shell_to_meterpreter`
- [ ] `set session <session>`
- [ ] `set LHOST <IP>`
- [ ] `run`
- [ ] `sysinfo`
- [ ] **Verify** you get a valid meterpreter session
- [ ] **Verify** you get the expected architecture on your meterpreter session.  THe defualt is python if you are on linux.
- [ ] Repeat on Windows x86 Targets
- [ ] Repeat on Windows x64 Targets
- [ ] Repeat on  Linux x86 Targets
- [ ] Repeat on  Linux ARM Targets
- [ ] Repeat on  Linux MIPS Targets

As the goal is to support automated testing, I will supply the test results for this covering the test cases required.

2017-09-25 20:21 UTC, bwatters-r7 commented
That went poorly....

2017-09-25 20:22 UTC, wvu-r7 commented
WOAH.

2017-09-27 04:35 UTC, timwr commented on modules/post/multi/manage/shell_to_meterpreter.rb
> +          payload_name = 'linux/armle/meterpreter/reverse_tcp'
Can you add AARCH64?
```
        elsif target_info =~ /aarch64/
          payload_name = 'linux/aarch64/meterpreter/reverse_tcp'
          larch = [ARCH_AARCH64]
```

2017-09-27 04:36 UTC, timwr commented
Good change, I should really fix: https://github.com/rapid7/metasploit-framework/issues/8436
I think it's as simple as removing the "session should be meterpreter" check. 
Also perhaps you can rebase this change so only the relevant diff is visible?

2017-09-27 07:15 UTC, timwr requested changes

2017-09-27 07:15 UTC, timwr commented on modules/post/multi/manage/shell_to_meterpreter.rb
> +        if target_info =~ /86/
You should flip this and the /64/ check, or `Linux x86_64` will match /86/ before reaching /64/.

2017-09-27 07:16 UTC, timwr commented on modules/post/multi/manage/shell_to_meterpreter.rb
> +        if target_info =~ /86/
Or put x86 in the else section...

2017-12-01 17:05 UTC, bwatters-r7 commented
After some digging, I think this PR is the wrong way to go about getting the desired functionality.  I'm closing this and instead opening https://github.com/rapid7/metasploit-framework/pull/9267

2017-12-01 17:05 UTC, closed without merging

2017-12-06 17:25 UTC, sempervictus commented
If the functionality is common for both the post and exploit use cases, really local exploit and remote, it probably warrants moving up a namespace and providing accessors to both consumers via common api. All for the work BTW.