Kb for auxiliary/scanner/http/open_proxy
rapid7/metasploit-framework pull request #9069
Opened 2017-10-11 11:03 UTC by itsmeroy2012

### Documentation on auxiliary/scanner/http/open_proxy
### Part of issue #8296

2017-10-11 21:07 UTC, wwebb-r7 requested changes

2017-10-11 21:07 UTC, wwebb-r7 commented on documentation/modules/auxiliary/scanner/http/open_proxy.md
> +Checks if an HTTP proxy is open. False positive are avoided verifying the HTTP return code and matching a pattern. The CONNECT method is verified only the return code. HTTP headers are shown regardin
> False positive are avoided verifying the HTTP return code and matching a pattern

Perhaps you meant

> False positives are avoided by verifying the HTTP return code and matching a pattern

also
>The CONNECT method is verified only the return code

maybe

> The CONNECT method is verified only by the return code

2017-10-11 21:40 UTC, wwebb-r7 commented on documentation/modules/auxiliary/scanner/http/open_proxy.md
> +Checks if an HTTP proxy is open. False positive are avoided by verifying the HTTP return code and matching a pattern. The CONNECT method is verified only by the return code. HTTP headers are shown re
Don't forget to make "false positive" plural

2017-10-12 00:36 UTC, wwebb-r7 approved these changes

2017-10-12 04:09 UTC, merged

2017-10-12 04:09 UTC, wwebb-r7 commented
### Release Notes

This update adds documentation for scanner/http/open_proxy

2017-10-12 04:10 UTC, wwebb-r7 commented
Looks good to go.  Thanks for the quick updates.

2017-10-13 21:46 UTC, vipzen commented
I was waiting for this. Thanks.