Adding ua_parser_js ReDoS Module
rapid7/metasploit-framework pull request #9284
Opened 2017-12-07 16:36 UTC by nstarke

"ua-parser-js" is an npm module for parsing browser
user-agent strings.  Vulnerable version of this module
have a problematic regular expression that can be exploited
to cause the entire application processing thread to "pause"
as it tries to apply the regular expression to the input.
This is problematic for single-threaded application environments
such as nodejs.  The end result is a denial of service
condition for vulnerable applications, where no further
requests can be processed.

## Verification

List the steps needed to make sure this thing works
- [ ] Create a new directory for test application
- [ ] copy below example server into test application directory as `server.js`
- [ ] run `npm i express` to install express in the test application directory
- [ ] to test vulnerable versions of the module, run `npm i ua-parser-js@0.7.15` to install a vulnerable version of ua-parser-js
- [ ] to test non-vulnerable versions of the module, run `npm i ua-parser-js` to install the latest version of ua-parser-js.
- [ ] once all dependencies are installed, run the server with `node server.js`
- [ ] Open up a new terminal
- [ ] Start `msfconsole`
- [ ] `use auxiliary/dos/http/ua_parser_js_redos`
- [ ]  `run`
- [ ] In vulnerable installations, Module should have positive output and the test application should accept no further requests.
- [ ] In non-vulnerable installations, module should have negative output and the test application should accept further requests.

Test application:
```
// npm i express
// npm i ua-parser-js@0.7.15 (vulnerable)
// npm i ua-parser-js (non-vulnerable)

const express = require('express')
const uaParser = require('ua-parser-js');
const app = express()

app.get('/', (req, res) => {
  var parser = new uaParser(req.headers['user-agent']);
  res.end(JSON.stringify(parser.getResult()));
});

app.listen(3000, '0.0.0.0', () => console.log('Example app listening on port 3000!'))
```

2017-12-07 17:24 UTC, wvu-r7 commented
He's back!

2017-12-11 18:07 UTC, h00die commented
do you mind putting some docs together for this module?  Template is [here](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/module_doc_template.md)

2017-12-11 18:13 UTC, h00die commented
Was this reported to the project? I dont see any obvious issues or PRs over there.

2017-12-11 18:27 UTC, h00die requested changes

2017-12-11 18:27 UTC, h00die commented on modules/auxiliary/dos/http/ua_parser_js_redos.rb
> +        This module exploits a Regular Expression Denial of Service vulnerability in the npm module "ua-parser-js". Server-side applications that use "ua-parser-js" for parsing the browser user-agent
can you multi-line this please

2017-12-11 18:27 UTC, h00die commented on modules/auxiliary/dos/http/ua_parser_js_redos.rb
> +      'Name'           => 'ua-parser-js npm module - Regular Expression Denial of Service',
can we shorten this, maybe DoS or REDoS?  Maybe also drop the - before the REDoS part as well?

2017-12-11 18:27 UTC, h00die commented on modules/auxiliary/dos/http/ua_parser_js_redos.rb
> +          ['CWE', '400'],
As per comment in PR, was the project notified of the issue?  That would give something to point back to.

2017-12-11 18:27 UTC, h00die commented on modules/auxiliary/dos/http/ua_parser_js_redos.rb
> +      print_status("Testing for service unresponsiveness.")
trade " for '

2017-12-11 18:27 UTC, h00die commented on modules/auxiliary/dos/http/ua_parser_js_redos.rb
> +        print_good("Service not responding.")
no need for interpolation

2017-12-11 18:27 UTC, h00die commented on modules/auxiliary/dos/http/ua_parser_js_redos.rb
> +        print_error("Service responded with a valid HTTP Response; ReDoS attack failed.")
no need for interpolation

2017-12-11 18:27 UTC, h00die commented on modules/auxiliary/dos/http/ua_parser_js_redos.rb
> +      print_error("An unknown error occurred.")
no need for interpolation

2017-12-11 18:27 UTC, h00die commented on modules/auxiliary/dos/http/ua_parser_js_redos.rb
> +      print_good("HTTP request timed out, most likely the ReDoS attack was successful.")
no need for interpolation

2017-12-11 18:27 UTC, h00die commented on modules/auxiliary/dos/http/ua_parser_js_redos.rb
> +      print_status("Testing Service to make sure it is working.")
no need for interpolation

2017-12-11 18:27 UTC, h00die commented on modules/auxiliary/dos/http/ua_parser_js_redos.rb
> +        print_status("Test request successful, attempting to send payload")
no need for interpolation

2017-12-11 18:27 UTC, h00die commented on modules/auxiliary/dos/http/ua_parser_js_redos.rb
> +    if !test_service
I believe we prefer `unless` instead of `if !`

2017-12-11 20:15 UTC, nstarke commented
This issue was indeed reported to the project, but it was done privately.  I added a link to the commit in the references section.

2017-12-13 01:40 UTC, h00die commented
![image](https://user-images.githubusercontent.com/752491/33917496-a436b688-df7c-11e7-991e-90b7693f18ac.png)

2017-12-13 01:45 UTC, h00die commented
Against the test app on ubuntu 16.04 with the vuln code:
## Good
```
msf auxiliary(dos/http/ua_parser_js_redos) > run

[*] Testing Service to make sure it is working.
[*] Test request successful, attempting to send payload
[*] Sending ReDoS request to 192.168.2.137:3000.
[*] No response received from 192.168.2.137:3000, service is most likely unresponsive.
[*] Testing for service unresponsiveness.
[+] Service not responding.
[*] Auxiliary module execution completed
```
success.
## not vuln
```
msf auxiliary(dos/http/ua_parser_js_redos) > run

[*] Testing Service to make sure it is working.
[*] Test request successful, attempting to send payload
[*] Sending ReDoS request to 192.168.2.137:3000.
[-] Auxiliary aborted due to failure: unknown: ReDoS request unsuccessful. Received status 200 from 192.168.2.137:3000.
[*] Auxiliary module execution completed
```
success.
## python simplehttpserver
```
msf auxiliary(dos/http/ua_parser_js_redos) > set rport 8000
rport => 8000
msf auxiliary(dos/http/ua_parser_js_redos) > run

[*] Testing Service to make sure it is working.
[*] Test request successful, attempting to send payload
[*] Sending ReDoS request to 192.168.2.137:8000.
[-] Auxiliary aborted due to failure: unknown: ReDoS request unsuccessful. Received status 200 from 192.168.2.137:8000.
[*] Auxiliary module execution completed
```
success.

2017-12-13 01:52 UTC, h00die commented
a few quick changes, and this will be good to go tomorrow!

2017-12-13 12:59 UTC, nstarke commented
What changes specifically need to be made at this point?  I'm a bit confused.  Sorry.

2017-12-13 16:33 UTC, h00die commented
I left 2 comments, one about the spaces before => and the other about slightly rearranging the docs

2017-12-13 16:41 UTC, nstarke commented
I'm sorry, I don't see the two comments you are referring to anywhere in the pull request. What am I doing wrong? Is there something I need to do in order to be able to see your comments?

2017-12-13 16:48 UTC, h00die commented
https://github.com/rapid7/metasploit-framework/pull/9284/files#r156543070
https://github.com/rapid7/metasploit-framework/pull/9284/files#r156544795
https://github.com/rapid7/metasploit-framework/pull/9284/files#r156546529

2017-12-13 16:49 UTC, h00die commented
Strange, I had the same thing happen where one tab showed the comments, and another one didn't. Regardless, I linked to the comments. Shouldn't take but 5min, and I'll land in a few hours!

2017-12-13 20:03 UTC, nstarke commented
I'm really sorry to sound like a broken record, but I still cannot see the comments you have left.  The links you provided don't direct me anywhere in the source tab.  I've tried two computers locally and had a colleague on the other side of the country try as well, and we have not been able to see your comments.  I'm really not sure what is going on at this point.  I apologize for the inconvenience.

2017-12-13 20:11 UTC, h00die commented
UGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.
my fault.
they're still pending. 2 seconds.

2017-12-13 20:11 UTC, h00die requested changes

2017-12-14 00:27 UTC, h00die approved these changes

2017-12-14 00:33 UTC, merged

2017-12-14 00:34 UTC, h00die commented
had 2 minor edits: https://github.com/rapid7/metasploit-framework/commit/544e4e3d0b1f559ebf1aa460e5601b50ea9cf6b3 but just ninja patched it to prevent that from being a hangup.

Thanks for the module, everything looked pretty good from the beginning, so easy land!

2017-12-14 00:35 UTC, h00die commented
# Release Notes
This PR adds a DoS module against ua_parser_js which is an npm module which has a problematic regex.

2017-12-15 13:57 UTC, nstarke commented
Thanks for landing this.  As always, it was a pleasure!