Module documentation fixes and updates
rapid7/metasploit-framework pull request #9493
Opened 2018-02-03 01:56 UTC by cbrnrd

I did a quick run through of some module docs and fixed some minor things. This is _not_ all of the problems in the docs. I'm sure there are more. 
This PR is a few things:
1. It fixes some grammatical errors (commas, spelling and the like)
2. Adds 'Introduction' header to particularly long starting descriptions 
    - I added this usually if the description was >~ 5 lines
3. Added clarifying statements (see censys_search.md)
4. Fix some broken links
5. Added some additional information (see archmigrate.md)
6. Fixed some minor but annoying markdown header typos
    - ##they looked like this
7. Removed some eyesores
    - See ms17_010_eternalblue, hashdump, and archmigrate

Paging @h00die because he's the docmaster, but if anyone else has some suggestions or additional edits, please tell me!

2018-02-03 02:51 UTC, h00die requested changes

2018-02-03 02:51 UTC, h00die commented on documentation/modules/exploit/multi/local/allwinner_backdoor.md
> +  ## Introduction
add a new line after intro and remove the spaces before the pounds
The lines after it don't look so hot in MD format either, mind taking a stab at cleaning them up (this was my module WAY back in the day, my how things have changed)

2018-02-03 02:51 UTC, h00die commented on documentation/modules/exploit/windows/fileformat/cve_2017_8464_lnk_rce.md
> +To set up the vulnerable environment, install a Windows version without the patch for CVE-2017-8464. To test the bypass, ensure that MS10-046 & MS15-020 are exploitable.
this sentence doesn't make much sense to me in general. There are no prior mentions in the docs to ms10-046 and a 'bypass' is only mentioned in the module info.  I think more info needs to be added to what we're bypassing, and why ms10 is relevant here.

2018-02-03 02:51 UTC, h00die commented on documentation/modules/post/windows/manage/archmigrate.md
> +- #### EXE
These don't follow the normal flow, should be **EXE**

2018-02-03 02:51 UTC, h00die commented on documentation/modules/post/windows/manage/archmigrate.md
> +- #### FALLBACK
These don't follow the normal flow, should be **FALLBACK**

2018-02-03 02:51 UTC, h00die commented on documentation/modules/post/windows/manage/archmigrate.md
> +- #### IGNORE_SYSTEM
These don't follow the normal flow, should be **IGNORE_SYSTEM**

2018-02-03 02:51 UTC, h00die commented
overall looks good, nice changes including on 2 of my own docs :).  I'll land soon as you get those minor changes made, thanks a bunch for this!!!!!

2018-02-03 02:54 UTC, cbrnrd commented
Thanks for the review :)  I'll change these by tomorrow morning.

2018-02-03 02:58 UTC, bcoles commented on documentation/modules/auxiliary/admin/smb/ms17_010_command.md
>  MS17-010 are psexec are two of the most popular exploits against Microsoft Windows. This module bolts the two together.
"MS17-010 and psexec"  ?

2018-02-03 02:58 UTC, bcoles commented on documentation/modules/auxiliary/gather/shodan_honeyscore.md
>  The `shodan_honeyscore` module utilizes the [Shodan](https://www.shodan.io/) API to determine whether or not a server is a honeypot or not.
`whether or not a server is a honeypot or not`

Repeated `or not`. Second instance is redundant.

2018-02-03 02:58 UTC, bcoles commented on documentation/modules/exploit/windows/fileformat/office_word_hta.md
>  Microsoft Office is an office suite of applications, servers, and services developed by Microsoft. Microsoft Office contains Microsoft Word, Microsoft Excel, Microsoft PowerPoint and so on. They can
`Virtusl Basic` ? Should be `Visual Basic` ?

`langauage` should be `language`

2018-02-03 16:52 UTC, cbrnrd commented on documentation/modules/exploit/windows/fileformat/cve_2017_8464_lnk_rce.md
> +To set up the vulnerable environment, install a Windows version without the patch for CVE-2017-8464. To test the bypass, ensure that MS10-046 & MS15-020 are exploitable.
Based on [this](https://www.cvedetails.com/cve/cve-2017-8464) and [this](https://www.rapid7.com/db/vulnerabilities/msft-cve-2017-8464), you aren't bypassing anything. Should the sentence just be removed?

2018-02-03 17:25 UTC, h00die commented on documentation/modules/exploit/windows/fileformat/cve_2017_8464_lnk_rce.md
> +To set up the vulnerable environment, install a Windows version without the patch for CVE-2017-8464. To test the bypass, ensure that MS10-046 & MS15-020 are exploitable.
https://www.rapid7.com/db/modules/exploit/windows/fileformat/cve_2017_8464_lnk_rce mentions bypassing a CPL (control panel?) Whitelist

2018-02-03 17:27 UTC, h00die commented on documentation/modules/exploit/windows/fileformat/cve_2017_8464_lnk_rce.md
> +To set up the vulnerable environment, install a Windows version without the patch for CVE-2017-8464. To test the bypass, ensure that MS10-046 & MS15-020 are exploitable.
@zeroSteiner any insight here?

2018-02-03 18:05 UTC, h00die approved these changes

2018-02-03 18:38 UTC, zeroSteiner commented on documentation/modules/exploit/windows/fileformat/cve_2017_8464_lnk_rce.md
> +To set up the vulnerable environment, install a Windows version without the patch for CVE-2017-8464. To test the bypass, ensure that MS10-046 & MS15-020 are exploitable.
Yeah, my understanding was that setting the folder ID in the `SpecialFolderDataBlock` to the Control Panel was causing the white list to be bypassed allowing an arbitrary CPL, (in the case of the module a DLL) to be loaded.

I don't see any reference to MS10-046 in either the fileformat or local variants of the module. IIRC, I didn't write the documentation for either of those so I'm not entirely sure how MS10-046 relates to them.

2018-02-04 17:58 UTC, cbrnrd commented
I removed the sentence we were having trouble with. Any other changes?

2018-02-04 18:48 UTC, h00die commented
I'm good with this, it can always be made better later if someone had something else.  At this point its a bunch of good changes.land coming shortly!

2018-02-04 18:55 UTC, merged

2018-02-04 19:02 UTC, h00die commented
# Release Notes
Updates to some spelling and grammar on docs, as well as consistency upgrades.

2018-02-04 19:03 UTC, h00die commented
@cbrnrd as always, thanks for the touch ups and changes.  Docs may not be sexy, but when something goes wrong and there aren't any its super aggravating!