Claymore Dual GPU Miner<= 10.5 dos
rapid7/metasploit-framework pull request #9512
Opened 2018-02-06 12:43 UTC by blue-bird1

This PR adds a module for  Claymore Dual GPU Miner<= 10.5 dos 

## Verification
- [ ]  install and run Claymore Dual GPU Miner
- [ ] Start `msfconsole`
- [ ] `use auxiliary/dos/tcp/claymore_dos`
- [ ]  `set rhost <rhost>`
- [ ]  `run`
- [ ]  Verify Miner program

2018-02-06 17:56 UTC, acammack-r7 requested changes
Thanks for the module! Just a couple things to change.

2018-02-06 17:56 UTC, acammack-r7 commented on modules/auxiliary/dos/tcp/claymore_dos.py
> +    exp = '''{"id": 1,"jsonrpc": "1.0","method": "%n"}'''
I think using `json.dumps({'id': 1, 'jsonrpc': '1.0', 'method': '%n'}).encode()` would be the more reliable way to write this.

2018-02-06 17:56 UTC, acammack-r7 commented on modules/auxiliary/dos/tcp/claymore_dos.py
> +        s.connect((host, port))
To support IPv6 and hostnames, we should use `socket.create_connection((host, port), 10)` instead of `socket` then `connect`. This also adds a timeout that prevents us from hanging if we can't reach the host.

2018-02-06 19:23 UTC, blue-bird1 commented on modules/auxiliary/dos/tcp/claymore_dos.py
> +    exp = '''{"id": 1,"jsonrpc": "1.0","method": "%n"}'''
It is good.But when It does not seem to work in python2. it is `str` type

2018-02-06 19:52 UTC, acammack-r7 commented on modules/auxiliary/dos/tcp/claymore_dos.py
> +    exp = '''{"id": 1,"jsonrpc": "1.0","method": "%n"}'''
I don't have a problem on my 2.7.10 install. What version of python 2 are you running and what traceback do you get?

2018-02-06 19:53 UTC, acammack-r7 approved these changes

2018-02-06 23:13 UTC, h00die commented on modules/auxiliary/dos/tcp/claymore_dos.py
> +        {'type': 'url', 'ref': 'https://www.exploit-db.com/exploits/43972/'},
Unless there's something different with python vs ruby modules, this can be type 'edb' and ref '43972'

2018-02-06 23:13 UTC, h00die commented on modules/auxiliary/dos/tcp/claymore_dos.py
> +        {'type': 'cve', 'ref': 'CVE-2018-6317'},
If python is handled like ruby, remove CVE- from the ref

2018-02-07 01:32 UTC, acammack-r7 commented on modules/auxiliary/dos/tcp/claymore_dos.py
> +        {'type': 'cve', 'ref': 'CVE-2018-6317'},
There's no difference here.

2018-02-07 01:32 UTC, acammack-r7 commented on modules/auxiliary/dos/tcp/claymore_dos.py
> +        {'type': 'url', 'ref': 'https://www.exploit-db.com/exploits/43972/'},
That should work

2018-02-16 16:47 UTC, merged

2018-02-16 16:48 UTC, busterb commented
## Release Notes

This adds a DoS module against Claymore Dual GPU Miner software versions <= 10.5.