Check for accessible named pipe on vuln targets
rapid7/metasploit-framework pull request #9618
Opened 2018-02-23 21:51 UTC by Auxilus

PoW

```
msf5 auxiliary(scanner/smb/smb_ms17_010) > run

[+] 192.168.0.2:445       - Host is likely VULNERABLE to MS17-010! - Windows 7 Ultimate 7601 Service Pack 1 x64 (64-bit)
[*] 192.168.0.2:445       - Checking for accessible named pipes
[+] 192.168.0.2:445       - Found accessible named pipe: netlogon
[+] 192.168.0.2:445       - Found accessible named pipe: lsarpc
[+] 192.168.0.2:445       - Found accessible named pipe: samr
[+] 192.168.0.2:445       - Found accessible named pipe: browser
[+] 192.168.0.2:445       - Found accessible named pipe: atsvc
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/smb/ms08_067_netapi`
- [ ] ...
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not
- [ ] **Document** the thing and how it works ([Example](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/multi/gather/aws_keys.md))

2018-02-23 21:57 UTC, wvu-r7 commented
This looks a lot like `pipe_auditor`. Consider consolidating the functionality into one place?

2018-02-23 21:58 UTC, Auxilus commented
You'd have to walk me through if you don't mind , sorry for the trouble

2018-02-23 22:00 UTC, Auxilus commented
I fount this pipe scanner code in ms17_010_eternalblue , copy pasted it to the scanner , and it worked....

2018-02-23 22:01 UTC, wvu-r7 commented
No worries. This was one of our to-dos from #9473.

2018-02-23 22:02 UTC, Auxilus commented
Yes ik :)

2018-02-23 22:04 UTC, wvu-r7 commented
You mean `lib/msf/core/exploit/smb/client/psexec_ms17_010.rb`? It was copied from `pipe_auditor`, IIRC.

What we should do is move the code into a general-purpose library and also add the ability to search for additional pipes, then rework the modules to use the consolidated code.

cc @zerosum0x0

2018-02-23 22:09 UTC, Auxilus commented
you mean adding it to `lib/msf/core/auxiliary` then include it where ever its needed?

2018-02-23 22:09 UTC, wvu-r7 commented
Probably a good idea to create `data/wordlists/named_pipes.txt`, too.

2018-02-23 22:11 UTC, Auxilus commented
Yeah,I can work on it tomorrow , its 4 am :)

2018-02-23 22:53 UTC, Auxilus commented
Looks like scanner should return more than one accessible named pipes, so do we have to modify `psexec_ms17_010.rb`?

Or just return the first accessible pipe name rather than returning array?

2018-02-23 23:29 UTC, ghost requested changes

2018-02-23 23:29 UTC, zerosum0x0 commented on modules/auxiliary/scanner/smb/smb_ms17_010.rb
> +        print_status("Checking for accessible named pipes")
make this print a vprint_status imo

2018-02-23 23:29 UTC, zerosum0x0 commented on modules/auxiliary/scanner/smb/smb_ms17_010.rb
> +                print_good("Found accessible named pipe: #{pipe}")
You can realistically end after the first named pipe here. But if you want to list them all, I'd comma separate them on a single line.

2018-02-23 23:29 UTC, zerosum0x0 commented on modules/auxiliary/scanner/smb/smb_ms17_010.rb
> +        end
maybe a vprint_status that no named pipe was found

2018-02-24 05:49 UTC, Auxilus commented
I've added rough code for the idea above

2018-02-24 05:51 UTC, Auxilus commented
There is a connection issue that I can't find origin of... 
![screenshot_20180224-111444](https://user-images.githubusercontent.com/23075789/36626208-aebd0c44-1954-11e8-8281-269ce6db3882.png)

2018-02-24 06:28 UTC, Auxilus commented
I'm getting `auxilus@termux:~/g/metasploit-framework > ./msfconsole                  ^[[A/data/data/com.termux/files/home/git/metasploit-framework/lib/msf/core/exploit/smb/client/psexec_ms17_010.rb:7:in `<module:Psexec_MS17_010>': uninitialized constant Msf::Auxiliary::PIPEAudit (NameError)`

2018-02-26 07:20 UTC, jmartin-r7 commented
Travis failures are for failing checks in `msftidy.rb`.   Please run locally and address any issues.

```
--- Checking new and changed module syntax with tools/dev/msftidy.rb ---
modules/auxiliary/scanner/smb/smb_ms17_010.rb:93 - [WARNING] Spaces at EOL
modules/auxiliary/scanner/smb/smb_ms17_010.rb:94 - [WARNING] Spaces at EOL
modules/auxiliary/scanner/smb/smb_ms17_010.rb:130 - [WARNING] Spaces at EOL
modules/auxiliary/scanner/smb/smb_ms17_010.rb:133 - [WARNING] Spaces at EOL
modules/auxiliary/scanner/smb/smb_ms17_010.rb:139 - [WARNING] Spaces at EOL
```

2018-02-26 14:53 UTC, Auxilus commented
The error I'm getting is
```
msf5 exploit(windows/smb/ms17_010_psexec) > exploit

[*] Started reverse TCP handler on 192.168.0.4:4444
[*] 192.168.0.5:445 - Target OS: Windows 7 Ultimate 7601 Service Pack 1
[-] 192.168.0.5:445 - NoMethodError
[-] 192.168.0.5:445 - undefined method `connect_to_pipe' for #<Msf::Modules::Mod6578706c6f69742f77696e646f77732f736d622f6d7331375f3031305f707365786563::MetasploitModule:0x0000007f8826db00>
Did you mean?  connect_timeout
[-] 192.168.0.5:445 - /data/data/com.termux/files/home/git/metasploit-framework/lib/msf/core/exploit/smb/client/psexec_ms17_010.rb:335:in `find_accessible_named_pipe'
/data/data/com.termux/files/home/git/metasploit-framework/lib/msf/core/exploit/smb/client/psexec_ms17_010.rb:37:in `eternal_pwn'
/data/data/com.termux/files/home/git/metasploit-framework/modules/exploits/windows/smb/ms17_010_psexec.rb:99:in `exploit'
/data/data/com.termux/files/home/git/metasploit-framework/lib/msf/core/exploit_driver.rb:206:in `job_run_proc'
/data/data/com.termux/files/home/git/metasploit-framework/lib/msf/core/exploit_driver.rb:167:in `run'
/data/data/com.termux/files/home/git/metasploit-framework/lib/msf/base/simple/exploit.rb:136:in `exploit_simple'
/data/data/com.termux/files/home/git/metasploit-framework/lib/msf/base/simple/exploit.rb:161:in `exploit_simple'
/data/data/com.termux/files/home/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/exploit.rb:110:in `cmd_exploit'
/data/data/com.termux/files/home/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:548:in `run_command'
/data/data/com.termux/files/home/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:510:in `block in run_single'
/data/data/com.termux/files/home/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `each'
/data/data/com.termux/files/home/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `run_single'
/data/data/com.termux/files/home/git/metasploit-framework/lib/rex/ui/text/shell.rb:208:in `run'
/data/data/com.termux/files/home/git/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/data/data/com.termux/files/home/git/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:48:in `<main>'
[*] Exploit completed, but no session was created.
```




Error is same when I run in Ubuntu

2018-03-08 20:44 UTC, Auxilus commented
```
auxilus@termux:~/d/metasploit-framework > ./msfconsole
/data/data/com.termux/files/home/doc/metasploit-framework/lib/msf/core/exploit/smb/client/psexec_ms17_010.rb:6:in `<module:Psexec_MS17_010>': uninitialized constant Msf::Auxiliary::PipeAudit (NameError)
```

2018-03-09 16:48 UTC, Auxilus commented
The changes are working now

2018-03-12 19:58 UTC, Auxilus commented
@wvu-r7 can you take a look at scanner module? Gives me connection reset error
Also see if other changes are needed. Thanks.

2018-03-20 07:55 UTC, busterb commented
@bwatters-r7 / @jmartin-r7 could we get a retest of the related modules here?

2018-03-26 22:02 UTC, merged

2018-03-26 22:04 UTC, wvu-r7 commented
558ecbcb4993776d1dfe6541167912de7eca4209
23a7444646f1829eb6aa9c2b25bd00c9551aa90d
e4c026fffd73183a53c908ffc40b977257311e43
09cb4a52df1b822f3040990ddb56e49e3bc9728c

2018-03-26 22:12 UTC, wvu-r7 commented
# Release Notes

This adds improvements to pipe auditing both to Framework core and the MS17-010 modules.

2018-03-26 22:13 UTC, busterb commented
👍 nice work!

2018-03-27 04:26 UTC, Auxilus commented
Thanks for the help @wvu-r7 @jmartin-r7 @busterb

2018-03-27 04:26 UTC, Auxilus commented
also @zerosum0x0

2018-03-27 05:04 UTC, wvu-r7 commented
You got it! Thanks for spearheading this!

2018-06-23 05:19 UTC, faizzaki212 commented
i scanned a host using auxiliary/scanner/smb/smb_ms17_010 then it says [+] host is likely vulnerable to ms17! but when i use all of the ms17 exploit, it doesn't work. my target is windows 7 ultimate pro and i'm running mac OSX sierra

2018-06-25 01:08 UTC, wvu-r7 commented
Please don't comment on old pull requests for support. Check this out: https://metasploit.com/help.