Add 2017-8917 RCE for Joomla 3.0.7
rapid7/metasploit-framework pull request #9666
Opened 2018-03-05 03:27 UTC by luisco

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/unix/webapp/joomla_comfields_sqli_rce`
- [ ] `set RHOST ...`
- [ ] `set TARGETURI ...`
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not
- [ ] **Document** the thing and how it works ([Example](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/multi/gather/aws_keys.md))

2018-03-06 13:40 UTC, jrobles-r7 commented
Please add module documentation. See [plugx.md](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/exploit/windows/misc/plugx.md) for an example.

2018-03-06 14:43 UTC, pbarry-r7 commented
Thanks for your contribution, @luisco.  Please fill out the above PR description and "verification steps" with relevant info (see other Metasploit Framework PRs as examples).

2018-03-07 01:46 UTC, luisco commented
I already added the documentation @jrobles-r7

2018-03-07 02:23 UTC, h00die requested changes

2018-03-07 02:23 UTC, h00die commented on documentation/modules/exploit/unix/webapp/joomla_sqli_rce_3_7_0.md
> +  This vulnerability can allow remote code execution.
With the SQLi, its possible to enumerate cookies of administrative users, and hijack one of their sessions.  If no administrators are authenticated, the RCE portion will not work.  If a session hijack is available, one of the website templates is identified, and our payload is added to the template as a new file, and then executed.

2018-03-07 02:23 UTC, h00die commented on documentation/modules/exploit/unix/webapp/joomla_sqli_rce_3_7_0.md
> +### Joomal 3.7.0 and an administrator must be authenticated in the backend
Joomla 3.7.0 on Ubuntu 16.04 with another user authenticated as an administrator

2018-03-07 02:23 UTC, h00die commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +        3.7.0.
I would expand this out to include what i commented in the docs

2018-03-07 02:23 UTC, h00die commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +    if res && res.body =~ /qpqjq(.*)qqqqq/
This would be relatively easy to catch on the network, can it be more dynamic for the flags on both ends?

2018-03-07 02:23 UTC, h00die commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +    # This way we make sure that's excluded and we only get real admin sessions.
+1 for descriptive comments

2018-03-07 02:23 UTC, h00die commented on documentation/modules/exploit/unix/webapp/joomla_sqli_rce_3_7_0.md
> +  This vulnerability can allow remote code execution.
admin or super user?

2018-03-07 02:23 UTC, h00die commented on documentation/modules/exploit/unix/webapp/joomla_sqli_rce_3_7_0.md
> +### Joomal 3.7.0 and an administrator must be authenticated in the backend
In the comments you mention Super User, here you mention administrator.  I'm not familiar with Joomla roles, but I'd assume there is a difference?

2018-03-07 02:23 UTC, h00die commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +    if res && res.code == 500 && res.body =~ /qpqjq(.*)qqqqq/
same as before, can these flags be randomized?

2018-03-07 02:23 UTC, h00die commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +    # Modify cookie to authenticated admin
as before, admin or super user?

2018-03-07 02:23 UTC, h00die commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +    auth_cookie << "="
single quotes

2018-03-07 02:23 UTC, h00die commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +    auth_cookie << ";"
single quotes

2018-03-07 02:23 UTC, h00die commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +      'uri'      => normalize_uri(target_uri.path, "administrator", "index.php"),
single quotes

2018-03-07 02:23 UTC, h00die commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +      'uri'      => normalize_uri(target_uri.path, "administrator", "index.php"),
single quotes

2018-03-07 02:23 UTC, h00die commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +      'uri'      => normalize_uri(target_uri.path, "administrator", "index.php"),
single quotes

2018-03-07 02:35 UTC, h00die commented
So after reading through this module, and having worked on wordpress exploits before, the whole time I was thinking that MUCH of this needs to be in the libraries.  There is too much goodness here to be simply limited to just this module and not shared elsewhere.

@luisco from a quick look over, good job.  I think the following may warrant being moved into the libs for other devs to use in the future (https://github.com/rapid7/metasploit-framework/tree/master/lib/msf/core/exploit/http/joomla):

- Getting templates: https://github.com/rapid7/metasploit-framework/pull/9666/files#diff-d2a5f154512ebd38558c6550d9f6f279R155
- Upload Template File: https://github.com/rapid7/metasploit-framework/pull/9666/files#diff-d2a5f154512ebd38558c6550d9f6f279R183 and https://github.com/rapid7/metasploit-framework/pull/9666/files#diff-d2a5f154512ebd38558c6550d9f6f279R237

With just these two what you'll basically be doing is making a template for others so that if ANY joomla module can get an admin auth cookie, theres now an easy path to RCE.

While not required to get this module landed, if you have the time and interest, I think that would make a big difference and save/encourage others to start writing some more Joomla modules.

2018-03-07 02:37 UTC, h00die requested changes

2018-03-07 02:37 UTC, h00die commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +      register_options(
can be removed in favor of including https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/exploit/http/joomla.rb as per previous comment

2018-03-07 02:37 UTC, h00die commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +
I would add an include for https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/exploit/http/joomla.rb

2018-03-09 02:39 UTC, h00die commented on documentation/modules/exploit/unix/webapp/joomla_sqli_rce_3_7_0.md
> +  This module exploits a SQL Injection vulnerability in the com_fields component which was introduced to the core of Joomla in version 3.7.0.
i'd wrap com_fields in ticks (`) since its a component and will help it stand out visually

2018-03-09 02:39 UTC, h00die commented on documentation/modules/exploit/unix/webapp/joomla_sqli_rce_3_7_0.md
> +  With the SQLi, its possible to enumerate cookies of administrative users, and hijack one of their sessions. If no administrators are authenticated, the RCE portion will not work. If a session hijac
its = it's

2018-03-09 02:39 UTC, h00die commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +          ['EDB', '42033'],
add spaces for consistency

2018-03-11 13:02 UTC, luisco commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +
Ready thanks

2018-03-27 20:40 UTC, jrobles-r7 reviewed
I'll try to use a generated string for the sqli check before merging this module and I'll include the other changes that haven't been implemented, which @h00die suggested.

2018-03-27 20:40 UTC, jrobles-r7 commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +    # Modify cookie to authenticated admin
From the testing I've done, this should be Super User. The module can retrieve Administrator cookies as well but the exploit will fail when it attempts to mess with templates using an Administrator's cookie.

2018-03-27 20:40 UTC, jrobles-r7 commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +    if res && res.body =~ /qpqjq(.*)qqqqq/
It looks like they are searching for this because they hardcoded it into the sqli check that was implemented. I'll attempt to modify this with generated text.

2018-03-27 20:40 UTC, jrobles-r7 commented on modules/exploits/unix/webapp/joomla_comfields_sqli_rce.rb
> +    if res && res.code == 200 && res.body =~ /Control Panel - Joomla - Administration/
The exploit was failing during my testing because of this check. If the site name is changed from `Joomla` to something else, then this check will fail even if you have successfully retrieved a Super User cookie.
Using `/Control Panel -(.*?)- Administration/` works.

2018-03-28 16:09 UTC, merged

2018-04-10 18:39 UTC, jrobles-r7 commented
# Release Notes
The exploit/unix/webapp/joomla_comfields_sqli_rce module exploits a SQL injection vulnerability in the com_fields component that was introduced  in Joomla 3.7.0. The module uses the injection to retrieve a Super User session cookie and then make requests as the Super User to gain code execution.