Slui File Handler Hijack LPE
rapid7/metasploit-framework pull request #9777
Opened 2018-03-28 18:44 UTC by gushmazuko

Slui File Handler Hijack LPE - MSF Module
UAC Bypass | Local Privilege Escalation Via Slui Hijack

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use exploit/windows/smb/ms08_067_netapi`
- [ ] ...
- [ ] **Verify** the thing does what it should
- [ ] **Verify** the thing does not do what it should not
- [ ] **Document** the thing and how it works ([Example](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/multi/gather/aws_keys.md))

2018-03-28 18:45 UTC, gushmazuko commented
Please view this module

2018-03-28 20:56 UTC, sempervictus requested changes
Thanks for getting this added, few suggestions on the PSH stuff, might have a few more on the module structure, but looks rational from here. Will merge test.

2018-03-28 20:56 UTC, sempervictus commented on modules/exploits/windows/local/bypassuac_sluihijack.rb
> +    psh_payload = Rex::Powershell::Payload.to_win32pe_psh_net(template_path, payload.encoded)
Do the other methods not work? MSIL doesn't require unsafe memory usage, so is less likely to trigger "smart" defenses.

2018-03-28 20:56 UTC, sempervictus commented on modules/exploits/windows/local/bypassuac_sluihijack.rb
> +    if psh_payload.length > CMD_MAX_LEN
We have memory stagers to deal with that issue

2018-03-28 20:56 UTC, sempervictus commented on modules/exploits/windows/local/bypassuac_sluihijack.rb
> +    psh_stager = "\"IEX (Get-ItemProperty -Path #{FODHELPER_WRITE_KEY.gsub('HKCU', 'HKCU:')} -Name #{payload_value}).#{payload_value}\""
Invoke-Expression is not well liked by AMSI, they think its for evil purposes. Suggest _&([scriptblock]::create((...))_, see [relevant Rex commit](https://github.com/rapid7/rex-powershell/commit/cb1a3c83202570aaa2fe8c667f180c124ca8982f) for examples.

2018-03-28 20:56 UTC, sempervictus commented on modules/exploits/windows/local/bypassuac_sluihijack.rb
> +    client.sys.process.execute(cmd_path, cmd_args, { 'Hidden' => true })
As mentioned with the memory stager piece, there's a post codepath for this with PSH which deals with a lot of the semantics for you.

2018-04-01 17:16 UTC, gushmazuko commented on modules/exploits/windows/local/bypassuac_sluihijack.rb
> +    psh_payload = Rex::Powershell::Payload.to_win32pe_psh_net(template_path, payload.encoded)
I just copied and changed the module "bypassuac_fodhelper.rb", because "bypassuac_sluihijack.rb" works very similar to him. The principle is the same. I don't know much about Ruby. But this module works good.

2018-04-02 14:51 UTC, jmartin-r7 commented
Please run `msftidy.rb` and address issues.

```
[*] Running msftidy.rb in ./.git/hooks/post-merge mode
--- Checking new and changed module syntax with tools/dev/msftidy.rb ---
modules/exploits/windows/local/bypassuac_sluihijack.rb - [ERROR] Incorrect disclosure date format
modules/exploits/windows/local/bypassuac_sluihijack.rb:37 - [WARNING] Spaces at EOL
```

2018-04-02 18:04 UTC, jmartin-r7 commented
Jenkins test this please.

2018-04-04 14:05 UTC, gushmazuko commented
Will you merge it?

2018-04-04 14:06 UTC, gushmazuko commented
Will you merge it?

2018-04-24 07:34 UTC, bcoles commented
Jenkins test this please

2018-05-10 12:26 UTC, gushmazuko commented
Is everything okay, will you merge it?

2018-05-11 01:36 UTC, bcoles commented on modules/exploits/windows/local/bypassuac_sluihijack.rb
> +    print_status("Cleaining up registry keys ...")
`Cleaning`

2018-05-11 01:36 UTC, bcoles commented on modules/exploits/windows/local/bypassuac_sluihijack.rb
> +    check_permissions!
Perhaps it would be worth moving this to the first line of the `exploit` method?

There's no point checking payload, above, unless we're going to proceed with exploitation.

2018-05-11 01:36 UTC, bcoles commented on modules/exploits/windows/local/bypassuac_sluihijack.rb
> +    # Check if you are an admin
It might be worth moving this `admin_group` check to after the `check` check below.

That way, it keeps the lines related to `admin_group` together. There's also no point checking if `admin_group` if the `check` method is just going to fail anyway.

Like this:

```ruby
    unless check == Exploit::CheckCode::Appears
      fail_with(Failure::NotVulnerable, "Target is not vulnerable.")
    end

    # Check if you are an admin
    vprint_status('Checking admin status...')
    admin_group = is_in_admin_group?
    unless is_in_admin_group?
      fail_with(Failure::NoAccess, 'Not in admins group, cannot escalate with this module')
    end
```

2018-05-11 01:36 UTC, bcoles commented on modules/exploits/windows/local/bypassuac_sluihijack.rb
> +      Exploit::CheckCode::Appears
Not a big deal, but `Exploit` is redundant here in `Exploit` context.

`CheckCode::Appears` is sufficient.

2018-05-11 01:36 UTC, bcoles commented on modules/exploits/windows/local/bypassuac_sluihijack.rb
> +
The whole `admin_group` check above is a bit confusing. Perhaps I'm reading it wrong, but there seems to be a lot of unnecessary duplicated conditionals.

`admin_group` is defined thusly:

`admin_group = is_in_admin_group?`

Then these conditionals are all one after each other:



```ruby
  fail_with unless is_in_admin_group?
  # ...
  if admin_group.nil?
  # ...
  else
    if admin_group
    # ...
    else
    # ...
    end
  end
```

2018-05-11 01:36 UTC, bcoles commented on modules/exploits/windows/local/bypassuac_sluihijack.rb
> +    unless check == Exploit::CheckCode::Appears
This `check` does not related to checking permissions. It would be best to move this conditional to the first line of the `exploit` method to ensure exploitation does not continue unless we're targeting the right operating system.

2018-05-23 16:19 UTC, bwatters-r7 commented on modules/exploits/windows/local/bypassuac_sluihijack.rb
> +    psh_payload = Rex::Powershell::Payload.to_win32pe_psh_net(template_path, payload.encoded)
@sempervictus the only references I can find to `MSIL` are in spec files and a reference to:
`modules/post/multi/manage/shell_to_meterpreter.rb:                        fail RuntimeError, 'MSIL Powershell method no longer exists'`
Is that something old?

2018-05-23 17:16 UTC, bwatters-r7 commented on modules/exploits/windows/local/bypassuac_sluihijack.rb
> +
Hrm.... this is because `is_in_admin_group?` returns true,false, or nil.  Also, this is straight from fodhelper.  I think I'm going to compress this and fix both/all to make it a bit more readable.

2018-05-28 09:58 UTC, gushmazuko reviewed
I think I did everything. Please check.

2018-05-28 09:58 UTC, gushmazuko commented on modules/exploits/windows/local/bypassuac_sluihijack.rb
> +
@bwatters-r7 you are right!

2018-05-30 20:23 UTC, merged