cleanup psexec code
rapid7/metasploit-framework pull request #9881
Opened 2018-04-16 08:18 UTC by Auxilus

This PR moves some psexec methods to psexec mixin, also reworked ms17_010 modules to use this code.

2018-04-17 16:24 UTC, wvu-r7 commented
You now have mixin methods that rely on datastore options existing solely within the modules. You will need to rework the methods, move the options into the mixin, or **at least** document the options within the mixin.

This is precisely the problem with moving module methods into a mixin. Mixins should not rely on the modules that use them. That's just poor design!

2018-04-17 16:28 UTC, Auxilus commented
thanks for the review, I'll fix it...

2018-04-18 17:04 UTC, jmartin-tech requested changes
Having done an initial review this will require significant rework to be acceptable in master.

2018-04-18 17:04 UTC, jmartin-r7 commented on lib/msf/core/exploit/smb/client/psexec.rb
> +  def report_auth
This method does not belong in the `psexec` mixin.  A mixin should have a defined purpose and only provide methods associated with that purpose.

2018-04-18 17:04 UTC, jmartin-r7 commented on lib/msf/core/exploit/smb/client/psexec.rb
> +    filename = datastore['SERVICE_FILENAME'] || "#{rand_text_alpha(8)}.exe"
more optional `datastore` parameters assumed but not registered by this mixin.  Here and below as `SERVICE_STUB_ENCODER`, `SHARE`

2018-04-18 17:04 UTC, jmartin-r7 commented on lib/msf/core/exploit/smb/client/psexec.rb
> +      exe = generate_payload_exe_service(opts)
This method comes from `msf/core/exploit/exe` again a mixin that is not directly required it is included by your change here but is currently out of scope if the module include this mixin does not already provide it.

2018-04-18 17:04 UTC, jmartin-r7 commented on lib/msf/core/exploit/smb/client/psexec.rb
> +    mof = generate_mof(mofname, filename)
This method is from `WbemExec` mixin again included above but not required so not in scope.

2018-04-18 17:09 UTC, Auxilus commented
thanks for the review @jmartin-r7 , I'll go over them and work on asap

2018-04-18 17:36 UTC, Auxilus commented on lib/msf/core/exploit/smb/client/psexec.rb
> +    case datastore['SHARE'].upcase
In some modules the share option is `SMBSHARE` (like in auxiliary/admin/smb/psexec_command)
while some have `SHARE` opt.
which one do we go with? cz any changes may affect other modules that include psexec mixin which are not in this PR.

2018-04-18 19:57 UTC, jmartin-r7 commented on lib/msf/core/exploit/smb/client/psexec.rb
> +    case datastore['SHARE'].upcase
This is an example of why `datastore` options are often not the first choice to use in mixin methods. See the existing `smb_read_file()`, it takes the `smbshare, host, file` as parameters to enable it to act as a utility method vs making assumptions about the state of the module.

2018-04-22 20:33 UTC, sempervictus commented
The data store deps are awful, thanks for fixing. One does have to wonder how this impacts out-of-tree modules? Maybe an msf5 tag?

2018-04-23 18:36 UTC, jmartin-r7 commented
@sempervictus scope looks fairly well defined, we are working thru the changes to limit side-effects on the methods.  This should keep functionality stable and hopefully maintain the compatibility at an API level with the existing mixin.

For now I would like to see this make it into 4.x. If I find something that breaks compatibility I'll add the `msf5` label.

2018-04-24 17:59 UTC, jmartin-tech requested changes
Another pass of things that need some thought.

2018-04-24 17:59 UTC, jmartin-r7 commented on lib/msf/core/exploit/smb/client/psexec.rb
> +    case datastore['SHARE'].upcase
This should now be `smb_share`.

2018-04-24 17:59 UTC, jmartin-r7 commented on lib/msf/core/exploit/smb/client/psexec.rb
> +  def get_output(file, smb_share, r_ip)
I am not sure this makes sense as an exposed method.  While it generates some log messages that are specific to a goal all it really does is call `smd_read_file` with those log messages wrapped around it.

Looking at the code where this is called, a more interesting method might be `execute_command_with_output(text, bat, cmd, smb_share, r_ip)`  that does the full execute, obtains the result and preforms the cleanup in one method.

```
def execute_command_with_output(text, bat, cmd, smb_share, r_ip)
    res = execute_command(text, bat, cmd)

    if res
      for i in 0..(datastore['RETRY'])
        Rex.sleep(datastore['DELAY'])
        # if the output file is still locked then the program is still likely running
        if (exclusive_access(text, smb_share, r_ip))
          break
        elsif (i == datastore['RETRY'])
          print_error("Command seems to still be executing. Try increasing RETRY and DELAY")
        end
      end
      get_output(text, smb_share, r_ip)
    end

    cleanup_after(text, bat, smb_share, r_ip)
```

Note that there are issues with the example method above as it is just the segment of code duplication that could be extracted here.  Things like `datastore` usage may need to be evaluated to make this work.  However this would allow `get_output()`,  `exclusive_access()` and `cleanup_after()` if not used externally anymore to be made private methods of the mixin.

2018-04-24 17:59 UTC, jmartin-r7 commented on lib/msf/core/exploit/smb/client/psexec.rb
> +    def powershell
This method needs documentation, it looks like it should be renamed something like `execute_powershell_payload()`.

2018-04-25 07:12 UTC, Auxilus commented
I've also tested the changes, all the modules seem to work..

2018-04-25 14:49 UTC, jmartin-r7 commented on lib/msf/core/exploit/smb/client/psexec.rb
> +    servicename = datastore['SERVICE_NAME'] || rand_text_alpha(8)
This is not needed just call local method `service_name` to keep consistent.

2018-04-25 14:49 UTC, jmartin-r7 commented on lib/msf/core/exploit/smb/client/psexec.rb
> +      file_location = smb_share.slice(0,1) +  ":\\#{filename}"
Should this set of `if` statements use `smb_share` as provided by the caller or local `smbshare` as generated earlier in the method?

2018-04-25 18:11 UTC, wvu-r7 commented
This looks a lot better, thanks!

2018-04-25 21:12 UTC, jmartin-r7 commented on lib/msf/core/exploit/smb/client/psexec.rb
> +    def execute_powershell_payload
Whitespace fix, please check format balance for the whole file.

2018-04-25 21:12 UTC, jmartin-r7 commented on lib/msf/core/exploit/smb/client/psexec.rb
> +  def exclusive_access(*files, smb_share, r_ip)
`exclusive_access`, `get_output` and `cleanup_after` should be made private now.  Either by moving them to the end of the file after a `private` keyword or by adding the restriction inside the class scope around L439
```
private :exclusive_access
private :get_output
private :cleanup_after
```

See https://en.wikibooks.org/wiki/Ruby_Programming/Syntax/Classes#Private

2018-04-26 23:18 UTC, jmartin-tech requested changes

2018-04-27 05:08 UTC, Auxilus commented
I've got some errors while testing `ms17_010_command`

```
msf5 auxiliary(admin/smb/ms17_010_command) > run                        [-] Auxiliary failed: Msf::OptionValidateError The following options failed to validate: DELAY.
msf5 auxiliary(admin/smb/ms17_010_command) > set delay 1                delay => 1
msf5 auxiliary(admin/smb/ms17_010_command) > run                        
[*] 192.168.1.36:445      - Target OS: Windows 7 Ultimate 7601 Service Pack 1                                                                   [*] 192.168.1.36:445      - GROOM_POOL_SIZE: 0x5030
[*] 192.168.1.36:445      - BRIDE_TRANS_SIZE: 0xfa0
[*] 192.168.1.36:445      - CONNECTION: 0xfffffa8003f76600              [*] 192.168.1.36:445      - SESSION: 0xfffff8a010161960
[*] 192.168.1.36:445      - FLINK: 0xfffff8a00f66b088
[*] 192.168.1.36:445      - InParam: 0xfffff8a00f66515c                 [*] 192.168.1.36:445      - MID: 0x1008
[*] 192.168.1.36:445      - Built a write-what-where primitive...
[*] 192.168.1.36:445      - Session Data: 0a02d80000000000e09df40480faffff010000000000000090a8f60b80f8ffff90a8f60b80f8ffff07000000000000000066f70380faffff00000000000000000000000000000000000000000000000000000000000000006a62fc93e5ddd30191a73c94e5ddd301ff3f96d536ffff7fffffffffffffff7f000000000000000006c31d00000000004c4dc65fa744ce758cb13ff349f71cad0000000000000000a0390d10a0f8ffff04110200000800000200000001010100000000010000000000000000000000001900000000000000000000000000000045004d00330032005c004b00450052004e0045004c0042004100530045002e0044004c004c000000
[*] 192.168.1.36:445      - session dat len = 256                       [*] 192.168.1.36:445      - Session ctx offset = a0
[*] 192.168.1.36:445      - Session ctx data = a0390d10a0f8ffff04110200000800000200000001010100000000010000000000000000000000001900000000000000000000000000000045004d00330032005c004b00450052004e0045004c0042004100530045002e0044004c004c000000
[*] 192.168.1.36:445      - secCtxAddr: fffff8a0100d39a0
[*] 192.168.1.36:445      - Reading secCtxData from fffff8a0100d39a0
[*] 192.168.1.36:445      - Read data from secCtx: 2a0228000300000003000000000000001030eb0fa0f8ffff00000000000000000000000000000000
[+] 192.168.1.36:445      - Overwrite complete... SYSTEM session obtained!
[+] 192.168.1.36:445      - Service start timed out, OK if running a command or non-service executable...
[*] 192.168.1.36:445      - checking if the file is unlocked
[*] 192.168.1.36:445      - Unable to get handle: The server responded with error: STATUS_SHARING_VIOLATION (Command=45 WordCount=0)
[*] 192.168.1.36:445      - checking if the file is unlocked
[*] 192.168.1.36:445      - Unable to get handle: The server responded with error: STATUS_SHARING_VIOLATION (Command=45 WordCount=0)
[-] 192.168.1.36:445      - Command seems to still be executing. Try increasing RETRY and DELAY
[*] 192.168.1.36:445      - Getting the command output...
[*] 192.168.1.36:445      - Executing cleanup...
[+] 192.168.1.36:445      - Cleanup was successful
[+] 192.168.1.36:445      - Command completed successfuly!
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

2018-04-27 05:12 UTC, Auxilus commented
output on master pulled code

``
[*] 192.168.1.36:445      - Obtaining a service manager handle...
[*] 192.168.1.36:445      - Creating the service...
[+] 192.168.1.36:445      - Successfully created the service
[*] 192.168.1.36:445      - Starting the service...
[+] 192.168.1.36:445      - Service start timed out, OK if running a command or non-service executable...
[*] 192.168.1.36:445      - Removing the service...
[+] 192.168.1.36:445      - Successfully removed the service
[*] 192.168.1.36:445      - Closing service handle...
[*] 192.168.1.36:445      - checking if the file is unlocked
[-] 192.168.1.36:445      - Unable to get handle: The server responded with error: STATUS_SHARING_VIOLATION (Command=45 WordCount=0)
[-] 192.168.1.36:445      - Command seems to still be executing. Try increasing RETRY and DELAY
[*] 192.168.1.36:445      - Getting the command output...
[+] 192.168.1.36:445      - Command completed successfuly!
[*] 192.168.1.36:445      - Output for "time":
The current time is: 10:40:40.07
Enter the new time:
[*] 192.168.1.36:445      - Executing cleanup...
[-] 192.168.1.36:445      - Unable to cleanup \WINDOWS\Temp\KTNqFYTEjjWxcxYM.txt. Error: The server responded with error: STATUS_SHARING_VIOLATION (Command=6 WordCount=0)
[-] 192.168.1.36:445      - Unable to cleanup. Maybe you'll need to manually remove true, false from the target.
[+] 192.168.1.36:445      - SYSTEM session cleaned up.
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

2018-04-27 05:15 UTC, Auxilus commented
It does give output in verbose => true

maybe change `vprint_line` to `print_line`?

2018-04-27 05:24 UTC, Auxilus commented
```
msf5 auxiliary(admin/smb/ms17_010_command) > set command cd
command => cd
msf5 auxiliary(admin/smb/ms17_010_command) > run

[*] 192.168.1.36:445      - Target OS: Windows 7 Ultimate 7601 Service Pack 1
[*] 192.168.1.36:445      - Built a write-what-where primitive...
[+] 192.168.1.36:445      - Overwrite complete... SYSTEM session obtained!
[+] 192.168.1.36:445      - Service start timed out, OK if running a command or non-service executable...
[*] 192.168.1.36:445      - checking if the file is unlocked
[*] 192.168.1.36:445      - Getting the command output...
[*] 192.168.1.36:445      - Executing cleanup...
[+] 192.168.1.36:445      - Cleanup was successful
[+] 192.168.1.36:445      - Command completed successfuly!
[*] 192.168.1.36:445      - Output for "cd":

C:\Windows\system32

[*] Scanned 1 of 1 hosts (100% complete) 
[*] Auxiliary module execution completed
msf5 auxiliary(admin/smb/ms17_010_command) >
```

2018-04-27 15:23 UTC, jmartin-tech approved these changes

2018-04-30 23:41 UTC, merged

2018-04-30 23:42 UTC, jmartin-r7 commented
## Release Notes

Common functionality of psexec modules has been consolidated into the smb/client/psexec mixin.